### ISSUE TITLE
System.Diagnostics.Process methods failing for MAC OSX version of netcore.

### ISSUE THREAD

**Issue by speed2048** [dotnet/coreclr#1000]
When I use System.DIagnostics.Process methods I get the following Exceptions. Methods used:

Process[] process = Process.GetProcesses (); or
 Process[] localByName = Process.GetProcessesByName("processname");

Exception: 

svr-mac-mini-001:test bob_mcmillan$ dnx --debug . run
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(UInt64 value)
   at System.Diagnostics.ProcessManager.CreateProcessInfo(Int32 pid)
   at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
   at System.Diagnostics.Process.GetProcesses(String machineName)
   at Program.Main(String[] args)

**Comment by stephentoub** [comment]
This is: https://github.com/dotnet/corefx/issues/1538

cc: @sokket

**Comment by stephentoub** [comment]
This was fixed in https://github.com/dotnet/corefx/issues/2185

**Comment by bodhichina** [comment]
@stephentoub  i try run below code under macos  10.13.2, looks nothing happend. can you help to check what's wrong 

>     var info=new ProcessStartInfo()
            { 
                FileName = "/Applications/Safari.app/Contents/MacOS/safari",
                CreateNoWindow = false,
                UseShellExecute = false
            };
            
            var process=new Process(){ StartInfo = info};
            process.Start();

**Comment by stephentoub** [comment]
@bodhichina, please open a new issue in corefx.  That's not related to this issue.
