### ISSUE TITLE
Long CORECLR_GDBJIT env variable 

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/coreclr#10003]
Current gdbjit feature seems not to support very long(>= 1024) CORECLR_GDBJIT variable(https://github.com/dotnet/coreclr/blob/master/src/vm/gdbjit.cpp#L1742). 
Is there any reason to check max length of this env variable ?

**Comment by chunseoklee** [comment]
CC @kvochko @Dmitri-Botcharnikov

**Comment by Dmitri-Botcharnikov** [comment]
@chunseoklee It was assumed that this variable holds the path of assembly to debug. However currently it holds list of assembly file names, so this check can be eliminated.

**Comment by chunseoklee** [comment]
@Dmitri-Botcharnikov Thank you.
