### ISSUE TITLE
CoreClr does not build with the latest lttng-ust-dev package available on Alpine

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/coreclr#10007]
If you try to build CoreClr on Alpine using the following Dockerfile it will fail.  This used to work as suggested in https://github.com/dotnet/coreclr/issues/917#issuecomment-263030347.  It looks like this is because lttng-ust-dev is currently at version 2.9.0-r0.  It works if you use lttng-ust-2.8.1-r0 (built from source).  2.8.1-r0 no longer appears to be available from https://dl-cdn.alpinelinux.org/alpine/edge/testing.
```
# Alpine does not produce x.y.z tags therefore a sha must
# be used to get a specific version (Alpine 3.4.3)
FROM sha256:7d23b3ca3463ae7d682961a1a07c1ec96d51fbbae90bef79207fad7385d4cb1e

ENV __PUBLISH_RID ubuntu.14.04-x64

RUN apk update

RUN apk add --no-cache \
        autoconf \
        bash \
        build-base \
        clang \
        clang-dev \
        cmake \
        curl-dev \
        gcc \
        gettext-dev \
        git \
        icu-dev \
        krb5-dev \
        libtool \
        linux-headers \
        llvm \
        make \
        python \
        zlib-dev

RUN apk -X https://dl-cdn.alpinelinux.org/alpine/edge/main add --no-cache \
        libunwind-dev \
        util-linux-dev

RUN apk -X https://dl-cdn.alpinelinux.org/alpine/edge/testing add --no-cache \
        lldb-dev \
        lttng-ust-dev

RUN apk add --no-cache ca-certificates \
    && update-ca-certificates \
    && apk add openssl
```

Build Error
```
2017-03-03T00:59:20.5942010Z [ 71%] Building CXX object src/md/compiler/dbi/CMakeFiles/mdcompiler-dbi.dir/__/classfactory.cpp.o
2017-03-03T00:59:20.5966530Z /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../liblttng-ust.so: undefined reference to `sched_getcpu'
2017-03-03T00:59:20.5983270Z /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../liblttng-ust.so: undefined reference to `pthread_setname_np'
2017-03-03T00:59:20.6050740Z clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
2017-03-03T00:59:21.2164540Z make[2]: *** [src/pal/tests/palsuite/eventprovider/eventprovidertest] Error 1
2017-03-03T00:59:21.2180340Z src/pal/tests/palsuite/eventprovider/CMakeFiles/eventprovidertest.dir/build.make:101: recipe for target 'src/pal/tests/palsuite/eventprovider/eventprovidertest' failed
2017-03-03T00:59:21.2197280Z CMakeFiles/Makefile2:60626: recipe for target 'src/pal/tests/palsuite/eventprovider/CMakeFiles/eventprovidertest.dir/all' failed
2017-03-03T00:59:21.2211970Z make[1]: *** [src/pal/tests/palsuite/eventprovider/CMakeFiles/eventprovidertest.dir/all] Error 2
2017-03-03T00:59:21.2224530Z make[1]: *** Waiting for unfinished jobs....
```

This issue was discovered while rebuilding the docker images used in official builds.

cc @janvorli, @mellinoe

**Comment by janvorli** [comment]
@MichaelSimons I'll take a look.

**Comment by janvorli** [comment]
@MichaelSimons FYI, I've tried to build docker image from the docker file you've provided above, but docker complains:
`Error: image library/sha256:7d23b3ca3463ae7d682961a1a07c1ec96d51fbbae90bef79207fad7385d4cb1e not found`
Replacing the sha:xxxxx with alpine:3.4 allowed me to build the image.

I can repro the problem, but it seems it is problem of the liblttng-ust.so itself and not ours. Just checking the dependencies of the liblttng-ust.so with ldd shows that, as you can see below. There are no sched_getcpu and pthread_setname_np on Alpine.
```
bash-4.3# ldd /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../liblttng-ust.so
        ldd (0x7fad89147000)
        liblttng-ust-tracepoint.so.0 => /usr/lib/liblttng-ust-tracepoint.so.0 (0x7fad88cc6000)
        liburcu-bp.so.4 => /usr/lib/liburcu-bp.so.4 (0x7fad88abf000)
        liburcu-cds.so.4 => /usr/lib/liburcu-cds.so.4 (0x7fad888b8000)
        libc.musl-x86_64.so.1 => ldd (0x7fad89147000)
        liburcu-common.so.4 => /usr/lib/liburcu-common.so.4 (0x7fad886b4000)
Error relocating /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../liblttng-ust.so: pthread_setname_np: symbol not found
Error relocating /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../liblttng-ust.so: sched_getcpu: symbol not found
```

**Comment by MichaelSimons** [comment]
@janvorli, sorry about the FROM syntax error, FWIW 'FROM alpine@sha256:02eb5cfe4b721495135728ab4aea87418fd4edbfbf83612130a81191f0b2aae3' should work.

**Comment by janvorli** [comment]
I have reported that to Alpine as a bug

**Comment by janvorli** [comment]
https://bugs.alpinelinux.org/issues/6989

**Comment by janvorli** [comment]
It actually doesn't have this problem if we use alpine:edge image instead of alpine 3.4. The musl in the edge contains the required exports.
However, it also brings in clang 4.0 and it turns out we cannot build with clang 4.0. There are multiple errors reported in #11159.

**Comment by janvorli** [comment]
This issue doesn't exist anymore. With Alpine 3.6 and the relatively recent #13052, the native parts of CoreCLR build on Alpine fine again.

**Comment by am11** [comment]
@janvorli, if feasible, can Alpine Linux build plan be added to Jenkins to validate its status?

**Comment by janvorli** [comment]
@am11 I am planning to do that. I am currently finalizing the end to end Alpine support, so that will be a follow up step.
