### ISSUE TITLE
dnx-coreclr-linux-x64.1.0.0-beta5-11781 fails with 17FC System.DllNotFoundException

### ISSUE THREAD

**Issue by jsacapdev** [dotnet/coreclr#1002]
Running in a docker container, With DNX_TRACE=1:

```
root@9b00b8a2e425:/app# ./SimpSamp
Loaded Module: dnx.coreclr.so
Found DLL Export: CallApplicationMain

17FC System.DllNotFoundException: 170B
   at Interop.mincore.GetStdHandle(Int32 nStdHandle)
   at System.Console.<>c__DisplayClass0.<get_Error>b__5()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at dnx.host.RuntimeBootstrapper.PrintErrors(Exception ex)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
   at DomainManager.Execute(Int32 argc, Char** argv)
root@9b00b8a2e425:/app# dnvm list
```

dnvm list

```
Active Version              Runtime Arch Location             Alias
1.0.0-beta5-11781    coreclr x64  ~/.dnx/runtimes/runtimes default
```

**Comment by kangaroo** [comment]
You have the windows version of System.Console.

**Comment by xPaw** [comment]
Hitting the same.

**Comment by yaakov-h** [comment]
Same here, OS X, 1.0.0-beta5-11781.

`dnx` won't even run without command-line arguments:

    ] dnx
    
    Resource string id=0x17FC System.DllNotFoundException: Resource string id=0x170B
       at Interop.mincore.GetStdHandle(Int32 nStdHandle)
       at System.Console.<>c__DisplayClass0.<get_Error>b__5()
       at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
       at dnx.host.RuntimeBootstrapper.PrintErrors(Exception ex)
       at dnx.host.RuntimeBootstrapper.Execute(String[] args)
       at DomainManager.Execute(Int32 argc, Char** argv)

`fs_usage` shows that dnx is looking for `libcoreclr`, and finding it:

    19:29:31  stat64            dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-beta5-11781/bin/libcoreclrpal.dylib    0.000003   dnx         
    19:29:31  stat64            v/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-beta5-11781/bin/libcoreclr.dylib    0.000004   dnx         
    19:29:31  open              v/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-beta5-11781/bin/libcoreclr.dylib    0.000005   dnx         
    19:29:31  stat64            /yaakov/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-beta5-11781/bin/libcoreclr    0.000016   dnx         
    19:29:31  stat64            /yaakov/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-beta5-11781/bin/libcoreclr    0.000002   dnx   

Here's the full `fs_usage` output, grepped for `dnx`: https://gist.github.com/yaakov-h/b17fa945c94fdfa8b90e

Most likely, the DLL that it can't find is `api-ms-win-core-processenvironment-l1-1-0.dll`, which as far as I know is part of the Windows API (Win32).

**Comment by Starcounter-Jack** [comment]
Same here

**Comment by Starcounter-Jack** [comment]
I can confirm the same error on a clean OS X installation of Beta5-11781. I.e. it should not be related to a  corrupt installation.

**Comment by ellismg** [comment]
Thanks for bringing this up.  It looks like there are some issues with the daily builds that we hand off to the ASP.NET team, which is causing us to not include the platform specific versions of some assemblies in the DNX package.

We are working on a fix, and hopefully it will be addressed in either tomorrow's build or the next day.  I'll post here when it's fixed.

**Comment by pedromig** [comment]
I am getting the same error in version 1.0.0-beta5-11855 and 1.0.0-beta5-11893 on both mac and linux.

**Comment by joachim-isaksson** [comment]
Same issue still present in 1.0.0-beta5-11904/coreclr on Mac (and on Debian 8)

    $ dnvm list

    Active Version              Runtime Arch Location             Alias
    ------ -------              ------- ---- --------             -----
      *    1.0.0-beta5-11904    coreclr x64  ~/.dnx/runtimes      c
           1.0.0-beta5-11904    mono         ~/.dnx/runtimes      d, default

    $ dnu

    Resource string id=0x17FC System.DllNotFoundException: Resource string id=0x170B
       at Interop.mincore.GetStdHandle(Int32 nStdHandle)
       at System.Console.<>c__DisplayClass0.<get_Error>b__5()
       at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
       at dnx.host.RuntimeBootstrapper.PrintErrors(Exception ex)
       at dnx.host.RuntimeBootstrapper.Execute(String[] args)
       at DomainManager.Execute(Int32 argc, Char** argv)

**Comment by cnblogs-dudu** [comment]
Same issue [dnx/issues#1955](https://github.com/aspnet/dnx/issues/1955)

**Comment by xPaw** [comment]
> We are working on a fix, and hopefully it will be addressed in either tomorrow's build or the next day.

@ellismg, any news on this?

**Comment by mstum** [comment]
Broken on OS X as well - 1.0.0-beta6-11944. Version 1.0.0-beta5-11657 worked.

**Comment by weinand** [comment]
coreclr is now broken on OS X for three weeks. When can we expect a fix?

**Comment by justinwyer** [comment]
same problem with 1.0.0-beta6-11944 on linux

**Comment by troydai** [comment]
Hi all, I'm sorry for the frustration. There were some breaking changes internally in past weeks. We, ASP.Net team and CLR team are working hard to close the gap and get latest build online. We're expecting to get a fix this week. I'll let you know once we make more progress.

Thanks for patience. Stay tuned.

**Comment by cheers00** [comment]
I guess we have to wait for the next build, I too seeing the same problem. dnu restore only creates lock file and doesn't download any components.

I ran HelloWorld program without any problems by following steps at https://github.com/dotnet/coreclr/blob/master/Documentation/linux-instructions.md.

But I am getting the following error for DNX.https://github.com/dotnet/coreclr/blob/master/Documentation/get-dotnetcore-dnx-linux.md

 I am using the latest beta6 coreclr and mono bits. dnu restore with mono was successful but I only see project.lock.json file created and I didn't get any other files.

dnu restore
```
@UbuntuLVM:~/dotnet$ dnu restore
Microsoft .NET Development Utility Mono-x64-1.0.0-beta5-11904
 Restoring packages for /home/user1dotnet/project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console'
Writing lock file /home/user1/dotnet/project.lock.json
Restore complete, 433ms elapsed
```

Error
```
 dnvm list
 
Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
       1.0.0-beta5-11904    coreclr x64  ~/.dnx/runtimes      
       1.0.0-beta5-11781    coreclr x64  ~/.dnx/runtimes      
  *    1.0.0-beta6-11944    coreclr x64  ~/.dnx/runtimes      
       1.0.0-beta6-11944    mono         ~/.dnx/runtimes      
       1.0.0-beta5-11904    mono         ~/.dnx/runtimes      default
       1.0.0-beta5-11781    mono         ~/.dnx/runtimes      

@UbuntuLVM:~/dotnet$ dnx . run 
17FC System.DllNotFoundException: 170B
   at Interop.mincore.GetStdHandle(Int32 nStdHandle)
   at System.Console.<>c__DisplayClass0.<get_Error>b__5()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at dnx.host.RuntimeBootstrapper.PrintErrors(Exception ex)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
   at DomainManager.Execute(Int32 argc, Char** argv)
```

**Comment by joachim-isaksson** [comment]
12005 no longer gives me the same error and seems to once again run my simple samples. 

Thanks for your hard work, all! :)

**Comment by cheers00** [comment]
12005?

**Comment by joachim-isaksson** [comment]
@cheers00 Sorry, was (a bit too) short for 1.0.0-beta6-12005/CoreCLR which seems to no longer have the issue with "Resource string id=0x17FC System.DllNotFoundException: Resource string id=0x170B".

**Comment by davidfowl** [comment]
Thanks for the patience :smile:

**Comment by jsacapdev** [comment]
back in business...thanks all for your help...
