### ISSUE TITLE
[x86/Linux] HFA tests failure

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#10027]
Failed Tests

 - JIT/jit64/hfa/main/testE/hfa_nd2E_r/hfa_nd2E_r.sh
 - JIT/jit64/hfa/main/testE/hfa_nf2E_d/hfa_nf2E_d.sh
 - JIT/jit64/hfa/main/testE/hfa_nf2E_r/hfa_nf2E_r.sh
 - JIT/jit64/hfa/main/testE/hfa_sd2E_d/hfa_sd2E_d.sh
 - JIT/jit64/hfa/main/testE/hfa_sd2E_r/hfa_sd2E_r.sh
 -  JIT/jit64/hfa/main/testE/hfa_sf2E_d/hfa_sf2E_d.sh
 - JIT/jit64/hfa/main/testE/hfa_sf2E_r/hfa_sf2E_r.sh
 - JIT/jit64/hfa/main/testE/hfa_sf2E_d/hfa_sf2E_d.sh
 - JIT/jit64/hfa/main/testE/hfa_sf2E_r/hfa_sf2E_r.sh

% All of these have a native function with RetBuf. Crashes when we P/Invoke it.

Error message

```
FAILED   - [ 5702 :    3 sec ] JIT/jit64/hfa/main/testE/hfa_nd2E_d/hfa_nd2E_d.sh
               BEGIN EXECUTION
               /root/dotnet-test/coreclr_unittest_20170228_083238_x86_x86-emu/coreclr-unittest-170227-233308/overlay/corerun hfa_nd2E_d.exe
               ./hfa_nd2E_d.sh: line 131:  7932 Segmentation fault      (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" hfa_nd2E_d.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 139
               END EXECUTION - FAILED
```

```
Program received signal SIGSEGV, Segmentation fault.
0xf4f17f0d in identity_HFA01 (hfa=...)
    at /var/jenkins/workspace/CLR/x86_Dbg_RT/repo/code/tests/src/JIT/jit64/hfa/main/dll/hfa_native.cpp:118
118     /var/jenkins/workspace/CLR/x86_Dbg_RT/repo/code/tests/src/JIT/jit64/hfa/main/dll/hfa_native.cpp: No such file or directory.
(gdb) i r
eax            0x3f800000       1065353216
ecx            0x3f800000       1065353216
edx            0xf4f64ac3       -185185597
ebx            0xffffd298       -11624
esp            0xffffc928       0xffffc928
ebp            0xffffc928       0xffffc928
esi            0x8087300        134771456
edi            0xffffc948       -14008
eip            0xf4f17f0d       0xf4f17f0d <identity_HFA01(HFA01)+13>
eflags         0x10286  [ PF SF IF RF ]
cs             0x23     35
ss             0x2b     43
ds             0x2b     43
es             0x2b     43
fs             0x0      0
gs             0x63     99
(gdb) disassemble identity_HFA01
Dump of assembler code for function identity_HFA01(HFA01):
   0xf4f17f00 <+0>:     push   %ebp
   0xf4f17f01 <+1>:     mov    %esp,%ebp
   0xf4f17f03 <+3>:     mov    0x8(%ebp),%eax
   0xf4f17f06 <+6>:     mov    %eax,%ecx
   0xf4f17f08 <+8>:     lea    0xc(%ebp),%edx
   0xf4f17f0b <+11>:    mov    (%edx),%edx
=> 0xf4f17f0d <+13>:    mov    %edx,(%eax)
   0xf4f17f0f <+15>:    mov    %ecx,%eax
   0xf4f17f11 <+17>:    pop    %ebp
   0xf4f17f12 <+18>:    ret    $0x4
End of assembler dump.
```

At the point it crashed, EAX must have been the address of return buffer. However EAX is 0x3f800000 which is 1.0 as float. Seems like calling convention problem.

cc: @janvorli @jkotas @parjong

**Comment by wateret** [comment]
About calling convention

As far as I understand default calling convention for JITd(managed) method is:

* ECX, EDX for first and second argument
* more arguments are pushed onto stack.

However it looks unfamiliar to me when there is a RetBuf argument in (static) method:

* ECX for RetBuf
* arguments other than RetBuf are pushed onto stack (EDX unused)

It works fine for managed code but fails when when we P/Invoke native functions. For native functions on x86/Linux, all arguments including RetBuf are pushed onto stack.

What would be the issue for this? Is the calling convention for methods with RetBuf correct? I also think `IL_Stub_PInvoke` could be an issue.

**Comment by janvorli** [comment]
@wateret 
>ECX, EDX for first and second argument

This is not correct. The correct statement is ECX and EDX for the first two arguments that can be passed in registers. So, if you have a managed function void fn(long a, int b, long c, int d), the first argument is passed on stack, the second in ECX, the third on stack and the fourth in EDX.

**Comment by wateret** [comment]
@janvorli Thank you. It explains "EDX unused case" since float arguments cannot be passed via registers.

**Comment by wateret** [comment]
It turns out that only `identity_HFA01` and `identity_HFA02` are problematic. HFA structs bigger than them work fine.

[Definition of struct HFA01 and HFA02](https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/jit64/hfa/main/dll/hfa_common.cs#L115-L125)

[Identity_HFA** function definition](https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/jit64/hfa/main/dll/hfa_native.cpp#L117-L123)

Here are assembly code for calling those functions including argument push.

**Call Identity_HFA01**

* Pushes first argument on stack
* Return by EAX (without RetBuf)

```
       8B45F0       mov      eax, dword ptr [ebp-10H]
       50           push     eax
       E8DAFDFFFF   call     ConsoleApplication.Program:Identity_HFA01(struct):struct
```

**Call Identity_HFA02**

* Set ECX as RetBuf
* Pushes all arguments(of 8 bytes) on stack

```
       F30F7E45E8   movq     xmm0, qword ptr [ebp-18H]
       83EC08       sub      esp, 8
       660FD60424   movq     dword ptr [esp], xmm0
       8D4DBC       lea      ecx, bword ptr [ebp-44H]
       E88EFDFFFF   call     ConsoleApplication.Program:Identity_HFA02(struct):struct
```

**Comment by janvorli** [comment]
@wateret just a little correction to what you've said:
> It explains "EDX unused case" since float arguments cannot be passed via registers.

In our case, we are not passing a float, but a struct containing a float. But the effect is the same.

**Comment by wateret** [comment]
For the case of calling `Identity_HFA02`:

Let's say the calling conventions
* A : ECX and EDX for the first two arguments that can be passed in registers, others via stack
* B : All arguments passed via stack (native code expects B)

Here's what I think, since the structs bigger than HFA02 works `to-be` way.

```
as-is : (Managed Code) --A--> (IL_STUB_PInvoke) --A--> (Native Code)
to-be : (Managed Code) --A--> (IL_STUB_PInvoke) --B--> (Native Code)
```

**Comment by wateret** [comment]
To summary the analysis so far, the error occurs when P/Invoke to a native function that has RetBuf argument and the struct size is less than 8 bytes.

[BOOL IsUnmanagedValueTypeReturnedByRef(UINT sizeofvaluetype)](https://github.com/dotnet/coreclr/blob/master/src/vm/i386/cgencpu.h#L482) looks suspicious.

**Comment by janvorli** [comment]
@wateret I guess the IsUnmanagedValueTypeReturnedByRef is most likely the issue. It seems that for Unix x86, it should always return true.

**Comment by wateret** [comment]
@janvorli Thank you, I agree. With `IsUnmanagedValueTypeReturnedByRef` returning always true, I still get the same error (no changes of `IL_STUB_PInvoke` JITd code). I think we need another fix as well as this fix.

**Comment by wateret** [comment]
I found that HFA02 doesn't get to below `if` block. while structs bigger than HFA02 success. Seems like HFA02 is pmCallConvCdecl.

```
In NDirect::PopulateNDirectMethodDesc at dllimport.cpp

4368 #ifdef _TARGET_X86_
4369     if (ndirectflags & NDirectMethodDesc::kStdCall)
4370     {
4371         // Compute the kStdCallWithRetBuf flag which is needed at link time for entry point mangling.
4372         MetaSig msig(pNMD);
4373         ArgIterator argit(&msig);
4374         if (argit.HasRetBuffArg())
4375         {
4376             MethodTable *pRetMT = msig.GetRetTypeHandleThrowing().AsMethodTable();
4377             if (IsUnmanagedValueTypeReturnedByRef(pRetMT->GetNativeSize()))
4378             {
4379                 ndirectflags |= NDirectMethodDesc::kStdCallWithRetBuf;
4380             }
4381         }
4382     }
4383 #endif // _TARGET_X86_
```

**Comment by wateret** [comment]
Compared identity_HFA02 to identity_HFA03,

When `PInvokeStaticSigInfo::DllImportInit()` calls 
`pInternalImport->GetPinvokeMap(pMD->GetMemberDef(), (DWORD*)&mappingFlags, ppEntryPointName, &modref)`, the result of `mappingFlags` values differ.

identity_HFA02 mappingFlags : 0x200 (pmCallConvCdecl)
identity_HFA03 mappingFlags : 0x300 (pmCallConvStdcall)

These two functions do same thing but the only difference is  size of struct.
@janvorli Can I ask what would make this difference? I'm not sure where the value of mappingFlags comes from.

**Comment by janvorli** [comment]
@wateret this is very strange, both of the functions should use the stdcall calling convention since they both have attribute specifying that:
```c#
        [DllImport(Config.DllName, EntryPoint = "identity_HFA02", CallingConvention = CallingConvention.StdCall)]
        public static extern HFA02 Identity_HFA02(HFA02 hfa);

        [DllImport(Config.DllName, EntryPoint = "identity_HFA03", CallingConvention = CallingConvention.StdCall)]
        public static extern HFA03 Identity_HFA03(HFA03 hfa);

```
