### ISSUE TITLE
gdbjit.cpp is inconsistent in using new and new (nothrow)

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#10033]
There are about 40 usages of new (nothrow) and about 14 throwing news without any particular reason. We should unify it.

**Comment by janvorli** [comment]
cc: @lucenticus, @ayuckhulk, @kvochko, @Dmitri-Botcharnikov

**Comment by ayuckhulk** [comment]
I'll look into this.

In some places there are also no error handling paths (for failed `new (nothrow)` case) so its also should be fixed.

@janvorli  Am I correct that it's better to use `(nothrow)` everywhere?

**Comment by janvorli** [comment]
@ayuckhulk in fact, I would prefer the opposite, using throwing new and then wrap the entry point functions in try / catch. That would remove some code churn caused by checking for nullptr and make the code easier to read.
I think that the only entry points are NotifyGdb::MethodCompiled and NotifyGdb::MethodDropped, right?
Maybe some of the code will need to be hardened against the oom exceptions so that no memory leaks and no data structures are left in an inconsistent state. The code already uses NewArrayHolder and NewHolder at many if not all places, which takes automatically care of releasing the memory in case of an exception.

**Comment by ayuckhulk** [comment]
@janvorli  I think we can close this issue.
