### ISSUE TITLE
dll reference support in .NET Core projects

### ISSUE THREAD

**Issue by bartstinson** [dotnet/coreclr#10035]
Hello, 

It's my understanding that prior VS 2017, it was impossible to add other .NET Core dll references to .NET Core projects without bundling the dependency in a NuGet package. In VS 2017, I see that the option to add dll references using the IDE but when I run it, the program fails to find the dependent dlls. Is the adding of dll references really now supported in VS 2017 for .NET Core projects or do we still have to go through NuGet?

Thanks

**Comment by danmosemsft** [comment]
I'm not sure where this goes, but I"ll move it to CLI who can put it right.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/cli #5954](https://github.com/dotnet/cli/issues/5954) via [**ZenHub**](https://www.zenhub.com/)
