### ISSUE TITLE
JIT: recognize/optimize Span<T> bounds checks more like array bounds checks

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/coreclr#10050]
Array bounds checks are inserted by the jit at ldelem operations, and internally we use the `GenTreeBoundsChk` operator to represent them.  This operator may raise an exception and so has exceptional flow, but not normal flow (doesn't split blocks).  Span<T> bounds checks, by contrast, are user-written compare/branch/throw sequences.  It would be handy to shape the span bound check IR more like the array bound check IR (by pattern-matching it, or by making the Span<T> indexer an intrinsic whose bounds checks the JIT is responsible for materializing, or adding attributes like [Bound] (which would apply to the length field) and [BoundsChecked] (which would apply to methods taking an index) to make the JIT more generally responsible for materializing span bounds checks).  This would both simplify modifying our bound-check-targeting optimizations like range check elim at spans and help anywhere that split blocks make our optimizations conservative (e.g. loop hoisting).

**Comment by mikedn** [comment]
> or adding attributes like [Bound] (which would apply to the length field) and [BoundsChecked] (which would apply to methods taking an index)

How would the index method parameter be identified? Assumed to be the first/single `int` parameter? This attribute based solution sounds interesting (though perhaps over complicated) as it may apply to `Slice(int start)` as well. But Slice has an `(int start, int length)` overload, I wonder what, if anything, should be done about that.

**Comment by JosephTremoulet** [comment]
> How would the index method parameter be identified?  Assumed to be the first/single int parameter?

Yes, that's what I was imagining, or `BoundsCheckedAttribute` could be parameterized by an `int parameterIndex`.

**Comment by russellhadley** [comment]
Keep in 2.0 for Span on Kestrel.

**Comment by ahsonkhan** [comment]
@JosephTremoulet, any updates on this issue?

**Comment by JosephTremoulet** [comment]
> @JosephTremoulet, any updates on this issue?

Just that the idea came up in offline discussion that if we have the IndexOutOfBoundsException be raised by something that can be recognized by the JIT as an intrinsic (perhaps a direct call to the associated CORINFO helper func?), then recognizing the pattern of such a call in a block that is conditionally called based on an unsigned compare would be something the JIT could do with reasonable complexity/speed, which makes it my favorite choice for how to implement this since it also leaves flexibility in how Span and friends are implemented in runtime/library sources.

**Comment by AndyAyersMS** [comment]
If we convert the indexer into an intrinsic (as Jan suggests over in #10031) we can simply generate whatever extra annotations/canonical format the jit needs. Not sure if there are any other bounds-check cases that are as significant so perhaps this is all the special casing we need.

**Comment by JosephTremoulet** [comment]
Sure, if we want to make the indexer an intrinsic anyway, that would simplify this.  One notable non-indexer API with bounds checking is Slice, but I'd guess that indexing is more frequently what's happening in the sort of inner loops where removing a bounds check can really be critical.

**Comment by AndyAyersMS** [comment]
Ok, I am going to work up some intrinsics for the Span and ReadOnlySpan indexers. Once it is a bit further along, I'll circle back and we can figure out the right expansion for the bounds check.

**Comment by AndyAyersMS** [comment]
Bounds check is now expressed like an array bounds check, via #10910. 

These checks are still not optimized away as well as corresponding array cases, though some optimization does kick in here and there.

**Comment by JosephTremoulet** [comment]
I'm currently working through the SpanBench test post-#10910 to see what it will take to get the rest of the checks optimized like the corresponding array cases.

**Comment by JosephTremoulet** [comment]
When assertion prop is deciding what assertions to generate, and is considering compares that may prove bounds checks redundant, it only does so when the compare is a function of an array length, and fortunately array lengths (except for known constant ones, which are handled separately) have value numbers whose opcode is arrlen.  For the span case, we'll start out with field loads, then in the good case promote them to locals, and often copy prop something else into the local's spot.  So the VNs are not so easy to spot.  My plan has been to have value numbering flag the VNs that show up as argument to bounds checks (in the length position) and have assertion prop consider those interesting.  Doing that much gets rid of the bounds check in TestIndexer3, but not the others.  Since the other have different conservative value numbers for the lengths before CSE, getting them depends on #9615, specifically the part where the cseArrLenMap is used... the cseArrLenMap is populated based on the VNs, but before we've rewritten CSEs, so it's a problem to have only the VNs used in bounds checks flagged at that point; what we really want are the VNs that *will* be used in bounds checks *after* CSE...

**Comment by JosephTremoulet** [comment]
#11521 brings the array bound check removal machinery in the jit optimizer to bear on spans.  I've opened #11785 to track a potential future improvement identified while working on #11521, but I think it's correct to consider this issue resolved now.
