### ISSUE TITLE
Add back calls to GetTypeInfo in Span<T> tests

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/coreclr#10052]
I had to remove the calls to GetTypeInfo in the Span perf tests.  This was because the call to GetTypeInfo was ambiguous between the real location in System.Reflection and in the newly added TraceEvent library.  Luckily, we never end up using the call to GetTypeInfo so for now I have commented out the code, so that we can go ahead and check in the xunit performance changes.

**Comment by jorive** [comment]
@DrewScoggins I have pushed to myget the updated .NET Core TraceEvent library with the fix. It is the one with version 1.0.1-alpha-experimental.

**Comment by ahsonkhan** [comment]
@DrewScoggins, any updates on this issue?

**Comment by danmosemsft** [comment]
@DrewScoggins ?

**Comment by DrewScoggins** [comment]
I looked at both files in the Span directory, and neither of them have GetTypeInfo commented out.  So I am closing this issue as it is no longer relevant.
