### ISSUE TITLE
[CoreFx:System.Net.Sockets.Tests] BCL Assert at System.ArraySegment`1.get_Array()

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#10077]
dotnet/corefx@4451feeeda61ddd558a9d45d6320f50540c2693f
3b36244d78c244b137205b8e81be7346600e7c81

CoreCLR x64 Checked
python tests\scripts\run-corefx-tests.py -build_type Checked

```
Discovering: System.Net.Sockets.Tests
Discovered:  System.Net.Sockets.Tests
Starting:    System.Net.Sockets.Tests
Assert Failure
Expression: BCL Assert
Description: ArraySegment is invalid
Stack Trace:
   at System.ArraySegment`1.get_Array()
   at System.Net.Sockets.Tests.SendReceiveSync.<>c__DisplayClass3_0.<ReceiveAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Finished running tests.  End time=17:00:02.42, Exit code = -2146232797
```

**Comment by RussKeldorph** [comment]
@stephentoub @geoffkizer FYI.  Note this is testing corefx HEAD versus coreclr HEAD.

**Comment by stephentoub** [comment]
I'd argue these asserts are invalid and should just be deleted; I'll do so tomorrow unless anyone objects. That we're able to hit the asserts by constructing invalid instances in the corefx tests highlights that. Granted, we're doing so via a union rather than its ctor, but still.

**Comment by geoffkizer** [comment]
If I'm understanding you correctly, you are basically saying that struct state has absolutely no integrity whatsoever because you can always circumvent it with LayoutKind.Explicit and FieldOffset.  Is that correct?

If so, then removing the asserts makes sense.  But I really hope that isn't the case.  Because as a user of .NET, I find it incredibly unsettling that supposedly "safe" code can fiddle with my struct state in arbitrary ways.

**Comment by geoffkizer** [comment]
Moveover, given this, it seems like #16715 is a serious security vulnerability and we need to provide downlevel patches for this.

**Comment by stephentoub** [comment]
> If I'm understanding you correctly, you are basically saying that struct state cannot be trusted because you can always circumvent it with LayoutKind.Explicit and FieldOffset. Is that correct?

In coreclr/corefx, yes, I believe we need to validate the contents of an ArraySegment before we use unsafe code to manipulate the contents in a way that could corrupt state if the contents were invalid, just as we would do if the byte[], int, and int were passed to us through any other means.

**Comment by stephentoub** [comment]
Also note that it doesn't require someone using Explicit / FieldOffset.  Imagine an ArraySegment stored in a field, and someone has a race condition in their program where one thread writes to the ArraySegment field at the same time another is reading it to pass it to one of our APIs.  An ArraySegment is not going to be read/written atomically and is subject to torn reads/writes.
