### ISSUE TITLE
[Arm64][GCStress 0x3] Test Failures

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#10070]
Test Failures

<pre>
baseservices/compilerservices/dynamicobjectproperties/Dev10_535767/Dev10_535767.cmd
CoreMangLib/cti/system/gc/GCCollect/GCCollect.cmd
</pre>

Test Output

<pre>
Output: TEST_CMD_LINE: baseservices\compilerservices\dynamicobjectproperties\Dev10_535767> C:\Users\DDJOIN\arm64_ci\tests\baseservices\compilerservices\dynamicobjectproperties\Dev10_535767\Dev10_535767.cmd
BEGIN EXECUTION
"C:\Users\DDJOIN\arm64_ci\tests\Tests\Core_Root\corerun.exe" Dev10_535767.exe
Running test TS:Unconnected CS:None 10000 entries...
Running test TS:Unconnected CS:Alternate 10000 entries...
Running test TS:Unconnected CS:Random 10000 entries...
Running test TS:Unconnected CS:All 10000 entries...
Running test TS:ForwardLinked CS:None 10000 entries...
Running test TS:ForwardLinked CS:Alternate 10000 entries...
Running test TS:ForwardLinked CS:Random 10000 entries...
Running test TS:ForwardLinked CS:All 10000 entries...
Running test TS:BackwardLinked CS:None 10000 entries...
Running test TS:BackwardLinked CS:Alternate 10000 entries...
Running test TS:BackwardLinked CS:Random 10000 entries...
Running test TS:BackwardLinked CS:All 10000 entries...
</pre>

<pre>
Output: TEST_CMD_LINE: CoreMangLib\cti\system\gc\GCCollect> C:\Users\DDJOIN\arm64_ci\tests\CoreMangLib\cti\system\gc\GCCollect\GCCollect.cmd
BEGIN EXECUTION
"C:\Users\DDJOIN\arm64_ci\tests\Tests\Core_Root\corerun.exe" GCCollect.exe
Beginning test case GCCollect at 3/9/2017 8:38:35 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
[Positive]
Beginning scenario: PosTest1: Call Collect to reclaim memories
ERROR!!!-001.1: GC.Collect does not work
WARNING [LOCAL VARIABLE] beforeCollect = 734736, afterCollect = 797768
Ending test case at 3/9/2017 8:57:27 AM
FAIL
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
</pre>

**Comment by BruceForstall** [comment]
Closing this as a dup of https://github.com/dotnet/coreclr/issues/15381
