### ISSUE TITLE
[x86/Linux] SIMD and GT_OBJ

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#10080]
While working with #10012, I get an assert fail in lower.cpp line about 975
```C++
#ifdef FEATURE_PUT_STRUCT_ARG_STK
        // If the ArgTabEntry indicates that this arg is a struct
        // get and store the number of slots that are references.
        // This is later used in the codegen for PUT_ARG_STK implementation
        // for struct to decide whether and how many single eight-byte copies
        // to be done (only for reference slots), so gcinfo is emitted.
        // For non-reference slots faster/smaller size instructions are used -
        // pair copying using XMM registers or rep mov instructions.
        if (info->isStruct)
        {
            // We use GT_OBJ for non-SIMD struct arguments. However, for
            // SIMD arguments the GT_OBJ has already been transformed.
            if (arg->gtOper != GT_OBJ)
            {
                assert(varTypeIsSIMD(arg)); <------ this fails
            }
            else
```
Currenrly x86/Linux does not use SIMD and thus `varTypeIsSIMD()` would return false no mater what the case. I'd like to know how to fix in this case.

**Comment by seanshpark** [comment]
CC @BruceForstall @YongseopKim

**Comment by seanshpark** [comment]
If surround with `#ifdef FEATURE_SIMD,` there are several other assert places.

**Comment by janvorli** [comment]
@seanshpark why do you think we are not using SIMD on x86? The disass that @parjong has just posted in #10059 shows we do.

**Comment by seanshpark** [comment]
@janvorli , do you mean this line?
```
IN00da:        movsd    qword ptr [esp], xmm0
```
Then I'm more confused cause `FEATURE_SIMD` is only turned on for AMD64 or x86 Windows, in src/jit/CMakeLists.txt
```
if (CLR_CMAKE_TARGET_ARCH_AMD64 OR (CLR_CMAKE_TARGET_ARCH_I386 AND NOT CLR_CMAKE_PLATFORM_UNIX))
  add_definitions(-DFEATURE_SIMD)
  add_definitions(-DFEATURE_AVX_SUPPORT)
endif ()
```
and in src/jit/vartype.h
```
#ifdef FEATURE_SIMD
template <class T>
inline bool varTypeIsSIMD(T vt)
{
    switch (TypeGet(vt))
    {
        case TYP_SIMD8:
        case TYP_SIMD12:
        case TYP_SIMD16:
#ifdef FEATURE_AVX_SUPPORT
        case TYP_SIMD32:
#endif // FEATURE_AVX_SUPPORT
            return true;
        default:
            return false;
    }
}
#else  // FEATURE_SIMD

// Always return false if FEATURE_SIMD is not enabled
template <class T>
inline bool varTypeIsSIMD(T vt)
{
    return false;
}
#endif // !FEATURE_SIMD
```
so `varTypeIsSIMD` always returns false.

**Comment by seanshpark** [comment]
When `assert(varTypeIsSIMD(arg));` fires, `arg` type is GT_LCL_VARS.
```
late:
======
lowering arg : N030 (  3,  2) [000751] ------------             *  lclVar    struct V52 tmp23  

Assert failure(PID 5450 [0x0000154a], Thread: 5450 [0x154a]):
Assertion failed 'varTypeIsSIMD(arg)' in 
'System.Reflection.RuntimeParameterInfo:GetParameters(ref,ref,ref,byref,bool):ref' (IL size 444)
```

But the code and comment doesn't match with this (GT_LCL_VARS)
```
        if (info->isStruct)
        {
            // We use GT_OBJ for non-SIMD struct arguments. However, for
            // SIMD arguments the GT_OBJ has already been transformed.
            if (arg->gtOper != GT_OBJ)
            {
                assert(varTypeIsSIMD(arg));
            }
```

**Comment by BruceForstall** [comment]
It looks like the code expects a struct `arg` to be `GT_OBJ` or a `GT_SIMD` node. I'm not sure where this should get transformed to `GT_OBJ`. Perhaps you could look at what Windows/x64 does by looking at that JitDump (I wouldn't suggest looking at Linux/x64 because the ABI is so weird).

I might suggest telling me during which test this happens, but I assume it depends on a bunch of work you haven't merged yet.

**Comment by seanshpark** [comment]
@BruceForstall , thank you for looking into this issue. Test is simple helloworld console output program and this happened with #10034 patches. I've just uploaded `Fix FieldList offset` fix that solved this issue. This fix corrects offset of ESP when there are more than two long arguments.
Before the fix code generation
```
# for first long
mov [esp+04H], edx
mov [esp], eax
# for the second long
mov [esp+04H], edx
mov [esp], eax
```
and after the fix
```
# for first long
mov [esp+0cH], edx
mov [esp+08H], eax
# for the second long
mov [esp+04H], edx
mov [esp], eax
```
There was no considering `putArgStk->gtSlotNum` as current x86 just uses `push` instruction.
Because of this problem, wrong argument was passed and that lead to misguided assertion.

**Comment by seanshpark** [comment]
I think this issue can be closed.
