### ISSUE TITLE
ConfigureAwait does nothing?

### ISSUE THREAD

**Issue by borrrden** [dotnet/coreclr#10082]
I ran into this unusual problem when running a unit test with xUnit.  I noticed the thread before I `await`ed an `async` call and the thread when I was done were different.  Ok, I guess this makes sense after reading about `SynchronizationContext`.  However, the weird part is that things are continuing on the same thread that the `async` task was running on.  That thread is reserved for processing async jobs, and so any blocking after the await in the original test code will cause that processing to lock.

My implementation of this is [here](https://github.com/couchbase/couchbase-lite-net/blob/feature/api-v2/src/Couchbase.Lite/Support/SerialQueue.cs#L136).  Roughly, it adds some logic to a queue and sets the result of a `TaskCompletionSource` when it is done.  In terms of what I am saying above, the logic gets executed in `ProcessAsync` and then the test code continues **on the same thread that ProcessAsync is running**

I inspected the `SynchronizationContext` of the thread at start, and determined that it is an XUnit library provided instance of [AsyncTaskMethodContext](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/AsyncTestSyncContext.cs).

If I understand correctly, without `ConfigureAwait(false)` the async state machine should post back to the original context when it is finished with its logic.  In that case, this instance (I inspected `innerContext` to be null) will call [XunitWorkerThread.QueueUserWorkItem](https://github.com/xunit/xunit/blob/vs2017/src/common/XunitWorkerThread.cs#L29) which just adds to a default constructure `TaskFactory` instance.  That seems to me that it should run on yet another thread and not the same one as before since the one from before is still executing stuff.

I thought maybe the default changed to `ConfigureAwait(false)` so I tried running `ConfigureAwait(true)` but the behavior was the same.  Is this a bug or the new behavior?

**Comment by stephentoub** [comment]
When you write code like:
```C#
var result = await t;
```
that logically translates into something like:
```C#
var $awaiter = t.GetAwaiter();
if (!$awaiter.IsCompleted)
{
    ... // stuff to hook up a continuation
    return;
}
Label:
var result = $awaiter.GetResult();
```
so if the thing you await is already completed by the time you await it, you will continue running synchronously on the same thread.  This has always been the behavior, and ConfigureAwait doesn't influence that, i.e. ConfigureAwait doesn't force the await to always complete asynchronously, but rather controls the continuation behavior if it does complete asynchronously.

**Comment by stephentoub** [comment]
Separately, in your code, Task.Factory.StartNew by default targets the current TaskScheduler, and it's up to the current TaskScheduler how to interpret and handle TaskCreationOptions.LongRunning.  If your intent here is to force a new thread to be created as happens for LongRunning with the default scheduler, you should explicitly pass TaskScheduler.Default as the scheduler argument to StartNew; otherwise, if the context in which you're running has a TaskScheduler set up, you may not get the behavior you want (of course, maybe that's exactly what you want, but just wanted to call it out).

**Comment by gkhanna79** [comment]
Issue moved to [dotnet/corefx #16973](https://github.com/dotnet/corefx/issues/16973) via [**ZenHub**](https://www.zenhub.com/)
