### ISSUE TITLE
CI: non-Windows r2r stress tests fail

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#10094]
All the non-Windows r2r stress tests failed with this:
```
ERROR: Failed to run DSL Script
java.util.concurrent.ExecutionException: com.cloudbees.plugins.flow.JobNotFoundException: Item dotnet_coreclr/master/x64_checked_windows_nt_r2r_jitstressregs0x10_bld_prtest not found (or isn't a job).
```

I saw this in #10039

**Comment by BruceForstall** [comment]
@RussKeldorph

**Comment by gkhanna79** [comment]
@BruceForstall Is this because of https://github.com/dotnet/coreclr/issues/10093?

**Comment by BruceForstall** [comment]
I don't know how flow jobs work, but my guess is the answer is no.

**Comment by gkhanna79** [comment]
@BruceForstall Is this still active?

**Comment by BruceForstall** [comment]
@gkhanna79 Yes, the issue still exists as far as I know.

**Comment by RussKeldorph** [comment]
@rartemev I'm not sure if this is just a bug in netci.groovy or something else.  If you don't know where to begin, let me know.

**Comment by rartemev** [comment]
Fixed
