### ISSUE TITLE
Fix Spanbench benchmark tests for fast span to be more reliable and meaningful

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/coreclr#10099]
https://github.com/dotnet/coreclr/tree/master/tests/src/JIT/Performance/CodeQuality/Span

We’ve identified a few things that we should change in the benchmark code itself: 
a.	The old tests were accidentally commented out, and the new tests can’t be run from the command line (they can only be run through xunit-perf).  We should be able to run all the tests, both from command line and xunit-perf
b.	We should do something to make sure the computations in the inner loops aren’t dead.  I’ll look into options to do this in a way that won’t unduly hamper bounds check removal optimizations
c.	In the tests as originally written, the PerfTestFoo methods are generic, so their calls to Span methods are generic-to-generic, so we pay extra overhead with T=String (since both the PerfTestFoo code and the Span code get shared) to do dictionary lookups.  In the tests as they’re checked in to coreclr, the PerfTestFoo methods are no longer generic.  Maybe we want to find a way to use generics again to make sure that pattern gets tested?

**Comment by gkhanna79** [comment]
@ahsonkhan Who should this be assigned to?

**Comment by ahsonkhan** [comment]
Most likely to me :)

**Comment by ahsonkhan** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/10216
