### ISSUE TITLE
[Arm64][1-Failure] managed\Compilation\Compilation\Compilation.cmd

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#10108]
Expected Output:

<pre>
BEGIN EXECUTION
 "C:\Users\DDJOIN\proyectos\febrero-2-2017\pruevas\tests2\Core_Root\corerun.exe" Compilation.exe
Starting the test
Using reference to: C:\Users\DDJOIN\proyectos\febrero-2-2017\pruevas\tests2\Core_Root\System.Private.CoreLib.dll
Test compiled
Expected: 100
Actual: -1
END EXECUTION - FAILED
FAILED
</pre>

**Comment by sdmaclea** [comment]
@jashook I did not see this failure in todays pri1 [Arm64/Unix] run

**Comment by jashook** [comment]
I have verified this passes on master.

**Comment by jashook** [comment]
When the arm64 ci is back online I will pr to start running it in automation.
