### ISSUE TITLE
[arm64][1-Failure] Regressions\coreclr\GitHub_7685\Test7685\Test7685.cmd fails

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#10107]
Expected Output

<pre>
BEGIN EXECUTION
 "C:\Users\DDJOIN\proyectos\febrero-2-2017\pruevas\tests2\Core_Root\corerun.exe" Test7685.exe
Error: passing struct with floats via reflection. Callee received [1.2, 5.6, -3.768694E-10, 2.481916E-05] instead of [1.2, 3.4, 5.6, 7.8]
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
</pre>

**Comment by gkhanna79** [comment]
@jashook Is this is a codegen issue?

**Comment by gkhanna79** [comment]
Thoughts on this @jashook ?

**Comment by jashook** [comment]
Upon first glance this looks like a codegen issue. Adding it to area codegen.

**Comment by jashook** [comment]
This is a vm bug related to enregistering structs when invoking into a reflected method.

**Comment by jashook** [comment]
Still assigned to me, I believe I have a fix.

**Comment by jashook** [comment]
Fixed with #10257
