### ISSUE TITLE
[Arm64][2-Failures] String Failures

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#10115]
Tests
<pre>
CoreMangLib/cti/system/string/StringFormat1/StringFormat1.cmd
CoreMangLib/cti/system/string/StringFormat2/StringFormat2.cmd
</pre>

Output
<pre>
20:19:29 Started: Fri Mar 10 19:52:34 2017
20:19:29 Started: Fri Mar 10 19:52:35 2017
20:19:29 Output: TEST_CMD_LINE: CoreMangLib\cti\system\string\StringFormat1> C:\Users\DDJOIN\arm64_ci\tests\CoreMangLib\cti\system\string\StringFormat1\StringFormat1.cmd 
20:19:29 BEGIN EXECUTION
20:19:29  "C:\Users\DDJOIN\arm64_ci\tests\Tests\Core_Root\corerun.exe" StringFormat1.exe 
20:19:29 Beginning test case for method: String.Format(String, Object) at 3/10/2017 7:52:35 PM
20:19:29 Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
20:19:29 [Positive]
20:19:29 Beginning scenario: PosTest1: Default format string for Int32
20:19:29 Beginning scenario: PosTest2: the length of the formatted Int32 value is less than alignment
20:19:29 ERROR!!!-003 TestId-P002: Value is not True as expected: Actual(False)
20:19:29 Beginning scenario: PosTest3: alignment is positive, the length of the formatted Int32 value is greater than alignment
20:19:29 Beginning scenario: PosTest4: alignment is zero
20:19:29 Beginning scenario: PosTest5: alignment is negative, and its absolute value is greater than length of formatted object
20:19:29 Beginning scenario: PosTest6: alignment is negative, and its absolute value is less than or equal length of formatted object
20:19:29 Beginning scenario: PosTest7: Formatted object is null
20:19:29 Beginning scenario: PosTest8: format string contains { literal
20:19:29 [Negative]
20:19:29 Beginning scenario: NegTest1: format is a null reference 
20:19:29 Beginning scenario: NegTest2: The format item in format is invalid 
20:19:29 Beginning scenario: NegTest3: The index is greater than number of formatted objects 
20:19:29 Beginning scenario: NegTest4: The index is negative 
20:19:29 Ending test case at 3/10/2017 7:52:35 PM
20:19:29 FAIL
20:19:29 Expected: 100
20:19:29 Actual: 0
20:19:29 END EXECUTION - FAILED
20:19:29 FAILED
</pre>

**Comment by sdmaclea** [comment]
In case it is interesting, these tests pass in debug mode and fail in checked mode on Arm64/Unix

**Comment by sdmaclea** [comment]
@jashook This failure appears intermittent.  I am seing it again on the tip.  It should be reopened

**Comment by BruceForstall** [comment]
@sdmaclea These don't fail for me on Windows arm64. Can you check again for Linux?

I've opened a PR to remove their exclusion on Windows.

**Comment by sdmaclea** [comment]
@BruceForstall I see no issue on linux-arm64 either
