### ISSUE TITLE
Coreclr tests-scripts must be ported to Unix

### ISSUE THREAD

**Issue by josteink** [dotnet/coreclr#1011]
Currently the coreclr-tests can only be built and run on Windows through the following scripts:

* [buildtests.cmd](https://github.com/dotnet/coreclr/blob/master/tests/buildtest.cmd) 
* [runtests.cmd](https://github.com/dotnet/coreclr/blob/master/tests/runtest.cmd)

These scripts should be ported to Unix shell-scripts so that coreclr-tests can be run on the port-platforms to validate changes directly.

[The current recommendation](https://github.com/dotnet/coreclr/wiki/Validating-changes) is to build the corefx repo (which also only builds on Windows) and indirectly validate coreclr through the corefx test-suite. I think this is an area ripe for improvement.

Looking over the scripts, it seems the main pre-requites are:

* msbuild (which has a [xplat-branch](https://github.com/Microsoft/msbuild/tree/xplat)). Build instructions can be found in the [corefx wiki](https://github.com/dotnet/corefx/wiki/Building-On-Unix#building-xplat-msbuild).
* Roslyn, which is known to run fine on pretty much all platforms through mono.
* [Xunit](https://github.com/xunit/xunit/), which is .NET-based, and which therefore may depend on coreclr to be in a pretty good initial shape.

I think this sounds doable, and I think this is a worthy goal to improve support for all ports: Linux, OSX and FreeBSD.

Besides getting the tests to run, it should also be documented *how* to get them running. This is currently significantly under-documented compared to the overall build-instructions and we should aim to get these on par.

It would be interesting to hear what people with more coreclr-experience think about this task:

* Do you foresee any "obvious" obstacles?
* Are there known xplatform-issues in the current test-suite?
* Will Xunit need to be run with the coreclr-instance being debugged, or can it be run with mono?

Could anyone provide some feedback? Especially Microsoftees are welcome to drop off some advice.

CC: @MattWhilden  @janvorli @kangaroo @ellismg

**Comment by jasonwilliams200OK** [comment]
> corefx repo (which also only builds on Windows)

I think this is not true: https://github.com/dotnet/corefx/wiki/Building-On-Unix.

@stephentoub, it seems like the following in [readme of corefx](https://github.com/dotnet/corefx/blob/9a86bb89e26c92afe9a0f61bed3dd757894b7499/README.md) is obsolete:

(first paragraph):

> You can 'watch' the repo to see Linux and Mac support being added over the next few months.

**Comment by kouvel** [comment]
There are instructions now for running CoreCLR tests outside Windows: https://github.com/dotnet/coreclr/blob/master/Documentation/building/unix-test-instructions.md

The test build currently still requires Windows.

**Comment by MattWhilden** [comment]
Do we know what the set of Issues is that tracks doing test builds on Unix platforms. Presumably msbuild being available etc etc. They'll certainly be issues from other repros but might be useful to collect any we know about as FYI and then close this issue down.

**Comment by kouvel** [comment]
I'm not aware of any blocking issues, I think it's just a matter of doing it. We would just have to pull in msbuild and Roslyn, it would be nice to get this done at some point.

**Comment by kouvel** [comment]
Apparently, there are were some stability issues that CI builds were running into, when running msbuild under mono. I understand that work is already being done there to enable full builds that don't require Windows. Closing this issue for now.
