### ISSUE TITLE
[Arm64] DevDiv_359736 test failures: No Exception thrown

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#10111]
Tests

<pre>
jit\Regression\JitBlue\DevDiv_359736\DevDiv_359736_do\DevDiv_359736_do.cmd
JIT\Regression\JitBlue\DevDiv_359736\DevDiv_359736_ro\DevDiv_359736_ro.cmd
</pre>

Expected Output:

<pre>
BEGIN EXECUTION
 "C:\Users\DDJOIN\proyectos\febrero-2-2017\pruevas\tests2\Core_Root\corerun.exe" DevDiv_359736_do.exe
FAILED: No exception thrown
Expected: 100
Actual: -1
END EXECUTION - FAILED
FAILED
</pre>
category:correctness
theme:cse
skill-level:intermediate
cost:small

**Comment by mikedn** [comment]
Likely a duplicate of #8648

**Comment by BruceForstall** [comment]
These tests still fail.

**Comment by BruceForstall** [comment]
@briansull Should this be fixed now? If so, can you submit a PR that removes
```
<ExcludeList Include="$(XunitTestBinBase)/JIT/Regression/JitBlue/DevDiv_359736/**">
    <Issue>8648</Issue>
</ExcludeList>
```
from issues.targets?

(and close this issue)

**Comment by briansull** [comment]
I verified that these tests now pass on Arm64 hardware

**Comment by briansull** [comment]
Test has been Enabled with #20347
