### ISSUE TITLE
error: pointer being freed was not allocated

### ISSUE THREAD

**Issue by alexanderuv** [dotnet/coreclr#10127]
I have created a fork for ClangSharp here: https://github.com/BladeLang/ClangSharp

and I ran into this issue. Seems to be a problem with P/Invoke

dotnet(12880,0x7fffe989e3c0) malloc: *** error for object 0x7fb97956c510: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

You can try yourselves. I installed llvm using homebrew so my command ends up like this:

(at the project root)
./build.netcore.sh /usr/local/Cellar/llvm/3.9.1/lib /usr/local/Cellar/llvm/3.9.1/include

**Comment by jkotas** [comment]
It is most likely a bug in ClangSharp, not in CoreCLR.

cc @mjsabby

**Comment by gkhanna79** [comment]
@alexanderuv Can you please move the issue to appropriate repo?

**Comment by alexanderuv** [comment]
You guys are right. I was looking more closely at the code and they are manually calling Alloc and Free so there must be something wrong there. I'm closing this.
