### ISSUE TITLE
[x86/Linux] Nested calls don't handle stack alignment properly

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#10122]
On Linux/x86, the stack must be aligned to 16 bytes when a call is made. We do this by computing the number of alignment bytes required, saving this on the first PUTARG_STK node, and generating an additional, preceding "sub esp, N" instruction before the first stack argument is generated. Then, after the call, we add back the alignment value, if any.

The alignment is calculated in fgArgInfo::ArgsAlignPadding().

The problem is, it assumes the stack is aligned when the arguments for a call start being pushed. This is not true for nested calls, for which we may push some args for an outer call, then push some args for an inner call, make the inner call, push some more args for the outer call, then make the outer call.

Consider the following program:
```
using System;
using System.Runtime.CompilerServices;

public class Program
{

    [MethodImplAttribute(MethodImplOptions.NoInlining)]
    public static float f1(float a)
    {
        Console.WriteLine(a);
        return a + 1.0f;
    }

    [MethodImplAttribute(MethodImplOptions.NoInlining)]
    public static float f2(float a, float b)
    {
        Console.WriteLine(a);
        return a + b + 1.0f;
    }

    public static int Main(string[] args)
    {
        float b = f2(2.0f, f1(1.0f));
        Console.WriteLine(b);

        return 100;
    }
}
```
which generates this code:
```
movss    xmm0, dword ptr [@RWD00]
sub      esp, 8 // f2 takes 8 bytes of stack arguments, so generate an 8-byte alignment adjustment
sub      esp, 4 // "push" the float argument
movss    dword ptr [esp], xmm0
movss    xmm0, dword ptr [@RWD04]
sub      esp, 12 // f1 takes 4 bytes of stack arguments, so generate a 12-byte alignment adjustment
                        // NOTE: the stack has already been adjusted by 12 bytes! No alignment adjustment is needed!
sub      esp, 4 // "push" the inner float arg
movss    dword ptr [esp], xmm0
call     [Program:f1(float):float]
add      esp, 12 // restore adjustment
fstp     dword ptr [TEMP_01 ebp-04H]
movss    xmm0, dword ptr [TEMP_01 ebp-04H]
sub      esp, 4 // "push" second outer arg
movss    dword ptr [esp], xmm0
call     [Program:f2(float,float):float]
add      esp, 8 // "restore" alignment
```

Option 1 for fixing this would be to have ArgsAlignPadding() take into account all argument and alignment stack adjustments that have been made by outer calls at the point the inner call args start being pushed.

Option 2 for fixing this would be to hoist all nested calls, preventing arguments from multiple nested calls being on the stack simultaneously (one one call's arguments would be set up and pushed at a time). This is done (and required by ABI) for all non-x86 targets. It might lead to sub-optimal code due to the need for temps to store intermediate results.

Related issues: #10002, #10059.

**Comment by BruceForstall** [comment]
@parjong @seanshpark

**Comment by parjong** [comment]
@BruceForstall @seanshpark currently attempts to enable ``FEATURE_FIXED_OUT_ARGS`` (#10012). Is it related with option 2?

**Comment by seanshpark** [comment]
@parjong , I think this is necessary with or without `FEATURE_FIXED_OUT_ARGS`, option 1 or option 2 either case.

**Comment by BruceForstall** [comment]
Implementing `FEATURE_FIXED_OUT_ARGS` out imply option 2.

However, I'm investigating implementing option 2 even if `FEATURE_FIXED_OUT_ARGS` is not enabled.
