### ISSUE TITLE
Vector<T> showing up incorrectly in debugger

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#10148]
e.g.
![image](https://cloud.githubusercontent.com/assets/2642209/23870422/c00b6230-07fc-11e7-853b-ff1964d61357.png)

cc: @mellinoe, @CarolEidt

**Comment by gkhanna79** [comment]
@noahfalk Please reroute as appropriate.

**Comment by noahfalk** [comment]
Is there a BCL owner for System.Numerics? Presumably that is where this should end up. In the meantime assigning to mikem for all things .Net Core debugging.

**Comment by jkotas** [comment]
You need to have machine with Intel AVX where SIMD Vector is 32 bytes to repro this bug.

**Comment by gkhanna79** [comment]
@lt72 @mikem8361 @noahfalk Is this on track for 2.0?

**Comment by mikem8361** [comment]
@jkotas do you know how I can tell if my Linux machine is Intel AVX/SIMB?

@janvorli the funceval bugs we've had in the past were with 16 byte enregistered values.  This is 32 bytes do either of you have any ideas where to start?

**Comment by gkhanna79** [comment]
Given that ZBB is on 5/10 and we have not looked at this yet, does this meet the bar for 2.0 @lt72 ?

**Comment by jkotas** [comment]
> @jkotas do you know how I can tell if my Linux machine is Intel AVX/SIMB?

`grep avx /proc/cpuinfo` (http://tinyurl.com/l47p7o7)

Note that this is not Linux specific bug. It repros on Windows x64 too, on both .NET Core and .NET Framework.

**Comment by lt72** [comment]
I do not believe this strictly meet the bar for 2.0, although there is little mention of tooling in general last time I checked. That said, isn't deadline on 5/10?  We'd' like to take a look unless there is a pressing need to make ZBB early.

**Comment by gkhanna79** [comment]
Deadline for ZBB is 5/10. I think you need to triage whether this is runtime/debugger issue or VS debugger issue.

**Comment by janvorli** [comment]
@mikem8361 I would start debugging in MethodDescCallSite::CallTargetWorker, that means the place where you've made the fixes for the 16 byte enregistered arguments before. It should be relatively easy to see what's going on in the argument copying loop. If the loop copied the argument correctly, then I'd look at the CallDescrWorkerInternal.

**Comment by tannergooding** [comment]
@mikem8361, from what I could tell investigating the related issue: https://github.com/dotnet/coreclr/issues/15694

It looks like Marshalling, Remoting, and Serialization are all seem to be working as expected.

However, it appears that debugging in particular does not work well with any memory that is not directly accessible by a corresponding field.

For example, with :
```
struct Data
{
    byte _0;
    int  _4;
}
```

There are three implicit padding bytes between `_0` and `_4`. If you were to explicitly set those to some value (say via unsafe code) and then try to view the same bytes in the debugger, they would appear as 0. The `_0` and `_4` fields would appear as their correct values.

Additionally, for types that are explicitly sized (like `Vector128<T>` or `Vector<T>`) the implicit bytes past the end of the last field are not accessible.

For Example, with:
```
[StructLayout(LayoutKind.Sequential, Size = 16)]
struct Vector128<T> where T : struct { }
```

There are no fields declared, but the size is explicitly set to 16. The debugger does not copy any of the implicit 16-bytes and they are set to 0.

For Example, with:
```
struct Vector<T>
{
    private Register register;
}

[StructLayout(LayoutKind.Explicit)]
struct Register
{
    // Internal System.Byte Fields
    [FieldOffset(0)]
    internal Byte byte_0;
    [FieldOffset(1)]
    internal Byte byte_1;
    [FieldOffset(2)]
    internal Byte byte_2;
    [FieldOffset(3)]
    internal Byte byte_3;
    [FieldOffset(4)]
    internal Byte byte_4;
    [FieldOffset(5)]
    internal Byte byte_5;
    [FieldOffset(6)]
    internal Byte byte_6;
    [FieldOffset(7)]
    internal Byte byte_7;
    [FieldOffset(8)]
    internal Byte byte_8;
    [FieldOffset(9)]
    internal Byte byte_9;
    [FieldOffset(10)]
    internal Byte byte_10;
    [FieldOffset(11)]
    internal Byte byte_11;
    [FieldOffset(12)]
    internal Byte byte_12;
    [FieldOffset(13)]
    internal Byte byte_13;
    [FieldOffset(14)]
    internal Byte byte_14;
    [FieldOffset(15)]
    internal Byte byte_15;

    // Internal System.SByte Fields
    [FieldOffset(0)]
    internal SByte sbyte_0;
    [FieldOffset(1)]
    internal SByte sbyte_1;
    [FieldOffset(2)]
    internal SByte sbyte_2;
    [FieldOffset(3)]
    internal SByte sbyte_3;
    [FieldOffset(4)]
    internal SByte sbyte_4;
    [FieldOffset(5)]
    internal SByte sbyte_5;
    [FieldOffset(6)]
    internal SByte sbyte_6;
    [FieldOffset(7)]
    internal SByte sbyte_7;
    [FieldOffset(8)]
    internal SByte sbyte_8;
    [FieldOffset(9)]
    internal SByte sbyte_9;
    [FieldOffset(10)]
    internal SByte sbyte_10;
    [FieldOffset(11)]
    internal SByte sbyte_11;
    [FieldOffset(12)]
    internal SByte sbyte_12;
    [FieldOffset(13)]
    internal SByte sbyte_13;
    [FieldOffset(14)]
    internal SByte sbyte_14;
    [FieldOffset(15)]
    internal SByte sbyte_15;

    // Internal System.UInt16 Fields
    [FieldOffset(0)]
    internal UInt16 uint16_0;
    [FieldOffset(2)]
    internal UInt16 uint16_1;
    [FieldOffset(4)]
    internal UInt16 uint16_2;
    [FieldOffset(6)]
    internal UInt16 uint16_3;
    [FieldOffset(8)]
    internal UInt16 uint16_4;
    [FieldOffset(10)]
    internal UInt16 uint16_5;
    [FieldOffset(12)]
    internal UInt16 uint16_6;
    [FieldOffset(14)]
    internal UInt16 uint16_7;

    // Internal System.Int16 Fields
    [FieldOffset(0)]
    internal Int16 int16_0;
    [FieldOffset(2)]
    internal Int16 int16_1;
    [FieldOffset(4)]
    internal Int16 int16_2;
    [FieldOffset(6)]
    internal Int16 int16_3;
    [FieldOffset(8)]
    internal Int16 int16_4;
    [FieldOffset(10)]
    internal Int16 int16_5;
    [FieldOffset(12)]
    internal Int16 int16_6;
    [FieldOffset(14)]
    internal Int16 int16_7;

    // Internal System.UInt32 Fields
    [FieldOffset(0)]
    internal UInt32 uint32_0;
    [FieldOffset(4)]
    internal UInt32 uint32_1;
    [FieldOffset(8)]
    internal UInt32 uint32_2;
    [FieldOffset(12)]
    internal UInt32 uint32_3;

    // Internal System.Int32 Fields
    [FieldOffset(0)]
    internal Int32 int32_0;
    [FieldOffset(4)]
    internal Int32 int32_1;
    [FieldOffset(8)]
    internal Int32 int32_2;
    [FieldOffset(12)]
    internal Int32 int32_3;

    // Internal System.UInt64 Fields
    [FieldOffset(0)]
    internal UInt64 uint64_0;
    [FieldOffset(8)]
    internal UInt64 uint64_1;

    // Internal System.Int64 Fields
    [FieldOffset(0)]
    internal Int64 int64_0;
    [FieldOffset(8)]
    internal Int64 int64_1;

    // Internal System.Single Fields
    [FieldOffset(0)]
    internal Single single_0;
    [FieldOffset(4)]
    internal Single single_1;
    [FieldOffset(8)]
    internal Single single_2;
    [FieldOffset(12)]
    internal Single single_3;

    // Internal System.Double Fields
    [FieldOffset(0)]
    internal Double double_0;
    [FieldOffset(8)]
    internal Double double_1;
}
```
Vector<T> has a single field, `Register`, which itself only declares fields for 16 sequential bytes. When the JIT explicitly sizes `Vector<T>` as 32-bytes on AVX compatible machines, the debugger only copies the 16 bytes that map to fields. The debugger doesn't copy the remaining 16-bytes and they are set to 0.

**Comment by lt72** [comment]
Moving to future and marking as tracking-external-issue, as this issue should be solved through #16280.

**Comment by tannergooding** [comment]
This is also being tracked by a vsfeedback issue: https://developercommunity.visualstudio.com/content/problem/222409/contents-of-systemnumericsvector-are-shown-incorre.html

**Comment by tmat** [comment]
Closing as dup of https://github.com/dotnet/coreclr/issues/16280
