### ISSUE TITLE
Wrong comment about GC pinning bit in object.h

### ISSUE THREAD

**Issue by 303248153** [dotnet/coreclr#10141]
I found this comment in https://github.com/dotnet/coreclr/blob/master/src/vm/object.h
```
// lose GC marking bit and the pinning bit
// A method table pointer should always be aligned.  During GC we set the least 
// significant bit for marked objects and we set the second to least significant
// bit for pinned objects.  So if we want the actual MT pointer during a GC
// we must zero out the lowest 2 bits.
```
I think it's wrong, GC pinning bit actually stored in object header

``` c++
void SetPinned()
{
    assert (!(gc_heap::settings.concurrent));
    GetHeader()->SetGCBit();
}

void SetGCBit() { m_uSyncBlockValue |= BIT_SBLK_GC_RESERVE; }
```
And I verified in lldb
![1](https://cloud.githubusercontent.com/assets/16222094/23843132/ab715616-07f4-11e7-84c5-8e618f14318a.jpg)

And no code is touching `m_pMethTab & 2`, am I right and should this comment be fixed?

**Comment by swgillespie** [comment]
That would seem to be the case, yeah. I suppose that this was historically the case, though we do use the GC bit on the sync block now as you observed. Feel free to submit a PR with a fixed comment, we'd be happy to take it!

**Comment by 303248153** [comment]
Thanks for response.
Also the code in `GetGCSafeMethodTable` use a hard code `3` for clear the MARKED_BIT and the pinned bit not using now, should it be fixed together?
```
PTR_MethodTable GetGCSafeMethodTable() const
    {
        LIMITED_METHOD_CONTRACT;
        SUPPORTS_DAC;

        // lose GC marking bit and the pinning bit
        // A method table pointer should always be aligned.  During GC we set the least 
        // significant bit for marked objects and we set the second to least significant
        // bit for pinned objects.  So if we want the actual MT pointer during a GC
        // we must zero out the lowest 2 bits.
        return dac_cast<PTR_MethodTable>((dac_cast<TADDR>(m_pMethTab)) & ~((UINT_PTR)3));
}
```
I think it can be replaced with
```
return dac_cast<PTR_MethodTable>((dac_cast<TADDR>(m_pMethTab)) & (~MARKED_BIT));
```

**Comment by swgillespie** [comment]
Sure, feel free to do that too!
