### ISSUE TITLE
Provide API for Primitive / Struct Array "Views"

### ISSUE THREAD

**Issue by AdamsLair** [dotnet/coreclr#1015]
## Problem Description

Consider the following case:

```
[StructLayout(StructLayout.Sequential)]
struct ColorRgba { byte R; byte G; byte B; byte A; }

private void Foo(byte[] colorDataRgba)
{
    // To interface with a library or other code, I need my color data in a different format.
    ColorRgba[] colorsA = ???;
    int[] colorsB = ???;
}
```

There are two ways of getting the color data in a different format:
1. Creating a new array of the appropriate size and do a block copy on it. This will result in a big performance hit for large arrays. Think of a 2048x2048 image in RGBA format. Might take "a while".
2. Using unsafe code to obtain a pointer to the array, cast it and then use that for access. This is essentially "free".

So, while the second approach may be preferable for high-performance code, it is not viable when passing array data to a class instance that requires a different format and at the same time wants to take ownership of that data - because it can't store a fixed unsafe pointer permanently. Thus, copying is the only choice here.

[There is a hack](http://stackoverflow.com/a/3577227/2015377) to be able to "cast" the array into the desired format, but that has its own problems and looks like it's going to break as soon as some core data layout changes, or the code is ported to a different platform. Generally not the kind of code you'd want in a C# project.
## A Bad Idea

Allowing all arrays of structs and primitive types to be cast is probably not a good idea.
- It will make a very niche and questionable operation more accessible and inviting.
- There will be the problem of the arrays element length, which will need to be recalculated when the element type size changes.
  - The recalculation itself may be questionable when the numbers don't add up. What will happen when casting a byte[] into a ColorRgba[](4 bytes each) when the byte array was only two elements long? Could throw an exception when performing the cast.
  - What will happen to other references to that same array, which are not cast? Their Length property would "magically" change into a wrong value. Definitely **not** viable.
  - Alternatively, an arrays length value could be internally expressed in bytes and be calculated upon access, depending on the type of the array. However, this would likely have a performance impact in various spots. Probably not viable either.
## A Hopefully Better Idea

As a different approach, maybe it would be possible to introduce "view" arrays that essentially wrap another existing arrays data segment and specify a new element type:

```
private void Foo(byte[] colorDataRgba)
{
    // Create a new "view" array that internally points to the data 
    // block of the original array. Could also do safety checks.
    ColorRgba[] colors = Array.CreateView<ColorRgba>(colorDataRgba);

    // Properly recalculated to colorDataRgba.Length / 4 and 
    // stored permanently in the view array header for performance reasons.
    Console.WriteLine(colors.Length);

    // Accesses the same data directly, without copying or casting
    Console.WriteLine(colors[0]);
}
```

Not sure about the internal additions that would be required for this, but I'd imagine the existing array header layout should have enough space to store a flag for being a view array and a pointer towards the actual data block.
## Proposed Solution

To me, the "view" array idea sounds most reasonable, but I'm sure others will have a far better grasp on this. 

What do you think?

**Comment by OtherCrashOverride** [comment]
You can use unsafe pointers and generics with a struct constraint to accomplish this.  The proposed "view" breaks type-safety: if I "view" the byte array of colors as an integer array, functions such as math operators no longer make sense.

Alternatives include:
System.Runtime.GCHandle.Alloc
System.Runtime.Marshal.PtrToStructure

**Comment by AdamsLair** [comment]
> You can use unsafe pointers and generics with a struct constraint to accomplish this. 

To my knowledge, I can't store an unsafe pointer permanently and it wouldn't be desirable either, as it would require the array to be fixed in memory permanently. I explained this in the problem description -  if my assumption is wrong, please provide an example on how to do this.

> if I "view" the byte array of colors as an integer array, functions such as math operators no longer make sense.

Yes, I know. But it does serve a specific use case that (again, to my knowledge) cannot be covered otherwise so far. Sure, you can use it to do nonsense - but you can also do nonsense with pretty much anything else, if you have no idea what you're doing. The important question is: Can you do *dangerous* nonsense? And as far as I can see it, the answer would be "no": You can screw up your own data, but that's it. Please do correct me if I'm wrong here!

> integer array

As far as the example goes, Rgba8 colors are sometimes encoded in an int[] where each int represents a single pixel. It may be curious, but it's really just a library choice, and I might need to deal with a set of libraries that I somehow have to tie together. Also, it's really just an example - maybe you're dealing with audio data in a byte[] you just retrieved, but you know the each two bytes in there actually encode a short and you need to pass that as a short[] to an audio library? I'm sure you can find more examples.

So, given the fact that the problem actually exists, I'd like to have a performant way to do this.

**Comment by OtherCrashOverride** [comment]
>  I might need to deal with a set of libraries that I somehow have to tie together.

It was evident that was the actual issue here and the solution is to use an agreed upon type.  It is by design that you can not do what is requested in the topic since the runtime is "strongly typed"

> please provide an example on how to do this.

You can store a reference to the object as normal and get its address as needed pinning only for the duration of use.  I did not provide an example because this is a GitHub issue, not a StackOverflow question.

**Comment by AdamsLair** [comment]
> It was evident that was the actual issue here and the solution is to use an agreed upon type.

This is a real-world issue that won't go away when simply because I decide I want to agree upon types, because I am not in charge of designing the API of every library out there. 

In C++, this would be no big deal, because I can always just reinterpret_cast - and even though this is a terrible practice that is only useful in 0.1% of all cases, these cases still *do* exist. Let me clarify that I do **not** want to propose a reinterpret_cast-like feature for C# or .Net - this would be a terrible idea. 

Instead, I'm proposing a framework addition for a specific case which hopefully cannot be abused in an arbitrary way: Limiting it to arrays of primitives and plain-old-data structs.

> I did not provide an example because this is a GitHub issue, not a StackOverflow question.

I did not ask for an example because I didn't do research, but to clarify whether we are talking about the same thing and find a mutual understanding. Your answers leave me unsure whether we're really both on the same page here and an example could help clear this up.

**Comment by jkotas** [comment]
"view" arrays are the key idea here. It looks same as Slice<T> proposed by https://github.com/dotnet/roslyn/issues/120.

The array views for structs like Color would a trivial add-on for Slice<T>.

**Comment by OtherCrashOverride** [comment]
As an example of 'nightmare' scenario of this: what happens when you 'view' the byte array as a SIMD type that has additional alignment requirements? What happens when you view the byte array as a floating point Color type as used by WPF, etc?

If you want to do this in your own code, that is your choice and there is currently a way to do that using unsafe pointers and generics.

**Comment by AdamsLair** [comment]
> If you want to do this in your own code, that is your choice and there is currently a way to do that using unsafe pointers and generics.

Did you read my above example? Unsafe pointers are not really helping here.

> As an example of 'nightmare' scenario of this:

When you view a byte array as a float array, you will get nonsense data. That's it. Doesn't sound too nightmarish to me, as it doesn't happen on accident, but only when doing it explicitly. Same with alignment requirements. (And if there is anything arcane going on with native SIMDs, you can always prevent that specific use case in the validation check of ```Array.CreateView<T>```)

This is not a feature for everyone to use all around their code, it has a very specific set of use cases. You will need to know what you're doing, but I believe that's by itself not a problem - as long as you're not able to break anything except your own code.

**Comment by OtherCrashOverride** [comment]
As a show of good faith, I will state that if this were somehow to be allowed it should probably take the form of:
R[] System.Runtime.InteropServices.Marshall.ReinterpretArray<T, R>(T[] typeArray) where T: struct, R: struct

**Comment by AdamsLair** [comment]
Looks good to me. Let's talk about what problems this might yield in practice and how to overcome them. 

*Bear in mind, I'm really just poking the problem with a stick here, as I have little to no knowledge about the actual runtime implementation of arrays and how they're handled internally. Feedback requested.*

## "What to look out for"

1. **Size Restrictions:** The size of both Types need to "fit", so the view doesn't lead to interpreting "half" a color with a memory access violation in the end.
2. **Plain Old Data:** Not only need both Types to be structs, they may also not contain fields of Types that could become dangerous when filled with garbage.
3. **Garbage Collection:** The garbage collector shouldn't collect the array that is viewn as long as a view still exists.

## "How to handle it (?)"

1. This could be a simple runtime check in the view creation method. Just throw an exception when it doesn't match.
2. It is possible to use reflection for determining this: Iterate over a structs fields and throw an exception if any of those fields is a reference to an object, a pointer or an IntPtr. But maybe there are faster ways to do this? Also, there might be other cues that could flag a certain struct as inappropriate for this. Maybe they are also required to have a ```StructLayout``` attribute of either sequential or explicit?
3. As long as a view has an internal reference to the original array, this *should* not be a problem (?) - though my knowledge wears really thin here with regard to possible alternative lowlevel implementations.. any word from someone who is more proficient?

--------------

There's probably more that I haven't thought about - especially on the implementation / backend side.

**Comment by OtherCrashOverride** [comment]
Presumably it would simply combine the Marshal.StructureToPtr and Marshal.PtrToStructure calls within a new call that did the following instead of copying memory:
1) Created a new array of the destination type and made it point to the source type's data.
2) Disposed the source type or made it an empty array.
3) Have an additional restriction that the source and destination types Marshal.SizeOf() must be equal sized or an even multiple.

https://github.com/dotnet/coreclr/blob/master/src/vm/marshalnative.cpp#L134

**Comment by OtherCrashOverride** [comment]
Multidimensional arrays would also be problematic. This means that byte[] cast to int[,] a would have many different valid interpretations.

**Comment by OtherCrashOverride** [comment]
After reviewing the Slice proposal, I should point out that this request is different from a Slice in that a Slice inherits the type of source data.  This proposal changes the type of the data.

**Comment by AdamsLair** [comment]
> 2) Disposed the source type or made it an empty array.

Personally, I wouldn't do this, actually. 

First, I don't see a reason why you wouldn't simply keep both arrays, as keeping them both functional might yield some additional benefits, like being able to modify a data block from two different angles, based on the use case. I also don't see a disadvantage of keeping them both around.

Secondly, disposing the source array might actually be more dangerous than the type change itself, since creating a "view" of an array wouldn't be expected to actually modify the source array in any way.

> Multidimensional arrays would also be problematic.

Personally, I don't think much would be lost when simply not supporting multidimensional arrays here. They are quite obscure.

**Comment by redknightlois** [comment]
Maybe I am wrong, but the reinterprete cast is happening right now inside fixed statements aka unsafe contexts. You can take a byte and interprete it as a long, what this is really all about is being able to reinterprete any blittable struct and take pointers from it in an unsafe context (which the CLR support as it can be done on F#). 

This is an example of such use for performance reasons: https://github.com/Corvalius/ravendb/blob/master/Raven.Voron/Voron/Util/MemoryUtils.cs#L176

With support for pointers to blittable managed types you will be able to easily create array views for manipulation inside unsafe contexts, which for most purposes would be far more than enough. 

Even in graphics programming I cannot think of a reason why I would need a 'permanent' reintepret cast when I can store the data in bytes and just "temporarily" interprete it as an specific type to interop with other libraries code. Granted the code could be far more elegant if I could just reinterprete it, but if I am doing it is because I need the speed probably not for the convenience or elegance. 

Examples I can think of are cases where I would want to treat a byte array as a SIMD vector for operating on it.

**Comment by OtherCrashOverride** [comment]
> First, I don't see a reason why you wouldn't simply keep both arrays

My concern was the impact of this on other systems such as the Garbage Collector.  I am not aware of any other construct in the runtime that has two objects pointing to the same data. What I proposed is basically a swap: create a new object and swap the data pointer of the source and destination.  This approach should have the least amount of possible side-effects and so is more likely to be considered for inclusion.

> I personally think that simply not supporting multi-dimensional arrays might not be a big loss here

I commented about multidimensional arrays since as I was going through the runtime code, I was reminded that single dimension, zero based arrays are special in the runtime and may be the only case where this proposal is trivial. 

It does beg the question though: are we solving one person's problem, or everyone's problem?  The example given at the start mentions an array of color (bitmap).  Its just as likely you will encounter this as a two dimensional array as a single.

> Even in graphics programming I cannot think of a reason why I would need a 'permanent' reintepret cast when I can store the data in bytes and just "temporarily" interprete it as an specific type to interop with other libraries code.

As I explored what it would take to implement this proposal, I asked myself where I would use this.  Its helpful to have a real world example rather than an abstract possible need.  The closest scenario I came up with was dealing with libav and in that instance I used the unsafe pointer approach. If a solution proves to be non-trivial and affects many subsystem, then there will definitely need to be a demonstrated need for this feature.

**Comment by omariom** [comment]
The benefit would be that the source byte array won't be pinned in memory.

```C#
var messageView = new ByteArrayView<Message>(bytes, numberOfElements);
long id = messageView[0].Id;
ProcessMessage(ref messageView[0]);
```

Generic argument must not contain pointers (references) directly or indirectly.
Constructor of ByteArrayView throws if  sizeof(Message) * numberOfElements doesn't fit into bytes.
The indexer behaves like array's indexer, e.g. throws IndexOutOfRangeException .

Also I'd like ByteArrayView to be immutable struct. This way we wouldn't have to pay the cost of  allocation of it.

**Comment by AdamsLair** [comment]
> Also I'd like ByteArrayView to be immutable struct. 

I think that creating a separate view class would severely diminish the use of this feature. This line here:

```
ProcessMessage(ref messageView[0]);
```
would only be possible when the view is itself a ```Message[]```, but not a ```ByteArrayView<Message>```, because in the class approach, this would need to be an indexer property, which can not be ```ref```-ed.

Also, if I need to pass a view to a method that requires an array of the appropriate Type, I will again need to copy my data - which was the main thing that I wanted to avoid when proposing this feature. So, let me modify your example slightly:

```
Message[] messageView = Array.CreateView<Message>(bytes, index, length);
long id = messageView[0].Id;
ProcessMessage(ref messageView[0]);
```

The resulting view array would be transparent, in the sense that you can't tell it's "just" a view array. I would imagine that this would make this feature most useful.

**Comment by redknightlois** [comment]
@AdamsLair Agree with your assessment. The point of having "views" in the end is to be able to reinterprete any blittable type into an array. 

One can actually think this is a more specific case of slicing: https://github.com/dotnet/roslyn/issues/120 

In the end the problem faced is very similar: 
- can a byte array be reinterpreted as another type?
- can a partial array be reinterpreted as an array?

**Comment by omariom** [comment]
Refs to indexer are possible with support of CLR.

Arrayview is not to replace array of structs. The idea is that it is efficient fixed size view into byte array.
________________________________

**Comment by omariom** [comment]
> So, let me modify your example slightly:
> Message[] messageView = Array.CreateView<Message>(bytes, index, length);

Agree.
It is a more uniform approach/

**Comment by ilexp** [comment]
Any news on this? From a gamedev perspective, I'd really like to see something like this. It's already possible to write high-performance code in C#, but stuff like this would certainly make it easier.

**Comment by omariom** [comment]
@ilexp It is being prototyped in [Slices](https://github.com/dotnet/corefxlab/tree/master/src/System.Slices)

**Comment by ilexp** [comment]
Just to be extra sure: The slice being a custom `Span<T>` struct is part of the prototype and would be changed as part of an actual implementation, correct? Because if it can't be treated exactly as an array, that would probably take away a big part of its core purpose.

**Comment by jkotas** [comment]
https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md is coming in .NET Core 2.1.

Sorry, it does not let you interpret one array as a different array. We did not find any reasonable way how to make that work.

**Comment by ilexp** [comment]
> Sorry, it does not let you interpret one array as a different array. We did not find any reasonable way how to make that work.

No problem, have been following Span and it turned out pretty awesome from what I can see. Looking forward to it!
