### ISSUE TITLE
llvm.org, gpg: no valid OpenPGP data found. building coreclr on ubuntu

### ISSUE THREAD

**Issue by cheers00** [dotnet/coreclr#1017]
I'm getting the following error when I tried to get additional packages for lldb-3.6. I am trying this on Ubuntu 14.04.2 LTS desktop image. Wondering if you have run into this problem.

My network is connected.

```
root@ubuntu:/# wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
--2015-05-18 04:37:54--  http://llvm.org/apt/llvm-snapshot.gpg.key
Resolving llvm.org (llvm.org)... 128.174.246.134
Connecting to llvm.org (llvm.org)|128.174.246.134|:80... failed: Connection refused.
gpg: no valid OpenPGP data found.
```

**Comment by akoeplinger** [comment]
The problem is that you can't connect to llvm.org (likely a network problem) and so no valid data is passed to apt-key, which in turn triggers the gpg error. Check that your network connection is working :)

**Comment by cheers00** [comment]
Network was working. I was able to update others

I switched to Ubuntu server (no desktop) and I don't see any issues.

**Comment by abritinthebay** [comment]
Seeing the same thing and it's because http://llvm.org/apt/llvm-snapshot.gpg.key doesn't exist

In fact the entire http://llvm.org/apt/ location doesn't exist

**Comment by ZizhengTai** [comment]
Yes I'm seeing the same issue as @abritinthebay is.

**Comment by tugberkugurlu** [comment]
same issue. `wget -q -O - http://llvm.org/apt/llvm-snapshot.gpg.key|apt-key add - ` simply doesn't work. Did anyone find a workaround for this?

**Comment by ZizhengTai** [comment]
If you go to http://llvm.org/apt in a browser, you can see they are working
on the issue. It should be resolved soon.

**Comment by tugberkugurlu** [comment]
@ZizhengTai oh, well. This is a bit screwed up :disappointed: https://twitter.com/tourismgeek/status/738102584540434432

**Comment by 7kemZmani** [comment]
at first I got the same error as @tugberkugurlu, but then I tried 
`wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key`
which downloaded `llvm-snapshot.gpg.key`; after that I just added the key file
`sudo apt-key add llvm-snapshot.gpg.key`

Works like a charm!
