### ISSUE TITLE
Most (all?) tests are failing under GCStress=0x3

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#10265]
See e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0x3/19/

The most frequent cause appears to be this assert:

```
Assert failure(PID 7408 [0x00001cf0], Thread: 3568 [0x0df0]): generation_allocation_pointer (youngest_generation) == nullptr\r\n\r\nCORECLR! WKS::gc_heap::fix_youngest_allocation_area + 0x26 (0x00007ff8`cbe5bf4a)
```

@swgillespie @Maoni0 can one of you take a look?

**Comment by pgavlin** [comment]
(cc @RussKeldorph)

**Comment by swgillespie** [comment]
This assert was introduced in https://github.com/dotnet/coreclr/pull/10065, I'll take a look.

**Comment by swgillespie** [comment]
I think I know what's going on here and I hope to have a fix out soon.

**Comment by swgillespie** [comment]
Related (but not the root cause of this particular issue: https://github.com/dotnet/coreclr/issues/10318)

**Comment by sdmaclea** [comment]
Also affects gcStress=0xC
