### ISSUE TITLE
AltDirectorySeparatorChar is incorrect on Unix

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/coreclr#1026]
https://github.com/dotnet/coreclr/blob/108b40a01da527fb9f37686be14897a81da31c1a/src/mscorlib/src/System/IO/Path.cs#L70

On Unix '\\' is a valid filename character so it should not be an alternate for directory separator.

@ellismg

**Comment by ellismg** [comment]
@stephentoub I think this is effectively dead code because we use the version from CoreFX for Unix, right?

**Comment by BrennanConroy** [comment]
Oh, should this be on CoreFX then?
https://github.com/dotnet/corefx/blob/99424912fe4436977909fab41f1809060ac24f94/src/System.Runtime.Extensions/src/System/IO/Path.cs#L58

**Comment by stephentoub** [comment]
I believe we still use the mscorlib one, and the file in CoreFX is currently used only for .NET Native (we want to use it for both, too, but haven't yet).
