### ISSUE TITLE
Linux HelloWorld. System.DllNotFoundException

### ISSUE THREAD

**Issue by cheers00** [dotnet/coreclr#1027]
I followed the steps of linux instruction document (https://github.com/dotnet/coreclr/blob/master/Documentation/linux-instructions.md). I couldn't get nuget.exe using curl and I manually had to copy from windows system. But I was able to do other steps without any errors.

But when I tried to run HelloWorld, I get the following error. Am I missing something?

```
root@ubuntu:/git/coreclr-demo/runtime# ./corerun HelloWorld.exe 

17FC System.DllNotFoundException: 170B
   at Interop.mincore.GetStdHandle(Int32 nStdHandle)
   at System.ConsolePal.get_OutputHandle()
   at System.ConsolePal.OpenStandardOutput()
   at System.Console.OpenStandardOutput()
   at System.Console.<>c.<get_Out>b__9_0()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at Program.DrawWindows()
   at Program.Main(String[] args)
root@ubuntu:/git/coreclr-demo/runtime# 
```

**Comment by ellismg** [comment]
This implies you did not copy the System.Console.dll that is built for Linux (that you built yourself) into your coreclr-demo folder.

Did you make sure to pass `/p:OSGroup=Linux` to build.cmd when building CoreFX and if so, which System.Console.dll did you copy over?

**Comment by cheers00** [comment]
I did again. I rebuilt mscorlib.dll, System.Console.dll and System.Diagnostics.Debug.dll on Windows and copied to runtime folder on Ubuntu. But I get the same error.

```
root@ubuntu:/git/coreclr-demo/runtime# ls -l
total 96416
-rwxr-xr-x 1 root root   106476 May 19 03:49 corerun
-rw-r--r-- 1 root root    11133 May 19 08:00 HelloWorld.cs
-rwxr-xr-x 1 root root    17408 May 19 10:04 HelloWorld.exe
-rw-r--r-- 1 root root 95215802 May 19 03:50 libcoreclr.so
-rw-r--r-- 1 root root  2936320 May 21 04:29 mscorlib.dll
-rw-r--r-- 1 root root    37376 May 21 04:29 System.Console.dll
-rw-r--r-- 1 root root    21360 May 20 08:51 System.Diagnostics.Contracts.dll
-rw-r--r-- 1 root root    18432 May 21 04:29 System.Diagnostics.Debug.dll
-rw-r--r-- 1 root root    20840 May 20 08:51 System.Diagnostics.Tools.dll
-rw-r--r-- 1 root root    20824 May 20 08:51 System.Globalization.dll
-rw-r--r-- 1 root root    20264 May 20 08:51 System.IO.dll
-rw-r--r-- 1 root root    22408 May 20 08:51 System.IO.FileSystem.Primitives.dll
-rw-r--r-- 1 root root    21320 May 20 08:51 System.Reflection.dll
-rw-r--r-- 1 root root    20872 May 20 08:51 System.Resources.ResourceManager.dll
-rw-r--r-- 1 root root    30528 May 20 08:51 System.Runtime.dll
-rw-r--r-- 1 root root    20848 May 20 08:51 System.Runtime.Extensions.dll
-rw-r--r-- 1 root root    20824 May 20 08:51 System.Runtime.Handles.dll
-rw-r--r-- 1 root root    23928 May 20 08:51 System.Runtime.InteropServices.dll
-rw-r--r-- 1 root root    20824 May 20 08:51 System.Text.Encoding.dll
-rw-r--r-- 1 root root    20360 May 20 08:51 System.Text.Encoding.Extensions.dll
-rw-r--r-- 1 root root    21320 May 20 08:51 System.Threading.dll
-rw-r--r-- 1 root root    21344 May 20 08:51 System.Threading.Tasks.dll
root@ubuntu:/git/coreclr-demo/runtime# ./corerun HelloWorld.exe 

17FC System.DllNotFoundException: 170B
   at Interop.mincore.GetStdHandle(Int32 nStdHandle)
   at System.ConsolePal.get_OutputHandle()
   at System.ConsolePal.OpenStandardOutput()
   at System.Console.OpenStandardOutput()
   at System.Console.<>c.<get_Out>b__9_0()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at Program.DrawWindows()
   at Program.Main(String[] args)
root@ubuntu:/git/coreclr-demo/runtime# 

```

**Comment by janvorli** [comment]
@adityamandaleeka has checked in a change few days ago that moved the english string resources into the libcoreclr.so, so you should be getting the correct exception message including the name of the file that was not found if you fetched the latest bits.

**Comment by ellismg** [comment]
You don't actually need the exception text.  `Interop.mincore.GetStdHandle` implies that we are still using the System.Console from Windows, which is not correct.

**Comment by cheers00** [comment]
I got the latest coreclr on Ubuntu and coreclr,corefx on Windows. Rebuilt all.

I am now getting the following exception of missing api-ms-win-core-processenvironment-l1-1-0.dll

```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processenvironment-l1-1-0.dll': Error 126 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetStdHandle(Int32 nStdHandle)
   at System.ConsolePal.get_OutputHandle()
   at System.ConsolePal.OpenStandardOutput()
   at System.Console.OpenStandardOutput()
   at System.Console.<>c.<get_Out>b__9_0()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at Program.DrawLinux()
   at Program.Main(String[] args)
```

**Comment by janvorli** [comment]
That's what @ellismg said. You are using the Windows version of the System.Console.dll instead of the Linux one. You need to get the one built for Linux.

**Comment by janvorli** [comment]
It should be in a subfolder of the bin\Linux.AnyCPU.Debug in the corefx.

**Comment by cheers00** [comment]
I am pretty sure that I copied System.Console.dll from Linux.AnyCPU.Debug folder of corefx on Windows build.

**Comment by xPaw** [comment]
This is related to #1002

**Comment by ellismg** [comment]
What ref is your HEAD pointer at when you are you building CoreFX?

**Comment by cheers00** [comment]
```build.cmd /p:OSGroup=Linux /p:SkipTests=true```

Or you are asking for something else?

**Comment by ellismg** [comment]
What's the output of `git rev-parse HEAD` (this tells me what commit you have checked out).

**Comment by cheers00** [comment]
```
 C:\Projects\GitHub\corefx [master]> git rev-parse HEAD
8d8c3e8f124f0e801ec185e9823cae6c65b38ef7
```

**Comment by ellismg** [comment]
Can you pull in newer changes?  We've had some changes to the build system in the past month and a half and I think they will be resolved by you just getting a newer copy of CoreFX sources.

**Comment by cheers00** [comment]
I have the latest (master). Wondering if I should switch to different branch,

```
C:\Projects\GitHub\corefx [master]> git pull
Already up-to-date.
```

**Comment by adityamandaleeka** [comment]
It appears you cloned your fork of the CoreFX repo, which is now well behind the main repo. You'll need to update your fork and then do a `git pull`.

**Comment by ellismg** [comment]
Do the following:

```
> git remote add upstream https://github.com/dotnet/corefx.git
> git fetch upstream
> git merge upstream/master
```

**Comment by cheers00** [comment]
I am having difficulties to build. I even downloaded master as zip and tried. Getting lots of ```Exec: error: FindPackagesById ```

**Comment by ellismg** [comment]
Can you share out a portion of your build log (put it in a gist and link to it?).  Seeing the full error would be helpful.  It sounds like it's nuget issues but we should be pulling most packages down via dnu now, so I'm a little confused.

You could also consider just downloading a [recent build from the CI system](http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug/lastSuccessfulBuild/artifact/*zip*/archive.zip) unzipping that and using it to get a copy of System.Console.dll.

**Comment by cheers00** [comment]
I was able to build corefx without any problems on another system with VS 2013 (only). I then copied the dlls to my Ubuntu system and HelloWorld worked.

Earlier I was trying to build it on PC with both VS 2013 and 2015 RC.
