### ISSUE TITLE
Error running corerun on Mac

### ISSUE THREAD

**Issue by meherkasam** [dotnet/coreclr#10285]
**Environment variables:**

echo $PATH
other_path_variables:/Users/meherk/Desktop/code/coreclr/bin/Product/OSX.x64.Debug

echo $CORE_LIBRARIES
/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1

**Inside ~/Desktop/helloworld, created a dotnet project:**
dotnet new console
dotnet restore
dotnet build
dotnet publish

**Inside ~/Desktop/helloworld/bin/Debug/netcoreapp1.1:**
$ ls
helloworld.deps.json              helloworld.pdb                    helloworld.runtimeconfig.json
helloworld.dll                    helloworld.runtimeconfig.dev.json publish

corerun helloworld.dll
Could not get full path: No such file or directory

Am I missing something obvious?

**Comment by gkhanna79** [comment]
You need to use _dotnet_ binary and do `dotnet <path to helloworld.dll>` and not usecorerun. The former is the way to run .NET Core applications (which is what your application above is).

**Comment by meherkasam** [comment]
The goal is to test my coreclr build locally. I cloned the coreclr repository, and followed all the instructions to do a build on a Mac. I then followed the instructions listed here to test my build: https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingCoreRun.md

The instructions listed here are, among other things:

> Consider that you already have a .NET application DLL called HelloWorld.dll and wish to run it (You could make such a DLL by using 'dotnet new' 'dotnet restore' 'dotnet build' in a 'HelloWorld' directory).

And execute: 
`corerun HelloWorld.dll`

**Comment by gkhanna79** [comment]
Did you set the paths as instructed on that link?

**Comment by meherkasam** [comment]
Yes, as I have already mentioned in my original post, I have set all the paths as instructed. This is what my ~/.bash_profile looks like:

export PATH="$PATH:/Users/meherk/Desktop/code/coreclr/bin/Product/OSX.x64.Debug"
export CORE_ROOT="/Users/meherk/Desktop/code/coreclr/bin/Product/OSX.x64.Debug"
export CORE_LIBRARIES="/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1"

**Comment by gkhanna79** [comment]
Per https://github.com/dotnet/coreclr/blob/d2d4a792e306097a7c7e8afd954eeb50f2d2f23e/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp#L70, looks like OSX is unable to get the path to corerun.

Does it work if you invoke corerun with the absolute path?

**Comment by meherkasam** [comment]
Different output this time: /Users/meherk/Desktop/code/coreclr/bin/Product/OSX.x64.Debug/corerun helloworld.dll

Unhandled Exception: System.TypeLoadException: Could not load type 'System.IO.TextWriter' from assembly 'System.IO, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Console.get_Out
   at System.Console.WriteLine(String value)
   at helloworld.Program.Main(String[] args)
Abort trap: 6

**Comment by gkhanna79** [comment]
Looks like you are now able to execute HelloWorld but running into missing assemblies. @weshaggard Where is TextWriter expected to be?

**Comment by weshaggard** [comment]
You are mixing the latest coreclr builds with the 1.1.1 builds of the corefx libraries which aren't compatible. Instead of doing this I would suggest you use dotnet and to consume your latest build use these instructions instead https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md.

**Comment by meherkasam** [comment]
I downloaded the latest nightly build of dotnet from your link. My path looks like this now:

`$PATH:/Users/meherk/Desktop/code/coreclr/bin/Product/OSX.x64.Debug:/Users/meherk/Desktop/dotnet-dev-osx-x64.latest`

I reran `dotnet new console, dotnet restore, and dotnet build` inside a new directory using this version. This is the error I see:

```
~/Desktop/helloworld/bin/Debug/netcoreapp2.0
$ /Users/meherk/Desktop/code/coreclr/bin/Product/OSX.x64.Debug/corerun helloworld.dll
coreclr_initialize failed - status: 0x80131524
```

**Comment by meherkasam** [comment]
Perfect! That worked for me. Thanks for all the help.
