### ISSUE TITLE
Math.Floor on Windows x86 handles `-0.0` differently

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#10288]
On all platforms, except x86 Windows, `Math.Floor(-0.0)` returns `-0.0`.

The IEEE spec does not directly specify a correct behavior here (just indirectly via the handling of -0 with regards to certain rounding modes), but the C11 spec does. Specifically, in `Annex F: IEC 60559 floating-point arithmetic`, it specifies:
> F.10.6.2 The floor functions
> — floor(±0) returns ±0.
> — floor(±∞) returns ±∞

**Comment by gkhanna79** [comment]
CC @danmosemsft

**Comment by danmosemsft** [comment]
As the standard is undefined this seems Future.

**Comment by tannergooding** [comment]
No, it is not critical. However, the workaround is trivial and could easily be done for 2.0.

The most current spec (ECMA 335:2012) indicates that the handling of floating point numbers (see I.12.1.3) is compliant with IEC 60559:1989 (which itself has been superseded by IEEE 754:2008).

Since the majority of our `System.Math` calls are FCALL implementations that call the corresponding CRT implementation, this actually represents a bug in the Windows CRT that should be fixed there as well.

We could also explicitly workaround this on our side, as we have done with other non-compliant calls in the past.

**Comment by danmosemsft** [comment]
Yeah, we're still taking all changes for 2.0 -- we haven't forked. But we're keeping the milestone for stuff we actually have to do to ship.

**Comment by tannergooding** [comment]
This was a bug with the `/fp:fast` implementation, I am logging internal bugs to track this.

**Comment by tannergooding** [comment]
Resolving since this is now tracked internally and the .NET implementation is behaving correctly.
