### ISSUE TITLE
[x86/Linux] How to create CLR unittest overlay?

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#10299]
The following failure have been observed while running x86/Linux CLR unittest (may be from 03/17?):
```
FAILED   - [ 631 :  147 sec ] Interop/ICastable/Castable/Castable.sh
               BEGIN EXECUTION
               /root/dotnet-test/coreclr_unittest_20170320_082336_x86_x86-emu/coreclr-unittest-170319-232419/Core_Root/corerun Castable.exe
               
               Unhandled Exception: System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ICastable' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
               ./Castable.sh: line 132: 15196 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" Castable.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```
This issue seems to be related with how we create an overlay. 

Here are the current stesp to create an overlay:
 1.  Copy TC stubs (files in "Tests/Core_Root")  into overlay
 1.  Copy FX artifacts into overlay
 1.  Copy CLR artifacts into overlay

I tried to use the following reversed steps:
 1.  Copy TC stubs (files in "Tests/Core_Root")  into overlay
 1.  Copy CLR artifacts into overlay
 1.  Copy FX artifacts into overlay

The latter approach seems to fix the above failure, but introduces new failures:
```
FAILED   - [ 6608 :    9 sec ] Loader/classloader/TypeInitialization/CircularCctors/CircularCctorFourThreadsBFI/CircularCctorFourThreadsBFI.sh
               BEGIN EXECUTION
               /root/dotnet-test/coreclr_unittest_20170320_091518_x86_x86-emu/coreclr-unittest-170320-001601/Core_Root/corerun CircularCctorFourThreadsBFI.exe
               
               Unhandled Exception: System.MethodAccessException: Attempt by method 'Test.Main()' to access method 'System.Threading.Thread..ctor(System.Threading.ThreadStart)' failed.
                  at Test.Main()
               ./CircularCctorFourThreadsBFI.sh: line 132: 25651 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" CircularCctorFourThreadsBFI.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```
The number of failures increases from 47 (with the former approach) into 83 (with the reversed approach).

This issue seems to be related with the recent changes on mscorlib facade, but I couldn't figure out how to address this.

**Comment by parjong** [comment]
@jkotas Could you let me know who is responsible to issues of this kine?

**Comment by jkotas** [comment]
cc @wtgodbe

**Comment by jkotas** [comment]
This was point in time problem caused by #10157 and other related changes. You should not see it anymore with current coreclr and corefx.

**Comment by jkotas** [comment]
Make sure to do a real clean build (e.g. delete bin directory).

**Comment by parjong** [comment]
@jkotas Thank you for comment. It turns out that real clean build and TC update are required to resolve this issue.
