### ISSUE TITLE
`Single.ToString` and `Double.ToString` do not differentiate between -0.0 and +0.0

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#10290]
This can cause significant confusion when debugging tests or strings where this differentiation matters.

**Comment by tarekgh** [comment]
@gkhanna79 why you think this is v2.0? we shipped like that before and even this is the behavior on the full framework. I am moving it to the future if you don't have any objection.

**Comment by tannergooding** [comment]
This also impacts IEEE compliance for floating-point values.

Namely 5.12.1 External character sequences representing zeros, infinities, and NaNs:
> The conversions (described in 5.4.2) from supported formats to external character sequences and back that recover the original floating-point representation, shall recover zeros, infinities, and quiet NaNs, as well as non-zero finite numbers. In particular, signs of zeros and infinities are preserved

This, much like https://github.com/dotnet/coreclr/issues/13106, would be a "breaking change" for `-0.0` -- CC. @jkotas, @eerhardt, @danmosemsft

**Comment by tannergooding** [comment]
Correct, today you cannot round trip `-0.0` (as it is always converted as just `0.0`, with no sign).
