### ISSUE TITLE
Unable to build coreclr repo __security_check_cookie_ex

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/coreclr#10298]
Portion of cmake errors while building with ".\build" after following the steps in the getting started on windows documentation and executing init-tools script:

```
    23>libucrtd.lib(invalid_parameter.obj) : error LNK2001: unresolved external symbol __security_check_cookie_ex [C:\Users\vikto\Documents\src\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]
    23>libucrtd.lib(input.obj) : error LNK2001: unresolved external symbol __security_check_cookie_ex [C:\Users\vikto\Documents\src\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]
    23>C:\Users\vikto\Documents\src\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\Debug\coreclr.dll : fatal error LNK1120: 1 unresolved externals [C:\Users\vikto\Documents\src\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]

Build FAILED.
    0 Warning(s)
    579 Error(s)

Time Elapsed 00:32:07.06
```

Error log file: 
[CoreCLR_Windows_NT__x64__Debug.zip](https://github.com/dotnet/coreclr/files/853730/CoreCLR_Windows_NT__x64__Debug.zip)

**Comment by ViktorHofer** [comment]
Error still occurs after reinstalling the tools in the correct order (first uninstall both, then VS17 and then cmake). Help is really appreciated

**Comment by RussKeldorph** [comment]
@gkhanna79 Is a VS2017 build known to work?

**Comment by ViktorHofer** [comment]
As described here it should: https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md

**Comment by gkhanna79** [comment]
@tannergooding Looked into enabling it and can comment on this.

**Comment by tannergooding** [comment]
There are still a couple issues building CoreCLR on VS2017 right now: https://github.com/dotnet/coreclr/issues/10056

However, AFAIK, the native build should work (at least it is working locally for me). @ViktorHofer, just to confirm, you are Running from a VS 2017 Developer Command Prompt, have the full set of required individual components installed, you have registered the `msdia120.dll` COM library, and you have CMake 3.7.2 or later installed, correct?

**Comment by ViktorHofer** [comment]
Yes running from Developer Command Prompt, all components as described in the docu i linked above are installed and cmake 3.7.2 x64_86 installed. Media120.dll registererd and python installed.

All steps done according to the documentation.

**Comment by tannergooding** [comment]
Well the failure seems to indicate that `BufferOverflowU.lib` or `BufferOverflow.lib` is not being properly referenced by the linker.

Could you grep your log and see if anything obvious pops out (my own log doesn't actually list anything related to `BufferOverflow`, but it is succeeding)?

**Comment by ViktorHofer** [comment]
Unfortunately there are also no occurence of anything related to buffer or overflow in my logs.

[CoreCLR_Windows_NT__x64__Debug.zip](https://github.com/dotnet/coreclr/files/855862/CoreCLR_Windows_NT__x64__Debug.zip)

**Comment by tannergooding** [comment]
I think your best bet here would be to do the following:
* `git clean -xdf`
* `set _echo = 1`
* `.\Build.cmd > Build.log`

and then attach the Build.log + CoreCLR_Windows_NT__x64_Debug.zip

My best guess here is that something is wrong with how one of the environment variables (`LIB` or maybe `PATH`) is being configured when the VC++ Toolchain is loaded. `BufferOverflow` should be coming from `C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x64` or `C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x64`

**Comment by ViktorHofer** [comment]
Followed your steps. Please find the logs in my attachment: 
[Build.zip](https://github.com/dotnet/coreclr/files/856019/Build.zip)

**Comment by tannergooding** [comment]
Still going through the logs, bug a couple of things immediately pop out:
1. NuGet fails to download
```
Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'www.nuget.org'"
At line:1 char:1
+ (New-Object Net.WebClient).DownloadFile('https://www.nuget.org/nuget. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```
2. You appear to have a newer version of the Win10 SDK installed (`10.0.15021.0` rather than `10.0.14393.0`)

**Comment by ViktorHofer** [comment]
The nuget error is probably because I built it while connected on my mobile phones hotspot.

I now uninstalled the Win10 SDK 10.0.15021.0 and now building again and it seems the __security_check_cookie_ex error is related to the new SDK as it hasn't pop up yet again. I will confirm that in a few minutes. Should be communicate that to the UWP team?

**Comment by tannergooding** [comment]
That would probably be the best route to take, as I don't think there is anything we can do here.

**Comment by ViktorHofer** [comment]
Escalated to the responsible product team and cc you.

**Comment by ViktorHofer** [comment]
Now native compilation seemed to work but failed afterwards. @tannergooding can you take on more look into it? Error is:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3260: Could not find any target framework profile redist files in the FullFrameworkFolders locations. [C:\Users\vikto\Documents\src\coreclr\src\ToolBox\SOS\NETCore\SOS.NETCore.csproj]
C:\Users\vikto\Documents\src\coreclr\Tools\Microsoft.CSharp.Core.targets(106,11): error MSB4064: The "OverrideToolHost" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property. [C:\Users\vikto\Documents\src\coreclr\src\ToolBox\SOS\NETCore\SOS.NETCore.csproj]
C:\Users\vikto\Documents\src\coreclr\Tools\Microsoft.CSharp.Core.targets(67,5): error MSB4063: The "Csc" task could not be initialized with its input parameters.  [C:\Users\vikto\Documents\src\coreclr\src\ToolBox\SOS\NETCore\SOS.NETCore.csproj]
  System.Private.CoreLib -> C:\Users\vikto\Documents\src\coreclr\bin\Product\Windows_NT.x64.Debug\System.Private.CoreLib.dll
```

Zip: [CoreCLR_Windows_NT__x64__Debug.zip](https://github.com/dotnet/coreclr/files/856422/CoreCLR_Windows_NT__x64__Debug.zip)

**Comment by tannergooding** [comment]
That is the issue I linked above: https://github.com/dotnet/coreclr/issues/10056

Passing in `/p:CSharpCoreTargetsPath=Roslyn\Microsoft.CSharp.Core.targets` should work (so `.\Build.cmd -- /p:CSharpCoreTargetsPath=Roslyn\Microsoft.CSharp.Core.targets`)

**Comment by tannergooding** [comment]
It looks like the solution is to use the Windows 10 SDK 15052 or higher (if using one of the preview SDK builds). @ViktorHofer is going to do a final validation on this and then we should be able to close the bug.

**Comment by ViktorHofer** [comment]
Tested on Windows 10 SDK 15052 on a fresh coreclr pull. Works fine now!
