### ISSUE TITLE
System.IO.Path.IsPathRooted does not check if valid drive letter on Windows

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/coreclr#10297]
While looking over the System.IO.Path class and its Windows implemented I noticed that the desired behavior stated in the method comment isn't what gets executed.

```
        // Tests if the given path contains a root. A path is considered rooted
        // if it starts with a backslash ("\") or a drive letter and a colon (":").
        public static bool IsPathRooted(string path)
        {
            if (path != null)
            {
                PathInternal.CheckInvalidPathChars(path);

                int length = path.Length;
                if ((length >= 1 && PathInternal.IsDirectorySeparator(path[0])) ||
                    (length >= 2 && path[1] == PathInternal.VolumeSeparatorChar))
                    return true;
            }
            return false;
        }
```
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/IO/Path.Windows.cs#128

With the current behavior the method would return true even if the first char is not a drive letter followed by a VolumeSeperatorChar. The second condition in the if statement should check if path[0] is drive letter. 

Am I correct? If yes, I am willing to implement the additional check.

**Comment by danmosemsft** [comment]
@JeremyKuhne

**Comment by JeremyKuhne** [comment]
I'm fine with making this more correct, would want @ianhays to chime in as well. `PathInternal.IsValidDriveChar()` can be used to validate.

**Comment by ianhays** [comment]
Seems reasonable to me.

**Comment by ViktorHofer** [comment]
I will submit a PR for that. If there would have been some tests with paths like "_:\\abc\\def" or "*:\\..." then the tests would all have passed. Maybe we should include more exception expected tests for future changes?

**Comment by JeremyKuhne** [comment]
> Maybe we should include more exception expected tests for future changes?

I think so :)

**Comment by mani-sn** [comment]
This is not a bug. Drive letter is any valid DOS device name and not necessarily a single letter.

Please refer the below two URL(s).

https://msdn.microsoft.com/en-us/library/windows/desktop/aa363908(v=vs.85).aspx

https://msdn.microsoft.com/en-us/library/windows/hardware/ff554302(v=vs.85).aspx

AA:, AB: AC: are valid driver letters.

FYI, Windows supports more than 26 drives. What would be the drive letter for 27th drive.

**Comment by danmosemsft** [comment]
@mani-sn I don't see mention of multi-character drive letters at the links above. @JeremyKuhne are you familiar with this?

**Comment by mani-sn** [comment]
DefineDosDevice() function still supports it but CreateFile and FindFirstFile no longer supports it. It seems that AA, AB and so on Windows 95 world and not Windows NT world.

**Comment by ViktorHofer** [comment]
@mani-sn If multi drive letters are supported on Windows NT, then we would need to rewrite a lot of code inside the System.IO.Path class in the coreclr.

**Comment by JeremyKuhne** [comment]
@mani-sn You can create dos device aliases of any name, but they can only be referenced as device paths (`\\.\` or `\\?\`). Device paths will always come back as rooted (as they start with a backslash) so we should be ok.

Only A-Z are recognized by normalization and converted into the "native" form of `\\?\A:\`. It is extremely unlikely that Windows will ever support logical drives outside of A-Z.

`GetLogicalDrives()`
https://msdn.microsoft.com/en-us/library/windows/desktop/aa364972.aspx

**Comment by safern** [comment]
@JeremyKuhne should we mark this as netfx-port-consider? As this behavior is different than desktop's behavior which returns true on this cases.
