### ISSUE TITLE
[Win][Build] tread C4819 as error,can't build on on-CP1252 windows.

### ISSUE THREAD

**Issue by binsys** [dotnet/coreclr#103]
tread C4819 as error,can't build on on-CP1252 windows,LIKE CP936(zh-CHS).

CMakeLists.txt
add_compile_options(/WX) # treat warnings as errors

need add "/wd4819" on add_compile_options.

**Comment by ellismg** [comment]
What file are you seeing this on?  What commit is your HEAD pointing at?  I thought that I fixed all these issues a few days ago.

We should be working to fix the source files, not disabling this warning.

**Comment by ellismg** [comment]
@binsys Are you still hitting this?  I believe this has been fixed and I'm going to close the issue if I don't hear back from you with information about what file you hit this on what commit your HEAD points at.

**Comment by binsys** [comment]
Sorry ,my source code tree is out of date,you are right.
