### ISSUE TITLE
Linux tests depends on Windows build.

### ISSUE THREAD

**Issue by mazong1123** [dotnet/coreclr#10308]
According to [this doc](https://github.com/dotnet/coreclr/blob/master/Documentation/building/unix-test-instructions.md), running the tests on Linux requires a Windows build (`--testRootDir=~/test/Windows_NT.x64.Debug`). It's a bit awkward as coreclr should be cross platform.

Do we have any plan to get rid of the Windows build for Linux tests? Or is there any particular reason for keeping the relationship between Linux tests and Windows build?

**Comment by RussKeldorph** [comment]
#8891

**Comment by RussKeldorph** [comment]
Closing as duplicate of #8891.
