### ISSUE TITLE
Thread.MemoryBarrier() not available in dnxcore50

### ISSUE THREAD

**Issue by damianh** [dotnet/coreclr#1031]
I am attempting to port [nowin](https://github.com/Bobris/Nowin). It appears `Thread.MemoryBarrier()` is not available in dnxcore50. I don't know if this is by design or not. 

![image](https://cloud.githubusercontent.com/assets/57436/7749513/66df1a36-ffce-11e4-83e8-e1c6a7f44a93.png)

**Comment by akoeplinger** [comment]
[Interlocked.MemoryBarrier](https://msdn.microsoft.com/en-us/library/system.threading.interlocked.memorybarrier(v=vs.110).aspx) should be available in core.

**Comment by damianh** [comment]
will try it..

**Comment by damianh** [comment]
worked :+1:  Thanks @akoeplinger
