### ISSUE TITLE
[arm64] GitHub_9891asserting

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#10316]
New test introduced in the fix for #9891 is asserting

JIT/Regression/JitBlue/GitHub_9891/GitHub_9891/GitHub_9891.sh

```
corerun GitHub_9891.exe

Assert failure(PID 32121 [0x00007d79], Thread: 32121 [0x7d79]): Assertion failed 'op1->gtOper == GT_LCL_VAR' in 'B:Main(ref):int' (IL size 50)

    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/importer.cpp Line: 9927
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr0/Tests/coreoverlay/corerun
```

@dotnet/arm64-contrib

**Comment by AndyAyersMS** [comment]
Are you sure you also picked up the fix in importer.cpp?

**Comment by sdmaclea** [comment]
@AndyAyersMS  Failure occurred while testing d905f67 in CI.  I didn't explicitly do a clean build but usually that has not given me trouble.  I can  do a clean build and see if it recurs.

**Comment by AndyAyersMS** [comment]
The test should fail like that without the accompanying fix. If you see it failing with the fix then please let me know. The line number 9927 indicates the version of importer.cpp is somewhat older than the latest.

**Comment by sdmaclea** [comment]
There is something wrong with my CI system this is not an issue with the tip.
