### ISSUE TITLE
ExectionContext is duplicated in 2 packages (dnxcore50)

### ISSUE THREAD

**Issue by damianh** [dotnet/coreclr#1032]
I have the following references in my dnxcore50 project:

              "System.Threading": "4.0.10-beta-22816",
              "System.Threading.ExecutionContext": "4.0.0-beta-22416",

Compiling gives me:

`The type 'ExecutionContext' exists in both 'System.Threading.ExecutionContext, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	Nowin.DNX Core 5.0	C:\dev\Nowin\Nowin\ExecutionContextFlowSuppresser.cs	29`

![image](https://cloud.githubusercontent.com/assets/57436/7749564/d2144754-ffce-11e4-8a99-ae07bb113a27.png)

Removing `System.Threading.ExecutionContext` package gives me the following compilation error:

`Error	CS0117	'ExecutionContext' does not contain a definition for 'IsFlowSuppressed'	Nowin.DNX Core 5.0	C:\dev\Nowin\Nowin\ExecutionContextFlowSuppresser.cs	29`

![image](https://cloud.githubusercontent.com/assets/57436/7749621/36d0fa5c-ffcf-11e4-9173-358d62b3463d.png)

Project can be viewed here: https://github.com/damianh/Nowin/tree/dnx

**Comment by kangaroo** [comment]
This should probably be moved to the corefx repo?

**Comment by davidfowl** [comment]
Yep

**Comment by davidfowl** [comment]
The problem is the versions. You're using a super old threading contract

**Comment by damianh** [comment]
@kangaroo I searched the repositories for [`ExecutionContext`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/ExecutionContext.cs) which is why I reported it here. Shall I move it?

**Comment by damianh** [comment]
@davidfowl I used the latest ones available on nuget.org https://github.com/damianh/Nowin/blob/dnx/Nowin/project.json#L28-L30
https://www.nuget.org/packages/System.Threading/4.0.10-beta-22816
https://www.nuget.org/packages/System.Threading.Thread/4.0.0-beta-22816

Is there later ones elsewhere?

**Comment by ggrnd0** [comment]
in myget [aspnetvnext](https://www.myget.org/gallery/aspnetvnext) feed 

    System.Threading	        v4.0.10-beta-22913	      1 week ago
    System.Threading.Thread	    v4.0.0-beta-22913         1 week ago

**Comment by damianh** [comment]
I think we might have abused the term `beta` a little bit here. :)

**Comment by davidfowl** [comment]
@damianh Can you open this on Corefx
