### ISSUE TITLE
Tests fail to build with VS2015

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#1033]
Run: build.cmd vs2015

C:\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\packageresolve.targets(25,5): error MSB4062: The "ResolveNuGetPackages" task could not be loaded from the assembly C:\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\Microsoft.DotNet.Build.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\coreclr\tests\src\Threading\ThreadStatics\cs_template.proj]

**Comment by jkotas** [comment]
Hopefully, the last issue for #30

**Comment by jkotas** [comment]
@AlexGhiondea @ramarag Any ideas?

**Comment by ramarag** [comment]
I will look into adding the support, I believe we just need to Update the Microsoft.DotNet.BuildTools

**Comment by jasonwilliams200OK** [comment]
* I installed VS2015 Professional RC.
* Installed cmake.
* In powershell: 

  ```powershell
  cd /projects
  git clone https://github.com/dontnet/coreclr/ --recursive
  cd coreclr
  .\build vs2015
  # couple of minutes later:
  # <verbose output here>
  # and finally:
 #
  # Repo successfully built.

  # Product binaries are available at C:\projects\coreclr\bin\Product\Windows_NT.x64.Debug
  # Test binaries are available at C:\projects\coreclr\bin\tests\Windows_NT.x64.Debug
  ```

Running Windows 8 Pro x64.

Seems to be building just fine here, without any modification..

**Comment by DickvdBrink** [comment]
Works for me too!
```
Repo successfully built.

Product binaries are available at C:\Users\Dick\Desktop\microsoft\coreclr\bin\Pr
oduct\Windows_NT.x64.Debug
Test binaries are available at C:\Users\Dick\Desktop\microsoft\coreclr\bin\tests
\Windows_NT.x64.Debug
```

Also VS2015 RC one small issue, had to remove `Xamarin` for it to work, see issue #927
