### ISSUE TITLE
Support Windows Minidump collection

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#10334]
Today if you try to collect a mini or triage dump on Windows none of the information relevant for debugging a stack trace through jitted code is collected. This renders Windows Error Reporting largely useless, as well as causing problems for other diagnostic scenarios that would like to use minidumps.

The root cause of the problem is .Net Core doesn't have access to the same extensibility mechanism in MiniDumpWriteDump that the desktop and .Net Native CLR implementations use. The current extensibility mechanism provided by the OS requires registering a dll in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\MiniDumpAuxiliaryDlls. That registry location requires admin privileges and can't be set when .Net Core installation is limited to xcopy only.

Proposed solution:
We have coordinated with the Windows OS team to design an additional extensibility mechanism to MiniDumpWriteDump. In lieu of admin privileges and registry edits, this one uses authenticode signature verification to ensure security and reads the PE resources in loaded modules for discovery. Specifically MiniDumpWriteDump will scan each module in the dump process looking for any resources with name=DUMP_HELPER, type=RT_RCDATA, lang=neutral. The resource contains the UTF8 encoded, null terminated name of a minidump auxilliary provider dll that is located in the same directory as the binary with the resource in it. After discovery and signature verification, MiniDumpWriteDump uses the minidump auxilliary provider no differently than if it had been loaded using the pre-existing registry technique.

**Comment by lt72** [comment]
Work is committed on Windows side and shipping with next Windows release in September time frame (RS3).

**Comment by noahfalk** [comment]
@leculver confirmed to me offline a little while ago that .Net Core minidumps are working now so resolving this issue.
