### ISSUE TITLE
Modify Platform ID of native images for Linux

### ISSUE THREAD

**Issue by JohnChen0** [dotnet/coreclr#1035]
Currently native images for Linux use the same Platform ID as those for Windows. This makes it harder to diagnose when Linux native images are accidentally used on Windows, or vice versa. A different Platform ID should be assigned instead.

**Comment by kangaroo** [comment]
Please also extend to have a PlatformID for OS X and FreeBSD at the same time.

**Comment by JohnChen0** [comment]
Fixed with commit ef310df.
