### ISSUE TITLE
Opening Corelib.csproj in VS triggers two warning dialogs.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/coreclr#10358]
"A file with the name 'SR.cs' already exists. Replace it?"

This started happening after I fetched the corelib-resx change.

This suggests the SR.cs generation step is incorrectly running during the design-time build.

**Comment by AtsushiKan** [comment]
cc @alexperovich

**Comment by AtsushiKan** [comment]
@alexperovich - any update on this? 

After some experimentation, it's trying to overwrite mscorlib\Common\System\SR.cs.

Deleting the file silences the dialog (but does not cause replacement of the file either.)

**Comment by alexperovich** [comment]
I haven't been able to look at this yet. Do you have a diag log I can look at?

**Comment by AtsushiKan** [comment]
The issue is that resource.targets is adding Common\System\SR.cs to the Compile list multiple times while the project is being loaded.

This change silences the dialog while still allowing the build to work (I haven't tested thoroughly)

https://github.com/dotnet/coreclr/compare/master...AtsushiKan:ann-wip

There's also this line:

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/System.Private.CoreLib.csproj#L981

which is triggering a warning that this is the second time resource.targets is being imported.

(c:\dd\CoreClr\src\mscorlib\System.Private.CoreLib.csproj(981,3): warning MSB4011: "c:\dd\CoreClr\Tools\resources.targets" cannot be imported again. It was already imported at "c:\dd\CoreClr\Tools\Build.Common.targets (187,3)". This is most likely a build authoring error. This subsequent import will be ignored. )

I'm not sure if this related but it should be cleaned up anyway.
