### ISSUE TITLE
[x86/Linux] LSRA gtLsraInfo.srcCount value for long type

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#10373]
While working with `FEATURE_FIXED_OUT_ARGS`, #10034, next problem I encounted is an assert on `src/jit/lsra.cpp Line: 3512`,
`Assert failure(PID 13202 [0x00003392], Thread: 13202 [0x3392]): Assertion failed '((consume == 0) && (produce == 0)) || (ComputeAvailableSrcCount(tree) == consume)' in 'ConsoleApplication.Program:DoTest()' (IL size 24)`

This happens when call has a long type argment and it gets `gtLsraInfo.srcCount` to some wrong value 1 but should get 2. I get `ComputeAvailableSrcCount(tree)` value to 2 when I call this.

I've trace the sequnce for this and first it was set to 2 in `Lowering::TreeNodeInfoInit()` by 
```
#ifdef FEATURE_PUT_STRUCT_ARG_STK
        case GT_PUTARG_STK:
            LowerPutArgStk(tree->AsPutArgStk());
            TreeNodeInfoInitPutArgStk(tree->AsPutArgStk()); <---  inside here, srcCount is set to 2
            break;
#endif // FEATURE_PUT_STRUCT_ARG_STK
```
and then to 1 with
```
        case GT_CALL:
            TreeNodeInfoInitCall(tree->AsCall()); <--- and then to 1 afterwards
            break;
```

It seems that `Lowering::TreeNodeInfoInitCall()` doesn't consider for x86.
```
        if (curArgTabEntry->regNum == REG_STK)
        {
            // late arg that is not passed in a register
            DISPNODE(argNode);
            assert(argNode->gtOper == GT_PUTARG_STK);
            argNode->gtLsraInfo.srcCount = 1;
            argNode->gtLsraInfo.dstCount = 0;
```

category:correctness
theme:register-allocator
skill-level:expert
cost:small

**Comment by seanshpark** [comment]
CC @YongseopKim

**Comment by seanshpark** [comment]
This seesm to resolve the problem.
```
diff --git a/src/jit/lsraxarch.cpp b/src/jit/lsraxarch.cpp
index 002e3d8..c91e85e 100644
--- a/src/jit/lsraxarch.cpp
+++ b/src/jit/lsraxarch.cpp
@@ -1410,6 +1410,13 @@ void Lowering::TreeNodeInfoInitCall(GenTreeCall* call)
 
         if (curArgTabEntry->regNum == REG_STK)
         {
+#if defined(UNIX_X86_ABI) && FEATURE_FIXED_OUT_ARGS
+            if (argNode->TypeGet() != TYP_STRUCT)
+            {
+                continue;
+            }
+#endif // UNIX_X86_ABI && FEATURE_FIXED_OUT_ARGS
+
             // late arg that is not passed in a register
             DISPNODE(argNode);
             assert(argNode->gtOper == GT_PUTARG_STK);
```

**Comment by CarolEidt** [comment]
I believe that this is no longer an issue.
