### ISSUE TITLE
Migrating a VS 2015 solution to VS 2017 does not stick

### ISSUE THREAD

**Issue by andre-artus** [dotnet/coreclr#10389]
I have migrated a solution with .NET Core projects from 2015 to 2017, seems to work. Can build, run, publish, all the good things. 

But, when I close the solution and try to reopen it I get a "needs migration" message on the projects and the projects do not load. When this happened at first I thought maybe something went wrong so I reverted to the old state and did everything again. I'm still having the issue. I cannot work like this constantly reverting and re-migrating.

**Comment by weshaggard** [comment]
Issue moved to [dotnet/sdk #1030](https://github.com/dotnet/sdk/issues/1030) via [**ZenHub**](https://www.zenhub.com/)
