### ISSUE TITLE
>50% of tests are failing under GCStress=0xF

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#10396]
#10322 failed to fix all the gcStress issues

@swgillespie @pgavlin

**Comment by sdmaclea** [comment]
Ran a random sampling of 100 passing tests with GCStress0xF  55 of 100 are failing.  Using 992d370 

Yesterday I had run a full gcStress0xF run with 109 failures in 10797 tests.  This used cd9b5e7  with a revert of #10065

**Comment by swgillespie** [comment]
@sdmaclea What sort of failures? Are they the same assertion that was failing earlier?

**Comment by sdmaclea** [comment]
@swgillespie When I look at the failures they look different.  It looks like the random samle was not random at all but picked known failing tests.

**Comment by sdmaclea** [comment]
@swgillespie My apologies.  It is working on tip with your patch.

**Comment by swgillespie** [comment]
Great! Glad to hear it!
