### ISSUE TITLE
System.Reflection.IReflectable missing [Guid] attribute.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/coreclr#10393]
Problem is, GuidAttribute lives in S.P.Interop.dll. So we'll probably to move it to CoreLib.

After this, IReflectable.cs should be moved to the shared partition.

**Comment by AtsushiKan** [comment]
Bah - opened in wrong repo.

**Comment by jkotas** [comment]
Also, I do not see GuidAttribute on IReflectable... .

**Comment by AtsushiKan** [comment]
That was a typo in the issue. The affected type is IReflect.

**Comment by jkotas** [comment]
It should be fine to remove the guid attribute on IReflect. I do not think it is needed in .NET Core. It was done in other places: https://github.com/dotnet/coreclr/commit/3e897075b1ab5afb914671ccca240b5e41116242#diff-6ea37a5b007350ae2cdb9dfef6b80d61L25

**Comment by jkotas** [comment]
(However, moving GuidAttribute to CoreLib sounds reasonable too.)
