### ISSUE TITLE
hosting coreclr on mac

### ISSUE THREAD

**Issue by JohnGorter** [dotnet/coreclr#10452]
Dont know if there is a better place to ask this question, but hosting assemblies on my mac always seems to fail:

void* clr_host;
unsigned int domainId;
void *coreclr = dlopen("/<abs-path-to>/coreclr/bin/Product/OSX.x64.Debug/libcoreclr.dylib", RTLD_NOW | RTLD_LOCAL);
    
    // if the lib is not found or loaded, escape...
    if (coreclr == nullptr) return -1;
    
    // grab the coreclr function pointer...
    coreclr_initialize_ptr coreclr_init = reinterpret_cast<coreclr_initialize_ptr>(dlsym(coreclr, "coreclr_initialize"));
    coreclr_create_delegate_ptr coreclr_delegate = reinterpret_cast<coreclr_create_delegate_ptr>(dlsym(coreclr, "coreclr_create_delegate"));

    
    const char * app_path =  "/<abs-path-to>/test.dll";
    const char * framework = "/abs=path-to>/coreclr/bin/Product/OSX.x64.Debug";
    
    std::string tpa_list = std::string();
    AddFilesFromDirectoryToTpaList(framework, tpa_list);
    
    const char *property_keys[] = { "APP_PATHS", "TRUSTED_PLATFORM_ASSEMBLIES" };
    const char *property_values[] = { app_path, tpa_list.c_str() };
    
   int ret = coreclr_init(
                           app_path,                               // exePath
                           "host",                                 // appDomainFriendlyName
                           sizeof(property_values)/sizeof(char *), // propertyCount
                           property_keys,                          // propertyKeys
                           property_values,                        // propertyValues
                           &clr_host,                            // hostHandle
                           &domainId                              // domainId
                           );

The outcome is always HRESULT 0x80131534.. The clr_host is always NULL upon return.. What am I doing wrong here?

Thanx!
John

**Comment by janvorli** [comment]
@JohnGorter the error code means:
```xml
<HRESULT NumericValue="0x80131534">
	<SymbolicName>COR_E_TYPEINITIALIZATION</SymbolicName>
	<Message>"Uncaught exception during type initialization."</Message>
	<Comment> An exception was thrown by a type's initializer (.cctor).</Comment>
</HRESULT>
```
So I guess you are missing some assemblies or have some other mismatch.
From your sample, it looks like you are adding just coreclr's products to the TPA. But that's not enough, you also need other assemblies from corefx, some native shared libraries from corefx and some assemblies that I believe come from nuget packages.

There are various ways how you could put them together. If you want to be on a pure "build everything yourself" plan, then you can clone and build corefx repo too. Finally, you'll need some addition assemblies. The way I use to get them is to build coreclr tests. That would generate a Core_Root folder in its bin folder subtree. Now the tests can only built on Windows, but there is someone finishing the work to make it possible to build the tests on Unix too.

Then to create a folder with all the assemblies you need, you'd copy all the stuff from Core_Root, then copy all files from bin/runtime/netcoreapp-OSX-Debug-x64/ in the CoreFX tree to the target folder and finally all files from coreclr/bin/Product/OSX.x64.Debug. Please note that the order is important.

After that, your host should work. 

Another way that should work and that might be easier for you is to publish your app using the dotnet tool for the OSX rid (passing --runtime osx.10.12-x64 to dotnet publish) as standalone, which would gather all the dependencies. You would then copy over all the files from the bin/runtime/netcoreapp-OSX-Debug-x64/ and finally all files from coreclr/bin/Product/OSX.x64.Debug.
While this should work, I have not verified it.

**Comment by JohnGorter** [comment]
Hi! Thanx for the reply..

So I've built the complete repo from github.. This should build all required dependencies, am I correct?

**Comment by janvorli** [comment]
If you build just the coreclr repo, it builds only System.Private.CoreLib.dll managed assembly and some native components. The CoreFX and CoreCLR are needed together.

**Comment by JohnGorter** [comment]
I run ./build.sh on the root of the coreclr repo.... doesnt this build it all?

**Comment by janvorli** [comment]
@JohnGorter no, it does not. It only builds coreclr stuff.

**Comment by JohnGorter** [comment]
So, another option would be to just install and point to artifacts from a prebuilt version of the .net framework?

**Comment by janvorli** [comment]
@JohnGorter yes. Unless you want to debug coreclr runtime or use the most up to date stuff that was not published as prebuilt package yet, that should work for you too.

**Comment by janvorli** [comment]
@JohnGorter btw, there is an ongoing effort to enable "build everything from source using a single build command", which is what you have obviously expected to get from building the coreclr repo.

**Comment by JohnGorter** [comment]
I've tried to use the prebuilt version to host an assembly:

       void *hostHandle;
    unsigned int domainId;
    unsigned int exitcode = 0;
    
    const char *propertyKeys[] = {"TRUSTED_PLATFORM_ASSEMBLIES"};
    const char *propertyValues[] = {"/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1/System.Runtime.dll:/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1/mscorlib.dll:/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1/System.Console.dll:/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1/System.IO.dll:/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1/System.Threading.dll:/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1/System.IO.FileSystem.Primitives.dll:/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1/System.Runtime.Handles.dll:/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1/System.Text.Encoding.dll:/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1/System.Runtime.Extensions.dll:/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.1/System.Threading.Tasks.dll"};
    void *pLib = dlopen("/abs-path-to>/coreclr/bin/Product/OSX.x64.Debug/libcoreclr.dylib",RTLD_NOW|RTLD_LOCAL);
    coreclr_initialize_ptr initPtr = (coreclr_initialize_ptr)dlsym(pLib,"coreclr_initialize");
    coreclr_execute_assembly_ptr execPtr = (coreclr_execute_assembly_ptr)dlsym(pLib,"coreclr_execute_assembly");
    coreclr_shutdown_ptr shutdownPtr = (coreclr_shutdown_ptr)dlsym(pLib,"coreclr_shutdown");
    int st = initPtr("/<project-path>","host",1,propertyKeys,propertyValues,&hostHandle,&domainId);
    printf("%x\n",st);
    if (st >= 0)
    {
        st = execPtr(hostHandle,domainId,0,NULL,"Test.dll", &exitcode);
        if (st >= 0)
        {
            printf("Exitcode: %x\n",exitcode);
        }
        shutdownPtr(hostHandle,domainId);
    }
    dlclose(pLib);


But keep getting errors on initialize, the error 0x80131524 COR_E_DLLNOTFOUND..

Any ideas?

John

**Comment by janvorli** [comment]
@JohnGorter the problem could be realated to the fact that you are loading libcoreclr.dylib that you have built, but mixing it with the files from the prebuilt package. The libcoreclr.so must always match the mscorlib.dll and System.Private.CoreLib.dll, they have to come from the same build and their build flavor (checked/debug/release) also must match. Also the managed assemblies that are in the prebuilt package and that came from corefx have to be compatible with the coreclr stuff. There were some shuffles from coreclr to corefx in the recent past and so using libcoreclr / mscorlib.dll / System.Private.CoreLib.dll built from current coreclr sources would likely not work with the stuff from the 1.1.1 package. That's why I was talking about getting all the corefx  and coreclr stuff if you wanted to use libcoreclr.so that you built yourself.

Anyways, I have used a copy of your code on my Ubuntu, only modified to use .so instead of dylib, used my own paths to assemblies and the libcoreclr from the prebuilt package and running a simple hello world app worked.
You can see the whole file here:
https://gist.github.com/janvorli/5a9ebfa6fe8bcf49840002f5044697cd

Compiled with `clang++ -g ./host.cpp -ldl -o host`

**Comment by JohnGorter** [comment]
You were absolutely correct and it makes total sense. Loading the dylib and added wrong versions of the dependencies..  Thanx again J! 

By the way, wouldn't it be possible for the dylib to dynamically load its dependencies instead of explicitly supplying them?

**Comment by gkhanna79** [comment]
@JohnGorter Can this be closed?

**Comment by danmosemsft** [comment]
I'll close this given there's no reply @JohnGorter feel free to reopen.

**Comment by JohnGorter** [comment]
Yes. This issue can be closed! Sorry for the late reply, missed the previous question. Thnx!
