### ISSUE TITLE
Potential JIT issue with nested structs in Release mode

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#10481]
Originally I filed this issue on corefxlab thinking it was a fast span issue on .NET Core 2.0 https://github.com/dotnet/corefxlab/issues/1374. I was able to reproduce the issue without span:

```C#
public struct BytesReader2
{
    ArraySegmentWrapper _unreadSegments;
    ArraySegment<byte> _currentSegment;

    public BytesReader2(ArraySegmentWrapper bytes)
    {
        _unreadSegments = bytes;
        _currentSegment = _unreadSegments.First;
    }

    public bool IsEmpty => _currentSegment.Count == 0;
}

public struct ArraySegmentWrapper
{
    ArraySegment<byte> _first;

    public ArraySegment<byte> First => _first;

    public ArraySegmentWrapper(ArraySegment<byte> first)
    {
        _first = first;
    }
}

[Fact]
public void DataShouldNotBeEmpty()
{
    var data = new byte[] { 1 };
    var segment = new ArraySegment<byte>(data);
    var wrapper = new ArraySegmentWrapper(segment);
    var reader2 = new BytesReader2(wrapper);
    Assert.False(reader2.IsEmpty);
}
```

This test only fails in **Release** mode, it works fine in **Debug**. 

If you change the constructor of `BytesReader2` from this:

```C#
    public BytesReader2(ArraySegmentWrapper bytes)
    {
        _unreadSegments = bytes;
        _currentSegment = _unreadSegments.First;
    }
```

To this:

```C#
    public BytesReader2(ArraySegmentWrapper bytes)
    {
        _unreadSegments = bytes;
        _currentSegment = bytes.First;
    }
```

It works as expected.

**EDIT:** This also works:

```C#
    [MethodImpl(MethodImplOptions.NoInlining)]
    public BytesReader2(ArraySegmentWrapper bytes)
    {
        _unreadSegments = bytes;
        _currentSegment = _unreadSegments.First;
    }
```

Here's the ASM:

Buggy version:

```C#
public BytesReader2(ArraySegmentWrapper bytes)
{
    _unreadSegments = bytes;
    _currentSegment = _unreadSegments.First;
}
```

```
var reader2 = new BytesReader2(wrapper);
00007FFCCAB704CC  vmovdqu     xmm0,xmmword ptr [rsp+58h]  
00007FFCCAB704D3  vmovdqu     xmmword ptr [rsp+28h],xmm0  
00007FFCCAB704DA  vmovdqu     xmm0,xmmword ptr [rsp+28h]  
00007FFCCAB704E1  vmovdqu     xmmword ptr [rsp+38h],xmm0  
00007FFCCAB704E8  mov         ecx,1  
00007FFCCAB704ED  call        00007FFCCAB70300
```

Using locals in the ctor:

```C#
public BytesReader2(ArraySegmentWrapper bytes)
{
    _unreadSegments = bytes;
    _currentSegment = bytes.First;
}
```

```
var reader2 = new BytesReader2(wrapper);
00007FFCCAB604CC  vmovdqu     xmm0,xmmword ptr [rsp+58h]  
00007FFCCAB604D3  vmovdqu     xmmword ptr [rsp+28h],xmm0  
00007FFCCAB604DA  vmovdqu     xmm0,xmmword ptr [rsp+28h]  
00007FFCCAB604E1  vmovdqu     xmmword ptr [rsp+38h],xmm0  
00007FFCCAB604E8  vmovdqu     xmm0,xmmword ptr [rsp+28h]  
00007FFCCAB604EF  vmovdqu     xmmword ptr [rsp+48h],xmm0  
00007FFCCAB604F6  cmp         dword ptr [rsp+54h],0  
00007FFCCAB604FB  sete        cl  
00007FFCCAB604FE  movzx       ecx,cl  
00007FFCCAB60501  call        00007FFCCAB60300  
```

No inlining:

```
[MethodImpl(MethodImplOptions.NoInlining)]
public BytesReader2(ArraySegmentWrapper bytes)
{
    _unreadSegments = bytes;
    _currentSegment = _unreadSegments.First;
}
```

```
var reader2 = new BytesReader2(wrapper);
00007FFCCAB604CC  lea         rcx,[rsp+38h]  
00007FFCCAB604D1  vmovdqu     xmm0,xmmword ptr [rsp+58h]  
00007FFCCAB604D8  vmovdqu     xmmword ptr [rsp+28h],xmm0  
00007FFCCAB604DF  lea         rdx,[rsp+28h]  
00007FFCCAB604E4  call        00007FFCCAB600A8  
00007FFCCAB604E9  cmp         dword ptr [rsp+54h],0  
00007FFCCAB604EE  sete        cl  
00007FFCCAB604F1  movzx       ecx,cl  
00007FFCCAB604F4  call        00007FFCCAB60300  
00007FFCCAB604F9  nop  
```

/cc @russellhadley

**Comment by mikedn** [comment]
@davidfowl @benaadams What's up? Are you expecting they fix this bug in the weekend? 😁

**Comment by davidfowl** [comment]
Just making sure I add the right people 😄

**Comment by mikedn** [comment]
The JIT drops assignment `_currentSegment = _unreadSegments.First;` on the floor:
```
fgMorphTree BB05, stmt 13 (before)
[000129] ----G-------             /--*  FIELD     struct _first
[000125] ----G-------             |  \--*  ADDR      byref 
[000126] ----G-------             |     \--*  FIELD     struct _unreadSegments
[000127] L-----------             |        \--*  ADDR      byref 
[000128] ------------             |           \--*  LCL_VAR   struct V04 loc3         
[000135] -A--G---R---             *  ASG       struct (copy)
[000134] ----G-------             \--*  OBJ(16)   struct
[000130] ----G-------                \--*  ADDR      byref 
[000131] ----G-------                   \--*  FIELD     struct _currentSegment
[000132] L-----------                      \--*  ADDR      byref 
[000133] ------------                         \--*  LCL_VAR   struct V04 loc3         

fgMorphCopyBlock:block assignment to morph:
[000128] -----+-N----             /--*  LCL_FLD   struct V04 loc3         [+0] Fseq[_unreadSegments, _first]
[000135] -A--G---R---             *  ASG       struct (copy)
[000134] ----G+------             \--*  OBJ(16)   struct
[000130] ----G+------                \--*  ADDR      byref 
[000133] U----+-N----                   \--*  LCL_FLD   struct V04 loc3         [+16] Fseq[_currentSegment]

fgMorphTree BB05, stmt 13 (after)
[000207] -----+------             *  NOP       void  
```
The first transform appears to be correct, it produces 2 `GT_LCL_FLD` with appropriate field offsets. But the second transforms [thinks](https://github.com/dotnet/coreclr/blob/master/src/jit/morph.cpp#L9757) that the assignment is useless because the same lclvar is involved in both LHS and RHS:

```C++
if ((destLclVar != nullptr) && (srcLclVar == destLclVar))
{
    // Beyond perf reasons, it is not prudent to have a copy of a struct to itself.
    GenTree* nop = gtNewNothingNode();
    INDEBUG(nop->gtDebugFlags |= GTF_DEBUG_NODE_MORPHED);
    return nop;
}
```
Looks like this code should take field offsets into consideration.

This looks like fallout from #8057.

**Comment by RussKeldorph** [comment]
@BruceForstall If there is a better person to fix it (who is available), feel free to reassign.

**Comment by briansull** [comment]
@JosephTremoulet Is also looking into this

**Comment by JosephTremoulet** [comment]
Yeah, sorry, should have assigned to myself.  I'll do that now, but @BruceForstall (or @mikedn) let me know if you're already working up a fix and we'll avoid duplicating the work.

@mikedn, thanks for the analysis.  Looks like the assumption that the whole lclVar is made throughout the function, so the fix will just need some care to figure out make sure all the right parts change.  And I'm curious why we wouldn't have hit this before; structs within structs aren't exactly rare,..

**Comment by mikedn** [comment]
> let me know if you're already working up a fix and we'll avoid duplicating the work.

Sorry, I don't dare touching that particular code and morph code in general :)

> Looks like the assumption that the whole lclVar is made throughout the function, so the fix will just need some care to figure out make sure all the right parts change.

Yes, I noticed that. It does extract the FieldSeq info but I don't think that can be used in this case, only the offset is safe.

> And I'm curious why we wouldn't have hit this before; structs within structs aren't exactly rare,..

Perhaps they aren't that rare but the combination we have here is not that common:
* copying from a field of a struct to another field of that struct
* the struct value has to be stored in a lclvar (in this particular example this required inlining to happen)

**Comment by JosephTremoulet** [comment]
> the assumption that the whole lclVar is [read/written is] made throughout the function

It looks like the places making that assumption are guarded by `destDoFldAsg`/`srcDoFldAsg`, which we only set if we're reading/writing the entire lclVar in question, so I think it really is just this one check that needs updating.


> It does extract the FieldSeq info but I don't think that can be used in this case, only the offset is safe.

Can you explain why / what you mean by "safe"?  The [path where dest is a `GT_LCL_FIELD`](https://github.com/dotnet/coreclr/blob/master/src/jit/morph.cpp#L9627-L9632) fails to set it [like the analogous case for src](https://github.com/dotnet/coreclr/blob/master/src/jit/morph.cpp#L9711-L9714), but assuming we fix that then I'd expect checking field sequence equality would be correct -- `IsLocalAddrExpr` appears to only return true when it has a valid field sequence.

**Comment by mikedn** [comment]
> Can you explain why / what you mean by "safe"?

What happens if explicit struct layout is used and 2 fields have the same offset? I suppose that we'll conclude that the fields are different and perform the copy even if it's not necessary. I would expect that in the worst case that would be just a CQ issue (and a really exotic one) but maybe there's a correctness issue as well? I don't know why the existing code comment says "it is not prudent to have a copy of a struct to itself".

**Comment by JosephTremoulet** [comment]
> What happens if explicit struct layout is used and 2 fields have the same offset? I suppose that we'll conclude that the fields are different and perform the copy even if it's not necessary. I would expect that in the worst case that would be just a CQ issue (and a really exotic one)

That's what I'd expect too


>maybe there's a correctness issue as well? I don't know why the existing code comment says "it is not prudent to have a copy of a struct to itself".

Yeah, that comment is a bit troubling.  I can't figure what the issue would be (partially-but-not-exactly-overlapping copies have memmove-vs-memcpy issues, but dropping the copy on the floor wouldn't make it more correct...), will try to poke around a bit before sending out PR.

**Comment by JosephTremoulet** [comment]
> Yeah, that comment is a bit troubling... will try to poke around a bit

The comment was added (with the check) in #7967 (technically in #8057 which #7967 got folded into) -- there's an explanation there:

> This was a case where we reused a struct temp, and then it wound up eventually getting assigned the value it originally contained, so we had V09 = V09. This hit the assert in liveness where it wasn't expecting to find a struct assignment with the same lclVar on the lhs and rhs. This assert should have been eliminated with the IR change to struct assignments, but when this situation arises we may run into issues if we call a helper that doesn't expect the lhs and rhs to be the same. So, change morph to eliminate such assignments.

Since clearly we need to generate the copy in this case, the assertion in liveness needs to accomodate this pattern (haven't checked yet whether that assertion it already takes field/offset into account, but just modifying morph lets the code above compile w/o assertion and run correctly), but I'm not clear what problems @CarolEidt was [referring to](https://github.com/dotnet/coreclr/issues/7954#issuecomment-258059663) with "an assignment from a struct to itself... I believe that may cause problems if a helper call is generated"

**Comment by JosephTremoulet** [comment]
The assertion in liveness was removed in #7967/#8057.  So, since
 - removing partially-overlapping assignments isn't correct, and
 - I don't have a concrete reason to think helpers couldn't cope with exact self-assignments, and
 - the jit can't generally guarantee that it avoids self-assignments (without injecting run-time pointer equality tests)

I'm going to go ahead and submit a PR that removes the self-assigns only for equal field sequences, and removes the comment.
