### ISSUE TITLE
Load unmanaged static dll in load context

### ISSUE THREAD

**Issue by rdvojmoc** [dotnet/coreclr#10494]
I have native unmanaged dll which is static and must be loaded each time when I need library to do some work if i want to run it in parallel. In .NET I would use AppDomain and load this dll when i need it, but in NET Core AppDomains are gone (for now). I have looked at AssemblyLoadContext but there is no proper documentation with LoadUnmanagedDll. Can this be done in netstandard1.6?

**Comment by jkotas** [comment]
Could you please explain a bit more why you are using AppDomains in .NET Framework? Why can't you just load the unmanaged dll within the same AppDomain?

**Comment by rdvojmoc** [comment]
Currently code is called with PInvoke and is working perfectly. Problem is because nature of this unmanged dll (it's static) written in C, when I try to call it in parallel throws AccessViolationException because two or more task wants to access same memory.

If I could load dll for each time that in some context and then call PInvoke on that this problem would be gone. At least that is my idea.

**Comment by jkotas** [comment]
The unmanaged .dll is always loaded just one. It is constrain imposed by the OS loader, not much we can do about it in .NET. It is same for both .NET Framework and .NET Core. If you load same unmanaged .dll from two different appdomain in full .NET Framework, both AppDomains will get the same instance.

**Comment by rdvojmoc** [comment]
Thanks for quick answer. Based on your answer only way to avoid this error, is to implement synchronized access to this unmanaged dll.

**Comment by jkotas** [comment]
Yes. The other alternatives maybe to run the unmanaged dll in separate process, or to have multiple physical copies (different paths on disk) of this unmanaged .dll.
