### ISSUE TITLE
Crossgen race condition?

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#10500]
I have been running crossgen of libraries in parallel, but have been experiencing odd non-reproducible failures.  Mostof them were due to previous build *.ni.dll's being present in the overlay.  I have resolved this, but I suspect there may also be a crossgen race condition.

In ZapImage::SaveImage(), it looks like crossgen creates the *.ni.dll file then writes its contents.  If another crossgen instance reads the file (dependency) there is a window where an incomplete *.ni.dll image is present.  If the incomplete native image could successfully be loaded without detecting the incompleteness, it would be a race condition.

The typical linux solution would be to write to a temporary file name, then rename to the final name so that the operation was effectively atomic.

**Comment by sdmaclea** [comment]
@jkotas Who is best to comment on whether this could be a real issue or not?

**Comment by jkotas** [comment]
crossgen tool is not designed to generate the output atomically. We never needed that. If you would like to fix it, go for it.

**Comment by sdmaclea** [comment]
I am not running into issues with this at the moment.  Since this is the current intended design, closing the issue.
