### ISSUE TITLE
Default Interface Method support 

### ISSUE THREAD

**Issue by yizhang82** [dotnet/coreclr#10504]
[C# Language Spec Link](https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md)
Runtime Spec Link (TBD)

List of work items: 

- [x] Fix up ILDAsm to support default interface methods (non-abstract virtual methods) on interfaces
- [x] Fix up ILDAsm to allow non-virtual instance methods on interface
- [x] Allow type loader to ignore not implemented interface methods on classes
- [x] Allow non-virtual interface instance methods in type loader
- [x] Support calling protected interface non-virtual instance method from derived class (TBD)
- [x] Hook up VSD interface dispatch
- [x] Throw in the case of diamond inheritance case
- [x] Support Shared generics and variance
- [x] Support looking up method impls
- [ ] Static constructors with initializers only (no static constructor by itself - needs more investigation)
- [ ] Support constrained interface call on value types
- [x] Handle interface precodes properly
- [x] Correct interface lookup algorithm (and validation) once design is finalized
- [x] Proper typeloader/ILDAsm error checking/validation for interface methods once design is finalized (private/protected/internal, virtual vs non-virtual)
- [ ] Reflection to tell the difference between default interface method and a regular
- [ ] NGEN support
- [x] R2R support
- [ ] Interaction with COM interop

**Comment by gkhanna79** [comment]
@yizhang82 Is this for .NET Core 2.0?

**Comment by yizhang82** [comment]
No. It's not part of .NET Core 2.0 work. I don't think we have a shipping date yet. Right now we are in early design/prototype phase.

**Comment by yizhang82** [comment]
We also need engineering work to support producing packages for Roslyn CI. Tracked here: https://github.com/dotnet/core-eng/issues/833

**Comment by mattwarren** [comment]
> Tracked here: [dotnet/core-eng#833](https://github.com/dotnet/core-eng/issues/833)

Just one thing, that 'core-eng' repo doesn't appear to be publicly accessible. 

I'm not saying it should be, but I just wanted to let you know that anyone who isn't a M/S employee can't see that link you posted.

**Comment by MichalStrehovsky** [comment]
Broken out the remaining tasks into individual issues and now tracking within the [Default interfaces project](https://github.com/dotnet/coreclr/projects/6).
