### ISSUE TITLE
Failure in baseservices\threading\mutex\misc\waitanyex2

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#10514]
```
Name created: fb0ff97a-57c0-499b-b3a9-6cf60dea23b0
Testing Mutex and non-Mutex, and signaling the other element
Acquire the Mutex
Holding the Mutex
Waiting...
WaitAny did not throw AbandonedMutexException
Test Failed
Expected: 100
Actual: -1
```

**Comment by jkotas** [comment]
Hit on #10488 (https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1_prtest/4634/testReport/junit/baseservices_threading/_waithandle_waitany_waitanyex2_waitanyex2_/_waithandle_waitany_waitanyex2_waitanyex2_cmd/)

**Comment by kouvel** [comment]
#11334: also affects waitanyex2a
