### ISSUE TITLE
Bundle latest cURL with fixes we care about

### ISSUE THREAD

**Issue by karelz** [dotnet/coreclr#10528]
Here's interesting list:
* Don't compile NSS version, it causes troubles - see https://github.com/dotnet/corefx/issues/16201
* cURL fix https://github.com/curl/curl/issues/1354 for https://github.com/dotnet/corefx/issues/17174

**Comment by stephentoub** [comment]
> Don't compile NSS version

On Linux we always want to use a version based on OpenSSL.  While we tolerate NSS and other backends, lots of features don't work when targeting those, e.g. custom handling of certificates, revocation checking, etc.

**Comment by jkotas** [comment]
Why is this tracked in CoreCLR repo?

**Comment by karelz** [comment]
I thought cURL bundling happens in CoreCLR -- @janvorli? If I am wrong, feel free to move it.

**Comment by janvorli** [comment]
No, it will happen in corefx repo. I am sorry for not noticing before this issue was in coreclr. Moving to corefx.

**Comment by janvorli** [comment]
Issue moved to [dotnet/corefx #17647](https://github.com/dotnet/corefx/issues/17647) via [**ZenHub**](https://www.zenhub.com/)

**Comment by karelz** [comment]
Ah, I didn't realize this stuff happens in CoreFX. Sorry for that Jan & Jan!
