### ISSUE TITLE
System.ExecutionEngineException when running .NET assembly

### ISSUE THREAD

**Issue by Spacefish** [dotnet/coreclr#1053]
It´s an simple .NET assembly .exe when running against clr.dll 4.6.57.0 i get a System.ExecutionEngineException in an "unknown module". Probably because VS searches for a managed code section, but it happens in unmanaged code.. What should i do? How can i debug this? i can upload the .net assembly (~200 kByte), but i don´t have the source code. It´s not pulling in any non standard .dll files.

**Comment by davidfowl** [comment]
Does this have anything to do with coreclr?

**Comment by Spacefish** [comment]
@davidfowl isn´t this the .NET runtime Codebase which is used for the current .NET Runtime as well? I thought it might contain the same bug, as the Runtime included in the .NET Framework 4.6 Preview?

If i don´t understand this right, i am sorry for posting the ticket. Please go ahead and close it then.

**Comment by davidfowl** [comment]
@Spacefish Nope it's the coreclr code base (some components are shared) but this isn't the place to file .NET 4.x CLR bugs.
