### ISSUE TITLE
Debug command !dso does not work in server GC mode for .net core app

### ISSUE THREAD

**Issue by imcarolwang** [dotnet/coreclr#10543]
In .net core app, add following runtimeconfig, !dso doesn't work; without the config !dso just work.

> {
>   "runtimeOptions":{ 
>   "configProperties":{
> 			"System.GC.Server": true
> 		     }
> 		   }
> }

**Comment by swgillespie** [comment]
@imcarolwang Can you provide some more details? What version of the CLI are you using? What operating system? What sort of "don't work" - is the output wrong or does it crash?

**Comment by imcarolwang** [comment]
I have repro app built on Win10 with the latest version of .net core SDK installed.
Operating system: tried on Windows10, Windows2012 R2, issue repro on both OS.

**The Details:**

A helloworld app would repro, it's created via "dotnet new console --framework netcoreapp2.0", add   RuntimeIdentifiers node to the **Helloworld.csproj**, like below:
```
<Project Sdk="Microsoft.NET.Sdk"> 
	<PropertyGroup>
	    <OutputType>Exe</OutputType>
 	    <TargetFramework>netcoreapp2.0</TargetFramework>
            <RuntimeFrameworkVersion>2.0.0-beta-001834-00</RuntimeFrameworkVersion>
            <RuntimeIdentifiers>win7-x64</RuntimeIdentifiers>
	</PropertyGroup>
</Project>
```
**program.cs**:
```
using System;
using System.Diagnostics;

namespace helloworld
{
    class Program
    {
        static void Main(string[] args)
        {
            string str = "helloworld";
            Console.WriteLine("calling the debugger.break, test string: {0}", str);
            Debugger.Break();
            Console.WriteLine("press anykey to exit ...");
            Console.Read();
        }
    }
}
```
dotnet build and run, then **dotnet publish HelloWorld.csproj -c Release -r win7x64 -o ReleaseFolder**

update file **helloworld.runtimeconfig.json** under ReleaseFolder with the aforementioned config of **"System.GC.Server": true**

run **windbg -g helloworld.exe**, check command !dso, the output from windbg(**doesn't work**):
```
0:000> !dso
OS Thread Id: 0x438c (0)
RSP/REG          Object           Name
```
without that config, type !dso the output is like the following(**works**):
```
0:000> !dso
OS Thread Id: 0xc24 (0)
RSP/REG          Object           Name
000000D56A97DE68 0000029b8b3c86f0 System.Byte[]
000000D56A97DFF0 0000029b8b3c8038 System.String    calling the debugger.break, test string: {0}
000000D56A97DFF8 0000029b8b3c8008 System.String    helloworld
000000D56A97E020 0000029b8b3c7ff0 System.String[]
...
```

**Comment by swgillespie** [comment]
@imcarolwang Thank you, that's very helpful! Can you also post the output of `lmDvmCoreCLR` when run in windbg with coreclr loaded? I'm going to try and reproduce this independent of the CLI tomorrow and that should retrieve the commit hash.

**Comment by imcarolwang** [comment]
0:000> lmDvmCoreCLR 

> Browse full module list
> start             end                 module name
> 00007ffa`bfd50000 00007ffa`c0270000   coreclr    (private pdb symbols)  E:\tools\amd64\sym\coreclr.pdb\0449C15F79F041A48AD229949E8223E91\coreclr.pdb
>     Loaded symbol image file: E:\projects\helloworld\pub\coreclr.dll
>     Image path: E:\projects\helloworld\pub\coreclr.dll
>     Image name: coreclr.dll
>     Browse all global symbols  functions  data
>     Timestamp:        Thu Mar 23 12:35:47 2017 (58D42393)
>     CheckSum:         00510F4F
>     ImageSize:        00520000
>     File version:     4.6.25123.8
>     Product version:  4.6.25123.8
>     File flags:       8 (Mask 3F) Private
>     File OS:          4 Unknown Win32
>     File type:        0.0 Unknown
>     File date:        00000000.00000000
>     Translations:     0409.04b0
>     CompanyName:      Microsoft Corporation
>     ProductName:      Microsoft® .NET Core
>     InternalName:     CoreCLR.dll
>     OriginalFilename: CoreCLR.dll
>     ProductVersion:   4.6.25123.08 built by: dlab-DDVSOWINAGE015. Commit Hash: 1976320a1a56afb23f3049fb91d93a85cb4fb1d4
>     FileVersion:      4.6.25123.08 built by: dlab-DDVSOWINAGE015. Commit Hash: 1976320a1a56afb23f3049fb91d93a85cb4fb1d4
>     PrivateBuild:     FX_VER_PRIVATEBUILD_STR
>     FileDescription:  Microsoft .NET Runtime
>     LegalCopyright:   © Microsoft Corporation.  All rights reserved.
>     Comments:         Flavor=Retail
>

**Comment by swgillespie** [comment]
cc @mikem8361 - I have a repro and it's probably my fault, I'm looking into it this morning.

**Comment by swgillespie** [comment]
@imcarolwang Thanks a ton for the report! It's fixed now on master. I'm not sure what the shipping cadence of the CLI is but it should be in the .NET Core SDK pretty soon.
