### ISSUE TITLE
CoreCLR test JIT\Regression\CLR-x86-JIT\V1.2-M01\b08046\b08046\b08046.cmd fails in release

### ISSUE THREAD

**Issue by PhoebeHui** [dotnet/coreclr#10549]
CoreCLR test ‘JIT.Regression.XUnitWrapper’ is failed, we encountered this issue for more than 6 times on VS2017 RTW compiler on Windows, sometimes it can’t repro, could someone help have a look?
It will be great if someone make it more reliable.

Repro steps:
1. Get CoreCLR source: ‘git clone https://github.com/dotnet/coreclr D:\CoreCLR\src’
2. Execute ‘build x86 release -Rebuild -- /clp:ShowCommandLine’
3. Run tests: ‘tests\runtest.cmd x86 release  >d:\corclr\test.log’

Failures:
D:\CoreCLR\src\bin\tests\Windows_NT.x86.Release\TestWrappers\JIT.Regression\JIT.Regression.XUnitWrapper.cs(57297): error : JIT_Regression._CLR_x86_JIT_V1_2_M01_b08046_b08046_b08046_._CLR_x86_JIT_V1_2_M01_b08046_b08046_b08046_cmd [FAIL] [D:\CoreCLR\src\tests\runtest.proj]     
  
  Return code:      1
  Raw output file:      D:\CoreCLR\src\bin\tests\Windows_NT.x86.Release\Reports\JIT.Regression\CLR-x86-JIT\V1.2-M01\b08046\b08046\b08046.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\CoreCLR\src\tests\..\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\corerun.exe" b08046.exe 
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\CoreCLR\src\bin\tests\Windows_NT.x86.Release\Tests\Core_Root
  > D:\CoreCLR\src\bin\tests\Windows_NT.x86.Release\JIT\Regression\CLR-x86-JIT\V1.2-M01\b08046\b08046\b08046.cmd
  
        Expected: True
        Actual:   False
          D:\CoreCLR\src\bin\tests\Windows_NT.x86.Release\TestWrappers\JIT.Regression\JIT.Regression.XUnitWrapper.cs(57297,0): at JIT_Regression._CLR_x86_JIT_V1_2_M01_b08046_b08046_b08046_._CLR_x86_JIT_V1_2_M01_b08046_b08046_b08046_cmd()

**Comment by BruceForstall** [comment]
Related to #4849?

**Comment by PhoebeHui** [comment]
Is there a way only disable this test on Windows?

**Comment by RussKeldorph** [comment]
@PhoebeHui This test used to be disabled on all platforms, but I confirm it isn't now.  I haven't yet found the change that reenabled it, but I suspect that was a mistake.

**Comment by PhoebeHui** [comment]
Thanks for all of you to fix this issue!

**Comment by PhoebeHui** [comment]
Thanks all of you to fix this issue!
