### ISSUE TITLE
System.NotSupportedException : Assembly.Load with a Codebase is not supported.

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#10561]
Either Assembly.GetName() should not set Codabase property or LoadFromAssemblyName should ignore CodeBase property in AssemblyName

**Comment by rahku** [comment]
If you call Assembly.GetName() for a loaded assembly the returned AssemblyName object has its CodeBase property set to url based location of assembly. If you use the same AssemblyName object and pass it to Assembly.Load(AssemblyName n) then it fails saying Load using CodeBase is not supported. In my opinion this is not good experience. I have two options to fix this:
1. Don't set property codebase & escapedcodebase in assemblyname. we already have a new property Location in assemblyname which provides path based location of assembly.
2. In function Assembly.Load(AssemblyName n) ignore the value of codebase. Save value of codebase property and in the passed-in assemblyname object set codebase property to null before call to InternalLoadAssemblyName() function. Then before return from Load() function reset back the CodeBase property to its original value.

I would prefer option #1 but this could be problematic for desktop compat. or do you think it does not give much value to fix this and should stay the way it is?

@jkotas @gkhanna79 Let me know your thoughts

**Comment by jkotas** [comment]
There is also `Assembly.CodeBase` property. It would be nice if `Assembly.CodeBase` and `Assembly.GetName().CodeBase` returned same results. 

Another option is to turn AssemblyName loads with CodeBase property set into LoadFrom. E.g. the following works in desktop:

```
    class Program
    {
        static void Main(string[] args)
        {
            var a = typeof(Program).Assembly;

            var an = new AssemblyName();
            an.CodeBase = a.CodeBase;

            var loaded = Assembly.Load(an);
            Debug.Assert(a.Equals(loaded));
        }
    }
```

Any reason to not do that?

> Save value of codebase property and in the passed-in assemblyname object set codebase property to null before call to InternalLoadAssemblyName() function. Then before return from Load() function reset back the CodeBase property to its original value.

I do not think you would ever want to mutate the AssemblyName passed in. You would want to create a copy if we want with this option.

> problematic for desktop compat

Yes, both `Assembly.CodeBase` and `AssemblyName.CodeBase` have non-trivial usage.

**Comment by rahku** [comment]
>Another option is to turn AssemblyName loads with CodeBase property set into LoadFrom. E.g. the following works in desktop:

We have already diverged a lot in behavior compared to desktop in Load* apis. So trying to do what desktop does should not be a goal I think. I feel it is better to be explicit between Load & LoadFrom and not combine the two. It is more simpler to explain & understand. 
There is also the complication of when the assemblyname contains both display name and codebase. In desktop the behavior for when this turns into LoadFrom is to verify that display name matches the loaded assembly and if that fails then fail the load. This would turn out to be complicated to handle because of the way loadfrom is implemented in .net core. 
And I do not think the complication is worth the benefit

So I am planning to go with this approach
>I do not think you would ever want to mutate the AssemblyName passed in. You would want to create a copy if we want with this option.

**Comment by jkotas** [comment]
Sounds good.
