### ISSUE TITLE
MSIL differences between .NET Framework and .NET Core

### ISSUE THREAD

**Issue by bobu** [dotnet/coreclr#10586]
Is there any documentation, or articles, that show any differences between the MSIL generated for the .NET Framework vs. .NET Core. Since they are presumably using the same CLI spec (https://www.ecma-international.org/publications/standards/Ecma-335.htm), there should be no differences. But I want to ask the question to see what is known on the subject.

**Comment by gkhanna79** [comment]
@jaredpar Do you want to chime in?

**Comment by jaredpar** [comment]
There is no difference.  The compiler itself doesn't even understand the concept of Net Framework vs. Net Core.  That is all handled at the MSBuild / NuGet level.  Once it gets down to the compiler layer it's just a set of references that we treat like any other.

**Comment by bobu** [comment]
@jaredpar That's great to hear. So are there any differences that you know of that occur in MSBuild?

**Comment by jaredpar** [comment]
> So are there any differences that you know of that occur in MSBuild?

What kind of differences are you concerned with here?  Are you referring to differences when MSBuild runs on CoreCLR s. desktop?

**Comment by bobu** [comment]
Just looking at Windows first, I would want to know if MSBuild changes any of the byte-code from what was expected in .NET Framework. I seriously doubt that there is anything in MSBuild that would do that, but I'm not sure.

**Comment by jaredpar** [comment]
> I would want to know if MSBuild changes any of the byte-code from what was expected in .NET Framework. 

It doesn't.  They don't directly control the emitted byte code, instead deferring to the compiler.

**Comment by bobu** [comment]
Thanks Jared. I'll close this issue.
