### ISSUE TITLE
ILAsm: Unable to create debugging information when only referencing System.Runtime

### ISSUE THREAD

**Issue by mletterle** [dotnet/coreclr#10608]
# Issue

When attempting to insert `DebuggableAttributes`, ilasm only considers `mscorlib` it does not consider `System.Runtime`. If the assembly only contains `System.Runtime` ilasm crashes with a assertion error.

# Repo

Consider the following il:

```cil
.assembly TestAssembly { }

.assembly extern System.Runtime 
{
}

.method static void Main()
{
    .entrypoint
    newobj instance void [System.Runtime]System.Object::.ctor()
    pop
    ret
}
```

Attempting to ilasm this and using, for example, the "debug=impl" option results in an Assert failure.

# Desired Result

ilasm should properly get the `System.Diagnostic.DebuggableAttribute` reference from whatever has been determined to be the "BaseAsmRef"

# Note

This is actually a duplicate of an [old connect bug of mine](https://connect.microsoft.com/VisualStudio/feedback/details/754111/ilasm-crashes-when-generating-pdb-files-for-an-assembly-that-does-not-reference-mscorlib).

**Comment by RussKeldorph** [comment]
@mletterle Sorry, I didn't notice you had a PR out to fix this when I assigned to @rartemev.  @rartemev I agree with @mletterle's logic.  Could you confirm @mletterle's change should work and merge if so?
