### ISSUE TITLE
Ubuntu x64 test failure 

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/coreclr#10603]
CoreCLR Ubuntu x64 test fail after merging #10410 
CI failure: https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_flow

```
15:42:35 FAILED   - JIT/Performance/CodeQuality/Span/SpanBench/SpanBench.sh
15:42:35                BEGIN EXECUTION
15:42:35                /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun SpanBench.exe
15:42:35                TestSpanClear<Byte>(1): 0.5054ms
15:42:35                TestSpanClear<Byte>(10): 0.0022ms
15:42:35                TestSpanClear<Byte>(100): 0.0006ms
15:42:35                TestSpanClear<Byte>(1000): 0.0007ms
15:42:35                TestSpanClear<String>(1): 0.0171ms
15:42:35                TestSpanClear<String>(10): 0.0038ms
15:42:35                TestSpanClear<String>(100): 0.0033ms
15:42:35                TestSpanClear<String>(1000): 0.004ms
15:42:35                TestArrayClear<Byte>(1): 0.009ms
15:42:35                TestArrayClear<Byte>(10): 0.0021ms
15:42:35                TestArrayClear<Byte>(100): 0.0019ms
15:42:35                TestArrayClear<Byte>(1000): 0.0018ms
15:42:35                TestArrayClear<String>(1): 0.009ms
15:42:35                TestArrayClear<String>(10): 0.0022ms
15:42:35                TestArrayClear<String>(100): 0.0019ms
15:42:35                TestArrayClear<String>(1000): 0.0026ms
15:42:35                
15:42:35                Unhandled Exception: System.TypeLoadException: Could not load type 'System.Span' from assembly 'System.Memory, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
15:42:35                   at Span.SpanBench.TestSpanAsBytes[T](T[] array, Int32 iterationCount, Boolean untrue)
15:42:35                   at Span.SpanBench.Invoke(Action`1 innerLoop, String nameFormat, Object[] nameArgs)
15:42:35                   at Span.SpanBench.Main(String[] args)
15:42:35                ./SpanBench.sh: line 200: 55987 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
15:42:35                Expected: 100
15:42:35                Actual: 134
15:42:35                END EXECUTION - FAILED
```

The strange thing is that #10410 seems to touch only x86 environment but it affected x64 tests. Is there another reason of test failure?

**Comment by RussKeldorph** [comment]
This is hitting Unix across the board and appears to have regressed 18-20 hours ago.  Still looking.

/cc @JosephTremoulet

**Comment by JosephTremoulet** [comment]
Could this be one of our "make an overlay by grabbing recent bits from coreclr + corefx, throwing them together, and hoping for the best" issues?

**Comment by RussKeldorph** [comment]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/release_ubuntu_tst/1245/ seems to be the build where this started.  @mmitche, any way your "CROSS" change caused this?  If not, then @JosephTremoulet yes, I suspect some change from outside coreclr took us down.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by mmitche** [comment]
@RussKeldorph Nope, that is a completely separate job.

**Comment by sdmaclea** [comment]
@RussKeldorph FWIW I was able to build and test 07fa3a32 on [Arm64/Unix] with no new regressions This is the same as https://ci.dot.net/job/dotnet_coreclr/job/master/job/release_ubuntu_tst/1250/ .  Of course I used the tests from the matching x64_checked_windows_nt_pri1_bld.

**Comment by AndyAyersMS** [comment]
Likely suspect is dotnet/corefx#17704.... we have not taken in the CoreFX update for this yet so the version info is potentially askew for our strange cross-build setup.

**Comment by AndyAyersMS** [comment]
Or more likely suspect dotnet/corefx#17407 which changed parts of Span.

**Comment by ahsonkhan** [comment]
This PR should resolve some issues: https://github.com/dotnet/coreclr/pull/10544
Waiting for the corefx package.

**Comment by hseok-oh** [comment]
resolved
