### ISSUE TITLE
ILAsm: Certain fundamental types may have their assembly references changed

### ISSUE THREAD

**Issue by mletterle** [dotnet/coreclr#10618]
# Issue

Ilasm has a set of types that it considers "fundamental types" that should only exist in one "BaseAsmRef", if those types are (deliberiately) made to point outside of what ilasm decides is the BaseAsmRef it will update those references regardless of what has been specified.

The current "fundamental types" are:

* `System.Enum`
* `System.Object`
* `System.String`
* `System.ValueType`

    See [ilasm/assembler.cpp\#`Assembler::ResolveClassRef`](https://github.com/dotnet/coreclr/blob/54891e0650e69f08832f75a40dc102efc6115d38/src/ilasm/assembler.cpp#L103)

## Examples

* Fundamental types are moved from `mscorlib` to `System.Runtime` when both are referenced. 
* Fundamental types are moved from arbitrary assemblies to either `System.Runtime` or `mscorlib` if one or the other is referenced.
* Fundamental types are moved from arbitrary assemblies to `mscorlib` if neither `System.Runtime` nor `mscorlib` are referenced.

# Repo

Consider the following il:

```cil
.assembly TestAssembly { }

.assembly extern System.Runtime 
{
}

.assembly extern mscorlib
{

}

.method static void Main()
{
    .entrypoint
    newobj instance void [mscorlib]System.Object::.ctor()
    pop
    ret
}
```

After processing by ilasm, `System.Object` will now be referenced in `System.Runtime` rather than `mscorlib`

Similarly, with the following il:

```cil
.assembly TestAssembly { }

.assembly extern MyObjectLibrary 
{
}

.method static void Main()
{
    .entrypoint
    newobj instance void [MyObjectLibrary]System.Object::.ctor()
    pop
    ret
}
```

When processed by ilasm, the assemblier will *helpfully* automatically add a reference to `mscorlib` and update the `System.Object` to reference it there instead of the original assembly.

# Desired Result

If fundamental types are explictly noted as being in a referenced assembly, ilasm should leave those references alone.

If a fundamental type is referenced without an explict assembly, then auto referencing the BaseAsmRef is probably correct, such as the following:

```cil
.assembly TestAssembly { }

.assembly extern MyLibrary 
{
}

.method static void Main()
{
    .entrypoint
    newobj instance void System.Object::.ctor()
    pop
    ret
}
```

**Comment by MichalStrehovsky** [comment]
If you throw `.mscorlib` into your source file, it serves as an escape hatch for this behavior.

**Comment by mletterle** [comment]
oh... this is good to know!

Hmm... almost rather it was opt-in as opposed to opt-out, but interesting.

**Comment by mletterle** [comment]
There are a couple of places in the code where `m_fIsMscorlib` being true might have unintended effects, I'm thinking specifically of the debugging options.... in `AsmMan::EmitDebuggableAttribute` if you use `.mscorlib` and your version number just *happens* to start with a 1 you can't use "debug=impl", though maybe that logic is no longer valid?

**Comment by danmosemsft** [comment]
@gkhanna79 where do ILASM issues go - what area, who owns it?

**Comment by gkhanna79** [comment]
Area-codegen and  Russ keldorph.


Thanks,
Gaurav
________________________________

**Comment by gkhanna79** [comment]
@RussKeldorph PTAL.

**Comment by DemiMarie** [comment]
What would happen if someone tried to load the resulting assembly?  Would it throw a `TypeLoadException`, or crash the runtime?

**Comment by RussKeldorph** [comment]
Re-open if/when a fix is ready.
