### ISSUE TITLE
[Arm64] Implement InitBlk unrolling

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#10624]
See TODO-ARM64-CQ in Lowering::LowerBlockStore

**Comment by sdmaclea** [comment]
@jashook Please assign this to me

**Comment by jashook** [comment]
cc @CarolEidt

**Comment by sdmaclea** [comment]
@briansull I want to use a C7.2.32 DUP (general) 

I do not see a unit test matching this.

To generate 'dup V0.16B, X1', it looks like this would be the form.  

```
emitIns_R_R_I(INS_dup, EA_1BYTE, REG_V0, REG_R1, 0, INS_OPTS_16B)
```

But it seems weird because the immediate is ignored.

**Comment by sdmaclea** [comment]
@briansull I decided against using dup for now, so you can ignore my question.

**Comment by briansull** [comment]
It is quite possible that some instruction variants still need a small change to be correct and usable.

**Comment by briansull** [comment]
My manual has DUP listed as  "C7.3.32 DUP (general)"

// imm5<4:size+1> is IGNORED

**Comment by sdmaclea** [comment]
For the form I suggested "dup V0.16B, X1", Q=1, imm5=xxxx1.  So does 

```
emitIns_R_R_I(INS_dup, EA_1BYTE, REG_V0, REG_R1, 0, INS_OPTS_16B)
```

Look right to you?

**Comment by briansull** [comment]
Yes the imm5 value is used to encode the OPT_16B and the encoding needs to be:

**16B when imm5 = xxxx1, Q = 1**

The comment in the ARM manual about the immediate being ignored
 I means that the xxxx value (which can vary is size is ignored)
It is used for the other format of the DUP instruction when you pass a second Vector register.

For our purposes you must pass an immediate of zero when passing a general purpose register.
