### ISSUE TITLE
RyuJIT/x86: assert failure when precompiling System.Security.AccessControl.dll

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#10621]
To repro:
1. Download the [System.Security.AccessControl.dll package](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Security.AccessControl/4.4.0-preview1-25131-02)
2. `crossgen runtimes/win/lib/netcoreapp2.0/System.Security.AccessControl.dll`

You should see the following assert:
```
Assert failure(PID 31136 [0x000079a0], Thread: 35532 [0x8acc]): Assertion failed 'treeNode->gtVal.gtVal1 < compiler->compHndBBtabCount' in 'System.Security.AccessControl.Privilege:ToggleState(bool):this' (IL size 407)

    File: c:\dev\coreclr\src\jit\codegenxarch.cpp Line: 2142
    Image: c:\dev\coreclr\bin\Product\Windows_NT.x86.Checked\crossgen.exe
```

This assert does not fire if `COMPlus_JitMinOpts` is set to `1`.

@AndyAyersMS can you take a look?

**Comment by AndyAyersMS** [comment]
Sure.

**Comment by AndyAyersMS** [comment]
In `System.Security.AccessControl.Privilege:ToggleState(bool):this` there is a nested try-finally with an empty try:
```C#
try {}
finally {
   try {...}
   finally {...}
}
```
when we remove the empty try we need to go and update the nesting level stored in the GT_END_LFIN statements of any enclosed try finally.

**Comment by AndyAyersMS** [comment]
Odd that we use this field when exiting the finally to figure out which slot to clear, but call `fgGetNestingLevel` to determine which slot to set when calling the finally.

Updating is certainly doable but it requires walking all the statements in the handler region. Might be more efficient to just rederive the nesting from the handler table by calling `fgGetNestingLevel` in both cases.

**Comment by AndyAyersMS** [comment]
Also, the non-empty try has to have multiple leaves or an uncloneable finally. The assertion check in `genCodeForTreeNode` is not as strong as it should be (it should check against maximum nesting, not against EH table entry count).
