### ISSUE TITLE
coreclr doesn't enforce the delegate transparency rule for some IL sequences.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#10620]
importer.cpp : impImportBlockCode has code to enforce  the delegate transparency rule:

```
// Insert delegate callout here.
if (opcode == CEE_NEWOBJ && (mflags & CORINFO_FLG_CONSTRUCTOR) && (clsFlags & CORINFO_FLG_DELEGATE))
{
  // In coreclr the delegate transparency rule needs to be enforced even if verification is disabled
  typeInfo              tiActualFtn          = impStackTop(0).seTypeInfo;
  CORINFO_METHOD_HANDLE delegateMethodHandle = tiActualFtn.GetMethod2();
  impInsertCalloutForDelegate(info.compMethodHnd, delegateMethodHandle, resolvedToken.hClass);
}
```

and GetMethod2() was added in PR #4999 as workaround for tests JIT/Methodical/delegate/_simpleoddpower_il_d/_simpleoddpower_il_d.sh
JIT/Methodical/delegate/_simpleoddpower_il_d/_simpleoddpower_il_r.sh
where such IL sequence exists:
```
    IL_01d0:  ldloc.0
    IL_01d1:  dup
    IL_01d2:  
    	call instance method int32 * () OddPower::GetMthdPtr1()
    IL_01d8:  newobj     instance void OddPower/MyDeleg2::.ctor(object,
                                                                native int)
```

call returns TI_ERROR type for pointers, because
`verMakeTypeInfo: case CORINFO_TYPE_PTR: // for now, pointers are treated as an error`
and it was done before the initial GitHub commit (2010).

So in this situation on the EE stack we have TI_ERROR type with nullptr in m_method.
GetMethod2 returns null, delegateMethodHandle == nullptr and impInsertCalloutForDelegate does nothing because isDelegateCreationAllowed returns false for nullptr.

**Comment by jkotas** [comment]
This should be deleted. We should not be enforcing any security transparency rules in CoreCLR anymore.

**Comment by sandreenko** [comment]
isDelegateCreationAllowed  was deleted.
