### ISSUE TITLE
RyuJIT/x86: assertion in LSRA when precompiling System.{Data.Common,Security.Cryptography.Xml}.dll under JitStress=1 and JitStressRegs=8

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#10622]
Repro steps:
1. Download the latest version of the appropriate package (i.e. one of [System.Data.Common](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Data.Common/4.4.0-beta-24913-02) or [System.Security.Cryptography.Xml](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Security.Cryptography.Xml/4.4.0-preview1-25131-02)).
2. set COMPlus_JitStress=1
3. set COMPlus_JitStressRegs=8
4. Run crossgen on the `netcoreapp2.0` implementation DLL.

You should see the following assertion:
```
Assert failure(PID 19196 [0x00004afc], Thread: 20732 [0x50fc]): Assertion failed 'farthestRefPhysRegRecord != nullptr' in 'System.Data.DataTable:set_EnforceConstraints(bool):this' (IL size 34)

    File: c:\dev\coreclr\src\jit\lsra.cpp Line: 5927
    Image: c:\dev\coreclr\bin\Product\Windows_NT.x86.Checked\crossgen.exe
```

**Comment by RussKeldorph** [comment]
Flaw in LSRA stress infrastructure.

**Comment by sdmaclea** [comment]
@pgavlin @CarolEidt The same defect seems to also affect [Arm64/Unix] during crossgen without any JitStress.

On version c111a57, It is affecting these files during crossgen
```
Microsoft.VisualBasic.dll
System.Private.Xml.dll
```

**Comment by pgavlin** [comment]
@sdmaclea The meaning of the referenced assertion boils down to "the RA could not find a viable allocation given the problem constraints", so if you are seeing it in other circumstances it may not be related to this issue.

Under which circumstances is the RA failing to allocate? Are there any stress modes enabled, or is this simply `crossgen {System.Private.Xml,Microsoft.VisualBasic}.dll?

**Comment by sdmaclea** [comment]
@pgavlin No stress modes enabled.  Simple crossgen.  This apparently was triggered in Arm64 with the recent CoreFX version upgrade.  Should I open a separate issue?

**Comment by pgavlin** [comment]
Yes, a separate issue would be most appropriate. Thanks!

**Comment by CarolEidt** [comment]
I am unable to reproduce this.
