### ISSUE TITLE
CheckProjects is fragile to running with cross targets.

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#10635]
CheckProjects assumes the tests were built in a CoreCLR repo. For cross targets such as Arm32, Arm64 this may not be correct causing the test to fail.

Note this bug is mostly just to add an issue tag to disable the test on Arm64.

**Comment by AndyAyersMS** [comment]
It really doesn't need to be run for every platform, so I'm fine if it gets excluded here and there.

Alternatively we can rework it so that if the test projects can't be found it will return a success exit code.
