### ISSUE TITLE
GC Logs

### ISSUE THREAD

**Issue by bjjzqd** [dotnet/coreclr#1063]
I'm wondering what the best method is for developers to get GC logs. Based on my research it seems ETW is the preferred method. I've got it working, and it does provide everything I need, but I'm curious if there's any other method. 

In my mind I'm imagining setting some environment variable and getting an easily parsable/spreadsheet output that includes which generation was collected, collection duration, and amount of reclaimed space. The end goal being that I can easily develop statistics and understand trends over time.

**Comment by jkotas** [comment]
cc @brianrob @Maoni0 

ETW and equivalent technologies on non-Windows platforms - https://github.com/dotnet/coreclr/blob/master/Documentation/cross-platform-performance-and-eventing.md - is what we have standardized on. We do not have plans to provide alternatives.

**Comment by Maoni0** [comment]
That's what GCStats in PerfView is for (you can download perfview from Microsoft.com).

**Comment by bjjzqd** [comment]
Great, this solves my issue. Thanks for the response.
