### ISSUE TITLE
[Arm64] Unable to load the native dll for ForeignThreadException

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#10636]
Expected Output

<pre>
BEGIN EXECUTION
 "C:\Users\DDJOIN\Downloads\CoreCLR-Pri1Testing\Tests\Core_Root\\corerun.exe" ForeignThreadExceptions.exe
Failed to catch an exception! System.DllNotFoundException: Unable to load DLL 'ForeignThreadExceptionsNative': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ForeignThreadExceptionsTest.InvokeCallback(MyCallback callback)
   at ForeignThreadExceptionsTest.RunTest()
   at ForeignThreadExceptionsTest.Main()
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
</pre>

**Comment by sdmaclea** [comment]
@jashook FYI #9876 just enabled this recently.  It is probably just the wrong dll in your overlay.

**Comment by BruceForstall** [comment]
Looks like this is a case of missing CRT.

If you copy (from a VS2017 install)
```
c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Redist\MSVC\14.14.26405\onecore\arm64\Microsoft.VC141.CRT
```
which includes vcruntime140.dll and msvcp140.dll, among others, into `CORE_ROOT`, then the load works.

Looks like netci.groovy does this, using a snapshot of the CRT:
```
if (architecture == "arm64") {
    addCommand("copy C:\\Jenkins\\vcruntime140.dll bin\\tests\\${osGroup}.${architecture}.${configuration}\\Tests\\Core_Root")
    addCommand("copy C:\\Jenkins\\vcruntime140d.dll bin\\tests\\${osGroup}.${architecture}.${configuration}\\Tests\\Core_Root")
}
```

**Comment by BruceForstall** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/19336
