### ISSUE TITLE
Debug.Assert failure should terminate the program unconditionally

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#10647]
Repro:

```
using System;
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            Debug.Assert(false);
        }
        catch
        {
        }

        Console.WriteLine("Hello World!");
    }
}
```

dotnet restore
dotnet run

Actual result: "Hello World!"
Expected result: Program is terminate with assert message

**Comment by jkotas** [comment]
The problem is that the `Debug.Assert` throws a regular catchable exception today. Instead, it needs to fail fast. There is old [TODO](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Diagnostics/Debug.Windows.cs#L19) pointing to https://github.com/dotnet/corefx/issues/3708 that was never fixed and postponed to future instead.

**Comment by jkotas** [comment]
This is import to fix for v2.0. 

We may be hitting assertion failures in our debug build tests runs today, but we never notice them because of they get caught as exception.

cc @danmosemsft @gkhanna79

**Comment by danmosemsft** [comment]
We want literally `Environment.FailFast` ? Will that produce equally good debug experience?

**Comment by jkotas** [comment]
We should keep the `Debugger.Break()` when debugger is attached: https://github.com/dotnet/coreclr/blob/f355c5789d5d7cd6ea10bee326c66f04641cfc90/src/mscorlib/src/System/Diagnostics/Debug.Windows.cs#L15

**Comment by bartonjs** [comment]
I have to say, the messages going away and the process just crashing has been very confusing to me.  Is this the same treatment we have on netfx and I was just spoiled when asserts were printing to the console during corefx development?
