### ISSUE TITLE
Change Encoding.Default to UTF-8 *without BOM* for Unix interoperability

### ISSUE THREAD

**Issue by mklement0** [dotnet/coreclr#10643]
This is a follow-up from [here](https://github.com/dotnet/standard/issues/260#issuecomment-290149417).

* `Encoding.Default` in the full framework on Windows reports the legacy "ANSI" code page (encoding).

* Core doesn't support these legacy pages (by default) so its `Encoding.Default` must return an encoding that makes sense in a cross-platform world.

* Currently, `Encoding.UTF8` is returned, which is a UTF-8 encoding _with BOM_.
  * The reason for returning `Encoding.UTF8` as `Encoding.Default` is a historic one, it seems, as the [source-code comment](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/Encoding.cs#L1235) mentions _Silverlight_(!).

* **UTF-8 with BOM is problematic on all Unix platforms, whose utilities do not expect a BOM and instead treat it as _data_, leading to unexpected results.**

* **Having `Encoding.Default` return a UTF-8 encoding _with BOM_ is pointless and confusing**, because it neither represents any platform's nor the framework's own true default, and may cause disruption in practice.

   * Note that both .NET Framework's and .NET Core's _true default_ is _BOM-less_ UTF-8, because that's what's used _in the absence of specifying an encoding_ with the [methods of the `System.IO` class](https://msdn.microsoft.com/en-us/library/system.io.file_methods%28v=vs.110%29.aspx).

**Comment by iSazonov** [comment]
@mklement0 Maintainers want the [format ](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md)

**Comment by svick** [comment]
@iSazonov Changing this would not affect the shape of the API, only behavior. So I don't think following the API review process makes sense.

**Comment by jkotas** [comment]
@tarekgh Do we need a test for this?

**Comment by iSazonov** [comment]
Thanks for the quick fix!

**Comment by tarekgh** [comment]
@jkotas I'll add a test as soon as we get the new coreclr in corefx
