### ISSUE TITLE
Add Fedora 25 to coreclr CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#10675]
@wtgodbe

**Comment by wtgodbe** [comment]
I don't think we currently have a docker image for Fedora 25, just 23 & 24 - when we run tests for Fedora 25 in Helix, we're using Portable Linux bits. @MattGal can confirm. If that's the case, I can add a Fedora 24 job to CI, but I believe all that would entail is switching all instances of fedora23 to fedora24 in netci.groovy, which would be easiest to do in your current PR https://github.com/dotnet/coreclr/pull/10667/files

@ellismg how do OS names map to docker images in netci.groovy files?

**Comment by ellismg** [comment]
> @ellismg how do OS names map to docker images in netci.groovy files?

We don't use docker images here.  The mapping of OS Names to azure images is here: https://github.com/dotnet/dotnet-ci/blob/master/jobs/generation/Utilities.groovy#L126

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/10739 - as mentioned, we can only do Fedora 24, not 25.
