### ISSUE TITLE
Seemingly Arbitrary Random Objects in Test APIs

### ISSUE THREAD

**Issue by rionmonster** [dotnet/coreclr#10694]
When looking into another existing issue, I came across the following seemingly unused instances of a `Random` class similar to the the following instance:

```
public void TryGetValueValidations(K[] keys, V[] values, K key, V value)
{
        // Other code omitted for brevity
       
        // This is an example of a random Random instance
        Random r = new Random();
        Test.Eval(!tbl.TryGetValue(key, out val), "Err_011 Expected TryGetValue to return false");
        Test.Eval(val == null, "Err_012 Expected val to be null");
}
```

After a cursory look, it appeared a few times specifically within the Test APIs (`tests/src/baseservices/compilerservices/dynamicobjectproperties/testapis.cs`) section, but may be found in other places: 

  - [C:\dev\coreclr\tests\src\baseservices\compilerservices\dynamicobjectproperties\testapis.cs(94)](https://github.com/dotnet/coreclr/blob/master/tests/src/baseservices/compilerservices/dynamicobjectproperties/testapis.cs#L89-L119)
  - [C:\dev\coreclr\tests\src\baseservices\compilerservices\dynamicobjectproperties\testapis.cs(150)](https://github.com/dotnet/coreclr/blob/master/tests/src/baseservices/compilerservices/dynamicobjectproperties/testapis.cs#L121-L153)
     
Is there are reason for this or do these need to be removed?

**Comment by stephentoub** [comment]
If the local is completely unused, it could be deleted.

**Comment by adityamandaleeka** [comment]
@rionmonster Can this issue be closed now?

**Comment by rionmonster** [comment]
@adityam Done :)
