### ISSUE TITLE
Add equivalent `bool` methods to Interlocked.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/coreclr#1070]
Currently, there aren't any Boolean-compatible methods in `System.Threading.Interlocked`.  It would be nice to get methods that work with them.

Most of the API would be identical:

    /// Compares two Booleans for equality and, if they are equal, replaces the first value.
    public static bool CompareExchange(	ref bool location1, bool value,	bool comparand)

    /// Sets a Boolean to a specified value and returns the original value, as an atomic operation.
    public static bool Exchange(ref bool location1, bool value)

And it might be good to have a toggling method, too:

    /// Inverts a specified variable and stores the result, as an atomic operation.
    public static bool Invert(ref bool location)

(...I'm not too happy with that name, but nothing better is coming to mind at the moment)

Without 'cheap' interlocking methods, developers either have to allow reads and updates to bools interleave, use expensive locking, or [roll their own equivalent](http://www.codeproject.com/Tips/375559/Implement-thread-safe-one-shot-bool-flag-with-Inte).

**Comment by stephentoub** [comment]
The problem is that a bool is smaller in size than a word; there's no hardware-level support for such operations.

**Comment by zabulus** [comment]
Do bool variables are aligned somehow in memory?

**Comment by Joe4evr** [comment]
> Do bool variables are aligned somehow in memory?

Yes, actually. I found [this nice in-depth explanation about bools in the CLR](http://stackoverflow.com/questions/28514373/what-is-the-size-of-a-boolean-in-c-does-it-really-take-4-bytes/28515361#28515361) some time ago. Worth a read.

**Comment by Clockwork-Muse** [comment]
hmm, I didn't realize word-size was the limiting factor.  I take it that explains why `byte` and `short` don't have equivalent methods either.

I'd then ask about implementing them as 'convenience' methods, but I'm getting the feeling that it'd be pointless without the hardware support, possibly even because it couldn't guarantee atomicity of the read/write pair... likely you couldn't lock on the passed in value (even if you could lock on a primitive, the `bool` would still be less than a word in size, so not eligible anyways...or am I going off wrong somewhere?)

**Comment by stephentoub** [comment]
Right.  While one might be able to dream up a solution (e.g. maybe determining what 4-byte boundary it's stored on and doing some kind of loop that volatile reads the current value, modifies it, interlocked compare exchange writes it back, and then loops around again if that fails), that's going to be strictly worse than just, for example, using a int instead of a bool.
