### ISSUE TITLE
Enable and verify SOS dump debugging tests

### ISSUE THREAD

**Issue by lt72** [dotnet/coreclr#10709]
Enabling testing for dump debugging, and verify they are passing.

**Comment by lt72** [comment]
This includes:
- Linux and Windows
- x64 and x86

**Comment by karelz** [comment]
Not blocking ZBB perf @lt72 guidance

**Comment by mikem8361** [comment]
The Linux x64 createdump SOS tests are running and successful.

PR: https://github.com/dotnet/debuggertests/pull/264
