### ISSUE TITLE
CLR performance Linux versus Windows

### ISSUE THREAD

**Issue by polarapfel** [dotnet/coreclr#10703]
Hi there,

Running version 1.0.1, creating a new console application using the default template, I noticed that the CLR takes up to two seconds on Linux to initialize before executing the "Hello World" binary from the default template. On Windows (same machine spec), the execution is instant.

Is this a known issue?

thanks,

Tobias W.

**Comment by benaadams** [comment]
What if you build first?
```
dotnet restore
dotnet build -c Release
dotnet run -c Release
```

**Comment by polarapfel** [comment]
Yes. Still takes two seconds to initialize the CLR before the binary executes. Both the release and the debug binaries compiled with dotnet run instantly on the latest Mono runtime on the same Ubuntu system.

**Comment by shahid-pk** [comment]
@polarapfel you said you are running against mono. But mono uses its diferent runtime (aka clr) than the one build from this repo.

**Comment by polarapfel** [comment]
@shahid-pk I ran against both for comparison.

On the same Ubuntu system, a binary compiled with dotnet (both release and debug) have different execution times on the dotnet CLR Windows versus Linux. The binary on Windows starts executing instantly after invoking the CLR. The binary on Linux has to wait around 2 seconds for the CLR to initialize (I know because I put a Console.Write with the system timestamp into main()).

Doing the same comparison on Linux with the dotnet CLR versus the Mono runtime, the binary executes instantly on Mono, the dotnet CLR takes around 2 seconds to initialize before it executes the binary.

This is bad and cannot be intentional. I didn't find any tickets pointing to this issue but I'm sure someone else must have noticed?!

thanks,

Tobias W.

**Comment by janvorli** [comment]
@polarapfel It seems it is specific to the `dotnet run`. If I run hello world using just dotnet with path to the target dll, it takes about 100 ms to complete:
```
 time ../dotnet ~/dotnet/test/bin/Release/netcoreapp1.1/test.dll
Hello World!

real    0m0.090s
user    0m0.079s
sys     0m0.011s

```
However, running it via the dotnet tool using `dotnet run` command, I can reproduce the time you were getting:
 time ../dotnet run -c Release
Hello World!

real    0m2.329s
user    0m2.228s
sys     0m0.260s

**Comment by polarapfel** [comment]
Yeah, that's right. Curious. Why is that? What happens when the "run" command is invoked within the CLR?

And also, why does the "run" command behave so differently on Windows (fast/instant) versus Linux (slow init)?

**Comment by janvorli** [comment]
@polarapfel let me move this issue to cli repo since it is clearly a problem of the cli.

**Comment by janvorli** [comment]
Issue moved to [dotnet/cli #6241](https://github.com/dotnet/cli/issues/6241) via [**ZenHub**](https://www.zenhub.com/)
