### ISSUE TITLE
Incorrect and unexpected optimizer behavior for Interlocked.Exchange with short value

### ISSUE THREAD

**Issue by stefan-schweiger** [dotnet/coreclr#10714]
**NOTE:** _Most likely this does not just affect Interlocked.Exchange, but it's easy to reproduce this way._

When turning on the optimization for the following code you get different (and also **wrong**) output values than from building the application without turning on the optimizer.

```c#
using System;
using System.Threading;

class Program
{
    private static int _intToExchange = -1;
    private static short _innerShort = 2;

    static void Main( string[] args )
    {
        var oldValue = Interlocked.Exchange(ref _intToExchange, _innerShort);
        Console.WriteLine( "It was:   {0}", oldValue );
        Console.WriteLine( "It is:    {0}", _intToExchange );
        Console.WriteLine( "Expected: {0}", _innerShort );
    }
}
```

Without using optimization the output is as expected:
```
It was:   -1
It is:    2
Expected: 2
```

But when you turn on optimization (e.g. with `<Optimize>true</Optimize>` in .csproj) this is the output:
```
It was:   65535
It is:    -65534
Expected: 2
```

More about this bug can also be found here on [stackoverflow](http://stackoverflow.com/q/43206775/503059).

**Comment by mikedn** [comment]
> Most likely this does not just affect Interlocked.Exchange, but it's easy to reproduce this way.

As far as I can tell this affects `Interlocked.Add` and `Interlocked.Exchange`. Do you have other examples?

**Comment by stefan-schweiger** [comment]
I don't have any other examples, it was just my best guess that this would probably also affect other methods with similar signatures or internals.
