### ISSUE TITLE
[RyuJIT/ARM32] Implement struct argument passing

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/coreclr#10722]
In the comment, (#8496 (comment))
```
    268 morph.cpp:4610 - NYI_ARM: fgMorphMultiregStructArgs
```

And when we use ryujit for BringUpTest only, we can find 2 NYIs related with fgMorphMultiregStructArgs

- JIT/CodeGenBringUpTests/struct16args:Main
- JIT/CodeGenBringUpTests/StructFldAddr:Main

**Comment by mskvortsov** [comment]
`fgMorphMultiregStructArgs` gets called by `fgMorphArgs` at [morph.cpp:4373](https://github.com/dotnet/coreclr/blob/a5fef2172ad19d4c58e67c9e5bee10d247cd8929/src/jit/morph.cpp#L4366-L4375):
```c++
#ifndef LEGACY_BACKEND
    // In the future we can migrate UNIX_AMD64 to use this
    // method instead of fgMorphSystemVStructArgs

    // We only build GT_FIELD_LISTs for MultiReg structs for the RyuJIT backend
    if (hasMultiregStructArgs)
    {
        fgMorphMultiregStructArgs(call);
    }
#endif // LEGACY_BACKEND
```
For the ARM case, `hasMultiregStructArgs` gets set on at [morph.cpp:3767](https://github.com/dotnet/coreclr/blob/a5fef2172ad19d4c58e67c9e5bee10d247cd8929/src/jit/morph.cpp#L3762-L3769):
```c++
#ifndef _TARGET_X86_
                // TODO-Arm: Does this apply for _TARGET_ARM_, where structs passed by value can be split between
                // registers and stack?
                if (size > 1)
                {
                    hasMultiregStructArgs = true;
                }
#endif // !_TARGET_X86_
```
Does an answer for the question posed in that comment exist? In general, considering poor readability of the `fgMorphArgs` function, are there any shortcuts for understanding the logic behind it? What are the steps required to implement struct-passing ABI for the RyuJIT/ARM32?

Some existing documentation on the subject: [jit-call-morphing.md](https://github.com/dotnet/coreclr/blob/fe98261c0fef181197380d0b42c482eb6eddcf94/Documentation/design-docs/jit-call-morphing.md), [first-class-structs.md](https://github.com/dotnet/coreclr/blob/fe98261c0fef181197380d0b42c482eb6eddcf94/Documentation/design-docs/first-class-structs.md)
Some relevant past commits: [f6846c2d](https://github.com/dotnet/coreclr/commit/f6846c2d17997da6a94d7f5bc8afd913ce10b416) [b324afc3](https://github.com/dotnet/coreclr/commit/b324afc3e3175a41e53e46d8dfd9d5916908b348) [b2efe59b](https://github.com/dotnet/coreclr/commit/b2efe59bec6e0b70b2ede2dc0301a790d465e6a4) [81b2abba](https://github.com/dotnet/coreclr/commit/81b2abba239fad281ede4e715beac3856477e61c) [5cd42135](https://github.com/dotnet/coreclr/commit/5cd421355052cbd96dc841aa845f95858909e014) [e550cf35](https://github.com/dotnet/coreclr/commit/e550cf35bd5ff8e7eefcb1a605219f71a3672d83) 

@BruceForstall @briansull @CarolEidt Please share your thoughts and/or directions for further work.
cc @dotnet/jit-contrib @dotnet/arm32-contrib

**Comment by BruceForstall** [comment]
Also related: https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/multi-reg-call-nodes.md

I presume you will need to implement appropriate changes for fgMorphMultiregStructArgs() for arm32. I don't know what those changes are.

It is certainly true that fgMorphArgs() is daunting. We've had hopes of cleaning it up drastically, but that hasn't happened yet, obviously.

The interesting parts of the ARM32 ABI that affect things are: (1) struct arguments can be split between registers and stack, and (2) HFA.

**Comment by hseok-oh** [comment]
@BruceForstall @mskvortsov Exactly. I've seen this complex code for ARM32 legacy when I tried to find bug in ARM32 hfa and code generation for calling struct constructor. Thanks for sharing documents.

**Comment by hseok-oh** [comment]
Now we can pass struct argument using register only. But we cannot pass struct argument to use stack yet. 
- pass struct argument using stack only: blocked in codegen phase
- pass struct argument using stack and register(s): blocked in morphing phase

**Comment by hseok-oh** [comment]
Close this issue.
Remaining issues (promoted struct #12657 hfa #11783) will be handled on each issue.
