### ISSUE TITLE
Remove JIT32 infra from build pipeline

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#10734]
- [ ] Wait for #10733 to be fixed and closed.
- [ ] Stop invoking build.cmd with buildjit32 switch.
- [ ] Stop cloning JIT32 repo.
- [ ] Anything else necessary to clean up.

**Comment by wtgodbe** [comment]
Assigning you @pgavlin since you are working on https://github.com/dotnet/coreclr/pull/11262

**Comment by pgavlin** [comment]
Closed by #11262.
