### ISSUE TITLE
Allow IL Only mode

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/coreclr#10753]
We should enable something similar to COMPlus_ZapDisable that makes the whole system treat an NI image as if it were IL. This means not throwing a BadImageFormatException when the file is R2R and dealing with whatever other things would need to fallback to just treating the image as IL.

This would enable our community to try and piece things together from different systems especially places where we don't have an SDK. As creating R2R images becomes more popular, it will be nice to be able to decide to load some of them as IL.

**Comment by danmosemsft** [comment]
@gkhanna79 please set milestone.

**Comment by jkotas** [comment]
@janvorli has done it as https://github.com/dotnet/coreclr/pull/14389

**Comment by Petermarcu** [comment]
I was talking to some folks in ASP.NET and in some cases, even though the assemblies are crossgen'd they want to enable an application to opt certain sets of assemblies into JIT'ing mode to ensure throughput is what is being optimized for over startup. I'm trying to figure out what a natural gesture might be to opt a certain set (a metapackage maybe) out of R2R.

**Comment by jkotas** [comment]
You can set `COMPlus_ReadyToRunExcludeList` to the list of simple names to not use R2R for.

**Comment by Petermarcu** [comment]
Ok, I wonder if we can have a more official feature/way of doing this where the setting is persisted with the application based on something in the users project.

**Comment by jkotas** [comment]
I do not see a reason why we cannot have it. It would be about getting the set flowing through the tooling and dotnet host - https://github.com/dotnet/cli, https://github.com/dotnet/sdk and https://github.com/dotnet/core-setup. No or very minimal changes required in the runtime.

cc @karelz

**Comment by Petermarcu** [comment]
Ok, I'm working with asp.net on some things that may require this. Will circle back if we need to do anything.
