### ISSUE TITLE
An error: 'HOSTLOG: Failed to load ..\debug\coreclr.dll: Error code: 193'

### ISSUE THREAD

**Issue by stonecity** [dotnet/coreclr#1076]
I have successfully build the coreclr source code. But when I run my own console app use corerun in the command prompt I am getting following errors:
 ..\CoreCLR\coreclr-master\bin\Product\Windows_NT.x64.Debug>corerun /v Test.exe
 HOSTLOG: Attempting to load: C:\user\CoreCLR\coreclr-master\bin\Product\Windows_NT.x64.Debug\CoreCLR.dll
 HOSTLOG: Failed to load: C:\user\CoreCLR\coreclr-master\bin\Product\Windows_NT.x64.Debug\CoreCLR.dll
 HOSTLOG: Error code: 193

My environment: windows7 x64 and VisualStudio 2013 with update 4.

**Comment by janvorli** [comment]
Windows error 193 is ERROR_BAD_EXE_FORMAT. Is it possible that you try to run corerun using command prompt (cmd.exe) from C:\Windows\SysWOW64 instead of c:\Windows\cmd.exe?

**Comment by stonecity** [comment]
it doesn't work..

**Comment by janvorli** [comment]
@stonecity Could you please check if you still have this problem with the latest CoreCLR? I would like to close this issue if it works for you now.

**Comment by janvorli** [comment]
Closing the issue since we have not seen the error from other sources and there was no response from the bug creator.
