### ISSUE TITLE
[Arm64] CQ use load/store pair instructions

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#10769]
There are a number of places where use of ldp/stp is suggested to improve CQ.

**Comment by sdmaclea** [comment]
@jashook Please assign this to me

Partially addressed by #11143

**Comment by sdmaclea** [comment]
@dotnet/arm64-contrib @dotnet/jit-contrib 

- There are a few cases where ldp/stp are not emitted due to emitIns_R_S & emitIns_S_R not supporting ldp/stp.  Should the new functions to add this support be called emitIns_R_R_S &  & emitIns_S_R_R ?
- In general the there is only one attr when emitting ldp/stp.  What is the current/intended behavior?  
    1. second operand has same attr as first
    2. second operand has same size as first, but is treated as GC none
- Should support for mismatched attr be added ?
    1. Extra enum flags? i.e.  BYREF_2ND REF_2ND
    2. Extra attr2 parameter?
    3. Add emit pair forms.  i.e. emitIns_RP_R_I()

**Comment by sdmaclea** [comment]
Partially addressed by #11217

**Comment by briansull** [comment]
All good questions.
> In general the there is only one attr when emitting ldp/stp.
The sizes have to be the same., but the GC types can be different. 
We would like to be able to support the loading of different GC types.

There is an emitter issue that is blocking the use of ldp/stp for stack locals, 
we use the last register field to hold the extra register need for a large stack offset.

**Comment by sdmaclea** [comment]
Partially addressed by #11219

**Comment by sdmaclea** [comment]
@briansull I assume the large stack offset issue is not impossible to solve.  I'll plan on looking at emitIns_R_S & emitIns_S_R next week, I will use the names emitIns_R_R_S & emitIns_S_R_R.  Unless you have a preference.  I might have to special case the large stack offset case (prevent ldp/stp or claim an additional temporary).

**Comment by sdmaclea** [comment]
There are pull request open for most of the remaining issues

**Comment by sdmaclea** [comment]
The issues are fixed on Unix.  The Windows version is still waiting on #11420 & #11261
