### ISSUE TITLE
NETStandard Class Library - How to build/deploy a class library with all dependencies included?

### ISSUE THREAD

**Issue by dfarrNTST** [dotnet/coreclr#10766]
Sorry if this is the wrong repo to put this in...let me know and we'll move it.  

We have plugin applications that we allow developers to write modules/plugin Class Libraries and drop them into certain folders for our host applications to load.  In .NET Framework this worked very well because after doing a Build on a class library project, all DLL's (including NuGet package references) were put into the bin folder and we could copy the contents of bin into the plugin/module folder.  We must have this same functionality in NETStandard/.Net Core.

We've tried this in a NETStandard Class Library targeting netstandard1.4...we've added a few NuGet packages and another project reference to this class library.  After each build, the only files in bin/Debug/netstandard1.4 are the Class Library DLL, the project reference DLL, and the deps json file.  The NuGet packages DLL's are not included.  We cannot put the NuGet references in the Host application.  How do we get ALL DLL references to be put in the bin/Debug/netstandard1.4 folder?  We've also tried Publish which just creates a NuGet package.  We need ALL DLL's in the output folder for our build process so we can automate the copying of the full plugin/module code.

Is there a way to force the creation of all DLL's in the target framework bin folder on Build?  If not, is this on the roadmap to be included.  This is the last and only impediment for us to move to NETStandard/.Net Core.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/cli #6261](https://github.com/dotnet/cli/issues/6261) via [**ZenHub**](https://www.zenhub.com/)

**Comment by danmosemsft** [comment]
You want the CLI repo, good luck!
