### ISSUE TITLE
Hardware requirement of coreclr

### ISSUE THREAD

**Issue by linquize** [dotnet/coreclr#1078]
Is the hardware requirement of coreclr specified in wiki?

Including CPU instruction, speed for each architecture, memory footprint

**Comment by jasonwilliams200OK** [comment]
I think AMD, Intel x86-32/64 and ARM 32/64 are supported architectures. There are references of SPARC, MIPS (see https://github.com/dotnet/coreclr/issues/969), RISC and SuperH in code, but I don't think they are declared as supported architectures (yet?)
You can find quite many interesting facts/hints here: https://github.com/dotnet/coreclr/tree/master/src/jit.

**Comment by janvorli** [comment]
Only the x64 is supported at the moment. See the wiki here:
https://github.com/dotnet/coreclr/wiki/Developer-Guide
The 'Project Goals and Priorities' talks about it and the table below shows the current support.

**Comment by linquize** [comment]
I need more details, instead of looking at the source code
e.g. what minimum ARM version, software/hardware float, what minimum x86 (SSE2 required?)

**Comment by janvorli** [comment]
@jkotas Do we have any details on that?

**Comment by jkotas** [comment]
We have always matched CoreCLR minimum requirements to the minimum requirements of the underlying OS that it is supported on.

CoreCLR on x86 does not require SSE2. CoreCLR on ARM shipping on Windows Phone is ARMv7, hardware float. Because of these are the minimum requirements of the underlying OSes.

**Comment by whoisj** [comment]
@jkotas :+1:

**Comment by zezba9000** [comment]
I posted a suggestion in the .NET Foundation forums about Open Sourcing key parts of .NET Compact that has already has run on MIPS, PPC, ARM, ect for years: http://forums.dotnetfoundation.org/t/open-source-net-compact-runtime/1190

I think being able to use it as references source would greatly help the efforts of this topic.  If i'm right you might consider voicing this suggestion as well :)

**Comment by tzwlai** [comment]
Closing this issue since it looks like it has been adequately addressed and there hasn't been any activity in a while.  Please feel free to reopen if anyone feels differently.
