### ISSUE TITLE
NullReferenceException during 'dotnet build' on ubuntu arm32

### ISSUE THREAD

**Issue by eerhardt** [dotnet/coreclr#10780]
It appears there is a JIT bug on ubuntu arm machines. While trying to get a .NET Core SDK that runs on my Raspberry Pi, I encountered an error:

```
Microsoft (R) Build Engine version 15.2.93.5465
Copyright (C) Microsoft Corporation. All rights reserved.

/home/ubuntu/dotnet/sdk/2.0.0-preview1-005720/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(93,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [/home/ubuntu/HelloWorld/HelloWorld.csproj]
/home/ubuntu/dotnet/sdk/2.0.0-preview1-005720/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(93,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [/home/ubuntu/HelloWorld/HelloWorld.csproj]
/home/ubuntu/dotnet/sdk/2.0.0-preview1-005720/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(93,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileLookup..ctor(LockFile lockFile) [/home/ubuntu/HelloWorld/HelloWorld.csproj]
/home/ubuntu/dotnet/sdk/2.0.0-preview1-005720/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(93,5): error MSB4018:    at Microsoft.NET.Build.Tasks.DependencyContextBuilder.Build() [/home/ubuntu/HelloWorld/HelloWorld.csproj]
```

Looking into that code, there was no way a NullReferenceException was coming from that method.

Using Console.WriteLines, I traced it down to [this exact line that was failing](https://github.com/dotnet/sdk/blob/09c2a6bd8e2c0ec1524361d3a560a1ef961e4367/src/Tasks/Microsoft.NET.Build.Tasks/LockFileLookup.cs#L26).  Note that `LibraryType` is a struct.

I have 2 repos of this bug, one is the long way and one is the short way.

### Short Repo
- Clone https://github.com/eerhardt/ArmJITBug
- Using the [latest 2.0 SDK](https://github.com/dotnet/cli#installers-and-binaries) (on a non-linux-arm machine or else you will run into this bug 😀)
  - dotnet restore
  - dotnet publish -c Release
- Copy the contents of `bin\Release\netcoreapp2.0\publish` to a Raspberry Pi running a recent [ubuntu (14 or 16) arm32 build](https://github.com/dotnet/core-setup#daily-builds) of dotnet.
- On the Pi:  `dotnet App.dll`.

#### result
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at TestIt.LockFileLookup..ctor(LockFile lockFile) in F:\DotNetTest\TestIt\App\Program.cs:line 30
   at TestIt.Program.Main(String[] args) in F:\DotNetTest\TestIt\App\Program.cs:line 14
```

### Long Repo
- Extract an ubuntu arm32 [shared framework](https://github.com/dotnet/core-setup#daily-builds) tarball onto your Raspberry Pi/arm machine.
- Build the dotnet/cli repo using `--configuration Release /p:DISABLE_CROSSGEN=1`.
- Extract the `artifacts/RID/packages/dotnet-sdk-RID.VERSION.tar.gz` archive into the same folder as the shared framework on your arm machine.  This will get you the SDK installed on your machine.

1. `dotnet new console`
1. `dotnet restore`
1. `dotnet run`

#### result
Same error as above with GenerateDepsFile task failing during the build.

## Notes
This only happens when I build the managed assembly for `Release`. The error doesn't repro when I build for `Debug`.

/cc @Petermarcu @jaredpar @VSadov @RussKeldorph

**Comment by RussKeldorph** [comment]
@BruceForstall @dotnet/samsung 

/cc @dotnet/jit-contrib

**Comment by eerhardt** [comment]
I forgot to attach the ILDASM of the method in question.

[LockFileLookup.Debug.txt](https://github.com/dotnet/coreclr/files/904117/LockFileLookup.Debug.txt)
[LockFileLookup.Release.txt](https://github.com/dotnet/coreclr/files/904116/LockFileLookup.Release.txt)

**Comment by jyoungyun** [comment]
I'm trying to test dotnet cli in Raspberry PI3. But `dotnet build` occurs the same error in PI3 board. When I added ArgumentNullException in LockFileLookup.cs file, this issue seems to be resolved. But I'm not sure if my changes are right or not. In my case, this issue occurs debug build. 

https://github.com/dotnet/sdk/issues/1094

**Comment by jyoungyun** [comment]
The NuGet.Config in https://github.com/eerhardt/ArmJITBug should be added `<add key="cli-deps" value="https://dotnet.myget.org/F/cli-deps/api/v3/index.json" />` source to restore NuGet.ProjectModel. :)

**Comment by hqueue** [comment]
@jyoungyun Thanks! :) I was facing same problem.

**Comment by hqueue** [comment]
After some investigation, I found that some hoisted copy generated in preheader of loop contains invalid values which is used to load loop invariant variable. I've used the example @eerhardt shared and the loop is https://github.com/eerhardt/ArmJITBug/blob/master/Program.cs#L30.

However I have to go out and will start debugging again next week if this issue is still live next week.

**Comment by eerhardt** [comment]
> The NuGet.Config in https://github.com/eerhardt/ArmJITBug should be added <add key="cli-deps" value="https://dotnet.myget.org/F/cli-deps/api/v3/index.json" /> source to restore NuGet.ProjectModel. :)

Thanks for letting me know.  I've pushed a change to fix it.

**Comment by eerhardt** [comment]
Doing a little more narrowing down the line causing the issue:

```C#
        public LockFileLookup(LockFile lockFile)
        {
            _packages = new Dictionary<KeyValuePair<string, NuGetVersion>, LockFileLibrary>();
            _projects = new Dictionary<string, LockFileLibrary>(StringComparer.OrdinalIgnoreCase);

            foreach (var library in lockFile.Libraries)
            {
                Console.WriteLine("Got Here");

                var libraryType = LibraryType.Parse(library.Type);
                Console.WriteLine($"Got Here2 {libraryType}");

                var package = LibraryType.Package;
                Console.WriteLine($"Got Here3 {package}");
                
                if (libraryType == package)
                {
                    Console.WriteLine("Got Here4");
                    _packages[new KeyValuePair<string, NuGetVersion>(library.Name, library.Version)] = library;
                }
                
                Console.WriteLine("Got Here5");
```

Outputs:

```
ubuntu@ubuntu:~/TestIt$ ~/dotnet/dotnet App.dll
Got Here
Got Here2 package

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at TestIt.LockFileLookup..ctor(LockFile lockFile) in F:\git\ArmJITBug\Program.cs:line 37
   at TestIt.Program.Main(String[] args) in F:\git\ArmJITBug\Program.cs:line 14
```

### Potential Workaround
Also, as pointed out in @jyoungyun's PR https://github.com/dotnet/sdk/pull/1095, a potential workaround here is to add a `throw` statement into the code.  Adding a fake `if` check and a `throw` causes the problem not to repro:

```C#
            foreach (var library in lockFile.Libraries)
            {
                if (string.Empty == null)
                {
                    throw new ArgumentNullException();
                }
                
                Console.WriteLine("Got Here");

                var libraryType = LibraryType.Parse(library.Type);
```

**Comment by gkhanna79** [comment]
@RussKeldorph Is this on track for 2.0?

**Comment by RussKeldorph** [comment]
@gkhanna79 I do not expect to block 2.0 for it if that's what you mean.  We are still trying to determine if we can create a fix that will meet the risk/reward bar.

**Comment by gkhanna79** [comment]
Should this be moved to 2.1 then?

**Comment by RussKeldorph** [comment]
Not until we either determine it cannot affect x86 and x64 or we determine we can't come up with an acceptable fix.

**Comment by jyoungyun** [comment]
@hseok-oh is analyzing this issue. Related PR is https://github.com/dotnet/coreclr/pull/11198.
