### ISSUE TITLE
Treat readonly fields as JIT time constants.

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#1079]
If understand it  right mutating readonly fields outside of constructors is forbidden at CLR level.

In certain conditions this could allow JIT to treat static fields of classes as JIT time constants.
And it opens interesting opportunities.
For example, there is already a JIT times constant - IntPtr.Size. In the following code JIT will get rid  not only of the wrong branch but the comparison itself:
```C#
if (IntPtr.Size == 32)
{
    Console.WriteLine("It is an x86 process");
}
else
{
    Console.WriteLine("It is an x64 process");
}
```

JIT could do the same with "constant" static readonly fields. 
Imagine such field:
```C#
private static bool etwLoggingEnabled = ReadValueFromConfig();
```
And this check:
```C#
if (etwLoggingEnabled)
{
    DoEtwLogging();
}
```
Or it could be a performance counter or other similar thing.

Another case is  static readonly  array fields. JIT could skip bounds checking as if it were a local variable or a parameter.

There are possibly other  optimization opportunities, you guys know your JIT better ;)

**Comment by mikedn** [comment]
"For example, there is already a JIT times constant - IntPtr.Size. In the following code JIT will get rid not only of the wrong branch but the comparison itself"

As far as I can tell RyuJIT already does that:

```C#
if (IntPtr.Size == 8)
    Console.WriteLine(IntPtr.Size);
```
generates this
```
mov         ecx,8  
call        00007FFC36ADC1B0  
```

> If understand it right mutating readonly fields outside of constructors is forbidden at CLR level.

Yet the following code runs and prints 42:
```C#
public class Program {
    public static readonly int x = 1;

    static void Main() {
        typeof(Program).GetField("x").SetValue(null, 42);
        Console.WriteLine(typeof(Program).GetField("x").GetValue(null));
    }
}
```

**Comment by omariom** [comment]
>As far as I can tell RyuJIT already does thatAs far as I can tell RyuJIT already does that

The idea is to extend it to static readonly fields.

> Yet the following code runs and prints 42:

yeah.. that's not complete readonliness :disappointed:

**Comment by GeirGrusom** [comment]
What about static readonly delegates? Could they be inlined or lifted?

**Comment by mikedn** [comment]
> The idea is to extend it to static readonly fields

Ah, I see. It does that too:
```C#
public class Program {
    public static readonly int x = 1;
    static void Main() {
        if (x == 1)
            Console.WriteLine(x);
    }
}
```
generates
```
sub         rsp,28h  
mov         ecx,1                            ;no if
call        00007FFC36ADC1B0  
add         rsp,28h  
ret  
```

> What about static readonly delegates? Could they be inlined or lifted?

Nope. Delegates are never inlined by current .NET JIT compilers.

**Comment by omariom** [comment]
WHAAAT!?? It is already there!?

Huge thanks guys! I dreamed of this feature :) 

:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Comment by omariom** [comment]
I checked it with ProcessorCount (just to be sure)
```C#
class Program
    {
        public static readonly int procCount = Environment.ProcessorCount;

        static void Main(string[] args)
        {
            if (procCount  == 2)
                Console.WriteLine("!");
        }
    }
```
if is completely eliminated. As well as WriteLine if procCount != 2.

It think this RuyJIT ability deserves a separate post in JIT team  blog. People should know about it.

**Comment by briansull** [comment]
For scalar types such as int or floats the JIT compilers have optimized this readonly fields since CLR 3.5 at least.  If an Object based readonly static field is initialized then it is not possible to optimize them as their values depend upon the address assigned at runtime.

**Comment by omariom** [comment]
I am happily closing this issue.
