### ISSUE TITLE
NUMA support on non-Windows platforms

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#10796]
Is there support for NUMA on non-Windows platforms?

**Comment by janvorli** [comment]
@tmds not yet. As I've mentioned in another issue, I am working on adding that support for GC right now.

**Comment by tmds** [comment]
Great. I wonder, does this make allocations numa aware? And will the ThreadPool be numa aware too?

**Comment by gkhanna79** [comment]
@janvorli IIRC, you were planning to get this done for 2.0, right?

**Comment by janvorli** [comment]
@gkhanna79 yes, it went already in (#10938).

**Comment by gkhanna79** [comment]
Ok - closing this issue in that case.
