### ISSUE TITLE
Reenable symweb indexing in coreclr/master

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#10809]
In https://github.com/dotnet/coreclr/pull/10807 I disabled symweb indexing in the master branch builds. Once we get a better handle on infra issues, we need to enable it again.

**Comment by danmosemsft** [comment]
@dagood is this on track for 5/10 ZBB? 
@dleeapho @markwilkie @Chrisboh @weshaggard

**Comment by dagood** [comment]
Yes, I'm creating a PR on `master` today. I'll be working on porting it to `release/2.0.0` after that.

The PR is the same concept as this one in CoreFX: https://github.com/dotnet/corefx/pull/18350 "Add separate symbol publish (index/archive) build leg". (I also will be porting that to CoreFX/release/2.0.0.)

**Comment by dagood** [comment]
This is now merged into `master`. (Not in `release/2.0.0` yet.)
