### ISSUE TITLE
[Arm64/Unix] valgrind memcheck 

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#10800]
Initial valgrind testing did not look clean.  Rerun and review logs.  Fix errors.

**Comment by sdmaclea** [comment]
Attempted to run on an arm64 system with 128 byte cache lines.  Hit this assertion issue https://bugs.kde.org/show_bug.cgi?id=380202

**Comment by danmosemsft** [comment]
@sdmaclea just happened to notice from that link above that the fix seems to be in the latest release of valgrind - if you want to try again.

**Comment by sdmaclea** [comment]
As @danmosemsft noted the issue cited above was fixed in Valgrind 3.13 release.  I just built vqlgrind 3.13 from source and tested ASP.NET plaintext benechmark.

I am seeing 

```
disInstr(arm64): unhandled instruction 0xD5033F5F
disInstr(arm64): 1101'0101 0000'0011 0011'1111 0101'1111
==37928== valgrind: Unrecognised instruction at address 0x534d1a8.
==37928==    at 0x534D1A8: InterlockedCompareExchange (pal.h:4402)
```

The unrecognized instruction is a `clrex`.  

I get the same error even on lighter tests i.e. `JIT/CodeGenBringUpTests/Add1`

**Comment by danmosemsft** [comment]
Ugh - well you may want to file more issues. ..

**Comment by sdmaclea** [comment]
I have not tried again.  This is clearly a Valgrind issue and not a CoreCLR issue.

It seems valgrind would have very limitied usefulness for CLR testing.  IT probably makes sense to close this issue.
