### ISSUE TITLE
Link to the List.cs file is broken in contributing.md

### ISSUE THREAD

**Issue by mazong1123** [dotnet/coreclr#10822]
The `List.cs` link is broken in:
https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md#file-headers
Seems like the List class was removed from https://github.com/dotnet/corefx/tree/master/src/System.Collections/src/System/Collections/Generic

I found another `List.cs` in https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/List.cs
But I'm not sure if it is the right one.

**Comment by danmosemsft** [comment]
You're right, want to submit a fix?

**Comment by mazong1123** [comment]
Yes. I'll submit a PR.
