### ISSUE TITLE
Singles sometimes have Double precision in x86 jit

### ISSUE THREAD

**Issue by ccurrens** [dotnet/coreclr#1082]
I think I've found an issue where single-precision floats sometimes have double-precision. I understand why it is happening, but I don't think it should behave the way it is. This affects CoreCLR and the desktop .NET framework, only in 32-bit processes when run in release mode. 64-bit processes are not affected, at least on my machine. I'm going to write this in more detail than is probably necessary for someone who is working on the jitter, but I'm hoping it makes it simple enough for anyone who reads it to understand (this includes me!).

### The bug

Floating point math in the x86 jitter uses instructions that perform it in a higher precision than the type can represent. For example, for a method with a return type of `Single`, the math performed will be done with extended double precision. If the return value is casted to a double, it's converted directly to a double from its extended precision form, making it look like the `Single` return value has a higher precision than it actually does. This creates inconsistencies in code, because sometimes the return value acts like it has a different precision sometimes. It should probably have converted the return value to a `Single` first and then converted that truncated value to a `Double`.

### Repro

Here is some code that demonstrates the issue:

```csharp
using System;

namespace FPTest
{
    class Program
    {
        static void Main(string[] args)
        {
            // Other values work, as well
            const Single a = 21.453241f, b = 1654853, c = 0.5f;

            var scoreValue = Score(a, b, c);
            Console.WriteLine(scoreValue);
            Console.WriteLine((Double)scoreValue);
            Console.WriteLine((Double)Score(a, b, c));
        }

        static Single Score(Single a, Single b, Single c)
        {
            return a + (b - a) * c;
        }
    }
}
```

**Output**

x64 (Release):

    827437.2
    827437.1875
    827437.1875

x86 (Release):

    827437.3
    827437.25
    827437.226620674

The difference between the values between x64 (`827437.2`) and x86 (`827437.3`) isn't significant[1]. However, the difference between the second and third lines of x86's output is. I would have expected the output lines 2 and 3 to be the same, since `scoreValue` and `Score(a,b,c)` are calculated using the same parameters.

### Explanation

Floating point in the x86 jitter uses instructions on the x87 coprocessor. By default, the x87 coprocessor uses 80-bit extended double precision for all floating point math (double and single). The last `Console.WriteLine` has the return value from `Score` directly passed to it after converting it to a `Double`. The jitter never emits code to truncate the value to single precision before converting it to double precision and passing it to `WriteLine`. Here is what the the jitter emitted, with some instructions removed for brevity:

    var scoreValue = Score(a, b, c);
        push    c
        push    b
        push    a
        call    FPTest.Program.Score(Single, Single, Single)

    // Return value from Score is already in st0
    // this duplicates the st0 and pushes a copy into st1
        fld     st(0) 

    Console.WriteLine(scoreValue);
    // Store st0 and st1 on the stack
    // Using a dword pointer with fstp will cause it to
    // convert the value from st* registers to single precision
        fstp    dword ptr [esp]
        fstp    dword ptr [ebp-4]
        call    System.Console.WriteLine(Single)

    Console.WriteLine((Double)scoreValue);
    // Load the previously stored single precision value
    // and put it back on the stack in double precision
    // the qword ptr causes fstp to do the double conversion
        fld     dword ptr [ebp-4]
        fstp    qword ptr [ebp-0Ch]
        fld     qword ptr [ebp-0Ch]
        sub     esp,8
        fstp    qword ptr [esp]
        call    System.Console.WriteLine(Double)

    Console.WriteLine((Double)Score(a, b, c));
        push    c
        push    b
        push    a
        call    FPTest.Program.Score(Single, Single, Single)
    // At this point, the return value from Score is in st0 with 80-bit 
    // extended precision.
    // fstp is called using a qword ptr, which converts the extended 
    // precision value directly to a double. It seems there should
    // be a conversion to single precision before passing the value
        fstp    qword ptr [ebp-0Ch]
        fld     qword ptr [ebp-0Ch]
        sub     esp,8
        fstp    qword ptr [esp]
        call    System.Console.WriteLine(Double)

The return value from `Score` is a `Single`, but due to the extended precision in x87 it makes it appear to have returned a `Double`, at least in certain cases. Commenting out the line `Console.WriteLine(scoreValue)` changes the output of the second line (it would now have `Double` precision) because the value is never pushed onto the stack as a `Single`.

If the a cast to `Single` is explicitly added to the code, either in the return value for `Score` or as so `Console.WriteLine((Double)(Single)Score(a, b, c));` the code behaves as I would expect, because the jitter emits this code instead:

    call    FPTest.Program.Score(Single, Single, Single)
    // conversion to Single precision
    fstp    dword ptr [ebp-4]
    fld     dword ptr [ebp-4]
    // conversion to Double precision
    fstp    qword ptr [ebp-0Ch]
    fld     qword ptr [ebp-0Ch]
    sub     esp,8
    fstp    qword ptr [esp]
    call    System.Console.WriteLine(Double)

However, both Resharper and Roslyn complain that the cast to `Single` is unnecessary even though it changes the behavior of the program.

---------------------

[1] The reason for the difference is because x64 uses SSE2 instructions and chooses instructions that uses single precision math. In x86, the x87 coprocessor is used which by default does all floating point calculations using 80-bit extended double precision. When the values are converted to single precision, they have slightly different values due to the increased precision during the calculations.

**Comment by mikedn** [comment]
It's unlikely to be a JIT bug because the CIL spec does clearly state that floating point computations may be done at a higher precision:

> Partition 1 - 12.1.3 ... Everywhere else (on the evaluation stack, as arguments, as return types, and as local variables) floating-point numbers are represented using an internal floating-point type. In each such instance, the nominal type of the variable or expression is either float32or float64, but its value can be represented internally with additional range and/or precision.

It also notes that you may get different results depending on the code and JIT:

> [Note: The use of an internal representation that is wider than float32 or float64 can cause differences in computational results when a developer makes seemingly unrelated modifications to their code, the result of which can be that a value is spilled from the internal representation (e.g., in a register) to a location on the stack. end note]

The specification itself may be debatable but at this point I'd rather see the x86 JIT use SSE2 instead of x87. But since CoreCLR doesn't support x86 this is a bit out of place.

**Comment by ccurrens** [comment]
Oh, I didn't see that CoreCLR doesn't support x86, although I see it now on [the wiki](https://github.com/dotnet/coreclr/blob/master/Documentation/project-priorities.md). I had assumed it was supported since you can pull it down via dnvm.

I know that it's supported to represent the values internally in a wider precision (otherwise, x87 would be against the spec), the issue is more about the inconsistent behavior when the same value is read from the stack vs. passed in directly from the register. It just makes it appear that sometimes the JIT truncates the value and sometimes it doesn't.

I don't know if it will be considered a bug or not. If it's not, or it's out of scope, feel free to close.

**Comment by briansull** [comment]
Yes what you describe is by design.

It allows locals variable of type float to be enregistered on 32-bit x86 platform.
Enregistering float locals can greatly enhance floating point performance, and is explicitly allowed by the IL spec.

**Comment by briansull** [comment]
Note that By default, the x87 coprocessor uses a either a 64-bit or an 80-bit extended double precision for all floating point math (double and single).  It is controlled by setting a bit in the Floating Point Control Word and the default that is used by the x86 CLR is to use 64-bit or standard double precision for floating point math.

**Comment by ccurrens** [comment]
@briansull Thanks for confirming that it's by design. That along with the spec that @mikedn quoted (I probably should have looked there first!) makes it very clear. I'll close the issue.
