### ISSUE TITLE
Build System Portability Improvement

### ISSUE THREAD

**Issue by Rew** [dotnet/coreclr#10836]
I have recently been working on porting a build of corlib to a new target OS.  I have managed to get it building successfully, however I believe that there are some improvements that could be made to the build system.  I will give a few specific suggestions, but I would guess those more familiar with the entire build process could offer some in addition.  I think more could be done on the documentation side as well to attract and enable new platforms to participate.

- There are a few locations in the msbuild process that use "$(TargetsUnix) != 'true".  The expectation is that these are conditionals that are intended to be included in Windows builds.  These declarations are troublesome since the cause undesired code to be included for other targets as they are added.  I would suggest to adjust all conditional compile directives to be opt in as opposed to opt out.  I'd have to double check where it is, but these may be candidates for some feature flags that are selected early on in the build process instead of having target specific flags down the road.
- The project file for Private.CoreLib has multiple areas of conditional file includes depending on target.  This has 2 problems.  The first one is that it makes it challenging to determine which parts of the project are intended to be target specific.  This is a challenge when introducing new targets as well as maintaining existing targets.  The second issue, and likely more important one, is that an update to a specific target requires a change to the primary project file.  I would suggest to have the primary project file import target specific files.  This could be 1 file per target or 1 file per target per featureset (i.e. globalization).  My prefered approach would just be a Private.CoreLib.Win32.targets, Private.CoreLib.Unix.targets, etc.  Possibly the main project could import these by the OS moniker if they exist so new targets wouldn't have to make a change to the project file at all.
- There is at least 1 case where a target specific partial class exists in shared for 1 target and in the main project for another.  I would suggest that migrations to shared are done on a "all or none" bases for target specific partial classes.

Let me know what you guys think.  I am already working on updates along these lines for my own personal fork, but I would be happy to include some additional feedback and roll it into the main fork.

**Comment by jkotas** [comment]
1. Changing `"$(TargetsUnix) != 'true'` to be opt-in using `$(TargetsWindows)` should be absolutely fine.

2. I think grouping the target specific files together should be definitely fine. It is done that way in the shared project already. I am not sure whether moving them to separate files is a good idea. It tends to not work well with Visual Studio.

3. Which one is it? It should be point in time problem. We probably have not moved the that other file to the shared project yet.

Thanks!

**Comment by Rew** [comment]
1. Sounds good.  I'll submit with the cases that I found after I isolate the changes and at least test the windows builds.

2. I understand the concern with Visual Studio.  My initial inclination was to just group in the project file.  The separate imports was an idea to try and partition updates required for a specific target a little more as well as easing the instructions for a new target.  I will group the target specific files for now and hold on my suggestion till later.  Once better organized it would be an easy update to do this at a later point if too many targets becomes a problem.

3.  SecureString I just found.  Unix is in shared, Win32 is not.

**Comment by danmosemsft** [comment]
@Rew  I'm curious what this target OS is?

**Comment by Rew** [comment]
@danmosemsft An embedded OS written in C# that has been in progress for a couple of years.  It has a functional AOT compiler tool chain with x86 and partial x64 support.  The closest example would probably be Singularity, but with an actual goal in mind.  The project I have been working on includes both the OS toolkit (Visual Studio Extension) and an OS built on it.  While there are some realistic prospects to commercialize, I wouldn't expect you to hear about it anytime soon.

The framework ends up being used in the AOT compile of the kernel as well as the framework for all modules loaded by the kernel at runtime.

Originally, I had developed a custom (ECMA-335 compliant) corelib and (very limited) framework libraries.  Due to licensing when starting the project, Mono wasn't a preferable option.  It turns out writing a framework with 1 person is time consuming (and far less interesting than compiler or gc development).  I hope that by working with the dotnet team I can still have the satisfaction of contributing to the framework, but focus a bit more on the OS.

**Comment by jkotas** [comment]
> SecureString I just found.

I have submitted a fix fort this one.

> The framework ends up being used in the AOT compile of the kernel

CoreRT may be better factored for this scenario. (Though, we are working towards sharing large part of CoreLib between CoreCLR and CoreRT so it should not really matter.)

**Comment by jkotas** [comment]
Fixed by #10839
