### ISSUE TITLE
Failed to load the coreclr.dll

### ISSUE THREAD

**Issue by gmeena** [dotnet/coreclr#10832]
hosting machine, window server 2008, IIS 7
running dotner --help giving this error. attached in image
![dotnetcore error](https://cloud.githubusercontent.com/assets/8595001/24836743/f46c375c-1d41-11e7-9f52-54a2fe022018.jpg)

After so much googling could not able to find solution so posting here. same is working in local machine.
I guess everything required already installed 
![core soft](https://cloud.githubusercontent.com/assets/8595001/24836843/5f2a1814-1d44-11e7-80c0-16f7c401a023.jpg)
![dotnetcore error](https://cloud.githubusercontent.com/assets/8595001/24851302/c4328cd0-1df0-11e7-80d6-b7e59f0158ff.jpg)

**Comment by mikedn** [comment]
Window Server 2008 or Windows Server 2008 R2?

I don't see Window Server 2008 listed in the [Prerequisites](https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites) doc.

**Comment by gmeena** [comment]
please see updated description with one more screen shot

**Comment by mikedn** [comment]
So it is Windows Server 2008, not 2008 R2. It's unfortunate that the installer doesn't block install on 2008 but the documentation doesn't include 2008 as a supported OS.

**Comment by gmeena** [comment]
So it will not work on 2008 WS.

**Comment by jkotas** [comment]
cc @gkhanna79

**Comment by gkhanna79** [comment]
Issue moved to [dotnet/core-setup #2016](https://github.com/dotnet/core-setup/issues/2016) via [**ZenHub**](https://www.zenhub.com/)
