### ISSUE TITLE
PreserveCompilationContext not working with netcoreapp2.0

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/coreclr#10849]
I have
`'<PreserveCompilationContext>true</PreserveCompilationContext>`

in my csproj, when I compile for .netcoreapp1.1 everything works fine, but if I try netcoreapp2.0 it doesn't seem to work.

I get an exception:
Can not find compilation library location for package 'microsoft.netcore.app''

**Comment by Liriel** [comment]
same here - can't tie the error to `PreserveCompilationContext` though
looks like this is a windows only problem, works on my linux box (both build 2.0.0-preview1-005683)

**Comment by danwalmsley** [comment]
@Liriel do you think the issue is with running on Windows, or with compiling on Windows?

**Comment by davidfowl** [comment]
Can you move this bug to https://github.com/aspnet/MvcPrecompilation

**Comment by danwalmsley** [comment]
@davidfowl can do, although my issue is with a non-mvc application, is the issue still valid there?

**Comment by davidfowl** [comment]
Ah no, maybe dotnet/sdk is more appropriate.

**Comment by Liriel** [comment]
@danwalmsley: the error is thrown when calling `dotnet run` building works fine in both environments

**Comment by danwalmsley** [comment]
https://github.com/dotnet/sdk/issues/1111

**Comment by danmosemsft** [comment]
OK since it's moved i'll close.
