### ISSUE TITLE
dotnet --help not working on hosting environment

### ISSUE THREAD

**Issue by gmeena** [dotnet/coreclr#10845]
I am not able to run dotnet --help command at my hosting server. local machine working fine. 
It seems that there is problem in dotnet core installation on hosting environment.

hosting machine, window server 2008, IIS 7

Installed on hosting environment
https://cloud.githubusercontent.com/assets/8595001/24836843/5f2a1814-1d44-11e7-80c0-16f7c401a023.jpg

**Comment by mikedn** [comment]
Seems similar to #10832

**Comment by jkotas** [comment]
Closing as dup
