### ISSUE TITLE
publishing netcoreapp2.0 doesnt generate an exe

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/coreclr#10854]
So I'm using latest build on windows and ubuntu 14.04 I have rids in my csproj, but publishing isn't including .exe for my app.

**Comment by benaadams** [comment]
Cli issue? https://github.com/dotnet/cli/issues/6237

**Comment by danwalmsley** [comment]
sorry my bad, it was that its a netcore2 app and I didn't realise it was actually using the dotnet 1.0.1 cli on my machine to build it! Amazed that it even works.
