### ISSUE TITLE
Produce and upload symbols for Linux

### ISSUE THREAD

**Issue by bleroy** [dotnet/coreclr#10868]
We need to produce (and sign):

- [x] Portable PDBs (same as Windows)
- [n/a] Windows PDBs converted from Portable PDBs (same as Windows) (use converter tool)
- [x] DWARF symbols from native libraries (e.g. CoreCLR.so)
- [x] DWARF symbols from CrossGen, when available/possible (currently not possible, symbols generation should be implemented with equivalent of /createPDB command in CrossGen)

We then need to upload those to:

- [x] [SymWeb](http://symweb)
- [x]  Msdl 
- [x] Download Center

**Comment by bleroy** [comment]
cc @lt72

**Comment by bleroy** [comment]
Related: #10419

**Comment by dleeapho** [comment]
Infra work tracked in:
https://github.com/dotnet/core-eng/issues/702
https://github.com/dotnet/core-eng/issues/701
https://github.com/dotnet/core-eng/issues/700
https://github.com/dotnet/core-eng/issues/699
https://github.com/dotnet/core-eng/issues/698

**Comment by karelz** [comment]
Let's use only 1 label to avoid double-counting and clarify responsibility - Infrastructure area per guidance from @lt72

**Comment by danmosemsft** [comment]
@dleeapho there are 3 of these symbol tasks -- do you expect to get them done for ZBB on 5/10? Want to make sure this isn't falling between teams.

@weshaggard @markwilkie @Chrisboh

**Comment by danmosemsft** [comment]
Also what if naything needs doing here for preview1.

**Comment by dleeapho** [comment]
This is tracking infra work that is set to be done post ZBB (5/8-5/26). @lt72 is aware of the timeline.

@lt72, correct me if I'm wrong but none of this is in scope for preview1.

**Comment by lt72** [comment]
you are correct: none of this is in scope for preview 1.

**Comment by karelz** [comment]
Just want to clarify Preview1 and ZBB are independent dates. Preview1 work happens in rel/2.0.0 branch. ZBB is for master and last integration from master to rel/2.0.0 branch.

Infra work is fine to be post-ZBB, just send me and Dan list of things you want to move there. Thanks!

**Comment by karelz** [comment]
@dleeapho @lt72 this is still marked as 2.0.0. Can we close it as done, or do we need to keep (parts?) for 2.1?

**Comment by mikem8361** [comment]
Symbol indexing and uploading is now automated.
