### ISSUE TITLE
Produce and upload symbols for Windows

### ISSUE THREAD

**Issue by bleroy** [dotnet/coreclr#10873]
We need to produce (and sign):

- [x] Portable PDBs
- [x] Windows PDBs converted from Portable PDBs
- [x] PDB symbols from native libraries (e.g. CoreCLR.dll)
- [x] PDB symbols from CrossGen, if available/possible

We then need to upload those to:

- [x] [SymWeb](http://symweb) (automate)
- [x] [Msdl](http://msdl.microsoft.com/download/symbols) (automate)
- [x] Download Center (automate)

cc @lt72

**Comment by dleeapho** [comment]
Infra work tracked in:
https://github.com/dotnet/core-eng/issues/702
https://github.com/dotnet/core-eng/issues/701
https://github.com/dotnet/core-eng/issues/700
https://github.com/dotnet/core-eng/issues/699
https://github.com/dotnet/core-eng/issues/698

**Comment by karelz** [comment]
Let's use only 1 label to avoid double-counting and clarify responsibility - Infrastructure area per guidance from @lt72

**Comment by gkhanna79** [comment]
@dleeapho Is the tracking upto date?

**Comment by dleeapho** [comment]
@gkhanna79 yes, they are slated for S118 (5/8-5/26).

**Comment by karelz** [comment]
@dleeapho does it affect the product code? If it is infra which can light up post-ZBB (5/10), we could mark it as Post-ZBB ...

cc @danmosemsft @Petermarcu

**Comment by lt72** [comment]
This is infra and should be marked as post-ZBB, unless @dleeapho has a reason not to.

**Comment by dleeapho** [comment]
The infra will not affect product code. Agree post-ZBB.

**Comment by devinvisible** [comment]
I'm not sure if "Microsoft Symbol Servers" (mentioned under Debugging > Symbols in the Options dialog of Visual Studio 2017) is accounted for by the "We then need to upload those to" locations mentioned by the original poster but it should be. Also consider publishing to https://msdl.microsoft.com/download/symbols so that classic _NT_SYMBOL_PATH setups will just work.

**Comment by lt72** [comment]
`consider publishing to https://msdl.microsoft.com/download/symbols so that classic _NT_SYMBOL_PATH setups will just work`

we will do that.

**Comment by gkhanna79** [comment]
@dleeapho Can this (and the other two similar issues) be closed?

**Comment by karelz** [comment]
@dleeapho @lt72 this is still marked as 2.0.0. Can we close it as done, or do we need to keep (parts?) for 2.1?

**Comment by lt72** [comment]
2.0.x

**Comment by mikem8361** [comment]
The symbol indexing and uploading is now automated.
