### ISSUE TITLE
Produce and upload symbols for macOS

### ISSUE THREAD

**Issue by bleroy** [dotnet/coreclr#10872]
We need to produce (and sign):

- [x] Portable PDBs (same as Windows)
- [n/a] Windows PDBs converted from Portable PDBs (same as Windows)
- [x] DWARF symbols from native libraries (e.g. CoreCLR.dylib)
- [x] DWARF symbols from CrossGen, if available/possible

We then need to upload those to:

- [x] [SymWeb](http://symweb)
- [x] Msdl (automate)
- [x] Download Center

cc @lt72

**Comment by dleeapho** [comment]
Infra work tracked in:
https://github.com/dotnet/core-eng/issues/702
https://github.com/dotnet/core-eng/issues/701
https://github.com/dotnet/core-eng/issues/700
https://github.com/dotnet/core-eng/issues/699
https://github.com/dotnet/core-eng/issues/698

**Comment by karelz** [comment]
Let's use only 1 label to avoid double-counting and clarify responsibility - Infrastructure area per guidance from @lt72

**Comment by gkhanna79** [comment]
@dleeapho Is this Post-ZBB as well?

**Comment by dleeapho** [comment]
@gkhanna79  yes.

**Comment by karelz** [comment]
@dleeapho @lt72 this is still marked as 2.0.0. Can we close it as done, or do we need to keep (parts?) for 2.1?

**Comment by mikem8361** [comment]
Symbol indexing and uploading is now automated.
