### ISSUE TITLE
Marshal.GetExceptionPointers in .Net Core

### ISSUE THREAD

**Issue by pharring** [dotnet/coreclr#10874]
We would like to use System.Runtime.Interopservices.Marshal.GetExceptionPointers() in a .Net core library to capture exception information.

@gkhanna79 Could it be added to .Net Core?

**Comment by gkhanna79** [comment]
@terrajobst @weshaggard @yizhang82 Can you help with this?

**Comment by yizhang82** [comment]
@pharring Can you help us understand the scenario that you need this for your library?

**Comment by yizhang82** [comment]
@pharring Never mind. I saw the mail. Let's have the conversation there.

**Comment by yizhang82** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/11125

**Comment by pharring** [comment]
Thank you. @karolz-ms FYI
