### ISSUE TITLE
Optimize native code size of Dictionary methods

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#10883]
From https://github.com/dotnet/coreclr/pull/10203#discussion_r110810331

I have glanced over the native code generated for `Dictionary<int,int>.Remove`. The CSE for `entry[i]` kicks in some cases, but not others. If you cache `ref Entry entry = ref entries[i];` at the start of the loop and replace all 9 occurrences of `entries[i]` with it, the native code generated for this method should be approximately 20% smaller.

**Comment by omariom** [comment]
We can already use C# 7 in coreclr and corefx!?

**Comment by jkotas** [comment]
Yes, for a while already.

**Comment by mikedn** [comment]
You can assign to me

**Comment by jkotas** [comment]
@mikedn Thank you!
