### ISSUE TITLE
Tizen CI failed with cannot find corerun

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#10897]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_debug_tizen_prtest/946/console
```
12:20:01 + chmod a+x ./bin/CoreFxBinDir/corerun
12:20:01 chmod: cannot access ‘./bin/CoreFxBinDir/corerun’: No such file or directory
```

**Comment by danmosemsft** [comment]
Comes from https://github.com/dotnet/coreclr/pull/10886
@hseok-oh 
@BruceForstall @gkhanna79 is it reasonable to ignore tizen failures for corelib work?

**Comment by gkhanna79** [comment]
@hseok-oh @hqueue @jyoungyun Can you please look into this at the earliest as this is blocking clean CI?

@danmosemsft Yes, please ignore Tizen failures until this is resolved.

**Comment by danmosemsft** [comment]
Maybe we should have a procedure, that after any update netci.groovy, one must check the next PR someone queues (as ones own PR will not validate the change properly)

**Comment by hseok-oh** [comment]
It occurs because corefx build result for tizen doesn't have corerun. So we should not do 'chmod' for tizen.

**Comment by gkhanna79** [comment]
Thank you. Can you please look into getting a proper fix for this?


Thanks,
Gaurav
________________________________
