### ISSUE TITLE
Inconsistent behaviour when using static fields and IDisposable

### ISSUE THREAD

**Issue by surculus12** [dotnet/coreclr#10895]
The following does not seem to be intended or at least consistent behaviour. I have three examples that seem inconsistent with each other. I will paste the `Main()` methods, but the general code is as follows.

```
    public class Program
    {
        private static string _SomeString = string.Empty;
        private static ObjectThatDisposes _ObjectThatDisposes = new ObjectThatDisposes(_SomeString);

        public static void Main(string[] args)
        {
                /* My snippets from below go here */
        }
    }

    public class ObjectThatDisposes : IDisposable
    {
        private static int _Int;
        public ObjectThatDisposes(string someConfig)
        {
            _Int = 1;
        }

        public int GetInt()
        {
            return _Int;
        }

        public void Dispose()
        {
            _Int = 0;
        }
    }
```

If we call `_ObjectThatDisposes.GetInt()` first, it will return 1. If we follow that by a `using` on `ObjectThatDisposes`, then the next `_ObjectThatDisposes.GetInt()` will return 0. However, if `_ObjectThatDisposes.GetInt()` is not called before the `using`, it will return 1.

That is,
```
        public static void Main(string[] args)
        {
            int ret1 = _ObjectThatDisposes.GetInt();
            // ret1 == 1
            using (var disposing = new ObjectThatDisposes(null)) { }
            int ret2 = _ObjectThatDisposes.GetInt();
            // ret2 == 0
        }
```
and,
```
        public static void Main(string[] args)
        {
            using (var disposing = new ObjectThatDisposes(null)) { }
            int ret1 = _ObjectThatDisposes.GetInt();
            // ret1 == 1
        }
```
But if we pass the same parameter to the `using` instance of `ObjectThatDisposes` as we did to our static instance, the latter is also disposed.
```
        public static void Main(string[] args)
        {
            using (var disposing = new ObjectThatDisposes(_SomeString)) { }
            int ret1 = _ObjectThatDisposes.GetInt();
            // ret1 == 0
        }
```

**Comment by mikedn** [comment]
In your second example ret1 should be 0, not 1. And in my tests it is 0 as expected.

What version of .NET are you using?

**Comment by surculus12** [comment]
It should be 1.1.1, but this might be a local issue for me then.

I'll run this on a 1.1.1 Docker instance to verify that this is no longer an issue.

**Comment by mikedn** [comment]
> It should be 1.1.1, but this might be a local issue for me then.

Thanks for the info, see my updated post.

**Comment by surculus12** [comment]
I have verified that this is happening using the [latest .net version](https://github.com/dotnet/dotnet-docker/blob/master/1.1/debian/sdk/Dockerfile) inside a Docker container.

From your edit I gather that this is due to some form of optimization?: Don't initialize the static fields until you need to.

**Comment by mikedn** [comment]
Yes, it's a form of optimization that the CLR offers and that the C# language takes advantage of.

C# spec 10.5.5.1 Static field initialization:

> If a static constructor (§‎10.12) exists in the class, execution of the static field initializers occurs immediately prior to executing that static constructor. Otherwise, the static field initializers **are executed at an implementation-dependent time prior to the first use of a static field of that class**.

Note how this is different from the way static constructors are run:

C# spec 10.2 Static constructors:
> The static constructor for a closed class type executes at most once in a given application domain. The execution of a static constructor is triggered by the first of the following events to occur within an application domain:
> * An instance of the class type is created.
> * Any of the static members of the class type are referenced. 

So if you really need that code to behave in a consistent manner you could add a static constructor and move the initialization of `_ObjectThatDisposes` to it. Though you should avoid depending on the this ordering, it's too much of a gotcha...

**Comment by surculus12** [comment]
Nah, the field I found this behaviour through shouldn't have been static to begin with, so this is a non-issue for me.

Since this is defined behaviour (although, indeed, very much gotcha), I'll close the issue.

Thanks for the explanation!
