### ISSUE TITLE
Build with VS 2017 only doesn't work

### ISSUE THREAD

**Issue by fujiy** [dotnet/coreclr#10890]
I followed the instructions mentioned here: https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md for Visual Studio 2017.

I don't have VS 2015.

When calling build from Developer Command Prompt  for VS 2017 I receive this error:

```
Running: C:\Users\myuser\Source\coreclr\Tools\dotnetcli\dotnet.exe C:\Users\myuser\Source\coreclr\Tools\run.exe C:\Users\myuser\Source\coreclr\config.json build -Project=C:\Users\myuser\Source\coreclr\build.proj -generateHeaderWindows -NativeVersionHeaderFile="C:\Users\myuser\Source\coreclr\bin\obj\_version.h" -BuildOS=Windows_NT -BuildType=Debug -BuildArch=x64
Running: C:\Users\myuser\Source\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /l:BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  C:\Users\myuser\Source\coreclr\build.proj /p:__BuildType=Debug /p:__BuildArch=x64 /p:__BuildOS=Windows_NT  /t:GenerateVersionHeader /p:GenerateVersionHeader=true /p:NativeVersionHeaderFile=C:\Users\myuser\Source\coreclr\bin\obj\_version.h
MSBUILD : error MSB1021: Cannot create an instance of the logger. Could not load file or assembly 'Tools\/net46\/Microsoft.DotNet.Build.Tasks.dll' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
Switch: BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log
Command execution failed with exit code 1.
BUILD: Restoring the OptimizationData Package
Tools are already initialized.
Running: C:\Users\myuser\Source\coreclr\Tools\dotnetcli\dotnet.exe C:\Users\myuser\Source\coreclr\Tools\run.exe C:\Users\myuser\Source\coreclr\config.json sync -optdata
Running: C:\Users\myuser\Source\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /flp:v=detailed;LogFile=sync.log /t:RestoreOptData /p:RestoreDuringBuild=true  ./build.proj
MSBUILD : error MSB1009: Project file does not exist.
Switch: ./build.proj
Command execution failed with exit code 1.
BUILD: Error: Failed to restore the optimization data package.
```

**Comment by danmosemsft** [comment]
Can you try "clean -all" from the root, then try again?

**Comment by Pothulapati** [comment]
@danmosemsft  Iam getting the exact same error when I try to Build. I also tried `clean -all` before doing `build` but I get the same error .

**Comment by danmosemsft** [comment]
does this file exist? <corefx>\Tools/net46/Microsoft.DotNet.Build.Tasks.dll

**Comment by fujiy** [comment]
I am without computer access. It happened even after a Windows clean installation (Creators update).

**Comment by Pothulapati** [comment]
@danmosemsft Yes,The File exists but I get the same error

**Comment by Pothulapati** [comment]
@danmosemsft I also tried building the repo on an Azure VM but It's showing the same error.I think this issue needs some attention.

**Comment by jnm2** [comment]
I'm having this issue also. From VS2017 developer command prompt:

```
C:\Users\jmusser\Source\Repos\coreclr>build
Starting Build at 21:36:58.97
BUILD: Commencing CoreCLR Repo build
BUILD: Checking prerequisites
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\\VsDevCmd.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26403.7
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
Installing dotnet cli...
Restoring BuildTools version 1.0.27-prerelease-01413-01...
Initializing BuildTools ...
Updating CLI NuGet Frameworks map...
Done initializing tools.
Running: C:\Users\jmusser\Source\Repos\coreclr\Tools\dotnetcli\dotnet.exe C:\Users\jmusser\Source\Repos\coreclr\Tools\run.exe C:\Users\jmusser\Source\Repos\coreclr\config.json build -Project=C:\Users\jmusser\Source\Repos\coreclr\build.proj -generateHeaderWindows -NativeVersionHeaderFile="C:\Users\jmusser\Source\Repos\coreclr\bin\obj\_version.h" -BuildOS=Windows_NT -BuildType=Debug -BuildArch=x64
Running: C:\Users\jmusser\Source\Repos\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /l:BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  C:\Users\jmusser\Source\Repos\coreclr\build.proj /p:__BuildType=Debug /p:__BuildArch=x64 /p:__BuildOS=Windows_NT  /t:GenerateVersionHeader /p:GenerateVersionHeader=true /p:NativeVersionHeaderFile=C:\Users\jmusser\Source\Repos\coreclr\bin\obj\_version.h
MSBUILD : error MSB1021: Cannot create an instance of the logger. Could not load file or assembly 'Tools\/net46\/Microsoft.DotNet.Build.Tasks.dll' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
Switch: BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log
Command execution failed with exit code 1.
```

https://github.com/dotnet/coreclr/issues/10181 looks related.

**Comment by jnm2** [comment]
Whereas with the VS2015 developer command prompt I get:

```
C:\Users\jmusser\Source\Repos\coreclr>build
Starting Build at 21:42:58.26
BUILD: Commencing CoreCLR Repo build
BUILD: Checking prerequisites
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\VsDevCmd.bat"
Tools are already initialized.
Running: C:\Users\jmusser\Source\Repos\coreclr\Tools\dotnetcli\dotnet.exe C:\Users\jmusser\Source\Repos\coreclr\Tools\run.exe C:\Users\jmusser\Source\Repos\coreclr\config.json build -Project=C:\Users\jmusser\Source\Repos\coreclr\build.proj -generateHeaderWindows -NativeVersionHeaderFile="C:\Users\jmusser\Source\Repos\coreclr\bin\obj\_version.h" -BuildOS=Windows_NT -BuildType=Debug -BuildArch=x64
Running: C:\Users\jmusser\Source\Repos\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /l:BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  C:\Users\jmusser\Source\Repos\coreclr\build.proj /p:__BuildType=Debug /p:__BuildArch=x64 /p:__BuildOS=Windows_NT  /t:GenerateVersionHeader /p:GenerateVersionHeader=true /p:NativeVersionHeaderFile=C:\Users\jmusser\Source\Repos\coreclr\bin\obj\_version.h
Command execution succeeded.
```

**Comment by fujiy** [comment]
Here is the log from the brand new Windows install:

```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26403.7
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Users\felip\Source>cd C:\Users\felip\Source\coreclr

C:\Users\felip\Source\coreclr>build skiptests
Starting Build at 23:24:09.54
BUILD: Commencing CoreCLR Repo build
BUILD: Checking prerequisites
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\\VsDevCmd.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26403.7
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
Installing dotnet cli...
Restoring BuildTools version 1.0.27-prerelease-01413-01...
Initializing BuildTools ...
Updating CLI NuGet Frameworks map...
Done initializing tools.
Running: C:\Users\felip\Source\coreclr\Tools\dotnetcli\dotnet.exe C:\Users\felip\Source\coreclr\Tools\run.exe C:\Users\felip\Source\coreclr\config.json build -Project=C:\Users\felip\Source\coreclr\build.proj -generateHeaderWindows -NativeVersionHeaderFile="C:\Users\felip\Source\coreclr\bin\obj\_version.h" -BuildOS=Windows_NT -BuildType=Debug -BuildArch=x64
Running: C:\Users\felip\Source\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /l:BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  C:\Users\felip\Source\coreclr\build.proj /p:__BuildType=Debug /p:__BuildArch=x64 /p:__BuildOS=Windows_NT  /t:GenerateVersionHeader /p:GenerateVersionHeader=true /p:NativeVersionHeaderFile=C:\Users\felip\Source\coreclr\bin\obj\_version.h
MSBUILD : error MSB1021: Cannot create an instance of the logger. Could not load file or assembly 'Tools\/net46\/Microsoft.DotNet.Build.Tasks.dll' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
Switch: BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log
Command execution failed with exit code 1.
BUILD: Restoring the OptimizationData Package
Tools are already initialized.
Running: C:\Users\felip\Source\coreclr\Tools\dotnetcli\dotnet.exe C:\Users\felip\Source\coreclr\Tools\run.exe C:\Users\felip\Source\coreclr\config.json sync -optdata
Running: C:\Users\felip\Source\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /flp:v=detailed;LogFile=sync.log /t:RestoreOptData /p:RestoreDuringBuild=true  ./build.proj
MSBUILD : error MSB1009: Project file does not exist.
Switch: ./build.proj
Command execution failed with exit code 1.
BUILD: Error: Failed to restore the optimization data package.
```

**Comment by ahsonkhan** [comment]
@gkhanna79, should we prioritize this issue?

**Comment by gkhanna79** [comment]
@tannergooding Can you PTAL?

**Comment by tannergooding** [comment]
In both cases, the only difference I see in the output given and the output I produce is that my build is additionally passing in: `/p:RestoreDefaultOptimizationDataPackage=false /p:UsePartialNGENOptimization=false`

However, the error logs they have both have the following path: `Tools\/net46\/Microsoft.DotNet.Build.Tasks.dll`. I would expect that the combination of slashes (`\/`) as the directory separators is having some negative impact here....

My Output:
```
Starting Build at  8:38:10.25
BUILD: Commencing CoreCLR Repo build
BUILD: Checking prerequisites
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\\VsDevCmd.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26403.7
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
Installing dotnet cli...
Restoring BuildTools version 1.0.27-prerelease-01413-01...
Initializing BuildTools ...
Updating CLI NuGet Frameworks map...
Done initializing tools.
Running: D:\Workspaces\coreclr\Tools\dotnetcli\dotnet.exe D:\Workspaces\coreclr\Tools\run.exe D:\Workspaces\coreclr\config.json build -Project=D:\Workspaces\coreclr\build.proj -generateHeaderWindows -NativeVersionHeaderFile="D:\Workspaces\coreclr\bin\obj\_version.h" -BuildOS=Windows_NT -BuildType=Debug -BuildArch=x64
Running: D:\Workspaces\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /l:BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  D:\Workspaces\coreclr\build.proj /p:__BuildType=Debug /p:__BuildArch=x64 /p:__BuildOS=Windows_NT  /t:GenerateVersionHeader /p:GenerateVersionHeader=true /p:NativeVersionHeaderFile=D:\Workspaces\coreclr\bin\obj\_version.h /p:RestoreDefaultOptimizationDataPackage=false /p:UsePartialNGENOptimization=false

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.48
Command execution succeeded.
BUILD: Restoring the OptimizationData Package
Tools are already initialized.
Running: D:\Workspaces\coreclr\Tools\dotnetcli\dotnet.exe D:\Workspaces\coreclr\Tools\run.exe D:\Workspaces\coreclr\config.json sync -optdata
Running: D:\Workspaces\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /flp:v=detailed;LogFile=sync.log /t:RestoreOptData /p:RestoreDuringBuild=true  ./build.proj

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.09
Command execution succeeded.
BUILD: Commencing build of native components for Windows_NT.x64.Debug
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\\..\..\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
...
```

**Comment by fujiy** [comment]
@tannergooding have you installed VS2015 in that computer?

**Comment by jnm2** [comment]
I have the exact same problem running the build from the VS2017 prompt on a brand new Windows install without VS2015 that I did on a machine with VS2015.

**Comment by tannergooding** [comment]
@fujiy, I valided on machines with the following configurations:
* VS2012 + VS2013 + VS2015 + VS2017
* VS2013 + VS2015 + VS2017
* VS2015 + VS2017
* VS2017

**Comment by jnm2** [comment]
@tannergooding This is frustrating. I'm loathe to install VS2015 on my new builds of Windows, so I have to remote to the machine that has it in order to build coreclr. What can we do to facilitate a fix to allow building from the VS2017 prompt?

**Comment by gkhanna79** [comment]
@tannergooding Didn't you confirm that repo built clean from within VS 2017 prompt?

**Comment by tannergooding** [comment]
@jnm2, that's the thing. I can successfully build on VS2017 standalone (Community, Professional, or Enterprise) without any issues (both from clean machines and from existing machines with other VS instances). So I am unsure what is blocking your machine from doing the same.

The only difference I've seen in the logs is that your path is somehow resolving to have `\/` instead of just `/` ( you have `Tools\/net46\/Microsoft.DotNet.Build.Tasks.dll`, while I end up with `Tools/net46/Microsoft.DotNet.Build.Tasks.dll`).

This is the command that is failing for you:
`C:\Users\jmusser\Source\Repos\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /l:BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  C:\Users\jmusser\Source\Repos\coreclr\build.proj /p:__BuildType=Debug /p:__BuildArch=x64 /p:__BuildOS=Windows_NT  /t:GenerateVersionHeader /p:GenerateVersionHeader=true /p:NativeVersionHeaderFile=C:\Users\jmusser\Source\Repos\coreclr\bin\obj\_version.h`

and given the failure, my best guess would be to just "correct" the path for the /l:BinClashLogger arg and see if that resolves the issue (so run `C:\Users\jmusser\Source\Repos\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /l:BinClashLogger,Tools\net46\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  C:\Users\jmusser\Source\Repos\coreclr\build.proj /p:__BuildType=Debug /p:__BuildArch=x64 /p:__BuildOS=Windows_NT  /t:GenerateVersionHeader /p:GenerateVersionHeader=true /p:NativeVersionHeaderFile=C:\Users\jmusser\Source\Repos\coreclr\bin\obj\_version.h`

Outside of that, I don't think I'll be able to get much further without diagnostic MSBuild logs.

**Comment by jnm2** [comment]
@tannergooding Running the failing command gives the original error. Running the command you corrected gives:

```
MSBUILD : error MSB1021: Cannot create an instance of the logger. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
Switch: BinClashLogger,Tools\net46\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log
```

Guess I'll post a diagnostic log next.

**Comment by jnm2** [comment]
@tannergooding Adding `/v:diag` to either command has no effect on the output. <code>C:\Users\jmusser\Source\Repos\coreclr\Tools\msbuild.cmd **/v:diag** /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net46\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log C:\Users\jmusser\Source\Repos\coreclr\build.proj /p:__BuildType=Debug /p:__BuildArch=x64 /p:__BuildOS=Windows_NT /t:GenerateVersionHeader /p:GenerateVersionHeader=true /p:NativeVersionHeaderFile=C:\Users\jmusser\Source\Repos\coreclr\bin\obj\_version.h</code>

**Comment by tannergooding** [comment]
@jnm2, are you running commands from the repository root (looks like `C:\Users\jmusser\Source\Repos\coreclr` in your case)?

I'm actually wondering if this is a similar issue to `https://github.com/dotnet/corefx/pull/18700`, commands would fail if the repository root was not your working directory.

**Comment by jnm2** [comment]
@tannergooding Um duh, didn't spot the other arg.

**Comment by jnm2** [comment]
@tannergooding I have been, but for that command I cd'd to \Tools. I'll try from the root.

**Comment by jnm2** [comment]
@tannergooding I have been, but for that command I cd'd to \Tools. I'll try from the root.

Ah, the corrected command succeeded from the root.

**Comment by jnm2** [comment]
@tannergooding Both commands succeed when the working directory is the repo root. However, I have never run `/build.cmd` itself except from the repo root. https://github.com/dotnet/corefx/pull/18700 looks likely.

**Comment by tannergooding** [comment]
Awesome.

@gkhanna79, It looks like there are two parts to a fix here:
1. CoreCLR needs a fix similar to https://github.com/dotnet/corefx/pull/18700 so that users can build from any working directory
2. Whatever parses the `config.json` should probably attempt to fully resolve the path and do so with regards to the repository root (this would result in full paths being passed in everywhere)

**Comment by fujiy** [comment]
Now I can build CoreFX.

I'm not sure why, since I always built from the repository directory. Is VS Developer CMD changing the working directory?

**Comment by jnm2** [comment]
@fujiy I think because dotnet/corefx#18700 was merged four days ago?

**Comment by fujiy** [comment]
Yes, as @tannergooding said, we need a similar fix for CoreClr.

What doesn't make sense yet is that I was building from repository directory, It seems that VS 2017 Developer CMD is changing the working directory

**Comment by fujiy** [comment]
I'm doing some tests and will try to send a fix
