### ISSUE TITLE
palinternal.h breaks "errno": src/pal/src/include/pal/thread.hpp:498:13: error: use of undeclared identifier 'errno'

### ISSUE THREAD

**Issue by saper** [dotnet/coreclr#1091]
I was [unable to compile CoreCLR on FreeBSD](https://github.com/dotnet/coreclr/issues/1044#issuecomment-107916239), due to `errno` being apparently undefined at the point where it's needed in `src/pal/src/include/thread.hpp`. ([full log](https://gist.github.com/saper/eafc21d80b753511270d)).

The problem might have been uncovered (but not caused) by f1b2b7d934339b0def5a96f111ea954974156ff8, which (re)introduced the use of system `errno` instead of using some own implementation.

The problem is that `palinternal.h` is a clever trick that does not handle some system headers fully.
It is worth to read https://github.com/dotnet/coreclr/blob/master/src/pal/src/include/pal/palinternal.h#L14-L136 before proceeding :)

What happens is this:

- `src/exception/seh.cpp` includes `<typeinfo>` and then `"pal/thread.hpp"`
- on my system `<typeinfo>` includes `<errno.h>`
- `<palinternal.h>` does its funny tricks and together with `<pal.h>` try to redefine `errno`. 
- What happens in the end is that `errno` stays undefined once the `corunix.hpp` is processed.
- Subsequent `#include <errno.h>` in the `thread.hpp` DOES NOT help, because `<errno.h>` was already included and the header guard (in my case `_SYS_ERRNO_H_`) is already defined
- This way we never get original system macro definition of `errno` back.
- This problem does not occur in the other files because at the point `palinternal.h` gets used `<errno.h>` has not yet been included by any other file.

So there needs to be a warning in the 'palinternal.h' file that explains the problem - 
using header files of the undef'd identifiers is probably a no-no.

When moving some function from category `A.2` (as described in `palinternal.h`) to category `A.1` 
it needs to be carefully checked if everything gets defined again.

Not sure where the bug is, maybe `#undef errno` and friends should go away, maybe `errno` should not be redefined in `pal.h`... etc. etc.

Anyway, my workaround was to include `<typeinfo>` *after* `"pal/thread.hpp"` in the `seh.cpp`
and the CoreCLR got compiled; but that is certainly not a solution.

This problem is not very FreeBSD specific, any use of some system header before `palinternal.h` gets included may create such problems, or worse, hidden bugs.

(mentioning https://github.com/dotnet/coreclr/issues/1010)

Thanks @josteink @jasonwilliams200OK for assisting me to get this sorted out.

**Comment by saper** [comment]
There reason why it didn't break earlier FreeBSD builds is that `<errno.h>` gets included via various C++ headers after [r278724](https://svnweb.freebsd.org/base/stable/10/contrib/libc%2B%2B/include/__config?r1=262801&r2=278724) in FreeBSD 10.

**Comment by josteink** [comment]
Great job, @saper. Not sure I deserve much honour in uncovering this issue, as I honestly think you did pretty much all the work, but with that said...

CC: @janvorli @stephentoub Do you guys have any opinion on this issue? What would be your preferred fix?

**Comment by jasonwilliams200OK** [comment]
I don't know how much is #1085 relevant to this. Usually C libs when compiled on FreeBSD require some additional inclusions.
@fieryorc, @mikem8361, any ideas on this and will you be addition more commits to #1085 or is it already set for merge?

**Comment by fieryorc** [comment]
The changes I'm making in #1085 are specific to another project to enable us to compile PAL headers along with std c++11 headers. My changes won't affect this in any way. coreclr code will remain as is and won't be impacted by #1085.

**Comment by jasonwilliams200OK** [comment]
@mmitche, with the VM recipe for CoreCLR (https://gist.github.com/jasonwilliams200OK/06db121ec534821fe541), I am able to successfully build locally on FreeBSD 10.2 by applying @saper's [patch](https://github.com/saper/coreclr/commit/9deed7c6b8b85de418362c258b59d5d6fa56046f):

```diff
diff --git a/src/pal/src/exception/seh.cpp b/src/pal/src/exception/seh.cpp
index 3080814..812d909 100644
--- a/src/pal/src/exception/seh.cpp
+++ b/src/pal/src/exception/seh.cpp
@@ -19,8 +19,8 @@ Abstract:

 --*/

-#include <typeinfo>
 #include "pal/thread.hpp"
+#include <typeinfo>
 #include "signal.hpp"
 #include "pal/handleapi.hpp"
 #include "pal/seh.hpp"
```

I wonder how it is building on CI, if CI is running FreeBSD 10.[0-2] and mono 4.0.3? Because locally without applying this patch and `setenv TZ UTC ; setenv MONO_THREADS_PER_CPU 50` before `./build.sh` it does not succeed with current CoreCLR master.

Should we fix this issue with the said patch?

/cc: @jkotas

**Comment by mmitche** [comment]
We build with skipmscorlib, so mono would not be involved.

Sent from my Windows Phone
________________________________

**Comment by jasonwilliams200OK** [comment]
You are right! I missed that one and will try with `skipmscorlib`. 
Nonetheless the code patch is still required to compile the code. :)

**Comment by mmitche** [comment]
I'll try and find out why its working in CI tomorrow.

Sent from my Windows Phone
________________________________

**Comment by jasonwilliams200OK** [comment]
Thanks! I have updated the guide for both with and without `skipmscorlib`.

**Comment by josteink** [comment]
What? Isn't this thing submitted and fixed already? I thought this issue was dead months ago.

I may have forgotten some context, but are there any portability issues with the proposed fix on Linux or OSX? Is there any technical reason this patch is not proposed as a PR already?

**Comment by saper** [comment]
The problem `<typeinfo>` has not been duly fixed, I just figured out this one-line fix works around the problem. To me this is an indication of more serious problems with PAL architecture, as indicated in the bug description in https://github.com/dotnet/coreclr/issues/1091.

As this is definitely out of scope for casual drive-by-development I am okay to work on this but not under the present contractual conditions. I am available for other options if anybody is interested in pushing this further (just drop me a line at saper@saper.info). This work should optimally be done in consultation with people who designed PAL (does not need to be a coordinated effort, though).

**Comment by josteink** [comment]
You are absolutely right that the proposed patch is a workaround to a problem which we ideally shouldn't be having. I do agree about that. But something being a workaround does not exclude it being a valid option worthy of consideration.

While I agree there seems to be some structural issues with the PAL-layer, I must honestly question the viability of a PAL redesign at this point.

Microsoft has said they are going to use CoreCLR in their commercial offerings (as in .NET delivered with Windows, and maybe Azure?). And for that to realistically happen, compatibility & stability needs to be rock-solid with existing implementations out there.

In that regard redesigning the PAL layer seems a bit risky, and even if somebody did all the hard work of redesigning it, implemented the new design and showed that it still worked, I'm assuming the gains would need to be many and obvious for such a patch to be accepted.

I doubt fixing one compiler error on FreeBSD (a currently unsupported platform) and preventing possible future regressions is going to be a solid enough argument for landing a patch that size.

Right now I think having a broken build for almost half a year is a more pressing issue than architectural objections to an existing code-base.

I really think you should submit the workaround as a PR, as you did all the hard work here and deserves credit for it, but if you are unwilling to do so, I may proceed to do so myself.

**Comment by saper** [comment]
All agreed. I think that this workaround is acceptable as it shouldn't break anything else that is not already broken. I think I haven't made myself clear: I do not agree to the terms laid out by the default CLA.

**Comment by jasonwilliams200OK** [comment]
Regarding the CLA signing requirement (clicking a button basically that you will not claim money for your work), for a small change like this won't be required. There is some kind of threshold for CLA signing.

**Comment by josteink** [comment]
Unless you patch exceeds a certain size, you will not be required to sign the CLA.

You can see this in the PR list:

https://github.com/dotnet/coreclr/pulls?q=is%3Aopen+is%3Apr+label%3Acla-not-required

**Comment by janvorli** [comment]
I've just tried to remove the `#include <typeinfo>` and it builds ok on both Linux and OSX, so it looks like some kind of historical dependency that is not needed anymore. Is it needed on FreeBSD? If not, we can just remove it.

**Comment by josteink** [comment]
Unless I remember incorrectly, I think `#include <typeinfo>` is needed for `errno`.

**Comment by saper** [comment]
On Thu, 8 Oct 2015, Jostein Kjønigsen wrote:

> Unless I remember incorrectly, I think `#include <typeinfo>` is needed for `errno`.

That could be needed for RTTI (are we using it?), but otherwise I think
PAL already knows what to include to get errno (<errno.h> in case of FreeBSD).

**Comment by josteink** [comment]
Fair enough. That's much more targeted and does sound better. I'll take your word for it :)

**Comment by saper** [comment]
I'd just try deleting `<typeinfo>` as @janvorli suggests but I have currently no access to my CoreCLR copy to test. #1085 did introduce some compatibility with C++11 but I don't see any rtti-related stuff there either.

But it's definitely worth checking with @fieryorc ("we are using C++11") and the "debugger team" to find out how things work there (or any other external PAL consumers).

**Comment by janvorli** [comment]
We include errno.h few lines below the `typeinfo` in the seh.cpp and we don't use RTTI in PAL.
In fact, not even the errno.h is needed anymore in the seh.cpp. PAL has a lot of history behind it and I think that some code was removed long ago that needed this stuff but the includes were just left in.

**Comment by saper** [comment]
Fast forward to 2017, I am getting this trying to build f1939c90aed599c107b44ef26b5db5b417860ed4 on FreeBSD 10.3:

````
[  0%] Building CXX object src/pal/src/CMakeFiles/tracepointprovider.dir/misc/tracepointprovider.cpp.o
[  0%] Building CXX object src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native_Static.dir/locale.cpp.o
[  0%] Building CXX object src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/locale.cpp.o
In file included from /home/saper/sw/coreclr/src/pal/src/misc/tracepointprovider.cpp:19:
In file included from /home/saper/sw/coreclr/src/pal/src/include/pal/palinternal.h:333:
/home/saper/sw/coreclr/src/pal/inc/pal.h:5400:9: error: 'errno' macro redefined [-Werror,-Wmacro-redefined]
#define errno  (*PAL_errno(PAL_get_caller))
        ^
/usr/include/errno.h:46:9: note: previous definition is here
#define errno           (* __error())
        ^
In file included from /home/saper/sw/coreclr/src/pal/src/misc/tracepointprovider.cpp:20:
In file included from /home/saper/sw/coreclr/src/pal/src/include/pal/dbgmsg.h:160:
/home/saper/sw/coreclr/src/pal/src/include/pal/thread.hpp:485:13: error: use of undeclared identifier 'errno'
            errno = dwLastError;
            ^
/home/saper/sw/coreclr/src/pal/src/include/pal/thread.hpp:494:20: error: use of undeclared identifier 'errno'
            return errno;
                   ^
3 errors generated.
--- src/pal/src/CMakeFiles/tracepointprovider.dir/misc/tracepointprovider.cpp.o ---
*** [src/pal/src/CMakeFiles/tracepointprovider.dir/misc/tracepointprovider.cpp.o] Error code 1

make[2]: stopped in /home/saper/sw/coreclr/bin/obj/FreeBSD.x64.Debug
1 error

make[2]: stopped in /home/saper/sw/coreclr/bin/obj/FreeBSD.x64.Debug
--- src/pal/src/CMakeFiles/tracepointprovider.dir/all ---
*** [src/pal/src/CMakeFiles/tracepointprovider.dir/all] Error code 2
````

**Comment by jkotas** [comment]
cc @wfurt
