### ISSUE TITLE
CoreCLR failed with error c4596 when build in conformance mode (/permissive-)

### ISSUE THREAD

**Issue by PhoebeHui** [dotnet/coreclr#10915]
I build CoreCLR with Visual studio 2017 RTW in conformance mode (/permissive-) on Windows, it failed with error C4596, The changes involved by 
https://github.com/dotnet/coreclr/commit/a387696646a1aa7413c2082a430845844e496313
This issue on https://github.com/dotnet/coreclr/blob/master/src/vm/sampleprofiler.h#L27

Could you help remove the redundant "SampleProfiler::" on ThreadProc. The compiler complains about this in conformance mode (/permissive-)

Failures:
d:\coreclr\src\src\vm\sampleprofiler.h(27): error C4596: 'ThreadProc': illegal qualified name in member declaration

**Comment by jkotas** [comment]
@PhoebeHui Would you like to submit a PR with the fix?

**Comment by jkotas** [comment]
Fixed by #11269
