### ISSUE TITLE
AppDomain.CurrentDomain.BaseDirectory does not end with a slash on Core

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/coreclr#10920]
`AppDomain.CurrentDomain.BaseDirectory` does not contain a slash at the end. Failing test in corefx with targetgroup **netfx** here: https://github.com/dotnet/corefx/issues/18196

console output netfx:
`C:\Users\vikto\Documents\src\corefx\bin\AnyOS.AnyCPU.Debug\System.Configuration.ConfigurationManager.Tests\netstandard\`

console output (preview-2 bits) core:
`C:\Users\vikto\Documents\src\corefx\bin\AnyOS.AnyCPU.Debug\System.Configuration.ConfigurationManager.Tests\netstandard`

`msbuild src/System.Configuration.ConfigurationManager/tests /t:BuildAndTest /p:targetgroup=netfx /p:xunitoptions="-method System.ConfigurationTests.UrlPathTests.GetDirectoryOrRootName_GettingDirectoryFromAFilePath"`

**Comment by danmosemsft** [comment]
@gkhanna79 where would the fix be, on the managed side or native (fusion side)?

**Comment by gkhanna79** [comment]
There is no fusion in CoreCLR. Depending upon how the API is plumbed, it could be in either managed or native.

**Comment by AlexGhiondea** [comment]
@gkhanna79 I thought that the host sets this value -- is that true?

**Comment by gkhanna79** [comment]
Feel free to move to Core-Setup and assign to @ramarag if you think the bug is there and not in AD setup code.

**Comment by AlexGhiondea** [comment]
I was going off this other comment on a similar issue: https://github.com/dotnet/coreclr/issues/2128#issuecomment-171830617

**Comment by ViktorHofer** [comment]
I'm not sure if the bug is in coreclr or in core-setup. I hoped you could answer that :)

**Comment by gkhanna79** [comment]
I have a basic question - which is the correct behavior? Desktop or CoreCLR? https://msdn.microsoft.com/en-us/library/system.appdomain.basedirectory(v=vs.110).aspx does not describe the expected behavior.

**Comment by ViktorHofer** [comment]
I think the answer is definitely Desktop because our customers are relying on that behavior since ages...

**Comment by danmosemsft** [comment]
@ViktorHofer could you please attempt to figure out wher ethis bug should go? I agree it is a breaking change we care about. I would like to get it on the right person/repo.

**Comment by ViktorHofer** [comment]
@danmosemsft I will talk to @gkhanna79 and make sure to move the issue to the corresponding team. My bet is - @tarekgh mentioned that too - that the value gets set by the host.

**Comment by gkhanna79** [comment]
@ramarag Can you PTAL if this is an issue in the host? If not, please send this to @AlexGhiondea

**Comment by ViktorHofer** [comment]
ping @ramarag

**Comment by ramarag** [comment]
This is a host issue, the logic which returns this value is actually at
https://github.com/dotnet/coreclr/blob/cdff8b0babe5d82737058ccdae8b14d8ae90160d/src/mscorlib/src/System/AppContext/AppContext.cs#L38

**Comment by ramarag** [comment]
Issue moved to [dotnet/core-setup #2176](https://github.com/dotnet/core-setup/issues/2176) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gkhanna79** [comment]
@danmosemsft Should this be moved to @ViktorHofer?

**Comment by ViktorHofer** [comment]
So the reason why the test is behaving differently is because xunit trims the trailing slash here: https://github.com/xunit/xunit/blob/914e97d57e388b5c8c2bf5c4381b5c232ed64b5a/src/xunit.runner.utility/AppDomain/AppDomainManager_AppDomain.cs#L40 (thanks @akoeplinger for the link)

I notified the owners but they are not willing to change it. NUnit had the same issue and they did change it (https://github.com/nunit/nunit-console/commit/f4080df5f9f39049c496d60bde84798fdd811cd7). cc @danmosemsft @karelz 

That means that AppDomain.BaseDirectory tests should use a Path.Combine routine for concatenating strings or not depending that there is a slash at the end (because testing with different TargetGroups has different behaviors).

That was about why the test is behaving differently on xunit. **The other part and reason why this issue is still open is, the AppDomain.BaseDirectory does not end with a slash on netcoreapp**. (repo: console application with .NET Core SDK preview-2 bits --> `Console.WriteLine(AppDomain.CurrentDomain.BaseDirectory);`)

**Comment by ViktorHofer** [comment]
Found it. DirectorySeperator gets removed here: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/AppDomainSetup.cs#L170

@danmosemsft @stephentoub Any idea why the DirectorySeperator char gets removed here?

**Comment by ViktorHofer** [comment]
@jkotas Where does `AppDomain.Setup` get called and does args[8] (basepath) contain a slash at the end? https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/AppDomain.cs#L966

**Comment by jkotas** [comment]
> Where does `private static Object Setup(Object arg)` in AppDomain.cs get called 

It is called from the unmanaged side of the runtime: https://github.com/dotnet/coreclr/blob/69d43a0f8cfe095336b286e7bb892fe49c702e30/src/vm/appdomain.cpp#L4726

> does arg[8] (basepath) ends with a slash? 

The key/value pairs are passed in by the CoreCLR host. So with the default shipping dotnet host, it is what gets computed in https://github.com/dotnet/core-setup/blob/2f3a31f0e475dc2fb91012fcaa0c082f6e74fe8a/src/corehost/cli/hostpolicy.cpp#L90. It ends with slash from what I can tell.

If the host does not pass one in, the default value is computed here https://github.com/dotnet/coreclr/blob/25169926291fcdcad25506c558690a0f63e61a93/src/mscorlib/src/System/AppDomainSetup.cs#L175 . It ends with slash from what I can tell.

> The other part and reason why this issue is still open is, the AppDomain.BaseDirectory does not end with a slash on netcoreapp

It does end with a slash for me with the latest bits. If it does not for you, post exact repro steps.

**Comment by ViktorHofer** [comment]
Talked with @jkotas offline. It seems the bad commit in dotnet/core-setup is still in. Waiting for new version and testing again in a few days.
