### ISSUE TITLE
question on building dotnetcore application but namespace error

### ISSUE THREAD

**Issue by skao21** [dotnet/coreclr#1093]
Hi 

I follow the https://github.com/dotnet/coreclr/blob/master/Documentation/linux-instructions.md to build my first C# Helloworld application. I am able to run the application in my ubuntu box.

Then I was trying to run a more complicate code to see if I can build tcp socket appliaction.

First, I create a simple c# file with only namespace included in the source code. I am able to build it on linux monodevelop ide.
But when I tried to follow the holloworld instruction to build the same c# file, it can not be built, I believe monodevelop also use mcs to build the project. So, i do not understand why the dotnetcore does not resolve the namespace as mondevelop does.

I came from linux background without much knowledge on .NET.

Thanks
kevin

Here is my c# file:  test.cs
test.cs
----------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Net;
using System.Net.Sockets;

namespace ClientServer
{
    

    public class ClientServer
    {
        public static void Main()
        {
        }
    }
}
---------------------------------

And here is the build error when compile from linux
----------------------------------------------
https://github.com/dotnet/coreclr/blob/master/Documentation/linux-instructions.md

ubuntu-1:~/coreclr-demo/runtime$ mcs -nostdlib -noconfig /r:../packages/System.Console.4.0.0-beta-22703/lib/contract/System.Console.dll /r:../packages/System.Runtime.4.0.20-beta-22703/lib/contract/System.Runtime.dll   ClientServer.cs
ClientServer.cs(4,14): error CS0234: The type or namespace name `Linq' does not exist in the namespace `System'. Are you missing `System.Core' assembly reference?
ClientServer.cs(6,14): error CS0234: The type or namespace name `Net' does not exist in the namespace `System'. Are you missing an assembly reference?
ClientServer.cs(7,14): error CS0234: The type or namespace name `Net' does not exist in the namespace `System'. Are you missing an assembly reference?
Compilation failed: 3 error(s), 0 warnings

NOYE: I also follow the same steps on WINDOW version and get the "same" namespace  errors on the test.cs using "csc".

**Comment by shahid-pk** [comment]
you need to do the same for System.Linq what you did for System.Console following that hello world demo when you copied System.Console and one other assembly which i forgot. Repeat all those steps and include System.Linq too.
It compiles on monodevelop using mcs because monodevelop uses mono and does not know anything about coreclr or corefx or its new build system. In mono and .net framework previous System.Linq was in System.Core which you do not need to reference because probably monodevelop/Visual Studio reference it for you automatically as some essential assemblies are referenced automatically by IDE's. While in coreclr and its bcl/corefx system.Linq is in its own assembly and package.

**Comment by jasonwilliams200OK** [comment]
[Untested solution]

I think in your `packages.config`, you need to add:

```xml
<package id="System.Linq" version="4.0.0-beta-22816" />
```

Then restore the packages:

```bash
mono nuget.exe restore -Source https://www.myget.org/F/dotnet-corefx/ -PackagesDirectory .
```

and execute:

```bash
mcs -nostdlib -noconfig \
/r:../packages/System.Console.4.0.0-beta-22703/lib/contract/System.Console.dll \
/r:../packages/System.Runtime.4.0.20-beta-22703/lib/contract/System.Runtime.dll \
/r:../packages/System.Linq.4.0.0-beta-22816/lib/contract/System.Linq.dll \
ClientServer.cs
```

*(you may want to verify the location of `System.Linq.dll` in `../packages/System.Linq.4.0.0-beta-22816` directory, I am assuming it would have the same structure as the others)*

pinging @stephentoub, @josteink

@richlander, (bit off-topic) I think in documentation, we can have line breaks `\` in CLI to avoid horizontal scrollbars (like I did above in `mcs` command). It would probably improve readability.

**Comment by josteink** [comment]
Yeah. You're missing the Link DLL.

**Comment by skao21** [comment]
shahid-pk,  jasonwilliams200OK and josteink  all correct 

It  is the System.Linq.4.0.0-beta-xxx that I missing.
But when I include  the System.Linq.4.0.0-beta-2281 in the packages.config  before running the "mono nuget.exe ....." I got the following error:
unable to find version "4.0.0-beta-22816" of package 'system;linq"
After replacing the 22816 with 22703 and run mcs the ling error was gone. 

But I still have the other 2 errors.

error CS0234: The type or namespace nameNet' does not exist in the namespace System'. Are you missing an assembly reference? ClientServer.cs(7,14):
error CS0234: The type or namespace nameNet' does not exist in the namespace `System'. Are you missing an assembly reference?
Compilation failed: 2 error(s), 0 warnings

I tried to include System.Net.4.0.0-beta-22703 and System.Net.4.0.0-beta-22816 before running nuget again.  Both include failed with  "unable to find version ...... " 
Is the problem from missing System.Net.dll?

**Comment by shahid-pk** [comment]
what is nameNet in your code ? i think you should gist or something all of your code.

**Comment by skao21** [comment]
Thanks for the help.

I am trying to  use the following as a  TCP server listening to clients request.
 IPAddress ipAd = IPAddress.Parse("192.168.1.24");
                                TcpListener myList = new TcpListener(ipAd, 8001);
TcpListener myList = new TcpListener(ipAd, 8001);

AND the other side the code also a HTTP client using  the following:
 HttpWebRequest request = (HttpWebRequest)WebRequest.Create(urladdr);

This code was working in my VS2013 in my Window machine. I am trying to port to Linux to see if it works. So I delete all the C# code in the file and only have the import.

Anyway, I am now only have "using statement" to try if the  namesapce are resolved under Linux.

This is my test code now.
----------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Net;
using System.Net.Sockets;

namespace ClientServer
{
    public class ClientServer
    {
        public static void Main()
        {
        }
    }
}
----------------------------------------------

By the way,
I steal the mono's System.Net.dll, it seems fix the following  problems.
error CS0234: The type or namespace nameNet' does not exist in the namespace System'. Are you missing an assembly reference? ClientServer.cs(7,14):

But I got another error:
error CS0234: The type or namespace name `Sockets' does not exist in the namespace `System.Net'. Are you missing an assembly reference?


Here are commands I ran on Linux. i am not sure should I refer to mono's dll file, please advise.

Ubuntu:~/coreclr-demo/runtime$ mono --version
Mono JIT compiler version 4.0.1 (tarball Tue May 12 15:39:23 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
   ......
Ubuntu:~/coreclr-demo/runtime$ ls /usr/lib/mono/4.0/System.Net.dll
/usr/lib/mono/4.0/System.Net.dll
Uuntu:~/coreclr-demo/runtime$ mcs -nostdlib -noconfig /r:../packages/System.Console.4.0.0-beta-22703/lib/contract/System.Console.dll /r:../packages/System.Runtime.4.0.20-beta-22703/lib/contract/System.Runtime.dll /r:../packages/System.Linq.4.0.0-beta-22703/lib/contract/System.Linq.dll /r:/usr/lib/mono/4.0/System.Net.dll  test.cs
test.cs(7,18): error CS0234: The type or namespace name `Sockets' does not exist in the namespace `System.Net'. Are you missing an assembly reference?
Compilation failed: 1 error(s), 0 warnings

**Comment by skao21** [comment]
Ok, in order to prove the code compiled on monodevelop, please review the capture.
I think the problem is from my packages.conf  - but i just do not know who to fix it.

![mono](https://cloud.githubusercontent.com/assets/12723453/7994343/a6dffaee-0ada-11e5-933b-272dd3a463fc.png)

**Comment by jasonwilliams200OK** [comment]
Please edit your previous comments and wrap your code in three back ticks followed by language name (C#) for better readability, like this:


\`\`\`c#
*your code*
\`\`\`

**Comment by skao21** [comment]
```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Net;
using System.Net.Sockets;

namespace ClientServer
{
    public class ClientServer
    {
        public static void Main()
        {
        }
    }
}
```

**Comment by jasonwilliams200OK** [comment]
Thank you and you may also want to edit your previous comments with same fix, so the future viewers don't get their eyes hurt. :)

> After replacing the 22816 with 22703 and run mcs the ling error was gone. 

Nuget supports wildcard, so you can *probably* use wild cards like this

```xml
<package id="System.Linq" version="4.*" />

<!-- or -->

<package id="System.Linq" version="4.0.0*" />

<!-- and even -->

<package id="System.Linq" version="*" />
```

Back to the next issue, `System.NET.Sockets` is yet to be open-sourced: https://github.com/dotnet/corefx-progress/blob/master/src-diff/README.md.

**Comment by shahid-pk** [comment]
@skao21  mono's System.net.dll won't work yes it will make it compile but you will have run time errors. I guess you will have to wain for System.Net.Sockets for a bit to get open source. It is coming. You can see what is coming and what has already got open sourced here https://github.com/dotnet/corefx-progress/blob/master/src-diff/README.md

**Comment by CIPop** [comment]
The System.Net.Sockets port has been completed: https://github.com/dotnet/corefx/issues/896.
