### ISSUE TITLE
JIT: unnecessary null checks in address trees that involve field access on byrefs

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#10942]
`P0`'s explicit null check is unnecessary. A similar check appears in the codegen for the proposed span indexer intrinsic expansion #10910, in cases where the span's pointer field cannot be promoted, and the check causes some performance regressions when using the intrinsic expansion instead of using the IL.

The explicit null check is inserted by morph in `fgMorphField`. Because interpretation of `GT_FIELD` is parent node dependent, morph needs to look for child field nodes and pass down the right context. There is some manipulation of address context in `fgMorphSmpOp` but it doesn't get this case right, and so the indefinite offset from `v * 8` is taken to apply to the dereference of `f.p` too.

```C#
unsafe struct F
{
    public F(int* x) { p = x; }
    public int* p;
}

static unsafe int P1(ref F f)
{
    return *(f.p);
}

static unsafe int P0(ref F f, int v)
{
    return *(f.p + v * 8);
}
```
```asm
;; P1
mov      rax, qword ptr [rcx]
mov      eax, dword ptr [rax]
ret

;; P0
cmp      dword ptr [rcx], ecx
mov      rax, qword ptr [rcx]
shl      edx, 3
movsxd   rdx, edx
mov      eax, dword ptr [rax+4*rdx]
ret
```

**Comment by AndyAyersMS** [comment]
The `* 8` is unnecessary -- I had been using `Span<byte>`  as inspiriation. Here's a simpler `P0` that likewise null checks:

```C#
static unsafe int P0(ref F f)
{
    return *(f.p + v);
}
```

```asm
cmp      dword ptr [rcx], ecx
mov      rax, qword ptr [rcx]
movsxd   rdx, edx
mov      eax, dword ptr [rax+4*rdx]
ret
```

**Comment by AndyAyersMS** [comment]
Am going to hold off merging #10910 until I've had a chance to look at this in more detail. If it turns out to be tricky to fix I have some workarounds I can do on the intrinsic side. But I'd prefer not to....

**Comment by omariom** [comment]
@AndyAyersMS 
Is it related to [Suboptimal code after inlining a method accessing a field via ref  ](https://github.com/dotnet/coreclr/issues/1226)

**Comment by AndyAyersMS** [comment]
Could very well be. I will have to investigate why the changes in #6631 don't kick in here.

But it's better to not create the check in the first place then to create it, prove it is not needed, and then remove it, so I'll probably pursue quashing the check in morph even if it could be cleaned up later on.
