### ISSUE TITLE
Add microbenchmarks for Span extension methods

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/coreclr#10954]
Add benchmark tests [here](https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/Performance/CodeQuality/Span/SpanBench.cs) that exercise the following Span extension methods:

- IndexOf
- IndexOfAny
- SequenceEqual
- StartsWith
- AsSpan
- CopyTo

cc @JosephTremoulet

**Comment by grant-d** [comment]
Also `Contains<T>` (https://github.com/dotnet/corefx/issues/27526)

**Comment by adamsitnik** [comment]
The described API are covered with benchmarks in the performance repo, the code can be found here: https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/corefx/System.Memory/Span.cs

**Comment by ahsonkhan** [comment]
> - CopyTo

Do we have the benchmarks for all the APIs, including CopyTo? I couldn't find that one.

**Comment by adamsitnik** [comment]
> Do we have the benchmarks for all the APIs, including CopyTo? 

We do, but they are stored in a separate file to allow for easy Array vs Span vs List comparison

https://github.com/dotnet/performance/blob/2296c92879ed0744cec9b983ac28ac208e7018bd/src/benchmarks/micro/corefx/System.Collections/CopyTo.cs#L40

BTW I found a big difference for Array.CopyTo vs Span.CopyTo using these benchmarks: https://github.com/dotnet/corefx/issues/36417
