### ISSUE TITLE
CoreCLR failed to build on Windows due to MSBuild error MSB1001: unknown switch --TargetsWindows=true

### ISSUE THREAD

**Issue by KarenHuang2016** [dotnet/coreclr#10968]
I tried to build CoreCLR on Windows with VS2017 RTM. It failed to build when execute msbuild.cmd. This issue is caused by master branch revision [42f1781](https://github.com/dotnet/coreclr/commit/42f1781463e973a7e764675715191b4f137d4e05#diff-f35ce63d6e75aecbc109ddc24e0d77f0).
This revision added a parameter _-TargetsWindow=true_ to msbuild.cmd. It seems the correct parameter should be _/p:TargetsWindows=true_.

You can repro the issue as the steps below:
1. git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2. Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\CoreCLR\src
3. build x86 release -Rebuild -- /clp:ShowCommandLine

Error info:
BUILDTEST: Creating test wrappers...
Tools are already initialized.
Running: D:\CoreCLR\src\Tools\dotnetcli\dotnet.exe D:\CoreCLR\src\Tools\run.exe D:\CoreCLR\src\config.json build -Project=D:\CoreCLR\src\tests\runtest.proj -BuildWrappers -MsBuildEventLogging=" " -MsBuildLog=/flp:Verbosity=normal;LogFile="D:\CoreCLR\src\bin\Logs\Tests_XunitWrapper_Windows_NT__x86__Release.log" -MsBuildWrn=/flp1:WarningsOnly;LogFile="D:\CoreCLR\src\bin\Logs\Tests_XunitWrapper_Windows_NT__x86__Release.wrn" -MsBuildErr=/flp2:ErrorsOnly;LogFile="D:\CoreCLR\src\bin\Logs\Tests_XunitWrapper_Windows_NT__x86__Release.err" -BuildOS=Windows_NT -BuildType=Release -BuildArch=x86    -Rebuild -- /clp:ShowCommandLine -TargetsWindows=true
Running: D:\CoreCLR\src\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false     D:\CoreCLR\src\tests\runtest.proj /p:__BuildType=Release /p:__BuildArch=x86 /p:__BuildOS=Windows_NT /t:Rebuild  /flp:Verbosity=normal;LogFile=D:\CoreCLR\src\bin\Logs\Tests_XunitWrapper_Windows_NT__x86__Release.log  /flp1:WarningsOnly;LogFile=D:\CoreCLR\src\bin\Logs\Tests_XunitWrapper_Windows_NT__x86__Release.wrn  /flp2:ErrorsOnly;LogFile=D:\CoreCLR\src\bin\Logs\Tests_XunitWrapper_Windows_NT__x86__Release.err /p:BuildWrappers=true /clp:ShowCommandLine **-TargetsWindows=true**
**MSBUILD : error MSB1001: Unknown switch.
Switch: -TargetsWindows=true**

For switch syntax, type "MSBuild /help"
Command execution failed with exit code 1.
Xunit Wrapper build failed

**Comment by danmosemsft** [comment]
@wtgodbe

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/11031 should resolve this issue. Sorry for the mistake! Explanation of the problem is in that PR.

**Comment by KarenHuang2016** [comment]
Thanks for fixing this issue!
