### ISSUE TITLE
Missing div => mul by reciprocal case

### ISSUE THREAD

**Issue by russellhadley** [dotnet/coreclr#10970]
This case was found in the Kestrel parser code.

For signed div by 10 we are successfully turning it into a imul by reciprocal, but for unsigned we're failing to do the transformation.

Repro: https://gist.github.com/russellhadley/3130b9bfb30567befbc03ae4830f5bfb

**Comment by russellhadley** [comment]
@shiftylogic can you provide a pointer to the case in the parser code?

**Comment by russellhadley** [comment]
@JosephTremoulet just assigning you for tracking purposes.

**Comment by mikedn** [comment]
I could take care of this, I worked on reciprocal division before.

**Comment by JosephTremoulet** [comment]
@mikedn have at it, thanks!

**Comment by russellhadley** [comment]
@mikedn It's up for grabs.  Go at it.

**Comment by shiftylogic** [comment]
Not Kestrel, that I am aware of. It is in our formatter code [here](https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Primitives/System/Text/Formatting/Internal/FormattingHelpers.cs#L109).

I have a (currently private) branch that attempted to add a ulong version of this method for the integer formatting code. That is when I saw the issue.

**Comment by mikedn** [comment]
> It is in our formatter code here.

Number formatting is a good use for unsigned magic division. `unsigned / 10` is cheaper than `signed / 10`.

**Comment by mikedn** [comment]
I adapted the number formatter code to make a quick perf test:
```C#
[MethodImpl(MethodImplOptions.NoInlining)]
public static int WriteDigits(ulong value, int digitCount, char* buffer, int index)
{
    ulong left = value;

    for (var i = digitCount - 1; i >= 0; i--)
    {
        ulong num;
        left = DivMod(left, 10, out num);
        buffer[index + i] = (char)('0' + num);
    }

    return digitCount;
}

[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static ulong DivMod(ulong numerator, ulong denominator, out ulong modulo)
{
    ulong div = numerator / denominator;
    modulo = numerator - (div * denominator);
    return div;
}
```
`WriteDigits` is ~7x faster when unsigned magic division is enabled (for value = 9223372036854775807 and digitCount = 20).

And unsigned magic division is 10-20% faster than signed magic division so in number formatting code is probably best to use unsigned numbers, anyway the sign is handled separately.

**Comment by shiftylogic** [comment]
Cool. I'll modify our formatting code once your change is merged and makes its way into our repo.
