### ISSUE TITLE
[Arm64/Unix] PR #10912 broke build

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#10971]
@rahku Let me know if you want this or you want to assign it to me.

**Comment by rahku** [comment]
Sorry for the break. It will be helpful if you can take care of it. I don't have a machine to test it.

**Comment by sdmaclea** [comment]
@rahku No problem.  I owe you one anyway.  Until we get [Arm64/Unix] in CI, we will see issues like these.  If you need me to build/test a future CoreCLR arm64 PR on [Arm64/unix] ping me.

**Comment by rahku** [comment]
Thanks 👍 will let you know in future if i need help.

**Comment by sdmaclea** [comment]
Fixed by #10977
