### ISSUE TITLE
Writing a C++ program on Linux that uses cor.h, cordebug.h, etc

### ISSUE THREAD

**Issue by quoctruong** [dotnet/coreclr#10978]
I'm trying to write a C++ program on Linux which will reference certain types and functions in cor.h (and some other header files in the coreclr repo). However, it seems that cor.h needs some other header files that redefine a lot of STL functions and types (especially in pal.h?). Is there a recommended way to build such a program?

**Comment by jkotas** [comment]
You can try defining `PAL_STDCPP_COMPAT` before including the pal headers. It is not perfect, but it will avoid majority of the collisions.

**Comment by quoctruong** [comment]
@jkotas Thank you! I tried that and managed to successfully compiled it. During linking, however, I still get this error:
```
Linux.x64.Debug/lib//libcoreclrpal.a(mutex.cpp.o): undefined reference to symbol 'pthread_mutexattr_setrobust@@GLIBC_2.12'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
```
which I assume is because I'm missing some linking library when I tried to link libcoreclrpal.a. Do you happen to know which other libraries I have to link to fix this?

Thanks!

**Comment by quoctruong** [comment]
Actually, I managed to fixed it by including the appropriate native library. Please ignore the comment above. Thanks!
