### ISSUE TITLE
Add the failing method/indexer when the runtimes throws a NullReferenceException

### ISSUE THREAD

**Issue by mburbea** [dotnet/coreclr#1098]
Currently, the null reference exception does not tell you much.
`object reference not set to an instance of an object`. If you are in debug or compiled with Pdbs you might get line numbers too.
But that doesn't tell a lot. I think it would be very useful if the exact method that's failing was also added. This will help narrow down the error quite a bit. Consider the following line.
`person.AddressInfo.PhoneNumber.E164Normalize()`
Any one of those properties could throw, but if It instead told me that `it was PhoneNumber get_AddressInfo()`, I now know where to look. 

Even in a virtual call type of case this is still tremendously more helpful.
`object reference not set to an instance of an object, failing call: Int32 Object.GetHashCode()`, 

I can at least see which method threw via the stacktrace and then I can look for usage of this method. While C#7 is going to add support for the `?.` safe navigator operator, there is still plenty of code written before the operator, and still plenty of null reference exceptions that can happen unexpectedly. (e.g. `Dictionary.TryGetValue` can throw a NullRefException if somebody is adding to the dictionary on a separate thread)

**Comment by akoeplinger** [comment]
See https://github.com/dotnet/coreclr/issues/25 for an similar discussion.

**Comment by mburbea** [comment]
Agreed, but while that was more or less asking for the line of compiled code, which I think is much harder, this might be an easier bit of data, as there is `methodref`/`methoddef` available in the il.

**Comment by mikedn** [comment]
> "this might be an easier bit of data, as there is  methodref / methoddef  available in the il"

Except that no IL code ever throws NullReferenceExceptions because IL code never runs. And the native code that does run doesn't know about methodrefs, after all the call might not even be there due to inlining.

**Comment by OtherCrashOverride** [comment]
> Any one of those properties could throw, but if It instead told me that it was PhoneNumber get_AddressInfo(), I now know where to look. 

Its not an error for a property or function to return a null.  The place in code where you got the null and call site where its used could be separated by an arbitrary amount of code:

> person.AddressInfo.PhoneNumber.E164Normalize()

Is "syntactic sugar" for:
> var temp1 = person.AddressInfo;
var temp2 = temp1.PhoneNumber;
var temp3 = temp2.E164Normalize();

Therefore, reporting 'get_AddressInfo()' as the place where the null was returned before its used as 'temp1' would require the runtime to have a deep knowledge of the language (and revisions of it) being used.  Reporting: "object reference not set to an instance of an object. temp1 was null" does not provide any additional debugging assistance. The issue deepens when you factor in code in-lining.

Its my opinion that NullReferenceException should not be any more exceptional than other exceptions.  This proposal, and the many other like it, are wanting better **unhandled exception** reporting.  As noted in the other threads, a primary concern is that CoreCLR is not specific to any language such as C#.  The error reporting has to make sense for any language using it.

**Comment by mburbea** [comment]
That was supposed to be the return type, not the actual reference. As for the inlining its true, but perhaps it can be looked up? I'm not sure.

**Comment by lt72** [comment]
Closing this since it seems interest has vanished.

**Comment by alexsorokoletov** [comment]
Not sure if the interest has vanished. It feels like we have #25 for that but then the thread is very long and ends with an article saying VS 2017 can do some magic about that.
#25 also links to the #1311 but 1311 has NullReferenceException out of scope.

I'm deeply interested in having this in any .NET (newer versions) inside NullReferenceException message or somewhere in data so that this information gets passed to the analytics/crash reporting systems.
