### ISSUE TITLE
[Arm64/Unix] SOS 64K page support

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#10982]
Fix "TODO-ARM64-NYI Support for SOS on target with 64K pages" Introduced by #10981

**Comment by sdmaclea** [comment]
@RussKeldorph I did not attempt to fix this in !10981 because I have never used or built the SOS debugger 
(locally or remotely).  I do not mind being assigned it, but this will likely be a low priority for me.

**Comment by RussKeldorph** [comment]
@sdmaclea Thanks for the correction.  Sorry about that.

**Comment by sdmaclea** [comment]
Also please check the usage of PAGE_SIZE & PAGE_MASK in src/debug/createdump/*.  These appear to be coming from host system headers.  These will probably need to be made dynamic to create usable dumps from targets with 64k pages.

**Comment by gkhanna79** [comment]
CC @mikem8361 @lt72

**Comment by mikem8361** [comment]
Currently createdump is only built/used on amd64.

**Comment by sdmaclea** [comment]
@debayng Tested SOS on 64K platform and found it to be working
