### ISSUE TITLE
CI test fail: Ubuntu arm Cross Release Build

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/coreclr#10986]
ARM32/Linux CI test fails by timeout occurs after https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_release_ubuntu_prtest/1089/, but I've seen similar messages when I try to test #10406 without removing `libcoreclrtraceptprovider.so`. 

So I suggest
- Change default PR triggered: arm ubuntu (14.04) release -> arm ubuntu 16.04 release
- Change arm ubuntu 14.04 debug/release CI job: build only, and skip test until we solve this failure 

@gkhanna79 @BruceForstall @janvorli

**Comment by hseok-oh** [comment]
It's a simple reason. Build result of CoreFX also has `libcoreclrtraceptprovider.so` because nupkg of CoreCLR has it. We should remove it from downloaded build result of CoreFX.

**Comment by gkhanna79** [comment]
@hseok-oh Can this be closed?
