### ISSUE TITLE
error MSB3073

### ISSUE THREAD

**Issue by sgzwiz** [dotnet/coreclr#110]
00:13:40.380     4>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: 命令“setlocal\r [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass f:/coreclr-master/src/vm/h2inc.ps1 f:/coreclr-master/src/vm/amd64/asmconstants.h >F:/coreclr-master/binaries/CMake/src/vm/wks/AsmConstants.tmp\r [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd\r [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: "E:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\cl.exe" -DDEBUG -D_DEBUG -D_DBG -DURTBLDENV_FRIENDLY=Checked -DBUILDENV_CHECKED=1 -DWRITE_BARRIER_CHECK=1     -DFEATURE_EVENT_TRACE=1 -D_CRT_STDIO_ARBITRARY_WIDE_SPECIFIERS -DDEV10 -DWIN32 -DDEVL=1 -D_WIN32_WINNT=0x0602 -D_WIN32_IE=0x0900 -DWINNT=1 -DNT_INST=0 -DCONDITION_HANDLING=1 -DNTDDI_VERSION=NTDDI_WIN8 -D_TARGET_AMD64_=1 -DDBG_TARGET_AMD64 -D_CRT_SECURE_NO_WARNINGS -DNTMAKEENV -D_BLD_CLR -DWINVER=0x0602 -DWIN32_LEAN_AND_MEAN=1 -DDEBUGGING_SUPPORTED -DEnC_SUPPORTED -DFEATURE_APPDOMAIN_RESOURCE_MONITORING -DFEATURE_ARRAYSTUB_AS_IL -DFEATURE_ASYNC_IO -DFEATURE_BCL_FORMATTING -DFEATURE_CLASSIC_COMINTEROP -DFEATURE_COLLECTIBLE_TYPES -DFEATURE_APPX -DFEATURE_COMINTEROP -DFEATURE_COMINTEROP_APARTMENT_SUPPORT -DFEATURE_COMINTEROP_UNMANAGED_ACTIVATION -DFEATURE_COMINTEROP_WINRT_MANAGED_ACTIVATION -DFEATURE_CORECLR -DFEATURE_CORESYSTEM -DFEATURE_CORRUPTING_EXCEPTIONS -DFEATURE_CRYPTO -DFEATURE_EXCEPTIONDISPATCHINFO -DFEATURE_FRAMEWORK_INTERNAL -DFEATURE_HIJACK -DFEATURE_HOST_ASSEMBLY_RESOLVER -DFEATURE_HOSTED_BINDER -DFEATURE_ISOSTORE -DFEATURE_ISOSTORE_LIGHT -DFEATURE_ISYM_READER -DFEATURE_LEGACYNETCF -DFEATURE_LEGACYNETCFCRYPTO -DFEATURE_LEGACYNETCF_DBG_HOST_CONTROL -DFEATURE_LEGACYNETCFFAS -DFEATURE_LEGACYSURFACE -DFEATURE_LOADER_OPTIMIZATION -DFEATURE_MANAGED_ETW -DFEATURE_MANAGED_ETW_CHANNELS -DFEATURE_MAIN_CLR_MODULE_USES_CORE_NAME -DFEATURE_MERGE_CULTURE_SUPPORT_AND_ENGINE -DFEATURE_MERGE_JIT_AND_ENGINE -DFEATURE_NORM_IDNA_ONLY -DFEATURE_PREJIT -DFEATURE_RANDOMIZED_STRING_HASHING -DFEATURE_STANDALONE_SN -DFEATURE_STRONGNAME_DELAY_SIGNING_ALLOWED -DFEATURE_STRONGNAME_MIGRATION -DFEATURE_STRONGNAME_TESTKEY_ALLOWED -DFEATURE_SVR_GC -DFEATURE_SYNTHETIC_CULTURES -DFEATURE_VERSIONING -DFEATURE_VERSIONING_LOG -DFEATURE_WIN32_REGISTRY -DFEATURE_WINDOWSPHONE -DFEATURE_WINMD_RESILIENT -DFEATURE_X509 -DFEATURE_X509_SECURESTRINGS -DPROFILING_SUPPORTED -DFEATURE_MULTICOREJIT -DFEATURE_USE_ASM_GC_WRITE_BARRIERS -DFEATURE_SYMDIFF -D_AMD64_ -D_AMD64_SIMULATOR_ -D_AMD64_SIMULATOR_PERF_ -D_AMD64_WORKAROUND_ -D_WIN64 -DAMD64 -D_SKIP_IF_SIMULATOR_ -D_SECURE_SCL=0 -D_NEW_SDK=1 -DOFFICIAL_BUILD=0 -DBETA=0 -DFX_BRANCH_SYNC_COUNTER_VALUE=0 -DUNICODE -D_UNICODE -D_TARGET_AMD64_=1 -DDBG_TARGET_64BIT=1 -DDBG_TARGET_AMD64=1 -DDBG_TARGET_WIN64=1 -DFEATURE_LEAVE_RUNTIME_HOLDER=1 -DUNICODE -D_UNICODE -DFEATURE_MERGE_JIT_AND_ENGINE /EP F:/coreclr-master/binaries/CMake/src/vm/wks/AsmConstants.tmp >F:/coreclr-master/binaries/CMake/src/vm/wks/AsmConstants.inc\r [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd\r [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: :cmEnd\r [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone\r [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: :cmErrorLevel\r [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: exit /b %1\r [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: :cmDone\r [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd\r [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: :VCEnd”已退出，代码为 1。 [F:\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]
                   已完成执行任务“Exec”的操作 - 失败。 (任务 ID: 136)

**Comment by sgzwiz** [comment]
Sorry. I was wrong.

**Comment by Alexx999** [comment]
@sgzwiz  that's OK, but you probably should close this issue so no-one has to review it.
