### ISSUE TITLE
DllImport not finding libs on Centos 7 + fedora (and archlinux)

### ISSUE THREAD

**Issue by NikkyAI** [dotnet/coreclr#11005]
the package i want to use is LibGit2Sharp.Portable

the gl2s package generates a dllmapping xml file in the bin folder, which is used on some distros
but ignored on others

the dev told me it is most likely a coreclr issue

runtimes i tested on:
```diff
- centos (breaks)
+ ubuntu (works in a VM)
+ windows (works)
+ debin (works in a VM)
  RHEL (untested)
- fedora (broken in a VM)
  openSUSE (untested)
- archlinux (breaks)
```

will keep the list updated as i can test more

test procedure;
```
# https://github.com/NikkyAI/lg2s
git clone https://github.com/NikkyAI/lg2s.git
cd lg2s
dotnet restore
dotnet run
```

**Comment by yizhang82** [comment]
@NikkyAI Thanks for reporting the issue. Can you provide more information, such as:
* What is the error (exception, AV, etc)
* Why do you think it's CoreCLR issue rather than issue in the application/library?

I don't think we support dllmap today - it's likely that you'll need to account for the difference in different distros at the moment.

**Comment by davidfowl** [comment]
Looks like it *might* be a packaging issue. @AArnott do you know if that package was updated to match the new RID conventions in nuget?

**Comment by AArnott** [comment]
I don't know if the libgit2sharp.nativebinaries package is using an older or newer RID convention. Here is what I see:

```
C:\USERS\ANDARNO\.NUGET\PACKAGES\LIBGIT2SHARP.NATIVEBINARIES\1.0.165
│   LibGit2Sharp.NativeBinaries.1.0.165.nupkg
│   LibGit2Sharp.NativeBinaries.1.0.165.nupkg.sha512
│   LibGit2Sharp.NativeBinaries.nuspec
│
├───build
│       LibGit2Sharp.NativeBinaries.props
│
├───libgit2
│       libgit2.license.txt
│       LibGit2Sharp.dll.config
│       libgit2_filename.txt
│       libgit2_hash.txt
│
└───runtimes
    ├───linux-x64
    │   └───native
    │           libgit2-1196807.so
    │
    ├───osx
    │   └───native
    │           libgit2-1196807.dylib
    │
    ├───win7-x64
    │   └───native
    │           git2-1196807.dll
    │           git2-1196807.pdb
    │
    └───win7-x86
        └───native
                git2-1196807.dll
                git2-1196807.pdb

```

**Comment by davidfowl** [comment]
@NikkyAI you can set `COREHOST_TRACE=1` and `dotnet bin\debug\netcoreapp1.1\ lg2s.dll` to see what the host is doing for your native binaries. You can also look at the .assets file in the `obj` folder to see how nuget inferred those folders. Regardless this belongs on github.com/dotnet/core-setup.

/cc @gkhanna79

**Comment by yizhang82** [comment]
@davidfowl Thanks. Is there anywhere we document these things? I'm planning to dig deeper into this topic (given that many people are having issues) but I find the documentation on authoring/probing native assets are a bit parse... As a runtime guy I only know what runtime does :(

**Comment by davidfowl** [comment]
@yizhang82 The most comprehensive guide is here. https://docs.microsoft.com/en-us/dotnet/articles/core/rid-catalog

I don't think there's anything that calls out the specific algorithm (but there should be). The general flow is:

- Run `dotnet restore` on a project
- NuGet generates a `project.assets.json` in the `obj` folder that describes the assets that build should use for both runtime and compile time. This includes native and managed assemblies.
- Build generates an `{appname}.deps.json`, that contains a subset of the information in `project.assets.json` relevant to the runtime.
- `dotnet` reads `{appname}.deps.json` and turns it into arguments to the CoreCLR host. https://github.com/dotnet/core-setup/blob/b4bb6cfc7beda3f60aaea0e46df5578d3d7fd74c/src/corehost/cli/hostpolicy.cpp

**Comment by NikkyAI** [comment]
thanks @davidfowl 
using `export COREHOST_TRACE=1` on my laptop
the best info i can get related to the lib that it is not loading is
```
Processing native/culture for deps entry [libgit2sharp.nativebinaries, 1.0.165, runtimes/linux-x64/native/libgit2-1196807.so]
  Considering entry [libgit2sharp.nativebinaries/1.0.165/runtimes/linux-x64/native/libgit2-1196807.so] and probe dir [/opt/dotnet/shared/Microsoft.NETCore.App/1.1.1]
    Skipping... probe in deps json failed
  Considering entry [libgit2sharp.nativebinaries/1.0.165/runtimes/linux-x64/native/libgit2-1196807.so] and probe dir [/home/nikky/.nuget/packages]
    Relative path query exists /home/nikky/.nuget/packages/libgit2sharp.nativebinaries/1.0.165/runtimes/linux-x64/native/libgit2-1196807.so
    Specified no roll forward; matched [/home/nikky/.nuget/packages/libgit2sharp.nativebinaries/1.0.165/runtimes/linux-x64/native/libgit2-1196807.so]
```
but i am not really sure what `Specified no roll forward matched` means and why it is failing

**Comment by NikkyAI** [comment]
http://nikky.moe/alpacka/trace.log.txt
crash is at the bottom

**Comment by davidfowl** [comment]
In both cases it looks like the host picked the right folder from the output:

```
Property NATIVE_DLL_SEARCH_DIRECTORIES = /home/nikky/.nuget/packages/libgit2sharp.nativebinaries/1.0.165/runtimes/linux-x64/native:/opt/dotnet/shared/Microsoft.NETCore.App/1.1.1:
```

So it may not be a host problem.

**Comment by davidfowl** [comment]
Are you sure libgit2 works on centos?

**Comment by NikkyAI** [comment]
actually i am not sure.. there is libgit2 packages for centos, and libgit2 boasts being 100% cross platform
https://libgit2.github.com/  https://pkgs.org/download/libgit2
also they list their compatability to be with any Linux on amd64 https://github.com/libgit2/libgit2sharp.nativebinaries#libgit2sharpnativebinaries

**Comment by bording** [comment]
FYI this isn't a CoreCLR problem. The current versions of the .so files shipped in the `LibGit2Sharp.NativeBinaries` package are built against Ubuntu 12.04, so that's why they don't work on CentOS.

Once LibGit2Sharp officially supports .NET Core, my plan is to ship more binaries in the package.

**Comment by davidfowl** [comment]
Thanks for the confirmation!

**Comment by NikkyAI** [comment]
guess that means this is resolved.. should be closeed i guess ?
