### ISSUE TITLE
Runtime fails to find locally built and referenced assemblies.

### ISSUE THREAD

**Issue by Labris** [dotnet/coreclr#11002]
How to reproduce (using VS2017):

Create new solution , add .net core DLL project.
Add test function
Build it.
Close Solution.
Create new solution, add .net core Console App
Reference previously built DLL, and call testfuntion from it;
Run Console program.

Expected result:
Call works and program quits.

What happens:
Program crashes with:
"System.IO.FileNotFoundException: 'Could not load file or assembly 'NetCoreTestDLL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'"

After build dll is sitting next to built console app.

**Comment by gkhanna79** [comment]
Issue moved to [dotnet/cli #6369](https://github.com/dotnet/cli/issues/6369) via [**ZenHub**](https://www.zenhub.com/)
