### ISSUE TITLE
Cant find lttng/tracepoint.h when building CoreCLR even though its present

### ISSUE THREAD

**Issue by phxvyper** [dotnet/coreclr#11000]
Im on Void Linux, x86_64. I have all of the dependencies installed including liblttng-ust-dev.

Running `./build.sh` produces an error "Cannot find libttng-ust-dev." Looking at the output above, it looked for the file `/usr/include/lttng/tracepoint.h` - which does exist in that exact directory, but the build system refuses to find it.

Why might it not be finding this file?

**Comment by am11** [comment]
On Void Linux, `lttng-ust-devel` implicitly depends on `liburcu-devel`. The lttng-ust package has a make-dependency on `liburcu`, but not the package dependency. Hence, we do not get `liburcu-devel` automatically with `lttng-ust-devel`.

Here is the Dockerfile that builds CoreCLR or Void Linux x64:

```dockerfile
FROM voidlinux/voidlinux
RUN uname -a

RUN xbps-install -Suy

RUN xbps-install -Suy \
 bash curl git gcc llvm clang lldb lldb-devel cmake libstdc++-devel icu-devel \
 libunwind-devel libtool make libuuid-devel lttng-ust-devel liburcu-devel \
 libblkid libfdisk libmount util-linux xfsprogs sqlite gawk

RUN git clone https://github.com/dotnet/coreclr && cd coreclr && ./build.sh

# How to use:
#
# * install docker
# * create directory coreclr-voidlinux
# * create a file in that directory called Dockerfile and copy this content
# * in terminal `cd to/coreclr-voidlinux`, and execute:
#       docker build --tag coreclr-docker .
# * or to avoid caching the intermediate-containers, use:
#       docker build --tag coreclr-docker --no-cache --rm=true .
```

Note that the dependencies on the last line (`libblkid libfdisk libmount util-linux xfsprogs sqlite gawk`) are added to resolve various XBPS packages conflicts in the official docker image. YMMV.

**Comment by phxvyper** [comment]
That made it build! Awesome, we were having a really hard time figuring out what was going on. Thanks a ton.
