### ISSUE TITLE
[Linux ARM64 GC] Enable FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP for Unix ARM64

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#11018]
This is important for short GC pauses.

**Comment by sdmaclea** [comment]
@jashook @jkotas Can you assign this to me.

**Comment by sdmaclea** [comment]
@jkotas Looks like FEATURE_MANUALLY_MANAGED_CARD_BUNDLES might be required too?

**Comment by jkotas** [comment]
> @jkotas Looks like FEATURE_MANUALLY_MANAGED_CARD_BUNDLES might be required too?

Right, it is optimization on top of `FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP`.

cc @adityamandaleeka

**Comment by sdmaclea** [comment]
This is fixed for 4k pages by #11375 (merged).
For 64K pages #11413 is also required.

**Comment by sdmaclea** [comment]
@jkotas Fixed by #11413 can be closed
