### ISSUE TITLE
[ARM32] Console app problem "Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0"

### ISSUE THREAD

**Issue by stefaanv** [dotnet/coreclr#11012]
Hi, 
I'm developing a .NET Core network-oriented console app to be deployed on a Raspberry Pi 3 running 16.04.2 LTS.  Although I was able to deploy to the rPi in the beginning when there was much less code, I get this error message now (with more code in the app)
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
at ProtocolHub.Program.Main(String[] args)
```
I have read [the post [ARM32] Could not load file or assembly ](https://github.com/dotnet/coreclr/issues/9168#issuecomment-277846829), but can't manage to implement the proposed changes partly because I'm having trouble understanding it all, partly because my .proj files are XML rather than json.
My code is [here on GitHub](https://github.com/stefaanv/ProtocolHubDotNetCore), I'm developing in VS2017.
The runtime on the rPi is
```
Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-001970-00
  Build    : fdfa54cfc092dbb30fe0ba53cc11aeaa6ab916e1
```
Before copying the code to the rPi, I change the runtime.config.json file to reflect the version of the installed framework
```
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0-preview1-001970-00"
    }
  }
}
```

Any ideas how to resolve this ?
Stefaan

**Comment by stefaanv** [comment]
Anyone ?

**Comment by gkhanna79** [comment]
The error indicates that assembly (lets call it Assembly A) containing Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher type was trying to load (or had a reference to) 4.2.0.0 version of System.ComponentModel.* while the version found was a lower version. Did Assembly A build against .NET Core as well?

**Comment by mohamedmansour** [comment]
I am having same issue on Windows dotnetcore2.

`System.IO.FileLoadException: 'Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'`

When doing the following:

```
WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
```
My csproj is the following:
```

<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <TypeScriptToolsVersion>2.4</TypeScriptToolsVersion>
    <OutputPath>..\bin\</OutputPath>
    <BaseIntermediateOutputPath>..\obj</BaseIntermediateOutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="1.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\**\*.ts;wwwroot\**\*.less;wwwroot\**\*.js;wwwroot\**\*.css" CopyToPublishDirectory="Never" />
    <Content Update="wwwroot\**\*.min.js;wwwroot\**\*.min.css" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="dotnet bundle" />
  </Target>
  
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.4.337" />
  </ItemGroup>

</Project>

```

Ideas what I should do?
