### ISSUE TITLE
Download dotnet tool is slow.

### ISSUE THREAD

**Issue by mazong1123** [dotnet/coreclr#11041]
Following dotnet tool link is very slow to access at least in China. 
https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/%DOTNET_VERSION%/%DOTNET_ZIP_NAME%

Is there any mirror sever here? If not I can setup one if you guys think it is necessary.

This is probably not a problem for most developers. If so please feel free to close this issue :).

**Comment by jkotas** [comment]
https://dotnetcli.azureedge.net/ should work. Would you like to submit PR to update docs and tools to use that instead?

**Comment by mazong1123** [comment]
Sure. I'd like to take this one.

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/14683/commits/f75e211ded5c832611f140c0f4ed710425c73772
