### ISSUE TITLE
Session IdleTimeout does not have effect

### ISSUE THREAD

**Issue by Marthyn** [dotnet/coreclr#11048]
dotnet cli output 
```
Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```

We have built a simple backoffice application that uses a Session from Dotnet Core. By using the method AddSession as described in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state we have tried to extend the session time from the default 20 minutes to longer. This does not seem to have an effect. Below is a code example where we set it to just 10 seconds, which also has no effect. Always the 20 minutes is kept. 

```C#
services.AddSession(options =>
{
  options.CookieName = ".STPSuppliers.Session804";
  options.IdleTimeout = TimeSpan.FromSeconds(10);
  options.CookieHttpOnly = true;
});
```

We have also tried only using the IdleTimout setting, not setting the CookieName or CookieHttpOnly option, without any effect.

**Comment by gkhanna79** [comment]
@Marthyn Can you please close this issue and move it to https://github.com/aspnet/Home?

CC @glennc

**Comment by gkhanna79** [comment]
Closing the issue here - please move it to ASP.NET repo.
