### ISSUE TITLE
Cordb::Initialize throws error on Linux

### ISSUE THREAD

**Issue by quoctruong** [dotnet/coreclr#11058]
Hi, I'm trying to write a debugger in C++ for CoreCLR using the [RegisterForRuntimeStartup](https://github.com/dotnet/coreclr/blob/master/src/dlls/dbgshim/dbgshim.cpp#L651) method (thanks to suggestion from this [issue](https://github.com/dotnet/coreclr/issues/10568). This works just fine on Windows machine.

However, when I tested it out on Linux, if I call `Initialize` on the `ICorDebug` object returned in the callback function, I get a segmentation fault error. I tried to ran it on gdb and I get to this:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff778aa53 in EnvironGetenv (name=0x7fffec00cb50 "COMPlus_StressLog", copyValue=0)
   at /coreclr/src/pal/src/misc/environ.cpp:928
928	   for (int i = 0; palEnvironment[i] != nullptr; ++i)
```
Not sure if this is correct but it seems that the [InitializeCommon function](https://github.com/dotnet/coreclr/blob/master/src/debug/di/rsmain.cpp#L481) is trying to get some environment variables and for some reason palEnvironment is not initialized?

Is this a bug or did I do something wrong here?

Thanks!

**Comment by gkhanna79** [comment]
CC @noahfalk

**Comment by noahfalk** [comment]
@mikem8361 - Sounds like this is right up your alley : )

**Comment by mikem8361** [comment]
This looks like the PAL is not being properly initialized. EnvironInitialize() initializes palEnvironment which is called from Initialize() in pal.cpp which is called from PAL_InitializeDLL().  PAL_InitializeDLL is called inside the PUBLIC_CONTRACT macro that is the beginning of all the public dbgshim functions RegisterForRuntimeStartup included.

I don't know why this is happening to you. You will probably have to debug into the PAL starting with PAL_InitializeDLL call in the PUBLIC_CONTRACT macro in RegisterForRuntimeStartup.

**Comment by quoctruong** [comment]
Is it because I'm not compiling with the appropriate headers and flags? I'm currently using clang to compile with the flags `-std=c++11 -fPIC -fms-extensions -fsigned-char -fwrapv -DPAL_STDCPP_COMPAT -DBIT64 -DPLATFORM_UNIX`. Are there any additional MACROS to define? Thanks!

**Comment by mikem8361** [comment]
I assumed you are using the coreclr cmake build. There are all kinds of macros/defines that need to be defined.  I couldn’t list here. The biggest one (but the only one) is FEATURE_PAL.

**Comment by quoctruong** [comment]
@mikem8361, turns out I was linking the wrong library. I linked with libcoreclr instead of libcoreclrpal. That seems to solve the problem. Thanks!
