### ISSUE TITLE
Unit test b091942 fails with seg fault on Tizen

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#11069]
```
FAILED   - JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b091942/b091942/b091942.sh
               BEGIN EXECUTION
               /home/coreclr/bin/tests/Windows_NT.x64.Debug/Tests/coreoverlay/corerun b091942.exe
               ./b091942.sh: line 200:  1846 Segmentation fault      (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 139
               END EXECUTION - FAILED
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_debug_tizen_prtest/1384/consoleText

This may not be actionable without symbols but we can start trackign at least.

**Comment by janvorli** [comment]
@danmosemsft it seems random coreclr unit tests keep crashing on the emulator pretty often. I think that there was a discussion about it in the past and that it was said that it is a problem of the emulator and that on real hardware, the tests are stable. @jyoungyun can you confirm that?

**Comment by RussKeldorph** [comment]
May be a dup of #6298.  I don't think this is codegen.  More likely the emulator itself.

**Comment by danmosemsft** [comment]
Another one: https://github.com/dotnet/coreclr/issues/11069

@jyoungyun ?

**Comment by parjong** [comment]
@danmosemsft @janvorli This does not appear on real device.

**Comment by danmosemsft** [comment]
@parjong how can we avoid these emulator specific issues impacting PR jobs? What do you suggest?

**Comment by parjong** [comment]
\CC @hqueue @hseok-oh @jyoungyun

**Comment by hqueue** [comment]
>  More likely the emulator itself.

Yes, it's related to emulator.

> how can we avoid these emulator specific issues impacting PR jobs? What do you suggest?

At first, we try to filter out tests which are unstable in emulation environment, but it seems to be  totally random regardless test suites.

One of candidate solution, which is not neat, could be re-trying `runtest.sh` inside CI with same overlay once more when test fails at the first try. I think we can reduce failure frequency of emulator greatly, although it's not a approach to choose.

**Comment by RussKeldorph** [comment]
@hqueue These failures have gone on far too long.  Assuming you can't fix the emulator or its environment (whereever the root problem lies), until there is an alternative solution in CI, retrying is probably our best option.  Could you (or someone you delegate) please add a hack to runtest.sh to recognize this situation and retry an individual test up to three times?  We can use #6298 to track this.  I will add more of my recommendations there.

**Comment by RussKeldorph** [comment]
Assuming dup of #6298
