### ISSUE TITLE
Remove Tools-Override/codeOptimization.targets

### ISSUE THREAD

**Issue by dpodder** [dotnet/coreclr#11078]
#10950 included a patch for BuildTools using the /Tools-Override mechanism for the file `codeOptimization.targets`. The override patch should be removed once BuildTools moves forward to version `1.0.27-prerelease-01513-01` or newer.

Note: only the `/Tools-Override/codeOptimization.targets` file needs to be removed; the other changes in #10950 (to `config.json`) need to be left in.

**Comment by gkhanna79** [comment]
@dpodder Is this for 2.0?

**Comment by dpodder** [comment]
@gkhanna79 No, it's not; it's a tracking issue for maintainability. The fix can happen either before 2.0 or after 2.0, as far as this issue is concerned.

**Comment by dpodder** [comment]
Resolved by #11620
