### ISSUE TITLE
[Memory consumption] Compact entry points for ARM

### ISSUE THREAD

**Issue by gbalykov** [dotnet/coreclr#11076]
Hello.

We propose to add compact entry points for ARM, but not exactly the way they are done for x86. For MethodDescChunk with 5 MethodDescs compact entry points will look like this:

```
entry1:
  mov r12, pc
  b CentralJump
entry2:
  mov r12, pc
  b CentralJump
entry3:
  mov r12, pc
  b CentralJump
entry4:
  mov r12, pc
  b CentralJump
entry5:
  mov r12, pc
  b CentralJump
CentraJump:
  ldr pc, pThePreStubCompactARM
  nop
  dw pChunk
  dw pThePreStubCompactARM
```

Compact entry points are encoded in Thumb, each compact entry has 4 byte size, CentralJump is 14 bytes.

ThePreStubCompactARM finds CentralJump by looking into branch offset of compact entry. Then it calculates offset of the compact entry from CentralJump by program counter stored in r12 and, thus, calculates index of MethodDesc in MethodDescChunk. Then,ThePreStubCompactARM loads pointer to MethodDescChunk from CentralJump and obtains MethodDesc, corresponding to the calculated index (this is done by traversing all MethodDescs in MethodDescChunk starting from the first until the MethodDesc with required index is met). After that, ThePreStubCompactARM calls PreStubWorker with obtained MethodDesc, like original ThePreStub.

Estimation on Tizen GUI Xamarin application (https://developer.tizen.org/sites/default/files/documentation/puzzle2.zip) shows, for ReadyToRun mode, that reduction of code heap size is 76 KB, which is 20% of code heap and, approximately, 2.2% of overall per-application CoreCLR memory consumption. For No-Precompilation mode, reduction of code heap size is 216 KB, which is 28% of code heap and, approximately, 2.3% of overall per-application CoreCLR memory consumption.

ReadyToRun mode means the Tizen-default set of precompiled assemblies is in ReadyToRun format, No-Precompilation mode means that there are no precompiled assemblies.

However, we expect slightly lower performance. Could you, please, suggest a way to estimate performance changes? We want to consider enabling compact entry points for arm by default. What do you think about this?

We plan to open pull request for this change in two days.

@lemmaa @egavrin @Dmitri-Botcharnikov @ruben-ayrapetyan

**Comment by jkotas** [comment]
> However, we expect slightly lower performance

The compact entrypoint is only used once to trigger JITing. There should be no performance impact.

**Comment by BruceForstall** [comment]
cc @janvorli

**Comment by gbalykov** [comment]
@jkotas,

Our concern is that calls to compact entry points are indirected via slots in a table that are patched to point to the actual entry points eventually. We would like to estimate the performance changes with calls indirected via slots. Is there any way to do that?

**Comment by gbalykov** [comment]
@jkotas,

To clarify out concerns, here is the place in source code, where caller is required to call via slot for compact entry points.

At the end of MethodDesc::TryGetMultiCallableAddrOfCode function:


```cpp

#ifdef HAS_COMPACT_ENTRYPOINTS
    // Caller has to call via slot or allocate funcptr stub
    return NULL;
#else // HAS_COMPACT_ENTRYPOINTS
    //
    // Embed call to the temporary entrypoint into the code. It will be patched 
    // to point to the actual code later.
    //
    return GetTemporaryEntryPoint();
#endif // HAS_COMPACT_ENTRYPOINTS
```

It is said in documentation (in the Book of the Runtime, Method Descriptor chapter), that raw speed difference between compact entry points and entry points implemented using StubPrecode or FixupPrecode is "the cost of an indirect call for a compact entry point vs. the cost of one direct call and one direct jump on the given platform". 

It is also said, that "the later used to be faster by a few percent in large server scenario since it can be predicted by the hardware better (2005)", but it's "not always the case on current (2015) hardware". 

We would like to measure performance impact of the compact entry points on ARM on current hardware. Could you, please, suggest a way to do that?

**Comment by jkotas** [comment]
The simplest microbenchmark to measure it is:

```
[MethodImpl(MethodImplOptions.NoInlining)]
static void empty()
{
}

static void test()
{
    for (int i = 0; i < 1000000000; i++)
        empty();
}
```

The measure it with and without `HAS_COMPACT_ENTRYPOINTS`.

**Comment by gbalykov** [comment]
@jkotas,

Thank you very much!

**Comment by gbalykov** [comment]
@jkotas,

Micro-benchmark showed next results:
- Cortex-A7 softfp:
      before: 12.81s (user time)
      after: 10.488s (user time)
- Cortex-A15 softfp:
      before: 5.3s (user time)
      after: 4.68s (user time)

**Comment by gbalykov** [comment]
Closing the issue. The pull request #11109 is merged.
