### ISSUE TITLE
JIT/CheckProjects test requires that Core_Root be relative to repo root

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#11079]
https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/CheckProjects/CheckProjects.cs#L51-L62

This condition isn't met in Helix, causing this test to fail there - I don't think we should require that Core_Root be in a location relative to the repo root for a test to execute.

CC @AndyAyersMS @RussKeldorph

**Comment by RussKeldorph** [comment]
Agreed.  We were thinking this (and other meta-tests) should somehow be made to run at the end of build-tests or between build-tests and runtest.

@jashook

**Comment by AndyAyersMS** [comment]
Would it be simpler to modify the test to report success if there is no bin directory above CORE_ROOT? Then no special casing is required.

**Comment by wtgodbe** [comment]
@AndyAyersMS I don't think so, because https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/CheckProjects/CheckProjects.cs#L60 assumes that it can find the path to the repo root by searching relative to Core_Root

**Comment by jashook** [comment]
This is a dup of 10635

**Comment by jashook** [comment]
As Russ explained, for tests which have a fundamental dependency on having the either access to the test or product sources, we should not include them in runtests. Instead they should be run as a post step to buildtests.

**Comment by AndyAyersMS** [comment]
Changing line 57 to `return 100;` should do the trick, no?

Doesn't make much sense to me to run this as part of buildtests, since the core overlay is probably not set up yet, and even if it is, we probably don't want to test the new jit during a build step more than we have to.

**Comment by wtgodbe** [comment]
@AndyAyersMS ah, I misunderstood - yeah, that would do the trick.

**Comment by RussKeldorph** [comment]
@AndyAyersMS I'm fine with a change like that for now to unblock Helix work.  In the future we might need to solve this a different way if we want this test to be effective in all environments.  I'd say our automation will likely look more like the Helix model in the future even if this works in ci.dot.net now.
