### ISSUE TITLE
JIT_opt._Tailcall_TailcallVerifyWithPrefix_TailcallVerifyWithPrefix & Loader_classloader._TypeInitialization_CctorsWithSideEffects_UntrustedCodeBFI reference System.Security.Permissions from mscorlib

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#11084]
> MESSAGE:
Error: Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. (Exception from HRESULT: 0x80070002 (COR_E_FILENOTFOUND))\r\nError compiling UntrustedCodeBFI.exe: Could not find or load a specific file. (Exception from HRESULT: 0x80131621 (COR_E_FILELOAD))\r\nError: compilation failed for \"UntrustedCodeBFI.exe\" (0x80131621)\r\n\n\nReturn code: 1\nRaw output file: D:\\j\\workspace\\x64_checked_w---ba5f4470\\bin\\tests\\Windows_NT.x64.Checked\\Reports\\Loader.classloader\\TypeInitialization\\CctorsWithSideEffects\\UntrustedCodeBFI\\UntrustedCodeBFI.output.txt\nRaw output:\nBEGIN EXECUTION\r\n\" D:\\j\\workspace\\x64_checked_w---ba5f4470\\tests\\..\\bin\\tests\\Windows_NT.x64.Checked\\Tests\\Core_Root\\crossgen.exe\" /Platform_Assemblies_Paths D:\\j\\workspace\\x64_checked_w---ba5f4470\\tests\\..\\bin\\tests\\Windows_NT.x64.Checked\\Tests\\Core_Root;D:\\j\\workspace\\x64_checked_w---ba5f4470\\bin\\tests\\Windows_NT.x64.Checked\\Loader\\classloader\\TypeInitialization\\CctorsWithSideEffects\\UntrustedCodeBFI UntrustedCodeBFI.exe\r\nMicrosoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0\r\nCopyright (c) Microsoft Corporation. All rights reserved.\r\n\r\nCrossgen failed with exitcode - -2146232799\r\nTest Harness Exitcode is : 1\r\n\nTo run the test:\n> set CORE_ROOT=D:\\j\\workspace\\x64_checked_w---ba5f4470\\bin\\tests\\Windows_NT.x64.Checked\\Tests\\Core_Root\n> D:\\j\\workspace\\x64_checked_w---ba5f4470\\bin\\tests\\Windows_NT.x64.Checked\\Loader\\classloader\\TypeInitialization\\CctorsWithSideEffects\\UntrustedCodeBFI\\UntrustedCodeBFI.cmd\n\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at Loader_classloader._TypeInitialization_CctorsWithSideEffects_UntrustedCodeBFI_UntrustedCodeBFI_._TypeInitialization_CctorsWithSideEffects_UntrustedCodeBFI_UntrustedCodeBFI_cmd() in D:\j\workspace\x64_checked_w---ba5f4470\bin\tests\Windows_NT.x64.Checked\TestWrappers\Loader.classloader\Loader.classloader.XUnitWrapper.cs:line 133387

https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/opt/Tailcall/TailcallVerifyWithPrefix.il#L50 (& other instances in same file)

https://github.com/dotnet/coreclr/blob/master/tests/src/Loader/classloader/TypeInitialization/CctorsWithSideEffects/UntrustedCodeBFI.il#L79 (& other instances in same file)

@weshaggard what is the best course of action here? These tests are failing in Helix & in CI

**Comment by weshaggard** [comment]
You either need to pull in our System.Security.Permissions package to your tests or remove the dependency on those types that live in there.

**Comment by wtgodbe** [comment]
These are now passing (I added a dependency on System.Security.Permissions)
