### ISSUE TITLE
[x86jit32] SciMark2 benchmark is broken.

### ISSUE THREAD

**Issue by jorive** [dotnet/coreclr#11089]
We have not got results since April 5th, 2017.
Benchmark: tests\src\JIT\Performance\CodeQuality\SciMark
Similar issue: https://github.com/dotnet/coreclr/issues/11088

**Comment by gkhanna79** [comment]
CC @RussKeldorph

**Comment by RussKeldorph** [comment]
@jorive If this started failing at the same time as Roslyn, it is likely the same as #11088, but I can't repro this now, with or without the fix for #11088 included.  I'll follow up with @adiaaida to see if she can help me with the repro, but closing this for now.
