### ISSUE TITLE
JIT_Performance._RunBenchmarks_RunBenchmarks_RunBenchmarks fails when running R2R

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#11082]
> MESSAGE:
Error: Could not load file or assembly 'System.Xml.XPath.XmlDocument, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. (Exception from HRESULT: 0x80070002 (COR_E_FILENOTFOUND))\r\nError compiling RunBenchmarks.exe: Could not find or load a specific file. (Exception from HRESULT: 0x80131621 (COR_E_FILELOAD))\r\nError: compilation failed for \"RunBenchmarks.exe\" (0x80131621)\r\n\n\nReturn code: 1\nRaw output file: D:\\j\\workspace\\x64_checked_w---ba5f4470\\bin\\tests\\Windows_NT.x64.Checked\\Reports\\JIT.Performance\\RunBenchmarks\\RunBenchmarks\\RunBenchmarks.output.txt\nRaw output:\nBEGIN EXECUTION\r\n\" D:\\j\\workspace\\x64_checked_w---ba5f4470\\tests\\..\\bin\\tests\\Windows_NT.x64.Checked\\Tests\\Core_Root\\crossgen.exe\" /Platform_Assemblies_Paths D:\\j\\workspace\\x64_checked_w---ba5f4470\\tests\\..\\bin\\tests\\Windows_NT.x64.Checked\\Tests\\Core_Root;D:\\j\\workspace\\x64_checked_w---ba5f4470\\bin\\tests\\Windows_NT.x64.Checked\\JIT\\Performance\\RunBenchmarks\\RunBenchmarks RunBenchmarks.exe\r\nMicrosoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0\r\nCopyright (c) Microsoft Corporation. All rights reserved.\r\n\r\nCrossgen failed with exitcode - -2146232799\r\nTest Harness Exitcode is : 1\r\n\nTo run the test:\n> set CORE_ROOT=D:\\j\\workspace\\x64_checked_w---ba5f4470\\bin\\tests\\Windows_NT.x64.Checked\\Tests\\Core_Root\n> D:\\j\\workspace\\x64_checked_w---ba5f4470\\bin\\tests\\Windows_NT.x64.Checked\\JIT\\Performance\\RunBenchmarks\\RunBenchmarks\\RunBenchmarks.cmd\n\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at JIT_Performance._RunBenchmarks_RunBenchmarks_RunBenchmarks_._RunBenchmarks_RunBenchmarks_RunBenchmarks_cmd() in D:\j\workspace\x64_checked_w---ba5f4470\bin\tests\Windows_NT.x64.Checked\TestWrappers\JIT.Performance\JIT.Performance.XUnitWrapper.cs:line 5147

This fails because crossgen.exe cannot find System.Xml.XPath.XmlDocument - I've confirmed this is because that .dll is not present in Core_Root. That package hasn't been published to MyGet since 1/13 (Dev/Eng), nor does it appear in Microsoft.Private.CoreFx.NETCoreApp. @weshaggard @RussKeldorph what's the best course of action here?

**Comment by RussKeldorph** [comment]
@AndyAyersMS Was `System.Xml.XPath.XmlDocument` perhaps just renamed and we just need to update our references?  For example, I see `System.Xml.XPath.XDocument.dll` already in Core_Root.  No idea if it's related, though.

@wtgodbe I feel like there should have been a build break before the crossgen step--either when restoring this dependency or when compiling the C#.  Is that an unreasonable expectation?  I don't pretend to fully understand our build process.

**Comment by AndyAyersMS** [comment]
When we compile I see
```
/reference:C:\repos\coreclr\tests\..\packages\System.Xml.XPath.XmlDocument\4.4.0-beta-24913-02\ref\netstandard1.3\System.Xml.XPath.XmlDocument.dll
```
passed to CSC, and this comes from the common benchmark\project.json that most of our tests use. So we're able to compile.

This class is evidently referenced somewhere in the code because the resulting assembly RunBenchmarks.exe contains:
```
.assembly extern System.Xml.XPath.XmlDocument
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:0:2:0
}
```
I can run the test just fine with no args, which is how it runs as a test case.

But if you pass `-f <suitable-file> -list` when running, it will fail with the same assembly not found error you see in crossgen.

So there's a conditionally used class in the code that is there in ref form for compilation but not present in the test overlay, and attempts to crossgen or run it with the right args will expose the missing assembly.

Seems like we need to update the code for this test and scrub the project.jsons a bit.

**Comment by wtgodbe** [comment]
@AndyAyersMS do you mind putting together a PR for this?

**Comment by AndyAyersMS** [comment]
Sure, just need to figure out what to reference instead...
