### ISSUE TITLE
Build fails while building tests\build.proj

### ISSUE THREAD

**Issue by krk** [dotnet/coreclr#1110]
build.cmd with no arguments fails with "PE file is already strong-name signed." on Struct02.exe file on Win 8.1 x64 VS2013

```
(OpenSourceSign target) -> 
C:\dotnet\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\sign.targets(19,5): error : 
C:\dotnet\coreclr\tests\..\bin\tests\obj\JIT\Generics\Typeof\\Struct02\Struct02.exe: PE file is already strong-name signed. [C:\dotnet\coreclr\tests\src\JIT\Generics\Typeof\cs_template.proj]
```

**Comment by Chrisboh** [comment]
@chcosta bouncing this over to you as I think it was something you were looking at.

**Comment by chcosta** [comment]
I don't believe the signing issues I am going to investigate are related to this, however...

A lot has changed in the past 6 1/2 months.  I just built coreclr clean on a Windows machine by simply calling build.cmd, and it completed without incident.  I'm going to close this issue.  @krk, please feel free to re-open this issue if you are still seeing a problem and provide additional repro information (if any is known).
