### ISSUE TITLE
System.Diagnostics.Stopwatch.ElapsedTicks property has a different order of magnitude

### ISSUE THREAD

**Issue by joost-morsink** [dotnet/coreclr#11102]
The ElapsedTicks property of the System.Diagnostic.Stopwatch class has ticks of size 1ns instead of 100ns:

```sharp
var sw = new Stopwatch();
sw.Start();
Thread.Sleep(TimeSpan.FromSeconds(1.0)); 
sw.Stop();
Console.WriteLine(sw.ElapsedTicks); // prints 1000798045 on my latest test run
Console.WriteLine(TimeSpan.FromSeconds(1.0).Ticks); // prints 10000000
```

Working on a new MacBook Pro with touchbar, just installed latest .net core. Build target is .NetCoreApp1.1.

**Comment by mattwarren** [comment]
I *think* this is covered by the MSDN docs, from [Stopwatch.ElapsedTicks Property](https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.elapsedticks(v=vs.110).aspx#Anchor_1):

> Stopwatch ticks are different from DateTime.Ticks. Each tick in the DateTime.Ticks value represents one 100-nanosecond interval. Each tick in the ElapsedTicks value represents the time interval equal to 1 second divided by the Frequency.

Assuming that `TimeSpan.Ticks` work the same as `DateTime.Ticks`, which [appears to be true](https://msdn.microsoft.com/en-us/library/system.timespan.ticks(v=vs.110).aspx#Anchor_1):

> The smallest unit of time is the tick, which is equal to 100 nanoseconds or one ten-millionth of a second. There are 10,000 ticks in a millisecond. The value of the Ticks property can be negative or positive to represent a negative or positive time interval.

**Comment by joost-morsink** [comment]
Sorry, it was my assumption that they were the same. Apparently they aren't. Thanks for looking into this.

**Comment by andreabalducci** [comment]
Hit same issue on my mac after working the full morning on my desktop pc.
Pc works as expected, on Mac x100 resolution on ticks. imho it's a bug

        [Fact]
        public void stopwatch_ticks_are_wrong_on_netcore_macos()
        {
            var sw = new Stopwatch();
            sw.Start();
            Thread.Sleep(100);
            sw.Stop();
            
            var msFromTicks = sw.ElapsedTicks / TimeSpan.TicksPerMillisecond;
            var ms = sw.ElapsedMilliseconds;
            
            Assert.Equal(ms, msFromTicks);
        }

On Windows pass, on MacOs fails.
dotnet --version => 1.0.3

**Comment by joost-morsink** [comment]
Hi,

I agree it is very confusing that TimeSpan 'Ticks' are different from
Stopwatch 'Ticks'. But if you use the Stopwatch.Frequency property you
should be able to make the test work.

```csharp
var msFromTicks = 1000.0 * sw.ElapsedTicks / StopWatch.Frequency;
var ms = sw.ElapsedMilliseconds;
```
This should work on both Mac and Win.

kind regards,

Joost.
