### ISSUE TITLE
Environment.FailFast should dump exception details to console

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#11114]
Environment.FailFast writes the message (and exception details if provided) to the Windows event log and passes them to Watson. Neither of these go to the developer's console nor to the XUnit logs. Now we have made Debug.Assert do FailFast, this is hindering debugging and test analysis.

We should also write to stderr so if it's a console app you see the details. This should include the message and exception details, with the callstack (hopefully that is just a string inside the exception when it reaches native code)

@jkotas any gotchas here?

**Comment by danmosemsft** [comment]
It should obviously do this with the minimum of ceremony, since this is a failure path. I see the VM already has `PrintToStdErr()` but I don't know if any work is needed to format the message/stack.

**Comment by jkotas** [comment]
All sounds good to me.

**Comment by danmosemsft** [comment]
@ViktorHofer do you want to take a shot at this?

**Comment by ViktorHofer** [comment]
Yeah I will look into it

**Comment by tarekgh** [comment]
@ViktorHofer if you are not looking at this one, I can help look at it tomorrow. please let me know

**Comment by ViktorHofer** [comment]
I will take a look at it tomorrow and will let you know if I need some help. Thanks!

**Comment by ViktorHofer** [comment]
SystemNative::GenericFailFast in "src\classlibnative\bcltype\system.cpp" needs to print the exception message with callstack to stderr and if passed the inner exception. I will talk with @jkotas about it.

**Comment by jkotas** [comment]
I think it should be done in  `EEPolicy::HandleFatalError` so that all sources of failfasts get logged. For example, we want to make sure that there is error message printed for fail fast caused by this program:

```
class My {

static unsafe int Main() {
    int * tmp = (int*)0x1234567890;
    return *tmp;
}

}
```

**Comment by ViktorHofer** [comment]
I'm looking into this right now. I will stick with just printing out the error message to stderr for now.

@gkhanna79 Any idea how to get the StackTrace at that point of execution?

**Comment by gkhanna79** [comment]
See DoReportForUnhandledException on how to compute the string version of the stacktrace.

**Comment by ViktorHofer** [comment]
Perfect, thanks!
