### ISSUE TITLE
CoreMangLib_cti._system_delegate_DelegateGetHashCode1_DelegateGetHashCode1 Fails in Helix 

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#11137]
Test fails periodically on all OS's:

> \n\nReturn code:      1\nRaw output file:      /home/helixbot/dotnetbuild/work/9976fdae-e3ba-4380-8a6b-5f74e91ad7ae/Work/cf6d7480-e675-4d37-be6f-fe028c7ba2ed/Unzip/Reports\CoreMangLib.cti\system\delegate\DelegateGetHashCode1\DelegateGetHashCode1.output.txt\nRaw output:\nBEGIN EXECUTION\n/home/helixbot/dotnetbuild/work/9976fdae-e3ba-4380-8a6b-5f74e91ad7ae/Payload/corerun DelegateGetHashCode1.exe\nBeginning test case DelegateGetHashCode at 4/20/17 11:51:54 PM\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\n\n[Positive]\nBeginning scenario: PosTest1: hash code of two different delegate object is not equal,the two delegate callback different function. \nTestClass's StartWork_Bool method  is running. id=1\nTestClass1's StartWork_Bool method  is running. id=1\nBeginning scenario: PosTest2: hash code of two different delegate object even though  they invoke the same function  is not equal \nTestClass's StartWork_Bool method  is running. id=1\nTestClass's StartWork_Bool method  is running. id=1\nBeginning scenario: PosTest3: Use the same type's same  method to create two delegate which delegate object is the same,their hashcode is equal\nTestClass's Working_Bool method  is running .\nTestClass's Working_Bool method  is running .\nBeginning scenario: PosTest4: Use the same type's different static method to create two delegate which delegate object is the same,their hashcode is equal \nTestClass's Completed_Bool method  is running .\nTestClass's Working_Bool method  is running .\nBeginning scenario: PosTest6:  Use the different type's same static method to create two delegate ,which delegate object is the same,their hashcode is equal\nTestClass's Completed_Bool method  is running .\nTestClass1's Completed_Bool method  is running .\nBeginning scenario: PosTest7:  Use the different instance's same instance method to create two delegate which delegate object is the same, their hashcode is different\nERROR!!!-013: HashCode is not excepted \nTestClass's StartWork_Bool method  is running. id=1\nTestClass1's StartWork_Bool method  is running. id=2\nBeginning scenario: PosTest8: hash code of two delegate object is not equal,the two delegate callback different function. \nTestClass's StartWork_Bool method  is running. id=1\nTestClass's StartWork_Bool method  is running. id=1 message=hello\n\nEnding test case at 4/20/17 11:51:54 PM\nFAIL\nExpected: 100\nActual: 0\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\n\nTo run the test:\n> set CORE_ROOT=/home/helixbot/dotnetbuild/work/9976fdae-e3ba-4380-8a6b-5f74e91ad7ae/Payload\n> /home/helixbot/dotnetbuild/work/9976fdae-e3ba-4380-8a6b-5f74e91ad7ae/Work/cf6d7480-e675-4d37-be6f-fe028c7ba2ed/Unzip/system/delegate/DelegateGetHashCode1/DelegateGetHashCode1.sh\n\nExpected: True\nActual:   False

Looks like this is the check that fails: https://github.com/dotnet/coreclr/blob/master/tests/src/CoreMangLib/cti/system/delegate/delegategethashcode1.cs#L229

https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170420.08/workItem/CoreMangLib.cti.XUnitWrapper/analysis/xunit/CoreMangLib_cti._system_delegate_DelegateGetHashCode1_DelegateGetHashCode1_~2F_system_delegate_DelegateGetHashCode1_DelegateGetHashCode1_cmd

@jkotas have you seen this before?

**Comment by jkotas** [comment]
> PosTest7: Use the different instance's same instance method to create two delegate which delegate object is the same, their hashcode is different\nERROR!!!-013: HashCode is not excepted

This is regression from #11019. This test has some small probability of failing because of it is based on randomness. I though that the probability is very small and it won't register on the radar (https://github.com/dotnet/coreclr/pull/11019#discussion_r112576752), but I was wrong apparently.

@mountgellert Could you please add retry logic to the test to make it not fail intermittently?

**Comment by wtgodbe** [comment]
@jkotas @mountgellert I've temporarily disabled this test for Helix - https://github.com/dotnet/coreclr/blob/master/tests/issues.targets#L422-L424. Please remove these lines when fixing the test.

**Comment by mountgellert** [comment]
Ok, can you help me by explaining what is Helix and how is that different from the normal build? If the hash codes are the same, that means that two sequentially created objects has the same hashcode - that's very very unlikely, so something else is different when run through Helix.

**Comment by wtgodbe** [comment]
Helix is where we test the output of our official builds (e.g. the packages that our customers consume). A difference there is that we build tests against binaries restored from packages, instead of binaries that were just built as part of a product build (the latter is the dev scenario, and the scenario we test in the CI). We also run tests against portable binaries (e.g. all Linux distros run tests against the same binaries), whereas locally & in the CI we use platform-specific binaries. Other than that, if the test itself is creating the two objects, I don't know why that behavior would be different in Helix vs. a normal build.

**Comment by jkotas** [comment]
@wtgodbe Is possible that the official build package and test package were from different source snapshots? (E.g. one having the change from #11019 and the other one not?)

**Comment by wtgodbe** [comment]
@jkotas yes, actually that's most likely what was happening - I didn't realize the test had been modified so recently. I merged an auto-update PR last night, but before that, one hadn't been merged for 3-4 days. Looks like that test passed in the most recent test pass - I'll keep an eye on this test, if it passes the next 2 times I'll consider this fixed.
