### ISSUE TITLE
Doesn't build with clang/llvm 4.0

### ISSUE THREAD

**Issue by juergenpf** [dotnet/coreclr#11159]
Using the clang/llvm 4.0 toolchain I'm getting build errors from pal.h, complaining about defining builtin functions _rotl, _rotr etc.

**Comment by gkhanna79** [comment]
CC @janvorli

**Comment by janvorli** [comment]
@juergenpf there are actually more issues than those two builtins. Clang 4.0 also complains about some clobber annotations in inline asm code, SSIZE_T_MIN constant, _mul128 argument types and few comparisons of pointers as > 0.

**Comment by janvorli** [comment]
I almost have these issues fixed.

**Comment by janvorli** [comment]
Fixed by #11226
