### ISSUE TITLE
Locating Native DLL (PInvoke) behaves differently on Win7 and Win10

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/coreclr#11170]
When I run my application on (netcoreapp2.0) windows 10 everything works fine, as soon as I move to windows 7, the exact same files (publish win7-x64) I get a dll not found exception.

Seems that the way it looks for dlls is different depending on the OS?

I have binaries that can be used to test available here:
https://ci.appveyor.com/api/projects/danwalmsley/AvalonStudio/artifacts/artifacts/zip/AvalonStudio-win7-x64.zip?branch=master

Is there a way to have dotnet run and output log showing where it is looking for native DLL?

**Comment by danwalmsley** [comment]
This looks like it might actually be:
https://github.com/mono/SkiaSharp/issues/264

**Comment by gkhanna79** [comment]
Based upon your response above, does it mean the issue can be closed?

**Comment by danwalmsley** [comment]
yes, iv tested now with the fix!
