### ISSUE TITLE
Support building with FEATURE_EVENT_TRACE=0

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/coreclr#11174]
#10406 and #10961 introduced event tracing for ARM with the option (as far as I understand) to not compile it in.

Right now, the NuGet packaging fails with `cmakeargs -DFEATURE_EVENT_TRACE=0`, because it [still expects the generated `libcoreclrtraceptprovider.so`](https://github.com/dotnet/coreclr/blob/master/src/.nuget/Microsoft.NETCore.Runtime.CoreCLR/runtime.Linux.Microsoft.NETCore.Runtime.CoreCLR.props#L12) on ARM.

I'd love to avoid the dependencies to lttng-ust on my Linux box :)

**Comment by parjong** [comment]
@Tragetaschen You may skip nuget packaging via skipnuget option if nuget packages are not necessary.

**Comment by gkhanna79** [comment]
CC @brianrob

**Comment by brianrob** [comment]
Yes, packaging is going to require libcoreclrtraceptprovider.so.  If you want to avoid installing lttng-ust as a build dependency, then I would recommend skipping nuget package creation via -skipnuget.
