### ISSUE TITLE
Profiling API and IL code verification

### ISSUE THREAD

**Issue by mmayr-at** [dotnet/coreclr#11173]
With the profiling API one can rewrite IL code with the `ICorProfilerInfo::SetILFunctionBody` method at runtime. I am using this to dynamically generate IL code to instrument methods of certain types including types in `mscorlib`. I'm looking now for a way to verify the dynamically generated IL code.

I know that [PEVerify](https://msdn.microsoft.com/en-us/library/62bwd2yd(v=vs.110).aspx) can be used to validate metadata and IL type safety. I could save all assemblies with modifed IL code to disk and run them through PEVerify. There are several problems with this approach:

- PEVerify does not work with `mscorlib`. 

```
c:\Windows\Microsoft.NET\Framework64\v4.0.30319>peverify mscorlib.dll

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

IL Verification cannot be performed on system library mscorlib.dll
All Classes and Methods in mscorlib.dll Verified.
```
- There are framework assemblies with metadata errors
```
c:\Windows\Microsoft.NET\Framework64\v4.0.30319>peverify System.Data.dll

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[MD]: Unverifiable PE Header/native stub.
[MD]: Error: Value class has neither fields nor size parameter. [token:0x02000452]
[MD]: Error: Value class has neither fields nor size parameter. [token:0x02000453]
3 Error(s) Verifying System.Data.dll
```
So IL type safety checks cannot be performed 
```
c:\Windows\Microsoft.NET\Framework64\v4.0.30319>peverify System.Data.dll /IL

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Unverifiable assembly 'c:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Data.dll' failed policy check.
1 Error(s) Verifying System.Data.dll
```

Is there any other way to do IL code verification? 

I found the switch [VerifyAllOnLoad](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md). Does it provide some similar functionality than PEVerify at runtime? If yes, is there any similar switch for full CLR?

**Comment by gkhanna79** [comment]
CC @RussKeldorph

**Comment by mmayr-at** [comment]
To clarify things I made a sample, please see attached [mscorlib_instrumented.zip](https://github.com/dotnet/coreclr/files/957292/mscorlib_instrumented.zip). Assume I would like to count the number of invocations for all `ToString()` methods.  The profiler emits a new class `InvocationCounter` into mscorlib and rewrites the IL code of every `ToString` method to call the `InvocationCounter.IncCounter(string methodName)` method, see screenshot below.

Now I'm looking for a way to verify the rewritten IL code of the instrumented `mscorlib`, e.g in the sample all `ToString()` methods.

![image](https://cloud.githubusercontent.com/assets/16279326/25388047/fca4bff6-29cc-11e7-8f4f-d2598191d48a.png)

**Comment by RussKeldorph** [comment]
You might want to check out other issues with the area-ILVerification label.  In particular, #295 has a link to @jkotas' prototype verifier.  Unfortunately, I can't provide much guidance beyond that, though @jkotas may be able to.

**Comment by mmayr-at** [comment]
@RussKeldorph 
Many thanks for the linked issue! My team, especially @gregkalapos, had a look at the ILVerify prototype and it looks very promising. I will close this issue and continue the discussion on #295.
