### ISSUE TITLE
Cannot call AssemblyLoadContext.InitializeDefaultContext()

### ISSUE THREAD

**Issue by xanather** [dotnet/coreclr#1119]
I am using DNX as the bootstrapper and I am unable to call AssemblyLoadContext.InitializeDefaultContext to set my own CoreCLR native library/assembly loading policies.

https://github.com/dotnet/coreclr/blob/b7273d6f8a6b0b0772c429151bfcbd27cba195fb/src/mscorlib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L247

I always get the model binding is locked exception. Even at the first line entry point my program. No other code touches AssemblyLoadContext.
Any ideas?

**Comment by jasonwilliams200OK** [comment]
Tip: you may want to replace `master` with `b7273d6` in URL you provided to freeze it to the current commit (so the future changes in that file don't misdirect the line number).

**Comment by davidfowl** [comment]
@xanather The DNX already set one and it's not possible for the application to override it. What are you trying to hook?

**Comment by xanather** [comment]
@davidfowl I'm just trying to enable custom native library loading based on the running platform in the LoadUnmanagedDll method (https://github.com/dotnet/coreclr/blob/b7273d6f8a6b0b0772c429151bfcbd27cba195fb/src/mscorlib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L206). Maybe it should be possible to extend DNX's AssemblyLoadContext and provide a command to use the type when calling dnx.exe?

**Comment by davidfowl** [comment]
It already is but we don't expose the native loading part as yet. File an issue on the DNX and we'll look at the extensibility. Here's what it looks like today https://github.com/aspnet/Entropy/blob/dev/samples/Runtime.CustomLoader/Program.cs

**Comment by xanather** [comment]
Will do, closing this issue then since it should be running fine on bare-bones CoreCLR without DNX.
