### ISSUE TITLE
Combining byrefs and unmanaged pointers prevents inlining

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#11211]
Repro:

```
using System;

class Test {

    static ref int foo(ref int p) {
        return ref p;
    }

    static unsafe int Main() {
        int a = 1;
        int * tmp = &a;
        foo(ref *tmp); // BUG: foo does not get inlined here
        return *tmp;
    }
}
```

**Comment by jkotas** [comment]
Original discussion: https://github.com/dotnet/corefxlab/issues/1479#issuecomment-297158779

The problem is that the inliner fails with `'fgInline' result 'failed this call site' reason 'return type mismatch'`

**Comment by AndyAyersMS** [comment]
Think we can fix this easily enough in the jit, we have the right type info, but we lose track of it when we see that we can directly substitute the arg expression into the inlinee, and the caller IL has converted the managed pointer to an integer:
```
  IL_0002:  ldloca.s   a
  IL_0004:  conv.u
  IL_0005:  dup
  IL_0006:  call       int32& Test::foo(int32&)
```

**Comment by jkotas** [comment]
> the caller IL has converted the managed pointer to an integer

I do not think that fixing this bug should be taking advantage how the pointer was created in the minimal repo. The original Span bug was more like this - the pointer came from unknown source:

```
static ref int foo(ref int p) {
    return ref p;
}

static int bar(int * p) {
    return foo(ref *p); // foo should get inlined here
}
```

**Comment by AndyAyersMS** [comment]
The fix doesn't need to see how the pointer was created. It needs to ensure that we use the callee's type when we refer to the argument value, not the caller's type.

Usually even this doesn't matter, but if the argument value also happens to be the return value, we get tripped up and reject the inline.
