### ISSUE TITLE
Import IL.targets from Microsoft.DotNet.BuildTools

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#1122]
We're currently using a checked-in copy of IL.targets from https://github.com/dotnet/buildtools. The copy should be deleted once coreclr has been moved to a version of the build tools that contains IL.targets.

**Comment by jasonwilliams200OK** [comment]
Wouldn't it make sense to request @weshaggard for releasing buildtools vNext rather quickly in a way that the new release is [also visible on GitHub => (dotnet/buildtools#169)](https://github.com/dotnet/buildtools/issues/169)? :smile:

**Comment by pgavlin** [comment]
CoreCLR is actually the problem here: in order to move to a newer version of the build tools, all of the tests need to be updated to use packages.json files instead of packages.xml (among other things). @mmitche is working on this.

**Comment by jasonwilliams200OK** [comment]
:+1: thanks for the answer.

**Comment by ellismg** [comment]
Pat, I think this is actionable now.

**Comment by jkotas** [comment]
Fixed by #15300
