### ISSUE TITLE
[x86/Linux] JIT.Methodical.Boxing.seh._relfilter fail (GCStress=3)

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#11223]
With GCStress=3 JIT.Methodical.Boxing.seh._relfilter fails on x86/Linux.

```
OK
Current totals 0 and 0 and 0
OK
Current totals 0 and 0.314159265358979 and 0.309016994374947
OK
Current totals 0 and 0.942477796076938 and 0.896802246667421
OK
Current totals 0 and 1.88495559215388 and 1.70581924104237
Current totals 0.0201 and 3.14159265358979 and 1.70581924104237
Filtering out the exception...

Assert failure(PID 1 [0x00000001], Thread: 1 [0x0001]): !CREATE_CHECK_STRING(pMT && pMT->Validate())
    File: /home/hanjoung/ws/dotnet/coreclr/src/vm/object.cpp Line: 1727
    Image: /work/nfs/dotnet/ttt/corerun
```

This is almost same issue with #11101(_dbgfilter) which was resolved  by #11195 (not reporting untracked from filter). However this time the most variables are encoded as tracked so we need to handle untracked.

As we discussed in #11101, We may need something like `GCInfo::gcMarkFilterVarsPinned()`.

**Comment by wateret** [comment]
@janvorli Here's my first attempt to do `gcMarkFilterVarsPinned()` on x86/Linux.
https://github.com/wateret/coreclr/commit/dc2ec633820e5d992c44e2ea5a2c597245049bab

It basically uses the same `gcMarkFilterVarsPinned()` of non-JIT32_GCENCODER. All I had to do more was to reorder the generated varDscPtrs by lifetime splitting(in vpdBegOfs order). However the problem was pinned_OFFSET_FLAG is only for untracked. For tracked, the same bit is used as this_OFFSET_FLAG.

**Comment by janvorli** [comment]
@wateret it is great that we can reuse the code almost as-is. 
> However the problem was pinned_OFFSET_FLAG is only for untracked. For tracked, the same bit is used as this_OFFSET_FLAG.

I am not sure I understand this. You say the problem "was", but I don't see any changes in the code that would do anything about it. 

And could you also explain why you had to reorder the  generated varDscPtrs by lifetime splitting? It is because for the x86 gc info they have to be ordered by the vpdBegOfs? 
You could modify the gcInsertVarPtrDscSplit to get the starting point as a parameter and pass it the varTmp, since the split parts cannot be inserted before that. Even if you were splitting the first range in the list, the desc1 and desc2 would always be after the original range in the list. So it would be more efficient this way. 
That also means gcInsertVarPtrDscSplit  doesn't need to handle the special case when the varInsert was nullptr, since it cannot happen.

**Comment by wateret** [comment]
@janvorli Thank you for your response, and I'm sorry that I was not clear.

> I am not sure I understand this. You say the problem "was", but I don't see any changes in the code that would do anything about it.

I should have written "is", not "was". I am still thinking about how to handle this issue. 

In gcinfo.h there is this comment and constant definitions. It says the second bit is used as "this" for tracked which implies "pinned" are not allowed for tracked.

```cpp
//  Note for untracked locals the flags allowed are "pinned" and "byref"
//   and for tracked locals the flags allowed are "this" and "byref"
//  Note that these definitions should also match the definitions of
//   GC_CALL_INTERIOR and GC_CALL_PINNED in VM/gc.h
//
const unsigned  byref_OFFSET_FLAG  = 0x1;  // the offset is an interior ptr
const unsigned pinned_OFFSET_FLAG  = 0x2;  // the offset is a pinned ptr
const unsigned   this_OFFSET_FLAG  = 0x2;  // the offset is "this"
```

the COMPlus_GCDump shows:

**Current master** (causes double-reporting from filter and parent)
```
44 2A 8B 30    | 002A..05DA  [EBP-44H] a  pointer
48 84 2B 87 05 | 0255..05DA  [EBP-48H] a  pointer
4C 20 86 65    | 0275..05DA  [EBP-4CH] a  pointer
50 20 86 45    | 0295..05DA  [EBP-50H] a  pointer
40 12 85 7D    | 02A7..05A4  [EBP-40H] a  pointer
40 86 08 2B    | 05AF..05DA  [EBP-40H] a  pointer
40 41 82 6B    | 05F0..075B  [EBP-40H] a  pointer
44 00 82 6B    | 05F0..075B  [EBP-44H] a  pointer
4C 00 83 76    | 05F0..07E6  [EBP-4CH] a  pointer
50 00 84 33    | 05F0..0823  [EBP-50H] a  pointer
48 00 83 20    | 05F0..0790  [EBP-48H] a  pointer
```

**With my changes**
```
44 2A 8B 30    | 002A..05DA  [EBP-44H] a  pointer
48 84 2B 87 05 | 0255..05DA  [EBP-48H] a  pointer
4C 20 86 65    | 0275..05DA  [EBP-4CH] a  pointer
50 20 86 45    | 0295..05DA  [EBP-50H] a  pointer
40 12 85 7D    | 02A7..05A4  [EBP-40H] a  pointer
40 86 08 2B    | 05AF..05DA  [EBP-40H] a  pointer
4A 41 81 07    | 05F0..0677  [EBP-48H] a this pointer // pinned
52 00 81 07    | 05F0..0677  [EBP-50H] a this pointer // pinned
4E 00 81 07    | 05F0..0677  [EBP-4CH] a this pointer // pinned
46 00 81 07    | 05F0..0677  [EBP-44H] a this pointer // pinned
42 00 81 07    | 05F0..0677  [EBP-40H] a this pointer // pinned
40 81 07 81 64 | 0677..075B  [EBP-40H] a  pointer
44 00 81 64    | 0677..075B  [EBP-44H] a  pointer
4C 00 82 6F    | 0677..07E6  [EBP-4CH] a  pointer
50 00 83 2C    | 0677..0823  [EBP-50H] a  pointer
48 00 82 19    | 0677..0790  [EBP-48H] a  pointer
```

I think everything is OK but "this" should have been "pinned".

In the code here: [eetwain.cpp#L4820](
https://github.com/dotnet/coreclr/blob/4d1df6367de8df74a4d1fb3fe079e181c511d76b/src/vm/eetwain.cpp#L4820), the second bit is ignored by `(lowBits & byref_OFFSET_FLAG) | CHECK_APP_DOMAIN`. I did a simple test: assuming the second bit as pinned for untracked(assuming no conflict between "this" and "pinned"). So, with my changes and changing this part to `lowBits | CHECK_APP_DOMAIN`and it worked for this test case(w/ GCStress=3). So maybe the only issue now is
encode pinned flag to untracked variables.

**Comment by wateret** [comment]
@janvorli 

> And could you also explain why you had to reorder the generated varDscPtrs by lifetime splitting? It is because for the x86 gc info they have to be ordered by the vpdBegOfs?

x86 GCInfo tracked variables are encoded with unsigned delta from the previous entry. That implies the tracked entries must be ordered by `vpdBegOfs`, non-decreasing. Here's [relevant code](https://github.com/dotnet/coreclr/blob/4d1df6367de8df74a4d1fb3fe079e181c511d76b/src/jit/gcencode.cpp#L2224). If `begOffs < lastOffset`, we get an assert failure.

> You could modify the gcInsertVarPtrDscSplit to get the starting point as a parameter and pass it the varTmp, since the split parts cannot be inserted before that. 

Good point. Thank you!
I thought about the third case of splitting, that is when `begOffs >= filterBeg && endOffs > filterEnd`. For this case the generated varPtrDsc should be inserted before the existing one since its range precedes the existing one. However I think we can easily change the existing one to precede the generated one. I think it is worth it so I'll make a change for that shortly.

**Comment by wateret** [comment]
Closing since #11281 is landed.
