### ISSUE TITLE
Restore default Unix file permissions to 777, allow the user to override.

### ISSUE THREAD

**Issue by aslicerh** [dotnet/coreclr#11232]
The changes made in dotnet/coreclr#7995 will be a big pain point for many unix users (and, potentially, cross-platform builders) moving forward, though I can understand the reason behind it.

Perhaps a more amiable solution would be to keep the default permissions at 777 and allow the user to override that default with an environment variable (or maybe even just the current umask setting)?

**Comment by jkotas** [comment]
Could you please share more details on why you think it will be a big pain point for many unix users? All other Unix tools use it as a default - why should .NET be different?

**Comment by tmds** [comment]
@aslicerh @jkotas I've split this issue into two specific cases:
- https://github.com/dotnet/cli/issues/6437
- https://github.com/dotnet/cli/issues/6438

Can we close this issue in favor of those?

cc @omajid

**Comment by aslicerh** [comment]
The reason the issue is not addressed by NuGet/Home#4424 is because there will be packages built from before whatever PR fixes that is implemented and these pre-existing packages will not have any defined permissions and instead will receive the defaults. The same will (most likely) always be true for cross-platform packages built on Windows for unix-y platforms.

The reason that this could be a pain for unix users is that anyone building a cross-platform build from Windows (or anyone from Windows not familiar with unix permission schemes) has never had to worry about this before, and now will. This means that existing NuGet packages will break if used in a 2.0 environment and will need to be rebuilt.

To be fair, if a breaking change was going to happen, a major change over like 2.0 _would_ be the time to do it. I just thought I'd throw out a proposal for a less severe change.

**Comment by janvorli** [comment]
@aslicerh the issue description seems a bit misleading to me. The #7995 has changed the default attributes for general file creation, while your concerns, if I understand them correctly, are rather related to the package restoration. That seems like an orthogonal thing to me.
If that's the case, I don't see how the #7995 would cause troubles. If an app writes out a file that it expects to be executable, it should also make sure it has the executable bit set. If I edit e.g. a shell script on Unix, I also need to set it to be executable explicitly.

**Comment by aslicerh** [comment]
Well, the 'Issue' is more of a suggestion, but I didn't see anything with or about, for example, an [Enhancement] tag.

The reason this applies to packaging is because, at the least, the zip extraction for packages is going to use OpenHandle. So it isn't quite orthogonal, just more of a consequence not directly in this project. If you need an example of the existing discussion about this, you can see in NuGet/Home#4424 how cross-compiled packages are breaking for 2.0 after a publish.

I do agree that the greater issue at hand here is that file permissions are not preserved when creating zip archives today. I even agree that package maintainers should already be checking to make sure that things that need to be executable are actually executable. That doesn't change what exists in the field today or what has been expected behavior up until this point.

But yeah, this is a suggestion, an idea for a middle ground. There's nothing incorrect or improper about what has already been implemented, just some unfortunate circumstances in regards to a transition from 1.* to 2.0 for some consumers.

**Comment by janvorli** [comment]
@aslicerh thank you for all the details.
