### ISSUE TITLE
[x86][Jit32] Math*.cmd failing

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#11276]
Effected Tests:

<pre>
\CoreMangLib\cti\system\mathf\MathFCos\MathFCos.cmd
\CoreMangLib\cti\system\mathf\MathFSin\MathFSin.cmd
</pre>

Example Output:

<pre>
BEGIN EXECUTION
         "D:\core\temp\coreclr\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" MathFCos.exe 
        Beginning test case Testing System.MathF.Cos(System.Single)... at 4/27/2017 3:27:52 PM
        Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
        
        [Positive]
        Beginning scenario: PosTest1: Verify the value of cosine(0)...
        Beginning scenario: PosTest2: Verify the value of cosine(MathF.PI/2)...
        Beginning scenario: PosTest3: Verify the value of cosine(MathF.PI)...
        ERROR!!!-005: cosine(MathF.PI) should be -1!
        Beginning scenario: PosTest4: Verify the value of cosine(3*MathF.PI/2)...
        Beginning scenario: PosTest5: Verify the value of cosine(2*MathF.PI) is equal to cosine(0)...
        ERROR!!!-009: cosine(3*MathF.PI/2) should be 0!
        Beginning scenario: PosTest6: Verify the value of cosine(number) is between -1 and 1...
        
        Ending test case at 4/27/2017 3:27:52 PM
        FAIL
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1

</pre>

**Comment by RussKeldorph** [comment]
Precision difference.
