### ISSUE TITLE
Running program with DNX on Minnow board MAX with Windows IoT Core

### ISSUE THREAD

**Issue by hpaiemen** [dotnet/coreclr#1128]
Hi,
I'm trying to run a small application on a Minnow board MAX with Windows IoT Core on it. It's a pretty basic application that consist of looping on string manipulation with basic math operations to bench performance of the garbage collector on different platforms. I use the "dnu publish" tool to create a package that can be deploy on Windows platform (I use CoreCLR v1.0.0-beta6-12005 x86 runtime and its been "publish" from a standard Windows 7 desktop).

After using ftp to put my package on the Minnow board, I use powershell remotely to exec a batch file to run dnx with proper parameters on the IoT device. Here's the error I get from my powershell:

"dnx.onecore.dll could not be loaded. Last error: 126"

I successfully run my program on different Windows 7 machine (Windows 7 Embedded also) with no problem what so ever. I thought maybe the one cored machines were not supported yet, but really I have no clue.

Thx for your help.

**Comment by hpaiemen** [comment]
Topic moved there : https://github.com/aspnet/dnx/issues/2048.

**Comment by adityamandaleeka** [comment]
Closing this issue since it's being discussed in the [dnx repo](https://github.com/aspnet/dnx/issues/2048).
