### ISSUE TITLE
Does reflection loading use the compatibility shim? (if not, can it)

### ISSUE THREAD

**Issue by Rcomian** [dotnet/coreclr#11292]
I'm trying to load a .NET Framework assembly into my .NET Core project through a call to `System.Reflection.Assembly.LoadFrom(path)`.

I can add a reference to the assembly and use the classes inside that assembly fine. Adding the file via a reference uses the compatibility shim and works fine.

Through reflection, however, I get the following error:

```
System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath
System.IO.FileLoadException: Could not load file or assembly 'library.dll, Version=6.0.6326.22847, Culture=neutral, PublicKeyToken=null'.
```

I don't think there's any legitimate reason why the assembly doesn't load: it exists, I have access and all the required dependencies - I know this as I can use the file through direct references fine.

The only thing I can think of is that it's not using the compatibility shim and the framework versions are very different.

To make the story more complete, I'm not actually calling `LoadFrom` from my .NET Core code - I'm referencing a .NET Framework assembly (through shim reference loading) which is itself calling `LoadFrom` to get create an instance of a class inside the target assembly.

Should assembly loading be shimmed in through this way?
Is it likely I've got some different issue?
If assembly loading doesn't use the shim, can this be implemented?

**Comment by gkhanna79** [comment]
Assembly Loader for .NET Core is something that we have kept intentionally simple and policy free. This is by design. LoadFrom is intended to explicitly load in the default context as well.

Which compat shim are you referring to and which .NEt Framework assembly is performing this load?

**Comment by Rcomian** [comment]
I'm talking about the compat shim that lets you reference a .net Framework 4.6.2 assembly from a .net core 2.0 assembly and use it.

There's no configuration needed, you just reference the assembly and it works (provided it doesn't use any features outside of .net core 2.0). It seems to work really well.

That's only one way of loading an assembly, however. The other way is to use `LoadFrom`. it appears when you try to load a .net framework 4.6.2 assembly into a .net core assembly this way, it doesn't work.

I'm asking for confirmation whether I'm right that `LoadFrom` doesn't use a compat shim. I'm also asking if `LoadFrom` will ever use the compat shim.

**Comment by gkhanna79** [comment]
> I'm talking about the compat shim that lets you reference a .net Framework 4.6.2 assembly from a .net core 2.0 assembly and use it.

I am not sure what this is - @weshaggard @jkotas Do you know what this is about? Is @Rcomian referring to some runtime facade assembly that is what his app gets built against?

> I'm asking for confirmation whether I'm right that LoadFrom doesn't use a compat shim

Yes, that is correct and is what I mentioned above as well.

@Rcomian Can you please share repro for this?

**Comment by weshaggard** [comment]
>I am not sure what this is - @weshaggard @jkotas Do you know what this is about? Is @Rcomian referring to some runtime facade assembly that is what his app gets built against?

Yes the only compat shims I'm aware of are the runtime facades which type-forward all the types to where they live. I would expect reflection to work just fine with those, I suspect the issue is more with LoadFrom and not the shims.

**Comment by gkhanna79** [comment]
> I'm referencing a .NET Framework assembly (through shim reference loading) which is itself calling LoadFrom to get create an instance of a class inside the target assembly.

Which assembly are you referencing and where is it calling LoadFrom? Can you please share a repro?

**Comment by Rcomian** [comment]
I'm going to close this, the issue is *not* what I thought it might be.

I was trying to call `Assembly.LoadFrom` to load an assembly that had already been loaded. That was the cause of the error. If you haven't already referenced the assembly, you can `Assembly.LoadFrom` a .NET Framework assembly just fine.

**Comment by jkotas** [comment]
> I was trying to call `Assembly.LoadFrom` to load an assembly that had already been loaded.

https://github.com/dotnet/coreclr/issues/9879 should have fixed this problem. Have you run on CoreCLR with this fix?

**Comment by Rcomian** [comment]
@jkotas, I haven't, but I shall try as soon as I can, it might make life a lot easier.
