### ISSUE TITLE
Port fix for mutex, event, and semaphore creation from CoreRT

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#11306]
Port dotnet/corert@78fae17f5434839a8720603973ff53f27e27f916 to CoreCLR

Fix the following tests that were disabled under UWP:
https://github.com/dotnet/corefx/blob/master/src/System.Threading/tests/MutexTests.cs#L142-L201

**Comment by kouvel** [comment]
Issue is reported here: http://stackoverflow.com/questions/36591765/mutex-creation-hangs-while-using-impersonation

**Comment by kouvel** [comment]
Can't use this solution for .NET Core as it breaks the access control APIs, will file separate issue for bug

**Comment by kouvel** [comment]
Can call DuplicateHandle to get the necessary access rights

**Comment by kouvel** [comment]
Better yet, include MAXIMUM_ALLOWED in the requested permissions

**Comment by gkhanna79** [comment]
@kouvel Are we driving this for ZBB on 5/10?

**Comment by kouvel** [comment]
It's not a regression so it's not required for 2.0, but it would be nice to fix. I'll move it to 2.1 for now and will consider picking it up if there's time.

**Comment by CIPop** [comment]
@kouvel I am still getting an UnauthorizedAccessException. 
It's not clear from this bug: Is this the expected behavior in an AppContainer accessing a Global mutex?

```
Message:          GetCertificateCollection threw System.TypeInitializationException: The type initializer for 'Certificates' threw an exception. ---> System.UnauthorizedAccessException: Access to the path 'Global\CoreFXTest.Configuration.Certificates.LoadPfxCertificate' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String str)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)

```

**Comment by kouvel** [comment]
Yes it looks like global mutexes can't be created or opened from within an AppContainer. You should be able to use a named mutex just not a global one. According to the documentation, local mutexes (no prefix or Local\ prefix) have session scope and it doesn't say anything specific about AppContainers, so you may be able to use a non-global named mutex instead.
