### ISSUE TITLE
Cleanup public members on AssemblyLoadContext 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#11311]
These are exposed in CoreFX on AppDomain (eg GetLoadedAssemblies is called by Appdomain.GetAssemblies). We should move them to AppDomain in CoreCLR, to make API diffs stop showing them up as unexposed API

   
```c#
    public abstract class AssemblyLoadContext {
        public static event AssemblyLoadEventHandler AssemblyLoad;
        public static event ResolveEventHandler AssemblyResolve;
        public static event ResolveEventHandler ResourceResolve;
        public static event ResolveEventHandler TypeResolve;
        public static Assembly[] GetLoadedAssemblies();
}
```

**Comment by jkotas** [comment]
There are number of other public unexposed types and members that we are using for handshake between CoreCLR and CoreFX. What makes the ones on AssemblyLoadContext special?

**Comment by gkhanna79** [comment]
@danmosemsft I dont believe there is anything actionable here, especially at this last moment of the release. Can this be closed?

**Comment by gkhanna79** [comment]
@danmosemsft Any concerns closing this?

**Comment by danmosemsft** [comment]
I think I flagged them because they were just pass throughs, ie., they might as well be on the right type. Fine to close.
