### ISSUE TITLE
FreeBSD CURRENT (11.0) Cmake not finding lldb

### ISSUE THREAD

**Issue by tony** [dotnet/coreclr#1131]
Related: https://github.com/dotnet/coreclr/issues/940

I have lldb in toolchain by using ``WITH_LLDB=YES`` in ``/etc/src.conf`` and running ``make buildworld && make installworld``.

Cmake isn't discovering llvm/lldb/clang from the ``/usr/src`` in the system toolchain.

**Comment by tony** [comment]
```
➜  coreclr git:(master) ✗ lldb --version
lldb version 3.6.1 clang revision 237755
```

```
➜  coreclr git:(master) ✗ ./build.sh
Commencing CoreCLR Repo build
Cleaning previous output for the selected configuration
Setting up directories for build
Checking pre-requisites...
Commencing build of native components for FreeBSD.x64.Debug
Invoking cmake with arguments: "/snip/study/dotnet/coreclr" DEBUG
CMake Warning at src/ToolBox/SOS/lldbplugin/CMakeLists.txt:26 (message):
  Cannot find lldb-3.5 or lldb-3.6.  Try installing lldb-3.6-dev (or the
  appropriate package for your platform)


Detected FreeBSD amd64
-- Configuring done
-- Generating done
-- Build files have been written to: /snip/study/dotnet/coreclr
Failed to generate native component build project!
```

**Comment by josteink** [comment]
You only need LLDB to be detected during the build-process if you want to build the (currently not very functional) SOS debugger plugin.

In FreeBSD 10.1 the binaries gets installed to `/usr/local/bin/` and the source to `/usr/local/include/lldb/`.

Looking at some of the source, it seems like you should be able to provide explicit paths for this if you want to when auto-detection fails, but I'm not 100% sure:

https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/ToolBox/SOS/lldbplugin/CMakeLists.txt#L34-L48

The key here seems to be `WITH_LLDB_INCLUDES`. Can you try setting that to your `/usr/src/`equivalent?

**Comment by saper** [comment]
I have llvm in `$HOME/git/llvm` so I have used this:

````
env LLDB_LIB_DIR=${HOME}/git/llvm/build/lib \
     LLDB_INCLUDE_DIR=${HOME}/llvm/tools/lldb/include ./build.sh
````

**Comment by tony** [comment]
@saper : I am going to give that approach a shot.

**Comment by tony** [comment]
@saper : I ended coming back to this thread and using your advice and using ``LLDB_LIB_DIR`` and ``LLDB_INCLUDE_DIR`` to look up the LLDB included with ``devel/clang37`` and ``devel/llvm-devel``.

The reason for the delay is my system was looking up old header files from building LLVM / Clang manually that I was overlooking that haunted me for weeks (https://github.com/dotnet/coreclr/issues/797#issuecomment-127187207).  Probably an obvious thing to many here, but I'm new enough to FreeBSD and build environments it tripped me up for a bit.

Let's finally clean these LLDB + FreeBSD issues up :smile:
