### ISSUE TITLE
[Arm64/Unix] Fails to load System.Private.Corelib.ni.dll

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#11324]
Tests are taking 3x as long to run.  This is apparently due to a failure to load S.P.C.ni.dll

**Comment by sdmaclea** [comment]
@gkhanna79 Is this due to #11040?

**Comment by gkhanna79** [comment]
@sdmaclea It is possible since that PR accounts for cross-targeting crossgen to be present. Can you check if https://github.com/dotnet/coreclr/pull/11040/files#diff-1708de55e5220e56e33f7ddb0f465f9cR695 is set to TRUE for Linux Arm64, does it address the problem?

**Comment by sdmaclea** [comment]
I will look at it tomorrow.  My machines are currently all tied up (due to the long run time caused by this problem).

**Comment by sdmaclea** [comment]
@parjong @BruceForstall Do you know if the System.Private.Corelib native image used to load on unix  arm32 and/or x86 ?  Does this issue also affect those platforms?

**Comment by BruceForstall** [comment]
I'll leave this for @parjong ; I haven't done enough actual running of code on Unix.

**Comment by gkhanna79** [comment]
I believe it does (https://github.com/dotnet/coreclr/blob/master/build.sh#L432) since they also do not support cross-targeting crossgen.

**Comment by sdmaclea** [comment]
Ok so the issue is that I have been running crossgen on the target to create S.P.C.ni.dll.  This allowed my tests to run faster.

The new code does not attempt to load S.P.C.ni.dll at all.  And does not attempt to load S.P.C.dll as ni on Unix unless target is amd64.

If fExplicitBindToNativeImage is set to true, and the NI is absent in S.P.C.dll, will it fall back and try to load as IL?

**Comment by gkhanna79** [comment]
> If fExplicitBindToNativeImage is set to true, and the NI is absent in S.P.C.dll, will it fall back and try to load as IL?

Assuming there are no alignment issues for mmap that you were discussing with me last week.

**Comment by parjong** [comment]
For x86, we do not attempt to crossgen S.P.C.dll, yet.
For ARM, we have been crossgened it.

**Comment by sdmaclea** [comment]
Fallback was broken on arm64.  I think the #11341 fix will work on all platforms.

**Comment by sdmaclea** [comment]
Fixed by #11341
