### ISSUE TITLE
Error with the .Net version manager installation instructions

### ISSUE THREAD

**Issue by axefrog** [dotnet/coreclr#1132]
The instructions indicate what I should enter into a powershell command prompt:

![](http://content.screencast.com/users/NathanRidley/folders/Jing/media/08b8dc4c-cec8-41fd-bd45-b8c6cbeb1fd5/2015-06-12_1836.png)

However when I do so, I get the following:

![](http://content.screencast.com/users/NathanRidley/folders/Jing/media/9f90e6e6-d675-49eb-81c2-d3499d194183/2015-06-12_1834.png)

If I omit the leading '@' symbol, it kind of works, but there's an error when it first starts:

![](http://content.screencast.com/users/NathanRidley/folders/Jing/media/ffcaa2f4-b8c5-41fc-9469-2754e9da2ec7/2015-06-12_1838.png)

**Comment by jasonwilliams200OK** [comment]
This is because that command is mean to run from cmd.
If you are inside the PowerShell, you don't need to "shell out" to powershell (because escaping from powershell to any other shell is different than cmd). Just run:

```powershell
&{$Branch='dev';iex ((new-object net.webclient).DownloadString('
https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}
# multi lines command: you will need to hit enter twice ?!!?
```

OR

```powershell
# for single line, hit enter once and command will run! welcome to powershell :)
&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}
```

**Comment by axefrog** [comment]
You'll note that the text in the instructions indicates that the prompt is powershell:

`PS >`

Might be worth changing to:

`C:>`

**Comment by jasonwilliams200OK** [comment]
> You'll note that the text in the instructions ..

Which one? See https://github.com/dotnet/coreclr/blob/b23b65a/Documentation/install/get-dotnetcore-dnx-windows.md#installing-dnvm

**Comment by blackdwarf** [comment]
My bad, I will assing this issue to myself and fix. :)

**Comment by axefrog** [comment]
All good, thanks for the fast responses.

**Comment by blackdwarf** [comment]
This is fixed now, so closing the issue.
