### ISSUE TITLE
Helix tests should run against packages from current build

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#11352]
Today, a Helix test run will run against packages from the most recent auto-update PR (i.e. not from the current build). They should instead run against packages from the current build, which should be restored from Azure.

**Comment by wtgodbe** [comment]
CC @gkhanna79

**Comment by wtgodbe** [comment]
Another solution would be to wait until the publish step finishes, then in the test build step, do a global find/replace in the repo to replace old package versions with the new version - this would circumvent the problem of needing an up-to-date project.lock.json file, but would make the builds slower

**Comment by wtgodbe** [comment]
Note also that this solution will be a stopgap until we can build tests on Linux, at which time we won't need to build tests against packages anymore.

**Comment by wtgodbe** [comment]
Actually, even better could be to only do the find/replace in build_against_packages_dependencies\project.lock.json - I could create an msbuild file that $(CoreClrPackageVersion) with 2.0.0-preview2-(officialbuildid). That way we could still restore from Azure blobs, and wouldn't need to wait for the publish step to finish (so the builds wouln't be any longer).

**Comment by gkhanna79** [comment]
@wtgodbe How is this coming along?

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/11897 fixes this
