### ISSUE TITLE
simple C# program prints incorrect value on some Windows 7 systems 

### ISSUE THREAD

**Issue by dmh2000** [dotnet/coreclr#11365]
using System;
    
    /*
     summary: on some Windows 7 systems,
              this program prints the wrong value it is configured as an 'x86' build in visual studio
              On all systems tested it prints the correct value if it is configured as an 'x64' build in visual studio OR
              if it is run using the Visual Studio debugger
    
              built using Visual Studio 2015 with update 3 on Windows 10 Pro
              The incorrect print only occurs on some windows 7 systems. Others work correctly. 
              We have not found a correlation on which machines work and which don't. Installing
              .Net 4.6.2 did not help on the offending machines
    
              The error also occurs depending on how many values are in the array. see comments.

    */        
    namespace crc
    {
        class Crc
        {
        //====================
        // 16 bit CRC TABLE
        //====================
            public static UInt16[] CCITTcrc16_table =
            {
                // in 32 bit build, delete the last word, 0x329b and the output is correct '0'
                // leave it in and the output is incorrect, 'e0'
                0x0000, 0x1189, 0x2312, 0x329b
             };
        }
    
        class Program
        {
    
            static void Main(string[] args)
            {
                // IF THE BUILD PROPERTY SPECIFIES 'x86' or 'prefer 32bit' AND runing from command line
                //     on some systems,  this prints correct  value '0'
                //     on other systems, this prints incorrect value 'e0'
                // IF THE BUILD PROPERTY is 'x64' OR executing 'x86' version in visual studio debugger
                //     it works correctly on all systems
                Console.WriteLine(Crc.CCITTcrc16_table[0].ToString("x"));
            }
        }
    }
[crc32.il.txt](https://github.com/dotnet/coreclr/files/974115/crc32.il.txt)
[crc64.il.txt](https://github.com/dotnet/coreclr/files/974114/crc64.il.txt)

**Comment by danmosemsft** [comment]
code gen?

**Comment by RussKeldorph** [comment]
@rhadley since this appears to be .NET instead of .NET Core.

@dotnet/jit-contrib Does this ring a bell?

**Comment by RussKeldorph** [comment]
@russellhadley  I mean...ugh.

Sounds like something JIT32-specific.

**Comment by russellhadley** [comment]
@briansull is taking a look at the repro.

**Comment by briansull** [comment]
I ran this using Windows 7 and Visual Studio 2015 SP3
with target release/x86 and the program produced the expected result.

Product version of the clrjit.dll is 4.6.1076.0

Perhaps there was some software , an obfuscator or profiler plugin that causes the problem on "some" of the customers Windows 7 systems.

**Comment by russellhadley** [comment]
@briansull how does the posted il compare with what you produced?

**Comment by briansull** [comment]
Looks pretty much the same.  In their case they seem to have posted the Debug IL rather than the Release IL.

**Comment by dmh2000** [comment]
We don't have an obfuscator or any plugins installed on the build system.
Plain vs2015 .Yes The build was a debug build.  However there is a lot of
our corporate IT things on the win7 systems. Maybe something there. But
using x64 fixes it for us.

**Comment by RussKeldorph** [comment]
@dmh2000 I'm afraid we'll need more clues about how to reproduce this before we can help.  Perhaps you can find some key difference between the systems where this repros and those where it doesn't.  Also, note that since this is a problem with the .NET Framework and not .NET Core (as far as we can tell), this should be reported either via the Visual Studio IDE's feedback link or at http://connect.microsoft.com.

**Comment by dmh2000** [comment]
I'll see if I can find something

**Comment by mikedn** [comment]
Antivirus? Someone reported a somewhat similar problem (involves array initialization) via Gitter: https://gitter.im/dotnet/coreclr?at=58ff3f68cfec91927272486c

**Comment by briansull** [comment]
Jeff Cyr @JeffCyr Apr 25 06:35
I just confirmed that the issue was caused by Cylance... wow. Always blame the antivirus first!

**Comment by JeffCyr** [comment]
This sure looks like the same Cylance issue, we isolated the problem to cylance overwriting the first index of the first declared array initializer to 0xE0.

**Comment by dmh2000** [comment]
thanks for looking into this. i verified that the affected systems had Cylance on them. you can close this issue

**Comment by RussKeldorph** [comment]
@dmh2000 Great to hear!  Thanks for following up.
