### ISSUE TITLE
Runtime should recognize IsByRefLike attribute and treat the types that have it as ref-like

### ISSUE THREAD

**Issue by VSadov** [dotnet/coreclr#11371]
The runtime already has some special treatment for ref-like types:

https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=IsByRefLike&type=

It makes sense that in addition to the hardcoded ref-like types, the types decorated with IsByRefLike are also treated in the same way.

==

This is related to:   
https://github.com/dotnet/coreclr/pull/11369
Also discussed in:   
https://github.com/dotnet/corefx/issues/19212

**Comment by VSadov** [comment]
CC: @jkotas

**Comment by gkhanna79** [comment]
@VSadov Is this for 2.0?

**Comment by VSadov** [comment]
No, definitely not 2.0
