### ISSUE TITLE
cleanup BCLDebug

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#11389]
Is this the debug tracing mechanism we want corelib code to use long term? CoreRT uses Debug.xx exclusively, CoreCLR corelib uses Debug.xx in most cases but BCLDebug.xx in some. They need to be reconciled.

BCLDebug has some other features: categories, verbosity, registry configuration.

**Comment by jkotas** [comment]
> Is this the debug tracing mechanism we want corelib code to use long term? 

No. It should be deleted.

**Comment by danmosemsft** [comment]
Do you want everything to just use Debug.Log, etc? With no filtering, disabling, ..? Or you want to recreate something like BCLDebug?

I don't know whether any of the existing uses would fire so much that Debug.Log would be spammy.

**Comment by jkotas** [comment]
There are a very few classes where BCLDebug.Log is used, and I do not think anybody used that logging for anything in like last 10 years. I think it is fine just to delete it. 

Or if you see a good reason to keep it (I do not) - change it to per-class Log method that is `[Condition("DEBUG")]` and does nothing, that the developer can instrument with printf in debug build.

CoreLib is no different from CoreFX. I do not think anything in CoreFX has logging like this either. It suggests that it is not very useful.

**Comment by danmosemsft** [comment]
OK. Easy up for grabs change.
