### ISSUE TITLE
Jit: simplify chain of gc - nogc - gc casts from span ctor

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#11390]
If a fixed pointer is used to construct a span we can see extra register shuffles as a value is cast in and out of GC.

```
       488B442428           mov      rax, bword ptr [rsp+28H]
       488BF0               mov      rsi, rax
       488BC6               mov      rax, rsi
       488BF0               mov      rsi, rax
```

See notes and source code in dotnet/corefxlab#1479.

**Comment by mikedn** [comment]
That code is really funny and it would be nice to see it fix. But then register to register moves are cheap so perhaps this isn't super important?

**Comment by AndyAyersMS** [comment]
Agree it may not be super important, but if the IL pattern for pinning really has changed recently it might bump up the priority some, and if the various `Unsafe` methods get popular, it might bump it up some more.

**Comment by ahsonkhan** [comment]
> If a fixed pointer is used to construct a span we can see extra register shuffles as a value is cast in and out of GC.

The extra register shuffles appears when constructing a span out of an array as well (maybe caused by the stopwatch).

```C#
Stopwatch sw = new Stopwatch();
var a = new int[10000];
sw.Restart();
Span<int> span = new Span<int>(a);
sw.Stop();
return span;
```

            Span<int> span = new Span<int>(a);
00007FFCC6E82645  lea         rcx,[rbx+10h]  
00007FFCC6E82649  mov         rbx,rcx  
00007FFCC6E8264C  mov         rcx,rbx  
00007FFCC6E8264F  mov         rbx,rcx  
00007FFCC6E82652  mov         ebp,2710h

**Comment by AndyAyersMS** [comment]
Seems a bit clunky to get at this one. 

Morph notices a cast out of GC and introduces a comma temp assign to hold the result. If this comma is under a regular assign we now have a short lifetime temp that wasn't needed, and this extra temp allows RA the freedom to shuffle. So in morph post pass we could look for
```
assign(local, comma(assign(temp, cast(...)), temp)
```
and optimized to
```
assign(local, cast(...))
```
but we'd need to know that the temp was otherwise unused to avoid having to duplicate the cast.

Recent example from the repro above, where we initialize a span from a locally created array:
```asm
       E86DD6365F           call     CORINFO_HELP_NEWARR_1_DIRECT
       4889442428           mov      gword ptr [rsp+28H], rax    // [rsp+28H] is the untracked pinned local
       488B442428           mov      rax, gword ptr [rsp+28H]
       83780800             cmp      dword ptr [rax+8], 0        // unnecessary length check
       7504                 jne      SHORT G_M15213_IG03
       33C0                 xor      rax, rax
       EB1A                 jmp      SHORT G_M15213_IG04

G_M15213_IG03:
       488B442428           mov      rax, gword ptr [rsp+28H]
       83780800             cmp      dword ptr [rax+8], 0        // unnecessary bounds check
       7629                 jbe      SHORT G_M15213_IG06
       488B442428           mov      rax, gword ptr [rsp+28H]    // pinned local array
       4883C010             add      rax, 16
       488BD0               mov      rdx, rax                    // move to the comma temp
       488BC2               mov      rax, rdx                    // then to the local

G_M15213_IG04:
       488BD0               mov      rdx, rax
       488BC2               mov      rax, rdx
```
We don't track pinned locals in SSA so we end up with some redundant checks, eliminating these would get rid of the join at IG04 and perhaps the second pair of moves. Wondering if perhaps pinned locals could be put into SSA, thought that might open us up to other issues.

**Comment by AndyAyersMS** [comment]
Instead of hacking the upstream IR to try and game allocation, I looked into decisions made by the allocator. Here there are 3 intervals:
```
Interval  1: (V01) RefPositions {#34@50 #44@76 #46@83} physReg:NA Preferences=[allInt] RelatedInterval <L5>[0000028FCAB3FFD0]
Interval  5: (V08) (struct) RefPositions {#47@84 #48@89} physReg:NA Preferences=[allInt] RelatedInterval <L3>[0000028FCAB3FF20]
Interval  6: (V09) RefPositions {#42@72 #43@75} physReg:NA Preferences=[allInt] RelatedInterval <L1>[0000028FCAB3FE70]
```
and we are looking at why interval 6 (i6) which is the cast temp ends up in RDX, while interval 1 ends up in RAX.

All the logic discussed below is in `tryAllocateFreeReg`.

When considering interval i6 at 42, the allocator first sees that it has related i1. The next ref positions for i1 look like a copy to i1's own related interval i5, so the allocator "forwards" this latter interval as the related interval to consider when considering i6.

There is no strong preference for either i6 or i5 so the allocator examines the various choices. RAX looks good initially but is supplanted by RDX as RAX is "assigned" (to i1 as it turns out). So allocator chooses RDX for i6. This happens even if you disable the "useAssignedReg" logic as not only does i1 remember that it was in RAX, RAX also remembers that it held i1.

Then moving to i1 at 44, the allocator sees i1 was previously assigned RAX and it is still available so it uses it for i1.

Then moving to i5 at 47 RDX again wins. So we see these back to back moves.

It seems like the forwarding through "copy-like" related interval with a strong preference to its related interval is part of the problem here as we forgo eliminating a nearby copy to try and possibly eliminate a later one. In this case we fail to eliminate either one.

**Comment by AndyAyersMS** [comment]
With just a small tweak to the related interval forwarding, I get this code:
```asm
G_M15213_IG03:
       488B442428           mov      rax, gword ptr [rsp+28H]
       83780800             cmp      dword ptr [rax+8], 0
       761D                 jbe      SHORT G_M15213_IG06
       488B442428           mov      rax, gword ptr [rsp+28H]
       4883C010             add      rax, 16

G_M15213_IG04:
       BA10270000           mov      edx, 0x2710
       488906               mov      bword ptr [rsi], rax
       895608               mov      dword ptr [rsi+8], edx
       488BC6               mov      rax, rsi
```
and magically all those moves are gone. We still do a back-and-forth dance with the pinned slot, but that's not an allocator issue.

Looking at what this does a bit more broadly....

**Comment by AndyAyersMS** [comment]
I'm going to close this as this particular issue given the fix in #16028. 

Note there are other cases where we can still see chains of shuffling moves and these come from other parts of the preferencing heuristic.

**Comment by ahsonkhan** [comment]
I tested on the latest runtime framework version (2.1.0-preview3-26319-04) and still observe the difference in disassembly between the two Span ctors:
![image](https://user-images.githubusercontent.com/6527137/37632574-18d6631e-2bac-11e8-9545-e4f5597f9396.png)

**Comment by AndyAyersMS** [comment]
Hmm, is the left one the fixed ctor and the right one the array ctor?

**Comment by ahsonkhan** [comment]
>Hmm, is the left one the fixed ctor and the right one the array ctor?

No, the other away around. Edited the post above.

Array ctor (red) vs. Pointer ctor (green)

**Comment by AndyAyersMS** [comment]
I'll take another look, but the preferencing code in the allocator is pretty touchy. So improving this for 2.1 is a long shot.

But we can at least see where and why it reverted or whether I fooled myself into thinking I had fixed it.
