### ISSUE TITLE
netcoreapp2.0 cannot reference netstandard2.0 in VS2017 preview

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/coreclr#11391]
If I build from command line it works.

But from latest vs2017 preview I get:
...project.... targets '.NETStandard,Version=v2.0'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v2.0'.

Is the a workaround for now?

**Comment by watashiSHUN** [comment]
when you say you can build it on the command line, you mean you are using `dotnet cli`? ( in my case running `dotnet run`  with version `2.0.0-preview2-005905` on this project is successful)

But I also got a similar error while trying to build `.NetStandard2.0` in VS2017, please see this [stackoverflow question](http://stackoverflow.com/questions/43771446/netframework4-6-1-reference-a-classlib-targetting-netstandard2-0/43772580?noredirect=1#comment74595635_43772580)...

**Comment by danmosemsft** [comment]
@terrajobst is it expected to work in this version?

**Comment by terrajobst** [comment]
Which version of VS 2017 are you using? Help | About | Copy Info. This will work with the build we give out at Build.

**Comment by karelz** [comment]
BTW: It doesn't look like it belongs into CoreCLR repo ...

cc @weshaggard @ericstj

**Comment by NinoFloris** [comment]
It's the same for omnisharp

```
        Update project: Roadrunner.Host.FunctionalTests
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Project '/Users/nfloris/Projects/Project/Project.csproj' targets '.NETStandard,Version=v2.0'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v2.0'.
``` 

it does compile, restore, test etc though

**Comment by ericstj** [comment]
Agree with @terrajobst, problem appears to be the VS setup.
Issues on project system should be filed in https://github.com/dotnet/project-system.

**Comment by NinoFloris** [comment]
Doesn't VS also use msbuild?

**Comment by karldodd** [comment]
Same problem for me here. I am using OmniSharp in VSCode.

I guess anyone in charge can move this issue to https://github.com/dotnet/project-system ?

**Comment by karelz** [comment]
This issue was moved to dotnet/project-system#2192
