### ISSUE TITLE
Failed to run "git clean -xdf" due to error Filename too long

### ISSUE THREAD

**Issue by KarenHuang2016** [dotnet/coreclr#11442]
When we try to clean coreclr source repository. it failed due to error "Filename too long". We must delete the file manually. Could you please help to take a look at this? Thanks!

1. We've cloned coreclr to D:\CoreCLR\src and built it successfully before.
2. cd D:\coreclr\src
3. git reset --hard
HEAD is now at bae3ded Reenable MapViewOfFile PAL test1 (#11393)
4. git clean -xdf
Removing Tools/
Removing bin/
Removing binclash.log
Removing init-tools.log
Removing packages/runtime.debian.8-x64.Microsoft.Private.CoreFx.NETCoreApp/4.4.0-preview2-25303-04/sources/bin/obj/AnyOS.AnyCPU.Release/Microsoft.CSharp
...... 
Removing tests/src/JIT/config/benchmark/project.lock.json
Removing tests/src/TestWrappersConfig/project.lock.json
Removing tests/src/performance/project.lock.json
**warning: Could not stat path 'packages/runtime.ubuntu.16.10-x64.Microsoft.Private.CoreFx.NETCoreApp/4.4.0-preview2-25303-04/sources/bin/obj/AnyOS.AnyCPU.Release/System.Runtime.InteropServices.WindowsRuntime/netcoreapp/System.Runtime.InteropServices.WindowsRuntime.notsupported.cs': Filename too long**

**Comment by danmosemsft** [comment]
@weshaggard it appears we have exceeded max path when cloned almost at the root..! Where are the "notsupported.cs" files generated from? Perhaps those can be shorter.

`d:\CoreCLR\src\packages/runtime.ubuntu.16.10-x64.Microsoft.Private.CoreFx.NETCoreApp/4.4.0-preview2-25303-04/sources/bin/obj/AnyOS.AnyCPU.Release/System.Runtime.InteropServices.WindowsRuntime/netcoreapp/System.Runtime.InteropServices.WindowsRuntime.notsupported.cs` is 264 characters.

**Comment by weshaggard** [comment]
We don't generate that file it is in the package. This package contains a copy of all the source files. @ericstj is there a way to tell nuget restore to exclude these files if as they aren't needed in most cases?

**Comment by RussKeldorph** [comment]
@karelz I could maybe understand this not blocking 2.0, but this should not be tolerated for long as it's a huge pain.  Can we at least agree to fix this in 2.1?  Along with fixing the existing absurdly long paths, there should be a test or build step or something that guarantees the Windows MAX_PATH limit won't be exceeded for a root path length of at most N characters, for some reasonable value of N.  As long as everyone stays under N, they won't have problems.

**Comment by karelz** [comment]
If it bothers us (i.e. we and community members hit it on regular basis), I agree we should tackle it rather sooner than later. @weshaggard @mellinoe thoughts?

**Comment by mellinoe** [comment]
This sounds very likely to happen, so we should try to fix it, I think. I'm not sure if the path in this "sources" folder is significant, but at the very least we should be able to make the file name shorter. "System.Runtime.InteropServices.WindowsRuntime.notsupported.cs" is pretty long just by itself.

**Comment by ericstj** [comment]
> @ericstj is there a way to tell nuget restore to exclude these files if as they aren't needed in most cases?

No, but if we have consumers of the Private.CoreFx packages other than core-setup maybe we should make them use the transport package infra that @chcosta created.  That way we'd have a different package that only had binaries.

I'm fine changing the name of the notsupported files, but I found that wasn't enough and was just the first long path that was hit.

**Comment by eerhardt** [comment]
We solved this in other repos by telling folks to set:

`git config --system core.longpaths true`

See https://github.com/dotnet/cli/issues/4182#issuecomment-277901627

**Comment by KarenHuang2016** [comment]
“git config --system core.longpaths true ” can resolve this issue. Thank you very much!
