### ISSUE TITLE
Test `_hfa_main_testC_hfa_nd2C_d` failing on x64 under GCStress=0xC and JITStress=1

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#11447]
e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_jitstress1/lastCompletedBuild/testReport/JIT_jit64/_hfa_main_testC_hfa_nd2C_d_hfa_nd2C_d_/_hfa_main_testC_hfa_nd2C_d_hfa_nd2C_d_cmd/

From the JIT dumps, this appears to be due to misplacement of a call to the PInvoke frame initialization IR that attempts to read the stub parameter from `r10` after it has been trashed.

cc @briansull

**Comment by RussKeldorph** [comment]
@pgavlin Should this be closed?

**Comment by pgavlin** [comment]
Yes.
