### ISSUE TITLE
Allow AppDomain.SetData more than once

### ISSUE THREAD

**Issue by bricelam** [dotnet/coreclr#11453]
There seems to be [an arbitrary limitation](https://github.com/dotnet/coreclr/blob/release/2.0.0/src/mscorlib/src/System/AppDomain.cs#L675) on Core CLR that prevents you from calling `AppDomain.SetData` more than once for the same name.

This limitation doesn't exist on .NET Framework.

We use `AppDomain.SetData` in our tests to check our usage of `AppDomain.GetData`. We typically clean up after the test by passing `null`, but this throws.

We discovered this by attempting to run our .NET Framework 4.6.1 test code on .NET Core App 2.0.

**Comment by gkhanna79** [comment]
CC @danmosemsft

**Comment by danmosemsft** [comment]
@AlexGhiondea any context on why this code exists? It looks like it precedes github: https://referencesource.microsoft.com/#mscorlib/system/appdomain.cs,2444

Unless there's a good reason, we should fix this. If you don't have cycles, LMK and I'll find someone.

**Comment by danmosemsft** [comment]
@sepidehMS can you do this one for 5/10 ?

**Comment by sepidehMS** [comment]
@danmosemsft I can't say for sure I will finish it for 5/10 with two other tasks I need to finish, but I certainly can spend time on this for investigation.

**Comment by danmosemsft** [comment]
OK!

**Comment by AlexGhiondea** [comment]
@sepidehMS the fix for this is to do something like what I have in this branch: https://github.com/AlexGhiondea/coreclr/tree/MakeSetData

**Comment by AlexGhiondea** [comment]
I have a PR for this here: https://github.com/dotnet/coreclr/pull/11496

**Comment by danmosemsft** [comment]
@ViktorHofer if @sepidehMS doesn't have time to do this today could you please get the PR in.

**Comment by AlexGhiondea** [comment]
@danmosemsft the PR is approved -- I am just waiting for CI to complete

**Comment by danmosemsft** [comment]
Great - thanks both of you.

**Comment by danmosemsft** [comment]
Fixed right @alexghiondea

**Comment by jkotas** [comment]
We need regression test in corefx

**Comment by karelz** [comment]
@AlexGhiondea should we move the test part into CoreFX? (we don't have to if it is easier this way)

**Comment by stephentoub** [comment]
I added a test here:
https://github.com/dotnet/corefx/issues/19657
