### ISSUE TITLE
Port MDBG tests to CoreCLR

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#1146]
When we have MDBG online, we will need to bring the tests over as well

**Comment by ZhichengZhu** [comment]
We have already starting working on that and ported  some of the key debugger tests for x-plat. The reason we didn't publish mdbg and those mdbg tests right now is because there is a MCG issue which haven't be resolved by interop team .

**Comment by tzwlai** [comment]
We are in the process of open-sourcing the repo containing MDbg and all of our tests, but it may not make it by RTM.

**Comment by lt72** [comment]
Completed
