### ISSUE TITLE
Add runtest support for MDBG tests

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#1147]
MDBG is run differently from the rest of the tests, so we need to create specific cmd files for MDBG scripts.

1. MDBG tests are run based on run script files, not source files
2. We need to have a way to specify external additional scripts that will set COMPLUS variables for alt jits
3. We need to load the correct extensions for running tests under corerun, setting environment variables, and running the scripts

**Comment by ZhichengZhu** [comment]
Hi adiaaida,
I'll answer your question one by one.
1. Basically for mdbg, script files are the collection of mdbg commands which should be run during the tests. For the source file,  do you mean the debuggee source file or a source that once it gets compiled, it can work like a debugger extension which contains testing steps like unit test?
2. In mdbg we do have an extension which can set the debuggee environment variable. In you use this command to set COMPLUS altjit variable, I believe that will work.
3. Mdbg do have the right extension, that can be used to for corerun setting environment variables, and running scripts. This is how we do our daily mdbg tests running.

**Comment by tzwlai** [comment]
Closing this after checking with @adiaaida.
