### ISSUE TITLE
Uri.IsWellFormedUriString() returns false for a URL which is correct

### ISSUE THREAD

**Issue by flo8** [dotnet/coreclr#11487]
I have a C# (.Net Core 1.1) app that needs to check if a URL is valid. I used the Uri.IsWellFormedUriString() which works pretty well but have a doubt about this one below which **returns false**. It seems to me that the URL is perfectly valid?

`Uri.IsWellFormedUriString("http://www.test.com/search/Le+Venezuela+b%C3%A9n%C3%A9ficie+d%27importantes+ressources+naturelles+%3A+p%C3%A9trole%2C+gaz%2C+mines", UriKind.Absolute)`

I used the very same URL with the PHP function below which says the URL is correctly formatted:
`function filter_var($url, FILTER_VALIDATE_URL)`

If I refer to the [RFC3986](https://tools.ietf.org/html/rfc3986)  it seems this URL is correct. Am I missing something here?

**Comment by mazong1123** [comment]
I think you'd better ask this question on [corefx repo](https://github.com/dotnet/corefx/issues) as this method was [implemented there](https://github.com/dotnet/corefx/blob/7df6b74cc4aeebc86e76b5c7901a59fa7fa793f6/src/System.Private.Uri/src/System/UriExt.cs#L365).

**Comment by flo8** [comment]
Thanks @mazong1123 that's what I did:
https://github.com/dotnet/corefx/issues/19630
Closing this one.
