### ISSUE TITLE
Load Types from unreferenced dlls Or dlls in bin

### ISSUE THREAD

**Issue by smartouss** [dotnet/coreclr#11491]
Hi!!

I have .net core web api that call another web api, so i have a factory class that create proxies objects at run time.

I divided the controllers into separate projects and i add them as part at startup.

My problem is that some proxies are not referenced in the project that have the startup class, and i'm trying to create the object using Type.GetType method but im getting an error that could not find type.

Is there a way to add dlls at run time, or add reference to them?

**Comment by gkhanna79** [comment]
You will need to use AssemblyLoadContext if the assemblies in question are not part of the application (https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md).
