### ISSUE TITLE
Debugging API

### ISSUE THREAD

**Issue by tonerdo** [dotnet/coreclr#11490]
What's the status of an X-Plat debugging api for .NET Core. If there's one how does it compare to the [ICorDebug interface](https://msdn.microsoft.com/en-us/library/ms230588(v=vs.110).aspx) for the full .NET Framework?  

How is it utilized? I don't see ICorDebug exported in [vm/ecalllist.h](https://github.com/dotnet/coreclr/blob/master/src/vm/ecalllist.h) so I'm guessing `MethodImplOptions.InternalCall` is off the table.

Apologies if this is a duplicate, I couldn't find an existing issue to answer my question

-Toni

**Comment by janvorli** [comment]
CC: @noahfalk - I think you have described the details somewhere, but I cannot find it.

**Comment by noahfalk** [comment]
@mikem8361 

The x-plat debugging API is ICorDebug. It works well minus a few features that haven't been ported yet. This is what VSCode uses for example when debugging on Linux and mac.

I wasn't sure what you were eluding to with MethodImplOptions.InternalCall? ICorDebug is implemented in mscordbi.dll and meant to be loaded into the debugger which process which is seperate from the debuggee process that loaded coreclr.dll. The runtime doesn't need to load ICorDebug to execute IL, thus there is no need for the runtime to have any ecalls defined for it.

**Comment by tsolarin** [comment]
@noahfalk thanks for the answer, that clarifies a lot. Any documentation on those few features that haven't been ported over?

**Comment by noahfalk** [comment]
Np, glad to help.
@mikem8361 would know best what that gap is, off the top of my head I think it might be managed return value, exception interception, and one uncommon corner case for stackwalking on dump debugging.

**Comment by lt72** [comment]
@mikem8361: can you provide an update and close the issue?

**Comment by lt72** [comment]
We will be providing the docs, although I am moving this to future because it is not a blocker for 2.1.
