### ISSUE TITLE
Time for .NET for web?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/coreclr#1150]
Hi,

Is it time to implement a dot net version for web, based on JS or TypeScript?

It would be great if we could start implement web client apps with C#, eventually implementing XAML as well and getting rid of HTML and CSS.
Now this might be not just a dream with Roslyn handy.

**Comment by OtherCrashOverride** [comment]
It was already tried long ago: it was called Silverlight.

**Comment by xied75** [comment]
@OtherCrashOverride Silverlight is a plug-in to browsers which holds a small runtime similar to coreclr today, it is 'native' to each browser (platform), and when Apple made it clear that it will never let it happen to Safari, MS un-plugged the plug.

What @weitzhandler suggested is a coreclr implemented in JS/TypeScript, so that all browser will support it from day one.

This maybe worth a look, http://tjanczuk.github.io/edge/#/

**Comment by weitzhandler** [comment]
@OtherCrashOverride, I actually meant precisely that, and not only that, with the aid of Apache Cordova such a port will make .NET the world widest technology, able to run on [any](https://wiki.apache.org/cordova/PlatformSupport) device as a native app.
And the reason I didn't mention the word Silverlight, @xied75 said what I was just about to say. Silverlight is an installable plugin, as opposed to a client library working natively on the browser.
I know there are some projects going on (see below), but none official. Some are paid, some are restricted licenses etc, but nothing out the box under the framework of [dotnet](github.com/dotnet).
I believe, that it's only the [coreclr]([dotnet](github.com/dotnet/coreclr) project that needs to be ported to TypeScript/JavaScript, the [corefx](github.com/dotnet/corefx) can probably be executed ontop of the local JS compilation of the core.
References:
[JSIL](https://github.com/sq/JSIL)
[Netjs](https://github.com/praeclarum/Netjs)
[Fayde](https://github.com/wsick/Fayde)

**Comment by RichiCoder1** [comment]
Far more relevant at this point would be tracking the [Web Assembly](https://github.com/WebAssembly/design) proposal, and then working with either the llilc team or yourself to compile down and run on that.

**Comment by karelz** [comment]
Closing as nebulous issue - see https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#when-we-close-issues
