### ISSUE TITLE
Timing issue in some baseservices tests

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#11503]
There is a timing issue in tests when multiple tests share a test binary via the `<CLRTestProjectToRun>` property and when the tests are run with crossgen (`r2r` jobs).

I believe the problem is that even though the `RunCrossGen` logic attempts to prevent two projects from `crossgen`ing the same binary at the same time, one project can have [moved the binary](https://github.com/dotnet/coreclr/blob/c9f469e5fc99a498f46bd2d60fb198b7f7f1c22b/tests/src/CLRTest.CrossGen.targets#L48) while another project is attempting to execute it, resulting in the "not found" message below.  If we must support this "binary reuse" mechanism in the test harness, rather than locking, I'd recommend a safer mechanism that only writes to the project's own folder, copying if necessary.  I realize that has its own complications if a binary depends on its containing folder, but perhaps this is a lesser evil.

Incidentally, while you're in here, consider addressing #11502 as well.

Example of failures:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_pri1r2r_tst/1705/#showFailuresLink

```
MESSAGE:
BEGIN EXECUTION export CDPATH=. /bin/sh -c ../CheckAddInt/CheckAddInt.sh BEGIN EXECUTION /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_pri1r2r_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun CheckAddInt.exe /start:0 /add:100 Managed assembly not found: No such file or directory Expected: 100 Actual: 255 END EXECUTION - FAILED Expected: 0 Actual: 1 END EXECUTION - FAILED
+++++++++++++++++++
STACK TRACE:
```

**Comment by RussKeldorph** [comment]
@gkhanna79 @wtgodbe FYI

**Comment by gkhanna79** [comment]
This failure is not present in https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fr2r~2Fcli~2F/build/20170509.02.

@RussKeldorph Is there something different in CI to trigger this? how consistently does this repro?

**Comment by wtgodbe** [comment]
This is because Mission Control runs the Xunit wrappers, which run tests serially (Mission Control does run several Xunit wrappers at once, but the tests within each wrapper run serially). CI runs runtest.sh, which runs tests in parallel.

**Comment by RussKeldorph** [comment]
@ghanna79 @wtgobe speculated that the tests may be running serially in Helix, which would prevent this from happening.  We also don't seem to see this in the Windows Jenkins jobs, so perhaps msbuild is serializing the projects for some reason.  We only seem to see this on Jenkins Unix, where presumably the test runner doesn't do any special synchronization.

**Comment by wtgodbe** [comment]
@RussKeldorph Windows Jenkins jobs also run the Xunit wrappers

**Comment by RussKeldorph** [comment]
@gkhanna79 

> how consistently does this repro?

Pretty much every Unix R2R job as far as I can tell.

**Comment by wtgodbe** [comment]
@RussKeldorph Unix jobs in Helix run through the Xunit Wrappers

**Comment by wtgodbe** [comment]
@gkhanna79 what do you think is the best course of action here? What's happening is that, while one test is modifying {test_name}.exe, another test tries to CoreRun {test_name}.exe while it's being renamed to {test_name}.org. I agree with Russ' assessment in https://github.com/dotnet/coreclr/issues/11502 that we should avoid removing any state from the test bin folder

**Comment by gkhanna79** [comment]
What is your proposal @wtgodbe ?

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/12064 fixed this

**Comment by RussKeldorph** [comment]
@wtgodbe Are you sure this is fixed?  I'm seeing the same failures: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_pri1r2r_tst/1957/

**Comment by wtgodbe** [comment]
Huh. Right you are, I'll reopen my old PR & see if I can get it working.
