### ISSUE TITLE
[Local GC] Enable feature: GC_PROFILING

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#11515]
Related to https://github.com/dotnet/coreclr/issues/8268. Some of this work has been done already but there is additional work to be done to enable a profiler to walk the heap - in particular, `ScanContext` refers to VM internals when traversing the heap.

**Comment by swgillespie** [comment]
Triage:

This is an important feature for 2.1, if only to prevent issues like https://github.com/dotnet/coreclr/pull/14777 and https://github.com/dotnet/coreclr/pull/14747 from occuring (though obviously the ideal shipping configuration is for profiling to work with a standalone GC).

**Comment by davmason** [comment]
Fixed in #19777
