### ISSUE TITLE
[Local GC] Enable feature: FEATURE_EVENT_TRACE

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#11514]
Related to https://github.com/dotnet/coreclr/issues/8268. This feature is not functional with a standalone GC - it will require changes to the `IGCToCLR` interface.

**Comment by swgillespie** [comment]
Triage:

This is critical to finish for 2.1. I am in the process of coming up with a strategy for this that I hope to begin putting into motion at the start of next week.

**Comment by swgillespie** [comment]
Implementation of this has started with https://github.com/dotnet/coreclr/pull/15873. For every event that the GC fires, we will need to convert it to a known event [(like this)](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/standalone-gc-eventing.md#concrete-example-porting-a-single-known-event-to-igctoclreventsink). More concrete examples other than just the design doc will follow.

@davmason This will be the work that the two of us will need to split up. It looks like a lot but I believe that a large number of these events are unused and can be ignored. As soon as https://github.com/dotnet/coreclr/pull/15873 lands I will open up another PR that illustrates exactly what needs to be done to port one of these events to the new system (https://github.com/swgillespie/coreclr/compare/event-spec-foundation...swgillespie:event-spec-allocationtick). 

This commit in particular (https://github.com/swgillespie/coreclr/commit/2ce0008e1646ca1dfa726a1f63f6e5d0df79acb6) ports `GCAllocationTick_V3`, a particularly involved event, to the new scheme.

cc @sergiy-k @Maoni0 @lt72 

## GC keyword
* [ ] GCStart (GCStart, GCStart_V1, GCStart_V2)
* [ ] GCEnd (GCEnd, GCEnd_V1)
* [ ] GCRestartEEEnd (GCRestartEEEnd, GCRestartEEEnd_V1)
* [ ] GCHeapStats (GCHeapStats, GCHeapStats_V1)
* [ ] GCCreateSegment (GCCreateSegment, GCCreateSegment_V1)
* [ ] GCFreeSegment (GCFreeSegment, GCFreeSegment_V1)
* [ ] GCRestartEEBegin (GCRestartEEBegin, GCRestartEEBegin_V1)
* [ ] GCSuspendEEEnd (GCSuspendEEEnd, GCSuspendEEEnd_V1)
* [ ] GCSuspendEEBegin (GCSuspendEEBegin, GCSuspendEEBegin_V1)
* [ ] GCAllocationTick (GCAllocationTick, GCAllocationTick_V1, GCAllocationTick_V2, GCAllocationTick_V3)
* [ ] GCCreateConcurrentThread (GCCreateConcurrentThread, GCCreateConcurrentThread_V1)
* [ ] GCTerminateConcurrentThread (GCTerminateConcurrentThread, GCTerminateConcurrentThread_V1)
* [ ] GCFinalizersEnd (GCFinalizersEnd, GCFinalizersEnd_V1)
* [ ] GCFinalizersBegin (GCFinalizersBegin, GCFinalizersBegin_V1)
* [ ] GCMarkStackRoots
* [ ] GCMarkFinalizeQueueRoots
* [ ] GCMarkHandles
* [ ] GCMarkOlderGenerationRoots
* [ ] FinalizeObject
* [ ] PinObjectAtGCTime
* [ ] GCTriggered
* [ ] IncreaseMemoryPressure
* [ ] DecreaseMemoryPressure
* [ ] GCMarkWithType
* [ ] GCJoin_V2
* [ ] GCPerHeapHistory_V3
* [ ] GCGlobalHeapHistory_V2

## GCPrivate keyword
* [ ] GCDecision (GCDecision, GCDecision_V1)
* [ ] GCSettings (GCSettings, GCSettings_V1)
* [ ] GCOptimized (GCOptimized, GCOptimized_V1)
* [ ] GCPerHeapHistory (GCPerHeapHistory, GCPerHeapHistory_V1)
* [ ] GCGlobalHeapHistory (GCGlobalHeapHistory, GCGlobalHeapHistory_V1)
* [ ] GCJoin (GCJoin, GCJoin_V1)
* [ ] PrvGCMarkStackRoots (PrvGCMarkStackRoots, PrvGCMarkStackRoots_V1)
* [ ] PrvGCMarkFinalizeQueueRoots (PrvGCMarkFinalizeQueueRoots, PrvGCMarkFinalizeQueueRoots_V1)
* [ ] PrvGCMarkHandles (PrvGCMarkHandles, PrvGCMarkHandles_V1)
* [ ] PrvGCMarkCards (PrvGCMarkCards, PrvGCMarkCards_V1)
* [ ] BGCBegin
* [ ] BGC1stNonConEnd
* [ ] BGC1stConEnd
* [ ] BGC2ndNonConBegin
* [ ] BGC2ndNonConEnd
* [ ] BGC2ndConBegin
* [ ] BGC2ndConEnd
* [ ] BGCPlanEnd
* [ ] BGCSweepEnd
* [ ] BGCDrainMark
* [ ] BGCRevisit
* [ ] BGCOverflow
* [ ] BGCAllocWaitBegin
* [ ] BGCAllocWaitEnd
* [ ] GCFullNotify (GCFullNotify, GCFullNotify_V1)
* [ ] PinPlugAtGCTime


## GCHandle keyword
* [ ] SetGCHandle
* [ ] DestroyGCHandle

## GCHandlePrivate keyword
* [ ] SetGCHandle
* [ ] DestroyGCHandle

## GCHeapDump keyword
* [ ] GCBulkRootEdge
* [ ] GCBulkRootConditionalWeakTableElementEdge
* [ ] GCBulkNode
* [ ] GCBulkEdge
* [ ] GCBulkRootCCW
* [ ] GCBulkRCW
* [ ] GCBulkRootStaticVar

## GCSampledObjectAllocationHigh keyword
* [ ] GCSampledObjectAllocationHigh

## GCHeapSurvivalAndMovement keyword
* [ ] GCBulkSurvivingObjectRanges
* [ ] GCBulkMovedObjectRanges
* [ ] GCGenerationRange

## GCSampledObjectAllocationLow keyword
* [ ] GCSampledObjectAllocationLow

**Comment by swgillespie** [comment]
https://github.com/dotnet/coreclr/pull/15905

**Comment by davmason** [comment]
#16020 
#16120
