### ISSUE TITLE
[Local GC] Enable feature: FEATURE_APPDOMAIN_RESOURCE_MONITORING

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#11517]
When this feature is enabled, the GC references the system app domain directly and records resource usage information for it, which a standalone GC can't do.

**Comment by swgillespie** [comment]
Triage:

I don't believe that this feature can be tested with CoreCLR - as far as I am aware it is a .NET Framework-only feature. Even if it were to be implemented for 2.1, I can't think of any way to ensure that it works.

**Comment by swgillespie** [comment]
Moving out to Future since this feature isn't supported on CoreCLR.

**Comment by davidwrighton** [comment]
This feature isn't going to be supported on CoreCLR. Closing the issue.
