### ISSUE TITLE
Add CONTRIBUTING.md in the root

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/coreclr#1152]
Makes GitHub show a notice when someone makes a PR, similar to corefx: https://github.com/dotnet/corefx/blob/master/CONTRIBUTING.md

/cc @blackdwarf

**Comment by blackdwarf** [comment]
Hm, interesting idea. I'm fine with this. @richlander thougths?

**Comment by richlander** [comment]
Works.

I'd propose to make a direct copy of the other file to make them the same.

**Comment by sharwell** [comment]
I'd either move the file, or create a short file that redirects a reader to the one in documentation. Duplicating it means you have to keep them in sync, which in reality means eventually they will not be the same and no one will know which one is correct.

**Comment by sharwell** [comment]
Proposed file (links shown in brackets but I didn't actually add targets):

---

## Contributors

Interested in contributing to dotnet/coreclr? We hope so! Here's the fastest way to get started:

* [Get the code]
* [Sign the Contributor Agreement] (required if you want to propose code changes)
* [Join us on Gitter]

When you get the chance, head on over to our [documentation] folder and we'll bring you up to speed as quickly as we know how.

**Comment by richlander** [comment]
That's good. I like that better than the CoreFX one. We should specifically link to the developer guide, which then should link to the contributing guide. Good?

I think you misunderstood my poorly worded statement. I wasn't suggesting copying coreclr/Documentation/contributing.md to coreclr/CONTRIBUTING.md. I was suggesting making a copy of corefx/CONTRIBUTING.MD for coreclr. Still, I think that we should use the version you made for both repos. Thanks!

**Comment by BigBoneDaddy** [comment]
Good idea!

**Comment by akoeplinger** [comment]
This was done with https://github.com/dotnet/coreclr/pull/6386 ages ago :)
