### ISSUE TITLE
Compile failed on CentOS 7

### ISSUE THREAD

**Issue by micli** [dotnet/coreclr#11520]
When I compile the newest version coreclr on CentOS 7, It always failed recently with below error message:

/coreclr/Tools/sign.targets(70,5): error : obj/Linux.x64.Debug/System.Private.CoreLib/System.Private.CoreLib.dll: I/O error reading or writing PE file: Invalid argument [/coreclr/src/mscorlib/System.Private.CoreLib.csproj]

**Comment by janvorli** [comment]
@micli I have just tried to build the latest sources on my local CentOS 7 and it succeeded.
Can you please run "git clean -xdf" in the root directory of the coreclr to clear all the Tools, packages and bin sub-directories and try again?
