### ISSUE TITLE
[Arm64/Unix] Unhandled Exception: System.OverflowException

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#11525]
I am seeing the following tests fail with an unhandled overflow exception
```
JIT/Methodical/fp.exgen/10w5d_cs_d/10w5d_cs_d.sh
JIT/Methodical/fp.exgen/10w5d_cs_r/10w5d_cs_r.sh
```

```
Unhandled Exception: System.OverflowException: Value was either too large or too small for a UInt16.
   at System.Convert.ThrowUInt16OverflowException()
   at System.Convert.ToUInt16(Int32 value)
   at testout1.Func_0_1()
   at testout1.Func_0()
   at testout1.Main()
```

**Comment by sdmaclea** [comment]
cc @dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
@rartemev I am not seeing this failure on the recent bad6729 version.

**Comment by jashook** [comment]
@sdmaclea any update on this? These are still running green on windows.

**Comment by sdmaclea** [comment]
@jashook No update at the moment.  I will look at them again.  I think there is a lurking GC issue which is sometimes hit by these tests.

**Comment by sdmaclea** [comment]
This has not been reproduced for 1mo.
