### ISSUE TITLE
[Arm64] Test Failures with no output

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#11534]
Affected Tests

<pre>
readytorun\genericsload\callgenericctor\callgenericctor.cmd 
readytorun\generics\generics.cmd
readytorun\mainv1\mainv1.cmd
readytorun\mainv2\mainv2.cmd
GC\Stress\Framework\ReliabilityFramework\ReliabilityFramework.cmd
readytorun\genericsload\usegenericfield\usegenericfield.cmd
GC\Regressions\dev10bugs\536168\536168\536168.cmd
</pre>

Example Output
<pre>
15:32:24 TestID: usegenericfield.cmd_9789
15:32:24 Path  : readytorun/genericsload/usegenericfield/usegenericfield.cmd
15:32:24 
15:32:24 Started: Wed May 10 15:23:32 2017
15:32:24 Started: Wed May 10 15:23:32 2017
15:32:24 Output: TEST_CMD_LINE: readytorun\genericsload\usegenericfield> readytorun\genericsload\usegenericfield\usegenericfield.cmd 
15:32:24 No output was generated!
15:32:24 
</pre>

**Comment by jashook** [comment]
Note that these are regressions.

/cc @dotnet/arm64-contrib

**Comment by BruceForstall** [comment]
The only test that is still disabled is `GC\Regressions\dev10bugs\536168\536168\536168.cmd` -- it is an extremely memory/time intensive test, so is disabled as a long-running test.
