### ISSUE TITLE
CancellationToken.Register should take an Action<CancellationToken, object> delegate

### ISSUE THREAD

**Issue by AArnott** [dotnet/coreclr#11548]
I have to allocate a new delegate and closure in my `CancellationToken.Register` calls because I need an object *and* the `CancellationToken` itself:

```csharp
this.CancellationRegistration = cancellationToken.Register(
  state => ((TaskCompletionSource<Releaser>)state).TrySetCanceled(cancellationToken),
  this.TaskSource);
```

Yet it would seemingly be a simple thing for the invoker of my delegate to *also* provide a copy of the `CancellationToken` itself when calling my delegate so that I can avoid the cost of the closure and then reuse the delegate for all invocations:

```csharp
public CancellationTokenRegistration Register(
  Action<CancellationToken, object> callback,
  object state);
```

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#26377
