### ISSUE TITLE
dotnet build failed

### ISSUE THREAD

**Issue by Whomsonever** [dotnet/coreclr#11543]
I have just installed documentation in the VS 2017 Help Viewer and am attempting to complete the first C# Tutorial which is for a console application:
The initial instructions are : 
in a command window enter
dotnet new console   ( to which I had to add -all)                      .... this worked ok
dotnet restore                                                                             .... this worked ok
dotnet build                                                                                .... this failed as follows

WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\DSCClassResources\WindowsPackageCab\WindowsPackageCab.cs(225,99): error CS0117: 'Environment' does not contain a definition for 'GetFolderPath' [C:\Windows\System32\system32.csproj]
WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\DSCClassResources\WindowsPackageCab\WindowsPackageCab.cs(225,125): error CS0117: 'Environment' does not contain a definition for 'SpecialFolder' [C:\Windows\System32\system32.csproj]
WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\DSCClassResources\WindowsPackageCab\WindowsPackageCab.cs(232,88): error CS0117: 'Environment' does not contain a definition for 'GetFolderPath' [C:\Windows\System32\system32.csproj]
WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\DSCClassResources\WindowsPackageCab\WindowsPackageCab.cs(232,114): error CS0117: 'Environment' does not contain a definition for 'SpecialFolder' [C:\Windows\System32\system32.csproj]

Build FAILED.

WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\DSCClassResources\WindowsPackageCab\WindowsPackageCab.cs(225,99): error CS0117: 'Environment' does not contain a definition for 'GetFolderPath' [C:\Windows\System32\system32.csproj]
WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\DSCClassResources\WindowsPackageCab\WindowsPackageCab.cs(225,125): error CS0117: 'Environment' does not contain a definition for 'SpecialFolder' [C:\Windows\System32\system32.csproj]
WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\DSCClassResources\WindowsPackageCab\WindowsPackageCab.cs(232,88): error CS0117: 'Environment' does not contain a definition for 'GetFolderPath' [C:\Windows\System32\system32.csproj]
WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\DSCClassResources\WindowsPackageCab\WindowsPackageCab.cs(232,114): error CS0117: 'Environment' does not contain a definition for 'SpecialFolder' [C:\Windows\System32\system32.csproj]
    0 Warning(s)
    4 Error(s)

Can anyone please advise what I need to do to overcome this problem ?

Thanking you in anticipation.

**Comment by jkotas** [comment]
> dotnet new console
> dotnet restore
> dotnet build

Try to execute these steps in a new empty directory.

The error suggest that you have done them in c:\windows\system32 and unrelated powershell files under this directory are getting picked up by `dotnet build` causing the error. `dotnet build` will try to build everything that is under current directory by default.

**Comment by Whomsonever** [comment]
Dear JKotas,
Thank you for your prompt response, but I do not understand what to do.

I would agree that the first time I attempted this tutorial that I probably just opened a standard command prompt whereas the second time (with the errors shown above) I used a Developer Command Prompt for VS2017 as administrator.

Do I need to delete a folder in system32 or run a command to clean a folder or ?

Thank you

**Comment by jkotas** [comment]
Try this:

```
mkdir c:\HelloWorld
cd  c:\HelloWorld
dotnet new console
dotnet restore
dotnet build
```

**Comment by Whomsonever** [comment]
Dear JKotas,

Worked a treat !

Many thanks for the time you took to help and for your invaluable assistance.
