### ISSUE TITLE
What are the configuration / build details for the FreeBSD jenkins environment?

### ISSUE THREAD

**Issue by tony** [dotnet/coreclr#1154]
According to Jenkins, CoreCLR is building and testing in Debug and Release [1][2]

Currently I have not been able to build CoreCLR with debug due to LLDB failing during the lin process. (https://github.com/dotnet/coreclr/issues/1131, https://github.com/dotnet/coreclr/issues/940)

What is the FreeBSD version, build configuration settings, LLVM, Clang and LLDB versions that we're building against on these environments?

[1] http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_freebsd_debug/
[2] http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_freebsd_release/

**Comment by saper** [comment]
Jenkins scripts can be found in the https://github.com/dotnet/dotnet-ci repository.

`lldb` is not necessary to build CoreCLR on FreeBSD. On Jenkins we just do
[this](https://github.com/dotnet/dotnet-ci/blob/master/jobs/dotnet_coreclr_freebsd_debug/config.xml#L47):

````
./build.sh verbose debug && src/pal/tests/palsuite/runpaltests.sh \
    ${WORKSPACE}/bin/obj/FreeBSD.x64.Debug ${WORKSPACE}/bin/paltestout
````

**Comment by saper** [comment]
@tony Did you succeed? Are there any other issues open?

**Comment by tony** [comment]
@saper: Sorry for the delay. I was side-tracked.  I'm looking at this closer now.

**Comment by tony** [comment]
> Are there any other issues open?

Not on any of these subjects for this.

I am experiencing a build issue with ``/build.sh verbose debug``. I am going to follow up with a ticket.

**Comment by tony** [comment]
@saper : Greetings, thank you for that.

Here is how I was able to do it with clang 3.6 from ports:

```sh
./build.sh verbose debug clang3.6 
```

Tests:
```
./src/pal/tests/palsuite/runpaltests.sh  $PWD/bin/obj/FreeBSD.x64.Debug $PWD/bin/paltestout
```

I am going to update the docs accordingly. I'm also giving llvm another shot with the advice from the other thread. (https://github.com/dotnet/coreclr/issues/940#issuecomment-113450059)

**Comment by tony** [comment]
Thank you for the help @saper !
