### ISSUE TITLE
Implement Functional Tests for EventPipe

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#11567]
Make sure that there is appropriate regression testing for the EventPipe.

**Comment by brianrob** [comment]
@nategraf, you are working on this now, right?

**Comment by nategraf** [comment]
Yes, I'll have a couple more as part of https://github.com/dotnet/coreclr/pull/14772

**Comment by nategraf** [comment]
Two tests that should be included under this objective are one for SampleProfiler and one to confirm the functional status of end-to-end LLTng and ETW. The latter will be important when ETW and LTTng are placed behind the EventPipe and we need to confirm that code changes there do not sever that stream

**Comment by brianrob** [comment]
Great, thanks @nategraf.

**Comment by brianrob** [comment]
We now have a basic set of tests that are helping us to catch issues.  Closing.
