### ISSUE TITLE
Prevent 'Press any key to continue' in a .Net Core Console App

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/coreclr#11576]
When I debug my console app it closes automatically.  When I run w/o debugging I get:

![image](https://cloud.githubusercontent.com/assets/14079228/26017231/8476d04c-3736-11e7-93bd-ad59e4f32934.png)

How do I prevent this?

Thanks,
Mike D.

**Comment by karelz** [comment]
This is standard VS behavior for ages AFAIK. Not sure if there is any opt-out.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/project-system #2184](https://github.com/dotnet/project-system/issues/2184) via [**ZenHub**](https://www.zenhub.com/)

**Comment by spottedmahn** [comment]
I see, thanks @karelz
