### ISSUE TITLE
string.IndexOf not returning proper value when searching for an empty string

### ISSUE THREAD

**Issue by slozier** [dotnet/coreclr#11578]
string.IndexOf is not returning the proper value when searching for an empty string and providing a start index. Works fine on .NET Framework and .NET Core 1.1.
```C#
Debug.Assert("abc".IndexOf("", 2) == 2);
```

**Comment by jkotas** [comment]
@tarekgh

**Comment by tarekgh** [comment]
Thanks @slozier for reporting this issue.

**Comment by jkotas** [comment]
Need tests in corefx
