### ISSUE TITLE
AV on SampleProfiler Disable

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#11588]
* thread #126: tid = 33976, 0x00007ffff6dcf962 libc.so.6`cfree + 34, name = 'dotnet', stop reason = invalid address (fault address: 0xfffffffffffffffc)
  * frame #0: 0x00007ffff6dcf962 libc.so.6`cfree + 34
    frame #1: 0x00007ffff64771d4 libcoreclr.so`CorUnix::CPalObjectBase::~CPalObjectBase(this=0x0000000000729a90) + 52 at palobjbase.cpp:349
    frame #2: 0x00007ffff6477183 libcoreclr.so`CorUnix::CPalObjectBase::ReleaseReference(CorUnix::CPalThread*) [inlined] void CorUnix::InternalDelete<CorUnix::CPalObjectBase>(p=0x0000000000729a90) + 14 at malloc.hpp:134
    frame #3: 0x00007ffff6477175 libcoreclr.so`CorUnix::CPalObjectBase::ReleaseReference(this=0x0000000000729a90, pthr=0x00007fff4801e9f0) + 117 at palobjbase.cpp:317
    frame #4: 0x00007ffff6468d1b libcoreclr.so`CorUnix::CSimpleHandleManager::FreeHandle(this=<unavailable>, pThread=0x00007fff4801e9f0, h=<unavailable>) + 283 at handlemgr.cpp:253
    frame #5: 0x00007ffff64687be libcoreclr.so`CloseHandle + 70 at handleapi.cpp:312
    frame #6: 0x00007ffff6468778 libcoreclr.so`CloseHandle(hObject=0x0000000000000844) + 40 at handleapi.cpp:287
    frame #7: 0x00007ffff61c7530 libcoreclr.so`CLREventBase::CloseEvent(this=0x000000000079f6c8) + 112 at synch.cpp:328
    frame #8: 0x00007ffff60d9dca libcoreclr.so`Thread::~Thread(this=0x000000000079f540) + 234 at threads.cpp:3066
    frame #9: 0x00007ffff60da52e libcoreclr.so`Thread::~Thread(this=0x000000000079f540) + 14 at threads.cpp:2990
    frame #10: 0x00007ffff60d9673 libcoreclr.so`Thread::DecExternalCount(this=<unavailable>, holdingLock=<unavailable>) + 467 at threads.cpp:2909
    frame #11: 0x00007ffff60d8029 libcoreclr.so`Thread::OnThreadTerminate(this=0x000000000079f540, holdingLock=0) + 1657 at threads.cpp:3541
    frame #12: 0x00007ffff60d7975 libcoreclr.so`DestroyThread(th=0x000000000079f540) + 341 at threads.cpp:993
    frame #13: 0x00007ffff61acb0f libcoreclr.so`SampleProfiler::ThreadProc(args=<unavailable>) + 431 at sampleprofiler.cpp:141
    frame #14: 0x00007ffff6496562 libcoreclr.so`CorUnix::CPalThread::ThreadEntry(pvParam=0x00007fff4801e9f0) + 306 at thread.cpp:1749
    frame #15: 0x00007ffff79bd6ba libpthread.so.0`start_thread + 202
    frame #16: 0x00007ffff6e5282d libc.so.6`clone + 109

**Comment by brianrob** [comment]
@kouvel, have you see this before?  This is a stress bug that shows up when creating a destroying threads in a loop.

**Comment by brianrob** [comment]
I think that this may be because COMPlus_PerformanceTracing=1 was set and the test called APIs to enable/disable tracing.

@kouvel, I'm interested in if you've seen this, but if not, I think it might have been a bad combination of the COMPlus variable above and code, and not an issue in threading.

**Comment by kouvel** [comment]
I haven't seen this before. The object pointer looks wrong, maybe some corruption occurred in the handle table. I don't see anything wrong with the way in which this event is used. I'll need to try for a repro, do you happen to know which test case runs into this, or is it a combination of tests that I can try?

**Comment by brianrob** [comment]
Thanks @kouvel.  Hold off on trying this for the moment.  I think that this could have been my own doing.  I want to prove that it could be a real bug before you spend any time on it.  I'll let you know.

**Comment by brianrob** [comment]
This appears to have been my fault.  Closing.
