### ISSUE TITLE
No usable version of the ICU libraries was found

### ISSUE THREAD

**Issue by seniorghost** [dotnet/coreclr#11599]
I'm trying to run my .NET Core app on a Raspberry PI and I have followed every step in this guide https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md
but I get this message:

`No usable version of the ICU libraries was found
Aborted`

I checked and I have all the libraries:
`libicuuc.a  libicuuc.so  libicuuc.so.52  libicuuc.so.52.1
libicui18n.a  libicui18n.so  libicui18n.so.52  libicui18n.so.52.1`

I'm running ubuntu.16.04

**Comment by janvorli** [comment]
@seniorghost can you please try to do
```sh
export CLR_ICU_VERSION_OVERRIDE=52.1
```
and then try again?

**Comment by seniorghost** [comment]
@janvorli 
Now I get this error `Cannot get symbol ucol_setMaxVariable_52 from libicui18n`

**Comment by janvorli** [comment]
@seniorghost thank you. I think I know what's going on. Can you please try to install package libicu55? If that doesn't fix the problem, I'll be able to look into it on Tuesday.

**Comment by seniorghost** [comment]
@janvorli thank you for your quick help, it works now 😃
