### ISSUE TITLE
Windows Vista Compatibility

### ISSUE THREAD

**Issue by CharlesToniolo** [dotnet/coreclr#11604]
Hello,

I would like to embed a .NET Core application with another application that runs with .NET 4.5.2.
Is there any way to build de CoreCLR compatible with Windows Vista, even if it runs slower?

The first error that i saw was the ResolveLocaleName missing in the Kernell32.DLL so i defined the ENABLE_DOWNLEVEL_FOR_NLS. After that i got another error, so I would like to know if there is any way to run on Vista.

Thanks

**Comment by richlander** [comment]
Windows 7 is the oldest Windows version that we support. We do not test Windows Vista, so even if you got it working, there would be no guarantee that future versions (including security patches) would work. Your best and fastest path is to upgrade to at least Windows 7. 

I hope you do find a way to use .NET Core. It sounds like you have a good idea in mind.

**Comment by benaadams** [comment]
Aside: https://support.microsoft.com/en-us/help/22882/windows-vista-end-of-support

> # Windows Vista support has ended
> As of April 11, 2017, Windows Vista customers are no longer receiving new security updates, non-security hotfixes, free or paid assisted support options, or online technical content updates from Microsoft. Microsoft has provided support for Windows Vista for the past 10 years, but the time has come for us, along with our hardware and software partners, to invest our resources towards more recent technologies so that we can continue to deliver great new experiences.
