### ISSUE TITLE
JIT optimization: IV widening

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/coreclr#11608]
(I'm creating tracking issues for some optimizations that RyuJit doesn't perform, so we'll have a place to reference/note when we see the lack of them affecting particular benchmarks)

**Comment by JosephTremoulet** [comment]
This leaves extra converts in `BenchI-XPos_Mtx` (and basically every loop that indexes into arrays...)

**Comment by mikedn** [comment]
Dup of #9179

**Comment by mikedn** [comment]
An alternative solution for array indices might be to change signed casts to unsigned casts, I once tried that in #8821 and it does improve performance in some cases. That approach unfortunately produced some regressions but there may be a way to do this cheaply in assertion propagation.

**Comment by JosephTremoulet** [comment]
> Dup of #9179

Sure is, thanks; closing.
