### ISSUE TITLE
Different behavior for x86 and x64 in passing structs

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#11611]
_From @mikasoukhov on May 15, 2017 15:26_

Code below for x86 print

handle( StrctInDlgt.Program, ( i:0, o: ), 123 )

for x64

handle( StrctInDlgt.Program, ( i:123, o:123 ), 123 )

Looks like for 64 bits value types args passed as a reference on stack.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StrctInDlgt
{
	public struct Data
	{
		public long Int;
		public object Obj;

		private long a, b, c, d, e, f, g, h, i, j;

		public override string ToString()
		{
			return string.Format( "( i:{0}, o:{1} )", Int, Obj );
		}
	}

	public delegate void CallMeNow( object sender, Data data, long value );

	class Handler
	{
		public void handle( object sender, Data data, long value )
		{
			Console.WriteLine( "handle( {0}, {1}, {2} )", sender, data, value );
			// now I will change some fields in LOCAL copy struct Data
			data.Int = value;
			data.Obj = value;
		}
	}

	class Program
	{
		CallMeNow _call;
		public event CallMeNow callMe
		{
			add { _call += value; }
			remove { _call -= value; }
		}

		static void Main( string[] args )
		{
			var p = new Program();

			var h1 = new Handler();
			p.callMe += h1.handle;
			var h2 = new Handler();
			p.callMe += h2.handle;

			var d = new Data();
			p._call?.Invoke( p, d, 123 );
			//p.callMe( p, d, 123 );

			Console.ReadLine();
		}
	}
}
```

_Copied from original issue: dotnet/corefx#19774_

**Comment by jkotas** [comment]
_From @danmosemsft on May 15, 2017 15:49_

The behavior is the same in full framework. I am not sure what the correct behavior should be: this may be more of a question for the Roslyn folk. @stephentoub ?

**Comment by tannergooding** [comment]
I've simplified this quite a bit and determined it is directly related to `MultiCastDelegate`:

```C#
using System;

public struct Data
{
    public long Int;
    public object Obj;
}

class Program
{
    public static void handle(Data data, long value)
    {
        Console.WriteLine("handle( ( i:{0}, o:{1} ), {2} )", data.Int, data.Obj, value);

        data.Int = value;
        data.Obj = value;
    }

    static void Main(string[] args)
    {
        Action<Data, long> handler = handle;
        handler += handle;

        var data = new Data();
        handler(data, 123);

        Console.ReadLine();
    }
}
```

**Comment by jkotas** [comment]
cc @dotnet/jit-contrib Looks like optimization bug in RyuJIT. There should be a local copy of the struct argument created so that the modifications do not leak to the caller.

**Comment by russellhadley** [comment]
@JosephTremoulet, could you take a look since you've been working on our struct handling?

**Comment by pgavlin** [comment]
FWIW, the C++ compiler appears to assume that the callee is allowed to modify the memory that backs an implicit pass-by-ref struct argument:

https://gist.github.com/pgavlin/7206ecdab27b5a93b07d617d5818491c
compiles to
https://gist.github.com/pgavlin/4e1b593270d46ec1639c17f57cd51dce

Note the write to the incoming parameter in `m`: https://gist.github.com/pgavlin/4e1b593270d46ec1639c17f57cd51dce#file-a-asm-L97-L99

If this is correct behavior, then perhaps that the MulticastDelegate invoke stub is not correctly copying the incoming argument to an outgoing argument when invoking its handlers.

**Comment by JosephTremoulet** [comment]
>  perhaps that the MulticastDelegate invoke stub is not correctly copying the incoming argument to an outgoing argument when invoking its handlers

That would fit with what I'm seeing -- Main calls System.Action`2[Data,Int64][Data,System.Int64]:Invoke (which is a single call and not where the problem is), and the next thing we jit (at least according to my jit-dump) is Program:handle (which gets the bad value passed in), so it would seem to be non-jitted code that behaves incorrectly.  Are the invoke stubs not jitted code?

**Comment by jkotas** [comment]
> Are the invoke stubs not jitted code?

They are still not jitted code on Windows AMD64 actually - I have not realized that we have not switched them to the stubs-as-il plan yet. So this is VM side bug. Thanks for taking a look

**Comment by jkotas** [comment]
We have shipped this with this bug for 10+ years. It does not make the bar for pushing to 2.0 at this point.
