### ISSUE TITLE
Error marshalling a string field, in Linux env only (Marshal.PtrToStruct in conjunction with StructLayout.Sequential and 8-bit char string)

### ISSUE THREAD

**Issue by weshaggard** [dotnet/coreclr#11614]
@Budenniy commented on [Mon Apr 17 2017](https://github.com/dotnet/standard/issues/305)

Hi colleagues,

Got an external binary stream of fixed-size/layout structures containing a string field in non-English 8-bit encoding (Win-1251) we need to decode. 
The approximate structure layout:

	[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1, Size = ...)]
	public struct ProblemStruct
	{
		Int64 Field1;
		...
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 51)]
		string ProblemField;
		...
		Int32 FieldXX;
	}

The decoding code:

	public static T ByteArrayToStructure<T>(byte[] bytes) where T : struct
        {
            var handle = GCHandle.Alloc(bytes, GCHandleType.Pinned);
            T structure = (T)Marshal.PtrToStructure(handle.AddrOfPinnedObject(), typeof(T));
            handle.Free();
            return structure;
        }

It's been running fine for a year or so under .NET 4.5-4.6 and later under .NET Core (including latest releases) ... in Windows environment. However we made a choice if favor of Linux and now are migrating the libraries.
Here comes the problem. Regardless of where the binaries have been built  - at Windows side or at Linux  - and of CultureInfo settings - decoding of this field (and of other similar fields) goes wrong. Installing additional languages in Ubuntu as well as a bunch of other common workarounds did not help as well...
The byte sequence being decoded at Linux side has been checked using VS Code debugger and contains correct Win-1251 codes. Changing the field type to byte array and applying manual decoding using appropriate Encoding.GetString gives correctly decoded string (but it gets very unhandy to use them this way). Output System.String object seems to be corrupt - gives a set of bogus characters when printed at console but enumerating through its chars shows only 0-s. Initial feeling - it treats the input byte sequence as some 16-bit encoding (UTF8) regardless of CharSet.Ansi setting.
The rest of the fields (even including nested structures) both preceding and follwoing the field are decoded fine - that should strike out the possibility of incorrect offsets. Still runs fine @ Win7.

Details:
OS: Ubuntu 16.04LTS, 
Framework: .netcoreapp1.1 - based builds

Any ideas how to resolve the issue are welcome - it's a real showstopper for us.
Will provide additional details if needed.

Thanks in advance,

Best,
Vlad

**Comment by danmosemsft** [comment]
@Budenniy can you cut this down to a small repro case? that would help enormously.

**Comment by Budenniy** [comment]
Hey Dan,

Thanks for you reply

Unfortunately I'm under a huge workload these days, anyway got this on follow-up. It seems rather tricky to mock a server-side for a topic streaming binary structures with 8-bit char string in it... need to think over it.

Thanks,

Best,
Vlad

**Comment by jkotas** [comment]
> it treats the input byte sequence as some 16-bit encoding (UTF8) regardless of CharSet.Ansi setting.

It is the expected behavior on Unix. The "Ansi" string marshalling is always using UTF8 encoding on Unix.

**Comment by Budenniy** [comment]
Hi Jan,

Could you explain why it is expected behaviour? I believe ANSI and UTF8 are quite different. How do we marshal structures with ANSI string members else and what's the purpose of CharSet.Ansi member then? Currently it's misleading and causes different behaviour of the same code at Windows vs Linux platforms.

Best,
Vlad

**Comment by jkotas** [comment]
On Windows, Ansi marshalling uses the current Windows ANSI code page, ie. the codepage returned by [GetACP](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318070(v=vs.85).aspx) Windows API. This value depends on your system setting, it can be any encoding, including UTF8.

Unix systems standardized on UTF8 encoding. There is no explicit concept of current code page. The equivalent of "current codepage" on Unix is always UTF8.

The APIs in System.Runtime.InteropServices namespace are designed for interop with unmanaged code. The conventions for unmanaged code are different between Windows and Unix, and thus these APIs behave differently between Windows and Unix to match the underlying platform.

**Comment by Budenniy** [comment]
Jan, 

I agree - dived into a question a bit deeper, ANSI term itself is slightly misleading these days. I'll rephrase my question - how do we marshal a structure with 8-bit char string member in it? (except obvious manual char array conversion)

Best,
Vlad

**Comment by jkotas** [comment]
There is nothing built-in if you are trying to marshal it to on-wire format that should fixed accross different OSes.

If you have a lot of these structures and you do not want to write the marshalling code manually, you may consider writing auto-generator of the marshalling code. As a side-effect, it should be also significantly faster than PtrToStructure and similar methods. The implementation of PtrToStructure is not very efficient in CoreCLR.

**Comment by Budenniy** [comment]
Already considered something like that - planned to try UnmanagedType.CustomMarshaler, but turned out it's not supported in current .netstandard1.6

**Comment by jkotas** [comment]
UnmanagedType.CustomMarshaler is added back in netstandard2.0.

**Comment by Budenniy** [comment]
Good morning Jan,

Thanks for tipping, a pity currently it's only in preview state, management is reluctant to use it for production, however I will definitely give it a try. 

From how I see the whole picture with my situation I guess the issue can be closed.

Best,
Vlad
