### ISSUE TITLE
Remove Extra Buffer Allocation / Copy from EventSource

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#11615]
Remove this extra allocation/copy and copy the arguments directly in EventPipeBufferManager::WriteEvent.

https://github.com/dotnet/coreclr/pull/11577/files/ac7ab91221c75e042325c36c263540a958643ef8#diff-73569c6f5e0722e21820732511f3dbf0R75

**Comment by gkhanna79** [comment]
@brianrob Please assign to someone if this is being tracked for 2.0.0.

**Comment by Petermarcu** [comment]
@brianrob is this coming through for 2.0.0 or should it just be moved to 2.1?

**Comment by brianrob** [comment]
This can me moved to 2.1.  Done.

**Comment by brianrob** [comment]
Fixed via #13347.
