### ISSUE TITLE
Assert failure(PID 25168 [0x00006250], Thread: 25268 [0x62b4]): Assertion failed 'freshBaseMethodAttribs == baseMethodAttribs'

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#11619]
This seems to be intermittent.  I've only seen it repro in CI and locally when running ALL of the corefx tests together, the CI doesn't always hit it, and it has hit different tests in different runs.  **I can't repro it when re-running the individual tests that fail locally.**

[Example of CI job that failed](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_jitstressregs8/177/).  This is not specific to JitStress(Regs); I have repro'd it locally with a stock corefx run:

Repro steps that worked for me (from coreclr 1cf39a4e686668f35aec3f336615c422e3cc9fec on Windows):
```
>build x64 checked skiptests
>python tests\scripts\run-corefx-tests.py -build_type Checked
```
Example output (de-interleaved from my local build-tests.log)
```
C:\git\coreclr\_\fx\bin/Windows_NT.AnyCPU.Release/System.Xml.XPath.Tests/netcoreapp//RunTests.cmd C:\git\coreclr\_\fx\bin/testhost/netcoreapp-Windows_NT-Release-x64/
Using C:\git\coreclr\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x64\ as the test runtime folder.
Executing in C:\git\coreclr\_\fx\bin\Windows_NT.AnyCPU.Release\System.Xml.XPath.Tests\netcoreapp\ 
Running tests... Start time:  9:22:37.20
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Xml.XPath.Tests
Discovered:  System.Xml.XPath.Tests
Starting:    System.Xml.XPath.Tests

Assert failure(PID 25168 [0x00006250], Thread: 25268 [0x62b4]): Assertion failed 'freshBaseMethodAttribs == baseMethodAttribs' in 'XPathTests.FunctionalTests.Expressions.SetContextFunctionalTestsTests:SetContextFunctionalTestsTest433()' (IL size 152)

    File: c:\git\coreclr\src\jit\importer.cpp Line: 18595
    Image: C:\git\coreclr\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x64\dotnet.exe

Finished running tests.  End time= 9:23:25.66, Exit code = 123456789
```

**Comment by RussKeldorph** [comment]
@AndyAyersMS Could you take a look since this looks devirt-related?

@dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
[Another CI failure example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_minopts/174/).  The latest run of the same job is green.

**Comment by AndyAyersMS** [comment]
Likely suspect: there's some kind of race where the jit decides to propagate noinline for some method X on one thread back to the VM while in the middle of jitting some other method Y on another thread, and where that jit attempt is looking at X's attributes. This jives with it only reproing intermittently and seemingly only under higher CPU loads.

We don't actually care about the state of the noinline attribute so I'll see if I can conifirm it is just that bit that differs and if so we can filter it out.

Assuming the above is true, it's an assert only issue, and will have no impact on codegen.

**Comment by AndyAyersMS** [comment]
Trying to get this to repro for me locally....

**Comment by AndyAyersMS** [comment]
Got a local repro but my attempt at emitting more diagnostic via stderr info failed to surface anywhere so I don't know for sure what the new and old attribute bits were. Am going to retry using stdout. If that fails I can always just check for the suspect case above directly.

**Comment by AndyAyersMS** [comment]
Got a second repro but couldn't find stdout text either. So have reworked things to have different asserts depending on whether or not `CORINFO_FLG_DONT_INLINE` is all that differs. Seems to take me a few hours to repro so hopefully will know later today if my guess above was right.

**Comment by AndyAyersMS** [comment]
Now have an example where the `DONT_INLINE` attribute bit is the only one changing. Am going to let these tests run a bit longer to see if the other assert (which checks all the other bits) ever fires.
```
Assert failure(PID 92880 [0x00016ad0], Thread: 70508 [0x1136c]): Assertion failed '!"attributesMatchedExceptDontInline"' in 'System.Xml.Tests.DocumentElement_InsertBeforeTests:InsertCDataNodeToDocumentNode()' (IL size 74)
         
File: e:\repos\coreclr\src\jit\importer.cpp Line: 18603
Image: E:\repos\coreclr\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x64\dotnet.exe

```

**Comment by AndyAyersMS** [comment]
Got another repro of the `DONT_INLINE` bit changing. Will do one more round of runs before deciding this is the only possibility.
