### ISSUE TITLE
Add agent cleanup steps to Windows official builds

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#11621]
Right now, agent cleanup is only done in the Linux builds. On Windows, the cleanup steps would fix a problem where sometimes processes linger and hold files open, breaking the next build's `git clean -xdf`. Build 20170513-02 hit this problem and failed.

/cc @gkhanna79 @wtgodbe

**Comment by RussKeldorph** [comment]
@jcagme @karajas @chcosta Is this dotnet/core-eng#2079?

**Comment by chcosta** [comment]
Yes, it's similar.  @karajas  is looking at utilizing the VSTS feature for process cleanup which should be available for investigation starting next week (12/4).  Karthik, do you want to close this as a duplicate?

**Comment by karajas** [comment]
Sounds good to me. Will update this, when the rollout is complete.
