### ISSUE TITLE
[ARM32] In Debug build, JIT/Methodical/fp/exgen/10w5d_cs_do fails

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#11640]
Following two `10w5d` tests are failing only in `Debug` build.
It passes with `Release` build for ARM32.

This fails with master branch with default JIT, i.e. legacy jit for ARM32.

```
JIT/Methodical/fp/exgen/10w5d_cs_do
JIT/Methodical/fp/exgen/10w5d_cs_ro
```

```
$ /mnt/albireo/mywork/device/rpi3/unittests/coreoverlays/coreoverlay.test20170515/corerun 10w5d_cs_do.exe

... (omitted)...

Func_0_3_6_3_4: != true

Unhandled Exception: System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(UInt64 value)
   at testout1.Func_0_3_6_2()
   at testout1.Func_0_3_6()
   at testout1.Func_0_3()
   at testout1.Func_0()
   at testout1.Main()
../run_10w5d.sh: line 12: 16789 Aborted                 (core dumped) /mnt/albireo/mywork/device/rpi3/unittests/coreoverlays/coreoverlay.test20170515/corerun 10w5d_cs_do.exe
```

This was found during debugging `10w5d1` test in ryujit/arm32 (issue #11603) and found that it fails only in Debug build.

**Comment by hqueue** [comment]
If possible, can anyone reproduce this in arm32 environment ?

**Comment by mskvortsov** [comment]
I can repro this. Fails on debug, passes on chk.

**Comment by hqueue** [comment]
@mskvortsov Thanks! And do you have any idea ? I suspect this issue may relate to library or C++ compiler intrinsic.

FYI. There was a corefx test issue in https://github.com/dotnet/corefx/issues/18601 where ARM math library  returns 1-bit different result.

**Comment by mskvortsov** [comment]
@hqueue No, I don't have, this issue needs investigation. However, the first thing I would think about is not a library/compiler issue, but the difference between debug/release builds (only release/chk turns on full optimizations).

**Comment by BruceForstall** [comment]
@hqueue Does this issue still exist?

**Comment by hqueue** [comment]
@BruceForstall Yes, it is still observed from recent master branch (4cf4202f113439b4dd99bea0cb6c8618760e55d4)

**Comment by sandreenko** [comment]
Does not repro with RyuJit and was fixed for legacy by @BruceForstall , could we close this issue?

**Comment by BruceForstall** [comment]
> fixed for legacy by @BruceForstall 

hmmm... did you find a commit that fixed it?

Nonetheless, yes, I will close it.
