### ISSUE TITLE
Add Move method to List<T>

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#1165]
There  are plenty of convenience methods in generic List. But no Move method that can efficiently move an item from one position to another.
What we have to do is [RemoveAt and Insert](https://github.com/dotnet/corefx/blob/master/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs#L200). It means two copies of big chunks of memory instead of one. The worst case is when both **from** and **to** are close to each other and to the beginning of a large list. What could be done with one copy  of a few items becomes two copies of almost the whole list.
In my implementation of ObservableCollection.MoveItem I had to get the underlying `List`, retrieve via reflection :see_no_evil: its array and  do the work myself. 

So.. **I propose adding new Move method to generic List with the following signature:**

``` C#
public void Move(int oldIndex, int newIndex);
```

**Comment by omariom** [comment]
cc: @KrzysztofCwalina

**Comment by OtherCrashOverride** [comment]
Isn't this what LinkedList is for?

**Comment by omariom** [comment]
LinkedList is quite different in its capabilities. Its elements can't be accessed by position, its layout is not cache friendly etc.

**Comment by hadibrais** [comment]
While such method can be added to the generic list and is really useful, it cannot be utilized from the existing **ObservableCollection.Move** method you referenced. That's because three state changes have to be reported: **NotifyCollectionChangedAction.Remove**, **NotifyCollectionChangedAction.Add** and **NotifyCollectionChangedAction.Move**. Also the intermediate states have to be captured and made available to any listeners. Regardless, such efficient method is really useful and should be offered by the generic List. It's also easy to implement.

**Comment by omariom** [comment]
I mentioned ObservableCollection.MoveItem just as an example where such method could be used.
Actually there are other cases where Move could be beneficial.

> That's because three state changes have to be reported: NotifyCollectionChangedAction.Remove, NotifyCollectionChangedAction.Add and NotifyCollectionChangedAction.Move.

Collection<T> (which is the base class) doesn't report any actions. So  nothing changes in terms of reporting.

**Comment by OtherCrashOverride** [comment]
List is not intended for performance with random inserts and deletes.  Adding 'move' would just encourage improper use of the class.  Move is a heavy weight function when type of List<T> is a struct/valuetype.

If there is a language where there is a precedence of having Move on a List it would be worth examining.  Neither C++ std::vector nor Java 8 have any such notion.

> In my implementation of ObservableCollection.MoveItem I had to get the underlying List, retrieve via reflection its array and do the work myself. 

It would also be helpful to post the code somewhere as an example of what is wanted.

**Comment by omariom** [comment]
@OtherCrashOverride 
Something like this:
```C#
public void Move(int oldIndex, int newIndex)
{
    if ((uint)oldIndex >= (uint)_size)
    {
        ThrowArgumentOutOfRange("oldIndex");
    }

    if ((uint)newIndex >= (uint)_size)
    {
        ThrowArgumentOutOfRange("newIndex");
    }

    T item = _items[oldIndex];

    if (newIndex < oldIndex)
    {
        Array.Copy(_items, newIndex, _items, newIndex + 1, oldIndex - newIndex);
    }
    else if (newIndex > oldIndex)
    {
        Array.Copy(_items, oldIndex + 1, _items, oldIndex, newIndex - oldIndex);
    }

    _items[newIndex] = item ;
    _version++;
}

```

**Comment by omariom** [comment]
>List is not intended for performance with random inserts and deletes. 

Yes, but we already have  **RemoveAt** and **Insert* methods which allow random inserts and deletes. And And they are **actually** used to implement move semantics.

**Comment by OtherCrashOverride** [comment]
I would suggesting creating a pull request with the code and some tests.  You should also include code to benchmark performance with Move versus RemoveAt / Insert.

**Comment by masonwheeler** [comment]
@OtherCrashOverride The performance benefits are obvious when you think about worst cases.  For example, imagine a list with a few thousand items in it, and the operation you want to perform is `Move(10, 20);`

With `RemoveAt` and `Insert`, you end up having to shift (essentially) all items in the list... twice.  With the proposed `Move` method, you would have to shift 9 items once.

**Comment by OtherCrashOverride** [comment]
> The performance benefits are obvious when you think about worst cases.

We really need to see benchmarks before we start speculating.  In theory, it should be faster.  The reality will come down to what the runtime does behind the scenes.

For most cases LinkedList is probably a better choice. The use case for this is where you require the data to be sequential in memory.  A specific example is when dealing with a GPU.  Vertex data is typically very large structs packed into an array.  It is also not uncommon to manipulate that data elements in real time.  This proposal may benefit that specific scenario.  We still require a benchmark to validate the claim.

**Comment by KrzysztofCwalina** [comment]
I think some kind of "move" API is worth exploring. But I think it would be great if somebody thought about a more general API than simple "move one items from here to there". For example, what if I want to move a slice/range? what if I want to swap two ranges? What if I want to round robin move three items? BTW, I am not proposing that we actually implement all these, often corner case, scenarios, but it would be good to have a good overview of the "move" scenarios and chose to implement the ones that are common and where we can get good performance improvement while preserving simplicity.

**Comment by OtherCrashOverride** [comment]
Upon further reflection, there is an issue here in that you can not actually get at the sequential data (for p/invoke) without exposing the internal array.  With that in mind, maybe 'Move' should be proposed for 'Array'.  List could then make use of that functionality without breaking encapsulation by exposing the internal array storage.

**Comment by AdamSpeight2008** [comment]
Why not just swap the contents?
```c#
public void Swap<T>( this T a, T )
{
  T tmp = a;
      a = b;
      b = a;
} 
```

**Comment by masonwheeler** [comment]
@AdamSpeight2008 Because that would only be a valid equivalent if the new index was adjacent to the old index.

Let's say we have a lit of ints, like so:

`0, 1, 2, 3, 4, 5, 6, 7, 8, 9`

Swapping 1 and 5 would result in

`0, 5, 2, 3, 4, 1, 6, 7, 8, 9`

whereas executing the hypothetical `Move(1, 5)` would result in:

`0, 2, 3, 4, 1, 5, 6, 7, 8, 9`

As you can see, they're completely different operations.

**Comment by AdamSpeight2008** [comment]
@masonwheeler  
Should the result of `Move( 1, 5)` be `0, 2, 3, 4, 5, 1, 6, 7, 8, 9`

**Comment by AdamSpeight2008** [comment]
The following extension methods implement the `Move`functionality.

```vb
Public Module Exts

    <Runtime.CompilerServices.Extension>
    Public Sub Swap(Of T)(ByRef x As T, ByRef y As T)
        Dim tmp = x : x = y : y = tmp
    End Sub


    <Runtime.CompilerServices.Extension>
    Public Function Move(Of T)(xs As IList(Of T), ox As Integer, nx As Integer) As IEnumerable(Of T)
        If ox = nx Then Return xs.AsEnumerable
        Return _Move(xs, ox, nx)
    End Function


    Private Iterator Function _Move(Of T)(xs As IList(Of T), ox As Integer, nx As Integer) As IEnumerable(Of T)
        Dim en = xs.GetEnumerator
        If nx < ox Then nx.Swap(ox)
        Dim ix = 0
        Dim oxd As T
        While en.MoveNext
            If ix = ox Then
                oxd = en.Current
            ElseIf ix = nx Then
                Yield en.Current
                Yield oxd
            Else
                Yield en.Current
            End If
            ix += 1
        End While
    End Function

End Module
```

**Comment by AdamSpeight2008** [comment]
`Move( 1, 5). Move( 5, 1)` should really result in the original list.

**Comment by omariom** [comment]
@KrzysztofCwalina,

I think two the most practical overloads at the moment are these:
```C#
void Move(oldIndex, newIndex);
void Move(sourceIndex, length, destinationIndex);
```

Or, as an alternative, List<T> could have Copy method with the same semantics as [Array.Copy](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Array.cs#L288) method. Then everyone could implement whatever he needs: moves, shifts, etc.

**Comment by omariom** [comment]
This is what I have to do.. :scream_cat: 

![](https://cloud.githubusercontent.com/assets/1781701/10099125/65e83124-638f-11e5-8241-4a4de138fc9c.png)

**Comment by omariom** [comment]
@KrzysztofCwalina 
Now that .NET Core 1.0 is out  can we change the milestone of the issue from Future to Present? )

**Comment by KrzysztofCwalina** [comment]
@terrajobst, @weshaggard, are you guys going to triage "future" issues?

**Comment by danmosemsft** [comment]
API request - moving to CoreFX.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #14338](https://github.com/dotnet/corefx/issues/14338) via [**ZenHub**](https://www.zenhub.com/)
