### ISSUE TITLE
[Unix] String format errors marked as unsupported

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#11655]
There are several tests (in the testsUnsupportedOutsideWindows.txt) which are failing due to string formatting errors.  This does not seem like an unsolveable platform error.

For example

`CoreMangLib/cti/system/byte/ByteToString3/ByteToString3.sh`

```
ERROR!!!-PostTest4, default_001: Expected: 1,280000E2 Actual: 1,280000E++002
ERROR!!!-PostTest4, 4digits_001: Expected: 1,2800E2 Actual: 1,2800E++002
```

Others...
```
CoreMangLib/cti/system/double/DoubleToString3/DoubleToString3.sh
CoreMangLib/cti/system/double/DoubleToString4/DoubleToString4.sh
CoreMangLib/cti/system/int/Int32ToString3/Int32ToString3.sh
CoreMangLib/cti/system/int64/Int64ToString3/Int64ToString3.sh
CoreMangLib/cti/system/uint16/UInt16ToString3/UInt16ToString3.sh
CoreMangLib/cti/system/uint16/UInt16ToString4/UInt16ToString4.sh
CoreMangLib/cti/system/uint32/UInt32ToString2/UInt32ToString2.sh
```

**Comment by AlexGhiondea** [comment]
It looks like the test is expecting a different output when on Unix -- looks like a test bug.

**Comment by mazong1123** [comment]
Seems like it's on purpose to separate the Windows and Linux expected results.
https://github.com/dotnet/coreclr/blob/master/tests/src/CoreMangLib/cti/system/byte/bytetostring3.cs#L92

I can't find useful commit info for the design. I'll remove the condition and to see if anything would break on Linux.
