### ISSUE TITLE
Fix JIT/CheckProjects

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#11664]
This test fails with the new BuildTools update.

**Comment by wtgodbe** [comment]
@AndyAyersMS this test started failing after I updated BuildTools to the 2.0.0 version - I've pasted the error message below, which doesn't tell me much (All suffixes appear to indicate success). Any ideas?

**Comment by wtgodbe** [comment]
> MESSAGE:
\n\nReturn code: 1\nRaw output file: D:\\j\\workspace\\debug_windows---17180f1b\\bin\\tests\\Windows_NT.x64.Debug\\Reports\\JIT.CheckProjects\\CheckProjects\\CheckProjects.output.txt\nRaw output:\nBEGIN EXECUTION\r\n \"D:\\j\\workspace\\debug_windows---17180f1b\\tests\\..\\bin\\tests\\Windows_NT.x64.Debug\\Tests\\Core_Root\\corerun.exe\" CheckProjects.exe \r\nScanning projects under D:\\j\\workspace\\debug_windows---17180f1b\\tests\\..\\tests\\src\\JIT\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Add1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\addref.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\And1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\AndRef.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Args4.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Args5.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Array1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Array2.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Array3.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Array4.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\ArrayExc.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\ArrayJagged.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\ArrayMD1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\ArrayMD2.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\ArrayObj.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\AsgAdd1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\AsgAnd1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\AsgOr1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\AsgSub1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\AsgXor1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\BinaryRMW.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Call1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\CnsBool.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\CnsLng1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblAdd.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblAddConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblArea.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblArray.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblAvg2.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblAvg6.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblCall1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblCall2.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblDist.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblDiv.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblDivConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblFillArray.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblMul.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblMulConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblNeg.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblRem.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblRoots.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblSub.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblSubConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DblVar.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\div1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\div2.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\DivConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\divref.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Eq1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FactorialRec.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FibLoop.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FiboRec.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPAdd.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPAddConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPArea.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPArray.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPAvg2.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPAvg6.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPCall1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPCall2.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPConvDbl2Lng.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPConvF2F.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPConvF2I.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPConvF2Lng.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPConvI2F.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPDist.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPDiv.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPDivConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPError.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPFillArray.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPMath.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPMul.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPMulConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPNeg.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPRem.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPRoots.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPSmall.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPSub.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPSubConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\FPVar.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Gcd.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Ge1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Gt1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Ind1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\InitObj.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\InstanceCalls.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\IntArraySum.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\IntConv.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Jmp1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrue1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueEqDbl.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueEqFP.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueEqInt1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueGeDbl.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueGeFP.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueGeInt1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueGtDbl.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueGtFP.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueGtInt1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueLeDbl.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueLeFP.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueLeInt1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueLtDbl.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueLtFP.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueLtInt1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueNeDbl.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueNeFP.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\JTrueNeInt1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Le1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LeftShift.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LngConv.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Localloc.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LocallocB_N.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LocallocB_N_PSP.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LocallocCnstB1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LocallocCnstB117.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LocallocCnstB117_PSP.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LocallocCnstB1_PSP.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LocallocCnstB5.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LocallocCnstB5001.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LocallocCnstB5001_PSP.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LocallocCnstB5_PSP.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LocallocLarge.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\LongArgsAndReturn.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Lt1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\ModConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\mul1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\mul2.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\mul3.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\mul4.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Ne1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\NegRMW.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\NestedCall.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\NotAndNeg.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\NotRMW.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\ObjAlloc.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\OpMembersOfStructLocal.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Or1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\OrRef.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\RecursiveTailCall.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\rem1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\RightShiftRef.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Rotate.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Shift.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\StaticCalls.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\StaticValueField.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\struct16args.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\StructFldAddr.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\StructInstMethod.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Sub1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\SubRef.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Swap.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Switch.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\UDivConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\UModConst.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Unbox.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\Xor1.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\CodeGenBringUpTests\\XorRef.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\config\\benchmark\\benchmark.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\config\\benchmark+roslyn\\benchmark+roslyn.csproj DebugType-n/a-SuffixNone\r\nD:\\j\\workspace\\debug_windows---17180f1b\\tests\\src\\JIT\\config\\benchmark+serialize\\benchmark+serialize.csproj DebugType-n/a-SuffixNone\r\n5991 projects, 3 needed fixes, 158 fixes deferred, 0 were fixed\r\nExpected: 100\r\nActual: -1\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\n\nTo run the test:\n> set CORE_ROOT=D:\\j\\workspace\\debug_windows---17180f1b\\bin\\tests\\Windows_NT.x64.Debug\\Tests\\Core_Root\n> D:\\j\\workspace\\debug_windows---17180f1b\\bin\\tests\\Windows_NT.x64.Debug\\JIT\\CheckProjects\\CheckProjects\\CheckProjects.cmd\n\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at JIT_CheckProjects._CheckProjects_CheckProjects_._CheckProjects_CheckProjects_cmd() in D:\j\workspace\debug_windows---17180f1b\bin\tests\Windows_NT.x64.Debug\TestWrappers\JIT.CheckProjects\JIT.CheckProjects.XUnitWrapper.cs:line 107

**Comment by wtgodbe** [comment]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/debug_windows_nt_prtest/6913/testReport/junit/JIT_CheckProjects/_CheckProjects_CheckProjects_/_CheckProjects_CheckProjects_cmd/

**Comment by AndyAyersMS** [comment]
It doesn't understand that there are now partial project files in the jit tree, so it thinks the following 3 projects need fixes since they don't specify `DebugType`. It should be updated to ignore any `.csproj` files under `config`.
```
tests\src\JIT\config\benchmark\benchmark.csproj DebugType-n/a-SuffixNone
tests\src\JIT\config\benchmark+roslyn\benchmark+roslyn.csproj DebugType-n/SuffixNone
tests\src\JIT\config\benchmark+serialize\benchmark+serialize.csproj DebugType-n/a-SuffixNone
```
