### ISSUE TITLE
2.0.0-preview1 mscorlib is not crossgen-ed

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#11678]
.NET Core 1.x had an mscorlib.ni.dll, this file is not in the 2.0.0-preview1.

The mscorlib.dll doesn't look like it's crossgen-ed:
```
$ file ./shared/Microsoft.NETCore.App/2.0.0-preview1-002111-00/mscorlib.dll
./shared/Microsoft.NETCore.App/2.0.0-preview1-002111-00/mscorlib.dll: PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
```

CC @janvorli

**Comment by mikedn** [comment]
mscorlib is a reference only assembly, it contains no code. Why would that be crossgened?

**Comment by tmds** [comment]
@mikedn I don't know. It was crossgened for 1.x.

**Comment by tmds** [comment]
@janvorli I don't know if this a real issue. Feel free to close it isn't.

**Comment by jkotas** [comment]
This is expected. See https://github.com/dotnet/coreclr/issues/5739 and related issues.
