### ISSUE TITLE
SuperPMI should support ReadyToRun

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#11702]
When crossgen'ing assemblies with ReadyToRun, the following NYIs show up in SuperPMI:
* getReadyToRunHelper
* GetReadyToRunDelegateCtorHelper

There may be others.

**Comment by sandreenko** [comment]
Could you write a repro steps please?

**Comment by CarolEidt** [comment]
Assuming your coreclr clone is at E:\git\coreclr:

cd E:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
set COMPlus_AltJit=*
set COMPlus_AltJitName=superpmi-shim-collector.dll
set SuperPMIShimLogPath=E:\SuperPmi
set SuperPMIShimPath=E:\git\coreclr\bin\Product\Windows_NT.x64.Checked\clrjit.dll

\git\coreclr\bin\Product\Windows_NT.x64.Checked\crossgen.exe /JITPath E:\git\coreclr\bin\Product\Windows_NT.x64.Checked\superpmi-shim-collector.dll /Platform_Assemblies_Paths "E:\git\coreclr\bin\Product\Windows_NT.x64.Checked;E:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root" Microsoft.CodeAnalysis.CSharp.dll

Note that the SuperPMIShimPath is using the clrjit.dll from the Product directory. I'm not sure why, but I get an error if I use the one from the Tests\Core_Root directory. Possibly operator error on my part. Also, you can use any of the corefx assemblies.
