### ISSUE TITLE
[RyuJIT][LSRA] Don't create Interval for non-reg candidate tracked variables

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#11707]
With #11698, only tracked variables have Intervals created for them. However, it still creates Intervals for non-reg candidate tracked variables; it shouldn't need to do this, if LSRA only pays attention to reg candidate variables. It possible doing this would improve memory allocation and throughput.

**Comment by pgavlin** [comment]
@CarolEidt I think this is done, is it not?

**Comment by CarolEidt** [comment]
Yes, it was done with #11994
