### ISSUE TITLE
Is it possible to use Mono's mscorlib, or to use Mono to build mscorlib on Linux?

### ISSUE THREAD

**Issue by obadz** [dotnet/coreclr#1170]
When I try to combine Mono's $MONO/lib/mono/4.5 folder with libcoreclr.so (etc.) into one folder, I still get the 0x80004005 error.

When I try to use xbuild to build mscorlib, I hit this exception because apparently the registry is invoked from the build files?

https://github.com/mono/mono/blob/51297ed7ab06480df84520c758639b6cef0790d9/mcs/class/Microsoft.Build.Engine/Microsoft.Build.BuildEngine/Expression.cs#L350

What's the plan to enable building the managed framework on Linux?
In the mean time is there zip file of the managed code that we could use?

Thanks!

**Comment by saper** [comment]
Getting mscorlib to build on something else than Windows is a work in progress.
This is https://github.com/dotnet/coreclr/issues/170 and there also some other issues open for particular items. Discussion about bootstrapping is focused not only on mono, there is also MSBuild (https://github.com/Microsoft/msbuild/) as well as Roslyn compiler available (https://github.com/dotnet/roslyn). None of them work at present though.

You can download a compiled `mscorlib.dll` from the continuous integration server:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_windows_debug/

in the "Artifacts" session you will find `mscorlib.dll` compiled for Windows, Linux, OSX and FreeBSD.

**Comment by obadz** [comment]
Thanks @saper !
