### ISSUE TITLE
[ARM32] SIGILL on vstr

### ISSUE THREAD

**Issue by ruben-ayrapetyan** [dotnet/coreclr#11715]
Hello.

There is some issue, which causes rare failures with `SIGILL` on ARM32

The failure was catched on `Double_And_Op_cs_d.exe` of CoreCLR test suite (`--crossgen --runcrossgentests`), details are below.

Build:
 arm release

Commit:
 ef8d1522eb15cb0371f31a9392891c942547a91f

Hardware:
 ODROID-XU3

The following GDB dump is for version with changes based on the commit.
With the changes, the failure occured in approximately 5% of runs under GDB (all of them occured on a `vstr dX, [sp, #...]` in a code very similar to the provided in the following dump).

To check that this is not a GDB bug and not an issue, introduced with my changes, I looped the test on ef8d1522eb15cb0371f31a9392891c942547a91f for about 100 times, and one of the runs ended with `132` exit code that indicates `SIGILL`. However, I don't have dump for this failure.

I don't think that the failure can be easily reproduced.

Anyway, I'm wondering why the `vstr    d7, [sp, #728]` can cause SIGILL in the code below.

Possible reasons I see:
- incorrectly flushed instruction cache (all the failures occured in an anonymously mapped area)
- one of conditions for producing "UNDEFINED INSTRUCTION" by `vstr` according to ARMv7 reference manual, which describes them as settings in the `CPACR`, `NSACR`, `HCPTR` and `FPEXC` registers, security state and mode of instruction execution

GDB dump:
```
Program received signal SIGILL, Illegal instruction.
0xb1b0b73e in ?? ()

(gdb) disassemble $pc - 0x30, $pc + 0x10
Dump of assembler code from 0xb1b0b70e to 0xb1b0b74e:

   0xb1b0b70e:  ldr     r2, [sp, #16]
   0xb1b0b710:  ldr     r2, [r2, #4]
   0xb1b0b712:  cmp     r3, r2
   0xb1b0b714:  bcc.n   0xb1b0b720
   0xb1b0b716:  movw    r1, #32269      ; 0x7e0d
   0xb1b0b71a:  movt    r1, #46731      ; 0xb68b
   0xb1b0b71e:  blx     r1
   0xb1b0b720:  ldr     r3, [sp, #16]
   0xb1b0b722:  ldr     r2, [sp, #724]  ; 0x2d4
   0xb1b0b724:  add.w   r1, r3, r2, lsl #3
   0xb1b0b728:  vldr    d7, [r1]
   0xb1b0b72c:  vstr    d7, [sp, #48]   ; 0x30
   0xb1b0b730:  b.n     0xb1b0b732
   0xb1b0b732:  vldr    d7, [sp, #56]   ; 0x38
   0xb1b0b736:  vldr    d6, [sp, #48]   ; 0x30
   0xb1b0b73a:  vadd.f64        d7, d7, d6
=> 0xb1b0b73e:  vstr    d7, [sp, #728]  ; 0x2d8
   0xb1b0b742:  vldr    d7, [sp, #728]  ; 0x2d8
   0xb1b0b746:  vstr    d7, [sp, #696]  ; 0x2b8
   0xb1b0b74a:  nop
   0xb1b0b74c:  b.n     0xb1b0b74e
End of assembler dump.

(gdb) info registers
r0             0xb2110e28       2987462184
r1             0xb2110e30       2987462192
r2             0x1      1
r3             0xb2110e28       2987462184
r4             0xb42002f5       3021996789
r5             0xbeffee68       3204443752
r6             0x0      0
r7             0xbeffedd0       3204443600
r8             0xbeffef58       3204443992
r9             0xbeffedd8       3204443608
r10            0xbeffdf10       3204439824
r11            0xbeffd0c8       3204436168
r12            0x24     36
sp             0xbeffcde0       0xbeffcde0
lr             0xb1b0b66d       -1313819027
pc             0xb1b0b73e       0xb1b0b73e
cpsr           0x800f0030       -2146500560

(gdb) p $d7
$1 = {u8 = {42, 15, 11, 181, 166, 49, 76, 64}, u16 = {3882, 46347, 12710, 16460}, u32 = {3037400874, 1078735270}, u64 = 4633132708729130794, f32 = {
    -5.18036018e-07, 3.1905303}, f64 = 56.387900000000016}

(gdb) p $sp
$2 = (void *) 0xbeffcde0 
```

**Comment by ruben-ayrapetyan** [comment]
Maybe, this is related issue: https://github.com/dotnet/coreclr/issues/13651

**Comment by BruceForstall** [comment]
Perhaps fixed by https://github.com/dotnet/coreclr/pull/17523. I'm going to close this. Reopen if the failure still exists on current sources.
