### ISSUE TITLE
Build failure: The file E:\coreclr\src\pal\tools\probe-win.ps1 is not digitally signed. (Invalid command)

### ISSUE THREAD

**Issue by saper** [dotnet/coreclr#1172]
On a pretty clean Win7 installation with VS2013 Update 4 (and not much else), using git checkout on   https://github.com/dotnet/coreclr/commit/ee26a59e352aa2beac79b2bb3b21176e9eb158cc with `core.autocrlf` set to `true` I get this after running

     build vs2013

````
Commencing CoreCLR Repo build
 
Checking pre-requisites...
 
Invalid command.
 
The AT command schedules commands and programs to run on a computer at      
a specified time and date. The Schedule service must be running to use      
the AT command.
...
````

Full dump is available at https://gist.github.com/saper/0f655d09c7e489c680d1

It seems that the `powershell` execution fails because of signing.

Having tried to run

     powershell -NoProfile -ExecutionPolicy RemoteSigned "& ""src\pal\tools\proble-win.ps1"""

manually results in:

````
File E:\coreclr\src\pal\tools\probe-win.ps1 cannot be loaded. The file E:\corec
lr\src\pal\tools\probe-win.ps1 is not digitally signed. The script will not exe
cute on the system. Please see "get-help about_signing" for more details..
At line:1 char:2
+ & <<<<  "src\pal\tools\probe-win.ps1"
    + CategoryInfo          : NotSpecified: (:) [], PSSecurityException
    + FullyQualifiedErrorId : RuntimeException
 ````

**Comment by saper** [comment]
Changing `RemoteSigned` to `Unrestricted` allows my build to proceed (I need to confirm once this script should execute once).

**Comment by poizan42** [comment]
@saper How did you get the files? Sounds like they are marked as downloaded files. Could you try unblocking the script like described here: http://blogs.msdn.com/b/delay/p/unblockingdownloadedfile.aspx

**Comment by saper** [comment]
On Thu, 25 Jun 2015, Kasper Fabæch Brandt wrote:

> @saper How did you get the files? Sounds like they are marked as downloaded files. Could you try unblocking the script like described here: http://blogs.msdn.com/b/delay/p/unblockingdownloadedfile.aspx

It is a check out from git.

"streams" from SysInternals does not show any additional NTFS streams
which could indicate file downloaded via "Internet zone"

**Comment by saper** [comment]
How does a signature look like on a PS1 file? Maybe I can check it manually somehow.

**Comment by poizan42** [comment]
It's not supposed to be signed:

    RemoteSigned - Downloaded scripts must be signed by a trusted publisher before they can be run.

Your powershell somehow thinks that the file is downloaded. I have no idea how that happens if it's not marked as such. Maybe som msft'er could come up with a reasonable explanation?

**Comment by saper** [comment]
I think I now: the repository is located on the SMB share.

**Comment by poizan42** [comment]
Seems like it would be reasonable to change it to unrestricted if that is the case.

**Comment by saper** [comment]
Yes, but in that case it stops the build and asks a question: I don't think that something we want to have in the repository? (Additionally, I think this error should be handled better...)

**Comment by poizan42** [comment]
What if you use `-ExecutionPolicy Bypass`?

**Comment by saper** [comment]
On Thu, 25 Jun 2015, Kasper Fabæch Brandt wrote:

> What if you use `-ExecutionPolicy Bypass`?

Yes, that works fine.

**Comment by tzwlai** [comment]
Closing this issue since it looks like the problem has been resolved and there's not been any activity in a while. Please feel free to reopen if anyone feels differently.
