### ISSUE TITLE
Fix broken performance test infrastructure

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/coreclr#11729]
The check-in that moved build tools forward to 2.0, broke all of our performance tests.

**Comment by AndyAyersMS** [comment]
Not sure what specifically you meant, but it looks like the xunit.performance.api got rolled back to 1.0.0-beta-build0003 and so we lost the profile-off ability and other recent improvements.

Consider the following results chart -- profile off was enabled around 5/5 and showed lower data for a time, then around 5/17 it changed and now reports similar numbers to profile on.

![image](https://cloud.githubusercontent.com/assets/10121823/26322861/9ba3f666-3ee1-11e7-81fe-246f4bb59bcf.png)

cc @jorive

**Comment by RussKeldorph** [comment]
@jorive @adiaaida @DrewScoggins Has this been fixed?

**Comment by RussKeldorph** [comment]
Closing stale.  @billwert FYI
