### ISSUE TITLE
Interlocked.CompareExchange missing for uint, ulong and (if possible) general structs.

### ISSUE THREAD

**Issue by redknightlois** [dotnet/coreclr#11723]
I recently needed to use ```Interlocked.CompareExchange``` inside a function with the following form:

```csharp
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private bool TryClaimSlot(ref uint entryKey, int key)
        {
            var entryKeyValue = entryKey;
            //zero keys are claimed via hash
            if (entryKeyValue == 0 & key != 0)
            {
                entryKeyValue = Interlocked.CompareExchange(ref entryKey, key, 0);
                if (entryKeyValue == 0)
                {
                    // claimed a new slot
                    this.allocatedSlotCount.Increment();
                    return true;
                }
            }

            return key == entryKeyValue;
        }
```

problem is that it can´t be done because the ```Interlocked.CompareExchange<T>``` requires it to be a class.

Also if anyone knows a workaround for it, I would appreciate it.

**Comment by stephentoub** [comment]
> workaround

For uint, you could do something like:
```C#
static unsafe uint InterlockedCompareExchange(ref uint location, uint value, uint comparand)
{
    fixed (uint* ptr = &location)
    {
        return (uint)Interlocked.CompareExchange(ref *(int*)ptr, (int)value, (int)comparand);
    }
}
```

For ulong, same but with long instead of int overload.

For structs, not sure how that would work given platform limitations on what sizes can be worked with atomically, alignment, etc.

**Comment by stephentoub** [comment]
(And with System.Runtime.CompilerServices.Unsafe, you could do the same thing for uint/ulong but without the unsafe pointer stuff: https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/ref/System.Runtime.CompilerServices.Unsafe.cs#L19)

**Comment by redknightlois** [comment]
Great! Gonna use that.

**Comment by danmosemsft** [comment]
Do we still need an issue? Is there a proposal to add such API?

**Comment by redknightlois** [comment]
It feels strange that ```uint``` and ```ulong``` are not treated as first class citizens in ```Interlocked``` methods. So yes, the proposal is to add them.

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#26378
