### ISSUE TITLE
Build failure: CMake Error at CMakeLists.txt:411 (message):   Not Implemented! (using 32-bit cmake)

### ISSUE THREAD

**Issue by saper** [dotnet/coreclr#1173]
Using:

- pretty clean Win7 installation with VS2013 Update 4 (and not much else), 
- git checkout on   https://github.com/dotnet/coreclr/commit/ee26a59e352aa2beac79b2bb3b21176e9eb158cc with `core.autocrlf` set to `true`
- CMake 3.2.3 32-bit from http://www.cmake.org/files/v3.2/cmake-3.2.3-win32-x86.exe

CMake project does not intend to ship 64-bit cmake binaries: http://www.cmake.org/pipermail/cmake/2010-September/039375.html (statement from year 2010).

The build fails:

````
Commencing CoreCLR Repo build

Checking pre-requisites...

Commencing build of native components for Windows_NT.x64.Debug

CMake Error at CMakeLists.txt:411 (message):
  Not Implemented!


-- Configuring incomplete, errors occurred!
See also "E:/coreclr/bin/obj/Windows_NT.x64.Debug/CMakeFiles/CMakeOutput.log".
See also "E:/coreclr/bin/obj/Windows_NT.x64.Debug/CMakeFiles/CMakeError.log".
Failed to generate native component build project
````

Using `set(IS_64BIT_BUILD 1)` unconditionally fixes the build. I don't think that CMake platform should influence the build!

**Comment by janvorli** [comment]
What is the CMAKE_SYSTEM_PROCESSOR in your case? This is what determines the IS_64BIT_BUILD value.
>  I don't think that CMake platform should influence the build!

This is not the cmake platform, but the system platform. We don't currently support cross compilation (building x64 binaries on x86 Windows).

**Comment by saper** [comment]
On Thu, 25 Jun 2015, Jan Vorlicek wrote:

> What is the CMAKE_SYSTEM_PROCESSOR in your case? This is what determines the IS_64BIT_BUILD value.
> >  I don't think that CMake platform should influence the build!
> 
> This is not the cmake platform, but the system platform. We don't currently support cross compilation (building x64 binaries on x86 Windows).

But I am building on 64 bit Windows, only using 32-bit cmake (because there is nothing else).

**Comment by saper** [comment]
I am sorry - my error. This was indeed a 32-bit VM! Thanks!
