### ISSUE TITLE
Change release/2.0.0 branch auto-upgrade to pull from upstream 2.0.0 branches, not master

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#11754]
Right now, [`DependencyBranch`](https://github.com/dotnet/coreclr/blob/4312dc7ea6f437ebd4071b86600aa043d6ca73da/dependencies.props#L22) in dependencies.props is set to update to `master` builds. It should update to `release/2.0.0` builds, instead.

See https://github.com/dotnet/core-setup/pull/2455. We should probably wait to do this until we have successful 2.0.0-branch preview2 builds of each upstream product.

/cc @gkhanna79

**Comment by gkhanna79** [comment]
We have had clean builds of the 2.0.0 branches - is this a good time to fix the issue @dagood ?

**Comment by dagood** [comment]
Yes, I'll submit a PR.

**Comment by dagood** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/11786.
