### ISSUE TITLE
`System.IntPtr` and `System.UIntPtr` Improvements

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#11768]
### Rationale

The .NET framework provides the `System.IntPtr` and `System.UIntPtr` types which wrap the `native int` IL primitive (as per ECMA-335).

These types are frequently used to represent both handles/pointers and integers whose size depend on the underlying platform.

When being used to represent the latter (platform sized integer) type, users may find a difficult time performing some basic operations, such as comparing two `native ints` to determine sort order.

Additionally, with the proposed C# `Native Sized Number Types` (https://github.com/dotnet/csharplang/issues/435) where language support for the primitive operations will be exposed (currently this will be done via partial erasure), the use of `System.IntPtr` and `System.UIntPtr` as `native int` types will become more prevalent (F# is one language that already exposes these operators).

As such, these types should be modified to expose a set of APIs that make other common operations easier to perform.

### Proposed API

The proposed API here only shows the members that would be new to the types.

**System.IntPtr**
```C#
[StructLayout(LayoutKind.Sequential)] // This is implicitly set by the compiler, but should be explicitly declared, as it is done for System.Int32
public struct IntPtr : IComparable, IComparable<int>, IComparable<IntPtr>, IEquatable<int>, IFormattable
{
    public static readonly IntPtr MaxValue;
    public static readonly IntPtr MinValue;

    public static bool operator ==(IntPtr left, int right);
    public static bool operator !=(IntPtr left, int right);

    int IComparable.CompareTo(object value);    // Explicitly implemented to ensure that users still get compile-time type checking
    public int CompareTo(int value);            // ECMA-335 defines binary comparisons for IntPtr/int and IntPtr/IntPtr
    public int CompareTo(IntPtr value);

    public bool Equals(int other);              // ECMA-335 defines binary comparisons for IntPtr/int and IntPtr/IntPtr
    public bool Equals(IntPtr other);           // This is currently explicitly implemented as IEquatable<IntPtr>.Equals(IntPtr other)

    public string ToString(IFormatProvider provider);
    public string ToString(string format, IFormatProvider provider);

    public static IntPtr Parse(string s);
    public static IntPtr Parse(string s, NumberStyles style);
    public static IntPtr Parse(string s, IFormatProvider provider);
    public static IntPtr Parse(string s, NumberStyles style, IFormatProvider provider);

    public static bool TryParse(string s, out IntPtr result);
    public static bool TryParse(string s, NumberStyles style, IFormatProvider provider, out IntPtr result);
}
```

**System.UIntPtr**
```C#
public struct UIntPtr : IComparable, IComparable<uint>, IComparable<UIntPtr>, IEquatable<uint>, IFormattable
{
    public static readonly UIntPtr MaxValue;
    public static readonly UIntPtr MinValue;

    public static bool operator ==(UIntPtr left, uint right);
    public static bool operator !=(UIntPtr left, uint right);

    int IComparable.CompareTo(object value);    // Explicitly implemented to ensure that users still get compile-time type checking
    public int CompareTo(uint value);           // ECMA-335 defines binary comparisons for IntPtr/int and IntPtr/IntPtr
    public int CompareTo(UIntPtr value);

    public bool Equals(uint other);             // ECMA-335 defines binary comparisons for IntPtr/int and IntPtr/IntPtr
    public bool Equals(UIntPtr other);          // This is currently explicitly implemented as IEquatable<UIntPtr>.Equals(UIntPtr other)

    public string ToString(string format);      // This is currently exposed on System.IntPtr, but not on System.UIntPtr
    public string ToString(IFormatProvider provider);
    public string ToString(string format, IFormatProvider provider);

    public static UIntPtr Parse(string s);
    public static UIntPtr Parse(string s, NumberStyles style);
    public static UIntPtr Parse(string s, IFormatProvider provider);
    public static UIntPtr Parse(string s, NumberStyles style, IFormatProvider provider);

    public static bool TryParse(string s, out UIntPtr result);
    public static bool TryParse(string s, NumberStyles style, IFormatProvider provider, out UIntPtr result);
}
```

### Other Thoughts

Implementing `System.IConvertible` is done by the other primitive types and may be useful in some cases here as well.

It might be worthwhile having `int` implement `IComparable<IntPtr>` and `IEquatable<IntPtr>`, given that these are valid operations as well.

**Comment by tannergooding** [comment]
I have an implementation of this proposal here: https://github.com/tannergooding/coreclr/pull/1. If this is approved, I can submit a PR to dotnet/coreclr directly.

**Comment by AtsushiKan** [comment]
public int CompareTo(object value);

Could you make this one an explicitly implemented method, i.e.

    int IComparable.Compare(object value)

so that people who just want to call IntPtr.CompareTo(IntPtr) will continue to get the benefits of compile-time type checking?

**Comment by tannergooding** [comment]
@AtsushiKan, updated the proposal. I'll update my implementation sometime later this evening.

**Comment by tannergooding** [comment]
FYI. @jaredpar. This was the proposal I mentioned this morning.

**Comment by tannergooding** [comment]
Updated my implementation to make IComparable explicit and to implement Parse/TryParse as per the proposal.

**Comment by tannergooding** [comment]
@gkhanna79, should I move this to dotnet/corefx, so that it can get the appropriate `api-*` tags?

**Comment by jkotas** [comment]
Yes. This is new API proposal. The new API proposals should start in corefx repo, even if the actual implementation happens to live in the runtime. https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by tannergooding** [comment]
Ported to https://github.com/dotnet/corefx/issues/20256
