### ISSUE TITLE
Assembly.LoadModule/AssemblyBuilder.LoadModule Not Implemented by Design

### ISSUE THREAD

**Issue by evo01** [dotnet/coreclr#11760]
Howdy,

I am sure I am late to the party on this one, but what is the current reason why we are not supporting Assembly.LoadModule(string name, byte[] rawCoff) / AssemblyBuilder.LoadModule?  I noticed in .NET 4.0 this method was removed, just trying to understand why and what is the suggested workarounds?

Thanks in adavance!

Adam

**Comment by jkotas** [comment]
LoadModule is used to load multi-module assemblies. Multi-module assemblies are not supported by .NET Core.
