### ISSUE TITLE
Losing perf when simply handling command line args on Linux.

### ISSUE THREAD

**Issue by coffins** [dotnet/coreclr#1177]
Well, I don't know if here already exists the same issue, but this is a bit confusing stuff.

O-o-okay. When I write something like this:

```csharp
using System;

namespace AwesomeProgram
{
    static class AwesomeClass
    {
        static void Main(string[] args)
        {
            foreach (string arg in args)
                Console.WriteLine(arg);
            Console.ReadLine();
        }
    }
}
```

and execute this as described in .NET Core Getting Started for Linux (After switching into directory with all of the required content. JSON file and source code of program):

```
dnx . run arg
```
I have to wait at least 3 secs to see output of ```arg``` value (If I submit more than 1 arg, process performs even slower).
Moreover, runtime ignores the fact that I already pressed Enter and satisfied ```ReadLine()``` by doing this. Everything simply goes into a loop and I can go into another line as many times as I want until value of ```arg``` is pasted. It means that strong sequence of events is broken, doesn't it?

**Comment by miclen** [comment]
I've watched same problem!

**Comment by coffins** [comment]
At the moment (without package updates or changes at all) handling process decreased from recent 3 or more secs right to 1, 1.5 and 2 secs somehow using the same code as in example above.

1.5 was registered during single arg handling,
2 was registered during 12 args handling,
1 sec was registered during pure DNX execution (```dnx . run```).

**Comment by davidfowl** [comment]
@coffins I'm not sure that breakdown is completely accurate. Most of the time spent during `dnx . run` is spent doing dynamic roslyn compilation. It's also not cached across runs so you pay the cost everytime.

**Comment by saper** [comment]
Running this as `./corerun corebug1177.exe` on FreeBSD:

I get 3-4 seconds CLR startup time. When I press Ctrl-D or Enter during that time (e.g. right after beginning) the program exits after writing arguments. So it looks o.k. to me.

**Comment by coffins** [comment]
@davidfowl I'm confused about the main purpose of DNX at the moment at least on Linux, then. To treat performance decreasing I by far have to call ```mcs``` and then ```mono``` or just ```./AssemblyName.exe``` to deal with assembly without performance loses. Is there something special and really helpful except just-in-time run?

**Comment by stephentoub** [comment]
> Running this as ./corerun corebug1177.exe on FreeBSD. I get 3-4 seconds CLR startup time

@saper, is that using a debug or release CoreCLR?  I just tried this locally, and with a release build of CoreCLR this takes < 0.1 seconds for me locally on Linux.

**Comment by saper** [comment]
Debug

**Comment by stephentoub** [comment]
@saper, ok, phew, thanks.  CoreCLR does a large amount of verification in debug builds that's stripped out for release builds.  We run our corefx tests in the CI system using a release CoreCLR (with debug corefx assemblies) in part because we're focused on testing the corefx assemblies rather than the runtime, but in larger part because of the debug performance impact, which can be an order of magnitude or two.

**Comment by coffins** [comment]
So issue may be closed? @davidfowl described trouble clearly and @miclen  @stephentoub opened better issue. Or I'm not right?
