### ISSUE TITLE
Static constructor & properties

### ISSUE THREAD

**Issue by atameet** [dotnet/coreclr#11771]
Hello,

I have the following test code. While, I know the _order_ of the initializations for static properties with/without static constructor(beforefieldinit) present and the calling of the static constructor timing is based on different things . In my understanding, at least when we access the (static)property then it is understood that the (static)constructor would have been called for sure. Please correct me if I am wrong or I am missing something completely obvious :)

```
using System;
namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var v1 = D1.val;
            Console.WriteLine("Hello World:" + v1 + ":");
            new D1();
            var v2 = D1.val;
            Console.WriteLine("Hello World:" + v2 + ":");
            Console.WriteLine(v1==v2);
            Console.Read();
        }
    }
    public class B{   
        //static B(){}
        public static string val{get;set;}
    }
    public class D1:B{
        static D1(){
            val="d1";
        }
    }
}
```

Output:
```
Hello World::
Hello World:d1:
False
```
I am using:
dotnet --version
1.0.0-preview2-1-003177

Thanks

**Comment by benaadams** [comment]
You are asking whether calling a parent static property on a derived type should trigger the static constructor of the derived type?

**Comment by atameet** [comment]
Since you put it this way, I can see what is happening :) but as I had set the property in the derived class static constructor there was a confusion around _expectation_ especially since i was accessing via derived class. If the static constructor has to be called at some point I think it could be nice to call it now and saves from calculating ownerships especially in a long hierarchy. Thanks.

**Comment by benaadams** [comment]
Out of curiosity as you can't override static methods/properties, does the compiler give a warning that you should be calling `B.val` instead? As it would if you instead called it like:
```csharp
var d = new D1();
var v3 = d.val; // Compile warning, use type rather than instance instead
```

**Comment by atameet** [comment]
No, it has 0 Errors and 0 Warnings.
For the d.val example you mentioned it shows a compile error.

**Comment by AtsushiKan** [comment]
Yes, this isn't something that can be fixed at the runtime level - it's the way the C# language is (mis)designed - letting you type "D1.val" instead of "B.val" and leaving no trace of "D1" in the generated IL that would trigger a static class constructor execution or even issuing a warning.

I've seen  so much unncessary confusion and wasted time caused by this language "feature", including

- Unit tests that were testing nothing for years because people innocently typed:

    Assert.Equals(x, y)

   rather than

    Assert.Equal(x, y)

- SHA1Managed.Create() succeeds on a FIPs-configured machine. Oh no! MSRC event!

- SHA1Cng.Create() creates a CSP hash object. Huh?

**Comment by atameet** [comment]
Nice, thanks for sharing. 

As a positive, at least in the case for methods, the results would be consistent on repeated calls or different scenarios and the intellisense/return types may help. While, as a negative forcing (if was possible) the derived constructor still won't help. 

On the other hand, here the results here are inconsistent based on whether some other statement (like derived object created or owned static property accessed) was executed unknowingly prior to using the inherited variable. As a positive, forcing the derived constructor can help.

Very interesting to know about the IL detail. Having D1 would have been nice.

Not sure if this is something that is fixable or even want to be fixed. Perhaps an error may be the easiest in case of setting base static fields in derived static constructors.

**Comment by benaadams** [comment]
Could it give a warning? "Should call static method on parent type where its defined"? But better ;-)

**Comment by AtsushiKan** [comment]
Either https://github.com/dotnet/csharplang or https://github.com/dotnet/roslyn would be the place to raise this issue. Not sure which one "a new warning for an old construct" lands on - might browse the issues peope have raised to see where the wind blows on something like this.

**Comment by atameet** [comment]
Have raised it in Roslyn for now: [dotnet/roslyn/issues/19698](url)
May close this then. Thanks.
