### ISSUE TITLE
Test build failed. Predefined type 'System.Object' is not defined or imported.

### ISSUE THREAD

**Issue by svick** [dotnet/coreclr#1178]
I'm trying to compile the current version (dfddf41) of CoreCLR from source following [this guide](https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md), but the build fails.

When I run `build clean`, the end of the console output looks like this:

>   b460385 -> C:\Users\Svick\git\coreclr\bin\tests\Windows_NT.x64.Debug\JIT\Regression\VS-ia64-JIT\V2.0-RTM\b460385\b460385.exe
> C:\Users\Svick\git\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\packageresolve.targets(25,5): warning : Unable to resolve the assets of System.Console: Couldn't find a matching group [C:\Users\Svick\git\coreclr\tests\src\JIT\Methodical\VT\etc\_relhan3_ref.csproj]
> C:\Users\Svick\git\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\packageresolve.targets(25,5): warning : Unable to resolve the assets of System.Runtime: Couldn't find a matching group [C:\U sers\Svick\git\coreclr\tests\src\JIT\Methodical\VT\etc\_relhan3_ref.csproj]
> C:\Users\Svick\git\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\packageresolve.targets(25,5): warning : Unable to resolve the assets of System.Runtime.Extensions: Couldn't find a matching
group [C:\Users\Svick\git\coreclr\tests\src\JIT\Methodical\VT\etc\_relhan3_ref.csproj]
> CSC : error CS0518: Predefined type 'System.Object' is not defined or imported [C:\Users\Svick\git\coreclr\tests\src\JIT\Methodical\VT\etc\_relhan3_ref.csproj]
> Test build failed. Refer C:\Users\Svick\git\coreclr\tests\..\bin\Logs\Tests_Managed_Windows_NT__x64__Debug.log for details
> Test binaries build failed. Refer C:\Users\Svick\git\coreclr\bin\Logs\MScorlib_Windows_NT__x64__Debug.log for details.

Looking into Tests_Managed_Windows_NT__x64__Debug.log, it says "9799 Warning(s), 1636 Error(s)", but they seem to be repeats of the warnings and error from the above snippet. I would include the whole log here, but it's over 300 MB. Potentially interesting might be the csc command line corresponding to the above error:

> C:\Program Files (x86)\MSBuild\12.0\bin\Csc.exe /noconfig /nowarn:78,162,164,168,169,219,251,252,414,429,642,649,652,675,1691,1717,1718,1701,1702 /nostdlib+ /define:DEBUG;TRACE;SIGNED /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\mscorlib.dll" /debug+ /delaysign+ /filealign:512 /keyfile:C:\Users\Svick\git\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\MSFT.snk /out:C:\Users\Svick\git\coreclr\tests\..\bin\tests\obj\JIT\Methodical\VT\etc\_relhan3_ref.exe /target:exe /utf8output han3_ref.cs 

MScorlib_Windows_NT__x64__Debug.log says "Build succeeded. 0 Warning(s) 0 Error(s)".

Since those errors don't seem like they say much, where should I look for more information to figure out what's causing this and how to fix it?

It's certainly possible there's something wrong with my machine (it's far from a clean install). The machine is Windows 7 64-bit. I have VS Ultimate 2013 Update 4 installed (as well as several other versions of VS, including VS 2015 RC).

**Comment by akoeplinger** [comment]
Try uninstalling the Xamarin tools, see https://github.com/dotnet/corefx/issues/449

**Comment by svick** [comment]
Thanks, that worked. I can now build successfully.
