### ISSUE TITLE
The interop marshaller should recognize the 'IsReadOnly' attribute

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#11830]
The C# language is gaining support for `ref readonly` parameters (https://github.com/dotnet/roslyn/pull/19713 and https://github.com/dotnet/csharplang/issues/38).

Today the marshaller will treat `ref` as `[In, Out]` unless explicitly marked as just `[In]`. That is, by default, it will both initialize with the managed state and then copy back any changes to the instance on return. While, when explicitly marked with just the `[In]` attribute, it will only initialize with the managed state and will **not** copy back any changes on return.

Without modification, the marshaller will also treat `ref readonly` in the same way (`[In, Out]`). As such, the marshaller should be updated to handle and recognize `ref readonly` parameters as `[In]`.

**Comment by tannergooding** [comment]
FYI. @VSadov, @jaredpar

**Comment by yizhang82** [comment]
@tannergooding Thanks for logging the issue. Let's take the discussion there on the csharplang issue.

**Comment by tannergooding** [comment]
Closing this. C# 7.3 is going to ensure the attribute is added.

FYI. @OmarTawfik
