### ISSUE TITLE
Question: Current Status

### ISSUE THREAD

**Issue by borgdylan** [dotnet/coreclr#1184]
I have noticed that a lot of work has been done such as the ARM port. However the page at https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/developer-guide.md has not been updated at all. What is the current status of x86 (32 bit) since x64 seems to be almost done (assumed since ARM32 for Win10 IoT was demoed at NDC) and ARM was behind x86 in priority?

**Comment by shahid-pk** [comment]
no their is no progress on x86 as of yet.

**Comment by borgdylan** [comment]
Thanks. I am on 32 bit linux currently and will test coreclr whenever it starts building for x86.

**Comment by borgdylan** [comment]
A few months passed and there have been people working on ARM according to the logs. Will 32bit linux support be started by end of year?

**Comment by OtherCrashOverride** [comment]
Related to #1264

**Comment by borgdylan** [comment]
@OtherCrashOverride The referred to issue hasn't been updated in a while.

**Comment by RussKeldorph** [comment]
Windows/x86 is supported, and Linux/x86 can be tracked with arch-x86 and os-linux labels, e.g. #9265.
