### ISSUE TITLE
[RyuJIT/arm32] Assertion failed 'unreached' (emitarm.cpp:3048, emitter::emitIns_R_R_R())

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#11846]
At emitarm.cpp Line: 3048

Example:
```
Assert failure(PID 13636 [0x00003544], Thread: 5860 [0x16e4]): Assertion failed 'unreached' in 'ILGEN_0x38e69edd:main():int' (IL size 1014)

    File: c:\gh\coreclr\src\jit\emitarm.cpp Line: 3048
    Image: c:\brucefo\tests\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```

Tests with this assert:
```
GC\Scenarios\FinalNStruct\finalnstruct\finalnstruct.cmd
GC\Scenarios\FinalNStruct\nstructresur\nstructresur.cmd
GC\Scenarios\FinalNStruct\nstructtun\nstructtun.cmd
JIT\Methodical\Arrays\range\_il_relnegIndexRngChkElim\_il_relnegIndexRngChkElim.cmd
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b16499\b16499b\b16499b.cmd
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b16895\b16895\b16895.cmd
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b25491\b25491\b25491.cmd
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b39946\b39946\b39946.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b32613\b32613\b32613.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b34952\b34952\b34952.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b67987\b67987\b67987.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b73786\b73786\b73786.cmd
```

**Comment by hqueue** [comment]
It seems that all above 12 tests are passed by now.
I've tested with `b2150d5fc16eddec33702fd89168487d76f06108` (today) in Checked build on Rpi3.
Can anybody confirm ?

**Comment by mskvortsov** [comment]
Weren't these failures just hidden by the #11778?

**Comment by hqueue** [comment]
@mskvortsov Thank you for the information. I just look into this and didn't noticed that this was related issue. Then can I expect that your PR (https://github.com/dotnet/coreclr/pull/11205) will fix this too ?

**Comment by mskvortsov** [comment]
Yep, it should.

**Comment by alpencolt** [comment]
I've checked on master all tests are passed with `COMPlus_AltJitAssertOnNYI=0`.
Almost all methods are compiled by RyuJIT except few which are rolled to legacy with `NYI_ARM: Struct split between integer registers and stack`

@BruceForstall could you check on Windows NT ARM and close this issue?

**Comment by BruceForstall** [comment]
@alpencolt I've assigned the issue to myself. I've had trouble recently running arm32 on Windows, but I'll keep trying.

**Comment by BruceForstall** [comment]
I verified these all pass now.
