### ISSUE TITLE
Missing dotnetcore.dll

### ISSUE THREAD

**Issue by ddobric** [dotnet/coreclr#11857]
When executing
`dotnet publish -c Release -r win10-x86`
I figured out that assembly _dotnetcore.dll_ is missing.
There is no any issue with this, just want to understand why.

Following
`dotnet publish -c Release -r win10-x64`

generates the named assembly in publish folder.

**Comment by gkhanna79** [comment]
Issue moved to [dotnet/cli #6673](https://github.com/dotnet/cli/issues/6673) via [**ZenHub**](https://www.zenhub.com/)
