### ISSUE TITLE
Incorrect Assert in Lazy<>::Value getter

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/coreclr#1186]
See https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/mscorlib/src/System/Lazy.cs#L325:
```csharp
LazyInternalExceptionHolder exc = m_boxed as LazyInternalExceptionHolder;
Contract.Assert(m_boxed != null);
exc.m_edi.Throw();
```
I think, `Contract.Assert(exc != null);` should be here.

**Comment by stephentoub** [comment]
Yes, the assert is wrong and should be ```exc``` rather than ```m_boxed``` as you call out.

**Comment by ViIvanov** [comment]
Can I create a PR for fix this? Or you will fix this someday?

**Comment by stephentoub** [comment]
Go for it :smile:
