### ISSUE TITLE
[Arm64] GCStress not thread safe

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#11877]
There are two GCStress issues which have appeared to be GCStress infrastructure issues related to updating a GCStress instruction from multiple threads.

This one has occurred 7+ times in 10+ runs
```
Consistency check failed: FAILED: !pThread->HasPendingGCStressInstructionUpdate()
    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/vm/gccover.cpp Line: 1771
```

This one has only occurred once....
```
/usr/bin/time /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/corerun thread20.exe

Assert failure(PID 19023 [0x00004a4f], Thread: 21060 [0x5244]): instrVal == *(DWORD *)(gcCover->savedCode + offset)
    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/vm/gccover.cpp Line: 1464
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/corerun


Assert failure(PID 19023 [0x00004a4f], Thread: 21036 [0x522c]): instrVal == *(DWORD *)(gcCover->savedCode + offset)
    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/vm/gccover.cpp Line: 1464
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/corerun


Assert failure(PID 19023 [0x00004a4f], Thread: 21083 [0x525b]): instrVal == *(DWORD *)(gcCover->savedCode + offset)
    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/vm/gccover.cpp Line: 1464
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/corerun
```

**Comment by sdmaclea** [comment]
@swgillespie @Maoni0

**Comment by Maoni0** [comment]
@RussKeldorph could someone from your team please take a look?

**Comment by RussKeldorph** [comment]
Pretty sure the first issue is #5310.  @swaroop-sridhar investigated it for a while and came to the conclusion that it is not easy to fix.  @jkotas may have an opinion as well.

I don't recall seeing the second issue before, but I'd guess it's another race condition that is only likely (or possible) to hit due to ARM's weaker-than-x86 memory model.

**Comment by sdmaclea** [comment]
@RussKeldorph Looks like #5310 is marked as fixed (which is why I could not find the issue you mentioned in the meeting).  However, but some of the changes are missing for arm64.  That should be enough for me to try to fix the first part.

The second one did indeed look very rare, Three threads hitting the same assert!

**Comment by sdmaclea** [comment]
@RussKeldorph I had stopped reading #5310 when I saw t was closed, but didn't realize it had been reopened (for x86 & arm64).  Looks like @rahku made a separate fix for this for arm64 in #6418.  But the fix looks fragile, I'll take a look at the tip and see if there is something broken/missing.

**Comment by janvorli** [comment]
@sdmaclea can this issue be closed now?

**Comment by sdmaclea** [comment]
Closing this is redundant with #5310.
