### ISSUE TITLE
[Question] Testing DAC compliance of changes in code base

### ISSUE THREAD

**Issue by ruben-ayrapetyan** [dotnet/coreclr#11879]
Hello.

What is the sufficient way to test changes that involve DAC-mode?

I think of running debugger tests as one of possible ways.
However, may be it doesn't provide enough coverage for changed code paths.

Also, I think of a special build configuration, which would allow to run general test suite, while checking the executed code paths for DAC-compliance.
Is there any existing build configuration that would allow this?

**Comment by ruben-ayrapetyan** [comment]
cc: @jkotas @mikem8361

**Comment by mikem8361** [comment]
I know of no special build that would test the DAC. The debugger test suite is it. We currently don't have the resources to do a special build configuration.  I'm not sure if it is even possible to really test the DAC that way.

**Comment by ruben-ayrapetyan** [comment]
@mikem8361, thank you for your answer.

Would it be possible to add debugger test suite in CI, to perform the check automatically?
As far as I know, the test suite is currently internal and so its contents are not available to public.
However, can it be possible to add the test suite to a CI job with only `PASS`/`FAIL` statuses, without opening the test suite to public?

**Comment by mikem8361** [comment]
We are working on doing that.  Not sure the exactly schedule because it requires some general test/CI infrastructure work to allow to use a private repo (debuggertests) in a public one (coreclr).

/cc: @Lorenzo Tessiore<mailto:lorenzte@microsoft.com>

**Comment by ruben-ayrapetyan** [comment]
@mikem8361, we currently work on set of changes that can significantly affect DAC functionality (the first of them is pull request #11394). Until the CI is not available, could we ask you to check the changes using the debugger test suite, when we will consider the changes are ready from other view points?
