### ISSUE TITLE
Assembly.Load(AssemblyLoadContext.GetAssemblyName(@"...")) throws unexpected exception

### ISSUE THREAD

**Issue by hpaiemen** [dotnet/coreclr#1187]
Hi,
I'm currently trying to port code from full framework 4.6 to DNX Core 5 and I encounter most of my problems with the new reflection API. Here is my problem :

I need to import at run time (dynamically) some assemblies that can be saved anywhere on disk. So the user most specify an absolute path for the assembly to be loaded. In full framework, I used `Assembly.LoadFrom(string asmPath)` method to get the job done. But, after doing some searches on compatibility with DNX Core 5, I understood that it wasn't (yet?) available.

I tried something with `AssemblyName` here is the result :

Empty class to import:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    public class Class1
    {
        public Class1()
        {
        }
    }
}
```
Test program :
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Reflection;
using System.Runtime.Loader;

namespace ConsoleApp1
{
    public class Program
    {
        public void Main(string[] args)
        {
            try
            {
                Assembly myAssembly = Assembly.Load(AssemblyLoadContext.GetAssemblyName(@"C:\ClassLibrary1.dll"));
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
                Console.ReadLine();
            }

        }
    }
}
```
Now the console output when running `ConsoleApp1` :
`Assembly.Load with a Codebase is not supported on Windows Phone.`

First, error message is probably not up to date since I don't target Windows Phone device (I used `vNext class library` and `vNext console app` in Visual Studio 2015 RC), and I would like to know if `Assembly.LoadFrom(string asmPath)` will be implemented for DNX Core 5 and if not, how can I load assemblies from their absolute (or relative) path on disk ?

Thx !

**Comment by kouvel** [comment]
You would have to use a custom `AssemblyLoadContext` to control assembly loading. See https://github.com/dotnet/corefx/tree/master/src/System.Runtime.Loader/tests for examples on how to use it. You can use the `LoadFromAssemblyName` method on an instance of the custom load context and in the overridden `Load` method, determine the path from which to load the assembly.

**Comment by jkotas** [comment]
Assembly.Load(AssemblyLoadContext.GetAssemblyName(@"...")) 

Actual: throws "Assembly.Load with a Codebase is not supported on Windows Phone" exception
Expected: work fine
