### ISSUE TITLE
[RyuJIT/arm32] All test failed after recent commit

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#11870]
After e5d76089a7af352759ed395ecc3c2e61bd6f9640 (https://github.com/dotnet/coreclr/pull/10275), all test failed with AltJit (ryujit/arm32) due to following exception.

```
FAILED   - [   0][   2s]JIT/CodeGenBringUpTests/Add1/Add1.sh
               BEGIN EXECUTION
               /mnt/albireo/mywork/device/rpi3/unittests/coreoverlays/coreoverlay.test20170524.checked.master/corerun Add1.exe
               
               Assert failure(PID 26798 [0x000068ae], Thread: 26798 [0x68ae]): Assertion failed 'block != nullptr' in 'System.Text.StringBuilder:VerifyClassInvariant():this' (IL size 226)
               
                   File: /opt/code/github/hqueue/coreclr/src/jit/flowgraph.cpp Line: 1033
                   Image: /mnt/albireo/mywork/device/rpi3/unittests/coreoverlays/coreoverlay.test20170524.checked.master/corerun
               
               ./Add1.sh: line 240: 26798 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED

```

For example, all tests in  `JIT/CodeGenBringUpTests` are passed with `COMPlus_AltJit=* COMPlus_AltJitAssertOnNYI=0` before the commit, but now all failed.

**Comment by hqueue** [comment]
FWIW At least 1st commit(7a4b14e5366bba52d188695c803c9e27e103d362 ) from https://github.com/dotnet/coreclr/pull/10275 works well with ryujit/arm32.
It seems that 2nd commit(https://github.com/dotnet/coreclr/commit/e5d76089a7af352759ed395ecc3c2e61bd6f9640) is not working well with ryujit/arm32.

**Comment by hqueue** [comment]
```
#ifndef _TARGET_64BIT_
    if (cmp->gtGetOp1()->TypeGet() == TYP_LONG)
    {
// TODO-ARM: This code should be enabled for ARM32 once support for GT_CMP and GT_SETCC is added.
#if _TARGET_X86_
```

It seems that it was expected failure, because ryujit/arm32 does not support GT_CMP and GT_SETCC yet.

For now, it would be better to avoid this code for ryujit/arm32, because it blocks other implemenation by now. I will make a PR soon.

**Comment by mikedn** [comment]
> It seems that it was expected failure, because ryujit/arm32 does not support GT_CMP and GT_SETCC yet.

That code is only enabled for X86, am I missing something?

**Comment by hqueue** [comment]
@mikedn I think the condition matters. Please take a look at the PR I just made. I didn't look into deep the path of compile phases yet. I just revert the commit for arm32 by now.

**Comment by hqueue** [comment]
@mikedn I also don't know why the condition matters. Do you have any idea?
