### ISSUE TITLE
System.ServiceModel not found when referencing a .net full dll in net core 2.0 preview

### ISSUE THREAD

**Issue by agonzalezm** [dotnet/coreclr#11874]
I have referenced a full .net dll in a net core 2.0 preview project but when i try to use one of their methods i get this exception. I tried to copy System.ServiceMode dll to project folder but didnt work. Is there any solution or workaround?

System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at VMware.Vim.VimClientImpl.Connect()
   at VMware.Vim.VimClientImpl.Connect(String server, Nullable`1 protocol, Nullable`1 port)
   at ConsoleApp2.Operations.<Connect>b__8_0() in c:\users\documents\visual studio 2017\Projects\ConsoleApp2\Program.cs:line 47
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by karelz** [comment]
@zhenlan this is WCF component. Any idea why it would be missing in .NET Core 2.0 preview? Is it packaging/setup problem?

**Comment by zhenlan** [comment]
Yes, ServiceModel is WCF, but I am not sure the way @agonzalezm using it is supported by clr(referencing a full framework assembly in a 2.0 net core app).

@agonzalezm is there any reason you choose not to use WCF for .net core packages in your 2.0 app? You can find more info of WCF for .net core 2.0.0 preview 1 release [here](https://github.com/dotnet/wcf/releases/tag/v2.0.0-preview1).

**Comment by agonzalezm** [comment]
i am not using WCF in my app, i am just referencing a vmware library dll that uses it and when i try to use a method on that library i get that error.

**Comment by karelz** [comment]
Can you point us to the VMWare library? Is it targeting .NET Core?

**Comment by agonzalezm** [comment]
No, this one is not targetting .net core, it targets full net framework.

But they also have a .net core version of the dll with some limitations but also i get not found error.

The .net core version is here: https://labs.vmware.com/flings/powercli-core

Download the zip and unzip.
Inside the folder now unzip PowerCLI.ViCore.zip
Reference PowerCLI_Core\PowerCLI.ViCore\VMware.Vim.dll

Create a console app and run:

        static void Main(string[] args)
        {
            var c = new VimClientImpl();
            c.Connect("localhost", CommunicationProtocol.Https, 443);           
        }

I get error:

System.IO.FileNotFoundException: 'Could not load file or assembly 'VMware.Vim, Version=6.5.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'

**Comment by karelz** [comment]
Did you ask VMWare why you are getting the exception on the .NET Core DLL? It looks like that should not happen.

**Comment by agonzalezm** [comment]
I asked in that page but I didnt get a reply. They are using it because their powershell modules are based on that dll and work.

**Comment by agonzalezm** [comment]
So their .full net 4.X library is not supported in net core 2.0 because it requires WCF?

**Comment by zhenlan** [comment]
Even if it's not WCF I am afraid it could fail with something else. Please use .NET Core version.

**Comment by agonzalezm** [comment]
Ok, and any idea why when adding reference to the path of the the .net core dll version then when running it cant find it? 

There error i get is like this from newtonsoft.json but i tried workaround there and didnt work: https://github.com/dotnet/cli/issues/3967

**Comment by danmosemsft** [comment]
@agonzalezm this issue is stale a long time, I 'm going to assume it is resolved. Please reopen if not.
