### ISSUE TITLE
EventPipe: Feature Request: Support EventSource RichPayload events

### ISSUE THREAD

**Issue by northtyphoon** [dotnet/coreclr#11939]
Here is the sample code to emit richpayload events. 

[EventSource(Name = "TestEventSource", Guid = "c68d147f-ede2-4960-af7d-aca72ae34807")]
    public class TestEventSource : EventSource
    {
        public class Keywords
        {
            public const EventKeywords Request = (EventKeywords)1;
        }

        public static TestEventSource Log = new TestEventSource();

        private TestEventSource()
        {
        }
        
        public void RequestStart(int intArg, string strArg)
        {
            Console.WriteLine($"{nameof(RequestStart)},{intArg},{strArg}");
            Write(
                "Request", 
                new EventSourceOptions { Keywords = Keywords.Request, Opcode = EventOpcode.Start, Level = EventLevel.Informational },
                new { IntArg = intArg, strArg = strArg }
            );
        }

        public void RequestStop(int intArg, string strArg)
        {
            Console.WriteLine($"{nameof(RequestStop)},{intArg},{strArg}");
            Write(
                "Request", 
                new EventSourceOptions { Keywords = Keywords.Request, Opcode = EventOpcode.Stop, Level = EventLevel.Informational },
                new { IntArg = intArg, strArg = strArg }
            );
        }        
    }

**Comment by brianrob** [comment]
Marking this for consideration in 2.1.
