### ISSUE TITLE
C# Async/Await optimization bug

### ISSUE THREAD

**Issue by deniszykov** [dotnet/coreclr#11954]
I've encountered a strange bug related compiler optimizaton and try/finally in async/await block.
I got small repro which reproduces this bug. This error appeared when the project was compiled by VS 2015 (and as I understood it by the new compiler). Before that, there was no problem.

https://gist.github.com/deniszykov/9a9dcd4f6fb5ea7905b8a15e5bc7d0c0

If /optimize is turned off it will runs fine. But in Release mode (and with /optimize) it will crash with NRE.

**Comment by 0xd4d** [comment]
You'll have more luck over here: https://github.com/dotnet/roslyn/issues/

The C# compiler stores the value in a local in the state machine method, but it's not always initialized. Workaround (for this example) is to **not** store the stream in a local, but just use `containerClass.ReadStream` all the time.

**Comment by deniszykov** [comment]
Thanks for workaround. I posted new issue https://github.com/dotnet/roslyn/issues/19831 in Roslyn repository.
