### ISSUE TITLE
Cannot use Reset() with Dictionary<TKey,TValue>.Enumerator without causing a boxing allocation.

### ISSUE THREAD

**Issue by bbi-yggy** [dotnet/coreclr#11965]
`Dictionary<TKey,TValue>.Enumerator` is a struct in order to allow dictionary iteration without boxing allocations. However, it only implements Reset() as an explicit implementation of IEnumerator.Reset - this means you cannot call Reset directly on an instance of `Dictionary<TKey,TValue>.Enumerator`.

If you cast the instance to IEnumerator and reset the result, you are boxing a copy of the enumerator and resetting that copy, not the instance itself.

Alternatively, if you get the iterator as `IEnumerator<KeyValuePair<TKey,TValue>>` in the first place, then you can Reset, but you've already caused a boxing allocation.

The following NUnit test case demonstrates the issue ...
```
[Test]
[Explicit("Test provided to demonstrate a curiousity about Dictionary<TKey,TValue>.Enumerator.Reset()")]
public static void DictionaryEnumeratorReset()
{
    Dictionary<int, string> dict = new Dictionary<int, string>();
    dict.Add(1, "1");
    dict.Add(2, "2");

    Dictionary<int,string>.Enumerator iterator = dict.GetEnumerator();
    int n = 0;
    while (iterator.MoveNext())
    {
        ++n;
    }
    Assert.AreEqual(dict.Count, n);

    // Reset the iterator and make sure it can iterate again.
    // NOPE! Since casting == boxing == copying - this resets *a copy of* iterator, not iterator itself!
    ((IEnumerator<KeyValuePair<int, string>>)iterator).Reset();
    n = 0;
    while (iterator.MoveNext())
    {
        ++n;
    }
    Assert.AreEqual(dict.Count, n);   // This will fail, because n is still 0.
}
```

**Comment by mikedn** [comment]
> The following NUnit test case demonstrates the problem ...

It's not clear what the problem really is. That your code resets a copy of the enumerator is normal, that's just how value types & boxing work. Are you in fact complaining about the Enumerator struct not offering a public Reset method that can be called without boxing?

**Comment by bbi-yggy** [comment]
Yup, exactly. Dictionary.Enumerator is a public struct *precisely* to avoid boxing allocations, but the way it implements Reset forces you back to a boxing allocation. Good point though, I'll amend the title and description to reflect this.

**Comment by mikedn** [comment]
>  but the way it implements Reset forces you back to a boxing allocation

Yes, but the idea is that you're not supposed to use `Reset`. The struct enumerator only implements `Reset` because `IEnumerator` requires it and `IEnumerator` has `Reset` because it was trying to mirror COM's `IEnumObjects` interface. So many struct enumerators (e.g. List<T>.Enumerator is identical in this regard) expose only what's needed for `foreach` to work - `MoveNext` and `Current`.

**Comment by bbi-yggy** [comment]
It's true that explicit use of MoveNext / Current / Reset is the exception rather than the rule, but it would be nice if the implementation permitted boxing-free use of Reset.

**Comment by justinvp** [comment]
You can call `Reset` on the struct enumerator without boxing with the help of a generic helper method, e.g.:

```c#
internal static class EnumeratorHelpers
{
    internal static void Reset<TEnumerator>(ref TEnumerator enumerator) where TEnumerator : IEnumerator
    {
        enumerator.Reset();
    }
}
```

Usage:

```c#
Dictionary<int,string>.Enumerator iterator = dict.GetEnumerator();
EnumeratorHelpers.Reset(ref iterator);
```

**Comment by bbi-yggy** [comment]
Oh, good idea! We do generic tricks like that all the time, I should have thought of that. I'll try that in the morning and resolve this issue if it works. Thanks @justinvp for the suggestion.

**Comment by bbi-yggy** [comment]
Yes, that's perfect, thanks again.
