### ISSUE TITLE
Long data format in lv-LV culture is wrong

### ISSUE THREAD

**Issue by simonech** [dotnet/coreclr#11964]
The format in which dates are formatted in Latvian is wrong;

d - `29.05.2017.`
D - pirmdiena, `2017. gada 29. maijs`
LongDatePattern: dddd, yyyy'. gada 'd. MMMM

According to [Latvian law](https://likumi.lv/ta/id/219491-dokumentu-izstradasanas-un-noformesanas-kartiba#p-363332) the long date format should be without the day of week part, so just `2017.gada 3.maijā`
Also there should be no space after the dot, and the month of May is written in the wrong case.

I understand this stuff probably comes from ages ago and probably comes straight from some Win32 API... but it's wrong :)

**Comment by janvorli** [comment]
@simonech since you mentioned Win32, I assume this problem occured on Windows for you. Am I right?

**Comment by simonech** [comment]
The code that retrieves the data calls [Interop.Kernel32.GetLocaleInfoEx](https://github.com/dotnet/coreclr/blob/1a3dfa8c8405fa56ea3de897c43d79650463e74c/src/mscorlib/src/System/Globalization/CultureData.Windows.cs#L199) to get the CultureData so I guess it comes from Win32.

Indeed, also when switching to lv-LV in windows I get the same mistakes

**Comment by danmosemsft** [comment]
@tarekgh how to report this to OS team?

**Comment by tarekgh** [comment]
@simonech which version of Windows you are running on? I need the info to report the issue to Windows team. 

I suggest you report it through the Windows insider too https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_web/how-do-i-submit-a-bug-report-for-windows-10/315a900d-8148-44a1-8fd0-829fb9a4ce03

**Comment by tarekgh** [comment]
I have reported the issue to Windows team and I am closing the issue here as no more action can be done from coreclr side. 

@simonech feel free to add any more comments and info as needed and I'll update the issue too if got any feedback from Windows team.

**Comment by jefgen** [comment]
Thank you for taking the time to report this issue.

The Windows locale data for lv-LV is aligned with the data from **CLDR** - The Unicode Common Locale Data Repository ( http://cldr.unicode.org/ 

The long data format from Windows is consistent with the data format from **CLDR** and **ICU** - International Components for Unicode ( http://site.icu-project.org/ )

You can use the ICU [Locale Explorer](http://demo.icu-project.org/icu-bin/locexp?d_=en&_=lv_LV) tool to view the long date formats for the locale `lv-LV`.

For example, the format for "Long Date" is: `2017. gada 31. maijs`

That said, it is possible that the data in CLDR/ICU is incorrect for this locale.

However, this could also be a case where the _official_ date formats differ from _common usage_ date formats.
Generally speaking, CLDR tends to lean towards using formats/patterns that are in 'common/active use'.

CLDR is a collaborative project which encourages people join and contribute. Anyone can submit data to CLDR.

CLDR is currently in an active contribution phase, and you can engage with linguists if you are a native speaker of the language. If you are not a native speaker, but would still like to contribute, we can start a discussion in the linguist forums with your report and ask for more data.

Thanks again!

**Comment by simonech** [comment]
Thank you everyone for the comments and explanations.
It's not about Windows 10, but on servers, as I have a website that needs to be localised in 24 languages, and being a governement site it needs to use the "legal" date formatting, which is different from the one provided by windows locale.
I guess I'll have to create my own `DateTimeFormat` for each of the languages in which formatting is different from one given by Windows.

**Comment by simonech** [comment]
@jefgen anyway... the Long Date pattern in Windows for Latvian is formatting the data using the Full Date format used in the ICU explorer.
So if it was supposed to use the Long Data, it is still a bug

**Comment by simonech** [comment]
I think the problem is that in .NET there is just:

- Short Date (d)
- Long Date (D)
- Full Date Short Time (f)
- Full Date Long Time (F)

But it misses the Full Date format, while the CLDR/ICU has Long Date (which is without day of week) and Full Date (which has day of week).
So, apparently, in some languages Windows uses the Long Date and in other the Full Date.

```
bg-BG - 29.5.2017 г. - 29 май 2017 г.
es-ES - 29/05/2017 - lunes, 29 de mayo de 2017
cs-CZ - 29. 5. 2017 - 29. května 2017
da-DK - 29-05-2017 - 29. maj 2017
et-EE - 29.05.2017 - 29. mai 2017
el-GR - 29/5/2017 - Δευτέρα, 29 Μαΐου 2017
fr-FR - 29/05/2017 - lundi 29 mai 2017
ga-IE - 29/05/2017 - 29 Bealtaine 2017
hr-HR - 29.5.2017. - 29. svibnja 2017.
it-IT - 29/05/2017 - lunedì 29 maggio 2017
lv-LV - 29.05.2017. - pirmdiena, 2017. gada 29. maijs
lt-LT - 2017-05-29 - 2017 m. gegužės 29 d.
hu-HU - 2017.05.29. - 2017. május 29.
mt-MT - 29/05/2017 - It-Tnejn, 29 ta' Mejju 2017
nl-NL - 29-5-2017 - maandag 29 mei 2017
pl-PL - 2017-05-29 - 29 maja 2017
pt-PT - 29/05/2017 - 29 de maio de 2017
ro-RO - 29.05.2017 - 29 mai 2017
sk-SK - 29.5.2017 - 29. mája 2017
sl-SL - 29.5.2017 - 29. maj 2017
fi-FI - 29.5.2017 - 29. toukokuuta 2017
sv-SE - 2017-05-29 - den 29 maj 2017
```

**Comment by jefgen** [comment]
Thanks @simonech.

Broadly speaking, the locale data in both Windows and CLDR/ICU lean towards using formats that are in common/active usage.

Note that there are actually **two** 'Long Date' patterns for lv-LV in Windows, which map to the _'full'_ and _'long'_ date patterns in CLDR/ICU.

The data for lv-LV actually has both:
   `<SLONGDATE>dddd, yyyy. 'gada' d. MMMM;yyyy. 'gada' d. MMMM;</SLONGDATE>`

However, I don't think the _second_ one is exposed in .NET directly.
You **might** be able to get at using `GetAllDateTimePatterns()`, but I'm not 100% sure to be honest.

**Comment by tarekgh** [comment]
Calling 

```C#
            CultureInfo ci = new CultureInfo("lv-LV");
            ci.DateTimeFormat.GetAllDateTimePatterns('D');
```

Will give you all supported long dates which include what @jefgen mentioned above

```
dddd, yyyy. 'gada' d. MMMM
yyyy. 'gada' d. MMMM
```

The first one is the default. if you want to set the second one is the default for the culture, yo may do 

```C#
            ci.DateTimeFormat.SetAllDateTimePatterns(new string[] { @"yyyy. 'gada' d. MMMM", @"dddd, yyyy. 'gada' d. MMMM" }, 'D');

```

And if you want to use these as the default for current culture, you may 

```C#
            CultureInfo.CurrentCulture = ci;
```
