### ISSUE TITLE
using daily build nuget package

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#11970]
https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/OfficalAndDailyBuilds.md
describes the use of the Microsoft.NETCore.Runtime.CoreCLR NuGet package at https://dotnet.myget.org/gallery/dotnet-core.

I'm unable to make an application that consumes this package.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <packageSources>
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json"/>
 </packageSources>
</configuration>
```

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR" Version="2.1.0-preview1-25330-01"/>
  </ItemGroup>
</Project>
```

```
using System;

namespace consoleapp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

```
$ dotnet restore -r linux-x64
$ dotnet publish -r linux-x64 --self-contained true
```
The version in the publish folder is:
```
$ strings bin/Debug/netcoreapp2.0/linux-x64/publish/libcoreclr.so | grep '@(#)'
@(#)Version 4.6.25302.01 built by: root-/tmp/tmp46857c8743c94ff2ab1fbff79bf87042.exec.cmd: line 2: hostname: command not found. Commit Hash: ea50f78e431f325c4382c21e9b91c3e76898ba1e
```
While the version in the NuGet package is:
```
$ strings ~/.nuget/packages/runtime.linux-x64.microsoft.netcore.runtime.coreclr/2.1.0-preview1-25330-01/runtimes/linux-x64/native/libcoreclr.so | grep '@(#)'
@(#)Version 4.6.25330.01 built by: root-/tmp/tmp8694902894184f4b92358bf5e3aab61b.exec.cmd: line 2: hostname: command not found. Commit Hash: ee454e11d0c73820dde10ab710f9d6eccd4471f1
```

**Comment by tmds** [comment]
I updated the csproj file to set a RuntimeFrameworkVersion.
```
    <RuntimeFrameworkVersion>2.1.0-preview1-*</RuntimeFrameworkVersion>
```
This gives me the coreclr that is part of the Microsoft.NETCore.App package.
```
$ strings bin/Debug/netcoreapp2.0/linux-x64/publish/libcoreclr.so | grep '@(#)'
@(#)Version 4.6.25324.01 built by: root-/tmp/tmp492deba5d92e49c995a7ea5a131c9e3f.exec.cmd: line 2: hostname: command not found. Commit Hash: a125a6e786f09045a28a7d3e4a2c612602f9d220
$ strings ~/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.0-preview1-25329-02/runtimes/linux-x64/native/libcoreclr.so | grep '@(#)'
@(#)Version 4.6.25324.01 built by: root-/tmp/tmp492deba5d92e49c995a7ea5a131c9e3f.exec.cmd: line 2: hostname: command not found. Commit Hash: a125a6e786f09045a28a7d3e4a2c612602f9d220
```

**Comment by janvorli** [comment]
@gkhanna79 unrelated to this issue, I've noticed in the version dumped above, that we have a bug in the script that generates the version string. See the `line 2: hostname: command not found.` in the version string.

**Comment by gkhanna79** [comment]
@joperezr @dagood Can you PTAL?

**Comment by gkhanna79** [comment]
@joperezr We should look into this for Escrow.

**Comment by joperezr** [comment]
I'll take a look into the version string issue. As to the fact that this package can't be referenced directly, the user scenario should be to never have to add a reference to it, since what you really want is to use the one that comes with Microsoft.NETCore.App package as the framework is very closely tied to the runtime so you don't want to manually specify a different runtime that might be incompatible with the framework. The right thing to do, is to only set `<RuntimeFrameworkVersion>` as you tried later.

**Comment by joperezr** [comment]
So the issue seems to be that `hostname` command is not part of our docker image files where we build for some distros (like the one for rhel for example) which is why we are now getting this error. I talk to @ellismg offline and there are basically two ways to fix this, either by adding `hostname` to our docker image files for all distros or by checking instead checking the exitcode of that command, and in case it is non-zero then we can simply not include the BuiltByString in the version info since it is not really relevant for official builds. 

@gkhanna79 thoughts?

**Comment by gkhanna79** [comment]
@joperezr Is this a recent regression?

> we can simply not include the BuiltByString in the version info since it is not really relevant for official builds

I do not see much value of the name of the machine that built it as well and would be fine removing it. @weshaggard What do you think?

**Comment by ellismg** [comment]
> I do not see much value of the name of the machine that built it as well and would be fine removing it. @weshaggard What do you think?

Note that because of how we do our official builds, the builder is always "root" and the hostname is some random string corresponding to the transient container we build in, so after the fact the information isn't really useful.

**Comment by weshaggard** [comment]
While I agree the particular value isn't high it is still a good hint that it was built from an official build as opposed to some private build which is the primary motivation for having that value. 

@tmds I think the instructions at https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md are a little more up to date with the current tooling. I suspect the thing you are missing is making your project self-contained, https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md#change-project-to-be-self-contained. If you don't do that they you will be running on the shared framework and cannot override the runtime in the shared framework.

**Comment by tmds** [comment]
Closed by https://github.com/dotnet/coreclr/pull/12056
