### ISSUE TITLE
"Testing with CoreFX" documentation incorrect?

### ISSUE THREAD

**Issue by justinvp** [dotnet/coreclr#1197]
I wanted to run the CoreFX System.Runtime tests to test some mscorlib changes.

The instructions detailed [here](https://github.com/dotnet/coreclr/blob/master/Documentation/building/testing-with-corefx.md) don't seem to work.

The CoreCLR package was correctly published to the location I specified in `InstallationLocation` (`C:\dev\corefx\packages` on my machine), but when I ran `msbuild /t:BuildAndTest` from `C:\dev\corefx\src\System.Runtime\tests`, it didn't run the tests with the locally published CoreCLR package.

In order to run the tests against my changes, I had to manually copy/replace the locally built CoreCLR dll's into `C:\dev\corefx\bin\tests\Windows_NT.AnyCPU.Debug\System.Runtime.Tests\dnxcore50`.

Is the documentation incorrect, or am I doing something wrong?

Thanks!

**Comment by justinvp** [comment]
Note: The example `localpublish.props` content in the doc wasn't rendering on GitHub correctly; the only way to see it was to look at the raw markdown. I submitted #1196 to address this.

**Comment by ellismg** [comment]
Sorry, Justin.  I don't have any expertise here, I'm on the copy everything into dnxcore50 plan, but maybe @blackdwarf, who wrote the instructions knows how this is supposed to work?

**Comment by blackdwarf** [comment]
I would have to ask @terrajobst to take a look.

**Comment by weshaggard** [comment]
I think the instructions are no longer correct as we don't use Microsoft.DotNet.CoreCLR package any more after @ericstj switch to using Microsoft.NETCore.Runtime.CoreCLR-x86 in corefx. Looks like we need to figure out the right workflow and update the instructions.

**Comment by jkotas** [comment]
Fixed a long time ago
