### ISSUE TITLE
Various file descriptors being inherited into child processes

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#11982]
I'm seeing a fair number of file descriptors from the runtime being inherited into child processes spawned via Process.Start.  These fall into two camps:
- A bunch of file descriptors for /dev/zero
- A few file descriptors for anonymous pipes

This gets amplified as child processes create their own child processes, as the grandchild inherits all of these file descriptors from the parent and grandparent, and so on.  A simple hello world that spawns a child has ~30 file descriptors open; by the time this gets to the 10th level descendent, that descendent has ~250 file descriptors open before it's even exec'd.

This takes up file descriptor real estate and goes against the ulimit, but also could be problematic for those pipes due to keeping them open beyond when might be desirable.

Looks like the /dev/zero ones might be coming from:
https://github.com/dotnet/coreclr/blob/master/src/pal/src/map/map.cpp#L513
and the anonymous pipes may be coming from one of a few different pipe calls in the pal.  We should open that /dev/zero descriptor with O_CLOEXEC.  For the pipes, assuming they don't need to be inherited, on Linux we should use pipe2 with O_CLOEXEC, and if pipe2 isn't available, use fcntl to set O_CLOEXEC after creating the pipes.

**Comment by ellismg** [comment]
Was this resolved with #11988 and #12032, Steve?

**Comment by danmosemsft** [comment]
@stephentoub is there any more work here for 2.0 Steve? Can you close or move to Future as appropriate?
