### ISSUE TITLE
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processenvironment-l1-1-0.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by obadz** [dotnet/coreclr#1198]
I've built coreclr (git rev 8c70800b5e8dc5535c379dec4a6fb32f7ab5e878) and downloaded the mscorlib from build # 643 as well as the nuget packages as instructed in the readme.

I've also built the HelloWorld example using Mono's mcs and when trying to run it, I get the following error:

```
$ corerun HelloWorld.exe                                                                                                                                                    

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processenvironment-l1-1-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetStdHandle(Int32 nStdHandle)
   at System.Console.<>c__DisplayClass0.<get_Out>b__3()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.WriteLine(String value)
   at Program.DrawWindows()
   at Program.Main(String[] args)
```

I'm running on Linux (NixOS) and the whole reproducible build process is encoded here:
https://github.com/obadz/nixpkgs/blob/29919da68fddb0b1542197740453509352cf32a9/pkgs/development/compilers/coreclr/default.nix

**Comment by stephentoub** [comment]
The NuGet packages for the corefx assemblies currently only include Windows binaries; your script is pulling them down, and as a result you're running with the Windows version of System.Console.dll, which is attempting to make P/Invokes to Win32 functions, resulting in this error.  You need the Linux version of System.Console.dll See the Linux instructions at https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md, specifically the section about Build the Framework.

**Comment by obadz** [comment]
@stephentoub,

Thanks, unfortunately, I don't have the ability to run the build on Windows.  Would it be possible to add System.Console.dll and Sytem.Diagnostics.Debug.dll to the build artifacts along with mscorlib.dll in here: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_windows_debug/ ?

Also, is the idea in Core that apps should ship with all dependencies including System.* (except for the two mentioned above) ?

Thanks

**Comment by stephentoub** [comment]
> Would it be possible to add System.Console.dll and Sytem.Diagnostics.Debug.dll to the build artifacts

It's a bit confusing because we've split coreclr and corefx across two different repos / CI environments, but the artifacts are actually available.  You can download the assemblies you need from:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug/lastSuccessfulBuild/Azure/

> is the idea in Core that apps should ship with all dependencies including System.* 

The system supports app-local deployments if that's what you want; that means the application can run out of a directory that has all of its dependencies (including whatever System.* assemblies you use) there with it.  We also plan to support a machine-wide model.

**Comment by obadz** [comment]
Great, thank you for pointing me to the corefx artifacts.

From a packaging standpoint, is the expectation that all the corefx DLLs should be available in the clr-path, or just mscorlib, or some subset (System.Console & System.Debug.Diagnostics) ?

**Comment by ellismg** [comment]
The long term goal is that the CoreFX packages (e.g. System.Console, System.Debug.Diagnostics) will contain all the different versions of the assembly, if they are platform specific.  As much as possible, we are working to remove implementations from mscorlib and move them into the CoreFX packages.  However, in the limit, we'll continue to have a mscorlib.dll and some of the CoreFX packages will be "facades" which just type forward to mscorlib.  For example, I expect that System.Runtime.dll will always just be a facade over mscorlib.

mscorlib itself will be provided by the nuget package that also holds coreclr.

**Comment by obadz** [comment]
@ellismg,

Thank you. So if I'm understanding this right,

Long term: all of corefx & mscorlib will be in Nuget (and therefore will ship with applications?). Therefore coreclr as it stands now (a handful of native executables and native shared libraries) will be sufficient to run dotnet applications.

For short and medium term, is there some expectation that mscorlib & the corefx stuff be packaged with the coreclr runtime?

I would like to package coreclr for NixOS and need to understand which DLLs I should include.

**Comment by shahid-pk** [comment]
@obadz  it is simple. coreclr along with its mscorlib for each platform will have a nuget package check ? ok
all other corefx libs will also have nuget packages each containing dlls for every platform check (for platforms that have different implementation otherwise a single dll for most of libraries) ? ok
Now your question what libs or dlls will you need is totally dependent on you . but yes coreclr+mscorlib is the run time so you definitely need that. Others are tottally dependent on your app's requirements.

**Comment by tzwlai** [comment]
Closing this issue since it looks like the problem has been resolved and there's not been any activity in a while. Please feel free to reopen if anyone feels differently.
