### ISSUE TITLE
[Question] Who uses libSystem.Globalization.Native.a?

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#11997]
CLR build produces both ``System.Globalization.Native.so`` and ``libSystem.Globalization.Native.a``, but it seems that ``libSystem.Globalization.Native.a`` is unnecessary. 

Is it necessary? I find that dotnet shared framework ubuntu package also includes this file.

**Comment by janvorli** [comment]
The CoreRT project uses it.

**Comment by tarekgh** [comment]
https://github.com/dotnet/corert/blob/e4db93bb495383782b4e1e6c5181356b72cbff88/src/BuildIntegration/Microsoft.NETCore.Native.Unix.props#L45

https://github.com/dotnet/corert/blob/cb947515370bdc09f99abd9fcc176c8cca8d2960/buildscripts/build-managed.sh#L99

https://github.com/dotnet/corert/blob/fd9268c6727ad30f1e8573c52ead16a77bdc713f/src/packaging/packages.targets#L188

@parjong I am closing the issue as the question answered by @janvorli but feel free to reply back with more questions if you have any.
