### ISSUE TITLE
OS X clang unused argument warning

### ISSUE THREAD

**Issue by wjk** [dotnet/coreclr#120]
When I build CoreCLR on OS X 10.10 following the merge of #117, I get the following warning for every code file compiled:

    clang: warning: argument unused during compilation: '-nostdinc++'

Any chance this could be removed? (It would probably be a good idea to only do this on OS X, as this flag probably has meaning to Linux compilers.)

**Comment by kangaroo** [comment]
I'll fix this shortly, just running a palsuite for another issue currently.

**Comment by kangaroo** [comment]
Can you try https://github.com/kangaroo/coreclr/tree/issue-120

It fixes it for me.

**Comment by cnblogs-dudu** [comment]
@kangaroo 
It fixes it for me too.

**Comment by jkotas** [comment]
Fixed by #125
