### ISSUE TITLE
corefx jobs failing with "System.Runtime.Serialization.SerializationException : Type 'System.Lazy`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable."

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#12008]
e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/192/

Looks like this came in with #11910. These failures are also present in the latest "update CoreCLR" PR in CoreFX: https://github.com/dotnet/corefx/pull/20499

cc @ViktorHofer

**Comment by ViktorHofer** [comment]
thanks, on it!

**Comment by danmosemsft** [comment]
Should be fixed by #20501

**Comment by pgavlin** [comment]
That PR does not seem to exist...?

**Comment by pgavlin** [comment]
Never mind, now it's accessible. Thanks!
