### ISSUE TITLE
No line numbers from Exception.ToString() on Linux

### ISSUE THREAD

**Issue by eroller** [dotnet/coreclr#12009]
I am using the /embed option to the roslyn compiler via SourceLink nuget package:

`<PackageReference Include="SourceLink.Embed.AllSourceFiles" Version="2.1.2" PrivateAssets="all" />`

Running under dotnet for windows I get line numbers in my stack trace, but not on Linux.

I am using Centos 7.1 with dotnet 1.1.2

**Comment by danmosemsft** [comment]
@noahfalk

**Comment by noahfalk** [comment]
@mikem8361

**Comment by lt72** [comment]
@mikem8361: PTAL

**Comment by lt72** [comment]
Re-assignig to Chris for investigation

**Comment by lt72** [comment]
This should be working now, please let us know if you find that is not the case. I will close the issue in a few days if I do not hear from you. Please re-open the issue if you need to.
