### ISSUE TITLE
Pal_InitializeCoreCLR return ERROR_INVALID_PARAMETER when linking against release build 

### ISSUE THREAD

**Issue by mholo65** [dotnet/coreclr#1201]
I'm currently playing around with CoreCLR in Linux and linking my executable against libcoreclr. I've done this by creating some custom headers that declares functions **Pal_InitializeCoreCLR** and **GetCLRRuntimeHost** plus related structs, defines, etc..

My application is working fine when linking against the debug build of licoreclr. But when linking against the release build, then **Pal_InitializeCoreCLR** returns ERROR_INVALID_PARAMETER. Since I'm linking against the release build, I'm unable to debug and see what goes wrong inside libcoreclr.

My application is built in debug and I have debugger attached when executing.

Thankful for any help!

**Comment by mikem8361** [comment]
We want to move away from the PAL_InitializeCoreCLR/GetCLRRuntimeHost APIs on coreclr (both *Unix and Windows) and use the following new non-COM based ones.  If they don't meet your needs or have the same problem could you let me know.
//
// Initialize the CoreCLR. Creates and starts CoreCLR host and creates an app domain
//
// Parameters:
//  exePath                 - Absolute path of the executable that invoked the ExecuteAssembly
//  appDomainFriendlyName   - Friendly name of the app domain that will be created to execute the assembly
//  propertyCount           - Number of properties (elements of the following two arguments)
//  propertyKeys            - Keys of properties of the app domain
//  propertyValues          - Values of properties of the app domain
//  hostHandle              - Output parameter, handle of the created host
//  domainId                - Output parameter, id of the created app domain 
//
// Returns:
//  HRESULT indicating status of the operation. S_OK if the assembly was successfully executed
//
extern "C"
int coreclr_initialize(
            const char* exePath,
            const char* appDomainFriendlyName,
            int propertyCount,
            const char** propertyKeys,
            const char** propertyValues,
            void** hostHandle,
            unsigned int* domainId)

//
// Shutdown CoreCLR. It unloads the app domain and stops the CoreCLR host.
//
// Parameters:
//  hostHandle              - Handle of the host
//  domainId                - Id of the domain 
//
// Returns:
//  HRESULT indicating status of the operation. S_OK if the assembly was successfully executed
//
extern "C"
int coreclr_shutdown(
            void* hostHandle,
            unsigned int domainId)
//
// Create a native callable delegate for a managed method.
//
// Parameters:
//  hostHandle              - Handle of the host
//  domainId                - Id of the domain 
//  entryPointAssemblyName  - Name of the assembly which holds the custom entry point
//  entryPointTypeName      - Name of the type which holds the custom entry point
//  entryPointMethodName    - Name of the method which is the custom entry point
//  delegate                - Output parameter, the function stores a pointer to the delegate at the specified address
//
// Returns:
//  HRESULT indicating status of the operation. S_OK if the assembly was successfully executed
//
extern "C"
int coreclr_create_delegate(
            void* hostHandle,
            unsigned int domainId,
            const char* entryPointAssemblyName,
            const char* entryPointTypeName,
            const char* entryPointMethodName,
            void** delegate)

//
// Create a native callable delegate for a managed method.
//
// Parameters:
//  hostHandle              - Handle of the host
//  domainId                - Id of the domain 
//  entryPointAssemblyName  - Name of the assembly which holds the custom entry point
//  entryPointTypeName      - Name of the type which holds the custom entry point
//  entryPointMethodName    - Name of the method which is the custom entry point
//  delegate                - Output parameter, the function stores a pointer to the delegate at the specified address
//
// Returns:
//  HRESULT indicating status of the operation. S_OK if the assembly was successfully executed
//
extern "C"
int coreclr_create_delegate(
            void* hostHandle,
            unsigned int domainId,
            const char* entryPointAssemblyName,
            const char* entryPointTypeName,
            const char* entryPointMethodName,
            void** delegate)

**Comment by mholo65** [comment]
Thanks, I've noticed the new API, but haven't had a chance to test it. I will try to make time for this in a near future.

Original problem was that I was unable to Initialize CoreCLR if I had debugger attached (in my case GDB) when running my executable, if my executable was linked against a CoreCLR built in release mode. Could it be anything in the Initialization phase that checks if a debugger is attached?

**Comment by mikem8361** [comment]
There shouldn’t be any difference.  We debug coreclr with lldb (and gdb) all the time under “corerun” which uses the new apis, but the new apis call PAL_InitializeCoreCLR so it should be the same.

mikem

**Comment by mholo65** [comment]
So the only difference between my executable and corerun is that my executable links to libcoreclr.so on compile-time (Static loading, dynamic linking), while corerun uses dlopen (Dynamic loading, dynamic linking) to open libcoreclr.so.

**Comment by janvorli** [comment]
I wonder - have you used release build of mscorlib.dll when trying to use the release version of the libcoreclr.so? These two must match.

**Comment by mholo65** [comment]
I used the DNX nupkg (beta6-something), so it should have contained correct mscorlib.dll. This was however a time ago, I will try to find time to verify this in a near future.

**Comment by mholo65** [comment]
Can't seem to reproduce anymore. Not with new API atleast.

However, before closing this issue, I'm curious on how is ```coreclr_create_delegate``` supposed to be used? Can't find any examples in code.

This however is not working fore me, initialization works (I think :smile_cat: )
```c++
    void* host;
    unsigned int id;
    void* delegate;
    int status = coreclr_initialize(
        "/home/martin/src/foobar/Hello.dll",
        "Hello.World",
        0,
        0,
        0,
        (void**)&host,
        &id);

    status = coreclr_create_delegate(
        host,
        id,
        "Hello",
        "Hello",
        "HelloWorld",
        (void**)&delegate);
```

```coreclr_create_delegate``` returns ```-2147024894```

The sources for Hello.dll is the following:
```CSharp
using System;

public class Hello {
  public static void HelloWorld() {
    Console.WriteLine("Hello World!");
  }
}
```

**Comment by davidfowl** [comment]
You need to initialize the TPA list with the appropriate dependencies.

**Comment by mikem8361** [comment]
@mholo65 did this fix your problem?  I would like to close this issue.

**Comment by mholo65** [comment]
Yes original issue is fixed, or at least unable to reproduce with new API. You may close this issue. Thanks for your help!
