### ISSUE TITLE
UnmanagedType.CustomMarshaler not working for struct fields in 2.0.0-preview1-002111-00

### ISSUE THREAD

**Issue by dlech** [dotnet/coreclr#12029]
I'm trying to marshal a struct using a custom marshaller for one of the fields, but it is failing with an "unknown error".

Sample Code:

```
using System;
using System.Runtime.InteropServices;

namespace CustomMarshalTest
{
    
    struct TestStruct
    {
        [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(Custom))]
        public string Value;
    }

    class Custom : ICustomMarshaler
    {
        static Custom instance = new Custom();

        public static ICustomMarshaler GetInstance(string cookie) => instance;

        public void CleanUpManagedData(object ManagedObj)
        {
        }

        public void CleanUpNativeData(IntPtr pNativeData)
        {
            if (pNativeData != IntPtr.Zero) {
                Marshal.FreeCoTaskMem(pNativeData);
            }
        }

        public int GetNativeDataSize()
        {
            return IntPtr.Size;
        }

        public IntPtr MarshalManagedToNative(object ManagedObj)
        {
            var str = ManagedObj as string;
            if (str == null) {
                return IntPtr.Zero;
            }
            return Marshal.StringToCoTaskMemUni(str);
        }

        public object MarshalNativeToManaged(IntPtr pNativeData)
        {
            if (pNativeData == IntPtr.Zero) {
                return null;
            }
            return Marshal.PtrToStringUni(pNativeData);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            try {
                Console.WriteLine("Hello World!");
                var s = new TestStruct { Value = "mfg" };
                var ptr = Marshal.AllocCoTaskMem(IntPtr.Size);
                Marshal.StructureToPtr<TestStruct>(s, ptr, false);
                var x = Marshal.PtrToStructure<TestStruct>(ptr);
                Marshal.FreeCoTaskMem(ptr);
            } catch (Exception ex) {
                Console.WriteLine(ex);
            }
        }
    }
}
```

Steps to repeat:

```
dotnet new console
# paste code into Program.cs
dotnet restore
dotnet run
```

Result:

```
Hello World!
System.TypeLoadException: Cannot marshal field 'Value' of type 'CustomMarshalTest.TestStruct': Unknown error.
   at System.Runtime.InteropServices.Marshal.StructureToPtr(Object structure, IntPtr ptr, Boolean fDeleteOld)
   at System.Runtime.InteropServices.Marshal.StructureToPtr[T](T structure, IntPtr ptr, Boolean fDeleteOld)
   at CustomMarshalTest.Program.Main(String[] args) in /home/david/work/junk/marshal-test/Program.cs:line 61
```

Am I doing something wrong here? According to the debugger `GetInstance` is never called.

More info:

```
$ dotnet --info
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by dlech** [comment]
FYI, the custom marshaller seems to work when applied directly to a pinvoke parameter, but not on struct fields.

**Comment by jkotas** [comment]
@yizhang82 Is this supposed to work?

**Comment by yizhang82** [comment]
This scenario is not currently supported in .NET. This is the error message I got on desktop CLR and .NET Core on Windows:

```
Hello World!
System.TypeLoadException: Cannot marshal field 'Value' of type 'CustomMarshalTest.TestStruct': Custom marshalers cannot be used on fields of structures.
   at System.Runtime.InteropServices.Marshal.StructureToPtr(Object structure, IntPtr ptr, Boolean fDeleteOld)
   at System.Runtime.InteropServices.Marshal.StructureToPtr[T](T structure, IntPtr ptr, Boolean fDeleteOld)
   at CustomMarshalTest.Program.Main(String[] args) in c:\users\yzha\documents\visual studio 2017\Projects\ConsoleApp13\ConsoleApp13\Program.cs:line 65
```

But on linux, I'm getting "Unknown error" just like @dlech is seeing. Looking at 
https://github.com/dotnet/coreclr/blob/master/src/vm/fieldmarshaler.cpp#L4255-L4256, we start with "Unknown error" but replaced it with the real one afterwards. It looks like SString::LoadResource is #ifdefed out to a no-op probably due to missing dependency.

**Comment by yizhang82** [comment]
After reading the code a bit more, it looks more likely a bug when we not propagating ERROR_INSUFFICIENT_BUFFER properly. Need to actually debug this later today.

**Comment by dlech** [comment]
Thanks for looking into this. I sent a PR to update the documentation as well.

**Comment by yizhang82** [comment]
With https://github.com/dotnet/coreclr/issues/12051, we now properly show the error message in non-windows:
System.TypeLoadException: Cannot marshal field 'Value' of type 'CustomMarshalTest.TestStruct': Custom marshalers cannot be used on fields of structures.

**Comment by dlech** [comment]
It looks like no further action is required here, so closing.

**Comment by yezilife** [comment]
Hi, Any plan to support customized Marshal for fields of a structure?

**Comment by jkotas** [comment]
We have no plans to do this.

If you need to do a custom struct marshaling, our recommendation is to write direct code that does the marshaling. It is both easier to understand, and typically much faster than depending on runtime to marshal the fields via internal reflection.

**Comment by yezilife** [comment]
Hi Jan,
Thank you for the quick response! Do you have any pointer/reference how to write the direct code that does the Marshaling? Or use Marshal.PtrToStructure as a reference?

The problem I am facing is I am using .NET Core with Native code interop in both Windows and Linux. Our native lib is using wchar_t which is 4 bytes in Linux. .NET Core built-in Marshal only support 2 bytes (UTF16) string Marshal. So I need to write custom Marshal for c# string and Native wchar_t (4 bytes) for Linux. Custom Marshal works for function parameters. But it doesn't work for struct fields.

-Dong
________________________________

**Comment by jkotas** [comment]
Could you please share an example of method and struct that takes the `wchar_t` string you are trying to call?
