### ISSUE TITLE
build.sh describes an unavailable sequential flag 

### ISSUE THREAD

**Issue by omajid** [dotnet/coreclr#12035]
`build.sh` includes `sequential` as a supported flag

    echo "-sequential: force a non-parallel build ^(default is to build in parallel"  
    echo "   using all processors^)." 

But the rest of build.sh completely ignores it.

We should fix it, or remove it completely.

**Comment by omajid** [comment]
Anyone have any thoughts?

**Comment by janvorli** [comment]
@Priya91 I can see you have added this option in the past. Could you please answer the question?

**Comment by janvorli** [comment]
@Priya91 ping :-)

**Comment by Priya91** [comment]
@janvorli I don't own this anymore, but sequential is not supposed to pass /m option. If that doesn't happen then it's a bug. cc @maririos

**Comment by omajid** [comment]
The thing that bothers me is that `sequential` doesnt do *anything*. It would be simplest to remove it.
