### ISSUE TITLE
[Local GC] Combine related threading GCToEEInterface callbacks

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#12043]
See https://github.com/dotnet/coreclr/pull/12036#issuecomment-305612816 for details. The fact that `IsPreemptiveGCDisabled`, `Enable/DisablePreemptiveGC`, `GetAllocContext`, and `CatchAtSafePoint` each take a Thread parameter instead of operating on the current thread ensures that callers will incur the cost of at least two indirections: once to call `GetThread` and once again to call the function unsing the thread.

If each one of the above functions operates on the current thread, it can avoid an indirection in the GC by directly calling GetThread.

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/16765
