### ISSUE TITLE
Add a string.Split(string) method to the BCL

### ISSUE THREAD

**Issue by James-Ko** [dotnet/coreclr#1206]
Hello. I'm not sure if there are any practical reasons why this couldn't be done, but I think it's pretty verbose that every time I want to split a CSV-style list like this:

    Mary, John, Jane, Doe

That I have to write up this:

    string[] names = string.Split(new[] { ", " }, StringSplitOptions.None);

Is it possible that we could add two more `Split(params string[])` and `Split(string[], int)` overloads to the class?

**Comment by ryanlin1986** [comment]
That's right, every time I used string.Split() method I felt it's really really weird to use a string array to do this.

**Comment by StanRoze** [comment]
i agree, this API has always been a little bit strange.

**Comment by benpye** [comment]
Maybe I'm missing something, what do you propose the `Split(string[], int)` overload would do?

**Comment by masonwheeler** [comment]
Agreeing too.  How often do you ever pass more than one string as an argument anyway?  Heck, most of the time when I use this, I'm splitting on a single char, and the rest of the time it's a single string consisting of two chars.  Does anyone here have different use patterns?

**Comment by StanRoze** [comment]
btw, im pretty sure this should be in https://github.com/dotnet/corefx

**Comment by masonwheeler** [comment]
I don't think so; System.String is implemented in mscorlib.

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs

**Comment by shahid-pk** [comment]
i also doubt its use case, it should be minimal.

**Comment by James-Ko** [comment]
@benpye The same as it does for [char](https://msdn.microsoft.com/en-us/library/c1bs0eda%28v=vs.110%29.aspx): limit the number of substrings returned. There's a `Split(string[], int, StringSplitOptions)` overload for this, but I don't see why we have to specify `StringSplitOptions` when the same does not apply to char.

**Comment by OtherCrashOverride** [comment]
I just encountered this issue today while coding so I thought I would include this extension method code to see if we are all on the same page:

For the original example given, instead of writing this:
```
string[] names = string.Split(new[] { ", " }, StringSplitOptions.None);
```
You can write this:
```
string[] names = string.Split(", ");
```

Sample implementation:
```
    public static class StringExtensions
    {
        public static string[] Split(this string value, string separator)
        {
            string[] separators = new string[] { separator };
            return value.Split(separators, StringSplitOptions.None);
        }
        public static string[] Split(this string value, char separator)
        {
            char[] separators = new char[] { separator };
            return value.Split(separators, StringSplitOptions.None);
        }


        public static string[] Split(this string value, string separator, StringSplitOptions options)
        {
            string[] separators = new string[] { separator };
            return value.Split(separators, options);
        }
        public static string[] Split(this string value, char separator, StringSplitOptions options)
        {
            char[] separators = new char[] { separator };
            return value.Split(separators, options);
        }


        public static string[] Split(this string value, string separator, int count)
        {
            string[] separators = new string[] { separator };
            return value.Split(separators, count, StringSplitOptions.None);
        }
        public static string[] Split(this string value, char separator, int count)
        {
            char[] separators = new char[] { separator };
            return value.Split(separators, count);
        }


        public static string[] Split(this string value, string separator, int count, StringSplitOptions options)
        {
            string[] separators = new string[] { separator };
            return value.Split(separators, count, options);
        }
        public static string[] Split(this string value, char separator, int count, StringSplitOptions options)
        {
            char[] separators = new char[] { separator };
            return value.Split(separators, count, options);
        }
    }
```

**Comment by mburbea** [comment]
There already is a PR for this #895, I'd want this as it's a potentially memory allocation hit.
I usually cache my usual arrays that I want to use and it just ends up looking silly.

`someInput.Split(SingleComma, StringSplitOptions.None)`

**Comment by James-Ko** [comment]
@masonwheeler @OtherCrashOverride Err... We don't really need to make extension methods when it comes to a single `char`, since there already [is one](https://msdn.microsoft.com/en-us/library/b873y76a%28v=vs.110%29.aspx). `params` lets you do `words.Split(' ')` without explicitly creating an array.

**Comment by OtherCrashOverride** [comment]
I actually noticed that after pasting the code.  Its good that you pointed it out though.  Now we can also consider the performance difference with an explicit signature verses a variadic one.

**Comment by weshaggard** [comment]
This is included as part of https://github.com/dotnet/corefx/issues/1513, so I'm closing this. Also for the future as @StanRoze stated these type of APIs requests should be opened in the corefx repo even if the implementation lives in the coreclr repo, as we try to keep the API discussions happening in corefx.
