### ISSUE TITLE
Able to change readonly fields with a lambda

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/coreclr#1208]
(Yes, this does involve Reflection.  No, I don't think this should work anyways).
Minimal example:
```
using System;
using System.Collections.Generic;
using System.Reflection;
using Xunit;

namespace Tests
{
    public class ModifyReadonlyTests
    {
        //Verify SetValue method does not set value for RO Field
        [Fact]
        public void SetReadonlyField()
        {
            Somehow instance = new Somehow();

            Type t = typeof(Somehow);
            FieldInfo info = t.GetTypeInfo().GetDeclaredField("intField");

            Assert.NotNull(info);
            Assert.True(info.Name.Equals("intField"));
            object originalValue = info.GetValue(instance);

            // Assert.Throws<FieldAccessException>(() => info.SetValue(instance, int.MaxValue));
            Action n = () => info.SetValue(instance, int.MaxValue);
            n.Invoke();
            Assert.Equal(originalValue, info.GetValue(instance));
        }
    }

    public class Somehow
    {
        public readonly int intField = 1;
    }
}
```
The critical thing seems to be including the call to `SetValue` in a lambda or action; if you call it outside of that (say, in a regular `try catch` block....), it throws the expected `FieldAccessException`.  I noticed this while doing minor cleanup maintenance on [FieldInfo_ConstantTests](https://github.com/dotnet/corefx/blob/master/src/System.Reflection/tests/FieldInfo/FieldInfo_ConstantTests.cs#L75).  Otherwise, it happily changes the value (both tests fail).

Doesn't throw the exception against 4.5 either.

**Comment by leppie** [comment]
It has always been like this. You can use reflection anywhere to change a `readonly` field. This is only enforced by the C# compiler at compile time.

**Comment by Clockwork-Muse** [comment]
@leppie - if the call to `SetValue` is _not_ in a lambda, it throws an exception.  If it is, no exception, and it changes the value.

**Comment by leppie** [comment]
This works without any exceptions. Perhaps the issue is related to the PCL reflection classes you are using.

    public class ModifyReadonlyTests
    {
        public static void Main()
        {
            Somehow instance = new Somehow();
            Type t = typeof(Somehow);
            FieldInfo info = t.GetField("intField");

            var originalValue = instance.intField;
            info.SetValue(instance, int.MaxValue);
            Console.WriteLine(instance.intField);
        }
    }

    public class Somehow
    {
        public readonly int intField = 1;
    }

**Comment by Clockwork-Muse** [comment]
Argh, I can't read.  I went back and looked at the original test again; it was swallowing the exception from **not throwing the exception**.("failing" the test).  H'okay, I'm an idiot.

Closing due to it working correctly, the test was just written wrong.  Now to correct the test....
