### ISSUE TITLE
AppContext.TargetFrameworkName always returns null - bug or by design?

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/coreclr#12086]
```
using System.Runtime.Versioning;

[assembly:TargetFrameworkAttribute("Hello")]

class n
{
    static void Main()
    {
        Console.WriteLine(AppContext.TargetFrameworkName);
    }
}
```

returns null rather than "Hello".

The implementation on CoreCLR goes through the motions of looking up the data from the current (and only) appdomain:

```
        public static string TargetFrameworkName
        {
            get
            {
                // Forward the value that is set on the current domain.
                return AppDomain.CurrentDomain.SetupInformation.TargetFrameworkName;
            }
        }

```

but the code to initialize TargetFrameName was ripped out.

I don't have a strong opinion either way - I just need to know what the intent is so I can implement the CoreRT version correctly.

**Comment by RussKeldorph** [comment]
Related?
 - dotnet/corefx#23063
 - dotnet/corefx#23197
 - dotnet/corefx#17452

I assume this isn't blocking 2.1, though it would be nice to answer the question so we can close the issue or triage any necessary work.

@dotnet/coreclr-contrib

**Comment by jkotas** [comment]
We should return the TargetFrameworkName here, I think. It is one line change - copy the implementation from CoreRT:

```
        public static string TargetFrameworkName => Assembly.GetEntryAssembly()?.GetCustomAttribute<TargetFrameworkAttribute>()?.FrameworkName;
```

**Comment by jkotas** [comment]
https://github.com/dotnet/corefx/issues/23063 is duplicate. CoreFX repo is more appropriate place to track this.
