### ISSUE TITLE
System.Numerics Matrix4x4  Right-Handed Coordinates Systems?

### ISSUE THREAD

**Issue by rochar** [dotnet/coreclr#12081]
Hi,

It's supposed to use Matrix4x4 only in Left-Handed Coordinates systems?

Thanks
Ricardo

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #20765](https://github.com/dotnet/corefx/issues/20765) via [**ZenHub**](https://www.zenhub.com/)
