### ISSUE TITLE
Remove AppDomainLeaks configuration option

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#12094]
CoreCLR has a configuration option, `AppDomainLeaks`, which enables some additional assertions throughout the codebase about app domains. These checks tend to be expensive and have not added much value over the years - they have been disabled in the full .NET Framework for over 10 years. It would be great if we could just remove it from the codebase altogether.

I think this could be a good community issue, if anyone's interested in getting their hands a little dirty throughout the VM. You can see the places that are using the `AppDomainLeaks` configuration check (https://github.com/dotnet/coreclr/blob/master/src/vm/eeconfig.h#L536) and start from there. Once all uses are removed, it should be possible to remove the `CHECK_APP_DOMAIN_LEAKS` feature define as well.

See also: https://github.com/dotnet/coreclr/issues/12075#issuecomment-306274175 https://github.com/dotnet/coreclr/pull/11379#issuecomment-299080463

**Comment by antofik** [comment]
Can I take this one? Looks pretty straight-forward to get acquainted with the code

**Comment by jkotas** [comment]
@antofik You are welcomed to take this one. 

I have sent you collaborator invite - that will allow us to assign this issue to you once you accept (GitHub limitation).

Pro-tip: GitHub will automatically subscribe you to all repo notifications (500+/day). We recommend people to switch to notifications where you're mentioned.

**Comment by antofik** [comment]
@jkotas Thanks, invitation accepted

**Comment by swgillespie** [comment]
@antofik thanks for taking care of this!
