### ISSUE TITLE
DBG_CheckStackAlignment not built

### ISSUE THREAD

**Issue by wjk** [dotnet/coreclr#121]
I ran into a build issue when compiling CoreCLR on OS X 10.10. Specifically, [`DBG_CheckStackAlignment`](https://github.com/dotnet/coreclr/blob/master/src/pal/src/arch/i386/context.S#L5) is not present in the emitted object file, thus causing linker errors. This can be corrected by removing the `#if`/`#endif` from the file. Thanks!

**Comment by cnblogs-dudu** [comment]
I build successfully in debug mode on OS X 10.10. Same issue when build in release mode.

**Comment by kangaroo** [comment]
Could you please do the following for the failing build

cd binaries/CMake
make VERBOSE=1

**Comment by wjk** [comment]
[Here’s the `make VERBOSE=1` output.](https://gist.github.com/wjk/a1f0e712e88c1ee81bab)

**Comment by kangaroo** [comment]
I don't see any linker errors?  Are you building a release build?

**Comment by wjk** [comment]
Sorry about that, kangaroo, I forgot that `tee` by default only captures standard output. The actual linker error is this:

```
Undefined symbols for architecture x86_64:
  "_DBG_CheckStackAlignment", referenced from:
      _DuplicateHandle in libCoreClrPal.a(handleapi.cpp.o)
      _CloseHandle in libCoreClrPal.a(handleapi.cpp.o)
      _CreateFileA in libCoreClrPal.a(file.cpp.o)
      _CreateFileW in libCoreClrPal.a(file.cpp.o)
      _CopyFileW in libCoreClrPal.a(file.cpp.o)
      _CopyFileA in libCoreClrPal.a(file.cpp.o)
      _DeleteFileA in libCoreClrPal.a(file.cpp.o)
      ...
ld: symbol(s) not found for architecture x86_64
```

Yes, I am doing a release build.

**Comment by cnblogs-dudu** [comment]
@wjk 
Remove `binaries` directory can fix it. see #123

**Comment by cnblogs-dudu** [comment]
Replacing `#if defined(_DEBUG)` with `#if defined(__APPLE__)` in src/pal/src/arch/i386/context.S can fix it.

**Comment by kangaroo** [comment]
Thats not the correct fix, I accidentally merged a debug config.h.osx.  I'll submit a PR shortly.

**Comment by kangaroo** [comment]
Fixed in https://github.com/dotnet/coreclr/pull/155

**Comment by kangaroo** [comment]
@sergiy-k Can you please close this out?
