### ISSUE TITLE
How can I debug Access Violation Exception on .net core 2 preview?

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/coreclr#12101]
Hi,

 I am receiving Access Violation Exception in my .net core 2 application, when this happens the debugger terminates and I have no way of knowing where the program was when this happened.

In full .net I could have set mixed mode debugging, however I cant see how to set this for .net core 2 projects.

Thanks in advance.

@mikem8361 I'm mentioning you since I think you work on the debugger and may know. :)

**Comment by mikem8361** [comment]
You could try windbg/cdb and SOS. 

On Windows .NET Core 2.0 does  support mixed mode debug but there seems to be problems with VS Launch (see #8603).

**Comment by danwalmsley** [comment]
@mikem8361 I used windbg for now thanks 👍
