### ISSUE TITLE
Vector4 constructor does not always evaluate argument list left to right

### ISSUE THREAD

**Issue by RossNordby** [dotnet/coreclr#1212]
Constructing a Vector4 with an evaluation order dependent argument list produces unexpected results.
As an example:
```
        struct TestVector4
        {
            public float X, Y, Z, W;
            public TestVector4(float x, float y, float z, float w)
            {
                X = x;
                Y = y;
                Z = z;
                W = w;
            }
        }
        static void Main()
        {

            var aRandom = new Random(5);
            var a = new TestVector4((float)aRandom.NextDouble(), (float)aRandom.NextDouble(), (float)aRandom.NextDouble(), (float)aRandom.NextDouble());

            var bRandom = new Random(5);
            var b1 = new Vector4((float)bRandom.NextDouble(), (float)bRandom.NextDouble(), (float)bRandom.NextDouble(), (float)bRandom.NextDouble());

            var bRandom2 = new Random(5);
            var bRandomX = (float)bRandom2.NextDouble();
            var bRandomY = (float)bRandom2.NextDouble();
            var bRandomZ = (float)bRandom2.NextDouble();
            var bRandomW = (float)bRandom2.NextDouble();
            var b2 = new Vector4(bRandomX, bRandomY, bRandomZ, bRandomW);
            
            Console.WriteLine($"A: ({a.X}, {a.Y}, {a.Z}, {a.W})");
            Console.WriteLine($"B1: ({b1.X}, {b1.Y}, {b1.Z}, {b1.W})");
            Console.WriteLine($"B2: ({b2.X}, {b2.Y}, {b2.Z}, {b2.W})");
        }
```
When executed with optimizations enabled, this outputs:
>A: (0.3383698, 0.2844184, 0.2629626, 0.6253759)
B1: (0.6253759, 0.2629626, 0.2844184, 0.3383698)
B2: (0.3383698, 0.2844184, 0.2629626, 0.6253759)

B1 has reversed order.

When executed with optimizations suppressed, it outputs the expected ordering:
>A: (0.3383698, 0.2844184, 0.2629626, 0.6253759)
B1: (0.3383698, 0.2844184, 0.2629626, 0.6253759)
B2: (0.3383698, 0.2844184, 0.2629626, 0.6253759)

The optimized result appears to violate the spec:
>7.5.1.2 Run-time evaluation of argument lists
During the run-time processing of a function member invocation (§7.5.4), the expressions or variable references of an argument list are evaluated in order, from left to right,

This behavior was also observed with Vector3. Tested using the default RyuJIT/numerics configuration that ships with VS2015 RC.

**Comment by mikedn** [comment]
This appears to be the unfortunate consequence of an optimization that evaluates the arguments in the opposite order to minimize register usage: [simd.cpp:1946](https://github.com/dotnet/coreclr/blob/master/src/jit/simd.cpp#L1946)

**Comment by mellinoe** [comment]
+ @CarolEidt

**Comment by CarolEidt** [comment]
I'll have a look - kind of an obvious "oops"; it's rather surprising nobody caught that before - thanks!
