### ISSUE TITLE
String.Format() fails with a specific format string

### ISSUE THREAD

**Issue by jakesays** [dotnet/coreclr#1214]
Given the line `String.Format("{0}{1:X2}}}", 2, 1)` I would expect the result to be `"201}"` however it returns "2X2}".

However `String.Format("{0}{1:X2} }}", 2, 1)` returns `"201 }"`.

Tried with mono and the expected behavior was returned.

**Comment by OtherCrashOverride** [comment]
https://msdn.microsoft.com/en-us/library/txafckwd%28v=vs.110%29.aspx

See "Escaping Braces"

On a related note, the issue that always gets me is:
```
String.Format("{0}{1:X2}", 2, (int)10)
"20A"

String.Format("{0}{1:X2}", 2, (IntPtr)10)
"210"
```

**Comment by jakesays** [comment]
Just read that link about brace escaping - wow what a mess. Someone was smoking something good when they came up with that parsing strategy. I still maintain this is a bug, and that mono behaves correctly.

**Comment by AdamSpeight2008** [comment]
@jakesays I'm started on a new version of [String Format Diagnostic](https://github.com/DotNetAnalyzers/StringFormatDiagnostic). That may help with this issue.

**Comment by jakesays** [comment]
@AdamSpeight2008 Not sure how that could possibly help this issue.

**Comment by AdamSpeight2008** [comment]
It can analyse the format part of the argument hole and see if it valid.
If the argument referred to is a type one from BCL it its capable of check it valid for that type.
It also has partial support for colouring the string, so you can see which are the opening and closing braces, and which are escaped..
![sfd_colors2](https://cloud.githubusercontent.com/assets/900107/8660483/1bf7867a-29a9-11e5-93d0-373c97be45fe.jpg)

**Comment by jakesays** [comment]
Again your diagnostic really has nothing to do with this issue.

**Comment by AdamSpeight2008** [comment]
@jakesays You proposal will change the runtime semantics of formart strings. Possibly changing a format string into on no does throw a format exception to one that doesnt or visa versa. 
I belive { } are allowed in custom \ user implement formatters. 

Also SFD makes some of the format exceptions **compile-time** errors and warnings.

**Comment by AdamSpeight2008** [comment]
@jakesays Mono use the exact same parsing method (afaict). So will produce the same output.

**Comment by jakesays** [comment]
@AdamSpeight2008 That is because mono recently switched to the .net BCL, so yes, new mono is just as broken.

Also I made no proposal. I opened a bug.

**Comment by jakesays** [comment]
Closing because this is by design.
