### ISSUE TITLE
[Linux] Low CPU utilization due to the return value of GetCurrentProcessCpuCount

### ISSUE THREAD

**Issue by helloguo** [dotnet/coreclr#12141]
When running TechEmpower Plaintext benchmark on a Linux machine with 88 logical cores, the low CPU utilization is observed.  The reason is that the GC thread number is limited to 64 because the return value of GetCurrentProcessCpuCount is cut to 64. 

In gc.cpp

```
    uint32_t nhp_from_process = CPUGroupInfo::CanEnableGCCPUGroups() ?
                                CPUGroupInfo::GetNumActiveProcessors():
                                GCToOSInterface::GetCurrentProcessCpuCount();
```

In util.cpp, https://github.com/dotnet/coreclr/blob/master/src/utilcode/util.cpp#L1290-L1291
```
int GetCurrentProcessCpuCount()
{
    ....
    if (count == 0 || count > 64)
        count = 64;
    ....
}
```

https://github.com/dotnet/coreclr/pull/12140 fixes this limitation.

**Comment by swgillespie** [comment]
cc @Maoni0

**Comment by Maoni0** [comment]
@helloguo thanks for doing this work. The comment for GetCurrentProcessCpuCount is certainly incorrect - GC can use > 64 The way GC uses > 64 heaps is via the CPU groups (BTW, the work to enable CPU groups in CLR was actually done by Intel folks) which is a thing on Windows but I suppose there's no such term on Linux. 

@janvorli could you please take a look at this and make sure that when we return > 64 here we are handling it correctly on Linux (eg, not using a data type that isn't big enough to accommodate 1024)? Would also be good to fix the incorrect comments in GetCurrentProcessCpuCount.
