### ISSUE TITLE
[Question] Will UWP6.0 Milestone Support Windows IoT

### ISSUE THREAD

**Issue by shaggygi** [dotnet/coreclr#12159]
Does anyone know if this [milestone](https://github.com/dotnet/coreclr/milestone/11) will support .NET Core for Windows IoT UWP apps that runs on RPi3 or is the focus more for desktop?

CC @karelz 

Thx

**Comment by karelz** [comment]
RPi3 is community support in 2.0: https://github.com/dotnet/core/blob/master/roadmap.md#net-core-20---supported-os-versions
Probably also in 2.1 - @Petermarcu will know for sure.

**Comment by shaggygi** [comment]
Thanks @karelz for reply.  @Petermarcu let me provide a little more insight to help with my question.

First, I mentioned .NET Core in original post, but I meant .NET Standard.  I have a .NET Standard 2.0 (Preview) API and would like to use in a Windows IoT UWP app on RPi3.  In addition, the app uses UWP specific Device APIs (Bluetooth, Serial, other I/O hardware, etc.).

I noticed there is an [example to run .NET Core on RPi3](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md), but in this case it needs to be UWP.  So my question is... will the UWP6.0 milestone bits include support to use .NET Standard 2.0 Class projects with Windows IoT UWP apps?

Also (and this might be worthy of a different issue), but since we will eventually be able to run .NET Core on RPi3... will we be able to reference the UWP Devices APIs or only in UWP apps?  If not, do you know of any plans/repos that offer .NET Core/Standard APIs to interact with RPi hardware (serial, I/O, I2C, etc.)?  This seems to be a better solution as they could hopefully be referenced in .NET Core apps for Windows and Linux running on RPi3.

Any help is appreciated.  Thanks again

**Comment by karelz** [comment]
UWP6.0 will enable .NET Standard 2.0 in UWP context. Windows IoT suports UWP, so it should naturally flow there (assuming you have the right OS version - Win10 Fall Creators Update, see [details](https://github.com/dotnet/core/blob/master/roadmap.md#ship-dates)).

.NET Core 2.0 on RPi3 should be able to use all APIs which are accessible outside of UWP context. Your question on availability of UWP Devices APIs outside of UWP context should be targeted at Windows team / authors of those UWP Devices APIs (@ptorr-msft may be able to help route your question).

**Comment by ptorr-msft** [comment]
Most of the non-UI WinRT APIs are available outside of UWP on Desktop, although some of them might require the Desktop Bridge if they rely on App identity etc. 

.NET Core doesn't support binding to WinRT APIs at the moment, so you can't call any of the WinRT APIs from a .NET Core app on IoT (or anywhere else) - you must use .NET Native (UWP).
