### ISSUE TITLE
init-tools doesn't show an actual error

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#12176]
If Set-ExecutionPolicy is set to restricted, that init-tools.log will have such message:

> C:\git\coreclr\packages\microsoft.dotnet.buildtools\2.0.0-prerelease-01702-02\lib\\init-tools.ps1 : File 
C:\git\coreclr\packages\microsoft.dotnet.buildtools\2.0.0-prerelease-01702-02\lib\init-tools.ps1 cannot be loaded 
because running scripts is disabled on this system. For more information, see about_Execution_Policies at 
http://go.microsoft.com/fwlink/?LinkID=135170.

However, build.cmd output will be clean before it will meet problems with nuget packages:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at Newtonsoft.Json.JsonConvert.DeserializeObject
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T]
   at Microsoft.DotNet.Execute.Executor.OpenFile()
   at Microsoft.DotNet.Execute.Executor.Main(String[] args)

And if you do "Set-ExecutionPolicy Unrestricted", init-tools will not run again before you do "git clean -qdfx".

**Comment by sandreenko** [comment]
@dotnet/jit-contrib could you please add necessary people here?

**Comment by JosephTremoulet** [comment]
Looks like the [line that invokes init-tools.ps1](https://github.com/dotnet/buildtools/blob/7973947fa359f99bd5e408955da8770274c469bc/src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.cmd#L122) that @mellinoe added in dotnet/buildtools#1422 doesn't pass `-ExecutionPolicy unrestricted` (or `-NoProfile`) to powershell like the [similar cmd -> powershell invocations](https://github.com/dotnet/coreclr/blob/699b25847ec14e47abc03cf7f3a1ffdb249d68b6/init-tools.cmd#L47) in coreclr/init-tools.cmd do.  Maybe it should?

**Comment by mellinoe** [comment]
Sounds reasonable to me. Could you file an issue over in https://github.com/dotnet/buildtools to track this?

**Comment by JosephTremoulet** [comment]
Filed dotnet/buildtools#1557, thanks

**Comment by yizhang82** [comment]
I'm seeing this too on a fresh box today and couldn't figure out why. Please fix this. Thanks!

**Comment by danmosemsft** [comment]
@mellinoe do we still need a build tools update to get your fix?

**Comment by RussKeldorph** [comment]
Fixed by dotnet/buildtools#1558 after we picked up the right buildtools version.
