### ISSUE TITLE
ResourceManager should restore logic for when to use satellite resource lookup under AppX

### ISSUE THREAD

**Issue by safern** [dotnet/coreclr#12178]
We should change ResourceManager.cs to do https://github.com/dotnet/coreclr/pull/12117/files#diff-eb71ec85c8bb94ecf707440b98c59716R894 once we fix our uap test runner to reprocess the test resources into PRI so that ResourceManager string loading works correctly inside APX.

cc: @jkotas

**Comment by gkhanna79** [comment]
Assigned to @tarekgh since he will be working on it.

CC @danmosemsft

**Comment by jkotas** [comment]
Note that this may also need to be updated to match the current CoreCLR packaging/build targets for UWP.

**Comment by safern** [comment]
This should be done after we update our test infrastructure to create a PRI file with all of our assemblies resources. We are targeting to do that once we have a green test run as we want to enable CI legs asap.

**Comment by tijoytom** [comment]
@safern @danmosemsft 

> This should be done after we update our test infrastructure to create a PRI file with all of our assemblies resources. We are targeting to do that once we have a green test run as we want to enable CI legs asap.
     What needs to happen now given the f5 is green in CI?

**Comment by safern** [comment]
https://github.com/dotnet/corefx/issues/21692

cc: @tarekgh who is working on this with me. We are now on hold waiting for a discussion on the design of the infrastructure side.

**Comment by tarekgh** [comment]
@tijoytom we already have a plan what exactly need to be done here. we are just waiting the final word from @morganbr if we continue or he want change the current design. I have handed the needed changes for PN side to @morganbr but if we change the design then we'll need to have a different plan. we should hear from @morganbr very soon about that.

**Comment by safern** [comment]
PR for infrastructure changes is in place: https://github.com/dotnet/buildtools/pull/1611
