### ISSUE TITLE
Build of tests doesn't work with VS2017

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#12190]
When building coreclr on Windows with VS2017 from VS2017 command prompt, the build of coreclr itself passes ok, but the build of tests that follows fails completely. The following error keeps getting repeated hunreds times:
    15>D:\git\coreclr\Tools\Microsoft.CSharp.Core.targets(106,11): error MSB4064: The "OverrideToolHost" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property. [D:\git\coreclr\tests\src\baseservices\compilerservices\RuntimeWrappedException\RuntimeWrappedException.csproj]
    15>D:\git\coreclr\Tools\Microsoft.CSharp.Core.targets(67,5): error MSB4063: The "Csc" task could not be initialized with its input parameters.  [D:\git\coreclr\tests\src\baseservices\compilerservices\RuntimeWrappedException\RuntimeWrappedException.csproj]

**Comment by janvorli** [comment]
CC: @wtgodbe, @weshaggard

**Comment by wtgodbe** [comment]
This is a dup of https://github.com/dotnet/coreclr/issues/11914 - I am looking into it. I put up https://github.com/dotnet/coreclr/pull/12175 to try to fix it, but looks like it caused/uncovered more errors down the line. I'm hoping Wes knows more about what's causing them

**Comment by weshaggard** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/12175
