### ISSUE TITLE
Make CoreCLR dependency on libnuma on Unix soft

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#12192]
Currently, when CoreCLR is built on a machine with libnuma dev package installed, it gets explicit dependency on libnuma. So it won't run on a Linux without this library installed. I would like to eliminate this hard dependency and make it soft by loading the libnuma via dlopen if it is present, but working fine without any numa support if the library is not installed.

**Comment by am11** [comment]
@janvorli, if this is up-for-grabs, I have a patch for it: https://github.com/am11/coreclr/commit/81cf8b5?w=1. Compiled it on CentOS 7 (without libinuma).

**Comment by janvorli** [comment]
@am11 thank you for creating the patch. My plan to make that change was slightly different though. We already do some shimming in icushim.cpp/h and also in opensslshim.cpp/h in corefx. I would like to implement it using the same technique to keep things consistent.

If you'd be willing to modify your change that way, I'd be more than happy to take that change. However, I am leaving for three weeks of vacation on Friday, so I'd be able to review the change either before or after I get back.

What I mean is to:
* still include the headers during the build - require the libnuma at the build machine
* keep the HAVE_NUMA_H
* after including the numa headers, define pointers for the functions we use using the decltype(functionname)* as the type, which means not having to specify their signatures by hand.
* after defining the pointers, use #define functionname functionname_ptr, which would result in the code calling the functions through the pointers implicitly
* finally, similar to what you did, load the library and use dladdr to get function pointer to each function
* overall it would use the same technique as the existing shim - single list of function names and its expansion into the pointer declaration and initialization.

So the list would look like
```C++
#define FOR_ALL_NUMA_FUNCTIONS \
    PER_FUNCTION_BLOCK(mbind) \
    PER_FUNCTION_BLOCK(numa_allocate_cpumask) \
    PER_FUNCTION_BLOCK(numa_available) \
    PER_FUNCTION_BLOCK(numa_bitmask_isbitset) \
    PER_FUNCTION_BLOCK(numa_bitmask_weight) \
    PER_FUNCTION_BLOCK(numa_free_cpumask) \
    PER_FUNCTION_BLOCK(numa_max_node) \
    PER_FUNCTION_BLOCK(numa_node_to_cpus) 
```
Then
```C++
// Declare pointers to all the used numa functions
#define PER_FUNCTION_BLOCK(fn) decltype(fn)* fn##_ptr;
FOR_ALL_NUMA_FUNCTIONS
#undef PER_FUNCTION_BLOCK
```
Then
```C++
#define mbind(...) mbind_ptr(__VA_ARGS)
#define numa_allocate_cpumask(...) numa_allocate_cpumask_ptr(__VA_ARGS)
etc...
```
And finally in the initialization function
```C++
#define PER_FUNCTION_BLOCK(fn) \
    fn##_ptr = (decltype(fn)*)dlsym(numaHandle, fn); \
    if (fn##_ptr == NULL) { fprintf(stderr, "Cannot get symbol " #fn " from " #lib "\n"); abort(); }

    FOR_ALL_NUMA_FUNCTIONS
#undef PER_FUNCTION_BLOCK
```

**Comment by am11** [comment]
Thanks for the detailed response @janvorli. I implemented it first with `typedef`, then changed it to type alias with `using`. One other pattern I found in CoreCLR is `decltype` and variadic templates.

I will try it with `decltype` and regular macro to form numashim, to keep it consistent with icushim. :)
