### ISSUE TITLE
Use Xunit wrappers to run tests on non-Windows

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#12202]

**Comment by sbomer** [comment]
Relevant work to build wrappers on unix: https://github.com/dotnet/coreclr/pull/18695. After this change, tests/runtest.py will run the wrappers on unix and windows, but runtest.sh will still traverse the filesystem and run .sh files.

**Comment by wtgodbe** [comment]
Looks like this is now resolved
