### ISSUE TITLE
[Question] How to detect .NET Core version at runtime

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/coreclr#12204]
I would like to get the .NET Core version at runtime. Is there a proper API?

The original problem:  https://github.com/dotnet/BenchmarkDotNet/issues/448

**Comment by am11** [comment]
Seems like dontet-cli also reflects over its executing assembly version to get the version: https://github.com/dotnet/cli/blob/cc80822c/src/Microsoft.DotNet.Cli.Utils/Product.cs. The CoreFX issue for the proposed API is apparently awaiting a compelling use-case: dotnet/corefx#17452. Perhaps, you can chime in with yours. :)

I tried using the suggested `AppContext.TargetFrameworkName` property in console app (with `<TargetFramework>netcoreapp1.1</TargetFramework>` in csproj), but it returns `null`:

```c#
static void Main(string[] args)
{
  Console.WriteLine(AppContext.TargetFrameworkName == null);
  // => True
}
```

**Comment by RussKeldorph** [comment]
I assume this is sufficiently tracked by dotnet/corefx#17452.  At any rate, API-related questions usually belong in dotnet/corefx.

Feel free to re-open if I misunderstood.
