### ISSUE TITLE
threading/SleepEx/test1/paltest_sleepex_test1 failing intermittently for freebsd

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#1221]
The freebsd sleep test is failing intermittently.  I think this probably just needs to have its tolerances loosened a bit.

Example:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_freebsd_release/172/console

**Comment by ghuntley** [comment]
See also https://github.com/dotnet/coreclr/issues/1010#issuecomment-104756763

**Comment by josteink** [comment]
I agree it sounds like that's the issue. It would be nice to have the test include expected timing vs actual timing so that we can assess what sort of increments are required though.

**Comment by danmosemsft** [comment]
@kouvel I'm going to close this as it's super old and not reported since 2015

**Comment by alexperovich** [comment]
Actually closing
