### ISSUE TITLE
Memory leaks on 1.0.4

### ISSUE THREAD

**Issue by alex-fomin** [dotnet/coreclr#12219]
I have detected the huge memory leaks in .net app running on Amazon Linux. 

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     amzn
 OS Version:  2017.03
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /opt/dotnet/sdk/1.0.4
```

The process info from `top`:
```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
13866 ec2-user  20   0 24.5g 4.1g  32m S  0.0 26.5  75:00.21 dotnet
```

lldb + libsosplugin shows very low memory consumed by GC:

```
(lldb) eeheap -gc
Number of GC Heaps: 4
------------------------------
Heap 0 (0000000001381EE0)
generation 0 starts at 0x00007F85AC1D54F8
generation 1 starts at 0x00007F85AC103CD0
generation 2 starts at 0x00007F85ABFFF000
ephemeral segment allocation context: none
         segment             begin         allocated              size
00007F85ABFFE000  00007F85ABFFF000  00007F85AC2C9510  0x2ca510(2925840)
Large object heap starts at 0x00007F89ABFFF000
         segment             begin         allocated              size
00007F89ABFFE000  00007F89ABFFF000  00007F89AC016D10  0x17d10(97552)
Heap Size:               Size: 0x2e2220 (lu) bytes.
------------------------------
Heap 1 (00000000013AB0E0)
generation 0 starts at 0x00007F86AC178F90
generation 1 starts at 0x00007F86AC0F71B0
generation 2 starts at 0x00007F86ABFFF000
ephemeral segment allocation context: none
         segment             begin         allocated              size
00007F86ABFFE000  00007F86ABFFF000  00007F86AC9AED78  0x9afd78(10157432)
Large object heap starts at 0x00007F89BBFFF000
         segment             begin         allocated              size
00007F89BBFFE000  00007F89BBFFF000  00007F89BBFFF018  0x18(24)
Heap Size:               Size: 0x9afd90 (lu) bytes.
------------------------------
Heap 2 (00000000013B02D0)
generation 0 starts at 0x00007F87AC094F80
generation 1 starts at 0x00007F87AC06B510
generation 2 starts at 0x00007F87ABFFF000
ephemeral segment allocation context: none
         segment             begin         allocated              size
00007F87ABFFE000  00007F87ABFFF000  00007F87AC16EF98  0x16ff98(1507224)
Large object heap starts at 0x00007F89CBFFF000
         segment             begin         allocated              size
00007F89CBFFE000  00007F89CBFFF000  00007F89CBFFF018  0x18(24)
Heap Size:               Size: 0x16ffb0 (lu) bytes.
------------------------------
Heap 3 (00000000013B54C0)
generation 0 starts at 0x00007F88AC155F68
generation 1 starts at 0x00007F88AC0E5F50
generation 2 starts at 0x00007F88ABFFF000
ephemeral segment allocation context: none
         segment             begin         allocated              size
00007F88ABFFE000  00007F88ABFFF000  00007F88AC211F80  0x212f80(2174848)
Large object heap starts at 0x00007F89DBFFF000
         segment             begin         allocated              size
00007F89DBFFE000  00007F89DBFFF000  00007F89DBFFF018  0x18(24)
Heap Size:               Size: 0x212f98 (lu) bytes.
------------------------------
GC Heap Size:            Size: 0x1014ef8 (lu) bytes.
```

`sos VerifyHeap` shows no errors.

The app perform huge amount of http requests via HttpClient and store results in MongoDB using latest MongoDB core driver.

The app targets `.netcoreapp1.1` and `centos-7.x64`.

I have no idea what can I do next to identify the memory leak source.

**Comment by janvorli** [comment]
@alex-fomin I assume that when you talk about the leak, you mean the "RES" column in the  "top" output. What is the memory consumption that you'd expect here? Is it possible that the Mongo DB consumes that much memory?

**Comment by alex-fomin** [comment]
@janvorli Yes, I mean "RES" column. We have a similar app - with intense MongoDB usage and some HttpClient calls - it takes about 500Mb in idle and ~800Mb-1Gb under load. The `top` and `lldb` info was taken when the app was in idle state - no massive http calls and no MongoDB usage.  I assume that MongoDB  (at least unamanaged memory) is not included in the running app - I can see various MongoDB objects in heap. I'll create a test app with MongoDB usage similar to leaked app and will return with results. Also, the same leak is for `netcoreapp1.0` as well. Also my colleague told me that he saw the same leak on Windows as well - I'll try to reproduce it under some memory profiler as well. Is there any technics I could use to improve info collection regrading the leak?

**Comment by janvorli** [comment]
@alex-fomin In the past, I was using the heaptrack tool described here for native memory leaks investigations: http://milianw.de/blog/heaptrack-a-heap-memory-profiler-for-linux. 
Memory leaks that would not be obviously visible in the sos reports could be caused by interop issues where the managed code keeps alive a memory structure allocated on the native side even when it is not needed anymore. If you know you have some kind of managed object that keeps alive some native memory, sos DumpHeap command might give you helpful information. For example, you might see that there is an excessive number of those managed objects.

**Comment by JustArchi** [comment]
This doesn't necessarily has to be memory leak, but runtime being lazy when it comes to giving memory back to OS.

> I have no idea what can I do next to identify the memory leak source.

If you want to confirm if my theory is right, you can add a very dirty timer in `Main()` function, like:

```
internal static class Program {
	private static Timer GarbageCollectionTimer;

	private static void Main() {
		GarbageCollectionTimer = new Timer(
			e => GC.Collect(),
			null,
			TimeSpan.FromSeconds(2), // Delay
			TimeSpan.FromSeconds(2) // Period
		);
	}
}
```

And observe if suddenly your app slowly gives memory back to OS, resulting in memory usage drop each 2 seconds. If yes, it's exactly the same issue. If it doesn't help, then very likely it's indeed a memory leak somewhere.
