### ISSUE TITLE
FEATURE_LEGACYSURFACE enabled for Windows mscorlib?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#1223]
Right now FEATURE_LEGACYSURFACE is enabled for the Windows build of mscorlib.  Does it need to be?  There are a bunch of types that are being made internal or tree shaken out on the Unix build but that are still being included for Windows, even though corefx has its own build of these types, e.g. all of System.IO.FileSystem.dll.

**Comment by danmosemsft** [comment]
Should be removed in https://github.com/dotnet/coreclr/issues/8857
