### ISSUE TITLE
StackOverflowException when stacking lambas without variable

### ISSUE THREAD

**Issue by adamfur** [dotnet/coreclr#12230]
// Fails
Func<bool> f = () => true;

f = () => true && f();
f();

// Works (using a temporary variable)
Func<bool> f = () => true;

var tmp = f;
f = () => true && tmp();
f();

# dotnet --version
2.0.0-preview1-005977

**Comment by janvorli** [comment]
@adamfur have you reproduced this on Windows, Unix or both?

**Comment by mikedn** [comment]
That's normal, you're capturing variable `f` so the second lambda calls itself. Keep in mind that in C# lambda expressions capture variables and not variable values.

**Comment by adamfur** [comment]
@janvorli Same across plattforms, tested on Linux and Windows.
@mikedn sane explanation, closing issue.
