### ISSUE TITLE
model.xml's FEATURE_LEGACYSURFACE usage has gotten stale

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#1224]
The model.xml file appears to use FEATURE_LEGACYSURFACE to annotate APIs that aren't type-forwarded from corefx, but with more and more implementations being moved to corefx, it appears to have gotten a bit stale over time.  For example, UnmanagedMemoryAccessor isn't marked as FEATURE_LEGACYSURFACE, even though corefx now has an implementation.  Same for SafeFileHandle, BitConverter, Path, and probably a variety of others.

**Comment by joshfree** [comment]
@AlexGhiondea PTAL

**Comment by am11** [comment]
It seems like this diff https://github.com/dotnet/coreclr/commit/ffc7372713170e09a9f80d4cd8d6bb238378a34b#diff-9f8fe187f0860c5a69db2d91a5edc001 cleaned up 70 out of 72 instances of `FEATURE_LEGACYSURFACE` in `model.xml`. The remaining two are: `System.IO.SearchOption` and `System.IO.SeekOrigin`.

**Comment by danmosemsft** [comment]
We will delete model.xml
https://github.com/dotnet/coreclr/issues/4651
