### ISSUE TITLE
[Arm64/Unix] FlushProcessWriteBuffers() ??

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#12246]
Looking at the implementation of `FlushProcessWriteBuffers()` it looks like it makes Intel/Amd specific assumptions about side effects of mprotect.

For Arm64:

The Atomic increment currently uses a Load Acquire Barrier and a Store Release Barrier.  This is functionally equivalent to a `dmb ish`.  It will probably switch to Compare and Swap with Acq/Rel when 8.1 atomics are present.  So the side effect will likely be the same.

The mprotect will execute a `dsb` to guarantee the pte update is visible to all MMU's before issuing a `TLBI*` instruction, the effects will be broadcast to all processors.  `TLBI*` will be typically observed by the other threads at their next context synchronization point (isb, exception).  

_The other threads' write buffers are unlikely to be flushed._

Is [Arm64/Unix] Functionally correct?  
+ It seems this code is functionally equivalent to a `dsb ishst`
+ I suspect it does not implement the contract correctly.
+ Is there a robust test to verify this is functioning correctly?

@janvorli

**Comment by sdmaclea** [comment]
cc @jkotas @dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
I guess this may be either 
+ `dsb ishst; tlbi *;`
+ `dsb ishst; tlbi *; dsb ishst`

In the latter case it would mean the TLBI was complete on all processors.  But it still does not guarantee the write buffers are flushed on other processors.

**Comment by jkotas** [comment]
Related to #1563.

What is the minimum Linux kernel version that ARM64 runs well on?

**Comment by janvorli** [comment]
@sdmaclea I don't think the assumptions the function makes are Intel specific. If one processor changes a protection of a page, TLBs on other processors, at least those that have that page in their TLB, need to be flushed to ensure that they don't contain stale mappings. The interlocked increment in the function just makes the page dirty to make sure the kernel cannot optimize out the TLB flush.
To make sure the TLBs on other processors are flushed, they need to be sent an IPI. And I believe the IPI ensures that the write buffers are flushed. Is this assumption wrong?

**Comment by sdmaclea** [comment]
> To make sure the TLBs on other processors are flushed, they need to be sent an IPI. And I believe the IPI ensures that the write buffers are flushed. Is this assumption wrong?

For arm64 the `tlbi` ops are weakly ordered and broadcast to other tlb's.  There is no hardware architectural need for an IPI.  

OS could do an IPI, for software architecture reasons.  I do not know if Linux kernel actually does an IPI for arm64 in this case.  POSIX standard does not appear to require it.

**Comment by janvorli** [comment]
@sdmaclea ah, from my past work on the Midori microkernel I only had low level experience with ARM32 and that one didn't have the TLBI and so IPI was necessary. 
But it looks like Linux kernel actually uses IPI to flush TLB on AARCH64 machines in SMP configuration.

**Comment by sdmaclea** [comment]
I drafted a sys_membarrier() implementation here  #12259.

**Comment by davidchisnall** [comment]
On FreeBSD, there is no IPI for page table updates on AArch64.  The architecture guarantees that these are visible to the other cores via the normal cache coherency protocol, so an IPI is redundant.  FreeBSD also currently lacks a membarrier system call, though that is probably something that needs fixing.

**Comment by sdmaclea** [comment]
> The architecture guarantees that these are visible to the other cores via the normal cache coherency protocol.

That statement is possibly a bit over generalized.  When invalidating a valid page table entry, a TLB invalidate is certainly necessary.  The coherency protocol certainly does not guarantee the TLB is updated.
