### ISSUE TITLE
ResourceManager.GetString doesn't return embedded text file on linux

### ISSUE THREAD

**Issue by Spongman** [dotnet/coreclr#12262]
a (.csproj) project a with an embedded text file, added using the VS2017.2 project properties UI.

[ConsoleApp2.zip](https://github.com/dotnet/coreclr/files/1073187/ConsoleApp2.zip)

on windows, it works fine.

on linux, it just shows:
````
$ dotnet --version
1.0.4
$ uname -a
Linux mybox 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
$ dotnet run
..\Resources\New Text Document.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;Windows-1252
````

**Comment by danmosemsft** [comment]
@tarekgh are there any known issues here?

**Comment by tarekgh** [comment]
please take a look at the issue https://github.com/dotnet/cli/issues/3695 this was CLI issue and I believe it is already fixed bu tI am not sure which release include the fix. I'll move this issue to CLI repo.

**Comment by tarekgh** [comment]
Issue moved to [dotnet/cli #6866](https://github.com/dotnet/cli/issues/6866) via [**ZenHub**](https://www.zenhub.com/)
