### ISSUE TITLE
[Question] Possible GC tuning for memory usage?

### ISSUE THREAD

**Issue by JustArchi** [dotnet/coreclr#12286]
I'm running my .NET core 2.0 app on Linux in very memory "heavy" environment. I'd like coreclr to release as much unused memory as possible back to OS ASAP.

I'll explain what I mean: a single call to `GC.GetTotalMemory(true)` shows that my app uses around 63 MB of memory (I don't have unmanaged/native memory allocated). However, due to recent work dotnet process managed to allocate as much as 29.8% (~ 600 MB) of total memory and seems to keep it for future calls, which can nicely improve performance, but not when system is swapping to satisfy that.

Why I know that the memory can be released? Because after calling the same `GC.GetTotalMemory(true)` 100 times, forcing 100 collections in dirty way, GC still states that around 63 MB is used, but overall memory used by the process drops with every call, down to 9.7%. This is 3x less than what dotnet kept allocated after the initial call, and nothing happened in the meantime in terms of memory pressure - app was completely idle.

I perfectly understand how GC works, but is it possible to somehow tune it in a way that would prefer to do more often collections and preferably release more unused memory back to OS? I'm basically looking for something like `save-target-ratio` and `default-allowance-ratio` from **[Mono](http://manpages.ubuntu.com/manpages/zesty/man1/mono.1.html)**:

```
              save-target-ratio=ratio
                     Specifies  the target save ratio for the major collector.
                     The collector  lets  a  given  amount  of  memory  to  be
                     promoted from the nursery due to minor collections before
                     it triggers a major collection. This amount is  based  on
                     how  much memory it expects to free. It is represented as
                     a ratio of the size of the heap after a major collection.
                     Valid values are between 0.1 and 2.0. The default is 0.5.
                     Smaller values will keep the major heap size smaller  but
                     will  trigger  more  major  collections. Likewise, bigger
                     values will use more memory and result in  less  frequent
                     major  collections.   This  option is EXPERIMENTAL, so it
                     might disappear in later versions of mono.

              default-allowance-ratio=ratio
                     Specifies  the  default  allocation  allowance  when  the
                     calculated size is too small. The allocation allowance is
                     how much memory the  collector  let  be  promoted  before
                     triggered  a  major  collection.   It  is  a ratio of the
                     nursery size.  Valid values are between 1.0 and 10.0. The
                     default is 4.0.  Smaller values lead to smaller heaps and
                     more frequent major collections.  Likewise, bigger values
                     will  allow  the  heap to grow faster but use more memory
                     when  it  reaches  a  stable  size.    This   option   is
                     EXPERIMENTAL,  so it might disappear in later versions of
                     mono.
```

Typically I got very satisfying results when I set above properties to `0.1` and `1.0` respectively.

I took a look at **[coreclr tuning](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md)**, but found only one interesting thing, which I tried right away:

```
export COMPlus_gcTrimCommitOnLowMemory=1
```

However, as expected I have too big swap for dotnet to consider close-to-OOM scenario, I'm not even sure if that option works properly on Linux at all.

Any help would be greatly appreciated, thank you for everything.

**Comment by swgillespie** [comment]
cc @Maoni0 (and cc @vancem who has discussed this before)

On Linux, you can use cgroups to impose a memory limit on your process and the GC will respect it. If you start reaching your cgroup resource limit, the GC will compact more aggressively in turn to keep your memory usage down. On Windows, you can achieve the same sort of thing using job objects.

In general, though, we hear this feedback a fair amount so it's great to get more information on different people's scenarios (thank you!). The answer today is that no, unfortunately today there is no way to tune the GC so that it releases memory to the OS more aggressively other than using OS services. I think that this is something that we would be open to consider in the future, though, especially since there is so much prior art with other runtimes being able to do this (Go and HotSpot spring to mind, and apparently Mono as well).

**Comment by swgillespie** [comment]
Also I took a look at `COMPlus_gcTrimCommitOnLowMemory` and it does not appear that it is referenced anywhere in the code. That sounds like a bug to me, either we should remove that config option or re-introduce it to the GC.

**Comment by Maoni0** [comment]
@JustArchi The 2 mono configs you mentioned really have nothing to do with how GetTotalMemory (true) works so if you are aiming to have GetTotalMemory (true) as a means to collect "as fast as possible", it already does that. GetTotalMemory (true) calls GC.Collect() which does a full blocking GC (it may or may not do a compacting GC depending on the tuning but as you mentioned it always reports 63mb in use so that's what's on the GC heap. That doesn't explain why the total process memory usage keeps dropping. So the first order of things is to find out what's this memory that keeps dropping. If you could share dumps after a couple of GetTotalMemory (true) calls that'd be very helpful.

@swgillespie this config is used on desktop. We could put the code under #ifdef FEATURE_CORECLR but don't remove it.

**Comment by swgillespie** [comment]
> @swgillespie this config is used on desktop. We could put the code under #ifdef FEATURE_CORECLR but don't remove it.

Ok!

**Comment by JustArchi** [comment]
Thank you for answering!

CGroups idea is definitely a nice to know, but that'd impose hard limit on my .NET core app how much memory it can allocate in the first place - I don't want to do that, as my app could crash with OOM under a bit more workload than usual. I'd love to tune GC a bit so it tries to avoid keeping huge amount of memory allocated if it doesn't need it, but at the same time runtime is free to ask for as much memory as it needs to satisfy workload.

I'll try to get some more insight like @Maoni0 recommended and see what I can find. Thanks!

**Comment by JustArchi** [comment]
I'm back with some extra observations.

It seems that the issue I'm describing affects only Server GC mode.

Non-server GC is very "gentle" and I can notice that even small increase of memory from 13.2% to 13.3% quickly leads to drop back to 13.1% soon after given function is done executing. This is exactly what I wanted to achieve without calling GC to collect manually.

However, there is downside that now my app during its most intensive times is capped at 200% of CPU usage (2 logical cores at maximum capacity). I tried with concurrent and non-current non-server GC but it didn't make much difference. This leads to overall lower performance as 20+ async task being executed in parallel previously took only 4-5 seconds of time, now they're taking as much as 12-15. With server GC all CPU cores are being used for processing.

Of course I didn't stop at that and tried to find a bit more info about what in fact is going on.

I did some experiments with `GCSettings.LatencyMode` but without luck - non-server GC in interactive mode doesn't really improve performance by doing more work at once, neither server GC in batch mode cleans more due to being capable of be executed without responsiveness guarantee. I believe it makes difference under the hood for GUI applications, but I'm running CLI bot app that mainly sends requests over HTTP and parses answers.

Then I wrote the most awful C# code in my entire life:

```
using System;
using System.Runtime;
using System.Threading;

namespace ArchiBoT {
	internal static class Hacks {
		private const byte GarbageCollectionCalls = 5; // Number of GC.Collect() calls
		private const byte GarbageCollectionPeriod = 5; // Garbage collection period in seconds, and compaction in minutes

		private static Timer GarbageCollectionTimer;
		private static Timer GarbageCompactionTimer;

		internal static void Init() {
			if (GarbageCollectionTimer == null) {
				GarbageCollectionTimer = new Timer(
					e => GarbageCollect(),
					null,
					TimeSpan.FromSeconds(GarbageCollectionPeriod), // Delay
					TimeSpan.FromSeconds(GarbageCollectionPeriod) // Period
				);
			}

			if (GarbageCompactionTimer == null) {
				GarbageCompactionTimer = new Timer(
					e => GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce,
					null,
					TimeSpan.FromMinutes(GarbageCollectionPeriod), // Delay
					TimeSpan.FromMinutes(GarbageCollectionPeriod) // Period
				);
			}
		}

		private static void GarbageCollect() {
			for (byte i = 0; i < GarbageCollectionCalls; i++) {
				GC.Collect();
				GC.WaitForPendingFinalizers();
			}
		}
	}
}
```

This **does** work with server GC, as in, through very dirty and hacky way I generate extra `GC.Collect()` calls on usual basis, forcing server GC to promote items to further generations and actually clean them, which successfully limited peak usage of server GC from 41% of entire server memory to only 25%, while not affecting performance that heavily.

Probably the most interesting observation is how both modes work compared to each other when not run with any calls to GC from the code.

Server GC typically does not care about memory usage and ask for whatever it needs to maintain maximum performance - this is OK and wanted scenario, but after it's done with heavy work, it still keeps that memory and doesn't want to give it back. Yes, it does give it back eventually after many, many background GC rounds (like what my app tries to create), but in general under normal non-hacky operation it's not possible to reclaim that memory anytime soon. And I noticed that even despite of having 30% memory allocated, it still asks for more from OS instead of taking a look what to clean and re-use what is currently allocated but unused. I know it might be faster and cheaper way to ask for extra and execute given thing instead of cleaning, but definitely there should be some way to limit it.

At that moment I think of something like `soft-heap-limit` from Mono:

```
              soft-heap-limit=size
                     Once the heap size gets larger  than  this  size,  ignore
                     what the default major collection trigger metric says and
                     only allow four  nursery  size's  of  major  heap  growth
                     between major collections.
```

Something like that could be a good metric for server GC how much it can allocate in its "whatever I need" mode, after which it must ensure more or less that every next memory allocation call is in fact reasonable and needed for program operation, and not just done because GC is too "lazy" to do its job 😄.

Basically like I said, if I wanted to put hard limit on my program how much memory it can use, I can do that already, but it's not my objective - I want my app to keep in mind that memory is "expensive" and should be kept at minimum, but at the same time not causing OOM scenarios due to hard limit, as my app is free to ask for more memory, as long as it's **truly needed**.

Non-server GC in fact achieves that, I noticed that it tends to clean up the mess when next allocation is needed, and ask for more memory if needed, while server GC typically doesn't care about the mess and asks for whatever is needed without evaluating that there is a lot ready for cleanup.

If you could in some way consider my scenario for eventual future improvements, that would be great. I'm trying hard to make use of what is already available and not ask for features that are possible to do in one way or another already, but in this scenario I have a choice between non-server GC and server GC with my `GC.Collect()` hack, and you know how awful that one is... 🙂

Thank you for your support!

**Comment by Maoni0** [comment]
Sounds like there are really 2 separate things that you've described - one was that you thought GetTotalMemory was "slowly releasing memory" (I was not convinced of that which was why I asked for more data but it sounds like you don't care about it anymore?); the other is really about how frugal you want GC to be with memory footprint. Something like mono's soft-heap-limit was already discussed in [11338](https://github.com/dotnet/coreclr/issues/11338). So yes we certainly have this on our TODO list. I can't tell you when exactly it will be available but you'll see it as we do the work.

**Comment by JustArchi** [comment]
This is connected though. I evaluated referce source and `GetTotalMemory(true)` calls `GC.Collect()` up to 20 times in a single call, and I did notice that memory goes down with every single call to `GC.Collect()`, until it reaches bare minimum (probably when all generations get cleared or close to that). The initial objective was always to limit amount of "allocated but unused" memory around, so when I noticed that a single call to `GetTotalMemory(true)` always releases some unused memory, I was fine with it, but then when another `GetTotalMemory(true)` call released even more, I was confused, as I thought that first one already did clear everything it could. This is still happening and I can still reproduce it on server GC, I can dig deeper into that if needed.

#11338 looks exactly like something I had in mind, I'm very happy to hear that it's planned. It's also something I didn't think about before - I could experiment with prefer 32-bit mode to indirectly make server GC less expansive. Thanks for answer!

**Comment by JustArchi** [comment]
Prefer 32-bit mode didn't change anything it seems, probably my environment is too small to consider bitness limit (I have 2 GB of ram total, app is expected to use up to 20% of that, so even if there is a difference in pointer size, it's still far below 2/3.5 GB).

After experimenting a bit more I found a solution that is good enough - I just have a timer that calls a single `GC.Collect()` every 2 seconds. Because of server GC, performance doesn't suffer that much (~8% CPU usage in idle), while ensuring that process will return unused memory back to OS at some point after workload. This is still a lot better than non-server GC, as performance hit compared to lack of that timer is negligible, while memory being released makes huge difference when next workload is happening.

This made my app use 8.4% of memory in idle, compared to previous amount of 35% and still asking for more. It's not a very elegant solution, but ensures that memory can grow rapidly when needed (one `GC.Collect()` each 2 seconds in interactive server GC is not enough to affect performance), while at the same time limiting memory in total idle (app releases unused memory in batches each 2 seconds when there is nothing to do).

I'm looking forward to implementation of #11338 - until then I consider this issue as closed, as there is not much to be added in terms of my original goal - now I can be sure that I didn't overlook anything. 

Thank you a lot for your support, I really appreciate it 👍

**Comment by Maoni0** [comment]
> This is connected though. 

That's what doesn't make sense to me. 

GetTotalMemory's implementation is really simple as you can see... it just waits for pending finalizers and induces GC again if the memory change is > 0.05; and does that for at most 20 times. So the only reason it would even be calling multiple GC.Collect at all is the GC memory has changed that much each time. But you are saying you don't see what gets returned from GetTotalMemory change yet it calls GC.Collect 20 times in one call and keeps calling GC.Collect for multiple of your GetTotalMemory calls? It does do WaitForPendingFinalizers but that's still assuming what you get back from GetTotalMemory actually changed enough. If I were you I would debug this - as I said the code is really very simple in GetTotalMemory, you can just step through it.

**Comment by JustArchi** [comment]
@Maoni0 I did the test as you suggested, the issue doesn't seem to be caused by `GC.GetTotalMemory(true)` but by `GC.Collect()` call "forcing" runtime to re-evaluate memory being used and give back to OS a small part each time its run.

I re-coded GC.GetTotalMemory(true) and added debug routines. Then as usual I waited till my app is done with work it has to do, leaving a lot of garbage to be collected in next call. The result is here: https://hastebin.com/omozezenis.rb

The app was more or less idle during testing period, yet after each `GetTotalMemory(true)` call overall memory being used by the process was dropping. As you can see, this is not the result of `GetTotalMemory(true)` executing many collections itself, but in fact `GC.Collect()` being called in the first place, at least once when `GetTotalMemory(true)` is called. This is what makes runtime re-consider and give memory back to OS - collection, getting total memory call is just a tool making it happen.

This is also why my workaround works fine for my use-case, because I call `GC.Collect()` each 2 seconds, "forcing" runtime to re-evaluate and release some chunk of memory back to OS. I'm not GC specialist here, but it's clear to me that runtime wants to keep as much memory as possible and it takes a lot of `GC.Collect()` calls to make it slowly release what it allocated back.
