### ISSUE TITLE
How to (and how to even know how to) resolve dependency conflict issues

### ISSUE THREAD

**Issue by axefrog** [dotnet/coreclr#1228]
I'm having some trouble trying to get my project to build. I started a game engine project in .Net a little while ago with the view to be able to compile for Linux and OS X when .Net 5 and the surrounding ecosystem had matured enough. I figured late beta versions were probably far enough along that I could start experimenting with transferring my projects and source files to the new runtimes and project format.

The first platform I'm supporting is Windows, using SharpDX, which has a 3.x version that supports coreclr. I've kept my Windows-specific stuff in a separate project/package and kept the core engine code completely platform independant. My first attempts at getting this new setup working are failing though.

My primary platform-independent project will not build at all, citing several errors like this:

    (1,29): error CS0433: The type 'AssemblyFileVersionAttribute' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

and *hundreds* of errors like this:

    (1,58): error CS0518: Predefined type 'System.String' is not defined or imported
    (2,54): error CS0518: Predefined type 'System.String' is not defined or imported
    (3,67): error CS0518: Predefined type 'System.String' is not defined or imported
    error CS0518: Predefined type 'System.Void' is not defined or imported
    error CS0518: Predefined type 'System.Void' is not defined or imported
    error CS0518: Predefined type 'System.Boolean' is not defined or imported

The new project.json file looks like this:

    {
        "version": "1.0.0-alpha-1",
        "description": "Core library for the Grasshopper game engine",
        "authors": [ "Nathan Ridley" ],
        "tags": [ "game engine" ],
        "projectUrl": "https://github.com/GrasshopperEngine/Grasshopper",
        "licenseUrl": "https://github.com/GrasshopperEngine/Grasshopper/LICENSE.txt",

        "dependencies": {
            "Serilog": "1.5.7",
            "System.Numerics.Vectors": "4.1.0-beta-23019",
            "Rx-Core": "2.3.0-beta2",
            "Rx-Interfaces": "2.3.0-beta2",
            "Rx-Main": "2.3.0-beta2",
            "Rx-PlatformServices": "2.3.0-beta2",
            "Microsoft.CSharp": "4.0.0-beta-23019"
        },

        "frameworks": {
            "dnx451": {},
            "dnxcore50": { }
        }
    }

Here are the runtimes I have installed:

    Active Version           Runtime Architecture Location                      Alias
    ------ -------           ------- ------------ --------                      -----
           1.0.0-beta4       clr     x64          C:\Users\nathan\.dnx\runtimes
           1.0.0-beta4       clr     x86          C:\Users\nathan\.dnx\runtimes
           1.0.0-beta4       coreclr x64          C:\Users\nathan\.dnx\runtimes
           1.0.0-beta4       coreclr x86          C:\Users\nathan\.dnx\runtimes
           1.0.0-beta5-12103 clr     x86          C:\Users\nathan\.dnx\runtimes
      *    1.0.0-beta6-12216 clr     x86          C:\Users\nathan\.dnx\runtimes default

I have no idea how to resolve the errors I mentioned above. I don't even understand what relationship between mscorlib and System.Runtime is, or how or why a conflict is even occurring there. I can actually delete the `dnx451` framework target from the project file and all of the errors disappear, but I can't do that because I *need* dnx451 as a platform target, otherwise I can't open a window in which to render graphics.

1. How do I resolve the above errors, and what do I need to know to avoid them in future so that I can properly use the dnx451 platform target?

2. What is the relationship between the dnx451 platform target and the old, monolothic, non-modular .Net 4.5.1, which predates dnx?

**EDIT**
I added the following line to my project's shared dependencies and the number of errors dropped to 5:

    "System.Runtime": "4.0.20-beta-22816"

And I get these errors (cropped for brevity):

    error CS0433: The type 'Stopwatch' exists in both 'System.Runtime.Extensions, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    error CS0433: The type 'Environment' exists in both 'System.Runtime.Extensions, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    error CS0433: The type 'Stopwatch' exists in both 'System.Runtime.Extensions, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    error CS0433: The type 'Stopwatch' exists in both 'System.Runtime.Extensions, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    error CS0433: The type 'Convert' exists in both 'System.Runtime.Extensions, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Note that I am using VS2015 RC, coupled with some help from the command line, and ReSharper 9.1 just to add a bit of extra exploratory help, and none of them offer any suggestions regarding the correct way to resolve these sorts of issues. What's the new workflow supposed to look like with regards to figuring out what dependencies to specify for different scenarios?

My earlier questions still stand also, I guess.

**Comment by jasonwilliams200OK** [comment]
"how to know which dependencies.."

I checked the docs: https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md#restore-nuget-packages, and it points to gh-480.

**Comment by axefrog** [comment]
Hmm, that's a start I guess, thanks. Why do I need to reference all of those in my project.json when of various samples and projects I've generated (using yeoman, etc.) need to have them added manually? As an example, here's an error I haven't resolved yet:

> D:\Dropbox\Work\GameDev\Grasshopper\CoreClr\src\core\Grasshopper.Core\Graphics\Rendering\Buffers\MeshBuffer.cs(3,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)

That is actually complaining about the "using" line, and yet I have another MVC6 project I create and in which I am using LINQ, and I get no such errors, nor is System.Linq referenced in the project file.

I'm about to read [Book of the Runtime](https://github.com/dotnet/coreclr/tree/master/Documentation#book-of-the-runtime) - maybe there will be some insights buried within...

**Comment by akoeplinger** [comment]
@axefrog check the project.lock.json to see the complete closure of your dependencies. I suspect that in your MVC project, something already transitively pulls in the System.Linq package, that's why it works there. In a barebones project you need to explicitly add the package.

**Comment by axefrog** [comment]
What's the workflow supposed to look like normally? I would have thought Visual Studio would generally prompt me to add references when they're missing, though perhaps that's a bad assumption.

**Comment by akoeplinger** [comment]
Yes, VS should prompt you via the light bulb to add the dependency.

**Comment by akoeplinger** [comment]
To answer your initial question: the `dnx*` targets mean *running on the DNX host*. `dnx451` means the plain-old monolithic .NET 4.5.1 running on the DNX host, while the `dnxcore50` means the refactored, modular .NET Core running on DNX.

In the old world, a bunch of stuff was put into mscorlib (basic building blocks like `string`, etc., but also stuff like System.IO). In the new world, those were factored out into separate packages and System.Runtime acts as the package that contains the basic building blocks (some of it is actually still implemented in mscorlib.dll, but you can treat that as an implementation detail) and System.IO has its own package.

**Comment by axefrog** [comment]
Ok, that makes sense. So why do I get errors complaining that something exists in *both* System.Runtime and mscorlib if I don't explicitly reference core stuff like System.Collections and so forth? As an experiment I deleted my newly-added references to the project.json file, and I deleted the lock file to make it regenerate, and all of those errors came back. Still quite confused about that. I've disabled ReSharper too, just to see if that's causing a problem. VS2015RC is crashing a lot when I go into certain erroneous cs files, making it harder to figure out where the problem is...

**Comment by akoeplinger** [comment]
Can you share an example project? Looks like something is pulling in mscorlib while it shouldn't.

**Comment by axefrog** [comment]
Here it is. https://www.dropbox.com/s/jos5a0eyn91yk24/Grasshopper.Core.zip?dl=0

**Comment by axefrog** [comment]
More dependency woes... As a test, I went and created a new ASP.NET MVC project and tried to build it. The package restore completedsuccessfully, but then when I ran it, I got issues complaining about missing ILibraryManager or something like that. Then I found this: https://github.com/aspnet/Home/issues/650, which made sense, so I went into the project.json file in VS2015RC and used CTRL+SPACE to figure out which package versions could be upgraded, and set all the ones to beta5 that seemed to be upgradable. End result? Multiple occurrences of "System.String is not defined or imported"...

*sigh*...

**Comment by akoeplinger** [comment]
@axefrog it works with this project.json:

```json
{
    "version": "1.0.0-alpha-1",
    "description": "Core library for the Grasshopper game engine",
    "authors": [ "Nathan Ridley" ],
    "tags": [ "game engine" ],
    "projectUrl": "https://github.com/GrasshopperEngine/Grasshopper",
    "licenseUrl": "https://github.com/GrasshopperEngine/Grasshopper/LICENSE.txt",

    "dependencies": {
        "Serilog": "1.5.7",
        "Rx-Core": "2.3.0-beta2",
        "Rx-Interfaces": "2.3.0-beta2",
        "Rx-Main": "2.3.0-beta2",
        "Rx-PlatformServices": "2.3.0-beta2"
    },

    "frameworks": {
        "dnx451": {
            "frameworkAssemblies": {
                "System.Runtime": "",
            },
            "dependencies": {
                "System.Numerics.Vectors": "4.0.0",
            },
        },

        "dnxcore50": {
            "dependencies": {
                "System.Numerics.Vectors": "4.1.0-beta-23019",
                "System.Collections": "4.0.0-beta-23019",
                "System.Linq": "4.0.0-beta-23019"
            }
        }
    }
}
```

As far as I can see, the issue was the System.Numerics.Vectors package that exists in an earlier version for the normal .NET 4.5.1 target. Additionally, the `frameworkAssemblies` key above means that System.Runtime will be pulled in from the GAC.

**Comment by axefrog** [comment]
@akoeplinger Awesome, thanks for the help! Managing the project.json file seems to be a bit of an exercise in shamanism. Perhaps I will sacrifice a goat and pray for the tooling to make the process simpler :D

**Comment by akoeplinger** [comment]
@axefrog I first duplicated the dependencies between the targets instead of using the shared one, then remembered that System.Numerics.Vectors already shipped a while ago before .NET Core was a thing and then looked at the package itself. Turns out the new package only supports net46, so that's why it doesn't work on net451. The older package does however.

**Comment by axefrog** [comment]
Thanks. Loving this whole new direction for .Net, despite the unexpected learning curve.

**Comment by nelsonsar** [comment]
Sorry for revive this issue, but, it's the most similar problem to mine I was able to found searching today.

I'm having a similar issue: I have to projects ```CLibrary```, a class library project, and ```ConsoleApp```, a console application.

```CLibrary```'s project.json file is:

```json
{
  "version": "1.0.0-*",
  "description": "CLibrary Class Library",
  "tags": [""],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
    "System.Collections": "4.0.10-beta-23019",
    "System.Linq": "4.0.0-beta-23019",
    "System.Threading": "4.0.10-beta-23019",
    "Microsoft.CSharp": "4.0.0-beta-23019",
    "System.Runtime": "4.0.20-beta-*"
  },

  "frameworks": {
      "dotnet": {}
  }
}
```

And ```ConsoleApp```'s project.json:

```json
{
  "version": "1.0.0-*",
  "description": "SimpleDependecy Console Application",
  "tags": [""],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
      "CLibrary": "1.0.0-*"
  },

  "commands": {
    "run": "run"
  },

  "frameworks": {
    "dnx451": {
    },
    "dnxcore50": {
      "dependencies": {
        "System.Collections": "4.0.10-beta-23109",
        "System.Console": "4.0.0-beta-23109",
        "System.Linq": "4.0.0-beta-23109",
        "System.Threading": "4.0.10-beta-23109",
        "Microsoft.CSharp": "4.0.0-beta-23109"
      }
    }
  }
}
```

I'm facing the same exception described by @axefrog. I did tried to add ```frameworkAssemblies```, but it did not work.

**Comment by teyc** [comment]
@nelsonsar I've provided a Gist https://gist.github.com/teyc/1a8a5ce733f4e427027a that works against dnxcore50 beta8 on OS X.

**Comment by stevenattwell** [comment]
Hello, not sure if this is the correct place to register this issue, if not apologies and could you point me to the correct issues list? 

I get similar problem/error syntax running beta7 when adding  **System.Data.SqlClient** to a Web API project where I am already referencing  **MySql.Data** and **MySql.Data.Entity**. I am attempting to execute stored procedures from both MySQL and SQL Server within the same project. After adding System.Data.SqlClient the following error occures,

```MSBUILD : DNX 4.5.1 error CS1703: Multiple assemblies with equivalent identity have been imported: '<in-memory assembly>' and '<in-memory assembly>'. Remove one of the duplicate references.```

The repro steps are,
1. Create a new ASP.NET Web Application
2. Select ASP.NET 5 Preview Templates -> Web API
3. Update project.json as below

```
    {
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {
    "EntityFramework": "6.1.3",
    "Microsoft.AspNet.Mvc": "6.0.0-beta7",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta7",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta7",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta7",
    "MySql.Data": "6.9.7",
    "MySql.Data.Entity": "6.9.7",
    "System.Data.SqlClient": "4.0.0-beta-23225"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --config hosting.ini"
  },

  "frameworks": {
    "dnx451": {
    }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ]
}
```
Adding the ```frameworkAssemblies``` key did not work.

**Comment by tzwlai** [comment]
@Sridhar-MS, assigning this to you for now.  Please feel free to reassign as appropriate.

**Comment by sergiy-k** [comment]
Hi @axefrog, based on the comments it seems that the issue you reported got resolved. Would it be OK to close this issue?

**Comment by axefrog** [comment]
Yes, I'm not having this problem currently, thankyou.

**Comment by sergiy-k** [comment]
Thank you!
