### ISSUE TITLE
Assembly loader fails to load assemblies with cyclic references

### ISSUE THREAD

**Issue by leppie** [dotnet/coreclr#12302]
```
λ dotnet --version
2.0.0-preview2-006391
```

**Expected:** Works as it does on the desktop version of .NET
**Actual:** Fails with `FileNotFoundException`

Note: This repro could probably be made smaller, but this is what I experienced with IronScheme.

# Setup
A.il
```
.assembly extern mscorlib {}
.assembly extern C {}
.assembly A {}
.module A.dll

.class public A 
{
    .method public static void Main()
    {
        .entrypoint
        ldstr "Hello"
        call object [C]C::FromA(object)
        pop
        ret
    }

    .method public static object FromB(object o)
    {
        ldarg.0
        ret
    }
}
```

C.il
```
.assembly extern mscorlib {}
.assembly extern B {}
.assembly C {}
.module C.dll

.class public C 
{
    .method public static object FromA(object o)
    {
        ldarg.0
        call object [B]B::FromC(object)
        ret
    }

    .method public static object FromB(object o)
    {
        ldarg.0
        ret
    }
}
```

B.il
```
.assembly extern mscorlib {}
.assembly extern A {}
.assembly extern C {}
.assembly B {}
.module B.dll

.class public B 
{
    .method public static object FromC(object o)
    {
        ldarg.0
        call object [C]C::FromB(object)
        call object [A]A::FromB(object)
        ret
    }
}
```

Compile all:
```
ilasm /dll A.il
ilasm /dll C.il
ilasm /dll B.il
```
All 3 outputs pass PEVerify (Entrypoint error can be ignored for DLL output).

# .NET Core 2.0 test
Create .NET Core 2.0 console app
Program.cs
```
class Program
{
    static void Main(string[] args)
    {
        A.Main();
    }
}
```
Project file
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="A">
      <HintPath>A.dll</HintPath>
    </Reference>
    <Reference Include="B">
      <HintPath>B.dll</HintPath>
    </Reference>
    <Reference Include="C">
      <HintPath>C.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```
Run
```
dotnet run
```
Result
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'C, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at A.Main()
```

# .NET desktop test
Compile
```
del A.dll
ilasm A.il
```
Run
```
A.exe
```
Result: Runs without error.

**Note:** If you merge A,B,C into 1 assembly (ilmerge/ilrepack), it runs fine on .NET Core 2.0

**Comment by karelz** [comment]
@davidwrighton interesting TypeSystem bug ... cc @jkotas 

@leppie do you have the C# intended code? (it is often faster to read than "reverse engineer" IL)

**Comment by leppie** [comment]
@karelz Each method just calls a method in the referenced assembly. Easiest way to view this would be in Reflector or your favourite .NET decompiler. The actual code in IronScheme involves a mixture of C#, Scheme and IL.

**Comment by jkotas** [comment]
@karelz This is not type system problem. This is assembly loader.

I am not able to reproduce the problem.

@leppie Could you please check that:
- bin\Debug\netcoreapp2.0  directory contains all A.dll, B.dll, C.dll
- bin\Debug\netcoreapp2.0\repro.deps.json has references to all A.dll, B.dll, C.dll

Or could you please share the zip file with your repro, and the compiled app?

**Comment by leppie** [comment]
@jkotas All 3 dll's present, but only A shows up in deps.json.

And after I did `dotnet build /t:clean` followed by `dotnet run`, it works, and all the dll's are listed in deps.json. 

Maybe this is a build issue? I added the references via VS2017 initially.

**Comment by leppie** [comment]
Tried to same approach now with IronScheme, but getting an obscure `null this` issue and only the property where it happens is in the callstack. 

Again, when I merge all of these assemblies together, I had no issue.

**Comment by leppie** [comment]
Closing for now till I can get more info what is going on.

**Comment by jkotas** [comment]
> Maybe this is a build issue?

Yes, this looks like a build issue. Build issues like this one belong to https://github.com/dotnet/cli

**Comment by davkean** [comment]
Build issues actually go in http://github.com/dotnet/sdk. CLI is just wrapper.
