### ISSUE TITLE
(Proposal) Make a Magic Number a Constant instead.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/coreclr#1232]
The `1000000` in the following should be exposed as a public constant.

[StringBuilder.cs Line: 1364](https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/mscorlib/src/System/Text/StringBuilder.cs#L1364)
[StringBuilder.cs Line: 1387](https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/mscorlib/src/System/Text/StringBuilder.cs#L1387)

```
public const int32 FormatArg_Alignment_Width_Limit = 1000000
public const int32 FormatArg_ArgIndex_Limit = 1000000
```

It's not ever stated in the available documentation that such a limit even exists, and it takes a bit of dig to find it. By making it a `public const`, should that value ever change in some edition of the BCL it is exposed to developers, so that they can take it into account.

**Comment by Clockwork-Muse** [comment]
Frankly, given you can designate _any_ index (you can skip directly to `int.MaxValue`), it would be more future-proof to just bump the index limit (although you'd need to take a bit of care on the ending condition).  A maximum of 4 more iterations, and most args exit the loop before performing that check because they get a non-numeric character anyways.
Of course, given usual use patterns, why somebody would have more than 100 arguments is a little curious...

I think the other one would be better using "Padding".  Why can you add 1mil pad characters, though?  That seems a tad excessive - if a character is 2mm (~16pt?), the resulting pad sequence is 2km long (a bit over a mile).  Anybody who needs anything that size is probably using a custom solution in the first place.

That code makes me nervous; maybe it should be broken up?  Although if the current form was for performance reasons, perhaps comments are in order.

**Comment by AdamSpeight2008** [comment]
@Clockwork-Muse 
> That code makes me nervous

Me too. Then I had to do reimplementation for a Roslyn Diagnostic, which required more information and error recovery. So it could report all of the issues, not just the first one. I eventually through an iterative approach, break it up into separate methods. Producing an object model over format strings 
* Parse Text
* Parse Arg Hole  
** Parse Index    
** Parse Alignment  
** Parse Format  

It's a similar in approach used parse  Interpolation Strings. 
Resulting in an object model over format strings, that permits me to do further analysis independent of the parsing and language.

**Comment by AdamSpeight2008** [comment]
@Clockwork-Muse 
I've created a new repo [Format String Parser](https://github.com/AdamSpeight2008/FormatStringParser) if you're interested in a re-implementation of the parsing method,.

**Comment by AdamSpeight2008** [comment]
**Options**
**1. Do nothing**

**2. Refactor**  
Potential to introduce new bugs, change in behavior (since documentation on it scarce).
+ Refactor into smaller more discrete functions. Eg  
Parse_ArgHole, Parse_ArgIndex, Parse_ArgAlign, Parse_ArgFormat, Parse_Digits, Parse_Whitespace
+ Similar design to what is used by Roslyn to do String Interpolation. Potential to use that instead.

Let assume that those ain't affected (bugs / behaviour), would it be a performance improvement.
- the grammar is a little tricky, to get right.
Eg. Do validation checks before construction of the output?
+ Thus no string-builder is used, in the error cases.
+ In the valid case, potential to know the approximate length of the output before construction. ( which include the alignment values of the *Argholes*). *ArgFormat* is trickier (if not impossible to 100% know).
+ Thus initial size of the string builder and subsequently less resizing.
+ See (Format String Parser) for a partial implementation.
Is the additional record keeping worth it?

**3. Add additional comments**  
(See PR #1261  commit: 1)
+ Overview of what each section of the algorithm is doing.
+ Better information on what the thrown exceptions, actual are. 

**4. Make the limits publicly accessible constants / read-only properties on the object.**  
(See PR #1261 commit: 2)
+ Potential to change their value depending on the target build. (eg Smaller for mobile / IoT )
+ Tooling / Extension can utilize it for compile-time analysis and diagnostics.

**5. Make the limits publicly known via the documentation (eg MSDN)**

**Comment by AdamSpeight2008** [comment]
@terrajobst 
I've been research a new implemenation `.Format` which parses the format string into a simple object model first, before constructing the output. Currently the `.net` impliementation constructs the output at the same time as parsing.

**Initial Analysis**
Tests with format strings without `argholes`, suggest it is at least **2 - 3 times faster**.
Since first parse to a simple object model;-
* If the format string contains no `argholes`
 * it returns the original string.
 * No string builder involved    

*The following have not been timed yet.*
* it does allow me to calculate a good estimate for the initial capacity for the stringbuilder.   
 * At least number the text characters in the non-arghole parts for format string.
 * Takes into account escaped opening `{{` and closing `}}` braces *(excludes arghole's `format`)*
 * Takes into account any arghole with `alignment` values.
 * Thus reducing the cost of resizing. 
* It has the potential to throw the same exceptions without constructing the output
 * which happens in the current `.net` implementation.   

Potential additions
* Caching of arghole arg's `.ToString` value. 
 * Thus isn't recalculated

Tests with format strings with `argholes` haven't be performed, as I've yet to implement the construction of the output section. 

Further analysis needs to be done
* How does the book-keeping affect garbage collection?
* Does a full implementation provide actual gains?

initial test show actual "performance" gains, and further potential gains.

**Comment by weshaggard** [comment]
@AdamSpeight2008 closing this as at this point I think do nothing is the right answer here for exposing the constants. I do think it is still work further investigating in better formatting APIs but I think that is a completely separate issue and belongs in the corefxlab repo for now.
