### ISSUE TITLE
build CoreCLR in win10 x64 error: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

### ISSUE THREAD

**Issue by yangliweng** [dotnet/coreclr#12327]
PS D:\project\coreclr> .\build
Starting Build at 22:29:17.89
BUILD: Commencing CoreCLR Repo build
BUILD: Checking prerequisites
BUILD: Using environment: "D:\vs2017\Common7\Tools\\VsDevCmd.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26430.13
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
Tools are already initialized.
Running: D:\project\coreclr\Tools\dotnetcli\dotnet.exe D:\project\coreclr\Tools\run.exe D:\project\coreclr\config.json b
uild -Project=D:\project\coreclr\build.proj -generateHeaderWindows -NativeVersionHeaderFile="D:\project\coreclr\bin\obj\
_version.h" -BuildOS=Windows_NT -BuildType=Debug -BuildArch=x64

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Prim
itives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.。
   at Newtonsoft.Json.JsonConvert.DeserializeObject
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T]
   at Microsoft.DotNet.Execute.Executor.OpenFile()
   at Microsoft.DotNet.Execute.Executor.Main(String[] args)
BUILD: Restoring the OptimizationData Package
Tools are already initialized.
Running: D:\project\coreclr\Tools\dotnetcli\dotnet.exe D:\project\coreclr\Tools\run.exe D:\project\coreclr\config.json s
ync -optdata

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Prim
itives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 
   at Newtonsoft.Json.JsonConvert.DeserializeObject
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T]
   at Microsoft.DotNet.Execute.Executor.OpenFile()
   at Microsoft.DotNet.Execute.Executor.Main(String[] args)
BUILD: Error: Failed to restore the optimization data package.
can  anyone help me  ?thanks.my  environment is vs2017 enterprise edition

**Comment by RodDaSilva** [comment]
I am getting the exact same issue but on a Windows 8.1 machine.  One note, I download a ZIP of the repo rather than forked it from Git.  Not sure if that could be the issue or not.  Would really like to get this solved.  This is my first time trying to build the CoreCLR project from source.  Have you been able to do this before, or is this your first time as well?  Just wondering if this is a new problem with the latest build or something.

Rod

**Comment by yangliweng** [comment]
@RodDaSilva Hi,this  is  not  my  first  time to build  coreclr,i built  it several  month  ago  on another  laptop,it  was successful to build.

**Comment by yangliweng** [comment]
I  have no idea  to  solve it ,the  final  solution  is  run  clean  command to  re-install  cli and  others.
