### ISSUE TITLE
Bring up Arm32 test runs

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#12336]
- [x] Enable running the test suite for Arm32 on a dev box
- [x] Enable running Arm32 tests in Helix

**Comment by wtgodbe** [comment]
CC @weshaggard @gkhanna79

**Comment by gkhanna79** [comment]
CC @danmosemsft @joshfree

**Comment by danmosemsft** [comment]
Yes please.

**Comment by Petermarcu** [comment]
Can we write down what UWP customer scenarios we expect to be running coreclr on ARM32?

**Comment by danmosemsft** [comment]
@wtgodbe anything remains here or can we close this
What would it mean to run ARM32 tests on a dev box?

**Comment by wtgodbe** [comment]
We can close this, a dev would need an Arm32 box to run tests locally no matter what.
