### ISSUE TITLE
build-test.sh failing on linux with "Windows PDB writer is not available"

### ISSUE THREAD

**Issue by salrashid123** [dotnet/coreclr#12394]
The test suite build script recently started failing on linux with the exception:

```bash
CSC : error CS0041: Unexpected error writing debug information -- 'Windows PDB writer is not available -- could not find Microsoft.DiaSymReader.Native.amd64.dll' [/usr/local/home/srashid/Desktop/dotnet_unit_latest/coreclr/tests/src/JIT/Regression/JitBlue/GitHub_12037/GitHub_12037.csproj]
/usr/local//home/srashid/Desktop/dotnet_unit_latest/coreclr/tests/dir.traversal.targets(25,5): error : (No message specified) [/usr/local/home/srashid/Desktop/dotnet_unit_latest/coreclr/tests/src/dirs.proj]
/usr/local/home/srashid/Desktop/dotnet_unit_latest/coreclr/tests/dir.traversal.targets(25,5): error : (No message specified) [/usr/local/home/srashid/Desktop/dotnet_unit_latest/coreclr/tests/build.proj]
    172 Warning(s)
    3 Error(s)

Time Elapsed 01:24:17.02
Command execution failed with exit code 1.
```
This happens on multiple machines when building with latest

the build-test script used to work just a week ago with 
  commit 699b25847ec14e47abc03cf7f3a1ffdb249d68b6 
after converting the three files cited on  [issue #12182 ](https://github.com/dotnet/coreclr/issues/12182) for utf-8 encoding

however, a git clone from the current
 commit cf63336cbc2597801d62e399be6bdba8938d1034  failes with the exception above

(I noticed the file  /coreclr/tests/build.proj doesn't have end of file [noeol]  but thats not an issue)

```bash
$ uname -a
Linux workstation.sfo 4.4.0-78-generic #99~14.04.2-Ubuntu SMP Thu Apr 27 18:49:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ locale 
LANG=en_US.UTF-8
LANGUAGE=en_US:
```

**Comment by rartemev** [comment]
This is the known problem. It happened because a bug in Roslyn for Linux. Hope it will be fixed soon.

Fast fix would look like replacing

`<DebugType></DebugType>` with `<DebugType>None</DebugType>` in .csproj file.

**Comment by salrashid123** [comment]
thanks; that worked.

**Comment by RussKeldorph** [comment]
I assume this is no longer an issues.  Please re-open if it is.
