### ISSUE TITLE
Want a turnkey way to build the product without building the tests.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/coreclr#1240]
The top level build.cmd script could really use an option to build the product without building and running all the tests.

**Comment by jasonwilliams200OK** [comment]
@mmitche, is it possible for build.[cmd/sh] to accept a CLI switch say `--ignore-test`, without affecting the CI setup?

**Comment by AtsushiKan** [comment]
#1247 fixed issue by adding "skiptestbuild" switch to build.cmd.
