### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'e_sqlite3' with .Net Core 2 project on Raspberry PI 

### ISSUE THREAD

**Issue by longo-net** [dotnet/coreclr#12445]
We have an application developed with .NET Core 2.0 Preview 1 that use entity framework with a sqlite db.
The app works fine on pc with windows and linux with x64 cpu, but if we publish it to "ubuntu.16.04-arm" runtime and copy the output on Raspberry Pi 2, when we try to run the app we have this error:

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found.
(Exception from HRESULT: 0x8007007E)
at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
at SQLitePCL.Batteries_V2.Init()

In the folder root there are two subfolders called "x86" and "x64" with inside "e_sqlite3.dll".

Could it be that the arm version of e_sqlite3.dll is missing?

**Comment by borrrden** [comment]
That's probably exactly it.  Until now there was no reason to compile this library for ARM because the only C# that ran on ARM was via UWP.  However, I think you should contact the owner of the SQLite.raw repo instead since he is the one in charge of these builds.

**Comment by tijoytom** [comment]
@longo-net Is this issue resolved ? I think the resolution is with SQLite.raw and it's not a dotnet core issue per se .I am closing this one.
