### ISSUE TITLE
DllImportAttribute doesn't import native libraries on OS X

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/coreclr#1244]
In attempting to build and test [aspnet/Microsoft.Data.Sqlite](https://github.com/aspnet/Microsoft.Data.Sqlite) against CoreCLR on OS X, I have encountered this issue:

`DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found.`

Shouldn't this use the default behavior of `dlopen`? i.e. it should find */usr/lib/libsqlite3.dylib*

My setup:
dnx CoreCLR
x64
1.0.0-beta6-12231
OS X Yosemite

**Comment by stephentoub** [comment]
To clarify, you're expecting that passing the string "something" to DllImport will bind to a library in a file with a "lib" prefix on the name, e.g. "libsomething"?

**Comment by natemcmaster** [comment]
Correct. Unless dllmaps are added (#930), we expect "sqlite3" to map to "libsqlite3.dylib"

Example from [our code](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/Interop/NativeMethods.cs#L53)
```c#
[DllImport("sqlite3", CallingConvention = CallingConvention.Cdecl)]
public static extern int sqlite3_bind_blob(Sqlite3StmtHandle pStmt, int i, byte[] zData, int nData, IntPtr xDel);
```

**Comment by stephentoub** [comment]
Thanks.  I was just asking for clarification because you stated you were hoping for the default behavior of dlopen, but to my knowledge dlopen doesn't do this kind of automatic prefixing/suffixing of default values.

**Comment by natemcmaster** [comment]
True. Good point. This is the default behavior of mono, not dlopen.

**Comment by stephentoub** [comment]
Thanks for the clarification.  Important issue to get resolved in some manner, but I think we have this well covered in two other issues (the #930 you mentioned and the earlier #444), both of which are still open and need some investment. Given that and the name of this issue, can you confirm that by using an appropriate name ("libsqlite3" or "libsqlite3.dylib") passed to DllImport that the library is being successfully loaded?  If so, I'd like to close this as a dup.

**Comment by natemcmaster** [comment]
Verified. "libsqlite3" loads the image. Closed as a dup.

But I want to emphasize what a pain this is. The workaround is large amounts of code to detect which platform we run (windows vs OS X, mono vs coreclr), just so we can change "sqlite3" to "libsqlite3" when appropriate.

**Comment by stephentoub** [comment]
> But I want to emphasize what a pain this is.

Believe me, I understand :smile:

**Comment by akoeplinger** [comment]
I fully agree with @natemcmaster, this is a real pain for cross-plat apps (hence why I opened #930) and I really hope we can push forward on a solution to this soon!
