### ISSUE TITLE
runtime args error giving a bad message

### ISSUE THREAD

**Issue by pynixwang** [dotnet/coreclr#12446]
```Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
         http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

when i use dotnet runtime but dll path is error,  `dotnet` show me this bad message, it 's very hard to find the problem. other errors also show this message.

**Comment by janvorli** [comment]
Issue moved to [dotnet/cli #7249](https://github.com/dotnet/cli/issues/7249) via [**ZenHub**](https://www.zenhub.com/)
