### ISSUE TITLE
Investigate release/2.0.0 x64 vs x86 throughput differences

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#12454]
In all of our throughput benchmarks, x86 throughput is worse than x64. We need to investigate this so we can understand these throughput differences.

category:throughput
theme:throughput
skill-level:expert
cost:small

**Comment by adiaaida** [comment]
Phases that most impact these differences:

Importation
Morph - Inlining
VN based copy prop
Assertion Prop
Local var Liveness
Lowering

In the case of assertion prop and lower, we seem to have to process additional blocks on x86. Also in lowering, we have to decompose longs, which adds a significant amount of time to throughput.

**Comment by BruceForstall** [comment]
This is obsolete now, so closing. We should do another round of cross-arch/cross-platform throughput comparisons sometime.
