### ISSUE TITLE
[x86][LEGACY_BACKEND] Assertion failed 'arg0VNtyp == arg1VNtyp'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#12465]
Tests:
```
Assert failure(PID 4640 [0x00001220], Thread: 10932 [0x2ab4]): Assertion failed 'arg0VNtyp == arg1VNtyp' in 'ILGEN_0x65088b5c:Method_0x5ad2583a(long,char,int,ubyte,byte,short,ubyte):long' (IL size 440)

JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b77304\b77304\b77304.cmd
```
run with:
```
set COMPLUS_AltJit=*
set COMPLUS_AltJitNgen=*
set COMPLUS_AltJitName=legacyjit.dll
set COMPLUS_NoGuiOnAssert=1
set COMPLUS_AltJitAssertOnNYI=1
```

**Comment by pgavlin** [comment]
@rartemev can you take a look at this?

**Comment by rartemev** [comment]
Is the following sequence correct? 

```
    IL_0127:  ldc.r8     3.1090543741470467e-094
    IL_0130:  ldsfld     float32 ILGEN_0x65088b5c::field_0x8$PST04000009
    IL_0135:  ceq
```

If so the problem is about assert which fails on `arg0VNtyp == float64` and `arg1VNtyp == float32` otherwise the test is incorrect.

**Comment by pgavlin** [comment]
IIUC that IL is legal. As per ECMA-335, all floating-point values are converted to type `F` (the internal floating-point representation) when they are pushed onto the evaluation stack, so the types of the compare's operands do match.

cc @dotnet/jit-contrib
