### ISSUE TITLE
CoreMangLib_cti._system_string_StringJoin_StringJoin fails in Helix on ARM

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#12491]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170626.03/workItem/CoreMangLib.cti.XUnitWrapper/analysis/xunit/CoreMangLib_cti._system_string_StringJoin_StringJoin_~2F_system_string_StringJoin_StringJoin_cmd

> Beginning scenario: 00O: Testing String.Join\r\nERROR!!!-006: Error in 00O, expected exception did not occur

@jkotas can you route this to the right person?

**Comment by jkotas** [comment]
cc @BruceForstall do you see this failure in your Windows ARM runs? If there is a bug, it is most likely in the JIT.

**Comment by BruceForstall** [comment]
I haven't had successful runs yet on my box, but I'll look for it.

**Comment by BruceForstall** [comment]
I see that fail (for both LEGACY_BACKEND and JIT32/arm32). The failure mode is:
```
ERROR!!!-006: Error in 00O, expected exception did not occur.
```
Looks like it's trying to create an enormous string an expecting to get an OutOfMemoryException. Seems like probably a VM issue generating that exception?
```
    public bool Test14() {
        string longStr = string.Empty;
        try
        {
            longStr = new string('a', 507374182);
        }
        catch (OutOfMemoryException) { return true; }   // If the system is too low on resources to create this string, there's nothing we can do
        return (IntPtr.Size == 4)?NegativeTest(longStr, new string[] { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m" }, 0, 3, typeof
(OutOfMemoryException), "00O"):true;
    }
```

**Comment by jkotas** [comment]
The size of the resulting string is 1.93GB. It is possible that there is enough contiguous address space when running on ARM in WoW to fit it in. ARM WoW gives the process close to 4GB address space.

I would double check that the string returned by the Join has the expected lenght. If it is the case, this is a bad test that should be deleted.

**Comment by tijoytom** [comment]
@wtgodbe Can check if this test should be deleted?

**Comment by BruceForstall** [comment]
> If it is the case, this is a bad test that should be deleted.

Or fixed.

There are lots of other valid test cases in this test that should stay.

**Comment by jkotas** [comment]
> There are lots of other valid test cases

They are redundant with tests in corefx ...

**Comment by wtgodbe** [comment]
@jkotas can you point me towards the test in CoreFX that this duplicates?

**Comment by jkotas** [comment]
These are corefx test cases for Join:

https://github.com/dotnet/corefx/blob/feb58b21e57401169856ec0a4c221ec2460042c8/src/System.Runtime/tests/System/StringTests.cs#L1751
https://github.com/dotnet/corefx/blob/feb58b21e57401169856ec0a4c221ec2460042c8/src/System.Runtime/tests/System/StringTests.cs#L1788
https://github.com/dotnet/corefx/blob/feb58b21e57401169856ec0a4c221ec2460042c8/src/System.Runtime/tests/System/StringTests.cs#L1797
https://github.com/dotnet/corefx/blob/feb58b21e57401169856ec0a4c221ec2460042c8/src/System.Runtime/tests/System/StringTests.cs#L1809

The tests cases are not exact duplicates, but they provide equivalent coverage.

**Comment by tijoytom** [comment]
@wtgodbe Can this be closed now?

**Comment by wtgodbe** [comment]
I've just merged https://github.com/dotnet/coreclr/pull/12785 and kicked off a build, if this test passes on that build I'll close this.

**Comment by wtgodbe** [comment]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170713.03

Passing
