### ISSUE TITLE
JIT_Regression._JitBlue_GitHub_3449_GitHub_3449_GitHub_3449 fails in Helix on ARM

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#12493]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170626.03/workItem/JIT.Regression.XUnitWrapper/analysis/xunit/JIT_Regression._JitBlue_GitHub_3449_GitHub_3449_GitHub_3449_~2F_JitBlue_GitHub_3449_GitHub_3449_GitHub_3449_cmd

> Expected: 0x43e08b2a2c280291\nActual: 0x43e08b2a2c280290\r\nExpected: 100\r\nActual: -1

@russellhadley can you route this to the right person?

**Comment by BruceForstall** [comment]
This failure is because the test is checking for `PROCESSOR_ARCHITECTURE==ARM` when it really should be checking for "CLR compiled by VC++ or CLANG" So, running on ARM on Windows gives the "Windows" result, not the "Linux" result.

**Comment by BruceForstall** [comment]
Fixed with #12683
