### ISSUE TITLE
JIT_Methodical._tailcall_v4_hijacking_hijacking fails in Helix on ARM

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#12494]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170626.03/workItem/JIT.Methodical.XUnitWrapper/analysis/xunit/JIT_Methodical._tailcall_v4_hijacking_hijacking_~2F_tailcall_v4_hijacking_hijacking_cmd

> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object

@russellhadley can you route this to the right person?

**Comment by Jiayili1** [comment]
Failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170627.02/workItem/JIT.Methodical.XUnitWrapper/analysis/xunit/JIT_Methodical._tailcall_v4_hijacking_hijacking_~2F_tailcall_v4_hijacking_hijacking_cmd

**Comment by BruceForstall** [comment]
This test should be disabled on arm (see #6217).

It already is disabled for Linux in testsUnsupportedOnARM32.txt.

@wtgodbe How should it be disabled for Windows?

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/12717 should disable that test for ARM

**Comment by wtgodbe** [comment]
Will close this pending next Helix test run.
