### ISSUE TITLE
CoreConsole.exe doesn't work if you omit ".exe" when invoking from the command line

### ISSUE THREAD

**Issue by mellinoe** [dotnet/coreclr#1253]
NOTE: I'm not sure this is actually a bug or if it's just the nature of the host program. It's also very minor.

The issue is as follows: I have a CoreCLR exe named, for example, "GenFacades.exe", which I want to host using CoreConsole. I rename GenFacades.exe -> GenFacades.dll, and rename CoreConsole.exe to GenFacades.exe. If I invoke "GenFacades.exe" from the command line, everything works as expected. Running "GenFacades" seems to fail, although I haven't debugged why exactly.

**Comment by benpye** [comment]
I haven't looked into it too much but this seems to blame https://github.com/dotnet/coreclr/blob/master/src/coreclr/hosts/coreconsole/coreconsole.cpp#L598 . When invoking GenFacades without the exe extensions `argv[0]` will not have the extension, so the call to `wcsrchr` will return a null pointer, so the call to `wcscmp` will cause an access violation. Seems the solution would be to null check the return value of `wcsrchr`, if null the extension isn't in the `argv[0]` so we'd need to allocate a new string, length of the current string + 4, and then concatenate the value for argv[0] and ".dll". I can leave this up to you or I can send a PR tomorrow.
