### ISSUE TITLE
Allow ability to specify Windows subsystem (Hide Console Window)

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/coreclr#12548]
at the moment I'm using:
https://github.com/AvaloniaUI/Avalonia/wiki/Hide-console-window-for-self-contained-.NET-Core-application

as a workaround to patch the file.

However if I want to use a Linux build server I cant do this step. Can this be supported natively by the dotnet sdk?

**Comment by RussKeldorph** [comment]
I believe this is dotnet/cli#296.  Feel free to open this issue in that repo if you disagree with the earlier conclusion.
