### ISSUE TITLE
Expose LastThrownException on Thread Object

### ISSUE THREAD

**Issue by Alois-xx** [dotnet/coreclr#12567]
We are using since a long time a hack 

http://geekswithblogs.net/akraus1/archive/2010/07/04/140761.aspx

for our own tracing infrastructure. Every .NET Framework update seems to change the offset in the unmanaged thread object. It would be much better if the Last Thrown Exception would simply be exposed so we do not need to rely on such hacks. 
I have talked about that issue with Andrew Pardoe some years back but he suggested only to use Intellitrace or the profiling APIs. This is a non starter since we have dozens of processes and we do normally not know for which process we need to enable profiling/IntelliTrace. 
This is used a lot during automated testing and in the field to check if any exception did pass our code which does not show up in the logs which is pretty powerful.
If this gets through .NET Core I would also like to see this in the regular .NET Framework showing up.

**Comment by jkotas** [comment]
There has always been `AppDomain.FirstChanceException` event that you can use to cache the last thrown exception. Is there a reason why it does not work for you?

**Comment by Alois-xx** [comment]
The _FirstChanceException_ event is delivered by a thread pool thread which also has nowhere noted in which thread the exception was thrown. Up to now there is no way to associate the thread on which an exception was thrown with the information gained by using the _FirstChanceException_ event. 

What I really would like to have is in the _Thread_ object a _Thread.CurrentlyUnwindingException_ property which would enable do do custom things in finally blocks in the exception unwind case if this property is not null.

**Comment by jkotas** [comment]
> The FirstChanceException event is delivered by a thread pool thread 

That's not correct. It is delivered on the thread where the exception was thrown before any other processing starts.

> which would enable to do custom things in finally blocks 

What kind of custom things you would do in finally block? 

It does not work well with nesting. If you are in finally block and you see that there is current exception, you cannot be sure whether you are executing the finally block exceptionally or not.

>  Thread object a Thread.CurrentlyUnwindingException 

I know that the Thread object has all sort of state attached to it for historic reasons. It has proven to be problematic - thread object is accessible from other threads that can observe the thread-local state (and sometimes set it as well) and the implementation needs to worry about races with these external observers now. We prefer to expose thread-local state as static properties, unrelated to the Thread object. It is a secondary point - just affects where the API may live.

**Comment by Alois-xx** [comment]
The use case is for tracing. If you implement a tracer you can do it like this:

public struct Tracer : IDisposable
{
    [ThreadStatic]
    static Exception AlreadySeen = null;

    public Tracer(Type type, string method)
     { .. } 

     public void Dispose()
      {
             Exception unwinding = Thread.UnwindingException;
             if( unwinding != AlreadySeen && unwinding != null)
             {
                     AlreadySeen =unwinding;
                     Console.WriteLine("Method xxxx is left with Exception {0}", unwinding);
             }

      }
}

You can use this in a using block and get notified when you enable tracing for Func that you will notice
that the method has been left with an exception altough it was nowhere explicitely catched. 
This is very useful for regression and testing in general to find oddities in our code. 

way out. I was not thinking about FirstChanceException because we use this since .NET 4.0 and FirstChanceException was added to .NET 4.5. 

Indeed FirstChanceException looks like a good way around that ugly hack. The new approach even simplifies the code. This should do the trick:

```
    struct Tracer : IDisposable
    {
        [ThreadStatic]
        static Exception LastThrown = null;

        static Tracer()
        {
            AppDomain.CurrentDomain.FirstChanceException += CurrentDomain_FirstChanceException;
        }

        private static void CurrentDomain_FirstChanceException(object sender, System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs e)
        {
            LastThrown = e.Exception;
        }

        public void Dispose()
        {
            if( LastThrown != null )
            {
                Console.WriteLine($"Leaving with an exception: {LastThrown}");
                LastThrown = null;
            }
        }
    }


   static void Main(string[] args)
        {
            for (int i = 0; i < 5; i++)
            {
                try
                {
                    using (var t1 = new Tracer())
                    {
                        using (var t2 = new Tracer())
                        {
                            throw new InvalidCastException("hi");
                        }
                    }
                }
                catch (Exception ex)
                { }
            }
        }
```

**Comment by jkotas** [comment]
> FirstChanceException was added to .NET 4.5.

Nit: It was added to .NET 4.0.

**Comment by Alois-xx** [comment]
Ups sorry you are right. I got the impression it was recently added but it seems I have missed that one a long time. It seems this idea is so good that MS has a patent for it (https://www.google.de/patents/US20100287414)
