### ISSUE TITLE
x86 Server GC PreGrow write barrier does not work when heap is mapped to a low VA

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#12560]
A bug in the write barrier initialization handshake in the Server GC startup path results in `g_ephemeral_low` never getting bashed into the write barrier on startup on x86, which results in heap corruption when the managed heap ends up in virtual addresses below `0x0F0F0F0F` and card table writes are mistakenly omitted. The managed heap does not usually end up that low in the VA space, but it can when running in nonstandard environments.

This was introduced by https://github.com/dotnet/coreclr/commit/04d6bd105ade5f6189a15a6dbb59b082613429a1 - will have a PR out addressing this soon.

cc @jkotas @Maoni0 @gkhanna79 @sergiy-k

**Comment by leecow** [comment]
@swgillespie can you confirm that everything is covered and this can be closed?

**Comment by swgillespie** [comment]
Yep, with the merge of https://github.com/dotnet/coreclr/pull/12584 this can be closed.
