### ISSUE TITLE
Infinite loop calling instance method on struct in emitted code

### ISSUE THREAD

**Issue by andy-hanson** [dotnet/coreclr#12596]
```cs
using System;
using System.Reflection;
using System.Reflection.Emit;

static class Program
{
	static void Main()
	{
		var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(
			new AssemblyName("Test"),
			AssemblyBuilderAccess.RunAndCollect);
		var moduleBuilder = assemblyBuilder.DefineDynamicModule("Test");
		var typeBuilder = moduleBuilder.DefineType("Test");
		var methodBuilder = typeBuilder.DefineMethod(
			"Test",
			MethodAttributes.Public | MethodAttributes.Static,
			typeof(string), // Wrong type!
			new Type[] { });

		// IL for `return Dummy.Instance.Self();`
		var il = methodBuilder.GetILGenerator();
		il.Emit(OpCodes.Ldsfld, typeof(Dummy).GetField(nameof(Dummy.Instance)));
		il.Emit(OpCodes.Call, typeof(Dummy).GetMethod(nameof(Dummy.Self)));
		il.Emit(OpCodes.Ret);

		var type = typeBuilder.CreateType();
		type.GetMethod("Test").Invoke(null, null);
		throw new Exception("Should reach here!");
	}
}

public struct Dummy
{
	public static readonly Dummy Instance = new Dummy();
	int someField; // No repro without this
	public Dummy Self() => this;
}
```

Put a breakpoint on `type.GetMethod("Test").Invoke(null, null);` and run.
Then try stepping (in or next, doesn't matter) -- there is apparently an infinite loop in the generated code. I would also expect to get an early error due to the wrong return type. (Filling in the correct return type `Dummy` changes nothing.)

It's also possible to make the program exit with no exception. Change `Self` to `public Dummy Self(Dummy other) => this;`, and put `il.Emit(OpCodes.Dup);` before the `OpCodes.Call`. Instead of an infinite loop, the program will exit with code 0.

My `dotnet --info`:
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.1
 OS Platform: Linux
 RID:         linuxmint.18.1-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by AndyAyersMS** [comment]
I can repro this on Ubuntu 14.04 with preview2. When running a debug build the jit will get stuck in an infinite loop in `LinearScan::BuildRefPositionsForNode`. Not sure exactly why; dropping in a checked jit causes it to crash much earlier during importation. On windows (both debug & release) the app will crash in the jit, and it will also crash in release on Ubuntu.

The jit takes some precautions to avoid getting into trouble with invalid IL, but it doesn't catch all cases. 
We can look into what it might take for the jit to detect and fail on a case like this, if it is important. How did you end up finding this?

**Comment by andy-hanson** [comment]
I didn't realize this IL was invalid, once the return type is fixed -- and fixing the return type doesn't change the behavior.

**Comment by AndyAyersMS** [comment]
Sorry, I should have been a bit less cryptic in my reply.

Instance methods called on structs -- like the `Self` in your example -- expect you to pass the *address* of the struct as `this`. So you should use `ldsflda` in your IL instead of `ldsfld`.

**Comment by andy-hanson** [comment]
Thanks!

**Comment by AndyAyersMS** [comment]
Are you ok with closing this, or do you think we need to work on hardening the jit to reject this kind of IL?

**Comment by andy-hanson** [comment]
When I originally ran into this issue, it was in this case:

> It's also possible to make the program exit with no exception. Change Self to public Dummy Self(Dummy other) => this;, and put il.Emit(OpCodes.Dup); before the OpCodes.Call. Instead of an infinite loop, the program will exit with code 0.

My expectation was that IL was like Java bytecode, and must be validated for security reasons. This seems to hint at an ability to get arbitrary machine code to execute.

Is there perhaps a separate tool I could use to validate IL before executing it?

**Comment by AndyAyersMS** [comment]
CoreCLR always runs in full trust, so no explicit IL verification/validation is done. The jit does some sanity checking but (as you can tell) doesn't catch everything.

There is a project over in the CoreRT repo to build a standalone verifier. Not sure how far along it is...

**Comment by andy-hanson** [comment]
OK, I'm closing this issue since this is a programmer error resulting in undefined behavior. Let me know if you ever find a link to the standalone verifier. Thanks!

**Comment by AndyAyersMS** [comment]
Here's a link to the [IL Verifier](https://github.com/dotnet/corert/tree/master/src/ILVerify) Project.
