### ISSUE TITLE
VirtualAlloc does not respect MEM_RESET

### ISSUE THREAD

**Issue by kangaroo** [dotnet/coreclr#1259]
Branching off:

https://github.com/dotnet/coreclr/issues/1236#issuecomment-122030108

It seems the GC uses MEM_RESET to indicate to the kernel that things can be physically removed from the commit charge.  PAL currently does nothing with this flag.  madvise() is probably the right thing.

**Comment by Maoni0** [comment]
@janvorli could you please take a look see if we can add this support?

**Comment by janvorli** [comment]
@Maoni0 sure, I already had it on my private list of stuff to work on in the future. 1.2.0 timeframe sounds good to me. I think that it should be quite straightforward - as @kangaroo has mentioned, madvise should be the tool we use for this purpose.

**Comment by Maoni0** [comment]
great! thanks Jan.

**Comment by gkhanna79** [comment]
@janvorli Is this for 2.0?

**Comment by janvorli** [comment]
I have it implemented, but I didn't send a PR yet since it seems that testing that it has the expected effect on the memory would be complex and we don't have any existing tests for that. Maybe we should put it in and fully test it after the feature complete date.

**Comment by janvorli** [comment]
Fixed by #10939
