### ISSUE TITLE
Calling SetWindowsHookEx via P/Invoke does not work as expected

### ISSUE THREAD

**Issue by devunt** [dotnet/coreclr#12594]
Calling SetWindowsHookEx with WH_KEYBOARD_LL via P/Invoke on Windows does not work as expected, instead it makes application hang on first keyboard input and also supresses all keyboard input globally until application exit.

```c#
const int WH_KEYBOARD_LL = 13;
delegate IntPtr LowLevelKeyBoardProc(int nCode, IntPtr wParam, IntPtr lParam);

[DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
static extern IntPtr SetWindowsHookEx(int idHook, LowLevelKeyBoardProc lpfn, IntPtr hMod, uint dwThreadId)

[DllImport("kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
static extern IntPtr GetModuleHandle(string lpModuleName);

static IntPtr HookProc(int nCode, IntPtr wParam, IntPtr lParam)
{
    // never called
}

static void Main(string[] args)
{
    using (var currentProcess = Process.GetCurrentProcess())
    using (var currentModule = currentProcess.MainModule)
    {
        var currentModuleHandle = GetModuleHandle(currentModule.ModuleName);
        SetWindowsHookEx(WH_KEYBOARD_LL, HookProc, currentModuleHandle, 0);
    }
}
```

This happends because a standard dotnet core application does not have a message loop, which is needed for low level hooks to work properly.

**Comment by stephentoub** [comment]
> This happends because a standard dotnet core application does not have a message loop, which is needed for low level hooks to work properly.

Neither does a simple C/C++ application by default.  If you want a message loop, you need to add one, e.g.
https://blogs.msdn.microsoft.com/toub/2006/05/03/low-level-keyboard-hook-in-c/

(Separately, when you pass a delegate to native code and that delegate might be called back to after the synchronous call returns, you need to ensure that the delegate won't be garbage collected while it might still be invoked by the native callee.  As currently written, passing HookProc to SetWindowsHookEx will actually expand into the equivalent of `new LowLevelKeyboardProc(HookProc)`, such that the delegate can be collected once SetWindowsHookEx returns... you need to keep that delegate rooted by explicitly creating it and, for example, keeping it rooted in a static.)

**Comment by devunt** [comment]
As `Application` lives in `System.Windows.Forms`, which can only be refered in .net framework based application, do we have other ways to initialize basic message loop in .net core application besides of implementing it by hands using `GetMessage` and other functions?

**Comment by stephentoub** [comment]
To my knowledge there isn't such a method built into .NET Core.  You'd need to either write the loop yourself, copy it from a variety of different examples on the web, or use one that someone else has provided in a library.

**Comment by poizan42** [comment]
Another note here, hMod should be the module (i.e. library) containing the function to call. However the function you give it is a trampoline to jit'ed code that is generated on the fly.

Now the low-level hooks such as WH_KEYBOARD_LL are special if you note the Remarks section:

> An application installs the hook procedure by specifying the WH_KEYBOARD_LL hook type and a pointer to the hook procedure in a call to the SetWindowsHookEx function.

> This hook is called in the context of the thread that installed it. The call is made by sending a message to the thread that installed the hook. Therefore, the thread that installed the hook must have a message loop.

Of course the documentation for SetWindowsHookEx does not specify what to do with the hMod parameter in this case, but presumably you can just set it to NULL.

**Comment by TheLastRar** [comment]
The hMod parameter can be set to NULL if you are running on an Vista or newer as long as OS itself is up-to-date. (http://stackoverflow.com/a/17898148)

You would also need to return the value from CallNextHookEx if you don't want to block keyboard inputs to the target window. This is in addition to the requirement of needing a message loop and keeping a reference to your callback delegate.
