### ISSUE TITLE
Tiered Jitting: Implement Opt-out configuration

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#12609]
We hope that tiered jitting is a useful performance improvement for nearly all projects and it will keep improving over time, but there is likely to be a small set of projects that want to disable it for various reasons. We need to determine and implement appropriate configuration switches to accomplish this. There is some initial discussion of the topic in #4331. Also likely to be useful is prior art such as configuration for ryujit when it was first introduced or GC configuration.

This item does not include other more sophisticated types of configuration such as configuring the JIT to replace the default tiering policy with a custom policy. Discussion for that is probably best left in #4331 for general brainstorming or opening a new work item to track a specific goal in that space. #4331 had several suggestions for useful extensions of the work.

**Comment by kouvel** [comment]
Closing based on #17807, please reopen if there are other things that should be covered by this issue

**Comment by kouvel** [comment]
Adding a method-level opt-out is covered by https://github.com/dotnet/corefx/issues/32235

**Comment by noahfalk** [comment]
It might be worth mentioning that the AggresiveOptimization happens to align right now with a method level opt-out for tiering, but developers shouldn't assume it will always mean that in the future. For example if we added a new faster Tier2 and the only way to reach it was to first profile Tier1 then we'd probably want AggressiveOptimization methods to move Tier1 -> Tier2 when possible.
