### ISSUE TITLE
decimal.Remainder correctness issues

### ISSUE THREAD

**Issue by pentp** [dotnet/coreclr#12605]
[Remainder calculation for decimal](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Decimal.cs#L758) uses `NearNegativeZero/NearPositiveZero` constants that claim to be *Constant representing the negative number that is the closest possible Decimal value to -0m/+0m*. The actual constant values have scale 27 (instead of 28) so they are 10 times larger than intended.

That entire condition looks odd, I couldn't find any tests to reproduce such values (it looks like `FCallDivide` refuses to calculate such imprecise results and throws `OverflowException`).

Are these values and/or logic incorrect? Maybe there are some tests for Desktop that cover these cases?

**Comment by pentp** [comment]
So I finally found test cases for this bug while writing [new tests](https://github.com/dotnet/corefx/pull/30291) for https://github.com/dotnet/corert/pull/5926.
`5.94499443m % 0.0000000000000000000000000007m = 0.0000000000000000000000000005m` but returns `0.0000000000000000000000000002m` because the constants have scale 27.

The current `Decimal.Remainder` implementation does several intermediate calculations that may round or overflow:
- `decimal.MaxValue % 0.1m` overflows.
- `5 % 0.0000000000000000000000000003m = 0.0000000000000000000000000002m` but returns `0.0000000000000000000000000001m` because of rounding.
- `decimal.MaxValue % 7.081881059m = 3.702941036m` but returns `4.081881059m` because of rounding.
- `decimal.MaxValue % 2004094637636.6280382536104438m = 1980741879937.1051521151154118m` but returns `1980741879937m` because of rounding.

I propose writing a new remainder calculation (based on CoreRT's `VarDecDiv`) as part of #18249, but after CoreCLR and CoreRT decimals are shared because the CoreFX tests are shared.

Are there any compatibility concerns with returning more precise results or not throwing overflow exceptions anymore?

**Comment by jkotas** [comment]
> Are there any compatibility concerns with returning more precise results or not throwing overflow exceptions anymore?

This is fine. We are not worried about fixing a clear correctness bugs like these in .NET Core. We are not aiming for bug-for-bug compatibility between .NET Core releases.
