### ISSUE TITLE
Tiered jitting: Design/Implement appropriate diagnostics

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#12612]
There are two aspects of this work:
1) We have pre-existing diagnostic APIs/tools that need to keep working properly in spite of tiered jitting. For example SOS, ETW events, COMPLUS logging, stress logging, ICorDebug and ICorProfiler APIs. ICorDebug and ICorProfiler are sizable and are already called out in separate work items, but the remainder are lumped here for now. We either need to confirm they are working as expected or fix any issues that tiered jitting caused if not.

2) We have new diagnostic scenarios specifically to diagnose issues relating to tiered jitting. In this case we need to understand the state of the code versions in the runtime. SOS already has some ReJIT related functionality that could be enhanced. New or adjusted ETW events may be necessary. New COMPLUS logging/stress logging messages would be useful. Questions that would be desirable for diagnostics to answer:
 - Is tiered jitting enabled?
 - Given code at a certain address, what jit settings were used to compile it?
 - For a particular MethodDesc, what code versions exist? If those versions have been jitted, where is the code?
 - In a perf trace, how much time did the runtime spend jitting each version of the code?
 - In a perf trace, which CPU samples are attributable to which versions of the code?

This is a bucket of likely many small items, please sub-divide as needed and make new work items.

**Comment by noahfalk** [comment]
ICorProfiler work is tracked in #12610, plus what was already done in #12193. 
ICorDebug work is tracked in #12617.

**Comment by mattwarren** [comment]
@noahfalk 

`<shameless plug>` I liked the tiered compilation feature so much that I wrote a blog post about it [A look at the internals of 'Tiered JIT Compilation' in .NET Core](http://mattwarren.org/2017/12/15/How-does-.NET-JIT-a-method-and-Tiered-Compilation/#tiered-compilation). If I've got anything horribly wrong, please let me know and I'll update the post (I know it's 'work-in-progress', so things might change over time) `</shameless plug>`

**Comment by noahfalk** [comment]
Hi @mattwarren! I'm flattered for the feature we've been working on to get such a nice blog post and very glad you are digging the work. Thanks! I sent you an email if you wanted to chat more technical details without taking this issue too far off topic ; )

**Comment by lt72** [comment]
One more issue to deal with, hopefully in 2.1 timeframe: #16506

**Comment by noahfalk** [comment]
#19133 - Add an explicit ETW event to indicate tiering is on/off

**Comment by noahfalk** [comment]
https://github.com/Microsoft/perfview/issues/717 - Ran into this while trying to do the MusicStore tiered compilation PerfView demo. It is sadly easy to hit on async heavy apps due to the large number of TPL events.

**Comment by kouvel** [comment]
CoreCLR changes that address all of the points above have already been merged, only the PerfView changes are remaining: https://github.com/microsoft/perfview/pull/939. I'll consider that PR as the completion of the work in a different repo, that this issue for this repo is complete, and the PR above can be tracked instead.
