### ISSUE TITLE
Does this repo access to NETFX_CORE functions when the project is built on android from unity

### ISSUE THREAD

**Issue by akilaVis** [dotnet/coreclr#12638]
Hi and thank you for this code, 
I have created a class library project (UWP) and link it with unity to generate a dll file, I could build the project for WSA from unity but can’t build it on android because I couldn’t access to the functions of NETFX_CORE in the class library (UWP) from unity, I want to ask you if this repo can access to NETFX_CORE functions when the project is built on android platform from unity?
Thank you for your help
Best regards

**Comment by RussKeldorph** [comment]
I don't think this is the right forum to ask this question, which probably explains the lack of response.  @karelz Can you suggest a better place?
