### ISSUE TITLE
ProcessorCount doesn't take into account cpu cfs limit from cgroup

### ISSUE THREAD

**Issue by gboucher90** [dotnet/coreclr#12630]
Hello,

It seems cgroup cpu share limit is not taken into account.

I'm running a .Net Core app into Mesos on CentOS 7. Wether I allocate 1 to 10 CPUs, Environment.ProcessorCount always returns the actual number of processor (24).

Then the ThreadPool doesn't really scale properly. In particular I encountered deadlocks.

This issue was also present in Java and was fixed last year: 
https://bugs.openjdk.java.net/browse/JDK-8140793
https://bugs.openjdk.java.net/browse/JDK-8170888

The only related issue I could find is https://github.com/dotnet/coreclr/issues/10690 which fixes this problem when cpuset is used.

It seems memory limit is correctly implemented via cgroup:
https://github.com/dotnet/coreclr/blob/master/src/pal/src/misc/cgroup.cpp

**Comment by pierrecdn** [comment]
As a side remark: it would be more convenient to handle the cpushare case because its more commonly used, even if the cpuset case is also very interesting because probably in place in most of the high performance use-cases.

**Comment by gboucher90** [comment]
https://github.com/dotnet/coreclr/pull/12794

**Comment by gboucher90** [comment]
Fixed by https://github.com/dotnet/coreclr/commit/df214e67d3cbccb42d2733f4cbe8097a378a731a
