### ISSUE TITLE
Could not resolve CoreCLR path - Raspberry Pi

### ISSUE THREAD

**Issue by techyian** [dotnet/coreclr#12645]
Hi,

I'm trying to run my application under .NET Core on a Raspberry Pi 2. The Pi is running Ubuntu Mate 16.04.2 LTS.

I've built my application under Windows using .NET Core SDK `2.1.0-preview1-006632` using `dotnet publish -r linux-arm` and this builds successfully. All publish files are present, however when I try to run the self-contained file, I receive the following error:

```Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1```

I have seen previous issues raised on StackOverflow/GitHub regarding this issue but that was last year and I hoped the issue may have been resolved. My understanding is that currently the SDK is not available for linux arm and this is why a self-contained application is made when running `dotnet publish`?

To confirm, I've followed the instructions found [here](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md), and all dependencies are installed.

Does anyone have any idea what may be causing this?

Thanks :)

**Comment by parjong** [comment]
When I build and publish a self-contained application on Linux (using .NET Core SDK ``2.0.0-preview2-006419``), it works well on Raspberry Pi 3  (running Raspbian).

Could you run your application after setting COREHOST_TRACE  as 1?

**Comment by techyian** [comment]
Can confirm a HelloWorld app created using `dotnet console new` works correctly when publishing for linux-arm. However the project I'm having issues with has 3rd party project dependencies. Going to do some more digging and see if I can figure out what's going on.

**Comment by techyian** [comment]
It seems to be the following causing the problem in the csproj file:

`<RuntimeIdentifiers>linux-arm</RuntimeIdentifiers>`

The csproj file generated by `dotnet console new` does not include this, but running `dotnet publish -r linux-arm` still works without issue. Removing this from my csproj file fixes the problem.

The instructions found [here](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md) suggest adding this to the csproj file - are these instructions now outdated?

**Comment by parjong** [comment]
I'm not sure, but it seems that [cli repo](https://github.com/dotnet/cli) is better fit for this kind of questions.

**Comment by jkotas** [comment]
cc @Petermarcu since he has been maintaining the instructions at https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

**Comment by Petermarcu** [comment]
@techyian, that entry in the csproj was made optional recently but it shouldn't have different effects than specifying `-r linux-arm` on the command line. That command line effectively just sets that property. @eerhardt for when you get a chance to look at that. I'm happy to remove that line from the instructions as it is optional now.

**Comment by janvorli** [comment]
Issue moved to [dotnet/cli #7248](https://github.com/dotnet/cli/issues/7248) via [**ZenHub**](https://www.zenhub.com/)
