### ISSUE TITLE
Add ability to specify APPDOMAIN_* and STARTUP_* flag values in Unix hosting APIs

### ISSUE THREAD

**Issue by lstratman** [dotnet/coreclr#1265]
First off, I am extremely appreciative of the work that was put in for coreclr_initialize and coreclr_create_delegate:  it has DRAMATICALLY simplified the amount of code that I've needed to write to spin up the CLR in my process under Linux.  There is one last piece that I, and I imagine others, need:  the ability to specify the APPDOMAIN_* flag values used in the second parameter of ICLRRuntimeHost2::CreateAppDomainWithManager().  Specifically, I need the ability to set the APPDOMAIN_ENABLE_ASSEMBLY_LOADFILE flag; if there is another way that I should be setting this flag outside of CreateAppDomainWithManager(), please let me know.

**Comment by janvorli** [comment]
@lstratman It looks like there is no other way to set this flag. And I agree that it makes sense to add the flags to the coreclr_initialize interface.
@jkotas, do you agree?

**Comment by jkotas** [comment]
I agree in general about the need to pass some of the flags - e.g. it should be definitely possible to pass `STARTUP_SERVER_GC` flag to select server GC via the hosting APIs. 

`APPDOMAIN_ENABLE_ASSEMBLY_LOADFILE` flag is questionable though. It enables untested experimental implementation of `Assembly.LoadFile`. `Assembly.LoadFile` is not part of .NET Core supported surface, and I believe that this experimental implementation does not quite work. `System.Runtime.AssemblyLoadContext` is the .NET Core replacement for `Assembly.LoadFile` that we stand behind.

**Comment by lstratman** [comment]
@jkotas Thank you for the information, I'll start using that instead of `Assembly.LoadFile`.

**Comment by kouvel** [comment]
Added GC startup flags in https://github.com/dotnet/coreclr/pull/2042

**Comment by kouvel** [comment]
https://github.com/dotnet/coreclr/commit/1d4dd203be223f629c57d7ac12bcaee4977e7a03
