### ISSUE TITLE
Replacement/Alternative for MSCorPE API (ICeeFileGen) on CoreCLR

### ISSUE THREAD

**Issue by mmayr-at** [dotnet/coreclr#12664]
Is there any official replacement or alternative for the MSCorPE API on CoreCLR? I use the `ICeeFileGen` interface on desktop CLR to create PE files with rewritten IL code/metadata, see https://github.com/dotnet/coreclr/issues/11173#issuecomment-297241911 for an example. The attached mscorlib_instrumented.zip was created with `ICeeFileGen`.

**Comment by jkotas** [comment]
It is replace by managed APIs in System.Reflection.Metadata. Look for PEBuilder:  https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/ref/System.Reflection.Metadata.cs#L3159

cc @tmat

**Comment by mmayr-at** [comment]
Thx for that information. But I think using the managed API from native code, especially in combination with the profiling API, would not be easy at all, would it? 

In addition the managed API would add an additional (managed) dependency to my application. Can I take it that the `Microsoft.Reflection.Metadata` is always present on CoreCLR?

The MSCorPE source still exists in CoreCLR, but is not public anymore. Do you have any plans to remove that completely? Otherwise I could create a custom library based on that source and and ship it with my application.

**Comment by jkotas** [comment]
We plan to focus on managed APIs for emitting managed assemblies going forward. For example, the APIs to emit portable PDBs are managed only. There is no unmanaged equivalent.

`System.Reflection.Metadata` is part of the shared .NET runtime today. If you use it in your app, you will have logical dependency on the nuget package. You just do not have to carry the physical copy with you if you publish the app for shared .NET runtime.

We do not have plans to maintain `ICeeFileGen` as stable public API in CoreCLR. You can take what is there today and do anything compatible with license with it.

**Comment by mmayr-at** [comment]
Thanks for clarification. Maybe I'll give the managed API a try.
