### ISSUE TITLE
Native code debugging

### ISSUE THREAD

**Issue by axefrog** [dotnet/coreclr#1267]
Is there anything about CoreCLR in particular that I should understand which would help answer a current issue of mine relating to the fact that VS2015 doesn't seem to support native code debugging? I'm building some sample projects with SharpDX, the newest version of which works in CoreCLR. In the past I was always able to get proper, helpful debug information from the native D3D objects that SharpDX calls via interop, if I enabled "native code debugging" for my project. If native code debugging is not available for CoreCLR projects, does this mean that the old csproj setup is actually here to stay and that I've been mistaken that it'll become a legacy thing in the future?

**Comment by victorhurdugaci** [comment]
See my answer here: http://stackoverflow.com/a/31603762/149064

**Comment by karelz** [comment]
Looks answered
