### ISSUE TITLE
UriFormatException thrown for valid *nix URI's

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/coreclr#1268]
`new Uri("/home/nate/somefile.txt")` throws. Although this is an invalid URI on Windows, it is valid on OS X and Linux.

>    System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)

This may belong in [CoreFX](https://github.com/dotnet/corefx) instead. If so, I'll re-submit there.

**Comment by am11** [comment]
Related https://github.com/dotnet/corefx/issues/1745.

**Comment by natemcmaster** [comment]
Dup.
