### ISSUE TITLE
Cannot post-mortem debugging core file which was generated by gcore

### ISSUE THREAD

**Issue by micli** [dotnet/coreclr#12709]
I have a simple .NET Core console app for this testing:
using System;
using System.Diagnostics;
`namespace DumpMe
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Please Dump Me!");
            for(int i = 0; i < 30; i++)
                Console.Write("=");
            Console.WriteLine("");
            int processId = Process.GetCurrentProcess().Id;
            Console.WriteLine("Current Process ID = {0}", processId);  
            Console.WriteLine("Press Enter to exit.");
            Console.ReadLine();
        }
    }
}`
I used dotnet run to launch a  DumpMe process. and then I opened another terminal to generate a core file by gcore like this:
`gcore -o DumpMe.core 28898 `
28898 is DumpMe process Id.
`
Missing separate debuginfo for /opt/dotnet/dotnet
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/da/ab9a3ec6dc6f4be68171b4f4a013fb8b431df0.debug
[New LWP 28906]
[New LWP 28905]
[New LWP 28904]
[New LWP 28903]
[New LWP 28902]
[New LWP 28901]
[New LWP 28900]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /opt/dotnet/host/fxr/2.0.0-preview2-25407-01/libhostfxr.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/9b/f6fff6ae5e15b1957347cb51153eb1273e688d.debug
Missing separate debuginfo for /opt/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25407-01/libhostpolicy.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/7e/e95287a8c900ad665e37977d9c79a0d117afc2.debug
Missing separate debuginfo for /opt/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25407-01/libcoreclr.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/d4/8422870231a60fec15d5fbd7c879768b65c587.debug
Missing separate debuginfo for /opt/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25407-01/libcoreclrtraceptprovider.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/25/0df9879e585eb87584a5e3237c21df0b89ddf1.debug
Missing separate debuginfo for /opt/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25407-01/libclrjit.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/40/a05cd7ebebc86c75bec84c9430e51fc753c3d5.debug
Missing separate debuginfo for /opt/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25407-01/System.Globalization.Native.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/77/deff841947369dd3dabec61b3bb5ffc9faef4b.debug
Missing separate debuginfo for /opt/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25407-01/System.Native.so
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/9c/0f38ce2fe533cca85d869ab81eb575df54ccd2.debug
0x00007fcbdd5e849d in read () from /lib64/libpthread.so.0
warning: target file /proc/28898/cmdline contained unexpected null characters
Saved corefile DumpMe.core.28898
`
Then I launch lldb 3.6 by loading core file like this:
`lldb -c DumpMe.core.28898`
But when I debug this core file, I got error message:
**The libcoreclr.so module is not loaded yet in the target process**
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lldb.embedded_interpreter
(lldb) target create --core "DumpMe.core.28898"
Core file '/home/micl/dotnet/DumpMe.core.28898' (x86_64) was loaded.
(lldb) plugin load /opt/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25407-01/libsosplugin.so
(lldb) clrstack
The libcoreclr.so module is not loaded yet in the target process`

**Comment by adityamandaleeka** [comment]
One problem I see is that you're not pointing lldb at the executable. Can you try `lldb -c DumpMe.core.28898 /path/to/dotnet`? In your case I guess the path is /opt/dotnet/dotnet based on the console output you pasted.

**Comment by micli** [comment]
@adityamandaleeka That works!
lldb -c DumpMe.core.28898 /usr/local/bin/dotnet 
I don't know that must specify target when beginning post-mortem debugging before.
