### ISSUE TITLE
[q] msvc assembler syntax

### ISSUE THREAD

**Issue by kangaroo** [dotnet/coreclr#1272]
So, while working on aarch64 there are a bunch of undefined macros.  I think I've reversed most of them, but there seems to be a msvc assembler syntax:

```
PROLOG_SAVE_REG_PAIR   fp, lr, #-32!
ldr     x4, [x0,#-8]!
str     x4, [sp,#-16]!
```

Near as I can tell, in the PROLOG_SAVE_REG_PAIR case, it allocates space on the stack, and then puts the registers into [sp].  I'm not entirely clear on the ! syntax though.  It seems that it means add #imm to reg and then perform operand?

Is this correct?

**Comment by BruceForstall** [comment]
It's standard AArch64 pre-indexed addressing, where the base register gets added and updated first, then the index happens. In the PROLOG_SAVE_REG_PAIR, the base register is implicitly sp.

**Comment by kangaroo** [comment]
@BruceForstall thanks for confirming, thats what I was assuming, but clang was having issues with it.  I'll dig in more.
