### ISSUE TITLE
[RyuJIT/ARM32][Question] status of JIT/superpmi/superpmicollect/superpmicollect.sh

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#12736]
When running with `COMPlus_AltJit=*`, following test is PASSED with `COMPlus_AltJit already exists: skipping SuperPMI collection and returning success` message.

Can we just skip and consider it PASSED ?

```
PASSED   - [6603][  10s]JIT/superpmi/superpmicollect/superpmicollect.sh
               BEGIN EXECUTION
               /home/dotnet_jenkins/workspace/hqueue/Run_coreclr_tests_Checked_ryujit_nyi_all/runtime/tests/Tests/coreoverlay/corerun superpmicollect.exe
               COMPlus_AltJit already exists: skipping SuperPMI collection and returning success
               Expected: 100
               Actual: 100
               END EXECUTION - PASSED
```

**Comment by BruceForstall** [comment]
@hqueue This is a limitation of the way the SuperPMI test works: the test itself sets COMPlus_AltJit, so if COMPlus_AltJit is already set, there is a kind of collision, and it can't do its job.

If you really want to test RyuJIT/arm32, you'll need to build it as the "main" JIT (don't define ALT_JIT in the build, and name it clrjit.dll), then run the test without setting COMPlus_AltJit.

I don't think it's necessary to do this for RyuJIT/arm32 yet. There are plenty of other bugs to work on first :-)

**Comment by hqueue** [comment]
@BruceForstall Thank you for the detailed explanation.
If so, I also think that it's not necessary now and let's leave it for future task until ryujit/arm32 can be default jit.

**Comment by RussKeldorph** [comment]
Assuming this is answered.  Reopen if not.
