### ISSUE TITLE
The culture / locale behavior for multi-language support varies between platforms and tools.

### ISSUE THREAD

**Issue by lemmaa** [dotnet/coreclr#12759]
I recently experienced a problem with some tests related to Culture / Locale support.
I have done some testing for multi-language support. The result is a different behavior depending on the platform and tools. 

* For unsupported cultures, the results for CLI and VS2017 are different on Windows 10 as well.
* `Ckb-IQ` and` ku-arab-IQ` are the same locale, which is recognized correctly on Windows 10, but different results on Linux and macOS.
* For `neutral`, the results of Windwos 10, Linux and macOS are different.

This can be a CoreFX category, but I have created an issue here because of the native implementation issues.

In addition, I need a way to add locale that is not currently supported in .NET Core. How can you solve this problem? (I create this issue as a separate one. https://github.com/dotnet/corefx/issues/22135 )

## Test 
You can get the test source code from https://github.com/lemmaa/dotnet-test/tree/master/CultureTest .
I used `netcoreap1.1` as TFM in `CultureTest.csproj` for Visual Studio 2017 test.

### Windows 10 (Command Prompt + dotnet CLI)

* Current code page : 437 (OEM - United states)

````
C:\dotnet\CultureTest>dotnet run
message neutral Hello (en)
message 'en-US' Hello (en)
message 'ku-TR' Hello (ku)
message 'ko-KR' Hello (ko) - ?????
message 'ckb-IQ' Hello (ku-arab)
message 'ku-arab-IQ' Hello (ku-arab)
message 'mai-IN' Hello
message 'sat-IN' Hello
message 'tu-IN' Hello
message 'zzz-ZZZ' Hello
message 'ja-JP' Hello (jp)

C:\dotnet\CultureTest>
````

### Windows 10 (Visual Studio 2017)

* Current code page : 437 (OEM - United states)

````
message neutral Hello (en)
message 'en-US' Hello (en)
message 'ku-TR' Hello (ku)
message 'ko-KR' Hello (ko) - ∞òêδàòφòÿ∞ä╕∞Üö
message 'ckb-IQ' Hello (ku-arab)
message 'ku-arab-IQ' Hello (ku-arab)
message 'mai-IN' Hello (en)
message 'sat-IN' Hello (en)
message 'tu-IN' Hello (en)
message 'zzz-ZZZ' Hello (en)
message 'ja-JP' Hello (jp)
````

### Linux-x64 (Ubuntu 16.04LTS)

* LANG=en_US

````
u2:sjlee:~/dotnet/CultureTest $ dotnet run
message neutral Hello (en)
message 'en-US' Hello (en)
message 'ku-TR' Hello (ku)
message 'ko-KR' Hello (ko) - 안녕하세요
message 'ckb-IQ' Hello
message 'ku-arab-IQ' Hello (ku)
message 'mai-IN' Hello
message 'sat-IN' Hello
message 'tu-IN' Hello
message 'zzz-ZZZ' Hello
message 'ja-JP' Hello (jp)
u2:sjlee:~/dotnet/CultureTest $
````

### Linux-arm32 (Ubuntu 14.04LTS Raspberry-Pi2)

* LANG=en_US

````
pi2home:sjlee:-/bin/Debug/netcoreapp2.0 $ /home/sjlee/coreoverlay/corerun -c /home/sjlee/coreoverlay CultureTest.dll
message neutral Hello (en)
message 'en-US' Hello (en)
message 'ku-TR' Hello (ku)
message 'ko-KR' Hello (ko) - 안녕하세요
message 'ckb-IQ' Hello
message 'ku-arab-IQ' Hello (ku)
message 'mai-IN' Hello
message 'sat-IN' Hello
message 'tu-IN' Hello
message 'zzz-ZZZ' Hello
message 'ja-JP' Hello (jp)
pi2home:sjlee:-/bin/Debug/netcoreapp2.0 $ 
````

### macOS Sierra version 10.12.5

* LANG=en_US

````
europa:sjlee:~/dotnet/CultureTest $ dotnet run
message neutral Hello
message 'en-US' Hello (en)
message 'ku-TR' Hello (ku)
message 'ko-KR' Hello (ko) - 안녕하세요
message 'ckb-IQ' Hello
message 'ku-arab-IQ' Hello (ku-arab)
message 'mai-IN' Hello
message 'sat-IN' Hello
message 'tu-IN' Hello
message 'zzz-ZZZ' Hello
message 'ja-JP' Hello (jp)
europa:sjlee:~/dotnet/CultureTest $
````

**Comment by tarekgh** [comment]
net core read the globalization data from the OS. we on't carry any data. on Windows we use Windows Win32 APIs to get the data. Starting Windows 10, Windows is using CLDR data with some small exceptions which differ than CLDR. on OSX/Linux we use ICU version installed on the system. this is by design to have parity with the underlying OS. if you want to ask for any data change, you can request the change from the CLDR which eventually will be used by most of the platforms. If you have specific issue for Windows, you can report this issue through Windows insider reporting and ask to get this fixed.
