### ISSUE TITLE
CoreCLR failed with error c4596 when build in conformance mode (/permissive-)

### ISSUE THREAD

**Issue by xiangfan-ms** [dotnet/coreclr#12799]
It is similar to this issue: https://github.com/dotnet/coreclr/issues/10915

In revision https://github.com/dotnet/coreclr/commit/0ce4fab8647ac3fbc200c27adfcf31aaae0f660b, the following function is added:

coreclr\src\src\jit\codegenlinear.h
    void CodeGen::genConsumeArgSplitStruct(GenTreePutArgSplit* putArgNode);

It should be:
    void genConsumeArgSplitStruct(GenTreePutArgSplit* putArgNode);

**Comment by xiangfan-ms** [comment]
@hseok-oh

**Comment by PhoebeHui** [comment]
More similar issue found:

In revision https://github.com/dotnet/coreclr/commit/6636cf82ba78f77c4beec4f27769725b675e6858 
The following function is added:
 static  void QCALLTYPE AssemblyNative::GetForwardedType(QCall::AssemblyHandle pAssembly, mdToken mdtExternalType, QCall::ObjectHandleOnStack retType);  

It should be:
static  void QCALLTYPE GetForwardedType(QCall::AssemblyHandle pAssembly, mdToken mdtExternalType, QCall::ObjectHandleOnStack retType);

**Comment by xiangfan-ms** [comment]
@AtsushiKan

**Comment by AtsushiKan** [comment]
This is a static method - what difference does it make whether it's global or a member of a class?

**Comment by xiangfan-ms** [comment]
The issue is the extra qualification:

struct S {
	static void S::f1();
	void S::f2();
};

'S::' is not allowed on a member function no matter whether it is static or not.

**Comment by sandreenko** [comment]
Is not it fixed by #13104?

**Comment by jkotas** [comment]
Yes, it is.
