### ISSUE TITLE
Consider providing a means to programatically re-initialize static classes.

### ISSUE THREAD

**Issue by Korporal** [dotnet/coreclr#12826]
Would it be feasible to add a static method to (say) the AppDomain class called "ReinitStatic" which accepts a Type argument? The method would restore a static class's fields to their initial state (as if the class were being accessed for the very first time).

This would be extremely useful for writing unit tests for static classes, currently there is no way and I have created a public "Reset" method for this purpose on some complicated static classes that we use a lot.

For example we have a pretty complex configuration class that does more than ConfigurationManager (which itself is static) and without the "Reset" method it would be very hard to write lots of tests for the various methods in the class. The reset allows every test to safely assume the static class is being accessed for the first time so that behavior is guaranteed to be independent of any prior tests.

I don't know if this is a "core" suggestion or not, but naturally it's so low level that it would be framework independent.

Thx

**Comment by kskjer** [comment]
Wouldn't it be easier to make your configuration class instantiable, and then have the static API be a proxy to a singleton instance stored as a private static member on that class? (Or it could be public, so clients could use it directly and you wouldn't have to make a static variant of the API.) That way you can just new up your class every time you need to test it.

**Comment by RussKeldorph** [comment]
@janvorli This doesn't feel like codegen.  Was that a mis-label?  VM or TypeSystem maybe?

**Comment by janvorli** [comment]
@RussKeldorph I am sorry, that was a mis-labeling.

**Comment by jkotas** [comment]
> The method would restore a static class's fields to their initial state

If these fields contain pointers to unmanaged resources, reainitializing them will cause leaks, crashes or hangs. This methods would be pretty dangerous to use on arbitrary types. Not a a good candidate for a public framework method.

I agree with @kskjer suggestion to use instantiable configuration class in situations like these. It is a much cleaner solution.
