### ISSUE TITLE
Dead links on wiki

### ISSUE THREAD

**Issue by svick** [dotnet/coreclr#1284]
[The Wiki page](https://github.com/dotnet/coreclr/wiki) contains several dead links. Specifically, both ".NET Core contributor info" links and also the "Build the repository" link are 404.

@richlander, you seem to be maintaining that page. Could you, or someone else with the proper rights, have a look at this? Thanks.

**Comment by adityamandaleeka** [comment]
I've fixed those broken links. It looks like they weren't updated after subdirectories were added under Documentation in [this commit](https://github.com/dotnet/coreclr/commit/8d3936bff7ae46a5a964b15b5f0bc3eb8d4e32db).

Thanks for pointing this out.
