### ISSUE TITLE
Need a SynchronizationContext.WaitHelper that *never* pumps messages

### ISSUE THREAD

**Issue by AArnott** [dotnet/coreclr#12846]
On Windows, we define a non-pumping SynchronizationContext for guarding against reentrancy at inopportune times. We do this by overriding the `Wait` method and [calling `WaitForMultipleObjects` directly](https://github.com/Microsoft/vs-threading/blob/87f655fb583fb0d3360ca723902a8bd1dd709ea4/src/Microsoft.VisualStudio.Threading/NoMessagePumpSyncContext.cs#L65).

As I consider exposing this type to our .NET Standard 2.0 build of the library (rather than just desktop-facing builds), I need a cross platform equivalent for this.

The [`SynchronizationContext.WaitHelper`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.synchronizationcontext.waithelper?view=netstandard-2.0) method might be good, except that is exactly the default behavior, and when invoked from an STA thread it pumps messages. Drilling into the CoreCLR code to see how it works in a xplat way so I could copy it modulo message pumping, I find it is surprisingly complex and several layers deep.

Is there some supported way for me to get at what I need, or should I just look up the mac and linux equivalents to `WaitForMultipleObjects` and P/Invoke into them the same way I do for Windows?

**Comment by jkotas** [comment]
There is no message pumping on non-Windows. Why do you need to do anything special on non-Windows?

> P/Invoke into them the same way I do for Windows?

I do not think you would be able to do that. WaitForMultipleObjects is internal implementation detail on non-Windows. It is not exported from libcoreclr.so.

**Comment by AArnott** [comment]
> There is no message pumping on non-Windows.

Thanks, @jkotas. That's all I need to know then. I can do a runtime OS check and call `WaitForMultipleObjects` on Windows and `WaitHelper` on other platforms.
