### ISSUE TITLE
[RyuJIT/ARM32] Assertion failed '!"Incompatible types for gtNewTempAssign"'

### ISSUE THREAD

**Issue by sjsinju** [dotnet/coreclr#12849]
Below tests were failed with checked build.
```
Assertion failed '!"Incompatible types for gtNewTempAssign"'
File: /opt/code/github/hqueue/coreclr/src/jit/gentree.cpp Line: 13703
```
```
JIT/jit64/hfa/main/testE/hfa_nd2E_d/hfa_nd2E_d.cmd
JIT/jit64/hfa/main/testE/hfa_nd2E_r/hfa_nd2E_r.cmd
JIT/jit64/hfa/main/testE/hfa_nf2E_d/hfa_nf2E_d.cmd
JIT/jit64/hfa/main/testE/hfa_nf2E_r/hfa_nf2E_r.cmd
JIT/jit64/hfa/main/testE/hfa_sd2E_d/hfa_sd2E_d.cmd
JIT/jit64/hfa/main/testE/hfa_sd2E_r/hfa_sd2E_r.cmd
JIT/jit64/hfa/main/testE/hfa_sf2E_d/hfa_sf2E_d.cmd
JIT/jit64/hfa/main/testE/hfa_sf2E_r/hfa_sf2E_r.cmd
```

**Comment by jashook** [comment]
Still failing for me.

**Comment by jashook** [comment]
This hits on Legacy Backend too.

**Comment by hseok-oh** [comment]
It is due to #12855 
cc/ @BruceForstall

**Comment by BruceForstall** [comment]
I reverted my change: https://github.com/dotnet/coreclr/pull/12871. Does this fix it? (I'll check myself soon)

**Comment by hseok-oh** [comment]
@BruceForstall BTW, is it right that one-field float(or double) struct is set as HFA? I think fgMorphArg is implemented based on the assumption that HFA struct is always multireg struct.

**Comment by BruceForstall** [comment]
@hseok-oh I'm not sure right now. There has been a lot of change in the last few years related to multi-reg arguments and return values -- to handle amd64 Linux and arm64 and x86 ABI -- but unfortunately those changes weren't made with any arm32 testing, so I think the previously existing model related to arm32 HFA is somewhat broken, as we can see by all the various HFA-related issues that have been investigated recently.

**Comment by hqueue** [comment]
Update with recent commit 9b0906b652c717abecfb8b5358023d0e24cb71f5.


For legacy backend, all assertions are gone.

For ryujit/arm32, 4 passed and 4 failed with known assertion (#11783).
```
PASSED   - [   0][   9s]JIT/jit64/hfa/main/testE/hfa_nd2E_d/hfa_nd2E_d.sh
PASSED   - [   1][   8s]JIT/jit64/hfa/main/testE/hfa_nd2E_r/hfa_nd2E_r.sh
PASSED   - [   4][   9s]JIT/jit64/hfa/main/testE/hfa_sd2E_d/hfa_sd2E_d.sh
PASSED   - [   5][   8s]JIT/jit64/hfa/main/testE/hfa_sd2E_r/hfa_sd2E_r.sh
```

```
FAILED   - [   2][   8s]JIT/jit64/hfa/main/testE/hfa_nf2E_d/hfa_nf2E_d.sh
FAILED   - [   3][   8s]JIT/jit64/hfa/main/testE/hfa_nf2E_r/hfa_nf2E_r.sh
FAILED   - [   6][   3s]JIT/jit64/hfa/main/testE/hfa_sf2E_d/hfa_sf2E_d.sh
FAILED   - [   7][   3s]JIT/jit64/hfa/main/testE/hfa_sf2E_r/hfa_sf2E_r.sh
               Assert failure(PID 12093 [0x00002f3d], Thread: 12093 [0x2f3d]): Assertion failed '(allRegs(theInterval->registerType) & mask) != 0' in 'HFATest.TestCase:Main():int' (IL size 590)

                   File: /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp Line: 903
```
