### ISSUE TITLE
WeakReference behaves differently from .NET Framework.

### ISSUE THREAD

**Issue by ngbrown** [dotnet/coreclr#12847]
I am porting NHibernate to .NET Core (nhibernate/nhibernate-core#633), and some of the tests related to `WeakReference` are not passing.

The same tests have been running on .NET Framework.

Please see the example test here:  https://github.com/ngbrown/coreclr-WeakReferenceTest

Running:
```
dotnet test -f net461
```
passes, while running:

```
dotnet test -f netcoreapp2.0
```

fails with:
```
NUnit3TestExecutor converted 7 of 7 NUnit test cases
NUnit Adapter 3.8.0.0: Test execution complete
Failed   IterationAfterGC
Error Message:
   should not have live elements
  Expected: False
  But was:  True

Stack Trace:
at NHibernate.Test.UtilityTest.WeakHashtableFixture.IterationAfterGC() in C:\dev\test\WeakReferenceTest\WeakHashtableFixture.cs:line 71

Failed   Scavenging
Error Message:
   Expected: 0
  But was:  2

Stack Trace:
at NHibernate.Test.UtilityTest.WeakHashtableFixture.Scavenging() in C:\dev\test\WeakReferenceTest\WeakHashtableFixture.cs:line 57

Failed   WeakReferenceGetsFreedButHashCodeRemainsConstant
Error Message:
   Expected: False
  But was:  True

Stack Trace:
at NHibernate.Test.UtilityTest.WeakHashtableFixture.WeakReferenceGetsFreedButHashCodeRemainsConstant() in C:\dev\test\WeakReferenceTest\WeakHashtableFixture.cs:line 41


Total tests: 7. Passed: 4. Failed: 3. Skipped: 0.
Test Run Failed.
Test execution time: 2.0657 Seconds
```

I think the summary is that weak references don't appear to actually be getting freed like they should be during garbage collection.  This means we can't be sure that our query cache (which `WeakHashtable` is used for) won't be a memory leak problem.

Version info:
```
> dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**Comment by ngbrown** [comment]
I wasn't 100% sure where to put this issue, because coreclr implements `WeakReference` and corefx has some [tests for it](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/WeakReferenceTests.cs).

From those tests, they sometimes did these three calls before checking stuff:

```cs
GC.Collect();
GC.WaitForPendingFinalizers();
GC.Collect();
```

but changing to that from a single `GC.Collect();` didn't change the results of our tests.

**Comment by jkotas** [comment]
The JIT has been always extending the lifetime of the local and temp variables in some cases - the spec allows that. It started doing it in more cases after change https://github.com/dotnet/coreclr/pull/9231.

We had tests that used to depend on the exact lifetime tracking as well that needed updating after this change, e.g. https://github.com/dotnet/corefx/pull/16595 .

**Comment by ngbrown** [comment]
Does `WeakReference` also depend on where in the stack it was created at or `GC.Collect()` was run at?  I don't really understand why `MethodImplOptions.NoInlining` is so important to the changes that happened.

Any suggestions for the [test code](https://github.com/ngbrown/coreclr-WeakReferenceTest/blob/master/WeakHashtableFixture.cs#L57)?

**Comment by stephentoub** [comment]
> Any suggestions for the test code?

Put the:
```C#
table[new object()] = new object();
table[new object()] = new object();
```
lines into their own non-inlined method so that the JIT doesn't have the ability to extend beyond the lifetime of the method any temporaries keeping those objects alive.

**Comment by swgillespie** [comment]
@ngbrown Here's a PR where I fixed some of CoreCLR's own tests that were running into trouble with the Collect/WaitForPendingFinalizers/Collect pattern: https://github.com/dotnet/coreclr/pull/11216. Unfortunately these sorts of tests are racy in general due to the asynchrony of the finalizer thread but the fixes I made in that PR seem to have fixed the tests.

**Comment by ngbrown** [comment]
Thanks everyone.  Putting the temporary objects into a non-inlined function fixed it.
