### ISSUE TITLE
Documentation based on Carol Eidt's tutorial from PLDI'16 

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#12859]
@CarolEidt I would love to see documentation pages with walkthrough on adding new feature to RyuJIT and supporting technologies as it was presented on [PLDI'16 workshop](https://gist.github.com/CarolEidt/58c7d4290d649783c749) or perhaps in expanded form. 

Reading the code and current documentation as a way to understand RyuJIT and start to play with code has a steep learning curve penalty.

**Comment by 4creators** [comment]
I am interested in grabbing this issue. The only problem is that I have not seen Corl Eidt's PLDI'16 workshop and to write docs I would need some notes or slides.

**Comment by CarolEidt** [comment]
@4creators - that would be great! When this issue was opened, I had planned to update the slides and translate them to md, and clean them up, but that's a bit of work so I hadn't gotten started on it. I will find and post either the slides or an md version by EOD tomorrow. Then you can go through them and see what works & what doesn't and what needs cleaning up, and I'll try to respond quickly to questions or issues.

**Comment by CarolEidt** [comment]
P.S. I think it will actually be good for someone not as intimately familiar with the JIT to do this, because you'll be a better judge of what isn't clear.

**Comment by 4creators** [comment]
Thank for fast response, I will be waiting for slides and notes :)

**Comment by CarolEidt** [comment]
I have a pull request #13079 for a markdown translation of the slides and notes - I haven't added any of the diagrams yet.

**Comment by 4creators** [comment]
How can we communicate? Via code review or via PR and review to your [coreclr/RyuJITTutorial](https://github.com/CarolEidt/coreclr/tree/RyuJITTutorial) branch. I have cloned it and started working on it.

**Comment by CarolEidt** [comment]
> How can we communicate? Via code review or in this repo or via PR and code review in your coreclr/RyuJITTutorial branch. I have already cloned it and started working on it.

I think that probably the best way is for me to merge my PR, and then you can submit PR's with updates, and we can continue to communicate questions on this issue. If we need to set up a chat, we can do that as well as the need arises.

**Comment by CarolEidt** [comment]
@4creators - I've added diagrams and merged my PR. Feel free to submit PR's with updates and/or ask questions that you think need clarification.

**Comment by 4creators** [comment]
Closing as documentation was added to coreclr.
