### ISSUE TITLE
Introduce a PGO Verification Test

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#12863]
At a minimum, this test should verify that PGO is enabled for the builds that we expected it to be enabled for.  For example, on Windows, we can run "dumpbin /headers <coreclr.dll | clrjit.dll> | grep coffgrp" and validate that the build is a PGU build.

It's fine for developers to not build using PGO, but we do want to make sure that official and PR builds pass this test - otherwise, we need to figure out what happened.

NOTE: I have not yet found a way to detect whether or not PGO data was properly applied when using LLVM on Linux.  It appears that "llvm-profdata show" only operates on profdata files and not shared objects that have been built with profile data.

cc: @jorive

**Comment by jorive** [comment]
cc: @nategraf

**Comment by nategraf** [comment]
The solution above is what I have landed on after some discussion with others. The key points that may or may not need further discussion (as I see them) are:
- If the positioning of this test as part of runtest.proj, but outside XUnit's purview is appropriate
- If the use of Python including checking in a small module is appropriate
- If it should also verify that PGO was NOT used when it should not be (The negative case)

**Comment by nategraf** [comment]
Still need one more PR to enable the tests in CI

**Comment by brianrob** [comment]
@nategraf, thanks for making these changes.  Does your latest PR affect official builds and CI or just CI?

**Comment by nategraf** [comment]
Just the CI

**Comment by brianrob** [comment]
Ok, great.  Do you know what needs to be done for the official build or is this the next avenue of investigation?

**Comment by nategraf** [comment]
That's the next avenue of investigation. I wanted to make sure these changes don't break anything once they are merged. I'm currently looking at a case where it's causing some friction.

**Comment by brianrob** [comment]
Ok, good deal.  Thanks.

**Comment by nategraf** [comment]
This check is working in the CI builds. In the logs for "Windows_NT x64 Release Priority 1 Build and Test" you can find

```
  Checking if the following DLLs are properly compiled with PGO
  D:\j\workspace\x64_release_w---0575cb46\bin\Product\Windows_NT.x64.Release\clrjit.dll: compiled with PGO (PGU)
  D:\j\workspace\x64_release_w---0575cb46\bin\Product\Windows_NT.x64.Release\coreclr.dll: compiled with PGO (PGU)
```
