### ISSUE TITLE
Does the Microsoft symbol server publish .NET Core symbols?

### ISSUE THREAD

**Issue by micli** [dotnet/coreclr#12880]
Can I specify Microsoft server http://msdl.microsoft.com/download/symbols when I debugging .NET Core application in both of platforms on Linux, Windows and macOS ?

Thanks!

**Comment by mikem8361** [comment]
The Microsoft symbol server only contains the .NET Core symbols/binaries for Windows. There are no Linux/OS X symbols/binaries on this symbol server.  As far as I know, none of the xplat debuggers (lldb, gdb, VSCode) support any kind of symbol server anyway.
