### ISSUE TITLE
[ARM32][LEGACY_BACKEND] System.DataMisalignedException: A datatype misalignment was detected in a load or store instruction.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#12908]
e.g.
```
Unexpected exception: System.DataMisalignedException: A datatype misalignment was detected in a load or store instruction.
   at InterlockedIncrement1.PosTest1()

Assert failure(PID 12512 [0x000030e0], Thread: 3428 [0x0d64]): fFixedUp || (pExceptionRecord->ExceptionCode == STATUS_STACK_OVERFLOW)

!  + 0x0 (0x00000000)
    File: c:\dev\coreclr\src\vm\exceptionhandling.cpp Line: 1205
    Image: c:\dev\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```
This is causing the following tests to fail:
### JitStress=1, JitStress=2
- InterlockedIncrement1.cmd_1252

**Comment by RussKeldorph** [comment]
This appears to be a stress-specific bug during `lvaStressLclFld`.  `LCL_FLD_PADDING` is [used](https://github.com/dotnet/coreclr/blob/d8b212f3190bedac609bf822638561e515694a93/src/jit/lclvars.cpp#L7215-L7229) to shift the lclvar's address, but the logic doesn't take alignment requirements into account.  
Perhaps we should adjust the padding amount to maintain alignment for address-exposed lclvars?

@dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
Calling this a test bug for now to note it is lower priority.  If it starts hitting in other tests as jitstress gets perturbed, we'll need to fix it sooner rather than later.

**Comment by BruceForstall** [comment]
This bug is ancient and we haven't seen the issue lately. I do remember an ARM-specific fix being made in this area.
