### ISSUE TITLE
[ARM32][LEGACY_BACKEND] Assertion failed 'tree->gtCall.IsTailCall()'

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#12907]
e.g.
```
Assert failure(PID 12584 [0x00003128], Thread: 12028 [0x2efc]): Assertion failed 'tree->gtCall.IsTailCall()' in 'HFATest.TestCase:Main():int' (IL size 575)

    File: c:\dev\coreclr\src\jit\assertionprop.cpp Line: 2105
    Image: c:\dev\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```

This is causing the following tests to fail:
### JitStress=1
- hfa_nf0E_r.cmd_10089
- hfa_nf1E_r.cmd_9915
- hfa_sf1E_r.cmd_2546
### JitStress=2
- hfa_nf0E_r.cmd_10089
- hfa_nf1E_r.cmd_9915
- hfa_sf1E_r.cmd_2546
- StructABI.cmd_1124

**Comment by pgavlin** [comment]
On a fundamental level, this is due to an IR shape that is not handled correctly by `fgMorphOneAsgBlockOp`: in particular, this function appears to assume that if the assignment type is not a struct type, then it must be valid to set certain `GT_IND`-specific flags on the RHS (https://github.com/dotnet/coreclr/blob/master/src/jit/morph.cpp#L9021-L9029). On ARM32, however, the RHS might be a single-field-HFA-returning call, and setting these flags incorrectly changes call-related flags instead. These incorrect flags cause later bits of the JIT to go a little haywire, eventually manifesting in the assert mentioned in this issue.

#12943 is an indirect solution as it prevents single-field-HFA-returning calls from having a non-struct type.

**Comment by pgavlin** [comment]
cc @CarolEidt

**Comment by CarolEidt** [comment]
This may be too obvious to be a valid solution, but it would seem that setting those flags would only be valid or necessary if it is a `GT_IND`. On x64/x86, that would be the case, since, IIRC, the rhs is always a `GT_IND` or a local. I believe that it's only on targets that return structs by value in registers that we support a `GT_CALL` on the rhs.

**Comment by pgavlin** [comment]
Here's the relevant morph dump:

```
fgMorphTree (before 486):
               [000425] --C-G--------             *  CALL      struct HFATest.TestMan.Get_HFA01
argSlots=0, preallocatedArgCount=0, nextSlotNum=0, outgoingArgSpaceSize=0

fgMorphTree (after 486):
               [000425] --C-G--------             *  CALL      float  HFATest.TestMan.Get_HFA01

fgMorphCopyBlock:
Local V37 should not be enregistered because: was accessed as a local field
fgMorphOneAsgBlock (after):
               [002143] --CXG--------             /--*  IND       int   
               [002142] --CXG--------             |  \--*  ADDR      byref 
               [000425] --CXG+-------             |     \--*  CALLV stub float  HFATest.TestMan.Get_HFA01
               [000432] -ACXG--------             *  ASG       int   
               [000431] *----+-N-----             \--*  IND       int   
               [000430] L----+-------                \--*  ADDR      byref 
               [000429] D----+-N-----                   \--*  LCL_VAR   struct V37 tmp29        
```

`fgMorphBlockOperand` adds the `IND(ADDR())` that wraps the call *after* the problematic flags have been set on the call node.

**Comment by pgavlin** [comment]
Indeed, the addition of the `IND(ADDR())` is what made me moderately skeptical about the easy solution that you suggest. After some further thought, however, I think that your suggestion is probably sufficient: presumably if we add this wrapper we can be certain that the location being dereferenced is known to point into the local frame, so these flags would not be necessary.

**Comment by CarolEidt** [comment]
> if we add this wrapper we can be certain that the location being dereferenced is known to point into the local frame, so these flags would not be necessary.

Yes, I think that's correct. The cases where we have a non-indirection rhs of a struct assignment are limited. To be conservative, you could assert that if the rhs is not an indirection, then it is a call or local, either of which mean the struct is on the stack.
