### ISSUE TITLE
[ARM32][LEGACY_BACKEND] Assertion failed 'isGeneralRegister(id->idReg2())'

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#12906]
e.g.
```
Assert failure(PID 8980 [0x00002314], Thread: 12628 [0x3154]): Assertion failed 'isGeneralRegister(id->idReg2())' in 'StructABI:Main():int' (IL size 2040)

    File: c:\dev\coreclr\src\jit\emitarm.cpp Line: 203
    Image: c:\dev\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```

This is causing the following tests to fail:
### JitStress=1
- hfa_nd0E_r.cmd_7442
### JitStressRegs=1
- StructABI.cmd_1124

**Comment by BruceForstall** [comment]
Dup of #8093?

**Comment by pgavlin** [comment]
> Dup of #8093?

Essentially, yes. I only left this open because it tracks a failure that is not mentioned in that issue--feel free to close this if you feel that #8093 is sufficient.

**Comment by BruceForstall** [comment]
@jashook Can this issue also be closed (after you verify all the test cases pass), with #12943?

**Comment by jashook** [comment]
Confirmed these no longer repro.
