### ISSUE TITLE
[ARM32][LEGACY_BACKEND] Assertion failed '(rsMaskLock & regMask) == 0'

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#12910]
e.g.
```
Assert failure(PID 6868 [0x00001ad4], Thread: 8788 [0x2254]): Assertion failed '(rsMaskLock & regMask) == 0' in 'System.Reflection.Metadata.Ecma335.MethodTableReader:GetRva(struct):int:this' (IL size 40)

    File: c:\dev\coreclr\src\jit\regset.cpp Line: 332
    Image: c:\dev\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```

This is causing the following tests to fail:
### JitStressRegs=1
- Compilation.cmd_11084
- ConvertToInt32_17.cmd_859
- ConvertToUInt3213.cmd_447
- CscBench.cmd_3424
### JitStress=1, JitStressRegs=1
- b70994.cmd_9671
- Compilation.cmd_11084
- ConvertToInt32_17.cmd_859
- ConvertToUInt3213.cmd_447
- CscBench.cmd_3424

**Comment by RussKeldorph** [comment]
set COMPlus_AltJit=*
set COMPlus_AltJitName=legacynonjit.dll
set COMPlus_JitStress=1
set COMPlus_JitStressRegs=1
cd <root>\bin\tests\Windows_NT.x86.Debug\JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b70994\b70994
b70994.cmd -coreroot <root>\bin\tests\Windows_NT.x86.Debug\Tests\Core_Root
