### ISSUE TITLE
Possible RyuJIT bug causes application hang with 100% CPU usage

### ISSUE THREAD

**Issue by oatkins** [dotnet/coreclr#12927]
After a recent Windows update, our build broke (for an internal LOB application). Build machines running acceptance tests were timing out, with the IIS Express process showing 100% CPU usage.

We identified that this could be fixed by switching to LegacyJit. Changing the version of .NET (e.g. to 4.7) does not fix the problem.

After examining the stacks of running threads on an IIS process manifesting the problem, I came up with a small repro: https://github.com/oatkins/RyuJitIssue

The code that causes the problem is ServiceStack's implementation of `ConcurrentDictionary<,>`. (We are "stuck" on an old version of ServiceStack because of licensing issues.) Accessing the dictionary from multiple threads seems to cause some kind of spin lock to "spin" indefinitely, hence the 100% CPU usage.

My debugging skills aren't up to working out whether the jit change is just revealing a bug in existing code (the `ConcurrentDictionary` implementation) or whether RyuJIT is generating code wrongly. However, ServiceStack is popular, and I suspect that many projects are still running on version 3.

Interestingly, in our "real" environment (rather than my small repo), the troublesome dictionary was being used from ServiceStack's version of [MiniProfiler](http://miniprofiler.com/). A couple of years ago, StackOverflow had a [production issue with RyuJIT](https://nickcraver.com/blog/2015/07/27/why-you-should-wait-on-dotnet-46/) which was also in MiniProfiler! This seems just to be a coincidence, though. The stack traces aren't obviously similar.

**Comment by mikedn** [comment]
It looks to me that this is a bug in this ServiceStack code (from a decompiler because I couldn't find the source code):
```C#
// ServiceStack.Net30.Collections.Concurrent.ObjectPool<T>
public void Release(T obj)
{
        ...
	while (true)
	{
		num2 = this.addIndex;
		if ((num2 & 134217728) <= 0)
		{
                                ...
				break;
		}
	}
        ...
}
```
```asm
    mov         eax,dword ptr [rsi+10h]  
L0:
    mov         ecx,eax  
    mov         r9d,ecx  
    and         r9d,8000000h  
    test        r9d,r9d  
    jg          L0
```
The JIT has hoisted the `addIndex` field load out of the loop and the loop is now infinite. The fields is not marked as volatile so the JIT is correct in doing this transformation.

**Comment by oatkins** [comment]
Interesting. [Here](https://github.com/ServiceStack/ServiceStack/blob/v3/src/ServiceStack.Common/Net30/ObjectPool.cs) is the source code. (Sorry: I should have included that link in the issue.) Thanks for the explanation. Looks as though we'll have to find a way to replace that code.

**Comment by mikedn** [comment]
> Here is the source code

Thanks! It's nice to see that the decompiler was right. Sometimes they screw up :)
