### ISSUE TITLE
CoreCLR uses the incorrect format string in printf type functions

### ISSUE THREAD

**Issue by benpye** [dotnet/coreclr#1294]
VS2015 RTM added a warning for using the incorrect string in printf (http://blogs.msdn.com/b/vcblog/archive/2015/06/22/format-specifiers-checking.aspx) which throws up various cases in the CoreCLR where the incorrect format string is used. I was going to just fix the errors and submit a PR however the "fix" is non trivial it seems. Many of the cases are with a size_t type, C99 added the 'z' prefix for size_t, MSVC seems to give 'I', only supporting 'z' in VS2015. PAL doesn't implement 'I' at this time other than for 'I64'. What is the best action to take here? If 'z' is used the minimum compiler is raised to VS2015, if 'I' is used PAL will have to modified to provide that functionality on other platforms. Another workaround would be to cast the value to a 64 bit type, and then always use the 64 bit format string, or we could disable the warnings 4778, 4477 and 4474. As warnings and treated as errors, this currently breaks the VS2015 build.

**Comment by JeremyKuhne** [comment]
C4778, C4477, C4474. (Adding with C prefix to make this a little easier to search for.)

**Comment by cheers00** [comment]
@JeremyKuhne  Coreclr compiling with VS2015 is still breaking. Wondering if there will be any fix soon.

**Comment by benpye** [comment]
@cheers00 What is the issue with the current master?

**Comment by cheers00** [comment]
It's same as #1356

**Comment by benpye** [comment]
That's not the true error message, that indicates a warning occurred, it's the warning that must be taken care of, it'll be further up in the build log.

**Comment by jkotas** [comment]
The warnings should be taken care of in master now. Also, I am working on more fixes for VS2015 build breaks in managed part of the build - #1375.
