### ISSUE TITLE
[RyuJIT/ARM32] Casts related NYI in codegenarm.cpp

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#12958]
There are few NYI in `codegenarm.arm` related to long <-> float casting. E. g.:
```
NYI_ARM("Casting int64/uint64 to double in genIntToFloatCast");
NYI_ARM("Casting int64/uint64 to float in genIntToFloatCast");
```
Is there any necessarily to keep them there? Such casts work well, since they are being transformed in Morph phase to different JIT helpers (like `CORINFO_HELP_LNG2DBL`).

I want to remove them. @dotnet/arm32-contrib any objections?

**Comment by BruceForstall** [comment]
Sounds good to me. Maybe leave some asserts (if there aren't any already) that such casts don't make it to codegen.
