### ISSUE TITLE
AccessViolationException with SIMD type fields in struct when optimizations enabled

### ISSUE THREAD

**Issue by RossNordby** [dotnet/coreclr#12950]
Executing [this](https://github.com/RossNordby/scratchpad/blob/d039476eb76f37c90e9c208585432e9e98b713b0/Repro/Repro/Program.cs) code:
```cs
using System.Numerics;

namespace Repro
{
    class Program
    {
        struct BoundingBoxTest
        {
            public Vector3 Min;
            public Vector3 Max;

            public override int GetHashCode()
            {
                return Min.GetHashCode() + Max.GetHashCode();
            }
        }

        public static void Test()
        {
            var box = new BoundingBoxTest();
            box.Min = Vector3.Min(box.Min, box.Min);
            var hmm = box.GetHashCode();
        }

        static void Main(string[] args)
        {
            var someMemory = new int[1];
            var someMoreMemory = new int[1];
            Test();
            someMoreMemory[someMemory[0]] = 0;
        }
    }
}

```
results in an AccessViolationException when compiled with optimizations enabled. It reproduces in every preview I've tried (from 2.0.0-preview2-002093-00 to 2.0.0-preview3-25518-01).

I didn't dig deep enough to identify a specific cause, but I did note that doing any the following seems to avoid the access violation (possibly only by chance):
1) Removing the BoundingBoxTest.GetHashCode override, 
2) Using StructLayout on the BoundingBoxTest to specify a size above the default of 24, and
3) Using non-SIMD types.

**Comment by AndyAyersMS** [comment]
This repros with current master. The jit is zeroing 16 bytes for simd12 variables in `Test`, and this overwrites the saved on entry `rdi`, and so when `Test` returns the locals in `Main` are wrong.
```asm
; Assembly listing for method Repro.Program:Test()
; Emitting BLENDED_CODE for X64 CPU with AVX
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 loc0         [V00    ] (  6,  6   )  struct (24) [rsp+0x28]   do-not-enreg[XS] must-init addr-exposed ld-addr-op
;  V01 tmp0         [V01    ] (  5,  5   )  simd12  ->  [rsp+0x28]   do-not-enreg[XSB] addr-exposed V00.Min(offs=0x00) P-DEP
;  V02 tmp1         [V02    ] (  2,  2   )  simd12  ->  [rsp+0x34]   do-not-enreg[XS] addr-exposed V00.Max(offs=0x0c) P-DEP
;  V03 OutArgs      [V03    ] (  1,  1   )  lclBlk (32) [rsp+0x00]
;
; Lcl frame size = 64

G_M40988_IG01:
       57                   push     rdi
       4883EC40             sub      rsp, 64
       C5F877               vzeroupper
       488D7C2428           lea      rdi, [rsp+28H]
       B906000000           mov      ecx, 6
       33C0                 xor      rax, rax
       F3AB                 rep stosd

G_M40988_IG02:
       C4E17857C0           vxorps   xmm0, xmm0
       C4E17911442428       vmovupd  xmmword ptr [rsp+28H], xmm0
       C4E17857C0           vxorps   xmm0, xmm0
       C4E17911442434       vmovupd  xmmword ptr [rsp+34H], xmm0  ;; trashes saved RDI
```

**Comment by AndyAyersMS** [comment]
Regression from 1.1 (which did not promote struct fields as aggressively, and was careful to use a 12 byte zeroing sequence).

Not really my area of expertise, but it would appear the cautionary logic in `lvaMapSimd12ToSimd16` that is currently 32-bit only needs to kick in for 64 bits too; it is inadvisable to increase the size of a P-DEP local.

cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
With changes to enable `lvaMapSimd12ToSimd16`'s restriction to kick in for 64 bits, and temporarily suppressing an assertion check in `Lowering::CheckNode`, the test passes, and the code in `Test` is now only zeroing 12 bytes per field:
```asm
G_M40988_IG02:
       C4E17857C0           vxorps   xmm0, xmm0
       C4E17B11442428       vmovsd   qword ptr [rsp+28H], xmm0
       C4E17970C802         vpshufd  xmm1, xmm0, 2
       C4E17A114C2430       vmovss   dword ptr [rsp+30H], xmm1
       C4E17857C0           vxorps   xmm0, xmm0
       C4E17B11442434       vmovsd   qword ptr [rsp+34H], xmm0
       C4E17970C802         vpshufd  xmm1, xmm0, 2
       C4E17A114C243C       vmovss   dword ptr [rsp+3CH], xmm1
```

**Comment by briansull** [comment]
@CarolEidt  @AndyAyersMS 
Please advice on whether this fix needs to be ported to Desktop

**Comment by AndyAyersMS** [comment]
Seems likely we'll need to port whatever fix we come up with. Not that far along yet with an actual fix.

**Comment by CarolEidt** [comment]
I agree; this would affect desktop equally. @AndyAyersMS let me know if there's anything you'd like me to do.

**Comment by AndyAyersMS** [comment]
@CarolEidt The fix for this seems relatively straightforward. Would be good to know if you agree. If so I can try to clean up the assert properly and start testing.

I've been working on #12949 instead....

**Comment by CarolEidt** [comment]
> The fix for this seems relatively straightforward. Would be good to know if you agree. If so I can try to clean up the assert properly and start testing.

Yes, I agree. I just looked at `Lowering::CheckNode()` and it's not really clear to me how valuable that is, but it should be pretty straightforward to change it to assert that we always widen `TYP_SIMD12` lclVars except in the case of "dependently promoted" fields.
