### ISSUE TITLE
Constructor Using Dynamic Type Not Visible When Using InternalsVisibleTo

### ISSUE THREAD

**Issue by adamrodger** [dotnet/coreclr#12988]
I have a class in `ClassLibrary1` like this:
```csharp
[assembly: InternalsVisibleTo("OtherLibrary")]
public class Foo
{
    internal Foo(dynamic bar)
    {
        Console.WriteLine(bar.Bar);
    }
}
```
And then in `OtherLibrary` I have a test:
```csharp
[Fact]
public void Test1()
{
    dynamic bar = new { Bar = "Success!" };
    Foo x = new Foo(bar);
}
```

**Expected Result**: Running the test passes and "Success!" is written to the console
**Actual Result**:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException : 'ClassLibrary1.Foo.Foo(object)' is inaccessible due to its protection level
   at CallSite.Target(Closure , CallSite , Type , Object )
   at CallSite.Target(Closure , CallSite , Type , Object )
   at OtherProject.UnitTest1.Test1()
```

If I change the constructor to take an explicitly typed object (e.g. pass a string directly) then the test passes. If I make the constructor public then the test also passes. It's only when `Foo` has an internal constructor with a `dynamic` argument.

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#22536
