### ISSUE TITLE
[RyuJIT] Get rid of TYP_CHAR and use TYP_USHORT instead

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#12983]
It's strange that we have both `TYP_CHAR` and `TYP_USHORT`, they're both unsigned short integers. It's even more strange that `TYP_CHAR` is used pretty much everywhere while `TYP_USHORT` rarely makes an appearance and as far as I can tell it is never used as a node type. Worse, there's code that doesn't bother to check for `TYP_USHORT`, it only checks for `TYP_CHAR` - `Lowering::getCastDescription` for example.

Is there any good reason to keep `TYP_CHAR`? Perhaps it was an attempt to be consistent with `TYP_BOOL`? At least `TYP_BOOL` does have a special meaning, it's an unsigned byte that's either 0 or 1. But `TYP_CHAR`?

**Comment by mikedn** [comment]
cc @dotnet/jit-contrib

**Comment by tannergooding** [comment]
> At least TYP_BOOL does have a special meaning, it's an unsigned byte that's either 0 or 1

Does `TYP_BOOL` actually guarantee that? I know there are several ways to get a `bool` with a value of `2`, for example.

**Comment by mikedn** [comment]
> Does TYP_BOOL actually guarantee that?

Sort of. I've seen it used in some cases in relation to compare operations which do produce only 0 and 1. But there's at least one case where it's used in situation where you can't actually guarantee that the value is 0/1 - in `fgMorphRecognizeBoxNullable` is used as the type of an indir that loads the `hasValue` field of a `Nullable<T>`. It's technically possible, by means of reflection or unsafe code, to set that field to some other value.

It might be worth digging a bit more into `TYP_BOOL` uses, perhaps it turns out that's just an unnecessary distraction.

**Comment by mikedn** [comment]
> It might be worth digging a bit more into TYP_BOOL uses, perhaps it turns out that's just an unnecessary distraction.

Well, TYP_BOOL is complicated, kind of redundant and debatably broken at the same time.

It turns out that any GT_IND node can have TYP_BOOL, not only those created by fgMorphRecognizeBoxNullable. Such nodes are created from bool field loads. Obviously, there is 0 guarantee that bool fields do contain only 0 and 1 so any optimization that relies on this is broken. How much broken remains to be seen.

IL local variables can too have type bool and the JIT does create TYP_BOOL lclvars for them and sets lvIsBoolean to true. However, it seems that GT_LCL_VAR nodes that refer to these variables have type TYP_INT.

Now, where is TYP_BOOL actually relevant? In most cases it is treated just like TYP_UBYTE. There are 3 exceptions that I found:

1. impImportStaticReadOnlyField uses `ival = *((bool*)fldAddr);` instead of `ival = *((unsigned char*)fldAddr);` to load the value of a static readonly field. AFAIK on all supported platforms sizeof(bool) is 1 so this use of TYP_BOOL is pointless (and possibly broken on platforms where sizeof(bool) is not 1).

2. optOptimizeBools relies indirectly on TYP_BOOL. It can turn `if (b1 && b2)` into `if (b1 & b2)` if it can prove that b1 and b2 are bools. Here things become kind of strange. The code doesn't directly check if the involved nodes have TYP_BOOL, it checks if the nodes are 0, 1 or lclvars with lvIsBoolean set. In short:
  * if b1 and b2 are bool fields then the optimization doesn't happen
  * if b1 and b2 are bool locals then the optimization does happen, even if the locals have been previously assigned values loaded from bool fields. Hmm...

To make things even more complicated optOptimizeBools also uses the GTF_BOOLEAN flag. It sets it on the b1 & b2 nodes it creates so it can also handle cases like `if (b1 && b2 && b3)`. Great but if we have such a flag why do we need TYP_BOOL? We could just make TYP_UBYTE GT_INDs and set the GTF_BOOLEAN flag on them if we really want to apply this optimization in the case of field.

3. optCreateAssertion can create a OAK_SUBRANGE [0,1] assertion from a TYP_BOOL node even if the value produced by that node isn't guaranteed to be in [0,1]. It's not clear what effect this may have, I suspect that sometimes this may result in a cast to TYP_BYTE being incorrectly dropped but I've yet to create a repro for this.

**Comment by fiigii** [comment]
May I ask the status of this work?

**Comment by mikedn** [comment]
No status. I was kind of waiting for the team to comment on it...

**Comment by fiigii** [comment]
@mikedn Thanks. Let me try this tomorrow.
