### ISSUE TITLE
[RyuJIT/ARM32] Numerous "InvalidProgramException while compiling method ..." while using crossgen

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#12997]
There about 23000 messages while compiling `System.Private.CoreLib.dll` using `crossgen` whin `libprotoji.so`.
For compiling I use `ReadyToRun`  and `FragileNonVersionable` modes:
```
./crossgen /ReadyToRun /JITPath /.../libprotojit.so System.Private.CoreLib.dll 
./crossgen /FragileNonVersionable /JITPath /.../libprotojit.so System.Private.CoreLib.dll 
```

Compiled `*.ni.dll` has smaller size (8122368 vs 13660160 legacy JIT).

cc @dotnet/arm32-contrib

**Comment by alpencolt** [comment]
@BruceForstall could you assign this issue to me?

**Comment by alpencolt** [comment]
I've used incorrect arguments for `crossgen`. Proper way to compile code with RyuJIT is:
```
COMPlus_AltJit=* COMPlus_AltJitNgen=* ./crossgen System.Private.CoreLib.dll
```
Option `/JITPath` doesn't allow to use RyuJIT since there is check in `coreclr/src/jit/compiler.cpp:5719`:
```C
#ifdef ALT_JIT
    if (!compIsForInlining() && !opts.altJit)
    {
        // We're an altjit, but the COMPlus_AltJit configuration did not say to compile this method,
        // so skip it.
        return CORJIT_SKIPPED;
    }
#endif // ALT_JIT
```

Knobs `COMPlus_AltJit=* COMPlus_AltJitNgen=*` are mandatory.
@BruceForstall is it possible to add more detailed error message for this case (or maybe change logic)?

2 new assertion found for `System.Private.CoreLib.dll`:
https://github.com/dotnet/coreclr/issues/13056
https://github.com/dotnet/coreclr/issues/13057

**Comment by BruceForstall** [comment]
> @BruceForstall is it possible to add more detailed error message for this case (or maybe change logic)?

I'm sure something is possible; I've had problems with this as well. I assume what's happening is the JIT returns CORJIT_SKIPPED, and the VM doesn't expect that, or have a fallback, so throws an "execution engine exception". I'm not sure what mechanisms the VM has for showing that. Maybe just throwing up an assert dialog in `_DEBUG` builds.

**Comment by alpencolt** [comment]
Not pretty solution but we can set `COMPlus_AltJit=* COMPlus_AltJitNgen=*` (or simulate like they were set in environment) if `/JITPath /.../libprotojit.so` was passed (off course we have to check if these variables were set buy user first).
So in this case we can use RyuJIT just buy calling `./crossgen /JITPath /.../libprotojit.so ...` and constrain list of compiled methods by using knobs `COMPlus_AltJit=* COMPlus_AltJitNgen=*`.

Check in `coreclr/src/jit/compiler.cpp:5719` is necessary for switching between JIT compilers (off course may there is better place for it or another return value).

**Comment by alpencolt** [comment]
I've rechecked only `COMPlus_AltJitNgen=*` is mandatory for using RyuJIT. `COMPlus_AltJit=*` and `/JITPath libprotojit.so` has no effect for `crossgen`.
