### ISSUE TITLE
[RyuJIT/ARM32] Full list of NYI_ARM

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#13000]
There is list of `NYI_ARM`. Some of them are obsolete and can be removed, another ones are optimizations and can be implemented in future.
Almost all of this list aren't covered by testsuit. So please let me know if some of this `NYI` are already assigned or can be removed. Information about which ones are optimizations and not important for us now is also will be useful.

**Structs:**
- `./jit/codegenarmarch.cpp:510:  NYI_ARM("genPutArgStk: fast tail call");`
- `./jit/codegenarmarch.cpp:545:  NYI_ARM("genPutArgStk: contained zero source");` #13138
- `./jit/codegenarmarch.cpp:668:  NYI_ARM("CodeGen::genPutArgStk - promoted struct");` #13096
- `./jit/codegenarmarch.cpp:1016: NYI_ARM("CodeGen::genPutArgSplit - promoted struct");` #13096
- `./jit/codegenarmarch.cpp:2298: NYI_ARM("CodeGen::genJmpMethod with multireg HFA arg");` #13142
- `./jit/codegenarmarch.cpp:3220: NYI_ARM("struct return from multi-reg GT_CALL");` Need to tail calls be implemented first.
- `./jit/lower.cpp:808:           NYI_ARM("lower: struct argument by fast tail call");`

**Copy Blocks:**
- `./jit/lowerarmarch.cpp:269:    NYI_ARM("initblk loop unrolling is currently not implemented.");`
- `./jit/lsraarmarch.cpp:802:     NYI_ARM("initblk loop unrolling is currently not implemented.");`
- `./jit/lsraarmarch.cpp:881:     NYI_ARM("cpblk loop unrolling is currently not implemented.");` #12614
- `./jit/codegenarm.cpp:781:      NYI_ARM("genCodeForCpBlkUnroll");`
- `./jit/codegenarm.cpp:790:      NYI_ARM("genCodeForInitBlkUnroll");`

**Casts:**
- `./jit/lowerarmarch.cpp:408:    NYI_ARM("Lowering for cast from float to small type"); // Not tested yet.`
- `./jit/codegenarmarch.cpp:1719: NYI_ARM("genRegCopy from 'int' to 'float'");`
- `./jit/codegenarm.cpp:1585:     NYI_ARM("Casting int64/uint64 to double in genIntToFloatCast");` #12958
- `./jit/codegenarm.cpp:1598:     NYI_ARM("Casting int64/uint64 to float in genIntToFloatCast");` #12958
- `./jit/codegenarm.cpp:1661:     NYI_ARM("Casting double to int64/uint64 in genIntToFloatCast");` #12958
- `./jit/codegenarm.cpp:1674:     NYI_ARM("Casting float to int64/uint64 in genIntToFloatCast");` #12958

**GC_WRITE_BARRIER:**
- `./jit/codegenarm.cpp:1355:     NYI_ARM("NOGC_WRITE_BARRIERS");` Optimization.
- `./jit/lsraarmarch.cpp:129:     NYI_ARM("NOGC_WRITE_BARRIERS");` Optimization.

**Others:**
- `./jit/lsraarmarch.cpp:378:     NYI_ARM("tail call");`
- `./jit/codegenarmarch.cpp:1922: NYI_ARM("fast tail call");`
- `./jit/lsraarmarch.cpp:549:     NYI_ARM("float reg varargs");`
- `./jit/codegenarmarch.cpp:454:  NYI_ARM("genIntrinsic for round - not implemented yet");`
- `./jit/codegenarmarch.cpp:1867: NYI_ARM("CodeGen - IsVarargs");`
- `./jit/codegenlegacy.cpp:10417: NYI_ARM("LOCK instructions");`
- `./jit/lowerarm.cpp:40:         NYI_ARM("isRMWRegOper() is never used and tested for ARM");`
- `./jit/emitarm.cpp:3696:        NYI_ARM("JitDataOffset static fields");`
- `./jit/emitarm.cpp:3700:        NYI_ARM("Thread-Local-Storage static fields");`
- `./jit/emitarm.cpp:3758:        NYI_ARM("JitDataOffset static fields");`
- `./jit/emitarm.cpp:3762:        NYI_ARM("Thread-Local-Storage static fields");`
- `./jit/lowerarmarch.cpp:81:     NYI_ARM("ARM IsContainableImmed for floating point type");`
- `./jit/lsraarm.cpp:265:         NYI_ARM("Lowering::TreeNodeInfoInit for GT_INTRINSIC");`
- `./jit/lsraarm.cpp:748:         NYI_ARM("TreeNodeInfoInit default case");`
- `./jit/codegenarm.cpp:1067:     NYI_ARM("st.lclFld contained operand");`
- `./jit/codegenarm.cpp:1119:     NYI_ARM("st.lclVar contained operand");`

cc @dotnet/arm32-contrib

**Comment by BruceForstall** [comment]
The current list is:

```
codegenarm.cpp:    NYI_ARM("genCodeForCpBlkUnroll");
codegenarm.cpp:    NYI_ARM("genCodeForInitBlkUnroll");
codegenarm.cpp:        NYI_ARM("st.lclFld contained operand");
codegenarm.cpp:            NYI_ARM("st.lclVar contained operand");
codegenarm.cpp:        NYI_ARM("NOGC_WRITE_BARRIERS");
codegenarmarch.cpp:            NYI_ARM("genIntrinsic for round - not implemented yet");
codegenarmarch.cpp:        NYI_ARM("genPutArgStk: fast tail call");
codegenarmarch.cpp:            NYI_ARM("genRegCopy from 'int' to 'float'");
codegenarmarch.cpp:            NYI_ARM("CodeGen - IsVarargs");
codegenarmarch.cpp:        NYI_ARM("fast tail call");
codegenarmarch.cpp:        NYI_ARM("struct return from multi-reg GT_CALL");
codegenlegacy.cpp:            NYI_ARM("LOCK instructions");
emitarm.cpp:        NYI_ARM("JitDataOffset static fields");
emitarm.cpp:        NYI_ARM("Thread-Local-Storage static fields");
emitarm.cpp:        NYI_ARM("JitDataOffset static fields");
emitarm.cpp:        NYI_ARM("Thread-Local-Storage static fields");
lower.cpp:            NYI_ARM("lower: struct argument by fast tail call");
lowerarm.cpp:    NYI_ARM("isRMWRegOper() is never used and tested for ARM");
lowerarmarch.cpp:                    NYI_ARM("ARM IsContainableImmed for floating point type");
lowerarmarch.cpp:            NYI_ARM("initblk loop unrolling is currently not implemented.");
lowerarmarch.cpp:        NYI_ARM("Lowering for cast from float to small type"); // Not tested yet.
lsraarm.cpp:                    NYI_ARM("Lowering::TreeNodeInfoInit for GT_INTRINSIC");
lsraarm.cpp:            NYI_ARM("TreeNodeInfoInit default case");
lsraarmarch.cpp:    NYI_ARM("NOGC_WRITE_BARRIERS");
lsraarmarch.cpp:            NYI_ARM("tail call");
lsraarmarch.cpp:        NYI_ARM("float reg varargs");
lsraarmarch.cpp:            NYI_ARM("initblk loop unrolling is currently not implemented.");
lsraarmarch.cpp:                NYI_ARM("cpblk loop unrolling is currently not implemented.");
```

**Comment by sergign60** [comment]
@dotnet/arm32-contrib 

codegencommon.cpp: NYI("Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch");
codegencommon.cpp: NYI("Model kill set for CORINFO_HELP_PROF_FCN_ENTER on target arch");
codegencommon.cpp: NYI("Model kill set for CORINFO_HELP_PROF_FCN_LEAVE on target arch");
codegencommon.cpp: NYI("Model kill set for CORINFO_HELP_PROF_FCN_TAILCALL on target arch");

**Comment by BruceForstall** [comment]
Now that #17365 has been merged, I don't think there's much value in keeping this issue. Separate issues can be created for individual cases, if necessary.
