### ISSUE TITLE
optimizing the memory set loop with size requirements the right way

### ISSUE THREAD

**Issue by Maoni0** [dotnet/coreclr#13015]
When you have this code:

` for (size_t i = 0; i < nPtrs; i++)
        *memPtr++ = 0;`

even though you need memPtr to be cleared as pointers, the compiler can replace this with a memset which will set by bytes. So when you read this memory you can read a partially cleared pointer value which obviously will cause problems. We had to declare memPtr [to be volatile](https://github.com/dotnet/coreclr/issues/12207) in ZeroMemoryInGCHeap to get around this. This issue is for looking into bringing perf back. Since you could be clearing large amounts of memory with Array.Clear (which uses ZeroMemoryInGCHeap) [the perf degrade can be significant](https://github.com/dotnet/coreclr/issues/12207#issuecomment-317236008).

**Comment by Maoni0** [comment]
this is actually not GC code so removing the tag. however I dunno who on the runtime team to assign it to :)

**Comment by janvorli** [comment]
@Maoni0 ah, sorry for the mis-labeling.

**Comment by janvorli** [comment]
@Maoni0 I just took a quick look at that. Actually, the volatile is misplaced in the current implementation, it makes the pointer itself being volatile instead of the data it points to. 
So if the following line 
```C++
volatile PTR_PTR_VOID memPtr = (PTR_PTR_VOID) memBytes;
```
is replaced by 
```C++
PTR_VOID volatile * memPtr = (PTR_PTR_VOID) memBytes;
```
then clang generates much better code. 
The code before the change looked like this:
```asm
   ef7b0:       48 8d 4f 08             lea    rcx,[rdi+0x8]
   ef7b4:       48 89 4d f8             mov    QWORD PTR [rbp-0x8],rcx
   ef7b8:       48 c7 07 00 00 00 00    mov    QWORD PTR [rdi],0x0
   ef7bf:       48 8b 4d f8             mov    rcx,QWORD PTR [rbp-0x8]
   ef7c3:       48 8d 79 08             lea    rdi,[rcx+0x8]
   ef7c7:       48 89 7d f8             mov    QWORD PTR [rbp-0x8],rdi
   ef7cb:       48 c7 01 00 00 00 00    mov    QWORD PTR [rcx],0x0
   ef7d2:       48 8b 4d f8             mov    rcx,QWORD PTR [rbp-0x8]
   ef7d6:       48 8d 79 08             lea    rdi,[rcx+0x8]
   ef7da:       48 89 7d f8             mov    QWORD PTR [rbp-0x8],rdi
   ef7de:       48 c7 01 00 00 00 00    mov    QWORD PTR [rcx],0x0
   ef7e5:       48 8b 4d f8             mov    rcx,QWORD PTR [rbp-0x8]
   ef7e9:       48 8d 79 08             lea    rdi,[rcx+0x8]
   ef7ed:       48 89 7d f8             mov    QWORD PTR [rbp-0x8],rdi
   ef7f1:       48 c7 01 00 00 00 00    mov    QWORD PTR [rcx],0x0
   ef7f8:       48 83 c0 04             add    rax,0x4
   ef7fc:       48 8b 7d f8             mov    rdi,QWORD PTR [rbp-0x8]
   ef800:       48 39 d0                cmp    rax,rdx
   ef803:       72 ab                   jb     ef7b0 <ZeroMemoryInGCHeap+0xe0>
```
and after the change like this:
```asm
   ef7d0:       48 c7 07 00 00 00 00    mov    QWORD PTR [rdi],0x0
   ef7d7:       48 c7 47 08 00 00 00    mov    QWORD PTR [rdi+0x8],0x0
   ef7de:       00
   ef7df:       48 c7 47 10 00 00 00    mov    QWORD PTR [rdi+0x10],0x0
   ef7e6:       00
   ef7e7:       48 c7 47 18 00 00 00    mov    QWORD PTR [rdi+0x18],0x0
   ef7ee:       00
   ef7ef:       48 83 c0 04             add    rax,0x4
   ef7f3:       48 83 c7 20             add    rdi,0x20
   ef7f7:       48 39 d0                cmp    rax,rdx
   ef7fa:       72 d4                   jb     ef7d0 <ZeroMemoryInGCHeap+0xa0>
```

**Comment by mikedn** [comment]
> Actually, the volatile is misplaced in the current implementation, it makes the pointer itself being volatile instead of the data it points to.

Note that in my perf test I used volatile correctly and still got a 2x slowdown compared to memset. I tested in VC++ and the generated code was similar to your fixed code but without unrolling.

**Comment by janvorli** [comment]
@mikedn have you also measured the perf of the code as it is now in the repo with the misplaced volatile?

**Comment by mikedn** [comment]
@janvorli Nope. I didn't measure the perf of the actual code, I just wrote the loop in a console app and played with it to see how well it works compared to using `memset` and `rep movsq`.

**Comment by Maoni0** [comment]
@janvorli thanks for looking into this! will you be checking this change in? also CC @dpodder. 

It seems like we should just write a small routine that calls rep movsq...

**Comment by dpodder** [comment]
D'oh... thanks @janvorli for finding this. I just checked on Windows (with VS 2017) and we get a similar benefit by moving the volatile to the right spot.

Before-
```asm
  0000000180256849: mov         rax,qword ptr [rsp+30h]
  000000018025684E: mov         qword ptr [rax],r10
  0000000180256851: add         qword ptr [rsp+30h],8
  0000000180256857: sub         rdx,1
  000000018025685B: jne         0000000180256849
```

After-
```asm
  00000001802567A2: mov         qword ptr [rcx],rdx
  00000001802567A5: add         rcx,8
  00000001802567A9: sub         rax,1
  00000001802567AD: jne         00000001802567A2
```

The extra mov would definitely hurt if this were called on a particularly large list, or from an otherwise hot code path. I agree with @Maoni0 though, if we really want this to be perf-optimized we'll likely want to roll a different implementation that explicitly does rep movsq (or better). We need to be careful, though, to do the right thing for ARM platforms as well.

**Comment by DemiMarie** [comment]
The best answer, and what HotSpot does, is to use hand tuned assembler here; this avoids any such problems.  Alternatively, would it be possible to use a loop using atomic operations with `memory_order_relaxed` here?
