### ISSUE TITLE
Core Tests: All work items have fireball on ubuntu.1610.amd64

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/coreclr#13020]
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170725.01

Core Tests: All work items have fireball on ubuntu.1610.amd64

**Comment by Jiayili1** [comment]
This issue is also repro on Ready-To-Run Tests, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fr2r~2Fcli~2F/build/20170725.01

**Comment by danmosemsft** [comment]
16.10 is removed now. As for R2R, this is also no repro now.
