### ISSUE TITLE
Random exceptions with System.Net.Http.WinHttpHandler

### ISSUE THREAD

**Issue by hanabi1224** [dotnet/coreclr#13086]
It randomly(at very low chance) throws 'An item with the same key has already been added.' when SendAsync being called, and same issue never happen after removing  WinHttpHandler
Package version: 4.3.1
.Net version: 4.6.2
OS: Azure guest OS 5-*
Http version: 2.0

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#22697
