### ISSUE TITLE
Proposal: GC should provide APIs to prevent temp objects from promoting their generation 

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#13081]
I hope to have the following APIs:
GC.SetNewObjectsAlwaysGen0() - on current thread, after this is called, all newly allocated objects will always stay in Generation0, even if GC happens, till GC.UnsetNewObjectsAlwaysGen0 is called.
GC.UnsetNewObjectsAlwaysGen0() - on current thread, revert back to normal behavior where living objects promote their generations after GC. 
The use case of these APIs is the scenario that a lot of objects are temporarily allocated and become garbage soon.

**Comment by benaadams** [comment]
Does [`GC.TryStartNoGCRegion()`](https://msdn.microsoft.com/en-us/library/system.gc.trystartnogcregion(v=vs.110).aspx) -> `EndNoGCRegion()` do what you want?

@mattwarren did a write up about it [Preventing .NET Garbage Collections with the TryStartNoGCRegion API](http://mattwarren.org/2016/08/16/Preventing-dotNET-Garbage-Collections-with-the-TryStartNoGCRegion-API/)

**Comment by ygc369** [comment]
@benaadams
Not the same. I don't want to forbid GC, and I only want to keep temp objects in generation0 even if GC happens. Once I finish my work with them, they can be collected next Gen0 GC.

**Comment by clrjunkie** [comment]
@ygc369 Can you please post a short code sample to illustrate the use-case? I ask because I assume such Api call has the potential to incur more collections since by holding on to Gen0 objects one would effectively reduce the Gen0 memory threshold for initiating future GC's, if the "locked objects" are accounted for, and I'm curious to see a case where such trade off might make sense.

**Comment by ygc369** [comment]
@clrjunkie 
These APIs should be used carefully and the new behavior should not last for a long time. It should be very unlikely that GC happens just between GC.SetNewObjectsAlwaysGen0() and GC.UnsetNewObjectsAlwaysGen0(). But I want to use these APIs just in case.
The use-case is quite common, many algorithms need temp allocated buffers to store mid-results. But these algorithms are usually complex, so I can't write one here.
Your concern about incurring more collections is reasonable, so I suggest that GC.SetNewObjectsAlwaysGen0() extend the Gen0 memory threshold.
