### ISSUE TITLE
[ThreadPool] WorkStealingQueue volatile ops. need to be optimized

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#13090]
`volatile` operations are heavy weight as they prevent C# reordering and register caching.

`LocalPush()` fast path hits 7 volatile ops
`CanSteal` hits 2 volatile operations.
`TrySteal` hits 12 volatile ops
`LocalPop()` hits 14 volatile operations.

Consider using a struct/union to allow appropriate subset of these to be written simultaneously.

```C#
internal volatile IThreadPoolWorkItem[] m_array = new IThreadPoolWorkItem[INITIAL_SIZE];
private volatile int m_mask = INITIAL_SIZE - 1;
private volatile int m_headIndex = START_INDEX;
private volatile int m_tailIndex = START_INDEX;
```

Consider non-volatile caches of the volatile items.

These types of optimizations have reportedly already been done for `ConcurrentQueue<>`.  So consider using a `ConcurrentQueue<IThreadPoolWorkItem>` to implement `WorkStealingQueue`

**Comment by sdmaclea** [comment]
@kouvel I was reviewing my other PR and I noticed how bad this was.  With the other patch, this should not be a problem for plaintext, but it looks like there is significant opportunity for ARM/ARM64 here.  Possibly even for x64 and x86.

**Comment by kouvel** [comment]
Reusing ConcurrentQueue for the WorkStealingQueue seems to make sense at a high level, should evaluate

**Comment by stephentoub** [comment]
> So consider using a ConcurrentQueue<IThreadPoolWorkItem> to implement WorkStealingQueue

Work-stealing queues are by design LIFO from the perspective of the owning thread. Changing it to be FIFO could be quite bad for certain workloads.

**Comment by sdmaclea** [comment]
So perhaps liberally stealing ConcurrentQueue<> design ideas.  @stephentoub Is the queue always LIFO.  i.e. are the thefts LIFO, but locally thread FIFO?

**Comment by stephentoub** [comment]
> Is the queue always LIFO. i.e. are the thefts LIFO, but locally thread FIFO?

The owning thread always accesses it's own end of the WSQ, so it's LIFO. Every other thread only accesses the other end, so they're FIFO. The theory is that the owning thread ends up popping the most recent work that's hot in it's cache, and other threads steal cold work. Plus, as long as there are at least 2 items in the queue, there's no explicit synchronization between the owner accessing its WSQ and other threads stealing from it.

**Comment by sdmaclea** [comment]
Closing in favor of #17563
