### ISSUE TITLE
CoreCLR has numerous C4477 warnings building on VS2015

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/coreclr#1310]
There are a ton (1000+?). Causes around 40 warnings as errors and fails the build.

One example:

  d:\repos\coreclr\src\debug\daccess\daccess.cpp(7285): warning C4477: '_snprintf_s' : format string '%d' requires an argument of type 'int', but variadic argument 2 has type 'unsigned __int64' [D:\Repos\coreclr\bin\obj\Windows_NT.x64.Debug\src\debug\daccess\daccess.vcxproj]

**Comment by akoeplinger** [comment]
Sounds like https://github.com/dotnet/coreclr/issues/1294?

**Comment by JeremyKuhne** [comment]
Yep, thanks @akoeplinger. I'll add the C versions so it's easier to find. :)
