### ISSUE TITLE
[ARM64/Linux] Implement UMEntryThunkCode::Poison

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#13117]
#12731 introduces ``UMEntryThunkCode::Poison`` for all the architecture (x86, x64, arm, arm64), but arm64 variant does not have a proper implementation.

We need to implement it properly.

**Comment by BruceForstall** [comment]
@dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
@BruceForstall please assign to me
