### ISSUE TITLE
Not able to build on Windows with VS 2015 installed

### ISSUE THREAD

**Issue by ganeshran** [dotnet/coreclr#1312]
The readme page https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md lists VS 2015 community as a supported version of Visual Studio.

However when I installed VS 2015 alone and tried to build coreclr , it asked me to install VS 2013 community edition instead. 

Is VS 2015 community edition not supported for building CLR?

**Comment by DickvdBrink** [comment]
Did you add vs2015 to the build command:

See the note:
>Note: for building using Visual Studio 2015 the parameter vs2015 should be added to the build command.

**Comment by ganeshran** [comment]
Ah.. Brainfreeze. I uninstalled VS 2015 and installed VS 2013 instead.

It builds perfectly now :) :+1:
