### ISSUE TITLE
Unable to load System.IO.Native dll - when Building coreclr on linux

### ISSUE THREAD

**Issue by ganeshran** [dotnet/coreclr#1313]
I am trying to build coreclr on linux using these instructions - https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md

When trying to run the app, I get the error

>
ganeshran@ganeshran-VirtualBox:~/coreclr-demo/runtime$ ./corerun HelloWorld.exe linux

>
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'System.IO.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.NativeIO.FStat(Int32 fileDescriptor, FileStats& output)
   at System.ConsolePal.UnixConsoleStream..ctor(String devPath, FileAccess access)
   at System.ConsolePal.OpenStandardOutput()
   at System.Console.OpenStandardOutput()
   at System.Console.<get_Out>b__3()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at Program.Main(String[] args)

As per the instructions, I built the corefx on windows and then copied the two dlls in the runtime folder. - System.Console.Dll and System.Diagnostics.Debug.dll. 

Going through the code, it seems IO.Native is a UNIX shim . This requires a class Interop.NativeIO (in Common/Src/Unix folder in corefx repo).

Is there any other dll required to be copied from corefx into the runtime folder to make the application run. Please let me know if I should create this issue in corefx repo instead of here.

**Comment by ganeshran** [comment]
cc @nguerrera

**Comment by nguerrera** [comment]
Sending PR now. The docs were missing a step on how to build the shims.

**Comment by ganeshran** [comment]
Thanks @nguerrera

**Comment by ganeshran** [comment]
@nguerrera It's working now!  :+1: 

Also this is a minor nitpick but this line in the instructions readme should be changed so readers clone both coreclr and corefox on Linux too.  The Native\build.sh script is in the corefx repo 

>
This guide assumes that you've cloned the coreclr repository into ~/git/coreclr on your Linux machine and the corefx and coreclr repositories into D:\git\corefx and D:\git\coreclr on Windows
