### ISSUE TITLE
The type 'List<T>' exists in both...

### ISSUE THREAD

**Issue by Fosol** [dotnet/coreclr#1315]
How am I supposed to debug why DNX is pulling in two different libraries?

The type 'List<T>' exists in both 'System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	

I'm using DNX version 1.0.0.-beta5

Here is my dependencies in my project.json file.
  "dependencies": {
    "Microsoft.AspNet.Identity": "3.0.0-beta5",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta5",
    "Microsoft.AspNet.DataProtection": "1.0.0-beta5",
    "Microsoft.AspNet.Mvc": "6.0.0-beta5",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta5",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta5",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta5",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta5",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta5",
    "Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta5",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta5",
    "Microsoft.Framework.Configuration.UserSecrets": "1.0.0-beta5",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta5",
    "LIS.Membership": "1.0.0-*"
  },

**Comment by Fosol** [comment]
I was able to drill down into my dependencies and find the project that was pulling in System.Collections separately.

Now that it's removed I get the following error.

Cannot implicitly convert type 'System.Threading.Tasks.Task<System.Collections.Generic.List<string>>' to 'System.Threading.Tasks.Task<System.Collections.Generic.IList<string>>'

**Comment by omariom** [comment]
Task<List<string>> and Task<IList<string>> are two different types.
Casting would work if it were ITask<T> supporting covariance.

**Comment by weshaggard** [comment]
List should be coming from System.Collections, at least at compile time, in the implementation it lives in mscorlib but the is an implementation detail and should not be referenced by anything at compile time. What is the original error you are hitting?

**Comment by BrunoJuchli** [comment]
@Fosol 
I think that while you can implicitly convert `task.Result` to `IList<string>` you cannot convert `Task<List<string>>` to `Task<IList<string>>`.
That's because `Task` is defined as `Task<TResult>` and not `Task<out TResult>`.

`IEnumerable` is ` IEnumerable<out T>` and so the following works:

    IEnumerable<List<string>> x = null;
    IEnumerable<IList<string>> f = x;

**Comment by Fosol** [comment]
Thanks!

I was able to cast to (List<string>) without any problems.
