### ISSUE TITLE
assembly-redirects in netcoreapp1.1 application

### ISSUE THREAD

**Issue by matthid** [dotnet/coreclr#13168]
See the F# repro in https://github.com/Microsoft/visualfsharp/issues/3408. I asked in gitter chat if there is a workaround to tell the runtime to load the correct assembly. @0x53A [found a similar way to make C# fail](https://github.com/Microsoft/visualfsharp/issues/3408#issuecomment-319527058). Now I have several questions and follow ups:

- ~~[1] Apparently binding redirections are still a thing? Can someone confirm that? If yes, is there documentation?~~
   ~~I tried to set them up via `<name>.dll.config` and `App.config` in the entry dll directory, but it seems like they are ignored.~~
   ~~Is this because `Suave` Is not signed?~~
 - ~~[2] If yes, is there anything you can do to achieve the correct behavior (besides redirecting manually at runtime)?~~
 - [3] Can I get a link to some docs or some further information about `<Name>.deps.json` and how that changes runtime behavior? 
 - [4] Are there other options I have not thought about?

Note that this is not about the particular Suave packaging error, which I acknowledge and needs to be fixed. But rather about the general solution we have when transitive dependencies don't match. In particular it is easy to construct similar situations when people build not against the "Minimal Version Requirement" they specify in the nuspec, which can happen quite often.

Thank you!

**Comment by matthid** [comment]
Apparently binding redirects are no longer supported. 
[3] and [4] still remain. In Particular I'd like to know if there is another way than doing it programmatically via `AssemblyLoadContext.Default.Resolving`...

**Comment by matthid** [comment]
Related https://github.com/dotnet/sdk/issues/384

**Comment by jkotas** [comment]
> Can I get a link to some docs or some further information about `<Name>.deps.json`

https://github.com/dotnet/cli/blob/master/Documentation/specs/runtime-configuration-file.md

> there is another way than doing it programmatically via `AssemblyLoadContext.Default.Resolving`

That's the way to do this in .NET Core. There is no declarative mechanism to compensate for packaging errors.
