### ISSUE TITLE
Stop building Ubuntu 16.10 on all branches

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/coreclr#13173]

**Comment by RussKeldorph** [comment]
@ChadNedzlek Is this still a problem?  I can't find 16.10 builds anywhere, but I may not be looking in the right place.

@weshaggard @danmosemsft

**Comment by ChadNedzlek** [comment]
Someone's probably already done it in the last 4 months... I'm not sure who though (I can't figure out what controls what platforms are built)
