### ISSUE TITLE
[RyuJIT] wrong sum result with /optimize on x64

### ISSUE THREAD

**Issue by rmbq** [dotnet/coreclr#13193]
I made a small project to test this issue, you can find it [here](https://drive.google.com/open?id=0By7oA_lL6epnMVZrRUV5SUpPVkE). small extract is this but issue can't be triggered with this method alone.
```
public void AnswerToCe(int currentBlock)
		{
			byte[] bufferToSend;
			byte[] macDst = mac;
			byte[] macSrc = TestSInstance.Instance.GetMAC();
			byte[] ethType;
			byte[] header;

			ethType = BitConverter.GetBytes(0x70ce);
			ethType = new byte[] { ethType[1], ethType[0] };
			header = Header.GetBytes();
			int index = 0;
			bufferToSend = new byte[macDst.Length + macSrc.Length + ethType.Length + header.Length + binaryBlocks[currentBlock].Length];
			Array.Copy(macDst, 0, bufferToSend, index, macDst.Length);
			index += macDst.Length;
			Array.Copy(macSrc, 0, bufferToSend, index, macSrc.Length);
			index += macSrc.Length;
			Logger.SInstance.Write(index.ToString(), "prova index pre");
			Array.Copy(ethType, 0, bufferToSend, index, ethType.Length);
			index += ethType.Length; /*<- THIS LINE!*/
			Logger.SInstance.Write(index.ToString(), "prova index post");
			//Debugger.Launch();
			Array.Copy(header, 0, bufferToSend, index, header.Length);
			index += header.Length;
			Array.Copy(binaryBlocks[currentBlock], 0, bufferToSend, index, binaryBlocks[currentBlock].Length);
		}
	}
```
In MainWindows.xaml.cs line 57 index value should be 14 but i get 18. disassembly can be found [here](https://pastebin.com/PvSmHkBQ).

I'm bad at assembly but i made these tries:
`index += ethType.Length;` is translated as `mov r12d,dword ptr [rsp+4Ch]`
`index += 2;` is translated as `mov r12d,dword ptr [rsp+4Ch]`
`index += 3;` is translated as `add r12d,3 `
`index ++;` is translated as `inc r12d`

i really don't know what is the value at rsp+4Ch. it's strage that `index += ethType.Length;` and `index += 2;` have the same asm code.

`useLegacyJit=1` solved the issue. Also, change a random line sometimes solve the issue, for example use mac instead of madDst.

i'm using visual studio 15.0.0-RTW+26228.4
framework 4.7.02053
tested on framework 4.6.2 and 4.7.

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib

**Comment by pgavlin** [comment]
This is a dup of https://github.com/dotnet/coreclr/issues/11574. @russellhadley @briansull, I know this came up recently--can you provide details on which .NET Framework releases have the fix?

**Comment by briansull** [comment]
We haven't yet shipped a HotFix for this issue on the Desktop.
It will be include in the next HotFix roll up for Windows 10.

It is fixed in CoreCLR  by #11574.

**Comment by sandreenko** [comment]
@briansull I think this issue can be closed now?

**Comment by briansull** [comment]
Closing
