### ISSUE TITLE
Add checks for required packages/versions in build script 

### ISSUE THREAD

**Issue by xplicit** [dotnet/coreclr#132]
Most of the issues on linux for now are related to improper packages/versions installations on the build target machine. Some of them are very difficult to diagnose and understand what is needed to resolve the error. Please add package/version checks in cmake files to be sure that all required packages (like clang-3.5) are installed and the compilation/execution errors does not relate to wrong versions of the installed packages.

**Comment by kangaroo** [comment]
I think some significant strides have been made here not just on linux, but also OSX.  Can we close this out?

**Comment by MattWhilden** [comment]
As a cleanup task I'm going to speculatively close this out. If that's in error please let me know.
