### ISSUE TITLE
Add "core dump" support to the runtime.

### ISSUE THREAD

**Issue by OtherCrashOverride** [dotnet/coreclr#1321]
The runtime should have a feature to perform a "core dump" when an un-handled exception occurs.  This would assist debugging greatly in being able to view the state everything was in when the exception happened.

(Issue was previously part of #1311 )

**Comment by ayende** [comment]
Better yet, instead of tying this to unhandled exception, we want an API
that we can call that would give this.

Something like:

Environment.CreateCrashDump(path);

The idea is that we might want this not only for crashes. It would be
useful to ask our own software to get dumps from high cpu, high memory, etc.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by gkhanna79** [comment]
Environment.FailFast should result in Core dump generation. Is that not happening?

**Comment by stephentoub** [comment]
I get core dumps both for unhandled exceptions that crash the app and for Environment.FailFast, though the defaults on my system mean I need to use something like ```ulimit -c unlimited``` or else they won't be generated.

I assume @ayende though is asking for the ability to generate a dump without crashing the proces, ala "Create dump file" with Task Manager on Windows.

**Comment by lt72** [comment]
This shipped with 2.0

**Comment by ayende** [comment]
@lt72 How do I force a dump without killing the process, I've not been able to find it.

**Comment by lt72** [comment]
@mikem8361: does our tool allows creating a dump without killing the process?

**Comment by mikem8361** [comment]
You can attach gdb and run "generate-core-file <dumpname>".  I think you can detach without killing the process, but I'm not sure with gdb.

If you have the createdump enabled (see [doc](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md)) with the COMPlus_DbgEnableMiniDump=1 env var set before the program is run, you can send a SIGILL signal and that will tell coreclr to create a dump. This may not work in all situations and is not offically supported.
