### ISSUE TITLE
Add linux-arm64 to official builds

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#13212]
This is needed for validation now that we support the linux-arm64 RID.

**Comment by sdmaclea** [comment]
@jashook Is there anything I can do to help enable this?  I just looked at netci.groovy, but I do not see any relevant nuget publishing code.  

@dotnet/arm64-contrib @janvorli FYI

**Comment by janvorli** [comment]
@sdmaclea there are several things to do:
1. modify src/.nuget/dir.props to include OfficialBuildRID for linux-arm64 
2. modify the buildpipeline\pipelines.json by cloning the Linux-CrossBuild node (setting the arch to arm64 and maybe modifying the docker image - I'm not sure about that one though, maybe the existing one will work) and modifying all nodes that reference that new node.

I think that should be all, based on my experience with adding Alpine official builds.

**Comment by janvorli** [comment]
Yes, the docker image will need to be modified. It contains the crossrootfs for arm, we need to add one for arm64 (or create another docker image for arm64 only). Since the existing one is the official docker image we use for build, it would be probably the best if I updated it / created a new one myself.

**Comment by sdmaclea** [comment]
@janvorli  The normal linux-arm64 builds are using `ROOTFS_DIR=/opt/arm64-xenial-rootfs` w/o a docker image.  Is there any reason the same cannot be done here?

`src/.nuget/dir.props` looks correct already

**Comment by janvorli** [comment]
The build lab and ci are separate things. The build lab uses docker even for non-cross builds for Linux. See buildpipeline\DotNet-CoreClr-Trusted-Linux.json. It makes it easy to support various Linux distros in a uniform way.

**Comment by sdmaclea** [comment]
So are there scripts to build the docker images?

**Comment by janvorli** [comment]
Yes, there are Dockerfiles, but these are not in a public repo, since they are used for our lab purposes only.

**Comment by jashook** [comment]
@sdmaclea @janvorli I am currently working on adding the x86 rootfs to the cross docker image. I can add the arm64 cross tools as well.

**Comment by sdmaclea** [comment]
@jashook Thanks

**Comment by janvorli** [comment]
@jashook that would be great. Btw, I've noticed that the build-rootfs.sh has a wrong lldb-dev package for lldb3.9, it is lldb-3.9-dev while it needs to be liblldb-3.9-dev. Could you please update that too? And then build the crossfs with "arm64 xenial lldb3.9" parameters. I've verified locally that it works.

**Comment by jashook** [comment]
Sure i'll include you both on the pr.
