### ISSUE TITLE
DateTime.Parse/TryParse fails if the date and time uses the same separator

### ISSUE THREAD

**Issue by GeirGrusom** [dotnet/coreclr#1322]
The following code (in .NET 4.6) throws a FormatException:

	var dateFormat = new DateTimeFormatInfo
	{
		DateSeparator = ".",
		TimeSeparator = ".",
	};
	
	var textDate = new DateTime(2015, 1, 1).ToString(dateFormat); // 01.01.2015 00.00.00
	var reverse = DateTime.Parse(textDate, dateFormat); // Throws FormatException

Windows 10 for some reason changed the time separator for some locales (norwegian, finnish and serbian) which now breaks with Parse and TryParse.

edit: missed the format on the parse.

**Comment by weshaggard** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
This is known issue and not a new one. the parser is just thinking it is parsing a time (and not a date) and then decide it is not valid time. in general the Parse/TryParse is not guaranteeing the parse all possible strings and we always recommend to use ParseExact/TryParseExact to guarantee successful parsing.
Fixing the parser will not be trivial as it is written as finite state machine. we'll try to look if there is a safe way can fix this without breaking other cases

**Comment by jouniheikniemi** [comment]
Regarding the same issue in .NET Framework, see my blog post at http://www.heikniemi.net/hardcoded/2015/08/windows-10-breaks-net-date-parsing-in-certain-locales/. And now that the state machine has been fixed there, I hope the fix will flow down here as well :-)

**Comment by tarekgh** [comment]
The fix is already in the github side too. I didn't resolve this issue yet because I want to add some tests before closing the issue. let me know if you have any question.

**Comment by tarekgh** [comment]
The issue has been fixed and added the needed tests. closing the issue here.
