### ISSUE TITLE
Access GC settings at runtime

### ISSUE THREAD

**Issue by gregolsky** [dotnet/coreclr#13224]
We would like to access runtime GC settings programmatically. The only one we could find was the `ServerGarbageCollection` setting which is accessible through:
https://github.com/dotnet/coreclr/blob/release/2.0.0/src/mscorlib/src/System/Runtime/GcSettings.cs

Can we somehow obtain the value of `ConcurrentGarbageCollection` and `RetainVMGarbageCollection` settings at runtime?

**Comment by Maoni0** [comment]
you can know whether concurrent is enabled by checking for GCLatencyMode - if it's GCLatencyMode.Batch it means it's not enabled. This is exposed because you can change it at runtime.

can you please tell me what you would do with something like RetainVM?

**Comment by gregolsky** [comment]
I just need to print it out on startup of the app for informational
purposes.

pt., 4.08.2017, 21:19 użytkownik Maoni Stephens <notifications@github.com>
napisał:

**Comment by Maoni0** [comment]
Ahh, then I view this more like a general "how do we expose settings from the runtime" than a GC specific thing. @KrzysztofCwalina do you have an opinion for exposing runtime settings from APIs? settings can be RW or RO.

**Comment by Maoni0** [comment]
Apparently @KrzysztofCwalina has been having issues with GH notifications as well so he didn't see this - I just emailed him about it.

**Comment by KrzysztofCwalina** [comment]
I would simply open an API addition proposal with all the members you think we should add. You can put all the members in either GCSettings or RuntimeInformation, or any other type and we can have a discussion whats the best place for them at the API review. 

@terrajobst, could you point us to the doc describing the API addition process?

**Comment by KrzysztofCwalina** [comment]
the API additions/design process is at: https://aka.ms/apireview

**Comment by Maoni0** [comment]
@gregolsky haven't heard from you in a while. I will close the issue for now. if you still need help please re-open it.
