### ISSUE TITLE
dotnet restore timeout, would you please provide CDN accelerate for china?

### ISSUE THREAD

**Issue by netroby** [dotnet/coreclr#13220]
```
  Restoring packages for /home/huzhifeng/workspace/netroby/hwapp/hwapp.csproj...
  Failed to download package 'runtime.linux-x64.Microsoft.NETCore.App.2.0.0-preview2-25407-01' from 'https://api.nuget.org/v3-flatcontainer/runtime.linux-x64.microsoft.netcore.app/2.0.0-preview2-25407-01/runtime.linux-x64.microsoft.netcore.app.2.0.0-preview2-25407-01.nupkg'.
  The download of 'https://api.nuget.org/v3-flatcontainer/runtime.linux-x64.microsoft.netcore.app/2.0.0-preview2-25407-01/runtime.linux-x64.microsoft.netcore.app.2.0.0-preview2-25407-01.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.
  Failed to download package 'runtime.linux-x64.Microsoft.NETCore.App.2.0.0-preview2-25407-01' from 'https://api.nuget.org/v3-flatcontainer/runtime.linux-x64.microsoft.netcore.app/2.0.0-preview2-25407-01/runtime.linux-x64.microsoft.netcore.app.2.0.0-preview2-25407-01.nupkg'.
  The download of 'https://api.nuget.org/v3-flatcontainer/runtime.linux-x64.microsoft.netcore.app/2.0.0-preview2-25407-01/runtime.linux-x64.microsoft.netcore.app.2.0.0-preview2-25407-01.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.

```

I came from china. I try to develop and run dotnet app code.

But i have trouble to get restore work.

Would you please add CDN accelerate for china?

**Comment by janvorli** [comment]
@netroby what is your Linux distro? We have seen a similar problem on Fedora 24 in the past and it was caused by a non up to date NSS library. `dnf upgrade nss` fixed the problem. So if you have Fedora 24 too, you might try this.

**Comment by ygc369** [comment]
@netroby 
支持。

**Comment by netroby** [comment]
I am using archlinux x64, so the nss may be very new.

```bash
core/nss 3.31-3
    Network Security Services

```

The VSCode provided cdn for china.It's amazing fast.

**Comment by janvorli** [comment]
@netroby would you be able to try if you have the same problem with Ubuntu (14.04, 16.04 or 16.10) on a machine connected to the same network? I'd like to figure out if the problem is archlinux specific or not.

**Comment by netroby** [comment]
Have no ubuntu in hand.

**Comment by janvorli** [comment]
Ok, let me try it locally on an archlinux x64 in a VM.

**Comment by benaadams** [comment]
[Changes to NuGet.org service management, and performance improvements in China](https://blog.nuget.org/20170907/Changes-to-NuGet-dot-org-service-management-and-performance-improvements-in-China.html)

> We have been actively investigating solutions to this problem. Based on our tests, developers in China should see up to 30x improvement in package download times and on average, a 10x improvement in overall package restore time. The solution requires us to co-locate our blob storage in China and use a local CDN provider to serve package requests. As a result, in order to implement this solution and better serve the global .NET community, the .NET Foundation will transfer ownership of the NuGet.org service to Microsoft.

**Comment by netroby** [comment]
Thanks for you great help. it really helpful for us. thanks .really thanks.
