### ISSUE TITLE
Regression / Test failing CI JIT_Methodical._tailcall_v4_hijacking_hijacking_._tailcall_v4_hijacking_hijacking_cmd

### ISSUE THREAD

**Issue by joshfree** [dotnet/coreclr#13235]
https://github.com/dotnet/coreclr/pull/13189

`D:\j\workspace\debug_windows---0fe1a1b1\bin\tests\Windows_NT.x64.Debug\TestWrappers\JIT.Methodical\JIT.Methodical.XUnitWrapper.cs(130587): error : JIT_Methodical._tailcall_v4_hijacking_hijacking_._tailcall_v4_hijacking_hijacking_cmd [FAIL] [D:\j\workspace\debug_windows---0fe1a1b1\tests\runtest.proj]`

https://ci.dot.net/job/dotnet_coreclr/job/release_uwp6.0/job/debug_windows_nt_prtest/48/testReport/JIT_Methodical/_tailcall_v4_hijacking_hijacking_/_tailcall_v4_hijacking_hijacking_cmd/

```
Stacktrace

MESSAGE:
\ncmdLine:D:\\j\\workspace\\debug_windows---0fe1a1b1\\bin\\tests\\Windows_NT.x64.Debug\\JIT\\Methodical\\tailcall_v4\\hijacking\\hijacking.cmd Timed Out\r\n\n\nReturn code: -100\nRaw output file: D:\\j\\workspace\\debug_windows---0fe1a1b1\\bin\\tests\\Windows_NT.x64.Debug\\Reports\\JIT.Methodical\\tailcall_v4\\hijacking\\hijacking.output.txt\nRaw output:\nBEGIN EXECUTION\r\n \"D:\\j\\workspace\\debug_windows---0fe1a1b1\\tests\\..\\bin\\tests\\Windows_NT.x64.Debug\\Tests\\Core_Root\\corerun.exe\" hijacking.exe \r\n\ncmdLine:D:\\j\\workspace\\debug_windows---0fe1a1b1\\bin\\tests\\Windows_NT.x64.Debug\\JIT\\Methodical\\tailcall_v4\\hijacking\\hijacking.cmd Timed Out\r\nTest Harness Exitcode is : -100\r\n\nTo run the test:\n> set CORE_ROOT=D:\\j\\workspace\\debug_windows---0fe1a1b1\\bin\\tests\\Windows_NT.x64.Debug\\Tests\\Core_Root\n> D:\\j\\workspace\\debug_windows---0fe1a1b1\\bin\\tests\\Windows_NT.x64.Debug\\JIT\\Methodical\\tailcall_v4\\hijacking\\hijacking.cmd\n\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at JIT_Methodical._tailcall_v4_hijacking_hijacking_._tailcall_v4_hijacking_hijacking_cmd() in D:\j\workspace\debug_windows---0fe1a1b1\bin\tests\Windows_NT.x64.Debug\TestWrappers\JIT.Methodical\JIT.Methodical.XUnitWrapper.cs:line 130587
```

category:correctness
theme:testing
skill-level:intermediate
cost:medium

**Comment by RussKeldorph** [comment]
Does not repro.  Will investigate if timeouts continue to happen.

**Comment by janvorli** [comment]
Another instance of the error happened today:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/debug_windows_nt_prtest/11186/testReport/junit/JIT_Methodical/_tailcall_v4_hijacking_hijacking_/_tailcall_v4_hijacking_hijacking_cmd/

**Comment by mikedn** [comment]
And another one: https://ci.dot.net/job/dotnet_coreclr/job/master/job/debug_windows_nt_prtest/11575/testReport/junit/JIT_Methodical/_tailcall_v4_hijacking_hijacking_/_tailcall_v4_hijacking_hijacking_cmd/

**Comment by AndyAyersMS** [comment]
I can't find any failure reports on this in the last 18 months or so. Suggest we just close.
