### ISSUE TITLE
Repeated http requests get stuck and cause client-side timeout

### ISSUE THREAD

**Issue by myarichuk** [dotnet/coreclr#13247]
Repeated http calls get stuck and timeout after one or two requests when executed in a 4.6.1 project that references a netstandard 2.0 project.
On my end, I've reproduced it here --> https://github.com/myarichuk/TestWebRequestGettingStuck
(the steps to reproduce are in the readme)
It reproduces each run reliably.

It looks like a bug.

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#23012
