### ISSUE TITLE
dbgshim.dll!RegisterForRuntimeStartup can incorrectly fail with E_ACCESSDENIED on Windows

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#13282]
RegisterForRuntimeStartup is requesting TOKEN_READ access when it should request TOKEN_QUERY access. 

Here is the line of code with the bug: https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/utilcode/securityutil.cpp#L339

This prevents RegisterForRuntimeStartup from working correctly with Azure Service Fabric local simulator processes.

**Comment by lt72** [comment]
Are the local simulatot processes an internal testing or a production scenario?

**Comment by gregg-miskelly** [comment]
That depends on your definition of 'production' -- this is how customers develop Azure Service Fabric applications on their dev box's. The problem might also exist with in-the-cloud debugging, but I am not sure if such a feature exists for Service Fabric.

**Comment by karelz** [comment]
BTW: I recommend to keep servicing issues opened, until they are merged into 2.0 servicing branch.

**Comment by Petermarcu** [comment]
This is approved for checkin when the branch is open for 2.0.2.

**Comment by Petermarcu** [comment]
This was merged for 2.0.1. Closing now.
