### ISSUE TITLE
Jit: Long method Jit time for ImmutableList.Enumerator.Dispose

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#13329]
```
JitTime 
(msec)	ILSize	NativeSize
17.4        74         163	

Method
System.Collections.Immutable.ImmutableList1+Enumerator[System.Collections.Generic.KeyValuePair2[System.__Canon,System.__Canon]].Dispose()

BG    Module
JIT   System.Collections.Immutable.dll
```

Corefx issue https://github.com/dotnet/corefx/issues/23125
MsBuild issue https://github.com/Microsoft/msbuild/issues/2419

/cc @davkean

**Comment by benaadams** [comment]
Method for reference

https://github.com/dotnet/corefx/blob/1fe52f7ff4e29462f75da9ae1c35d9789ad13709/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.Enumerator.cs#L150-L162

**Comment by RussKeldorph** [comment]
@AndyAyersMS Not clear this is actionable at this point, but assigning since you started looking.  Feel free to un-assign or close if there is nothing to do.

**Comment by AndyAyersMS** [comment]
Yeah, probably not actionable. So am going to close.
