### ISSUE TITLE
[ARM64] Assertion failed '(attr != EA_1BYTE) || !(tree->gtFlags & GTF_IND_UNALIGNED)'

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#13348]
crossgen of S.P.CoreLib is failing with:

Assertion failed '(attr != EA_1BYTE) || !(tree->gtFlags & GTF_IND_UNALIGNED)' in 'System.Runtime.CompilerServices.Unsafe:ReadUnaligned(byref):ubyte' (IL size 10)

**Comment by jashook** [comment]
Bin Searching for the bad pr.

**Comment by jkotas** [comment]
It is likely #13278. It added a few more calls of ReadUnaligned in CoreLib.

**Comment by jashook** [comment]
It is #13278 that caused it.

**Comment by AndyAyersMS** [comment]
Anyone planning on fixing this?

**Comment by jashook** [comment]
Yes, looking into it this morning.

**Comment by jashook** [comment]
Addressed with #13377
