### ISSUE TITLE
Undo workaround for https://github.com/dotnet/coreclr/issues/12592

### ISSUE THREAD

**Issue by yizhang82** [dotnet/coreclr#13344]
Once https://github.com/dotnet/coreclr/issues/12592 is fixed, Undo the following:
```
  # Disable incremental link due to incremental linking CFG bug crashing crossgen
  set(NO_INCREMENTAL_LINKER_FLAGS "/INCREMENTAL:NO")    
```

**Comment by MichalStrehovsky** [comment]
This has been fixed in VS 2017 Update 5, but let's keep this around for a bit longer until everyone is off the buggy versions.
