### ISSUE TITLE
Different code generated by checked vs. release RyuJIT for Guid.op_Inequality

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#13358]
Repro:

1. Build Windows x64 checked, inspect the code for `Guid.op_Inequality`. You should see:

```
mov      eax, dword ptr [rcx]
cmp      eax, dword ptr [rdx]
jne      ...
```

2. Build Windows x64 release, copy release clrjit.dll over to your checked build, inspect the code for `Guid.op_Inequality`. You should see less efficient code - the arguments are spilled to stack:

```
nop     dword ptr [rax+rax]
mov     qword ptr [rsp+8],rcx
mov     qword ptr [rsp+10h],rdx
mov     rax,qword ptr [rsp+8]
mov     eax,dword ptr [rax]
mov     rdx,qword ptr [rsp+10h]
cmp     eax,dword ptr [rdx]
jne      ...
```

Expected: Both checked and release RyuJIT generate same efficient code.

**Comment by benaadams** [comment]
Is this more widespread?

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

Likely there is some side-effect in jit sources under DEBUG that shouldn't be under DEBUG. These kinds of errors are probably not common. More likely then not they lead to easily observable problems.

However, we really should be checking to ensure that debug, checked and release builds of the jit produce the exact same output. Doing this in volume requires automation, and right now there is no readily automatable way to disassemble from release jits. 

Such capability would be useful in its own right. The native image dumper seems like one possible route to solution, for volume disassembly of prejitted code.

There might also be some simple ways to tell that the code differs between jits without knowing exactly how it differs, for instance comparing the native code sizes recorded in jit event trace records.

**Comment by BruceForstall** [comment]
@AndyAyersMS @dotnet/jit-contrib We used to have internal automation to check for chk/ret differences. It should be possible to do this with SuperPMI (e.g., with the internal desktop collection, do SuperPMI asm diffs passing CHK and RET JIT from same sources; it will tell you functions that differ, then you might need to hook up the late disassembler to see the actual code)

**Comment by AndyAyersMS** [comment]
I'll take a look.

**Comment by AndyAyersMS** [comment]
Something like this might also make a good PGO/non-PGO validation test....

**Comment by AndyAyersMS** [comment]
I added some per-phase instrumentation to dump out number of blocks, statements, trees, and locals after each phase. Running over corelib, diffing CHK vs REL, and listing just the first phase that diverges gives the following:
```
JIT;Method;PhaseNum;Phase;Blocks;Stmts;Trees;Locals

CHK;Microsoft.Win32.OAVariantLib:ChangeType(struct,ref,short,ref):struct;11;Morph - Global;5;15;0;15
REL;Microsoft.Win32.OAVariantLib:ChangeType(struct,ref,short,ref):struct;11;Morph - Global;5;15;0;16

CHK;System.Diagnostics.Tracing.EventSource:Write(ref,struct,ref):this;11;Morph - Global;3;6;0;7
REL;System.Diagnostics.Tracing.EventSource:Write(ref,struct,ref):this;11;Morph - Global;3;6;0;8

CHK;System.IO.Stream:Write(struct):this;38;Optimize Valnum CSEs;11;20;178;29
REL;System.IO.Stream:Write(struct):this;38;Optimize Valnum CSEs;11;20;179;30

CHK;MemberInfoCache`1[__Canon][System.__Canon]:PopulateMethods(struct):ref:this;38;Optimize Valnum CSEs;79;225;1609;127
REL;MemberInfoCache`1[__Canon][System.__Canon]:PopulateMethods(struct):ref:this;38;Optimize Valnum CSEs;79;225;1604;128

CHK;MemberInfoCache`1[__Canon][System.__Canon]:PopulateConstructors(struct):ref:this;49;Global local var liveness;30;0;473;72
REL;MemberInfoCache`1[__Canon][System.__Canon]:PopulateConstructors(struct):ref:this;49;Global local var liveness;30;0;475;72

CHK;MemberInfoCache`1[__Canon][System.__Canon]:PopulateRtFields(struct,long,int,ref,byref):this;49;Global local var liveness;31;0;436;65
REL;MemberInfoCache`1[__Canon][System.__Canon]:PopulateRtFields(struct,long,int,ref,byref):this;49;Global local var liveness;31;0;438;65

CHK;MemberInfoCache`1[__Canon][System.__Canon]:PopulateLiteralFields(struct,ref,byref):this;38;Optimize Valnum CSEs;23;86;537;56
REL;MemberInfoCache`1[__Canon][System.__Canon]:PopulateLiteralFields(struct,ref,byref):this;38;Optimize Valnum CSEs;23;86;538;57

CHK;MemberInfoCache`1[__Canon][System.__Canon]:AddSpecialInterface(byref,struct,ref,bool):this;49;Global local var liveness;23;0;304;37
REL;MemberInfoCache`1[__Canon][System.__Canon]:AddSpecialInterface(byref,struct,ref,bool):this;49;Global local var liveness;23;0;305;37

CHK;MemberInfoCache`1[__Canon][System.__Canon]:PopulateInterfaces(struct):ref:this;38;Optimize Valnum CSEs;76;192;1452;105
REL;MemberInfoCache`1[__Canon][System.__Canon]:PopulateInterfaces(struct):ref:this;38;Optimize Valnum CSEs;76;192;1447;102

CHK;MemberInfoCache`1[__Canon][System.__Canon]:PopulateNestedClasses(struct):ref:this;38;Optimize Valnum CSEs;25;54;361;30
REL;MemberInfoCache`1[__Canon][System.__Canon]:PopulateNestedClasses(struct):ref:this;38;Optimize Valnum CSEs;25;54;362;31

CHK;MemberInfoCache`1[__Canon][System.__Canon]:PopulateEvents(struct,ref,ref,byref):this;38;Optimize Valnum CSEs;25;74;502;47
REL;MemberInfoCache`1[__Canon][System.__Canon]:PopulateEvents(struct,ref,ref,byref):this;38;Optimize Valnum CSEs;25;74;506;48

CHK;MemberInfoCache`1[__Canon][System.__Canon]:PopulateProperties(struct,ref,ref,ref,byref):this;38;Optimize Valnum CSEs;79;203;1343;108
REL;MemberInfoCache`1[__Canon][System.__Canon]:PopulateProperties(struct,ref,ref,ref,byref):this;38;Optimize Valnum CSEs;79;203;1338;109

CHK;System.Collections.Generic.ObjectEqualityComparer`1[Nullable`1][System.Nullable`1[System.__Canon]]:LastIndexOf(ref,struct,int,int):int:this;55;LSRA resolve;24;0;206;27
REL;System.Collections.Generic.ObjectEqualityComparer`1[Nullable`1][System.Nullable`1[System.__Canon]]:LastIndexOf(ref,struct,int,int):int:this;55;LSRA resolve;23;0;204;27

CHK;System.Collections.Generic.ObjectEqualityComparer`1[Nullable`1][System.Nullable`1[System.__Canon]]:IndexOf(ref,struct,int,int):int:this;55;LSRA resolve;24;0;204;27
REL;System.Collections.Generic.ObjectEqualityComparer`1[Nullable`1][System.Nullable`1[System.__Canon]]:IndexOf(ref,struct,int,int):int:this;55;LSRA resolve;23;0;202;27
```
Somewhat unexpectedly, `GUID.op_Inequality` is not listed. Not sure why just yet.

**Comment by AndyAyersMS** [comment]
@briansull reminded me that this behavior could also come from uninitialized values. The diversity of phases where CHK and REL diverge lends credence to that hypothesis.  That could also explain why I don't see the guid method in my list

Will start tracking these down, one by one...

**Comment by AndyAyersMS** [comment]
The first diff comes from `fgRetypeImplicitByRefArgs()` and was introduced in #10453.

Here `lvKeepType` is a stress-only field so setting it under `DEBUG` is reasonable, but the other two fields need to be set consistently in all build modes.

It might explain Jan’s diffs. It would give better codegen in CHK, but would not lead to buggy codegen in REL.

```C++
#ifdef DEBUG
            // This should not be converted to a double in stress mode,
            // because it is really a pointer
            varDsc->lvKeepType = 1;

            // The struct parameter may have had its address taken, but the pointer parameter
            // cannot -- any uses of the struct parameter's address are uses of the pointer
            // parameter's value, and there's no way for the MSIL to reference the pointer
            // parameter's address.  So clear the address-taken bit for the parameter.
            varDsc->lvAddrExposed     = 0;
            varDsc->lvDoNotEnregister = 0;

            if (verbose)
            {
                printf("Changing the lvType for struct parameter V%02d to TYP_BYREF.\n", lclNum);
            }
#endif // DEBUG
```
Will see what happens to my diff set above if I fix this.

**Comment by JosephTremoulet** [comment]
Yikes! Yes, the intent was definitely to clear `lvAddrExposed` and `lvDoNotEnregister` in all builds.

**Comment by AndyAyersMS** [comment]
My screening build doesn't see any diffs in corelib with this fixed. Will send out a PR and see what happens on desktop.
