### ISSUE TITLE
Cleanup on shutdown

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/coreclr#1335]
With `AppDomain` no longer supported in CoreCLR, we no longer have a `AppDomain.DomainUnload` event to hook into. What's the new Right Way to handle necessary cleanup that used to go there?

**Comment by ayende** [comment]
What about AppDomain.CurrentDomain.ProcessExit ?

**Comment by masonwheeler** [comment]
@ayende Sure looks like that's part of `AppDomain` too...

**Comment by whoisj** [comment]
Might have to go old school. 

```
int main(string[] args)
{
    try
    {
        // ...
    }
    finally
    {
        // clean up here
    }
}
```

Won't help a library much. Perhaps make your entry-point `IDisposable`?

**Comment by kouvel** [comment]
Using the dispose pattern is the only workaround that I'm aware of, a class library would require a call from consumers to do graceful cleanup, as finalizers are unreliable during shutdown. See dotnet/corefx#5205 for more details, it's is a proposal to add AssemblyLoadContext.Unload that would behave similarly to AppDomain.Unload in CoreCLR.

**Comment by kouvel** [comment]
Considering this a duplicate of dotnet/corefx#5205 and closing.
