### ISSUE TITLE
Math.Sin produces different results on CoreCLR and Full CLR

### ISSUE THREAD

**Issue by Thealexbarney** [dotnet/coreclr#13357]
Based on my testing, Math.Sin in CoreCLR commonly produces slightly different results than the sin functions in the Full CLR, and the GCC and MSVC C++ libraries do.

Here's a simple example:

````
using System;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            double a = -9.14252549579842144211739e-1;
            double b = Math.Sin(a);
            var aInt = BitConverter.DoubleToInt64Bits(a);
            var bInt = BitConverter.DoubleToInt64Bits(b);
            Console.WriteLine($"{aInt:x}");
            Console.WriteLine($"{bInt:x}");
        }
    }
}

````

Results:
`dotnet run -f net47`:

`bfed418e90175c7e`
`bfe958efe48e6dd7`

`dotnet run -f netcoreapp1.0`:

`bfed418e90175c7e`
`bfe958efe48e6dd6`

The results are the same with .NET Core 2.0.

It's only one step off, but I would have expected the results to be the same on both frameworks running on the same machine.
The difference can cause slight issues when a program is expected to produce the same output when running on either .NET Core or .NET Framework.

**Comment by jkotas** [comment]
Similar issue discussed in https://github.com/dotnet/coreclr/issues/12737

**Comment by jkotas** [comment]
.NET Core produces more precise results.
