### ISSUE TITLE
CPUGroupInfo class on Linux when Hyper-Threading is on

### ISSUE THREAD

**Issue by helloguo** [dotnet/coreclr#13383]
For the machine with two sockets and 26 physical cores per socket, Class `CPUGroupInfo ` assumes Processors/Numa Node/CPU Group/Number are like this when Hyper-Threading is on:

```
cpu [0,51], Node 0, Group 0, Number [0,51]
cpu [52,103], Node 1, Group 1, Number [0,51]
```

The data structure `m_CPUGroupInfoArray `  is initialized based on the above assumption. Some functions using data structure `m_CPUGroupInfoArray `  such as `GetGroupForProcessor(), CalculateCurrentProcessorNumber(), InitCPUGroupInfoArray(), ChooseCPUGroupAffinity()` are used by GC or ThreadPool.

However, the above assumption is only true for Windows or Linux with HT off. For Linux with HT on, Processors/NumaNode/CPUGroup/Number are as shown below:
```
cpu [0,25], Node 0, Group 0, Number [0,25]
cpu [26,51], Node 1, Group 1, Number [0,25]
cpu [52,77], Node 0, Group 0, Number [26,51]
cpu [78,103], Node 1, Group 1, Number [26,51]
```

Need to fix `CPUGroupInfo  `class so that NUMA can be used properly.

**Comment by janvorli** [comment]
@helloguo could you please dump me the  /sys/devices/system/node/node0/cpumap and  /sys/devices/system/node/node1/cpumap on that machine?

**Comment by helloguo** [comment]
![capturemap](https://user-images.githubusercontent.com/18431130/29337907-fd8782fc-81c7-11e7-9192-64e379b5cc9a.PNG)

**Comment by janvorli** [comment]
We are currently using the processor number that Linux assigns to each core. As you can see, the cpumap matches the structure we generate. Node 0 contains processors 0..25 and 52..77 and we assign them to group 0 with numbers 0..51. Similar to node 1 - it contains processors 26..51 and 78..103 and we assign them to group 1 with numbers 0..51.
I actually wonder why would the m_CPUGroupInfoArray be incorrect. Looking at the code that generates it, it only uses ActiveProcessorCount and ActiveProcessorMask from each pRecord->Group.GroupInfo[i] and doesn't seem to do anything with the cpu indexes. I assume that  pRecord->Group.GroupInfo[i].ActiveProcessorCount is 52 and pRecord->Group.GroupInfo[i].ActiveProcessorMask is 0x000FFFFFFFFFFFFF. Is that not true?

**Comment by helloguo** [comment]
For example,  `CPUGroupInfo::GetGroupForProcessor(WORD processor_number, WORD* group_number, WORD* group_processor_number)`. https://github.com/dotnet/coreclr/blob/master/src/utilcode/util.cpp#L1121. when the processor_number 26 is passed in, group_number should be 1 and group_processor_number should be 0. However, based on the current implementation, group_number returns 0 and group_processor_number returns 26?

Another example is` CPUGroupInfo::InitCPUGroupInfoRange()` https://github.com/dotnet/coreclr/blob/master/src/utilcode/util.cpp#L1012, which sets         `m_CPUGroupInfoArray[i].begin` and  `m_CPUGroupInfoArray[i].end`. It assumes CPUGroupRange is consecutive. However, for group 0 the CPUGroupRange should be [0,25] and [52,77].

**Comment by janvorli** [comment]
@helloguo of course, if my assumption that I've mentioned above that pRecord->Group.GroupInfo[i].ActiveProcessorCount is 52 and pRecord->Group.GroupInfo[i].ActiveProcessorMask is 0x000FFFFFFFFFFFFF is not correct and we generate something else, then that would be a problem.

**Comment by helloguo** [comment]
@janvorli I should put more context to make it clear :)

I see some run to run variation when I run TechEmpower plaintext multiple times.  I suspect it's due to the unbalanced GC heaps on Linux. For example, `balance_heaps `function in gc.cpp ifdef out the following code for Linux. So I'm doing a prototype so that these codes can also be executed for Linux.

```
#if !defined(FEATURE_PAL)
                    if (CPUGroupInfo::CanEnableGCCPUGroups())
                    {   //only set ideal processor when max_hp and org_hp are in the same cpu
                        //group. DO NOT MOVE THREADS ACROSS CPU GROUPS
                        uint16_t org_gn = heap_select::find_cpu_group_from_heap_no(org_hp->heap_number);
                        uint16_t max_gn = heap_select::find_cpu_group_from_heap_no(max_hp->heap_number);
                        if (org_gn == max_gn) //only set within CPU group, so SetThreadIdealProcessor is enough
                        {   
                            uint16_t group_proc_no = heap_select::find_group_proc_from_heap_no(max_hp->heap_number);

                            GCThreadAffinity affinity;
                            affinity.Processor = group_proc_no;
                            affinity.Group = org_gn;
                            if (!GCToOSInterface::SetCurrentThreadIdealAffinity(&affinity))
                            {
                                dprintf (3, ("Failed to set the ideal processor and group for heap %d.",
                                            org_hp->heap_number));
                            }
                        }
                    }
                    else 
                    {
                        uint16_t proc_no = heap_select::find_proc_no_from_heap_no(max_hp->heap_number);

                        GCThreadAffinity affinity;
                        affinity.Processor = proc_no;
                        affinity.Group = GCThreadAffinity::None;

                        if (!GCToOSInterface::SetCurrentThreadIdealAffinity(&affinity))
                        {
                            dprintf (3, ("Failed to set the ideal processor for heap %d.",
                                        org_hp->heap_number));
                        }
                    }
#endif // !FEATURE_PAL
```

 `find_cpu_group_from_heap_no`() uses data structure `heap_no_to_cpu_group[]`, which is initialized by `heap_select::set_cpu_group_for_heap(heap_number, gn);`. `gn` is generated by `CPUGroupInfo::GetGroupForProcessor((uint16_t)heap_number, &gn, &gpn);` 

```
/*static*/ void CPUGroupInfo::GetGroupForProcessor(WORD processor_number,
		                         WORD* group_number, WORD* group_processor_number)
{
    LIMITED_METHOD_CONTRACT;

#if !defined(FEATURE_REDHAWK) && (defined(_TARGET_AMD64_) || defined(_TARGET_ARM64_))
    WORD bTemp = 0;
    WORD bDiff = processor_number - bTemp;

    for (WORD i=0; i < m_nGroups; i++)
    {
        bTemp += m_CPUGroupInfoArray[i].nr_active;
        if (bTemp > processor_number)
        {
            *group_number = i;
            *group_processor_number = bDiff;
            break;
        }
        bDiff = processor_number - bTemp;
    }
#else
    *group_number = 0;
    *group_processor_number = 0;
#endif
}
```

From the above code, we can see if the `(uint16_t)heap_number` is 25 or 26, it will give us group 0. But from numa.cpp's view, heap_number 25 should be group 0 and heap_number 26 should be group 1. Let's assume `org_hp `is 25 and `max_hp `is 26, then balance_heaps() will think they are in same group. So `balance_heap()` will update the `GCThreadAffinity`. But actually, we'd better no do this in this situation.

**Comment by janvorli** [comment]
I am sorry for the late response, I got distracted by other work. Even with this detailed description, I don't see the problem. I think that I must be missing something. 
In your example above, when the  org_hp is 25 and max_hp is 26, they really are in the same group. The heap 25 is attached to Unix OS processor 25 and the heap 26 to Unix OS processor 52. They are in the same NUMA node.
You assume that the heap_number corresponds to the processor index that Unix OS uses. But I don't see why it would need to be that way. 
Now looking at the source again, it seems that you must have added implementation of SetThreadIdealProcessorEx to PAL to enable setting the affinity in gc_heap::balance_heap. Can you please show me what is the implementation of that function?

**Comment by helloguo** [comment]
> You assume that the heap_number corresponds to the processor index that Unix OS uses. But I don't see why it would need to be that way.

I agree with you. The heap_number does not necessarily correspond to the processor index that Unix OS uses. But when I test my prototype (you can check it out here https://github.com/dotnet/coreclr/pull/13606), I print out the cpu, which the current thread is running on by using `pthread_getaffinity_np`. I also print out the cpu, which the thread wants to set affinity to. Sometimes they are in different NUMA nodes (for example, one is 95 and the other one is 17). Then I'm not sure if the CPUGroupInfo class works with NUMA properly.

**Comment by janvorli** [comment]
@helloguo thank you for the additional details. I'll take a look at your prototype and walk through the CPUGroupInfo implementation again to see if I can spot something. It would also be helpful if you could instrument the SetThreadIdealProcessorEx to print the contents of lpIdealProcessor and and the value that we would generate into the lpPreviousIdealProcessor at the point where the SetThreadIdealProcessorEx would move the processor between NUMA nodes.

Actually, looking at your prototype, I can see a problem there. You assign the lpPreviousIdealProcessor before using the value from the lpIdealProcessor. If these two pointers point to the same structure, which actually happens in GCToOSInterface::SetCurrentThreadIdealAffinity, then it would not move the thread anywhere.

**Comment by helloguo** [comment]
> You assign the lpPreviousIdealProcessor before using the value from the lpIdealProcessor.

Thank you for pointing it out. Will fix it.

>  If these two pointers point to the same structure, which actually happens in GCToOSInterface::SetCurrentThreadIdealAffinity, then it would not move the thread anywhere.

In the current prototype,` success = !!SetThreadIdealProcessorEx(GetCurrentThread(), &proc, NULL);` is the only place to call `SetThreadIdealProcessorEx`. In this case, the `lpPreviousIdealProcessor` is NULL. So I guess it's fine in this case. Anyway, I will fix it and see what's going on.

**Comment by janvorli** [comment]
@helloguo have you investigated this issue any further? Have you tried my suggestion in the comment https://github.com/dotnet/coreclr/issues/13383#issuecomment-325325349 above about printing some stuff in the SetThreadIdealProcessorEx ?

**Comment by helloguo** [comment]
@janvorli I did not have a chance to do that yet. I will do that and let you know what's going on.

**Comment by helloguo** [comment]
@janvorli I dump out more information with https://github.com/dotnet/coreclr/pull/13606, which shows lpPreviousIdealProcessor's Group is same as lpIdealProcessor's Group. I guess my previous prototype had bugs as you pointed it out.

I'm going to close this issue.
