### ISSUE TITLE
JIT: some instruction sizes mis-estimated on x64

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#13398]
Known cases:

- GT_LABELs via emitIns_R_L -- size is estimated before the relocation flags are applied
- reg-reg movs via emitInsSizeRR -- REX prefix can be counted twice

I believe the intention is that these mis-estimates are tolerable (the true size may not be knowable and the actual size is known later) but they expose other issues.

The label case leads to an error in the code recording the inline pinvoke return address, as the jit stores the address one (or more) bytes into the return instruction instead of the address of the instruction. Not clear if this causes any observable problems as being close enough to the right value may be sufficient.

I have plausible fixes for both that I'll send out in a PR shortly.

This was discovered while looking for CHK/RET codegen differences.

cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Seems like perhaps we should make sure the underlying issues are fixed before we "hide" them by fixing the size estimations.

In fact, perhaps we should add a stress mode that always over-estimates instruction sizes by 1 or more (or does so for some subset of instructions), to tease out other potential issues with the emission adjustment code.

**Comment by AndyAyersMS** [comment]
Sounds like a sensible plan, though note for the GT_LABEL/LEA case the mis-estimates arguably lead to incorrect code.

**Comment by AndyAyersMS** [comment]
Also the mis-estimation is (so far) consistent between CHK and REL, so it should be simple to instrument the jit and track down more cases that we ought to fix.
