### ISSUE TITLE
JIT: compQuirkForPPP can cause CHK/REL gc info diffs

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#13407]
This quirk resizes a local struct from 32 bytes to 64 bytes, but does not make corresponding changes to the GC info for the struct. 

So the GC tracking emitted for the last 4 pointer-sized "fields" of this struct is somewhat arbitrary as the jit reads off the end of the supplied GC info into unrelated data. 

In my particular case some of the extra fields were tracked in CHK and not in REL, but this bug could easily lead to non-gc pointer fields being reported as GC fields in REL.

cc @briansull, @dotnet/jit-contrib

**Comment by mikedn** [comment]
@dotnet/jit-contrib Is this quirk for PPP thing still needed? It can also cause faults in rare circumstances:

```C#
struct PPP {
    public long a, b, c, d;
}

static PPP s_ppp;

[MethodImpl(MethodImplOptions.NoInlining)]
static void Sink(ref PPP s) {
}

static void Test() {
    PPP ppp = s_ppp;
    Sink(ref ppp);
}
```
The generated code is:
```asm
;  V00 loc0         [V00    ] (  2,  2   )  struct (64) [rsp+0x20]   do-not-enreg[XSB] must-init addr-exposed ld-addr-op
;  V01 OutArgs      [V01    ] (  1,  1   )  lclBlk (32) [rsp+0x00]   "OutgoingArgSpace"
;
; Lcl frame size = 96
...
       48B9802AF4CAA7010000 mov      rcx, 0x1A7CAF42A80
       488B09               mov      rcx, gword ptr [rcx]
       C5FA6F4108           vmovdqu  xmm0, xmmword ptr [rcx+8]
       C5FA7F442420         vmovdqu  xmmword ptr [rsp+20H], xmm0
       C5FA6F4118           vmovdqu  xmm0, xmmword ptr [rcx+24]
       C5FA7F442430         vmovdqu  xmmword ptr [rsp+30H], xmm0
       C5FA6F4128           vmovdqu  xmm0, xmmword ptr [rcx+40]
       C5FA7F442440         vmovdqu  xmmword ptr [rsp+40H], xmm0
       C5FA6F4138           vmovdqu  xmm0, xmmword ptr [rcx+56]
       C5FA7F442450         vmovdqu  xmmword ptr [rsp+50H], xmm0
       488D4C2420           lea      rcx, bword ptr [rsp+20H]
       E83FF0FFFF           call     C:sink(byref)
```
Because the amount of bytes to copy is taken from the destination variables, 64 bytes are copied from source instead of 32. If you're really unlucky and the source is at the end of the page that's followed by an unallocated page...

**Comment by BruceForstall** [comment]
Looks like a real bug to me, that probably deserves its own issue.

Looks like @briansull added it over 3 years ago. I don't remember the details. @briansull Was it a desktop only quirk? Can we put it under `#if !defined(FEATURE_CORECLR)`? Or should this issue just get fixed?
