### ISSUE TITLE
[RyuJIT/armel]  Assertion failed '(op2 == idx) || (op2->gtEffectiveVal() == idx)'

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#13422]
Failed Tests

- JIT/SIMD/VectorConvert_r/VectorConvert_r.sh
- JIT/SIMD/VectorConvert_ro/VectorConvert_ro.sh

**Comment by BruceForstall** [comment]
These fail for me in a Windows RyuJIT/arm32 run.
