### ISSUE TITLE
Sharing build scripts between corefx and coreclr

### ISSUE THREAD

**Issue by benpye** [dotnet/coreclr#1344]
Both coreclr and corefx have native code now, and share scripts such as `gen-buildsys-clang.sh` and have a very similar `build.sh`, I think it would be good to have a common `corebuild` repo or such, in which these scripts and the cross compilation support could be maintained, to reduce duplication. corefx and coreclr could then be cloned into that directory and only contain the cmake files for themselves, and no scripts for building etc. It does add another step to building either locally, but I can't see another way of removing the duplication.
#1343 improves the complexity of these scripts and so it has come to my attention, currently corefx lacks cross compile support for the native components, and with the current system, we'd have to duplicate the coreclr cross building.

**Comment by am11** [comment]
:+1: for this idea. 
Might also make sense to move all the build-related machinery to a directory (say 'tools-for-core') at root of buildtools repo and add buildtools as a submodule to core[clr/fx]. Then in build.[cmd/sh] of each repo:

```bash
# an example bash script for coreclr/build.sh

# fetch buildtools if directory does not exists
if [ ! -d "buildtools" ]; then
  if which git >/dev/null; then
    git clone //github.com/dotnet/buildtools
    # alternatively:   git submodule update --init
  elif which wget >/dev/null; then
    wget -qO- -O buildtools.zip https://github.com/dotnet/buildtools/archive/master.zip && \
    unzip buildtools.zip && \
    rm buildtools.zip 
  else
    # try curl or die with message
   echo "Something went wrong! :("
   exit 404
  fi
fi

# forward all CLI args to the unified script
./buildtools/tools-for-core/build.sh "$a"
```

**Comment by benpye** [comment]
Don't submodules pin a specific version... only reason I'd be reluctant to suggest that, and you end up having a copy in both corefx and coreclr if you checkout both.

**Comment by am11** [comment]
> Don't submodules pin a specific version... 

Yup, it points to a specific commit. You can also `cd` into submodule directory and run `git pull --rebase origin master` to fetch the latest. But it is probably considered as a good practice (I personally follow) to stick to the tested commit of upstream, which downstream is warranting.

I agree about ending up having a copy in all dependent (downstream) repos, but it can be avoided by just dropping `--recursive` argument from `git clone` command:

```bash
git clone https://github.com/dotnet/coreclr
# will only clone coreclr without any submodule
git clone https://github.com/dotnet/coreclr --recursive
# will clone coreclr with all the immediate and the nested submodules
```

If the repo was initially cloned without submodule and the user changed their mind later, it can still be done without needing to re-clone, like so:

```bash
# sometime after cloning the downstream without submodules
cd coreclr
git submodule update --init
```

**Comment by benpye** [comment]
But then your other project (say corefx if coreclr was cloned with the build scripts), would have to be configured to look in coreclr for the build scripts? What I suggested is somewhat like LLVM/Clang, you clone clang into the LLVM repository which, same for things like libc++abi and the like. I do understand the merits of submodules, but I'm not sure they are the right solution here. I suspect whatever we do will have to translate in some way to the TFS side as everything in mirrored too, and that could be another sticking point for submodules but could do with someone from MS to give a little more insight there.

**Comment by ellismg** [comment]
I really don't think we should be adopting sub-modules.  Taking aside the TFS Mirror issues (which is just a technically problem that we can solve at the end of the day if this was the right direction) it seems like we'd be adding a great deal of complexity for little gain.

I think the general approach we have been taking is to try to push shared logic into buildtools, and have a small wrapper which acquires nuget, restores buildtools and then jumps into some logic in buildtools.  I think it would be best to explore that direction.

I agree that we are building up debt here and it would be good to pay it down.  With both CoreFX and CoreCLR wanting to build native and managed code, it seems like we may need to start thinking about how buildtools can handle native stuff.

**Comment by jkotas** [comment]
This was solved by https://github.com/dotnet/arcade/. The shared scripts are in the https://github.com/dotnet/coreclr/tree/master/eng and synchronized across all repos.
