### ISSUE TITLE
ThrowExceptionFromHR vs GetExceptionFromHR : different results

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/coreclr#13460]
Hi

The exception thrown by `ThrowExceptionFromHR` is different from the exception that we get from `GetExceptionFromHR`. However, [msdn ](https://msdn.microsoft.com/en-us/library/t8t3ykxc(v=vs.110).aspx)documentation says :

`Use the GetExceptionForHR method to get an Exception based on an HRESULT without having to call the ThrowExceptionForHR method and catch the exception.`

Steps to reproduce :

```
mkdir exception
cd exception
dotnet new xunit

# edit UnitTest1.cs file :

E:\work\dotnetvstest\dotnetxunit>cat UnitTest1.cs
using System;
using Xunit;
using System.Runtime.InteropServices;

namespace dotnetxunit
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            int errorCode = -2146231029;
            Exception hrException = Marshal.GetExceptionForHR(errorCode);

            try
            {
                Marshal.ThrowExceptionForHR(errorCode);
            }
            catch (COMException)
            {
                // GetExceptionForHR should also give me COMException
                Assert.NotEqual(null, hrException as COMException);
            }
            catch (Exception)
            {
                // hrException should not give me COMException
                Assert.Equal(null, hrException as COMException);
            }
        }
    }
}


Test run for E:\work\dotnetvstest\dotnetxunit\bin\Debug\netcoreapp2.0\dotnetxunit.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-dev
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.3230093]   Discovering: dotnetxunit
[xUnit.net 00:00:00.4327966]   Discovered:  dotnetxunit
[xUnit.net 00:00:00.4702397]   Starting:    dotnetxunit
[xUnit.net 00:00:00.6154191]     dotnetxunit.UnitTest1.Test1 [FAIL]
[xUnit.net 00:00:00.6177655]       Assert.NotEqual() Failure
[xUnit.net 00:00:00.6179389]       Expected: Not null
[xUnit.net 00:00:00.6180426]       Actual:   null
[xUnit.net 00:00:00.6199349]       Stack Trace:
[xUnit.net 00:00:00.6222026]         E:\work\dotnetvstest\dotnetxunit\UnitTest1.cs(22,0): at dotnetxunit.UnitTest1.Test1()
[xUnit.net 00:00:00.6432646]   Finished:    dotnetxunit
Failed   dotnetxunit.UnitTest1.Test1
Error Message:
 Assert.NotEqual() Failure
Expected: Not null
Actual:   null
Stack Trace:
   at dotnetxunit.UnitTest1.Test1() in E:\work\dotnetvstest\dotnetxunit\UnitTest1.cs:line 22

Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.3305 Seconds

E:\work\dotnetvstest\dotnetxunit>
```

Expected :

Test should have passed.
`GetExceptionForHR` should return `COMException` for unknown `HResult`.

Other details :
```
dotnet --version
2.0.0-preview2-006497
```

I have reproduce the issue in both Windows and Ubuntu 64 bit.

**Comment by jkotas** [comment]
cc @tijoytom

**Comment by danmosemsft** [comment]
The type of `hrException` here is just Exception.

**Comment by ashishnegi** [comment]
@danmosemsft yes, you are correct. The type of `hrException` here is just `Exception`.

**Comment by ashishnegi** [comment]
Also, if we do COM interop, in case of unknown HResult, we should get COMException.
However, we just get System.Exception in coreclr.
I think both issues are related.

**Comment by tijoytom** [comment]
@jkotas @ashishnegi @danmosemsft 
I did some digging around and it's this change that broke this https://github.com/dotnet/coreclr/commit/16fc3005c085212f6e700a0df8ff7f36c1ea535b

This change was made to fix a test issue where a test checks  if  HResult 0x8000000e maps to a System.InvalidOperationException. Bryan who made the checkin reversed the flag passed to "GetKindFromHR". Also the whole premise of the change itself seems to be wrong , it says   "The test checks that the HResult 0x8000000e maps to a System.InvalidOperationException but we get "A method was called at an unexpected time" , Now HResult 0x8000000e  do not map to System.InvalidOperationException , it's E_ILLEGAL_METHOD_CALL and we were throwing  the right exception. So in a nutshell , we changed the product to fix a wrong test.

**Comment by danmosemsft** [comment]
Keeping open to track adding a test

**Comment by tijoytom** [comment]
CoreFX Test  https://github.com/dotnet/corefx/pull/23521

**Comment by ashishnegi** [comment]
@danmosemsft Since this was a bug, I am also seeing another potential similar issue. Just want to confirm before opening an issue.

Issue is :

When doing COM Interop in coreclr in windows, we are getting System.Exception for HResults for which net framework 4.5.1 gives COMException.
Is runtime now not giving COMException ? In that case, above behavior is intended.
If not, will this fix also correct above issue ?
Otherwise, I will file another bug with more details.

**Comment by danmosemsft** [comment]
@ashishnegi can you pick up the latest build of 2.1 from https://github.com/dotnet/cli (check it contains fix above) and try your sceario?
If it still reproes, please open a new issue and we will take a look.

**Comment by ashishnegi** [comment]
@danmosemsft I don't see any released 2.1 in https://github.com/dotnet/cli/releases or tags or any branch `2.1` in cli. Can you point to right binaries ?

**Comment by danmosemsft** [comment]
@ashishnegi here https://github.com/dotnet/cli#installers-and-binaries is a table with 'latest daily build' marked 2.1.0.xxxx... you want something from that table. 
Eg I would typically get https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.zip unzip it and put it into c:\dotnet (say). Then in that folder I would make a folder `proj` and cd into that and do `..\dotnet new console` (taking care to run the dotnet.exe out of the folder I made not one in the path). And so forth. This is a nice way to use an isolated .NET Core which you can remove by just rmoving the folder.

**Comment by mjsabby** [comment]
We just hit this bug in 2.0.5 when porting Bing.com code, can we get this ported to 2.0? @danmosemsft @jkotas what is the procedure for that?

**Comment by jkotas** [comment]
This was ported to 2.0.x servicing already: https://github.com/dotnet/coreclr/pull/15735 . It should be in 2.0.6 update.
