### ISSUE TITLE
Undo "goto return" works-around

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/coreclr#13466]
Issue to track following up on feedback at https://github.com/dotnet/coreclr/pull/13314#issuecomment-321586182 -- now that the JIT tries to pull early returns out of loops, find the code where `goto` has been added to work around its prior inability to do so, revert, and make sure the JIT gives the desired layout.

**Comment by jkotas** [comment]
Does the JIT have tail-merging now? If not, deleting these workarounds will make the code bigger and somewhat slower.

**Comment by JosephTremoulet** [comment]
> Does the JIT have tail-merging now? If not, deleting these workarounds will make the code bigger and somewhat slower

It does not, thanks for the heads-up...

**Comment by JosephTremoulet** [comment]
It looks like there are three levels of complexity regarding epilog sharing:

1: The label is only targeted by a single return (as in IndexOfAny specializations for [two](https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/mscorlib/src/System/String.Searching.cs#L139-L171) and [three](https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/mscorlib/src/System/String.Searching.cs#L173-L195) chars, [CompareOrdinalIgnoreCaseHelper](https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/mscorlib/src/System/String.Comparison.cs#L21-L59), and [EqualsIgnoreCaseAsciiHelper](https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/mscorlib/src/System/String.Comparison.cs#L140-L180)): these are taken care of by #13314, I'll submit a PR for them shortly.

2: The label is targeted by multiple returns (as in [EqualsHelper](https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/mscorlib/src/System/String.Comparison.cs#L80-L138) and [StartsWithOrdinalHelper](https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/mscorlib/src/System/String.Comparison.cs#L182-L235)):  interestingly, we already "merge" them into a single return, thanks to [this JIT code](https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/jit/flowgraph.cpp#L8268-L8273) that was added to deal with an X86 GC encoding limitation but fires on all targets.  When that code fires, however, we admit just one return for the entire method, so end up with several blocks setting the return code and jumping to the exit.  It might be interesting to adjust that code to check if the returned value is a constant and share same-constant returns (and share non-constant returns) but keep different-constant returns separate from each other and from the non-constant return (up to the trackable limit per the GC encoding) -- this would be a very narrow pattern match, but I think it could cheaply identify and help with search-loop predicate methods, which the motivating cases here have been.

3: Gotos target a cascade of labels that compute different results for different entries to the "cascade" (as in general [IndexOf](https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/mscorlib/src/System/String.Searching.cs#L41-L81)/[LastIndexOf](https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/mscorlib/src/System/String.Searching.cs#L315-L359) and [CompareOrdinalHelper](https://github.com/dotnet/coreclr/blob/fca2b735f4b5193dfbf7f8b5b8d36060d73a9967/src/mscorlib/src/System/String.Comparison.cs#L237-L355)):

Here's an example of the gotos:

```c#
                    if (*pCh == value) goto ReturnIndex;
                    if (*(pCh + 1) == value) goto ReturnIndex1;
                    if (*(pCh + 2) == value) goto ReturnIndex2;
                    if (*(pCh + 3) == value) goto ReturnIndex3;
```

and the corresponding labels:

```c#
            ReturnIndex3: pCh++;
            ReturnIndex2: pCh++;
            ReturnIndex1: pCh++;
            ReturnIndex:
                return (int)(pCh - pChars);
```

Rewriting the source by duplicating all those `pCh++` statements would mean that a straightforward tail merge could restore this code, but that seems like an especially awkward way to write the source.  Rewriting the source by rewriting `goto ReturnIndex2` as `return (int)(pCh - pChars) + 2` etc. would require an extraordinarily sophisticated tail-merge to return to the current form (even supposing we were clever enough to factor out the constants, initializing them before jumping to the common return would require inserting a block in the loop), so I think it's best to leave these as they are (unless I'm just missing what the rewrite would look like that would make this a more normal tail merge case).

/cc @dotnet/jit-contrib
