### ISSUE TITLE
Test projects shouldn't list out all the RuntimeIdentifiers

### ISSUE THREAD

**Issue by weshaggard** [dotnet/coreclr#13474]
See https://github.com/dotnet/coreclr/commit/383a266b6a9c05a73f18ec00b807c841eb722d1d where we have been having trouble with getting RH6 builds going because we have to first build it while the tests fail and then update the tests after we have the build passing. On top of that we are restoring way more then we need to on each leg because of this list.

We should parameterize the list of RID's we restore based on the RID we are going to build and test to eliminate this issue.

**Comment by wtgodbe** [comment]
Will take a look at this today

**Comment by wtgodbe** [comment]
Testing a fix right now, in the meantime if it doesn't work, adding the RH6 rid to https://github.com/dotnet/coreclr/blob/master/tests/src/Common/test_dependencies/test_dependencies.csproj#L30 (& a few other places) is a temporary fix. Hopefully won't be needed.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/13529 is the PR

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/coreclr/pull/13529 - https://devdiv.visualstudio.com/DevDiv/Net%20CoreFX/_build/index?buildId=946407&_a=summary
