### ISSUE TITLE
Missing license header in test py files

### ISSUE THREAD

**Issue by omajid** [dotnet/coreclr#13471]
Most files under https://github.com/dotnet/coreclr/tree/master/src/ToolBox/SOS/tests do not have a license header. Is it safe to assume that they are licensed under https://github.com/dotnet/coreclr/blob/master/LICENSE.TXT ?

**Comment by danmosemsft** [comment]
@richlander ?

**Comment by richlander** [comment]
It looks like most/all of these came via commits from Samsung, which means they came in under the .NET Foundation CLA. Samsung signed a corporate-level CLA with the .NET Foundation.

So, yes, we can assume that these are MIT. It would be good if someone added the same license headers for these files that we use with other files.

**Comment by danmosemsft** [comment]
@sam-baravy seems you added these, would you mind adding the usual 3 line license header same as our other files?

**Comment by mikem8361** [comment]
Fixed with PR https://github.com/dotnet/coreclr/pull/17102
