### ISSUE TITLE
Incorrect description for System.(U)IntXX

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/coreclr#13479]
With the exception of System.Int32 the description for other System.(U)IntXX  uses the term ”class”.

>Purpose: This class will encapsulate a short and provide an Object representation of it.

However, all those are “structs”. 

System.Int16
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Int16.cs

System.Int64
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Int64.cs

System.UInt16
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Int64.cs

System.UInt32
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Int64.cs

System.UInt64
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Int64.cs

The following don't have a description comment:

System.Byte
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Byte.cs

System.SByte
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/SByte.cs

**Comment by jkotas** [comment]
> all those are “structs”

Depends on whether you are using [C#](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf) or [CLI](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf) spec. Class types in CLI are either object types (C# reference types) or value types (C# struct types). Reference types in C# are further divided into class types, interface types, array types, and delegate types. 

C# and CLI are not fully consistent. Historic artifact of each being built by different team...

**Comment by jkotas** [comment]
These comments have pretty limited value. Maybe best to delete them.
