### ISSUE TITLE
Marshal of struct error on non-windows

### ISSUE THREAD

**Issue by MaitreDede** [dotnet/coreclr#13498]
Hi,

I have a structure, with some field that are other structures, and others as structure arrays . They are defined as `public sealed class` with `StructLayout(LayoutKind.Sequential)`.
Idea is :
```
[StructLayout(LayoutKind.Sequential)]
public sealed class A
{
  public int x;
  public B y;
  [MarshalAs(UnmanagedType.ByvalArray, SizeConst=10)]
  public C[] z;
}

[StructLayout(LayoutKind.Sequential)]
public sealed class B
{
  public int x;
}
[StructLayout(LayoutKind.Sequential)]
public sealed class C
{
  public int x;
}
```

Somewhere in my code, I have `Marshal.SizeOf<A>()`.
On windows : works fine.
On linux (bash on windows) : error
On arm (pi3) : error
```
Unhandled Exception: System.ArgumentException: Type 'A' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed.
```

If I redefine my structs from `public sealed class`  to `public struct`, it works well.

What have I done wrong ?

Thanks.

**Comment by danmosemsft** [comment]
@MaitreDede is it feasible to make a simple standalone repro?

**Comment by MaitreDede** [comment]
@danmosemsft  After trying to make a simple repro case, I didn't managed to have a "simple" case.

Source code is here : https://github.com/MaitreDede/RaspberryPi.Native/tree/bug-struct-repro
The entry point project is Repro.BugStruct.
It can't run on windows since it is for raspberry libraries.

- I installed a fresh Raspbian Lite (jessie) on a SD card, and use it in a Raspberry Pi 3.
- I followed [this article](https://blogs.msdn.microsoft.com/david/2017/07/20/setting_up_raspian_and_dotnet_core_2_0_on_a_raspberry_pi/) to install the dotnet core runtime 2.0. (I don't know if it is really needed, but at least the dependencies are here).
- I published my app `dotnet publish -r linux-arm` (on my dev machine, windows 10 x64)
- I uploaded the thing to my pi, `chmod +x Repro.BugStruct` and `./Repro.BugStruct`.

```
pi@pi3:~/repro $ ./Repro.BugStruct 
Size direct : MyClass 32
Size direct : MyStruct 32
Size generic method : MyClass 32
Size generic method : MyStruct 32
Size in generic class method is 32
Size in generic class method is 32
Size in generic class ctor is 32
Size in generic class ctor is 32
Size HeritedGenericStruct:  32
Size HeritedGenericClass:  32
ok
Hello World! Size of MMAL_PARAMETER_STEREOSCOPIC_MODE_T is 20
Hello World! Size of VC_IMAGE_T is 64
Hello World! Size of MMAL_COMPONENT_T is 56
Hello World! Size of MMAL_PORT_T is 64
Hello World! Size of MMAL_PARAMETER_CAMERA_INFO_CAMERA_T is 32
ok
Host created
Creating component vc.camera_info
Getting camera info

Unhandled Exception: System.ArgumentException: Type 'RaspberryPi.MMAL.Interop.MMAL_PARAMETER_CAMERA_INFO_T' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed.
   at System.Runtime.InteropServices.Marshal.SizeOfHelper(Type t, Boolean throwIfNotMarshalable)
   at System.Runtime.InteropServices.Marshal.SizeOf(Type t)
   at System.Runtime.InteropServices.Marshal.SizeOf[T]()
   at RaspberryPi.MMAL.Interop.Wrappers.BaseParameter`1..ctor() in I:\RaspberryPi.Native\RaspberryPi.Native\MMAL\Interop\Wrappers\BaseParameter.cs:line 21
   at RaspberryPi.MMAL.Interop.Wrappers.MMAL_PARAMETER_CAMERA_INFO_T_Wrapper..ctor()
   at RaspberryPi.MMAL.CameraInfoComponent.GetCameraInfo(Int32 cameraNum) in I:\RaspberryPi.Native\RaspberryPi.Native\MMAL\CameraInfoComponent.cs:line 25
   at Repro.BugStruct.Program.Main(String[] args) in I:\RaspberryPi.Native\Repro.BugStruct\Program.cs:line 51
Aborted
```

**Comment by luqunl** [comment]
I can repro this issue on my local and use the following simple repro.
`    [StructLayout(LayoutKind.Sequential)]
    public sealed class A
    {
      public int x;
      [MarshalAs(UnmanagedType.ByValArray, SizeConst=10)]
      public C[] z;
    }

    [StructLayout(LayoutKind.Sequential)]
    public sealed class C
    {
      public int x;
    }
    
    class Program
    {
        static void Main(string[] args)
        {
            int n = Marshal.SizeOf<A>();
        }
    }`

**Comment by luqunl** [comment]
The issue is related to code:
https://github.com/dotnet/coreclr/blob/52a816d3011f4d03b80b5940dc036b40d701f52d/src/vm/mlinfo.cpp#L5171

**Comment by luqunl** [comment]
The reason why Windows works but Linux doesn't work is that COM Interop is supported in Windows and isn't support in Non-Windows.

**Comment by luqunl** [comment]
@MaitreDede, Please use Struct instead of [StructLayout]Class for inline array type.
