### ISSUE TITLE
When debugging a 64-bits process with RyuJIT enabled Windows Freezes and Crash

### ISSUE THREAD

**Issue by redknightlois** [dotnet/coreclr#1350]
Last couple of days I had been a very bad time dealing with debugging a project. The debugger would crash msvcmon.exe and Windows will stop responding (even Ctrl-Alt-Del wont work). After disabling RyuJIT everything came back to normal.

**Comment by jkotas** [comment]
cc @cmckinsey @CarolEidt

**Comment by mmitche** [comment]
@redknightlois Is this against CoreCLR or the Desktop CLR?  If it's against Desktop, can you file an issue on Connect so we can take a look?  http://connect.microsoft.com/VisualStudio.  Please include detailed steps to reproduce the problem.

**Comment by redknightlois** [comment]
@mmitche DesktopCLR which is sad, because Connect is where bugs are sent to rot and be forgotten. 

There are not many more instructions as:

- Process running on fumes memory wise (the process being debugged uses a lot of memory) 
- Debugger breaks.
- You just do your usual debugging things (step in-out etc)
- Eventually the whole computer stops responding 
- A message box I have never seen before tells me that an operation has been waiting for too long, with 2 options (end process and/or keep waiting).
- No matter which one I select, the whole desktop crash (explorer) and a msvcmon.exe also appear. And not even Ctrl-Alt-Del will be able to show the options. Sometimes it comes back after a minute or two, but most times I ended up hard rebooting (which happens instantly).

Important to note: I had VS2015 installed one of the latest RC5 and then the RTM (since release). This started happening a few days ago, probably related to some clr update. Disabling RyuJIT makes the problem disapear (havent seen it again). 

Environment: Windows 8.1 (patched up to today)
Installed: Visual Studio 2010, 2012, 2013, 2015

**Comment by mmitche** [comment]
@redknightlois Luckily, connect gets routed to developers fairly quickly these days :)  Is your process that is running on fumes 64-bit or 32-bit?

**Comment by CarolEidt** [comment]
@redknightlois Have you taken a look at the RyuJIT troubleshooting tips here: https://github.com/Microsoft/dotnet/blob/master/docs/testing-with-ryujit.md?

**Comment by redknightlois** [comment]
@mmitche 64-bits
@CarolEidt From that document is where I got how to disable RyuJIT to try if it had anything to do with the issue I had or it was something else.

**Comment by CarolEidt** [comment]
@redknightlois If I understand the above correctly, this problem did not start occurring immediately after installing VS2015 and .NET 4.6, but some time later? If so, it might be useful to understand what may have changed - can you correlate with any updates or changes that happened?

**Comment by redknightlois** [comment]
@CarolEidt I have it installed since release, but I havent worked with that project for a while. I remember having done something along the time I installed it (without trouble), so any update that may have happen in between could be the culprit. I have it setup to automatically update whenever an update is available, so you can assume an up-to-date machine. Sadly as I cannot recover from the issue it is hardly difficult I would be able to get more data. 

However, I can try to repro it enabling RyuJIT if you have any way to acquire relevant information.

**Comment by Furynation** [comment]
I am also having the same issue. At first, I thought it was related to a continuous testing tool I used (called NCrunch); so I filed a bug report with them, I captured a minidump which can be found here: http://forum.ncrunch.net/yaf_postst1622_Unable-to-Debug-tests-in-Visual-Studio-2015.aspx

I have been able to reproduce it in a 2nd scenario repeatedly as well. I'm not sure if it will repro if I package it up. Wanted to make this visible, I will file a bug over at connect.

**Comment by redknightlois** [comment]
@Furynation Glad I am not the only one to have this issue and that you were able to get a minidump for it.

**Comment by mmitche** [comment]
@Furynation thanks!

**Comment by Furynation** [comment]
@mmitche No problem! I hope there's enough info. in the dump to help resolve the issue.

**Comment by mmitche** [comment]
@Furynation @redknightlois Looking at the dump now

**Comment by Furynation** [comment]
@mmitche You are my hero. "Please don't be user error, please don't be user error." :)

**Comment by mmitche** [comment]
@Furynation I posted some stuff on the Connect.  I'm trying to get a repro outside of the dump because it doesn't quite give enough info.  Also, did you say that this doesn't repro with RyuJIT disabled?

**Comment by Furynation** [comment]
I tried disabling RyuJIT, but it didn't seem to help. Let me pull up my repro once and I'll get back to you shortly.

**Comment by redknightlois** [comment]
@mmitche Not in my case at least. I solved it disabling RyuJIT.

**Comment by mmitche** [comment]
Hmm, I'm wondering whether these are not related then (but both are interesting).  Did you manage to get a crash dump for your msvsmon crash?

**Comment by redknightlois** [comment]
@mmitche No, in my case it is not recoverable. Windows Freezes completely. Only once I was able to see the msvsmon crash before I have to hit the reset button (windows didnt close it just reset directly).

**Comment by Furynation** [comment]
@mmitche No lambdas, no conditional break points, just a bunch of setup code for a test. It dies after initializing a builder class I've created. I have a quite a bit of inheritance going on; the minute I step out of this builder constructor, msvsmon crashes. I do have watches, but they're from a different part of the project and they don't exist where I'm debugging. I'd be willing to share the 5-10 .cs files that make up the code which is crashing, but not sure it'd do you any good? I'd have to be able to share them non-publicly.

**Comment by mmitche** [comment]
@Furynation I'll let you know if we end up needing it.

**Comment by mmitche** [comment]
@Furynation Your bug has been assigned over to the debugger team.  Which just leaves the first issue.  @redknightlois Is the debugging experience good without RyuJIT enabled (responsive).  I'm trying to figure out whether the memory-intensive application could be on the line of running out of memory (at least physical space) and RyuJIT pushes it over the edge, or whether there could be a situation where RyuJIT is causing bad behavior in the debugger.  How long do you have to debug before it hangs and crashes?

**Comment by Furynation** [comment]
@mmitche  Thank you very much for your help!

**Comment by redknightlois** [comment]
@mmitche Not much time, I consume the memory pretty fast in wall clock (heavily multithreaded). As soon as I hit the breakpoint, sometimes in the third or fourth F10 it crash. Sometimes it takes more. Without RyuJIT is is pretty responsive and doesnt crash for me.

**Comment by mmitche** [comment]
@redknightlois my initial attempt at repro'ing using a memory hogging app didn't work, steps were still very responsive.  Does it matter where you stop and step as to whether it decided to crash or not (kind of code, types of debugging windows open, etc.).  Is there any way you can get a reduced repro (or just a repro) to us?

**Comment by redknightlois** [comment]
@mmitche if I didnt break nothing happens, it crashes only after breaking and stepping through the code. 

Do you have any tool out there that would record data that would survive the windows crash? I could at least try to reproduce, some time has passed already (installed Windows 10 in that time :D), but probably I would be able to reproduce it on purpose enabling RyuJIT.

**Comment by mmitche** [comment]
Let me ask around and see what people think.  If it doesn't crash the process, then an automatic minidump isn't going to work.  I'm wondering whether you can get it almost to the point of crashing (a couple F10's), then generate a minidump of whatever process appears to be starting to eat a ton of mem or CPU (it would be another process).  You can do that by right clicking on a process in the task manager and clicking "Create Dump File"

Another silly question: is the intellitrace window open?

**Comment by redknightlois** [comment]
I tried to get a minidump, the problem is I lose complete control of the computer when it happens and end up hitting the reset button after some time. 

Intellitrace was enabled, windows not open.

**Comment by mmitche** [comment]
@redknightlois Well, i'm a bit stumped.  I've been unable to repro the problem locally with a high memory application.  What happens if you disable intellitrace?  I'll try to find out the best way to get a dump in this scenario.

**Comment by mmitche** [comment]
@redknightlois Here's an interesting suggestion.  If you can identify the process(es) that seem to cause the hang, you can set the affinity to a single CPU, which should keep your system usable while you're able to grab the minidump

**Comment by redknightlois** [comment]
Will try that. Let's pray I can reproduce this on Windows 10.

**Comment by CIPop** [comment]
@mmitche I can repro this consistently on RS1 debugging System.Net.Security from CoreFX (CoreCLR context using CoreRun + Xunit).

**Comment by mmitche** [comment]
Oof, gotta page in some context here....
/cc @dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
@cipop Can you share more details about the repro, i.e. what app, config, debug location, etc.?  It might also be useful to attach ntsd/windbg to msvsmon.exe and share a remote if you can catch it crashing.

**Comment by CIPop** [comment]
I followed up offline with a full-memory dump and trace.

**Comment by gregg-miskelly** [comment]
@CIPop are you trying to debug .NET Core RTM builds with VS 2015 Update 2 or before? That will NOT work. Install: https://blogs.msdn.microsoft.com/visualstudio/2016/06/07/visual-studio-2015-update-3-rc/

**Comment by CIPop** [comment]
@gregg-miskelly Did not know that. Trying it now.

**Comment by CIPop** [comment]
@gregg-miskelly You are right! I can't repro the problem after installing Update 3 RC. Thanks!

**Comment by redknightlois** [comment]
@gregg-miskelly Havent seen this either for a long time already (upgrade to Windows 10 fixed it).
