### ISSUE TITLE
Remove all dead PAL functions

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#13503]
There are likely still some PAL functions that are not used anymore. This issue tracks work needed to eliminate them.
There are two ways how PAL functions are used. First, coreclr native shared libraries and applications link to libcoreclrpal.a static library. And second, System.Private.CoreLib.dll PInvokes some of the PAL functions that are exposed by libcoreclr.so.
The functions that the native shared libraries and applications link to are listed in https://gist.github.com/janvorli/527f407a54c45e937b322ae373c00779.
The functions exposed by libcoreclr.so for PInvoke purposes include some of these and may add others. The list of the exposed functions is in https://github.com/dotnet/coreclr/blob/master/src/dlls/mscoree/mscorwks_unixexports.src.
The goal is to walk through https://github.com/dotnet/coreclr/blob/master/src/pal/inc/pal.h, find functions that are not in one of these two lists, verify that they are not needed by the PAL itself and then remove their implementation from PAL and their declarations from pal.h.

**Comment by janvorli** [comment]
cc: @danmosemsft

**Comment by danmosemsft** [comment]
@justinvp any interest in doing more of this...

**Comment by justinvp** [comment]
Sure... When I get a chance, I'll take a look.
