### ISSUE TITLE
[Arm64/Unix] tip broken

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#13507]
`Assertion failed 'objChild->isContained()' `
File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/lsraarmarch.cpp Line: 672

`Assertion failed '((consume == 0) && (produce == 0)) || (ComputeAvailableSrcCount(tree) == consume)'`
File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/lsra.cpp Line: 3638

crossgen of Microsoft.CodeAnalysis.VisualBasic.dll leads to this assertion
`Assertion failed 'block->bbPreds->flBlock == block->bbPrev'`
File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/optimizer.cpp Line: 1958

**New failing tests (due to assertions above)**
```
JIT/jit64/hfa/main/testG/hfa_nd0G_d/hfa_nd0G_d.sh
JIT/jit64/hfa/main/testG/hfa_nd0G_r/hfa_nd0G_r.sh
JIT/jit64/hfa/main/testG/hfa_nd1G_d/hfa_nd1G_d.sh
JIT/jit64/hfa/main/testG/hfa_nd1G_r/hfa_nd1G_r.sh
JIT/jit64/hfa/main/testG/hfa_nd2G_d/hfa_nd2G_d.sh
JIT/jit64/hfa/main/testG/hfa_nd2G_r/hfa_nd2G_r.sh
JIT/jit64/hfa/main/testG/hfa_nf0G_d/hfa_nf0G_d.sh
JIT/jit64/hfa/main/testG/hfa_nf0G_r/hfa_nf0G_r.sh
JIT/jit64/hfa/main/testG/hfa_nf1G_d/hfa_nf1G_d.sh
JIT/jit64/hfa/main/testG/hfa_nf1G_r/hfa_nf1G_r.sh
JIT/jit64/hfa/main/testG/hfa_nf2G_d/hfa_nf2G_d.sh
JIT/jit64/hfa/main/testG/hfa_nf2G_r/hfa_nf2G_r.sh
JIT/jit64/hfa/main/testG/hfa_sd0G_d/hfa_sd0G_d.sh
JIT/jit64/hfa/main/testG/hfa_sd0G_r/hfa_sd0G_r.sh
JIT/jit64/hfa/main/testG/hfa_sd1G_d/hfa_sd1G_d.sh
JIT/jit64/hfa/main/testG/hfa_sd1G_r/hfa_sd1G_r.sh
JIT/jit64/hfa/main/testG/hfa_sd2G_d/hfa_sd2G_d.sh
JIT/jit64/hfa/main/testG/hfa_sd2G_r/hfa_sd2G_r.sh
JIT/jit64/hfa/main/testG/hfa_sf0G_d/hfa_sf0G_d.sh
JIT/jit64/hfa/main/testG/hfa_sf0G_r/hfa_sf0G_r.sh
JIT/jit64/hfa/main/testG/hfa_sf1G_d/hfa_sf1G_d.sh
JIT/jit64/hfa/main/testG/hfa_sf1G_r/hfa_sf1G_r.sh
JIT/jit64/hfa/main/testG/hfa_sf2G_d/hfa_sf2G_d.sh
JIT/jit64/hfa/main/testG/hfa_sf2G_r/hfa_sf2G_r.sh
JIT/opt/Inline/tests/UnsafeBlockCopy/UnsafeBlockCopy.sh
```

@dotnet/arm64-contrib @jkotas @jashook

**Comment by sdmaclea** [comment]
Doing Bisect:

There are at least two breaking patches
The 
```
crossgen of Microsoft.CodeAnalysis.VisualBasic.dll leads to this assertion
Assertion failed 'block->bbPreds->flBlock == block->bbPrev'
File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/optimizer.cpp Line: 1958```

Is a caused by a more recent patch than the rest of the patches. 94231f0

**Comment by sdmaclea** [comment]
Looks like the earliest failure is 5dada64d (doesn't compile) or 0ad49b141f1 which seem to be #13198 

@CarolEidt Are you aware of these failing tests?

**Comment by CarolEidt** [comment]
> Are you aware of these failing tests? (All the fails except the crossgen basic block failure)

Yes, I'm working on them. Sorry for the delay.

**Comment by CarolEidt** [comment]
@sdmaclea - I believe that my PR #13470 addressed this - were there failures beyond the tests run by the CI system?

**Comment by sdmaclea** [comment]
@CarolEidt Threre were some crossgen failures with the same asserts which I did not report.  

I will take a look.  Thanks

**Comment by sdmaclea** [comment]
@CarolEidt The only remaining problem is orthogonal.

Log from crossgen of Microsoft.CodeAnalysis.VisualBasic.dll
```
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assert failure(PID 23751 [0x00005cc7], Thread: 23751 [0x5cc7]): Assertion failed 'block->bbPreds->flBlock == block->bbPrev' in 'Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE.MetadataDecoder:IsOrClosedOverATypeFromAssemblies(ref,struct):bool' (IL size 213)

    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/optimizer.cpp Line: 1958
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/crossgen
```

This was introduced after your patch.  I haven't finished the bisect to know the root cause yet.

**Comment by sdmaclea** [comment]
@CarolEidt Thanks

**Comment by CarolEidt** [comment]
OK, I'll let you make the call on when/whether this should be closed.

**Comment by sdmaclea** [comment]
@JosephTremoulet Looks like the remaining crossgen failure was introduced by #13314.  PTAL.

**Comment by JosephTremoulet** [comment]
I am happy to look, but won't be able to until Monday.

**Comment by JosephTremoulet** [comment]
It looks like [this logic](https://github.com/dotnet/coreclr/blob/59d059c1fdeee785cda8a82474a628f7085df687/src/jit/optimizer.cpp#L1921-L1928) also needs to be applied [up here](https://github.com/dotnet/coreclr/blob/59d059c1fdeee785cda8a82474a628f7085df687/src/jit/optimizer.cpp#L1851-L1854) -- I added it where we insert blocks to the loop set during the flow walk, but not where we initialize the loop block set to the seed singleton.  I'll put together a PR...

**Comment by JosephTremoulet** [comment]
FWIW, the reason we aren't running into Windows is because [this code](https://github.com/dotnet/coreclr/blob/272f640378ebcc0fe9a7e2a82453fa160595f081/src/zap/zapimage.cpp#L2092-L2099) skips crossgen compilation of `IsOrClosedOverATypeFromAssemblies`:

https://github.com/dotnet/coreclr/blob/272f640378ebcc0fe9a7e2a82453fa160595f081/src/zap/zapimage.cpp#L2092-L2099

I don't know why that would differ on Windows vs Linux...
