### ISSUE TITLE
[Question] Does the Desktop JIT not eliminate typeof(T) == typeof(...) checks in generic methods?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#13514]
I [am planning](https://github.com/dotnet/corefx/compare/master...jamesqo:fast-ec?expand=1#diff-8b314c23a075770e35727dcd2d472a88R14) to bring a PR to corefx soon that avoids one virtual method call to `IEqualityComparer<T>.Equals` when the equality comparer is the default one, with a new extension method `EqualsFast`. I intended to use `EqualsFast` in all of the collection types, including those in System.Collections and those in System.Collections.Immutable. However, it came to my attention that S.C.I still has to support desktop, and [from here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgBgARYCMALANwCwAULgYQHQAiAlhAOYB2A9rEwMZQVq+InQBKAV3YwmYOHQDCnMAAcmAG0QBlRADc+cAVSpYAzHlgRpvAgCY8ilRASIAqtLVNpBqgG8qeAIIzCytbPAY4ADMIcTUYAB4AFQA+f0C/SkCsoPMYSz48ZwgAE052NQBPPABRAEdxCA8YCodlJ0Qk5Jr6xs8WpTbnBDwAXm6Gpv7HIc7GKJi4wSyAXyNMwIBtAFk4GAALTmKASRU1AAod/cOT5TUAeWVpMqg6AEFWVmcoKCYdOCPykx2EDWABKAC6aQCply+WswE4nDU40aUAAYtAEikzvsmFA8Ec6hM+q12ghOng4D1JqShkg8Ik8AAPemMiqgqF4DLZQIAel5DLuDDuIHszyYxUQeCBsDgJQI+HYsWR0HMcCkQLgyJ0jXEcDwEHYxTwygQnD2TGAnhBKJpAzJswi0ViMDonKyEWA4lYb2+iBgZypxOatKlAEIxkq1GpQYJ3XyBYkhSKGRb8bw9nBeABrcwHWLG4p4iDKZRy4aRM1gPD7fWsdWISxwY28Q76piRBnS/Fcdj6zid2smhAya1/GsVMv44BazgAdzd6x5HbwgepJPtQ1GYydCyxyToRN6Ic3iA5S+y3J52RXOMncAHZ0SoO3E7Lj+AFXgoPP18v8b/aEAHZV0/b8zk4YAACssxgUEmVfM4wLgUEIOg2DQQqJZAICVYLz/W9mnfSInxfEYxiIh8SKgZCfwA/98JwggQLOGivxQtCYN4OCEPI1c2PAyCuLgrD6JWMTAkI+9H2fV9KMfKADgQODfyYq8mMCLAWMUzhlNQoSMN4sZWKUuDOIw0TGJ5PCNKk4jSLk6SSPEHS9NUnD1I05jVxc0z9PQ7j4MQ3zdLMgzAssjSbKYuyqIcvj5JIoEVIkgJPI0rTV2S/zhKCvizmy8yIuwnDopw2KZLIiinLOcRsvcwD0qYzLasK8KeOCtqApEkrALKwCKpI2SEpqtQyjBBq/yanCWrG9gwSKjr8rmhb2sw3q/36gjOzvezhuq+zYnGuirIYrzNJYo75pywzgpWm7itSvAtuvQb4oOuKiBwE6NOmwCWq+h6luMwHFvWp6XtwtY/0yoNjymQZEEPakoDOFk8HZXq8Lw4w7HkXxOSwYg8C2M4Gr+0MEDcdRrQMOZnTieJkoPI87WmJHWfRTEzhwelvqxqhliAA==) it looks like the desktop CLR is unable to remove the `typeof` checks resulting in very bloated asm.

Is this accurate/was the `typeof` optimization really only implemented in CoreCLR? Thanks.

/cc @jkotas

**Comment by benaadams** [comment]
> Desktop CLR v4.7.2053.00 (clr.dll) on x86.

**Comment by jkotas** [comment]
The optimization is implemented in .NET Framework too, but the exact set of conditions where it kicks in is likely different from the current CoreCLR.
