### ISSUE TITLE
Tests project build fails after coreclr builds successfully 

### ISSUE THREAD

**Issue by ganeshran** [dotnet/coreclr#1351]
When I build the coreclr project on windows 7 with Visual Studio 2013, the tests project fails with a `The system cannot find the path specified` error. The coreclr project  builds successfully before the tests build is started

However when I cd into the tests directory and run the "buildtest.cmd" file directly , it works and builds all the test projects

>
Time Elapsed 00:00:06.14
Starting the Managed Tests Build
>
  Restoring build tools...
  Restoring all packages...
  The system cannot find the path specified.
e:\git\coreclr\tests\build.proj(23,5): error MSB3073: The command ""e:\git\core
clr\tests\packages\/dnx-coreclr-win-x86.1.0.0-beta5-12101/\bin\dnu.cmd" restore
 --packages "e:\git\coreclr\tests\packages" "e:\git\coreclr\tests\src"" exited
with code 3.
Test build failed. Refer e:\git\coreclr\tests\..\bin\Logs\Tests_Managed_Windows_
NT__x64__Debug.log for details
Test binaries build failed. Refer e:\git\coreclr\bin\Logs\MScorlib_Windows_NT__x
64__Debug.log for details.

Debug Log

>
"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "e:\git\coreclr\tests\..\tests\build.proj"  /nologo /maxcpucount /verbosity:minimal /nodeReuse:false /fileloggerparameters:Verbosity=normal;LogFile="e:\git\coreclr\tests\..\bin\Logs\Tests_Managed_Windows_NT__x64__Debug.log";Append  
Build started 8/6/2015 1:23:58 AM.
     1>Project "e:\git\coreclr\tests\build.proj" on node 1 (default targets).
     1>_RestoreBuildTools:
         Restoring build tools...
         Attempting to download https://www.nuget.org/nuget.exe...
         "e:\git\coreclr\tests\packages\NuGet.exe" install -OutputDirectory "e:\git\coreclr\tests\packages" -ConfigFile "e:\git\coreclr\tests\src\NuGet.Config" -Verbosity detailed "e:\git\coreclr\tests\src\.nuget/packages.Windows_NT.config"
         Copying file from "e:\git\coreclr\tests\src\NuGet.Config" to "e:\git\coreclr\tests\packages\NuGet.Config".
         Touching "e:\git\coreclr\tests\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00056\lib\Microsoft.DotNet.Build.Tasks.dll".
         Touching "e:\git\coreclr\tests\packages\NuGet.exe".
         Touching "e:\git\coreclr\tests\packages\/dnx-coreclr-win-x86.1.0.0-beta5-12101/\bin\dnu.cmd".
       BatchRestorePackages:
         Restoring all packages...
         "e:\git\coreclr\tests\packages\/dnx-coreclr-win-x86.1.0.0-beta5-12101/\bin\dnu.cmd" restore --packages "e:\git\coreclr\tests\packages" "e:\git\coreclr\tests\src"

**Comment by mmitche** [comment]
In the bad case, does the dnu.cmd not end up on your machine in the location indicated?

**Comment by gkhanna79** [comment]
Is the issue resolved post the merges above?

**Comment by mmitche** [comment]
Yes.
