### ISSUE TITLE
Unify number parsing/formatting code with corert

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#13544]
The implementation of number parsing/formatting in corert is a managed port of the native implementation in coreclr.  We want to unify on the managed implementation, though doing so also involves addressing several perf gaps.  Doing this will then enable much more easily implementing span-based number formatting in coreclr.

**Comment by stephentoub** [comment]
The remaining code to be unified is that for double/single and decimal.

**Comment by RussKeldorph** [comment]
@danmosemsft Is this still destined for 2.1?

**Comment by danmosemsft** [comment]
Nope.

**Comment by pentp** [comment]
Number parsing/formatting should be unified after #20080 is mirrored to CoreRT.
