### ISSUE TITLE
Upgrading to .NET Core 2.0 makes obfuscation tools not working.

### ISSUE THREAD

**Issue by zwcloud** [dotnet/coreclr#13563]
After upgrading my project from .NET Core 1.1 to .NET Core 2.0, all formerly working obfuscation tools don't work any more.

* https://github.com/0xFireball/ModPhuserEx/issues/9   @0xFireball
    > Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

* https://github.com/lextm/obfuscar/issues/119  @lextm
    > Failed to resolve assembly: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

A possibly related question on StackOverflow:
[Could not load file or assembly 'netstandard, Version=2.0.0.0, …'. Reference assemblies should not be loaded for execution](https://stackoverflow.com/q/45021965/3427520)

Another post on visual studio community:
[Fakes with .NET Standard 2.0](https://developercommunity.visualstudio.com/content/problem/97436/fakes-with-net-standard-20.html)

**Q**: Why do I not downgrade to .NET Core 1.1?
**A**: Because [`System.Reflection.ObfuscationAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.obfuscationattribute?view=netframework-4.7&viewFallbackFrom=netcore-1.1) is not available in .NET Core 1.1.

**Comment by danmosemsft** [comment]
@weshaggard @ericstj @terrajobst can help here.

**Comment by weshaggard** [comment]
@zwcloud what version of the tools are you using? Do you have at least VS2017 15.3? If you could post a sample project demonstrating the issue I'd be happy to take a look and suggest a fix.

**Comment by zwcloud** [comment]
> What version of the tools are you using? 

The latest code of both tools.

> Do you have at least VS2017 15.3? If you could post a sample project demonstrating the issue I'd be happy to take a look and suggest a fix.

I have VS2017 15.3. But I think it is not related to VS2017 versions. You can just create a .NET Standard 2.0 Class Library with some dummy classes inside. It can be easily reproduced for both tools.

**Comment by weshaggard** [comment]
I see, the reason I asked about tooling was because we have some custom targets in our tools that should automatically include the netstandard.dll for a .NET Framework application. However in your case you aren't  trying to consume the library in a .NET Framework application it is the obfuscation tool that is missing the dependency.

As a potential workaround could you find `C:\Program Files\dotnet\sdk\2.0.0\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\netstandard.dll` on your machine and drop it into the same folder as the obfuscation tool is running in.

**Comment by zwcloud** [comment]
I repaced the original netstandard.dll with the one you just said.

Then the error becomes following for ModPhuserEx
> Exception: dnlib.DotNet.TypeResolveException: Could not resolve type: System.ValueTuple`3 (netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)

**Comment by weshaggard** [comment]
Looks like you need one more. Try copying `C:\Program Files\dotnet\sdk\2.0.0\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.ValueTuple.dll`.

**Comment by zwcloud** [comment]
Error still occurred:
> Exception: dnlib.DotNet.TypeResolveException: Could not resolve type: System.ValueTuple`2 (System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)

I created a reproducable sample for you:
[ConsoleApp.zip](https://github.com/dotnet/coreclr/files/1253366/ConsoleApp.zip)

Note I have added `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0` to probePath of the ModPhuserEx project file.

The error for that sample is
> Exception: dnlib.DotNet.MemberRefResolveException: Could not resolve method/field: System.ValueTuple`2<System.Int32,System.Int32> ClassLibrary.Class1::GetImageSize(System.String) (ClassLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)

**Comment by lextm** [comment]
As maintainer of Obfuscar, I did some investigation on this issue.

A simple .NET Standard 2.0 assembly would contain only a single reference to `netstandard.dll`. And `netstandard.dll` uses type forwarding to guide CLR to load types from the actual assemblies (like `System.Runtime`).

By serving Mono Cecil or dnlib with proper search paths (like `C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0`), the reference issue can be easily addressed, but other operations can still lead to problems.

One example is that if using Mono Cecil to import a type like `System.Text.Encoding`, Cecil would add a reference to `System.Runtime`, as it does not think type forwarding in `netstandard.dll` is enough.

Thus, the libraries would require some updates so as to fully support .NET Standard 2.0 scenarios.

**Comment by weshaggard** [comment]
@lextm thanks for fixing your tool to support netstandard 2.0. 

@zwcloud is that enough to unblock you? There isn't much we can do on our side beyond provide some guidance to the tool authors on how to fix this so I'm going to close this issue. Please feel free to continue the discussion though.
