### ISSUE TITLE
visual studio 2015 build: error C2220: warning treated as error - no 'object'

### ISSUE THREAD

**Issue by syalachigere** [dotnet/coreclr#1356]
```build clean VS2015```

I am getting lots of build errors, starting with the following. How do I make these warnings not treated as errors?

I am building this using latest Visual Studio.

```
\github\coreclr\src\jit\compiler.cpp(5940): error C2220: warning treated as error - no 'object'.
file  generated [\GitHub\coreclr\bin\obj\Windows_NT.x64.Debug\src\jit\dll\ClrJit.vcxproj]
```

**Comment by ganeshran** [comment]
This is a known issue.  Visual Studio 2015 build is currently broken

**Comment by ganeshran** [comment]
See #1294
