### ISSUE TITLE
MissingMethodException: Method not found: 'System.DateTimeOffset System.DateTime Offset.get_UtcNow()'.

### ISSUE THREAD

**Issue by eerhardt** [dotnet/coreclr#13571]
Calling `DateTimeOffset.UtcNow` from the attached assembly on .NET Core 2.0.0 is throwing a MissingMethodException: Method is not found.

NuGet created `NuGet.Build.Tasks.Pack.dll` using ILMerge.  The IL in the assembly *looks* correct to me, but I'm not an expert.

I've created a standalone console app that invokes a constructor for `LogMessage` in that assembly, which in turn calls `DateTimeOffset.UtcNow`.  Invoking `dotnet run` on the project using .NET Core SDK 2.0 throws an exception:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target oftructor)
 an invocation. ---> System.MissingMethodException: Method not found: 'System.DateTimeOffset System.DateTimeeters, CultureInfo culture)
Offset.get_UtcNow()'.
   at NuGet.Common.LogMessage..ctor(LogLevel level, String message)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean cons
tructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] param
eters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at App.Program.Main(String[] args) in F:\DotNetTest\ILMergeTest\App\Program.cs:line 15
```

## Repro
1. Extract [Repro.zip](https://github.com/dotnet/coreclr/files/1250016/Repro.zip)
1. Using the [2.0 SDK](https://www.microsoft.com/net/download/core#/sdk) `dotnet run` the project

@jkotas - is there someone that can look at the .dll in the Repro.zip?  I'm not sure why this error is happening.

/cc @rohit21agrawal

**Comment by rohit21agrawal** [comment]
this is actually blocking our CI from generating a build so it's high priority for nuget team to get this resolved.

CC: @rrelyea

**Comment by jkotas** [comment]
The assembly contains bad IL. From ILDASM of NuGet.Build.Tasks.Pack.dll:

```
    IL_0008:  call       class [System.Runtime]System.DateTimeOffset [System.Runtime]System.DateTimeOffset::get_UtcNow()
```

System.DateTimeOffset is C# struct, so it has to be referred to as valuetype. The above code is referring to it as `class` which is incorrect. The correct way to call this method is - notice class is replaced valuetype:

```
    IL_0008:  call       valuetype [System.Runtime]System.DateTimeOffset [System.Runtime]System.DateTimeOffset::get_UtcNow()
```

**Comment by jkotas** [comment]
FWIW, CCI2 that ILMerge is based on is known to suffer from these kind of bugs.

**Comment by eerhardt** [comment]
Doh.  I missed that.  Thanks @jkotas for the quick turnaround.
