### ISSUE TITLE
Add support System.Numerics.Vectors types with double precision

### ISSUE THREAD

**Issue by acecebov** [dotnet/coreclr#13591]
Add support System.Numerics.Vectors types with double precision:
Vector2d, Vector3d, Vector4d, Matrix3x2d, Matrix4x4d, PlaneD, QuaternionD.

There are lots of scientific/gaming cases when we want to work with double precision and benefit of SIMD!

**Comment by danmosemsft** [comment]
@acecebov thanks for the suggestion, can you move the issue to the corefx repo? New api proposals go there.

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#25334
