### ISSUE TITLE
Portuguese localized string is wrong

### ISSUE THREAD

**Issue by ginvok** [dotnet/coreclr#1360]
I'm not sure where should I post this issue (I think its origin is in the .Net framework), so I'm sorry if I made a mistake posting here. And if I can't find the string in any repository.

There are some mistakes in the pt-BR (and probably pt-PT as well) translation, for example one common error while parsing string to integer says "Sequência de entrada não estava em um formato incorreto". 
It's a double negative and roughly translates as "Input sequence is **not** in a **in**correct format" (and actually means that it is correct?)

The original text is "Input string was not in a correct format", the key is "Format_InvalidString"

Number.cs : 1024
throw new FormatException(Environment.GetResourceString("Format_InvalidString"));

There may be more obscure translation mistakes, but I'm only aware of this one at this time.

**Comment by jkotas** [comment]
This repo is only used to track CoreCLR specific issues. Since this is .NET framework issue, could you please file it on Connect at http://connect.microsoft.com/VisualStudio ?

**Comment by ginvok** [comment]
Yes I'll do, thanks jkotas!

**Comment by jkotas** [comment]
https://connect.microsoft.com/VisualStudio/feedback/details/1652200

**Comment by jkotas** [comment]
Thanks! I am going to close this issue since it is tracked in the right place now.
