### ISSUE TITLE
CoreCLR NuGet symbol packages have strange names

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#13601]
I just downloaded a package `runtime.win-x64.Microsoft.NETCore.Runtime.CoreCLR.2.1.0-preview2-25625-02.symbols` from [here](https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win-x64.Microsoft.NETCore.Runtime.CoreCLR/2.1.0-preview2-25625-02) and the names of `mscordaccore` and `sos` had some suspiciously empty components where build numbers should be:

<img width="340" alt="files2" src="https://user-images.githubusercontent.com/1871912/29735576-b2321544-89ae-11e7-93e5-d05aaccebcc4.png">

@dagood speculated that it could be due to empty build variables: https://github.com/dotnet/coreclr/issues/13594#issuecomment-325024728.

@wtgodbe, would you know about this?

**Comment by wtgodbe** [comment]
Did this only start happening recently, or can you find the same in an older package (at least a couple weeks)?

**Comment by swgillespie** [comment]
It looks like this affects all `2.1.0-preview2` packages, going back to July: https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win-x64.Microsoft.NETCore.Runtime.CoreCLR/2.1.0-preview2-25501-02 . Though the package names are slightly different:

<img width="246" alt="capture" src="https://user-images.githubusercontent.com/1871912/29735785-7954dae8-89b0-11e7-9812-0c96663e77f0.PNG">

**Comment by janvorli** [comment]
I believe this is intentional and VS or WinDbg uses them to locate arch specific sos / mscordaccore. I think @mikem8361 made this change.

**Comment by swgillespie** [comment]
Yeah, I've found windbg in particular looks for a matching mscordaccore + sos with this method. However this is bound to fail if the version numbers are incorrect, as they are in this issue (in the first case, they are missing - in the second case, they are wrong). I had to rename the files to what windbg was asking for in order to get it to work.

**Comment by mikem8361** [comment]
I just noticed that we shipped 2.0 with the the wrong names. @dagood I thought this was fixed? Maybe it didn't make into the 2.0 release branch.

```
hostpolicy.dll
hostpolicy.pdb
microsoft.diasymreader.native.amd64.dll
mscordaccore.dll
mscordaccore.pdb
mscordaccore_amd64_amd64_4.6.00001.0.dll
mscordbi.dll
mscordbi.pdb
mscorrc.debug.dll
mscorrc.debug.pdb
mscorrc.dll
mscorrc.pdb
sos.dll
sos.pdb
sos_amd64_amd64_4.6.00001.0.dll
system.private.corelib.dll
system.private.corelib.ni.pdb
```

**Comment by dagood** [comment]
I don't remember hearing about this issue until a few days ago in https://github.com/dotnet/coreclr/issues/13594, let alone a fix.

**Comment by mikem8361** [comment]
@dagood I must have been remembering something else. I'm not sure you understand the way coreclr uses the dotnet build tools but for some reason BuildNumberMajor/BuildNumberMinor are not being set to the OfficialBuildId (or anything) when the nuget packages are built.

Would you have time to look into this?

**Comment by mikem8361** [comment]
Reopening issue to use for 2.0.1 service request PR.

**Comment by Petermarcu** [comment]
This is approved for checkin when the branch is open for 2.0.2.
