### ISSUE TITLE
[Question] Unloading an Assembly

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/coreclr#13612]
I'm aware Unloading of the AssemblyLoadContext is not yet implemented. Is the same true for assemblies?

**Comment by jkotas** [comment]
Yes, the same is true for assemblies. 

The eventual AssemblyLoadContext unloading is the only assembly unloading we plan to have in .NET Core. To unload the single assembly, you will still need to load it into unloadable AssemblyLoadContext.

**Comment by ElanHasson** [comment]
So it's going to be either unload the entire load context or don't?

Also, as far as fallback go for contexts, lf a type isn't found in the current context, it falls back to the creating context, until it hits default?


Also, is code isolated like it was in appdomain?

**Comment by jkotas** [comment]
Unloading is not going to change how assemblies are resolved accross multiple load contexts. The design is described here: https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md

**Comment by ElanHasson** [comment]
Thanks, I've read that document, was just confirming I understood it
correctly.

Does anything special need to be done to communicate across contexts like
it was in appdomain? Or is the way to look at a load context "a collection
of assemblies that reload the types and code and data with an optional way
to change how resolution happens"?

But not isolation like we have with app domains? No marshalling etc?

**Comment by jkotas** [comment]
Right. There is no marshalling required between ALCs as long as they agree on types to communicate.

The types to communicate has to be identical. E.g. both ALCs have to use type from parent ALC, or one ALC has to refer to types loaded by other ALC.

If each ALC loads own copy of the type, the types won't be identical.

**Comment by ElanHasson** [comment]
Cool. Thanks for the clarification.
