### ISSUE TITLE
Core Tests & Ready-To_run Tests: All work items have fireball issue, failed to generate the test result

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/coreclr#13618]
Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170828.01
https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fr2r~2Fcli~2F/build/20170828.01

failed configuration: all platforms

**Comment by danmosemsft** [comment]
@wtgodbe can you take a look?

**Comment by wtgodbe** [comment]
Yeah, I'll look into this as soon as I get a chance. I suspect it may be linked to https://github.com/dotnet/coreclr/pull/13529.

**Comment by wtgodbe** [comment]
Never mind, timeline doesn't fit with it being that PR. will keep digging.

**Comment by wtgodbe** [comment]
Looks like https://github.com/dotnet/coreclr/pull/13575 is the culprit. I've asked them to revert it or try to figure out an alternate solution.

**Comment by wtgodbe** [comment]
Apparently this will be fixed by https://github.com/dotnet/coreclr/pull/13510. Will keep an eye on the tests once that's merged.

**Comment by wtgodbe** [comment]
This has been resolved
