### ISSUE TITLE
Build failure: No profile data available for file "lsraxarch.cpp"

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#13655]
@dotnet-mc-bot commented on [Tue Aug 29 2017](https://github.com/dotnet/core-eng/issues/1626)

Opened on behalf of @mmitche

Warnings: 0
Status Message: failed

Build : Master - 20170829.02 (Product Build)
Failing configurations:
- Linux
  - Release-x64
[Mission Control Build Info](https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/build~2Fproduct~2F/build/20170829.02/workItem/Orchestration/analysis/external/Visual%20Studio%20Build%20Information)

---

@mmitche commented on [Tue Aug 29 2017](https://github.com/dotnet/core-eng/issues/1626#issuecomment-325707539)

This appears to a product team issue.  @danmosemsft does this look familiar?

2017-08-28T11:15:25.0681850Z [ 98%] Building CXX object src/jit/standalone/CMakeFiles/clrjit.dir/__/lowerxarch.cpp.o
2017-08-28T11:15:25.3402490Z [ 98%] Built target coreclr
2017-08-28T11:15:25.3570320Z [ 98%] Building CXX object src/jit/standalone/CMakeFiles/clrjit.dir/__/lsraxarch.cpp.o
2017-08-28T11:15:25.6722250Z [ 98%] Building CXX object src/jit/standalone/CMakeFiles/clrjit.dir/__/simd.cpp.o
2017-08-28T11:15:26.0882780Z [ 98%] Building CXX object src/jit/protononjit/CMakeFiles/protononjit.dir/__/rationalize.cpp.o
2017-08-28T11:15:26.1543090Z [ 98%] Building CXX object src/jit/standalone/CMakeFiles/clrjit.dir/__/simdcodegenxarch.cpp.o
**2017-08-28T11:15:26.3007960Z error: no profile data available for file "lsraxarch.cpp" [-Werror,-Wprofile-instr-unprofiled]**
2017-08-28T11:15:26.6282960Z 1 error generated.
2017-08-28T11:15:26.6342900Z make[2]: *** [src/jit/standalone/CMakeFiles/clrjit.dir/__/lsraxarch.cpp.o] Error 1
2017-08-28T11:15:26.6357470Z make[2]: *** Waiting for unfinished jobs....
2017-08-28T11:15:26.6842310Z Scanning dependencies of target dactablerva_header
2017-08-28T11:15:26.7111060Z [ 98%] /root/coreclr/bin/obj/Linux.x64.Release/src/inc/dactablerva.h
2017-08-28T11:15:26.7801690Z [ 98%] Building CXX object src/jit/protononjit/CMakeFiles/protononjit.dir/__/regalloc.cpp.o
2017-08-28T11:15:26.8158870Z [ 98%] Built target dactablerva_header
2017-08-28T11:15:26.8382880Z [ 98%] Building CXX object src/jit/protononjit/CMakeFiles/protononjit.dir/__/register_arg_convention.cpp.o

---

@mmitche commented on [Tue Aug 29 2017](https://github.com/dotnet/core-eng/issues/1626#issuecomment-325707924)

Associated changes:

Associated changes
5c07c5a Authored by Dan Moseley 
Remove always defined FEATURE_RANDOMIZE_STRING_HASHING define (#13491)

* Remove always defined FEATURE_RANDOMIZE_STRING_HASHING

* Fully remove randomized hashing

* Leftovers

* Remove additionalEntropy from HashSortKey as it was always 0

* Remove additionalEntropy from HashString as it was always 0

* Change to private, as not in fact called by reflection in .NET Core

* Fix build break due to FCDECLn

* Revert removed QCALL

* Remove unused strlen parameter ...
0db6d91 Authored by Dan Moseley 
Remove dead HResults.cs (#13611)

* Fix old copy paste mistake

* Remove dead HResults.cs

* Ren ...
a07fc39 Authored by Carol Eidt 
Merge pull request #13543 from hseok-oh/ryujit/fix_13451

[RyuJIT/ARM32] Simplify lowering long argu ...
02f0853 Authored by Adrian Godong 
Refactor AsSpan to AsReadOnlySpan (#13608)

* Refactor AsSpan to AsReadOnlySpan
* Updated usages.
...
74bccda Authored by Hyeongseok Oh 
Remove SetContained for GT_FIELD_LIST

Remove SetContained for GT_FIELD_LIST: already set when it is ...
fbba195 Authored by Carol Eidt 
Merge pull request #13597 from CarolEidt/InfoLinearScan

Move TreeNodeInfoInit to LinearScan
97a5627 Authored by Carol Eidt 
PR Feedback and formatting
98e481e Authored by Carol Eidt 
Move TreeNodeInfoInit to LinearScan

In preparation for computing the TreeNodeInfo on the fly, move ...
4928bcd Authored by Hyeongseok Oh 
Remove clearing regnum in LowerArg

Remove clearing regnum in LowerArg
Revert changing in gentree.h
de3b593 Authored by Hyeongseok Oh 
Fix regeression with Containment

- SetContained for GT_FIELD_LIST
- OperIsMultiRegOp return true fo ...

---

@mmitche commented on [Tue Aug 29 2017](https://github.com/dotnet/core-eng/issues/1626#issuecomment-325708064)

Will move into coreclr repo if it is.

**Comment by 4creators** [comment]
I am hitting similar problem with another file while building on WSL Ubuntu 16.04 with clang 3.9.1
```
[ 73%] Building CXX object src/jit/standalone/CMakeFiles/clrjit.dir/__/__/__/version.cpp.o
error: no profile data available for file "hwintrinsicxarch.cpp" [-Werror,-Wprofile-instr-unprofiled]
1 error generated.
src/jit/standalone/CMakeFiles/clrjit.dir/build.make:1598: recipe for target 'src/jit/standalone/CMakeFiles/clrjit.dir/__/hwintrinsicxarch.cpp.o' failed
make[2]: *** [src/jit/standalone/CMakeFiles/clrjit.dir/__/hwintrinsicxarch.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 73%] Building CXX object src/vm/wks/CMakeFiles/cee_wks.dir/__/vars.cpp.o
CMakeFiles/Makefile2:1730: recipe for target 'src/jit/standalone/CMakeFiles/clrjit.dir/all' failed
make[1]: *** [src/jit/standalone/CMakeFiles/clrjit.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
Any solution to this issue in sight?

**Comment by RussKeldorph** [comment]
Assuming this is resolved.  @jorive @DrewScoggins @adiaaida

**Comment by adiaaida** [comment]
Failures like this should resolve themselves within about 24hrs when we autoupload new profile data. If you're hitting it, your best bet is to just pass the nopgooptimize flag.
