### ISSUE TITLE
Add support for OpenSuse 42.2 in .NET CoreCLR 1.1.0

### ISSUE THREAD

**Issue by MattGal** [dotnet/coreclr#13671]
This issue tracks ensuring that your team has considered how to handle OpenSuse 42.2 builds in your .NET Core 1.1.0 repositories.

Since .NET Core 1.1 is an LTS release, per @leecow we need to support OpenSUSE 42.2 with it.  Unfortunately, when 1.1 release branches were snapped, 42.1 was the used version.  It turns out there was not even a RID (runtime identifier) that matches this build (In the 1.1 time frame, ‘opensuse.42.1-x64’ was used)

Please use this issue to track addressing the issue for your specific repository.  In some cases, little-to-no change will be required but lacking a previously-used RID we need to figure something out.

@wtgodbe  FYI

**Comment by wtgodbe** [comment]
Sure, will take a look at this. Should be a relatively simple change.

**Comment by RussKeldorph** [comment]
@wtgodbe Are you still planning to handle this?  If not, could you describe the necessary work and remove your assignment?

**Comment by wtgodbe** [comment]
I am not, but I believe all that would be required is to add a build on a OpenSUSE42.2 docker image in this file - https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/DotNet-BuildPipeline?path=%2Fsrc%2FPipeBuild%2FPipeBuild%2Fpipelines.coreclr.release.1.1.0.json&version=GBmaster&_a=contents

As well as making sure everything builds as expected on that image.
