### ISSUE TITLE
Where is Assembly.Location?

### ISSUE THREAD

**Issue by aggieben** [dotnet/coreclr#1367]
While trying to port some 4.5 code to CoreCLR, I found my issue from April (#760), which proved helpful.  However, now I'm trying to use `Assembly.Location`, which seems to be declared ([src/mscorlib/src/System/Reflection/Assembly.cs:1041](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Reflection/Assembly.cs#L1041)), but at build time, I experience the following error:

> 'Assembly' does not contain a definition for 'Location' and not extension method 'Location' accepting a first argument of type 'Assembly' could be found ...

It seems that actual instances of `Assembly` are being produced by the runtime somehow, but I don't quite follow how, ergo I'm also confused about where this property is hiding...

**Comment by akoeplinger** [comment]
FYI the mscorlib code in this repo is shared between Desktop .NET and .NET Core, so not everything in the source is exposed in .NET Core.

`Assembly.Location` isn't exposed, like a bunch of other [methods](https://github.com/dotnet/corefx/issues/1784) on `Assembly`.

**Comment by aggieben** [comment]
Yeah, I've noticed.  It's a frustrating thing to try and divine what's exposed and what's not :-1: 

Is there some record _anywhere_ that would give this detail?

**Comment by akoeplinger** [comment]
> Is there some record anywhere that would give this detail?

yep, everything listed at https://github.com/dotnet/corefx-progress/tree/master/src-full is available.

**Comment by aggieben** [comment]
Ah! There's always something I didn't know about lurking about on GitHub.  Thanks!

**Comment by aggieben** [comment]
Actually, one last question: since `Assembly.Location` isn't in the CoreCLR API, is there an alternative way supported by CoreCLR to get the path of a loaded assembly?

**Comment by xanather** [comment]
@aggieben You could try AppContext.BaseDirectory

**Comment by aggieben** [comment]
@xanather that only works for the executing assembly.  This has to be for any assembly loaded in the AppDomain.

**Comment by nosami** [comment]
I would like Assembly.Location (or any method for determining the location of mscorlib) for OmniSharp. 
I use it for loading mscorlib into test cases.

**Comment by weshaggard** [comment]
cc @nguerrera

**Comment by nguerrera** [comment]
There's a good discussion about Assembly.Location in dotnet/corefx#2221. Closing this since we should discuss API changes on corefx.
