### ISSUE TITLE
Reasons for allocating a char buffer in Encoding.GetEncoding

### ISSUE THREAD

**Issue by James-Ko** [dotnet/coreclr#1368]
Is there a reason why we both allocate a new `char[]` and a new string instance [here](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/Encoding.cs#L1492-L1496) in `GetEncoding(byte[], int, int)`, while `GetString(byte*, int)` does not? The comments say that "internally we override this for performance reasons," and in fact the exact same code is copied and pasted between [6 different files](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/UTF7Encoding.cs#L470-L473).

Changing the parent method from safe to unsafe doesn't affect compatibility, does it? And even if it did, wouldn't it be possible to write a safe wrapper around the overload and call that?

**Comment by jkotas** [comment]
The minimum required to create your custom encoding is to override abstract `int GetChars(byte[] bytes, int byteIndex, int byteCount, char[] chars, int charIndex)` and 3 other similar abstract methods. The other methods are virtual and they can be optionally overridden for better performance.

It is artifact of how the framework evolved in compatible way. The safe methods that take arrays were added first, and the unsafe methods that take pointers were added later. The copy&paste boilerplate code in each encoding optimized for performance is a price that has been paid to avoid breaking change when the unsafe methods were added.

**Comment by James-Ko** [comment]
So essentially, changes to `GetString` would break compatibility. Alright, I guess I'll close this then.
