### ISSUE TITLE
Port docker cgroup limits fixes to 2.0.x

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#13699]
See #13488

**Comment by Petermarcu** [comment]
@janvorli can you send the email out for review of this one to shiproom?

**Comment by janvorli** [comment]
@Petermarcu I will create a PR for the port (this is just an issue tracking it) and send the email.

**Comment by janvorli** [comment]
Fixed by #13895

**Comment by mhalenar** [comment]
hi guys, is there any plan for LXD (lxc) cgroup limits fixes?

**Comment by janvorli** [comment]
@mhalenar the cgroups limits fixes already made should not be specific to docker, so if it doesn't work with lxd, please let me know. Please note that the official 2.0 runtime in the released 2.0 cli doesn't contain the fix yet, so you'd need to use prerelease 2.0.3 or higher runtime to get the fix.
