### ISSUE TITLE
Version Information in libcoreclr.so is Invalid

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#13702]
When running strings libcoreclr.so | grep "@(#)", I get the output below.  The Commit hash is correct, but the built by information is broken:

@(#)Version 4.6.25610.02 built by: root-/tmp/tmpc8563550a3e548e99ca2d5896043f8ba.exec.cmd: line 2: hostname: command not found. Commit: dc2ffcdff2fb19e4b252cec3bc6672400a375c1e

**Comment by brianrob** [comment]
@wtgodbe, do you know the right person to route this to?

**Comment by wtgodbe** [comment]
Not sure, but @janvorli might know where to start

**Comment by brianrob** [comment]
Thanks.  @janvorli, any ideas on this one?

**Comment by janvorli** [comment]
The broken hostname in the version is a known problem - the hostname app is missing on some build machines. I think the decision was to remove it completely since it doesn't provide any useful information.

**Comment by brianrob** [comment]
Ok, thanks.  Is there an issue that I should resolve this as a duplicate of?

**Comment by mellinoe** [comment]
https://github.com/dotnet/coreclr/issues/10770

**Comment by brianrob** [comment]
Duplicate of #10770.
