### ISSUE TITLE
Add TypeInfo.GetDeclaredProperties(string name)

### ISSUE THREAD

**Issue by kingces95** [dotnet/coreclr#13714]
Given `TypeInfo.GetDeclaredMethods(string name)` I expect `TypeInfo.GetDeclaredProperties(string name)` to exist, but it does not.

In general, I expect reflection to provide symmetric functionality for `MemberInfos` that share a common dimension. For example, both `MethodBase` and `PropertyInfo` have parameters. So given `MethodBase.GetParameters` I expect to find an API with similar functionality for properties and I do, namely `PropertyInfo.GetIndexParameters`. For that reason, given `TypeInfo.GetDeclaredMethods(string name)` I expect to find an API with similar functionality for properties, namely `TypeInfo.GetDeclaredProperties(string name)`.

From a C# perspective, only indexers are exposed as properties with the same name (e.g. "Item"). For example, the following program will throw an `AmbiguousMatchException` (see [fiddle](https://dotnetfiddle.net/Tgw5IM)). 

````C#
public abstract class Indexers {	
	public abstract int this[int i] { get; }
	public abstract int this[string s] { get; }
}

public class Program {	
	public static void Main()
		=> typeof(Indexers).GetTypeInfo().GetDeclaredProperty("Item");
}
````
However reflection is supposed to be language agnostic and other languages could provide syntax to emit properties with arbitrary matching names but different signatures. For example, using ILASM this can easily be done.

**Comment by AtsushiKan** [comment]
Functionality-wise, we're already covered: `GetDeclaredProperty(name)` would be `type.GetProperty(name, BF.Public|NonPublic|Instance|Static|DeclaredOnly`.

While there's a valid symmetry argument here, the fact is that `TypeInfo` is a dead-end as far as future api evolution goes. It's purpose was to replace `Type` as the main source of truth about type definitions (with `Type`'s surface area being significantly reduced and used for the purpose of representing type references.) That effort sank like a lead balloon in the market so at this point, `TypeInfo` exists only for backward compatibility and we expect it to fade out of sight over time.

**Comment by kingces95** [comment]
> fade out of sight over time

I'm under the impression there is no process for removing APIs once they're added to a .NET Standard. Am I mistaken?

**Comment by AtsushiKan** [comment]
We won't remove `TypeInfo` - we just won't encourage its use in new code.

**Comment by kingces95** [comment]
Should we consider the extension methods on `CustomAttributeExtensions` to be similarly discouraged from use now that `ICustomAttributeProvider` is back or are we still open to suggestions for those APIs?

**Comment by AtsushiKan** [comment]
I see `CustomAttributeExtensions` as a viable path for future api extensions. Unlike `TypeInfo`, its existence is not "in the developer's face" the way `GetTypeInfo()` is and unlike the interface, we can add generic apis without paying the perf costs of generic virtuals.

**Comment by EvilBeaver** [comment]
> We won't remove TypeInfo - we just won't encourage its use in new code

Does this mean that internals of ASP.NET Core MVC will be overwritten to some another class? 
Now TypeInfo is everywhere in Controllers creation pipelilne, and thos means we have to write our new code dependent on TypeInfo.

**Comment by AtsushiKan** [comment]
>Does this mean that internals of ASP.NET Core MVC will be overwritten to some another class?

I don't own any part of ASP.NET so I can't speak on that. As I said, `TypeInfo` isn't going away - it just isn't going to be further evolved or actively promoted as it's redundant with `Type`.

**Comment by RussKeldorph** [comment]
Assuming resolved.  Please re-open if there is more discussion necessary.
