### ISSUE TITLE
Add GenericMethodParameters and GenericMethodArguments to MethodInfo

### ISSUE THREAD

**Issue by kingces95** [dotnet/coreclr#13737]
Most APIs that deal with generic arguments are symmetric across `Type` and `MethodInfo`. For that reason given `Type.GenericTypeParameters` and `Type.GenericTypeArguments` I expect `MethodInfo.GenericMethodParameters` and `MethodInfo.GenericMethodArguments` to exist.

| Type | MethodInfo |
| ---- | ---- |
| IsGenericType | IsGenericMethod |
| IsGenericTypeDefinition | IsGenericMethodDefinition |
| GetGenericArguments | GetGenericArguments |
| GetGenericTypeDefinition | GetGenericMethodDefinition |
| MakeGenericType | MakeGenericMethod |
| ContainsGenericParameters | ContainsGenericParameters** |
| GenericTypeArguments |  |
| GenericTypeParameters |  |

** Inherited from `MethodBase`

**Comment by AtsushiKan** [comment]
@kingces95 - can you reopen this issue in the dotnet/corefx repo? That's where "api request" issues need to be in order to get through to the end of the process. Thanks.

**Comment by kingces95** [comment]
Ok, thanks. https://github.com/dotnet/corefx/issues/23741

**Comment by AtsushiKan** [comment]
Moved to corefx.
