### ISSUE TITLE
JIT\Methodical\Arrays\misc\arrres fails with Conservative GC

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#1373]
> set COMPLUS_GCConservative=1
coreclr\bin\tests\Windows_NT.x64.Debug\JIT\Methodical\Arrays\misc>arrres.cmd
BEGIN EXECUTION
"\coreclr\bin\Product\Windows_NT.x64.Debug\corerun.exe" "arrres.exe"
Unhandled Exception: System.Exception: Exception of type 'System.Exception' was thrown.
   at GCTest.Test.Test3()
   at GCTest.Test.Main()
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED

**Comment by RussKeldorph** [comment]
I'm not sure how interesting this is.  @swaroop-sridhar do we need to support Conservative GC?

**Comment by swaroop-sridhar** [comment]
Yes, we don't support conservative GC.
I filed the bug while working on LLILC, because the JIT used conservative GC for bringup.
