### ISSUE TITLE
project.assets.json need to be all-platform/architecture

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#13758]
It looks like some of these:

```
tests\src\Common\build_against_pkg_dependencies\obj\project.assets.json
tests\src\Common\external\obj\project.assets.json
tests\src\Common\stress_dependencies\obj\project.assets.json
tests\src\Common\targeting_pack_ref\obj\project.assets.json
tests\src\Common\test_dependencies\obj\project.assets.json
tests\src\Common\test_runtime\obj\project.assets.json
tests\src\Common\vc_runtime\obj\project.assets.json
```

are built specific to the build you’ve just done (e.g., x86), instead of being “all platform”. E.g.,

```
tests\src\Common\test_runtime\obj\project.assets.json
```

has:

```
"runtimes": { "win-arm": { "#import": [] } }                                  
```

after I've done an ARM build. Then, when I try to do an x86 layouts, even though I have previously done a full x86 build including tests, I get:

```
E:\gh\coreclr2\tests\publishdependency.targets(49,5): error : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win-x86": { } }' to your project.json and then re-run NuGet restore. [E:\gh\coreclr2\tests\runtest.proj]
```

Looks like possibly a regression due to 6c0e0abf7c7b2ab48671ec2e37ff925fb5ca9c80

**Comment by BruceForstall** [comment]
@wtgodbe It looks like this is still a problem. Can you please take a look? This regression prevents doing both x86 and arm builds/layouts on the same enlistment, which I need to do frequently.

cc @dotnet/jit-contrib

**Comment by mikedn** [comment]
This impacts my workflow as well. I looked into having separate `obj` subfolders for each architecture, like we have in other projects, but I couldn't get things to work.

**Comment by wtgodbe** [comment]
Sorry for the delay, I'll look into this today.

**Comment by wtgodbe** [comment]
I believe this should be resolved by https://github.com/dotnet/coreclr/issues/14048, @BruceForstall if you're still having issues feel free to reopen this & ping me
