### ISSUE TITLE
Linux stack size seems 8x bigger than windows?

### ISSUE THREAD

**Issue by Drawaes** [dotnet/coreclr#13765]
I was writing a little function to show the remaining stacksize in core.
(Best not to ask why ;) )

But I thought I had the calculations wrong, so I tried a couple of ways. In the end I can only come to the conclusion that on Linux .net core has an 8mb stack not a 1mb stack. 

This is easily confirmed by stackallocing 3mb of data and on Windows this crashes and on Linux it doesn't.

My question is, is this correct, and if it is ... why the big difference?

Repro code here 

[Program.cs](https://github.com/Drawaes/dotnetXperiments/blob/master/HowMuchStack/Program.cs)

**Comment by Drawaes** [comment]
To add more information

This happens on the main thread, spawned foreground threads and background threads.

Turns out that my ulimit (default one) on ubuntu is 8mb. If I set this to unlimited all threads default to 2mb. Does this seem like unusual behaviour? As .net is a VM shouldn't this part of the environment be realitively consistent across platforms?

**Comment by stephentoub** [comment]
> As .net is a VM shouldn't this part of the environment be realitively consistent across platforms?

It also needs to respect the platform. The user limit is set to 8mb... why should the VM override that by default?

**Comment by Drawaes** [comment]
No reason I guess, just surprising, .net framework has always had this basic size and mono followed close for compatibility. It's not a problem if it's expected.
