### ISSUE TITLE
[Legacy Backend][StackFP] sort algorithm for fpLclFPVars seems incorrect

### ISSUE THREAD

**Issue by 303248153** [dotnet/coreclr#13770]
Problem line:
https://github.com/dotnet/coreclr/blob/bac965ea8d3977a08257ee6758e14ccda34547e3/src/jit/stackfp.cpp#L4328

I think it should be
``` c++
if (raVarIsGreaterValueStackFP(fpLclFPVars[i], fpLclFPVars[min]))
```
The `min` should point to the var have greatest weight, not the last var have greater weight than `sortNum`.

And another problem line:
https://github.com/dotnet/coreclr/blob/bac965ea8d3977a08257ee6758e14ccda34547e3/src/jit/stackfp.cpp#L3725

It should be
``` c++
return int(lv1->lvRefCnt - lv2->lvRefCnt) > 0 ? true : false;
```
The var have most refcnt should go first.

I'm not sure I'm right, if it looks OK I can open a PR.

**Comment by mikedn** [comment]
> if it looks OK I can open a PR

Note that RyuJIT does not actually use the FP stack code, that's a legacy thing.

**Comment by RussKeldorph** [comment]
These look like good catches, but I don't think we'd take fixes for them.  We're keeping legacy backend around for now for comparison purposes, but there's no interest in improving it.  I'd recommend closing this issue unless someone objects.

@dotnet/jit-contrib

**Comment by 303248153** [comment]
Well, I understand that, first i didn't notice it's legacy backend.
I'll close it now.
