### ISSUE TITLE
[Arm64] JIT optimize len %= 64

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#13787]
@dotnet/arm64-contrib @dotnet/jit-contrib 

`len %= 64;` is generating 

```
    lsr     x0, x21, #6
    lsl     x0, x0, #6
    sub     x21, x21, x0
```

Should be 
```
    and x21, x21, 0x3f
```

**Comment by mikedn** [comment]
Hmm, presumably `len` is `ulong`?

This looks like an issue with morph, it converts UMOD to UDIV+LSH+SUB (AFAIR because ARM doesn't have a mod instruction). It shouldn't do this transform when the second operand is a constant, lower takes care of that case (for x64/86 currently).

**Comment by sdmaclea** [comment]
> presumably len is ulong?

`len` is `nuint` which is `System.UInt64` for arm64.  So yes.

**Comment by sdmaclea** [comment]
Also need to fix `NYI("genCodeForMulHi");`

@karelz @jashook Please assign this to me.
