### ISSUE TITLE
[Arm64] JIT optimize `if ((len & 24) == 0) goto `

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#13790]
`if ((len & 24) == 0) goto MCPY03;` is generating

```
        and     w0, w24, #24
        cmp     w0, #0
        beq     G_M55607_IG12
```
This could be
```
        ands    w0, w24, #24
        beq     G_M55607_IG12
```
or
```
        and     w0, w24, #24
        cbz     w0, G_M55607_IG12
```

**Comment by mikedn** [comment]
Note that `Lowering::LowerCompare` already does this for x86/64. For ARM this requires adding support for GT_TEST_EQ/NE in CodeGen.

**Comment by sdmaclea** [comment]
@mikedn @jashook Unless someone else wants this, please assign to me.

**Comment by mikedn** [comment]
I think I have it mostly working in https://github.com/mikedn/coreclr/tree/and-cmp-arm64. 

However, I'm not very familiar with ARM64 assembly and I have no hw to test on. In particular, I haven't checked if `tst` supports the same immediate range as `cmp` or if `tst` is properly encoded (the internal JIT diassembler can't be trusted in this case). 

Feel free to finish it.

**Comment by sdmaclea** [comment]
@Mikedn Thanks I'll take a look.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib @dotnet/arm64-contrib
