### ISSUE TITLE
[RyuJIT/ARM32] CI for RyuJIT/ARM32

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#13804]
There is a need for CI for RyuJIT/ARM32 as RyuJIT/ARM32 has passed almost all unit tests.

However as discussed at #13585, it is not desirable to use existing QEMU environment for RyuJIT/ARM32.
Instead, Windows RyuJIT/ARM32 will be available and is being introduced at #13664.

This issue will track all RyuJIT/ARM32 issues.

**Comment by JensNordenbro** [comment]
Is this the thing that eventually will enable crossgen on Linux ARM? (My impression is that crossgen is not done today due to legacy backend, but I could be wrong).

**Comment by hqueue** [comment]
> Is this the thing that eventually will enable crossgen on Linux ARM? (My impression is that crossgen is not done today due to legacy JIT backend, but I could be wrong).

Not really. This issue tracks issues about RyuJIT/ARM32 CI which runs at runtime, not RyuJIT/ARM32 invoked from crossgen.
BTW  `crossgen` already works with existing legacy JIT backend.

**Comment by hqueue** [comment]
@BruceForstall all I see your comment at https://github.com/dotnet/coreclr/issues/8496#issuecomment-330689180.
I want to track ryujit CI issues here, what do you think of it?

And I have a question.  I found that there are two legs running, i.e.  `Windows_NT arm Cross Checked Build and Test` and `Windows_NT armlb Cross Checked Build and Test`. According to your comment(https://github.com/dotnet/coreclr/issues/8496#issuecomment-330689180), I think `arm` uses ryujit and `armlb` uses legacy backend.

Does `Windows_NT arm Cross Checked Build and Test` use RyuJIT/ARM32 on Windows ? Then where can I found a script for this run ?

**Comment by BruceForstall** [comment]
@hqueue What are the specific ARM32 CI issues that need to be tracked? My preference would generally be to open individual issues for each specific issue, unless there are a large number of similar issues that should be tracked here, all together.

You are correct:

|job name|JIT|
|---|---|
|Windows_NT arm Cross Checked Build and Test|RyuJIT/arm32|
|Windows_NT armlb Cross Checked Build and Test|arm32 LEGACY_BACKEND|

These jobs are triggered for every PR (for users on the ARM64 machine "white list"). There are additional jobs available for various stress modes, e.g.:

|job name|mode|
|---|---|
|Windows_NT arm Cross Checked jitstress1 Build and Test|RyuJIT/arm32, COMPlus_JitStress=1|
|Windows_NT arm Cross Checked jitstressregs4 Build and Test|RyuJIT/arm32, COMPlus_JitStressRegs=4|

> Does Windows_NT arm Cross Checked Build and Test use RyuJIT/ARM32 on Windows ?

Yes, it does.

>  Then where can I found a script for this run ?

Do you mean: how can I do this build and test run?
1. You can build on Windows using "build.cmd arm checked". See https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md and https://github.com/dotnet/coreclr/blob/master/Documentation/building/cross-building.md.
2. Unfortunately, we haven't open sourced the test harness we've been using to invoke arm tests on Windows.

**Comment by JensNordenbro** [comment]
@hqueue ; So the reason I ask is that today I run asp.net core in a couple of different ways on Yocto Linux-ARM. 
Regardless if I use 

- The tar.gz files provided at core-setup readme.md. 
- Tragetaschen repo
- SCD on Linux arm-rid

.. I get slow startup performance. Once up and running it felt ok so that made me assue JITing was the culprit. 

In neither solution, mentioned above, I can find neither

- Crossgen.exe

- dll.ni files

[Peeking quickly at the Tragetaschen repo](https://github.com/Tragetaschen/meta-aspnet/search?utf8=%E2%9C%93&q=crossgen&type=) it looks like crossgen is not activated in this build script. Maybe this is a misstake or maybe this is unrelated to my problem. 
Regardless, I would be greatful for more details on how to activate crossgen capabilities or how to determine if JIT is the problem or not!

**Comment by hqueue** [comment]
> @hqueue What are the specific ARM32 CI issues that need to be tracked? My preference would generally be to open individual issues for each specific issue, unless there are a large number of similar issues that should be tracked here, all together.

@BruceForstall  I also agree. Than I think we can close this issue, because I wanted to discuss enabling RyuJIT/ARM32 CI here. And now `Windows_NT arm Cross Checked Build and Test` is enabled.


>> Then where can I found a script for this run ?
> 2. Unfortunately, we haven't open sourced the test harness we've been using to invoke arm tests on Windows.

I asked this question because I want to see exact options when building and running tests.  But unfortunately, it's not available. 

Then can you share us a full set of `COMPlus` options used for `Windows_NT arm Cross Checked Build and Test` and other tests you mentioned above ?
I think `COMPlus_AltJit=* COMPlus_AltJitNgen=*` are used when invoking ryujit/arm32 CI, right?

**Comment by hqueue** [comment]
@JensNordenbro Right. Startup performance in arm is somewhat slow now and `crossgen` can improve the startup performance. Becuase crossgen is not fully brought up yet, it is not enabled by default for ARM32 now. We are now working on crossgen in arm32 and I think we can open new issue discussing start up performance of arm32 if you want. You can find out issues and PR regarding arm32 crossgen at https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=%20label%3Aarea-CrossGen%2FNGEN%20

**Comment by JensNordenbro** [comment]
I think this is worth an issue of its own; Today it is hard to decide on doing ARM stuff on .NET Core until this is resolved.

**Comment by BruceForstall** [comment]
All the RyuJIT/arm32 issues are collected here: https://github.com/dotnet/coreclr/projects/4

I only see one ReadyToRun issue, and no general crossgen issue. Maybe there should be one (or more)?

**Comment by BruceForstall** [comment]
> Then can you share us a full set of COMPlus options used for Windows_NT arm Cross Checked Build and Test and other tests you mentioned above ?
> I think COMPlus_AltJit=* COMPlus_AltJitNgen=* are used when invoking ryujit/arm32 CI, right?

@hqueue yes, although I noticed we weren't setting AltJitNgen (that's a mistake; we should set it).

`jitstressX` modes set `COMPlus_JitStress=X` for X=1 or 2.
`jitstressregsX` modes set `COMPlus_JitStressRegs=X` for X=1, 2, 3, 4, 8, 0x10, 0x80, or 0x1000.
gcstress0x3 mode sets `COMPlus_GCStress=0x3`
gcstress0xc mode sets `COMPlus_GCStress=0xC`
tailcallstress mode sets `COMPlus_TailCallStress=1`
minopts mode sets `COMPlus_JitMinOpts=1`
zapdisable mode sets `COMPlus_ZapDisable=1`

I also normally set
```
COMPlus_NoGuiOnAssert=1
COMPlus_ContinueOnAssert=0
COMPlus_AltJitAssertOnNYI=1
```
(and I'll make a change the the CI to set these also)

**Comment by hqueue** [comment]
@BruceForstall Thank you for the information :)

And I will close this issue.
