### ISSUE TITLE
GC not uncommiting memory

### ISSUE THREAD

**Issue by iburman** [dotnet/coreclr#13807]
Scenario - we have multiple services running under IIS, one per worker process, on Windows 2012 R2 with 16 cores. Using ServerGC.

Problem - CLR keeps large amount of memory uncommitted, much more than required to store our active objects. As there are multiple servers, at some point we reach a condition where IIS can't start a new service for lack of memory on the machine, as well as some other performance issues.

We understand that Server GC creates one heap per core and that the segment's size on this server is 64MB but our problem is that CLR doesn't uncommit memory when it could.

We considered some workarounds but none is worth it:

1 - Use workstation GC - solves the memory issue but downgrades significantly performance

2 - Affinitizing each process to some cores - solves the memory issue but creates other problems, like:
how to distribute the cores between the processes
reduced performance - our algorithms don't use a lot of memory but require a lot of CPU, so limiting the processors affects performance
finally - we have a large customer base, each customer with different server configurations, so we would have to find the optimal solution at an individual base, which we want to avoid.

Through some experimentation we figured out on a Windows 7 machine still with Server GC but now with 16 MB segments, that CLR still keeps many segments committed, like on the server. However, when we called GC.Collect multiple times in a row, the CLR started to uncommit memory in small chunks, until just one segment per heap stayed committed. It didn't go below that,  so we assume that CLR will keep at least the first segment of each heap totally committed forever.

We are looking for a solution to that like:

Option 1 - to be able to set the size of the segments.  This can be done using SetGCStartupLimits but only if you host the CLR. I couldn't find a way to set this value through a configuration parameter. Is there such an option through configuration? 

Option 2 - configure the CLR to be more aggressive in uncommiting memory, including uncommit memory in the first segment of each heap if possible. Is there any option to change how CLR uncommits memory?

I believe that a combination of 1 and 2 would be ideal.

Option 3 - probably not a good one, but in case we can't use neither 1 or 2, is there a way to ask CLR not to create one heap per core. For example, set just one heap per each 2 cores, or each 4 cores? In other words, accomplishing the same as with affinitizing the processes by reducing the number of heaps without limiting the access to the CPUs, and without having to decide how to split the cores between the processes.

Any other alternative?

Thanks
Israel

**Comment by benaadams** [comment]
> Any other alternative?

Run in 32bit mode? :-/ https://github.com/dotnet/coreclr/issues/11338

**Comment by swgillespie** [comment]
cc @Maoni0 

Options 1 and 2 are covered by this issue (and Ben's link above): https://github.com/dotnet/coreclr/issues/13292. We are envisioning something like a "latency level", where you can select a level that optimizes most for the aspects of GC performance that you care about - in your case, keeping committed memory low. (In particular: https://github.com/dotnet/coreclr/issues/13292#issuecomment-321729506).

Setting the segment size directly isn't exposed through the .NET Core SDK/.NET Framework at the moment (other than the hosting API).

As for this:

> Option 3 - probably not a good one, but in case we can't use neither 1 or 2, is there a way to ask CLR not to create one heap per core.

There is no officially supported way to do this, but *unofficially* you can use the `COMPlus_GCHeapCount` environment variable to control the number of heaps created for ServerGC. I just checked and .NET Framework 4.7 and .NET Core 2.0 shipped with this config key available. You may also want to combine it with `COMPlus_GCNoAffinitize` (setting to 0 or 1) which will disable/enable the affinitization of server GC threads to cores.

**Comment by iburman** [comment]
@benaadams - 32 bit mode may not be an option because we also call into native, so would require 32 bit native dlls. I read #11338 and some ideas there when available would be helpful in our scenario.

@swgillespie - any idea when these "latency level" options would be available?

In regards to setting the segment size, any reason why this option  is available only through the hosting API? It seems to me that having this flexibility through configuration may benefit many scenarios where more control over memory consumption is required. It would be really nice to have it.

As for the COMPlus environment variables I have a few questions:

1 - If we end up using this as an option due to lack of anything else, what's the risk of it suddenly not to be available in some future release? As it's not supported I have some concerns.

2 - Please correct me if I'm wrong, but by setting this through environment variable, it affects all process running on the machine, right? Or is there a way to limit the effect of an environment variable to a specific process (running in IIS)? If the first is the case then we may run into problems as  we have a large customer base using our system, and they certainly wouldn't like to have us dictate how other services should run on their machines. I would like to give this a try; is there a way to set it at a process level?

Thanks!

**Comment by Maoni0** [comment]
I am puzzled - if you are on 16-core and using Server GC, the only way you could get 64mb per seg would be LOH segs on 64-bit on an older version of the CLR. at some point (I can't remember exactly when, perhaps around 4.6/4.5 timeframe) I changed it so that we don't make the LOH seg smaller based on the # of cores but that would make it 256mb. If you are on 32-bit you can't get 64mb to begin with on 16-core - you would get 16mb for SOH segs and 8mb for LOH segs. 

Can you please elaborate the reasons why you can't use hosting APIs? the SetGCStartupLimits hosting API is for this purpose...

**Comment by iburman** [comment]
@naomi0

I'm a consultant working with an ISV to help them solve this problem. I may need to return to them to get additional information based on your input, but let me tell you what I know so far:

1 - We are not on 32 bits; we are on 64 bits.

2 - The services are hosted in IIS which is a CLR host by itself. I guess that having them create their own host would be some additional pain. I'm not sure if they want to go in this direction, I would have to check. But again, is there a reason why this setting is only available through the hosting APIs and not through a configuration parameter?

3 - It isn't a LOH issue; more below.

What I have seen:
The service I looked at shows 1.7 GB committed memory. VMMap and DotMemory  show majority of it as being managed heap. I don't remember the exact number but it was about 1.3 or so.. DotMemory shows 1.3 as allocated to Gen0.

dumpheap -stat shows a total of memory consumed by objects around 400 MB.

The committed memory didn't go down despite forcing GC multiple times in a row, without sending new requests to the service, so no new objects were being created.

I checked pinned objects and there were a few, around 10. I didn't check them individually where they are located but I assume that if they would be creating large free buffers, I would see it in dumpheap -stat as large free blocks. Is my assumption right?

As for the size of the segments for Gen 0 to Gen2 , are you saying that they shouldn't be 64MB at all on a Windows 2012 R2 server, on a 64 bits process using Server GC? Can you please confirm I understood this correctly so I can go back and look at this again?

4 - Perfmon - I had a hard time using the .Net memory counters on this machine. For the services running under IIS they showed as 0 most of the time. Sometimes for a short time they showed up and returned to zero after that. The counters worked fine on a small test application running standalone using workstation GC. Do you or anybody else experienced similar problem? Any idea why this would happen?

Thanks.

**Comment by Maoni0** [comment]
Yes, I am saying there's no way, unless your host has already done some configuration, that you would have a 64mb or 16mb segment on 64-bit with Server GC. all SOH segments have the same size.

We intentionally did not allow an easy way to configs segment size. Segment size is an internal tuning parameter in GC and most of the time people should not be messing with it so it was only available to change in hosting APIs. 

I am not sure what's happening with perfmon. Is it possible to collect some ETW events instead? that would be the best way to figure out what's going on. 

```perfview /GCCollectOnly /nogui /accepteula /NoV2Rundown /NoNGENRundown /NoRundown /merge:true /zip:true collect```

run your scenario

after you are done, press s in the perfview cmd window to stop it

This should be run long enough to capture enough GC activities, eg, if you know problems occur at times, this should cover time that *leads* up to when problems happen (not only during problematic time).

If you know how long to run it for you can do 

```perfview /GCCollectOnly /nogui /accepteula /NoV2Rundown /NoNGENRundown /NoRundown /merge:true /zip:true /MaxCollectSec:1800 collect ```

replace 1800 (half an hour) with however many seconds you need. This command is lightweight so it can be on for a long time.

**Comment by iburman** [comment]
@naomi0
To finalize this thread: The customer experimented with the HighDensityWebHosting setting which improved the situation. They are happy with the results and don't want to spend time on further investigating what was going on, at least for the moment.
Thanks a lot for your input.

**Comment by janvorli** [comment]
@iburman I guess you meant to reference @Maoni0

**Comment by Maoni0** [comment]
Ok that's fine. Is it ok to close this issue?

**Comment by iburman** [comment]
@Maoni0 
Yes, I'm closing it now. Again, thanks for your help. And sorry for mistyping your alias.
@janvorli - thanks for catching the mistyping.
