### ISSUE TITLE
DCR: Review ReferenceCountedDisposable as an alternative to IRetainable

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/coreclr#13840]
Design Change Request (DCR)
From https://github.com/dotnet/coreclr/pull/13583#issuecomment-325162865:
> :bulb: My strongest recommendation here would be to carefully review the semantics of [`ReferenceCountedDisposable<T>`](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Utilities/ReferenceCountedDisposable.cs) in Roslyn and consider how they might be usable in these scenarios as an alternative to `IRetainable`. This type provides strong guarantees in concurrent code and eliminates many concerns related to ownership when both `IDisposable` and `IRetainable` are at play. It also provides a weak reference type with strong semantic guarantees.

cc @KrzysztofCwalina, @shiftylogic

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#23870

**Comment by jkotas** [comment]
corefx is better place for API design discussions.

**Comment by ahsonkhan** [comment]
> corefx is better place for API design discussions.

Sounds good. Thanks.
