### ISSUE TITLE
[Arm64] Enable LowerCompare cast removal

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#13864]
Note, this will merge conflict with #13799.

**Comment by mikedn** [comment]
Are you talking about this bit of code?

https://github.com/dotnet/coreclr/blob/72201862c9b646ca651b686c5d7df9b71ca033e8/src/jit/lower.cpp#L2418-L2455

That relies on x86/64 having 8 bit comparison instructions. Does ARM have that? My impression is that its instructions are 32/64 bit only.

**Comment by sdmaclea** [comment]
Yes.  I didn't look at the code closely.  I thought it was removing a cast on op2, the integral constant.

**Comment by sdmaclea** [comment]
@mikedn if the compare is GT_NE or GT_EQ and the immediate is 0, the compare can be a `tst op1, #0xff`
Also would work for `tst op1, #0xffff`.  

Is that worth enabling for arm64?  It might cover a large part of the xarch optimization

**Comment by mikedn** [comment]
If memory serves me well this particular optimization mostly impacts byte/bool calls. As in:
```C#
if (Environment.HasShutdownStarted)
    Console.WriteLine("kboom");
```
On x64 this generates a 8 bit `test al, al` to avoid the cast:
```asm
       E85D11AB5F           call     System.Environment:get_HasShutdownStarted():bool
       84C0                 test     al, al
       7410                 je       SHORT G_M55888_IG03
```
On ARM64 the same code generates:
```asm
        94000000          bl      System.Environment:get_HasShutdownStarted():bool
        53001C09          uxtb    w9, w0
        7100013F          cmp     w9, #0
        540000C0          beq     G_M55888_IG03
```
If `tst op1, #0xff` is used then `uxtb` can be eliminated. It seems useful to do this since `bool` returning methods are relatively common. 

But there's a catch: the JIT appears to insert the cast to byte only if the callee is NGENed. I think it does this to maintain compatibility with old NGEN images generated by JIT64 which did not widen `bool` to 32 bit. That would mean that the cast should not be inserted at all on ARM64 since there is no compat story.

**Comment by mikedn** [comment]
> I think it does this to maintain compatibility with old NGEN images generated by JIT64 which did not widen bool to 32 bit. 

Not sure who knows the exact story. Perhaps @briansull ?

**Comment by briansull** [comment]
I don't believe that you can rely upon calls to widen byte/char/bool values.
The native C++ compiler will return values in just the lower 8/16 bits and leave garbage in the upper bits.  Call that go to managed code will always widen the result to 32-bits.

**Comment by sdmaclea** [comment]
> The native C++ compiler will return values in just the lower 8/16 bits and leave garbage in the upper bits

For arm64 it seems like that would be hard to do, but I am OK with just being safe as it does not add much complexity.

**Comment by mikedn** [comment]
I see that ARM64 GCC (on https://gcc.godbolt.org/) too uses `tst w0, 255` because the callee does not widen:
```C
char __attribute__((noinline)) Test(int b) { return b; }
void Test2(int x, int y) { if (Test(x == y)) printf("\n"); }
```
```asm
Test(int):
        ret
Test2(int, int):
        stp     x29, x30, [sp, -16]!
        cmp     w0, w1
        cset    w0, eq
        add     x29, sp, 0
        bl      Test(int)
        tst     w0, 255
        bne     .L6
        ldp     x29, x30, [sp], 16
        ret
.L6:
        ldp     x29, x30, [sp], 16
        mov     w0, 10
        b       putchar
```

**Comment by sdmaclea** [comment]
Sounds like we are agreed the optimization is useful for arm64.  #13878 is my proposed implementation.

**Comment by mikedn** [comment]
> Sounds like we are agreed the optimization is useful for arm64

It looks like I forgot to mention that disabling this optimization on x64 results in significant regression - 100K AFAIR - and most cases involve bool callees. So yes, it should be quite useful on arm64 as well.
