### ISSUE TITLE
[Arm64] LowerCompare enable lowering mixed type comparisons.

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#13860]
@dotnet/jit-contrib 

Should this section be enabled for `_TARGET_64BIT_` (amd64+arm64) ?  Or is there a reason it is an am64 specific issue?
https://github.com/dotnet/coreclr/blob/master/src/jit/lower.cpp#L2350-L2392

**Comment by mikedn** [comment]
Hmm, it depends on how does the ARM64 codegen handle mixed type comparisons. It's probably best to enable that code for ARM64 as well to avoid surprises. Maybe one day someone will fix loop cloning to not produce this kind of comparisons.

**Comment by sdmaclea** [comment]
@mikedn Thanks

**Comment by sdmaclea** [comment]
This will also merge conflict with #13799

**Comment by mikedn** [comment]
It looks like ARM64 codegen does handle mixed type comparisons:
https://github.com/dotnet/coreclr/blob/72201862c9b646ca651b686c5d7df9b71ca033e8/src/jit/codegenarm64.cpp#L3482-L3502

Probably not a good idea as it results in code duplication and accidental behavior differences between ARM64 and x64.

**Comment by sdmaclea** [comment]
> Probably not a good idea as it results in code duplication and accidental behavior differences between ARM64 and x64.

@mikedn Translation "It should be removed from codegen, because lowering should do this."  Is that what you meant?

**Comment by mikedn** [comment]
> "It should be removed from codegen, because lowering should do this." Is that what you meant?

Yes.

**Comment by sdmaclea** [comment]
Fixed by #13941
