### ISSUE TITLE
[Arm64] JIT/opt/Enum/hasflag/hasflag.sh fails

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#13917]
```
corerun hasflag.exe

Assert failure(PID 19790 [0x00004d4e], Thread: 19790 [0x4d4e]): Assertion failed 'isValidGeneralDatasize(size)' in 'P:ByrefG(byref,ubyte):bool' (IL size 19)

    File: src/jit/emitarm64.cpp Line: 5160
    Image: bin/tests/pr1/Tests/coreoverlay/corerun
```

**Comment by sdmaclea** [comment]
@AndyAyersMS @dotnet/arm64-contrib This is a new test added in #13748

**Comment by AndyAyersMS** [comment]
Could be the new code is violating some assumption about operand sizes. But first, does this repro with COMPlus_JitMinOpts=1? If so it's a pre-existing issue.

**Comment by sdmaclea** [comment]
@AndyAyersMS This does repro with `COMPlus_JitMinOpts=1`

**Comment by AndyAyersMS** [comment]
In that case, can you or somebody on arm64-contrib investigate further? 

The optimization added with the test should not fire in minopts. Possibly the non-default sized enums used in the test have uncovered some pre-existing issue in ARM64 codegen?

**Comment by sdmaclea** [comment]
Looks like the issue is arm64 is using `emitTypeSize` when it should be using `emitActualTypeSize`.  The former should be used for memory operations, the latter for register operations.

**Comment by sdmaclea** [comment]
The assertion is on an and operation with byte size operands.

**Comment by mikedn** [comment]
> The assertion is on an and operation with byte size operands.

Clear case of missing "actual type" somewhere :)

**Comment by sdmaclea** [comment]
@jashook You can assign to me as I already created a PR.
