### ISSUE TITLE
sos DumpLog failed on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by Jamesxql** [dotnet/coreclr#13935]
I've used lldb-3.6 to attach a asp.net core application on ubuntu 16.04.3-x64, and I load the sos plugin with the below 
```sh
plugin load /usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libsosplugin.so
setclrpath /usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.2
```
Then I use `dumplog` command to generate stress log, but I receive this error: 
```sh
Attempting to dump Stress log to file 'StressLog.txt'
----- No thread logs in the image: The stress log was probably not initialized correctly. -----
No Stress log in the image, no file written
DumpLog  failed
```

Did I do something wrong?

**Comment by janvorli** [comment]
Have you turned on the stress log before running the app by setting the `COMPlus_StressLog env` var to 1?

**Comment by Jamesxql** [comment]
@janvorli Whether I must set the `COMPlus_StressLog ` environment variable before the dotnet application starts?

**Comment by janvorli** [comment]
@Jamesxql yes, correct.

**Comment by Jamesxql** [comment]
@janvorli Thank you very much!
