### ISSUE TITLE
Improve lock contention problem on Linux 

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#13949]
Fora  while now there has been an issue where MSBuild of tests in the CoreCLR project took substantially longer on Linux than on Windows.   (it was taking 31 minutes to build on Linux rather than something less than half that on Windows).   

@rartemev  tracked this down (see  https://github.com/Microsoft/msbuild/pull/2513)  

Most of the time was spent in monitor spinning an lock contention.  

  59.63%  dotnet   libcoreclr.so                         [.] Object::EnterObjMonitorHelperSpin
  18.21%  dotnet   libcoreclr.so                         [.] AwareLock::Contention

Now this build was highly concurrent (100s of concurrent builds), so it is not surprising that there is lock contention in MSBUILD.   However, a key issue is that any spinning that MSBUILD does is very likely taking away CPU from USEFUL compilations.    Thus our algorithms that tend to produce alot (too much) spinning which what was causing the problem.

The fix @rartemev pursued was in MSBUILD itself to avoid making the locks so hot.  This is a  good fix (making msbuild more scalable), but what is definitely true is that HOT LOCKS will happen, and so we need to insure that the runtime itself deals with this situation as best it can.   In particular 

Linux locks should not perform 2X worse than Windows locks even in hot lock case.

This is what this Issue is about.
 
@rartemev can you supply the traces that you used to intially investigate the issue (you can place them in a sub-directory under \\clrmain\public\PerfInvestigations  (e.g. 17-09-13.LinuxMsBuild) and indicate that in this issue, so that @kouvel can use them to improve CoreCLR.   

@kouvel - We should start by simply understanding why Windows and Linux are different here.   However I would like to expand the work into looking for the 'right' amount of spinning.    I have done a little investigation here that we can talk about if you wish.    Basically, my argument is that ideally we should be trying hard NOT to spin ourselves (and let the underlying critical section/event decide that).   We will still end up doing spinning of our own because we try to NOT create the Event (and we don't need to unless we have to wait) but after a lock has blocked at least once we should have an Event and we should defer to that code.   If we we find that we can do better with spinning of our own, we should incorporate history of what worked last time to optimized it.   Note we are in a nicer place than the reader-writer spin lock because

1. We don't use Sleep but a real events, so we only block for the time needed, (not the 16 msec minimum Sleep() imposes)
2. We have access to Stopwatch/QPC, so we can KNOW how long we waited with high precision and thus decide if spinning is worthwhile next time.  

Because choosing not to spin is not a strong commitment (Because if we immediately unblock we only wasted a few uSec can detect that with Stopwatch/QPC and thus decide to spin next time and 'correct' the issue), we can be more aggressive about doing it, which means that frankly we should not be spinning for much more than the time it takes to block and unblock, which will keep spin overhead low.

@brianrob @jkotas @stephentoub @geoffkizer

**Comment by redknightlois** [comment]
@vancem With the exception of the Linux part, it sounds very much like the runtime behavior observed at https://github.com/dotnet/coreclr/issues/13388 . The behavior with @kouvel improvements to the spin-lock (including the normalization) is way better; probably it is worth trying MSBuild under the spin fix first.

**Comment by rartemev** [comment]
@vancem @kouvel I added document with stack trace analysis under \\clrmain\public\PerfInvestigations\17-09-13.LinuxMsBuild

**Comment by kouvel** [comment]
I have filed the following issues that I believe need to be fixed in order:
- https://github.com/dotnet/coreclr/issues/13978
- https://github.com/dotnet/coreclr/issues/13980
- https://github.com/dotnet/coreclr/issues/13981

**Comment by kouvel** [comment]
@redknightlois, Monitor has not yet been switched to YieldProcessorNormalized, that is now covered by issue https://github.com/dotnet/coreclr/issues/13980

**Comment by kouvel** [comment]
This issue is mostly resolved, remaining work items are covered by other issues above
