### ISSUE TITLE
[Arm64/Windows] Dependency verification errors detected for 2.0.0-prerelease-02012-02

### ISSUE THREAD

**Issue by pgodeq** [dotnet/coreclr#13947]
While cross-compiling coreclr tests for ARM64 Windows Checked, I get dependency verification errors. 
I use the command: build-test.cmd arm64 checked toolset_dir c:\DATA\VS2015.WDK.14965
I do not get any error while building coreclr.

I tried the following link [https://github.com/dotnet/buildtools/blob/master/Documentation/project-nuget-dependencies.md](url) where they suggest to update corefx. I did that but end up with same errors while building coreclr tests.

The error log is given below:
Tools are already initialized.
Running: c:\DATA\clr\ci\2017-13-09\coreclr\Tools\dotnetcli\dotnet.exe c:\DATA\clr\ci\2017-13-09\coreclr\Tools\run.exe c:\DATA\clr\ci\2017-13-09\coreclr\config.json build -Project=c:\DATA\clr\ci\2017-13-09\coreclr\tests\build.proj -MsBuildLog=/flp:Verbosity=normal;LogFile="c:\DATA\clr\ci\2017-13-09\coreclr\bin\Logs\Tests_Managed_Windows_NT__arm64__Checked.log" -MsBuildWrn=/flp1:WarningsOnly;LogFile="c:\DATA\clr\ci\2017-13-09\coreclr\bin\Logs\Tests_Managed_Windows_NT__arm64__Checked.wrn" -MsBuildErr=/flp2:ErrorsOnly;LogFile="c:\DATA\clr\ci\2017-13-09\coreclr\bin\Logs\Tests_Managed_Windows_NT__arm64__Checked.err" -BuildOS=Windows_NT -BuildType=Checked -BuildArch=arm64
Running: c:\DATA\clr\ci\2017-13-09\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /l:BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  c:\DATA\clr\ci\2017-13-09\coreclr\tests\build.proj /p:__BuildType=Checked /p:__BuildArch=arm64 /p:__BuildOS=Windows_NT /p:RestoreDefaultOptimizationDataPackage=false /p:UsePartialNGENOptimization=false /p:PortableBuild=true  /flp:Verbosity=normal;LogFile=c:\DATA\clr\ci\2017-13-09\coreclr\bin\Logs\Tests_Managed_Windows_NT__arm64__Checked.log  /flp1:WarningsOnly;LogFile=c:\DATA\clr\ci\2017-13-09\coreclr\bin\Logs\Tests_Managed_Windows_NT__arm64__Checked.wrn  /flp2:ErrorsOnly;LogFile=c:\DATA\clr\ci\2017-13-09\coreclr\bin\Logs\Tests_Managed_Windows_NT__arm64__Checked.err
  [22:22:05.82] Verifying all auto-upgradeable dependencies...
c:\DATA\clr\ci\2017-13-09\coreclr\Tools\VersionTools.targets(61,5): error : Dependency verification errors detected. To automatically fix based on dependency rules, run the msbuild target 'UpdateDependencies' [c:\DATA\clr\ci\2017-13-09\coreclr\tests\build.proj]
c:\DATA\clr\ci\2017-13-09\coreclr\Tools\VersionTools.targets(61,5): error : Dependencies invalid: In 'c:\DATA\clr\ci\2017-13-09\coreclr\BuildToolsVersion.txt', '2.0.0-prerelease-02012-02 [c:\DATA\clr\ci\2017-13-09\coreclr\tests\build.proj]
c:\DATA\clr\ci\2017-13-09\coreclr\Tools\VersionTools.targets(61,5): error : ' must be '2.0.0-prerelease-02012-02'. [c:\DATA\clr\ci\2017-13-09\coreclr\tests\build.proj]

c:\DATA\clr\ci\2017-13-09\coreclr\Tools\VersionTools.targets(61,5): error : Dependency verification errors detected. To automatically
fix based on dependency rules, run the msbuild target 'UpdateDependencies' [c:\DATA\clr\ci\2017-13-09\coreclr\tests\build.proj]
c:\DATA\clr\ci\2017-13-09\coreclr\Tools\VersionTools.targets(61,5): error : Dependencies invalid: In 'c:\DATA\clr\ci\2017-13-09\coreclr\BuildToolsVersion.txt', '2.0.0-prerelease-02012-02 [c:\DATA\clr\ci\2017-13-09\coreclr\tests\build.proj]
c:\DATA\clr\ci\2017-13-09\coreclr\Tools\VersionTools.targets(61,5): error : ' must be '2.0.0-prerelease-02012-02'. [c:\DATA\clr\ci\2017-13-09\coreclr\tests\build.proj]
Command execution failed with exit code 1.

**Comment by pgodeq** [comment]
@jashook Please, take a look.

**Comment by jashook** [comment]
I would recommend running clean.cmd to clean the enlistment. Then build again:

```
build.cmd arm64 checked toolset_dir c:\DATA\VS2015.WDK.14965
```

Please note that you can get the tests here to unblock yourself: https://clrjit.blob.core.windows.net/arm64ci/win2012-9bb540/arm64/checked/tests.zip

**Comment by pgodeq** [comment]
Thanks for the suggestion and sharing the tests to unblock. 

I cleaned with clean.cmd and used the build command, but unfortunately I get the same errors as above. 
I have even deleted the .dnx, .dotnet and .nuget folders in c:\users\<myusername>\  so that they are freshly installed. This is specific to a machine as it happens while build for x64 as well.  
Can you please suggest how I can solve this ?

With these tests.zip, I get Pass: 11146 Fail: 45  Not run: 0.
Failures are for invalid directories for tests with name '*Parse*.cmd' (for example CoreMangLib\cti\system\boolean\BooleanTryParse\BooleanTryParse.cmd and CoreMangLib\cti\system\byte\ByteParse1\ByteParse1.cmd)
Should all of them pass ?

**Comment by pgodeq** [comment]
Works for me now with the current sources. Not sure what fixed this.
