### ISSUE TITLE
can't convert to object  " as "

### ISSUE THREAD

**Issue by cscer** [dotnet/coreclr#13969]
![image](https://user-images.githubusercontent.com/6744243/30411134-c28103ae-9941-11e7-8964-92867cfadf3d.png)

Traget to NetFramework4.6  it's works

but Target to netcoreapp2.0, 
User u=userEntity as User;  u is null;
watch the variable u in vs ,  it throw a FileNotFoundException,
but the file location from exception message is exist. and The assembly file is which the "User" type  definition.

why?

**Comment by AndyAyersMS** [comment]
@cscer we will need more information from you to make progress on this. Do you have a repro case you can share?

**Comment by cscer** [comment]
@AndyAyersMS 

sorry for the late reply.

The complete project can reproduce the issue, but the complete project is very large.

I tried to write a project to reproduce the issue, but did not succeed.

I think there are still a number of bugs in netcore or there are differences with the full framework, and vs2017 is not stable enough.

I've stopped migrating this project to Netstandard and reused net461.

I used the main APIs for this problem: Dispatchproxy, AppDomain CurrentDomain. assemblyresolve

Enclose some code that may help you locate the problem.
[codes.zip](https://github.com/dotnet/coreclr/files/1445368/codes.zip)

**Comment by jeffschwMSFT** [comment]
Thanks for sharing the code sample, but it does not contain sufficient detail for us to clearly understand the underlying issue.  If you are still seeing this issue please let us know.  It seems from your Nov comment that your project has shifted gears and this is not likely blocking any more.
