### ISSUE TITLE
Remove asm versions of Monitor helpers and use portable C++ versions instead

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#13979]
Ideally should be done before or as part of https://github.com/dotnet/coreclr/issues/13980

**Comment by benaadams** [comment]
Is an interesting difference; Windows has custom asm, and linux goes straight to C++?

**Comment by kouvel** [comment]
Yep, I don't expect there will be much change in perf

**Comment by benaadams** [comment]
Might make the Windows version worse; and the Linux version is already worse 😉

**Comment by kouvel** [comment]
That would be some good data to act on :)

**Comment by kouvel** [comment]
In the referenced PR that removes the asm helpers, it looks like the Windows version is worse than the asm mainly because of some register allocation issues, but the difference in perf doesn't seem to be significant. I didn't see much difference between Windows/Linux in the perf of the hottest fast paths (unlocked cases). Another difference is GetThread() is slower on Linux, not much can be done about that at the moment.
