### ISSUE TITLE
unable to install in kali linux 2017.1

### ISSUE THREAD

**Issue by AhmedHussainy** [dotnet/coreclr#13975]
i am trying to install dot net core 2.0 in kali linux x64 2017.1 ....
but not working i am following the official guide [here](https://www.microsoft.com/net/core#linuxdebian)
but i got error when i apply this command :
`sudo apt-get install dotnet-sdk-2.0.0`
the error is :
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  aspnetcore-store-2.0.0 dotnet-host dotnet-hostfxr-2.0.0 dotnet-runtime-2.0.0
  libicu52 liblttng-ust-ctl2 liblttng-ust0 libssl1.0.0 libunwind8 liburcu6
E: Could not get lock /var/cache/apt/archives/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/cache/apt/archives/

```

**Comment by janvorli** [comment]
@AhmedHussainy this usually means that you have some other installer running at the same time. Even just running a GUI package installer (not sure what it is on the Kali) without any ongoing installation prevents the command line apt-get from working.

**Comment by AhmedHussainy** [comment]
you are right after a full restart everything is working fine .... thank you very much
