### ISSUE TITLE
Stop copying pgort*.dll alongside an instrumented product build

### ISSUE THREAD

**Issue by dpodder** [dotnet/coreclr#13970]
Building the repo with PGO instrumentation enabled (`build.cmd release pgoinstrument`) produces an instrumented runtime and JIT, which introduce a new runtime dependency on pgort140.dll. This is normally available in a VC++ developer environment, and our training automation ensures that it is on PATH.

Due to a Setup/CLI bug, however (dotnet/core-setup#3213), we can't actually run a CLI with an instrumented runtime unless pgort140.dll is copied into the same folder as coreclr.dll/clrjit.dll. Something about the way dotnet.exe loads the runtime prevents it from pulling the PGO dependency from PATH.

To work around this, we've long had a hack of copying pgort140.dll alongside an instrumented product build of the runtime. This used to be done in pgosupport.cmake, and as of #12581 it's being moved into build.cmd. Once dotnet/core-setup#3213 is fixed, the hack should be removed from build.cmd.

**Comment by RussKeldorph** [comment]
@adiaaida per #14886 should this issue be closed?

**Comment by adiaaida** [comment]
Yes. This looks like the only way we are going to be able to do this for now, so it will stay, and this can be closed.
