### ISSUE TITLE
Consider applying spinning changes to Monitor, to anything else that uses g_SpinConstants

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#13985]
Apply PRs that fix the following Monitor spinning issues:
- Depends on https://github.com/dotnet/coreclr/issues/13980
- Evaluate applying https://github.com/dotnet/coreclr/issues/13981 as well, if it's found to be useful, on a case-by-case basis

**Comment by kouvel** [comment]
Not likely to happen until a significant issue is shown to substantiate the work

**Comment by danmosemsft** [comment]
@kouvel is it not worth leaving some of these open for potential community interest? We have many such issues open that we do not plan to work on.

**Comment by kouvel** [comment]
It would take a considerable amount of time to validate, and with little gain. It's probably not worth taking on unless there is a significant issue. There are other types of work that would benefit more.
