### ISSUE TITLE
Expanding "Assembly" variable in Debugger prevents "FileNotFound" exception 

### ISSUE THREAD

**Issue by roozbehid-ic** [dotnet/coreclr#13996]
VS 2017 15.3.4
Project is .Net Core App 2.0 Console (Running/Debugging in Windows 10)

          string filename = @"d:\myfile.dll"
           Assembly  asm = Assembly.LoadFrom(filename);
           Type[] asmTypes = asm.GetTypes();

myfile.dll is a .Net 4.6.1 Class library with many other dependencies. I get FileNotFoundException on one of the dependencies. I have copied that file everywhere (for example c:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\) but that is not enough. I also used gflags and it seems .Net is not even looking for that assembly.

The strange thing is if I am debugging it and I expand "asm" variable after Assembly.LoadFrom, then I wont get the exception! I also tried debugging into framework and it seems in this line (AssemblyLoadContext.cs)

        Func<AssemblyLoadContext, AssemblyName, Assembly> assemblyResolveHandler = Resolving;

Resolving is null, which later this would cause the exception.

It also works fine if I switch to .Net Framework 4.6.1 for my console app.

**Comment by jkotas** [comment]
Have you tried to put the dependency next to the file that it is referencing (i.e. `d:\dependency.dll`); or subscribing to `AppDomain.AssemblyResolve`  and providing the path to your dependency via this event?

> It also works fine if I switch to .Net Framework 4.6.1 for my console app.

Where is the dependency loaded from in .Net Framework?

**Comment by roozbehid-ic** [comment]
Yes the dependency is next to that file.  .Net 4.6.1 loads it from the one next to the file. Like d:\dependency.dll.

----------------------- Different but similar issue :
I have already observed another -probable- bug that .net core does not load dependency dll even if it was in its path. 
Looking at it with "gflags +sls" I can see that file is loaded -finally- successfully, but .net complains about it not being found. Initially it was looking (for dependent dll) in c:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0 and some other system wide locations before looking for it in the same path, so I thought maybe it is time-outing or something. Because when I moved it into c:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0 it worked.

**Comment by roozbehid-ic** [comment]
I think I find out why debugger works. It throws exception but also asm.GetTypes() returns value (Is it how it supposed to work?) For example doing this you end up with asmTypes being populated.

            Type[] asmTypes;
            try
            {
                 asmTypes = asm.GetTypes();
            }
            catch
            {

            }

**Comment by jkotas** [comment]
Would it be possible to create a small repro for the problem that we can take a look at?

> For example doing this you end up with asmTypes being populated.

This does not sound right.
