### ISSUE TITLE
[RyuJIT/armel] Pri2 test regression (332 tests fail)

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#14008]
332 Tests fail with recent master branch.

Here are part of list that failed.
```
JIT.CodeGenBringUpTests.DblAdd.DblAdd
JIT.CodeGenBringUpTests.DblArea.DblArea
JIT.CodeGenBringUpTests.DblArray.DblArray
JIT.CodeGenBringUpTests.DblAvg2.DblAvg2
JIT.CodeGenBringUpTests.DblAvg6.DblAvg6
JIT.CodeGenBringUpTests.DblCall2.DblCall2
JIT.CodeGenBringUpTests.DblDist.DblDist
JIT.CodeGenBringUpTests.DblDiv.DblDiv
JIT.CodeGenBringUpTests.DblMul.DblMu
JIT.CodeGenBringUpTests.DblRem.DblRem
JIT.CodeGenBringUpTests.DblSub.DblSub
JIT.CodeGenBringUpTests.DblVar.DblVar
JIT.CodeGenBringUpTests.InstanceCalls.InstanceCalls
JIT.CodeGenBringUpTests.OpMembersOfStructLocal.OpMembersOfStructLocal
JIT.CodeGenBringUpTests.StaticCalls.StaticCalls
JIT.CodeGenBringUpTests.struct16args.struct16args
...
```

**Comment by wateret** [comment]
The regression has been introduced since #13715 landed.

**Comment by wateret** [comment]
cc: @dotnet/arm32-contrib

**Comment by wateret** [comment]
JITd Code in `Main()`, calling to `DblAdd()`

```
G_M4665_IG02:
            movs    r2, 0
            movw    r3, 0xd1ff
            movt    r3, 0xd1ff
            vmov.i2d d8, r2, r3
            vmov.d2i r0, r1, d8
            movs    r2, 0
            movw    r3, 0xd1ff
            movt    r3, 0xd1ff
            vmov.i2d d8, r2, r3
            vmov.d2i r3, r2, d8    !!! Should've been [vmov.d2i r2, r3, d8] !!!
            mov     r2, r3
            movw    lr, 0xd1ff
            movt    lr, 0xd1ff
            ldr     lr, [lr]
            blx     lr          // BringUpTest:DblAdd(double,double):double
            vmov.i2d d0, r0, r1
```

**Comment by wateret** [comment]
It looks like the problem is incorrect RefPosition's preferences.
The TC is `JIT.CodeGenBringUpTests.DblAdd.DblAdd` and the problematic method is `Main` when it calls to `DblAdd(double, double)` and there must be incorrect codegen with passing argument regester of double type.

Before

```
Interval 11: RefPositions {#19@14 #21@15} physReg:NA Preferences=[r2]
Interval 12: RefPositions {#20@14 #22@15} physReg:NA Preferences=[r3]
```

Now

```
Interval 11: RefPositions {#19@14 #21@15} physReg:NA Preferences=[r2-r3]
Interval 12: RefPositions {#20@14 #22@15} physReg:NA Preferences=[r2-r3]
```

This causes Interval 11 can assign either r2 or r3 and so is Interval 12. But by calling convention, Interval 11 and 12 must be r2 and r3, respectively.

**Comment by wateret** [comment]
@CarolEidt Do you have any idea on this? I think GT_PUTARG_REG and GT_COPY nodes relationship matters here. FYI I attach the full JitDump of Main function. 
[dbladd_main_now.txt](https://github.com/dotnet/coreclr/files/1320991/dbladd_main_now.txt)
[dbladd_main_before.txt](https://github.com/dotnet/coreclr/files/1320992/dbladd_main_before.txt)

**Comment by CarolEidt** [comment]
I will need to look at this in more detail, but I see that the `GT_COPY` nodes are still being used; I think that these should now be changed to `GT_BITCAST`. However, that is probably unrelated to this particular issue.

**Comment by CarolEidt** [comment]
I believe that the problem is here: https://github.com/dotnet/coreclr/blob/master/src/jit/lsra.cpp#L4158. Note that, in the code above, the `candidates` and `currCandidates` are being set and modified. That's what's used to set the registers on the `RefPosition`. The register sets on the `Interval` are just preferences, not requirements, so it is the setting on the `RefPosition` that really matters. So the code for   MultiRegOp and `GT_COPY` (which should really be `GT_BITCAST`) should look like the code above for PutArgSplit.

**Comment by wateret** [comment]
> So the code for MultiRegOp and GT_COPY (which should really be GT_BITCAST) should look like the code above for PutArgSplit.

@CarolEidt I just tried that, but it seems like the candidates are just ALL_INT. So all the GT_COPY is assigned to r0 and r1.

**Comment by wateret** [comment]
@CarolEidt So now I wonder if this code is still valid.

https://github.com/dotnet/coreclr/blob/43cf34fe74b435427ffb62f54fc730b4b46c4c22/src/jit/lsraarmarch.cpp#L312

Now that we call `TreeNodeInfoInit()` just before creating a RefPosition for each node, I think updating Op1's LsraInfo actually does nothing since RefPosition for that node has been already created.

**Comment by CarolEidt** [comment]
It is valid to update the srcCandidates because the src/use RefPositions haven't been constructed yet. However, those are considered hints. I think the problem may be that the register assignment on the putarg isn't being used to set dstCandidates.

**Comment by CarolEidt** [comment]
I think you need to change to use GT_BITCAST, which probably needs to use GenTreeCopyOrReload, and put the register assignment on it when it is created. Then it needs to have a TreeNodeInfoInit method that uses the register assignment to set the dstCandidates.
