### ISSUE TITLE
Catching a StackOverflowException

### ISSUE THREAD

**Issue by joshcomley** [dotnet/coreclr#14010]
If I have this simple app:

	using System;

	namespace PlayGround.Core.Console
	{
		public class Program
		{
			public static void Main(string[] args)
			{
				try
				{
					DoSomething();
				}
				catch(Exception e)
				{
					System.Console.WriteLine("Bugger");
				}

			}

			private static void DoSomething()
			{
				DoSomething();
			}
		}
	}

The exception handler itself is never called, instead the app crashes and I get this error:

![7mwfr](https://user-images.githubusercontent.com/820534/30482091-9c964da6-9a19-11e7-8bea-f16016a0dac8.png)

The same happens if I use the `StackOverflowException` in the `catch` instead of just `Exception`.

Is there anyway to catch a StackOverflow exception and not have the app crash?

**Comment by sharwell** [comment]
To date I have not found a way to handle a `StackOverflowException` within a .NET process, outside of the case where you use the [hosting API](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/hosting/) to launch the CLR in a non-standard mode which allows these exceptions to be caught. I've tried everything I could think of, including routing calls through an intermediate unmanaged C++ library using unmanaged exception handlers to try and prevent the CLR from seeing the exception. I would be delighted if someone found a way to "intercept" this exception on a thread.

**Comment by jkotas** [comment]
Right, StackOverflowException is non cachable.

Related to #652

**Comment by masums** [comment]
But there should have any way to prevent app crash for StackOverflowException because for that full web app crashes. Which is an unexpected behavior.
