### ISSUE TITLE
.assembly IL directive: definition of "legacy library" and "auto"

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/coreclr#1401]
I'm looking through the IL testcases and stumbled over the following keywords that aren't mentioned in ECMA335:

[calli2.il](https://github.com/dotnet/coreclr/blob/7e1bc37cfe2bc5372e3b55d7e4b0504ae9493c06/tests/src/JIT/Directed/coverage/importer/calli2.il#L4-L5)

```
.assembly extern legacy library mscorlib {} 
.assembly legacy library calli2 {} 
```

[typeEqualOp.il](https://github.com/dotnet/coreclr/blob/2d024d472a600156af270765864a95b822bcf272/tests/src/JIT/Methodical/casts/ilseq/typeEqualOp.il#L5)

```
.assembly extern mscorlib{auto}
```

Can anyone shed some light on what they do?

**Comment by akoeplinger** [comment]
Found a page in the ".NET IL Assembler" book by Serge Lidin about `auto` in `.assembly`:

https://books.google.com/books?id=Xv_0AwAAQBAJ&pg=PA91
> When the keyword auto is specified, the ILAsm compiler queries the GAC and tries to find an assembly with the specified name. If it succeeds, it reads the assembly attributed (version, public key, culture) and puts these attributes into the generated AssemblyRef metadata record.

The same book also says that `legacy library` is "for backward compatibility only", does this mean it can be ignored?

**Comment by BruceForstall** [comment]
Stale; closing.
