### ISSUE TITLE
TimeZoneInfo Now functionality

### ISSUE THREAD

**Issue by TimCurwick** [dotnet/coreclr#14019]
TimeZoneInfo objects should have functionality to provide the current time in the time zone defined in the object. This would be similar to the DateTime and DateTimeOffset Now and UTCNow static properties, though of course not static. For consistency, this could be a property named Now.
Something like:
`public readonly DateTime Now {
    get {
        return ConvertTime( DateTime.UtcNow, this);
        }
    }`

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #26400](https://github.com/dotnet/corefx/issues/26400) via [**ZenHub**](https://www.zenhub.com/)
