### ISSUE TITLE
Implicit operator throws when checking ArraySegment != null or ArraySegment == null

### ISSUE THREAD

**Issue by MindyStivers** [dotnet/coreclr#14012]
### Symptom
Using != or == operator to compare an ArraySegment to null throws an ArgumentNullException.  For example: 
`if (new ArraySegment<byte>() == null)`

### Cause
The != and == operator trigger implicit conversion from an array to ArraySegment on `null`. The resulting call to the ArraySegment constructor with a null array parameter throws an ArgumentNullException:

`public static implicit operator ArraySegment<T>(T[] array) => new ArraySegment<T>(array);`
results in:
`new ArraySegment<T>(null);`
which throws ArgumentNullException.

dotnet/corefx#10528
#9926

**Comment by benaadams** [comment]
ArraySegment is a struct so can never actually be null; do you want to check if its array is null?

`if (new ArraySegment<byte>().Array == null)`

**Comment by MindyStivers** [comment]
D'oh! This just started throwing out of the depths of an older test when we moved to .net core 2.0.  Fair 'nuf that the answer is we have bad test code that was previously sneaking through.

I know the implicit operator docs say it should not throw so I wanted to make sure to follow up.

**Comment by benaadams** [comment]
I do wonder what it will do for struct tests in generics e.g.

`if (default(T) == null)`
`if (default(T) != null)`

Where T is ArraySegment

**Comment by MindyStivers** [comment]
The generic tests you suggested work fine when T is an ArraySegment.  Perhaps worth noting that (although it's rather pointless) we can compare other value types == or != null without an exception.

**Comment by serkantkaraca** [comment]
I think we are talking here about breaking the contract on null check on struct types. It doesn't really matter whether it makes sense or not to null check. Null check on struct compiles but throws an undescriptive NullRef which breaks the former behavior. We need to fix this.

**Comment by kasper3** [comment]
Thanks @stephentoub and prioritizing it. Redirected from https://github.com/dotnet/corefx/issues/26987.

**Comment by jkotas** [comment]
We should add a test to corefx (if there is not one already).

**Comment by stephentoub** [comment]
> We should add a test to corefx (if there is not one already).

I'll do so.
