### ISSUE TITLE
Throwing IndexOutOfRangeException at Microsoft.Cci.MetadataWriter.GetRowCounts() in openSuse 13.2

### ISSUE THREAD

**Issue by gideonkorir** [dotnet/coreclr#1402]
I'm trying to get the Linux sample working on openSuse but I can not get the sample console app to run.
Steps to reproduce:
`
sudo zypper install libunwind  

sudo zypper install  libopenssl-devel 
`
install mono 4.0.2 from [mono-complete](http://software.opensuse.org/package/mono-complete)  "show other versions" > "Mono:Factory" 1 click install. You are no longer required to sync certificates as explained [here](http://www.mono-project.com/docs/getting-started/install/linux/).

Install dnvm and dnx as explained on [get-dotnetcore-dnx-linux](https://github.com/dotnet/coreclr/blob/master/Documentation/install/get-dotnetcore-dnx-linux.md).

Running dnvm list returns:

![dnvm-list](https://cloud.githubusercontent.com/assets/1640535/9294882/10aa7852-4463-11e5-8301-83053dc92b8c.PNG)

running the sample on mono runs correctly:

![dnx-mono](https://cloud.githubusercontent.com/assets/1640535/9294899/d0a70972-4463-11e5-91e7-fccde2a7f71e.PNG)

running the sample using coreclr:

![dnx-core64](https://cloud.githubusercontent.com/assets/1640535/9294908/29ceff50-4464-11e5-99b7-9b5a1bc4bde9.PNG)

May be similar to this [issue](https://github.com/dotnet/roslyn/issues/4512)

**Comment by akoeplinger** [comment]
Yeah, this looks very much like https://github.com/dotnet/roslyn/issues/4512. Since the verdict on that issue was that it's a mismatch between the roslyn and coreclr dlls for dnx I hope it'll resolve itself automatically :smile:

**Comment by gideonkorir** [comment]
:D ok. We can close the issue and I'll just have to wait since I have no clue on how to fix it :). Linking this issue with [this](https://github.com/dotnet/coreclr/issues/803) to help out anyone wanting to get coreclr on openSuse. Thanks.

**Comment by tzwlai** [comment]
Closing this issue per the previous comment.  Please feel free to reopen if needed.
