### ISSUE TITLE
Allow opening Unix file descriptors

### ISSUE THREAD

**Issue by logankp** [dotnet/coreclr#14038]
I'd like the ability to open raw file descriptors from .Net for reading/writing. This is useful in the case of [systemd socket activation](http://0pointer.de/blog/projects/socket-activation.html). If opening file descriptors isn't possible, maybe allow opening` /proc/self/fd/n`.  Currently, trying to open a socket from `/proc/self/fd` results in an IOException.

**Comment by stephentoub** [comment]
You can get a stream for an arbitrary file descriptor using SafeFileHandle and FileStream, e.g.
```C#
public static Stream CreateStreamForFileDescriptor(int fd) =>
    new FileStream(
        new SafeFileHandle((IntPtr)fd, ownsHandle: false),
        FileAccess.ReadWrite);
```

**Comment by logankp** [comment]
Alright now I feel stupid. I tried that last night but must have done something wrong because testing it again worked just fine.
