### ISSUE TITLE
[Feature Request] Consider supporting interop to Rust

### ISSUE THREAD

**Issue by realvictorprm** [dotnet/coreclr#14042]
Hello fellow developers out there,
sorry for disturbing with such a crazy feature request.

The CLR technical seen has limitations regarding performance for certain circumstances. To solve such people often start using native languages like C and C++. Still though not all task must be done in such a language and so it's still common to use some .NET through the nice "interop". 

However meanwhile other languages showed up for the native area which neatly solve the traps of C and or C++. It's very likely that more and more developers are going to consider and accept those languages for native application development. One of those great languages is in my opinion **Rust**. 

Therefore I'm asking officially whether it's technical possible to extend the native interop for interacting with new languages like Rust seamless. 

I can imagine that this could be a enormous task to do, therefore I suggest first to discuss it and post some pointers about how any kind of _extension_ could be done. This would encourage that experiments could be done (e.g. from me maybe).

**Comment by svick** [comment]
[It seems that if you declare a Rust function with `#[no_mangle] extern "C"`, you can then call it from C# using normal PInvoke.](https://stackoverflow.com/a/35639867/41071)

So, what exactly are you asking? That the CLR should understand Rust name mangling, so that you can call any Rust function from C#? Or something else?

**Comment by realvictorprm** [comment]
@svick yes this would be nice

According your link, I think this has some drawbacks.

**Comment by svick** [comment]
It seems Rust does not have a defined ABI: https://github.com/rust-lang/rfcs/issues/600. So I don't think that would make sense.

**Comment by realvictorprm** [comment]
ok I agree @svick Let's close this as long as there isn't one

**Comment by tannergooding** [comment]
.NET doesn't even support C++ name mangling today (or at least I don't think it does).

I think effort would be better spent on a simple tool (or analyzer) that converts unmanagled names to managled names for Rust (pretty sure these already exist for MSVC, GCC, and Clang).

Users can then just run said tool/analyzer before compilation and have things work.

**Comment by realvictorprm** [comment]
@tannergooding I'm currently experimenting with interop and very interested in combining languages :)
