### ISSUE TITLE
Enable logging of Environment.FailFast into event log

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#14045]
Currently logging the Environment.FailFast and the corresponding stack trace into the event log in .NET core is disabled. We should enable it. See #14037 for some details on what needs to be done.

**Comment by jkotas** [comment]
Why not use #14037 to track this fix?

**Comment by janvorli** [comment]
@jkotas hmm, I don't know now why I have created this separate issue. Makes sense to reuse the original reported one.
