### ISSUE TITLE
System.Console.writeline causes DllNotFoundException: Unable to load System.Native

### ISSUE THREAD

**Issue by alexandrio** [dotnet/coreclr#1404]
Followed instructions to build coreclr and corefx  from building guide, when trying to execute the recomended HelloWorld.cs program causes next exception message:

alejandro@ubuntudev:~/coreclr-demo/runtime$ ./corerun HelloWorld.exe linux

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'System.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Sys.FStat(Int32 fileDescriptor, FileStatus& output)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.ConsolePal.UnixConsoleStream..ctor(String devPath, FileAccess access)
   at System.ConsolePal.OpenStandardOutput()
   at System.Console.OpenStandardOutput()
   at System.Console.<>c.<get_Out>b__11_0()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at Program.DrawLinux()
   at Program.Main(String[] args)

built on ubuntu 14.04.03

corefx and coreclr mscorlib.dll windows version built on windows 8.1 with vs2015 community

mono --version
Mono JIT compiler version 4.0.3 (Stable 4.0.3.20/d6946b4 Tue Aug  4 09:43:57 UTC 2015)

**Comment by stephentoub** [comment]
Have you built the native components in the corefx repo and copied them to your execution directory?

**Comment by alexandrio** [comment]
yes, i suppose is this step
alejandro@ubuntudev:~/git/corefx$ src/Native/build.sh
alejandro@ubuntudev:~/git/corefx$ cp bin/Linux.x64.Debug/Native/*.so ~/coreclr-demo/runtime

**Comment by stephentoub** [comment]
cc: @nguerrera

**Comment by nguerrera** [comment]
That should have worked if you those steps executed successfully.  Did the src/Native/build.sh complete successfully? If not, can you provide the output?

**Comment by alexandrio** [comment]
well, i deleted repositories and downloaded again, repeated complete procedure for instalation and now was succesfull, last time, there was nothing in the output directory and now there is system.native.so, after this all is working 

    alejandro@ubuntudev:~/git/corefx$ src/Native/build.sh
    Commencing CoreFX Native build
    Setting up directories for build
    Checking pre-requisites...
    Commencing build of corefx native components for Linux.x64.Debug
    Invoking cmake with arguments: "/home/alejandro/git/corefx/src/Native" DEBUG
    CMake Warning at System.Security.Cryptography.Native/CMakeLists.txt:13 (message):
      Cannot find libcrypto, skipping build for
      System.Security.Cryptography.Native.  .NET cryptography is not expected to
      function.  Try installing libssl-dev (or the appropriate package for your
      platform)


    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/alejandro/git/corefx/bin/obj/Linux.x64.Debug/Native
    Executing make install -j 5 
    [100%] Built target System.Native
    Install the project...
    -- Install configuration: "DEBUG"
    -- Up-to-date: /home/alejandro/git/corefx/bin/Linux.x64.Debug/Native/./System.Native.so
    CoreFX native components successfully built.
    Product binaries are available at /home/alejandro/git/corefx/bin/Linux.x64.Debug/Native

**Comment by stephentoub** [comment]
Glad you got it working.
