### ISSUE TITLE
string.IndexOf not returning proper value when searching for a null character

### ISSUE THREAD

**Issue by michaellandi** [dotnet/coreclr#14066]
It appears that the behavior is different between the 2.0.0 linux runtime and the 2.0.0 windows runtime.

`"hello".IndexOf("\0")`

Windows: -1
Linux: 0

> Product Information:
> Version: 2.0.0
> Commit SHA-1 hash: cdcd1928c9

**Comment by karelz** [comment]
That is unfortunate :( - do you know what is the behavior on "full" .NET Framework?
I assume you verified it differs only for null character and not for any character which is not part of the string, right?

@joperezr can you please take a look? It is something we might want to fix in servicing ...
cc @danmosemsft

**Comment by hughbe** [comment]
Could https://github.com/dotnet/coreclr/issues/2051 be related?

**Comment by danmosemsft** [comment]
@karelz .NET Framework returns -1. Note this overload is culture sensitive. The docs say, 
```
Character sets include ignorable characters, which are characters that are not considered when performing a linguistic or culture-sensitive comparison. In a culture-sensitive search (that is, if comparisonType is not StringComparison.Ordinal or StringComparison.OrdinalIgnoreCase), if value contains an ignorable character, the result is equivalent to searching with that character removed. If value consists only of one or more ignorable characters, theIndexOf(String, StringComparison)method always returns 0 (zero) to indicate that the match is found at the beginning of the current instance.
```

This is consistent with `\0` being ignorable on Linux (at least in en-US) but not on Windows, as @tarekgh stated in #2051.

**Comment by tarekgh** [comment]
Right, on Linux the null character has no sorting weight which on Windows it does. The sorting behavior depends on the OS. if you want to force IndexOf to not ignore the null character, you'll need to use the Ordinal operation and not the linguistic operation.
