### ISSUE TITLE
GC and locality of reference

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/coreclr#14060]
See https://github.com/dotnet/csharplang/issues/922#issuecomment-330535022 where proposal was original posted.

Arrays are allocated in memory contiguously. so unlike linked list, there is no pointer for each item of array. there is only one pointer for array, and rest of items are randomly accessible using indexer.

The reason why arrays are much faster than linked lists is because they are basically contiguous block of memory. locality is high and there will be less cache misses,

[From this article](https://msdn.microsoft.com/en-us/library/eye126ky.aspx#Anchor_1) 

>Missed cache hits, on both the internal and external cache, as well as page faults (going to secondary storage for program instructions and data) slow the performance of a program.
A CPU cache hit can cost your program 10–20 clock cycles. An external cache hit can cost 20–40 clock cycles. A page fault can cost one million clock cycles (assuming a processor that handles 500 million instructions/second and a time of 2 millisecond for a page fault). Therefore, it is in the best interest of program execution to write code that will reduce the number of missed cache hits and page faults.
One reason for slow programs is that they take more page faults or miss the cache more often than necessary. To avoid this, it's important to use data structures with good locality of reference, which means keeping related things together. Sometimes a data structure that looks great turns out to be horrible because of poor locality of reference, and sometimes the reverse is true.

I was thinking that why not introduce a mechanism to increase locality in memory for some objects simply by noting it. with help of GC of course which can move objects around. 

sometimes developer knows better than GC, so we could ask him, please keep these together, because we are likely to use these objects together. but again GC can do anything reasonable himself, it will take this as hint.

```
public class Bucket
{
    int hashcode;
    int T value;

    [KeepLocalityHigh] // as suggested by @mikedn, (something like this)
    Bucket next;
}
```

In this simple example, you can see that Bucket in dynamically allocated. by noting attribute on that field, we tell runtime that locality is important here. so if possible keep references related here together. this can reduce number of cache misses (<s>and page faults</s>❓), and you are still using power of linked list structures. 
I believe this could significantly increase performance where number of data is large and locality is high.

Is this even possible to be implemented without causing havoc in GC or CLR mechanism? I know its not that simple though, I'm just throwing ideas here.

**Comment by sharwell** [comment]
@benaadams @tannergooding I'd be interested in your take on this - in particular for additional cases where locality of reference types would be advantageous.

**Comment by jkotas** [comment]
The GC tend to keep objects allocated sequentially next to each other. If you have a data structure that suffers from a poor locality over time, you can recreate copy of it to regain its locality. It is not that different what GC would have to do to the same - it would also have to copy everything around, except that the GC would need to pause execution of all managed code to pull this off.

Teaching GC to reorganize the GC heap according to these annotations would significantly increase pause times (stop the world). The pause times are #1 GC problem these days. We certainly do not want to increase them.

**Comment by swgillespie** [comment]
This would also be made difficult by the fact that the GC aggressively combines adjacent objects into "plugs" to reduce the number of distinct objects that need to be relocated (by merging them together into larger collections of objects). Breaking up plugs to respect locality attributes would be pretty devastating to the performance of the plan phase, not to mention the perf cost of trying to record locality information when marking the heap.

cc @Maoni0 (though she's OOF right now)

**Comment by benaadams** [comment]
For allocating together and using together, locality is generally pretty good. 

If you scatter allocate over time time then locality isn't so good. However getting the GC to defrag and work out priority order of something like a linked list would be pretty hard as it wouldn't understand what the correct order would mean in terms of the apps' specific algorithm - as well as the considerable added overhead to the GC.

You can force allocate a group together by allocating an array of structs; then it will always be together (this is what Dictionary does).

You can then defrag/order it correctly by switching items in the array and updating the referring indexes.

This isn't necessarily easy or straightforward depending on your data structure. There are entire different classes of datastructures/algorithms dedicated to trying to maintain [cache obliviousness](https://en.wikipedia.org/wiki/Cache-oblivious_algorithm), cache locality, iterator ordering etc with various trade offs.

I think it would be tricky for the GC to try to do this without an invasive knowledge of what your app is doing; some kind of Profile Guided Allocation...

**Comment by jkotas** [comment]
Given the above discussion this is very unlikely to materialize in any form in .NET Core.

**Comment by albertnetymk** [comment]
In this paper, https://dl.acm.org/citation.cfm?id=1134021, it's mentioned that this feature is implemented in CLR 2. I wonder if it's available in this open-source version of CLR.

**Comment by jkotas** [comment]
This was a research experiment implemented on top CLR 2 codebase. The code was never part of the master CLR codebase.

**Comment by albertnetymk** [comment]
The quoted sentence, especially the word "ships", got me to think otherwise. Thank you for the clarification.
