### ISSUE TITLE
VS 2017 Fails to Open AllTestProjects.sln

### ISSUE THREAD

**Issue by kingces95** [dotnet/coreclr#14074]
Per the [Building and running tests on Windows](https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-test-instructions.md), I expected to be able to open `AllTestProjects.sln` in VS 2017. Actually, the load started, and may have "finished" but also failed with`dimensionValuesMap must contain at least one element` (and also `Unknown Hard Error` from `csrss.exe` according to `procexp`. Not sure how/if that's related).

Here is [my VS 2017 version info](https://gist.github.com/kingces95/d8a063b484f2b606e0558dcb01b6661c).

Here is [a mini dump](https://microsoft-my.sharepoint.com/:u:/p/chrkin/EaDB6C4uHxhPhetQZ2ye1igB-L4eV_QhAlDZT684cnc74Q) (MS Only).

![image](https://user-images.githubusercontent.com/4120386/30619445-7624a3fa-9d6d-11e7-995e-fd0c1e41b3f2.png)

Here is [the log](https://gist.github.com/kingces95/f47dac650629ed420e8cb74d8f317f85) pointed to in the error message.

The threads after attaching a debugger:

![image](https://user-images.githubusercontent.com/4120386/30622023-d4d6b046-9d7c-11e7-869e-c91370f70cb6.png)

And when I clicked `OK` on the hard error, the debuggee process got taken down and [this error appeared in the attached debugger log](https://gist.github.com/kingces95/8167e4f78db3a2153ea409b6a51b1080).

**Comment by kingces95** [comment]
I'd guess active developers use the command line so it may be easier to simply not support the solution. In which case, we just pull that bit from the documentation.

**Comment by mikedn** [comment]
A solution containing 1646 projects? You're brave if you attempted to load that. I never dared.

**Comment by kingces95** [comment]
Yep, I was a bit surprised to see that suggested in the documentation. So I thought I'd give it a try. 

I understand that there's probably no market value to enabling that scenario. That said, seems a shame that the premier vehicle for developing CorClr apps and libraries cannot dogfood itself.

It's probably just that the tests were developed before VS was baked and there's no point in aggregating them into a few larger projects... 

Either way, we should pull it from the docs.

**Comment by mikedn** [comment]
And it's likely that the actual number of test projects is much higher, there are 7527 .csproj files in the tests\src directory. That solution file is never updated when new tests are added.

> It's probably just that the tests were developed before VS was baked and there's no point in aggregating them into a few larger projects now that they were developed for the command line...

Not only that there are lots of tests but the .csproj files aren't necessarily "standard" VS project files. They may contain customizations that make VS barf.

Note that once you build the tests you may be able to load the xunit wrappers projects and run the tests in VS. I've never tried that myself but I heard that it is possible in #4840.

> Either way, we should pull it from the docs.

And delete the solution file, it will never work. Even if VS would load it correctly and in a reasonable amount of time nobody will bother updating it when new tests are added.
