### ISSUE TITLE
Cache miss problem after GC

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#14076]
After GC, data in cpu cache might become invalid, so there would be a lot of cache misses, which would harm performance. Is there any way to solve this problem? Could GC "update" or "refresh" the cache data instead of making cache invalid? Is it possible to keep the cache data still valid after GC?

**Comment by jkotas** [comment]
> Could GC "update" or "refresh" the cache data instead of making cache invalid?

This would hurt performance even more.
