### ISSUE TITLE
GenericPInvokeCalliHelper on Unix

### ISSUE THREAD

**Issue by mellinoe** [dotnet/coreclr#1408]
(Not sure if there is an issue tracking this in general, wasn't able to quickly find one).

Currently, these helpers are stubbed out in the unixstubs file (I'm running on x64 but it's probably true in the other archs as well):

````C++
    void GenericPInvokeCalliHelper()
    {
        PORTABILITY_ASSERT("Implement for PAL");
    }
````

I was looking into running some small programs using OpenTK (www.github.com/opentk/opentk) on CoreCLR, and hit this assertion running on Linux. OpenTK uses calli for a lot of their OpenGL interop code so I am assuming that is what is triggering this assertion. I haven't debugged the exact line that my program reaches, but I know it gets through some portions of the OpenTK initialization which involve some other simple interop calls.

Do we have anything tracking this work or know how difficult / complicated it is to get this up and running?

**Comment by jkotas** [comment]
This should be pretty straightforward to implement based on the Windows implementation.

cc @kouvel @sergiy-k

**Comment by kouvel** [comment]
I'll take a look at this.

**Comment by mellinoe** [comment]
Thanks, @kouvel . If you get a change set together, I can help test it with the program I mentioned above, just to give some extra validation.

**Comment by kangaroo** [comment]
@mellinoe if you have a test case, please post it.  I did all this functionality, it was rather simple, but before posting a PR I'd like to confirm that it fixes your use case.

**Comment by mellinoe** [comment]
I made a smaller repro, basically the code here:

https://github.com/mellinoe/BoxGame/blob/master/src/OpenTK.Demo/Program.cs

I uploaded the demo app here, which has the whole runtime/framework as well:
http://1drv.ms/1fAVl2W

Just the demo assemblies (if you're testing with your framework/runtime):
http://1drv.ms/1fAVbIS

**Comment by kangaroo** [comment]
@mellinoe Thanks, your sample now properly renders the inverted triangle (at least I think thats the expected result?) on my branch.

**Comment by mellinoe** [comment]
Awesome! Yes, that's the expected result, it's the simplest demo/sample project that OpenTK has in their repo :smile:

I'll check it out now.

**Comment by mellinoe** [comment]
I did test this quickly yesterday, and the demo program worked fine. Looks like the PR was merged in so I will close this. Thanks @kangaroo !
