### ISSUE TITLE
[Windows Arm64] CI Trigger words should match job name to eliminate confusion

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#14091]
The current trigger `@dotnet-bot test Windows_NT arm64 Checked` is confusing

@jashook

**Comment by BruceForstall** [comment]
I agree (I fixed ARM/ARMLB). The fix is here: https://github.com/dotnet/coreclr/blob/155728da699955a5fdc36ac394be68114bd53689/netci.groovy#L1234-L1303
