### ISSUE TITLE
[Arm64] Remove dead #defines INS_ADDC et. al.

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#14092]
`INS_ADDC` is only by codegenlegacy.cpp

In `compiler.h` there is a whole series of these defines for each platform.  Most platforms no longer support legacy codegen.

The list in `compiler.h` should be audited and cleaned up.

**Comment by BruceForstall** [comment]
ARM and x86 still build for LEGACY_BACKEND, so it's only ARM64 that can be cleaned up (since x86 and x64 share the defines; unless we split them). At some point (not sure how soon) we might be able to remove `LEGACY_BACKEND` entirely, in which there will be massive opportunities for cleanups.

**Comment by sdmaclea** [comment]
OK  The group should probably be in a `#ifdef LEGACY_BACKEND`

**Comment by sdmaclea** [comment]
Fixed by #14107
