### ISSUE TITLE
[Arm] Implement inst_SET and cleanup 

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#14100]
Implement inst_SET
Use in `genCodeForSetcc()` and `genSetRegToCond()` to cleanup

@dotnet/arm32-contrib

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by mikedn** [comment]
What exactly is this about? ARM32 doesn't have a direct equivalent of CSET/SETcc, it needs a sequence of instructions (either using IT or conditional branches).

**Comment by sdmaclea** [comment]
If you look at #14101, you can see ARM64 code duplication is eliminated using the pseudo instruction `inst_SET`.  ARM32 doesn't have the function, so code is more complicated.

**Comment by sdmaclea** [comment]
The duplication may have been separately eliminated by your rework of relops

**Comment by mikedn** [comment]
OK, so if I understand correctly this is just about moving duplicated code from `genSetRegToCond` and `genCodeForSetcc` to `inst_SET`. I can take care of this.

**Comment by mikedn** [comment]
On a closer look I don't think this change would be useful. It just moves some code from ARM32's `genCodeForSetcc` to `inst_SET` and that's it. 

It would be more useful if we could also implement ARM32's `genSetRegToCond` using `inst_SET` like it's done on ARM64. But we can't do that, the generate code would be worse. Basically `inst_SET` hides the fact that multiple instructions are generated and takes away flexibility.

If anything, I'd rather move `inst_SET` to codegenxarch.cpp and codegenarm64.cpp. It's rather pointless to put a function in a common file and then split the entire function body using ifdefs like that. Not to mention that if you remove the pointless switch what remains is a 2-3 line function...

**Comment by RussKeldorph** [comment]
Closing based on @mikedn's assessment.  Re-open if you disagree.
