### ISSUE TITLE
COR_E_FAILFAST when accessing assembly with derived interface

### ISSUE THREAD

**Issue by gkeongit** [dotnet/coreclr#14110]
Accessing the Assembly.ExportedTypes terminates the application with COR_E_FAILFAST, if the loaded assembly contains an interface, which derives from an interface in another assembly.

This happens only in a .NET Core 2.0 Console App. The same assemblies do not cause the termination in a .NET Framework Console App. I am running the application from VS 2017 15.3.4 debugger. 

**Example**

First assembly contains:
````csharp
namespace SomeClassLibrary
{
    public interface ISomeInterface
    {
    }
}
````

Second assembly contains:

````csharp
namespace CoreClassLibrary
{
    public interface ISomeDerivedInterface : SomeClassLibrary.ISomeInterface
    {
    }
}
````

Console Application contains:

````csharp
static void Main(string[] args)
{
    // load the second assembly with the derived interface
    var coreAssembly =
        Assembly.LoadFrom(@"..\CoreClassLibrary\bin\Debug\netcoreapp2.0\CoreClassLibrary.dll");

    // This instruction terminates the program with a COR_E_FAILFAST
    var coreTypes = coreAssembly.ExportedTypes.ToArray();
}
````

**Comment by jkotas** [comment]
Likely duplicate of https://github.com/dotnet/coreclr/issues/12668. It should be fixed in .NET Core 2.0.1 update.

**Comment by gkeongit** [comment]
OK, I'm closing this and try the update. Thank you.
