### ISSUE TITLE
[Arm64] GT_INTRINSIC // TODO-ARM64-NYI

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#14115]
```
       case GT_INTRINSIC:
        {
            // TODO-ARM64-NYI
            // Right now only Abs/Round/Sqrt are treated as math intrinsics
            noway_assert((tree->gtIntrinsic.gtIntrinsicId == CORINFO_INTRINSIC_Abs) ||
                         (tree->gtIntrinsic.gtIntrinsicId == CORINFO_INTRINSIC_Round) ||
                         (tree->gtIntrinsic.gtIntrinsicId == CORINFO_INTRINSIC_Sqrt));
```

Set could include these (possibly more)
```
        case CORINFO_INTRINSIC_Sin:
        case CORINFO_INTRINSIC_Sqrt:
        case CORINFO_INTRINSIC_Abs:
        case CORINFO_INTRINSIC_Cos:
        case CORINFO_INTRINSIC_Round:
        case CORINFO_INTRINSIC_Cosh:
        case CORINFO_INTRINSIC_Sinh:
        case CORINFO_INTRINSIC_Tan:
        case CORINFO_INTRINSIC_Tanh:
        case CORINFO_INTRINSIC_Asin:
        case CORINFO_INTRINSIC_Acos:
        case CORINFO_INTRINSIC_Atan:
        case CORINFO_INTRINSIC_Atan2:
        case CORINFO_INTRINSIC_Log10:
        case CORINFO_INTRINSIC_Pow:
        case CORINFO_INTRINSIC_Exp:
        case CORINFO_INTRINSIC_Ceiling:
        case CORINFO_INTRINSIC_Floor:
```

**Comment by sdmaclea** [comment]
@russellhadley @jkotas I just looked at XARCH code and most of these are not supported yet there either.  Is this something which is no longer recommended with new style intrinsics?

**Comment by jkotas** [comment]
cc @tannergooding

**Comment by sdmaclea** [comment]
Looks like only these two can be mapped to Arm64 intrinsics
```
        case CORINFO_INTRINSIC_Ceiling:
        case CORINFO_INTRINSIC_Floor:
```

`FRINTP` & `FRINTM` respectively

**Comment by tannergooding** [comment]
I believe most of them were actual intrinsics in the legacy JIT (where the x87 FPU covered most of these instructions).

However, there is no equivalent instruction for most of these under SSE/SSE2 (and the call to the SSE/SSE2 implementation is generally faster and more accurate than the x87 FPU version anyways).

I'm not sure what the case is for ARM.

**Comment by sdmaclea** [comment]
These transforms are also possible, but not necessarily easy.
`conv.i(round.d(d)) -> round.i(d)` `fcvtnu` or `fcvtns`
`conv.i(floor.d(d)) -> floor.i(d)` `fcvtmu` or `fcvtms`
`conv.i(ceil.d(d)) -> ceil.i(d)` `fcvtpu` or `fcvtps`

**Comment by sdmaclea** [comment]
@tannergooding Thanks
