### ISSUE TITLE
Update performance tests to use NetStandard1.5

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/coreclr#14124]
Almost all of the performance tests are build against netstandard1.4 as it was required before we switched to a .NET Core version of the performance runner.  Since we have done this we have not updated the tests to netstandard1.5, and gain the additional APIs that entails.  Doing this would resolve https://github.com/dotnet/coreclr/pull/9281 and allow us to remove this hack https://github.com/dotnet/coreclr/pull/9315.

category:correctness
theme:benchmarks
skill-level:intermediate
cost:small

**Comment by BruceForstall** [comment]
@DrewScoggins Do you know when this might happen? #9281 bit me recently (see #14989)

**Comment by DrewScoggins** [comment]
@jorive as well here. I believe that we made the decision to have all performance tests run on the lowest netstandard version that is possible. This was to ensure that the binaries are as portable as possible. If a particular set of tests need to be updated to a newer version of netstandard, submit the PR and we can merge it. There is nothing technical blocking that from happening.

**Comment by jorive** [comment]
@BruceForstall Yes, you should be able to move the benchmarks to any netstandard you need. Our only suggestion is to keep it on the lowest possible netstandard if possible. This is to allow us to run the benchmark on release1.1 as a baseline.
Additionally, port the changes to the release1.1 and release2.0 branches.

**Comment by AndyAyersMS** [comment]
Fixed via #16378.

**Comment by AndyAyersMS** [comment]
Unfixed via #16647.

**Comment by AndyAyersMS** [comment]
Seems complex enough that we should defer this until after 2.1. So moving to Future.

**Comment by billwert** [comment]
I can't close this issue but it seems clear it should be closed, as we don't use xunit-perf anymore as far as I know. @AndyAyersMS can you close this?

**Comment by AndyAyersMS** [comment]
There are still copies of these tests in coreclr, and they're still useful, to jit devs anyways. 

They got updated when we updated the tests to the new csproj format.
