### ISSUE TITLE
[RyuJIT] Enable CORINFO_INTRINSIC Round, Ceiling, and Floor to generate ROUNDSS and ROUNDSD

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#14134]
SSE4.1 added the `ROUNDSS` and `ROUNDSD` instructions. For machines which support them, we should support emitting them for the `Round`, `Ceiling`, and `Floor` methods in `System.Math` and `System.MathF`.

**Comment by tannergooding** [comment]
FYI. @fiigii 

I think this will be more readily possible once https://github.com/dotnet/coreclr/pull/14020 goes in (since we will be able to properly distinguish SSE4.1 from SSE3; today they are combined into the `InstructionSet_SSE3_4` value)

**Comment by fiigii** [comment]
> I think this will be more readily possible once #14020 goes in (since we will be able to properly distinguish SSE4.1 from SSE3; today they are combined into the InstructionSet_SSE3_4 value)

Yes, I think so, and it will be finished soon. Are you implementing these math intrinsics?

**Comment by tannergooding** [comment]
I plan on doing so, if someone else doesn't get to them first.
