### ISSUE TITLE
[RyuJIT/x86] Assertion failed 'op1 != nullptr'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#14149]
```
c:\gh\coreclr>c:\gh\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe c:\gh\coreclr\bin\tests\Windows_NT.x86.Checked\JIT\opt\Enum\hasflag\hasflag.exe

Assert failure(PID 27944 [0x00006d28], Thread: 33716 [0x83b4]): Assertion failed 'op1 != nullptr' in 'P:Main():int' (IL size 797)

    File: c:\gh\coreclr\src\jit\gentree.cpp Line: 5936
    Image: c:\gh\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

**Comment by BruceForstall** [comment]
@AndyAyersMS You recently added this test. Did you test with x86?

**Comment by AndyAyersMS** [comment]
I ran the regular CI tests, but it looks like the test case ended up as Pri1. I likely cloned a neighboring test project that had been pri1-ified recently.

So maybe it doesn't get tested normally in x86 CI? We seem to be purging the test logs pretty aggressively now. I can't tell if it ran or not back then.

**Comment by AndyAyersMS** [comment]
Issue is that `gtClone` does not handle `GT_CNS_LNG` for some reason. Should be simple to fix.
