### ISSUE TITLE
[Arm64/Unix] Enable FEATURE_EVENT_TRACE

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#14148]
tracing/eventpipesmoke/eventpipesmoke/eventpipesmoke.sh

```
./corerun eventpipesmoke.exe
Start: Enable tracing.
End: Enable tracing.

Start: Allocation.
End: Allocation.

Start: Disable tracing.
End: Disable tracing.

Created 387 bytes of data
Expected: 100
Actual: 0
```

@dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
@brianrob @nategraf @jkotas Do you know if this test should pass on Ubuntu?  It is not clear to me why this was working at all or why it recently stopped working.

**Comment by sdmaclea** [comment]
Last known passing 5d37885730.  First known failure 52f428891a7

**Comment by nategraf** [comment]
This test should be passing on Ubuntu, and it is enabled as priority 1. This tests was recently https://github.com/dotnet/coreclr/pull/14127 enabled in CI.

I am unaware of the status of EventPipe's functionality on ARM64.

**Comment by sdmaclea** [comment]
> This tests was recently #14127 enabled in CI.
Thanks.  That explains why it is a new fail.  

I suspect event tracing support is not present for arm64/unix.  I'll let @dotnet/arm64-contrib confirm.  If so, this issue should be changed to "[Arm64/Unix] Enable event tracing"

**Comment by brianrob** [comment]
This is probably because FEATURE_EVENT_TRACE is not enabled: https://github.com/dotnet/coreclr/blob/master/clrfeatures.cmake#L2

**Comment by brianrob** [comment]
It is reasonable to disable this test on arm64 until this functionality works.

**Comment by sdmaclea** [comment]
Not sure why, but this was not sufficient to fix the test.
```
diff --git a/clrfeatures.cmake b/clrfeatures.cmake
index 3d5d155..99d9971 100644
--- a/clrfeatures.cmake
+++ b/clrfeatures.cmake
@@ -18,6 +18,8 @@ if(NOT DEFINED FEATURE_EVENT_TRACE)
       set(FEATURE_EVENT_TRACE 1)
     elseif(CLR_CMAKE_TARGET_ARCH_ARM)
       set(FEATURE_EVENT_TRACE 1)
+    elseif(CLR_CMAKE_TARGET_ARCH_ARM64)
+      set(FEATURE_EVENT_TRACE 1)
     endif()
   endif(CLR_CMAKE_PLATFORM_LINUX)
 endif(NOT DEFINED FEATURE_EVENT_TRACE)
```

**Comment by sdmaclea** [comment]
> Not sure why

Test fails with an assert if above patch is used.
```
Created 9662116 bytes of data

Assert failure(PID 8437 [0x000020f5], Thread: 8437 [0x20f5]): !"Heap contamination detected! HeapFree was called on a heap other than the one that memory was allocated from.\n" "Possible cause: you used new (executable) to allocate the memory, but didn't use DeleteExecutable() to free it."
    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/vm/hosting.cpp Line: 490
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/corerun
```

**Comment by sdmaclea** [comment]
@janvorli @jkotas Is there something which needs to be implemented to enable FEATURE_EVENT_TRACE on a new platform?

**Comment by sdmaclea** [comment]
Trying also removing 
`
<_PlatformDoesNotSupportEventTrace Condition="'$(Platform)' == 'arm64'">true</_PlatformDoesNotSupportEventTrace>
`

**Comment by janvorli** [comment]
@sdmaclea there should be nothing to add. Only the lttng-ust-dev package needs to be installed to build with that feature on.
