### ISSUE TITLE
Question: Mark tests for conditional disabling

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#14157]
In dotnet/coreclr tests, it is possible to mark a test with various characteristics ("traits"), and then choose which tests NOT to run based on the tests so marked?

There is issues.targets, but it appears that is only used at test BUILD time, not test RUN time. I want to be able to (for example) build the x86 release tests once, then run any number of JIT stress modes, or altjit runs, with each type of run disabling some (different) subset of tests. I don't want to have to build the test wrappers again for each run type. I don't want to disable (via the existing issues.targets) the union of all failing tests for all possible modes (this is far too many, especially when considering altjit and platform bring-up).

It looks like xunit has a `-notrait` feature, but I don't see if it is currently plumbed through from a dotnet/coreclr test proj file to the auto-generated xunit wrappers, for example.

@RussKeldorph @dotnet/jit-contrib @wtgodbe

**Comment by RussKeldorph** [comment]
We could add this as part of #4840.
