### ISSUE TITLE
Unsafe static readonly declaration order results in different values assigned

### ISSUE THREAD

**Issue by eltechnic0** [dotnet/coreclr#14151]
I am not sure if this issue really fits in this repo, or if its an issue whatsoever, but here it goes.

Given this code:

```csharp

    class SizeofConstComesBefore
    {
        public unsafe static readonly int ConstSizeof = sizeof(int);
        public static readonly int ConstComposed = ConstSizeof + 1;
    }

    class SizeofConstComesAfter
    {
        public static readonly int ConstComposed = ConstSizeof + 1;
        public unsafe static readonly int ConstSizeof = sizeof(int);
    }
```

The values of the readonly variables are:

For `class SizeofConstComesBefore`: 
- `ConstSizeof = 4`
- `ConstComposed = 5`

For `class SizeofConstComesAfter`: 
- `ConstSizeof = 4`
- `ConstComposed = 1`

Is this the intended behavior?

I'm using:
- C# compiler version 2.3.2.62030 (b1476ba8)
- Net Framework 4.6.1 (installed is 4.7.02046)
- Visual Studio Community 2017 15.3.4+26730.15

**Comment by stephentoub** [comment]
See https://msdn.microsoft.com/en-us/library/aa645758(v=vs.71).aspx

"The static field variable initializers of a class correspond to a sequence of assignments that are executed in the textual order in which they appear in the class declaration."

**Comment by eltechnic0** [comment]
Your totally right, this is the expected behaviour. Also in [https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/static](url)
