### ISSUE TITLE
Several of the FileSystemWatcherTests are failing after PR 14043

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#14154]
It seems that https://github.com/dotnet/coreclr/pull/14043 introduced four failures in the CoreFX baseline tests:
* System.IO.Tests.File_Create_Tests.FileSystemWatcher_File_Create
* System.IO.Tests.FileSystemWatcherTests_netstandard17.EndInit_ResumesPausedEnableRaisingEvents
* System.IO.Tests.FileSystemWatcherTests_netstandard17.EndInit_ResumesPausedEnableRaisingEvents(setBeforeBeginInit: True)
* System.IO.Tests.FileSystemWatcherTests_netstandard17.EndInit_ResumesPausedEnableRaisingEvents(setBeforeBeginInit: False)

These were first detected in https://github.com/dotnet/coreclr/pull/14119 (Job: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_corefx_baseline_prtest/98/). But they also appeared earlier in the daily runs of the job: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_corefx_baseline/298/.

NOTE: It wasn't detected earlier due to other build failures in the job that was caused by an unrelated change.

I did validate that it repro's as of the PR commit (555f436263ed5632443efbcc9b860a7d7c5069a3), but not in the commit prior to that (5d3788573000ed800c5b6851c3c93b59fca3946a).

**Comment by tannergooding** [comment]
FYI. @stephentoub, @pjanotti, @JeremyKuhne, since you were the reviewers and/or tagged for review on the associated PR.

**Comment by poizan42** [comment]
The ftruncate call fires a MODIFY inotify event (even on an empty file). I think the solutions are:

1. Make [ExpectEvent](https://github.com/dotnet/corefx/blob/a7f6f470cb2c4cdaafdc3ad85e2520992a8db265/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs#L116) more tolerant of "spurious" events like on OSX.
2. A limited version of 1. - add an argument to ExpectEvent to tell it that an event is allowed but not required.
3. Make the tests use CreateNew or OpenOrCreate rather than Create
4. Check whether the file is empty before truncating

Option 4. incurs an overhead of an extra syscall. Option 3. is complicated by the fact that the tests in tests/FileSystemWatcherTest.cs creates the file through TempFile which in turn calls File.WriteAllBytes.

**Comment by pjanotti** [comment]
Thanks @tannergooding.

@poizan42 at first glance I agree: either solution 1 or 2, initially I am leaning towards 1.

**Comment by pjanotti** [comment]
/cc @jkotas 

Marked failed tests as active issues: https://github.com/dotnet/corefx/pull/24305

**Comment by poizan42** [comment]
@pjanotti @stephentoub I can make a PR, but first I would like to know which of the solutions to go with. The strict verification on non-OSX ensures that backwards compatibility is kept at least per-platform, even though user programs probably shouldn't rely on that. But of course #14043 already did change the behaviour so it could break badly written programs.

**Comment by pjanotti** [comment]
Thanks @poizan42. The less strict verification makes more sense to me, making it very strict means that we risk to have to adapt whenever a new platform comes onboard and the adaptation is to "correct" the test.

**Comment by pjanotti** [comment]
Hi @poizan42 do you have time to work on this? If yes I can assign it to you, if not, (of course) it is fine, I can take a look at it.

**Comment by poizan42** [comment]
@pjanotti You can assign me :)

**Comment by pjanotti** [comment]
Thanks. I discovered that I can't actually assign the issue to you. Your name/alias doesn't show on the set of possible assignees.

@karelz is @poizan42 missing some step/approval in order to be assigned stuff to him on coreclr?

**Comment by poizan42** [comment]
@pjanotti That's because I'm only a Collaborator on corefx and not coreclr, I believe @karelz can fix that

**Comment by pjanotti** [comment]
Ah, that makes sense. So let's do that on your next contribution to coreclr.

**Comment by karelz** [comment]
@poizan42 yes, fixed - check your inbox for the invitation.
Pro tip: Disable notifications on the repo, just enable those where you are mentioned, otherwise you will drown in notifications ;)
