### ISSUE TITLE
Suggestion: Make a list of JIT optimization supported by RyuJIT

### ISSUE THREAD

**Issue by damageboy** [dotnet/coreclr#14163]
From time to time, I learn of "new" (in the sense of not known to me) optimization that RyuJIT or the LegacyJIT can take.

From a recent [example](https://github.com/dotnet/coreclr/pull/14030), I learned, for instance, that:

> For BCL ValueType primitives byte, sbyte, ushort, short, uint, int, ulong, long, IntPtr, UIntPtr, Guid cast via object to the type and use .Equals directly them directly; then rely on the Jit to elide the boxing - meaning the mostly completely inline (e.g. Guid doesn't; though isn't a virtual call)

Or in other words, that in this type of code-construct:
```c#
           if (typeof(TKey) == typeof(byte))
            {
                return (byte)(object)key0 == (byte)(object)key1;
            }
```

The JIT can omit the boxing all together.

As someone attempting to write correct yet readable code, this sort of information, of what the JIT can and can't do, is not available to the best of my knowledge.

Is there a way the a definitive list could be made that describes exactly which optimizations the JIT can make and under what circumstances?

**Comment by jkotas** [comment]
Dup of https://github.com/dotnet/coreclr/issues/12135 ?

**Comment by damageboy** [comment]
Thanks, I assumed I wasn't the first, but couldn't find anything.. I'll port my comments over there
