### ISSUE TITLE
FnGetCLRRuntimeHost should probably take void** instead of IUnknown**

### ISSUE THREAD

**Issue by tandasat** [dotnet/coreclr#14161]
FnGetCLRRuntimeHost defined in [MSCOREE.IDL](https://github.com/dotnet/coreclr/blob/master/src/inc/MSCOREE.IDL) take `IUnknown**` as a second parameter. It diverges from the typical COM related functions to query objects (such as QueryInterface, or CorBindToRuntimeEx) in that it takes `IUnknown**` and not `void**`.

```cpp
#pragma midl_echo("typedef HRESULT  (STDAPICALLTYPE *FnGetCLRRuntimeHost)(REFIID riid, IUnknown **pUnk);")
```

This prevents developers from using `IID_PPV_ARGS` with `FnGetCLRRuntimeHost` just like other functions as `IID_PPV_ARGS` attempts to pass an argument as `void**`. Is it worth changing definition of `FnGetCLRRuntimeHost` to take  `void**`?

**Comment by karelz** [comment]
This is .NET Framework bug, it does not affect .NET Core. We do not track .NET Framework issues on GitHub - [DeveloperCommunity](https://developercommunity.visualstudio.com/spaces/8/index.html) is the right place.

Nevertheless, changing the IDL would be technical breaking change - someone's code might not compile anymore with the fixed version. Given that the impact is minimal (devs can easily cast), I don't think we should make the change. Personally, I would recommend to Won't Fix it for .NET Framework.

Closing as it is not applicable to .NET Core on GitHub.
