### ISSUE TITLE
Activity ID generated for activity tracing is not sufficiently unique.

### ISSUE THREAD

**Issue by JamesCrompton-MSFT** [dotnet/coreclr#14165]
When activity tracing generates a new "GUID" (packed path) for Start or Send events, it does not create a unique enough GUID when considering multi process and multi server scenarios. The same GUID will be generated on multiple machines and processes simultaneously making it very difficult to parse the logs using just activity ID. A combination of process ID, machine name and time range are all required in order to uniquely identify an execution thread.

@vancem, @brianRob - I believe the fix for this may already be in but opening the issue as we discussed.

**Comment by brianrob** [comment]
@vancem, it looks like you've already added processID - https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Diagnostics/Tracing/ActivityTracker.cs#L514.  Do we want to keep this bug aroudn to track adding more uniqueness?

**Comment by vancem** [comment]
I think we can close this.
