### ISSUE TITLE
JIT: possible TP improvements when inlining

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#14174]
A couple of ideas that might improve throughput when inlining.

During inlining, the jit must walk the arguments to the original call and determine how to propagate the values into the inline body. Doing this entails some case analysis depending on the shape of the arg tree and the kinds of uses in the arg in the inlinee body.

When call arguments are the return values from inlined calls, the jit will see `GT_RET_EXPR` placeholder nodes.  These placeholders have conservative side effect flags and obscure the shape of the arg tree. The inliner could walk back through these nodes to the actual tree and use that tree instead. For example:
```C#
int R3() { return 3; }
int X(int val) { ... }
int Y() { X(R3()) }
```
This would apply when inlining `X` into `Y`.

A similar thing might be possible earlier, when importing `X` to be inlined -- if th;e jit tunnels through the return placeholders it could directly substitute `R3`'s return value into the body of `X`.

A likely way to catch both of these cases is to revise the `inlArgInfo` for an inlinee when the `argNode` is a `GT_RET_EXPR`.

**Comment by mikedn** [comment]
Trivial (and likely very common inline candidates) methods like `return 3` should probably bypass the whole inlinee compiler stuff. It should be easy and efficient to peek at the inlinee IL and recognize trivial patterns - ldc/ret, ldfld/ret and maybe even some call/ret cases.

**Comment by AndyAyersMS** [comment]
Maybe? It is a tempting idea.

The preliminary at IL scan we do to qualify a method as an inline candidate avoids asking the VM a lot of the hard/expensive questions (for instance, resolving tokens and then checking method and field properties). These questions are deferred until importation. And the answers to those questions can alter jit codegen. They also must be asked in the context of the inlinee.

I am not aware of any up-front checks we can to to be confident a given method's importation will be simple.

**Comment by AndyAyersMS** [comment]
Thinking about this some more, perhaps I partially answered my own question -- when a method's IL does not contain any tokens then importation is likely straightforward and context free. Any exceptions are likely catchable by looking at the method flags, which is fairly cheap.

Unfortunately that rules out field accesses.

Might be interesting to see what fraction of inlinees have no IL tokens.

**Comment by mikedn** [comment]
> Unfortunately that rules out field accesses

And unfortunately those will likely be very common, there are many property getters and setters out there that do just that.

**Comment by AndyAyersMS** [comment]
Considering this for 2.1.
