### ISSUE TITLE
coreclr_initialize failed

### ISSUE THREAD

**Issue by toxsedyshev** [dotnet/coreclr#1419]
Trying to run HelloWorld using that manual: 
https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md

Got that error while trying to run the application:
coreclr_initialize failed - status: 0x80004005

What's wrong?

**Comment by ellismg** [comment]
As a start, you might try enabling PAL logging and see if it gives any clues.

`export PAL_DBG_CHANNELS="+all.all"`

This will produce a lot of spew, but might help narrow down things.  The comments in [dbgmsg.h](https://github.com/dotnet/coreclr/blob/master/src/pal/src/include/pal/dbgmsg.h) explain more about how the logging works.

**Comment by Nikolay-Kha** [comment]
Hello!
I have the same issue. My logs are here:
https://drive.google.com/file/d/0B9jKFl3qYG3pZjRRWC1scjdLck0/view?usp=sharing
I found just one interesting line(#3269):
{0xb5e-0x7fd9609e73d0} ERROR [LOADER ] at MAPMapPEFile.2418: Magic number mismatch
but my HelloWorld.exe starts with:
00000000 4d 5a 90 00 03 00 00 00 04 00 00 00 ff ff 00 00 MZ..............
and PE magic looks good.
SO, I don't have any clue what's wrong.

**Comment by janvorli** [comment]
This error usualy means that the mscorlib.dll doesn't match the libcoreclr.so, which means that either they are built from different version of source code (although if there was no change in the interface between these libraries, it should work ok) or one is debug build and the other is release build. 
Or, you might have mscorlib.ni.dll in the folder where you have libcoreclr.so. This would be the windows precompiled version of mscorlib, which obviously cannot be loaded on Linux. And the magic number mismatch in the log would probably be a hint that this is going on. Deleting the mscorlib.ni.dll should fix the issue.

**Comment by nguyenm100** [comment]
see https://github.com/dotnet/coreclr/issues/1456

**Comment by tzwlai** [comment]
Closing this since it looks like the problem has been resolved.  Please feel free to reopen if that's not the case.
