### ISSUE TITLE
ExecutionEngineException with optimizations enabled in SIMD-including code

### ISSUE THREAD

**Issue by RossNordby** [dotnet/coreclr#14245]
When optimizations are enabled, calling Test in the following triggers a System.ExecutionEngineException.
```cs
    public class ExecutionEngineExceptionRepro
    {
        public struct Wrapper
        {
            public Vector3 Vector1;
            public Vector3 Vector2;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        public static void SomeOtherFunction(ref Wrapper w)
        {
        }

        void SomeFunction()
        {
            var wrapper = new Wrapper();
            SomeOtherFunction(ref wrapper);
            var v = new Vector<float>();
        }
        
        public static int Test()
        {
            var test = new ExecutionEngineExceptionRepro();
            test.SomeFunction();
            return test.GetHashCode();
        }
    }
```
The exception appears extremely finicky; many small changes can suppress the error. I haven't dug into it much, but it seems to require the presence of SIMD types.

Reproduced on 2.0.0. I haven't yet tested on 2.1 previews (my environment is a bit hosed).

**Comment by RossNordby** [comment]
Hm, now that I think of it, this might just be a duplicate of https://github.com/dotnet/coreclr/issues/12950. I had forgotten about that one, but it has a very similar setup- clearing 16 bytes for the 12 byte Vector3 type in Wrapper.

**Comment by AndyAyersMS** [comment]
Doesn't seem to repro in current master, and does look a lot like #12950. I think the fix for that has made it into a 2.0 servicing release; I am double-checking which one...

**Comment by AndyAyersMS** [comment]
Looks like it is slated for 2.0.3, which should be out soon.

**Comment by AndyAyersMS** [comment]
2.0.3 is [now available](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.3.md). Please let us know if this doesn't fix the issue.

**Comment by RossNordby** [comment]
Looks like 2.0.3 fixed it; thanks!
