### ISSUE TITLE
Poor dynamic performance

### ISSUE THREAD

**Issue by JamesNK** [dotnet/coreclr#1425]
Originally https://github.com/aspnet/dnx/issues/2541

---

A Json.NET unit test that stress tests `dynamic` is much slower when run via DNX

Microsoft .NET Development Utility CoreCLR-x64-1.0.0-beta8-15120

```
private void UpdateValueCount(IDictionary<string, int> counts, dynamic d)
{
    string s = d.ToString();

    int c;
    if (!counts.TryGetValue(s, out c))
    {
        c = 0;
    }

    c++;
    counts[s] = c;
}

[Test]
public void DeserializeLargeDynamic()
{
    dynamic d;

    using (var jsonFile = System.IO.File.OpenText("large.json"))
    using (JsonTextReader jsonTextReader = new JsonTextReader(jsonFile))
    {
        JsonSerializer serializer = new JsonSerializer();
        d = serializer.Deserialize(jsonTextReader);
    }

    IDictionary<string, int> counts = new Dictionary<string, int>();

    Stopwatch sw = new Stopwatch();
    sw.Start();

    foreach (dynamic o in d)
    {
        foreach (dynamic friend in o.friends)
        {
            UpdateValueCount(counts, friend.id);
            UpdateValueCount(counts, ((string) friend.name).Split(' ')[0]);
        }
    }

    Console.WriteLine("Time (secs): " + sw.Elapsed.TotalSeconds);
}
```

https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json.Tests/large.json

DNX: Time (secs): 314.7453895
.NET 4.5: Time (secs): 0.1715269

**Comment by mikedn** [comment]
With .NET 4.5 when a dynamic callsite is executed for the first time an exception is thrown: 

```
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Additional information: 'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'friends'
```

With .NET Core the same exception is thrown every time when the callsite is executed. No wonder that it's extremely slow.

Might be a bug somewhere in .NET Core's version of Microsoft.CSharp or System.Dynamic.Runtime.

**Comment by RichiCoder1** [comment]
If it's an issue with Microsoft.CSharp's Runtime Binder, then this would actually be a corefx issue.
Relevant code: https://github.com/dotnet/corefx/tree/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder

**Comment by JamesNK** [comment]
Checked in repro: https://github.com/JamesNK/Newtonsoft.Json/tree/a9ea63da59cc90b474bee5a6f351e9fad55a44bf

build\runbuild.cmd builds and tests everything, including the slow test on CoreCLR.

**Comment by jkotas** [comment]
cc @AlekseyTs

**Comment by mikedn** [comment]
Here's a simpler repro:
```C#
using System;
using System.Diagnostics;
using System.Dynamic;

public class Program
{
    public static void Main()
    {
        dynamic[] a = new dynamic[1000];

        for (int i = 0; i < a.Length; i++)
        {
            a[i] = new ExpandoObject();
            a[i].id = i;
        }

        var sw = Stopwatch.StartNew();
        int sum = 0;

        for (int i = 0; i < a.Length; i++)
            sum += a[i].id;

        Console.WriteLine("Result: {0} Time {1} secs", sum, sw.Elapsed.TotalSeconds);
    }
}
```
Takes ~18 seconds when run on CoreCLR and only ~0.001 seconds when run on .NET 4.6.

**Comment by mikedn** [comment]
Yup, this is a bug for corefx. 

During porting to CoreCLR a [method](https://github.com/dotnet/corefx/blob/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/BinderHelper.cs#L196) that checked for transparent proxies was changed in such a way that now it always returns true. This prevents "rules" cached for one dynamic instance to be reused for a different dynamic instance.

That method should probably always return false as CoreCLR doesn't support remoting.

I don't know why but this transparent proxy issue seems very familiar to me, as if someone reported this before. But the bug is still there so maybe I'm dreaming...

**Comment by JamesNK** [comment]
Cool, a legitimate perf bug :bowtie:

I don't suppose you get one of those sweat Cup of T's for logging issues or is it PRs only?

**Comment by AlekseyTs** [comment]
@VSadov FYI
