### ISSUE TITLE
Path.GetFullPath

### ISSUE THREAD

**Issue by avenicci** [dotnet/coreclr#14257]
GetFullPath corrupts any file names with trailing U+00A0 (non-breaking space).

Example:
```csharp
Path.GetFullPath("C:\\abc\xA0"); // returns "C:\abc"
```

This behavior is not expected. Only U+0020 should be removed.

I examined the source code and arrived here:
https://referencesource.microsoft.com/#mscorlib/system/io/path.cs,516

This comment suggests the opposite of what happens.
```csharp
// Trim whitespace off the end of the string.
// Win32 normalization trims only U+0020. 
```

**Comment by jkotas** [comment]
cc @JeremyKuhne  @pjanotti

**Comment by JeremyKuhne** [comment]
> This behavior is not expected. Only U+0020 should be removed.

I agree that we shouldn't be doing this anymore, and on Core, we've recently removed this aggressive trimming: https://github.com/dotnet/coreclr/commit/65c3d712eff3f6d0fd913e4a6db7e1061eb63f85

I've marked the issue for porting consideration to the desktop .NET (NetFX). Making the change there is a little bit trickier as we need to allow for limited trust scenarios (as changing the trimming could impact CAS) and retain the old behavior under a quirk setting for compatibility.

**Comment by avenicci** [comment]
Maybe add a "Resolve" method that doesn't throw exceptions and uses GetLongPathName to fix case. I have a helper available that covers all edge cases of paths.

**Comment by JeremyKuhne** [comment]
> Maybe add a "Resolve" method that doesn't throw exceptions and uses GetLongPathName to fix case. I readily have a helper available that covers all edge cases.

We would change `Path.GetFullPath()`, I'm just calling out that it is a bit more involved on NetFX. You should be able to get around the trimming behavior on desktop for now by temporarily putting a trailing separator on the path after manually trimming any trailing space chars.

This "hack" is taking advantage of the way [GetFullPathName](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364963.aspx) works- this is the API all Win32 APIs call implicitly and what we call explicitly from `Path.GetFullPath()`.

``` C#
string path = "Foo\xA0\x20";
// Trimming trailing spaces must be done manually to ensure identical behavior with
// < .NET 4.6.2 and >= .NET 4.6.2
path = path.TrimEnd('\x20');
path = path + Path.DirectorySeparatorChar;
path = Path.GetFullPath(path);
```

**Comment by jkotas** [comment]
This is fixed in .NET Core. Ports to .NET Framework are tracked in MS internal bug database.
