### ISSUE TITLE
Make default(zeynep) evaluate to true

### ISSUE THREAD

**Issue by defaultstuff** [dotnet/coreclr#1427]
After lengthy discussions and some experience in the matter, we believe that default(zeynep) should evaluate to true in the CLR. We are requesting CLR support for this because even after our most persistent efforts we could not make default(zeynep) return true. We are happy to submit a patch for this issue but so far we have been unable to produce a working solution. As such, we would very much appreciate assistance in how to approach the bug.

**Comment by jkotas** [comment]
Could you please try using [fully qualified name](https://en.wikipedia.org/wiki/Fully_qualified_name)? `zeynep` is frequently used name - the unexpected behavior that you are seeing is likely caused by name ambiguity.

**Comment by mikedn** [comment]
Does that mean that we can also request that default(int) is changed to 42? It's well known that 42 is the answer to everything so it doesn't make sense that default(int) currently returns such a worthless quantity as 0.
