### ISSUE TITLE
Ubuntu x64 Release builds error due to missing profile data

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#14289]
e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_ubuntu_longgc/308/consoleText:

```
error: no profile data available for file "hwintrinsicxarch.cpp" [-Werror,-Wprofile-instr-unprofiled]
1 error generated.
make[2]: *** [src/jit/standalone/CMakeFiles/clrjit.dir/__/hwintrinsicxarch.cpp.o] Error 1
```

Looks like `hwintrinsicxarch.cpp` is a brand new file and hasn't gotten profile data yet. Maybe we need an update?

**Comment by swgillespie** [comment]
hmm, not sure who deals with PGO nowadays - @nategraf would you know?

**Comment by BruceForstall** [comment]
Shouldn't this be a warning, not an error? Or else this will happen every time we add a file.

**Comment by swgillespie** [comment]
It looks like clang accepts `-Wno-error` to opt-out of `-Werror` for specific warnings - we should probably do so here.

**Comment by swgillespie** [comment]
Looks like this is going to be made moot by https://github.com/dotnet/coreclr/pull/14290.

**Comment by 4creators** [comment]
This issue is tracked by #13655 

One of the workarounds is to pass -nopgooptimize on command line as described in #13642
