### ISSUE TITLE
abs overload for 64-bit ints missing when building with clang 3.5 (?)

### ISSUE THREAD

**Issue by poizan42** [dotnet/coreclr#143]
When building with clang I get the following warning and variations thereof:
```
In file included from /home/poizan/coreclr/src/jit/jitpch.h:20:
/home/poizan/coreclr/src/jit/jit.h:608:31: warning: absolute value function 'abs' given an argument of type 'ssize_t' (aka 'long') but has parameter of type 'int' which may cause truncation of value [-Wabsolute-value]
    return ((size_t)          abs(x));
                              ^
/home/poizan/coreclr/src/jit/jit.h:608:31: note: use function 'std::abs' instead
    return ((size_t)          abs(x));
                              ^~~
                              std::abs
/home/poizan/coreclr/src/jit/jit.h:608:31: note: include the header <cstdlib> or explicitly provide a declaration for 'std::abs'
```

This seems a bit weird as jitpch.h does in fact include cstdlib. But it also includes stdlib.h before that, so maybe the clang version of cstdlib fails to take this possibility into account.

clang version:
```
Debian clang version 3.5.0-9 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

**Comment by poizan42** [comment]
Actually the standard lib cstdlib is never included. Here is the relevant part from running the clang preprocessor:

```C++
#line 1750 "/home/poizan/coreclr/src/pal/inc/rt/palrt.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/sscli_version.h"
#line 1751 "/home/poizan/coreclr/src/pal/inc/rt/palrt.h"
#line 7 "/home/poizan/coreclr/src/pal/inc/rt/stdint.h"
#line 8 "/home/poizan/coreclr/src/jit/jitpch.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/windows.h"
#line 9 "/home/poizan/coreclr/src/jit/jitpch.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/wchar.h"
#line 10 "/home/poizan/coreclr/src/jit/jitpch.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/stdio.h"
#line 11 "/home/poizan/coreclr/src/jit/jitpch.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/stddef.h"
#line 12 "/home/poizan/coreclr/src/jit/jitpch.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/stdlib.h"
#line 13 "/home/poizan/coreclr/src/jit/jitpch.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/limits.h"
#line 14 "/home/poizan/coreclr/src/jit/jitpch.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/string.h"
#line 15 "/home/poizan/coreclr/src/jit/jitpch.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/float.h"
#line 16 "/home/poizan/coreclr/src/jit/jitpch.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/share.h"
#line 17 "/home/poizan/coreclr/src/jit/jitpch.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/cstdlib"
#line 18 "/home/poizan/coreclr/src/jit/jitpch.h"
#line 1 "/home/poizan/coreclr/src/pal/inc/rt/intrin.h"
```

The pal cstdlib file just contains and include of palrt.h, but that only provides an `int abs(int)` from pal.h

**Comment by sergiy-k** [comment]
@poizan42  Interesting… I don’t see this warning. I guess this is due to a difference in toolchain version. In any case, we should fix. I will add an overload unless, of course, you’d like to add it yourself and submit a pull request. :)

Regarding inclusion of standard libraries. When building on Linux, only PAL is allowed to include header files from standard libraries. All other components of CoreCLR (runtime, jit, etc) are not allowed to do that. They should include PAL header files only.

**Comment by poizan42** [comment]
@sergiy-k Do I understand it correctly that palrt.h should declare the signature itself and not include the system's cstdlib?

**Comment by janvorli** [comment]
@poizan42 Yes, that's correct. Anything running on top of PAL should never include any platform specific headers.

**Comment by sergiy-k** [comment]
@poizan42 I would put the declaration into pal.h next to abs(int) under “#if defined(BIT64)”.
Thank you!

**Comment by poizan42** [comment]
So I should declare something like this?
```C++
#ifdef __cplusplus
extern "C++" {
inline LONG abs(LONG _X)
{
    return labs(_X);
}
}
#endif
```

Though the C++ standard seems a bit unclear on this, clang refuses to compile it with a declaration has a different language linkage error. Maybe we could define both with C++ linkage if building as C++. But do I understand correctly that PAL only declares the signature and we just hope that it's somewhere inside libc when linking? Is that even guaranteed?

**Comment by poizan42** [comment]
Wait - LONG is (32bit) int and not 64bit.

**Comment by sergiy-k** [comment]
@poizan42 Yes, correct. It should be __int64 instead of LONG.

**Comment by poizan42** [comment]
Actually as pointed out by @jkotas labs takes a LONG, so we are actually completely missing an llabs implementation. But should we just add its signature and expect it to be in libc? It might be implemented as a macro or inline function and not even exist in the system's libc.

**Comment by poizan42** [comment]
Uhm, if I declare llabs with __int64 then clang gives me this warning:
```
/home/poizan/coreclr/src/pal/inc/pal.h:5438:27: warning: incompatible redeclaration of library function 'llabs' [-Wincompatible-library-redeclaration]
PALIMPORT __int64 __cdecl llabs(__int64);
                          ^
/home/poizan/coreclr/src/pal/inc/pal.h:5438:27: note: 'llabs' is a builtin with type 'long long (long long)'
```

It dosn't complain if I declare it with long long instead.

**Comment by poizan42** [comment]
So what about this? Don't know if llabs should be 64-bit only?

**Comment by sergiy-k** [comment]
@poizan42 I agree, it needs to be ‘long long’. I don’t think that it should to be 64bit only. Thank you!
