### ISSUE TITLE
SciMark2 / benchmarkLU performance has degraded ~21% on Linux in the past 8 days

### ISSUE THREAD

**Issue by jorive** [dotnet/coreclr#14303]
Baseline: ee79bb188e097b49f5ffcb36f0d7c86314d45579 (717.92 ms)
Diff (current data): 8eb9adbe7f069638c1457b458c2c5a569eaaabf8 (916.11 ms)

The micro benchmark runs on Ubuntu14.04 in the lab.

**Comment by BruceForstall** [comment]
Postponed until Linux PGO is fixed. E.g., see #14290.
