### ISSUE TITLE
Consider removing String.IsAscii() fast paths

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#14320]
IsAscii needs to enumerate the whole string to check the chars and then caches the result, so it can be  actually slowing things down in situations where we're only going to be operating on a string once (which is probably fairly common).

**Comment by stephentoub** [comment]
https://github.com/dotnet/corert/pull/4673#discussion_r142692843

**Comment by benaadams** [comment]
I was wondering if it would make sense to combine it with `IsInterned` so it only did it for multi-use strings

e.g.
`String.IsInterned(s) && s.IsAscii()`

But suspected that wouldn't be a fast function...

**Comment by benaadams** [comment]
Though `IsAscii` itself is a bit weird as it isn't just `IsAscii` (> 0x7f) but also does a lookup against [`HighCharHelper::HighCharTable`](https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/utilcode/util_nodependencies.cpp#L930-L1107) for `TRUE` so its ascii && not special sorting char

**Comment by tannergooding** [comment]
Maybe we should have explicit extensions methods (provided separately from CoreFX, CoreFXExtensions maybe) that allow fast paths for ASCII.

**Comment by benaadams** [comment]
Though `IsAscii` itself is a bit weird as it isn't just `IsAscii` (> 0x7f) but also does a lookup against [`HighCharHelper::HighCharTable`](https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/utilcode/util_nodependencies.cpp#L930-L1107) for `TRUE` so its ascii && not special sorting char

Might be quicker to test `& 0x80808080 == 0` depending on function; then switch remainder to non-ascii. Though equality would have found its answer if one was true and other was false before upper/lowercasing

**Comment by tannergooding** [comment]
Is there any reason why we can't inline `IsAscii` into each use itself?

That is, currently we are doing a check against the entire string all at once. Why not start out assuming ASCII and once we hit a non ASCII character, break out and continue the rest of the comparisons as non-ASCII?

**Comment by jkotas** [comment]
> Is there any reason why we can't inline IsAscii into each use itself?

Yes, I think it should be the approach. CoreRT has it done that way in multiple places. You can look at this as reconciliation of the implementation between CoreCLR (that has IsAscii) and CoreRT (that does not have IsAscii), measuring perf along to way to make sure that there are no major regressions. For example, https://github.com/dotnet/coreclr/blob/da8b7181dbe362fbfe64c7ef72ff3a4a7db68f24/src/mscorlib/src/System/String.Comparison.cs#L20 vs. https://github.com/dotnet/corert/blob/1562dfa173008e397ec9a3f98c8d5b632391c28b/src/System.Private.CoreLib/src/System/Globalization/CompareInfo.cs#L460

**Comment by bbowyersmyth** [comment]
To help give some data to this item I've run a couple of tests on the existing code.

Test code here https://gist.github.com/bbowyersmyth/0523d23a9fb1ff2e2589cc74e92d2a35 100 character string.


Method |      Mean |     Error |    StdDev |
------------------------------- |----------:|----------:|----------:|
CompareEarlyExitBothCached |  15.98 ns | 0.0077 ns | 0.0064 ns |
CompareEarlyExitRightCached |  88.16 ns | 0.2218 ns | 0.2075 ns |
CompareEarlyExitLeftCached |  87.49 ns | 0.0182 ns | 0.0152 ns |
CompareEarlyExitNoCached | 158.32 ns | 0.0582 ns | 0.0454 ns |
CompareLateExitBothCached | 124.45 ns | 0.0530 ns | 0.0442 ns |
CompareLateExitRightCached | 195.41 ns | 0.4621 ns | 0.4322 ns |
CompareLateExitLeftCached | 194.66 ns | 0.0297 ns | 0.0263 ns |
CompareLateExitNoCached | 266.33 ns | 0.1819 ns | 0.1420 ns |

Method |      Mean |     Error |    StdDev |
------------------------------- |----------:|----------:|----------:|
CompareUnicodeEarlyExitBothCached |  18.00 ns | 0.0066 ns | 0.0062 ns |
CompareUnicodeEarlyExitRightCached |  24.88 ns | 0.0017 ns | 0.0015 ns |
CompareUnicodeEarlyExitLeftCached |  18.12 ns | 0.0032 ns | 0.0028 ns |
CompareUnicodeEarlyExitNoCached |  28.27 ns | 0.0123 ns | 0.0109 ns |
CompareUnicodeLateExitBothCached | 137.02 ns | 0.0982 ns | 0.0820 ns |
CompareUnicodeLateExitRightCached | 209.43 ns | 0.0607 ns | 0.0507 ns |
CompareUnicodeLateExitLeftCached | 137.02 ns | 0.0802 ns | 0.0750 ns |
CompareUnicodeLateExitNoCached | 209.37 ns | 0.3853 ns | 0.3604 ns |


There is about a ~70ns overhead per string to determine if an ascii string is only ascii (plus some other char type checks). Very little overhead to determine a unicode string isn't ascii as long as the character appears at the start. If it's sticking around the IsAscii perf could be improved as that seems expensive.

If its a new ascii string it would need to be reused more than 4 times to gain back the initial calculation expense on early differences. To be more accurate though it may need to be many times that to cover all the short lived strings.

Anyway the test code can be used to determine how much each one improves or regresses. Although its difficult to say how many times a string will be reused.

**Comment by jkotas** [comment]
Fixed by #26759
