### ISSUE TITLE
Cannot run test referencing System.Reflection.Emit.dll

### ISSUE THREAD

**Issue by kingces95** [dotnet/coreclr#14335]
I am be able to build a test that references classes in `System.Reflection.Emit` so I expected I'd be able to run that test as well. What I actually find is that the metadata is available during the build but absent during the run. 

Following the documentation for building tests I find from the msbuild logs that the assembly referenced during a build is:

>packages\Microsoft.Private.CoreFx.NETCoreApp\4.5.0-preview1-25712-02\ref\netcoreapp2.1\System.Reflection.Emit.dll

But the assembly that is used during the run is the one that that ends up at:

>bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\System.Reflection.Emit.dll

And that assembly contains no metadata. I expected it to contain metadata to enable loading classes in the emit namespace.

**Comment by jkotas** [comment]
> And that assembly contains no metadata. 

This assembly contains should contain forwarders to System.Private.CoreLib. The actual implementation of System.Reflection.Emit lives in System.Private.CoreLib.

**Comment by kingces95** [comment]
I thought so, but it does not. At least on my setup. Does yours?

**Comment by kingces95** [comment]
My mistake. It does...
