### ISSUE TITLE
Failed to build test on windows

### ISSUE THREAD

**Issue by Deren-Liao** [dotnet/coreclr#14348]
build-test.cmd  failed. 
The error log shows:
  3397>CSC : error CS0006: Metadata file 'C:\git\coreclr\bin\Product\Windows_NT.x64.Debug\System.Private.CoreLib.dll' could not be found [C:\git\coreclr\tests\src\Interop\ICastable\Castable.csproj]
     3>C:\git\coreclr\tests\dir.traversal.targets(25,5): error : (No message specified) [C:\git\coreclr\tests\src\dirs.proj]
     1>C:\git\coreclr\tests\dir.traversal.targets(25,5): error : (No message specified) [C:\git\coreclr\tests\build.proj]

------------
I just want to run  the corclr tests on Linux.   I need a built release/2.0.0 windows test targets.    Would you please share it to me? I know you guys can build the tests successfully. 

Thanks.

**Comment by sandreenko** [comment]
Can you run build.cmd, it will build both coreclr and tests.
Why don't you build tests on Linux if you want to run them there?

**Comment by Deren-Liao** [comment]
Build , build-test got same errors. 
From document it instructs to build tests form windows and copy it to Linux to run.

**Comment by rartemev** [comment]
@Deren-Liao have you tried to build it on your Linux box using build-test.sh instead?

**Comment by RussKeldorph** [comment]
I don't think there's enough information for us to reproduce this.  If it's still a problem, please provide more details.  If you just want the coreclr tests, they are constantly built in our CI system and can be downloaded from there; for example: https://ci.dot.net/job/dotnet_coreclr/job/release_2.0.0/job/debug_windows_nt_bld/

Choose the latest successful job and select the Build Artifacts link.  The .zip contains archive/bin/tests.zip which can be unzipped to get the tests.

**Comment by Deren-Liao** [comment]
Thanks, I only need the test binaries so that I can run the tests.
