### ISSUE TITLE
All CoreCLR tests failing in 2.0 branch on RH69 with coreclr_initialize failed - status: 0x80131524

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#14344]
https://mc.dot.net/#/product/netcore/200/source/official~2Fcoreclr~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170930.01/workItem/CoreMangLib.components.XUnitWrapper/wilogs

@janvorli @wtgodbe is this an issue you're aware of? I know until recently RH69 was not working in CoreFX 2.0, now it is.

**Comment by janvorli** [comment]
I am not aware of that, I was monitoring only the corefx branch recently. I'll take a look.

**Comment by janvorli** [comment]
@RussKeldorph I am sorry, it went completely out of my radar. Looking into it now.

**Comment by RussKeldorph** [comment]
@janvorli No problem. :)  Thanks for volunteering to look.

**Comment by janvorli** [comment]
It turns out it got fixed by #14892.
