### ISSUE TITLE
Convert.ToBase64String is using "\r\n" line breaks, even on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#14357]
When Base64FormattingOptions.InsertLineBreaks is used, it's using "\r\n" regardless of platform. Presumably that's not the desired behavior...
https://github.com/dotnet/coreclr/blob/da8b7181dbe362fbfe64c7ef72ff3a4a7db68f24/src/mscorlib/shared/System/Convert.cs#L2522-L2523
https://github.com/dotnet/coreclr/blob/da8b7181dbe362fbfe64c7ef72ff3a4a7db68f24/src/mscorlib/shared/System/Convert.cs#L2540-L2541
https://github.com/dotnet/coreclr/blob/da8b7181dbe362fbfe64c7ef72ff3a4a7db68f24/src/mscorlib/shared/System/Convert.cs#L2581

**Comment by poizan42** [comment]
FWIW I would be quite surprised if the behaviour of ToBase64String depended on the platform considering that the consumer is likely not to be the same as the producer. Should probably just always be \n.

**Comment by stephentoub** [comment]
> Should probably just always be \n.

That would be a breaking change and behavioral difference from the .NET Framework.

**Comment by poizan42** [comment]
Hmm yeah that's a problem. What about adding a new value to Base64FormattingOptions to control the newline behaviour?

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #26401](https://github.com/dotnet/corefx/issues/26401) via [**ZenHub**](https://www.zenhub.com/)
