### ISSUE TITLE
await sometimes not posting continuation to current SynchronizationContext

### ISSUE THREAD

**Issue by mconnew** [dotnet/coreclr#14367]
In the WCF team we are seeing CI test failures due to continuations not posting to the current SynchronizationContext. We have tests to verify that if there's a non-default synchronization context set and you are awaiting an asynchronous WCF call that the await continuation is posted back to the synchronization context. We do this by creating a single threaded synchronization context and running the test via the context. We then compare the managed thread id before and after the await to make sure they are the same. This is to emulate the UI scenario with a single threaded dispatcher.  
The failure is timing sensitive as these tests succeed on most CI platforms. They are passing on all OSes except Windows, and only fail with a release build and when we are running against a self hosted service. When the service is running in IIS, it changes the timings sufficiently that the failures disappear. We have not been able to repro the issue locally.  
[This](https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.4.0.0.cs#L168) is one of the failing tests.  
These tests were working with coreclr build 2.1.0-preview1-25720-03 and started failing with coreclr build 2.1.0-preview1-25730-01.  
I've marked this as blocking partner as we can't move forward our dependency versions (so can't release) without this being fixed.

**Comment by stephentoub** [comment]
Thanks for raising the issue.  I broke this in #14178.  The fix is simple.  I'll submit a PR.
