### ISSUE TITLE
Bug! Marshal.GetDelegateForFunctionPoiner returns wrong delegate

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/coreclr#14362]
OS: Windows 10 x64, Ubuntu 16.04 x64
Framework: NetCoreApp 2.0, Net Framework 4.6

Given code:
```CSharp
using System;
using System.Runtime.InteropServices;

namespace MarshalDelegateError
{
    public class Test1
    {
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate IntPtr MyDelegateOne(IntPtr a, IntPtr b, IntPtr c);
    }

    public class Test2
    {
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate IntPtr MyDelegateTwo(IntPtr a, IntPtr b, IntPtr c);
    }

    class Program
    {
        private static IntPtr MyTestFunc(IntPtr a, IntPtr b, IntPtr c)
        {
            return a;
        }

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            IntPtr ptr = Marshal.GetFunctionPointerForDelegate((Test1.MyDelegateOne)MyTestFunc);

            var d1 =(Test1.MyDelegateOne) Marshal.GetDelegateForFunctionPointer(ptr, typeof(Test1.MyDelegateOne));
            var d2 = (Test2.MyDelegateTwo)Marshal.GetDelegateForFunctionPointer(ptr, typeof(Test2.MyDelegateTwo));
            Console.WriteLine("Bug was not reproduced!");
        }
    }
}
```
Produces this error:
![image](https://user-images.githubusercontent.com/10322215/31293838-b8a68db8-aae9-11e7-9177-914b03fa1fe8.png)

But should works fine.

This problem forces developer to manually maintain strong one to one relationship between marshaling delegate name and marshaling delegate signature.

**Comment by dmitriyse** [comment]
Even worth. I tested this problem when MyDelegateOne and MyDelegateTwo are defined in different assemblies and found the same behavior under .Net 4.6

On a NetCoreApp 2.0 I faced with VS debug pause but without any review-able exception.

**Comment by jkotas** [comment]
We need to verify that the delegate is of the right type here: https://github.com/dotnet/coreclr/blob/46ab1d132c9ad471d79afa20c188c2f9c85e5f20/src/vm/comdelegate.cpp#L1449

**Comment by stephentoub** [comment]
This is called out in the docs:
https://msdn.microsoft.com/en-us/library/zdx6dyyh(v=vs.110).aspx
```
The GetDelegateForFunctionPointer method has the following restrictions:
...
You cannot use this method to create a delegate from a function pointer to another managed delegate.
```

**Comment by dmitriyse** [comment]
I got this error, even when function pointer was returned from a C library (CPython in my case).
So I think restriction "You cannot use this method to create a delegate from a function pointer to another managed delegate." is not a root of the problem.

**Comment by dmitriyse** [comment]
I am wrong. It's exactly "You cannot use this method to create a delegate from a function pointer to another managed delegate." restriction.

This code works without the error:

```CSharp
using System;
using System.Runtime.InteropServices;

namespace MarshalDelegateError
{
    public class Test1
    {
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate IntPtr MyDelegateOne(IntPtr a, IntPtr b, IntPtr c);

    }

    public class Test2
    {
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate IntPtr MyDelegateTwo(IntPtr a, IntPtr b, IntPtr c);
    }

    class Program
    {
        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern IntPtr LoadLibraryEx(string lpFileName, IntPtr hFile, uint dwFlags);

        [DllImport("kernel32", CharSet = CharSet.Ansi, ExactSpelling = true, SetLastError = true)]
        internal static extern IntPtr GetProcAddress(IntPtr hModule, string procName);

        private static IntPtr MyTestFunc(IntPtr a, IntPtr b, IntPtr c)
        {
            return a;
        }

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            IntPtr hMoudle = LoadLibraryEx("kernel32.dll", IntPtr.Zero, 0);
            IntPtr ptr = GetProcAddress(hMoudle, "CreateProcessW");
            var d1 =(Test1.MyDelegateOne) Marshal.GetDelegateForFunctionPointer(ptr, typeof(Test1.MyDelegateOne));
            var d2 = (Test2.MyDelegateTwo)Marshal.GetDelegateForFunctionPointer(ptr, typeof(Test2.MyDelegateTwo));
            Console.WriteLine("Bug was not reproduced!");
        }
    }
}
```
Looks like somewhere Managed pointer is converted to unmanaged and then passed back to .Net.
I need to inspect Pythonnet codebase to identify short cirtcuit.

**Comment by dmitriyse** [comment]
I checked pythonnet codebase and it does not contains any Marsha.GetFunctionPointerForDelegate call. Probably some additional action is required to reproduce the problem.

**Comment by dmitriyse** [comment]
I found the way how unmanaged CPython receives function pointer to a managed delegate:

```CSharp
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
    internal struct Thunk
    {
        public Delegate fn;

        public Thunk(Delegate d)
        {
            fn = d;
        }
    }
```

We can close this issue.
@stephentoub thank you for the right suggestion.
