### ISSUE TITLE
Reduce the number of runtime dependencies required to be installed

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/coreclr#14360]
We get a lot of feedback that people have trouble figuring out the right dependencies to install in order to run their self contained applications. In some cases, including the binary or static linking is not a good choice but in others, it may be a fine choice. We need to make some progress here and get down to just a few easy to identify and high level dependencies. 

Other than the experience of getting the dependencies, many of them contribute some size to our docker images so if we can link away some of it, that would be another benefit.

Here is an example issue: https://github.com/dotnet/core/issues/679

This isn't specific to coreclr, it also needs to happen in corefx but I think the static linking option is more relevant to coreclr.

**Comment by RussKeldorph** [comment]
@janvorli Is there remaining work in 2.1 for this?

**Comment by Petermarcu** [comment]
I think @janvorli checked in the last bit of this yesterday.

**Comment by janvorli** [comment]
Right
