### ISSUE TITLE
[RyuJIT/x86][TailcallStress=1] Assertion failed 'header->epilogCount <= 1'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#14376]
Found in an x86 `COMPlus_TailcallStress=1` run

```
Assert failure(PID 13592 [0x00003518], Thread: 11152 [0x2b90]): Assertion failed 'header->epilogCount <= 1' in 'EHTest:f3()' (IL size 6)

    File: e:\gh\coreclr2\src\jit\gcencode.cpp Line: 1628
    Image: E:\gh\coreclr2\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

Test:
```
JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b92289\b92289\b92289.cmd
```

**Comment by BruceForstall** [comment]
@dotnet/arm32-contrib

**Comment by sandreenko** [comment]
I checked many commits but I can't repro this issue. Do you know the git hash that can repro it?

**Comment by sandreenko** [comment]
Can't repro.

**Comment by BruceForstall** [comment]
@sandreenko I've reopened this issue; it still repros. Additional info:
1. It repros on x86; it does not require arm32.
2. It only repros with Checked Core_Root; it doesn't repro when using Debug Core_Root. It still repros with a Debug clrjit.dll copied to the Checked Core_Root.

Example failure: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_tailcallstress_prtest/11/consoleText
