### ISSUE TITLE
IL working in .Net Framework but not in .Net Core 2.0

### ISSUE THREAD

**Issue by luboid** [dotnet/coreclr#14379]
Hi,

I have project 

https://github.com/luboid/ES5.Script/tree/dotnet-core-2 

which compile JavaScript to IL, here is problematic case 

https://github.com/luboid/ES5.Script/tree/dotnet-core-2/TestConsole/test-cases/not-working

*.frmw.txt IL code generated by .Net Framework
*.core.txt IL code generated by .Net Core

IL code is identical and there is no differences but generate exception :

System.InvalidProgramException: Common Language Runtime detected an invalid program.

when executed in .Net Core

I'am using 

http://blogs.msdn.com/b/haibo_luo/archive/2005/10/25/484861.aspx

to catch IL

ES5.Script\EcmaScript\EcmaScriptCompiler.cs:line 384

Win 10 (version:1703, build:15063.608) 
VS 2017 (version:15.3.5)
.Net Core 2.0
.Net Framework 4.7.02046

**Comment by mikedn** [comment]
It appears that there's something wrong with try/catch/finally blocks in your IL code. For example,

```
IL_0210: /* 08  |          */ ldloc.2
IL_0211: /* 45  | ...      */ switch     (IL_027d)
IL_021a: /* dd  | 0000004D */ leave      IL_026c
...
IL_027c: /* dc  |          */ endfinally
IL_027d: /* 07  |          */ ldloc.1
IL_027e: /* 2a  |          */ ret
```
Looks like the switch is inside a try block and it is trying to jump outside of it.

**Comment by svick** [comment]
I agree with @mikedn. I have simplified the JS to:

```js
function test() {
    try {
        return true;
    } finally {
    }
}
```

The IL then looks like this:

```il
.method public static object  test(class [ES5.Script.Core]ES5.Script.EcmaScript.ExecutionContext A_0,
                                   object A_1,
                                   object[] A_2,
                                   class [ES5.Script.Core]ES5.Script.EcmaScript.Objects.EcmaScriptInternalFunctionObject A_3) cil managed
{
  // Code size       191 (0xbf)
  .maxstack  12
  .locals init (class [ES5.Script.Core]ES5.Script.EcmaScript.ExecutionContext V_0,
           object V_1,
           int32 V_2)
  IL_0000:  ldarg.0
  IL_0001:  call       instance class [ES5.Script.Core]ES5.Script.EcmaScript.EnvironmentRecord [ES5.Script.Core]ES5.Script.EcmaScript.ExecutionContext::get_LexicalScope()
  IL_0006:  ldarg.0
  IL_0007:  call       instance class [ES5.Script.Core]ES5.Script.EcmaScript.Objects.GlobalObject [ES5.Script.Core]ES5.Script.EcmaScript.ExecutionContext::get_Global()
  IL_000c:  newobj     instance void [ES5.Script.Core]ES5.Script.EcmaScript.DeclarativeEnvironmentRecord::.ctor(class [ES5.Script.Core]ES5.Script.EcmaScript.EnvironmentRecord,
                                                                                                                class [ES5.Script.Core]ES5.Script.EcmaScript.Objects.GlobalObject)
  IL_0011:  ldc.i4     0x0
  IL_0016:  newobj     instance void [ES5.Script.Core]ES5.Script.EcmaScript.ExecutionContext::.ctor(class [ES5.Script.Core]ES5.Script.EcmaScript.EnvironmentRecord,
                                                                                                    bool)
  IL_001b:  stloc.0
  IL_001c:  ldloc.0
  IL_001d:  ldarg.2
  IL_001e:  ldc.i4     0x0
  IL_0023:  newarr     [mscorlib]System.String
  IL_0028:  ldarg      A_3
  IL_002c:  nop
  IL_002d:  nop
  IL_002e:  ldc.i4     0x0
  IL_0033:  newobj     instance void [ES5.Script.Core]ES5.Script.EcmaScript.Objects.EcmaScriptArgumentObject::.ctor(class [ES5.Script.Core]ES5.Script.EcmaScript.ExecutionContext,
                                                                                                                    object[],
                                                                                                                    string[],
                                                                                                                    class [ES5.Script.Core]ES5.Script.EcmaScript.Objects.EcmaScriptInternalFunctionObject,
                                                                                                                    bool)
  IL_0038:  ldstr      "arguments"
  IL_003d:  ldloc.0
  IL_003e:  call       instance class [ES5.Script.Core]ES5.Script.EcmaScript.EnvironmentRecord [ES5.Script.Core]ES5.Script.EcmaScript.ExecutionContext::get_VariableScope()
  IL_0043:  ldc.i4     0x0
  IL_0048:  ldc.i4.0
  IL_0049:  call       void [ES5.Script.Core]ES5.Script.EcmaScript.EnvironmentRecord::CreateAndSetMutableBindingNoFail(object,
                                                                                                                       string,
                                                                                                                       class [ES5.Script.Core]ES5.Script.EcmaScript.EnvironmentRecord,
                                                                                                                       bool,
                                                                                                                       bool)
  IL_004e:  ldarg.1
  IL_004f:  call       class [ES5.Script.Core]ES5.Script.EcmaScript.Objects.Undefined [ES5.Script.Core]ES5.Script.EcmaScript.Objects.Undefined::get_Instance()
  IL_0054:  beq        IL_0064
  IL_0059:  ldarg.1
  IL_005a:  brfalse    IL_0064
  IL_005f:  br         IL_0070
  IL_0064:  ldloc.0
  IL_0065:  call       instance class [ES5.Script.Core]ES5.Script.EcmaScript.Objects.GlobalObject [ES5.Script.Core]ES5.Script.EcmaScript.ExecutionContext::get_Global()
  IL_006a:  starg      A_1
  IL_006e:  nop
  IL_006f:  nop
  IL_0070:  ldloc.0
  IL_0071:  call       instance class [ES5.Script.Core]ES5.Script.EcmaScript.Objects.GlobalObject [ES5.Script.Core]ES5.Script.EcmaScript.ExecutionContext::get_Global()
  IL_0076:  call       instance void [ES5.Script.Core]ES5.Script.EcmaScript.Objects.GlobalObject::IncreaseFrame()
  .try
  {
    IL_007b:  call       class [ES5.Script.Core]ES5.Script.EcmaScript.Objects.Undefined [ES5.Script.Core]ES5.Script.EcmaScript.Objects.Undefined::get_Instance()
    IL_0080:  stloc.1
    .try
    {
      IL_0081:  ldc.i4.1
      IL_0082:  box        [mscorlib]System.Boolean
      IL_0087:  stloc.1
      IL_0088:  ldc.i4     0x0
      IL_008d:  stloc.2
      IL_008e:  br         IL_0095
      IL_0093:  ldc.i4.m1
      IL_0094:  stloc.2
      IL_0095:  ldloc.2
      IL_0096:  switch     ( 
                            IL_00bd)
      IL_009f:  leave      IL_00ac
    }  // end .try
    catch [mscorlib]System.Exception 
    {
      IL_00a4:  pop
      IL_00a5:  rethrow
      IL_00a7:  leave      IL_00ac
    }  // end handler
    IL_00ac:  leave      IL_00bd
  }  // end .try
  finally
  {
    IL_00b1:  ldloc.0
    IL_00b2:  call       instance class [ES5.Script.Core]ES5.Script.EcmaScript.Objects.GlobalObject [ES5.Script.Core]ES5.Script.EcmaScript.ExecutionContext::get_Global()
    IL_00b7:  call       instance void [ES5.Script.Core]ES5.Script.EcmaScript.Objects.GlobalObject::DecreaseFrame()
    IL_00bc:  endfinally
  }  // end handler
  IL_00bd:  ldloc.1
  IL_00be:  ret
} // end of method C::test
```

And running peverify on it says:

> [IL]: Error: [EC::test][offset 0x00000096] Branch out of try block.

**Comment by luboid** [comment]
My question is why this work in .Net Framework and not in .Net Core

I also have working example:
https://github.com/luboid/ES5.Script/tree/dotnet-core-2/TestConsole/test-cases/working

How you will comment documentation example:
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator.beginfinallyblock?view=netcore-2.0
which contains jump out of finally block - label myEndOfMethodLabel

**Comment by svick** [comment]
> My question is why this work in .Net Framework and not in .Net Core

My guess is that some time before the release of .Net Framework 4.7 and .Net Core 2.0, the CLR was changed to produce the exception on this code. (The code was always invalid, but CLR used to run it nevertheless.)

> How you will comment documentation example:
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator.beginfinallyblock?view=netcore-2.0
which contains jump out of finally block - label myEndOfMethodLabel

That code also throws for me on .Net Framework 4.7 and .Net Core 2.0, so I opened a docs issue about it: https://github.com/dotnet/docs/issues/3351.

> My VS 2017 do not allow to me set .Net 4.7

Have you tried installing .Net Framework 4.7 from the VS installer? (BTW, this is probably not about which .Net Framework you target in VS, it's about which .Net Framework ends up actually running the code.)

**Comment by luboid** [comment]
But this is braking change and here is not mentioned

https://support.microsoft.com/en-us/help/4015088/known-issues-in-the-net-framework-4-7

Installer says:

![image](https://user-images.githubusercontent.com/383517/31311690-6ae5c8a6-abba-11e7-9a2f-09d477409afe.png)

![image](https://user-images.githubusercontent.com/383517/31311693-78932890-abba-11e7-9eaa-abd32621daa1.png)

![image](https://user-images.githubusercontent.com/383517/31311778-1ead7de2-abbc-11e7-8efb-3c9f422e4cc5.png)

I try to set it up in app.config but with no success, is still working :) 
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7"/>
  </startup>
</configuration>
```

**Comment by svick** [comment]
Ok, my guess was wrong. The difference is not .Net Framework 4.7 vs. older frameworks, it's x64 vs. x86.

On .Net Framework 4.7, the problematic code throws an exception when run as 64-bit process, but runs fine as 32-bit process.

**Comment by mikedn** [comment]
The relevant JIT code doesn't appear to have changed since it was open sourced. In fact, the relevant code exists even in the legacy JIT32 that the x86 version of .NET Framework uses. What seems to be different is when the code is run. It looks like the IL checking code is always run if verification is enabled and that means that your code will likely fail even on x86 in some cases.

In any case, bad IL is bad IL. If verification is enabled bad IL should always be rejected and if it's not then there's a bug in the JIT. However, if verification is not enabled then the JIT basically exhibits "undefined behavior" when encountering bad IL. What exactly happens depends on the used JIT and its version. Intentional or unintentional changes in the JIT's undefined behavior are unlikely to be documented in "known issues" documents.

**Comment by luboid** [comment]
Ok, thanks. 
But we don't need to bang our heads in the wall, JIT or not JIT, runtime need to be same, whatever

**Comment by danmosemsft** [comment]
@luboid I think this can be closed now?

**Comment by luboid** [comment]
Yes
