### ISSUE TITLE
[Infrastructure/Windows] Native coreclr build spawns cl instances up to square of processor/core number and consumes 14 GB on 8 core box

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#14406]
Not sure that it is the right repo to post issue. If not please advise and I will move it.

Testing source-build I have noticed that on my notebook with 16 GB of RAM and 4 core / 8 thread processor MSBuild spawns total of 8 MSBuild nodes and each node may spawn in turn 8 compiling MSVC cl.exe processess. Compilers are starved and utilize on average 1 - 2 % of CPU time each and momory consumption varies from 50 MB up to 500 MB for each cl instance. Memory consumption of MSBuild process tree grows up to 14 GB - maximum from 3 runs.

In contrast to that situation build on linux (Ubuntu 14.04 and 16.04) and macOS consumes 1 - 2 GB, spawns 8 clang processes, each process uses roughly 12 - 15 % of processor time and memory usage ranges from 50 to maximum 200 MB. Build seems to be significantly faster as well but since I can not compare build times directly (my Mac box has significantly different specs than Windows one on which I use linux VM/WSL) I would consider this judgment to be not very precise.

This problem seems to be common to many different projects relying on CMake generating Visual Studio projects i.e. LLVM/Clang suffers from the very same issue. Therefore imho it could be helpful to change MSBuild configuration for native coreclr build to use single node instead of multiple nodes each for one virtual processor present in the machine.  

Situations seems to have improved with regard to memory consumption in last couple of weeks for master branch  but it still is highly inefficient in release/2.0.0 branch. Anyway having 64 compilers running in parallel on 8 cores wastes a lot of resources and time for synchronisation and context switching.

**Comment by mikedn** [comment]
Yeah, that's a case of double parallelization - both MSBuild and CL have their parallelization capabilities turned on. But AFAIR I once tried to fix this and it made the build a bit slower so I gave up. The main problem is that it can make the machine unusable for a while...

**Comment by 4creators** [comment]
@mikedn 
This is why I am raising this issue. I work on Windows laptop with 16 GB of RAM and 4 cores / 8 threads - I have to quit all programs to avoid paging and OOM exceptions ...  
Do you know where I could change MSBuild to use 1 node instead of multiple nodes for native build. I think this would fix this issue as MSBuild will stop multiplying cl instances.

**Comment by 4creators** [comment]
@weshaggard @wtgodbe Can you help by guiding me what can be fixed? I can provide PR to get it done.

**Comment by mikedn** [comment]
You could probably start with tweaking `/maxcpucount` in config.json
https://github.com/dotnet/coreclr/blob/ea23b794eaa7f5bf595da55e2ff5ea6025a1c772/config.json#L678-L683
but it's not clear how that can be exposed as a `build.cmd` parameter.
