### ISSUE TITLE
VectorTest.CheckValue<T> uses unsupported format

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#14400]
`VectorTest.CheckValue<T>(T value, T expectedValue)` is using format `X` for `T` Single/Double

```
Console.WriteLine("CheckValue failed for type " + typeof(T).ToString() + ". Expected: {0} (0x{0:X}), Got: {1} (0x{1:X})", expectedValue, value)
```

This is not currently supported by `src/classlibnative/bcltype/number.cpp`  and results in an exception making it difficult to understand initial failure.

**Comment by sdmaclea** [comment]
@jkotas FYI

**Comment by RussKeldorph** [comment]
@CarolEidt
