### ISSUE TITLE
System.Numerics.Vector<T>.Count for platform without AVX

### ISSUE THREAD

**Issue by ANDREENKOS** [dotnet/coreclr#1441]
In Debug mode without AVX RyuJit generate call to Vector<T>.Count, which throw exception because IsHardwareAccelerated returns true.

**Comment by akoeplinger** [comment]
I think this was fixed yesterday by https://github.com/dotnet/corefx/pull/2971

**Comment by ANDREENKOS** [comment]
I think it wasn't.
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_windows_debug_prtest/1836/testReport/

**Comment by mellinoe** [comment]
You will need to update the test project to use the newest version of the NuGet package, which should be available. I published it individually yesterday. The version is 4.1.1-beta-23226.
