### ISSUE TITLE
ASPNET CORE 2.0 AND WCF: Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0

### ISSUE THREAD

**Issue by isegos** [dotnet/coreclr#14410]
Hello.
I make .Net Core 2.0 application with net standart 2.0. I created WCF application with framework 4.7 and hoated it into Windows Servive by net.tcp. WCF app works fine for console and winforms app. But I can't connect netcore app to wcf.
WCF server and client works without app.config.

When I connect to WCF by WinForm app I use this:

```
IChat chat = null;
ChannelFactory<IChat>` channelFactory = null;
EndpointAddress ep = new EndpointAddress("net.tcp://{server}:{port}/Chat/");
NetTcpBinding tcpb = new NetTcpBinding();

channelFactory = new ChannelFactory<IChat>(tcpb); // !!!!!!!!!!!!
chat = channelFactory.CreateChannel(ep);
```

But, at my netcore app I can't do it. I must write:
`channelFactory = new ChannelFactory<IChat>(tcpb, ep); // !!!!!!!!!!!`

I get next error: 
`System.InvalidOperationException: An error occurred while loading attribute 'ServiceContractAttribute' on type 'IChat'.  Please see InnerException for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.`

How can I fix it? Please, help.

**Comment by jkotas** [comment]
This issue was moved to dotnet/wcf#2337
