### ISSUE TITLE
Debuggers can no longer func-eval Assembly.Load() in .NET Core 2.0, but can in 1.x and .NET Framework

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/coreclr#14416]
It's no longer possible for a debugger to func-eval `Assembly.Load(string)`. An exception is thrown. It was possible in .NET Core 1.x and is possible in .NET Framework.

Repro:

- Create a .NET Core 1.x console app and a .NET Core 2.0 console app
- Debug both with Visual Studio
- Enter the following expression in the watch window `System.Reflection.Assembly.Load("System.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")`

Result:
.NET Core 1.x: works as expected

.NET Core 2.0: fails with the following exception:

```
'Assembly.Load("System.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")' threw an exception of type 'System.ArgumentException'
...
		Message	"Cannot evaluate a security function."	string
...
```

There are many reasons a debugger would want to call `Assembly.Load`:

- User entered an expression in the watch window
- A conditional BP requires Assembly.Load to be called
- The debugger requires an assembly to be loaded that hasn't been loaded yet, eg. to expand the Results View (requires System.Linq / System.Core)

**Comment by jkotas** [comment]
Thank you for reporting this bug. It is fixed in the live master, and the fix is also going to be included in .NET Core 2.0.3 update (https://github.com/dotnet/coreclr/pull/13780).
