### ISSUE TITLE
Debugger step-in on methods that are running Tier1 code don't have the correct STEP_CALL stop reason

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#14428]
I didn't actually repro this, but I assume you would repro it by:

1) Run some method Foo many times until tiered compilation recompiles it as a Tier1 method
2) Use a debugger to step in to a call to Foo
3) Check the stop reason provided in ICorDebugManagedCallback::StepComplete

It should be STEP_CALL, but presumably it won't be because of the bug here:
https://github.com/dotnet/coreclr/blob/master/src/debug/ee/controller.cpp#L5585
This code is trying to recognize when we stopped at offset zero in a method, but GetFunctionAddress refers to the address in the default compilation of the method, not the tier1 version of the method.

**Comment by davmason** [comment]
LGTM
