### ISSUE TITLE
current status for 32 bit Linux support

### ISSUE THREAD

**Issue by philippweidhas** [dotnet/coreclr#14431]
Hi im actually looking for a possibility to run .Net Core on 32 Bit Linux. Could someone how is more into that project give me a short Answer how realistic the chances are to get it working with the current status? I would like to understand how far this support has come with the done efforts. 
Greetings  from Germany Philipp

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/issues/9265 

There are no prebuilt binaries available, but it should generally work if you build it yourself.
