### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80131500 on Linux Docker container

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/coreclr#14444]
@Parth6288 commented on [Wed Aug 30 2017](https://github.com/dotnet/core/issues/918)

Hi,

Developing the app on Windows, it runs fine on Windows. When trying to run the published release build on CentOS7, it works fine. However running it on Linux container, it throws this error:Failed to initialize CoreCLR, HRESULT: 0x80131500

Creation of a new app inside the container and running it works, but I want to build on Windows and host on Linux container.

Dotnet info:
Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/
--- End breadcrumb write 0

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Any Ideas?

---

@omajid commented on [Thu Aug 31 2017](https://github.com/dotnet/core/issues/918#issuecomment-326284000)

Can you install `strace` in your container and run `strace` on `dotnet`? If your original command is:

     dotnet /path/to/dll

The strace version becomes

    strace -o logfile dotnet /path/to/dll

And please upload `logfile` from the container to somewhere public.

---

@Parth6288 commented on [Thu Aug 31 2017](https://github.com/dotnet/core/issues/918#issuecomment-326493830)

Attached is the log file.

[dotnetstracelog.txt](https://github.com/dotnet/core/files/1269238/dotnetstracelog.txt)

---

@Petermarcu commented on [Fri Oct 06 2017](https://github.com/dotnet/core/issues/918#issuecomment-334913090)

@janvorli looks like there is a lot of probing for System.Globalization.Native.so. Any thoughts?

**Comment by steve-todorov** [comment]
We are also having the same issue in an OpenSUSE docker image we created for testing purposes.  Is there any progress or timeline on this?

**Comment by janvorli** [comment]
I am sorry, I've missed the issue when it was created. The problem I can see in the log is that System.Globalization.Native.so is trying to load ICU libraries version 50 only while it is supposed to scan for supported versions. That is pretty strange and it looks as if the /root/publishcentos/System.Globalization.Native.so was actually from some old pre-2.0.0 version of .NET core. 
To see if that's the case, run `ldd /root/publishcentos/System.Globalization.Native.so`. If you see libicuuc.so.50 in the listed dependencies, then it is the case.
@steve-todorov, as for your case, could you please also capture the strace output and shared it e.g. via gist? I'd take a look.

**Comment by steve-todorov** [comment]
@janvorli sure, I've created a gist with a `strace.log` and also the `Dockerfile` we're using to build the docker image. Hope that helps. Let me know if you need anything more.

**Comment by janvorli** [comment]
@steve-todorov thanks for the trace and dockerfile, it reveals the problem. You are installing ICU package that is not usable by dotnet core. The minimum version that can work with our stuff is version 50.1, you are installing version 42.1. Please note that the version has nothing to do with suse version, it is just a coincidence.
In dotnet version 1.0.3, the ICU version is fixed to the version of standard ICU package available for your platform. In your case, for SUSE 42.1 it is ICU 52.1. "zypper install icu" or better for smaller image just "zypper install libicu52_1" will install the right version.
In dotnet 2.0 and later, we are no longer bound to a fixed version, but the minimal version of 50.1 remains.

**Comment by steve-todorov** [comment]
@janvorli thank you very much for looking into this! I confirm that after I installed the `libicu52_1` package everything seems to be working properly now. Thanks!

**Comment by janvorli** [comment]
@steve-todorov you're welcome.

**Comment by RussKeldorph** [comment]
Please re-open if not resolved.
