### ISSUE TITLE
[x86] undefined symbol: _ZN13StubLinkerCPU25X86EmitCurrentThreadFetchE6X86Reg

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#14453]
After #14398 PR `corerun` failed with:
```
dlopen failed to open the libcoreclr.so with error libcoreclr.so: undefined symbol: _ZN13StubLinkerCPU25X86EmitCurrentThreadFetchE6X86Reg
```
cross build x86 on 64-bit is used.
Method `StubLinkerCPU::X86EmitCurrentThreadFetch(X86Reg dstreg)` at https://github.com/dotnet/coreclr/blob/master/src/vm/i386/stublinkerx86.cpp#L2363 is guarded by statement:
#if !defined(FEATURE_STUBS_AS_IL)
``
but it used in code where `FEATURE_STUBS_AS_IL` is defined.
@jkotas it looks there is need two implementation: with enabled `FEATURE_STUBS_AS_IL` and not.

**Comment by jkotas** [comment]
Sorry about that. I have submitted PR to add the code for this back.

**Comment by alpencolt** [comment]
@jkotas thank you!
Not a problem, I've tried to fix it but didn't found information about this `FEATURE_STUBS_AS_IL` so asked you to help.
