### ISSUE TITLE
Official Build: download blobs silently fails

### ISSUE THREAD

**Issue by chcosta** [dotnet/coreclr#14454]
Recent builds failed because the "sync -ab" step in VSTS silently failed to download blobs and this led to a later failure when the build (test) attempted to gather the payload for submission to Azure.

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1056129

I'm not proposing the best way to fix this, but one possibility (that would make it clearer what occurred when this type of failure happens), is to update https://github.com/dotnet/coreclr/blob/master/src/syncAzure.proj#L21 to validate that blobs were downloaded , rather than waiting for a subsequent step to error out.

/cc @wtgodbe

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/14457 should resolve

**Comment by wtgodbe** [comment]
I can also put up a PR later to validate download in sync

**Comment by RussKeldorph** [comment]
I assume this should have been closed when #14457 was merged.  Please re-open if not.
