### ISSUE TITLE
JIT: generalize unbox.any to look at other sources of type info

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#14473]
`unbox.any` gets optimized if it is immediately preceded by a `box` to the same type. We ought to be able to check for other sources of type information and perhaps do similar optimizations.

Effectively we'd call `gtGetClassHandle` on the input operand and if we had an exact result we'd be able to remove the type test and manifest the unbox as a copy.

category:cq
theme:importer
skill-level:expert
cost:small

**Comment by AndyAyersMS** [comment]
Considering for 2.1

**Comment by AndyAyersMS** [comment]
Initial part of changes to detect when a type is known to an unbox: [master...AndyAyersMS:UnboxAny](https://github.com/dotnet/coreclr/compare/master...AndyAyersMS:UnboxAny). Note the simple cases where we have box-unbox directly in one method are already handled by an existing importer peephole optimization.

jit-diffs shows 26 hits in the FX assemblies. These are cases where inlining has exposed a box-unbox chain. For instance, in the `ObjectEqualtyComparer`s `LastIndexOf` instantiated for `int32` we one such instance after inlining `Int32.Equals(ref)`.

In this case we could remove the type tests guarding the unbox but would not be able to undo the box. Callee IL is
```
IL_0000  03                ldarg.1     
IL_0001  75 df 00 00 02    isinst       0x20000DF
IL_0006  2d 02             brtrue.s     2 (IL_000a)
IL_0008  16                ldc.i4.0    
IL_0009  2a                ret         
IL_000a  02                ldarg.0     
IL_000b  4a                ldind.i4    
IL_000c  03                ldarg.1     
IL_000d  a5 df 00 00 02    unbox.any    0x20000DF
IL_0012  fe 01             ceq         
IL_0014  2a                ret         
```
and the caller's box is passed via a temp since it is multi-use. 

So probably this should wait until we can "forward" boxes into callee IL and sort out the multi-use box optimization capabilities as in #14472.

**Comment by mikedn** [comment]
> For instance, in the ObjectEqualtyComparers LastIndexOf instantiated for int32 we one such instance after inlining Int32.Equals(ref).

Hmm, I ran into some unboxes in `ObjectEqualtyComparers` myself when trying something in VN. I'm not sure if they're the same but in any case, there are some unboxes that can be removed by assigning a proper VN to a `GT_IND` that dereferences an ref that was previously allocated using new/box. For `LastIndexOf` I see the following diff:
```diff
--- D:\Projects\diffs\dasmset_4\base\System.Private.CoreLib.dasm	2018-01-23 20:24:23.000000000 +-0200
+++ D:\Projects\diffs\dasmset_4\diff\System.Private.CoreLib.dasm	2018-01-23 20:24:22.000000000 +-0200
@@ -1376350,13 +1376328,5 @@
        call     CORINFO_HELP_NEWSFAST
-       lea      r15, bword ptr [rsi+8*r15+16]
+       lea      rdx, bword ptr [rsi+8*r15+16]
        mov      qword ptr [rax+8], rdi
-       mov      r12, rax
-       lea      rdx, [(reloc)]
-       cmp      qword ptr [r12], rdx
-       je       SHORT G_M38409_IG04
-       mov      rdx, r12
-       lea      rcx, [(reloc)]
-       call     CORINFO_HELP_UNBOX
-G_M38409_IG04:
-       mov      rax, qword ptr [r12+8]
-       cmp      rax, qword ptr [r15]
+       mov      rax, qword ptr [rax+8]
+       cmp      rax, qword ptr [rdx]
```

**Comment by AndyAyersMS** [comment]
Moving this to future too, as it depends on the multi-use box work.

**Comment by AndyAyersMS** [comment]
There are some cases of this that don't depend on multi use boxes. Here's a fairly common example (cf dotnet/coreclr#33970):
```c#
// current
public override bool Equals(object value) => value is Index && _value == ((Index)value)._value;
// proposed improvement
public override bool Equals(object value) =>  value is Index index && _value == index._value;
```
IL for this second case is:
```
ldarg.1     
dup         
stloc.1     
isinst       0x2000002
brfalse.s    FAIL
ldloc.1     
unbox.any    0x2000002
stloc.0     
ldarg.0     
ldfld        0x4000001
ldloc.0     
ldfld        0x4000001
ceq         
ret         
FAIL:
ldc.i4.0    
ret         
```
For a value class like `Index` both these implementations require two type tests at runtime: one for the `isinst` and one for the `unbox.any`. The jit is currently unable to propagate the type information from the `isinst` test down to the `unbox.any` and so emits redundant tests (one of them in the unbox helper):
```asm
G_M27175_IG01:
       push     rdi
       push     rsi
       sub      rsp, 40
       mov      rsi, rcx

G_M27175_IG02:
       mov      rdi, rdx
       mov      rdx, rdi
       test     rdi, rdi
       je       SHORT G_M27175_IG03
       mov      rcx, 0xD1FFAB1E
       cmp      qword ptr [rdi], rcx
       je       SHORT G_M27175_IG03
       xor      rdx, rdx

G_M27175_IG03:
       test     rdx, rdx
       je       SHORT G_M27175_IG06
       mov      rdx, 0xD1FFAB1E
       cmp      qword ptr [rdi], rdx
       je       SHORT G_M27175_IG04
       mov      rdx, rdi
       mov      rcx, 0xD1FFAB1E
       call     CORINFO_HELP_UNBOX

G_M27175_IG04:
       mov      eax, dword ptr [rdi+8]
       cmp      dword ptr [rsi], eax
       sete     al
       movzx    rax, al

G_M27175_IG05:
       add      rsp, 40
       pop      rsi
       pop      rdi
       ret      

G_M27175_IG06:
       xor      eax, eax

G_M27175_IG07:
       add      rsp, 40
       pop      rsi
       pop      rdi
       ret      
```
The optimization can't be done in the importer as the value produced by isinst is not used. Subsequent flow-sensitive optimizations passes like assertion prop can't recognize the inline type tests.

A small change to the IL and then an implementation of the jit optimization noted above would allow for the second type test to be optimized away. 
```
/// altered IL
ldarg.1     
isinst       0x2000002
dup     
stloc.1
brfalse.s    FAIL
ldloc.1     
unbox.any    0x2000002
stloc.0     
ldarg.0     
ldfld        0x4000001
ldloc.0     
ldfld        0x4000001
ceq         
ret         

FAIL:

ldc.i4.0    
ret         
```
With a prototype jit opt, there is still a bit of redundant testing but only one type test and no residual helper call (hence the method becomes a leaf and we can streamline prolog/epilog too):
```asm
G_M27214_IG01:
       0F1F440000           nop

G_M27214_IG02:
       488BC2               mov      rax, rdx
       4885C0               test     rax, rax
       7411                 je       SHORT G_M27214_IG03
       48BA68240222FD7F0000 mov      rdx, 0x7FFD22022468
       483910               cmp      qword ptr [rax], rdx
       7402                 je       SHORT G_M27214_IG03
       33C0                 xor      rax, rax

G_M27214_IG03:
       4885C0               test     rax, rax
       740C                 je       SHORT G_M27214_IG05
       8B4008               mov      eax, dword ptr [rax+8]
       3901                 cmp      dword ptr [rcx], eax
       0F94C0               sete     al
       0FB6C0               movzx    rax, al

G_M27214_IG04:
       C3                   ret

G_M27214_IG05:
       33C0                 xor      eax, eax

G_M27214_IG06:
       C3                   ret
```
@gafter this is the kind of thing I was mentioning the other day -- I didn't implement this jit opt when I first thought of it because it wasn't (and still isn't) a common IL pattern. But it could and arguably should be...
