### ISSUE TITLE
ReadyToRun Dump, How to?

### ISSUE THREAD

**Issue by johndevsys** [dotnet/coreclr#1447]
Hello,

can someone point me on how to dump ReadyToRun functions, headers and other info from a binary file. In other words is there a straightforward way to give an .exe file as input and get the dump as output.

Thanks
-John

**Comment by jkotas** [comment]
We have not done the work to open source the native image dump utility yet. Some of the code is there, but it is not complete.

For now, you can get dump the code as it is being generated (in debug builds):

set COMPlus_NGenDisasm=*
crossgen /readytorun hello.exe

**Comment by johndevsys** [comment]
Thanks for replying.

There is no dump from the above commands. The exact commands I am using are :
set COMPlus_NGenDisasm=*
.\crossgen.exe /App_Paths .\TestHello /Platform_Assemblies_Paths Framework  /Platform_Winmd_Paths Framework /ReadyToRun /MissingDependenciesOK /in TestHello\c.exe /out TestHello\c.Triton.exe

the output is (the same as without the set command) : 
Microsoft (R) CoreCLR Native Image Generator - Version 4.6.23015.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image TestHello\c.Triton.exe generated successfully.

**Comment by jkotas** [comment]
It looks like you are running release build of CoreCLR.

COMPlus_NGenDisasm switch works on debug build of CoreCLR only. You have to build the debug CoreCLR yourself from the git repo - it will be at bin\Product\Windows_NT.x64.Debug.

The nuget packages are not available for debug build only today.
