### ISSUE TITLE
[Question] Native Image and PDB

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#14485]
When I run this code with pdb file:

```cs
class Program
{
    static void Main(string[] args)
    {
        throw new Exception("EXCEPTION MESSAGE");
    }
}
```

Before crossgen

```
Unhandled Exception: System.Exception: EXCEPTION MESSAGE
   at excep.Program.Main(String[] args) in /work/nfs/dotnet/temp/excep/Program.cs:line 9
```

After crossgen

```
Unhandled Exception: System.Exception: EXCEPTION MESSAGE
   at excep.Program.Main(String[] args)
```

I found out that if I run with `a.ni.dll` file the runtime looks for `a.ni.pdb`. However even if I change the filename from `a.pdb` to `a.ni.pdb`, source file and line number is still not shown because the pdb file and dll's GUID does not match. I also found `/CreatePDB` option from `crossgen` so I assumed there may be another PDB format for NI. 

So my questions are:

1. How are `ni.pdb` and `pdb` different? When I comment out GUID check part(in CoreFX `PEReader.cs`) it works at least for the above example.
2. Why `/CreatePDB` is only supported for Windows? There is several compile errors when I undefine `NO_NGENPDB`.

**Comment by mikedn** [comment]
The `.ni.pdb` contains information about the native code generated by crossgen. PDB files are generated using Windows specific libraries, crossgen itself does not know how to write a PDB file.

**Comment by wateret** [comment]
@mikedn Thank you. So is it like `.ni.pdb` equals to `.pdb` + "native code info" ?
What I'd like to do is just showing source file name and line number when printing stack trace while running some `.ni.dll`.

**Comment by jkotas** [comment]
You should not need `.ni.pdb` for this to work. `.ni.pdb` is only needed by tools on Windows that can only work with unmanaged pdbs, like stack sampling profilers.

> I found out that if I run with `a.ni.dll` file

Does it work if you rename this file to `a.dll`? (ie replace the original IL file with the crossgened file)

We have stopped using the .ni.dll suffix for the crossgen images in the shipping configs. We just use the .dll suffix for them. This saves every tool and piece of code out there that does probing for IL .dlls to also probe for NI .dlls.

**Comment by wateret** [comment]
@jkotas I tried that(renaming `.ni.dll` to `.dll`), but I get `BadImageFormatException`. Similar to #13776.

And I think it would fail using data of `.pdb` file even if it was loaded. Since GUIDs do not match. The code for that is here. https://github.com/dotnet/corefx/blob/5f083c7ac0d8ab35f48e7ff9176e05af894c4562/src/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs#L789-L792

**Comment by wateret** [comment]
FYI I'm talking about fragile-non-versionable images. It is still strange that the NI image was generated by the exactly same runtime.

**Comment by jkotas** [comment]
These look like bugs in handling of fragile-non-versionable images.

Still, `/CreatePDB` option is not needed to make the managed exception stacktraces to be printed.

**Comment by chunseoklee** [comment]
@jkotas You mean that line number printing is possible with ni image and pdb(from non-ni dll) ? Thus, it seems like a bug ?

**Comment by jkotas** [comment]
Right.

**Comment by wateret** [comment]
Source and line number info is not shown with R2R too. I meant that `BadImageFormatException` issue was only for fragile non-versionable images.

**Comment by wateret** [comment]
Should PDB GUID for dll file and its crossgened file be the same? Currently the crossgened file(`.ni.dll`)'s PDB GUID is different.

**Comment by jkotas** [comment]
R2R images should have two PDB records - one with the original IL PDB guid and one with the native PDB guid. The IL PDB record is copied over by `ZapImage::CopyDebugDirEntry`. The stack trace formatter should pick up the IL PDB record.

**Comment by mikedn** [comment]
> You mean that line number printing is possible with ni image and pdb(from non-ni dll) ? Thus, it seems like a bug ?

Where is the native code offset to IL offset mapping stored? In the .ni image itself?

**Comment by wateret** [comment]
@joktas Thank you. I checked two different RSDS records exist.

**Comment by jkotas** [comment]
> Where is the native code offset to IL offset mapping stored? In the .ni image itself?

Right. `READYTORUN_SECTION_DEBUG_INFO`

**Comment by wateret** [comment]
@jkotas @mikedn I was using the older version of CoreCLR. And it seems like this (065a5216c1d16ff519bf18c5b559c8eda276f580) resolves what I'm asking. Sorry about that.
