### ISSUE TITLE
Create OverridePackageSource property and use it for build-from-packages source

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#14525]
Currently the intermediate location is added as a restore source directly:

https://github.com/dotnet/coreclr/blob/a78940216170cdf5f9b97ccbf6edaca2ac0758c9/tests/dir.props#L92

CoreFX has a [`OverridePackageSource`](https://github.com/dotnet/corefx/blob/71761de5f8deb0c332f62622f71f94f27252c624/dir.props#L73) property that's used when an override is needed, and it would be nice to use this approach rather than hardcoding the source in `tests/dir.props`.

(With the Repo API, CoreFX's `OverridePackageSource` looks like [this](https://github.com/dotnet/corefx/blob/dfda60fb5bd3e538df4102354a4a7b68074b5a44/dir.props#L68).)

Brought up in https://github.com/dotnet/coreclr/pull/14518#discussion_r144936737

**Comment by jashook** [comment]
@dagood is this required for 2.1?

**Comment by dagood** [comment]
@weshaggard fixed this in https://github.com/dotnet/coreclr/pull/14683, so it's actually already in 2.1. (It was just cleanup.)
