### ISSUE TITLE
Unboxing failures should report target and actual types

### ISSUE THREAD

**Issue by jskeet** [dotnet/coreclr#1453]
Consider this code:

```csharp
public class Test {
    public static void Main() {
        object x = new object();
        string y = (string) x;
    }
}
```

That produces a nice informative error:

> System.InvalidCastException: Unable to cast object of type 'System.Object' to type 'System.String'.

Change the `string y = (string) x;` to `int y = (int) x;` and we get:

> System.InvalidCastException: Specified cast is not valid.

This is far less useful. As an example of when this is a pain, consider calling `SqlCommand.ExecuteScalar`... if you're not entirely sure (before trying) what type is going to be used for the result (you may know it's an integer type, but not which) it's annoying to have to use a local variable to report the actual type in a log or debug session before the cast. If the exception just provided the same information that it does for a reference cast, it would streamline development.

**Comment by omariom** [comment]
:+1:
