### ISSUE TITLE
System.Text.RegularExpressions, How to?

### ISSUE THREAD

**Issue by thangchung** [dotnet/coreclr#1454]
I tried to use Regex.Matches function in .NET 4.6, but when I built the solution, it always threw an exception like this

`Error CS0234	The type or namespace name 'RegularExpressions' does not exist in the namespace 'System.Text' (are you missing an assembly reference?) GraphQL4Net.DNX Core 5.0 graphql4net\src\GraphQL4Net\Language\Source.cs` 

I know that CoreCLR did a lot of changes. I have read a bunch of code in coreclr project, but not quite understand too much. So could anyone tell me, how can I fix it?

**Comment by stephentoub** [comment]
Try including System.Text.RegularExpressions in your project.json file. The regex functionality is a separate library now.

**Comment by mellinoe** [comment]
If you are using .NET 4.6, you should be able to reference Regex types by just importing the namespace. The Regex types on Desktop are in System.dll, which is referenced by default. However, you also mentioned CoreCLR, so if you are trying to build a .NET Core project, then you will need to do as Stephen mentioned and add the System.Text.RegularExpressions NuGet package.

**Comment by thangchung** [comment]
Thanks @stephentoub  & @mellinoe for your help. It's really working. But one more thing I am still concerning. If I put `dotnet` tag inside `framework` tag (`project.json` file), then it worked, but if I put `dnx451` & `dnxcore50` like many samples on internet, then it always threw the exception. What's correct way to go with?

It worked
`
"frameworks": {
    "dotnet": {
    }
  }
`
It did not work
`
"frameworks": {
    "dnx451": {
    },
    "dnxcore50": {
    }
  }
`

**Comment by teyc** [comment]
`dnx451` should have worked without declaring any dependencies. On `dnxcore50` your project json  should have at least dependency on System.Text.RegularExpressions
```
    "dnx451": {  },
    "dnxcore50": {
      "dependencies": {
        "System.Text.RegularExpressions": "4.0.0-beta-*",
     }
   }
```

Then, to build for `dnx451` do the following
```
$ dnvm use 1.0.0-beta8-15564 -r mono
$ dnu restore
$ dnu build --framework dnx451
```

And to build for `dnxcore50`
```
$ dnvm use 1.0.0-beta8-15564 -r coreclr
$ dnu restore
$ dnu build --framework dnxcore50
```

**Comment by tzwlai** [comment]
Closing this since it looks like the problem has been resolved.  Please feel free to reopen if needed.
