### ISSUE TITLE
[Infrastructure/Windows] Review usage of VsDevCmd. bat script in build and run scripts

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#14540]
Code review for PR #14515 led to conclusion that usage of VsDevCmd.bat script in build.cmd and run.cmd needs further review as in some places it may be not required. This issue is created to track work on this problem.

**Comment by weshaggard** [comment]
Thanks @4creators for helping improve our build infrastructure.

**Comment by 4creators** [comment]
Fixed with #14515
