### ISSUE TITLE
[Infrastructure/Windows] Free -ExtraParameters command line option in run.cmd script for use by invokers

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#14543]
The issue was created by PR #14509. See coment by @BruceForstall https://github.com/dotnet/coreclr/pull/14509#issuecomment-337323436.

Currently passing -ExtraParameters option to script will result in error:

```bash
Error: Parameter ExtraParameters specified more than once.
```

**Comment by weshaggard** [comment]
I suspect the best way is to figure out how to make CMake automatically include a common props files when it generates the projects.

**Comment by 4creators** [comment]
@weshaggard  Will research this and thnx for suggestions. Pls assign me to this issue as well.
