### ISSUE TITLE
CoreCLR or CoreFX Build fails with No CMAKE_C_COMPILER CMAKE_CXX_COMPILER could be found

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#14552]
This is me, simply documenting something that took me way to long to debug, and I want to give others a fighting chance of debugging it.

My scenario is simple: I reinstall a new Win 10 OS, install Visual Studio 2017 install, CMake and Git and Python as the instructions tell me to and try to build CoreCLR.  

It fails with the text below complaining about that fact that it cannot find the C and C++ compiler.  (Very obscure).   

First: what is going on?   CMAKE is a build system that we use to build native components.  It is roughly the same as MSBUILD.    However being cross platform it goes to some trouble to detect what C and C++ compiler it has available.  To do this  and determine important things about the compiler it compiles a small program.  IF THIS COMPILATION FAILS THE RESULT IS THE FAILURE BELOW.   

You can see the exact compilation failure by looking at the CMakeError.log file that it indicates.  In my case what was happening was that the linker was failing because it could not find gdi32.lib.   

That in turns took some digging, but I found this very helpful link 
https://developercommunity.visualstudio.com/content/problem/41860/gdi32lib-missing.html

Basically the version of the windows SDK that VS 2017 uses (10.0.15063.0) was stripped of some libraries to save space, but the default VS link commands were not updated in VS2017, leading to the error.   The solution I chose was to follow the guidance give in the link above to go back into the VS2017 installer, and explicitly add back in that you want VS to install the 10.0.15063.0 version of the SDK .  If you do that you get the 'full install' of the SDK and Link no longer fails and everything start to work.

Hopefully you will never need these instructions, but if you do hopefully a search might find these useful instructions. 

```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.4.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'
Commencing build of native components

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:28 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:28 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "C:/Users/vancem/Source/Repos/corefx-vancem/bin/obj/Windows_NT.x64.Debug/native/CMakeFiles/CMakeOutput.log".
See also "C:/Users/vancem/Source/Repos/corefx-vancem/bin/obj/Windows_NT.x64.Debug/native/CMakeFiles/CMakeError.log".
Failed to generate native component build project!
```

**Comment by vancem** [comment]
I have listed the fix in the initial issue.  I created the issue just to allow others to find this work-around.

**Comment by chcosta** [comment]
You just saved me a lot of time.  Thanks!

**Comment by Drawaes** [comment]
I suddenly have this same error compiling corefx but with MSVCRTD.lib missing. This was after updating VS2019 and VS2017 to the latest. Previous to that I could build. I have all the Windows SDK's installed I can. Any ideas here?

**Comment by Drawaes** [comment]
Turns out it seemed that VS2019 took priority and if I run it from an explicit 2017 command prompt it now works.
