### ISSUE TITLE
[Win][Build]C4819: Non-ASCII character in source

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/coreclr#14556]
Position: `src\classlibnative\bcltype\number.cpp` L289-294
Character: `∗`
Windows Version: 16299.19
Code Page: 936(Simplified Chinese)
Visual Studio Version: 15.4.0 (msvc 19.11.25547)

The characters are in comment, so can be safely removed anyway.
Quite strange about this issue, because the same issue was reported and fixed 2 years ago, and no longer reported. Doubting about VS2017/vc141.

_a better solution could be making msvc work with UTF8 without BOM_

**Comment by jkotas** [comment]
cc @mazong1123

**Comment by mazong1123** [comment]
@huoyaoyuan Thanks for reporting it.

It's interesting. Those comments are copied from the original paper. I guess my PDF reader interpreted the character `*` as Chinese character because my locale is Chinese.

I'd like to fix it soon.
