### ISSUE TITLE
Monitor fast path perf

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#14571]
Try to improve the monitor fast path code generation to get it to get closer to asm fast path perf by either force-inlining spin loops or moving spin loops to the slow path, such that the slow path call at the end is the only call.

- Depends on https://github.com/dotnet/coreclr/issues/13980

**Comment by jkotas** [comment]
GetThread is inlined after https://github.com/dotnet/coreclr/pull/14398

**Comment by kouvel** [comment]
Not likely to happen - nice to have but not necessary, makes sense to do but no data to substantiate
