### ISSUE TITLE
JIT:  Allow CALLEE_IS_FORCE_INLINE precedent over CALLEE_DOES_NOT_RETURN

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#14585]
Currently `CALLEE_DOES_NOT_RETURN` will take precedent over `CALLEE_IS_FORCE_INLINE` this can be undesirable as there is no way to get a non-returning method to then inline.

**Comment by RussKeldorph** [comment]
@AndyAyersMS @dotnet/jit-contrib
