### ISSUE TITLE
Add Facebook, Twitter, and XBoxLive leader board support to System.Exception

### ISSUE THREAD

**Issue by OtherCrashOverride** [dotnet/coreclr#1459]
Current exceptions are not very helpful in assisting the developer.  We should add social networking features to facilitate a better debugging experience.

**Comment by jasonwilliams200OK** [comment]
Aww.. Here, have a beer on me: :beer:

**Comment by omariom** [comment]
![](https://avatars2.githubusercontent.com/u/1781701)

**Comment by OtherCrashOverride** [comment]
There is also room now to put Google Ads in the exception messages.

**Comment by jasonwilliams200OK** [comment]
Don't forget about those instagals! :dancer:

**Comment by OtherCrashOverride** [comment]
If you guys were young and open to new things like me, you would understand how mindblowingly game changing this is! :+1:  :+1:  :+1:  :+1: 

We can now query StackOverflow when an exception happens and also include the top 10 suggestions in the exception!  Additionally, others that have the same exception can follow you to see if you come up with an answer.  Also!!!!111!!!!!1 We should include ILSPY in CoreCLR, so that you can get a decompiled listing of the code where the exception occurred

I am going to start prototyping this soon!!!! :100:  :100: :100:

**Comment by linquize** [comment]
coreclr is not a GUI program. I cannot imagine integrating such services.

**Comment by OtherCrashOverride** [comment]
>  I cannot imagine integrating such services.

i was skyping with others and we decided we are going to change ``System.Exception.Message`` to a new and improved JSON format.  This will make integration with the services and DNX easier.

**Comment by CrshOverride** [comment]
I'm so glad these suggestions are being made by the OTHER CrashOverride rather than myself...

**Comment by terrajobst** [comment]
![images](https://cloud.githubusercontent.com/assets/5169960/9564217/093c563a-4e54-11e5-8d85-b5b54130006b.jpg)

OK, point taken and your feedback is being discussed in https://github.com/dotnet/corefx/issues/1187.
