### ISSUE TITLE
ICustomMarshaler not supported in UWP/WinRT

### ISSUE THREAD

**Issue by Foda** [dotnet/coreclr#14599]
`UnmanagedType.CustomMarshaler `and `ICustomMarshaler ` are both [supported ](https://github.com/dotnet/coreclr/commit/e8c4f5499136e137fdb3e3c5fb798b2637b21996) by .Net Core 2.0/.Net Standard 2.0, but not supported in UWP/WinRT. I can't seem to find any documentation that lists specific  .Net Standard APIs not supported in UWP/WinRT, but I would think this isn't the only case. 

See [mtypes.h](https://github.com/dotnet/coreclr/blob/master/src/vm/mtypes.h) for a list of marshaling that's allowed.

For more information: I received an error "Custom marshalers are not supported", which led me [here](https://github.com/dotnet/coreclr/blob/44736b809edaacc39d9bab1d18e04067e3fdb13d/src/dlls/mscorrc/mscorrc.rc#L2058), which led me to the handling of this case for AppX processes [here](https://github.com/dotnet/coreclr/blob/52a816d3011f4d03b80b5940dc036b40d701f52d/src/vm/mlinfo.cpp#L2862)

I assume that this means that UWP/WinRT isn't actually .Net Standard 2.0 compliant? Or is there not a guarantee that all APIs are functional?

**Comment by tijoytom** [comment]
@russellhadley @luqunl

**Comment by zhuman** [comment]
The code pointed to that does the `IsAppXProcess` check also raises a larger question: does the CoreCLR differentiate between a Centennial (full-trust) process running from an AppX versus a UWP app-container process? It would appear not, which is a bit concerning. You should be able to take a CoreCLR full-trust desktop console app and deploy it in an AppX package without changing its behavior. This check indicates that you basically drop support for things like IDispatch in this mode. Maybe the answer to that would be that you should just always use the full desktop CLR for desktop console apps, even when you deploy them via AppX.

**Comment by jkotas** [comment]
> does the CoreCLR differentiate between a Centennial (full-trust) process running from an AppX versus a UWP app-container 

It does not. IsAppXProcess is going to return false in .NET Core apps running as Centennial.

**Comment by jkotas** [comment]
The differentiation happens in the host .exe that is used to launch the process. The UWP host used to run UWP apps sets the `STARTUP_APPX_APP_MODEL` flag that turns on the special UWP restrictions (https://github.com/dotnet/core-setup/blob/master/src/uwp/Host/UWPHost/UWPHost.cpp). The regular console `dotnet.exe` host does not set this flag.

**Comment by jkotas** [comment]
> Or is there not a guarantee that all APIs are functional?

Right. Work on progress to make these differences more discoverable: https://github.com/dotnet/corefx/issues/18405

**Comment by danmosemsft** [comment]
I'm going to close this as it seems answered. All .NET Standard API is available on UWP now and the vast majority of it will work as expected. There are some limitations due to the platform.

**Comment by zhuman** [comment]
I think there is still an open question of whether .NET Core should allow ICustomMarshaler on UWP or not. .NET Core appears to support it on non-UWP platforms. The conversation so far established that there may be functional differences with .NET 2.0 Standard APIs, but it's not clear what the reason is for blocking this particular API if that's intended (the other marshaler types blocked for UWP seem to make sense in that they specifically block some Win32-only functionality). Some people use this to do custom string marshaling for UTF8 strings, for example, which would still be relevant with UWP apps using open-source C/C++ libraries.

**Comment by aybe** [comment]
How is one supposed to alleviate these non-supported calls then, rewrite perfectly working code just for UWP ?

You could have at least updated your docs, or provided an example for an alternative way.
