### ISSUE TITLE
[RyuJIT/arm32][JitStressRegs=8] Assertion failed 'refPosition->isFixedRegRef || (refPosition->nextRefPosition != nullptr && refPosition->nextRefPosition->isFixedRegRef)'

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#14624]
There are a number of these failures in arm altjit jitstressregs=8, due to my refactoring checkin.

**Comment by BruceForstall** [comment]
Looks like basically all tests fail now with jitstressregs8:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstressregs8_prtest/7/consoleText

**Comment by CarolEidt** [comment]
This (at least the first few that I checked) were actually asserting in the x86 compilation.
