### ISSUE TITLE
[Arm64] Tests still failing on tip

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#14626]
```
baseservices/threading/monitor/enter/monitorenter/monitorenter.sh
JIT/jit64/hfa/main/testC/hfa_sd0C_d/hfa_sd0C_d.sh
JIT/jit64/hfa/main/testC/hfa_sd0C_r/hfa_sd0C_r.sh
JIT/jit64/hfa/main/testC/hfa_sd1C_d/hfa_sd1C_d.sh
JIT/jit64/hfa/main/testC/hfa_sd1C_r/hfa_sd1C_r.sh
JIT/Methodical/Arrays/huge/_il_relhuge_struct/_il_relhuge_struct.sh
JIT/Methodical/VT/port/_il_relhuge_gcref/_il_relhuge_gcref.sh
```

Tests are failing with SEG Fault or 
```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
```

Many of these were also failing on #14591 and may still be related to LSRA refactoring.

Symptoms also lead me to suspect GCInfo is broken.

@dotnet/arm64-contrib @dotnet/jit-contrib 

Tested version ae991c3a60

**Comment by CarolEidt** [comment]
@sdmaclea - I have examined the code diffs for one of those tests, and the only source of diffs was the change to use IP0 and IP1. I have a PR #14677 to basically revert that change (though we must allow for the case where the register turns up in `allocateBusyReg()` because it is the candidate register for a fast tail call target). If this addresses the issue, we have issue #14607 to figure out why (e.g. perhaps there's a bad kill set somewhere, though it's not apparent to me).
Since I don't have easy access to hardware, can you advise me what test I should request for this PR to run the tests that are failing?

**Comment by sdmaclea** [comment]
@CarolEidt  I would expect the "test Windows arm64 cross checked and test" leg to run all those tests.

**Comment by BruceForstall** [comment]
The current job is "Windows_NT arm64 Cross Checked Innerloop Build and Test" -- unfortunately, there is no way to trigger an arm64 pri1 test run right now. cc @jashook .

**Comment by sdmaclea** [comment]
I can run it on Monday on Linux when I am back in the office.

**Comment by CarolEidt** [comment]
> I can run it on Monday on Linux when I am back in the office.

That would be great. I attempted to build & run today with a loaned system, but was not successful (can't find System.Native).

**Comment by CarolEidt** [comment]
These two tests are passing with my PR #14677:
JIT/Methodical/Arrays/huge/_il_relhuge_struct/_il_relhuge_struct.sh
JIT/Methodical/VT/port/_il_relhuge_gcref/_il_relhuge_gcref.sh

The others (apparently pri1 tests) I am unable to test.

**Comment by sdmaclea** [comment]
These 4 are still failing w/ #14677
```
JIT/jit64/hfa/main/testC/hfa_sd0C_d/hfa_sd0C_d.sh
JIT/jit64/hfa/main/testC/hfa_sd0C_r/hfa_sd0C_r.sh
JIT/jit64/hfa/main/testC/hfa_sd1C_d/hfa_sd1C_d.sh
JIT/jit64/hfa/main/testC/hfa_sd1C_r/hfa_sd1C_r.sh
```

I think #14677 is still a logical step and could be submitted as is...  The remaining tests are failing with segfaults.

**Comment by BruceForstall** [comment]
These 4 are failing on Windows in the CI:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt/

**Comment by BruceForstall** [comment]
The crash is here:
```
 # Child-SP          RetAddr           Call Site
00 0000005a`e2775510 00007fff`cb66d3c3 protononjit!LinearScan::isSpillCandidate+0x147 e:\gh\coreclr2\src\jit\lsra.cpp @ 6142]
01 0000005a`e2775560 00007fff`cb66eedb protononjit!LinearScan::allocateBusyReg+0x223 e:\gh\coreclr2\src\jit\lsra.cpp @ 6251]
02 0000005a`e2775650 00007fff`cb675f91 protononjit!LinearScan::allocateRegisters+0x153b e:\gh\coreclr2\src\jit\lsra.cpp @ 8349]
03 0000005a`e2775820 00007fff`cb4ff08b protononjit!LinearScan::doLinearScan+0xd1 e:\gh\coreclr2\src\jit\lsra.cpp @ 1795]
04 0000005a`e2775860 00007fff`cb502024 protononjit!Compiler::compCompile+0xe1b e:\gh\coreclr2\src\jit\compiler.cpp @ 4984]
05 0000005a`e2775970 00007fff`cb4f6f05 protononjit!Compiler::compCompileHelper+0xc54 e:\gh\coreclr2\src\jit\compiler.cpp @ 6163]
06 0000005a`e2775a40 00007fff`cb500659 protononjit!`Compiler::compCompile'::`47'::__Body::Run+0x75 e:\gh\coreclr2\src\jit\compiler.cpp @ 5504]
07 0000005a`e2775aa0 00007fff`cb4f6e0e protononjit!Compiler::compCompile+0x1019 e:\gh\coreclr2\src\jit\compiler.cpp @ 5508]
08 0000005a`e2775c10 00007fff`cb4f6faa protononjit!``jitNativeCode'::`11'::__Body::Run'::`6'::__Body::Run+0x18e e:\gh\coreclr2\src\jit\compiler.cpp @ 6811]
09 0000005a`e2775c70 00007fff`cb50c3ee protononjit!`jitNativeCode'::`11'::__Body::Run+0x6a e:\gh\coreclr2\src\jit\compiler.cpp @ 6838]
0a 0000005a`e2775cf0 00007fff`cb512c98 protononjit!jitNativeCode+0x1ee e:\gh\coreclr2\src\jit\compiler.cpp @ 6838]
0b 0000005a`e2775e70 00007fff`cdbeb39f protononjit!CILJit::compileMethod+0x1d8 e:\gh\coreclr2\src\jit\ee_il_dll.cpp @ 300]
```

Data:
```
0:000> ??nextPhysRegPosition
class RefPosition * 0x00000000`00000000
0:000> ??physRegRecord
class RegRecord * 0x00000251`601d1ef8
   +0x000 firstRefPosition : (null) 
   +0x008 recentRefPosition : (null) 
   +0x010 lastRefPosition  : (null) 
   +0x018 isActive         : 0
   +0x020 assignedInterval : (null) 
   +0x028 previousInterval : (null) 
   +0x030 regNum           : 2f ( REG_V15 )
   +0x034 isCalleeSave     : 1
   +0x035 registerType     : c ( TYP_FLOAT )
   +0x036 isBusyUntilNextKill : 0
```

The relevant code in isSpillCandidate:
```
#ifdef _TARGET_ARM_
    if (assignedInterval == nullptr && assignedInterval2 == nullptr)
#else
    if (assignedInterval == nullptr)
#endif
    {
        RefPosition* nextPhysRegPosition = physRegRecord->getNextRefPosition();
        assert((nextPhysRegPosition->nodeLocation == refLocation && candidateBit != refPosition->registerAssignment)
                   ARM64_ONLY(|| (physRegRecord->regNum == REG_IP0) || (physRegRecord->regNum == REG_IP1)));
        return false;
    }
```

It's the assert, above, where the crash is (nextPhysRegPosition is nullptr).

@CarolEidt
