### ISSUE TITLE
Add/Expose String.EndsWith(char)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#1463]
So we don't have to rewrite it over and over :smile:. Seems like its already there just made internal for some reason:

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L2210

People end up writing code like this:

https://github.com/aspnet/dnx/blob/dev/ext/compiler/preprocess/Internalization.cs#L100

and this

https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime/NuGet/Utility/PathUtility.cs#L45

**Comment by bbowyersmyth** [comment]
I had the same thought a while back and discovered it would be a breaking change for an edge case in VB.

Against the current framework the following is valid VB:

    Dim find As Char = "a"c
    Dim result = "abc".StartsWith(find)

The compiler wraps `find` with a call to a string conversion and all is good. If `EndsWith(char)` was made public and the code recompiled it would switch from using the CurrentCulture based `EndsWith(string)` to the Ordinal based `EndsWith(char)`.

Whether any of the [offending characters](http://stackoverflow.com/questions/27974514/why-does-string-u0022-start-with-this-string-u204d) or the above scenario is deemed important I would love to hear. Especially a `StartsWith(char)` with direct access to `String.m_firstChar`

**Comment by AlexGhiondea** [comment]
It seems like the VB compiler is trying to help by picking an overload that will work.

@VSadov -- do you know what the VB compile would do if we were to introduce the ```bool EndsWith(char value)``` overload on string?

@davidfowl can you create an issue in the CoreFx repo (following the [API review process] (aka.ms/apireview))?

**Comment by joshfree** [comment]
Moved this to the correct repo https://github.com/dotnet/corefx/issues/4805

**Comment by fujiy** [comment]
Just to update people subscribed to this topic. It's completed: https://github.com/dotnet/corefx/pull/16198
