### ISSUE TITLE
JENKINS-19022: warning: possible memory leak due to Git plugin usage

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#14686]
Warning in CI Logs

JENKINS-19022: warning: possible memory leak due to Git plugin usage; 
see: https://wiki.jenkins-ci.org/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData

> 01:20:22 Fetching upstream changes from https://github.com/dotnet/coreclr
01:20:22  > git fetch --tags --progress https://github.com/dotnet/coreclr +refs/pull/14655/*:refs/remotes/origin/pr/14655/* # timeout=90
01:20:23  > git rev-parse refs/remotes/origin/pr/14655/merge^{commit} # timeout=10
01:20:23  > git rev-parse refs/remotes/origin/origin/pr/14655/merge^{commit} # timeout=10
**01:20:23 JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://wiki.jenkins-ci.org/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData**
01:20:23 Checking out Revision 27019068c395250c8d4c6f44f6288d497fc23892 (refs/remotes/origin/pr/14655/merge)
01:20:23 Commit message: "Merge 8eb92370085b19192839f93b72a337072bb943de into 980def6282c9c64d38a218c3f37093d130222458"
01:20:23  > git config core.sparsecheckout # timeout=10
01:20:23  > git checkout -f 27019068c395250c8d4c6f44f6288d497fc23892
01:20:33 FATAL: Could not checkout 27019068c395250c8d4c6f44f6288d497fc23892
01:20:33 hudson.plugins.git.GitException: Command "git checkout -f 27019068c395250c8d4c6f44f6288d497fc23892" returned status code 128:
01:20:33 stdout: 
01:20:33 stderr: error: unable to write file tests/src/baseservices/threading/interlocked/add/add.csproj
01:20:33 error: unable to write file tests/src/baseservices/threading/interlocked/add/checkaddint.cs
01:20:33 error: unable to write file tests/src/baseservices/threading/interlocked/add/checkaddlong.cs
01:20:33 error: unable to write file tests/src/baseservices/threading/interlocked/add/interlockedaddint.cs
01:20:33 error: unable to write file tests/src/baseservices/threading/interlocked/add/interlockedaddintwithsubtract.cs

**Comment by jkotas** [comment]
cc @dotnet/dnceng

**Comment by mmitche** [comment]
@benaadams The memoryleak warning has nothing to do with the actual error.  Do have a link to the run? i suspect it's probably an out of disk space issue.  Maybe OSX.

**Comment by benaadams** [comment]
I reported the failure error separately https://github.com/dotnet/coreclr/issues/14688 and it was fixed with https://github.com/dotnet/dotnet-ci/commit/9c6484a632e29755e15a32feda81abae12f42d75

**Comment by RussKeldorph** [comment]
@mmitche Could you close if there is nothing actionable here?
