### ISSUE TITLE
Path.GetFullPath difference between Windows and Linux

### ISSUE THREAD

**Issue by YvonneArnoldus** [dotnet/coreclr#14707]
I have written some code that uses Path.GetFullPath().  I have found some different results for the same paths between Windows and Linux in my Docker image.

Windows: 
input:  a\b\\..\\..\c.\ -> output: C:\code\fontoxml-sdk-schemacompiler\test\FontoXml.Server.Utils.XmlCatalog.Tests\bin\Debug\netcoreapp2.0\c\

Linux:  a/b/../../c./ -> output: /app/test/FontoXml.Server.Utils.XmlCatalog.Tests/bin/Release/netcoreapp2.0/c./

It seems the current directory indicator isn't resolved on Linux as it is on Windows while the parent directory indicator is.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #24907](https://github.com/dotnet/corefx/issues/24907) via [**ZenHub**](https://www.zenhub.com/)
