### ISSUE TITLE
[Local GC] Compile without FEATURE_REDHAWK

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#14701]
Accomplishing this will produce a GC largely equivalent to the one that is linked-in to `coreclr.dll` by default. Today, `clrgc.dll` compiles with `FEATURE_REDHAWK` to paper over some problems, namely:

* Use of `_ASSERTE`
* Use of `nativeoverlapped.h` in the handle table for Overlapped I/O
* Use of `S_SIZE_T`
* `Ref_InitializeHandleTableBucket` making use of `NewHolder`

Final milestone of https://github.com/dotnet/coreclr/issues/11518.

cc @Maoni0 @sergiy-k @jkotas

**Comment by davmason** [comment]
Fixed in #17769
