### ISSUE TITLE
Running dotnet as low priviledge process

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/coreclr#14740]
Hi 

On our test servers, we want to run dotnet with `Network Service` account, which has low privileges.
 However, `dotnet testapp.dll` gives us `Access Denied`.

I tried setting `set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true` and `set NUGET_FALLBACK_PACKAGES=%cd%\fallback_folder` and then run `dotnet`.

This does not help.

dotnet version is `2.0.2`.

I tried `set COREHOST_TRACE=1` to see if i get any debug info. But only `Access Denied` is printed on `stderr`.

How can i debug why dotnet is failing to start ?

**Comment by valerysntx** [comment]
actually You can try "Process Monitor" ([procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)), it can observe file and registry usage of a particular app, producing live detailed log, that can be studied for 'Access Deny' errors

**Comment by ashishnegi** [comment]
@valerysntx  Thanks for the suggestion.
I downloaded latest dotnet zip file and extracted to `D:\Users\testadm\dotnet` folder.
I filtered on events from `process name dotnet.exe` in procmon.
As before, I have set the `DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true`.
I ran `dotnet --version` so as to reduce surface area to dotnet code base.
Procmon gives access denied in :
```
"CreateFile","D:\Users\testadm\dotnet\dotnet.exe","ACCESS DENIED","Desired Access: Read Data/List Directory, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: n/a, ShareMode: Read, Delete, AllocationSize: n/a"
"QueryOpen","D:\Users\testadm\dotnet\host\fxr","ACCESS DENIED",""
```
Full logs are at [dotnet_procmon_logs_with_network_service_priviledge](https://gist.github.com/ashishnegi/8e7aaa47931a372c94c5414b7601a69f).

Here is full command list of what I ran :
```
## My comment : 
## setting skip first time experiment :
D:\Users\testadm\Downloads\SysinternalsSuite>set DOTNET_SKIP_FIRST_TIME_EXPERIEN
CE=true

## NO .dotnet folder under my user folder.
D:\Users\testadm\Downloads\SysinternalsSuite>dir "D:\Users\testadm"\
 Volume in drive D is Windows
 Volume Serial Number is D896-308E

 Directory of D:\Users\testadm

10/30/2017  12:58 PM    <DIR>          .
10/30/2017  12:58 PM    <DIR>          ..
10/30/2017  12:02 PM    <DIR>          Contacts
10/30/2017  12:02 PM    <DIR>          Desktop
10/30/2017  12:02 PM    <DIR>          Documents
10/30/2017  12:58 PM    <DIR>          dotnet
10/30/2017  12:16 PM       129,741,059 dotnet.zip
10/30/2017  12:10 PM    <DIR>          Downloads
10/30/2017  12:02 PM    <DIR>          Favorites
10/30/2017  12:02 PM    <DIR>          Links
10/30/2017  12:02 PM    <DIR>          Music
10/30/2017  12:02 PM    <DIR>          Pictures
10/30/2017  12:02 PM    <DIR>          Saved Games
10/30/2017  12:02 PM    <DIR>          Searches
10/30/2017  12:02 PM    <DIR>          Videos
               1 File(s)    129,741,059 bytes
              14 Dir(s)  22,044,495,872 bytes free

# # starting dotnet as Network Service
D:\Users\testadm\Downloads\SysinternalsSuite>PsExec64.exe -i -u "nt authority\ne
twork service" D:\Users\testadm\dotnet\dotnet.exe --version

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

D:\Users\testadm\dotnet\dotnet.exe exited on RD00155DE6396A with error code -214
7450749.
```

If I run with admin mode, promon logs are [here]( https://gist.github.com/ashishnegi/a28b4f9172e01fa9efaaaee1c635dd73)

**Comment by jkotas** [comment]
This issue was moved to dotnet/core-setup#3373

**Comment by jkotas** [comment]
`dotnet.exe` lives in core-setup repo.
