### ISSUE TITLE
DynamicMethod does not work with ref-return

### ISSUE THREAD

**Issue by weltkante** [dotnet/coreclr#14742]
When using ref-return with DynamicMethod I'm getting a `NotSupportedException: The return Type contains some invalid type (i.e. null, ByRef)`.

However ByRef is clearly not invalid since the C# Compiler added ref-returns as a language feature and generating such IL into a DynamicAssembly also works without complaining; I think the restriction of DynamicMethod should be lifted. Here's some [example code](https://gist.github.com/weltkante/94652de66940d494cdcf61e3a62a4b0f) I'm using for testing this.

There is also dotnet/roslyn#17993 but since this isn't working at all just adding tests won't do and it probably needs some fix in the CLR as well to at least lift the restrictions in the argument checks.

**Comment by jkotas** [comment]
This should be easy fix:
- Remove the superfluous check for ByRef: https://github.com/dotnet/coreclr/blob/da8b7181dbe362fbfe64c7ef72ff3a4a7db68f24/src/mscorlib/src/System/Reflection/Emit/DynamicMethod.cs#L301
- Adjust error message: https://github.com/dotnet/coreclr/blob/e46a52864447e8037746cca83928d61ba8623edc/src/mscorlib/Resources/Strings.resx#L415
- Adjust test: https://github.com/dotnet/corefx/blob/868f123881e520285ab09600380e38abdd457a06/src/System.Reflection.Emit.Lightweight/tests/DynamicMethodCtor.cs#L116

**Comment by cod7alex** [comment]
Hi guys, what change to test will be convenient? Just check that it does not throw now?

**Comment by jkotas** [comment]
Yes. Emit a trivial dynamic method that returns byref and call it.
