### ISSUE TITLE
[RyuJIT/x86][JitStressRegs=0x80] Assertion failed 'emitVerifyEncodable(ins, size, reg1, reg2)'

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#14771]
This assert occurs in this recently-added test:
JIT\HardwareIntrinsics\Crc32_r\Crc32_r.exe

This impedes arm altjit stress testing.

**Comment by fiigii** [comment]
Thanks for pointing out! I will fix this in `emitter::emitVerifyEncodable`.

**Comment by fiigii** [comment]
Hmm, this is not caused by `emitter::emitVerifyEncodable`. Something similar to https://github.com/dotnet/coreclr/pull/7122?
