### ISSUE TITLE
[RyuJit/Arm32/JitStress=1]Assertion failed '!GenTree::IsExOp(tree->OperKind()) && tree->OperIsSimple()'

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#14773]
There are 4 new failures in [arm32 JitStress leg](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress1_prtest/9/#showFailuresLink): 
```
JIT_HardwareIntrinsics._Lzcnt_r_Lzcnt_r_._Lzcnt_r_Lzcnt_r_cmd
JIT_HardwareIntrinsics._Popcnt_r_Popcnt_r_._Popcnt_r_Popcnt_r_cmd
JIT_HardwareIntrinsics._Lzcnt_ro_Lzcnt_ro_._Lzcnt_ro_Lzcnt_ro_cmd
JIT_HardwareIntrinsics._Crc32_ro_Crc32_ro_._Crc32_ro_Crc32_ro_cmd
```

This is presumably due to #14456.

**Comment by fiigii** [comment]
@sandreenko Thanks for pointing this out! Will fix.

**Comment by fiigii** [comment]
Why does the test fail on ARM32? cc @CarolEidt

**Comment by CarolEidt** [comment]
> Why does the test fail on ARM32?

It is not actually failing on ARM32. When we do arm altjit stress testing, it actually compiles and runs the x86 code, and then, for each method, it also calls the arm altjit. So any x86 stress failures also show up on the arm altjit stress testing.

**Comment by fiigii** [comment]
I see. Thank you for explaining.

**Comment by BruceForstall** [comment]
Note that this is causing most or all x86 and x64 stress modes to fail. See https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/
