### ISSUE TITLE
Assembly.Load with null Version

### ISSUE THREAD

**Issue by mellinoe** [dotnet/coreclr#1477]
I'm curious about the behavior of Assembly.Load(AssemblyName) when the given AssemblyName has a null Version property. It seems that, when trying to load an unsigned assembly (no public key), you must assign something to the Version property; even 0.0.0.0 works. For example, the following doesn't work:
````CSharp
Assembly.Load(new AssemblyName("unsigned-assembly"))
>> FileLoadException, "Assembly's manifest definition doesn't match assembly reference"
````
but the following does. The second one works because the assembly is signed.
````CSharp
Assembly.Load(new AssemblyName("unsigned-assembly") { Version  = new Version(0, 0, 0, 0) });
Assembly.Load(new AssemblyName("signed-assembly"));
````
Do we have documentation regarding this behavior? It seems a little counter-intuitive to me.

This came up because the latest beta version of xUnit attempts to load assemblies by calling Assembly.Load(new AssemblyName() { Name = ..., Version = null }). Actually it's slightly different than that, but that's the gist of it: https://github.com/xunit/xunit/blob/master/src/common/SerializationHelper.cs#L166.

cc: @jkotas , @nguerrera , @weshaggard

**Comment by jkotas** [comment]
It looks like a bug to me that we should fix.

**Comment by tmat** [comment]
We need this to be fixed before we can start running Roslyn tests on CoreCLR.

**Comment by sergiy-k** [comment]
@kouvel, could you please take a look?

**Comment by kouvel** [comment]
Sure, I'll take a look

**Comment by jkotas** [comment]
cc @gkhanna79

**Comment by mellinoe** [comment]
There was some discussion over email regarding this that wasn't captured here. A main point was that assemblies on the TPA list (everything residing next to CoreRun gets put there) must have a version specified in order to be loaded. That seems to be the relevant part of the logic involved here.
