### ISSUE TITLE
How To Build My Own .Net Core Profiler

### ISSUE THREAD

**Issue by Salty-Sailor** [dotnet/coreclr#14786]
I have written a .NetCore(2.0) App and want to do some profile work. Based on the .NetCore  Profiling Overview docs(https://github.com/dotnet/coreclr/blob/master/Documentation/botr/profiling.md),
it seems like that I just need to implement the Profiler DLL and add into my .NetCore Project(is that right?).But I have no experience on writing code like this(what I only know is that I need to implement the **ICorProfilerCallback2** interfaces in the Profiler DLL).
So, is there any suggestions on how to start to build my own Profiler or some Profiler examples? Thank you :)

PS: My work OS is macOS&centOS 7,
and in this file (https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/profiling-api-status.md) it seems that the profiling API was finished on Windows/Linux

**Comment by jkotas** [comment]
@sywhang

**Comment by sywhang** [comment]
Hi @Salty-Sailor, thank you for your inquiry. 

We do have a very minimal, but working sample profiler available at https://github.com/Microsoft/clr-samples/tree/master/ProfilingAPI/ReJITEnterLeaveHooks. There are already instructions on how to build it and use it, for Windows/Linux/MacOS. You can feel free to use this as your starting point on how to implement your own .NET Core profiler.

Please do keep in mind that the profiler APIs have not yet been tested on macOS, and you may experience unexpected failures on macOS. As the profiler API status states, they have been tested against Linux, so I'd suggest using centOS to start.

If you have any more questions or trouble, please feel free to comment again.

Cheers,
Sung

**Comment by Salty-Sailor** [comment]
That's truly what I want, thanks!!!

**Comment by sywhang** [comment]
Glad to hear that it was what you were looking for. 
I'll close this issue for now, but feel free to reopen if you run into any issues :)
