### ISSUE TITLE
Add command to dotnet CLI to download symbols for runtime and libraries

### ISSUE THREAD

**Issue by lt72** [dotnet/coreclr#14794]
How about something like:

```dotnet get-runtime-symbols``` (defaults to runtime and libraries that best match the CLI version)
```dotnet get-runtime-symbols 2.0.3```

**Comment by lt72** [comment]
After talking to Kathleen it seems like the idea implementation for this feature is through a "global tool", say _net_symclient_. Such global tool will be a nuget package, that evolves independently of the dotnet cli, although it will follow appropriate naming conventions for the EXE and its commands, as well as share the command line parsing code, so that the help experience will be consistent as well. (Please note that the command line parser may or may not be available at the time 2.1 ships, although this would just entail a temporary code dup, if at all).

Users will be able to do:
```dotnet install net_symclient``` to get the latest version of the tool, and then will use it as per the scenarios we will define and document on coreclr doc pages.

If this sounds OK and there are no other ideas to explore, we will take a stab at this sometimes soon.


@KathleenDollard 
@Petermarcu @danmosemsft FYI

**Comment by KathleenDollard** [comment]
I'd like us to knock that name around a little to, but I think this is a great global tools candidate.
________________________________

**Comment by mikem8361** [comment]
The symbol downloader extension (1.0.0) has been published:

To get matching runtime and symbol binaries for the core dump use the symbol downloader CLI extension:
  - Install the [.NET Core 2.1 SDK](https://www.microsoft.com/net/download/).
  - Install the symbol downloader extension: `dotnet tool install -g dotnet-symbol`.
  - Run `dotnet symbol coredump` to download the runtime binaries and symbols.
  - Check out the coreclr and corefx repositories at the appropriate commit for the appropriate source.
  - For more details see: [dotnet-symbol](https://github.com/dotnet/symstore/blob/master/src/dotnet-symbol/README.md).
