### ISSUE TITLE
Improve unix corerun debug messages

### ISSUE THREAD

**Issue by linquize** [dotnet/coreclr#148]
It would be nice to add more debug messages in unix corerun and add something like --verbose option.
e.g, the program quit silently or just print 0x80004005 when an error occurred.
Also, when an unhandled exception is thrown, the exception is not printed to standard error.
We do not know the cause of error.

**Comment by cnblogs-dudu** [comment]
Print 0x80004005 because mscorlib.dll is absent.
Same silently quit problem:
```
# ./corerun HelloWorld.dll
# 
```

**Comment by linquize** [comment]
Also, when an unhandled exception is thrown, the exception is not printed to standard error.

**Comment by kangaroo** [comment]
There are some undocumented (at least as far as I could find) environment variables which will give you various log information:

For the execution engine try:
export COMPlus_LogEnable=1
export COMPlus_LogToConsole=1

Adjust COMPlus_LogLevel as needed.

For the PAL (which is probably where you are failing) you can use:

export PAL_DBG_CHANNELS="+all.all"

See src/pal/src/include/pal/dbgmsg.h for more fine grained options of the PAL log levels.

**Comment by cnblogs-dudu** [comment]
@kangaroo 
Thansk. `export PAL_DBG_CHANNELS="+all.all"` works.

**Comment by cnblogs-dudu** [comment]
`export PAL_DBG_CHANNELS="+PAL.TRACE:-FILE.ERROR"` has less noise.

**Comment by janvorli** [comment]
@linquize Exception handling and stack walking is not implemented yet. I am working on it.

**Comment by kangaroo** [comment]
Unhandled exception printing was implemented.  Can we close this out?

**Comment by MattWhilden** [comment]
As a cleanup task I'm going to speculatively close this out. If that's in error please let me know.
