### ISSUE TITLE
Not possible to build CoreCLR for ARM (cross compilation, on Linux)

### ISSUE THREAD

**Issue by gitchomik** [dotnet/coreclr#1480]
file : /coreclr/src/ToolBox/SOS/Strike/CMakeLists.txt
revis issue : d5d41105716703845d61a6f8c26724381b959c7d
lines : 79-82

**Comment by shahid-pk** [comment]
their are no CI servers set up for the arm build as of yet because their is still some work to do . Although it should be building ok. @benpye  will surely know and help u .

**Comment by gitchomik** [comment]
Are yout sure ?
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_arm_linux_debug/

**Comment by shahid-pk** [comment]
this is probably a test build that @mmitche  was trying to setup the CI server and yes i am 200 % sure

**Comment by gitchomik** [comment]
OK, probab;y you are right, but I just make this issue because rev. d5d41105716703845d61a6f8c26724381b959c7d even not start, for example rev. c3efa1e9cc7953e50496d494de0cd0e2a1cc337f is starting to build something, that it is difference.

**Comment by shahid-pk** [comment]
@mmitche got into some other issues too when he was trying to setup the CI server. If you can fix these issues it will be great. as the arm port is all until now a community effort.

**Comment by mmitche** [comment]
Yeah I added that yesterday.  I still need to formalize the rootfs on the machines (I got it working in a local test).  That will happen today and then it should start passing as part of the outerloop testing when the strike fix goes in (which I think a couple community members were just about to fix)

**Comment by mmitche** [comment]
Yep, though it's currently broken.  I think that's a different issue though
