### ISSUE TITLE
Add -utf-8 to compileoptions.cmake?

### ISSUE THREAD

**Issue by LYP951018** [dotnet/coreclr#14818]
When compiling CoreCLR under Windows with locales other than America (such as China), MSVC generates warnings that some of files contain characters are not representable under the code page (such as 936).

**Comment by jkotas** [comment]
@LYP951018 This sounds like a good idea. Would you be interested in submitting PR with the fix?

**Comment by LYP951018** [comment]
@jkotas Yes! I'll submit a pr soon.
