### ISSUE TITLE
Debugging instructions should clearly carry information as to how acquire symbols

### ISSUE THREAD

**Issue by lt72** [dotnet/coreclr#14819]
[Debugging instructions](https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md) should carry the information on how to acquire symbols. Whether that happens through a tool, or by manual download, or both, all locations of the symbols should be clearly documented.
E.g.: the debugging instruction page should carry a link to the [core-setup](https://github.com/dotnet/core-setup) and the download links page on [DLC](https://www.microsoft.com/net/download/windows).

**Comment by mikem8361** [comment]
Add this section to doc:

- To get matching runtime and symbol binaries for the core dump use the symbol downloader CLI extension:
  - Install the [.NET Core 2.1 SDK](https://www.microsoft.com/net/download/).
  - Install the symbol downloader extension: `dotnet tool install -g dotnet-symbol`.
  - Run `dotnet symbol coredump` to download the runtime binaries and symbols.
  - Check out the coreclr and corefx repositories at the appropriate commit for the appropriate source.
  - For more details see: [dotnet-symbol](https://github.com/dotnet/symstore/blob/master/src/dotnet-symbol/README.md).
