### ISSUE TITLE
Possibly use shared memory/semaphores in the dbi/coreclr debugger transport.

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#1482]
More details to come.

**Comment by Djuffin** [comment]
When running in a Docker container /tmp (where CLR keeps debugging fifo-s) is not necessary cleaned between container restarts, and main process (debugee) always has pid=1. 

That's why fifo like /tmp/clr-debug-pipe-1-in almost always already exists in a container that's running CoreCLR process.

**Comment by mikem8361** [comment]
@leecow, @tzwlai  I don't think this is a blocking-release/rtm issue.

PR #2633 will address most of the ways the pipe files are not cleaned up.

**Comment by leemgs** [comment]
> That's why fifo like /tmp/clr-debug-pipe-1-in almost always already exists in a container that's running CoreCLR process.

@Djuffin , BTW, Can we print  some messages (hint data) via /tmp/clr-debug-pipe-*** ?
For instance, target#> cat /tmp/clr-debug-pipe-<pid>-99999-{in|out}   [enter]
In this case, I could not get any messages.

**Comment by mikem8361** [comment]
Djuffin (Eugene) is no longer at Microsoft anymore.  

This name problem with docker has been fixed by adding the creation time to the pipe name (and the named semaphores used in launch/attach in dbgshim). See TwoWayPipe::GetPipeName in twowaypipe.cpp.

**Comment by mikem8361** [comment]
I think this suggestion would no longer is viable because instead of just leaking pipe files in the tmp directory switch to shared memory/semaphores would mean that a coreclr process could leak both a named shared memory and named semaphore file artifact. On OS X, there isn't a way to clean inspect or clean the leaked semaphore artifacts. Rebooting is the only option.
