### ISSUE TITLE
`double.IsNaN` and `float.IsNaN` should be updated to be intrinsic

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#14846]
Both of these methods should be updated to be intrinsic and generate a single instruction on platforms that support it.

On x86 architectures, they should be generating `ucomisd` and `ucomiss`, respectively.

category:cq
theme:basic-cq
skill-level:intermediate
cost:medium

**Comment by tannergooding** [comment]
As per the discussion here: https://github.com/dotnet/coreclr/pull/13781

@mikedn pointed out:
> The code generated for something like `if (isnan) d = nan` is
```asm
       C4E17B110424         vmovsd   qword ptr [rsp], xmm0
       488B0424             mov      rax, qword ptr [rsp]
       48BAFFFFFFFFFFFFFF7F mov      rdx, 0x7FFFFFFFFFFFFFFF
       4823C2               and      rax, rdx
       48BA000000000000F07F mov      rdx, 0x7FF0000000000000
       483BC2               cmp      rax, rdx
       7E09                 jle      SHORT G_M55888_IG03
       C4E17B100515000000   vmovsd   xmm0, qword ptr [reloc @RWD00]
```
> Unfortunately it involves storing/loading to/from memory and that's probably impossible to avoid without JIT support. The "normal" way to do this in ASM is `movq rax, xmm0`.

**Comment by tannergooding** [comment]
MSVC, GCC, Clang all end up generating code similar to:
The codegen for `IsNaN` could be simplified down to something similar to the following:
```asm
xor eax, eax
ucomisd xmm0, xmm0
setp al
```

**Comment by mikedn** [comment]
Rather than turning `IsNan` into an intrinsic we should look into improving the codegen for `x != x`. That may be simpler than adding an intrinsic.
