### ISSUE TITLE
Marshalling a returned struct with a boolean field crashes

### ISSUE THREAD

**Issue by ddobrev** [dotnet/coreclr#1485]
This code:
    using System.Runtime.InteropServices;

    namespace TestMarshal
    {
        public struct QVariant
        {
            [StructLayout(LayoutKind.Explicit, Size = 16)]
            public struct Internal
            {
                [FieldOffset(0), MarshalAs(UnmanagedType.I1)]
                public bool d;
            }

            [UnmanagedFunctionPointerAttribute(CallingConvention.ThisCall)]
            public delegate Internal _Interpolated_0Delegate(System.IntPtr instance);

            public static _Interpolated_0Delegate _Interpolated_0DelegateInstance;

            public static Internal _Interpolated_0DelegateHook(System.IntPtr instance)
            {
                return new Internal();
            }
        }

        class Program
        {
            static void Main()
            {
                QVariant._Interpolated_0DelegateInstance += QVariant._Interpolated_0DelegateHook;
                var functionPointerForDelegate = Marshal.GetFunctionPointerForDelegate(QVariant._Interpolated_0DelegateInstance);
                functionPointerForDelegate.GetHashCode();
            }
        }
    }

crashes with:

"Method's type signature is not PInvoke compatible."

It crashes the same way if MarshalAs(UnmanagedType.I1) is added to the field.

I have tested this with .NET 4.0 and .NET 4.5.1, no difference in behaviour.
It works properly on Mono with or without a MarshalAs attribute.

**Comment by akoeplinger** [comment]
It seems to run fine on CoreCLR via DNX dnx-coreclr-win-x64.1.0.0-beta8-15563, so it might be a .NET bug.

Contrary to what you experienced I also get a crash on Mono (4.0 and master, `* Assertion at mini-amd64.c:918, condition 'class1 != ARG_CLASS_NO_CLASS' not met`).

**Comment by ddobrev** [comment]
Yes, it's a .NET bug, I have no idea if it works on CoreCLR. About Mono, this code - http://pastebin.com/vSckyJaK - works, there may be problems with the decreased test case I used here.

**Comment by akoeplinger** [comment]
@ddobrev you're right, it works on Mono and CoreCLR with that code and crashes on .NET 4.6.

**Comment by jkotas** [comment]
This is documented implementation limitation. From [msdn](https://msdn.microsoft.com/en-us/library/ef4c3t39.aspx): P/Invoke cannot have non-blittable types as a return value

You can workaround it by making the struct blittable:

        [StructLayout(LayoutKind.Explicit, Size = 16)]
        public struct Internal
        {
            [FieldOffset(0)]
            public byte d;
        }

It will crash on CoreCLR too - once you actually try to call the delegate. CoreCLR exception throwing is more lazy in this case - for better performance.

**Comment by ddobrev** [comment]
@jkotas thank you very much for your explanation. So this behaviour is actually documented. Let me ask you: is this behaviour a part of the C#/CLI specification? If not, why does it work on Mono, have they perhaps taken a little liberty in their implementation?

**Comment by jkotas** [comment]
The CLI specification does not have the exact lists of marshaling behaviors that has to be supported - it only talks about a very basic minimum. Look for `II.15.5.4 Data type marshaling`.

BTW: Our longer term plan to deal with the pinvoke marshaling is MCG tool. More details about how MCG works is in [this blog](http://blogs.msdn.com/b/dotnet/archive/2014/06/13/net-native-deep-dive-debugging-into-interop-code.aspx) post written by @yizhang82

**Comment by ddobrev** [comment]
I understand. Thank you very much. I am closing this since it's documented and therefore a limitation, not a bug.
