### ISSUE TITLE
[Question] Checked/free mismatch with native image exception

### ISSUE THREAD

**Issue by Alecu100** [dotnet/coreclr#14870]
So I tried to setup my own coreCLR project locally to debug it and understand it better.

I could not understand if the instructions in the readme and documentation section of the repository is up to date.

So I tried something similar. I created a .net core application in Visual Studio 2017. And I added a reference to the CoreCLR I just built like this in the project:

    <PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR" Version="2.0.0" /> 

Then I created a new nugget package source and pointed it to the build directory when the coreCLR libraries are stored after you build them, the bin/Product/platform/.nugget directory.

Then I changed the project to be self-contained, to copy all the assemblies locally and not depend on anything. I added a new entry in the project: for this:

    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>

And that's about all. I checked and when I start to debug coreCLR in a .net core project it crashes at this line:

`    if (info->wBuild !=
#if _DEBUG
        CORCOMPILE_BUILD_CHECKED
#else
        CORCOMPILE_BUILD_FREE
#endif
        )
    {
        RuntimeVerifyLog(LL_ERROR, pLogAsm, W("Checked/free mismatch with native image."));
        return FALSE;
    }`

I don't know if I am doing something wrong here.

**Comment by jkotas** [comment]
I would recommend to use https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md#update-coreclr-from-raw-binary-output . This is what I have been doing personally for testing or debugging, and it is easiest way to use private coreclr build in an app.

> Checked/free mismatch with native image

This error means that the debug build of CoreCLR.dll is used together with release build of System.Private.CoreLib.dll, or vice versa. Both CoreCLR.dll and System.Private.CoreLib.dll have to be same build flavor.

**Comment by jkotas** [comment]
> I could not understand if the instructions in the readme and documentation section of the repository is up to date.

We try to keep the instructions up to date. If you find some that are outdates, please create an issue or even better submit PR to correct it. Thank you!

**Comment by Alecu100** [comment]
Hello,

Thanks for replying! Will look into this as soon as I get home. Maybe I will even do a post on my blog about setting up and running a custom CoreCLR.
