### ISSUE TITLE
Implement InjectActivation for FreeBSD

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/coreclr#1487]
`InjectActivationInternal` (from src\pal\src\exception\signal.cpp) currently uses `pthread_sigqueue` in order to inject a function, so it doesn't work on FreeBSD where `pthread_sigqueue` is not available. This isn't a problem at the moment because there's no code that needs to use `InjectActivation` on FreeBSD for now, but if we want to use this function for GC suspension like we currently do on Linux, it needs to be implemented.

The work here is to implement this function with a design that works with FreeBSD and also remains compatible with other platforms.

**Comment by adityamandaleeka** [comment]
BTW, @kangaroo had some thoughts about this here: https://github.com/dotnet/coreclr/pull/1371#issuecomment-129974852

**Comment by janvorli** [comment]
I need to implement activations for OSX for GC suspension purposes. So I have decided to implement mechanism to store pending activations in the CPalThread that can also be used on Linux / FreeBSD with pthread_kill that's portable.

**Comment by janvorli** [comment]
Fixed by #1582
