### ISSUE TITLE
PowerShell hangs on exit because finalizer is not called using dotNet CLR 2.0.4

### ISSUE THREAD

**Issue by PaulHigin** [dotnet/coreclr#14889]
I don't know if this is related to Issue #14763, but it looks like this recent version of the CLR is not calling finalizers.  This is causing PowerShell to hang in some cases (https://github.com/PowerShell/PowerShell/issues/5205).

Repro:
```
using System;
using System.IO;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var pid = System.Diagnostics.Process.GetCurrentProcess().Id;
            Console.WriteLine("Process ID: " + pid.ToString());

            // Wait for debugger attach.
            var debuggerAttached = false;
            while (!debuggerAttached)
            {
                System.Threading.Thread.Sleep(500);
            }
            System.Diagnostics.Debugger.Break();

            var testC1 = new TestC1(@"c:\temp1.txt");
        }
    }

    public class TestC1
    {
        FileStream _fs;

        public TestC1(string filePath)
        {
            try
            {
                _fs = File.Open(filePath, FileMode.Open);
            }
            catch { }
        }

        ~TestC1()
        {
            if (_fs != null) { _fs.Dispose(); }
        }
    }
}
```
Set a breakpoint on ~TestC1() and it never gets called.

**Comment by daxian-dbw** [comment]
A clarification: the original powershell issue https://github.com/PowerShell/PowerShell/issues/5205 was reported with powershell-beta.8 package which targets .NET Core runtime 2.0.0, so this issue is not specific to 2.0.4 servicing packages.

**Comment by jkotas** [comment]
> Set a breakpoint on ~TestC1() and it never gets called.

This is behavior is by design in .NET Core. .NET Core does not have finalization on shutdown because of it is impossible to do it reliably. It has been like that since .NET Core 1.0.

https://github.com/dotnet/corefx/issues/5205 has details.

**Comment by PaulHigin** [comment]
Regarding repro, debuggerAttached is set to "true" after debugger attach.  System.Diagnostics.Debugger.IsAttached will work too.

**Comment by PaulHigin** [comment]
@jkotas I didn't read the entire 5205 issue.  When you say running finalizer threads on shutdown is not reliable on dotnet Core, do you mean it is less reliable than what was implemented in the FullCLR?  Or that it can never be completely reliable?  I don't mind that it is never fully reliable because it works well enough and PowerShell has been working fine for years with the FullCLR finalizer on shutdown.  A best effort is perfectly fine.  If the CLR does not solve the issue then it means that each application will have to do it when needed.  I feel it is better to have the CLR solution.

**Comment by jkotas** [comment]
It can never be completely reliable. It is not reliable even in the full CLR. It is frequent source of the shutdown hangs and crashes there. If you check Windows telemetry about hangs and crashes during powershell shutdown, I expect that you will find good number of them caused by this issue.

If there are specific actions you need to execute during shutdown, the recommendation is to register them as `AppDomain.DomainUnload.Unload` event handler. `AppDomain.DomainUnload.Unload` is .NET Standard 2.0 API and works find in all runtimes.

It is intentional minor incompatibility between .NET Framework and .NET Core.

**Comment by PaulHigin** [comment]
Ok.  I think we can use AppDomain.DomainUnload.Unload event to do clean up.  Thanks.

**Comment by PaulHigin** [comment]
@jkotas 
I experimented with this and AppDomain.DomainUnload event is not called with my version of DotNet Core CLR (2.0.4).  Am I missing something?

The AppDomain.ProcessExit event *is* called but that doesn't help me because process exit will not occur until all threads exit and I am using this to clean up threads.

**Comment by jkotas** [comment]
> AppDomain.DomainUnload event is not called with my version of DotNet Core CLR (2.0.4). Am I missing something?

Sorry. I forgot that the DomainUnload event is not delivered for default domain (always the case for .NET Core).

> AppDomain.ProcessExit event is called but that doesn't help me because process exit will not occur until all threads exit

Can you mark your threads as background threads so that they do not block process exit?

**Comment by PaulHigin** [comment]
@jkotas  We don't want these to be background threads.  I'll go with plan B and not rely on CLR events.
