### ISSUE TITLE
[Local GC] Unhandled exception in standalone GC causes a deadlock

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#14915]
When not running standalone, an unhandled exception in the GC is caught by the vectored exception handler [here](https://github.com/dotnet/coreclr/blob/master/src/vm/excep.cpp#L7802) which ultimately causes an assert failure, e.g. (seen here with an AV inserted into `WKS::GCHeap::Promote`):

```
Assert failure(PID 29968 [0x00007510], Thread: 20984 [0x51f8]): Consistency check failed: AV in clr at this callstack: ------
CORECLR! WKS::GCHeap::Promote + 0x41 (0x00007ffe`4a210c01)
CORECLR! GcEnumObject + 0xC3 (0x00007ffe`4a0ca4c3)
CORECLR! GcInfoDecoder::ReportStackSlotToGC + 0x55E (0x00007ffe`4a1305ee)
CORECLR! GcInfoDecoder::ReportSlotToGC + 0x1B5 (0x00007ffe`4a130015)
CORECLR! GcInfoDecoder::ReportUntrackedSlots + 0x82 (0x00007ffe`4a130682)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x1070 (0x00007ffe`4a12e8f0)
CORECLR! EECodeManager::EnumGcRefs + 0x5D8 (0x00007ffe`49dbd658)
CORECLR! GcStackCrawlCallBack + 0x485 (0x00007ffe`4a0cab95)
CORECLR! Thread::MakeStackwalkerCallback + 0x6C (0x00007ffe`49aae3cc)
CORECLR! Thread::StackWalkFramesEx + 0x17B (0x00007ffe`49ab14db)
CORECLR! Thread::StackWalkFrames + 0x2F4 (0x00007ffe`49ab1344)
CORECLR! ScanStackRoots + 0x32F (0x00007ffe`4a2b4ebf)
CORECLR! GCToEEInterface::GcScanRoots + 0x1F9 (0x00007ffe`4a2b3ae9)
CORECLR! GCScan::GcScanRoots + 0x2F (0x00007ffe`4a2be2cf)
CORECLR! WKS::gc_heap::mark_phase + 0x322 (0x00007ffe`4a23a212)
CORECLR! WKS::gc_heap::gc1 + 0x1AA (0x00007ffe`4a22e35a)
CORECLR! WKS::gc_heap::garbage_collect + 0x5CA (0x00007ffe`4a22e14a)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x1DC (0x00007ffe`4a20ee7c)
CORECLR! WKS::GCHeap::GarbageCollectTry + 0xE0 (0x00007ffe`4a20eff0)
-----
.AV on tid=0x51f8 (20984), cxr=0000003800979B00, exr=0000003800979FF0
FAILED: false

CORECLR! CHECK::Trigger + 0x26A (0x00007ffe`497fc24a)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x2F6 (0x00007ffe`4990a466)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x8C (0x00007ffe`49909e8c)
CORECLR! CLRVectoredExceptionHandler + 0x262 (0x00007ffe`49909de2)
CORECLR! CLRVectoredExceptionHandlerShim + 0x172 (0x00007ffe`4990a702)
NTDLL! RtlUserThreadStart + 0x132 (0x00007ffe`a74df0a2)
NTDLL! RtlWalkFrameChain + 0x122B (0x00007ffe`a748cecb)
NTDLL! KiUserExceptionDispatcher + 0x2E (0x00007ffe`a7513b6e)
CORECLR! WKS::GCHeap::Promote + 0x41 (0x00007ffe`4a210c01)
CORECLR! GcEnumObject + 0xC3 (0x00007ffe`4a0ca4c3)
    File: e:\github\coreclr\src\vm\excep.cpp Line: 7930
    Image: E:\GitHub\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\CoreRun.exe
```

When running standalone, for whatever reason, this vectored exception handler is not invoked and instead we end up in the normal CLR exception path, which results in us attempting to allocate a managed exception object. On debug builds, this asserts:

```
Assert failure(PID 43992 [0x0000abd8], Thread: 43532 [0xaa0c]): CONTRACT VIOLATION by ExceptionTracker::GetOrCreateTracker at "e:\github\coreclr\src\vm\exceptionhandling.cpp" @ 3682

GC_TRIGGERS encountered in a GC_NOTRIGGER scope

                        CONTRACT in ExceptionTracker::GetOrCreateTracker at "e:\github\coreclr\src\vm\exceptionhandling.cpp" @ 3682
VIOLATED-->  CONTRACT in EECodeManager::EnumGcRefs at "e:\github\coreclr\src\vm\eetwain.cpp" @ 4919
                        FAULT_FORBID in standalone::ScanStackRoots at "e:\github\coreclr\src\vm\gcenv.ee.cpp" @ 83
                        GCX_NOTRIGGER in standalone::ScanStackRoots at "e:\github\coreclr\src\vm\gcenv.ee.cpp" @ 83
                        CANNOTTHROW in standalone::ScanStackRoots at "e:\github\coreclr\src\vm\gcenv.ee.cpp" @ 83
                        CONTRACT in Alloc at "e:\github\coreclr\src\vm\gchelpers.cpp" @ 218
                        CONTRACT in SlowAllocateString at "e:\github\coreclr\src\vm\gchelpers.cpp" @ 1011
                        OVERRIDE_TYPE_LOAD_LEVEL_LIMIT in MethodDescCallSite::CallTargetWorker at "e:\github\coreclr\src\vm\callhelpers.cpp" @ 371
                        CONTRACT in MethodDescCallSite::CallTargetWorker at "e:\github\coreclr\src\vm\callhelpers.cpp" @ 361
                        CONTRACT in AppDomain::DoSetup at "e:\github\coreclr\src\vm\appdomain.cpp" @ 4642
                        GCX_COOP in CorHost2::_CreateAppDomain at "e:\github\coreclr\src\vm\corhost.cpp" @ 671
                        GCX_COOP_THREAD_EXISTS in CorHost2::_CreateAppDomain at "e:\github\coreclr\src\vm\corhost.cpp" @ 647
                        CONTRACT in CorHost2::_CreateAppDomain at "e:\github\coreclr\src\vm\corhost.cpp" @ 617



CORECLR! CONTRACT_ASSERT + 0x342 (0x00007ffe`489faab2)
CORECLR! EEContract::DoChecks + 0x3DE (0x00007ffe`48b59ace)
CORECLR! ExceptionTracker::GetOrCreateTracker + 0x327 (0x00007ffe`48cf1937)
CORECLR! ProcessCLRException + 0x62F (0x00007ffe`48cfd57f)
NTDLL! chkstk + 0x11D (0x00007ffe`a7514c3d)
NTDLL! RtlWalkFrameChain + 0x1518 (0x00007ffe`a748d1b8)
NTDLL! KiUserExceptionDispatcher + 0x2E (0x00007ffe`a7513b6e)
CLRGC! WKS::GCHeap::Promote + 0x3B (0x00007ffe`6c98625b)
CORECLR! PromoteCarefully + 0xE1 (0x00007ffe`48f9b751)
CORECLR! GcEnumObject + 0x92 (0x00007ffe`492ea492)
    File: e:\github\coreclr\src\vm\exceptionhandling.cpp Line: 3682
    Image: E:\GitHub\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\CoreRun.exe
```

On non-debug builds, this will deadlock since crashes in the GC generally occur when *doing* GCs and the allocating thread needs to switch to cooperative mode to allocate.

**Comment by swgillespie** [comment]
Marking this as 2.1 as this is really annoying for developers (*this* developer, at least...).

**Comment by swgillespie** [comment]
Ultimately it looks like we'll only assert/ExecutionEngineException if the faulting IP lies within `coreclr.dll`:
https://github.com/dotnet/coreclr/blob/master/src/vm/excep.cpp#L7901

@jkotas @janvorli @RussKeldorph I'm wondering, is there a protocol for dealing with unhandled exceptions in modules external to the CLR itself but still part of the runtime, like in a standalone JIT?

**Comment by jkotas** [comment]
There is no protocol today. Standalone JIT has been responsible for its own internal exception handling.

**Comment by swgillespie** [comment]
@jkotas @janvorli 

I've been thinking about this (I hit it often when developing) and I've thought of two possible solutions, which differ philosophically on *who* is responsible for dealing with unhandled exceptions:

1. We could change the module check to include the module of a standalone GC, if one is loaded. This check is here: https://github.com/dotnet/coreclr/blob/master/src/vm/excep.cpp#L7901 and would be a check to see if the IP is in the standalone GC module. In this case, it's the EE's responsibility to handle exceptions leaking out of the GC and fail fast.
2. We could have the GC install its own vectored exception handler where it would do what `excep.cpp` does; check and see if the exception came from within the GC and, if it did, fail fast. In this case it's the GC's responsibility to ensure that exceptions never leak out of the GC module. (Alternatively, the GC could install try/catch blocks around all entrypoints).

The second option, while keeping the onus of exception handling on the GC, still relies on the EE's ability to turn hardware exceptions into SEH/C++ exceptions, especially on non-Windows platforms. This seems like trouble to me. If a hardware exception occurs in the GC and the EE dutifully turns it into a managed exception, we're in the same situation we are today where the EE's vectored exception handler attempts to allocate a managed object and deadlocks. If the GC *weren't* to rely on the EE to handle hardware exceptions, it would need to set up its own `SIGSEGV`, `SIGBUS`, `SIGFPE` signal handlers.

Does anyone have any particular aversion to option 1, or have any other ideas for this? Having the GC deadlock on unhandled exceptions is a huge pain for testing in general so I'm really hoping to fix this in a way that doesn't compromise exception handling performance in general.

**Comment by swgillespie** [comment]
cc @sergiy-k @Maoni0

**Comment by jkotas** [comment]
> option 1

Fine with me.

BTW: This is Windows-specific problem. The faults in the libclrgc.so should be turned into process abort on Unix already because of there is no exception handling interop on Unix.

**Comment by sergiy-k** [comment]
I'm fine with Option 1 too.
