### ISSUE TITLE
Add support for ARMv6

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/coreclr#14932]
@ivpadim commented on [Tue Nov 07 2017](https://github.com/dotnet/core/issues/1066)

# Include support for ARMv6

This was mentioned a while ago (issue [667](https://github.com/dotnet/core/issues/667)).
Is there a plan to support ARMv6? 
The only option right now is to install mono which works ok.

**Comment by shaggygi** [comment]
Referencing https://github.com/dotnet/coreclr/issues/10605

**Comment by jkotas** [comment]
Duplicate of #10605
