### ISSUE TITLE
IsSupported needs to return false for not-yet-implemented intrinsics

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#14930]
Repro:

```
using System;
using System.Runtime.Intrinsics.X86;

unsafe class My {

static void Main()
{
    Span<float> span1 = stackalloc float[4];
    span1[0] = 9.5f;
    span1[1] = 8.5f;
    span1[2] = 7.5f;
    span1[3] = 6.5f;

    if (Sse.IsSupported)
    {
        fixed (float* span1Ptr = &span1.DangerousGetPinnableReference())
        {
           var vector1 = Sse.Load(span1Ptr);
        }
    }
}

}
```

Actual result: Invalid program exception
Expected result: succeeds

It is very hard for folks to experiment with this otherwise. And we would have to do this before shipping .NET Core 2.1 for non-yet-implemented intrinsics anyway.

**Comment by eerhardt** [comment]
@fiigii - is this on your plate to tackle soon?  @danmosemsft mentioned that he'd like to see it fixed before the new year so people can start using these new hardware intrinsics.

**Comment by fiigii** [comment]
@eerhardt Originally, I planned to fix this issue before we ship the first subset of fully-implemented intrinsics to .NET Core 2.1. At this time (11/28/2017), only `Lzcnt` and `Popcnt` classes are fully-implemented, and SIMD classes are being implemented in progress https://github.com/dotnet/coreclr/pull/15244.

If you want it fixed now, I am okay to do it, but we would not be able to use certain enabled intrinsics (i.e. `Sse42.Crc32`). 

@jkotas any comment?

**Comment by jkotas** [comment]
We should fix it now. We prefer to be in the "ship-ready" state at all times.

**Comment by fiigii** [comment]
> We should fix it now. We prefer to be in the "ship-ready" state at all times.

Will do.

**Comment by fiigii** [comment]
I will submit this PR after https://github.com/dotnet/coreclr/pull/15244 gets merged, which attempts to avoid code conflict.
