### ISSUE TITLE
Tiered Jitting: Fix IL to native mapping for ETW

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#14947]
ETW emits a Native->IL mapping data for each jitted version and doing code review I can see that it probably isn't emitting the correct mapping. 

https://github.com/dotnet/coreclr/blob/master/src/vm/eventtrace.cpp#L6667

The signature of this method uses a MethodDesc and a ReJITID, neither of which is a strong enough identifier to isolate which version of tiered jitting code is being refered to. Without knowing which jitted instance to emit the IL->Native map for and knowing that the maps differ, at least some of the versions must be wrong.

**Comment by davmason** [comment]
Fixed with #15038
