### ISSUE TITLE
Build CoreCLR for iOS

### ISSUE THREAD

**Issue by GCCFeli** [dotnet/coreclr#14950]
Is there any plan to get an iOS build?

**Comment by jkotas** [comment]
iOS is no-JIT environment. All code has to be precompiled or interpreted. We do not have plans to make CoreCLR in no-JIT environments in foreseeable future. It would be a very large and expensive project. CoreCLR depends on JIT and ability to generate code dynamically at runtime pretty heavily.

https://github.com/dotnet/corert would be a better starting point for iOS .NET Core port. It has been specifically designed for the no-JIT environments. Or you can look at https://github.com/mono/mono/ that works on iOS already.

**Comment by RussKeldorph** [comment]
Please re-open if not sufficiently answered.
