### ISSUE TITLE
[JIT] ref return indexing into array runs more slowly than non-ref return

### ISSUE THREAD

**Issue by damageboy** [dotnet/coreclr#14957]
Basically trying to test the diffrence between:

Code is [here](https://github.com/damageboy/refslowness)

Plain vanilla indexing into array:
```c#
    public T this[int index]
    {
      [MethodImpl(MethodImplOptions.AggressiveInlining)]
      get
      {
#if DEBUG
        if (index < 0 || index >= Count)
          throw new ArgumentOutOfRangeException(nameof(index), $"Bad index {index} was supplied, Count is {Count}");
        if (Count != Capacity)
          throw new InvalidOperationException("The indexer may not be called before the buffer is full");
#endif

        return _buffer[(_head + index) % Capacity];
      }
    }
```

And a ref version of the same thing:
```c#
    public ref T this[int index]
    {
      [MethodImpl(MethodImplOptions.AggressiveInlining)]
      get
      {
#if DEBUG
        if (index < 0 || index >= Count)
          throw new ArgumentOutOfRangeException(nameof(index), $"Bad index {ind                            ex} was supplied, Count is {Count}");
        if (Count != Capacity)
          throw new InvalidOperationException("The indexer may not be called be                            fore the buffer is full");
#endif

        return ref _buffer[(_head + index) % Capacity];
      }
    }
```

# Non ref:
BenchmarkDotNet=v0.10.10, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.19)
Processor=Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), ProcessorCount=8
Frequency=2742186 Hz, Resolution=364.6726 ns, Timer=TSC
.NET Core SDK=2.0.2
  [Host]     : .NET Core 2.0.0 (Framework 4.6.00001.0), 64bit RyuJIT
  Job-THPAEG : .NET Framework 4.7 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2556.0

Jit=RyuJit  Platform=X64  Runtime=Clr
LaunchCount=1  TargetCount=10  WarmupCount=1

  Method |     Mean |     Error |    StdDev |      Min |      Max |
-------- |---------:|----------:|----------:|---------:|---------:|
 Indexer | 2.290 ns | 0.0441 ns | 0.0291 ns | 2.240 ns | 2.327 ns |
 
 # Ref
 
 
BenchmarkDotNet=v0.10.10, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.19)
Processor=Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), ProcessorCount=8
Frequency=2742186 Hz, Resolution=364.6726 ns, Timer=TSC
.NET Core SDK=2.0.2
  [Host]     : .NET Core 2.0.0 (Framework 4.6.00001.0), 64bit RyuJIT
  Job-LVZAAF : .NET Framework 4.7 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2556.0

Jit=RyuJit  Platform=X64  Runtime=Clr
LaunchCount=1  TargetCount=10  WarmupCount=1

  Method |     Mean |     Error |    StdDev |      Min |      Max |
-------- |---------:|----------:|----------:|---------:|---------:|
 Indexer | 3.468 ns | 0.1724 ns | 0.1141 ns | 3.361 ns | 3.683 ns |

As faras I can see, there is no real reason for why the ref-return version run slowly compared to the non-ref version...

In theory, ref-return should/could just do the pointer calculation and the caller would do the derefefrence just like the non ref version...

**Comment by mikedn** [comment]
I ran your code on a current CoreCLR build and the code generated for the test loop is identical:
```asm
G_M17058_IG03:
       4C8BD1               mov      r10, rcx
       4D8B5A08             mov      r11, gword ptr [r10+8]
       418BC0               mov      eax, r8d
       41034228             add      eax, dword ptr [r10+40]
       99                   cdq
       41F77A30             idiv     edx:eax, dword ptr [r10+48]
       413B5308             cmp      edx, dword ptr [r11+8]
       7318                 jae      SHORT G_M17058_IG05
       4863C2               movsxd   rax, edx
       C4C17B5844C310       vaddsd   xmm0, qword ptr [r11+8*rax+16]
       41FFC1               inc      r9d
       4183F90A             cmp      r9d, 10
       7CD4                 jl       SHORT G_M17058_IG03
```

**Comment by damageboy** [comment]
I just tried to recreate the results again and it doesn't happen anymore after getting the same results for 30 minutes of runs....
I'll try to recreate again....

**Comment by damageboy** [comment]
I went back to the same version, on the same machine and cannot re-create this right.
I feel stupid, but it actually happened in a repeatable way.

i guess my lesson here is to not submit these sort of issues before I have a disassembly that shows the issue...

I'm extremely sorry for wasting your time @mikedn

**Comment by mikedn** [comment]
> but it actually happened in a repeatable way.

Yeah, unfortunately benchmarking can produce weird results sometimes. When possible, always consult the generated assembly code. And even if the code is identical it's still possible to get surprises (e.g. identical code but with different alignment can produce different results).

> I'm extremely sorry for wasting your time

No problem.
