### ISSUE TITLE
The behavior of the "await stream.WriteAsync or await stream.ReadAsync" function is inconsistent for "async void" between donetcore1.0 and donetcore2.0

### ISSUE THREAD

**Issue by xflytang** [dotnet/coreclr#14956]
**Why the results differ between 1.0 and 2.0?**
test code:
``` C#
using System;
using System.Net;
using System.Net.Sockets;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        private Socket socket;
        private NetworkStream stream;

        async void connect()
        {
            IPAddress ipAddress;
            IPAddress.TryParse("127.0.0.1", out ipAddress);
            IPEndPoint ipEndPoint = new IPEndPoint(ipAddress, 2400);

            Console.WriteLine("connect 1");
            socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            await socket.ConnectAsync(ipAddress, ipEndPoint.Port);
            Console.WriteLine("connect 2");
        }
        byte[] buffer = new byte[] {
            0x11, 0x22, 0x33, 0x44
        };
        async void write()
        {
            Thread.Sleep(1000);
            Console.WriteLine("write 1");
            stream = new NetworkStream(socket);
            //await Task.Yield();
            await stream.WriteAsync(buffer, 0, buffer.Length);
            Thread.Sleep(1000);
            Console.WriteLine("write 2");
        }

        static void Main(string[] args)
        {
            Program program = new Program();
            program.connect();
            program.write();
            Console.WriteLine("Hello World!");

            while (true)
                Thread.Sleep(1000);
        }
    }
}

dotnetcore 1.0
connect 1
connect 2
write 1
Hello World!
write 2

dotnetcore 2.0
connect 1
connect 2
write 1
write 2
Hello World!

**Comment by xflytang** [comment]
![dotnet-process](https://user-images.githubusercontent.com/30112636/32597672-509e4834-c572-11e7-97ed-32541f538ba8.PNG)

**Comment by mikedn** [comment]
> Why the results differ between 1.0 and 2.0?

You seem to assume that async I/O operations always complete asynchronously and thus the completion code (Sleep and WriteLine) always run on a different thread than the thread that initiated the async I/O operation.

Async I/O purpose in life is to avoid blocking an existing thread for long periods of time, not to force the completion to run on a separate thread. If you want use appropriate means, e.g. replace Thread.Sleep with Task.Delay.

**Comment by xflytang** [comment]
My question is **"Why the results differ between 1.0 and 2.0?"**
Thread.Sleep is only to show the order of output

**Comment by stephentoub** [comment]
Because it's much more likely that socket operations in .NET Core 2.0 will complete synchronously.

**Comment by mikedn** [comment]
> My question is "Why the results differ between 1.0 and 2.0?"

Well, if you want to know the exact change that caused this then try this PR: https://github.com/dotnet/corefx/pull/3710

As the description in that PR states, the 1.0 `NetworkStream` did not override `ReadAsync`/`WriteAsync` and this the default implementation provided by `Stream` was used. The default implementation emulates async I/O by executing sync I/O in the thread pool. Async I/O operations that are emulated like this can never complete synchronously like real async I/O can do.

**Comment by xflytang** [comment]
@mikedn thanks
