### ISSUE TITLE
Imperative native Dll import API

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#14968]
The managed code often wants to have a strong control where to load native dlls from. For example, our own code in System.Drawing.Common: https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/src/System/Drawing/GdiplusNative.Unix.cs#L22 . The discussion in https://github.com/dotnet/coreclr/issues/930 has more example of similar use cases.

We should consider adding imperative native Dll loading APIs to make this easier.

**Comment by jkotas** [comment]
cc @russellhadley

**Comment by tmds** [comment]
@jkotas linking some related issues:
https://github.com/dotnet/corefx/issues/16123
https://github.com/dotnet/coreclr/issues/8721

**Comment by jkotas** [comment]
Related proposal: https://github.com/dotnet/corefx/issues/17135

**Comment by migueldeicaza** [comment]
Ouch the code for loading GDI+ looks obscene, and I bet the resulting code is not very pleasant.

My vote of course is for .NET to adopt the existing dllmap file that Mono uses, which would remove that ugly code.

**Comment by 4creators** [comment]
@migueldeicaza @jkotas 
It seems that https://github.com/dotnet/corefx/issues/17135 and Mono dllmap approach are to some extent complementary and could solve some native dll loading problems.

**Comment by Auersberg** [comment]
Dllmap? Nope. 
https://github.com/dotnet/coreclr/issues/930

**Comment by jkotas** [comment]
https://github.com/dotnet/corefx/issues/17135 is pretty close to what this should be. Let's use that issue to track this.
