### ISSUE TITLE
How to integrate CoreClr Binaries manually in a Linux System

### ISSUE THREAD

**Issue by philippweidhas** [dotnet/coreclr#15004]
Hallo .Net Core Community,

im looking for a way to integrate my selfbuild Binaries of coreclr and corefx in an UbuntuSystem. I build the binaries for x86 to get .Net Core running on a x86 Ubuntu System. Now i need a guide where and how to place the binaries in this UbuntuSystem. Can someone give me a instruction or a link to an guide wich i was not able to find.

Greetings
Philipp

**Comment by jkotas** [comment]
cc @janvorli

**Comment by janvorli** [comment]
@philippweidhas I would recommend looking at how the .deb packages for Ubuntu x64 are formed and use locations based on that.
See e.g. the https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-ubuntu.14.04-x64.deb. I've extracted the md5sums file from it for you which shows the structure quite nicely:
https://gist.github.com/janvorli/ea618cf23d6a305b4d3f7a5542742248

**Comment by janvorli** [comment]
@philippweidhas can this issue be closed or do you have more questions on this matter?

**Comment by RussKeldorph** [comment]
Feel free to re-open if not sufficiently answered.
