### ISSUE TITLE
AppDomain::CacheStringsForDAC missing implementation

### ISSUE THREAD

**Issue by FSou1** [dotnet/coreclr#15001]
I've just found that an implementation of the method `AppDomain::CacheStringsForDAC` is [missing](https://github.com/dotnet/coreclr/blob/56ec8cb6dcbb0e7a844f2f3e37b646bb57a737db/src/vm/appdomain.cpp#L6425-L6439) and wasn't pretty sure if it's ok.

Would you mind to let me know any explanation about the current state of this method?

**Comment by jkotas** [comment]
It used to have code specific to .NET Framework assembly loader
https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/vm/appdomain.cpp#L8054. It is not needed in .NET Core. It can be deleted, as well as the unused fields that it used to refer to (`m_applicationBase`, `m_privateBinPaths` and `m_configFile`). Are you interested in submitting PR?

**Comment by FSou1** [comment]
The entire method and properties could be safely deleted? I'm defenetly interesting in submitting such kind of PR :)

**Comment by FSou1** [comment]
Ok, i'm going to be the responsible of this PR

**Comment by FSou1** [comment]
I've noticed that `m_applicationBase`, `m_privateBinPaths` and `m_configFile` used within next methods: 

https://github.com/dotnet/coreclr/blob/27a25bd37fa1fe6201c27709b1884e1b328f8beb/src/debug/daccess/request.cpp#L2629
https://github.com/dotnet/coreclr/blob/27a25bd37fa1fe6201c27709b1884e1b328f8beb/src/debug/daccess/request.cpp#L2673
https://github.com/dotnet/coreclr/blob/27a25bd37fa1fe6201c27709b1884e1b328f8beb/src/debug/daccess/request.cpp#L2584

I think those lines could be also safely removed. Right?

Otherwise my suggestion is to update them like this (but does it make any sense?):

```
 HRESULT
ClrDataAccess::GetPrivateBinPaths(CLRDATA_ADDRESS appDomain, int count,
                                  __out_z __inout_ecount(count) wchar_t *paths, unsigned int *pNeeded)
{
    if (appDomain == NULL || (paths == NULL && pNeeded == NULL) || (paths != NULL && count == 0))
        return E_INVALIDARG;

    SOSDacEnter();
    AppDomain* pAppDomain = PTR_AppDomain(TO_TADDR(appDomain));

    // Turn from bytes to wide characters
    if ((PTR_BaseDomain(pAppDomain) == PTR_BaseDomain(SharedDomain::GetDomain())) ||
        (PTR_BaseDomain(pAppDomain) == PTR_BaseDomain(SystemDomain::System())))
    {
        // Shared domain and SystemDomain don't have this field.
        if (pNeeded)
            *pNeeded = 1;

        if (paths)
            paths[0] = 0;

        hr = S_OK;
    }

    SOSDacLeave();
    return hr;
}
```

**Comment by jkotas** [comment]
> I think those lines could be also safely removed. Right?

Right.

> Otherwise my suggestion is to update them like this (but does it make any sense?):

You can just make the method return `E_FAIL` with a comment that it is not supported on CoreCLR.
