### ISSUE TITLE
嵌入coreclr的一些问题

### ISSUE THREAD

**Issue by JimsC** [dotnet/coreclr#15019]
我想做一个东西，想把coreclr嵌入到我自己的应用程序中，然后运行一些c#代码，我想像lua那样可以绑定一些c/c++的方法让c#来调用，但是好像没有相关的资料
我在网上查到的资料都是c#通过dllimport来载入动态链接库的方式来调用c/c++的方法，但是我嵌入coreclr后不想再调用动态链接库的方法，而是调用嵌入了coreclr的应用程序本身的一些方法
我想知道是否能够目前coreclr是否能实现？谢谢了！

**Comment by huoyaoyuan** [comment]
请在国际GitHub项目上使用英文。
Please use English in international GitHub project.
##### Translation in brief:
I want to host coreclr in my application, run some C# code, and call C++ methods from C#.
I searched and found documents about using `DllImport` to call into dynamic libraries, but I want to call into my host application, not another dll file.
Can I do this using coreclr now?

**Comment by JimsC** [comment]
So embarrassed!

let me use my poor English and google translate try explain the issue

I want to  embed coreclr into my own application, and then run some c # code, and invoke c/c++ code from c#, some  language, like lua, can bind some c/c++ method , then lua code can invoke c/c++ code, but it seems like that c# cannot do that.

I found the information on the Internet , dllmport can make c# code invoke c/c++ code with  load dynamic link library , but I do not want to load  dynamic link library , just call into my own application

I want know  is there some way to achieve my purpose?

**Comment by RussKeldorph** [comment]
Does [Marshal.GetDelegateForFunctionPointer](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getdelegateforfunctionpointer?view=netcore-2.0#System_Runtime_InteropServices_Marshal_GetDelegateForFunctionPointer_System_IntPtr_System_Type_) do what you want?

**Comment by JimsC** [comment]
yes , it is a way to achieve my purpose.

last day I think a another way 

I can make a simple application, but most code in dynamic link library, I didn't do it , I will try it later, I think it will be success, if not, I will try the Marshal.GetDelegateForFunctionPointer

thank you!

这个方法能达到我的目的
在昨天提出这个issue后，我想到了另一种方法，我可以做一个简单的应用程序，但是大部分的实现都放在动态链接库里面，这样就可以用dllimport，之前我对动态链接库有一些误会（比如我以为对一个动态链接库的多次载入会导致有多个实现，实际上不是的，每次载入都会关联到全局符号表，下次载入的时候全局符号表已经有了，就不会载入了）
之后我会先用我的方法尝试下，如果不行，我再用Marshal.GetDelegateForFunctionPointer
谢谢！
