### ISSUE TITLE
RyuJIT should eliminate unnecessary try/finally

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#1505]
If the `finally` block in a `try`/`finally` pair does nothing then they can be eliminated. Such `finally` blocks are produced when `foreach` is used with BCL collections such as `List<T>` because their enumerators have empty Dispose methods. The JIT compiler inlines the Dispose method and the callsite and null check are eliminated but the `try`/`finally` is left behind.

Also, I'm not very familiar with exception handling but it seems that it should be possible to inline the finally handler if it's small. The handlers generated when `foreach` is used with `IEnumerable<T>` consist of a null check and a call - `if (x != null) x.Dispose();`. Incidentally this code isn't even optimized, the generated code contains a redundant load and null check:

```
       488B4DF0             mov      rcx, gword ptr [rbp-10H]
       4885C9               test     rcx, rcx
       7413                 je       SHORT G_M65129_IG11
       488B4DF0             mov      rcx, gword ptr [rbp-10H]
       49BB38000601FC7F0000 mov      r11, 0x7FFC01060038
       3909                 cmp      dword ptr [rcx], ecx
       41FF13               call     qword ptr [r11]System.IDisposable:Dispose():this
```

It's unfortunate that such a common code pattern isn't better handled.

**Comment by BruceForstall** [comment]
One optimization JIT64 did that RyuJIT doesn't do is "finally cloning" -- essentially inlining the contents of the "finally" block into the "main function" immediately after the "try" that requires "finally" handling. This improves the non-exceptional path by not requiring call/prolog/epilog/return code. It still requires marking the inlined region very carefully to handle potential exceptions properly. It also increases code size. We'd like to do that at some point. There are lots of other "optimization in the presence of exception handling" cases we'd like to improve, especially around register allocation, inlining, etc.

**Comment by VSadov** [comment]
I believe "empty finally" may deserve to be handled before more general EH optimizations are implemented.
I think it is a fairly common case with  struct enumerators like List<T> and also, being a trivial case, perhaps it is easier to handle than more general scenarios.

**Comment by mikedn** [comment]
> I think it is a fairly common case with struct enumerators like List

IMO those enumerators should have explicitly implemented Dispose but that can't be changed now so it's up to the compilers to clean up. I suppose the C# compiler could do this as well by special casing those enumerators but that feels kind of ugly.

**Comment by danmosemsft** [comment]
@AndyAyersMS @mikedn what about empty try? There are plenty in CoreFX I believe as a leftover from thread abort support. They aren't removed yet.

Some are nested, eg

https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs#L453

```
  452                  bool timerIsNotDisposed;
  453:                 try { }
  454                  finally
  455                  {
  ...
  615                  try
  616                  {
  617:                     try { }
  618                      finally
  619                      {
  ...
  987                          try
  988                          {
  989:                             try { }
  990                              finally
  991                              {
```

Do those need special treatment also?

**Comment by AndyAyersMS** [comment]
Yeah, these may be something the jit needs to clean up better -- let me take a look. Pointers to other examples welcome.

**Comment by AndyAyersMS** [comment]
Some experimenting shows that the current CSC will eliminate `try {} finally {}` even when such constructs are nested. But an empty try with a non-empty finally (as in the examples above) is not simplified.

Haven't looked at a `try {} catch` example yet.

It should be fairly simple to construct a recognizer for empty-try non-empty-finallys and see if they're common enough that the jit should optimize them away.

**Comment by danmosemsft** [comment]
@AndyAyersMS if you grep the CoreFX repo for "try { }" you should find 23 matches. That's with a space between curlies, there may be other forms

**Comment by danmosemsft** [comment]
I created an issue https://github.com/dotnet/coreclr/issues/8924
