### ISSUE TITLE
MemoryStream.CopyToAsync calls destination.Write / WriteAsync with count=0 when there's nothing to copy

### ISSUE THREAD

**Issue by davidni** [dotnet/coreclr#15057]
`MemoryStream` provides a specialized implementation of `CopyToAsync` that avoids extra allocations and buffer copies by writing the entire buffer in one go. Makes sense.

When there are no bytes to copy in the source stream, however, it should bail out early and do nothing. That would be the consistent thing to do to match the behavior of the base implementation `Stream.CopyToAsync` (`Stream.CopyToAsync` would call `ReadAsync,` which would return `0`, and that would be the end of it -- no calls to `WriteAsync`). Instead, it currently calls `destination.WriteAsync(..., count: 0)`.

The current behavior is unexpected, inconsistent, and gives rise to other problems when the destination stream cannot deal with `0`-length writes properly (see [aspnet/HttpSysServer #417](https://github.com/aspnet/HttpSysServer/issues/417) which I just filed).

Note: I don't think this problem is unique to .NET Core, and other versions of the .NET Framework are also affected.

**Comment by Tragetaschen** [comment]
I just stumbled over this on full .NET framework (`<TargetFramework>net47</TargetFramecork>`):
`await memoryStream.CopyToAsync(serialPort.BaseStream)` just hung when `memoryStream.Length == 0`
