### ISSUE TITLE
Rethink the Microsoft.NETCore.ILAsm NuGet package

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/coreclr#15059]
It's really unfortunate that to consume ilasm.exe from the Microsoft.NETCore.ILAsm NuGet package, we need to download 24 MB of garbage* that is Microsoft.NETCore.Runtime.CoreCLR because ILAsm depends on `MetaDataGetDispenser` API exported from coreclr.dll. We should explore static linking or a different factoring of the nugets.

\* If the only thing you need is a working ilasm.exe and don't care about the 20+ MB of System.Private.CoreLib, DAC, SOS, JIT, host, etc.

**Comment by MichalStrehovsky** [comment]
Motivated by dotnet/buildtools#1806

**Comment by jaredpar** [comment]
Just want to give my 👍 to this bug. This is so painful for us to maintain in Roslyn. We just want the simple ilasm -> il transformation. Keeping the runtime in sync here is a tax. I'd love it if the package and deployment was much simpler.

**Comment by jaredpar** [comment]
Curious: what is the cost of doing this? Most recently I've spent two days trying to deploy ILASM. When I think back about the total time I've spent just deploying this simple native tool I just get sad. Maybe my time is better spent just fixing this.

**Comment by AaronRobinsonMSFT** [comment]
@jaredpar I think this should be a straight forward problem to solve. On Windows we are linking against `coreclr`, but not on Unix so I assume if we play with the linker flags a bit we could get this to just work.

```
if(CLR_CMAKE_PLATFORM_UNIX)
  target_link_libraries(ilasm
    ${ILASM_LINK_LIBRARIES}
    ceefgen
    unixcoreclrloader
    utilcodestaticnohost
    mscorrc_debug
    coreclrpal
    palrt
  )

  # FreeBSD and NetBSD implement dlopen(3) in libc
  if(NOT CMAKE_SYSTEM_NAME STREQUAL FreeBSD AND NOT CMAKE_SYSTEM_NAME STREQUAL NetBSD)
    target_link_libraries(ilasm
      dl
    )
  endif(NOT CMAKE_SYSTEM_NAME STREQUAL FreeBSD AND NOT CMAKE_SYSTEM_NAME STREQUAL NetBSD)
else()
  target_link_libraries(ilasm
    ${ILASM_LINK_LIBRARIES}
    coreclr
    ole32
    oleaut32
    shell32
  )
endif(CLR_CMAKE_PLATFORM_UNIX)
```

**Comment by AaronRobinsonMSFT** [comment]
Oh.. nevermind. CoreCLR dynamically loaded instead. Boo...

**Comment by MichalStrehovsky** [comment]
As of #25144, `xcopy ilasm.exe a:\path\where\you\want\it` is enough to get a working ilasm!

**Comment by jkoritzinsky** [comment]
I'll take a look at updating the ilasm and ildasm packages as well as the Microsoft.NET.Sdk.IL now that they're self-contained.

**Comment by jkoritzinsky** [comment]
See #25930 for the updates to the packages/sdk.
