### ISSUE TITLE
jit\gtstructs.h Line: 56 assert(found)

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#15056]
There are 3 regressions with jitstress=2 after #14945:
```
JIT_Performance._CodeQuality_Roslyn_CscBench_CscBench_._CodeQuality_Roslyn_CscBench_CscBench_cmd
JIT_Regression._JitBlue_DevDiv_461649_DevDiv_461649_DevDiv_461649_._JitBlue_DevDiv_461649_DevDiv_461649_DevDiv_461649_cmd
managed_Compilation._Compilation_Compilation_._Compilation_Compilation_cmd
```
[Ci run.](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitstress2_prtest/64/#showFailuresLink)

**Comment by sandreenko** [comment]
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
This fails on x64 with both jitstress=1 and jitstress=2:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitstress2_prtest/63/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitstress1_prtest/37/
