### ISSUE TITLE
HashCode improvement for String

### ISSUE THREAD

**Issue by neurospeech** [dotnet/coreclr#1506]
1. Cache HashCode, so HashCode is not calculated at every subsequent calls, this is important for following case
2. Check A.HashCode != B.HashCode in String.Equals() instead of A.Length != B.Length
3. I hope switch statement can take advantage of HashCode matching

**Comment by mikedn** [comment]
> Check A.HashCode != B.HashCode in String.Equals() instead of A.Length != B.Length

If the hashcode hasn't been computed yet it has to be computed and that's potentially more expensive than just doing a normal string equality check. Or if the hashcode hasn't been computed fallback to using Length. Might be useful in some cases but I would speculate that it won't useful often enough. In many cases at least one of the strings will not have its hashcode already computed as it was just created (from user input, file parsing, database queries etc.)

> I hope switch statement can take advantage of HashCode matching

String switches can be implemented using hashtables or a bunch of `if` statements. Roslyn uses the second approach and if the number of cases is relatively high then it precomputes the switch expression hashcode to avoid unnecessary string equality tests.

**Comment by neurospeech** [comment]
What if hashcode is created at time of creating (allocating) strings, in for operation whenever it is doing memory copy or spliting strings or in StringBuilder, it can keep copy of hashcode whenever string is updated.

**Comment by RichiCoder1** [comment]
I can't speak for the dotnet team, but I don't think they'd be for either caching hashcodes, or generating then at string generation time. The latter goes against doing as little as possible when creating strings and might add unnecessary complexity, and the former would add a lot of unnecessary memory pressure, especially in string heavy systems. Hashcodes are relatively cheap to compute, too, in the grand scheme of things.

**Comment by GeirGrusom** [comment]
Caching string hashcodes would break code that performs unsafe operations on strings.

**Comment by mikedn** [comment]
> What if hashcode is created at time of creating (allocating) strings, in for operation whenever it is doing memory copy or spliting strings or in StringBuilder, it can keep copy of hashcode whenever string is updated.

Well, not every string needs to be tested for equality  with another string or used as a hashtable key so computing the hashcode upfront is unlikely to be beneficial. To me this looks like the good optimization done in the wrong place. The framework has no idea how a string will be used - if it will be equality tested 0, 1 or more times - so such an optimization may end up being a de-optimization in many cases. This is the type of optimization that can be implemented on a case by case basis:
* As already, mentioned Roslyn does this for switches with many cases
* `Dictionary<K, V>` caches the key hashcode when a key/value pair is added
* `XmlReader` makes use of custom string interning which allows transforming some string equality tests into reference equality and additionally it minimizes string allocation

**Comment by AlexGhiondea** [comment]
I agree with @mikedn. The Framework has no way of knowing if a string will be compared with another string and so computing and storing the hash code can actually hurt performance.

**Comment by neurospeech** [comment]
Ok I get it, I was only concerned about using HashCode in switch, but as if Roslyn compiler uses hash code, that should be better.
