### ISSUE TITLE
Tests seem to time out before the default timeout expires

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#15072]
According to:
https://github.com/dotnet/coreclr/blob/master/tests/src/Common/Coreclr.TestWrapper/CoreclrTestWrapperLib.cs#L99
The default timeout should be 10 minutes. It doesn't look like the following tests override that default timeout, and yet they seem to be timing out in less than or around one minute in the CI. From under tests/src/baseservices/threading/generics/Monitor:

EnterExit14 and waitone2:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress2_jitstressregs0x1000_prtest/8/

EnterExit14:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress2_jitstressregs2_prtest/9/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress2_jitstressregs3_prtest/9/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_tailcallstress_prtest/21/

EnterExit14, EnterExit12:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress2_jitstressregs4_prtest/9/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstressregs8_prtest/15/

**Comment by RussKeldorph** [comment]
@kouvel Can you be more specific about what you're seeing?  In almost all cases you linked, the test results indicate the test timed out at 10 min.  For example, at https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress2_jitstressregs2_prtest/9/testReport/baseservices_threading/_generics_Monitor_EnterExit14_EnterExit14_/_generics_Monitor_EnterExit14_EnterExit14_cmd/, I see: 
![image](https://user-images.githubusercontent.com/15160879/32985478-e1e519a8-cc70-11e7-8ee5-e4a90fae3ff2.png)

Where are you seeing less than our around minute?

The one exception is the waitone2 test here: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress2_jitstressregs0x1000_prtest/8/ which seems to have failed, not timed out.

**Comment by kouvel** [comment]
Ah ok, I misinterpreted the following:

```
17:19:17          "D:\j\workspace\x86_arm_altji---b796a440\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" EnterExit14.exe
...
17:19:32   cmdLine:D:\j\workspace\x86_arm_altji---b796a440\bin\tests\Windows_NT.x86.Checked\baseservices\threading\generics\Monitor\EnterExit14\EnterExit14.cmd Timed Out
```

And thought the timeout was for the test. It looks like the 10 minute timeout is for all tests and it just happens to be timing out during this test.

```
17:08:16   xUnit.net MSBuild Runner (32-bit .NET 4.0.30319.42000)
17:12:39     Discovering: baseservices.threading.XUnitWrapper
```

It took 4 minutes after xunit was started to start discovering the first set of tests. I guess we may need to increase the timeout when running on these arm machines.

```
17:08:12 RUNTEST: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\\..\..\MSBuild\15.0\Bin\MSBuild.exe" "D:\j\workspace\x86_arm_altji---b796a440\tests\runtest.proj" /p:Runtests=true /clp:showcommandline /nologo /nodeReuse:false  /p:Platform=x86 /maxcpucount /fileloggerparameters:Verbosity=normal;LogFile="D:\j\workspace\x86_arm_altji---b796a440\tests\..\bin\Logs\TestRunResults_Windows_NT__x86__Checked.log";Append /fileloggerparameters1:WarningsOnly;LogFile="D:\j\workspace\x86_arm_altji---b796a440\tests\..\bin\Logs\TestRunResults_Windows_NT__x86__Checked.wrn" /fileloggerparameters2:ErrorsOnly;LogFile="D:\j\workspace\x86_arm_altji---b796a440\tests\..\bin\Logs\TestRunResults_Windows_NT__x86__Checked.err" /consoleloggerparameters:Summary /verbosity:minimal
17:08:16   xUnit.net MSBuild Runner (32-bit .NET 4.0.30319.42000)
17:12:39     Discovering: baseservices.threading.XUnitWrapper
...
17:19:17          "D:\j\workspace\x86_arm_altji---b796a440\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" EnterExit14.exe
...
17:19:32   cmdLine:D:\j\workspace\x86_arm_altji---b796a440\bin\tests\Windows_NT.x86.Checked\baseservices\threading\generics\Monitor\EnterExit14\EnterExit14.cmd Timed Out
17:19:32         Test Harness Exitcode is : -100
17:19:32         
17:19:32   To run the test:
17:19:32   > set CORE_ROOT=D:\j\workspace\x86_arm_altji---b796a440\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
17:19:32   > D:\j\workspace\x86_arm_altji---b796a440\bin\tests\Windows_NT.x86.Checked\baseservices\threading\generics\Monitor\EnterExit14\EnterExit14.cmd
17:19:32   
17:19:32         Expected: True
17:19:32         Actual:   False
17:19:32           D:\j\workspace\x86_arm_altji---b796a440\bin\tests\Windows_NT.x86.Checked\TestWrappers\baseservices.threading\baseservices.threading.XUnitWrapper.cs(2977,0): at baseservices_threading._generics_Monitor_EnterExit14_EnterExit14_._generics_Monitor_EnterExit14_EnterExit14_cmd()
```

**Comment by kouvel** [comment]
Filed https://github.com/dotnet/coreclr/issues/15098 for the waitone2 failure
