### ISSUE TITLE
mscorlib.dll missing / cross-build arm64 / Debian

### ISSUE THREAD

**Issue by outbackdingo** [dotnet/coreclr#15078]
[mscorlib.txt](https://github.com/dotnet/coreclr/files/1483840/mscorlib.txt)
the following guide states

https://github.com/dotnet/coreclr/blob/master/Documentation/building/cross-building.md

Build mscorlib on Ubuntu

The following instructions assume you are on a Linux machine such as Ubuntu 14.04 x86 64bit.

To build mscorlib for Linux, run the following command:

    lgs@ubuntu ~/git/coreclr/ $ build.sh arm64 debug verbose -rebuild
The output is at bin/Product/.arm.Debug/mscorlib.dll.

    lgs@ubuntu ~/git/coreclr/ $ file ./bin/Product/Linux.arm.Debug/mscorlib.dll 
    ./bin/Product/Linux.arm.Debug/mscorlib.dll: PE32 executable (DLL) 
    (console) ARMv7 Thumb Mono/.Net assembly, for MS Windows

however..... upon completion we see no mscorlib.dll as st

ated
ls -al bin/Product/Linux.arm64.Debug/
total 338856
drwxr-xr-x 9 root root     4096 Nov 17 16:03 .
drwxr-xr-x 4 root root     4096 Nov 17 15:39 ..
drwxr-xr-x 2 root root     4096 Nov 17 15:32 bin
-rwxr-xr-x 1 root root   154984 Nov 17 15:41 coreconsole
-rwxr-xr-x 1 root root   159336 Nov 17 15:41 corerun
-rwxr-xr-x 1 root root   635152 Nov 17 15:42 createdump
-rwxr-xr-x 1 root root 47155856 Nov 17 15:42 crossgen
drwxr-xr-x 2 root root     4096 Nov 17 15:32 gcinfo
drwxr-xr-x 2 root root     4096 Nov 17 15:32 IL
-rwxr-xr-x 1 root root  8016552 Nov 17 15:42 ilasm
-rwxr-xr-x 1 root root  7279696 Nov 17 15:42 ildasm
drwxr-xr-x 2 root root     4096 Nov 17 15:32 inc
drwxr-xr-x 2 root root     4096 Nov 17 15:42 lib
-rwxr-xr-x 1 root root  3284088 Nov 17 15:41 libclrgc.so
-rwxr-xr-x 1 root root 25496632 Nov 17 16:03 libclrjit.so
-rwxr-xr-x 1 root root 96415384 Nov 17 15:42 libcoreclr.so
-rwxr-xr-x 1 root root  1760368 Nov 17 15:24 libcoreclrtraceptprovider.so
-rwxr-xr-x 1 root root  5596480 Nov 17 15:41 libdbgshim.so
-rwxr-xr-x 1 root root 58491568 Nov 17 15:42 libmscordaccore.so
-rwxr-xr-x 1 root root 15297584 Nov 17 15:42 libmscordbi.so
-rwxr-xr-x 1 root root 25244208 Nov 17 16:03 libprotononjit.so
-rwxr-xr-x 1 root root   418544 Nov 17 15:42 libsosplugin.so
-rwxr-xr-x 1 root root  3383536 Nov 17 15:42 libsos.so
-rw-r--r-- 1 root root  8837536 Nov 17 15:42 libsuperpmi-shim-collector.so
-rw-r--r-- 1 root root  8680000 Nov 17 15:42 libsuperpmi-shim-counter.so
-rw-r--r-- 1 root root  8659824 Nov 17 15:42 libsuperpmi-shim-simple.so
-rw-r--r-- 1 root root  1008236 Nov 17 15:41 libSystem.Globalization.Native.a
drwxr-xr-x 3 root root     4096 Nov 17 15:32 Loader
-rwxr-xr-x 1 root root  8679352 Nov 17 15:42 mcs
drwxr-xr-x 2 root root     4096 Nov 17 16:03 PDB
-rw-r--r-- 1 root root    65869 Nov 17 15:14 sosdocsunix.txt
-rw-r--r-- 1 root root    16384 Nov 17 15:32 SOS.NETCore.dll
-rw-r--r-- 1 root root     6264 Nov 17 15:32 SOS.NETCore.pdb
-rwxr-xr-x 1 root root  8706608 Nov 17 15:42 superpmi
-rwxr-xr-x 1 root root   517416 Nov 17 15:41 System.Globalization.Native.so
-rw-r--r-- 1 root root  2927616 Nov 17 15:32 System.Private.CoreLib.dll

**Comment by jkotas** [comment]
This is documentation bug. All references to mscorlib.dll should be replace with System.Private.CoreLib.dll.

**Comment by outbackdingo** [comment]
So where has mscorlib.ddll gone o??? i have an app tha says cant find
mscorlib.dll in linux arm64

**Comment by jkotas** [comment]
mscorlib is built in github.com/dotnet/corefx repo.
