### ISSUE TITLE
Unix Build and Test failing in CI frequently

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#15096]
The error is:
```
Unhandled Exception: System.TypeLoadException: Could not load type 'System.MemoryExtensions' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

The problem is that we copy the CoreFX build straight from CoreFX jobs, but the CoreFX job for CentOS is not running anymore and we get stale build (on some CI machines at least).

**Comment by jkotas** [comment]
@jashook What should be done about this?

**Comment by jkotas** [comment]
It seems to be affecting all Unix builds. E.g. Ubuntu leg in https://github.com/dotnet/coreclr/pull/15091 failed with this error.

**Comment by RussKeldorph** [comment]
@jkotas @rartemev created build-test.sh, which should make Unix package restore more similar to Windows.  At the time that script was created, msbuild was too slow, but recent tools updates have made performance acceptable on Linux (we hope).  @jashook is working to get it deployed in CI, which involves getting rid of the "flow" jobs for x64 and building everything on Unix.  I believe that's the first step to resolving this issue.

@wtgodbe

**Comment by jkotas** [comment]
I agree that getting rid of the "flow" jobs is goodness. Do you believe that it is going to get done in a few days?

If not, can we patch the existing flow jobs to make the CI green? It is not good to have failing jobs in CI for extended time. Something have changed in the CI setup very recently that they started failing frequently - when you look at 10 most recent active PRs, all 10 of them are red because of this issue.

**Comment by jashook** [comment]
Looking into this.

**Comment by jashook** [comment]
>I agree that getting rid of the "flow" jobs is goodness. Do you believe that it is going to get done in a few days?

We should be able to move to a dependency restore system closer to what we already use in build pipeline and in build-test fairly quickly. I think that should be a relatively fast change to unblock us.

**Comment by jashook** [comment]
Starting on a change.

**Comment by jkotas** [comment]
@jashook Thank you!

**Comment by RussKeldorph** [comment]
@jkotas I misinterpreted your description.  I thought you were referring to the long term issue of fragility in the way CoreFx is consumed on Unix that caused occasional periods of spurious failures that worked themselves out once the repos both moved past the break.  If you are describing a problem that is not going to go away on its own, that may require a different immediate action, though I don't know enough to say for sure.  We will look into it.

**Comment by jashook** [comment]
Prototyping a change which uses build-test to create the coreoverlay directory in dev/unix_test_workflow.

**Comment by jkotas** [comment]
@jashook Do you have any update on the progress - when can we expect the fix? This is pretty painful to deal with.

**Comment by jashook** [comment]
Currently I have a few incremental changes in dev/unix_test_workflow. Pretty happy with it minus some issues with overwriting native bits correctly.

**Comment by ahsonkhan** [comment]
@jashook, I see #15230 got merged. Has the issue been resolved?

**Comment by jashook** [comment]
This issue is still open, I have a few changes being tested in a different branch: dev/unit_test_workflow.

**Comment by jkotas** [comment]
@jashook Thank you!
