### ISSUE TITLE
Unable to use attributes

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/coreclr#1510]
Hi,

I have an assembly project. Here's it's *project.json* file:

    {
      "version": "1.0.0-*",
      "description": "Rnet Class Library",
      "authors": [ "Shimmy" ],
      "tags": [ "" ],
      "projectUrl": "",
      "licenseUrl": "",
      "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
      },
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23225",
        "System.Xml.XmlSerializer": "4.0.11-beta-23225"
      }
    }

I defined the following class in the project:

    using System;
    using System.Xml.Serialization;

    namespace Rnet
    {
      [XmlRoot]
      public class Customer
      {
        public string FirstName { get; set; }
        public string LastName { get; set; }
      }
    }

When I try to build I get the following error:
> Error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

I tried adding `"dependencies": { "System.Runtime": "4.0.21-beta-23225" }` under `dnx451` in the *project.json* file, but then I get a bunch of errors similar to the following:

>The type 'DateTime' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by weshaggard** [comment]
I believe you only need to add the System.Runtime dependency on the dnxcore50 section.

**Comment by weshaggard** [comment]
@weitzhandler I assume you got past this problem so I'm closing. If that isn't the case please provide some further information.
