### ISSUE TITLE
dotnet publish with "--self-contained" and "--runtime" doesn't respect "--output" parameter

### ISSUE THREAD

**Issue by lyze237** [dotnet/coreclr#15111]
Hello,

I'm currently trying to publish into the `build/publish` directory but when I run the `dotnet publish` command together with `--self-contained` and `--runtime` it won't respect the `--output` parameter:

    dotnet.exe publish "./Solution.sln" --output "D:/Sources/Solution/build/publish" --runtime win-x64 --self-contained

Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Project-> D:\Sources\Solution\Project\bin\Debug\netcoreapp2.0\win-x64\project.dll
  Project -> D:\Sources\Solution\build\publish\

The directorys content after running the command:

**D:/Sources/Sources/Project/bin/Debug/netcoreapp2.0/win-x64**

    hostpolicy.dll  project.deps.json  project.exe  project.runtimeconfig.dev.json
    hostfxr.dll    project.dll        project.pdb  project.runtimeconfig.json

**D:\Sources\Solution\build\publish**

Literally all dlls of the framework and dependencies but no exe.

Could somebody help?

**Comment by jkotas** [comment]
This issue was moved to dotnet/cli#8087
