### ISSUE TITLE
Question: Why C# doesn't allow passing parameter as final?

### ISSUE THREAD

**Issue by AhmedRagheb** [dotnet/coreclr#15139]
In Java, you can mark variable as final 
```
public void GetById(final int id)
{
    // Get by id and don't change id 
}
```
Why this is not allowed in C#. 
There are many questions like this in Stackoverflow but I prefer to ask here to get the right reason behind that, not just theoretical answers.

**Comment by mikedn** [comment]
This is a question/suggestion for the csharplang repo, not coreclr. I'm pretty sure they already have some discussions around allowing `readonly` to be used for local variables.

**Comment by AhmedRagheb** [comment]
Ok, I will close it and move it there.
Thanks,
