### ISSUE TITLE
JIT test errors on Unix when changing decimal to explicit layout

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#15159]
As part of unifying decimal's formatting code between coreclr and corert, @jkotas suggested I make decimal have an explicit layout, as it is in corert.  In doing so, a handful of JIT tests started failing:
```
JIT.Directed.coverage.oldtests.lclfldadd_cs_r.lclfldadd_cs_r
JIT.Directed.perffix.primitivevt.mixed1_cs_ro.mixed1_cs_ro
JIT.Methodical.fp.exgen.1000w1d_cs_r.1000w1d_cs_r
JIT.Methodical.fp.exgen.1000w1d_cs_ro.1000w1d_cs_ro
JIT.Methodical.fp.exgen.1000w1d_cs_do.1000w1d_cs_do
JIT.Methodical.fp.exgen.1000w1d_cs_d.1000w1d_cs_d
JIT.Methodical.fp.exgen.10w5d_cs_d.10w5d_cs_d
JIT.Methodical.fp.exgen.10w5d_cs_do.10w5d_cs_do
JIT.Methodical.fp.exgen.10w5d_cs_ro.10w5d_cs_ro
JIT.Methodical.fp.exgen.200w1d-02_cs_do.200w1d-02_cs_do
JIT.Methodical.fp.exgen.10w5d_cs_r.10w5d_cs_r
JIT.Methodical.fp.exgen.200w1d-02_cs_ro.200w1d-02_cs_ro
JIT.Directed.perffix.primitivevt.mixed1_cs_do.mixed1_cs_do
```
The failures would seem to indicate a JIT/runtime bug, as they're frequently eminating from code other than decimal, suggesting that something is getting corrupted, e.g.
```
FAILED   - JIT/Methodical/fp/exgen/200w1d-02_cs_ro/200w1d-02_cs_ro.sh
               BEGIN EXECUTION
               /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun 200w1d-02_cs_ro.exe

               Unhandled Exception: System.OverflowException: Value was either too large or too small for an Int32.
                  at System.Convert.ThrowInt32OverflowException()
                  at System.Convert.ToInt32(Int64 value)
                  at testout1.Func_0()
                  at testout1.Main()
               ./200w1d-02_cs_ro.sh: line 243: 101339 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```
These failures are only occurring on Unix.

Here's the commit that undoes the explicit layout; reverting this commit yields the failures.
https://github.com/dotnet/coreclr/pull/15145/commits/dc35586ecd37be9d2517244175da8b84a1237005

**Comment by janvorli** [comment]
I may be wrong, but I think that the Unix amd64 ABI support in coreclr cannot pass / return structs with explicit layout by value in registers. Looking at the https://github.com/dotnet/coreclr/commit/dc35586ecd37be9d2517244175da8b84a1237005, it looks like the struct would be a candidate for passing in registers and so if we pass or return such struct from managed to native code in runtime, it could explain the issues.

**Comment by jkotas** [comment]
You are probably right. It would meant that marking Decimal as ExplicitLayout would be a breaking change. 

I am wondering whether https://github.com/dotnet/corefx/blob/master/src/System.Memory/Common/src/System/MutableDecimal.cs is the better solution for the explicit layout problem. As side-effect, it would get rid of majority of the places where we mutate the Decimal fields internally and allowed us to mark Decimal as `readonly struct`.

cc @pentp

**Comment by pentp** [comment]
Using unsafe ref casts to work on the overlaid fields could work, but it might hurt perf, for example in .ctors because JIT optimizations might not work as well. In any case, `[FieldOffset(8), NonSerialized] private ulong ulomidLE;` would still require explicit layout, unless we add another projection struct.
`readonly struct` would be a nice benefit, but it would have a limited effect (only on `ToString, Equals, CompareTo`) because all the operators, conversions and math functions are defined as static functions and it would be a breaking change to add `in` for them.

I think making the explicit layout work first and then later coming back to the `readonly struct` theme after CoreCLR and CoreRT share decimal code and we can find a way to get more functions to use `in` semantics without breaking changes.

I'm not too familiar with the Unix amd64 ABI, but why does it want to pass/return 16-byte structs using registers? Changing from sequential to explicit should not be a breaking change in CLR and explicit could be made to work even when passed in registers (e.g., by re-constituting them to a local on stack).

**Comment by jkotas** [comment]
> Using unsafe ref casts to work on the overlaid fields could work

I was thinking we would always start by casting the whole decimal as `ref MutableDecimal` and go from there. We would not be casting for each individual field access.

> I'm not too familiar with the Unix amd64 AB

The struct calling convention Unix amd64 ABI depends on the content of the struct - if you change the fields of the struct, it will change how it gets passed. Also, there is no direct exact mapping between C++ unions and C# explicit layout that complicates things furher.

**Comment by pentp** [comment]
Always casting first and then passing by `ref/in` should be doable (maybe even combine `DecCalc` and `MutableStruct` for better code cohesion). If I understand correctly, the C# compiler treats `System.Decimal` in a special way that allows it to have .ctors that don't init all fields? I tried to look into it once, but didn't find anything in Roslyn.
That leaves inline-able functions like `Negate` - if they still inline properly, then using `MutableDecimal` shouldn't have negative perf effects and works around Unix amd64 ABI problems also.

**Comment by jkotas** [comment]
This issue was moved to dotnet/corert#4994
