### ISSUE TITLE
Tiered jitting: We need a working x86 full-stack build so that the VS profiler team can test our feature

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#15154]
When I last tried to find a working x86 dotnet daily build I wasn't successful. This is apart from any details of the tiered jitting feature - the dotnet build wasn't able to do some basic restore/build/run for a template ASP.Net app. Its possible the daily build I tried was just an unlucky one but I was unable to quickly salvage it or find information about an LKG version to use instead.

These are the steps I used to acquire and run an x64 version that worked. I expected that I could replace 'x64' with 'x86' everywhere it shows up below and it would also work, but that didn't happen. 

---

1)	Download and run the installer for the new build: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.0-preview1-007525/dotnet-sdk-2.2.0-preview1-007525-win-x64.exe
This should install the new build SxS with any other builds on the machine. You don’t need to uninstall anything in advance.
You should observe the following folders have been created on the machine which were not present before:
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.0-preview1-25907-02
C:\Program Files\dotnet\sdk\2.2.0-preview1-007525

2)	Create a new default MVC ASP.Net project in Visual Studio

3)	Open the .csproj file that was created and replace the XML tag that looks like this:
`<TargetFramework>netcoreapp2.0</TargetFramework>`
                So that it is now this:
 ```
              <TargetFramework>netcoreapp2.1</TargetFramework>
              <RuntimeFrameworkVersion>2.1.0-preview1-25907-02</RuntimeFrameworkVersion>
```

4)	In the same directory as the .sln, add a file named global.json with this content:
{
  "sdk": {
    "version": "2.2.0-preview1-007525"
  }
}

5)	In the same directory as the .sln, add a second file named “nuget.config” with this content:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<packageSources>
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json"/>
</packageSources>
</configuration>
```

6)	Now build and run the application.

**Comment by noahfalk** [comment]
@weshaggard - @lt72 suggested I assign this to you but I'm not sure?

**Comment by weshaggard** [comment]
Not sure why this would be assigned to me. 

@noahfalk what errors are you seeing?

**Comment by lt72** [comment]
@weshaggard: I just tried Noah's repro steps, and it seems to work for me.
@noahfalk: Can you please send the error you were seeing?

**Comment by RussKeldorph** [comment]
@noahfalk Is this still an issue?  If so, could you send more details about the failure?

**Comment by noahfalk** [comment]
Sorry this was tracking a todo item I had right before I left for thanksgiving so I didn't get a chance to repro it again and record the exact behavior. My suspicion is that it was a transient issue with a build or just user error. In any case I don't think the VS profiler guys are blocked now so I'm going to close this and reopen with more details later if necessary. Thanks for checking @RussKeldorph
