### ISSUE TITLE
[arm64] GC\API\NoGCRegion\NoGC\NoGC.cmd is slow on Debug

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#15169]
On my Windows ARM64 machine, the `GC\API\NoGCRegion\NoGC\NoGC.cmd` test takes about 3.5 minutes on Checked, but over 20 minutes on Debug. I believe this is why all the ARM64 Debug build and tests CI runs are failing on this test, due to a timeout.

What is the best way to address this long running test? One option: disable the test in tests\arm64\tests.lst. This would disable it for all runs. Or, we could add a "NOT_IN_DEBUG" category to the test and change the CI to not run tests in this category during Debug test runs.

I notice the test doesn't have the `<IsLongRunningGCTest>true</IsLongRunningGCTest>` tag in its metadata. Maybe because it is only long running in this one case? (It also turns out arm64 doesn't use this metadata.)

**Comment by BruceForstall** [comment]
@swgillespie @jashook ideas?

**Comment by swgillespie** [comment]
I'd be interested in seeing what's taking it so long. This test completes relatively quickly on x64 so I'm pretty surprised it would take 20 minutes. Can you grab a CPU sampling trace of this test? I'm always afraid of disabling tests wholesale since there could be bugs lurking but the `NOT_IN_DEBUG` solution sounds reasonable to me.

**Comment by BruceForstall** [comment]
This is preventing arm64 Debug jobs from completing successfully, so every job shows failure:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/arm64_cross_debug_windows_nt_tst/

**Comment by BruceForstall** [comment]
This (and other) tests have been marked `LONG_RUNNING` in https://github.com/dotnet/coreclr/pull/15388 and thus don't run on arm64.

If anything, we should create a `LONG_RUNNING` CI job that runs all these with a very long timeout. Currently, they are never run.
