### ISSUE TITLE
RuntimeBinderException when using Task extension method on the result of an async method in a call tree that includes a dynamic parameter

### ISSUE THREAD

**Issue by bungeemonkee** [dotnet/coreclr#15186]
I ran into a very specific case where the clr appears to not properly resolve extension methods at runtime for code involving both dynamics and async and throws a RuntimeBinderException.

CLI version: 2.0.3
CLR versioin: 2.0.3

If the code below is added to a netcoreapp2.0 console project it will reproduce the exception.

Program.cs
```csharp
using System;
using System.Threading.Tasks;

namespace RuntimeBinderException
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            Go(args).Wait();

            Console.WriteLine("Should not get here.");
        }

        public static async Task Go(dynamic thing)
        {
            await DoSomething(thing).TaskExtension();
        }

        public static async Task DoSomething(object parameter)
        {
            // The function needs only be declared async - it doesn't need to actually await anything
        }
    }
}

TaskExtensions.cs
```csharp
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace RuntimeBinderException
{
    public static class TaskExtensions
    {
        public static async Task TaskExtension(this Task task)
        {
            await task;
        }
    }
}
```

The exception is:
>Unhandled Exception: System.AggregateException: One or more errors occurred. ('System.Threading.Tasks.Task' does not contain a definition for 'TaskExtension') ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Threading.Tasks.Task' does not contain a definition for 'TaskExtension'
>   at CallSite.Target(Closure , CallSite , Object )
>   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
>   at RuntimeBinderException.Program.<Go>d__1.MoveNext() in /mnt/c/_Local/Playground/RuntimeBinderException/RuntimeBinderException/Program.cs:line 17
>   --- End of inner exception stack trace ---
>   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>   at System.Threading.Tasks.Task.Wait()
>   at RuntimeBinderException.Program.Main(String[] args) in /mnt/c/_Local/Playground/RuntimeBinderException/RuntimeBinderException/Program.cs:line 10

I have included a zip archive of the solution to reproduce the issue.
[RuntimeBinderException.zip](https://github.com/dotnet/coreclr/files/1497723/RuntimeBinderException.zip)

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#25461

**Comment by JonHanna** [comment]
As per the corefx issue. This is correct behaviour. A much shorter reproduction of the same behaviour is `((dynamic)new int[0]).Any()`. The dynamic binder does not—and should not—consider extension method syntax in deciding which overload to bind to. You should use the static method call syntax of `TaskExtensions.TaskExtension(DoSomething(thing));` instead.
