### ISSUE TITLE
AssemblyName.GetAssemblyName throws exceptions on Linux and macOS

### ISSUE THREAD

**Issue by bording** [dotnet/coreclr#15189]
Given the following program:
```csharp
class Program
{
    static Task Main()
    {
        var assembliesString = (string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES");
        var assemblies = assembliesString.Split(Path.PathSeparator);

        var tasks = new List<Task>();

        for (int i = 0; i < 100; i++)
        {
            tasks.Add(Task.Run(() => GetAssemblyNames(assemblies)));
        }

        return Task.WhenAll(tasks);
    }

    static void GetAssemblyNames(string[] assemblies)
    {
        foreach (var assembly in assemblies)
        {
            var assemblyName = AssemblyName.GetAssemblyName(assembly);
        }
    }
}
```

The behavior varies depending on what OS it is run on. It works perfectly on Windows. On Linux and macOS, the calls to GetAssemblyName eventually start failing. I've seen a variety of exceptions.

on macOS I've see the following exceptions:
```
System.IO.FileLoadException: Could not load file or assembly '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.0.3/System.Security.Cryptography.Encoding.dll'. A device attached to the system is not functioning.
 (Exception from HRESULT: 0x8007001F)
```
```
System.IO.FileLoadException: Could not load file or assembly '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.0.3/System.Diagnostics.FileVersionInfo.dll'. The system cannot open the file.
 (Exception from HRESULT: 0x80070004)
```

on Linux I've seen:
```
System.Runtime.InteropServices.COMException (0x8007000C) : The access code is invalid.
(Exception from HRESULT: 0x8007000C)
```
```
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
```

The stack traces all show the exceptions coming from `System.Reflection.AssemblyName.nGetFileInformation(String s)`. The assemblies that end up throwing vary from run to run, so the ones listed above are just examples.

I've run my tests using the 2.0.3 SDK and runtime, on the following OSes:
- Windows 10 1709 16299.64
- macOS 10.13
- Ubuntu 16.04

**Comment by jkotas** [comment]
cc @russellhadley

**Comment by janvorli** [comment]
I've tried it on my Ubuntu 14.04 and I can confirm that I repro the problem. Running under lldb reveals that the issue is due to too many open file handles. On my system, it had 4095 handles opened at the time it failed. 99% of these are managed assemblies, each having many handles opened. There are e.g. 59 handles to System.Net.Http.dll.
I haven't done further investigations yet.

**Comment by bording** [comment]
@jkotas @janvorli Any update on when this might be investigated more?
