### ISSUE TITLE
gc.cpp: null dereference when MULTIPLE_HEAPS is not defined

### ISSUE THREAD

**Issue by rigdern** [dotnet/coreclr#1519]
In [`src/gc/gc.cpp`](https://raw.githubusercontent.com/dotnet/coreclr/bb260291f7b2dd7744a7ddd950c3b7ae00259611/src/gc/gc.cpp), near the top of the `gc_heap::get_segment_for_loh` method, `hp` is initialized to `0` and then dereferenced on the next line:

```cpp
#ifndef MULTIPLE_HEAPS
    gc_heap* hp = 0;
#endif //MULTIPLE_HEAPS
    heap_segment* res = hp->get_segment (size, TRUE);
```

Reported on this web page: http://www.viva64.com/en/b/0310/#ID0E5BJM

**Comment by jkotas** [comment]
This is by design - GC is using null gc_heap pointer throughout when MULTIPLE_HEAPS is not defined. The null pointer is never actually dereferenced.

**Comment by drbo** [comment]
I believe that this is still undefined behavior per the C++ standard, and that GCC and Clang will consider this code as having undefined behavior.  GCC can be given the flag `-fno-delete-null-pointer-checks` but Clang cannot, so this code must be fixed, as must all the other undefined behaviors in <a>http://www.viva64.com/en/b/0310/#ID0E5BJM</a>.

**Comment by alexandrnikitin** [comment]
@drbo Take a look at my explanation in https://github.com/dotnet/coreclr/issues/1860#issuecomment-150593473

**Comment by rigdern** [comment]
Closing based on @alexandrnikitin's explanation in #1860.
