### ISSUE TITLE
Socket.IOcontrol handles Windows-specific control codes and is not supported in linux

### ISSUE THREAD

**Issue by ms0713** [dotnet/coreclr#15194]
Using DllImport in my .Net code, I was using **ws2_32.dll**. While running same in Linux it says dll cant be load.
So I stopped using DllImport and used Socket.IOControl() to read my data from socket. This time linux gives following error:
Socket.IOControl handles Windows -specific control codes and is not supported in linux.

What could be the common way to recieve data in Windows and Linux???

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#25467
