### ISSUE TITLE
Coreclr build fails with error :  __declspec attribute 'selectany' is not supported 

### ISSUE THREAD

**Issue by sam0302** [dotnet/coreclr#15197]
I am trying to build coreclr using yocto for Raspberry pi platform. I am using the bitbake layer from https://github.com/Tragetaschen/meta-aspnet.
I am getting compilation issue as below:

1.
> /coreclr/2.0.0-r0/git/src/inc/cor.h:2210:1: error: __declspec attribute 'selectany' is not supported [-Werror,-Wignored-attributes]
SELECTANY const mdToken g_tkCorEncodeToken[4] ={mdtTypeDef, mdtTypeRef, mdtTypeSpec, mdtBaseType};
^
/build/tmp/work/xxx-linux-gnueabi/coreclr/2.0.0-r0/git/src/inc/cor.h:2207:41: note: expanded from macro 'SELECTANY'
    #define SELECTANY extern __declspec(selectany)

also below error
2. 
>/build/tmp/work/xxx-linux-gnueabi/coreclr/2.0.0-r0/git/src/pal/src/loader/module.cpp:1176:5: error: lambda capture '__param' is not used [-Werror,-Wunused-lambda-capture]
    PAL_EXCEPT(EXCEPTION_EXECUTE_HANDLER)
    ^
/build/tmp/work/xxx-linux-gnueabi/coreclr/2.0.0-r0/git/src/pal/inc/pal.h:6091:44: note: expanded from macro 'PAL_EXCEPT'
    auto exceptionFilter = [&disposition, &__param](PAL_SEHException& ex)       \

Please suggest what could be the issue

**Comment by jkotas** [comment]
cc @janvorli

**Comment by janvorli** [comment]
@sam0302 it is a bug in the clang 5.0 compiler, it seems that they are going to fix it for 5.1 release.

**Comment by sam0302** [comment]
Thanks jan, I got a patch fix for 1st error : SELECTANY issue here: https://reviews.llvm.org/D33852
Is there any patch fix for 2nd error, where we get error for unused variable in lambda capture.
I want to apply the patch locally so that i can build coreclr successfully.

**Comment by janvorli** [comment]
You silent the 2nd error by adding 
```C++
(void)__param;
```
right before the following line src/pal/src/loader/module.cpp:1178
```C++
WARN("Call to DllMain (%p) got an unhandled exception; ignoring.\n", module->pDllMain);
```

**Comment by jkotas** [comment]
If this will fix the error for you, it would be great if you can submit CoreCLR PR with the fix.

**Comment by sam0302** [comment]
I tried the above changes of adding (void)__param; However this does not fix the issue...
I am getting this error from 3 different files and everywhere i made same changes but the issue persists

/src/pal/src/loader/**module.cpp**:1176:5: error: lambda capture '__param' is not used [-Werror,-Wunused-lambda-capture]
    PAL_EXCEPT(EXCEPTION_EXECUTE_HANDLER)
/src/vm/**stubmgr.cpp**:475:5: error: lambda capture '__param' is not used [-Werror,-Wunused-lambda-capture]
    PAL_EXCEPT(EXCEPTION_EXECUTE_HANDLER)
/src/vm/**util.cpp**:3256:5: error: lambda capture '__param' is not used [-Werror,-Wunused-lambda-capture]
    PAL_EXCEPT(EXCEPTION_EXECUTE_HANDLER)

**Comment by janvorli** [comment]
@sam0302 I am sorry for misleading you. This is not a correct fix. The right way to do that is to modify the PAL_EXCEPT macro. Can you please add the 
```C++
(void)__param;
```
to the PAL_EXCEPT macro definition right before the line https://github.com/dotnet/coreclr/blob/master/src/pal/inc/pal.h#L5924?

The thing is that the __param can be used by the dispositionExpression, but in many cases the dispositionExpression is just a constant and so it is unused.
