### ISSUE TITLE
FailFast logging should include inner exception details and stacktrace

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/coreclr#15203]
We introduced FailFast logging with this change: https://github.com/dotnet/coreclr/commit/0c4a490 but are currently ignoring the passed exception data and stacktrace when calling `FailFast(string,Exception)`. We currently output the stacktrace that originates from the FailFast call.

This issue was reported here: https://github.com/dotnet/corefx/issues/25477
Related issue:
- https://github.com/dotnet/coreclr/issues/14037
- https://github.com/dotnet/coreclr/issues/14867

cc @danmosemsft @jkotas

**Comment by ViktorHofer** [comment]
@danmosemsft If somebody has free cycles that would be something nice to be done.

**Comment by danmosemsft** [comment]
It woudl be good to have in 2.1. @wtgodbe if you run out of bugs, here is another valuable one.

**Comment by danmosemsft** [comment]
I've found the FailFast logging super useful.

**Comment by sywhang** [comment]
Hey @ViktorHofer, do you mind if I take over this along with #14867? 

@lt72: FYI

**Comment by ViktorHofer** [comment]
Please feel free to do so. Thanks a lot!

**Comment by ViktorHofer** [comment]
Consider also #14037

**Comment by sywhang** [comment]
Thanks for the link! Will take a look at these two first and move onto that issue if I have time.

**Comment by danmosemsft** [comment]
Using the code below I get just
```
FailFast:
Oops

   at System.Environment.FailFast(System.String, System.Exception)
   at System.Environment.FailFast(System.String, System.Exception)
   at Program.Main()
```
Problems
1) FailFast appears twice.
2) Exception and inner exception are not shown.

```c#
using System;
using System.Diagnostics;

class Program
{
    static void Main()
    {
        try
        {
            A();
        }
        catch(Exception ex)
        {
            Environment.FailFast("Oops", ex);
        }
    }

    static void A()
    {
        B();
    }

    static void B()
    {
        try
        {
            C();
        }
        catch (Exception ex)
        {
            throw new ArgumentException("my ae", ex);
        }
    }

    static void C()
    {
        D();
    }

    static void D()
    {
        throw new NullReferenceException("my nre");
    }
}
```
@sywhang I tihnk this one is important to fix as this can be critical diagnostic informatoin. Do you have time to pick this one up?

**Comment by sywhang** [comment]
Hey @danmosemsft, 
I can probably start tackling this along with the fix I'm working on for the issue you brought up in #14867.

**Comment by danmosemsft** [comment]
Thanks @sywhang . I would like to try hard to get these into 2.1 because it makes the product more supportable (and self supportable). Please let me know if it looks like you won't be able to get them in. Appreciate it.

**Comment by sywhang** [comment]
This should be now fixed with #16622.

**Comment by danmosemsft** [comment]
Thanks @sywhang!

**Comment by danmosemsft** [comment]
BTW if you are interested in protecting this with a test, I believe a best way would be to do it in CoreFX something like this test
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/System/EnvironmentTests.cs#L194
The only piece missing is a way to gather the console output for the child process (this one is just getting the exit code)
That would need a change to add a new option on RemoteInvokeOptions that caused console to be captured, and wired up in here
https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.Process.cs

**Comment by sywhang** [comment]
@danmosemsft ,

Thank you! I'll look into those and add some tests for this. I might not be able to get to it in the next couple of weeks though (kinda falling behind on some GC work), but I will create an issue in CoreFX to keep myself reminded.

**Comment by danmosemsft** [comment]
That would be great. Now that we have this, I don't want it to get broken. Ping me if you need pointers.
