### ISSUE TITLE
Facilitate using CMake's standard mechanism to find CoreCLR

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/coreclr#1521]
[LLILC](https://github.com/dotnet/llilc) (and other projects?) pulls in some CoreCLR sources for utilities such as GC encoding.  LLILC, like most (all?) LLVM tools, uses CMake for configuration, and currently we find those CoreCLR sources via a required argument passed on the cmake command line, but this causes some friction in the LLVM build where (aside from this) there are no required cmake command line arguments (see [D12679](http://reviews.llvm.org/D12679)).  Cmake has a standard [`find_package` utility](http://www.cmake.org/cmake/help/v3.0/command/find_package.html) for locating a "package" like this in a "default" location.  That mechanism is quite flexible; it can search specific directories, the path, locations specified by cmake-specific environment variables, cmake's user package registry, and its system package registry, or can be overridden with custom logic.

The purpose of this issue is to track that (long-term) we'd like to have these packaged as a cmake package which `find_package` can find (or be overriden to find).  The relevant sources currently get copied as part of the build process and I know we already have plans to be able to find them in nuget packages (I think @russellhadley and/or @mmitche know more about that), it may be that the best way to handle this would be for the build or an install step or nuget installation to record the location somewhere that cmake can subsequently find it.

**Comment by BruceForstall** [comment]
@JosephTremoulet Do you want to keep this open?

**Comment by JosephTremoulet** [comment]
Seems like it would be bad form to close this without reverting the objectionable part of [D12679](https://reviews.llvm.org/D12679) that's working around it.
