### ISSUE TITLE
Rationale behind EEHashTableBase implementation

### ISSUE THREAD

**Issue by Rattenkrieg** [dotnet/coreclr#15216]
I've used eehash as basis for some internals in #15135 and here are listed some questionable parts of it. Do not consider it as criticism, I'm just curious of trade-offs which .net team was challenged.
Also there is [comment](https://github.com/dotnet/coreclr/blob/master/src/vm/eehash.h#L10) in `eehash.h` that might be treaten as evidence of "not so thorough implementation":
> // Provides hash table functionality needed in the EE - intended to be replaced later with better
// algorithms, but which have the same interface.

I'm evaluating implementation from the way it is used in string interning routines - [src/vm/stringliteralmap.h](https://github.com/dotnet/coreclr/blob/master/src/vm/stringliteralmap.h) and friends.

 - Why the load factor is as big as 2? 
https://github.com/dotnet/coreclr/blob/master/src/vm/eehash.inl#L249
 - Why length is increased by multiplying by 4 and hence business of keeping `hash mod size` coprime with length is left to hash function implementation? 
https://github.com/dotnet/coreclr/blob/master/src/vm/eehash.inl#L673
 - Specific to strings, i.e `stringliteralmap` - were alternative data structs considered? For example HAT-trie.

**Comment by jkotas** [comment]
This hashtable was implemented more than 15 years ago. It never showed on the radar as bottleneck so  nobody bothered to make it better. I agree that it does not seem to be a particularly great implementation.

**Comment by Rattenkrieg** [comment]
I'll try to guess that reason for big load factor is pursue to reduce costly grow operations that (at least in intern pool routines) happens under lock.
I'm closing this as the (unsurprisingly obvious) answer was given. But I'll be happy if someone could share their thoughs or expierence.
