### ISSUE TITLE
Disable FEATURE_PERFTRACING

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/coreclr#15228]
Is there any way to disable `FEATURE_PERFTRACING` ? 
It seems that undefining `FEATURE_PERFTRACING`  as follows does not work on build since definitions from `FEATURE_PERFTRACING` block are used on python-generated cpp files.
```
diff --git a/clr.coreclr.props b/clr.coreclr.props
index 059fb3a..4fbe500 100644
--- a/clr.coreclr.props
+++ b/clr.coreclr.props
@@ -90,6 +90,6 @@

   <PropertyGroup Condition="'$(TargetsLinux)' == 'true'">
     <FeatureManagedEtw>true</FeatureManagedEtw>
-    <FeaturePerfTracing>true</FeaturePerfTracing>
+    <FeaturePerfTracing>false</FeaturePerfTracing>
   </PropertyGroup>
 </Project>
diff --git a/clrdefinitions.cmake b/clrdefinitions.cmake
index 6db2b24..2408e05 100644
--- a/clrdefinitions.cmake
+++ b/clrdefinitions.cmake
@@ -111,9 +111,6 @@ endif(FEATURE_DBGIPC)
 if(FEATURE_EVENT_TRACE)
     add_definitions(-DFEATURE_EVENT_TRACE=1)
 endif(FEATURE_EVENT_TRACE)
-if(CLR_CMAKE_PLATFORM_LINUX)
-    add_definitions(-DFEATURE_PERFTRACING)
-endif(CLR_CMAKE_PLATFORM_LINUX)
 if(CLR_CMAKE_PLATFORM_UNIX)
     add_definitions(-DFEATURE_EVENTSOURCE_XPLAT=1)
 endif(CLR_CMAKE_PLATFORM_UNIX)
```
Is there any good way to disable `FEATURE_PERFTRACING` ?

**Comment by jkotas** [comment]
cc @brianrob

**Comment by brianrob** [comment]
@chunseoklee, I could believe that there is a bug in how we handle the generated source files.  The intention is that if you need to disable this feature that it should work, but we've not had occasion to do so on Linux.  In fact, #14772 is working to enable FEATURE_PERFTRACING on all platforms.

Out of curiosity, why are you trying to disable FEATURE_PERFTRACING?

**Comment by brianrob** [comment]
Marking this as up-for-grabs, since it sounds like this is just a matter of tracing down code that is not under ifdef FEATURE_PERFTRACING.

**Comment by chunseoklee** [comment]
@brianrob  sort for late response.

> Out of curiosity, why are you trying to disable FEATURE_PERFTRACING?

On tizen side, there was a problem of event pipe. Now, this can be fixed with https://github.com/dotnet/coreclr/pull/15765. 

Thank you.

**Comment by brianrob** [comment]
@chunseoklee are you saying that #15765 solves the problem?
