### ISSUE TITLE
Source/line info doesn't work on Windows for Windows PDBs

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#15254]
Integrate Windows PDB fix into the next 2.0.x service release.

Master (2.1) PR: https://github.com/dotnet/coreclr/pull/14696
Originally issue: https://github.com/dotnet/corefx/issues/21079

**Comment by pranavkm** [comment]
Is there a specific 2.0.x release you're targeting for this? One of Mvc's compilation scenarios is affected by this and I wanted to track this so we can verify it being fixed from our end too

**Comment by mikem8361** [comment]
It should be 2.0.4 maybe 2.0.5.
