### ISSUE TITLE
 .net core 2.0 calling Socket.Select caused high cpu usage.

### ISSUE THREAD

**Issue by zl-cn** [dotnet/coreclr#15264]
System: windows 10
Platform: .net core 2.0
under .net core 2.0 calling Socket.Select caused high cpu usage.
but under .net 4.6 it's ok.
simple code:

while(true) { Socket.Select(checkRead, checkWrite, checkError, 0); if (checkError.Count == 0 && checkWrite.Count == 0 && checkRead.Count == 0) { Thread.Sleep(10); continue; } }

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#25572
