### ISSUE TITLE
Building native shims from top level folder

### ISSUE THREAD

**Issue by janhenke** [dotnet/coreclr#1527]
Currently there is no top level way to build the native shims. One has to call  ```src/Native/build.sh```. Since the shims are needed for CoreFX to work correctly on Unix systems, it would be helpful to provide some intuitive way of invoking the build from the top level.

I see two obvious ways to archive this:

1. Create a top level ```build-native.sh``` which starts the build in ```src/Native```
2. Have the top level ```build.sh``` invoking building the shims in addition to the manages assemblies.

I am in favour of option 2. How are general ideas?

cc @nguerrera @sokket @stephentoub

**Comment by sokket** [comment]
Option two seems like a clean approach to me; having a shim-specific build in the top level directory seems wonky. It should also make it super easy to build all of CoreFX with one command, which is definitely a plus. There are probably some issues to think through with this method, such as if the native build blocks the managed on failure, though. Thoughts?

**Comment by janhenke** [comment]
We have to do one of the builds before the other anyway (otherwise they would compete for CPU time). So to not affect the managed code build, we could build all of the managed assemblies first. Only if that is successful we can build the native shims afterwards.

**Comment by janhenke** [comment]
I just now realize I opened the issue at the wrong repository. This was meant to go to CoreFX instead. I will open it there again. @sokket Feel free to post your reply there.
