### ISSUE TITLE
Windows Debug builds use /O1

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#1528]
Why do we build the *Debug* flavor on Windows with the `O1` optimization switch instead of `Od`? Can we please change it to `Od`?

(I can't tell what non-Windows builds use; can someone tell me if the debug flavor is built with or without optimization, and where to find that information?)

**Comment by mikedn** [comment]
See #1144, apparently there's a test that fails if code isn't optimized.

**Comment by BruceForstall** [comment]
Closing, since Matt fixed this with #1144
