### ISSUE TITLE
JITMinOpts=1 Assertion on LSH w/ negative shift

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#15291]
When running Arm64 with JITMinOpts=1, the following test is asserting
JIT/Methodical/flowgraph/dev10_bug679955/indexMinusOne/indexMinusOne.sh

My initial analysis indicates the issue is not platform specific.

```
Assert failure(PID 30534 [0x00007746], Thread: 30534 [0x7746]): Assertion failed 'shiftAmountValue >= 0' in 'ILGEN_0x52ea038a:Method_0xc9efd6b0(int,int,double,char,int,ubyte,double,ubyte,char,byte):char' (IL size 4430)

    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/morph.cpp Line: 496
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/corerun
```

When running w/o MinOpts the offending statement is removed.

```
Removing statement [002476] in BB07 as useless:
               [002476] ------------              *  STMT      void  (IL   ???...0x114D)
               [002475] ---XG-------              \--*  RETURN    int   
               [002473] ------------                 |  /--*  CAST      int <- uint <- long
               [002159] ------------                 |  |  |  /--*  CNS_INT   int    -1
               [002472] ------------                 |  |  \--*  LSH       long  
               [002076] ------------                 |  |     \--*  LCL_VAR   long   V128 tmp103      
               [002474] ---XG-------                 \--*  INDEX     int   
               [001907] ------------                    \--*  LCL_VAR   ref    V119 tmp94       
```

With Minopts, the statement remains and the above assert fires.

Offending code is as follows
```
                if (shiftAmount->IsIntegralConst())
                {
                    const ssize_t shiftAmountValue = shiftAmount->AsIntCon()->IconValue();
                    assert(shiftAmountValue >= 0);

                    if (shiftAmountValue >= 32)
                    {
                        // Result of the shift is zero.
                        DEBUG_DESTROY_NODE(tree);
                        GenTree* zero = gtNewZeroConNode(TYP_INT);
                        return fgMorphTree(zero);
                    }
                    else
                    {
                        // Shift amount is small enough that we can push the cast through.
                        canPushCast = true;
                    }
                }
                else
                {
                    // Shift amount is unknown. We can't optimize this case.
                    assert(!canPushCast);
                }
```

The assert could be removed and the negative case could be properly handled.  Whichever is correct:
+ Treat negative shift as `canPushCast = false;`
+ Calculate the effective shift, which I suspect is `actualShift = shiftAmount & (bitsInType(T) - 1)`

Otherwise
+ Ignore the MinOpts failure on illegal IL.

**Comment by sdmaclea** [comment]
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Hmm, I just added this assert.

ECMA-355 doesn't quite come out and say it, but I suspect negative shift values give rise to undefined behavior. Probably going via `canPushCast = false` route is safest here, eg remove the assert and modify the `else` to be `else if (shiftAmount >= 0)`.

**Comment by briansull** [comment]
I believe that whatever the shift amount is (positive or negative) the shifter masks off teh lowest 4 or 5 bits and shift by that amount.  When other bits are set, the result is "undefined" but it shouldn't result in an assert.  

App-compat may require us not to disturb this behavior by changing the results.

So to preserve "app-compat" shifting  65 bits would continue to produce the same result as shifting by 1 bit and not be "optimized" to produce a zero value.

**Comment by AndyAyersMS** [comment]
We can avoid the > 64 case too easily enough... guess I'll fix this.
