### ISSUE TITLE
EventPipe doesn't catch ActivityId set by EventSource

### ISSUE THREAD

**Issue by xiaomi7732** [dotnet/coreclr#15302]
The following issue is reproduced on .NET Core for Linux.

**Reproduce steps:**
1. Enable eventpipe. (referenced control code: https://github.com/dotnet/coreclr/blob/bac965ea8d3977a08257ee6758e14ccda34547e3/tests/src/tracing/common/TraceControl.cs)
2. Set a new activity id for current thread upon EventSource:
```csharp
// Switch to a new activity.
EventSource.SetCurrentThreadActivityId(Guid.NewGuid());
// Write event source so that EventPipe is listen upon.
SomeEventSource.Log.WriteRequest("Any", "any");
```
3. Inspect the generated trace log file.

**Expected:** AcitivityID will be on the events being caught.
**Actual:** ActivityID is empty.

**Comment by brianrob** [comment]
@xiaomi7732 I want to confirm some behavior that you're seeing here.  Are you saying that if you set the activity ID and then log an event via EventSource that the activityID doesn't show up?  Or is this specific to runtime events (non-EventSource)?

**Comment by xiaomi7732** [comment]
@brianrob it is: set the activity ID and then log an event via EventSource that the ActivityID doesn't show up in netperf file. Thanks for looking into this. Please let me know if more info is needed.

**Comment by brianrob** [comment]
@xiaomi7732 thanks.  I have a test case for this and I think I know what needs to be done.  Will work on a PR.

**Comment by xiaomi7732** [comment]
@brianrob sounds perfect!

**Comment by xiaomi7732** [comment]
@brianrob Thanks for taking care of this.
