### ISSUE TITLE
[RyuJIT/arm32][GCStress=3] Failures in GCStress=3 runs

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#15309]
It's not clear these are JIT bugs or other issues; generally GCStress=3 failures does not imply JIT bugs.
```
Tests.lst=_dbglcs2.cmd_803, , , Smrt00000001, , # JIT\Methodical\Arrays\lcs\_dbglcs2\_dbglcs2.cmd  CATS: EXPECTED_PASS
Tests.lst=_speed_dbglcs2.cmd_1650, , , Smrt00000001, , # JIT\Methodical\Arrays\lcs\_speed_dbglcs2\_speed_dbglcs2.cmd  CATS: EXPECTED_PASS
Tests.lst=Dev10_535767.cmd_1682, , , Smrt00000001, , # baseservices\compilerservices\dynamicobjectproperties\Dev10_535767\Dev10_535767.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=_rellcs2.cmd_2121, , , Smrt00000001, , # JIT\Methodical\Arrays\lcs\_rellcs2\_rellcs2.cmd  CATS: EXPECTED_PASS
Tests.lst=_speed_rellcs2.cmd_2415, , , Smrt00000001, , # JIT\Methodical\Arrays\lcs\_speed_rellcs2\_speed_rellcs2.cmd  CATS: EXPECTED_PASS
Tests.lst=ArraySort3.cmd_2866, , , Smrt00000001, , # CoreMangLib\cti\system\array\ArraySort3\ArraySort3.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=CompareExchangeTClass.cmd_3014, , , Smrt00000001, , # baseservices\threading\interlocked\compareexchange\CompareExchangeTClass\CompareExchangeTClass.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=_speed_relvirtcall.cmd_4088, , , Smrt00000001, , # JIT\Methodical\refany\_speed_relvirtcall\_speed_relvirtcall.cmd  CATS: EXPECTED_PASS
Tests.lst=ExternalException.cmd_4406, , , Smrt00000001, , # baseservices\exceptions\regressions\V1\SEH\VJ\ExternalException\ExternalException.cmd  CATS: EXPECTED_PASS;GCSTRESS_FAIL;13203;Pri1
Tests.lst=CompareExchangeTClass_1.cmd_4723, , , Smrt00000001, , # baseservices\threading\interlocked\compareexchange\CompareExchangeTClass_1\CompareExchangeTClass_1.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=Collect0.cmd_5024, , , Smrt00000001, , # GC\API\GC\Collect0\Collect0.cmd  CATS: EXPECTED_PASS
Tests.lst=GCCollect.cmd_5027, , , Smrt00000001, , # CoreMangLib\cti\system\gc\GCCollect\GCCollect.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=objmonhelper.cmd_5924, , , Smrt00000001, , # baseservices\threading\regressions\269336\objmonhelper\objmonhelper.cmd  CATS: EXPECTED_PASS;GCSTRESS_FAIL;13200;Pri1
Tests.lst=b80737.cmd_10094, , , Smrt00000001, , # JIT\Regression\VS-ia64-JIT\M00\b80737\b80737\b80737.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=smalloom.cmd_10071, , , Smrt00000001, , # GC\Coverage\smalloom\smalloom.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=NoGC.cmd_11390, , , Smrt00000001, , # GC\API\NoGCRegion\NoGC\NoGC.cmd  CATS: EXPECTED_PASS;NEW
```
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_gcstress0x3_tst_prtest/2/

**Comment by BruceForstall** [comment]
Current set of GCStress=3 Windows arm32 bugs:
```
[TESTS]
Tests.lst=_dbglcs2.cmd_803, , , Smrt00000001, , # JIT\Methodical\Arrays\lcs\_dbglcs2\_dbglcs2.cmd  CATS: EXPECTED_PASS
Tests.lst=_speed_dbglcs2.cmd_1650, , , Smrt00000001, , # JIT\Methodical\Arrays\lcs\_speed_dbglcs2\_speed_dbglcs2.cmd  CATS: EXPECTED_PASS
Tests.lst=Dev10_535767.cmd_1682, , , Smrt00000001, , # baseservices\compilerservices\dynamicobjectproperties\Dev10_535767\Dev10_535767.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=_rellcs2.cmd_2121, , , Smrt00000001, , # JIT\Methodical\Arrays\lcs\_rellcs2\_rellcs2.cmd  CATS: EXPECTED_PASS
Tests.lst=_speed_rellcs2.cmd_2415, , , Smrt00000001, , # JIT\Methodical\Arrays\lcs\_speed_rellcs2\_speed_rellcs2.cmd  CATS: EXPECTED_PASS
Tests.lst=ArraySort3.cmd_2866, , , Smrt00000001, , # CoreMangLib\cti\system\array\ArraySort3\ArraySort3.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=CompareExchangeTClass.cmd_3014, , , Smrt00000001, , # baseservices\threading\interlocked\compareexchange\CompareExchangeTClass\CompareExchangeTClass.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=_speed_relvirtcall.cmd_4088, , , Smrt00000001, , # JIT\Methodical\refany\_speed_relvirtcall\_speed_relvirtcall.cmd  CATS: EXPECTED_PASS
Tests.lst=ExternalException.cmd_4406, , , Smrt00000001, , # baseservices\exceptions\regressions\V1\SEH\VJ\ExternalException\ExternalException.cmd  CATS: EXPECTED_PASS;LEGACYJIT_GCSTRESS_FAIL;13203;Pri1
Tests.lst=CompareExchangeTClass_1.cmd_4723, , , Smrt00000001, , # baseservices\threading\interlocked\compareexchange\CompareExchangeTClass_1\CompareExchangeTClass_1.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=objmonhelper.cmd_5924, , , Smrt00000001, , # baseservices\threading\regressions\269336\objmonhelper\objmonhelper.cmd  CATS: EXPECTED_PASS;LEGACYJIT_GCSTRESS_FAIL;13200;Pri1
Tests.lst=smalloom.cmd_10071, , , Smrt00000001, , # GC\Coverage\smalloom\smalloom.cmd  CATS: EXPECTED_PASS;Pri1
```
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_gcstress0x3_tst_prtest/5/artifact/bin/tests/Windows_NT.arm.Checked/Smarty.run.0/Smarty.0.fail.smrt/*view*/

**Comment by sergign60** [comment]
@BruceForstall I see in comments ```LEGACYJIT_GCSTRESS_FAIL```. Could you tell, does it mean that CoreCLR on windows-arm uses LEGACY JIT?
CC: @dotnet/arm32-contrib

**Comment by BruceForstall** [comment]
No, CoreCLR on Windows ARM32 uses RyuJIT now. The `LEGACY_BACKEND` path (aka legacy jit) was used by default until December. And the CI can still test it using the "armlb" jobs. But we will remove it eventually, hopefully soon.

**Comment by BruceForstall** [comment]
For Windows, tests that are incompatible with GCStress can be marked `GCSTRESS_EXCLUDE` in the Categories list for a test in tests\arm\tests.lst. Tests that are currently failing can be marked `GCSTRESS_FAIL` (with an associated GitHub issue tracking the failure).

These failures are most likely VM issues, or test issues, not JIT issues.

**Comment by sergign60** [comment]
@BruceForstall 
CC: @dotnet/arm32-contrib 
I've found that on arm platforms only two following tests fail from https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_gcstress0x3_tst_prtest/5/artifact/bin/tests/Windows_NT.arm.Checked/Smarty.run.0/Smarty.0.fail.smrt/*view*/ 

``` objmonhelper``` and ``` smalloom```. They hang for vaguely long time.

**Comment by sergign60** [comment]
https://github.com/dotnet/coreclr/issues/16503

**Comment by sergign60** [comment]
https://github.com/dotnet/coreclr/issues/16564

**Comment by BruceForstall** [comment]
@janvorli fyi. These are still failing as last mentioned above. Since it's GCStress=0x3, I presume there's a VM issue here.

**Comment by janvorli** [comment]
All of the tests in the list above are timeouts. I've ran some of them locally and they eventually completed successfully, although not in the 10 min limit. I am in a process of verifying that it is the case for all of them.
In another run that @BruceForstall has pointed me to, the https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_gcstress0x3_tst/40/, there were 11 tests failing due to timeout, 3 due to invalid working directory (Bruce has identified that it is due to the recent change in the test building). 
One (JIT\Performance\CodeQuality\BenchmarksGame\regex-redux\regex-redux-1) has failed due to an assert `Consistency check failed: Crst Level violation: Can't take level 0 lock CrstExecuteManRangeLock because you already holding level 0 lock CrstLeafLock`. I was unable to repro it in more than 100 iterations on my Raspberry PI 3, so I am going to try to repro it on Windows ARM.
The last one failed due to its incompatibility with GC stress (it measures memory before and after GC and expects it to go down). I have created PR #17319 to exclude that test from GC stress.

**Comment by janvorli** [comment]
I was able to repro the Crst level violation issue on arm Windows machine under the debugger, so I can investigate it.

**Comment by kouvel** [comment]
I'll take a look

**Comment by RussKeldorph** [comment]
Changing to test bug (GCStress infra specifically) based on preliminary investigation by @kouvel.

**Comment by kouvel** [comment]
At least for the last issue it doesn't look like there is a threat for deadlock, I'm taking a closer look though. It looks like @janvorli figured out the rest of the issues.

**Comment by kouvel** [comment]
I have a smaller repro, working on a fix. It doesn't look like the issue affects release builds.

**Comment by kouvel** [comment]
I have put up PR https://github.com/dotnet/coreclr/pull/17376 to fix the regex-redux-1 issue. @janvorli, which of the tests are timing out, and should they be disabled under GCStress?

**Comment by BruceForstall** [comment]
We do have the concept of a "long running" GC test: pass "longgc" to runtest.cmd or "--long-gc" to runtest.sh, and tests are tagged with
```
<IsLongRunningGCTest>true</IsLongRunningGCTest>
```
in the .csproj/.ilproj file

However, this doesn't work for Windows arm/arm64; we'd need to define a new tag, e.g., GCSTRESS_LONG for the tests.lst files.

Also, it looks like on Windows it only bumps the per-test timeout to 20 minutes, which wouldn't be sufficient. I wonder if anyone ever runs these; maybe manually?

**Comment by janvorli** [comment]
* baseservices\threading\interlocked\compareexchange\CompareExchangeTClass\CompareExchangeTClass.cm (**took 16211 secs to complete**)
* baseservices\threading\interlocked\compareexchange\CompareExchangeTClass_1\CompareExchangeTClass_1.cmd (**took 20893 secs to complete**)

**Comment by kouvel** [comment]
Maybe at some point it would make sense to have a different variant of tests that are useful to run under GC stress, which wouldn't take as long. I guess that most of these are not intended to run with GC stress. Should I go ahead and disable them under GC stress?

**Comment by janvorli** [comment]
Yes, it would be great.

**Comment by janvorli** [comment]
Closing this issue as the tests failing due to the long running time were disabled for gcstress and the issue with invalid lock rank was addressed.
