### ISSUE TITLE
Fix misnamed DAC

### ISSUE THREAD

**Issue by lt72** [dotnet/coreclr#15310]
Current DAC name is incorrectly formatted as
   <LongNameSuffix>_$(LongNamePlatform)_$(LongNamePlatform)_$(MajorVersion).$(MinorVersion).$(BuildNumberMajor).0$(BuildNumberMinor)</LongNameSuffix>

the zero (0) before the minor build number should be removed for debugger/Watson to work properly.

**Comment by dagood** [comment]
FYI @leculver, I fixed this for 2.0.5 manually. (Fix PR is merged for 2.0.6+.)
