### ISSUE TITLE
ConsoleColor.White isn't white on macosx

### ISSUE THREAD

**Issue by equiman** [dotnet/coreclr#15320]
I'm working in a console project in dotnet core. 
But white color on mac is represented as lighter gray and not as white color.

Example img: https://ibb.co/kKoXPb
1) is background color in terminal by default.
2) is `Console.BackgroundColor = ConsoleColor.White; ` but is represented as lighter gray. 

I'm using default terminal application on macos.

$> dotnet --version
2.0.0

$> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B1003

Code using to format with color:
https://github.com/equiman/hardhat/blob/master/dev/tools/Colorify.cs

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#25634
