### ISSUE TITLE
[XARCH] Verify crossgen traps SIMD code

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#15328]
The intent is for SIMD codegen to be deferred during crossgen.

Audit of current SIMD code indicates SIMD is disabled during crossgen.  However, it is not clear if the SIMD candidate code is properly being trapped to defer generation.

Verify functionality is correct.

@CarolEidt

**Comment by sdmaclea** [comment]
Testing with `ARM64` SIMD in #14633 showed that enabling FeatureSIMD in Zapper was sufficient to enable SIMD code generation.  No trap to disable zapper codegen was found.

@CarolEidt was also unable to find the trap which disabled crossgen of XARCH code.  

@dotnet/jit-contrib FYI

**Comment by AndyAyersMS** [comment]
The block is in `MethodTableBuilder::CheckIfSIMDAndUpdateSize` but it is conditionally compiled under ```C++
#if defined(_TARGET_X86_) || defined(_TARGET_AMD64_)
```
So you probably need to update the the condition logic.

**Comment by sdmaclea** [comment]
@AndyAyersMS Thanks

It looks like that handles the `Vector<T>` case.  That seems to be the only place `IDS_EE_SIMD_NGEN_DISALLOWED` is used in a `throw`.  How are the `Vector3` et. al cases being handled?  

For ARM64, the `Vector<T>` size does not need to change as it is always 16 bytes.  It looks therefore like the code does not need to change.  (At least until Scalable Vector Extension support is added).

**Comment by CarolEidt** [comment]
Thanks @AndyAyersMS - I had forgotten that it was in `MethodTableBuilder`.

> How are the Vector3 et. al cases being trapped?

Those cases are not being trapped, as their sizes don't change.

>  It looks therefore like the code does not need to change.

Yes, I think that's correct - it should be fine as-is until such time as we have different sized vectors on ARM64.

**Comment by CarolEidt** [comment]
@sdmaclea - I think we can close this now?

**Comment by sdmaclea** [comment]
> Those cases are not being trapped, as their sizes don't change.

However during crossgen, SIMD code is not being generated since the feature is disabled during XARCH crossgen.

**Comment by sdmaclea** [comment]
This can be closed if you are OK with the suboptimal crossgen

**Comment by CarolEidt** [comment]
> However during crossgen, SIMD code is not being generated since the feature is disabled during XARCH crossgen.

Right - I don't recall for sure, but I believe that's to avoid mixing AVX and SSE encodings (though that remains an issue for other floating point code, just not as significant).

I'm not sure I would call it "suboptimal" crossgen; rather, it's avoiding suboptimal crossgen IMO.

**Comment by sdmaclea** [comment]
OK, I thought you would want to trap `Vector3` et al crossgen too, to enable SIMD optimization of these methods within crossgen assemblies.

Closing since this is not considered an issue
