### ISSUE TITLE
CoreCLR build: Deprecate unused variables used in the build

### ISSUE THREAD

**Issue by jcagme** [dotnet/coreclr#15335]
@karajas commented on [Fri Nov 10 2017](https://github.com/dotnet/core-eng/issues/2076)

This would include 
- defaults in each leg where the value should be coming in from pipebuild
- publish.proj, syncAzure.proj
- Conditions that can be handled by VSTS conditions.
- dead variables in pipebuild and build legs

---

@karajas commented on [Fri Nov 10 2017](https://github.com/dotnet/core-eng/issues/2076#issuecomment-343603136)

This could also be the work to standardize the variable names as seen in https://github.com/dotnet/coreclr/pull/14835 and https://github.com/dotnet/coreclr/pull/14787 
@weshaggard fyi

**Comment by RussKeldorph** [comment]
If these are things you can trivially address with your pending changes, please consider.  If not, please change the milestone to Future and clear your assignment.

**Comment by jashook** [comment]
Closing this issue. It still is useful to remove unused variables in our props/targets files but we do not use buildpipeline anymore.
