### ISSUE TITLE
[Watson] Reliability crash in coreclr.dll!PEFile::LoadAssembly

### ISSUE THREAD

**Issue by leculver** [dotnet/coreclr#15331]
There is a crash accounting for 18.5% of our external failures in this callstack:
```
0 coreclr!AssemblySpec::Bind
1 coreclr!AppDomain::BindAssemblySpec
2 coreclr!PEFile::LoadAssembly
3 coreclr!Module::LoadAssembly
4 coreclr!Assembly::FindModuleByTypeRef
5 coreclr!ClassLoader::LoadTypeDefOrRefThrowing
6 coreclr!SigPointer::GetTypeHandleThrowing
7 coreclr!MemberLoader::GetDescFromMemberRef
8 coreclr!CEEInfo::resolveToken 
```

I have not dug deeply into this issue.  I have requested heap dumps be collected for this bucket.

You can find the Watson bucket here:  https://watson/Failure?FailureSearchText=51ff1255-3178-91e0-9571-43a1f7add6b2

**Comment by jeffschwMSFT** [comment]
This issue is due to invalid instrumentation of System.Private.CoreLib.  The current dumps have insufficient details to fully confirm, waiting for full memory dumps.

**Comment by jeffschwMSFT** [comment]
The volume of this issue is so low that requesting additional heap dumps has not yielded an actionable heap dump (only prior to RS3 - which is missing key details).  This looks 100% related to a desktop profiler injecting mscorlib references to System.Private.CoreLib which is not supported.
