### ISSUE TITLE
CoreCLR build: Ensure all paths follow a pattern.

### ISSUE THREAD

**Issue by jcagme** [dotnet/coreclr#15334]
@karajas commented on [Fri Nov 10 2017](https://github.com/dotnet/core-eng/issues/2075)

This includes
 - All file paths should be fully qualified through msbuild.
 - Publishing search paths should be standardized on.
 - Publishing urls should follow a agreed upon schema.

**Comment by RussKeldorph** [comment]
Closing in favor of getting on arcade proper.
