### ISSUE TITLE
CoreCLR build: Setup Dumpling in CoreCLR Linux builds

### ISSUE THREAD

**Issue by jcagme** [dotnet/coreclr#15333]
@karajas commented on [Fri Nov 10 2017](https://github.com/dotnet/core-eng/issues/2074)

This would help use diagnose any seg faults that we see happening in coreclr builds. The Linux builds happen in Docker and get copied to the staging directory adjacent to the source directory on the VSTS build agent.

@DrewScoggins 

---

@maririos commented on [Thu Nov 30 2017](https://github.com/dotnet/core-eng/issues/2074#issuecomment-348353006)

@karajas could you please move this and the other CoreCLR issues to their repo?

**Comment by RussKeldorph** [comment]
dotnet/core-eng#5982

**Comment by RussKeldorph** [comment]
Closing in favor of #21134
