### ISSUE TITLE
Proposal: Add support for AOP scenarion

### ISSUE THREAD

**Issue by vbcodec** [dotnet/coreclr#15355]
AOP is increasingly used technique, and CLR should add suport for this echnique. Current AOP tools usually rely on converting assembly to add code that is called when function is starting, ending and when exception is raised. 

CLR should provide these possibilities, and external tools won;t be necessary. System.Reflection is good place that can be used to register callback handlers, to notify when functions / events / properties are used.

**Comment by jkotas** [comment]
Thanks for the suggestion. There are number of existing issues about AOP. Let's use those to discuss this problem space:

https://github.com/dotnet/corefx/issues/1935
https://github.com/dotnet/csharplang/issues/605
https://github.com/dotnet/csharplang/issues/107

If you think there are specific APIs that would help 3rd party AOP implementations, here is how to propose them: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by vbcodec** [comment]
I don';t think that there are any serious issues. CLR may recompile code from IL, if it detect that some handlers are registered for fiunction / event / property. For NET Native there may be two code paths, that can be composed depending on needs.  It is relative easy to achieve.

dotnet/csharplang#605 and dotnet/csharplang#107 do not apply here, as it is related to library level, not CLR
