### ISSUE TITLE
There is no "Native" directory

### ISSUE THREAD

**Issue by Injac** [dotnet/coreclr#1535]
Hi,
I just followed this guide here, to compile the coreclr repo on Linux:

https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md

Problem: there is no "Native" directory. Does this need to be updated? How to build the native components?

**Comment by mikedn** [comment]
Looks like the documentation is in need for an update, that Native thing has moved to the corefx repository.

**Comment by Injac** [comment]
Ok. Good to know, thanks for the quick feedback :)

**Comment by ellismg** [comment]
FWIW, The "Native" directory will be coming back in a few days, as mscorlib.dll will end up needing some native shims.

**Comment by gitchomik** [comment]
@Injac If yout are talking about "Native" source directory (in section "Build the Framework Native Components") is still in corefx repository (not coreclr) https://github.com/dotnet/corefx/tree/master/src/Native, so the documentation is no need for an update.

**Comment by Injac** [comment]
Ok. Thanks to all of you for the quick help.

**Comment by tzwlai** [comment]
Closing this issue since it looks like the problem has been resolved already.  Please feel free to reopen if needed.
