### ISSUE TITLE
Cannot succeeded compile the latest coreclr on macOS.

### ISSUE THREAD

**Issue by micli** [dotnet/coreclr#15352]
Environment:
micl-MBP-15:coreclr micl$ cmake --version
cmake version 3.9.4
CMake suite maintained and supported by Kitware (kitware.com/cmake).
Xcode Version 9.1 (9B55)

I have been updated all software by Apple Store before I started building action.
The building progress always stops at 100% with 13 errors.

repro steps:
`
1. mkdir dot-net
2. cd dot-net
3. git clone http://www.github.com/dotnet/coreclr
4. cd coreclr
5. ./build.sh
`
The building output has been attached.  I tried twice, all failed.

[Building-log.txt](https://github.com/dotnet/coreclr/files/1525990/Building-log.txt)

**Comment by micli** [comment]
There is something else, I want to ask you guys does .NET Core support LLDB debugging on macOS? I mean can I use LLDB that installed with Xcode to debugging .NET Core apps on macOS ?

**Comment by jkotas** [comment]
Many macro-redefined errors:

```
#define SCHAR_MIN   (-128)In file included from 
/Users/micl/dot-net/coreclr/src/ToolBox/SOS/lldbplugin/sosplugin.h:        ^8
:
In file included from /Users/micl/dot-net/coreclr/src/ToolBox/SOS/lldbplugin/inc/lldbservices.h:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/limits.h15::
65In file included from :/Users/micl/dot-net/coreclr/src/pal/inc/rt/palrt.h9::138 :
note: 
      previous /Users/micl/dot-net/coreclr/src/pal/inc/pal.hdefinition: 239is: 9here: 
error: 'CHAR_BIT'#define SCHAR_MIN (-__SCHAR_MAX__-1)
 macro        ^

      redefined [-Werror,-Wmacro-redefined]In file included from 
/Users/micl/dot-net/coreclr/src/ToolBox/SOS/lldbplugin/setsostidcommand.cpp:5:
In file included from /Users/micl/dot-net/coreclr/src/ToolBox/SOS/lldbplugin/sosplugin.h:8:
In file included from /Users/micl/dot-net/coreclr/src/ToolBox/SOS/lldbplugin/inc/lldbservices.h:15:
In file included from /Users/micl/dot-net/coreclr/src/pal/inc/rt/palrt.h:138:
/Users/micl/dot-net/coreclr/src/pal/inc/pal.h:242:9: error: 'SCHAR_MAX' macro
      redefined [-Werror,-Wmacro-redefined]
#define SCHAR_MAX     127
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/limits.h:60:9: note: 
      previous definition is here
#define SCHAR_MAX __SCHAR_MAX__
        ^
In file included from /Users/micl/dot-net/coreclr/src/ToolBox/SOS/lldbplugin/setsostidcommand.cpp:5:
In file included from /Users/micl/dot-net/coreclr/src/ToolBox/SOS/lldbplugin/sosplugin.h:8:
In file included from /Users/micl/dot-net/coreclr/src/ToolBox/SOS/lldbplugin/inc/lldbservices.h:15:
In file included from /Users/micl/dot-net/coreclr/src/pal/inc/rt/palrt.h:138:
/Users/micl/dot-net/coreclr/src/pal/inc/pal.h:243:9: error: 'UCHAR_MAX' macro
      redefined [-Werror,-Wmacro-redefined]
#define UCHAR_MAX     0xff
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/limits.h:70:9: note: 
      previous definition is here
#define UCHAR_MAX (__SCHAR_MAX__*2  +1)
        ^
```

**Comment by jkotas** [comment]
>  .NET Core support LLDB debugging on macOS? 

Yes, but it is pretty low-level: https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md#debugging-coreclr-on-os-x

**Comment by micli** [comment]
@jkotas Can you confirm this is an issue or it's my personal mistake? Thanks!

**Comment by jkotas** [comment]
I have not seen this error myself.

We have seen build breaks caused by XCode updates recently #15005. These errors may be a similar problem.

**Comment by micli** [comment]
@jkotas 
I can confirm that the issue caused by LLDB SDK compatible. I just fully compiled LLVM3.9 Clang 3.8 and LLDB 3.9. And then I "sudo make install" these components on my macOS. Finally I tried to compile coreclr again. It works!
This article
https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md#debugging-coreclr-on-os-x
really useful!
