### ISSUE TITLE
Numeric Constraint / Attribute on Generic Types

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/coreclr#15359]
[Link to VB: Numeric Constraint for Generics](https://github.com/dotnet/vblang/issues/214)
If we could add an attribute or constraint to generic type parameters, we could restrict the types to those that are considered numeric. *What is to be considered Numeric is a separate discussion.*
For the purpose of the proposal we are using the definition of `NumericTypeName' (from the VB Grammar) to define the meaning of Numeric.
```c#
Structure Range< [Numeric] Tx, [Numeric] Sx > {  }
```
Now that we're constrained the type, to a subset that we know have numerical operators. We are then permitted to use said operators with the generic object being defined.

Since is a fundamental change to how some generics work, the CLR should be aware of them.

**Comment by 4creators** [comment]
This is a language feature request which should be moved to `dotnet/csharplang` repo.

**Comment by RussKeldorph** [comment]
I believe this needs to be approved at the language level before it is interesting as an issue here.  Feel free to re-open if you disagree.
