### ISSUE TITLE
Port optimizations to TryFormat and ToString from the UTF-8 formatter

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/coreclr#15364]
We can optimize TryFormat/ToString for 32-bit.
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Number.Formatting.cs

Also, it is faster to first count the digits and then output backwards rather than outputting in reverse and then reversing it.

See related PRs from where we can port the optimizations: 
- https://github.com/dotnet/corefx/pull/25424#issuecomment-347744346
- https://github.com/dotnet/corefx/pull/25626#issuecomment-348798209

cc @stephentoub, @jkotas

**Comment by RussKeldorph** [comment]
@ahsonkhan Can this up-for-grab issue be moved to Future?

**Comment by ahsonkhan** [comment]
Yes. This perf optimization is not critical for 2.1. Thanks.

**Comment by Tornhoof** [comment]
Maybe for reference between CoreCLR and Utf8Formatter, especially DateTime could use a bit of love with formatting option 'o'.

``` ini

BenchmarkDotNet=v0.10.13, OS=Windows 10.0.17133
Intel Core i7-4790K CPU 4.00GHz (Haswell), 1 CPU, 8 logical cores and 4 physical cores
Frequency=3906250 Hz, Resolution=256.0000 ns, Timer=TSC
.NET Core SDK=2.1.300-preview1-008174
  [Host]     : .NET Core 2.1.0-preview3-26406-03 (CoreCLR 4.6.26405.01, CoreFX 4.6.26405.01), 64bit RyuJIT
  DefaultJob : .NET Core 2.1.0-preview3-26406-03 (CoreCLR 4.6.26405.01, CoreFX 4.6.26405.01), 64bit RyuJIT


```
|                   Method |      Mean |     Error |    StdDev |  Gen 0 | Allocated |
|------------------------- |----------:|----------:|----------:|-------:|----------:|
|       &#39;DateTime CoreCLR&#39; | 301.38 ns | 0.1300 ns | 0.1085 ns | 0.0224 |      96 B |
| &#39;DateTime Utf8Formatter&#39; |  65.48 ns | 0.0219 ns | 0.0194 ns | 0.0151 |      64 B |
|          &#39;Int64 CoreCLR&#39; |  61.36 ns | 0.0280 ns | 0.0262 ns | 0.0132 |      56 B |
|    &#39;Int64 Utf8Formatter&#39; |  29.88 ns | 0.0056 ns | 0.0043 ns | 0.0152 |      64 B |
|         &#39;Double CoreCLR&#39; | 172.05 ns | 0.0891 ns | 0.0695 ns | 0.0112 |      48 B |
|   &#39;Double Utf8Formatter&#39; | 201.66 ns | 0.0619 ns | 0.0549 ns | 0.0341 |     144 B |
|        &#39;Decimal CoreCLR&#39; |  98.98 ns | 0.0466 ns | 0.0364 ns | 0.0113 |      48 B |
|  &#39;Decimal Utf8Formatter&#39; | 103.14 ns | 0.2039 ns | 0.1908 ns | 0.0151 |      64 B |
|           &#39;Guid CoreCLR&#39; |  54.60 ns | 0.0256 ns | 0.0227 ns | 0.0247 |     104 B |
|     &#39;Guid Utf8Formatter&#39; |  42.63 ns | 0.1325 ns | 0.1035 ns | 0.0152 |      64 B |

**Comment by stephentoub** [comment]
> Maybe for reference between CoreCLR and Utf8Formatter, especially DateTime could use a bit of love with formatting option 'o'

I'm surprised by your results. https://github.com/dotnet/coreclr/pull/17092 effectively did bring the Utf8Formatter implementation over to DateTime.

**Comment by Tornhoof** [comment]
It's ``UtcNow`` vs ``Now``. If I change the benchmark to ``UtcNow`` it is:
``` ini

BenchmarkDotNet=v0.10.13, OS=Windows 10.0.17133
Intel Core i7-4790K CPU 4.00GHz (Haswell), 1 CPU, 8 logical cores and 4 physical cores
Frequency=3906250 Hz, Resolution=256.0000 ns, Timer=TSC
.NET Core SDK=2.1.300-preview1-008174
  [Host]     : .NET Core 2.1.0-preview3-26406-03 (CoreCLR 4.6.26405.01, CoreFX 4.6.26405.01), 64bit RyuJIT
  DefaultJob : .NET Core 2.1.0-preview3-26406-03 (CoreCLR 4.6.26405.01, CoreFX 4.6.26405.01), 64bit RyuJIT


```
|                   Method |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
|------------------------- |---------:|----------:|----------:|-------:|----------:|
|       &#39;DateTime CoreCLR&#39; | 93.86 ns | 0.0276 ns | 0.0245 ns | 0.0209 |      88 B |
| &#39;DateTime Utf8Formatter&#39; | 65.58 ns | 0.1712 ns | 0.1517 ns | 0.0151 |      64 B |

**Comment by stephentoub** [comment]
> It's UtcNow vs Now

Still surprised.  The code is basically the same, even for time zone stuff:
https://github.com/dotnet/coreclr/blob/721343dc84247d54ee5f3365b97b06090dfa8ade/src/mscorlib/shared/System/Globalization/DateTimeFormat.cs#L1128
vs
https://github.com/dotnet/corefx/blob/f5d31619f821e7b4a0bcf7f648fe1dc2e4e2f09f/src/System.Memory/src/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Date.O.cs#L18

**Comment by ahsonkhan** [comment]
> Yes the code is pretty much the same and as far as I can see, the asm output of benchmarkdotnet is pretty much the same too, so I have no idea what happens there. I reproduced it on two different systems, same behaviour.

Can you also share your csproj and the output of `dotnet --info` you used to compile/run? Maybe, the version is out-dated.

> I can create a dedicated bug for it, if you prefer that.

If there is still a performance difference, yes, please file a new issue.

**Comment by stephentoub** [comment]
And maybe briefly modify the benchmark code to do `Console.WriteLine(typeof(object).Assembly.Location)` just to confirm it is in fact loading the expect corelib.

**Comment by Tornhoof** [comment]
Assembly Location: ``C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.0-preview3-26406-03\System.Private.CoreLib.dll``
I tried it with multiple runtime versions and sdks too (from the last few days), the specific output of dotnet --info:
```ini
C:\WINDOWS\system32>dotnet --info
.NET-Befehlszeilentools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17133
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Host (useful for support):
  Version: 2.1.0-preview3-26406-03
  Commit:  a876b38f2e

.NET Core SDKs installed:
  1.0.2 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-preview2-30457 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-preview2-30457 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview3-26325-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview3-26329-05 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview3-26403-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview3-26405-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview3-26406-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I'll open a different bug for this.

**Comment by ahsonkhan** [comment]
If all else fails, maybe wait for a newer build after this gets merged - https://github.com/dotnet/corefx/pull/28873 (also, maybe this one a shot 2.1.0-preview3-26406-06).

**Comment by stephentoub** [comment]
See my comment at https://github.com/dotnet/coreclr/issues/17461#issuecomment-379364797... the code is comparing apples to oranges.

**Comment by stephentoub** [comment]
Also, why are the coreclr tests calling ToString and the Utf8Formatter tests aren't, and why are the coreclr tests doing stackalloc and the Utf8Formatter aren't?  That's just extra overhead on the coreclr test, further making the comparison invalid.  Fixing those issues, I get this:
```
         'Format DateTime CoreCLR UTC' |  81.60 ns | 0.3302 ns | 0.3089 ns |       0 B |
   'Format DateTime Utf8Formatter UTC' |  72.57 ns | 1.1241 ns | 0.9387 ns |       0 B |
       'Format DateTime CoreCLR Local' | 291.86 ns | 1.6520 ns | 1.5453 ns |       0 B |
 'Format DateTime Utf8Formatter Local' | 286.17 ns | 2.5988 ns | 2.4310 ns |       0 B |
```

**Comment by stephentoub** [comment]
Closing in favor of https://github.com/dotnet/corefx/issues/30612, as that one has check boxes :)
