### ISSUE TITLE
Proposal: Primitively Support Immutable Types 

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/coreclr#15368]
Immutable object is an object whose state can not be changed once its created.

There is no way to explicitly declare immutable type. it can be only implied by usage but I think this is not optimal. not for functional programming or to some degree for OOP.

It would be beneficial to support immutable types strictly at CLR site. so that other languages and programmers can benefit from it. Immutability could be just noted using a modifier at declaration site (eg. declaration of type Foo).

some types are partially immutable while others are completely immutable, we are not talking about weak immutable types, as its already achievable. but for _immutable_ or _strongly immutable_ types there can be more gain and benefit if such property was supported at lower levels.

Properties of immutable type:

- All references to immutable type is referentially transparent.
- methods of immutable type are pure. (they can not access static content)
- immutable type can only declare immutable records.
- there can be no assignments other than local assignments.

What benefits does this provide?

- generic immutable types are inherently generic covariant. (be it class or struct)
- they are inherently thread safe.
- all references are transparent, with this fact, certain optimizations can be done before and after compilation.
- since type is known to be immutable, copying is not needed and can make programmer code and execution of program more efficient and simpler. 
- there can be primitive support for [COW
](https://en.wikipedia.org/wiki/Copy-on-write)
- there can be primitive support for interning immutable type. (how this is requested at higher levels needs to be discussed for each language independently.)
- there is no need to heavily change and reformulate what currently is defined at CLR (or what ever this relates to). its just extra candy that hopefully does not clash with entire design of CLR.

What else did I miss? please point it out if there is more to consider. 

And please make this happen some day ❤️

**Comment by mikedn** [comment]
"Immutable types" is first and foremost a language feature. It's not clear what, if anything, the runtime must provide to make such a feature feasible.

**Comment by MkazemAkhgary** [comment]
did you read `What benefits does this provide?`

**Comment by mikedn** [comment]
> did you read What benefits does this provide?

It's irrelevant. Immutable types is a relatively complex language feature and as such it should start in the language world. Once the language settles on a design the runtime may be asked to provide the required features (if any). And possible implement useful optimizations. 

After all, you said it yourself:

> there is no need to heavily change and reformulate what currently is defined at CLR (or what ever this relates to). its just extra candy that hopefully does not clash with entire design of CLR.

**Comment by MkazemAkhgary** [comment]
Then why in c# repo when it was proposed to support covariant classes it was rejected? It was claimed that this requires CLR change. https://github.com/dotnet/roslyn/issues/171#issuecomment-239947729

May i ask where is this _language world_ so we can start from there? :)

Maybe If it starts from then language designers would less complain. Because what language is based on CLR can freely extend.

If you notice for runtime features i said _"it can"_ . Those are not in priority. But something that can be achieved later but not necessairly.

It should start from some where but if started here it would encourage all languages to equally evolve with this feature.

**Comment by mikedn** [comment]
> Then why in c# repo when it was proposed to support covariant classes it was rejected? It was claimed that this requires CLR change. dotnet/roslyn#171 (comment)

What variance has to do with immutability? I mean, OK, immutability can sometimes help with that but surely variance is not the main purpose of immutability.

> May i ask where is this language world so we can start from there? :)

I don't know, the csharplang repo perhaps?

> Maybe If it starts from here then language designers would less complain

If it starts here then there's a good change that the language designers would complain more. Because what the runtime provided isn't what they need.

> If you notice for runtime features i said "it can" . Those are not in priority. But something that can be achieved later but not necessairly today.

I'm lost. You're contradicting yourself. You claim runtime support is not strictly necessary but yet you create an issue in the runtime repo.

**Comment by MkazemAkhgary** [comment]
Ok. I may seem to be condradicting my self. But what matters to me is end resulglt. I want this feature. How and where its implemented doesnt really matter to me. I just had to post it. I thought here is good place to start. Also because this is proposed on general concept of immutability its less likey to be thrown away. 

If i propose it in csharplang i can speculate how it goes. Its not beneficial. It doesnt worth the effort it takes. etc etc. But i post it there and see how it goes. Ill post it later when i have time to think and write good :)

I also said if it starts here its beneficial to other languages as well. I want my candy so im just trying to get it ;)

**Comment by svick** [comment]
The difference between immutability and class covariance is that covariance is a runtime feature and changing it would require runtime support. I don't see what benefits would runtime support have for immutability. For example, have a look at F#: it supports immutability well and it doesn't require anything special from the runtime.

**Comment by MkazemAkhgary** [comment]
@svick Well, if c# supports immutability as well, can we have immutable covariance classes/structs?

Main point is, we dont want to have smart runtime that decides wether or not a class can be covariance. With a alternative approach, immutable types can be covariant and it will be easier to implement. 

other optimizations as well can be considered later.

**Comment by MkazemAkhgary** [comment]
In conclusion, this will make things to evolve faster and easier. No fancy analysis of class usage. It makes runtime simpler it can also optimize more stuff in safe manner. So thats my answer to what benefit runtime has for supporting immutability.

**Comment by karelz** [comment]
It does not seem like a feature we would implement in Runtime, unless languages ask for it. F# seems to be doing well without it so far.

Given there was only one vote for it so far, and couple of votes against, I will close it.
If we see more upvotes in future, or more duplicates, or languages asks, we can reconsider.
