### ISSUE TITLE
Have assembly/module load events report if image contains R2R codegen

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#15392]
Currently it does not seem to be possible to determine if an assembly/module contains R2R codegen from the event stream. This fact is of interest to analysis tools since R2R code has distinctly different performance characteristics.

It seems like we could simply add new AssemblyFlag and ModuleFlag values to report on this directly.

It would also be nice to know if the R2R code in an image is not being used. I need look at the granularity of the R2R dependence checks to see if this is an assembly/module level thing or whether it also needs to appear for individual methods.

**Comment by lt72** [comment]
@brianrob FYI

**Comment by brianrob** [comment]
Sounds like a great addition to me.  @AndyAyersMS are you planning to implement this or should we mark it up-for-grabs once you find out the granularity of the R2R code use/rejection policy?

FYI @vancem.

**Comment by AndyAyersMS** [comment]
The first part looks simple enough on the producer side. I don't know what all is involved in getting event consumers to know about the new flag value(s). But it should be harmless to set extra flag bits even if consumers aren't aware of what they mean.

I'll investigate the second part further and update this note when I know more.

**Comment by brianrob** [comment]
Yes, setting the value on the producer side should be fine as long as it's done in a backwards compatible way.  I can show you what to do in TraceEvent/PerfView to make the flag consumable.

**Comment by AndyAyersMS** [comment]
There is per-method body validation for R2R. To properly distinguish the case where crossgen did not precompile a method vs the case where the precompiled method can't be used because of breaking changes in dependent assemblies, it looks like we would need to distinguish which failure path is taken in `ReadyToRunInfo::GetEntryPoint` -- the first series of checks determines if there is an entry for the method and then if so, a second series of checks sees if the method's body can be used.

We should be able to pass the information around via the `PrepareCodeConfig` which is an on-stack class present during the attempt to load prejitted code and also during the jit request (which eventually invokes the event logging). We just need to pass it down to the R2R layer so it can record what happened.

Similar thing should also be viable for classic NGEN images though if we see jitting in such an image it must be the case that the method was omitted from prejitting as there is no second-level compatibility checking. But for consistency sake it might be worth tracking this the same way.

**Comment by AndyAyersMS** [comment]
Here's a cut at the provider side: [master...AndyAyersMS:AddR2RFlagsToEvents](https://github.com/dotnet/coreclr/compare/master...AndyAyersMS:AddR2RFlagsToEvents).

Not super happy with the names so feel free to suggest alternatives.

Also wondering if I should split out the cases where a profiler inhibits using prejitted code from the case where R2R versioning inhibits using prejitted code.

FYI @jkotas

**Comment by AndyAyersMS** [comment]
Fixed via #15801 and #16184.
