### ISSUE TITLE
Unable to compile HelloWorld.cs on Ubuntu after following instructions

### ISSUE THREAD

**Issue by glen-84** [dotnet/coreclr#154]
I followed the instructions [here](https://github.com/dotnet/coreclr/wiki/Building-and-Running-CoreCLR-on-Linux) but the 2nd-to-last step (mcs) fails with:

    glen@ubuntu:~/coreclr-demo/runtime$ mcs /nostdlib /noconfig /r:../packages/System.Console.4.0.0-beta-22512/lib/contract/System.Console.dll /r:../packages/System.Runtime.4.0.20-beta-22512/lib/contract/System.Runtime.dll HelloWorld.cs
    error CS0009: Metadata file `/home/glen/coreclr-demo/runtime/../packages/System.Runtime.4.0.20-beta-22512/lib/contract/System.Runtime.dll' does not contain valid metadata
    error CS0518: The predefined type `System.Object' is not defined or imported
    error CS0518: The predefined type `System.ValueType' is not defined or imported
    error CS0518: The predefined type `System.Attribute' is not defined or imported
    error CS0518: The predefined type `System.Int32' is not defined or imported
    error CS0518: The predefined type `System.UInt32' is not defined or imported
    error CS0518: The predefined type `System.Int64' is not defined or imported
    error CS0518: The predefined type `System.UInt64' is not defined or imported
    error CS0518: The predefined type `System.Single' is not defined or imported
    error CS0518: The predefined type `System.Double' is not defined or imported
    error CS0518: The predefined type `System.Char' is not defined or imported
    error CS0518: The predefined type `System.Int16' is not defined or imported
    error CS0518: The predefined type `System.Decimal' is not defined or imported
    error CS0518: The predefined type `System.Boolean' is not defined or imported
    error CS0518: The predefined type `System.SByte' is not defined or imported
    error CS0518: The predefined type `System.Byte' is not defined or imported
    error CS0518: The predefined type `System.UInt16' is not defined or imported
    error CS0518: The predefined type `System.String' is not defined or imported
    error CS0518: The predefined type `System.Enum' is not defined or imported
    error CS0518: The predefined type `System.Delegate' is not defined or imported
    error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
    error CS0518: The predefined type `System.Void' is not defined or imported
    error CS0518: The predefined type `System.Array' is not defined or imported
    error CS0518: The predefined type `System.Type' is not defined or imported
    error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
    error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
    error CS0518: The predefined type `System.IDisposable' is not defined or imported
    error CS0518: The predefined type `System.IntPtr' is not defined or imported
    error CS0518: The predefined type `System.UIntPtr' is not defined or imported
    error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
    error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
    error CS0518: The predefined type `System.Exception' is not defined or imported
    Compilation failed: 32 error(s), 0 warnings

Distro: Ubuntu 14.04.1 LTS

**Comment by shahid-pk** [comment]
where is your packages directory located ?

**Comment by kangaroo** [comment]
The instructions seem wrong.  Add -r:/path/to/coreclr/mscorlib.dll

/nostdlib removes all imports.

**Comment by kangaroo** [comment]
cc @ellismg

**Comment by glen-84** [comment]
@shahid-pk

    glen@ubuntu:~/coreclr-demo$ ls -lsh
    total 8,0K
    4,0K drwxrwxr-x 19 glen glen 4,0K Feb  8 18:37 packages
    4,0K drwxrwxr-x  2 glen glen 4,0K Feb  8 18:38 runtime

**Comment by glen-84** [comment]
@kangaroo

    glen@ubuntu:~/coreclr-demo/runtime$ sudo mcs /nostdlib /noconfig /r:mscorlib.dll /r:../packages/System.Console.4.0.0-beta-22512/lib/contract/System.Console.dll /r:../packages/System.Runtime.4.0.20-beta-22512/lib/contract/System.Runtime.dll HelloWorld.cs
    error CS0009: Metadata file `/home/glen/coreclr-demo/runtime/../packages/System.Runtime.4.0.20-beta-22512/lib/contract/System.Runtime.dll' does not contain valid metadata
    Compilation failed: 1 error(s), 0 warnings

**Comment by shahid-pk** [comment]
delete every ../ after every  /r: 
you have deleted only one.

**Comment by glen-84** [comment]
@shahid-pk The packages folder is in the parent folder (coreclr-demo).

The paths are correct, but there's something wrong with the metadata.

**Comment by shahid-pk** [comment]
ok i got it you are using System.Console.dll from packages but you should use the one you compiled .... not the one from packages.

**Comment by davidfowl** [comment]
Instead of using mcs to manually compile, you should consider using kpm build. You'll be able to compile against the same packages and you'll get a DLL as output that you can use to run with corerun

**Comment by glen-84** [comment]
@shahid-pk

    glen@ubuntu:~/coreclr-demo/runtime$ sudo mcs /nostdlib /noconfig /r:mscorlib.dll /r:System.Console.dll /r:../packages/System.Runtime.4.0.20-beta-22512/lib/contract/System.Runtime.dll HelloWorld.cs
    error CS0009: Metadata file `/home/glen/coreclr-demo/runtime/../packages/System.Runtime.4.0.20-beta-22512/lib/contract/System.Runtime.dll' does not contain valid metadata
    Compilation failed: 1 error(s), 0 warnings

I tried this as well:

    sudo mcs /nostdlib /noconfig /r:mscorlib.dll /r:System.Runtime.dll HelloWorld.cs

It worked, but running it I get:

    glen@ubuntu:~/coreclr-demo/runtime$ ./corerun HelloWorld.exe
    Hello, Windows...

      {0x7fcfd0e89780-0x7fcfcf8e44e0} ASSERT [DEBUG  ] at /home/glen/git/coreclr/src/pal/src/arch/i386/context.cpp.682: Got unknown signal number 11 with code 128

The documentation doesn't seem very accurate.

**Comment by shahid-pk** [comment]
because /r:System.Runtime.dll make mcs compile against mono's System.Runtime.dll. And in that version of the assembly their are things that .net core does not have that is why that error i guess.
you should try kpm build as @davidfowl  suggested.

**Comment by glen-84** [comment]
I think I'll just wait for the documentation to be fixed. I have no idea what the project.json file should look like, etc.

Thanks.

**Comment by ellismg** [comment]
@glen-84, your invocation of msc prints the following:

```
glen@ubuntu:~/coreclr-demo/runtime$ mcs /nostdlib /noconfig /r:../packages/System.Console.4.0.0-beta-22512/lib/contract/System.Console.dll /r:../packages/System.Runtime.4.0.20-beta-22512/lib/contract/System.Runtime.dll HelloWorld.cs
error CS0009: Metadata file `/home/glen/coreclr-demo/runtime/../packages/System.Runtime.4.0.20-beta-22512/lib/contract/System.Runtime.dll' does not contain valid metadata
```

The System.Runtime.dll does not contain valid metadata error is a problem.  Can you tell me what version of msc you have and how you installed it?

@kangaroo Not referencing mscorlib.dll is by design.  You need to compile against the .NET Core Surface area (System.Runtime.dll and System.Console.dll).  Building against mscorlib.dll is completely unsupported and will produce assemblies that may or may not work.  For example, the implementation of Console in mscorlib does not support all the features cross platform, whereas the one in System.Console.dll does.  If you compile against mscorlib directly, it's very likely that you'll run into bugs as you try to use more and more features.

**Comment by glen-84** [comment]
@ellismg

Mono C# compiler version 3.12.0.0

I'm pretty sure that I followed your instructions for the installation.

**Comment by ellismg** [comment]
Thanks!  That matches the version I have.

Can you ```sha1sum``` the System.Runtime.dll contract (/home/glen/coreclr-demo/packages/System.Runtime.4.0.20-beta-22512/lib/contract/System.Runtime.dll)

I get the following:

```31bae453bc467516b448498c8aef330df86ac11a  System.Runtime.dll```

I ran these instructions on multiple machines so I'm pretty sure they are correct.  If you get a different sha1sum could you try deleting the stuff under packages and nuget restoring again?

**Comment by glen-84** [comment]
0fa1e6ec31117775b8f883e2b4ff934a97c98077  /home/glen/coreclr-demo/packages/System.Runtime.4.0.20-beta-22512/lib/contract/System.Runtime.dll

I did as you said and now the hash is the same. :-|

However, when I run it ...

    glen@ubuntu:~/coreclr-demo/runtime$ ./corerun HelloWorld.exe linux
    {0x7f1b6d985780-0x7f1b6c3e04e0} ASSERT [MISC   ] at /home/glen/git/coreclr/src/pal/src/misc/fmtmessage.cpp.239: Unable to continue due to missing library.

**Comment by cnblogs-dudu** [comment]
@glen-84 Same exception "Unable to continue due to missing library"  in #164 . Try following:
```
git clone https://github.com/cnblogs-dudu/CoreClrHelloWorld.git
cd CoreClrHelloWorld
runtime_linux/corerun app/HelloWorld.exe
```

**Comment by cnblogs-dudu** [comment]
There are two mscorlib.dll. One is for mcs. Another is for corerun. When `./corerun HelloWorld.exe linux`, the mscorlib.dll in runtime directory should come from binaries\intermediates\amd64\Debug\mscorlib.dll that produce by `build.cmd unixmscorlib`.

**Comment by glen-84** [comment]
@cnblogs-dudu

The mscorlib.dll in my runtime folder *is* from the output of that command.

**Comment by ellismg** [comment]
@glen-84 Are you still hitting this?  I have updated the documents to take into account the new dependencies and layouts of the builds.  If you're still hitting issues let me know and we can try to figure things out.

**Comment by glen-84** [comment]
@ellismg,

I started from scratch, and ...

1. I get "Visual Studio 2013 Community (free) is a pre-requisite to build this repository." -- I have Express, so I commented-out this check:

    -if exist "%VS120COMNTOOLS%\..\IDE\devenv.exe" goto CheckMSBuild
    +::if exist "%VS120COMNTOOLS%\..\IDE\devenv.exe" goto CheckMSBuild
    +goto CheckMSBuild

2. In your docs, the path to System.Diagnostics.Debug.dll is incorrect, it should be `bin\Unix.AnyCPU.Debug\System.Diagnostics.Debug\System.Diagnostics.Debug.dll`

3. When I run the EXE I get:

    glen@ubuntu:~/coreclr-demo/runtime$ ./corerun HelloWorld.exe linux
    Assert failure (unable to format)
    /home/glen/git/coreclr/src/utilcode/ccomprc.cpp
    false && "UNIXTODO: Implement string loading from resources"
    **** MessageBox invoked, title 'Assert failure (unable to format)' ****
      false && "UNIXTODO: Implement string loading from resources"
    ********

    Assert failure (unable to format)
    /home/glen/git/coreclr/src/utilcode/ccomprc.cpp
    false && "UNIXTODO: Implement string loading from resources"
    **** MessageBox invoked, title 'Assert failure (unable to format)' ****
      false && "UNIXTODO: Implement string loading from resources"
    ********

    Assert failure (unable to format)
    /home/glen/git/coreclr/src/utilcode/ccomprc.cpp
    false && "UNIXTODO: Implement string loading from resources"
    **** MessageBox invoked, title 'Assert failure (unable to format)' ****
      false && "UNIXTODO: Implement string loading from resources"
    ********

    ^C{0x7fe9facb5700-0x7fea918ef780} ASSERT [EXCEPT ] at /home/glen/git/coreclr/src/pal/src/exception/signal.cpp.497: Should not reach fatal_signal_handler
    Trace/breakpoint trap (core dumped)

I'm pretty sure I followed the instructions correctly.

**Comment by ellismg** [comment]
@glen-84 Can you do the following:  export COMPlus_DumpJittedMethods=1 and then run corerun again and share the output in a gist?  I'm interested in figuring out how far the runtime got before blowing up.

**Comment by glen-84** [comment]
https://gist.github.com/glen-84/2a850574cce083c30ffe

Seems to be a FileLoadException?

Do you think it would help if I installed mono-complete instead of just mono-devel?

**Comment by ellismg** [comment]
I have things working with mono-devel, so I don't think you should need complete.  If you prepend the call to corerun with strace and grep around the output for "open(" syscalls, you can see what library we were trying to load when we blow up.  That might be helpful.  I wonder if for some reason we are trying to use the System.Console type out of mscorlib instead of the standalone one.  If that was the case, I expect things might not work correctly.

**Comment by glen-84** [comment]
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
    open("/usr/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
    open("/home/glen/coreclr-demo/runtime/libcoreclr.so", O_RDONLY|O_CLOEXEC) = 3
    open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
    open("/usr/lib/x86_64-linux-gnu/libunwind.so.8", O_RDONLY|O_CLOEXEC) = 3
    open("/lib/x86_64-linux-gnu/liblzma.so.5", O_RDONLY|O_CLOEXEC) = 3
    open("/etc/localtime", O_RDONLY|O_CLOEXEC) = 3
    open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
    open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 8
    open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 8
    open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 8
    open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 8
    open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 8
    open("/home/glen/coreclr-demo/runtime/mscorlib.ni.dll", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/home/glen/coreclr-demo/runtime/mscorlib.dll", O_RDONLY) = 8
    open("/dev/zero", O_RDWR)               = 10
    open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 9
    open("/home/glen/coreclr-demo/runtime/libcoreclr", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/home/glen/coreclr-demo/runtime/HelloWorld.exe", O_RDONLY) = 9
    open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 12
    open("/dev/zero", O_RDWR)               = 12
    open("/home/glen/coreclr-demo/runtime/System.Runtime.dll", O_RDONLY) = 11
    open("/dev/zero", O_RDWR)               = 14
    open("/home/glen/coreclr-demo/runtime/System.Console.dll", O_RDONLY) = 13
    open("/dev/zero", O_RDWR)               = 16
    open("/home/glen/coreclr-demo/runtime/System.IO.dll", O_RDONLY) = 15
    open("/dev/zero", O_RDWR)               = 18
    open("/home/glen/coreclr-demo/runtime/System.Threading.dll", O_RDONLY) = 17
    open("/dev/zero", O_RDWR)               = 20
    open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 17
    open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 17

**Comment by ellismg** [comment]
No smoking gun there.  Let me think a bit on what the best way to debug this is.

**Comment by glen-84** [comment]
Are you using a different distro?

**Comment by ellismg** [comment]
Nope.  14.04 LTS

matell@MATELL-UB:~/git/coreclr$ uname -a
Linux MATELL-UB 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by glen-84** [comment]
glen@ubuntu:~$ uname -a
    Linux ubuntu 3.13.0-46-generic #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015 x86_64                                                            x86_64 x86_64 GNU/Linux

I'm just trying to understand why it works for you but not for me.

**Comment by ellismg** [comment]
I really want to figure this out as well.

Is there some way for you to share your runtime directory with me?  Compressed it is like 30 meg, which may be hard to upload, but if you're open to it we can figure out a solution.  Feel free to e-mail me as well: matell@microsoft.com.

**Comment by glen-84** [comment]
This should work: https://drive.google.com/file/d/0BzpJrZ9UkZtxUmhORHJDN3JSeUk/view?usp=sharing

**Comment by ellismg** [comment]
Thanks!

Can you let me know what Sha your HEAD is at in corefx when you build System.Console.dll?  If I replace your System.Console.dll assembly with my own, everything works.  Looking at the IL for your System.Console.dll it doesn't look obviously incorrect, so I want to dig a little more.

**Comment by glen-84** [comment]
Glen@GLEN-PC /D/Programming/Git/corefx (master)
    $ git rev-parse HEAD
    0e73355555771af3a8f6dbc8318f8fe2866512b1

Is it normal that after building I get a bunch of modifications like this?:

    Glen@GLEN-PC /D/Programming/Git/corefx (master)
    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.

    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

            modified:   src/Microsoft.Win32.Registry/src/Resources/SR.cs
            modified:   src/System.Collections.Concurrent/src/Resources/SR.cs
            modified:   src/System.Collections.Immutable/src/Resources/SR.cs
            modified:   src/System.Collections.NonGeneric/src/Resources/SR.cs
            modified:   src/System.Collections.Specialized/src/Resources/SR.cs
            modified:   src/System.ComponentModel.Annotations/src/Resources/SR.cs
            etc.

Diff:

    Glen@GLEN-PC /d/Programming/Git/corefx (master)
    $ git diff src/Microsoft.Win32.Registry/src/Resources/SR.cs
    warning: LF will be replaced by CRLF in src/Microsoft.Win32.Registry/src/Resources/SR.cs.
    The file will have its original line endings in your working directory.

**Comment by ellismg** [comment]
Thanks!

I think a bug has crept into CoreFx, since I'm able to reproduce your issue if I build at that revision.  Can you try building from 2416d382ab092890f5cf4d9e0fea838b4789a4ba?  I verified that works for me.

I will start figuring out what change caused the break.

I also see your LF issues.  We recently changed the SR files are generated, so they are now updated at build time.  We must be writing the wrong line endings.  I will work to get that fixed as well.

**Comment by ellismg** [comment]
The issue was due to some package updates we did after I edited the guide yesterday.  This caused the packages.config in the guide to have outdated versions of some assemblies and hence that caused the assembly load failures.  I have updated the Wiki to include a new packages.config with the correct versions.

**Comment by glen-84** [comment]
ellismg@linux:~/coreclr-demo/runtime$ mcs /nostdlib /noconfig /r:../packages/System.Console.4.0.0-beta-22512/lib/contract/System.Console.dll /r:../packages/System.Runtime.4.0.20-beta-22512/lib/contract/System.Runtime.dll HelloWorld.cs

Should be:

    ellismg@linux:~/coreclr-demo/runtime$ mcs /nostdlib /noconfig /r:../packages/System.Console.4.0.0-beta-22703/lib/contract/System.Console.dll /r:../packages/System.Runtime.4.0.20-beta-22703/lib/contract/System.Runtime.dll HelloWorld.cs

... and now it works! :smile:

Also, the LF issue seems to have been fixed in a later commit.

Thanks for your help. :+1:

**Comment by ellismg** [comment]
Thanks @glen-84 for pointing out the issue in the wiki and for working with me to validate everything.
