### ISSUE TITLE
WindowsRuntimeMarshal.EventCacheKey should implement GetHashCode, Equals

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#15415]
The struct [`EventCacheKey`](https://github.com/dotnet/coreclr/blob/5304962d18bccdfe84f08c7ffb1230c3c4d1763a/src/mscorlib/src/System/Runtime/InteropServices/WindowsRuntime/WindowsRuntimeMarshal.cs#L354-L363) is used as a dictionary key so should implement `IEquatable<T>` and `GetHashCode`, `Equals`

**Comment by jkotas** [comment]
I do not see it used as key. Where is it used exactly?

**Comment by benaadams** [comment]
Sorry mean struct `EventCacheKey` is used in `Dictionary<EventCacheKey, EventCacheEntry>`

https://github.com/dotnet/coreclr/blob/5304962d18bccdfe84f08c7ffb1230c3c4d1763a/src/mscorlib/src/System/Runtime/InteropServices/WindowsRuntime/WindowsRuntimeMarshal.cs#L519-L520)

**Comment by benaadams** [comment]
hmm... uses its own `EventCacheKeyEqualityComparer`

**Comment by benaadams** [comment]
Uses its own EventCacheKeyEqualityComparer; but the methods could be moved to the struct and then it will work with the non interface devirtualization (in Dictionary CQ PR)
