### ISSUE TITLE
CoreCLR build: Unify arguments for each leg

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/coreclr#15426]
@karajas commented on [Fri Nov 10 2017](https://github.com/dotnet/core-eng/issues/2077)

This is feedback from the arm64 toolsets argument change.

Questions to address: 
 - Is there a way to simplify the pipeline in anyway? (no. of pipelines, no. of legs, no. of jsons to maintain)
 - Is there a way to simplify the arguments passed to each build?
 - Is there a way to test any change to the arguments and validate before merging?

---

@maririos commented on [Thu Nov 16 2017](https://github.com/dotnet/core-eng/issues/2077#issuecomment-345066095)

Is there a way this could be applied to all the repos instead of just CoreCLR?

**Comment by RussKeldorph** [comment]
@Chrisboh, @maririos, @karajas Is there work planned to address this issue in 2.1, or are these just open questions about possible future improvements?  If the former, could you clarify what will by done and by whom?  If the latter, could you change the milestone to Future?

**Comment by karajas** [comment]
Reviewing the questions
> Is there a way to simplify the pipeline in anyway?
The main issue with this might have happened during the work to move to the transport feed, which required understanding the build layout between each leg and the fact that the test build waits for one OS to overwrite another and the fact that we have to build the tests on Windows.

> Is there a way to simplify the arguments passed to each build?
> Is there a way this could be applied to all the repos instead of just CoreCLR?
This is something I would be happy to look over (along with simplifying the pipelines) but currently the push seems to be on build reliability. For which, we need a set of pipelines and arguments that are stable.

> Is there a way to test any change to the arguments and validate before merging?
We do have this in place now. We have a PB Local Run option that can be toggled.

Currently, the CoreCLR build seems ok for now. I can go ahead and close this out if needed.

**Comment by RussKeldorph** [comment]
@karajas I'll go ahead and close.  Please create a new issue to track specific changes if/when they are needed.  Thanks.
