### ISSUE TITLE
Building mscorlib fails with Unrecognized option: '/test:moduleName=CommonLanguageRuntimeLibrary'

### ISSUE THREAD

**Issue by roterdam** [dotnet/coreclr#1545]
I opened mscorlib.csproj in Visual Studio and tried to build it, and it failed with the following error:

Severity	Code	Description	Project	File	Line	Source
Error		Unrecognized option: '/test:moduleName=CommonLanguageRuntimeLibrary'	mscorlib	C:\coreclr\src\mscorlib\CSC		Build

Are there special instructions to build it without building full coreclr?

**Comment by shahid-pk** [comment]
from command line or powershell type this **build.cmd windowsmscorlib** to build mscorlib only, if you are on windows.

**Comment by AlexGhiondea** [comment]
@roterdam which version of VS are you using? I am guessing VS 2015. 

The error comes from the fact that we are trying to use a switch that Roslyn does not support but the native compiler does support.

When we were bringing up the open source build for mscorlib we needed to support both compilers so we introduced a property (UseRoslynCompiler) that triggers which switches to set.

You can fix this locally by updating the default value for this property to 'true' in the [GenerateCompilerResponseFile.targets](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/GenerateCompilerResponseFile.targets) file.

I hope there might be a way to detect if the Roslyn compiler is available and use that logic for setting this property. I'll try looking into this.

**Comment by roterdam** [comment]
Thanks @AlexGhiondea , yes using VS2015. I did try your suggestion and @shahid-pk both works, so I'm good.

**Comment by stephentoub** [comment]
> both works, so I'm good.

Great.

**Comment by hynguyen2610** [comment]
@AlexGhiondea 
Could you explain more clearly about "You can fix this locally by updating the default value for this property to 'true' in the GenerateCompilerResponseFile.targets file "
I opened the file but I don't know where to modify the default value

**Comment by AlexGhiondea** [comment]
You can try setting the property inside the property group like this:

<UseRoslynCompiler>True</UseRoslynCompiler>
