### ISSUE TITLE
CoreClr publish restoring feed package to root of drive

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/coreclr#15495]
@chcosta commented on [Wed Dec 06 2017](https://github.com/dotnet/core-eng/issues/2229)

In an unrelated investigation, I saw that this build definition, https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/index?buildId=1194955, is doing a `dotnet restore` of the `init-tools.msbuild` project and assets are getting generated into the root folder

Machine name: ddvsowinage041
```
E:\A>dir e:\ /b
2.0.0-prerelease-02124-02
2.0.0-prerelease-02126-01
2.0.0-prerelease-02130-01
2.0.0-prerelease-02131-01
2.0.0-prerelease-02202-02
2.0.0-prerelease-02203-01
2.0.0-prerelease-02208-03
2.0.0-prerelease-02208-04
2.0.0-prerelease-02210-05
2.0.0-prerelease-02215-01
2.0.0-prerelease-02219-01
2.1.0-prerelease-02221-02
2.1.0-prerelease-02228-01
2.1.0-prerelease-02301-01
2.1.0-prerelease-02304-01
A
clrcompression.dll.requires_signing
external
Microsoft
Packages
...

E:\A>dir e:\2.1.0-prerelease-02304-01 /b
init-tools.msbuild.nuget.cache
init-tools.msbuild.nuget.g.props
init-tools.msbuild.nuget.g.targets
project.assets.json
```

Looking at one of the generated targets files or the `project.assets.json` file, it appears that the package which is being restored to the root is Microsoft.DotNet.Build.Tasks.Feed.

Here's the contents of `init-tools.msbuild.nuget.g.targets`
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)microsoft.dotnet.build.tasks.feed\2.1.0-prerelease-02301-01\build\Microsoft.DotNet.Build.Tasks.Feed.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.dotnet.build.tasks.feed\2.1.0-prerelease-02301-01\build\Microsoft.DotNet.Build.Tasks.Feed.targets')" />
  </ImportGroup>
</Project>
```

I have not investigated further to determine if this is strictly in the above mentioned build definition or any usage of init-tools which restores the feed package.
FYI @karajas @jcagme 

---

@jcagme commented on [Wed Dec 06 2017](https://github.com/dotnet/core-eng/issues/2229#issuecomment-349813937)

@wtgodbe I assume this is not planned but can you please double check?

---

@wtgodbe commented on [Thu Dec 07 2017](https://github.com/dotnet/core-eng/issues/2229#issuecomment-350060133)

This is definitely not intended. I have no idea why only the Microsoft.DotNet.Build.Tasks.Feed package would be restored but not the other 2 packages in init-tools.msbuild - the only difference I see between it and the other 2 is that its name is parameterized, and that it is imported explicitly here - https://github.com/dotnet/coreclr/blob/62aef543f5f6a1c6f9b0890fbfe37da72714d27e/src/publish.proj#L5. Other than that I don't see it referenced in CoreCLR anywhere.

---

@ChadNedzlek commented on [Tue Dec 12 2017](https://github.com/dotnet/core-eng/issues/2229#issuecomment-351195658)

I... don't really have any idea where to start here. Do we know what code is restoring those packages? There's so much indirection and parameterization that I don't even know what repository to start looking in.

---

@ChadNedzlek commented on [Tue Dec 12 2017](https://github.com/dotnet/core-eng/issues/2229#issuecomment-351196716)

I think it's this file: https://github.com/dotnet/coreclr/blob/master/init-tools.msbuild, and presumably the problem is that "ToolsDir" isn't defined, and the restore is using the BaseIntermediateOutputPath variable to decide where to do the restore?

---

@wtgodbe commented on [Tue Dec 12 2017](https://github.com/dotnet/core-eng/issues/2229#issuecomment-351197032)

That seems reasonable, normally I'd assume we'd be building that file through init-tools.cmd, but if it's being built directly it wouldn't know any value for "ToolsDir"

---

@ChadNedzlek commented on [Tue Dec 12 2017](https://github.com/dotnet/core-eng/issues/2229#issuecomment-351203913)

That definitely seems to be what's happening.  This seems like a bug in the coreCLR version of the init-tools.cmd?  It doesn't set "ToolsDir" to anything... and I'm not sure it ever _was_ set to anything. @wtgodbe Where did you expect this to be pointing when you made PR https://github.com/dotnet/coreclr/pull/13795  but then removed it in https://github.com/dotnet/coreclr/pull/14662?  Was the removal of the /p:ToolsDir a mistake that should be reverted?

Anyway, this looks like a coreclr problem, so I'm going to move the issue over there so it's near the code that needs to change...

**Comment by wtgodbe** [comment]
@ChadNedzlek I don't remember why I removed that, but I suspect it can be added back in. @karajas can you look at Chad's last comment in the issue description and see if you remember why /p:ToolsDir=xxx was removed from init-tools?

**Comment by ChadNedzlek** [comment]
@wtgodbe @karajas Any further information? This is messing up build machines, because the builds are placing files in random locations on the harddrive.  I can easily revert the change that removed the /p:ToolsDir set, but since I have no idea what the intent of that change was, I'm pretty hesitant to just make random changes in a codebase in which I'm not familiar.

**Comment by ChadNedzlek** [comment]
Is there someone responsible for the Core CLR builds that I could have look into this?

**Comment by wtgodbe** [comment]
My suspicion is that I initally made a change to the line that passes `/p:ToolsDir=xxx`, but then reverted the change after Karthik's comment (https://github.com/dotnet/coreclr/pull/14662/files#r146404288), and accidentally reverted it to the state of that line from an older version of the file. I don't see any reason why we wouldn't want or need `/p:ToolsDir=xxx` there, so I think it would be safe for you to add that back in.

I believe @jashook is in charge of CoreCLR builds now.
