### ISSUE TITLE
FEATURE_EVENT_TRACE and FEATURE_PERFTRACING macros may be combined

### ISSUE THREAD

**Issue by nategraf** [dotnet/coreclr#15493]
Following #14772 and as the [EventPipe design](https://github.com/dotnet/designs/blob/master/accepted/cross-platform-performance-monitoring.md) continues to be implemented the seperation of FEATURE_EVENT_TRACE and FEATURE_PERFTRACING is becoming inaccurate and potentially confusing, We may want to merge the two and create one as the implementation progresses.

**Comment by brianrob** [comment]
There still may be some benefit to keeping these separate - FEATURE_PERFTRACING is a subset of FEATURE_EVENT_TRACE. Closing this for now.
