### ISSUE TITLE
Is it possible for JIT to devirtualize object boxing in simple cases?

### ISSUE THREAD

**Issue by kasper3** [dotnet/coreclr#15515]
I was testing out https://sharplab.io/

This code:

```c#
class C {   
    C(){
        CallDo1();
        CallDo2();
    }
    
    void CallDo1() => Do1(123);
    void CallDo2() => Do2(123);
    void Do1(object foo) {}
    void Do2(int foo) {}
}
```

produces:

```asm
; Desktop CLR v4.7.2114.00 (clr.dll) on x86.

C..ctor()
    L0000: mov ecx, 0x72893c04
    L0005: call 0x1de30c8
    L000a: mov dword [eax+0x4], 0x7b
    L0011: ret

C.CallDo1()
    L0000: mov ecx, 0x72893c04
    L0005: call 0x1de30c8
    L000a: mov dword [eax+0x4], 0x7b
    L0011: ret

C.CallDo2()
    L0000: ret

C.Do1(System.Object)
    L0000: ret

C.Do2(Int32)
    L0000: ret
```

Is it possible to devirtualize this int->object->int boxing?

**Comment by kasper3** [comment]
![image](https://user-images.githubusercontent.com/33230602/33972221-837f50b2-e085-11e7-90bf-4a5acff8c6ff.png)

**Comment by benaadams** [comment]
Might currently do in the current branch (on inlining)? https://github.com/dotnet/coreclr/pull/14698

/cc @AndyAyersMS

**Comment by fiigii** [comment]
@kasper3 This website (sharply) uses JIT32 rather than RyuJIT.

**Comment by kasper3** [comment]
Thanks. Is RuJIT output different than the one demonstrated above (forgoes boxing)?

@ashmind, would it be feasible to incorporate  RuyJIT in https://github.com/ashmind/SharpLab?

**Comment by mikedn** [comment]
It's not clear what you mean by "devirtualize object boxing", there is no virtual call in your code. The current RyuJIT build eliminates all the code:

```asm
G_M33789_IG01:
G_M33789_IG02:
       C3                   ret
; Total bytes of code 1, prolog size 0 for method C:Test():this
```
Presumably that's what you expect.
However, if the `foo` parameter is used then boxing is back, of course:
```C#
void Do1(object foo) { Console.WriteLine(foo);  }
```
generates
```asm
G_M33789_IG01:
       4883EC28             sub      rsp, 40
G_M33789_IG02:
       48B958806267FD7F0000 mov      rcx, 0x7FFD67628058
       E8EDA6845F           call     CORINFO_HELP_NEWSFAST
       488BC8               mov      rcx, rax
       C741087B000000       mov      dword ptr [rcx+8], 123
       E83EFCFFFF           call     System.Console:WriteLine(ref)
       90                   nop
G_M33789_IG03:
       4883C428             add      rsp, 40
       C3                   ret
; Total bytes of code 40, prolog size 4 for method C:Test():this
```

**Comment by ashmind** [comment]
@kasper3 
> @ashmind, would it be feasible to incorporate RuyJIT in https://github.com/ashmind/SharpLab?

Yep and I planned this, but I can't promise any specific timeline.
(which with SharpLab/OSS might mean anything from a few weeks to a few years)
