### ISSUE TITLE
Add "Create" method to EqualityComparer<> class

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/coreclr#15526]
Now we have a `Create` method in [Comparer<> class](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/Comparer.cs#L21):
```cs
public static Comparer<T> Create(Comparison<T> comparison)
```

I think, it will be usable to have an analog in EqualityComparer<>:
```cs
public static EqualityComparer<T> Create(Func<T, T, bool> equals, Func<T, int> getHashCode)
```

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#25928
