### ISSUE TITLE
ASAN false positive

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#15540]
There are a lot of false-positive cases in CoreCLR when it executed with enabled ASAN caused by custom stack unwinding and memory allocation, e.g.:
```
Address 0x961fa700 is located in stack of thread T12 at offset 0 in frame
    #0 0xac012a1f in ExceptionTracker::ResumeExecution(_CONTEXT*, _EXCEPTION_RECORD*) /usr/src/debug/coreclr-2.0.0.12082/src/vm/exceptionhandling.cpp:4017:0

  This frame has 1 object(s):
    [16, 36) '_check' <== Memory access at offset 0 partially underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
Thread T12 created by T11 here: 
```

It is needed to add annotions to handle such cases correct:
https://github.com/google/sanitizers/wiki/AddressSanitizerManualPoisoning
and fake stack API: https://github.com/llvm-mirror/compiler-rt/blob/master/include/sanitizer/asan_interface.h#L135

cc @Dmitri-Botcharnikov @kbaladurin

**Comment by janvorli** [comment]
Fixed by #15563
