### ISSUE TITLE
Bug inside c# dot Net Core Compiler 

### ISSUE THREAD

**Issue by MkazemAkhgary** [dotnet/coreclr#15545]
this code does not compile which makes sense perfectly (because of cycling issue).

    public struct Node<T>
    {
        Node<T> Left { get; }
    }

how ever nullable member doesn't seem to cause cycling. but lets be accurate. this code explodes at runtime. this does not compile in dot net framework which is all good. but it **does** compile in dot net core and causes `type load exception` at runtime. 

    public struct Node<T>
    {
        Node<T>? Left { get; }
    }

---

P.S. if this post does not belong to this repo, please let me know so I post in appropriate repo.

**Comment by MichalStrehovsky** [comment]
> P.S. if this post does not belong to this repo, please let me know so I post in appropriate repo

Thanks for reporting! This is tracked as dotnet/corefx#25251.
