### ISSUE TITLE
Move tests/JIT/HWIntrinsics/* into XArch subdirectory

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#15551]
It would be nice to keep HWIntrinsic tests in platform/namespace specific directories.

I plan to add the `Arm64` tests into `tests/JIT/HWIntrinsics/Arm64`

It would be nice to move the `XARCH` ones into a subdirectory `XArch`, `x86` or something like that.  

@dotnet/jit-contrib For opinions
@fiigii Since this will likely affect your work, can you do this at your convenience?

**Comment by tannergooding** [comment]
I have a PR up (https://github.com/dotnet/coreclr/pull/15538) which moves them under the X86 folder to account for this.

**Comment by tannergooding** [comment]
I can split the particular commit which moves the tests out and into a separate PR if it is currently blocking.

**Comment by fiigii** [comment]
@tannergooding Thanks for the work. However, "X86" is in .gitignore, so that we may have to "force" add each file in the future. Could you change it to other name, such as "Xarch", "Intel", or something?

**Comment by tannergooding** [comment]
The PR also explicitly adds the tests/src/JIT/HardwareIntrinsics/X86 folder to the list of paths to not ignore. I believe we already had to do a similar thing for the src/mscorlib/Sysyem/Runtime/Intrinsics/X86 folder. I know we have already done the same for some other src paths that include X86.

**Comment by tannergooding** [comment]
Note: I am not opposed to using xarch (or something other than x86) as the folder name if people feel strongly.

I just believe making the folder name line up with the name space name makes locating the tests and their organization a bit simpler.

**Comment by fiigii** [comment]
> I just believe making the folder name line up with the name space name makes locating the tests and their organization a bit simpler.

Agree, and I prefer x86 over others actually.

**Comment by jkotas** [comment]
> I can split the particular commit which moves the tests out and into a separate PR if it is currently blocking.

It is not blocking, but it would make your other PR easier to review. Could you please split it into a separate PR?
