### ISSUE TITLE
JIT: GitHub_15291 test failure with MinOpts

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#15566]
Related to #15442 

```
C:\gh\coreclr\bin\tests\Windows_NT.x86.Checked\JIT\Regression\JitBlue\GitHub_15291\GitHub_15291\GitHub_15291.cmd -coreroot C:\gh\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
BEGIN EXECUTION
 "C:\gh\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" GitHub_15291.exe
r64:FFFFFFFF r64a:00000000
r63:FFFFFFFF r63a:FFFFFFFF
r32:FFFFFFFF r32a:FFFFFFFF
r31:7FFFFFFF r31a:7FFFFFFF
rm1:FFFFFFFF rm1a:FFFFFFFF
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
PASS: 0, FAIL: 1, TOTAL: 1
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_minopts/

**Comment by mikedn** [comment]
Looks like this comes from shift decomposition, it should do mask the shift count to 6 bits to match the updated behavior of the shift helper.

https://github.com/dotnet/coreclr/blob/46dc37a27abe79d5977a1942541b1665b61f7a17/src/jit/decomposelongs.cpp#L1090
