### ISSUE TITLE
EventSetInformation in advapi32 called from .Net 4.6 - First chance exception on Windows 7

### ISSUE THREAD

**Issue by BryantL** [dotnet/coreclr#1556]
As indicated in https://github.com/dotnet/coreclr/issues/974 .Net 4.6 calls the EventSetInformation method in advapi32 which is unavailable on windows 7 (I'm creating a new issue as that issue was closed).

I realise that the resulting exception is swallowed and the call not made again however the initial first chance exception is somewhat annoying.  

According to comments in https://github.com/dotnet/coreclr/issues/974 the Windows OS team were planning on patching this "within month" however it is now over 4 months since that comment was made and my machine does not have a patched version nor can I find a KB on the patch (though it may well be possible that my search skills have failed me).

Do the OS team still plan on patching this in and if so is there an approximate timeline?  Alternatively, if it has already been patched, is there a KB for it?

Thanks,
Bryant

**Comment by zwcloud** [comment]
I ran into this issue when debugging unit tests with VS2013(update 4) just now.

**Comment by JamesZhengRuqing** [comment]
May I know if this is fixed? Which .Net framework update I need for windows 7?
