### ISSUE TITLE
Question: test artifacts

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#15569]
@jashook With #15448, Looks like the test artifacts created by Windows Check Build and Test file shrunk by 75%.  Tests shrunk by 80%.  Is that expected?

Building on Unix is taking hours on my Skylake i7 8 core desktop.  Picking up the test artifacts from CI was saving a lot of build time on my systems.

Is there a place where the Priority 0 & Priority 1 tests artifacts are still archived  and publicly accessible.

**Comment by jashook** [comment]
I am guessing that you are now picking up priority 0 tests. Both options should now be available as artifacts. I currently don’t have access to find the links however you are looking for the windows_nt_bld job for priorit 1 and the windows_nt_bld_prtest for priority 0.

Will post the links to artifacts tomorrow when I have access to reliable internet.

**Comment by sdmaclea** [comment]
@jashook For reference I have been pulling the tests from addresses like this 

https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt_bld/20901/artifact/bin/tests/tests.zip

Builds >= 20824 have roughly 90MB in tests 
Build <= 20820 have > 400MB

**Comment by BruceForstall** [comment]
@jashook It looks like your change also caused windows_nt_bld to build pri-0 and not pri-1. E.g.,

https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt_bld/20824/consoleText
```
D:\j\workspace\checked_windo---3c72507e>set __TestIntermediateDir=int  && build.cmd checked x64  -priority=0 
```

and the previous, https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt_bld/20822/consoleText
```
D:\j\workspace\checked_windo---3c72507e>set __TestIntermediateDir=int  && build.cmd checked x64  -priority=1 
```

I presume this means all non-Windows builds that depend on these are doing pri-0 test runs now, not pri-1 as before.

**Comment by BruceForstall** [comment]
Looks like it was due to this change to netci.groovy:
```
-    if (scenario == 'default' && isPR == true) {
 +    if ((scenario == 'default' && isPR == true) || (scenario == 'default' && isBuildOnly == true)) {
          priority = '0'
      }
```

It would be trivial to back this out, with no negative consequences except for build time. But, @jashook , what was the reasoning behind adding it?

**Comment by jashook** [comment]
I verified what Bruce has mentioned, that change needs to be backed out. It erroneously ended up in the pr.

**Comment by sdmaclea** [comment]
@BruceForstall Thanks for the fix.  I assume someone knows the tip is broken https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt_bld/ is failing recent builds.

**Comment by BruceForstall** [comment]
> I assume someone knows the tip is broken 

Well, given how many people are on vacation, I wouldn't assume that :-)

Thanks for the heads-up.
