### ISSUE TITLE
implicit operator Memory<T>(T[] array) should not throw for null array

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/coreclr#15572]
It's very unexpected, from a callers perspective, to call a method like:
```` C#
public static void DoStuff(Memory<byte> memory);
````
with a call like
```` C#
btye [] arr = null;
DoStuff(arr);
````

This call throws an ArgumentNullException in the constructor of Memory.  Our published guidelines for developers, here [implicit (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/implicit), says that implicit operators should not throw.  And it seems reasonable for this operator to return a `Memory<byte>.Empty`, which will lead to the expected callstack (or, if the DoStuff method can actually handle null, then the expected behavior).

**Comment by bartonjs** [comment]
Span is right (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Span.cs#L351-L352)

ReadOnlySpan is right (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/ReadOnlySpan.cs#L263-L266)

Memory is wrong (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Memory.cs#L104-L107), no nullcheck.

ReadOnlyMemory is wrong (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/ReadOnlyMemory.cs#L95-L98), no nullcheck

**Comment by jkotas** [comment]
cc @ahsonkhan
