### ISSUE TITLE
[Perf] Correctly disable Indexer and SpanBench

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#15578]
1ec48880ab3785bbcd4b0bf157afdeee1f34f9fe disabled Indexer and SpanBench perf tests by returning 100, which in the perf infrastructure does nothing. The tests need to be disabled by adding the skip benchmark attribute to failing tests:
`
[Benchmark(Skip = "Issue #")] // The issue number related to this failure.`

**Comment by ahsonkhan** [comment]
The tests were re-enabled in https://github.com/dotnet/coreclr/pull/15546 and hence there shouldn't be any issues with running the perf tests now.

Closing the issue. Please re-open if there are still some issues with running the tests.
