### ISSUE TITLE
GetManifestResourceStream return junkie code when using coreclr beta7

### ISSUE THREAD

**Issue by zhangxin511** [dotnet/coreclr#1558]
I am running 1.0.0-beta7 coreclr to run web application using command "dnx kestrel". I found the GetManifestResourceStream return junkie chars:

var template = _resourceAssembly.GetManifestResourceStream("Swashbuckle.SwaggerUi.index.html");
var templateText = new StreamReader(template).ReadToEnd();

The templateText will have funny chars after certain length.

**Comment by joshfree** [comment]
@ramarag PTAL

**Comment by davidfowl** [comment]
This was a Roslyn bug that has since been fixed

**Comment by gkhanna79** [comment]
Closing per David's comment above.
