### ISSUE TITLE
Bogus SynchronizationLockException thrown in thread intensive workloads

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#15592]
In x64 Windows release testing in the CI:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/release_windows_nt

There are many cases of the TryEnter01, TryEnter03, and TryEnter05 tests failing:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/release_windows_nt/3556/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/release_windows_nt/3553/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/release_windows_nt/3549/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/release_windows_nt/3546/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/release_windows_nt/3538/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/release_windows_nt/3586

**Comment by BruceForstall** [comment]
@kouvel Is this your area?

**Comment by kouvel** [comment]
Yes `tookLock` needs to be reset to false before calling `Monitor.TryEnter()` in the loop, I'll fix

**Comment by kouvel** [comment]
Yes I'll take a look

**Comment by kouvel** [comment]
Closing until another failure occurs, hopefully with more info

**Comment by jkotas** [comment]
We have a pretty reliable repro in real-world workload. I am going to send you details about the repro via email.

**Comment by kouvel** [comment]
Should be fixed by https://github.com/dotnet/coreclr/pull/16089

**Comment by kouvel** [comment]
Reopening for release/2.1 PR https://github.com/dotnet/coreclr/pull/16093

**Comment by kouvel** [comment]
Fixed by #16093
