### ISSUE TITLE
Clean up config.h to be generated at build time

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#156]
#155

**Comment by kangaroo** [comment]
Took a stab at moving all this to CMake. There are some warts on the CMakeLists.txt, but I took an initial goal of getting compatibility with the unpublished configure output.  We can remove defines and clean things up as we clean up the PAL.

There were also some typos and inconsistencies between the configure.in and config.h's that are checked in (guessing the configure.in drifted).  I made what seemed like logical choices there, but maybe the build bots will hate me :)

We may want to consider moving the ftruncate checks out of build time.  They have a nasty habit of using up all your disk space shortly.

PR: https://github.com/dotnet/coreclr/pull/255

*may the linux CI build have mercy on my soul*

**Comment by kangaroo** [comment]
This is fixed too.  Can someone close it out please?

**Comment by jkotas** [comment]
Fixed.
