### ISSUE TITLE
Getting currency sign (¤) when given culture name without region

### ISSUE THREAD

**Issue by lukazh** [dotnet/coreclr#15619]
Version: 1.1
Runtime: Ubuntu.16.04-x64
Reproduce:
````
using System;
using System.Globalization;
namespace myapp
{
    class Program
    {
        static void Main(string[] args)
        {
            var c = new CultureInfo("fr");
            Console.WriteLine(c.NumberFormat.CurrencySymbol);
        }
    }
}
````
On ubuntu when the culture name given for instantiation of CultureInfo is without  region (e.g. "fr" instead of "fr-FR"), the CurrencySymbol will be currency sign (¤), while on windows 10 it acts correctly.

**Comment by tarekgh** [comment]
Net core depends on the underlying OS for the culture and region data. We don't carry the data ourselves. So, you can expect some differences when running on Windows than on Ubuntu. 

If you think Ubuntu behavior is wrong, you can file an issue against ICU library http://site.icu-project.org/bugs.
