### ISSUE TITLE
Need new CI modes for Intel hardware intrinsics

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#15618]
Due to https://github.com/dotnet/coreclr/pull/15514, most of the Intel hardware intrinsics are disabled by default. So we need the new CI modes with Debug and Checked build.
```
['COMPlus_EnableIncompleteISAClass' : '1'],
['COMPlus_EnableIncompleteISAClass' : '1', 'COMPlus_EnableAVX' : '0'], // test non-VEX-encoding 
['COMPlus_EnableIncompleteISAClass' : '1', 'COMPlus_EnableAVX2' : '0'], // test AVX CPUs
['COMPlus_EnableIncompleteISAClass' : '1', 'COMPlus_EnableSSE' : '0' , 'COMPlus_EnableSSE2' : '0' , 'COMPlus_EnableSSE3' : '0' , 'COMPlus_EnableSSSE3' : '0' , 'COMPlus_EnableSSE41' : '0' , 'COMPlus_EnableSSE42' : '0' , 'COMPlus_EnableAVX' : '0' , 'COMPlus_EnableAVX2' : '0' , 'COMPlus_EnableAES' : '0' , 'COMPlus_EnableBMI1' : '0' , 'COMPlus_EnableBMI2' : '0' , 'COMPlus_EnableFMA' : '0' , 'COMPlus_EnableLZCNT' : '0' , 'COMPlus_ EnablePCLMULQDQ' : '0' , 'COMPlus_EnablePOPCNT' : '0'],
['COMPlus_EnableIncompleteISAClass' : '1', 'COMPlus_FeatureSIMD' : '0'],
```

cc @BruceForstall @CarolEidt @jkotas @tannergooding

**Comment by 4creators** [comment]
@fiigii @tannergooding 
This can be done with support of `CLRTestBatchPreCommands` and `BashCLRTestPreCommands` MSBuild properties on a per directory or per test project basis. I have implemented it in my Sse2 tests in the following places:

https://github.com/dotnet/coreclr/pull/15585/files#diff-ed7fd7fe0842d20364c23fad645e6ffd where COMPlus_EnableIncompleteISAClass=1 is set for whole `X86` directory and

https://github.com/dotnet/coreclr/pull/15585/files#diff-2ba0b8c1849292f8fa181ad58c8c164c where COMPlus_EnableAVX=0 is set to tests legacy Sse2 codegen

I will prepare PR to enable it independently of my #15585 PR.
