### ISSUE TITLE
OrdinalCaseSensitiveComparer is ISerializable but missing deserialization .ctor(streamingcontext ...etc...)

### ISSUE THREAD

**Issue by itadapter** [dotnet/coreclr#15626]
https://github.com/dotnet/coreclr/blob/da8b7181dbe362fbfe64c7ef72ff3a4a7db68f24/src/mscorlib/shared/System/StringComparer.cs#L327

Causes binary deserialization (since there is no .ctor) problems need to add the .ctor complementing 
`GetObjectData(SerializationInfo info, StreamingContext context)`

**Comment by itadapter** [comment]
What is missing is something like:
``` cs
protected OrdinalComparer(SerializationInfo info, StreamingContext context) : base(info, context)
{
    IntState = info.GetInt32("IntState");//just as an example 
}
```
the method has to complement and mirror the GetObjectData()...

**Comment by jkotas** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
@itadapter why do you want to deserialize a `OrdinalIgnoreCaseComparer`? The type doesn't exist on .NET Framework and serializes itself to a `OrdinalComparer`. That means you will never see the OICC type in your serialization blob. https://source.dot.net/#System.Private.CoreLib/shared/System/StringComparer.cs,348

**Comment by itadapter** [comment]
Not correct, `Dictionary<string, object>(StringComparer.OrdinalIfnoreCase)`  serialization fails on dot-core but works on net.
Anyhow, the code is wrong as it is ISerializable but does not have a .ctor for deserialization

**Comment by ViktorHofer** [comment]
> Dictionary<string, object>(StringComparer.OrdinalIgnoreCase) serialization fails on dot-core but works on net.

Are you using the latest servicing release (2.0.4) of .NET Core 2? It might help if you provide your `dotnet --info` output here. We had a bug in 2.0 which was fixed in one of the servicing releases which impacted the Dictionary serializability.

> Anyhow, the code is wrong as it is ISerializable but does not have a .ctor for deserialization

That's intentional. The `OrdinalIgnoreCaseComparer` should be serializable and save it's state as a `OrdinalComparer` but not to be deserializable. If we would want that type to be deserializable we would also need typeforwards. Work was done here: https://github.com/dotnet/coreclr/pull/12215

**Comment by itadapter** [comment]
```
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

**Comment by itadapter** [comment]
Shared framework host 2.0.3,  are you saying it needs to be upgraded? If yes, then is it fixed in Mac and *nix images?   Where do I get the patch?

**Comment by ViktorHofer** [comment]
Please update to 2.0.4 and try it again

**Comment by ViktorHofer** [comment]
https://www.microsoft.com/net/download/linux

**Comment by itadapter** [comment]
2.0.4 does not solve the issue (at least on win 64)
And I do see that Dictionary  serializes System.OrdinalIgnoreCaseComparer instance into the stream.
So, without digging into Dictionary, keep in mind that BinaryFormatter is not what many use, so if there is a special treatment in BinaryFormatter (I dont know if there is), it is ogtta be done properly in Dictionary so other serializers may work.

Unfortunately, I have no other way but create a special fake OrdinalComparer and use that instead of the system one

**Comment by ViktorHofer** [comment]
If it doesn't sove your issue then there's probably a bug in the run time. Can you please provide a small repro so that I can test it locally.

**Comment by itadapter** [comment]
I have tried Dictionary<>(OrdIgnoreCase) with BinaryFormatter and it works, however Dictionary.GetObjectData does write OrdinalIgnoreCase comparer to stream.
What I am not getting is - **did you create special treatment for this in BinaryFormatter**?

if yes then it is a wrong approach as the comparers should transparently ser in any formatter that uses ISerializable.  Effectively our case is failing because dictionary writes it to stream, of course we can also add a special "IF CASE" in our serializer but it is just wrong

**Comment by itadapter** [comment]
http://source.dot.net/#System.Private.CoreLib/shared/System/Collections/Generic/Dictionary.cs,347
http://source.dot.net/#System.Private.CoreLib/shared/System/Collections/Generic/Dictionary.cs,474
So how does comparer get handled?

**Comment by jkotas** [comment]
It works because of `OrdinalIgnoreCaseComparer.GetObjectData` calls `SerializationInfo.SetType`: https://source.dot.net/#System.Private.CoreLib/shared/System/StringComparer.cs,348. This call overrides the type that the object is serialized as.

There is no special treatment for this in BinaryFormatter. `SerializationInfo.SetType` existed since forever and it is used in number of situations similar to this one. It sounds like that your custom binary serializer does not handle `SerializationInfo.SetType` correctly.

**Comment by itadapter** [comment]
Yes, it looks like it is the case. What is strange though is that this is the first case when this behavior gets exposed, as none of other framework classes ever used .SetType()  issue closed thank you

**Comment by itadapter** [comment]
I realize that this has been like this for a long time, but `SerializationInfo.SetType()` concept is a bit strange to say the least. The problem deals with types derived of the ones used in SetType(), such as arrays.

For example,  say you serialize an array of  Car:     Car[] is the root, then you get polymorphic Ford, Buick, Honda, Mazda instances... now,    Suppose all Japanese cars override SetType() during serialization into JapaneseCar archetype. What would you get back on deserialization?  An array filled with JapaneseCar instances in place of Honda and Mazda? 
What if JapaneseCar does not derive from Car?  What if you serialize Honda[] as a root object, are you going to get JapaneseCar[] back (its impossible since they are even not assignment compatible)

**Comment by jkotas** [comment]
Binary serialization has number of security, performance and functionality issues. The one you have pointed out is one of them. These issues cannot be really fixed without breaking compatibility.

Binary serialization was included in limited fashion in .NET Core just to make it easier to adopt .NET Core. It is legacy technology that should not be used in new projects, and existing projects should consider migrating away from it.

**Comment by itadapter** [comment]
I was expecting it (the criticism of binary serialization) :)
The stuff that you are referring to is the same mantra that they repeated in Core 1 against ISeriaizable. Consequently after much pressure that we(the community) has put on you guys have added binary serialization back. 
Binary serialization done the right way is **very important for high-perf and cluster applications** as it outperforms json and other text formats 5x if not 10x especially on long runs (less GC, no string parsing etc..). The security is of no concern to us in our cluster. The fragility does not exist until one uses SetType() :)  Another use of binary serialization is 100% transparent CLR object cloning and extra large heaps storing 100s of millions of object instances in-process. There are many uses, just for in-proc programming.
It is very important for business applications, as it allows for automatic tele-port of domain/state objects. And if you tell us to use JSON we may just as easily switch from .NET to Node, as what is the point to use C# on the server anyway if I have to use JSON?(or XML or whatever). 

The problem is that *SetType() used in modern fx is really a deal breaker*, as it introduces a lot of problems. I still don't understand why Dictionary/comparers are implemented in such way, instead you could have used an enum serializing system comparer type in Dictionary class (I think this is the way it is coded in .NET  framework). This would have obviated this whole issue with SetType() .. which is horrible.

**Comment by jkotas** [comment]
> Binary serialization done the right way is very important

Agree with that. However, `System.Runtime.Serialization.Formatters.Binary.BinaryFormatter` is not binary serialization done the right way. Examples of binary serialization done the right way are Bond or ProtoBuf.

> outperforms json and other text formats 5x if not 10x especially

Bond or ProtoBuf do. `System.Runtime.Serialization.Formatters.Binary.BinaryFormatter` rarely outperforms json, and it is often the worst possible choice performance wise. https://www.bing.com/search?q=serialization+performance+comparison

> The problem is that SetType() used in modern fx is really a deal breaker

SetType got used in number of places in .NET Framework over the years. It is used in a few more places in .NET Core, but it is nothing really new.

> enum serializing system comparer type in Dictionary class

The code for serialization of Dictionary class is identical between .NET Core and .NET Framework.

**Comment by itadapter** [comment]
The Dictionary serialization works in .NET 4.7.1 (no SetType() is used) as-is, however Core does use SetType() as I have seen yesterday.

TL.DR
 **It would be nice if SerializationInfo.SetType() was marked as OBSOLETE and not used by any framework code** - it is a cheap fix with great benefit. Unfortunately now I have a choice of either not using Dictionary<> or adding unneeded dangerous semantic to our serialization stack that is really not necessary as everything has worked without it for 10+ years.

My point is this:  full-featured CLR binary serialization as prescribed by ISerializable and IDeserializationCallback along with [OnSer/Deser] attributes works very well for business-domain oriented apps and works very well on List<T>, Dict<T,T> etc... The whole benefit of this approach is the 100% transparency of the objects serialized, no need to use special designs/attributes for those classes. This is very much needed for cluster programming, and in-process large heaps, copy-on write semantic and other cases.

Most serializer tests results are incorrect due to fixed payloads a-la "Person". The aforementioned Protobuf can not be considered a CLR-compatible serializer at all, as it does not handle (by design) polymorphism, entangled graphs, boxing and other cases. Also Protobuf is not really as fast as many think as tests below show.

Regarding BinaryFormatter - it is the only full-CLR-featured serializer (besides Wire And Slim), and it is very slow, that is why we use NFX Slim which yields 5x-10x speed and 2x-3x space over BinaryFormatter. https://github.com/aumcode/nfx/tree/master/Source/NFX/Serialization

Encourage you to look at these results, tested major serializers against DIFFERENT payloads, for example Person vs Person[10] vs Person[100] vs Dictionary<Person> , etc. What tests reveal is that Protobuf for example is not that fast after all, whereas JIL is much faster than Newtonsowft and sometimes on the par with Protobuf.
http://aumcode.github.io/serbench/

The practice shows that careless full CLR binary serialization is fragile and security dangerous, yet as I have mentioned, it does have many uses in-process, for things like BigMemory: https://www.infoq.com/articles/Big-Memory-Part-2

**Comment by jkotas** [comment]
`SerializationInfo.SetType` is not used in .NET 4.7.1 in OrdinalCaseSensitiveComparer. It is used in number of other types. For example, `LongEnumEqualityComparer` uses it in .NET 4.7.1: http://referencesource.microsoft.com/#mscorlib/system/collections/generic/equalitycomparer.cs,495 .

We cannot obsolete and stop using `SerializationInfo.SetType`. It would break compatibility with .NET Framework.

I think we can consider adding the binary serialization constructors for types that are using `SerializationInfo.SetType`, even though it is not  needed by the BinaryFormatter. There are just a few that do not have one yet. Would it be sufficient to make your binary serialization scheme work?

> we use NFX Slim which yields 5x-10x speed and 2x-3x space over BinaryFormatter. 

Nice!

**Comment by itadapter** [comment]
I guess the rule should be observed per original spec from the original MSFT docs from 2005-ish era, which said: any custom-deserializable class has to have a `.ctor(SerInfo, StrmingCtx)`. 

We have removed this requirement in our Slim serializer, because of those BCL types that dont have the .ctors, however this is just inconsistent with  the way it was. At any rate, looks like we'd better refrain from using Dictionary<>  and List<> classes for these reasons (as we don't control how they get serialized)

**Comment by ViktorHofer** [comment]
> I guess the rule should be observed per original spec from the original MSFT docs from 2005-ish era, which said: any custom-deserializable class has to have a .ctor(SerInfo, StrmingCtx).

Again, that statement is still valid, but not applicable here as the `OrdinalCaseSensitiveComparer` is intended to be serializable (via `SerializationInfo.SetType`) but not deserializable.
