### ISSUE TITLE
IPEndPoint cannot return the correct value when compare the same value

### ISSUE THREAD

**Issue by Luoyingliang** [dotnet/coreclr#15633]
There are wrong value return when I do the execute this code:
`ip1==ip2`
both `ip1` and `ip2` are IPEndPoint type,and value both are "192.168.31.15:55360",but it doesn't return true.
now I used the `ToString()` method to instead of that

**Comment by Dmitry-Me** [comment]
Looks like `IPEndPoint` class belongs to CoreFX repo.

**Comment by Luoyingliang** [comment]
I'm so sorry,I forget  check the repo name
