### ISSUE TITLE
Use sys_membarrier to implement FlushProcessWriteBuffers on Linux 4.3+

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#1563]
See #198 for details

**Comment by janvorli** [comment]
It seems that the implementation of the sys_membarrier on Linux 4.3 is too slow.
Starting with kernel 4.14, there is a new flag MEMBARRIER_CMD_PRIVATE_EXPEDITED that enables much faster implementation of the syscall using IPI. See https://lttng.org/blog/2018/01/15/membarrier-system-call-performance-and-userspace-rcu/ for some details.
