### ISSUE TITLE
Add EventSource for blocking syscalls

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#15675]
Currently .NET initiated blocking (`Wait`) can be detected either using `SynchronizationContext` and/or tplETW for Tasks.

However, blocking that happens as a result of sys calls cannot be easily detected (`Thread.Sleep`, sync I/O `File.Read`, blocking `Sockets`)

On Windows you need to listen to the Kernel `CSwitch` ETW events; however this requires elevated privileges; and only a single listener can be listening per system (rather than per process, listening to its own events) - also it makes it more difficult to pull a StackTrace compared to an `EventSource` based approach.

Adding an EventSource for blocking calls would assist in detecting them and also be cross platform.

/cc @stephentoub @vancem

**Comment by benaadams** [comment]
Use case check if `Thread.CurrentThread.IsThreadPoolThread`; if so report the blocking (to detect potential threadpool starvation sources)

Extension to https://github.com/aspnet/Diagnostics/pull/429

**Comment by omariom** [comment]
Blocking calls like File.Read or Socket.Receive can return without blocking. Is there a practical way to know that in advance?

**Comment by vancem** [comment]
/cc @brianrob @nategraf

In general the .NET Runtime does not control all the places where blocking can happen (we call APIs all over the place that may block).    Thus instrumenting them all is impossible (but there MAY be value in instrumenting some ones the .NET Runtime does control, we need to know more about the scenario)

However there is also another approach.  

Brian and Nate have been working on something called EventPipe, which basically is designed for the scenario that @benaadams  mentions (profiling where blocking is important and ETW is not available).   

It works by sampling all threads at intervals (e.g. 1msec), and simply notes the stacks.  This sampling occurs whether the stack is blocked or not.   

Note that we have been looking for APIs on Linux that would allow us to (mostly) unambiguously determine if a thread is blocked at the time the sample is taken, but we have not yet found something.    however we always know the managed call stack for the sample as well as whether we have transitioned to native code.   Thus while we can't distinguish the difference between an native OS operation being CPU bound vs blocked we CAN distinguish between CPU in MANAGED code from any time spent outside managed code (which is very likely to be mostly blocked time in OS operations).     This should be sufficient for most analyses.  

Nate is in the last phases of getting this checked in.   We should see if this capability is enough to resolve this issue.

**Comment by benaadams** [comment]
That would probably do the trick

**Comment by nategraf** [comment]
To clarify: There is a component called the SampleProfiler which takes samples on a roughly 1ms time interval (under heavy cpu load this can be very rough). The changes I checked in this morning bring this to Windows, while it has existed on Linux since coreclr release 2.0

**Comment by brianrob** [comment]
I'm going to close this issue since it sounds like SampleProfiler will enable this.  It is now available on Windows, but still on all platforms, it is only controllable in-proc and via environment variables.  Post 2.1, we are looking to make this much easier with https://github.com/dotnet/designs/pull/26.
