### ISSUE TITLE
liblttng problem with build for android

### ISSUE THREAD

**Issue by meold** [dotnet/coreclr#15687]
Hello!
After i run  cross/build-android-rootfs.sh I have this output. Can you help me please??

`CMake Error at src/pal/src/configure.cmake:1347 (message):
Cannot find liblttng-ust-dev. Try installing liblttng-ust-dev (or the
appropriate packages for your platform)
Call Stack (most recent call first):
src/pal/src/CMakeLists.txt:5 (include)

-- Configuring incomplete, errors occurred!
See also "/git/coreclr/bin/obj/Linux.arm64.Debug/CMakeFiles/CMakeOutput.log".
See also "/git/coreclr/bin/obj/Linux.arm64.Debug/CMakeFiles/CMakeError.log".
~/git/coreclr
Failed to generate CoreCLR component build project!`

**Comment by jkotas** [comment]
Try to build with `cmakeargs -DFEATURE_EVENT_TRACE=0`. It should disable to the tracing subsystem that pulls in lttng.

**Comment by meold** [comment]
@jkotas Ok, thanks
I run this: `CONFIG_DIR=`realpath cross/android/arm64` ROOTFS_DIR=`realpath git/coreclr/cross/android-rootfs/toolchain/arm64/sysroot` ./build.sh cross arm64 skipgenerateversion skipnuget cmakeargs -DFEATURE_EVENT_TRACE=0`

And get this another errors:
`In file included from git/coreclr/src/corefx/System.Globalization.Native/calendarData.cpp:9:
git/coreclr/src/corefx/System.Globalization.Native/icushim.h:142:1: error: 'ucol_setVariableTop' is deprecated [-Werror,-Wdeprecated-declarations]
FOR_ALL_ICU_FUNCTIONS
^
git/coreclr/src/corefx/System.Globalization.Native/icushim.h:137:24: note: expanded from macro 'FOR_ALL_ICU_FUNCTIONS'
    PER_FUNCTION_BLOCK(ucol_setVariableTop, libicui18n)
                       ^
git/coreclr/cross/android-rootfs/toolchain/arm64/sysroot/../sysroot/usr/include/unicode/ucol.h:1271:1: note: 'ucol_setVariableTop' has been explicitly marked deprecated here
ucol_setVariableTop(UCollator *coll, 
^
In file included from git/coreclr/src/corefx/System.Globalization.Native/calendarData.cpp:9:
git/coreclr/src/corefx/System.Globalization.Native/icushim.h:142:1: error: 'ucol_setVariableTop' is deprecated [-Werror,-Wdeprecated-declarations]
FOR_ALL_ICU_FUNCTIONS
^
git/coreclr/src/corefx/System.Globalization.Native/icushim.h:137:24: note: expanded from macro 'FOR_ALL_ICU_FUNCTIONS'
    PER_FUNCTION_BLOCK(ucol_setVariableTop, libicui18n)
                       ^
git/coreclr/cross/android-rootfs/toolchain/arm64/sysroot/../sysroot/usr/include/unicode/ucol.h:1271:1: note: 'ucol_setVariableTop' has been explicitly marked deprecated here
ucol_setVariableTop(UCollator *coll, 
^
1 error generated.
src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native_Static.dir/build.make:62: recipe for target 'src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native_Static.dir/calendarData.cpp.o' failed
make[2]: *** [src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native_Static.dir/calendarData.cpp.o] Error 1
CMakeFiles/Makefile2:142: recipe for target 'src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native_Static.dir/all' failed
make[1]: *** [src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native_Static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
1 error generated.
src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/build.make:62: recipe for target 'src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/calendarData.cpp.o' failed
make[2]: *** [src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/calendarData.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  0%] Building CXX object src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/casing.cpp.o
In file included from git/coreclr/src/corefx/System.Globalization.Native/casing.cpp:8:
git/coreclr/src/corefx/System.Globalization.Native/icushim.h:142:1: error: 'ucol_setVariableTop' is deprecated [-Werror,-Wdeprecated-declarations]
FOR_ALL_ICU_FUNCTIONS
^
git/coreclr/src/corefx/System.Globalization.Native/icushim.h:137:24: note: expanded from macro 'FOR_ALL_ICU_FUNCTIONS'
    PER_FUNCTION_BLOCK(ucol_setVariableTop, libicui18n)
                       ^
git/coreclr/cross/android-rootfs/toolchain/arm64/sysroot/../sysroot/usr/include/unicode/ucol.h:1271:1: note: 'ucol_setVariableTop' has been explicitly marked deprecated here
ucol_setVariableTop(UCollator *coll, 
^
1 error generated.
src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/build.make:86: recipe for target 'src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/casing.cpp.o' failed
make[2]: *** [src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/casing.cpp.o] Error 1
CMakeFiles/Makefile2:105: recipe for target 'src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/all' failed
make[1]: *** [src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Failed to build CoreCLR component`

**Comment by jkotas** [comment]
This was discussed in https://github.com/dotnet/coreclr/issues/5160. There is something wrong with detecting `ucol_setMaxVariable`.

**Comment by meold** [comment]
@jkotas ok, thanks
But now i get another error and I can't find smth information about it.

`Executing make install -j 2
[  0%] Linking CXX shared library System.Globalization.Native.so
[  0%] Built target System.Globalization.Native_Static
clang38++: warning: argument unused during compilation: '-pie'
clang38++: warning: argument unused during compilation: '-pie'
clang38++: warning: argument unused during compilation: '-pie'
clang38++: warning: argument unused during compilation: '-pie'
clang38++: warning: argument unused during compilation: '-pie'
clang38++: warning: argument unused during compilation: '-pie'
clang38++: warning: argument unused during compilation: '-pie'
clang38++: warning: argument unused during compilation: '-pie'
clang38++: warning: argument unused during compilation: '-pie'
clang38++: warning: argument unused during compilation: '-pie'
[  1%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/locale/unicode.cpp.o
[  1%] Built target System.Globalization.Native
[  1%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/locale/utf8.cpp.o
/git/coreclr/src/pal/src/locale/unicode.cpp:41:10: fatal error: 'libintl.h' file not found
#include <libintl.h>
         ^
1 error generated.
src/pal/src/CMakeFiles/coreclrpal.dir/build.make:854: recipe for target 'src/pal/src/CMakeFiles/coreclrpal.dir/locale/unicode.cpp.o' failed
make[2]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/locale/unicode.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  1%] Built target tracepointprovider
[  1%] Built target dlltest2_exports
[  1%] Built target dlltest1_exports
[  1%] Built target unixcoreruncommon
CMakeFiles/Makefile2:240: recipe for target 'src/pal/src/CMakeFiles/coreclrpal.dir/all' failed
make[1]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Built target debug-pal
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Failed to build CoreCLR component`

**Comment by jkotas** [comment]
No idea about this one.

**Comment by jkotas** [comment]
cc @janvorli

**Comment by janvorli** [comment]
@meold this means that the ICU library headers are not present. Are you sure the rootfs was built without any errors? I remember that there was a problem that a version of the library packages needs to be manually updated from time to time when they get bumped in the repository. See the last change that did that here:
https://github.com/dotnet/coreclr/commit/b3e859cb5777bb68dd15caac75ee861da98489ae#diff-64e4222a4045c49394b856c6644cefef

My guess is that some of the `wget` commands have silently failed and you haven't noticed (we should add bash option to the script to make sure that a failed command fails the whole script, which seems to not be there).

**Comment by meold** [comment]
@janvorli @jkotas, I updated my build-android-rootfs.sh like this(last versions from termux.net):
<img width="1349" alt="screen shot 2018-01-07 at 11 42 44 am" src="https://user-images.githubusercontent.com/28731421/34648277-0c03f01e-f3a0-11e7-9845-4f4cb7287184.png">
<img width="846" alt="screen shot 2018-01-07 at 11 42 58 am" src="https://user-images.githubusercontent.com/28731421/34648280-0dc72060-f3a0-11e7-8bc3-661a509cb581.png">

But none of these packages contain `libintl.h`, so I have the next error:
`/git/coreclr/src/pal/src/locale/unicode.cpp:41:10: fatal error: 'libintl.h' file not found
#include <libintl.h>
         ^
1 error generated.
src/pal/src/CMakeFiles/coreclrpal.dir/build.make:854: recipe for target 'src/pal/src/CMakeFiles/coreclrpal.dir/locale/unicode.cpp.o' failed
make[2]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/locale/unicode.cpp.o] Error 1
CMakeFiles/Makefile2:240: recipe for target 'src/pal/src/CMakeFiles/coreclrpal.dir/all' failed
make[1]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/all] Error 2`

Any suggestions would very helpful.
Thanks.

**Comment by meold** [comment]
@janvorli, @jkotas any ideas about this problem?

**Comment by janvorli** [comment]
@meold this header should be part of gettext-dev package. So it looks like the build-android-rootfs.sh should include getting this package.

**Comment by janvorli** [comment]
The URL for ARM64 seems to be http://termux.net/dists/stable/main/binary-aarch64/gettext-dev_0.19.8-2_aarch64.deb

**Comment by meold** [comment]
@janvorli , I added this package, but still get the same error(

**Comment by janvorli** [comment]
@meold hmm, I've checked the location of the header and it is actually part of libc on Linuxes. On Android, it is not present. It is strange though that we were able to build the stuff for android in the past just fine.
@qmfrederik, do you happen to remember if we needed to do anything special w.r.t. the `libintl.h`?

**Comment by qmfrederik** [comment]
@meold @janvorli Well, it's been a while since I looked at .NET Core on Android ;-).

It looks like `libintl.h` was previously part of libandroid-support but it has been removed in termux/libandroid-support@08ad732aa81f0109410c362eb817fbac50c73b06.

@meold Can you try downloading [libintl..h](https://raw.githubusercontent.com/termux/libandroid-support/a35f565f00428c9fbe1a844c377db4fcd187c874/include/libintl.h) and save it to a location where the compiler can find it?

From #15751 it seems you managed to build CoreCLR for Android, how did you handle the libintl.h dependency there?

**Comment by meold** [comment]
@qmfrederik, I I tried to add `libintl.h` file, but still get the same error.

@qmfrederik, I downloaded `libintl.h` file for [#15751](https://github.com/dotnet/coreclr/issues/15751)  from this [this link](https://packages.ubuntu.com/trusty/musl-dev).

@jkotas @qmfrederik @janvorli , so, could you help with the build process for android? Maybe there are some another important steps, that I forgot.

Any suggestions would very helpful.
Thanks.

**Comment by janvorli** [comment]
@meold I was on a paternity leave for the last month so I am sorry for low responsiveness. Now I'm back, so I can try to run the android build locally and find out how to fix the issue.

**Comment by meold** [comment]
@janvorli, thank you very much. Waiting for your reply.

**Comment by meold** [comment]
@janvorli, thank you for the for [this pull request](https://github.com/dotnet/coreclr/pull/15868). CoreCLR builds fine now.
But I have another problem - with CoreFX (described [here](https://github.com/dotnet/corefx/issues/26362))

Any suggestions would very helpful.
Thanks.

**Comment by brianrob** [comment]
Looks like the coreclr build succeeded, so closing this.
