### ISSUE TITLE
DirectoryInfo.Exists implement may have bug

### ISSUE THREAD

**Issue by luchunminglu** [dotnet/coreclr#15695]
Test on  win7 
.net core 2.0 and .net 4.5

```

 DirectoryInfo dir = new DirectoryInfo("tests");
            // expect false and result is false
            Console.WriteLine("dir exists = "+dir.Exists);
            if (!dir.Exists)
            {
                dir.Create();
            }
            // expect true but result is false
            Console.WriteLine("dir exists = " + dir.Exists);

            if (dir.Exists)
            {
//dir not delete
                dir.Delete();
            }
            // expect false and result is false
            Console.WriteLine("dir exists = " + dir.Exists);

```

**Comment by mikedn** [comment]
Most of the information `DirectoryInfo` provides is obtained from the filesystem when the object is created. You need to call `Refresh` to update the information if the filesystem has changed. See https://docs.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo.refresh?view=netframework-4.7.1#System_IO_FileSystemInfo_Refresh

I suppose it could be argued that methods like `Create` and `Delete` should call `Refresh` automatically.

**Comment by luchunminglu** [comment]
thanks
