### ISSUE TITLE
Make Vector64<T>, Vector128<T>, and Vector256<T> work with the debugger.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#15694]
### Rationale
Currently `Vector64<T>`, `Vector128<T>` and `Vector256<T>` in the `System.Runtime.Intrinsics` namespace are opaque types.

This is great for the hardware intrinsics API, but it provides a very poor experience in the debugger.

As such, I propose that the types be extended with the `DebuggerTypeProxy` and `DebuggerDisplay` attributes to provide a better debugging experience.

### Additional Thoughts
I propose the `DebuggerDisplay` attribute should display a string of T elements.

Ex: For `Vector128<float>`, it would display `"{e0, e1, e2, e3}"`, for `Vector128<ushort>` it would display `"{e0, e1, e2, e3, e4, e5, e6, e7}"` (where `e#` is the value of that given element).

I propose `DebuggerTypeProxy` should have several properties in the form of `public <type>[] <type>View` and there should be a property for each supported value of `T` (i.e. `float`, `double`, `byte`, `short`, `int`, `long`, `sbyte`, `ushort`, `uint`, and `ulong`).

Ex: `Vector128DebugView` would have `public byte[] ByteView {get;}`, `public float[] SingleView {get;}`, etc...

### Notes
In doing a prototype for this proposal, I found that the debugger would always see `0` as the value of the underlying struct. I initially attempted to add serialization support, but that did not resolve the issue. 

However, adding private fields to the structs allowed it to work (I'm guessing the debugger is marshalling the type, or something similar).

Ex: I had to change `Vector128<T>` to the following in order for `DebuggerTypeProxy` and `DebuggerDisplay` to work:
```C#
[Intrinsic]
[StructLayout(LayoutKind.Sequential, Size = 16)]
[DebuggerTypeProxy(typeof(Vector128DebugView<>))]
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public struct Vector128<T> where T : struct
{
    // These fields exist purely so debug view works
    private ulong _lower;
    private ulong _upper;
}
```

**Comment by tannergooding** [comment]
FYI. @fiigii, @CarolEidt, @eerhardt, @RussKeldorph

**Comment by fiigii** [comment]
Why do we need the fields `_lower` and `_upper`? Shall we expose a `ToString` method for debugging (not only work with the debugger)?

**Comment by tannergooding** [comment]
> Why do we need the fields _lower and _upper?

As mentioned, I was prototyping this and couldn't get it to work without explicitly adding private fields that equaled 16-bytes. I did try to make the type serializable first, so I am guessing the debugging is doing marshalling or something else instead. There might be some other way of getting it to work (custom marshaller maybe), but I wouldn't know off the top of my head.

> Shall we expose a ToString method for debugging (not only work with the debugger)?

You mean for `Console.WriteLine` and the like? That would work as well, but I think would need to be an explicit design decision to implement that support for the type, since it has farther reaching effects.

**Comment by tannergooding** [comment]
Also CC. @sdmaclea, since it would impact these types for ARM/ARM64

**Comment by 0xd4d** [comment]
If there are 10 properties, one property for each supported primitive type, then that means the user would have to expand the variable, then figure out which one of the 10 arrays is correct, and expand it. The debugger could of course be updated to only show the correct property but that will require updates to all debuggers.

If showing the other arrays isn't important, then it only needs one public property that returns a `System.Array`.

**Comment by tannergooding** [comment]
> If there are 10 properties, one property for each supported primitive type, then that means the user would have to expand the variable, then figure out which one of the 10 arrays is correct, and expand it. 

@0xd4d, The debugger will already display which type the field is: 
![image](https://user-images.githubusercontent.com/10487869/34511110-2a7c9f5e-f00e-11e7-8ff9-0d2088df8278.png)

The other properties provide a way to view the data in the other valid formats (which is sometimes important or useful): 
![image](https://user-images.githubusercontent.com/10487869/34511130-59095ef2-f00e-11e7-9f70-bc404e31bb68.png)

Both of these are very similar to the way `__m128` works in the native compiler:
![image](https://user-images.githubusercontent.com/10487869/34511213-b24e3406-f00e-11e7-8c95-ce082377f3f5.png)

![image](https://user-images.githubusercontent.com/10487869/34511222-c279cdf4-f00e-11e7-94af-80e52b929817.png)

**Comment by 4creators** [comment]
IMO it is best to avoid blowing up the types and at maximum have `System.Array` property (not desirable) or have a conversion  operator in `Vector128DebugView` which would convert VectorNNN to `struct<T>/class<T>` which would be easy to visualize. This would keep separation of concerns at the right distance.

**Comment by eerhardt** [comment]
cc @mikem8361 - in case he has any insight into why `_lower` and `_upper` are necessary.

**Comment by jkotas** [comment]
Would one dummy field of type `T` work?

**Comment by tannergooding** [comment]
> Would one dummy field of type T work? 

No, then only sizeof(T) bits were accessible in the debugher

**Comment by tannergooding** [comment]
> have a conversion operator in Vector128DebugView

The Debug View types are generally internal. Additionally, they debugger does  other expose the proxy types directly, so there is no way to make use of operators on a proxy type.

The primary goal should be to make Vector128 and Vector256 work with the debugger, without causing the types to lose their opaquness. Taking advantage of the debugger attributes to create proxy types (displayed on hover) and display strings (displayed in the locals/watch/ee) should work well for this.

The one, side effect currently is that adding the private fields makes (directly in the types, so Marshall in works) them viewable in the locals/watch window under view raw structures mode.

**Comment by jkotas** [comment]
> "view raw structures" mode

Ok, make sense. Would it be better to have the dummy fields as byte to better match what the type is?

**Comment by jkotas** [comment]
Linking related bug: https://github.com/dotnet/coreclr/issues/10148

**Comment by tannergooding** [comment]
> Ok, make sense. Would it be better to have the dummy fields as byte to better match what the type is?

It might. I had done `ulong` for `Vector128` and two `Vector128` for `Vector256` since that required adding less fields and "view raw structures" is generally a more advanced scenario.

I assume they would be something like `private byte _0, _1, _2, ...;` rather than `_upper`, `_lower`.

> Linking related bug: #10148

I'm guessing there is either a marshalling or debugger bug when working with explicitly sized types. I know on the debugger side of things there are other scenarios that don't work well either (such as fixed sized buffers).

**Comment by tannergooding** [comment]
Looks like its probably in the debugger. Marshalling, serialization, and remoting (in other scenarios) seems to be working as expected

**Comment by tannergooding** [comment]
Commented here: https://github.com/dotnet/coreclr/issues/10148#issuecomment-355478631 about my findings.

It appears to impact any bytes for a struct that are not directly accessible by a declared field (this includes padding bytes and additional bytes from explicating sizing a struct).

**Comment by sdmaclea** [comment]
@tannergooding FYI Vector64<T> has merged too

**Comment by tannergooding** [comment]
Updated the OP to include `Vector64<T>`.

@jkotas, @eerhardt. Is there an alias we can ping to get a response on the debugger issue for Explicitly Sized types?

It would be great to implement this without needing to explicitly declare private fields, if possible.

**Comment by jkotas** [comment]
> Is there an alias we can ping to get a response on the debugger issue

cc @noahfalk @gregg-miskelly

**Comment by mikem8361** [comment]
Does this only happen on a Linux or OS X target and not Windows? Is this VS or VSCode? Only on AVX compatible machines? There were problems with func eval (Property evaluation) on Linux/OS X for 16 byte enregistered arguments.

**Comment by tannergooding** [comment]
@mikem8361, This exists on Linux, OSX, and Windows. Just like https://github.com/dotnet/coreclr/issues/10148#issuecomment-355478631

Basically, any byte which is not explicitly covered by a field does not appear to work in the debugger.

Ex:
```
struct Data
{
    byte _0;
    // implicit padding byte
    // implicit padding byte
    // implicit padding byte
    int  _4;
}
```

The three implicit padding bytes are always 0 in the debugger.

or Ex:
```
[StructLayout(LayoutKind.Sequential, Size = 16)]
struct Vector128<T> where T : struct { }
```

All of the 16-bytes in `Vector128<T>` are implicit (no field exists that maps directly to those bytes), so all 16-bytes are always 0.

Or Ex:
struct Vector<T>
{
    private Register register;
}

[StructLayout(LayoutKind.Explicit)]
struct Register
{
    [FieldOffset(0)]
    internal Double double_0;
    [FieldOffset(8)]
    internal Double double_1;

     // Other overlapping fields
}
```

On an AVX machine, `Vector<T>` is explicitly sized to 32, so the latter 16 bytes (which are not directly mapped to a field) are not accessible.

```

**Comment by tannergooding** [comment]
The same issue also impacts fixed sized buffers:

Ex:
```
internal unsafe struct MyBuffer
{
    public fixed char fixedBuffer[128];
}
```

**Comment by tannergooding** [comment]
FYI. @It72, @chsienki. I have created https://github.com/dotnet/coreclr/issues/16280 to track the debugger issue.

This issue was originally just tracking adding the relevant `DebuggerTypeProxy` and `DebuggerDisplay` attributes to the `Vector64<T>`, `Vector128<T>`, and `Vector256<T>` types.
