### ISSUE TITLE
Arm/Arm64 cross builds failing

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#1570]
As of:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_arm64_linux_debug/29/

Changes in that build:

Changes 1.Add link to .NET Core Roadmap (commit: 2c655822e3e26f9f3edea50ac8f4d4c91873a5bf) (detail)
2.Use Frame list context when GetThreadContext is unavailable (commit: eb3260e67bc653b56a80fbf0e8a07d78e3a404c1) (detail)
3.Use out-of-proc libunwind to unwind native stack from DAC (commit: d0f71d0b22e9012263e4a078d24738c75e384a90) (detail)

Error:

In file included from /mnt/j/workspace/dotnet_coreclr_arm64_linux_debug/src/pal/src/exception/seh.cpp:282:
/mnt/j/workspace/dotnet_coreclr_arm64_linux_debug/src/pal/src/exception/seh-unwind.cpp:494:5: error: use of undeclared identifier 'WinContextToUnwindContext'; did you mean 'WinContextToUnwindCursor'?
    WinContextToUnwindContext(context, &unwContext);
    ^~~~~~~~~~~~~~~~~~~~~~~~~
    WinContextToUnwindCursor
/mnt/j/workspace/dotnet_coreclr_arm64_linux_debug/src/pal/src/exception/seh-unwind.cpp:88:13: note: 'WinContextToUnwindCursor' declared here
static void WinContextToUnwindCursor(CONTEXT *winContext, unw_cursor_t *cursor)
            ^
/mnt/j/workspace/dotnet_coreclr_arm64_linux_debug/src/pal/src/exception/seh-unwind.cpp:494:40: error: cannot initialize a parameter of type 'unw_cursor_t *' (aka 'unw_cursor *') with an rvalue of type 'unw_context_t *' (aka 'unw_tdep_context *')
    WinContextToUnwindContext(context, &unwContext);
                                       ^~~~~~~~~~~
/mnt/j/workspace/dotnet_coreclr_arm64_linux_debug/src/pal/src/exception/seh-unwind.cpp:88:73: note: passing argument to parameter 'cursor' here
static void WinContextToUnwindCursor(CONTEXT *winContext, unw_cursor_t *cursor)

**Comment by benpye** [comment]
@mmitche Working on fixing the build break, however I believe arm64 shouldn't be broken. It appears the arm64 build is actually also building the arm files:

```
Using rootfs in /opt/arm-liux-genueabihf-root
+ ROOTFS_DIR=/opt/arm-liux-genueabihf-root ./build.sh skipmscorlib arm cross verbose debug
```

**Comment by mmitche** [comment]
@benpye Agh...how did that happen.  Changed.

**Comment by benpye** [comment]
After I believe I have fixed the first error I am hitting the assert at https://github.com/dotnet/coreclr/blob/master/src/debug/inc/dbgipcevents.h#L2355 . I guess this is a cause of the conversion from `MAX_PATH` somewhere along the line, I have modified it to the smallest value that will pass the assertion and therefor I assume is large enough.

**Comment by mmitche** [comment]
Different error on arm64:

In file included from /mnt/j/workspace/dotnet_coreclr_arm64_linux_debug/src/pal/src/exception/seh.cpp:282:
/mnt/j/workspace/dotnet_coreclr_arm64_linux_debug/src/pal/src/exception/seh-unwind.cpp:398:14: error: duplicate case value: 'UNW_REG_IP' and 'UNW_AARCH64_X30' both equal '30'
        case UNW_AARCH64_X30:  *valp = (unw_word_t) winContext->Lr; break;
             ^
/mnt/j/workspace/dotnet_coreclr_arm64_linux_debug/src/pal/src/exception/seh-unwind.cpp:395:14: note: previous case defined here
        case UNW_REG_IP:       *valp = (unw_word_t) winContext->Pc; break;
             ^
1 error generated.

**Comment by benpye** [comment]
I've disabled that code for non AMD64 platforms for now since it seems like it's only called from the AMD64 VM. Something I would like @kangaroo to look at though, libunwind lies on both ARM and ARM64 about the registers it's using, in this case, it uses LR for both IP and LR as per https://github.com/fdoray/libunwind/blob/master/include/libunwind-aarch64.h hence it has two of the same case. I already use the exact registers on ARM to avoid this, maybe this should be done for ARM64 too?
