### ISSUE TITLE
Fix scripting that auto-generates the knobs file description

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#15700]
When we split off the jit-specific knobs the scripting that auto-generates the knobs file [Documentation/project-docs/clr-configuration-knobs.md](../blob/master/Documentation/project-docs/clr-configuration-knobs.md) was not updated. So many newer jit knobs are not described.

I believe some knobs appear in both files so simply parsing both will lead to some duplication.

Would be nice to get this fixed.

**Comment by fiigii** [comment]
I tried this in https://github.com/dotnet/coreclr/pull/9710, but looks like the macros of jit-specific knobs do not support generating docs and adding new macros was not allowed.
