### ISSUE TITLE
Debugger exited with COR_E_EXECUTIONENGINE(0x80131506) on netcoreapp2.0 with special code

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#15709]
_From @yyjdelete on December 19, 2017 6:41_

## Environment data
`dotnet --info` output:
```
.NET 命令行工具 (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17046
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
```
VS Code version:`1.18.1_x64/1.20.0-insider_x64`
C# Extension version:`1.13.1`

## Steps to reproduce
1. Add the attached file, and target `netcoreapp2.0`
2. Change configuration from Debug to Release
3. Disable JustMyCode
4. Set an breakpoint at base.Test()
5. Start Debug
6. Add watch to this.Data or this.ToString() or just expand this
7. See debuger exit with COR_E_EXECUTIONENGINE(0x80131506) on netcoreapp2.0

<details>
<summary>Program.cs</summary>

```cs
using System;
class Program
{
    public abstract class T1
    {
        public byte data = 1;
        public virtual byte Data => data;
        public virtual void Test()
        {
            Console.WriteLine("T1");
            //Not happen after uncomment this
            //Console.WriteLine(Environment.StackTrace);
        }
    }
    public class T2 : T1
    {
        public override void Test()
        {
            //new csproj format, and TargetFramework: net461 or netcoreapp2.0
            //1. Set an breakpoint here, disable `Just My Code`, and debug with Release build(Debug works well)
            //2.1 Expand `this` or wath `this.Data`, `this.ToString()` or some others
            //2.2 Or type `this.Data`/`this.GetType().Name` in immediately window(System.ExecutionEngineException, exit after continue, but if you don't contine and type again, you can get the result).
            base.Test();
            //Not happen after uncomment this
            //Console.WriteLine("T2");
        }
    }
    private static T1 t1 = new T2();
    private static void Main(string[] args)
    {
        try {
            t1.Test();
        }catch(Exception e){
            Console.Error.WriteLine(e);
        }
        Console.ReadLine();
    }
}
```
</details>

---

NOTE: 
1. When set another breakpoint at t1.Test(), and watch t1.Data first and continue to next breakpoint, it works well.
2. This also happen in VS2017.6p1 and net471/netcoreapp2.0.
3. This don't happen with netcoreapp1.1 with all debugger.
4. This not happen on `JetBrains Rider` nor `dnSpy`, maybe only an issue with VS's debugger?
5. Not tested on linux.

## Expected  behavior
Not crash.

## Actual behavior
The target process corrupts itself and exits.

----
Already post an issue at https://developercommunity.visualstudio.com/content/problem/166880/debugger-crash-with-systemexecutionengineexception.html , but found the same thing also happen with vscode, so also report it here. 
  

_Copied from original issue: OmniSharp/omnisharp-vscode#1927_

**Comment by gregg-miskelly** [comment]
Hi @yyjdelete I can't really speculate on why you wouldn't see this with JetBrains products, but this looks to be an issue in the CLR. I can port the bug over to their repo.

**Comment by gregg-miskelly** [comment]
I was able to reproduce the problem. VS seems to be kicking off the func eval correctly, but then the target process hits into an AV that gets escalated into a fatal error.

**Comment by tommcdon** [comment]
Sorry for the long delay in getting to this issue.  I was unable to repro on .NET Core 2.2.6 (x64) or .Net Core 3 preview 8 (x64).  Please let us know if this is still and issue and we will take another look.
