### ISSUE TITLE
ARM legs are failing in CI in release/2.0.0

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#15719]
It looks like these have never passed? 

```
15:54:41 BUILDTEST: Commencing build of native test components for arm/Release
15:54:41 BUILDTEST: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\\..\..\VC\Auxiliary\Build\vcvarsall.bat" x86_arm
15:54:41 **********************************************************************
15:54:41 ** Visual Studio 2017 Developer Command Prompt v15.0.26730.16
15:54:41 ** Copyright (c) 2017 Microsoft Corporation
15:54:41 **********************************************************************
15:54:42 The input line is too long.
15:54:42 :export_x86
15:54:42  was unexpected at this time.
15:54:42 
```

https://github.com/dotnet/coreclr/pull/15686

I don't see a line like `:export_x86` in the vcvars related batch files.

@RussKeldorph who sponsors the ARM legs?

**Comment by RussKeldorph** [comment]
It's currently tracked by #15067, but it's better to track with an issue, so thanks.

@weshaggard asked us to look at it, but it's not clear how urgently.

**Comment by jashook** [comment]
It looks to me like after https://github.com/dotnet/coreclr/pull/14892 our builds in release/2.0.0 are using vs 2017 if both vs 2015 and vs 2017 are installed on the machine. #16332 will force vs 2015 for the arm builds. I think it is worth understanding why we are now building with vs 2017 in the branch now.
