### ISSUE TITLE
CentOS builds failing

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#1571]
CentOS builds failing as of build 78:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_linux_centos71_debug/78/

/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libunwind-ptrace.a(_UPT_create.o): relocation R_X86_64_PC32 against undefined symbol `malloc@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_linux_centos71_debug/80/consoleFull#-120596925674b77ed1-74ea-41e6-b970-9241fe4855f3

**Comment by pgavlin** [comment]
I'm seeing the same thing on FC22. I think it's possible that either RedHat has a broken build of libunwind or that we should be linking against the shared libraries.

**Comment by kangaroo** [comment]
We should be linking against the shared libraries.

**Comment by Djuffin** [comment]
It looks like .so version of libunwind-ptrace is missing from libunwind RPM packages
https://apps.fedoraproject.org/packages/libunwind//contents 
https://apps.fedoraproject.org/packages/libunwind-devel/contents

**Comment by kangaroo** [comment]
@Djuffin I see libunwind.so in the -devel package?

**Comment by pgavlin** [comment]
@kangaroo AFAICT from readelf libunwind.so does not contain any of the libunwind-ptrace APIs.

**Comment by Djuffin** [comment]
I reported a bug for the libunwind package 
https://bugzilla.redhat.com/show_bug.cgi?id=1265874

**Comment by pgavlin** [comment]
Should this be closed, or should we leave it open for tracking? It doesn't look like the underlying bug is fixed yet and I assume that we want the functionality provided by the library...

**Comment by Djuffin** [comment]
This issue was tracking build break now the lack of functionality. I created a new one #1659.

**Comment by pgavlin** [comment]
Excellent--thanks!

**Comment by pgavlin** [comment]
FWIW, I've verified that this does fix the build issues I was seeing on FC22.

**Comment by steveharter** [comment]
Unrelated to the libunwind linker issue, there is a compile issue now which was introduced in  Build #93 (Sep 23) when the ICU native calendar libraries were added (System.Globalization.Native/calendarData.cpp). Currently working on a fix for that.

**Comment by steveharter** [comment]
Added #1660 for the ICU compile issue

**Comment by pgavlin** [comment]
FWIW, I'm not seeing #1660 on FC22.

**Comment by steveharter** [comment]
Once the ICU issue is addressed there appears to be another compile issue (no issue created yet):
/home/steveharter/git/coreclr/src/ToolBox/SOS/lldbplugin/debugclient.cpp:495:14: error:
      no member named 'SetFilename' in 'lldb::SBFileSpec'
    fileSpec.SetFilename(name);
    ~~~~~~~~ ^
/home/steveharter/git/coreclr/src/ToolBox/SOS/lldbplugin/debugclient.cpp:697:14: error:
      no member named 'SetFilename' in 'lldb::SBFileSpec'
    fileSpec.SetFilename(name);

**Comment by steveharter** [comment]
With the ICU fix the build is now passing. Closing issue
