### ISSUE TITLE
[JIT] Unnecessary movzx instruction when writing a value to a Span of byte

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/coreclr#15731]
When writing to a `Span<byte>`, the JIT will emit an unnecessary `movzx` instruction if it has also emitted a bounds check for the memory access. Writing code which causes the JIT to elide the bounds check will also remove the extra `movzx` instruction.

The samples below show amd64 codegen.

**Sample code with JIT-included automatic bounds check:**

```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
public static void Foo(uint value, Span<byte> buffer)
{
    int index = 0;
    value -= 10;
    buffer[index] = (byte)value;
}
```
```asm
00007FF9BCAA2A10  sub         rsp,28h  
00007FF9BCAA2A14  add         ecx,0FFFFFFF6h  
00007FF9BCAA2A17  cmp         dword ptr [rdx+8],0  
00007FF9BCAA2A1B  jbe         00007FF9BCAA2A2A  
00007FF9BCAA2A1D  mov         rax,qword ptr [rdx]  
00007FF9BCAA2A20  movzx       edx,cl  
00007FF9BCAA2A23  mov         byte ptr [rax],dl  
00007FF9BCAA2A25  add         rsp,28h  
00007FF9BCAA2A29  ret  
00007FF9BCAA2A2A  call        00007FFA1C731C50  
00007FF9BCAA2A2F  int         3  
```

Note in particular that instead of writing the contents of the _cl_ register directly, the value is bounced through the _edx / dl_ register before being written.

**Sample code with manual branch which elides JIT's auto bounds check:**

```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
public static void Bar(uint value, Span<byte> buffer)
{
    int index = 0;
    value -= 10;
    if ((uint)index >= (uint)buffer.Length) { goto OutOfRange; }
    buffer[index] = (byte)value;
    return;

    OutOfRange:
    ref byte unused = ref buffer[index]; // will trigger exception
}
```
```asm
00007FF9BCA92A50  sub         rsp,28h  
00007FF9BCA92A54  mov         rax,qword ptr [rdx]  
00007FF9BCA92A57  mov         edx,dword ptr [rdx+8]  
00007FF9BCA92A5A  add         ecx,0FFFFFFF6h  
00007FF9BCA92A5D  test        edx,edx  
00007FF9BCA92A5F  jbe         00007FF9BCA92A68  
00007FF9BCA92A61  mov         byte ptr [rax],cl  
00007FF9BCA92A63  add         rsp,28h  
00007FF9BCA92A67  ret  
00007FF9BCA92A68  cmp         edx,0  
00007FF9BCA92A6B  jbe         00007FF9BCA92A72  
00007FF9BCA92A6D  add         rsp,28h  
00007FF9BCA92A71  ret  
00007FF9BCA92A72  call        00007FFA1C731C50  
00007FF9BCA92A77  int         3
```

Note the direct write from the _cl_ register to the address in _rax_. (The reason I wrote the _OutOfRange_ label like I did is that it causes the JIT to emit `call 00007FFA1C731C50` in the failure case. Otherwise I'd have to manually throw and it causes the codegen to look wonky.)

**Comment by mikedn** [comment]
That's a new thing. There's code in morph that's supposed to remove these useless casts but it can't because the lhs of the `GT_ASG` is a `GT_COMMA`! Also affects arrays. Seems easy to fix, just skip the comma.
