### ISSUE TITLE
Why Cors AddPolicy doesn't allow *.example.com ?

### ISSUE THREAD

**Issue by AhmedRagheb** [dotnet/coreclr#15753]
Hello,

Is there a reason (security may be) that prevent Cors AddPolicy from adding all subdomains of my domain in Origins list. As I think it doesn't make sense to add all my subdomains to the Origins list.

Thanks.

**Comment by jkotas** [comment]
This belongs to https://github.com/aspnet/CORS repo

**Comment by jkotas** [comment]
This issue was moved to aspnet/CORS#140

**Comment by jkotas** [comment]
This issue was moved to aspnet/Home#2745
