### ISSUE TITLE
CROSS_check_prtest failing

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#15778]
The CROSS_check_prtest job is failing on multiple PRs.

Looks to be an authentication request failure, possibly due to an expired signature.

**Comment by jkotas** [comment]
cc @dotnet/dnceng

**Comment by MattGal** [comment]
Looks like a simple case of an expired SAS token on a blob used for PR testing, @mmitche is updating that right now.

**Comment by MattGal** [comment]
This looks fixed, successful run post update: 

https://ci.dot.net/job/dotnet_coreclr/job/master/job/CROSS_check_prtest/9576/ 

The new URL should not expire for quite a long time.

**Comment by tannergooding** [comment]
Thanks!
