### ISSUE TITLE
Cap ArrayPool ThreadStatics

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#15797]
ArrayPool should limit the number of ThreadStatic caches it creates for people that have gone wild and either set the threadpool min threads really high or spew lots of long running Tasks Microsoft/msbuild#2384

Perhaps they should be held in a finalizable object so when the Thread expires it will continue allocating more. e.g. static max counter incremented on alloc, and decremented on finalize?

**Comment by jkotas** [comment]
I agree that there needs to be some sort of coordination between GC and Array pool. I have opened https://github.com/dotnet/coreclr/issues/7747 on this a long time ago.

E.g. say that the array pool is keeping 100MB. Whether it is too much or just right depends on the overall state of the heap, that only the GC really understands.

**Comment by Maoni0** [comment]
let's use [7747](https://github.com/dotnet/coreclr/issues/7747) to track ArrayPool perf improvements. closing this one.
