### ISSUE TITLE
Lower ArrayPool defaults for 32bit

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#15796]
At its most extreme; on 64+ core machine the ArrayPool can grow to
`byte` pool 871 MB 
`char` pool at 1741 MB
For total of 2613 MB; plus 2MB+4MB per thread - should the defaults be lower for 32 bit processeses?

**Comment by Maoni0** [comment]
#17177

**Comment by Maoni0** [comment]
#17177 is merged now...so I will close this.

**Comment by benaadams** [comment]
@Maoni0 not sure it completely resolves this? 

e.g. If you ran on in 32 bit mode on a 64 core machine the amount memory the array pool is willing to store is higher than that available to the process? (Though it may be practically solved with #17177 and https://github.com/dotnet/coreclr/pull/17078?)

(use case: unrefined way of keeping densely packed microservices or websites memory under control as they need to share the machine memory rather than consider it all their own https://github.com/dotnet/coreclr/issues/11338)

**Comment by Maoni0** [comment]
sorry, I should have clarified - #17078 is implied - you have to trim. #17177 just makes that trimming also work for 32-bit apps that runs on machines with more physical memory than what a 32-bit process can address.
