### ISSUE TITLE
XmlWriter.WriteStartElement

### ISSUE THREAD

**Issue by Looooooka** [dotnet/coreclr#15826]
Using 
writer.WriteStartElement("prefix:elementname");
used to work. one didn't have to use the overload 

writer.WriteStartElement("localname", "ns");
now it throws an exception.
A bunch of plugins and libraries that could be ported simply by including the cs file are not incompatible because of this minor change.
In my case xml plugins for log4net formatter
I think simply using the same behavior as before could fix a lot of unnecessary rewrites. 
No need to be that strict with overloads

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#26271
