### ISSUE TITLE
Build error : Microsoft.Win32.RegistryKey is internal 

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/coreclr#15825]
I am porting a netframework project to coreclr ns2.0.
This project uses Microsoft.Win32.RegistryKey class, which is public in netframework.
RegistryKey is however [internal ](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/Microsoft/Win32/RegistryKey.cs#L69)in coreclr. Hence, I am getting build errors.

How can I use RegistryKey class in coreclr ?

Extra information :

```
> dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  N/A

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   E:\nmir\SF.DotNet-CLI.1.0.6\b\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9


```

**Comment by jkotas** [comment]
> RegistryKey is however internal in coreclr

This is subset of registry implementation for internal coreclr use.

The full public registry implementation is in Microsoft.Win32.Registry package. Run `dotnet add package Microsoft.Win32.Registry` to add this package to your project. The source code for this package lives at https://github.com/dotnet/corefx/tree/master/src/Microsoft.Win32.Registry

**Comment by jkotas** [comment]
> .NET Command Line Tools (2.0.0-preview2-006497)

You may want to upgrade the preview to the 2.0 release: https://www.microsoft.com/net/download/

**Comment by ashishnegi** [comment]
One general question regarding this : 

Will the implementation of RegistryKey work on Linux as well ?

**Comment by jkotas** [comment]
The current Linux implementation of RegistryKey throws PlatformNotSupportedExceptions. https://github.com/dotnet/corefx/issues/14896 is about making this better.
