### ISSUE TITLE
How to use your build of core clr for x86 Windows

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/coreclr#15830]
Hello!

I am working on [EventPipe for x86](https://github.com/Microsoft/perfview/issues/470)

I have followed all instructions placed [here](https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md) and the build of core clr x86 worked on the first try.

Then I followed [this](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md) and failed to run HelloWorld against it.

1. I am using latest dotnet cli, added to PATH

```
.NET Command Line Tools (2.2.0-preview1-007927)

Product Information:
 Version:            2.2.0-preview1-007927
 Commit SHA-1 hash:  a212d5a017

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\dotnet-sdk-latest-win-x86\sdk\2.2.0-preview1-007927\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26110-02
  Build    : 77152705cd56e7d89f52585959ec3559d91084c4
```

2. My csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <RuntimeFrameworkVersion>2.1.0-preview1-26210-0</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="runtime.win-x86.Microsoft.NETCore.Runtime.CoreCLR" Version="2.1.0-preview1-26210-0" />
  </ItemGroup>
</Project>
```

I tried setting `	<Platform>x86</Platform>` but it did not change anything

3. My NuGet.Config file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />

    <add key="local coreclr" value="C:\Projects\forks\coreclr\bin\Product\Windows_NT.x86.Debug\.nuget\pkg" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />

  </packageSources>
</configuration>
```

4. dotnet restore complains a little about dependencies:

```
PS C:\Projects\forks\coreclr\fresh> dotnet restore
C:\Projects\forks\coreclr\fresh\fresh.csproj : warning NU1603: fresh depends on Microsoft.NETCore.App (>= 2.1.0-preview1-26210-0) but Micros
```

5. dotnet publish creates the package:

```
C:\Projects\forks\coreclr\fresh\fresh.csproj : warning NU1603: fresh depends on Microsoft.NETCore.App (>= 2.1.0-preview1-26210-0) but Microsoft.NETCore.App 2.1.0-preview1-26210-0 was not found. An approximate best match of Microsoft.NETCore.App 2.1.0-preview2-25430-06 was resolved.
  fresh -> C:\Projects\forks\coreclr\fresh\bin\x86\Debug\netcoreapp2.1\win-x86\fresh.dll
  fresh -> C:\Projects\forks\coreclr\fresh\bin\x86\Debug\netcoreapp2.1\win-x86\publish\
```

6. the package contains the dll files from my local build:

![image](https://user-images.githubusercontent.com/6011991/34849192-d7643f82-f721-11e7-88e0-9a50312d841b.png)

7. **but when I try to run the executable it fails. This is what I found in Event Log:**

```
Faulting application name: fresh.exe, version: 0.0.0.0, time stamp: 0x5956d194
Faulting module name: coreclr.dll, version: 4.6.26210.0, time stamp: 0x5a57c9e4
Exception code: 0x80131506
Fault offset: 0x00322ae0
Faulting process id: 0x44d8
Faulting application start time: 0x01d38b264ccd78b1
Faulting application path: C:\Projects\forks\coreclr\fresh\bin\x86\Debug\netcoreapp2.1\win-x86\publish\fresh.exe
Faulting module path: C:\Projects\forks\coreclr\fresh\bin\x86\Debug\netcoreapp2.1\win-x86\publish\coreclr.dll
Report Id: 95d6d273-f845-43c5-9a3d-7401ee4432c4
Faulting package full name: 
Faulting package-relative application ID: 
```

**Suspicious thing:**

When I reference `Microsoft.NETCore.Runtime.CoreCLR` the way described in the docs the dotnet cli fails to restore the package:

```xml
<PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR" Version="2.1.0-preview1-26210-0" />
```

I used VS to check if the files produced by the build are recognized as NuGet packages and they are:

![image](https://user-images.githubusercontent.com/6011991/34849553-0554b7d6-f723-11e7-94e9-0f5a01a6ce0f.png)

I used the full package name as workaround:

```xml
    <PackageReference Include="runtime.win-x86.Microsoft.NETCore.Runtime.CoreCLR" Version="2.1.0-preview1-26210-0" />
```

@jkotas Jan do you have any idea what could go wrong? I have tagged you because you are the last person who edited the `.md` docs file

I just need to be able to debug and run test this local core clr build. If there is any other way to do this then please let me know.

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md#update-coreclr-from-raw-binary-output should work fine. It is what I have been doing.

https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md#update-coreclr-using-runtime-nuget-package has a big warning that these steps do not work anymore. I do not think there is a easy way to make these steps work. It would be best to delete them.

These steps should be eventually replaced by steps to build Microsoft.NetCore.App NuGet package locally. These steps will be result of [Build from Source](https://github.com/dotnet/core-eng/issues/791).

**Comment by adamsitnik** [comment]
@jkotas thanks for the answer!

**Comment by adamsitnik** [comment]
@jkotas I will try one more thing, if I fail I am going to create a PR with removing this part of the docs

**Comment by adamsitnik** [comment]
@jkotas I got it working!

the solution is to also reference the JIT package:

```xml
<PackageReference Include="runtime.win-x86.Microsoft.NETCore.Jit" Version="2.1.0-preview1-26210-0" />
```

```cs
static void Main(string[] args)
{
	var coreAssemblyInfo = System.Diagnostics.FileVersionInfo.GetVersionInfo(typeof(object).Assembly.Location);
	Console.WriteLine($"Hello World from Core {coreAssemblyInfo.ProductVersion}");
	Console.WriteLine($"The location is {typeof(object).Assembly.Location}");
}
```

```
Hello World from Core 4.6.26210.0 @BuiltBy: adsitnik-MININT-O513E3V @SrcCode: https://github.com/dotnet/coreclr/tree/66bd34e16bc9058263a2c5cd522ee6b59e1b4419
The location is C:\Projects\forks\coreclr\last_chance\bin\Debug\netcoreapp2.1\win-x86\publish\System.Private.CoreLib.dll
```

I am going to send PR with docs update tomorrow and then close this issue.
