### ISSUE TITLE
Non-Windows R2R testing fails

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#15845]
All non-Windows R2R jobs are failing with:
```
23:43:46 Unable to precompile /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_r2r_gcstress15_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/xunit.performance.api.dll.
23:43:46 Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
23:43:46 Copyright (c) Microsoft Corporation.  All rights reserved.
23:43:46 
23:43:46 Error: Could not load file or assembly 'Microsoft.3rdpartytools.MarkdownLog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=aebcf7a12080279b'. The system cannot find the file specified.
23:43:46  (Exception from HRESULT: 0x80070002 (COR_E_FILENOTFOUND))
23:43:46 Error compiling /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_r2r_gcstress15_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/xunit.performance.api.dll: Could not find or load a specific file. (Exception from HRESULT: 0x80131621 (COR_E_FILELOAD))
23:43:46 Error: compilation failed for "/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_r2r_gcstress15_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/xunit.performance.api.dll" (0x80131621)
23:43:46 
Build step 'Execute shell' marked build as failure
```

e.g.,
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_r2r_gcstress15_tst/13/consoleFull#-8536224876a086b3e-df04-41d2-bc4d-43e8f9406d07
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_r2r_jitminopts_tst/69/consoleFull#-8536224876a086b3e-df04-41d2-bc4d-43e8f9406d07
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_r2r_jitstress1_tst/70/consoleFull#-8536224876a086b3e-df04-41d2-bc4d-43e8f9406d07
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_r2r_tst_prtest/2/consoleFull#-8536224876a086b3e-df04-41d2-bc4d-43e8f9406d07

**Comment by BruceForstall** [comment]
@jorive @brianrob Is this something you know about?

**Comment by BruceForstall** [comment]
cc @RussKeldorph

**Comment by BruceForstall** [comment]
btw, this is happening due to the `--crossgen` argument to tests\runtest.sh, which invokes the `precompile_overlay_assemblies` function to precompile basically every dll in the `CORE_ROOT` overlay directory.

It looks like there is already a mechanism to skip certain files: see the tests\skipCrossGenFiles.*.txt files. Perhaps xunit.performance.api.dll should be added to those lists? Or, maybe the Microsoft.3rdpartytools.MarkdownLog dependency should be added to the overlay directory?

**Comment by jorive** [comment]
Adding @dotnet/rap-team

**Comment by jorive** [comment]
@BruceForstall No, sorry, this is not something I know about. Is this failure new? Do you have a small repro?

**Comment by BruceForstall** [comment]
I don't have a small repro. You can see it by triggering a R2R job on a PR, e.g. "Ubuntu x64 Checked R2R Build and Test". You can see (some of) the commands being run by looking at the console output, e.g., https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_r2r_gcstress15_tst/13/consoleText.

The basic command being run (and failing, from runtest.sh) is:
```
$overlayDir/crossgen /Platform_Assemblies_Paths $overlayDir $filename
```

So, something like:
```
/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_r2r_gcstress15_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_r2r_gcstress15_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_r2r_gcstress15_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/xunit.performance.api.dll
```

**Comment by BruceForstall** [comment]
I've submitted a PR to work around this by not crossgen'ing xunit.performance.api.dll.
