### ISSUE TITLE
Update UAP TFM on master branch to be vNext

### ISSUE THREAD

**Issue by joperezr** [dotnet/coreclr#15849]
As we get ready to ship .NET Core 2.1, we need to make sure that we rev up the version of UAP vnext on our master branch since we shouldn't ship OOB packages that have a uap asset with the old TFM. Because we haven't done this yet, we are currently seeing problems trying to consume OOB packages in UWP like the one described here #25024 about System.Memory package. Once that is fixed, we should be able to consume packages like System.Memory again.

@joshfree I suppose we don't know yet what will the next UAP TFM be, but is it safe to just use 10.0.RS3+1 for now? (16299 + 1 = 10.0.16300). 

cc: @weshaggard

**Comment by jkotas** [comment]
Did you mean to open this in CoreFX? I do not think this has anything to do with CoreCLR.

**Comment by joperezr** [comment]
oh sorry, yes that was my bad, moving to corefx.

**Comment by joperezr** [comment]
Issue moved to [dotnet/corefx #26305](https://github.com/dotnet/corefx/issues/26305) via [**ZenHub**](https://www.zenhub.com/)
