### ISSUE TITLE
JIT\SIMD\VectorConvert tests fail on x86 Checked with AVX2 disabled

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#15848]
The `JIT_SIMD._VectorConvert_r_VectorConvert_r_._VectorConvert_r_VectorConvert_r_cmd` and `JIT_SIMD._VectorConvert_ro_VectorConvert_ro_._VectorConvert_ro_VectorConvert_ro_cmd` tests are failing in the x86 Checked build when AVX2 is also disabled. They appear to pass as expected when AVX is also disabled.

* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitx86hwintrinsicnoavx2/1/
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitx86hwintrinsicnoavx2/2/

I did validate locally that the `COMPlus_EnableIncompleteISAClass` flag has no impact on the result.

**Comment by tannergooding** [comment]
Code can basically be simplified to:
```C#
public static int VectorConvertSingleUInt(Vector<Single> A)
{
    Vector<UInt32> B = Vector.ConvertToUInt32(A);
    Vector<Single> C = VectorConvertUIntSingle(B);

    return CheckResult(A, B, C);
}

public static Vector<Single> VectorConvertUIntSingle(Vector<UInt32> B)
{
    return Vector.ConvertToSingle(B);
}

public static int CheckResult(Vector<Single> A, Vector<UInt32> B, Vector<Single> C)
{
    int returnVal = Pass;
    for (int i = 0; i < Vector<Single>.Count; i++)
    {
        UInt32 uint32Val = (UInt32)A[i];
        Single cvtSglVal = (Single)uint32Val;
        if (B[i] != uint32Val)
        {
            Console.WriteLine("B[" + i + "] = " + B[i] + ", UInt32Val = " + uint32Val);
            returnVal = Fail;
        }
        if (C[i] != cvtSglVal)
        {
            Console.WriteLine("C[" + i + "] = " + C[i] + ", cvtSglVal = " + cvtSglVal);
            returnVal = Fail;
        }
    }
    return returnVal;
}
```

The problematic code is `Vector.ConvertToSingle` (it doesn't matter if inlined or not, I pulled it out to isolate the generated assembly).

[Avx2.txt](https://github.com/dotnet/coreclr/files/1630367/Avx2.txt)
[NoAvx2.txt](https://github.com/dotnet/coreclr/files/1630368/NoAvx2.txt)

The primary difference is that we do (AVX2):
```asm
mov      eax, 0xD1FFAB1E
vmovd    xmm0, eax
vpbroadcastd ymm0, ymm0
```

vs (AVX)
```asm
mov      eax, 0x5300
vpxor    xmm0, xmm0
vpinsrw  xmm0, eax, 1
vpinsrw  xmm0, eax, 3
vmovlhps xmm0, xmm0
```

Relevant codegen is here: https://github.com/dotnet/coreclr/blob/master/src/jit/simdcodegenxarch.cpp#L1076

**Comment by CarolEidt** [comment]
I believe that this is a pre-existing bug, and that it has been hidden by the pseudo-random test inputs. The problem is that casting from float to unsigned is not supported by hardware. The existing implementation simply uses the signed conversion, which is not correct. For scalar code the JIT converts to double, then calls a helper to convert to uint32. If I modify the test to always use `MinValue` and `MaxValue` as the first two elements, it fails on AVX2 as well.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib @tannergooding @fiigii - looking back at my old notes on the vector conversions, I had suggested that we leave the floating point-to-unsigned conversions un-accelerated. While reviewing the final implementation, I failed to notice that they were being implemented as the same as the signed conversions.
At this point, there are 2 (or 3 depending on how you count) alternatives:
- Stop recognizing these as intrinsics.
- Fix the implementation:
  - Expand them in the importer in terms of existing intrinsics (produces bigger trees, but might be simpler, and likely to produce similar code), OR
  - Allocate register temps and do the expansion in the code generator.

I'm interested in feedback on these alternatives. Thanks in advance!

**Comment by 4creators** [comment]
> Expand them in the importer in terms of existing intrinsics (produces bigger trees, but might be simpler, and likely to produce similar code)

We can provide reasonable, accelerated support for this operation in terms of intrinsics. IMO it would more convenient to expanding this operation in C# Vector code. This would be probably most flexible solution as this would not depend on additional functionality from Jit compiler and software fallback would be well handled by other runtimes i.e. Mono.

The operation could be redefined as two operations 1) in checked context will convert to unsigned integer unless one of the Vector floating point values is less than zero what should result in `OverflowException`, 2) in unchecked context will convert to unsigned like in a "binary" way what I understand as treating sign as a most significant bit of unsigned integer. Obviously, software fallback should support this behavior.

**Comment by tannergooding** [comment]
I think the simplest fix might be: `Stop recognizing these as intrinsics.` (I believe we already have a software fallback).

I would like to see the implementation fixed, but it might be worthwhile waiting and seeing if we can do that using the HWIntrinsics.

The algorithm (for HWIntrinsics or JIT support) should be effectively this: https://github.com/Microsoft/DirectXMath/blob/master/Inc/DirectXMathConvert.inl#L158

It only requires SSE instructions, which are all but complete (for the basic codegen scenario, only Store is remaining, and many of the simple operations already support containment).

It should be easy to see if we can actually maintain performant numbers using HWIntrinsics rather than hardcoded JIT support.

**Comment by CarolEidt** [comment]
> The algorithm (for HWIntrinsics or JIT support) should be effectively this: https://github.com/Microsoft/DirectXMath/blob/master/Inc/DirectXMathConvert.inl#L158

Unfortunately, that is not compatible with what the JIT is doing for conversion of unsigned types. For uint32, the x64 jit does a float->long conversion and then simply truncates the result. For x86, it does a float->double->ulong conversion, and then truncates the result. This gives the right answer for in-range values, and the spec says:
> If overflow occurs converting a floating-point type to an integer, or if the floating-point value being converted to an integer is a NaN, the value returned is unspecified.

I think we need to be compatible with what the JIT does for scalar code.

> It should be easy to see if we can actually maintain performant numbers using HWIntrinsics rather than hardcoded JIT support.

I'm not really sure how performant we need to be for conversion to unsigned, so I'm not sure how much it's worth to special-case each target.

**Comment by fiigii** [comment]
> Expand them in the importer in terms of existing intrinsics (produces bigger trees, but might be simpler, and likely to produce similar code), OR

I am not sure if it is worthwhile to try a new JIT approach for `Vector<T>` intrinsic at this time.
Meanwhile, I don't know how many applications/libraries rely on the `Vector.ConvertToSingle(Vector<UInt32>)` to get the _performance improvement_.

I think we can adopt the first approach ("Stop recognizing these as intrinsics.") if we do not want to pay much engineering effort for this API. 
Then, 
1. wait for refactoring all `Vector<T>` via hardware intrinsic in managed code. OR,
2. re-enable and improve JIT implementation when critical uses (i.e., CoreFX) get performance bottlenecks from managed `Vector.ConvertToSingle(Vector<UInt32>)`.
