### ISSUE TITLE
SlowTailCallArgs test fails with timeout for GCStress=3

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#15851]
This recently added test (https://github.com/dotnet/coreclr/commit/1a67e84aca889cf94c716a7847cfe0b4d1ee62d6) fails in GCStress=3 jobs with timeout, e.g.:

x64 Windows checked:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0x3/63/#showFailuresLink

x86 Windows checked:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0x3/58/#showFailuresLink

Seems like it might need to be marked
```
<GCStressIncompatible>true</GCStressIncompatible>
```
in SlowTailCallArgs.csproj, unless there is a better way to get it to pass in GCStress jobs.

**Comment by kouvel** [comment]
Ran it for about 30 minutes with no failure yet but it's not finishing though progressing. I'll disable the test under GCStress as you suggested.

**Comment by kouvel** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/16048
