### ISSUE TITLE
Dev10_535767 fails with GCStress=3

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#15852]
For x86 Windows with `COMPlus_GCStress=3`, test baseservices\compilerservices\dynamicobjectproperties\Dev10_535767\Dev10_535767.cmd fails with output like this:

```
...
Running test TS:Random CS:Random 10000 entries...
TestError: Node 87 wasn't collected even though it was unreachable
```

The periodic job:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0x3/

Both 58 and 57 show this failure.

I don't see it on x64.

**Comment by BruceForstall** [comment]
@jkotas @kouvel @swgillespie Seems like a VM or GC bug (or long-standing test issue?). Who can own this?

**Comment by jkotas** [comment]
The test is calling `WaitForPendingFinalizers` so it is most likely a test issue.

**Comment by kouvel** [comment]
The failure seems to be sporadic, is there something about `WaitForPendingFinalizers` that would make it unreliable? I was thinking of trying to isolate the GC reference nulling into a separate method but it doesn't seem like that would help.

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/issues/4093#issuecomment-296853982 explains the typical issue with `WaitForPendingFinalizers`.

**Comment by kouvel** [comment]
Thanks, looks like that was the issue. Fixed with https://github.com/dotnet/coreclr/pull/16048.
