### ISSUE TITLE
How to debug DllNotFoundException in Linux 

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/coreclr#15863]
I have a coreclr project which dynamically loads native library `libabc.so` . This works in Ubuntu.
So, basic code is fine. However, In RedHat, I am getting error:

```
Unable to load DLL 'libabc.so': The specified module or one of its dependencies 
could not be found.  (Exception from HRESULT: 0x8007007E)
--
<my_stack_trace>
```

I have tried adding path of library and dependent assemblies to LD_LIBRARY_PATH. That didn't work.
How can I debug this ?

I set `export COREHOST_TRACE=1`.
I am starting executable via :

```
export COREHOST_TRACE=1
exec dotnet abc.dll > out.out
```

But `out.out` is also empty.

In windows, we have Fuslogvw.exe (Assembly Binding Log Viewer) to debug these issues.
How can I debug this in Linux or RedHat specifically ?

**Comment by jkotas** [comment]
cc @wtgodbe This is related to #10520 that you are working on.

**Comment by jkotas** [comment]
@ashishnegi Try to run `ldd -r libabc.so` to find out why the library is failing to load. https://github.com/dotnet/coreclr/issues/14923#issuecomment-342893930 has some other useful links on how to diagnose this issue. Please let us know how you have done to diagnose the problem once you figure it out. We would like to make the diagnostic of these issues more straightforward.

**Comment by ashishnegi** [comment]
`ldd -r libabc.so` shows all dependencies in right location. I tried `strace`. Its output does not show `abc.so` being accessed. So, I guess this is a dependency problem. I grep for all dependencies of `abc.so`. Not all are `open`ed. Dependencies which are opened are rightly located.
Is there anything else I can try ?

**Comment by janvorli** [comment]
@ashishnegi have you really run the `ldd -r libabc.so` on redhat?

**Comment by janvorli** [comment]
I mean, haven't you run it on Ubuntu instead?

**Comment by ashishnegi** [comment]
I have run commands on redhat. 
It shows `not found` for 2 libraries. but once I run the command with :
`LD_LIBRARY_PATH=/path/to/not_found_library ldd -r libabc.so` it shows all libraries with their location.
While running my application, I set the LD_LIBRARY_PATH in my shell script and then start the process. I get same error.

As stated before, with `strace` I don't even find `open` call for `abc.so`. I see `open` calls for `some` dependencies of `abc.so` which are located correctly as per strace.

**Comment by janvorli** [comment]
I wonder - do you use "export LD_LIBRARY_PATH=/path/to/not_found_library" in your script? Without the "export", it would not have effect on the child process.
You can also just prefix the invocation of your process with `LD_LIBRARY_PATH=/path/to/not_found_library` (`LD_LIBRARY_PATH=/path/to/not_found_library myprocess`). That way, the path influences only your process.
You can try to track the LD attempts using LD_DEBUG env variable, see e.g. http://www.bnikolic.co.uk/blog/linux-ld-debug.html

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/15831 has improved the error message for DllNotFoundException in Linux
