### ISSUE TITLE
Mismatching allocation and deallocation in VirtualAllocExNuma()

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/coreclr#15867]
This was found with Cppcheck

pal/src/numa/muna.cpp has `VirtualAllocExNuma()` function that does this:

    unsigned long *nodeMask = new unsigned long[nodeMaskLength];
    //whatever, then
    free(nodeMask);

Pairing `new[]` with `free()` yields undefined behavior. I guess `malloc()` with a null check should be used here - same as with other memory allocations in this translation unit.

**Comment by janvorli** [comment]
@Dmitry-Me Thank you very much for spotting that. I was originally using new / delete there and converted everything to malloc / free during the change cleanup and obviously missed that place.
