### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by SashaDeveloper** [dotnet/coreclr#15899]
I use dependency injection in .Net Core and when calling the service method gets the following error: '((System.RuntimeType)((System.Reflection.RuntimeMethodInfo)e.TargetSite).ReflectedType).Declaring Method' threw an exception of type 'System.InvalidOperationException'.

**Comment by jkotas** [comment]
@SashaDeveloper Could you please share test that demonstrates the issue?

**Comment by SashaDeveloper** [comment]
Register service in Startup: services.AddScoped<ITestService, TestService>();
Code in controller:
private readonly ITestService _testService;
 public TestController(IMapper mapper,ITestService testService){
 _testService=testService;
}
Code in action controller:
await _testService.CallMethod();
![reflection](https://user-images.githubusercontent.com/32124643/35044748-32516b1e-fb9a-11e7-825b-9a792c380f86.png)
This code working last week, but now not working.

**Comment by jkotas** [comment]
I am sorry, but I am not able to reproduce the problem with what you have shared.

Let's have Visual Studio installed. What exact steps do I need to do to see the problem?

If it is easier, you can push a test project that reproduces the problem to your github account and share link to it.
