### ISSUE TITLE
Ahead of time JIT "warm up" for .NET web apps

### ISSUE THREAD

**Issue by Plasma** [dotnet/coreclr#159]
Hey team,

I'd like to propose a CLR runtime feature that allows me to tell my application to "warm up" and "pre jit" as much as possible so that the first IIS web request to reach my .NET website does not incur this penalty.

There are various tools to try and "warm up" a .NET site at this time (IIS Warm Up module, App Pool mode to AlwaysRunning, etc) but none of these directly address the compilation/JIT step incurred the first time a code path is executed during a web request.

It would be _fantastic_ to be able to call a runtime method (or compilation flag?) that instructs the runtime to warm up as much as possible now (pay that cost up front) instead of incurring it for every new web request using a different code path.

**Comment by jkotas** [comment]
We are going to have crossgen tool that allows the .dlls to be precompiled. The tool is not part of the cmake build yet, but the sources are there already at https://github.com/dotnet/coreclr/tree/master/src/tools/crossgen . It is also available in the CoreCLR that is bundled with ASP.NET vNext.

The crossgen tool is similar to NGen from desktop CoreCLR. It does not have the limitations of NGen, and it is designed to work well for ASP.NET vNext on CoreCLR. k-crossgen command in the ASP.NET vNext  https://github.com/aspnet/XRE/blob/dev/scripts/k-crossgen.cmd should run it on every assembly from the website.

**Comment by davidfowl** [comment]
Yep. We're also working on an end to end story to enable this for deployment `kpm bundle --native` that will integrate something like this (we have this today but it's not well tested). We're also looking at a way to do this during package restore (stay tuned).

**Comment by Plasma** [comment]
Great news thank you. Are there any benchmarks available showing off Thai feature or incidental results internally?

**Comment by MattWhilden** [comment]
It's not really my area but I presume the ASPNET folks will announce things when they finish getting all the pieces together. However, it will be similar to the wins you'd get for .NET applications if you applied the NGEN technology.

**Comment by jkotas** [comment]
https://github.com/aspnet/ have added support for crossgen a while ago.

**Comment by papaslavik** [comment]
Hello, is there a way to emit some code for arm using crossgen on a x64 machine?
