### ISSUE TITLE
[RyuJIT\Sse] 81 test failures in local x64 Checked build for optimized (ro) Sse hardware intrinsics tests

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#15918]
To reproduce: 
1. Clone current master branch - tested on commit: 84efbc8e71fff8ccffdd637017036d2dc0f666df
2. Build on Windows for x64 Checked
3. set COMPlus_EnableIncompleteISAClass=1
4. run tests: tests\runtest x64 Checked 

Large part of errors is due to assert:
```
Assert failure(PID 17088 [0x000042c0], Thread: 13556 [0x34f4]): Assertion failed 'child->isContained()' in 'IntelHardwareIntrinsicTest.Program:Main(ref):int' (IL size 232)

File: e:\src\ms\dotnet\coreclr-sse\src\jit\lsraxarch.cpp Line: 494
```
Attached are logs from one of the runs. Tested 2 times by doing fresh clone, build, test.

[TestRunResults_Windows_NT__x64__Checked_Logs.zip](https://github.com/dotnet/coreclr/files/1644219/TestRunResults_Windows_NT__x64__Checked_Logs.zip)

@tannergooding @fiigii @sdmaclea

**Comment by fiigii** [comment]
Will be fixed by https://github.com/dotnet/coreclr/pull/15901

**Comment by 4creators** [comment]
> Bad merge between two of my PRs (#15538) and (#14736) that resulted in the System.Math.Round, System.Math.Floor, and System.Math.Ceiling functions asserting in Debug/Checked builds on non-AVX enabled machines.

> Will be fixed by #15901

Actually I have run the test on AVX2 machine with all ISA extensions enabled and this seems to deal with `non-AVX enabled machines`. Will it fix test on Vex path as well?

**Comment by tannergooding** [comment]
@4creators, that was one of the issues.

The other issue (the assert in `lsraxarch.cpp` on L494, which is also resolved by the PR) was that adding the fields to the opaque vector types (e.g. `Vector128<T>`, in https://github.com/dotnet/coreclr/pull/15897) in order to support debugging caused the structs to undergo promotion where they shouldn't.

**Comment by fiigii** [comment]
> Will it fix test on Vex path as well?

That is another story. `Assertion failed 'child->isContained()'` is caused by the current DebugView change, which also fixed by #15901

**Comment by 4creators** [comment]
> caused the structs to undergo promotion where they shouldn't

When do you think it can go in? If it is a bit longer than now perhaps we could revert #15897 until #15901 will get merged. I have tried to work on SSE2 but this problem is blocking my Sse2 testing as well.

**Comment by tannergooding** [comment]
I believe the PR is just waiting for sign-off from @CarolEidt on the latest changes.

**Comment by 4creators** [comment]
> I believe the PR is just waiting for sign-off from @CarolEidt on the latest changes.

That's good. I will revert locally and try to work until it is fixed.

**Comment by tannergooding** [comment]
@4creators, this should be resolved now. Let me know if you are still seeing issues.

**Comment by 4creators** [comment]
@tannergooding thanks, all Sse tests are passing now on all configurations.
