### ISSUE TITLE
Setting AsyncLocal has very high allocation

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#1591]
Setting an AsyncLocal value creates a [new ExecutionContext](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/ExecutionContext.cs#L194) which then creates a [new Dictionary and List](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/ExecutionContext.cs#L72) enumerating the original ones and copying to new; at which point it then switches the ThreadStatic ExecutionContext to be the new one.

In aspnet setting an AsyncLocal value generates 1.36MB per 4k requests:

![asynclocal](http://aoa.blob.core.windows.net/aspnet/async_local_a.png)

Which means at 1M rps it generates 340 Mbytes per second of garbage for the GC to flush; and at 6M rps it generates 2 GBytes of garbage per second; or 122 GBytes per minute.

**Comment by ericeil** [comment]
Thanks for the feedback; this is something we'd like to improve, and just need to prioritize it relative to other work.

**Comment by davidfowl** [comment]
@ericeil this affects the ASP.NET default pipeline. How do we get this prioritized?

**Comment by ericeil** [comment]
#1629 should help a little.  @benaadams, would you mind running your experiment again, with this change, to see how much it helps?

**Comment by benaadams** [comment]
@ericeil may be some time... though building the C++ has reminded me why one of the reasons why I prefer C# :grin:

**Comment by benaadams** [comment]
Well that was a strange build process journey... I think I missed out a couple requests from them the count; lot of strange activity going on in a full debug build to the bottom...

Nevertheless; that's taken it from 1360 kB to 976 kB; so has shaved a third off!

![set local top](http://aoa.blob.core.windows.net/aspnet/set-local-top.png)

Drilling down a bit further

![set local bottom](http://aoa.blob.core.windows.net/aspnet/set-local-bottom.png)

Looks good to me.

**Comment by ericeil** [comment]
@benaadams, thanks!

**Comment by davidfowl** [comment]
W00p!

**Comment by benaadams** [comment]
Closing as fixed. Other options discussed like mutability wouldn't help this particular use case and would make testing and correct behaviour more difficult.
