### ISSUE TITLE
ArrayPool logging initialization is 70% of startup for empty program

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#15954]
Empty program executes about 320 methods managed methods today (in release build). Initialization of ArrayPool logging (ArrayPoolEventSource) is responsible for 220 of them. When the ArrayPool initialization is commented out, I am back to about 100 where we used to to be historically.

Is the ArrayPool logging valueable enough to contribute this much to startup cost of empty program? Can we make it cheaper or not have it?

**Comment by jkotas** [comment]
cc @vancem

**Comment by stephentoub** [comment]
Just curious, what in an empty program uses ArrayPool?

**Comment by jkotas** [comment]
The first call comes from Path APIs:
```
System_Private_CoreLib!System.Runtime.InteropServices.StringBuffer..ctor(Int32)+0x5b
System_Private_CoreLib!System.IO.PathHelper.Normalize(System.String, Boolean, Boolean)+0x57
System_Private_CoreLib!System.IO.Path.GetFullPath(System.String)+0x3b1
System_Private_CoreLib!System.AppDomain.NormalizePath(System.String, Boolean)+0x2e
System_Private_CoreLib!System.AppDomain.NormalizeAppPaths(System.String)+0x1d4
System_Private_CoreLib!System.AppDomain.Setup(System.Object)+0x651
```

**Comment by benaadams** [comment]
Its all to run `log.IsEnabled()` and get `false` back.

I had a look at this before and but couldn't work out how to address it: Guid/Sha1, CultureInfo and Reflection

![image](https://user-images.githubusercontent.com/1142958/35197802-033e6232-fedd-11e7-9de5-3df4dfc9a3c8.png)

**Comment by benaadams** [comment]
With Prestub/Unknown contributing:
![image](https://user-images.githubusercontent.com/1142958/35197893-7b48322a-fede-11e7-9744-bda35e6de9ef.png)

**Comment by benaadams** [comment]
Time wise 87% is EventSource.GetGuid

**Comment by Alois-xx** [comment]
@benaadams : Then using the internal EventSource ctor with the guid would be way to go. Reading the Guid via reflection is costly after all. FrameworkEventSource()  uses this trick.

**Comment by benaadams** [comment]
>Then using the internal EventSource ctor with the guid would be way to go. 

Seems to do the trick, goes straight to `Initialize` https://github.com/dotnet/coreclr/pull/16054 

Post 
![image](https://user-images.githubusercontent.com/1142958/35476200-010b8e88-03a4-11e8-8d88-fd891102d54f.png)

**Comment by Alois-xx** [comment]
That was a fast change. The numbers look great.
