### ISSUE TITLE
CoreCLR failed to build due to the error C2065: 'DNER_IsStructArg': undeclared identifier

### ISSUE THREAD

**Issue by shanshan0309** [dotnet/coreclr#15960]
I tried to build CoreCLR on Windows with VS2017 Update2. It failed to build due to the error C2065: 'DNER_IsStructArg': undeclared identifier. This issue is caused by master branch revision [128893e](https://github.com/dotnet/coreclr/commit/128893e65c3e748e2ac9b85cbc6e0560cf84e2e1). Could you please help take a look at this? Thank you!

**You can repro this issue as the steps below:**
1. git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2. Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\CoreCLR\src
3. build x86 release -Rebuild -- /clp:ShowCommandLine

**Error info:**
PGOMGR : warning PG0188: No .PGC files matching 'D:\CoreCLR\src\packages\optimization.windows_nt-x86.pgo.coreclr\99.99.99-master-20180116-0045\data\clrjit!*.pgc' were found. [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\jit\standalone\clrjit.vcxproj]
PGOMGR : warning PG0188: No .PGC files matching 'D:\CoreCLR\src\packages\optimization.windows_nt-x86.pgo.coreclr\99.99.99-master-20180116-0045\data\coreclr!*.pgc' were found. [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\dlls\mscoree\coreclr\coreclr.vcxproj]
**d:\coreclr\src\src\jit\morph.cpp(4970): error C2065: 'DNER_IsStructArg': undeclared identifier [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\jit\armelnonjit\armelnonjit.vcxproj]**
d:\coreclr\src\src\jit\morph.cpp(4970): error C2065: 'DNER_IsStructArg': undeclared identifier [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\jit\legacynonjit\legacynonjit.vcxproj]
d:\coreclr\src\src\jit\morph.cpp(4970): error C2065: 'DNER_IsStructArg': undeclared identifier [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\jit\protononjit\protononjit.vcxproj]

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/15958

**Comment by shanshan0309** [comment]
@jkotas, thank you so much for fixing this issue. I've verified your fix works well.
