### ISSUE TITLE
Improve CI coverage for release builds

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#15963]
The recent build break in official build (#15958, #15960) highlighted that we have no CI coverage for release builds. I think we should look into improving it:

- `CentOS7.1 x64 Checked Innerloop Build and Test` and `Ubuntu x64 Checked Innerloop Build and Test` have huge overlap. One of them should be changed to release build to have better coverage.
- We should have at least one 32-bit release build. Not sure what the best option for it is.

**Comment by jkotas** [comment]
cc @jashook @RussKeldorph

**Comment by jashook** [comment]
This has somewhat been addressed with #15813; however, the centos release jobs are broken and need to be fixed. #16035 reverts the ci back to use checked centOS until the release jobs are green.

**Comment by RussKeldorph** [comment]
We are currently testing linux-musl-x64 release builds as part of the default mix.  Re-open if this isn't sufficient.
