### ISSUE TITLE
Potential Specification & Implementation Mismatch: Whether a method definition overrides inherited method.

### ISSUE THREAD

**Issue by Imisnew2** [dotnet/coreclr#15969]
From this version of the specification:
https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf

CLS Rule 4 states:
> Assemblies shall follow Annex 7 of Technical Report 15 of the Unicode Standard
> 3.0 governing the set of characters permitted to start and be included in identifiers, available online
> at http://www.unicode.org/unicode/reports/tr15/tr15-18.html. Identifiers shall be in the
> canonical format defined by Unicode Normalization Form C. For CLS purposes, two identifiers
> are the same if their lowercase mappings (as specified by the Unicode locale-insensitive, one-toone
> lowercase mappings) are the same. That is, for two identifiers to be considered different
> under the CLS they shall differ in more than simply their case. However, in order to override an
> inherited definition the CLI requires the precise encoding of the original declaration be used.

The key part I think the CLR violates is the last sentence:
> However, in order to override an inherited definition the CLI requires the precise encoding of
> the original declaration be used.

I believe that means that the lowercase mapping logic described just prior should not apply? If so, here's how I constructed an example that appears to violate the rule:

```
Imports System

Class Program
    Shared Sub Main(args As String())
        Dim a As A = new A()
        Dim b As B = new B()
        Dim c As A = new B()
        a.foo() ' Should output 'Foo'
        b.foo() ' Should output 'FOO' (direct call to B::Foo)
        c.foo() ' Should output 'FOO' (virtual call to B::Foo)
    End Sub
End Class

Class A
    Public Overridable Sub Foo() ' Emitted as A::Foo
        Console.WriteLine("Foo")
    End Sub
End Class

Class B
    Inherits A
    Public Overrides Sub FOO() ' Emitted as B::Foo
        Console.WriteLine("FOO")
    End Sub
End Class
```

Using ILDasm, I disassemble this program, change the name of 'B::Foo' to 'B::FOO', then, using ILAsm, I reassemble the program. If my interpretation of CLS Rule 4 is correct, B::FOO should no longer be considered an override of A::Foo, and the program should output:
```
Foo
Foo
Foo
```
Instead, I get the same output from both the pre-modified program and post-modified program:
```
Foo
FOO
FOO
```

Side-note: Interestingly enough, the "b.foo()" call from Main is emitted as 'B::Foo' although no 'B::Foo' exists (in the modified program), yet 'A::Foo' exists... Unsure whether in this context the lower-cased mapping should be checked, or if it should search the base-class for 'Foo'.

This is a fairly esoteric edge case, but one I was investigating due to trying to see exactly how far VB's case-insensitivity goes. It appears case-insensitive IL could be emitted and work properly using VB's case-insensitivity rules, but the Roslyn compiler seems to use a canonical name for any symbol that overrides another symbol (perhaps due to interpreting CLS Rule 4 the same way I have?).

**Comment by Imisnew2** [comment]
Someone had pointed out to me that this rule isn't a *requirement* for a runtime, merely adherence to the CLS (guidelines for language-interoperability, as I understand it). That said, I'll point to the text just above this rule in section I.8.5.1 "Valid names":

> All name comparisons are done on a byte-by-byte (i.e., case sensitive, locale-independent, also
> known as code-point comparison) basis. Where names are used to access built-in VES-supplied
> functionality (e.g., the class initialization method) there is always an accompanying indication on
> the definition so as not to build in any set of reserved names.

**Comment by RussKeldorph** [comment]
@jkotas For esoteric ECMA/runtime question.  @jaredpar re: Roslyn behavior.

**Comment by MichalStrehovsky** [comment]
> Instead, I get the same output from both the pre-modified program and post-modified program:

I'm not able to repro this.

If I update this line:

```
  .method public hidebysig strict virtual 
          instance void  Foo() cil managed
```

To this line:

```
  .method public hidebysig strict virtual 
          instance void  FOO() cil managed
```

And touch nothing else, I get:

```
Foo
Foo
Foo
```

Which is expected, because the runtime is case sensitive per the rules you're citing in your second comment (*All name comparisons are done on a byte-by-byte basis*) and FOO won't override a Foo (unless you put a `.override` on it).

CLS rules are recommendations to language designers to promote language interopability but the runtime doesn't enforce/follow them. Case insensitive languages wouldn't be able to target the CLI if the runtime was case insensitive.

> Side-note: Interestingly enough, the "b.foo()" call from Main is emitted as 'B::Foo' although no 'B::Foo' exists (in the modified program), yet 'A::Foo' exists... Unsure whether in this context the lower-cased mapping should be checked, or if it should search the base-class for 'Foo'

I can't find the rule in the ECMA-335 spec right now, but this behavior is by design - this is to allow moving a method to a base class without breaking binary compatibility.

**Comment by Imisnew2** [comment]
I see. My test appears to have been flawed. I was using .NET Core version 2.0.0 (as reported by dotnet --version) and matching copies of ILDasm/ILAsm. I re-used the <assembly>.deps.json from the original build, which contained:
```
[snip]
  "targets": {
    ".NETCoreApp,Version=v2.0": {
      "tmp/1.0.0": {
        "runtime": {
          "<original>.dll": {}
        }
      }
    }
  }
[snip]
```
Changing <original> -> <modified> causes the expected behavior (Foo three times).

Full instructions on how I built my test, annotated with where the flaw was:
```
$ mkdir tmp && cd tmp
$ dotnet new console --language VB
$ vim Program.vb
# Insert program from above
$ dotnet build
$ ildasm bin/Debug/netcoreapp2.0/tmp.dll > bin/Debug/netcoreapp2.0/tmp.il
$ cp bin/Debug/netcoreapp2.0/tmp.il bin/Debug/netcoreapp2.0/mod.il
$ vim bin/Debug/netcoreapp2.0/mod.il
# Change Foo to FOO for class B.
$ ilasm bin/Debug/netcoreapp2.0/mod.il -out:bin/Debug/netcoreapp2.0/mod.dll
$ for FILE in bin/Debug/netcoreapp2.0/tmp.*.json; do cp ${FILE} ${FILE//tmp/mod}; done
# ERROR: Did not update mods.deps.json to point at mod.dll -- still points at tmp.dll
$ dotnet bin/Debug/netcoreapp2.0/mod.dll
Foo
FOO
FOO
$ vim bin/Debug/netcoreapp2.0/mod.deps.json
# Update to contain mod.dll
$ dotnet bin/Debug/netcoreapp2.0/mod.dll
Foo
Foo
Foo
```
I am somewhat surprised by this (considering I ran 'dotnet .../mod.dll'), but I don't fully understand the reason the assembly itself needs to be in the deps.json file either, so I won't try to argue against that.

This issue can be closed. Sorry for the confusion.
