### ISSUE TITLE
Guid and Span: Possible optimization opportunity

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#16012]
I think this ctor..
https://github.com/dotnet/coreclr/blob/949b94eabd74f2632c220b03f998a802032d2b82/src/mscorlib/shared/System/Guid.cs#L48

 can be implemented as..

```C#
 public Guid(ReadOnlySpan<byte> b)
 {
        if (b.Length != 16)
            throw new ArgumentException(SR.Format(SR.Arg_GuidArrayCtor, "16"), nameof(b));
        
       this = Unsafe.ReadUnaligned<Guid>(ref MemoryMarshal.GetRerefernce(b));
}
```
The same for 
https://github.com/dotnet/coreclr/blob/949b94eabd74f2632c220b03f998a802032d2b82/src/mscorlib/shared/System/Guid.cs#L1019

```C#
public bool TryWriteBytes(Span<byte> destination)
{
	if (destination.Length < 16)
		return false;

	Unsafe.WriteUnaligned(ref MemoryMarshal.GetRerefernce(b), this);
	return true;
}
```

I cannot check the code generated but as Guid is 16 bytes long it can be read/written with one `mov`.

**Comment by benaadams** [comment]
@GrabYourPitchforks ?

**Comment by GrabYourPitchforks** [comment]
It's not _quite_ that straightforward because of endianness fixups, but you're right that there's likely good opportunity for improvements.

**Comment by omariom** [comment]
Like this?
```C#
...
if (!BitConverter.IsLittleEndian)
{
    _a = BinaryPrimitives.ReverseEndianness(_a);
    _b = BinaryPrimitives.ReverseEndianness(_b);
    _c = BinaryPrimitives.ReverseEndianness(_c);
}
```
would be interesing to see how it impacts the code generated for ARM.

**Comment by GrabYourPitchforks** [comment]
Yup, something like that seems correct.

**Comment by mikedn** [comment]
> would be interesing to see how it impacts the code generated for ARM.

Why? Most of the ARM devices are little endian. And I doubt that there are any .NET Core builds that support big endian anyway.

**Comment by GrabYourPitchforks** [comment]
@mikedn I don't think it would affect our ARM codegen since you correctly point out that we currently only support little-endian ARM. My comment about adding the checks for big-endian platforms are really more of a best practice thing. Perhaps we will run on big-endian archs in the future, so we should try to limit fragile code paths.

**Comment by mikedn** [comment]
> My comment about adding the checks for big-endian platforms is really more of a best practice thing

Yes, I know. And my comment was about omariom's comment about the impact this would have on ARM. The impact is 0 because ARM doesn't use big endian :grin:

In the meantime I wonder what kind of code the proposed update will generate, have to check...

**Comment by mikedn** [comment]
Yep, it looks like it will should good code. I haven't tried changing the actual `Guid` constructor but in a separate test method I get something like:
```asm
       C4E17A6F00           vmovdqu  xmm0, qword ptr [rax]
       C4E17A7F01           vmovdqu  qword ptr [rcx], xmm0
```

**Comment by omariom** [comment]
That's all good news.

So on the only difference on ARM will be that thanks to unalignment it will load/save it byte by byte?

**Comment by GrabYourPitchforks** [comment]
@omariom Perhaps in the worst case. Ideally the JIT is smart enough to know the capabilities of the target hardware and emit optimal assembly. But sometimes practice isn't as clean as theory. ;)

**Comment by mikedn** [comment]
Right, alignment could be a problem on ARM. The current ARM JIT ignores the `unaligned.` IL prefix that `ReadUnaligned` uses and generate something like:
```asm
000012  681A           ldr     r2, [r3]
000014  6002           str     r2, [r0]
000016  685A           ldr     r2, [r3+4]
000018  6042           str     r2, [r0+4]
00001A  689A           ldr     r2, [r3+8]
00001C  6082           str     r2, [r0+8]
00001E  68DA           ldr     r2, [r3+12]
000020  60C2           str     r2, [r0+12]
```
I'm not familiar enough with ARM to tell if this will blow up if the data is not 4 byte aligned. Supposedly newer ARM hardware does support unaligned access but I have no idea what hardware .NET Core is supposed to run on.

And even if it doesn't blow up there's the performance question. Unaligned reads tend to be ok as long as they don't span cache lines or pages and this may affect even x86/x64 hardware. But it's a somewhat unrelated issue as the JIT will use `vmovdqu` whenever you copy a `Guid` and not only in this specific case of using `ReadUnaligned` to read from a span.

**Comment by danmosemsft** [comment]
Perhaps you'd like to offer a PR with measuremnts @omariom ?

**Comment by omariom** [comment]
Right now I don't have such ability. Otherwise I would create a pr instead of the issue 😟 

May be someone else in this discussion can do it (pls 😊)?

**Comment by omariom** [comment]
Closed in https://github.com/dotnet/coreclr/pull/21336
