### ISSUE TITLE
CoCreateGuid in PAL doesn't conform with specs

### ISSUE THREAD

**Issue by morganbr** [dotnet/coreclr#1602]
CoCreateGuid in coguid.cpp currently just calls PAL_Random for sizeof(GUID) randomness, which misses a couple of important issues:
1. That doesn't match either the Microsoft or UUID specifications, which reserve bits for the type variant of the GUID.
2. The implementation of PAL_Random suggests there are cases where there's not good randomness available. That can cause UUID collisions.

We should consider a full UUID implementation, such as /proc/sys/kernel/random/uuid that can fall back to other generation methods.

**Comment by morganbr** [comment]
This looks related to https://github.com/dotnet/corefx/issues/3573 so assigning it to @janvorli.

**Comment by janvorli** [comment]
Fixed by #1738
