### ISSUE TITLE
Project workspace_cleaner failing for 24 days

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#16033]
Probably helpful to track down CI failures; but probably should be cleaning?

https://ci.dot.net/job/workspace_cleaner/

Permalinks
Last build (#454), 3 hr 8 min ago
Last stable build (#430), 24 days ago
Last successful build (#430), 24 days ago

Last failed build (#454), 3 hr 8 min ago
Last unsuccessful build (#454), 3 hr 8 min ago
Last completed build (#454), 3 hr 8 min ago

**Comment by RussKeldorph** [comment]
@dotnet/dnceng Do you know what this is and where this issue should be tracked?

**Comment by mmitche** [comment]
it's just something that deletes some directories on the static machines every now and again.

I altered it so that it doesn't run there, but this is not something to worry about

**Comment by MattGal** [comment]
Thanks, Matt!
