### ISSUE TITLE
Memory Corruption when using large structs with Span fields

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/coreclr#16044]
A couple of weeks ago, we added a large struct containing Span<byte> fields to corefxlab:
https://github.com/dotnet/corefxlab/blob/master/src/System.Buffers.Primitives/System/Buffers/ReadOnlyBufferReader.cs#L22

Since then, we started to see strange failures in CI:
1. The failures occur only on Mac OS X
2. The failures are non-deterministic
3. The failures look like memory corruption, i.e. write 5 bytes to memory (through a complex span using API), read it, get different 5 bytes read.

There are different tests (all using the by ref struct BufferReader) that fail, but the test that I observed failing several times is: https://github.com/dotnet/corefxlab/blob/master/tests/System.Buffers.Primitives.Tests/ReadableBufferReaderFacts.cs#L303

I tried to add instrumentation to the code to see what's happening, but after adding the instrumentation I cannot reproduce the bug anymore. The instrumentation was taking spans out from the by ref structs, storing then in locals (so I can dump data in the span content). This made me thing that we may not be reporting the interior pointer properly when ByReference<T> is buried in layers of structs (ByReference<T> -> span -> BytesReader ...) 

@jkotas, @VSadov, @pakrym, @davidfowl, @joshfree

**Comment by joshfree** [comment]
+@janvorli

**Comment by VSadov** [comment]
The method that may not be reporting all the GC refs is

https://github.com/dotnet/corefxlab/blob/b5b8dab751fe0c5f3f8dbf381cbe87e541f17a20/src/System.Buffers.Primitives/System/Buffers/ReadOnlyBufferReader.cs#L139

Where `BufferReader<TSequence> bytes` is a large struct that contains a span.

**Comment by jkotas** [comment]
@KrzysztofCwalina Could you please add corefxlab label that these failures were seen on; and build flavor (debug vs. release).

**Comment by KrzysztofCwalina** [comment]
the builds that fail:
Innerloop OSX10.12 Debug Build and Test 
Innerloop OSX10.12 Release Build and Test 

What do you mean by "corefxlab label"? Are you asking for a snapshot  of a branch?

**Comment by jkotas** [comment]
Yes - a commit SHA1 that the failure was seen on.

**Comment by KrzysztofCwalina** [comment]
The commit where we started to seriously using this by-ref struct is 1fecfe73502183562d79aae08e2f2a93371700ea

The failures started to show up after this commit

**Comment by KrzysztofCwalina** [comment]
OK, after many ties (~20 test runs), I caught the failure: https://github.com/dotnet/corefxlab/pull/2084.

**Comment by jkotas** [comment]
```
[xUnit.net 00:00:27.4766390]     System.IO.Pipelines.Tests.ReadableBufferReaderFacts+OwnedMemory.CopyToLargerBufferWorks [FAIL]
09:53:14 [xUnit.net 00:00:27.4793690]       Assert.True() Failure
09:53:14 [xUnit.net 00:00:27.4794840]       Expected: True
09:53:14 [xUnit.net 00:00:27.4795660]       Actual:   False
09:53:14 [xUnit.net 00:00:27.4822220]       Stack Trace:
09:53:14 [xUnit.net 00:00:27.4849140]         /Users/dotnet-bot/j/workspace/dotnet_corefxlab/master/osx10.12_release_prtest/tests/System.Buffers.Primitives.Tests/ReadableBufferReaderFacts.cs(318,0): at System.IO.Pipelines.Tests.ReadableBufferReaderFacts.CopyToLargerBufferWorks()
09:53:14 Failed   System.IO.Pipelines.Tests.ReadableBufferReaderFacts+OwnedMemory.CopyToLargerBufferWorks
09:53:14 Error Message:
09:53:14  Assert.True() Failure
09:53:14 Expected: True
09:53:14 Actual:   False
09:53:14 Stack Trace:
09:53:14    at System.IO.Pipelines.Tests.ReadableBufferReaderFacts.CopyToLargerBufferWorks() in /Users/dotnet-bot/j/workspace/dotnet_corefxlab/master/osx10.12_release_prtest/tests/System.Buffers.Primitives.Tests/ReadableBufferReaderFacts.cs:line 318
09:53:30 [xUnit.net 00:00:42.7659620]   Finished:    System.Buffers.Primitives.Tests
```

**Comment by jkotas** [comment]
Here is standalone reliable repro: 
[Program.txt](https://github.com/dotnet/coreclr/files/1692522/Program.txt)

**Comment by jkotas** [comment]
@kouvel This looks like a bug in FindByRefPointerOffsetsInByRefLikeObject . Could you please take a look?
