### ISSUE TITLE
Interlocked.Exchange<T> is slower than Interlocked.CompareExchange<T>

### ISSUE THREAD

**Issue by roji** [dotnet/coreclr#16051]
See this SO: https://stackoverflow.com/questions/48470081/interlocked-exchange-slower-than-interlocked-compareexchange

Long story short, microbenchmarking `Interlocked.Exchange<T>` against `Interlocked.CompareExchange<T>` shows that the former is quite a bit slower, apparently `CompareExchange<T>` has an optimization that could also be applied to `Exchange<T>`.

The performance difference does not show with other overloads (e.g. `Exchange<T>` vs. `CompareExchange<int>`)

**Comment by mikedn** [comment]
Hmm, `Interlocked.Exchange<T>` should probably be changed to
```C#
[MethodImplAttribute(MethodImplOptions.AggressiveInlining)]
public static T Exchange<T>(ref T location1, T value) where T : class
{
    return Unsafe.As<T>(Exchange(ref Unsafe.As<T, object>(ref location1), (object)value));
}
```
@jkotas ? I doubt that we want to special case `Exchange` in the runtime like we do `CompareExchange`. Quite the opposite I'd say..

**Comment by jkotas** [comment]
Agree. This all predates `ref` returns and `S.R.CS.Unsafe`.

**Comment by benaadams** [comment]
Also remove `COMInterlocked::ExchangeGeneric, FC_TypedByRef location, FC_TypedByRef value`?

**Comment by mikedn** [comment]
Yeah, I'm removing all the gunk.

**Comment by benaadams** [comment]
Value in doing the same with?
`COMInterlocked::CompareExchangeGeneric, FC_TypedByRef location, FC_TypedByRef value, LPVOID comparand)`

**Comment by mikedn** [comment]
> Value in doing the same with?

What exactly does "the same" mean? If you're talking about the solution I mentioned above then I'd avoid doing that in case the JIT's inliner decides to throw a fit. I ended up cleaning up the whole mess. Still waiting for a build to see if it actually works.

**Comment by benaadams** [comment]
> What exactly does "the same" mean?

Aye, dropping 
`void _CompareExchange(TypedReference location1, TypedReference value, Object comparand)` 
and using
`Object CompareExchange(ref Object location1, Object value, Object comparand)`

>  I'd avoid doing that in case the JIT's inliner decides to throw a fit.

Fair enough

**Comment by mikedn** [comment]
Dropping `_CompareExchange` is fine. Dropping the special casing from jitinterface.cpp is a bit more problematic. Ideally the generic method would be an intrinsic and the non-generic one would just use the generic one so no casts are needed.

Unfortunately it seems that the a generic method cannot be an intrinsic. Oh well, back to the drawing board...

**Comment by tannergooding** [comment]
> Unfortunately it seems that the a generic method cannot be an intrinsic

Why can't it? We have a few other intrinsic generics (but they might all be using the "named intrinsic" feature).

**Comment by jkotas** [comment]
FWIW, adding the special casing for `Interlocked.Exchange` to jitinterface.cpp should be fine if it helps.

**Comment by mikedn** [comment]
> FWIW, adding the special casing for Interlocked.Exchange to jitinterface.cpp should be fine if it helps.

Hmm, don't think it's needed, `AggresiveInlining` should do the job well in most cases. It's more of a question if we can remove the jitinterface.cpp special casing for `CompareExchange`. It's probably safer not to.

Also, I'm not sure if we can remove `_Exchange`. At least in theory that would break existing crossgened images that inlined `Exchange<T>`. Though `Exchange<T>` doesn't appear to inline today so perhaps it's fine...

**Comment by jkotas** [comment]
> At least in theory that would break existing crossgened images that inlined `Exchange<T>`

There is no cross-module inlining for the version resilient R2R native images. The internal implementation details like this are fine to change.
