### ISSUE TITLE
SuppressUnmanagedCodeSecurity MIA

### ISSUE THREAD

**Issue by GuardRex** [dotnet/coreclr#1605]
`SuppressUnmanagedCodeSecurity` didn't make it into `System.Security`? My PInvoke's are fully trusted (and speed is important). Is there a workaround for a dnxcore50 app?

![capture](https://cloud.githubusercontent.com/assets/1622880/10037303/d87c5908-6179-11e5-8cee-a8f5ac6c59bc.PNG)

**Comment by morganbr** [comment]
All of the security demand code around P/Invokes is ifdef'd out on CoreCLR. As long as your code calling the P/Invokes is security critical (which it is if you don't have any special attributes), there are no extra security checks in the way of your P/Invoke calls. As a result, no need for that attribute :)

**Comment by nathanaeljones** [comment]
Ugh, so because it's not defined, the rest of the world has to Ifdef  P/Invoke declarations too? 

If people start creating fake shims to avoid this we're going to have some fun symbol collisions.
