### ISSUE TITLE
GC.SuppressFinalize not keeping object alive?

### ISSUE THREAD

**Issue by Alois-xx** [dotnet/coreclr#16053]
I have noticed a sporadic issue inside TraceEvent:

https://github.com/Microsoft/perfview/issues/533

which causes an objects finalizer to run although it is still alive. I have tried to create a repro but failed so far. 
I suspect the missing ingredient might be that Thread::RareDisablePreemptiveGC is called while the unmanaged code is being run. 

```
clr!CLREventBase::Wait+0x1a
clr!WaitForEndOfShutdown_OneIteration+0x81
clr!WaitForEndOfShutdown+0x1b
clr!Thread::RareDisablePreemptiveGC+0x52f
clr!JIT_RareDisableHelper+0x24
DomainNeutralILStubClass.IL_STUB_PInvoke(IntPtr)
DomainNeutralILStubClass.IL_STUB_PInvoke(IntPtr)
System.Runtime.InteropServices.Marshal.FreeHGlobal(IntPtr)(+0xe IL,+0x19 Native)

```

To prove my point I would need some hints how I can get the GC into the state that RareDisablePreemptiveGC is called. I have created some smaller stress application but that method did never break in the debugger. Any hints are appreciated.

**Comment by jkotas** [comment]
> clr!WaitForEndOfShutdown

This means that you are running on .NET Framework and that the runtime is shutting down. All objects are finalized on .NET Framework, even the live ones.

The shutdown finalization is a well source of shutdown crashes. We have disabled it in .NET Core. https://github.com/dotnet/corefx/issues/5205 has all the details about it.

**Comment by Alois-xx** [comment]
Ahh thanks! That explains it. The fix to move GC.SuppressFinalize before the unmanaged call will then reliably fix the issue.
