### ISSUE TITLE
System.Runtime.CompilerServices.UnsafeTests:RefIsAddressGreaterThan test triggers JIT asserts

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#16062]
Repro:

- Run CoreFX tests on checked JIT (e.g. via `corefx_baseline` job)
- The recently added `System.Runtime.CompilerServices.UnsafeTests:RefIsAddressGreaterThan` test fails with: `Assertion failed '!op2->IsCnsIntOrI() || genTypeCanRepresentValue(type, op2->AsIntCon()->IconValue())' in 'System.Runtime.CompilerServices.UnsafeTests:RefIsAddressGreaterThan()'`

**Comment by jkotas** [comment]
@dotnet/jit-contrib

**Comment by mikedn** [comment]
Checking, that's an assert I added...

**Comment by mikedn** [comment]
The funny casting in that test produced the following IR:
```
------------ BB02 [01C..031) -> BB06 (cond), preds={BB01} succs={BB03,BB06}
N001 (  1,  1) [000195] ------------       t195 =    CNS_INT   byref  1 $102
N002 (  1,  1) [000051] ------------        t51 =    CNS_INT   byref  -1 $101
                                                 /--*  t195   byref  
                                                 +--*  t51    byref  
N003 (  3,  3) [000202] N------N-U--       t202 = *  GE        int    $401
                                                 /--*  t202   int    
N004 (  5,  5) [000060] ------------              *  JTRUE     void  
```
`genTypeCanRepresentValue` treats `TYP_BYREF` as `size_t` and `CNS_INT` stores constant values using `ssize_t` so the assert fails when the constant value is negative.

The assert should apply only to small integer types, in that case we emit a byte/word size `cmp` instruction and we need to ensure that the constant fits in a byte/word. I'll send a PR later today to fix this.

That said, that test is kind of bogus as the code it generates has nothing to do with real-world code. The constant refs it generates should be somehow "hidden" from the actual compare operation so you don't end up with a constant compare operation that constant folding or other compiler optimizations may throw away.
