### ISSUE TITLE
ThreadPool.UnsafeQueueUserWorkItem MIA

### ISSUE THREAD

**Issue by GuardRex** [dotnet/coreclr#1607]
I have `ThreadPool.QueueUserWorkItem()`, but I'd prefer to have `ThreadPool.UnsafeQueueUserWorkItem()` ... because I think it's faster, and I have a speed critical dnxcore50 app that I'm working on. Is the unsafe version under consideration?

**Comment by ericeil** [comment]
On CoreCLR, capturing and restoring the ExecutionContext is *much* less costly than the full CLR.  So it's questionable whether UnsafeQueueUserWorkItem would actually benefit much.  If you have profile data showing that this would make a big difference for your app, then we should consider adding this API; otherwise, I'm going to close this for now.

**Comment by GuardRex** [comment]
This would be for a web server I'm working on, so yes, spawning many thousands of threads per second without capturing the `ExecutionContext` should matter. A few microseconds per thread is going to mushroom-cloud into poor performance under load. I'll try and profile with and without via the full CLR and report back.

**Comment by ericeil** [comment]
A profile from the full CLR may not help much, as the vast majority of the ExecutionContext costs on the CLR don't apply on CoreCLR (which has a completely different ExecutionContext implementation).

If you can profile on CoreCLR, with QueueUserWorkItem, and show that ExecutionContext is a significant contributor to overall run time, then we'll have something to work with.

**Comment by GuardRex** [comment]
If I don't have `UnsafeQueueUserWorkItem`, how would I do that? ... Are you saying I can pull it out of Reference Source and place it into my project to perform the profiling?

**Comment by GuardRex** [comment]
I think I see what you mean ... just find out `QueueUserWorkItem`'s hit within the overall scope of processing. Ok ... that I can do.

**Comment by ericeil** [comment]
What I meant was to try it with just the existing QueueUserWorkItem, and use your profiler to find how much CPU time was used by ExecutionContext code.
