### ISSUE TITLE
x86 JIT produces non-optimal codegen when working with ByReference<T> instances

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/coreclr#16082]
The high-level summary is that I have two nearly identical methods: one which takes its parameters as `byte*`, the other which takes its parameters as `ByReference<byte>`. x86 RyuJIT seems to be producing non-optimal codegen in the code paths that operate on the `ByReference<T>`. For example, there's extra register shuffling here that doesn't occur in the `byte*`-based code paths. x64 RyuJIT does the right thing by producing identical (seemingly optimal) codegen for both scenarios.

See https://github.com/dotnet/coreclr/pull/15947#issuecomment-360660892 for full context.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by GrabYourPitchforks** [comment]
If there are no complaints, I'm going to close this. The introduction of reassignable ref locals means that we no longer rely on passing `ByReference<T>` through the ABI.
