### ISSUE TITLE
Add tests to the lstFile so they can be run in automation.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#16113]
As per the comment from @jashook here: https://github.com/dotnet/coreclr/pull/15771#pullrequestreview-92768110

**Comment by tannergooding** [comment]
FYI. @jashook, @CarolEidt.

It sounds like this might be a more general work item, rather than specific to just the hardware intrinsics.

**Comment by jashook** [comment]
Correct assigned to myself, thanks for opening

**Comment by jashook** [comment]
Lst files are no longer supported.
