### ISSUE TITLE
[Test Failure] JIT.Performance.CodeQuality.Span.SpanBench.SpanBench

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#16134]
This is currently failing in x64 Ubuntu stress runs with a MissingMethodException.

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_jitx86hwintrinsicnoavx2_tst_prtest/32/testReport/JIT.Performance.CodeQuality.Span/SpanBench/SpanBench/

**Comment by tannergooding** [comment]
@jkotas, @ianhays. Looks related to https://github.com/dotnet/coreclr/pull/15941

**Comment by jkotas** [comment]
Failures like these are expected as breaking changes propagate through the system. The JIT corefx legs are not robust against them. https://github.com/dotnet/coreclr/issues/12782#issuecomment-348636757 describes about what it would take to fix it.

**Comment by tannergooding** [comment]
It would seem like disabling the tests, with a tracking issue, and re-enabling them after the changes pump back might be appropriate, so that CI doesn't turn up red for known breaks.

**Comment by jkotas** [comment]
I do not think there is a reasonable way to disable these tests. The tests are fixed in master as of https://github.com/dotnet/coreclr/commit/93ec62347a4e97b920513296eefb27bdacbecfe9 . These systems just pick up stale bits in various ways.

**Comment by tannergooding** [comment]
> I do not think there is a reasonable way to disable these tests.

Why can't we just add them to the `tests\issues.targets` and `tests\testsFailingOutsideWindows.txt`. That seemed to be sufficient for the HWIntrinsic API tests that where failing due to similar naming changes (I think the difference is that the HWIntrinsic tests are part of the inner loop, while this one seems to be part of the outer loop).

**Comment by jkotas** [comment]
I believe that by the time you do that and it propagates through the system, the fixed tests will propagate through the system as well so it won't be necessary.

**Comment by jkotas** [comment]
@RussKeldorph @BruceForstall

**Comment by BruceForstall** [comment]
@tannergooding fyi, looks like these are passing now, e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_jitx86hwintrinsicnoavx2_tst/

IMO, we need to have CoreCLR-side "breaking changes" trigger a larger test run than the usual "innerloop" one, and disable tests where they can be disabled. These failures weren't in the "corefx" jobs, which are more problematic (I don't think we have an easy way to disable those).
