### ISSUE TITLE
x86: HardwareIntrinsics tests fail with JitStressRegs=4

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#16132]
These tests are failing in the JIT\HardwareIntrinsics\X86\Sse directory:
CompareGreaterThan_r
CompareGreaterThanOrEqual_r
CompareLessThan_r
CompareLessThanOrEqual_r
CompareNotGreaterThan_r
CompareNotGreaterThanOrEqual_r
CompareNotLessThan_r
CompareNotLessThanOrEqual_r
CompareOrdered_r
CompareUnordered_r
Reciprocal_r
Reciprocal_ro
ReciprocalSqrt_r
ReciprocalSqrt_ro

**Comment by CarolEidt** [comment]
These pass with `COMPlus_EnableAVX=0` (hence an AVX-capable system is necessary to repro)

**Comment by CarolEidt** [comment]
They also fail on Ubuntu/x64 with JitStressRegs=4. This is an ABI-related stress mode (reverse caller-callee), so perhaps it is not surprising.

**Comment by tannergooding** [comment]
@CarolEidt, is it interesting that most of these only fail for the non-optimized version, or is that expected since unnecessary stores won't get folded?

**Comment by CarolEidt** [comment]
> is it interesting that most of these only fail for the non-optimized version, or is that expected since unnecessary stores won't get folded?

I haven't looked into it, but that may be the case. However, given that it's only the "reverse caller-callee" mode I'm not sure.

**Comment by CarolEidt** [comment]
At least some instances of the reciprocal failures are due to encoding issues:
Reciprocal_r
Reciprocal_ro
ReciprocalSqrt_r
ReciprocalSqrt_ro
Filed new issue #16135

**Comment by tannergooding** [comment]
Something looks to be wrong with the encoding for `CompareGreaterThan` as well.

JitDisasm reports:
`vcmpps xmm6, xmm7, xmmword ptr [ebp-64H], 6`

But that is actually:
`vcmpps xmm6, xmm6, xmmword ptr [ebp-0x64], 6`

**Comment by tannergooding** [comment]
I see the problem, will have a fix up shortly.

**Comment by CarolEidt** [comment]
> I see the problem, will have a fix up shortly.

Awesome, thanks!

**Comment by tannergooding** [comment]
https://github.com/dotnet/coreclr/pull/16140

**Comment by CarolEidt** [comment]
Fixed by #16140
