### ISSUE TITLE
[Test Failure] the `Sse2.MultiplyLow` test fails for some inputs.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#16153]
See https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitx86hwintrinsicnoavx_prtest/56/, for an example.

**Comment by tannergooding** [comment]
FYI. @4creators

**Comment by tannergooding** [comment]
In the validation logic the test is doing:
```C#
CheckMethod<short> checkInt16 = (short x, short y, short z, ref short a) =>
{
    var tmp = ((int)x * y) * 0x0000ffff;
    a = unchecked((short)tmp);
    return -a == z;
};
```

@4creators, could you explain the reasoning behind the `* 0x0000ffff`?

The architecture manual indicates the logic is simply:
![image](https://user-images.githubusercontent.com/10487869/35694031-daf01cb6-0734-11e8-9ef2-abdc188ba8c6.png)

So I would think we just want to do:
```
var expectedResult = unchecked((short)((int)(x) * (int)(y)));
return expectedResult == z;
```

**Comment by 4creators** [comment]
> could you explain the reasoning behind the * 0x0000ffff?

Typo - should be `& 0x0000ffff` - unlucky that it worked for same values though - preparing fix

**Comment by tannergooding** [comment]
>should be & 0x0000ffff

The `unchecked((short)(tmp))` should handle that

What about the logic for `-a == z;`? (not sure why `a` is being negated).

**Comment by 4creators** [comment]
> What about the logic for -a == z;? (not sure why a is being negated).

Suspect that it could be merge problem during rebasing - I have started with > 50 commits before rebasing first to 5 and finally to 1 commit

**Comment by CarolEidt** [comment]
@tannergooding @fiigii @4creators - The fact that this test was exhibiting non-deterministic behavior is problematic. I believe that it is still the plan to change the Sse2 tests to use the new templates, but if that's not happening soon, we should change TestTableSse2.cs to *not* use `DateTime.UtcNow.Ticks` as an argument to `Random`.

**Comment by tannergooding** [comment]
> The fact that this test was exhibiting non-deterministic behavior is problematic.

Agreed.

> I believe that it is still the plan to change the Sse2 tests to use the new templates, but if that's not happening soon

I was planning on moving most of the tests over after https://github.com/dotnet/coreclr/pull/16095 goes in.

Then I was going to work on adding templates for testing commutative operations and containment tests for `LoadScalar`

**Comment by CarolEidt** [comment]
Thanks @tannergooding!

**Comment by 4creators** [comment]
@CarolEidt  @tannergooding In such case I will speed up test conversion to common template and fix 

> TestTableSse2.cs to not use DateTime.UtcNow.Ticks as an argument to Random

**Comment by 4creators** [comment]
@tannergooding Which part of test should I port to common template?

**Comment by tannergooding** [comment]
>  In such case I will speed up test conversion to common template and fix

I was explicitly waiting on #16095 in order to help prevent merge conflicts and to reduce the total number of changes, since it updates the tests to include additional scenarios.

> Which part of tests should I port to common template?

All of it. The only thing the Sse2 tests are doing that the template is not is validating loops, which I was going to update the template to cover (one commit moves the tests over to the template, a second commit updates the template to test loops and regenerates all the tests).

**Comment by 4creators** [comment]
OK than I will start work once #16095 will be in except for parts which do not have to wait.

**Comment by tannergooding** [comment]
> OK than I will start work once #16095 will be in except for parts which do not have to wait.

I already have part of this done locally (on top of my existing changes), so that might just end up duplicating work.

It would be beneficial to have any new tests using the template from the get-go (if you plan on resolving the merge conflicts and continuing with https://github.com/dotnet/coreclr/pull/15777, for example).
