### ISSUE TITLE
TypeLoadException .net core 2.0

### ISSUE THREAD

**Issue by nim** [dotnet/coreclr#16188]
I have Exception than i try use this struct

```
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    struct LinkStruct
    {
        public LinkStruct? Chield { get; set; } 
    }
```

**Comment by stephentoub** [comment]
That won't compile. The C# compiler error tells you why:
```
Struct member 'Program.LinkStruct.Chield' of type 'Program.LinkStruct?' causes a cycle in the struct layout
```
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0523

**Comment by nim** [comment]
It a bug, this nullable type. I have compiled but i got runtime error.

**Comment by mikedn** [comment]
This sounds like the reference assembly bug with structs missing their fields that allowed invalid code to compile. Anyway, compiled or not the code is not valid, a struct cannot contain itself.

**Comment by jkotas** [comment]
The issue with reference assemblies was fixed recently: https://github.com/dotnet/corefx/issues/6185
