### ISSUE TITLE
Extra allocation in corner cases CombineNoChecks(ReadOnlySpan<char> first, ReadOnlySpan<char> second)

### ISSUE THREAD

**Issue by Anipik** [dotnet/coreclr#16195]
We changed the string version of CombineNoChecks to a span version which introduced new allocations in corner cases like 

```
CombineNoChecks("foo", "");
```
which was not the case earlier.
My suggestion to solve this issue is to keep the basic corner checks in the string overload, instead of completely removing the string overload.

CC: @JeremyKuhne @danmosemsft

**Comment by JeremyKuhne** [comment]
> My suggestion to solve this issue is to keep the basic corner checks in the string overload, instead of completely removing the string overload.

Sounds good.
