### ISSUE TITLE
Do interface casts to access methods elide the virtual dispatch?

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#16198]
e.g.
```csharp
((IHttpRequestFeature)this).Method = RequestHeaders[":method"];
```
Does it just change the method called; or does it cause an interface dispatch, so a second hidden method is required
```csharp
private string MethodForInterface { get; set; }
string IHttpRequestFeature.Method
{
    get => MethodForInterface;
    set => MethodForInterface = value;
} 
```
```csharp
MethodForInterface = RequestHeaders[":method"];
```

from  https://github.com/aspnet/KestrelHttpServer/pull/2294

/cc @AndyAyersMS

**Comment by benaadams** [comment]
```csharp
public interface IMethod
{
 	int Value { get; }    
}

public class C : IMethod {
    
    int IMethod.Value => 5;
    
    public int M() 
    {
        return ((IMethod)this).Value;
    }
}
```
[sharplab.io](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQBEJinANjASQDsYIFsBjCAgWwAdcIaITYBLAeyIBoYQpkNAD4ABAAwACEQEYA3AFgAUCIDMEtiTKUIEggFkIMABYcAJkoDeSiQEgNMCQDUouODosSA5odkSAvhKBEkp+SkqqUgBMEgDCEiC6BsZmElaKQcHpQfaJhiamAHTOrjoAvAB8EgCsClmB1kEROXoAFACUmRlpGRkiAOwSLS36eWZtxmzIbUUubrUZoYp+QA==) would suggest not
```asm
; Desktop CLR v4.7.2558.00 (clr.dll) on x86.

C..ctor()
    L0000: ret

C.IMethod.get_Value()
    L0000: mov eax, 0x5
    L0005: ret

C.M()
    L0000: push ebp
    L0001: mov ebp, esp
    L0003: call dword [0x1eff0070]
    L0009: pop ebp
    L000a: ret
```

**Comment by AndyAyersMS** [comment]
I may be missing the point here, but no, we don't devirtualize:
```
impDevirtualizeCall: Trying to devirtualize interface call:
    class for 'this' is C (attrib 20000000)
    base method is IMethod::get_Value
--- base class is interface
    devirt to C::IMethod.get_Value -- final method
               [000002] --C-G-------              *  CALLV stub int    IMethod.get_Value
               [000001] ------------ this in rcx  \--*  LCL_VAR   ref    V00 this         
    Class not final or exact for interface, no devirtualization
```
In your example above the jit could take advantage of the fact that in a constructor the exact type of `this` is known, and so it could devirtualize. Might be worth looking at further.

**Comment by benaadams** [comment]
> I may be missing the point here, 

There are some times you want to use the interface to access the explicitly implemented methods/properties, so its just accessing a different view of methods rather than as an interface.

Kinda like how a constrained generic is a call via the interface, but still a direct call.

So for example if you had a dictionary but wanted to call the 
`Contains(KeyValuePair<TKey, TValue> keyValuePair)` 
method you'd first have to cast it to the interface that implemented it as its not directly implemented on dictionary e.g.
```csharp
if (((ICollection<KeyValuePair<int, string>>)dict).Contains(KeyValuePair<int, string> (5, "hello")))
{
    // ...
}
```

**Comment by benaadams** [comment]
Ah, basically they act as virtual calls regardless as they can be reimplemented. Makes sense.

Thank you

**Comment by benaadams** [comment]
As a follow up... if the class was sealed would that make a difference? (as the interface site couldn't be reimplemented)
