### ISSUE TITLE
Span<> performance and generated code

### ISSUE THREAD

**Issue by alexandrnikitin** [dotnet/coreclr#16197]
I've been playing with `Span<>` feature and notice that its performance is relatively slower and the generated assembly code looks bulky. 

I'm comparing an array on heap `new int[];`, unsafe stack allocated array `stackalloc int[16];`, stack allocated Span `Span<int> x1 = stackalloc int[16];`, span with stack allocated buffer `new Span<int>(buffer, 16);`. [The code can be found here.](https://github.com/alexandrnikitin/SpanBenchmark/blob/27e463348a0bbad147701ab5367b5763b3aeba87/SpanTest/SpanBenchmarks.cs) Stack allocated Span is almost 3 times slower than unsafe stack allocated array. I have  .NET Core `2.1.0-preview2-26130-06` but also tried `2.0.x` with `System.Memory` package from MyGet. You can find the repro code is in this repository: https://github.com/alexandrnikitin/SpanBenchmark.

Basically my question is: What am I doing wrong? Or these results are expected?

The results I get:

``` ini

BenchmarkDotNet=v0.10.12, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.192)
Intel Core i7-4600U CPU 2.10GHz (Haswell), 1 CPU, 4 logical cores and 2 physical cores
Frequency=2630627 Hz, Resolution=380.1375 ns, Timer=TSC
.NET Core SDK=2.1.300-preview2-008042
  [Host] : .NET Core 2.1.0-preview2-26130-06 (Framework 4.6.26130.05), 64bit RyuJIT
  Core   : .NET Core 2.1.0-preview2-26130-06 (Framework 4.6.26130.05), 64bit RyuJIT

Job=Core  Runtime=Core  

```
|              Method |     Mean |     Error |    StdDev | Scaled |
|-------------------- |---------:|----------:|----------:|-------:|
|      ArrayBenchmark | 17.73 ns | 0.1007 ns | 0.0893 ns |   1.00 |
|     UnsafeBenchmark | 10.68 ns | 0.1037 ns | 0.0970 ns |   0.60 |
|       SpanBenchmark | 28.25 ns | 0.2521 ns | 0.2358 ns |   1.59 |
| SpanUnsafeBenchmark | 18.54 ns | 0.0563 ns | 0.0373 ns |   1.05 |

The assembly code Span generates:

```asm

00007ffc`fe39eaf0 SpanTest.SpanBenchmarks.SpanBenchmark()	
            Span x1 = stackalloc int[16];
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00007ffc`fe39eb22 b804000000      mov     eax,4
00007ffc`fe39eb27 6a00            push    0
00007ffc`fe39eb29 6a00            push    0
00007ffc`fe39eb2b 48ffc8          dec     rax
00007ffc`fe39eb2e 75f7            jne     00007ffc`fe39eb27
00007ffc`fe39eb30 488d0424        lea     rax,[rsp]
00007ffc`fe39eb34 48896538        mov     qword ptr [rbp+38h],rsp
00007ffc`fe39eb38 33d2            xor     edx,edx
00007ffc`fe39eb3a 48895510        mov     qword ptr [rbp+10h],rdx
00007ffc`fe39eb3e 48894510        mov     qword ptr [rbp+10h],rax
00007ffc`fe39eb42 488b4510        mov     rax,qword ptr [rbp+10h]
00007ffc`fe39eb46 488d5518        lea     rdx,[rbp+18h]
00007ffc`fe39eb4a 488902          mov     qword ptr [rdx],rax
00007ffc`fe39eb4d c7452010000000  mov     dword ptr [rbp+20h],10h
            var sum = 0;
            ^^^^^^^^^^^^
00007ffc`fe39eb54 c4e17a6f4518    vmovdqu xmm0,xmmword ptr [rbp+18h]
00007ffc`fe39eb5a c4e17a7f4528    vmovdqu xmmword ptr [rbp+28h],xmm0
00007ffc`fe39eb60 33c0            xor     eax,eax
            for (int i = 0; i < x1.Length; i++)
                 ^^^^^^^^^
00007ffc`fe39eb62 33d2            xor     edx,edx
00007ffc`fe39eb64 8b4d30          mov     ecx,dword ptr [rbp+30h]
00007ffc`fe39eb67 85c9            test    ecx,ecx
00007ffc`fe39eb69 7e11            jle     00007ffc`fe39eb7c
                sum += x1[i];
                ^^^^^^^^^^^^^
00007ffc`fe39eb6b 4c8b4528        mov     r8,qword ptr [rbp+28h]
00007ffc`fe39eb6f 4c63ca          movsxd  r9,edx
00007ffc`fe39eb72 43030488        add     eax,dword ptr [r8+r9*4]
            for (int i = 0; i < x1.Length; i++)
                                           ^^^
00007ffc`fe39eb76 ffc2            inc     edx
00007ffc`fe39eb78 3bd1            cmp     edx,ecx
00007ffc`fe39eb7a 7cef            jl      00007ffc`fe39eb6b
            return sum;
            ^^^^^^^^^^^
00007ffc`fe39eb7c 48b9c368fccd3f200000 mov rcx,203FCDFC68C3h
 ```

Compared to unsafe stack allocation:

```asm


00007ffc`fe3aeb50 SpanTest.SpanBenchmarks.UnsafeBenchmark()	
            int* x1 = stackalloc int[16];
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00007ffc`fe3aeb74 b804000000      mov     eax,4
00007ffc`fe3aeb79 6a00            push    0
00007ffc`fe3aeb7b 6a00            push    0
00007ffc`fe3aeb7d 48ffc8          dec     rax
00007ffc`fe3aeb80 75f7            jne     00007ffc`fe3aeb79
00007ffc`fe3aeb82 488d0424        lea     rax,[rsp]
00007ffc`fe3aeb86 48896508        mov     qword ptr [rbp+8],rsp
            var sum = 0;
            ^^^^^^^^^^^^
00007ffc`fe3aeb8a 33d2            xor     edx,edx
            for (int i = 0; i < 16; i++)
                 ^^^^^^^^^
00007ffc`fe3aeb8c 33c9            xor     ecx,ecx
                sum += x1[i];
                ^^^^^^^^^^^^^
00007ffc`fe3aeb8e 4c63c1          movsxd  r8,ecx
00007ffc`fe3aeb91 42031480        add     edx,dword ptr [rax+r8*4]
            for (int i = 0; i < 16; i++)
                                    ^^^
00007ffc`fe3aeb95 ffc1            inc     ecx
            for (int i = 0; i < 16; i++)
                            ^^^^^^
00007ffc`fe3aeb97 83f910          cmp     ecx,10h
00007ffc`fe3aeb9a 7cf2            jl      00007ffc`fe3aeb8e
            return sum;
            ^^^^^^^^^^^
00007ffc`fe3aeb9c 8bc2            mov     eax,edx

```

**Comment by benaadams** [comment]
Wouldn't like make a huge difference, but you might want to have length as your loop condition for span and array
```csharp
for (int i = 0; i < x1.Length; i++)
```

**Comment by AndyAyersMS** [comment]
Thanks for the report -- looks like a couple of issues we'll have to investigate further:
* spans are not getting register promoted
* bounds check is not getting eliminated 
* initial span construction overhead seems pretty high (and there is a copy)

Because spans refer to their array payloads while arrays contain them, the jit has to be fairly aggressive about loading the span fields into registers to get array-like codegen. Something is preventing that here.

The other issues are likely related -- if we can promote the spans then they should improve too. So that's the first thing to look at.

**Comment by alexandrnikitin** [comment]
@benaadams My bad, I've lost those while porting the code. It doesn't change much, range checks are still there. Anyway I updated the code and the original post. I also added one of the real-world cases with more work to illustrate the difference [here](https://github.com/alexandrnikitin/SpanBenchmark/tree/master/SpanTest/RealWorldCases).

@AndyAyersMS I'm happy to close this if those issues are already tracked somewhere.

**Comment by AndyAyersMS** [comment]
Had a bit of time to drill in.

The issue here is that `stackalloc` triggers the jit to generate a stack guard, since it opens the possibility that buggy user code could corrupt the stack. And when the jit decides to generate a stack guard it disables all struct promotion.

This is unfortunate since wrapping a stackalloc in a span should help ensure safe access to the stack buffer (unlike raw pointer math).

You can simulate what the codegen would be like if the jit wasn't quite so worried about stack corruption by splitting the method in two so that the stack allocation happens in an outer method and the loop in an inner (noinline) method.

But such contortions shouldn't be needed. This looks like something we should fix. I'll see if we can get it done in time for 2.1.

**Comment by davidfowl** [comment]
We should make sure that this doesn't affect places in existing code where we stackalloc in case we don't get this fixed for 2.1 (I believe in you @AndyAyersMS  😄 )

/cc @jkotas @KrzysztofCwalina @ahsonkhan @GrabYourPitchforks @stephentoub

**Comment by ahsonkhan** [comment]
> You can simulate what the codegen would be like if the jit wasn't quite so worried about stack corruption by splitting the method in two so that the stack allocation happens in an outer method and the loop in an inner (noinline) method.

Would this apply to the places below marked as (A)?

Here are a few places we use stackalloc span, to showcase how it is being used:
**CoreClr:**
https://github.com/dotnet/coreclr/blob/c0fe49b36a9556506f2b13e553a17c9f6c5531b4/src/mscorlib/src/System/Environment.Windows.cs#L16

(A) https://github.com/dotnet/coreclr/blob/c247f5bffa563820fe8db6fa14b42024c57c540f/src/mscorlib/src/System/Environment.cs#L496

- https://github.com/dotnet/corefx/blob/103639b6ff5aa6ab6097f70732530e411817f09b/src/Common/src/CoreLib/System/ParseNumbers.cs#L221
-  https://github.com/dotnet/corefx/blob/103639b6ff5aa6ab6097f70732530e411817f09b/src/Common/src/CoreLib/System/Guid.cs#L607
-  https://github.com/dotnet/corefx/blob/103639b6ff5aa6ab6097f70732530e411817f09b/src/Common/src/CoreLib/System/Globalization/CultureData.cs#L639

**Corefx:**

- (A) https://github.com/dotnet/corefx/blob/a7f6f470cb2c4cdaafdc3ad85e2520992a8db265/src/Common/src/System/Net/Internals/IPAddressExtensions.cs#L21
- https://github.com/dotnet/corefx/blob/0af4e15eb108261244182b79b6a42f0cf82e961e/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/PkcsPal.AnyOS.cs#L58
- https://github.com/dotnet/corefx/blob/eb0d4388c339288a589bdd7f5e0c9fcd61da4362/src/System.IO.FileSystem/src/System/IO/DosMatcher.cs#L29
- (A) https://github.com/dotnet/corefx/blob/a7f6f470cb2c4cdaafdc3ad85e2520992a8db265/src/Common/src/System/Net/SocketAddress.cs#L106
- https://github.com/dotnet/corefx/blob/2b4664a53d8a5729343f056ffa82ff5cb4d32d40/src/System.Net.Http/src/System/Net/Http/Managed/AuthenticationHelper.Digest.cs#L220
- (A) https://github.com/dotnet/corefx/blob/17be4bc9b3fd9443026d2bf7d11a043b940bbcf4/src/System.Runtime.Extensions/src/System/Environment.Windows.cs#L154
- https://github.com/dotnet/corefx/blob/6c50a9e705800bbc5d166c91aa2c7e2a85b2325b/src/Common/src/Interop/FreeBSD/Interop.Process.cs#L228
- https://github.com/dotnet/corefx/blob/a8011033db2d22114dd27a8b8d149ad3b759ecc9/src/System.Net.Primitives/src/System/Net/IPAddress.cs#L611
- (A) https://github.com/dotnet/corefx/blob/c47edd1c8a3e561e5081e966b0d270fa2b345f05/src/System.Runtime.Numerics/src/System/Numerics/BigNumber.cs#L512
- https://github.com/dotnet/corefx/blob/0af4e15eb108261244182b79b6a42f0cf82e961e/src/Common/src/System/Security/Cryptography/AsnWriter.cs#L589
- https://github.com/dotnet/corefx/blob/f965141b767517d465c03b899dc87b2e52d2e6fc/src/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/Windows/HelpersWindows.cs#L340
- (A) https://github.com/dotnet/corefx/blob/0af4e15eb108261244182b79b6a42f0cf82e961e/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs#L551
- https://github.com/dotnet/corefx/blob/40cbd5636851093309b841db4d53af369b7ef1c6/src/Common/src/System/Security/Cryptography/AsnReader.cs#L1119

**Comment by danmosemsft** [comment]
When fixing this seasrch for 16197 in the code to reverse workarounds.

**Comment by AndyAyersMS** [comment]
After enabling register promotion in frames with stackalloc, we get the following. As hoped, the jit cleans up the inner loop:
```
G_M35366_IG04:
       4C63C1               movsxd   r8, ecx
       42031480             add      edx, dword ptr [rax+4*r8]
       FFC1                 inc      ecx
       83F910               cmp      ecx, 16
       7CF2                 jl       SHORT G_M35366_IG04
```
Basically the same codegen as in the array case. Same goes with the `SpanUnsafeBenchmark`. So this is clearly a desirable way to go as it doesn't require any clever analysis and can handle most any pattern.

Looking at diffs more broadly it also seems to be an improvement, both in terms of CQ and in terms of actual protection.

So I need to figure out what the original reason was for blocking promotion. RyuJit's logic here can be traced back to Jit32....maybe I can dig something out there.

**Comment by AndyAyersMS** [comment]
Looked back in source control history to the point where this struct promotion was introduced in Jit32 and it was this way from the start -- have not found any specific reason why promotion was disabled when a method has GS. 

Local testing looks ok and codegen looks good too. So have put up a PR and started some broader testing.

**Comment by alexandrnikitin** [comment]
Just to confirm, I've installed the latest `2.1.0-preview2-26308-01` CLR build and the issue is fixed. It's time to switch 😄  Thank you!!

The results from the above benchmark:

```
BenchmarkDotNet=v0.10.12, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.248)
Intel Core i7-4600U CPU 2.10GHz (Haswell), 1 CPU, 4 logical cores and 2 physical cores
Frequency=2630632 Hz, Resolution=380.1368 ns, Timer=TSC
.NET Core SDK=2.1.300-preview2-008316
  [Host] : .NET Core 2.1.0-preview2-26308-01 (Framework 4.6.26307.01), 64bit RyuJIT
  Core   : .NET Core 2.1.0-preview2-26308-01 (Framework 4.6.26307.01), 64bit RyuJIT

Job=Core  Runtime=Core

              Method |     Mean |     Error |    StdDev | Scaled |
-------------------- |---------:|----------:|----------:|-------:|
      ArrayBenchmark | 17.00 ns | 0.1170 ns | 0.1037 ns |   1.00 |
     UnsafeBenchmark | 12.03 ns | 0.0778 ns | 0.0728 ns |   0.71 |
       SpanBenchmark | 12.16 ns | 0.2008 ns | 0.1878 ns |   0.72 |
 SpanUnsafeBenchmark | 12.12 ns | 0.2083 ns | 0.1948 ns |   0.71 |
```

**Comment by KrzysztofCwalina** [comment]
@AndyAyersMS great thanks for the fix! @alexandrnikitin, thanks for bringing this issue to our attention!
