### ISSUE TITLE
Preserve Stack Trace when rethrowing Exception

### ISSUE THREAD

**Issue by fujiy** [dotnet/coreclr#16209]
Based on this issue https://github.com/dotnet/coreclr/issues/8521.

Is it possible to change the CRL behavior, to include the original line number in Stack Trace, like the ExceptionDispatchInfo.Capture(ex).Throw() does?

@mikedn, @danmosemsft, @saxenark

Thanks

**Comment by danmosemsft** [comment]
@fujiy this is also covered by https://github.com/dotnet/coreclr/issues/15780. Folks there seemed OK with replacing the line of the throw; with the line of where it was thrown. It just needs someone to do the work. Any interest in taking a look?

**Comment by fujiy** [comment]
It seems interesting, but I have zero C/C++ knowledge :(
I'll discuss with some colleagues who could be interested.

I think we can close this issue as a duplicate and continue in https://github.com/dotnet/coreclr/issues/15780

**Comment by danmosemsft** [comment]
Sure. OK. BTW, it might not need writing much C++, just finding the right place to tweak.
