### ISSUE TITLE
Assertion failed 'callerArgNum < comp->info.compArgsCount'

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#16201]
Hit by CoreFX test when run on checked CoreCLR:

12:53:40   Assert failure(PID 4908 [0x0000132c], Thread: 3784 [0x0ec8]): Assertion failed 'callerArgNum < comp->info.compArgsCount' in 'System.Configuration.Internal.DelegatingConfigHost:VerifyDefinitionAllowed(ref,int,int,ref):this' (IL size 17)

**Comment by jkotas** [comment]
cc @dotnet/jit-contrib

**Comment by briansull** [comment]
Desktop also hits this when ngen-ing System.dll:

Assert failure(PID 27616 [0x00006be0], Thread: 11336 [0x2c48]): Assertion failed 'callerArgNum < comp->info.compArgsCount' in 'ClientSettingsConfigurationHost:InitForConfiguration(byref,byref,byref,ref,ref):this' (IL size 133)

**Comment by briansull** [comment]
Assert occurs when lowering a FastTailCall:

```
05 000000da`85b8b270 00007ff9`71903969 clrjit!noWayAssertBodyConditional+0x40 [d:\codegenmirror\src\ndp\clr\src\jit\error.cpp @ 517] 
06 000000da`85b8b2a0 00007ff9`7190262b clrjit!Lowering::LowerFastTailCall+0x28d [d:\codegenmirror\src\ndp\clr\src\jit\lower.cpp @ 2117] 
07 000000da`85b8b3b0 00007ff9`71904374 clrjit!Lowering::LowerCall+0x1c7 [d:\codegenmirror\src\ndp\clr\src\jit\lower.cpp @ 1734] 
08 000000da`85b8b450 00007ff9`7190242a clrjit!Lowering::LowerNode+0x510 [d:\codegenmirror\src\ndp\clr\src\jit\lower.cpp @ 170] 
09 000000da`85b8b4d0 00007ff9`719007ec clrjit!Lowering::LowerBlock+0x92 [d:\codegenmirror\src\ndp\clr\src\jit\lower.cpp @ 5476] 
0a 000000da`85b8b500 00007ff9`717edece clrjit!Lowering::DoPhase+0x4c [d:\codegenmirror\src\ndp\clr\src\jit\lower.cpp @ 5286] 
0b 000000da`85b8b530 00007ff9`717f19e9 clrjit!Phase::Run+0x3e [d:\codegenmirror\src\ndp\clr\src\jit\phase.h @ 32] 

```

**Comment by sandreenko** [comment]
I recently have changed number of arguments for VSD #15910, maybe it is connected.

**Comment by briansull** [comment]
PR #16218 was committed and that should fix this problem.

**Comment by briansull** [comment]
@jkotas we canclose this issue if  CoreFX testing is now green.
