### ISSUE TITLE
[RyuJIT] Update emitIns_R_AR to support SSE4.1 instructions without VEX-encoding 

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#16216]
The SSE4.1 instruction `movntdqa` (used by HW intrinsic `LoadAlignedVector128NonTemporal`) can be correctly generated with  VEX-encoding. 
However, with legacy SSE encoding, RyuJIT compiles `movntdqa  xmm0, xmmword ptr [rdi]` to 
```
66 0F 38 2F
```
and the correct encoding should be
```
66 0f 38 2a 07
```

cc @CarolEidt @tannergooding

**Comment by tannergooding** [comment]
This is basically a subset of https://github.com/dotnet/coreclr/issues/15908

**Comment by tannergooding** [comment]
Self assigning. I had already investigated and done a partial fix for this as part of #15908

**Comment by tannergooding** [comment]
This should be done. There is still a remaining issue but that is being tracked seperately: https://github.com/dotnet/coreclr/issues/16296
