### ISSUE TITLE
Invalid x64 codegen with fixed statement and struct

### ISSUE THREAD

**Issue by xoofx** [dotnet/coreclr#16210]
Hey,

I found an invalid codegen (both hitting CoreCLR and .NET Framework).  For CoreCLR, I'm testing it with netcoreapp2.0 (my current dotnet version is 2.1.4)

This is the offending code (make sure to compile it with unsafe and x64):

```
using System;

namespace TestBugFixedStruct
{
    public struct float4
    {
        public float4(float x, float y, float z, float w)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.w = w;
        }


        public float x;
        public float y;
        public float z;
        public float w;

        public unsafe float this[int index]
        {
            get
            {
                fixed (float* array = &x) { return array[index]; }
            }
            set
            {
                fixed (float* array = &x) { array[index] = value; }
            }
        }
    }


    class Program
    {
        public static float Process(int i)
        {
            var test = new float4(5, 4, 3, 2);
            return test[i];
        }

        static void Main(string[] args)
        {
            var method = typeof(Program).GetMethod("Process");
            for (int i = 0; i < 4; i++)
            {
                Console.WriteLine($"Result: {method.Invoke(null, new object[] { i })}");
            }
        }
    }
}
```
It should print: 

``` 
Result: 5
Result: 4
Result: 3
Result: 2
```
but instead it prints garbage like this (for index > 0)

```
Result: 5
Result: 0.08975968
Result: 1.905766E-43
Result: -1.469787E-33
```
Looking at the memory, it seems that the index calculation is correct, but the constructor on the stack (`new float4(5,4,3,2)`) is getting corrupted/or partial (haven't followed exactly what is happening in the details). Only the value `5` is correctly layout in memory, but not the following values.

If I change the body of the indexer to something less efficient (like `if index == 0 return x;`...etc.) it is working. I don't mean that it is the offending part. It looks more like the conjunction of the two (constructor and indexer) getting squashed in the codegen.

Let me know if you need more details.

**Comment by tannergooding** [comment]
Does this still fail if you do `fixed(float4* pThis = &this) { return (float*)(pThis)[index]; }`?

**Comment by mikedn** [comment]
Looks like the JIT failed to notice that the address of the variable was taken and managed to promote the struct to independent local variables. The net result is that the initialization of `y`, `z` and `w` was dropped.

**Comment by mikedn** [comment]
Hmm, not clear if this is really a bug. 

It might be because in some cases the JIT manages to do the "right" thing - it detects that the field address is used to access memory other than the field itself and promotes the struct to dependent lclvars. But this detection is limited and fails if the address ends up in a lclvar which is basically what happens here.

It's simpler to observe the issue if inlining isn't dragged into the picture:
```C#
var test = new float4(5, 4, 3, 2);
ref float p = ref test.x;
Console.WriteLine(p);
return Unsafe.Add(ref p, i);
```
If the `Console.WriteLine` call is removed then the program works correctly.

But ultimately what the "right" thing is in this case is hard to say. In C++ this would be tossed into the "undefined behavior" bin.

**Comment by xoofx** [comment]
> Does this still fail if you do fixed(float4* pThis = &this) { return (float*)(pThis)[index]; }?

Nope, it works.

> Hmm, not clear if this is really a bug.

Not sure to follow you here. I mean, it's real optimizer bug right? 😅  The JIT is optimizing something that it should not, guessing that only x is used here, and removing the other values from the stack. I discovered this issue while using our compiler that translates IL to LLVM native code, where the result was actually valid (and tried also with mono which also doesn't exhibit this behavior). The code is not loading a field but taking an address, so the optimizer should not guess that we are going to use only the fixed field.

The same code with a C++ compiler would give a correct result, it is a well defined behavior (again, not following exactly what you mean, my apologize)

**Comment by mikedn** [comment]
> The same code with a C++ compiler would give a correct result, it is a well defined behavior (again, not following exactly what you mean, my apologize)

It may give the correct result depending on what side of the bed the compiler wakes up. As far as the C++ standard is concerned the operation "pointer + int" has defined behavior only when the pointer points to an array element.

It's not very clear from either the C# spec or the IL spec if such code is valid or not. I'm guessing that it could be valid because the C# spec defined pointer arithmetic in terms of memory addresses rather than arrays and because `float4` has sequential layout. But then again, it's not clear, I'm just guessing.

**Comment by xoofx** [comment]
Ok, so indeed, in the C++ specs, 5.7:

> 84) An object that is not an array element is considered to belong to a single-element array for this purpose;

And pointer arithmetic beyond the limit of an array has an undefined behavior. 

So now I understand your concern about whether this is a bug or not. 👍 

Though, I was able to test this with LLVM (both array and struct) and LLVM at least doesn't follow an undefined behavior and is working for both.

It is not so uncommon to do this kind of code (while I agree that it is unsafe, and if it is an undefined behavior in the specs, that's fair enough)... though maybe in that case, the compiler could emit a warning if we take the address of a field of a struct to clarify that the pointer is only valid for the field access, because this brings a well defined scariness 😅

**Comment by mikedn** [comment]
>  the compiler could emit a warning if we take the address of a field of a struct to clarify that the pointer is only valid for the field access

Well, taking the address of a field is perfectly fine, the compiler can't really emit a warning for that.

Anyway, we'll see what the JIT team has to say. In some cases this works correctly so perhaps they had a reason to make it work.

**Comment by xoofx** [comment]
> Well, taking the address of a field is perfectly fine, the compiler can't really emit a warning for that.

Sure but this undefined behavior makes it less "perfectly fine" in case you go beyond this sole address...

**Comment by xoofx** [comment]
For example changing the code to something like this:

```
        public static float Process(int i)
        {
            var test = new float4(5, 4, 3, 2);
            return Process2(ref test, i);
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        public static float Process2(ref float4 test, int i)
        {
            return test[i];
        }
```
returns the correct result, unless I remove the `MethodImplOptions.NoInlining` then it brings the same "bug" (inlining the undefined behavior)

**Comment by benaadams** [comment]
Can go for an explicit layout and throw in a fixed buffer and you'll get the right result
```csharp
[StructLayout(LayoutKind.Explicit)]
public unsafe struct float4
{
    public float4(float x, float y, float z, float w)
    {
        this.x = x;
        this.y = y;
        this.z = z;
        this.w = w;
    }

    [FieldOffset(0)]
    private fixed float ptr[4];
    
    [FieldOffset(0 * sizeof(float))]
    public float x;
    [FieldOffset(1 * sizeof(float))]
    public float y;
    [FieldOffset(2 * sizeof(float))]
    public float z;
    [FieldOffset(3 * sizeof(float))]
    public float w;

    public unsafe float this[int index]
    {
        get
        {
            fixed (float* array = ptr) { return array[index]; }
        }
        set
        {
            fixed (float* array = ptr) { array[index] = value; }
        }
    }
}
```

**Comment by tannergooding** [comment]
@benaadams, it feels like just taking the address of `this` is the simpler/cleaner approach at that point 😄

**Comment by benaadams** [comment]
> it feels like just taking the address of this is the simpler/cleaner approach at that point 

Throw in an extra cast instead? Works too 😄 
```csharp
public unsafe float this[int index]
{
    get
    {
        fixed (float4* array = &this) { return ((float*)array)[index]; }
    }
    set
    {
        fixed (float4* array = &this) { ((float*)array)[index] = value; }
    }
}
```

**Comment by AndyAyersMS** [comment]
Generally I would say that when you use `Unsafe` or pointers you need to know what you are doing.

But this issue is subtle -- you have to understand the how the struct promotion jit optimization works and how to inhibit the optimization if you really want to walk off one field and onto another. And we have well-defined layouts for some structures. So that might sway us towards fixing this.

My guess is that equivalent cases with pointers will exhibit this same broken behavior going way back. So unless this is a recent regression, that might sway us towards NOT fixing this.

It seems likely that attempted fixes will end up being too conservative and block promotion in cases where it is perfectly safe. But it's hard to know for sure without drilling in deeper.

**Comment by clarkis117** [comment]
I think I might have found a discrepancy between runtime versions (going backwards). Using the sample provided by @xoofx, with a minor change to use GetTypeInfo().GetMethod() for .NET Core 1.1 & 1.0  :

.NET Core 2.0
```
dotnet run -f netcoreapp2.0 -c release --runtime win10-x64 --no-incremental
Result: 5
Result: -2.661089E+11
Result: 3.503246E-44
Result: 1.4579E+30
```

.NET Core 1.1
```
dotnet run -f netcoreapp1.1 -c release --runtime win10-x64 --no-incremental
Result: 5
Result: 4
Result: 3
Result: 2
```

.NET Core 1.0
```
dotnet run -f netcoreapp1.0 -c release --runtime win10-x64 --no-incremental
Result: 5
Result: 4
Result: 3
Result: 2
```

.NET Framework 4.7
```
dotnet run -f net47 -c release --runtime win10-x64 --no-incremental
Result: 5
Result: -8.670312E+22
Result: 3.054831E-43
Result: -8.165179E-16
```

.NET Framework 4.6
```
dotnet run -f net46 -c release --runtime win10-x64 --no-incremental
Result: 5
Result: -2.249678E-33
Result: 1.121039E-44
Result: -8.165179E-16
```

.NET Framework 4.5
```
dotnet run -f net45 -c release --runtime win10-x64 --no-incremental
Result: 5
Result: 1.240206E-23
Result: 5.465064E-44
Result: -8.165179E-16
```

.NET Framework 4.0
```
dotnet run -f net40 -c release --runtime win10-x64 --no-incremental
Result: 5
Result: 1.027479E-38
Result: 0
Result: -8.165179E-16
```

Project is Here: https://github.com/clarkis117/InvalidCodeGenx64Fixed

**Comment by xoofx** [comment]
> But this issue is subtle -- you have to understand the how the struct promotion jit optimization works and how to inhibit the optimization if you really want to walk off one field and onto another. And we have well-defined layouts for some structures. So that might sway us towards fixing this.

@AndyAyersMS  Also the fact that running with a a debug assembly doesn't exhibit this bug (haven't checked the details how IL code is slightly different there). Also in my example above, the fact that the ref could point to a field of a embedded struct in a managed object would not exhibit this behavior as well. It happens only when you are using a struct instantiated on the stack that is involved close enough in an inlining strategy. 

> My guess is that equivalent cases with pointers will exhibit this same broken behavior going way back. So unless this is a recent regression, that might sway us towards NOT fixing this.
> It seems likely that attempted fixes will end up being too conservative and block promotion in cases where it is perfectly safe. But it's hard to know for sure without drilling in deeper.

I agree. I can live with the disclaimer that taking fixed of a field of a struct on a stack might give unpredictable results depending if the address is used beyond this sole field. Roslyn compiler could maybe emit a warning if it sees (likely painful to determine) that a fixed field is used and its address is being scrambled... but it could give false positive in case it cannot see that the ref struct is actually not on the stack and not inlineable... ah, well, undefined behavior are really annoying...

> I think I might have found a discrepancy between runtime versions (going backwards). Using the sample provided by @xoofx, with a minor change to use GetTypeInfo().GetMethod() for .NET Core 1.1 & 1.0 :

@clarkis117 Interesting that it appeared to work only for .NET Core 1.x. For the .NET framework, do you really have separated runtimes on your machine? (As there is usually only one in `C:\Windows\Microsoft.NET\`- the latest - the framework being just routed differently to it)

**Comment by RussKeldorph** [comment]
Calling this a question until it is resolved whether this is a bug.

**Comment by benaadams** [comment]
It would probably impact the "Fixed Sized Buffers" proposal? https://github.com/dotnet/csharplang/blob/master/proposals/fixed-sized-buffers.md
```csharp
[CompilerGenerated, UnsafeValueType, StructLayout(LayoutKind.Sequential, Pack = 0)]
struct <Buffer>e__FixedBuffer_1024<T>
{
    private T _e0;
    private T _e1;
    // _e2 ... _e1023
    private T _e1024;

    public ref T this[int index] => ref (uint)index <= 1024u ?
                                         ref RefAdd<T>(ref _e0, index):
                                         throw new IndexOutOfRange();
}
```

**Comment by xoofx** [comment]
good catch and likely 😞

**Comment by tannergooding** [comment]
I think it impacts fixed sized buffers in general, including the existing ones. The existing fixed sized buffers reference a single element in an explicitly sized struct and then access it like an array.

**Comment by AndyAyersMS** [comment]
Cautiously optimistic that there might be a simple fix here. Morph is already doing this sort of analysis; it looks like it just overlooks one case.

**Comment by AndyAyersMS** [comment]
Overlooks maybe *two* cases....

**Comment by mikedn** [comment]
> Overlooks maybe two cases....

@AndyAyersMS Maybe three cases?
```c#
struct foobar {
    public byte b1, b2, b3, b4;
    public foobar(int x) {
        b1 = 1;
        b2 = 2;
        b3 = 3;
        b4 = 4;
    }
}
[MethodImpl(MethodImplOptions.NoInlining)]
static int Test() {
    foobar f = new foobar(42);
    return Unsafe.As<byte, int>(ref f.b1);
}
```
generates
```asm
G_M55888_IG01:
       50                   push     rax
G_M55888_IG02:
       C644240401           mov      byte  ptr [rsp+04H], 1
       8B442404             mov      eax, dword ptr [rsp+04H] ; reads 3 bytes of garbage data
G_M55888_IG03:
       4883C408             add      rsp, 8
       C3                   ret
```
Should we fix this as well?

**Comment by AndyAyersMS** [comment]
Seems like perhaps we should. 

The trouble arises here as we don't realize the indir can read beyond the field:
```
[000015] *-CXG-------    \--*  IND       int   
[000045] ----G-------       \--*  ADDR      byref 
[000046] ----G-------          \--*  FIELD     ubyte  b1
[000047] L-----------             \--*  ADDR      byref 
[000048] ------------                \--*  LCL_VAR   struct V00 loc0         
```
Trying to catch this via lookahead from `GT_IND` seems somewhat clunky, but perhaps it will work out ok.

But it seems like we perhaps should extend the AXC stack to include offset and width (both of which can be unknown) and stop relying so much on lookahead for this and other cases.

**Comment by mikedn** [comment]
> But it seems like we perhaps should extend the AXC stack to include offset and width (both of which can be unknown) and stop relying so much on lookahead for this and other cases.

Yep, I'm trying to do just that.
