### ISSUE TITLE
Debugger FIFO pipes ignores TMPDIR

### ISSUE THREAD

**Issue by crntn** [dotnet/coreclr#16234]
This is issue is related to [issue#8844](https://github.com/dotnet/coreclr/issues/8844)
I need to run dotnet in a restricted environment that do not have access to /tmp.

As described in the above linked issue we noticed that twowaypipe.cpp creates 2 files into /tmp.
See [process.cpp](https://github.com/dotnet/coreclr/blob/master/src/pal/src/thread/process.cpp#L1465)

Considering there is a method in [path.cpp](https://github.com/dotnet/coreclr/blob/e45a895df6b4cc50347daafed05cefa59af511a2/src/pal/src/file/path.cpp#L437) that generates a temp path respecting the TMPDIR env variable, I am inclined to think the debugger FIFO pipes should also respect this convention and writes the files to TMPDIR if the variable is set.

Would it make sense to submit a pull request implementing this change ? 

Thanks !

**Comment by jkotas** [comment]
cc @mikem8361

**Comment by mikem8361** [comment]
@crntn if you want to do the work, I'll help and review it. I'm in the middle fixing a problem on arm tizen with my PR that allows debugging (which includes creating those pipes on Linux) be disabled with an environment variable (PR #16141).

**Comment by mikem8361** [comment]
Fixed now.
