### ISSUE TITLE
Enable containment test for AVX.LoadVector256/LoadAlignedVector256

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#16244]
After AVX.Load* intrinsics get implemented, the HW-intrinsic test template should enable containment test for `AVX.LoadVector256/LoadAlignedVector256`.

https://github.com/dotnet/coreclr/pull/16200#issuecomment-362972744

cc @tannergooding @CarolEidt

**Comment by tannergooding** [comment]
@fiigii, are you planning on enabling these after #16200 is merged, or should I do it?

**Comment by fiigii** [comment]
> are you planning on enabling these after #16200 is merged,

Yes, I can do it. Do not worry 😄 
BTW, I will submit a PR to implement most of the simple SIMD intrinsics of AVX/AVX2 in this week, which probably a good chance to test containment on `AVX.LoadVector256/LoadAlignedVector256` as well.

**Comment by CarolEidt** [comment]
@fiigii - I assigned this to you, as well as one for the simple AVX/AVXs intrinsics (#16426).

**Comment by fiigii** [comment]
@CarolEidt Got it. Thanks. In the future, if I have any plan, I will open issues at first.
