### ISSUE TITLE
Improve FEATURE_PARTIAL_SIMD_CALLEE_SAVE

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#16282]
FEATURE_PARTIAL_SIMD_CALLEE_SAVE is used to enable saving and restoring the high bits of certain registers which the platform ABI does not require the caller to preserve.

The current implementation inserts a save and restore of the high bits for every call.

This solution is naive.  It restores every register immediately regardless : 
+ whether it will ever be used in the function
+ whether it will need to be saved again before use in the function

Also I expect the cost of the register save restore is not properly handled in local register promotion/enregistering cost metrics.

@dotnet/jit-contrib 

category:cq
theme:basic-cq
skill-level:expert
cost:medium

**Comment by CarolEidt** [comment]
Thanks for submitting this issue. I don't believe that it will actually restore a register that is never used again (the lclVar in it wouldn't be live at that point), but you are certainly correct that 1) it doesn't determine whether it will simply need to be saved again, and 2) it doesn't evaluate the cost.
I confess that I haven't thought about it deeply, but I think these need a different model that the binary caller-save vs. callee-save choice supports.

**Comment by CarolEidt** [comment]
@sdmaclea - I believe that this was addressed with #23344, so I'm inclined to close this.
