### ISSUE TITLE
CI Reliability: Alpine linux leg fails in Jenkins

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#16285]
Probably intermittent infrastructure issue:

https://ci3.dot.net/job/dotnet_coreclr/job/master/job/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/1896/

> Setting status of d341a66e5aac7b8471bb133231703fa0f0dd5db6 to FAILURE with url https://ci3.dot.net/job/dotnet_coreclr/job/master/job/alpine-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/1896/ and message: 'Build finished. '
> Using context: Alpine.3.6 x64 Debug Build
> java.lang.NullPointerException
> 	at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1026)
> 	at java.util.Collections$UnmodifiableList.<init>(Collections.java:1302)
> 	at java.util.Collections.unmodifiableList(Collections.java:1287)
> 	at hudson.model.ParametersAction.getAllParameters(ParametersAction.java:351)
> 	at sun.reflect.GeneratedMethodAccessor439.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.jenkinsci.plugins.workflow.cps.ParamsVariable.getValue(ParamsVariable.java:61)
> 	at org.jenkinsci.plugins.workflow.cps.CpsScript.getProperty(CpsScript.java:121)
> 	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:456)
> 	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:284)
> 	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
> 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:326)
> 	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:282)
> 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:286)
> 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:262)
> 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:262)
> 	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
> 	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
> Caused: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.GeneratedMethodAccessor439.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.jenkinsci.plugins.workflow.cps.ParamsVariable.getValue(ParamsVariable.java:61)
> 	at org.jenkinsci.plugins.workflow.cps.CpsScript.getProperty(CpsScript.java:121)
> 	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
> 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:456)
> 	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:284)
> 	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
> 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:326)
> 	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:282)
> 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:286)
> 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:262)
> 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:262)
> 	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
> 	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
> 	at WorkflowScript.run(WorkflowScript:22)
> 	at ___cps.transform___(Native Method)
> 	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
> 	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
> 	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
> 	at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
> 	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
> 	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
> 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
> 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
> 	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
> 	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
> 	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
> 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
> 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:35)
> 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
> 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
> 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:32)
> 	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
> 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:330)
> 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
> 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:242)
> 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:230)
> 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
> 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Finished: FAILURE

**Comment by noahfalk** [comment]
@mmitche

**Comment by AndyAyersMS** [comment]
@noahfalk seems like this has been pretty reliable lately....

**Comment by noahfalk** [comment]
I agree, the failure seems rare. @AndyAyersMS were you suggesting we should dispose of the bug in some manner? 

@mmitche - Is this an issue you or someone on your team is interested in tracking or are we just ignoring CI infra failures that don't meet a certain threshold of reproducibility?

**Comment by mmitche** [comment]
@noahfalk If this happened after a jenkins restart (most likely, but I can't tell becuase that build has been deleted), then this is something just to ignore as it won't be reproducible in normal operation.

**Comment by noahfalk** [comment]
OK, sounds like its not useful for investigation so I'm going to close the issue.
