### ISSUE TITLE
[x86][RyuJit][JitStress=1]JIT_HardwareIntrinsics._X86 fails

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#16290]
4 Hardware intrinsics tests started to fail after https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitstress1/406/ with:
`Assertion failed 'genActualType(lclTyp) == genActualType(op1->gtType) || genActualType(lclTyp) == TYP_I_IMPL && op1->IsVarAddr() || (genActualType(lclTyp) == TYP_I_IMPL && (op1->gtType == TYP_BYREF || op1->gtType == TYP_REF)) || (genActualType(op1->gtType) == TYP_I_IMPL && lclTyp == TYP_BYREF) || (varTypeIsFloating(lclTyp) && varTypeIsFloating(op1->TypeGet())) || ((genActualType(lclTyp) == TYP_BYREF) && genActualType(op1->TypeGet()) == TYP_REF)`

**Comment by sandreenko** [comment]
cc @tannergooding @fiigii @dotnet/jit-contrib

**Comment by tannergooding** [comment]
This is already tracked by https://github.com/dotnet/coreclr/issues/16236

@fiigii is currently working on a fix.

**Comment by sandreenko** [comment]
Thanks, closed as duplicate.
