### ISSUE TITLE
[Arm64] Create Bootstrap Command Line Build Tools for Preview 2.1

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#16299]
@janvorli was able to help me build a bootstrap command line tool `dotnet` for Arm64 based on the 2.0 release.  Unfortunately this was unstable.

Now that 2.1 release is approaching, I would like to build a new bootstrap tool chain based on the 2.1 AMD64 preview release.

To make this simple I need

1. AMD64 Ubuntu 2.1 preview CLI & SDK toolchain.  Is there a 2.1 CLI/SDK actively being built?  Are there artifacts somewhere?
2. Windows 2.1 CoreCLR 2.1 build with test artifacts.  Is the 2.1 branch of CoreCLR being actively built?  Are there artifacts in CI somewhere?
3. A patch to CoreCLR to make it build with the AMD64 Ubuntu 2.1 preview CLI & SDK toolchain.  
Linux My testing of the 2.0 CLI was based on attempting to build CoreCLR.  This seemed like a pretty rigorous test.  Is there a branch of CoreCLR which will build successfully with a preview 2.1 tool chain?  Is it difficult to build CoreCLR with a different tool chain?  

@jkotas @RussKeldorph I am not sure who the correct people to ask about this or if this is premature.

**Comment by jkotas** [comment]
>  Is there a 2.1 CLI/SDK actively being built?

Yes. Daily builds are at https://github.com/dotnet/cli

> A patch to CoreCLR to make it build with the AMD64 Ubuntu 2.1 preview CLI & SDK toolchain.

There should be no patches required. https://github.com/dotnet/source-build/ is the right place to discuss this.
