### ISSUE TITLE
OSX CI builds are failing during linking of libmscordbi.dylib with missing symbol _IID_ICorDebugFunction4 linker error

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#16294]
Yesterday OSX CI builds started to fail with subproject build error:

```
00:24:02.499 Undefined symbols for architecture x86_64:
00:24:02.499   "_IID_ICorDebugFunction4", referenced from:
00:24:02.517       CordbFunction::QueryInterface(_GUID const&, void**) in libcordbdi.a(rsfunction.cpp.o)
00:24:02.525 ld: symbol(s) not found for architecture x86_64
00:24:02.532 clang: error: linker command failed with exit code 1 (use -v to see invocation)
00:24:02.532 make[2]: *** [src/dlls/mscordbi/libmscordbi.dylib] Error 1
00:24:02.532 make[1]: *** [src/dlls/mscordbi/CMakeFiles/mscordbi.dir/all] Error 2
```
It affects several PRs including #16237, #16288, #16223 and others

Examples:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_prtest/621/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_prtest/617/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_prtest/620/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_prtest/614/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx10.12_prtest/11422/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx10.12_prtest/11423/

**Comment by RussKeldorph** [comment]
@davmason @noahfalk Can you check if this is due to #15819?

@dotnet/dotnet-diag

**Comment by jkotas** [comment]
The offending change reverted in #16300
