### ISSUE TITLE
ExecutionContext.SuppressFlow() suppression state does not flow

### ISSUE THREAD

**Issue by TimLovellSmith** [dotnet/coreclr#16307]
Hi,
I have been wrestling with behavior of ExecutionContext.SuppressFlow() when combined with await/async. I have slowly come to believe the current behavior (in .net version I'm using at least) is flawed. Here is the problem.

Because ExecutionContext does not come for free, and saving/restoring it has measurable overheads,
I think it is a good idea for me to suppress the ExecutionContext flow in a method I have which loops for a long time and happens to be implemented as async. I.e. something like this

```
async void ReadWriteLoop()
{
    ExecutionContext.SuppressFlow();
    while (true)
    {
         await AsyncCallNumberOne();
         await AsyncCallNumberTwo();
         await AsyncCallNumberThree();
    }
}

async Task AsyncCallNumberOne()
{
    await AsyncCallNumberFour();
    await AsyncCallNumberFive();
}
```

However, the observed behavior of this code is that after each async call, `ExecutionContext.IsFlowSuppressed()` might return `false`.
This presents a problem. The only way I can definitely get ExecutionContext to be suppressed for this entire logical execution flow is by peppering suppress calls everywhere:

```
void EnsureSuppressed() { If (!ExecutionContext.IsFlowSuppressed()) ExecutionContext.SuppressFlow(); }

async void ReadWriteLoop()
{
    while (true)
    {
         EnsureSuppressed();
         await AsyncCallNumberOne();
         EnsureSuppressed();
         await AsyncCallNumberTwo();
         EnsureSuppressed();
         await AsyncCallNumberThree();
    }
}

async Task AsyncCallNumberOne()
{
    Debug.Assert(ExecutionContext.IsFlowSuppressed(), "we know it is suppressed by the caller... in this case");
    await AsyncCallNumberFour();
    EnsureSuppressed();
    await AsyncCallNumberFive();
}
```
I.e. the observed behavior is that while the _execution context_ successfully is suppressed, and we resume execution without restoring the execution context, the _suppression state_  is not restored, requiring us to suppress execution context all over again in order to get it really suppressed.

This doesn't seem good. Calling ExecutionConext.IsFlowSuppressed() and ExecutionContext.SuppressFlow() like this isn't free in either lines of code nor CPU and memory!

The behavior I actually believe should happen is that the _suppression state_ should be preserved around the async call, meaning there need be no further calls to EnsureSuppressed();

That would better fulfil what I believe the _intent_ of ExecutionContext.SuppressFlow() is: to suppress flow of the entire context for the current 'logical execution operation'.

And then it also might be feasible to undo the suppression correctly (currently it seems like it is a conceptual mess to do this!)

**Comment by RussKeldorph** [comment]
@kouvel @stephentoub

**Comment by Farham0** [comment]
What do you think of using a delegate?

**Comment by TimLovellSmith** [comment]
@Farham0 I don't think I yet understand your question. Are you suggesting I should not use await/async, but use delegates with .ContinueWith(), or Async callbacks approach instead?

**Comment by TimLovellSmith** [comment]
Closing this as I'm no longer of the opinion it makes sense. The main problem with my idea is that ExecutionContext is basically a "thread-local" concept, whereas async/await switches you *across threads*.
