### ISSUE TITLE
Refactor the x86 instruction metadata

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#16333]
There are a number of TODO-XArch bugs today (mostly in `emitxarch.h`) that suggest we update the instruction metadata to carry additional information. However, there are some limitations with the current implementation that may hinder these workitems from being resolved.

I believe the two primary limitations in the existing setup are:
* A specific ordering of definitions is required
  * This limits the ability to easily refactor or re-order the existing data
* The current definitions assume all encodings of an instruction share the same "properties"
  * Some encodings belong to different ISAs
  * Some encodings support different architectures (32-bit vs 64-bit)
  * Some encodings read/write flags, while others may not
  * Some encodings may vary on the prefixes supported/required
  * etc...

I've created this issue as a place of discussion on how the instruction metadata should be updated to best support the current state and any future changes that may be desired.

**Comment by tannergooding** [comment]
FYI. @CarolEidt

**Comment by tannergooding** [comment]
I believe the first issue (the current implementation requires definitions to be particularly ordered) is more trivial to resolve (and I think I have such a refactoring complete locally, at the very least all the tests are passing).

It looks like we currently require the entries to be defined in the following order:
* INST5
* INST4
* INST3
* INST2
* INST1
* INST0

It looks like this was done in order to save space in the various `insCodes` tables. However, this quickly broke down with the introduction of the SIMD instructions where they all use the `INST3` definitions and generally have two `BAD_CODE` encodings.

Updating the tables to define an entry for all instructions removes most of the ordering limitations. The remaining ordering limitations are with certain instruction "groups" (such as `imul_AX` through `imul_R15`, or the `JCC`, `SETCC`, or `MOVCC` instructions). However these remaining limitations cause less issues.

**Comment by tannergooding** [comment]
The second issue (flags and other metadata are on a per instruction, rather than a per encoding basis) is more complicated.

I believe we would need to update the metadata to define an instruction (id + name). Each instruction would then have multiple encodings. Each encoding would then define the following data:
* ISA
* Base Encoding (the actual bytes for the encoding)
* CPU Flags Read
  * A general bool is defined in the current table, but looks unused
  * This would actually be a bitmap of the individual flags read
* CPU Flags Written
  * A general bool is defined in the current table, but looks unused
  * This would actually be a bitmap of the individual flags written
* Encoding Flags
  * Supports 32-bit
  * Supports 64-bit
  * Supports 2-byte VEX Prefix
  * Supports 3-byte VEX Prefix
  * etc

How these encodings are defined per instruction is probably worth some discussion. The current Architecture manual specifies there are a few different instruction formats (see Volume 2, Chapter 2):
* Protected Mode, Real-Address Mode, and Virtual 8086 Mode Encoding
* IA-32E Mode Encoding
* AVX Encoding (VEX Encoding)
* VEX Encoding for GPR
* AVX-512 Encoding (EVEX Encoding)

In order to limit the amount of table data that is unused and to support future encodings, it would likely be beneficial to construct some mechanism for defining encodings in each of these categories, but not requiring each category per instruction. This will likely also simplify the various checks/code-paths required in the emitter.

**Comment by tannergooding** [comment]
Also FYI. @fiigii 

This might be required (or at the very least make future work easier) if/when AVX-512 comes into play.

**Comment by CarolEidt** [comment]
@tannergooding - How would you see this as different from #14523?

Two general comments:
- The encoding of instructions takes a non-trivial percentage of JIT time, so we not only want to ensure that we don't regress throughput, but really need to have a goal of improving it with a refactor.
- We don't want all the code generation for XARCH to have to worry about whether it is generating SSE or AVX encodings, so we want to preserve the mapping from one to the other where it exists.

**Comment by tannergooding** [comment]
> How would you see this as different from #14523?

I missed that there was an existing issue for this, GitHub search didn't turn it up with the terms I used.

> We don't want all the code generation for XARCH to have to worry about whether it is generating SSE or AVX encodings, so we want to preserve the mapping from one to the other where it exists.

The existing logic for that will likely change with any significant refactoring we do to better handle VEX prefixes, so we should be able to ensure that the new mechanism handles this case as well.

**Comment by tannergooding** [comment]
Going to close this as a dupe of #14523 and migrate my comments over, where relevant.

**Comment by fiigii** [comment]
> The existing logic for that will likely change with any significant refactoring we do to better handle VEX prefixes

One of my concern is that the refectoring may break legacy backbend build, we always need to consider desktop-CLR very carefully...

**Comment by tannergooding** [comment]
> One of my concern is that the refectoring may break legacy backbend build, we always need to consider desktop-CLR very carefully...

@BruceForstall commented (see https://github.com/dotnet/coreclr/pull/15804#issuecomment-358109723) that the LEGACY_BACKEND code could be removed at some point in the future, at which point that will no longer be a concern.
