### ISSUE TITLE
Managed Struct Bitfield support

### ISSUE THREAD

**Issue by fanoI** [dotnet/coreclr#1635]
Support for Struct Bitfileds could be added to the CLR?
Having to talk with low level hardware in C/C++ is really natural to write something as:

```
  typedef struct reg {
         unsigned char bit1: 1;
         unsigned char bit2: 1;
         unsigned char bit3: 1;
         unsigned char bit4: 1;
         unsigned char bit5: 1;
         unsigned char bit6: 1;
         unsigned char bit7: 1;
         unsigned char bit8: 1;
  } reg_t;

  reg_t reg;
```

to write in the VI bit one simply does: `reg.bit6 = 1` and get the value of the bit ifself it is easy.
When it is time to write to the device you simple cast the the thing to char (they are 8 bit that is a byte) and use the write method.
In C# this could be done with bitmask that seems to me a return to the past or with the bitVector that is not so simple to use that the struct above (it is not so easy to map what the VI bit means in the stuct I can give the proper name for example a printer could set it to one with paper is OFF and so the field will be called low_paper_on).

**Comment by zabulus** [comment]
Have you tried to use enum with ```FlagsAttibute``` and with ```byte``` base type? 
It is not so flexible as bit-fields structs. Reading: IsFlag(bitname). Setting flag: value = value | bitname. Unsetting flag: value = value & !bitname.
You could even wrap this to extension methods.

**Comment by mikedn** [comment]
> Support for Struct Bitfileds could be added to the CLR?

This is something that can be done in a .NET language like C#, it doesn't have to be done in the CLR. Doing this in the CLR would require a ton of work to extend the metadata format and possibly the IL and the only added benefit would be reflection support. It seems rather unlikely that you would need to mix reflection and bitfields.

> In C# this could be done with bitmask that seems to me a return to the past

It's hardly a return to the past as you would do the same thing in C/C++ as well. The precise way the bits are allocated is compiler dependent and as such people avoid using bitfields in scenario like the one you describe.

**Comment by fanoI** [comment]
How this could be done in C#? With a class? In a struct you cannot indicated the size in bit of the fields (there is struct layout but the size is in bytes the only thing you can have is fields that occupy the same memory useful to emulate unions) or this could emulated with some "syntatic sugar"?
I know that in C/C++ in reality is the compiler that does the bitmasking and that padding issues could be presents but using GCC attribute packed the 8 bit struct in the example occupies exactly one byte as
the low level device expects. Obviously I expect in C#/CLR to have always a defined behavior so this should be never an issue.

Enum flags not solve totally the problem: if the bit field does not have size one bit but more (to talk to some devices you will need 14 bit for example).

A possible alternative to a bit field struct could be a sort of BitBuffer class in which to indicate the size in bits of the object and then can be used as an int.

It could be used in this way:

    BitBuffer b = new BitBuffer(1); // What is this for the CLR? A Byte with 7 bits not used?
    b = 1; // give the value of 1 to the bit (true / false could be accepted as this the "true" boolean type)
    if (b == 1)
         WriteLine("b is 1!");
    else
         WriteLine("b is NOT 1!");
    b++; // b is now 0 because 1 + 1 = 0 plus carry that is lost

This is another case to simulate an int24 (usable for RGB or to send command to some audiocards):

      BitBuffer color = new BitBuffer(24);
      color = 42; // I don't know what color this is...

Our struct could become:

    typedef struct reg {
        BitBuffer bit1 = new BitBuffer(1);
        BitBuffer bit2 = new BitBuffer(1);
        BitBuffer bit3 = new BitBuffer(1);
        BitBuffer bit4 = new BitBuffer(1);
        BitBuffer bit5 = new BitBuffer(1);
        BitBuffer bit6 = new BitBuffer(1);
        BitBuffer bit7 = new BitBuffer(1);
        BitBuffer bit8 = new BitBuffer(1);
     } reg_t;

     reg_t reg;

But we are allocating a lot of memory and so it is less efficient, for sure our struct not occupy 1 Byte anymore (but this could be solved using the getBytes() method of Object when you need to send  the data the device) and, in the end, it is less immediate that the starting bitfield struct.

One other thing against bitmask they are not unsafe too? For example using a Byte as base I cannot do a >> 9 and go outside the byte memory? Have a proper bitfield will enforce simplicity and  language security too.

**Comment by mikedn** [comment]
> How this could be done in C#? With a class? In a struct you cannot indicated the size in bit of the fields 

This has nothing to do with classes or structs. The C# compiler simply needs to pack the bit fields into normal fields of the appropriate integral type, exactly the same way C/C++ compilers do. Though unlike in the C/C++ case this packing can be done by well defined rules.

An attribute would have to be added to the generated field(s) to indicate what bitfields were packed into it so they can be accessed by code outside the assembly. Languages without bitfield support would not be able to see these fields but usually fields are accessed via properties so this shouldn't be a problem. Anyway you'd have a similar problem if you modify the runtime to support bitfields in metadata.

> A possible alternative to a bit field struct could be a sort of BitBuffer class in which to indicate the size in bits of the object and then can be used as an int.

There's `BitVector32` which does something like that already. Though personally I don't like its design and usually use something simpler (example adapted from real code):

```C#
struct Node
{
    private uint bits;

    public uint Bits
    {
        get { return bits; }
    }

    public bool IsLeaf
    {
        get { return GetBits(31, 1) != 0; }
        set { SetBits(31, 1, value ? 1u : 0u); }
    }

    public int Index
    {
        get { return (int)GetBits(0, 31); }
        set { SetBits(0, 31, (uint)value); }
    }

    private uint GetBits(int index, int length)
    {
        return (bits >> index) & ((1u << length) - 1u);
    }

    private void SetBits(int index, int length, uint value)
    {
        uint mask = ((1u << length) - 1u) << index;
        bits = (bits & ~mask) | ((value << index) & mask);
    }
}
```

Granted, writing the property getters and setters is a bit tedious but how often do you need this kind of types anyway?

> One other thing against bitmask they are not unsafe too? For example using a Byte as base I cannot do a >> 9 and go outside the byte memory? Have a proper bitfield will enforce simplicity and language security too.

Let's not try to oversell features, this has nothing to do with safety (in the sense that is used in the .NET world) nor security because you cannot "go outside the byte memory". At best it is error prone if you sprinkle bit accesses throughout the code but this can be avoided by encapsulating those accesses in properties. It's just that you need to write a bit more code to do so.

**Comment by fanoI** [comment]
I use bitfields a lot in reality as I have to write device drivers (in user space not in kernel space) to talk to for example to serial printers and this type of devices to use less memory possible use bitmask / bitfields a lot for example is typical to have 8 diagnostic sensors of the device packed in a byte.
So I have to write a lot of these tedious classes to make bitmasks more usable and it is for this that I proposed a CLR integrated solution. If only C# could use bitfields there will be the same problem that C++/CLI has with "native" C++ types it cannot interop directly with the other languages.

**Comment by mikedn** [comment]
>  it is for this that I proposed a CLR integrated solution. If only C# could use bitfields there will be the same problem that C++/CLI has with "native" C++ types it cannot interop directly with the other languages.

A CLR integrated solution doesn't guarantee that other languages can use bitfields because it's up to each language to provide access to the runtime solution. In the end it comes down to choosing between changing both the runtime and the compiler(s) or changing only the compiler(s).

**Comment by sgf** [comment]
request too,
like C Bit Fields https://docs.microsoft.com/en-us/cpp/c-language/c-bit-fields?view=vs-2019

**Comment by BruceForstall** [comment]
Closing this in favor of https://github.com/dotnet/csharplang/issues/465
