### ISSUE TITLE
Build fails with weird errors if git is not on path

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/coreclr#16356]
Running the build.cmd script (on Windows) from VS development environment without having git on path fails the build in a really weird way which is hard to figure out.
If this happens the error reported is:
```
E:\coreclr\bin\obj\_version.h(19): error RC2001: newline in constant [E:\coreclr\bin\obj\Windows_NT.x86.Debug\src\tools
\crossgen\crossgen.vcxproj]

```
Looking into this the _version.h has a line like this:
```
#define VER_PRODUCTVERSION_STR      "4.6.26211.0 @BuiltBy: vitkaras-VITKARASD @Branch: 'git' is not recognized as an internal or external command,
operable program or batch file."

```
If the build really needs git (which in this case it could put some <unknown> string instead into the version), then it should fail up front with a clear error message. Currently it fails during compilation and keeps on trying to compile and so on.

**Comment by danmosemsft** [comment]
@wtgodbe maybe this was the issue you were hitting..

**Comment by RussKeldorph** [comment]
This issue was moved to dotnet/buildtools#1959
