### ISSUE TITLE
HW intrinsics and SuperPMI

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#16350]
How should the hardware intrinsics work with SuperPMI collection and replay?

Currently, when I run, for example, JIT\HardwareIntrinsics\X86\Avx2\Avx2_ro, the test passes.

When I set some variables to collect SuperPMI on this test:
```
set SuperPMIShimLogPath=e:\gh\coreclr2\bin\tests\Windows_NT.x86.Checked\JIT\HardwareIntrinsics\X86\Avx2\Avx2_ro
set SuperPMIShimPath=e:\gh\coreclr2\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\clrjit.dll
set COMPlus_AltJit=*
set COMPlus_AltJitName=superpmi-shim-collector.dll
```

and run, I get a crash: JIT_ThrowPlatformNotSupportedException, from the stack:
```
...
CoreCLR!JIT_ThrowPlatformNotSupportedException+0x21a
System_Private_CoreLib!System.Runtime.Intrinsics.X86.Avx2.Add(System.Runtime.Intrinsics.Vector256`1<Byte>, System.Runtime.Intrinsics.Vector256`1<Byte>)+0x5
Avx2_ro!JIT.HardwareIntrinsics.X86.SimpleBinaryOpTest__AddByte.RunBasicScenario()+0x66
Avx2_ro!JIT.HardwareIntrinsics.X86.SimpleBinaryOpTest__AddByte.RunUnsupportedScenario()+0x27
Avx2_ro!JIT.HardwareIntrinsics.X86.Program.AddByte()+0x20
Avx2_ro!JIT.HardwareIntrinsics.X86.Program.Main(System.String[])+0xa1
...
```

Is there some JIT-EE API not being implemented properly by the SuperPMI shim? Is there additional work that needs to happen to support collection/replay of HW intrinsics?

**Comment by BruceForstall** [comment]
@CarolEidt @fiigii @tannergooding @sdmaclea

**Comment by fiigii** [comment]
> Is there some JIT-EE API not being implemented properly by the SuperPMI shim? 

I introduced 3 JIT-EE interfaces for HW intrinsics in https://github.com/dotnet/coreclr/pull/15244 and https://github.com/dotnet/coreclr/pull/15340
- getTypeForPrimitiveNumericClass
- getClassNameFromMetadata
- getTypeInstantiationArgument

But I am not familiar with SuperPMI, so I just followed other API's SPMI code. Do they make this problem?

Additionally, the JIT-helper `ThrowPlatformNotSupportedException` was also introduced for HW intrinsics. This scenario (`RunUnsupportedScenario`) tests unsupported situations that should catch `PlatformNotSupportedException`.

**Comment by CarolEidt** [comment]
The hardware intrinsics should work much the same as SIMD does for SuperPMI - that is, it should record (and then replay) the calls that the JIT makes to determine the ISA, as well as getting the type info that @fiigii mentions. It's not immediately apparent what might be missing.

**Comment by BruceForstall** [comment]
Well, with a current sync and build, I don't see this problem anymore. Maybe something got fixed.
