### ISSUE TITLE
Permanent cross-platform sdk for profilers

### ISSUE THREAD

**Issue by bobuva** [dotnet/coreclr#16369]
The [ProfilingAPI sample](https://github.com/Microsoft/clr-samples/tree/master/ProfilingAPI) has a [documentation note](https://github.com/Microsoft/clr-samples/tree/master/ProfilingAPI#native-sdk-for-consuming-the-profiler-apis) that states that building that sample using headers from the CoreCLR source is a temporary solution, awaiting a more permanent sdk. 

Do you have any more information on whether that sdk is ready to be consumed by profiler writers?

**Comment by RussKeldorph** [comment]
@noahfalk

**Comment by lt72** [comment]
@bobuva: we have not scheduled yet creating a proper SDK for the Debugging and Profiling API. We are considering this work for the release after 2.1 (likely sometimes at the end of 2018), but there is not committed work item yet.

**Comment by bobuva** [comment]
Great, thanks for the reply!
