### ISSUE TITLE
[Arm64/Linux] Release 2.1 -- System.TypeLoadException: Virtual Non-Abstract Interface Method

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#16368]
On the Release 2.1  branch e259e0acec, I see the following assert.

```
corerun diamondshape.exe

Unhandled Exception: System.TypeLoadException: Virtual Non-Abstract Interface Method.
   at Program.Negative()
   at Program.Main()
```
Affects the following tests
```
Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape/diamondshape.sh
Loader/classloader/DefaultInterfaceMethods/genericmethods/genericmethods/genericmethods.sh
Loader/classloader/DefaultInterfaceMethods/methodimpl/methodimpl/methodimpl.sh
Loader/classloader/DefaultInterfaceMethods/sharedgenerics/sharedgenerics/sharedgenerics.sh
Loader/classloader/DefaultInterfaceMethods/simple/simple/simple.sh
Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh
```

**Comment by sdmaclea** [comment]
@jkotas My guess this is a crossplatform problem.

**Comment by jkotas** [comment]
This is test for default interfaces feature. This feature and the matching tests should disabled in the release/2.1 branch. 

@MichalStrehovsky Any know issues with this?

**Comment by MichalStrehovsky** [comment]
These got disabled when the feature got turned off in #15994. Is there another exclusion list besides `issues.targets` and `testsFailingOutsideWindows.txt` where we need to disable these?

**Comment by sdmaclea** [comment]
Found using my CI system.  I had missed their addition into testsFailingOutsideWindows

Closing as these failures are expected.
