### ISSUE TITLE
GCStress failure: test147911_cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#16375]
x86 checked `GCStress=C` failure:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc/67/testReport/junit/baseservices_exceptions/_regressions_Dev11_147911_test147911_test147911_/_regressions_Dev11_147911_test147911_test147911_cmd/

Related to #12522?

(Also see #15883)

**Comment by BruceForstall** [comment]
@janvorli since you are assigned #12522, I'm assigning this to you as well.

**Comment by janvorli** [comment]
I've tried to repro it locally, but even after 15000 iterations with GCStress=C, I could not repro it. The lab log is gone already.

**Comment by janvorli** [comment]
I'm closing the issue, in case it repros again, I'll try to dig more info from the lab log and run a repro on the same machine where it happened.
