### ISSUE TITLE
What information can be candidates for pitching (dropping)?

### ISSUE THREAD

**Issue by sergign60** [dotnet/coreclr#16387]
We're trying to use Code Pitching feature (dropping unused jitted code) (https://github.com/dotnet/coreclr/pull/10496) for mobile devices.  I've found also that ```EHInfo``` and ```GCInfo``` could be pitched also at the same time. Could you give us some hints, what information (meta) for method could be pitched with code? Thanks in advance
CC:@noahfalk  @jkotas @janvorli @Dmitri-Botcharnikov @alpencolt

**Comment by noahfalk** [comment]
I'd expect with some work you should be able to get rid of everything you find in the CodeHeader: the jitted code, EHInfo, GCInfo, and DebugInfo.

LCG doesn't currently delete EHInfo, GCInfo, or DebugInfo and the comments in the code don't give any rationale why not. Its possible this was just an optimization the original authors didn't get time to implement or maybe there are thornier technical problems lurking. Conceptually EHInfo would only be used when handling an exception in a method, GCInfo would be used when the method is on the stack during a GC and DebugInfo is used by a debugger to inspect the method + when the in process System.Diagnostics.StackTrace class sees the method on the stack. Proving the method is not on the stack would theoretically eliminate everything but the debugger. In practice the line might be blurrier and it would require code review to identify how references to those datastructures may have been propagated and used.

**Comment by jkotas** [comment]
> LCG doesn't currently delete EHInfo, GCInfo

LCG does delete EHInfo and GCInfo.

**Comment by noahfalk** [comment]
Sorry, I misspoke. I should have said LCG doesn't delete those things at the same time it deletes the code, and the comments don't say why the delete is being delayed, only that it is:

https://github.com/dotnet/coreclr/blob/master/src/vm/codeman.cpp#L3169

        FreeCodeMemory(pHeap, codeStart);

        // We are leaking GCInfo and EHInfo. They will be freed once the dynamic method is destroyed.

        return;

**Comment by sergign60** [comment]
@noahfalk @jkotas Thanks!

**Comment by RussKeldorph** [comment]
@sergign60 Can this issue be closed, or is there more info you're looking for?

**Comment by RussKeldorph** [comment]
Re-open or create new issue if this isn't sufficiently answered.
