### ISSUE TITLE
Process.Start fails to execute properly

### ISSUE THREAD

**Issue by victorsample** [dotnet/coreclr#16399]
Using Visual Studio 2017 Community
Process.Start (<name>,<command_line)
fails to execute properly.
Trying to start Postgresql utility "psql" with command line "-U aobadmin aobdb <C:\\Temp\\backupdb.sql" does not execute properly.
Putting the execution in a ".bat" file and building the command line in the bat file does work.
Apparently the form of the "psql" command is causing a problem.

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#27165
