### ISSUE TITLE
Seemingly different behavior of System.Runtime.Loader on Windows and Linux while trying to load analyzer assemblies in Roslyn

### ISSUE THREAD

**Issue by agocke** [dotnet/coreclr#1640]
Repro: If you clone my branch of Roslyn at https://github.com/agocke/roslyn/tree/CoreClrAnalyzerLoadFailure and run "./cibuild" and record all the output you will see a bunch of warnings about being unable to load analyzer assemblies. I've attempted to add print statements to instrument the compiler to give more information about the load failure.

Short description of the problem, as far as I see it:

On Linux, and only on Linux, when Roslyn attempts to load any analyzer assembly using the CoreClrAnalyzerLoader (built off of AssemblyLoadContext) the CLR produces an exception while attempting to load the Microsoft.CodeAnalysis DLL, e.g.

```  
CSC : warning CS8032: An instance of analyzer Roslyn.Diagnostics.Analyzers.CSharp.CSharpDoNotCallContinueWithWithoutTaskSchedulerAnalyzer cannot be created from /home/andy/.nuget/packages/Microsoft.Net.RoslynDiagnostics/1.1.1-beta1-20150818-01/tools/Roslyn.Diagnostics.Analyzers.CSharp.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). [/home/andy/code/roslyn/src/Compilers/Core/Portable/CodeAnalysis.csproj]
```

From what I can tell, this HRESULT indicates that we are attempting to load Microsoft.CodeAnalysis, even though it is already loaded. This seems like a sensible limitation, but when I've instrumented the Loader type to print all attempted loads to stderr, I see no information that Microsoft.CodeAnalysis was previously loaded nor had been requested to be loaded. It's possible that it's being loaded as a dependency of Csc before we have a change to set the default loader, but we're currently setting the default loader in Main (https://github.com/agocke/roslyn/blob/CoreClrAnalyzerLoadFailure/src/Compilers/CSharp/CscCore/Program.cs).

I'm not exactly sure if this is a bug, or by design, but it seems strange that it's different on Linux and Windows. If it is by design I would be grateful for some guidance on what the 'safe' loader code would look like, here.

**Comment by jkotas** [comment]
cc @kouvel

**Comment by kouvel** [comment]
There were two issues:
- The version of the built MS.CodeAnalysis.dll was 0.0.0.0, while 1.0.0.0 was requested in the assembly reference. @agocke has fixed this.
- The built MS.CodeAnalysis.dll was not signed and didn't have a PKT, while the assembly reference to it specified a PKT. It was determined that CoreCLR should not require the PKT to match to successfully bind to an assembly on the TPA list. I'm sending out a PR for this change shortly.
