### ISSUE TITLE
GCProfileWalkHeapWorker - Enable the function usage on Linux

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#1641]
As part of the work which enabled FEATURE_EVENT_TRACE for Linux, it was found that the function 
GCProfileWalkHeapWorker [src/gc/gcee.cpp]  does not work properly to emit GC dump events.

This is because it  needs functionality that is defined only under macro GC_PROFILING, this macro and associated files are not being pulled in as part of the Linux build process.

Please do the right thing to get the function working properly,

NOTE: this issue is actionable on completion of  https://github.com/dotnet/coreclr/pull/1598

**Comment by adityamandaleeka** [comment]
Having looked at this, it appears that `GCProfileWalkHeapWorker` has enough implicit dependencies on `PROFILING_SUPPORTED` that it makes sense to wait to enable this until the work to turn on `PROFILING_SUPPORTED` is complete.

Selectively enabling some things that are currently under `PROFILING_SUPPORTED` will require carefully untangling several functions and global state variables, and will complicate things when `PROFILING_SUPPORTED` is really being enabled.

**Comment by lt72** [comment]
Plans around profiling on Linux have changed drastically, so this issue is not relevant any longer.
