### ISSUE TITLE
Refactor code writing directly to the event stream 

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#1642]
This issues was identified as part of #1598  
[src/vm/eventtrace.cpp](https://github.com/dotnet/coreclr/blob/master/src/vm/eventtrace.cpp)
The following functions writing directly to the ETW event stream, they need to be refactored so that they are portable across different logging systems
i.	BulkComLogger::FlushRcw()
ii.	BulkComLogger::FlushCcw()
iii.	BulkStaticsLogger::FireBulkStaticsEvent()
iv.	BulkTypeEventLogger::FireBulkTypeEvent()

**Comment by wtgodbe** [comment]
@ramarag was this achieved by https://github.com/dotnet/coreclr/pull/1751 and/or https://github.com/dotnet/coreclr/pull/1598?

**Comment by ramarag** [comment]
#1751 addresses the issue of managed code logging events, while #1598 addresses a schema based logging events in the VM. the schema is present in [ClrEtwAll.man
](https://github.com/dotnet/coreclr/blob/master/src/vm/ClrEtwAll.man)

This issue is specific for  logging specific events[listed above].  These have a complicated schema that were not specified at compile time for ETW and instead are directly write to the event stream.

**Comment by wtgodbe** [comment]
This appears to be a non-issue - no writing occurs unless m_currRcw is incremented from its initial value of 0, which only happens inder #ifdef FEATURE_COMINTEROP, which is not defined on non-Windows. I checked with @yizhang82 and he agrees - I believe this can be closed.
