### ISSUE TITLE
[Arm64] CompareExchange/Exchange `Object`/`IntPtr` needs to mark card tables et. al.

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#16446]
The following interlocked methods are not updating GC card tables when writing objects/pointers
```
public static extern Object CompareExchange(ref Object location1, Object value, Object comparand);
public static extern IntPtr CompareExchange(ref IntPtr location1, IntPtr value, IntPtr comparand);
public static extern Object Exchange(ref Object location1, Object value);
public static extern IntPtr Exchange(ref IntPtr location1, IntPtr value);
```

It is not clear to me why this is not a problem for other platforms.

To get this to work, I think we need a helper like JIT_WriteBarrier which does not write, but only updates the GC card tables and associated structures.We also may need to make the write to marking GC tables non-interruptible.  I think I will need a bit of design advice.

@jkotas @Maoni0 @dotnet/jit-contrib @dotnet/arm64-contrib

**Comment by mikedn** [comment]
`IntPtr` overloads have nothing to do with GC, `IntPtr` is basically an integer. `Object` overloads should already call native functions such as https://github.com/dotnet/coreclr/blob/e3562c9bcc92ec04eec97cf1a945e7ea6d5234d2/src/vm/comutilnative.cpp#L1810
These do have write barriers.

**Comment by sdmaclea** [comment]
Thanks @mikedn 
So 
`
        97FFE334          bl      System.Threading.Interlocked:CompareExchange(byref,ref,ref):ref
`

Is actually a call to `COMInterlocked::CompareExchangeObject` because of 
```
FCFuncElementSig("CompareExchange",&gsig_SM_RefObj_Obj_Obj_RetObj,COMInterlocked::CompareExchangeObject)
```
