### ISSUE TITLE
[ARM/Linux] Thread.Name behavior

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#16449]
I'm trying to set `Thread.Name` before thread is being started. But it doesn't work this way, I can change `Name` only from created thread. Please look to sample:
```C#
using System;
using System.Threading;
class Sample
{
    private Thread t;
    private void Runner()
    {
        // Changes are being applied if I set Name there
        // Thread.CurrentThread.Name = "MyThread2";
        while (true)
        {
            Console.WriteLine("Thread " + Thread.CurrentThread.Name + " is alive");
            Thread.Sleep(1000);
        }
    }

    public void Start()
    {
        t = new Thread(Runner);
        t.Name = "MyThread";
        t.Start();
    }

    public static int Main()
    {
        new Sample().Runner();
        return 100;
    }
}
```

Is this code correct or there is bug? Used commit:
```
commit cc4ac534127c73fd45d6ecd1b6ca62af77626ebb
Merge: 73a175f 023b4cf
Author: Carol Eidt <carol.eidt@microsoft.com>
Date:   Thu Feb 15 07:30:29 2018 -0800

    Merge pull request #16160 from sdmaclea/PR-ARM64-SIMD-INSERT
    
    [Arm64] Implement Simd.Insert
```
cc @dotnet/arm32-contrib

**Comment by lt72** [comment]
@kouvel PTAL

**Comment by kouvel** [comment]
I'm suspecting that the thread instance the name is set on is not the same as the thread instance returned by CurrentThread, which should not be the case, would you be able to verify if that's the issue? It seems to be working on x64 Windows/Linux, for now I have added similar tests that were missing in CoreFX and put it on the CI to see if it fails anywhere.

**Comment by alpencolt** [comment]
`Main()` function is incorrect. Sorry my mistake.
