### ISSUE TITLE
`Vector2.Equals()` returning incorrect result, when nested + optimization disabled

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/coreclr#16443]
### Symptom
On my machine `Vector2.Equals(Vector2 other)` returns false negatives when the following conditions are met:
- `Vector2` is nested into another struct on the stack
- Optimization is disabled (eg: a Debug build)
- Running on RyuJIT runtime, having `Vector.IsHardwareAccelerated == true`

I do not experience this issue with `Vector3` or `Vector4`.

### System configuration
- CPU: Intel® Core™ i7-7700HQ
- OS: Microsoft Windows 10 Home | 10.0.16299 Build 16299
- Environment.Version: 4.0.30319.42000
- `dotnet --version`: 2.1.2

### Steps to reproduce
[Here is](https://github.com/antonfirsov/NetCore2NumericsBugProbably/blob/master/VectorEqualityConsole/Program.cs) my sample application capable to reproduce the issue.
The results of several experiments on my machine:
```
dotnet run -c Debug -f netcoreapp2.0
Environment.Version: 4.0.30319.42000 | Vector.IsHardwareAccelerated:True
Expected: True | Actual: False

dotnet run -c Release -f netcoreapp2.0
Environment.Version: 4.0.30319.42000 | Vector.IsHardwareAccelerated:True
Expected: True | Actual: True

dotnet run -c Debug -f net461
Environment.Version: 4.0.30319.42000 | Vector.IsHardwareAccelerated:True
Expected: True | Actual: False

dotnet run -c Release -f net461
Environment.Version: 4.0.30319.42000 | Vector.IsHardwareAccelerated:True
Expected: True | Actual: True
```

**Comment by mikedn** [comment]
Hrm, it looks like the JIT uses `movups` to load `Vector2` values from local variables and thus ends up with 8 bytes of data and 8 bytes of garbage:
```asm
C4E1781045E8         vmovups  xmm0, qword ptr [rbp-18H] ; should have been vmovsd
C4E178104DE0         vmovups  xmm1, qword ptr [rbp-20H] ; should have been vmovsd
C4E17828D0           vmovaps  xmm2, xmm0
C4E168C2D100         vcmpps   xmm2, xmm1, 0
```
