### ISSUE TITLE
Versioning multiple projects

### ISSUE THREAD

**Issue by RickZeeland** [dotnet/coreclr#16469]
Can anyone tell me if it is possible to use the old trick with one _versioninfo.cs_ file linked to multiple projects in .NET Core and .NET Standard.
If not possible, it would be nice if this feature was added, this would save us a lot of work in a solution with hundreds of projects.
See article here for an explanation: [https://www.codeproject.com/Articles/18302/How-to-Keep-Your-Sanity-and-Multiple-Projects-Vers](url)

**Comment by Joe4evr** [comment]
Your link isn't linking right.

But for that, it's better to use a `Common.props` file:
```xml
<Project>
  <PropertyGroup>
    <VersionPrefix>1.2.3</VersionPrefix>
    <VersionSuffix>abc</VersionSuffix>
    <!-- etc.... -->
  </PropertyGroup>
</Project>
```
Then in your .csproj, add `<Import Project="..\..\Common.props" />` right after the `<Project>` element opener.

**Comment by RickZeeland** [comment]
Thanks a lot for your speedy reply, gonna give it a try !
Here is the link again: [CodeProject](https://www.codeproject.com/Articles/18302/How-to-Keep-Your-Sanity-and-Multiple-Projects-Vers)

**Comment by RussKeldorph** [comment]
I believe this question is more appropriate in another repo; perhaps [dotnet/cli](https://github.com/dotnet/cli).  Please open an issue there if this question isn't sufficiently answered.  Thanks!
