### ISSUE TITLE
[Arm64/Ubuntu] GCStress = 0x4/0x8/0xC/0xF Regression

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#16471]
I am seeing ~10K new GCStress failures on a231c3a.  Problem did not exist on 5d023ebe

Looking at the logs, I would guess this was introduced by #16384 

I would guess this is not Arm64 or Ubuntu specific.

@jkotas @janvorli @mlabiuk 
@dotnet/jit-contrib @dotnet/arm64-contrib

**Comment by mlabiuk** [comment]
Could you provide logs and how to reproduce test? Link to CI build?

**Comment by sdmaclea** [comment]
This is my the log from 
`JIT/CodeGenBringUpTests/Add1/Add1.sh`
```
corerun Add1.exe

Assert failure(PID 12683 [0x0000318b], Thread: 12683 [0x318b]): 
!CREATE_CHECK_STRING(pMT && pMT->Validate())
    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/vm/object.cpp Line: 733
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/corerun
```

You should be able to reproduce locally by setting one of: 
`export COMPlus_GCStress=F`
`export COMPlus_GCStress=C`
`export COMPlus_GCStress=8`
`export COMPlus_GCStress=4`

The assertion above typically indicates that the GC either:
+ Moved an object without finding and updating all the references to the object
+ Deleted an object because it failed to find all the references to the object

@Maoni0 @swgillespie FYI

**Comment by sdmaclea** [comment]
You should be able to trigger an x64 gcstress=0xc CI run with something like 
`@dotnet-bot test Ubuntu x64 Checked gcstress0xc`

**Comment by Maoni0** [comment]
@RussKeldorph, could someone from your team take a look at these GCStress failures from jit tests?

**Comment by BruceForstall** [comment]
@Maoni0 It's almost certainly a regression due to VM change #16384, not a JIT change, according to @sdmaclea 's investigation. Someone could verify that.

**Comment by janvorli** [comment]
Ah, I can see there is a bug that I've missed during the PR. The signalContextRecord is left uninitialized, no wonder it causes the crashes. @mlabiuk I'm going to send out a PR with a fix.

**Comment by janvorli** [comment]
Oh, I was just seeing things. It seems actually correct. Sorry for the false alarm.

**Comment by janvorli** [comment]
So there actually is a bug, but more subtle. I'll create a PR with a fix.

**Comment by sdmaclea** [comment]
FWIW I did run gcStress0xc on  `a231c3a~1` and it was working well.

**Comment by janvorli** [comment]
I've merged the fix in. It took more than 24 hours to run the CI gcstress0xc job.
