### ISSUE TITLE
Can't find src/Native/build.sh

### ISSUE THREAD

**Issue by ZhichengZhu** [dotnet/coreclr#1647]
Hi Team,
I followed this instruction(https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md) to build the coreclr. But so far seems there is a problem about the building Native Component:
ellismg@linux:~/git/corefx$ 
ellismg@linux:~/git/corefx$ cp bin/Linux.x64.Debug/Native/*.so ~/coreclr-demo/runtime

Seems there is no build.sh corefx/src/Native. Do we have any idea about how to build it?
Thanks,
Zhicheng Zhu

**Comment by akoeplinger** [comment]
See https://github.com/dotnet/coreclr/pull/1625 for some corrections to the docs.

**Comment by gitchomik** [comment]
See #1601, https://github.com/dotnet/corefx/commit/5361c0f77facc1f113bee68bd4b184cad0fdd7be, https://github.com/dotnet/corefx/commit/425d47f8494b2c2a4414efd799e65fb6b58cc9f7

**Comment by adityamandaleeka** [comment]
This has been fixed with https://github.com/dotnet/coreclr/commit/38787b0d6802eb6138b9ea1653d6fa8ed8063a42
