### ISSUE TITLE
Publish symbols using Microsoft.SymbolUploader.Build.Task package

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#16482]
The `Microsoft.SymbolUploader.Build.Task` package on the BuildTools feed is the new way to index and publish symbols to the symbol server. It should be used instead of the current combination of BuildTools' `GetAllSymbolFilesToPublish` and the VSTS symbol publish build step.

Example implementation in Core-Setup: https://github.com/dotnet/core-setup/pull/3465

**Comment by mikem8361** [comment]
I haven't been able to test this (all the changes are done) because the coreclr pipe build hasn't passed in a week or so.

**Comment by RussKeldorph** [comment]
@mikem8361 Which pipebuild are you referring to?  Most of the last few official pipebuilds have succeeded. https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/buildHistory

**Comment by mikem8361** [comment]
It looks like https://devdiv.visualstudio.com/DevDiv/_build/index?context=mine&path=%5C&definitionId=1832&_a=completed is passing now. It wasn't last night or over the last two week.s

**Comment by mikem8361** [comment]
Still failing when I launch DotNet-CoreClr_PipeBuild-Master with my branch: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1513433&_a=summary

It looks like it was the orchestrated builds that were succeeding.

**Comment by dagood** [comment]
It looks like the failures are because you queued it with a container name with a `/` in it: https://blogs.msdn.microsoft.com/jmstall/2014/06/12/azure-storage-naming-rules/

**Comment by mikem8361** [comment]
I’m not sure what that means or how I did it.  I just queued DotNet-CoreClr-PipeBuild-Master with Branch = “mikem/uploader” which is my changes in the DotNet-CoreCLR-Trusted repo.

**Comment by mikem8361** [comment]
PB_ContainerName is set to "coreclr-$(Branch)-$(OfficialBuildId)" which means I can't have "mikem/" in my branch name. I'll fixed that.

**Comment by dagood** [comment]
I see, didn't realize how the dev branch build flow works. I remember some discussion about having the def automatically convert `/` to `-`, but I guess that wasn't implemented.

**Comment by mikem8361** [comment]
Not needed for 2.1.

**Comment by mikem8361** [comment]
PR #17463.
