### ISSUE TITLE
Change file names of template-driven HW intrinsic tests

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#16509]
Currently, the template-driven tests have file names with the pattern "Intrinsic.Base.cs". However, certain AVX/AVX2/FMA intrinsic can operate over `Vector128<T>` and `Vector256<T>` both.
So the test files should be changed to "Intrinsic.Vector128/256\<Base\>.cs".

I will make this change after https://github.com/dotnet/coreclr/pull/16183 merged.

cc @tannergooding @CarolEidt

**Comment by tannergooding** [comment]
To be more precise, it is currently `Intrinsic.RetBaseType`.

Changing it to `Intrinsic.RetVectorType_RetBaseType` (or something similar) sounds good to me.

Do we know if there are any intrinsics where they need to differentiate based on parameter types as well? (It would be good to support that scenario as well, if it needs it).

**Comment by fiigii** [comment]
> Do we know if there are any intrinsics where they need to differentiate based on parameter types as well?

Did not see. If there is, they are very minority. We can specially treat them.

**Comment by tannergooding** [comment]
@fiigii, I think the simplest way to deal with this will be to add a new field to the Inputs that specifies the file name.

That is, each entry is currently `(string templateFileName, string[] templateData)`. We could change that to `(string templateFileName, string generatedFileName, string[] templateData)`.

We can use the existing logic for `string.IsNullOrEmpty(generatedFileName)`.

**Comment by tannergooding** [comment]
That will cover generation for the 99% and the customization, if required, for the minority cases that result in conflicts.

**Comment by fiigii** [comment]
@tannergooding Sounds good!
