### ISSUE TITLE
[Arm64/Ubuntu] ZapDisable fails

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#16519]
The following tests fail in the zapdisable test configuration.  `ZapDisable=1` `ReadyToRun=0`
```
baseservices/exceptions/regressions/V1/SEH/VJ/NestedEx1/NestedEx1.sh
readytorun/tests/mainv1/mainv1.sh
readytorun/tests/mainv2/mainv2.sh
```

@dotnet/arm64-contrib @dotnet/jit-contrib 

The readytorun failures might be expected.

**Comment by BruceForstall** [comment]
I wonder if these are recent regressions, or Linux specfic (I assume you tested Linux); the last CI runs have been clean, but it's only run once a week: https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_zapdisable_flow/

**Comment by sdmaclea** [comment]
>  recent regressions, or Linux specfic

I do not know, it was the first time I had run that job in a long time.

**Comment by sdmaclea** [comment]
@BruceForstall 
I just reran these on master tip to gather logs.  
I did not see the `baseservices/exceptions/regressions/V1/SEH/VJ/NestedEx1/NestedEx1.sh`

The `mainv1/mainv2` failures are crossgen failures.
```
Could not load file or assembly '/home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/System.Private.CoreLib.dll'. An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B (COR_E_BADIMAGEFORMAT))
Error: compilation failed for "test.dll" (0x8007000b)
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Could not load file or assembly '/home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/System.Private.CoreLib.dll'. An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B (COR_E_BADIMAGEFORMAT))
Error: compilation failed for "fieldgetter.dll" (0x8007000b)
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Could not load file or assembly '/home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/System.Private.CoreLib.dll'. An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B (COR_E_BADIMAGEFORMAT))
Error: compilation failed for "mainv1.exe" (0x8007000b)
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

/usr/bin/time /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/corerun mainv1.exe

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly '/home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/readytorun/tests/mainv1/test.ni.dll'. The system cannot find the file specified.
```

I use crossgen in my workflow all the time so I am certain it generally works.  I regularly crossgen S.P.C.dll and every dll from corefx.

In the past, I had seen the if S.P.C.dll was crossgened and renamed to S.P.C.dll (like it is supposed to be), then crossgen stopped working.  Given the logs that is likely the root cause.

**Comment by sdmaclea** [comment]
```
  <BashCLRTestPreCommands><![CDATA[
$(BashCLRTestPreCommands)
rm -f test.dll
cp ../testv1/test/test.dll test.dll
$CORE_ROOT/crossgen -readytorun -platform_assemblies_paths $CORE_ROOT:`pwd` -out test.ni.dll test.dll
$CORE_ROOT/crossgen -readytorun -platform_assemblies_paths $CORE_ROOT:`pwd` -out fieldgetter.ni.dll fieldgetter.dll
$CORE_ROOT/crossgen -readytorun -platform_assemblies_paths $CORE_ROOT:`pwd` -out mainv1.ni.exe mainv1.exe
]]></BashCLRTestPreCommands>
```

Also note the crossgen errors are ignored...

**Comment by sdmaclea** [comment]
FWIW I see the same thing in `master` and `release 2.1` branch tips

**Comment by BruceForstall** [comment]
AFAIK, mainv1 and mainv2 are the only R2R tests in the "normal" test run.

Related:

Looks like we have lots of arm64 R2R jobs defined in the CI, but they've never run: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/

Looks like the Windows "baseline" arm64 R2R test has basically never passed, with about 3 failures now:
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/arm64_cross_checked_windows_nt_r2r_tst/

**Comment by BruceForstall** [comment]
@sdmaclea Is this still an issue? Can you check your Linux runs?

**Comment by sdmaclea** [comment]
I am no longer seeing these failures.
