### ISSUE TITLE
Windows debug and release CI builds failing on PRs.

### ISSUE THREAD

**Issue by Priya91** [dotnet/coreclr#1652]
cc @mmitche 
```
"d:\j\workspace\dotnet_coreclr_windows_release_prtest\bin\obj\Windows_NT.x64.Release\install.vcxproj" (default target) (1) ->
18:39:20        "D:\j\workspace\dotnet_coreclr_windows_release_prtest\bin\obj\Windows_NT.x64.Release\ALL_BUILD.vcxproj" (default target) (2) ->
18:39:20        "D:\j\workspace\dotnet_coreclr_windows_release_prtest\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\coreclr.vcxproj" (default target) (20) ->
18:39:20        "D:\j\workspace\dotnet_coreclr_windows_release_prtest\bin\obj\Windows_NT.x64.Release\src\binder\v3binder\v3binder.vcxproj" (default target) (57) ->
18:39:20          C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\CodeAnalysis\Microsoft.CodeAnalysis.targets(214,5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Build.Tasks.Core.dll". Could not find file 'C:\Users\dotnet-bot\AppData\Local\Temp\leshgc0u.dll'. [D:\j\workspace\dotnet_coreclr_windows_release_prtest\bin\obj\Windows_NT.x64.Release\src\binder\v3binder\v3binder.vcxproj]
18:39:20 
18:39:20 
18:39:20        "d:\j\workspace\dotnet_coreclr_windows_release_prtest\bin\obj\Windows_NT.x64.Release\install.vcxproj" (default target) (1) ->
18:39:20        "D:\j\workspace\dotnet_coreclr_windows_release_prtest\bin\obj\Windows_NT.x64.Release\ALL_BUILD.vcxproj" (default target) (2) ->
18:39:20        "D:\j\workspace\dotnet_coreclr_windows_release_prtest\bin\obj\Windows_NT.x64.Release\src\dlls\dbgshim\dbgshim.vcxproj" (default target) (60) ->
18:39:20        "D:\j\workspace\dotnet_coreclr_windows_release_prtest\bin\obj\Windows_NT.x64.Release\src\debug\shim\debugshim.vcxproj" (default target) (61) ->
18:39:20          C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\CodeAnalysis\Microsoft.CodeAnalysis.targets(214,5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Build.Tasks.Core.dll". Could not find file 'C:\Users\dotnet-bot\AppData\Local\Temp\24mrskrb.dll'. [D:\j\workspace\dotnet_coreclr_windows_release_prtest\bin\obj\Windows_NT.x64.Release\src\debug\shim\debugshim.vcxproj]
```

**Comment by mmitche** [comment]
@Priya91 I am 90% sure this is an MSBuild bug caused by a race in the CodeTaskFactory target.

**Comment by ellismg** [comment]
Have we engaged with the MSBuild folks?

**Comment by mmitche** [comment]
@ellismg Yes.  They didn't know what was going on.  I actually remember seeing this all the way back in the MIdori days.  My thoughts are that we should check in nuget.exe like Roslyn does and remove the initial code task factory.  What do you think?

**Comment by joshfree** [comment]
@weshaggard can you follow up with msbuild?

**Comment by mmitche** [comment]
@joshfree I contacted them a while back about this.  They have not heard of such a failure.  In addition, it probably doesn't help us to even have a fix right now (except for future releases) since we wouldn't get the fix in stock VS 2015 MSBuild.

**Comment by mmitche** [comment]
@AndyGerlicher I am seeing this more, and I am noticing a potential pattern:  When the TEMP dir has a very large amount of files (30k+), the frequency of this bug appears to increase.

**Comment by kitplummer** [comment]
I'm seeing the same issue - only from CI (GoCD in my case).  If I run the same command from PowerShell directly it works.  I've also noticed that the 'temp' file it's looking for doesn't exist...the AppData\local\TEMP directory doesn't exist either.

**Comment by mmitche** [comment]
@kitplummer The machines now clean %TEMP% every few hours if idle, so that's likely the reason you're seeing an empty TEMP.  Those files should get deleted at the end of an msbuild invocation anyway.  Anyways, I'm trying to track down an instance of this in the wild, so let me know if you see an instance in your PR as soon as possible.

**Comment by kitplummer** [comment]
@mmitche - I didn't even have the \Temp subdirectory.  Creating it manually got me to the next error...where msbuild can't find some RSP files.

```
18:25:14.207   Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23026 for x86
18:25:14.207   Copyright (C) Microsoft Corporation.  All rights reserved.
18:25:14.207   
18:25:14.207 cl : Command line error D8022: cannot open 'C:\Windows\system32\config\systemprofile\AppData\Local\Temp\tmpbbe76a1f33584aac8e159f8752b45233.rsp' [C:\goagent\pipelines\libpng\projects\vstudio\zlib\zlib.vcxproj]
```

**Comment by mmitche** [comment]
Can you take that machine offline?  That is not where the temp dir should be at all.  Should be under users.  I wonder whether the user profile got corrupted.

Sent from my Windows Phone
________________________________

**Comment by kitplummer** [comment]
I can, and have restarted the machine a couple of times.  I'd wondered about the profile too...as it was something that I've messed with a lil bit, in order to run PS stuff earlier in my CI process.  But, I think I've cleared all of that out.  Sorry to have hijacked your issue...but figured since I was seeing the same thing figured I'd chime in.  I'm open to troubleshooting on my side if that helps you at all.

**Comment by mmitche** [comment]
Errr. okay.  What machine was that?  What do you mean by "earlier in the CI process"?

**Comment by kitplummer** [comment]
This is a Windows 2012 Server R2 machine, with Visual Studio 2015 Community Edition installed on it.  I'm using GoCD and so there's the agent installed and running as a service.  

Before the msbuild command gets called, I have a step that downloads a source code zip file, and extracts it.  Those tasks are executed through PowerShell, which requires some tweaking of the local profile.

Part of my issue could be that the project I'm trying to build is set up to target VS2010, so I'm changing that with the call to 'msbuild':

```
msbuild /p:PlatformToolset=v140 /toolsversion:14.0
```
This is all new territory for me, so I'm not sure what is happening when the GoCD agent calls it, versus me in PowerShell directly.

**Comment by mmitche** [comment]
Oh oh. okay.  This is not something attached to the main CI.  Okay.  I'm not familiar with GoCD unfortunately.

**Comment by akoeplinger** [comment]
@kitplummer I think you're hitting the same issue as https://github.com/Microsoft/msbuild/issues/185, the problem seems to be GoCD running the service as SYSTEM which causes all sorts of problems.

**Comment by kitplummer** [comment]
@akoeplinger - Thanks a ton!!!  @mmitche was close - it is the Temp\ subdirectory that is the issue.  If I just set ENV vars for TEMP and TMP - to something sane, my msbuild run works.

**Comment by jasonwilliams200OK** [comment]
Happened again in #6634.
@mmitche, this issue was closed, but is there an issue tracking this at: https://github.com/Microsoft/msbuild/issues. If not, should I do the honors? :)

**Comment by weshaggard** [comment]
@jasonwilliams200OK yes please do the honors. I saw this issue here http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/windows_nt_debug_prtest/351/console as well.

**Comment by jasonwilliams200OK** [comment]
@weshaggard, also: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x86_lb_checked_windows_nt_prtest/2829/, which is complaining about `XamlTaskFactory` instead.

**Comment by jasonwilliams200OK** [comment]
Upstream issue: #899.

**Comment by mmitche** [comment]
They are the same failure, relating to code compiled dynamically by msbuild during the build.
