### ISSUE TITLE
[RyuJIT] Update emitter to support SSE2 SIMD shift instructions 

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#16543]
SSE2 SIMD shift instructions have special encoding that left and right shift shares same opcode (distinguished by the `Reg/Opcode` field). Now, `emitter::emitOutputRI` deals with these instructions, but it should be improved.
1. these shift instructions should be addressed by `emitIns_R_R_I` as well, which leverages VEX.NDS (non-destructive source) encoding.
2. `emitOutputRI` cannot work with `psrldq`/`pslldq` on `imm8` > 127.

cc @CarolEidt @tannergooding

**Comment by mikedn** [comment]
> emitOutputRI cannot work with psrldq/pslldq on imm8 > 127

Hmm, why do you need that?

**Comment by tannergooding** [comment]
I think this is just a casting problem, but I am waiting to here back from @fiigii.

See https://github.com/dotnet/coreclr/pull/16183#discussion_r170408497 for more details
