### ISSUE TITLE
[Arm64] Enable CLR implemented write watch on ARM64 on Windows.

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#16544]
See  #16516

Might be partially dependent on  #13592

**Comment by BruceForstall** [comment]
@adityamandaleeka You've fixed a number of Windows/Linux arm64 parity issues. Do you want to take this one, too?

**Comment by RussKeldorph** [comment]
@adityamandaleeka Is this likely to be implemented for 3.0?  If not, could you move it to Future?

**Comment by adityamandaleeka** [comment]
@RussKeldorph I do believe this will make it in. I implemented it last week and am just waiting to get some more perf data before I make the go/no-go call.

If that doesn't happen today or tomorrow, I'll go ahead and move this to future.

**Comment by adityamandaleeka** [comment]
PR is out: https://github.com/dotnet/coreclr/pull/23752

**Comment by adityamandaleeka** [comment]
This is done.
