### ISSUE TITLE
netstandard deps.json and the netfx gac are not compatible

### ISSUE THREAD

**Issue by ForkBug** [dotnet/coreclr#16569]
I create a windows C# project A. A refers to netstandard project B. B refers to a couple of nuget, like C,D,E.
The problem is, C,D,E couldn't be found in A's project output folder. They have to be copied manually.

The root cause may be the netstandard deps.json and the netfx gac are not compatible. Core/netstandard use another way to find dependencies.

Recursive copy referred netstandard dll to VS output folder, may fix this problem. But it mostly like a workaround

**Comment by jkotas** [comment]
This issue was moved to dotnet/sdk#1996
