### ISSUE TITLE
CoreMangLib System.Single.GetHashCode is failing

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#16566]
This test is sporadically failing based on the seed it starts with.

See https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitincompletehwintrinsic_prtest/118/testReport/CoreMangLib_cti/_system_single_SingleGetHashCode_SingleGetHashCode_/_system_single_SingleGetHashCode_SingleGetHashCode_cmd/ for more details.

**Comment by tannergooding** [comment]
CC. @jkotas

**Comment by tannergooding** [comment]
Also failed:
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitx86hwintrinsicnosimd_prtest/128/testReport/CoreMangLib_cti/_system_single_SingleGetHashCode_SingleGetHashCode_/_system_single_SingleGetHashCode_SingleGetHashCode_cmd/
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitx86hwintrinsicnoavx2_prtest/112/testReport/CoreMangLib_cti/_system_single_SingleGetHashCode_SingleGetHashCode_/_system_single_SingleGetHashCode_SingleGetHashCode_cmd/
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitincompletehwintrinsic_prtest/130/testReport/CoreMangLib_cti/_system_single_SingleGetHashCode_SingleGetHashCode_/_system_single_SingleGetHashCode_SingleGetHashCode_cmd/
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitx86hwintrinsicnosimd_prtest/125/testReport/CoreMangLib_cti/_system_single_SingleGetHashCode_SingleGetHashCode_/_system_single_SingleGetHashCode_SingleGetHashCode_cmd/
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitx86hwintrinsicnoavx2_prtest/123/testReport/CoreMangLib_cti/_system_single_SingleGetHashCode_SingleGetHashCode_/_system_single_SingleGetHashCode_SingleGetHashCode_cmd/
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt_prtest/3316/testReport/CoreMangLib_cti/_system_single_SingleGetHashCode_SingleGetHashCode_/_system_single_SingleGetHashCode_SingleGetHashCode_cmd/
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitx86hwintrinsicnoavx_prtest/122/testReport/junit/CoreMangLib_cti/_system_single_SingleGetHashCode_SingleGetHashCode_/_system_single_SingleGetHashCode_SingleGetHashCode_cmd/

**Comment by mikedn** [comment]
I don't see why the test is flaky, the part that fails is not random. It's simply that the hashcode of `Single.NaN` has changed.

**Comment by tannergooding** [comment]
@mikedn, your right.

For a single PR, I had 15 jobs pass, 15 jobs fail, and saw the test failure mention that it uses `CORE_SEED`.

I had assumed this meant flaky, but it is actually just a deterministic failure in the pri-1 tests.
