### ISSUE TITLE
[Perf] Investigate BenchF/BenchMk Regression between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#16579]
We regressed 25%.

**Comment by adiaaida** [comment]
This regression appears to be due to changes between be21b511fc3ee42a2db1c8ce70499efd8d82d37e and 8ad9cd160cbc716c87b804a47e552509c2910135 (https://github.com/dotnet/coreclr/compare/be21b511fc3ee42a2db1c8ce70499efd8d82d37e...dotnet:8ad9cd160cbc716c87b804a47e552509c2910135)

**Comment by AndyAyersMS** [comment]
2.1 codegen here exhibits the same spilling as seen in #16578.

**Comment by AndyAyersMS** [comment]
Should also be fixed by #16877.
