### ISSUE TITLE
[Perf] Investigate BenchF/BenchMk2 Regression between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#16578]
We regressed 12% on x64.

**Comment by adiaaida** [comment]
This regression appears to be due to changes between be21b511fc3ee42a2db1c8ce70499efd8d82d37e and 8ad9cd160cbc716c87b804a47e552509c2910135 (https://github.com/dotnet/coreclr/compare/be21b511fc3ee42a2db1c8ce70499efd8d82d37e...dotnet:8ad9cd160cbc716c87b804a47e552509c2910135)

**Comment by AndyAyersMS** [comment]
I'll take a look.

**Comment by AndyAyersMS** [comment]
2.0 at ~180, 2.1/master at ~205.

Only significant diff here is as follows (comes from `Math.Abs`): I think it functionally is fine because the sign bit is in the same place for the upper half of a float pair as it is for a double. But I wonder if switching from double / single / double like this introduces dependence-tracking issues in the HW that causes a performance glitch:
```diff
       C4E17B101598060205 vmovsd   xmm2, qword ptr [@RWD08]-
-       C4E17954C2   vandpd   xmm0, xmm2
+       C4E17854C2   vandps   xmm0, xmm2
       C4E17B1145F8 vmovsd   qword ptr [ebp-08H], xmm0
```
@fiigii do you know if there are possible delay issues from something like this (the `vandps` variant)?

**Comment by AndyAyersMS** [comment]
Oops, disregard the above `vandps` notes -- they are for x86 codegen.

**Comment by AndyAyersMS** [comment]
Ok, now looking at actual x64 codegen. All the action here is in `Bench`. 2.0 uses registers effectively, but master/2.1 is spilling. Not sure why just yet, will look at dumps in a bit.

Diff snippet of inner loop up to the call to `Exp`:
```asm
;;; 2.0

       C4E17B1005D24DEAFF   vmovsd   xmm0, qword ptr [reloc classVar[0x69935cb8]]
       C4E17057C9           vxorps   xmm1, xmm1
       C4E1732A0DF04DEAFF   vcvtsi2sd xmm1, dword ptr [reloc classVar[0x69935ca8]]
       C4E17B5EC1           vdivsd   xmm0, xmm1
       C4E17B1105CE4DEAFF   vmovsd   qword ptr [reloc classVar[0x69935ce8]], xmm0
       C4E17057C9           vxorps   xmm1, xmm1
       C4E1732A0DD04DEAFF   vcvtsi2sd xmm1, dword ptr [reloc classVar[0x69935c98]]
       C4E17B59C1           vmulsd   xmm0, xmm1
       C4E17B1105AA4DEAFF   vmovsd   qword ptr [reloc classVar[0x69935cd8]], xmm0
       E879E3D45F           call     Math:Exp(double):double

;; 2.1

       C4E17B10058E39EEFF   vmovsd   xmm0, qword ptr [reloc classVar[0x69924c78]]
       C4E17057C9           vxorps   xmm1, xmm1
       C4E1732A0DAC39EEFF   vcvtsi2sd xmm1, dword ptr [reloc classVar[0x69924c68]]
       C4E17B5EC1           vdivsd   xmm0, xmm1
       C4E17B11442458       vmovsd   qword ptr [rsp+58H], xmm0
       C4E17B10442458       vmovsd   xmm0, qword ptr [rsp+58H]
       C4E17B11057C39EEFF   vmovsd   qword ptr [reloc classVar[0x69924ca8]], xmm0
       C4E17857C0           vxorps   xmm0, xmm0
       C4E17B2A057E39EEFF   vcvtsi2sd xmm0, dword ptr [reloc classVar[0x69924c58]]
       C4E17B59442458       vmulsd   xmm0, qword ptr [rsp+58H]
       C4E17B11442438       vmovsd   qword ptr [rsp+38H], xmm0
       C4E17B10442438       vmovsd   xmm0, qword ptr [rsp+38H]
       C4E17B11054839EEFF   vmovsd   qword ptr [reloc classVar[0x69924c98]], xmm0
       C4E17B10442438       vmovsd   xmm0, qword ptr [rsp+38H]
       E81C18D85F           call     Math:Exp(double):double
```

**Comment by AndyAyersMS** [comment]
Looking at dumps, things seem pretty comparable until LSRA -- there is one extra integer CSE in 2.1, but the double parts seem the same.

The LSRA dumps have changed enough that I can't easily tell why the behavior is different. Michelle's analysis indicates the regression likely happened quite a while ago.

@CarolEidt do you have time to take a quick look at the 2.1 / master behavior here and see why we are spilling so much? It should be something pretty basic -- this is a single block loop with some calls.

**Comment by mikedn** [comment]
> But I wonder if switching from double / single / double like this introduces dependence-tracking issues in the HW that causes a performance glitch:

Nope, both `andps` and `andpd` are executed by the same execution unit (floating point unit on current processors). You can get into trouble only if you mix integer and floating point instructions (e.g. use `pand` instead of `andps`/`andpd`).

**Comment by fiigii** [comment]
> do you know if there are possible delay issues from something like this (the vandps variant)?

No, I did not see any related issue. Maybe @tannergooding is more familiar with `Math`.

**Comment by fiigii** [comment]
> But I wonder if switching from double / single / double like this introduces dependence-tracking issues in the HW that causes a performance glitch:

> both andps and andpd are executed by the same execution unit 

Right, this kind of state switching only exists between integer and floating units.

**Comment by fiigii** [comment]
@AndyAyersMS @adiaaida Could you provide more details of the test environment (e.g., processor and OS)?

**Comment by CarolEidt** [comment]
> @CarolEidt do you have time to take a quick look at the 2.1 / master behavior here and see why we are spilling so much? It should be something pretty basic -- this is a single block loop with some calls.

I'll take a look

**Comment by tannergooding** [comment]
> Maybe @tannergooding is more familiar with Math.

AFAIK, there weren't any related changes to System.Math.

**Comment by AndyAyersMS** [comment]
For lab perf HW: OS is Windows Server 2016, CPU is i7-4790.
