### ISSUE TITLE
reliability_stress_framework nightly config case incorrect

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#16586]
https://github.com/dotnet/coreclr/blob/master/tests/src/GC/Stress/testmix_gc.config#L40-L42

`Concurrentspin2.exe` should be `concurrentspin2.exe`.  This will cause this test to be skipped on case sensitive filesystems (Linux ...)

**Comment by sdmaclea** [comment]
@Maoni0 FYI

**Comment by Maoni0** [comment]
@sywhang would you please fix this? thanks!

**Comment by sdmaclea** [comment]
This was not fixed correctly.

**Comment by sywhang** [comment]
This should've been fixed with #16607 . Sorry for the confusion
