### ISSUE TITLE
Implement AVX helper-intrinsics and underlying intrinsics

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#16583]
I will implement AVX helper-intrinsics (e.g., `SetVector256`, `SetAllVector256`, `SetHighLow`, `StaticCast`) and underlying intrinsics (such as `BroadcastScalarToVector128`, `Sse41.Insert`).

cc @CarolEidt @tannergooding

**Comment by tannergooding** [comment]
@fiigii, could you prioritize `Sse41.Insert` and `Sse41.Extract` in their own PR first?

**Comment by fiigii** [comment]
@tannergooding Sure, will do.
