### ISSUE TITLE
[Perf] Investigate BenchI/CSieve Regression between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#16582]
We regressed 5% in release/2.1

**Comment by AndyAyersMS** [comment]
Will investigate.

**Comment by AndyAyersMS** [comment]
Assuming this was x64. Identical codegen for `Bench` in 2.0 and 2.1. 

This also seems to be alignment related, this time loop top as the method is not recursive.

Long-term behavior in master:
![image](https://user-images.githubusercontent.com/10121823/37235228-f1a06bf2-23b1-11e8-835a-800d52db1927.png)

So several stable levels at around 1080, 1095, 1145, 1160, and 1170.

2.0 has stayed at 1095 for the most part:

![image](https://user-images.githubusercontent.com/10121823/37235235-0414b2d4-23b2-11e8-9e39-a8c4bf5ab2c3.png)

2.1 was at 1095 but recently jumped up to 1145, about a 5% increase:

![image](https://user-images.githubusercontent.com/10121823/37235244-0f911670-23b2-11e8-889e-baa7b2f05a4a.png)

So nothing actionable here for 2.1. Loop alignment is a known limitation that we may address in the future in #11607.
