### ISSUE TITLE
[Perf] Investigate BenchI/Ackerman x86 Regression between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#16581]
We are regressed in x86.

**Comment by AndyAyersMS** [comment]
2.0 and 2.1 codegen is identical for both `Acker` and `Bench`.

This test is notoriously sensitive to method alignment. Let's look at the longer-term stability in master:
![image](https://user-images.githubusercontent.com/10121823/37232429-d14e8658-23a3-11e8-9db8-1d95655dd771.png)

So there seem to be 4 stable levels: 695, 720, 770, and 790.

2.0 seems to have settled in on 695:

![image](https://user-images.githubusercontent.com/10121823/37232489-12c80c9e-23a4-11e8-914a-afdde2eaf3a6.png)

2.1 started there but has jumped up to 720:

![image](https://user-images.githubusercontent.com/10121823/37232551-52843196-23a4-11e8-8522-11852310b495.png)

So I assume this perf difference is an artifact of method entry alignment. On x86 we end up aligning most jitted method entries to 8 byte boundaries, so it would appear that there is some 32-byte sensitivity here.

At some point we might want to rethink alignment, either to stabilize cases like this, or as an enabler for loop top alignment (#11607), or perhaps in general. I have opened #16873 to investigate method alignment impact.

I don't think there is anything actionable here for 2.1 so will close this issue.
