### ISSUE TITLE
[RyuJIT] adding a function for checking if a HWIntrinsicFlag is set or unset

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#16594]
https://github.com/dotnet/coreclr/pull/16183#discussion_r170726444

cc @CarolEidt @tannergooding

**Comment by CarolEidt** [comment]
@fiigii, I believe this addresses one of the TODO items from#16183, but there's not enough context here to understand the issue. Could you explain, and reference the relevant source if possible?

**Comment by fiigii** [comment]
> but there's not enough context here to understand the issue. Could you explain, and reference the relevant source if possible?

@CarolEidt 
@tannergooding suggested this improvement at https://github.com/dotnet/coreclr/pull/16183#discussion_r170726444, I think this is just a convenient function to make the code more readable.

**Comment by tannergooding** [comment]
Resolved with #18255
