### ISSUE TITLE
[Perf] Investigate Span Improvement between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/coreclr#16605]
Investigate mostly improvement and some regressions in the Span performance suite.

category:cq
theme:benchmarks
skill-level:intermediate
cost:small

**Comment by AndyAyersMS** [comment]
@DrewScoggins can you please describe the regressions in a bit more detail -- we might want to investigate these as there is still some time to fix things in 2.1.

Some improvement in span perf was expected, mainly from #10453 and #11521. It would be good to know if anything else played a role.

**Comment by DrewScoggins** [comment]
I have not done an initial triage here, just gone through the results and saw that we had some movement on the benchmarks. I can try and take a first cut at this, but it would likely not be until the end of the week.

**Comment by BruceForstall** [comment]
@DrewScoggins You assigned this issue to yourself. Do you intend to look at it, or can we close it? It's somewhat obsolete at this point.

**Comment by DrewScoggins** [comment]
We can also close this as well.
