### ISSUE TITLE
Compiler error in CentOS in ICU native shim libraries

### ISSUE THREAD

**Issue by steveharter** [dotnet/coreclr#1660]
Address compiler issue:
/src/corefx/System.Globalization.Native/calendarData.cpp:501:94: error: no member named 'SHORT' in 'icu_50::DateFormatSymbols'
                        return EnumWeekdays(locale, calendarId, DateFormatSymbols::STANDALONE, DateFormatSymbols::SHORT, callback, context);

CentOS7 is using ICU50 and the above enum value wasn't added until ICU51

**Comment by ellismg** [comment]
This is resolved now in CI.  Thanks Steve!
