### ISSUE TITLE
[Perf] Investigate LinqBenchmarks Regression between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/coreclr#16602]
Investigate the full suite of Linq benchmarks as we saw regressions across many tests as large as 5%

**Comment by AndyAyersMS** [comment]
Any progress?

**Comment by AndyAyersMS** [comment]
I took a quick look and don't see any obvious regressions. Some of the tests are super-noisy so looking at just one pair of runs may give misleading results.

For instance here is Where00ForX in master ... maybe there was a regression around 11/15 but I wouldn't be super-confident saying so.

![image](https://user-images.githubusercontent.com/10121823/37429672-49d4471a-278d-11e8-9742-2e7aabcb01b9.png)

**Comment by AndyAyersMS** [comment]
For completeness' sake, here is 2.0 over a similar time span:

![image](https://user-images.githubusercontent.com/10121823/37429859-c6c5d446-278d-11e8-8cb0-69285b8d0fe9.png)

and here is the data we have so far on 2.1 (note both axes scales differ from above):

![image](https://user-images.githubusercontent.com/10121823/37429882-d7f32d40-278d-11e8-897d-4a34054ef4fc.png)

They both bounce around a lot.  Comparing 2.0 vs 2.1 using just data from one particular pair of runs can lead to wildly different conclusions depending on which pair of measurements is chosen.

It sure would be nice to better control this run to run variation (tracked via #11656).

So, am going to close this out. If there is data I have overlooked that shows regressions, feel free to re-open.
