### ISSUE TITLE
[Perf] Investigate RayTracer Improvement between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/coreclr#16604]
We saw a 5% improvement in Raytracer and we should look into what caused this win.

category:cq
theme:benchmarks
skill-level:intermediate
cost:small

**Comment by BruceForstall** [comment]
@DrewScoggins You assigned this issue to yourself. Do you intend to look at it, or can we close it? It's somewhat obsolete at this point.

**Comment by DrewScoggins** [comment]
This should definitely be closed.
