### ISSUE TITLE
[Perf] Investigate BinaryFormatter Improvement between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/coreclr#16628]
It's up to 70% faster

**Comment by danmosemsft** [comment]
It is possible that the fix for https://github.com/dotnet/corefx/issues/25529 is part of this but it depends on the test scenario.

Which test scenario is this? Is it possible to put links to benchview graphs in these analysis issues? That would help a lot.

**Comment by adamsitnik** [comment]
After some investigation, it looks that `System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize` was 55% of the inclusive samples for `BinaryFormatter.Serialize` for 2.0.5. For the preview of 2.1 it's "only" 24%.

Visualization of the improvement (it's a Flame Graph from PerfView):
![image](https://user-images.githubusercontent.com/6011991/37028178-d2b0c604-2133-11e8-82bf-fb40f4a68547.png)

Call Tree from 2.0.5 (CoreCLR 4.6.00001.0, CoreFX 4.6.25519.03):
![image](https://user-images.githubusercontent.com/6011991/37028326-452a6244-2134-11e8-8f22-fb6b9de6266e.png)

Call Tree from 2.1 (CoreCLR 4.6.26130.05, CoreFX 4.6.26130.01):
![image](https://user-images.githubusercontent.com/6011991/37028434-881e54fc-2134-11e8-9a20-f08888d0891a.png)

When I `Drill Into` the `WriteObjectInfo.InitSerialize` I get following flame graph for 2.0.5:
![image](https://user-images.githubusercontent.com/6011991/37028672-34be4a5a-2135-11e8-9436-1ab1174a2b15.png)

And Call Tree:
![image](https://user-images.githubusercontent.com/6011991/37029625-65b651a4-2138-11e8-9a40-b1df972e5d14.png)

When I do the same for 2.1 there is no `coreclr!ReflectionInvocation::PerformVisibilityCheckOnField` on the call stack.

![image](https://user-images.githubusercontent.com/6011991/37029726-bbc56b66-2138-11e8-93cb-b964c312df81.png)

I tried to find `PerformVisibilityCheckOnField` in CoreCLR code base but I have [failed](https://github.com/dotnet/coreclr/search?q=PerformVisibilityCheckOnField). And I am very confused because it's also not present in the [2.0 branch](https://github.com/dotnet/coreclr/blob/release/2.0.0/src/vm/reflectioninvocation.cpp)

@danmosemsft who could help me to solve the mystery of `coreclr!ReflectionInvocation::PerformVisibilityCheckOnField`?


Code that I used:

```cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization.Formatters.Binary;
using System.Xml.Serialization;

namespace BinaryFormatterImprovement
{
    class Program
    {
        static void Main(string[] args)
        {
            var serializer = new BinaryFormatter();
            List<double> results = new List<double>();

            using (var memoryStream = new MemoryStream(capacity: short.MaxValue))
            {
                var value = CreateLoginViewModel();

                Benchmark(memoryStream, serializer, 1, "Warmup", value);

                for (int i = 0; i < 10; i++)
                {
                    results.Add(RealRun(memoryStream, serializer, 1000, "Actual run", value));
                }
            }

            var coreclrAssemblyInfo = FileVersionInfo.GetVersionInfo(typeof(object).Assembly.Location);
            var corefxAssemblyInfo = FileVersionInfo.GetVersionInfo(typeof(System.Text.RegularExpressions.Regex).Assembly.Location);

            Console.WriteLine($"CoreCLR {coreclrAssemblyInfo.FileVersion}, CoreFX {corefxAssemblyInfo.FileVersion}");
            Console.WriteLine($"Avg: {results.Average()}, Min: {results.Min()}, Max: {results.Max()}");
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static double RealRun(Stream stream, BinaryFormatter serializer, int invocationCount, string displayText, LoginViewModel value) => Benchmark(stream, serializer, invocationCount, displayText, value);

        private static double Benchmark(Stream stream, BinaryFormatter serializer, int invocationCount, string displayText, LoginViewModel value)
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();

            var timer = Stopwatch.StartNew();

            for (int i = 0; i < invocationCount; i++)
            {
                stream.Position = 0;
                serializer.Serialize(stream, value);
            }

            TimeSpan avg = timer.Elapsed / invocationCount;
            Console.WriteLine($"{displayText}: Average elapsed milliseconds: {avg.TotalMilliseconds}");

            return avg.TotalMilliseconds;
        }

        private static LoginViewModel CreateLoginViewModel()
            => new LoginViewModel
            {
                Email = "name.familyname@not.com",
                Password = "abcdefgh123456!@",
                RememberMe = true
            };
    }

    [Serializable]
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public bool RememberMe { get; set; }
    }
}
```

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.1;netcoreapp2.0</TargetFrameworks>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

</Project>
```

**Comment by mattwarren** [comment]
> And I am very confused because it's also not present in the 2.0 branch

Is it in the 2.0 branch :-), see https://github.com/dotnet/coreclr/blob/release/2.0.0/src/vm/reflectioninvocation.cpp#L225-L272 and https://github.com/dotnet/coreclr/blob/release/2.0.0/src/mscorlib/src/System/Reflection/RtFieldInfo.cs#L17-L18 (it's a [FCall method](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/mscorlib.md#fcall-functional-behavior))

But it was removed in the PR that @mikedn linked to, see https://github.com/dotnet/coreclr/pull/13241/files#diff-a07ab78d2f4a1c72865756edae89399c and https://github.com/dotnet/coreclr/pull/13241/files#diff-1c8320f0c8f1cd0dd3a744b0ba4ea0ab

> I wouldn't rely too much on GitHub searches. Sometimes things don't show up, tends to happen with large files AFAIR.

Yep, I tend to keep a copy of the source locally and use VSCode, I've been bitten by GitHub searches before

**Comment by adamsitnik** [comment]
@mikedn @mattwarren thanks for help!

So the improvement comes most probably from #13241 ;)

I have opened an issue to implement benchmarks for `BinaryFormatter` to keep track of its performance. https://github.com/dotnet/corefx/issues/27770

**Comment by danmosemsft** [comment]
@viktorhofer fyo
