### ISSUE TITLE
[Perf] Investigate XmlSerializer.Deserialize Regression between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/coreclr#16627]
10-30% Windows, 50-100% Linux

**Comment by AndyAyersMS** [comment]
If this is a new perf test that requires non-repo assets, please make sure to write up good repro instructions somewhere.

**Comment by adamsitnik** [comment]
I investigated the problem and opened a new issue in CoreFX, as both `XmlSerializer` and `Marvin` live there: https://github.com/dotnet/corefx/issues/27636
