### ISSUE TITLE
Remove dependency on the libuuid

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#16642]
coreclr runtime now depends on a 3rd party libuuid library that is used just to create a random based GUID in the CoCreateGuid PAL function. We would like to eliminate as much runtime dependencies as we can, so let's replace it by our own implementation.

**Comment by kasper3** [comment]
* can it be cleaned up in rest of the places like scripts, docs and packaging manifest https://github.com/dotnet/coreclr/search?q=libuuid?
* can the same cleanup of libuuid made to corert at this point?
