### ISSUE TITLE
Implement AVX2 Intrinsics

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#16653]
Pending:
- [x] AlignRight
- [x] Blend
- [x] ConvertToDouble
- [x] ConvertToInt32
- [x] ConvertToUInt32
- [ ] GatherVector128
- [ ] GatherVector256
- [ ] GatherMaskVector128
- [ ] GatherMaskVector256
- [ ] MaskLoad
- [ ] MaskStore
- [ ] MultipleSumAbsoluteDifferences
- [ ] MultiplyAddAdjacent
- [ ] MultiplyHigh
- [ ] MultiplyHighRoundScale
- [ ] MultiplyLow
- [ ] PackSignedSaturate
- [ ] PackUnsignedSaturate
- [ ] Permute4x64
- [ ] PermuteVar8x32
- [ ] ShiftRightArithmeticVariable
- [ ] Shuffle
- [ ] ShuffleHigh
- [ ] ShuffleLow
- [ ] Sign
- [ ] SumAbsoluteDifferences

category:reach
theme:intrinsics
skill-level:intermediate
cost:large

**Comment by tannergooding** [comment]
@fiigii, could you confirm which ones you are currently planning on implementing?

**Comment by fiigii** [comment]
> could you confirm which ones you are currently planning on implementing?

 BroadcastScalarToVector128
 BroadcastScalarToVector256
 BroadcastVector128ToVector256
 Extract*
 Insert*

**Comment by fiigii** [comment]
Could you please update this list?

**Comment by tannergooding** [comment]
@fiigii, should be updated now.

**Comment by fiigii** [comment]
Thank you so much.

**Comment by fiigii** [comment]
@tannergooding I see that you assigned this issue to your self. Are you implementing these AVX2 intrinsics?

**Comment by tannergooding** [comment]
Yes. I am working on most of them right now. We can split them if you have some spare time/etc :)

**Comment by fiigii** [comment]
Thanks for the work. Could you share which ones you are working on? I will some spare time next week 😄

**Comment by tannergooding** [comment]
@fiigii, I am currently just working on them in alphabetical order. I'll have a PR up Monday morning with w/e I completed over the weekend.

**Comment by fiigii** [comment]
@tannergooding Are you implementing some APIs in this list? I want to continue in alphabetical order.

**Comment by tannergooding** [comment]
@fiigii, I am finalizing the BMI intrinsics. The list should be free to pull from 😄

**Comment by fiigii** [comment]
Thanks, I will pick up `MaskLoad`, `MaskStore`, and `ShiftRightArithmeticVariable` (this missed in my previous PR).
