### ISSUE TITLE
SOS - Error message in Linux mention a command that doesn't exist in lldb

### ISSUE THREAD

**Issue by fujiy** [dotnet/coreclr#16665]
When I call sos ClrStack and can't walk the stack, it returns:

(lldb) sos ClrStack
OS Thread Id: 0x0 (1)
Unable to walk the managed stack. The current thread is likely not a
managed thread. You can run **!threads** to get a list of managed threads in
the process

It should be clrthreads or sos Threads

**Comment by mikem8361** [comment]
Fixed with PR #16701.
