### ISSUE TITLE
Implement SSE2 intrinsics

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#16673]
Pending (a check means it is in a pending PR):
- [x] LoadHigh
- [x] LoadLow
- [x] SetVector128
- [x] SetScalarVector128
- [x] SetAllVector128
- [x] StoreNonTemporal

**Comment by fiigii** [comment]
@tannergooding @4creators

**Comment by tannergooding** [comment]
MaskMove is pending here: [WIP] Implement the SSE2 MaskMove intrinsic

**Comment by fiigii** [comment]
@tannergooding Thank you 😄

**Comment by 4creators** [comment]
@fiigii In the above list there are still missing `LoadHigh` and `LoadLow` intrinsics

**Comment by fiigii** [comment]
@4creators Thanks! Will add.

**Comment by 4creators** [comment]
@fiigii `ConvertScalarToVector128UInt32` is already implemented.

**Comment by fiigii** [comment]
> ConvertScalarToVector128UInt32 is already implemented.

I did not find it in `hwintrinsiclistxarch.h`.

**Comment by 4creators** [comment]
https://github.com/dotnet/coreclr/blob/master/src/jit/hwintrinsiclistxarch.h#L187

**Comment by fiigii** [comment]
Ah, it was accidently removed by a bad marge on my local machine. Thank you so much!

**Comment by fiigii** [comment]
@4creators `ConvertScalarToVector128UInt32` is not tested, its test file actually uses `Sse.ConvertScalarToVector128Single`
https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/HardwareIntrinsics/X86/Sse2/ConvertScalarToVector128UInt32.cs

Please fix.

**Comment by 4creators** [comment]
@fiigii Thanks for catching this error. Will fix.

**Comment by 4creators** [comment]
@fiigii @tannergooding  I am working on remaining 5 intrinsics: `LoadHigh`, `LoadLow`, `SetAllVector128`, `SetScalarVector128`, `SetVector128`,

**Comment by 4creators** [comment]
@fiigii `StoreNonTemporal` is missing as well unless it is in some PR

**Comment by fiigii** [comment]
@4creators You are right. Added to the list. Thanks!

**Comment by 4creators** [comment]
@fiigii There is new PR #16736 which implements `LoadHigh`, `LoadLow` and `SetScalaVector128`

**Comment by 4creators** [comment]
@fiigii @tannergooding two last SSE2 intrinsics SeVector128 and StoreNonTemporal are in #16817 and #16832 respectively.

**Comment by 4creators** [comment]
@fiigii @tannergooding 

This issue can be closed now as all SSE2 intrinsics are implemented. I am working on porting tests to templates.
