### ISSUE TITLE
Wrong result using & operator on value of type short on ARM platform

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#16675]
_From @mdisg on February 28, 2018 9:50_

Hello,

i'm currently porting an existing .NET application used on embedded devices to .NET Core. 
Yesterday a bug showed up running in a backup task which simply takes old log files and puts them into a zip archive for which we use the [DotNetZip Library](https://archive.codeplex.com/?p=dotnetzip). This task has run several times without a problem but yesterday i got the exception `IndexOutOfRangeException: 'Index was outside the bounds of the array.`

This happend on a ARMv7 embedded board running Ubuntu 16.04.3 LTS. I then tried to create a zip archive using the same file on Windows 10 and on Ubuntu running in a Virtualbox where no problem showed up

Looking deeper into the reason for that exception revealed that a negative value is passed to a method which does not expect it. I compared the same call of the method on other platforms which showed me that there is always a positive value passed to the method and it works as expected.
The reason for that negative value was a AND operation using the `& operator` on a value of type `short/Int16` which is read from a array `short[]`.

The operation which is done in the DotNetZip library is:
`hash_head = (head[ins_h] & 0xffff);`
where hash_head is of type `int`

The value at the array position which is causing the exception is `-32762` The result of the operation should be `32774`. Running that code using .NET Core on the ARM board gives the result `-32762`.
On all my other environments the result was correct (.NET 3.5, 4, .NET CF 3.5 (ARM) and .NET Core on Windows).

I then changed the code to this:
```
short current = head[ins_h];
hash_head = (current & 0xffff);
```
After that change, the operation gave the same result as on the other platforms and the zip archive was created without any errors.

The erroneous behavior can easily be reproduced with the following code running on the arm platform.
```
var shortArray = new short[] { -32762 };
Console.WriteLine("shortArray result: " + (shortArray[0] & 0xFFFF));
```

This code does the same but in a different manner and works on arm:
```
short shortValue = -32762;
Console.WriteLine("shortValue result: " + (shortValue & 0xFFFF));
```

This is a weird behavior and i think this can be a big issue porting existing code to .NET Core. In my case it can easily be solved by the given workaround but i think this can cause many trouble with projects running fine on x86/x64 but not on ARM.

I tested the given code using the dotnet runtime in version 2.0.0, 2.0.4 and 2.1-preview (26227-02)
The behavior exists in all of them.

If further information is required please ask for it.

_Copied from original issue: dotnet/corefx#27548_

**Comment by jkotas** [comment]
_From @danmosemsft on March 1, 2018 0:1_

@jkotas this seems codegen, do you agree?

**Comment by jkotas** [comment]
cc @dotnet/arm32-contrib

**Comment by mikedn** [comment]
Apparently this is a bug in the legacy JIT, it incorrectly eliminates the AND:
```asm
000006  6843           ldr     r3, [r0+4]
000008  4299           cmp     r1, r3
00000A  D205           bhs     SHORT G_M55886_IG04
00000C  EB00 0041      add     r0, r0, r1 LSL 1
000010  F9B0 0008      ldrsh   r0, [r0+8]
```
The RyuJIT version generates:
```asm
000006  6843           ldr     r3, [r0+4]
000008  4299           cmp     r1, r3
00000A  D208           bhs     SHORT G_M55886_IG04
00000C  004B           lsls    r3, r1, 1
00000E  18C0           adds    r0, r0, r3
000010  F9B0 0008      ldrsh   r0, [r0+8]
000014  F64F 73FF      movw    r3, 0xffff
000018  4018           ands    r0, r3
```

**Comment by alpencolt** [comment]
@mikedn following test also failed with RyuJIT:
```C#
class Regresssion
{
	const int Pass = 100;
    const int Fail = -1;

	[MethodImplAttribute(MethodImplOptions.NoInlining)]
    public static int AndShort()
    {
    	var shortArray = new short[] { -32762 };
		// Console.WriteLine("shortArray result: " + (shortArray[0] & 0xFFFF));
		return (shortArray[0] & 0xFFFF);
    }

	public static int Main()
    {
        if (AndShort() != -32762) return Fail;
        return Pass;
    }

}
```
```Shell
$./corerun ../exe/AndShort.exe 
$ echo $?
255
```

Generated code:
```ASM
; Assembly listing for method Regresssion:AndShort():int
; Emitting BLENDED_CODE for generic ARM CPU
; optimized code
; r11 based frame
; partially interruptible
; Final local variable assignments
;
;  V00 tmp0         [V00,T00] (  5, 10   )     ref  ->   r0         class-hnd
;# V01 OutArgs      [V01    ] (  1,  1   )  lclBlk ( 0) [sp+0x00]  
;
; Lcl frame size = 0

G_M46438_IG01:
000000  E92D 4800      push    {r11,lr}
000004  46EB           mov     r11, sp

G_M46438_IG02:
000006  F645 70B0      movw    r0, 0x5fb0
00000A  F2CB 106F      movt    r0, 0xb16f
00000E  2101           movs    r1, 1
000010  F646 739D      movw    r3, 0x6f9d
000014  F2CB 635C      movt    r3, 0xb65c
000018  4798           blx     r3		// CORINFO_HELP_NEWARR_1_VC
00001A  F248 0306      movw    r3, 0x8006
00001E  B21B           sxth    r3, r3
000020  8103           strh    r3, [r0+8]
000022  F9B0 0008      ldrsh   r0, [r0+8]
000026  F64F 73FF      movw    r3, 0xffff
00002A  4018           ands    r0, r3

G_M46438_IG03:
00002C  E8BD 8800      pop     {r11,pc}

; Total bytes of code 48, prolog size 6 for method Regresssion:AndShort():int
```

**Comment by mikedn** [comment]
@alpencolt You're testing the wrong value, the result should be 32774, not -32762.

**Comment by RussKeldorph** [comment]
Closing based on @mikedn's analysis--Thanks!  This appears to be fixed by the move to RyuJIT.  Re-open if I am mistaken.

**Comment by mdisg** [comment]
@RussKeldorph does this mean it is fixed with the release of 2.1 or what has to be done to use RyuJIT?

**Comment by mikedn** [comment]
RyuJIT is used by default in 2.1 (both release and the current preview) so you don't need to do anything.

**Comment by mdisg** [comment]
@mikedn thanks for the quick response. I will test it when i continue my work on that project in which the issue came up
