### ISSUE TITLE
Improve documentation on F# Framework Compatabilities

### ISSUE THREAD

**Issue by geoeo** [dotnet/coreclr#16686]
A new project of type classlib defaults to dotnetstandard2.0 framework. This does not support a number of (presumed) default system libraries such as System.Numerics.Vectors.

This is by no means obvious since a C# classlib **also** targets dotnetstandard2.0 but **does** support these libraries.

## Steps to reproduce
* Make a F# project of type classlib
* Note that System.Numerics.Matrix4x4 is undefined

* Make a F# project of type console
* Note that System.Numerics.Matrix4x4 is defined.

**Comment by RussKeldorph** [comment]
@karelz Can you help route this?  This sounds like an oversight rather than something requiring documentation, but I really have no idea.

**Comment by jkotas** [comment]
@KevinRansom Where should this go?

**Comment by svick** [comment]
I don't see any difference between F# and C# .Net Standard 2.0 library when it comes to referencing `System.Numerics.Vectors` (see below). Can you clarify what exactly did you do to observe the difference?

## C#

1. `dotnet new classlib -lang c#`
2. Add `System.Numerics.Matrix4x4 m;` field to `Class1` in Class1.cs.
3. `dotnet build` fails:

    ```
    Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
    Copyright (C) Microsoft Corporation. All rights reserved.

      Restore completed in 89,46 ms for C:\code\tmp\hwapp\hwapp.csproj.
    Class1.cs(7,25): error CS0234: The type or namespace name 'Matrix4x4' does not exist in the namespace 'System.Numerics' (are you missing an assembly reference?) [C:\code\tmp\hwapp\hwapp.csproj]

    Build FAILED.

    Class1.cs(7,25): error CS0234: The type or namespace name 'Matrix4x4' does not exist in the namespace 'System.Numerics' (are you missing an assembly reference?) [C:\code\tmp\hwapp\hwapp.csproj]
        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:03.44
    ````
4. `dotnet add package System.Numerics.Vectors`
5. `dotnet build` succeeds:

    ```
    Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
    Copyright (C) Microsoft Corporation. All rights reserved.

      Restoring packages for C:\code\tmp\hwapp\hwapp.csproj...
      Restore completed in 281,16 ms for C:\code\tmp\hwapp\hwapp.csproj.
    Class1.cs(7,35): warning CS0169: The field 'Class1.m' is never used [C:\code\tmp\hwapp\hwapp.csproj]
      hwapp -> C:\code\tmp\hwapp\bin\Debug\netstandard2.0\hwapp.dll

    Build succeeded.

    Class1.cs(7,35): warning CS0169: The field 'Class1.m' is never used [C:\code\tmp\hwapp\hwapp.csproj]
        1 Warning(s)
        0 Error(s)

    Time Elapsed 00:00:02.86
    ```

## F#

1. `dotnet new classlib -lang f#`
2. Add `type C = val m : System.Numerics.Matrix4x4` to Library.fs
3. `dotnet build` fails:

    ```
    Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
    Copyright (C) Microsoft Corporation. All rights reserved.

      Restore completed in 55,54 ms for C:\code\tmp\hwapp\hwapp.fsproj.
    C:\code\tmp\hwapp\Library.fs(7,34): error FS0039: The type 'Matrix4x4' is not defined in 'System.Numerics'. [C:\code\tmp\hwapp\hwapp.fsproj]

    Build FAILED.

    C:\code\tmp\hwapp\Library.fs(7,34): error FS0039: The type 'Matrix4x4' is not defined in 'System.Numerics'. [C:\code\tmp\hwapp\hwapp.fsproj]
        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:04.69
    ```
4. `dotnet add package System.Numerics.Vectors`
5. `dotnet build` succeeds:

    ```
    Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
    Copyright (C) Microsoft Corporation. All rights reserved.

      Restoring packages for C:\code\tmp\hwapp\hwapp.fsproj...
      Restore completed in 1,26 sec for C:\code\tmp\hwapp\hwapp.fsproj.
      hwapp -> C:\code\tmp\hwapp\bin\Debug\netstandard2.0\hwapp.dll

    Build succeeded.
        0 Warning(s)
        0 Error(s)

    Time Elapsed 00:00:06.79
    ```

**Comment by geoeo** [comment]
The fact that I have to add the package is not documented

**Comment by svick** [comment]
Are you saying that [the API reference for `Matrix4x4`](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.matrix4x4) should tell you which package it's in on which framework? If so, I agree. Here are some links about that issue: https://github.com/dotnet/designs/pull/25, https://github.com/MicrosoftDocs/feedback/issues/121, https://github.com/dotnet/docs/issues/320.

**Comment by geoeo** [comment]
> Are you saying that the API reference for Matrix4x4 should tell you which package it's in on which framework?

Pretty much, yes.

**Comment by karelz** [comment]
Looks like it is mostly covered by https://github.com/dotnet/docs/issues/320. Let me know if I misunderstood.
