### ISSUE TITLE
More meaningfull error instead of "The library hostpolicy.dll required to execute"

### ISSUE THREAD

**Issue by roozbehid-ic** [dotnet/coreclr#16708]
It seems when .Net Core application doesnt have **appname.deps.json** or **appname.runtimeconfig.deps**, .Net Core shows this error 

    A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'some path'

It hit me several times and I've spent some time just looking for that dll and why it is missing until I found that [other people](https://stackoverflow.com/questions/38085430/the-library-hostpolicy-dll-was-not-found) also hit it and the reason was something else.

Some error message before tht about those missing files would save tons of time.

**Comment by jkotas** [comment]
This issue was moved to dotnet/core-setup#3768
