### ISSUE TITLE
Unexpected PEVerify errors reported for reflection calls

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/coreclr#1674]
See https://github.com/dotnet/roslyn/issues/5238 for the description of the issue and repro steps.

**Comment by jkotas** [comment]
I suspect that the problem in dotnet/roslyn#5238 was missing System.Reflection.TypeExtensions assembly. I am not able to reproduce the problem.

BTW: We are working on a new standalone IL verifier at: https://github.com/dotnet/corert/tree/master/src/ILVerify
