### ISSUE TITLE
PAL_InitializeTracing is Not Called on Start-up

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#16763]
PAL_InitializeTracing loads libcoreclrtraceptprovider.so during module load of libcoreclr.so via a module constructor.  This is done to allow CoreCLR to log to LTTng.

It appears that in recent builds PAL_InitializeTracing is not being called, and isn't even ending up in libcoreclr.so:

```
nm bin/Product/Linux.x64.Debug/libcoreclr.so | grep PAL_Initialize
00000000009e1ab0 t PAL_Initialize
00000000009e35e0 t PAL_InitializeCoreCLR
00000000009e3d90 t PAL_InitializeDebug
00000000009e3510 t PAL_InitializeDLL
```

I have confirmed that the file is being compiled.

**Comment by brianrob** [comment]
@janvorli are you aware of anything in the PAL that might have changed and could be affecting this?

**Comment by janvorli** [comment]
I am not aware of any change that would touch it. But I can confirm that when I build the latest main, it doesn't work. Building release/2.0.0 works. I am running git bisect to find the offending commit.

**Comment by janvorli** [comment]
@brianrob this is the commit that introduced the issue. The commit before that was working: https://github.com/dotnet/coreclr/commit/c1bbdae7964b19b7063074d36e6af960f0cdc3a0
I don't have any more time today to look into that, the git bisect has just completed.

**Comment by brianrob** [comment]
Thanks @janvorli.  I have a fix for this and will get it posted soon.
