### ISSUE TITLE
.Net Standard 2.1?

### ISSUE THREAD

**Issue by jherby2k** [dotnet/coreclr#16806]
I can't find any information about a .net standard 2.1.

I really want to use the new Span-ified methods like Stream.Read in my class libraries, but it looks like that stuff isn't in System.Memory but rather the .net core 2.1 SDK. Any other way to get these APIs, or do I have to wait for .net standard 2.1. And is there any ETA on that?

**Comment by ahsonkhan** [comment]
> I really want to use the new Span-ified methods like Stream.Read in my class libraries, but it looks like that stuff isn't in System.Memory but rather the .net core 2.1 SDK. Any other way to get these APIs, or do I have to wait for .net standard 2.1. And is there any ETA on that?

You do not have to wait for them to be added to .net standard 2.1 if your applications can target .NET Core 2.1.

> are these in OOB packages?

The System.Memory package (which contains Span/Memory/etc) is available OOB (for full framework and older version of .net core (like 2.0), and it complies with netstandard1.1 so can be used on any of the platforms that support netstandard1.1+.

The new overloads being added throughout the BCL, like the Stream methods, as part of the "Spanification," are only available starting on .NET Core 2.1, as far as I know.


> I can't find any information about a .net standard 2.1.

Can you help address this, especially if I missed something?
cc @terrajobst, @KrzysztofCwalina, @stephentoub

**Comment by Joe4evr** [comment]
> But i'm writing a class library, not an application, and targeting .net standard as per Microsoft's recommendation.

Yes, I've been wondering myself why there are methods in `netcoreapp` that aren't available in the equivalent `netstandard` TFM. Basic things like [`ConcurrentQueue<T>.Clear()`](https://apisof.net/catalog/System.Collections.Concurrent.ConcurrentQueue%3CT%3E.Clear()) (yet [`ConcurrentStack<T>.Clear()`](https://apisof.net/catalog/System.Collections.Concurrent.ConcurrentStack%3CT%3E.Clear()) is available *everywhere*).

**Comment by RussKeldorph** [comment]
This issue was moved to dotnet/standard#682
