### ISSUE TITLE
Missed commits in 2.1-preview

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#16825]
We're preparing release of 2.1-preview for Tizen platform and have found that some interesting for us patches are missing in 2.1-preview branch.
Is it possible to cherry pick them? If so what is the due date?

@jkotas @janvorli @BruceForstall 
cc @kbaladurin @Dmitri-Botcharnikov

**Comment by jkotas** [comment]
I do not think there is 2.1-preview branch. There is https://github.com/dotnet/coreclr/tree/release/2.1 branch from which we have shipped .NET Core 2.1 Preview1  https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-net-core-2-1-preview-1/ . I expect we are going to integrate master into it to ship the next eventual preview and the actual .NET Core 2.1 release. If your changes are in master now they will get to the release branch.

cc @Petermarcu

**Comment by danmosemsft** [comment]
Correct.

**Comment by alpencolt** [comment]
If so it's great. These commits are in master.
Thank you.
