### ISSUE TITLE
[Linux][ARM][PAL]PAL_CS_NATIVE_DATA_SIZE are different for x86_arm and arm_arm crossgens

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#16826]
Found that 
1.`PAL_CS_NATIVE_DATA_SIZE` has different values for Linux/ARM `(80)` and Linux/x86 `(76)` as defined in src/pal/inc/pal.h;
2. Which ends up in having different sizes for `_CRITICAL_SECTION::CSNativeDataStorage` and `CrstExplicitInit` structures;
3. Which causes `Module` class to be of different sizes - 1484 bytes when compiled on Linux/x86 and 1504 bytes when compiled Linux/ARM

Now, when we do x86_arm crossgen-ing (fragile NGen) of `System.Private.CoreLib.dll` we end up with the image that couldn't be loaded on Linux/ARM since we do serialize class `Module` to `.data` section in `CEEPreloader::Link` call in compile.cpp and EE expects this one to be 1504 bytes.

This issue was related to #16787 which will be closed since we identified where the problem is.

One of possible solutions is to use only ReadyToRun for x86_arm crossgen. We can allow to use fragile NGen for S.P.C.dll if we do native arm_arm crossgen.

@jkotas @RussKeldorph Can you please take a look?
cc @janvorli

**Comment by jkotas** [comment]
I think we should switch to R2R crossgen for CoreLib unconditionally on ARM.

**Comment by RussKeldorph** [comment]
@jkotas For ARM, I think that's an acceptable solution, but should this be fixed for the general case?  I believe a similar mismatch exists for x64->ARM64 and x64->x86, which might be interesting cross scenarios in the future (though I'm not sure if the mismatch will cause problems).  Or should we just not allow fragile ngen to proliferate beyond existing supported scenarios?

**Comment by jkotas** [comment]
I think we should be working towards retiring fragile NGen support in crossgen.

If you would like to fix this, https://github.com/dotnet/coreclr/pull/10159 was earlier attempt to fix it that insightful discussion. It was not merged though.

**Comment by RussKeldorph** [comment]
@jkotas Thanks for the pointer.  I don't object to retiring fragile ngen, so this doesn't need to be fixed.  @echesakovMSFT Just go with R2R unconditionally for ARM, even for the native crossgen, as @jkotas suggests.
