### ISSUE TITLE
[Arm64/Ubuntu] JIT/HardwareIntrinsics/X86/Avx2 fail GCStress=8

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#16844]
On the 5e03df42d9fb tip, I see the following avx2 tests failing GCStress=8 with a segmentation fault

JIT/HardwareIntrinsics/X86/Avx2/Avx2_r/Avx2_r.sh
JIT/HardwareIntrinsics/X86/Avx2/Avx2_ro/Avx2_ro.sh

```
corerun Avx2_r.exe
Running Add.Byte test...
Running Add.Int16 test...
Running Add.Int32 test...
Running Add.Int64 test...
Running Add.SByte test...
Running Add.UInt16 test...
Running Add.UInt32 test...
Running Add.UInt64 test...
Running And.Byte test...
Running And.Int16 test...
Running And.Int32 test...
Running Ancorerun Avx2_r.exe
Running Add.Byte test...
Running Add.Int16 test...
Running Add.Int32 test...
Running Add.Int64 test...
Running Add.SByte test...
Running Add.UInt16 test...
Running Add.UInt32 test...
Running Add.UInt64 test...
Running And.Byte test...
Running And.Int16 test...
Running And.Int32 test...
Running And.Int64 test...
Running And.SByte test...
Running And.UInt16 test...
Running And.UInt32 test...
Running And.UInt64 test...
Running AndNot.Byte test...
Running AndNot.Int16 test...
Running AndNot.Int32 test...
Running AndNot.Int64 test...
Running AndNot.SByte test...
Running AndNot.UInt16 test...
Running AndNot.UInt32 test...
Running AndNot.UInt64 test...
Running Average.Byte test...
Running Average.UInt16 test...
Running BlendVariable.Byte test...
Running BlendVariable.SByte test...
Running BroadcastScalarToVector128.Byte test...
Running BroadcastScalarToVector128.SByte test...
Running BroadcastScalarToVector128.Int16 test...
Running BroadcastScalarToVector128.UInt16 test...
Running BroadcastScalarToVector128.Int32 test...
Running BroadcastScalarToVector128.UInt32 test...
Running BroadcastScalarToVector128.Int64 test...
Running BroadcastScalarToVector128.UInt64 test...
Running BroadcastScalarToVector128.Single test...
Running BroadcastScalarToVector128.Double test...
Running BroadcastScalarToVector256.Byte test...
Command terminated by signal 11
```

Fails in same spot repeatably.

@tannergooding @CarolEidt

**Comment by tannergooding** [comment]
Sorry for the delayed response. Looking into this.

**Comment by tannergooding** [comment]
@fiigii, @CarolEidt, @sdmaclea.

Part of the issue is that we are only handling `NI_HW_INTRINSIC_START` through `NI_HW_INTRINSIC_END`, and we only define intrinsic nodes for the current ISA.

This means that, on Arm, `x86.<Isa>.IsSupported` is never handled as a constant node of 0 (and likewise for `Arm64.<Isa>.IsSupported` on x86).

This means that we end up jitting a bunch of code that should never be compiled.

**Comment by tannergooding** [comment]
That being said, the fault is probably still an issue that needs to be addressed...

**Comment by fiigii** [comment]
> This means that, on Arm, x86.<Isa>.IsSupported is never handled as a constant node of 0 (and likewise for Arm64.<Isa>.IsSupported on x86).

On ARM, mscorlib is built with `X86Isa.PlatformNotSupported.cs` files, and JIT has no idea about x86 intrinsic nodes. I think this design should work fine.

**Comment by tannergooding** [comment]
> I think this design should work fine

@fiigii, It doesn't look like the dead code paths are being optimized away (even in Release mode), so something needs to be fixed.

```
G_M32556_IG02:
       E84059265E           call     System.Runtime.Intrinsics.Arm.Arm64.Simd:get_IsSupported():bool
       85C0                 test     eax, eax
       7412                 je       SHORT G_M32556_IG03
       48BF3031494BF0010000 mov      rdi, 0x1F04B493130
       488B0F               mov      rcx, gword ptr [rdi]
       E8DAC2FFFF           call     System.Console:WriteLine(ref)

G_M32556_IG03:
```

**Comment by tannergooding** [comment]
@CarolEidt, would you know why the `get_IsSupported` call (which is implemented as `public static bool IsSupported { get { return false; }}`) isn't getting treated as a constant?

**Comment by CarolEidt** [comment]
> would you know why the get_IsSupported call (which is implemented as public static bool IsSupported { get { return false; }}) isn't getting treated as a constant?

I would assume that isn't being inlined. It seems like they ought to be easy candidates for inlining, so I'd have to look at the jitdump or debug it to see why they're not, but I'm not sure why we wouldn't mark these with `[MethodImpl(MethodImplOptions.AggressiveInlining)]` just to be sure. I'm pretty sure that if the inliner has already done a bunch of inlining it will just stop.

**Comment by tannergooding** [comment]
> I'm pretty sure that if the inliner has already done a bunch of inlining it will just stop.

It definitely wasn't this. I had tested with a minimal repro and still saw it fail.

Will check the jit dump.

**Comment by tannergooding** [comment]
> Will check the jit dump.

Hmmm, as of the latest master, it looks to be getting inlined properly. Maybe my machine was in a bad state last time I checked....

**Comment by sdmaclea** [comment]
FWIW on more recent tip 4e332945, these are all failing in `gcStress=1`,`gcStress=2`,`gcStress=4`,and `gcStress=8`
```
JIT/HardwareIntrinsics/X86/Avx/Avx_r/Avx_r.sh
JIT/HardwareIntrinsics/X86/Avx/Avx_ro/Avx_ro.sh
JIT/HardwareIntrinsics/X86/Avx2/Avx2_r/Avx2_r.sh
JIT/HardwareIntrinsics/X86/Avx2/Avx2_ro/Avx2_ro.sh
```

**Comment by tannergooding** [comment]
This is probably the same issue as https://github.com/dotnet/coreclr/issues/16370

Based on my initial analysis, this had nothing to do with Hardware Intrinsics and was a more general issue.

It may actually be related to https://github.com/dotnet/coreclr/issues/16892

**Comment by AndyAyersMS** [comment]
Can we get an updated status here? Is this now fixed?

**Comment by fiigii** [comment]
Yes, please close.

**Comment by sdmaclea** [comment]
It is fixed in the master branch.
It is still failing in the release_2.1 branch.

I am assuming release_2.1 will get a refresh around ZBB. So this can be closed
