### ISSUE TITLE
[ARM] Crossgen can't generate pdb for R2R System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#16864]
In order to use Ready2Run for `System.Private.CoreLib.dll` for ARM and retire fragile NGen (as we wanted in #16826 #16839) this needed to be resolved first

```
BUILD: "D:\git\coreclr-base\bin\Product\Windows_NT.arm.Checked\x86\crossgen.exe" /Platform_Assemblies_Paths "D:\git\coreclr-base\bin\Product\Windows_NT.arm.Checked" /CreatePdb "D:\git\coreclr-base\bin\Product\Windows_NT.arm.Checked\PDB" "D:\git\coreclr-base\bin\Product\Windows_NT.arm.Checked\System.Private.CoreLib.dll" 
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Loaded image 'D:\git\coreclr-base\bin\Product\Windows_NT.arm.Checked\System.Private.CoreLib.dll' (for input file 'D:\git\coreclr-base\bin\Product\Windows_NT.arm.Checked\System.Private.CoreLib.dll') is not a native image.
Error generating PDB for 'D:\git\coreclr-base\bin\Product\Windows_NT.arm.Checked\System.Private.CoreLib.dll': Couldn't find a native image. (Exception from HRESULT: 0x80131C64)
Error: compilation failed for "D:\git\coreclr-base\bin\Product\Windows_NT.arm.Checked\System.Private.CoreLib.dll" (0x80131c64)
```
**Related issues:** #16862

**Comment by echesakovMSFT** [comment]
I investigated this problem which can be reproduced on any architecture supporting PDB generating (not only Windows/arm).

**Steps to reproduce:**
1. Disable fragile NGen for `S.P.C.dll` in crossgen.cpp by commenting out the following
```
     if (fCompilingMscorlib)
         dwFlags &= ~NGENWORKER_FLAGS_READYTORUN;
```
2. `crossgen S.P.C.dll`
3. `crossgen /CreatePdb S.P.C.ni.dll`
 

Here are my understanding why `/CreatePdb` works for any R2R assembly but does not work for  R2R `S.P.C.dll`:

1. During step 3 in compile.cpp `CreatePdb()` checks whether at least one module `pModule` in the assembly is `pModule->HasNativeImage() || pModule->IsReadyToRun()`. Otherwise, it shows *Error generating PDB* error.
1. `pModule->IsReadyToRun()` checks whether `pModule->m_pReadyToRunInfo != NULL`
2. `m_pReadyToRunInfo` in initialized with `ReadyToRunInfo::Initialize` in `Module::Initialize` in ceeload.cpp
3. `ReadyToRunInfo::Initialize` always returns `NULL` if `IsCompilationProcess() && !IsNgenPDBCompilationProcess()`
4. `IsNgenPDBCompilationProcess()` returns `IsCompilationProcess() && g_pCEECompileInfo->GetIsGeneratingNgenPDB()` 
5. `GetIsGeneratingNgenPDB()` returns value of `m_fGeneratingNgenPDB` which set in `SetIsGeneratingNgenPDB()`

**Scenario 1:** `crossgen /CreatePdb` any R2R assembly (but not `S.P.C.dll`) has the following order of  function calls:
1. `m_pEECompileInfo->SetIsGeneratingNgenPDB(TRUE)` in `CreatePdbInCurrentDomain` in zapper.cpp 
2. `Module::Initialize()`
3.  `ReadyToRunInfo::Initialize()` returns not `NULL`.

**Scenario 2:** `crossgen /CreatePdb` R2R `S.P.C.dll` has the following order of  function calls:
1. `CreateCompilationDomain()` in `CreatePdb()` in zapper.cpp
2. `Module::Initialize()` for System Domain
3. Since `m_fGeneratingNgenPDB` is `FALSE` `ReadyToRunInfo::Initialize` returns `NULL`
4. `m_pEECompileInfo->SetIsGeneratingNgenPDB(TRUE)` in `CreatePdbInCurrentDomain` in zapper.cpp 
5. `pModule->IsReadyToRun()` returns `FALSE` in  `CreatePdb()` in compile.cpp

@jkotas PTAL 
Do you know what could be preferred solution to this issue? 
Why do we check in `ReadyToRunInfo::Initialize()` whether `IsCompilationProcess() && !IsNgenPDBCompilationProcess()`. Is it performance optimization? I am wondering if we can we just exclude this check when `_TARGET_ARM_`?

cc @RussKeldorph

**Comment by jkotas** [comment]
I think the right fix for this is to set the GeneratingPDB flag earlier: https://github.com/dotnet/coreclr/pull/16882
