### ISSUE TITLE
clr-beta vs coreclr-beta vs desktop-clr

### ISSUE THREAD

**Issue by cheers00** [dotnet/coreclr#1686]
I am trying to understand differences between ```clr, coreclr``` and ```desktop-clr```. 
```coreclr``` is now open sourced and I understand the versions but how ```clr beta-versions``` and ```desktop CLR 4.56``` differ?

```
Active Version           Runtime Architecture OperatingSystem Alias
------ -------           ------- ------------ --------------- -----
       1.0.0-beta7       clr     x64          win
       1.0.0-beta7       clr     x86          win
  *    1.0.0-beta7       coreclr x64          win             
       1.0.0-beta7       coreclr x86          win             
```

**Comment by ellismg** [comment]
/cc @davidfowl 

The "beta" for desktop here refers to DNX itself being in beta, not the underlying OS runtime.  When using the "CLR" runtime, DNX uses whatever .NET 4.5 runtime is on your machine.

**Comment by cheers00** [comment]
Got it. Thank you.
