### ISSUE TITLE
ValueTask could reuse cancelled task

### ISSUE THREAD

**Issue by bcronce** [dotnet/coreclr#16886]
In [private Task GetTaskForValueTaskSource()](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Threading/Tasks/ValueTask.cs) and `private Task<TResult> GetTaskForValueTaskSource()`, the task returned by this method in certain cases could be made static and reused.

```c#
var tcs = new TaskCompletionSource<bool>();
tcs.TrySetCanceled();
return tcs.Task;
```
into
```c#
internal static Task CancelledTask ...
...
return ValueTask.CancelledTask
```

**Comment by jkotas** [comment]
cc @stephentoub
