### ISSUE TITLE
Don't dup stdin & stderr as this can break some std io redicection code

### ISSUE THREAD

**Issue by TheLastRar** [dotnet/coreclr#16880]
Consider a program that does the follow;

Create pipes and dup2 the write fd onto stdin, stderr, 
Have a thread continually read the pipes until EOF is reached (at which point the thread will terminate).
Use coreclr.
...
Restore the original stdin, stderr,
Close the write fd of pipes,
Wait for the pipe reader thread to terminate.

As coreclr dups the fd for stdin & stderr, there is still a write fd for the pipe, meaning the read thread will never receive an EOF and the program to hang at the last step.

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#27935
