### ISSUE TITLE
Lots of GCStress failures in HWIntrinsics tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#16938]
E.g., https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc/78/#showFailuresLink

```
JIT_HardwareIntrinsics._X86_Avx_Avx_r_Avx_r_._X86_Avx_Avx_r_Avx_r_cmd
JIT_HardwareIntrinsics._X86_Avx_Avx_ro_Avx_ro_._X86_Avx_Avx_ro_Avx_ro_cmd
JIT_HardwareIntrinsics._X86_Sse41_Sse41_r_Sse41_r_._X86_Sse41_Sse41_r_Sse41_r_cmd
JIT_HardwareIntrinsics._X86_Sse41_MultipleSumAbsoluteDifferences_r_MultipleSumAbsoluteDifferences_r_._X86_Sse41_MultipleSumAbsoluteDifferences_r_MultipleSumAbsoluteDifferences_r_cmd
JIT_HardwareIntrinsics._X86_Avx2_Avx2_ro_Avx2_ro_._X86_Avx2_Avx2_ro_Avx2_ro_cmd
JIT_HardwareIntrinsics._X86_Avx2_Avx2_r_Avx2_r_._X86_Avx2_Avx2_r_Avx2_r_cmd
JIT_HardwareIntrinsics._X86_Sse41_ConvertToVector128_r_ConvertToVector128_r_._X86_Sse41_ConvertToVector128_r_ConvertToVector128_r_cmd
JIT_HardwareIntrinsics._X86_Ssse3_Ssse3_r_Ssse3_r_._X86_Ssse3_Ssse3_r_Ssse3_r_cmd
JIT_HardwareIntrinsics._X86_Sse3_Sse3_r_Sse3_r_._X86_Sse3_Sse3_r_Sse3_r_cmd
JIT_HardwareIntrinsics._X86_Sse_Sse_r_Sse_r_._X86_Sse_Sse_r_Sse_r_cmd
```

**Comment by BruceForstall** [comment]
@CarolEidt @fiigii @tannergooding 
cc @dotnet/jit-contrib

**Comment by fiigii** [comment]
I have investigated this issue for https://github.com/dotnet/coreclr/issues/16370. The codegen of HW intrinsics looks no problem... May need help from GC experts @jkotas

**Comment by sdmaclea** [comment]
@BruceForstall Are they in x86 and arm64 tests?  I can take a look at arm64 failures if needed.

**Comment by BruceForstall** [comment]
You can see all the various stress (GC and JIT) jobs here: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/

> @BruceForstall Are they in x86 and arm64 tests? I can take a look at arm64 failures if needed.

Looks like x86 has similar failures: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc/72/#showFailuresLink

Our Windows arm64 runs have been broken for a while due to machine issues. In the next week or so, the next run will hopefully be valid. It looks like we don't run GCStress on non-Windows arm64 machines (well, it looks like there are jobs defined, but never run. Probably without triggers or cron definitions.)

**Comment by tannergooding** [comment]
Fix should be here: https://github.com/dotnet/coreclr/pull/16957
