### ISSUE TITLE
ASP.Net Core Web API with Full Framework does not deploy as FDD

### ISSUE THREAD

**Issue by Vatsi** [dotnet/coreclr#16932]
Hi,
 I recently created ASP.Net Core Web API with the full framework as I wanted to use my existing .net Framework binaries and SAML 2.0 authentication.

 My project file looks like following.

`<PropertyGroup>`
    `<TargetFramework>net462</TargetFramework>`
 ` </PropertyGroup>`

  `<PropertyGroup>`
    `<AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>`
  `</PropertyGroup>`

  `<ItemGroup>`
    `<Compile Include="..\..\..\..\..\ProductAssemblyInfo\ProductAssemblyInfo.cs" Link="Properties\ProductAssemblyInfo.cs" />`
  `</ItemGroup>`

  `<ItemGroup>`
    `<Content Include="obj\project.assets.json" />`
  `</ItemGroup>`

 ` <ItemGroup>`
    `<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />`
  `</ItemGroup>`

  `<ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">`
    `<Reference Include="System" />`
    `<Reference Include="System.ServiceModel" />`
    `<Reference Include="System.Core" />`
    `<Reference Include="Microsoft.CSharp" />`
    `<Reference Include="System.Data" />`
    `<Reference Include="System.Web" />`
    `<Reference Include="System.Xml" />`
    `<Reference Include="System.Configuration" />`
    `<Reference Include="System.IdentityModel" />`
    `<Reference Include="Microsoft.CSharp" />`
  `</ItemGroup>`

  `<ItemGroup>`
    `<PackageReference Include="Libuv" Version="1.10.0" />`
    `<PackageReference Include="Microsoft.AspNetCore" Version="2.0.1" />`
    `<PackageReference Include="Microsoft.AspNetCore.Authentication.Abstractions" Version="2.0.1" />`
    `<PackageReference Include="Microsoft.AspNetCore.ApplicationInsights.HostingStartup" Version="2.0.1" />`
    `<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.0.1" />`
    `<PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.0.1" />`
    `<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.2" />`
    `<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="2.1.0" />`
    `<PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.0.1" />`
    `<PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.0.1" />`
    `<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.1" />`
    `<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv" Version="2.0.1" />`
    `<PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="2.0.0" />`
    `<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.0.0" />`
    `<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.0.0" />`
    `<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />`
    `<PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />`
    `<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.0.0" />`
    `<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.0" />`
    `<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.0.0" />`
  `</ItemGroup>`

This works fine but when we deploy such Web API, it requires to have all package binaries and dependencies in the bin folder instead of grabbing it from Runtime Store.

My guess is that while deploying it follows SCD deployment instead of FDD.

Can you please help me on how I can achieve it to refer package binaries and depdnecies from Runtime store instead of from bin?

I'm using ASP.Net Core 2.0.5 and .Net Framework 4.6.2.

Please let me know if you need more information on this.

**Comment by RussKeldorph** [comment]
@Vatsi I suspect you would be more likely to get an answer at https://github.com/aspnet/Home/.  Have you tried there?

**Comment by Vatsi** [comment]
@RussKeldorph let me try there. Whatever response I get, I will update here as well. As of now keeping this one open as well in case anyone has any inputs. Thanks for the tip.

**Comment by davidfowl** [comment]
There is no runtime store on .NET Framework so you end up with all of the assemblies in the bin folder. There's no such thing as a FDD with .NET Framework.

**Comment by RussKeldorph** [comment]
Closing as answered.  I recommend posting any follow-up questions to https://github.com/aspnet/Home or https://github.com/dotnet/cli.
