### ISSUE TITLE
JIT produces suboptimal code (unnecessary call) when using recent ReadOnlySpan compiler optimizations

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/coreclr#16944]
Roslyn recently made a change (https://github.com/dotnet/roslyn/pull/24621) where they're able to optimize code of the form `ReadOnlySpan<byte> span = new byte[] { /* literal data */ }`. However, this produces IL that seems to defeat JIT optimizations, resulting in unnecessary calls and suboptimal performance.

**Sample code (control)**

```cs
[MethodImpl(MethodImplOptions.NoInlining)]
private static unsafe uint Foo(int x)
{
    var span = new ReadOnlySpan<byte>(&x, 4);
    return span[1];
}
```
```text
  .method private hidebysig static uint32 
          Foo(int32 x) cil managed noinlining
  {
    // Code size       21 (0x15)
    .maxstack  3
    .locals init (valuetype [System.Runtime]System.ReadOnlySpan`1<uint8> V_0)
    IL_0000:  ldloca.s   V_0
    IL_0002:  ldarga.s   x
    IL_0004:  conv.u
    IL_0005:  ldc.i4.4
    IL_0006:  call       instance void valuetype [System.Runtime]System.ReadOnlySpan`1<uint8>::.ctor(void*,
                                                                                                     int32)
    IL_000b:  ldloca.s   V_0
    IL_000d:  ldc.i4.1
    IL_000e:  call       instance !0& modreq([System.Runtime]System.Runtime.InteropServices.InAttribute) valuetype [System.Runtime]System.ReadOnlySpan`1<uint8>::get_Item(int32)
    IL_0013:  ldind.u1
    IL_0014:  ret
  } // end of method Program::Foo
```
```asm
ConsoleApp8!ConsoleApp8.Program.Foo(Int32):
00007ffe`cf3714c0 894c2408        mov     dword ptr [rsp+8],ecx
00007ffe`cf3714c4 488d442408      lea     rax,[rsp+8]
00007ffe`cf3714c9 0fb64001        movzx   eax,byte ptr [rax+1]
00007ffe`cf3714cd c3              ret
```

**Sample code (experimental)**

```cs
[MethodImpl(MethodImplOptions.NoInlining)]
private static unsafe uint Foo(int x)
{
    var span = new ReadOnlySpan<byte>(new byte[] { 1, 2, 3, 4, 5 });
    return span[1];
}
```
```text
  .method private hidebysig static uint32 
          Foo(int32 x) cil managed noinlining
  {
    // Code size       23 (0x17)
    .maxstack  3
    .locals init (valuetype [System.Runtime]System.ReadOnlySpan`1<uint8> V_0)
    IL_0000:  ldloca.s   V_0
    IL_0002:  ldsflda    valuetype '<PrivateImplementationDetails>'/'__StaticArrayInitTypeSize=5' '<PrivateImplementationDetails>'::'11966AB9C099F8FABEFAC54C08D5BE2BD8C903AF'
    IL_0007:  ldc.i4.5
    IL_0008:  call       instance void valuetype [System.Runtime]System.ReadOnlySpan`1<uint8>::.ctor(void*,
                                                                                                     int32)
    IL_000d:  ldloca.s   V_0
    IL_000f:  ldc.i4.1
    IL_0010:  call       instance !0& modreq([System.Runtime]System.Runtime.InteropServices.InAttribute) valuetype [System.Runtime]System.ReadOnlySpan`1<uint8>::get_Item(int32)
    IL_0015:  ldind.u1
    IL_0016:  ret
  } // end of method Program::Foo
```
```asm
ConsoleApp8!ConsoleApp8.Program.Foo(Int32):
00007ffe`cf3a14c0 4883ec28        sub     rsp,28h
00007ffe`cf3a14c4 48b9493a3c8562020000 mov rcx,offset ConsoleApp8+0x3a49 (00000262`853c3a49)
00007ffe`cf3a14ce e86dd52458      call    System_Private_CoreLib!Internal.Runtime.CompilerServices.Unsafe.As[[...]](...)+0xffffffff`fffffe90 (00007fff`275eea40)
00007ffe`cf3a14d3 0fb64001        movzx   eax,byte ptr [rax+1]
00007ffe`cf3a14d7 4883c428        add     rsp,28h
00007ffe`cf3a14db c3              ret
```

Note the unnecessary `call` instruction, which should have been inlined into the caller. (The method's implementation is to return its input, so the entire call should've been optimized away as in the control sample.)

If I modify the MSIL manually by inserting a `conv.i` instruction immediately after the `ldsflda` and recompile, the JIT instead produces this codegen:

```asm
ConsoleApp8!ConsoleApp8.Program.Foo(Int32):
00007ffe`cf3a14c0 48b85120fa1d41020000 mov rax,offset ConsoleApp8+0x2051 (00000241`1dfa2051)
00007ffe`cf3a14ca 0fb600          movzx   eax,byte ptr [rax]
00007ffe`cf3a14cd c3              ret
```

This is the desired codegen for this method. The JIT seems to incorrectly require the `conv.i` instruction to get full optimization.

**Comment by AndyAyersMS** [comment]
This may be something similar to #11211.

Can you find the inline failure reason (say from ETL via perfview or via a checked jit with COMPlus_JitPrintInlinedMethods=1)? 

If not, I can take a look later tonight...

**Comment by GrabYourPitchforks** [comment]
I just rebuilt checked coreclr from source and set the environment variable you suggested. The JIT now seems to be refusing to inline the `ReadOnlySpan<byte>` ctor into its caller. I don't know what changed.

```text
**************** Inline Tree
Inlines into 06000003 ConsoleApp8.Program:Foo(int):int
  [0 IL=0008 TR=000005 06001660] [FAILED: not inline candidate] System.ReadOnlySpan`1[Byte][System.Byte]:.ctor(long,int):this
Budget: initialTime=129, finalTime=129, initialBudget=1290, currentBudget=1290
Budget: initialSize=655, finalSize=655
```

**Comment by GrabYourPitchforks** [comment]
```text
**************** Inline Tree
Inlines into 06000003 Program:Foo(int):int
  [1 IL=0008 TR=000005 06001653] [aggressive inline attribute] ReadOnlySpan`1:.ctor(long,int):this
    [2 IL=0000 TR=000027 06004EFB] [below ALWAYS_INLINE size] RuntimeHelpers:IsReferenceOrContainsReferences():bool
    [0 IL=0017 TR=000071 06000258] [FAILED: noinline per IL/cached result] ThrowHelper:ThrowInvalidTypeWithPointersNotSupported(ref)
    [0 IL=0033 TR=000042 06000119] [FAILED: return type mismatch] Unsafe:As(byref):byref
Budget: initialTime=129, finalTime=217, initialBudget=1290, currentBudget=1388
Budget: increased by 98 because of force inlines
Budget: initialSize=655, finalSize=655
```

**Comment by GrabYourPitchforks** [comment]
BTW I'm working around it for now by adding a new ctor overload `ByReference<T>.ctor(IntPtr)` and changing the `ReadOnlySpan<T>` ctor to have the following line.

```cs
_pointer = new ByReference<T>((IntPtr)pointer);
```

It gets the job done in a pinch, and perhaps it's a valid solution if we're antsy about making JIT changes to support this scenario, but I'd need to run it by a few more people if we want to leverage it as a workaround.

**Comment by GrabYourPitchforks** [comment]
Actually, now that I've had time to think about it, I'm wondering if we should just make the `ByReference<T>` change and not worry about the JIT optimization. This may end up being the less risky option. @AndyAyersMS, are you familiar enough with `ByReference<T>` to know if this is simply a non-starter of an idea?

**Comment by AndyAyersMS** [comment]
Fixing this in the jit is probably best as this kind of pattern may show up elsewhere and the fix should be simple and low risk. I will try and look at it soon.

**Comment by jkotas** [comment]
I agree with Andy. This is best to fix it in the JIT.

**Comment by AndyAyersMS** [comment]
I have a fix, it is very similar to #11218, just a different case. Will have a PR up shortly.

**Comment by GrabYourPitchforks** [comment]
That was a stupendous turnaround. Thank you so much for looking into this so quickly!

**Comment by VSadov** [comment]
Awesome!!

BTW, One thing that I am thinking about is that perhaps once `CompilerServices.Unsafe` API settles, we should make it C# intrinsics. 
The methods are 1-2 IL instructions. Some less than that - `AsRef` is really a noop.
We could just know some of them and inline actual IL instead of emitting calls.

**Comment by jkotas** [comment]
A lot more valuable would be to have Roslyn support for constructs that S.R.CS.Unsafe cannot express today: https://github.com/dotnet/roslyn/issues/11475 

Inlining S.R.CS.Unsafe is nice to have. It does not matter a whole lot whether these methods are inlined at JIT time, C# compile time, or ILLink time. I am wondering whether it would be possible to generalize this to inline any methods marked agresiveinlining and NonVersionableAttribute.

**Comment by GrabYourPitchforks** [comment]
One consideration is that the C# compiler will need to know the real IL instructions if it's to inline directly during source compilation. Some APIs may be implemented in IL as a `throw new PlatformNotSupportedException();` equivalent, with the real implementation being provided by the runtime.

We could shrink binary size on disk if the C# compiler were to inline these calls. Consider the implementation of `Buffer.Memmove(byte&, byte&, nuint)`, whose IL is almost 400 bytes longer than `Buffer.Memmove(byte*, byte* nuint)`'s IL, but for which RyuJIT produces nearly identical assembly. But given the rarity of methods which make heavy use of `Unsafe` and other intrinsic APIs, I'm not sure if that would justify the development cost.

**Comment by jkotas** [comment]
> Some APIs may be implemented in IL as a `throw new PlatformNotSupportedException();`

Right. We would need to fold reference assemblies for AOT compilation (used for R2R in some cases) into the regular reference assemblies for this work. And it is also why I have mentioned that we would be only able to do this if the method is marked with the right attributes.

I agree that the gain from this would be pretty minimal, relative to the cost required to build this.
