### ISSUE TITLE
Preallocated jump stubs for dynamic methods are reused and this leads to race/crash in some uncommon cases

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#16940]
1. When coreclr is far away from the precode, the preallocated jump stub initially points to PrecodeFixupThunk, and the precode points to the jump stub
2. Later, the jump stub is modified to point to jitted code
3. The precode is updated from "call jumpStub" to "jmp jumpStub"

Between 2 and 3, another thread may end up executing a call to the jitted code, leaving an extra return address on the stack. See test case in fix PR.

@ChrisAhna

**Comment by janvorli** [comment]
cc: @vitek-karas
