### ISSUE TITLE
Assert in JIT during crossgen in Windows armlb CI tests

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#16961]
The "Windows_NT armlb Cross Checked Innerloop Build and Test" is consistently failing with the following error. 
```
Assert failure(PID 3088 [0x00000c10], Thread: 2192 [0x0890]): Assertion failed 'indirectCellAddress->IsCnsIntOrI() && indirectCellAddress->gtRegNum == REG_R2R_INDIRECT_PARAM' in '<>f__AnonymousType0`1[__Canon][System.__Canon]:ToString():ref:this' (IL size 77)
17:11:08 
17:11:08     File: d:\j\workspace\armlb_cross_c---dd3d1742\src\jit\valuenum.cpp Line: 7437
17:11:08     Image: D:\j\workspace\armlb_cross_c---dd3d1742\bin\Product\Windows_NT.arm.Checked\x86\crossgen.exe
```

**Comment by janvorli** [comment]
cc: @dotnet/jit-contrib 

@briansull it seems it has started with this change:
https://github.com/dotnet/coreclr/pull/16928

**Comment by echesakovMSFT** [comment]
I think this started failing after I switched crossgen of S.P.C.dll to be R2R on ARM in #16895

**Comment by briansull** [comment]
It seem very unlikely that my fix would case this.

**Comment by AndyAyersMS** [comment]
This is causing the armlb leg in every PR that triggers it to fail. We really should either fix now it or disable this leg or do something equivalent....

![image](https://user-images.githubusercontent.com/10121823/37840207-ac210d8e-2e79-11e8-85e4-b40bbab69fff.png)

**Comment by erozenfeld** [comment]
@RussKeldorph Should we close this since we are planning on doing #17490 soon?

**Comment by RussKeldorph** [comment]
@erozenfeld Sure.
