### ISSUE TITLE
[arm32/Ubuntu] Test failures with JitStress=2 + JitStressRegs=2

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#16964]
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm_cross_checked_ubuntu_jitstress2_jitstressregs2_tst_prtest/1/consoleText

```
FAILED   - baseservices/threading/paramthreadstart/ThreadStartGenerics_2/ThreadStartGenerics_2.sh
               BEGIN EXECUTION
               export CDPATH=.
               /bin/sh -c ../ThreadStartGenerics/ThreadStartGenerics.sh
               BEGIN EXECUTION
               /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs2_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun ThreadStartGenerics.exe max
               ../ThreadStartGenerics/ThreadStartGenerics.sh: line 243: 11273 Segmentation fault      $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 139
               END EXECUTION - FAILED
               Expected: 0
               Actual: 1
               END EXECUTION - FAILED
FAILED   - baseservices/threading/paramthreadstart/ThreadStartGenerics/ThreadStartGenerics.sh
               BEGIN EXECUTION
               /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs2_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun ThreadStartGenerics.exe min
               ./ThreadStartGenerics.sh: line 243: 11353 Segmentation fault      $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 139
               END EXECUTION - FAILED
```

Note that these failed 4 consecutive runs.

**Comment by CarolEidt** [comment]
@BruceForstall - I'm wrapping up the last desktop arm bug (I think), so this seems like the next logical bug for me to work on, since it's using jitStressRegs. However, it's non-obvious to me exactly what this job is - I gather that this is a cross-build, but it must be actually running on arm for there to be runtime failures.
Can you clarify the workflow to repro this?

**Comment by BruceForstall** [comment]
It's Linux/arm32. The cross build is done in Docker on Linux/x64, with results zip'ed/copied to the arm32 box. One way to figure out how to repro is follow the CI job definitions (unfortunately, these aren't yet merged to master). For now, maybe I'll try to set up a repro machine for you.

**Comment by BruceForstall** [comment]
This still appears in the CI, but I'm unable to reproduce it locally. I'll leave this open and check again when the CI changes are live in master.

**Comment by BruceForstall** [comment]
I don't see this in the current master branch.
