### ISSUE TITLE
Span<double> significantly (3-4 times) worse than double[]

### ISSUE THREAD

**Issue by manofstick** [dotnet/coreclr#16979]
Following some discussion [begun here](https://stackoverflow.com/questions/49308115/c-sharp-vectordouble-copyto-barely-faster-than-non-simd-version-and-bad-span), I have created a example where access to a `Span<double>` is 3 to 4 times worse than a `double[]` - unless I'm doing something stupid (which hey, is possible...)

    using System;
    using System.Diagnostics;
    using System.Linq;

    namespace ThisIsNotSoGood
    {
        class Program
        {
            public static void daxpy_naive1(double alpha, double[] x, double[] y)
            {
                for (var i = 0; i < x.Length; ++i)
                    y[i] = y[i] + x[i] * alpha;
            }

            public static void daxpy_naive2(double alpha, double[] x, double[] y)
            {
                for (var i = 0; i < x.Length; ++i)
                    y[i] += x[i] * alpha;
            }

            public static void daxpy_span1(double alpha, Span<double> x, Span<double> y)
            {
                for (var i = 0; i < x.Length; ++i)
                    y[i] = y[i] + x[i] * alpha;
            }

            public static void daxpy_span2(double alpha, Span<double> x, Span<double> y)
            {
                for (var i = 0; i < x.Length; ++i)
                    y[i] += x[i] * alpha;
            }

            static void RunSillyTest(string name, Action f, double[] b)
            {
                for (var ii = 0; ii < 1; ++ii)
                {
                    var total = 0.0;
                    var sw = Stopwatch.StartNew();
                    for (var i = 1; i <= 100000; ++i)
                        f();
                    var time = sw.ElapsedMilliseconds;
                    total += b.Sum();
                    Console.WriteLine($"{name}: {time} (checksum={total})");
                }
            }

            static void Main(string[] args)
            {
                var r = new Random();
                var a = Enumerable.Range(0, 10000).Select(i => r.NextDouble()).ToArray();
                var b_orig = Enumerable.Range(0, a.Length).Select(i => r.NextDouble()).ToArray();

                double[] b;

                b = b_orig.ToArray();
                RunSillyTest("daxpy_naive", () => daxpy_naive1(0.001, a, b), b);

                b = b_orig.ToArray();
                RunSillyTest("daxpy_naive", () => daxpy_naive2(0.001, a, b), b);

                b = b_orig.ToArray();
                RunSillyTest("daxpy_span1", () => daxpy_span1(0.001, a, b), b);

                b = b_orig.ToArray();
                RunSillyTest("daxpy_span2", () => daxpy_span2(0.001, a, b), b);
            }
        }
    }

And built, run with:

    PS> dotnet --version
    2.1.101
    PS> dotnet build -c release
        ...
    PS> dotnet run -c release
    daxpy_naive1: 728 (checksum=507359.418169168)
    daxpy_naive2: 771 (checksum=507359.418169168)
    daxpy_span1: 2633 (checksum=507359.418169168)
    daxpy_span2: 2014 (checksum=507359.418169168)

**Comment by jkotas** [comment]
What is netcoreapp version in your .csproj file?

**Comment by manofstick** [comment]
Test.csproj

    <Project Sdk="Microsoft.NET.Sdk">

      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.0</TargetFramework>
      </PropertyGroup>

      <ItemGroup>
        <PackageReference Include="System.Memory" Version="4.5.0-preview1-26216-02" />
      </ItemGroup>

    </Project>

Looks like I ain't got .NET Core 2.1 SDK... I'll install and try again...

**Comment by manofstick** [comment]
@jkotas 

Hmm. Actually downloaded and tried to install (from [here](https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.101-windows-x64-installer)), and it says its installed! But if I change `netcoreapp2.0` to `netcoreapp2.1`  then I get the error:

    C:\Program Files\dotnet\sdk\2.1.101\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [C:\temp\xxxx\Test\Test.csproj]

**Comment by jkotas** [comment]
https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-net-core-2-1-preview-1/ has good links to install .NET Core 2.1 Preview 1 from. Sorry about the confusing version numbers.

**Comment by manofstick** [comment]
@jkotas 

OK, all good!

2.1.300-preview1-008174  did the trick.

Although the += version is ~ 10% slower - but that's a different question I guess...
