### ISSUE TITLE
Native library loading does not try "lib" prefix when trying specific search paths

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#1698]
NDirect::LoadLibraryModule tries several specific search paths before trying to load the library directly using the system default search paths. These include the directory of the assembly with the DllImport attribute, and native search paths provided by the host. When trying these specific search paths, an absolute path is sent to PAL's LoadLibrary, and for absolute paths prefixing is not attempted. At least when DllImport only specifies a library name without a path, "lib" prefixing should be attempted for all search paths tried.

**Comment by kouvel** [comment]
@adityamandaleeka, you had mentioned this before, are you already looking at it?

**Comment by masonwheeler** [comment]
This should be closed as As Designed.  See my comments on #1780 for the rationale. (TLDR: doing this or anything like it opens up a DLL Injection security hole.)

What needs to be done instead is to expand upon (or possibly replace) `DllImport` with some mechanism that lets the coder explicitly specify the correct import names for multiple platforms, whereas `DllImport` currently only supports a single import platform.

**Comment by adityamandaleeka** [comment]
This problem was fixed (and discussed further) in #1780. Closing this issue.
