### ISSUE TITLE
Proprietary dependencies in dotnetcore

### ISSUE THREAD

**Issue by dragonchaser** [dotnet/coreclr#16987]
Hi,

we are wondering if there is any proprietary code in the sources of the packages or its dependencies used to build dotnet core on linux.
https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/copyright.md#binary-license4 states that everything bundled as binary is to be threaded as MIT license. Unfortunately we do not want to use pre-build binaries but want to “brew” our own.

Thanks & regards
Christian

**Comment by 4creators** [comment]
This issue is discussed and handled in  https://github.com/dotnet/source-build repo. Specifically it was discussed and agreed that the whole build should be source based including all tools.

see https://github.com/dotnet/source-build/issues/187#issuecomment-332875712 and following discussion.
