### ISSUE TITLE
Test builds use different casing for transport feeds, breaking the build

### ISSUE THREAD

**Issue by MattGal** [dotnet/coreclr#16990]
After initially suspecting that this was a leftover problem from secret cycling, I realize it’s not, rather it’s a URL casing issue.

Specifically the product builds put their transport feed here:
http://dotnetbuildoutput.blob.core.windows.net/coreclr-master-20180316-02/DotNet-CoreClr-Master-1832/Release/pkg/index.json  (works)

Then the test builds try to use a transport feed like this:
https://dotnetbuildoutput.blob.core.windows.net/coreclr-master-20180316-02/DotNet-CoreClr-Master-1832/**r**elease/pkg/index.json 
 
The R in release having different casing breaks the transport feed.  It may be related to recent changes to prevent blob collisions? 

@RussKeldorph , @jashook , @wtgodbe  FYI.

**Comment by MattGal** [comment]
The root of this problem is the following variable:

```
    "IntermediateAzureFeed": {
      "value": "https://dotnetbuildoutput.blob.core.windows.net/$(ParentContainerName)/$(ParentBlobNamePrefix)$(ParentBuildType)/pkg/index.json"
    },

When it succeeds:
/p:IntermediateAzureFeed=https://dotnetbuildoutput.blob.core.windows.net/coreclr-master-20180316-03/DotNet-CoreClr-Master-1832/Release/pkg/index.json

When it fails:
/p:IntermediateAzureFeed=https://dotnetbuildoutput.blob.core.windows.net/coreclr-master-20180316-04/DotNet-CoreClr-Master-1832/release/pkg/index.json

```

**Comment by MattGal** [comment]
@RussKeldorph I found your root cause.  See this build:
https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1485356

Specifically:
```
2018-03-16T13:36:08.2599942Z Found parameter ParentBlobNamePrefix with value: DotNet-CoreClr-Master-1832/
2018-03-16T13:36:08.2600694Z Found parameter ParentBuildType with value: release
```
Which is coming from property "BuildConfiguration" in the failing case.  Simply making the default value here be "Release" should fix your issue but may have other random fallout if you depend on its casing somewhere else.  (I can make this change if you want, but I may not have time to chase the other problems)

**Comment by RussKeldorph** [comment]
@mattgal Thanks.  Test build queued: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1487317&_a=summary
