### ISSUE TITLE
[Arm64/Ubuntu] Recent regression to JIT/Directed/RVAInit/oddsize

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17008]
`JIT/Directed/RVAInit/oddsize/oddsize.sh`

```
corerun oddsize.exe

Assert failure(PID 42610 [0x0000a672], Thread: 42610 [0xa672]): 
Assertion failed 'obj->gtIntCon.gtIconVal == 0' in 'Test:Main():int' (IL size 13)

    File: src/jit/compiler.hpp Line: 4358
```

First failure observed on d6b2ead7f
Last observed pass on 7ee3f6360

**Comment by tannergooding** [comment]
This is also impacting x86 and x64

**Comment by BruceForstall** [comment]
Looks like this was caused by https://github.com/dotnet/coreclr/pull/16966.

You can see this from the job where this started failing on Windows x86: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt/

@AndyAyersMS PTAL. IMO, revert to fix the pervasive job failures.
