### ISSUE TITLE
dotnet.exe has stopped working saying can't load coreclr.pdb

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/coreclr#17016]
@jaydeept commented on [Fri Jan 19 2018](https://github.com/dotnet/core/issues/1230)

This issue I have already reported [here](https://github.com/aspnet/Home/issues/2798) but just wanted to make sure it's reported at right place.

---

@jaydeept commented on [Fri Jan 19 2018](https://github.com/dotnet/core/issues/1230#issuecomment-358991466)

aspnet/Home#2798

**Comment by mikem8361** [comment]
@jaydeept do you have the Microsoft Symbol Server enabled in the Symbols option menu? 

I checked the .NET Core 2.0.5 coreclr.pdb and it is on the above symbol server.

**Comment by mikem8361** [comment]
I noticed in the screen capture in https://github.com/aspnet/Home/issues/2798 you didn't have the Microsoft Symbol Server checked in the Options->Debug->Symbols menu.

That would explain why you are not loading symbols for coreclr.pdb.

**Comment by mikem8361** [comment]
I haven't seen any response to my previous comment so I assume there isn't any issue anymore.
