### ISSUE TITLE
Add support for self-modyfing code to JIT and CoreRT. Make C#/IL faster than C++

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/coreclr#17032]
Self-modifying code is a code that modyfies itself through execution (https://en.wikipedia.org/wiki/Self-modifying_code)
JIT (RuiJIT) is already a sort of self-modifying code. RuiJIT + Roslyin in general already have all required infrastructure to create advanced self-modifying code.

Primary target:
1) Event-loop with specialized event invocation.
``` CSharp 
/// ------------------ Tradiltional event loop example: ---------------------------------
public class EventLoop
{
       private readonly Queue<Action> _eventsQueue = new Queue<Action>();
       public void PostUnsafe(Action a){
             _eventsQueue.Enqueue(a);
       }

       //...

       public void DoEvents()
       { 
            while(_eventsQueue.TryDequeue(out var a)
            {
                  try
                  {
                        // 1) Action should be created (2 times GC allocation)
                        // 2) One Virtual-call
                        // 3) For async-await statemachines another overhead is required to pass-back result of action execution.
                        a();

                        // Finally Action-based event loops have ~60 Mops/sec maximal performance
                        // And 10 Mops/sec for special (Non-TPL based) async/await state machines
                  }
                  catch
                  {
                       // ..
                  }
            }
       }

       public void Run()
       {
              while(_exitRequested)
              {
                   DoEvents();
                   WaitEventScheduled();
              }
       }

       // ....
}

/// -------------------------- Self-modifying code approach: -------------------
public class LightSpeedEventLoop:
{
       private readonly ExecutionStream _eventLoop = new ExecutionStream();
       
       // ...

       [MethodImpl(MethodImplOptions.AggressiveInlining)]
       public Span<byte> PostUnsafe(int size)
       {
              // Must also be inlined
             return _eventLoop.GetNextCodeSpace(size);
       } 

       public void Run()
       {
              while(_exitRequested)
              {
                    // Executes all written x86/Arm  instructions until becomes empty.
                    _eventLoop.Run();
                    WaitEventScheduled();
              }
       }
}

// CompilerServices class for generating native code
public class NativeCodeCallGenerator<TThis, TArg1, TArg2>
{
        public NativeCodeCallGenerator(Expression<Action<TThis>> callExpression, bool allowInline = false)
        {
              // Binary template should be prepared here (OMG it's a kind of magic)
        }
        public int Size {get;}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Generate(Span<byte> target, TThis obj, TArg1 a, TArg2 b)
        {
              // Also super optimized way to write instructions
        }
}

public class MyEventLoopUser
{
       public static readonly NativeCodeCallGenerator<MyEventLoopUser, int, string> _myEvHandlerCallGenerator = 
            new NativeCodeCallGenerator<MyEventLoopUser, int, string>(u=>u.MyHandler(0, null));
       
       public void MyHandler(int i, string s)
       {
            // TODO: Do event handling
       }

       public void DoSomething()
       {
             // Scheduling should takes ~ 4-10 CPU instructions
             // Call should takes ~ 4 CPU instructions
             // In theory we can get up to 200+ Mops/sec of the event loop itself
             // And also 200+ Mops/sec of the new "async/await" state machines (now true coroutines)
             // No any language have so fast coroutines yet, with such tool it's possible to do 10M+ request per second in plain text (https://www.techempower.com/benchmarks/#section=data-r15&hw=ph&test=fortune).
             
             // That's how we schedule specialized callback
             var codeSpace = LightSpeedEventLoop.Current.Post(_myEvHandlerCallGenerator.Size);
             _myEvHandlerCallGenerator.Generate(this, 10, "The string");
            
             // Do something else 
       }
}

```

Other benefits:

It's like an SSE4 CPU boost but on a compiler-side, so specially compiled C# code can runs even faster than super optimized C++ code with latest GCC.

CLR is a closest one runtime than can bring "self-modifying code" benefits to the every-day programming.
Self-modifying code have huge undiscovered potential, mary "under the hood" CoreFX parts can be re-implemented with more than 10x speed up.

Problems: 
1) Exceptions
2) Reference object pinning
3) Debugging
4) OS Security Policy

**Comment by svick** [comment]
1. There are existing and proposed ways to avoid allocations for delegates (`state` object, static delegates https://github.com/dotnet/csharplang/issues/302), I think they make this proposal less useful.
2. I would like to see some evidence about the claimed 10× speedup in real-world scenarios. Especially consider that in most cases, the code called from an event loop is more than just a few instructions, so changing one virtual call to non-virtual might not have significant effect.
3. More specifically, do you have evidence showing that event loop dispatch is what's slowing down the `plaintext` TechEmpower benchmark?
4. You say that this approach would make `async`-`await` state machines more efficient. Can you elaborate on how would this proposal achieve that?
5. You claim that many parts of CoreFX could benefit from this. Can you explain which parts those are and how would they benefit?
6. This sounds like something that you could do on your own. You would allocate native memory with the execute bit set (you can do that using `VirtualAlloc` on Windows), then get address of the code you want to invoke (probably with a manually written IL method using `ldftn` today and static delegate or compiler intrinsic `ldftn` https://github.com/dotnet/roslyn/issues/11475 in the future) and finally generate the right native code to call the method. Though it's possible I overlooked something and that this approach would not actually work.

**Comment by mikedn** [comment]
I'm not sure what exactly do you need additional CLR support for this. "Self modifying code" is a fancy name for runtime code generation, something that has been available in .NET since day 1 via reflection emit and more recently through higher level features such as `System.Linq.Expressions`.

Yes, CoreRT doesn't support that but then that's an issue for the CoreRT repo.

**Comment by dmitriyse** [comment]
> I'm not sure what exactly do you need additional CLR support for this. "Self modifying code" is a fancy name for runtime code generation, something that has been available in .NET since day 1 via reflection emit and more recently through higher level features such as System.Linq.Expressions.

1) Probably some improvements are required. Because only JIT can generate x86/64/ARM/... instructions. 2) Also JIT possibly compiles whole method at once and have no any methods to generate "compatible" with each other code from blocks of IL instructions.
3) Patching. Generated x86/64/ARM/... code should be written to target with patches. I thinkg there are no any patching ability in API

**Comment by mikedn** [comment]
1. Ah, so you want a way to emit native code directly? That's the kind of thing that sounds nice in theory but it's likely to be messy in practice. It's not like you can emit whatever native code you want, you have to integrate with the runtime (calling conventions, GC write barriers, call various helpers etc.). That's going to make this a rather costly/complex feature with unclear potential...
2. Probably you're thinking of something like inline assembly in C/C++. But that's a very different thing as it actually works in the "whole method at once" manner. It's not really feasible to generate a block of code that is "compatible" with code that has already been generated.
3. Yeah, with the existing features this is implicitly achieved by calling the generated code via a delegate. That's probably not what you have in mind but due to 2. above it probably won't get better. At best, you could probably replace an entire method with new code with some hypothetical runtime support.

**Comment by dmitriyse** [comment]
Probably there is another approach simpler than Self-modifying code.
But I did not found any one yet.
That's my task description:
1) Single-threaded environment and no any synchronization requied, not any race conditions, memory barriers, etc.
2) I need an event loop that can run scheduled tasks sequencially
3) task is a C# return-less method with unpredictable in-only arguments set, plus some-how stored arguments for the method. So every task can have different amount of corresponding data
4) I should avoid any object allocation or I need to use super fast object pooling 1~4 il instructions.
5) Only one virtual-call / non-virtual call per task is allowed.

This problem cannot be solved in the current C# language and I suggest even in the current IL .

**Comment by BruceForstall** [comment]
This discussion is stale; I'm going to close the issue.
