### ISSUE TITLE
Missing information about LTS on download page

### ISSUE THREAD

**Issue by rhegner** [dotnet/coreclr#17031]
The .NET Core download page used to have a clear separation between Current and LTS releases.

This information is missing on the [current page](https://www.microsoft.com/net/download/windows/run).

I want to upgrade my project from 1.1 to 2.0 as soon as there is a LTS version of 2.0 available. But I can't see from that website if 2.0.6 is a LTS version or not.

**Comment by shahid-pk** [comment]
2.0.0 is LTS, 2.0.* is bug fixes version so the latest the better and more bug fixes. 1.0.* was LTS and still is. But yes it should be mentioned somewhere if not already.

**Comment by RussKeldorph** [comment]
This issue was moved to dotnet/core#1360
