### ISSUE TITLE
[RyuJIT] Refactor the codegen/emitter for MOVD/MODQ

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#17051]
The codegen/emitter of `MOVD`/`MODQ` is very messy in the current backend. 
It has several "instructions" to generate `MOVD`/`MODQ` (e.g., `mov_i2xmm`, `mov_xmm2i`, `movd`, and `movd`), but the codegen is not consistent. 
For example, `mov_i2xmm` can generate `MOVD` and `MOVQ` based on different emit-size, but it just accepts some of the valid sizes. 
```cpp
INST3( mov_i2xmm,   "movd"        , 0, IUM_WR, 0, 0, BAD_CODE,     BAD_CODE, PCKDBL(0x6E)) 
INST3( mov_xmm2i,   "movd"        , 0, IUM_WR, 0, 0, BAD_CODE,     BAD_CODE, PCKDBL(0x7E)) 
INST3( movd,        "movd"        , 0, IUM_WR, 0, 0, PCKDBL(0x7E), BAD_CODE, PCKDBL(0x6E))
INST3( movq,        "movq"        , 0, IUM_WR, 0, 0, PCKDBL(0xD6), BAD_CODE, SSEFLT(0x7E))
```

cc @CarolEidt @tannergooding

**Comment by mikedn** [comment]
> For example, mov_i2xmm can generate MOVD and MOVQ based on different emit-size, but it just accepts some of the valid sizes.

What do you mean? It sounds like a contradiction, either it can generate based on different emit-size or it can't because there are only 2 valid sizes.

**Comment by fiigii** [comment]
For example, `mov_i2xmm` + `64-bit` can generate `MOVQ xmm, rax`, but `mov_i2xmm` + `32-bit` does not work, we need `mov_i2xmm` + `128-bit` to generate `MOVD xmm, eax`.

**Comment by mikedn** [comment]
> For example, mov_i2xmm + 64-bit can generate MOVQ xmm, rax, but mov_i2xmm + 32-bit does not work, we need mov_i2xmm + 128-bit to generate MOVD xmm, eax.

Seems to be working fine for me:
```C++
getEmitter()->emitIns_R_R(INS_mov_i2xmm, EA_4BYTE, REG_XMM6, REG_RDX);
getEmitter()->emitIns_R_R(INS_mov_i2xmm, EA_8BYTE, REG_XMM5, REG_RBX);
getEmitter()->emitIns_R_R(INS_mov_xmm2i, EA_4BYTE, REG_XMM4, REG_RCX);
getEmitter()->emitIns_R_R(INS_mov_xmm2i, EA_8BYTE, REG_XMM3, REG_RAX);
```
generates
```asm
C4E1796EF2           vmovd    xmm6, edx
C4E1F96EEB           vmovd    xmm5, rbx
C4E1797EE1           vmovd    ecx, xmm4
C4E1F97ED8           vmovd    rax, xmm3
```

**Comment by fiigii** [comment]
@mikedn Oh, you are right! I used the wrong emit-size in https://github.com/dotnet/coreclr/pull/17030 (should be `emitActualTypeSize` rather than `emitTypeSize`). Thank you!
