### ISSUE TITLE
CoreCLR failed when build with permissive- + MSVC on windows.

### ISSUE THREAD

**Issue by QuellaZhang** [dotnet/coreclr#17063]
CoreCLR failed with error C2760: syntax error: unexpected token 'identifier', expected ';'  when build with permissive- on Windows, I use latest source on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

You can repro this issue as the steps below:
1.	git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2.	Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\CoreCLR\src
3.	set  _CL_=/permissive-
4.	build x86 release -Rebuild -- /clp:ShowCommandLine
Error info:
d:\coreclr\src\src\vm\rcwrefcache.h(56): error C2760: syntax error: unexpected token 'identifier', expected ';'

**Comment by jkotas** [comment]
@QuellaZhang Feel free to submit a fix for this.
