### ISSUE TITLE
[Arm64] Remove HACK -- Arm64 does not have corefx jobs yet

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17069]
https://github.com/dotnet/coreclr/blob/master/netci.groovy#L2149

CoreFX Arm64 CI jobs are being enabled.  Hopefully https://github.com/dotnet/corefx/pull/28250 will be the last required patch

**Comment by RussKeldorph** [comment]
Hint: press 'y' after clicking the link above to get perma-link

https://github.com/dotnet/coreclr/blob/e431eb23fc21b773c17b96bb0f8189597d436b98/netci.groovy#L2149

**Comment by sdmaclea** [comment]
@RussKeldorph Thanks

**Comment by sdmaclea** [comment]
Fixed by #17764
