### ISSUE TITLE
Divergent exception handling between coreclr and desktop CLR

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/coreclr#1707]
Running [this test](https://gist.github.com/JosephTremoulet/9aaea4bbff83a3cbfc8d#file-test-cs) produces [different output](https://gist.github.com/JosephTremoulet/9aaea4bbff83a3cbfc8d#file-output-txt) with CoreCLR vs Desktop CLR (for me).  AFAIK they should behave the same.  The most exotic thing the test does is abort execution of a finally by propagating a new exception out of it.
This was using a fresh debug Windows x64 build of CoreCLR synced to 1f21a82ee179d10882c22952c46617b6c9bc88b4, and I believe the version of Desktop CLR running the test was 4.0.30319.33440 but I'm not sure how to verify that.
/cc @BruceForstall @janvorli

**Comment by janvorli** [comment]
@JosephTremoulet I've tried your test on Linux and it has printed the same result as you've got on the desktop CLR (error code 0).So it seems to be a problem with Windows CoreCLR only.

**Comment by janvorli** [comment]
I've tried it on the current Windows CoreCLR and got the correct output too.
So I wonder what went wrong in your testing. It looks from the test result that all the tests have failed. Have you built your test against the CoreCLR targetting pack? Do you have all the correct platform assemblies in the same folder where you executed corerun.exe?

**Comment by JosephTremoulet** [comment]
> Have you built your test against the CoreCLR targetting pack?

No.  I guess my ad-hoc tests to-date have all been "close enough", so I didn't realize I needed that.


> Do you have all the correct platform assemblies in the same folder where you executed corerun.exe?

Likewise.

Thanks for the help, sorry for the distraction.  I'll follow the [posted steps](https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md) and that should fix my issue.
