### ISSUE TITLE
Consider debug-only checks on Dictionary<K,V> to flag invalid concurrency

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#17070]
We could add some asserts that would deterministically throw if a writer thread and another thread ever entered a Dictionary concurrently.

Although CoreFX doesn't run its regular test runs with CHK corelib, Stress runs do and possibly will introduce enough concurrency when they run their tests (I believe they pick a limited number of tests to focus on) to shake out such a bug in CoreFX code.

**Comment by benaadams** [comment]
I can take this on; Debug mode means I can use interlocked, so can go strong

**Comment by safern** [comment]
Marked as future, but @benaadams if you want to take it might be a nice to have Debug code in 2.1

**Comment by benaadams** [comment]
https://github.com/dotnet/coreclr/pull/17076
