### ISSUE TITLE
Non-inlined ctor significantly slower on Linux than on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#1708]
Here is my repro:
```C#
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;

class Program
{
    static void Main()
    {
        var sw = new Stopwatch();
        MyObject o;
        while (true)
        {
            sw.Restart();
            for (int i = 0; i < 1000000; i++)
            {
#if false
                o = new MyObject();
                o = new MyObject();
                o = new MyObject();
                o = new MyObject();
                o = new MyObject();
                o = new MyObject();
                o = new MyObject();
                o = new MyObject();
                o = new MyObject();
#else
                MyObject.Nop();
                MyObject.Nop();
                MyObject.Nop();
                MyObject.Nop();
                MyObject.Nop();
                MyObject.Nop();
                MyObject.Nop();
                MyObject.Nop();
                MyObject.Nop();
#endif
            }
            sw.Stop();
            Console.WriteLine(sw.Elapsed);
        }
    }

    class MyObject
    {
        [MethodImpl(MethodImplOptions.NoInlining)]
        internal MyObject() { }

        [MethodImpl(MethodImplOptions.NoInlining)]
        internal static void Nop() { }
    }
}
```
There are three different tests here:
1. Invoking a non-inlineable method (set the #if to false)
2. Constructing an object with a non-inlineable ctor (set the #if to true)
3. Constructing an object with an inlinineable ctor (set the #if to true and comment out the MyObject ctor)

(1) and (3) both perform ~equivalently for me on both my Linux VM and my Windows host.

But (2) is ~10x slower for me on Linux than it is on Windows.

cc: @jkotas, @LLITCHEV, @janvorli

**Comment by stephentoub** [comment]
(As a 4th case, changing the ctor to remove the NoInlining attribute and add a call to Nop() to its body is also ~equivalent for me on both Linux and Windows.)

**Comment by jkotas** [comment]
@kouvel This looks like same problem as the inefficient allocation helpers that you are working on.

cc @sergiy-k

**Comment by kouvel** [comment]
Partially fixed by dotnet/coreclr#1746. Here are my numbers in iterations per second, where each iteration consists of 10,000 calls:
- Allocation and non-inlined constructor (Windows): 10047
- Allocation and non-inlined constructor (Linux): 1277 (baseline), 4442 (fixed)

Leaving the issue open since there is still a considerable gap.

**Comment by kouvel** [comment]
The inlining itself doesn't seem to make any difference for me, just the allocation part. Case 3 above is also performing similarly to above.

**Comment by kouvel** [comment]
Almost all of the remaining difference is in GetThread. There isn't an easy fix for this, so we are currently not planning on addressing this. We can take another look if we see this to be a significant issue in user scenarios.

**Comment by stephentoub** [comment]
Does this mean https://github.com/dotnet/corefx/issues/3588 and https://github.com/dotnet/corefx/issues/3590 should also be closed?

**Comment by kouvel** [comment]
Ah yes they're all the same issue, I have closed the others now as well.
