### ISSUE TITLE
Slow span with stackalloc on netcoreap 2.1-preview1-final

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/coreclr#17093]
Scenario:
I'm generating Guids and modify some values to form a CombGuid, so I thought with netcoreapp2.1 I can use ``Span<byte>`` for it. Well for some reason, as soon as I use ``Span<byte>`` and especially ``Span<byte>`` with stackalloc it's slower than the simple ``ToByteArray``.
As far as I see the ctor of the Guid with the Span (conversion to ReadOnlySpan?) is doing way much more work than the non Span versions,  even though the ``byte[]`` ctor of Guid is doing a ``AsReadOnlySpan`` too.
https://github.com/dotnet/coreclr/blob/e2ff69f7cbcfe120414ff0e3130eaa48a252ab34/src/mscorlib/shared/System/Guid.cs#L42-L45

Repro:
I removed all the modification code to make sure I do nothing else.
```csharp
[MemoryDiagnoser]
[DisassemblyDiagnoser]
public class Benchmark
{

    [Benchmark]
    public Guid CombGuidHeap()
    {
        var guidArray = Guid.NewGuid().ToByteArray();
        return new Guid(guidArray);
    }

    [Benchmark]
    public Guid CombGuidSpanHeap()
    {
        Span<byte> span = new byte[16];
        Guid.NewGuid().TryWriteBytes(span);
        return new Guid(span);
    }

    [Benchmark]
    public Guid CombGuidStackalloc()
    {
        Span<byte> span = stackalloc byte[16];
        Guid.NewGuid().TryWriteBytes(span);
        return new Guid(span);
    }
}
```

The output is:
``` ini

BenchmarkDotNet=v0.10.13, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.248)
Intel Xeon CPU E5-1620 0 3.60GHz, 1 CPU, 8 logical cores and 4 physical cores
Frequency=3507174 Hz, Resolution=285.1299 ns, Timer=TSC
.NET Core SDK=2.1.300-preview1-008174
  [Host]     : .NET Core 2.1.0-preview1-26216-03 (CoreCLR 4.6.26216.04, CoreFX 4.6.26216.02), 64bit RyuJIT
  DefaultJob : .NET Core 2.1.0-preview1-26216-03 (CoreCLR 4.6.26216.04, CoreFX 4.6.26216.02), 64bit RyuJIT


```
|             Method |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
|------------------- |---------:|----------:|----------:|-------:|----------:|
|       CombGuidHeap | 113.1 ns | 0.0892 ns | 0.0835 ns | 0.0075 |      40 B |
|   CombGuidSpanHeap | 124.5 ns | 0.8079 ns | 0.7557 ns | 0.0074 |      40 B |
| CombGuidStackalloc | 142.5 ns | 0.5711 ns | 0.5062 ns |      - |       0 B |

Beause I can't attach an html as the output of the disassembler, I created a JSFiddle for that: https://jsfiddle.net/60rjd863/

**Comment by AndyAyersMS** [comment]
You should see some improvement from #16220. This is not in preview1 but will be in preview2.

**Comment by AndyAyersMS** [comment]
Just to follow up, with latest master (approximately what will be in preview2) I see comparable performance:

```
CombGuidHeap: 124.2887ns
CombGuidSpanHeap: 135.8442ns
CombGuidStackalloc: 121.5926ns
```
Codegen for `CombGuidSpanHeap` and `CombGuidStackalloc` is also comparable. Former has some extra overhead for the heap allocation/array creation which makes it slower. Latter has a bit of extra code at the end to verify the stack cookie but that is fairly cheap.

**Comment by AndyAyersMS** [comment]
Let me know if you would like to verify this is fixed for you with more recent builds, and we'll leave this open until you do.

**Comment by Tornhoof** [comment]
Thank you for your tests, with that new fancy benchmarkdotnet feature to run any corefx/coreclr build I checked that it is indeed faster on ore recent builds (albeit on a different system):

``` ini

BenchmarkDotNet=v0.10.13, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.309)
Intel Core i7-4790K CPU 4.00GHz (Haswell), 1 CPU, 8 logical cores and 4 physical cores
Frequency=3906246 Hz, Resolution=256.0003 ns, Timer=TSC
.NET Core SDK=2.2.0-preview1-007813
  [Host]     : .NET Core 2.1.0-preview1-26013-05 (CoreCLR 4.6.26013.03, CoreFX 4.6.26013.06), 64bit RyuJIT
  Job-GGWGQE : .NET Core ? (CoreCLR 4.6.26308.06, CoreFX 4.6.26307.06), 64bit RyuJIT
  Job-ATQFPZ : .NET Core ? (CoreCLR 4.6.26319.06, CoreFX 4.6.26319.04), 64bit RyuJIT


```
|             Method |              Toolchain |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
|------------------- |----------------------- |---------:|----------:|----------:|-------:|----------:|
|       CombGuidHeap | myget builds preview 2 | 83.37 ns | 0.8569 ns | 0.8015 ns | 0.0094 |      40 B |
|   CombGuidSpanHeap | myget builds preview 2 | 86.33 ns | 0.6654 ns | 0.5195 ns | 0.0094 |      40 B |
| CombGuidStackalloc | myget builds preview 2 | 87.56 ns | 0.0846 ns | 0.0750 ns |      - |       0 B |
|       CombGuidHeap | myget builds preview 3 | 82.69 ns | 0.2958 ns | 0.2767 ns | 0.0094 |      40 B |
|   CombGuidSpanHeap | myget builds preview 3 | 85.06 ns | 0.0644 ns | 0.0603 ns | 0.0094 |      40 B |
| CombGuidStackalloc | myget builds preview 3 | 87.36 ns | 0.0422 ns | 0.0374 ns |      - |       0 B |

I close this bug now.
