### ISSUE TITLE
Arm64 Ubuntu CI test failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17095]
The debug/checked/release "small page size" test jobs all fail with:
```
21:55:10 + cp ./bin/Product/Linux.arm64.Debug/corefxNative/System.IO.Compression.Native.a ./bin/Product/Linux.arm64.Debug/corefxNative/System.IO.Compression.Native.so ./bin/Product/Linux.arm64.Debug/corefxNative/System.Native.a ./bin/Product/Linux.arm64.Debug/corefxNative/System.Native.so ./bin/Product/Linux.arm64.Debug/corefxNative/System.Net.Http.Native.a ./bin/Product/Linux.arm64.Debug/corefxNative/System.Net.Http.Native.so ./bin/Product/Linux.arm64.Debug/corefxNative/System.Net.Security.Native.a ./bin/Product/Linux.arm64.Debug/corefxNative/System.Net.Security.Native.so ./bin/Product/Linux.arm64.Debug/corefxNative/System.Security.Cryptography.Native.OpenSsl.a ./bin/Product/Linux.arm64.Debug/corefxNative/System.Security.Cryptography.Native.OpenSsl.so ./bin/CoreFxBinDir
21:55:10 cp: target './bin/CoreFxBinDir' is not a directory
21:55:10 
Build step 'Execute shell' marked build as failure
```

e.g.:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_debug_small_page_size_tst/845/console
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_release_small_page_size_tst/818/console
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_checked_small_page_size_tst/810/console

**Comment by BruceForstall** [comment]
cc @jashook @RussKeldorph

**Comment by sdmaclea** [comment]
Does this happen to have to do with the corefx package being on myget
https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.linux-arm64.Microsoft.Private.CoreFx.NETCoreApp conflicting with #17069

**Comment by sdmaclea** [comment]
I was part of the Hack code but until #17123, we need it.
