### ISSUE TITLE
[local gc] LogAlways is not handled correctly for local gc

### ISSUE THREAD

**Issue by davmason** [dotnet/coreclr#17118]
In GCEventStatus::Set https://github.com/dotnet/coreclr/blob/a4845dca1e1edffe07286d0c8ddff04aadab0181/src/gc/gceventstatus.h#L86-L99

If the provider is turned on with LogAlways, the value of level will be 255 and at the very least the assert will fire, I haven't dug through the code path yet and it also may not do what's expected.

**Comment by Maoni0** [comment]
fixed by [#17277](https://github.com/dotnet/coreclr/pull/17277)
