### ISSUE TITLE
Resolving path for .NET core SDK's libraries

### ISSUE THREAD

**Issue by jzielnik** [dotnet/coreclr#17125]
Hello,

I've been working on a project that could load other projects (using Microsoft.Build.Evaluation.Project), however I've encountered an issue. Project class has ICollection AllEvaluatedItems properity but for .NET Core and .NET Standard projects this collection does not have references which can be found under Dependencies/SDK/. 
I've managed to find that after building such project in \obj there is 'project.assets.json' file which contains all paths to those SDK's libraries however there are sometimes multiple versionsof those libs. I have data about loaded project 'TargetFramework' property but sometimes it's not one-to-one match of library path and targeted framework.

Is there some nice and easy way to find out which one of those is loaded by CLR as it must know which one to chose based or project properties? Perhaps some kind of library or algorithm? Or does it need to be checked manually for each lib?

Thanks and regards,
Jakub

**Comment by RussKeldorph** [comment]
Not clear if this is a diag, API, or some other type of question.

**Comment by jzielnik** [comment]
[ConsoleApp4.zip](https://github.com/dotnet/coreclr/files/1852436/ConsoleApp4.zip)

Attaching minimal example (newly created project). When I open attached solution in VS, I can see in Dependencies>SDK>Microsoft.NETCore.App a list of assemblies and nuget packages, for example "Microsoft.NETCore.DotNetHostPolicy (2.0.0)" and "Microsoft.CSharp.dll". How can I get full paths to those assemblies?

**Comment by tobyash86** [comment]
>  How can I get full paths to those assemblies?

Based on the first comment in this thread I assume you want to resolve those assembly paths by analyzing the project which has those references defined.

I have exactly the same problem. There is a similar question #13778 and coreclr team suggests using shared\Microsoft.NETCore.App\ directory in dotnet installation folder, but locating it is not that simple as it can be deployed anywhere on the HDD. Is getting this location from PATH variable really the best option?? 

Also, the directory contains multiple versions folders inside, how to pick the proper one based on my project configuration?

And I think this is still not enough as I need to resolve location for each referenced assembly in the analyzed project. With project references or assembly references, it should be quite easy (these are defined in .csproj) but I see some additional scenarios which may cause resolving dependencies quite challenging:

- resolving paths of nuget packages - should I search in %userprofile%\.nuget\packages ? Is it sufficent for nuget packages?
- there are some other "internal dotnet" references like Microsoft.NETCore.Platforms which is not located within shared\Microsoft.NETCore.App\ but in sdk\NuGetFallbackFolder. 
- I have noticed that there are also other subfolders in dotnet installation folder like 'sdk', 'shared' or 'store'. Does all of them contain assemblies which can be referenced to a project?
- are there any other assembly locations I am missing?

If there is no clear answer to my question, could you at least guide me to the implementation of the algorithm which loads those assemblies in runtime, so I could at least create my own implementation which will guess which assemblies should be loaded by my analyzed project?

**Comment by tobyash86** [comment]
Basically, I am implementing code analyzer using Roslyn and I need to pass these assemblies into the parser to resolve types from them. Currently, I am using data from projects.assets.json file to get those paths.

**Comment by jeffschwMSFT** [comment]
Great.  I am going to close this question for now.  But feel free to reach out if you have any other questions.  We are actively looking into loading dependencies so all this feedback is appreciated.

**Comment by jkotas** [comment]
> I am implementing code analyzer using Roslyn and I need to pass these assemblies into the parser to resolve types from them

You may get better answer to your question in https://github.com/dotnet/roslyn-analyzers or https://github.com/dotnet/sdk repos. CoreCLR repo is not the best place to ask questions about the build tooling.

**Comment by tobyash86** [comment]
> We are actively looking into loading dependencies so all this feedback is appreciated.

Great, I will be looking forward for some usable solution.

> You may get better answer to your question in https://github.com/dotnet/roslyn-analyzers or https://github.com/dotnet/sdk repos. CoreCLR repo is not the best place to ask questions about the build tooling.

I wasn't asking how to pass dependencies into Roslyn - I am already doing it. I was asking how to locate project dependencies which are used at compile time. Using projects.assets.json is far from perfect. I was looking for some schema for it, but I have found notning.
