### ISSUE TITLE
Implement AVX MaskStore

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#17127]
The class of `Avx` has <del>three</del> one intrinsic not available in .NET Core 2.1:
- <del>`ZeroAll` and `ZeroUpper` are tricky for test cases.</del>
- `MaskStore` has a design issue https://github.com/dotnet/coreclr/issues/17058.

I will address this issue for post-2.1.

cc @tannergooding @CarolEidt @eerhardt @4creators

**Comment by CarolEidt** [comment]
> `ZeroAll` and `ZeroUpper` are tricky for test cases.

The trickiness here is more than just test cases. Since these impact register contents, and specific register assignments (or even whether values are even *in* registers) is not exposed to developers, we need to clearly specify the semantics of these instructions, and the specific scenarios in which they and and should be used.

**Comment by mikedn** [comment]
What's the use case for `ZeroAll` and `ZeroUpper`?

**Comment by CarolEidt** [comment]
> What's the use case for ZeroAll and ZeroUpper?

`ZeroUpper` would be used to avoid penalties when transitioning between SSE and AVX code. These are generated by the JIT when it is generating AVX code, but the thought is that some developers may want to have direct control over this. That said, I'm rather uncertain that exposing these is the right thing to do - hence the desire to see the scenarios elucidated.

**Comment by mikedn** [comment]
> would be used to avoid penalties when transitioning between SSE and AVX code

AFAIK it's a bit more specific than that - it's about transitioning between VEX and non-VEX encoded instructions. But since the JIT will always use VEX when it's available, even when SSE intrinsics are used, I don't see how such transitions could occur inside a method. So I see no reason for these intrinsics to be exposed.

**Comment by CarolEidt** [comment]
> the JIT will always use VEX when it's available, even when SSE intrinsics are used

Yes that's true - however, the developer may be invoking native code that they know is using non-VEX-encoded instructions. AFAIK this will be covered by existing JIT code that addresses such boundaries (in fact, I think it's a bit conservative about issuing them when it could prove they weren't needed). So, I still don't see a scenario.

**Comment by fiigii** [comment]
> specific register assignments (or even whether values are even in registers) is not exposed to developers, we need to clearly specify the semantics of these instructions

I agree. We have decided that only provide "deterministic" semantics for users, which is a good reason to not expose these two intrinsics.

**Comment by 4creators** [comment]
> only provide "deterministic" semantics for users

IMO we should consider providing `non-deterministic` `unsafe` class(es) which would contain code which is not recommended to be used for standard coding. This would follow similar decision made earlier to expose `Unsafe` which is available for corner cases in performance critical code. That class could comprise other intrinsics as well i.e. scalar loads which will not zero other elements in Vector.

The main reason for this is that HW Intrinsics are created for advanced, high performance scenarios where users anyway will use any available semantic to get maximum performance without bothering with using `unsafe` and dangerous coding patterns.

**Comment by mikedn** [comment]
> The main reason for this is that HW Intrinsics are created for advanced, high performance scenarios where users anyway will use any available semantic to get maximum performance including unsafe and dangerous code.

In the specific case of ZeroUpper and ZeroAll this doesn't mean anything without a clear use case. It's basically marketing speech.

**Comment by CarolEidt** [comment]
So, to summarize, unless and until there is a compelling use case, we won't be supporting ZeroUpper and ZeroAll

**Comment by tannergooding** [comment]
@fiigii, are you going to be working on this soon, or is it something I can move to my plate?

**Comment by fiigii** [comment]
@tannergooding If you have time to pick this up, that would be great, thanks! BTW, I will start to complement the remaining AVX2 intrinsic from next week.
