### ISSUE TITLE
structure of nupkg for targetting multiple frameworks each with different dll

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/coreclr#17120]
I have a c# library. It has some different apis in netstandard than net47.

I want to generate a nupkg which should be usable from both .netfx and coreclr projects. So, if someone creates a fullframework net46/net47 project Or coreclr project targeting netcoreapp2.0, it should pick up dll based on its version.

I have the following structure of nupkg :

```
my_lib.NUPKG
|   my_lib.nuspec
|   [Content_Types].xml
|
+---lib
|   \---net45
|           my_lib.dll
|           my_lib.xml
|
+---package
|   \---services
|       \---metadata
|           \---core-properties
|                   f173822ccbd74dfb9a5338af5508d1b6.psmdcp
|
+---ref
|   \---netstandard2.0
|           my_lib.dll
|
+---runtimes
|   +---linux
|   |   \---lib
|   |       \---netstandard2.0
|   |               my_lib.dll
|   |
|   \---win
|       \---lib
|           +---net461
|           |       my_lib.dll
|           |
|           +---net462
|           |       my_lib.dll
|           |
|           +---net47
|           |       my_lib.dll
|           |
|           +---net471
|           |       my_lib.dll
|           |
|           \---netstandard2.0
|                   my_lib.dll  // this is different from above my_lib.dll
|
\---_rels
        .rels

```

This is working for me. 

However, when user creates a coreclr project targeting net471 using
```
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
  <TargetFramework>net47</TargetFramework>
</PropertyGroup>
```
during compilation, it refers to netstandard2.0 dll and fails to compile. If I comment out the incompatible apis, in the generated build, it has right net47 `my_lib.dll`. This means that during compilation `only`, it is referring to netstandard2.0 dll.  

I think that their might be something wrong with how I have structured my nupkg.
What is the right way for this ? Can you point me to some documentation around this ?

**Comment by ericstj** [comment]
http://github.com/nuget/home is the right place.

Here's a quick answer: whenever there is a an applicable `ref` asset NuGet will prefer that over a `lib` asset.  

My recommendation would be to avoid using `ref` unless you really need to (eg: you need to hide some APIs that are in the implementation).  Moreover you must ensure that any apis exposed by the 'netstandard` assembly are implemented in the framework-specific (eg: `net461`, `net46`, etc) assemblies.  If those APIs aren't implemented folks will hit issues compiling a `netstandard` project against your library then running on the specific framework.

Also, you are not guaranteed to restore `net4*` frameworks with a RID, so I would copy all those to the lib\net4* folders as well.

**Comment by ashishnegi** [comment]
@karelz  By CoreCLR I mean project created during dotnet cli.
I am facing problem when user changes `tragetframework` to `net47` for a project created by dotnet cli.
During compilation, it refers to netstandard2.0 dll and fails to compile as some apis are missing in netstandard2.0 dll.

@ericstj Thanks I will try your suggestion of having folders in ref.
I have a doubt about your comment on issues about apis exposed by netstandard apis.

If a netstandard project compiled against my library runs on specific framework, which assembly will be part of final published package. I think it is netstandard assembly. Is that right ?
If its right, then how will it be a problem as project is compiled against and runs with same assembly.

**Comment by ericstj** [comment]
> If a netstandard project compiled against my library runs on specific framework, which assembly will be part of final published package. I think it is netstandard assembly. Is that right ?

Only if someone redistributes your raw DLL instead of using a package reference.

Packages referenced transitively are resolved in the context of the head project.  Also consider that the head project can directly reference your package and it will get the most appropriate asset for its framework and that supersedes anything a dependency might have used.  That's also how NuGet package dependencies work: if someone builds against your netstandard library and puts their netstandard library in a package, both get referenced from a .NET framework project NuGet chooses the best asset from each for the referencing project's target framework.
