### ISSUE TITLE
[Linux] Unable to catch TargetInvocationException

### ISSUE THREAD

**Issue by mellinoe** [dotnet/coreclr#1713]
I have a test program which I'm using to print out a bunch of information about some types that I am implementing. It basically enumerates all of the properties and methods on an object, invokes them, and prints all of the results out (recursively). If an exception is encountered, I just catch it and print out the exception message, and continue on with the rest of the properties.

I just build the latest source from master and ran my program, and it seems that I'm no longer able to catch any of my PlatformNotSupported exceptions (wrapped in TargetInvocationException). The program just prints out the inner exception message/ stack trace, and terminates. 

The program is here:
https://github.com/mellinoe/NetworkInformationApp/blob/master/src/NetworkInformation.SampleUsage/Program.cs

It's a bit long, but just take a look at, for example, the PrintProperties() method. I'm attempting to catch TargetInvocationException, and print out the inner exception, then just continue on. At runtime, though, I just get a message like:

````
Unhandled Exception: System.PlatformNotSupportedException: Operation is not . . .
    at System.Net.NetworkInformation.....
    at System.RuntimeMethodHandle.InvokeMethod(...)
    ...
````

Which should be the inner exception from my reflection invocation. I would expect that I can catch the TargetInvocationException and continue. This was working with a coreclr build from around last week.

**Comment by janvorli** [comment]
Thanks @mellinoe, I'll look into that.

**Comment by mellinoe** [comment]
@janvorli 
Some additional information: I found that if I explicitly catch Exception, rather than TargetInvocationException (or add another catch block after it, in my case), then I am able to at least continue with the program.

I am still seeing some weird behaviour, though. In my catch (Exception) block, I am trying to print a few things out (just to know that I actually caught the exception), but the only thing that gets printed out is the Exception message/stack trace itself, and the program continues. So there's something very strange there. At the very least I can sort of work around this issue in my test program.

**Comment by janvorli** [comment]
@mellinoe could you please close this issue if it already works ok for you?

**Comment by mellinoe** [comment]
Sorry for the delay. I wasn't able to repro this again, so it must have been an issue with the test program I was using. After refreshing my builds, I wasn't able to get back to the state I was in where this was happening. Closing this out now.
