### ISSUE TITLE
Not possible to DllImport a native assembly with a "." in its file name

### ISSUE THREAD

**Issue by eerhardt** [dotnet/coreclr#17150]
Since our tooling doesn't support customers to compile for each OS, it currently isn't possible to name a native assembly using namespace names, like "Microsoft.Foo.Bar", and use the assembly in a `DllImport` successfully on both Windows and non-Windows.

## Repro:
Create a native assembly named `Test.Foo`.  On Windows it is named `Test.Foo.dll`.  On Linux it is named `Test.Foo.so`.  On macOS it is named `Test.Foo.dylib`.

It is not possible to create a C# `DllImport` into this native assembly from a single managed assembly.

On Windows, if you use:

```C#
        internal const string NativePath = "Test.Foo";

        [DllImport(NativePath)]
        public static extern bool Bar();
```

You get an error:

`System.DllNotFoundException : Unable to load DLL 'Test.Foo': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

So you need to use `Test.Foo.dll` in order for Windows to load it.

However, doing this causes it to fail on non-Windows.  On non-Windows if you use:

```C#
        internal const string NativePath = "Test.Foo.dll";

        [DllImport(NativePath)]
        public static extern bool Bar();
```

You get the error:

`System.DllNotFoundException: Unable to load shared library 'Test.Foo.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libTest.Foo.dll: cannot open shared object file: No such file or directory`

Using `strace`, it shows that we are not stripping the `.dll` off of the name during probing:

```
open("/mnt/shared/TestML/runtimes/linux-x64/native/Test.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/eerhardt/dotnet/shared/Microsoft.NETCore.App/2.1.0-preview3-26322-05/Test.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/mnt/shared/TestML/Test.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 82
fstat(82, {st_mode=S_IFREG|0644, st_size=95952, ...}) = 0
mmap(NULL, 95952, PROT_READ, MAP_PRIVATE, 82, 0) = 0x7ff76fd9f000
close(82)                               = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/Test.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/Test.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/Test.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/Test.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
munmap(0x7ff76fd9f000, 95952)           = 0
open("/mnt/shared/TestML/runtimes/linux-x64/native/libTest.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/eerhardt/dotnet/shared/Microsoft.NETCore.App/2.1.0-preview3-26322-05/libTest.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/mnt/shared/TestML/libTest.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 82
fstat(82, {st_mode=S_IFREG|0644, st_size=95952, ...}) = 0
mmap(NULL, 95952, PROT_READ, MAP_PRIVATE, 82, 0) = 0x7ff76fd9f000
close(82)                               = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libTest.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/libTest.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libTest.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libTest.Foo.dll.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
munmap(0x7ff76fd9f000, 95952)           = 0
open("/mnt/shared/TestML/runtimes/linux-x64/native/Test.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/eerhardt/dotnet/shared/Microsoft.NETCore.App/2.1.0-preview3-26322-05/Test.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/mnt/shared/TestML/Test.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 82
fstat(82, {st_mode=S_IFREG|0644, st_size=95952, ...}) = 0
mmap(NULL, 95952, PROT_READ, MAP_PRIVATE, 82, 0) = 0x7ff76fd9f000
close(82)                               = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/Test.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/Test.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/Test.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/Test.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
munmap(0x7ff76fd9f000, 95952)           = 0
open("/mnt/shared/TestML/runtimes/linux-x64/native/libTest.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/eerhardt/dotnet/shared/Microsoft.NETCore.App/2.1.0-preview3-26322-05/libTest.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/mnt/shared/TestML/libTest.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 82
fstat(82, {st_mode=S_IFREG|0644, st_size=95952, ...}) = 0
mmap(NULL, 95952, PROT_READ, MAP_PRIVATE, 82, 0) = 0x7ff76fd9f000
close(82)                               = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libTest.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/libTest.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libTest.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libTest.Foo.dll", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
munmap(0x7ff76fd9f000, 95952)           = 0
```

## Possible solution

We could add another variation on non-Windows that stripped the `.dll` off of the library name, and then append `.so` or `.dylib` to it.  This would allow the name `Test.Foo.dll` to work on all currently supported platforms.

/cc @jkotas @stephentoub

**Comment by jkotas** [comment]
> We could add another variation on non-Windows that stripped the .dll

I would think we should rather make the dot in the filename work on Windows.

**Comment by stephentoub** [comment]
> I would think we should rather make the dot in the filename work on Windows.

It looks like right now we leave the path manipulation to LoadLibrary, which chooses to append ".dll" only if there's no file extension, which presumably it determines based on whether the name contains a dot.  We could just add a probe ourselves for name + ".dll" (maybe if it doesn't already end in ".dll").

**Comment by jkotas** [comment]
cc @jeffschwMSFT @luqunl

**Comment by jeffschwMSFT** [comment]
This is part of a larger group of work that is needed to aid making p/invokes more cross platform friendly.  We are considering how to best address these.

**Comment by ektrah** [comment]
Related: https://github.com/dotnet/coreclr/issues/8902

**Comment by luqunl** [comment]
Yes, Currently We rely on LoadLibrary to find the file in windows. We have seems couple complains about this and maybe it is time to fix this.

**Comment by kasper3** [comment]
Wouldn't a simple probe fix this particular issue like @stephentoub mentioned:

https://github.com/dotnet/coreclr/blob/52a816d3011f4d03b80b5940dc036b40d701f52d/src/utilcode/longfilepathwrappers.cpp#L66

```diff
+auto dllSuffix = W(".dll");
+if(!path.EndsWithCaseInsensitive(dllSuffix))
+{
+    path.Append(dllSuffix);
+}

ret = LoadLibraryExW(path.GetUnicode(), hFile, dwFlags);
```

and the "larger group of work" can continue later? Are there any side effects using such an approach?

**Comment by luqunl** [comment]
@kasper3 , in my mind, this LoadLibraryExW code path is a very common. Previous I was thinking that this change should only affect Pinvoke. 
I would change the following code
https://github.com/dotnet/coreclr/blob/430331c011a0460670e2743ab08caa36f914f52d/src/vm/dllimport.cpp#L6181

BTW, you may also need to deal with ".exe" extension.

**Comment by luqunl** [comment]
> CoreCLR does not allow DllImport("my.exe" right?
You can call an exported function from an exe  through DllImport in CoreCLR, see 
`        [DllImport("VsGraphicsDesktopEngine.exe", CallingConvention = CallingConvention.StdCall)]
        public static extern void Save();`

**Comment by kasper3** [comment]
https://github.com/kasper3/coreclr/commit/edb45878f6915bf7443d74f7da2d17dd1dae5ac9
I am trying to test it but unable to do so using these steps https://github.com/dotnet/coreclr/blob/d1793d37564cf0bbcc5ace7c8f1a0ae0da40d9a5/Documentation/workflow/UsingYourBuild.md. Getting `Failed to initialize CoreCLR, HRESULT: 0x80131500` on Windows 10, after `dotnet2.1 publish -c release`, copying `coreclr.dll` from `coreclr\bin\Product\Windows_NT.x64.Release` to `bin\release\netcoreapp2.1\win-x64\publish\` and running `bin\release\netcoreapp2.1\win-x64\publish\test.exe`. Maybe the docs are outdated? Also tried by copying all files from `coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root` over to publish directory, but getting the same exception.

**Comment by janvorli** [comment]
@kasper3 are you building the sources from the same commit as the coreclr.dll that was published? That's the way I use for debugging stuff - build coreclr from the same commit, then copy all the files from coreclr\bin\Product\Windows_NT.x64.Release (or coreclr\bin\Product\Windows_NT.x64.Debug if I want to do debugging with unoptimized code)  to the folder where the official coreclr.dll was located.

**Comment by kasper3** [comment]
@janvorli, with the following:

1. git clone coreclr and run `.\build.cmd`
2. download and extract https://dotnetcli.azureedge.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.zip to dotnet21 directory
3. run `dotnet21\dotnet.exe new console -n mytest && cd mytest`
4. add DllImport code (with dll name having period) in Program.cs
5. run `dotnet21\dotnet.exe restore https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`
6. run `dotnet21\dotnet.exe publish -c release`
7. copy contents of `coreclr\bin\Product\Windows_NT.x64.Release` directory to `mytest\bin\release\netcoreapp2.1\win-x64\publish\`
8. run `mytest\bin\release\netcoreapp2.1\win-x64\publish\mytest.exe`

i got `Failed to initialize CoreCLR, HRESULT: 0x80131500`.

Are you saying that between 2 and 3, i should copy contents of `coreclr\bin\Product\Windows_NT.x64.Release` directory to `dotnet21\shared\Microsoft.NETCore.App\2.1.0-preview3-26411-06` and skip # 7? Tried that, but it also failed with 0x80131500.

**Comment by jeffschwMSFT** [comment]
@kasper3 that hr indicates that some exception was thrown during startup.  Can you run it under a debugger and see what the issue is?  In general the steps you ran are correct and should work.

**Comment by kasper3** [comment]
@jeffschwMSFT, tried debugging with Windbg, but not sure if this helps:

```cmd
"%ProgramFiles(x86)%\Windows Kits\10\Debuggers\x64\windbg" -o dotnet.exe publish -r win-x64
```

```dbg
Microsoft (R) Windows Debugger Version 10.0.16299.91 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

CommandLine: dotnet.exe publish -r win-x64
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00007ff7`67450000 00007ff7`67477000   dotnet.exe
ModLoad: 00007ffd`63f00000 00007ffd`640db000   ntdll.dll
ModLoad: 00007ffd`63d00000 00007ffd`63dae000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007ffd`63ab0000 00007ffd`63cf9000   C:\WINDOWS\System32\KERNELBASE.dll

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00007ff6`88b80000 00007ff6`88b91000   conhost.exe
ModLoad: 00007ffd`63f00000 00007ffd`640db000   ntdll.dll
ModLoad: 00007ffd`63d00000 00007ffd`63dae000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007ffd`63ab0000 00007ffd`63cf9000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00000000`65cd0000 00000000`65d65000   C:\WINDOWS\System32\SYSFER.DLL

...
...
...

ModLoad: 00007ffd`50620000 00007ffd`50684000   C:\dotnet21preview3-win-x64\host\fxr\2.1.0-preview3-26404-01\hostfxr.dll
ModLoad: 00007ffd`36290000 00007ffd`36321000   C:\dotnet21preview3-win-x64\shared\Microsoft.NETCore.App\2.1.0-preview3-26404-01\hostpolicy.dll
ModLoad: 00007ffd`1e0e0000 00007ffd`1e6a5000   C:\dotnet21preview3-win-x64\shared\Microsoft.NETCore.App\2.1.0-preview3-26404-01\coreclr.dll
ModLoad: 00007ffd`62670000 00007ffd`627b5000   C:\WINDOWS\System32\ole32.dll
ModLoad: 00007ffd`633a0000 00007ffd`63699000   C:\WINDOWS\System32\combase.dll
ModLoad: 00007ffd`60c40000 00007ffd`60caa000   C:\WINDOWS\System32\bcryptPrimitives.dll
ModLoad: 00007ffd`62640000 00007ffd`62667000   C:\WINDOWS\System32\GDI32.dll
ModLoad: 00007ffd`60d60000 00007ffd`60ee7000   C:\WINDOWS\System32\gdi32full.dll
ModLoad: 00007ffd`61130000 00007ffd`611ca000   C:\WINDOWS\System32\msvcp_win.dll
ModLoad: 00007ffd`63db0000 00007ffd`63efa000   C:\WINDOWS\System32\USER32.dll
ModLoad: 00007ffd`60ef0000 00007ffd`60f0e000   C:\WINDOWS\System32\win32u.dll
ModLoad: 00007ffd`636a0000 00007ffd`63760000   C:\WINDOWS\System32\OLEAUT32.dll
ModLoad: 00007ffd`630b0000 00007ffd`63101000   C:\WINDOWS\System32\SHLWAPI.dll
ModLoad: 00007ffd`59750000 00007ffd`5975a000   C:\WINDOWS\SYSTEM32\VERSION.dll
ModLoad: 00007ffd`5fef0000 00007ffd`5ff15000   C:\WINDOWS\SYSTEM32\bcrypt.dll
ModLoad: 00007ffd`62610000 00007ffd`6263d000   C:\WINDOWS\System32\IMM32.DLL
(82c8.73d4): Unknown exception - code 04242420 (first chance)
windows\core\console\open\src\host\srvinit.cpp(480)\ConhostV2.dll!00007FFD4BD817FB: (caller: 00007FFD4BD90628) ReturnHr(4) tid(7458) 80070032 The request is not supported.
windows\core\console\open\src\host\srvinit.cpp(480)\ConhostV2.dll!00007FFD4BD817FB: (caller: 00007FFD4BD90628) ReturnHr(5) tid(7458) 80070032 The request is not supported.
ModLoad: 00007ffd`02910000 00007ffd`03579000   C:\dotnet21preview3-win-x64\shared\Microsoft.NETCore.App\2.1.0-preview3-26404-01\System.Private.CoreLib.dll
ModLoad: 00007ffd`1df70000 00007ffd`1e0d4000   C:\dotnet21preview3-win-x64\shared\Microsoft.NETCore.App\2.1.0-preview3-26404-01\clrjit.dll
(82c8.73d4): C++ EH exception - code e06d7363 (first chance)
(82c8.73d4): C++ EH exception - code e06d7363 (first chance)
(82c8.73d4): CLR exception - code e0434352 (first chance)
(82c8.73d4): C++ EH exception - code e06d7363 (first chance)
(82c8.73d4): CLR exception - code e0434352 (first chance)
(82c8.73d4): CLR exception - code e0434352 (first chance)
(82c8.73d4): CLR exception - code e0434352 (first chance)
(82c8.73d4): CLR exception - code e0434352 (first chance)
(82c8.73d4): CLR exception - code e0434352 (first chance)
(82c8.73d4): CLR exception - code e0434352 (first chance)
(82c8.73d4): CLR exception - code e0434352 (first chance)
(82c8.73d4): CLR exception - code e0434352 (first chance)
(82c8.73d4): C++ EH exception - code e06d7363 (first chance)
(82c8.73d4): CLR exception - code e0434352 (first chance)
ModLoad: 00007ffd`603a0000 00007ffd`603b1000   C:\WINDOWS\System32\kernel.appcore.dll
*** ERROR: Module load completed but symbols could not be loaded for C:\WINDOWS\System32\SYSFER.DLL
SYSFER+0x19e6d:
00000000`65ce9e6d c3              ret
```

**Comment by luqunl** [comment]
@kasper3, Could you try in a official version dotnet core? 
 BTW, I have added a  DllImport into a exe testcase into https://github.com/dotnet/coreclr/pull/17505

**Comment by kasper3** [comment]
This is actually a breaking change

from https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175.aspx

> * The name of the module. This can be either a library module (a .dll file) or an executable module (an .exe file). The name specified is the file name of the module and is not related to the name stored in the library module itself, as specified by the LIBRARY keyword in the module-definition (.def) file.
> * If the string specifies a module name without a path and the file name extension is omitted, the function appends the default library extension .dll to the module name. To prevent the function from appending .dll to the module name, include a trailing point character (.) in the module name string.

so @jkotas' example `[DllImport("mydll.dat")]` is working today, but won't work after this change as the other guy wants it to load `mydll.dat.dll`. It is not confined to .dll, .exe, .dat.. it could be any extension.  Even the overload of `DllImport` will not be elegant as we are already transforming `.so/.so.Major/.so.Major.Minor` on Linux with current API, and partially transforming .dll on windows (underlying LoadLibrary is doing it). New overload would then only concern Windows with no effect on Linux? Other way to achieve it is by rewriting LoadLibrary using something even lower level, then implementing everything that LoadLibrary does, except for this .dll extension magic. There is no easy way to fix it.
