### ISSUE TITLE
[Arm64] Unix stubs are incomplete

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17166]
https://github.com/dotnet/coreclr/blob/ba4ed5441c6c39f672b37a28da57f79af934977a/src/vm/arm64/unixstubs.cpp#L14-L27

Hit by this corefx test
```
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Reflection.Emit.ILGeneration.Tests
Discovered:  System.Reflection.Emit.ILGeneration.Tests
Starting:    System.Reflection.Emit.ILGeneration.Tests

Assert failure(PID 12218 [0x00002fba], Thread: 13681 [0x3571]): false && "Implement for PAL"
    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/vm/arm64/unixstubs.cpp Line: 16
    Image: /home/sdmaclea/corefx/arm64-runtime/corerun


Assert failure(PID 12218 [0x00002fba], Thread: 13681 [0x3571]): false && "Implement for PAL"
    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/vm/arm64/unixstubs.cpp Line: 16
    Image: /home/sdmaclea/corefx/arm64-runtime/corerun

Command terminated by signal 6
```

@janvorli @jkotas What are these supposed to do?

**Comment by sdmaclea** [comment]
Looks like the assembly functions are written...

https://github.com/dotnet/coreclr/blob/ba4ed5441c6c39f672b37a28da57f79af934977a/src/vm/arm64/pinvokestubs.S
https://github.com/dotnet/coreclr/blob/ba4ed5441c6c39f672b37a28da57f79af934977a/src/vm/arm64/pinvokestubs.asm

**Comment by janvorli** [comment]
This looks like they were forgotten here. I wonder how come  they don't clash with the asm versions

**Comment by sdmaclea** [comment]
I don't know..  I am trying to compile with them deleted.  Maybe PInvokeStub are missing from the CMake files list?

**Comment by sdmaclea** [comment]
It complied successfully.  I am going to submit a PR.

**Comment by sdmaclea** [comment]
Removing the bad asserts changed behavior, but the Call Indirect PInvokes are not working.

I took a look at amd64 code it has three snippets missing from arm64

Modify the cookie (comment seems to be obsolete related to removed FEATURE_ALL_INTERFACES)

https://github.com/dotnet/coreclr/blob/a38ed985e11b0d56ecd44e3e6d2878cef8ca6052/src/vm/amd64/pinvokestubs.S#L27-L33
Save more regs
https://github.com/dotnet/coreclr/blob/a38ed985e11b0d56ecd44e3e6d2878cef8ca6052/src/vm/amd64/pinvokestubs.S#L46-L50
Restore more regs
https://github.com/dotnet/coreclr/blob/a38ed985e11b0d56ecd44e3e6d2878cef8ca6052/src/vm/amd64/pinvokestubs.S#L60-L64

Is this necessary?

I have been unable to figure out where the code for GenericPInvokeCalliStubWorker resides so it is difficult to figure out

**Comment by jkotas** [comment]
The code for GenericPInvokeCalliStubWorker  is here: https://github.com/dotnet/coreclr/blob/master/src/vm/dllimport.cpp#L6511
