### ISSUE TITLE
[Linux] [CoreClr] Inconsistent behavior of Encoding.GetEncoding method

### ISSUE THREAD

**Issue by mviorno** [dotnet/coreclr#1717]
I use the following code to obtain utf-32BE encoding (utf-32 big endian):

```csharp
Encoding encoding = Encoding.GetEncoding("utf-32BE");
Assert.AreEqual("utf-32BE", encoding.WebName);
```

Unfortunately, when running under linux with coreclr runtime, this code returns utf-8 encoding instance, instead of utf-32BE. But under windows with any runtime and under linux when running with mono runtime, this code return correct utf-32BE encoding instance.

Same problem reproduces with the code below:

```csharp
Encoding encoding = CodePagesEncodingProvider.Instance.GetEncoding(12001); // utf-32BE
Assert.AreEqual("utf-32BE", encoding.WebName);
```

Moreover, when Encoding.GetEncoding tries to obtain non-existing encoding (linux, coreclr), it also returns utf-8 encoding instance. But with other runtimes such code throws CultureNotFoundException.

```csharp
Encoding encoding = Encoding.GetEncoding("invalid_encoding_name");
Assert.AreEqual("utf-8", encoding.WebName); // test runs fine, but an exception expected!
```

Environment:

```
uname -a

Linux debianDNX 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
```

```
dnvm list

Active Version              Runtime Arch OperatingSystem Alias
------ -------              ------- ---- --------------- -----
       1.0.0-beta6          mono         linux/darwin
  *    1.0.0-rc1-15838      coreclr x64  linux           default
       1.0.0-beta8-15618    mono         linux/darwin
       1.0.0-beta8-15530    mono         linux/darwin
       1.0.0-rc1-15838      mono         linux/darwin
       1.0.0-beta8-15618    coreclr x64  linux
       1.0.0-beta7          mono         linux/darwin
```

**Comment by stephentoub** [comment]
The implementation for this just got checked in yesterday:
https://github.com/dotnet/coreclr/pull/1645

Does your test include that change?

**Comment by mviorno** [comment]
We use recent packages from the following feed:

```
https://www.myget.org/F/aspnetvnext/
```

There is a piece of text from project.json.lock file generated after running dnu restore command:

```
      "System.Text.Encoding/4.0.11-beta-23406": {
        "type": "package",
        "dependencies": {
          "System.Runtime": "4.0.0"
        },
        "compile": {
          "ref/dotnet/System.Text.Encoding.dll": {}
        },
        "runtime": {
          "lib/DNXCore50/System.Text.Encoding.dll": {}
        }
      },
      "System.Text.Encoding.CodePages/4.0.1-beta-23406": {
        "type": "package",
        "dependencies": {
          "System.Runtime": "4.0.0",
          "System.Text.Encoding": "4.0.10"
        },
        "compile": {
          "ref/dotnet/System.Text.Encoding.CodePages.dll": {}
        }
      },
```

Looks like "System.Text.Encoding.CodePages/4.0.1-beta-23406" depends on "System.Text.Encoding": "4.0.10" instead of "System.Text.Encoding/4.0.11-beta-23406". Is this correct?

**Comment by stephentoub** [comment]
cc: @weshaggard, @eerhardt

**Comment by eerhardt** [comment]
>Encoding encoding = Encoding.GetEncoding("utf-32BE");
Assert.AreEqual("utf-32BE", encoding.WebName);

This was fixed with https://github.com/dotnet/coreclr/pull/1645.  I don't think the latest CoreCLR build as propagated out to https://www.myget.org/F/aspnetvnext/ yet, has it?  I think the best thing to do would be to test it out with the latest CoreCLR and see if it is fixed.  (it should be fixed, utf-32BE is a supported encoding on CoreCLR on Linux with that change)

**Comment by eerhardt** [comment]
I tested this with 1.0.0-rc2-16128 coreclr.

```C#
		Encoding encoding = Encoding.GetEncoding("utf-32BE");
		Console.WriteLine(encoding.WebName);
```

prints out:

```
utf-32BE
```

However, it doesn't look like this change made rc1, when I use 1.0.0-rc1-15838, I get the output:

```
utf-8
```

Closing as this is now fixed in the latest code.
