### ISSUE TITLE
[Arm64] System.Text.Tests.EncodingTest.TestRoundtrippingSpecificCodepageEncoding fails

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#17192]
_From @sdmaclea on March 24, 2018 0:35_

```
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Text.Encoding.CodePages.Tests
Discovered:  System.Text.Encoding.CodePages.Tests
Starting:    System.Text.Encoding.CodePages.Tests
   System.Text.Tests.EncodingTest.TestRoundtrippingSpecificCodepageEncoding(encodingName: \"GB18030\", bytes: [129, 48, 137, 55, 129, ...], expected: \"Þßàáâã\") [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [129, 48, 137, 55, 129, ...]
      Actual:   Byte[] [129, 48, 137, 55, 129, ...]
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Text.Encoding.CodePages/tests/EncodingCodePages.cs(535,0): at System.Text.Tests.EncodingTest.TestRoundtrippingSpecificCodepageEncoding(String encodingName, Byte[] bytes, String expected)
Finished:    System.Text.Encoding.CodePages.Tests

=== TEST EXECUTION SUMMARY ===
   System.Text.Encoding.CodePages.Tests  Total: 740, Errors: 0, Failed: 1, Skipped: 0, Time: 5.775s
```

_Copied from original issue: dotnet/corefx#28438_

**Comment by jkotas** [comment]
_From @tarekgh on March 24, 2018 18:5_

@jkotas who can look at this one as it looks arm64 specific issue?

**Comment by jkotas** [comment]
This is most likely codegen or runtime bug. Somebody from @dotnet/arm64-contrib should take a look.

It may be best for this issue to live in coreclr repo, like all other issues that track arm64-specific crashes and failures hit by corefx tests: https://github.com/dotnet/coreclr/labels/arch-arm64

**Comment by sdmaclea** [comment]
@tarekgh We took a look at this.  @debayang found that `GB18030Encoding.LoadManagedCodePage()` was incorrectly assuming `mapUnicodeTo4BytesFlags[]` was zero initialized.  

I took a look.  The memory comes from `GetNativeMemory()` which calls `System.Runtime.InteropServices.Marshal.AllocHGlobal()`.
`System.Runtime.InteropServices.Marshal.AllocHGlobal()` is documented at least by Xamarin as not zero initializing memory `Also, the allocated memory is not zero-filled.`  https://developer.xamarin.com/api/member/System.Runtime.InteropServices.Marshal.AllocHGlobal/p/System.IntPtr/ 

Looks like this is a corefx bug.

**Comment by tarekgh** [comment]
Looks we fixed a similar issue before in some other place but we missed this one.

https://source.dot.net/#System.Text.Encoding.CodePages/System/Text/SBCSCodePageEncoding.cs,95

will close this issue here and will re-activate the corefx one and will fix it. thanks for your investigation.
