### ISSUE TITLE
Regression in vm/corhost.cpp

### ISSUE THREAD

**Issue by llamadonica** [dotnet/coreclr#17199]
#17080 Adds information to EventPipe in corhost.cpp

EventPipe is only defined when FEATURE_PERFTRACING is turned on, so the build currently breaks when PERFTRACING is off. This affects android builds (and anyone else without liblttng-ust-dev)

**Comment by llamadonica** [comment]
@adamsitnik (since you were the original reviewer): This seems like such a minor issue. Can I just submit a PR?

**Comment by adamsitnik** [comment]
@llamadonica sure!

**Comment by brianrob** [comment]
@llamadonica, thanks for reporting this.  Yes, feel free to submit a PR for this, or I can do this as well.

Can you tell me more about the android builds?  Where are these built out of?  I'm not aware of any official build that we do where FEATURE_PERFTRACING is disabled.

**Comment by llamadonica** [comment]
The android builds are using these instructions https://github.com/dotnet/coreclr/blob/master/Documentation/building/android.md and the libttng issue is here: #15687 (along with various other unrelated android build tips.)

FEATURE_PERFTRACING is disabled by default when FEATURE_EVENT_TRACE is disabled, which is why I came the issue while doing an android x86 build for termux. This only affects unofficial builds, but it seems like the feature flags should work correctly if they're there.

**Comment by brianrob** [comment]
Thanks much @llamadonica.  Agreed they should work if they're present - just wasn't familiar with the android build instructions.
