### ISSUE TITLE
CLRStack -i  in SOS causes SegmentationFault on LLDB / Linux

### ISSUE THREAD

**Issue by chsienki** [dotnet/coreclr#17259]
ClrStack -i is causing a segmentation fault in SOS on Linux

 ### Repro Steps:

**Environment:**
Ubuntu 14.04
LLDB 3.8.1
CLR 2.1.0-preview3-26324-03

**lldb steps:**
target create _pathtoclr_/corerun
settings append target.run-args _netcoreexe_
plugin load _pathtoclr_/libsosplugin.so

_Step or continue until libcoreclr.so is loaded_

sos ClrStack -i

### Expected Output:
Dumping managed stack and managed variables using ICorDebug

### Actual Output:
Segmentation fault (core dumped)

**Comment by mikem8361** [comment]
This may be that the libsosplugin.so is built for lldb 3.9 for .NET Core 2.1 and we are stilling testing against 3.8.1.

**Comment by mikem8361** [comment]
Issue moved to [dotnet/diagnostics #44](https://github.com/dotnet/diagnostics/issues/44) via [**ZenHub**](https://www.zenhub.com/)
