### ISSUE TITLE
about c++ native call .netcore through coreclr

### ISSUE THREAD

**Issue by daoqiang** [dotnet/coreclr#17254]
I want to set by coreclr using c++ to call.Netcore program, but the existing project I must use the /md option to compile, (vs2017) (conflict /clr options and /md options) so I can only through the c++ project into coreclr source code to make the call, how should I hand it in, there is no ready-made examples of use, thank you you

**Comment by jeffschwMSFT** [comment]
It sounds like you are interested in hosting the CLR so that you can call .NET from C++?  If that is the case there are a few examples on how to use our hosting API: in http://yizhang82.me/hosting-coreclr and https://github.com/dotnet/coreclr/tree/master/src/coreclr/hosts.  You can then use coreclr_create_delegate  to create a delegate in .NET code.

**Comment by daoqiang** [comment]
Wow, this is very useful information for me，A little bit inadequate is that in the yizhang82`s blog, the source code connection of the example seems to be a mistake.
Now I can only create a function pointer through the c++ code, and then.Netcore creates the corresponding delegate to call it? Can't you call class directly through an object - oriented way
Thank you

**Comment by daoqiang** [comment]
Can you give me a more complete example? In the official example, I only saw the code of c++, the code of.Netcore is not, I can't see how it is invoked, the code that your blog contains can't run on window, thank you.

**Comment by daoqiang** [comment]
https://github.com/dotnet/docs/blob/master/docs/core/tutorials/netcore-hosting.md
Is this a description document to call.Netcore by loading coreclr.dll by c++? If I follow this document, I can use coreclr to generate coreclr.lib in my project, just as the steps described in the document

**Comment by jeffschwMSFT** [comment]
Great, sounds like you are all set.  There are a handful of open source tools we are exploring to help make this scenario more seamless (cppsharp, swig, etc.).  I am going to close this question for now, but please feel free to reach out if you have more questions.

**Comment by kasper3** [comment]
There is also a Rust binding https://github.com/gsfraley/dotrust.
