### ISSUE TITLE
Differences between full CLR and CoreCLR

### ISSUE THREAD

**Issue by roterdam** [dotnet/coreclr#1728]
Other than missing things from CoreFX which are in progress, what are some differences in CoreCLR vs. CLR?
- Same GC?
- Same JIT?
- C++/CLI support missing?

**Comment by rstat1** [comment]
As far as I am aware the CLR in this repo is identical to the CLR in full .NET and the only differences are in the available API set in corefx.

**Comment by roterdam** [comment]
I would think so too, but seems like there is at least C++/CLI that is missing. I should try loading one to confirm it to be honest.

**Comment by rstat1** [comment]
Well ok..yea that's missing too. But is C++/CLI really a feature directly part of the CLR, instead of just a language implemented on top of it?

I admittedly know very little about C++/CLI so feel free to correct me on that if I'm wrong..

**Comment by roterdam** [comment]
I know very little as well and I would agree that is _should_ be the same. Maybe C++/CLI has some implications on the runtime like how native code may be loaded, etc. It is quite possible that it underneath the covers adds PInvoke calls so who knows.

**Comment by roterdam** [comment]
https://github.com/dotnet/coreclr/issues/659

**Comment by rstat1** [comment]
Well I guess that explains it...

**Comment by karelz** [comment]
Looks explained. Closing.
