### ISSUE TITLE
Will DLLs compiled against Profile7 automatically load in my CoreCLR host?

### ISSUE THREAD

**Issue by roterdam** [dotnet/coreclr#1729]
If I make a custom CoreCLR host, will Profile7 magically work? Or is there some other other profile?

**Comment by weshaggard** [comment]
There is nothing magic about Profile7. We used that for our corefx libraries primarily to ensure we had a portable profile that we knew we could support on CoreCLR. Things compiled against it will work assuming you deploy the matching implementation assemblies that are used.

**Comment by roterdam** [comment]
Thanks. So if I compile my dll as profile7 and my exe as profile7 using VS 2015 it'll load on CoreCLR? Don't I need to reference the CoreFX? Or are you saying no one doesn't need to, eventually all of Profile7 CoreFX will be there.

**Comment by mellinoe** [comment]
> So if I compile my dll as profile7 and my exe as profile7 using VS 2015 it'll load on CoreCLR
In short, yes. That will work. Profile 7 does not include some basic things like System.Console, however, so you'd have a hard time making anything very useful that way.

To expand: all of the current contracts we have in CoreFX are built on top of past contracts. Profile 7 is a small set of such past contracts. Right now, profile 7 is a heavy subset of what we have in corefx, meaning we have a LOT more in corefx now than was in any past portable profile. And, like Wes said, there's nothing special about profile 7, this applies to any of the portable subsets you can target.

**Comment by roterdam** [comment]
Ok, so is there a list of how to target a profile? I would like to use System.Console :)

**Comment by ericstj** [comment]
Have a look at the CLI docs in https://github.com/dotnet/cli.  That's probably a better place to get started and ask these sorts of questions.
