### ISSUE TITLE
provide an option to the user to skip initializing large objects

### ISSUE THREAD

**Issue by Maoni0** [dotnet/coreclr#17325]
sometimes it may be desirable to not have GC to clear memory when it hands an object out. this issue is to track providing such an option to users. the GC part is tracked via #17324.

**Comment by RussKeldorph** [comment]
Sorry @Maoni0.  My mistake.

**Comment by VSadov** [comment]
I think this issue is addressed in #24096 there is an option to not clear now.

I will keep https://github.com/dotnet/corefx/issues/31787 open to follow up with making the API public.
