### ISSUE TITLE
[Arm64] IsIPInMarkedJitHelper -- Help 

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17337]
@janvorli I need help understnding the intent of IsIPInMarkedJitHelper

Based on review of comments, it seems this is used to mark a subset of JIT helpers as being in managed code

For `arm64` it currently includes
```
    CHECK_RANGE(JIT_MemSet)
    CHECK_RANGE(JIT_MemCpy)
    CHECK_RANGE(JIT_WriteBarrier)
    CHECK_RANGE(JIT_CheckedWriteBarrier)
```

Shouldn't it also include 
```
    CHECK_RANGE(JIT_ByRefWriteBarrier)
    CHECK_RANGE(JIT_Stelem_Ref)
    CHECK_RANGE(JIT_Stelem_Ref_NotExactMatch)
    CHECK_RANGE(JIT_Stelem_DoWrite)
    CHECK_RANGE(JIT_Stelem_Ref)
```

I am assuming the stubs are not needed, because they are generated by the JIT and treated as managed code.  It would be really nice to understand the classification rules, constraints and requirements.

Also based on my read, these functions will effectively get retried if a signal occurs, signal will return to the caller, to call the helper again.  So these functions have functional constraints as well to not modify the call arguments.  Is my understanding here correct?

**Comment by RussKeldorph** [comment]
@jkotas

**Comment by sdmaclea** [comment]
Assuming my retry assumption above is correct.

`JIT_MemSet` and `JIT_MemCpy` are modifying their input arguments, so if they are retried, random corruption could occur.

`JIT_Stelem_*` looks like it only destroys input arguments while throwing.  Still would need to fix this.

`JIT_*Barrier*` code also modifies input registers, and would need rework to allow retry.

**Comment by AndyAyersMS** [comment]
I think the aim of `IsIPInMarkedJitHelper` is to identify ranges of native code in jit helpers where there are implicit null checks, so AVs in these ranges end up reported as managed null reference exceptions originating in the calling frame (which should be managed code).

The `stelem` helpers look like they do explicit null checks. The byref write barrier is probably never supposed to AV.

**Comment by jkotas** [comment]
IsIPInMarkedJitHelper is used to mark ranges of assembly code helper where we expect null references to occur and be handled.

When IsIPInMarkedJitHelper returns true, we do not retry execution of the helper. We just move the IP and SP to the callsite of the helper for the purpose of exception handling. We do not ever resume execution at the callsite.

**Comment by sdmaclea** [comment]
Thanks
