### ISSUE TITLE
[Question] How to print all task status and stack?

### ISSUE THREAD

**Issue by 316181444** [dotnet/coreclr#17343]
I need there information for found some impossible issue (i guess) like like "Task.Run(() => {Console.WriteLine(xxx)})" never execution.

Thanks a lot

**Comment by 316181444** [comment]
My program is running on Ubuntu 14.04. on the problem happened only way just restart my program....

**Comment by jkotas** [comment]
cc @stephentoub @noahfalk

**Comment by 316181444** [comment]
Please help me . This issue happens after my program runs for 12 hours. and my program have many log. i not sure why in my “task.run” code block print log function not execution on the issue happening . i maybe need all task run status and stacks. 
Thanks a lot.

**Comment by noahfalk** [comment]
As a start you should be able to get stacks by attaching either:
VSCode - https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code#debug
lldb -  https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md

You could also run your project with VS remotely connected to a Linux machine but I don't think attach is supported yet so this may not be ideal for long running scenarios: https://docs.microsoft.com/en-us/cpp/linux/deploy-run-and-debug-your-linux-project

Hopefully one of these techniques can help get the ball rolling on diagnosing your issue.

**Comment by 316181444** [comment]
@noahfalk Thanks for you replay
VSCode remote debug on Linux cannot display "Tasks" 
lldb(sosplugin) - only print all threads not "Tasks"

I am not sure why "a Task never start" deadlock? exception? and use threads list cannot be thinking these problems.

**Comment by noahfalk** [comment]
No unfortunately the task specific debugging tools aren't as well supported in VSCode. Even in VS the task window only shows tasks that had some activity (scheduled, started running) after the debugger attached so its not great for post-mortem style investigation.

I was instead suggesting that if logging was insufficient you could view the underlying thread stacks, and if necessary you can inspect the runtime implementations of various parts of the task libraries. Its getting out of my area of expertise but my basic understanding is that Tasks are queued to TaskSchedulers (such as TaskScheduler.Default), and assuming you are using the default scheduler it queues to the thread pool. @stephentoub is the expert on these internals.

Taking a shot in the dark as to things that may have gone wrong:
a) If you have deadlocked something in user code that submits tasks to the TaskScheduler (for example you stop calling await Foo), then there won't be any new tasks scheduled.
b) If you use a task scheduler that has a limited degree of concurrency (this would be a non-default TaskScheduler) and your tasks don't finish, scheduled tasks won't start.
c) If your tasks are being awaited in a particular SynchronizationContext (https://blogs.msdn.microsoft.com/pfxteam/2012/01/20/await-synchronizationcontext-and-console-apps/) and you have blocked the thread in that context, then the awaits won't finish.
d) If your tasks are continuations and the tasks they depend on haven't completed, then the continuation tasks won't be scheduled.

Looking around a bit more, I also found some examples of code that log the EventSource for task events and this seems like a promising avenue to pursue:
http://source.roslyn.io/#Roslyn.Hosting.Diagnostics/DiagnosticOnly_TPLListener.cs,2d99bbd1957ed659,references
You can get more data than this example by examining the values in the eventData.payload object. For example eventData.payload[2] is the task id. To see everything that is available in the payload:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Tasks/TPLETWProvider.cs

By logging when tasks are scheduled, start, and complete you can determine at what stage each task stopped making progress and then investigate only issues that apply to that part of the lifetime.

Hope this helps.

**Comment by benaadams** [comment]
What type of app? For ASP.NET Core apps you can use https://github.com/benaadams/Ben.BlockingDetector and it will output the stack traces for things blocking in the ThreadPool (which can cause Task.Run to wait indefinately due to ThreadPool stravation)

**Comment by 316181444** [comment]
Thanks a lot. I was Found bug is "Socket.SendAsync" never timeout. Thanks

**Comment by noahfalk** [comment]
Excellent, glad to hear it! Assuming that wraps this up I'm going to close the issue, but we can always open a new one (or re-open this one) if needed.

**Comment by 316181444** [comment]
Yes. sure thing
