### ISSUE TITLE
.NET Core app slow launching (ARM)

### ISSUE THREAD

**Issue by RoySalisbury** [dotnet/coreclr#17355]
First things first.  I know its "preview" and I know performance usually gets better in the actual release.  However, is it just me, or is starting a .NET Core app (2.0 or 2.1-preview1) take longer than it should?

My app takes around 30 seconds (with the CPU at 150% according to TOP) before it really even starts.  I know this because the very first thing I have in "main" is a Console.WriteLine.

This is an ASP.NET Core app.  But even a simple "Hello World" console apps takes about 7 seconds.  

In the early days of .NET, you could deploy your app and "ngen" the files so they were basically native instructions.  I figure that is what is happeing when the app is run, but its does not cache the info.  And there is no way to pre-jit the files.

Are there plans to get this faster for ARM (and I'm specifically talking Raspberry Pi here, but it could be others as well)?

**Comment by stephentoub** [comment]
How are you running the app?

**Comment by hjc4869** [comment]
AFAIK, crossgen does not support ARM properly, so everything would be JIT compiled.

It is a lot faster on a more recent ARM core, though. (Cortex-A72@2GHz only takes 0.5s to run Hello World)

**Comment by RoySalisbury** [comment]
@stephentoub  - Tried 2 ways..

dotnet ./Project.dll
and (after marking the file for execute)
./Project

Both take the same time.  But the 2nd way is the normal one.

**Comment by stephentoub** [comment]
> Tried 2 ways

Ok, thanks, just wanted to make sure it wasn't `dotnet run`, which could end up including all of the C# compilation time.

**Comment by RoySalisbury** [comment]
@hjc4869 - So, how can we get it pre-jit compiled.   Switching to a different processor is not an option.  We have a lot invested in the Pi for a product we are creating.

Hopefully this is just something that "is in the works".

**Comment by hjc4869** [comment]
https://github.com/dotnet/core-setup/issues/3314
Maybe this will be included in the next preview.

**Comment by RoySalisbury** [comment]
Thats good.  Reading through most of the other referenced threads as well, it looks like the base CLR will get cross compile work, but the base ASP.NET Core libraries won't (for dependency reasons).

But seeing as how 80% (I made that number up) of an ASP.NET Core app is base CLR assemblies, that should still provide a good speed increase.

**Comment by RussKeldorph** [comment]
The biggest impact should be the ahead-of-time compile ("crossgen") of System.Private.Corelib.dll, which should be coming in the next 2.1 preview, along with crossgen of the corefx assemblies.  Crossgen of other components, such as aspnetcore can be tracked via aspnet/Universe#554 for example.

There could still be other runtime-related startup issues that aren't addressed by crossgen, but I'd like to close this issue until we've seen how much difference crossgen makes since the major crossgen tasks for coreclr (this repo) are complete.

@Petermarcu
