### ISSUE TITLE
Difference in code and documentation of BlockingCollection.BoundedCapacity

### ISSUE THREAD

**Issue by nerai** [dotnet/coreclr#17395]
[.NET framework reference source of `BlockingCollection.BoundedCapacity`](https://referencesource.microsoft.com/#System/sys/system/collections/concurrent/BlockingCollection.cs,72) says:

> ... The bounded capacity of this collection, or int.MaxValue if no bound was supplied.

However, if no capacity is supplied in the ctor, it is called:

    Initialize(collection, NON_BOUNDED, collection.Count);

with

    private const int NON_BOUNDED = -1;

So the BoundedCapacity of an unbounded instance is -1, not int.MaxValue. To verify:

	var a = new BlockingCollection<int> ();
	Console.WriteLine (a.BoundedCapacity); // prints -1
	Console.WriteLine (int.MaxValue); // prints 2147483647

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #28782](https://github.com/dotnet/corefx/issues/28782) via [**ZenHub**](https://www.zenhub.com/)
