### ISSUE TITLE
[Arm64/Linux] Spurious failures to load libicu* symbols

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17396]
Over the last few month when running regressions there have been sporadic failures to load symbols from
libicuuc and/or libicui18n

```
// Cannot get symbol ucal_getKeywordValuesForLocale from libicui18n
// jitStressRegs0x400
CoreMangLib/cti/system/io/stream/StreamNull_PSC/StreamNull_PSC.sh

// Cannot get symbol u_getVersion from libicuuc
// forcerelocs
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b55216/b55216/b55216.sh

// Cannot get symbol ucal_getKeywordValuesForLocale from libicui18n
// Nightly master #25 (4/3/2018)
// gcServer
JIT/jit64/localloc/ehverify/eh13_small/eh13_small.sh

// Cannot get symbol ucal_getKeywordValuesForLocale from libicui18n
// Nightly master #25 (4/3/2018)
// jitStressRegs0x2
JIT/Regression/CLR-x86-JIT/V1-M14-SP1/b119538/b119538b/b119538b.sh
```

Incidence rate is fairly low.  Last nights regressions ran 305K coreclr tests (30 configs) on master and another 305K tests on release_2.1.  There were two failures last night.

@janvorli @jkotas I am wondering if there is a race condition loading these libraries.  Is some initialization locking needed?

**Comment by janvorli** [comment]
@tarekgh is it possible that there is a race calling the GlobalizationNative_LoadICU and invoking icu functions?

**Comment by tarekgh** [comment]
I don't think this a race condition. The managed initialization is coming from a static property 

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Globalization/GlobalizationMode.cs#L9

which should be atomic from the runtime.

**Comment by sdmaclea** [comment]
`dlopen` & `dlsym`  are both marked thread safe.  So agreed race is probably not the issue.

Some of the Ubuntu packages have been updated since I upgraded.  I'll run upgrade and watch this.

**Comment by janvorli** [comment]
It is also pretty weird that that symbols reported are in the middle of the list - so it seems like it was able to get a few of them before it failed. It would be interesting to print the `dlerror()` in the error message too. 
@sdmaclea if you repro this issue in the future, would you be able to test it with that addition?
The error is printed here: https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/icushim.cpp#L257

**Comment by sdmaclea** [comment]
Are you OK with a permanent change to print the output of `dlerror()`

**Comment by janvorli** [comment]
Yes. This is a diagnostic output, so the more info we can print the better.

**Comment by sdmaclea** [comment]
From last night
```
corerun arithm32_cs_ro.exe
Cannot get symbol u_getVersion from libicuuc
```

**Comment by tarekgh** [comment]
@sdmaclea can we repro this with this build?

**Comment by sdmaclea** [comment]
The failures are spurious.  I am unable to reproduce standalone.  So I need a full run to catch one of these.  And then they only occur every few nights.  I'll watch the nightly runs to see if we can get a failure w/ the `dlerror()` message.

Thanks for merging the extra debug info.

**Comment by sdmaclea** [comment]
Last nights run had two fails.
```
corerun b28037.exe
Cannot get symbol udat_close from libicui18n
Error: /usr/lib/aarch64-linux-gnu/libicui18n.so.55: undefined symbol: udat_close
```
```
corerun mul_ovf_i4.exe
Cannot get symbol ucol_closeElements from libicui18n
Error: /usr/lib/aarch64-linux-gnu/libicui18n.so.55: undefined symbol: ucol_closeElements
```

**Comment by sdmaclea** [comment]
Since it is so rare, I wonder if a simple retry would help.

**Comment by tarekgh** [comment]
didn't the change of getting the error code used in this build? the error code may give some clue why this is happening? 

 > Since it is so rare, I wonder if a simple retry would help.

Maybe, but we still need to understand why this is happening.

**Comment by sdmaclea** [comment]
@tarekgh Above the string returned by dlerror() is after the "Error: " i.e "/usr/lib/aarch64-linux-gnu/libicui18n.so.55: undefined symbol: udat_close"

> we still need to understand why this is happening

Should we trigger a core dump?

**Comment by tarekgh** [comment]
@sdmaclea somehow I was expecting error number :-) so I didn't notice this.

searching the Web, looks the problem could be there is unstable ICU package installed on the system. here is one example https://forum.manjaro.org/t/icu-update-from-arch-breaks-various-apps-dependencies/22836. I don't know though why in our case this can happen? do you know what list of other apps/packages we install in our case that may trigger installing unstable ICU versions?

**Comment by sdmaclea** [comment]
@tarekgh It is possible the OS on my machines is contaminated with unstable versions.  When I get a chance I will try a clean install.

**Comment by janvorli** [comment]
I don't think it is an issue with unstable ICU since it happens intermittently. 
I would like to understand the issue more. One way would be to loop through all the functions even in case of failures and log all the ones that we've failed to map. That way, we could see if the problem is that from some point, the dlopen starts to fail and so it is not recoverable or if it just randomly fails for some functions.
What I mean is that instead of aborting here: https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/icushim.cpp#L257 we would set a flag and abort after the loop.

**Comment by sdmaclea** [comment]
I haven't seen the interrmittent failure in a few weeks.  Work to stabilize release 2.1 for arm64 may have fixed this.  I am going to close this.  Will reopen if I see the failure again.
