### ISSUE TITLE
Custom AssemblyLoadContext not used when loading dependencies

### ISSUE THREAD

**Issue by Rohansi** [dotnet/coreclr#1740]
When loading an assembly that has additional dependencies in a custom AssemblyLoadContext, the dependencies will be loaded by the TPA binder if they can be found in the same directory as the managed executable.

I can replicate this with CoreRun from coreclr@66b24ad114f991cd882387f1a3bb280c7cd6877f. I  also tested this with dnx (CoreClr-x64-1.0.0-rc1-15838) but I couldn't replicate it there, but it may be possible to if I knew the paths it was using.

My directory tree looks like this:
```
runtime\
  - CoreRun.exe
  - coreclr.dll
  - mscorlib.dll
  - System.*.dll
program\
  - Program.exe
  - Test.dll
  - TestDep.dll
```

The source for the assemblies in the program directory: https://gist.github.com/Rohansi/40770cc6663e04c3a76d 

And I run Program.exe with: `..\runtime\CoreRun.exe Program.exe` or `runtime\CoreRun.exe program\Program.exe`

`CustomLoadContext.Load()` will only be called once when loading Test.dll. If I move Test.dll and TestDep.dll into a lib subdirectory and load from there it will be called for both.

**Comment by kouvel** [comment]
I'm taking a look at the TPA binder issue. In the meantime as a workaround, you can move Program.exe into the runtime folder. That would remove program\ from being an app path, and it has to use the custom load context to load assemblies from there.
