### ISSUE TITLE
Incorrect exception stack trace on release builds

### ISSUE THREAD

**Issue by ateoi** [dotnet/coreclr#17419]
I am getting different exception stack traces for debug and release builds for the tests 
`ThrowStatementDoesNotResetExceptionStackLineSameMethod` and `ThrowStatementDoesNotResetExceptionStackLineOtherMethod` from https://github.com/ateoi/corefx/blob/5c7dd13f09e1d6550589238d3e8dd9babc621469/src/System.Runtime/tests/System/ExceptionTests.cs. On debug builds, I get the expected exception stack traces, but on release builds I get incorrect ones. I've tagged some of the inconsistencies I've found below with [right] and [wrong].

**Windows NETFX x86**
1. ThrowStatementDoesNotResetExceptionStackLineSameMethod test
- DEBUG call stack:
<pre><code>at System.Tests.ExceptionTests.ThrowAndRethrowSameMethod(Stack`1 callStack) in C:\Repos\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 91
<b>[right]</b> at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineSameMethod() in C:\Repos\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 71</code></pre>
- RELEASE call stack:
<pre><code>at System.Tests.ExceptionTests.ThrowAndRethrowSameMethod(Stack`1 callStack) in C:\Repos\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 91
<b>[wrong]</b> at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineSameMethod() in C:\Repos\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 72</code></pre>
2. ThrowStatementDoesNotResetExceptionStackLineOtherMethod test
- DEBUG call stack:
<pre><code>at System.Tests.ExceptionTests.ThrowException(Stack`1 callStack) in C:\Repos\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 134
at System.Tests.ExceptionTests.ThrowAndRethrowOtherMethod(Stack`1 callStack) in C:\Repos\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 127
<b>[right]</b> at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod() in C:\Repos\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 103</code></pre>
- RELEASE call stack:
<pre><code>at System.Tests.ExceptionTests.ThrowException(Stack`1 callStack) in C:\Repos\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 134
at System.Tests.ExceptionTests.ThrowAndRethrowOtherMethod(Stack`1 callStack) in C:\Repos\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 127
<b>[wrong]</b> at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod() in C:\Repos\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 104</code></pre>
**Linux CORE x64**
1. ThrowStatementDoesNotResetExceptionStackLineSameMethod test
- DEBUG call stack:
<pre><code>at System.Tests.ExceptionTests.ThrowAndRethrowSameMethod(Stack`1 callStack) in /home/ateoi/git/corefx/src/System.Runtime/tests/System/ExceptionTests.cs:line 85
<b>[right]</b> at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineSameMethod() in /home/ateoi/git/corefx/src/System.Runtime/tests/System/ExceptionTests.cs:line 71</code></pre>
- RELEASE call stack:
<pre><code>at System.Tests.ExceptionTests.ThrowAndRethrowSameMethod(Stack`1 callStack) in /home/ateoi/git/corefx/src/System.Runtime/tests/System/ExceptionTests.cs:line 85
<b>[wrong]</b> at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineSameMethod() in /home/ateoi/git/corefx/src/System.Runtime/tests/System/ExceptionTests.cs:line 72</code></pre>
2. ThrowStatementDoesNotResetExceptionStackLineOtherMethod test
- DEBUG call stack:
<pre><code>at System.Tests.ExceptionTests.ThrowException(Stack`1 callStack) in /home/ateoi/git/corefx/src/System.Runtime/tests/System/ExceptionTests.cs:line 134
<b>[right]</b> at System.Tests.ExceptionTests.ThrowAndRethrowOtherMethod(Stack`1 callStack) in /home/ateoi/git/corefx/src/System.Runtime/tests/System/ExceptionTests.cs:line 117
<b>[right]</b> at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod() in /home/ateoi/git/corefx/src/System.Runtime/tests/System/ExceptionTests.cs:line 103</code></pre>
- RELEASE call stack:
<pre><code>at System.Tests.ExceptionTests.ThrowException(Stack`1 callStack) in /home/ateoi/git/corefx/src/System.Runtime/tests/System/ExceptionTests.cs:line 134
<b>[wrong]</b> at System.Tests.ExceptionTests.ThrowAndRethrowOtherMethod(Stack`1 callStack) in /home/ateoi/git/corefx/src/System.Runtime/tests/System/ExceptionTests.cs:line 118
<b>[wrong]</b> at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod() in /home/ateoi/git/corefx/src/System.Runtime/tests/System/ExceptionTests.cs:line 104</code></pre>

**Comment by danmosemsft** [comment]
@mikem8361 could you please take a look?

I am not sure how important it is to fix this for 2.1: it is only 1-off, but when analyzing a failure output (eg from the event log) an accurate line number is a key piece of information.

**Comment by mikem8361** [comment]
I'll try to look at the Linux .NET Core repro, there isn't I can do about NETFX (desktop) unless I'm misunderstanding something. Obviously we are using portable PDBs on Linux, but on the desktop are they Windows or Portable PDBs (later versions of the destkop do support portable PDB).

**Comment by ateoi** [comment]
> but on the desktop are they Windows or Portable PDBs

Windows PDBs

**Comment by mikem8361** [comment]
This may be fixed by PR https://github.com/dotnet/runtime/pull/2269
