### ISSUE TITLE
CoreFX tests on checked CoreCLR slow

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17414]
Triage of these indicated there was likely expensive `_DEBUG_` or assertion code slowing down common code paths when running CoreFX tests w/ CoreCLR checked binaries.

https://github.com/dotnet/coreclr/issues/17410 
https://github.com/dotnet/coreclr/issues/17411
https://github.com/dotnet/coreclr/issues/17413

CoreCLR should regularly run CoreFX tests w/ CoreCLR checked binaries., so this should be fixed if possible.

It is possible this is arm64 or linux only, but it is equally likely this affects all platforms.

**Comment by sdmaclea** [comment]
@debayang Ran a profile.  The major slow down in checked vs. release exists in x64 and arm64.

The checked profile of System.IO.Tests.File_Copy_str_str.CopyFileWithData_MemberData showed 
```
16.76% corerun libcoreclr.so [.] Object::ValidateInner 
11.52% corerun libcoreclr.so [.] WKS::GCHeap::IsHeapPointer 
7.12% corerun ld-2.17.so [.] _dl_tlsdesc_return 
6.94% corerun libcoreclr.so [.] MethodTable::GetClass 
4.11% corerun libcoreclr.so [.] MethodTable::SanityCheck
```

Object validation is creating the most significant overhead.  

Hacking the checked build to disable USE_CHECKED_OBJECTREFS improves performance in checked 5x.  Further disabling SanityCheck() would also help close the gap.

**Comment by sdmaclea** [comment]
The question now is what if anything to do.

Options:
- Only run  USE_CHECKED_OBJECTREFS and SanityCheck() under HeapVerify
- Create a new option to disable USE_CHECKED_OBJECTREFS and SanityCheck() for better estimate of pefrormance
- Split HeapVerify into several flags.   Enable USE_CHECKED_OBJECTREFS and SanityCheck() by default, enable extended checking with another flag, disable both on zero

@jkotas

**Comment by jkotas** [comment]
What are the most frequent callers of the object validation?

**Comment by debayang** [comment]
Below callers of the Object::ValidateInner() function with the checked binary.

<pre><code>
- [17.06%] Object::ValidateInner
   - instance void [System.IO.FileSystem.Tests] System.IO.Tests.File_Copy_str_str::CopyFileWithData_MemberData(char[],bool)
	 - 17.02% void [xunit.assert] Xunit.Assert::Equal(!!0,!!0,class [System.Runtime]System.Collections.Generic.IEqualityComparer`1<!!0>)
		- instance bool [xunit.assert] Xunit.Sdk.AssertEqualityComparer`1[System.__Canon]::Equals(!0,!0)
		   - 17.02% instance valuetype [System.Runtime]System.Nullable`1<bool> [xunit.assert] Xunit.Sdk.AssertEqualityComparer`1[System.__Canon]::CheckIfEnumera
			  - 9.77% instance bool [xunit.assert] Xunit.Sdk.AssertEqualityComparer`1[System.__Canon]::Equals(!0,!0)
				 + 2.73% ObjectNative::GetClass
				 + 2.65% instance bool [System.Private.CoreLib] System.RuntimeType::IsSubclassOf(class System.Type)
				 + 1.94% JIT_IsInstanceOfAny
				 + 1.61% instance bool [System.Private.CoreLib] System.RuntimeType::IsValueTypeImpl()
				 + 0.84% JIT_GetRuntimeType
			  - 7.25% instance object [System.Private.CoreLib] System.Array::GetValue(int32)
				 + 3.47% ArrayNative::GetReference
				 + 3.28% ReflectionInvocation::TypedReferenceToObject
				 + 0.48% ArrayNative::GetRank
				   0.02% Object::ValidateInner
</code></pre>

Objectref distribution :
```
+   29.85%     1.83%  corerun  libcoreclr.so  [.] OBJECTREF::operator-> 
+   11.53%     0.81%  corerun  libcoreclr.so  [.] OBJECTREF::OBJECTREF
+   11.42%     1.00%  corerun  libcoreclr.so  [.] OBJECTREF::OBJECTREF
+    9.81%     1.03%  corerun  libcoreclr.so  [.] OBJECTREF::operator= 
```

**Comment by debayang** [comment]
@sdmaclea 

Another option may be to skip the ValidateObject through a flag.
https://github.com/dotnet/coreclr/blob/master/src/vm/vars.hpp#L312-L313

**Comment by jkotas** [comment]
> Below callers of the Object::ValidateInner() function with the checked binary.

How should I read this? I shows `System.Array::GetValue` as the caller, but with very small cost `0.02% Object::ValidateInner`.

**Comment by debayang** [comment]
@jkotas  Sorry for the confusion.  I have expanded the call trace.  
Each of the callers eventually calls one of the Objectref overloaded operators which  internally calls ValidateInner().
So if we sum up the individual costs it sums up to ~17% in this case.

<pre> <code>
- instance void [System.IO.FileSystem.Tests] System.IO.Tests.File_Copy_str_str::CopyFileWithData_MemberData(char[],bool)
                     - 17.02% void [xunit.assert] Xunit.Assert::Equal(!!0,!!0,class [System.Runtime]System.Collections.Generic.IEqualityComparer`1<!!0>)
                        - instance bool [xunit.assert] Xunit.Sdk.AssertEqualityComparer`1[System.__Canon]::Equals(!0,!0)
                           - 17.02% instance valuetype [System.Runtime]System.Nullable`1<bool> [xunit.assert] Xunit.Sdk.AssertEqualityComparer`1[System.__Canon]::CheckIfEnumera
                              - 9.77% instance bool [xunit.assert] Xunit.Sdk.AssertEqualityComparer`1[System.__Canon]::Equals(!0,!0)
                                 - 2.73% ObjectNative::GetClass
                                    - 1.15% MethodTable::GetManagedClassObjectIfExists
                                       + 0.55% OBJECTREF::OBJECTREF
                                       + 0.55% OBJECTREF::operator=
                                         0.06% Object::ValidateInner
                                    + 1.00% OBJECTREF::operator->
                                    + 0.51% OBJECTREF::OBJECTREF
                                      0.07% Object::ValidateInner
                                 - 2.65% instance bool [System.Private.CoreLib] System.RuntimeType::IsSubclassOf(class System.Type)
                                    - 1.56% instance class System.RuntimeType [System.Private.CoreLib] System.RuntimeType::GetBaseType()
                                       - 0.80% RuntimeTypeHandle::IsInterface 
                                          + 0.27% OBJECTREF::OBJECTREF
                                          + 0.26% OBJECTREF::OBJECTREF
                                          + 0.25% OBJECTREF::operator->
                                            0.03% Object::ValidateInner
                                       - 0.76% RuntimeTypeHandle::IsGenericVariable
                                          + 0.25% OBJECTREF::operator->
                                          + 0.24% OBJECTREF::OBJECTREF
                                          + 0.23% OBJECTREF::OBJECTREF
                                            0.03% Object::ValidateInner
                                    - 1.09% RuntimeTypeHandle::GetBaseType
                                       + 0.51% OBJECTREF::OBJECTREF
                                       + 0.30% OBJECTREF::operator->
                                       + 0.24% OBJECTREF::OBJECTREF
                                         0.04% Object::ValidateInner
                                 - 1.94% JIT_IsInstanceOfAny
				     - 1.91% JITutil_IsInstanceOfAny
                                       + 0.94% ObjIsInstanceOf
                                           0.54% Object::ValidateInner
                                       + 0.22% OBJECTREF::OBJECTREF
                                       + 0.21% OBJECTREF::operator->
                                      0.02% Object::ValidateInner
                                 - 1.61% instance bool [System.Private.CoreLib] System.RuntimeType::IsValueTypeImpl()
                                    - JIT_GetRuntimeType
                                       + 1.08% MethodTable::GetManagedClassObjectIfExists
                                       + 0.51% OBJECTREF::operator->
                                         0.02% Object::ValidateInner
                                 + 0.84% JIT_GetRuntimeType
                              - 7.25% instance object [System.Private.CoreLib] System.Array::GetValue(int32)
                                 - 3.47% ArrayNative::GetReference
                                    + 2.90% OBJECTREF::operator->
                                    + 0.43% OBJECTREF::OBJECTREF
                                      0.14% Object::ValidateInner
                                 - 3.28% ReflectionInvocation::TypedReferenceToObject
                                    - 2.15% MethodTable::Box
                                       - 1.66% MethodTable::FastBox
                                          + 0.62% MethodTable::Allocate
                                          + 0.52% OBJECTREF::OBJECTREF
                                          + 0.46% OBJECTREF::operator->
                                            0.05% Object::ValidateInner
                                       + 0.47% OBJECTREF::operator=
                                         0.02% Object::ValidateInner
                                    + 0.57% OBJECTREF::operator->
                                    + 0.51% OBJECTREF::operator=
                                      0.06% Object::ValidateInner
                                 - 0.48% ArrayNative::GetRank
                                      Object::ValidateInner
                                   0.02% Object::ValidateInner
</code></pre>

**Comment by jkotas** [comment]
Is it 17% of total time? That does not sound too bad...

**Comment by debayang** [comment]
Its 17% in ValidateInner self overhead. Including Children it ~40%.
Below child calls of ValidateInner().

<pre><code>
Children      Self  Command  Shared Object  Symbol
-   39.75%    17.06%  corerun  libcoreclr.so  [.] Object::ValidateInner
   - 22.69% Object::ValidateInner
      - 11.14% MethodTable::Validate
         + 6.72% MethodTable::SanityCheck
           0.96% WKS::GCHeap::GetGcCount
         + 0.40% MethodTable::GetClass
      - 3.97% CAutoTryCleanup<CLRException::HandlerState>::~CAutoTryCleanup
           2.88% CLRException::HandlerState::CleanupTry
         + 0.65% _dl_tlsdesc_return
           0.31% GetCurrentSP
        2.90% NativeExceptionHolderBase::Push
      + 2.51% ObjHeader::Validate
        0.54% GCScan::GetGcRuntimeStructuresValid
        0.47% WKS::GCHeap::GetGcCount
</code></pre>

**Comment by jkotas** [comment]
I think we should look at this as a performance issue in the methods that are showing up in these profiles.

- Optimize the implementation of the reflection methods that are showing on these profiles, like `IsSubclassOf`. They make a lot of managed/native trips. This will make them both faster in general, and reduce the object validation overhead in them.

- Selectively suppress some of the object validation in `ObjectNative::GetClass` (use `Object*` instead of `OBJECTREF`)

**Comment by sandreenko** [comment]
@sergiy-k has found the issue! (The process looks like a magic to me, so do not ask me how).
So in inc/contract.h we have:
https://github.com/dotnet/coreclr/blob/9d85a643eb32d57188ab1805998dc9a9d6978f8a/src/inc/contract.h#L241-L245 (it was added there before 2010).

So the contracts are disabled on arm32 and enabled on arm64. It explains the difference that I saw in #22077 and explains how this issue was resolved for arm32.

I tried to disable contracts for arm64 in this `#ifdef` but got bunch of compiler errors that I am trying to avoid now.

@jkotas do you remember that change, do we need to do the same for arm64? Do we need them for arm32?

**Comment by jkotas** [comment]
You should be able to define `DISABLE_CONTRACTS` in the cmakefile and it should disable the contracts in all the right places. You can switch ARM over to the same plan for clarity.

We have the contracts disabled on all Unix flavors as well.

I think it is good enough to have the contracts enabled on Windows x86/x64 only since they are very expensive as you have observed, and most of the validation that they do is platform-independent.
