### ISSUE TITLE
Coreclr crashes on valid code

### ISSUE THREAD

**Issue by gafter** [dotnet/coreclr#1742]
See https://github.com/dotnet/roslyn/issues/5870

This is preventing the integration of a PR to compensate for [bugs in double.Parse](https://github.com/dotnet/coreclr/issues/1316) in the Roslyn compilers: https://github.com/dotnet/roslyn/pull/5379

**Comment by gkhanna79** [comment]
@janvorli i am assigning this to you since the related issue (5870) is being looked into by you.

**Comment by janvorli** [comment]
@gafter I assume this issus can be closed now, right?

**Comment by gafter** [comment]
I don't think so. The root cause was a missing assembly, but the CLR reacted by simply crashing instead of diagnosing the problem.

**Comment by janvorli** [comment]
@gafter Oh, I've thought you've tested it with the latest CoreCLR. That problem should be fixed already. Would you be able to give it a try by removing the assembly locally and checking that it reports an exception instead? Or tell me how I can quickly test that myself?

**Comment by gafter** [comment]
@agocke Can you please help here?

**Comment by agocke** [comment]
Yes, the version in our CI produces an exception and message.
