### ISSUE TITLE
Custom AssemblyLoadContext fails to load runtime assemblies

### ISSUE THREAD

**Issue by jp2masa** [dotnet/coreclr#17448]
I'm working on an application which needs to load all .NET Core runtime assemblies, and I'm using a custom `AssemblyLoadContext` implementation, but I'm having a problem: `netstandard.dll` fails to load, `LoadFromAssemblyPath` throws a `BadImageFormatException`. This works on the default `AssemblyLoadContext.Default` though. I read the docs about `AssemblyLoadContext`, and it looks like custom implementations cannot load `System.Private.CoreLib`, but `netstandard` is not mentioned. I'd like to know if it's possible to load all the .NET Core runtime assemblies in an isolated context, and if not, why does this restriction exist.
Any help would be appreciated.

**Comment by jkotas** [comment]
How did you get the `netstandard.dll` that you are getting the `BadImageFormatException` on? What does the error message in `BadImageFormatException` say? It may be easiest if you can share a small standalone repro of the problem.

This error likely means that you are trying to load netstandard.dll reference assembly for execution; or that you are trying to load platform-specific assembly on wrong platform (e.g. Unix version of netstandard.dll on Windows; or vice versa).

**Comment by jp2masa** [comment]
I'm loading the runtime version of `netstandard.dll` for `win-x86`, and it only seems to fail when doing it from a unit test. In the test settings, x86 is set as the default architecture, and I tried to set the `Platform` to `x86` in the unit test project.
This is the message in the `BadImageFormatException`:
>System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

**Comment by RussKeldorph** [comment]
@jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
@jp2masa can you share out your sample?  I tried a simple AssemblyLoadContext and was able to load multiple netstandard.dll's.

**Comment by jp2masa** [comment]
Here's a sample: https://gist.github.com/jp2masa/ea8f1260d9b08820671edb924b33c695
To make the sample simpler, I hardcoded the assembly path, so it assumes that `runtime.win-x86.Microsoft.NETCore.App` was restored at least once, and the packages path is the default one (`%userprofile%\.nuget\packages\`). Loading the `win-x64` version of `netstandard.dll` works fine.

**Comment by jkotas** [comment]
> Loading the win-x64 version of netstandard.dll works fine.

You are trying to load win-x86 (ie 32-bit) flavor of the assembly with native code on win-x64 (ie 64-bit runtime). It is expected that this is not going to work.

The assemblies in the runtime package contain native code, and so they can only be loaded in the matching runtime.

**Comment by jkotas** [comment]
We may want to look into throwing exception with more descriptive message if possible in this case.

**Comment by jp2masa** [comment]
I thought that the native assemblies were only the ones in "runtimes/win-x86/native/".
I need to load the runtime assemblies, but I don't actually need to use the types from there, so I need something like `Assembly.ReflectionOnlyLoadFrom`, what would be the best way to achieve it? Should I use `System.Reflection.Metadata` for this?

**Comment by jkotas** [comment]
Yes, `System.Reflection.Metadata` works for this case.

**Comment by jeffschwMSFT** [comment]
Request part of #11298 closing this issue
