### ISSUE TITLE
Directory.EnumerateDirectories doesn't return directory list on rhel7.2

### ISSUE THREAD

**Issue by jainaashish** [dotnet/coreclr#17465]
I've created a simple application to demonstrate the issue where `Directory.EnumerateDirectories` api doesn't return the list of child directories on rhel 7.2, although it works fine on Windows or Ubuntu. 

Sample Project - https://github.com/jainaashish/CoreClrIssue/tree/master/EnumerateDirectoriesIssue/EnumerateDirectoriesIssue

**Comment by danmosemsft** [comment]
@jeremykuhne @anipik

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#29095
