### ISSUE TITLE
Tearing a ValueTask can result in breaking type safety

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#17470]
ValueTask currently uses Unsafe.As to cast to a Task or an IValueTaskSource based on whether a bit is set elsewhere in the instance.  But a torn read/write with a ValueTask stored in a field could result in seeing the wrong polarity of that bit for the actual object read, which could result in violating type safety.  While this use of Unsafe.As is good for perf, we should undo it and do a normal type cast.

cc: @jkotas, @GrabYourPitchforks, @kouvel

**Comment by kouvel** [comment]
@tarekgh
