### ISSUE TITLE
updated to 2.1 preview,DateTime.Now is not correct

### ISSUE THREAD

**Issue by tianvan** [dotnet/coreclr#17478]
![tim 20180409144223](https://user-images.githubusercontent.com/10600430/38483091-4cfa57be-3c04-11e8-8c41-b2947e5c2f64.png)

**Comment by RussKeldorph** [comment]
@danmosemsft

**Comment by AlexGhiondea** [comment]
@tianvan can you share the piece of code that shows this discrepancy? Is it simply calling `DateTime.Now`?

@tarekgh could you take a look at this?

**Comment by tarekgh** [comment]
@tianvan what OS you are running on? what is your time zone setting there? and what is your default locale on the system? please provide more details.

**Comment by tianvan** [comment]
@tarekgh windows 10 64bit,default language chinese,just update nuget package to 2.1 preview,not install .not core 2.1 runtime

**Comment by tianvan** [comment]
@AlexGhiondea just call DateTime.Now

**Comment by tarekgh** [comment]
@tianvan does your time zone setting is configured to be China time zone? I'll take a look anyway.

**Comment by tianvan** [comment]
@tarekgh [
![tim 20180416135540](https://user-images.githubusercontent.com/10600430/38792108-fd21c40a-417d-11e8-8bee-39e3b9b1d067.png)
](url)

I didn't change any code,today i run it,i seems to be right

**Comment by tianvan** [comment]
@tarekgh razor code
```
 <div class="mdc-text-field mdc-text-field--box mdc-text-field--with-leading-icon" data-mdc-auto-init="MDCTextField">
        <i class="material-icons mdc-text-field__icon" tabindex="0">date_range</i>
        <input type="datetime" id="beginTime" class="mdc-text-field__input" value="@DateTime.Now.AddDays(-SettingManager.GetSettingValue<double>(AppSettingNames.DefaultTimeFilterScope)).ToString("yyyy/MM/dd H:mm")">
        <label for="beginTime" class="mdc-floating-label .font-hei">起始时间</label>
        <div class="mdc-line-ripple"></div>
    </div>
    <div class="mdc-text-field mdc-text-field--box mdc-text-field--with-leading-icon" data-mdc-auto-init="MDCTextField">
        <i class="material-icons mdc-text-field__icon" tabindex="0">date_range</i>
        <input type="datetime" id="endTime" class="mdc-text-field__input" value="@DateTime.Now.ToString("yyyy/MM/dd H:mm")">
        <label for="endTime" class="mdc-floating-label .font-hei">截至时间</label>
        <div class="mdc-line-ripple"></div>
    </div>

**Comment by tarekgh** [comment]
@tianvan 

I think I am kind of understanding what was wrong from your side. When you are doing 

```C#
DateTime.Now.ToString("yyyy/MM/dd H:mm")
```

This depends on the CurrentCulture and what calendar is selected with that culture. from the original bitmap image you posted, it looks to me the date is coming in Hijri (i.e. you have been using a culture which selected either the HijriCalendar or UmAlQuraCalendar) and that is the reason you were seeing the date displayed in the year 1439. if you want to guarantee the date always show in Gregorian regardless of the current culture settings, you can do 

```C#
DateTime.Now.ToString("yyyy/MM/dd H:mm", CultureInfo.InvariantCulture)
```

I am closing this issue and feel free to reply again if you face any other issue.
