### ISSUE TITLE
Make it easy to acquire all SOS binaries needed for debugging

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#17486]
Tracking a request originally made here: https://github.com/dotnet/cli/issues/8872

Depending on the OS, debugger and runtime a developer needs different versions of the sos binaries (sos, libsos, libsosplugin). We are working to make it easier to acquire these binaries and filed this work item to track the work. I imagine a few things may need to happen (sub-divide this issue if needed, but retain this one to track overall status)

- Produce any binary variations that are currently non-existent
- Figure out the most convenient mechanism for distributing the binaries (likely in the SDK?)
- Provide documentation

**Comment by danmosemsft** [comment]
@janvorli

**Comment by kasper3** [comment]
Coming from https://github.com/aspnet/DotNetTools/issues/428, can SOS be also published as an official dotnet-cli tool?

@mikem8361, can you explain a bit what kind of version issues did you notice? With current state of CoreCLR master, libsos builds with LLB 3.[4-9], 4.0, 5.0 and the latest 6.0 and works with any one of them available at runtime. Perhaps things have improved in package managers for llvm toolchain?

**Comment by janvorli** [comment]
@kasper3 Until lldb 3.9, the plugin built for previous versions was crashing in new versions. It seems that the interface has either stabilized or just not changed since.

**Comment by kasper3** [comment]
@janvorli, would it help if we abstract out the methods in a shim like openssl shim in corefx?

**Comment by mikem8361** [comment]
Issue moved to [dotnet/diagnostics #43](https://github.com/dotnet/diagnostics/issues/43) via [**ZenHub**](https://www.zenhub.com/)
