### ISSUE TITLE
CoreCLR failed to run test "baseservices.exceptions.XUnitWrapper" crashed

### ISSUE THREAD

**Issue by shanshan0309** [dotnet/coreclr#17493]
CoreCLR failed to run test "baseservices.exceptions.XUnitWrapper" crashed on Windows with VS2017 Update2. This issue is caused by master branch revision [e7c7551](https://github.com/dotnet/coreclr/commit/e7c755118a97ed9cfb1b24a3c1e82007793fc227). Could you please help take a look at this? Thank you!

**You can repro this issue as the steps below:**

1. git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2. Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\CoreCLR\src
3. build x86 release -Rebuild -- /clp:ShowCommandLine
4. build-test.cmd x86 release -- /clp:ShowCommandLine
5. tests\runtest.cmd x86 release

**Error info:**
The whole log file please see attachment.
[log_x86_test.log](https://github.com/dotnet/coreclr/files/1894023/log_x86_test.log)
To run the test:
> set CORE_ROOT=D:\CoreCLR\src\bin\tests\Windows_NT.x86.Release\Tests\Core_Root
> D:\CoreCLR\src\bin\tests\Windows_NT.x86.Release\baseservices\exceptions\WindowsEventLog\WindowsEventLog\WindowsEventLog.cmd
  
        Expected: True
        Actual:   False
          D:\CoreCLR\src\bin\tests\Windows_NT.x86.Release\TestWrappers\baseservices.exceptions\baseservices.exceptions.XUnitWrapper.cs(107,0): at baseservices_exceptions._WindowsEventLog_WindowsEventLog_WindowsEventLog_._WindowsEventLog_WindowsEventLog_WindowsEventLog_cmd()

**Comment by RussKeldorph** [comment]
@sywhang

**Comment by sywhang** [comment]
@shanshan0309 Thanks for reporting. This test had some dependencies that had to be met, so I took it out on https://github.com/dotnet/coreclr/pull/17482. If you update your branch to the latest master, it should be fixed already.

**Comment by sywhang** [comment]
Closing this issue as it should be fixed with #17482
