### ISSUE TITLE
Initialize multiple variables in one line

### ISSUE THREAD

**Issue by nanddonet** [dotnet/coreclr#17527]
Currently if I do this:

`bool b1, b2= true; ` it works but if I do:

`var b1, b2= true;` it doesn´t.

Should be nice to allow the later so we don´t have to write 2 lines like:

`var b1= true;
 var b2= true;`

**Comment by gfoidl** [comment]
This is a language feature-request, so yould should report this in https://github.com/dotnet/csharplang

1. Create the issue there
1. Link this issue in the new created issue
1. Close this issue

**Comment by gfoidl** [comment]
Moved to https://github.com/dotnet/csharplang/issues/1456

Thanks!

**Comment by janvorli** [comment]
It doesn't work as you expect for the bool - it initializes just b2, the b1 is not initialized. So the reason why the var doesn't work is that there is nothing to infer the type of b1 from.
