### ISSUE TITLE
[Perf] Benchstone/BenchF/BenchMrk regression of ~15% on x86

### ISSUE THREAD

**Issue by valenis** [dotnet/coreclr#17544]
**[Perf] Benchstone/BenchF/BenchMrk regression of ~15% on x86**

Regression can be seen in Benchview - CoreCLR/Master branch between [commits](https://github.com/dotnet/coreclr/compare/0c9e96e1c2c484e7c80bf7f7a7765e6650cbdf73...dotnet:bd7493440cefe9cdfb3648de99178e208f8df5df). Orange dotted line is the Release v2.0 baseline.

![image](https://user-images.githubusercontent.com/19602715/38749646-392b7320-3f07-11e8-963c-882cb035d3be.png)

**Comment by valenis** [comment]
@CarolEidt or @fiigii can you take a look?

**Comment by valenis** [comment]
Yes, this only affects 32-bit x86 platform.

**Comment by fiigii** [comment]
Will be fixed by https://github.com/dotnet/coreclr/pull/17560
