### ISSUE TITLE
[Perf] Benchstone/BenchI/BenchE improvement of ~5% on x86

### ISSUE THREAD

**Issue by valenis** [dotnet/coreclr#17547]
**[Perf] Benchstone/BenchI/AddArray improvement of ~5% on x86**

Improvement can be seen in Benchview - CoreCLR/Master branch between [commits](https://github.com/dotnet/coreclr/compare/367d9b1dd1b542f3d391d0b9111d5914602db2d9...dotnet:312e4486adc4eb8062caa67d4aa9be5411524996). Orange dotted line is the Release v2.0 baseline.

![image](https://user-images.githubusercontent.com/19602715/38750257-42b12438-3f09-11e8-802e-f46787a6c8fb.png)

**Comment by BruceForstall** [comment]
@erozenfeld Is there any reason to keep this issue open?

**Comment by RussKeldorph** [comment]
#13314 maybe?  @AndyAyersMS Do you consider this worth investigating at this point?

**Comment by AndyAyersMS** [comment]
I think we can happily assume we did something good.
