### ISSUE TITLE
[Perf] Benchstone/BenchI/AddArray improvement of ~8% on x86

### ISSUE THREAD

**Issue by valenis** [dotnet/coreclr#17545]
**[Perf] Benchstone/BenchI/AddArray improvement of ~8% on x86**

Improvement can be seen in Benchview - CoreCLR/Master branch between [commits](https://github.com/dotnet/coreclr/compare/099e24486977ef4930692aa2c122f572e3d09d01...dotnet:52be8c187c9edbaaa2c8a775800bedad112bc6c6). Orange dotted line is the Release v2.0 baseline.

![image](https://user-images.githubusercontent.com/19602715/38749963-3b46b538-3f08-11e8-8bc2-c4ce538a2d2b.png)

**Comment by valenis** [comment]
@CarolEidt can you confirm that this is due to the tuning of spill weights from [commits](https://github.com/dotnet/coreclr/compare/099e24486977ef4930692aa2c122f572e3d09d01...dotnet:52be8c187c9edbaaa2c8a775800bedad112bc6c6)?

**Comment by CarolEidt** [comment]
I rebuilt the before & after, and yes, due to the tuning of spill weights, the `flags2` variable is no longer spilled, avoiding a save & restore in the second loop.

**Comment by CarolEidt** [comment]
#valenis - can this be closed since it is explained?
