### ISSUE TITLE
[Perf] ByteMark/BenchEmFloatClass improvement of ~3% on x86

### ISSUE THREAD

**Issue by valenis** [dotnet/coreclr#17548]
**[Perf] ByteMark/BenchEmFloatClass improvement of ~3% on x86**

Improvement can be seen in Benchview - CoreCLR/Master branch between [commits](https://github.com/dotnet/coreclr/compare/89e85cfff719bc743ad53fdc702b0379c5286087...dotnet:e45a895df6b4cc50347daafed05cefa59af511a2). Orange dotted line is the Release v2.0 baseline.

![image](https://user-images.githubusercontent.com/19602715/38750595-4892d6a2-3f0a-11e8-9bcb-33e8ccc8cb88.png)

**Comment by BruceForstall** [comment]
@AndyAyersMS Is there any reason to keep this issue open?

**Comment by AndyAyersMS** [comment]
No.. FWIW here is the updated chart... starting roughly where the green bits are above, so whatever the improvement was, it's still there.

![image](https://user-images.githubusercontent.com/10121823/51008880-8a8b1780-1502-11e9-8e94-2118862690c6.png)
