### ISSUE TITLE
[Perf] SIMD/RayTracerBench regression of ~7% on x86

### ISSUE THREAD

**Issue by valenis** [dotnet/coreclr#17552]
**[Perf] SIMD/RayTracerBench regression of ~7% on x86**

Regression can be seen in Benchview - CoreCLR/Master branch between [commits](https://github.com/dotnet/coreclr/compare/0c9e96e1c2c484e7c80bf7f7a7765e6650cbdf73...dotnet:bd7493440cefe9cdfb3648de99178e208f8df5df). Orange dotted line is the Release v2.0 baseline.

![image](https://user-images.githubusercontent.com/19602715/38752109-e943cca6-3f0e-11e8-9f64-f5ee1acd9e90.png)

**Comment by valenis** [comment]
Looks like the same issue affecting #17544

**Comment by RussKeldorph** [comment]
This indeed seems to have been resolved by the fix for #17544.
