### ISSUE TITLE
Default NumberStyle in float.Parse and double.Parse is Integer for Span

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/coreclr#17553]
The default NumberStyle in ``float.Parse`` and ``double.Parse`` is ``NumberStyle.Integer`` for Span.
https://github.com/dotnet/coreclr/blob/bc28740cd5f0533655f347fc315f6a28836a7efe/src/mscorlib/shared/System/Double.cs#L300-L304
https://github.com/dotnet/coreclr/blob/bc28740cd5f0533655f347fc315f6a28836a7efe/src/mscorlib/shared/System/Single.cs#L291-L295

I don't think this is correct. It breaks default parsing of fp numbers with the following exception:

```csharp
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
```

The default NumberStyle in ``float.TryParse`` and ``double.TryParse`` are correct:

https://github.com/dotnet/coreclr/blob/bc28740cd5f0533655f347fc315f6a28836a7efe/src/mscorlib/shared/System/Double.cs#L319-L322

https://github.com/dotnet/coreclr/blob/bc28740cd5f0533655f347fc315f6a28836a7efe/src/mscorlib/shared/System/Single.cs#L308-L311

The same number which throws an exception for ``Parse`` works nicely with ``TryParse``

The NumberStyles for the string overloads are correct:
https://github.com/dotnet/coreclr/blob/bc28740cd5f0533655f347fc315f6a28836a7efe/src/mscorlib/shared/System/Single.cs#L265-L269

https://github.com/dotnet/coreclr/blob/bc28740cd5f0533655f347fc315f6a28836a7efe/src/mscorlib/shared/System/Double.cs#L266-L270

Repo:
```csharp
 ReadOnlySpan<char> value = "123.45".AsSpan();
  var fp = float.Parse(value, provider: CultureInfo.InvariantCulture); // breaks
  var dp = double.Parse(value, provider: CultureInfo.InvariantCulture); // breaks
```
This appears to be the case even in the original PR from @stephentoub  in #13389 and looks to be a copy/paste error from the integer types.

**Comment by stephentoub** [comment]
Thanks for reporting this.

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/corefx/pull/29099 and https://github.com/dotnet/coreclr/pull/17556
