### ISSUE TITLE
JitStress=2 failure in corefx System.Diagnostics.StackTrace.Tests

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#17558]
We get the following failure in x64_checked_windows_nt_corefx_jitstress2 jobs (e.g., https://ci.dot.net/job/dotnet_coreclr/job/master/view/Windows_NT/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress2/484/consoleText)

```
Starting:    System.Diagnostics.StackTrace.Tests
     System.Diagnostics.Tests.StackFrameTests.SkipFrames_CallMethod_ReturnsExpected [FAIL]
        Assert.NotEqual() Failure
        Expected: Not Void SkipFrames_CallMethod_ReturnsExpected()
        Actual:   Void SkipFrames_CallMethod_ReturnsExpected()
```

Two other failures from that run are the same as in #17557.

**Comment by BruceForstall** [comment]
Also seen on arm: https://github.com/dotnet/coreclr/issues/17583

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/corefx/pull/30463
