### ISSUE TITLE
Suprising sliced ReadOnlySpan Equality with strings

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/coreclr#17566]
If a ``ReadOnlySpan`` is sliced the it does not equal an "equal" (in sense of char by char) string anymore, but for an unsliced ``ReadOnlySpan`` it does equal it.
As ``Slice`` can be used for ``SubString``, like described in @stephentoub's article https://msdn.microsoft.com/en-us/magazine/mt814808.aspx this is a bit unexpected.

Repro
```csharp
string fullString = "Hello World and Universe";
ReadOnlySpan<char> span = fullString;
string partialString = "Hello World";
ReadOnlySpan<char> partialSpan = span.Slice(0, 11); 

Console.WriteLine(span == fullString);
Console.WriteLine(span.ToString() == fullString);

Console.WriteLine(partialSpan == partialString);
Console.WriteLine(partialSpan.ToString() == partialString);
```
The output is:
```ini
True
True
False
True
```
<details>

```ini
.NET Core SDK (gemäß "global.json"):
 Version:   2.1.300-preview2-008530
 Commit:    822ae6d43a

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17133
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008530\

Host (useful for support):
  Version: 2.1.0-preview3-26411-01
  Commit:  38de1bfbb8

.NET Core SDKs installed:
  1.0.2 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008530 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview3-26411-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
</details>

**Comment by RussKeldorph** [comment]
@ahsonkhan

**Comment by stephentoub** [comment]
operator== on span checks to see if it points to the same exact memory with the same length, as commented here:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Span.Fast.cs#L277-L284
It does not check to see whether different memory has the same contents.  For that you can use SequenceEquals, or you can use the extension Equals method like https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/MemoryExtensions.Fast.cs#L37 that allows you to specify a StringComparison type.

**Comment by Tornhoof** [comment]
Yeah, I'm using SequenceEquals, but I don't think the current behaviour is useful, in my opinion the Equals for string should either always work correctly or should not be implemented at all or always throw.

**Comment by stephentoub** [comment]
> Regarding comments, the comment for Equals being obsolete tells you to use '=='

Yes, and == is implemented, it just doesn't have the semantics you want it to have.  We had many discussions about what the semantics of == should be.  For better or worse, they're what they are and aren't going to change at this point.

**Comment by Tornhoof** [comment]
Ok, then it's time for a roslyn analyzer. Anyway do you know why the comment does not show up in Intellisense?

**Comment by svick** [comment]
@Tornhoof 

> in my opinion the Equals for string should either always work correctly or should not be implemented at all or always throw

There is no `operator ==` for `ReadOnlySpan<char>` and `string`. There is `operator ==` for two `ReadOnlySpan<T>` and there is also an implicit conversion from `string` to `ReadOnlySpan<char>`. Put together, the effect is that you can use `==` to compare `ReadOnlySpan<char>` and `string`, but it's not something that can be removed on its own.

**Comment by Tornhoof** [comment]
> ...  but it's not something that can be removed on its own.

Why? If that's the only problem, implement ==/!= for string, it should take the equality operators before the implicit cast.
```csharp
public static bool operator ==(ReadOnlySpan<char> a, string b)
{
    throw new InvalidOperationException();
}
public static bool operator ==(string a, ReadOnlySpan<char> b)
{
    throw new InvalidOperationException();
}
public static bool operator !=(ReadOnlySpan<char> a, string b)
{
    throw new InvalidOperationException();
}
public static bool operator ==(string a, ReadOnlySpan<char> b)
{
    throw new InvalidOperationException();
}
```

**Comment by ahsonkhan** [comment]
> Anyway do you know why the comment does not show up in Intellisense?

What do we need to do to get xml comments to show up on Intellisense?

cc @weshaggard, @mairaw

**Comment by mairaw** [comment]
@ahsonkhan, we need to populate the docs source [here](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/ReadOnlySpan%601.xml). The docs then populate the IntelliSense files.

I've opened a docs issue for this: https://github.com/dotnet/docs/issues/4946.

**Comment by ahsonkhan** [comment]
>  For better or worse, they're what they are and aren't going to change at this point.

As @stephentoub mentioned, the ==, Equals(obj), SequenceEqual semantics are not going to change for Span.

There is also an Equals extension method that lets you do the comparison with a StringComparison passed in:
https://github.com/dotnet/corefx/blob/master/src/System.Memory/ref/System.Memory.cs#L43

Because of that, I am going to close this issue. cc @KrzysztofCwalina  

> If that's the only problem, implement ==/!= for string, it should take the equality operators before the implicit cast.

Feel free to open an issue in [corefx](https://github.com/dotnet/corefx) proposing adding these APIs along with your rationale for why we need them to avoid accidental use of `==` between string/Spans due to the implicit cast which results in unintended output. Here is the API review process: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md
