### ISSUE TITLE
Windows ARM32 GCStress=0xc failures in baseservices\threading\generics\WaitCallback thread tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17570]
The `baseservices\threading\generics\WaitCallback` thread tests consistently fail in Windows ARM32 GCStress=0xc runs, although it is not always the same set of tests which fail (there are many different "thread" tests). E.g.:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_gcstress0xc_tst_prtest/16/artifact/bin/tests/Windows_NT.arm.Checked/Smarty.run.0/Smarty.0.fail.smrt/*view*/
```
Tests.lst=thread23.cmd_867, , , Smrt00000001, , # baseservices\threading\generics\WaitCallback\thread23\thread23.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=thread20.cmd_7499, , , Smrt00000001, , # baseservices\threading\generics\WaitCallback\thread20\thread20.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=thread22.cmd_10415, , , Smrt00000001, , # baseservices\threading\generics\WaitCallback\thread22\thread22.cmd  CATS: EXPECTED_PASS;Pri1
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_gcstress0xc_tst/19/artifact/bin/tests/Windows_NT.arm.Checked/Smarty.run.0/Smarty.0.fail.smrt/*view*/
```
Tests.lst=thread06.cmd_2550, , , Smrt00000001, , # baseservices\threading\generics\WaitCallback\thread06\thread06.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=thread18.cmd_2551, , , Smrt00000001, , # baseservices\threading\generics\WaitCallback\thread18\thread18.cmd  CATS: EXPECTED_PASS;Pri1
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_gcstress0xc_tst/18/artifact/bin/tests/Windows_NT.arm.Checked/Smarty.run.0/Smarty.0.fail.smrt/*view*/
```
Tests.lst=thread24.cmd_1484, , , Smrt00000001, , # baseservices\threading\generics\WaitCallback\thread24\thread24.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=thread22.cmd_10415, , , Smrt00000001, , # baseservices\threading\generics\WaitCallback\thread22\thread22.cmd  CATS: EXPECTED_PASS;Pri1
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_gcstress0xc_tst/17/artifact/bin/tests/Windows_NT.arm.Checked/Smarty.run.0/Smarty.0.fail.smrt/*view*/
```
Tests.lst=thread19.cmd_1070, , , Smrt00000001, , # baseservices\threading\generics\WaitCallback\thread19\thread19.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=thread24.cmd_1484, , , Smrt00000001, , # baseservices\threading\generics\WaitCallback\thread24\thread24.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=thread06.cmd_2550, , , Smrt00000001, , # baseservices\threading\generics\WaitCallback\thread06\thread06.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=thread30.cmd_9020, , , Smrt00000001, , # baseservices\threading\generics\WaitCallback\thread30\thread30.cmd  CATS: EXPECTED_PASS;Pri1
```

**Comment by BruceForstall** [comment]
It seems like MinOpts + HeapVerify causes even more failures, on average:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_gcstress0xc_minopts_heapverify1_tst/19/artifact/bin/tests/Windows_NT.arm.Checked/Smarty.run.0/Smarty.0.fail.smrt/*view*/

**Comment by BruceForstall** [comment]
Some failures are `!pThread->HasPendingGCStressInstructionUpdate()` (https://github.com/dotnet/coreclr/issues/17598, https://github.com/dotnet/coreclr/issues/5310).

There are also many cases of:

```
BEGIN EXECUTION
 "C:\Users\robox\j\workspace\arm_cross_che---88fcf6b1\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root\corerun.exe" thread22.exe 

Assert failure(PID 16144 [0x00003f10], Thread: 17188 [0x4324]): instrVal32 == *(DWORD*)(gcCover->savedCode + offset)

<no module>! <no symbol> + 0x0 (0x00000000)
    File: d:\j\workspace\arm_cross_che---9fe37e18\src\vm\gccover.cpp Line: 1451
    Image: C:\Users\robox\j\workspace\arm_cross_che---88fcf6b1\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: 123456789
END EXECUTION - FAILED
FAILED
```

**Comment by BruceForstall** [comment]
@AndyAyersMS Looks like another GCStress race? Is the `instrVal32 == *(DWORD*)(gcCover->savedCode + offset)` case covered by your change https://github.com/dotnet/coreclr/pull/17330?

**Comment by sdmaclea** [comment]
@BruceForstall Looking briefly at the code, I didn't see any obvious test design issues.

As far as I can see now, the gsStress race issues are fixed for linux-arm64.  You may want to see if these still have issues on arm32.
