### ISSUE TITLE
.NET Core assembly cannot be found when assembly loaded through dynamic IL injected-code

### ISSUE THREAD

**Issue by bobuva** [dotnet/coreclr#17587]
I have a profiler that injects IL into some methods so that they can call into my managed assembly. Since my assembly is in the GAC, it works fine for .NET Framework, but when I tried it in .NET Core, the assembly could not be found. Although this may be a duplicate of https://github.com/dotnet/coreclr/issues/3894, I would like to hear what you think are the best options for accomplishing this assembly load. I do not want to modify the application being profiled (I don't have control over its source), so the solution needs to be something I can do with the profiler or a simplified environment setting.

**Comment by jkotas** [comment]
cc @noahfalk

**Comment by noahfalk** [comment]
For anyone interested, the conversation around this is occurring in #3894.

**Comment by bobuva** [comment]
Thanks @noahfalk . I'll close this one then.
