### ISSUE TITLE
[arm32/Ubuntu] GCStress failures: "Consistency check failed: FAILED: !pThread->HasPendingGCStressInstructionUpdate()"

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17598]
When I run GCStress=0xc on Ubuntu arm32, the most common failure is:

```
               Assert failure(PID 23543 [0x00005bf7], Thread: 23543 [0x5bf7]): Consistency check failed: FAILED: !pThread->HasPendingGCStressInstructionUpdate()
                   File: /mnt/coreclr/src/vm/gccover.cpp Line: 1772
                   Image: /ssd/brucefo/checked/coreclr/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun

               ./30032.sh: line 243: 23543 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

The most common failures are the tests in these directories:
```
baseservices/threading/generics/TimerCallback
baseservices/threading/generics/WaitCallback
```

as well as
```
baseservices/threading/regressions/beta2/437044/437044.sh
```
which in at least one of my runs required 5 retries to pass.

This is https://github.com/dotnet/coreclr/issues/5310.

**Comment by AndyAyersMS** [comment]
Reading the code it seems like the only way this can happen is if the `SuspendEE` call made transitively by `DoGcStress` doesn't suspend. But that seems like a long shot. 

If you have a reliable repro then let me know. I can't get my x64 case to repro so far.

**Comment by sdmaclea** [comment]
This also fails on linux-arm64 but failure rate is probably lower.

Last night failed on 
`gcStress=0x4 baseservices/threading/generics/WaitCallback/thread01/thread01.sh`
```
corerun thread01.exe

Assert failure(PID 22795 [0x0000590b], Thread: 23914 [0x5d6a]): 
Consistency check failed: FAILED: !pThread->HasPendingGCStressInstructionUpdate()
    File: /home/vmjenkins/workspace/Dotnet/build_coreclr/src/vm/gccover.cpp Line: 1737
```

**Comment by echesakovMSFT** [comment]
Hit this issue multiple times when was testing #18053

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_flow_prtest/5/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_jitstress1_flow_prtest/3/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_flow_prtest/3/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_minopts_heapverify1_flow_prtest/1/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_zapdisable_flow_prtest/1/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_zapdisable_heapverify1_flow_prtest/1/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_zapdisable_jitstress2_flow_prtest/1/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_r2r_gcstress15_flow_prtest/1/
