### ISSUE TITLE
Implement string resources for coreclr on Linux

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#176]
# String resources for coreclr on Linux
## Introduction
The native coreclr library uses Win32 resources for storing various error messages so that they can be internationalized. To read the resources, it uses standard win32 APIs to load satellite resource dlls and to read string resources from them.
As for Linux, we don’t have an implementation of Win32 resources reading PAL and so we need to implement some way to access the resources. To keep the Linux build of coreclr self-contained, we also need to be able to produce the resource files from the .rc files.
## Possible solutions
To implement resource reading on Linux, we have several options:
1)	Implement support for Win32 resources by adding support for resource dll loading and Win32 resources parsing to PAL. That would also mean that we would have to port the windows resource compiler to Linux.
2)	Reuse format / tools / code that were implemented in the past for ROTOR.
3)	Implement our own resource storage format, tools to generate them from .rc files and code in PAL to read them.
4)	Use GNU gettext API and tools. This is de-facto standard for internationalization on Linux. Implement tool for converting .rc files to the input format required by the gettext. For example the libc library uses it for localization of its own strings.
Let's further focus on the last solution which after some investigations turned out to be the best for the intended purposes.
## GNU gettext description
The GNU gettext is a set of APIs to access localized strings and also a set of tools to extract strings from C / C++ files for localization purposes and to produce binary files that the API can use to get strings. Location where the API looks for the binary files with strings and also the naming of the files themselves can be configured by the API. It is also possible to specify what encoding should the strings returned by the gettext have, which is independent of the encoding used in the source string file.
While the whole toolchain is able to extract the strings from C / C++ files, it is not a required step. It is possible to create the files with the strings manually or using a tool. 
### Source file format
The source string file has .po extension. It contains entries with the following format:

white-space
\# translator-comments
\#. extracted-comments
\#: reference...
\#, flag...
\#| msgid previous-untranslated-string
msgid untranslated-string
msgstr translated-string

The lines starting with the # character are not necessary. They are comments to help translators and also some directives that help the toolchain to verify correctness of the strings that contain formatting characters (by specifying what programming language are the strings meant for), allow to specify a context for the message (there can be different translations based on the context) and can serve some additional advanced purposes.
The convention is to use the untranslated string as a message id, but nothing prevents usage of any string as the id.
### Compiling the source file to a binary form
The msgfmt tool is used to compile the source string file in the .po format into the binary .mo format:
msgfmt source.so -o target.mo
### The API
Getting a message string for a given msgid is as simple as calling a single API function gettext with the msgid string as a parameter. There is one more flavor of this function (dgettext) that have an additional parameter specifying a text domain (it represents the name of the compiled strings file without the extension and is used e.g. to allow each dynamic library to have its own resource strings).
Besides the above mentioned functions, there is a function bindtextdomain that sets a directory in which strings for a given text domain reside and bind_textdomain_codeset that sets the string encoding of the strings that the gettext function returns for a given text domain. 
The gettext looks for the string in a folder that is constructed as follows:
directory_name/locale/LC_MESSAGES/domain_name.mo
The directory_name is the directory specified using the bindtextdomain, the locale is a locale of the resources (e.g. en_US) and the domain_name is the text domain passed to the dgettext.
As for the locale, the gettext api uses the current locale of the current process. 
### Using the gettext for resources in coreclr
To do a resource string lookup in coreclr, we need to map a resource id to the string. As was shown in the previous paragraphs, the gettext uses strings as message ids, while the resource ids used in coreclr are integers. But we can easily convert the resource id to string and then pass it to the gettext. 
Then the remaining detail to solve was how to generate the .po files from the windows .rc files. Fortunately, if we run the .rc file through the C preprocessor, the resulting file format is very simple to parse. 
Essentially, we just have to look for the lines starting with “STRINGTABLE DISCARDABLE” and then generate msgid / msgstr lines for each line between the line that starts with BEGIN and the line that starts with END. Each string entry in the preprocessed .rc file is formed by a numeric resource id followed by the string itself. Sometimes there are multiple strings next to each other on the same line, which results from the original .rc files having strings split to multiple lines terminated by \\.
These strings need to be merged into one.
I’ve implemented a simple script in awk that parses the preprocessed .rc file and behaves as described above. I have then verified that it generates correct .po file that can be further processed by the msgfmt tool to produce a .mo file. I’ve also verified that the gettext works correctly with the produced .mo file using a simple application.
So now that I have that, we just need to implement a new PAL function that essentially just converts a resource id to string and calls the gettext and to modify the CCompRC class to use it instead of resource dlls.
### More details on the gettext
Complete manual of the gettext can be found here:
http://www.gnu.org/software/gettext/manual/gettext.pdf

**Comment by utaal** [comment]
I've compiled coreclr on OSX (support was recently merged in https://github.com/dotnet/coreclr/commit/bb38f10ec8efea85a85b57669b161a2cd0beb1dd) and I'm encountering the following assert failure (on a binary compiled with mono):

    Assert failure (unable to format)
    /Users/utaal/Src/coreclr/src/utilcode/ccomprc.cpp
    false && "UNIXTODO: Implement string loading from resources"
    **** MessageBox invoked, title 'Assert failure (unable to format)' ****
      false && "UNIXTODO: Implement string loading from resources"
    ********

I'm not incredibly familiar with the `.net` platform but it looks like this `assert` failure is related with this issue. Is this correct?

**Comment by janvorli** [comment]
@utaal Yes, that's correct.

**Comment by poizan42** [comment]
What about assemblies that are not part of the framework? They are going to have resources baked into them as embedded win32 resources anyways.

**Comment by janvorli** [comment]
@poizan42 I am sorry for a late response. In CoreCLR on Linux, we don't care about the embedded win32 resources. We don't need to read or parse them in any way.

**Comment by janvorli** [comment]
Implemented by #543
