### ISSUE TITLE
Incorrect prefix appended when the native library lives in "relative" directory in Unix

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#17604]
_From @luqunl on April 17, 2018 6:3_

The issue is found by Jkotas:

https://github.com/dotnet/coreclr/blob/9d45401c6056a5b9c92d036e25c34ad34c03385e/src/vm/dllimport.cpp#L6054

libNameIsRelativePath is going to be true for a paths like:
XXX\YYY\library
or
\XXX\YYY\library.

On Unix, we will end up trying paths like:
**lib**XXX\YYY\library.so
or
**lib**\XXX\YYY\library.so.

_Copied from original issue: dotnet/corert#5719_

**Comment by RussKeldorph** [comment]
@jeffschwMSFT

**Comment by kasper3** [comment]
@RussKeldorph, @danmosemsft, can this be considered for 2.1 servicing?
