### ISSUE TITLE
About 20% performance regression for OrderBy() and OrderByThenBy() on windows

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/coreclr#17603]
Here are the graphs showing timings from Aug to now for these tests.

<img width="1060" alt="screen shot 2018-04-16 at 11 07 19 pm" src="https://user-images.githubusercontent.com/5897654/38851560-08d96c2e-41cb-11e8-8154-4730865ce439.png">

<img width="1063" alt="screen shot 2018-04-16 at 11 17 43 pm" src="https://user-images.githubusercontent.com/5897654/38851868-6f25fda2-41cc-11e8-9884-ea79f7e50ed1.png">

There was a noticeable jump in October for OrderBy() and OrderByThenBy() tests that does not seem to have been corrected since.

For Windows:
The corefx commit related to this regression is https://github.com/dotnet/corefx/commit/2b25c6c739ada3e8da8b8783e008f48f9078fb33, which in turn points to code changes are in CoreCLR. 
Here's the coreclr commit bd7493440cefe9cdfb3648de99178e208f8df5df  and here's a [github diff](https://github.com/dotnet/coreclr/commit/bd7493440cefe9cdfb3648de99178e208f8df5df) 

Refer to [benchview](https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[23]&mpids=[1292]&cfgids=[2706]&testids=[60303,60301,60302,60300,60319,60317,60318,60316]&jobgroup=CoreFX&jobtype=rolling&branchId=42&) for more details.

cc: @kouvel @danmosemsft

category:cq
theme:benchmarks
skill-level:expert
cost:small

**Comment by maryamariyan** [comment]
For linux the results for Linux is a bit shaky. The timing jump from October to December is related to this corefx diff https://github.com/dotnet/corefx/commit/fe5b7f51822615b3f343348e6bcb5aa06fec0b72.

**Comment by fiigii** [comment]
May be fixed by https://github.com/dotnet/coreclr/pull/17560

**Comment by danmosemsft** [comment]
https://github.com/dotnet/coreclr/issues/17544

**Comment by danmosemsft** [comment]
@jorive why are there no results showing up after April for these tests?

https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=%5B957%5D&archids=%5B23%5D&mpids=%5B1292%5D&cfgids=%5B2706%5D&testids=%5B60303,60301,60302,60300,60319,60317,60318,60316%5D&jobgroup=CoreFX&jobtype=rolling&branchId=42&

**Comment by jorive** [comment]
@danmosemsft You missed a selecting a configuration. I just sent you the updated link.

**Comment by RussKeldorph** [comment]
We weren't able to repro this.  Please re-open if you can.
