### ISSUE TITLE
Sse2.ConvertToXYZ-methods with wrong reference assembly?

### ISSUE THREAD

**Issue by gfoidl** [dotnet/coreclr#17611]
## Problem

For instance

https://github.com/dotnet/coreclr/blob/34c7fe62cabfc8f99c8ab83c8d734c88bbeb2b1b/src/mscorlib/src/System/Runtime/Intrinsics/X86/Sse2.cs#L502-L506

should take a `Vector128<double>` and return a scalar.
The reference assembly doesn't provide this method.
![grafik](https://user-images.githubusercontent.com/5755834/38885975-d7d2118a-4274-11e8-9fd8-e1f2e73df908.png)
So it won't compile.
```
Error	CS1503	Argument 1: cannot convert from 'System.Runtime.Intrinsics.Vector128<double>' to 'System.Runtime.Intrinsics.Vector128<int>'	ConsoleApp1	
```

Checking the assemblies with ILSpy I see that `System.Private.CoreLib.dll` has the correct method, while `........\.nuget\packages\system.runtime.intrinsics.x86\4.5.0-preview1-25809-02\ref\netcoreapp2.1\System.Runtime.Intrinsics.X86.dll` has the wrong methods.

The other `ConvertToXYZ` are analog. I haven't checked any other methods (so far).

## Steps to reproduce

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.1</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Runtime.Intrinsics.X86" Version="4.5.0-preview1-25809-02" />
    </ItemGroup>

</Project>
```

```c#
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

namespace ConsoleApp1
{
    class Program
    {
        static void Main()
        {
            Vector128<double> vector128 = default;
            double value = Sse2.ConvertToDouble(vector128);
        }
    }
}
```

Repro is the same in VS and from the CLI.

**Comment by fiigii** [comment]
I am pretty sure that the reference assembly has exposed this API https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Intrinsics.Experimental/ref/System.Runtime.Intrinsics.cs#L907 and the runtime has implemented it https://github.com/dotnet/coreclr/blob/master/src/jit/hwintrinsiclistxarch.h#L170

**Comment by gfoidl** [comment]
From the reference assembly I see
`[assembly: AssemblyInformationalVersion("4.6.25809.02 @BuiltBy: dlab-DDVSOWINAGE026 @SrcCode: https://github.com/dotnet/corefx/tree/a17b150a7a174494fa8e74fc47dd0269413dfe77")]`

So it would be https://github.com/dotnet/corefx/blob/a17b150a7a174494fa8e74fc47dd0269413dfe77/src/System.Runtime.Intrinsics.X86/ref/System.Runtime.Intrinsics.X86.cs#L813

Maybe in this NuGet-package they got out of sync?
In the _master_-branches they're in sync as @fiigii points out.

**Comment by fiigii** [comment]
> <PackageReference Include="System.Runtime.Intrinsics.X86" Version="4.5.0-preview1-25809-02" />

The package has been renamed to `System.Runtime.Intrinsics.Experimental`.

**Comment by fiigii** [comment]
Please look at https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Runtime.Intrinsics.Experimental

**Comment by gfoidl** [comment]
Ah, I missed that. Not it's fine. Thanks!!!
