### ISSUE TITLE
About 10% performance regression for Perf_BigInteger tests

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/coreclr#17612]
Ctor_ByteArray
![capture04](https://user-images.githubusercontent.com/5897654/38886242-355e249c-422a-11e8-87a5-c2af03d8c409.PNG)

Ctor_ByteSpan
![capture05](https://user-images.githubusercontent.com/5897654/38886356-92c6bb58-422a-11e8-9819-39a0eb4424d5.PNG)

ToByteArray
![capture06](https://user-images.githubusercontent.com/5897654/38886484-efe301e8-422a-11e8-8db6-b2a38acb5bd1.PNG)

TryWriteBytes
![capture07](https://user-images.githubusercontent.com/5897654/38886552-23aa80be-422b-11e8-90fe-4a9b2dd512d7.PNG)

[Updated]:
For all of the above, the corefx diff below is causing the regression increase: 
dotnet/corefx@7ec7367

Check [benchview ](https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[23]&mpids=[1292]&cfgids=[2706]&testids=[64296,64295,64297,64305,64304,64306,64299,64298,64300,64308,64307,64309]&jobgroup=CoreFX&jobtype=rolling&branchId=42&) for more detail.

cc: @kouvel @danmosemsft

**Comment by danmosemsft** [comment]
@maryamariyan it seems impossible to me that the SHA above could affect this scenario. 

If I click on the regressed data point in your benchview query I get https://github.com/dotnet/corefx/compare/834049b454f13ae9dafe4a2e9c98a1002351181a...dotnet:93764c0991d167e3b74f41f1ea129004ce10598c 
in which this is clearly the key change:
https://github.com/dotnet/corefx/commit/7ec73674f2a0d04ae974d36c861d10e305cb0a86

@bartonjs can you please triage for 2.1?

**Comment by maryamariyan** [comment]
@danmosemsft thanks that makes a lot of sense now. 
I took the diff build 93764c0 rather than comparing with base diff as you did above.

I updated the above description.

**Comment by bartonjs** [comment]
Yep, it got worse for very small numbers, and better for large ones.  This was discussed during the PR.

https://github.com/dotnet/corefx/pull/25324

I don't think there's any action here.

**Comment by danmosemsft** [comment]
Fine

**Comment by RussKeldorph** [comment]
Then can we close this?
