### ISSUE TITLE
1.1.8 long-name DAC/SOS has incorrect version (001, expected 01)

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#17619]
I ran some basic symbol validation on the recent 1.1.8 release and found that the long-name DAC/SOS has incorrect versions:

 * ..._4.6.26328.**001**.dll
 * ..._4.6.26328.**01**.dll (expected)

This was fixed in `release/2.0.0`+ by https://github.com/dotnet/coreclr/pull/15583 merging to `master`.

Should the fix be ported to `release/1.1.0`?
Should the 1.1.8 build in particular be manually fixed by renaming the dll and republishing symbols?

/cc @lt72 @mikem8361 @leculver @weshaggard

**Comment by leculver** [comment]
Yes, please port this fix everywhere it needs to go.  Otherwise I have to manually rearchive the files that were improperly named.

**Comment by RussKeldorph** [comment]
@dotnet/dotnet-diag @tommcdon I put this in the 1.1.x milestone so it's off the 2.1.0 radar and since 1.1 seemed appropriate.  Feel free to move it to 2.2 or Future if that reduces the change you'll lose track of it.

**Comment by dagood** [comment]
We hit this again in 1.1.9 so I'm working on another manual fixup + rearchive.

/cc @weshaggard
