### ISSUE TITLE
Cannot get light-up technique of assembly load to work with .NET Core 2.0

### ISSUE THREAD

**Issue by bobuva** [dotnet/coreclr#17626]
First of all, please let me know if this type of issue should be addressed in another repo. I did see some mention of this light-up technique here, so that's why I chose this repo.

I recently learned about the light-up technique that Application Insights uses to get their assemblies loaded into any ASP.NET app. [Here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/platform-specific-configuration?view=aspnetcore-2.1) is a link to it.

I've implemented an IHostingStartup class in an assembly.  I'm using a target of `netcoreapp2.0`. One thing I'm not sure if it could be an issue is that I had installed the .NET Core 2.1 preview (first and the second one), and the SDK that comes with it. So my .NET Core SDK is 2.1.

I followed exactly the same process of making sure my assembly, symbols and deps.json are put in the right place in the my user profile tree under the `.dotnet` subdirectory paths. In fact I used the nice Powershell script that I think Luke Latham wrote and referred to [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/platform-specific-configuration?view=aspnetcore-2.1). 

I verified that the files are copied correctly, and that my deps.json file has the necessary entries.

When I run a hosting app like the `HostingStartupSample` that Luke used (all of the source is [here](https://github.com/aspnet/Docs/tree/master/aspnetcore/host-and-deploy/platform-specific-configuration/sample), I get this exception as it starts up:

```
System.InvalidOperationException: Startup assembly ShiftLeft.NetCore.Agent failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'ShiftLeft.NetCore.Agent, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---
```

I have no idea why it cannot find it. I set the COREHOST_TRACE=1 environment  variable but didn't see anything more than what I already knew. 

Here is the code:

```
using Microsoft.AspNetCore.Hosting;
using ShiftLeft.Agent;

// Use a Hosting Startup Attribute to identify the IHostingStartup implementation.
[assembly: HostingStartup(typeof(ShiftLeft.NetCore.Agent.AgentHostingStartup))]

namespace ShiftLeft.NetCore.Agent
{
    public class AgentHostingStartup : IHostingStartup
    {
        public static void Main(string[] args)
        { }

        public void Configure(IWebHostBuilder builder)
        {
            Logger.Instance.Log("AgentHostingStartup.Configure...");
        }
    }
}
```

The Main() entrypoint is to make the compiler happy -- apparently I cannot use that interface without having a Main entrypoint? All I do for my configuration is simply use a logger class to tell me if it gets loaded.

I could use some additional tips on troubleshooting this or if you think there's a bug. Thanks, Bob

**Comment by RussKeldorph** [comment]
@bobuva Can you clarify what led you to dotnet/coreclr?  I think I would have started with https://github.com/aspnet/Home, but I could be missing something or may simply be ignorant.

**Comment by bobuva** [comment]
@RussKeldorph I had originally read about this in this issue: https://github.com/dotnet/coreclr/issues/3894. I think you're right, though. I'll move this issue to https://github.com/aspnet/Home.

**Comment by bobuva** [comment]
Moved to https://github.com/aspnet/Home/issues/3071

**Comment by RussKeldorph** [comment]
@bobuva Thanks!
