### ISSUE TITLE
DynamicILGenerator does not support BeginFaultBlock and BeginExceptFilterBlock

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/coreclr#1764]
When emitting an Expression.TryFault to a dynamic method via the LambdaExpression.Compile method, this barfs with a NotSupportedException from BeginFaultBlock. It's unclear why this limitation exists; the code doesn't have a comment as to why it's not supported either.

This limitation makes this expression node type fairly useless especially when one can't emit to a MethodBuilder for an assembly that supports this construct. We could possibly emulate Try...Fault behavior in the expression compiler to work around this, or get the support in CoreCLR.

**Comment by JonHanna** [comment]
This is documented at https://msdn.microsoft.com/en-us/library/system.reflection.emit.ilgenerator.beginfaultblock%28v=vs.110%29.aspx but it would certainly be useful to improve upon, and I agree it isn't clear why this limitation is here, on first glance at least.

**Comment by JonHanna** [comment]
The same thing is true of `BeginExceptFilterBlock()`.

**Comment by pallavit** [comment]
@jkotas Would you by any chance know why emitting exception fault blocks is not supported with DynamicMethod?

**Comment by jkotas** [comment]
> @jkotas Would you by any chance know why emitting exception fault blocks is not supported with DynamicMethod?

There is no good reason for it whatsoever. We should remove this restriction.

**Comment by jkotas** [comment]
It should just work once you remove the restrictio. The original developer who worked on this feature just liked to not-support anything that nobody explicit asked for...

**Comment by pallavit** [comment]
> It should just work once you remove the restriction.

Interesting...Looks like we can do this for Desktop as well then?

**Comment by jkotas** [comment]
Right.

**Comment by pallavit** [comment]
Closing this issue and moving it to corefx repo instead under System.Reflection.Emit.
