### ISSUE TITLE
[Arm64/Linux] #16962 Broke arm64 crosscomponent build

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17654]
@CarolEidt 
cc/ @weshaggard

**Comment by CarolEidt** [comment]
@sdmaclea - sorry about that! Can you explain how the build was broken by #16962?

**Comment by weshaggard** [comment]
From a quick glance I suspect it is https://github.com/dotnet/coreclr/pull/16962/files#diff-b6b8820938a1795cb24a04b8b3f48adfR207 that caused the extra define.

**Comment by sdmaclea** [comment]
So crossgen is being built on x64 for arm64 JIT.

**Comment by CarolEidt** [comment]
@weshaggard - yes, I believe you're right. I'm testing a fix now.
