### ISSUE TITLE
linux-instructions missing ssl dependencies for corefx portion

### ISSUE THREAD

**Issue by chris-downs** [dotnet/coreclr#1765]
I followed /Documentation/building/linux-instructions.md on Ubuntu 15.04 and failed while running corefx/build.sh due to these missing dependencies:

libcurl4-openssl-dev
libssl-dev

This occurred while performing the steps in the "Build the Framework Native Components" section. 

It might be helpful to add those to the apt-get prerequisites at the top of the page. The build was successful after I installed those extra two.

**Comment by jasonwilliams200OK** [comment]
Just wondering, will only adding `curl` to the list of `apt-get` suffice?

**Comment by chris-downs** [comment]
It doesn't look like curl provides either of those, they're more related to openssl. However, libcurl4-openssl-dev provides libssl-dev if you want to reduce the number of dependencies listed.

**Comment by jasonwilliams200OK** [comment]
Seems like this is already addressed by this pending PR: https://github.com/dotnet/coreclr/pull/1601/.

**Comment by ellismg** [comment]
Should be fixed by #1601
