### ISSUE TITLE
MediaType.GetHashCode() throws System.ExecutionEngineException

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#17661]
_From @austindrenski on April 17, 2018 20:49_

`MediaType.GetHashCode()` throws a `System.ExecutionEngineException` in an ASP.NET Core application. 

I've included a minimal project that consistently reproduces the exception on my local machine. 

Does anyone have an idea of what's behind this?

__Program.cs:__
```c#
using System;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Formatters;

namespace test
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            MediaType t = new MediaType("text/csv");

            // throws => System.ExecutionEngineException
            Console.WriteLine(t.GetHashCode());

            WebHost.CreateDefaultBuilder(args)
                   .Build()
                   .Run();
        }
    }
}
```
__test.csproj__
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
  </ItemGroup>

</Project>
```

_Copied from original issue: aspnet/Mvc#7673_

**Comment by jkotas** [comment]
_From @mkArtakMSFT on April 18, 2018 18:10_

Thanks for reporting this issue.
@dougbu, can you please look into this?

**Comment by jkotas** [comment]
This was CoreCLR bug. It was fixed for 2.1 as side-effect of https://github.com/dotnet/coreclr/pull/16550.

**Comment by jkotas** [comment]
_From @dougbu on April 18, 2018 22:51_

Thanks @jkotas !

@austindrenski because this is a closed issue in the Core CLR, I'm marking this as `external` and closing it. You may want to watch dotnet/coreclr#16545 to see if it is reopened or otherwise added to a 2.0.x patch release.

**Comment by dougbu** [comment]
@jkotas should this issue be assigned to you and the `external` label removed?

I hope this means you're considering re-targeting the fix for downstream patches 🥇

**Comment by jkotas** [comment]
Submitted downstream port for approval #17720
