### ISSUE TITLE
Lower memory usage, expected?

### ISSUE THREAD

**Issue by sebastienros** [dotnet/coreclr#17687]
On the reliability testing we are doing in the aspnet team, I noticed a drop in memory usage around April 11-12. Is this something that could be explained by Server GC changes?

| OS | Before (MB) | After (MB) | Delta |
| -- | -- | -- | -- |
| Linux | 430 | 360 |  -27% |
| Windows | 345 | 245 | -29% |

This graph show the Windows consumption overtime. The application was the same, the load constant. Only ASP.NET and the runtime were updated. (MVC + EF + Razor). CPU usage remained constant.

![image](https://user-images.githubusercontent.com/1165805/39024187-0436c0d8-43f4-11e8-82ff-6d30b7e07985.png)

If this is not expected I might be able to run the app with the version that were used and get some dumps/traces. It can also be related to changes in other repos but I am trying here first.

**Comment by RussKeldorph** [comment]
@maoni0 @jkotas @vancem

**Comment by stephentoub** [comment]
My guess would be @JeremyKuhne's ArrayPool trimming PR:
https://github.com/dotnet/coreclr/pull/17518

Maybe ASP.NET is doing something at start-up that creating a bunch of arrays of a particular size in the pool, and then those sizes go largely unused after that point?  Or something like that.

**Comment by JeremyKuhne** [comment]
> My guess would be @JeremyKuhne's ArrayPool trimming PR:

My guess as well. ArrayPoolEventSource has events that you could use to validate that this is the case ("BufferTrimmed", notably).

cc: @danmosemsft

**Comment by sebastienros** [comment]
Ok, thanks.
At least now you get an idea of the impact on "close to real world" web apps.
