### ISSUE TITLE
'perfcollect install' fails on official dotnet docker images

### ISSUE THREAD

**Issue by sebastienros** [dotnet/coreclr#17686]
In a `microsoft/dotnet:2.0-sdk-jessie` image, running `perfcollect install` errors with an unsupported linux distribution. `uname` returns `Linux` which isn't handled.

I tried to install manually based on `Debian` instructions, however after installing `zip` and `linux-tools` I still get a 

```
Perf not installed.
Install perf to proceed.
```

**Comment by RussKeldorph** [comment]
@brianrob

**Comment by RussKeldorph** [comment]
@vancem

**Comment by RussKeldorph** [comment]
This issue was moved to dotnet/corefx-tools#76
