### ISSUE TITLE
ThirdPartyNotices.txt in installer/packages is missing entries

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#17690]
Repro steps:
1. Download https://www.nuget.org/packages/runtime.linux-x64.Microsoft.NETCore.App/2.1.0-preview2-26406-04
2. Look at THIRD-PARTY-NOTICES.TXT

Expected:
This should call out all of CoreCLR's Third Party Notices. An example missing one is libunwind8. I believe the complete list can be found at https://github.com/dotnet/coreclr/blob/release/2.1/THIRD-PARTY-NOTICES.TXT

Actual:
[THIRD-PARTY-NOTICES.TXT](https://github.com/dotnet/coreclr/files/1930160/THIRD-PARTY-NOTICES.TXT)

There is a similar problem when installing the .NET SDK (and maybe runtime?) - there is a ThirdPartyNotices.txt (laid down to /usr/share/dotnet/ThirdPartyNotices.txt and c:\Program Files\dotnet\ThirdPartyNotices.txt), but this is also missing many items from this repo's Third-Party-Notices, including libunwind8 again.

**Comment by danmosemsft** [comment]
@RussKeldorph seems like 2.1 fix is needed

**Comment by RussKeldorph** [comment]
@danmosemsft Sounds like you understand this better than I do.  Can you give more details on exactly what needs to happen?  Does coreclr just need to add its THIRD-PARTY-NOTICES.TXT to its package(s) [all of them? which path?] and upstack can take it from there?

I'm sure I could figure it out eventually, but given the urgency, if someone knows exactly what needs to happen, I'd appreciate a hint.

@eerhardt @weshaggard @janvorli

**Comment by Petermarcu** [comment]
Yes, lets tactically update the one in core-setup.

**Comment by RussKeldorph** [comment]
This issue was moved to dotnet/core-setup#4053
