### ISSUE TITLE
[clrdbg] Add support for inline values

### ISSUE THREAD

**Issue by rajivharris** [dotnet/coreclr#17693]
VSCode Debugger Protocol now supports inline values for variables when debugging. It would be great if vsdbg/vsdbg-ui adds support for this.

Debugger Protocol:
[https://github.com/Microsoft/vscode-debugadapter-node/issues/78](url)
[https://github.com/Microsoft/vscode-debugadapter-node/blob/896566e0be3f48e5cf90fb715b3b3ffbfa777888/protocol/src/debugProtocol.ts#L1329-L1337](url)

VSCode Support:
[https://github.com/Microsoft/vscode/pull/16129](url)

**Comment by RussKeldorph** [comment]
@dotnet/dotnet-diag @tommcdon

**Comment by noahfalk** [comment]
@gregg-miskelly - I think this is for you guys more than it is for us? Let us know if there is a corresponding runtime part of the ask.

**Comment by gregg-miskelly** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2206

**Comment by gregg-miskelly** [comment]
@noahfalk feel free to close this.

**Comment by gregg-miskelly** [comment]
@rajivharris Correct. The OmniSharp/omnisharp-vscode repo is the home of the C# extension. So we track all issues related to the C# extension there (including things that have nothing to do with OmniSharp).
