### ISSUE TITLE
About 40% regression or the XmlDocument performance test Create()

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/coreclr#17715]
The Regression for the XmlDocument performance test [Create()](https://github.com/dotnet/corefx/blob/697e2b910e6cccbc1f3d58be111e309db4823ab7/src/System.Private.Xml/tests/XmlDocument/Performance/Perf.XmlDocument.cs#L16) is illustrated in the chart below.

<img width="1062" alt="screen shot 2018-04-20 at 6 03 33 pm" src="https://user-images.githubusercontent.com/5897654/39078880-32feeb30-44c5-11e8-9886-3b5f311fb9c5.png">

Refer to [benchview](https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[23]&mpids=[1292]&cfgids=[2785,2706]&testids=[61756]&jobid=94550&) for more details.

@krwq I was looking at the Marvin hashcode commit dotnet/corefx@697e2b9 you submitted in January and it seems when instantiating XmlDocument it suddenly regressed. Was this by design or not intentional?

Overall the regression is about 45% on Linux (and around 30% on Windows). Although the regression seems to have started from January, there have been some ups and downs since so not exactly sure if I can find the exact root cause for the overall regression here in a straightforward way.

The test Create() as seen [here](https://github.com/dotnet/corefx/blob/697e2b910e6cccbc1f3d58be111e309db4823ab7/src/System.Private.Xml/tests/XmlDocument/Performance/Perf.XmlDocument.cs#L16), just attempts to create new XmlDocument() multiple times.

cc: @kouvel @danmosemsft

**Comment by RussKeldorph** [comment]
@maryamariyan Can you clarify why this was opened in coreclr instead of corefx?

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#29260

**Comment by maryamariyan** [comment]
@RussKeldorph please accept my sincerest apology here. This was meant to be created for corefx.

I copied the template from another issue I had opened earlier by right clicking on the issue page (creating the issue in that repo), not noticing the original was already in coreclr.
 
I was paying much attention to the content of the issue that I missed this detail.
