### ISSUE TITLE
headers to use when porting Profiler from windows to linux

### ISSUE THREAD

**Issue by fwanggg** [dotnet/coreclr#17736]
I have a CLR profiler that supports dotnet core 2.0 on Windows. Now i wish to port it to build and work on  Linux. I think i need some guidance on what are the best practices and/or an relatively realistic example.

I had started my research based on a sample dotnet core profiler written by MS folks:
https://github.com/Microsoft/clr-samples/tree/master/ProfilingAPI/ReJITEnterLeaveHooks
(recommended starting point as is stated in this issue: https://github.com/dotnet/coreclr/issues/14786). 

This Sample Profiler uses **PAL** and uses `PAL_STDCPP_COMPAT` which i believe would simplify the porting of Windows API. However, i found that:
`typedef char16_t WCHAR;` in file `pal_mstypes.h`. 

This is not good because `WCHAR` on Linux is now no longer wchar_t but the old windows code interchangeably uses WCHAR and wchar_t in lots places. So i see lots of compilation error trying to pass `L"foobar"` to Profiling related API that takes `LPWSTR` (e.g. `IMetaDataAssemblyImport->GetAssemblyProps`).  porting `wchar_t` to `char16_t` is not ideal in this case either. So i concluded that the way that the Sample Profiler is setup probably doesn't suit me well.

In fact, there was an issue in the sampler profiler complaining the exact same type compilation error, i.e. passing `wchar_t*` to a API that takes `WCHAR*`. And looking at the fix https://github.com/Microsoft/clr-samples/commit/e9e57e5526da374dc8012afee0395aa946515921, the author didn't fix it. He just simply removed the code, so it's not helpful. 

Then i start looking at the coreclr source code. I think the Profiler should perhaps use same types defined in the clr itself simply because how closely these two interact.  So My observation shows that `cor.h` (a necessary piece for a profiler) uses **PAL**( e.g. It has to reference `STDMETHOD ` defined in `palrt.h`) however, the clr itself uses `WCHAR` defined as `wchar_t` in `pal_mstypes.h` under condition that `PAL_STDCPP_COMPAT` is not defined. So the CLR itself probably doesn't need to port wchar_t string literal to chart_16. 

I feel that Profiler better off uses **PAL** because **CLR** uses it. But Should i use `PAL_STDCPP_COMPAT` as the sample profiler did? If i use it, i get WCHAR defined as char16_t which is defined different from coreclr, which seems wrong for the Profiler. 

I am little confused because types like `WCHAR `are defined in 3 places(`pal_mstypes.h/PAL_STDCPP_COMPAT`, `pal_mtypes.h`,`clr_types.h`). what headers/Compilation flags should i use,  so the types of the Profiler can be the same as in the CoreCLR. It feels like the Profiler writer has to carefully arrange those include headers but i have no clue how?  OR i guess it might be helpful if someone explains in general how the Profiling Interface piece in CLR is built if the Profiler should be doing the same?

**Comment by davmason** [comment]
CoreCLR and the profiling apis use char16_t everywhere on non-windows platforms. Windows wchar is 16 bits and we have lots of assumptions about wchar being 16 bits.

If you use char16_t everywhere you interact with the profiler, it will work. You can use 16 bit literals to interact with the profiler. I.e. `u"16 bit literal string"`

When porting our profiler tests to linux and mac I ran in to the issue that lots of standard string manipulation libraries are not implemented for char16_t. The PAL provides implementations of these libraries, but our test code was not using the PAL so I worked around it by using wchar for string manipulation and then converting to char16_t everywhere we needed to call in to the profiler apis. It's a bit less efficient but works.

Hope this helps.

**Comment by fwanggg** [comment]
@davmason  it helps. 
Good to know char16_t is the way to go.
However, i do see 
https://github.com/dotnet/coreclr/blob/master/src/inc/clrtypes.h#L183
where WCHAR is defined as wchar_t. And used in places like this(i didn't analyze the include dependencies myself because it's a massive project. I had my IDE resolves it for me.):
https://github.com/dotnet/coreclr/blob/master/src/ildasm/ceeload.cpp#L93

isn't `ceeload.cpp` part of CoreCLR? But it's actually using wchar_t not char16_t?
Or maybe only the part that actually interact with profiler needs to be in char16_t (which is what i need)?

**Comment by janvorli** [comment]
@fwanggg coreclr is not compiled with PAL_STDCPP_COMPAT. That was added for special purposes of out of coreclr usage of the PAL to enable including the pal headers together with some std c++ headers minimizing the risk of name clashing.
If you don't need to include some headers from the platform together with the PAL headers in your profile and can rely on just what our PAL provides, then you don't want to define  PAL_STDCPP_COMPAT and both wchar_t and WCHAR will be defined as wchar16_t.

However, if you define PAL_STDCPP_COMPAT, then only WCHAR is 16 bit . The wchar_t is 32 bit so that it matches what the std c++ and other platform headers expect. So in such case, your code needs to strictly stick to using just the WCHAR for stuff that's going to be used for the PAL calls and places where you want 16 bit chars.

**Comment by fwanggg** [comment]
@janvorli sorry if i misunderstand but @davmason mentioned **CoreCLR and the profiling apis use char16_t everywhere on non-windows platforms.**

And you mentioned **coreclr is not compiled with PAL_STDCPP_COMPAT** which means CoreCLR uses wchar_t from what i can see from the code below.

The 2 statements seem to be contradictory from what i can understand. which one is correct or both(because i didn't understand it)?

```
#ifdef PAL_STDCPP_COMPAT

#ifdef BIT64
typedef unsigned long int uintptr_t;
#else // !BIT64
typedef unsigned int uintptr_t;
#endif // !BIT64

typedef char16_t WCHAR;

#else // PAL_STDCPP_COMPAT

**typedef wchar_t WCHAR;**
#if defined(__linux__) 
#ifdef BIT64
typedef long int intptr_t;
typedef unsigned long int uintptr_t;
#else // !BIT64
typedef int intptr_t;
typedef unsigned int uintptr_t;
#endif // !BIT64
#else
typedef INT_PTR intptr_t;
typedef UINT_PTR uintptr_t;
#endif
```

**Comment by janvorli** [comment]
@fwanggg I am sorry for not being clear. Coreclr does use wchar_t, but it is redefined as #define wchar_t __wchar_16_cpp__ here:
https://github.com/dotnet/coreclr/blob/master/src/pal/inc/pal_char16.h#L32

**Comment by fwanggg** [comment]
@janvorli wow, there is the secret i missed i think. 
So, just to confirm, so coreclr does use the 16bit type not the 32 bit type because `wchar_t` gets hijacked and redefed. 
So, as a profiler writer, i should really stick with char16_t and forget about the 32bit standard wchar_t type. is this statement correct?

**Comment by janvorli** [comment]
@fwanggg since you are porting the profiler from Windows, it would be the best way.

**Comment by fwanggg** [comment]
@janvorli thanks for the clarification.
