### ISSUE TITLE
[Question] R2R and version bubbles

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#17735]
As I understand the main motivation to create Ready To Run mode of crossgen is making native images are more independent from runtime change. What is the current state of it? Should we regenerate application native images in case of updating runtime or system libraries (of course, I mean case when API isn't changed)?

Second question is about version bubbles. As I see from source code (https://github.com/dotnet/coreclr/blob/master/src/vm/jitinterface.cpp#L654) `Version bubble == Assembly`. Are there any plans to implement this concept?
What projects will needed changes to support this? Except CoreCLR I think compiler should know about bubbles. Are there any other projects?

cc @jkotas @BruceForstall @gbalykov

**Comment by jkotas** [comment]
> What is the current state of it? 

We use it in all our shipping configurations. CoreLib on x86/x64 is the last library that is still using fragile NGen. I expect that we will switch it to R2R as well.

We see a very good results when R2R is used together with tiered JITing (R2R is used as "Tier 0" JIT). I expect that we going to enable tiered JITing by default.

> Are there any plans to implement this concept?

I expect that we will focus on tiered JITing because of it will give us better performance than eliminating version bubbles.

> Are there any other projects?

The build tasks that are calling crossgen would need to know about it too.

**Comment by alpencolt** [comment]
By our estimation R2R is on **20%** slower than R2R on application startup on ARM which is very important metric for consumer electronic. So we are looking ways to improve situation.

What is the status of tiered JIT? Is there any documentation how to use it? I saw only the issue https://github.com/dotnet/coreclr/issues/4331

cc @Dmitri-Botcharnikov

**Comment by jkotas** [comment]
> By our estimation R2R is on 20% slower than R2R on application startup on ARM 

Yes, R2R is not as fast as fragile NGen. Tiered JIT helps with it somewhat. There are more opportunities for optimizations:
- R2R is not able to save code for all methods in version resilent way (generics are typically the worst offender) 
- It should be possible to speed up type loader as well

It would be useful to know where does the 20% in your case goes.

> What is the status of tiered JIT? Is there any documentation how to use it? 

Set COMPlus_TieredCompilation environment variable (https://github.com/dotnet/coreclr/pull/17283). If you would like to know more details about it, ask on #4331.

**Comment by jkotas** [comment]
> is it possible to improve R2R to save more (or all) methods in version resilient way, for example generics over value types?

Shared generic code for value types. http://www.mono-project.com/docs/advanced/runtime/docs/gsharedvt/ describes the basic idea and how it was implemented in Mono runtime. The implementation for CoreCLR would not be same, but the idea would be very similar.

The CoreRT compiler has infrastructure for this. We are currently investigating whether it is feasible to use the CoreRT compiler to produce native images for CoreCLR to solve problems like these.

**Comment by jkotas** [comment]
cc @nattress @davidwrighton
