### ISSUE TITLE
unix coreconsole fails in when run via PATH search

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#1774]
CoreConsole uses argv[0] to determine it's location, which causes problems when a coreconsole-based app is on the PATH and is run from shell.

Repro steps:

Create a simple C# app (just something that prints hello world will work, or use an existing test app)
Compile it assemble a coreconsole-based app so that you have a single-folder standalone application
Put that folder on the PATH environment variable
Attempt to run it from while in the directory containing the app => It should work
Change to another directory => It now fails with `Could not get full path to current executable: No such file or directory`

**Comment by janvorli** [comment]
It looks like on Linuxes, we can get the full path by calling readlink function with "/proc/self/exe" and on FreeBSD readlink function with "/proc/curproc/file".
For OSX, there seems to be proc_pidpath function that can get a path for a pid.

**Comment by stephentoub** [comment]
> It looks like on Linuxes, we can get the full path by calling readlink function with "/proc/self/exe" ... For OSX, there seems to be proc_pidpath function that can get a path for a pid.

Yeah, that's what we do in System.Diagnostics.Process in corefx on Linux and OS X:
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Linux.cs#L184
and
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.OSX.cs#L180

**Comment by davidfowl** [comment]
It would be great if we could fix this ASAP :smile:

**Comment by gkhanna79** [comment]
I am working on a fix - tested on Mac and need to test on Ubuntu.

**Comment by davidfowl** [comment]
:+1:
