### ISSUE TITLE
Division of Vector3 by a scalar is slow (10x times slower than by a vector3)

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#17750]
As far as I understand the following code
```
var v1 = new Vector3(1, 1, 1);
var v2 = v1 / 2.0f;
```
converts `2.0f` to a `Vector3(2.0f, 2.0f, 2.0f)` and divide `v1` by this vector (see https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/src/System/Numerics/Vector3_Intrinsics.cs#L273) using intristics so it sounds like it should perform with the same speed as:
```
var v1 = new Vector3(1, 1, 1);
var v2 = v1 / new Vector(2.0f, 2.0f, 2.0f);
```
but the results are: https://gist.github.com/EgorBo/b961aec1b6814b71c4ba8c53984a507e
10x time slower than the division by a vector.

it feels like `new Vector3(float)` has wrong intristics and slower than `new Vector3(float, float, float)`
Does it use `_mm_set1_ps` to populate a vector from a scalar?
I see all operations are inlined so I can't blame them.

---
![image](https://user-images.githubusercontent.com/523221/39188940-aa25c0c8-47d9-11e8-9985-65bd46a69a3f.png)

**Comment by mikedn** [comment]
The two versions aren't comparable as in the `DivideByVector` case the JIT manages to eliminate the entire loop body. Sure, it would be nice if the JIT did this in both cases but then the results wouldn't be relevant anyway. You need to adjust your tests so that dead code elimination does not kick in.

**Comment by mattwarren** [comment]
Out of interest, what does the output of the BenchmarkDotNet [`[DisassemblyDiagnoser]`](https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/guide/Configs/Diagnosers.md#disassembly-diagnoser) show?

> You need to adjust your tests so that dead code elimination does not kick in.

The BenchmarkDotNet docs show the recommended [way to do this](http://benchmarkdotnet.org/Guides/GoodPractices.htm#avoid-dead-code-elimination)

**Comment by EgorBo** [comment]
@mattwarren @mikedn you were right, rewrote the benchmark and the results now as a expected, thanks!

**Comment by mikedn** [comment]
For clarity here's the actual diff between the two versions when the result is stored in a static:
```diff
@@ -51,16 +52,7 @@
        8BC6         mov      eax, esi
        D1E0         shl      eax, 1
        C4E17057C9   vxorps   xmm1, xmm1
        C4E1722AC8   vcvtsi2ss  xmm1, eax
-       C4E16857D2   vxorps   xmm2, xmm2
-       C4E16A2AD0   vcvtsi2ss  xmm2, eax
-       C4E16057DB   vxorps   xmm3, xmm3
-       C4E1622AD8   vcvtsi2ss  xmm3, eax
-       C4E15857E4   vxorps   xmm4, xmm4
-       C4E15A10E3   vmovss   xmm4, xmm4, xmm3
-       C4E15973FC04 vpslldq  xmm4, 4
-       C4E15A10E2   vmovss   xmm4, xmm4, xmm2
-       C4E15973FC04 vpslldq  xmm4, 4
-       C4E15A10E1   vmovss   xmm4, xmm4, xmm1
-       C4E17828CC   vmovaps  xmm1, xmm4
+       C4E37121C90E vinsertps xmm1, xmm1, 14
+       C4E170C6C940 vshufps  xmm1, xmm1, 64
        C4E1785EC1   vdivps   xmm0, xmm1
```

It seems that `new Vector3(i * 2, i * 2, i * 2)` doesn't generate good code, the JIT doesn't realize that all 3 components are identical and treat it as `new Vector3(a, b, c)` which is more expensive.

If you use `new Vector3(i * 2)` you get identical code.
