### ISSUE TITLE
Server GC is set with different env vars across platforms

### ISSUE THREAD

**Issue by sywhang** [dotnet/coreclr#17760]
On Unix, we set server gc by setting ```COMPlus_gcServer=1```, but this does not work on Windows.

On Windows, we use ```complus_buildflavor=svr```. 

There is also this in ```coreruncommon.cpp``` and ```corerun.cpp```
```
// Name of the environment variable controlling server GC.
// If set to 1, server GC is enabled on startup. If 0, server GC is
// disabled. Server GC is off by default.
static const char* serverGcVar = "CORECLR_SERVER_GC"; 
```

We should try to make these into one variable that works across all platforms.

**Comment by jkotas** [comment]
`CORECLR_SERVER_GC` is corerun specific hack. corerun is our non-shipping host for our internal use. It should be fine to just remove this one.

**Comment by sywhang** [comment]
@jkotas, I'll remove ```CORECLR_SERVER_GC``` and ```CORECLR_CONCURRENT_GC```, and make COMPlus_gcServer and COMPlus_gcConcurrent be the only env var to enable server / concurrent GC.

**Comment by sywhang** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/17837
