### ISSUE TITLE
Runtime needs to support long paths on Windows without extended syntax

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/coreclr#1776]
The Windows APIs are used as the abstraction for the PAL. Need to set up wrappers so that we can shim in the extended path syntax where necessary.

**Comment by JeremyKuhne** [comment]
@Priya91 moved the runtime from fixed buffers- we still need to have the native code inject extended syntax when making File/Directory Management calls on Windows (\\\\?\\).

**Comment by gkhanna79** [comment]
Post discussion, we will target this for RTM as the cost to enable is about 4-6 weeks (across Windows/Ubuntu/Mac and testing it) and there is no impending need for it to be in RC2.

CC @tzwlai @brianrob @leecow @weshaggard @JeremyKuhne

**Comment by ramarag** [comment]
#3441, #3433 and #2998 fixes the native portions of the VM. Only the mscorlib remains to be fixed.
Assigning it back to @JeremyKuhne
