### ISSUE TITLE
Environment.CommandLine does not work as expected.

### ISSUE THREAD

**Issue by RabdPnguin** [dotnet/coreclr#17761]
Let's say I call a command with the following options:
cmd --option "--whatever"

Environment.CommandLine returns something different depending on whether it's a dotnet core app or full framework app.

4.7: "cmd.exe --option "--whatever""
core 2.0: "cmd.exe --option --whatever"

This presents a problem making it impossible (or at least difficult) to pass arguments that start with a hyphen to an option. Core should work just like the full framework. Return the unparsed args.

This also affects the dotnet core cli.

// [powershell] create a directory called "-o"
mkdir "-o" <-- notice this works in powershell which was built on the full framework/mono

dotnet new console -o -o
^ it will assume the 2nd -o is an option (which it should)
dotnet new console -o "-o"
^ it will strip the quotes and assume the 2nd -o is an option (which it shouldn't)

// speaking of the dotnet cli specifically...
dotnet new console -o:-o
dotnet new console -o:"-o"
^ the above two commands will create the console app in the current directory, NOT the "-o" directory.

dotnet new console -o=-o
dotnet new console -o="-o"
^ this actually works and will create the console app in the "-o" directory.

however, all the following should do the same thing.

dotnet new console -o "-o" //  command doesn't work
dotnet new console -o:"-o" // command works but creates the console app in wrong directory
dotnet new console -o="-o" // command works as expected

Why does : work differently than =?

**Comment by RussKeldorph** [comment]
@danmosemsft @karelz

**Comment by RussKeldorph** [comment]
This issue was moved to dotnet/corefx#29335

**Comment by RussKeldorph** [comment]
@RabdPnguin I moved this to dotnet/corefx#29335 to track the issue @karelz mentioned.  Feel free to open an issue in dotnet/cli or dotnet/core-setup per @steveharter.
