### ISSUE TITLE
Unable to publish project on Linux on 2.1 Preview 2

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/coreclr#17774]
Hi, my project built and published no problem on 2.0 and 2.1 Preview 1

but now I get:

```
/home/dan/repos/AvalonStudio/AvalonStudio/AvalonStudio.Languages.Xaml/AvalonStudio.Languages.Xaml.csproj : error NU1605: Detected package downgrade: Microsoft.NETCore.App from 2.0.6 to 2.0.0. Reference the package directly from the project to select a different version.  [/home/dan/repos/AvalonStudio/AvalonStudio/AvalonStudio/AvalonStudio.csproj]
/home/dan/repos/AvalonStudio/AvalonStudio/AvalonStudio.Languages.Xaml/AvalonStudio.Languages.Xaml.csproj : error NU1605:  AvalonStudio.Languages.Xaml -> Avalonia.Designer.HostApp -> Microsoft.NETCore.App (>= 2.0.6)  [/home/dan/repos/AvalonStudio/AvalonStudio/AvalonStudio/AvalonStudio.csproj]
/home/dan/repos/AvalonStudio/AvalonStudio/AvalonStudio.Languages.Xaml/AvalonStudio.Languages.Xaml.csproj : error NU1605:  AvalonStudio.Languages.Xaml -> Microsoft.NETCore.App (>= 2.0.0) [/home/dan/repos/AvalonStudio/AvalonStudio/AvalonStudio/AvalonStudio.csproj]
```
`AvalonStudio.csproj` is a `netcoreapp2.0` project.
`AvalonStudio.Languages.Xaml.csproj`is a `netcoreapp2.0` project
`Avalonia.Designer.HostApp` is also a `netcoreapp2.0` project.

The previous version was happy with this.

The repository containing the code at specific commit to repro is here:
https://github.com/VitalElement/AvalonStudio/commit/e947164d84a72f61a5b44dfcb4b5c93e7af2d63e

`git clone --recursive`
`cd AvalonStudio\AvalonStudio\AvalonStudio`
`dotnet publish -c Release -f netcoreapp2.0 -r debian.8-x64`

Let me know if I can provide any further information.

Thanks in advance.

**Comment by RussKeldorph** [comment]
@danmosemsft @karelz

**Comment by danmosemsft** [comment]
@steveharter any idea where this should go?

**Comment by karelz** [comment]
Aren't these NuGet errors?
@danwalmsley did you retarget your project to 2.1 Preview2? Does it fail only during publish, or also during build?
Are you able to minimize the repro to standalone projects referencing the suspicious NuGet packages?

**Comment by danwalmsley** [comment]
@karelz dotnet build works on its own.

I left the project files as they were .netcoreapp2.0.

I will have a go at minimizing the repro.

**Comment by danwalmsley** [comment]
@karelz the references are Project references not Nuget packages.

Im trying to get you a minimal repro asap.

**Comment by RussKeldorph** [comment]
@karelz Do we know enough to say where this bug should be tracked?  Do we know if it might require a 2.1 fix?

**Comment by danwalmsley** [comment]
[Repro.zip](https://github.com/dotnet/coreclr/files/1968223/Repro.zip)
Ok sorry for the delay here is a repro of the issue.

Extract the zip file.

Install dotnet 2.1 preview 2

cd into AvalonStudio.Languages.Xaml directory.

run `dotnet publish -f netcoreapp2.0 -r win7-x64`

you will get the error,

uninstall the preview and go back to version 2 sdk.

run the publish command again, it will work.

**Comment by karelz** [comment]
This issue was moved to dotnet/sdk#2207
