### ISSUE TITLE
Fix IMPL_LIMITATION on Struct LclVar Offsets for 64-bit targets

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#17777]
The emitter has a `struct emitLclVarAddr` which has  a limitation on offset values for large LclVars numbers (above 32767)   For our 64-bit targets we can use some extra bits to eliminate this limiation.

**Comment by sdmaclea** [comment]
@briansull It looked like #17793 was intended to fix this.  However it is not closed and the test added by #17793 is failing on linux-arm64.  Should I open  separate issue, or is this still supposed to be open?

**Comment by briansull** [comment]
Yes, I thought that #17793 would fix the test case that I added for all platforms.

There may be a different issue on Arm64 that is causing the test to fail.

I am holding off on checkin in this change.

**Comment by briansull** [comment]
I am seeing the Arm64 failure:

 Assertion failed 'emitCurIG != emitPrologIG' in 'Repro.Program:Test

So we should open am issue for that (assuming thta iis what we see on Linux as well.

**Comment by sdmaclea** [comment]
Opened #17841

**Comment by briansull** [comment]
The Fix for #17793 will suffice for now.
