### ISSUE TITLE
ICLRRuntimeHost2，is it multithread  safe？

### ISSUE THREAD

**Issue by daoqiang** [dotnet/coreclr#17790]
ICLRRuntimeHost2，is it multithread  safe？
thank you

**Comment by RussKeldorph** [comment]
@jkotas Can you redirect or answer?

**Comment by jkotas** [comment]
cc @jeffschwMSFT 

Some of the methods are (like CreateDelegate), some of the methods are not (like CreateAppDomainWithManager).

**Comment by daoqiang** [comment]
ok,thank you
