### ISSUE TITLE
Port RayTracer benchmark to SoA algorithm using Vector128/256<T>

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#17798]
The current SIMD benchmark [RayTracer](https://github.com/dotnet/coreclr/tree/master/tests/src/JIT/Performance/CodeQuality/SIMD/RayTracer) is using `Vector3` to vectorize the basic 3D vector operations. However, this program is an AoS algorithm that cannot leverage wider SIMD operations. So, we should port RayTracer to a SoA algorithm using AVX intrinsics with `Vector256<T>`, then extend it to SSE* intrinsic with `Vector128<T>`.

cc @CarolEidt @tannergooding @AndyAyersMS @jkotas

**Comment by fiigii** [comment]
I will work on this issue, please assign to me.

**Comment by AndyAyersMS** [comment]
Please make a new benchmark so we have both versions.

**Comment by fiigii** [comment]
Yes, this benchmark is only for Intel hardware intrinsic, which will be put in https://github.com/dotnet/coreclr/tree/master/tests/src/JIT/HardwareIntrinsics/X86

**Comment by AndyAyersMS** [comment]
Perhaps you should add it over where we have all the other benchmarks:

https://github.com/dotnet/coreclr/tree/master/tests/src/JIT/Performance/CodeQuality

**Comment by fiigii** [comment]
Thanks for the suggestion. Will do.
