### ISSUE TITLE
Request safe non-allocation bit converter between value type and byte array

### ISSUE THREAD

**Issue by horney0824** [dotnet/coreclr#17809]
I always face some needs like write some value type to a chunk of memory (and read back) byte by byte.
But there is no way to write a struct or struct array to an existing byte array for now, except the unsafe pointer way.

Add APIs like below will be a big help:

public static void Write<T>(Span<T> elem, Span<byte>)where T:struct
public static void Read<T>(Span<T> elem, Span<byte>)where T:struct

**Comment by jkotas** [comment]
You can write this using `MemoryMarshal.AsBytes(span1).CopyTo(span2)`.

If you believe that this is not good enough and we need a dedicated API for it, please open API proposal issue in corefx repo: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md
