### ISSUE TITLE
ResourceManager doesn't take the SatelliteContractVersion attribute into account

### ISSUE THREAD

**Issue by sergey-kanaev** [dotnet/coreclr#17816]
I have a third-party .NET Standard 2.0 class library built with MSBuild via VisualStudio. The library has the SatelliteContractVersion attribute. The corresponding satellite assembly with localization resources has an assembly version that differs from the main library's assembly version.
The main assembly is loaded successfully by the .NET Framework 4.6.1 and .NET Core framework. But the satellite assembly is loaded only if an application that uses the library is built with .NET Framework 4.6.1. 
 
The issue occurs in .NET Core because the ResourceManager.GetSatelliteContractVersion() method always returns the 'null' value. So the ResourceManager in .NET Core ignores the version of the satellite assembly, which is specified in the SatelliteContractVersion attribute of the main assembly. Instead, the ResourceManager tries to load the satellite assembly with the version specified in the AssemblyVersion attribute of the main assembly.

For example, the following attributes are applied to the assembly:
- [assembly: AssemblyVersion("1.2.3.4")]
- [assembly: SatelliteContractVersion("1.2.0.0")]

After building using MSBuild, the following assemblies are created:
- a main assembly "A.dll" with version 1.2.3.4;
- a satellite assembly "A.resources.dll" with version 1.2.0.0.

.NET Core framework loads assembly "A.dll" with version 1.2.3.4 and tries to load the "A.resource.dll" assembly with version 1.2.3.4.

.NET Framework 4.6.1 loads assembly "A.dll" with version 1.2.3.4 and tries to load the "A.resouces.dll" assembly with version 1.2.0.0.

The issue leads to different behavior if the existing libraries with the SatelliteContractVersionAttribute are built by MSBuild in .NET Framework applications and .NET Core applications.

**Comment by RussKeldorph** [comment]
@jeffschwMSFT

**Comment by jkotas** [comment]
Fixed by #22249
