### ISSUE TITLE
Ensure that any byrefs created in genCodeForIndexAddr cannot point outside of the array

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#17823]
For Arm/arm64 in `CodeGen::genCodeForIndexAddr(GenTreeIndexAddr* node)` we need to insure that we don't create a byref that might point outside of the array object.

**Comment by briansull** [comment]
Fix available in https://github.com/briansull branch byref-fix

**Comment by BruceForstall** [comment]
https://github.com/dotnet/coreclr/compare/master...briansull:byref-fix

**Comment by briansull** [comment]
I could not make a test case the currently has a problem, because we are fairly cautious  when folding constants into array LEA instructions.  That could change in the future, so we should fix this to prevent problems in the future when we do more address folding operations.

**Comment by briansull** [comment]
Fixed with #17866
