### ISSUE TITLE
Concurrent GC enabled with multiple env vars

### ISSUE THREAD

**Issue by sywhang** [dotnet/coreclr#17824]
Concurrent GC can be enabled by setting environment variable COMPlus_gcConcurrent=1

There is another variable that sets this: CORECLR_CONCURRENT_GC.

We should only have one variable that sets concurrent GC instead of having multiple of them.

Similar issue to https://github.com/dotnet/coreclr/issues/17760

**Comment by jkotas** [comment]
`CORECLR_CONCURRENT_GC` is corerun specific hack. corerun is our non-shipping host for our internal use. It should be fine to just remove this one.

**Comment by sywhang** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/17837
