### ISSUE TITLE
Unhandled managed exceptions don't generate core dump

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#1782]
Core dumps are not generated currently because "exit()" (via ExitProcess) is used to terminate the process instead of "abort()" (TerminateProcess) in the HandleFatalError path.

**Comment by gkhanna79** [comment]
@cshung - We should see how this can be aligned with WER work that is done in EEPolicy::LogFatalError

**Comment by mikem8361** [comment]
@cshung, @gkhanna79 PR #1811 fixes this issue.

**Comment by mikem8361** [comment]
#1811 fixes this issue.
