### ISSUE TITLE
SEHException occurs VS 2017 Remote Debugging on Windows  to debug Linux ASP.NET Core application

### ISSUE THREAD

**Issue by mwoo-o** [dotnet/coreclr#17825]
Application Environment: Oracle Linux 7.4 (RedHat 7.4)
Debugging Environment: Visual Studio Enterprise 2017 v15.6.6 on Windows
.NET Core SDK Version on both Windows and Linux: 2.1.101

VS is able to attach the Linux ASP .NET Core process in the debugger.  However, when trying to step over or continue the execution, SEHException occurs.  Here is the exception information:
 - Data: System.Collections.ListDictionaryInternal
 - ErrorCode/HResult: -2147467259
 - Message: "External component has thrown an exception."

We have Microsoft sessions on site to talk about VS remote debugging for ASP.NET Core on Linux  and have documentation to describe how to do that.  However, the documentation is based on ubuntu Linux.    We follow similar steps in Oracle Linux v7.4 and encountered SEHException.  We also tried Console Application, and also encountered exception.

We need to know if VS Remote debugging on Window can debug .NET Core process in  Oracle Linux v7.1 or above.

**Comment by RussKeldorph** [comment]
@dotnet/dotnet-diag @dotnet/debugger-team

**Comment by gregg-miskelly** [comment]
@mwoo-o What version of vsdbg are you using (look at version.txt next to it)?
Can you grab a log from VS? https://github.com/Microsoft/VSDebugAdapterHost/wiki/Logging

**Comment by gregg-miskelly** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#2240

**Comment by gregg-miskelly** [comment]
I moved the issue for now. Please close this one.
