### ISSUE TITLE
[Arm64] JitStressRegs=0x200 GitHub_17777 asserts

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17861]
JIT/Regression/JitBlue/GitHub_17777/GitHub_17777/GitHub_17777.sh
jitStressRegs=0x200

```
corerun GitHub_17777.exe

Assert failure(PID 1462 [0x000005b6], Thread: 1462 [0x05b6]): Assertion failed 
'!"Unexpected inactive assigned interval in isRegInUse"' in 
'Repro.Program:Test(int,int,int,int,int,int,int,int,int,int,int,int,int,int......' 
(IL size 2418)

    File: /home/vmjenkins/workspace/Dotnet/build_coreclr/src/jit/lsra.cpp Line: 3441
```

@briansull @CarolEidt Assert is in lsra

**Comment by BruceForstall** [comment]
@CarolEidt Currently, the CI runs JitStressRegs with 1, 2, 3, 4, 8, 0x10, 0x80, 0x1000, for CoreCLR Pri-1 tests and CoreFX tests, and for R2R tests, and CoreCLR Pri-1 tests in conjunction with JitStress=2. Are there other combinations that should be run, such as JitStressRegs=0x200?

**Comment by CarolEidt** [comment]
@BruceForstall - The JitStressRegs values that were left out of regular testing were, at least at one time, known to have some implementation issues (i.e. the reason that they didn't run clean was due at least in part to some problems with the way the stress mode was implemented). I don't have specific recollection for why 0x200 was left out, so I'm going to look into this case to see if it's fundamental.
So - short answer is "no, we shouldn't run the other combinations, at least until we evaluate them".

**Comment by sdmaclea** [comment]
@CarolEidt For linux-arm64, I have been running most of the jitStressRegs combinations.  The only one which was obviously broken was 0x800.  Some may be worthless, because they fail to expose any issues...
