### ISSUE TITLE
UDP changes?

### ISSUE THREAD

**Issue by DanielRabasco** [dotnet/coreclr#17880]
I'm using a tracking system called Optitrack and connecting it via UDP protocol (using  .NET) with Unity.
 I've changed the Unity runtime scripting version from .NET 3.5 to .NET 4.6 (experimental) and when I run my scene, the fps start to decrease increasingly. With .NET  3.5 it doesn't happens.

Thanks for the help.

**Comment by jkotas** [comment]
Unity does not use .NET Core runtime. You should ask this question in Unity support forums.

**Comment by DanielRabasco** [comment]
Ok, thank you very much
