### ISSUE TITLE
 Unify remaining diverged collections types in corelib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#17897]
We have reached the point that 60% of CoreCLR corelib code is shareable. We believe we can reasonably take this further, perhaps to 80% however much of the remaining reconciliation will take domain knowledge because the merges are not trivial.  See #9474

From a diff of `corert\src\system.private.corelib\src` and `coreclr\src\mscorlib\src` these are files related to collections whose implementations are yet to be unified. In some cases this will take care. In some happy cases the CoreRT code may just be a frozen old copy of the CoreCLR code from years ago in which case possibly resolution may be just "take coreclr". Once implementations have been reconciled, the shared copy should move under "shared" and the other copies deleted.
 	
- [ ]  	.\system\collections\concurrent\lowlevelconcurrentqueue.cs
- [ ]  	.\system\collections\generic\arraysorthelper.cs
- [ ]  	.\system\collections\generic\comparer.cs
- [ ]  	.\system\collections\generic\compatibilityequalitycomparers.cs
- [ ]  	.\system\collections\generic\equalitycomparer.cs
- [ ]  	.\system\collections\generic\equalonlycomparer.cs

**Comment by filipnavara** [comment]
Is anything still left for this one?

**Comment by jkotas** [comment]
Looks all done.
