### ISSUE TITLE
Unify remaining diverged diagnostics types in corelib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#17898]
We have reached the point that 60% of CoreCLR corelib code is shareable. We believe we can reasonably take this further, perhaps to 80% however much of the remaining reconciliation will take domain knowledge because the merges are not trivial. See #9474

From a diff of `corert\src\system.private.corelib\src` and `coreclr\src\mscorlib\src` these are files related to diagnostics whose implementations are yet to be unified. In some cases this will take care. In some happy cases the CoreRT code may just be a frozen old copy of the CoreCLR code from years ago in which case possibly resolution may be just "take coreclr". Once implementations have been reconciled, the shared copy should move under "shared" and the other copies deleted

- [x]  	.\system\diagnostics\debug.corert.cs
- [x]  	.\system\diagnostics\debug.windows.cs
- [x]  	.\system\diagnostics\debugannotations.cs
- [x]  	.\system\diagnostics\debugger.cs
- [x]  	.\system\diagnostics\debuggerguidedstepthroughattribute.cs
- [x]  	.\system\diagnostics\lowleveldebugfunceval.cs
- [x]  	.\system\diagnostics\stackframe.corert.cs
- [x]  	.\system\diagnostics\stackframe.cs
- [x]  	.\system\diagnostics\stackframeextensions.cs
- [x]  	.\system\diagnostics\stacktrace.cs
- [x]  	.\system\diagnostics\contracts\contracts.cs
- [ ]  	.\system\diagnostics\contracts\contractsbcl.cs
- [ ]  	.\system\diagnostics\tracing\eventsource_corert.cs
- [ ]  	.\system\diagnostics\tracing\unsafenativemethods.cs

**Comment by filipnavara** [comment]
StackTrace.cs and Contracts.cs are done now.

**Comment by filipnavara** [comment]
- debug.corert.cs was already cleaned up and unified
- debug.windows.cs is not present in CoreRT anymore
- debugger.cs is purely `InternalCall`s in CoreCLR, so not worth sharing
- lowleveldebugfunceval.cs (LowLevelDebugFuncEval class), debugannotations.cs (DebugAnnotations class), debuggerguidedstepthroughattribute.cs (DebuggerGuidedStepThroughAttribute class), stackframeextensions.cs (StackFrameExtensions class) exists in CoreRT only, there is no CoreCLR equivalent

That leaves out:
- .\system\diagnostics\contracts\contractsbcl.cs
- .\system\diagnostics\tracing\eventsource_corert.cs
- .\system\diagnostics\tracing\unsafenativemethods.cs
