### ISSUE TITLE
Unify remaining diverged globalization types in corelib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#17896]
We have reached the point that 60% of CoreCLR corelib code is shareable. We believe we can reasonably take this further, perhaps to 80% however much of the remaining reconciliation will take domain knowledge because the merges are not trivial.  See #9474

From a diff of `corert\src\system.private.corelib\src` and `coreclr\src\mscorlib\src` these are files related to globalizations whose implementations are yet to be unified. In some cases this will take care. In some happy cases the CoreRT code may just be a frozen old copy of the CoreCLR code from years ago in which case possibly resolution may be just "take coreclr". Once implementations have been reconciled, the shared copy should move under "shared" and the other copies deleted.

- [ ]  	.\system\globalization\calendardata.dummy.cs
- [ ]  	.\system\globalization\charunicodeinfodata.cs
- [ ]  	.\system\globalization\compareinfo.dummy.cs
- [ ]  	.\system\globalization\culturedata.dummy.cs
- [ ]  	.\system\globalization\cultureinfo.cs
- [ ]  	.\system\globalization\cultureinfo.dummy.cs
- [ ]  	.\system\globalization\cultureinfo.unix.cs
- [ ]  	.\system\globalization\cultureinfo.windows.cs
- [ ]  	.\system\globalization\globalizationmode.cs
- [ ]  	.\system\globalization\globalizationmode.unix.cs
- [ ]  	.\system\globalization\globalizationmode.windows.cs
- [ ]  	.\system\globalization\hijricalendar.dummy.cs
- [ ]  	.\system\globalization\idnmapping.dummy.cs
- [ ]  	.\system\globalization\japanesecalendar.dummy.cs
- [ ]  	.\system\globalization\normalization.dummy.cs
- [ ]  	.\system\globalization\textinfo.dummy.cs
- [ ]  	.\system\text\codepagedataitem.cs
- [ ]  	.\system\text\encodingdata.cs
- [ ]  	.\system\text\encodingtable.cs

**Comment by ANahr** [comment]
This is likely already mostly done by
#21735
#20529
others

All that is left is:
- [ ]  .\system\globalization\globalizationmode.cs
- [ ]  .\system\globalization\globalizationmode.unix.cs
- [ ]  .\system\globalization\globalizationmode.windows.cs
