### ISSUE TITLE
Unify remaining diverged reflection types in corelib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#17900]
We have reached the point that 60% of CoreCLR corelib code is shareable. We believe we can reasonably take this further, perhaps to 80% however much of the remaining reconciliation will take domain knowledge because the merges are not trivial.   See #9474

From a diff of `corert\src\system.private.corelib\src` and `coreclr\src\mscorlib\src` these are files whose implementations are yet to be unified. In some cases this will take care. In some happy cases the CoreRT code may just be a frozen old copy of the CoreCLR code from years ago in which case possibly resolution may be just "take coreclr". Once implementations have been reconciled, the shared copy should move under "shared" and the other copies deleted.

- [ ]   	.\system\reflection\assembly.corert.cs
- [ ]  	.\system\reflection\assemblyname.cs
- [ ]  	.\system\reflection\assemblynamehelpers.cs
- [ ]  	.\system\reflection\assemblynamehelpers.strongname.cs
- [ ]  	.\system\reflection\assemblynamelexer.cs
- [ ]  	.\system\reflection\assemblynameparser.cs
- [ ]  	.\system\reflection\binderbundle.cs
- [ ]  	.\system\reflection\customattributedata.cs
- [ ]  	.\system\reflection\customattributeextensions.cs
- [ ]  	.\system\reflection\customattributenamedargument.cs
- [ ]  	.\system\reflection\customattributetypedargument.cs
- [ ]  	.\system\reflection\exceptionhandlingclause.cs
- [ ]  	.\system\reflection\fieldinfo.corert.cs
- [ ]  	.\system\reflection\legacycustomattributeapis.cs
- [ ]  	.\system\reflection\localvariableinfo.cs
- [ ]  	.\system\reflection\methodbase.corert.cs
- [ ]  	.\system\reflection\methodbody.cs
- [ ]  	.\system\reflection\missingmetadataexception.cs
- [ ]  	.\system\reflection\runtimeassemblyname.cs
- [ ]  	.\system\reflection\runtime\customattributes\runtimeimplementedcustomattributedata.cs
- [ ]  	.\internal\reflection\explicitscopeattribute.cs
- [ ]  	.\internal\reflection\metadatatransformedattribute.cs
- [ ]  	.\internal\reflection\augments\reflectionaugments.cs
- [ ]  	.\internal\reflection\core\nonportable\iruntimeimplementedtype.cs
- [ ]  	.\internal\reflection\core\nonportable\runtimetypeunifier.cs
- [ ]  	.\internal\reflection\extensions\nonportable\customattributeinheritancerules.cs
- [ ]  	.\internal\reflection\extensions\nonportable\customattributeinstantiator.cs
- [ ]  	.\internal\reflection\extensions\nonportable\customattributesearcher.cs

**Comment by jkotas** [comment]
A lot of these are done already. If there is anything left worth doing, it should be tracked by dedicated issues / PRs.
