### ISSUE TITLE
Remove ConcurrentStack from System.Private.CoreLib 

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/coreclr#17909]
This issue is opened to track removing ConcurrentStack from System.Private.CoreLib 

Referring to [comment](https://github.com/dotnet/coreclr/pull/17800#issuecomment-385092192) _From @stephentoub on Apr 27, 2018, 1:57 PM PDT_:

> ConcurrentStack is to my knowledge used in only one place in corelib, by PinnableBufferCache, which is in turn only used by Overlapped as a way to cache OverlappedData instances, and I think we could come up with something better than ConcurrentStack for this use case, in particular since every Push ends up allocating a Node in ConcurrentStack.

Related to issue: https://github.com/dotnet/coreclr/issues/17751

cc: @stephentoub @danmosemsft @jkotas

**Comment by kasper3** [comment]
Since [PinnableBufferCache](https://github.com/dotnet/coreclr/blob/14de6935792bd56eb11a87c211a4e04b1b29e019/src/System.Private.CoreLib/src/System/PinnableBufferCache.cs) is using `lock`s in most places around the usage of `ConcurrentStack<object> m_FreeList`, except when it does `TryPop` (in one place and without `lock` in another) and usage of `Push`, could we use `List<object>` to mimic LIFO or something else?

Also `private ConcurrentStack<object> m_FreeList = new ConcurrentStack<object>();` can be
`private readonly ConcurrentStack<object> m_freeList = new ConcurrentStack<object>();`

**Comment by jkotas** [comment]
PinnableBufferCache is a custom object pool. It suspect it is avoiding locks on the common Alloc/Free path for scalability.

It was used in number of places in corefx as well, and we simply got rid of it there. See https://github.com/dotnet/corefx/issues/15761. Similar concerns as discussed in the corefx issue apply here as well. The problem is basically how to simplify or eliminate PinnableBufferCache in CoreLib without regressing performance of large multithreaded workloads?

**Comment by kasper3** [comment]
Ok, so instead we should focus on usages of PinnableBufferCache instead of attempting to overhaul it and try to use (shared) array pool?

**Comment by kasper3** [comment]
Reading @adamsitnik's blog http://adamsitnik.com/Array-Pool/, it seems like we should probably use ArrayPool<T>.Create in this situation for performance? With ArrayPool<T>.Shared.Rent, implementation looks like this: https://github.com/kasper3/coreclr/commit/fc12eedb7934b9bfda812444b2e7024db17344a3. There seems to be no other reference of `PinnableBufferCache` in coreclr and corert.

**Comment by stephentoub** [comment]
@kasper3, no, PinnableBufferCache isn't used here to cache arrays, it's used here to cache OverlappedData instances.  The "Buffer" nomenclature is based on the type's original use case, but it's really just a PinnableObjectCache, for use with objects that are expected to be pinned.

Taking a step back here, the goal here isn't exactly to remove ConcurrentStack from CoreLib.  If PinnableBufferCache is the right tool for the job in Overlapped, and if ConcurrentStack is the right tool for the job in PinnableBufferCache, then the right answer is simply to delete ConcurrentStack from corefx and type forward to the implementation exposed from CoreLib.  However, I'm not convinced of either of those two "right tool for the job" statements.  The work here is to determine whether there's something better.  If we find that PinnableBufferCache is overkill and we can use a better caching scheme for OverlappedData instances, then the ConcurrentStack issue becomes moot: all uses would be gone and we could simply delete it from CoreLib.  But assuming we do want to keep PinnableBufferCache, I think it's likely there's a better data structure to be used than ConcurrentStack, we "just" need to find it.

Based on PinnableBufferCache's current implementation, it's needs are primarily to be able to do fast-path / inexpensive / thread-safe removals that may operate concurrently with an add or count operation.  It's currently using a LIFO data structure, which in theory would help with cache locality, but I'm not sure that's really impactful in this particular use case (it may be, I'm just a bit skeptical).  ConcurrentStack largely meets these needs, which I'm sure is why it was chosen, however every Push operation allocates, which is undesirable.  It would be nice to find a data structure that meets these needs and doesn't incur an allocation for each usage.  ConcurrentQueue may actually be sufficient; it has a much better memory allocation profile.  It's not LIFO, so the impact of that would need to be measured on real cases.  But more importantly, its Count method has much more expensive effects than ConcurrentStack's, so the impact of that would need to be examined (if Count is only used infrequently and on slow paths as appears to be the case, maybe that's ok, but maybe not).  Often in situations like this, thread-local storage is used, as is done in ConcurrentBag, but I expect that's likely a bad choice for this particular case, as it'll frequently be the case that pops end up happening on thread pool worker threads and pushes end up happening on thread pool I/O threads, which would make it an extremely expensive cache.  There may be some other data structure that could be implemented that would do better, but it would require experimentation.

**Comment by danmosemsft** [comment]
Even if ConcurrentStack stays in CoreLib, why not remove it from CoreFX? We used to prefer to duplicate collections because the CoreFX one was easier to work on. But it can now easily be worked on in the mirrored Corelib within CoreFX.

Same for ConcurrentQueue - CoreFX could consume from Corelib?

**Comment by jkotas** [comment]
> Same for ConcurrentQueue - CoreFX could consume from Corelib?

We do that already.

> ConcurrentStack 

The ConcurrentStack + PinnableBufferCache + Overlapped combo has a ton of cruft in it. I would rather just get of the cruft than try to optimize for it. Related to #18293 ,  cc @Anipik . I will try to look at it tonight.
