### ISSUE TITLE
NumberFormatInfo.CurrentInfo.CurrencySymbol does not detect machine regionalization settings

### ISSUE THREAD

**Issue by SonnevilleJ** [dotnet/coreclr#17906]
# Overview
When running on a US MacBook Pro, `NumberFormatInfo.CurrentInfo.CurrencySymbol` does not detect machine regionalization settings and returns `¤` instead of `$` even though the regionalization settings clearly indicate `$` should be used. This appears to be [hardcoded here](https://github.com/dotnet/coreclr/blob/eb6430a72fa0fd6c5ee79b7b2209f7c51559f0c1/src/mscorlib/shared/System/Globalization/NumberFormatInfo.cs#L61) in the `coreclr` project.

I've created a [.NET Core project](https://github.com/SonnevilleJ/dotnet-currency-test/) to demonstrate this issue.

# Behavior
* Expected behavior: `NumberFormatInfo.CurrentInfo` should return a `NumberFormatInfo` whose properties are set based on the regionalization settings of the host machine.
* Observed behavior: `NumberFormatInfo.CurrentInfo` returns a `NumberFormatInfo` with an incorrect `CurrencySymbol` property, set to `¤` instead of `$`.

**Comment by stephentoub** [comment]
What is your LANG environment variable set to?

**Comment by SonnevilleJ** [comment]
```bash
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by stephentoub** [comment]
Try doing:
```
export LANG=en_US.UTF-8
```

**Comment by SonnevilleJ** [comment]
Thanks, Stephen, that worked.
