### ISSUE TITLE
Rename coreclr\src\mscorlib directory to coreclr\src\System.Private.CoreLib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#17905]
See #9474. This will reduce confusion: as the work continues to unify more and more code in the two corelibs, it makes sense for the directory name to reflect this. Also, it reflects the rename we did from mscorlib for 1.0.

@maryamariyan you'll just need to do this and find everything that breaks. (Not just in the repo - eg., the mirror)

**Comment by maryamariyan** [comment]
@ViktorHofer I use sourcetree to navigate around this. With sourcetree I add small diffs into the file to have the file show up in working directory as changed. Then can right click on the file to log it and trace back to older commits by checking out its parents.

**Comment by danmosemsft** [comment]
@ViktorHofer just edit the URL, this restarts it at the rename (616976 is the first commit after the rename)
https://github.com/dotnet/coreclr/commits/master?after=616976119f02491c1cf89de29451b1cf285928a9+0&path%5B%5D=src&path%5B%5D=mscorlib
