### ISSUE TITLE
Reliability - Watson crash in AssemblySpec::Bind  

### ISSUE THREAD

**Issue by leculver** [dotnet/coreclr#17943]
We have a failure during EEStartup, tracked by this internal Watson bucket:
https://watson/Failure?FailureSearchText=4a3aff04-3ef6-bbbe-2ae8-2cffa0b278c3

This accounts for 91.6% of reported external failures in coreclr.dll:

    0 coreclr!AssemblySpec::Bind  0x0000000000000183    coreassemblyspec.cpp 
    1 coreclr!AppDomain::BindAssemblySpec  0x0000000000000126    appdomain.cpp 
    2 coreclr!PEFile::LoadAssembly  0x000000000000010C    pefile.cpp 
    3 coreclr!Module::LoadAssembly  0x00000000000000F6    ceeload.cpp 
    4 coreclr!Assembly::FindModuleByTypeRef  0x00000000000001F9    assembly.cpp 
    5 coreclr!ClassLoader::LoadTypeDefOrRefThrowing  0x00000000000002AE    clsload.cpp 
    6 coreclr!SigPointer::GetTypeHandleThrowing  0x000000000000021F    siginfo.cpp 
    7 coreclr!MemberLoader::GetDescFromMemberRef  0x000000000000039B    memberload.cpp 
    8 coreclr!CEEInfo::resolveToken  0x00000000000005A6    jitinterface.cpp 
    9 clrjit!Compiler::impImportBlockCode  0x0000000000000927    importer.cpp 
    10 clrjit!Compiler::impImportBlock  0x0000000000000093    importer.cpp 
    11 clrjit!Compiler::impImport  0x00000000000002DB    importer.cpp 
    12 clrjit!Compiler::compCompile  0x00000000000000A4    compiler.cpp 
    13 clrjit!Compiler::compCompileHelper  0x0000000000000299    compiler.cpp 
    14 clrjit!Compiler::compCompile  0x000000000000025D    compiler.cpp 
    15 clrjit!jitNativeCode  0x000000000000026E    compiler.cpp 
    16 clrjit!CILJit::compileMethod  0x00000000000000A2    ee_il_dll.cpp 
    17 coreclr!invokeCompileMethod  0x00000000000000E5    jitinterface.cpp 
    18 coreclr!CallCompileMethodWithSEHWrapper  0x0000000000000052    jitinterface.cpp 
    19 coreclr!UnsafeJitFunction  0x00000000000004F5    jitinterface.cpp 
    20 coreclr!MethodDesc::JitCompileCodeLocked  0x00000000000001FE    prestub.cpp 
    21 coreclr!MethodDesc::JitCompileCodeLockedEventWrapper  0x00000000001313C1    prestub.cpp 
    22 coreclr!MethodDesc::JitCompileCode  0x0000000000000399    prestub.cpp 
    23 coreclr!MethodDesc::DoPrestub  0x000000000000059E    prestub.cpp 
    24 coreclr!PreStubWorker  0x000000000000037A    prestub.cpp 
    25 coreclr!ThePreStub  0x0000000000000055    ThePreStubAMD64.asm 
    26 coreclr!CallDescrWorkerInternal  0x0000000000000083    CallDescrWorkerAMD64.asm 
    27 coreclr!MethodDescCallSite::CallTargetWorker  0x00000000000002B5    callhelpers.cpp 
    28 coreclr!AppDomain::InitializeDomainContext  0x0000000000000105    appdomain.cpp 
    29 coreclr!SystemDomain::InitializeDefaultDomain  0x000000000000004E    appdomain.cpp 
    30 coreclr!SystemDomain::SetupDefaultDomain  0x0000000000000199    appdomain.cpp 
    31 coreclr!SystemDomain::SetupDefaultDomainNoThrow  0x000000000000004D    appdomain.cpp 
    32 coreclr!EEStartup  0x000000000000006E    ceemain.cpp

**Comment by jeffschwMSFT** [comment]
The underlying issue is that an attached profiler is injecting mscorlib references to System.Private.CoreLib which do not resolve and lead to the crash.  The best course forward is to understand why these profilers are not .NET Core aware.

**Comment by IlyaBiryukov** [comment]
There is another Watson with similar call stacks in VS Live Share vsls-agent.exe, 
https://watson/Failure?FailureSearchText=4a3aff04-3ef6-bbbe-2ae8-2cffa0b278c3&MaxRows=100

I'm pretty sure there was no attached profiler.

**Comment by jeffschwMSFT** [comment]
Profiler is attached in that bucket as well... lmi shows the loaded profiler.

**Comment by IlyaBiryukov** [comment]
Here is a call stack from [that Watson bucket](https://devdiv.visualstudio.com/DevDiv/Project%20Cascade/_queries?id=622918&triage=true&fullScreen=false&_a=edit) without profiler
```
coreclr!AssemblySpec::Bind in coreassemblyspec.cpp
coreclr!AppDomain::BindAssemblySpec in appdomain.cpp
coreclr!PEFile::LoadAssembly in pefile.cpp
coreclr!Module::LoadAssembly in ceeload.cpp
coreclr!Assembly::FindModuleByTypeRef in assembly.cpp
coreclr!ClassLoader::LoadTypeDefOrRefThrowing in clsload.cpp
coreclr!SigPointer::GetTypeHandleThrowing in siginfo.cpp
coreclr!MemberLoader::GetDescFromMemberRef in memberload.cpp
coreclr!CEEInfo::resolveToken in jitinterface.cpp
clrjit!Compiler::impImportBlockCode in importer.cpp
clrjit!Compiler::impImportBlock in importer.cpp
clrjit!Compiler::impImport in importer.cpp
clrjit!Compiler::compCompile in compiler.cpp
clrjit!Compiler::compCompileHelper in compiler.cpp
clrjit!Compiler::compCompile in compiler.cpp
clrjit!jitNativeCode in compiler.cpp
clrjit!CILJit::compileMethod in ee_il_dll.cpp
coreclr!invokeCompileMethodHelper in jitinterface.cpp
coreclr!invokeCompileMethod in jitinterface.cpp
coreclr!CallCompileMethodWithSEHWrapper in jitinterface.cpp
coreclr!UnsafeJitFunction in jitinterface.cpp
coreclr!MethodDesc::MakeJitWorker in prestub.cpp
coreclr!MethodDesc::DoPrestub in prestub.cpp
coreclr!PreStubWorker in prestub.cpp
coreclr!ThePreStub in asmhelpers.asm
coreclr!CallDescrWorkerInternal in asmhelpers.asm
coreclr!MethodDescCallSite::CallTargetWorker in callhelpers.cpp
coreclr!AppDomain::InitializeDomainContext in appdomain.cpp
coreclr!SystemDomain::InitializeDefaultDomain in appdomain.cpp
coreclr!SystemDomain::SetupDefaultDomain in appdomain.cpp
coreclr!SystemDomain::SetupDefaultDomainNoThrow in appdomain.cpp
coreclr!EEStartup in ceemain.cpp
coreclr!EnsureEEStarted in ceemain.cpp
coreclr!CorHost2::Start in corhost.cpp
coreclr!coreclr_initialize in unixinterface.cpp
hostpolicy!coreclr::initialize
hostpolicy!run
hostpolicy!corehost_main
hostfxr!execute_app
hostfxr!fx_muxer_t::read_config_and_execute
hostfxr!fx_muxer_t::parse_args_and_execute
hostfxr!fx_muxer_t::execute
vsls.agent!wmain
vsls.agent!__scrt_common_main_seh in exe_common.inl
```

**Comment by jeffschwMSFT** [comment]
What indication shows that a profiler is not attached?  I looked at two dumps in that bucket and they both had the exact same profiler attached.
