### ISSUE TITLE
[Arm64] System.Linq.Expressions.Tests.ArrayBoundsTests.SingleNegativeBoundErrorMessage regression

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17958]
This test case was passing near 2.1 fork.
```
   System.Linq.Expressions.Tests.ArrayBoundsTests.SingleNegativeBoundErrorMessage(useInterpreter: True) [FAIL]
      Assert.Equal() Failure
                   (pos 2)
      Expected: Array dimensions exceeded supported range.
      Actual:   Arithmetic operation resulted in an overflo
                   (pos 2)
```

@dotnet/arm64-contrib @VSadov @OmarTawfik  FYI

**Comment by OmarTawfik** [comment]
@sdmaclea do you know who owns that part on coreclr? the test is passing on corefx master, so I'm assuming it is a recent change in coreclr.

**Comment by sdmaclea** [comment]
> @sdmaclea do you know who owns that part on coreclr? the test is passing on corefx master, so I'm assuming it is a recent change in coreclr.

I don't happen to know who owns it.

@jit-contrib @jkotas Does anyone know who would own this code?

**Comment by jkotas** [comment]
It is not unclear to me what you mean by "this code".

If the test is passing everywhere else, I expect that it is going to be JIT regression.

cc @adityamandaleeka

**Comment by briansull** [comment]
THe old message, "Array dimensions exceeded supported range."  originates here:

`dlls\mscorrc\mscorrc.rc:1418:    IDS_EE_ARRAY_DIMENSIONS_EXCEEDED        "Array dimensions exceeded supported range."`

likely thrown here:

`vm\jithelpers.cpp:3152:        EX_THROW(EEMessageException, (kOverflowException, IDS_EE_ARRAY_DIMENSIONS_EXCEEDED));`

```
#ifdef _WIN64
    // Even though ECMA allows using a native int as the argument to newarr instruction
    // (therefore size is INT_PTR), ArrayBase::m_NumComponents is 32-bit, so even on 64-bit
    // platforms we can't create an array whose size exceeds 32 bits.
    if (size > INT_MAX)
        EX_THROW(EEMessageException, (kOverflowException, IDS_EE_ARRAY_DIMENSIONS_EXCEEDED));
#endif
```

**Comment by BruceForstall** [comment]
Closing this. System.Linq.Expressions.Tests is disabled in CI. If we attempt to re-enable, we'll hit this again. https://github.com/dotnet/coreclr/issues/25269
