### ISSUE TITLE
Don't eliminate a cpblk when offsets are different

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#17969]
When the JIT encounters a cpblk between two different offsets of the same local, if both fields are not recognizable to the JIT (i.e. the `FieldSeqNode` returned by `IsLocalAddrExpr()` and/or the `gtFieldSeq` field of a `GT_LCL_FLD` is `FieldSeqStore::NotAField()`) it will incorrectly optimize away the cpblk.

**Comment by CarolEidt** [comment]
@adityamandaleeka I've tracked down the root cause, I have a smaller repro that fails with coreclr, and I'm currently working on a fix.

**Comment by adityamandaleeka** [comment]
Thanks @CarolEidt!
