### ISSUE TITLE
Cannot start dotnet app

### ISSUE THREAD

**Issue by serdam55** [dotnet/coreclr#17979]
I'm not an expert of NetCore and I'm not able to fix this issue. So I developed an application using NetCore 2.0, and I'm trying to run this on ubuntu machine.

I installed all the dependencies for NetCore on Ubuntu, and then I tried to run my app (is a dll) using this command: dotnet BotScrap.dll

I get this error:

`Error: An assembly specified in the application dependencies manifest (BotScrap.deps.json) was not found: package: 'Google.Protobuf', version : '3.5.1' path: 'lib/netstandard1.0/Google.Protobuf.dll'`

What I did wrong? How can I fix this?

Thanks.

**Comment by kasper3** [comment]
If documentation/googling doesn't help, you can try asking such usage questions at https://stackoverflow.com/questions/tagged/.net-core and share some reproducible steps or a sample project (if not the actual project). There is also a chat channel https://gitter.im/dotnet/cli for QA/help.

That error message suggests that your package is not restored properly, run `dotnet restore` in project directory and check if `~/.nuget/packages/google.protobuf/3.5.1/lib/netstandard1.0/Google.Protobuf.dll` exists.

seems to be working for me on ubuntu:

ProtobufSample.csproj
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.5.1" />
  </ItemGroup>

</Project>
```

Program.cs
```c#
using System;
using Google.Protobuf;

class Program
{
    static void Main(string[] args)
    {
        var data = ByteString.CopyFrom(new byte[] { 0, 1, 2, 3 });
        Console.WriteLine(data.ToBase64());
    }
}
```

type `dotnet run` in shell & hit `[Enter]` - works
`dotnet bin/Debug/netcoreapp2.0/ProtobufSample.dll` - works
`cd bin/Debug/netcoreapp2.0 && dotnet ProtobufSample.dll` - works

**Comment by serdam55** [comment]
hi @kasper3  so I guess should I use publish command first? How can I do that?

**Comment by janvorli** [comment]
Thank you @kasper3 for providing help!
