### ISSUE TITLE
What's data stored in method handle?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/coreclr#17980]
```
MethodInfo mi=...;
int data = Marshal.ReadInt32(mi.MethodHandle.Value);
int mask=0xffff;//how to set the mask?
int order=data&mask;
MethodInfo method=module.ResolveMethod(0x06000000+order);
```

I know, the lower bits is the order number of a method, but I don't know which position is the first bit.

What's the meaning of all the bits?

**Comment by svick** [comment]
This is really not something you should be reading from your code, at least assuming that code is meant for more than satisfying your curiosity. It's internal runtime data and the runtime does not give you any guarantee whatsoever about what's contained in it.

That being said, as far as I can tell, `MethodHandle.Value` is a pointer to the native `MethodDesc` type. If you want to look at that type, go to [the `src/vm/method.hpp` file](https://github.com/dotnet/coreclr/blob/v2.1-rc1/src/vm/method.hpp) for the version of .Net Core you're using (in my case, it's .Net Core 2.1 RC1).

There you will see that you were close: [the mask is `0x3FFF`](https://github.com/dotnet/coreclr/blob/v2.1-rc1/src/vm/method.hpp#L1680). But that's not the whole story. If the upper bits of the token are not all zero (which is guaranteed to happen for modules with more than 16K methods), then you will also need to access the `MethodDescChunk` type and doing that is [kind of involved](https://github.com/dotnet/coreclr/blob/v2.1-rc1/src/vm/method.hpp#L2176-L2178).

I have [attempted to translate the C++ code to C#](https://gist.github.com/svick/22d003327c5d002197748af399aecec0). The code seems to work for me, but it's possible it's not actually correct and it's likely it won't work on other versions of .Net.

**Comment by CreateAndInject** [comment]
so, if there are 17K methods, how can I get the order number of a method?
use 0x7fff as mask?
or there are not enough data?some data is lost?

**Comment by svick** [comment]
@CreateAndInject Look at the gist I linked from my previous comment. It contains the code that you would need for that.

**Comment by jkotas** [comment]
`MethodInfo.MetadataToken` property will give you the metadata token that you are looking for without any hacks.

Please do not add dependencies on runtime internal implementation details. It is very fragile, non-portable and likely wrong.
