### ISSUE TITLE
dotnet sdk support on RHEL 6.x

### ISSUE THREAD

**Issue by AmeetShinde** [dotnet/coreclr#17999]
It seems that dotnet core runtime is supported on RHEL 6.x with version 2.0.3 (with preview marker) but not the dotnet core SDK. We can certainly build the binaries for RHEL 6.x from other platforms but we also have requirement to run the test suite with dotnet test command on RHEL 6.x platform. For this, we need dotnet driver to be invoked on this platform. So how can we make dotnet tooling work on RHEL 6.x. If not, what is the workaround to run the tests on this platform.

**Comment by jkotas** [comment]
Related https://github.com/dotnet/core/issues/1260

cc @Petermarcu
