### ISSUE TITLE
CoreCLR should not handle SIGTERM

### ISSUE THREAD

**Issue by jaredpar** [dotnet/coreclr#1799]
Consider these two lines:

- https://github.com/dotnet/coreclr/blame/bc146608854d1db9cdbcc0b08029a87754e12b49/src/pal/src/thread/threadsusp.cpp#L1319
- https://github.com/dotnet/coreclr/blob/bc146608854d1db9cdbcc0b08029a87754e12b49/src/pal/src/thread/threadsusp.cpp#L1561

This means at least a portion of our threads will no longer respond to SIGTERM.  Which in turns means CoreCLR processes will not exit in response to the `kill` command.  Users will be forced to use `kill -9` instead.

Maybe it's escaping me but can't see any reason for us to be doing this.  It just serves to make processes hard to kill without any real benefit.  This is already causing us a rather large issue with our Jenkins infrastructure.

**Comment by mikem8361** [comment]
PR #1811 fixes this issue.
