### ISSUE TITLE
ReadOnlySpan.CopyTo is surprisingly (relatively) expensive and doesn't inline

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#18005]
Its mostly a wrapper on BufferMemmove with some checks
```
[FAILED: unprofitable inline] ReadOnlySpan`1:CopyTo(struct):this
```
![image](https://user-images.githubusercontent.com/1142958/40074205-f446ed1a-5870-11e8-8b2a-61b37db700c8.png)

First occurrence in `System.Private.CoreLib.dasm`
```asm
; Assembly listing for method ReadOnlySpan`1:CopyTo(struct):this
; Lcl frame size = 48
G_M47339_IG01:
       push     rdi
       push     rsi
       push     rbx
       sub      rsp, 48
       mov      qword ptr [rsp+28H], rdx
G_M47339_IG02:
       mov      eax, dword ptr [rcx+8]
       mov      r9d, eax
       mov      r10, qword ptr [rdx+48]
       mov      r10, qword ptr [r10]
       cmp      r9d, dword ptr [r8+8]
       ja       SHORT G_M47339_IG05
       mov      rsi, bword ptr [r8]
       mov      rcx, bword ptr [rcx]
       mov      rdi, rcx
       movsxd   rbx, eax
       mov      rcx, qword ptr [r10+64]
       test     rcx, rcx
       jne      SHORT G_M47339_IG03
       mov      rcx, rdx
       lea      rdx, [(reloc)]
       call     CORINFO_HELP_RUNTIMEHANDLE_CLASS
       mov      rcx, rax
G_M47339_IG03:
       mov      rdx, rsi
       mov      r8, rdi
       mov      r9, rbx
       call     Buffer:Memmove(byref,byref,long)
       nop      
G_M47339_IG04:
       add      rsp, 48
       pop      rbx
       pop      rsi
       pop      rdi
       ret      
G_M47339_IG05:
       call     ThrowHelper:ThrowArgumentException_DestinationTooShort()
       int3     
; Total bytes of code 99, prolog size 12 for method ReadOnlySpan`1:CopyTo(struct):this
```
Second occurrence in `System.Private.CoreLib.dasm`
```asm
; Assembly listing for method ReadOnlySpan`1:CopyTo(struct):this
; Lcl frame size = 40
G_M648_IG01:
       sub      rsp, 40
       nop      
G_M648_IG02:
       mov      r8d, dword ptr [rcx+8]
       mov      eax, r8d
       cmp      eax, dword ptr [rdx+8]
       ja       SHORT G_M648_IG04
       mov      rdx, bword ptr [rdx]
       mov      rax, rdx
       mov      rdx, bword ptr [rcx]
       movsxd   r8, r8d
       mov      rcx, rax
       shl      r8, 1
       call     Buffer:Memmove(struct,struct,long)
       nop      
G_M648_IG03:
       add      rsp, 40
       ret      
G_M648_IG04:
       call     ThrowHelper:ThrowArgumentException_DestinationTooShort()
       int3     
; Total bytes of code 52, prolog size 5 for method ReadOnlySpan`1:CopyTo(struct):this
```

**Comment by benaadams** [comment]
Could add a `if (typeof(T) == typeof(byte))` path and call the non-generic version? 

Might be the generic version has inlined into `CopyTo` and the non-generic version is the one that shows in the trace, with the generic adding to `CopyTo`? (As there is only one `Memmove` entry)

The Span type is `<byte>` in this instance.

**Comment by AndyAyersMS** [comment]
The inliner almost thinks inining `CopyTo` is worthwhile on its own. Perhaps I should revisit making it a bit more aggressive when there is a span typed argument or return value.
```
multiplier in methods of promotable struct increased to 3.
Inline candidate looks like a wrapper method.  Multiplier increased to 4.
Inline candidate callsite is boring.  Multiplier increased to 5.3.
calleeNativeSizeEstimate=813
callsiteNativeSizeEstimate=135
benefit multiplier=5.3
threshold=715
Native estimate for function size exceeds threshold for inlining 81.3 > 71.5 (multiplier = 5.3)
```

The runtime lookups are likely there for the case where we have `Span<ref-type>` and the `CopyTo`  is implicitly invoking the array constructor. We can't yet optimize away the array type checks in that constructor for ref type Ts, even when T is "known" because all this is getting inlined into a non-shared method (see #10258).

If the root method were itself generic the even the Span inlines would largely be blocked because of shared-shared restrictions.

I don't see any benefit to further type specialization here...

**Comment by mikedn** [comment]
> The runtime lookups are likely there for the case where we have Span<ref-type> and the CopyTo is implicitly invoking the array constructor. 

Hmm? It seems to me they're there because of the Memmove call.

**Comment by AndyAyersMS** [comment]
Ah -- I take it you're referring to the lookup in uninlined prejitted version, which is there for the `Span<ref-type>` instantiation. If we inline this method than that part goes away.

**Comment by benaadams** [comment]
> The runtime lookups are likely there for the case where we have Span<ref-type> and the CopyTo is implicitly invoking the array constructor...

There are quite a few struct wrapper hoops in the code I'm looking at that produces the example traces, however everything is a struct other than the byte array; so hopefully it shouldn't be blocked by shared generics.

If of interest, specifically the app is [PlatformBenchmarks](https://github.com/aspnet/KestrelHttpServer/tree/dev/benchmarkapps/PlatformBenchmarks) and the [lines that initiate the ReadOnlySpan.CopyTo are](https://github.com/aspnet/KestrelHttpServer/blob/8da5f55832acf0386682726925112ebd411db60c/benchmarkapps/PlatformBenchmarks/BenchmarkApplication.cs#L76-L96); in the `Plaintext` method; which can be activated by navigating to the url that running the app outputs plus the path `/plaintext` e.g. `http://localhost:8080/plaintext`

**Comment by AndyAyersMS** [comment]
Actually the runtime lookup is not quite the case I thought -- here we see the array construction and not just its declared type. But even in that case we are limited because arrays are one of the types where the jit only has approximate type handles at jit time, and even the object's method table does not describe its full type 

We construct the array like follows:
```asm
       48B960F6FAF9FE7F0000 mov      rcx, 0x7FFEF9FAF660
       E840FC825F           call     CORINFO_HELP_NEWARR_1_OBJ
```
and then type test it later via
```asm
       48B9D251FFF8FE7F0000 mov      rcx, 0x7FFEF8FF51D2
       E82385395F           call     CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPE
       483BE8               cmp      rbp, rax
```
So the two handles differ, and likewise the array instance method table may also be an approximate handle, so we can't test that versus the known handle either. Instead we have to call `GetType` on the array instance, which goes off and does magic.

Seems like there ought to be a way to connect the newarray helper arg with the exact type handle. I think the prototype changes in #10258 have some of the right bits.

Will have to investigate this further.

**Comment by jkotas** [comment]
> even the object's method table does not describe its full type

This is not true for arrays. It used to be true a long time ago, but it is not the case anymore.

**Comment by AndyAyersMS** [comment]
So is this bit of code in `canInlineTypeCheckWithObjectVTable` now out of date?

https://github.com/dotnet/coreclr/blob/f17770dd0318aa80fcd2a70288f097f2e05ba3bd/src/vm/jitinterface.cpp#L3769-L3773

**Comment by jkotas** [comment]
> There are quite a few struct wrapper hoops in the code I'm looking at

Just guessing: These force inlined wrappers tend to cause the IR size to explode. The JIT has hardcoded limits on the IR size after which stops inlining. You may be hitting one of these.

**Comment by jkotas** [comment]
> So is this bit of code in canInlineTypeCheckWithObjectVTable now out of date?

I think so.

**Comment by jkotas** [comment]
I think it may be possible for `canInlineTypeCheckWithObjectVTable` to just always return `true` in CoreCLR. I do not see a good reason why it would ever need to return false in CoreCLR.

**Comment by AndyAyersMS** [comment]
Some exploratory changes here to try and eliminate or streamline the type test: [master...AndyAyersMS:Fix18005](https://github.com/dotnet/coreclr/compare/master...AndyAyersMS:Fix18005).

Did not have much luck bypassing the `canInline` check; suspect we need to do something else in the type compare optimization to make it work, at least for arrays.

Also from running small diffs there was no impact -- seems likely there just aren't that many type tests on array types.
