### ISSUE TITLE
Avx.HorizontalAdd produces incorrect result sometimes

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#18017]
I have the following C++ code:
```
    float array[] = {8392608, 8394057, 8395506, 8396955, 8398404, 8399853, 8401302, 8402751};
    __m256 vec = _mm256_loadu_ps(array);
    __m256 add = _mm256_hadd_ps(vec, vec);
```
the result of `_mm256_hadd_ps` is:
```
16786664.0, 16792460.0, 16786664.0, 16792460.0, 16798256.0, 16804052.0, ...
```
but when I do it in C# using System.Runtime.Intrinsics.X86 I get different values:
```
16786660.0, 16792460.0, 16786660.0, 16792460.0, 16798260.0, 16804050.0, 16798260.0, 16804050.0
```

C# version:
```
    var array = new float[] {8392608, 8394057, 8395506, 8396955, 8398404, 8399853, 8401302, 8402751};
    fixed (float* ptr = &array[0])
    {
        var vec = Avx.LoadVector256(ptr);
        Vector256<float> add = Avx.HorizontalAdd(vec, vec);
    }
```
I am not an expert in SIMD so probably I am missing something?

System.Runtime.Intrinsics.Experimental: 4.5.0-rc1
dotnet --version: 2.1.300-preview2-008530

**Comment by EgorBo** [comment]
@mikedn 
I did it in Visual Studio so I could see the values during debug in both native and managed code
but let's assume I used
```
float firstValue ;
_MM_EXTRACT_FLOAT(firstValue, _mm256_extractf128_ps(add, 0), 0);
```

**Comment by gfoidl** [comment]
> it did not pass my tests for certain values

How do you test? 
Hopefully not with `==` for floats / doubles. Use `Math.Abs(actual - expected) < allowedTolerance`, due to the nature of the represenation of floats in the IEEE floating-point standard.

**Comment by tannergooding** [comment]
@gfoidl, this isn't one of the cases where that should matter. IEEE compliant floating-point arithmetic is deterministic, if nothing else.

If the resulting bits are not exactly matching, then there is a difference somewhere. Given the simplicity of the code, it could be one of:
* Conversion from int to float
* The instructions emitted
* The ToString function used to display the result

**Comment by mikedn** [comment]
Seems to work fine in VS debugger:
![image](https://user-images.githubusercontent.com/9973420/40123957-13e0159c-5930-11e8-9488-d7df63affab0.png)

**Comment by tannergooding** [comment]
Yeah, I also get the correct output on both Debug and Release mode:
```
16786664
16792460
16786664
16792460
16798256
16804052
16798256
16804052
```

**Comment by tannergooding** [comment]
@EgorBo, could you provide some more details about your hardware and the disassembly that is generated by your program?

**Comment by EgorBo** [comment]
@tannergooding sure, I'll attach a more detailed repro

**Comment by tannergooding** [comment]
In Release mode, I get:
```
00007FFE58F52421  vmovups     ymm0,ymmword ptr [rcx]  
00007FFE58F52426  vhaddps     ymm6,ymm0,ymm0 
```

In Debug mode, I get:
```
                var vec = Avx.LoadVector256(ptr);
00007FFE58F72472  mov         rcx,qword ptr [rbp+168h]  
00007FFE58F72479  vmovups     ymm0,ymmword ptr [rcx]  
00007FFE58F7247E  vmovupd     ymmword ptr [rbp+0C0h],ymm0  
00007FFE58F72487  vmovupd     ymm0,ymmword ptr [rbp+0C0h]  
00007FFE58F72490  vmovupd     ymmword ptr [rbp+140h],ymm0  
                Vector256<float> add = Avx.HorizontalAdd(vec, vec);
00007FFE58F72499  vmovupd     ymm0,ymmword ptr [rbp+140h]  
00007FFE58F724A2  vhaddps     ymm0,ymm0,ymmword ptr [rbp+140h]  
00007FFE58F724AB  vmovupd     ymmword ptr [rbp+0A0h],ymm0  
00007FFE58F724B4  vmovupd     ymm0,ymmword ptr [rbp+0A0h]  
00007FFE58F724BD  vmovupd     ymmword ptr [rbp+120h],ymm0 
```

**Comment by EgorBo** [comment]
Here is the repro: https://gist.github.com/EgorBo/f8c626faa7f4d2f95f7e2a97dbdbbc82
for me it starts to reproduce after `i = 11592` (67181440.00 != 67181430.00)

Intel Core i7 8700K 
Windows 10
Release x64
System.Runtime.Intrinsics.Experimental: 4.5.0-rc1 (from nuget)
2.1.300-preview2-008530

**Comment by EgorBo** [comment]
ah, it makes sense now, thank you! I think I can close it

**Comment by tannergooding** [comment]
For reference, an equivalent sum should look like:
```
public static float EquivalentSum(float[] array)
{
    const int vecSize = 8;

    var sum = new float[vecSize];
    for (int i = 0; i <= array.Length - vecSize; i += vecSize)
    {
        sum[0] += array[i + 0];
        sum[1] += array[i + 1];
        sum[2] += array[i + 2];
        sum[3] += array[i + 3];
        sum[4] += array[i + 4];
        sum[5] += array[i + 5];
        sum[6] += array[i + 6];
        sum[7] += array[i + 7];
    }

    var t1 = new float[vecSize];
    {
        t1[0] = sum[0] + sum[1];
        t1[1] = sum[2] + sum[3];
        t1[2] = sum[0] + sum[1];
        t1[3] = sum[2] + sum[3];
        t1[4] = sum[4] + sum[5];
        t1[5] = sum[6] + sum[7];
        t1[6] = sum[4] + sum[5];
        t1[7] = sum[6] + sum[7];
    }
    var t2 = new float[vecSize];
    {
        t2[0] = t1[0] + t1[1];
        t2[1] = t1[2] + t1[3];
        t2[2] = t1[0] + t1[1];
        t2[3] = t1[2] + t1[3];
        t2[4] = t1[4] + t1[5];
        t2[5] = t1[6] + t1[7];
        t2[6] = t1[4] + t1[5];
        t2[7] = t1[6] + t1[7];
    }
    var t3 = new float[vecSize / 2];
    {
        t3[0] = t2[4];
        t3[1] = t2[5];
        t3[2] = t2[6];
        t3[3] = t2[7];
    }
    var t4 = new float[vecSize / 2];
    {
        t4[0] = t2[0] + t3[0];
        t4[1] = t2[1] + t3[1];
        t4[2] = t2[2] + t3[2];
        t4[3] = t2[3] + t3[3];
    }
    return t4[0];
}
```

**Comment by EgorBo** [comment]
Well, at least it works for doubles for the given range.
Sorry for the trouble and thank you for the equivalent

**Comment by tannergooding** [comment]
> Well, at least it works for doubles for the given range.

Right. `double` has an approx. range of `15-17` significant digits while `float` only has an approx. range of `6-9` significant digits. So you should get much more accurate results, even when operations are re-ordered, with `double` (but at the cost of slower computation).
