### ISSUE TITLE
Socket exception when running .NET app from shared drive.

### ISSUE THREAD

**Issue by gevorgter** [dotnet/coreclr#18020]
Recent (May 14, 2018)  Windows update has resurfaced the problem when .NET app, that is started from shared drive, can not do any network operation. Error says "invalid argument was supplied" when trying to use WebClient or web services. 

Not sure how to work around it since all articles are from 2012 and they do not apply anymore.

**Comment by karelz** [comment]
Is it problem on .NET Framework? Which version?
Do you have a minimal repro?

**Comment by gevorgter** [comment]
Hello, here is the minimal repro.
Works fine when run on a C drive. Once moved to mapped drive on a network i get 
"An exception occurred during WebClient request....Error creating the WebProxy specified in the system.net/defaultProxy' configuration section..... An invalid argument was supplied".

In order to reproduce problem you must have the most recent update from Microsoft.
The project was compiled with .NET 4.6 in Visual Studio 2017. And i have Windows 10 Home with latest update

I do not have any proxy set up and it worked for years.
my guess it has something to do with .NET trying to figure out my default Proxy settings and not having enough permissions. 

Let me know if you need more clarifications, thanks for looking into it.

```
[STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            try
            {
                using (WebClient cl = new WebClient())
                    cl.DownloadFile("https://www.google.com", "c:\\tmp\\aa.htm");
                MessageBox.Show("Success");
            }
            catch (Exception e)
            {
                MessageBox.Show(e.ToString());
            }
        }
```

**Comment by karelz** [comment]
Did you check your app and machine configs? Is the value in "system.net/defaultProxy" valid or invalid? What if you remove it from the configs?
Are you able to reproduce it on clean OS install with your HelloWorld style app above? (e.g. on a new VM)

**Comment by gevorgter** [comment]
App.config is clean for this Repro except line with "....supportedRuntime version="v4.0"...."

I have checked machine.config for Proxy settings. All clean. I do not have clean install of windows (do not have VM) but every single machine out of 6 in my little office started to have a problem once i updated it with latest windows update . So i can rule out my laptop having problem.  Also those machines in the office (except my laptop) almost clean (minimal software installed on them, Google chrome, Microsoft office and that is it, no development tools, games or anything like that. They are only used to do work through browse, and do shipping with this custom shipping software i wrote that used to sit on mapped drive). 

We have a small network (no domain or anything like that). Just old computer acting as a shared drive and all computers belonging to same Workgroup.

**Comment by karelz** [comment]
I cannot reproduce the problem. Here are my steps, can you please try them?
1. Create Console App (.NET Framework), targetting .NET Framework 4.6.
```c#
class Program
{
    static void Main()
    {
        using (var cl = new System.Net.WebClient())
            cl.DownloadFile("https://www.google.com", "D:\\Temp\\out.htm");
    }
}
```
2. Copy it to a share on another machine
3. Run the EXE from the share (Debug build)
**Result (as expected):** File `D:\Temp\out.htm` is created.

.NET Framework version:
```
filever -v c:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
FileVersion     4.7.2650.0 built by: NET471REL1LAST_B
```

**Comment by gevorgter** [comment]
I did. It does not work. Same exception.
Do you mind running "winver" in command line.  Updated computer says Version 1803. 
Just want to make sure you have an updated windows. A bit latter i will do the test at home (I have a desktop computer) to see if can reproduce the problem there (Totally different environment from the office). 

thanks.

**Comment by karelz** [comment]
I have older winver (1709). Can you run the filver above? That usually corresponds to specific .NET version.
@AlexGhiondea where to move potential .NET Framework breaking change bugs?

**Comment by gevorgter** [comment]
1. Sorry, i do not have filever on my computer and the only download i found is XP SP2 support tool which would not install due to my windows being win 10. If you know where i can get filever i would download it and let you know the info.

2. 1709 version is pre-update version. You must install latest update from Microsoft to reproduce problem. Without it everything worked fine (program run from shared drive without problem) until i installed recent update. Basically as soon as i updated computers one by one, they one by one started giving me error for .NET app that is on shared drive.

**Comment by karelz** [comment]
Why doesn't the XP SP2 tools pack install on Win10? Did you try XP compat mode?

**Comment by gevorgter** [comment]
XP compat worked (did not think of that). Without it setup gave me an error "it can only be installed on Windows XP. So result is
filever -v c:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
--a-- W32i   DLL ENU      4.7.3101.0 shp  7,247,992 05-15-2018 clr.dll

**Comment by AlexGhiondea** [comment]
For .NET Framework breaking changes you can file an issue here: https://github.com/microsoft/dotnet/issues

**Comment by karelz** [comment]
@gevorgter can you please check the same output line I did? See https://github.com/dotnet/coreclr/issues/18020#issuecomment-390351510

**Comment by karelz** [comment]
This issue was moved to Microsoft/dotnet#755
