### ISSUE TITLE
Possible Bug: Complete lock-up in ASP.NET Core startup due to StubHelpers?

### ISSUE THREAD

**Issue by rossdempster** [dotnet/coreclr#18030]
Hi all,

This is potentially a difficult issue to track down. I have been developing with ASP.NET Core for a few months now and (very) rarely the application locks-up completely during start up. I am currently running version 2.1.101 but don't recall which version I was running when I first encountered this issue. The time between manifestations is measured in weeks. I assume this is some kind of unlucky race condition.

I captured this screenshot from the latest occurrence. The lock-up always occurs within WebHostBuilder.Build(). The rest of the stack trace might be variable because this is the first time I've had a proper look at it.

In this instance, the code appears to be stuck in StubHelpers.AddToCleanupList (hence why I am posting this here). Resuming the application has no effect. We remain stuck in the same place. I need to restart the application to get past this point. 

![image](https://user-images.githubusercontent.com/16805881/40167385-cecbed26-59b8-11e8-8b6c-e57aef1681ac.png)

**Comment by janvorli** [comment]
@rossdempster are you sure that in the case you've posted here the stack trace wasn't changing when you resumed the execution and then interrupted it again?

**Comment by tommcdon** [comment]
@cshung can this issue be resolved?

**Comment by tommcdon** [comment]
@cshung investigated and was not able to repro.  Please provide a dump of the process when it is hung and we can investigate further.  Closing the issue due to lack of actionable information for now.
