### ISSUE TITLE
JIT: assert in test with call to Array<T>.IndexOf with Vector type

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#18043]
```C#
using System;
using System.Numerics;
using System.Collections.Generic;

class X
{
    public static int Main()
    {
        Vector<float> f = new Vector<float>();
        Vector<float>[] a = new Vector<float>[10];
        return Array.IndexOf(a, f);
    }
}
```
If you compile and run with CHECKED jit you hit the following assert:
```
Assert failure(PID 24440 [0x00005f78], Thread: 7436 [0x1d0c]): 
Assertion failed '!IsDummyUse()' in 
'System.Collections.Generic.GenericEqualityComparer`1[Vector`1]
 [System.Numerics.Vector`1[System.Single]]:IndexOf(ref,struct,int,int):int:this' (IL size 96)

File: d:\repos\coreclr\src\jit\lir.cpp Line: 110
```

**Comment by AndyAyersMS** [comment]
This may have something to do with the importer box optimizations -- we have a boxed Vector<T> where the object to box is an array lookup -- all feeding a null check, and the jit optimizes away the check. But the tree to initialize the box payload has side effects, and so part of it must be retained.

The exception minifier treats this as a non-struct case and so we end up with an unconsumed GT_OBJ:
```
               [000051] ------------              *  STMT      void  (IL   ???...  ???)
               [000040] ---XG-------              \--*  OBJ(32)   simd32
               [000039] ---XG-------                 \--*  ADDR      byref 
               [000037] ------------                    |  /--*  LCL_VAR   int    V07 loc2         
               [000038] ---XG-------                    \--*  INDEX     struct
               [000036] ------------                       \--*  LCL_VAR   ref    V01 arg1         
```
Which seems to lead to the assert later in rationalize.

Probably need to handle SIMD types like they were structs here.

**Comment by 4creators** [comment]
IMO it hits general problem of correctly abstracting `Vector<T>` which on one hand should be treated as special register for register operations and when it is in memory as a `struct`. 

@tannergooding Is the Vector ABI implementation handling such cases correctly?

**Comment by tannergooding** [comment]
`System.Numerics.Vector<T>` is handled completely separately from `System.Runtime.Intrinsics.Vector128<T>`, `S.R.I.Vector64<T>`, and `S.R.I.Vector256<T>`.

The only special ABI handling the latter have, right now, is that they are appropriately packed when they are a member of a struct.

I agree, however, that ultimately they should be handled as structs anywhere that they are not specially handled as their respective primitive type.
