### ISSUE TITLE
[Arm64] jitStressRegs=3 failures

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#18052]
The following tests fail with jitStressRegs=3 when run on x64/windows, using the arm64 altjit:

CoreMangLib\cti\system\mathf\MathFSign\MathFSign.cmd
JIT\Generics\Locals\static_assignment_class01\static_assignment_class01.cmd
JIT\Generics\Constraints\convert_static01\convert_static01.cmd
JIT\IL_Conformance\Old\Conformance_Base\add_ovf_u2\add_ovf_u2.cmd
JIT\jit64\opt\regress\vswhidbey\481244\foo_opt\foo_opt.cmd

Note that this test leg was last run in the CI system on 16 Feb.

**Comment by sdmaclea** [comment]
Looks like the failures are issues while running the code.  So these are not arm64 issues, but rather x64 issues while running x64_altjit.  Perhaps related to the config options in test/x64_arm64_altjit.cmd ? 

@BruceForstall

**Comment by CarolEidt** [comment]
I have just realized that I failed to run these with `COMPlus_SIMD16ByteOnly`. Now none of them are failing either in master or in my branch. Let me rebase and see if I can reproduce the failures that are showing up in PR #16517

**Comment by sdmaclea** [comment]
@CarolEidt   COMPlus_SIMD16ByteOnly should be on by default in altjit arm64 jobs

**Comment by CarolEidt** [comment]
> COMPlus_SIMD16ByteOnly should be on by default in altjit arm64 jobs

Right, but when I ran the tests in my local copy of my branch and master, I forgot - and naturally the jobs failed in both.

**Comment by CarolEidt** [comment]
They were apparently spurious failures. Closing this.
