### ISSUE TITLE
Support byte-code-Injection in coreclr?

### ISSUE THREAD

**Issue by DevWithLin** [dotnet/coreclr#18094]
Is coreclr similar to java instrument(byte-code manipulation)? 

The Instrumentation API offers a hook into the JVM runtime which allows Java agents to access more advanced features of the JVM.

so ,Is coreclr like that?

**Comment by mattwarren** [comment]
> Is coreclr similar to java instrument(byte-code manipulation)?

It's similar, but not quite the same, for instance AFAIK in Java you can do the byte-code manipulation using Java code, but in .NET you have to use C/C++.

You can find some more information in the [Profiling doc](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/profiling.md) and a [Profiling API Sample for CoreCLR](https://github.com/Microsoft/clr-samples/tree/master/ProfilingAPI/) is available.

**Comment by DevWithLin** [comment]
thank you for your answer.
