### ISSUE TITLE
Calling an VB.Net String-functions (like Left(string),Right(string),Space(string),Trim(string)) in a .NET Core project throwing Runtime exceptions

### ISSUE THREAD

**Issue by amshekar** [dotnet/coreclr#18095]
Calling an VB.Net String-functions (like Left(string),Right(string),Space(string),Trim(string)) in a .NET Core project throwing Runtime exceptions
General
We have a .Net core 2.0 webapi project and want to call a old vb.net method. The method have some string functions like Left,right,space and trim . We added the DLL as a reference . But in runtime we are getting method not found exception.

like

> Method not found: 'System.String Microsoft.VisualBasic.Strings.Left(System.String)'.'
> Method not found: 'System.String Microsoft.VisualBasic.Strings.Space(System.String)'.'
> Method not found: 'System.String Microsoft.VisualBasic.Strings.Right(System.String)'.'
> 

Any help\advice is most appreciated .
We might not changes the old custom dll code which have dependencies with other systems.
If we want to do the modification in old dll if possible what would be the better approach with minimum impact

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#29873
