### ISSUE TITLE
Clarify style guidance for c++ code

### ISSUE THREAD

**Issue by zgxnet** [dotnet/coreclr#181]
It seems that there are quite a lot of naming conventions in C++ code. E.g. getClassModule, SetCodeHeader, heap_segment_reserved. Why not use a single naming style?

**Comment by MattWhilden** [comment]
@zgxnet, the codebase is very old and guidelines were not strictly enforced over that period. In general our guideline is, "Keep it consistent within a file."

However, that doesn't mean "do whatever you want". I'm sure if a new file was started with a completely wacky set of standards then we'd ask for it to conform a bit better to other things in the code base.

It may be worthwhile to clarify this in out contributor guide which has plenty to say about C# but not much about C++.

@richlander, who should we bother about getting the right guidance written down?

**Comment by MattWhilden** [comment]
@zgxnet I've updated the page at https://github.com/dotnet/corefx/wiki/Coding-style.

**Comment by linquize** [comment]
But it is for C# only, not for C++

**Comment by MattWhilden** [comment]
My intent was to have my above guidance for C++ fall into the "General Guidance" I've clarified that a bit better now. 

Thoughts?

**Comment by MattWhilden** [comment]
Closing for now. Let me know if there's something you'd like modified.
