### ISSUE TITLE
comctl32.dll AccessViolationException - Windows 10 - WindowsForms ComboBox

### ISSUE THREAD

**Issue by FarrynDE** [dotnet/coreclr#18110]
I have a Windows Forms application that experiences intermittent crashes when run on Windows 10 operating system. The crashes stop when I run the app in compatibility mode for Windows 7.

The errors appear to be coming from the ComboBox control. Is this a known issue or are there any code work-arounds?

# **Application Error**
Name der fehlerhaften Anwendung: MesEfficiencyGUI.exe, Version: 18.1.0.331, Zeitstempel: 0x5ab0a6bb
Name des fehlerhaften Moduls: comctl32.dll, Version: 6.10.16299.309, Zeitstempel: 0xac6b2343
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000000dbf4f
ID des fehlerhaften Prozesses: 0x3d54
Startzeit der fehlerhaften Anwendung: 0x01d3f31d125b7619
Pfad der fehlerhaften Anwendung: MesEfficiencyGUI.exe
Pfad des fehlerhaften Moduls: C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.16299.309_none_15cfd4c4935e6b11\comctl32.dll
Berichtskennung: 8bebb71b-da35-444c-91fb-9f786b32b457
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

**# .NET Runtime**
Anwendung: MesEfficiencyGUI.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.AccessViolationException
   bei System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   bei System.Windows.Forms.NativeWindow.DefWndProc(System.Windows.Forms.Message ByRef)
   bei System.Windows.Forms.Control.WmMouseDown(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   bei System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   bei System.Windows.Forms.ComboBox.WndProc(System.Windows.Forms.Message ByRef)
   bei de.draexlmaier.common.ui.SizeableComboBox.WndProc(System.Windows.Forms.Message ByRef)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   bei System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   bei System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   bei System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   bei System.Windows.Forms.Form.ShowDialog(System.Windows.Forms.IWin32Window)
   bei de.draexlmaier.pcm.mes.efficiency.gui.DynamicData.EFFProductionGroupAdminForm.ToolStripButtonLendPersonnel_Click(System.Object, System.EventArgs)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(System.Object, System.EventArgs)
   bei System.Windows.Forms.ToolStripButton.OnClick(System.EventArgs)
   bei System.Windows.Forms.ToolStripItem.HandleClick(System.EventArgs)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(System.Windows.Forms.MouseEventArgs)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(System.Windows.Forms.MouseEventArgs)
   bei System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32)
   bei System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   bei System.Windows.Forms.ToolStrip.WndProc(System.Windows.Forms.Message ByRef)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   bei System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   bei System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   bei System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   bei de.draexlmaier.pcm.mes.efficiency.gui.Program.Main(System.String[])

**Comment by FarrynDE** [comment]
https://stackoverflow.com/questions/43518980/windows-10-creators-update-net-4-7-system-accessviolationexception-issue
It seems that the problem leads to the JIT compiler

**Comment by RussKeldorph** [comment]
There doesn't seem to be evidence that the linked issue is related.  The right channels to report .NET Framework issues are VS Developer Community Portal or Product Support (links are at https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback).

Before we can investigate, we need more information, such as a set of instructions to reproduce the failure.  If you have instructions to reproduce this failure on .NET Core, feel free to re-open this issue.  Otherwise, please use the instructions above to report the issue against the .NET Framework, but note that more information on the repro will still be needed.
