### ISSUE TITLE
CoreCLR failed when build in conformance mode (/permissive-)  

### ISSUE THREAD

**Issue by PhoebeHui** [dotnet/coreclr#18123]
I build CoreCLR with Visual studio 15.7.1 in conformance mode (/permissive-) on Windows, it failed with error C4596, The changes involved by
https://github.com/dotnet/coreclr/commit/b39a5b2cfad4620ae23cda84186a36ffb463cd5a#diff-7844842ffbae44d891b5170d2a229d4bR1590

Could you help remove the redundant "LinearScan::" on BuildRMWUses. The compiler complains about this in conformance mode (/permissive-)

Failures:
d:\coreclr\src\src\jit\lsra.h(1590): error C4596: 'BuildRMWUses': illegal qualified name in member declaration

**Comment by kant2002** [comment]
@jkotas this should be already fixed by https://github.com/dotnet/coreclr/pull/18272
