### ISSUE TITLE
IContainable(Of T) Interface.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/coreclr#18146]
# `IContainable(Of T)`
This is a simple interface that decouple the concept of containablity from collections / sequences and read / write access.
```vbnet
Interface IContainable(Of T)
  Function Contains( value As T ) As Boolean
End Interface
```

**Comment by svick** [comment]
Requests for adding new APIs [should be opened in the corefx repo](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/IssuesFeedbackEngagement.md). And ideally, they should follow the [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).

**Comment by jkotas** [comment]
@AdamSpeight2008 Could you please open this issue in corefx repo instead with the right format?
