### ISSUE TITLE
Question: How do I diagnose an IPE?

### ISSUE THREAD

**Issue by borgdylan** [dotnet/coreclr#18148]
I am running code on .NET Core that is ported over from mono. The same compiler was used in both instances. Mono runs the IL fine but .NET Core is complaining about invalid IL in a particular method. Is there a debug flag that will make .NET Core spit out the exact instruction that it finds invalid? As the author of said compiler, I could fix the bug pointed out by the CLR if I had the instruction pointed out.

**Comment by jkotas** [comment]
Try using `COMPlus_JitDump` and these instructions  https://github.com/dotnet/coreclr/blob/master/Documentation/building/viewing-jit-dumps.md
