### ISSUE TITLE
Linq Aggregate Extensions for TimeSpan and <T>

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/coreclr#18152]
Hi All,
It would be great if there was an overload of Sum<> which could accept a TimeSpan.  Also, it would be nice if there was was another overload that let you specify an initial value and an aggregator.

var Custom = (from x in items select x).Sum(initial => default(T), (Total, Element)=> Total + Element);

**Comment by svick** [comment]
Requests for adding new APIs [should be opened in the corefx repo](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/IssuesFeedbackEngagement.md). And ideally, they should follow the [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).

**Comment by jkotas** [comment]
@TonyValenti Could you please open this issue in corefx repo with the right format instead?
