### ISSUE TITLE
Missing API 'IntPtr AsIntPtr<T>(ref T value)' in 'System.Runtime.CompilerServices.Unsafe'

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/coreclr#18150]
The **System.Runtime.CompilerServices.Unsafe** API seems to be missing the following:

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	public static IntPtr AsIntPtr<T>(ref T value) => (IntPtr)Unsafe.AsPointer(ref value);

The IL would be the same as the other `As...` functions:

    L_0000: ldarg.0
    L_0001: conv.u
    L_0002: ret

The objective is to displace the cast (from `void*` to `IntPtr`) out of end-user code scenarios which *otherwise wouldn't need to be marked as* `unsafe`. 

To restate, the use-case here is within certain "non-unsafe" (i.e. "safe?") C# methods which--if it weren't for calling to the existing `System.Runtime.CompilerServices.Unsafe.AsPointer(...)` method--would otherwise ***not*** need to be marked with the `unsafe` keyword. For example, transitonary code which needs to extract or expose the `IntPtr` and pass it down to other APIs, yet without itself ever needing to invoke `IntPtr.ToPointer()`.

This addition to the `Unsafe` library would allow such methods to obtain the `IntPtr` and still retain their "non-unsafe" status.

Although the C# shim shown above can (obviously) can be used to mitigate this omission, for completeness it would be nice to organize this function with its related kin by including it in `System.Runtime.CompilerServices.Unsafe`.

**Comment by jkotas** [comment]
The fact that you can use `System.Runtime.CompilerServices.Unsafe` methods without unsafe context in C# is a deficiency, not a feature. We do not want to be making calling unsafe methods without unsafe contexts easier. Ideally, C# compiler would require `unsafe` context for calling all methods on `System.Runtime.CompilerServices.Unsafe`. https://github.com/dotnet/roslyn-analyzers/issues/972 and related issues have discussion about this.

We exclusively use proper unmanaged pointers (like `void*`), and not `IntPtr`, for unmanaged pointers in signatures of new APIs. The API design was not consistent in the early days of .NET and there are old APIs that use IntPtr for unmanaged pointer.

**Comment by glenn-slayden** [comment]
Understood and thanks for the informative reply.

So looking at the existing `System.Runtime.CompilerServices.Unsafe` API surface then, it appears that `IntPtr` is still the proper--and only?--sanctioned expression of (unmanaged) pointer *differences* (offsets)?

**Comment by jkotas** [comment]
Right. https://github.com/dotnet/corefx/issues/12593 has the discussion about the `Unsafe.ByteOffset` design.
