### ISSUE TITLE
Assertion failed 'farthestRefPhysRegRecord != nullptr' /dotnet/coreclr/src/jit/lsra.cpp:3637 

### ISSUE THREAD

**Issue by iarischenko** [dotnet/coreclr#18153]
I'm using the x86 version of the CoreCLR to run CoreRT and compile tests for ARM.

After the commit:
> b39a5b2cfad4620ae23cda84186a36ffb463cd5a 

compilation fails (for all tests) with message

> cd /overlay.arm.Debug && ./corerun ilc.dll --codegenopt "AltJitNgen=*" @/overlay.arm.Debug/pow3/base.ilc.rsp
/dotnet/coreclr/src/jit/lsra.cpp:3637
Assertion failed 'farthestRefPhysRegRecord != nullptr' in 'Sys:DoubleToString(double,int,int,int):int' (IL size 14)

The folder /overlay.arm.Debug/ contains necessary parts from CoreRT, CoreCLR and CoreFX to 
cross-compile IL binary to native ARM code.  I've followed the following guide: [https://github.com/dotnet/corert/blob/master/Documentation/cross-building.md](url)
The `@/overlay.arm.Debug/pow3/base.ilc.rsp` is dependency file, generated by the `msbuild`. 
The pow3 test is one of the CoreCRL's tests for CoreRT. The tests are downloaded by `/dotnet/corert/tests/runtest.sh`  script and could be run by the following command `./tests/runtest.sh -coreclr all`

I've checked with the following versions of the CoreCRL, CoreRT and CoreFX:

CoreCLR: 6bf04a47badd74646e21e70f4e9267c71b7bfd08
CoreFX: ccdb5a48a49d3e932aa00d02749777464f4c8d5b
CoreRT: a028615abe80057e413d632a7c9257208b7c6865

**Comment by alpencolt** [comment]
cc @dotnet/arm32-contrib 
cc @CarolEidt

**Comment by CarolEidt** [comment]
It is quite unlikely that this is the same bug as #18228. @iarischenko - can you clarify whether you are compiling for arm or armel? The instructions you reference seem to imply armel, but I want to make sure.

**Comment by CarolEidt** [comment]
I'm attempting to build using the instructions here: https://github.com/dotnet/corert/blob/master/Documentation/cross-building.md but for arm instead of armel. I'm getting the following error from `./build.sh arm debug verbose clean cross`:
```
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'jitinterface' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libjitinterface: cannot open shared object file: No such file or directory
     at Internal.JitInterface.CorInfoImpl.GetJitHost(IntPtr configProvider)
     at Internal.JitInterface.CorInfoImpl..ctor(Compilation compilation, JitConfigProvider jitConfig) in /git/corert/src/JitInterface/src/CorInfoImpl.cs:line 113
     at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper) in /git/corert/src/ILCompiler.Compiler/src/Compiler/RyuJitCompilation.cs:line 37
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper) in /git/corert/src/ILCompiler.Compiler/src/Compiler/Compilation.cs:line 329
     at ILCompiler.Program.Run(String[] args) in /git/corert/src/ILCompiler/src/Program.cs:line 493
     at ILCompiler.Program.Main(String[] args) in /git/corert/src/ILCompiler/src/Program.cs:line 649
  Aborted (core dumped)
/git/corert/bin/Linux.arm.Debug/build/Microsoft.NETCore.Native.targets(183,5): error MSB3073: The command ""/git/corert/tests/../bin/Linux.arm.Debug/tools/ilc" @"/git/corert/tests/src/Simple/Threading/obj/Debug/arm/native/Threading.ilc.rsp"" exited with code 134. [/git/corert/tests/src/Simple/Threading/Threading.csproj]
```

**Comment by CarolEidt** [comment]
@dotnet/corert-contrib - can someone suggest where I might be going wrong? I've been successfully building coreclr and corefx using docker; might that be possible for corert as well?

**Comment by BredPet** [comment]
@CarolEidt it's "normal" )) CoreRT isn't working as itself, just follow instruction cross-building.md

**Comment by CarolEidt** [comment]
In this step of the instructions (part of "Step 2"):
./build-native.sh -debug -buildArch=x86 -- verbose cross

This results in a usage error. It is apparently the "cross" parameter that is no longer supported, but I can't determine what the replacement option would be, and the command above is also what is shown in the corefx cross building instructions: https://github.com/dotnet/corefx/blob/master/Documentation/building/cross-building.md

If I leave it off, I get a failure when it tries to chmod `/git/corefx/bin/testhost/netcoreapp-Linux-Debug-x86/dotnet`. Any idea how that's supposed to be set?

cc @dotnet/corefx-contrib

**Comment by BredPet** [comment]
I used this https://github.com/dotnet/corert/blob/master/Documentation/cross-building.md instruction with the latest corefx, it's working. The issue is still exists.
```
coreclr/src/jit/lsra.cpp:3622
Assertion failed 'farthestRefPhysRegRecord != nullptr' in 'Sys:DoubleToString(double,int,int,int):int' (IL size 14)
```

**Comment by CarolEidt** [comment]
I ran into repeated issues in attempting to build arm.
I got farther in attempting to build armel, but now the corert build step "./build.sh armel debug verbose cross" immediately fails with:
```

Setting up directories for build
Checking pre-requisites...
Commencing build of corert native components for Linux.armel.Debug
/git/corert/bin/obj/Native/Linux.armel.Debug /git/corert
Invoking cmake with arguments: "/git/corert/buildscripts/.." Debug
loading initial cache file /git/corert/buildscripts/../cross/tryrun.cmake
Re-run cmake no build system arguments
-- The C compiler identification is Clang 3.9.1
-- The CXX compiler identification is Clang 3.9.1
-- Check for working C compiler: /usr/bin/clang-3.9
-- Check for working C compiler: /usr/bin/clang-3.9 -- broken
CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/clang-3.9" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /git/corert/bin/obj/Native/Linux.armel.Debug/CMakeFiles/CMakeTmp



  Run Build Command:"/usr/bin/make" "cmTC_028ba/fast"

  /usr/bin/make -f CMakeFiles/cmTC_028ba.dir/build.make
  CMakeFiles/cmTC_028ba.dir/build

  make[1]: Entering directory
  '/git/corert/bin/obj/Native/Linux.armel.Debug/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_028ba.dir/testCCompiler.c.o

  /usr/bin/clang-3.9 --target=arm-linux-gnueabi -isystem
  /git/corert/buildscripts/../cross/rootfs/armel/usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1/include/c++
  -isystem
  /git/corert/buildscripts/../cross/rootfs/armel/usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1/include/c++/armv7l-tizen-linux-gnueabi
  --sysroot=/git/corert/buildscripts/../cross/rootfs/armel
  --target=arm-linux-gnueabi
  --gcc-toolchain=/git/corert/buildscripts/../cross/rootfs/armel/usr -mthumb
  -mfpu=vfpv3 -mfloat-abi=softfp -Wno-deprecated-declarations
  -D__extern_always_inline=inline -o
  CMakeFiles/cmTC_028ba.dir/testCCompiler.c.o -c
  /git/corert/bin/obj/Native/Linux.armel.Debug/CMakeFiles/CMakeTmp/testCCompiler.c


  Linking C executable cmTC_028ba

  /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_028ba.dir/link.txt
  --verbose=1

  /usr/bin/clang-3.9 --target=arm-linux-gnueabi
  --sysroot=/git/corert/buildscripts/../cross/rootfs/armel
  --gcc-toolchain=/git/corert/buildscripts/../cross/rootfs/armel/usr
  --target=arm-linux-gnueabi -fuse-ld=gold
  -B/git/corert/buildscripts/../cross/rootfs/armel/usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1
  -L/git/corert/buildscripts/../cross/rootfs/armel/lib
  -L/git/corert/buildscripts/../cross/rootfs/armel/usr/lib
  -L/git/corert/buildscripts/../cross/rootfs/armel/usr/lib/gcc/armv7l-tizen-linux-gnueabi/6.2.1
  CMakeFiles/cmTC_028ba.dir/testCCompiler.c.o -o cmTC_028ba -rdynamic

  /usr/bin/ld.gold: fatal error:
  /git/corert/buildscripts/../cross/rootfs/armel/usr/lib/../lib/crt1.o:
  unsupported ELF machine number 40

  clang: error: linker command failed with exit code 1 (use -v to see
  invocation)

  CMakeFiles/cmTC_028ba.dir/build.make:97: recipe for target 'cmTC_028ba'
  failed

  make[1]: *** [cmTC_028ba] Error 1

  make[1]: Leaving directory
  '/git/corert/bin/obj/Native/Linux.armel.Debug/CMakeFiles/CMakeTmp'

  Makefile:126: recipe for target 'cmTC_028ba/fast' failed

  make: *** [cmTC_028ba/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)
```
Any suggestions?
cc @dotnet/corert-contrib

**Comment by BredPet** [comment]
@CarolEidt It seems uninitialized armel rootfs.
Just init rootfs: sudo cross/build-rootfs.sh armel tizen before building

**Comment by CarolEidt** [comment]
I still can't get this to build. I followed the above instructions, still without success.
I am unable to make any progress on this bug without being able to build corert.

**Comment by jkotas** [comment]
@iarischenko @BredPet Could you please find the method it is asserting in, and extract it into a small standalone repro?

**Comment by BredPet** [comment]
@CarolEidt It's strange, errors?

@jkotas 
> ... extract it into a small standalone repro?

I don't really understand, what this means?
In CoreRT compile time: method Sys:DoubleToString(double,int,int,int):int
In CoreCLR asserts in lsra.cpp:
`regNumber LinearScan::allocateBusyReg(Interval* current, RefPosition* refPosition, bool allocateIfProfitable)`

**Comment by jkotas** [comment]
Ah ok - could you please pass `--codegenopt NGenDump=DoubleToString` switch to the ilc and share the dump that it produces? We should be able to produce a small repro based on that - bugs like this often repro on CoreCLR as well.

**Comment by CarolEidt** [comment]
The problem is in the handling of the unmanaged call to `Sys.DoubleToString. When the register allocator generates uses for the double argument (that's passed in two integer registers) at the call site, it assigns them both to r0, instead of r0 and r1, causing it to fail to allocate a register in the second case.
I'm going to see if I can create a coreclr repro, to make this easier to validate.

**Comment by CarolEidt** [comment]
@iarischenko - I believe I've fixed the bug with #18891. I was able to reproduce the root cause on coreclr, but not able to reproduce the assert. I've now added additional asserts to hopefully catch such cases in future. Could you verify that this issue is fixed with the latest coreclr?

**Comment by iarischenko** [comment]
@CarolEidt - I've checked with d25bcb8e27c5e583d6abfe6d59d3f32316ac7733 revision, It works with out any issues.

**Comment by CarolEidt** [comment]
@iarischenko - excellent! thanks for confirming.
