### ISSUE TITLE
NgenR2R emits many non-actionable warnings

### ISSUE THREAD

**Issue by rido-min** [dotnet/coreclr#18165]
moved from [Microsoft/dotnet/issues/757](https://github.com/Microsoft/dotnet/issues/757)

For example (some of the warnings were already removed from coreclr):

- ReadyToRun: JIT helper not supported: CORINFO_HELP_MON_ENTER (dotnet/coreclr#12153)
- Implicit boxing for calls to constrained methods not supported (https://github.com/dotnet/coreclr/pull/12274/files)
- Method not found: 'System.Drawing.Image System.Windows.Forms.ContainerControl.get_BackgroundImage()'. while resolving 0xa000022 - System.Windows.Forms.ContainerControl.get_BackgroundImage.
The output should be modified so that expected warnings do not show up as warnings in Visual Studio.

**Comment by jkotas** [comment]
NgenR2R is .NET Framework specific tool. CoreCLR repo is not for tracing .NET Framework specific issues.
