### ISSUE TITLE
NgenR2R output doesn't get included during incremental build 

### ISSUE THREAD

**Issue by rido-min** [dotnet/coreclr#18168]
moved from [Microsoft/dotnet/issues/760](https://github.com/Microsoft/dotnet/issues/760)

When creating and AppX package, the dlls included in the package are not R2R'd if the package is produced during an incremental build.
See RssBandit/RssBandit#1747.

**Comment by jkotas** [comment]
NgenR2R is .NET Framework specific tool. CoreCLR repo is not for tracing .NET Framework specific issues.
