### ISSUE TITLE
NgenR2R doesn't play nicely with Fody

### ISSUE THREAD

**Issue by rido-min** [dotnet/coreclr#18169]
moved from [Microsoft/dotnet/issues/761](https://github.com/Microsoft/dotnet/issues/761)

When using NgenR2R together with Fody, Fody runs after NgenR2R. The inputs to Fody are the dlls with native code, and Fody isn't able to process mixed-mode binaries.

**Comment by jkotas** [comment]
NgenR2R is .NET Framework specific tool. CoreCLR repo is not for tracing .NET Framework specific issues.
