### ISSUE TITLE
NgenR2R is not able to compile netstandard libraries 

### ISSUE THREAD

**Issue by rido-min** [dotnet/coreclr#18164]
moving from [Microsoft/dotnet/issues/756](https://github.com/Microsoft/dotnet/issues/756)

Adding a netstandard nuget package to a project results in types not being found by NgenR2R. In some cases, netstandard shims are part of the input, but they aren't able to be loaded by NgenR2R because they are marked as reference assemblies.

**Comment by jkotas** [comment]
NgenR2R is .NET Framework specific tool. CoreCLR repo is not for tracing .NET Framework specific issues.
