### ISSUE TITLE
[Arm64] Enable HW intrinsics for Windows

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#18175]
It appears arm64 HW intrinsics capabilities are enabled for Linux via `PAL_GetJitCpuCapabilityFlags` and not via a cross-platform mechanism used by Windows.

Enable Windows/Linux parity by enabling (and testing) the HW intrinsics for Windows as well.

**Comment by BruceForstall** [comment]
@sdmaclea comments?

I haven't checked, but what about arm64 SIMD? Is there Windows/Linux parity?

Can you think of any other feature for which there is not cross-platform parity?

**Comment by sdmaclea** [comment]
I have opened a bunch of issues where I implemented something for Arm64 Linux but not Windows.

#16544, #13592, #13590, #13053

My guess is that arm64 SIMD is enabled on Windows.  I don't think it is currently gated by PAL_GetJitCpuCapabilityFlags.  (but perhaps it should be... )

I had thought that eventually, we would implement PAL_GetJitCpuCapabilityFlags on Windows too.

**Comment by sdmaclea** [comment]
The heap sizing on Windows may also need looking at....

**Comment by BruceForstall** [comment]
Thanks for the links.

> The heap sizing on Windows may also need looking at....

Is there an issue (or set of issues) where this was tweaked for arm64?

**Comment by sdmaclea** [comment]
> Is there an issue (or set of issues) where this was tweaked for Linux?

This is the last one #13071.  I think it is just a matter of making sure the heap size calculation is appropriate in gcServer=0 and gcServer=1.  Might already be OK for Windows.  On Linux it was hard coded to 64K when I first looked.  Which led to a lot of gen0 GC events.

**Comment by sdmaclea** [comment]
@CarolEidt 
This was primarily due to lack of a public documented method to determine the set of supported arm64 features in the Windows OS.

**Comment by CarolEidt** [comment]
I am working on this, and I believe I've identified the appropriate API to use: https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-isprocessorfeaturepresent

However, the `PF_ARM` enum values seem to be defined only in the Windows 10 SDK, and AFAICT we are using an older version.

@dotnet/dnceng @dotnet/jit-contrib - can someone point me in the right direction to identify how the build system selects which includes to use, and how/whether one could include the appropriate winnt.h to access this capability?

**Comment by BruceForstall** [comment]
@CarolEidt Why do you think we're using a pre-Windows 10 SDK?

I think we use whatever is installed with your VS2017/2015 installation. E.g., I happen to have 10.0.16299.0 and 10.0.17134.0 on my machine and it appears the build is using the newer one. build.cmd in the repo root determines which version of VS to use, and invokes vcvarsall.bat to set the environment.

Maybe the interesting question is: what version of VS2017 and the Windows SDK is available on the official build machines? I think you're safe assuming this API is there.

Our internal desktop builds are against an older Windows SDK, which doesn't appear to have the `PF_ARM_V8` defines. You might need to do some `#ifdef` magic to keep the build working in both places.

**Comment by CarolEidt** [comment]
The reason I assumed that we were using a pre-Windows 10 SDK is that the `PF_ARM` enum values are reported as undefined when I build. There may be some other reason, but `IsProcessorFeaturePresent` is defined, and seems to work when I pass it the appropriate value.

How does one determine which version of the SDK is being used when I build?

**Comment by AndyAyersMS** [comment]
cmake will print the SDK version when it does its initial configure for windows arm32 or arm64 builds:
```
 message("Using Windows SDK version ${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}")
```
It looks like by default cmake [figures this out on its own](https://cmake.org/cmake/help/v3.6/variable/CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION.html) and probably picks the highest-versioned SDK.

**Comment by CarolEidt** [comment]
@AndyAyersMS thanks. It appears that it's using 10.0.17134.0, and that version of winnt.h definitely has these enum values defined. So I was at a loss as to why they weren't defined. However, I re-tried and now it seems to be working and I don't know what I was doing differently before. Sorry for the confusion, but thanks for the help.
