### ISSUE TITLE
JIT: Remove unused parameters from genCreateAddrMode

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#18177]
Now that the `LEGACY_BACKEND` has been disabled, this method is always called with:
- `regMask == RBM_NONE`
- `nogen == true`

These parameters should be removed.

In addition, the `scale` parameter is only defined under `SCALED_ADDR_MODES`, however `Lowering` calls it with that parameter unconditionally. Currently, all targets define that to be true, but for now it's probably best to at least modify the call in lower.cpp to be consistent.

Finally, the header comment talks about `LEA_AVAILABLE` when it should be `SCALED_ADDR_MODES`, and it would be good to clean up this header to follow the format here: https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/clr-jit-coding-conventions.md#94-function-header-comment

**Comment by CarolEidt** [comment]
This issue would be a good "getting started" project for someone wanting to gain familiarity with the JIT. It would be good to build coreclr on your chosen target, and to read the JIT overview and tutorial documents: https://github.com/dotnet/coreclr/blob/master/Documentation/botr/ryujit-overview.md and https://github.com/dotnet/coreclr/blob/master/Documentation/botr/ryujit-tutorial.md

**Comment by CarolEidt** [comment]
Note: there is another `TODO-Cleanup` comment in this method about the type of the `cnsPtr` argument, which should be a pointer to a signed integer. It would be nice to take care of that as well.

**Comment by karelz** [comment]
Thanks for the PR @Suchiman! I sent you collaborator invite, so that we can assign the issue to you - see details in https://github.com/dotnet/corefx/wiki/Hackathon#how-can-i-grab-an-issue
cc @AndyAyersMS

**Comment by Suchiman** [comment]
@karelz accepted
