### ISSUE TITLE
[arm64] Implement/remove NYI_ARM64

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#18178]
The following are the remaining `NYI_ARM64`. They should either be removed, if not needed, or implemented, or split into a separate issue for each related unimplemented feature.

| File | NYI |
| --- | --- |
| codegenarmarch.cpp | NYI_ARM64("CodeGen::genJmpMethod with multireg HFA arg") |
| ~~codegencommon.cpp~~ | ~~NYI_ARM64("Unsupported JMP indirection")~~ |
| ~~emit.cpp~~ | ~~NYI_ARM64("Need to handle fix-up to data from cold code.")~~ |
| ~~emitarm64.cpp~~ | ~~NYI_ARM64("Relocation Support for long address")~~ |
| ~~morph.cpp~~ | ~~NYI_ARM64("Tail calls via stub are unsupported on this platform.")~~ |
| ~~register_arg_convention.cpp~~ | ~~NYI_ARM64("alignReg")~~ |

category:correctness
theme:testing
skill-level:expert
cost:small

**Comment by janvorli** [comment]
> morph.cpp:    NYI_ARM64("Tail calls via stub are unsupported on this platform.");

I think this one belongs to #2556 (even though the issue is about implementation for Linux, it seems that we should probably not invest into implementing the old style of tail calls via stub for arm64 on Windows, since the design we will use for Linux would work on Windows too).

**Comment by RussKeldorph** [comment]
> codegencommon.cpp:                NYI_ARM64("Unsupported JMP indirection");

Fixed by #19281

**Comment by RussKeldorph** [comment]
> emit.cpp: NYI_ARM64("Need to handle fix-up to data from cold code.")
> emitarm64.cpp: NYI_ARM64("Relocation Support for long address")

#18181

**Comment by BruceForstall** [comment]
Moved `NYI_ARM64("CodeGen::genJmpMethod with multireg HFA arg")` to its own issue: https://github.com/dotnet/coreclr/issues/23147

**Comment by BruceForstall** [comment]
No remaining NYI here, so closing.
