### ISSUE TITLE
Is Multi-Core JIT, ProfileOptimization possible with CoreCLR?

### ISSUE THREAD

**Issue by xoofx** [dotnet/coreclr#18202]
Hey, 

This is a question regarding the API `ProfileOptimization.SetProfileRoot` and `ProfileOptimization.StartProfile`. It doesn't seem to be available through .NET CoreCLR (and almost no issues apart #17124), there is a bit of multi-core JIT in [multicorejit.h](https://github.com/dotnet/coreclr/blob/master/src/vm/multicorejit.h) with actually the internal calls declared for both SetProfileRoot/StartProfile... but no C# version of it...

So just wondering if it could be available? If not, what were the reason? (Not really used? Not compatible with CoreCLR?...etc.)

Thanks!

**Comment by xoofx** [comment]
Ah, I can see it in `AssemblyLoadContext`, so it seems to be supported then?

https://github.com/dotnet/coreclr/blob/f31097f14560b193e76a7b2e1e61af9870b5356b/src/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L383-L392

**Comment by RussKeldorph** [comment]
@brianrob

**Comment by brianrob** [comment]
@noahfalk, can you help with this?

**Comment by jkotas** [comment]
The replaying of profiler optimizations triggers assembly loads. The assembly loads need to know context to go into. The APIs to control that were moved to AssemblyLoadContext during early days of .NET Core to accommodate it so that this can be used with non-default load contexts too. (It can be only used for default context in .NET Framework.)

**Comment by lindexi** [comment]
[ProfileOptimization.SetProfileRoot(String) Method (System.Runtime) | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.profileoptimization.setprofileroot?view=netframework-4.7.2 )
