### ISSUE TITLE
Eliminate GenTreeRegVar and GT_REG_VAR

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#18201]
These are no longer used with the removal of `LEGACY_BACKEND`.

category:design
theme:ir
skill-level:intermediate
cost:small

**Comment by mikedn** [comment]
Eh, I was looking at it this morning. It appears to be used here: https://github.com/dotnet/coreclr/blob/86c438de4043359942f3e0f46c55fdaa98dc5b2f/src/jit/codegenlinear.cpp#L739-L742

Though I wouldn't be too surprised to find out that it's a red herring.

**Comment by CarolEidt** [comment]
> Though I wouldn't be too surprised to find out that it's a red herring.

I'm nearly certain that it *is* a red herring. I believe that was inserted as a hack, and is either no longer needed or can be worked around another way.

**Comment by mikedn** [comment]
Ah, it's not actually used. That code is executed only if the tree was previously `GT_REG_VAR`.

**Comment by juliusfriedman** [comment]
Based on the discussion here and the fact that GT_REG_VAR, GenTreeRegVar and REG_VAR are used in a total of 17  files:
coreclr\src\jit\codegencommon.cpp
coreclr\src\jit\codegenlinear.cpp
coreclr\src\jit\compiler.cpp
coreclr\src\jit\compiler.h
coreclr\src\jit\compiler.hpp
coreclr\src\jit\flowgraph.cpp
coreclr\src\jit\gcinfo.cpp
coreclr\src\jit\gentree.cpp
coreclr\src\jit\gentree.h
coreclr\src\jit\gtlist.h
coreclr\src\jit\gtstructs.h
coreclr\src\jit\liveness.cpp
coreclr\src\jit\lower.cpp
coreclr\src\jit\morph.cpp
coreclr\src\jit\rationalize.cpp
coreclr\src\jit\regset.cpp
coreclr\src\jit\valuenum.cpp

I would like to help out with this and have committed my code.

I was a little unsure of was if RegVar in gtstructs.h should be removed also or reassigned to GT_LCL_VAR, it is removed for now.

In codegencommon.cpp there is also a branch that I was unsure of so I have eliminated it also.

Also was not sure if there were any tests required for this, I have ensured that building the source works after my modifications.

**Comment by mikedn** [comment]
> I was a little unsure of was if RegVar in gtstructs.h should be removed also or reassigned to GT_LCL_VAR, it is removed for now.

That RegVar needs to be removed as well.

> In codegencommon.cpp there is also a branch that I was unsure of so I have eliminated it also.

Not sure which one you're talking about but in general, all `GT_REG_VAR` and `GenTreeRegVar` should go away.

> Also was not sure if there were any tests required for this, I have ensured that building the source works after my modifications.

You mean like adding new tests? No, that's not needed. This code is simply not used.

**Comment by juliusfriedman** [comment]
Thanks for the update, the code is available @ https://github.com/juliusfriedman/coreclr/commit/e212cb7c2a59cd6f117f838dc26aa081fc73e41e as indicated above.

**Comment by mikedn** [comment]
There are a few small issue to fix but otherwise it looks reasonable. Feel free to send a PR.

**Comment by juliusfriedman** [comment]
https://github.com/dotnet/coreclr/commit/d60421f97173d502cebf34e70d5bddbb6a216957 Should fix those formatting errors.

**Comment by CarolEidt** [comment]
Nice cleanup! I think this looks good - could you submit a PR?

**Comment by juliusfriedman** [comment]
Finally have the PR with all builds passing here: https://github.com/dotnet/coreclr/pull/18317
Sorry for the delay and commit noise.

**Comment by juliusfriedman** [comment]
@mikedn, @CarolEidt ; I updated the comments on this PR, let me know what else needs to be done and if I should focus on the contents of my comments or just leave things as they are and complete the assignment and if so what else is required to do so.

**Comment by juliusfriedman** [comment]
@BruceForstall

**Comment by CarolEidt** [comment]
Closed with #18317

**Comment by ANahr** [comment]
@CarolEidt I think you forgot to actually close this one.

**Comment by CarolEidt** [comment]
@ANahr - yes, thanks!
