### ISSUE TITLE
[Ubuntu 16.04 + NGINX] An assembly specified in the assemblies was not found

### ISSUE THREAD

**Issue by vfilenga** [dotnet/coreclr#18212]
Steps to reproduce:

1 - Have a functioning NET CORE 2.0 app 
2 - Add automapper library to it
3 - publish through cli cmd "dotnet publish --configuration Release
4 - grab all the generated files and put into "/var/www/anygym/publish" on a ubunto 16.04 machine

![image](https://user-images.githubusercontent.com/16693247/40755299-446fd682-6454-11e8-8e36-974c1993db9e.png)

Error presented:

 An assembly specified in the application dependencies manifest (Any.Gym.API.deps.json) was not found:
    package: 'AutoMapper.Extensions.Microsoft.DependencyInjection', version: '3.2.0'
    path: 'lib/netstandard2.0/AutoMapper.Extensions.Microsoft.DependencyInjection.dll'

Observation:

The requested dll has been confirmed to be found at "/var/www/anygym/publish" directory

**Comment by jkotas** [comment]
Could you please make sure that you grabbing the assemblies from `bin\Release\netcoreapp2.0\publish` directory in step 4?

This error would happen if you grabbed assemblies from `bin\Release\netcoreapp2.0` directory instead.

We know that the distinction between `dotnet run` that puts bits into `bin\Release\netcoreapp2.0` and `dotnet publish` that puts bits into ``bin\Release\netcoreapp2.0\publish` is pretty confusing. We are looking into how to make it better for .NET Core 3.0.

**Comment by vfilenga** [comment]
@jkotas Thank you! That was it! Once I entered "publish" folder (one directory above) it worked. I was running the command `dotnet Any.Gym.API.dll` from one directory below which was `bin\Release\netcoreapp2.0`
