### ISSUE TITLE
[arm64] crossgen of "JIT\opt\Tailcall\TailcallVerify" fails.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#18226]
on x64 with:
```
COMPLUS_AltJit=*
COMPLUS_AltJitName=protononjit.dll
COMPLUS_AltJitNgen=*
```
this command:
`C:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\crossgen.exe  /Platform_Assemblies_Paths   C:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\ "C:\git\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\opt\Tailcall\TailcallVerifyWithPrefix\TailcallVerifyWithPrefix.exe"`

fails with:
```
Assert failure(PID 24968 [0x00006188], Thread: 39532 [0x9a6c]): Assertion failed 'tiVerificationNeeded || varDsc->lvType == TYP_UNDEF || tree->gtType == TYP_UNKNOWN || allowStructs || genActualType(varDsc->TypeGet()) == genActualType(tree->gtType) || (tree->gtType == TYP_BYREF && varDsc->TypeGet() == TYP_I_IMPL) || (tree->gtType == TYP_I_IMPL && varDsc->TypeGet() == TYP_BYREF) || (tree->gtFlags & GTF_VAR_CAST) || varTypeIsFloating(varDsc->TypeGet()) && varTypeIsFloating(tree->gtType)' in 'TailcallVerify.Condition21:CalleeE4(int,int,int,int,int,struct):struct' (IL size 132)

    File: c:\git\coreclr\src\jit\lclvars.cpp Line: 3841
    Image: C:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\crossgen.exe
```

It is not a recent regression, the issue existed in April at least. This test is excluded in many places, but it is because `x86 JIT doesn't support implicit tail call optimization or tail. call pop ret sequence`, it should not fail with an assert in crossgen.

[Example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_arm64_altjit_checked_windows_nt_r2r_prtest/8/).

**Comment by sandreenko** [comment]
cc @dotnet/jit-contrib

**Comment by jashook** [comment]
I believe this is a dup of https://github.com/dotnet/coreclr/issues/17099.

**Comment by sandreenko** [comment]
> I believe this is a dup of #17099.

Yes, thank you. Closed as dup.
