### ISSUE TITLE
Convert Decimal to all-managed implementation

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#18249]
CoreCLR's is in
https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Decimal.cs
https://github.com/dotnet/coreclr/blob/master/src/classlibnative/bcltype/decimal.cpp

The place to start is by grabbing the code verbatim from CoreRT and measuring performance, then optimizing to fix any regression:

https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Decimal.cs
https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Decimal.DecCalc.cs

Ensuring tests have good coverage, of course.

**Comment by danmosemsft** [comment]
Once this is done the resulting implementation should move to System.Private.CoreLib/shared/System/Decimal.cs and both CoreCLR and CoreRT will use it.

**Comment by pentp** [comment]
https://github.com/dotnet/corert/pull/4452 and https://github.com/dotnet/corert/pull/4997 have most of the performance work done and the remaining performance regressions affect only x86 (everything else is already faster than the current native implementation). The following table has the remaining methods that need work, in particular, ADD and MUL are significantly slower:

### 32-bit

|  ADD |     Mean |     Error |    StdDev | Scaled |
|-------- |---------:|----------:|----------:|-------:|
|  Native | 28.43 ns | 0.0251 ns | 0.0090 ns |   1.00 |
|  CoreRT | 64.05 ns | 0.3440 ns | 0.1227 ns |   2.25 |
| CoreRT2 | 35.95 ns | 0.0438 ns | 0.0156 ns |   1.26 |

|  MUL |     Mean |     Error |    StdDev | Scaled |
|-------- |---------:|----------:|----------:|-------:|
|  Native | 19.23 ns | 0.0267 ns | 0.0069 ns |   1.00 |
|  CoreRT | 47.70 ns | 0.3100 ns | 0.1106 ns |   2.48 |
| CoreRT2 | 28.09 ns | 0.0383 ns | 0.0137 ns |   1.46 |

|  DIV |     Mean |     Error |    StdDev | Scaled |
|-------- |---------:|----------:|----------:|-------:|
|  Native | 116.6 ns | 0.1997 ns | 0.0712 ns |   1.00 |
|  CoreRT | 235.5 ns | 1.0579 ns | 0.3773 ns |   2.02 |
| CoreRT2 | 120.3 ns | 0.0839 ns | 0.0299 ns |   1.03 |

|  HashCode |      Mean |     Error |    StdDev | Scaled |
|-------- |----------:|----------:|----------:|-------:|
|  Native |  7.567 ns | 0.0219 ns | 0.0078 ns |   1.00 |
|  CoreRT | 14.418 ns | 0.0122 ns | 0.0043 ns |   1.91 |
| CoreRT2 | 10.899 ns | 0.0220 ns | 0.0079 ns |   1.44 |

|  FromDouble |      Mean |     Error |    StdDev | Scaled |
|-------- |----------:|----------:|----------:|-------:|
|  Native |  36.31 ns | 0.1820 ns | 0.0649 ns |   1.00 |
|  CoreRT | 112.25 ns | 0.1553 ns | 0.0403 ns |   3.09 |
| CoreRT2 |  41.83 ns | 0.1743 ns | 0.0621 ns |   1.15 |

|  Negate |     Mean |     Error |    StdDev | Scaled |
|-------- |---------:|----------:|----------:|-------:|
|  Native | 1.744 ns | 0.0029 ns | 0.0007 ns |   1.00 |
|  CoreRT | 7.583 ns | 0.0181 ns | 0.0065 ns |   4.35 |
| CoreRT2 | 1.855 ns | 0.0012 ns | 0.0003 ns |   1.06 |

**Comment by pentp** [comment]
Test coverage should be pretty exhaustive already from https://github.com/dotnet/corefx/pull/24053 and https://github.com/dotnet/corefx/pull/26338.

**Comment by jkotas** [comment]
Also, compat issue with the CoreRT implementation needs to be addressed before this can land in CoreCLR: https://github.com/dotnet/corert/issues/4994

**Comment by pentp** [comment]
I'll start working on making decimal a readonly struct in corert so that https://github.com/dotnet/corert/issues/4994 can be resolved before decimal is shared with CoreCRL.
