### ISSUE TITLE
Share more of the HWIntrinsic base code between ARM and XArch, if possible

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#18256]
https://github.com/dotnet/coreclr/pull/18255 did a fairly big refactoring of the XArch HWIntrinsic code.

There are likely several functions which could be shared between Arm64 and XArch. This issue tracks the initial investigation and any work required.

category:design
theme:intrinsics
skill-level:expert
cost:medium

**Comment by CarolEidt** [comment]
@tannergooding - thanks for posting the issue!

**Comment by tannergooding** [comment]
Going to close this as I believe the majority of shareable code is now shared. CC. @CarolEidt
