### ISSUE TITLE
[Arm64/Linux] gcStress=1/2/3 intermittent failures

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#18286]
This issue is for tracking intermittent gcGtress failures which are not threading related..

While the occurrence rate of these failures is low, it is worth tracking them here to help detect patterns.

**Comment by sdmaclea** [comment]
This failure occurred in one run this weekend.

gcStress=0x4
```
corerun GetGenerationWR.exe

Assert failure(PID 14440 [0x00003868], Thread: 14440 [0x3868]): 
!CREATE_CHECK_STRING(pMT && pMT->Validate())
    File: src/vm/object.cpp Line: 733
```

**Comment by sdmaclea** [comment]
gcStress is stable on Linux/Arm64 now.  I am no longer seeing intermittent failures.  Closing this for now.

**Comment by sdmaclea** [comment]
I saw one spurious failure here on 7/2/2018 in gcStress=0x2
```
corerun LocallocLarge.exe

Assert failure(PID 10087 [0x00002767], Thread: 11371 [0x2c6b]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"
    File: /home/vmjenkins/workspace/Dotnet/build_coreclr/src/vm/jithelpers.cpp Line: 5157
```

**Comment by sdmaclea** [comment]
There was one spurious failure over the weekend of 7/15/2018
`gcStress=0x2`
```
corerun SystemCollGenericICollClear.exe

Assert failure(PID 12351 [0x0000303f], Thread: 12351 [0x303f]): pTable
    File: src/gc/handletable.cpp Line: 64
```

**Comment by Maoni0** [comment]
sorry @sdmaclea we haven't looked at these failures but I really appreciate your reporting - please keep them coming. I'll try my best to make the investigation happen.

**Comment by sdmaclea** [comment]
@Maoni0 It is not clear to me how to debug these as they are very rare now.  I see about 1 failure a week.  I am running gcStress 1,2,4,8 each 10x a night...  It seems worth still reporting...

**Comment by sdmaclea** [comment]
This one happened once on 7/18/2018

gcStress=2
```
corerun LocallocLarge.exe

Assert failure(PID 32851 [0x00008053], Thread: 34610 [0x8732]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"
    File: /home/vmjenkins/workspace/Dotnet/build_coreclr/src/vm/jithelpers.cpp Line: 5157
```

**Comment by sdmaclea** [comment]
I added a few new configurations to my nightly runs.

This test is consistently failing in these configs
```
gcStress=0xC jitstress=1 JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b399444/b399444b/b399444b.sh
gcStress=0xC jitstress=2 JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b399444/b399444b/b399444b.sh
```

Failure looks simialr to the LocalAlloc fail.

```
corerun b399444b.exe

Assert failure(PID 7270 [0x00001c66], Thread: 7270 [0x1c66]): 
    !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"
    File: src/vm/jithelpers.cpp Line: 5157
```

**Comment by Maoni0** [comment]
would someone from your team please take a look at this, @RussKeldorph?

**Comment by sdmaclea** [comment]
There was one rare failure 7/30/2018
`GC/API/GC/GetGenerationWR/GetGenerationWR.sh`
`gcStress=0xC`
```
corerun GetGenerationWR.exe

Assert failure(PID 17500 [0x0000445c], Thread: 17500 [0x445c]): 
    !CREATE_CHECK_STRING(pMT &amp;&amp; pMT-&gt;Validate())
    File: src/vm/object.cpp Line: 733
```

It may be worth noting the `GetGenerationWR2` is marked gcStressIncompatible

**Comment by RussKeldorph** [comment]
@sdmaclea Would you mind opening a separate issue to capture failures that happen under GCStress=4/8/C and/or JitstressXXX as opposed to GCStress=1/2/3 only?

**Comment by sdmaclea** [comment]
@RussKeldorph 

`LocalAllocLarge` looks like it always happened in gcStress=0x2/0x3/0xF.  
`SystemCollGenericICollClear` occurred once at gcStress=0x2

`b399444b` has always occurred in `gcStress=0xC jitstress=1/2`
`GetGenerationWR` looks like it happened in gcStress=0x4 & 0xC.  

I'll move `b399444b` & `GetGenerationWR` to a new issue.

**Comment by RussKeldorph** [comment]
`SystemCollGenericICollClear` was deleted.
`LocallocLarge` has had no "interesting" failures (e.g. it timed out once--yesterday, coredistools failed to download 4 times, etc.) in any test mode in our Kusto history.

I don't think we're going to investigate any time soon based on the above.  Please re-open if you disagree.  @dotnet/jit-contrib @janvorli.
