### ISSUE TITLE
Working folder when debugging a .NET Core app changing bizarrely

### ISSUE THREAD

**Issue by Pilchie** [dotnet/coreclr#18284]
_From @adamralph on June 1, 2018 22:33_

_Continuing from [Twitter](https://twitter.com/davkean/status/1002675512399970304)._

Note that the breakpoint is _before_ the call to `Directory.SetCurrentDirectory()`!

![working-dir](https://user-images.githubusercontent.com/677704/40866148-6f48d7b0-65fc-11e8-9e9b-498bae7e57c2.gif)

_Copied from original issue: dotnet/project-system#3609_

**Comment by Pilchie** [comment]
_From @adamralph on June 1, 2018 22:35_

@davkean if you want to try it yourself, the repo is https://github.com/adamralph/liteguard

I'm using VS 15.7.1.

**Comment by Pilchie** [comment]
_From @adamralph on June 1, 2018 22:40_

Also, this is when I create a blank console project in a fresh instance of VS:

![image](https://user-images.githubusercontent.com/677704/40866350-8372ed9c-65fd-11e8-90cd-21376e604851.png)

**Comment by Pilchie** [comment]
_From @adamralph on June 1, 2018 22:43_

And again, as soon as I add a call to `Directory`, it changes, _before_ the call to `Directory` has happened_.

![image](https://user-images.githubusercontent.com/677704/40866444-f5d3e76a-65fd-11e8-9381-35b4f5a7931a.png)

**Comment by Pilchie** [comment]
_From @adamralph on June 1, 2018 22:44_

@davkean I suspect that to produce the screenshot in your tweet, you called `Directory.GetCurrentDirectory()`, hence the reason you saw the project output folder.

**Comment by Pilchie** [comment]
_From @steveharter on June 4, 2018 16:29_

I can confirm this is an issue with 2.0.x. I also have a "random" location in a simple app: `C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.7\\System.Private.CoreL` when there aren't any references to a System.IO type (or perhaps others; I didn't try) in the code block.

However with 2.1.0 I couldn't repro the issue because the immediate window won't run a `Directory.GetCurrentDirectory()` without an assembly reference: `error CS0234: The type or namespace name 'Directory' does not exist in the namespace 'System.IO' (are you missing an assembly reference?)`

I suggest moving this issue to coreclr repo since it appears to be related to type initialization.

**Comment by Pilchie** [comment]
Moved based on @steveharter's suggestion.

**Comment by jkotas** [comment]
This is caused by https://github.com/dotnet/corefx/issues/16229. 

In .NET Core 2.0, the intermediate Windows is picking up the internal untested System.IO.Directory type in CoreLib. This has been cleaned up in .NET Core 2.1 and that's why you are not able to reproduce it. 

There are still some duplicate types in .NET Core 2.1 for which this continues to be a problem.

**Comment by danmosemsft** [comment]
This specific issue seems fixed, and hypothetical other issues tracked by dotnet/corefx#16229
