### ISSUE TITLE
Alpine Linux coreclr, dac, dbi not honoring PAL symbol versions

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#18307]
The loader on Alpine links the libmscordbi.so PAL references to libvsbaseservices.so (which contains VS's debug engine PAL) instead of the the PAL in libmscordaccore.so.

On Alpine Linux the export PAL APIs from the DAC need to have a module specific prefix added so the loader links to the right module/PAL.

**Comment by mikem8361** [comment]
Added to master in PR #18873.

**Comment by danmosemsft** [comment]
@mikem8361 if you want this into 2.1.x (per milestone set on this issue) you'll want to talk to @RussKeldorph
