### ISSUE TITLE
NullReferenceException on Linux with nullable unboxing

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#1831]
Here's a minimal repro:
```C#
using System;

class Program
{
    static void Main() { F(); }

    static object F()
    {
        object o = null;
        long? l = (long?)o;
        return (object)l;
    }
}
```
On Windows this runs without error.  On Linux this throws a NullReferenceException.

This is a very simplified version of code failing in some of the corefx System.Linq.Expressions tests.

cc: @LLITCHEV, @janvorli, @bartdesmet, @VSadov

**Comment by VSadov** [comment]
Nullables are special. Boxing nullable default value results in  null. And the other way - unboxing  null results in a nullable default.
Unboxing to nullable should never throw NRE

**Comment by VSadov** [comment]
Also check the unbox opcode.
It is trickier than unbox.any. Where nullable unbox.any on null needs to just push a default nub value, unbox needs to conjure up a nub variable holding a default value and push a reference to that.

**Comment by stephentoub** [comment]
I should note that the codeI provided only repros when compiled with /o+.  If compiled instead with /o-, it doesn't repro.  Here's the IL generated for F() with optimizations:
```
  IL_0000:  ldnull
  IL_0001:  unbox.any  valuetype [System.Runtime]System.Nullable`1<int64>
  IL_0006:  box        valuetype [System.Runtime]System.Nullable`1<int64>
  IL_000b:  ret
```
and without:
```
  IL_0000:  nop
  IL_0001:  ldnull
  IL_0002:  stloc.0
  IL_0003:  ldloc.0
  IL_0004:  unbox.any  valuetype [System.Runtime]System.Nullable`1<int64>
  IL_0009:  stloc.1
  IL_000a:  ldloc.1
  IL_000b:  box        valuetype [System.Runtime]System.Nullable`1<int64>
  IL_0010:  stloc.2
  IL_0011:  br.s       IL_0013
  IL_0013:  ldloc.2
  IL_0014:  ret
```

**Comment by stephentoub** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/1862
