### ISSUE TITLE
JIT has run out of instruction bits in instrDesc

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#18324]
We have 9 bits for the instruction field and `INS_count` is now 515. It's not clear how come we didn't hit any asserts yet, it might be because the last instructions are long jumps and `INS_align`. Long jumps do not appear to be used and `INS_align` is probably only used with the "align loops" option.

**Comment by mikedn** [comment]
cc @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
@mikedn - thanks for this! I was just talking yesterday about how we'd run out of bits before, and I was kind of surprised we weren't running up against the limit again. Clearly we're missing at least one assert check!

**Comment by mikedn** [comment]
There is an assert in `idIns`:
```C++
        void idIns(instruction ins)
        {
            _idIns = ins;
            assert(_idIns == ins);
        }
```
That's why I'm guessing that the instructions at the end of the enum aren't currently used.

Anyway, a static_assert would be much better.

But now the problem is where to steal a bit from. Simply increasing the width of bit field from 9 to 10 increases the size of the struct by 8 bytes. If it was that easy I would have simply sent a PR doing that :grin:

**Comment by CarolEidt** [comment]
> If it was that easy I would have simply sent a PR doing that

I have no doubt!

**Comment by mikedn** [comment]
The current x64 `instrDesc` layout is:
```
	|struct emitter::instrDesc {
0000:00	|	instruction _idIns:9;
0000:09	|	emitter::insFormat _idInsFmt:8;
0000:11	|	unsigned int _idCodeSize:4;
0000:15	|	emitter::opSize _idOpSize:3;
0000:18	|	GCtype _idGCref:2;
0000:1A	|	_regNumber_enum _idReg1:6;
0004:00	|	_regNumber_enum _idReg2:6;
0004:06	|	unsigned int _idSmallDsc:1;
0004:07	|	unsigned int _idLargeCns:1;
0004:08	|	unsigned int _idLargeDsp:1;
0004:09	|	unsigned int _idLargeCall:1;
0004:0A	|	unsigned int _idBound:1;
0004:0B	|	unsigned int _idCallRegPtr:1;
0004:0C	|	unsigned int _idCallAddr:1;
0004:0D	|	unsigned int _idNoGC:1;
0004:0E	|	unsigned int _idCnsReloc:1;
0004:0F	|	unsigned int _idDspReloc:1;
0004:10	|	unsigned int _idSmallCns:16;
0008	|	emitter::instrDesc::idAddrUnion _idAddrUnion;
	|};
	|
	|union emitter::instrDesc::idAddrUnion {
0000	|	emitLclVarAddr iiaLclVar;
0000	|	BasicBlock* iiaBBlabel;
0000	|	insGroup* iiaIGlabel;
0000	|	unsigned char* iiaAddr;
0000	|	emitter::emitAddrMode iiaAddrMode;
0000	|	CORINFO_FIELD_STRUCT_* iiaFieldHnd;
0000:00	|	_regNumber_enum _idReg3:6;
0000:06	|	_regNumber_enum _idReg4:6;
	|};
```

**Comment by BruceForstall** [comment]
Normally, when we increase the number of bits somewhere, the number of small constant bits decreases by one (and thus we end up with more small constant overflows into larger instrDescs).

In this case, perhaps we should look to remove (or comment out) unused instructions first?

Maybe we get lucky because we never explicitly use the long jump instructions, but they are used via calculation in `emitter::emitOutputLJ`.

**Comment by BruceForstall** [comment]
I heartily agree that a static assert is required!

**Comment by mikedn** [comment]
> In this case, perhaps we should look to remove (or comment out) unused instructions first?

Yeah, I have a few ideas:
* replace all JCC/SETCC/CMOVCC instructions with one per group. The condition would be stored separately. Where - that is the big question.
* get rid of the IMUL_ref hack. Seems doable on the emitter side, the trouble is that it might require duplicating some hairy logic form `emitInsBinary`.

**Comment by tannergooding** [comment]
> In this case, perhaps we should look to remove (or comment out) unused instructions first?

@BruceForstall, I'm not sure that would help much. We still have a number of HWIntrinsics to implement (which depend on undeclared instructions) and that will push us right back over.

**Comment by mikedn** [comment]
> We still have a number of HWIntrinsics to implement (which depend on undeclared instructions) and that will push us right back over.

Do you happen to have any estimate of the number of instructions yet to be added? Cleaning up JCC/SETCC/CMOVCC/IMUL would save around 70 instructions.

**Comment by mikedn** [comment]
> Maybe we get lucky because we never explicitly use the long jump instructions, but they are used via calculation in emitter::emitOutputLJ.

Yes, but it looks like they only exist to provide the encoding for long jumps. So it they don't need to be referenced explicitly from codegen then it seems that the proper way to deal with them is to simply use INST2 for short JCCs.

**Comment by tannergooding** [comment]
@mikedn, `70` might be enough for now.

For the currently approved intrinsics, we still have to implement all of `AES`, `BMI1`, `BMI2`, and `PCLMULQDQ`. We also have to finish implementing `AVX`, `AVX2`, and `SSE42` (AVX and AVX2 have several of the instructions, but not all, exposed already).

I'll try to get a more complete count after lunch.

NOTE: We will have to grow if we decide to implement AVX-512; but that hasn't been reviewed/approved yet.

**Comment by AndyAyersMS** [comment]
If `instrDescs` were in an array and non-copyable then the ID would be a function of the address, so wouldn't need to be stored explicitly.

**Comment by BruceForstall** [comment]
> Yes, but it looks like they only exist to provide the encoding for long jumps. So it they don't need to be referenced explicitly from codegen then it seems that the proper way to deal with them is to simply use INST2 for short JCCs.

so that would "abuse" one of the encoding formats, repurposed for "long" jumps?

**Comment by mikedn** [comment]
> If instrDescs were in an array and non-copyable then the ID would be a function of the address, so wouldn't need to be stored explicitly.

I don't understand, what ID are you referring to?

**Comment by mikedn** [comment]
> NOTE: We will have to grow if we decide to implement AVX-512; but that hasn't been reviewed/approved yet.

I suppose it's reasonable to assume that they'll be approved sooner or later. So yes, it looks like 70 more instructions won't be enough, a rough count of the instructions in the latest Intel manual gives something like 650 instructions. And that doesn't account for the fact that they have a single section for instruction groups such as JCC. Not all are needed but anyway, in the best case we'll be very close to the limit.

**Comment by mikedn** [comment]
> Normally, when we increase the number of bits somewhere, the number of small constant bits decreases by one (and thus we end up with more small constant overflows into larger instrDescs).

It seems to me that this is the best course of action right now. Cleaning up instructions is tempting but it may take a while, every time I look at the emitter I find more complications that it's not clear how should be addressed. And 15 bits for constants should still be reasonable.

**Comment by AndyAyersMS** [comment]
Probably just ignorance on my part. If `instrDesc`s are immutable then I'd store them all in an array (or permute as a struct of arrays) and use the instruction enum as array index to refer to them and not let them be copied. Then the first field would be the same as the index and so wouldn't need to be stored explicitly and we could have as many as we pleased.

But it looks like instr descs are copied so maybe they're also mutable?

**Comment by mikedn** [comment]
> If instrDescs are immutable then I'd store them all in an array (or permute as a struct of arrays) and use the instruction enum as array index to refer to them and not let them be copied.

Sorry, I still don't understand. But instrDescs have variable size so array indexing won't work in this case.

Speaking of variable size. That's a good example of emitter weirdness - sometimes we don't even allocate memory for a full `instrDesc`, we only allocate memory for half of it. And code has to check `idSmallDsc` before touching `_idAddrUnion` (the last 8 bytes).

**Comment by BruceForstall** [comment]
> It seems to me that this is the best course of action right now. Cleaning up instructions is tempting but it may take a while, every time I look at the emitter I find more complications that it's not clear how should be addressed. And 15 bits for constants should still be reasonable.

Agreed.

**Comment by briansull** [comment]
Yes, 15 bits for immediate constants is still reasonable.

**Comment by briansull** [comment]
Actually the easy fix for now is to reduce the size of 

emitter::insFormat _idInsFmt:8;  on XARCH to 7 bits

Otherwise their a problem getting everything to pack:

The current x64 instrDesc layout is:
	|struct emitter::instrDesc {
0000:00	|	instruction _idIns:9;
0000:09	|	emitter::insFormat _idInsFmt:8;
0000:11	|	unsigned int _idCodeSize:4;
0000:15	|	emitter::opSize _idOpSize:3;
0000:18	|	GCtype _idGCref:2;
0000:1A	|	_regNumber_enum _idReg1:6;
0004:00	|	_regNumber_enum _idReg2:6;
0004:06	|	unsigned int _idSmallDsc:1;
0004:07	|	unsigned int _idLargeCns:1;
0004:08	|	unsigned int _idLargeDsp:1;
0004:09	|	unsigned int _idLargeCall:1;
0004:0A	|	unsigned int _idBound:1;
0004:0B	|	unsigned int _idCallRegPtr:1;
0004:0C	|	unsigned int _idCallAddr:1;
0004:0D	|	unsigned int _idNoGC:1;
0004:0E	|	unsigned int _idCnsReloc:1;
0004:0F	|	unsigned int _idDspReloc:1;
0004:10	|	unsigned int _idSmallCns:16;
0008	|	emitter::instrDesc::idAddrUnion _idAddrUnion

**Comment by briansull** [comment]
There are only 79 different insFormat's on XARCH

**Comment by briansull** [comment]
For Arm we have 91
For Arm64 we have 120

findstr IF_DEF emitfmtsarm.h | wc
     97     926   12001
findstr IF_DEF emitfmtsarm64.h | wc
    123    1358   11419

**Comment by mikedn** [comment]
> Otherwise their a problem getting everything to pack:

Yes, we'd need to move the registers near the end so they land in the second unsigned, with the many 1 bit fields in the middle. But since there's a spare bit in `idInsFmt` there's no need for that. I was actually wondering how come there are so many formats but never got around to check. Thanks!
