### ISSUE TITLE
Hope ThreadPoolTimer.CreatePeriodicTimer can start a job immediately

### ISSUE THREAD

**Issue by SusLes** [dotnet/coreclr#18331]
Moving from Microsoft\dotnet.
<br>
Posted by @kevin-jing.
<br>
Now it works like wait > work > wait …
<br>
How to work like work > wait > work …? <br>
https://docs.microsoft.com/en-us/windows/uwp/threading-async/create-a-periodic-work-item
I'm actually using a workaround:<br>
ThreadPoolTimer.CreateTimer(MonitorAsync, TimeSpan.FromSeconds(0));
PeriodicTimer = ThreadPoolTimer.CreatePeriodicTimer(MonitorAsync, TimeSpan.FromSeconds(10));<br>
It's not beautiful.<br>
I hope MS can add another overload like:<br>
CreatePeriodicTimer(TimerElapsedHandler handler, TimeSpan period, TimeSpan delay);

**Comment by danmosemsft** [comment]
@SusLes seems reasonable. Could you please close this one, and open a new issue in dotnet/corefx, with the proposal in format suggested in https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md ? Then we can review it formally.

**Comment by stephentoub** [comment]
That's not a .NET class.  It's WinRT.

**Comment by RussKeldorph** [comment]
@danmosemsft @stephentoub Any idea where WinRT API requests can be made?

**Comment by stephentoub** [comment]
> Any idea where WinRT API requests can be made?

I don't know.

**Comment by danmosemsft** [comment]
Helped Russ offline

**Comment by ptorr-msft** [comment]
For future reference, Windows API requests can be made via the Feedback Hub ("Developer" category) or via https://wpdev.uservoice.com/. I'll also pass this one on internally. Thanks for your feedback!
