### ISSUE TITLE
CoreCLR failed when build with msvc on windows

### ISSUE THREAD

**Issue by PhoebeHui** [dotnet/coreclr#18338]
CoreCLR failed with warning C4644  when build with msvc on Windows, I use latest source on master branch. The source code is ill-formed, could you please help take a look at this?
Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

The probably fix: the project either needs to build with /wd4644, pragma push/pop the warning, or do as the warning says and use the STL’s offsetof

You can repro this issue as the steps below:
1.git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2.Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\CoreCLR\src
3.build x86 release -Rebuild -- /clp:ShowCommandLine

Failures:
d:\coreclr\src\src\vm\i386\profiler.cpp(172,10): warning C4644:  usage of the macro-based offsetof pattern in constant expressions is non-standard; use offsetof defined in the C++ standard library instead [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\vm\wks\cee_wks.vcxproj]
d:\coreclr\src\src\vm\i386\profiler.cpp(172,10): warning C4644:     case offsetof(ArgumentRegisters, ECX): [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\vm\wks\cee_wks.vcxproj]
d:\coreclr\src\src\vm\i386\profiler.cpp(172,10): warning C4644:          ^ [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\vm\wks\cee_wks.vcxproj]
d:\coreclr\src\src\vm\i386\profiler.cpp(174,10): warning C4644:  usage of the macro-based offsetof pattern in constant expressions is non-standard; use offsetof defined in the C++ standard library instead [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\vm\wks\cee_wks.vcxproj]
d:\coreclr\src\src\vm\i386\profiler.cpp(174,10): warning C4644:     case offsetof(ArgumentRegisters, EDX): [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\vm\wks\cee_wks.vcxproj]
d:\coreclr\src\src\vm\i386\profiler.cpp(174,10): warning C4644:          ^ [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\vm\wks\cee_wks.vcxproj]
<snip>
[D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\vm\wks\cee_wks.vcxproj]
d:\coreclr\src\src\vm\i386\profiler.cpp(172,10): error C2220:  warning treated as error - no 'object' file generated [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\vm\wks\cee_wks.vcxproj]
d:\coreclr\src\src\vm\i386\profiler.cpp(172,10): error C2220:     case offsetof(ArgumentRegisters, ECX): [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\vm\wks\cee_wks.vcxproj]
d:\coreclr\src\src\vm\i386\profiler.cpp(172,10): error C2220:          ^ [D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\src\vm\wks\cee_wks.vcxproj]

**Comment by jkotas** [comment]
Related to #18260 / #18128 ?
cc @sandreenko

**Comment by mikedn** [comment]
It seems that there are multiple `offsetof` definitions in the CLR headers (corinfo.h, gcinfotypes.h, volatile.h), it's not clear why it feels the need to reinvent the wheel instead of using the `offsetof` provided by the standard headers.
