### ISSUE TITLE
corerun prints nothing when there's a managed exception at the entrypoint (on OSX)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#1836]
```C#    
    public class  Program
    {
        public static void Main(string[] args)
        {
            throw new System.Exception("Hej");
        } 
    }
```

Try that, and it will noop. This was on OSX, I'm not sure what happens on windows.

I assume coreconsole has the same behavior.

/cc @jkotas @gkhanna79 @janvorli

**Comment by stephentoub** [comment]
FYI, on Linux I see this:
```
stoub@stoublinux1:~/netcore$ ./corerun Repro.exe 

Unhandled Exception: System.Exception: Hej
   at Program.Main(String[] args)
Aborted (core dumped)
stoub@stoublinux1:~/netcore$ 
```

**Comment by sergiy-k** [comment]
@davidfowl, I have just tried your repro code on the latest build of coreclr on OSX and I see the same output that @stephentoub got on Linux (i.e. the correct one). What is the sync point of the libcoreclr that you are using? A few days ago there was large change that was incorrectly merged and removed the top level exception handler. It has been fixed already.

**Comment by davidfowl** [comment]
Ok then I have an old crusty build.

**Comment by anurse** [comment]
What build is this? I'm still seeing it using the runtime in the NuGet package `Microsoft.NETCore.Runtime 1.0.1-beta-23420`

Program.cs:

```csharp
using System;

namespace ProcessTests
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            throw new Exception("Oh noes!");
        }
    }
}
```

Output:
```
› ./ProcessTests; echo $?
6
```

The exit code is 6 and nothing is written...

**Comment by anurse** [comment]
Looks like maybe it hasn't made the NuGet feed? The latest build from dotnet-ci exhibits the **correct** behavior:

```
› ./ProcessTests; echo $?

Unhandled Exception: System.Exception: Oh noes!
   at ProcessTests.Program.Main(String[] args)
```
