### ISSUE TITLE
[Regression] Assertion failed 'mask != RBM_NONE'

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#18367]
`jit\regset.cpp (120) - Assertion failed 'mask != RBM_NONE'`
The regression was introduced by #18230.

cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
What test case, architecture, etc.?

**Comment by sandreenko** [comment]
I need an issue to get the issue number for the test case. I will add it tommorow, it is x86, debug.

**Comment by mikedn** [comment]
> I need an issue to get the issue number for the test case.

Out of curiosity - is it a hard requirement to use the issue number? In some simple cases I was tempted to just use the PR number. But I went ahead and filled an issue because that seems to be the practice.

**Comment by sandreenko** [comment]
> Out of curiosity - is it a hard requirement to use the issue number? In some simple cases I was tempted to just use the PR number. But I went ahead and filled an issue because that seems to be the practice.


We usually add regression tests with issue number in the name, I think it is fine when you open a PR with a repro, then rename the test in this PR to use PR's number. I did not have a repro yesterday, but wanted to inform about existing issue and prevent duplication of work I opened  this, don't think there are strict requirements about that.


> @sandreenko - thanks for finding this. I gather you're already working on (or have) a fix?

Yes, I am planning to push PR soon.

**Comment by sandreenko** [comment]
The issue is that `regTracker.rsTrashRegSet(killMask); ` was replaced with `regSet.verifyRegistersUsed(killMask); ` and the second one doesn't allow 'killMask` to be empty (it calls `rsSetRegsModified` with this assert), when the previous method allowed it. Empty `killMask` is valid for certain helpers, for example for `ProfilingLeaveCallback`.


The fix can be to change the assert or check it that `killMask` is not empty before calling  `rsSetRegsModified` or `regSet.verifyRegistersUsed`.

I am working on a repro.
