### ISSUE TITLE
Remove length restrictions on named synchronization primitives lengths on Windows

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#18370]
From https://github.com/dotnet/coreclr/pull/18320#issuecomment-395603647

If the OS allows creating mutex with the long name, we should allow it too. We are just getting into way by blocking the longer names for no good reason.

**Comment by jkotas** [comment]
cc @Anipik @danmosemsft 

It would be nice to do this before moving the remaining synchronization primitives to shared partition to avoid need for ifdefs.

**Comment by jkotas** [comment]
Look for `MAX_PATH` under src\System.Private.CoreLib\src\System\Threading

**Comment by Anipik** [comment]
@jkotas i will due that after the #18320 gets merged

**Comment by stephentoub** [comment]
Related: https://github.com/dotnet/corefx/issues/3740
