### ISSUE TITLE
Remove usage of CodeTaskFactory

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#1838]
We need to remove the usage of CodeTaskFactory if possible.  This should be replaced with a download of nuget.exe in the initial build script if possible.  The inline C# code used to download nuget is the source of many failed builds
/cc @weshaggard @gkhanna79

**Comment by mellinoe** [comment]
Can we just require that NuGet.exe be on your PATH, or on your machine in some well-known location that we probe? We already require a lot of other things be installed without trying to download them, so I'm wondering if there's something about NuGet.exe that makes it special other than the fact that it's a standalone executable (and therefore easily downloadable).

> This should be replaced with a download of nuget.exe in the initial build script if possible

How will you build using msbuild then? Or will msbuild invoke the download script that downloads nuget.exe and the continue normally?

**Comment by mmitche** [comment]
msbuild could do that, or we could invoke it in build.cmd/sh beforehand.

**Comment by akoeplinger** [comment]
Downloading nuget.exe in build.cmd sounds like a good approach to me, it's already done in [build.sh](https://github.com/dotnet/coreclr/blob/429bb1cecd6208b6334c73eae7e48442951d2c5d/build.sh#L128)

**Comment by ellismg** [comment]
@mmitche Are you sure about the nuget.exe download being the problematic task?  When I was looking at some of the failed builds, it seemed like there was also an inline task in the official build targets that used C# code to set some environment variables (this was in the C++ Code Analysis targets).  Or maybe we are hitting this in both places?

**Comment by ellismg** [comment]
For example, the failure here does not seem to be related to NuGet.exe downloading: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/debug_windows_nt_prtest/332/consoleFull#111985390379494335-f7bd-47d0-8771-8661e00c2db2

**Comment by mmitche** [comment]
@ellismg Hmm, that could could be it too.  It's a little unclear.  I'm not sure whether a target simply being included causes the compilation, or whether it needs to be run. We don't hit this in CoreFx though, which is an interesting datapoint.

**Comment by weshaggard** [comment]
In either case I would still like to get the downloading of nuget of our msbuild project files in into build.cmd/build.sh.

**Comment by tzwlai** [comment]
@weshaggard, assigning this to you for now.  Please feel free to reassign as appropriate.

**Comment by weshaggard** [comment]
With the switch to dotnet cli and init-tools.cmd this we no longer use the CodeTaskFactory for downloading nuget.exe so closing this issue.
