### ISSUE TITLE
StringBuidler  support Offset(int length)

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/coreclr#18399]
New API:
```C#
//
public void Offset(int length){
   if(length<0)
   {
       // throw........   
   }
   if(length>count){
       // alloc more space
   }else{ 
      // reset the offset
       m_ChunkLength=length;
   }
}
```

Use:
```C#
StringBuilder builder = new StringBuilder();
for(int i=0;i<10;i+=1)
{
    builder.Append(array[i]);
    builder.Append(',');
}
builder.Offset(builder.length-1);
builder.Append(others);

```

**Comment by stephentoub** [comment]
I don't understand... what's the purpose of this proposed meeting?

**Comment by NMSAzulX** [comment]
“1，2，3，”
I want to remove the latest ',' 

result:
“1，2，3”

**Comment by jkotas** [comment]
Replace `builder.Offset(builder.length-1);` with `builder.Length=builder.length-1` in your example. It will remove the latest.

**Comment by jkotas** [comment]
Another way to remove the latest character from StringBuilder is: `builder.Remove(builder.Length - 1, 1)`.

**Comment by NMSAzulX** [comment]
OK. Thank you~
