### ISSUE TITLE
Potential incorrect optimization leading to AccessViolationException

### ISSUE THREAD

**Issue by hvanbakel** [dotnet/coreclr#18413]
So we've been running into an issue where the runtime seems to be assigning the wrong value to a parameter leading to an `AccessViolationException` being thrown.

The issue occurs in a docker container (based on `microsoft/dotnet:2.0-runtime`) running on Linux and doesn't occur on Windows. The code in the callstack in the image was compiled in Release configuration. It seems to have assigned the formatter `Func<object, System.Exception, string>` value to the exception parameter. 

It has been hard to pinpoint exactly why it is doing what it's doing here and at the time of writing I don't have a small case that reproduces the issue. We do run plenty of other code that uses the same routines that doesn't get this issue so our hypothesis is that the JITter might be optimizing something here leading to the exception.

![jit issue](https://user-images.githubusercontent.com/4130108/41247567-2df53e84-6d63-11e8-8d81-bb4295adce43.png)

Please let me know of any additional information needed and I'll try to get it as soon as possible.

**Comment by AndyAyersMS** [comment]
I'm not sure if the debugger view can be entirely trusted here, as debug emission for release builds is done on a best-faith effort.

A couple things to try to help narrow things down:
* does this error happen deterministically?
* does the error reproduce in debug builds?
* does the error reproduce if you run release and set `COMPlus_JitMinOpts=1`?

**Comment by hvanbakel** [comment]
The debugger window seems to be accurate given crashes we've seen without debugging that seemed to report just this. We attached a debugger because we were sure that had to be wrong since this is all static typed 😄 .

It is deterministic, just on a specific code path.
As to the debug builds, and the release build with a flag set, I'll get back to you on that.

**Comment by hvanbakel** [comment]
So the results of my additional tests:

1. Running a debug build -> still crashes
2. Setting the `COMPlus_JitMinOpts=1` as an environment variable in Docker -> still crashes
3. Removing the call to [LoggerMessage.Define](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-2.1#loggermessagedefine) -> fixes the issue

To elaborate on #3, that was the call that occurred just before the call into the MS logger library.

I'm still trying to see if I can create a simple repro case but haven't been able to yet.

**Comment by AndyAyersMS** [comment]
Since you still see crashes in debug and with minopts it is probably not a jit issue.

@davidfowl does this seems familiar to you at all? Any platform or docker specific issues you know of with logging?

**Comment by hvanbakel** [comment]
@AndyAyersMS the fact that this is net core doesn't matter here, correct. Just making sure 😄, I looked at https://github.com/Microsoft/dotnet/blob/master/Documentation/testing-with-ryujit.md and that seems very NetFx only

**Comment by AndyAyersMS** [comment]
.Net Core also uses RyuJit. 

You still could be hitting a problem in the jit, but at this point I suspect it is something else.

**Comment by hvanbakel** [comment]
Just verified, switching the docker image over from
`FROM microsoft/dotnet:2.0-runtime AS final`
to
`FROM microsoft/dotnet:2.1-aspnetcore-runtime AS final`

Fixes the issue too.

**Comment by AndyAyersMS** [comment]
If there is some bug in 2.0 that is behind all this, it would be good to root cause it and see why it's no longer an issue with 2.1. I'm not sure we can help much without some kind of repro though.

**Comment by hvanbakel** [comment]
I totally understand, so far I have not been able to reproduce this though 😞 it is very much complicated by the fact that it only happens on linux.

We'll try to see if we can make it crash from a Mac. If not, I would not know how to get more info out of it.

**Comment by hvanbakel** [comment]
I think I might have stumbled upon part of the problem, my dockerfile looks like this:
```
FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY . .
RUN dotnet publish EntryPoint.csproj -c Release -o /dist

# build runtime image
FROM microsoft/dotnet:2.1-aspnetcore-runtime
WORKDIR /app
COPY --from=build /dist .
ENTRYPOINT ["dotnet", "EntryPoint.dll"]
```

The thing that apparently makes a difference is the BUILD docker image that I'm pulling in. Where building it like this `FROM microsoft/dotnet:2.1-sdk AS build` works but building it like this `FROM microsoft/aspnetcore-build AS build` does not. So maybe this is not in the JIT but in the msbuild image that gets pulled in. 

That would explain why we were only seeing it in Docker and why the Linux only might not apply. It could very well be that building this on windows with the above image yields the same results.

I'll try and gather some more data, but thought this was relevant nonetheless.

**Comment by hvanbakel** [comment]
I'm afraid not, we were going to upgrade to 2.1 anyway because of that being an LTS release. So since it doesn't occur there we were unblocked. 

We're experimenting with docker at this time so it's hard to figure out exactly what is happening and why since we cannot reproduce this outside of docker. 

If you want I can close this issue for now then reopen it if I do find more information that is relevant.

**Comment by AndyAyersMS** [comment]
I think that seems reasonable -- if you get back to this, feel free to reopen, as we would like to understand what is happening.

**Comment by hvanbakel** [comment]
Close for now
