### ISSUE TITLE
FileNotFoundException being thrown for assemblies that are in fact present or even when loaded into AppDomain

### ISSUE THREAD

**Issue by gordon-matt** [dotnet/coreclr#18410]
I have a small .NET Core app I am writing which reads all types from an assembly and the XML comments from the corresponding XML comments file. I am facing a problem with loads of **FileNotFoundException**s being thrown when a method, constructor or whatever is using a type that comes from another assembly (example: `SelectList` from `Microsoft.AspNetCore.Mvc.ViewFeatures`). So when trying to get info from say, a `RuntimeMethodInfo`, it will throw an exception like: **Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.**.

I have tried 2 different possible solutions, both of which are not working (hence my asking here for help):

1. Firstly, I ensured all required assemblies were present by using `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`, so I know that all required assemblies are present in one location. This still results in the same thing: lots of **FileNotFoundException**s being thrown, even though those assemblies are in fact present in the same location as the assemblies I am reading.

2. I then thought that perhaps there is some limitation in .NET Core requiring those assemblies to be loaded into the running app... so I iterated through all the assemblies and loaded them with `AppDomain.CurrentDomain.Load` and additionally, I inspected the results from `AppDomain.CurrentDomain.GetAssemblies()` and confirmed that those assemblies were now in fact loaded into the running app... but unfortunately that also did not work... and exact the same errors were thrown.

So what do I do here?

I have extracted the important parts of the app I am writing and put them info a small demo project here: [LoadAssembliesProblem](https://github.com/gordon-matt/LoadAssembliesProblem)
> **NOTE:** There are some comments in the **Program.cs** file as well.

Is this some kind of a bug or am I doing something wrong here?

**Comment by jeffschwMSFT** [comment]
@gordon-matt thanks for reaching out on this issue.  Getting this sort of plug-in model working on .NET Core is not straight forward and we are actively looking into how to make it easier.  If you have other feedback we are interested in hearing.
In this particular case, the missing piece is to add an assembly resolve event so that dependent assembly loads are found.  Code similar to the following got the repro working for me (I added it in the Main method):
System.Runtime.Loader.AssemblyLoadContext.Default.Resolving += (context, name) =>
{
	var path = Path.Combine(examplePath, name.Name + ".dll");
	if (File.Exists(path)) return System.Runtime.Loader.AssemblyLoadContext.Default.LoadFromAssemblyPath(path);
	return null;
};

**Comment by gordon-matt** [comment]
Fantastic! Thank you! The only comment I have really is that I think one of the default places it should look is in the same directory as the assembly that we are reading from. Isn't that how it worked in the older .NET framework (To look in GAC and current folder by default)? Obviously with .NET Core we don't use GAC because everything is a NuGet package now, but surely looking in the same folder as the one we're reading from makes sense, right? Maybe something to keep in mind? If not, feel free to close this issue. Thanks again!

**Comment by jeffschwMSFT** [comment]
Thanks for the feedback @gordon-matt, same directory certainly seems like a good default.  We have several issues active on the broader issue, I will close this one.
