### ISSUE TITLE
StringBuilder should pin during P/Invoking when it has only one chunk

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/coreclr#1842]
As it stands right now, getting a string out of a P/Invoke with StringBuilder requires 4 allocations:
1. Create a new SB with the needed capacity and it does a new char[capacity] {1}
2. On the way to native a new native buffer is created {2} and data is copied if marked as [In]
3. On the way back from native it will call ReplaceBufferInternal, allocating a new char[capacity] {3} and copy the content of the native buffer
4. Calling ToString() then creates another managed allocation {4}

**Comment by JeremyKuhne** [comment]
@stephentoub, @vancem

**Comment by stephentoub** [comment]
> StringBuilder should pin during P/Invoking when it has only one chunk

Such pinning could certainly help when marshaing with Unicode (at least to eliminate (2) and (3) in your list).  When marshaling with Ansi, there are still improvements that could be made, e.g. (3) in your list could be replaced by a copy/encode into the original buffer in the SB if it'll fit.

**Comment by JeremyKuhne** [comment]
Note that marshalling is done with ILWSTRBufferMarshaller and ILCSTRBufferMarshaller.

https://github.com/dotnet/coreclr/blob/bc146608854d1db9cdbcc0b08029a87754e12b49/src/vm/ilmarshalers.cpp#L511

**Comment by jkoritzinsky** [comment]
Closing this since we can't pin the buffer while mantaining compatibility with previous behavior. See conversation in #21785 and #21800.
