### ISSUE TITLE
Make a pass to remove dead strings from mscorrc.rc

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#18420]
Some strings in [mscorrc.rc](https://github.com/dotnet/coreclr/blob/master/src/dlls/mscorrc/mscorrc.rc) seem to be dead. eg
`IDS_SERIALIZATION_NONFREEZABLE_TYPE` `IDS_EE_IJWLOAD_CROSSVERSION_DISALLOWED` `IDS_EE_TORNSTATE` `IDS_CLASSLOAD_SH_SUBCLASS_FINALIZER`

It should not be too hard to write a script that removes any strings whose identifiers only appear in mscorrc\mscorrc.rc and mscorrc\resource.h.

Separately, src\inc\corerror.xml which generates mscorurt.rc and coreerror.h may also be worth looking at. eg : `CLR_OPTSVC_E_CONTROLLER_INTERRUPT` `NGEN_E_EXE_MACHINE_TYPE_MISMATCH`

**Comment by jkotas** [comment]
There are still some that can be cleaned up:

https://github.com/dotnet/coreclr/pull/18535#discussion_r196290773

**Comment by jkotas** [comment]
Would you mind doing more scrub for strings like `VER_E_STACK_P_VALCLASS_OBJREF_VAR` 
 or `VER_E_INITIALIZE_ARRAY_MISSING_TOKEN` ?
