### ISSUE TITLE
Move SSE/SSE2 Set[All]Vector128 helpers to JIT implementation

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#18436]
The current managed implementation of SSE/SSE2 `Set[All]Vector128` helpers have some inefficient codegn (e.g., unnecessary zeroing semantics from `SetScalarVector128`). I will look into moving them to JIT-inside implementation.

cc @CarolEidt @tannergooding

**Comment by tannergooding** [comment]
@fiigii, could you please provide examples of the inefficient codegen (using current master, as there were a number of improvements that just went in).

Given that these are helper intrinsics, they should be implementable in managed code, and if they aren't, then there are likely clear places where we should work to improve codegen instead.
