### ISSUE TITLE
[arm/Ubuntu] crash under GCStress in test b65423.exe

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#18441]
E.g., https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_zapdisable_tst/12/consoleFull#-5931779914b7730ef-150b-4be7-a00f-82ba6c50792b

```
09:41:06                BEGIN EXECUTION
09:41:06                /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_zapdisable_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun b65423.exe
09:41:06                Caught TypeLoadException exception: 100
09:41:06 
               ./b65423.sh: line 244:  3713 Segmentation fault      $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
09:41:06                Expected: 100
09:41:06                Actual: 139
09:41:06                END EXECUTION - FAILED
```

I can repro this about 1/2 the time with just `COMPlus_GCStress=C`. I've never seen it take more than 4 runs in a row to reproduce. I can't reproduce the crash under GDB.

**Comment by BruceForstall** [comment]
cc @janvorli

**Comment by janvorli** [comment]
@BruceForstall I'll look into it.

**Comment by janvorli** [comment]
@BruceForstall I've tried to repro it with the current master. I've ran 1000 iterations of the test on my Odroid XU4 with Ubuntu 18.04 installed and it never failed, so it seems it was fixed by some change that was made since June.

**Comment by BruceForstall** [comment]
I'll go ahead and close it then.

Looks like recent runs have plenty of other issues to look into :-) (https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_zapdisable_tst/39)

**Comment by janvorli** [comment]
@BruceForstall maybe reenable the test for ARM32 again?

**Comment by BruceForstall** [comment]
Well, it looks like it's actually not disabled; the testsFailing.arm.txt file is no longer used, and I don't see it disabled in issues.targets.
