### ISSUE TITLE
Perfcollect issue while executing perf script (kubernetes engine)

### ISSUE THREAD

**Issue by sterchelen** [dotnet/coreclr#18452]
Hi,

First of all my workload is on Kubernetes engine. We run our pods on `container optimized os` from google. With this **OS** it's almost impossible to collect tracing events. So I created a node with ubuntu.
I can run perfcollect with no problem until the execution of the `perf script` statement which tries to output with cpu field. An error is thrown with the following description : 
`'cpu-clock' event do not have CPU attribute set`. 

- I run perfcollect as follow:  `./perfcollect collect test -pid myPID` 

Does anyone has faced this issue ?

Thank you.

**Comment by jkotas** [comment]
cc @brianrob

**Comment by brianrob** [comment]
I have seen this once before, but it's not clear to me why it happens.  It basically means that the CPU number is not available as part of the cpu-clock events.

If you want to work around this you can remove the cpu item from the calls to 'perf script' here: https://github.com/dotnet/corefx-tools/blob/master/src/performance/perfcollect/perfcollect#L1523.

I have filed an issue to see what can be done here: https://github.com/dotnet/corefx-tools/issues/84

**Comment by tommcdon** [comment]
cc @sywhang

**Comment by sywhang** [comment]
This is showing up in more and more places, for example - https://github.com/dotnet/corefx-tools/issues/92. I'll spend some time later this week to investigate why this might be happening.

**Comment by paraspatidar** [comment]
FYI , apart from kubernetes , same behavior is observed on Ubuntu VM on azure.
when running that command manually  : 
` /usr/bin/perf script -i perf.data.merged -f comm,pid,tid,cpu,time,event,ip,sym,dso,trace > perf.data.txt` : 
output : `Samples for 'cpu-clock' event do not have CPU attribute set`

OS : 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

uname -r : **4.18.0-1011-azure**

**Comment by sywhang** [comment]
I opened https://github.com/dotnet/corefx-tools/issues/100 to track this instead of this, since it isn't really a runtime issue but more of the perfcollect script (corefx-tools is where that tool lives).

**Comment by sterchelen** [comment]
Is Microsoft planning to improve the performance metric ?
Like go, integrating in the runtime some tools to extract EASILY cpu by
instructions, memory usage (heap, garbage collection) etc.

**Comment by sywhang** [comment]
On Windows, there is already various ways that you can get do performance analysis such as ETW and PerfView. 

To make this available on all platforms that we support on .NET Core, we are actively working on various runtime support such as EventPipe, runtime performance counters, etc. This project board (https://github.com/dotnet/coreclr/projects/5) tracks the work items that we are actively working on.

If you have specific questions about your scenario, feel free to reach out via issues on GitHub, or to my email (listed on my profile).
