### ISSUE TITLE
dotnet --info only finds same architecture, and lists entries twice when called with absolute path.

### ISSUE THREAD

**Issue by leecow** [dotnet/coreclr#18466]
@markusschaber commented on [Fri May 18 2018](https://github.com/dotnet/core-setup/issues/4154)

## Steps to reproduce
call "dotnet --info" or "C:\Absolute\Path\to\dotnet.exe --info"

See https://gist.github.com/markusschaber/480879b83ec9a22077c6c31e3d7f8346 for full repro.

## Expected  behavior
All installed SDKs and runtimes are listed exactly once.

## Actual behavior
When calling without absolute path, only the SDKs and runtimes of the same architecture (e. G. x86 vs x64) are listed.

When calling with absolute path, it also only finds the SDKs and runtimes of the same architecture, but lists all of them twice.

## Environment data
Microsoft Windows [Version 6.1.7601], 64 bit (x64).

---

@markusschaber commented on [Fri May 18 2018](https://github.com/dotnet/core-setup/issues/4154#issuecomment-390234367)

Remark: I filed this report as recommended on gitter (https://gitter.im/dotnet/coreclr) - I'll be on holiday for the next to weeks, with only limited ability to monitor this issue. Thanks for your patience.

---

@steveharter commented on [Mon May 21 2018](https://github.com/dotnet/core-setup/issues/4154#issuecomment-390657990)

On`C:\Absolute\Path\to\dotnet.exe` showing duplicate entries: if the path exactly matches (casing included) a previous entry, then it is not shown. In the example `c:` was used for the path of `dotnet.exe` while the physical disk is `C:` causing two entries to be found. We can attempt to filter ignoring case on Windows, but on Unix we can't since the file system can be case-sensitive.

---

@markusschaber commented on [Wed May 23 2018](https://github.com/dotnet/core-setup/issues/4154#issuecomment-391433151)

Maybe the pathes could be normalized, like the System.IO.Path.GetFullPath() method does on the classic .NET? This could also resolve symlinks etc...

**Comment by jkotas** [comment]
This issue was moved to dotnet/core-setup#4236

**Comment by markusschaber** [comment]
Ok, thanks! :-)
