### ISSUE TITLE
Profiler rejit can break invariants in jit interface

### ISSUE THREAD

**Issue by davmason** [dotnet/coreclr#18463]
In CEEInfo::ScanToken, we exit early if pModule is System.Private.CoreLib as a perf optimization since we expect that System.Private.CoreLib won't have any external references.

However, profiler rejit can rewrite any IL, including adding external references to IL in System.Private.CoreLib. In our profiler tests I observed the following chain of events.

1.  Profiler rejits System.Private.CoreLib code with calls to an external library that is not yet loaded
2.  When the code is rejitted the external library is not activated because CEEInfoScanToken exits early
3.  On the first call to the rejitted code the method from the external library is jitted, and an assert fires because the module is not activated https://github.com/dotnet/coreclr/blob/6bf04a47badd74646e21e70f4e9267c71b7bfd08/src/vm/prestub.cpp#L1522

The test passes on retail, but I'm afraid there may be some pathological case lurking here that can cause corruption or a crash.

Code for CEEInfo::ScanToken, for reference
 https://github.com/dotnet/coreclr/blob/79b8f94cc52b6b79945074b748508a0b3cbb8be6/src/vm/jitinterface.cpp#L2801-L2884

**Comment by davmason** [comment]
CC @noahfalk

**Comment by RussKeldorph** [comment]
@davmason If you need help from CodeGen let us know.  We try to limit each issue to a single area for reporting purposes, so leaving just diag for now.

**Comment by davmason** [comment]
Looking further, this is not a regression and has always been the case. A test change is responsible for the behavior. Closing this issue.
