### ISSUE TITLE
Use HeapAlloc instead of LocalAlloc on Windows

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/coreclr#1846]
LocalAlloc is depreciated
https://msdn.microsoft.com/en-us/library/windows/desktop/aa366723(v=vs.85).aspx

If we're not using the LMEM_MOVEABLE flag it appears that the overhead isn't too great, but it still does have some. We should consider flipping to Heap\* from Local*.

**Comment by JeremyKuhne** [comment]
@vancem, @jkotas, @stephentoub

**Comment by jkotas** [comment]
LocalAlloc is used in ~2 places, neither of them is on a hot path. This issue is nice-to-have code cleanup - it won't make visible difference.

**Comment by stephentoub** [comment]
@jkotas, doesn't the public Marshal.AllocHGlobal (along with the corresponding StringTo methods) use LocalAlloc?  I'm not sure it would have a measurable impact, but AllocHGlobal is used in many places.

**Comment by jkotas** [comment]
You are right - it is used by AllocHGlobal.

**Comment by mikedn** [comment]
Is this issue still valid? I don't think it's possible to change `AllocHGlobal` to use `HeapAlloc` instead of `LocalAlloc`, someone could have used it to allocate some memory, pass the pointer to native code and then use `LocalFree` in the native code to free the memory.
