### ISSUE TITLE
AssemblyBinding with codeBase and href : Support in CoreClr ?

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/coreclr#18464]
I wanted to solve problem of `How to load an assembly at runtime that is located in a folder that is not the bin folder of the application`. I found this [.Net Framework reference](https://support.microsoft.com/en-us/help/837908/how-to-load-an-assembly-at-runtime-that-is-located-in-a-folder-that-is)

Is `Method 2: Use an application configuration (.config) file with the <codeBase> tags` in above link supported in CoreClr ?

I am not able to get it work on CoreClr.

Here is my `app.config` which generates `<app>.dll.config` :
```
<configuration>
   <runtime>
      <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
         <dependentAssembly>
            <assemblyIdentity name="sft"  culture="neutral" publicKeyToken="8be7d6a1e90327c2"/>
            <codeBase version="1.0.0.0" href="FILE://E:/work/dotnet_projs/sf_sft/sf/bin_appconfig/Debug/netcoreapp2.0/NS/sft.dll"/>
         </dependentAssembly>
      </assemblyBinding>
   </runtime>
</configuration>
```

Here is sample project :

1. sf folder is console app that depends on sft library.
2. sft is strong signed.
3. sf has App.config referring to full location of sft library. Please update it to your local path.
4. hand craft sf.deps.json to remove references of sft.dll and move sft.dll to folder referred in (3).

[assemblybinding_codebase.zip](https://github.com/dotnet/coreclr/files/2101044/assemblybinding_codebase.zip)

**Comment by jkotas** [comment]
There is no first class official tooling support for this.

The `.deps.json` file is equivalent to the binding redirects from .NET Framework. If you add path element to for the assembly in the `.deps.json` file, it should have the same effect as codeBase element in the .NET Framework binding redirects:

```
    "sft/1.0.0": {
...
      "path": "E:/work/dotnet_projs/sf_sft/sf/bin_appconfig/Debug/netcoreapp2.0/NS"
    }
```

**Comment by ashishnegi** [comment]
@jkotas As `.deps.json` is not human editable. Changes to file are reverted with each build. 
When I add App.config to coreclr project, it causes sf.dll.config file generation with exact same content. 

So, it will be great to take this issue as feature request.

**Comment by jeffschwMSFT** [comment]
Can you elaborate on the scenario that you are looking to achieve?  If we provided a way to get early access to resolve this assembly at runtime would that also be a solution?

**Comment by ashishnegi** [comment]
This is in context of #18405 where we are transitioning from .Net Framework to CoreClr and trying to find a solution for GACed assemblies. 

Scenario 1 : 
My `Main` is dependent on `A.dll` which is GACed in .Net Framework. We don't ship it with SDK nupkgs (in both Coreclr and .Net Framework). This is because it contains actual implementation.  We want/need to always have latest version of A.dll running in user's app on Service Fabric platform. In coreclr, the `Main` fails to load as `Types` referred in `Main` function depends on some types present in `A.dll`. CoreClr app crashes as soon as it comes up.

Scenario 2 :
There is a pair of DLLs, `sdk_B.dll` in sdk and `B.dll` in runtime. Here, we were able to load B.dll dynamically using `AssemblyResolver` as it is required lazily. However, today we are not able to ship any new features in `B.dll` and `sdk_B.dll` in coreclr windows and linux. This is because older apps running in cluster have older version of `sdk_B.dll` which does not have new properties accessed by new `B.dll` present in runtime.
This problem does not exist in .Net Framework as sdk_B.dll is GACed.

For scenario 1 we don't have any solution today.
For scenario 2, we can reduce it to scenario 1 by using `ref` folder for `sdk_B.dll` in nupkgs. Then, `sdk_B.dll` is not listed in `<app>.deps.json`. So, if we have a good loading story, then we can always load latest version of both `sdk_B.dll` and `B.dll`.

To actually have a win for us, we need a solution which is transparent to sdk consumers / app developers. User's don't have to add any code in their apps for working with our sdks. 
So, a solution like : `Program's static constructor` called before `Main` is called will *not* work for us. We can't ask users to add an `AssemblyResolver` in `Program's static constructor`.

A solution like [additional deps](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/additional-deps.md) looks promising, where we can have an environment variable `DOTNET_ADDITIONAL_DEPS` which lists a set of globally available dependencies. However, I am having problems getting it to work on a sample app. Please share a sample project that shows the scenario it is trying to solve. I can open another issue for it for better tracking.

**Comment by vitek-karas** [comment]
Would the [startup hook](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/host-startup-hook.md) work for you?
For scenario 1, if the A.dll is not specified as a static dependency of the Main (that is there's no record of it in .deps.json, or the file doesn't exist) then using the resolver described in the startup hook document you should be able to always point it to the latest version. And this approach doesn't require any changes to the user app, just setting environment variable.

**Comment by jkotas** [comment]
@ashishnegi is from service fabric that we have added the startup hook for.
