### ISSUE TITLE
Profiler flag to ignore NGEN doesn't seem to be working

### ISSUE THREAD

**Issue by pjanotti** [dotnet/coreclr#18488]
/cc @noahfalk 

These [comments](https://github.com/dotnet/coreclr/pull/11040#issuecomment-298004449) indicate that the flag `COR_PRF_DISABLE_ALL_NGEN_IMAGES` can be used to force jitting of precompiled methods. However, this is not working for `System.Private.CoreLib.dll` in CoreFx with OpenCover, which does specify the flag and works when the IL version of S.P.C.dll is used instead.

If this is something that can be changed on the short run I may be able to drop some work to restore CI coverage for S.P.C.dll (Windows only).

**Comment by davmason** [comment]
@pjanotti what version of coreclr are you running on? There was a known issue that was fixed with #13021, that is in 2.1 and was ported to 2.0 servicing.

**Comment by pjanotti** [comment]
@davmason I'm running against my local build of coreclr (last commit 16169a8738ab7332a0fc2f2e48937997932798ef), and running the coverage from corefx using the `/p:CoreClrOverridePath` to point to the latest build.

**Comment by davmason** [comment]
@pjanotti how much investigation have you done here? We have profiler tests that should fail if disabling ngen images was broken, so my suspicion is that there is something else going on here, but it's possible something regressed recently.

If you haven't already done this, the easiest way is to run your scenario under a native debugger and verify that `ProfToEEInterfaceImpl::SetEventMask` is called and has `COR_PRF_DISABLE_ALL_NGEN_IMAGES` set.

**Comment by pjanotti** [comment]
@davmason I had debugged OpenCover for other issues and didn't pay attention to this specific flag, let me take a look...

**Comment by pjanotti** [comment]
Sorry for the false alarm. I missed that the PDB matching the crossgen version was named S.P.C.ni.pdb. OpenCover was excluding it because it was failing to find matching PDB - this is compound by the fact that the version of OpenCover in CoreFx only supports WindowsPDB and this file was not being converted to a WindowsPDB.
