### ISSUE TITLE
RegistrationServices support?

### ISSUE THREAD

**Issue by wjk** [dotnet/coreclr#18490]
Following the announcement that Windows Forms and WPF will be ported to .NET Core 3.0, I have a question about some complex (but necessary) COM interop that is currently not possible on .NET Core.

Suppose the following:

* I have an application developed in .NET Core 3 that will be distributed through the Windows Store.
* This application will include shell extensions (such as a preview handler), that are exposed through AppX Packaged COM.
* Due to restrictions inherent to Packaged COM, these COM-visible types must be vended as an out-of-proc server, rather than an in-proc handler.

On .NET Framework, I can do this using [the `RegistrationServices` class](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.registrationservices?view=netframework-4.7.2). However, this class is not available in .NET Core. Furthermore, the docs for the `RegisterTypeForComClients()` method states I should _not_ P/Invoke into `CoRegisterClassObject`, and that doing so is unsupported. However, this seems to be the only way to do out-of-proc COM registration under .NET Core. The wording implies that bad things will happen in the CLR if I try this, so I am leery of using this technique in my .NET Core-based app.

The only workaround I can think of is to use an ATL-based COM server EXE written in C++, that vends COM interfaces that forward their calls to another COM interface implemented in C#. However, due to the lack of a fully-featured Mono-style hosting API for Core, I cannot do so because I have no way of calling C# code other than a static `Main()` method from C++. Therefore, there seems to be no way to implement shell extensions in .NET Core that meet the restrictions mentioned above. Would it be possible for `RegistrationServices` to be (re)introduced to CoreCLR, or, alternatively, to document another technique for accomplishing this? Thanks!

**Comment by jeffschwMSFT** [comment]
Thanks @wjk for raising this scenario.  We are still working through the details of store shipped applications and as we understand more we will keep these types and scenario in mind.  @AaronRobinsonMSFT @luqunl

**Comment by AaronRobinsonMSFT** [comment]
@wjk Support for out-of-proc COM registration in .NET Core is probably not going to make the 3.0 release. Your proposed work around would definitely work though. As an alternative, you could also try mimicing the Running Object Table approach demoed here: https://github.com/AaronRobinsonMSFT/COMInterop/tree/master/OutOfProcDemo. This demo targets .NET Framework, but should work fine for .NET Core providing you supply the Type Library (TLB) rather than expecting the runtime to auto generate one for you.

**Comment by wjk** [comment]
@AaronRobinsonMSFT I never knew you could do that. You learn something new every day. However, AFAIK Packaged COM doesn't use the ROT in this fashion. That being said, with the in-proc COM hosting scaffolding we've added, I can definitely create something that would work. Thanks!
