### ISSUE TITLE
EventSource ActivityIds not present in Release UWP (.NET Native) traces

### ISSUE THREAD

**Issue by mtaron** [dotnet/coreclr#18533]
The attached UWP app ([ActivityIdUwp.zip](https://github.com/dotnet/coreclr/files/2113339/ActivityIdUwp.zip)) has a simple self-describing EventSource.

```
public sealed class TestEventSource : EventSource
{​
public static TestEventSource Log = new TestEventSource();​
​
private TestEventSource()​
 : base("TestEventSource")​
{​
}​
​
private const string Test = "Test";​
public void TestStart() => Write(Test, new EventSourceOptions { Opcode = EventOpcode.Start });​
public void TestStop() => Write(Test, new EventSourceOptions { Opcode = EventOpcode.Stop });​
}
```

When you take a trace of a **debug** build of the app, you will that ActivityIds are automatically computed for the stop and start events.

Event Name | Time MSec | Process Name | Rest
-- | -- | -- | --
TestEventSource/Test/Start | 13,081.954 | ActivityIdUwp (10460) | ThreadID="31,964" ProcessorNumber="1" ActivityID="/#10460/1/1/"
TestEventSource/Test/Stop | 13,237.359 | ActivityIdUwp (10460) | ThreadID="31,964" ProcessorNumber="1" DURATION_MSEC="155.405" ActivityID="/#10460/1/1/"

But when you take a trace of a **release** build of the app, the activities are **not present**.

Event Name | Time MSec | Process Name | Rest
-- | -- | -- | --
TestEventSource/Test/Start | 9,952.188 | ActivityIdUwp (25548) | ThreadID="30,972" ProcessorNumber="0"
TestEventSource/Test/Stop | 9,958.760 | ActivityIdUwp (25548) | ThreadID="30,972" ProcessorNumber="0" DURATION_MSEC="6.573"

@brianrob since this could be related to issue [#18319 Classic EventSources don't work in Release builds using .NET Native (UWP)](https://github.com/dotnet/coreclr/issues/18319).

**Comment by jkotas** [comment]
Duplicate
