### ISSUE TITLE
Adding types to R2R images using profiler metadata emit at ModuleLoadFinished triggers AV

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#18536]
After the ModuleLoadFinished callback returns the runtime attempts to update a type loader cache called the 'AvailableClassHash'. Historically this cache was always created eagerly prior to ModuleLoadFinished being called but ReadyToRun changed the behavior to be lazy. Unfortunately the code path the profiler used to update that cache wasn't changed to account for the lazy creation so it attempts to insert into the non-existent cache and triggers an AV. I stumbled upon the issue accidentally while trying to test something else. My repro was adding a type forwarder to System.Runtime.dll but based on code review I think the issue also applies to adding new TypeDefs.
Currently 'Ready To Run' compilation is used for all framework images except System.Private.CoreLib.dll.

Callstack with the AV:

 	coreclr.dll!ClassLoader::AddExportedTypeHaveLock(Module * pManifestModule, unsigned int cl, AllocMemTracker * pamTracker) Line 4771	C++
 	[Inline Frame] coreclr.dll!ClassLoader::AddExportedTypeDontHaveLock(Module *) Line 4679	C++
	coreclr.dll!Assembly::AddExportedType(unsigned int cl) Line 2176	C++
 	coreclr.dll!Module::NotifyProfilerLoadFinished(HRESULT hr) Line 248	C++
 	coreclr.dll!DomainFile::PostLoadLibrary() Line 1035	C++
 	coreclr.dll!DomainFile::DoIncrementalLoad(FileLoadLevel level) Line 582	C++
 	coreclr.dll!AppDomain::TryIncrementalLoad(DomainFile * pFile, FileLoadLevel workLevel, Wrapper<FileLoadLock *,&DoNothing<FileLoadLock *>,&FileLoadLock::HolderLeave,0,&CompareDefault<FileLoadLock *>,2,1> & lockHolder) Line 5841	C++
 	coreclr.dll!AppDomain::LoadDomainFile(FileLoadLock * pLock, FileLoadLevel targetLevel) Line 5773	C++
 	coreclr.dll!AppDomain::LoadDomainAssemblyInternal(AssemblySpec * pIdentity, PEAssembly * pFile, FileLoadLevel targetLevel) Line 5603	C++
 	coreclr.dll!AppDomain::LoadDomainAssembly(AssemblySpec * pSpec, PEAssembly * pFile, FileLoadLevel targetLevel) Line 5490	C++
 	coreclr.dll!Module::LoadAssembly(AppDomain * pDomain, unsigned int kAssemblyRef, const char * szWinRtTypeNamespace, const char * szWinRtTypeClassName) Line 5613	C++
 	coreclr.dll!Assembly::FindModuleByTypeRef(Module * pModule, unsigned int tkType, Loader::LoadFlag loadFlag, int * pfNoResolutionScope) Line 1274	C++
 	coreclr.dll!ClassLoader::LoadTypeDefOrRefThrowing(Module * pModule, unsigned int typeDefOrRef, ClassLoader::NotFoundAction fNotFoundAction, ClassLoader::PermitUninstantiatedFlag fUninstantiated, unsigned int tokenNotToLoad, ClassLoadLevel level) Line 3003	C++
 	coreclr.dll!ClassLoader::LoadApproxTypeThrowing(Module * pModule, unsigned int tok, SigPointer * pSigInst, const SigTypeContext * pClassTypeContext) Line 3416	C++
 	[Inline Frame] coreclr.dll!ClassLoader::LoadApproxParentThrowing(Module *) Line 3462	C++
 	coreclr.dll!ClassLoader::CreateTypeHandleForTypeDefThrowing(Module * pModule, unsigned int cl, Instantiation inst, AllocMemTracker * pamTracker) Line 11906	C++
 	coreclr.dll!ClassLoader::CreateTypeHandleForTypeKey(TypeKey * pKey, AllocMemTracker * pamTracker) Line 3589	C++
 	coreclr.dll!ClassLoader::LoadTypeHandleForTypeKey_Body(TypeKey * pTypeKey, TypeHandle typeHnd, ClassLoadLevel targetLevel) Line 4325	C++
 	coreclr.dll!ClassLoader::LoadTypeHandleForTypeKey(TypeKey * pTypeKey, TypeHandle typeHnd, ClassLoadLevel targetLevel, const InstantiationContext * pInstContext) Line 4044	C++
 	coreclr.dll!ClassLoader::LoadTypeDefThrowing(Module * pModule, unsigned int typeDef, ClassLoader::NotFoundAction fNotFoundAction, ClassLoader::PermitUninstantiatedFlag fUninstantiated, unsigned int tokenNotToLoad, ClassLoadLevel level, Instantiation * pTargetInstantiation) Line 2887	C++
 	coreclr.dll!ClassLoader::LoadTypeDefOrRefThrowing(Module * pModule, unsigned int typeDefOrRef, ClassLoader::NotFoundAction fNotFoundAction, ClassLoader::PermitUninstantiatedFlag fUninstantiated, unsigned int tokenNotToLoad, ClassLoadLevel level) Line 3065	C++
 	coreclr.dll!Assembly::GetEntryPoint() Line 1918	C++
 	coreclr.dll!Assembly::ExecuteMainMethod(PtrArray * * stringArgs, int) Line 1792	C++
 	coreclr.dll!CorHost2::ExecuteAssembly(unsigned long dwAppDomainId, const wchar_t * pwzAssemblyPath, int argc, const wchar_t * * argv, unsigned long * pReturnValue) Line 491	C++
 	coreclr.dll!coreclr_execute_assembly(void * hostHandle, unsigned int domainId, int argc, const char * * argv, const char * managedAssemblyPath, unsigned int * exitCode) Line 407	C++

**Comment by noahfalk** [comment]
In order to unblock myself locally I created a partial fix which can be found at: https://github.com/noahfalk/coreclr/tree/fix_r2r_export_master 
I'm not actively continuing work here however, anyone can pick up where I left off.

**Comment by sywhang** [comment]
Thanks @noahfalk, I'll take a look at this

**Comment by davmason** [comment]
Fixed with #23202
