### ISSUE TITLE
[Linux/arm64]  GitHub_18497 fails with assert

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#18544]
```
corerun GitHub_18497.exe

Assert failure(PID 38848 [0x000097c0], Thread: 38848 [0x97c0]): 
Assertion failed 'varDsc->lvFieldCnt == 1' in 'GitHub_18497:Sum(struct):struct' (IL size 18)

    File: src/jit/lclvars.cpp Line: 2020
```

@Caroleidt To track new failure introduced in #18499

**Comment by CarolEidt** [comment]
This is a pre-existing bug exposed by this new test.
I believe that the problem is that the struct promotion logic (where the assert is firing) is not considering the implicitByRef (passed by reference) case.
