### ISSUE TITLE
GlobalizationMode.Invariant's PunycodeDecode repeatedly calling StringBuilder.ToString

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#18545]
See all of these calls to `output.ToString()` including two in a loop, and `output` isn't changing in this region:
https://github.com/dotnet/coreclr/blob/473d9b09c7e000480f41021c94fbffeae27cb179/src/System.Private.CoreLib/shared/System/Globalization/IdnMapping.cs#L776-L806

Seems like this should either a) create the string once rather than repeatedly creating it, or b) retrieve the char from the StringBuilder to test it rather than using a string and an index.  In other words, worst case we should be allocating one string here, best case zero.  Given the potential expense of indexing into a StringBuilder, I'm not sure which ends up being faster.

cc: @tarekgh, @krwq

**Comment by tarekgh** [comment]
I'll take a look at this one.
