### ISSUE TITLE
Pointer to generic Type are not allowed.

### ISSUE THREAD

**Issue by Neo-Ciber94** [dotnet/coreclr#18547]
**Is impossible to declare pointers to generic types, .NET 7.3**  

        public struct Unmanaged<T> where T: unmanaged { }

        public unsafe struct SomeCoolAndSexyStruct<T> where T: unmanaged
        {
                public Unmanaged<T>* _pointer; //Not allowed
        }

**Comment by jkotas** [comment]
This is C# language limitation.

**Comment by jkotas** [comment]
This issue was moved to dotnet/csharplang#1649
