### ISSUE TITLE
SSE2 Insert (pinsrw) has incorrect encoding on containment form

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#18553]
SSE2 `Insert` (instruction `pinsrw`) has incorrect encoding on containment form:
```asm
;;; Vector128<short> v = Sse2.Insert(baseVector, array[4], 7);
;;; compiled to

C46179C6620E07   vpinsrw  xmm12, xmm0, xmmword ptr [rdx+14], 7 ;;; VEX encoding
66440FC6620E07   pinsrw   xmm12, xmmword ptr [rdx+14], 7       ;;; non-VEX encoding
```
However, the correct encoding should be
```asm
C46179C4620E07  vpinsrw  xmm12, xmm0, xmmword ptr [rdx+14], 7 ;;; VEX encoding
66440FC4620E07  pinsrw   xmm12, xmmword ptr [rdx+14], 7       ;;; non-VEX encoding
```

Note: the JIT dump is incorrect, the above `xmmword ptr` should read `word ptr `.

SSE4.1 Insert works fine, and this bug seems introduced from the recent containment change.

I will look into this issue. cc @CarolEidt @tannergooding

**Comment by tannergooding** [comment]
@fiigii, it is probably one if the "Does the constant fit in a byte" checks. For example: https://github.com/dotnet/coreclr/blob/master/src/jit/emitxarch.cpp#L10067

There are three others as well (just search for `code |= 2`)

**Comment by fiigii** [comment]
@tannergooding Thanks! I will investigate it later.

**Comment by tannergooding** [comment]
@fiigii, do you know why the tests aren't failing? Is this just not a covered scenario since the SSE2 tests haven't been moved to the templates yet?

**Comment by fiigii** [comment]
Because the current test template only covers containment for vector types, but SSE2 `pinsrw` requires a `short` on the last operand 
```asm
PINSRW xmm, r32/m16, imm8
```
