### ISSUE TITLE
there seems to be a way to accelerate GC of objects with finalizer

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#1856]
When GC of generation 1 or 2 finishes, all garbage objects with finalizer should be moved to heap zone of generation 0. Thus, these objects would be collected next generation 0 GC after their finalizers are called.

**Comment by ygc369** [comment]
What do you think about this idea?

**Comment by ygc369** [comment]
I think this idea should be considered.

**Comment by ygc369** [comment]
Nobody is interested in this?

**Comment by vancem** [comment]
It is very hard to see whether this change would have interesting positive effect on performance.   It might, but it might not.   Generally speaking we expect finalizable objects to always be a small fraction of the total, and thus any change to improve them is likely to have a very small effect.   

Ideas for improvements are considerably more valuable if they have (ideally real world) data that argues that the improvement is very significant.    

Note that even with this data, there still is a finite amount of resources.    We have not even shipped our  V1.0.0 release, so there are many work items that this needs to compete with.
