### ISSUE TITLE
Compatibility with .Net Framework : static constuctor in Program called before Main is invoked

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/coreclr#18566]
The static constructor of `Program` in both coreclr and .net framework are called before `Main` is invoked, if everything is simple.

In our case, we have a Type being referred in `Main` which is loaded dynamically by an `AssemblyResolver` registered in `Program's static constructor`. Static constructor in .Net Framework is called successfully before `Main` is invoked. So, we get a change to register our `AssemblyResolver`. However, in CoreClr, the app crashes before `static` constructor of `Program` is called.

```cs
using System;
using System.IO;

namespace sf
{
    class Program
    {
        static Program()
        {
            Console.WriteLine("In static constructor of Program");
        }

        static void Main(string[] args)
        {
            Console.WriteLine("In Main.");
            X x = new X();
            x.Foo();
            Console.ReadLine();
        }
    }
}
```

Where `X` class come from another `library`.

Build CoreClr and Fullclr projects with above file and a library that has `class X` with `Foo` function.

1. Delete `library.dll` files from `bin\Debug` in fullclr. we get :
```
bin\Debug>ConsoleApp1.exe
In static constructor of Program

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'sft, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at sf.Program.Main(String[] args)
^C
```

2. Delete `library.dll` files from `bin\Debug\netcoreapp2.0` in coreclr. Edit `<app>.deps.json` to remove entry for `library.dll`.

```
bin\Debug\netcoreapp2.0>dotnet sf.dll

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'sft, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8be7d6a1e90327c2'. The system cannot find the file specified.
   at sf.Program.Main(String[] args)

```
My library name is: `sft.dll` here.

Sample projects : coreclr code under `sf` folder. .net framework code under `fullclr` folder.
[sf_sft.zip](https://github.com/dotnet/coreclr/files/2118619/sf_sft.zip)

**Comment by jkotas** [comment]
The timing of static constructors in .NET Framework is unpredictable, depends on multiple factors. For example, if you `ngen install ConsoleApp1.exe` in .NET Framework, the timing will change to the .NET Core one.

We have changed the timing in .NET Core to be consistent and predictable.

The underlying details have been discussed in https://github.com/dotnet/coreclr/issues/17981

**Comment by ashishnegi** [comment]
Good to know that we are moving towards consistency in CoreClr.
