### ISSUE TITLE
DateTime.ToString("d") formats differently on Mac OS and Windows

### ISSUE THREAD

**Issue by woodne** [dotnet/coreclr#18579]
When I have a DateTime that I call `ToString("d", CultureInfo.CreateSpecificCulture("en-US"))` I would expect that the formatted string would be the same on different platforms, but for a date "9/25/2017" it produces 9/25/17 on MacOS and 9/25/2017 on windows.

**Comment by jkotas** [comment]
The culture-specific formatting uses the format configured in the OS. MacOS and Windows are configured differently by default in this case.

This is duplicate of https://github.com/dotnet/coreclr/issues/16960 . Check the discussion in this issue for more details.

**Comment by woodne** [comment]
Thanks! Sorry I tried searching but could not find this.
