### ISSUE TITLE
Possible null pointer access

### ISSUE THREAD

**Issue by alexandrnikitin** [dotnet/coreclr#1860]
I'm reviewing the GC code and encountered the following code in [gc.cpp][gc.cpp] on line 34464:

```cpp
...
size_t
GCHeap::GarbageCollectGeneration (unsigned int gen, gc_reason reason)
{
    dprintf (2, ("triggered a GC!"));

#ifdef MULTIPLE_HEAPS
    gc_heap* hpt = gc_heap::g_heaps[0];
#else
    gc_heap* hpt = 0;
#endif //MULTIPLE_HEAPS
    Thread* current_thread = GetThread();
    BOOL cooperative_mode = TRUE;
    dynamic_data* dd = hpt->dynamic_data_of (gen);
...
```

If `MULTIPLE_HEAPS` isn't defined then `hpt` is null. But we access it a few lines latter.

  [gc.cpp]: https://raw.githubusercontent.com/dotnet/coreclr/master/src/gc/gc.cpp

**Comment by janvorli** [comment]
See #1519

**Comment by alexandrnikitin** [comment]
Ok, closed. Here's more detailed explanation:
If we don't define `MULTIPLE_HEAPS` we define `PER_HEAP` as static
```cpp
#ifdef MULTIPLE_HEAPS
#define PER_HEAP
#else //MULTIPLE_HEAPS
#define PER_HEAP static
#endif // MULTIPLE_HEAPS
```
And in `gc_heap` class `dynamic_data_table` becomes static:
```cpp
PER_HEAP
dynamic_data dynamic_data_table [NUMBERGENERATIONS+1];
```
Taking into account that we inline the `dynamic_data_of` method:
```cpp
inline
dynamic_data* gc_heap::dynamic_data_of (int gen_number)
{
    return &dynamic_data_table [ gen_number ];
}
```
everything works...
:see_no_evil:


Guys, how do you work on that codebase?????
