### ISSUE TITLE
Q: Is `Activator.CreateInstance(typeFromDynamicModule)` safe to call while same dynamic module is being mutated?

### ISSUE THREAD

**Issue by stakx** [dotnet/coreclr#18635]
A few people and I have been trying to track down a somewhat elusive multi-threading issue in Castle DynamicProxy and/or the runtime (https://github.com/castleproject/Core/issues/193). We're getting to the point where we could use some expert knowledge from the CLR-savvy folks.

DynamicProxy performs lots of dynamic type generation using System.Reflection.Emit. The code that uses `ModuleBuilder`, `TypeBuilder` etc. to generate the types is guarded with an exclusive lock that only one thread may enter at a time. (This because, as far as we know, System.Reflection.Emit does not give any official thread-safety guarantees.)

However, the `Type`s returned by `TypeBuilder.CreateType()` are instantiated using `Activator.CreateInstance` *outside* of any lock.

We've noticed that our elusive threading issue appears to occur significantly less often if `Activator.CreateInstance` is called while a lock is being held that prevents the dynamic module from being modified.

So we're wondering: Is a call to `Activator.CreateInstance(type)` officially (thread-) safe if the `ModuleBuilder` that contains `type` is being mutated by concurrent System.Reflection.Emit calls?

/cc @BrunoJuchli, @TimLovellSmith, @AtsushiKan

**Comment by BrunoJuchli** [comment]
Note: the 'type' and any of it's references are not modified while `Activator.CreateInstance(type)` is called. However, other types are concurrently emitted to the same Module.

**Comment by jkotas** [comment]
> Is a call to `Activator.CreateInstance(type)` officially (thread-) safe if the `ModuleBuilder` that contains type is being mutated by concurrent `System.Reflection.Emit` calls?

Yes, it is how it is supposed to work.

**Comment by stakx** [comment]
@jkotas, thanks for the fast response, great to hear! I'm assuming it would then also be safe to invoke not-yet-JIT-ted methods on the type while other additional types are emitted into the dynamic module?

**Comment by jkotas** [comment]
Right.

**Comment by stakx** [comment]
Closing this for now, as our question has been answered. Thank you!
