### ISSUE TITLE
Enable FEATURE_GDBJIT on default builds

### ISSUE THREAD

**Issue by carlokok** [dotnet/coreclr#18632]
On Linux/OSX it would be very nice if the default distributing has FEATURE_GDBJIT enabled so the debugging experience doesn't require manual building of SOS to have *some* debugging experience (presuming one sets the envvar needed for this)

**Comment by AaronRobinsonMSFT** [comment]
@mikem8361 regarding building SOS.

**Comment by mikem8361** [comment]
Enabling FEATURE_GDBJIT in release/shipped builds costs to much in memory and perf.  Even to enable it for debug or checked builds (which we don't ship) would probably cost too much.

We are working on making lldb/SOS easier to setup and config, better tested, runtime version independent and the binaries (even for OSX) available for all our platforms and distros.  And document how to install or build lldb for your distro.  It is currently a work in progress but you can see https://github.com/dotnet/diagnostics for the current state. It is much easier now to get the lldb plugin and SOS built for OSX/Xcode's version of lldb.  Just clone the repo, built it and you will have the OSX bits  you need.
