### ISSUE TITLE
comcallablewrapper has very misleading commentary

### ISSUE THREAD

**Issue by riverar** [dotnet/coreclr#18630]
As part of the gutting of FEATURE_CORECLR ifdefs (https://github.com/dotnet/coreclr/commit/54891e0650e69f08832f75a40dc102efc6115d38#diff-ade4b3276f9a170febb781e66ab30039), appx-specific functionality got removed but this comment (https://github.com/dotnet/coreclr/blob/master/src/vm/comcallablewrapper.cpp#L1927-L1937) wasn't updated, sending me on a wild goose chase for a few hours.

Was going to submit a PR but guidelines indicate bar wouldn't be met. I disagree, hence this issue. Hope we can all agree this comment should be edited.

cc: @danmosemsft

**Comment by AaronRobinsonMSFT** [comment]
@riverar Feel free to submit a PR with proposed changes. @luqunl and I are actively working in this area and would appreciate hearing comments and concerns.

cc: @jeffschwMSFT

**Comment by AaronRobinsonMSFT** [comment]
@riverar Merged - Thanks!
