### ISSUE TITLE
Simplifying the enumerator code: yield enumerate myList;

### ISSUE THREAD

**Issue by LunarWhisper** [dotnet/coreclr#18633]
Each time, when faced with a similar code, it makes me sad:

```csharp
private IEnumerable<Guid> EnumerateIDs()
{
    yield return Guid.Empty;

    foreach (Guid id in this.PrimaryIDs)
        yield return id;

    foreach (Guid id in this.SecondaryIDs)
        yield return id;
}
```

I think we can easily simplify it by adding syntactic sugar:
```csharp
private IEnumerable<Guid> EnumerateIDs()
{
    yield return Guid.Empty;

    yield enumerate this.PrimaryIDs;
    yield enumerate this.SecondaryIDs;
}
```

**Comment by jkotas** [comment]
You are proposing a new C# language feature. Please open in https://github.com/dotnet/csharplang repo. There is a good chance a similar proposal has been opened there already.

**Comment by EgorBo** [comment]
E.g. https://github.com/dotnet/csharplang/issues/378
