### ISSUE TITLE
Community Slack engagement story needs work

### ISSUE THREAD

**Issue by riverar** [dotnet/coreclr#18643]
*[I'm writing this in story form as I believe it's important you look at this through the proper lens]*

# Story time
So, put on your new user hat. 🤠 

You want to engage with the CoreCLR community and figure out why you can't debug CoreCLR. You hit the engagement documentation (https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/IssuesFeedbackEngagement.md).

The CoreCLR repository documentation reels you in with a "chat with the community" heading and a badge that shows there's 6,517 registered users on Slack. Wow! Sounds great! You click this badge.

Now you're whisked away to some random blog (tattoocoder) where it indicates 7,091 users. Hm okay whatever. I'm daring, I'll type my email into this random blog widget.

You continue through Slack's awful user flow where it notifies you that you're joining the .NET Slack. Great! But hosted at... aspnetcore.slack.com. You don't care about aspnet. But you continue anyway.

You join the slack and get plopped into the #general channel with no further guidance. You go through the Slack tutorial for the 100th time and remember there are channels. You join the CoreCLR channel and there's only 286 people. You begin to question if everything you did was for nothing ... 

And end scene. 🦑 

# Suggestions

* Make it clear the Slack is or isn't official (it's not clear)
* Set some expectations -- do core maintainers hang out in here? should I use Slack over Gitter for certain scenarios?
* Rename the Slack name/URLs to make sense (https://get.slack.help/hc/en-us/articles/201663443-Change-your-workspace-or-org-name-and-URL)
* Welcome users with a map ([perhaps with custom code](https://api.slack.com/best-practices/blueprints/new-user-notification) or a [simple bot](https://greetbot.io/))

# Dog Tax

![image](https://user-images.githubusercontent.com/475132/41888633-5501900a-78bb-11e8-803a-b66bd988117d.png)

cc: @spboyer

**Comment by PureKrome** [comment]
dotnet.slack.com is taken :(

![](https://media.giphy.com/media/MwtjauC5lamQM/giphy.gif)

**Comment by AaronRobinsonMSFT** [comment]
@riverar You're not wrong

Looks like that link was added by @vancem over two years ago. @jkotas does the link in question still reflect reality?

**Comment by jkotas** [comment]
This link was added by https://github.com/dotnet/corefx/pull/8566 first and then same change was made in https://github.com/dotnet/coreclr/pull/4983 and https://github.com/dotnet/cli/pull/3046.

I have clicked through it and I agree that it is a bad experience. I think we should delete the link.

Also, I do not think we need to have multiple official chat channels. I like that aspnet settlet on gitter:  https://github.com/aspnet/Home/pull/1444#issuecomment-240499207

**Comment by jkotas** [comment]
cc: @terrajobst, @richlander

**Comment by terrajobst** [comment]
Yes, using the Gitter link makes a lot more sense. Thanks changing it @jkotas!

@riverar I'll assume this addresses your concerns and I'm closing this now. Feel free to reopen it!

**Comment by spboyer** [comment]
@riverar - all great concerns. Actually, @benaadams and I had this conversation when the Slack channel was initially created and fell upon many challenges when trying to rename it to something that was more related to .NET Core. However -> "squatters".

Some of the points you make, user flow, channels etc or just a "Slack thing" and getting used to how the thing works. Bouncing from Slack, Skype, Teams, Gitter, whatever conversation thing a team wants is a pain at times and on top of that remembering that we must adhere to ways of the force for each platform.

Gitter makes more sense per repo, Slack makes sense for a community. My 2 cents.
