### ISSUE TITLE
Array bound check performance regression between .NET Core 2.0 and 2.1

### ISSUE THREAD

**Issue by lahma** [dotnet/coreclr#18647]
I noticed this while running [Jint's](https://github.com/sebastienros/jint) benchmark suite with .NET Core 2.1, some of the benchmarks looked better but some worse for my surprise. I was able to narrow it down to probably how bounds checking happens depending whether you use index >= Length vs index < Length.

The performance difference is noticeable (> 20%) and the original code tried to communicate intent better (JavaScript can surprisingly do all kinds of indexing). The example is a a bit simplified from original where the idea is to jump between array and dictionary based whether the data is sparse or not. I did already fix the issue by changing the indexing to happen as more conventional less-than - see comment.

[Here's the repro code](https://gist.github.com/lahma/b8b3f1a5e324fdbf11f570fd26589f73) and comments about performance difference.

**Comment by gfoidl** [comment]
The root for this problem is https://github.com/dotnet/coreclr/issues/15671
So you have to fetch `_dense` into a local, so that the bound checks can be elminated -- see also https://github.com/dotnet/corefx/pull/26086#discussion_r159065422 (for context about the above issue).

BTW: use
```c#
if ((uint)index >= (uint)dense.Length)
```
to eliminate the checks.

**Comment by lahma** [comment]
@gfoidl thanks for the quick response. Good to know that this issue is known and addressed already. I tried the uint cast for length with the index < dense.Length and it did indeed eliminate more checking. Thank you for the tip!
