### ISSUE TITLE
Websockets: Server doesnt realize when a client is disconnected and keeps connection as open

### ISSUE THREAD

**Issue by agonzalezm** [dotnet/coreclr#18646]
I have websocket server/clientapp  that works perfectly in net core 2.0 but after updating project to net core 2.1 the server doesnt realize when a client is disconnected so it keeps waiting for ever, while debugging this code although client got disconnected the server reports the websocket connection as OPEN. Any idea what has changed or how to make this work in 2.1?

```
System.Net.WebSockets;


var ct = context.RequestAborted;
WebSocketReceiveResult result = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), ct);
while (!result.CloseStatus.HasValue)
{
   buffer = new byte[receiveChunkSize];
   result = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), ct);
   ManageMessage(jobId, buffer);
   buffer = null;
}
await webSocket.CloseAsync(result.CloseStatus.Value, result.CloseStatusDescription, ct);
```

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#30668
