### ISSUE TITLE
Allow setting COR_PRF_ENABLE_REJIT after runtime startup

### ISSUE THREAD

**Issue by mjsabby** [dotnet/coreclr#18641]
It would useful to allow ReJIT on attach instead of it being restricted to scenarios where the profiler is loaded at startup.

This can be solved either such that only methods jitted after ReJIT is turned on are rejittable or make all jit compiled methods rejittable from the beginning of process startup. The former can be confusing but is probably easier to implement in the existing runtime with some error checking to fail on methods that are not rejittable.

If we go with the latter implementation, calling SetEventMask with `COR_PRF_ENABLE_REJIT` will probably be a no-op and return success so that profilers don't have to change.

**Comment by davmason** [comment]
This is allowed now in #19054
