### ISSUE TITLE
Remove Conditional Compilation of Generated DotNETRuntimeEventSource.cs

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#18661]
Build scripts and/or project files need to be fixed so that the conditional compilation of DotNETRuntimeEventSource.cs can be replaced with an unconditional compilation.  Otherwise, we risk ending up with a build System.Private.CoreLib.dll that doesn't contain the contents of DotNETRuntimeEventSource.cs.

The line of interest is here: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/System.Private.CoreLib.csproj#L446.

**Comment by brianrob** [comment]
Looking back at the reason I added this, it was because in the official build, sync.sh was failing because DotNETRuntimeEventSource.cs was missing.  Sync.sh is called before the build starts and so it's expected that the file is not there.

The failure is isolated to Unix, and it appears to be due to an interaction between run.exe and the shell.  Run.exe executes the msbuild sync task by running the following:

```
~/src/coreclr/Tools/msbuild.sh /nologo /verbosity:minimal  /flp:v=detailed;LogFile=sync.log /t:Sync /p:RestoreDuringBuild=true  ./build.proj
```

Bash interprets this as two commands being provided together:
```
~/src/coreclr/Tools/msbuild.sh /nologo /verbosity:minimal  /flp:v=detailed
LogFile=sync.log /t:Sync /p:RestoreDuringBuild=true  ./build.proj
```

I'm not sure why run.exe doesn't complain, but if you run this line directly in bash it will run the first command, which is the moral equivalent of ```msbuild``` which does a build of build.proj.  build.proj contains a reference to System.Private.CoreLib.csproj which is why the corelib build occurs (and fails).  Then, the second command is run - LogFile=sync.log is interpreted by bash as setting an environment variable, and then bash attempts to run /t:Sync which of course isn't a valid command.

The solution is to put quotes around ```/flp:v=detailed;LogFile=sync.log``` at which point the whole line is interpreted as one command.

@jkotas, do you know where the source code for run.exe is located?  I would like to see if the fix is easy enough.

**Comment by AaronRobinsonMSFT** [comment]
@brianrob The `run.exe` tool comes out of the build tools repo: https://github.com/dotnet/buildtools/blob/master/src/Run

**Comment by brianrob** [comment]
Thanks @AaronRobinsonMSFT.
