### ISSUE TITLE
Add additional PInvoke tests to coreclr

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/coreclr#18675]
The PInvoke scenario surface area is large and the coreclr repo doesn't have coverage that would be considered adequate. Missing areas (not exhaustive):

- Arrays
- SafeHandles
- CriticalHandles
- DllImport searching with UNICODE characters

**Comment by jkoritzinsky** [comment]
Some of these tests are currently in-PR awaiting review:

- Array: #19266 
- SafeHandles: #19330 
- CriticalHandles: #19297 

I'll take a deeper look at the DllImport Unicode scenarios.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Any more work here?

**Comment by jkoritzinsky** [comment]
I think we've covered everything between what's merged in and what's in PR.
