### ISSUE TITLE
Option additionalProbingPaths is not working

### ISSUE THREAD

**Issue by mkSanalogic** [dotnet/coreclr#18683]
According to documentation, this parameter should allow the placement of libraries in a different location, for example a subdirectory. However, the parameter fails to work as advised.

I'm running into the same behavior explained in this posting on StackOverflow: 
https://stackoverflow.com/questions/48650348/additionalprobingpaths-not-respected-after-dotnet-publish

Basically, if you put the additional path into the json file, it is ignored and moving a library to the new location will produce an error:
"An assembly specified in the application dependencies manifest ([referencedLibrary].deps.json) was not found"

This either does not work at all or it's documentation needs to be greatly improved.

**Comment by mkSanalogic** [comment]
I've attached a very simple example app demonstrating the issue. The output in the debug directory of SimpleTestApp is configured so it should find the library which has been moved to the lib subdirectory, but an error is produced instead.

[SimpleTestApp.zip](https://github.com/dotnet/coreclr/files/2144161/SimpleTestApp.zip)

**Comment by jkotas** [comment]
cc @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
For better or worse this feature does work, but it may not be intuitive.  Let me explain how you can modify this project to have it work.
First how I diagnosed the failed load.  I set COREHOST_TRACE=1 and validated where the host looked when additionalProbingPaths was set...

Processing TPA for deps entry [SimpleTestLib, 1.0.0, SimpleTestLib.dll]
  Considering entry [SimpleTestLib/1.0.0/SimpleTestLib.dll], probe dir [], probe fx level:0, entry fx level:0
    Local path query did not exist C:\temp\repro\SimpleTestApp\SimpleTestApp\SimpleTestApp\bin\Debug\netcoreapp2.1\SimpleTestLib.dll
    Skipping... not found in deps dir 'C:\temp\repro\SimpleTestApp\SimpleTestApp\SimpleTestApp\bin\Debug\netcoreapp2.1\'
    Skipping... not found in probe dir ''
  Considering entry [SimpleTestLib/1.0.0/SimpleTestLib.dll], probe dir [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.1], probe fx level:1, entry fx level:0
    Skipping... not found in deps json.
    Skipping... not found in probe dir 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.1'
  Considering entry [SimpleTestLib/1.0.0/SimpleTestLib.dll], probe dir [C:\temp\repro\SimpleTestApp\SimpleTestApp\SimpleTestApp\bin\Debug\netcoreapp2.1\lib], probe fx level:-1, entry fx level:0
    Relative path query did not exist C:\temp\repro\SimpleTestApp\SimpleTestApp\SimpleTestApp\bin\Debug\netcoreapp2.1\lib\SimpleTestLib\1.0.0\SimpleTestLib.dll
    Skipping... not found in probe dir 'C:\temp\repro\SimpleTestApp\SimpleTestApp\SimpleTestApp\bin\Debug\netcoreapp2.1\lib'

Note that it was probing for SimpleTestLib.dll in lib\SimpleTestLib\1.0.0\SimpleTestLib.dll.

When I moved the assembly into that directory it worked as expected.  Another possible way to find this assembly in a subdirectory would be by subscribing to System.Runtime.Loader.AssemblyLoadContext.Resolve.  In this callback you could probe for the assembly and load via AssemblyLoadContext.LoadFrom*.  I hope that helps.

**Comment by mkSanalogic** [comment]
Hi Jeff,
I apologize for my late reply - I've been away over an extended weekend.

Back on thursday I found some hint about this when somebody commented that in dotnet core the probing directory is supposed to be set up like a nuget repository, but this was shortly before I left and I couldn't get it to run quickly. I presume I failed setting up all the directories properly.

Anyway, coming from dotnet framework, this is supposed to be the replacement for the probing directory you can define there in app.config, right? If so, I maintain my point that this does not work as one could reasonably expect it to work. 
After all, just publishing an app does no such thing as establishing a structure in which libraries are placed in subdirectories with proper versioning either. All it does is dump all files in one directory.

It's - in my opinion - unreasonable to expect the user of the probing directory command to fabricate a nuget-like structure on his own - this most likely makes using the option more trouble than it's worth in all but a few edge cases. 
What the option should provide is - just as it did in dotnet framework - define an alternative directory where the application will look for it's libraries. Not sorted in a structure it doesn't expect libraries to be sorted in at the standard location, just a flat location and that's it.

With that expectation in mind, the feature in it's current implementation does indeed not work properly.

Since the intention of using the probing dir in the first place was to move dozens of dlls out of the way for a command line application deployed to linux, I'm afraid your workaround solution sounds a little too complicated for my use case, but nonetheless, I thank you very much for your time and consideration, very much appreciated.

**Comment by jeffschwMSFT** [comment]
Your point is well taken.  We are re-evaluating the overall loading/probing space and we will keep your feedback in mind.  Thanks

**Comment by mkSanalogic** [comment]
Fair enough I guess. Thanks again for your efforts.
