### ISSUE TITLE
Proposal: Re-introduce support for multi-module assemblies

### ISSUE THREAD

**Issue by mjsabby** [dotnet/coreclr#18692]
Is there a technical reason or downside to having multi-module assemblies in CoreCLR?

https://github.com/dotnet/coreclr/commit/1aa7d6b8796f7e28a63162117c5bb16a207a472b removed the code associated with FEATURE_MULTIMODULE_ASSEMBLIES since it was never defined.

If there isn't, I'd like to propose we bring this feature back.

**Comment by jkotas** [comment]
Nothing in end-to-end .NET Core support it. Expensive to bring back in supported way.

**Comment by markusschaber** [comment]
I don't know about your use-case, but maybe the .NET Linker / Mono Linker can help in some cases?
