### ISSUE TITLE
Issue with large arrays

### ISSUE THREAD

**Issue by ddobric** [dotnet/coreclr#18709]
Have some Machine Learning code, which works on .NET and allocates a large array double[65536,65536].
To make this working, I had to enable gcAllowVeryLargeObjects .

How to do the same in .NET Core?

Right now, getting following exception:
System.OutOfMemoryException: 'Array dimensions exceeded supported range.'

Thanks

**Comment by jkotas** [comment]
`gcAllowVeryLargeObjects` is enabled by default in .NET Core (enabled by default by https://github.com/dotnet/coreclr/pull/8853).

`gcAllowVeryLargeObjects` has still limit of `UInt32.MaxValue` elements in the array: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element#remarks . `double[65536,65536]` is over this limit.

**Comment by AaronRobinsonMSFT** [comment]
@ddobric Your question seems to imply that you were able to get this to work on .NET Framework. Is that true? The link @jkotas refers to applies to both CoreCLR _and_ .NET Framework so it would be odd if setting that flag allowed the referenced allocation on .NET Framework.

**Comment by Maoni0** [comment]
@ddobric are you still pursuing this? if so can you please answer @AaronRobinsonMSFT's question to let us know whether this worked on .NET or not? otherwise let's close the issue.
