### ISSUE TITLE
[RC1 blocker] DiagnosticDescriptor contructor creating instances with emtpy or default properies on coreclr on Linux/Darwin

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/coreclr#1871]
With the newest coreclr build 23426 The `DiagnosticDescriptor` constructor at https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/Compilers/Core/Portable/Diagnostic/DiagnosticDescriptor.cs. The properties of the instance created are null or deafult values.

see https://github.com/dotnet/roslyn/issues/6326 for repro example.

**Comment by JunTaoLuo** [comment]
cc @muratg @pakrym

**Comment by muratg** [comment]
@joshfree Can you please triage?  

Thanks,
Murat

**Comment by pakrym** [comment]
Repro. On coreclr 23426 first `Console.WriteLine` doesn't output anything.

`program.cs`

```
using System;
using System.IO;
using Microsoft.CodeAnalysis;


namespace A
{
    public class Program
    {
        public static void Main()
        {
            Console.WriteLine(Diagnostic.Create(new DiagnosticDescriptor(
                "DN1001",
                title: "title",
                messageFormat: "msg",
                category: "cat",
                defaultSeverity: DiagnosticSeverity.Warning,
                isEnabledByDefault: true), null).Id);


            Console.WriteLine(Diagnostic.Create(
                "DNX1",
                "cat",
                "msg",
                DiagnosticSeverity.Warning,
                DiagnosticSeverity.Warning,
                true,
                4).Id);
                }
    }
}
```

`project.json`

```
{
  "dependencies": {
    "Microsoft.CodeAnalysis.CSharp": "1.1.0-rc1-*"
  },
  "frameworks": {
    "dnxcore50": {
      "dependencies": {
        "System.Console": "4.0.0-beta-*",
        "System.IO": "4.0.11-*"
      }
    }
  }
}
```

**Comment by joshfree** [comment]
This should be fixed in the -beta-23430 packages on http://myget.org/gallery/dotnet-core-rel.  @JunTaoLuo @LLITCHEV can you verify?

**Comment by JunTaoLuo** [comment]
@pakrym is working on verification in https://github.com/aspnet/dnx/issues/3104

**Comment by LLITCHEV** [comment]
Verified fixed by @pakrym.
