### ISSUE TITLE
Strange codegen with structure fields accesses

### ISSUE THREAD

**Issue by voinokin** [dotnet/coreclr#18710]
The C# repro code below shows non-uniformity in .NET Core 2.1 JIT behavior regarding (de)optimization of memory accesses having potential side effects. In short, test methods attempt to access all three fields of the structure instance of which only two first values are used.

```
[StructLayout(LayoutKind.Sequential)]
struct VT
{
    public static readonly int Size = Marshal.SizeOf<VT>();

    public int F1, F2, F3;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Get(out int v1, out int v2, out int v3)
    {
        v1 = F1;
        v2 = F2;
        v3 = F3;
    }
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void TestMethodInlining(VT* pVT)
{
    int v1, v2, v3;
    pVT->Get(out v1, out v2, out v3);
    Do(v1, v2);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void TestByRef(ref VT VTRef)
{
    int v1, v2, v3;
    v1 = VTRef.F1;
    v2 = VTRef.F2;
    v3 = VTRef.F3;
    Do(v1, v2);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void TestByPtr(VT* pVT)
{
    int v1, v2, v3;
    v1 = pVT->F1;
    v2 = pVT->F2;
    v3 = pVT->F3;
    Do(v1, v2);
}

static void Main(string[] args)
{
    byte* pDataBytes = stackalloc byte[VT.Size];
    VT* pVT = (VT*)pDataBytes;
    pVT->F1 = 1;
    pVT->F2 = 2;
    pVT->F3 = 3;

    TestMethodInlining(pVT);
    TestByRef(ref *pVT);
    TestByPtr(pVT);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void Do(int v1, int v2)
{
    Console.WriteLine("v1={0} v2={1}", v1, v2);
}
```

Disasm listings follow
------------------------------------------
**`TestMethodInlining()`**
Accesses all three fields. Access to 3rd field is still there even when `out v3` is replaced with `out _` . A side question - is it mandatory to adjust RSP anyhow for such methods?
```
--- Program2.cs ---
    pVT->Get(out v1, out v2, out v3);
000007FE78721590  sub         rsp,28h  
000007FE78721594  mov         edx,dword ptr [rcx]  
000007FE78721596  mov         eax,dword ptr [rcx+4]  
000007FE78721599  mov         ecx,dword ptr [rcx+8]  
    Do(v1, v2);
000007FE7872159C  mov         ecx,edx  
000007FE7872159E  mov         edx,eax  
000007FE787215A0  call        000007FE78721040  
000007FE787215A5  nop  
000007FE787215A6  add         rsp,28h  
000007FE787215AA  ret  
--- No source file -------------------------------------------------------------
```

------------------------------------------
**`TestByRef()`**
Access to the 3rd field is dropped. This looks strange to me since the side effects are supposedly the same as in previous case. Also, field access is generated if I wrap it with `Volatile.Read(ref VTRef.F3)`. Also, the same question regarding RSP as in previous case.
```
--- Program2.cs ---
    v1 = VTRef.F1;
000007FE78722AE0  sub         rsp,28h  
000007FE78722AE4  mov         edx,dword ptr [rcx]  
000007FE78722AE6  mov         eax,dword ptr [rcx+4]  
000007FE78722AE9  mov         ecx,edx  
000007FE78722AEB  mov         edx,eax  
000007FE78722AED  call        000007FE787215C0  
000007FE78722AF2  nop  
000007FE78722AF3  add         rsp,28h  
000007FE78722AF7  ret  
--- No source file -------------------------------------------------------------
```

------------------------------------------
**`TestByPtr()`**
Quite a mess! First two fields are accessed and copied to EDX + EAX like in case 2 (and unlike in case 1). And then it looks like entire structure is copied on stack for the reason quite obscure. [I believe I've seen other cases when the structure passed as method arg with **ref/in** modifiers is copied, but this could be separate issue]
```
--- Program2.cs ---
    v1 = pVT->F1;
000007FE78712B10  sub         rsp,38h  
000007FE78712B14  mov         edx,dword ptr [rcx]  
000007FE78712B16  mov         eax,dword ptr [rcx+4]  
000007FE78712B19  mov         r8d,dword ptr [rcx]  
000007FE78712B1C  mov         dword ptr [rsp+28h],r8d  
000007FE78712B21  mov         r8d,dword ptr [rcx+4]  
000007FE78712B25  mov         dword ptr [rsp+2Ch],r8d  
000007FE78712B2A  mov         ecx,dword ptr [rcx+8]  
000007FE78712B2D  mov         dword ptr [rsp+30h],ecx  
000007FE78712B31  mov         ecx,edx  
000007FE78712B33  mov         edx,eax  
000007FE78712B35  call        000007FE787115C0  
000007FE78712B3A  nop  
000007FE78712B3B  add         rsp,38h  
000007FE78712B3F  ret  
--- No source file -------------------------------------------------------------
```

-----------------------------------------

One observation is that JIT produces the same code for all three methods when I add `volatile` modifier to all three fields.

**Comment by voinokin** [comment]
Another observation - if I change test methods to pass just 1st field during invokation to `Do()`, this is reflected in disasm as:

------------------------
**`TestMethodInlining()`**
No change - all three fields are accessed.

------------------------
**`TestByRef()`**
Changed to read just the first field.

------------------------
**`TestByPtr()`**
Even more mess - this time the structure is copied 2 times on stack !

```
--- Program2.cs ---
    v1 = pVT->F1;
000007FE7A852AF0  sub         rsp,48h  
000007FE7A852AF4  mov         eax,dword ptr [rcx]  
000007FE7A852AF6  mov         edx,dword ptr [rcx]  
000007FE7A852AF8  mov         dword ptr [rsp+38h],edx  
000007FE7A852AFC  mov         edx,dword ptr [rcx+4]  
000007FE7A852AFF  mov         dword ptr [rsp+3Ch],edx  
000007FE7A852B03  mov         edx,dword ptr [rcx+8]  
000007FE7A852B06  mov         dword ptr [rsp+40h],edx  
000007FE7A852B0A  mov         edx,dword ptr [rcx]  
000007FE7A852B0C  mov         dword ptr [rsp+28h],edx  
000007FE7A852B10  mov         edx,dword ptr [rcx+4]  
000007FE7A852B13  mov         dword ptr [rsp+2Ch],edx  
000007FE7A852B17  mov         ecx,dword ptr [rcx+8]  
000007FE7A852B1A  mov         dword ptr [rsp+30h],ecx  
000007FE7A852B1E  mov         ecx,eax  
000007FE7A852B20  call        000007FE7A8515C0  
000007FE7A852B25  nop  
000007FE7A852B26  add         rsp,48h  
000007FE7A852B2A  ret  
--- No source file -------------------------------------------------------------
```

Then, if I just add field F4 which is neither initialized nor accessed, the disasm for the first 2 cases does not change, but for the 3rd case I've got:

```
--- Program2.cs ---
    v1 = pVT->F1;
000007FE7AB92AF0  sub         rsp,48h  
000007FE7AB92AF4  mov         eax,dword ptr [rcx]  
000007FE7AB92AF6  movdqu      xmm0,xmmword ptr [rcx]  
000007FE7AB92AFA  movdqu      xmmword ptr [rsp+38h],xmm0  
000007FE7AB92B00  movdqu      xmm0,xmmword ptr [rcx]  
000007FE7AB92B04  movdqu      xmmword ptr [rsp+28h],xmm0  
000007FE7AB92B0A  mov         ecx,eax  
000007FE7AB92B0C  call        000007FE7AB915C0  
000007FE7AB92B11  nop  
000007FE7AB92B12  add         rsp,48h  
000007FE7AB92B16  ret 
```

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
On windows x64, any method that makes a call must generally also allocate a stack frame (there is a scratch area one can use to avoid this sometimes if the frame is small, but the jit doesn't use it afaik).
So that explains the RSP adjustments.

Looking at `TestByPtr`: here for some reason (perhaps preserving exception semantics) CSC is requesting a copy be made and then discarded:
```
IL_0000  02                ldarg.0     
IL_0001  7b 02 00 00 04    ldfld        0x4000002
IL_0006  02                ldarg.0     
IL_0007  7b 03 00 00 04    ldfld        0x4000003
IL_000c  0a                stloc.0     
IL_000d  02                ldarg.0     
IL_000e  71 02 00 00 02    ldobj        0x2000002        // make copy of VT
IL_0013  26                pop                           // and then throw it away
IL_0014  06                ldloc.0     
IL_0015  28 07 00 00 06    call         0x6000007
IL_001a  2a                ret         
```
The jit should arguably detect this pattern as an importer peep and just nullcheck arg0 instead. I don't know how common this pattern is. Let me investigate some more.

So we currently keep the copy around.  Which explains this bit:
```asm
       448B01               mov      r8d, dword ptr [rcx]
       4489442428           mov      dword ptr [rsp+28H], r8d
       448B4104             mov      r8d, dword ptr [rcx+4]
       448944242C           mov      dword ptr [rsp+2CH], r8d
       8B4908               mov      ecx, dword ptr [rcx+8]
       894C2430             mov      dword ptr [rsp+30H], ecx
```
One might also hope that even if this gets past the importer we would deadcode it later, but the promoted temps are address exposed because they're related to the parent which is address exposed by the copy. So they stay live.

With that sorted it would produce the same code as `TestByRef`. Would also be nice to avoid the register shuffles here but since RCX is live in both loads and the first should go into ECX we have to have at least one move. And then we pick EDX. Because of this the second load can't get its preferred EDX and so ends up in EAX. Then we shuffle them about. Fixing this would be tricky I think...

**Comment by voinokin** [comment]
Thanks for the explanation!
Anyway, couple questions remain:
- why two copies of the structure if I use only 1 value of 3 ? (Should I ask elsewhere?)
- why does `TestMethodInlining()` accesses all 3 values although other 2 cases only touch what's used later? My use case is - I have VT with bunch of fields and a method `GetAllData()` which returns everything. Then the code that calls this method chooses what to ignore. My understanding is that all three test methods should produce the same machine code (+/- null reference checks for `ref` modifier, JIT seems to like this :-) )

**Comment by AndyAyersMS** [comment]
> why two copies of the structure if I use only 1 value of 3 ? (Should I ask elsewhere?)

Which version of which method? 

> why does TestMethodInlining() accesses all 3 values although other 2 cases

Not sure yet.

**Comment by AndyAyersMS** [comment]
The `ldobj; pop` pattern doesn't seem all that common.

@VSadov can you help me understand the purpose of that bit of IL that CSC generates for `TestMethodPtr`? Above was using 2.8.0.62811 (9081e399).

**Comment by voinokin** [comment]
@AndyAyersMS Here's updated repro - with 8 fields read and only 1 value used, it appears that there are 7 copies of the VT on stack.

```
[StructLayout(LayoutKind.Sequential)]
struct VT
{
    public static readonly int Size = Marshal.SizeOf<VT>();

    public int F1, F2, F3, F4, F5, F6, F7, F8;
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void Do(int v1)
{
    Console.WriteLine("v1={0}", v1);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void TestByPtr(VT* pVT)
{
    int v1, v2, v3, v4, v5, v6, v7, v8;
    v1 = pVT->F1;
    v2 = pVT->F2;
    v3 = pVT->F3;
    v4 = pVT->F4;
    v5 = pVT->F5;
    v6 = pVT->F6;
    v7 = pVT->F7;
    v8 = pVT->F8;
    Do(v1);
}

static void Main(string[] args)
{
    byte* pDataBytes = stackalloc byte[VT.Size];
    VT* pVT = (VT*)pDataBytes;
    pVT->F1 = 1;
    pVT->F2 = 2;
    pVT->F3 = 3;
    pVT->F4 = 4;
    pVT->F5 = 5;
    pVT->F6 = 6;
    pVT->F7 = 7;
    pVT->F8 = 8;

    TestByPtr(pVT);
}
```
--------------------
**ILDASM**

```
.method private hidebysig static void  TestByPtr(valuetype _100GbSort.Program2/VT* pVT) cil managed noinlining
{
  // Code size       61 (0x3d)
  .maxstack  8
  IL_0000:  ldarg.0
  IL_0001:  ldfld      int32 _100GbSort.Program2/VT::F1
  IL_0006:  ldarg.0
  IL_0007:  ldobj      _100GbSort.Program2/VT
  IL_000c:  pop
  IL_000d:  ldarg.0
  IL_000e:  ldobj      _100GbSort.Program2/VT
  IL_0013:  pop
  IL_0014:  ldarg.0
  IL_0015:  ldobj      _100GbSort.Program2/VT
  IL_001a:  pop
  IL_001b:  ldarg.0
  IL_001c:  ldobj      _100GbSort.Program2/VT
  IL_0021:  pop
  IL_0022:  ldarg.0
  IL_0023:  ldobj      _100GbSort.Program2/VT
  IL_0028:  pop
  IL_0029:  ldarg.0
  IL_002a:  ldobj      _100GbSort.Program2/VT
  IL_002f:  pop
  IL_0030:  ldarg.0
  IL_0031:  ldobj      _100GbSort.Program2/VT
  IL_0036:  pop
  IL_0037:  call       void _100GbSort.Program2::Do(int32)
  IL_003c:  ret
} // end of method Program2::TestByPtr
```

--------------------
**Disasm**
```
--- \Program2.cs ---
    v1 = pVT->F1;
000007FE6BED15A0  sub         rsp,108h  
000007FE6BED15A7  mov         eax,dword ptr [rcx]  
000007FE6BED15A9  movdqu      xmm0,xmmword ptr [rcx]  
000007FE6BED15AD  movdqu      xmmword ptr [rsp+0E8h],xmm0  
000007FE6BED15B6  movdqu      xmm0,xmmword ptr [rcx+10h]  
000007FE6BED15BB  movdqu      xmmword ptr [rsp+0F8h],xmm0  
000007FE6BED15C4  movdqu      xmm0,xmmword ptr [rcx]  
000007FE6BED15C8  movdqu      xmmword ptr [rsp+0C8h],xmm0  
000007FE6BED15D1  movdqu      xmm0,xmmword ptr [rcx+10h]  
000007FE6BED15D6  movdqu      xmmword ptr [rsp+0D8h],xmm0  
000007FE6BED15DF  movdqu      xmm0,xmmword ptr [rcx]  
000007FE6BED15E3  movdqu      xmmword ptr [rsp+0A8h],xmm0  
000007FE6BED15EC  movdqu      xmm0,xmmword ptr [rcx+10h]  
000007FE6BED15F1  movdqu      xmmword ptr [rsp+0B8h],xmm0  
000007FE6BED15FA  movdqu      xmm0,xmmword ptr [rcx]  
000007FE6BED15FE  movdqu      xmmword ptr [rsp+88h],xmm0  
000007FE6BED1607  movdqu      xmm0,xmmword ptr [rcx+10h]  
000007FE6BED160C  movdqu      xmmword ptr [rsp+98h],xmm0  
000007FE6BED1615  movdqu      xmm0,xmmword ptr [rcx]  
000007FE6BED1619  movdqu      xmmword ptr [rsp+68h],xmm0  
000007FE6BED161F  movdqu      xmm0,xmmword ptr [rcx+10h]  
000007FE6BED1624  movdqu      xmmword ptr [rsp+78h],xmm0  
000007FE6BED162A  movdqu      xmm0,xmmword ptr [rcx]  
000007FE6BED162E  movdqu      xmmword ptr [rsp+48h],xmm0  
000007FE6BED1634  movdqu      xmm0,xmmword ptr [rcx+10h]  
000007FE6BED1639  movdqu      xmmword ptr [rsp+58h],xmm0  
000007FE6BED163F  movdqu      xmm0,xmmword ptr [rcx]  
000007FE6BED1643  movdqu      xmmword ptr [rsp+28h],xmm0  
000007FE6BED1649  movdqu      xmm0,xmmword ptr [rcx+10h]  
000007FE6BED164E  movdqu      xmmword ptr [rsp+38h],xmm0  
000007FE6BED1654  mov         ecx,eax  
000007FE6BED1656  call        000007FE6BED1040  
000007FE6BED165B  nop  
000007FE6BED165C  add         rsp,108h  
000007FE6BED1663  ret  
--- No source file -------------------------------------------------------------
```
--------------------
**Reflector** shows this:

```
[MethodImpl(MethodImplOptions.NoInlining)]
private static unsafe void TestByPtr(VT* pVT)
{
  VT vt1 = pVT[0];
  VT vt2 = pVT[0];
  VT vt3 = pVT[0];
  VT vt4 = pVT[0];
  VT vt5 = pVT[0];
  VT vt6 = pVT[0];
  VT vt7 = pVT[0];
  Do(pVT.F1);
}
--

**Comment by voinokin** [comment]
(I have feeling, that `ldobj; pop` pattern is used to simulate null reference check, with the consequence having copy of the structure on stack)

**Comment by VSadov** [comment]
I do not think this is intentional. 
`p->field` is lowered very early into `(*p).field`.  Then at codegen we see unused struct field load. Struct field loads do not have sideeffects (unless volatile, static, etc...) so we only emit unused receiver.
`(*p).field`  becomes `(*p)`  which has to emit since dereference is sideeffecting (can throw).

Note that from the language prospective `ref` cannot be null since it is an existing variable passed by reference and must have storage, but `*` can, since it is just a value. That is why '*' and 'ref' behave differently here. Language permits eliminating unused `refArg.structField` entirely, but not the unused `ptrArg->structField`. This is subtle. I hope it makes sense.

Anyways - `(*p)` is correct, since it produces right sideeffects, but perhaps not the best. 
It leads to 
`<receiver expr>; ldobj; pop`

Perhaps reducing unused field loads off a pointer indirection could be better reduced to `ref (*p).field`.
That would lead to
`<receiver expr>; ldflda; pop`

Not sure if JIT would like it more though. In any case it would be reasonable for the JIT to optimize either patter to a null check.

**Comment by VSadov** [comment]
Actually `ldflda` would not work here. One can happily just do `null + offset`. There must be an indirect read. So it is either `ldobj` or `ldfld`

**Comment by AndyAyersMS** [comment]
Looks like the importer is somewhat aware of things like this for `CEE_POP` but ends up keeping the copy around. I have prototyped a forward-looking peephole that will get rid of the copy. We may be better served enhancing what `CEE_POP` handling can do as it might get even more cases.

With the prototype we still do a null check. Among other things, assertion prop won't make non-null assertions on pointers. That is not entirely unreasonable but it looks odd when there is an equivalent check just upstream.
```asm
; Assembly listing for method P:TestByPtr(long)
; Emitting BLENDED_CODE for X64 CPU with AVX
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  5,  5   )    long  ->  rcx
;  V01 loc0         [V01,T02] (  2,  2   )     int  ->  rax
;  V02 OutArgs      [V02    ] (  1,  1   )  lclBlk (32) [rsp+0x00]
;  V03 tmp1         [V03,T01] (  2,  4   )     int  ->  rdx
;
; Lcl frame size = 40

G_M62956_IG01:
       4883EC28             sub      rsp, 40

G_M62956_IG02:
       8B11                 mov      edx, dword ptr [rcx]
       8B4104               mov      eax, dword ptr [rcx+4]
       480FBE09             movsx    rcx, byte  ptr [rcx]     // residual code from ldobj; pop
       8BCA                 mov      ecx, edx
       8BD0                 mov      edx, eax
       E8FAD3FFFF           call     P:Do(int,int)
       90                   nop

G_M62956_IG03:
       4883C428             add      rsp, 40
       C3                   ret
```
