### ISSUE TITLE
Failure in arm32/arm64 corefx altjit tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#18723]
I'm seeing:
```
10:14:48 Running: D:\j\workspace\x64_arm64_alt---734a66f6\_\fx\Tools\dotnetcli\dotnet msbuild /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:OSGroup=Windows_NT /p:ConfigurationGroup=Release /p:ArchGroup=x64 /p:BuildPackages=false  /flp:v=normal;LogFile=build-tests.log  /flp2:warningsonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err  src/tests.builds /p:WithoutCategories="IgnoreForCI;XsltcExeRequired" /p:PreExecutionTestScript=D:\j\workspace\x64_arm64_alt---734a66f6\SetStressModes.bat
10:14:48 
MSBUILD : error MSB1006: Property is not valid.
10:14:48 Switch: XsltcExeRequired
10:14:48 
10:14:48 For switch syntax, type "MSBuild /help"
10:14:49 Command execution failed with exit code 1.
10:14:49 
10:14:49 D:\j\workspace\x64_arm64_alt---734a66f6>exit 1
```

Did something change in the corefx tools (msbuild, etc.) that makes this syntax invalid now?

This syntax is constructed in coreclr: tests\scripts\run-corefx-tests.py

e.g.: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_baseline/230/consoleFull#-165810470383554902-aff0-4799-9e92-0ada24ce2a06

**Comment by BruceForstall** [comment]
@RussKeldorph @stephentoub @A-And @weshaggard any ideas?

**Comment by weshaggard** [comment]
Looks like something changed to make the `;` no longer escaped. `/p:WithoutCategories="IgnoreForCI;XsltcExeRequired"` not sure what that might be.  If nothing else changed it is possible the resent update to SDK (https://github.com/dotnet/coreclr/pull/18626) might have caused this.

**Comment by BruceForstall** [comment]
Looks like it was this change that did it: https://github.com/dotnet/corefx/pull/30675

I need to figure out how to invoke dotnet with the backslashes still there.

fwiw, this syntax is **extremely** fragile and frustrating, given all the undocumented magic processing that CMD does with quotes and semicolons.

**Comment by BruceForstall** [comment]
That change caused us to use "dotnet msbuild" instead of the desktop msbuild. It looks like there is a known problem with quote parsing, described here: https://github.com/dotnet/cli/issues/7791 (and other places).

The suggested workaround is to add backslashes before the quotes. However, that is very hard to get passed through all the layers of python/CMD scripting.

**Comment by BruceForstall** [comment]
@weshaggard I've submitted a PR with a fix for this. You might be amused (or dismayed?) by the fix.
