### ISSUE TITLE
SuppressUnmanagedCodeSecurityAttribute cannot be applied to structures

### ISSUE THREAD

**Issue by ddobrev** [dotnet/coreclr#1872]
The documentation says that using SuppressUnmanagedCodeSecurity on a class applies it to all contained methods. The same should work for a structure and its methods.

**Comment by joshfree** [comment]
@morganbr PTAL

**Comment by morganbr** [comment]
@ddobrev, could you please tell us more about your intended usage for SuppressUnmanagedCodeSecurity on a struct? In case it helps, you don't need that attribute at all with CoreCLR -- it's effectively always turned on.

**Comment by ddobrev** [comment]
I need to support .NET 4.0 too which means CoreCLR cannot help me. I used it in the most standard way possible - I have structures with many P/Invoke declarations within and I am forced to apply the attribute to each one, and to also remember to apply it to each newly added P/Invoke. If this worked, I would've been able to apply the attribute to the structure itself and forget about it.

**Comment by gkhanna79** [comment]
@morganbr Is this actionable for 1.1.0 RTM?

**Comment by morganbr** [comment]
@gkhanna79  This isn't actionable for 1.1. It looks like the request it to support it on full framework (though the attribute would have to be updated on CoreCLR as well).

**Comment by jkotas** [comment]
CAS is not supported in .NET Core.
