### ISSUE TITLE
Create package for Raspbian OS (ARM32)

### ISSUE THREAD

**Issue by ygoe** [dotnet/coreclr#18732]
While there is a working binary download for dotnet (.NET Core) for ARM32 that works on a Raspberry Pi B 3+ with a current Raspbian OS, there are no instructions how to install it. And there are no packages for the OS, too. So it's a bit of a mystery how to actually make .NET Core work on a Raspi.

I think there should be a package for that OS. It should be as simple as that:

    sudo apt install dotnet

Maybe a custom package source needs to be added, but definitely no manual tar file works. Mono was easier to install when it was current like 5 years ago.

Since the docker support on the Raspi with dotnet-runtime packages is very poor (multi-arch fails, need to select arm32 image specifically, can't get my app in a custom image), I need to install .NET Core on the Raspi OS itself.

**Comment by kasper3** [comment]
Current blocker for ARM32 in general is https://github.com/dotnet/cli/issues/8998. In my understanding it's about couple of lines of XML changes in dotnet/cli to pack the right binaries (like done for ARM64 https://github.com/dotnet/cli/pull/9011/files) and then testing cross build on x64 (which is a more involved task).
That said, CoreCLR/CoreFx/CoreSetup parts for ARM32 are done.

**Comment by RussKeldorph** [comment]
This issue was moved to dotnet/core#1828
