### ISSUE TITLE
regressions in arm64_altjit r2r jobs: temp != nullptr

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#18746]
Some tests are failing after #18346, for example [b393481](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_arm64_altjit_checked_windows_nt_r2r_prtest/12/testReport/junit/JIT_Regression/_CLR_x86_JIT_dev10_b393481_b393481_b393481_/_CLR_x86_JIT_dev10_b393481_b393481_b393481_cmd/) fails with `Assertion failed 'temp != nullptr' in 'TestAnonymousTypes.Program:Main(ref):int' (IL size 534)\r\n\r\n File: d:\\j\\workspace\\x64_arm64_alt---840786b4\\src\\jit\\regset.cpp Line: 676`.

**Comment by sandreenko** [comment]
cc @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
I had taken a look at this before @sandreenko pointed me at this issue. @jashook - I see that it's assigned to you. I can look further if you'd like. It *seems* (from an initial look at a jitdump) that the register allocator is tracking int and long spill-temps separately, which it shouldn't be doing.
