### ISSUE TITLE
Consider targeting NaCL as a supported platform of CoreCLR

### ISSUE THREAD

**Issue by AArnott** [dotnet/coreclr#1874]
It seems that if CoreCLR ran on the [Google Native Client](https://en.wikipedia.org/wiki/Google_Native_Client), we could run CoreCLR code in Chrome, and (eventually) Electron apps, and potentially any other Chromium host. 

Is there any interest? Has any investigation been done already?

**Comment by AArnott** [comment]
Rumor has it that [mono has already been compiled for NaCL](https://atomio.slack.com/archives/electron/p1445903043001888).

**Comment by mellinoe** [comment]
Perhaps we can consider targeting WebAssembly as a forward-looking goal? It would get us more reach than just Chromium browsers, but I have no idea what the timeline is like for it to become usable/stable. Perhaps we could have an experimental branch as it becomes more stable.

**Comment by jkotas** [comment]
NaCl is officially deprecated in favor of WebAssembly now: https://blog.chromium.org/2017/05/goodbye-pnacl-hello-webassembly.html

**Comment by AArnott** [comment]
@jkotas would #5303 be an equivalent issue to this one, but tracking .NET Core code doing native code gen for WebAssembly instead?

**Comment by jkotas** [comment]
I think so.
