### ISSUE TITLE
Ensure that the indirect call fallback for HWIntrinsics executes the same instructions as the inlined version

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#18743]
There are a few `Avx` helper functions (namely `Extract` and `Insert`) which are emitting a managed software implementation rather than a switch table fallback.

These should be updated to use the switch table fallback instead.

**Comment by tannergooding** [comment]
FYI. @CarolEidt, @fiigii, @eerhardt 

This tracks the discussion here: https://github.com/dotnet/coreclr/pull/18734#discussion_r199337102

**Comment by fiigii** [comment]
Please close this issue.

**Comment by tannergooding** [comment]
I think there are still a few APIs where we aren't validating this (namely the tests that aren't templated yet)....

Do we still have a bug tracking the move of all HWIntrinsic tests to be templated?

**Comment by fiigii** [comment]
> There are a few Avx helper functions (namely Extract and Insert)

We no longer have Avx.Extract/Insert helpers.

**Comment by tannergooding** [comment]
Ah, I didn't read the top post, just the PR title.
