### ISSUE TITLE
Question about software protection

### ISSUE THREAD

**Issue by xsharkx** [dotnet/coreclr#18741]
There is a question about software protection. We used confusing software to compiling and then obscure the code, and then deploying。we use hardware key to protection secret algorithms, so that the software could be prevented from being copied. Now deployed in the container, if a customer asks us to deploy a private cloud to them, the file is easily copied by . Whether the container can be restricted can not be mounted, or can not be copied.

**Comment by jkotas** [comment]
This is a very general question that is not related to CoreCLR runtime.

**Comment by xsharkx** [comment]
But this can be solved by CLR, for example, compiled DLL can be encrypted, and CLR can run encrypted DLL. Give CLR a Key through the environment variable

**Comment by jkotas** [comment]
CLR has APIs that allows you to implement this scheme on your own (look for `Assembly.Load(byte[])`).
