### ISSUE TITLE
Implement Efficient Dispatch Polling Mechanism for EventPipe

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#18758]
Context: https://github.com/dotnet/coreclr/pull/18649#discussion_r199631486

We should consider replacing the polling loop when there are no new events with an AutoResetEvent to ensure that the CPU can go quiescent when there are no events.

**Comment by tommcdon** [comment]
@jorive needs investigation to determine this is still an issue for 3.0

**Comment by brianrob** [comment]
This is still worth keeping around but it isn't related to the IPC mechanism.  This is about the call to ```Sleep``` here: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Diagnostics/Eventing/EventPipeEventDispatcher.cs#L180.
