### ISSUE TITLE
Expose IsSzArray on System.Type for public use

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/coreclr#1877]
Expression compilers can benefit from this to differentiate between vectors and multi-dimensional arrays of rank 0. See https://github.com/dotnet/corefx/issues/4161 for a concrete example.

**Comment by VSadov** [comment]
This is indeed is a strange omission. The only way to distinguish vectors and arrays is IsSzArray and that one is not public.
I see no reason for hiding this. The distinction between vectors and arrays is well defined and documented.

**Comment by VSadov** [comment]
CC @terrajobst

**Comment by weshaggard** [comment]
@AtsushiKan is there any reason we should or could not expose this?

**Comment by AtsushiKan** [comment]
Definitely, we should expose it. I found myself quite annoyed at its omission just last week.

**Comment by davkean** [comment]
I like @AtsushiKan suggestion of IsVector.

**Comment by mburbea** [comment]
Yes, I'd like this too. In the past, I've had to write code to check if the type name had a [*] indicating that it was md array of size 1.

**Comment by JonHanna** [comment]
*Vector* is a rather overloaded term, making `IsVector` a possible source of confusion, especially since when the difference between an SZ-Array and any other array, including single-rank non-zero based, comes up, the term used tends to be "SZArray".

Might I suggest `public bool IsSZArray => IsSzArray;` as a simple implementation that builds on the existing code without breaking any strange custom implementations. It's not great to distinguish a member just on casing, but I think it would be worth bending the rule.

**Comment by JonHanna** [comment]
> I like @AtsushiKan suggestion of IsVector.

*Vector* has a few different existing uses as a term, and SZ-Array is commonly enough used in the .NET world. Could we just expose the existing member? Failing that, what about `public bool IsSZArray => IsSzArray;`?

**Comment by AtsushiKan** [comment]
It seems the issue needs to be in corefx repo to get the needed api-review tags, so opening one in corefx to replace this.

https://github.com/dotnet/corefx/issues/16566

**Comment by dsyme** [comment]
Just to mention this addition to the Sysem.Type architecture is causing problems when using TypeDelegator as a way to make custom System.Type implementations: 
 https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/236#issuecomment-420251440

I've sent email internally about this, but in general my impression is that we can't add new public virtuals to System.Type (at least if we allow people to create custom implementations of System.Type via TypeDelegator, which we do).
