### ISSUE TITLE
An assembly specified in the application dependencies manifest (Example.deps.json) was not found

### ISSUE THREAD

**Issue by M144-Coder** [dotnet/coreclr#18846]
I am developing a web application using Asp.NET Core 2.1 on Visual Studio 17.7, the problem is when I publish the web app as a Framework-Dependent and I try to run the app on production machine I get this error message:

`Error:
An assembly specified in the application dependencies manifest (Example.deps.json) was not found:
package: 'Cronos', version: '0.6.3'
path: 'lib/netstandard1.0/Cronos.dll'`

Cronos.dll is a dependency of Hangfire library which I am using in the web app, in the Example.deps.json file I found this:

`"Cronos/0.6.3": {
    "dependencies": {
      "NETStandard.Library": "2.0.3"
    },
    "runtime": {
      "lib/netstandard1.0/Cronos.dll": {
        "assemblyVersion": "0.6.3.0",
        "fileVersion": "0.6.3.0"
      }
    },
    "compile": {
      "lib/netstandard1.0/Cronos.dll": {}
    }
  },`

The problem is that it's referencing the libraries in the runtime store, which will work on the developemnt machine but when I deploy to another machine the error happens.

I have tried the suggested solution in this article:

https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store

By setting:-

`<PropertyGroup>
    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
</PropertyGroup>`

and I have also tried solutions in this github issue with no success:

https://github.com/dotnet/coreclr/issues/13542

**Comment by jeffschwMSFT** [comment]
@M144-Coder do you have an example that you can share?  Based on the issue description it seems that if you added Hangfire to the store on your production server the issue may be resolved.  What benefit are you seeing from using the store in this way?  Is it possible to deploy Hangfire (and Cronos) as a package local resource?

**Comment by M144-Coder** [comment]
The issue is that I was running the web application from the root file, I just tried running the other dll file inside the publish folder and the application started successfully, the question is why there is two dll files?, one is in the release root folder and the other is inside the publish folder.

**Comment by jeffschwMSFT** [comment]
This is an area we are looking into.  The reason for the current behavior is to reduce file copies on the inner loop.  It sounds like you have at least a working example now so I am going to close the issue, but let us know if you find something else.

**Comment by Megasware128** [comment]
@jeffschwMSFT I have the same issue when using AutoMapper. What is the status of this problem?

**Comment by jeffschwMSFT** [comment]
@livarcocc is there an issue tracking our potential work on aligning publish and bin?
