### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80131500 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by jinhduong** [dotnet/coreclr#18847]
Error: `Failed to initialize CoreCLR, HRESULT: 0x80131500`
I have a project which using `dotnet 1.1.2` and it works in `Window` well but when I move the environment to Ubuntu and then install the latest version `2.1.301`.

After that once I create new project like as `dotnet new webapi` and then use `dotnet run`, it works well. But when I run the old project (`1.1.2`) it always throw the above `error`

Here is my logfile `strace`
[logfile.txt](https://github.com/dotnet/coreclr/files/2178758/logfile.txt)

Thanks.

# OS
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

**Comment by AaronRobinsonMSFT** [comment]
@jinhduong  The `0x80131500` represents a general .NET exception, which means this is more than likely failing in managed code. Can you try using `lldb` and the `sos` plugin - instructions can be found [here](https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md).

**Comment by jinhduong** [comment]
@AaronRobinsonMSFT Thanks for your response but I follow the instruction which is quite hard and still not resolved my problem so I already switch to `ubuntu 16.04` and this problem was be resolved.

**Comment by AaronRobinsonMSFT** [comment]
@jinhduong Okay. Thanks for updating us. I will close this issue - feel free to re-open if you hit it again.
