### ISSUE TITLE
System.Drawing.Tests.FontTests.ToLogFont Null Exception

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#18840]
This test is failing:

System.Drawing.Tests.FontTests.ToLogFont_NullLogFont_ThrowsArgumentNullException

It's been failing since https://github.com/dotnet/coreclr/pull/18791: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_corefx_innerloop_prtest/443/

Perhaps there's some corefx/coreclr interdependency that has not been reconciled?

@AaronRobinsonMSFT

**Comment by danmosemsft** [comment]
ecb7b2551f3f115da05be112e324e017b4cd7f0e removed this test. It looks like you have old tests and new implementation.

**Comment by AaronRobinsonMSFT** [comment]
I think that @stephentoub did some kind of merge in corefx and coreclr - see [corefx#30830](https://github.com/dotnet/corefx/issues/30830).

**Comment by CarolEidt** [comment]
> It looks like you have old tests and new implementation.

The "you" in this case is the CI system. How are the tests & implementation supposed to be kept in sync?

**Comment by stephentoub** [comment]
@CarolEidt, when exactly did the failures you see happen?  A change was merged into coreclr on Friday that broke a test in corefx; that test was then fixed for the updated behavior on Sunday morning in https://github.com/dotnet/corefx/pull/30895.  If you ran coreclr CI against corefx tests in that interim, you would have seen a break.  But you shouldn't be seeing it now.  Are you?

**Comment by CarolEidt** [comment]
The failures are showing up in the CI system in this job: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_corefx_innerloop_prtest . They've been failing since the PR I mentioned. Build #442 was the last time they passed (https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_corefx_innerloop_prtest/442/).
Build #443 (https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_corefx_innerloop_prtest/443/) was the test for that PR, and it failed.

**Comment by stephentoub** [comment]
Apparently there's now another mechanism I wasn't aware of coreclr is using for running the corefx tests:
https://github.com/dotnet/coreclr/pull/18844#issuecomment-403663651
and it's not using the latest corefx test source, so it doesn't matter that the test has been fixed.  Sounds like @A-And is the person to talk to about it.

But the test was definitely fixed, and corefx has happily been running it against the most recent coreclr it pulled in.

**Comment by jkotas** [comment]
Fixed by #18844. This fell through the cracks because of the CI outage - change was merged without full set of CI jobs being run on it.
