### ISSUE TITLE
The `perf.groovy` script is not escaping the PR title properly when it contains double-quotes

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#18855]
This issue was causing failures in https://github.com/dotnet/coreclr/pull/18849

For example: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_min_opt_ryujit_smoketest_prtest/2556/

**Comment by adiaaida** [comment]
@jorive

**Comment by jorive** [comment]
@tannergooding This seems a parsing/escaping problem of the batch command line interface, not the `submission-metadata.py`

**Comment by tannergooding** [comment]
@jorive, potentially.

Looks like the jobs are doing:
```bat
if "%GIT_BRANCH:~0,7%" == "origin/" (set "GIT_BRANCH_WITHOUT_ORIGIN=%GIT_BRANCH:origin/=%") else (set "GIT_BRANCH_WITHOUT_ORIGIN=%GIT_BRANCH%")
set "BENCHVIEWNAME=coreclr private %BenchviewCommitName%"
set "BENCHVIEWNAME=%BENCHVIEWNAME:"=""%"
py "%WORKSPACE%\Microsoft.BenchView.JSONFormat\tools\submission-metadata.py" --name "%BENCHVIEWNAME%" --user-email "dotnet-bot@microsoft.com"
py "%WORKSPACE%\Microsoft.BenchView.JSONFormat\tools\build.py" git --branch %GIT_BRANCH_WITHOUT_ORIGIN% --type private
```
The second `set "BENCHVIEWNAME" is attempting to replace all `"` with `""`. But something else has already changed `"` to `\"`, which breaks the overall parsing

**Comment by jorive** [comment]
the `perf.groovy` fille is trying to do the operations below, but something is not working as expected

```cmd
@if not defined _echo echo off

setlocal
  if exist ".\submission-metadata.json" del /f /q ".\submission-metadata.json"

  set "GV_TITLE=coreclr private Fixing encodeXmmRegAsIval to ensure the result meets the "fits in imm8" check"
  set "GV_TITLE=%GV_TITLE:"=""%"

  py.exe submission-metadata.py --name "%GV_TITLE%" --user-email "dotnet-bot@microsoft.com" || exit /b 1

  type submission-metadata.json
endlocal& exit /b 0
```

**Comment by jorive** [comment]
This generated command seems wrong:
`py "D:\j\w\perf_perflab_---988491d2\Microsoft.BenchView.JSONFormat\tools\submission-metadata.py" --name "coreclr private Fixing encodeXmmRegAsIval to ensure the result meets the \""fits in imm8\"" check" --user-email "dotnet-bot@microsoft.com"`

In addition, the run should have stopped/failed at this point.

**Comment by jorive** [comment]
@tannergooding You are right, the generated command in ci2 looks fine, but the executed command displayed in the log is different.
```cmd
rem In ci2
set "BENCHVIEWNAME=coreclr private %BenchviewCommitName%"
set "BENCHVIEWNAME=%BENCHVIEWNAME:"=""%"
py "%WORKSPACE%\Microsoft.BenchView.JSONFormat\tools\submission-metadata.py" --name "%BENCHVIEWNAME%" --user-email "dotnet-bot@microsoft.com"
```
```cmd
rem In Log
set "BENCHVIEWNAME=coreclr private Fixing encodeXmmRegAsIval to ensure the result meets the \"fits in imm8\" check"
set "BENCHVIEWNAME=coreclr private Fixing encodeXmmRegAsIval to ensure the result meets the \""fits in imm8\"" check"
py "D:\j\w\perf_perflab_---988491d2\Microsoft.BenchView.JSONFormat\tools\submission-metadata.py" --name "coreclr private Fixing encodeXmmRegAsIval to ensure the result meets the \""fits in imm8\"" check" --user-email "dotnet-bot@microsoft.com"
```

**Comment by jkotas** [comment]
`perf.groovy` is gone
