### ISSUE TITLE
ARM64 corefx test failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#18886]
The following tests fail in corefx CI runs, and have been disabled. There are some similar failures for ARM in #16001.

E.g., https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_baseline_tst_prtest/2/consoleText

**Comment by BruceForstall** [comment]
```
Invariant.Tests
System.Diagnostics.Process.Tests
System.Drawing.Common.Tests
System.Linq.Expressions.Tests
System.Net.HttpListener.Tests
System.Numerics.Vectors.Tests
System.Runtime.InteropServices.RuntimeInformation.Tests
System.Runtime.Serialization.Formatters.Tests
System.Management.Tests
System.ValueTuple.Tests
```

**Comment by sandreenko** [comment]
The updated lists of falied tests (arm64 windows no stress):
System.Diagnostics.Process.Tests
System.Drawing.Common.Tests
System.Management.Tests

**Comment by sandreenko** [comment]
Management tests won't work on platforms without desktop CoreFX https://github.com/dotnet/corefx/issues/34030#issuecomment-446769181

**Comment by sandreenko** [comment]
System.Diagnostics I think is covered by https://github.com/dotnet/corefx/issues/9628.

Failures in System.Diagnostics.Process.Tests look intresting,
