### ISSUE TITLE
Crossgen fails to compile many different assemblies when run with -ReadyToRun

### ISSUE THREAD

**Issue by agocke** [dotnet/coreclr#1889]
I've tried with every Roslyn assembly and some of the small dependencies like System.Collections.Immutable.dll.

The error message is always `Error: file "<assembly>.dll" or one of its dependencies was not found.`

**Comment by jkotas** [comment]
@JohnChen0 Could you please take a look?

cc @gkhanna79

**Comment by JohnChen0** [comment]
The cause of the error is missing mscorlib, which needs to be present in the same directory as crossgen itself. The error message should be more clear about what file is not found.

**Comment by gkhanna79** [comment]
@agocke Are you able to generate the native image with R2R switch once you have mscorlib.ni.dll next to crossgen?

**Comment by JohnChen0** [comment]
Commit 8d67d1f improves error reporting from crossgen, and should make this type of issues easier to debug in the future.
