### ISSUE TITLE
createdump is missing on ARM and ARM64

### ISSUE THREAD

**Issue by wfurt** [dotnet/coreclr#18893]
X86 runtime has utility `createdump` and there are instructions out there how to use to collect debug info. It is missing in arm runtime. 

This is probably packaging issue. I build it and run it on me RPI and it seems to function.
It did create dump as well as it prints reasonable output when executed with -d flag. 

> src/.nuget/Microsoft.NETCore.Runtime.CoreCLR/runtime.Linux.Microsoft.NETCore.Runtime.CoreCLR.props

```
 <_PlatformDoesNotSupportCreatedump Condition="'$(Platform)' == 'arm'">true</_PlatformDoesNotSupportCreatedump>
 <NativeBinary Condition="'$(_PlatformDoesNotSupportCreatedump)' != 'true'" Include="$(BinDir)createdump" />
 ```

**Comment by BruceForstall** [comment]
@wfurt @mikem8361 Is this still a problem?

**Comment by wfurt** [comment]
It seems so. I downloaded master build from  https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-linux-arm.tar.gz and it is still not there. This originally come up by external user. I can try to find the original issue if needed.

**Comment by BruceForstall** [comment]
@wfurt @mikem8361 Does it make sense to leave the "Milestone" as "2.2.x"? Or should we move it to 3.0? I want to make sure anyone querying for all 3.0 issues sees this. Or should there be a separate 3.0 copy of this issue?

**Comment by wfurt** [comment]
I would set it to 3.0 or future. I don't think this would ever meet the bar for 2.x servicing.
