### ISSUE TITLE
[Linux/arm32][GCStress=0xc] RuntimeEventSourceTest 'listener.EventCount > 0' Assertion Failure

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#18907]
All the recent Ubuntu arm32 GCStress=0xc runs failed the same way in recently added RuntimeEventSourceTest in #18649 

```
...
 System.Exception: Condition 'listener.EventCount > 0' is not true at Tracing.Tests.Common.Assert.True(String name, Boolean condition) at Tracing.Tests.RuntimeEventSourceTest.Main(String[] args) ./runtimeeventsource.sh: line 244: 9975 Aborted $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments Expected: 100 Actual: 134 END EXECUTION - FAILED
```

[arm_cross_checked_ubuntu_gcstress0xc_flow #19](https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_flow/19/)
[arm_cross_checked_ubuntu_gcstress0xc_jitstress1_flow #18](https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_jitstress1_flow/18/)
[arm_cross_checked_ubuntu_gcstress0xc_jitstress2_flow #16](https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_flow/16/)
[arm_cross_checked_ubuntu_gcstress0xc_minopts_heapverify1_flow #18](https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_minopts_heapverify1_flow/18/)
[arm_cross_checked_ubuntu_gcstress0xc_zapdisable_flow #19](https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_zapdisable_flow/19/)
[arm_cross_checked_ubuntu_gcstress0xc_zapdisable_heapverify1_flow #20](https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_zapdisable_heapverify1_flow/20/)
[arm_cross_checked_ubuntu_gcstress0xc_zapdisable_jitstress2_flow #17](https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_zapdisable_jitstress2_flow/17/)

**Update:** when the issue resolved please remove `<GCStressIncompatible>true</GCStressIncompatible>` added in #18911

**Comment by BruceForstall** [comment]
Can the test be disabled until this issue is fixed?

@brianrob is this yours?

**Comment by brianrob** [comment]
If you like, this test can be disabled on gcstress runs, but we should not blanket disable it.

**Comment by brianrob** [comment]
Spoke with @BruceForstall and @echesakovMSFT offline.  To unblock test runs, feel free to mark this as GCStress incompatible, and we can keep this issue open to investigate why the test is failing.

**Comment by BruceForstall** [comment]
@brianrob Is this a 3.0 issue?

**Comment by brianrob** [comment]
Yes, should be looked at for 3.0.

cc: @noahfalk, @jorive

**Comment by jorive** [comment]
Test disabled with https://github.com/dotnet/coreclr/pull/22899
