### ISSUE TITLE
Hardware Intrinsics: Add uint overload for Sse41.MultiplyLow

### ISSUE THREAD

**Issue by Zhentar** [dotnet/coreclr#18905]
```cs
var buffMult = Sse.StaticCast<int,uint>(Sse41.MultiplyLow(
                            Sse.StaticCast<uint, int>(buffVals),
                            Sse.StaticCast<uint, int>(prime32_2)));
```

Works, but it's pretty ugly. 

(for the benefit of those, who like me from two days ago, have minds happily free of two's complement arithmetic, the low half of a multiply is the same for both signed and unsigned values. So while Intel documents the underlying PMULLD as signed, it is actually sign agnostic)

I suspect that there is a matching `Avx2.MultiplyLow` for which this is equally applicable.

**Comment by tannergooding** [comment]
CC. @fiigii, @CarolEidt, @eerhardt

**Comment by fiigii** [comment]
@Zhentar Thanks for the proposal and I agree. `MultiplyLow` only takes the lower 32-bit of the result, so the sign does not matter.

@tannergooding I am also considering to add all the integer overloads for `Avx2.BlendVariable` that is very common to use.

**Comment by tannergooding** [comment]
@fiigii, We'll want to make sure we have an issue tracking it and that it goes to API review (I am working on ensuring another one is setup soon to cover the issues/requrests that have cropped up).

**Comment by fiigii** [comment]
I see. Let me open an issue for `Avx2.BlendVariable`.

**Comment by fiigii** [comment]
Please close this issue.
