### ISSUE TITLE
Assembly.LoadFrom("System.Threading.Tasks.Extensions.dll") fails with FileLoadException

### ISSUE THREAD

**Issue by gfraiteur** [dotnet/coreclr#18903]
We (PostSharp) noticed a weird behavior of .NET Core CLR and are asking for clarifications so we can implement a proper solution.

Consider the following program:

```
   class Program
    {
        static void Main(string[] args)
        {
           Assembly.LoadFrom(@"C:\Users\gael\.nuget\packages\system.threading.tasks.extensions\4.5.1\lib\netstandard2.0\System.Threading.Tasks.Extensions.dll");
   
        }
    }
```

When executed with the default command line with .NET Core 2.0.9, this program throws:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at ConsoleApp2.Program.Main(String[] args) in c:\users\gael\documents\visual studio 2017\ConsoleApp2\Program.cs:line 10
```

We found the following workaround. First, define a file `my.deps.json` with the following content:

```
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v2.0",
    "signature": "fc666d3b05189566bb68c07fa9bfb9b94dbee726"
  },
  "targets": {
    ".NETCoreApp,Version=v2.0": {
      "System.Threading.Tasks.Extensions/4.5.1": {
        "dependencies": {
          "System.Runtime.CompilerServices.Unsafe": "4.5.0"
        },
        "runtime": {
          "C:/Users/gael/.nuget/packages/system.threading.tasks.extensions/4.5.1/lib/netstandard2.0/System.Threading.Tasks.Extensions.dll": {
            "assemblyVersion": "4.2.0.0",
            "fileVersion": "4.6.26606.5"
          }
        }
      }
    }
  },
  "libraries": {
    "System.Threading.Tasks.Extensions/4.5.1": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-rckdhLJtzQ3EI+0BGuq7dUVtCSnerqAoAmL3S6oMRZ4VMZTL3Rq9DS8IDW57c6PYVebA4O0NbSA1BDvyE18UMA==",
      "path": "system.threading.tasks.extensions/4.5.1",
      "hashPath": "system.threading.tasks.extensions.4.5.1.nupkg.sha512"
    }
  }
}
```

Then use the following command line:

```
dotnet --additional-deps my.deps.json ConsoleApp2.dll
```

Our hypothesis is that `Assembly.LoadFrom` is not allowed for assemblies that are shipped with .NET Core (i.e. those under the directory `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.9`). A viable workaround is to generate an additional `deps.json` file and include any assembly that we need to load at runtime but that are not a build-time dependency.

Could you please spread some light on this situation?

Thank you.

-gael

**Comment by danmosemsft** [comment]
@jeffschwMSFT do you know?

**Comment by jeffschwMSFT** [comment]
@gfraiteur thanks for reaching out.  The original failure happens for two reasons: 1) simple version downgrade checks and 2) tpa list unification.  When running on .NET Core 2.0.9 there is a version of System.Threading.Tasks.Extensions with version 4.1.1 that ships as part of NetCore.APP.  When you try to load S.T.T.E version 4.2 (which is what ships as part of the 4.5.1 nuget package) the runtime checks the TPA list and sees there is a version that is part of the platform.  When we try to load that version we see there is a downgrade in the version and fail.  The reason why adding it to the *.deps.json file fixes this issue is that at startup the highest version wins and is loadable.  
The poor diagnostics is noted and that is a problem we are actively looking to resolve.  For assemblies that ship as part of the NETCore.App package not easily overwritten in this way.  
What is the core of your scenario?

**Comment by gfraiteur** [comment]
Thank you for your reply.

Our scenario is a post-compiler (PostSharp), which transforms the assembly being built. This assembly itself contains executable transformations (aspects with build-time logic), therefore we need to feed our application (a .NET Core App application in this case) with the proper list of dependencies. This assembly has of course a different set of dependencies than the post-compiler system.

I think our scenario is just a sub-case of any "plugin loader" system, which typically uses Assembly.LoadFrom. I guess all plugin loaders would be affected by this limitation.

As a workaround, it seems we will need to generate `deps.json` on the fly from the MSBuild task before starting our post-compiler. Maybe a better solution is needed for the general case, i.e. to support Assembly.LoadFrom when the list of dependencies is not known upfront.

**Comment by jeffschwMSFT** [comment]
In this case if you wire up a AssemblyResolve event and return the 4.2 version of System.Threading.Tasks.Extensions then we will load it (regardless of the version number).  We are exploring options to make this better, once we have a proposal I will include you for comment.

**Comment by gfraiteur** [comment]
Thank you. Currently we're calling `Assembly.LoadFrom` from `AssemblyLoadContext.Default.Resolving`. Do you suggest. I tried to use `AppDomain,AssemblyResolve` instead per your suggestion, but I did not work.

I now have a workaround that generates some `postsharp.deps.json` before starting dotnet.exe and it seems to work, although it's a bit brutal.

**Comment by jeffschwMSFT** [comment]
I am glad you have a workaround.  We are actively discussing this scenario and hopefully we will have a better story (at least diagnostics).  Closing for now
