### ISSUE TITLE
Make crossgen.exe walk the closure and emit .ni.dlls for everything in a folder

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#1890]
Can we make crossgen smarter and just have it walk the closure and do what ngen did? It would make it much more efficient and easier on us than having to call it per assembly ourselves.

**Comment by JohnChen0** [comment]
We don't currently have the ability to generate multiple .ni.dll files from one process. Desktop NGen works around this by creating a separate child process for each NI that it generates. To emit multiple NIs from crossgen.exe, we would have to modify it to create child processes as well. This won't be any more efficient than writing a shell script to walk the closure. Thus, I propose not to fix this issue.

@davidfowl Please let me know if you disagrees.

**Comment by JohnChen0** [comment]
Closing this issue as "won't fix", since adding this feature in crossgen.exe will be less flexible and less efficient than using shell scripts.
