### ISSUE TITLE
[arm64] corefx System.ComponentModel.Composition.Tests failure

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#18913]
While scouting Windows arm64 corefx testing: https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_baseline_tst_prtest/3/consoleText

```
----- start 14:37:47.47 ===============  To repro directly: ===================================================== 
pushd C:\Users\robox\j\workspace\arm64_cross_c---c55e6c4b\_\fx\bin\tests\System.ComponentModel.Composition.Tests\netcoreapp-Windows_NT-Release-arm64\
set COMPlus_TieredCompilation=0
call C:\Users\robox\j\workspace\arm64_cross_c---c55e6c4b\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm64\dotnet.exe xunit.console.netcore.exe System.ComponentModel.Composition.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================

C:\Users\robox\j\workspace\arm64_cross_c---c55e6c4b\_\fx\bin\tests\System.ComponentModel.Composition.Tests\netcoreapp-Windows_NT-Release-arm64>set COMPlus_TieredCompilation=0 

C:\Users\robox\j\workspace\arm64_cross_c---c55e6c4b\_\fx\bin\tests\System.ComponentModel.Composition.Tests\netcoreapp-Windows_NT-Release-arm64>call C:\Users\robox\j\workspace\arm64_cross_c---c55e6c4b\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm64\dotnet.exe xunit.console.netcore.exe System.ComponentModel.Composition.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.ComponentModel.Composition.Tests
Discovered:  System.ComponentModel.Composition.Tests
Starting:    System.ComponentModel.Composition.Tests

Assert failure(PID 8880 [0x000022b0], Thread: 11324 [0x2c3c]): Precondition failure: FAILED: !(section->Characteristics & ~((0x00000020 | 0x00000040 | 0x00000080| 0x02000000 | 0x04000000 | 0x08000000 | 0x20000000 | 0x40000000 | 0x80000000 | 0x10000000)))
	 FAILED: CheckNTHeaders()
		d:\j\workspace\arm64_cross_c---999e2d10\src\inc\pedecoder.inl, line: 713

CORECLR! coreclr_shutdown_2 + 0xFA20 (0x00007ffc`d854ed50)
CORECLR! coreclr_shutdown_2 + 0x5E1BC (0x00007ffc`d859d4ec)
CORECLR! GetCLRRuntimeHost + 0x183018 (0x00007ffc`d8742078)
CORECLR! GC_VersionInfo + 0x1441DC (0x00007ffc`d8cc651c)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ffc`d8011900)
<no module>! <no symbol> + 0x0 (0x00007ffc`7a493f08)
    File: d:\j\workspace\arm64_cross_c---999e2d10\src\utilcode\pedecoder.cpp Line: 356
    Image: C:\Users\robox\j\workspace\arm64_cross_c---c55e6c4b\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm64\dotnet.exe

----- end 14:39:18.36 ----- exit code 123456789 ----------------------------------------------------------
```

Remove exclusion from arm64\corefx_test_exclusions.txt when fixed.

**Comment by BruceForstall** [comment]
Only seen once, in the baseline run, and not in any stress mode runs.

**Comment by kouvel** [comment]
Also seen in https://github.com/dotnet/coreclr/pull/19122 on x86 (with tiering enabled)

**Comment by kouvel** [comment]
Failed in the following jobs in the PR I mentioned above:

```
Windows_NT x86 Checked Build and Test (Jit - CoreFx TieredCompilation=1)
Windows_NT x86_arm_altjit Checked corefx_tieredcompilation
```

**Comment by kouvel** [comment]
No repro on x86 on latest

**Comment by sandreenko** [comment]
Link https://github.com/dotnet/coreclr/pull/18917 where it was disabled.

**Comment by sandreenko** [comment]
I was not able to repro that issue (1000 runs, with/without stress load).

It looks like another instance of the shutdown race issue, there are many instances of it (https://github.com/dotnet/coreclr/search?q=shutdown&type=Issues). It is not arm64 specific and it is not test specific, I think it should not block preview.

@marklio I was told that you can be interested in such kind of issues where we have a race between managed thread and shutdown (for example https://github.com/dotnet/coreclr/issues/11404 or #22159), could you please take a look?

**Comment by marklio** [comment]
Thanks. I am definitely interested in reliability issues. What evidence points to this being linked to the general "callbacks during shutdown" issue? Is it the stack? That stack looks bogus (like no/wrong symbols. The offsets are large, and the call patterns don't make sense). I'm still ramping up on digging into GitHub issues. I'm assuming there's no additional information other than this issue? Hopefully, we'll soon be setup to have more diagnosable failures for things like this.

**Comment by sandreenko** [comment]
> Thanks. I am definitely interested in reliability issues. What evidence points to this being linked to the general "callbacks during shutdown" issue? Is it the stack? That stack looks bogus (like no/wrong symbols. The offsets are large, and the call patterns don't make sense). I'm still ramping up on digging into GitHub issues. I'm assuming there's no additional information other than this issue? Hopefully, we'll soon be setup to have more diagnosable failures for things like this.

I think you won't see this issue again because it happened in a contracts check and it was disabled for arm64 windows. I do not know how to get any additional information for this one, I think  #11404 or #22159 are the best issues to start because they have repro steps).

I will push a PR to reenable this test and close if CI shows that it is green.
