### ISSUE TITLE
Add all integer overloads for Avx2.BlendVariable

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#18910]
Now, we only have the `byte/sbyte` overload for `Avx2.BlendVariable` since the instruction uses the mask vector as a byte sequence.
However, `Avx2.BlendVariable` is very common to use, adding all integer overloads (`short/ushort/int/uint/long/ulong`) will significantly improve the user experience.

cc @tannergooding @CarolEidt @eerhardt

**Comment by saucecontrol** [comment]
If you do it on `Avx2.BlendVariable`, I'd think it should be done on all the byte-shuffle ops.  `Ssse3.Shuffle` would also need them, for example.  

And there are less obvious ones like `Ssse3.AlignRight`.

Now that the `StaticCast` calls get folded, it's strictly a usability issue.  Perhaps the answer is to improve the `StaticCast` to be more terse?

**Comment by fiigii** [comment]
> If you do it on Avx2.BlendVariable, I'd think it should be done on all the byte-shuffle ops. Ssse3.Shuffle would also need them, for example.

Agree, I will investigate it and put here later. Thanks!

> Perhaps the answer is to improve the StaticCast to be more terse?

Don't you mean eliminating `StaticCast` and using implicit conversion of Vector128/256 instead?

**Comment by saucecontrol** [comment]
> Don't you mean eliminating StaticCast and using implicit conversion of Vector128/256 instead?

Yeah, that might be ideal.  I remember seeing the discussions around when generics would be used and when the argument types would be exploded, and while the rules make a lot of sense, there's so much flexibility build into the way the Intel instructs are defined with `__m128i` and `__m256i` that it would mean a ton of overloads to cover everything people will be doing with these instructions.

**Comment by tannergooding** [comment]
> Perhaps the answer is to improve the StaticCast to be more terse?

One of the proposals here was to partially explode the `StaticCast` methods. That is, where today you have `Vector128<U> StaticCast<T, U>(Vector128<T>)` you could instead do `Vector128<T> StaticCast<T>(Vector128<float>)` (and explode the other 9 types as well). This makes it significantly less verbose.

> using implicit conversion of Vector128/256 instead?

I don't think implicit conversions are a good idea, and they aren't supported with some languages (such as F#).

**Comment by tannergooding** [comment]
As for the general proposal. I think it would depend on how confusing it is perceived to pass in a `Vector128<int>` but operate as if it was a `Vector128<byte>`.

**Comment by saucecontrol** [comment]
> you could instead do Vector128<T> StaticCast<T>(Vector128<float>)

I like this idea a lot.

> I think it would depend on how confusing it is perceived to pass in a Vector128<int> but operate as if it was a Vector128<byte>.

I think it goes back to the target audience for these.  You have to assume the user knows what the instruction does, and if the instruction operates on the byte level, I'd know that if I were calling it, regardless of the argument types.

**Comment by tannergooding** [comment]
> Also also, let's say that doesn't make it past API review... If I were to define my own partially exploded Cast, would that get inlined and then folded away same as the official one?

Provided it called the underlying `StaticCast` methods, it should.

**Comment by 4creators** [comment]
> One of the proposals here was to partially explode the StaticCast methods. That is, where today you have Vector128<U> StaticCast<T, U>(Vector128<T>) you could instead do Vector128<T> StaticCast<T>(Vector128<float>) (and explode the other 9 types as well).

Proposal to simplify `StaticCast<T, U>` API is here:  https://github.com/dotnet/corefx/issues/27911#issuecomment-372684004
