### ISSUE TITLE
Hardware Intrinsics:  Non-volatile xmm regs unnecessarily spilled to stack

### ISSUE THREAD

**Issue by Zhentar** [dotnet/coreclr#18925]
Even though my code only actually needs a total of 4 SSE registers, in some cases the JIT is deciding to use `xmm6`,`xmm7`, and `xmm8`, spilling them to the stack.

```asm
DelimitedFileParser.SpanXxHash32.SSEImpl(System.ReadOnlySpan`1<Byte> ByRef)
	sub     rsp,68h
	vmovaps xmmword ptr [rsp+50h],xmm6
	vmovaps xmmword ptr [rsp+40h],xmm7
	vmovaps xmmword ptr [rsp+30h],xmm8
	xor     eax,eax
	mov     qword ptr [rsp+20h],rax
	mov     qword ptr [rsp+28h],rax
	mov     rdx,rcx
;				var vals = Sse2.SetVector128(0 - PRIME32_1, 0, PRIME32_2, PRIME32_1 + PRIME32_2);
	xor     ecx,ecx
	vmovd   xmm0,ecx
	mov     ecx,85EBCA77h
	vmovd   xmm1,ecx
	mov     ecx,24234428h
	vmovd   xmm2,ecx
	vpunpckldq xmm2,xmm2,xmm0
	mov     ecx,61C8864Fh
	vmovd   xmm0,ecx
	vpunpckldq xmm1,xmm1,xmm0
	vpunpckldq xmm6,xmm2,xmm1
;				var prime32_1 = Sse2.SetAllVector128(PRIME32_1);
	mov     ecx,9E3779B1h
	vmovd   xmm0,ecx
	vpshufd xmm7,xmm0,0
;				var prime32_2 = Sse2.SetAllVector128(PRIME32_2);
	mov     ecx,85EBCA77h
	vmovd   xmm0,ecx
	vpshufd xmm8,xmm0,0
	lea     rcx,[rsp+20h]
	call    DelimitedFileParser.SpanXxHash32.TakeFrom[[System.Runtime.Intrinsics.Vector128`1[[System.UInt32, System.Private.CoreLib]], System.Private.CoreLib],[System.Byte, System.Private.CoreLib]](System.ReadOnlySpan`1<Byte> ByRef)
	cmp     dword ptr [rsp+28h],0
	jne     M14_L00
;				if (vecBuff.IsEmpty) { return PRIME32_5; }
;				                       ^^^^^^^^^^^^^^^^^
	mov     eax,165667B1h
	vmovaps xmm6,xmmword ptr [rsp+50h]
	vmovaps xmm7,xmmword ptr [rsp+40h]
	vmovaps xmm8,xmmword ptr [rsp+30h]
	add     rsp,68h
	ret
;				for (int i = 0; i < vecBuff.Length; i++)
;				     ^^^^^^^^^
M14_L00
	xor     eax,eax
	cmp     dword ptr [rsp+28h],0
	jle     M14_L02
;					var buffVals = vecBuff[i];
M14_L01
	mov     rdx,qword ptr [rsp+20h]
	movsxd  rcx,eax
	shl     rcx,4
	vmovupd xmm0,xmmword ptr [rdx+rcx]
;					var buffMult = Sse.StaticCast<int, uint>(Sse41.MultiplyLow(
;											Sse.StaticCast<uint, int>(buffVals),
;											Sse.StaticCast<uint, int>(prime32_2)));
	vpmulld xmm0,xmm0,xmm8
;					vals = Sse2.Add(vals, buffMult);
	vpaddd  xmm6,xmm6,xmm0
;					var toTheLeft = Sse2.ShiftLeftLogical(vals, 13);
	vpslld  xmm0,xmm6,0Dh
;					var toTheRight = Sse2.ShiftRightLogical(vals, 32 - 13);
	vpsrld  xmm1,xmm6,13h
;					vals = Sse2.Or(toTheLeft, toTheRight);
	vpor    xmm6,xmm0,xmm1
;					vals = Sse.StaticCast<int, uint>(Sse41.MultiplyLow(
;											Sse.StaticCast<uint, int>(vals),
;											Sse.StaticCast<uint, int>(prime32_1)));
	vpmulld xmm6,xmm6,xmm7
;				for (int i = 0; i < vecBuff.Length; i++)
;				                                    ^^^
	inc     eax
	cmp     eax,dword ptr [rsp+28h]
	jl      M14_L01
;				uint v1 = Sse41.Extract(vals, 0);
M14_L02
	vpextrd eax,xmm6,0
;				uint v2 = Sse41.Extract(vals, 1);
	vpextrd edx,xmm6,1
;				uint v3 = Sse41.Extract(vals, 2);
	vpextrd ecx,xmm6,2
;				uint v4 = Sse41.Extract(vals, 3);
	vpextrd r8d,xmm6,3
;				return MergeValues(v1, v2, v3, v4);
	rol     eax,1
	rol     edx,7
	add     eax,edx
	rol     ecx,0Ch
	add     eax,ecx
	rol     r8d,12h
	add     eax,r8d
	vmovaps xmm6,xmmword ptr [rsp+50h]
	vmovaps xmm7,xmmword ptr [rsp+40h]
	vmovaps xmm8,xmmword ptr [rsp+30h]
	add     rsp,68h
	ret
```
Full code: [SpanXxHash32.cs.txt](https://github.com/dotnet/coreclr/files/2195999/SpanXxHash32.cs.txt)

**Comment by tannergooding** [comment]
FYI. @CarolEidt, @fiigii 

@CarolEidt, does the register allocator currently have any smarts here on which registers it should prefer from the XMM/YMM pool?

**Comment by voinokin** [comment]
It looks like XMM6-8 were chosen due to the presence of `DelimitedFileParser.SpanXxHash32.TakeFrom()` call. JIT doesn't seem to analyze nested calls, so it decides to allocate storage as "caller-saved" for later re-use. There are no non-inlineable methods within the loop after the nested method call mentioned above, so the range XMM0-5 is available.

**Comment by Zhentar** [comment]
Ah, yeah, okay, that makes sense. Is that something it reasonably could/should reorder or otherwise handle better? Or should this just be closed?

**Comment by voinokin** [comment]
...Moveover, I think you'd see bunch of `VEXTRACTxx` and `VINSERTxx` around the method call code if you'd have 256-bit SIMD variables (see #18144).

**Comment by voinokin** [comment]
@Zhentar 
> Ah, yeah, okay, that makes sense. Is that something it reasonably could/should reorder or otherwise handle better? Or should this just be closed?

Well... my opinion is that in ideal world :-) JIT would have more advanced analysis. But until that happens, I prefer to place SIMD setup code *AFTER* any method invocations. The longer story is - if you have to deal with vectors expressed as generics method parameters, and you expect any of 128- or 256-bit vectors, you have to other choice for now. Here's example:

```
        [MethodImpl(MethodImplOptions.NoInlining)]
        unsafe static ulong GetKeyPartsFissionedMultiKey256x256Specialized<
            TPermuteBuffer256, TKeysDataRetrievalCookie256,
            TMultiKeyOps256, TMultiKeyPartsPreparationCookie,
            TUseKeyPartOfst /*use when bool*/>(

            ref TPermuteBuffer256 permuteBufferRef, ulong recordsBaseIndex, ulong recordsCount,
            ref TMultiKeyOps256 multiKeyOpsRef, ulong keyPartOfst)

            where TPermuteBuffer256 : TPermuteBuffer, ISortPermuteBuffer256<TPermuteBufferIndexer, TKeysDataRetrievalCookie256>
            where TKeysDataRetrievalCookie256 : struct

            where TMultiKeyOps256 : TKeyOps, ISortMultiKeyOps256<
                TComparableKeyPart, TMinMaxKeyPartAggregate, TKeyPartsPreparationCookie, TMultiKeyPartsPreparationCookie,
                TKeysLCPInfo>
            where TMultiKeyPartsPreparationCookie : struct

        {
            // Returns amount of records processed

            bool useKeyPartOfst = (typeof(TUseKeyPartOfst) == typeof(bool));

            ulong iterationsTotal = 0;
            if (KeyPartsInVector256 < 4 || KeyPartsInVector256 > 16) throw new NotSupportedException();
            if (!permuteBufferRef.IsHardwareAccelerated256 || !multiKeyOpsRef.IsHardwareAccelerated256) throw new NotSupportedException();

            iterationsTotal = recordsCount / (uint)KeyPartsInVector256;
            if (iterationsTotal == 0) goto Done;

======= non-inlineable invocations go here
            ref TPermuteBufferIndexer permuteBufferIndexer = ref permuteBufferRef.GetIndexer((long)recordsBaseIndex);
            Sse.Prefetch0(Unsafe.AsPointer(ref permuteBufferIndexer));

            void* pKeysDataBase = permuteBufferRef.GetKeysDataBase(); 

====== SIMD setup starts here
            Vector256<int> keyPartStartOfsts = Avx.SetAllVector256((int)keyPartOfst);
            Vector256<int> maxKeyPartLengths = Avx.ExtendToVector256(Sse2.SetAllVector128((int)multiKeyOpsRef.MaxKeyPartLength));

====== these 3 vars could in fact be SIMD vectors with dimension determined by TMultiKeyOps256 implementation
            TKeysDataRetrievalCookie256 keysDataRetrievalCookie256 = permuteBufferRef.GetKeysDataRetrievalCookie256();
            TKeyPartsPreparationCookie keysPrepCookie = multiKeyOpsRef.GetKeyPartsPreparationCookie();
            TMultiKeyPartsPreparationCookie multiKeysPrepCookie = multiKeyOpsRef.GetMultiKeyPartsPreparationCookie256();

            Vector256<int> onesI32 = Avx.SetAllVector256((int)1);

            ulong iterationsLeft = iterationsTotal;
            do
            {
                 ......
```

**Comment by AndyAyersMS** [comment]
> JIT doesn't seem to analyze nested calls

The execution model in .Net Core / .Net Framework allows method bodies to be changed after they're jitted (say via the profile API or by tiered rejitting). So it's not possible in general for the JIT to propagate low-level facts -- for instance the actual register kill sets -- about a method from callee to caller.

And from a practical standpoint, the JIT tends to process callers before callees, so even for things like general performance "hints"  (eg the callee is likely to throw) there is no organic opportunity to observe the callee's generated code before the caller's code.

So our main mechanism right now for interprocedural optimization is inlining. The cross-method dependences introduced by inlining are carefully tracked by the jit and runtime so that if you inline B into A and then modify B, the runtime knows that A must also be rejitted.

**Comment by CarolEidt** [comment]
Thanks @voinokin for sharing your insights - they are spot-on. In the ideal world it would be great to have summary analysis of downstream methods, but @AndyAyersMS describes some of the reasons why that's difficult. One might imagine a cache of such summary information that could be consulted by a tiered JIT, but of course that would rely on the "ideal world" capability of invalidating and re-jitting code that has incorporated reliance on such cached information.

There are a number of near-term improvement that could be made to the JIT would be to improve the handling of the ymm registers, as indicated in #17481 and #18144. I also thought there was an issue to improve the heuristics for using callee-save registers, taking into account the cost of the save & restore code (i.e. sometimes it would be cheaper to spill and/or use/define directly from memory), but I can't find such an issue at the moment.

**Comment by Zhentar** [comment]
I'll close this one as "pie in the sky" then 😄
