### ISSUE TITLE
Update the `ConvertToDouble`, `ConvertToSingle`, and `GetLowerHalf` HWIntrinsics to be nops

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#18949]
These helper methods exist purely to satisfy the type system (much in the same way as `StaticCast`). We should update them to be nops.

**Comment by tannergooding** [comment]
FYI. @CarolEidt, @fiigii, @RussKeldorph, @eerhardt

**Comment by fiigii** [comment]
@tannergooding Please update the title.

**Comment by tannergooding** [comment]
Going to close this one as it will be resolved in https://github.com/dotnet/coreclr/pull/21351, and any work to improve the codegen further will likely be part of a larger effort.
