### ISSUE TITLE
Assertion failure on Unixes in JIT/SIMD/VectorExp_ro with tiering enabled

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#18945]
```
11:35:59 FAILED   - JIT/SIMD/VectorExp_ro/VectorExp_ro.sh
11:35:59                BEGIN EXECUTION
11:35:59                /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun VectorExp_ro.exe
11:35:59                
11:35:59 
               Assert failure(PID 117174 [0x0001c9b6], Thread: 117174 [0x1c9b6]): Assertion failed 'arg->OperGet() == GT_LCL_VAR' in 'VectorExpTest`1[Int64][System.Int64]:VectorExp(struct,long,long,long):int' (IL size 148)
11:35:59                
11:35:59                    File: /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_innerloop_prtest/src/jit/morph.cpp Line: 4628
11:35:59                    Image: /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun
11:35:59                
11:35:59                ./VectorExp_ro.sh: line 248: 117174 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
11:35:59                Expected: 100
11:35:59                Actual: 134
11:35:59                END EXECUTION - FAILED
```

Examples from test PR https://github.com/dotnet/coreclr/pull/18611:
- https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_innerloop_tst_prtest/4533/consoleFull#-372034708f66db340-b3cd-4e23-8190-9b52cb916333
- https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_tst_prtest/4117/consoleFull#692939362f66db340-b3cd-4e23-8190-9b52cb916333
- https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_centos7.1_innerloop_tst_prtest/4492/consoleFull#1121768594f66db340-b3cd-4e23-8190-9b52cb916333

Seems to repro consistently at the moment, seems unrelated to tiering and other changes in the PR above. Use last commit from PR above to repro, it may also repro with the equivalent environment variables. In one run, `arg->gtOper == GT_COMMA`.

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

**Comment by kouvel** [comment]
Duplicate of https://github.com/dotnet/coreclr/issues/19124
