### ISSUE TITLE
.NET CORE console appliation crashes randomly on RaspberryPi (mode: 3B+, Linux ARM32)

### ISSUE THREAD

**Issue by shaojun** [dotnet/coreclr#18958]
# Issue Title

My .NET CORE (runtime version 2.1.1) console application crashes randomly on RaspberryPi (mode: 3B+, Linux ARM32, Debian 9)

# General
I have an application that just open 8 tcp connections for read and write, the data rate for each connection is about 200Byte/second, in most case the application can runs well, but sometime later, like 7 or 8 hours, it randomly crashes, I have attached the `AppDomain.CurrentDomain.UnhandledException` with logging but in these cases it never get called, and I have seem some extra info shown in console before application crashes and quit, they are:

> ./myApp: relocation error: /pathToMyApp/libclrjit.so: symbol pthread_, version GLIBC_2.4 not defined in file libpthread.so.0 with link time reference

and

>Bus error

and

>Aborted

Later, I've add my app to daemon mode, and this time I can see sth in syslog:

> Jul 17 08:30:51 raspberrypi systemd[1]: myApp.service: Main process exited, code=killed, status=6/ABRT
> Jul 17 08:30:51 raspberrypi systemd[1]: myApp.service: Unit entered failed state.
> Jul 17 08:30:51 raspberrypi systemd[1]: myApp.service: Failed with result 'signal'.
> Jul 17 08:31:01 raspberrypi systemd[1]: myApp.service: Service hold-off time over, scheduling restart.

I've logged the performance counters all the way, can see the CPU and memory are all stable.
I've tried followed the [enable core dump on linux](http://blogs.microsoft.co.il/sasha/2017/02/26/analyzing-a-net-core-core-dump-on-linux/) but could never see any dump files generated, please help.

**Comment by BruceForstall** [comment]
@shaojun Does the issue still occur? Have you tried .NET Core 2.2 or .NET Core 3.0?

**Comment by shaojun** [comment]
it has been fixed
