### ISSUE TITLE
EventWaitHandle.OpenExisting("".PadLeft(512)) is throwing ArgumentException instead of 

### ISSUE THREAD

**Issue by cshung** [dotnet/coreclr#18968]
The following test outputted "Pass" in .NET Core 2.1 and is now outputting "Fail" with the latest CoreCLR in the master branch.

```
using System;
using System.Threading;

namespace Event
{
    internal static class Program
    {
        static void Main(string[] args)
        {
            try
            {
                EventWaitHandle.OpenExisting("".PadLeft(512));
            }
            catch (ArgumentException)
            {
                Console.WriteLine("Pass");
            }
            catch (WaitHandleCannotBeOpenedException)
            {
                Console.WriteLine("Fail");
            }
        }
    }
}
```

It is probably caused by the removal of the validation on path length:
https://github.com/dotnet/coreclr/commit/422b0e81797d5428812c6ef825e22565e2dc63f3

To reproduce it:

1. Create a .NET Core application
2. Modify the csproj to add `<RuntimeIdentifier>win-x64</RuntimeIdentifier>` under the PropertyGroup tag.
3. `dotnet publish --self-contained`
4. Run the build executable, it should output "Pass".
5. Build the latest master CoreCLR and copy the new binaries on top of the published ones.
6. Run the build executable, it should output "Fail".

**Comment by jkotas** [comment]
Mutex on Unix checks for `ERROR_FILENAME_EXCED_RANGE` because of there is actual length limit on Unix.

There is no actual limit on Windows.

I do not think we need to be doing unnatural things to preserve the exception type here.
