### ISSUE TITLE
Publish looks in wrong folder for dependency

### ISSUE THREAD

**Issue by ghosttie** [dotnet/coreclr#18974]
I have a project targeting .NET Core 2.1 that has a reference to a project targeting .NET Standard 2.0.

Everything compiles and runs fine, but when I try to publish, it fails with this error:

> Metadata file 'C:\projects\asp.net\Project Name\Project Name.BusinessLogic\bin\Release\netcoreapp2.1\Project Name.BusinessLogic.dll' could not be found

It appears to be looking for a nonexistent \netcoreapp2.1\ directory instead of \netstandard2.0\ where the dll actually is.

I think it might be using the referencing project's target rather than the referenced project's target to construct the path, but I could be wrong.

EDIT: on reflection, this might be the wrong project to report this to - can someone give me direction to the correct project?

**Comment by jkotas** [comment]
This issue was moved to dotnet/cli#9690
