### ISSUE TITLE
Enable tiered compilation by default

### ISSUE THREAD

**Issue by richlander** [dotnet/coreclr#18973]
# Enable tiered compilation by default

Tiered compilation was added as an optional feature in .NET Core 2.1. It has been demonstrated that the [feature has a lot of value](https://github.com/dotnet/coreclr/issues/18361#issuecomment-396402549). We have done additional test runs that show similar gains.

There have been some reports of [degradation due to tiered compilation](https://github.com/dotnet/coreclr/issues/18361). We believe that these cases are in the narrow minority.

We would like to do the following:

- Enable tiered compilation by default in the first .NET Core 2.2 preview.
- Enable an opt-out of the feature. It is opt-in right now.
- Collect user feedback on the feature to make a decision if the feature works well enough to ship in 2.2 enabled.

We would make the same changes in master (AKA .NET Core 3.0) at the same time.

If that doesn't work out, we could keep the feature as opt-in and enable it in some set of templates. This option isn't a proposal and would be dissapointing

Relevant links:

* https://github.com/dotnet/coreclr/issues/4331
* https://github.com/dotnet/coreclr/pull/17840
* https://github.com/dotnet/sdk/pull/2201
* https://github.com/dotnet/coreclr/issues/18361

**Comment by richlander** [comment]
Fixed. Thanks!

**Comment by benaadams** [comment]
Will this use the cross-gen'd code when available; falling back to tier 1 jit when not; then moving to tier 2 in hot paths? (i.e. use crossgen'd in preference to tier 1 jit)

**Comment by mattwarren** [comment]
Just a minor thing, but the markdown around `{feature has a lot of value]` is borked and not rendering correctly

**Comment by kouvel** [comment]
Closing based on https://github.com/dotnet/coreclr/pull/19691
