### ISSUE TITLE
Ensure .NET Core respects and plays nicely with Docker limits

### ISSUE THREAD

**Issue by richlander** [dotnet/coreclr#18971]
Docker enables you to [limit a container's resources](https://docs.docker.com/config/containers/resource_constraints/). This control is great for high-density hosting and other low-resource scenarios. Developers have the expectation that the application platform respects these limits and does its best to work within them.

I wrote a [crude test framework](https://github.com/richlander/dotnet-docker-limits) to determine how .NET Core behaves when various resource limits are set. You can see the [test results](https://gist.github.com/richlander/48bb0ad51a2406937b61bea01de7cf87).

The results I saw made some sense -- workstation performed better than server gc in this environment -- however some other characteristics were surprising. It could be that my tests were flawed.

Our first goal is to provide developers with guidance. For example, if there a minimum memory limit that is required to run an app in production? Is server gc currently safe to run with docker limits?

Our next goal is to update the product, as appropriate, to ensure that it works well with Docker limits, and then to update guidance appropriately.

Once we are done, I'd like to re-run this test suite following the guidance. I/we should be able to pick a lower bound number (this app is very simple) and expect it to run w/o memory exhaustion.

[My app](https://github.com/richlander/dotnet-docker-limits/tree/master/src/aspnetapi) is very simple. There will be apps run in containers that require running on multiple cores and take advantage of server GC. Is that appropriate for docker limits, or is there a minimum memory level of 250mb, for example, for that scenario? We should probably find a different test app that better exhibits the behavior of this type of app.

**Comment by kouvel** [comment]
@kouvel

**Comment by richlander** [comment]
Working on a solution:

- [Design](https://github.com/dotnet/designs/pull/49)
- [Implemementation](https://github.com/dotnet/coreclr/pull/22180)

**Comment by luhenry** [comment]
@richlander most of the work so far has been focused on making it work nicely in Docker for Linux images. Is the plan also to improve the support of Docker for Windows images, like `microsoft/nanoserver` image for example?

**Comment by sergiy-k** [comment]
@richlander, I assume this can be closed now based on the work that @luhenry and @Maoni0 did, right?

**Comment by RussKeldorph** [comment]
@richlander Ping

**Comment by sergiy-k** [comment]
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-3/
