### ISSUE TITLE
[arm64] Assertion failed '(sizeDif == 4) || (sizeDif == 8)' in 'floatMDArrTest:Main():int'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#18989]
Failure in
```
Tests.lst=float_cs_ro.cmd_7350, , , Smrt00000001, , # JIT\Methodical\MDArray\DataTypes\float_cs_ro\float_cs_ro.cmd  CATS: JIT;EXPECTED_PASS;Pri1
```

with:
```
COMPlus_JitStress -> 2
COMPlus_JitStressRegs -> 4
COMPlus_TieredCompilation -> 0
```

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_jitstress2_jitstressregs4_tst/32/

```
TEST_CMD_LINE: JIT\Methodical\MDArray\DataTypes\float_cs_ro> C:\Users\robox\j\workspace\arm64_cross_c---0ae079d7\bin\tests\Windows_NT.arm64.Checked\JIT\Methodical\MDArray\DataTypes\float_cs_ro\float_cs_ro.cmd 

BEGIN EXECUTION
 "C:\Users\robox\j\workspace\arm64_cross_c---0ae079d7\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root\corerun.exe" float_cs_ro.exe 

Assert failure(PID 24364 [0x00005f2c], Thread: 18392 [0x47d8]): Assertion failed '(sizeDif == 4) || (sizeDif == 8)' in 'floatMDArrTest:Main():int' (IL size 9417)

    File: d:\j\workspace\arm64_cross_c---0aaef436\src\jit\emit.cpp Line: 4033
    Image: C:\Users\robox\j\workspace\arm64_cross_c---0ae079d7\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: 123456789
END EXECUTION - FAILED
FAILED
```

**Comment by BruceForstall** [comment]
@dotnet/arm64-contrib @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
This also fails on Linux/arm64 with 
1. `JitStress=2`, `JitStressRegs=3`
2. `JitStress=2`, `JitStressRegs=8`

https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs3_tst_prtest/1/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs8_tst_prtest/1/consoleFull

**Comment by briansull** [comment]
I could not repro this issue using my Desktop Windows system using the AltJit:

C:\fxkit\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\Methodical\MDArray\DataTypes\float_cs_ro>set comp
COMPLUS_AltJit=*
COMPLUS_AltJitName=protononjit.dll
COMPLUS_JitStress=2
COMPLUS_JitStressRegs=4
COMPLUS_TieredCompilation=0

C:\fxkit\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\Methodical\MDArray\DataTypes\float_cs_ro>C:\fxkit\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe float_cs_ro.exe
PASSED

**Comment by CarolEidt** [comment]
@briansull - I have encountered a number of places where an issue doesn't repro with the AltJit. Some of those I've addressed by adding HFA support to the altjit, but there are other cases where the differences in VM behavior cause differences in the IL we see, or the responses to VM queries.
You'll need to determine whether the bug still exists on actual hardware.

**Comment by briansull** [comment]
This test is passing on Arm64 hardware:

```
f:\coreclr\bin\tests\Windows_NT.arm64.Checked\JIT\Methodical\MDArray\DataTypes\float_cs_ro>float_cs_ro.cmd
BEGIN EXECUTION
 "f:\coreclr\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root\corerun.exe" float_cs_ro.exe
PASSED
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED

f:\coreclr\bin\tests\Windows_NT.arm64.Checked\JIT\Methodical\MDArray\DataTypes\float_cs_ro>set CO
COMPLUS_JitStress=2
COMPLUS_JitStressRegs=4
COMPLUS_TieredCompilation=0
COMPUTERNAME=CLRJITCOBALT2
CORE_ROOT=f:\coreclr\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root
```

**Comment by BruceForstall** [comment]
@briansull Please submit a PR to remove this from issues.targets:
```
<ExcludeList Include="$(XunitTestBinBase)/JIT/Methodical/MDArray/DataTypes/float_cs_ro/*">
    <Issue>18989</Issue>
</ExcludeList>
```
