### ISSUE TITLE
Ubuntu IL linker test failures in CI

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19007]
This job is failing every test:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/illink/job/x64_checked_ubuntu_illink_flow/

e.g.:
```
FAILED   - baseservices/compilerservices/dynamicobjectproperties/Dev10_535767/Dev10_535767.sh
               BEGIN EXECUTION
               Illink executable [/mnt/j/workspace/dotnet_coreclr/master/illink/x64_checked_ubuntu_illink_tst/linker/linker/bin/netcore_Release/netcoreapp2.0/ubuntu-x64/publish/illink] Invalid
```

Note that there is also a non-flow Ubuntu x64 IL linker test job:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/illink/job/x64_checked_ubuntu_illink/

This one passes, but it doesn't look like it's actually doing any interesting testing. I'm not sure this is a related issue or not. If not, create a new issue to address removing one of them (if necessary).

**Comment by BruceForstall** [comment]
@sbomer @erozenfeld @swaroop-sridhar

**Comment by BruceForstall** [comment]
(misc. other note: the debug and release jobs have never run. Should they be deleted? Or scheduled to run periodically?)

**Comment by RussKeldorph** [comment]
@jeffschwMSFT I probably shouldn't have stashed this under `area-ILTools`.  Resetting triage.  I assume this is `Future` but feel free to make the call.

**Comment by sbomer** [comment]
Closing in favor of https://github.com/dotnet/coreclr/issues/25239.
