### ISSUE TITLE
Jit fails to build under VS 2015 RC1

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#1902]
Use of static operator new is no longer supported.

This is being used inside alloc.h to assert if anyone uses new or delete.

**Comment by jashook** [comment]
Have a fix, about to submit a PR.

**Comment by bryanar** [comment]
Just an FYI: Just came here to see if this was being talked about, https://connect.microsoft.com/VisualStudio/feedback/details/1401729/operator-delete-source-compatibility-break

**Comment by jashook** [comment]
That is correct, it is the same issue.

**Comment by jashook** [comment]
Checked in.
