### ISSUE TITLE
Include and ThenInclude sub properties causes System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct

### ISSUE THREAD

**Issue by harsha89vyas** [dotnet/coreclr#19027]
The following include sequence causes the **System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct**
.Include(x => x.A)
                                                        .ThenInclude(x => x.B)
                                                        .ThenInclude(x => x.C)
                                                     .Include(x => x.A)
                                                        .ThenInclude(x => x.B)
                                                        .ThenInclude(x => x.D)
                                                        .ThenInclude(x => x.E)
                                                     .Include(x => x.A)
                                                        .ThenInclude(x => x.B)
                                                        .ThenInclude(x => x.D)
                                                        .ThenInclude(a => a.F)
                                                     .Include(x => x.A)
                                                        .ThenInclude(x => x.B)
                                                        .ThenInclude(x => x.D)
                                                        .ThenInclude(a => a.G)
                                                     .Include(x => x.A)
                                                        .ThenInclude(x => x.B)
                                                        .ThenInclude(x => x.D)
                                                        .ThenInclude(a => a.C)
                                                        .ThenInclude(a => a.H)

This happens due to the fix https://github.com/dotnet/coreclr/pull/16991 applied due to issue https://github.com/dotnet/corefx/issues/28123

**Comment by benaadams** [comment]
Added an issue to corefx so its easier to find information about this exception in search dotnet/corefx#31186

**Comment by RussKeldorph** [comment]
This issue was moved to aspnet/EntityFrameworkCore#12926
