### ISSUE TITLE
Arm64: Verify that IP0/IP1 are reserved as needed for jumps

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#19034]
IP0/IP1 are reserved in the ABI for linking stubs. Any branch with target out of range is free to contaminate these.
The register allocator needs to ensure that either 1) no lclVar is allocated to those registers at block end, or 2) they are being reserved (elsewhere) if a branch may be out of range.

**Comment by CarolEidt** [comment]
Currently, IP1 is always being reserved, see https://github.com/dotnet/coreclr/issues/18190 (`REG_OPT_RSVD` is defined to be `REG_IP1` on arm64).

**Comment by CarolEidt** [comment]
IP0 is used as `REG_INDIRECT_CALL_TARGET_REG` and `REG_FASTTAILCALL_TARGET`, however it only appears to be used for the latter, and is reserved during register allocation in that context.
For the former, there is code in `CodeGen::genCallInstruction()` (codegenarmarch.cpp) that is #ifdef'd out that uses it for a call target address.

**Comment by CarolEidt** [comment]
@sdmaclea - I believe that you were the one that indicated that IP0/IP1 are reserved in the ABI for linking stubs. I don't see anywhere that they are used for that purpose by the JIT, and any call stub would already be modeled as killing those registers. Is there something I'm missing, or can I close this issue?

**Comment by sdmaclea** [comment]
Sorry I saw this while I was in class last week.  I'll take a look.

**Comment by sdmaclea** [comment]
I think your survey seems to be sufficient to close this.  There is a NYI which would also use IP1/REG_OPT_RSVD, but seems it is covered as mentioned above.  Thanks @CarolEidt

**Comment by CarolEidt** [comment]
@sdmaclea - Thanks!
I'll close.
