### ISSUE TITLE
Assembly analysis without reflection

### ISSUE THREAD

**Issue by Korporal** [dotnet/coreclr#19038]
There is sometimes a need to examine the internals of assemblies for various things, like does the assembly contain class X or does it have some attribute Y etc. Using reflection and the various load options is fine for many cases but not all.

For example it's not easy to load an assembly by some tool if the app that uses it uses version overrides in its config file, this is because to load the assembly requires its referenced assemblies to also be loaded and this only works under specific circumstances, the app can load a different version to the one in the parent manifest because it "knows about" the overrides, but a tool or utility has no idea about these overrides and may fail to load assembly A1 if the version of a referenced assembly file A2 differs from the version defined in the A1 manifest.

If we just want to open some DLL file and examine it for _certain_ things then it must be possible to do this without using reflection because the file format is well defined (as an [ECMA standard](https://www.ecma-international.org/publications/standards/Ecma-335.htm)).

Does anyone know if anything exists to let me analyze assembly files in some way without relying on reflection, loading and so on?

**Comment by jkotas** [comment]
There are multiple options you can choose from. The main ones are:

https://www.nuget.org/packages/System.Reflection.Metadata/ - lower level reader
https://www.nuget.org/packages/Mono.Cecil - higher level object model
