### ISSUE TITLE
.Net Core and IoThread

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/coreclr#19056]
In the [document](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md) , I not found any about IoThread message, .NET Core has no IoThread?

**Comment by jkotas** [comment]
I am not sure what you mean by ioThread. Could you please what you mean by ioThread ? What is the problem you are trying to solve with it?

**Comment by davidfowl** [comment]
Yes it has the same setup as .net Framework with respect to IO threads specifically on Windows. Linux is completely different
