### ISSUE TITLE
Pri-1 tests broken as of #18695

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#19075]
All pri-1 JitStress jobs started failing after https://github.com/dotnet/coreclr/pull/18695 was merged.

I have validated locally that reverting f5f9a3456abcfdea5d886fededaa0265c80281ed fixes the issue.

**Comment by tannergooding** [comment]
FYI. @jashook, @AaronRobinsonMSFT, @sbomer

**Comment by jashook** [comment]
Should have some time today/tomorrow to look. If I do not get to it by Monday ill assign to Sven.

**Comment by tannergooding** [comment]
@AaronRobinsonMSFT, see https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitstress1/577/ for more details.

Build succeeds, running tests fails with:
```
The command "D:\j\workspace\x64_checked_w---02832afb\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe D:\j\workspace\x64_checked_w---02832afb\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\xunit.console.dll
...
-parallel all -html D:\j\workspace\x64_checked_w---02832afb\tests\..\bin\Logs\TestRun_Windows_NT__x64__Checked.html -xml D:\j\workspace\x64_checked_w---02832afb\tests\..\bin\Logs\TestRun_Windows_NT__x64__Checked.xml  -notrait category=outerloop -notrait category=failing" exited with code -532462766
```

**Comment by tannergooding** [comment]
All other JitStress jobs that run pri1 tests (and that I looked at, which was a number of them) have the same failures. Some quick PR links are on the failures here: https://github.com/dotnet/coreclr/pull/19062

**Comment by jashook** [comment]
I am able to repro the failure locally by passing testenv. It looks as if the pri1 tests are actually building correctly, I have a feeling that the test env being passed along is broken.

Will investigate further.

**Comment by sbomer** [comment]
Thanks for looking into this @jashook! I noticed the following in the PR failure @tannergooding linked:
```Unhandled` Exception: System.ArgumentException: file not found: D:\j\workspace\x64_checked_w---02832afb\tests\\..\bin\tests\Windws_NT.x64.Checked\\readytorun\DynamicMethodGCStress``` - note the "Windws". This makes me think we're hitting https://github.com/Microsoft/msbuild/issues/2530.
