### ISSUE TITLE
Cross platform PInvoke - returning strings to .NET core 2.0

### ISSUE THREAD

**Issue by MattWorkWeb** [dotnet/coreclr#19082]
I need to have my C++ dll return a string to .NET core 2.0 wrapper.   I want .NET to free up string when appropriate, and not have to make explicit call back to C++ to deallocate string.  I've been able to do this successfully if I use CoTaskMemAlloc() (in Windows) to allocate the memory for string on C++ side but CoTaskMemAlloc is not supported in Linux.  Windows C++ solution with CoTaskMemAlloc:

**[.NET code]**
        [DllImport(EngineDllFullPath, CallingConvention = CallingConvention.Cdecl)]
        [return: MarshalAs(UnmanagedType.LPStr)]
        public static extern string getText();

        public static string GetValue()
        {
            string s = getText();  // No need to free; .NET will take care of it
            return s;
        }

**[Unmanaged C++ code]**
       char* getText()
       {
          ...
          char* s = (char*)::CoTaskMemAlloc(size);
          ...
          return s;
       }

Is there a cross platform solution to this that doesn't use CoTaskMemAlloc that can compile/run on windows and linux?

Thanks

**Comment by jkotas** [comment]
Forward CoTaskMemAlloc/Free to a regular malloc/free on non-Windows. E.g. it is what the interop tests do: https://github.com/dotnet/coreclr/blob/fa6222d52a81c24077206cf5082b2f3967e67ebc/tests/src/Common/Platform/platformdefines.h#L139

**Comment by AaronRobinsonMSFT** [comment]
@jkotas is right. He pointed out the global test definition. In the Interop test directory itself we have also defined it explcitly:

https://github.com/dotnet/coreclr/blob/fa6222d52a81c24077206cf5082b2f3967e67ebc/tests/src/Interop/common/xplatform.h#L119

**Comment by AaronRobinsonMSFT** [comment]
@MattWorkWeb I have created an issue for documenting or creating an example for this. See #19090.

**Comment by AaronRobinsonMSFT** [comment]
Moved to dotnet/docs#6629
