### ISSUE TITLE
[Ubuntu/arm][GCStress=0xC][JitStress] GC/API/WeakReference/Finalize2

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#19085]
This has failed three times while testing PR #18784 in

[Ubuntu arm Cross Checked gcstress0xc_jitstress1 Build and Test](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_jitstress1_tst_prtest/8/consoleText)
[Ubuntu arm Cross Checked gcstress0xc_jitstress2 Build and Test](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst_prtest/9/consoleText)
```
FAILED   - GC/API/WeakReference/Finalize2/Finalize2.sh
               BEGIN EXECUTION
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress1_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun Finalize2.exe
               Running ~GetTargetTest
               getTarget passed
               
               Running ~IsAliveTest
               IsAliveTest passed
               
               Running ~SetTargetTest
               setTarget failed
               
               
               Short WR Test Failed!
               
               
               Running ~GetTargetTest
               getTarget failed
               
               Running ~IsAliveTest
               IsAliveTest passed
               
               Running ~SetTargetTest
               Caught expected InvalidOperationException
               setTarget passed
               
               
               Long WR Test Passed!
               
               
               Test Failed!
               Expected: 100
               Actual: 1
               END EXECUTION - FAILED
```

**Note:** when the issue is resolved remove the corresponding line in tests/testsFailing.arm.txt (https://github.com/dotnet/coreclr/pull/19087)

**Comment by AndyAyersMS** [comment]
I'll investigate

**Comment by AndyAyersMS** [comment]
I can't repro this so far with recent bits. It runs kind of slowly so only have ~20 iterations (also running with side-loaded stress).

And as far as I can tell we've been running this test under GC/Jit for a while now and there are no recent failures. So likely will close...

**Comment by AndyAyersMS** [comment]
Still no repro, after ~100 runs or so. Closing.
