### ISSUE TITLE
CoreCLR failed to run test in VS2017 Update 7

### ISSUE THREAD

**Issue by shanshan0309** [dotnet/coreclr#19108]
CoreCLR failed to run test on Windows with VS2017 Update7. Could you please help take a look at this? Thank you!

**You can repro this issue as the steps below:**
1. git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2. Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\CoreCLR\src
3. build x86 release -Rebuild -- /clp:ShowCommandLine
4. build-test.cmd x86 release -- /clp:ShowCommandLine
5. tests\runtest.cmd x86 release

**Error info:**
The whole log file please see attachment.
[log_x86_test.log](https://github.com/dotnet/coreclr/files/2223051/log_x86_test.log)

**Comment by shanshan0309** [comment]
This issue can be reproduced from the master revision https://github.com/dotnet/coreclr/commit/ad4df07bf2ea70334ada357d1240099e61b1d170.

**Comment by PhoebeHui** [comment]
Any updates?

**Comment by RussKeldorph** [comment]
I can repro this, but only on high-core-count machines.   Looks like the issue #20349 addressed can happen on other 32-bit platforms.  Possible fixes:
 - Figure out why xUnit or whatever is taking so ridiculously much memory and fix it
 - Broaden #20349 to apply to all 32-bit platforms
 - (If above affects performance) Limit parallelism some other way

**Comment by sandreenko** [comment]
The virtual memory consumption should be limited by #22746.
