### ISSUE TITLE
[RyuJIT] Linux has more SIMD register spills than Windows

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#19117]
The code example is from the SoA ray-tracer benchmark https://github.com/dotnet/coreclr/pull/18839, the C# source code is same as https://github.com/dotnet/coreclr/issues/19116
![image](https://user-images.githubusercontent.com/1263030/43165851-cc4b59e4-8f49-11e8-91e3-cff128816706.png)

We can see that vector variables are always spilled on stack after generated on Linux. But the Windows version can leveage the calling convention (callee-saved XMM6-XMM15) to save/restore SIMD registers just around call-sites, sometime that call avoid memory access.

**Comment by fiigii** [comment]
@CarolEidt @AndyAyersMS @tannergooding

**Comment by AndyAyersMS** [comment]
Can you double-check that the jit is producing optimized code in your examples? The object ctor should always get inlined.

The lack of callee-saved XMMs is an issue (eg #4316). There have been suggestions to inline more aggressively but a lot of math helpers bottom out in natively implemented methods.

**Comment by fiigii** [comment]
> The object ctor should always get inlined.

I will take a look at JITDump, thanks.

**Comment by AndyAyersMS** [comment]
Can you share out the whole jit dump (or at least the part at the end that shows the full inline tree)? 

Jit dumps during inlining can be confusing to parse because the inliner's behavior is somewhat pipelined.

**Comment by fiigii** [comment]
Sure, the Windows jit dump is [Win_colordump.txt](https://github.com/dotnet/coreclr/files/2225698/Win_colordump.txt) and Linux is [Linux_colordump.txt](https://github.com/dotnet/coreclr/files/2225701/Linux_colordump.txt)

**Comment by AndyAyersMS** [comment]
How odd... this is with normal jitting, right? Is this versus a current CoreCLR or something else?
```
      [0 IL=0001 TR=000672 06000183] [FAILED: not inline candidate] System.Object:.ctor():this
```

**Comment by fiigii** [comment]
> this is with normal jitting, right?

I think so... I just build the master branch of CoreCLR and copied it to the publish fold.

**Comment by AndyAyersMS** [comment]
Which dotnet version are you using?

**Comment by fiigii** [comment]
Oh, I see, I probably used the debug version of mscorlib.

**Comment by fiigii** [comment]
@AndyAyersMS I checked that `System.Object..ctor` is inlined with released build mscorlib. Sorry about the mistake.

Closing this issue.
