### ISSUE TITLE
IMetaDataImport::GetFieldProps reporting size of field name wrong

### ISSUE THREAD

**Issue by dotnetjt** [dotnet/coreclr#19118]
Working with this API, and in this method:

```
HRESULT GetFieldProps(
  [in]                                           mdFieldDef      tkFieldDef,
  [out]                                          mdTypeDef       *ptkTypeDef,
  [out, size_is(cchField), length_is(*pchField)] LPWSTR          szField,
  [in]                                           ULONG           cchField,
  [out]                                          ULONG           *pchField,
  [out]                                          DWORD           *pdwAttr,
  [out, size_is(, *pcbSigBlob)]                  PCCOR_SIGNATURE *ppvSigBlob,
  [out]                                          ULONG           *pcbSigBlob,
  [out]                                          DWORD           *pdwCPlusTypeFlag,
  [out, size_is(, *pcchValue)]                   UVCP_CONSTANT   *ppValue,
  [out]                                          ULONG           *pcchValue
);
```

The `out ULONG *pchField ` parameter is always reporting 1 byte larger than the field actually is.

For example:

```
private string MyField;
```
reports as a size of 8.

Any idea why this is?

**Comment by AaronRobinsonMSFT** [comment]
That length includes the null terminator. The code path is a bit complicated, but on Windows the computation is eventually done by [`MultiByteToWideChar()`](https://docs.microsoft.com/en-us/windows/desktop/api/stringapiset/nf-stringapiset-multibytetowidechar). Referencing this function's documentation the following line is relevant:

>If this parameter is -1, the function processes the entire input string, including the terminating null character. Therefore, the resulting Unicode string has a terminating null character, and the length returned by the function includes this character.

Observe the call here:
https://github.com/dotnet/coreclr/blob/2b92e13d9c015de34b12487131932410148ffb80/src/md/enc/metamodelrw.cpp#L5171

**Comment by dotnetjt** [comment]
@AaronRobinsonMSFT thanks for the explanation. I can work with it. 👍
