### ISSUE TITLE
Tiered Compilation: Need an ETW event that explicitly indicates tiering is enabled or disabled

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#19133]
Right now PerfView assumes that the lack of a jit compilation tier1 event means tiering was disabled but this is error prone in at least two situations:
a) Short running apps may never have time to tier any methods but the feature was enabled
b) Apps that generate large amounts of ETW events may drop events or exhaust the circular buffer causing all tier1 jit events to be lost (this is exacerbated by PerfView's misleading UI that shows you have enough buffer even when events are being dropped)

**Comment by AaronRobinsonMSFT** [comment]
@noahfalk Do we have an idea on details that might be inserted into this event? Is there metadata that should be in the payload?

**Comment by noahfalk** [comment]
Adding @kouvel

@AaronRobinsonMSFT - For the PerfView scenario I had in mind all we need is 1 bit, TRUE for tiered compilation on, FALSE for off. There might even be some other event we could add this bit to but I didn't go searching for options.

**Comment by kouvel** [comment]
Closing in favor of https://github.com/dotnet/coreclr/issues/23221 and https://github.com/dotnet/coreclr/issues/23222
