### ISSUE TITLE
Incorrect naming for JIT\HardwareIntrinsics\X86\Sse2 test projects

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19131]
The naming of the following doesn't follow the correct naming scheme:
```
MoveScalar_r.Int64.csproj
MoveScalar_r.UInt64.csproj
MoveScalar_ro.Int64.csproj
MoveScalar_ro.UInt64.csproj
```
The `_r` or `_ro` suffix needs to be the _last_ thing before the file extension. Thus, they should be:
```
MoveScalar.Int64_r.csproj
MoveScalar.UInt64_r.csproj
MoveScalar.Int64_ro.csproj
MoveScalar.UInt64_ro.csproj
```

**Comment by BruceForstall** [comment]
@fiigii @tannergooding @CarolEidt

**Comment by fiigii** [comment]
@4creators is working on fixing SSE2 tests

**Comment by 4creators** [comment]
@BruceForstall I will fix naming problems - pls assign issue to me.
