### ISSUE TITLE
Incorrect Optimization setting for tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19132]
The naming convention is that `*_ro` tests are optimized (`<Optimize>True</Optimize>`) and `*_r` tests are not (`<Optimize></Optimize>`).

The following are not built optimized and should be (and the build is the same as the `_r` versions):
```
JIT\HardwareIntrinsics\X86\Sse2\CompareGreaterThanOrEqualScalar_ro.csproj
JIT\HardwareIntrinsics\X86\Sse2\CompareGreaterThanOrEqualUnorderedScalar_ro.csproj
```

The following are built optimized and should not be (the `_ro` versions are built optimized):
```
Sse2\MaskMove_r.csproj
Sse2\MoveMask_r.csproj
Sse2\MoveScalar_r.csproj
Sse2\MoveScalar_r.Int64.csproj
Sse2\MoveScalar_r.UInt64.csproj
Avx\InsertExtractVector128_r.csproj
Avx\MoveMask_r.csproj
Avx2\MoveMask_r.csproj
```

(related: https://github.com/dotnet/coreclr/pull/19083)

**Comment by BruceForstall** [comment]
@fiigii @tannergooding @CarolEidt

**Comment by tannergooding** [comment]
@4creators, if possible. It would be good to split this out into a separate PR.

The general test cleanup/updating is a more involved PR and will likely take longer to review.
