### ISSUE TITLE
Cannot find libSystem.dylib

### ISSUE THREAD

**Issue by IlyaBiryukov** [dotnet/coreclr#19147]
Our .net core 2.1.201 app uses native interop on Mac and has methods attributed with `[DllImport("libSystem.dylib")]` some customers report that it fails to find libSystem.dylib or one of its dependencies:

**Comment by IlyaBiryukov** [comment]
The error message is "Unable to load DLL 'libSystem.dylib': The specified module or one of its dependencies could not be found. (Exception from HRESULT: 0x8007007E)"

Is there anything we can do to fix that or get more info from the customers as to what is going on?

**Comment by AaronRobinsonMSFT** [comment]
@IlyaBiryukov CoreCLR is using `dlopen()` on MacOS - see below. I believe there are environment variables for requesting tracing from `dyld`. Perhaps [here](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/LoggingDynamicLoaderEvents.html)? `DYLD_PRINT_LIBRARIES`?

https://github.com/dotnet/coreclr/blob/2194ecc60e3fae9a235e5722934660c342366d63/src/pal/src/loader/module.cpp#L1403
