### ISSUE TITLE
BuildTest fails in CI for 2.0.0

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#19167]
> 11:07:05 Locating coredistools.dll
11:07:05 File Not Found
11:07:05 CoreDisTools library path: 
11:07:05 Failed to locate the downloaded library: 
11:07:05 BUILDTEST: Commencing build of native test components for arm/Debug
11:07:05 BUILDTEST: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\\..\..\VC\Auxiliary\Build\vcvarsall.bat" x86_arm
11:07:06 **********************************************************************
11:07:06 ** Visual Studio 2017 Developer Command Prompt v15.0.26730.16
11:07:06 ** Copyright (c) 2017 Microsoft Corporation
11:07:06 **********************************************************************
11:07:06 The input line is too long.
11:07:06 :export_x86
11:07:06  was unexpected at this time.
11:07:06 

https://ci.dot.net/job/dotnet_coreclr/job/release_2.0.0/job/arm_cross_release_windows_nt_prtest/

CC @joshfree

**Comment by joshfree** [comment]
thanks for filing this @wtgodbe; hopefully this is fixable without having to do "subst" workarounds

**Comment by wtgodbe** [comment]
2.0.0 is EOL, so we should be able to close this.
