### ISSUE TITLE
[Windows/arm64] Update runtime used to run tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19178]
As part of https://github.com/dotnet/coreclr/issues/18048 (building Windows ARM using public tools), we should also update the snapshot of VC CRT used on the test machines.

netci.groovy currently copies a specific, cached copy of part of the CRT when running a Windows arm64 job:
```
if (architecture == "arm64") {
    addCommand("copy C:\\Jenkins\\vcruntime140.dll bin\\tests\\${osGroup}.${architecture}.${configuration}\\Tests\\Core_Root")
    addCommand("copy C:\\Jenkins\\vcruntime140d.dll bin\\tests\\${osGroup}.${architecture}.${configuration}\\Tests\\Core_Root")
}
```

This is needed by the `Exceptions\ForeignThread\ForeignThreadExceptions` test, at minimum (which is currently disabled due to https://github.com/dotnet/coreclr/issues/10636).

We should update this to copy the entire CRT that is up-to-date with the build tools, e.g.:
```
c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Redist\MSVC\14.14.26405\onecore\arm64\Microsoft.VC141.CRT
```

This directory contains:
```
concrt140.dll
msvcp140.dll
msvcp140_1.dll
msvcp140_2.dll
vccorlib140.dll
vcruntime140.dll
```

When I copy these to the arm64 `CORE_ROOT`, then the ForeignThreadExceptions test passes.

Instead of the `C:\\Jenkins` path, we should keep the entire tree, so we have a version number, e.g.:
```
c:\Redist\MSVC\14.14.26405\onecore\arm64\Microsoft.VC141.CRT
```

**Comment by BruceForstall** [comment]
@jashook @RussKeldorph comments?

**Comment by RussKeldorph** [comment]
Getting rid of obsolete cached copies of things seems like a good idea.  I'm not certain what the final solution should look like, though...i.e. whether this is a machine config issue or something that simply needs to be worked around forever.  I'm just not sure what unique constraints Win/ARM64 has, if any, and if they are by design.

**Comment by BruceForstall** [comment]
Looks like maybe I need to extend https://github.com/dotnet/coreclr/pull/12781 to update CORE_ROOT when generating the arm64 Windows layouts, to copy a package of now-public arm64 CRT.

**Comment by BruceForstall** [comment]
Then I can remove the manual copy in netci.groovy, which was presumably copying something private.

**Comment by BruceForstall** [comment]
Added comments to https://github.com/dotnet/coreclr/issues/12898 asking about this.

**Comment by BruceForstall** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/19336
