### ISSUE TITLE
Unable to catch in managed code any user exception thrown from native Linux code

### ISSUE THREAD

**Issue by yaireclipse** [dotnet/coreclr#19192]
Basically, I have a solution that contains one project of managed C# .NET Core and another native linux C++ project. The managed code project uses the native one. In the native code I throw various C++ exceptions (such as `runtime_error`). In the managed code, I call the native code within a `try`-`catch` block, expecting to catch the offending exception(s) in the managed code.

I've tried:

1.  `catch (Exception)`;
2.  `catch (System.Runtime.CompilerServices.RuntimeWrappedException)`;
3.  Parameterless `catch {..}`;
4.  Using `[SecurityCritical]` + `[HandleProcessCorruptedStateExceptions]`, although I thought these exceptions are probably not considered corrupted-state exception, and even if they did, in #9045 @jkotas [states that corrupted-state exceptions are not converted to managed exceptions](https://github.com/dotnet/coreclr/issues/9045#issuecomment-274615567);
5.  Setting `legacyCorruptedState­­ExceptionsPolicy` to `true` (again - although I thought I'm not dealing with corrupted-state exceptions).

All, to no avail.

I've set-up [this Minimal, Complete and Verifiable example](https://github.com/yaireclipse/CatchNativeExceptions) that demonstrates what I currently fail to achieve, and the different attempts to solve it.

Tested with .NET Core 2.0, on Ubuntu 16.04.2 LTS (via Bash on Ubuntu on Windows) and CentOS Linux release 7.5.1804 (via Docker for Windows).

This was actually [asked in the past on Stackoverflow](https://stackoverflow.com/questions/50851329/catch-native-exception-in-dotnet-core) by @levhaikin, a colleage of mine, with no answers, so we turn to you :) :

1.  Is my expectation correct? Meaning, is there a way, in .NET Core, to catch an exception thrown from native code, in managed code?
2.  If so, what am I doing wrong? How should it be done?

Thanks,
Yair

**Comment by jkotas** [comment]
We do not support exception handling interop on Unix. There is no good way to do it. The Mono project has a great write up on it here: http://www.mono-project.com/docs/advanced/pinvoke/#runtime-exception-propagation . The same reasoning applies to .NET Core.

**Comment by yaireclipse** [comment]
Wow. Good reading indeed!

In the end of the referenced section in that article, the author recommends as follows:

> C++ exceptions will need to be mapped into an “out” parameter or a return value, so that managed code can know what error occurred, and (optionally) throw a managed exception to “propagate” the original C++ exception.

@jkotas, do you recommend the same approach for .NET Core wrapping native C++ as well?

Thanks for the quick response and the reference!

**Comment by jkotas** [comment]
> do you recommend the same approach for .NET Core wrapping native C++ as well?

Yes.

**Comment by yaireclipse** [comment]
OK. Thank you for your time :) I'm closing this issue.

**Comment by yaireclipse** [comment]
@AaronRobinsonMSFT, thanks for the interesting reference. Sounds like a good direction for C programming in general. Also might enable automatic translation of exceptions in non-Windows native code to managed code, and maybe even unifying Windows and non-Windows behavior.
