### ISSUE TITLE
Dataflow cancellation crashes console app when debugger is attached

### ISSUE THREAD

**Issue by lfr** [dotnet/coreclr#19194]
Platform: Windows
Debugger: Visual Studio 2017
Version: 2.1.2

After pressing Ctrl+C, The following program will hang before the 2nd beakpoint is hit, but only when debugger is attached:

```
class Program
{
    static async Task Main(string[] args)
    {
        var cts = new CancellationTokenSource();
        Console.CancelKeyPress += (s, e) => cts.Cancel(true);

        var block1 = new TransformBlock<int, int>(async x =>
        {
            Console.WriteLine($"In: {x}");
            await Task.Delay(3000);
            return x;
        }, new ExecutionDataflowBlockOptions()
        {
            CancellationToken = cts.Token
        });
        var block2 = new ActionBlock<int>(x =>
        {
            Console.WriteLine($"Processed: {x}");
        });

        block1.LinkTo(block2, new DataflowLinkOptions() { PropagateCompletion = true });

        foreach (var i in Enumerable.Range(0, 100))
            await block1.SendAsync(i);

        block1.Complete();

        // wait for cancellation to be triggered
        await Task.WhenAny(Task.Delay(Timeout.Infinite, cts.Token));

        await block1.Completion; // breakpoint 1
        await block2.Completion; // breakpoint 2

        Console.ReadKey();
    }
}
```

**Comment by AaronRobinsonMSFT** [comment]
@lferrao You might want to submit a [VS Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) issue instead. The VS Debugger team works closely with the CoreCLR Diagnostics team so this will get here if it is indeed a CoreCLR issue.

**Comment by lferrao** [comment]
@gregg-miskelly @AaronRobinsonMSFT Any news on this front? The ticket I created there has been forgotten.

**Comment by tommcdon** [comment]
Closing this ticket since it is being tracked on the following developer community feedback ticket:

https://developercommunity.visualstudio.com/content/problem/302780/dataflow-cancellation-crashes-dotnet-console-app-w.html
