### ISSUE TITLE
WIndows does not decode EventSource events if they use enums that not based on int or long.

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#19204]
@brianrob 

See the VS bug https://microsoft.visualstudio.com/OS/_workitems/edit/18408493 which is where this issue arose.  I have copied the important part in the next comment in case the link break.

**Comment by vancem** [comment]
The fixes are in [Sytem.Diagnostics.Tracing.ManifestBuidler.CreateManifestString](https://github.com/dotnet/coreclr/blob/f26b8eea691d51332b2bd46ff32643f235c8ab14/src/System.Private.CoreLib/shared/System/Diagnostics/Tracing/EventSource.cs#L5460).   Basicaly we can handle other kinds of primitive types.

I think just using the Convert.ToInt64(obj) will fix that.

However because the whole manifest will be rejected if you emit empty maps, we need to emit nothing in that case.

This is very straightforward.

**Comment by tommcdon** [comment]
@vancem is this issue resolved or is there other outstanding work we need to do for this?

**Comment by vancem** [comment]
This issue has been fixed by the PR referenced above.
