### ISSUE TITLE
Tests failure GC\Features\Finalizer\finalizeother\finalizearray GC\Features\Finalizer\finalizeother\finalizearraysleep

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#19218]
**COMPlus_JitStress=1**

**GC\Features\Finalizer\finalizeother\finalizearray\finalizearray.cmd** fails since [Windows_NT arm Cross Checked r2r_jitstress1 Build and Test #15 (Jul 21, 2018 1:11:13 AM)](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_r2r_jitstress1_tst/15/)

**GC\Features\Finalizer\finalizeother\finalizearraysleep\finalizearraysleep.cmd**
**GC\Features\Finalizer\finalizeother\finalizearray\finalizearray.cmd**  fail since [Windows_NT arm Cross Checked jitstress1 Build and Test #35 (Jul 23, 2018 6:49:51 AM) ](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_jitstress1_tst/35)

**GC/Features/Finalizer/finalizeother/finalizearray/finalizearray.sh** fails since [Ubuntu arm Cross Checked r2r_jitstress1 Build and Test #20 (Jul 23, 2018 7:23:30 AM)](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_r2r_jitstress1_tst/20/)
```
FAILED   - GC/Features/Finalizer/finalizeother/finalizearray/finalizearray.sh
               BEGIN EXECUTION
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress1_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress1_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress1_tst_prtest/bin/tests/Linux.arm.Checked/GC/Features/Finalizer/finalizeother/finalizearray/IL:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress1_tst_prtest/bin/tests/Linux.arm.Checked/GC/Features/Finalizer/finalizeother/finalizearray /in finalizearray.org /out finalizearray.exe
               Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
               Copyright (c) Microsoft Corporation.  All rights reserved.
               
               Native image finalizearray.exe generated successfully.
               in ReleaseLock
               in takeLock
               /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_r2r_jitstress1_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun finalizearray.exe
               Test for Finalize() for array of objects failed!
               in ReleaseLock
               Expected: 100
               Actual: 1
               END EXECUTION - FAILED
```

**COMPlus_JitStress=2**
**GC\Features\Finalizer\finalizeother\finalizearraysleep\finalizearraysleep.cmd**
**GC\Features\Finalizer\finalizeother\finalizearray\finalizearray.cmd** fail since [Windows_NT arm Cross Checked r2r_jitstress2 Build and Test #14 (Jul 22, 2018 12:47:38 PM)](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_r2r_jitstress2_tst/14/)

/cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
For finalizearray, JitStress=1 enables the random inliner, and it looks like this enables inlining `CreateObj.ctor` into `Main`. That makes it possible for the temp holding the new array allocation to live past the nulling of `obj` and potentially keeps the array live.
```
Inlines into 06000001 Test:Main():int
  [1 IL=0000 TR=000007 06000006] [profitable inline] CreateObj:.ctor():this
    [2 IL=0001 TR=000051 0600049C] [below ALWAYS_INLINE size] System.Object:.ctor():this
    [3 IL=0033 TR=000082 06000004] [below ALWAYS_INLINE size] Dummy:.ctor():this
      [4 IL=0001 TR=000109 0600049C] [below ALWAYS_INLINE size] System.Object:.ctor():this
  [0 IL=0007 TR=000014 06000007] [FAILED: noinline per IL/cached result] CreateObj:RunTest():this
  [5 IL=0012 TR=000016 060003AD] [below ALWAYS_INLINE size] System.GC:Collect()
    [0 IL=0002 TR=000117 060003A3] [FAILED: cannot get method info] System.GC:_Collect(int,int)
  [6 IL=0017 TR=000018 060003B6] [below ALWAYS_INLINE size] System.GC:WaitForPendingFinalizers()
    [0 IL=0000 TR=000123 060003B5] [FAILED: cannot get method info] System.GC:_WaitForPendingFinalizers()
  [7 IL=0022 TR=000020 060003AD] [below ALWAYS_INLINE size] System.GC:Collect()
    [0 IL=0002 TR=000129 060003A3] [FAILED: noinline per IL/cached result] System.GC:_Collect(int,int)
  [0 IL=0044 TR=000044 06000081] [FAILED: noinline per IL/cached result] System.Console:WriteLine(ref)
  [0 IL=0057 TR=000036 06000081] [FAILED: noinline per IL/cached result] System.Console:WriteLine(ref)
```
Would suggest we mark `CreateObj` as noinline here.

Similar issue for finalizearraysleep.
