### ISSUE TITLE
[Arm64/Linux] gcStress=4/8/C intermittent failures

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#19211]
The following test failed twice over the last few months.

On 7/30/2018 the failure looked like 
`GC/API/GC/GetGenerationWR/GetGenerationWR.sh`
`gcStress=0xC`
```
corerun GetGenerationWR.exe

Assert failure(PID 17500 [0x0000445c], Thread: 17500 [0x445c]): 
    !CREATE_CHECK_STRING(pMT &amp;&amp; pMT-&gt;Validate())
    File: src/vm/object.cpp Line: 733
```

Early 6/2018 the failure was similar

`gcStress=0x4`
```
corerun GetGenerationWR.exe

Assert failure(PID 14440 [0x00003868], Thread: 14440 [0x3868]): 
!CREATE_CHECK_STRING(pMT && pMT->Validate())
    File: src/vm/object.cpp Line: 733
```

It may be worth noting the `GetGenerationWR2` is marked gcStressIncompatible

**Comment by sdmaclea** [comment]
@RussKeldorph moved from #18286

**Comment by sdmaclea** [comment]
Failed again on 8/4/2018 in `gcStress=0xC` `corerun GetGenerationWR.exe`.  Result was a segmentation fault.

**Comment by AndyAyersMS** [comment]
I'll investigate.

**Comment by AndyAyersMS** [comment]
Haven't been able to repro this.

We don't seem to run these tests under CI GC stress anymore so have no recent CI history to refer to.

@BruceForstall do you know where these are excluded?

**Comment by sdmaclea** [comment]
@AndyAyersMS These represented the intermittent failures I saw while running gcStress in my nightly runs over a period of month from 3/2018 to 8/2018.  I ran each GC multiple times a night, and report each instance of a failure.  These failures were rare.  

I think I may have marked them as gcStressIncompatible to prevent them running in CI.  If we are OK with them being gsStressIncompatible, we could possibly close this...

**Comment by BruceForstall** [comment]
@AndyAyersMS Are you sure they are not run? Looks to me like they should be run, e.g., https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_gcstress0xc_flow/. The only problem is we don't currently save enough log information to see exactly which tests are actually run, so it's hard to know. This particular test is not marked GCStressIncompatible.

**Comment by BruceForstall** [comment]
I added storing/uploading of individual test reports, but only to Windows. You can see the Windows/arm64 GCStress0xC logs here: https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_gcstress0xc_tst/55/.

(Or, specifically, this zip file: https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_gcstress0xc_tst/55/artifact/bin/tests/testReports.zip)

E.g.,
```
BEGIN EXECUTION

C:\j\workspace\arm64_cross_c---86d54ed4\bin\tests\Windows_NT.arm64.Checked\GC\API\GC\GetGenerationWR>set COMPLUS_NOGUIONASSERT=1 

C:\j\workspace\arm64_cross_c---86d54ed4\bin\tests\Windows_NT.arm64.Checked\GC\API\GC\GetGenerationWR>set COMPLUS_CONTINUEONASSERT=0 

C:\j\workspace\arm64_cross_c---86d54ed4\bin\tests\Windows_NT.arm64.Checked\GC\API\GC\GetGenerationWR>set COMPLUS_GCSTRESS=0xC 

C:\j\workspace\arm64_cross_c---86d54ed4\bin\tests\Windows_NT.arm64.Checked\GC\API\GC\GetGenerationWR>set COMPLUS_TIEREDCOMPILATION=0 
 "C:\j\workspace\arm64_cross_c---86d54ed4\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root\corerun.exe" GetGenerationWR.exe 
In Finalize() of Dummy
Expected exception
Test passed!
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED
Test Harness Exitcode is : 0
```

**Comment by AndyAyersMS** [comment]
Thanks. Still odd that CI on Linux seems to give two different views on what is being run. I find the summary view useful as one can eventually get to the per-test history for that CI leg.

At any rate from what I can tell this test is running on arm64 linux with GC stress and passing. And it passes for me locally. So, I'm going to close this.

**Comment by AndyAyersMS** [comment]
Of course right after I close this as no repro, it repros...

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_gcstress0xc_flow_prtest/21/

```
/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_gcstress0xc_tst_prtest/bin/tests/Linux.arm64.Checked/GC/API/GC/GetGenerationWR/GetGenerationWR.sh: line 244: 14681 Segmentation fault      (core dumped)
```

**Comment by AndyAyersMS** [comment]
I've had some luck using `jit-diff` to induce a stress load on the machine (similar perhaps to running the full test suite, but less painful to set up). It is not completely fleshed out yet but here's the gist of it.

For the program that you want to try and make crash, set up an LLDB batch script (here debug-before.txt):
```
target create ./corerun
settings set -- target.run-args  "../../GC/API/GC/GetGenerationWR/GetGenerationWR.exe"
settings set -- interpreter.prompt-on-quit TRUE
process launch -s
process handle -n FALSE -p TRUE -s FALSE SIGILL SIGRTMIN
continue
```
then use this to repeatedly launch the program under LLDB...
```
let a=0; while true; do echo $a; lldb-6.0 -b -S debug-before.txt; let a++; done
```
While this is churning away, open up another shell and launch jit-diffs.

This additional stress on the machine seems to provoke failures in the above test once every 20 runs or so, whereas without it it fails much less often. I still need to figure out how to get LLDB to stop if the program fails.

Sample output:
```
25
(lldb) command source -s 0 'debug-before.txt'
Executing commands in '/home/andya/repos/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root/debug-before.txt'.
(lldb) target create ./corerun
Current executable set to './corerun' (aarch64).
(lldb) settings set -- target.run-args  "../../GC/API/GC/GetGenerationWR/GetGenerationWR.exe"
(lldb) settings set -- interpreter.prompt-on-quit TRUE
(lldb) process launch -s
Process 25563 launched: './corerun' (aarch64)
(lldb) process handle -n FALSE -p TRUE -s FALSE SIGILL SIGRTMIN
NAME         PASS   STOP   NOTIFY
===========  =====  =====  ======
SIGILL       true   false  false
SIGRTMIN     true   false  false
(lldb) continue
In Finalize() of Dummy
Expected exception
Test passed!
Process 25563 resuming
Process 25563 exited with status = 100 (0x00000064)

26
(lldb) command source -s 0 'debug-before.txt'
Executing commands in '/home/andya/repos/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root/debug-before.txt'.
(lldb) target create ./corerun
Current executable set to './corerun' (aarch64).
(lldb) settings set -- target.run-args  "../../GC/API/GC/GetGenerationWR/GetGenerationWR.exe"
(lldb) settings set -- interpreter.prompt-on-quit TRUE
(lldb) process launch -s
Process 27237 launched: './corerun' (aarch64)
(lldb) process handle -n FALSE -p TRUE -s FALSE SIGILL SIGRTMIN
NAME         PASS   STOP   NOTIFY
===========  =====  =====  ======
SIGILL       true   false  false
SIGRTMIN     true   false  false
(lldb) continue
Process 27237 resuming
Process 27237 stopped
* thread #1, name = 'corerun', stop reason = signal SIGSEGV: invalid address (fault address: 0x7400610063006c)
    frame #0: 0x0000ffffb729fd98 libcoreclr.so`MethodTable::SanityCheck() [inlined] MethodTable::RawGetComponentSize(this=<unavailable>) at methodtable.h:1763

27
(lldb) command source -s 0 'debug-before.txt'
Executing commands in '/home/andya/repos/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root/debug-before.txt'.
(lldb) target create ./corerun
Current executable set to './corerun' (aarch64).
(lldb) settings set -- target.run-args  "../../GC/API/GC/GetGenerationWR/GetGenerationWR.exe"
(lldb) settings set -- interpreter.prompt-on-quit TRUE
(lldb) process launch -s
Process 28393 launched: './corerun' (aarch64)
(lldb) process handle -n FALSE -p TRUE -s FALSE SIGILL SIGRTMIN
NAME         PASS   STOP   NOTIFY
===========  =====  =====  ======
SIGILL       true   false  false
SIGRTMIN     true   false  false
(lldb) continue
In Finalize() of Dummy
Expected exception
Test passed!
Process 28393 resuming
Process 28393 exited with status = 100 (0x00000064)
```

**Comment by AndyAyersMS** [comment]
Above technique has turned up a number of different looking failure modes. But I can't yet figure out how to script LLDB to break in on a failure -- it just keeps going. So not much insight yet from debugging.

A sampling of failures:
```
;; at a GC triggered by GC collect call

Assert failure(PID 16980 [0x00004254], Thread: 16980 [0x4254]): !CREATE_CHECK_STRING(pMT && pMT->Validate())
    File: /coreclr/src/vm/object.cpp Line: 695
    Image: /home/andya/repos/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun

0000FFFFFFFFC658 0000000000000000 [ResumableFrame: 0000ffffffffc658] 
0000FFFFFFFFE530 0000ffff3ed277e4 [InlinedCallFrame: 0000ffffffffe530] System.GC._Collect(Int32, Int32)
0000FFFFFFFFE510 0000FFFF3ED277E4 CreateObj.RunTest() [/coreclr/tests/src/GC/API/GC/GetGenerationWR.cs @ 31]
0000FFFFFFFFE5D0 0000FFFF3ED27658 CreateObj.Main() [/coreclr/tests/src/GC/API/GC/GetGenerationWR.cs @ 56]
0000FFFFFFFFE998 0000ffffb7477bb4 [GCFrame: 0000ffffffffe998] 
0000FFFFFFFFEE68 0000ffffb7477bb4 [GCFrame: 0000ffffffffee68] 
```
```
;; similar stack trace as above, different failure symptom

Process 11887 stopped
* thread #1, name = 'corerun', stop reason = signal SIGSEGV: invalid address (fault address: 0x74006500670070)
    frame #0: 0x0000ffffb729fd98 libcoreclr.so`MethodTable::SanityCheck() [inlined] MethodTable::RawGetComponentSize(this=<unavailable>) at methodtable.h:1763
```
``` 
;; failed in dl_open somehow when trying to load the jit

* thread #1, name = 'corerun', stop reason = signal SIGBUS: illegal address
    frame #0: 0x0000ffffb7fdc788 ld-linux-aarch64.so.1`___lldb_unnamed_symbol4$$ld-linux-aarch64.so.1 + 2040
    frame #1: 0x0000ffffb7fe4148 ld-linux-aarch64.so.1
    frame #2: 0x0000ffffb7fdf9f8 ld-linux-aarch64.so.1`___lldb_unnamed_symbol7$$ld-linux-aarch64.so.1 + 1064
    frame #3: 0x0000ffffb7fe3970 ld-linux-aarch64.so.1
    frame #4: 0x0000ffffb7fbff58 libdl.so.2`dlopen_doit(a=0x000000770000007c) at dlopen.c:66
    frame #5: 0x0000ffffb7fdf9f8 ld-linux-aarch64.so.1`___lldb_unnamed_symbol7$$ld-linux-aarch64.so.1 + 1064
    frame #6: 0x0000ffffb7fc0610 libdl.so.2`_dlerror_run(operate=(libdl.so.2`dlopen_doit at dlopen.c:58), args=0x0000000000000000) at dlerror.c:163
    frame #7: 0x0000ffffb7fc0008 libdl.so.2`__dlopen(file=<unavailable>, mode=<unavailable>) at dlopen.c:87
    frame #8: 0x0000ffffb774ee7c libcoreclr.so`LOADLoadLibraryDirect(libraryNameOrPath=0x000000000050d280) at module.cpp:1485
    frame #9: 0x0000ffffb774d0d8 libcoreclr.so`::LoadLibraryExW(LPCWSTR, HANDLE, DWORD) [inlined] LOADLoadLibrary(shortAsciiName=0x000000000050d280, fDynamic=NO) at module.cpp:1722
    frame #10: 0x0000ffffb774d0c0 libcoreclr.so`::LoadLibraryExW(lpLibFileName=<unavailable>, hFile=<unavailable>, dwFlags=<unavailable>) at module.cpp:251
    frame #11: 0x0000ffffb71fc6b4 libcoreclr.so`LoadLibraryExWrapper(lpLibFileName=<unavailable>, hFile=0x0000000000000000, dwFlags=0) at longfilepathwrappers.cpp:64
    frame #12: 0x0000ffffb73083e0 libcoreclr.so`CLRLoadLibrary(char16_t const*) [inlined] CLRLoadLibraryWorker(lpLibFileName=u"/home/andya/repos/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root/libclrjit.so") at util.cpp:2231
    frame #13: 0x0000ffffb73083bc libcoreclr.so`CLRLoadLibrary(lpLibFileName=u"/home/andya/repos/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root/libclrjit.so") at util.cpp:2248

```

**Comment by AndyAyersMS** [comment]
Can also hit asserts when GC is triggered by the finalizer thread:
```
Assert failure(PID 43493 [0x0000a9e5], Thread: 43940 [0xaba4]): !CREATE_CHECK_STRING(pMT && pMT->Validate())
    File: /coreclr/src/vm/object.cpp Line: 695
    Image: /home/andya/repos/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun

OS Thread Id: 0xaba4 (7)
        Child SP               IP Call Site
0000FFFFB4599508 0000000000000000 [ResumableFrame: 0000ffffb4599508] 
0000FFFFB459B3C0 0000FFFF3ED2849C System.Console.get_Out() [/__w/1/s/src/System.Console/src/System/Console.cs @ 112]
0000FFFFB459B3D0 0000FFFF3ED2804C System.Console.WriteLine(System.String) [/__w/1/s/src/System.Console/src/System/Console.cs @ 540]
0000FFFFB459B3F0 0000FFFF3ED27994 Dummy.Finalize() [/coreclr/tests/src/GC/API/GC/GetGenerationWR.cs @ 12]
0000FFFFB459B750 0000ffffb7477bb4 [DebuggerU2MCatchHandlerFrame: 0000ffffb459b750] 

* thread #7, name = 'corerun', stop reason = signal SIGTRAP
  * frame #0: 0x0000ffffb77bcf7c libcoreclr.so`DBG_DebugBreak
    frame #1: 0x0000ffffb77325cc libcoreclr.so`::DebugBreak() at debug.cpp:405
    frame #2: 0x0000ffffb71fc25c libcoreclr.so`::DbgAssertDialog(szFile=<unavailable>, iLine=<unavailable>, szExpr=<unavailable>) at debug.cpp:723
    frame #3: 0x0000ffffb72a7820 libcoreclr.so`Object::ValidateInner(this=0x0000ffff18080d88, bDeep=YES, bVerifyNextHeader=YES, bVerifySyncBlock=YES) at object.cpp:695
    frame #4: 0x0000ffffb74760f0 libcoreclr.so`GcInfoDecoder::ReportRegisterToGC(this=0x0000ffffb4597ca8, regNum=19, gcFlags=0, pRD=<unavailable>, flags=1, pCallBack=<unavailable>, hCallBack=0x0000ffffb4598ff8)(void*, OBJECTREF*, unsigned int), void*) at gcinfodecoder.cpp:1681
    frame #5: 0x0000ffffb74739d4 libcoreclr.so`GcInfoDecoder::EnumerateLiveSlots(this=<unavailable>, pRD=<unavailable>, reportScratchSlots=<unavailable>, inputFlags=<unavailable>, pCallBack=<unavailable>, hCallBack=<unavailable>)(void*, OBJECTREF*, unsigned int), void*) at gcinfodecoder.cpp:947
```

**Comment by AndyAyersMS** [comment]
I can still repro crashes even with #22415 and x19 is still implicated -- the one I'm looking at has a stress-induced GC on the finalizer thread, managed stack shows `Console.WriteLine` calling back into native code.

Can't get lldb to do symbol resolution for some reason so the information below is a bit rough:
```
#0  0x0000ffffb0511528 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x0000ffffb05129e0 in __GI_abort () at abort.c:89
#2  0x0000ffffb00a1cfc in PROCAbort () at /coreclr/src/pal/src/thread/process.cpp:3313
#3  0x0000ffffb00a1be4 in RaiseFailFastException (pExceptionRecord=<optimized out>, pContextRecord=<optimized out>, dwFlags=<optimized out>) at /coreclr/src/pal/src/thread/process.cpp:1398
#4  0x0000ffffafaecaf4 in TerminateOnAssert () at /coreclr/src/utilcode/debug.cpp:183
#5  _DbgBreakCheck (szFile=<optimized out>, iLine=<optimized out>, szExpr=<optimized out>, fConstrained=<optimized out>) at /coreclr/src/utilcode/debug.cpp:440
#6  0x0000ffffafaed000 in _DbgBreakCheckNoThrow (szFile=0xffffb013e03c "/coreclr/src/vm/object.cpp", iLine=695, szExpr=0xffffb013e14b "!CREATE_CHECK_STRING(pMT && pMT->Validate())",
    fConstrained=0) at /coreclr/src/utilcode/debug.cpp:547
#7  0x0000ffffafaed3c8 in DbgAssertDialog (szFile=<optimized out>, iLine=<optimized out>, szExpr=0x6 <error: Cannot access memory at address 0x6>) at /coreclr/src/utilcode/debug.cpp:692
#8  0x0000ffffafb98918 in Object::ValidateInner (this=0xffff180aafd8, bDeep=1, bVerifyNextHeader=1, bVerifySyncBlock=1) at /coreclr/src/vm/object.cpp:695
#9  0x0000ffffafd67134 in GcInfoDecoder::ReportRegisterToGC (this=0xfffface88ca8, regNum=19, gcFlags=0, pRD=<optimized out>, flags=1, pCallBack=<optimized out>, hCallBack=0xfffface89ff8)
    at /coreclr/src/vm/gcinfodecoder.cpp:1681
...
#26 0x0000ffffafc694e4 in OnGcCoverageInterrupt (regs=0x0) at /coreclr/src/vm/gccover.cpp:1337
#27 0x0000ffffafb268fc in IsGcMarker (pContext=0xffff0800e570, pExceptionRecord=0x8fde) at /coreclr/src/vm/excep.cpp:6682
#28 0x0000ffffafd57914 in HandleHardwareException (ex=0xfffface8ac18) at /coreclr/src/vm/exceptionhandling.cpp:5186
#29 0x0000ffffb0025288 in SEHProcessException (exception=<optimized out>) at /coreclr/src/pal/src/exception/seh.cpp:286
#30 0x0000ffffb00274d0 in common_signal_handler (code=<optimized out>, siginfo=<optimized out>, sigcontext=<optimized out>, numParams=<optimized out>)
    at /coreclr/src/pal/src/exception/signal.cpp:813
#31 0x0000ffffb002646c in sigill_handler (code=4, siginfo=0xfffface8b160, context=0xfffface8b1e0) at /coreclr/src/pal/src/exception/signal.cpp:315
#32 <signal handler called>
#33 0x0000ffff375f8fcc in ?? ()
#34 0x0000ffff375f84ac in ?? ()
#35 0x0000ffffafc1ebec in CallDescrWorkerWithHandler (pCallDescrData=0xffff180a96c8, fCriticalCall=<optimized out>) at /coreclr/src/vm/callhelpers.cpp:70
#36 0x0000ffffafc1eed8 in DispatchCallSimple (pSrc=0xfffface8c518, numStackSlotsToCopy=0, pTargetAddress=281471610747112, dwDispatchCallSimpleFlags=0) at /coreclr/src/vm/callhelpers.cpp:226
#37 0x0000ffffafb89ffc in MethodTable::CallFinalizer (obj=<optimized out>) at /coreclr/src/vm/methodtable.cpp:3951
#38 0x0000ffffafc66184 in FinalizerThread::DoOneFinalization (fobj=0xffff180ade78, pThread=0x2c89c6a0, bitToCheck=0, pbTerminate=0xfffface8c654) at /coreclr/src/vm/finalizerthread.cpp:175
#39 0x0000ffffafc65f78 in FinalizerThread::FinalizeAllObjects (fobj=0xffff180ade78, bitToCheck=<optimized out>) at /coreclr/src/vm/finalizerthread.cpp:255
#40 0x0000ffffafc66914 in FinalizerThread::FinalizerThreadWorker (args=<optimized out>) at /coreclr/src/vm/finalizerthread.cpp:600

 sos ClrStack
OS Thread Id: 0x8fde (1)
        Child SP               IP Call Site
0000FFFFACE8A508 0000000000000000 [ResumableFrame: 0000fffface8a508]
0000FFFFACE8C3C0 0000FFFF375F8FCC /home/andya/repos/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root/System.Console.dll!Unknown
0000FFFFACE8C3D0 0000FFFF375F8B64 /home/andya/repos/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root/System.Console.dll!Unknown
0000FFFFACE8C3F0 0000FFFF375F84AC /home/andya/repos/coreclr/bin/tests/Linux.arm64.Checked/GC/API/GC/GetGenerationWR/GetGenerationWR.exe!Unknown
0000FFFFACE8C750 0000ffffafd68bf4 [DebuggerU2MCatchHandlerFrame: 0000fffface8c750]
```

**Comment by BruceForstall** [comment]
Does it repro with a debug runtime and/or JIT? Maybe you'd get better argument data then.

Can you figure out which frame the GC is reporting? Presumably that could be found in one of the frames 10 through 25 you elided.

**Comment by AndyAyersMS** [comment]
Also realized using `jit-diff` to induce stress is causing artificial crashes. Apparently `dlopen` doesn't do anything special to protect the file it maps in, so if you overwrite the file bad things can happen. And `jit-diff` will stage in test version of `libclrjit.so`. So have gone back to just using `stress` to add load to the machine to make the above repro more often.

**Comment by AndyAyersMS** [comment]
```
(gdb) print ((CrawlFrame*)0xfffface88ee0)->codeInfo
$2 = {m_codeAddress = 281471610749680, m_methodToken = {m_pRangeSection = 0x2c8a2d60, m_pCodeHeader = 281471610749536}, m_pMD = 0xffff377459f0, m_pJM = 0x2c862080, m_relOffset = 136,
  m_pFunctionEntry = 0xffff377e1e4c}
(gdb) print *(MethodDesc*) 0xffff377459f0
$3 = {m_pszDebugMethodName = 0xffff37765118 "RunTest", m_pszDebugClassName = 0xffff37745920 "CreateObj", m_pszDebugMethodSignature = 0xffff377651a0 "instance bool *()",
  m_pDebugMethodTable = {static isRelative = false, m_addr = 281471612115608}, m_GcCover = 0xffff377d6d98, m_wFlags3AndTokenRemainder = 4, m_chunkIndex = 6 '\006', m_bFlags2 = 1 '\001',
  m_wSlotNumber = 5, m_wFlags = 8200, static s_ClassificationSizeTable = 0xffffb01e32e0 <MethodDesc::s_ClassificationSizeTable>, static m_GCCoverCrst = {<CrstBase> = {{m_criticalsection = {
          DebugInfo = 0x2c8a0280, LockCount = 0, RecursionCount = 0, OwningThread = 0x0, LockSemaphore = 0x0, SpinCount = 0, bInternal = 0, dwInitState = 1, csnds = {
            rgNativeDataStorage = '\000' <repeats 115 times>, pvAlign = 0x0}}}, m_dwFlags = 3221225472, m_entercount = 0, m_crstType = CrstGCCover, m_tag = 0xffffb013064e "CrstGCCover",
      m_crstlevel = 11, m_holderthreadid = {m_FiberPtrId = 0x0}, m_next = 0x0, m_prev = 0x0, m_cannotLeave = {m_val = 0}, m_countNoTriggerGC = 0}, <No data fields>}}
```
So we're evidently looking at the frame for `CreateObj.RunTest` at offset 136 (0x88) and x19 is live there:
```
00000028 interruptible
00000028 +X19
0000004c +Fp+58
0000007c +X3(interior)
00000098 -X19 -X3(interior)
```
Hmm, looks like we are still generating an inline pinvoke. Let me debug the jit and see why the change in #22415 is not blocking this.

**Comment by AndyAyersMS** [comment]
More specifically, we're at offset 0x88 in `RunTest`
```asm
        F9001BA2          str     x2, [fp,#48]  // [V08 PInvokeFrame+0x18]
        10000182          adr     x2, [G_M62964_IG04]
        F90027A2          str     x2, [fp,#72]  // [V08 PInvokeFrame+0x30]
        F94033A2          ldr     x2, [fp,#96]  // [V07 FramesRoot]
        910083A3          add     x3, fp, #32   // [V08 PInvokeFrame+0x08]
        F9000843          str     x3, [x2,#16]
        F94033A2          ldr     x2, [fp,#96]  // [V07 FramesRoot]
        3900305F          strb    wzr, [x2,#12]           // enable preemptive GC
**      D28B2402          movz    x2, #0x5920             // gc stress interrupts here
        F2A0CC42          movk    x2, #0x662 LSL #16
        F2DFFFE2          movk    x2, #0xffff LSL #32
        F9400042          ldr     x2, [x2]

G_M62964_IG03:
        D63F0040          blr     x2            // pinvoke call

G_M62964_IG04:
        F94033A0          ldr     x0, [fp,#96]  // [V07 FramesRoot]
        52800021          mov     w1, #1
        39003001          strb    w1, [x0,#12]     // disable preemptive GC
```
This code is running on thread 5 and has just flipped the thread to preemptive mode and has also linked in the inline frame, but hasn't gotten to the call. It has triggered a stress GC.  Thread 1 has also triggered a gc stress GC and won the race.
```
       ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
   5    1 8fd8 000000002C878740    20020 Preemptive  0000000000000000:0000000000000000 000000002C85C6B0 0     Ukn
   1    2 8fde 000000002C89C6A0    21220 Cooperative 0000000000000000:0000000000000000 000000002C85C6B0 0     Ukn (Finalizer) (GC)
   6    3 8fdf 0000FFFF0C000980  1020220 Preemptive  0000000000000000:0000000000000000 000000002C85C6B0 0     Ukn (Threadpool Worker)
```
Not sure how this connects back to x19 (the bad objref) just yet.

**Comment by AndyAyersMS** [comment]
I have a guess, though not confirmed yet.

On ARM64 there are quite a few instructions in the inline pinvoke where the thread is in preemptive mode:
```
        3900305F          strb    wzr, [x2,#12]       // enable preemptive GC
        D28B2402          movz    x2, #0x5920 
        F2A0CC42          movk    x2, #0x662 LSL #16
        F2DFFFE2          movk    x2, #0xffff LSL #32
        F9400042          ldr     x2, [x2]
        D63F0040          blr     x2                  // pinvoke call
        F94033A0          ldr     x0, [fp,#96]
        52800021          mov     w1, #1
        39003001          strb    w1, [x0,#12]        // disable preemptive GC
```
When we instrument for GC stress we replace all those instructions with illegal opcodes. This triggers a SIGILL which the runtime handles and (eventually) materializes the saved register context as a managed frame.

Suppose Thread 1 is executing the above and has enabled preemptive GC and then gets a SIGILL on one of the subsequent instructions. The register context, including the current x19, is saved by the signal handler. Before Thread 1 can make much progress beyond that point, it gets swapped out (which is more likely if the machine is heavily loaded).

Thread 2 comes along and triggers a GC and since Thread 1 is in preemptive mode, Thread 2 doesn't need to suspend Thread 1 to initiate a GC. So Thread 2 starts a GC and this GC relocates the object referred to by x19. But since Thread 1 hasn't yet gotten to the point where it can push the saved context as a managed frame, the saved copy of x19 is not updated by this GC.

Thread 1 gets swapped back in and runs far enough to push its saved register context as a managed frame... recall it is heading towards initiating a GC....

At this point one of two things happens.

If Thread 1 gets blocked before it can initiate the next GC, the thread that triggers GC will find a stale object reference in x19 in Thread1's frame.

If Thread1 continues and triggers a GC it will find a bad reference in x19 in its own frame.

The key is that Thread1 must be paused in the vulnerable window that opens once it has gone into preemptive mode, hit a hardware interrupt and saved off context, and closes once it has saved the context as a managed frame. And some other thread must trigger a GC when Thread 1 is paused in this window and must get far enough relocate x19 before Thread 1 resumes and pushes its frame.

On x64 the window is smaller as the call to the pinvoked method is the likely bracketed on either side by the instructions that flip the GC mode. So while it seems we could still hit this kind of race it is perhaps somewhat less likely.

If the above is correct, this is a stress mode only issue -- without GC Stress, Thread 1 would not normally cause a HW exception in that stretch of code, so it would not create the vulnerable context.

**Comment by AndyAyersMS** [comment]
Fairly sure this is the problem, but not 100% sure. And can't think of a good solution to this offhand.

@BruceForstall @janvorli any thoughts?

**Comment by janvorli** [comment]
Found something in https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md, in the Per-call-site PInvoke work section:

> The Frame is made active by setting InlinedCallFrame->m_pCallerReturnAddress.
The code then toggles the GC mode by setting Thread->m_fPreemptiveGCDisabled = 0.
**Starting now, no GC pointers may be live in registers**. RyuJit LSRA meets this requirement by adding special refPositon RefTypeKillGCRefs before unmanaged calls and special helpers.
Then comes the actual call/PInvoke.

**Comment by AndyAyersMS** [comment]
Thanks, I should have remembered that. The gc info shows x19 is killed at the call, but we're breaking in for GC at 0x88, a bit before the call.
```
00000028 interruptible
00000028 +X19
0000004c +Fp+58
0000007c +X3(interior)
00000098 -X19 -X3(interior)    [ call ]
```

So I think the bug is that the jit is not killing x19 early enough. It needs to happen when the frame is switched to preemptive, not right at the call.

On x64 these two instructions probably almost always end up being adjacent and so I guess we get away with killing GC refs at the call.

**Comment by AndyAyersMS** [comment]
Looking at how LSRA models this I wonder if we should just introduce a new pseudo-op into the IR stream, something like GT_PINVOKE_KILL_CALLEE_SAVE_GC_REFS. Or abstract over the instruction that does the actual work, eg GT_ENABLE_PREEMPTIVE_GC...

Alternatively we could update `Compiler::killGCRefs` to match the specific GT_STOREIND that we produce to enable preemptive GC, but we only consult this when the operation already has a kill set.

**Comment by BruceForstall** [comment]
+ @CarolEidt for the LSRA modeling questions/ideas.

**Comment by CarolEidt** [comment]
I think any of Andy's suggestions would work. Personally, I find the idea of an abstract instruction, `GT_ENABLE_PREEMPTIVE_GC` more appealing, but it is perhaps more work.

**Comment by AndyAyersMS** [comment]
Made an attempt at fixing this by just marking the STOREIND in the pinvoke call prolog as special. I'm probably going about it the wrong way -- seems to require a fair bit of plumbing to propagate information around as needed:
* lower marks the STOREIND in the call prolog as one that enables preeemptive gc
* `killGcRefs` helper updated to spot this as well as calls
* LSRA generalized to call `killGcRefs` more broadly instead of just checking at calls. Also requires some small updates in flow as all the above is bypassed if the instruction has no inherent kills. And needs per-arch handling.
* codegen (per arch) looks for these special STOREINDs and sets a new emit attribute. Also updates gcinfo.
* emit (per arch) looks for this new emit attribute and sets a new flag on the inst descr for the store. Requires updating emitter for all possible forms the store instr may take. Also need to verify this new attribute doesn't get stripped off somewhere along the way.
* emit (common) looks for the special instr descr flag and if set, kills all callee saves in the gc ref live set

@CarolEidt @BruceForstall any advice on how to approach this more cleanly, or does the above look about like you'd expect?

I can share out my fork once it actually is working -- haven't done the last bits of the above yet.

**Comment by AndyAyersMS** [comment]
Another idea (quite possibly not a good idea) is to mark the instruction range where preemptive GC is enabled as non-interruptible. Since we've put the thread into preemptive mode nothing should actually consult the GC info to see if there is a safepoint in this range. Marking it this way should prevent GC stress from instrumenting and avoid getting HW exceptions which are the thing that expose our overly long GC lifetime reporting. But it seems possible that somewhere in the runtime they may check (say during a GC stackwalk) that each frame is stopped at a permissible point.

The more sane alternative is to have special GC info annotations for the vulnerable pinvoke regions (eg no stress instrumentation). This would allow us to undo some of hacks in gccover where it has to specially check for the post-pinvoke gc in progress query. But we probably should avoid creating a bunch of stress only extra data.

**Comment by BruceForstall** [comment]
> Made an attempt at fixing this by just marking the STOREIND in the pinvoke call prolog as special.

You mean the one that sets the GC state to zero?

What you've described seems like a whole lot of complexity. And it also gives the "general" STOREIND some very special-case behavior.

My personal preference would be to add a `GT_PINVOKE_KILL_CALLEE_SAVE_GC_REFS` marker node in the code stream, possibly just before the GC state change, but maybe before any of the call-site pinvoke setup. It could be added first in InsertPInvokeCallProlog. Seems like it wouldn't interact with other nodes, and would only serve to introduce reg kills and a label to mark them in codegen. And LSRA would have to know about the kills, e.g., killGcRegs() would have to change. Our existing `GT_START_NONGC` node is kind of like this.

I presume this should be all-platform, even if you've only seen this fail on arm64.

**Comment by AndyAyersMS** [comment]
RIght, all platform....

I'll give your suggestions a try. When we hit this in codegen we can just directly tell the emitter how to update the GC refs. Does seem quite a bit simpler.

**Comment by AndyAyersMS** [comment]
Have the above mostly implemented, but still not quite sure what to do in the emitter.

In codegen:
```C++
        case GT_START_PREEMPTGC:
            gcInfo.gcMarkRegSetNpt(RBM_INT_CALLEE_SAVED);
            getEmitter()->emitKillCalleeSavesGCRefs();
            break;
```
and then in the emitter, something like:
```
void emitter::emitKillCalleeSavesGCRefs()
{
    emitGCregDeadUpdMask(RBM_INT_CALLEE_SAVE, ...)
}
```
But to do that I need a code pointer... seems like using `emitInsLast` is risky?

Or should have this create a new IG (or force the next instruction to do so) and arrange so that when that IG is created it masks off the callee saves?

**Comment by AndyAyersMS** [comment]
Chatted with @BruceForstall offline and he's pointed me in the right direction -- create a label up in codegen and the gc kills will get propagated to the emitter.
