### ISSUE TITLE
Assert during resource loading prevents crossgen from running on Linux

### ISSUE THREAD

**Issue by JohnChen0** [dotnet/coreclr#1923]
In the current 1.0.0-rc1 build, while using crossgen to compile mscorlib.dll on Linux, an assert failure occurs with debug build, while a segmentation fault occurs with release build. This prevents crossgen from completing successfully.

This has been fixed in master branch with commit 0bc6af1. This commit needs to be merged into rc1 branch.

**Comment by JohnChen0** [comment]
Fixed with commit f9fd9cf.

**Comment by AndyAyersMS** [comment]
@JohnChen0 did you try crossgen on all the framework assemblies with RC1? I am seeing failures.

**Comment by JohnChen0** [comment]
@AndyAyersMS I have run crossgen on a large number of framework assemblies without seeing any issues. Could you please provide more details of the failures?
