### ISSUE TITLE
SSE2 HWIntrinsics tests should be moved to use the code templates

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#19245]
Currently the majority of the SSE2 HWIntrinsic tests are hand written which leads to maintainability issues and gaps in coverage as compared to the other HWIntrinsic tests (templates have been updated a few times, in order to fix bugs, or add new scenarios, which impacts the vast majority of other HWIntrinsic tests).

It would be beneficial to move them to the same code generation templates as the other HWIntrinsic tests. Additionally, if the SSE2 tests were covering relevant code patterns not covered by the existing templates, it should be reviewed whether or not adding those scenarios to the templates would be generally beneficial.

**Comment by tannergooding** [comment]
CC. @fiigii, @CarolEidt, @eerhardt

**Comment by 4creators** [comment]
@tannergooding Yes, I am working on it, but slow progress is due to my other obligations. I do expect to finish the work in 2 - max 3 weeks time frame. If thts OK pls assign it to me.

**Comment by RussKeldorph** [comment]
@tannergooding Can we close this in favor of #19246?  If we need to break out individual test groups, we could use a checklist in that issue.

**Comment by tannergooding** [comment]
Yes, that should be fine. At this point, the `SSE2` tests are the bulk of what remains, in any case.
