### ISSUE TITLE
[Arm64] VIXL?

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#19280]
Linaro is maintaining an open source aarch32/aarch64 assembler disassembler, based on work originally done by ARM.

https://git.linaro.org/arm/vixl.git/about/LICENCE 

I have spent no time looking at it, but I am aware other projects are using this project.

It is not clear whether this might be useful in CoreCLR.  

This issue is just to mention its existence and allow it to possibly be considered.  Feel free to close...

@BruceForstall

**Comment by BruceForstall** [comment]
Interesting; good to know. cc @janvorli 

I'll close the issue since I don't foresee an immediate use, but it's good to have the info here.
