### ISSUE TITLE
Array -> Memory -> Span overly defensive?

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#19293]
Creating a {ReadOnly}Memory from an array does lots of checks; which is correct
https://github.com/dotnet/coreclr/blob/9d1e7dd8eb744b14eb4a90b401e854d7a5f79fff/src/System.Private.CoreLib/shared/System/Memory.cs#L96-L113

Slicing a {ReadOnly}Memory also performs bounds checks based on the confirmed offset and lengths

However creating a Span from and array backed {ReadOnly}Memory uses the regular array constructor
https://github.com/dotnet/coreclr/blob/9d1e7dd8eb744b14eb4a90b401e854d7a5f79fff/src/System.Private.CoreLib/shared/System/Memory.cs#L286-L289

Which then rechecks all the parameters again 
https://github.com/dotnet/coreclr/blob/9d1e7dd8eb744b14eb4a90b401e854d7a5f79fff/src/System.Private.CoreLib/shared/System/Span.Fast.cs#L73-L89

This makes an array backed Memory the most expensive kind of Span creator.

Does it need to recheck everything or can it use an internal Span .ctor that bypasses the additional checks?

/cc @jkotas @stephentoub @GrabYourPitchforks @davidfowl @ahsonkhan

**Comment by benaadams** [comment]
Issue with struct tearing on `Memory<T>` perhaps? Should still be able to skip the array type checks?

**Comment by jkotas** [comment]
> Issue with struct tearing on `Memory<T>` perhaps? 

Right.

**Comment by GrabYourPitchforks** [comment]
I _think_ the JIT will automatically elide the null check in the `Span<T>` ctor, because it should be able to reason that the argument cannot be null due to the shape of the call site in `Memory<T>.get_Span`, and everything gets inlined. However I don't think it can automatically elide the `typeof(T[])` check, even though within `Memory<T>.get_Span` we know this check will succeed. Maybe a potential micro-improvement opportunity?

**Comment by benaadams** [comment]
@GrabYourPitchforks this is fixed now?

**Comment by ahsonkhan** [comment]
> However creating a Span from and array backed {ReadOnly}Memory uses the regular array constructor

> Does it need to recheck everything or can it use an internal Span .ctor that bypasses the additional checks?


Yes, it no longer uses the regular (checked) span ctor: 
https://github.com/dotnet/coreclr/blob/4e23b22ee5cce5db9f8aafb4c6e3b17dbfe07567/src/System.Private.CoreLib/shared/System/Memory.cs#L344

Fixed in https://github.com/dotnet/coreclr/pull/20386
