### ISSUE TITLE
Frequent failure in CoreFX ReadAsyncCompletesIfFlushAsyncCanceledMidFlush test

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19295]
This fails in Jenkins frequently, though not always, e.g.:

Windows x86:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/562/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/560/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/558/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/557/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/554/

Windows x64:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/590/

```  System.IO.Pipelines.Tests.FlushAsyncCancellationTests.ReadAsyncCompletesIfFlushAsyncCanceledMidFlush [FAIL]
        Reader was not completed in reasonable time
        Expected: True
        Actual:   False
```

**Comment by BruceForstall** [comment]
@stephentoub @weshaggard @karelz Can someone get this to the right person?

**Comment by stephentoub** [comment]
Introduced in https://github.com/dotnet/corefx/pull/31212 by @pakrym.

**Comment by BruceForstall** [comment]
@pakrym Are you looking at this?

**Comment by pakrym** [comment]
Yes, sorry, was finishing my 2.1.4 checking yesterday.

**Comment by BruceForstall** [comment]
@pakrym It doesn't look like this is completely fixed. From a few runs I kicked off this afternoon:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_jitstressregs2/604/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_jitstressregs3/587/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstress1/553/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstress2/561/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs0x80/563/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs3/552/

**Comment by BruceForstall** [comment]
It's the Jenkins CI. You can look at the logs for what it does. Basically, it clones and builds dotnet/coreclr, then clones and builds (live, master branch) dotnet/corefx. It uses the built coreclr to run the corefx tests. Referenced above are various jobs, mostly setting different stress mode environment variables.

**Comment by pakrym** [comment]
Are JIT stress runs slower than usual runs?

**Comment by BruceForstall** [comment]
Probably, though I wouldn't expect it to be significant. I don't know what the delta is, though.

**Comment by RussKeldorph** [comment]
There are cases like #18912 where disabling the optimizer can radically affect runtime, and JitStress can sometimes have similar effects on a per-method basis.  So if you get "unlucky" on a critical method, perf can tank.  Not saying that's the case here.  Just FYI.

**Comment by BruceForstall** [comment]
@pakrym The test says "Reader was not completed in reasonable time". What is this "reasonable time"? How is it determined? In one example I saw, the test only ran for 72 seconds. I thought xunit had per-test timeouts of something like 5 minutes.

What are you doing to investigate and fix this?

**Comment by BruceForstall** [comment]
Ok, I see the test has:
```
Assert.True(Task.WaitAll(new [] { writer, reader, canceller }, TimeSpan.FromSeconds(30)), "Reader was not completed in reasonable time");
```

Several questions:
1. Why does the test need to specify a hard-coded time to wait? Shouldn't it just depend on xunit to time it out?
2. Can you simply bump this up to 5 minutes, say? Since in a normal case you say it will be much faster, this shouldn't affect normal cases.
3. IMO, the "reasonable time" should state exactly how long it waited (currently, it should say "Reader was not completed in 30s")

**Comment by pakrym** [comment]
> Why does the test need to specify a hard-coded time to wait? Shouldn't it just depend on xunit to time it out?

Not all repositories have xunit timeout enabled so I specified one to be sure that failing test wouldn't cause a build hang.

> Can you simply bump this up to 5 minutes, say? Since in a normal case you say it will be much faster, this shouldn't affect normal cases.

Yes, I'll open PR to bump it to 5m.

**Comment by BruceForstall** [comment]
Looks like this still fails at least sometimes. Here's a case on arm64:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstressregs1_tst/5/consoleFull
```
01:18:44 Discovering: System.IO.Pipelines.Tests
01:18:50 Discovered:  System.IO.Pipelines.Tests
01:18:54 Starting:    System.IO.Pipelines.Tests
01:24:05 
   System.IO.Pipelines.Tests.FlushAsyncCancellationTests.ReadAsyncCompletesIfFlushAsyncCanceledMidFlush [FAIL]
01:24:05       Reader was not completed in 5 minutes
01:24:05       Expected: True
01:24:05       Actual:   False
```

**Comment by BruceForstall** [comment]
Also, https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstressregs4_tst/5/consoleFull

**Comment by pakrym** [comment]
Not sure what's the best solution here. I can limit iteration count even more but it might prevent the test from hitting original race it was trying to verify.

**Comment by pakrym** [comment]
Fixed in https://github.com/dotnet/corefx/pull/32360

**Comment by pakrym** [comment]
@BruceForstall, can you close this, please?
