### ISSUE TITLE
.NET Core 2.1: Non-GAC DLLs Not Found

### ISSUE THREAD

**Issue by rockerinthelocker** [dotnet/coreclr#19292]
See https://github.com/PowerShell/PowerShell/issues/7326 and https://github.com/PowerShell/PowerShell/issues/7076 for further details. Thank you!

**Comment by jkotas** [comment]
cc @vitek-karas

**Comment by vitek-karas** [comment]
It's possible to workaround this by using `LoadFrom` instead of `LoadFile`. See comment on PowerShell/PowerShell#7326 for more details.

**Comment by jkotas** [comment]
This was answered in https://github.com/PowerShell/PowerShell/issues/7326

**Comment by rockerinthelocker** [comment]
@jkotas , What makes you believe that this was answered? Would you mind to re-open this issue? Thank you!

**Comment by jkotas** [comment]
https://github.com/PowerShell/PowerShell/issues/7326#issuecomment-410712145 is complete answer to this question.

**Comment by rockerinthelocker** [comment]
@jkotalik @coolcsh , Sorry, but that's not the case. Something is broken. Either in PowerShell v6.1.0-preview.3 or .NET Core 2.1. It's that simple; and the MaxMind GeoIP assemblies work just fine with PowerShell v6.1.0-preview.2 and previous versions. So, all the replies you guys have offered are out of context and ignore the facts.

**Comment by vitek-karas** [comment]
I'd be happy to look into it if you do have a repro. I tried the repro described in the powershell issue on the v6.1.0-preview.3 with .NET Core 2.1 and it worked just fine for me (once I applied the workaround).
Maybe if you could share the folder with the dlls and the script you're using (zip it and post it on some file sharing service or on GitHub)… along with the exact environment (please run dotnet --info on the machine and send us the output).

**Comment by rockerinthelocker** [comment]
@vitek-karas, Thank you for taking the time! Below are the requested details.

PowerShell Version Table:

```
PS C:\Users\User> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.4
PSEdition                      Core
GitCommitId                    6.1.0-preview.4
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

.NET Core Details:

```
Microsoft Windows [Version 10.0.17134.165]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\User>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

PowerShell 6.1.0-preview.4 Output:

```
PowerShell 6.1.0-preview.4
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

Loading personal and system profiles took 1132ms.
PS C:\Users\User> $GeoIpDbPath = 'C:\GeoIP\'
PS C:\Users\User> $GeoIpLibrary = $GeoIpDbPath + 'MaxMind.GeoIP2.dll'
PS C:\Users\User> $GeoIpDbLibrary = $GeoIpDbPath + 'MaxMind.Db.dll'
PS C:\Users\User> $GeoIpNewtonJson = $GeoIpDbPath + 'Newtonsoft.Json.dll'
PS C:\Users\User> $GeoIpAsnDb = $GeoIpDbPath + 'GeoLite2-ASN.mmdb'
PS C:\Users\User>
PS C:\Users\User> [System.Reflection.Assembly]::LoadFrom($GeoIpLibrary)

GAC    Version        Location
---    -------        --------
False  v4.0.30319     C:\GeoIP\MaxMind.GeoIP2.dll


PS C:\Users\User> [System.Reflection.Assembly]::LoadFrom($GeoIpDbLibrary)

GAC    Version        Location
---    -------        --------
False  v4.0.30319     C:\GeoIP\MaxMind.Db.dll


PS C:\Users\User> [System.Reflection.Assembly]::LoadFrom($GeoIpNewtonJson)

GAC    Version        Location
---    -------        --------
False  v4.0.30319     C:\Program Files\PowerShell\6-preview\Newtonsoft.Json.dll


PS C:\Users\User> $asnReader = [MaxMind.GeoIP2.DatabaseReader]::new($GeoIpAsnDb)
Exception calling ".ctor" with "1" argument(s): "Could not load type 'System.IO.MemoryMappedFiles.MemoryMappedFileSecurity' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'."
At line:1 char:1
+ $asnReader = [MaxMind.GeoIP2.DatabaseReader]::new($GeoIpAsnDb)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : TypeLoadException

PS C:\Users\User>
```

While LoadFrom grabbed the Newtonsoft.Json.dll from C:\Program Files\PowerShell\6-preview\ instead of the requested C:\GeoIP\ path, it makes no difference when loading the assembly from C:\GeoIP\ via LoadFile; and the same exception is thrown.

So the question certainly is why it worked for @jkotas (https://github.com/PowerShell/PowerShell/issues/7326#issuecomment-411509122), but not with official release builds installed on a fresh Windows 10 1803 guest VM. Thank you!
