### ISSUE TITLE
taskcanceledexception during application shutdown WPF application

### ISSUE THREAD

**Issue by Dileepreddyj** [dotnet/coreclr#19305]
Since the beginning of May, we have seen an increased amount of TaskCanceledExceptions reported by users of our software PDFCreator. This affects all versions of the application (at least three years back) and all of them started showing this exception in May.

This is the complete stack trace:

TaskCanceledException at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout) at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout) at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout) at MS.Internal.WeakEventTable.OnShutDown() at MS.Internal.ShutDownListener.HandleShutDown(Object sender, EventArgs e)

The problems seems to be a refactoring in WeakEventTable. There is an arbitrary timeout of 300ms at line 278:

https://referencesource.microsoft.com/#WindowsBase/Base/MS/Internal/WeakEventTable.cs

A TimeoutException is caught, but it seems to have been moved from to an async Task which throws this TaskCanceledException when the timeout is reached.

**Comment by sharwell** [comment]
@jaredpar this is the same issue we had to deal with in WpfFact, and I think @chgund was dealing with it too.

**Comment by jkotas** [comment]
This is .NET Framework WPF specific issue. CoreCLR repo is not the right place to report .NET Framework WPF issues. The best channels to report this are documented in https://github.com/dotnet/corefx/#how-to-engage-contribute-and-provide-feedback

I see that you have reported this as https://developercommunity.visualstudio.com/content/problem/284294/taskcanceledexception-during-application-shutdown.html . I have asked owners of this area to respond to this issue.
