### ISSUE TITLE
some methods unexpectedly bypass tier0 jitting and go straight to tier1

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#19322]
Noticed this while messing about with the interpreter. A few methods from corelib unexpectedly end up getting jitted initially at tier1 and bypass tier0. 

@kouvel compiled this list for MusicStore:
```
System.SpanHelpers, System.Private.CoreLib.SequenceEqual(Byte ByRef, Byte ByRef, UInt64)
System.SpanHelpers, System.Private.CoreLib.IndexOf(Char ByRef, Char, Int32)
System.SpanHelpers, System.Private.CoreLib.LastIndexOf(Char ByRef, Char, Int32)
System.SpanHelpers, System.Private.CoreLib.SequenceCompareTo(Char ByRef, Int32, Char ByRef, Int32)
System.SpanHelpers, System.Private.CoreLib.IndexOf(Byte ByRef, Byte, Int32)
System.Decimal+DecCalc, System.Private.CoreLib.VarDecFromR8(Double, DecCalc ByRef)
System.SZArrayHelper, System.Private.CoreLib.get_Count<<System.Byte, System.Private.CoreLib>>()
System.SZArrayHelper, System.Private.CoreLib.get_Item<<System.Byte, System.Private.CoreLib>>(Int32)
```
These all seem to be methods that use Vector or HW intrinsics. So perhaps when they bail out from crossgen, something important gets bypassed, and as a result, tiering thinks that they're not tiering-eligible.

cc @noahfalk

**Comment by sergiy-k** [comment]
Many of these methods have the MethodImplOptions.AggressiveOptimization attribute which makes them ineligible for R2R and QuickJIT (Tier0).

I think that we should at least allow to CrossGen them and use the precompiled (potentially less efficient) code if Tiered Compilation is enabled.

@jkotas, @MichalStrehovsky, what do you think?

**Comment by jkotas** [comment]
The reasons for which these methods got marked with AggressiveOptimization should not longer apply with the recent change. I think it should be able to just remove the AggressiveOptimization flag on them.

**Comment by kouvel** [comment]
When the issue was filed CoreLib was NGen'ed and for some reason the listed methods were reporting `IsZapped() == true` but without having pregenerated code, hence they were not eligible for tiering and were being jitted with optimizations. Closing since the original case does not show up anymore with CoreLib being R2R'ed.
