### ISSUE TITLE
PDBs for crossgenned binaries on Linux/macOS?

### ISSUE THREAD

**Issue by rjmholt** [dotnet/coreclr#19337]
I've been working on https://github.com/PowerShell/PowerShell/issues/7348, trying to get symbols available for PowerShell releases.

It looks like PDB generation for crossgen builds is:
 - possible on Windows with https://github.com/dotnet/coreclr/pull/4572
 - but not possible on Linux/macOS with DiaSymReader not open source (based on https://github.com/dotnet/coreclr/issues/8175)

Is that still correct?

Just want to register that PowerShell would get use out of PDBs for crossgen builds on Linux/macOS.

**Comment by jkotas** [comment]
The original IL PDBs work fine with crossgened binaries for debugging. You should just distribute those.

The native PDBs produced by crossgen are only needed for sampling profilers on Windows. You should not need to produce native PDBs on Unix.

**Comment by rjmholt** [comment]
Thanks @jkotas!
