### ISSUE TITLE
Assert failure: !IsAfContentType_WindowsRuntime(pModule->GetAssemblyRefFlags(tkType))

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19347]
Seen in Ubuntu arm32 Checked R2R testing:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/arm_cross_checked_ubuntu_r2r_flow/20/

Also, e.g., Ubuntu x64 Checked R2R:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/x64_checked_ubuntu_r2r_flow/2364/

```
./tests/runtest.sh: line 537:  2762 Aborted                 $overlayDir/crossgen /Platform_Assemblies_Paths $overlayDir $filename > $filename.stdout 2> $filename.stderr
Unable to precompile /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_r2r_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/System.Runtime.WindowsRuntime.dll.
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.


Assert failure(PID 2762 [0x00000aca], Thread: 2762 [0x0aca]): !IsAfContentType_WindowsRuntime(pModule->GetAssemblyRefFlags(tkType))
    File: /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/src/vm/assembly.cpp Line: 1222
    Image: /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_r2r_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/crossgen
```

**Comment by BruceForstall** [comment]
@nattress @kouvel @jkotas Can someone please triage?

**Comment by nattress** [comment]
I'm surprised we even try and build / crossgen System.Runtime.WindowsRuntime on Linux. It has assembly refs to WinRT types which are not going to work.

**Comment by BruceForstall** [comment]
This appears to be a regression, due to one of the changes in https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/arm_cross_checked_ubuntu_r2r_flow/20/, since the test passed in the previous build (https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/arm_cross_checked_ubuntu_r2r_flow/19/). Did System.Runtime.WindowsRuntime.dll just show up?

Should we get an assertion, or a different failure message?

If you just want to disable crossgen of this, you can add it to these files in the tests directory:
```
skipCrossGenFiles.arm.txt
skipCrossGenFiles.arm64.txt
skipCrossGenFiles.x64.txt
skipCrossGenFiles.x86.txt
```

**Comment by nattress** [comment]
Yeah that assembly just showed up recently looking at previous test runs. I'll get it skipped. We should give an instructive error message in this case instead of just asserting.

**Comment by nattress** [comment]
I checked on retail build and we fail compilation with an error. The assert just fires first in chk builds.

**Comment by nattress** [comment]
What do we want to fix here? An assert fires in chk builds but Crossgen will fail with an error message about being unable to resolve the WinRT type if you ignore the assert (or have asserts off).

**Comment by BruceForstall** [comment]
Don't you just want the error message to occur in all cases? Simply passing the crossgen tool an assembly it can't/shouldn't compile shouldn't generate an assert.
