### ISSUE TITLE
Report a better error message when assembly version conflict is encountered

### ISSUE THREAD

**Issue by tmat** [dotnet/coreclr#19357]
I’m seeing very odd intermittent failures on .NET Core 2.1.400-preview-009088 when loading a dependency from a build task.

An example of such failure is https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=1916424&_a=summary&view=logs 

E:\A\_work\154\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-prerelease-63202-02\tools\Sign.proj(39,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'System.IO.Packaging, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
E:\A\_work\154\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-prerelease-63202-02\tools\Sign.proj(39,5): error MSB4018: File name: 'System.IO.Packaging, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

The file being loaded (System.IO.Packaging) is located in the same directory as the build task assembly.

Memory dump: %internal_share%\tomat\Bugs\CoreLoaderBug

Turns out we have two tasks that depend on a different version of System.IO.Packaging - 4.0.2.0 and 4.0.3.0. The load error is intermittent since it depends on the order in which these two versions are loaded. The solution to this problem would be to load tasks to separate Assembly Load Contexts: https://github.com/Microsoft/msbuild/issues/1754.

However, the assembly loader should report an error that indicates the version mismatch instead of the above error.

**Comment by tmat** [comment]
@markwilkie @weshaggard FYI - This loader bug affects Arcade build tasks.

**Comment by tmat** [comment]
@mikem8361 FYI - this is the issue I mentioned.

**Comment by 4creators** [comment]
I am hitting similar problems in custom build system for some of products I work on.

**Comment by jeffschwMSFT** [comment]
Thanks for the feedback.  We are working on diagnostics so I am going to close this bug for now in favor of other bugs tracking similar situations #18147
