### ISSUE TITLE
[RyuJIT/arm64] Implement ELT hooks

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19368]
It looks like genProfilingEnterCallback and genProfilingLeaveCallback will NYI on arm64.

**Comment by AndyAyersMS** [comment]
@BruceForstall seems like you should take this one?
cc @RussKeldorph

**Comment by BruceForstall** [comment]
I'll take it, but it's not a 3.0 issue, so I'll move it out of 3.0.

**Comment by AndyAyersMS** [comment]
Can you comment on why it's not a 3.0 issue?

**Comment by BruceForstall** [comment]
The diagnostics team does not include the profiling apis for arm64 as a 3.0 committed feature.
