### ISSUE TITLE
JIT generates binary different code in x86_arm and arm_arm due to host NaN representation

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#19370]
It seems that assumption that two crossgens (x86_arm and arm_arm) generate binary identical code is not 100% true. 
I encountered this for `Microsoft.VisualBasic.dll` - produced native images were different in one **bit**! (ignoring mismatching checksums). 

The divergence happens during ` Microsoft.VisualBasic.CompilerServices.Operators:DivideObject(ref,ref):ref` method compilation.

The "interesting" place in x86_arm disassembly:
```asm
00008A  2200           movs    r2, 0
00008C  F240 0300      movw    r3, 0x00
000090  F6CF 73F8      movt    r3, 0xfff8
000094  EC43 2B14      vmov.i2d d8, r2, r3
000098  ED80 4B01      vstr    d8, [r0+4]
```

The corresponding place in arm_arm disassembly:
```asm
00008A  2200           movs    r2, 0
00008C  F240 0300      movw    r3, 0x00
000090  F6C7 73F8      movt    r3, 0x7ff8
000094  EC43 2B14      vmov.i2d d8, r2, r3
000098  ED80 4B01      vstr    d8, [r0+4]
```

The code is the compiled following expression 
```C#
double cnsZero = 0.0;
double cnsNaN = cnsZero / cnsZero;
```

During its compilation JIT in `fgValueNumber()` relies on the following function
https://github.com/dotnet/coreclr/blob/d1804ad5634ef85d88b52331b99b1f58626dacf2/src/jit/valuenum.cpp#L248-L270 
which on Linux/x86 host for `v1 / v2` where `v1=0.0` and `v2=0.0` returns `fff8 0000 0000 0000` while on arm host the result is `7ff8 0000 0000 0000`. 

While semantically they both are correct this would cause us a problem with validation of cross-bitness crossgen work in the future. 

The workaround for this could be similar to how https://github.com/dotnet/coreclr/blob/d1804ad5634ef85d88b52331b99b1f58626dacf2/src/jit/valuenum.cpp#L227 is implemented and use "custom" implementation for double/float division
```c++
TFp FpDiv(TFp dividend, TFp divisor)
{
    // From the ECMA standard:
    //
    // If [dividend] is zero and [divisor] is zero
    //   the result is NaN.
    // If [dividend] is infinity and [divisor] is infinity
    //   the result is NaN.

    if (dividend == 0 && divisor == 0)
    {
        return TFpTraits::NaN();
    }
    else if (!_finite(dividend) && !_isnan(dividend) && !_finite(divisor) && !_isnan(divisor))
    {
        return TFpTraits::NaN();
    }

    return dividend / divisor;
}
```

@dotnet/jit-contrib Is there any better idea how to approach this issue?

**Comment by BruceForstall** [comment]
The "custom" FpDiv solution looks like a good solution to me.

**Comment by echesakovMSFT** [comment]
Closing via #19395
