### ISSUE TITLE
CoreClr failed to build on Windows due to MSBUILD ERROR : error MSB1001: Unknown switch. Switch: --

### ISSUE THREAD

**Issue by LarryIII** [dotnet/coreclr#19376]
Hello,
I am testing CoreCLR on Windows with VS 2017 15.7.2. It failed due to the "error MSB1001: Unknown switch. Switch: --". It casued by commit:https://github.com/dotnet/coreclr/commit/b37c6d8ee5b4ad9833f21cfc30582b56797e37b4.
I noticed you removed '--' on purpose, I am surprised why does not support '--' to add  extra MSBUILD options? Is there other way that we can add extra MSBUILD flags when building source!

You can repro the issue as the steps below:
1. git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2. Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\CoreCLR\src
3. build x86 release -- /clp:ShowCommandLine

Could you please give me a workaround for this or consider rollback this to use '--' when building?
Thank you!

**Comment by jkotas** [comment]
cc @BruceForstall

**Comment by RussKeldorph** [comment]
[This](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=1933375&view=logs) build supposedly checked out d485659348af3528b688ac5b7e4c58dacba6de58 but still failed with the same error.

**Comment by BruceForstall** [comment]
This should have fixed it: https://github.com/dotnet/coreclr/pull/19367

**Comment by BruceForstall** [comment]
This will fix it: https://github.com/dotnet/coreclr/pull/19382

**Comment by BruceForstall** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/19382

**Comment by LarryIII** [comment]
Thanks All :)
