### ISSUE TITLE
OSX CoreFX CI Leg is Consistently Failing

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#19403]
It appears that all runs of this CI leg are failing due to tests timing out: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_debug_osx10.12_corefx_innerloop_prtest/

**Comment by brianrob** [comment]
@RussKeldorph not sure who owns these.
@BruceForstall not sure if this is related to your change a couple of days ago to netci.groovy - https://github.com/dotnet/coreclr/commit/e1a46af39014796606d1f40ecd090602f987a145.

**Comment by 4creators** [comment]
Some runs are passing:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_corefx_innerloop_prtest/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_osx10.12_corefx_innerloop_prtest/

It seems `checked`and `release` builds have chance to pass, sometimes there are IO errors:
```
java.nio.channels.ClosedChannelException
```

**Comment by BruceForstall** [comment]
@A-And

**Comment by MattGal** [comment]
The failing legs all look like this:

```
09:58:23 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.WriteAsync_AfterComplete_ThrowsException finished in 628360ms.
09:58:23 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.Complete_WithException_PropagatesToNewWaitingReader finished in 628372ms.
09:58:24 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.WaitToReadAsync_DataWritten_CompletesSuccessfully(cancelable: False) finished in 628440ms.
09:58:24 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.WaitToReadAsync_DataWritten_CompletesSuccessfully(cancelable: True) finished in 628447ms.
09:58:24 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.TryComplete_Twice_ReturnsTrueThenFalse finished in 628453ms.
09:58:24 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.Complete_AfterEmpty_NoWaiters_TriggersCompletion finished in 628461ms.
09:58:24 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.WaitToReadAsync_DataAvailableAfter_CompletesAsynchronously finished in 628469ms.
09:58:24 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.ManyWriteAsync_ThenManyTryRead_Success(readMode: 0) finished in 628515ms.
09:58:24 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.ManyWriteAsync_ThenManyTryRead_Success(readMode: 1) finished in 628517ms.
09:58:24 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.WaitToReadAsync_NoDataWritten_Canceled_CompletesAsCanceled finished in 628522ms.
09:58:24 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.ValueTask_MultipleContinuations_Throws finished in 628537ms.
09:58:24 WARNING: Long running test System.Threading.Channels.Tests.SyncSingleReaderUnboundedChannelTests.ReadAsync_AwaitThenGetResult_Throws finished in 628552ms.
```
Are we certain that these warnings aren't legititmate ??  @mmitche might have more insight and is online a couple times a day but these runs look tanked due to insanely slow execution, as much as 45 minutes for a single XUnit fact.

**Comment by BruceForstall** [comment]
@A-And It looks like a PR currently triggers these CoreFX jobs:
```
OSX10.12 x64 Release CoreFX Tests
OSX10.12 x64 Checked CoreFX Tests
OSX10.12 x64 Debug CoreFX Tests
Ubuntu x64 Checked CoreFX Tests
Windows_NT x64 Debug CoreFX Tests
Windows_NT x64 Checked CoreFX Tests
Windows_NT x64 Release CoreFX Tests
```

Is that the right set? Can / should we disable all the OSX jobs? Can we disable the Debug jobs altogether?

**Comment by AndyAyersMS** [comment]
Maybe make the names more expressive too, so we know for sure how each part is built? Is `Windows_NT x64 Debug CoreFX Tests` running a debug CoreCLR, or testing a debug CoreFx, or both, or some hybrid?

I would expect we'd rarely want to test a debug CoreCLR, especially on something like this.

**Comment by jkotas** [comment]
> Is that the right set? 

This matrix is excessive. We should have ~3 CoreFX legs triggered by default, some combinations of checked/release and OS flavors. 7 is way too much. I though we had 3 originally - I have not noticed PRs that enabled the extra 4.

> Can we disable the Debug jobs altogether?

Yes.

**Comment by BruceForstall** [comment]
> I have not noticed PRs that enabled the extra 4.

It's possible my recent netci.groovy hacking has inadvertently added more.

I'll work on a change to reduce to this:

```
Ubuntu x64 Checked CoreFX Tests
Windows_NT x64 Checked CoreFX Tests
Windows_NT x64 Release CoreFX Tests
```

**Comment by BruceForstall** [comment]
Done. https://github.com/dotnet/coreclr/pull/19414.

**Comment by BruceForstall** [comment]
I'm going to close this issue, since we don't have OSX CoreFX PR jobs in the CI anymore.
