### ISSUE TITLE
Run DotNet Core App on X86 Without OS

### ISSUE THREAD

**Issue by alan1010ten** [dotnet/coreclr#19402]
How to run DotNet Core app on X86, without OS?

**Comment by gfoidl** [comment]
Well, by installing any [supported OS](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md), the by installing the [.NET Core Runtime](https://www.microsoft.com/net/download/dotnet-core/2.1) for that OS.

Or do you mean something different? If so, please eloberate your concern.

**Comment by alan1010ten** [comment]
I mean run DotNet Core on X86, without any OS.

**Comment by gfoidl** [comment]
Since a OS is a prerequisite for .NET Core this won't be possible.

The runtime calls "into" the OS in several ways (memory, IO, etc.) so .NET Core can't live without the OS.

**Comment by jkotas** [comment]
@gfoidl Thanks for the answer

**Comment by 4creators** [comment]
> Since a OS is a prerequisite for .NET Core this won't be possible.

It is not entirely true. In HPC area so called `library operating systems` are often used to replace whole OS. It usually works in such configuration that on one node you have minimal hypervisor with multiple VMs. One VM runs linux kernel and some drivers to serve selected OS services to all other VMs which run on `bare metal hypervisor`. To run on `bare metal` you need to provide basic services to runtime what is done using external library. Library OS is often statically linked with runtime as seamless `runtime-os package` on top of which you can run whatever runtime supports.

Similar idea is to use `unikernels` or in other words one process `operating system - runtime package`.
