### ISSUE TITLE
JIT: jitstress2 failure in JIT\Methodical\fp\exgen\10w5d_cs_ro after switch to R2R codegen for corelib

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#19413]
Fails after #19359, running with x64 checked. Method prints same output stream, but return code is now 108 instead of 100.

Fair number of diffs in jitted code before/after this change. Haven't tried pinning it down yet.

cc @dotnet/jit-contrib

**Comment by sandreenko** [comment]
I thinks it is dup of #18988.

**Comment by AndyAyersMS** [comment]
Yes, seems likely.

**Comment by sandreenko** [comment]
Fixed by @mikedn #19621.
