### ISSUE TITLE
Enumerable.Except method filters the enumerable to distinct items; this isn't stated.

### ISSUE THREAD

**Issue by ekolis** [dotnet/coreclr#19443]
For instance if I have

    var nums = new int[] { 1, 1, 2, 3 };
    foreach (var num in nums.Except(new int[] { 3 }))
	Console.Write(num);

I expect to see 112 but I only see 12.

**Comment by Tornhoof** [comment]
According to https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except?view=netcore-2.1#System_Linq_Enumerable_Except__1_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___0__

it's defined as the _set difference_, a set in mathematics is not allowed to have duplicate values.
The source code example even shows that (two 2.0, 2.3 in numbers1, output is only one 2).

**Comment by jkotas** [comment]
This issue was moved to dotnet/docs#6968
