### ISSUE TITLE
R2RDumpTest debug failure

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19441]
This test appears to have started failing in Debug runs with https://github.com/dotnet/coreclr/pull/19419

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/x86_debug_windows_nt/5075/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/debug_windows_nt/5358/

@nattress @acmyu

**Comment by acmyu** [comment]
A recent change caused two of the runtime functions in the native image to switch their id, so the output of R2RDump no longer matches the expected xml. I've created a pr to disable R2RDumpTests for now because it's too fragile
