### ISSUE TITLE
Japanese Lunisolar Calendar conversion table discrepancy for the year 1962

### ISSUE THREAD

**Issue by elyoh** [dotnet/coreclr#19450]
The [Japanese Lunisolar Calendar](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Globalization/JapaneseLunisolarCalendar.cs) uses a table of data for conversion between Japanese lunisolar dates and Gregorian dates.  There appears* to be a discrepancy for the table entry for the _days in months_ for lunar months 6 and 7 of the lunar year which started in the Gregorian year 1962 when compared with two other sources.  These are:
- output from Calendrical Calculations (4th edition, section 19.9) which provides algorithms for accurate dates for the period 1860 to at least 2100
- [Rekijitsu taikan : Meiji kaireki 1873-nen--2100-nen shinkyūreki, kanshi kyūsei rokuyō taishō](http://www.worldcat.org/title/rekijitsu-taikan/oclc/675252389?referer=di&ht=edition ()) which provides accurate tables of dates in this calendar over the period years 1873 to 2100 (with the exception of 1947)

*there isn't a source given for the existing table data - is it still known / available for cross check?

**Comparison of table data**

Days in month for 1962  | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
.NET | 29 | 30 | 29 | 29 | 30 | **30** | **29** | 30 | 29 | 30 | 30 | 29 | 0
Calendrical Calculations / Rekijitsu taikan | 29 | 30 | 29 | 29 | 30 | **29** | **30** | 30 | 29 | 30 | 30 | 29 | 0

Assuming the output of Calendrical Calculations algorithms is correct, then the current table entry for 1962:
`1962    */{    0    ,    2    ,    5     ,    19808    },/*    29    30    29    29    30    30    29    30    29    30    30    29    0    354`
should be changed to
`1962    */{    0    ,    2    ,    5     ,    19296    },/*    29    30    29    29    30    29    30    30    29    30    30    29    0    354`

At the same time, it would also be a _trivial_ matter to extend the table to support dates for all the Japanese calendar eras currently supported by .NET (Meiji, Taisho, Showa, and Heisei).  Given the recent updates to the Japanese and Japanese Lunisolar calendars relating to the new Japanese calendar era, this might be an appropriate time to do that.

I would be happy to submit PR to address these.

**Comment by elyoh** [comment]
I have also verified this with a third source:
- output from the [USNO Astronomical Applications API v2.1.0](http://aa.usno.navy.mil/data/docs/api.php#rstt).

Dates of the new moon for Tokyo in 1962 (lat 35, lon 135, timezone +9h) were obtained using the public API and _days in month_ calculated (note - lunar months start on the day of the new moon and end on the day preceding the next new moon).

Lunar month | Dates of new moon for Tokyo | Days in Month
-- | -- | --
1 | 05-Feb-62 | 29
2 | 06-Mar-62 | 30
3 | 05-Apr-62 | 29
4 | 04-May-62 | 29
5 | 02-Jun-62 | 30
6 | 02-Jul-62 | **29**
7 | 31-Jul-62 | **30**
8 | 30-Aug-62 | 30
9 | 29-Sep-62 | 29
10 | 28-Oct-62 | 30
11 | 27-Nov-62 | 30
12 | 27-Dec-62 | 29
1 | 25-Jan-63 | -

The results match exactly with Calendrical Calculations and again suggest that the existing _days in month_ table entry for 1962 is incorrect.

**Comment by tarekgh** [comment]
@elyoh do you want to open a PR to fix this?

**Comment by tarekgh** [comment]
Thanks again @elyoh
