### ISSUE TITLE
Chinese Lunisolar Calendar conversion table discrepancy for the years 2057, 2089, and 2097

### ISSUE THREAD

**Issue by elyoh** [dotnet/coreclr#19480]
The [Chinese Lunisolar Calendar](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Globalization/ChineseLunisolarCalendar.cs) uses a table of data for conversion between Chinese lunisolar dates and Gregorian dates. There appears to be a discrepancy for the table entry for the _days in months_ for the lunar years which started in the Gregorian years 2057, 2089, and 2097 when compared with other sources. These are:

- output from Calendrical Calculations (4th edition, section 19) which implements the Chinese lunisolar calendar rules used by the [Purple Mountain Observatory](http://english.pmo.cas.cn/) as also detailed [here](http://aa.usno.navy.mil/publications/docs/c15_usb_online.pdf)
- footnote on [tables](http://www.hko.gov.hk/gts/time/conversion.htm) published by the Hong Kong Observatory which state their tables are out by one day for the new moons on 28 September 2057, 4 September 2089, and 7 August 2097 (which matches exactly with the same discrepancy between the .NET tables and output from Calendrical Calculations)

Year | Days in month | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2057 | .NET | 29 | 30 | 30 | 29 | 30 | 29 | 30 | **30** | **29** | 29 | 30 | 29 | 0
2057 | CC    | 29 | 30 | 30 | 29 | 30 | 29 | 30 | **29** | **30** | 29 | 30 | 29 | 0
2089 | .NET | 30 | 30 | 29 | 30 | 29 | 29 | **30** | **29** | 29 | 30 | 30 | 29 | 0
2089 | CC    | 30 | 30 | 29 | 30 | 29 | 29 | **29** | **30** | 29 | 30 | 30 | 29 | 0
2097 | .NET | 30 | 29 | 30 | 29 | 29 | **30** | **29** | 29 | 30 | 30 | 29 | 30 | 0
2097 | CC    | 30 | 29 | 30 | 29 | 29 | **29** | **30** | 29 | 30 | 30 | 29 | 30 | 0

Existing table entries:
```
2057    */{ 0 , 2 , 4 , 27424 },/*    29    30    30    29    30    29    30    30    29    29    30    29    0  354
2089    */{ 0 , 2 , 10 , 53856 },/*   30    30    29    30    29    29    30    29    29    30    30    29    0  354
2097    */{ 0 , 2 , 12 , 42192 },/*   30    29    30    29    29    30    29    29    30    30    29    30    0  354
```
Suggested updated table entries based on Calendrical Calculations:
```
2057    */{ 0 , 2 , 4 , 27296 },/*    29    30    30    29    30    29    30    29    30    29    30    29    0  354
2089    */{ 0 , 2 , 10 , 53600 },/*   30    30    29    30    29    29    29    30    29    30    30    29    0  354
2097    */{ 0 , 2 , 12 , 41680 },/*   30    29    30    29    29    29    30    29    30    30    29    30    0  354
```

**Comment by elyoh** [comment]
I have also verified this with a third source:
- output from the [USNO Astronomical Applications API v2.1.0](http://aa.usno.navy.mil/data/docs/api.php#rstt).

Dates of the new moon for Beijing (lat 39.9°, lon 116.4°, timezone +8h) for the 3 years in question were obtained using the public API and _days in month_ calculated (note - lunar months start on the day of the new moon and end on the day preceding the next new moon).  The calculations should use a height of 43.5 m but the API does not support that.  This is only relevant if the time of the new moon is close to midnight (as it is in one case in 2097).

Lunar month | Dates of new moon for Beijing | Days in Month
-- | -- | --
1 | 04-Feb-57 | 29
2 | 05-Mar-57 | 30
3 | 04-Apr-57 | 30
4 | 04-May-57 | 29
5 | 02-Jun-57 | 30
6 | 02-Jul-57 | 29
7 | 31-Jul-57 | 30
8 | 30-Aug-57 | 30
9 | 29-Sep-57 | 29
10 | 28-Oct-57 | 29
11 | 26-Nov-57 | 30
12 | 26-Dec-57 | 29
1 | 24-Jan-58 | -
1 | 10-Feb-89 | 30
2 | 12-Mar-89 | 30
3 | 11-Apr-89 | 29
4 | 10-May-89 | 30
5 | 09-Jun-89 | 29
6 | 08-Jul-89 | 29
7 | 06-Aug-89 | 29
8 | 04-Sep-89 | 30
9 | 04-Oct-89 | 29
10 | 02-Nov-89 | 30
11 | 02-Dec-89 | 30
12 | 01-Jan-90 | 29
1 | 30-Jan-90 | -
1 | 12-Feb-97 | 30
2 | 14-Mar-97 | 29
3 | 12-Apr-97 | 30
4 | 12-May-97 | 29
5 | 10-Jun-97 | 29
6 | 09-Jul-97 | 30
7 | 08-Aug-97 | 29
8 | 06-Sep-97 | 29
9 | 05-Oct-97 | 30
10 | 04-Nov-97 | 30
11 | 04-Dec-97 | 29
12 | 02-Jan-98 | 30
1 | 01-Feb-98 | -

The results for 2057 and 2089 match exactly with Calendrical Calculations.
The result 2097 matches the .NET table.  

As noted earlier, the Astronomical Applications API does not include elevation in the calculation and this is important for accounting for the mismatch in 2097.  According to the Astronomical Applications API, the new moon corresponding with the start of lunar month 7 of in Gregorian year 2097 takes place on August 8, 2097 at a local time of 00:01 at elevation **0m**.  If the correct elevation of 43.5m is used (as per Calendrical Calculations), the same new moon occurs slightly earlier on August 7, 2097 (note - sunrise and moon rise are earlier with increased elevation).  It is therefore still highly likely that the .NET table entry for 2097 is incorrect.

A final [source](http://www.math.nus.edu.sg/aslaksen/calendar/cal.pdf) notes that both 2089 and 2097 are lunar years with 3 short (29-day) months in a row.

**Comment by tarekgh** [comment]
@elyoh do you want to submit a PR to fix that?
