### ISSUE TITLE
Build CoreCLR on FreeBSD11

### ISSUE THREAD

**Issue by Szadegan** [dotnet/coreclr#19481]
Hi,
I am trying to use the instructions for FreeBSD to build CoreCLR on FreeBSD11 with llvm3.8
During Build the runtime step (build.sh) I got this error:
`[ 99%] Linking CXX shared library libcoreclr.so Killed *** [all] Error code 137 make: stopped in /usr/home/git/coreclr/bin/obj/FreeBSD.x64.Debug 1 error make: stopped in /usr/home/git/coreclr/bin/obj/FreeBSD.x64.Debug Failed to build CoreCLR component.`

![image](https://user-images.githubusercontent.com/24319588/44094619-f82549e2-9fd6-11e8-88ec-e5e6f40395a9.png)

**Comment by Szadegan** [comment]
Just as an update, I will try to install it on a server with a better config. Eventhough my current server has 1GB RAM which should be enough

**Comment by wfurt** [comment]
we have daily builds now. reopen if you still have issue.
