### ISSUE TITLE
Refactor instrsxarch.h to contain a `flags` field

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#19498]
Currently the `instrsxarch.h` macros define a number of pieces of information for each instruction:
* id
* name
* update mode
* encodings
* flags
  * is floating point
  * reads flags
  * writes flags

The `flags` are currently listed separately and combined later:
```cpp
// ...
#define INST5(id, nm, fp, um, rf, wf, mr, mi, rm, a4, rr)
// ...
INST5(push   , "push"         , 0, IUM_RD, 0, 0, 0x0030FE, 0x000068, BAD_CODE, BAD_CODE, 0x000050)
```
and
```cpp
const BYTE          CodeGenInterface::instInfo[] =
{
    // ...
    #define INST5(id, nm, fp, um, rf, wf, mr, mi, rm, a4, rr ) (INST_USE_FL*rf|INST_DEF_FL*wf|INST_FP*fp),
    // ...
};
```

I propose we refactor this so that all flags are listed together, under a single macro parameter. This would help facilitate the ability to insert additional flags, as necessary:
```cpp
#define INST5(id, nm, um, flags, mr, mi, rm, a4, rr)
INST5(push   , "push"         , IUM_RD, INS_FLAGS_None,        0x0030FE, 0x000068, BAD_CODE, BAD_CODE, 0x000050)
INST5(inc    , "inc"          , IUM_RW, INS_FLAGS_WritesFlags, 0x0000FE, BAD_CODE, BAD_CODE, BAD_CODE, 0x000040)
```
and
```
const insFlags          CodeGenInterface::instInfo[] =
{
    // ...
    #define INST5(id, nm, um, flags, mr, mi, rm, a4, rr ) static_cast<insFlags>(flags),
    // ...
};
```

**Comment by tannergooding** [comment]
CC. @mikedn, @BruceForstall, @CarolEidt 

Namely, this would help facilitate adding flags for the various SSE-AVX2 instructions, where it would allow us to cut out a number of the big switch tables we have today:
* `IsDstDstSrcAVXInstruction`: https://github.com/dotnet/coreclr/blob/master/src/jit/emitxarch.cpp#L138
* `IsDstSrcSrcAVXInstruction`: https://github.com/dotnet/coreclr/blob/master/src/jit/emitxarch.cpp#L386

It would also help facilitate other changes that may require or benefit from per instruction flags, such as adding the 2-byte VEX encoding support.

**Comment by tannergooding** [comment]
@BruceForstall, @CarolEidt. Does this look reasonable to you?

If so, the refactoring is fairly trivial to make. Some profiling I did with VTune showed that `IsDstDstSrc` was taking around 10% of the emit time for HWIntrinsic intensive code.

**Comment by CarolEidt** [comment]
This looks quite reasonable to me. And the `IsDstDstSrc` and `IsDstSrcSrc` methods have been the source of numerous bugs in the past. Making the information declarative is far better than having it in code, and putting it in the table with the instructions should make it harder to forget to think about this.

While emit may not be as high a throughput impact as some other phases, the fact that so much of the per-instruction information is contained in code rather than declared with the instruction makes a higher maintenance burden.
