### ISSUE TITLE
Unsafe.Unbox is not available inside mscorlib

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#19492]
I am wondering why `Unsafe.Unbox` is not part of CoreCLR - I see it is available in CoreFX: https://github.com/dotnet/corefx/pull/31133/files 
I wrote a small roslyn script https://gist.github.com/EgorBo/41d91a4d0b6ccb90096dd7cc0857dfa0 and it found lots of places where I believe we could utilize `ref Unsafe.Unbox<T>` instead of unboxing and wondering if it makes sense or not, e.g. https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Guid.cs#L1048
![image](https://user-images.githubusercontent.com/523221/44123805-a870ef4e-a032-11e8-93a7-47f98ef7dd89.png)

**Comment by benaadams** [comment]
Was added 28 days ago and marked with the 3.0 milestone?

**Comment by benaadams** [comment]
Ah, you mean not downlevel for use in coreclr?

**Comment by EgorBo** [comment]
@benaadams yeah exactly, in coreclr. To be able to improve some mscorlib bits (including shared?)

**Comment by jkotas** [comment]
We add Unsafe methods to CoreLib clone as needed. It is not available in CoreLib because of nothing needed it so far. If you have a good use for it in CoreLib, feel free to add it.
