### ISSUE TITLE
Implement GetThreadTimes in PAL

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/coreclr#195]
Currently we have an empty stub in coreclr/src/pal/src/thread/thread.cpp.
We need to provide proper implementation for Linux and add a test under coreclr/src/pal/tests/palsuite.

**Comment by kangaroo** [comment]
See https://github.com/dotnet/coreclr/issues/197 for how to grab kernel and user time at the least.

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/coreclr/pull/1671

**Comment by wtgodbe** [comment]
Resolved by #1671
