### ISSUE TITLE
Question on sealed / NotInheritable

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/coreclr#19506]
When implementing such classes I was wondering where it was stated in the documentation the semantics associated with sealing a class.

Specially the question is as follows:

If I have a class which has a virtual method

`class Class { virtual void Method(){}}`

Then I override this method in a derived class

`class DerivedClass{ overide void DerivedMethod(){}}`

Then I seal a new derived class as follows

`sealed class SealedClass{ overide sealed void SealedMethod(){}}`

Do I need to explicitly seal the method also? My take would be is that since the type is sealed implicitly all virtual methods MUST be sealed but I can see other answers to that argument also given potential changes in the CLR and certain scenarios but I am not 100% sure although I would be surprised to learn such.

Thanks for the clarification!

**Comment by adityamandaleeka** [comment]
`sealed` specifies that the type cannot be derived from, so it's not possible for another class to come along and override a virtual method on a sealed type.

I'll close this issue now since it's a general language question and not a CoreCLR issue.
