### ISSUE TITLE
Fix sos clrstack unwinding for the special HelperMethodFrame

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#1950]
The sos clrstack command sometimes hangs or stops unwind when it hits the special HelperMethodFrame when dumping managed stacks.  This requires an out of context stack unwinder in the DAC to fix this problem and there isn't one available for OSx and the one available for Linux doesn't work on all distributions so it has been disabled. The fix I propose is to use the lldb unwinding abi via the data target interface provided to DAC by the SOS code.

**Comment by mikem8361** [comment]
PR #1946 has resolved this issue

**Comment by joshfree** [comment]
reactivating issue until a fix is made in the /release/1.0.0-rc1 branch.
