### ISSUE TITLE
Add a flag to enable/disable hw intrinsics

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#19519]
This could potentially be a a `COMPlus_EnableHWIntrinsics` flag that is exposed in Release. It would be set to 1 by default, and could be set to 0 to disable them. It would need to imply `COMPlus_FeatureSIMD`, as the JIT relies on that flag for much of the code that supports the vector types.

**Comment by CarolEidt** [comment]
As discussed in https://github.com/dotnet/corefx/pull/31779

**Comment by CarolEidt** [comment]
cc @eerhardt @tannergooding

**Comment by danmosemsft** [comment]
I think it would be helpful if I could set different values to control each of the `XXX.IsSupported` individually. If my goal is to have a way to force the code down every possible path for tests.

**Comment by CarolEidt** [comment]
> I think it would be helpful if I could set different values to control each of the XXX.IsSupported individually. If my goal is to have a way to force the code down every possible path for tests.

We have that for Checked, which I think is sufficient (open to other views here, though). We also have `Complus_EnableAVX` supported for Release, which is useful as it controls whether the AVX encodings are used.

For this specifically I thought it would be useful to expose it in Release.

**Comment by tannergooding** [comment]
The benefit of having it for each `ISA` as well, is that you don't have to recompile in order to test certain code paths (you can compile once and then run multiple times with different env flags to test AVX, SSE, etc)

We might need something like that if we want to have benchmark tests (or functional tests) for CoreFX that covers 'Software' vs 'Sse' vs Sse3' vs 'Avx', etc

**Comment by danmosemsft** [comment]
If we are running CoreFX tests presumably it would be easier to just run all the tests in the repo with the flag in which case we would presumably prefer a release runtime for speed.

**Comment by tannergooding** [comment]
Having the capability to control the individual ISAs has come up again for ML.NET: https://github.com/dotnet/machinelearning/pull/1292

I believe it is going to be almost impossible to do any sort of long term benchmarking, testing, etc; without having the ability to control these flags in retail configurations. Modifying the source code and recompiling is not going to be a maintainable scenario for real-world codebases that are external to CoreFX or CoreCLR.

**Comment by CarolEidt** [comment]
Closed with https://github.com/dotnet/coreclr/issues/20498
