### ISSUE TITLE
C# Wpf Image Memory with High Resolution images(7680 X 2180) 

### ISSUE THREAD

**Issue by ankur4747github** [dotnet/coreclr#19517]
Problem:- WPF image holds memory. when I select an image from the directory and displayed to the image after click on destroy-image-button image is destroyed but memory is still on hold as per TaskManager and after done the same operation many times application will crash outof memory exception.. this issue is with High Resolution images(7680 X 2180)

An unhandled exception of type 'System.OutOfMemoryException' occurred in PresentationCore.dll

{The function evaluation was disabled because of an out of memory exception.}

Code & Steps:-

I just simply select the image from the directory and displayed to the WPF image

    private void ImgDisplay_Click(object sender, RoutedEventArgs e)
    {
        image.Source = new BitmapImage(new Uri(filePath));
    }

    private void ImgDistry_Click(object sender, RoutedEventArgs e)
    {
        image.Source = null;
    }

    private void ImgSelect_Click(object sender, RoutedEventArgs e)
    {
        OpenFileDialog openFileDialog1 = new OpenFileDialog();
        openFileDialog1.ShowDialog();
        filePath = openFileDialog1.FileName;
    }

<Window x:Class="WpfApplication4.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" 
    Title="MainWindow" Background="Transparent" MaxHeight="1080" MaxWidth="1920">
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto"></RowDefinition>
        <RowDefinition Height="*"></RowDefinition>
        <RowDefinition Height="Auto"></RowDefinition>
    </Grid.RowDefinitions>
    <Grid Margin="5">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto"></ColumnDefinition>
            <ColumnDefinition Width="Auto"></ColumnDefinition>
            <ColumnDefinition Width="Auto"></ColumnDefinition>
        </Grid.ColumnDefinitions>
        <Button Height="40" Width="120" Background="Green" Name="ImgDisplay" Foreground="White" Content="Display Image" Click="ImgDisplay_Click" />
        <Button Margin="10,0,10,0" Grid.Column="1" Height="40" Width="120" Name="ImgDistry" Content="Distroy Image" Background="Red" Foreground="White" Click="ImgDistry_Click" />
        <Button Grid.Column="2" Height="40" Width="120" x:Name="ImgDistry_Copy" Content="Select Image" Background="Yellow" Foreground="Black" Click="ImgSelect_Click" />
    </Grid>
    <ScrollViewer Grid.Row="1">
        <Image Name="image"/>
    </ScrollViewer>
</Grid>
After select image from the directory

![6](https://user-images.githubusercontent.com/3060341/44206873-d6ff4080-a178-11e8-97b7-1f53f56c1007.png)
![7](https://user-images.githubusercontent.com/3060341/44206874-d6ff4080-a178-11e8-83af-cf1bb1d0f417.png)
![8](https://user-images.githubusercontent.com/3060341/44206875-d797d700-a178-11e8-899b-cafec48707df.png)

After doing 2-3 time same operation select image then destroy.. memory is increasing after each operation

Memory 
High Resolution images that i used you can download from here https://www.dropbox.com/s/fiodfaedwabtkgg/1.png?dl=0 https://www.dropbox.com/s/2bk0qm1clx4bgq1/2.png?dl=0 https://www.dropbox.com/s/6evtsqmqthu60mu/3.png?dl=0 https://www.dropbox.com/s/6p3o36wcires2jn/4.png?dl=0 https://www.dropbox.com/s/k5t1y9apcj4oee4/5.png?dl=0

**Comment by AaronRobinsonMSFT** [comment]
@ankur4747github This appears to be a WPF application which is not presently supported in .NET Core. I recommend using one of the built-in tools in Visual Studio to determine [.NET memory utilization](https://msdn.microsoft.com/en-us/library/dn342825.aspx).
