### ISSUE TITLE
Enable conditional event filtering for LTTng

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#1951]
This will allow for  IsEnabled check for every Event.
Measure if there is any perf degradation if  COMPlus_EnableEventLog is on by default
Measure the Perf Degradation when EventSource is used
       1. See if splitting framework Evenstource Events having their own lttng event will help perf?

**Comment by gkhanna79** [comment]
@brianrob Assigning this to you per our discussions last week.

**Comment by leculver** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/5068.

At least, what we intend to do for this release is fixed.  We will be making further improvements in v.next.
