### ISSUE TITLE
Add regression test for unhandled exceptions in secondary thread

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#1952]
There was an issue #1922 that was fixed,  but we need to add regression test for that.

**Comment by gkhanna79** [comment]
I presume you are driving this for 2.0 as well @janvorli ?

**Comment by janvorli** [comment]
I was thinking about it multiple times in the past and I think we should just drop this. I cannot see a reasonable way to write a regression test for this, since the issue was caused by incorrect processing of multiple native TRY / CATCH blocks embedded in each other in single frame in a special case that I don't know how to induce by a managed app, since it stemmed from an exception thrown from the native code.
