### ISSUE TITLE
Could not load file or assembly 'dnx.clr.managed' or one of its dependencies clr 1.0.0-rc1-16048

### ISSUE THREAD

**Issue by hugoarias** [dotnet/coreclr#1955]
Hey,
I'm trying to run web app with the latest clr package;

    {
        "projects": [ "src", "test" ],
        "sdk": {
            "version": "1.0.0-rc1-16048",
            "runtime": "coreclr",
            "architecture": "x86"
        }
    }

    Active Version           Runtime Architecture Location
    ------ -------           ------- ------------ --------
       1.0.0-beta4       clr     x64          C:\Users\user\.dnx\runtimes
       1.0.0-beta4       clr     x86          C:\Users\user\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\user\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\user\.dnx\runtimes
       1.0.0-beta5       clr     x64          C:\Users\user\.dnx\runtimes
       1.0.0-beta5       clr     x86          C:\Users\user\.dnx\runtimes
       1.0.0-beta5       coreclr x64          C:\Users\user\.dnx\runtimes
       1.0.0-beta5       coreclr x86          C:\Users\user\.dnx\runtimes
       1.0.0-beta5-12103 clr     x86          C:\Users\user\.dnx\runtimes
       1.0.0-beta6       clr     x86          C:\Users\user\.dnx\runtimes
       1.0.0-beta6-12250 clr     x86          C:\Users\user\.dnx\runtimes
       1.0.0-beta7       clr     x86          C:\Users\user\.dnx\runtimes
    *  1.0.0-rc1-16048   clr     x86          C:\Users\user\.dnx\runtimes
       1.0.0-rc1-16048   coreclr x64          C:\Users\user\.dnx\runtimes
       1.0.0-rc1-16048   coreclr x86          C:\Users\user\.dnx\runtimes

I did the 'dnu publish' and then try debugging the code with visual studio.

However I'm getting the error I mentioned

*Could not load file or assembly 'dnx.clr.managed' or one of its dependencies. The system cannot find the file specified.*

looking for the file in the directory:
    c:\Users\user\\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-16048\bin\

It actually doesn't exist... So is there any missing configuration to make it work? Or what can I do since I want to run it in the rc1 version.

**Comment by davidfowl** [comment]
If you updated from beta7 and are using IIS please read this blog post  http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx. You nee to make *ALOT* of changes to make older projects work.
