### ISSUE TITLE
[Ubuntu 16.04] PR #19525 might have introduced a regression on the CQ benchmarks

### ISSUE THREAD

**Issue by jorive** [dotnet/coreclr#19568]
The range of changes that are captured for the run that started showing the regression are these: https://github.com/dotnet/coreclr/compare/a81d9103d23f714a0bd3efb900321b0b9f383311...dotnet:0fc981abe7b9ca6898f157bc247edad265d4088b

This is an example of a single regression of ~24%
![capture](https://user-images.githubusercontent.com/12551699/44367867-d7a01b80-a485-11e8-90ef-76fa39ade628.PNG)

/cc @AndyAyersMS @noahfalk @kouvel

**Comment by AndyAyersMS** [comment]
Things back to normal now...

![image](https://user-images.githubusercontent.com/10121823/44444404-81b89a00-a591-11e8-9bbd-62e4a5fd8591.png)

Though note the regression is a hallmark of a certain class of programs that will regress with our current tiering: programs where perf-sensitive code is in a method that isn't called very often (aka "cold method / hot loop(s)").
