### ISSUE TITLE
String.IndexOf has unexplained poor performance for different inputs

### ISSUE THREAD

**Issue by djluck** [dotnet/coreclr#19562]
## Summary
I have found a where `String.IndexOf` runs thousands of times slower for different inputs. Affects .NET framework and .NET core on windows (may well be windows specific).

Given this benchmark:
```
void Main()
{	
	var config = DefaultConfig.Instance
		.With(new Job("X64-Clr-RyuJit", BenchmarkDotNet.Jobs.RunMode.Short, EnvMode.Clr)
		{
			Accuracy = { RemoveOutliers = false },
			Env = { Runtime = Runtime.Clr, Platform = Platform.X64, Jit = Jit.RyuJit },
		});

	BenchmarkRunner
		.Run<StringBenchmark>(config);
}

public class StringBenchmark
{
	private string toSearch;
	
	public StringBenchmark()
	{
		// Reads in a ~4MB file that contains non-ascii characters
		toSearch = File.ReadAllText(@"C:\users\jameslu\desktop\large.htm");
	}
	
	[Benchmark]
	public int IndexOfStartComment()
	{
		return toSearch.IndexOf("<!-- ", StringComparison.CurrentCultureIgnoreCase);
	}

	[Benchmark(Baseline= true)]
	public int IndexOfStartStyle()
	{
		return toSearch.IndexOf("<style ", StringComparison.CurrentCultureIgnoreCase);
	}
}
```
You get these results:
```

              Method |           Mean |          Error |        StdDev |     Scaled | ScaledSD |
-------------------- |---------------:|---------------:|--------------:|-----------:|---------:|
 IndexOfStartComment | 552,852.051 us | 100,436.282 us | 5,674.8362 us | 243,196.76 | 6,592.44 |
   IndexOfStartStyle |       2.275 us |       1.292 us |     0.0730 us |       1.00 |     0.00 |
```

You'd expect `IndexOfStartComment` to run slightly faster, as it has less characters to match. However `IndexOfStartStyle` runs ~243,000 times slower.

This is a perfview trace for `IndexOfStartStyle`:
![image](https://user-images.githubusercontent.com/1540536/44338043-0cc95f80-a4c0-11e8-8e6d-3a4109831a36.png)

And this is a perfview trace for `IndexOfStartComment`:
![image](https://user-images.githubusercontent.com/1540536/44338065-24084d00-a4c0-11e8-9a9d-d2986fa323a5.png)

`FindNLSStringEx` seems to be responsible somehow but I haven't been able to find much about _why_ these two different arguments would yield such a vast difference in execution time.

**Comment by benaadams** [comment]
Where do `<!-- ` and `<style ` occur in the file?

What the results if you use `StringComparison.Ordinal`

**Comment by benaadams** [comment]
Where do `<!-- ` and `<style ` occur in the file?

e.g. what is the return value of the two `IndexOf`s

**Comment by djluck** [comment]
Oh dear. I thought I had found something worth reporting, instead I overlooked the position of strings being searched.

The indexes are `1000` and `-1`.

I think it might be worth closing this immediately and if possible, deleting this to save my embarrassment..
