### ISSUE TITLE
Need some way for the jit to reliably identify methods across runs

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#1957]
The `methodHash` provided to the jit via the jit interface is supposed to provide this, but it's not unique. Neither are names or tokens.

Ideally this method ID would be independent of jit behavior (eg LLILC and RyuJit would see the same IDs even if they make different demands via the jit interface). 

I'd be willing to settle for something that works only in crossgen to start with.

Without something like this it's going to be challenging to correlate inlining data across runs and implement things like log replay.

**Comment by sergiy-k** [comment]
@gkhanna79, could you please route this issue? Is this something we will do for v1 rtm?

**Comment by AndyAyersMS** [comment]
It's something I would still really love to see.... right now I'm ignoring methods that have colliding hash values when I am correlating inlining data from one run to another.

**Comment by gkhanna79** [comment]
We can try to look into this dependent upon other issues we must go through for RTM.

**Comment by drbo** [comment]
What about using a Blake2b (faster) or SHA2 hash?

**Comment by AndyAyersMS** [comment]
I'd be willing to help work up a fix....

**Comment by gkhanna79** [comment]
@AndyAyersMS In that case, would you like me to assign the issue over to you?

**Comment by gkhanna79** [comment]
@AndyAyersMS I have assigned this to you since you wanted to take a stab at this for RTM.

**Comment by AndyAyersMS** [comment]
Still would be nice to have, but not urgent at this point.

**Comment by briansull** [comment]
This is fixed with #27147

**Comment by briansull** [comment]
Fixed
