### ISSUE TITLE
Enable eventpipe without restart dotnet process

### ISSUE THREAD

**Issue by ins4n333** [dotnet/coreclr#19597]
Is it any way to enable eventpipe diagnostics without restart dotnet process?
Performance problems with   my application do not start immediately, but in around several days after launch.

Now for starting EventPipe diagnostics I need to enter next commands
export COMPlus_EnableEventPipe=1
export COMPlus_EventPipeConfig=Microsoft-DotNETCore-SampleProfiler:1:5

and restart dotnet process.

dotnet --info
Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0
.NET Core SDKs installed:
  No SDKs were found.
.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jkotas** [comment]
cc @brianrob

**Comment by ins4n333** [comment]
@brianrob Thank you! It would be cool feature. In my case I need enable EventPipe only on several seconds. 

Also, please tell me whether there is a way to limit  the circular buffer size and turn off text events (which can be viewed in perfview) leaving only thread traces?

**Comment by brianrob** [comment]
@ins4n333, there isn't a COMPLUS variable for setting the circular buffer size, through it would be trivial to add one (if you're interested in submitting a PR for this, that would be a great).

I'm not sure I understand your second question.  What do you mean by text events and thread traces?

**Comment by tommcdon** [comment]
We implemented a mechanism to enable/disable file-based eventpipe in 2.2
In 3.0 the pipe can be enabled/disabled through IPC (see https://github.com/dotnet/coreclr/pull/23106)
