### ISSUE TITLE
R2RDump - Invalid Machine type in the COFF header for Linux images

### ISSUE THREAD

**Issue by acmyu** [dotnet/coreclr#19592]
Right now, for ReadyToRun images created on Linux, R2RDump isn't able to read the Machine type (Amd64, arm, etc.). When I use dumpbin /HEADERS for Linux native images, the machine type is also unknown

It tries to read the machine type from the CoffHeader using the PEReader, but gets a large number instead of a valid machine type. The R2RReader currently writes a warning and sets the machine to Amd64

**Comment by jkotas** [comment]
The machine type is `xored` with OS-specific constant on non-Windows OSes. Look for `IMAGE_FILE_MACHINE_NATIVE_OS_OVERRIDE`.

**Comment by acmyu** [comment]
This should solve the issue: https://github.com/dotnet/coreclr/pull/19638
R2RDump could now get the machine code for non-Windows images
