### ISSUE TITLE
Implement GetFileSizeEx in PAL

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/coreclr#196]
Currently we have an empty stub in coreclr/src/pal/src/file/file.cpp.
We need to provide proper implementation for Linux and Mac and add a test under coreclr/src/pal/tests/palsuite.

**Comment by kangaroo** [comment]
It seems that CorUnix::InternalGetFileSize already does the correct thing here on platforms with SIZEOF_OFF_T > 4, it just needs to be wired up and tested.

**Comment by benpye** [comment]
I believe this should now be closed as #244 implements this.
