### ISSUE TITLE
taghelpers not working

### ISSUE THREAD

**Issue by dejandjenic** [dotnet/coreclr#19600]
taghelpers not working correctly if project is published with lower case format of file

e.g.
project exists and its name is MYPROJ.csproj at c:\test

if published with command

dotnet publish "c:\test\myproj.csproj" -o "c:\testpub\"

dll will be created and tag helpers will not work. Generated Namespace is the same in both cases but [assembly: AssemblyTitle("myproj")] is taken from input parametar instead from csproj file.

**Comment by jkotas** [comment]
This issue was moved to aspnet/Mvc#8308
