### ISSUE TITLE
Ensure VEX encoded instrcutions with reserved VEX.vvvv bits have them always set to 1111

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#19625]
Implementation of `AVX2.Permute4x64` #19580 required a change to VEX encoding code that ensured reserved `VEX.vvvv` bits always are set to 1111 otherwise instruction would raise #UD exception.

It turns out that there is large group of VEX and EVEX encoded implemented instructions which require setting `VEX.vvvv` bits to 1111.

Working on a fix.

cc @CarolEidt @fiigii @tannergooding

**Comment by tannergooding** [comment]
I'm not sure why a fix is needed (or where it would be needed). As you mentioned, there is a large group of instructions that require setting VEX.vvv bits to 1111b. Many of these have been implemented and in use for some time (both as HWIntrinsics, and even before HWIntrinsic support came online as regular instructions and SIMD support).

**Comment by fiigii** [comment]
I think the reason is that you put the instructions in the DstDstSrc table, but them should not be there.

**Comment by 4creators** [comment]
Closing as problems were clarified and solved
