### ISSUE TITLE
arm Ubuntu machines not processing jobs correctly

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19648]
Looks like all arm32 Ubuntu jobs are failing with something like:
```
21:06:32  > git rev-list 656c77eeacf722e97a06e56d8d34b9c0cc6e746c # timeout=10
21:06:33 
Unable to access upstream artifacts area /jenkins/jobs/dotnet_coreclr/jobs/master/jobs/x86_checked_windows_nt_innerloop_bld_prtest/builds/4648/archive. Does source project archive artifacts?
21:06:33 ERROR: Failed to copy artifacts from dotnet_coreclr/master/x86_checked_windows_nt_innerloop_bld_prtest with filter: **
21:06:33 [xUnit] [INFO] - Starting to record.
```
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_tst_prtest/3721/consoleFull

root job: https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_flow_prtest/

@dotnet/dnceng @mmitche @jashook @RussKeldorph @MattGal

**Comment by BruceForstall** [comment]
> With 16 successful runs of that CI since it may not be worth investigating.

yep. Thanks for checking.

**Comment by MattGal** [comment]
(@mmitche : I'd still like to know if you did anything to unblock this for my own learning!)

**Comment by mmitche** [comment]
Didn't change anything.  Let me take a look.  That looks like a scary message.
