### ISSUE TITLE
P/Invoke custom marshaler sometimes fails type cast

### ISSUE THREAD

**Issue by AArnott** [dotnet/coreclr#19654]
I'm trying to track down why [my upgrade](https://github.com/AArnott/Nerdbank.GitVersioning/pull/210) of libgit2sharp to 0.25.2 led to nerdbank.gitversioning to fail (reliably) on a seemingly random set of projects across multiple repos.

In [the failure](https://github.com/AArnott/Nerdbank.GitVersioning/issues/215), [a type check](https://github.com/libgit2/libgit2sharp/blob/5199c83d37f7baf5a775eacaffd66322b1d90ef1/LibGit2Sharp/Core/FilePathMarshaler.cs#L67) fails after passing through [a very clearly type constraining method](https://github.com/libgit2/libgit2sharp/blob/5199c83d37f7baf5a775eacaffd66322b1d90ef1/LibGit2Sharp/Core/NativeMethods.cs#L1395-L1398). Considering that perhaps it's a matter of assembly double-loading, I checked. The managed debugger reports the assembly is loaded once, and that the AssemblyLoadContext is the same at both points of the callstack leading up to the failure. 

This repros only on .NET Core (2.1), and does so on Windows and Linux (I didn't test Mac). This same code works fine within MSBuild running on the .NET Framework.

[The repro](https://github.com/AArnott/Nerdbank.GitVersioning/issues/215#issuecomment-415785686) is super reliable and relatively simple. @rainersigwald also has [a great repro](https://github.com/AArnott/Nerdbank.GitVersioning/issues/215#issuecomment-415774717).

**Comment by luqunl** [comment]
>> Could this be addressed by your work with custom marshaling?

@AaronRobinsonMSFT , it is similar issue. I will take a look.

**Comment by AArnott** [comment]
Continuing the investigation in https://github.com/AArnott/Nerdbank.GitVersioning/issues/217#issuecomment-415989664 (since my workaround utterly failed), I found that the p/invoke custom marshaler problem surfaces after the *second* custom `AssemblyLoadContext` is created and p/invokes come from that one.

**Comment by jkoritzinsky** [comment]
Fixed by #21606
