### ISSUE TITLE
Unify the Interop xplatform.h file with the common coreclr test platformdefines.h 

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/coreclr#19657]
@luqunl 

See #19576

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Is there anything else we should do here?

**Comment by jkoritzinsky** [comment]
Unless we want to merge the two headers (which I would be ok with doing) I think we're all good here.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky I think merging them is a good idea if possible. Any features that have relevance only for Interop should be in the local header - so it should be very small.
