### ISSUE TITLE
Asp.Net MVC application will not run on IIS

### ISSUE THREAD

**Issue by ZackTech** [dotnet/coreclr#19669]
I have a Asp.Net MVC application that will not run in IIS, I just get HTTP 500 Server error. I don't get any log files suggesting what the error is, but the event viewer says:
Application 'MACHINE/WEBROOT/APPHOST/CRMWEBSITE.COM' started process '16904' successfully and is listening on port '13854'.

If I open a command prompt and cd to the Web Site folder and enter the command:
dotnet .\Crm.WebSite.dll 
Then go into the browser and use the URL http://localhost:5000 The Web Site starts up and runs normally.

How do I diagnose the problem and fix it?

**Comment by benaadams** [comment]
Might be a path issue? Try changing webconfig to specify the `dotnet` path, e.g.

Change
```
<aspNetCore processPath="dotnet"
```
To
```
<aspNetCore processPath="C:\Program Files\dotnet\dotnet"
```
Though here are the trouble shooting https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-iis-errors-reference?view=aspnetcore-2.1

**Comment by jkotas** [comment]
This issue was moved to aspnet/AspNetCoreModule#320
