### ISSUE TITLE
PInvoke function that returns a struct

### ISSUE THREAD

**Issue by nxrighthere** [dotnet/coreclr#19676]
One of my customers encountered a problem today that doesn't appear with .NET Framework/Mono.

For some reason in this function (ENet.cs line 747):
```csharp
[DllImport(nativeLibrary, CallingConvention = CallingConvention.Cdecl)]
internal static extern Address enet_peer_get_address(IntPtr peer);
```
marshalling is not possible of an `ENetAddress` struct (ENet.cs line 64) which internally contained in `Address` (ENet.cs line 90):
```csharp
[StructLayout(LayoutKind.Sequential)]
public struct ENetAddress {
	[MarshalAs(UnmanagedType.ByValArray, SizeConst = 16)]
	public byte[] host;
	public ushort port;
}
```
look at `Peer.Address` (ENet.cs line 515).

The runtime throws this exception:
> Unhandled Exception: System.Runtime.InteropServices.MarshalDirectiveException: Method's type signature is not PInvoke compatible.
   at ENet.Native.enet_peer_get_address(IntPtr peer)
   at ENet.Peer.get_Address() in E:\TestENetServer\ENet.cs:line 517
   at TestENetServer.Program.Main(String[] args) in E:\TestENetServer\Program.cs:line 25

Here's an example of projects - [ENetCSharpTest.zip](https://github.com/dotnet/coreclr/files/2321643/ENetCSharpTest.zip)
Simple run the server and then the client, and you will catch an exception.

Here's repository with a complete source code including the native library - https://github.com/nxrighthere/ENet-CSharp

**Comment by nxrighthere** [comment]
As a workaround, I [changed](https://github.com/nxrighthere/ENet-CSharp/commit/d7615a3c200db95ad52ac37bfb6bc6908807c5ae) the functions to obtain an address directly from the unmanaged side, instead of marshalling a struct.

**Comment by jeffschwMSFT** [comment]
cc @AaronRobinsonMSFT (wrt marshalling test coverage)

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Didn't you add some testing for this scenario?

**Comment by jkoritzinsky** [comment]
I thought I did. I'll go check.

**Comment by jkoritzinsky** [comment]
Fixed by #21470

**Comment by ceztko** [comment]
Sorry for the late reply: I just add as an information for other people stumbling in similar cases that the change in #21470 is only available in recent .NET core runtimes (unfortunately the improvement has **not** been backported in .NET framework so far) and it also allows marshaling of structures like the following as return values:

```
[StructLayout(LayoutKind.Sequential)]
struct PString
{
    [MarshalAs(UnmanagedType.LPWStr, SizeParamIndex = 1)]
    public string String;
    public int Lenght;
}
```

**Comment by AaronRobinsonMSFT** [comment]
>unfortunately the improvement has not been backported in .NET framework so far

I want to set expectations here with respect to the above. There are no plans (now or in the future) to port any new interop work to .NET Framework.

**Comment by ceztko** [comment]
> I want to set expectations here with respect to the above. There are no plans (now
> or in the future) to port any new interop work to .NET Framework.

Perfectly understandable to me. Thank you very much for the clarification.
