### ISSUE TITLE
Optimize generic methods performing type checks on their type arguments when reference types known ahead are subsituted

### ISSUE THREAD

**Issue by voinokin** [dotnet/coreclr#19671]
Use case:
There is method (or methods) which are supposed to have slightly different machine code generated according to the features requested with artificially supplied type arguments (see repro code below). This works when the type arguments are substituted with value types (method `TestOnOff()`), but not with sealed/static classes (method `TestYesNo()`).

The disasm displays that: 
- Method having type args substituted with VTs gets its body *specialized* for each distinct set of type args, and the type match check on result of `typeof(...)` is folded to constants
- Method having type args substituted with RTs does not have body specialized (the same entry point is used for both invocations), instead each type match check on result of `typeof(...)` provides machine code, although *ALL* type args have *sealed* RTs and are known at call site. This prohibits further optimizations which are observed the case with VTs.

```
abstract class YesNo { protected YesNo() { } }
sealed class Yes : YesNo { Yes() { } }
sealed class No : YesNo { No() { } }

interface IOnOff { }
struct On : IOnOff { }
struct Off : IOnOff { }

[MethodImpl(MethodImplOptions.NoInlining)]
static void TestYesNo<TSwitch1, TSwitch2>()
    where TSwitch1 : YesNo
    where TSwitch2 : YesNo
{
    bool switch1IsOn = (typeof(TSwitch1) == typeof(Yes));
    bool switch2IsOn = (typeof(TSwitch2) == typeof(Yes));

    Console.WriteLine("TestYesNo(): SW1={0}, SW2={1}", switch1IsOn, switch2IsOn);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void TestOnOff<TSwitch1, TSwitch2>()
    where TSwitch1 : struct, IOnOff
    where TSwitch2 : struct, IOnOff
{
    bool switch1IsOn = (typeof(TSwitch1) == typeof(On));
    bool switch2IsOn = (typeof(TSwitch2) == typeof(On));

    Console.WriteLine("TestOnOff(): SW1={0}, SW2={1}", switch1IsOn, switch2IsOn);
}

static void Main(string[] args)
{
    TestYesNo<Yes, No>();
    TestYesNo<No, Yes>();

    TestOnOff<On, Off>();
    TestOnOff<Off, On>();
}
```

**Comment by benaadams** [comment]
It will do it if they inline; otherwise all reference types will use the shared generic code path

**Comment by AndyAyersMS** [comment]
As Ben says, we can only specialize method instantiations over ref types once they are inlined into a non-generic or not-shared generic method. Changing this is likely to be challenging as sharing is one of the main things that keeps generic inspired code growth tolerable.

And IIRC even when we inline, we don't always map the shared placeholder `__Canon` types back to the corresponding instantiation types. So we may not get as much benefit from inlining as we could.

**Comment by AndyAyersMS** [comment]
#16266 proposes allowing generic specialization over ref types. So perhaps we can close this as a dup?

**Comment by voinokin** [comment]
In my case it's possible to supply other type arguments - not only feature impl. switches.
Current issue can be considered dup if #16266 will cover the case I just described.

Example follows, where `TIterator` / `TIteratorState1` / `TIteratorState2` are unrelated to `TSortRecordReversedPlacement` and `TTryStoreNonTemporal`:
```
[MethodImpl(MethodImplOptions.NoInlining)]
static void ConsolidateRunData<
    TIterator, TIteratorState1, TIteratorState2,
    TSortRecordReversedPlacement, TTryStoreNonTemporal>(

    TWord* pRunItemsDataBuffer,
    RunItemDataWordsCopyTasksX4* pCopyTasksX4BufferAligned, ulong recordsCount,
    in TIterator iteratorInit, ulong dataWordsTotal)

    where TIterator : struct, IRunDataIterator<TIteratorState1, TIteratorState2, TWord>
    where TIteratorState1 : struct
    where TIteratorState2 : struct

    where TSortRecordReversedPlacement : struct, IImplSwitch
    where TTryStoreNonTemporal : struct, IImplSwitch
{
    ....
}
```

**Comment by RussKeldorph** [comment]
@voinokin Feel free to add/clarify your request to #16266.  We can address whether this is a dup if/when that is ever implemented.
