### ISSUE TITLE
CoreCLR failed when build with permissive- + MSVC on windows.

### ISSUE THREAD

**Issue by QuellaZhang** [dotnet/coreclr#19685]
CoreCLR failed with  error C4596: 'AppDomainIsRudeUnload': illegal qualified name in member declaration  when build with permissive- on Windows, I use latest source 5d2ae2f on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.
 
**You can repro this issue as the steps below:**

1. git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2. open a VS 2017 x86 command prompt and browse to D:\CoreCLR
3. set _CL_=/permissive- /wd5043 /wd4644
4. build x86 release -- /clp:ShowCommandLine

 
**Error info:**
d:\coreclr\src\src\gc\env\gcenv.ee.h(94,55): error C4596: 'AppDomainIsRudeUnload': illegal qualified name in member declaration 
d:\coreclr\src\src\gc\env\gcenv.ee.h(94,55): error C4596:  static bool GCToEEInterface::AppDomainIsRudeUnload(void *appDomain);

**Comment by jkotas** [comment]
Will be fixed by #19681 

cc @davmason

**Comment by davmason** [comment]
This slipped through on a recent commit. I actually noticed it and thought I had fixed it, I either reintroduced when I backed out some changes or just forgot to fix it. It will be fixed soon though.

**Comment by QuellaZhang** [comment]
Thanks! @jkotas @davmason

**Comment by QuellaZhang** [comment]
@jkotas @davmason Thanks! This issue has gone, CoreCLR is clean now.
