### ISSUE TITLE
Automate CoreCLR's CoreFX CI Test Infrastructure

### ISSUE THREAD

**Issue by josalem** [dotnet/coreclr#19690]
# CoreFX Tests in CoreCLR CI

## Current State
A suite of CoreFX tests are executed on top of CI builds of CoreCLR during PRs.  Currently, these tests are manually built and uploaded to an Azure Blob Storage container and downloaded during the CI pipeline.  The cadence of building and uploading the binaries is completely manual with almost no visibility as to what commit from dotnet/corefx was used to build the tests.  While this works, it is inconvenient for maintenance, and unfriendly for developers who may want to pull down the same test binaries that are running in the CI for their PR.

## Goals
* Automate the cataloging (upload and versioning) of CoreFX test binaries.
* Simplify the retrieval of a specific version of the CoreFX test binaries.
* Hook into the automation that already updates the CoreFX version in [coreclr/dependencies.props](https://github.com/dotnet/coreclr/blob/master/dependencies.props) via [maestro-bot](https://github.com/dotnet/versions).

This issue is for unifying discussions, as this may require changes in dotnet/coreclr and dotnet/corefx.

CC - @A-And @adityamandaleeka 

[WIP]

**Comment by echesakovMSFT** [comment]
@BruceForstall

**Comment by RussKeldorph** [comment]
Assuming fixed by #24259.  Remaining work tracked in #24501.
