### ISSUE TITLE
[Windows|x86|x64] Incorrect comparison of short

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#19705]
Example code:

```
C#

void TestEchoShort()
{
   short ret = echo_short(8);
   Debug.Assert(ret == 8); // Fails
}


C:

short echo_short(_int8 arg, ...)
{
   return arg;
}
```

/cc @BruceForstall

**Comment by mikedn** [comment]
> Value is returned in $al

Presumably you mean `$ax`?

> we copy $eax.

Normally the JIT should insert a cast after the call to clean up the upper bits.

**Comment by BruceForstall** [comment]
cc @erozenfeld

**Comment by jashook** [comment]
@mikedn correct this also is not vararg specific and can be reproed on x64.

**Comment by jashook** [comment]
I also believe this can be reproed on unix; however, I believe the upper bits need to be forced to have junk.

A thought would be:

```
short echo_short(_int8 arg, ...)
{
   __int64 value = 2147483647;
   return reinterperate_cast<_int8>(arg);
}
```

**Comment by mikedn** [comment]
Can't seem to reproduce. Such a PInvoke call passes through a stub and the code generated for that includes the expected cast, even 2 of them:
```asm
G_M1904_IG03:
       FFD0                 call     rax

G_M1904_IG04:
       C6460C01             mov      byte  ptr [rsi+12], 1
       833D19A4FF5F00       cmp      dword ptr [(reloc)], 0
       7406                 je       SHORT G_M1904_IG05
       FF152D1FFF5F         call     [CORINFO_HELP_STOP_FOR_GC]

G_M1904_IG05:
       480FBFC0             movsx    rax, ax

G_M1904_IG06:
       480FBFC0             movsx    rax, ax
```

**Comment by jashook** [comment]
I have confirmed that this will fail on x64 and x86, it repros for me only with a non-debug build.

**Comment by jashook** [comment]
It was found with https://github.com/dotnet/coreclr/pull/17707. https://github.com/dotnet/coreclr/pull/17707/files#diff-891cca29262cd9b7b6c55a2ca049196bR3446 will fail.

**Comment by mikedn** [comment]
It looks to me that the native test code is wrong:

```C++
DLLEXPORT __int8 _cdecl echo_short(__int8 arg, ...)
{
    return arg;
}
```

**Comment by erozenfeld** [comment]
The code for the native function is:
```
echo_short:
  0000000180001580: 48 89 54 24 10     mov         qword ptr [rsp+10h],rdx
  0000000180001585: 8A C1              mov         al,cl
  0000000180001587: 4C 89 44 24 18     mov         qword ptr [rsp+18h],r8
  000000018000158C: 4C 89 4C 24 20     mov         qword ptr [rsp+20h],r9
  0000000180001591: C3                 ret
```
so the sign extension in the stub is insufficient. al should be sign extended, bot eax.

**Comment by erozenfeld** [comment]
This is what VC compiler generates for a native caller:
```
int main()
{
    printf("%d\n", echo_short(2));
}
```
```
main:
00007FF6A0C61090  sub         rsp,28h  
00007FF6A0C61094  mov         ecx,2  
00007FF6A0C61099  call        echo_short (07FF6A0C61070h)  
00007FF6A0C6109E  movsx       edx,al  
00007FF6A0C610A1  lea         rcx,[string "%d\n" (07FF6A0C62200h)]  
00007FF6A0C610A8  call        printf (07FF6A0C61010h)  
00007FF6A0C610AD  xor         eax,eax  
00007FF6A0C610AF  add         rsp,28h  
00007FF6A0C610B3  ret
```
Note the `al ` sign extension after the call to echo_short.

**Comment by erozenfeld** [comment]
I'm not sure if this behavior is documented anywhere but we should probably match it in the stub.

**Comment by erozenfeld** [comment]
Actually, it appears the problem is that the managed declaration
```
        [DllImport("varargnative", CallingConvention = CallingConvention.Cdecl)]
        extern static short echo_short(short arg, __arglist);
```
doesn't match the native one
```
DLLEXPORT __int8 _cdecl echo_short(__int8 arg, ...)
{
    return arg;
}
```

**Comment by erozenfeld** [comment]
I'll fix the test and make sure things work correctly both for `byte` and `short` cases with matching managed/native declarations.
