### ISSUE TITLE
Write web services with Typescript, and using coreclr to run them as native code.

### ISSUE THREAD

**Issue by michaeljota** [dotnet/coreclr#19711]
This is not actually my idea, but certainly is an interesting one.

Here is the original blog post: 

> https://dev.to/zohaibility/its-time-for-typescript-native-2dg7

Deno project: 

> [Deno](https://github.com/denoland/deno)

---

This would allow us as developers to write web services and server side applications in Typescript, but instead of being compiled down and run in Node, the whole idea would be to be able to actually interpret that code as is, allowing thinks as runtime errors for types. 

I know that Typescript and C# looks a loot alike, for obvious reasons, but being Typescript a super set of Javascript, and the latter a functional language, this could actually be something really great for the .Net Core community.

**Comment by RussKeldorph** [comment]
This repo doesn't seem to be an appropriate place to hold this discussion.  Perhaps https://github.com/Microsoft/TypeScript?  Perhaps somewhere specific to we services?
