### ISSUE TITLE
Add support for MarshalAs(UnmanagedType.BSTR) on UNIX systems

### ISSUE THREAD

**Issue by odhanson** [dotnet/coreclr#19735]
Although Marshal.StringToBStr et al. works fine on Mac. The following code
```
delegate void Callback([MarshalAs(UnmanagedType.BStr)]string s);

        [DllImport("libTestDynLib.dylib")]
        static extern void MyTest([MarshalAs(UnmanagedType.BStr)]string s, Callback c);

        static void Main(string[] args)
        {
            MyTest("This is a test", s =>
            {
                Console.WriteLine(s);
            });
        }
```
Is failing on Mac:
System.Runtime.InteropServices.MarshalDirectiveException: "Cannot marshal 'parameter #1': Invalid managed/unmanaged type combination (String parameters and return types must be paired with LPStr, LPWStr, or LPTStr)."
  at TestBSTR.Program.MyTest(String s, Callback c)\n   at TestBSTR.Program.Main(String[] args) in /Users/odhanson/Projects/MyGuidTest/TestBSTR/Program.cs:15

Seems like (for looking at the code) this has only been implemented for windows (as part of COM support).

We are currently in the process of porting a FX application to Core, that has extensive interop with existing native libraries (that are cross platform). The BSTR is used extensively and we would definitely need support for this type of marshaling.

**Comment by odhanson** [comment]
@jkotas , @danmosemsft , @richlander

**Comment by luqunl** [comment]
@odhanson, do you also need Ansi BSTR support?

**Comment by odhanson** [comment]
@luqunl we only use UnmanagedType.BSTR in our project

**Comment by AaronRobinsonMSFT** [comment]
@odhanson What @luqunl is asking is, do you use ANSI characters (8-bit) in your `BSTR`s or do you use `wchar_t` (16-bit/32-bit) characters only?

**Comment by AaronRobinsonMSFT** [comment]
Doh. I completely forgot about the ‘AnsiBStr’ enum value, you are absolutely right. Sorry about the noise. 🙂

**Comment by odhanson** [comment]
@luqunl any estimate to when this might be incorporated into 2.1 ? We hade a workaround using our own  custom marshaller for BSTR but now we have found out that the custom marshaller doesn't work for structures that contain BSTR strings. So having this change incorporated will solve us a lot of time

**Comment by luqunl** [comment]
@odhanson , the product part is done and the testing part should be finished in one or two weeks

**Comment by danmosemsft** [comment]
Reactivating for 2.2 port. (When buddy tested)

**Comment by danmosemsft** [comment]
Was ported
