### ISSUE TITLE
Sse41.Extract has "interesting" codegen

### ISSUE THREAD

**Issue by Porges** [dotnet/coreclr#19732]
I was just poking some benchmarks and noticed this.

Setup: Runtime=.NET Core 2.1.3 (CoreCLR 4.6.26725.06, CoreFX 4.6.26725.05), 64bit RyuJIT

Where I would expect Sse41.Extract to turn into a simple `vpextrb`, I'm seeing it assemble to a `call` to the following...

```asm
System.Runtime.Intrinsics.X86.Sse41.Extract(System.Runtime.Intrinsics.Vector128`1, Byte)	

vmovupd xmm0,xmmword ptr [rcx]
movzx   eax,dl
lea     rdx,[00007ff7`abc4f8e0]
mov     edx,dword ptr [rdx+rax*4]
lea     rcx,[00007ff7`abc4edf0]
add     rdx,rcx
jmp     rdx
vpextrb eax,xmm0,0
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,1
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,2
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,3
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,4
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,5
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,6
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,7
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,8
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,9
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,0Ah
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,0Bh
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,0Ch
jmp     00007ff7`abc4f8de
vpextrb eax,xmm0,0Dh
jmp     00007ff7`abc4f8de
```

This continues on up to `FFh` 🤣

**Comment by mikedn** [comment]
Judging from the code you linked to in the other issue you're calling Extract with a non-constant offset. `vpextrb` does not support that, the offset has to be constant.

**Comment by Porges** [comment]
Thanks! That is unfortunate.

**Comment by mikedn** [comment]
> Thanks! That is unfortunate.

See if you can replace it with a SSE3/AVX shuffle. It's probably not going to be as fast as a hypothetical variable offset `pextrb` but it would likely be faster than the switch table approach used as fallback by the JIT.

**Comment by Porges** [comment]
I think in my case I can arrange things so I can use a constant value here. Thanks for the advice ☺️

**Comment by 4creators** [comment]
> Judging from the code you linked to in the other issue you're calling Extract with a non-constant offset. vpextrb does not support that, the offset has to be constant.

@mikedn @Porges 

Actually, .NET Core intrinsic "support" using non const parameters but to enable  their handling jit generates code which converts non const parameter into jump table what allows to emit `pextrb` with immediate const. This is `by design` and is very inefficient in comparison to calling intrinsic with const parameter.

**Comment by tannergooding** [comment]
I believe he was indicating that `vpextrb` (the instruction) doesn't support non-constant parameters.
We (CoreCLR) support non-constant parameters for the matching intrinsic by emitting a jump table.

I am working on an analyzer that will try to flag cases where the user is passing in a non-constant parameter and notify them of the potential perf hit.
