### ISSUE TITLE
Assertion in `MethodTable::AssignClassifiedEightByteTypes`

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#1973]
The SysV classifier asserts when classifying `Nested4` below:

`
unsafe struct InlineArray5
{
	public fixed byte Array[9];
}

struct Nested4
{
	public InlineArray5 Field1;
	public ushort Field2;
}
`

The assertion is:
```
Assert failure(PID 7400 [0x00001ce8], Thread: 7400 [0x1ce8]): helperPtr->fieldLayoutSizes[ordinal] <= SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES
    File: /home/pgavlin/dev/coreclr/src/vm/methodtable.cpp Line: 2984
    Image: /home/pgavlin/dev/coreclr/llilc/corerun

**** MessageBox invoked, title 'corerun - Assert Failure (PID 7400, Thread 7400/0x1ce8)' ****
  helperPtr->fieldLayoutSizes[ordinal] <= SYSTEMV_EIGHT_BYTE_SIZE_IN_BYTES

/home/pgavlin/dev/coreclr/src/vm/methodtable.cpp, Line: 2984

Abort - Kill program
Retry - Debug
Ignore - Keep running
```

**Comment by AndyAyersMS** [comment]
@pgavlin How are you finding these cases? 

Are we doing any sort of systematic ABI testing? If not, we really should be.

**Comment by pgavlin** [comment]
I am finding these through ad-hoc testing. The tests in #1972 are an example.

I agree that we should find some way to do systematic ABI testing; any suggestions are welcome.

**Comment by AndyAyersMS** [comment]
Here's one [example](https://www.st.cs.uni-saarland.de/publications/details/lindig-aadebug-2005) with a recent-looking [repo](https://github.com/lindig/quest) we might consider. There is probably something more recent we can leverage.

**Comment by sergiy-k** [comment]
@pgavlin, do you know if this has been already fixed?

**Comment by pgavlin** [comment]
I think so, but I will double-check.

**Comment by sergiy-k** [comment]
Hi @pgavlin, did you have a chance to double-check this? Thank you.

**Comment by pgavlin** [comment]
Yes, this is fixed.
