### ISSUE TITLE
API Proposal: Expose TheadPool.UnsafeQueueCustomWorkItem and IThreadPoolWorkItem

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#19758]
When looking at a memory dump, it would be great if we could see data about work items in the various queues. Some of the things that would be interesting to see per work item
- A display name (HttpRequest/TaskContinuation) that can be provided by the caller
- An elapsed time to know how long an item was in the queue

This sort of info might help when looking at dumps trying to diagnose issues with the thread pool.

To enable this and other optimized scheduling scenarios, we should expose an interface that would allow customization of the underlying work item.

Proposal:

```C#
public interface IThreadPoolWorkItem
{
    void Execute();
}

public class ThreadPool
{
    public static void UnsafeQueueUserWorkItem(IThreadPoolWorkItem workItem, bool preferLocal);
}
```

These are advanced APIs and as such, there's no overload that captures the `ExecutionContext` (I'm not sure how it could anyways)

cc @stephentoub @kouvel @vancem

**Comment by davidfowl** [comment]
I had a thought. Instead of exposing these properties what if we just exposed something like `IThreadPoolWorkItem`? That would make it easier to implement it on user objects that have more context.

**Comment by stephentoub** [comment]
If this is about dumps, that data could all be stored in the state object that the caller provides, as that would be visible/inspectable in a dump, too, and that can be done with the implementation and API as they already exist.

I don't think we should add a display name to work items; we did that initially with tasks, and it ended up not being particularly useful, and backed it out... plus it almost certainly wouldn't be pay-for-play, at least in terms of memory, as every work item would need to be capable of holding on to a name.  Similarly, I'd worry about having to store the queued time onto a work item, as it would both increase the size of the work item and, depending on the desired accuracy, could entail a very measurable perf hit on acquiring the current time.

We've talked in the past about exposing a variant of IThreadPoolWorkItem (we wouldn't want to expose the abort-related method that's now legacy in core), and the corresponding ThreadPool.UnsafeQueueCustomWorkItem method.  I'm generally fine with that.  It would allow for certain schemes to be implemented more efficiently for someone that really knows what they're doing, and would allow for some additional diagnostics on direct usage, as you're suggesting.

**Comment by davidfowl** [comment]
> If this is about dumps, that data could all be stored in the state object that the caller provides, as that would be visible/inspectable in a dump, too, and that can be done with the implementation and API as they already exist.

I realize that, closures do work they are just extremely obscure to build tooling on top of.

> We've talked in the past about exposing a variant of IThreadPoolWorkItem (we wouldn't want to expose the abort-related method that's now legacy in core), and the corresponding ThreadPool.UnsafeQueueCustomWorkItem method. I'm generally fine with that. It would allow for certain schemes to be implemented more efficiently for someone that really knows what they're doing, and would allow for some additional diagnostics on direct usage, as you're suggesting.

Yep, that's why I kinda changed my suggestion to be exposing something like IThreadPoolWorkItem instead of adding those fields to every work item. That might be the best compromise and would allow callers to provide a custom work item instances.

Part of the thing driving this is to enable building tooling on top of the thread pool queues to allow visibility into the queued work items.

**Comment by davidfowl** [comment]
Just thought of another benefit of exposing this API, in Kestrel, we'd basically shave most of the QUWI allocations down since we're just invoking the callback over and over but incur the cost of a QueueUserWorkItem allocation when we don't need to:

https://github.com/aspnet/KestrelHttpServer/blob/8f6cb72ef27d86c9f691ba39851aa958a265cd5e/src/Kestrel.Transport.Sockets/Internal/IOQueue.cs#L13

The IOQueue itself would implement IThreadPoolWorkItem (or whatever variant doesn't have MarkAborted):

```C#
public class IOQueue : PipeScheduler, IThreadPoolWorkItem
{
    private readonly object _workSync = new object();
    private readonly ConcurrentQueue<Work> _workItems = new ConcurrentQueue<Work>();
    private bool _doingWork;

    public override void Schedule(Action<object> action, object state)
    {
        var work = new Work
        {
            Callback = action,
            State = state
        };

        _workItems.Enqueue(work);

        lock (_workSync)
        {
            if (!_doingWork)
            {
                System.Threading.ThreadPool.UnsafeQueueCustomWorkItem(this);
                _doingWork = true;
            }
        }
    }

    public void ExecuteWorkItem()
    {
        while (true)
        {
            while (_workItems.TryDequeue(out Work item))
            {
                item.Callback(item.State);
            }

            lock (_workSync)
            {
                if (_workItems.IsEmpty)
                {
                    _doingWork = false;
                    return;
                }
            }
        }
    }

    private struct Work
    {
        public Action<object> Callback;
        public object State;
    }
}
```

Pretty neat.

**Comment by stephentoub** [comment]
That's what I meant by "It would allow for certain schemes to be implemented more efficiently for someone that really knows what they're doing,"

**Comment by davidfowl** [comment]
Yep I was just calling out one of those concrete cases

**Comment by davidfowl** [comment]
Should I file a new bug or change this one to be the concrete API proposal?

**Comment by stephentoub** [comment]
Thanks. Either's fine.

**Comment by davidfowl** [comment]
Updated the proposal.

**Comment by stephentoub** [comment]
This issue was moved to dotnet/corefx#32485
