### ISSUE TITLE
[TieredCompilation] Miscellaneous regressions with tiering need investigation

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#19759]
- [x] JitBench Word2Vec benchmark’s "first search" numbers regressed significantly (350%)
  - Perhaps a case of cold method with hot loops (https://github.com/dotnet/coreclr/issues/19751)
  - Duplicate of https://github.com/dotnet/coreclr/issues/19751, until that is fixed tiering should be turned off for this test
- [x] Word2Vec's "training" is also slower but to a much lesser degree, perhaps a combination of the above and https://github.com/dotnet/coreclr/issues/19752, until that is fixed tiering should be turned off for this test
  - Duplicate of https://github.com/dotnet/coreclr/issues/19751
- [x] JitBench CscRoslynSource benchark
  - Project compilation completes while there is still tier 0 activity occurring, so call counting and tier 1 transitions don't happen
  - There's lots of room for throughput improvement with tier 1 JIT, perhaps it needs better heuristics to determine when to transition
  - No regressions in first or subsequent iterations as of https://github.com/dotnet/coreclr/pull/18610
  - Tracking potential improvements separately
- [x] Potential code locality issues - see https://github.com/dotnet/coreclr/pull/19121#issuecomment-408014042 and https://github.com/dotnet/coreclr/pull/19121#issuecomment-409925789
  - Code locality issues are unconfirmed, tracking potential improvements separately

**Comment by kouvel** [comment]
I searched online for any other issues that may have been reported and did not find any new issues.

**Comment by mattwarren** [comment]
@kouvel I ran into some strange Tiered-Compilation results when writing [this blog post](https://mattwarren.org/2019/03/01/Is-CSharp-a-low-level-language/#using-mathf-functions-instead-of-math):

| Run        | C++ (VS C++ 2017) | .NET Framework (4.7.2) | .NET Core (2.2) TC OFF | .NET Core (2.2) TC ON |
|------------|:-----------------:|:----------------------:|:----------------------:|:---------------------:|
| TestRun-01 |       41.38       |          58.89         |          46.04         |         44.33         |
| TestRun-02 |       41.19       |          57.65         |          46.23         |         45.96         |
| TestRun-03 |       42.17       |          62.64         |          46.22         |         48.73         |

All times are in **seconds** and the tests were run with `SET COMPlus_TieredCompilation=0` and `SET COMPlus_TieredCompilation=1`. I've not dug into the underlying cause, but the code [is here](https://gist.github.com/mattwarren/d17a0c356bd6fdb9f596bee6b9a5e63c) if it helps?

(I *suspect* that's it's related to https://github.com/dotnet/coreclr/issues/19751, as the code is essentially a series of nested loops)

**Comment by kouvel** [comment]
I'm seeing slightly lower perf with tiering, and looks like it's due to https://github.com/dotnet/coreclr/issues/19751. I'm seeing:

TC off | TC on | TC on DisableTier0Jit
-- | -- | --
41.83 | 43.87 | 42.10

For these types of benchmarks, for now a decent workaround may be `DisableTier0Jit` or to disable tiered compilation. I'm looking into whether it would be feasible to do that automatically for methods with loops.

**Comment by mattwarren** [comment]
Out of interest, do you see the variability that I was seeing across multiple runs? For me 'TC OFF' was more stable, but 'TC ON' produced more variable times? 

Thanks for the tip about `DisableTier0Jit`, I'd not heard about that config option.
