### ISSUE TITLE
Binding with ReuseAddress not working with UdpClient on Linux

### ISSUE THREAD

**Issue by olijf** [dotnet/coreclr#19765]
# Binding multiple clients on Linux platform in dotnet framework 2.1 does not work as expected

I am binding to a socket with SO_REUSEADDR (``MultiCastClient.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);``) but on Linux this gives me an address already in use exception.
In dotnet core 2.0 this was working fine. 

# General

I have the following relevant piece of code: 
```
...
MultiCastClient = new UdpClient();

MultiCastClient.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
var EndPoint = new IPEndPoint(IPAddress.Any, _listenPort);
MultiCastClient.JoinMulticastGroup(IPAddress.Parse(multicastAddress));

MultiCastClient.Client.Bind(EndPoint); // <--- this is where the bind exception happens.

try
{
	MultiCastClient.BeginReceive(RecieveCallBack, null);
}
...
```

I have a project targeting netcoreapp2.0 

When I am running this with ``dotnet-hosting-2.0.8`` everything is fine. However when I am running this with the newer CLR ``aspnetcore-runtime-2.1`` (all on Debian 9) I am getting a bind exception: 
```
Application startup exception: System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at UDPNMEAMessageReciever.UdpMessageProcessor.Start()
...
```

I havent looked into it much further, but I would like to be able to use the newer CLR. 
Thanks for helping me out here, I really appreciate your efforts.

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#32027
