### ISSUE TITLE
Fix UNKNOWN in dump generated by createdump

### ISSUE THREAD

**Issue by chrisnas** [dotnet/coreclr#19762]
https://github.com/dotnet/coreclr/pull/19761

With the current implementation, an LLDB analysis of a dump generated with the -h option leads to UNKNOWN instead of type/method names in dumpheap -stat or dumpstack commands.
This is due to missing assemblies from which the sos/mscordac plugin are extracting metadata.

With this pull request, the assemblies are now part of the dump without increasing too much the size: on a dual core machine, full=11GB, withheap=226MB, withheap(+patch)=269MB

It is especially important to decrease the size of a "usable" memory dump in the context of containers for which disk space is restricted and time during which an application does not respond to help check is limited.

Note: does not seem to be fixed on 2.1*

**Comment by mikem8361** [comment]
See https://github.com/dotnet/diagnostics/issues/56 also.

**Comment by mikem8361** [comment]
PR #19761 was merged.

**Comment by dpetillo** [comment]
@mikem8361 @chrisnas  will this fix be ported to 2.1?  I'm seeing this issue for minidumps on 2.1.11 with the lastest sos extensions.

**Comment by mikem8361** [comment]
This fix is in SOS which works against 1.1.x, 2.1.x, 2.2.x and 3.0.x versions of the .NET Core runtime. You can build a version with the fix from the diagnostics repo: https://github.com/dotnet/diagnostics#building-the-repository
