### ISSUE TITLE
[TieredCompilation] Hot method when inlined never reaches tier 1

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#19764]
The problem arises in application processing data with one very hot method doing 99,99% of the work which is inlined into cold method. Hot method never reaches tier1 compilation due to lack of tracking of it's pseudo calls and never gets optimized. The impact on application overall performance is 5 - 7 % performance regression.

Hot method cannot be prevented from inlining as this would cause much higher performance regression.

**Comment by benaadams** [comment]
Related? https://github.com/dotnet/coreclr/issues/19751

**Comment by 4creators** [comment]
@benaadams Not entirely since in this case method was hot before inlining and inlining converted method into case #19751. The solution to both issues could be different. Standard case for #19751 would require code blocks activity tracking while solution here could be based on deferred inlining or  maximum optimization of inlinee when inlining.

My proposal would be to go for maximum optimization of methods with aggressive inlining attribute which without it would not be inlined. This should happen when containing method is compiled for the first time.

**Comment by AndyAyersMS** [comment]
Do you have an example? Today we don't do any inlining at Tier0. And if we ever enable inlining for Tier0, it likely will only be for very small (and loop-free) callees. So I don't believe Tier0 inlining will add any new wrinkles to the cold method / hot loop issue.

We might need to check if explicit tail recursion (eg via a `tail` prefix) still gets handled like a call in Tier0 codegen, though.

**Comment by 4creators** [comment]
> So I don't believe Tier0 inlining will add any new wrinkles to the cold method / hot loop issue.

Could be wrong diagnosis on my side, however, switching tiered compilation off gives 5 - 7 % improvement.

> Do you have an example?

Yeah, `NBody` performance benchmark based on AVX2/AVX, SSE/SSE2/SSE3 intrinsics. Waiting for #19580 to get in before creating PR since it requires Avx2.Permute4x64 and code needs some cleanup as well.

**Comment by 4creators** [comment]
> Today we don't do any inlining at Tier0

It may mean that lack of inlining of hot method into cold one creates the performance penalty :smile;

**Comment by AndyAyersMS** [comment]
We'll have to look at your example. Post it when you can.

**Comment by tommcdon** [comment]
Moving to the 'future' milestone until we get a repro to investigate

**Comment by kouvel** [comment]
> `NBody` performance benchmark based on AVX2/AVX, SSE/SSE2/SSE3 intrinsics

@4creators, it looks like https://github.com/dotnet/coreclr/pull/19580 has been merged, could you please share a link to the benchmark code?

**Comment by kouvel** [comment]
> Not entirely since in this case method was hot before inlining and inlining converted method into case #19751

Methods containing loops are no longer tiered and are jitted with optimizations on first call since 3.0. If that was the issue (cold caller containing loop is not optimized, hence hot inlinee is also not optimized), then after the change the caller would be jitted with optimizations including any inlinees. Closing for now, if that was not the issue then please reactivate with more info.

**Comment by kouvel** [comment]
As noted above, the cold caller would not inline the hot callee when the caller is not optimized (correction from above comment), but the loop in the cold caller may still be hot and may be a significant source of calls to the callee, in which case the call overhead may be a significant contributor to the lower perf, that shouldn't be happening as of 3.0. I don't see a way for the hot callee to not be optimized.
