### ISSUE TITLE
Why Memory<T> and ReadOnlyMemory<T> does not implement IList<T> and IReadOnlyList<T> interfaces?

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/coreclr#19787]
Why Memory<T> and ReadOnlyMemory<T> does not implement IList<T> and IReadOnlyList<T> interfaces?

**Comment by benaadams** [comment]
It would be a severe anti-pattern as the performance would be dreadful. You'd have to repeatedly get the Span for each element; also why they don't have an enumerator or indexer (i.e. `this[int]`).

**Comment by jkotas** [comment]
Also, there are lifetime issues when `Memory<T>` is pointing to unmanaged memory.

`MemoryMarshal.ToEnumerable` was added as compromise. https://github.com/dotnet/corefx/issues/24854 has discussion on this.
