### ISSUE TITLE
Handling of ICorDebugManagedCallback.ControlCTrap is incorrect on Windows

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#19791]
## Repro steps:

OS: Windows

1. Create a new .NET Core app. Example:

```C#
static void Main(string[] args)
{
    while (true)
    {
        Thread.Sleep(100);
    }
}
```
2. Run the app with `dotnet run`
3. Attach to the process with VS or VS Code debugger
4. Control-C the app
5. This will fire the ControlCTrap back to the debugger, which will return back S_FALSE

Expected:
App is allowed to continue running and should exit

Actual:
App never exits and is stuck waiting for some sort of continue

## Notes:
It looks like vstfdevdiv changeset 1680357 wasn't ported to CoreCLR, and I think that may be the problem.

**Comment by noahfalk** [comment]
@mikem8361

**Comment by hoyosjs** [comment]
Closing this issue. We dropped support for due to complications in how interop

**Comment by hoyosjs** [comment]
VS/VSCode no longer trap on
