### ISSUE TITLE
Add event counters for the ThreadPool

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#19795]
It would be great to have event counters for the thread pool
- Number of threads (I think this exists as event data on ThreadPoolAdjustment)
- Number of globally queued work items
- Number of work item in all work stealing queues

cc @brianrob @vancem

**Comment by kouvel** [comment]
For the thread pool queues, would a total work item count suffice? I feel it is kind of an implementation detail that there are different types of queues but maybe it would be useful in some cases to separate them. The `QueueUserWorkItem` API was already modified to expose the local/global difference.

**Comment by davidfowl** [comment]
This is done right @kouvel?

**Comment by kouvel** [comment]
Currently the pending work item count reflects the total from the global queue and work-stealing queues, to keep the APIs simple to begin with. How the queues would be managed is kind of an implementation detail and may change in the future. There probably are cases where it would be useful to know each count separately and it would probably be good to consider what changes would be occurring to queues before exposing that in the APIs. So for this issue I was hoping to understand better if there would be a need to expose counts of different queues, different types of queues, and to how much detail. If there's a need for that it can be considered how to expose an API that could provide that info generically tying the info too closely with the current implementation.

**Comment by davidfowl** [comment]
We did this right? Can we close this issue now?

**Comment by kouvel** [comment]
Yea closing, if there is a need for getting separate counts between local and global queues, it can be considered in a new issue
