### ISSUE TITLE
Not consistent integer remainder behavior at the corner case

### ISSUE THREAD

**Issue by pkulikov** [dotnet/coreclr#19806]
The remainder operator under consideration is the [% operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#remainder-operator)

The corner case is the following:
- the left operand equals `int.MinValue`
- the right operand equals `-1`

The referenced above draft C# 6 language specification says:
> If the left operand is the smallest `int` or `long` value and the right operand is `-1`, a `System.OverflowException` is thrown. In no case does `x % y` throw an exception where `x / y` would not throw an exception.

The following code demonstrates not consistent behavior 
```csharp
using System;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(int.MinValue % -1);

        int a = int.MinValue;
        int b = -1;
        try
        {
            Console.WriteLine(a % b);
        }
        catch (OverflowException e)
        {
            Console.WriteLine(e.Message);
        }
    }
}
```

produces (copy/paste and run in [try.dot.net](https://try.dot.net/), for example) the following output
```
0
Arithmetic operation resulted in an overflow.
```

First, `Console.WriteLine(int.MinValue % -1);` doesn't throw, but produces zero. It's not according to the first quoted spec sentence
> If the left operand is the smallest `int` or `long` value and the right operand is `-1`, a `System.OverflowException` is thrown.

OK, the spec might have changed, but if we use variables instead of constants: `Console.WriteLine(a % b);` throws, given
```csharp
int a = int.MinValue;
int b = -1;
```

Regardless of the outcome (according to the spec or not), I would expect both outcomes at least be the same.

Seems that compiler converts `int.MinValue % -1` into zero (against the spec) and .NET doesn't mirror that behavior yet.

**Comment by mikedn** [comment]
Looks like a C# compiler bug, the IL code generated for something like `return int.MinValue % -1;` is
```
IL_0000  16                ldc.i4.0
IL_0001  2a                ret
```
AFAIR I've seen a similar issue recently but I can't find it right now.

**Comment by Joe4evr** [comment]
I copied your repro [to SharpLab](https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoOBmFVANhQCZCB2HAbxyXpQLRLgBYkBZAQwEsoAKAJR0GtbAwmEAnPz7AAdBz4A1LgBsIAUyQBSJAFpUgrNhGSkcpFyQBeC1AVKoqjZpPn6lgEa2DGM5LAYACeARJiHpJoMtZ6XsZhDAC+ifQAxlzAaQAWSPwA8gBummAAZmoA9gDuAKIAHmmaAA7APBVQSJrC4h4RkQzR/JqKmgDOo1wA5l3uHik99PNJQA==). :ok_hand:

**Comment by jakobbotsch** [comment]
Indeed this is a Roslyn bug, see https://github.com/dotnet/roslyn/issues/27348

**Comment by pkulikov** [comment]
@jakobbotsch thanks for pointing to the issue.
