### ISSUE TITLE
Allow command-line programs to have PowerShell Cmdlet-like arguments autocompletion

### ISSUE THREAD

**Issue by jzabroski** [dotnet/coreclr#19821]
I am 10x more productive in C# than I am in PowerShell, and think most of us would be better off writing code in either F# or C# than PowerShell, especially for DesiredStateConfiguration code integration, especially when you consider the pattern matching introduced in c# 7.

While PowerShell allows a back-door way [Authoring a DSC resource in C#](https://docs.microsoft.com/en-us/powershell/dsc/authoringresourcemofcs) via cmdlets, I lose all the niceties of bundling things as C# assemblies and nuget packages.  Cmdlets are just loose C# files with crazy ways of specifying dependencies that have no static linking to guarantee assemblies load correctly.

Perhaps this feature exists today and I don't know about it, the closest thing I could find was [.NET CLI Tab Completion](https://github.com/dotnet/cli/blob/master/Documentation/general/tab-completion.md), but that appears to be a clever hack using shell conventions.

Ideal would be for PowerShell to have the .exe tell it what the command line options are. Windows has never supported this, but I don't see why it cannot. There may be some practical constraints around this, such as arranging the .exe metadata such that command line info can be seeked for on the file quickly.

**Comment by RussKeldorph** [comment]
Doesn't seem relevant to this repo.  Perhaps https://github.com/Powershell/Powershell?

**Comment by jzabroski** [comment]
@RussKeldorph  Why isn't it relevant?  dotnet tools have command line parameters now.  There should be a standard language for command line parameters.  This is 2019 - I think we have exhausted all the ways someone can specify things on the command line.  Time to put .NET on the moon and give people less RSI and carpal tunnel by giving them auto-complete.  It should definiitely be part of the core runtime that programs the runtime runs has autocomplete

**Comment by svick** [comment]
@jzabroski 

> Ideal would be for PowerShell to have the .exe tell it what the command line options are. 

That sounds like a request for PowerShell first. If PowerShell starts supporting something like this, then .Net Core can start supporting it.

> It should definiitely be part of the core runtime that programs the runtime runs has autocomplete

I don't think it can. Autocomplete depends on the shell you're using:
* If you're using cmd, there is no custom autocomplete.
* If you're using PowerShell, it works one way.
* If you're using bash, it works another way.
* If you're using zsh, it works yet another way.

I think it could make sense to support autocomplete for custom .Net CLI tools (e.g. `dotnet watch`), expanding on the support for autocomplete in popular shells that .Net CLI already has (such request probably belongs to [the dotnet/cli repo](https://github.com/dotnet/cli)). But I don't think it's realistic to have generic autocomplete for any .Net Core app.

**Comment by jzabroski** [comment]
Petr,

When I right-click on a dll in Windows and go to Properties, why can I get
the version info of the dll?

Why can't I also get the command line parameters?

Why can't PowerShell then use that command line parameters metadata to
support auto-complete?

I think you're arguing about the presentation of the metadata, whereas I'm
saying there is a genuine need to describe the metadata before it can be
presented.

Thus, it's a catch-22 to tell me to tell the PowerShell guys about this
idea: how can they support exe autocomplete if there is no metadata to
query?

The only reasonable argument against this feature, if I am playing devil's
advocate, is not all platforms targeting the CLR runtime have command
lines/tty support.  But then there are probably other things that the CLR
supports that not every platform supports (System.Console). So where do I
request that?

If you want my 2 cents, I think no one wants to do this because it probably
means messing with how EXEs are stored, and nobody wants to risk their
career/reputation on potentially introducing a bug that way.

The alternative could be to handle this the way SOAP/JSONP does: ship a
WSDL/SWAGGER side-by-side with the services, so that the EXE format does
not have to change.  Thus, a logical super-structure would be placed on top
of the EXE.

**Comment by jzabroski** [comment]
Actually, you did give me a (HACKY) idea - I can prototype this in
PowerShell and show everyone how great it is.  I just need to overload a
special character that would serve as a PS function (similar to how % is an
alias for foreach-object).

The special character function could then be used like this:

~ dotnet w<tab>

It's a bit messy in that PowerShell parameters have to be given
"-ParameterName Value" style, which makes it very hard to create elegant
DLLs. However, ~ or similar could use PowerShell's Dynamic Parameters to
see the first argument is dotnet.exe, search for a dotnet.exe.swagger file
next to the exe, and use that for further auto-complete options.

**Comment by RussKeldorph** [comment]
> Why isn't it relevant?

@jzabroski I'm sorry I wasn't clear.  This repo contains the .NET Core Runtime (CoreCLR), which is generally not concerned with user interfaces of tools or programs that run on it.  Your request seems to be related to the dotnet command-line tool (https://github.com/dotnet/cli as @svick points) out and/or Powershell.  I'm not entirely familiar with the features involved, but either of those repos seem more relevant for discussion of this topic, so I recommend moving it somewhere else if you'd like to continue the discussion.

**Comment by jzabroski** [comment]
@RussKeldorph  Just to circle back on this... How would a command-line tool know what arguments are available for Flash Fill if the .dll doesn't embed that data in an efficient way?  Similar to magic byte headers or file extensions help to determine what program to suggest you open a file with.

This is the reason I filed this against the CorCLR github, as it seems intrinsic to the DLL.  But maybe CoreCLR doesn't concern with the DLL itself - that is a bit murky to me. Thoughts?
