### ISSUE TITLE
Move AVX/AVX2 intrinsic tests to template

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#19825]
I will move all AVX/AVX2 intrinsic tests to the template after implement the remaining AVX2 intrinsic in JIT.

**Comment by 4creators** [comment]
It's dupe of #19246 and that issue is already assigned. If you want to take it over pls remove my assignment and close it.

**Comment by RussKeldorph** [comment]
Closing assuming duplicate of #19246.
