### ISSUE TITLE
Mount database on sql server by code

### ISSUE THREAD

**Issue by mferraricloudsurfers** [dotnet/coreclr#19834]
Starting from mdf and ldf files and knowing the sql server connection credentials, I want to mount the database by code using .NET Core 2.
Is it possible?

**Comment by RussKeldorph** [comment]
I don't think coreclr is the right place for this issue, but I'm not sure where to redirect it, so moving to core in hopes of finding the right home.

**Comment by RussKeldorph** [comment]
This issue was moved to dotnet/core#1927
