### ISSUE TITLE
AssemblyLoadContext failing in netcoreapp

### ISSUE THREAD

**Issue by sokket** [dotnet/coreclr#19837]
@Petermarcu 

I have an ASP core app (targeting netcoreapp2.1, platform x64, and RID win7-x64) that's attempting to load a plugin (netstandard2.0, x64, win7-x64) via AssemblyLoadContext.LoadFromAssemblyPath (via a trivial implementation class we'll call MyAssemblyLoadContext)

```
MyAssemblyLoadContext context = new MyAssemblyLoadContext();
Assembly plugin = context.LoadFromAssemblyPath(fullPathToMyPlugin)
```

The above code runs just fine; however, when I attempt to cycle through the types in the Assembly in order to find any of the expected Plugin types, I get the loader failure

```
foreach (Type t in plugin.GetTypes())
{
...
}
```

Exception:
{System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

There are a whole lot of other assembly load failures, so I'm guessing there's a dependency load issue somewhere (or it isn't happening automagically). There isn't a whole lot of documentation around this area, so I'm a bit stuck. Any helpful pointers would be great :)

**Comment by Petermarcu** [comment]
@jeffschwMSFT @AtsushiKan @steveharter

**Comment by jeffschwMSFT** [comment]
@sokket can you share out the simple repro?  

cc @vitek-karas @swaroop-sridhar

**Comment by sokket** [comment]
@jeffschwMSFT sure thing; minimal repro is available here: https://github.com/sokket/coreplugintest

**Comment by sokket** [comment]
FYI - the failure I see happens here: https://github.com/sokket/coreplugintest/blob/master/Core/Startup.cs#L28

**Comment by sokket** [comment]
@vitek-karas: sorry for the first issue...whipped this up real quick to show the issue and forgot to fix up that section.

In regards to the Overall Approach - I started with AssemblyLoadContext in order to have hot loading and unloading of assemblies (ie if a customer changed their subscription) but it looks like unloading won't be possible until release 3 of .NET Core. If loading with the default context will provide auto dependency resolution, it looks like that's the easiest route forward until v3 has the hot loading / unloading. 

Thanks for your help, I'll try that out now

**Comment by vitek-karas** [comment]
Yes - unloadability is not supported in .NET 2.1 and the current plan is to have some form of this in .NET 3.0. Whether `Assembly.LoadFrom` will work for you really depends on the plugin. This approach only lets you load one version of an assembly with a given name. Might be OK for your scenario... or not.

**Comment by sokket** [comment]
Looks like loading into the default context will work for the time being; thanks for your help!
