### ISSUE TITLE
.NET Core Runtime ARM64 Status

### ISSUE THREAD

**Issue by richlander** [dotnet/coreclr#19843]
# .NET Core Runtime ARM64 Status

The .NET Core team is in the process of adding support for ARM64, as part of the .NET Core 3.0 project. This issue will be updated as ARM64 support progresses.

[.NET Core 3.0 Preview 1](https://github.com/dotnet/core/issues/2099) includes support for Linux ARM64. Please try this build and provide support.

## Current Status

ARM64 builds are functional, for console and ASP.NET Core apps.

## Details

Initial support for ARM64 was added in the .NET Core 2.1 release. The team is not maintaining .NET Core 2.x branches with respect to ARM64. All ARM64 improvements will be made in the .NET Core 3.0 branch (currently [master](https://github.com/dotnet/coreclr)).

See [Installing .NET Core 3.0 on Linux ARM64](https://gist.github.com/richlander/467813274cea8abc624553ee72b28213) to install .NET Core on your ARM64 machine. Builds are available from the [daily builds page](https://github.com/dotnet/core/blob/master/daily-builds.md).

## Bug Queries

the following bugs queries are available for ARM64:

* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues?q=is%3Aopen+is%3Aissue+label%3Aarch-arm64)
* [dotnet/corefx](https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+label%3Aarch-arm64)

## Operating Systems

.NET Core 3.0 ARM64 builds are tested on the following operating systems:

* Ubuntu 16.04 and 18.04
* Debian 9

## Test Hardware

.NET Core 3.0 ARM64 builds have been tested on the following hardware:

* [NVIDIA Jetson TX2 Module](https://developer.nvidia.com/embedded/buy/jetson-tx2)
* [Pine A64](https://www.pine64.org/?page_id=46823)
* [Qualcomm Centriq 2400](https://www.qualcomm.com/products/qualcomm-centriq-2400-processor)
* [Qualcomm Snapdragon](https://www.qualcomm.com/snapdragon/always-connected-pc)
* [Raspberry Pi3](https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/)

**Comment by jashook** [comment]
Issue #19805 has been fixed with #19822. I have confirmed that the latest built sdk overwritten with a private build of coreclr master works as expected. 

Currently we are waiting on a daily build with the changes that went in last night.

**Comment by richlander** [comment]
I just tested the latest build. It works. Yeahh!

`dotnet new console` produces a project that references `netcoreapp2.1`. I updated the reference to `netcoreapp3.0` and then dotnet run worked. Performance is not great. That's something to look into more.

ASP.NET Core apps are not yet working (ASP.NET Core is missing from the ARM64 SDK).

**Comment by jschiefer** [comment]
Successfully tried the SDK on Avnet Ultra96 (Xilinx Zynq Ultrascale+ ZU3EG), running Petalinux 2018.2. Very nice!

**Comment by qmfrederik** [comment]
I found `dotnet build` to be _very_ slow on a Raspberry Pi 3 device. The main reason appears to be that `dotnet build` will start 4 `msbuild` processes in parallel, but the device has not enough memory to support that (only 1 GB of memory is available).

I've opened dotnet/cli#10981

**Comment by RussKeldorph** [comment]
Closing as ARM64 is feature complete for 3.0.
