### ISSUE TITLE
Objects lost to mutator in gc_heap::mark_object_simple1() when marking many partial references

### ISSUE THREAD

**Issue by rimim** [dotnet/coreclr#19852]
This is only a problem for the normal gc, the server gc enables MH_SC_MARK which does not have this problem.

In gc_heap::mark_object_simple1() in the label 'more_to_do:'

                    if (ref_to_continue)
                    {
                        //update the start
      #ifdef MH_SC_MARK
                        assert ((*(place-1)) == (uint8_t*)0);
                        *(place-1) = (uint8_t*)((size_t)oo | partial_object);
                        assert (((*place) == (uint8_t*)1) || ((*place) == (uint8_t*)2));
     #endif //MH_SC_MARK
                        *place = ref_to_continue;
                    }

Unless MH_SC_MARK is enabled which is only enabled for the SERVER gc the partial object being marked will be missed. The *(place-1) slot needs to be updated even when MH_SC_MARK is not set, because the code that pops the references from the stack always reads two slots:

                if (partial_p (oo))
                {
                    start = ref_from_slot (oo);
                    oo = ref_from_slot (*(--mark_stack_tos));
                    dprintf (4, ("oo: %Ix, start: %Ix\n", (size_t)oo, (size_t)start));
                    assert ((oo < start) && (start < (oo + size (oo))));
                }

And if MH_SC_MARK is not set you only updated one slot. So I'd recommend the following change:

                    if (ref_to_continue)
                    {
                        //update the start
     #ifdef MH_SC_MARK
                        assert ((*(place-1)) == (uint8_t*)0);
                        assert (((*place) == (uint8_t*)1) || ((*place) == (uint8_t*)2));
     #endif //MH_SC_MARK
                        *(place-1) = (uint8_t*)((size_t)oo | partial_object);
                        *place = ref_to_continue;
                    }

The loop will continue to scan the oo object at the saved offset if the set aside stack for partial references is full (set to 32 for normal and 64 for server).

**Comment by jkotas** [comment]
cc @Maoni0

**Comment by Maoni0** [comment]
> The *(place-1) slot needs to be updated even when MH_SC_MARK is not set, because the code that pops the references from the stack always reads two slots

it reads 2 slots but one of them (where place-1 points to) remains the object address (till we are done marking this object in full) when MH_SC_MARK is not defined; we only need to update the slot where ref_to_continue is stored to indicate where in that object we should continue marking next time and that's stored in *place.

**Comment by rimim** [comment]
The problem is that if COLLECTIBLE_CLASS is defined then mark_stack_tos is one higher and place-1 is off-by-one. Probably doesn't affect the stock coreclr since that is not enabled.

**Comment by jkotas** [comment]
Is #19892 fixing this?

**Comment by rimim** [comment]
Yes.

**Comment by Maoni0** [comment]
@rimim you didn't mention COLLECTIBLE_CLASS. #19892 fixes this and is done in the right way. when COLLECTIBLE_CLASS is not defined, there's no problem.
