### ISSUE TITLE
[Tests/Arm/Arm64/Windows] CI PR jobs do not run tests for Windows arm and arm64 - consider enabling them when possible

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#19856]
Due to failures reported in #19853 I have verified test results for commits which caused them. It turns out that Windows CI jobs do not run tests what may lead to slipping in commits with errors on `arm` and `arm64` Windows targets. Consider enabling test runs once infrastructure will allow for it.

**Comment by RussKeldorph** [comment]
ARM and ARM64 should now be running tests in a manner more like other platforms, so hopefully now only the tests that fail due to a known issues are disabled (via issues.targets).  If I've misunderstood this issue, feel free to re-open.
