### ISSUE TITLE
What's the process for getting .NET Core to officially support an additional Linux distribution?

### ISSUE THREAD

**Issue by vellozzi** [dotnet/coreclr#19854]
# Issue Title

What's the process for getting .NET Core to officially support an additional Linux distribution?

# General

I'd like to work toward getting Amazon Linux added to the list of officially supported Linux distributions for .NET Core. 

What needs to be done, and where can I get started?

**Comment by Petermarcu** [comment]
I actually think this was in the right place before. I'll close this one and reopen the other one.
