### ISSUE TITLE
Set affinity for server GC threads

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#1986]
Body of `set_thread_affinity_mask_for_heap` is ifdefed out for CoreCLR. @Maoni0 thinks that it is important to fix this.

**Comment by benaadams** [comment]
From botr [Garbage Collection Design](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/garbage-collection.md)

> **Efficient locking:** The thread affinity of allocation contexts and quantums guarantee that there is only ever a single thread writing to a given allocation quantum. As a result, there is no need to lock for object allocations, as long as the current allocation context is not exhausted.

Could be a bug; rather than just perf?

**Comment by jkotas** [comment]
This issue is about thread affinity of server GC threads that affects performance only.

The botr paragraph you have quoted talks about thread affinity of allocation quantums that is unrelated concept.

**Comment by benaadams** [comment]
Ah, makes sense then

**Comment by benaadams** [comment]
Resolved by https://github.com/dotnet/coreclr/pull/4770 ?

**Comment by janvorli** [comment]
@benaadams it was fixed for Windows only, we still need to fix it for Unix.

**Comment by gkhanna79** [comment]
@janvorli Is this still planned for fixing in 2.0?

**Comment by janvorli** [comment]
Yes, I am currently finishing it. I have most of the stuff done.

**Comment by janvorli** [comment]
Implemented by #10938
