### ISSUE TITLE
Test exclusion lists for Windows arm and arm64 targets should raise warning for missing, excluded tests

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#19882]
Currently if Test.lst for Windows arm or Windows arm64 target has an excluded test it expects that it will be present in the code. While this enforces keeping lists in sync with test sources the check should not fail tests but simply raise warning. Such behavior would be consistent with the intention of the list which is to prevent execution of excluded tests. Failing tests due to missing excluded tests does not seem to be well aligned with exclusion list intentions.

cc @jashook @echesakovMSFT @BruceForstall

**Comment by BruceForstall** [comment]
The expectation is that these files, and test running mechanism, will soon disappear.

That being said, I'm not sure I agree. We've had problems in the past where tests unexpectedly and unintentionally disappear from the build, and the Windows arm/arm64 tests.lst files are the only reason we notice. So I'm a little worried that we'll lose that "check" when they do disappear.

**Comment by 4creators** [comment]
> So I'm a little worried that we'll lose that "check" when they do disappear.

This is another side of the problem and seems to be more important than small inconvenience of failing CI.
