### ISSUE TITLE
Getting NU1202  Package Microsoft.NETCore.App 2.0.9 is not compatible with netstandard2.0

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/coreclr#19896]
@MihaMarkic commented on [Tue Sep 11 2018](https://github.com/dotnet/core/issues/1929)

# Issue Title

When publishing project, I'm getting some NU1202  errors:
```
...\AutoMasshTik.Engine.csproj : error NU1202: Package Microsoft.NETCore.App 2.0.9 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.NETCore.App 2.0.9 supports: [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
...\AutoMasshTik.Engine.csproj : error NU1202:   - netcoreapp (.NETCoreApp,Version=v0.0) [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
...\AutoMasshTik.Engine.csproj : error NU1202:   - netcoreapp2.0 (.NETCoreApp,Version=v2.0) [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
...\AutoMasshTik.Engine.csproj : error NU1202: Package Microsoft.NETCore.App 2.0.9 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0) / win10-x86. Package Microsoft.NETCore.App 2.0.9 supports: [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
...\AutoMasshTik.Engine.csproj : error NU1202:   - netcoreapp (.NETCoreApp,Version=v0.0) [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
...\AutoMasshTik.Engine.csproj : error NU1202:   - netcoreapp2.0 (.NETCoreApp,Version=v2.0) [...\AutoMasshTik\src\AutoMasshTik.UI\AutoMasshTik.UI.csproj]
```

# General

The project in question is [AutoMasshTik](https://github.com/MihaMarkic/AutoMasshTik). 
I invoke something like 
`
 dotnet publish -o somepath\files  -r win10-x86 -c release /p:ShowLinkerSizeComparison=true
`
and get those errors.

`dotnet restore`
does not have issues and the project can be published/run just fine otherwise.

Note: you have to add latest ILLink.Tasks 0.1.5-preview-1841731 to AutoMasshTik.UI.csproj.

**Comment by Petermarcu** [comment]
I moved this hear because its sounds like an interaction with the ILLink tasks.

**Comment by karelz** [comment]
@sbomer @jeffschwMSFT should it go to https://github.com/mono/linker repo?

**Comment by sbomer** [comment]
@karelz I think it should go in mono/linker.

**Comment by karelz** [comment]
@sbomer thanks! Feel free to move it yourself in future if that's the case ;)

**Comment by karelz** [comment]
This issue was moved to mono/linker#446
