### ISSUE TITLE
Support running CoreFX perf tests against CoreCLR as part of PR/CI

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#19893]
We do not currently have a mechanism (outside of manually doing so) to run the CoreFX perf tests against a change made to CoreCLR (either as part of a PR or normal CI).

Given that a large portion of types are implemented in CoreCLR as part of `System.Private.CoreLib`, we should likely have an easy mechanism to validate these perf changes.

**Comment by tannergooding** [comment]
CC. @jkotas, @eerhardt, @danmosemsft, @adamsitnik

**Comment by adamsitnik** [comment]
I have some good news, we already have it, but in a private repo that we hope to open soon ([link](https://github.com/dotnet/performance/tree/master/src/benchmarks)).

In the performance repo we have:

1. All CoreCLR benchmarks ported to BenchmarkDotNet
2. All CoreFX benchmarks ported to BenchmarkDotNet

I have also added the possibility for BenchmarkDotNet to run given benchmarks against given `dotnet cli` and/or `CoreRun`. 
The goal is that you can use existing build scripts that put everything required to run .NET app together to a folder, and then provide the path to `CoreRun.exe` / `dotnet.exe`  to BenchmarkDotNet.

Also, all of the benchmarks have been groupped into categories, some of them (like Span) belong to both CoreCLR and CoreFX.

**Comment by RussKeldorph** [comment]
Let's enhance dotnet/performance if the desired functionality isn't already there.
