### ISSUE TITLE
Question: Java11 now has ZGC, does .Net have a similar one?

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#19906]
ZGC is a new GC mechanism for large heap.

**Comment by janvorli** [comment]
cc: @Maoni0

**Comment by Maoni0** [comment]
yes, we are aware. we don't offer a similar GC right now as it hasn't been at the top of our priority list. when we do you will see it announced.

**Comment by 4creators** [comment]
@mattwarren ZGC garbage collector in Java and K. Kokosa Zero Garbage Collector have nothing in common except for Garbage. ZGC is a new GC mechanism to support huge in memory applications (up to 4TB) with minimum latency while ZGC by K. Kokosa is an experimental design which does nothing more than:

> It only allows you to allocate objects, because this is obviously required by the Execution Engine. Created objects are never automatically deleted and theoretically, no longer needed memory is never reclaimed.

**Comment by Maoni0** [comment]
@mattwarren ZGC is a concurrent compacting GC. if you search for concurrent compacting garbage collector, there's a ton of stuff in the literature.

**Comment by mattwarren** [comment]
@4creators @Maoni0 my bad, I mis-understood what ZGC was. Thanks for the info, I guess I need to go away and do some reading :grin:
