### ISSUE TITLE
EventSource generates an out-of-band error when using WriteEvent(int, byte[])

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#1991]
When defining an event source with an event like:
```C#
[Event(1)]
public void LogArray(byte[] arr)
{
    WriteEvent(1, arr);
}
```
EventSource reports an out-of-band error of the form:
```
Event 1 was called with 2 argument(s) , but it is defined with 1 paramenter(s).
```
It appears this is due to the WriteEvent(int, byte[]) overload writing out two EventData elements, one for the array length, and one for the array pointer, which is a mismatch from the event signature that just takes the array.

cc: @vancem, @brianrob

**Comment by brianrob** [comment]
cc: @davmason

**Comment by sergiy-k** [comment]
Fixed by PR https://github.com/dotnet/coreclr/issues/1991
