### ISSUE TITLE
Linked cancellation token source where all tokens must be cancelled

### ISSUE THREAD

**Issue by MatthewLymer** [dotnet/coreclr#19912]
This is more of an question of whether such functionality exists within the coreclr already.

I've used `CancellationTokenSource.CreateLinkedTokenSource` to get a `CancellationToken` which will be cancelled when any of the subject tokens are cancelled.

My current scenario is I invoke an HTTP API and I would like to record in Entity Framework the result of that call.  Currently the EF call uses the same token I used for the HTTP API.  This works fine so long the token does not become cancelled.

The obvious solution to use a separate `CancellationToken` for the database call, which resulted in me making a small one that expires after 3 seconds, works fine for most scenarios but sometimes it operation takes longer than 3 seconds, so despite the first token still having time left left, the database operation fails due to the 3 second token.

My question is: 
Is there functionality within the `CancellationTokenSource` class (or elsewhere) that creates a linked token where *all* of the subject tokens must be cancelled for the derived one to be considered cancelled?

**Comment by kouvel** [comment]
CC @tarekgh

**Comment by tarekgh** [comment]
I am not aware of any API support this scenario. you may create your custom type doing that. 

CC @stephentoub just in case he knows any API doing that.

**Comment by stephentoub** [comment]
> Is there functionality within the CancellationTokenSource class (or elsewhere) that creates a linked token where all of the subject tokens must be cancelled for the derived one to be considered cancelled?

There's nothing built into .NET, but you could easily build your own, e.g. (untested)
```C#
sealed class AllLinkedSource : CancellationTokenSource
{
    private readonly CancellationTokenRegistration[] _registrations;
    private int _remaining;

    public AllLinkedSource(params CancellationToken[] tokens)
    {
        _remaining = tokens.Length;
        _registrations = new CancellationTokenRegistration[tokens.Length];
        for (int i = 0; i < tokens.Length; i++)
        {
            _registrations[i] = tokens[i].Register(t =>
            {
                var thisRef = (AllLinkedSource)t;
                if (Interlocked.Decrement(ref thisRef._remaining) == 0) thisRef.Cancel();
            }, this);
        }
    }

    protected override void Dispose(bool disposing)
    {
        foreach (CancellationTokenRegistration reg in _registrations) reg.Dispose();
        base.Dispose(disposing);
    }
}
```

**Comment by tarekgh** [comment]
@MatthewLymer I am closing this issue but feel free to reply back with any more follow up questions.

**Comment by MatthewLymer** [comment]
Awesome, thanks for your help guys!
