### ISSUE TITLE
Remove DllImport EXE test

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/coreclr#19916]
Loading an `exe` as a library results in undefined behavior and should not be attempted. It is not a supported scenario in Windows.

The test should be removed: `tests\src\Interop\DllImportAttribute\ExeFile\CMakeLists.txt`

**Comment by luqunl** [comment]
Please Don't remove. This can be Windows Only testcase.

**Comment by AaronRobinsonMSFT** [comment]
This isn't supported by Windows, but since we had a customer issue about a regression I will leave it.
