### ISSUE TITLE
SIMD not enabled on Unix?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#1996]
Am I misunderstanding how the JIT is compiled, or does this code effectively mean that we're not enabling FEATURE_SIMD on Unix?
https://github.com/dotnet/coreclr/blob/master/src/jit/CMakeLists.txt#L9-L13
```
if (WIN32) 
if (CLR_CMAKE_PLATFORM_ARCH_AMD64)
  add_definitions(-DFEATURE_SIMD -DFEATURE_AVX_SUPPORT) 
endif (CLR_CMAKE_PLATFORM_ARCH_AMD64)
endif (WIN32)
```
If it's not being enabled, can we fix that?

cc: @CarolEidt, @mellinoe

**Comment by RussKeldorph** [comment]
Subset of #983.
