### ISSUE TITLE
CI is highly unstable - network errors + IO disk has run out of space errors

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#19982]
Over last week CI is failing multiple times with both network errors (failures: git clone, java.IO exceptions) and IO disk errors. Such situation leads to higher than expected load on CI as tests have to be rerun, and increased length of developer cycle. 

On top of that there are problems with triggering individual jobs - trigger phrases seem to not always work correctly.

**Comment by 4creators** [comment]
It turns out that IO disk has run out of space errors could be a network errors:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_innerloop_prtest/7943/

reports IO disk error 

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_innerloop_prtest/7943/console

but seems to fail due to network error

09:16:45 Started by upstream project "dotnet_coreclr/master/x64_checked_ubuntu_innerloop_flow_prtest" build number 7684
09:16:45 originally caused by:
09:16:45  GitHub pull request #19980 of commit 45b5746fd9f370ad889ea96852dbaff465497b21, no merge conflicts.
09:16:45 Building remotely on ubuntu1404-20180321-901501 (ubuntu1404-20180321) in workspace /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_innerloop_prtest
09:16:45 [WS-CLEANUP] Deleting project workspace...
09:16:45 [WS-CLEANUP] Done
09:16:45 Selected Git installation does not exist. Using Default
09:16:45 Cloning the remote Git repository
09:16:45 Cloning repository https://github.com/dotnet/coreclr
09:16:45  > git init /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_innerloop_prtest # timeout=10
09:16:45 Fetching upstream changes from https://github.com/dotnet/coreclr
09:16:45  > git --version # timeout=10
09:16:45  > git fetch --tags --progress https://github.com/dotnet/coreclr +refs/heads/*:refs/remotes/origin/* # timeout=90
09:17:05  > git config remote.origin.url https://github.com/dotnet/coreclr # timeout=10
09:17:05  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
09:17:05  > git config remote.origin.url https://github.com/dotnet/coreclr # timeout=10
09:17:05 Fetching upstream changes from https://github.com/dotnet/coreclr
09:17:05  > git fetch --tags --progress https://github.com/dotnet/coreclr +refs/pull/19980/*:refs/remotes/origin/pr/19980/* # timeout=90
09:17:06  > git rev-parse refs/remotes/origin/pr/19980/merge^{commit} # timeout=10
09:17:06  > git rev-parse refs/remotes/origin/origin/pr/19980/merge^{commit} # timeout=10
09:17:06 JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://wiki.jenkins-ci.org/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData
09:17:06 Checking out Revision ffeb6f19ad199fe289e8658edbd9b906e22a420a (refs/remotes/origin/pr/19980/merge)
09:17:06 Commit message: "Merge 45b5746fd9f370ad889ea96852dbaff465497b21 into d47162260d4e202bb06fcc7449fadbfd2955b83b"
09:17:06  > git config core.sparsecheckout # timeout=10
09:17:06  > git checkout -f ffeb6f19ad199fe289e8658edbd9b906e22a420a
09:17:08  > git rev-list 2f33c5f719701af8ea53f6e788f37513ce927b20 # timeout=10
09:17:08 First time build. Skipping changelog.
09:17:08 Run condition [Current build status] enabling prebuild for step [[Archive the artifacts]]
09:17:08 FATAL: Unable to produce a script file
09:17:08 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to ubuntu1404-20180321-901501
09:17:08 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
09:17:08 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
09:17:08 		at hudson.remoting.Channel.call(Channel.java:908)
09:17:08 		at hudson.FilePath.act(FilePath.java:986)
09:17:08 		at hudson.FilePath.act(FilePath.java:975)
09:17:08 		at hudson.FilePath.createTextTempFile(FilePath.java:1363)
09:17:08 		at hudson.tasks.CommandInterpreter.createScriptFile(CommandInterpreter.java:162)
09:17:08 		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:94)
09:17:08 		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
09:17:08 		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
09:17:08 		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
09:17:08 		at hudson.model.Build$BuildExecution.build(Build.java:206)
09:17:08 		at hudson.model.Build$BuildExecution.doRun(Build.java:163)
09:17:08 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
09:17:08 		at hudson.model.Run.execute(Run.java:1724)
09:17:08 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
09:17:08 		at hudson.model.ResourceController.execute(ResourceController.java:97)
09:17:08 		at hudson.model.Executor.run(Executor.java:429)
09:17:08 
java.io.IOException: No space left on device
09:17:08 	at java.io.FileOutputStream.writeBytes(Native Method)
09:17:08 	at java.io.FileOutputStream.write(FileOutputStream.java:326)
09:17:08 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
09:17:08 	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316)
09:17:08 	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
09:17:08 	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
09:17:08 	at hudson.FilePath$17.invoke(FilePath.java:1380)
09:17:08 	at hudson.FilePath$17.invoke(FilePath.java:1363)
09:17:08 	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2760)
09:17:08 	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
09:17:08 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
09:17:08 	at hudson.remoting.Request$2.run(Request.java:358)
09:17:08 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
09:17:08 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09:17:08 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:17:08 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:17:08 	at java.lang.Thread.run(Thread.java:748)
09:17:08

**Comment by BruceForstall** [comment]
@dotnet/dnceng 

@4creators I've seen many of these problems, but it's probably more actionable to point these out with specific cases when they happen, such as links to the failing jobs.

w.r.t. trigger phrases not being recognized: I've assumed that this is due to CI server overload (or other problem), as either (1) waiting, (2) re-triggering using the same trigger phrase, or (3) closing and re-opening the PR has always done the trick.

**Comment by 4creators** [comment]
FWIW It seems that disk are filling up bcs build and test leave dotnet.exe running with multiple MSBuild nodes. The same happens locally after build.

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_windows_nt_formatting_prtest/22102/
```
12:34:14 Deleting D:\j\workspace\x64_windows_n---616f30f2\dj
12:34:14 Traceback (most recent call last):
12:34:14   File "tests\scripts\format.py", line 253, in <module>
12:34:14     return_code = main(sys.argv[1:])
12:34:14   File "tests\scripts\format.py", line 236, in main
12:34:14     shutil.rmtree(dotnetcliPath, onerror=del_rw)
12:34:14   File "C:\Python27\lib\shutil.py", line 252, in rmtree
12:34:14     onerror(os.remove, fullname, sys.exc_info())
12:34:14   File "tests\scripts\format.py", line 30, in del_rw
12:34:14     os.remove(name)
12:34:14 WindowsError: [Error 5] Access is denied: 'D:\\j\\workspace\\x64_windows_n---616f30f2\\dj\\dotnet.exe'
12:34:14 
12:34:14 D:\j\workspace\x64_windows_n---616f30f2>exit 1 
12:34:14 
Build step 'Execute Windows batch command' marked build as failure
```

**Comment by Chrisboh** [comment]
Hi @BruceForstall, we are tracking this with https://github.com/dotnet/core-eng/issues/4203 and is looking into it now.
