### ISSUE TITLE
Question: is it safe to use default calli on native function pointers?

### ISSUE THREAD

**Issue by buybackoff** [dotnet/coreclr#19997]
Detailed question is on [SO](https://stackoverflow.com/questions/52273315/cli-calli-on-x64-calling-convention), but no answer there.

Basically, using `calli` without `unmanaged cdecl` works just fine for native calls on `x64` and is much faster than `DllImport`. This could be very useful for lighweight native calls and I have a [real example](https://github.com/Spreads/Spreads.LMDB/commit/dc5f383a719add5e591af55492edce888c0cda5d) and not just an empty function call.

Does it work by design and could I rely on this behavior on `x64`?

**Comment by benaadams** [comment]
Related [csharplang/proposals/intrinsics](https://github.com/dotnet/csharplang/blob/master/proposals/intrinsics.md)

**Comment by buybackoff** [comment]
@benaadams Isn't that proposal about managed calls mostly? I started to look into the `calli` after following that proposal and measured perf for native calls. If default `calli` is not supported for them then there is no benefits of using them so far, probably due to #13756.

**Comment by AndyAyersMS** [comment]
For x64 the calling convention will work out, but you risk running into issues with GC. The extra glue put in by the jit or runtime for calls to unmanaged methods helps the runtime figure out that the stack has transitioned out of managed code and sets things up to trap back to the runtime if a GC is in progress when the unmanaged code returns.

For calls to very quick executing methods it may take a long time to encounter one of these problems but the potential is there.

**Comment by buybackoff** [comment]
@AndyAyersMS Will this cause a crash like a segfault or what king of problem?

Also, I am not sure if default calli is faster due to inlining from #13756 or due to that additional work you mention?

**Comment by AndyAyersMS** [comment]
It could cause a variety of problems. Crashing is certainly possible. 

If the calli is invoking managed code (which the "default" implies) then none of the special precautions are required, so the call can go direct.

Also note measuring pinvoke overhead is subtle as a healthy part of the setup cost can be amortized across calls. See for instance the comments in #2373.

**Comment by jkotas** [comment]
> It could cause a variety of problems. Crashing is certainly possible.

Other problems that this will caused are hangs and data corruptions.

**Comment by jkotas** [comment]
> I have a [real example](https://github.com/Spreads/Spreads.LMDB/commit/dc5f383a719add5e591af55492edce888c0cda5d) 

Note that your use of `Unsafe.AsPointer` is not generally safe. The arguments can be allocated on GC heap and GC can move them around.

If you are sure that the arguments do not need to pinned, you can use the same optimization for the DllImport path too - change the DllImport arguments to unmanaged pointers. `ref` arguments require marshaling (pinning) and thus they are more expensive to pass.

**Comment by buybackoff** [comment]
> Note that your use of Unsafe.AsPointer is not generally safe. The arguments can be allocated on GC heap and GC can move them around.

They are blittable value types on the stack, I assumed it's save to take a pointer via Unsafe. The struct itself have a pointer that refers to always pinned or native memory.

> ref arguments require marshaling (pinning) and thus they are more expensive to pass.

I have changed native call signature for DllImport to use `void*`: `(void* txn, uint dbi, void* key, void* data)` and the difference is still stable 6-9%. My original tests with empty native function showed 60% diff on `netcoreapp2.1` and 80% on `net471`, and that native call has only pointers without refs. Also marking all intermediate methods between benchmark and native call with `NoInlining` to account for possible issues as in 2373 keeps the difference.

However, LMDB is the only real-world example I could come up with where P/Invoke overhead is visible - due to it's insane read speed. And the order of the difference in single digit percents is not enough to justify such hacks with `calli`. Due to Vector<T> and upcoming SIMD intrinsics the need for very lightweight native calls is disappearing. P/Invoke overhead was a deal-breaker e.g. when trying to use Yeppp native library for SIMD simple math, payload needed to be very huge to get to break-even.

So I assume the answer to my question is *no, it's not save*. (Yet running a benchmark for several hours with a separate thread allocating and collecting without even spinning, ok after 3 hours.)

Last related question: are the `DllImport` calls used by `corefx/coreclr` exactly the same as in user code and the framework is not "cheating" e.g. by removing some overheads?

**Comment by jkotas** [comment]
>  Are the DllImport calls used by corefx/coreclr exactly the same as in user code 

Yes, the DllImport used internally by corefx/coreclr is exactly same as in user code. No cheating.

**Comment by jkotas** [comment]
> They are blittable value types on the stack, I assumed it's save to take a pointer via Unsafe

Yes, it is safe in this case. It is better to pass the value as unmanaged pointer everywhere to make this clear and correct by construction.

**Comment by KodrAus** [comment]
> The extra glue put in by the jit or runtime for calls to unmanaged methods helps the runtime figure out that the stack has transitioned out of managed code and sets things up to trap back to the runtime if a GC is in progress when the unmanaged code returns.

I've been curious about what's _actually in_ a p/invoke call, so started spelunking around [`dllimport.cpp`](https://github.com/dotnet/coreclr/blob/master/src/vm/dllimport.cpp#L4823-L5096). It looks like the `[UnmanagedFunctionPointer]` and `[DllImport]` approaches emit roughly the same code at runtime; they both end up wrapping the unmanged call up in some `IL_STUB_PInvoke`? Is there a bit more of a description anywhere on what the actual pieces in that generated delegate are?

**Comment by jkotas** [comment]
The actual low-level details of what happens for managed->native transition are described in https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md#per-frame-pinvoke-initialization

The "big picture" that this fits into is described in:

https://github.com/dotnet/coreclr/blob/master/Documentation/botr/intro-to-clr.md#the-concept-of-managed-code
https://github.com/dotnet/coreclr/blob/master/Documentation/botr/stackwalking.md

**Comment by KodrAus** [comment]
Thanks! That's exactly what I was after.
