### ISSUE TITLE
Implement calling convention for structs passing in JIT for Linux and Mac

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/coreclr#200]
@llitchev Could you please provide a bit more details here about the current state of the work and name of a feature branch once you move the code that your are currently working on to GitHub? Thank you.

**Comment by LLITCHEV** [comment]
My fork for this work is LLITCHEV/creclr. The branch is SystemVStructs. Working on transferring the changes from my TF repository and populating the branch.

**Comment by KindDragon** [comment]
Reference to branch https://github.com/LLITCHEV/coreclr/tree/SystemVStructs

**Comment by jkotas** [comment]
I am adding a workaround in https://github.com/dotnet/coreclr/pull/392 . It should be removed once this issue fixed.

**Comment by jkotas** [comment]
@cwensley has run into this when trying to P/Invoke method with struct CGRect argument on Mac.

**Comment by jkotas** [comment]
@cwensley has run into this when trying to P/Invoke method with struct CGRect argument on Mac.

**Comment by LLITCHEV** [comment]
Implementation PRed.
Implementation of System V ABI struct passing. #1806
