### ISSUE TITLE
Using System.Management classes causes runtime assert

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#20001]
_From @filipnavara on September 17, 2018 15:15_

Using the following code:
```c#
new ManagementClass("Win32_BIOS");
```

crashes CoreCLR on Windows:
```
Assertion Failed
BSTR localloc'ed buffer is too small

   at System.StubHelpers.BSTRMarshaler.ConvertToNative(String strManaged, IntPtr pNativeBuffer)
   at System.Management.SecuredConnectHandler.ConnectNSecureIWbemServices(String path, IWbemServices& pServices)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ThreadDispatch.ThreadEntryPointMethodWithParam()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

I am not sure whether this is something that is broken on the CoreFX side or CoreCLR side, so please move if this is inappropriate repository (/cc @jkotas).

_Copied from original issue: dotnet/corefx#32316_

**Comment by jkotas** [comment]
This looks like a bug in CoreCLR.

**Comment by jkotas** [comment]
cc @luqunl @jeffschwMSFT

**Comment by luqunl** [comment]
@filipnavara, Could you give more info about how to repro this? I couldn't repro with the following code
` `         
var c = new ManagementClass("Win32_BIOS");
System.Management.ManagementObjectCollection wmiNetAdapters = c.GetInstances();
 Console.WriteLine("Net adapters:" + wmiNetAdapters.Count);
``

**Comment by filipnavara** [comment]
I'll try to reduce the problem to simple app and post it. On my machine it was enough to just execute the single line and have the program run long enough that the `InitializeGuts` thread got executed. I used CoreFX and CoreCLR debug builds from today's morning built on my machine. There's a tiny chance that it may be something in my build setup that caused it, but it was easily reproducible within our application.

**Comment by filipnavara** [comment]
Oh, one thing that could be relevant is that I executed the application as "win-x86" runtime, ie. 32-bits.

**Comment by luqunl** [comment]
Let me try to use x86 and give update later

**Comment by luqunl** [comment]
still no luck, @filipnavara, Do you know the value for strManaged during assert? if yes, it will help a lot to repro this.

> System.StubHelpers.BSTRMarshaler.ConvertToNative(String strManaged, IntPtr pNativeBuffer)

**Comment by filipnavara** [comment]
Thanks for taking the time! I will try to make a repro tomorrow and modify my runtime to print out more information.

**Comment by filipnavara** [comment]
[core.zip](https://github.com/dotnet/coreclr/files/2392746/core.zip)

This is the simplest repro I was able to produce. Curiously it doesn't crash when run from inside Visual Studio. However if it is built once and then run using `dotnet core.dll` from command line with the 32-bit `dotnet` SDK it produces the crash above.

**Comment by filipnavara** [comment]
Interestingly the initialization in the `System.Management` assembly is improperly guarded:

https://github.com/dotnet/corefx/blob/a0e4d78a74b241289dcf0c4c1c6fa026e394a150/src/System.Management/src/System/Management/ManagementScope.cs#L946-L969

If the `!MTAHelper.IsNoContextMTA()` branch is taken then two successive calls can start the initialization in a separate thread at the same time.

**Comment by luqunl** [comment]
> If the !MTAHelper.IsNoContextMTA() branch is taken then two successive calls can start the initialization in a separate threads at the same time.

From quick look, it seems you are right that two thread may initialize it at the same time. @pjanotti should know more about this.

Even with your code, I can't repro(bad luck for me).  Here is my steps
1. copy SDK from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x86.zip
2. unzip your core.zip into my local folder and add a RID into project file 
3. dotnet build
4. dotnet publish
5. copy chk version coreclr bit into published folder..
6. run core.exe

**Comment by filipnavara** [comment]
I think it must be some sort of race condition in the initialization that triggers it. It's a bit difficult to debug when it doesn't happen under a debugger. I'll try to come up with a better reproducible way to trigger it.

**Comment by luqunl** [comment]
I will close this issue first. if you have a repro, please reactive this issue.

**Comment by filipnavara** [comment]
I tried to reproduce the issue again without success. I came to the conclusion that my previous setup must have been broken and had a mismatched CoreLib and CoreCLR debug/release builds. With debug CoreLib the assert would be present, but release CoreCLR wouldn't put in the necessary data for the assert to fire correctly. Thanks for all the help with this!
