### ISSUE TITLE
[Arm32]: corefx System.IO.Compression.DeflateStreamUnitTests fails

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#20003]
This test is failing:

System.IO.Compression.Tests

Specifically, if you pass `-class System.IO.Compression.DeflateStreamUnitTests` to xunit, it may fail. I have yet to see it fail on 16.04, but it fails most of the time on 14.04, but I was fooled into thinking that this failure was specific to COMPlus_JitStressRegs=8 and introduced in my PR #19745 because it coincidentally didn't fail with master the first time I tried.

It failed here: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/view/Official%20Builds/job/arm_cross_checked_ubuntu_corefx_baseline_tst/21/ in a recent run, without stress.

**Comment by sandreenko** [comment]
I have not found an exclusion for it and do not see it failing in the available history. So I assume the test is running and doesn't fail.
 Close for now. Please reopen if it is still an issue.
