### ISSUE TITLE
BitConverter.IsLittleEndian as a constant

### ISSUE THREAD

**Issue by deinok** [dotnet/coreclr#20026]
Seems like the static readonly field IsLittleEndian can be changed to `public const bool IsLittleEndian`

**Comment by mikedn** [comment]
That would prevent you from writing AnyCPU libraries that use `IsLittleEndian` because the value of the constant will be baked into your library at compile time.

Besides, there's little need for this to be a constant. The JIT already treats it as such.

**Comment by deinok** [comment]
@mikedn, ouch i totally missed this.
Closing this
