### ISSUE TITLE
[Question] ARMEnabled knob

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#20041]
CoreCLR has `ARMEnabled` knob. Is it related to ARM CPU or to [Azure Resource Manager(ARM)](https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/deployment/arm-onboarding)

cc @jkotas

**Comment by jkotas** [comment]
It has nothing to do with Azure Resource Manager.

It stands for [AppDomain Resource Monitoring](https://www.bing.com/search?q=AppDomain+Resource+Monitoring). It is not really useful in CoreCLR since it does not support appdomains.

**Comment by alpencolt** [comment]
Thank you!
cc @gbalykov @BredPet
