### ISSUE TITLE
Build of mscorlib taking a long time on clean systems

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#2004]
On a clean system with no nuget cache, building mscorlib takes an excessive amount of time (> 10 mins).  Any ideas why?

/cc @stephentoub @ellismg @pgavlin

**Comment by pgavlin** [comment]
Last time I checked most of that time was being spent in dnu (on both Windows & Linux).

**Comment by mmitche** [comment]
@sergiy-k This doesn't repro any longer, closing
