### ISSUE TITLE
Make PEVerify output useful

### ISSUE THREAD

**Issue by ygoe** [dotnet/coreclr#2005]
I'm generating or manipulating assemblies at the IL level with Mono Cecil. This can lead to all sorts of errors and I use PEVerify to find them. But when the full output of PEVerify is just "The method does not exist." (or whatever the text is in English) then it's not helpful at all. No token number, no affected type, no nothing. Where should I even start to look for the problem? What does the detected problem look like? Why is a method missing, who wants to have it? The program doesn't run properly and I can see where it produces wrong results, but I don't see anything strange in that area.

I could provide you a broken assembly for reference but I can't upload it here.

**Comment by leppie** [comment]
Can you dump the IL as a gist? (also doing a ildasm/ilasm cycle might give more info about the error)

**Comment by dg9ngf** [comment]
You can download the assembly files here:

https://drive.google.com/file/d/0B8CN0ghdY1SdaGdrZXlESVE3Y2s/view?usp=sharing

I haven't made especially good experience with ildasm+ilasm, Most of the time something is missing that is not represented with IL so the result is incomplete and doesn't work.

**Comment by jkotas** [comment]
This issue was moved to dotnet/corert#5060

**Comment by jkotas** [comment]
This should get addressed by https://github.com/dotnet/corert/tree/master/src/ILVerify project.
