### ISSUE TITLE
Remove generic Intel hardware intrinsic and explode them on all the supported types

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#20057]
According to the latest API review meeting, we determined that hardware intrinsic should explicitly be exploded on all the supported types (e.g., `Vector256<int>`, `Vector128<long>`, `Vector128<short>`, `Vector256<float>`, etc). This also makes it clear when/if support for new types (e.g., Half) are added in the future that they aren't supported in the older ISAs. But we may be able to have generic helper intrinsic (like `SetAllVector256<T>`).

@CarolEidt @tannergooding @eerhardt

**Comment by tannergooding** [comment]
CC. @terrajobst

**Comment by Wraith2** [comment]
Are api reviews still recorded or noted somewhere?

**Comment by fiigii** [comment]
@Wraith2 https://github.com/dotnet/apireviews/tree/master/2018/Hardware-Intrinsics-Intel
