### ISSUE TITLE
cpblk corruption with LOH block containing refs causes CLR fatal exit

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/coreclr#20086]
The **cpblk** instruction works fine for moving blocks which contain managed references, ***but only if the blocks are in generation 0***.  For objects in generation 2, a.k.a. the Large Object Heap (LOH), the CLR consistently fails and exits with a severe error (such as **FatalExecutionEngineError**), usually after a short delay which is consistent with the GC discovering corrupted object references introduced by **cpblk**. The boundary of the successful vs. crash behavior is exact at the LOH threshold size of 85,000 bytes.

Repro the same **cpblk** SOH/LOH disparity on all configs: 32-/64-bit mode, Debug/Release, JIT optimization on/off.

Demonstration code follows.
```C#
public class c_int { public int i; }
public struct foo { public c_int obj; long a, b, c; }

static void Main()
{
    int objHdr = IntPtr.Size * 3, 
         cb = IntPtr.Size == 4 ? 28 : 32, N;

    // SOH test: OK
    test(N = (84999 - objHdr) / cb, N * cb);

    // LOH test: FAIL
    test(N = 85000 / cb + 1, N * cb);
}

static Random rnd = new Random();
```
Test outer loop (infinite):
```C#
static void test(int N, int cb_tot)
{
    Console.WriteLine("N={0} cb-tot={1}", N, cb_tot);
    Console.WriteLine("---iter--- -gen- ----total-alloc----");

    var data = new List<foo[]>();

    for (int i = 0; ; report(i, data))
        while (++i % 1000 != 0)
            iter(data, N, cb_tot);
}
```
Single test iteration. An array is created in either the SOH or LOH, as configured above in `Main()`. Half the time, the object references in the array are populated with new SOH objects. The other half of the time they are stolen from some other previous array. Note that, regardless of the SOH/LOH status of the array itself, the contained-objects referenced inside the array are always SOH.
```C#
static void iter(List<foo[]> data, int N, int cb_tot)
{
    var dst = new foo[N];
    data.Add(dst);

    if ((data.Count & 1) == 1)
    {
        for (int i = 0; i < dst.Length; i++)
            dst[i].obj = new c_int { i = i };
    }
    else
    {
        var src = data[rnd.Next(data.Count - 1)];

        Unsafe.CopyBlock(
            ref Unsafe.As<foo, byte>(ref dst[0]),
            ref Unsafe.As<foo, byte>(ref src[0]),
            (uint)cb_tot);

        // touch copied refs to test them
        for (int i = 0; i < dst.Length; i++)
            if (dst[i].obj.i != i)
                throw new Exception();
    }
}
```
Diagnostic output method:
```C#
static void report(int iter, List<foo[]> data)
{
    long gcMem = GC.GetTotalMemory(false);

    Console.WriteLine("{0,10}  {1,4}  {2,18:#,###}", iter, GC.CollectionCount(0), gcMem);

    if (gcMem > (IntPtr.Size == 4 ? 1610612736L : 10737418240L))
    {
        data.Clear();

        do
        {
            Console.WriteLine("Collect {0:#,###}", gcMem);
            GC.Collect(int.MaxValue, GCCollectionMode.Forced, true, true);
            GC.Collect();
            GC.WaitForPendingFinalizers();
        }
        while ((gcMem = GC.GetTotalMemory(true)) > 5L * 1024 * 1024 * 1024);
    }
}
```
I didn't spend much time writing this up because I presumed the issue will be dismissed as "by design." That is, it's perilously easy to just assert that "**cpblk** *may not* be used over data containing managed references, period," and be done with it. As the Henny Youngman joke goes, "I told the doctor it hurts when I do *this*, and he said, 'Well don't do that.'" It would be a sad result, since **cpblk** does seem to work just fine in generation-0.

Also, even if that is the decision, the documentation should be improved since the existing specs are unclear, not only with regard to this LOH/SOH effect on **cpblk**, but even whether **cpblk** is intended to support blocks containing managed references or not.

And finally, if this operation is deemed not-supported, it would be nice to understand why it appears to work for the SOH. For example, as the code above shows, after hitting a memory limit the GC memory seems to be **fully recovered** each time the `List<foo>` is cleared, which seems to suggest that the GC is indeed aware of the **cpblk**-copied references.

**Comment by jkotas** [comment]
>  cpblk may not be used over data containing managed reference

Correct.

> it would be nice to understand why it appears to work for the SOH.

In the current GC implementation, the most critical part that cpblk is missing are card updates. The card updates are only done for references from older generation to younger generations. Thus you are most likely going to hit crash with missing cards when the references are pointing to Gen0.

> the documentation should be improved

Agree.

**Comment by glenn-slayden** [comment]
@jkotas  Referring your [comment](https://github.com/dotnet/corefx/issues/5474#issuecomment-172378582) in a related conversation, it remains unclear to me whether the `stobj` instruction is GC-savvy or not. In other words, is the following generic function sanctioned for any/all `T`, value-types and reference handles alike?

```CIL
.method static void CopyOneElement<T>(!!T[] dst, int32 i_dst, !!T[] src, int32 i_src)
{
    ldarg dst
    ldarg i_dst
    ldelema !!T        // note: ldelema̲
    ldarg src
    ldarg i_src
    ldelem !!T
    stobj !!T          // <-- GC safe?
    ret
}
```
Unlike `cpblk`, the `stobj` instruction _does_ indeed require a type token, so I'm hoping for a better outcome on this one.

**Comment by jkotas** [comment]
Yes, `stobj` is doing the proper GC tracking.

**Comment by glenn-slayden** [comment]
@jkotas Fantastic, thanks!

**Comment by glenn-slayden** [comment]
@jkotas Indeed, with `stobj` I'm seeing what I believe are the GC notification calls: 

```cil
    ldelema !T
    dup
    sizeof !T
    dup
    add
    add
    ldloc psrc
    sizeof !T
    dup
    add
    add
    ldobj !T
    stobj !T
00007FF890FB4B62 mov rdx,qword ptr [r12+10h]
00007FF890FB4B67 lea rcx,[rsi+10h]
00007FF890FB4B6B call 00007FF8F05A3E20          <-- GC notify

    dup
    sizeof !T
    add
    ldloc psrc
    sizeof !T
    add
    ldobj !T
    stobj !T
00007FF890FB4B70 mov  rdx,qword ptr [r12+8]
00007FF890FB4B75 lea  rcx,[rsi+8]
00007FF890FB4B79 call 00007FF8F05A3E20          <-- GC notify

    ldloc psrc
    ldobj !T
    stobj !T
00007FF890FB4B7E mov rdx,qword ptr [r12]
00007FF890FB4B82 mov rcx,rsi
00007FF890FB4B85 call 00007FF8F05A3E20          <-- GC notify
```

Beautiful amd64 generation, by the way. Never ceases to amaze me.

**Comment by glenn-slayden** [comment]
I also see that the x64 JIT is smart enough to **not** emit the GC notification calls for the generic instantiation of `!T` when it knows that `!T` is a value-type that does not contain any references.

That's great, of course, but it gets even more amazing when it somehow also correctly identifies as vacuous--and therefore eliminates--an explicitly-coded IL branch that depends on the *runtime value* of some arbitrary readonly static `bool` field "`IsReferenceOrContainsReferences`" in the method's enclosing generic `!T` class. The value of this field is manually pre-computed by the respective `.cctor` and was intended as part of a (now-obviously failed) campaign to supposedly improve on JIT results.

This JIT behavior was so spectacular to me that I had to actually go ahead and confirm that it is only by virtue of the static field's `initonly` specification (yes, indeed, this is the case) that the subsequent method JITting is able obtain this aggressive, optimal result. Very great stuff here; I should have guessed.

**Comment by AndyAyersMS** [comment]
@glenn-slayden seems like this issue can be closed?

**Comment by glenn-slayden** [comment]
@AndyAyersMS The reason @jkotas had kept this issue open was as a **documentation bug** against the IL **cpblk** instruction.

Namely, that it can only be used to copy 'blittable' memory, i.e., memory regions that do not contain any GC handles (object references).  Or, put conversely, **cpblk** must **_not_** be used to copy memory containing object references.
