### ISSUE TITLE
Transport feed URLs getting slightly munged, breaking CoreCLR release/2.2 build

### ISSUE THREAD

**Issue by MattGal** [dotnet/coreclr#20114]
@dotnet-mc-bot commented on [Mon Sep 24 2018](https://github.com/dotnet/core-eng/issues/4226)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055537
  - **Agent:** DDVSOWINAGE100
  - **Error log:** C:\Program Files\dotnet\sdk\2.1.201\NuGet.targets(0,0): error : Unable to load the service index for source https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02/DotNet-CoreClr-Master-1832/platform/pkg/i...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055538
  - **Agent:** DDVSOWINAGE054
  - **Error log:** C:\Program Files\dotnet\sdk\2.1.201\NuGet.targets(0,0): error : Unable to load the service index for source https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02/DotNet-CoreClr-Master-1832/platform/pkg/i...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055541
  - **Agent:** DDVSOWINAGE057
  - **Error log:** E:\A\_work\0\s\Tools\SyncCloudContent.targets(0,0): error : Request https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02?restype=container&comp=list&prefix=DotNet-CoreClr-Master-1832/platform/TestNative...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055539
  - **Agent:** DDVSOWINAGE055
  - **Error log:** C:\Program Files\dotnet\sdk\2.1.201\NuGet.targets(0,0): error : Unable to load the service index for source https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02/DotNet-CoreClr-Master-1832/platform/pkg/i...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055540
  - **Agent:** DDVSOWINAGE056
  - **Error log:** C:\Program Files\dotnet\sdk\2.1.201\NuGet.targets(0,0): error : Unable to load the service index for source https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02/DotNet-CoreClr-Master-1832/platform/pkg/i...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055542
  - **Agent:** DDVSOWINAGE058
  - **Error log:** E:\A\_work\0\s\Tools\SyncCloudContent.targets(0,0): error : Request https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02?restype=container&comp=list&prefix=DotNet-CoreClr-Master-1832/platform/TestNative...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055543
  - **Agent:** DDVSOWINAGE060
  - **Error log:** E:\A\_work\0\s\Tools\SyncCloudContent.targets(0,0): error : Request https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02?restype=container&comp=list&prefix=DotNet-CoreClr-Master-1832/platform/TestNative...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055544
  - **Agent:** DDVSOWINAGE077
  - **Error log:** E:\A\_work\0\s\Tools\SyncCloudContent.targets(0,0): error : Request https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02?restype=container&comp=list&prefix=DotNet-CoreClr-Master-1832/platform/TestNative...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055545
  - **Agent:** DDVSOWINAGE078
  - **Error log:** E:\A\_work\0\s\Tools\SyncCloudContent.targets(0,0): error : Request https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02?restype=container&comp=list&prefix=DotNet-CoreClr-Master-1832/platform/TestNative...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055546
  - **Agent:** DDVSOWINAGE079
  - **Error log:** E:\A\_work\0\s\Tools\SyncCloudContent.targets(0,0): error : Request https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02?restype=container&comp=list&prefix=DotNet-CoreClr-Master-1832/platform/TestNative...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055547
  - **Agent:** DDVSOWINAGE080
  - **Error log:** E:\A\_work\0\s\Tools\SyncCloudContent.targets(0,0): error : Request https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02?restype=container&comp=list&prefix=DotNet-CoreClr-Master-1832/platform/TestNative...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2055548
  - **Agent:** DDVSOWINAGE081
  - **Error log:** E:\A\_work\0\s\Tools\SyncCloudContent.targets(0,0): error : Request https://dotnetbuildoutput.blob.core.windows.net/coreclr-platform-2-2-20180924-02?restype=container&comp=list&prefix=DotNet-CoreClr-Master-1832/platform/TestNative...

@jcagme, @markwilkie

---

@MattGal commented on [Mon Sep 24 2018](https://github.com/dotnet/core-eng/issues/4226#issuecomment-424060407)

This isn't actually a network build failure, rather the build is trying to restore from a Sleet feed at:

`https://dotnetbuildoutput.blob.core.windows.net/coreclr-release-2-2-20180924-02/DotNet-CoreClr-Master-1832/...`
But the actual bits are getting pushed into:
`https://dotnetbuildoutput.blob.core.windows.net/coreclr-release22-20180924-02/dotnet-coreclr-master-1832/`

I'll track this issue down and make it into a CoreCLR bug (or fix it if it's cheap / fast)

**Comment by MattGal** [comment]
@GrabYourPitchforks I think this was caused by your changes to support feature/utf8string.  Basically, when the test builds happen they're looking for one container name (in the above example coreclr-release-2-2-20180924-02) when in reality some hyphens have been removed in the actual value.  

It looks like while ParentContainerName was indeed originally just "ContainerName", it must have been getting some kind of tweaking itself.  I believe simply providing the same value for PB_ContainerName may solve the problem easily; see me if you need any clarification.

**Comment by MattGal** [comment]
I think I know what to look for at least;  While my previous suggested fix should unblock you either way, I bet there's someone changing '.' and '/' into empty char instead of -, like the PB_SanitizedContainerName thing does.

**Comment by GrabYourPitchforks** [comment]
I'll update the .ps1 file and see how it goes.

**Comment by GrabYourPitchforks** [comment]
I found one more build definition where the .ps1 file was duplicated. Updated it and we'll see how it goes.

**Comment by GrabYourPitchforks** [comment]
Builds are now succeeding (see https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2061522). Closing issue. Ping me if things go sideways again.

**Comment by MattGal** [comment]
Very close, the values are now only off by one hyphen (the test build is still swapping the / in release/2.2 for a '-', while the real build for an empty char.

**What the test build is trying to load:**
https://dotnetbuildoutput.blob.core.windows.net/coreclr-release-22-20180926-02/DotNet-CoreClr-Master-1832/Release/pkg/index.json

**Actual:**
https://dotnetbuildoutput.blob.core.windows.net/coreclr-release22-20180926-02/DotNet-CoreClr-Master-1832/Release/pkg/index.json

See https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=2062828&view=logs for this happening today.

**Comment by GrabYourPitchforks** [comment]
@MattGal Should I just special-case the "release/" prefix? It seems weird that some of our branches (feature/utf8string) expect the slash to be converted to a hyphen, and some branches (release/2.2) expect it to be removed entirely. Since our transforms don't follow a common convention special-casing might be the best option.

**Comment by MattGal** [comment]
@GrabYourPitchforks Anything using the master branch pipebuild here is using the same convention to modify ContainerName (I originally made this change specifically for this type of problem).  You're welcome to pick any convention you like as long as it's consistent; I'll provide my opinion and let you know if you fixed it, but the decision needs to be done by whoever owns the CoreCLR build on the team.

**Comment by markwilkie** [comment]
@GrabYourPitchforks - Curious why you felt the need to email "heavy hitters"....  If we as a team are not handling this right in some way, we'd certainly like to improve.  Thoughts?

**Comment by GrabYourPitchforks** [comment]
@markwilkie Matt was OOF and recommended offline that I email the wider team since you'd all be more responsive.

**Comment by MattGal** [comment]
I believe this issue can be closed now btw, my most recent change seems to both satisfy prod con (https://mc.dot.net/#/netcore/22/latest ) and Levi's one-off build requirements.
