### ISSUE TITLE
How to dump a .net core 2.0 console application in Linux Docker's container?

### ISSUE THREAD

**Issue by ZhiqiangTao** [dotnet/coreclr#20122]
I have an .net core 2.0 console application running in a Linux docker's container, some keys env as below:

1.docker base image:**FROM microsoft/dotnet:2.0-runtime**
2.Linux version:centos 7.2

Now, I want to investigate some problems, so I need to dump **in the docker inside**
Note: the .net core application in the docker container is running all the time, and **not crash**

**Comment by mikem8361** [comment]
You can debug live/attach to your app from another shell running the same docker container or just run your app in the background.  lldb/SOS can be used to attach to the process and get the state of the managed threads/stacks: [doc](https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md#debugging-coreclr-on-linux). 

You can also use the "createdump" utility that comes with the runtime to generate a core dump from a running process: [doc](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md#configurationpolicy).

**Comment by ZhiqiangTao** [comment]
thanks a lot

**Comment by alexsandro-xpt** [comment]
@mikem8361 if I want to generate dump at all crash inside a container and send it to another place like a container volume or whatever to analyze later. The question is, how can I generate it at every crash time?

**Comment by mikem8361** [comment]
Are you asking how to configure the runtime to automatically generate core dumps on unhandled exceptions or other crashes? See [doc](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md#configurationpolicy).

You can control with env vars the path/coredump name as long as the .NET Core app has access to this path.
