### ISSUE TITLE
Allow disabling strong name validation for an assembly per-process

### ISSUE THREAD

**Issue by lostmsu** [dotnet/coreclr#20128]
.NET Framework allowed to skip strong name validation via a user-wide setting for the development purposes. It poses known security issue, as not only the program, that is being developed will skip validation for a specific assembly/public key pair, but also all of the installed software run by the same user.

This feature request proposes to let processes control their own validation, so that in a debug build of MyApp I could reference PartiallySigned.dll, and have something like
```csharp
#if DEBUG
StrongNameValidation.SkipFor("PartiallySigned.dll", publicKey: "abcd...1234");
#endif

**Comment by jkotas** [comment]
This feature does not make sense for .NET Core. .NET Core does not ever do strong name validation. 

Also, strongnames should not be used for security. All strong name documentation has warnings about it e.g. see https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies.
