### ISSUE TITLE
CultureInfo without user overrides

### ISSUE THREAD

**Issue by psmolinsky** [dotnet/coreclr#2014]
How to get a `CultureInfo` without user overrides, please? In full .NET Framework there is [constructor with such parameter](https://msdn.microsoft.com/en-us/library/7h898a16.aspx) or [GetCultureInfo method](https://msdn.microsoft.com/en-us/library/yck8b540.aspx).

**Comment by tarekgh** [comment]
@psmolinsky could you tell abut the scenario you need this for? usually the apps should work with whatever user chose but I am curious to know your scenario that don't need the user overrides.

**Comment by psmolinsky** [comment]
Any web application running on server? Or if a developer runs such application locally, no matter what his overrides are, application should not use his overrides.

**Comment by tarekgh** [comment]
@psmolinsky usually servers don't override the default user settings (and if they override the settings this will be intention to be used). developers run the application locally should use the user overrides because this is the choice of the user.

Also note that user overrides is interesting only for current culture. so if using any other culture there will not be any user overrides. 

any server-client apps want to have consistent results between the server and client, they should use fixed data (custom data) because it is not guaranteed the server and the client machines will have the exact version of the data anyway even if we turn off the user override. 

my question, did you run into any specific scenario that required not using the user overrides?

**Comment by psmolinsky** [comment]
Ok, you are right about server-side applications, but...

Example specific scenario: a customer asks a developer to develop something which uses formatting of values in some web application. Developer has his local overrides and doesn't realize it. He finishes his job and value is formatted correctly on his machine. However when application is deployed to the server without overrides, customer will be angry. You can find more scenarios like this, which I guess are not critical, but it would make sense to use `CultureInfo` without overrides.

Additionally in .NET Core there is already constructor with `useUserOverride` parameter, but it is `internal`. Thus why not to expose it and let consumers decide?

**Comment by tarekgh** [comment]
The scenario you have mentioned can happen even when the user override is off. this can happen if you have different versions of the OS running the dev and server machines. like Windows 8.x and Windows 10 has different globalization data, Windows and Linux has different data too. this is why in my last reply I mention the comment 

> any server-client apps want to have consistent results between the server and client, they should use fixed data (custom data) because it is not guaranteed the server and the client machines will have the exact version of the data anyway even if we turn off the user override. 

other scenario is people can install custom cultures which can override the whole culture on Windows machines and at that time even turning off user override will not really help.

The guide lines is, if you want to guarantee the behavior then you need to use your fixed format. this is why we recommend people for example when they persist a date string to format the dates using the Invariant culture or format it in the ISO format to guarantee parsing it back to work with any problem. 

We intentionally did expose the other constructor in coreclr for the following reasons:
- The issue I mentioned before which is some apps decide to turn off the user override and the user expected to see his/her settings reflected in the application. sometimes people get confused between 2 apps running on the same machine and one reflecting the user settings and the other is not
- if the user decided to change the default settings, then the user really want to see the customized settings reflected on the apps.
- We need to find compelling scenario which really need this and so far we didn't really find any real one.

**Comment by psmolinsky** [comment]
Ok, it makes sense. Thanks for explanation.
