### ISSUE TITLE
Don't allocate the AwaitTaskContinuation when scheduling continuations via the IAsyncStateMachineBox

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#20155]
Today when we're about to schedule the async state machine continuation (because it can't be inlined), we allocate an extra object that we then queue to the thread pool here https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs#L790

We can avoid this completely by making `IAsyncStateMachineBox` and [AsyncStateMachineBox](https://github.com/dotnet/coreclr/blob/598fca6348cbedc9cadb92aabf00b0f6f181bf83/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilder.cs#L520)  implement `IThreadPoolWorkItem`. 

It would avoid the allocation in the very common case where we're awaiting a tcs that has the `TaskCreationOptions.RunContinuationsAsynchronously` flag set.

PS: I was going to take a stab at this change but I deleted my coreclr repo to save space 😄 

cc: @stephentoub

**Comment by stephentoub** [comment]
Good idea. I'll take a look.

**Comment by davidfowl** [comment]
Next time 😄. I'll be looking for more opportunities 😄
