### ISSUE TITLE
Non-finalizing TaskExceptionHolder type?

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#20150]
If a `Task` is `await`ed (e.g. `ITaskAwaiter`) and faults the exception will always be surfaced so the exception could be stored in a `TaskExceptionHolder` type that doesn't have a finalizer?

/cc @stephentoub

**Comment by juliusfriedman** [comment]
I like the idea, in the interim I believe we could also choose to call SuppressFinalize in the catch block which would provide almost the same result in the short term.

**Comment by benaadams** [comment]
Obv in the grand scheme of throwing exceptions; it might not be a huge factor

**Comment by stephentoub** [comment]
How do you propose to make that happen in a way that doesn't negatively impact success cases? i.e. without adding interlockeds or increasing the task size?

**Comment by benaadams** [comment]
>  or increasing the task size?

Move the finalizable part to a derived class of `TaskExceptionHolder`?

Not sure how to detect if it has an awaited continuation here though (to switch the type created based on it)

https://github.com/dotnet/coreclr/blob/28a8d423efc79c1cb2b23fa21747c5f7c5f7a057/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L1847

Don't think that would work for Tasks that complete synchronously either though? (Only ones that resume)

**Comment by stephentoub** [comment]
> Move the finalizable part to a derived class of TaskExceptionHolder?

Sure, but how do you know when to use the derived type instead?  The awaiter would somehow need to communicate to the Task that it's being awaited.  Where does that information get stored in a way that doesn't negatively impact success cases?  And how does that information get stored in a thread-safe way that doesn't negatively impact success cases?

**Comment by stephentoub** [comment]
> Not sure how to detect if it has an awaited continuation here

Ah, you're suggesting that the answer to my questions of "where does that information get stored / how does that information get stored in a thread-safe way" is that the Task would look at its continuations list to see if there's a known await continuation object there, and if there is, treat that as meaning that the exception will definitely be observed and it could allocate the non-finalizable holder instead?

That makes sense, except that there's no guarantee that such an awaiter will actually observe the exception, e.g. `task.GetAwaiter().OnCompleted(() => { /* nop */ });`.  Given the downsides, I'm not seeing the upsides here being worthwhile... agree? disagree?

**Comment by benaadams** [comment]
>  is that the Task would look at its continuations list to see if there's a known await continuation object there, and if there is, treat that as meaning that the exception will definitely be observed and it could allocate the non-finalizable holder instead?

Yes; also when its only a single await continuation (common path); rather than list.

> `e.g. task.GetAwaiter().OnCompleted(() => { /* nop */ });`

Never thought of doing that. Now you are just giving me ideas... 😉 

Could additionally check the Action's Target and Method; though that's probably going to be slow...

> Given the downsides, I'm not seeing the upsides here being worthwhile...

The upside I see is if there is a whole chain of awaits then their will be a cascade of exceptions being thrown, caught and new ones thrown; so it would reduce the cost. Though likely its trivial in comparison to the exceptions being thrown and caught.

>  agree? disagree?

For a synchronously completing awaited Task based method this wouldn't help? As the Task would error before the continuation was added?

In which case this wouldn't be very helpful for the fast-path (of the slow exception path) anyway?

**Comment by stephentoub** [comment]
> For a synchronously completing awaited Task based method this wouldn't help? As the Task would error before the continuation was added?

Correct

**Comment by benaadams** [comment]
meh :)
