### ISSUE TITLE
Enable regular test runs of CoreCLR tests in unloadable AssemblyLoadContext

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#20168]
To make sure that new changes don't break the unloadability support, we need to enable regular (e.g. nightly) test runs where all pri-1 CoreCLR tests are executed inside of an unloadable AssemblyLoadContext. We will also need to have an exclusion list since some tests are not compatible with the unloadability (they e.g. start threads with infinite loops).

**Comment by tommcdon** [comment]
@janvorli This item looks like it is tracking assembly loader coreclr tests so moving to the area-AssemblyLoader path.  If there is something diagnostic specific please let us know.

**Comment by janvorli** [comment]
All of the necessary parts are done, so the last remaining piece is to add the lab test runs. 
Locally, the tests can be run using `tests/runtest.cmd/sh` with additional argument `/runincontext`. All that this argument does is that it sets `CLRCustomTestLauncher` env variable to point to 'tests/scripts/runincontext.cmd/sh', `__RunInUnloadableContext` env variable to 1 and timeout to 20 minutes.

**Comment by janvorli** [comment]
Fixed by #25325
