### ISSUE TITLE
Stacktrace formatting needs to be aware of collectible types

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#20179]
The cache in https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.CoreCLR.cs assumes that assembly metadata are not ever unloaded. It is not the case for collectible assemblies.

**Comment by josalem** [comment]
Update strategy:
- [ ] Update `GetSourceLineInfo` in CoreFX with an overload that accepts a `Reflection.Reflection.Assembly` but doesn't use it. - [code](https://github.com/josalem/corefx/blob/stacktrace-cache-unloading-coreclr20179-prechange/src/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.CoreCLR.cs)
- [ ] Update CoreCLR to collect managed assembly objects when walking the stack and calls new form of `GetSourceLineInfo`. - [code](https://github.com/josalem/coreclr/blob/stacktrace-cache-unloading-20179/src/System.Private.CoreLib/src/System/Diagnostics/StackFrameHelper.cs)
- [ ] wait for new version of CLR to be used by corefx
- [ ] update CoreFX to remove old version of `GetSourceLineInfo` and use `ConditionalWeakTable<Assembly, MetadataReaderProvider>` internally. - [code](https://github.com/josalem/corefx/blob/stacktrace-cache-unloading-coreclr20179/src/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.CoreCLR.cs)

CC - @janvorli

**Comment by josalem** [comment]
All phases have been merged in!
