### ISSUE TITLE
We should obsolete the String.Copy method

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/coreclr#20195]
The `String.Copy` static method takes an input string instance and duplicates it, creating a new reference and copying the original contents into the new object. The method is contracted [per MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.string.copy) to return a new object. (Contrast this with `String.Clone`, which returns the original instance.)

The only real use case for this is to create a new string instance so that the caller can use unsafe code to modify the string contents. However, as discussed in https://github.com/dotnet/coreclr/issues/14208 (the string deduping feature), it is technically illegal to mutate string instances. Furthermore, once the string deduping feature comes online, there'd no longer be any distinction between two different strings that happen to contain the same data. In that world it would make sense for `String.Copy` just to return its input argument as its return value.

Given all of this, there seems to be no legitimate use for the method going forward. I propose we obsolete it both to discourage new code from calling it and to signal to existing code bases that its behavior may imminently change.

One alternative would be to change its behavior to return its input argument _without_ also obsoleting it, but I do not believe this is a good course of action. It means that developers who rely on this method to return a duplicate instance (because they're about to perform an unsafe operation) won't ever be notified that the method is no longer safe for their particular use case.

**Comment by jkotas** [comment]
This is API proposal type of issue. Should this rather live in CoreFX?

**Comment by benaadams** [comment]
> It means that developers who rely on this method to return a duplicate instance (because they're about to perform an unsafe operation)

`string.Create<TState>(int length, TState state, SpanAction<char, TState> action)` formalizes the mutate newly allocated zero'd string prior to use pattern; while introducing safety via the Span and ensuring its not used prior to mutation.

For passing to native code which may mutate the string; shouldn't one of the `Marshal.StringToXxx` methods (+ free) be used instead for a defensive copy? 

Does the default p/invoke marshaller copy the string anyway?

**Comment by GrabYourPitchforks** [comment]
Moved to https://github.com/dotnet/corefx/issues/32563.
