### ISSUE TITLE
Implement a plugin for loading CoreCLR debugger extensions into LLDB

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/coreclr#202]
We need to be able to debug managed code in CoreCLR that is running on Linux and Mac. For this purpose we need to implement a (command) plugin for LLDB that will allow loading CoreCLR debugger extensions (SOS) into LLDB.

This plugin should implement a debugger interface/transport that will allow SOS extensions to access LLDB’s APIs in order to examine debugee’s state.

@mikem8361 Could you please provide name of your feature branch once you move the code that your are currently working on to GitHub?

**Comment by mikem8361** [comment]
soscommand1
