### ISSUE TITLE
Windows x86 Release build failing in DacTableGen

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#2022]
e.g. http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x86_release_windows_nt_prtest/13/console

/cc @mmitche

**Comment by jkotas** [comment]
I am not able to reproduce this on my machine - perhaps the CI is using a different version of the compiler than I got.

However, I have submitted a PR that should fix it: https://github.com/dotnet/coreclr/pull/2025 . Is there a way how to make the CI to run x86 ret built on it?

**Comment by mmitche** [comment]
'@dotnet-bot test x86 windows release' should work.

Sent from my Windows Phone
________________________________

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/2025 + https://github.com/dotnet/coreclr/pull/2028
