### ISSUE TITLE
Infinite Loop in DBG_printf_gcc and DBG_printf_c99

### ISSUE THREAD

**Issue by marler8997** [dotnet/coreclr#20261]
In `DBG_printf_gcc` and `DBG_printf_c99` there is an infinite recursive loop that occurs if the thread calling it is not a PAL thread.  They both call `InternalGetCurrentThread` which in turn will create the thread data structures if it's not already a PAL thread, which in turn can print more debug, which will then call `InternalGetCurrentThread` again which in turn will print more debug and so on.

**Comment by RussKeldorph** [comment]
@janvorli

**Comment by janvorli** [comment]
@marler8997 thank you for reporting this. It seems we can fix it easily by not calling `InternalGetCurrentThread()` in the `DBG_printf_xxx` functions and passing NULL to `InternalEnterCriticalSection` and `InternalLeaveCriticalSection` instead. That would make these functions, resp the `ObtainCurrentThreadId` that these functions call, obtain the current thread id using platform calls (syscall or various pthread_xxx functions). Although it is slower, in this code path it doesn't matter.
I was wondering if you'd be interested in creating PR for such fix.

**Comment by marler8997** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/20267
