### ISSUE TITLE
Clear the ExecutionContext on Task after it executes

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#20273]
There's a scenario where you're caching data lazily that is computed asynchronously. Here's an example https://gist.github.com/davidfowl/94d1b7d60ad544289b5f60df4c8a6520. We have this global cache that stores asynchronously computed values, as a result it stores the `Task` itself in the cache so that multiple callers get the same value. As a result, the ExecutionContext is stored in the cache forever, which means async locals are stored forever.

We should clear the ExecutionContext after the task has executed.

**Comment by benaadams** [comment]
Good catch; we use `Task<T>` often as an async version of `Lazy<T>` so the EC will be cached generally forever
