### ISSUE TITLE
different behavior in dllimport in netcoreapp2.0 vs netstandard2.0 in Linux

### ISSUE THREAD

**Issue by roozbehid-ic** [dotnet/coreclr#20279]
I've found some strange behavior when targeting netstandard2.0 and cost me at least 10 hours to find easy/strange fix.

foo.c:

    #include <stdio.h>
    void foo(void)
    {
      puts("Hello, I'm a shared library");
    }

run following commands in your bash 
     
     gcc -c -fpic foo.c
     gcc -shared -o libfoo.so foo.o

     
test.csproj

      <Project Sdk="Microsoft.NET.Sdk">
      
        <PropertyGroup>
          <OutputType>Exe</OutputType>
          <TargetFramework>netstandard2.0</TargetFramework>
        </PropertyGroup>
      </Project>        

Program.cs

      using System;
      using System.Runtime.InteropServices;
      
      namespace cs
      {
          class Program
          {
              [DllImport("foo")]
              private static extern void foo();
      
              static void Main(string[] args)
              {
                 foo();
                  Console.WriteLine("Hello World!");
              }
          }
      }

So now if you run it with TargetFramework as netcoreapp2.0. It will work.

If you run it with TargetFramework as netstandard2.0 you will get an exception on foo module not found.

      Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'foo': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
      at cs.Program.foo()
      at cs.Program.Main(String[] args) in /mnt/d/Projects/test/bugtest/cs/Program.cs:line 13

What I experienced in my bigger project being compiled as netstandard2.0 was that with presence of foo.dll, it would generate "bad image format exception".
But renaming it to libfoo.so I would get "no module found" which was way more challenging as I was pointing the problem to my C++ code and probably something being wrong with it!

Anyway I know this is a console app so it should be netcoreapp2.0 but it is a common mistake that I do (and assume many others) which also end up in a binary that runs anyway! (if it is a wrong target why compiler does not warn?!)

-----------------------------
Additional info:
Ran in WSL (ubuntu 16.04)
dotnet --version : 2.1.104

**Comment by svick** [comment]
How are you running the project? When I try to run such a project with `dotnet run` on .Net Core 2.1.105, I get:

```
Unable to run your project.
Please ensure you have a runnable project type and ensure 'dotnet run' supports this project.
A runnable project should target a runnable TFM (for instance, netcoreapp2.0) and have OutputType 'Exe'.
The current OutputType is 'Exe'.
```

Does the issue still exist if the `DllImport` is in a .Net Standard library that's referenced from a .Net Core application?

**Comment by roozbehid** [comment]
I just type the name of program or dotnet test.dll

**Comment by roozbehid-ic** [comment]
I compile it then run it. There are registered (something) in linux that you can just type the name of file and run it.

**Comment by svick** [comment]
@roozbehid-ic If I understand what you're doing correctly, then you're not running the application right.

The valid ways of running a .Net Core application on Linux are:

1. `dotnet run`
2. If you have a framework-dependent application (which is the default), execute `dotnet publish` and then run the .dll through `dotnet`, e.g. `dotnet bin/Debug/netcoreapp2.0/publish/app.dll`.
3. If you have a self-contained application that specifies a Runtime Identifier, execute `dotnet publish` and then directly run the executable, e.g. `./bin/Debug/netcoreapp2.0/ubuntu.16.04-x64/publish/app`.

(Yes, it's complicated and it's unfortunate that it's too easy to run the application incorrectly. Hopefully, this will improve in the future, e.g. with https://github.com/dotnet/cli/issues/10061.)

**Comment by roozbehid-ic** [comment]
Yes the problem was not running it in those specified ways.
I am closing this issue and thanks
