### ISSUE TITLE
PMI assert in system.private.corelib

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#20284]
PMI now asserts when processing system.private.corelib on x64 checked:
```
;; complus_tieredcompilation=0
corerun d:\repos\jitutils\bin\pmi.dll prepall-quiet D:\repos\coreclr2\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\System.Private.CoreLib.dll
Assert failure(PID 560 [0x00000230], Thread: 20044 [0x4e4c]): Assertion failed 'HWIntrinsicInfo::lookupIns(intrinsic, baseType) != INS_invalid' in 'System.Runtime.Intrinsics.X86.Avx2:BlendVariable(struct,struct,struct):struct' (IL size 9)

    File: d:\repos\coreclr2\src\jit\hwintrinsicxarch.cpp Line: 827
    Image: D:\repos\coreclr2\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
```
possibly from #19420 

cc @fiigii @dotnet/jit-contrib

**Comment by fiigii** [comment]
@AndyAyersMS  #19420 added new overload APIs for these intrinsic. The JIT implementations and test cases are in https://github.com/dotnet/coreclr/pull/20210

**Comment by AndyAyersMS** [comment]
Are you saying this is an expected failure until we've merged #20210?

If so: in the (not too distant) future we may be adding PMI runs to the CI, so we'll have to stage changes like this differently.

**Comment by fiigii** [comment]
> Are you saying this is an expected failure until we've merged

Yes, it probably is expected (but I am not very familiar with PMI tests). In the current master, `Avx2:BlendVariable` has APIs on some types but temporarily no JIT implementation.

> so we'll have to stage changes like this differently.

Recently, we are changing some APIs of hardware intrinsic https://github.com/dotnet/coreclr/issues/20062. Once the work gets done, we won't have this kind of failures.

**Comment by fiigii** [comment]
@AndyAyersMS #20210 is merged, could you please try again?

**Comment by AndyAyersMS** [comment]
Trying... it now.

I am currently hitting an assert in crossgen now. Let me see if this repros with a clean build...
```
D:\repos\coreclr\bin\Product\Windows_NT.x64.Checked>crossgen System.Private.CoreLib.dll
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.


Assert failure(PID 10924 [0x00002aac], Thread: 22892 [0x596c]): Assertion failed 'm_rsCompiler->lvaDoneFrameLayout < Compiler::FINAL_FRAME_LAYOUT' in 'DomainNeutralILStubClass:IL_STUB_PInvoke(int,ref,ref,byref,ref,byref,byref):bool' (IL size 361)

    File: d:\repos\coreclr\src\jit\regset.cpp Line: 110
    Image: D:\repos\coreclr\bin\Product\Windows_NT.x64.Checked\crossgen.exe
```

**Comment by AndyAyersMS** [comment]
Looks like the above was a transient issue.

And PMI is ow working on corelib again,.

**Comment by fiigii** [comment]
Thanks!
