### ISSUE TITLE
RandomNumberGenerator on DNX 5.0

### ISSUE THREAD

**Issue by angelsix** [dotnet/coreclr#2029]
Is there a plan in the RC to have the RandomNumberGenerator available in DNX50. Right now its only in 451.

**Comment by bartonjs** [comment]
@angelsix `RandomNumberGenerator` is available from the `System.Security.Cryptography.Algorithms` package.  There was an older `System.Security.Cryptography.RandomNumberGenerator` package, but we merged several crypto packages down into a smaller set.

**Comment by weshaggard** [comment]
I believe this question has been answered so closing this issue. If there are follow-ups please file an issue in the corefx repo about it.
