### ISSUE TITLE
Port CoreCLR SOS debugger extension from Windows to Linux and Mac

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/coreclr#203]
We currently have a number of debugger commands implemented in the SOS debugger extension on Windows which can be used to debug managed applications and examine their state in WinDbg. We need to port them to Linux and Mac and integrate them with LLDB. Note: this work depends on “Implement a plugin for loading CoreCLR debugger extensions into LLDB” (https://github.com/dotnet/coreclr/issues/202).

Here is a list of most useful debugger extension commands in SOS that we need to port:

IP2MD
CLRStack
PrintException
DumpLog
DumpObj
DumpStackObjects
DumpDomain
DumpMT
DumpMD
Name2EE
BPMD

@mikem8361 Could you please provide name of your feature branch once you move the code that your are currently working on to GitHub?

**Comment by mikem8361** [comment]
soscommand1 is the branch for these changes.

**Comment by Maoni0** [comment]
Would be great to port !VerifyHeap as well - it's an extremely commonly used command.

**Comment by mikem8361** [comment]
All the commands except for Name2EE, BPMD and VerifyHeap were implemented by merge #500. See issue #506
