### ISSUE TITLE
Cleanup /**/ style comments in C#

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#20330]
There are still about 50 comments like
```
            /***
             * Div96By32
             *
             * .....
             ***********************************************************************/
```
in System.Private.Corelib. These should all be converted to XML format (or removed, if they are not worth keeping) to be consistent with our other C# code.

**Comment by JorgeAndd** [comment]
Could I work on this one?
Can you show me any example of the correct format for the comments?

**Comment by ablanchet** [comment]
According to the [design guideline here](https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/clr-jit-coding-conventions.md#7.1.1) I think the intended format of this particular example would be:
```csharp
// Div96By32
//
// .....
```

**Comment by ablanchet** [comment]
I think the intended format would be a classic xml comment like this: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments

In this particular example the original comment in the codebase is: 
```csharp
/***
 * Div96By32
 *
 * Entry:
 *   bufNum - 96-bit dividend as array of ULONGs, least-sig first
 *   ulDen   - 32-bit divisor.
 *
 * Purpose:
 *   Do full divide, yielding 96-bit result and 32-bit remainder.
 *
 * Exit:
 *   Quotient overwrites dividend.
 *   Returns remainder.
 *
 * Exceptions:
 *   None.
 *
 ***********************************************************************/
private static uint Div96By32(ref Buf12 bufNum, uint ulDen)
```

and should have been something like:
```csharp
/// <summary>
/// Do full divide, yielding 96-bit result and 32-bit remainder.
/// </summary>
/// <param name="bufNum">96-bit dividend as array of ULONGs, least-sig first</param>
/// <param name="ulDen">32-bit divisor</param>
/// <returns>remainder</returns>
private static uint Div96By32(ref Buf12 bufNum, uint ulDen)
```
