### ISSUE TITLE
UTF8ToUnicode doesn't employ fallback replacement on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#2037]
Small repro:
```C#
using System;
using System.Reflection;

class Test
{
    [StringValue("\uDFFF")]
    static void Main()
    {
        foreach (var ca in typeof(Test).GetTypeInfo().GetDeclaredMethod("Main").CustomAttributes)
        foreach (char c in (string)ca.ConstructorArguments[0].Value)
            Console.WriteLine("{0:X2}", (int)c);
    }
}

[AttributeUsage(AttributeTargets.Method)]
class StringValueAttribute : Attribute
{
    public string Text;
    public StringValueAttribute(string text) { Text = text; }
}
```
On Windows, this prints out:
```
FFFD
FFFD
```
On Linux, however, it prints out:
```
DFFF
```
This appears to be due to UTF8ToUnicode (which is used as part of MultiByteToWideChar, which is used as part of StringObject::NewString, which is used in attribute parsing) not falling back to 0xFFFD for each invalid code unit, which MultiByteToWideChar on Windows does.

cc: @jkotas, @janvorli, @ellismg

**Comment by janvorli** [comment]
@wtgodbe is working on replacing the UTF8ToUnicode by a port from the managed version that we have in mscorlib. The issue should get fixed by that.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/3809 should resolve this.

**Comment by stephentoub** [comment]
This shouldn't be closed until we remove the ActiveIssue from the corresponding test.
