### ISSUE TITLE
Bash - Better to use #!/usr/bin/env bash

### ISSUE THREAD

**Issue by shanselman** [dotnet/coreclr#204]
Bash - Would it be better to #!/usr/bin/env bash...more portable? http://stackoverflow.com/a/16365367/6380

**Comment by poizan42** [comment]
I don't think the script uses any bashisms, so it should be changed to /bin/sh instead (posix actually doesn't make any guarantees on the path of either, so it's technically impossible to write a portable script...)

**Comment by shahid-pk** [comment]
but this is one of the best practices and one of the others is to avoid paths with spaces in them altogether so you do not have to hack scripts to deal with them.

**Comment by linquize** [comment]
Yes, switch to /bin/sh if not stick to bash.

**Comment by poizan42** [comment]
The clang probing (issue #250) i'm working on [here](https://github.com/poizan42/coreclr/compare/probe-clang) is going to need bash anyways, so if we are going to use that I think we should change it to `#!/usr/bin/env bash`.

**Comment by kangaroo** [comment]
I don't think we should restrict bash-isms, even the most obscure unix based distros have bash available these days.  

@shanselman Want to submit a PR? :+1:

**Comment by landonf** [comment]
@kangaroo Plenty don't ship it by default, though; no harm in reducing dependency load if it's not too much of a burden to do so.

Otherwise, +1 on #!/usr/bin/env from a FBSD perspective.

**Comment by kangaroo** [comment]
@landonf I agree many don't ship by default. I just meant this one doesn't seem like a dependency to avoid just for dependencies sake. If we have a good reason to use bashisms we should go ahead. It's not overly burdensome for other platforms.

That said. We shouldn't adopt it for no reason either.
