### ISSUE TITLE
Misc build failures in 'prodcon/coreclr/release/2.1/' - '20181014.01'

### ISSUE THREAD

**Issue by MattGal** [dotnet/coreclr#20424]
@dotnet-mc-bot commented on [Sat Oct 13 2018](https://github.com/dotnet/core-eng/issues/4389)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2115874
  - **Agent:** DDVSOLINUXAGE005
  - **Error log:** ERROR: Could not restore build tools correctly....

@jcagme, @markwilkie

---

@ChadNedzlek commented on [Mon Oct 15 2018](https://github.com/dotnet/core-eng/issues/4389#issuecomment-429972873)

This one looks like we are trying to call "pwsh", which is core powershell... on linux?  I don't know if that's expected and our machines are configured incorrectly, or if the build isn't supposed to be doing that.

---

@ChadNedzlek commented on [Mon Oct 15 2018](https://github.com/dotnet/core-eng/issues/4389#issuecomment-429991818)

This one looks like it's something wrong on our end.  Either the Alpine images aren't right, or the init-tools.sh isn't working, but it's nothing to do with the repo.

---

@MattGal commented on [Mon Oct 15 2018](https://github.com/dotnet/core-eng/issues/4389#issuecomment-429999773)

It's a segmentation fault in the cli, that didn't reproduce or get a dump:

```
018-10-14T05:09:25.6978741Z Restoring BuildTools version 2.1.0-rc1-03006-01...
2018-10-14T05:09:40.5675348Z /root/coreclr/init-tools.sh: line 152:    37 Segmentation fault      (core dumped) "$__DOTNET_CMD" restore "$__INIT_TOOLS_RESTORE_PROJECT" --no-cache --packages "$__PACKAGES_DIR" --source "$__BUILDTOOLS_SOURCE" /p:BuildToolsPackageVersion=$__BUILD_TOOLS_PACKAGE_VERSION /p:ToolsDir="$__TOOLRUNTIME_DIR" >> "$__init_tools_log"
2018-10-14T05:09:40.5675818Z ERROR: Could not restore build tools correctly.
2
```
Given this exact docker container and exact commit hash can successfully run, it's an intermittent CLI problem 

---

@MattGal commented on [Mon Oct 15 2018](https://github.com/dotnet/core-eng/issues/4389#issuecomment-430006385)

This issue is a segmentation fault (of which we've seen them before) in `dotnet restore`.  

I discussed this a bit with Eric Erhardt from CLI, and while the functionality involved is technically owned by the NuGet team, he suggested given it's a segmentation fault that this is most likely a CoreCLR issue.  As such, I'm going to move this to their repository for triage / discussion.  I've reclassified the failure from Misc to "DotNetRestore" as well.

**Comment by RussKeldorph** [comment]
Unfortunately, we didn't get to look into this at the time.  If this is still failing, please point to a newer failure.  As it is, there isn't much to go on.  I fear we are going to need to figure out to turn this into a crashdump before it is actionable.
