### ISSUE TITLE
Much worse debugging experience with Attach + Tier0 methods

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/coreclr#20421]
If you attach to a .NET Core 3.0 application (Release build), and try to debug a tier0 method, you can't see any locals or args. The jitter only reports that they're available in the prolog, so a debugger can't read them. That makes debugging optimized release builds much more difficult than it used to be.

Note that this is not a problem with tier1 methods. They work as before, locals and args are visible (most of the time).

Repro:

- Compile (release build) the following program with the latest .NET Core 3.0 daily build
- Start it from the console
- Attach to it
- Have a look in the locals window in Main() and in SomeMethod(). The locals/args are only shown if IP == END_OF_PROLOG
- Let it run so SomeMethod becomes a tier1 method
- Step into SomeMethod() again and notice that locals/args are shown

```C#
using System;

namespace ConsoleApp16 {
    class Program {
        static void Main(string[] args) {
            var p = new Program();
            Console.WriteLine("Attach to it now");
            Console.ReadKey();
            var array = new byte[] { 1, 2, 3, 4 };
            p.SomeMethod(0x1234, "hello", array);
            Console.WriteLine("Warming up");
            for (int i = 0; i < 1000; i++)
                p.SomeMethod(0x1234, "hello", array);
            Console.WriteLine("Should be tier1 now, if it's not, try iterating 10K times instead of 1K times");
            Console.ReadKey();
            p.SomeMethod(0x1234, "hello", array);
        }

        // if it's a tier0 method or if MethodImplOptions.NoOptimization is enabled, it's not possible to
        // see the locals and args except when it's stopped right after the prolog.
        // It works if it's a tier1 method (and I assume, but I haven't tested, if AggressiveOptimization is enabled)
        int SomeMethod(int magic, string str, byte[] array) {
            int ret = magic ^ str.Length ^ array.GetHashCode();
            Console.Write("");
            for (int i = 0; i < str.Length; i++) {
                ret += str[i];
                ret += str.GetHashCode();
            }
            ret += magic;
            Console.WriteLine($"{ret} {str}");
            return ret;
        }
    }
}
```

**Comment by BruceForstall** [comment]
@AndyAyersMS @kouvel @noahfalk

**Comment by AndyAyersMS** [comment]
@0xd4d thank you. I can confirm your report. This looks like an issue in the jit. 

At tier0 the jit only emits minimal ranges for the locals:
```
*************** Variable debug info
4 vars
  1(   UNKNOWN) : From 00000000h to 00000021h, in rdx
  2(   UNKNOWN) : From 00000000h to 00000021h, in r8
  3(   UNKNOWN) : From 00000000h to 00000021h, in r9
  0(   UNKNOWN) : From 00000000h to 00000021h, in rcx
```
while at tier1 there are full ranges:
```
*************** Variable debug info
9 vars
  1(   UNKNOWN) : From 00000000h to 00000011h, in rdx
  2(   UNKNOWN) : From 00000000h to 00000011h, in r8
  3(   UNKNOWN) : From 00000000h to 00000011h, in r9
  0(   UNKNOWN) : From 00000000h to 00000011h, in rcx
  3(   UNKNOWN) : From 00000011h to 0000001Bh, in r9
  4(   UNKNOWN) : From 0000003Eh to 0000004Ah, in rbp
  5(   UNKNOWN) : From 0000003Eh to 00000065h, in r14
  2(   UNKNOWN) : From 00000011h to 0000006Dh, in rsi
  1(   UNKNOWN) : From 00000011h to 0000006Dh, in rdi
```
Do you happen to know if this also happens in the 2.2 preview? If not, I can check.

It could be caused by some of the recent changes I made to how we handle locals in minopts. Will look deeper.

**Comment by 0xd4d** [comment]
Yes, seems to work with 2.2.0-preview3-27002-02

tier0:

```
; arg #0 (this) 00007FF89D292C10-00007FF89D292C3A RCX
; arg #1 (magic) 00007FF89D292C10-00007FF89D292C3A RDX
; arg #1 (magic) 00007FF89D292C3A-00007FF89D292D0B [RBP+18h]
; arg #2 (str) 00007FF89D292C10-00007FF89D292C3A R8
; arg #3 (array) 00007FF89D292C10-00007FF89D292C3A R9
; local #0 (ret) 00007FF89D292C3A-00007FF89D292D0B [RBP-14h]
; local #1 (i) 00007FF89D292C3A-00007FF89D292D0B [RBP-18h]
```

tier1:

```
; arg #0 (this) 00007FF89D293DB0-00007FF89D293DD5 RCX
; arg #1 (magic) 00007FF89D293DB0-00007FF89D293DD5 RDX
; arg #1 (magic) 00007FF89D293DD5-00007FF89D293E31 RDI
; arg #2 (str) 00007FF89D293DB0-00007FF89D293DD5 R8
; arg #2 (str) 00007FF89D293DD5-00007FF89D293E45 RSI
; arg #3 (array) 00007FF89D293DB0-00007FF89D293DD5 R9
; arg #3 (array) 00007FF89D293DD5-00007FF89D293DDF R9
; local #0 (ret) 00007FF89D293E02-00007FF89D293E0E RBP
; local #1 (i) 00007FF89D293E02-00007FF89D293E29 R14
```

**Comment by AndyAyersMS** [comment]
So the basic issue is that `CodeGen::siBeginBlock` never "opens" scopes for the locals at minopts (Tier0) because it expects to be tracking them with liveness, and we no longer track any locals in minopts.

What I had expected was that the locals would now be reported for debug the same way that we report untracked locals. So need to dig a bit further.

**Comment by AndyAyersMS** [comment]
And the answer to that follow-on question is that apparently untracked locals don't get reported in debug info for non-debug codegen modes -- eg in the following there is no debug information for `t` in `Main`:
```C#
using System;
using System.Runtime.CompilerServices;

struct T
{
    public double w;
    public double x;
    public double y;
    public double z;
    public int a;
    public int b;
}

class X
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static void U(ref T t)
    {
        t.a = 100;
    }

    public static int Main()
    {
        var t = new T();
        U(ref t);
        Console.WriteLine($"t.a = {t.a}");
        return t.a;
    }
}
```
Recent changes (#19103) in master have made all locals and args untracked at Tier0 to improve jitting time.

It seems plausible that the jit should emit debug info for these untracked locals, even if there will be places in the method where the values aren't current.

**Comment by AndyAyersMS** [comment]
@0xd4d PR to improve debug for Tier0 has just merged. Should appear in the nightly builds in a day or two. Would appreciate you taking another look and letting us know if things are in a good state for you or there are still issues.

**Comment by 0xd4d** [comment]
Is this fix in the latest build? I tried 3.0.100-alpha1-009708 and I still see no locals when using the above test program.

**Comment by AndyAyersMS** [comment]
It should be in the [latest nightly](https://github.com/dotnet/core-setup/blob/master/README.md#daily-builds) which is currently 3.0.0-preview1-27030-01.

**Comment by 0xd4d** [comment]
Thanks for the link, I used the other one. This one works for me too.

**Comment by AndyAyersMS** [comment]
@0xd4d Just to confirm -- you're now seeing the local variables and args in the debugger with 3.0.0-preview1-27030-01?

**Comment by 0xd4d** [comment]
Yes it works with the latest build from core-setup repo which is 3.0.0-preview1-27030-01 but not with the latest build from core-sdk repo which is an earlier version (3.0.0-preview1-27029-03)

**Comment by AndyAyersMS** [comment]
Thanks for confirming.

And thanks again for reporting this. Let us know if you see anything else amiss.
