### ISSUE TITLE
Port fix to Windows x86 watson dump

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/coreclr#20437]
On Windows X86, the fatal error infrastructure will capture the wrong context, which leads to dumps providing incorrect error location leading to a lot of wasted time.

Port fix for 110171 x86 VM failfasts lead to extremely confusing and misleading Watson dumps

**Comment by jkoritzinsky** [comment]
Was this fixed by #23289?

cc: @elinor-fung

**Comment by elinor-fung** [comment]
Yep, fixed by #23289
