### ISSUE TITLE
build error MSB3073 in x64_release_centos7.1_r2r_tst

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20457]
failed job: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_centos7.1_r2r_tst/2381/

failure log:
/mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/tests.targets(74,5): error MSB3073: The command "/mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/bin/tests/Linux.x64.Release/Tests/Core_Root/corerun /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/bin/tests/Linux.x64.Release/Tests/Core_Root/xunit.console.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/baseservices/compilerservices/baseservices.compilerservices.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/baseservices/exceptions/baseservices.exceptions.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/baseservices/multidimmarray/baseservices.multidimmarray.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/baseservices/threading/baseservices.threading.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/baseservices/varargs/baseservices.varargs.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/CoreMangLib/cti/CoreMangLib.cti.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/CoreMangLib/system/CoreMangLib.system.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Exceptions/Finalization/Exceptions.Finalization.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Exceptions/ForeignThread/Exceptions.ForeignThread.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/GC/API/GC.API.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/GC/Coverage/GC.Coverage.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/GC/Features/GC.Features.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/GC/LargeMemory/GC.LargeMemory.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/GC/Regressions/GC.Regressions.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/GC/Scenarios/GC.Scenarios.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/hosting/stress/hosting.stress.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/ArrayMarshalling/Interop.ArrayMarshalling.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/BestFitMapping/Interop.BestFitMapping.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/COM/Interop.COM.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/DllImportAttribute/Interop.DllImportAttribute.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/FuncPtrAsDelegateParam/Interop.FuncPtrAsDelegateParam.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/ICastable/Interop.ICastable.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/MarshalAPI/Interop.MarshalAPI.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/NativeCallable/Interop.NativeCallable.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/PrimitiveMarshalling/Interop.PrimitiveMarshalling.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/RefCharArray/Interop.RefCharArray.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/RefInt/Interop.RefInt.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/SimpleStruct/Interop.SimpleStruct.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/StringMarshalling/Interop.StringMarshalling.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/StructMarshalling/Interop.StructMarshalling.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Interop/StructPacking/Interop.StructPacking.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/BBT/JIT.BBT.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/CheckProjects/JIT.CheckProjects.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/CodeGenBringUpTests/JIT.CodeGenBringUpTests.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/Directed/JIT.Directed.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/Generics/JIT.Generics.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/IL_Conformance/JIT.IL_Conformance.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/Intrinsics/JIT.Intrinsics.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/jit64/JIT.jit64.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/Methodical/JIT.Methodical.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/opt/JIT.opt.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/Performance/JIT.Performance.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/Regression/JIT.Regression.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/RyuJIT/JIT.RyuJIT.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/JIT/SIMD/JIT.SIMD.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Loader/binding/Loader.binding.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Loader/classloader/Loader.classloader.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Loader/lowlevel/Loader.lowlevel.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Loader/multimodule/Loader.multimodule.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Loader/NativeLibs/Loader.NativeLibs.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Loader/regressions/Loader.regressions.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/Loader/versioning/Loader.versioning.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/readytorun/DynamicMethodGCStress/readytorun.DynamicMethodGCStress.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/readytorun/tests/readytorun.tests.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/reflection/DefaultInterfaceMethods/reflection.DefaultInterfaceMethods.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/reflection/GenericAttribute/reflection.GenericAttribute.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/reflection/ldtoken/reflection.ldtoken.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/reflection/regression/reflection.regression.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/reflection/Tier1Collectible/reflection.Tier1Collectible.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/tracing/eventactivityidcontrol/tracing.eventactivityidcontrol.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/tracing/eventlistener/tracing.eventlistener.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/tracing/eventsource/tracing.eventsource.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/tracing/runtimeeventsource/tracing.runtimeeventsource.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/tracing/tracecontrol/tracing.tracecontrol.XUnitWrapper.dll /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/../bin/tests/Linux.x64.Release/tracing/tracevalidation/tracing.tracevalidation.XUnitWrapper.dll -parallel all -html /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/bin/Logs/TestRun.html -xml /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/bin/Logs/TestRun.xml  -notrait category=outerloop -notrait category=failing -nocolor" exited with code 134. [/mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_r2r_tst/tests/runtest.proj]
19:24:35 
19:24:35 Build FAILED.
19:24:35 
19:24:35

**Comment by BruceForstall** [comment]
Looks like all the release x64 CentOS R2R jobs fail with:
```
terminate called after throwing an instance of 'PAL_SEHException'
```

This is when invoking `corerun xunit.console.dll` on the wrapper assemblies.

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_centos7.1_r2r_tst/

@janvorli

**Comment by janvorli** [comment]
This is really strange. I've acquired the repro VM and the issue reproes 100%. I've rebuilt coreclr on that VM and got the same issue. But I've built from the same commit on my local VM with the same CentOS 7.1 and it works just fine. 
I've then tried to copy the libcoreclr.so from the "bad" build to my local VM and the failure occurred there too. 
The issue is that an exception thrown in the native code is not caught by a catch handler in the the native code just a frame or two above.
So the conclusion is that somehow the build on our lab machines produces binaries with broken ability to handle exceptions. I have no idea how that could happen. I am currently diffing the produced libcoreclr.so binaries. The "good" binary is about 625kB larger than the bad one.

**Comment by janvorli** [comment]
Next finding - the .o files contain correct `.eh_frame` stuff even on the "bad" build, so the linker is the one to blame here.

**Comment by janvorli** [comment]
Mystery solved - the issue was caused by an outdated ld.gold. 
My box (good build):
```
ld.gold --version
GNU gold (version 2.25.1-32.base.el7_4.1 ) 1.11
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

The CI repro VM (bad build):
```
 ld.gold --version
GNU gold (version 2.23.52.0.1-30.el7_1.2 20130226) 1.11
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

Updating the ld.gold (`sudo yum update binutils`) fixed the issue on the CI repro VM.

@dotnet/dnceng - we will need to update the binutils on our CI CentOS 7.1 machines to let them produce native binaries with correct exception handling info.

**Comment by janvorli** [comment]
Ping @dotnet/dnceng - the release x64 CentOS R2R jobs keep failing due to this issue.

**Comment by MattGal** [comment]
@janvorli this should be a very simple PR to move to using Centos.7.Amd64.Open for your Jenkins agents (which now floats to "latest centos").   I'll take a quick peek at doing that.

**Comment by MattGal** [comment]
I took a peek at the ginormous .groovy file and the cheapest fix would probably be to have a mapping like you have for the ARM machines here:

https://github.com/dotnet/coreclr/blob/c767f41d7b29a0b2021136ecd96644512b343c45/netci.groovy#L712-L805

To pick up different affinities for Helix machines when possible.  You'd probably want to also remove the minor version from your Centos naming as well since they only support "latest 7" AFAIK.  From chatting with @mmitche there may be some special build dependencies on the old agent VHD, those would need to be either bootstrapped as part of the build if so or added to the base image for Centos.7.Amd64.Open.

**Comment by RussKeldorph** [comment]
Assuming this is no longer relevant.

**Comment by MattGal** [comment]
@RussKeldorph yes; we've updated Centos quite a bit since then and Jenkins is no longer in use.
