### ISSUE TITLE
EventPipe config file isn't read from AppBase

### ISSUE THREAD

**Issue by anurse** [dotnet/coreclr#20454]
It looks like the EventPipe config file (added in https://github.com/dotnet/coreclr/pull/20238) is expected to be in the same directory as `dotnet.exe` rather than the same directory as the managed app.

To reproduce this problem

1. Clone https://github.com/aspnet/AspLabs
1. Check out branch `anurse/dotnet-collect-eventpipe`
1. Launch a .NET process that emits events to `Microsoft-Windows-DotNETRuntime`
1. Run the `dotnet run --project ./src/dotnet-monitor/samples/SampleMonitoredApp` command from the AspLabs repo
1. In a different window run `dotnet run --project ./src/dotnet-monitor/src/dotnet-collect -- -c ./src/dotnet-monitor/samples/SampleMonitoredApp/bin/Debug/netcoreapp2.2/SampleMonitoredApp.eventpipeconfig`
1. Wait a few seconds, then press `A` and `G` in the console window running SampleMonitoredApp a few times to allocate some memory and trigger GCs
1. Press Ctrl-C in the `dotnet-collect` window

Expected Behavior:

A `.netperf` file is dropped in the directory from which `dotnet-collect` was launched

Actual Behavior:

No `.netperf` file is dropped

If the `-c` path is changed to `~/.dotnet/x64/SampleMonitoredApp.eventpipeconfig` (i.e. the file is placed next to the `dotnet.exe`), then the `netperf` file *is* written successfully.

Also note that `SampleMonitoredApp` uses reflection to dump out the expected config file path and it shows that the search path is next to `dotnet.exe`.

cc @brianrob @vancem

**Comment by brianrob** [comment]
The bug here is that I was using ```AppDomain.CurrentDomain.BaseDirectory``` instead of ```AppContext.BaseDirectory```.  https://github.com/dotnet/coreclr/pull/20464 addresses this.
