### ISSUE TITLE
servermodel test failed in CI job x64_checked_windows_nt_heapverify1

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20462]
the failing job: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_heapverify1/99/

failed tests:

- StackTracePreserveTests( not sure if it should be disabled, refer to https://github.com/dotnet/coreclr/pull/20337)
- servermodel 

To run the test:
  > set CORE_ROOT=D:\j\workspace\x64_checked_w---facfb6a0\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
  > D:\j\workspace\x64_checked_w---facfb6a0\bin\tests\Windows_NT.x64.Checked\GC\Scenarios\ServerModel\servermodel\servermodel.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x64_checked_w---facfb6a0\bin\tests\Windows_NT.x64.Checked\TestWrappers\GC.Scenarios\GC.Scenarios.XUnitWrapper.cs(33149,0): at GC_Scenarios._ServerModel_servermodel_servermodel_._ServerModel_servermodel_servermodel_cmd()

**Comment by BruceForstall** [comment]
The StackTracePreserveTests were disabled shortly after the job referred to here.

In the latest run:
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_heapverify1/100

the servermodel test is a timeout:
```
cmdLine:D:\j\workspace\x64_checked_w---facfb6a0\bin\tests\Windows_NT.x64.Checked\GC\Scenarios\ServerModel\servermodel\servermodel.cmd Timed Out
```
we should do something to either up the per-test timeouts for this (heapverify) run or disable it for this run (e.g., mark it GCStressIncompatible)

There is another timeout as well:
```
cmdLine:D:\j\workspace\x64_checked_w---facfb6a0\bin\tests\Windows_NT.x64.Checked\GC\Features\HeapExpansion\bestfit-finalize\bestfit-finalize.cmd Timed Out
```

**Comment by RussKeldorph** [comment]
`StackTracePreserveTests` tracked by #20322.

Assuming timeout tweaking and mode compat is done or being tracked by other issues as failures arise.  @sandreenko
