### ISSUE TITLE
2 tests failed in CI job x64_checked_osx10.12_r2r_jitstressregs0x80_tst

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20474]
the failing job: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/146/

failed tests:

- **JIT_jit64._opt_cse_hugeexpr1_hugeexpr1_._opt_cse_hugeexpr1_hugeexpr1_sh**
Stacktrace
MESSAGE:
\ncmdLine:/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/jit64/opt/cse/hugeexpr1/hugeexpr1.sh Timed Out\n/n/nReturn code: -100/nRaw output file: /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/jit64/Reports/JIT.jit64/opt/cse/hugeexpr1/hugeexpr1.output.txt/nRaw output:/nBEGIN EXECUTION\nin takeLock\n/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/Tests/Core_Root:/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/jit64/opt/cse/hugeexpr1/IL:/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/jit64/opt/cse/hugeexpr1 /in hugeexpr1.org /out hugeexpr1.exe\n\ncmdLine:/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/jit64/opt/cse/hugeexpr1/hugeexpr1.sh Timed Out\nTest Harness Exitcode is : -100\n/nTo run the test:/n> set CORE_ROOT=/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/Tests/Core_Root/n> /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/jit64/opt/cse/hugeexpr1/hugeexpr1.sh/n\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at JIT_jit64._opt_cse_hugeexpr1_hugeexpr1_._opt_cse_hugeexpr1_hugeexpr1_sh() in /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12/bin/tests/OSX.x64.Checked/TestWrappers/JIT.jit64/JIT.jit64.XUnitWrapper.cs:line 24049
- **JIT_Regression._VS_ia64_JIT_V1_2_M02_b28158_b28158_b28158_._VS_ia64_JIT_V1_2_M02_b28158_b28158_b28158_sh**
Stacktrace
MESSAGE:
\ncmdLine:/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh Timed Out\n/n/nReturn code: -100/nRaw output file: /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/Regression/Reports/JIT.Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.output.txt/nRaw output:/nBEGIN EXECUTION\nin takeLock\n/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/Tests/Core_Root:/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/IL:/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158 /in b28158.org /out b28158.exe\n\ncmdLine:/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh Timed Out\nTest Harness Exitcode is : -100\n/nTo run the test:/n> set CORE_ROOT=/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/Tests/Core_Root/n> /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx10.12_r2r_jitstressregs0x80_tst/bin/tests/OSX.x64.Checked/JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh/n\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at JIT_Regression._VS_ia64_JIT_V1_2_M02_b28158_b28158_b28158_._VS_ia64_JIT_V1_2_M02_b28158_b28158_b28158_sh() in /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12/bin/tests/OSX.x64.Checked/TestWrappers/JIT.Regression/JIT.Regression.XUnitWrapper.cs:line 92299

**Comment by BruceForstall** [comment]
Both failed with timeouts. I kicked off another run to see if they fail again: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_osx10.12_r2r_jitstressregs0x80_flow/171/

**Comment by BruceForstall** [comment]
I still see b28158 fail with timeout.

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_osx10.12_r2r_jitstressregs0x80_flow/

**Comment by RussKeldorph** [comment]
`b28158` is not currently disabled.

`hugeexpr1` is disabled for ARM64 only.

**Comment by BruceForstall** [comment]
Closing this. If there are disabled tests that should be enabled, that should be audited and a new issue created.
