### ISSUE TITLE
build managed tests failed in CI job checked_ubuntu

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20487]
the failing job: https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu/24969

the failed log:
Building step 'Managed tests build (build tests)' slice=4 via "/mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/run.sh" build -Project=/mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/tests/build.proj -MsBuildLog="/flp:Verbosity=normal;LogFile=/mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Checked.log;Append=true" -MsBuildWrn="/flp1:WarningsOnly;LogFile=/mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Checked.wrn;Append=true" -MsBuildErr="/flp2:ErrorsOnly;LogFile=/mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Checked.err;Append=true" -MsBuildEventLogging="/l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log"  -BuildArch=x64 -BuildType=Checked -BuildOS=Linux  -priority=1
…
Command execution failed with exit code 139.
ERROR: An error occured in /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/Tools/dotnetcli/dotnet /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/Tools/run.exe /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/config.json build -Project=/mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/tests/build.proj -MsBuildLog=/flp:Verbosity=normal;LogFile=/mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Checked.log;Append=true -MsBuildWrn=/flp1:WarningsOnly;LogFile=/mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Checked.wrn;Append=true -MsBuildErr=/flp2:ErrorsOnly;LogFile=/mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Checked.err;Append=true -MsBuildEventLogging=/l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log -BuildArch=x64 -BuildType=Checked -BuildOS=Linux -priority=1. Check logs under /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu.
Failed to build Managed tests build (build tests). See the build logs:
    /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Checked.log
    /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Checked.wrn
    /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Checked.err

**Comment by BruceForstall** [comment]
The key for this failure is:
```
Command execution failed with exit code 139.
```

The job fails periodically with this, but not very often.

The other "random" failure mode seems to be https://github.com/dotnet/coreclr/issues/20236 and `tests/dir.traversal.targets(25,5): error : (No message specified) ` (https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu/24973/consoleFull#39706996933fe3402-0c0f-45a7-a707-47164965bab5)

**Comment by RussKeldorph** [comment]
I'm not aware of this hitting for a while, so I assume either we picked up an improved SDK or (more likely) @echesakovMSFT's work in #22885 reduced the stress on the build enough to mitigate it.  Feel free to re-open if you disagree.
