### ISSUE TITLE
NuGet package file checksum changes on Microsoft.NETCore.DotNetHostResolver 2.1.0

### ISSUE THREAD

**Issue by baracoder** [dotnet/coreclr#20489]
Sorry if I am opening the issue in the wrong repository. I am not sure where it belongs.

In the past few weeks the checksum of the package Microsoft.NETCore.DotNetHostResolver version 2.1.0 changed on nuget.org multiple times, even though the the nuget.org detail page shows that the package was updated 5 months ago. Is this behavior to be expected and if so, why?

The reason I am asking is, that I am trying to package some dotnet [software](https://github.com/baracoder/dotnet2nix) for [nix](https://nixos.org/nix/). Nix is a purely functional package manager which makes builds repeatable. Different inputs (e.g. dependencies) lead to different results, so the build breaks if the file fetched from the url does not have the expected checksum.
I am using NuGet v2 url format: `https://www.nuget.org/api/v2/package/Microsoft.NETCore.DotNetHostResolver/2.1.0`

Any suggestions are welcome.

**Comment by jkotas** [comment]
NuGet dependency resolution will give you latest package servicing by default. 

Are you actually downloading the 2.1.0 package, or are you getting auto upgraded to the latest servicing (ie 2.1.5 currently)? You should be able to figure it out by inspecting the content of the package.

**Comment by baracoder** [comment]
Thank you for the reply @jkotas 
That pointed me in the right direction.

I looked at the contents of the newly downloaded package.
The nuspec file has also `<version>2.1.0</version>`
Looking at the modification dates, only `.signature.p7s` has changed
```
  Length      Date    Time    Name
---------  ---------- -----   ----
      530  05-15-2018 14:08   _rels/.rels
     1224  05-15-2018 14:08   Microsoft.NETCore.DotNetHostResolver.nuspec
     1812  05-15-2018 14:08   runtime.json
     1105  05-15-2018 14:08   LICENSE.TXT
    28261  05-15-2018 14:08   THIRD-PARTY-NOTICES.TXT
      529  05-15-2018 14:08   [Content_Types].xml
      870  05-15-2018 14:08   package/services/metadata/core-properties/c9b779054c744ae4a302fd6cbafe03f4.psmdcp
    18702  10-04-2018 02:39   .signature.p7s
---------                     -------
    53033                     8 files
```

I have found an announcement from August where nuget.org introduces  repository signatures  https://blog.nuget.org/20180810/Introducing-Repository-Signatures.html

This fits with the the changing checksums I have noticed. 
An earlier version of the package from cache has a different `.signature.p7s`
```
     9354  05-15-2018 17:45   .signature.p7s
```
I did not find any third version of that file, so it might have been other files which changed over time.
