### ISSUE TITLE
could not load file or assembly System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20488]
the failing job: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_zapdisable_tst/598/

failed tests:

```
- readytorun_DynamicMethodGCStress._DynamicMethodGCStress_DynamicMethodGCStress_._DynamicMethodGCStress_DynamicMethodGCStress_sh
- readytorun_tests._mainv1_mainv1_._mainv1_mainv1_sh
- readytorun_tests._mainv2_mainv2_._mainv2_mainv2_sh
```

failed log:

To run the test:
> set CORE_ROOT=/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_zapdisable_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root
> /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_zapdisable_tst/bin/tests/Linux.x64.Checked
eadytorun/DynamicMethodGCStress/DynamicMethodGCStress/DynamicMethodGCStress.sh

Expected: True
Actual:   False

[/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_zapdisable_tst/bin/tests/Linux.x64.Checked/readytorun/tests/mainv1/mainv1.sh]: 

Could not load file or assembly '/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_zapdisable_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/System.Private.CoreLib.dll'. An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B (COR_E_BADIMAGEFORMAT))
Error: compilation failed for \"test.dll\" (0x8007000b)
Could not load file or assembly '/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_zapdisable_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/System.Private.CoreLib.dll'. An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B (COR_E_BADIMAGEFORMAT))
Error: compilation failed for \"fieldgetter.dll\" (0x8007000b)
Could not load file or assembly '/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_zapdisable_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/System.Private.CoreLib.dll'. An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B (COR_E_BADIMAGEFORMAT))
Error: compilation failed for \"mainv1.exe\" (0x8007000b)

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly '/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_zapdisable_tst/bin/tests/Linux.x64.Checked/readytorun/tests/mainv1/test.ni.dll'. The system cannot find the file specified.

   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContet, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Program.MyLoadContext.TestMultipleLoads() in /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/tests/src/readytorun/tests/main.cs:line 340
   at Program.RunAllTests() in /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/tests/src/readytorun/tests/main.cs:line 457
   at Program.Main() in /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/tests/src/readytorun/tests/main.cs:line 484
/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_zapdisable_tst/bin/tests/Linux.x64.Checked/readytorun/tests/mainv1/mainv1.sh: line 251: 116057 Aborted                 (core dumped) $_DebuggerFullPath \"$CORE_ROOT/corerun\" $ExePath $CLRTestExecutionArguments
/n/nReturn code:      1/nRaw output file:      /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_zapdisable_tst/bin/tests/Linux.x64.Checked/readytorun/tests/Reports/readytorun.tests/mainv1/mainv1.output.txt/nRaw

**Comment by sandreenko** [comment]
I expect this issue to go away after #21497. and ci confirms that it is gone.
Another test failure in this job is covered by #19340.

So I think we can close this one, @BruceForstall ?

**Comment by sandreenko** [comment]
It was the same issue that I hit with `jitutils jit-diff` when 
`/home/sergey/git/coreclr/bin/tests/Linux.x64.Checked/Tests/Core_Root/crossgen  /Platform_Assemblies_Paths /home/sergey/git/coreclr/bin/Product/Linux.x64.Checked/IL /home/sergey/git/coreclr/bin/Product/Linux.x64.Checked/IL/System.Private.CoreLib.dll`
worked fine and 
`/home/sergey/git/coreclr/bin/tests/Linux.x64.Checked/Tests/Core_Root/crossgen  /Platform_Assemblies_Paths /home/sergey/git/coreclr/bin/tests/Linux.x64.Checked/Tests/Core_Root /home/sergey/git/coreclr/bin/Product/Linux.x64.Checked/IL/System.Private.CoreLib.dll`
failed (the diff is in `/Platform_Assemblies_Paths` the working version used `Product/Linux.x64.Checked/IL` and the failed used `tests/Linux.x64.Checked/Tests/Core_Root`). 
and failed with:
```
Could not load file or assembly '/home/sergey/git/coreclr/bin/tests/Linux.x64.Checked/Tests/Core_Root/System.Private.CoreLib.dll'. An attempt was made to load a program with an incorrect format.
 (Exception from HRESULT: 0x8007000B (COR_E_BADIMAGEFORMAT))

Thread 1 "crossgen" hit Catchpoint 1 (exception thrown), 0x00007ffff729bc3d in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff729bc3d in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000781d7f in ThrowHR (hr=-2147467259) at /home/sergey/git/coreclr/src/utilcode/ex.cpp:967
#2  0x000000000074a98f in ThrowAndLog (hr=-2147024885, 
    szMsg=0x8f608e "m_pEECompileInfo->Startup(fForceDebug, fForceProfile, fForceInstrument)", 
    szFile=0x8f5f3c "/home/sergey/git/coreclr/src/zap/zapper.cpp", lineNum=593)
    at /home/sergey/git/coreclr/src/zap/zaplog.h:41
#3  0x0000000000746df8 in Zapper::InitEE (this=0xc83760, fForceDebug=0, fForceProfile=0, 
    fForceInstrument=0) at /home/sergey/git/coreclr/src/zap/zapper.cpp:593
```

on windows both version worked fine.

Now it works on Linux as well.

**Comment by BruceForstall** [comment]
Yes. Closed.
