### ISSUE TITLE
PtrToStringAuto incorrectly uses PtrToStringUni (UTF-16) instead of PtrToStringUTF8

### ISSUE THREAD

**Issue by morguldir** [dotnet/coreclr#20504]
https://github.com/dotnet/coreclr/blob/87e96eafa84545335dd6ec02cb4e233211456677/src/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs#L57-L61

https://github.com/dotnet/coreclr/blob/87e96eafa84545335dd6ec02cb4e233211456677/src/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs#L122-L126

According to [System.Text.Encoding.Default](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=netframework-4.7.2#System_Text_Encoding_Default) UTF-8 is supported on all platforms and is the default value with .NET Core.

Either way, UTF-16 is incorrect on linux

**Comment by jkotas** [comment]
Right, it would be nice to not have this difference.

**Comment by jkotas** [comment]
Resolving as duplicate in favor of https://github.com/dotnet/coreclr/issues/23464
