### ISSUE TITLE
'local\temp\tmpcilhpt' is not recognized as an internal or external command -- arm64_cross_checked_windows_nt_tst

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20514]
the failing job: https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt_tst/666/

failed log:
 Loader_classloader._TypeGeneratorTests_TypeGeneratorTest1114_Generated1114_Generated1114_._TypeGeneratorTests_TypeGeneratorTest1114_Generated1114_Generated1114_cmd [FAIL]
        **'c:\users\helixa~1\appdata\local\temp\tmp_2kull' is not recognized as an internal or external command,**
        operable program or batch file.
        
  cmdLine:C:\j\workspace\arm64_cross_c---b1f63449\bin\tests\Windows_NT.arm64.Checked\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest1114\Generated1114\Generated1114.cmd Timed Out
        
  
  Return code:      -100
  Raw output file:      C:\j\workspace\arm64_cross_c---b1f63449\bin\tests\Windows_NT.arm64.Checked\Reports\Loader.classloader\TypeGeneratorTests\TypeGeneratorTest1114\Generated1114\Generated1114.output.txt

**Comment by BruceForstall** [comment]
This is seen in other runs, on different tests, as well, e.g.:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt_tst/663/consoleFull
```
12:21:35 
      GC_API._GC_GetAllocatedBytesForCurrentThread_GetAllocatedBytesForCurrentThread_._GC_GetAllocatedBytesForCurrentThread_GetAllocatedBytesForCurrentThread_cmd [FAIL]
12:21:35         'c:\users\helixa~1\appdata\local\temp\tmpcilhpt' is not recognized as an internal or external command,
12:21:35         operable program or batch file.
```

**Comment by shimingsg** [comment]
similar failing in job https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_jitstress2_jitstressregs2_tst/47/consoleText
failed log:
JIT_superpmi._superpmicollect_superpmicollect_._superpmicollect_superpmicollect_cmd [FAIL]
        'c:\users\helixa~1\appdata\local\temp\tmp8zbiyr' is not recognized as an internal or external command,
        operable program or batch file

**Comment by shimingsg** [comment]
2 tests similar failing in job https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_jitstressregs4_tst/43

- JIT_Generics._Coverage_chaos65204782cs_o_chaos65204782cs_o_._Coverage_chaos65204782cs_o_chaos65204782cs_o_cmd
- JIT_Regression._VS_ia64_JIT_V1_2_M02_b14364_b14364_b14364_._VS_ia64_JIT_V1_2_M02_b14364_b14364_b14364_cmd

**Comment by shimingsg** [comment]
test failed in https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_tieredcompilation_tst/15

failed test:
baseservices_threading._waithandle_waitany_waitanyex4_waitanyex4_._waithandle_waitany_waitanyex4_waitanyex4_cmd [FAIL]

a few jitstress runs are failed with the similar error:
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress

**Comment by BruceForstall** [comment]
@jashook Do you know what this file is? When I've seen this, it seems to be output along with failed results, but doesn't seem like the cause of the failures.

**Comment by jashook** [comment]
I have never seen this before or this failure before I do not really have any guesses either on what could be the cause sorry.

**Comment by BruceForstall** [comment]
I fixed this with https://github.com/dotnet/coreclr/pull/21809
