### ISSUE TITLE
JIT_Regression._CLR_x86_JIT_V1_M09_b13621_b13621_b13621_._x86_JIT_V1_M09_b13621_b13621_b11_cmd failed with System.InvalidOperationException: Handle is not initialized

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/coreclr#20519]
See [log](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable_jitstress2/102/testReport/junit/JIT_Regression/_CLR_x86_JIT_V1_M09_b13621_b13621_b13621_/_CLR_x86_JIT_V1_M09_b13621_b13621_b13621_cmd/)

JIT_Regression._CLR_x86_JIT_V1_M09_b13621_b13621_b13621_._CLR_x86_JIT_V1_M09_b13621_b13621_b13621_cmd [FAIL]
        
  Unhandled Exception: System.InvalidOperationException: Handle is not initialized.
           at System.Runtime.InteropServices.GCHandle.ValidateHandle(IntPtr handle)
           at System.Runtime.InteropServices.GCHandle.Free()
           at DefaultNamespace.RootMem.Finalize()
  
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_checked_w---0668d603\bin\tests\Windows_NT.x86.Checked\Reports\JIT.Regression\CLR-x86-JIT\V1-M09\b13621\b13621\b13621.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_checked_w---0668d603\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" b13621.exe 
        0
        50
        100
        150
        200
        250
        300
        350
        400
        450
        500
        550
        600
        650
        700
        750
        800
        850
        900
        950
        Expected: 100
        Actual: -532462766
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1

**Comment by sandreenko** [comment]
It needs only `complus_gcstress=0xc` to repro.

**Comment by sandreenko** [comment]
It is a test regression after change in #18476.
