### ISSUE TITLE
hundreds of tests failed with time out in CI job arm64_cross_checked_ubuntu16.04_gcstress0x3_tst

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20521]
the failing job: 
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_gcstress0x3_tst/3/

one of the failed log:
MESSAGE:
\ncmdLine:/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_gcstress0xc_tst/bin/tests/Linux.arm64.Checked/JIT/Methodical/fp/exgen/10w5d_cs_d/10w5d_cs_d.sh Timed Out\n/n/nReturn code: -100/nRaw output file: /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_gcstress0xc_tst/bin/tests/Linux.arm64.Checked/JIT/Methodical/Reports/JIT.Methodical/fp/exgen/10w5d_cs_d/10w5d_cs_d.output.txt/nRaw output:/nBEGIN EXECUTION\n/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_gcstress0xc_tst/bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun 10w5d_cs_d.exe\n\ncmdLine:/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_gcstress0xc_tst/bin/tests/Linux.arm64.Checked/JIT/Methodical/fp/exgen/10w5d_cs_d/10w5d_cs_d.sh Timed Out\nTest Harness Exitcode is : -100\n/nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_gcstress0xc_tst/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_gcstress0xc_tst/bin/tests/Linux.arm64.Checked/JIT/Methodical/fp/exgen/10w5d_cs_d/10w5d_cs_d.sh/n\nExpected: True\nActual: False
+++++++++++++++++++
STACK TRACE:
at JIT_Methodical._fp_exgen_10w5d_cs_d_10w5d_cs_d_._fp_exgen_10w5d_cs_d_10w5d_cs_d_sh() in /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs:line 76829

**Comment by BruceForstall** [comment]
@janvorli @kouvel Who can investigate GCStress=3 failures?

**Comment by janvorli** [comment]
@BruceForstall I'll take a look

**Comment by shimingsg** [comment]
similar in this job: https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_gcstress0xc_zapdisable_tst/4/

**Comment by BruceForstall** [comment]
@shimingsg Let's keep the "gcstress0x3" and "gcstress0xc" issues separate -- they might be related, but typically have different causes.

**Comment by shimingsg** [comment]
@BruceForstall , new issue for gcstress0xc: https://github.com/dotnet/coreclr/issues/20538

**Comment by BruceForstall** [comment]
@janvorli These are fast 48-core machines we're running on in the lab. We wouldn't want to run sequentially, but maybe we could limit the parallelism some and/or up the timeouts.

**Comment by janvorli** [comment]
Last three runs of the https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_gcstress0x3_tst/ passed green, so I am closing this issue.
