### ISSUE TITLE
System.Memory.Tests failed in CI job arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_tst

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20520]
the failing job:
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_tst/22/consoleText

failed log:
[37m  Discovering: System.Memory.Tests (method display = ClassAndMethod, method display options = None)
[m[37m  Discovered:  System.Memory.Tests (found 1955 of 1976 test cases)
[m[37m  Starting:    System.Memory.Tests (parallel test collections = on, max threads = 46)
[m./RunTests.sh: line 127:  3452 Aborted                 (core dumped) $RUNTIME_PATH/dotnet xunit.console.dll System.Memory.Tests.dll -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_tst/_/fx/bin/tests/System.Memory.Tests/netcoreapp-Linux-Release-arm64
----- end 09:17:24 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.

**Comment by sandreenko** [comment]
The test was not excluded and available history doesn't show any failures on this test.
