### ISSUE TITLE
InvalidProgramException occurs for a simple assembly (RyuJIT only)

### ISSUE THREAD

**Issue by rstarkov** [dotnet/coreclr#2053]
The following IL program, when assembled and run, throws an InvalidProgramException when RyuJIT is used. Disabling RyuJIT makes the problem go away. The program passes v4.6 of peverify.

The instruction at the after_try label seems to be crucial. Moving that instruction (along with the label) to after the finally block makes the problem go away.

    .assembly extern mscorlib
    {
        .publickeytoken = (B7 7A 5C 56 19 34 E0 89)
        .ver 4:0:0:0
    }
    .assembly Invalid
    {
        .ver 1:0:52015:51109
    }

    .class public abstract auto ansi sealed beforefieldinit Program
           extends [mscorlib]System.Object
    {
        .method public hidebysig static void Main() cil managed
        {
            .entrypoint
            .maxstack  1

            .try
            {
                leave end_of_prog
            }
            catch [mscorlib]System.Object
            {
                pop
                br inner_try

                after_try:
                leave end_of_prog

                .try
                {
                    inner_try:
                    leave after_try
                }
                finally
                {
                    endfinally
                }
            }

            end_of_prog:
            ret
        }
    }

As the previous jitter didn't throw when running this code, I suspect that the assembly is actually valid, and so this is a bug in RyuJIT.

**Comment by Timwi** [comment]
Interesting find. I managed to reproduce this with an actual C# program which compiles to IL that is fairly equivalent to yours. However, the exception only triggers on a 64-bit system and with the “Prefer 32-bit” option disabled (so that the process runs as 64-bit). Here is the C# code:

    public static class Program
    {
        public static void Main()
        {
            try
            {
                goto end_of_prog;
            }
            catch
            {
                goto inner_try;

                after_try:
                goto end_of_prog;

                inner_try:
                try
                {
                    goto after_try;
                }
                finally
                {

                }
            }

            end_of_prog:
            return;
        }
    }

**Comment by caesay** [comment]
I can confirm that the code Timwi posted crashes on my system:
OS: Win 10 x64 / .Net: 4.6
Tried with and without the vs hosting process (no change). Running the program compiled for 32bit has no issues as suggested. If I run compiled for 64bit, it crashes - but only if "Optimize Code" is left un-checked.

**Comment by rstarkov** [comment]
The code is produced by serializing a graph representing a method's IL. I'm going to see if the code you linked to hints at what work-around we should employ, but if you have a specific suggestion that would be very helpful.

It's true that my example has a lot of dead code, but the program I started with didn't. I suspect @Timwi could construct an example where the code isn't dead, but it sounds unnecessary as you're fixing it anyway. Thanks!

**Comment by BruceForstall** [comment]
This is caused by a case where the "finally" is the very last thing in the function or handler. Normally, there is code after that, such as a return. But in this case, the call-to-finally occurs last, and branches backwards to a block that then has a return from the catch. The workaround is to make sure there is at least some code after the try/finally.

I am testing a fix.
