### ISSUE TITLE
build error MSB3073 in CI job arm64_cross_checked_windows_nt_corefx_jitstress1_flow

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20540]
the failing jobs:

- https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstress1_bld/14/
- https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstress2_bld/13/
- https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstressregs0x1000_bld/13/
- https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstressregs0x10_bld/13/

the failed log:
```
**CMake is a pre-requisite to build this repository but it was not found on the path**. Please install CMake from http://www.cmake.org/download/ and ensure it is on your path.
  Failed to generate native component build project!
D:\j\workspace\arm64_cross_c---16b68231\_\fx\src\Native\build-native.proj(50,5): error MSB3073: The command ""D:\j\workspace\arm64_cross_c---16b68231\_\fx\src\Native\build-native.cmd" arm64 Release Windows_NT" exited with code 1.

Build FAILED.
```

**Comment by shimingsg** [comment]
some jitstress jobs failed with similar log:
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/

**Comment by BruceForstall** [comment]
I had asked about this issue in https://github.com/dotnet/coreclr/pull/20415 but got no response.

@weshaggard @jashook any ideas here?

**Comment by BruceForstall** [comment]
This has been fixed
