### ISSUE TITLE
OSX build fails with latest CMAKE 3.4 release

### ISSUE THREAD

**Issue by cmckinsey** [dotnet/coreclr#2054]
Trying the mac build for the first time. Install directions say to use:

brew install cmake

picked up the latest version 3.4 which appears to not work. The build.make file corresponding to this .S file that was generated does not have $(ASM_INCLUDE) in the production for assembling the file.

/Users/cmckinsey/dev/coreclr/src/vm/amd64/calldescrworkeramd64.S:7:10: fatal error: 'unixasmmacros.inc' file not found
#include "unixasmmacros.inc"
         ^
1 error generated.

Installing cmake 3.3.2 fixes the issue. However build fails later building mscorlib.

I notice the CI job skips the mscorlib build and just runs some native PAL tests. Does the mscorlib build on OSX still work?

**Comment by ellismg** [comment]
> I notice the CI job skips the mscorlib build and just runs some native PAL tests. Does the mscorlib build on OSX still work?

The build requires mono and mono is flaky when trying to build mscorlib.dll so we don't run it in CI.  I've had luck using a local build of mono and doing work arounds like setting `MONO_THREADS_PER_CPU` to a large number (I usually do 2000).

I have not tried to build mscorlib on OSX in the past few days, but it should work.  What error are you getting?

**Comment by cmckinsey** [comment]
I see this error:

Commencing build of mscorlib components for OSX.x64.Debug
  mscorlib -> /Users/cmckinsey/dev/coreclr/bin/obj/OSX.x64.Debug/mscorlib.dll
  Error: FindPackagesById: runtime.linux.System.Net.NameResolution
    Too many open files
  Error: FindPackagesById: runtime.linux.System.Net.NameResolution
    Too many open files
  Error: FindPackagesById: runtime.linux.System.Net.NameResolution
    Too many open files
  Error: FindPackagesById: runtime.win7.System.Runtime.InteropServices.RuntimeInformation
    Too many open files
  Error: FindPackagesById: runtime.win7.System.Runtime.InteropServices.RuntimeInformation
    Too many open files
  Error: FindPackagesById: runtime.win7.System.Runtime.InteropServices.RuntimeInformation
    Too many open files
  Error: FindPackagesById: runtime.unix.System.Net.Requests
    Too many open files
  Error: FindPackagesById: runtime.unix.System.Net.Requests
    Too many open files
  Error: FindPackagesById: runtime.osx.10.10.System.IO.FileSystem
    Too many open files
  Error: FindPackagesById: runtime.osx.10.10.System.IO.FileSystem
    Too many open files
  Error: FindPackagesById: runtime.osx.10.10.System.IO.FileSystem
    Too many open files
  Error: FindPackagesById: runtime.osx.10.10.System.Diagnostics.Process
    Too many open files
  Error: FindPackagesById: runtime.win7.System.Security.Cryptography.X509Certificates
    Too many open files
  Error: FindPackagesById: runtime.win7.System.Security.Cryptography.X509Certificates
    Too many open files
  Error: FindPackagesById: runtime.win7.System.Security.Cryptography.X509Certificates
    Too many open files
  Error: FindPackagesById: runtime.linux.System.Security.Cryptography.Algorithms
    Too many open files
  Error: FindPackagesById: runtime.linux.System.Security.Cryptography.Algorithms
    Too many open files
  Error: FindPackagesById: runtime.linux.System.Security.Cryptography.Algorithms
    Too many open files
  Error: FindPackagesById: runtime.osx.10.10.System.IO.FileSystem.DriveInfo
    Too many open files
  Error: FindPackagesById: runtime.osx.10.10.System.IO.FileSystem.DriveInfo
    Too many open files
  Error: FindPackagesById: runtime.osx.10.10.System.IO.FileSystem.DriveInfo
    Too many open files
  Error: FindPackagesById: runtime.unix.System.Security.Cryptography.Encoding
    Too many open files
  Error: FindPackagesById: runtime.unix.System.Security.Cryptography.Encoding
    Too many open files
  Error: FindPackagesById: runtime.unix.System.Security.Cryptography.Encoding
    Too many open files
  Error: FindPackagesById: runtime.unix.System.Security.Cryptography.X509Certificates
    Too many open files
  Error: FindPackagesById: runtime.unix.System.Security.Cryptography.X509Certificates
    Too many open files
  Error: FindPackagesById: runtime.osx.10.10.System.IO.FileSystem.Watcher
    Too many open files
  Error: FindPackagesById: runtime.osx.10.10.System.IO.FileSystem.Watcher
    Too many open files
  Error: FindPackagesById: runtime.osx.10.10.System.IO.FileSystem.Watcher
    Too many open files
/Users/cmckinsey/dev/coreclr/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00105/lib/toolruntime.targets(32,5): error MSB3073: The command ""/Users/cmckinsey/dev/coreclr/packages/dnx-mono.1.0.0-beta5-12101/bin/dnu" restore --packages "/Users/cmckinsey/dev/coreclr/packages/" "/Users/cmckinsey/dev/coreclr/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00105/lib/tool-runtime/project.json"" exited with code 1. [/Users/cmckinsey/dev/coreclr/src/mscorlib/mscorlib.csproj]
Failed to build mscorlib.

Setting the MONO_THREADS_PER_CPU did not make any difference.

**Comment by janvorli** [comment]
@cmckinsey The "too many files" is something that @gkhanna79 was looking into few weeks ago and the fix was to raise the allowed number of open files. I am not sure what was the exact way to do that for OSX, @gkhanna79 can you please comment on it here?

**Comment by ellismg** [comment]
Try `ulimit -n 2048` to update the number of allowed open files.  You can see the current limits with `ulimit -a`.

**Comment by janvorli** [comment]
Fixed by #2529
