### ISSUE TITLE
System.Security.Cryptography.Cng.Tests.DSACngPkcs8Tests.NoPlaintextExportAllowsEncryptedPkcs8 failed with Assert failure.

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/coreclr#20541]
**Job:**
jitstress » x86_checked_windows_nt_corefx_jitstressregs8
[https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs8/623/](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs8/623/)

**Affected tests:**
System.Security.Cryptography.Cng.Tests.DSACngPkcs8Tests.NoPlaintextExportAllowsEncryptedPkcs8(algorithm: TripleDes3KeyPkcs12) 

**Log:**
System.Security.Cryptography.Cng.Tests.DSACngPkcs8Tests.NoPlaintextExportAllowsEncryptedPkcs8(algorithm: TripleDes3KeyPkcs12) [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_checked_w---fb0ba759\_\fx\src\System.Security.Cryptography.Cng\tests\DSACngPkcs8Tests.cs(20,0): at System.Security.Cryptography.Cng.Tests.DSACngPkcs8Tests.VerifyMatch(DSACng exported, DSACng imported)
          D:\j\workspace\x86_checked_w---fb0ba759\_\fx\src\System.Security.Cryptography.Cng\tests\CngPkcs8Tests.cs(74,0): at System.Security.Cryptography.Cng.Tests.CngPkcs8Tests`1.NoPlaintextExportAllowsEncryptedPkcs8(PbeEncryptionAlgorithm algorithm)

**Comment by sandreenko** [comment]
I was able to repro it locally, but it fails in 2% runs on my machine.

**Comment by sandreenko** [comment]
assigned to @bartonjs , the issue looks like a windows bug.

**Comment by sandreenko** [comment]
Repro steps:
build CoreFX x86 debug :
`build.cmd -Debug /p:OSGroup=Windows_NT /p:ArchGroup=x86`

Update:
 `corefx\src\System.Security.Cryptography.Cng\tests\CngPkcs8Tests.cs` add several hundred lines of `[InlineData(PbeEncryptionAlgorithm.Aes256Cbc)]` to  `NoPlaintextExportAllowsEncryptedPkcs8`.

Rebuild tests:
`build.cmd -test -SkipTests -Debug /p:OSGroup=Windows_NT /p:ArchGroup=x86`.

Run the test:
```
pushd F:\git\corefx\artifacts\bin\tests\System.Security.Cryptography.Cng.Tests\netcoreapp-Windows_NT-Debug-x86
F:\git\corefx\artifacts\bin\testhost\netcoreapp-Windows_NT-Debug-x86\dotnet.exe xunit.console.dll System.Security.Cryptography.Cng.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=XsltcExeRequired -notrait category=OuterLoop -notrait category=failing -method System.Security.Cryptography.Cng.Tests.DSACngPkcs8Tests.NoPlaintextExportAllowsEncryptedPkcs8

```


I also have found it useful to add `bool result = exported.VerifyData(data, signature, hashAlgorithm); while (!result) {}` to debug it.

**Comment by bartonjs** [comment]
CoreFX finally saw one, too :)

https://github.com/dotnet/corefx/issues/33313

**Comment by bartonjs** [comment]
The fix just went into corefx, so the intermittency should be gone with the next cross-pollenation

**Comment by BruceForstall** [comment]
@bartonjs So is this fixed? Can it be closed?
