### ISSUE TITLE
FileStream.Seek & FileStream.Position does not check if current position is same as desired position

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#20556]
FileStream.Seek and FileStream.Position should check if the current position is same as desired position then bail out early. This avoids having to disregard buffers when using buffered IO.

**Comment by jkotas** [comment]
cc @JeremyKuhne

**Comment by rahku** [comment]
or better yet check if desired position is in buffer and then adjust pointers accordingly

**Comment by benaadams** [comment]
Probably shouldn't call `SetFilePointer` either "Windows Server Performance Team Blog: [Designing Applications for High Performance – Part III](https://blogs.technet.microsoft.com/winserverperformance/2008/06/25/designing-applications-for-high-performance-part-iii-2/)" (June 25, 2008)

> The old DOS SetFilePointer API is an anachronism.  One should specify the file offset in the overlapped structure even for synchronous I/O.

**Comment by JeremyKuhne** [comment]
@benaadams Thanks for the link. 

We've got a lot of serious work to do with FileStream. An overhaul is on our wishlist.

cc: @stephentoub
