### ISSUE TITLE
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b48990\b48990a regression

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#20561]
This regression is caused by #17996.

if we have such IL:
```
    [ 0]  17 (0x011) ldloc.0
    [ 1]  18 (0x012) ldc.r4 2.0000000000000000
    [ 2]  23 (0x017) div
    [ 1]  24 (0x018) conv.r4 <- cast from double to float.
    [ 1]  25 (0x019) ldc.r4 0.00000000000000000
    [ 2]  30 (0x01e) ceq
    [ 1]  32 (0x020) stloc.3
```
then before the change we had:
```
               [000017] ------------              *  STMT      void  (IL 0x011...  ???)
               [000013] ------------              |     /--*  CNS_DBL   float  0.00000000000000000
               [000014] ------------              |  /--*  EQ        int
               [000012] ------------              |  |  \--*  CAST      float <- float
               [000010] ------------              |  |     |  /--*  CNS_DBL   float  2.0000000000000000
               [000011] ------------              |  |     \--*  DIV       float
               [000009] ------------              |  |        \--*  LCL_VAR   float  V00 loc0
               [000016] -A----------              \--*  ASG       int
               [000015] D------N----                 \--*  LCL_VAR   int    V03 loc3
```
but now we do not have this cast `[000012]`.

This cast protected us on x86 with x87 floating point stack.
The next tree in this test is:
```
    [ 0]  33 (0x021) ldloc.3
    [ 1]  34 (0x022) brtrue.s

               [000022] ------------              *  STMT      void  (IL 0x021...  ???)
               [000021] ------------              \--*  JTRUE     void
               [000019] ------------                 |  /--*  CNS_INT   int    0
               [000020] ------------                 \--*  NE        int
               [000018] ------------                    \--*  LCL_VAR   int    V03 loc3
```
when we do `Folding fp operator with constant nodes into a fp constant` for `[000011]` in https://github.com/dotnet/coreclr/blob/f69b623c9f41c5d358d52f40e5cdad808b005bed/src/jit/gentree.cpp#L14136-L14145
on x87 c++ compiler generates:
```
0F407222  fld         dword ptr [f1]  
0F407225  fdiv        dword ptr [f2] <- push a result on stack as qword.  
0F407228  fstp        qword ptr [d1] <- read the result as qword(double).
```
that leaves `d1=7.0064923216240854e-46` and then we propogate it as `LCL_VAR   int    V03 loc3` and fold 
` 0 != 7.0064923216240854e-46  ( [000014] ------------              |  /--*  EQ        int)` to `false`.

on x86 with SIMD C++ generates:
```
00007FFA95D2A819  movss       xmm0,dword ptr [f1]  
00007FFA95D2A81F  divss       xmm0,dword ptr [f2]  <- stores the single-precision floating-point result in the destination operand.
00007FFA95D2A828  cvtss2sd    xmm0,xmm0  
00007FFA95D2A82C  movsd       mmword ptr [d1],xmm0 
```
that sets `d0=0` and works fine.

So on x87 the test return 1 (because everything is collapsed into on false branch), on other platforms 100.

**Comment by mikedn** [comment]
Is there any reason to use x87 on x86?

**Comment by fiigii** [comment]
CoreCLR has targeted to SSE2 as the codegen bottom-line, we should not generate x87 instructions that cannot leverage modern microarchitecture optimizations.

**Comment by sandreenko** [comment]
The issue not in the instruction set, I think code that do folding should call 'forceCastToFloat' for the result.
It is incorrect that we have an implicit cast in IL, but ignore it.

**Comment by AndyAyersMS** [comment]
@sandreeko I'm also confused -- how is x87 relevant? 

And where is the cast? RyuJit is going to operate on floats here and the spec allows this.

This does not seem to fail on CoreCLR, do you know why?
```
Folding fp operator with constant nodes into a fp constant:
               [000010] -----+------              /--*  CNS_DBL   float  2.0000000000000000
               [000011] ------------              *  DIV       float 
               [000009] -----+------              \--*  CNS_DBL   float  1.4012984643248171e-45
Bashed to fp constant:
               [000011] ------------              *  CNS_DBL   float  0.00000000000000000
```
Ah -- see you did an edit above. 

So you are saying is that on desktop we're using an older C++ compiler that does not use SSE2 on x86 by default, and because of this, the prototype desktop x86 ryujit does the jit-time constant folding differently?

**Comment by AndyAyersMS** [comment]
If we forcibly cast the results back to float in `gtFoldExprConst` then it fixes things for jits built with older compilers. For completeness, we'd want to do this for the other float cases too....
```diff
                         f1 = forceCastToFloat(d1);
                         f2 = forceCastToFloat(d2);
-                        d1 = f1 / f2;
+                        d1 = forceCastToFloat(f1 / f2);
```

**Comment by sandreenko** [comment]
> So you are saying is that on desktop we're using an older C++ compiler that does not use SSE2 on x86 by default, and because of this, the prototype desktop x86 ryujit does the jit-time constant folding differently?

Yes.

**Comment by AndyAyersMS** [comment]
I'll put up a PR for this shortly... want to verify desktop devbvts first and look at diffs.

**Comment by mikedn** [comment]
> I'll put up a PR for this shortly... want to verify desktop devbvts first and look at diffs.

Hmm, do you have any heavy FP code that's worth diffing? It's something that the current diff set used in .NET Core lacks.

**Comment by RussKeldorph** [comment]
FWIW it's possible to get even the latest VC++ x86 compiler to do math in x87 if it's optimizing and trying to accomodate the unfortunate ABI:
```asm
>type t.cpp
double divdff(float a, float b)
{
    return a/b;
}


>cl -c -O2 t.cpp -FAs
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.26830 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

t.cpp

>dumpbin /disasm t.obj
Microsoft (R) COFF/PE Dumper Version 14.16.26830.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file t.obj

File Type: COFF OBJECT

?divdff@@YANMM@Z (double __cdecl divdff(float,float)):
  00000000: D9 44 24 04        fld         dword ptr [esp+4]
  00000004: D8 74 24 08        fdiv        dword ptr [esp+8]
  00000008: C3                 ret
```
It may not be relevant to this discussion.  If not, FYI.

**Comment by mikedn** [comment]
> FWIW it's possible to get even the latest VC++ x86 compiler to do math in x87 if it's optimizing and trying to accomodate the unfortunate ABI:

Fortunately such small functions (there are some just like this in VN) will normally inline so the ABI doesn't matter. VC++ is also capable of using a custom calling convention (without x87) if the function doesn't escape.

**Comment by AndyAyersMS** [comment]
Desktop test.devBVT.SelfHost.RyuJIT@x86chk passed with no failures.

Looks like we only collect desktop SPMI for x64 so I am running regular asm diffs for x86 instead.
