### ISSUE TITLE
Use GetPathOfFileAbove where appropriate

### ISSUE THREAD

**Issue by Frassle** [dotnet/coreclr#20582]
There's a number of places in the project files that use a construct like `"$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), dir.props))\dir.props"`, which is equivalent to `"$([MSBuild]::GetPathOfFileAbove(dir.props))"`. That's much clearer to read and less chance of mistakes if these are ever edited. It's a pretty simple find-replace operation to fix it. Would this be accepted as PR or are there reasons to not use GetPathOfFileAbove?

**Comment by RussKeldorph** [comment]
@Frassle We would gladly accept a PR if the proposal is functionally equivalent.

**Comment by echesakovMSFT** [comment]
Just FYI, `GetPathOfFileAbove` is supported since MSBuild 15 (https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0?view=vs-2017)

**Comment by sandreenko** [comment]
> Just FYI, GetPathOfFileAbove is supported since MSBuild 15 (https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0?view=vs-2017)

It means that we would need to require VS-2017 at least and change [our build instruction ](https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md#visual-studio )

**Comment by danmosemsft** [comment]
It was actually CoreFX (me) that originally proposed they add that, in the hope that years later (maybe now) we could actually consume it... 😃

**Comment by Frassle** [comment]
OK, next time on working on some coreclr stuff I'll put together a PR for this.

**Comment by safern** [comment]
Fixed in: https://github.com/dotnet/coreclr/pull/25951
