### ISSUE TITLE
new IDispatch test failing for some arm64 CI runs

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#20580]
@AaronRobinsonMSFT one of these new tests from #20497 is failing on arm64 for tests that normally run in CI for jit changes.

See notes at end of #20553.

CI job history here (failed for the last four jobs, expect this trend will continue):

https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt_innerloop_tst_prtest/

cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
@BruceForstall @jashoo we may want to disable this test for arm64 in the meantime. Can you give me some pointers? I haven't kept up with the current exclusion mechanism....

**Comment by BruceForstall** [comment]
tests\issues.targets. Look for "Windows arm64 specific excludes"

Note nit: "arm64 for tests that normally run in CI for jit changes" -- not true. These run for all changes, but only for people on the Windows arm64 "whitelist" (look for "arm64Users" in netci.groovy). It would be nice to get rid of this whitelist.

**Comment by AaronRobinsonMSFT** [comment]
Boo. Sorry about this @AndyAyersMS. Do you want me to disable this or are you?

**Comment by AndyAyersMS** [comment]
I'll take care of it.

**Comment by AndyAyersMS** [comment]
Just to elaborate -- since I'm on the whitelist a PR coming from me will show that the test actually is disabled.

We should probably add you if we think it's likely your work might somehow be windows arch sensitive.

**Comment by echesakovMSFT** [comment]
Fails on Windows/arm as well  https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_innerloop_tst_prtest/1910/testReport/

**Comment by AaronRobinsonMSFT** [comment]
@davidwrighton Looks like something was missed in the ARM side of things. I don't know why the CI passed though :-/ Care to take a quick look? If it is the same issue, please feel free to send the issue over to me. I am out of office at the moment.

**Comment by jkoritzinsky** [comment]
Looks like this was fixed by #20618 and was never closed.
