### ISSUE TITLE
[x64/windows] test failed with access violation

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#20597]
**job**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_jitstress1/105/#showFailuresLink

**affected test**
Loader_classloader._TypeGeneratorTests_TypeGeneratorTest992_Generated992_Generated992_._TypeGeneratorTests_TypeGeneratorTest992_Generated992_Generated992_cmd 

**Log**
Expected: 100
        Actual: -1073741819
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1

**Comment by BruceForstall** [comment]
fyi, there are also tests in this run that fail with the GC-interesting "Detected use of a corrupted OBJECTREF. Possible GC hole." assert.

**Comment by sandreenko** [comment]
I am looking at GCStress issues that are similar to that one.

**Comment by sandreenko** [comment]
The issue is the same as #21145, so I will close it as a duplicate.
