### ISSUE TITLE
Warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6" were not found

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20596]
the failing job:
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_jitstressregs2_tst/42

failed log:
C:\j\workspace\arm64_cross_c---a958bcc1\Tools\dotnetcli\sdk\2.1.301\Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\j\workspace\arm64_cross_c---a958bcc1\packages\microsoft.dotnet.buildtools\3.0.0-preview1-03309-01\lib\tool-runtime\project.csproj]

**Comment by RussKeldorph** [comment]
Please re-open if you see this again.
