### ISSUE TITLE
MultiplyHorizontalAdd_ro failed in CI job arm64_cross_checked_windows_nt_jitstress2_jitstressregs3_tst

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20593]
the failing job: https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_jitstress2_jitstressregs3_tst/45/

failed log:
TEST_CMD_LINE = JIT\HardwareIntrinsics\X86\Sse2\MultiplyHorizontalAdd_ro> JIT\HardwareIntrinsics\X86\Sse2\MultiplyHorizontalAdd_ro\MultiplyHorizontalAdd_ro.cmd 
TEST_EXPECTED_RETURN_CODE = 0
TEST_ACTUAL_RETURN_CODE = -1 (0xffffffff)

TEST_START_TIME = Mon Oct 08 22:15:48 2018
TEST_END_TIME =   Mon Oct 08 22:15:48 2018
TEST_DURATION =   0.000000 secs

TEST_AUTOMATIONHINT = FAIL - Invalid Working Directory
TEST_AMBIENT_ENVVAR = COMPlus_ContinueOnAssert -> 0
TEST_AMBIENT_ENVVAR = COMPlus_JitStress -> 2
TEST_AMBIENT_ENVVAR = COMPlus_JitStressRegs -> 3
TEST_AMBIENT_ENVVAR = COMPlus_NoGuiOnAssert -> 1
TEST_AMBIENT_ENVVAR = COMPlus_TieredCompilation -> 0

TEST_RESULT = FAILED

**Comment by BruceForstall** [comment]
This is likely a real issue, but the job run is too old. I'm not sure why it hasn't run more recently. I kicked off another run: https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_jitstress2_jitstressregs3_flow/52/.
