### ISSUE TITLE
coreclr_create_delegate corrupts memory under x86, but not x64

### ISSUE THREAD

**Issue by lstratman** [dotnet/coreclr#2059]
I have a [project](https://github.com/medicomp/edge) that serves as a bridge between Node.js and .NET and have recently updated it to support CoreCLR; it is native code that is bootstrapping CoreCLR and then calling coreclr_create_delegate to get pointers to various CLR methods that serve as an interop layer.  Everything works great when the project is compiled as an x64 binary and I use an x64 version of CoreCLR.  However, when I compile under x86 and use an x86 version of CoreCLR, coreclr_create_delegate seems to corrupt memory and I end up with access violation exceptions either in the midst of my set of coreclr_create_delegate calls or when trying to return the the calling function.  I have created a [test application](https://www.dropbox.com/s/k620izxr1xtt591/testdelegate.zip?dl=0) to demonstrate the issue.  To use it:

1. Extract both files in the .zip to an empty directory.
2. With a VS x64 native tools command prompt open, compile with `cl /EHsc testdelegate.cpp`
3. Run `testdelegate.exe`; it should run successfully and (in addition to a bunch of logging) display "Finished creating CLR delegates, test successful" at the end.
4. Now open a VS x86 native tools command prompt and recompile with the same command line as above.
5.  Re-run the program.  This time, it should crash with an access violation exception either in the middle of the set of coreclr_create_delegate calls or when it tries to return to the calling function.

The actual calls to coreclr_create_delegate are wrapped in a macro defined on line 67 and the various calls to this macro are in the CreateDelegates function defined on line 87.

If you need any more information from me, don't hesitate to ask.

**Comment by lstratman** [comment]
Also, I have tested this using the latest stable (1.0.0-beta8) and unstable (1.0.0-rc2-16177) builds.

**Comment by janvorli** [comment]
I'll take a look, thanks @lstratman for reporting the problem.

**Comment by joncham** [comment]
I am guessing this is an issue with calling convention. On x64 there is only one. On x86 there is multiple and default calling convention when marshaling delegates is STDCALL. I see in your binding code that you are not marking your function pointer typedefs with STDCALL. For example:

`typedef void (*FreeHandleFunction)(CoreClrGcHandle handle);`

needs to be

`typedef void (STDMETHODCALLTYPE *FreeHandleFunction)(CoreClrGcHandle handle);`

**Comment by joncham** [comment]
You can either use STDCALL on the native typedefs, or perhaps mark the delegates in C# with an attribute to define their default marshaling behavior.

**Comment by lstratman** [comment]
That seems to have done the trick:  I added `STDMETHODCALLTYPE` to the typedefs for my .NET delgates and also to the typedefs for `coreclr_initialize` and `coreclr_create_delegate`.  Thanks, @joncham!

Closing the issue.
