### ISSUE TITLE
GC eventually deadlocks? entire program with large self referential data set

### ISSUE THREAD

**Issue by ala53** [dotnet/coreclr#206]
In simple terms: I think I broke the garbage collector

This project here - https://github.com/ala53/clr_gc_deadlock/ - builds an index of the English dictionary along with building links to each word for further processing. Unfortunately, single or multithreaded, console or wpf, the GC ends up eating more and more of the CPU time the more we begin building links to the definition to the point that it eventually locks up the entire program, including the UI thread, permanently. It seems that the GC cannot handle all of the self referential hashtables. I've tried server GC (which improved but did not fix the problem), batch, LOH compaction, etc. Nothing has kept the garbage collector from eventually locking up the program.

For the lazy, what I'm doing in the linked project is this:

List<Word> Dictionary;

Then each word (thousand mile overview) is this:
string Word
List<Word> Definition; (this is just a pointer to a word class in the List, not a separate instance per word)

Unfortunately, there's 86,000 words with 100 or 200 pointers to words in the definition. Then there's about 11 properties in each word and maybe 30-40 strings allocated.

So, there's maybe 5 million objects on the heap and a billion or so references to words being tracked. Normally, I'd understand where latency could happen, but there is nothing to garbage collect at any point because there is no deallocation (past the first phase, which runs fine), just allocation of new words.

**Comment by OtherCrashOverride** [comment]
> So, there's maybe 5 million objects on the heap and a billion or so references to words being tracked. 

Sounds to me like you are simply out of memory.  The lock up you are seeing is probably the OS trying to swap memory to and from disk.

**Comment by mikedn** [comment]
This piece of code is very likely wrong:

```C#
bool alltasksdone = false;

while (!alltasksdone)
{
    foreach (var task in tasks)
        if (task.IsAlive)
            alltasksdone = false; // should be true, as is now you'll never get out of this loop
    Task.Delay(100);
}

```
>So, there's maybe 5 million objects on the heap and a billion or so references to words being tracked.

I don't know how you estimated "a billion or so references" but when the program gets stuck the memory usage is around 300 megabytes. You can't possible store a billion references in 300 megabytes, you need 4 or 8 gigabytes just for the references.

**Comment by stephentoub** [comment]
> This piece of code is very likely wrong

In addition to the issue @mikedn calls out in the code, the "Task.Delay(100)" as written is nop.  It's creating a Task that will complete after ~100ms, but that Task is then just being dropped on the floor.  You either need to await it, or .Wait it, or something similar.
