### ISSUE TITLE
Dependency resolution issues within net framework unit tetst class

### ISSUE THREAD

**Issue by maximburyak** [dotnet/coreclr#20606]
This issue replicates when referencing nuget package with embedded kestrel dlls from unit test class library, that also references aspnetcore.

Please take a look into this repro repository: https://github.com/maximburyak/EmbeddedProjectsReferenceIssue

I'm not sure if it's a coreclr issue or mstest issue, probably something in between, because for some reason, only when using tests infrastructure, the embedded dlls from the package, that should have been addressed like any other "resource" are used in the build process, and on the other hand, coreclr is not able to choose one "right" version for all packages and is not able to build correctly, but does not fail, instead, it issues the warning: 

`warning MSB3277: Found conflicts between different versions of "System.Memory" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed`

And when running using mstest infrastructure to run the test using dotnet test (or when running the test from visual studio) the next message received:
`The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
No test is available in `

**Comment by jeffschwMSFT** [comment]
@livarcocc do you feel that once we unify build and publish if this issue may be addressed?

**Comment by jeffschwMSFT** [comment]
@nguerrera @dsplaisted @livarcocc can y'all take a look at this issue?  It feels related to the SDK.

**Comment by dsplaisted** [comment]
This looks to me like an issue in https://github.com/microsoft/vstest, or if not then the test infrastructure would need to be involved in getting more details about why exactly this is failing.

**Comment by jeffschwMSFT** [comment]
Moved to https://github.com/microsoft/vstest/issues/2011
