### ISSUE TITLE
JIT_Regression._CLR_x86_JIT_V1_M09_b13621_b13621_b13621_._CLR_x86_JIT_V1_M09_b13621_b13621_b13621_cmd Failed with access violation

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#20600]
**job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_jitstress2/104/#showFailuresLink

**Log:**
Expected: 100
        Actual: -1073741819
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1

**Comment by BruceForstall** [comment]
This is a relatively old run. I kicked off a new one: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_jitstress2/

**Comment by sandreenko** [comment]
It is dup of #20519.
Was fixed by #20701.
