### ISSUE TITLE
Assertion failed '(genRegMask(argReg) & RBM_ARG_REGS) != RBM_NONE'

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20629]
the failing job: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_jitincompletehwintrinsic/265

failed tests:

- JIT_jit64._mcc_interop_mcc_i33_mcc_i33_._mcc_interop_mcc_i33_mcc_i33_cmd
- JIT_jit64._mcc_interop_mcc_i03_mcc_i03_._mcc_interop_mcc_i03_mcc_i03_cmd
- JIT_jit64._mcc_interop_mcc_i63_mcc_i63_._mcc_interop_mcc_i63_mcc_i63_cmd
- JIT_jit64._mcc_interop_mcc_i73_mcc_i73_._mcc_interop_mcc_i73_mcc_i73_cmd
- JIT_jit64._mcc_interop_mcc_i13_mcc_i13_._mcc_interop_mcc_i13_mcc_i13_cmd
- JIT_jit64._mcc_interop_mcc_i53_mcc_i53_._mcc_interop_mcc_i53_mcc_i53_cmd

failed log:
JIT_jit64._mcc_interop_mcc_i73_mcc_i73_._mcc_interop_mcc_i73_mcc_i73_cmd [FAIL]
        
        Assert failure(PID 10620 [0x0000297c], Thread: 11564 [0x2d2c]): Assertion failed '(genRegMask(argReg) & RBM_ARG_REGS) != RBM_NONE' in 'MCCTest.MyClass:GetSum2(double,int,long,float,short,double):struct' (IL size 5)
        
            File: d:\j\workspace\x64_arm64_alt---d3160b11\src\jit\codegenarmarch.cpp Line: 2719
            Image: D:\j\workspace\x64_arm64_alt---d3160b11\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
        
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x64_arm64_alt---d3160b11\bin\tests\Windows_NT.x64.Checked\Reports\JIT.jit64\mcc\interop\mcc_i73\mcc_i73.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x64_arm64_alt---d3160b11\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" mcc_i73.exe 
        Expected: 100
        Actual: -1073740286
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x64_arm64_alt---d3160b11\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
  > D:\j\workspace\x64_arm64_alt---d3160b11\bin\tests\Windows_NT.x64.Checked\JIT\jit64\mcc\interop\mcc_i73\mcc_i73.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x64_arm64_alt---d3160b11\bin\tests\Windows_NT.x64.Checked\TestWrappers\JIT.jit64\JIT.jit64.XUnitWrapper.cs(23139,0): at JIT_jit64._mcc_interop_mcc_i73_mcc_i73_._mcc_interop_mcc_i73_mcc_i73_cmd()

**Comment by sandreenko** [comment]
Fixed by #21018

**Comment by jashook** [comment]
This is still an open issue. Have a fix.

**Comment by sandreenko** [comment]
Fixed by @jashook & @briansull PR #22656.
Passed in ci today.
