### ISSUE TITLE
ExecuteScalarAsyncErrorTest failed in CI job x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs0x10

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20626]
the failing job: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs0x10/337

failed test:

- System.Data.SqlClient.Tests.DiagnosticTest.ExecuteScalarAsyncErrorTest

 [FAIL]

failed log:
System.Data.SqlClient.Tests.DiagnosticTest.ExecuteScalarAsyncErrorTest [FAIL]
        **Timed out** after 60000ms waiting for remote process 7084
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x64_arm64_alt---33b67f3c\_\fx\src\CoreFx.Private.TestUtilities\src\System\Diagnostics\RemoteExecutorTestBase.cs(351,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing)

**Comment by jiangzeng** [comment]
Similar sql connection time out issue in [jitstress » x86_arm_altjit_checked_windows_nt_corefx_jitstress2](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstress2/329/testReport/junit/System.Data.SqlClient.Tests/DiagnosticTest/ExecuteScalarAsyncTest/) : 

System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=689; handshake=2573; [Login] initialization=101; authentication=143; [Post-Login] complete=1486;  ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.

**Comment by BruceForstall** [comment]
I don't see this in current runs; closing.
