### ISSUE TITLE
Regressions in span indexer performance

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#20678]
We seem to have had a recent regression in the span indexer performance tests. 

Thanks to @jorive for bringing this to my attention.

Impacted tests are: Indexer2, Indexer4, Indexer5, Indexer6, ReadOnlyIndexer2,  SameIndex2, WriteViaIndexer1, and WriteViaIndexer2.

Likely suspect is #20113 (based on Benchview).

Diff of recent master for `TestIndexer2` vs 2.2 shows we're now failing to eliminate a bounds check:

```asm
;; 2.2
G_M37174_IG03:
       4D63C8               movsxd   r9, r8d
       460FB60C08           movzx    r9, byte  ptr [rax+r9]
       4433C9               xor      r9d, ecx
       410FB6C9             movzx    rcx, r9b
       41FFC0               inc      r8d
       443BC2               cmp      r8d, edx
       7CE9                 jl       SHORT G_M37174_IG03

;; master
G_M37174_IG03:
       413BD0               cmp      edx, r8d
       731B                 jae      SHORT G_M37174_IG05
       4C63CA               movsxd   r9, edx
       460FB60C09           movzx    r9, byte  ptr [rcx+r9]
       4433C8               xor      r9d, eax
       410FB6C1             movzx    rax, r9b
       FFC2                 inc      edx
       413BD0               cmp      edx, r8d
       7CE5                 jl       SHORT G_M37174_IG03
```

@sandreenko can you investigate?
cc @dotnet/jit-contrib

**Comment by sandreenko** [comment]
@AndyAyersMS  yes, will start shortly. Thanks for bringing this up.

**Comment by AndyAyersMS** [comment]
Sample Benchview result:

![image](https://user-images.githubusercontent.com/10121823/47685362-843bff00-db93-11e8-9f1a-f751632c0e7f.png)

**Comment by AndyAyersMS** [comment]
You can run `jit-diff` over the test assemblies, but it's not commonly done as it takes a while and runs into issues at times (see dotnet/jitutils#156).


I usually don't do a full sweep over tests, but instead look at selected tests (via `jit-diff diff --assembly`) where I expect to see impact.

But that doesn't help spot cases with unexpected impacts.

Maybe our forthcoming automation of jit-diffs in CI will give us better chances to spot unexpected impact.
