### ISSUE TITLE
[Perf] [illink] Update ILLink tests to reference VS2017

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#20671]
We have upgraded the VM pool that the illink jobs use to a helix queue that only has VS2017 installed to fix the coreclr build issue. However, this has broken the ILLink jobs, which have hard-coded requirements on VS2015. This is manifesting in the following failure:

https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_illink_Windows_NT_x64_full_opt_ryujit/3064/console

```
07:00:22 D:\j\w\perf_illink_W---e8877b83>"\..\..\VC\vcvarsall.bat" x86_amd64   && py tests\scripts\run-xunit-perf.py -arch x64 -configuration Release -os Windows_NT -generateBenchviewData "D:\j\w\perf_illink_W---e8877b83\Microsoft.Benchview.JSONFormat\tools" -uploadToBenchview -runtype rolling  -optLevel full_opt -jitName ryujit -outputdir "D:\j\w\perf_illink_W---e8877b83\bin\sandbox_logs" -scenarioTest -testBinLoc bin\tests\Windows_NT.x64.Release\performance\linkbench\linkbench -group ILLink -nowarmup 
07:00:22 The system cannot find the path specified.
```

Therefore, the ILLink jobs need to be updated to use VS2017 instead of VS2015, and the perf.groovy needs to be updated to not reference 2015 as well.

**Comment by adiaaida** [comment]
@swaroop-sridhar @sbomer PTAL

**Comment by adiaaida** [comment]
This will need to be updated in both master and release/2.2

**Comment by sbomer** [comment]
Closing in favor of https://github.com/dotnet/coreclr/issues/25239.
