### ISSUE TITLE
"MC Not Found" when running cmake (Visual Studio 2017)

### ISSUE THREAD

**Issue by amelvill** [dotnet/coreclr#20672]
I get "MC Not Found" when I try to generate Visual Studio 2017 solutions using `cmake ..` in a "build" directory I created, it looks like I meet all of the prerequisites.

Here is my console output:

```
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.15.26732.1
-- The CXX compiler identification is MSVC 19.15.26732.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- VS_PLATFORM_TOOLSET is v141
-- VS_PLATFORM_NAME is Win32
-- The ASM_MASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/ml.exe
CMake Error at CMakeLists.txt:94 (message):
  MC not found


-- Configuring incomplete, errors occurred!
See also "/coreclr/build/CMakeFiles/CMakeOutput.log".
See also "/coreclr/build/CMakeFiles/CMakeError.log".
```

If the error is referring to MC.exe, I am not sure why cmake couldn't find it, if I start the Visual Studio 2017 developer command prompt I can run MC.exe. Do I need to specify its path when I run cmake?

If it matters I have both VS 2015 and VS 2017 installed on this computer.

Running build.cmd seemed to work (I only had one warning) so I would guess that there's just something wrong on the cmake side. 

The build.cmd setup works good for me so this isn't a pressing issue, just thought I'd mention this, I remember cmake did work at one point in the past for Windows though I don't remember exactly when. According to the [documentation page](https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md#cmake) cmake should still work for coreclr on Windows.

**Comment by RussKeldorph** [comment]
I don't think we have any supported scenarios around invoking `cmake` directly.  That said free to contribute a PR making this work if you're interested.
