### ISSUE TITLE
Add support for native threads

### ISSUE THREAD

**Issue by xoofx** [dotnet/coreclr#20691]
Hi,

(This might be an issue more suitable for corefx?, but let's start the discussion here just to get some bootstrap feedback)

Today, we can only create managed threads, taking a managed delegate. But in some cases, we would like to be able to to run native threads by passing a native pointer to the start function directly, so that this native thread could run native code without being interrupted by the GC.

The runtime is already using internally an abstraction around the threading but this is a quite annoying to have to redo this abstraction in our own .NET app (or through a pinvoke and C++ abstraction)

Would it be desirable/feasible to provide an API to create/managed native threads directly from C#?

**Comment by jkotas** [comment]
If you create managed thread and the only thing you do on that managed thread is to call your unmanaged method, the GC suspension will not ever stop that thread while running your unmanaged method in .NET Core. Properly implemented  GC suspension should see that this thread is running unmanaged code and leave the thread alone.

**Comment by xoofx** [comment]
Oh, really, didn't know about this for .NET Core, that's nice!
Will give a try, thanks!
