### ISSUE TITLE
clr and Win-Fibers: clr's CLRVectoredExceptionHandler crashes process

### ISSUE THREAD

**Issue by tobias-loew** [dotnet/coreclr#20715]
Hi,

I've got a native Windows-process that also loads some dlls containing managed code and therefore also loads the clr.
In the native C++ code I use Win-Fibers. The code in the Fibers is native-ONLY.
When I throw a C++ - exception in the Fiber the process crashes (as also reported here https://github.com/dotnet/coreclr/issues/17669).

The reason seems to be that `Thread::IsStackSpaceAvailable` (in https://github.com/dotnet/coreclr/blob/master/src/vm/threads.cpp) returns `FALSE` since it compares `GetLastNormalStackAddress` (which uses `m_CacheStackLimit` which is cached from a call on the NON-FIBER stack) to the `GetCurrentSP` (which belongs to the Fiber's stack and is unrelated to the former)

There are two possible solutions to this:
- the easy one: do not cache stack-limits like `m_CacheStackLimit` but always evaluate on the current stack
- the hard one: get Fiber-aware and if Fibers are present then cache the limits in Fiber-local-storage

**Comment by jkotas** [comment]
Fibers are not supported by .NET: https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-and-unmanaged-threading-in-windows#threads-and-fibers

**Comment by tobias-loew** [comment]
I understand that .net does not support Fibers, but the problem is:
If the clr is loaded then due to the Vectored Exception Handling even plain C++ exceptions on a native-only stack trigger the execution of the clr/.net Exception-Handler. Thus even so the .net/clr does not support Fibers, its exception handlers should be aware that Fibers exist.
Otherwise perfectly valid code gets corrupted only by accidentally loading some managed code into the process.

**Comment by jkotas** [comment]
I think hardening the Vector Exception Handler for fibers would make sense. It may be best to detect that we are running on a fiber and exit as early as possible. Are you interested in proposing a change to do that? 

cc @janvorli

**Comment by tobias-loew** [comment]
I've made a PR https://github.com/dotnet/coreclr/pull/20746
Please have a look at it since I'm not familiar with the coding guidelines of this project. 
Thanks!

**Comment by jkoritzinsky** [comment]
Now that #20746 is merged in, should this issue be closed?

**Comment by jkotas** [comment]
Agree
