### ISSUE TITLE
ARM64 atomics: crash with ldaddal instruction

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#20721]
Enable JIT_FLAG_HAS_ARM64_ATOMICS, perhaps by setting it manually in compiler.cpp,  Compiler::compCompile(). Then do a PMI run over System.Private.CoreLib.dll. The method `System.SharedStatics:AddMemoryFailPointReservation(long):long` has an interlocked add -- XADD -- that is generated with a ldaddal instruction (when atomics are enabled). But it fails with a `NO_WAY("unexpected instruction")` in `emitter::emitInsTargetRegSize` during emission. (Note: it will attempt to re-jit in MinOpts mode.)

**Comment by BruceForstall** [comment]
cc @CarolEidt

**Comment by sdmaclea** [comment]
For 3.0 it might be sufficient to disable this code until we have hardware to test it.  As is an ARMv8.1 feature most hardware does not yet support it.

**Comment by mikedn** [comment]
Hmm, atomics, I can take a look

**Comment by mikedn** [comment]
Eh, this is just in the emitter disassembly code. It's unnecessarily pedantic, it should simply return `idOpSize()` for instructions that it doesn't recognize since only a few really need special handling.

**Comment by AndyAyersMS** [comment]
I'll take a look.

**Comment by mikedn** [comment]
Oops, I completely forgot about this. I think I fixed it back then but never made a PR for it, if only I can find the branch...

**Comment by AndyAyersMS** [comment]
Great, let me know.

I wonder if we have access to any arm64 HW where atomics are supported?

**Comment by mikedn** [comment]
I certainly don't have access to such HW. I just check if the emitted bytes match the instruction encoding from manuals.

I found my fix, I simple added `ldaddal` to `emitInsTargetRegSize`. I'll take another look and send a PR later today, no point in wasting your time with this.
