### ISSUE TITLE
CodeGenBringUpTests/Rotate.cs forgets third constructor parameter

### ISSUE THREAD

**Issue by ViciousPotato** [dotnet/coreclr#2072]
Line 291
https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/CodeGenBringUpTests/Rotate.cs#L291

Obviously Test constructor takes third parameter. Error jenkins log from last *successful* run:

> 22:20:57 Rotate.cs(291,25): error CS7036: There is no argument given that corresponds to the required formal parameter 'k' of 'Test.Test(ulong, uint, ushort)' [d:\j\workspace\dotnet_coreclr\debug_windows_nt\tests\src\JIT\CodeGenBringUpTests\Rotate.csproj]

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/debug_windows_nt/219/consoleFull

@erozenfeld

**Comment by mmitche** [comment]
@jaredpar @ViciousPotato It looks like it knew the test build failed, but didn't exit:

%_buildprefix% %_msbuildexe% "%__ProjectFilesDir%\build.proj" %__MSBCleanBuildArgs% /nologo /maxcpucount /verbosity:minimal /nodeReuse:false %_buildParameters% /fileloggerparameters:Verbosity=diagnostic;LogFile="%__TestManagedBuildLog%";Append %* %_buildpostfix%
IF ERRORLEVEL 1 echo Test build failed. Refer to !__TestManagedBuildLog! for details && exit /b 1
exit /b 0

**Comment by jaredpar** [comment]
@mmitche yep.  This line seems to be the culprit

https://github.com/dotnet/coreclr/blob/master/tests/buildtest.cmd#L169
