### ISSUE TITLE
Slow cast ushort -> char

### ISSUE THREAD

**Issue by iSazonov** [dotnet/coreclr#20747]
I'd expect that cast ushort -> char has zero delay but I discovered that second sample in code below is much slower. Is it expected?
```c#
public static readonly char[] table1 = new char[]
        {
            (char)0,
            (char)1,
            (char)2,
            (char)3,
            (char)4
        }

char a = table1[0];

public static readonly ushort[] table1 = new ushort[]
        {
            0,
            1,
            2,
            3,
            4
        }

char a = (char)table1[0];
```

**Comment by mikedn** [comment]
Can you post a more complete example that shows what and how did you measure? A quick test doesn't show anything unexpected in the code generated for `char a = (char)table1[0];` so perhaps you're seeing a different problem? Like some issue with the way static constructors are run.

**Comment by iSazonov** [comment]
@mikedn Thanks! You are right. I prepare simple test and can not repo. Seems it is an edge issue for "ushort to char cast with using static array in `for loop". I'll close the issue because I already rewrite my code with ref and char type and see many unresolved reports in the repo for edge cases.

(For history reference, my work is tracked in https://github.com/PowerShell/PowerShell/issues/8120)
