### ISSUE TITLE
JIT ETW event signatures for ref readonly methods

### ISSUE THREAD

**Issue by szehetner** [dotnet/coreclr#20754]
The Jit Inlining Events (e.g. "Method/InliningFailedAnsi", ID 186) produce a strange signature for ref readonly methods. Consider the following program:

```csharp
class Program
{
    private static long a;
    public static ref readonly long Foo(bool b) => ref a;
    public static ref readonly long Foo(int i) => ref a;

    static void Main(string[] args)
    {
        Foo(true);
        Foo(1);
    }
}
```
When this is run, 2 InliningFailed events are emitted, but both have the same InlineeNameSignature: 
`required_modifier System.Runtime.InteropServices.InAttribute  (int64&)`. This doesn't seem to follow the pattern of other InlineeNameSignatures I have seen; the return type for ref readonly methods seems to always be "required_modifier System.Runtime.InteropServices.InAttribute" and the actual return type is in the parameter list. Because the actual parameter types are missing, it is impossible to distinguish two overloads.

I would expect something similar to a method with a ref return value, e.g. the method 
```csharp
public static ref long Foo(int i) => ref a;
```
has an InlineeNameSignature of `int64&  (int32)`

Is this a bug or by design? Can this be changed so overloads can be distinguished?

**Comment by szehetner** [comment]
cc @AndyAyersMS

**Comment by jkotas** [comment]
This is bug in https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/utilcode/prettyprintsig.cpp#L690

The method should not exit after printing modifier. Instead, it needs to reloop to print the actual type.

**Comment by jkotas** [comment]
@szehetner Are you interested in submitting a fix for this?

**Comment by szehetner** [comment]
Yes, I'll give it a try.
