### ISSUE TITLE
Handling SIGTERM in asp.net core middleware in docker container

### ISSUE THREAD

**Issue by meanin** [dotnet/coreclr#20765]
Hi All,
is it possible at all? I created simple asp.net core application [here](https://github.com/meanin/talk_zero_downtime_deployment_with_kubernetes/tree/master/demo_net). The application is running in linux docker container. Now, I am trying to implement graceful shutdown, with waiting for current request completion. I tried many different ways, starts from `AppDomain.CurrentDomain.ProcessExit += OnProcessExit`, going trough `Console.CancelKeyPress += ConsoleOnCancelKeyPress` and finished on `AssemblyLoadContext.Default.Unloading += OnUnloading`. I tried to place it inside a middleware as well as on top of program.cs. I am stoping docker with command below:
`docker stop -t 30 containerId`
Docker documentation says, that this should cause SIGTERM on a first try, wait given time and raise SIGKILL.

I already saw issues:
https://github.com/aspnet/Hosting/issues/870
https://github.com/aspnet/Hosting/issues/1527
https://github.com/dotnet/coreclr/issues/2688
https://github.com/dotnet/coreclr/issues/8565

Any guess?

**Comment by davidfowl** [comment]
Graceful shutdown already works out of the box with ASP.NET Core so there’s no need to re-implement it.

**Comment by meanin** [comment]
Is this the reason, why I cannot get any of these events while debbuging?

**Comment by davidfowl** [comment]
Maybe? I’m not sure about that but I know you can delete your code because it’s handled

**Comment by meanin** [comment]
Tested in a 2 .net core application:
1. generic host [here](https://github.com/meanin/dotnetcore-service-sample)
2. generic host alongside with asp.net application [here](https://github.com/meanin/sigterm-demo)

In both cases, I wasn't able to catch this while debugging, while running container in interactive mode shows log messages on all events.

The last thing that I want to test is IApplicationLifetime on docker container interactive. I suspect that it will be working, but again, I won't be able to debug.

Regards

**Comment by meanin** [comment]
I can confirm that all of the solutions are working on `docker run -it` mode. Issue closed.
