### ISSUE TITLE
[corefx_jitstress] error CS0115: 'DebugTests.WriteLogger.ShowDialog(string, string, string, string)': no suitable method found to override

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#20777]
I saw this locally as well in CI https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_corefx_jitstress1_prtest/7/console
```
16:33:18 Build FAILED.
16:33:18 
16:33:18 
DebugTests.cs(108,34): error CS0115: 'DebugTests.WriteLogger.ShowDialog(string, string, string, string)': no suitable method found to override [/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstress1_prtest/_/fx/src/System.Diagnostics.Debug/tests/System.Diagnostics.Debug.Tests.csproj]
16:33:18     0 Warning(s)
16:33:18     1 Error(s)
16:33:18 
16:33:18 Time Elapsed 00:05:04.79
16:33:18 Build failed (exit code '1'). See log: /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstress1_prtest/_/fx/eng/common/../../artifacts/log/Release/Build.binlog
16:33:18 [/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstress1_prtest/tests/scripts/run-corefx-tests.py]: Error: exit code 256
16:33:18
```

**Comment by jkotas** [comment]
The CoreCLR and CoreFX is out of sync right now. The failure will go away once they are in sync again.

The jitstress CI legs need to be switched over to use stable CoreFX test snapshot like what the CoreFX tests are using to avoid hitting temporary problems like these.

**Comment by jiangzeng** [comment]
Similar issue found in **x64_checked_ubuntu_corefx_baseline**
[https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_baseline/lastFailedBuild/](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_baseline/lastFailedBuild/)

**Comment by BruceForstall** [comment]
I forgot that first build corefx, which includes a copy of coreclr downloaded from packages (I think), and _then_ we copy over our built coreclr on top of that, _before_ we build the corefx tests. So apparently the test build is referencing our built/copied coreclr?

Perhaps we could/should build the corefx test build using the downloaded/package coreclr, and only after the tests are built, overwrite the coreclr with our built one. Then, run the tests.

The corefx scripts haven't supported splitting the "build tests" and "run tests" functionality, at least not that I've found. You can build without running using the `-SkipTests` argument to `build.sh`. But if you do that, is there an easy way to run the tests? For arm/arm64 we use the `tests/scripts/run-corefx-tests.sh` script. For non-cross builds, we could use this as well as `run-corefx-tests.bat` for Windows. But neither of those is really the "official" way to run tests. Is there a better option?

@jkotas When do expect this "out of sync" problem to be resolved?

**Comment by jkotas** [comment]
> Perhaps we could/should build the corefx test build using the downloaded/package coreclr, and only after the tests are built, overwrite the coreclr with our built one. Then, run the tests.

Right. There are more ingredients to make this work well though:

1. The known good copy of the corefx tests. This copy can be:
    - Either downloaded binaries. It is what the PR default CoreFX legs do.
    - Or built from a known corefx repo label as you have said. It takes more time and has more moving parts. It is what we have historically done for the optional CoreFX legs in CoreCLR.
2. Exclusion list with list of CoreFX tests that are failing momentarily. It is at https://github.com/dotnet/coreclr/blob/master/tests/CoreFX/CoreFX.issues.json for the PR default CoreFX legs
3. Script to combine and run 1. + 2. above. This script that does this for the PR default legs is at https://github.com/dotnet/coreclr/tree/master/tests/src/Common/CoreFX .

> When do expect this "out of sync" problem to be resolved?

Once https://github.com/dotnet/corefx/pull/33210 goes through.

**Comment by BruceForstall** [comment]
> Once dotnet/corefx#33210 goes through.

Looks like that got abandoned. Now we have https://github.com/dotnet/corefx/pull/33301 which is still failing.

Long-term, we should replace our usage of run-corefx-tests.py with the mechanism used by the default PR CoreFX jobs. That is, we should extend the default PR CoreFX jobs to be able to support cross-targeting, and stress modes.

I'm wondering if there are simple changes that would make our run-corefx-tests.py system work better. We haven't had problems like this before, once we moved to the current build model. So maybe we just deal with it, and hope the corefx breaking change propagates through soon, and everything gets back to working.

**Comment by BruceForstall** [comment]
@echesakovMSFT  This issue seems to be resolved. I kicked off basically all corefx jobs in CI to verify.
