### ISSUE TITLE
Differenct Daylight Saving Time detection than Windows

### ISSUE THREAD

**Issue by lertoo** [dotnet/coreclr#20798]
Date: November 5, 2018
TimeZoneKeyName: AUS Eastern Standard Time
Display: (UTC+10:00) Canberra, Melbourne, Sydney
Adjust for dalight saving time automatically: On

When registry:
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation]
"DynamicDaylightTimeDisabled"=dword:00000001

Windows display the current time as AUS EDST, however, .NET Framework (4.7.2) display non-DST.
For instance: 
 When Windows display 3:02 PM (daylight saving time),
 TimeZoneInfo.Local.SupportsDaylightSavingTime is False;
 DateTimeOffset.LocalDateTime displays 2:02 PM (non-daylight saving time).

How .NET Fraemwrok handling DST is different than Windows, this cause lots of confusions - users see DST in Windows, however applications display standard time. The problem is in TimeZoneInfo class.

**Comment by lertoo** [comment]
When DynamicDaylightTimeDisabled is true (1), the Windows lock screen shows standard time rather than daylight saving time.
The the registry is changed, there is a need to restart the machine to take effect.

**Comment by RussKeldorph** [comment]
@tarekgh

**Comment by tarekgh** [comment]
@lertoo I think .NET working as expected but your question more why Windows didn't reflect the change you made in the registry. as you figured it, Windows may need to reboot. I am wondering did you try to disable the daylight saving option change that in Windows setting UI instead of directly editing the registry? I believe at that time you will not need to reboot and the change will be reflected on Windows.

I am closing the issue but feel free to reply back with any question.

**Comment by lertoo** [comment]
No - Windows reflected the change but not .NET.

Simply change the registry to:
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation]
"DynamicDaylightTimeDisabled"=dword:00000001

Check Windows clock time and the value of "new DateTimeOffset().LocalDateTime", you will see the issue.

**Comment by tarekgh** [comment]
Look at the doc https://docs.microsoft.com/en-us/windows/desktop/api/timezoneapi/ns-timezoneapi-dynamic_time_zone_information which is explaining the meaning.

```
To disable daylight saving time, set this member to TRUE, clear the StandardDate and DaylightDate members, and call SetDynamicTimeZoneInformation. To restore daylight saving time, call SetDynamicTimeZoneInformation with DynamicDaylightTimeDisabled set to FALSE.
```

in short, DynamicDaylightTimeDisabled=1 means you are disabling the daylight saving. and DynamicDaylightTimeDisabled=0 means you are enabling the daylight saving. So, .NET working as expected.

Now, you may think this is a Windows problem but I am not sure either if this is true as Windows doesn't support manipulating the registry key manually and you need to do it through Windows Settings so Windows can react to the change. or you need to reboot the machine.
