### ISSUE TITLE
Garbage collection of Memory<T>after a Slice()

### ISSUE THREAD

**Issue by hpbieker** [dotnet/coreclr#20791]
Say you have the following code:
```
var buffer = new byte[100 * 1024];
var memory = new Memory<byte>(buffer);

var memorySlice = memory.Slice(0, 1);
buffer= null;
memory = null;
```

It looks like the GC will not garbage collect `buffer` because `memorySlice` still have a reference to it. Wouldn't it make sense that the GC removed the parts of `buffer` that is no longer referenced?

**Update**:  Changed from `Span()` to `Slice()` in text and code above.

**Comment by mikedn** [comment]
Perhaps it might make sense but this isn't exactly easy - the GC doesn't know about Span, it only knows about "interior" pointers. If such a pointer is encountered then the entire object is kept alive. Attempting to keep track of span's length, figure out which part(s) of the object are referenced by live span(s) (keep in mind that you can create a bunch of spans for different parts of an object) and actually slicing the GC heap object by creating the appropriate object headers is an enormous undertaking.

**Comment by Joe4evr** [comment]
Arrays can't be resized, so in order to view just a small part of the array in `memorySpan`, the entire array needs to stay in memory.

**Comment by svick** [comment]
@Joe4evr But in the code above, you don't have a legitimate way to access the array itself, only one part of its memory.

So I think it would be acceptable to deallocate the parts of the array that are no longer accessible (including the object header).

(Whether it's practical is another question entirely.)

**Comment by hpbieker** [comment]
I understand that it would require some effort. But I think this would be useful.

Say you need to create an array/list like object, but do not know how many elements it will include until you reach the end of your stream.
```
var list = new List<object>();
while (notEndOfFile)
  list.Add(someObject);
return list.ToArray();
```

If you instead could to something like:
```
var mb = MemoryBuilder<object>();
while (notEndOfFile)
  mb.Add(someObject);
return mb.CreateMemory();
```

You wouldn't not have to allocate yet another array/list to do `ToArray()`, but the GC would still be able to remove the excess bytes allocated if a GC was triggered.

And as @svick points out, it does not have to be an array object anymore because `Memory<T>` does not expose object, only the memory it contains. The only reason why it exists is because `memorySpan` have a reference to an object which happens to be an array.

**Comment by svick** [comment]
@hpbieker 

> `Memory<T>` does not expose object, only the memory it contains

I should have been more explicit: `Span<T>` does not expose the array, but [`Memory<T>` does](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.memorymarshal.trygetarray?view=netcore-2.1). So if this was implemented, I think it could only apply to `Span<T>`, not to `Memory<T>`.

**Comment by jkotas** [comment]
> But in the code above, you don't have a legitimate way to access the array itself, only one part of its memory.

You can access the whole array fine using unsafe code. There is nothing invalid about it if you know how the Span was created. There are even a few places in coreclr/corefx that do that.

**Comment by GSPP** [comment]
Also, if an array length could ever change that would break a lot of invariants and optimizer assumptions.

**Comment by hpbieker** [comment]
Memory<T>() could have an extra ctor for allocating the backing memory, and that memory could be something that is not an array? We do not need an array here, that is just the way the current ctor is implemented?

**Comment by stephentoub** [comment]
> Memory() could have an extra ctor for allocating the backing memory

If you want to allocate, instead of:
```C#
Memory<byte> memorySlice = memory.Slice(0, 1);
```
you can just do:
```C#
Memory<byte> memorySlice = memory.Slice(0, 1).ToArray();
```

**Comment by TChatzigiannakis** [comment]
The entirely valid concern about not modifying object types and array sizes at runtime can be addressed if the CLR would instead allocate a new, smaller array, copy the relevant elements, and redirect the existing slice object to point to that new array instead, freeing the original for later collection.

Of course, it would still break any code that makes assumptions about what's outside boundaries of the slice. I'm not familiar with the specification to know if the behavior of such code is well-defined or not, but if such code isn't well-formed, the optimization could reasonably take precedence.

**Comment by benaadams** [comment]
> The entirely valid concern about not modifying object types and array sizes at runtime can be addressed if the CLR would instead allocate a new, smaller array, copy the relevant elements, and redirect the existing slice object to point to that new array instead, freeing the original for later collection.

Can do that in code
```csharp
memory = memory.Slice(0, 1).ToArray();
```

**Comment by hpbieker** [comment]
Sure, but the idea with the GC is that it should get rid of what is no longer needed? Using ToArray will add another allocation, but if this is done by GC it will only be allocated when it is moving the memory anyway.

**Comment by TChatzigiannakis** [comment]
@benaadams True, but this manual management of the situation. The user will have to make an educated guess about whether the reallocation is worth doing.

If this was done automatically by the CLR, the decision could be made based on (for example) whether all the existing slices pointing inside the buffer cover a total area of the buffer that's small enough to warrant getting rid of the unused areas. (This would probably be complicated for the runtime to assess, I'm just throwing the idea on the table.)

**Comment by TChatzigiannakis** [comment]
@mikedn The entire class of scenarios where this would be useful to have in could be described as "whenever the user has to allocate a lot of memory and then take a number of slices that's unknown ahead of time". Admittedly it would be a pretty rare case and I haven't personally encountered it.

**Comment by hpbieker** [comment]
The original use case I had was building a large list/array with unknown size and prevent the last ToArray allocation to reduce the size. However it looks like this will be a lot of work for the GC (both in terms of development and at runtime, so I am closing the issue now.
