### ISSUE TITLE
Rebuild of Development nuget package fails

### ISSUE THREAD

**Issue by poizan42** [dotnet/coreclr#208]
Steps to reproduce:
1. Run build.cmd
2. Delete .nuget\Microsoft.DotNet.CoreCLR.Development.1.0.0-prerelease.nupkg from the output folder
3. Run build.cmd again

MScorlib fails with the following error:
```
  Attempting to build package from 'Microsoft.DotNet.CoreCLR.Development.nuspec
  '.
  File not found: '..\mscorlib.pdb'.
C:\Users\poizan\Documents\dev\coreclr\build.proj(61,5): error MSB3073: The comm
and ""C:\Users\poizan\Documents\dev\coreclr\binaries\tools\NuGet.exe" pack "C:\
Users\poizan\Documents\dev\coreclr\binaries\Product\x64\debug\.nuget\Microsoft.
DotNet.CoreCLR.Development.nuspec" -NoPackageAnalysis -NoDefaultExcludes -Outpu
tDirectory "C:\Users\poizan\Documents\dev\coreclr\binaries\Product\x64\debug\.n
uget"" exited with code 1.
```

This is because the BuildNuGetPackages target expects to run before the MovePDB target in build.proj.

Wouldn't it make sense to make BuildNuGetPackages always run after MovePDB and change the nuspec file to reference PDB\mscorlib.pdb?

**Comment by mmitche** [comment]
@poizan42 Weird, I saw this earlier today but then couldn't reproduce it.  I'll give it another try.  Thanks for the report.

**Comment by poizan42** [comment]
Closing as it should be fixed now
