### ISSUE TITLE
Sos plugin on unix is missing SyncBlk

### ISSUE THREAD

**Issue by crntn** [dotnet/coreclr#20803]
Hi !

While investigating suspicious locks in System.Data.SqlClient on Unix we realized there was no implementation of the syncblk command in the sos plugin.

Do you guys have plans to port it ?

Thanks !

**Comment by janvorli** [comment]
cc: @mikem8361

**Comment by crntn** [comment]
Awesome ! I tried your WIP commit locally and was able to use the command with my dump :smiley: 

I wasn't able to get the syncblk command to appear in the output of soshelp but it was functionnal.

Thanks for reacting so fast !
