### ISSUE TITLE
Unable to delete File (dll) after unloading context.

### ISSUE THREAD

**Issue by FrankDoersam** [dotnet/coreclr#20806]
Hello,

i could not delete a dll after unloading it.

Could you please fix this bug.

Code:

 class SimpleUnloadableAssemblyLoadContext : AssemblyLoadContext
    {
        public SimpleUnloadableAssemblyLoadContext()
           : base(isCollectible: true)
        {
        }

        protected override Assembly Load(AssemblyName assemblyName) => null;
    }

    class Program
    {
        private static void ExecuteAssembly(Assembly assembly)
        {
            MethodInfo entry = assembly.EntryPoint;
            foreach (Type type in assembly.GetTypes())
            {
                Console.WriteLine(type.FullName);
            }
            Console.WriteLine("ok");

        }

        static void Main(string[] args)
        {
            AssemblyLoadContext tt = new SimpleUnloadableAssemblyLoadContext();
            tt.LoadFromAssemblyPath(@"C:\Lokale Daten\AppDomainUnload\ConsoleApp1\bin\Debug\netcoreapp3.0\Plugin\Plugin1.dll");

            tt.Unload();
            Console.ReadKey();
        }

        private static void Context_Unloading(AssemblyLoadContext obj)
        {
            Console.WriteLine("Unloading");
        }
    }

Thanks in advance.
Yours sincerely
Frank Dörsam

**Comment by jkotas** [comment]
Answered in https://github.com/dotnet/corefx/issues/19773#issuecomment-435888506

We should make sure to include this in the documentation for assembly unloading at https://docs.microsoft.com/en-us/

**Comment by janvorli** [comment]
Closing this issue as we have already published a doc on unloading at https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability-howto

**Comment by masums** [comment]
Unfortunately Microsoft's example project also unable to delete dll after unloading. 
[https://github.com/dotnet/samples/tree/master/core/tutorials/Unloading](https://github.com/dotnet/samples/tree/master/core/tutorials/Unloading)
I have tested this example project.  Deleted plugins after Console.WriteLine(). 
Throws exception. I have added following lines
```CSharp
            Console.WriteLine($"Unload success: {!hostAlcWeakRef.IsAlive}");
            File.Delete(pluginFullPath);
````

**Comment by NMSAzulX** [comment]
I had the same problem and I'm going to do more tests tonight.

**Comment by NMSAzulX** [comment]
@masums @FrankDoersam  I solved this problem using stream loading.Maybe it can solve your problem.
```C#

if (!DynamicDlls.ContainsKey(path))
{
        using (FileStream stream = new FileStream(path, FileMode.Open))
        {
              var assembly = LoadFromStream(stream);
              var types = assembly.GetTypes();

              for (int i = 0; i < types.Length; i++)
              {
                   ClassMapping[types[i].Name] = assembly;
              }
        }
}

```

It's ok.  
But before you unload it, you have to clear the dictionary. 
`DynamicDlls.Clear();` (Note: Don't do it in the 'Main' method.)

**Comment by masums** [comment]
Thank you for your suggestion. But how it will load its dependencies. And
will we be able to delete them also after unload?

**Comment by NMSAzulX** [comment]
@masums  Maybe using AssemblyDependencyResolver.  
Although I don't know how to use it yet, I'm just referring to the official example. 


> I have a [project](https://github.com/dotnetcore/Natasha) based on roslyn. I use [DependencyContext.Default.CompileLibraries](https://github.com/dotnetcore/Natasha/blob/master/src/Natasha/Engine/AssemblyModule/AssemblyDomain.cs#L55-L58) to get all dependencies when I compile dynamically.

**Comment by NMSAzulX** [comment]
@masums  Unwittingly, I found a solution to this.    

In the constructor
``` C#
if (arg == "Default")
{
     Default.Resolving += Default_Resolving;
}
```  

In the class
```C#
//Default will 
private Assembly Default_Resolving(AssemblyLoadContext arg1, AssemblyName arg2)
{
   return Load(arg2);
}
```

```C#
protected override Assembly Load(AssemblyName assemblyName)
{
    string assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
    if (assemblyPath != null)
    {
         return Handler(assemblyPath);
    }

    return null;
}
```  

@janvorli I'm a little confused.  If I use the Resolving event instead of implementing the Load method, it will also work. Load and Resolving have the same functionality?

**Comment by janvorli** [comment]
@vitek-karas can you please answer the question about Resolving event vs Load method?

**Comment by janvorli** [comment]
> Unfortunately Microsoft's example project also unable to delete dll after unloading.
@masums I am sorry, I've missed your comment on this here. It should work, so let me try to figure out what's wrong.

**Comment by NMSAzulX** [comment]
@janvorli  I have an issue. I learned SOS debugging and printed out some information, but I don't know if it's useful?  https://github.com/dotnet/coreclr/issues/26386

**Comment by vitek-karas** [comment]
* `AssemblyLoadContext.Load` method is the first thing called during the resolution. So this gives you the ability to resolve all assembly requests in the load context. Only once this returns null, the control goes to the default load context as a fallback. So this allows you to load a different version of a given assembly than the one in the default context.
* `AssemblyLoadContext.Resolving` event is fired when all other attempts for resolution failed - it's basically the last chance (almost). So in this case if the assembly exists in the default load context it would not get to the event handler at all.

The `AssemblyDependencyResolver` is typically used in the `Load` method (to allow overrides of the default context). But obviously it depends on your scenario.

Another difference is that the `Resolving` event can be handled even on the default load context (you can add your event handler to `AssemblyLoadContext.Default.Resolving`. It is not possible to override the `Load` method on the default context though (this is intentional - it would be really easy to completely break everything if that method had a bug in it).

@NMSAzulX loading from memory should work, but there is a downside - it will not work with Ready2Run images (assemblies precompiled via `crossgen`). That might be OK in your scenario though. It's also obviously slower as you're making a copy (loading from file just memory maps the file which is typically faster and consumes less memory).

**Comment by NMSAzulX** [comment]
@janvorli @vitek-karas Thank you very much.Will there be any documents coming out?

**Comment by vitek-karas** [comment]
Documentation about the `AssemblyLoadContext` and the actual order in which things happen is here: https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/loading-managed

**Comment by NMSAzulX** [comment]
@vitek-karas  OK .

**Comment by masums** [comment]
> > Unfortunately Microsoft's example project also unable to delete dll after unloading.
> 
> @masums I am sorry, I've missed your comment on this here. It should work, so let me try to figure out what's wrong.

@janvorli It's ok. 
Problem is if we want to develop a modular application which updates it's running plugins/modules at run time then it will require to unload the dll and replace that dll by the new version and load the new dll again. 

So if we are unable to unload the plugins/modules dll and delete that dll then it is not possible to update plugins/modules while the application is running.
 
Good thing is we can unload the dll at runtime. It works perfectly. But only problem is we can not delete the unloaded dll while the application is running. 

Right now we unload the plugin and restart the application then update that plugin. We just do not want to restart the application for plugins update. After unloading the dll we have to delete the dll for avoiding the restart.  

Thanks

**Comment by masums** [comment]
Today I have tested [https://github.com/dotnet/samples/tree/master/core/tutorials/Unloading](url)  this code. Now it is working with the new release of .Net core 3.0.100. Delete is working for unloaded dll. May be It will also work for me if I update the framework version.
