### ISSUE TITLE
[release/2.2] TestSpanIndexVariantString Performance Regression

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#20813]
While doing a comparison of release/2.2 to release/2.1 I found a regression in the TestSpanIndexVariantString test on Windows x64 of about 12.5%.

I have not dug too far into the traces, but can share them and a repro upon request.

**Comment by AndyAyersMS** [comment]
I'll investigate.

**Comment by AndyAyersMS** [comment]
As in #20811 this test does not have stable numbers over time. (4 this time...). 2.1 is at ~19.5 and 2.2 at 22.3. Likely culprit is also loop alignment.



Inner-loop codegen identical:
```asm
G_M13033_IG08:
       8BD3                 mov      edx, ebx
       23D7                 and      edx, edi
       3B542428             cmp      edx, dword ptr [rsp+28H]
       7328                 jae      SHORT G_M13033_IG10
       488B4C2420           mov      rcx, bword ptr [rsp+20H]
       4863D2               movsxd   rdx, edx
       488B14D1             mov      rdx, gword ptr [rcx+8*rdx]
       498D4F08             lea      rcx, bword ptr [r15+8]
       E883E16A5F           call     CORINFO_HELP_ASSIGN_REF
       FFC3                 inc      ebx
       3BDE                 cmp      ebx, esi
       7CDB                 jl       SHORT G_M13033_IG08
```

* 2.1 Perf History
![image](https://user-images.githubusercontent.com/10121823/48038712-aea73280-e126-11e8-97be-37506a7121fb.png)

* 2.2 Perf History
![image](https://user-images.githubusercontent.com/10121823/48038725-bd8de500-e126-11e8-9536-9acd9a6f62d0.png)

* Master Perf History
![image](https://user-images.githubusercontent.com/10121823/48038745-d26a7880-e126-11e8-9dc1-c7349056e1a9.png)

So, closing as a known issue with perf stability of this test.
