### ISSUE TITLE
Unmanaged API and ABI provided by CoreCLR 

### ISSUE THREAD

**Issue by omajid** [dotnet/coreclr#20835]
CoreCLR exposes a few unmanaged APIs (Application Program Interface, C headers, if you will), and ABIs (Application Binary Interface, the native ELF symbols exported, for example) that others can use. For example, CoreCLR provides a hosting API (https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting). Some other issues (such as https://github.com/dotnet/coreclr/issues/11490) have touched on other APIs such as a debug api.

To that end, it might be helpful to clarify some expectations around CoreCLR. This would be very nice to have if/when other libraries/applications that have a dependency on .NET Core (and CoreCLR) start getting packaged into Linux distributions.

1. Is there a complete list of API that CoreCLR exposes?
   
2. Does CoreCLR provide both an API and an ABI? As in, will applications compiled against one version of CoreCLR continue working against other versions?

3. What headers files are the supported APIs defined in? Are there unsupported APIs in those headers too?

4. Are the both API and ABI stable? What is the process for changing/breaking the API/ABI? Are there any examples of API break within .NET Core so far?

/cc @crummel @dseefeld

**Comment by jeffschwMSFT** [comment]
Closing out this question. Please let us know if you have any additional questions.
