### ISSUE TITLE
Build runtime will fail

### ISSUE THREAD

**Issue by kevin-coder** [dotnet/coreclr#2085]
Environment:
Windows 8.1, Visual Studio 2015, CMake 3.4.0-rc2. Latest version of code.
Reproduce steps:
1. Enter into the coreclr folder.
2. Type build clean, after a few minutes, it will be fail. See build log for details in attachment.

[MScorlib_Windows_NT__x64__Debug.TXT](https://github.com/dotnet/coreclr/files/37454/MScorlib_Windows_NT__x64__Debug.TXT)

**Comment by janvorli** [comment]
I have seen a report of build failing on OSX with the same version of CMake (3.4.0), although in a different way (#2054). I wonder if there was some breaking change in this version of CMake or if there is something broken in it. 
In the OSX case, downgrading to CMake 3.3.2 fixed the problem. Would it be possible for you to try the same thing and see if it fixes the issue?

**Comment by janvorli** [comment]
CC: @cmckinsey

**Comment by huzq** [comment]
OK, I will have a try and update the results ASAP.

**Comment by huzq** [comment]
I have tried with CMake version at 3.2.2, seems that it could build successful before "Restoring build tools...", however, when restoring build tools, fails still appears. See attached log for details.
[MScorlib_Windows_NT__x64__Debug.txt](https://github.com/dotnet/coreclr/files/37940/MScorlib_Windows_NT__x64__Debug.txt)

**Comment by sergiy-k** [comment]
Hi @kevin-coder, are you still able to reproduce this problem?

**Comment by sergiy-k** [comment]
Please re-open this issue if you are still running into a problem with building coreclr. Thank you!

**Comment by kevin-coder** [comment]
OK, I will have a try and if there is still such kind of issues, I will re-open it. Thanks!
