### ISSUE TITLE
Finalizer called on object that has not been constructed

### ISSUE THREAD

**Issue by cosborne83** [dotnet/coreclr#20858]
On multiple versions of .NET (at least 4.5.2 to 4.7.2) There appears to be a difference of behavior depending on JIT optimizations applied with regards construction of a finalizable type where a method that returns one of the arguments passed to its constructor throws an exception. Whilst it's noted widely that finalizers will still be run for an object where an exception is thrown during execution of the object's own constructor, in this case, the object is still finalized despite the constructor (and field initializers) never having been called.

Example code:

    class Program
    {
        static void Main()
        {
            Console.WriteLine("Ready");
            Console.ReadLine();

            try
            {
                using (new Finalizable(MethodThatThrows()))
                {
                     // ...
                }
            }
            catch
            {
                Console.WriteLine("Caught exception");
            }

            GC.Collect();
            GC.WaitForPendingFinalizers();
            Console.WriteLine("Done");
        }

        private static string MethodThatThrows()
        {
            throw new Exception();
        }
    }

    class Finalizable : IDisposable
    {
        private readonly bool _constructed = true;

        public Finalizable(string data)
        {
            Console.WriteLine("Constructed");
        }

        public void Dispose()
        {
            Console.WriteLine("Disposing");
            GC.SuppressFinalize(this);
        }

        ~Finalizable()
        {
            Console.WriteLine("Finalizing. WasConstructed: {0}", _constructed);
        }
    }

Expected output (appears in Debug mode and sometimes in Release, seemingly dependent on optimizations that were applied during JIT):

    Caught exception
    Done

Observed output:

    Caught exception
    Finalizing. WasConstructed: False
    Done

It appears that depending on optimizations applied, the order of operations is either:

1. Call methods that return the constructor arguments
2. Create new Finalizable object
3. Call Finalizable..ctor()

Or the following, which results in the Finalizer eventually being called on an uninitialized object if step 2 throws:

1. Create new Finalizable object
2. Call methods that return the constructor arguments
3. Call Finalizable..ctor()

Is this expected behavior?

**Comment by mikedn** [comment]
Duplicate/related to #2478

**Comment by stephentoub** [comment]
Closing as dup.
