### ISSUE TITLE
Assertion failed '!"Unhandled operation in EvalOpSpecialized<T> - unary"'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#20881]
Found in corefx tests (Windows and Linux).

2 cases of:
```
Assert failure(PID 8048 [0x00001f70], Thread: 16564 [0x40b4]): Assertion failed '!"Unhandled operation in EvalOpSpecialized<T> - unary"' in 'System.Buffers.Text.Utf8Formatter:TryFormat(bool,struct,byref,struct):bool' (IL size 138)
22:23:36   
22:23:36       File: d:\j\workspace\x64_checked_w---a7bd363e\src\jit\valuenum.cpp Line: 633
22:23:36       Image: D:\j\workspace\x64_checked_w---a7bd363e\_\fx\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-x64\dotnet.exe
```

x64:
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/lastFailedBuild/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_baseline/lastFailedBuild/consoleFull

x86:
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/lastFailedBuild/consoleFull

**Comment by AndyAyersMS** [comment]
This also shows up in PMI runs:
```
corerun.exe c:\repos\jitutils\bin\pmi.dll prepall-quiet-cctors c:\repos\coreclr2\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\System.Memory.dll

Assert failure(PID 9588 [0x00002574], Thread: 9432 [0x24d8]): Assertion failed '!"Unhandled operation in EvalOpSpecialized<T> - unary"' in 'System.Buffers.Text.Utf8Formatter:TryFormat(bool,struct,byref,struct):bool' (IL size 138)

    File: c:\repos\coreclr2\src\jit\valuenum.cpp Line: 633
    Image: C:\repos\coreclr2\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
```

**Comment by briansull** [comment]
Almost certairly the same issue as #20883

**Comment by briansull** [comment]
THis is caused when a new GenTree node is added and
`bool ValueNumStore::CanEvalForConstantArgs(VNFunc vnf)` returns true; 
which is does in the default case.
The code to perform the EvalOp needs to be added.

**Comment by GrabYourPitchforks** [comment]
https://github.com/dotnet/coreclr/pull/20883 has been committed. Please let me know if this doesn't address the issue we're seeing here.

**Comment by briansull** [comment]
We no longer see ths assert
