### ISSUE TITLE
(Documentation) Add WKS, SVR and CEE to glossary

### ISSUE THREAD

**Issue by poizan42** [dotnet/coreclr#209]
I couldn't figure out what these are acronyms/abbreviations for. WKS and SVR seems to be different GCs? Workstation and Server GCs?

**Comment by mikedn** [comment]
Yep, WKS = Workstation and SVR = Server. Back in the days of .NET 1.x there were 2 different runtime dlls - mscorwks.dll and mscorsvr.dll. Now there's only one dll which contains both GCs. Well, it's the same GC but configured differently.

I would guess that CEE = Common Execution Engine.

**Comment by poizan42** [comment]
So mscordacwks = Microsoft Common Object Runtime Data Access Component for Workstation? Though that name seems to have become increasingly inaccurate over the lifetime of .NET.

**Comment by mikedn** [comment]
Yes, that's what mscordacwks means.

The wks suffix is kind of redundant now. You probably noticed that there's a cee_wks project but no cee_svr project. The cee_wks project includes both WKS and SVR GC, see gceesvr.cpp and gceewks.cpp. Both files include the GC code but gceesvr.cpp defines SERVER_GC=1

**Comment by richlander** [comment]
Resolved: https://github.com/dotnet/coreclr#learn-about-coreclr

**Comment by omajid** [comment]
If anyone ends up here looking for the definition, the new glossary is at: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/glossary.md
