### ISSUE TITLE
LocalGC: Unable to initialize custom GC

### ISSUE THREAD

**Issue by kkokosa** [dotnet/coreclr#20909]
I am unable to compile DLL that will be accepted as custom GC - no matter what I try (Debug/Release, x86/x64) runtime seems to not like its binary format:

```
> dotnet run
Using launch settings from F:\GithubProjects\CoreCLR.ZeroGC\src\Samples.ConsoleApp\Properties\launchSettings.json...
Failed to initialize CoreCLR, HRESULT: 0x80004005
```

And `launchSettings.json`:

```
{
  "profiles": {
    "ConsoleApp": {
      "commandName": "Project",
      "environmentVariables": {
        "COMPlus_GCName": "f:\\GithubProjects\\CoreCLR.ZeroGC\\build\\ZeroGC.Calloc\\x64_Release\\ZeroGC.Calloc.dll"
      }
    }
  }
}
```

Repro should be possible from my project at https://github.com/kkokosa/CoreCLR.ZeroGC. I've double checked it on two completely different machines: Windows 10 Pro 1803 17134.345, .NET Core 2.1.400, Windows SDK 10.0.15063.0 and Windows Server 2016 1607 14393.1944 .NET Core 2.1.402, Windows SDK 10.0.16299.0. I've checked also the newest 2.1.5 with 2.1.403 SDK.

Underlying `LoadLibraryExW` just always returns `STATUS_INVALID_IMAGE_FORMAT`:

![image](https://user-images.githubusercontent.com/11159779/48255938-66ca2900-e40e-11e8-8a21-83e95ef5e00b.png)

I've double checked all possible dependencies - compiled x64 dll is indeed 64-bit and has only 64-bit dependencies (checked by Depends). Debug build does not help here as it is this system call that is failing...

Edit: BTW, the same project was working during .NET Core 2.1 preview.

**Comment by janvorli** [comment]
It seems that in the screenshot from WinDbg above, it was attempting to load the 32 bit version. That would explain the `STATUS_INVALID_IMAGE_FORMAT`. So maybe the error when you attempt to load the 64 bit version is different.

**Comment by kkokosa** [comment]
@janvorli indeed this error was misleading. But after further investigation, I am even more confused. Looking at below lines, it returns E_FAIL (0x80004005) because of version info not being 1:

```
coreclr!`anonymous namespace'::LoadAndInitializeGC+0x7e:
00007fff`15cc1b8a 488d0d47162d00  lea     rcx,[coreclr!g_gc_version_info (00007fff`15f931d8)]
2:018> p
onecore\windows\core\console\open\src\host\srvinit.cpp(411)\conhost.exe!00007FF7153BC372: (caller: 00007FF7153B8CD9) ReturnHr(57) tid(5fc4) 80070032 The request is not supported.
coreclr!`anonymous namespace'::LoadAndInitializeGC+0x8b:
00007fff`15cc1b97 833d3a162d0001  cmp     dword ptr [coreclr!g_gc_version_info (00007fff`15f931d8)],1 ds:00007fff`15f931d8=00000002
2:018> p
coreclr!`anonymous namespace'::LoadAndInitializeGC+0x94:
00007fff`15cc1ba0 b805400080      mov     eax,80004005h
```

So looking at `LoadAndInitializeGC`, it is most probably major version check: 

https://github.com/dotnet/coreclr/blob/0fccc78cfea93bafbba07cc4a84a32582a3af88f/src/vm/gcheaputilities.cpp#L199-L204

But the major version should be 2... So I've just swapped major with minor:

```
extern "C" DLLEXPORT void
GC_VersionInfo(
    /* Out */ VersionInfo* result
)
{
	result->MajorVersion = GC_INTERFACE_MINOR_VERSION;
	result->MinorVersion = GC_INTERFACE_MAJOR_VERSION;
    result->BuildVersion = 0;
    result->Name = "Zero GC";
}
```

And it is now perfectly working...

**Comment by jkotas** [comment]
> Edit: BTW, the same project was working during .NET Core 2.1 preview.
> I've just swapped major with minor

Note that we have bumbed up the interface version since .NET Core 2.1 preview. You may have old copy of the gc interface sources.

**Comment by kkokosa** [comment]
@jkotas but how it explains that runtime checks for `1` as major version? And obviously, I do not have old GC interface sources - I use coreclr master repo from Oct 23 (which is by far after the Preview).

**Comment by jkotas** [comment]
Here is the check in the runtime: https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/vm/gcheaputilities.cpp#L199

> I use coreclr master repo from Oct 23 

And is the runtime that you are using built from this label too? I think you are using some older version of the runtime binaries where the GC interface major version was still `1`.
