### ISSUE TITLE
Hardware exceptions on FreeBSD always abort

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#2090]
Even with a try/catch (via the PAL_TRY/PAL_EXCEPT macros) a hardware exception aborts the process when the PAL SEH code (in SEHProcessException) throws the PAL_SEHException created for this h/w signal. It may have something to do with throwing an exception in a signal handler. It was found in the new PAL exception_handling/pal_sxs/test1 test but also happens in the simpler exception_handler/pal_except/test1 (if enabled).

**Comment by krytarowski** [comment]
I'm experiencing the same behavior on NetBSD. Could you try to prepare a minimalistic and standalone test-case that is supposed to pass on other platforms and fail on BSD? I will take it and investigate.

**Comment by krytarowski** [comment]
Something with usage of PAL.

**Comment by mikem8361** [comment]
This tests hardware and software exceptions across multiple PALs (in different modules).  It would be a lot of work to create a simple test-case that doesn't involve the PAL.

**Comment by mikem8361** [comment]
I didn't mean to add the software exceptions.  palsxs tests hardware exceptions trapped via various signals and that the proper chaining across multiple PALs occurs.

**Comment by krytarowski** [comment]
For now I will leave it as it is, I will be back to it once other parts of dotnet will be ported to NetBSD.

**Comment by krytarowski** [comment]
Fixed by @janvorli in master.

**Comment by krytarowski** [comment]
Should be closed
