### ISSUE TITLE
Is there a api for get referenced but not loaded assemblies?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/coreclr#20904]
Is there a api for get referenced but not loaded assemblies, I wanna get types from some referenced but not directly referenced in my code assemblies.

**Comment by WeihanLi** [comment]
I've tried `Assembly.GetEntryAssembly().GetReferencedAssemblies()` and `AppDomain.CurrentDomain.GetAssemblies()`, but these methods seems to use to get assemblies that 
had loaded.

**Comment by WeihanLi** [comment]
I've referenced some assemblies that has not been used, I wanna get type info from these assemblies via reflection, but I can not get these assemblies, it seemed to be that these assemblies are not loaded into the default app domain.

**Comment by steveharter** [comment]
Even if the assemblies have not been used yet, you can still call GetReferencedAssemblies as mentioned above. From those references, you can load the assembly(s) into the default app domain and perform reflection.

If you do not want to load the assembly(s) into the default app domain, you can use the new MetadataLoadContext feature that will be available for 3.0.

**Comment by WeihanLi** [comment]
Hi @steveharter ,I'm sorry that I may elaborate not so clearly, these assemblies are referenced but not used in my app directly since app start to the app end, so these assemblies seemed to be not used so they're not loaded into the app domain.
So when I use `Assembly.GetEntryAssembly().GetReferencedAssemblies()` and `AppDomain.CurrentDomain.GetAssemblies()`, they can not load these assemblies.

Is there a document or something about `MetadataLoadContext`?
Will it be available in `.netstandard2.1`?

**Comment by steveharter** [comment]
If the types in those assemblies are not referenced, then the main exe\assembly will not have a reference to them and thus they will not show up in `GetReferencedAssemblies`. You can also use tools such as `ildasm.exe` to open your exe\assembly and inspect the manifest for assembly references.

However you can still manually load those assemblies via `Assembly.LoadFrom()` and then perform reflection.

Note that `MetadataLoadContext` is for read-only inspection meaning no methods can be called. Documentation is pending - the code is currently in the corefx repro's master branch. It will not be "in" netstandard but will support netstandard. It is to be shipped out-of-band so you'll need a package reference to it.

**Comment by jeffschwMSFT** [comment]
Here are the docs for the MetadataLoadContext - https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadataloadcontext?view=dotnet-plat-ext-3.0.  I am going to close this issue for now, but please let me know if you have any other questions.

**Comment by WeihanLi** [comment]
Thanks @jeffschwMSFT , is there a sample here? I've had a look at the docs,but confused on how to use.

**Comment by jeffschwMSFT** [comment]
cc @steveharter @joshfree for sample on MetadataLoadContext

**Comment by steveharter** [comment]
Here you go. This sample lists the assembly references from the current console app:

```cs
using System;
using System.Linq;
using System.IO;
using System.Reflection;
using System.Collections.Generic;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // This sample uses just the current assembly and its core assembly for the assembly name->location resolution.
            List<string> files = new List<string>();
            Assembly coreAssembly = typeof(object).Assembly;
            files.Add(coreAssembly.Location);

            // If you wanted to be able to load referenced assemblies you'll need to add their path. Something like this:
            //string myFrameworkLocation = Path.GetDirectoryName(coreAssembly.Location);
            //List<string> files = Directory.GetFiles(myFrameworkLocation).Where(name => name.EndsWith(".dll")).ToList();
            //files.Add(typeof(MetadataAssemblyResolver).Assembly.Location);
            //add others here...

            Assembly thisAssembly = typeof(Program).Assembly;
            files.Add(thisAssembly.Location);

            using (MetadataLoadContext lc = new MetadataLoadContext(new PathAssemblyResolver(files), coreAssembly.GetName().Name))
            {
                Assembly asm = lc.LoadFromAssemblyName(thisAssembly.GetName());
                foreach (AssemblyName referencedAssembly in asm.GetReferencedAssemblies())
                {
                    Console.WriteLine($"FullName:{referencedAssembly.FullName}");
                   // From here we could load the assembly and reflect over it (requires the other commented code above):
                    //Assembly refAssembly = lc.LoadFromAssemblyName(referencedAssembly.Name);
                    //foreach (Type type in refAssembly.GetTypes())
                    //{
                    //    Console.WriteLine($"    Type:{type.FullName}");
                    //}
                }
            }

            Console.WriteLine("Finished");
            Console.ReadLine();
        }
    }
}
```

Output:
```
FullName:System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
FullName:System.Collections, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
FullName:System.Reflection.MetadataLoadContext, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
FullName:System.Console, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Finished
```

**Comment by WeihanLi** [comment]
Thanks so much. @steveharter @jeffschwMSFT
