### ISSUE TITLE
Memory<T> is pinning prepinned arrays

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#20939]
Looking at the profile on IOCompletion for Kestrel plaintext; mostly seems to be moving stuff onto the threadpool to run?

However 35% is used freeing `GCHandle`

![image](https://user-images.githubusercontent.com/1142958/48314841-61fca500-e5c7-11e8-99f1-b07c54b2ce5a.png)

Other issue, lock contention blue prior to UnsafeQueueUserWorkItem, don't see where the lock is though.

Queuing to threadpool via `UnsafeQueueUserWorkItem` is only 4.3%

Haven't come to any conclusions as of yet; might just be tracing overheads?

**Comment by benaadams** [comment]
Lock contention ( `UnsafeQueueUserWorkItem`) and call to Disposal look to be in Kestrel. So this is just a question on `GCHandle.Free`

**Comment by benaadams** [comment]
Hmm... aren't these all pre-pinned arrays in Kestrel; what's it trying to Free? (i.e. shouldn't they be NOPs) in the MemoryManager?

**Comment by benaadams** [comment]
@GrabYourPitchforks Prepinned array is creating a `GCHandle` when its pinned?

**Comment by benaadams** [comment]
Seems to be actually Pinning
![image](https://user-images.githubusercontent.com/1142958/48315798-b5282500-e5d2-11e8-8ffc-d43a54dccae5.png)

**Comment by stephentoub** [comment]
How do you know this is coming from prepinned arrays, rather than operations on other arrays that aren't pinned already?

**Comment by benaadams** [comment]
All the Memory submitted to the socket by Kestrel is from `MemoryPoolBlock`s which are created via
`MemoryMarshal.CreateFromPinnedArray(slab.Array, _offset, _length)`

https://github.com/aspnet/KestrelHttpServer/blob/release/2.2/shared/Microsoft.Extensions.Buffers.MemoryPool.Sources/MemoryPoolBlock.cs#L12-L28

They are Sliced; added to [BufferSegment](https://github.com/dotnet/corefx/blob/master/src/System.IO.Pipelines/src/System/IO/Pipelines/BufferSegment.cs)s and ReadOnlySequences etc so it is possible the pinned flag gets lost somewhere (outside of the actual pin method)

**Comment by benaadams** [comment]
Lock issue https://github.com/aspnet/KestrelHttpServer/pull/3093

**Comment by benaadams** [comment]
Maybe zero length reads using a `Memory.Empty` that's not marked as pre-pinned?

**Comment by benaadams** [comment]
`Memory.Empty` doesn't look like it will pin as it has no backing object; so that should be fine.

This probably would though?
https://github.com/aspnet/KestrelHttpServer/blob/5db6394769e229139cbf8538ec73253ce76e735b/src/Kestrel.Transport.Sockets/Internal/SocketReceiver.cs#L16-L18
```csharp
_awaitableEventArgs.SetBuffer(Array.Empty<byte>(), 0, 0)
```

**Comment by benaadams** [comment]
It was `Array.Empty<byte>()` getting pinned and unpinned
![image](https://user-images.githubusercontent.com/1142958/48322277-a6675f80-e61e-11e8-8a9a-305e5dd9d233.png)

**Comment by benaadams** [comment]
Aside: Wonder if having the same object pinned hundreds of time was making the GCHandle.Free more expensive and explained the cost?

**Comment by jkotas** [comment]
GC handle allocator is a custom pool of IntPtr-sized items. The cost of allocating/freeing a GC handle is not affected by how many other GC handles are pointing to the same object. Number of GC handles and what they are pointing to affects time spent in GC, but not the cost of allocating/freeing GC handles.

The pseudo code for allocating a GC handle is:

```
void* handle = getPoolForHandleType(handleType).alloc();
*(void**)handle = (void*)object;
return handle;
```

And freeing:

```
getPoolForHandleType(getHandleTypeFromHandle(handle)).free(handle)
```

I see the following in your profile:

- `FireDestroyGCHandle` and other related code: All tracing code should behind a fast check to make it pay-for-play. It does not seem to be happening here. We are doing several calls related to tracing just to fine out that there is nothing to do. Opened #20941.

- `TableQuickRebalanceCache`: The handles seems to be always allocated on one set of threads and freed on a different set of threads. It requires reballancing (sending the handles from the local pool to the global pool). This is the "usual" problem with malloc/free like allocators. I do not think we can do much about it.
