### ISSUE TITLE
Enum.TryParse  Method conflict 

### ISSUE THREAD

**Issue by maikebing** [dotnet/coreclr#20942]
Enum.TryParse(Type enumType, string value, out object result)

TryParse<TEnum>(string value, bool ignoreCase, out TEnum result) where TEnum : struct

```
       RpcCmds cmd = RpcCmds.NotSupported;
       object obj;
       Enum.TryParse(typeof(RpcCmds), "NotSupported", out obj);  //A 
       Enum.TryParse("NotSupported", true, out cmd);  //B
```
IDE thinks A is not wrong, but the compiler mistaken B for this usage.
Is this a BUG?

**Comment by stephentoub** [comment]
What framework are you building for?  The `bool TryParse(Type enumType, string value, out object result);` overload is specific to .NET Core and doesn't exist in .NET Framework.

**Comment by maikebing** [comment]
TargetFrameworks:
`   <TargetFrameworks>netcoreapp2.1;net46</TargetFrameworks>`

When netcoreapp2.1:

Error CS1503: Parameter 1: cannot be converted from "System.Type" to "string" 
Error CS1503: Parameter 2: cannot be converted from "string" to "bool"

**Comment by stephentoub** [comment]
The repro compiles fine for me when targeting netcoreapp2.1:
```
c:\Users\stoub\Desktop\Repro>dotnet build -f netcoreapp2.1
Microsoft (R) Build Engine version 15.9.19+g938f3292a0 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 18.06 ms for c:\Users\stoub\Desktop\Repro\ConsoleApp20942.csproj.
  ConsoleApp20942 -> c:\Users\stoub\Desktop\Repro\bin\Debug\netcoreapp2.1\ConsoleApp20942.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.71
```
And I get the expected build errors (the ones you shared) when targeting net46:
```
c:\Users\stoub\Desktop\Repro>dotnet build -f net46
Microsoft (R) Build Engine version 15.9.19+g938f3292a0 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 21.11 ms for c:\Users\stoub\Desktop\Repro\ConsoleApp20942.csproj.
[c:\Users\stoub\Desktop\Repro\ConsoleApp20942.csproj]
Program.cs(20,25): error CS1503: Argument 1: cannot convert from 'System.Type' to 'string' [c:\Users\stoub\Desktop\Repro\ConsoleApp20942.csproj]
Program.cs(20,42): error CS1503: Argument 2: cannot convert from 'string' to 'bool' [c:\Users\stoub\Desktop\Repro\ConsoleApp20942.csproj]

Build FAILED.

Program.cs(20,25): error CS1503: Argument 1: cannot convert from 'System.Type' to 'string' [c:\Users\stoub\Desktop\Repro\ConsoleApp20942.csproj]
Program.cs(20,42): error CS1503: Argument 2: cannot convert from 'string' to 'bool' [c:\Users\stoub\Desktop\Repro\ConsoleApp20942.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.50

c:\Users\stoub\Desktop\Repro>
```
since those methods don't exist in .NET 4.6.

**Comment by maikebing** [comment]
> 
> 1>------ Rebuild All started: Project: ConsoleApp20942, Configuration: Debug Any CPU ------
> 1>Program.cs(20,25,20,40): error CS1503: Argument 1: cannot convert from 'System.Type' to 'string'
> 1>Program.cs(20,42,20,56): error CS1503: Argument 2: cannot convert from 'string' to 'bool'
> 1>Done building project "ConsoleApp20942.csproj" -- FAILED.
> 1>ConsoleApp20942 -> C:\Users\mysti\source\repos\ConsoleApp20942\ConsoleApp20942\bin\Debug\netcoreapp2.1\ConsoleApp20942.dll
> ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

![20942](https://user-images.githubusercontent.com/3445167/48454615-e0895a80-e7f2-11e8-80a7-e66953474cad.png)

**Comment by stephentoub** [comment]
If you remove `net46` from your .csproj, I assume it works?

**Comment by maikebing** [comment]
Yes.
In special cases, I must use. NET 461 under Windows and  using. NET Core under Linux! 
I'll use `#if `to fix it. 
Thank you very much for your help.

**Comment by stephentoub** [comment]
> In special cases, I must use. NET 461 under Windows and using. NET Core under Linux!

Could you elaborate on what those cases are?
