### ISSUE TITLE
ETW for GCThreadControl?

### ISSUE THREAD

**Issue by xoofx** [dotnet/coreclr#20948]
Hey,

While evaluating the impact of GC on a thread that is being interrupted, I have this case where GCThreadControl is being called:

![image](https://user-images.githubusercontent.com/715038/48347694-494fc600-e67f-11e8-9f02-e85d69470489.png)

and I'm assuming that it is in the situation of `ThreadSuspend::SuspendRuntime` and it looks like it is calling later `Thread::RareDisablePreemptiveGC`, and I would like to gather automatically the total amount of time this function is waiting. I have tried to use ETW TraceEvent API to gather this but I was not able to find anything useful... and checking the source, I'm not sure there are any ETW events triggered there...

This event is particularly important for threads that are compute only, not doing anykind of allocations for example, as they are going to be interrupted by the GC anyway if another thread is making lots of allocations (at least on platforms supporting thread hijacking)

Do you think that's something that could be added actually? 

I can try to send a PR (but I have never done anykind of ETW integration in CoreCLR, so I would not mind to get some guidance!)

cc: @Maoni0

**Comment by xoofx** [comment]
I have a subsidiary question: I can see that when a thread is only running pinvoke code (and so the thread doesn't have any managed references alive), the thread doesn't seem to be interrupted by the GC, which is what @jkotas confirmed in #20691 
Where is located in the source code this decision of not interrupting this thread? In `ThreadSuspend::SuspendRuntime` there is an iteration over the threads, but `thread->SuspendThread();` is called on all of them while I don't see this suspension in the Concurrency Visualizer for this particular "pinvoke" thread

**Comment by jkotas** [comment]
Every thread has `m_fPreemptiveGCDisabled` flag. This flag is `true` when the thread is running managed code and `false` when the thread is running external unmanaged code (ie inside pinvoke). `ThreadSuspend::SuspendRuntime` does nothing to threads that have `m_fPreemptiveGCDisabled` flag set.

This is explained in detail in: https://github.com/dotnet/coreclr/blob/master/Documentation/botr/threading.md#entering-cooperative-mode

**Comment by xoofx** [comment]
> Every thread has m_fPreemptiveGCDisabled flag. This flag is true when the thread is running managed code and false when the thread is running external unmanaged code (ie inside pinvoke). 

Right, I misread the code block and indeed, the `SuspendThread` is inside the `m_fPreemptiveGCDisabled `  block.  So the background GC thread is processing the stack roots of this "pinvoke" thread, while the thread is still running, and there is only a protection if the thread goes back from unmanaged to managed (the case of `partially-interruptable` I assume when there is this "gc pools" ), is it correct?

**Comment by jkotas** [comment]
> there is only a protection if the thread goes back from unmanaged to managed (the case of partially-interruptable I assume

Right, going from unmanaged for managed will check for GC in progress and wait as necessary. It has unrelated to partially interruptible code though.

**Comment by mattwarren** [comment]
@xoofx if it helps I wrote about ['partially/fully interruptible' code](http://mattwarren.org/2016/08/08/GC-Pauses-and-Safe-Points/#gc-suspension-in-user-code) a while back. My understanding is that 'partially/fully interruptible' code is only ever referring to *managed* code.

**Comment by xoofx** [comment]
> @xoofx if it helps I wrote about 'partially/fully interruptible' code a while back. My understanding is that 'partially/fully interruptible' code is only ever referring to managed code.

Indeed, I was travelling at this exact time, so I probably missed your post 😉

**Comment by Maoni0** [comment]
is there still interest in pursuing this? note that 

> So the background GC thread is concurrently processing the stack roots of this "pinvoke" thread (starting from the last cooperative to preemptive pinvoke transition), while the thread is still running, and there is only a protection if the thread goes back from unmanaged to managed while the GC is still running (the case of partially-interruptable I assume when there is this "gc pools" ), is it correct?

if you are talking about background GC thread processing the stack root *concurrently*, it doesn't care about pinvoke going back to managed - the "going back to managed" part is only relevant when the EE is suspended/is being suspended.

**Comment by Maoni0** [comment]
I'm closing this for now. please reactivate if you'd like to discuss further.

**Comment by xoofx** [comment]
> is there still interest in pursuing this? note that

Sorry, forgot to get back to you. 

I'm interested yes. It is a bit unexpected that it is not possible to recover from some logs the GC pause time for these threads from ETW events. That's roughly 2ms every 15ms on a working thread that are not being reported as GC sync time.

> if you are talking about background GC thread processing the stack root concurrently, it doesn't care about pinvoke going back to managed - the "going back to managed" part is only relevant when the EE is suspended/is being suspended.

I'm confused. If a working thread A is transitioning to pinvoke, and a background GC thread is triggered inspecting the managed part stack trace of A, you need a safe guard if the pinvoke code would come back to managed stack, as the thread A would start to concurrently modify the stack being inspected by the GC thread, no? How this is working otherwise?

**Comment by jkotas** [comment]
> recover from some logs the GC pause time for these threads from ETW events

It should be the time spent in RareDisablePreemptiveGC. You should be able to find the time threads are blocked with RareDisablePreemptiveGC on the stack work from the existing ETW events.

**Comment by xoofx** [comment]
> It should be the time spent in RareDisablePreemptiveGC. You should be able to find the time threads are blocked with RareDisablePreemptiveGC on the stack work from the existing ETW events.

I will check again, but last time I tried to collect all events, I was not able to get anything... maybe I messed up something

**Comment by Maoni0** [comment]
>a background GC thread is triggered inspecting the managed part stack trace of A,

that's different from what I said which was

>background GC thread processing the stack root concurrently

stack walk itself is done when EE is suspended but processing stack roots is mostly done concurrently and I was referring the concurrent stack root processing part.

>it is not possible to recover from some logs the GC pause time for these threads from ETW events. That's roughly 2ms every 15ms on a working thread that are not being reported as GC sync time.

not sure what you meant by "GC sync time" but the SuspendEEStart/End event pair includes when suspension starts (where it starts to look at threads to suspend them) till all threads are suspended. I don't understand what "roughly 2ms every 15ms" means at all. are you saying that it takes 2ms to suspend this thread or 2ms inside a GC or something else?
