### ISSUE TITLE
Reverse_LPWStr_OutAttr in COM tests are wrong

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#20970]
I was debugging a problem with one of the COM tests (Interop\COM\NETClients\Primitives). When the test was loaded into an unloadable ALC, it was executed, then the ALC was unloaded, a new ALC was created and the whole thing was repeated, it crashed in the string interning code in the native runtime.

It turns out that the test does something bad - it marshalls a string as LPWSTR by ref and then modifies its contents (reverses the string). That breaks immutability of managed strings. For interned strings, the crash happens because when we try to remove the entry from per-LoaderAllocator string literal map, we also need to remove it from the global map. To remove it from the global map, we compute the hash from the string contents – but since the string was modified, it doesn’t match the original hash and the stale entry is left in the global map. However, this entry is a pointer shared between the global and per-LoaderAllocator maps. The loader allocator cleanup code deletes the entry, since its refcount went to zero. So now the global map’s entry is pointing to the deleted memory. 
The next run of the test in a new ALC then tries to add an entry for the same string to the global map, it finds the broken entry for the string hash and crashes.

Since strings are immutable, this test case should be removed or fixed.

**Comment by janvorli** [comment]
Correction: the offending case is actually the `Reverse_LPWStr_OutAttr` test.

**Comment by AaronRobinsonMSFT** [comment]
Addressed with #21012
