### ISSUE TITLE
Windows GUI apps should display dialog for Debug.Fail

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/coreclr#20973]
Refer to https://github.com/dotnet/corefx/issues/3708#issuecomment-438005841.

The default behavior in .NET Core for Debug.Fail is to end application by calling Environment.FailFast.
WPF and winforms applications need to be able to show UI Dialog similar to in .NET Framework upon Debug.Fail (and Debug.Assert) call.

We can now use Trace Listeners as illustrated in the test [here](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Debug/tests/DebugTestsUsingListeners.cs#L248-L303) to mock Debug.Fail using Trace Listeners.

We should be able to follow the same procedure to override default Debug.Fail behavior into showing UI dialogs.

cc: @jkotas @danmosemsft @merriemcgaw

**Comment by janvorli** [comment]
This has nothing to do with PAL as it is for windows. I've changed the area to VM.

**Comment by danmosemsft** [comment]
I wonder whether, if the gui but is not set and there is a console, we should simulate a dialog at the console (ask the same question there). But perhaps it is not possible to know whether the console is redirected.

**Comment by jkotas** [comment]
> it is not possible to know whether the console is redirected

It is not possible to know whether there is somebody sitting in front of the screen, ready to respond. If somebody would prefer this behavior, they can implement it themselves. Introducing behavior like this by default would break half of the CI systems out there.

**Comment by jkotas** [comment]
The solution for this one should be the same as the solution for https://github.com/dotnet/core-setup/issues/6412. Resolving as duplicate.

cc @sdmaclea

**Comment by stephentoub** [comment]
@jkotas, it appears https://github.com/dotnet/core-setup/issues/6412 was resolved by writing to the event log.  That's the desired resolution for this?

**Comment by jkotas** [comment]
Yes, that's where we landed for 3.0 after some discussion.
