### ISSUE TITLE
[Perf] [release/2.1] Investigate Perf Scenarios failures

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/coreclr#20984]
We are seeing an issue that seems identical to what we were seeing in https://github.com/dotnet/coreclr/issues/20571. You can find the logs for the failing test here, https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/release_2.1/job/perf_scenarios_Windows_NT_x64_full_opt_ryujit/155/artifact/bin/sandbox_logs/Scenarios/Off/JitBench/JitBench_log.txt

cc: @jorive @billwert @brianrob @RussKeldorph

**Comment by RussKeldorph** [comment]
Assume this is no longer interesting in light of https://github.com/dotnet/performance.
