### ISSUE TITLE
Alternate parsers for project.json (preload package with parser and then delegate context building)

### ISSUE THREAD

**Issue by comdiv** [dotnet/coreclr#2099]
Have own yml-like parser with some object behavior that ends with set of XElements for example (in context of dnx:

```
#File hw/helloworld.bxl (totally replace package.json)
require ../default.bxl
project helloworld
    import debugsupport # as result it will be default project where in dnxcore50 System.Diagnostics.Debug will be added with  "4.0.0-beta-*" version

#File default.bxl
class project abstract
    version = "1.0.0-*"
    framework dnx451
    framework dnxcore50
        version = "4.0.0-beta-*"
        ref System.Console

class debugsupport abstract
    +framework dnxcore50
        ref System.Diagnostics.Debug


```

So this syntax is more comfortable for me and allow make more modular and centralized management for all configurations in our current solutions.
For now we go CMAKE way - we take bxl configs and generate project.json or *.csproj + *.sln files.

But may be it's possible provide way for dnx to use custom project definition directly.

For example:

In package.json

```
{
      "loader":"BxlProjectLoader, Comdiv.Contrib.Bxl",
      "file": "my.bxl"
}
```

or

```
{
    "externalloader":"bxlprojectloader.exe",
    "args":"my.bxl"
}
```

Desired behavior - 1-st case - dnx loads nuget Comdiv.Contrib.Bxl (there's no still ))), get BxlProjectLoader class and send JSON to it and get rewrited back.
2-nd case - dnx locate bxlprojectloader.exe (in accessible PATH or in special dir %profile%/dnxtools) and call it with current dir and args -> read STDOUT with rewriten project.json 

So where are no needs to support distinct project.json internal format, but such thing allow to support external project formats with implicit bridging.

**Comment by jeffschwMSFT** [comment]
Thank you for the suggestion.  Given we are now using sdk style projects, I am going to close this issue before we move to our consolidated repo.
