### ISSUE TITLE
We shouldn't hardcode "NETFX 4.5.1 Tools" in path to ResGen

### ISSUE THREAD

**Issue by poizan42** [dotnet/coreclr#210]
src/mscorlib/GenerateSplitStringResources.targets has the path to ResGen given as "$(FrameworkSDKDir)bin\NETFX 4.5.1 Tools\ResGen.exe". The recommendation from [here](https://connect.microsoft.com/VisualStudio/feedback/details/811986/-frameworksdkdir-value-in-vs-macros-post-build-event-references-invalid-path) is to use $(SDK40ToolsPath)ResGen.exe, but @AlexGhiondea mentioned that it might not work when building from the internal mirror.

Maybe we could add an Exists condition and use the "NETFX 4.5.1 Tools" path if it exists and the $(SDK40ToolsPath) path otherwise?

**Comment by AlexGhiondea** [comment]
I looked into this and the change from $(FrameworkSDKDir)bin\NETFX 4.5.1 Tools to $(SDK40ToolsPath)ResGen.exe should be safe.

We set the ResCommand property internally so changing this should not be an issue.

@poizan42 do you want to take this?
