### ISSUE TITLE
CrossGen should support existing app manifests on Windows

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/coreclr#21006]
During the crossgen process, the application manifest embedded in the IL image should be propagated to the new image when run on Windows. This If this is not done, then various scenarios could be broken (i.e. scenario where an assembly is designated to run on Windows and has embedded a manifest to enable support or some feature (i.e. RegFree COM)).

See #20986 

cc @vitek-karas @swaroop-sridhar @jeffschwMSFT

**Comment by davidwrighton** [comment]
This is fixed.
