### ISSUE TITLE
PAL: Remove PAL registration for Native file handles

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#21009]
PAL API registers file handles to create a HMODULE structure from a NATIVE_FILE_HANDLE.
Investigate whether this process is necessary, and if not remove it.

One of the things that PAL registration does is to call DLLMain() on a native DLL to mimic Windows style functionality. However, this is likely unnecessary for Unix DLLs, and can be removed.

**Comment by swaroop-sridhar** [comment]
Apart from calling DllMain() on the opened native DLLs, the PAL Module registration implements another functionality -- It uses ref-counting to use one OS-handle if the same library is opened multiple times. FreeLibrary() actually calls dlclose() only after the ref-count on the module structure runs to zero. 
I believe this is done to reduce the number of dll-handles used, which is a limited resource. 

@jkotas do you still think it is OK to remove the PAL registration code?
CC: @janvorli

**Comment by jkotas** [comment]
> the PAL Module registration implements another functionality -- It uses ref-counting to use one OS-handle if the same library is opened multiple times. 

This functionality is useless.

`dlopen/dlclose` does the exact same ref-counting as we do on any reasonable Unix system. For example, try to run the following on Linux:

```
#include <dlfcn.h>
#include <stdio.h>

int main()
{
    printf("%p\n", dlopen("libc.so.6", RTLD_LAZY));
    printf("%p\n", dlopen("libc.so.6", RTLD_LAZY));
    printf("%p\n", dlopen("libc.so.6", RTLD_LAZY));

    return 0;
}
```

You will see that it prints 3 identical numbers. It is because dlopen is just ref-counting same piece of memory (it is not actually OS kernel handle like on Windows). Our own ref-counting on top of it is a pure overhead that does not add value.

> do you still think it is OK to remove the PAL registration code?

Yes.

**Comment by swaroop-sridhar** [comment]
There are a couple of more tasks that the module structure does:
* A dl_handle to library-name map -- so that we can return the name `GetModuleFileNameW()` implementation.
    * There are a couple of places of non-windows-only code where this method is called 
* A marker to not free libraries when built for `NEED_DLCOMPAT` (via `refCount = -1`)

@jkotas Do we need to maintain the above? we likely do.

If we maintain the above information, we can still simplify the code such that:
* PAL code internally maintains a dl_handle to name/info map
    * PAL Load/Free API will insert and remove from the above map
    * Other PAL API will use the info if available for a handle, but this is optional.
* Only the OS handle is exposed outside the PAL code.

**Comment by jkotas** [comment]
> There are a couple of places of non-windows-only code where this method is called

None of those places apply here.

> `NEED_DLCOMPAT`

`NEED_DLCOMPAT` is a dead code. You can delete it while you are on it. We have deleted `dlcompat.h` that it depends on long time ago.

> Do we need to maintain the above?

We do not.

**Comment by swaroop-sridhar** [comment]
>> None of those places apply here. 

@jkotas I'm not sure what you mean by this. 
There are several places in the code that call WszGetModuleFileName and ClrGetModuleFileName wrappers. [SuperPMI](https://github.com/dotnet/coreclr/blob/master/src/ToolBox/superpmi/superpmi/parallelsuperpmi.cpp#L445) [Debugger](https://github.com/dotnet/coreclr/blob/master/src/debug/ee/debugger.cpp#L15163) [Disasm](https://github.com/dotnet/coreclr/blob/master/src/vm/disassembler.cpp#L86) [Crossgen](https://github.com/dotnet/coreclr/blob/master/src/dlls/mscoree/mscoree.cpp#L550) etc.

Removing `GetModuleFileName()` support from PAL, will need adjusting these codes like above under `FEATURE_PAL`. This handle-to-name mapping may be useful to other future features too. 

So, want to really make sure about removing this existing functionality.

**Comment by jkotas** [comment]
This primary focus of this issues should be removing the registration for the public facing DllImport / Marshal.LoadLibrary path.

It is ok to leave the registration in for the Win32 LoadLibrary that random internal pieces of code depend on if it is too hard to cleanup.

> SuperPMI Debugger Disasm Crossgen etc.

BTW: All these places call GetModuleFileName with `NULL` argument that takes a special path for EXE. It does not depend on the DLL registration.
