### ISSUE TITLE
Audit all uses of memcpy in coreclr

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#2101]
Recently we had discovered a bug in coreclr on Unix that was caused by incorrect usage of memcpy to copy memory where the source and destination regions overlapped. On Windows, it worked ok since the memcpy was copying memory in ascending order and the destination started below the source. But on Unix, the memcpy was copying memory in the reverse order and so it was not doing what the developer has intended.
There are about 600 usages of memcpy in the coreclr. We should proactively audit all of them to make sure similar issue is not lurking at some other place as well.

**Comment by benaadams** [comment]
Also might want to check the performance of `memmove` is what you expect on Windows https://github.com/dotnet/coreclr/issues/2430

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/2492 should resolve this issue
