### ISSUE TITLE
Update JIT/EE interface to get the enclosing class name from metadata

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#21042]
We exposed 64-bit-only hardware intrinsic in nested classes `X64` https://github.com/dotnet/coreclr/pull/20146, so we need the JIT/EE interface `getMethodNameFromMetaData` to return the enclosing class name as well.

Which vm interface I can use to get the enclosing class names of `X64`?
@jkotas @AndyAyersMS @CarolEidt @tannergooding

**Comment by fiigii** [comment]
Currently, we are using `GetFullyQualifiedNameInfo` to implement `getMethodNameFromMetadata`. Is there a similar function can get the enclosing class name?
https://github.com/dotnet/coreclr/blob/cd0fe8e2d781b21d18254b6414521f6399997f6e/src/vm/jitinterface.cpp#L6574-L6614

**Comment by tannergooding** [comment]
What does it currently return? I would think we could do nested partial comparisons to make this efficient?

Basically:
```
if (namespaceName.StartsWith("System.Runtime.Intrinsics"))
{
    namespaceName += "System.Runtime.Intrinsics".Length;

    if (namespaceName[0] == '\-0')
    {
        // className must be Vector64, Vector64<T>, Vector128, Vector128<T>, Vector256, or Vector256<T>
    }
    else if (namespaceName.Equals("X86"))
    {
        // clasName must be Sse, Sse2, .... 
    }
}
```

**Comment by fiigii** [comment]
> What does it currently return?

For `X64` nested classes, `getMethodNameFromMetadata` returns empty string for namespace and `X64` for class name.

> I would think we could do nested partial comparisons to make this efficient?

Yes, we can.

**Comment by jkotas** [comment]
I would add an extra `char**` argument to `getMethodNameFromMetadata` to return the nested type name if there is one.

You can use `pMT->GetEnclosingCl()` to get the token of the enclosing type.

**Comment by fiigii** [comment]
@jkotas Thank you! Will try.

**Comment by fiigii** [comment]
> You can use pMT->GetEnclosingCl() to get the token of the enclosing type.

@jkotas How can I get the MethodTable pointer from the token?

**Comment by jkotas** [comment]
You do not need to fetch the MethodTable. You can get the name & namespace using:

```
        LPCUTF8 szName, szNamespace;
        if (FAILED(pMT->GetMDImport()->GetNameOfTypeDef(pMT->GetEnclosingCl(), &szName, &szNamespace)))
        {
...
        }
```

**Comment by fiigii** [comment]
@jkotas It works, thank you!
