### ISSUE TITLE
Update fork of perf scenarios

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/coreclr#21043]
We need to update the fork for JitBench/MusicStore. We will need to get the credentials for the bot account to whoever is going to do the work on the CoreCLR side. @adiaaida @maririos

**Comment by adiaaida** [comment]
Can you explain this a bit more? Why do we need to update the fork and which branches? What is the failure mode for this? I don't have any issue with updating the fork, I'm just curious why.

**Comment by DrewScoggins** [comment]
I was talking with @jorive and I believe that there has been a substantial change in the scenario and as a result we need to update our fork, but he can perhaps speak with more clarity about it.

**Comment by adiaaida** [comment]
Ah ok. That makes sense. I haven't noticed any changes recently (we are purposefully not using the master branch of JitBench and the branches have very different outputs, so our parsing would need to change), but if you think we need to, we should.

@adamsitnik can probably speak better to why we are using the branch we are using of JitBench.

**Comment by RussKeldorph** [comment]
@DrewScoggins @adiaaida @adamsitnik @jorive I assume this is obsoleted by the dotnet/performance repo.  Please re-open if I am mistaken.

**Comment by billwert** [comment]
Yeah, this should live in the perf repo. (Though I think it is currently busted..)
