### ISSUE TITLE
32-bit SIMD indirections don't flag use of AVX

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#21055]
The `LinearScan::Build` methods are intended to call `SetContainsAVXFlags` for any potential use of AVX registers. However, this is not done in LinearScan::BuildIndir()`, which can encounter loads or stores of 32-bit SIMD types (and note that the general case in `LinearScan::BuildNode()`, which calls this method for any tree for which `varTypeIsFloating` is true, doesn't cover this case because that only covers `TYP_FLOAT` and `TYP_DOUBLE`).

**Comment by CarolEidt** [comment]
cc @fiigii @tannergooding @dotnet/jit-contrib 

I found this because, in working on supporting the HVA calling convention for Arm64, I found it was useful to directly represent SIMD arguments, rather than having them wrapped in `OBJ` nodes. This changed some block copies to direct loads/stores (reducing code size as well, since it replaced two 16-byte load/store with one 32-byte load/store). However, it also exposed some places where the `vzeroupper` was no longer being generated.

**Comment by fiigii** [comment]
> I found this because, in working on supporting the HVA calling convention for Arm64

Don’t you mean for x64?

**Comment by CarolEidt** [comment]
> Don’t you mean for x64?

No, I'm actually working on Arm64 HVA support - but the changes to the handling of SIMD nodes (not being under `OBJ` nodes) was not target-specific, and it uncovered this issue.

**Comment by fiigii** [comment]
@CarolEidt After consulted our native compiler experts, I think we probably can improve the VZEROUPPER codegen, please see https://github.com/dotnet/coreclr/issues/21062

**Comment by CarolEidt** [comment]
@fiigii - it would be great to improve the vzeroupper codegen, but I need to make a decision in the short term about whether to add in the vzerouppers (inserted, as today, in both prologue and epilogue), or to lose the vzerouppers in some of the cases that have them today.
So - the question is whether it is better to have both or none.

**Comment by fiigii** [comment]
> or to lose the vzerouppers in some of the cases that have them today.

I do not think we can eliminate vzerouppers in the epilogue, which will impact external code calling managed code (reverse P/Invoke).
