### ISSUE TITLE
arm/arm64 asserts for `Vector64.ToVector128()` and `Vector128.ToVector256` when dealing with double, long, and ulong

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#21064]
As per https://github.com/dotnet/coreclr/pull/20994#issuecomment-439516501, `Vector64<T>.ToVector128()` and `Vector128<T>.ToVector256()` both assert in the Checked CoreCLR build and with TieredCompilation disabled when dealing with `double`, `long`, and `ulong`.

The minimal repro I have gotten so far is:

```csharp
public static void Main(string[] args)
{
    Vector128<double> x = default(Vector64<double>).ToVector128();
}
```

Where `ToVector128` is:
```csharp
public Vector128<T> ToVector128()
{
    Vector128<T> result = Vector128<T>.Zero;
    Unsafe.As<Vector128<T>, Vector64<T>>(ref result) = this;
    return result;
}
````

From my own tests, it looks like the failure is falling out from the `ref Vector64<T>` return by `Unsafe.As<Vector128<T>, Vector64<T>>(ref result)`, as storing this in a local allows the test to pass on Debug mode.

Quoting @CarolEidt:
> AFAICT from the dump, it seems that things are going wrong in the morphing of the assignment to the lower 8 bytes of result. At that point, I believe that fgMorphCopyBlock should be marking it as address taken since it's a partial assignment. But it's a mystery why this would only be an issue for the double variant.

**Comment by CarolEidt** [comment]
Fixed with #21151
