### ISSUE TITLE
Downstream Failure errors

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#21079]
failed in job:
https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_throughput_linux_arm_flow/793/consoleText

failed log:
Schedule job dotnet_coreclr � perf � master � perf_throughput_linux_arm_build
Build dotnet_coreclr � perf � master � perf_throughput_linux_arm_build #689 started
dotnet_coreclr � perf � master � perf_throughput_linux_arm_build #689 completed  : FAILURE
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
[BFA] Found downstream Failure causes ...

**Comment by maririos** [comment]
Jenkins related connection error. Current jobs are passing https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_throughput_linux_arm_build/692/

So closing the issue

**Comment by v-haren** [comment]
failed in job:https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/release_2.2/job/perf_linux_flow/40/

**Comment by adiaaida** [comment]
We do not need to track failures in the flow jobs, as they just start other jobs. Failure of the downstream job (Ubuntu1604 perf) is tracked by #20850
