### ISSUE TITLE
Fixing naming of `Sse41.Test*` and `Avx.Test*` methods

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#21070]
During the last HWIntrinsics review meeting, we discussed the naming of methods that return a bool based on the CPU flags set by the instruction.

It was determined that, for methods which do this and where the flag they set has the "normal" semantics for that flag, we should use a name that represents that accurately (so this applies to methods like `Sse41.TestC`, but not to most of the Sse42 string manipulation functions).

We should update the `TestC`, `TestZ`, and `TestNotZAndNotC` methods accordingly (where `C` represents `Carry` and `Z` represents `Zero`).

These instructions behave as:
```
tmp[127:0] := a[127:0] AND b[127:0]
IF (tmp[63] == tmp[127] == 0)
	ZF := 1
ELSE
	ZF := 0
FI
tmp[127:0] := (NOT a[127:0]) AND b[127:0]
IF (tmp[63] == tmp[127] == 0)
	CF := 1
ELSE
	CF := 0
FI
```

Where:
* `TestC` returns `CF == 1`
* `TestZ` returns `ZF == 1`
* `TestNotZAndNotC` returns `(ZF == 0) && (CF == 0)`

**Comment by tannergooding** [comment]
CC. @eerhardt, @terrajobst, @fiigii, @CarolEidt

**Comment by eerhardt** [comment]
Do we have a list of proposed/recommended new names?

**Comment by tannergooding** [comment]
I don't believe we currently have any proposed names. However, if this is being done, it needs to be done before 3.0.

**Comment by tannergooding** [comment]
This issue was moved to dotnet/corefx#34882
