### ISSUE TITLE
Implement ToString for Vector64/128/256<T>

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#21096]
Currently, developers have to store `Vector64/128/256<T>` to an array to print the elements. It would be helpful for simple command line debugging if `Vector64/128/256<T>` override `ToString` method.

**Comment by fiigii** [comment]
@tannergooding @CarolEidt @eerhardt Thoughts?

**Comment by tannergooding** [comment]
We already implement the internal `DisplayString` for debugging support, so extending that to support `ToString()` wouldn't be hard (nor would extending it to be properly `IFormattable`).
* What about `GetHashCode()` and `Equals()` which are generally overridden at the same time?
* `ElementCount` is another internal one that might be useful to expose

**Comment by tannergooding** [comment]
I would recommend opening an issue on CoreFX for this (and another for the `MultiplyNoFlags` method), if those go up tonight; I can mark them as "ready-for-review" and we should be able to cover them in API review tomorrow.

**Comment by fiigii** [comment]
> I would recommend opening an issue on CoreFX for this

Done, thanks!

**Comment by fiigii** [comment]
Moved to https://github.com/dotnet/corefx/issues/33613
