### ISSUE TITLE
Running a simple 'HelloWorld' console app through the `protononjit.dll` on Windows causes various asserts

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#21108]
### Repro

1. Build a x64 Debug or Checked build of CoreCLR
2. Create and build a simple "Hello World" console app (`dotnet new console` works)
3. Enable the AltJit (`COMPlus_AltJit=*`, `COMPlus_AltJitName=protononjit.dll`) and attempt to run the console app

### Results

```
Assert failure(PID 31916 [0x00007cac], Thread: 31256 [0x7a18]): Assertion failed 'tree->IsLocal() || (tree->OperGet() == GT_RET_EXPR) || (tree->OperGet() == GT_CALL) || ((tree->gtOper == GT_ADDR) && varTypeIsSIMD(tree->gtGetOp1()))' in 'System.SpanHelpers:IndexOf(byref,ushort,int):int' (IL size 460)

    File: e:\users\tagoo\repos\coreclr_base\src\jit\simd.cpp Line: 1130
    Image: e:\users\tagoo\repos\coreclr_base\bin\tests\windows_nt.x64.debug\tests\core_root\corerun.exe
```

**Comment by tannergooding** [comment]
CC. @CarolEidt, @jkotas (this assert is in the Span Indexer)

**Comment by tannergooding** [comment]
In this particular case, the `GenTree` causing the assertion is a `GT_ADDR` where `gtOp1` is a `TYP_STRUCT` and we expect a `TYP_SIMD` (the `__vfptr` is `protononjit.dll!GenTree::DummyVirt(void)`).

**Comment by tannergooding** [comment]
Hmmm, this seems to be because you also have to set `COMPlus_Simd16ByteOnly=1`... I would've expected that to be the default (or possibly a warning) for the AltJit since ARM/ARM64 only supports 16-byte SIMD as its maximum....

**Comment by CarolEidt** [comment]
We should definitely have a better solution for this (at least an assert from the altjit if `COMPlus_Simd16ByteOnly=1` is not set. See https://github.com/dotnet/coreclr/issues/17099
