### ISSUE TITLE
.NET Core Need to Consume .NET Framework Assemblies

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [dotnet/coreclr#21107]
.NET Core needs to consume .NET Framework assemblies because there are too many assemblies in .NET Framework that have to be used.

Third party packages most of the time are not in same quality as .NET Framework.

**Comment by davidfowl** [comment]
It already can since .NET Core 2.0. It’ll only work if the set of APIs used exists in .NET Core though. You should be able to use the API port tool to determine how compatible those libraries are.

**Comment by aaabbbcccddd00001111** [comment]
I mean the assemblies in .NET Framework that are not present in .NET Core.

**Comment by jkotas** [comment]
.NET Core is never going to have all assemblies that used to be in .NET Framework. If you have a specific technology you would like to see included in .NET Core, please open issue on it in the repo that is closest to it. Here are a few example of similar issues: https://github.com/dotnet/corefx/issues/5766 or https://github.com/dotnet/corefx/issues/2394
