### ISSUE TITLE
GetCodeInfo2 gets the same native code start address after multiple JITCompilationFinished events

### ISSUE THREAD

**Issue by vkvenkat** [dotnet/coreclr#21110]
Tiered Compilation was enabled by default in .NET Core 2.2 Preview 2 and included some changes to profiling APIs. The [JITCompilationFinished](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilercallback-jitcompilationfinished-method) event is now being called twice for most function hotspots. A [GetCodeInfo2](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo2-getcodeinfo2-method) call after each such callback event fetches the same native code start address for the same function. 

Isn't GetCodeInfo2 supposed to return a different start address after each callback? Is this a bug? 
@noahfalk

**Comment by noahfalk** [comment]
That behavior in GetCodeInfo2 is by-design, we wanted to preserve back-compat on the existing API so it still produces the code regions for a single code body only. If you want to enumerate the start addresses for all available code bodies we added:
ICorProfiler9::GetNativeCodeStartAddresses - https://github.com/dotnet/coreclr/pull/14612/files#diff-e7d550d94de30cdf5e7f3a25647a2ae1R3901

Is that the behavior you were looking for?

**Comment by vkvenkat** [comment]
Thanks for the information. We will try out your suggestion and re-open the issue later if needed.
