### ISSUE TITLE
Custom CLR build. Failed to attach debugger to the process.

### ISSUE THREAD

**Issue by AndreyZWorkAccount** [dotnet/coreclr#21139]
Hi guys,
I've built CLR locally. Build process has been finished without any errors.
After the build was done I created new test application, built it using 'dotnet publish' command and then replaced runtime libraries in the output folder. Everything is ok and my application definitely uses my local version of CLR.
But when I try to attach the debugger ( Open 'CoreCLR' solution in Visual Studio 2017 -> Debug -> Attach to process ) to the running application I see the following issue:

Assert failure(PID 6948 [0x00001b24], Thread: 10044 [0x273c]): g_fEEShutDown || !"Crst Reentrancy violation"

CORECLR! CrstBase::IsSafeToTake + 0x2CA (0x00007ffe`ab682c8a)
CORECLR! CrstBase::Enter + 0x233 (0x00007ffe`ab682503)
CORECLR! ThreadStore::Enter + 0x48 (0x00007ffe`ab72a538)
CORECLR! ThreadSuspend::LockThreadStore + 0x2DB (0x00007ffe`ab70bf8b)
CORECLR! Debugger::HandleIPCEvent + 0x39F (0x00007ffe`ac330fbf)
CORECLR! `HandleIPCEventWrapper'::`3'::__Body::Run + 0x58 (0x00007ffe`ac38dca8)
CORECLR! HandleIPCEventWrapper + 0x58 (0x00007ffe`ac38ba48)
CORECLR! DebuggerRCThread::HandleRSEA + 0x41D (0x00007ffe`ac38bedd)
CORECLR! DebuggerRCThread::MainLoop + 0x885 (0x00007ffe`ac38d255)
CORECLR! DebuggerRCThread::ThreadProc + 0x7CA (0x00007ffe`ac38fe1a)

Am I doing something wrong? Why the issue appears?

**Comment by AndreyZWorkAccount** [comment]
Any news?

**Comment by janvorli** [comment]
My guess is that the issue is there for the official build as well, but since it is a release build, asserts are disabled and so it is not detected. Your build is debug or checked one, so the assert is enabled.
cc: @mikem8361, @noahfalk, @tommcdon

**Comment by AndreyZWorkAccount** [comment]
@janvorli , thank you for the response. Yes, I've built CLR using Debug mode.

**Comment by hoyosjs** [comment]
This might have gotten solved by #21498, but it's hard to tell without a hash of your build and what type of attach are you doing. Is it managed only, or mixed attach? @AndreyZWorkAccount
