### ISSUE TITLE
x64 Checked Ubuntu GCStress=0xc has two failures

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#21143]
https://github.com/dotnet/coreclr/pull/21128 fixed an issue where the GCStress tests were not running with the appropriate timeout. However, there were still two remaining failures (see https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_tst_prtest/48/ for more details):
* Loader_classloader._TypeGeneratorTests_TypeGeneratorTest1141_Generated1141_Generated1141_._TypeGeneratorTests_TypeGeneratorTest1141_Generated1141_Generated1141_sh
* Loader_classloader._TypeGeneratorTests_TypeGeneratorTest864_Generated864_Generated864_._TypeGeneratorTests_TypeGeneratorTest864_Generated864_Generated864_sh

For both of these, they look like actual failures and should be investigated further.

**Comment by sandreenko** [comment]
Do not see this issue in the last jobs (https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_tst/).
