### ISSUE TITLE
x64 Checked Ubuntu GCStress=0x3 has one failure

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#21144]
#21128 fixed an issue where the GCStress tests were not running with the appropriate timeout. However, there was still one remaining failure (see https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_gcstress0x3_tst_prtest/24/ for more details):
*  JIT_Directed._tailcall_tailcall_tailcall_._tailcall_tailcall_tailcall_sh

This failure is still a timeout (which exceeded the 120m per test limit) and should be investigated further.

**Comment by sandreenko** [comment]
I do not see these failures in the last jobs (https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_gcstress0x3_tst/)
