### ISSUE TITLE
mscorlib.xml file doesn't contain some xml doc comments

### ISSUE THREAD

**Issue by PranavSenthilnathan** [dotnet/coreclr#2115]
When I take a look at "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\mscorlib.xml", I don't see the xml documentation for a few members, like ``System.Action`1`` and ``System.Action`6``. This might be an issue in some build tools (dotnet/buildtools).

**Comment by weshaggard** [comment]
@mairaw Does this sound like a similar issue we were fixing with the intellisense files?

**Comment by mairaw** [comment]
Yes @weshaggard! These will be fixed with the updated files.

**Comment by weshaggard** [comment]
Thanks for confirming @mairaw. @PranavSenthilnathan I'm going to close this issue as it is a known issue that we expect will be fixed in the next update.
