### ISSUE TITLE
Interop_MarshalAPI._NativeLibrary_NativeLibraryTests_NativeLibraryTests_._NativeLibrary_NativeLibraryTests_NativeLibraryTests_sh [FAIL]

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#21167]
Ubuntu x64 Checked Innerloop Build and Test (Jit - TieredCompilation=0) 

Seen in https://github.com/dotnet/coreclr/pull/21159

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_no_tiered_compilation_innerloop_tst_prtest/3267/console

**Comment by jkotas** [comment]
line 244: 81852 Segmentation fault 

cc @swaroop-sridhar

**Comment by swaroop-sridhar** [comment]
Unfortunately I'm unable to repro this failure locally, and all subsequent runs in the lab have passed.
I'll try running this test in a loop.

**Comment by swaroop-sridhar** [comment]
I'll close the issue, since there was no actionable repro, we can come back to it if we get a repro.
