### ISSUE TITLE
.net core poor performance vs .net framework

### ISSUE THREAD

**Issue by manofstick** [dotnet/coreclr#21172]
Whilst playing around with some of the [Linq optimizations](https://github.com/dotnet/corefx/pull/31025#issuecomment-404900306) in .net core, I though I would try a hard-coded, not-for-general-use but nice on memory `Take` implementation.

Anyway, you can find the full gist of that [here](https://gist.github.com/manofstick/1b65890af418c1a83259d1394b127aae).

The results of this are relatively inconsequential, but what is interesting is the performance difference of my algorithm between .net core and .net framework. (I'm not confusing the obvious improvements that went into the Linq implementation).

if you use the gist and run:

    var sw = Stopwatch.StartNew();
    for (var i = 0; i < 10; ++i)
    {
        sw.Restart();
        var sortedTake = SortedTake(DataSetAdverserial(), 50);
        Console.WriteLine(sw.ElapsedMilliseconds);
    }

then the algorithm on .net framework takes ~150ms on my machine, but ~380ms under .net core (both running 64bit JIT).

I understand some small differences, but 2.5x slower seems a bit excessive? Or should this be expected with some algorithms?

**Comment by jkotas** [comment]
I assume that you are getting these results on preview .NET Core 3.0 runtime, not on the released one.

Looks like a regression from tiered compilation. We have a few known issues there. Could you please  `set COMPlus_TieredCompilation=0` and confirm that it makes the regression go away?

cc @kouvel

**Comment by manofstick** [comment]
@jkotas 

No this is .net core 2.1.500

I have made a new gist which just calls the algo from Main...

    PS C:\> mkdir speed
    PS C:\> cd speed
    PS C:\speed> dotnet --version
    2.1.500
    PS C:\speed> dotnet new console
    The template "Console Application" was created successfully.

    Processing post-creation actions...
    Running 'dotnet restore' on C:\speed\speed.csproj...
      Restoring packages for C:\speed\speed.csproj...
      Generating MSBuild file C:\speed\obj\speed.csproj.nuget.g.props.
      Generating MSBuild file C:\speed\obj\speed.csproj.nuget.g.targets.
      Restore completed in 196.15 ms for C:\speed\speed.csproj.

    Restore succeeded.

    PS C:\speed> notepad program.cs # // Code from https://gist.github.com/manofstick/5d59e96b9b9b4dac9fa256b7c66af6c2
    PS C:\speed> dotnet run -c Release
    369
    367
    441
    375
    389
    457
    386
    377
    435
    366
    PS C:\speed> csc -o Program.cs
    Microsoft (R) Visual C# Compiler version 2.10.0.0 (b9fb1610)
    Copyright (C) Microsoft Corporation. All rights reserved.

    PS C:\speed> .\program
    145
    143
    145
    143
    143
    143
    145
    142
    143
    146

**Comment by jkotas** [comment]
Do you happen to have global setting in your environment that turns on tiered compilation? Could you please try force tiered compilation on and off using `COMPlus_TieredCompilation` environment variable?

Here are the results I am getting. It is code from your gist with `Console.WriteLine($"RuntimePath={typeof(object).Assembly.Location}");` added:

```
C:\test>dotnet run -c Release
Environment.Is64BitProcess=True
Environment.Version=4.0.30319.42000
Environment.OSVersion=Microsoft Windows NT 6.2.9200.0
RuntimePath=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.6\System.Private.CoreLib.dll
114
107
106
105
105
103
108
104
109
109

C:\test>set COMPlus_TieredCompilation=1

C:\test>dotnet run -c Release
Environment.Is64BitProcess=True
Environment.Version=4.0.30319.42000
Environment.OSVersion=Microsoft Windows NT 6.2.9200.0
RuntimePath=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.6\System.Private.CoreLib.dll
311
310
313
302
303
302
300
304
300
303

C:\test>set COMPlus_TieredCompilation=0

C:\test>dotnet run -c Release
Environment.Is64BitProcess=True
Environment.Version=4.0.30319.42000
Environment.OSVersion=Microsoft Windows NT 6.2.9200.0
RuntimePath=C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.6\System.Private.CoreLib.dll
116
105
104
106
107
104
111
106
109
105
```

**Comment by manofstick** [comment]
@jkotas 

Argh; changed environmental variables, but forgot to restart shell. Sorry.

...yes, now I get expected results, so it is just a tiered regression issue...

**Comment by jkotas** [comment]
@yzrmn #20282 #19752

**Comment by yzrmn** [comment]
Thanks, did some digging and finally solved my problems!
COMPlus_TieredCompilation=0 actually solved the first issue related to disassembly output not being optimized. The second one was balanced windows power plan messing with Stopwatch timings.

**Comment by kouvel** [comment]
Looks like an occurrence of https://github.com/dotnet/coreclr/issues/19751. Tiered compilation may not tier methods called only one or a few times early enough, like `Main` and `SortedTake`. An easy solution for benchmarks like this is to disable tiered compilation. Another option in 3.0 is to attribute such methods with `[MethodImpl(MethodImplOptions.AggressiveOptimization)]`, which may be useful for cases outside benchmarks.
