### ISSUE TITLE
free(): invalid pointer

### ISSUE THREAD

**Issue by RoySalisbury** [dotnet/coreclr#21182]
.NET Core 2.1.6
Raspberry PI 3 B+
Latest Rasbian Lite 

I have a small app that I am doing some work in talking to a temperature sensor (MLX90164).  This communicates via I2C using the WiringPi library via Unosquare.RaspberryIO Nuget package.  I can view the source code for the NuGet package and the C library for wiringPi.  Only a single file handle is ever allocated, and as far as I can tell, thats not where the issue is.

If I run my program, it will abort with:

`*** Error in `/home/pi/Development/publish/TestApp': free(): invalid pointer: 0x76d65694 ***`

Running under gdb, I can get the following output.

```
[New Thread 0x6e153450 (LWP 14342)]
Ambient Temp (C): 21.71  -  Object Temp (C): 21.63
[Thread 0x6e153450 (LWP 14342) exited]
[New Thread 0x6e153450 (LWP 14347)]
Ambient Temp (C): 21.71  -  Object Temp (C): 21.61
[Thread 0x6e153450 (LWP 14347) exited]
[New Thread 0x6e153450 (LWP 14348)]
*** Error in `/home/pi/Development/publish/TestApp': free(): invalid pointer: 0x76d65694 ***

Thread 1105 "TestApp" received signal SIGABRT, Aborted.
[Switching to Thread 0x6dfff450 (LWP 14330)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x76c73824 in __GI_abort () at abort.c:89
#2  0x76cacf78 in __libc_message (do_abort=do_abort@entry=2, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:175
#3  0x76cb3ad4 in malloc_printerr (action=<optimized out>, str=0x76d66040 "free(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5049
#4  0x76cb4514 in _int_free (av=0x76d82794 <main_arena>, p=0x76d6568c, have_lock=<optimized out>) at malloc.c:3905
#5  0x768e7030 in HeapFree () from /home/pi/Development/publish/libcoreclr.so
#6  0x768e70ea in LocalFree () from /home/pi/Development/publish/libcoreclr.so
#7  0x6c5a12d0 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 

```

I have uploaded a simple test case at the following location.

https://1drv.ms/u/s!Aq5b3zEUkJG5gqQG5f2xH9-KhwlBVw

I have other sensors that do not have this issue. Strange this its just this one. You will need the MLX90614 sensor to test this.

https://www.amazon.com/KNACRO-MLX90614ESF-Temperature-Thermometer-Interface/dp/B06WVGD8WJ/

**Comment by BruceForstall** [comment]
@RoySalisbury Do you still have this problem? Have you tried .NET Core 2.2 or .NET Core 3.0? It may be difficult for us to investigate this; are you able to investigate further?

cc @janvorli

**Comment by RoySalisbury** [comment]
I'll have to update to 2.2.1 (SDK 102) and see.  I know it was still happening with 2.2.0 (SDK 100 and 101).

I worked around the issue by doing the following after each I2C read.

GC.Collect(3, GCCollectionMode.Forced);

I was going to try the (unreleased) GPIO/I2C library from the MS labs repo, but it seems that its not very well flushed out yet and missing a bunch of things.

Roy

**Comment by k3z0** [comment]
Hi Roy,

We recently discover that our nuget Unosquare.RaspberryIO.Peripherals is using a previous version of RaspberryIO. We are going to release a new version of the Peripherals package with the correct dependencies.

By the moment, try to add explicitly the newest version of RaspberryIO package:

    <PackageReference Include="Unosquare.Raspberry.IO" Version="0.17.2" />

Greetings.

**Comment by RoySalisbury** [comment]
OK.. I'll give that a shot and see if it makes any difference.

Thanks

**Comment by RoySalisbury** [comment]
I have upgraded bothe the DotNetCore Host (2.2.102) and the Unosquare.Raspberry.IO assembly as requested.  I have also remove my GC.Collect statement.  

I'll let it run over night and see if it crashes out. This will be running on my full application so it will get a pretty good workout of cpu, memory and threads.

Roy

**Comment by RoySalisbury** [comment]
Just like to report back that since upgrading to 2.2.102 and the the latest Unosquare assembly, I have not received the error that was I was getting.  Not sure if it was fixed, or just masked by some new memory allocation in 2.2.102 (had the  same thing in 2.1.100 to 2.1.101 with thread memory getting released multiple times).

So I will close it for now and reopen if it starts back up.

Thanks

Roy
