### ISSUE TITLE
"System.BadImageFormatException: Bad IL range" happen when call defined method for dotnet 2.1 or higher version

### ISSUE THREAD

**Issue by johnww89** [dotnet/coreclr#21187]
Hi all,
i am writing a profiler that use DefineMethod to define a method token of an assembly. when i call that method token in a IL code on dotnet 2.1 or higher version it will show the error: "System.BadImageFormatException: Bad IL range" but the same source code run well for dotnet 2.0.x. so what is the problem?

**Comment by johnww89** [comment]
dotnet2.0 and dotnet 3.0 which downloaded from https://github.com/dotnet/core-sdk/blob/master/README.md do not have this bug. 
dotnet2.1 and dotnet 2.2 both have this bug

**Comment by johnww89** [comment]
actually dotnet3.0 also have this bug but for different method.
i debug into coreclr find out the exception is thown because the RVA address is not valid.
in pedecoder.cpp PEDecoder::RvaToSection(RVA rva) it check rva valid by 
`
            if (rva < VAL32(section->VirtualAddress))
            {
                printf("RvaToSection1 section->VirtualAddress=%x\n",section->VirtualAddress);
                printf("RvaToSection1 rva=%x\n",rva);
                RETURN NULL;
            }`

the printf is what i added to debug the problem. in my case section->VirtualAddress=2000 and rva=844
so rva is not valid so it return null and then thow the exception.
 this is method is what i use DefineMethod to define a new method name in the assembly. i fetch rva by calling ICorProfilerInfo::GetModuleInfo to get the base address then calling GetILFunctionBody to get the method address then minus the base address. the code look like:
`GetModuleInfo(moduleId, &baseAddr, 0, NULL, NULL, NULL);
 GetILFunctionBody(moduleId, methodToken, &MethodHeader, &MethodSize);
 rva = (ULONG)(MethodHeader - baseAddr);`
and i also print this rva value it is also 844 which is the same value as the printed in coreclr. so the problem should be the baseAddr or MethodHeader. and then i decode the content from MethodHeader
and it actully is the body of that method. so MethodHeader should be correct then the problem should be baseAddr. how to get the baseaddr correct or there is any other way to get rva?
@jkotas

**Comment by jkotas** [comment]
> i debug into coreclr find out the exception is thown because the RVA address is not valid.
in pedecoder.cpp PEDecoder::RvaToSectio

What is the stacktrace when this check fails?

**Comment by johnww89** [comment]
I don't have the stacktrace. and i don't think it need stacktrace because the problem is not that place. it is because i providing wrong rva to DefineMethod. i print the correct RVA is 0x2644 in clr code. but i got 0x844 and provide it to DefineMethod so got this error. after i hardcoded the rva as 0x2644 in my profiler code it works. so the problem is how to got the rva in a profiler.
but i got RVA with the correct way i think the source is:

GetModuleInfo(moduleId, &baseAddr, 0, NULL, NULL, NULL); 
GetILFunctionBody(moduleId, methodToken, &MethodHeader, &MethodSize);
 rva = (ULONG)(MethodHeader - baseAddr);

**Comment by johnww89** [comment]
i use coreclr commit 1e647b10ab49fae4b6515666b46a3c6871a96393
and i get the rva of Microsoft.AspNetCore.Hosting.WebHostBuilder::.ctor 
Microsoft.AspNetCore.Hosting.dll version is 2.0.1
can you check that method's rva?

**Comment by johnww89** [comment]
@0xd4d 
so how to get RVA during ModuleAttachedToAssembly?
