### ISSUE TITLE
Error response from daemon: error parsing HTTP 404 response 

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#21186]
failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_throughput_linux_arm_build/736/

failed log:
Run condition [Current build status] enabling prebuild for step [[Archive the artifacts]]
[perf_throughput_linux_arm_build] $ /bin/sh -xe /tmp/jenkins875866921440804781.sh
+ docker run -i --rm -v /mnt/j/w/dotnet_coreclr/perf/master/perf_throughput_linux_arm_build:/mnt/j/w/dotnet_coreclr/perf/master/perf_throughput_linux_arm_build -w /mnt/j/w/dotnet_coreclr/perf/master/perf_throughput_linux_arm_build -e ROOTFS_DIR=/crossrootfs/arm -e CAC_ROOTFS_DIR=/crossrootfs/x86 microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-e435274-20180426002420 /mnt/j/w/dotnet_coreclr/perf/master/perf_throughput_linux_arm_build/build.sh release arm cross
Unable to find image 'microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-e435274-20180426002420' locally
docker: Error response from daemon: error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n".
See 'docker run --help'.
Build step 'Execute shell' marked build as failure

**Comment by adiaaida** [comment]
Looks like the arm docker image changed. I'm checking to see if the main jobs are failing with the same reason, or if they are on a different docker image.

@maririos @DrewScoggins

**Comment by adiaaida** [comment]
@jashook Do the arm builds not need to be done on docker images anymore?

**Comment by adiaaida** [comment]
Regular arm builds are not failing like this. Not sure what's going on, but I'm going to keep looking.

**Comment by adiaaida** [comment]
Looks like the docker image is back: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_throughput_linux_arm_build/737/console

Closing this issue.
