### ISSUE TITLE
Attribute.GetCustomAttributes missing for CoreCLR

### ISSUE THREAD

**Issue by schotime** [dotnet/coreclr#2119]
Hi,

Just wondering if Attribute.GetCustomAttributes will be available at all for DNXCore? If not is there a work around which does walk the property hierarchy?

Cheers,
Adam

**Comment by schotime** [comment]
Have looked further and found this seems to do the trick.

```csharp
#if NET35 || NET40
            var attrs = Attribute.GetCustomAttributes(mi);
#else
            var attrs = mi.GetCustomAttributes();
#endif
```

Please confirm?

**Comment by weshaggard** [comment]
Yes that is correct. We added a bunch of generic extension methods, see https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Extensions/ref/System.Reflection.Extensions.cs#L10.
