### ISSUE TITLE
Error C1076 in x64_arm64_altjit_checked_windows_nt_jitstressregs3

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21208]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_jitstressregs3/355/
**Log:**
```
c1xx : error C3859: Failed to create virtual memory for PCH [D:\j\workspace\x64_arm64_alt---b89da94d\bin\obj\Windows_NT.x64.Checked\src\vm\wks\cee_wks.vcxproj]
c1xx : fatal error C1076: compiler limit: internal heap limit reached [D:\j\workspace\x64_arm64_alt---b89da94d\bin\obj\Windows_NT.x64.Checked\src\vm\wks\cee_wks.vcxproj]
```

**Comment by AriNuer** [comment]
This issue might be related: #15414

**Comment by BruceForstall** [comment]
Those issues do look related. I'm going to close this as it appears to be just one occurrence. If it happens more frequently, we'll have to look into it.
