### ISSUE TITLE
Building nmake

### ISSUE THREAD

**Issue by jdm7dv** [dotnet/coreclr#21200]
I brought nmake from the original shared source runtime standard to my fork. There are three headers that are giving me trouble "rotor_pal.h" "pal_error.h" " and "pal_mstypes.h" what replaced these includes?

Thanks,

Jonathan

**Comment by jkotas** [comment]
`rotor_pal.h` got renamed to just `pal.h` in CoreCLR. The other headers you have mentioned are still there.

Note that there is 10+ years worth of changes between the Rotor and current CoreCLR. It is unlikely that the nmake is going to "just work".

**Comment by jdm7dv** [comment]
```
1>c:\users\jonathan_moore\my_github\not_far_from_orion\coreclr\src\nmake\rotor_pal.h(1963): error C2143: syntax error: missing ',' before '*'
1>c:\users\jonathan_moore\my_github\not_far_from_orion\coreclr\src\nmake\rotor_pal.h(2589): error C3646: 'ContextRecord': unknown override specifier
1>c:\users\jonathan_moore\my_github\not_far_from_orion\coreclr\src\nmake\rotor_pal.h(2589): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\users\jonathan_moore\my_github\not_far_from_orion\coreclr\src\nmake\rotor_pal.h(4293): fatal error C1189: #error:   PAL_TRY_LOCAL_SIZE is not defined for this architecture
```
Really the only error I'm getting

**Comment by jdm7dv** [comment]
```
expandFileNames("$", &NewList, &macros);
expandFileNames("*?", &NewList, NULL);
```
please read the build log and look in action .cpp it maybe a ```const char*``` error. And the error looks redundant.

**Comment by jdm7dv** [comment]
please see new issue ignore my last comments.
