### ISSUE TITLE
Interop\COM\NativeClients\Primitives do not see files in Core_Root

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#21221]
If you run the test with `complus_gcstress=0xc` you will see:
```
F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe Primitives.exe
Searching for exe to launch in F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Interop\COM\NativeClients\Primitives...
Launching 'F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Interop\COM\NativeClients\Primitives\COMClientPrimitives.exe'...
External disassembler is not available.
LoadLibrary failed for 'F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Interop\COM\NativeClients\Primitives\coredistools.dll': error 126
```

It happens because the test sees only libraries in its own folders and there is no an external disassembler there. That is why in #19760 there was added `<CLRTestScriptLocalCoreShim>true</CLRTestScriptLocalCoreShim>` to copy `CoreShim.dll` to the test folder.

If you copy the test files to Core_Root and run from there it will work as expected.

@AaronRobinsonMSFT Do you know what is special about this test that it doesn't see Core_Root files as others and why do we need to copy `CoreShim.dll`? 

The simple fix for this issue would be to copy the disassembler as well, but I do not think that it is the right one.

Examples of failures you can see in #21145 and #20460. I will disable this test in gcstress mode for now.

**Comment by AaronRobinsonMSFT** [comment]
>That is why in #19760 there was added `<CLRTestScriptLocalCoreShim>true</CLRTestScriptLocalCoreShim>` to copy CoreShim.dll to the test folder.

@sandreenko That isn't why that was added. It was added due to how RegFree COM works and the requirements of that system. I will have to take a quick look, but there are a myriad of potential issues hear especially how this relates to CLR activation since the test itself is native _not_ managed. Disabling this might be the right approach, but I will have to investigate.

**Comment by BruceForstall** [comment]
I get a pop-up when I run this locally.

![image](https://user-images.githubusercontent.com/10901265/49187375-26c6d980-f31c-11e8-95ba-12efbe475581.png)

Can we get this test marked GCStressIncompatible, at least for now?

**Comment by BruceForstall** [comment]
No, my code was from before your change. Didn't see your commit.
