### ISSUE TITLE
[Windows/arm64] All corefx test runs time out

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#21236]
For example,

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_baseline_flow/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstress1_flow/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstress2_flow/

**Comment by BruceForstall** [comment]
@dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
The checked runs were very slow for a few tests.  Release builds were much faster.  See #17414

**Comment by BruceForstall** [comment]
Thanks for the link.

For Linux/arm64, the runs currently take ~1 hour 10 minutes (https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_flow/66/console), and only 15 minutes is runtime. Of course, it's running in parallel on a 48-core machine.

On Windows, it takes ~7 hours 25 minutes before timing out (https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_baseline_flow/19/). On Windows it runs tests using `tests\scripts\run-corefx-tests.bat` which does NOT run anything in parallel. I don't know how fast the Windows arm64 boxes are compared to the Centriqs.

As for long-running tests, it looks like System.IO.FileSystem.Tests takes 34 minutes (of the ones that ran). The next longest takes 9 minutes.

Perhaps we could convert to run using xunit or Python, in parallel. Or maybe we just need to invest in running "the new way" (how the CoreFX "innerloop" jobs run, which uses a custom-built dotnet CLI host).

**Comment by sandreenko** [comment]
That was fixed by #22605 some time ago.
