### ISSUE TITLE
AVX MissingMethodException at runtime for current previews of SDK

### ISSUE THREAD

**Issue by gfoidl** [dotnet/coreclr#21244]
Simple repro:
```c#
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

namespace Demo
{
    class Program
    {
        static int Main()
        {
            Vector256<sbyte> vec = Avx2.SetAllVector256<sbyte>(-1);
            return vec.GetElement(0);
        }
    }
}
```

Builds and runs on SDK Version `3.0.100-preview-009765`.
Builds on later SDK Versions (`3.0.100-preview-009791` onwards), but at runtime it throws 
```
System.MissingMethodException: Method not found: 'System.Runtime.Intrinsics.Vector256`1<SByte>
```

win-x64 and linux-x64 are affected.

If https://github.com/dotnet/coreclr/issues/21174 is related, please feel free to close this one.

/cc: @tannergooding

**Comment by tannergooding** [comment]
This should be resolved in the current nightlies. I think the preview build happened to get snapped before CoreCLR/CoreFX had fully synced on this change.

**Comment by gfoidl** [comment]
I'll recheck in a couple of days. When it is resolved, I'll close the issue.

**Comment by gfoidl** [comment]
https://github.com/dotnet/corefx/issues/34444 is a duplicate of this one and should be fixed in https://github.com/dotnet/corefx/pull/34449.
