### ISSUE TITLE
Errors while build coreclr on a Azure Linux Ubuntu VM

### ISSUE THREAD

**Issue by saurabh500** [dotnet/coreclr#2124]
I am using a Azure VM for running some corefx tests. 
To run the tests, I need to build the coreclr for Linux by using ./build.sh Release in the CoreClr git clone.

However when I build it, I get the following error after which the build hangs

[  4%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/synchmgr/synchcontrollers.cpp.o
[  4%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/synchmgr/synchmanager.cpp.o
[  4%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/synchmgr/wait.cpp.o
[  4%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/thread/context.cpp.o
/home/local/REDMOND/sausing/coreclr/src/pal/src/thread/context.cpp:1289:5: error: use of undeclared identifier
      '__builtin___clear_cache'
    __builtin___clear_cache((char *)lpBaseAddress, (char *)((INT_PTR)lpBaseAddress + dwSize));
    ^
1 error generated.
make[2]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/thread/context.cpp.o] Error 1
make[1]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

The details of the kernel 
Linux hotname-linux 3.19.0-31-generic #36~14.04.1-Ubuntu SMP Thu Oct 8 10:21:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I can build coreclr on another Ubuntu baremetal installation.

**Comment by sergiy-k** [comment]
Hi @saurabh500, are you still hitting this issue?

**Comment by saurabh500** [comment]
@sergiy-k   I am not facing this anymore

Based on my comments on #2130 
 I checked the VM clang version. It was v 3.4 
 I have upgraded to v3.5 and I can build coreclr successfully now.

**Comment by sergiy-k** [comment]
Thank you!
