### ISSUE TITLE
Respect the precision specifier when formatting floats/doubles using 'E' or 'G'

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#21273]
This was broken out of https://github.com/dotnet/coreclr/issues/19802

Currently when formatting a `Single`/`Double` using the `"G"`/`"E"` specifiers, we clamp the precision specifier to 17. We should remove this limitation and instead return the number of digits the user requested.

**Comment by tannergooding** [comment]
It may be interesting to consider a mechanism that would allow users to request more than `99` digits (the current format specifier only allows two digit precision specifiers).

The longest roundtrippable string for a `double-precision floating-point value` is only 17 digits, but the longest exact value is 768 significant digits (1075 digits if you include the leading zeros). There are other programming languages, such as Python, that do allow you to return the exact string. Additionally, our existing formatting algorithms support printing as many digits as requested (provided the destination buffer is large enough).

I think that updating the existing format specifier to support more than two digit precision specifiers may be a breaking change, so adding a new API could be an alternative option if we decided this is something worth enabling (given that it is trivial to support, after we determine the shape, and sometimes useful).

**Comment by tannergooding** [comment]
> also the ability to specify the algorithm in the format

Not sure how this would be applicable. The IEEE 754 specification only has one correct answer for any given number of digits. That is, if the user requests 'X' digits, the string returned is deterministic and there is only one correct result that should be returned by any given implementation (if the algorithm returns a different result, it is incorrect).

The only thing a different algorithm should change is how efficiently it does the parsing/formatting, and we should always aim to use the best algorithm possible, overall.

**Comment by juliusfriedman** [comment]
On a more succinct note, is it really much difference of having a compat flag which is then later enhanced to accept the algorithm and other parameters...  only in terms of Implementation... hence where you would want to change this and yes I will concede that you would want the change at the system level in general however general things are... you may encounter a situation where process based configurations are required for cost or other concerns let alone security et al...

**Comment by juliusfriedman** [comment]
Thanks for the lengthy explanation. In short why don't you agree that the compat flag support which is already conceded as needed and also the fact that is also conceded that the method would not work with both implementations does not matter? 

I'm merely thinking when adding such support to please do so in a isolated and considerate way such that I would also be able to easily switch out the support therein.

**Comment by tannergooding** [comment]
A compat flag is not automatically added for every breaking change. Instead, we will consider adding a compat flag that allows users to fallback to the old behavior if there are enough users that are dependent on the old behavior. Compat flags are also generally not added to the public surface area of an API. Instead, they are enabled via configuration switches that are consumed in a "well-defined" way (someone else may be able to provide more details on how this works for netcore; on desktop you would often opt-in to the quirks via the `app.config` file).

For cases like this, I wouldn't expect many users to be dependent on requesting 20 digits but only having 17 returned.

**Comment by juliusfriedman** [comment]
And that's not mention the code or other measures I probably had to put in place to accomadate.

**Comment by tannergooding** [comment]
> And that's not mention the code or other measures I probably had to put in place to accomadate

Could you please elaborate and give examples of how you believe this will break you?

**Comment by juliusfriedman** [comment]
Specifically I have not and me.. it wont... but would imagine such unsafe code to already exist... and to those matters I will not speak.

**Comment by danmosemsft** [comment]
@tannergooding marked Future?

**Comment by tannergooding** [comment]
@danmosemsft, I think this is one that we should consider fixing for 3.0.

As it is, the `UTF8Formatter` does not support all the same format specifiers as the `UTF16Formatter` and there is no way to get an explicit number of digits for the most common formats (such as `G17`).

The overall fix should be generally trivial, since we are just passing this down to the UTF16 formatter anyways.

**Comment by danmosemsft** [comment]
Sounds good you're the area owner feel free to change.
