### ISSUE TITLE
PInvoke incorrectly handles overloaded methods

### ISSUE THREAD

**Issue by LightBender** [dotnet/coreclr#21276]
Consider the following C interface and corresponding C# PInvoke declarations.
```C
    struct slice {
        size_t length;
        void* ptr;
    }
    struct return_ulong_error {
        ulong _value;
        slice _error;
    }
return_ulong_error csharp_Test_C1_ValueProperty(void* __obj__) { //... }
return_ulong_error csharp_Test_C1_ValueProperty(void* __obj__, ulong value) { //... }
```

```C#
    internal struct slice {
        internal IntPtr length;
        internal IntPtr ptr;
    }
    internal struct return_ulong_error {
        public static implicit operator ulong(return_ulong_error ret) { return ret._value; }
        private ulong _value;
        private slice _error;
    }

[DllImport("csharp-tests", EntryPoint = "csharp_Test_C1_ValueProperty", CallingConvention = CallingConvention.Cdecl)]
private static extern return_ulong_error C1_ValueProperty(IntPtr __obj__);
[DllImport("csharp-tests", EntryPoint = "csharp_Test_C1_ValueProperty", CallingConvention = CallingConvention.Cdecl)]
private static extern return_ulong_error C1_ValueProperty(IntPtr __obj__, ulong value);
```
According to the documentation here: https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-classes-structures-and-unions#unions-sample (I know it's .NET Framework, but one would except .NET Core to work the same way) it should be possible to call overloaded C methods provided the normal overloading rules are followed.

The bug is that when calling the second method listed in the C# code, the P/Invoke system instead calls the first listed method in the C example. Note that calling the first method in the C# code ALSO calls the first method in the C example.

.NET Core Info Dump
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     fedora
 OS Version:  29
 OS Platform: Linux
 RID:         fedora.29-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.500 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by mikedn** [comment]
> return_ulong_error csharp_Test_C1_ValueProperty(void* __obj__) { //... }
return_ulong_error csharp_Test_C1_ValueProperty(void* __obj__, ulong value) { //... }

Is there a mistake in the example? Judging from the entry point you have specified the second function is supposed to be called `csharp_Test_C1_ValueProperty1`, with a 1 suffix.

**Comment by LightBender** [comment]
@mikedn Yup, corrected.

**Comment by LightBender** [comment]
@stephentoub I see it now: "The same unmanaged function"
Is this something that just doesn't work in P/Invoke?

**Comment by mikedn** [comment]
I don't understand, you seem to have changed the `DllImport` names, not the C function names. That means that this isn't actually C code since C doesn't support function overloading.

**Comment by LightBender** [comment]
It is D, which also happens to be a ANSI compliant C compiler. It looks like this might be a case of the compiler being smarter than I am and reworking the symbols underneath me.
I'll admit to never actually having worked with C specifically (my education started with C++). Sorry to bother everyone.

**Comment by mikedn** [comment]
I don't know about D but in C++ (which supports function overloading) the "exported" function names are something like `_Z28csharp_Test_C1_ValuePropertyPv` and `_Z28csharp_Test_C1_ValuePropertyPvm`, at least with Linux / GCC. On Windows with Visual C++ you'll get different names.

Apparently D has its own encoding scheme, that simply appends 1 to the function name.

In general, you'd want to avoid dealing with cross language overloading. The native compiler generated names are compiler and/or platform specific which makes things cumbersome. And DllImport doesn't know about overloading, it expects an exact name match.

**Comment by LightBender** [comment]
I appended the number at the end as a workaround. I didn't take the time to investigate what D itself is doing underneath the hood but it does use a different mangling scheme than C or C++. It could very well be a bug in the D spec, so I've raised the question with the folks over there.
It makes sense to me now that I understand the full problem space.

**Comment by LightBender** [comment]
Thank you for pointing out the painfully obvious to me though!

**Comment by svick** [comment]
As has already been stated, C does not support function overloading, so this is not possible at all in C.

C++ mangles function names by default. If you want them to have C-like names to PInvoke them, you have to use `extern "C"` and if you do that while attempting to use overloading, [you'll get an error](https://godbolt.org/z/n-ScKR) like "conflicting declaration of C function".

I don't know D, but as far as I can tell, the situation there is the same as in C++: If you want it to use C-like names, you have to use [`extern (C)`](https://dlang.org/spec/interfaceToC.html). And if you combine that with overloading, [you'll get an error](https://godbolt.org/z/T0ZKLa): "Function type does not match previously declared function with the same mangled name".
