### ISSUE TITLE
[JIT] Further work on genAllocLclFrame

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#21282]
During https://github.com/dotnet/coreclr/pull/21074 review we found several issues with genAllocLclFrame implementation (in particular, for ARM/ARM64). Here is a list of what could be improved.

- [ ] Adjust comments related to frameSize (they are wrong for ARM and they should be generalized and use pageSize instead of explicit sizes in bytes). Also look into if we really need `getVeryLargeFrameSize()`

- [ ] ARM implementation of this function has a deadcode under `(frameSize < compiler->getVeryLargeFrameSize())` case 
```c++
        if (frameSize >= 0x2000)
        {
            instGen_Set_Reg_To_Imm(EA_PTRSIZE, initReg, -2 * (ssize_t)pageSize);
            getEmitter()->emitIns_R_R_R(INS_ldr, EA_4BYTE, initReg, REG_SPBASE, initReg);
            regSet.verifyRegUsed(initReg);
        }
```
since `getVeryLargeFrameSize()` on ARM returns `2 * pageSize`

There are also several TODO comments in ARMARCH implementation of  genAllocLclFrame:
- [ ] TODO-ARM64-Bug?: set the availMask properly!
- [ ]  TODO-LdStArch-Bug?: review this. The first time we load from [sp+0] which will always succeed. That doesn't make sense
- [ ] TODO-ARM64-CQ: we could probably use ZR on ARM64 instead of rTemp.

**See also related comments:**

https://github.com/dotnet/coreclr/pull/21074#discussion_r236498347
> @mikedn: Do we actually need getVeryLargeFrameSize? It's kind of strange to call a function for this and then have a comment and even actual code that assumes that the function returns a certain value.

https://github.com/dotnet/coreclr/pull/21074#discussion_r237284879
> @echesakovMSFT Interesting that the function returns 2 * pageSize on ARM and 3 * pageSize on other platforms. So not only these comments are wrong but there is also a deadcode in ARM genAllocLclFrame in else if (frameSize < compiler->getVeryLargeFrameSize()) case.

**Comment by echesakovMSFT** [comment]
@BruceForstall @CarolEidt @mikedn PTAL

**Comment by CarolEidt** [comment]
Thanks for opening this @echesakovMSFT

**Comment by BruceForstall** [comment]
I've fixed all these issues.
