### ISSUE TITLE
error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#21298]
failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_full_opt_ryujit/3573/

failed log:
C:\j\w\perf_perflab_---22877dc9\tests\src\baseservices\typeequivalence\impl\TypeImpl.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\j\w\perf_perflab_---22877dc9\tests\dir.traversal.targets(25,5): error : (No message specified) [C:\j\w\perf_perflab_---22877dc9\tests\src\dirs.proj]
C:\j\w\perf_perflab_---22877dc9\tests\dir.traversal.targets(25,5): error : (No message specified) [C:\j\w\perf_perflab_---22877dc9\tests\build.proj]
    28 Warning(s)
    3 Error(s)

Time Elapsed 00:04:35.06
BUILDTEST: Error: build failed. Refer to the build log files for details:
    C:\j\w\perf_perflab_---22877dc9\bin\Logs\Tests_Managed_Windows_NT__x64__Release.log
    C:\j\w\perf_perflab_---22877dc9\bin\Logs\Tests_Managed_Windows_NT__x64__Release.wrn
    C:\j\w\perf_perflab_---22877dc9\bin\Logs\Tests_Managed_Windows_NT__x64__Release.err
Build step 'Execute Windows batch command' marked build as failure
[Current build status] check if current [FAILURE] is worse or equals then [FAILURE] and better or equals then [SUCCESS]
Run condition [Current build status] enabling perform for step [[Archive the artifacts]]
Archiving artifacts
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] MSBuild Error from category Build

**Comment by adiaaida** [comment]
This appears to be fixed by #21294.

**Comment by v-haren** [comment]
failed again:
https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_scenarios_Windows_NT_x64_min_opt_ryujit/1090/
https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_scenarios_Windows_NT_x64_full_opt_ryujit/3426/
https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_scenarios_Windows_NT_x64_tiered_ryujit/543/

**Comment by adiaaida** [comment]
@AaronRobinsonMSFT we are seeing these failures in builds for the performance tests because of this line:

`<Project Sdk="Microsoft.NET.Sdk">`

in tests/src/baseservices/typeequivalence/contracts/TypeContracts.csproj. Do you know why this is happening? Can we remove the SDK specifier?

**Comment by AaronRobinsonMSFT** [comment]
@adiaaida If that is removed, the build would probably fail. I don't understand why this is failing in those runs at all. Is the build environment different from other CIs?

**Comment by adiaaida** [comment]
Other than the fact that they are physical hardware, and possibly aren't having their nuget caches cleared out like fresh vms would, no.

**Comment by AaronRobinsonMSFT** [comment]
Boo. Okay, I see the issue. I will fix this. Stand by.

**Comment by AaronRobinsonMSFT** [comment]
This should be addressed in #21369

**Comment by adiaaida** [comment]
Thanks Aaron!

**Comment by ambs** [comment]
I updated my dotnet this week and I am getting this same error (and it was working before).
Some details:

```
 ambs  ~   dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.602
 Commit:    04475eb7cf

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  19.1
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.602/

Host (useful for support):
  Version: 2.1.9
  Commit:  dcedc87d22

.NET Core SDKs installed:
  2.1.602 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

My csproj has that same line: `<Project Sdk="Microsoft.NET.Sdk">`

And this error: `Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.`

Any hint is more than welcome.

**Comment by ambs** [comment]
Correction, `dotnet build` works. Just Visual Code that is now failing, no idea why.

**Comment by amagrath** [comment]
I encountered this problem trying to build a multi-project solution in a Linux Docker Container. Examining the projects, I noticed that some projects were created with an SDK of "Microsoft.Net.Sdk" and others with "Microsoft.NET.Sdk". All newly created projects have the upper-case version. I standardised ALL projects to use the upper-case version and everything compiled OK after that.

**Comment by Apostolique** [comment]
@ambs Personally, I fixed it by going in my Control Panel and uninstalling the latest "Microsoft .NET Core SDK".

If you have `"omnisharp.loggingLevel": "debug"` in your vscode settings, you should see that MSBuildToolsPath will point back to something like:
`\.vscode\extensions\ms-vscode.csharp-1.18.0\.omnisharp\1.32.11\msbuild\15.0\Bin`

**Comment by ambs** [comment]
@amagrath - Changing the case of the SDK didn't change.
@Apostolique - I think that is not the problem here. I was trying to downgrade the latest .net core, but debian packages started giving issues... and I quit (as omnisharp will need eventually to deal with new versions).

**Comment by Apostolique** [comment]
@ambs You should still enable `"omnisharp.loggingLevel": "debug"` and see which paths vscode is getting set to. The log is long, but if you start from the top you will eventually find which sdk is getting used.

There's a reason why `<Project Sdk="Microsoft.NET.Sdk">` can't be found.

**Comment by ambs** [comment]
Looking to the log file, and searching for failure reports, I found these:

````
        FAILURE: Could not locate '/home/ambs/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.11/omnisharp/msbuild/15.0/Bin/Microsoft.AspNetCore.Razor.Language.dll'.
        FAILURE: Could not locate '/home/ambs/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.11/omnisharp/msbuild/15.0/Bin/Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll'.
        FAILURE: Could not locate '/home/ambs/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.11/omnisharp/msbuild/15.0/Bin/Microsoft.CodeAnalysis.VisualBasic.Features.dll'.
        FAILURE: Could not locate '/home/ambs/.vscode/extensions/ms-vscode.csharp-1.18.0/.omnisharp/1.32.11/omnisharp/msbuild/15.0/Bin/Microsoft.Build.resources.dll'.
````

I would say this last is the critical one... and yeah, it isn't there...
