### ISSUE TITLE
Enable all CI machines for coredump

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#21305]
Several of our CI machines (specifically the Ubuntu ones) are not correctly figured for coredump collection:
> CoreDump generation not enabled due to unsupported coredump pattern: |/usr/share/apport/apport %p %s %c %d %P

We should update the images to ensure that this is set to `core.%P`

For an example, see https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_innerloop_tst_prtest/8421/

**Comment by RussKeldorph** [comment]
Closing in favor of #21134
