### ISSUE TITLE
FileSystemWatcher raises a System.NullReferenceException (fixed in CoreFX)

### ISSUE THREAD

**Issue by jcurl** [dotnet/coreclr#21307]
When deleting files, I use FileSystemWatcher to monitor when the file is really deleted (sometimes the File.Delete is returned before the file really is removed from the filesystem). This bug is observed on Windows 10 running .NET Framework 4.7.2.

The exception stack is simple:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
--
at System.IO.FileSystemWatcher.Monitor(Byte[] buffer)
at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

Looking at the reference sources I've identified the error, and also confirmed that this error is documented and fixed at https://github.com/dotnet/corefx/issues/1556 (with PR https://github.com/dotnet/corefx/pull/1649/commits/f2720abb758b50a9debb5ec146939ef6f5cef82d). The fix appears to be simple, but a reliable workaround in my code to this bug appears very difficult, without introducing memory leaks (don't dispose the FileSystemWatcher class).

This issue has been reproduced rarely, but I have 3 instances of it occurring. Once on my Surface Book Pro running Win 10 v1809, the other on a Win7 machine (sorry, don't know the .NET version there).

**Comment by danmosemsft** [comment]
Hello @jcurl. This repo is for..NET Core issues. The best place to report NET Framework issues is at https://developercommunity.visualstudio.com/spaces/61/index.html (I think)
Note that.NET Framework is taking much fewer changes because it must balance the risk of each change.

**Comment by jcurl** [comment]
Thanks. Raised it there under https://developercommunity.visualstudio.com/content/problem/396666/filesystemwatcher-raises-a-systemnullreferenceexce.html.
