### ISSUE TITLE
new CultureInfo() doesn't always throw for invalid culture on Linux

### ISSUE THREAD

**Issue by derwasp** [dotnet/coreclr#21306]
[CultureInfo()](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=netframework-4.7.2) doesn't throw an expected exception on **linux**, though it does on windows.
`dotnet --version` is **2.1.403** on linux. Different version on windows.
When a constructor of the CultureInfo class is called with a _short_ string of random text, it doesn't throw an exception.

If you run the following script it would actually compile and display "hello" on linux, but throw an exception on Windows.

```
mkdir testConsoleApp
cd testConsoleApp
dotnet new console

cat >./Program.cs <<EOL
using System;
namespace testConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(new System.Globalization.CultureInfo("hello"));
        }
    }
}
EOL

dotnet run
```

Example output:

```
root@7f3bdfda572e:/# mkdir testConsoleApp
root@7f3bdfda572e:/# cd testConsoleApp
root@7f3bdfda572e:/testConsoleApp# dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /testConsoleApp/testConsoleApp.csproj...

  Restoring packages for /testConsoleApp/testConsoleApp.csproj...
  Generating MSBuild file /testConsoleApp/obj/testConsoleApp.csproj.nuget.g.props.
  Generating MSBuild file /testConsoleApp/obj/testConsoleApp.csproj.nuget.g.targets.
  Restore completed in 172.34 ms for /testConsoleApp/testConsoleApp.csproj.

Restore succeeded.

root@7f3bdfda572e:/testConsoleApp#
root@7f3bdfda572e:/testConsoleApp# cat >./Program.cs <<EOL
> using System;
> namespace testConsoleApp
> {
>     class Program
>     {
>         static void Main(string[] args)
>         {
>             Console.WriteLine(new System.Globalization.CultureInfo("hello"));
>         }
>     }
> }
> EOL
root@7f3bdfda572e:/testConsoleApp#
root@7f3bdfda572e:/testConsoleApp# dotnet run

hello
```

The interesting thing is that if you would run this script, it would actually throw an exception.

```
mkdir testConsoleApp
cd testConsoleApp
dotnet new console

cat >./Program.cs <<EOL
using System;
namespace testConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(new System.Globalization.CultureInfo("Hello World!"));
        }
    }
}
EOL

dotnet run
```

Example of exception:

```
root@7f3bdfda572e:/testConsoleApp# dotnet run

Unhandled Exception: System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
Hello World! is an invalid culture identifier.
   at System.Globalization.CultureInfo.InitializeFromName(String name, Boolean useUserOverride)
   at testConsoleApp.Program.Main(String[] args) in /testConsoleApp/Program.cs:line 8
```

**Expected result**

`System.Globalization.CultureNotFoundException: Culture is not supported.` is thrown consistently on all platforms.

**Comment by jkotas** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
The .Net is using the ICU http://userguide.icu-project.org/locale on Linux for getting the culture information. If ICU permit creating such cultures, then .Net will just use it. The culture can be created if the name conform to the BCP-47 https://tools.ietf.org/html/bcp47 and that is why "hello" succeeded and "Hello World!"  doesn't. I believe Windows 10 started to adapt the same behavior which allow creating cultures with BCP-47 formed names even if Windows doesn't have a real data for such cultures,

**Comment by derwasp** [comment]
@tarekgh got it, thanks.
Though I got the idea, it's a bit unexpected that because of it, apps would behave differently on different environments.

**Comment by tarekgh** [comment]
@derwasp

> apps would behave differently on different environments.

We always advice that the apps don't assume the globalization data wouldn't change. this always happen anyway. The good globalized apps should work seamlessly regardless the globalization data. Also, it is good thing to have parity with the underlying OS behavior. This is by design for the .NET.
