### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#21349]
failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/release_2.1/job/sizeondisk_x64/305/

failed log:
D:\j\w\sizeondisk_x64f7d2f24d>exit 0 
[sizeondisk_x64f7d2f24d] $ cmd /c call C:\Users\runner\AppData\Local\Temp\jenkins1877164351699745079.bat

D:\j\w\sizeondisk_x64f7d2f24d>if "origin/" == "origin/" (set "GIT_BRANCH_WITHOUT_ORIGIN=release/2.1" )  else (set "GIT_BRANCH_WITHOUT_ORIGIN=origin/release/2.1" ) 

D:\j\w\sizeondisk_x64f7d2f24d>set "BENCHVIEWNAME=Dotnet Size on Disk Mon 12/03/2018 19:16:19.85" 

D:\j\w\sizeondisk_x64f7d2f24d>set "BENCHVIEWNAME=Dotnet Size on Disk Mon 12/03/2018 19:16:19.85" 

D:\j\w\sizeondisk_x64f7d2f24d>C:\Python35\python.exe "D:\j\w\sizeondisk_x64f7d2f24d\Microsoft.BenchView.JSONFormat\tools\submission-metadata.py" --name "Dotnet Size on Disk Mon 12/03/2018 19:16:19.85" --user-email "dotnet-bot@microsoft.com" 
The system cannot find the path specified.

D:\j\w\sizeondisk_x64f7d2f24d>C:\Python35\python.exe "D:\j\w\sizeondisk_x64f7d2f24d\Microsoft.BenchView.JSONFormat\tools\build.py" git --branch release/2.1 --type rolling 
The system cannot find the path specified.

D:\j\w\sizeondisk_x64f7d2f24d>exit 3 
Build step 'Execute Windows batch command' marked build as failure

**Comment by adiaaida** [comment]
Issue moved to [dotnet/core-eng #4743](https://github.com/dotnet/core-eng/issues/4743) via [**ZenHub**](https://www.zenhub.com/)
