### ISSUE TITLE
Make EventPipe circular buffer work as a true circular buffer

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#21357]
Today the EventPipe is implemented as a set of per-thread circular buffer and these buffers.  This means that some threads might got back in time more than other threads.   Moreover is that it is hard to know when in the trace you have 'full information' from all threads.   This leads to subtle bugs and misunderstandings about the trace.

Instead  EventPipe should bookkeep enough information so that it can know that time where all threads have information in their circular buffers, and only output information after that point (at least by default).

**Comment by tommcdon** [comment]
@noahfalk should we move this to future?

**Comment by noahfalk** [comment]
I'm actually going to suggest we just close this. I think Vance is referring to the current direct file-writing behavior that attempts to maintain a ring buffer and then writes out whatever is in that buffer when tracing is disabled. That behavior isn't going to be what people see when they use dotnet-trace, we haven't documented it, and I suspect at some point we will either deprecate it entirely or fix it to do something more useful.
