### ISSUE TITLE
MSB4019: The imported project ".../netcoreapp-Linux-Release-x64/Microsoft.Net.Test.Sdk.props" was not found.  

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#21399]
failed in job: https://ci2.dot.net/job/dotnet_corefx/job/perf/job/master/job/perf_ubuntu16.04_release/3573/

failed log:
[/home/administrator/jenkins/w/dotnet_corefx/perf/master/perf_ubuntu16.04_release/src/System.Windows.Extensions/tests/System.Windows.Extensions.Tests.csproj]
/home/administrator/jenkins/w/dotnet_corefx/perf/master/perf_ubuntu16.04_release/Directory.Build.props(444,3): error MSB4019: The imported project "/home/administrator/jenkins/w/dotnet_corefx/perf/master/perf_ubuntu16.04_release/artifacts/bin/runtime/netcoreapp-Linux-Release-x64/Microsoft.Net.Test.Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by adiaaida** [comment]
@ViktorHofer this seems to have started failing with ae38b7cc3762d832fdcebe27a0aab7b22ab2f3fa

**Comment by AaronRobinsonMSFT** [comment]
I am going to go out on a limb here and say this is similar to the issue a few days ago - #21298. Not sure how to confirm, but it could be related.

**Comment by ViktorHofer** [comment]
Fix is here: https://github.com/dotnet/corefx/pull/33867

**Comment by BruceForstall** [comment]
FYI, this is affecting dozens of arm32/arm64 jobs as well.

**Comment by AraHaan** [comment]
This seems to affect most of the jobs on my pull request as well.

**Comment by ViktorHofer** [comment]
The change is now in corefx master.

**Comment by AraHaan** [comment]
@ViktorHofer It seems after merging the change in that it still seems to happen in jenkins.

**Comment by ViktorHofer** [comment]
Right, another casing was still wrong. Opened https://github.com/dotnet/arcade/pull/1496

**Comment by ViktorHofer** [comment]
Closing this as it should now be resolved.
