### ISSUE TITLE
Ubuntu dotnet package conflicts with xamarin packages

### ISSUE THREAD

**Issue by dlech** [dotnet/coreclr#2139]
I am trying to install the `dotnet` package on Ubuntu 14.04 as described on <http://dotnet.github.io/getting-started/>, however, the installation fails because it tries to install the same file in the same place as one of the Xamarin mono packages.

```
Unpacking dotnet (1.0.16759.1448048244-1) ...
dpkg: error processing archive /var/cache/apt/archives/dotnet_1.0.16759.1448048244-1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/resgen', which is also in package mono-devel 4.2.1.102-0xamarin1
```

I have a bit of experience with debian packaging. If someone could point me to where the `dotnet` source code is, I would be glad to have a look at it.

**Comment by akoeplinger** [comment]
See https://github.com/dotnet/cli/issues/125

**Comment by dlech** [comment]
Thanks. I figured I couldn't be the first person to report this, but I couldn't find it.
