### ISSUE TITLE
Clarify Visual Studio 2015 support

### ISSUE THREAD

**Issue by richlander** [dotnet/coreclr#214]
Please add Visual Studio 2015 support here: https://github.com/dotnet/coreclr/wiki/Developer-Guide

This should be CTP-specific, with links to the actual download location.

**Comment by ellismg** [comment]
I don't think that we support VS 2015 yet, because of some stuff around the DIA libraries.  Is this a dupe of #30?

**Comment by richlander** [comment]
OK. That clarifies it. I'll close this.
