### ISSUE TITLE
Enumerable.Range terminates prematurely inside an async iterator

### ISSUE THREAD

**Issue by pkanavos** [dotnet/coreclr#21404]
The code in issue #21379 compiles succesfully after adding the bridging code but `Enumerable.Range()` iterates only twice. The following code : 

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    namespace TestCsConsole
    {
        class Program
        {
            static async Task Main(string[] args)
            {
                await foreach (var num in GetNumbersAsync())
                {
                    Console.WriteLine($"{ num,5}");
                }
                Console.ReadKey();
            }

            private static async IAsyncEnumerable<int> GetNumbersAsync()
            {
                foreach (var num in Enumerable.Range(0, 10))
                {
                    await Task.Delay(100);
                    yield return num;
                }
            }

        }
    }

Will print just 

    0
    1

This doesn't happen with arrays or even other iterator methods. This code : 

    private static async IAsyncEnumerable<int> GetNumbersAsync()
    {
        foreach (var num in counter(0, 10))
        {
            await Task.Delay(100);
            yield return num;
        }
    }
    private static IEnumerable<int> counter(int start,int count)
    {
        for (int i = start; i < count; i++)
        {
            yield return i;
        }
    }

WIll print : 

    0
    1
    2
    3
    4
    5
    6
    7
    8
    9

Using .NET Core SDK 3.0.100-preview-009812 on Windows 10 x64

**Comment by stephentoub** [comment]
This is a compiler bug: https://github.com/dotnet/roslyn/issues/31268
