### ISSUE TITLE
mscorlib.dll build failed on Windows 10 TH2

### ISSUE THREAD

**Issue by mcfi** [dotnet/coreclr#2140]
mscorlib.dll build failed on Windows 10 TH2 with the following error message:

C:\Users\Ben\Documents\GitHub\coreclr\src\mscorlib\Tools\Versioning\NativeVersion.rc(8): fatal error RC1015: cannot open include file 'windows.h' [C:\Users\Ben\Documents\GitHub\coreclr\src\mscorlib\mscorlib.csproj]

C:\Users\Ben\Documents\GitHub\coreclr\src\mscorlib\Tools\Versioning\GenerateVersionInfo.targets(111,5): error MSB3073: The command ""C:\Program Files (x86)\Windows Kits\10\bin\x86\rc.exe" /nologo /x /i "C:\Users\Ben\Documents\GitHub\coreclr\bin\obj\Windows_NT.x64.Debug" /i "C:\Program Files (x86)\Windows Kits\10\Include\wdf\um" /i "C:\Program Files (x86)\Windows Kits\10\Include\wdf\\shared" /D _UNICODE /D UNICODE /l"0x0409" /r /fo "C:\Users\Ben\Documents\GitHub\coreclr\bin\obj\Windows_NT.x64.Debug\\NativeVersion.res" "C:\Users\Ben\Documents\GitHub\coreclr\src\mscorlib\Tools\Versioning\NativeVersion.rc"" exited with code 1. [C:\Users\Ben\Documents\GitHub\coreclr\src\mscorlib\mscorlib.csproj]

It seems that the Windows SDK on for Win 10 TH2 does not have directories "C:\Program Files (x86)\Windows Kits\10\Include\wdf\um" and "C:\Program Files (x86)\Windows Kits\10\Include\wdf\\shared".

**Comment by mikedn** [comment]
I've ran into this myself a while ago but as far as I can tell it's not a Windows issue nor a CoreCLR issue. It's a bug in the Windows Driver Kit, it dumps some directories in the wrong place and the build tools get confused and pick the wrong paths. Try uninstalling it.

**Comment by mcfi** [comment]
Uninstalling the Windows Driver Kit worked. Thanks, Mike.

**Comment by weshaggard** [comment]
Seems like this issue is resolved so closing.
