### ISSUE TITLE
Createdump utility - minidump does not show method names

### ISSUE THREAD

**Issue by klesta490** [dotnet/coreclr#21402]
Hi!
Sorry for notifying directly @mikem8361, but it seems to me that you would answer that anyway :).

I am having trouble using CreateDump utility, if I use standard minidump, I don't see any method names and the output looks like this. 
```
(lldb) sos DumpStack
...
00007FFF95C49170 00007fc1907716ed (MethodDesc 00007fc18fb058f8 + 0x5d /app/ApacheKafkaBackup.dll!Unknown), calling 00007fc190771288 (stub for /app/ApacheKafkaBackup.dll!Unknown)
...
```

if full dump is done, it is OK and I see method names from my dll. I am using createdump from NetCore 2.1.4

**Comment by mikem8361** [comment]
This is a known issue (https://github.com/dotnet/diagnostics/issues/56). I plan to fix it in SOS itself, but I think a workaround was added to createdump in the master branch (3.0). It didn’t make into 2.1 or 2.2.

**Comment by klesta490** [comment]
Thanks for answer. Can I dump net core app running on 2.1.4 with 3.0 createdump?
