### ISSUE TITLE
CoreConsole fails if there is a space in the main EXE location

### ISSUE THREAD

**Issue by wjk** [dotnet/coreclr#2143]
I am using CoreConsole as the basis of a custom CoreCLR entry-point for my GUI app. I have patched it to use `_tWinMain` instead of `wmain`, and it actually works. However, I find that if there is a space in the full path to the main executable (regardless of the actual value of `argv[0]`), then either CoreConsole or CoreCLR gets horribly confused. For example, if `argv[0]` is `C:\Users\wjk\Documents\Visual Studio 2015\Projects\MyProject\MyProject.exe`, then I get the error `Cannot load "Visual.dll"`. Moving the main executable to a path containing no spaces solves the problem, but is not scalable. Once I install my program into `C:\Program Files\MyProgram` (and I plan on doing so), it will break again unless this bug is fixed.

I am not familiar enough with the CoreCLR codebase to triage the issue any further. Any pointers?

**Comment by wtgodbe** [comment]
Hi,

I am not able to get a repro of this problem - out of curiosity, what happens when you install your program to 'C:\Program Files\MyProgram' and run it from there?

**Comment by wjk** [comment]
@wtgodbe Unfortunately, I cannot currently tell you the answer to this. Due to [dotnet/cli#948](https://github.com/dotnet/cli/issues/948) et al, I cannot successfully build my app to test this issue or anything else.

**Comment by wtgodbe** [comment]
@wjk are you able to repro this locally yet?

**Comment by wjk** [comment]
Not yet. I'm sorry. Even though [dotnet/cli#948](https://github.com/dotnet/cli/issues/948) has been resolved, I still cannot build my app. I'll get back to you once I can.

**Comment by wjk** [comment]
@wtgodbe I got it to work! :smile: When I copy my program into this directory: `C:\Users\William\Documents\Visual Studio 2015\Projects\VSU\VisualStudioUninstaller.exe`, and I run it, the program exits immediately. Running it from the Command Prompt enables me to see the following error message:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Visual.dll' or one of its dependencies. The system cannot find the file specified.
```

Unfortunately, I don't know _which_ DLL it is trying to load, only that it loaded CoreCLR successfully, thanks to the .NET exception diagnostic being shown. However, my app uses no reflection; all assemblies are referenced via `dnx` project references, and this should be looked for by the CoreCLR dynamic loader equivalent.

**Comment by wtgodbe** [comment]
Alright, my suspicion is that it's trying to load "Visual.dll" because the first space in the path to your executable comes after the word "Visual" - did you draw the same conclusion? To confirm, can you move it to a different directory with a space after some other word?

**Comment by wjk** [comment]
I have tried running the program inside the directory `C:\Users\William\Documents\GitHub\My Uninstaller App`, but the only difference is that it now can't find `My.dll`.

**Comment by wtgodbe** [comment]
OK that confirms my suspicion - just to be sure, when you run from the command line, what exactly are you entering into the command prompt? Are you surrounding it with quotes? (i.e., you should be running `"C:\Users\William\Documents\GitHub\My Uninstaller App"`)

**Comment by wjk** [comment]
What I usually do is `cd` into the directory using a Command Prompt and then run the program from inside this directory; however, typing the full, absolute path to the .EXE file, in quotes, makes no difference.

**Comment by wtgodbe** [comment]
Interesting. I'll see if I can get a repro on my end.

**Comment by wtgodbe** [comment]
Would it be possible for you to provide a stack trace? I still can't get a repro - the same scenario works fine on my system

**Comment by wjk** [comment]
@wtgodbe How should I do that? All I see when I try to run the program is the exception message.

**Comment by wtgodbe** [comment]
Actually, it might be easier if you share your app/environment with me - do you think you could host the directory you're running your app from on github, and I can try to get a repro that way?

**Comment by wtgodbe** [comment]
Also, could you give me the exact steps you're using to reproduce the error (command prompts and all)?

**Comment by wjk** [comment]
I think I found my problem. Because I am writing a GUI app, I must use the `WinMain` entry point. `WinMain` (in my case `_tWinMain`) passes the command line as one string. CoreCLR expects a standard `argc`/`argv` pair, so I used `CommandLineToArgvW()` to split the command line, but inspection using the debugger reveals that `CommandLineToArgvW` is splitting the full path to the EXE on any spaces, just as it should, except if there are any inside `argv[0]`, that value will be incorrectly truncated. I suspect that this may be a bug in `CommandLineToArgvW()`, as I have seen reports of longstanding bugs in that function. @wtgodbe Do you have any ideas as to how I should split the command line that won't fall victim to this issue?

(Note: Care must be taken to ensure proper behavior when the program is run both with and without any arguments, as it may be invoked either way when it is completed.)

**Comment by wtgodbe** [comment]
Ah, I see! That makes sense - are you using the parameter lpCmdLine from WinMain to get your command line arguments, or are you getting the command line from GetCommandLine? (https://msdn.microsoft.com/en-us/library/windows/desktop/ms683156(v=vs.85).aspx). I suspect if you use quotes around the path name, and use GetCommandLine, that your problem will be solved.

**Comment by wjk** [comment]
That did it, all right! My program now runs correctly even if there is a space in the full path to its main EXE. Thanks so much!

**Comment by wtgodbe** [comment]
Great! Happy to help.
