### ISSUE TITLE
[arm64/windows] SyntaxError in arm64_cross_checked_windows_nt_corefx_baseline_bld

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21433]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_baseline_bld/22/
**Failed log:**
```
D:\j\workspace\arm64_cross_c---efb15e6d>python -u D:\j\workspace\arm64_cross_c---efb15e6d\tests\scripts\run-corefx-tests.py -arch arm64 -ci_arch arm64 -build_type Checked -fx_root D:\j\workspace\arm64_cross_c---efb15e6d\_\fx -fx_branch master -env_script D:\j\workspace\arm64_cross_c---efb15e6d\SetStressModes.bat -no_run_tests 
  File "D:\j\workspace\arm64_cross_c---efb15e6d\tests\scripts\run-corefx-tests.py", line 53
    os.chmod(name, 0651)
                      ^
SyntaxError: invalid token
```

**Comment by AriNuer** [comment]
similar in jobs:

- https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstress2_bld/22/
- https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstressregs0x1000_bld/21/
- https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstressregs0x80_bld/22/

**Comment by sandreenko** [comment]
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
This is an issue with the script and Python 3+. Python 2.7 works.
