### ISSUE TITLE
thousand test failures in corefx.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#21445]
Examples in baseline jobs: [x64](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/710/), [x86](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/682/testReport/).

I have not found an exisiting issue, please close this as dup if there is one.
Most of tests fail with:
`System.PlatformNotSupportedException : This platform does not support distributed transactions.` or CoreFX asserts.
Are these tests new?

**Comment by sandreenko** [comment]
Looks like these tests are [old ](https://github.com/dotnet/corefx/blob/f8df80f76769aa842ecf2c79eb3e3250d473c7e3/src/System.Runtime.Extensions/tests/System/IO/PathTests_Unix.cs)and has not changed recently, so maybe it is a regression.
cc @dotnet/jit-contrib .

**Comment by BruceForstall** [comment]
Looks like there's a fix out for this: https://github.com/dotnet/arcade/pull/1577 (also see https://github.com/dotnet/coreclr/issues/21464#issuecomment-447080944)

**Comment by sandreenko** [comment]
Fixed by dotnet/arcade#1577
