### ISSUE TITLE
Add ThreadPool.UnhandledException type delegate

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#2144]
Throwing an unhandled exception at the top level of a ThreadPool thread either by using `ThreadPool.QueueUserWorkItem` or use of `async void` will crash the process (by design?) and they cannot be stopped and are at the top of the stack.

It would be better if `ThreadPool` had a something like `TaskScheduler.UnobservedTaskException` to catch these events so they could be logged/handled.

**Comment by ayende** [comment]
And recovered from!

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by kouvel** [comment]
Is there a good reason why the exception cannot be handled by the task or work item queued to the thread pool? I don't see why an unhandled exception handler is required when a simple try/catch would suffice. Maybe I missed something.

**Comment by benaadams** [comment]
@kouvel Yes wrapping the functions internally in a try catch will solve the issue; however when providing a server library that calls user code people can and will use things like `async void` for example https://github.com/aspnet/Hosting/issues/484 and https://github.com/aspnet/Mvc/issues/3901 which will cause the server to crash.

The threadpool specifically can be handled by wrapping the function in a lamba prior to putting it on the threadpool; but its not great e.g. https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Infrastructure/LoggingThreadPool.cs

**Comment by kouvel** [comment]
Ignoring exceptions from these fire-and-forget tasks can be problematic too, a task waiting for a state change or signal from another task that throws an exception could just hide the bug. They could also just create a thread and throw an exception in that thread.

Even making it configurable whether to crash or not doesn't seem like a good solution, as it would have to be configured at the process level, and a handler would not be able to associate an exception with a task. The current design leaves it up to the task to handle exceptions, and these fire-and-forget tasks should always handle exceptions, the task should know best how to do so. In a case like above, where there is a dependent task, I don't see a good way to handle an out-of-band exception sent to an event, attribute it to the faulty user code, and recover gracefully.

If you want fault tolerance in the server, why not isolate potentially faulty user code in a separate process? That would at least allow graceful recovery, and if fault attribution is important, you can determine how much process isolation to use for that.

**Comment by davidfowl** [comment]
https://msdn.microsoft.com/en-us/library/system.threading.tasks.taskscheduler.unobservedtaskexception(v=vs.110).aspx

In .NET 4.0 exceptions on unobserved tasks crashed the process as well, turns out this is pretty bad behavior for a plethora of reasons so the above event was added. Something more generic for thread pool threads would be great as well.

/cc @stephentoub for thoughts

**Comment by NickCraver** [comment]
On a similar vein, has there been any thought to a replacement for `AppDomain.UnhandledException` at the process level now that `AppDomain` is gone? When we want to do global error handling it's easy enough with logging and middleware wrappers in ASPNet Core, but I'm coming up short on options for non-ASPNet applications.

**Comment by dotnetshadow** [comment]
#3348

**Comment by dotnetshadow** [comment]
Please see the updated reference at #3348

**Comment by dotnetshadow** [comment]
aspnet/dnx#3348

**Comment by kouvel** [comment]
`AppDomain.UnhandledException` was added with dotnet/corefx#11275
