### ISSUE TITLE
openSUSE 13.2 rolling / outerloop build failure on missing libuuid dependency

### ISSUE THREAD

**Issue by joshfree** [dotnet/coreclr#2145]
The openSUSE coreclr build is continuously failing:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_opensuse13.2/lastBuild/console
08:34:13 CMake Error at src/pal/src/configure.cmake:918 (message):
**08:34:13   Cannot find libuuid.  Try installing uuid-dev or the appropriate packages**
08:34:13   for your platform
08:34:13 Call Stack (most recent call first):
08:34:13   src/pal/src/CMakeLists.txt:5 (include)

@ramarag can you make the fix since you added the dependency?

/cc @mmitche @gkhanna79

**Comment by gkhanna79** [comment]
@joshfree I am not aware of Rama adding a dependency on libuuid. He added a dependency for liblttng. This issue looks to be in the PAL - @janvorli can you please take a look?

**Comment by janvorli** [comment]
Yes, we depend on libuuid on Linux, the dependency has been there for about a month. @mmitche can you please install libuuid on the openSUSE CI machines?

**Comment by mmitche** [comment]
@janvorli Done
