### ISSUE TITLE
Console.Write behaviour differs from full .NET

### ISSUE THREAD

**Issue by glennc** [dotnet/coreclr#2146]
I don't know if this is known or then underlying reason for this, but the following code appears to behave differently between desktop and core clr on my Windows 10 machine.

```c#
class Program
{
    static void Main(string[] args)
    {
        Console.Write("prompt>");
        var input = Console.ReadLine();
        Console.WriteLine("echo " + input);
        Console.ReadLine();
    }
}
```

standard C# console app output:
```
prompt>hello
echo hello
```

Using dotnet cli to run the same code with dnxcore50 as my framework I get this:

```
hello
prompt>echo hello
```

**Comment by stephentoub** [comment]
Hmm, using csc.exe to compile and corerun to execute, on both Windows 10 and Linux I see:
```
prompt>hello
echo hello
```
I've not tried with dotnet cli, but this suggests to me that it's not an issue with coreclr or with System.Console.dll in corefx.

**Comment by glennc** [comment]
Interesting. I was assuming it was a System.Console.dll issue. Let me try a few more things...

**Comment by glennc** [comment]
Ok, looks like it is specifically when doing `dotnet run` compiling and executing works fine as well. So it is most likely an issue with the way we are launching it.

I'll close this and go create an issue on the cli.

**Comment by glennc** [comment]
@stephentoub I spent a little bit of time this morning with @anurse looking at this.

Looks like you see this problem when redirecting console output. The dotnet cli compile and runs my program, and it forwards output from my programs process to the console. It listens to OutputDataRecieved : https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Cli.Utils/Command.cs

But it doesn't look like it is being flushed properly after write, and adding code like this `Console.Out.Flush();` in-between the write and the readline doesn't do anything, which I would've thought would force something to happen.

Is there something I am missing about how this works that makes the `dotnet cli` approach to proxying output from its process to the console not viable? I suspect there are some other issues with the way it works, but I would like to understand this particular problem.

**Comment by stephentoub** [comment]
@glennc, can you share a standalone repro (not using dotnet cli, just using the Process APIs) that does what you expect on Windows but not on Linux?  I took a look at the link you sent, but there's a lot of indirection happening via delegates and writers and whatnot being passed around and types named things I'm not familiar with (e.g. Reporter), so it's difficult for me to understand exactly what's talking to what.

**Comment by glennc** [comment]
Yeah, sure thing.

**Comment by glennc** [comment]
I should add some clarification as well, I am not convinced that this is a Core CLR/CLR difference (I will verify that now as I get a repro). But that it will probably boil down to: What is the correct way, if any, to run a console application from code and direct all of its output to the console of the hosting application. The way it is being done in the `dotnet cli` doesn't appear to be correct.

**Comment by anurse** [comment]
FYI, this behavior occurs in both CLR and CoreCLR and does not appear to be limited to the CLR. It looks like it's not possible to disable line-buffering on the stdout pipe from a Windows process. Even using a sub-process in C++ and manually flushing doesn't appear to work.

Looks like repl-style apps just won't be feasible in dotnet run for the near future at least because it redirects the output/error streams of the compiled app.

**Comment by anurse** [comment]
I have boiled down some code here: https://github.com/anurse/Scratch/tree/master/stdout-pipe-and-repl

Looks like removing the StdOut/StdErr forwarding does solve the problem, but that would be unfortunate if necessary because we were capturing that in some scenarios. Looks like most of those are no longer relevant in dotnet-cli so we can disable that.

**Comment by glennc** [comment]
Ok, then I think the answer here is to stop doing redirection stuff in the `dotnet cli` and not worry about. Thanks :)
