### ISSUE TITLE
Starting in netcoreapp3.0 float.TryParse parses large numbers as infinity instead of failing to parse

### ISSUE THREAD

**Issue by halter73** [dotnet/coreclr#21473]
```
using System;

namespace FloatRouteConstraintTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var f = 0f;
            var b = float.TryParse("1.79769313486232E+300", out f);

            Console.WriteLine("Hello World! {0} {1}", b, f);
        }
    }
}
```

With the 2.2.0 runtime, the above program outputs:

```
Hello World! False 0
```

With 3.0.0-preview1-26907-05, it outputs:

```
Hello World! True ∞
```

While the new behavior isn't exactly wrong, it is breaking. See https://github.com/aspnet/AspNetCore-Internal/issues/1326#issuecomment-445972904.

**Comment by stephentoub** [comment]
cc: @tannergooding

**Comment by tannergooding** [comment]
The new behavior is fixing some very old bugs in the floating-point parsing code to ensure it is IEEE 754 compliant. We now also match what other IEEE 754 compliant languages/frameworks do when parsing strings as floating-point (such as ES6).

> See aspnet/AspNetCore-Internal#1326 (comment)

I don't have permissions to the internal aspnet repos, could you send the relevant info required to get access? This may help in determining what exactly was broken in ASP.NET

CC. @jkotas as an FYI

**Comment by rynowak** [comment]
We have some tests that verify that this code https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/Constraints/FloatRouteConstraint.cs#L41 fails to parse for a large value (out of range for a float). I think someone read an article that told them to test boundary conditions.

**Comment by tannergooding** [comment]
Closing this as "by-design" as this was fixed as part of the IEEE 754 compliance work.

Feel free to leave any additional comments or re-open if you feel this needs further discussion.

**Comment by stephan-tolksdorf** [comment]
The behaviour change from throwing an `OverflowException` to returning infinity for parsed numbers not representable as a finite floating-point value (after rounding) in .NET Core 3 should be explicitly documented, e.g. here: https://docs.microsoft.com/en-us/dotnet/api/system.double.parse?view=netcore-3.0

**Comment by tannergooding** [comment]
This was already explicitly documented as part of the breaking changes list here: https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0#floating-point-parsing-operations-no-longer-fail-or-throw-an-overflowexception

**Comment by stephan-tolksdorf** [comment]
Thanks for the pointer! Maybe a link to this excellent compatibility change documentation could be added to the API documentation for the affected functions?

**Comment by jkotas** [comment]
The documentation at https://docs.microsoft.com/en-us/dotnet/api/system.double.parse?view=netcore-3.0 says:
```
OverflowException
s represents a number that is less than MinValue or greater than MaxValue.
```
that is clearly wrong now.
