### ISSUE TITLE
EnumProcessModules + GetModuleFileNameExW will crash with hPseudoCurrentProcess

### ISSUE THREAD

**Issue by knuzk** [dotnet/coreclr#21485]
@jkotas @richlander GetProcessModulesFromHandle doesn't call AddReference g_pobjProcess, so the  object will be deleted when the function exits.

Process.cpp line 2688:

   if (hPseudoCurrentProcess == hProcess)
    {
        pobjProcess = g_pobjProcess; // AddReference is missed
    }

**Comment by jkotas** [comment]
Introduced by https://github.com/dotnet/coreclr/commit/dac4a490f66ef501fb8d7b246ed3c21a8bcfa485#diff-35149ba730fd61aba699e375e72c5f3fR2264

cc @mikem8361

**Comment by mikem8361** [comment]
Fix in PR: https://github.com/dotnet/coreclr/pull/21526
