### ISSUE TITLE
Crossgen should emit a warning when compiling assemblies with the partial NGEN flag, and no embedded IBC data

### ISSUE THREAD

**Issue by fadimounir** [dotnet/coreclr#21495]
Currently crossgen generates an output image that has no compiled method, and reports that it successfully compiled the image.

Repro assembly: Microsoft.CodeAnalysis.dll

**Comment by sergiy-k** [comment]
Should this be an error instead of warning to catch misconfigurations early? Just asking...

**Comment by fadimounir** [comment]
This will become an error. Reasons:
1. Most people will usually look over warnings and ignore them
2. Setting PartialNgen without IBC is like not running crossgen at all
3. It would be better to notify users with an eye-catching error, and that is so much easier to diagnose compared to silent "slow" executions because we JIT all methods

Chatted with @brianrob too about this, and we agreed it's good to make it an error instead of a warning.
