### ISSUE TITLE
Interop\StringMarshalling\LPTSTR\LPTSTRTest Marshal_InOut modifies managed string inline

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#21506]
This is another case of a test that modifies the passed in string inline and thus breaks string interning. This test needs to be fixed or removed.

**Comment by janvorli** [comment]
cc: @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@janvorli I can appreciate that this isn't something we want, but .NET Framework actually supported these semantics. In fact this test is identical to one taken from the .NET Framework. I don't quite understand why we have tested for this literally for years and _now_ it is a broken scenario. Is this something we need to update in the marshaller code? Should we update the doc to reflect this _or_ perhaps throw an exception when users attempt to marshal a string as `[Out]`?
