### ISSUE TITLE
Dead calls to R2R allocators are not deleted

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#21530]
```
using System;

public class Test
{
    public static void Main()
    {
        Test test = new Test();
        test.Foo();        
    }

    public void Foo()
    {
        Console.WriteLine("In foo");
    }
}
```

Jit codegen:

```
; Assembly listing for method Test:Main()
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 OutArgs      [V00    ] (  1,  1   )  lclBlk (32) [rsp+0x00]   "OutgoingArgSpace"
;* V01 tmp1         [V01,T00] (  0,  0   )     ref  ->  zero-ref    class-hnd exact "NewObj constructor temp"
;
; Lcl frame size = 40

G_M30453_IG01:
       4883EC28             sub      rsp, 40
       90                   nop

G_M30453_IG02:
       48B968300010FA010000 mov      rcx, 0x1FA10003068
       488B09               mov      rcx, gword ptr [rcx]
       E829FBFFFF           call     System.Console:WriteLine(ref)
       90                   nop

G_M30453_IG03:
       4883C428             add      rsp, 40
       C3                   ret

; Total bytes of code 29, prolog size 5 for method Test:Main()
```

Fragile crossgen codegen:

```
; Assembly listing for method Test:Main()
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 OutArgs      [V00    ] (  1,  1   )  lclBlk (32) [rsp+0x00]   "OutgoingArgSpace"
;* V01 tmp1         [V01,T00] (  0,  0   )     ref  ->  zero-ref    class-hnd exact "NewObj constructor temp"
;
; Lcl frame size = 40

G_M30453_IG01:
       4883EC28             sub      rsp, 40
       90                   nop

G_M30453_IG02:
       488B0D00000000       mov      rcx, qword ptr [(reloc)]
       488B09               mov      rcx, gword ptr [rcx]
       E800000000           call     System.Console:WriteLine(ref)
       90                   nop

G_M30453_IG03:
       4883C428             add      rsp, 40
       C3                   ret

; Total bytes of code 26, prolog size 5 for method Test:Main()
```

R2R codegen:

```
; Assembly listing for method Test:Main()
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 OutArgs      [V00    ] (  1,  1   )  lclBlk (32) [rsp+0x00]   "OutgoingArgSpace"
;* V01 tmp1         [V01,T00] (  0,  0   )     ref  ->  zero-ref    class-hnd exact "NewObj constructor temp"
;
; Lcl frame size = 40

G_M30453_IG01:
       4883EC28             sub      rsp, 40
       90                   nop

G_M30453_IG02:
       FF1500000000         call     [CORINFO_HELP_READYTORUN_NEW]
       488B0D00000000       mov      rcx, qword ptr [(reloc)]
       488B09               mov      rcx, gword ptr [rcx]
       FF1500000000         call     [System.Console:WriteLine(ref)]
       90                   nop

G_M30453_IG03:
       4883C428             add      rsp, 40
       C3                   ret

; Total bytes of code 33, prolog size 5 for method Test:Main()
```

**Comment by erozenfeld** [comment]
The reason is that CORINFO_HELP_READYTORUN_NEW is marked as mayFinalize: https://github.com/dotnet/coreclr/blob/497419bf8f19c649d821295da7e225e55581cce9/src/jit/utils.cpp#L1240

so we consider it side-effecting:

https://github.com/dotnet/coreclr/blob/6b9e1dc685e55430d1471baa799db32bc2807a1c/src/jit/gentree.cpp#L928

and never remove calls to it:

https://github.com/dotnet/coreclr/blob/e1a5d0fca2ccd95ef8c21167343f4fdd017b53a6/src/jit/liveness.cpp#L1753

To be able to remove this allocation call we would need to be able to check  that the class being allocated is in the same versioning bubble and has no finalizers. We could either expose this via a new JitEE interface method or have another helper name for this case (e.g., CORINFO_HELP_READYTORUN_NO_FINALIZER_NEW). For example, in non-R2R case we have CORINFO_HELP_NEWFAST (class may have a finalizer) and CORINFO_HELP_NEWSFAST (class doesn't have a finalizer).

@jkotas @AndyAyersMS Any thoughts on this?

**Comment by AndyAyersMS** [comment]
Having two helper enums here makes sense to me, it fits in with how the jit models helper properties.

The two helper enums can probably map to the same actual helper under the covers, all we really need to do here is convey one extra bit of info back to various parts of the jit.

**Comment by jkotas** [comment]
I think it would be more appropriate to have a method on JIT/EE interface that returns whether the given class is candidate for stack allocation. Inferring this information from JIT helper ID does not sound quite right, even for the existing `CORINFO_HELP_NEWFAST` logic.

`CORINFO_HELP_NEWFAST` helper is used for types without finalizer that may be fine candidates for stack allocation in number of cases (look at implementation `getNewHelperStatic`):
- Object requires 8-byte alignment, or
- Profiler is interested in tracking allocations. This one is particularly interesting: The current implementation will disable stack allocations with tracking memory profiler attached, and thus the profiler will report more allocations than what actually happens without profiler attached...

**Comment by erozenfeld** [comment]
We have a method on JIT/EE interface that returns whether the given class is candidate for stack allocation but this issue is not about stack allocation. We should be able to get rid of the allocation in the issue's example even when stack allocation feature is not enabled.

**Comment by jkotas** [comment]
> That logic has been in the jit for a long time

That does not make it correct. I am trying to point out that this logic is too conservative.

Consider this slightly modified example:

```csharp
using System;

public class Test
{
    long _field;

    public static void Main()
    {
        Test test = new Test();
    }
}
```

On x64, the allocation will be eliminated today. On arm, the allocation won't be eliminated in this example today. This is with JIT - I am not even talking about R2R.

The JIT is trying to guess what the EE side meant, and the guess is not always right, like in my example on ARM. It is anti-pattern in the JIT/EE interface design. We should eliminate the guessing in all cases, not just for the R2R. The options I can think of: 

1. Add `bool allocationHasSideEffect(CORINFO_CLASS_HANDLE handle)` method
2. Or add `bool * pHasSideEffects` flag to the existing `getNewHelper` method
3. Or add  `_HAS_NO_SIDEEFFECTS` flavors for all allocation helpers; not just the R2R one. This does not look very pretty, but it can be done if the other options are too hard to model in the JIT.

Which one of these options you like the most?

**Comment by erozenfeld** [comment]
I'll try to make option 2 work. We can add a gfFlags value for this, i.e., GTF_CALL_M_HELPER_HAS_SIDEEFFECTS (similar to the existing GTF_CALL_M_HELPER_SPECIAL_DCE). For the value of the flag we can re-use one of the values that are currently not used on GT_CALL nodes (e.g., 0x01000000 is currently only used on GT_LCL_VAR and GT_IND).

One more thing that will need to be addressed: currently we don't call getNewHelper for R2R case, CORINFO_HELP_READYTORUN_NEW is hard-coded in the jit. That will need to change so that we can get pHasSideEffects back.

@jkotas @AndyAyersMS sounds reasonable?

**Comment by jkotas** [comment]
Sounds reasonable to me.

**Comment by AndyAyersMS** [comment]
Seems reasonable.

Note there are many other helper properties the jit will deduce based on the helper enum value, so at some point we probably need to revisit how all this is modeled.

The `GTF_CALL_M_FLAG` flag space is entirely disjoint from the regular flag space so just pick the next free value (`0x00400000`) -- don't worry yet about compacting these.
