### ISSUE TITLE
Test failure: JIT_SIMD._CircleInConvex_ro_CircleInConvex_ro_._CircleInConvex_ro_CircleInConvex_ro_cmd

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21546]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress1/373/
**Failed test:**
JIT_SIMD._CircleInConvex_ro_CircleInConvex_ro_._CircleInConvex_ro_CircleInConvex_ro_cmd

**Log:**
```
JIT_SIMD._CircleInConvex_ro_CircleInConvex_ro_._CircleInConvex_ro_CircleInConvex_ro_cmd [FAIL]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_arm_altji---c75e0863\bin\tests\Windows_NT.x86.Checked\Reports\JIT.SIMD\CircleInConvex_ro\CircleInConvex_ro.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_arm_altji---c75e0863\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" CircleInConvex_ro.exe 
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x86_arm_altji---c75e0863\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
  > D:\j\workspace\x86_arm_altji---c75e0863\bin\tests\Windows_NT.x86.Checked\JIT\SIMD\CircleInConvex_ro\CircleInConvex_ro.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_arm_altji---c75e0863\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT.SIMD\JIT.SIMD.XUnitWrapper.cs(949,0): at JIT_SIMD._CircleInConvex_ro_CircleInConvex_ro_._CircleInConvex_ro_CircleInConvex_ro_cmd()
```

**Comment by BruceForstall** [comment]
@CarolEidt @fiigii @tannergooding Another SIMD-related failure

**Comment by tannergooding** [comment]
This also repro's for `TieredCompilation=0, JitStress=1` on regular x86 (no AltJit).

**Comment by tannergooding** [comment]
@CarolEidt, I started looking at this briefly and the second argument to `cw` and `ccw` (all three arguments are Point structs) is getting corrupted across multiple consecutive calls (with the no other changes).

I'll try to post more information later tonight

**Comment by tannergooding** [comment]
Okay, I can get the failure case simplified to something like:
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

using Point = System.Numerics.Vector2;

namespace ClassLibrary
{
    public class test
    {
        [MethodImpl(MethodImplOptions.NoInlining)]
        static bool cw(Point a, Point b, Point c)
        {
            Console.WriteLine($"{a}, {b}, {c}");
            return a.X * (b.Y - c.Y) + b.X * (c.Y - a.Y) + c.X * (a.Y - b.Y) < 0;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void FailureCase(List<Point> p)
        {
            Point p1 = p[0];
            Point p2 = p.Last();

            cw(p1, p[1], p2);
            cw(p1, p[1], p2);
            cw(p1, p[1], p2);
        }

        static Point NextPoint(Random random)
        {
            return new Point(
                (float)random.NextDouble(),
                (float)random.NextDouble()
            );
        }

        static void Main()
        {
            Random random = new Random(13);
            List<Point> p = new List<Point>();

            p.Add(NextPoint(random));
            p.Add(NextPoint(random));
            p.Add(NextPoint(random));

            FailureCase(p);
        }
    }
}
```

This outputs something similar to the following:
```
<0.5177724, 0.6317674>, <4.203895E-45, 1.130228E-35>, <0.07534777, 0.9195563>
<0.5177724, 0.6317674>, <4.227116E-37, 8.022706E-37>, <0.07534777, 0.9195563>
<0.5177724, 0.6317674>, <4.227125E-37, 2.73921E-29>, <0.07534777, 0.9195563>
```
It should be noted that `a` and `c` are always constant. `b` looks to be non-deterministic (although it shouldn't be mutating at all). It also isn't specific to parameter 2, but rather any parameter where the index into the `List<T>` isn't cached first.

**Comment by tannergooding** [comment]
Here are the disassemblies:
[JitDisasm_TC_Off.txt](https://github.com/dotnet/coreclr/files/2683031/JitDisasm_TC_Off.txt)
[JitDisasm_TC_On.txt](https://github.com/dotnet/coreclr/files/2683032/JitDisasm_TC_On.txt)

**Comment by tannergooding** [comment]
CI Job lists 40 new commits that were tested: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress1/373/, one of these is the likely culprit

**Comment by tannergooding** [comment]
Looks like it is also specific to something being inlined from `S.P.Corelib` (possibly the `System.Collections.Generic.List`1[Vector2][System.Numerics.Vector2]:get_Item(int):struct:this` call), as it also only repros with the release build of S.P.Corelib

**Comment by tannergooding** [comment]
@CarolEidt, this looks to be caused by the BLK node change: https://github.com/dotnet/coreclr/pull/21304.

Here is the disasm/dump with d57aca4b2f64942724bbfc0e40db6a125848df47 reverted:
* [JitDisasm_TC_Off-Revert_d57aca4b.txt](https://github.com/dotnet/coreclr/files/2683103/JitDisasm_TC_Off-Revert_d57aca4b.txt)
* [JitDump_TC_Off-Revert_d57aca4b.zip](https://github.com/dotnet/coreclr/files/2683104/JitDump_TC_Off-Revert_d57aca4b.zip)
