### ISSUE TITLE
Incorrect marshalling for a struct with a nested struct larger than 8 bytes on SystemV AMD64 ABI

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/coreclr#21585]
Given the structures and signature below:

```csharp
    public struct SeqStruct
    {
        public int a;
        public bool b;
        public string str;

        public SeqStruct(int _a, bool _b, string _str)
        {
            a = _a;
            b = _b;
            str = String.Concat(_str, "");
        }
    }

    public struct NestedStruct
    {
        public SeqStruct value;
    }

    [DllImport("LayoutClassNative")]
    private static extern bool SimpleNestedLayoutClassByValue(NestedStruct p);
```

And the native side:

```cpp
struct SeqClass
{
    int a; 
    bool b;
    char* str;
};
struct NestedLayoutClass
{
    SeqClass str;
};

extern "C" DLL_EXPORT BOOL STDMETHODCALLTYPE SimpleNestedLayoutClassByValue(NestedLayoutClass v);
```

The SystemV ABI expects the `v` parameter to be enregistered. However, the runtime passes the value of `v` on the stack instead of enregistering it. I've traced the problem to be
https://github.com/dotnet/coreclr/blob/12a8870119b3e8023d68868792b29c28991168b3/src/vm/methodtable.cpp#L2651-L2656

This check is too broad eagerly marks the `NestedStruct` type as not enregisterable.

This bug is blocking one of the tests in #20867.

cc: @janvorli @CarolEidt @RussKeldorph

**Comment by janvorli** [comment]
@jkoritzinsky the reason why the struct is not passed in registers is the fact that it contains managed reference. We explicitly don't try to pass such structs in registers. We have discussed that in the past long time ago when we were enabling the SystemV amd64 ABI and decided to do it that way. IIRC, one of the reasons was that all managed fields are located at the beginning of the struct on the managed side and so they don't match the native side. @jkotas, do you happen to remember some other reasons?

**Comment by jkoritzinsky** [comment]
Even if the managed structure is defined as follows we still don't enregister its native layout:

```csharp
    public struct SeqStruct
    {
        public int a;
        public bool b;
        public IntPtr ptr;
    }

    public struct NestedStruct
    {
        public SeqStruct value;
    }
```

It seems like we don't enregister the native layout of the struct if it's non-blittable even if it doesn't have any managed objects.

**Comment by jkotas** [comment]
> do you happen to remember some other reasons?

I do not remember this particular case being discussed. The discussion for this does not seem to be captured on github to go back to it unfortunately.

Looks like a bug to me. 

I do remember that the SystemV classification of non-blittable types was questionable because of number of Windows-specific concepts have not mapped cleanly. (My suggestion at that time was to have none or very limitted support non-blittable struct marshaling on Unix, but that's not what we ended up doing.)

**Comment by janvorli** [comment]
For some reason, the MethodTable::ClassifyEightBytesWithNativeLayout differs in this from the MethodTable::ClassifyEightBytesWithManagedLayout.  The managed version doesn't have that check at all. So maybe removing it completely culd fix the issue.

**Comment by jkoritzinsky** [comment]
I tested and can say that removing that check does fix the structs I've supplied. I just wasn't sure if removing that check would break anything else.

**Comment by janvorli** [comment]
Well, it seems it could potentially only break cases where fields are larger than the eightbyte. Handling of the others remains the same. So it would be good to figure out and add test cases with various layouts where such large struct fields would be used. 
I would recommend e.g. the following cases:
* struct that contains a 32 bit field followed by a struct with size larger than eightbyte
* deeper level of recursion - like the test you've described in this issue, but adding one or more wrapping layers.
