### ISSUE TITLE
Path.DirectorySeparatorChar and Path.AltDirectorySeparatorChar are the same causing a misbehaviour of Path.GetFileName()

### ISSUE THREAD

**Issue by dvdme** [dotnet/coreclr#21597]
[Path.DirectorySeparatorChar](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.directoryseparatorchar?view=netcore-2.1) and [Path.AltDirectorySeparatorChar](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.altdirectoryseparatorchar?view=netcore-2.1) are both the '/' char in Ubuntu.

I think this is causing that `Path.GetFileName()`, running under Ubuntu, if supplied with an argument that is a Windows path (like `C:\temp\file.txt`) will not return the correct file name.

It is written in the [Path.GetFileName() documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfilename?view=netcore-2.1)  that:

> The separator characters used to determine the start of the file name are DirectorySeparatorChar and AltDirectorySeparatorChar.

If these fields were holding the chars '/' and '\\' then `Path.GetFileName()` would probably get the correct file name, from a windows path, while running in a Ubuntu machine. But since they are the same, the method, running under Ubuntu, returns the full windows path.

Test code:

```csharp
using System;

namespace myApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(System.IO.Path.AltDirectorySeparatorChar);
            Console.WriteLine(System.IO.Path.DirectorySeparatorChar);
            Console.WriteLine(System.IO.Path.GetFileName(@"C:\temp\img.jpg"));
            Console.WriteLine(System.IO.Path.GetFileName("/tmp/img.jpg"));
        }
    }
}
```

Output of `dotnet run`:

```
/
/
C:\temp\img.jpg
img.jpg
```

dotnet version: 2.1.500

**Comment by jkotas** [comment]
cc @JeremyKuhne

**Comment by bartonjs** [comment]
`'\\'` is a legal filename character on Linux, so the Path APIs can't treat it as a directory separator.

```
jbarton@jsb-ubuntu2:~/extract$ ls -al
total 12
drwxrwxr-x  3 jbarton jbarton 4096 Dec 19 09:09 .
drwxr-xr-x 47 jbarton jbarton 4096 Dec 17 08:26 ..
-rw-rw-r--  1 jbarton jbarton    0 Dec 19 09:09 hey\there
drwxrwxr-x  3 jbarton jbarton 4096 Dec 17 08:27 shared
```

**Comment by dvdme** [comment]
> `'\\'` is a legal filename character on Linux, so the Path APIs can't treat it as a directory separator.
> 
> ```
> jbarton@jsb-ubuntu2:~/extract$ ls -al
> total 12
> drwxrwxr-x  3 jbarton jbarton 4096 Dec 19 09:09 .
> drwxr-xr-x 47 jbarton jbarton 4096 Dec 17 08:26 ..
> -rw-rw-r--  1 jbarton jbarton    0 Dec 19 09:09 hey\there
> drwxrwxr-x  3 jbarton jbarton 4096 Dec 17 08:27 shared
> ```

This is most certainly a good point. But the consequence of this is that Path.GetFileName() will work as expected for Windows and Linux paths while running on Windows but not while running on Linux.
 
I can't think on any good way of making this happens so perhaps this could be stated in the documentation.

**Comment by danmosemsft** [comment]
@dvdme I think it should be clarified - perhaps you'd like to offer a PR in https://github.com/dotnet/docs?

**Comment by dvdme** [comment]
@danmosemsft I followed your sugestion and made a PR to https://github.com/dotnet/docs

**Comment by danmosemsft** [comment]
Thanks @dvdme
