### ISSUE TITLE
Compile does not recognize BindingFlags.OptionalParamBinding

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/coreclr#2159]
Compilation using `System.Reflection.BindingFlags.OptionalParamBinding` fails even though it is defined [in source](https://github.com/dotnet/coreclr/blob/2b71c200ef1e55f55dc0e94029597b52b839037a/src/mscorlib/src/System/Reflection/BindingFlags.cs#L58)

```
DNXCore,Version=v5.0 error CS0117: 'BindingFlags' does not contain a definition for 'OptionalParamBinding'
```

I'm not sure if this a Roslyn issue or a CoreCLR issue.

**Comment by MichalStrehovsky** [comment]
`OptionalParamBinding` is not in the [.NET Core version](http://dotnet.github.io/api/System.Reflection.BindingFlags.html) of the enum type.

**Comment by natemcmaster** [comment]
This flag is also in [full .net](https://github.com/Microsoft/referencesource/blob/9d944a62119f6ef061e931a7e955f9bb33f8e95c/mscorlib/system/reflection/bindingflags.cs#L63) (along with several others). I'm not sure why .NET Core excludes these other flags. If they were explicitly excluded from the .NET Core contract for some reason, then feel free to close.

**Comment by weshaggard** [comment]
It is intentionally not included in .Net Core. We are planning to include more reflection APIs but I suspect this enum value may not be included. Can you give more info on the scenario you are using it for?

As for it being in the source please keep in mind that this is shared with the full framework so it has a lot more then what ends up in the .Net Core version of mscorlib. We have some tools that strip out a lot of the code that is not supported on .Net Core.

**Comment by natemcmaster** [comment]
@weshaggard `Activator.CreateInstance` for a constructor with optional params. I worked around this by finding and invoking `ConstructorInfo` instead.

**Comment by natemcmaster** [comment]
This was added to public API surface in .NET Standard 2.0.
