### ISSUE TITLE
Assertion failed 'compiler->compSupports(InstructionSet_SSE)'

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21596]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitnox86hwintrinsic/311/#showFailuresLink
**Failed tests:**
JIT_HardwareIntrinsics._General_Vector64_1_Vector64_1_r_Vector64_1_r_._General_Vector64_1_Vector64_1_r_Vector64_1_r_cmd
JIT_HardwareIntrinsics._General_Vector128_1_Vector128_1_r_Vector128_1_r_._General_Vector128_1_Vector128_1_r_Vector128_1_r_cmd
JIT_HardwareIntrinsics._General_Vector128_1_Vector128_1_ro_Vector128_1_ro_._General_Vector128_1_Vector128_1_ro_Vector128_1_ro_cmd
JIT_HardwareIntrinsics._General_Vector64_1_Vector64_1_ro_Vector64_1_ro_._General_Vector64_1_Vector64_1_ro_Vector64_1_ro_cmd
JIT_HardwareIntrinsics._General_Vector128_Vector128_r_Vector128_r_._General_Vector128_Vector128_r_Vector128_r_cmd
JIT_HardwareIntrinsics._General_Vector128_Vector128_ro_Vector128_ro_._General_Vector128_Vector128_ro_Vector128_ro_cmd
**One of failed log:**
```
JIT_HardwareIntrinsics._General_Vector128_1_Vector128_1_r_Vector128_1_r_._General_Vector128_1_Vector128_1_r_Vector128_1_r_cmd [FAIL]
        
        Assert failure(PID 4504 [0x00001198], Thread: 9420 [0x24cc]): Assertion failed 'compiler->compSupports(InstructionSet_SSE)' in 'System.Runtime.Intrinsics.Vector128`1[Byte][System.Byte]:get_Zero():struct' (IL size 15)
        
            File: d:\j\workspace\x86_arm_altji---427ff4c4\src\jit\hwintrinsiccodegenxarch.cpp Line: 1260
            Image: D:\j\workspace\x86_arm_altji---427ff4c4\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
        
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_arm_altji---427ff4c4\bin\tests\Windows_NT.x86.Checked\Reports\JIT.HardwareIntrinsics\General\Vector128_1\Vector128_1_r\Vector128_1_r.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_arm_altji---427ff4c4\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" Vector128_1_r.exe 
        Beginning test case Zero.Byte at 12/18/2018 7:45:18 AM
        Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
        
        Beginning scenario: RunBasicScenario
        Expected: 100
        Actual: -1073740286
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x86_arm_altji---427ff4c4\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
  > D:\j\workspace\x86_arm_altji---427ff4c4\bin\tests\Windows_NT.x86.Checked\JIT\HardwareIntrinsics\General\Vector128_1\Vector128_1_r\Vector128_1_r.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_arm_altji---427ff4c4\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(669,0): at JIT_HardwareIntrinsics._General_Vector128_1_Vector128_1_r_Vector128_1_r_._General_Vector128_1_Vector128_1_r_Vector128_1_r_cmd()
```

**Comment by BruceForstall** [comment]
@fiigii @tannergooding @CarolEidt

**Comment by tannergooding** [comment]
@CarolEidt, This looks related to the `gtGetSIMDZero` handling added here: https://github.com/dotnet/coreclr/pull/21304/files#diff-26597eae27417b7113176d9fcb5e1f10R16402. We are validating `compSupports(InstructionSet_SSE)` in the other place this is called: https://github.com/dotnet/coreclr/blob/master/src/jit/importer.cpp#L4283

The assert exists because users are able to disable the HWIntrinsic codegen support via `COMPlus_EnableHWIntrinsic=0` (in which case we shouldn't be hitting any code in `hwintrinsiccodegenxarch.cpp` and we should end up emitting the software fallback code instead).

**Comment by tannergooding** [comment]
I'll put up a PR shortly, the fix should likely just be checking `compSupports(InstructionSet_SSE)` for `TYP_SIMD16` and `compSupports(InstructionSet_AVX)` for `TYP_SIMD32` and returning `nullptr` if either of those return false.

**Comment by tannergooding** [comment]
PR is here: https://github.com/dotnet/coreclr/pull/21605
