### ISSUE TITLE
StackOverflowException when accessing Sse42.X64 class

### ISSUE THREAD

**Issue by differentrain** [dotnet/coreclr#21616]
Sample code:

```
Console.WriteLine($"Sse42.IsSupported = {Sse42.IsSupported}");
Console.WriteLine($"Sse42.X64.IsSupported = {Sse42.X64.IsSupported}");
```
Output:

>  Sse42.IsSupported = True
> Process is terminating due to StackOverflowException.

.NET Core SDK version:
> 3.0.100-preview-009812

 Platforms:
> Windows, Linux, Os

#https://github.com/dotnet/corert/issues/6704

**Comment by differentrain** [comment]
#

**Comment by differentrain** [comment]
@fiigii  If "the latest" means `3.0.100-preview-009812 SDK` and `Microsoft.NETCore.App 3.0.0-preview-27122-01 runtime` , yes.

> `dotnet --version` :
> 3.0.100-preview-009812

> `dotnet run -f netcoreapp3.0` :
> Sse42.IsSupported = True
> Process is terminating due to StackOverflowException.

**Comment by fiigii** [comment]
No, I meant the daily build https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries

```
> dotnet --version
3.0.100-preview-009844
```

I tried, that works.

**Comment by differentrain** [comment]
> No, I meant the daily build https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries
> 
> ```
> > dotnet --version
> 3.0.100-preview-009844
> ```
> I tried, that works.
I see. thank your for your reply.
