### ISSUE TITLE
Rename AsyncStateMachineBox

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#21612]
Mostly a preference change for debugging/profiling/examining dumps.

`AsyncStateMachineBox` is called `AsyncTaskMethodBuilder+AsyncStateMachineBox<...>` in profiles, dumps etc

![image](https://user-images.githubusercontent.com/1142958/50264767-fa324900-0413-11e9-8ae7-6c427adf74d6.png)

Would an acceptable change be to rename this to `StateMachine` so it becomes `AsyncTaskMethodBuilder+StateMachine<...>`?

/cc @stephentoub @davidfowl

**Comment by benaadams** [comment]
Would look more like this:

![image](https://user-images.githubusercontent.com/1142958/50264999-534eac80-0415-11e9-87db-36e9b8cb3ffd.png)

**Comment by benaadams** [comment]
`StateMachineBox` would work also; if differentiating that its different heap type (and that there is a non-boxed version)

**Comment by stephentoub** [comment]
Without the Box suffix I think it's strange, as it's not actually the state machine from the compiler, but rather has the state machine as one field. So the only difference at that point is whether it has an Async prefix. And while doing the prefix may have been a better name choice initially, I don't think that's a worthwhile change now, e.g. DumpAsync will now have to compare more possible names (or at least do more complicated comparisons), devs in a debugger will have to know about a difference between 2.1/2.2 and 3.0, etc. Just doesn't seem worth it to me.

**Comment by davidfowl** [comment]
I agree, I'm not sure it adds much value now since we're essentially just removing the async prefix...

**Comment by benaadams** [comment]
k
