### ISSUE TITLE
[x86/x64] JIT vector tests failing due to bad codegen

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#21625]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_minopts/696/

**Failed tests:**
JIT_HardwareIntrinsics._General_Vector256_Vector256_ro_Vector256_ro_._General_Vector256_Vector256_ro_Vector256_ro_cmd
JIT_HardwareIntrinsics._General_Vector128_Vector128_r_Vector128_r_._General_Vector128_Vector128_r_Vector128_r_cmd
JIT_HardwareIntrinsics._General_Vector256_Vector256_r_Vector256_r_._General_Vector256_Vector256_r_Vector256_r_cmd
JIT_HardwareIntrinsics._General_Vector128_Vector128_ro_Vector128_ro_._General_Vector128_Vector128_ro_Vector128_ro_cmd

**Failed log:**
```
JIT_HardwareIntrinsics._General_Vector256_Vector256_ro_Vector256_ro_._General_Vector256_Vector256_ro_Vector256_ro_cmd [FAIL]
Return code:      1
Raw output file:      D:\j\workspace\x86_checked_w---a981555f\bin\tests\Windows_NT.x86.Checked\Reports\JIT.HardwareIntrinsics\General\Vector256\Vector256_ro\Vector256_ro.output.txt
  Raw output:
  BEGIN EXECUTION
... ...
To run the test:
  > set CORE_ROOT=D:\j\workspace\x86_checked_w---a981555f\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
  > D:\j\workspace\x86_checked_w---a981555f\bin\tests\Windows_NT.x86.Checked\JIT\HardwareIntrinsics\General\Vector256\Vector256_ro\Vector256_ro.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_checked_w---a981555f\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(739,0): at JIT_HardwareIntrinsics._General_Vector256_Vector256_ro_Vector256_ro_._General_Vector256_Vector256_ro_Vector256_ro_cmd()
```

**Comment by tannergooding** [comment]
Failure is with `CreateScalar` for `Int16`, `UInt16`, and `SByte`. The upper 2/3-bytes aren't being zeroed.

**Comment by tannergooding** [comment]
The current implementation is:
```csharp
public static unsafe Vector128<short> CreateScalar(short value)
{
    if (Sse2.IsSupported)
    {
        return Sse2.ConvertScalarToVector128UInt32((ushort)(value)).AsInt16();
    }

    return SoftwareFallback(value);

    Vector128<short> SoftwareFallback(short x)
    {
        var result = Vector128<short>.Zero;
        Unsafe.WriteUnaligned(ref Unsafe.As<Vector128<short>, byte>(ref result), value);
        return result;
    }
}
```

Looks like the `SoftwareFallback` isn't using the new variable `x` passed in and so the compiler creates a capture context:
```csharp
[CompilerGenerated, StructLayout(LayoutKind.Auto)]
private struct CapturedContext
{
    public short value;
}

public static unsafe Vector128<short> CreateScalar(short value)
{
    CapturedContext context = default;
    context.value = value;

    if (Sse2.IsSupported)
    {
        return Sse2.ConvertScalarToVector128UInt32((ushort)(context.value)).AsInt16();
    }

    return SoftwareFallback(context.value, ref context);
}

internal static Vector128<short> SoftwareFallback(short x, ref CapturedContext context)
{
    var result = Vector128<short>.Zero;
    Unsafe.WriteUnaligned(ref Unsafe.As<Vector128<short>, byte>(ref result), context.value);
    return result;
}
```

**Comment by tannergooding** [comment]
The partial fix here is to ensure that the `SoftwareFallback` methods aren't capturing any variables.

However, this also needs further investigation to determine why the `zero-extend on load` semantics aren't happening when we access the variable from the captured context.

**Comment by tannergooding** [comment]
For the larger issue, the tree we have is the following:
```
               [000034] ------------              *  STMT      void  (IL 0x00F...0x01A)
               [000030] ------------              |  /--*  HWIntrinsic simd16 uint ConvertScalarToVector128UInt32
               [000029] ------------              |  |  \--*  FIELD     ushort value
               [000028] L-----------              |  |     \--*  ADDR      byref 
               [000027] ------------              |  |        \--*  LCL_VAR   struct V02 loc0         
               [000033] -A----------              \--*  ASG       simd16 (copy)
               [000031] D-----------                 \--*  LCL_VAR   simd16 V03 loc1  
```

It looks like we need to update `ContainCheckHWIntrinsic` to check the tree-type against the expected type and only mark the operand as containable if the types match.

**Comment by BruceForstall** [comment]
The job referenced above is a minopts job. This presumably is what is causing the x86 debug job to fail: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/x86_debug_windows_nt/5898

**Comment by fadimounir** [comment]
This is blocking #21497 from being merged since it will cause CI jobs to fail

**Comment by fadimounir** [comment]
This is not just affecting the x86 architecture. This also fails on x64 (see: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_centos7.1_innerloop_tst_prtest/9111/)

**Comment by fadimounir** [comment]
@tannergooding I analyzed the codegen on x86. My analysis notes are in #21773 in case it helps

**Comment by brianrob** [comment]
@tannergooding, do you have an update on this?  As @fadimounir pointed out above, #21497 is blocked by this fix, and we do want to get it merged soon.

**Comment by tannergooding** [comment]
Sorry for the delay, I just got back from vacation today. The fix is here: https://github.com/dotnet/coreclr/pull/21641 and should just be waiting for CI to finish.

**Comment by brianrob** [comment]
Excellent.  Thanks @tannergooding.
