### ISSUE TITLE
BadImageFormat Exception when trying to use TextControl in .Net Core 3.0 preview 1

### ISSUE THREAD

**Issue by Lohnegrim** [dotnet/coreclr#21680]
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
  Version: 3.0.0-preview-27122-01
  Commit:  00c5c8bc40

Maybe simmilar to/relevant https://github.com/dotnet/coreclr/issues/11298 or https://github.com/dotnet/coreclr/issues/18447

Hi,
I tried to Convert and run a project to .Net Core 3.0 Preview 1 and run in a Problem with an External Component. "Tx TextControl".

I reduced the relevant Code to the minimum and Created a repro:
[textcontrol.txtools.zip](https://github.com/dotnet/coreclr/files/2710433/textcontrol.txtools.zip)

If it does not work here the Steps for the Repo:
1. Trial from: https://www.textcontrol.com/products/windows-forms/tx-text-control-dotnet/downloads.
2. Add a reference to the txtools from the package.
3. And this Code to a new .Core 3.0 console project:
                TXTextControl.txtools.Initialize();

I tried multiple Compinations, 32 + 64 bit version for the txtool.dll, and 32, 64, AnyCpu of the .net core project, but I always get BadImageFormat.

**Comment by jeffschwMSFT** [comment]
The underlying issue is that txtools.dll is an IJW assembly built against .NET Framework.  We are adding IJW support for .NET Core 3.0, but the component vendor will need to recompile this assembly to targert .NET Core.

cc @jkoritzinsky

**Comment by jkoritzinsky** [comment]
We're tracking IJW support in #18013, so I'm going to close this in favor of #18013.
