### ISSUE TITLE
Build failed in x86_arm_altjit_checked_windows_nt_corefx_jitstress1 with exit code 1

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21685]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstress1/391/
**Failed log:**
```
Build failed.
[D:\j\workspace\x86_arm_altji---bee8c131\tests\scripts\run-corefx-tests.py]: Error: exit code 1

D:\j\workspace\x86_arm_altji---bee8c131>exit 1
```

**Comment by BruceForstall** [comment]
Well, I'm not sure why, but a subsequent job finally succeeded (https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstress1/398/), so I'm going to close this apparent flaky build issue.
