### ISSUE TITLE
StackOverflowException in Popcnt with self-contained apps

### ISSUE THREAD

**Issue by sebastienros** [dotnet/coreclr#21690]
Using the latest CLR version, when publishing a self-contained "hello world" app in ASP.NET we get an SO on the very first request. It repros on both win and lin. 

Debugging it shows this trace:

```
000000c93163c210 00007ff99787c5af (MethodDesc 00007ff9978f35b0 + 0xf System.Runtime.Intrinsics.X86.Popcnt+X64.get_IsSupported()), calling (MethodDesc 00007ff9978f35b0 + 0 System.Runtime.Intrinsics.X86.Popcnt+X64.get_IsSupported())
000000c93163c240 00007ff99787c5af (MethodDesc 00007ff9978f35b0 + 0xf System.Runtime.Intrinsics.X86.Popcnt+X64.get_IsSupported()), calling (MethodDesc 00007ff9978f35b0 + 0 System.Runtime.Intrinsics.X86.Popcnt+X64.get_IsSupported())
...
```

Probably this: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Runtime/Intrinsics/X86/Popcnt.cs#L23

/cc @tannergooding @fiigii

**Comment by fiigii** [comment]
This is a new feature in CoreCLR. Could you please try the daily build?

**Comment by sebastienros** [comment]
Just tried with these versions, (latest runtime from myget 3 hours ago) and it still happens

```
SDK:                         3.0.100-preview-009812
Runtime:                     3.0.0-preview-27227-2
ASP.NET Core:                3.0.0-preview-18626-0224
```

**Comment by sebastienros** [comment]
I can provide the full self-contained app I am using if you need it.

**Comment by benaadams** [comment]
Out of curiosity if you switch off TieredCompilation and ReadyToRun does it work?

**Comment by fiigii** [comment]
I tried that SDK 3.0.100-preview-009844 works.

**Comment by sebastienros** [comment]
You might be right, looking at the versions in the self-contained app itself, it is using a runtime from Nov 20th. However the ASP.NET one is correct. I will investigate.

**Comment by benaadams** [comment]
I had a problem that build/publish wasn't updating overwriting existing runtime files from a previous build/publish even though I'd changed version, so I had to delete obj/bin/.vs to get it to output up to date runtime to get emitted

**Comment by sebastienros** [comment]
I am closing it because it doesn't seem to be a bug in the clr, but an issue with the SDK and me not knowing how to force a specific runtime in 3.0 for self-contained apps.
