### ISSUE TITLE
A question about Compiler::optHoistCandidate logic

### ISSUE THREAD

**Issue by alexandrnikitin** [dotnet/coreclr#2173]
The `Compiler::optHoistCandidate` method has the following piece of code:

```
// The outer loop also must be suitable for hoisting...
if ((optLoopTable[lnum].lpFlags & LPFLG_HOISTABLE) == 0)
    return;
```

It cant be found here https://github.com/dotnet/coreclr/blob/release/1.0.0-rc1/src/jit/optimizer.cpp#L6029
Where the comment states that we check the outer loop. 
While we pass the current loop in callers, i.e. in `Compiler::optHoistLoopExprsForBlock`  https://github.com/dotnet/coreclr/blob/release/1.0.0-rc1/src/jit/optimizer.cpp#L5762

The question: Is the comment wrong?

**Comment by mikedn** [comment]
IMO both the comment and the `if` are odd. How could a non-hoistable loop contain hoist candidates to begin with?

**Comment by alexandrnikitin** [comment]
Do you have tests for that code?

**Comment by mikedn** [comment]
> Do you have tests for that code?

Me? To avoid confusions, I do not work for Microsoft.

Anyway, I'm not sure what kind of tests do you expect to see. If you look a bit more closely at the code you'll see that the `if` is actually useless.

**Comment by alexandrnikitin** [comment]
>If you look a bit more closely at the code you'll see that the if is actually useless.

Agreed. But I can understand the `if` as a double check. An exression tree can be hoistable, but a loop isn't, those flags can be set from everywhere.

**Comment by mikedn** [comment]
>  But I can understand the  if  as a double check

Such double checks are normally done with asserts, like in `optPerformHoistExpr`.

> those flags can be set from everywhere

The `LPFLG_HOISTABLE` flag? You can't really set it from anywhere else but `optHoistThisLoop`. Doing otherwise would require duplicating a bunch of checks and the whole thing is poorly factored as is, the last thing it needs is more duplication.

**Comment by alexandrnikitin** [comment]
Yes, I understand all that. I just try to put myself in that developer's place. 
Actually, I can live with an additional useless check, but not with a misleading comment.

**Comment by pgavlin** [comment]
@alexandrnikitin it looks like this is now tracked by #2174, so I am closing this issue. Please feel free to reopen it if I've closed it in error.
