### ISSUE TITLE
Where is Type.Assembly?

### ISSUE THREAD

**Issue by SharpNoiZy** [dotnet/coreclr#2176]
Hi,

I search for Type.Assembly in .NET Platform 5.4.
Is it somewhere available?

Kind regards

**Comment by weshaggard** [comment]
Assembly property is on TypeInfo so you need to call type.GetTypeInfo().Assembly

**Comment by vors** [comment]
Note: `GetTypeInfo()` is an extension method that lives in `System.Reflection`.
