### ISSUE TITLE
Alpine Linux, ASP.NET Core 2.2: Localization not working

### ISSUE THREAD

**Issue by rahuldj** [dotnet/coreclr#21772]
I have an ASP.NET Core 2.2 application that uses RequestLocalizationOptions to set supported cultures and allows switching between languages by setting the "CookieRequestCultureProvider.DefaultCookieName" cookie value through a POST call that does:

```
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return Redirect(returnUrl);
        }
```

The language switcher behaves correctly on my local windows machine (as well as in docker with image: microsoft/dotnet:2.2.0-aspnetcore-runtime)

However, if I switch to microsoft/dotnet:2.2.0-aspnetcore-runtime-alpine, the localization no longer works.

I'm not sure how to go about troubleshooting this, however, _something_ in alpine image handles localization differently than the non-alpine based microsoft/dotnet:2.2.0-aspnetcore image (or my local.)

**Comment by am11** [comment]
This is because official Alpine docker has invariant globalization enabled for Alpine: https://github.com/dotnet/dotnet-docker/blob/b402e0/2.2/runtime-deps/alpine3.8/amd64/Dockerfile#L22-L23.
To opt-out of invariant mode, try adding the following to your Dockerfile (or without `RUN` in shell script):

```dockerfile
RUN apk add icu-libs; unset DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
```

**Comment by am11** [comment]
This is because official Alpine docker has invariant globalization enabled: https://github.com/dotnet/dotnet-docker/blob/b402e0/2.2/runtime-deps/alpine3.8/amd64/Dockerfile#L22-L23.
To opt-out of invariant mode, try adding the following to your Dockerfile (or without `RUN` in shell script):

```dockerfile
RUN apk add icu-libs; unset DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
```

**Comment by rahuldj** [comment]
Thank you @am11!
 I guess I missed the announcement. Followed your instructions to fix the issue.
