### ISSUE TITLE
Bad x86/x64 codegen for Vector APIs

### ISSUE THREAD

**Issue by fadimounir** [dotnet/coreclr#21773]
Note: I manually debugged the x86 version, but i think the bug applies to x64 as well.

### To repro:

1. Replace the System.Private.CoreLib.dll file from your %core_root% directory with the IL version to force the jitting of the code
2. Build and run test JIT\HardwareIntrinsics\General\Vector256\Vector256_r\Vector256_r.csproj

### Snippet stdout from failing portion:
_Beginning scenario: RunBasicScenario
Vector256.CreateScalar(Int16): RunBasicScenario failed:
   value: 3387
  result: (3387, 247, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

Beginning scenario: RunReflectionScenario
Vector256.CreateScalar(Int16): RunReflectionScenario failed:
   value: 11422
  result: (11422, 247, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)_

### Analysis:
I believe the issue is in System.Runtime.Intrinsics.Vector128.CreateScalar(Int16), where we write a WORD value to a memory location, however we read it as a DWORD value when loading it into xmm0 (see highlighted below). We probably also have similar behaviors with data types like uint16, byte, char,... and on x64 we _may_ have the same bug with int and uint.
The bug is **non-deterministic** and really depends on what garbage values exist on the stack. The JIT test mentioned in this repro however is written in a way such that it deterministically fails at the same location with the same values, so it's easier to debug: just put a breakpoint at the beginning of function CreateScalarInt16() (in CreateScalar.Int16.cs) and debug the call to RunBasicScenario.

push    ebp
mov     ebp,esp
sub     esp,64h
vzeroupper
mov     dword ptr [ebp-4],ecx
mov     dword ptr [ebp-8],edx
cmp     dword ptr ds:[5D6338h],0
je      System_Private_CoreLib!System.Runtime.Intrinsics.Vector128.CreateScalar(Int16)+0x1d (07af6b75)
call    CoreCLR!JIT_DbgIsJustMyCode (640ff280)
mov     ecx,dword ptr [ebp-8]
movsx   ecx,cx
**mov     word ptr [ebp-0Ch],cx      ** -> word write**
nop
mov     dword ptr [ebp-34h],1
mov     ecx,dword ptr [ebp-34h]
movzx   ecx,cl
mov     dword ptr [ebp-10h],ecx
cmp     dword ptr [ebp-10h],0
je      System_Private_CoreLib!System.Runtime.Intrinsics.Vector128.CreateScalar(Int16)+0x6a (07af6bc2)
nop
**vmovd   xmm0,dword ptr [ebp-0Ch]       ** -> dword read**
vmovupd xmmword ptr [ebp-54h],xmm0
vmovupd xmm0,xmmword ptr [ebp-54h]
vmovupd xmmword ptr [ebp-20h],xmm0
vmovupd xmm0,xmmword ptr [ebp-20h]
vmovupd xmmword ptr [ebp-64h],xmm0
vmovupd xmm0,xmmword ptr [ebp-64h]
vmovupd xmmword ptr [ebp-30h],xmm0
nop
jmp     System_Private_CoreLib!System.Runtime.Intrinsics.Vector128.CreateScalar(Int16)+0x88 (07af6be0)
lea     ecx,[ebp-0Ch]
push    ecx
lea     ecx,[ebp-44h]
movsx   edx,word ptr [ebp-0Ch]
call    dword ptr ds:[7A4C864h]
vmovupd xmm0,xmmword ptr [ebp-44h]
vmovupd xmmword ptr [ebp-30h],xmm0
nop
jmp     System_Private_CoreLib!System.Runtime.Intrinsics.Vector128.CreateScalar(Int16)+0x88 (07af6be0)
mov     eax,dword ptr [ebp-4]
vmovupd xmm0,xmmword ptr [ebp-30h]
vmovupd xmmword ptr [eax],xmm0
mov     esp,ebp
pop     ebp
ret

**Comment by fadimounir** [comment]
cc @jkotas

**Comment by fadimounir** [comment]
This is blocking me from being able to merge #21497 since SSE instructions are not supported for R2R images, and the jitted methods in S.P.CoreLib are failing 4 JIT tests.

**Comment by fadimounir** [comment]
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Dup of https://github.com/dotnet/coreclr/issues/21625?

@tannergooding @CarolEidt @fiigii

**Comment by fiigii** [comment]
> Dup of #21625?

Yes, I think so.

**Comment by fadimounir** [comment]
Ok I can close this since it's a dup.
