### ISSUE TITLE
CustomAttributeNamedArgument

### ISSUE THREAD

**Issue by seesharper** [dotnet/coreclr#2181]
The CustomAttributeNamedArgument class is supposed to have a MemberInfo property, but when trying to compile for the CoreCLR (I am using the latest bits) it complains and says the property is missing. The same goes for the CustomAttributeData class that is supposed to have a Constructor property. Whren I look at the source https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Reflection/CustomAttribute.cs/#L584 it seems to be implemented but that might not represents the latest packages on NuGet? Or is it something else that I am missing here?

**Comment by stephentoub** [comment]
They're not exposed in the System.Reflection contract.

cc: @weshaggard, @terrajobst

**Comment by seesharper** [comment]
Which is considered a bug then?

**Comment by stephentoub** [comment]
It's by design, meaning it was left out on purpose. The question is whether it should be added back, whether there was a really good reason for it to be omitted, etc.

**Comment by seesharper** [comment]
In that case it would be rather difficult to add custom attributes to new
types.

**Comment by joshfree** [comment]
@pallavit could you take a look please?

**Comment by pallavit** [comment]
@seesharper We are going to take a deeper look at the entire reflection surface area and attempt to add most of the existing functionality.

**Comment by seesharper** [comment]
Hi. Since the CustomAttributeData class still provides the AttributeType property, it is still possible to get to the member through the member name. The constructor can be resolved by matching the constructor(s) from the AttributeType against the ConstructorArguments property that is also still available from the CustomAttributeData class. It is not as convenient as before, but still doable.
Keep up the good work. The CoreCLR rocks!! :)
