### ISSUE TITLE
Add MinEventTime and MaxEventTime to the EventBlock in the NetPerf File Format

### ISSUE THREAD

**Issue by mjsabby** [dotnet/coreclr#21827]
The `EventBlock` object that is part of the NetPerf file format as[ described here](https://github.com/Microsoft/perfview/blob/e45ac230931864436cbcf37bb0d26b918c075e10/src/TraceEvent/EventPipe/EventPipeFormat.md#next-objects--the-eventblock-object), can include two additional fields to allow filtering of the data in the file.

If we add `MinEventTime` and `MaxEventTime` then a reader can iterate through the blocks and ignore the events they don't care about. This is very useful in a continuous production profiling scenario where the event data is being written to a single file, but you only care about a subset of the data for your transaction of interest be that a database query or http request and you can quickly get to it by skipping the data.

**Comment by mjsabby** [comment]
@vancem @noahfalk

**Comment by mjsabby** [comment]
Now that @jorive has done multiple event sessions. This becomes a useful vehicle for supporting production profiling scenarios where one session collects jitted code info, module loads, etc for the process lifetime. And another session has data in "chunks" of X minutes to help production investigations.

I don't think this is a major change and it's best if we do this in 3.0, given 3.1 will be LTS and a minor change from 3.0. I'm happy to contribute.

**Comment by noahfalk** [comment]
Complete in #24853 (coreclr) and https://github.com/microsoft/perfview/pull/948 in TraceEvent. The trace event parser isn't using this data for any purpose right now, but it is in the file.
