### ISSUE TITLE
MSBuild Error

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#21845]
failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x86_min_opt_ryujit_smoketest/248/

failed log:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(4176,5): error MSB3027: Could not copy "D:\j\w\perf_perflab_---31b4e899\bin\int\Managed\GC\Regressions\v2.0-beta1\289745\302560\302560.exe" to "D:\j\w\perf_perflab_---31b4e899\bin\tests\Windows_NT.x86.Release\GC\Regressions\v2.0-beta1\289745\302560\302560.exe". Exceeded retry count of 10. Failed.  [D:\j\w\perf_perflab_---31b4e899\tests\src\GC\Regressions\v2.0-beta1\289745\302560.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(4176,5): error MSB3021: Unable to copy file "D:\j\w\perf_perflab_---31b4e899\bin\int\Managed\GC\Regressions\v2.0-beta1\289745\302560\302560.exe" to "D:\j\w\perf_perflab_---31b4e899\bin\tests\Windows_NT.x86.Release\GC\Regressions\v2.0-beta1\289745\302560\302560.exe". Operation did not complete successfully because the file contains a virus or potentially unwanted software. [D:\j\w\perf_perflab_---31b4e899\tests\src\GC\Regressions\v2.0-beta1\289745\302560.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(4176,5): error MSB3021:  [D:\j\w\perf_perflab_---31b4e899\tests\src\GC\Regressions\v2.0-beta1\289745\302560.csproj]
D:\j\w\perf_perflab_---31b4e899\tests\dir.traversal.targets(25,5): error : (No message specified) [D:\j\w\perf_perflab_---31b4e899\tests\src\dirs.proj]
D:\j\w\perf_perflab_---31b4e899\tests\dir.traversal.targets(25,5): error : (No message specified) [D:\j\w\perf_perflab_---31b4e899\tests\build.proj]

**Comment by filipnavara** [comment]
There was a bunch of those "Operation did not complete successfully because the file contains a virus or potentially unwanted software" errors tracked in other issues. The response from the core-eng team was that the machines should be configured to exclude the build output directory from antivirus checks. /cc @MattGal (cannot CC the team as it's private, sorry)

**Comment by MattGal** [comment]
Fix is tracked by https://github.com/dotnet/core-eng/issues/4555 which is being actively worked on.
