### ISSUE TITLE
measurement.json does not exist. There is no data to be uploaded

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#21846]
failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_scenarios_Windows_NT_x86_full_opt_ryujit/3520/

failed log:
[tests\scripts\run-xunit-perf.py]: cmd.exe /c START "CORECLR_PERF_RUN" /B /WAIT /HIGH C:\j\w\perf_scenario---a17ae768\bin\sandbox\corerun.exe C:\j\w\perf_scenario---a17ae768\bin\sandbox\JitBench.exe --perf:outputdir C:\j\w\perf_scenario---a17ae768\bin\sandbox_logs\Scenarios\Off\JitBench --perf:runid Perf-Off --target-architecture x86 --perf:collect stopwatch
Traceback (most recent call last):
  File "tests\scripts\run-xunit-perf.py", line 529, in <module>
    sys.exit(main(Args))
  File "tests\scripts\run-xunit-perf.py", line 520, in main
    upload_to_benchview(python, coreclrRepo, benchviewPath, uploadToBenchview, benchviewGroup, runType, configuration, operatingSystem, etwCollection, optLevel, jitName, pgoOptimized, arch)
  File "tests\scripts\run-xunit-perf.py", line 285, in upload_to_benchview
    raise Exception('%s does not exist. There is no data to be uploaded.' % jsonFile)
Exception: C:\j\w\perf_scenario---a17ae768\bin\sandbox\measurement.json does not exist. There is no data to be uploaded.

**Comment by jorive** [comment]
This is the performance harness `C:\j\w\perf_scenario---a17ae768\bin\sandbox\corerun.exe C:\j\w\perf_scenario---a17ae768\bin\sandbox\JitBench.exe` failed, did not print what the failure was, and did not return non-zero exit code. Finally, the python script attempted to read a file that did not exist.

Suggestions:
1. Scenario harness should communicate error, and exit non-zero when failures
2. (Optionally) Python script should check if file exist before attempting to consume it and print appropriate error.

**Comment by adiaaida** [comment]
We do archive the logs, they're just in the build artifacts:

https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_scenarios_Windows_NT_x86_full_opt_ryujit/3520/artifact/bin/sandbox_logs/Scenarios/Off/JitBench/Perf-Off-JitBench.log

https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_scenarios_Windows_NT_x86_full_opt_ryujit/3520/artifact/bin/sandbox_logs/Scenarios/Off/JitBench/JitBench_log.txt

**Comment by adiaaida** [comment]
I've seen this failure before. It is because of changes to coreclr to AppDomain. We need to rev up the version of dotnet we are using so that it is more recent.

**Comment by jorive** [comment]
I still believe the harness should return non-zero exit code, otherwise we attempt to run the next step of automation and fail giving the wrong impression.

**Comment by RussKeldorph** [comment]
These jobs are gone and to be replaced via #18756
