### ISSUE TITLE
Add configuration knob to skip tier 0 for methods that don't have prejitted code

### ISSUE THREAD

**Issue by mjsabby** [dotnet/coreclr#21856]
It would be really useful to have an option where the JIT could generate optimized code for Tier0.

There maybe scenarios where perceived/useful startup time isn't negatively impacted by the JIT spending time to optimize Tier0. Such applications would have other startup bottlenecks, like loading configuration data from the disk or network.

There already exists such a setting `TieredCompilation_Test_OptimizeTier0`, but it is marked as unsupported. So the change here may just be exposing that as a supported setting.

**Comment by mjsabby** [comment]
cc @kouvel

**Comment by mjsabby** [comment]
I was going to add to the issue that a reasonable thing to think would be what does Tier1 do now?

I think it would be:

* R2R images still benefit from tiered compilation (although you could argue that could be a different setting, i.e. only do Tiered Compilation for R2R images)
* Certain low-level things like indirections that are there due to method JIT order could be smoothed out, like you said.
* Any future speculative optimizations

**Comment by kouvel** [comment]
The current config option `OptimizeTier0` would basically generate tier 1 code for tier 0, and then tier-up the method later with a rejit to tier 1 code again. I think a more useful option would be to skip tier 0 and just generate tier 1 code once for methods that don't have prejitted code, and for methods that have prejitted code, to tier up normally as currently done. For scenarios where JIT time is not important during startup, at the moment there would not be much benefit from tiering and it may just be disabled. There are some cases where tiering can still produce better-performing code than without tiering, it may be appropriate in the future when there are more such cases to have a mode that yields the best steady-state perf asap without consideration for startup time.

**Comment by kouvel** [comment]
> For scenarios where JIT time is not important during startup, at the moment there would not be much benefit from tiering and it may just be disabled.

Just to add to that, a goal is to ensure that it would not be necessary to disable tiering to achieve comparable or better steady-state perf, we are currently working towards that.

**Comment by mjsabby** [comment]
> skip tier 0 and just generate tier 1 code once for methods that don't have prejitted code, and for methods that have prejitted code, to tier up normally as currently done

@kouvel yup I'm totally fine with that being the setting as it certainly achieves most of what I care about, so if that's just as easy to do this setting we could do that.

**Comment by kouvel** [comment]
Updated title
