### ISSUE TITLE
[x64_arm64_altjit]  failed to archive artifacts

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#21863]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_jitsse2only/407/

**log:**
```
Run condition [Current build status] enabling perform for step [[Archive the artifacts]]
Archiving artifacts
ERROR: No artifacts found that match the file pattern "bin/tests/testReports.zip". Configuration error?
ERROR: �bin/tests/testReports.zip� doesn�t match anything: �bin� exists but not �bin/tests/testReports.zip�
Build step 'Flexible publish' changed build result to FAILURE
```

**Comment by BruceForstall** [comment]
Wrote PR to improve the situation here, with more logging, and avoid failure if nothing to log: https://github.com/dotnet/coreclr/pull/21880

**Comment by BruceForstall** [comment]
Assume fixed with https://github.com/dotnet/coreclr/pull/21880
