### ISSUE TITLE
Inconsistent/ambigious C# 'default' operator behavior with value types

### ISSUE THREAD

**Issue by SherifRefaat** [dotnet/coreclr#21874]
Hi, I am not entirely sure about this. But personally, I don't think this is ever right in terms of secure coding.
Here it is:

`Guid? x = default(Guid?); this is equivalent to Guid? x = default;`
which produce `null` (it is fine).

Let's have the following
`Guid y = Guid.NewGuid();`
then
`Guid? z = (y == default) ? y : default(Guid?);`
this will make `z` equal to `null`. Which again is valid. But if you do
`Guid? z = (y == default) ? y : default;`
this will make `z` equal to `00000000-0000-0000-0000-000000000000` (default value of `System.Guid`)

Implicitly, you mean here the `default` for `z` **not** `y`.

I think this is a problem in terms of secure coding since `z == null` will always fail since it is equal to `00000000-0000-0000-0000-000000000000`
More worse (in my opinion), this `z == default` will always evaluate to false since it contains the default value of `Guid` not `Guid?`

Thanks.

**Comment by SherifRefaat** [comment]
By the way, it seems that this behavior is consistent with all `T?` or `Nullable<T>` where T is a value type.

**Comment by mazong1123** [comment]
This sounds more like a C# lang stuff. Asking in [csharplang](https://github.com/dotnet/csharplang/issues) repo probably could get better response. :)

**Comment by xied75** [comment]
Agree, it's definitely the spec and semantic meaning that belongs to the mentioned repo, e.g.
https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.1/target-typed-default.md

For faster and interactive discussion with the team, try use gitter:
https://gitter.im/dotnet/csharplang?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by SherifRefaat** [comment]
Thanks.
