### ISSUE TITLE
COMPlus_ThreadPool_ForceMinWorkerThreads vs ThreadPool.GetMinThreads value

### ISSUE THREAD

**Issue by joudot** [dotnet/coreclr#21879]
I am setting COMPlus_ThreadPool_ForceMinWorkerThreads before I run a .NET Core console app.

From this console app I call `ThreadPool.GetMinThreads(out int workerThreads, out int ioThreads);`

However I noticed that the **workerThreads** value is different from the **COMPlus_ThreadPool_ForceMinWorkerThreads** value. 

I am sure there is a logic explanation since **workerThreads** is consistent depending on  **COMPlus_ThreadPool_ForceMinWorkerThreads**:
- **workerThreads** = **COMPlus_ThreadPool_ForceMinWorkerThreads** when 0< **COMPlus_ThreadPool_ForceMinWorkerThreads** <10
- **workerThreads** = **COMPlus_ThreadPool_ForceMinWorkerThreads** + 6 when 9< **COMPlus_ThreadPool_ForceMinWorkerThreads** <20
- **workerThreads** = **COMPlus_ThreadPool_ForceMinWorkerThreads** + 12 when 19< **COMPlus_ThreadPool_ForceMinWorkerThreads** <30
- **workerThreads** = **COMPlus_ThreadPool_ForceMinWorkerThreads** + 18 when 29< **COMPlus_ThreadPool_ForceMinWorkerThreads** <40
- ...

What is the explanation for this difference?

**Comment by kouvel** [comment]
The value specified for the environment variable is treated as hexadecimal, even when a 0x prefix is not added. I still get confused by that sometimes :)

**Comment by joudot** [comment]
Shouldn't it be documented on here: [](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md) ?

For some configuration params (e.g **Spinning heuristics Configuration Knobs**), it explicitly says they are hexadecimals but I don't think there is anything about that for the **ThreadPool Configuration Knobs** section.

**Comment by kouvel** [comment]
Yea it should be documented, it would still be very likely that people would miss the docs and run into this anyway. It would have been nice to look for a `0x` prefix before treating the value as hex but it's too late for that and such a change would be breaking now. I'll file an issue to update the docs.

**Comment by blackie1019** [comment]
@joudot Thanks for reply. You answered my question.
