### ISSUE TITLE
Small bit of unreachable IL in CLRtoWinRT stub

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#21883]
Not sure if it matters all that much, but `IL_STUB_CLRtoWinRT` contains a small bit of unreachable IL. Noticed this while modifying the jit to track which methods are only partially imported.
```
IL_0022  25                dup         
IL_0023  16                ldc.i4.0    
IL_0024  3c 0d 00 00 00    bge          13 (IL_0036)
IL_0029  28 03 00 00 06    call         0x6000003
IL_002e  02                ldarg.0     
IL_002f  28 04 00 00 06    call         0x6000004
IL_0034  7a                throw       
IL_0035  16                ldc.i4.0       // unreachable
IL_0036  26                pop         
```
perhaps the emitted IL used to be different?

https://github.com/dotnet/coreclr/blob/bd5ea1c46ca21631194610f88f2ba420e8982d5b/src/vm/dllimport.cpp#L989-L992

**Comment by mateoatr** [comment]
I don't think that this particular line is unreachable. Looking at the emitted IL, we first duplicate whatever is on top of the stack, then we put a 0, and then we compare the two top elements to see if we branch `(X >=? 0)`. If we branch, then good, the line is not reached, but if we do, then the `throw` would be first throwing an exception (`call         0x6000004`), then emptying the stack (according to ECMA 335 III.4.31), and then the `pop` that follows would provoke an underflow.

Furthermore, if I remove the line and try to compile, I get the following:

```
Assert failure(PID 40736 [0x00009f20], Thread: 36616 [0x8f08]): Consistency check failed: IL stack underflow! -- see logging outputFAILED: false

  CROSSGEN! CHECK::Trigger + 0x276 (0x00007ff6`437e11f6)
  CROSSGEN! ILStubLinker::Link + 0x20D (0x00007ff6`43a957cd)
  CROSSGEN! ILStubState::FinishEmit + 0xA52 (0x00007ff6`439da892)
  CROSSGEN! CreateNDirectStubWorker + 0x11C0 (0x00007ff6`439d3c10)
  CROSSGEN! CreateInteropILStub + 0x9E0 (0x00007ff6`439d1f20)
  CROSSGEN! NDirect::CreateCLRToNativeILStub + 0x3C4 (0x00007ff6`439d0314)
  CROSSGEN! NDirect::CreateCLRToNativeILStub + 0x14D (0x00007ff6`439cfecd)
  CROSSGEN! NDirect::GetILStubMethodDesc + 0x84 (0x00007ff6`439dbeb4)
  CROSSGEN! CEEPreloader::GenerateMethodStubs + 0x151 (0x00007ff6`437bcfa1)
  CROSSGEN! ZapImage::TryCompileMethodDef + 0x1B6 (0x00007ff6`43c09726)
      File: root\runtime\src\coreclr\src\vm\stubgen.cpp Line: 836
      Image: root\runtime\artifacts\bin\coreclr\Windows_NT.x64.Debug\crossgen.exe
```

**Comment by AndyAyersMS** [comment]
> I don't think that this particular line is unreachable.

The `pop` does not follow the `throw` in execution order. The next IL instruction to execute after a `throw` must be at the start of some kind of EH clause (or program termination, if no suitable clause can be found).

The stack modelling done by the stub linker also doesn't account for the control flow effects of the `throw`. So when you remove that line, it finds a stack height mismatch that isn't there.

Again, I don't think there is much to be gained from changing this, I just thought it was odd that we'd intentionally emit unreachable IL. Now I see why -- we are working within the limitations of the stub linker stack validation checks.
