### ISSUE TITLE
Set EnableTelemetry=true for CoreCLR dnceng official builds

### ISSUE THREAD

**Issue by MattGal** [dotnet/coreclr#21885]
Whenever kicking off an official build, if you set this property to be true we'll enable automated build failure analysis and logging to the Helix database, and track infrastructure-related problems.

(@robertborr FYI too)

**Comment by MattGal** [comment]
note that you'll likely need to update your view configuration file as well, look at recent PRs from @safern  in dotnet/core-eng for examples.  This is because the telemetry path changed a little (ref/heads, etc)

**Comment by safern** [comment]
https://github.com/dotnet/core-eng/pull/4985

**Comment by sbomer** [comment]
To enable the telemetry from the default job template, we just need to pass enableTelemetry as a parameter to job.yml in https://github.com/dotnet/coreclr/blob/master/eng/xplat-job.yml.

**Comment by RussKeldorph** [comment]
Fixed by #22650.
