### ISSUE TITLE
A static TaskScheduler's field is unnecessarily keeping weak reference of all active TaskSchedulers

### ISSUE THREAD

**Issue by JeffCyr** [dotnet/coreclr#2189]
I'm in a situation where I would need to create potentially millions of custom TaskScheduler instances in a process. This would work perfectly since the TaskScheduler class is very lightweight, however I realized there was extra overhead because of a debugger utility that keeps all references of the actives TaskSchedulers in a static dictionary.

[TaskScheduler default constructor:](https://github.com/dotnet/coreclr/blob/bc146608854d1db9cdbcc0b08029a87754e12b49/src/mscorlib/src/System/Threading/Tasks/TaskScheduler.cs#L302)

```c#
protected TaskScheduler()
{
	// Protected constructor. It's here to ensure all user implemented TaskSchedulers will be 
	// registered in the active schedulers list.
	Contract.Assert(s_activeTaskSchedulers != null, "Expected non-null s_activeTaskSchedulers");
	s_activeTaskSchedulers.Add(this, null);
}
```

Could this dictionary be disabled by default? Maybe with a flag like `Task.s_asyncDebuggingEnabled` does.

**Comment by stephentoub** [comment]
@JeffCyr, ```s_activeTaskSchedulers``` is a ```ConditionalWeakTable<TaskScheduler, object>```, not a ```Dictionary<...>```.  It won't keep the TaskScheduler instances alive.

**Comment by JeffCyr** [comment]
@stephentoub Exactly, I'm concerned about the extra memory

**Comment by stephentoub** [comment]
I see.  Have you measured to show that it's prohibitive?  I just tried with creating 10M schedulers, and it's effectively adding the equivalent of approximately only three reference fields to each instance.  Most schedulers are going to have fields of their own, on top of the 24 bytes from the base class (on 64-bit), and so while at worst it's doubling the size of an instance, it's likely doing a lot less than that.  So we're basically talking about three reference fields extra ammortized across the lifetime of a scheduler instance.

The reason we don't make this conditional on something like s_asyncDebuggingEnabled is because it harms the debugger attach scenario.  Without this, the debugger is unable to efficiently find all TaskSchedulers and then can't query for any tasks scheduled to them.

**Comment by JeffCyr** [comment]
I created a benchmark that compares the difference between the creation of 10 millions task scheduler versus an equivalent class without the static dictionary.

https://gist.github.com/JeffCyr/304848f42ba481fe3e27

Here's the results:

> Real TaskScheduler test:
> Memory usage: 420.48 MB
> Total time: 00:00:13.9793632
> 
> Fake TaskScheduler test:
> Memory usage: 148.89 MB
> Total time: 00:00:01.0347952

In fact the CPU overhead is more troubling than the memory overhead. This is a micro benchmark that does not represent the reality, but still, it seems bad to spend 12 seconds CPU time and 272 MB doing stuff that will never be useful without a debugger attach. I might be misguided, but do people actually use this feature of the debugger? I don't know anybody who does.

Note that most custom TaskScheduler do not return anything in `TaskScheduler.GetScheduledTasks` because there is no efficient way of tracking them, so they are kept in that dictionary for no reason.

**Comment by stephentoub** [comment]
Thanks.  I understand the microbenchmark impact.  I'm asking more about the impact on a real application that has a need for 10M task schedulers.  Do those task schedulers themselves really have no additional fields, do no additional logic in their constructors, exist purely for the scheduling of close to zero tasks, and go away basically instantly?  These costs as shown in the microbenchmark are measurably impactful on such an application?

I'm not arguing it'd be nice to remove any unnecessary overhead, it certainly would be.  But I'm trying to understand whether what we'd give up is really worth it, given the actual impact on a real app.   Note that while it's true that some custom TaskSchedulers don't implement GetScheduledTasks, I don't think it's fair to say that most don't.  And the provided fix harms the scenario for *all* schedulers, including the default scheduler, so with your proposed fix, you likely won't see any queued tasks even from the default thread pool scheduler in an attach scenario... even if we wanted to address this for custom schedulers outside of the framework, we couldn't take the suggested fix as is, for at least this reason.  The ConcurrentExclusiveSchedulerPair scheduler included in the framework also fully implements GetSchedulerPair.  As do many of those provided as working examples in the ParallelExtensionsExtras.  And others I've seen other customers implement.

**Comment by JeffCyr** [comment]
Here's the actual scenario, I'm working with Akka.NET to implement an ActorTaskScheduler that may be use internally by each actor to schedule async methods on their mailbox. The custom scheduler is very lightweight, the only field is a reference back to the actor.

Akka.NET promote the usage of fine grained actor and it can end up with millions of them. As a library it must be flexible to support any kind of use case, and massive actor creation is one of them, it could be inconvenient to have that scenario slowed down unnecessarily.

I understand your concern about the proposed fix, there's probably a middle ground solution where we could opt-out of debugger tracking.

Right now we could bypass the constructor with `FormatterServices.GetUninitializedObject`, it look safe with the current implementation, but I would not use that unless you can guarantee it won't break in a future release :)

**Comment by JeffCyr** [comment]
@stephentoub Continuing on the brainstorm, I thought of adding a virtual property EnableDebuggerAttach, but it could be bad to call that in the base ctor, your solution is less discoverable but maybe safer.

On a side note, does the Visual Studio debugger show the active TaskScheduler with their pending task or it's only used in custom debugger? I occasionally debugged Task/TaskScheduler related issue, but I used ClrMD which can walk the heap and find all TaskScheduler without requiring a static dictionary.

Also, is it useful to have the scheduled task when the process was started without debugger? Task.s_asyncDebuggingEnabled would be false and the debugger would not know the active tasks.

**Comment by stephentoub** [comment]
> does the Visual Studio debugger show the active TaskScheduler with their pending task or it's only used in custom debugger?

It's used by Visual Studio.  While it could walk the heap, that's relatively slow to do while stepping.

> is it useful to have the scheduled task when the process was started without debugger? 

It is when attaching the debugger.

> Task.s_asyncDebuggingEnabled would be false and the debugger would not know the active tasks.

s_asyncDebuggingEnabled is really a separate mechanism and was actually added in a later version than all of this TaskScheduler stuff.  The TaskScheduler mechanism allows the debugger to find all of the scheduled tasks, and to do so in an inexpensive manner, with schedulers that already keep track of tasks for one reason or another being able to just hand that list over to the debugger. The s_asyncDebuggingEnabled mechanism was added in support of debugging tasks related to asynchronous operations, where nothing else is keeping track of these tasks, and where there's overhead associated with doing so, e.g. outputting events for the debugger to listen to, adding and removing each task from a table, etc.

> Continuing on the brainstorm

Thanks for the details on your scenario. I can see how if you're talking about an agent-based design with tons of agents coming and going, each getting its own scheduler, and potentially nothing ever being scheduled to a given agent, that these overheads could become measurable and impactful.  It'd be good to understand whether that's just a theory or whether it actually happens in practice.  Presumably it's more than just a theory if you're considering using a mechanism like GetUnintializedObject(), which is quite a dangerous thing to do (even if works), in large part for the reasons you outline.

We can't sacrifice the attach experience for the default scheduler, but we could work around that, e.g. by doing what you suggest but also adding from the derived TaskScheduler's ctor (in a way that avoids a duplicate-add error).

The question then is whether the costs are measurable enough to warrant either a) sacrificing the attach scenario for other schedulers, b) providing API to control the behavior, or c) coming up with some heuristic.  I think (b) is overkill.  If we could come up with something decent for (c), that'd potentially be ok, but it'd also potentially lead to other bugs and/or confusion.  Which suggest that this really does come down to  the tradeoff in perf vs the attach scenario. 

Are there any numbers you can share from a real, representative app to highlight this actually making a measurable difference?

Also, is this time-sensitive?  I'd like to think about it a bit and also confer with some of the debugger folks.

**Comment by JeffCyr** [comment]
@stephentoub I made a test about the behavior of the "Parallel Tasks" window in Visual Studio 2013 & 2015:

Target -> Debug
```c#
static void Main(string[] args)
{
    ThreadPool.SetMaxThreads(4, 4);

    Task.Factory.StartNew(Task1);
    Task.Factory.StartNew(Task2);
    Task.Factory.StartNew(Task3);
    Task.Factory.StartNew(Task4);

    Task.Factory.StartNew(Task1);
    Task.Factory.StartNew(Task1);
    Task.Factory.StartNew(Task1);
    Task.Factory.StartNew(Task1);
    Task.Factory.StartNew(Task1);

    Console.ReadKey(true);
}

private static void Task1()
{
    while (true) ;
}

private static void Task2()
{
    Thread.Sleep(-1);
}

private static void Task3()
{
    Thread.Sleep(-1);
}

private static void Task4()
{
    Thread.Sleep(-1);
}
```

Results when the process is started with debugger:
![tasks-started-with-debugger](https://cloud.githubusercontent.com/assets/2624074/11501154/0a0d1ce8-9800-11e5-93d6-aebe84f58f2a.png)

And when the process is started without debugger:
![tasks-started-without-debugger](https://cloud.githubusercontent.com/assets/2624074/11501162/15696f4c-9800-11e5-80ba-16be92da16b5.png)

So it seems that Visual Studio's debugger is unable to show the scheduled tasks anyway when the process is started without debugger. Considering this, do you think that the proposed fix of checking `Task.s_asyncDebuggingEnabled` would be acceptable?

The question about if this would be measurable in a real-world application is hard to answer concretely, right now Akka.NET actors are geared towards synchronous message handling which does not use a custom TaskScheduler, I'm working right now to build a robust and efficient mechanism to support asynchronous message handling in the actors through an ActorTaskScheduler per actor.

So I'm only theoretically speaking here, in practice I guess that the memory usage won't be noticeable and the CPU overhead will be amortized. But since it would not harm the debugger attach scenario in Visual Studio like my testing showed, I think its a free optimization. It would also be nice that when people are micro-benchmarking Akka.NET they don't get slowed down by an unnecessary TaskScheduler debugging utility.

This is not time-sentitive, I guess that even if it was fixed now we wouldn't get it in .Net 4.6.X for a while anyway. And we mitigate this by lazy creating the TaskScheduler per actor only when async message processing is actually used.

Thanks for looking into this!

**Comment by stephentoub** [comment]
Hmm.  You're right that something appears to be amiss, though I see something different.  When I attach, I see this:
![attach](https://cloud.githubusercontent.com/assets/2642209/11501860/4a41aebe-9805-11e5-827e-c2e706d55357.PNG)
though if I attach by adding a call to Debugger.Launch(), I get this as expected:
![launch](https://cloud.githubusercontent.com/assets/2642209/11501878/64f3bf68-9805-11e5-810a-79f24240492f.PNG)

@gregg-miskelly, do you know what's going on here and what the expected behavior is?  Is my knowledge of the expected results here just out-of-date?

Regarding, "And we mitigate this by lazy creating the TaskScheduler per actor only when async message processing is actually used", I'd think you'd want to do that anyway.  If you're really talking about millions of these things getting created, then you'd likely want to eliminate as many per-actor objects as you can until they're absolutely needed.

**Comment by JeffCyr** [comment]
@stephentoub For the record, I have .Net 4.6 installed (version 4.6.96.0) and the test project was targeting .Net 4.5.1 but I retried with .Net 4.6 and got the same results.

**Comment by stephentoub** [comment]
@gregg-miskelly, thoughts on this?
