### ISSUE TITLE
System.ExecutionEngineException on call to GC.Collect()

### ISSUE THREAD

**Issue by sunkin351** [dotnet/coreclr#21949]
In an attempt to see if a garbage collection would invalidate a Function Pointer returned from a call to `Marshal.GetFunctionPointerForDelegate<T>()`, I call `GC.Collect()` directly after and it throws an `ExecutionEngineException`. Is this a bug with .NET Core or am I doing something wrong?

.NET Runtime version: `.NET Core 2.1`

**Comment by sunkin351** [comment]
One other thing, It is a release build only thing... Not sure why.

**Comment by jkotas** [comment]
Could you please share a small program (e.g. as gist) that demonstrates this problem?

**Comment by sunkin351** [comment]
Literally, it's this:
```cs
delegate void TestDelegate();
static void Main(string[] args)
{
    IntPtr ptr = Marshal.GetFunctionPointerFromDelegate<TestDelegate>(SomeFunction); //Some function matching the Delegate signature
    GC.Collect();
}
```
I don't understand what I could be doing wrong. It's guaranteed to throw when I compile and run this in release mode on my machine.

**Comment by sunkin351** [comment]
One more thing to note, in debug mode, the pointer is still valid after the collection... Whereas normally it would throw a `NullReferenceException`, not caused by the pointer dereference. This should also be looked at.

**Comment by AaronRobinsonMSFT** [comment]
@sunkin351 I am unable to reproduce this issue. I am using .NET Core 2.1. Is there any chance you can gather a DMP of the crash?

```csharp
using System;
using System.Runtime.InteropServices;

namespace ConsoleApp1
{
    class Program
    {
        static void SomeFunction()
        { }

        delegate void TestDelegate();
        static void Main(string[] args)
        {
            IntPtr ptr = Marshal.GetFunctionPointerForDelegate<TestDelegate>(SomeFunction); //Some function matching the Delegate signature
            GC.Collect();
        }
    }
}
```

**Comment by sunkin351** [comment]
This is Windows 10 I'm running on. Can you walk me through getting the crash dump for you? I've never heard of being able to do this before now.

**Comment by AaronRobinsonMSFT** [comment]
There are a number of ways, but the easiest would probably be to use [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump). Above it was mentioned this occurred in 'Release', you can also debug the 'Release' build from Visual Studio and capture of a DMP using https://docs.microsoft.com/en-us/visualstudio/debugger/using-dump-files?view=vs-2017#BKMK_Create_a_dump_file.

**Comment by sunkin351** [comment]
I just ran the test once more to make sure the issue was still present... Now its failing as it should (FailFast ExecutionEngineException upon callback of the garbage collected delegate.) instead of an `ExecutionEngineException` being thrown in `GC.Collect()`... Idk if that's actually what it was doing all along, cause it was pointing to GC.Collect() being the source of the error before, but now its the actual pointer invocation.

**Comment by sunkin351** [comment]
This started as an experiment to see what would happen if I tried to call a garbage collected delegate as if from native code, so now I know. But then there's an interesting situation where this doesn't happen in Debug. XD

**Comment by sunkin351** [comment]
I figured the no optimization thing would leave a few references. Thanks. Closing this now as this issue is mostly circumstantial, it would appear.
