### ISSUE TITLE
Re-enable signing for System.Private.CoreLib

### ISSUE THREAD

**Issue by morganbr** [dotnet/coreclr#21946]
System.Private.CoreLib isn't currently being signed due to https://github.com/dotnet/arcade/issues/1582 . Once that's resolved, the block below should be removed https://github.com/dotnet/coreclr/blob/234bbb509e9ea8b08787fcd509edd6141e37d751/eng/Signing.props#L50-L53

**Comment by sbomer** [comment]
Official build with the fix: https://dnceng.visualstudio.com/internal/_build/results?buildId=76035
