### ISSUE TITLE
Waiting for v2.1.7-dependencies tag

### ISSUE THREAD

**Issue by vellozzi** [dotnet/coreclr#21958]
We're waiting on the v2.1.7-dependencies tag so we can build 2.1.7.
Are you still following the "-dependencies" convention for this repo?  Can you give an ETA?

**Comment by RussKeldorph** [comment]
@wtgodbe @mmitche

**Comment by vellozzi** [comment]
OK.  But what is the 2.1.6-dependencies tag for then?
It looks like the last commit before that tag is actually changing dependencies.

I also have a couple issues open for corefx and core-setup: https://github.com/dotnet/corefx/issues/34551 and https://github.com/dotnet/core-setup/issues/4962

do those need to be tagged still?

**Comment by mmitche** [comment]
core-setup and corefx definitely need tags.  The 2.1.6 tag for dependencies is technically incorrect for coreclr but doesn't functionally matter.

**Comment by vellozzi** [comment]
OK.  Thanks.
