### ISSUE TITLE
Generic Type Check elision for enums

### ISSUE THREAD

**Issue by damageboy** [dotnet/coreclr#21971]
Hi,
I'm trying to figure out if / how can generic type checking for enums be elided at JIT time...
Sample (of theoretical code that I would like the JIT to pick up and optimize away:

[Link to sharplab.io](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgBgARYCMA3ALABQueAygBYQIAOAMhMAHQBKArgHYwBLMHDKUAzAQBMeAMJ4A3hTzKCEuL25gaAe2EBRDVsXkVpvAEEkeAEJWZVgCJKVAX2fL3qggBY8AWQAKAEo8T2MzFWpdOANNPAg8AF4dfUN2B1EI5XNGRnUAEwBxdUQBAGMAiCDM109PUwBtACkBGGLeUoqYAE887QAzAKjUzSCggF16lQF+RF4IABsfC1yC9s6AHgAVAD4ArbwYIKnlcKzTAHoLvEYYBDxaRDg8ASh4m+0Z+HuYbUPHm4MCDCb54ADuzzBEH4hz+/W0CEgMGIeHhCBOZiueCgQkYC2eADdFtxnj08m8IXgytCqdAYP9noxPrN7vkBAg4GUYAtulZgNx6WiMZdrkQcG9ofk8HwANa8bRg3h4ADmJQQ5TwRIWJMOvTgFOeHTgUt+N24CyWMEeYGFKix2gFmoECQSZONeA5/SevDKcAotuUWKtrzwC202hlb2VCG0UCgfMdBxDcoVSog9KaAEktgBaQTCbF/YNvakWw4cv0mc5266qmAl3SMAT4qX5VOw95sjlc2llsGtWh4eV4YAIaFlWgzZUBl79PABN0DfYhRLJReDKDAbrwMYz0w5PK8fIBQjVGdwBZQZ4COcLvVLrYrtf3wZbnfHKvVswHgoBSRnz9qwvK9Z3nddlySZ8+g3WgESOD8vwiH8jwCMQAMQvBgOvW9wMfSDdWggJuCgWCEHgvcVGQ49vHQxCsNAu9CLw1cCLgJcvl3QCMKogIAFZaK/eibzAl8IJY8DuA4hCMMo1YUIANgEoDL2wkSmKfVilzDXhlU4mTZMPY8AHYlPOIScNE5ioLYwZzW0HS9P0lZDICAAOUysnMtSbLE6yl36MN00c/SeIATg8iIvMYnyrM0wY224YB8WCmSeMIHAIrMKLcI08D8k5IRFhS7i5OPQhTxqQSVIYnL8PA4BwwWYrELS/9KuUkDhOih9ctEicGGar80rQ9qzOqrravE0TCkk/JBurNKaNGzzxos9S6tEhx0zgLYhDgebzjS/jlsi1bvJ6jamL26hGGhA6sjSxSTqys7usGR92EzKBYjAaSQtKgJ5Ke89XsmvzBjFe7Tgo7IAcIEzntMNwuJWq8ZzOf6XMIdzEdqFHlGR0xPCwCQsF8HivniEIwgxIhQsqJTkYoFwgA==)
```csharp
internal void AppendGeneric<T>(T t)
{
    // this looks gross, but T is known at JIT-time so this call tree
    // gets compiled down to a direct call with no branching
    if (typeof(T) == typeof(sbyte))
      Append(1);
    else if (typeof(T) == typeof(byte))
       Append(2);
    ...
    else if (typeof(T).IsEnum)
        Append(66);
    else if (typeof(T) == typeof(string))
        Append(17);
    else
        Append(18);
}   
```

Currently, the JIT appears to not recognize / pickup the `if (typeof(T).IsEnum)` expression at JIT time.

Would it be possible for the JIT to support such type checks at JIT time?

Naturally, this sort of enhancement should not be limited to IsEnum specifically, and there are many other type checks that could benefit from this sort of optimization...

**Comment by AndyAyersMS** [comment]
Yes, it's possible -- there was a similar suggestion over in #2591.

**Comment by damageboy** [comment]
Grrr...
I really tried to search for previous issues before posting this.
Closing since its obviously a duplicate...
