### ISSUE TITLE
System.Collections.Concurrent.Tests test hang

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#21995]
In a PR of mine I saw a test failure that seems like it could indicate a real issue, or perhaps a test bug:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_corefx_innerloop_prtest/6358/console

```
06:00:08.568 WARNING: System.Collections.Concurrent.Tests.ConcurrentBagTests.ManyConcurrentAddsTakes_EnsureTrackedCountsMatchResultingCollection(threadsPerProc: 1, seconds: 0.5) is running for 19657s.
06:00:08.568 WARNING: System.Collections.Concurrent.Tests.EtwTests.TestEtw is running for 19673s.
06:00:08.568 WARNING: System.Collections.Concurrent.Tests.ConcurrentQueueTests.ToArray_ParallelInvocations_Succeed is running for 19673s.
06:00:08.568 WARNING: System.Collections.Concurrent.Tests.ConcurrentStackTests.ToArray_ParallelInvocations_Succeed is running for 19666s.
06:00:28.900 Build timed out (after 360 minutes). Marking the build as aborted.
```
It worked fine on a second try and I can't seem to find existing reports of this so it's probably rare/hard to reproduce.

What looks interesting to me is that there are 4 test that are (presumably) running in parallel and they're all stuck. 3 of them are likely 100% independent and should not have such an issue. But if you put the 4th into the mix - EtwTests - I suppose it's possible that there's an issue somewhere, in ETW perhaps.

**Comment by danmosemsft** [comment]
@brianrob the TestEtw test here is doing work inside
```c#
            using (var listener = new TestEventListener("System.Collections.Concurrent.ConcurrentCollectionsEventSource", EventLevel.Verbose))
```
Specifically it is invoking `RunWithCallback`.

[TestEventListener is a ](https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs) S.D.Tracing.EventListener.

Is it possible for this to affect independent concurrently running tests that are using concurrent collections? Eg., the listener is somehow synchronous with work they are doing.

**Comment by stephentoub** [comment]
I'm not sure why it would be causing this issue, but these tests should be moved to another process with RemoteInvoke, to avoid interference between the EventSource tests and every other test in the process; we already do that in some test suites, but apparently not here.  I'll take care of that.

**Comment by danmosemsft** [comment]
I guess let's close this based on that change, but @brianrob please let us know if you think there is a product bug maybe.

**Comment by filipnavara** [comment]
Not sure what is going on, but I keep hitting this in CI now. Exact same symptoms, same build configuration ("Ubuntu x64 Checked CoreFX Tests"). My guess is that the CoreFX tests still using the stale snapshot and didn't pick-up https://github.com/dotnet/corefx/pull/34645, right? If that's the case, is there something that could be done about it until we get up-to-date CoreFX tests (https://github.com/dotnet/corefx/issues/34957, https://github.com/dotnet/corefx/pull/35439)? Perhaps temporarily disabling the offending test.
