### ISSUE TITLE
Instrumented System.Private.CoreLib causes StackOverflowException

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/coreclr#21994]
We are currently using coverlet in corefx for code coverage measurement. Coverlet instruments an assembly with Mono.Cecil and adds a tracker template type + calls to the template for every hit count to be recorded.

The tracker template: https://github.com/tonerdo/coverlet/blob/master/src/coverlet.template/ModuleTrackerTemplate.cs

The calls to the template (example Internal.IO.File.Exists):

```
// File
using Coverlet.Core.Instrumentation.Tracker;
using System;
using System.IO;
using System.Security;

public static bool Exists(string path)
{
    bool result;
    try
    {
        System.Private.CoreLib_c64a6f40-c11a-4e9c-b1eb-86506d4b4c35.RecordHit(147618);
        if (path == null)
        {
            System.Private.CoreLib_c64a6f40-c11a-4e9c-b1eb-86506d4b4c35.RecordHit(147619);
            System.Private.CoreLib_c64a6f40-c11a-4e9c-b1eb-86506d4b4c35.RecordHit(147620);
            result = false;
        }
```

Something must have changed recently (in the last 3 months) as I tried a version from October which worked fine (3.0.0-preview1-26929-03).

StackOverflow details from windbg:

```
Failed to request MethodData, not in JIT code range
MethodDesc:   00007ffe8f19b9c0
Method Name:          Coverlet.Core.Instrumentation.Tracker.System.Private.CoreLib_c64a6f40-c11a-4e9c-b1eb-86506d4b4c35.RecordHit(Int32)
Class:                00007ffe8f1a2980
MethodTable:          00007ffe8f19b9f0
mdToken:              00000000060052c9
Module:               00007ffe8eff6020
IsJitted:             yes
Current CodeAddr:     00007ffe8f116510
Code Version History:
  CodeAddr:           00007ffe8f116510  (Tier 0)
  NativeCodeVersion:  0000000000000000
```

Repro steps:
1. Build corefx
2. Remove this line https://github.com/dotnet/corefx/blob/master/src/Directory.Build.props#L30
3. Copy contents from `corefx\artifacts\bin\testhost\netcoreapp-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\9.9.9\il` to `corefx\artifacts\bin\testhost\netcoreapp-Windows_NT-Debug-x64\shared\Microsoft.NETCore.App\9.9.9` (replace).
4. Run a code coverage test run from System.Diagnostics.Debug: `dotnet msbuild src\System.Diagnostics.Debug\tests\ /t:RebuildAndTest /p:Coverage=true`.

cc @jkotas

**Comment by sharwell** [comment]
📝 I proposed testing again with `System.Threading.Interlocked` excluded from instrumentation. This type is the only remaining point of recursion now that tonerdo/coverlet#291 is merged.

**Comment by jkotas** [comment]
Looks like @sharwell has the fix.
