### ISSUE TITLE
Mac OS X - DllNotFoundException for libcurl

### ISSUE THREAD

**Issue by jflr** [dotnet/coreclr#2200]
### Mac OS X - DllNotFoundException for libcurl
A DllNotFoundException is thrown when running `dnu restore`.  

### Functional impact
`dnu restore` fails.

### Minimal repro steps
Run `dnu restore` with `CoreClr-x64-1.0.0-rc1-16202`.  

### Expected result
`dnu restore` should succeed.

### Actual result
When running `dnu restore`, the following exception is thrown:
>System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libcurl': The specified module could not be found.
> (Exception from HRESULT: 0x8007007E)
>   at Interop.libcurl.curl_version_info(Int32 curlVersionStamp)
>   at System.Net.Http.CurlHandler..cctor()
>   --- End of inner exception stack trace ---
>   at System.Net.Http.CurlHandler..ctor()
>   at System.Net.Http.HttpClient..ctor()
>   at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource..ctor(String baseUri, String userName, String password, Reports reports)
>   at Microsoft.Dnx.Tooling.PackageFeedCache.CreatePackageFeed(PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Reports reports)
>   at Microsoft.Dnx.Tooling.PackageFeedCache.<>c__DisplayClass1_0.<GetPackageFeed>b__0(PackageSource _)
>   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>   at Microsoft.Dnx.Tooling.PackageFeedCache.GetPackageFeed(PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Reports reports)
>   at Microsoft.Dnx.Tooling.RestoreCommand.AddRemoteProvidersFromSources(List`1 remoteProviders, List`1 effectiveSources, PackageFeedCache packageFeeds, SummaryContext summary)
>   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()

### Further technical details
`curl --version` returns:
>curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
>Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
>Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets

**Comment by joshfree** [comment]
@muratg @danroth27

**Comment by muratg** [comment]
@moozzyk

**Comment by joshfree** [comment]
@Sridhar-MS @piotrpMSFT PTAL in the context of CLI for RC2

**Comment by Sridhar-MS** [comment]
Moved this issue to dotnet/cli#956 and closing this one.
