### ISSUE TITLE
Structures with fixed buffers sometimes misclassified in SystemV eightbyte classification

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/coreclr#22016]
The struct below is misclassified by the SystemV classifier:

```csharp
[StructLayout(LayoutKind.Sequential)]
public unsafe struct FixedBufferClassificationTest
{
    public fixed int arr[3];
    public float f;
}
```

The two eightbytes should both be classified as `INTEGER` eightbytes; however, the runtime sees the type above as equivalent to the following:

```csharp
[StructLayout(LayoutKind.Sequential)]
public unsafe struct FixedBufferClassificationTest
{
    [StructLayout(LayoutKind.Sequential, Size=12)]
    private struct FixedBufferType
    {
         private int i;
    }
    [FixedBufferAttribute(typeof(int),3)]
    public FixedBufferType arr;
    public float f;
}
```

Since the classifier has no special knowledge of the concept of fixed buffers, the classifier marks the first four bytes as `INTEGER`, the next 8 as `NO_CLASS`, and the final four as `SSE`. This results in the second eightbyte being classified as `SSE` instead of `INTEGER`.

**Comment by janvorli** [comment]
@jkoritzinsky just to make sure I understand it correctly - does it means that for fixed buffers, we don't classify each entry of the fixed array but just the first one?

**Comment by jkoritzinsky** [comment]
Yep. We only classify the first field since theees only one field in metadata.
