### ISSUE TITLE
[Linux/arm64] Ready2Run exit code 137 test failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#22010]
We see quite a few Linux/arm64 test jobs fail with exit code 137. I _think_ this corresponds to SIGKILL.

What does it mean?

What can be done about it?

E.g.,
https://github.com/dotnet/coreclr/issues/22001
https://github.com/dotnet/coreclr/issues/22000
https://github.com/dotnet/coreclr/issues/21801
https://github.com/dotnet/coreclr/issues/21269
https://github.com/dotnet/coreclr/issues/20992
https://github.com/dotnet/coreclr/issues/20991
https://github.com/dotnet/coreclr/issues/20990
https://github.com/dotnet/coreclr/issues/20989
https://github.com/dotnet/coreclr/issues/20539
https://github.com/dotnet/coreclr/issues/20517

**Comment by BruceForstall** [comment]
@janvorli @jashook @echesakovMSFT @dotnet/arm64-contrib @dotnet/jit-contrib Ideas?

**Comment by jashook** [comment]
It is worth reproing some of these individually to see if they only get the signal under load.

**Comment by echesakovMSFT** [comment]
Interestingly, all the failure you referred to happened during Ready2Run jobs

**Comment by sdmaclea** [comment]
137 is SIGKILL. `kill -l` will show the list of signals.   Error code is 128 + signal.

In my runs, SIGKILL typically came from timeout, triggered by my wrapper code.  It can also be triggered by an out of memory condition.  A few of the GC tests stress memory and shouldn't be run in parallel with other tests.

**Comment by CarolEidt** [comment]
I was unable to repro linux/arm64 issue #21802 (also a r2r stress run), after multiple attempts. This was also a SIGKILL error code. The subsequent test run was clean, and then the one after that had another SIGKILL failure, plus an exit code 1 that I was unable to repro. 
It would be great if we could figure out how to avoid these.

**Comment by BruceForstall** [comment]
One problem here is that these almost always don't repro when run by hand, and subsequent test runs also normally pass. But the issues keep popping up. Noticing that these have all been R2R failures is useful. If any other patterns are noticed, that too would be useful. I think we somehow need to try "harder" (or "smarter") to repro or otherwise figure out what's causing these failures.

**Comment by CarolEidt** [comment]
It would be useful to have a way to run a test under load - e.g. have a dummy app that would stress memory & cpu (should be fairly simple to write?) and have that running while trying to repro the test.

**Comment by echesakovMSFT** [comment]
I used **stress tool** (https://linux.die.net/man/1/stress) for this

**Comment by CarolEidt** [comment]
@echesakovMSFT - did it repro test failures that otherwise didn't fail?

**Comment by echesakovMSFT** [comment]
@CarolEidt I used this tool to repro other failures before (not related to these ones). The tool does exactly what you described (i.e. keeping busy all/some cpu cores and stressing memory)

**Comment by BruceForstall** [comment]
More cases:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_ubuntu16.04_r2r_tst/24/consoleFull
-- 3 GCSimulator failures

https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_ubuntu16.04_r2r_tst/24/consoleFull
-- 4 failures
```
baseservices_threading._semaphore_ctoropen_semaphorectorneg3_semaphorectorneg3_._semaphore_ctoropen_semaphorectorneg3_semaphorectorneg3_sh
JIT_Directed._StrAccess_straccess4_straccess4_._StrAccess_straccess4_straccess4_sh
JIT_IL_Conformance._Old_Base_brfalse_brfalse_._Old_Base_brfalse_brfalse_sh
JIT_HardwareIntrinsics._X86_Sse_Sqrt_r_Sqrt_r_._X86_Sse_Sqrt_r_Sqrt_r_sh
```

**Comment by RussKeldorph** [comment]
@sergiy-k This appears to be specific to ARM64 ReadyToRun.  Do you have someone that could investigate?

**Comment by sergiy-k** [comment]
I wonder how much memory is on these machines. I'm asking this because one of the common reasons for exit code 137 is when a process is killed by OOM Killer. From the two log files that @BruceForstall shared above, I can see that in both cases the failure happened on DDARM64S-011. It looks like that all of the failed tests exited with code 137 about at the same time. Whether OOM happens or not might depend on the set of tests that xunit decides to run in parallel at the same time.

One way to verify whether this is due to OOM Killer is to check the messages in /var/log/messages on the machine where the failure occurred. Is it possible to do that?

/cc @janvorli

**Comment by RussKeldorph** [comment]
History is limited at this point, but this doesn't seem to be hitting anywhere.  Assuming @sergiy-k's theory is correct.
