### ISSUE TITLE
[arm] Test failed: System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(noProviderName: False)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22024]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_baseline_tst/50/

**Failed  test:**
System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(noProviderName: False)

**Log:**
```
System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(noProviderName: False) [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Diagnostics.EventLog\tests\System\Diagnostics\Reader\ProviderMetadataTests.cs(26,0): at System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(Boolean noProviderName)
  Finished:    System.Diagnostics.EventLog.Tests
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.EventLog.Tests  Total: 142, Errors: 0, Failed: 1, Skipped: 1, Time: 70.836s
----- end  6:56:08.37 ----- exit code 1 ----------------------------------------------------------
```

**Comment by BruceForstall** [comment]
Also failed the next run,

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_baseline_tst/51/consoleFull

@danmosemsft Any known issues here?

**Comment by danmosemsft** [comment]
Looks like https://github.com/dotnet/corefx/issues/34547

@maryamariyan what is the status there -  I thought you fixed it?

**Comment by maryamariyan** [comment]
No that was separate test that @stephentoub disabled in https://github.com/dotnet/corefx/pull/34548.

I'm looking at this now.

**Comment by maryamariyan** [comment]
Pushed up https://github.com/dotnet/corefx/pull/34650
