### ISSUE TITLE
[arm64] Are unwind codes after frame pointer established unnecessary?

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#22056]
In some arm64 frame types, we establish the frame pointer and then subtract off the remainder of the frame, e.g.:
```
stp     fp, lr, [sp,#-16]!
mov     fp, sp
sub     sp, sp, #0x910
```
And this `sub sp` is reported in the unwind info. Does it need to be? Once the frame pointer is established, the unwinder should be able to unwind the callee-saved regs and the rest of the frame.

**Comment by janvorli** [comment]
It seems to me that you are right and that this does not need to be reported in the unwind info for FP based frames.
