### ISSUE TITLE
Loading profiler failed CoCreateInstance 0x8007007e

### ISSUE THREAD

**Issue by kenfullscale** [dotnet/coreclr#22066]
**Behavior**
Our profiler failed to be loaded in centOs 7.6 with the error code 0x8007007e
"Loading profiler failed during C"..., 183Loading profiler failed during CoCreateInstance.  Profiler CLSID: '{cf0d821e-299b-5307-a3d8-b283c03916da}'.  HRESULT: 0x8007007e.  Process ID (decimal): 103504.  Message ID: [0x2504].) = 183

**Strace log**
stat("/usr/share/dotnet/libcoreclr.so", 0x7ffd9eef2358) = -1 ENOENT (No such file or directory)
stat("/usr/share/dotnet/dotnet.dll", 0x7ffd9eef23a8) = -1 ENOENT (No such file or directory)
stat("/usr/share/dotnet/shared/Microsoft.NETCore.App/2.2.1/Microsoft.NETCore.App.runtimeconfig.dev.json", 0x7ffd9eef1018) = -1 ENOENT (No such file or directory)
stat("/usr/share/dotnet/shared/Microsoft.NETCore.App/2.2.1/Microsoft.NETCore.App.runtimeconfig.json", 0x7ffd9eef1338) = -1 ENOENT (No such file or directory)

**Comment by RussKeldorph** [comment]
@dotnet/dotnet-diag

**Comment by sywhang** [comment]
That particular HResult indicates that your profiler module could not be found. Did you set the environment variables ```CORECLR_PROFILER``` and ```CORECLR_PROFILER_PATH``` correctly? ```CORECLR_PROFILER``` should be set to the exact GUID that your profiler exported and ```CORECLR_PROFILER_PATH``` should be set to the exact path to your profiler's dll.

**Comment by kenfullscale** [comment]
@sywhang , I set properly all the environment variables and this is working fine in ubuntu but not in centos 7.6.

**Comment by sywhang** [comment]
@kenfullscale That's interesting. We haven't tested our profiler tests on CentOS yet so there may actually be a product issue. I'll try to get a CentOS machine and see I can repro your issue. Thanks for reporting this.

**Comment by sywhang** [comment]
cc @noahfalk @davmason

**Comment by kenfullscale** [comment]
I already fix this issue.
