### ISSUE TITLE
Adding memcmp intrisinc?

### ISSUE THREAD

**Issue by ayende** [dotnet/coreclr#22078]
We are using `memcmp` a _lot_, to do comparisons of pieces of data inside mmap file.
Because of the cost of p/invoke, we wrote our own memory comparison function and only shell to `memcmp` if the size is large enough to be worth it. 

I would rather be able to directly call `memcmp` without paying the pinvoke costs. 
Calls to `memset` and `memcpy` are already exposed via `Unsafe.InitBlock` and `Unsafe.CopyBlock`, respectively.
See: 
https://github.com/dotnet/corefx/blob/64c6d9fe5409be14bdc3609d73ffb3fea1f35797/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L162

What would be the process of adding a similar functionality for exposing `memcmp` ?

**Comment by jkotas** [comment]
`Unsafe.` are thin wrappers over IL instructions. There is no memcmp IL instruction and that's why there is no `Unsafe.MemCmp`.

`int SequenceCompareTo<byte>(ReadOnlySpan<byte> span, ReadOnlySpan<byte> other)` is the public API equivalent of memcmp. Have you tried that?

**Comment by ayende** [comment]
I wouldn't actually include a static copy of it. My intent was to basically shell to the same `memcmp` that is used everywhere. I assume that this gets to the normal C library, which is already as optimized as we can get.

**Comment by GSPP** [comment]
@ayende 

> which is already as optimized as we can get.

I'm not so sure about that. I saw reports about major optimizations in memcpy/memcmp in standard libraries fairly recently (at most very few years ago). At that time I was amazed to learn that these methods had not been properly optimized before.

It is not safe to rely on standard library memcpy/memcmp to be maximally fast.

**Comment by redknightlois** [comment]
@jkotas I have seen in the code some things that could be streamlined (no guarantees though), but those improvements would also be of benefit given our use case. The code is going to be a bit more complex though because we will be working with intrinsics and managing the emitted assembler type of techniques. 

If it is of your interest I can give it a try. I wouldn't start though if there is no interest to pursue that direction.

**Comment by jkotas** [comment]
We are interested in performance improvements. As you know, we try to maintain a balance between the code complexity and performance of different cases (e.g. it is common for changes like these to help for some cases and regress other cases). 

@benaadams tried improvements for SequenceEquals in https://github.com/dotnet/coreclr/pull/22019 that did not seem to work well.

**Comment by redknightlois** [comment]
Will give it a try then.

**Comment by benaadams** [comment]
> @benaadams tried improvements for SequenceEquals in #22019 that did not seem to work well.

OTOH it did help me notice that IndexOf can be likely significantly improved; which SequenceCompareTo can like benefit from; as they are similar in that they both need to find the location of the match/non-match in a vector and equals already gives it https://github.com/dotnet/coreclr/pull/22118

**Comment by benaadams** [comment]
i.e. this part specifically of `SequenceEquals` where its processing a non-match I'm referring to:

https://github.com/dotnet/coreclr/blob/a5c5feb8939ae6ae10d9d2b7f2bc8d43ed99bc38/src/System.Private.CoreLib/shared/System/SpanHelpers.Byte.cs#L1076-L1083

**Comment by redknightlois** [comment]
@benaadams what are the benchmark scenarios you are using for the `memcmp`. If you already have the code for them, better as we can talk over the same set of results :)

**Comment by benaadams** [comment]
Using changes in https://github.com/dotnet/coreclr/pull/22127

Different

```
|  Method |   N |      Mean |
|-------- |---- |----------:|
|  Native |  16 | 10.751 ns |
| Managed |  16 |  5.141 ns |
|  Native |  17 | 10.705 ns |
| Managed |  17 |  4.582 ns |
|  Native |  25 | 10.564 ns |
| Managed |  25 |  4.435 ns |
|  Native |  32 | 10.551 ns |
| Managed |  32 |  5.227 ns |
|  Native |  79 | 10.360 ns |
| Managed |  79 |  4.584 ns |
|  Native | 256 | 10.813 ns |
| Managed | 256 |  5.013 ns |
```

AlmostSameButDifferent

```
|  Method |   N |      Mean |
|-------- |---- |----------:|
|  Native |  16 | 11.298 ns |
| Managed |  16 |  4.717 ns |
|  Native |  17 | 13.002 ns |
| Managed |  17 |  5.557 ns |
|  Native |  25 | 12.173 ns |
| Managed |  25 |  5.548 ns |
|  Native |  32 | 12.470 ns |
| Managed |  32 |  4.613 ns |
|  Native |  79 | 16.639 ns |
| Managed |  79 |  7.081 ns |
|  Native | 256 | 21.392 ns |
| Managed | 256 | 11.007 ns |
```

Same  

```
|  Method |   N |      Mean |
|-------- |---- |----------:|
|  Native |  16 | 11.471 ns |
| Managed |  16 |  4.686 ns |
|  Native |  17 | 11.454 ns |
| Managed |  17 |  4.527 ns |
|  Native |  25 | 11.966 ns |
| Managed |  25 |  4.552 ns |
|  Native |  32 | 11.751 ns |
| Managed |  32 |  3.999 ns |
|  Native |  79 | 16.089 ns |
| Managed |  79 |  5.850 ns |
|  Native | 256 | 21.342 ns |
| Managed | 256 | 10.994 ns |
```
