### ISSUE TITLE
CoreFX tests work 3x time slower on arm64 than on arm32.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#22077]
Out arm64 corefx jobs are usually failing with timeouts: [example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_baseline_tst/23/console).

It happens because most tests work very slow (significantly slower than on arm32, on arm32 [the job takes ~3 hours](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_corefx_baseline_tst/51/), on arm64 fails with 6 hours timeout).

I have tested it locally and got the same result, for example:
```
arm32
Z:\_\fxArm\artifacts\bin\tests\System.ComponentModel.Annotations.Tests\netcoreapp-Windows_NT-Release-arm>call Z:\_\fxArm\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe xunit.console.dll System.ComponentModel.Annotations.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -verbose -method System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.DotDecimalExtremaAndInvalidValuesInvariantParse -parallel none
xUnit.net Console Runner v2.4.1-pre.build.4059 (32-bit .NET Core 4.6.27308.0)
  Discovering: System.ComponentModel.Annotations.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.ComponentModel.Annotations.Tests (found 1 of 351 test case)
  Starting:    System.ComponentModel.Annotations.Tests (parallel test collections = off, max threads = 8)
    System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.DotDecimalExtremaAndInvalidValuesInvariantParse(type: typeof(decimal), min: "1.0", max: "3.0", value: "9.0") [STARTING]
    System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.DotDecimalExtremaAndInvalidValuesInvariantParse(type: typeof(decimal), min: "1.0", max: "3.0", value: "9.0") 
[FINISHED] Time: 1.6501653s
```
and
```
arm64
Z:\_\fx\artifacts\bin\tests\System.ComponentModel.Annotations.Tests\netcoreapp-Windows_NT-Release-arm64>call %WORKSPACE%\_\fx\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-arm64\dotnet.exe xunit.console.dll System.ComponentModel.Annotations.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -verbose -method System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.DotDecimalExtremaAndInvalidValuesInvariantParse -parallel none
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.27308.0)
  Discovering: System.ComponentModel.Annotations.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.ComponentModel.Annotations.Tests (found 1 of 351 test case)
  Starting:    System.ComponentModel.Annotations.Tests (parallel test collections = off, max threads = 8)
    System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.DotDecimalExtremaAndInvalidValuesInvariantParse(type: typeof(decimal), min: "1.0", max: "3.0", value: "9.0") [STARTING]
    System.ComponentModel.DataAnnotations.Tests.RangeAttributeTests.DotDecimalExtremaAndInvalidValuesInvariantParse(type: typeof(decimal), min: "1.0", max: "3.0", value: "9.0") 
[FINISHED] Time: 4.7277696s

```

so 1.6s against 4.7s and the result is stable (TieredCompilation=0, parallel=none, local runs were made on cobalt3)

Based on JittedMethods I see that on arm64 we compile methods that we do not compile on arm32:
50 of ILStubClass::IL_STUB_InstantiatingStub;
18 of ILStubClass::IL_STUB_UnboxingStub;

Does this problem look familiar to anybody? @dotnet/jit-contrib @dotnet/arm64-contrib

**Comment by sandreenko** [comment]
The issue blocks #18886 because we do not see all failing tests in ci.

**Comment by BruceForstall** [comment]
So maybe there's a difference in what is crossgen'ed in System.Private.Corelib?

**Comment by sandreenko** [comment]
> So maybe there's a difference in what is crossgen'ed in System.Private.Corelib?

With ZapDIsabled the difference is even worse (56s against 13s).

**Comment by janvorli** [comment]
@sandreenko do you happen to know what is the ratio on Linux?

**Comment by echesakovMSFT** [comment]
@janvorli Oh, I didn't know there is a way to run on RPi3 in arm64 mode

**Comment by janvorli** [comment]
@echesakov yes, it has Quad Core 1.2GHz Broadcom BCM2837 64bit CPU and so you can install both 32 and 64 bit Linux on it.

**Comment by janvorli** [comment]
On my RPI3, the test suite mentioned above also completes significantly faster with arm32 Linux than with arm64 Linux, although the difference is smaller:
```
ARM64
   System.ComponentModel.Annotations.Tests  Total: 8, Errors: 0, Failed: 0, Skipped: 0, Time: 8.595s

ARM32:
   System.ComponentModel.Annotations.Tests  Total: 8, Errors: 0, Failed: 0, Skipped: 0, Time: 5.065s
```

**Comment by janvorli** [comment]
Although, I've just realized that the 64 bit linux I was testing uses older kernel 4.9.10 while the 32 bit uses kernel 4.14.71 and we have recently switched to implementing FlushProcessWriteBuffers using membarrier syscall on kernels >= 4.14, so it might contribute to the difference a bit too.

**Comment by sandreenko** [comment]
xperf shows that 

coreclr!COMModule::GetTypes uses 18s (exclusively) on arm64 and 5s on arm32.

I am not sure where this method (COMModule::GetTypes) is defined, https://github.com/dotnet/coreclr/blob/65918165dbeb24861f27fc96f0ccf380b13097d3/src/vm/commodule.cpp#L980-L982

does anybody know?

**Comment by AndyAyersMS** [comment]
That's where it is defined -- it delegates most of the work to `GetTypesInner` which is just below, so I would not expect much time to be spent there (modulo inlining).

It is set up this way so it can be called from managed code.

**Comment by sandreenko** [comment]
> Why do you think so? A method takes between ~0.1ms to compile on fast hardware and 1ms on slow hardware. So the times you are talking about here are between 5ms and 50ms. Orders of magnitude different from the times in #22077.

@jkotas 
From JittedMethods I see that on arm64 we compile/run 50 of ILStubClass::IL_STUB_InstantiatingStub and
18 of ILStubClass::IL_STUB_UnboxingStub that we do not compile/run on arm32.

The difference there is not in the compile time, I have checked JitTimeLogFile and it showed me that throughput is approximately the same.

So the code that we are running is slower, do these stubs have big overhead?

**Comment by sandreenko** [comment]
@AndyAyersMS I am working on it.

**Comment by sandreenko** [comment]
Ok, so my current results are:
1. the issue doesn't repro in release mode, so it is a duplicate of #17414. (I though I have seen release corefx jobs, but I can't find them no , did they exist for arm?)
2. The  part that works slower in this case is:
```
commodule::GetTypes
->commodule::GetTypesInner
--->ClassLoader::LoadTypeDefOrRefThrowing

```
3. WPR or xperf do not show some methods in the profile, in this case it was showing only `GetTypes
` as hot without information about `GetTypesInner` (that was not inlined).

I think it is reasonable to increase the timeout for our arm64 jobs until #17414 is fixed to get the full coverege.
