### ISSUE TITLE
Size regression in official build

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#22082]
Here is the size of the Microsoft.NETCore.App
3.0.0-preview-27122-01 - 74.5MB
3.0.0-preview-27317-3 - 223MB
 
Largest Files - 3.0.0-preview-27122-01
12022784 Nov 21 12:25 System.Private.CoreLib.dll
9886064 Nov 21 12:24 libcoreclr.so
8472576 Nov 22 01:26 System.Private.Xml.dll
5156352 Nov 22 01:25 System.Linq.Expressions.dll
3827752 Nov 21 12:24 libmscordaccore.so
2995112 Nov 21 12:21 libclrjit.so
2925742 Nov 21 17:29 System.IO.Compression.Native.a
2848256 Nov 22 01:25 System.Data.Common.dll
2769736 Nov 21 12:24 libmscordbi.so
2028032 Nov 22 01:26 System.Private.DataContractSerialization.dll
1344512 Nov 22 01:26 System.Linq.Parallel.dll
1328128 Nov 22 01:26 System.Net.Http.dll
1062912 Nov 22 01:26 System.Reflection.Metadata.dll
 
Largest Files - 3.0.0-preview-27317-3
87105280 Jan 17 01:31 libcoreclr.so
44616496 Jan 17 01:32 libmscordaccore.so
25415920 Jan 17 01:26 libclrjit.so
13306440 Jan 17 01:32 libmscordbi.so
8478208 Jan 17 17:33 System.Private.Xml.dll
8415232 Jan 17 01:33 System.Private.CoreLib.dll
5254656 Jan 17 17:32 System.Linq.Expressions.dll
3750840 Jan 17 01:27 libdbgshim.so
3660552 Jan 17 01:32 libsos.so
2923870 Jan 17 13:05 System.IO.Compression.Native.a
2852352 Jan 17 17:32 System.Data.Common.dll
2033664 Jan 17 17:33 System.Private.DataContractSerialization.dll
1430128 Jan 17 01:15 libcoreclrtraceptprovider.so
1385472 Jan 17 17:32 System.Net.Http.dll
1361920 Jan 17 17:32 System.Linq.Parallel.dll
1065472 Jan 17 17:33 System.Reflection.Metadata.dll

**Comment by richlander** [comment]
Ouch!!! Please fix this!

**Comment by sbomer** [comment]
Could be related to stripping symbols - investigating...

**Comment by benaadams** [comment]
That's kinda unusual; something changed with the C/C++ compiler?
```
+73 MB + 781% : libcoreclr.so              :  9,886,064 -> 87,105,280 
+39 MB +1060% : libmscordaccore.so         :  3,827,752 -> 44,616,496
+21 MB + 749% : libclrjit.so               :  2,995,112 -> 25,415,920
+10 MB + 380% : libmscordbi.so             :  2,769,736 -> 13,306,440
 -3 MB -  30% : System.Private.CoreLib.dll : 12,022,784 ->  8,415,232 
```
`System.Private.CoreLib.dll` down by 30%; but the native libs are way up

**Comment by RussKeldorph** [comment]
@sbomer Found that our new build infra doesn't pass -stripSymbols to build.sh.  I would have thought that were the default for release builds, but I guess not.

**Comment by jashook** [comment]
https://github.com/dotnet/coreclr/pull/22083
