### ISSUE TITLE
Path with forward-slashes passed to LoadUnmanagedDllFromPath cause load to fail

### ISSUE THREAD

**Issue by per-samuelsson** [dotnet/coreclr#22094]
**Describe the bug**
When a native binary in a package is defined in the `.nuspec` using *forward-slashes*, `AssemblyLoadContext.LoadUnmanagedDllFromPath()` will fail loading it.

Sample `<file>` causing this failure:

**Foo.nuspec**
```xml
<files>
  <file src="nativeassets\*.dll" target="runtimes/win-x64/native" />
</files>
```

**To Reproduce**
1. Define a NuGet package that include a native binary using the above pattern.
2. Load an assembly in an ALC that depend on the native binary and execute some code in it, e.g. using P/Invoke, and resolve specifically to the path in the NuGet cache.

**Expected behavior**
The native binary successfully load.

**Actual behavior**
The native binary fail to load.

**Screenshots**
![image](https://user-images.githubusercontent.com/2902045/51372011-13561480-1afc-11e9-98d7-86251ecd963c.png)

**Additional context**
Spent quite some time figuring out what this problem was about, and what especially fooled me was that `File.Exist(unmanagedPath)` return **true**, because that API clearly deal with mixed slashes. Then when you pass the exact same path on to `AssemblyLoadContext.LoadUnmanagedDllFromPath(path)`, it will raise the above exception.

Tested only on

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed
```

**Comment by danmosemsft** [comment]
Thanks for reporting. Generally can you please paste stack traces in as text? It makes it searchable for others.

**Comment by per-samuelsson** [comment]
> Generally can you please paste stack traces in as text? It makes it searchable for others.

Most definitely. Sorry. This one was from an integration test on one of our build servers, so just did what was easiest at the moment.
