### ISSUE TITLE
Failed to compile CoreCLR when VS 2019 is installed

### ISSUE THREAD

**Issue by ayende** [dotnet/coreclr#22103]
I'm running the `build.cmd` from `Developer Command Prompt for VS 2017` console ,and I get a compilation error

```
c:\work\coreclr\src\vm\amd64\virtualcallstubcpu.hpp(589): error C2057: expected constant expression (compiling source
 file C:\Work\coreclr\src\vm\virtualcallstub.cpp) [C:\Work\coreclr\bin\obj\Windows_NT.x64.Debug\src\vm\wks\cee_wks.vc
xproj]
```

I'm pretty sure that I followed the Windows build instructions. i looked at the line:

https://github.com/dotnet/coreclr/blob/master/src/vm/amd64/virtualcallstubcpu.hpp#L589

And it _looks_ fine.  The values there are defined here: 
https://github.com/dotnet/coreclr/blob/master/src/vm/amd64/virtualcallstubcpu.hpp#L185-L186

**Comment by benaadams** [comment]
I have to comment out line 589 to get it to build
```cpp
static_assert_no_msg((DispatchStubLong_offsetof_failLabel - DispatchStubLong_offsetof_failDisplBase) < INT8_MAX);
```

:-/

**Comment by ayende** [comment]
Okay, as long as it isn't just me, I was worried that was something in my env.

**Comment by kouvel** [comment]
Maybe a compiler version difference or something else. Can you send me the output of `cl -version` from that prompt? I'll try to repro and take a look.

**Comment by ayende** [comment]
```
C:\Work\coreclr>cl -version
Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25834 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-version'
cl : Command line error D8003 : missing source filename
```

**Comment by kouvel** [comment]
Looks like I'm on a more recent compiler:
`Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x64`

Are there updates available to install for VS? It may have been a bug that was fixed. Meanwhile I'll see if something can be done to avoid the error.

**Comment by ayende** [comment]
This probably came because I installed the VS 2019 preview.

**Comment by kouvel** [comment]
I'd have to check with VS 2019 preview but I don't see how the expression in the code would not be a constexpr. All of the components in the expression should be constexprs. So far anyway, it looks more like a bug than a conformance issue. Also not sure why the VS 2019 preview compiler would have a lower version than mine which is the latest updated VS 2018.

**Comment by benaadams** [comment]
I get it with
```
>cl -version
Microsoft (R) C/C++ Optimizing Compiler Version 19.20.27027.1 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
```

**Comment by benaadams** [comment]
Both @ayende and I seem to be reporting `x86` and @kouvel is reporting `x64` however

**Comment by kouvel** [comment]
I haven't been able to build coreclr with VS 2019 yet, I'm probably missing some setup steps. Working around it for now by changing the static assert into a dynamic assert.

**Comment by tannergooding** [comment]
@kouvel. Shouldn't we have an issue tracking the workaround? TODO comments tend to get lost and forgotten about when they dont have an associated work item.

**Comment by kouvel** [comment]
Yea true, I'll keep this one open

**Comment by jkotas** [comment]
Building with VS2019 worked fine for a while now.
