### ISSUE TITLE
Cannot open project System.Private.CoreLib

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/coreclr#22132]
Hi,

I'm unable to open the project System.Private.CoreLib in VS 15.9.5.
When I try to do so, I get the following error:

> D:\Users\Shimmy\Source\Repos\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj : error  : The imported project "D:\Users\Shimmy\Source\Repos\coreclr\Tools\Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.CSharp.CurrentVersion.targets

**Comment by jkotas** [comment]
Build the repo from command line once first. It will open fine after that.

Would you be interested in submitting PR to improve the docs to make this clear?

**Comment by weitzhandler** [comment]
> Build the repo from command line once first. It will open fine after that.

That worked. Thank you!

> Would you be interested in submitting PR to improve the docs to make this clear?
First of all, once this issue is around, people might bump into it in the future and benefit from it. But I wouldn't mind updating the docs, it's just that I'm not sure where in the docs this should be addressed.
