### ISSUE TITLE
Microbenchmarks should run with tiered JITing enabled

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#22134]
From https://github.com/dotnet/coreclr/issues/22128#issuecomment-456513621

Microbenchmarks runs are done with tiered JITing disabled. It means that they are not measuring performance that our customers are going to see in the default configuration.

We should have microbenchmarks run with the default configuration (ie tiered JITing enabled).

**Comment by RussKeldorph** [comment]
@billwert @adamsitnik Is this already covered in dotnet/performance?  If not, will it be?

**Comment by adamsitnik** [comment]
In the old perf lab, the tiered JIT was always disabled.

At the end of February, we have added runs for tiered and non-tiered micro benchmark runs to the performance repo https://github.com/dotnet/performance/pull/340 Initially, the gap was huge for some of the benchmarks with "hot loops"

After @kouvel has merged https://github.com/dotnet/coreclr/pull/23599 the gap dissapeared.

![obraz](https://user-images.githubusercontent.com/6011991/59515574-b8182a80-8ebf-11e9-93ab-216eeeffadea.png)

The current status is that we are replacing the "Tiered" and "non-Tiered" runs with single run with default settings: https://github.com/dotnet/performance/pull/561

**Comment by RussKeldorph** [comment]
@adamsitnik Thanks!
