### ISSUE TITLE
Support Edit and Continue in generic context

### ISSUE THREAD

**Issue by tmat** [dotnet/coreclr#22140]
Currently it is not possible to edit a generic method or add or update any method in a generic type. 

Inability to apply edits in generic context is mainly limitation of the runtime. The compiler is capable of emitting the correct IL delta. The debugger also might need some work.

Limitations like this result in decreased productivity and thus dissatisfaction of customers that use EnC for fixing issues in complex apps that take a lot of effort to get to the state where the issue reproduces. See https://github.com/dotnet/roslyn/issues/27976 for an example of customer feedback.

**Comment by tommcdon** [comment]
Looks like a duplicate to #19829
