### ISSUE TITLE
dotnet restore hangs inside a docker container

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/coreclr#2215]
[dotnet restore](https://github.com/dotnet/cli/blob/master/Documentation/intro-to-cli.md#experience-) command in the new [dotnet/CLI](https://github.com/dotnet/cli) tools.

It happens only inside a docker container.

**Comment by janvorli** [comment]
Fixed by #2528

**Comment by TheRubble** [comment]
I'm currently fighting with this issue. Also happens during dotnet run, gets stuck after the compiling xxx for .NetCoreApp,Version=v1.0
