### ISSUE TITLE
[Windows] GC\API\GC\Collect0 fails with GCStress=0xc

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#22170]
It started to fail in different jobs ([x86_gcstess0xc_zapdisable](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable/112/testReport/junit/GC_API/_GC_Collect0_Collect0_/_GC_Collect0_Collect0_cmd/), or [x64_gcstress0xc](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc/125/testReport/junit/GC_API/_GC_Collect0_Collect0_/_GC_Collect0_Collect0_cmd/)).

Output looks like:
```
         "D:\j\workspace\x64_checked_w---fbaae03b\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" Collect0.exe 
        Array is in generation: 0
        Object is in generation: 0
        Collect(0)
        Array is in generation: 1
        Object is in generation: 2
        Test for GC.Collect(0) failed!
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
```

**Comment by sandreenko** [comment]
I think that it could be introduced by #21782, @janvorli , @Maoni0 could you please take a look?

I was not able to repro it locally but I saw this test failed in many legs.

**Comment by Maoni0** [comment]
I don't think this can possibly be related to #21782 which only affects collectible types. 

this test can rightfully fail during GC stress 0xc where a GC could be triggered between these 2 lines:
```csharp
		int agen2 = GC.GetGeneration(array);
		int ogen2 = GC.GetGeneration(obj);
```
in which case both objects could be promoted to gen2. agen2 could still say 1 because at that point both objects were in gen1. 

this test should not be run under gcstress... I'll make it GCStressIncompatible.

**Comment by Maoni0** [comment]
#22175

**Comment by sandreenko** [comment]
> this test should not be run under gcstress... I'll make it GCStressIncompatible.

As I see [Collect1 ](https://github.com/dotnet/coreclr/blob/master/tests/src/GC/API/GC/Collect1.cs) also fails from time to time: [example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable/112/testReport/junit/GC_API/_GC_Collect1_Collect1_/_GC_Collect1_Collect1_cmd/). 


And the issue is not GCStress itself, 

https://github.com/dotnet/coreclr/blob/e8652c69d6c0fbfbeed5e68b4d83d039d6217796/tests/src/GC/API/GC/Collect1.cs#L13-L17

after this code `GC.GetGeneration(array)` must be `> 0`, but as we see from https://github.com/dotnet/coreclr/blob/e8652c69d6c0fbfbeed5e68b4d83d039d6217796/tests/src/GC/API/GC/Collect1.cs#L29
the test output:
```
       "D:\j\workspace\x86_checked_w---34329519\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" Collect1.exe 
        Array is in generation: 0
        Object is in generation: 0
        Collect(1)
        Array is in generation: 0 <- that is wrong, it must be 2+.
        Object is in generation: 2
        Test for GC.Collect(1) failed!
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
```

it is still 0 in this test case.

So I am not sure that #22175 is the right fix, but if it is then we need the same fix for Collect1.

**Comment by Maoni0** [comment]
how was collect1 run? was it run inside a process with other tests? if so those other tests can certainly trigger GCs and we are back to a situation similar to GCStress.

> Array is in generation: 0 <- that is wrong, it must be 2+.

nothing says Array must be 2 (there's no +). we may decide to not promote.

in general these checking generation tests are of low value. and I definitely would not run collect0 under GCStress 'cause it makes no sense for reasons I mentioned above.

**Comment by sandreenko** [comment]
As we discussed the right solution is to disable Collect1 as well, the issue can happen if the first
https://github.com/dotnet/coreclr/blob/aab30e3248b882ecad122127f3d60a2ce9ea14a6/tests/src/GC/API/GC/Collect1.cs#L17
decides not to promote `array`.
then https://github.com/dotnet/coreclr/blob/aab30e3248b882ecad122127f3d60a2ce9ea14a6/tests/src/GC/API/GC/Collect1.cs#L24
doesn't promote anything (because gen1 is empty)
so both `array` and `obj`  stay in gen0 when we ask for array generation:
https://github.com/dotnet/coreclr/blob/aab30e3248b882ecad122127f3d60a2ce9ea14a6/tests/src/GC/API/GC/Collect1.cs#L26-L27
but if 2  `GC.Collect()` happen between there 2 lines then `obj` will be moved to gen2 and we will see such output.
