### ISSUE TITLE
Unspecified error in dir.traversal.targets during test build on perf hardware

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#22179]
failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x86_min_opt_ryujit/1156/

failed log: 
[WS-CLEANUP] Deleting project workspace...Cannot delete workspace :remote file operation failed: C:\j\w\perf_perflab_---ce30617b at hudson.remoting.Channel@4268bdb7:JNLP4-connect connection from 131.107.147.125/131.107.147.125:46715: java.io.IOException: Unable to delete 'C:\j\w\perf_perflab_---ce30617b\Tools\net46\roslyn\tools\Microsoft.DiaSymReader.Native.amd64.dll'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
ERROR: Step �Delete workspace when build is done� failed: Cannot delete workspace: remote file operation failed: C:\j\w\perf_perflab_---ce30617b at hudson.remoting.Channel@4268bdb7:JNLP4-connect connection from 131.107.147.125/131.107.147.125:46715: java.io.IOException: Unable to delete 'C:\j\w\perf_perflab_---ce30617b\Tools\net46\roslyn\tools\Microsoft.DiaSymReader.Native.amd64.dll'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
Finished: FAILURE

**Comment by adiaaida** [comment]
It is unclear what the actual error is, but this appears to be a test build failure as we are seeing this:

C:\j\w\perf_perflab_---ce30617b\tests\dir.traversal.targets(25,5): error : (No message specified) [C:\j\w\perf_perflab_---ce30617b\tests\src\dirs.proj]

@RussKeldorph

**Comment by adiaaida** [comment]
This seems to have started with @janvorli's change #22064. We are failing with an unspecified error during the test build, but only on the perfsnake machines.

**Comment by RussKeldorph** [comment]
Fixed by #22496
