### ISSUE TITLE
[osx] Clean up compiler warnings in the PAL

### ISSUE THREAD

**Issue by kangaroo** [dotnet/coreclr#222]
There is a large usage of deprecated API in the PAL (specifically in locale) right now that need cleaning up and modernizing.

**Comment by kangaroo** [comment]
I've started some of this work here:

https://github.com/kangaroo/coreclr/tree/warning-clean

Cleaning up the usage of CFGregorianData and deprecated CFURL functions are the biggest remaining pieces.

**Comment by kangaroo** [comment]
PR for part 1 here:

https://github.com/dotnet/coreclr/pull/223

Can someone add up-for-grabs for the CFGregorianData and CFURL pieces?

**Comment by sergiy-k** [comment]
Hi @kangaroo, I think we can remove pretty much most of that stuff from PAL. Globalization should be removed for sure (System.Globalization.dll no longer calls into libcoreclr so there is no dependency on PAL). As far as I remember, the only thing we need to do in PAL is to convert strings (WideCharToMultiByte and MuliByteToWideChar) and I think that's it (but I need to look at the code to double check this).

**Comment by ellismg** [comment]
Yes.  We should rip most of the stuff out of locale.cop.  I will do a pass tomorrow.  The plan is to not call into the VM for this stuff anymore.

**Comment by kangaroo** [comment]
With the locale stuff ripped out there are two remaining tasks on this issue:

'''
/Users/plasma/Work/dotnet/ports/osx/src/pal/src/misc/version.cpp:69:24: warning: 'CFURLCreateDataAndPropertiesFromResource' is deprecated: first deprecated in OS X 10.9 - For resource data, use the CFReadStream API. For file resource properties, use
      CFURLCopyResourcePropertiesForKeys. [-Wdeprecated-declarations]
    Boolean fCreated = CFURLCreateDataAndPropertiesFromResource(kCFAllocatorDefault, 
                       ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFURLAccess.h:47:9: note: 'CFURLCreateDataAndPropertiesFromResource' has been explicitly marked deprecated here
Boolean CFURLCreateDataAndPropertiesFromResource(CFAllocatorRef alloc, CFURLRef url, CFDataRef *resourceData, CFDictionaryRef *properties, CFArrayRef desiredProperties, SInt32 *errorCode) CF_DEPRECATED(10_0, 10_9, 2_0, 7_0, "For resource data, use the CFReadStream AP...
        ^
/Users/plasma/Work/dotnet/ports/osx/src/pal/src/misc/version.cpp:76:41: warning: 'CFPropertyListCreateFromXMLData' is deprecated: first deprecated in OS X 10.10 - Use CFPropertyListCreateWithData instead. [-Wdeprecated-declarations]
    CFPropertyListRef systemVersPlist = CFPropertyListCreateFromXMLData(kCFAllocatorDefault, 
                                        ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:38:19: note: 'CFPropertyListCreateFromXMLData' has been explicitly marked deprecated here
CFPropertyListRef CFPropertyListCreateFromXMLData(CFAllocatorRef allocator, CFDataRef xmlData, CFOptionFlags mutabilityOption, CFStringRef *errorString) CF_DEPRECATED(10_0, 10_10, 2_0, 8_0, "Use CFPropertyListCreateWithData instead.");
                  ^
'''

and

'''
/Users/plasma/Work/dotnet/ports/osx/src/pal/src/exception/machmessage.cpp:29:1: warning: unused variable 'defdbgchan' [-Wunused-const-variable]
SET_DEFAULT_DEBUG_CHANNEL(EXCEPT);
^
/Users/plasma/Work/dotnet/ports/osx/src/pal/src/include/pal/dbgmsg.h:235:33: note: expanded from macro 'SET_DEFAULT_DEBUG_CHANNEL'
    static const DBG_CHANNEL_ID defdbgchan = DCI_##x
                                ^
1 warning generated.
'''

**Comment by ellismg** [comment]
I'll take a look at these.  Thanks @kangaroo.

**Comment by sergiy-k** [comment]
I think we can just remove both the function in version.cpp and the macro in machmessage.cpp.

**Comment by kangaroo** [comment]
@sergiy-k I think so to, they both looked safe to kill

**Comment by kangaroo** [comment]
@ellismg Sorry, the warnings were bugging me so I just cleaned them up.

**Comment by jkotas** [comment]
#348
