### ISSUE TITLE
Dump process stack under macOS and Linux

### ISSUE THREAD

**Issue by pepone** [dotnet/coreclr#22209]
Hi,

I looking for a way to get a backtrace of all threads from a running .NET Core process , similar to gdb `thread apply all bt` or lldb `bt all` commands

Is there support to get that info from macOS or Linux?

**Comment by danmosemsft** [comment]
Yes, `sos` works on Mac and Linux. Please see https://github.com/dotnet/diagnostics.

**Comment by danmosemsft** [comment]
This issue was moved to dotnet/diagnostics#118
