### ISSUE TITLE
Handling for custom modifiers Microsoft.VisualC.NeedsCopyConstructorModifier and System.Runtime.IsCopyConstructed is not correct

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/coreclr#22219]
CoreCLR is missing the BlittableValueClassWithCopyCtorMarshaller

The logic in NDirect::MarshalingRequired doesn't detect marshalling needed cases for ByRef parameters. Currently it only implements the logic for Ptr parameters.

**Comment by AaronRobinsonMSFT** [comment]
We are going to need this for any CLI support so I am putting it in the 3.0 milestone.

cc @jeffschwMSFT @jkoritzinsky
