### ISSUE TITLE
[corefx][jitminopts] System.Buffers.Text.Tests.FormatterTests.TestFormatterDecimal regression

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#22215]
[ci example1](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_minopts/lastCompletedBuild/testReport/), [ci example2](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs8/lastCompletedBuild/).

There were no recent test changes so it is probably an issue on our side.

**Comment by filipnavara** [comment]
I remember seeing some PR with changes to decimal formatting... @tannergooding?

**Comment by sandreenko** [comment]
cc @dotnet/jit-contrib

**Comment by filipnavara** [comment]
https://github.com/dotnet/coreclr/pull/22070 ?

**Comment by tannergooding** [comment]
Yes, we reverted an earlier change and negative zero is once again being formatted as `0.0`. This will require a fixup in CoreFX after the change pumps over.

CC. @pentp, @jkotas

**Comment by sandreenko** [comment]
thanks @filipnavara!

@tannergooding any reasons why we see the issue only in minopts/stress?

**Comment by sandreenko** [comment]
Fixed by #22254
