### ISSUE TITLE
Global Date Format

### ISSUE THREAD

**Issue by ZackTech** [dotnet/coreclr#22210]
I am developing an Asp.net Core version 2 Web Api and Web Front End. In one of my entry forms I am using a Boostrap date picker. When I run the application on my own PC even connected to the Azure database everything runs normally. On Azure when the model validates server side I get Invalid Date Format. I think server side it has decided to use the US date format.

Is there a global setting I can set just once which I can set it to use UK format irrespective of what hardware the software is sitting on. If that does not exist can we please have one?

**Comment by RussKeldorph** [comment]
@tarekgh

**Comment by tarekgh** [comment]
@ZackTech I am not that familiar with Bootstrap date picker but can't you set your preferred locale when using the picker? 

```Xml
<div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker2'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker2').datetimepicker({
                    locale: 'en-GB'
                });
            });
        </script>
    </div>
</div>
```

Something else you may try is doing the following in your startup code:
```C#
CultureInfo ci = CultureInfo.GetCultureInfo("en-GB");
CultureInfo.DefaultThreadCurrentCulture = ci;
CultureInfo.CurrentCulture = ci;
```

These will force using en-GB as default culture for date formatting and parsing.

**Comment by tarekgh** [comment]
I found some useful thread which may help too https://stackoverflow.com/questions/19382189/change-language-for-bootstrap-datetimepicker

**Comment by tarekgh** [comment]
@ZackTech I am closing the issue but feel free to reply back with any more questions and we'll be happy to help.

**Comment by ZackTech** [comment]
As for your suggestion, been there, done that, got the T-Shirt! Doesn't fix the problem!!

I found this thread on stackoverflow.
https://stackoverflow.com/questions/44688311/how-to-set-culture-for-date-binding-in-asp-net-core

This is the code that I have added to Startup.cs in the Web Front End is:

var supportedCultures = new[] { new CultureInfo("en-GB") };
        app.UseRequestLocalization(new RequestLocalizationOptions
        {
            DefaultRequestCulture = new RequestCulture("en-GB"),
            SupportedCultures = supportedCultures,
            SupportedUICultures = supportedCultures
        });

Not sure if it should also go in the Web Api too?

The hours I seem to waste constantly fighting the annoying US date format is just untrue.
There has just got to be a better way to dealing with this sort of issue.

Lastly before you close an issue I think you need to make sure you have actually addressed the issue and fixed it if at all possible (which your answer didn't!).

**Comment by tarekgh** [comment]
@Eilon do you have any suggestion for @ZackTech from ASP.NET side?

> Lastly before you close an issue I think you need to make sure you have actually addressed the issue and fixed it if at all possible (which your answer didn't!).

Closing the issue doesn't mean we'll not respond to you. I reactivated the issue if this make a difference to you.
