### ISSUE TITLE
CoreCLR Build Failure - Windows

### ISSUE THREAD

**Issue by clrjunky** [dotnet/coreclr#2221]
1.	New Win10 Pro Machine (All Update Applied)
2.	Installed VS2013 Pro (All Updates Applied)
3.	Installed VS2015 Community (All Updated Applied)
4.	Installed Git (Git-2.6.3-64-bit, https://git-scm.com/download/win)
5.	Installed CMAKE (cmake-3.4.1-win32-x86.exe, https://cmake.org/download)
6.	C:\git>git clone https://github.com/dotnet/coreclr
7.	C:\git>git clone https://github.com/dotnet/corefx
8.	C:\git\coreclr>git config --global core.autocrlf true
9.	C:\git\corefx>git config --global core.autocrlf true
10.	Downloaded https://nuget.org/nuget.exe
11.	Added C:\nuget to system path
12.	Developer Command Prompt for VS 2015:

C:\git\coreclr>build x64 Debug Clean skiptestbuild
Commencing CoreCLR Repo build

Doing a clean build

Could Not Find C:\git\coreclr\bin\Logs\*_Windows_NT__x64__Debug.*
Checking pre-requisites...

Commencing build of native components for Windows_NT.x64.Debug

'"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\..\..\VC\vcvarsall.bat"' is not recognized as an internal or external command,
operable program or batch file.
CMake Error at CMakeLists.txt:5 (project):
  Could not find an appropriate version of the Windows 10 SDK installed on
  this machine

-- Configuring incomplete, errors occurred!
See also "C:/git/coreclr/bin/obj/Windows_NT.x64.Debug/CMakeFiles/CMakeOutput.log".
Failed to generate native component build project

**Comment by shahid-pk** [comment]
try to build it from normal console not developer.

**Comment by clrjunky** [comment]
Normal Console:

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\git\coreclr>build x64 Debug Clean skiptestbuild
Commencing CoreCLR Repo build

Doing a clean build

Could Not Find C:\git\coreclr\bin\Logs\*_Windows_NT__x64__Debug.*
Checking pre-requisites...

Commencing build of native components for Windows_NT.x64.Debug

'"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\..\..\VC\vcvarsall.bat"' is not recognized as an internal or external command,
operable program or batch file.
Error: DIA SDK is missing at "DIA SDK". This is due to a bug in the Visual Studio installer. It does not install DIA SDK at "" but rather at VS install location of previous version. Workaround is to copy DIA SDK folder from VS install location of previous version to "" and then resume build.
Visual Studio 2013 Express does not include the DIA SDK. You need Visual Studio 2013+ (Community is free).
See: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/developer-guide.md#prerequisites

**Comment by mikedn** [comment]
> '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\....\VC\vcvarsall.bat"' is not recognized as an internal or external command,

Do you have Visual C++ installed?

**Comment by clrjunky** [comment]
@mikedn Thanks, forgot it's not included in the default VS2015 install.
I added it and the build ok.
