### ISSUE TITLE
[Linux] DllImport should invoke with RTLD_GLOBAL flag

### ISSUE THREAD

**Issue by BlackCentipede** [dotnet/coreclr#22227]
The CoreCLR behavior seems to be behaving as if library is loaded as RTLD_LOCAL despite the fact that the actual code resolves them with RTLD_LAZY flag when using dlopen. This causes some difficulty of using CoreCLR for P/Invoke code that since current P/Invoke API currently cannot access global library variables (at least cleanly), we would normally use dlopen/dlsym to access the global library variables. The problem is that it behaves in a way that it seems as if there are 2 instances of the same library. It has persisted for more than 2 years now.

I've written a minimal reproduction code that can be tested on Mono and CoreCLR:
https://github.com/BlackCentipede/PinvokeBug

To test, simply run `dotnet run` and `clang -std=c99 -shared -fPIC -olibTest.so Test.c && mcs Program.cs && mono Program.exe` under TestPInvoke directory.

Dotnet Core would print the following:

![dotnetcorebug](https://user-images.githubusercontent.com/9369939/51781366-e8a82500-20d4-11e9-8258-35f9988b83d0.png)

And Mono Runtime would print the following:
![mono](https://user-images.githubusercontent.com/9369939/51781370-f493e700-20d4-11e9-9175-efac34457e14.png)

This is tested on Dotnet Core 2.2.102 and Mono 5.16.0.

**Comment by jkotas** [comment]
This issue was discussed in https://github.com/dotnet/coreclr/pull/18628 . 

`RTLD_GLOBAL` will make some libraries work, but it will break others. There is no one right default. We have chosen `RTLD_LOCAL` to be the default since others (e.g. Python) made the same choice. Also, it matches the behavior on Windows - there is not even concept of global on Windows.

We have introduced a callback in .NET Core 3.0 that allows customizing how the libraries are loaded for DllImport: `NativeLibrary.SetDllImportResolver`. More details are in https://github.com/dotnet/corefx/issues/32015.

@swaroop-sridhar Do you happen to have a sample how one can use `NativeLibrary.SetDllImportResolver` to load with `RTLD_GLOBAL` ?

**Comment by tannergooding** [comment]
> Also, it matches the behavior on Windows - there is not even concept of global on Windows.
@jkotas, this is not the case.

`LoadLibrary` (and `LoadLibraryEx`, by extension) ref counts modules on a per-process basis and Windows (see https://docs.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-loadlibraryw#remarks for more details), using the same code will return (as it does on Mono for `dlopen`):
```
1
2
3
```

Here is an end-to-end sample showing the behavior on Windows: [repro.zip](https://github.com/dotnet/coreclr/files/2798558/repro.zip)

**Comment by tannergooding** [comment]
Additionally, when using `LoadLibraryEx`, it is possible to explicitly load multiple instances of a given module by specifying it is a datafile or image resource. In this scenario, it does not call DllMain and you must do that (and similar setup) yourself (this is similar to the LOCAL loading state in dlopen).

**Comment by jkotas** [comment]
> ref counts modules on a per-process basis

@tannergooding This has not much to do with refcounting or loading multiple instance of the same .dlls.

On Unix, there is basically a process global hashtable of all exported symbols. When a shared library is loaded using `RTLD_GLOBAL`, its symbols are added to this hashtable and other shared libraries can resolve them, without specifying where the symbol should come from in its import tables.

**Comment by swaroop-sridhar** [comment]
>> Do you happen to have a sample how one can use NativeLibrary.SetDllImportResolver to load with RTLD_GLOBAL ?

Here's a sample: 
```C#
using System.Runtime.InteropServices;

void Test()
{
    DllImportResolver resolver =
        (string libraryName, Assembly asm, DllImportSearchPath? dllImportSearchPath) =>
             Interop.Libdl.dlopen(libraryName, RTLD_GLOBAL);

    NativeLibrary.SetDllImportResolver(Assembly.GetExecutingAssembly();, resolver);

   // .. Then try the pInvoke ... 
}
```
