### ISSUE TITLE
How to deal with errors when porting 4.5 code to core 5.0

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#2222]
I am trying to compile a 4.5 project for core 5.0.

I get a ton of errors, some example:
- The name 'Thread' does not exist in the current context
- The name 'AppDomain' does not exist in the current context
- The name 'TimeZone' does not exist in the current context
- 'Uri' does not contain a definition for 'HexEscape'
- 'Type' does not contain a definition for 'GetTypeCode'
- AssemblyBuilderAccess' does not contain a definition for 'RunAndSave'
- 'Type' does not contain a definition for 'IsInterface' and no extension method 'IsInterface' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
- 'TypeBuilder' does not contain a definition for 'CreateType' and no extension method 'CreateType' accepting a first argument of type 'TypeBuilder' could be found (are you missing a using directive or an assembly reference?)
- 'Type' does not contain a definition for 'GetCustomAttributes' and the best extension method overload 'CustomAttributeExtensions.GetCustomAttributes(MemberInfo, Type, bool)' requires a receiver of type 'MemberInfo'
- 'Socket' does not contain a definition for 'Handle' and no extension method 'Handle' accepting a first argument of type 'Socket' could be found (are you missing a using directive or an assembly reference?)
- 'BindingFlags' does not contain a definition for 'ExactBinding'

Some of these errors should be solvable by adding project.json dependencies.
Other errors are not implemented yet. And yet others will never be implemented.

So I wonder about a few things:
- how do I figure out which dependencies to add?
- how can I know what functionality isn't available today?
- how can I know what functionality isn't planned to be available (in the foreseeable future)?
- how can I match the version I am using to the source repos online (e.g. what code is in System.Runtime, Version=4.0.21.0)?
- when I look inside the source repos, I see some of the things I get errors about are present (e.g. [ExactBinding](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Reflection/BindingFlags.cs#L53), [GetCustomAttributes](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Reflection/MemberInfo.cs#L53), [CreateType](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Reflection/Emit/TypeBuilder.cs#L2246)). So why do I get the errors?

Thanks

**Comment by afscrome** [comment]
http://packagesearch.azurewebsites.net/ Is a useful site to work out what packages a type / method has moved to.

For the Properties on Type, many of them have moved from Type to TypeInfo, which can be obtained by calling GetTypeInfo() on a type.

**Comment by tmds** [comment]
@afscrome I managed to get rid of a bunch of errors using the website and TypeInfo.

Where are [GetTypeCode](https://msdn.microsoft.com/en-us/library/system.type.gettypecode(v=vs.110).aspx) and [PlatformID](https://msdn.microsoft.com/en-us/library/3a8hyw88(v=vs.110).aspx) on the CoreCLR?

**Comment by mellinoe** [comment]
GetTypeCode was removed, but PlatformID has a work-in-progress replacement here:

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices.RuntimeInformation/ref/System.Runtime.InteropServices.RuntimeInformation.cs

It's available in the System.Runtime.InteropServices.RuntimeInformation package.

**Comment by tzwlai** [comment]
@joshfree, could you help reassign this please?

**Comment by tmds** [comment]
From my original question, I think it is useful these questions are answered:
* how do I figure out which dependencies to add?
* how can I match the version I am using to the source repos online (e.g. what code is in System.Runtime, Version=4.0.21.0)?

For other specific errors, I can google/stackoverflow/create an issue.

**Comment by weshaggard** [comment]
@bleroy you are planning to write some docs on this subject, these are some good questions to cover.

**Comment by tmds** [comment]
Nice article about porting: https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core/

Encountering a new porting issue:
```
The type or namespace name 'NetworkInterface' does not exist in the namespace 'System.Net.NetworkInformation' (are you missing an assembly reference?)
The type or namespace name 'NetworkAddressChangedEventHandler' could not be found (are you missing a using directive or an assembly reference?)
```

Adding System.Net.NetworkInformation as a dependency gives me an error:
```
error: Unable to resolve System.Net.NetworkInformation (>= 4.1.0-beta-23516) for DNXCore,Version=v5.0.
```
This is what I have in my project.json
```
"dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23728",
        "System.Net.NetworkInformation": "4.1.0-beta-23516"
    },
    "frameworks": {
        "dnxcore50": { }
    }

```
How can I fix this?

**Comment by terrajobst** [comment]
@tmds 

Besides using ApiPort and Package Search, here are concrete answers to your questions:

> The name 'Thread' does not exist in the current context

You need to reference the NuGet package `System.Threading.Thread`.

> The name 'AppDomain' does not exist in the current context

AppDomain isn't available on .NET Core. For isolating assemblies, use `AssemblyLoadContext`.

> The name 'TimeZone' does not exist in the current context

The replacement is `TimeZoneInfo`.

> 'Uri' does not contain a definition for 'HexEscape'

I believe there is no replacement.

> 'Type' does not contain a definition for 'GetTypeCode'

Will be added back.

> AssemblyBuilderAccess' does not contain a definition for 'RunAndSave'

AFAIK we no longer support using RefEmit for emitting assemblies to disk. Is there a reason you need to persist the assembly?

> 'Type' does not contain a definition for 'IsInterface' and no extension method 'IsInterface' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

Use `type.GetTypeInfo().IsInterface`.

> 'Type' does not contain a definition for 'GetCustomAttributes' and the best extension method overload 'CustomAttributeExtensions.GetCustomAttributes(MemberInfo, Type, bool)' requires a receiver of type 'MemberInfo'

Use `type.GetTypeInfo().GetCustomAttributes()`.

> 'TypeBuilder' does not contain a definition for 'CreateType' and no extension method 'CreateType' accepting a first argument of type 'TypeBuilder' could be found (are you missing a using directive or an assembly reference?)

Use `typeBuilder.CreateTypeInfo()` instead.

> 'Socket' does not contain a definition for 'Handle' and no extension method 'Handle' accepting a first argument of type 'Socket' could be found (are you missing a using directive or an assembly reference?)

AFAIK we removed all `Handle` properties that used `IntPtr` instead of `SafeHandle`.

@stephentoub @SidharthNabar What's the replacement?

> 'BindingFlags' does not contain a definition for 'ExactBinding'

It looks we don't plan on adding this enum member back. The replacement should just be to remove it from the flags. @pallavit?

**Comment by tmds** [comment]
@terrajobst 
Updated question in [this comment](https://github.com/dotnet/coreclr/issues/2222#issuecomment-171869337) 
Currently I am strugging with System.Net.NetworkInformation, see [this comment](https://github.com/dotnet/coreclr/issues/2222#issuecomment-185115470)

**Comment by mellinoe** [comment]
Could you try referencing a newer version of System.Net.NetworkInformation? For example, try version `4.1.0-rc3-23728` as it's from the say day as your NETStandard.Library package.

**Comment by tmds** [comment]
@mellinoe I am able to restore the package now. I was missing the nuget feed, so I copied it over from a 'dotnet new'-project. I didn't notice at first because I managed to get the NETStandard.Library (which was cached on my system).
Thanks

**Comment by tmds** [comment]
@bleroy, @weshaggard can I close this issue?

**Comment by weshaggard** [comment]
Yes I think the recent blog post https://blogs.msdn.microsoft.com/dotnet/2016/02/23/porting-msbuild-to-net-core/ covers the general approach and @terrajobst answered most of your specific questions. If you have other questions please feel free to file another issue.
