### ISSUE TITLE
CopyToAsync default buffer size very high

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#2223]
[`Stream.CopyToAsync`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Stream.cs#L125) without a specified buffer size will use [`_DefaultCopyBufferSize = 81920`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Stream.cs#L48) which is a pretty sizeable buffer 

~~for anything to have completed sync so unless the stream being read from always has the same amount buffered [each loop](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Stream.cs#L165-L168) will need to return a different `Task` with a different value.~~

~~So you may experience perf gains by specifying a much smaller buffer size; as it could then return a cached `Task<int>` on each read.~~

~~Assuming the following was true for the read stream (else you'd just be increasing call count for no gain)~~
~~* The underlying stream is continuing to buffer between calls to `ReadAsync`~~
~~* `ReadAsync` doesn't wait till the buffer is completely full before returning - e.g. a network type stream I'd hope wouldn't wait for a 82kB buffer to fill before returning~~

@stephentoub point below about GC is a much better one.

(From: https://github.com/dotnet/corefx/issues/4708#issuecomment-160798119)

**Comment by stephentoub** [comment]
> so unless the stream being read from always has the same amount buffered each loop will need to return a different Task with a different value. So you may experience perf gains by specifying a much smaller buffer size; as it could then return a cached Task<int> on each read

In a Stream like MemoryStream this doesn't make a difference for the Task-caching optimization because all of the data is already available.  In a Stream like FileStream this doesn't make a difference (unless you've explicitly created the buffer size for the FileStream to be greater than 80K) as FileStream will skip its buffer entirely in that case.  Did you have a particular stream implementation in mind for this particular comment?  In most streams, once the implementation decides not to use the internal buffer, you're not going to be on a fast path that lets you reuse a task anyway, so I don't know that this is really an issue.  Can you point to a particular case where you believe this is a problem?

> Stream.CopyToAsync without a specified buffer size will use _DefaultCopyBufferSize = 81920

My previous comments are unrelated to the title of your issue, though, which is that CopyToAsync is using a very large default buffer size.  I believe @vancem was involved in choosing that value, so he might be able to speak to it.  I can see how it could be beneficial in the CopyTo case, as if you expect most copies to be quick then the buffer is likely to be collected in gen0, and it's likely a better optimization to minimize the number of reads/writes than to use a smaller buffer.  However, CopyToAsync is likely to involve asynchrony, which is likely to involve longer periods of time, with a higher chance of the buffer getting promoted.  So I'm somewhat skeptical a buffer of this large size is the best default for CopyToAsync even if it is for CopyTo.

**Comment by benaadams** [comment]
I will admit it may be me at fault as a library author for my own streams; as I've always seen `CopyToAsync` as a "for free" implementation. However, the streams can be inherited and overridden, and it can be overridden in my own streams to use a different default; but its only from looking into the coreclr code that I realised it was so large. (The sync default doesn't bother me)

Probably as you rightly point out a larger issue would be the size and lifetime with respect to GC; as we set up many medium lifetime stream translator/converter/filters (like gzip or ssl would be) that use a similar pattern to that used in Kestrel (https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Filter/FilteredStreamAdapter.cs#L31-L34) where the CopyToAsync is essentially a continuous process; rather than a one off operation.

**Comment by benaadams** [comment]
Add overload where it takes a buffer? `buffer, offset, count`

**Comment by stephentoub** [comment]
> thank you for replying so quickly

You're welcome :smile:  Thanks.

> Add overload where it takes a buffer?

There are lots of places in the current implementation where a byte[] gets constructed, e.g. most of the stream implementations have a byte[] buffer per instance, same for the readers/writers, CopyTo/CopyToAsync, etc.  I agree with you that these cases are important to address, and they're definitely on our radar.  We do want to handle them and do so consistently.  I expect that at a mimimum once something like https://github.com/dotnet/corefx/issues/4547 / https://github.com/dotnet/apireviews/pull/20 happens, we'll start taking advantage of that in most of these places (after verifying that it does in fact result in better performance).  Then on top of that there's the possibility of additional API surface area, with ctors / overloads / etc. accepting the buffer or the buffer pool to use, but that's a much larger change, and one that's also more difficult to make with existing surface area.

cc: @sokket, @KrzysztofCwalina

**Comment by vancem** [comment]
Stephen added me to comment on the history of why the size is chosen to be 81K.     I agree that it is larger than you might expect.   At the time this was chosen, we were influenced by the fact that a copyToAsync were most commonly used with WinRT interfaces (e.g. copy files etc from outside the App sandbox), and it was not uncommon to have high latency, which argued for larger buffer sizes.   Also the likelihood of the buffer having a long lifetime was low (it only survives for the lifetime of the copyTo), so the cost of a larger buffer was relatively small.   

In the interim, it is quite possible that things have changed enough to reevaluate this choice.  WinRT latencies have probably improved (but I don't have numbers), and copyTo is probably being used in a broader variety of scenarios now than before.    

Still, at least there is a rationale behind the current choice (large as possible (thus good for high latency connections), but small enough to stay out of the large object heap.   If we change this, I would want to understand that rationale that drives it (One rationale is that 'default' users have much smaller streams and the buffers only get used once and so 'setup time' for the buffer (allocation, clearing and GC cost), start to dominate (or it is common to for the CopyTo to last long enough to escape Gen 0 collection).   There is nothing that says 8K or 16K is the 'obvious' choice for a default.   We need some data on how 'typical' uses use it to really make an informed choice.   Do we have some data?

**Comment by redknightlois** [comment]
@vancem the size as-is should be OK, problem is that it is not pooled :) ... also implementors (at least some) already use the knowledge that the default buffer is big in the default, those that are hurt by allocators end up implementing their own pooled CopyToAsync() versions.

**Comment by benaadams** [comment]
@vancem my leaning would be for `CopyToAsync` and `CopyTo` to use different defaults; with the `-Async` version being much smaller. `CopyTo` you are blocked until it completes; whereas `CopyToAsync` opens up lots of interesting uses and is potentially much longer lived.

@redknightlois `CopyToAsync` via extension method ;-) But that means you are already pooling... The discovery method that you should override `CopyToAsync` is currently looking at the source for mscorlib

**Comment by stephentoub** [comment]
I think one of the most interesting points that @vancem alludes to is that by giving a bigger buffer size, you enable each stream to do more per operation, thereby not only minimizing the number of calls that needs to be made, but also minimizing the overhead (often allocations) that comes with each such call.  So potentially counterintuitively, a larger buffer size can actually mean significantly fewer allocations and actually less work for the GC.

For example, here's a little benchmark that's just meant to measure various aspects of doing such a copy operation.  I'm using FileStreams, and in a very specific manner, so I expect the results would change based on the kinds of streams used and how, but this at least provides for an interesting example, and highlights why the current size choice can actually be good.

```C#
using System;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        int NumTasks = Environment.ProcessorCount * 10;
        const int IterationsPerTask = 500;
        const int SourceLength = 1 * 1024 * 1024;
        const int BufferSize = 80 * 1024;

        string sourcePath = "source.bin";
        File.WriteAllBytes(sourcePath, Enumerable.Range(0, SourceLength).Select(i => (byte)i).ToArray());

        var genToBufferCounts = new ConcurrentDictionary<int, int>();

        int gen0 = GC.CollectionCount(0);
        int gen1 = GC.CollectionCount(1);
        int gen2 = GC.CollectionCount(2);
        var sw = Stopwatch.StartNew();

        var tasks = new Task[NumTasks];
        for (int task = 0; task < tasks.Length; task++)
        {
            string destPath = $"dest{task}.bin";
            tasks[task] = Task.Run(async () =>
            {
                using (var source = File.OpenRead(sourcePath))
                using (var dest = File.OpenWrite(destPath))
                {
                    for (int iter = 0; iter < IterationsPerTask; iter++)
                    {
                        source.Position = dest.Position = 0;
                        int bufferEndingGen = await MyCopyToAsync(source, dest, BufferSize, CancellationToken.None);
                        genToBufferCounts.AddOrUpdate(bufferEndingGen, 1, (k, v) => v + 1);
                    }
                }
            });
        }
        Task.WaitAll(tasks);

        Console.WriteLine($"Time: {sw.Elapsed}");
        Console.WriteLine($"Total Gen0 collections: {GC.CollectionCount(0) - gen0}");
        Console.WriteLine($"Total Gen1 collections: {GC.CollectionCount(1) - gen1}");
        Console.WriteLine($"Total Gen2 collections: {GC.CollectionCount(2) - gen2}");

        foreach (var pair in genToBufferCounts)
        {
            Console.WriteLine($"Buffers in Gen{pair.Key}: {pair.Value}");
        }
    }

    private static async Task<int> MyCopyToAsync(Stream source, Stream dest, int bufferSize, CancellationToken cancellationToken)
    {
        byte[] buffer = new byte[bufferSize];
        int bytesRead;
        while ((bytesRead = await source.ReadAsync(buffer, 0, buffer.Length, cancellationToken).ConfigureAwait(false)) > 0)
        {
            await dest.WriteAsync(buffer, 0, bytesRead, cancellationToken).ConfigureAwait(false);
        }
        return GC.GetGeneration(buffer);
    }
}
```

When I run this with:
```
int NumTasks = Environment.ProcessorCount * 10;
const int IterationsPerTask = 500;
const int SourceLength = 1 * 1024 * 1024;
const int BufferSize = 80 * 1024;
```
I get the following output (obviously this will vary somewhat from machine to machine, run to run, etc.):
```
Time: 00:00:09.1535315
Total Gen0 collections: 44
Total Gen1 collections: 22
Total Gen2 collections: 0
Buffers in Gen0: 18636
Buffers in Gen1: 1364
```
If I then change the size of the buffer down from 80k to 8k:
```
const int BufferSize = 8 * 1024;
```
I instead get these results:
```
Time: 00:00:48.4268452
Total Gen0 collections: 378
Total Gen1 collections: 178
Total Gen2 collections: 0
Buffers in Gen0: 8930
Buffers in Gen1: 11070
```
Worse across the board: took much longer, incurred many more GCs, and a much larger percentage of the (smaller) buffers ended up in gen1.

There are almost certainly important and contrary cases where the larger buffer size does make performance measurably worse, potentially even with small tweaks to my example, but this example highlights that there are also cases where it makes performance significantly better.  Without data about the most important scenarios to which to tune, it does seem it'd be difficult to choose something meaningfully better.

**Comment by benaadams** [comment]
Quite a difference; seems fair enough for a general case then - thank you for looking into it. Closing this.

**Comment by benaadams** [comment]
@stephentoub Interestingly, while run-time is improved x5 and GCs reduced, memory "in-use" is far worse
```
const int BufferSize = 80 * 1024;
Gen0 1,455MB
Gen1 106MB
```
```
const int BufferSize = 8 * 1024;
Gen0 69MB
Gen1 86MB
```
