### ISSUE TITLE
[arm] System.Runtime.InteropServices.Tests.ThrowExceptionForHRTests.ThrowExceptionForHR_ErrorInfo_ReturnsValidException Failed

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22244]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_corefx_baseline_tst/41/

**Failed tests:**
System.Runtime.InteropServices.Tests.ThrowExceptionForHRTests.ThrowExceptionForHR_ErrorInfo_ReturnsValidException

**Log:**
```
[m[31;1m    System.Runtime.InteropServices.Tests.ThrowExceptionForHRTests.ThrowExceptionForHR_ErrorInfo_ReturnsValidException(errorCode: -2147352570, errorInfo: 0) [FAIL]
[m[37m      Assert.Equal() Failure
[m[37m                       ↓ (pos 7)
[m[37m      Expected: System.Private.CoreLib
[m[37m      Actual:   System.Runtime.InteropServices.Tests
[m[37m                       ↑ (pos 7)
[m[30;1m      Stack Trace:
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_baseline/_/fx/src/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/ThrowExceptionForHRTests.cs(78,0): at System.Runtime.InteropServices.Tests.ThrowExceptionForHRTests.ThrowExceptionForHR_ErrorInfo_ReturnsValidException(Int32 errorCode, IntPtr errorInfo)
```

**Comment by BruceForstall** [comment]
@danmosemsft Have you seen this? Looks like a stable, multi-platform, regression.

@AaronRobinsonMSFT Maybe related to interop work?

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall This is really weird. I can't imagine we have changed anything here, but the semantics of the `Marshal.ThrowExceptionForHR()` method are impossible to properly predict. In fact this test is actually written incorrectly... Boo... @jkoritzinsky or I will handle this.
