### ISSUE TITLE
Enable Background GC on Linux

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/coreclr#2224]
Background GC relies on the Write Watch support provided by Windows. There are a few different approaches we can take in order to implement Background/Concurrent GC on Linux. We need to investigate how we can achieve this in the most efficient way.

**Comment by jasonwilliams200OK** [comment]
@sergiy-k, found this related thread http://fixunix.com/linux/76508-trapping-writes-mmapd-memory.html for https://msdn.microsoft.com/en-us/library/windows/desktop/aa366573 (`GetWriteWatch` function).

> There is no facility of Linux which scans the page table, collects the
dirty bits, and deposits the page numbers (or corresponding addresses)
into a buffer in user space. Using mprotect() and signals is the
closest available simulation of such functionality in Linux (except
for instruction-by-instruction emulation: see valgrind, etc.)

(and then the code example in the following replies)

**Comment by kouvel** [comment]
@Maoni0 pointed me to the soft-dirty feature as well: https://www.kernel.org/doc/Documentation/vm/soft-dirty.txt. Unfortunately, in previous kernel versions that are still used, it looks like reading the pagemap requires sudo. It seems they changed it to be readable in a recent kernel version.

I'm currently planning on using mprotect / signal handlers. While the performance of modifying pages is worse (takes about 4x as long), it may be a solution we can apply on other platforms, and may choose to switch to soft-dirty on Linux at a later time. An issue with this solution is that mprotect splits the mapped regions, and the default limit on the number of mapped regions (64K) seems to be rather small for this purpose. It may require a config change to vm.max_map_count to enable concurrent GC.
