### ISSUE TITLE
Assertion failure on eventpipe

### ISSUE THREAD

**Issue by sywhang** [dotnet/coreclr#22259]
Trying to get events via eventpipe using the dotnet-collect tool (https://github.com/dotnet/diagnostics/tree/master/src/Tools/dotnet-collect) while running debug version of the runtime fires this assert:
```
Assert failure(PID 2132 [0x00000854], Thread: 2132 [0x0854]): pContainingBuffer == GetHead()
```

Running the app with runtime built in release mode fixes this but it should be looked at.

**Comment by tommcdon** [comment]
@cshung this may be related to #22502

**Comment by tommcdon** [comment]
@sywhang is this still an issue?

**Comment by sywhang** [comment]
It may be a duplicate of #22502, but I just want to leave this here to test it after fix for #22502 is merged to make sure it is a duplicate.

**Comment by tommcdon** [comment]
@cshung can you verify if #22502 fixes this issue?

**Comment by sywhang** [comment]
#24341 fixed this.
