### ISSUE TITLE
[Linux] Inconsistent behavior/description for exepath in coreclr_initialize

### ISSUE THREAD

**Issue by BlackCentipede** [dotnet/coreclr#22271]
In coreclr_initialize API described here: https://github.com/dotnet/coreclr/blob/master/src/coreclr/hosts/inc/coreclrhost.h

The exepath parameter is extremely misleading on linux-x64 platform, if exepath is specified to absolute path to Managed Assembly binary file (dll file), the coreclr_create_delegate API will fail to detect/find that managed assembly. If exepath is specified to directory path that contains that Managed Assembly, then the coreclr_create_delegate invocation will succeed with correct parameters.

Can we add snippet to resolve exepath parameter to directory path for Unix platform?

**Comment by BlackCentipede** [comment]
Oh... that clarify a lot.

**Comment by BlackCentipede** [comment]
@janvorli I just tested it on my end with absolute path to C/C++ executable, it failed to run or detect Managed Assembly. But if I keep the directory path to where managed assembly is located, the invocation would succeed.

**Comment by janvorli** [comment]
@BlackCentipede I guess there must be some other problem in your hosting app. Maybe the properties you are passing to the coreclr_initialize are not correct? As a sanity check, I've ran corerun host under lldb to check what we pass to the API to make sure my memory is correct:
```
coreclr_initialize(exePath="/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/corerun", appDomainFriendlyName="unixcorerun", propertyCount=6, propertyKeys=0x00007fffffffe5f0, propertyValues=0x00007fffffffe5c0, hostHandle=0x00007fffffffe5b0, domainId=0x00007fffffffe5ac) + 67 at unixinterface.cpp:176, name = 'corerun', stop reason = step in
    frame #0: 0x00007ffff5d04873 libcoreclr.so`::coreclr_initialize(exePath="/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/corerun", appDomainFriendlyName="unixcorerun", propertyCount=6, propertyKeys=0x00007fffffffe5f0, propertyValues=0x00007fffffffe5c0, hostHandle=0x00007fffffffe5b0, domainId=0x00007fffffffe5ac)

(lldb) p *(const char*(*)[6])propertyKeys
(const char *[6]) $8 = ([0] = "TRUSTED_PLATFORM_ASSEMBLIES", [1] = "APP_PATHS", [2] = "APP_NI_PATHS", [3] = "NATIVE_DLL_SEARCH_DIRECTORIES", [4] = "System.GC.Server", [5] = "System.Globalization.Invariant")

(lldb) p *(const char*(*)[6])propertyValues
(const char *[6]) $9 = ([0] = "/home/janvorli/dotnet30/test/bin/Debug/netcoreapp3.0/linux-x64/publish/test.dll:/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/System.Net.Sockets.dll:/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/api-ms-win-core-normalization-l1-1-0.dll:/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/api-ms-win-service-private-l1-1-1.dll:/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/WindowsBase.dll:/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/api-ms-win-core-errorhandling-l1-1-0.dll:/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/api-ms-win-core-winrt-registration-l1-1-0.dll:/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/Microsoft.Diagnostics.FastSerialization.dll:/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/api-ms-win-core-fibers-l1-1-1.dll:/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root/System.Globalization.Calendars.dll:/hom", [1] = "/home/janvorli/dotnet30/test/bin/Debug/netcoreapp3.0/linux-x64/publish", [2] = "/home/janvorli/dotnet30/test/bin/Debug/netcoreapp3.0/linux-x64/publish", [3] = "/home/janvorli/dotnet30/test/bin/Debug/netcoreapp3.0/linux-x64/publish:/home/janvorli/git/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root", [4] = "false", [5] = "false")
```

**Comment by BlackCentipede** [comment]
My program is DLang which compiles similarly to C++ output. 

The APP_PATHS targets "/home/centi/Projects/WxDlang/TestLib/bin/Release/netcoreapp2.2/"
And TPA_List get generated from this directory: "/opt/dotnet/shared/Microsoft.NETCore.App/2.2.1/"

```cs
using System;

    public static class Program
    {
        public static void Main()
        {
            Console.WriteLine(typeof(Program).Assembly.GetName());
            Console.WriteLine("Hello World!");
        }
    }
```

This is the C# program that compiles to TestLib.dll and for 3 parameters passed into coreclr_create_delegate are:

Assembly Name = "TestLib"
Type Name = "Program"
Method Name = "Main"

The parameters above works fine on invocation, but if I specified the absolute path to DLang Native program using thisExePath in https://dlang.org/phobos/std_file.html#thisExePath for APP_PATHS and exepath parameters then the invocation will fail. I am working on reproduction code so you can test this.

**Comment by janvorli** [comment]
Please note that while the exePath should contain the full path of the host application, the APP_PATHS should only contain the directory.

**Comment by BlackCentipede** [comment]
Oh that one works, and that make sense now. Thank you.

**Comment by BlackCentipede** [comment]
I guess for the most part, just need few documentation to explain this in Embedded CoreCLR API and it'll be all good to go. :+1:

**Comment by janvorli** [comment]
@BlackCentipede I have enhanced the coreclrhost.h by adding comments and also explicitly setting the calling convention for Windows x86.

**Comment by sergiy-k** [comment]
@BlackCentipede, @janvorli, is there anything else actionable here or this issue can be closed now? Thank you!
