### ISSUE TITLE
[arm64] Test Failed: CoreMangLib_system._delegate_delegate_DelegateCombine1_DelegateCombine1_._delegate_delegate_DelegateCombine1_DelegateCombine1_sh 

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22288]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs8_tst/18/

**Failed tests:**
CoreMangLib_system._delegate_delegate_DelegateCombine1_DelegateCombine1_._delegate_delegate_DelegateCombine1_DelegateCombine1_sh
CoreMangLib_system._runtime_interopservices_maral_MaralSizeOf1_PSC_MaralSizeOf1_PSC_._runtime_interopservices_marshal_MarshalSizeOf1_PSC_MarshalSizeOf1_PSC_sh
JIT_CodeGenBringUpTests._DblCall2_ro_DblCall2_ro_._DblCall2_ro_DblCall2_ro_sh
JIT_CodeGenBringUpTests._DblAvg2_r_DblAvg2_r_._DblAvg2_r_DblAvg2_r_sh
JIT_IL_Conformance._Old_Conformance_Base_dup4_dup4_._Old_Conformance_Base_dup4_dup4_sh

**Log:**
```
CoreMangLib_system._delegate_delegate_DelegateCombine1_DelegateCombine1_._delegate_delegate_DelegateCombine1_DelegateCombine1_sh [FAIL]
        /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs8_tst/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs8_tst/bin/tests/Linux.arm64.Checked/CoreMangLib/system/delegate/delegate/DelegateCombine1/DelegateCombine1.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/CoreMangLib.system/CoreMangLib.system.XUnitWrapper.cs(179,0): at CoreMangLib_system._delegate_delegate_DelegateCombine1_DelegateCombine1_._delegate_delegate_DelegateCombine1_DelegateCombine1_sh()
```

**Comment by VSadov** [comment]
I have re-run this on a lab machine 5000 times concurrently with another session also re-running the test 5000 times. 
There were no failures.
