### ISSUE TITLE
List<List<T>>

### ISSUE THREAD

**Issue by Ultronvision** [dotnet/coreclr#22308]
I think there is runtime issue with list of list. I have just create a list and add them to another list, might be a code snapshot explain well the issue. Here is code snipt.

 `var aq1 = new Quadrant
            {
                Contents = "imran",
                Number = 1
            };
            var aq2 = new Quadrant
            {
                Contents = "imran",
                Number = 1
            };
            var aq3 = new Quadrant
            {
                Contents = "imranj",
                Number = 1
            };
 var quadList = new List<Quadrant>();
            quadList.Add(aq1);
            quadList.Add(aq2);
            quadList.Add(aq3);

            var aq11 = new Quadrant
            {
                Contents = "imran",
                Number = 2
            };
            var aq21 = new Quadrant
            {
                Contents = "imran",
                Number = 3
            };
            var aq31 = new Quadrant
            {
                Contents = "Jon",
                Number = 4
            };
            var quadList2 = new List<Quadrant>();
            quadList2.Add(aq11);
            quadList2.Add(aq21);
            quadList2.Add(aq31);

            var listoflist = new List<List<Quadrant>>();
**//Here is the problem if I add quadList two times in the listoflist then its only show the contents from the
//first list but not the second, but if I add two differe quadlist into listoflist then it works fine, Why is that //so.**
            listoflist.Add(quadList);
            listoflist.Add(quadList2);
            Console.WriteLine("Listoflist count:" + listoflist.Count);
            foreach (var qlist in listoflist)
            {
                Console.WriteLine("its first run");
                do
                {
                     var aname = qlist.First().Contents;
                    var namelist = qlist.Where(mn => mn.Contents.ToString() == aname).ToList();
                    foreach (var item in namelist)
                    {
                        Console.WriteLine("myname is:" + item.Contents);
                    }
                    Console.WriteLine("now removing list" + qlist.Count + " " + namelist.Count);
                    qlist.RemoveAll(al => namelist.Exists(nl => nl.Contents == al.Contents));
                    Console.WriteLine("its Removed:")
                } while (qlist.Count > 0);
                Console.WriteLine("its comming outside");
            }`
At the moment I have just use another name for the inner lists to avoid the issue. Might be I am doing something wrong or you people have the fix for this problem.

Regards,
Imran Ahmed

**Comment by MarcoRossignoli** [comment]
hi @Ultronvision, If I understood well code works correctly, if you do:
```
...
var listoflist = new List<List<Quadrant>>();
listoflist.Add(quadList);
listoflist.Add(quadList);
...
```
the next foreach iterate on "same" `List<Quadrant>` object because Quadrant it's a reference type(class) so first foreach cycle remove all elements from `quadrantList` and second cycle on "same instance"(same reference for first and second list object of listoflist) find empty list.
You can find useful information on .NET types here https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/types

Let me know if I understood your issue or if I'm out of track.

**Comment by Ultronvision** [comment]
Thank You Marco,

I think I well understand your point. So the quadList double assignment
would be not ok. Either I have to create same list but new name will work.

Once again Thank you.

regards,
Imran

**Comment by MarcoRossignoli** [comment]
You're welcome!
If it's resolved you can close this issue, so we simplifying core team work!
