### ISSUE TITLE
error CS0234: The type or namespace name 'Reflection' does not exist in the namespace 'System' 

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22316]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_jitstressregs0x80_bld/57/

**Log:**
```
D:\j\workspace\arm_cross_che---54006c1f\_\fx\artifacts\obj\ref\System.Threading.Channels\netcoreapp-AnyOS-Release\System.Threading.Channels.AssemblyInfo.cs(10,19): error CS0234: The type or namespace name 'Reflection' does not exist in the namespace 'System' (are you missing an assembly reference?) 
```

**Comment by BruceForstall** [comment]
@danmosemsft Temporary inconsistency? Failure in corefx builds?

**Comment by sandreenko** [comment]
The test was not excluded and was running green last month.

**Comment by danmosemsft** [comment]
I have a bit less time to look at tests than I have in the past, it would probably be good to tag @wfurt normally as he's looking at the tests more than anyone right now. Unless you have someone more specific..
