### ISSUE TITLE
3.0 preview2 coreclr.dll revision number doesn't match long-name DAC/SOS

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#22323]
coreclr.dll seems to have a version that doesn't match the package version and the long-name DAC/SOS version. Symbol publish for 3.0 preview2 (https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2367422) hit warnings like these:

```
microsoft.symboluploader.build.task\1.0.0-beta-63604-05\build\PublishSymbols.targets(29,7): warning:
  File NOT found mscordaccore_arm64_arm64_4.6.27322.00.dll CLR: mscordaccore_arm64_arm64_4.6.27322.00.dll/5c479ea752a000/mscordaccore_arm64_arm64_4.6.27322.00.dll - mscordaccore_arm64_arm64_4.6.27322.00.dll
  File NOT found sos_arm64_arm64_4.6.27322.00.dll CLR: sos_arm64_arm64_4.6.27322.00.dll/5c479ea752a000/sos_arm64_arm64_4.6.27322.00.dll - sos_arm64_arm64_4.6.27322.00.dll
  File NOT found mscordaccore_amd64_amd64_4.6.27322.00.dll CLR: mscordaccore_amd64_amd64_4.6.27322.00.dll/5c479e7657e000/mscordaccore_amd64_amd64_4.6.27322.00.dll - mscordaccore_amd64_amd64_4.6.27322.00.dll
```

Note the version, `4.6.27322.00`. Should be `4.6.27322.72` to match the long-name DAC/SOS and package version, `3.0.0-preview-27322-72`.

Doing `(gi .\coreclr.dll) | Select *` on the preview2 coreclr.dll gives me this:

```
VersionInfo       : File:             C:\Users\dagood\desktop\coreclr.dll
                    InternalName:     CoreCLR.dll
                    OriginalFilename: CoreCLR.dll
                    FileVersion:      4.6.27322.0 @BuiltBy: vsagent-a0000QC @Branch: master @SrcCode: https://github.com/dotnet/coreclr/tree/b9e88989458e24fa9764e045917b141e3338eae7
```

vs. preview1's:

```
VersionInfo       : File:             C:\Users\dagood\desktop\coreclr.dll
                    InternalName:     CoreCLR.dll
                    OriginalFilename: CoreCLR.dll
                    FileVersion:      4.6.27121.03 @BuiltBy: dlab14-DDVSOWINAGE101 @Branch: master @SrcCode:
```

I don't know whether those numbers are exactly what long-name lookup uses, but I think it shows the problem is that coreclr.dll has the wrong version.

I'm going to try to fix this up by making a package with the long-named files renamed to `...4.6.27322.00.dll` and indexing those. This might be blocking some form of debugging (snapshot, dumps) on win-x64 + win-x86.

@sbomer CoreCLR moved from pipebuild to yaml between preview1 and preview2, right? (IIRC this is why the build number is so high.) Some change in how the version files are generated could explain this. The `.0` suggests the build is being treated as a developer build at some point--missing some official build number input somewhere.

/cc @dotnet/dotnet-diag (since you were tagged on https://github.com/dotnet/coreclr/issues/17619), @leecow

**Comment by dagood** [comment]
> I'm going to try to fix this up by making a package with the long-named files renamed to `...4.6.27322.00.dll` and indexing those. This might be blocking some form of debugging (snapshot, dumps) on win-x64 + win-x86.

I published the fixup and my symbol checker confirmed the long-name DAC/SOS is indexed against coreclr.dll on internal and public symbol servers for x86 and x64, using the `00` version. (An infra fix in CoreCLR is still needed or else it will happen again.)

**Comment by noahfalk** [comment]
Davis maybe sync with @mikem8361 (or @tommcdon if Mike is busy) so we can coreclr fixed up? Thanks for the temporary fix!

**Comment by dagood** [comment]
This seems like a simple build infra issue to me--these version numbers are generated by the build based on OfficialBuildId. It probably isn't being passed in all the way, or generated too late in the build process, since the switch to AzDO or Arcade. It's applied to the package version and long-name DAC/SOS filename (`72`), but not coreclr DLL version info (`0`/`00`).

Maybe I'm not understanding the purpose of a sync, glad to have one if so. 😄

I tagged sbomer thinking he's able to work on infra issues, but that might not be right (per https://github.com/dotnet/coreclr/issues/22398#issuecomment-460740641). @RussKeldorph are you the right person to route this to someone able to put CoreCLR infra stuff on their backlog for the next preview?

**Comment by RussKeldorph** [comment]
@dagood I've asked @jeffschwMSFT to nominate someone to take a look.  I assume it needs to be fixed by preview 3, is it more urgent than that?

**Comment by dagood** [comment]
Thanks! Preview 3 is correct. As far as I know, nobody has raised this issue with the daily builds.

**Comment by tommcdon** [comment]
Adding Mike in case he can either help out or provide consultation in case there is debugger related work

**Comment by sbomer** [comment]
Thanks @dagood! I suspect this will be fixed by simply passing the OfficialBuildId to build.sh/build.cmd in our .yml files. When I originally looked at what OfficialBuildId was doing, I missed that it was influencing version numbers (I thought it was only relevant for package versions). I'll try to put in a fix for this since it's small and I feel responsible for missing this.

I opened https://github.com/dotnet/coreclr/issues/22448 to track the work to fix our version numbers (removing the 7* and also using arcade/semver2).
