### ISSUE TITLE
Test Infrastructure Failure: System.ComponentModel.Win32Exception (12): Cannot allocate memory

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22367]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_r2r_jitstress2_tiered_tst/18/

**Log:**
```
Test Infrastructure Failure: System.ComponentModel.Win32Exception (12): Cannot allocate memory
```

**Comment by BruceForstall** [comment]
21 tests fail in that job; most or all appear to be due to out of memory.

**Comment by BruceForstall** [comment]
Current runs succeed
