### ISSUE TITLE
JIT\Regression\CLR-x86-JIT\V1-M09\b16102 Fails

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#2236]
The JIT\Regression\CLR-x86-JIT\V1-M09\b16102\b16102\b16102.cmd
test fails, reporting that it got the wrong answer.

**Comment by mikedn** [comment]
Are you talking about the test that's added in one of your PRs? It seems that the [test](https://github.com/richardlford/coreclr/commit/23be972553350daa8483ac6331b812743cb9594c#diff-b529a068faec82361339b84d8a814fab) doesn't contain any actual code.

**Comment by RussKeldorph** [comment]
Fixed by #4845.
