### ISSUE TITLE
Buffer overrun in vectorized string.strlen

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#22393]
Repro:

```
using System;
using System.Runtime.InteropServices;

class My {

    internal const int MEM_COMMIT = 0x1000;
    internal const int MEM_RESERVE = 0x2000;
    internal const int PAGE_READWRITE = 0x04;

    [DllImport("kernel32.dll")]
    internal static extern unsafe void* VirtualAlloc(void* lpAddress, UIntPtr dwSize, int flAllocationType, int flProtect);

    static unsafe void Main()
    {
        void * p = VirtualAlloc(null, new UIntPtr(0x10000), MEM_RESERVE, PAGE_READWRITE);
   
        VirtualAlloc(p, new UIntPtr(0x1000), MEM_COMMIT, PAGE_READWRITE);
        sbyte * s = (sbyte*)p + 0x1000 - 0x1F;

        for (int i = 0; i < 20; i++) *(s+i) = (sbyte)'a';

        new string(s); 
    }
}
```

Result:

```
vpbroadcastb ymm0,xmm0
vmovupd ymm1,ymmword ptr [rsi+rdx] ds:000001f0`b00a0ff0=61 <--- Crash here
vpcmpeqb ymm1,ymm0,ymm1
```

**Comment by jkotas** [comment]
@benaadams The assumption about IndexOf processing memory in aligned chunks no longer holds:

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/String.cs#L658

Could you please take a look a the best way to fix this?

I have noticed intermittent crashes in corefx tests caused by this bug. cc @stephentoub

**Comment by benaadams** [comment]
Sure

**Comment by benaadams** [comment]
Interesting... your example crashes on current; but not on https://github.com/dotnet/coreclr/pull/22187

Digging deeper

**Comment by benaadams** [comment]
Interesting I had a build where this doesn't crash (first one I tried it on); not sure what change it was that was making it work. However, can definitely repro it on current.

Digging deeper.
