### ISSUE TITLE
Publish official build versions to dotnet/versions

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#22398]
Tizen uses this information to trigger builds. It looks like the new CoreCLR official yaml defs don't publish, and the old/legacy builds that did got turned off recently: https://github.com/dotnet/versions/commits/master/build-info/dotnet/coreclr/master.

In the unknown future, Tizen could use BAR, but there isn't public access: https://github.com/dotnet/arcade/issues/1818.

@sbomer can you work on adding this?

https://github.com/dotnet/core-setup/issues/4987 had me do this for core-setup.

/cc @gbalykov @alpencolt

**Comment by sbomer** [comment]
@dagood thanks for the heads up! I won't be able to myself. Here's some info for whoever does this:

We used to call https://github.com/dotnet/coreclr/blob/master/UpdatePublishedVersions.ps1 from buildpipeline: https://github.com/dotnet/coreclr/blob/master/buildpipeline/DotNet-Trusted-Publish.json#L271.

This uses the buildtools task https://github.com/dotnet/buildtools/blob/02a6b294d75b51165d0bac3d2517c4a9c53527e0/src/Microsoft.DotNet.Build.Tasks/VersionTools/UpdatePublishedVersions.cs.

@RussKeldorph if we continue using that task, it's another lingering buildtools dependency that we should track and eventually remove.

**Comment by RussKeldorph** [comment]
@jeffschwMSFT

**Comment by sdmaclea** [comment]
dotnet/versions will be updated with the next official build.
