### ISSUE TITLE
Two NotSupportedException first-chance exceptions occuring when tracing on Linux

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#22399]
I'm using perfcollect to do some tracing on Linux, against the latest coreclr/corefx bits from master.  My app starts by hooking up an AppDomain.FirstChanceException handler that prints exceptions to the console, and when tracing is enabled, I see the following output:
```
System.NotSupportedException: Specified method is not supported.
   at System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLength()
System.NotSupportedException: Specified method is not supported.
   at System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLength()
```

**Comment by sywhang** [comment]
This may be a duplicate of https://github.com/dotnet/coreclr/issues/21743. I fixed this about 10 days ago with https://github.com/dotnet/coreclr/pull/21993. Could you please check if your branch contains this fix?

**Comment by stephentoub** [comment]
Thanks, this seems to be addressed now.
