### ISSUE TITLE
Move System.Globalization.Native to CoreFX repository?

### ISSUE THREAD

**Issue by filipnavara** [dotnet/coreclr#22391]
According to Git history the original rationale for keeping it in CoreCLR repository is that System.Private.CoreLib depends on it. That's the case now even for System.Native that resides in CoreFX, so that reason seems to be passé. Furthermore it's shared by CoreRT so it adds one more dependency to publish and track.

**Comment by jkotas** [comment]
@marek-safar Do you plan to use System.Globalization.Native in Mono?

**Comment by marek-safar** [comment]
@jkotas yes, we do but cannot say in which form exactly right now but if we are going to customize it for a specific platform I'd prefer to do it in a shared location as well.

**Comment by jkotas** [comment]
Just making sure - does corefx/src/Native count as shared location?

**Comment by jkotas** [comment]
I think we should sit on this one for a bit until we have a better idea about the form that it will be used by Mono.

**Comment by am11** [comment]
Another advantage of this move would be that we can clean up some helpers (such as https://github.com/dotnet/coreclr/blob/af83b8ad6f/src/corefx/System.Globalization.Native/pal_compiler.h) and utilize others for safe math in the CoreFX repo.

**Comment by jkotas** [comment]
We plan to look at adjusting repo boundaries for .NET 5.
