### ISSUE TITLE
-Wsign-compare warnings in PAL with GNU compiler

### ISSUE THREAD

**Issue by franksinankaya** [dotnet/coreclr#22405]
[  6%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/loader/modulename.cpp.o
src/pal/src/exception/remote-unwind.cpp: In function ‘bool ReadSLEB128(const libunwindInfo*, unw_word_t*, unw_word_t*)’:
src/pal/src/exception/remote-unwind.cpp:281:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ((shift < (8 * sizeof(unw_word_t))) && ((byte & 0x40) != 0)) {
                ^
src/pal/src/exception/remote-unwind.cpp: In function ‘bool ParseCie(const libunwindInfo*, unw_word_t, dwarf_cie_info_t*)’:
src/pal/src/exception/remote-unwind.cpp:538:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < sizeof(augmentationString); i++)
                       ^
src/pal/src/exception/remote-unwind.cpp:573:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < sizeof(augmentationString); i++)
                       ^
src/pal/src/locale/unicode.cpp: In function ‘BOOL GetUnicodeData(INT, UnicodeDataRec*)’:
src/pal/src/locale/unicode.cpp:141:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (nUnicodeValue <= UNICODE_DATA_DIRECT_ACCESS)
                       ^
src/pal/src/file/path.cpp: In function ‘DWORD GetTempPathA(DWORD, LPSTR)’:
src/pal/src/file/path.cpp:500:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (defaultDirLen < nBufferLength)

In file included from src/pal/src/map/virtual.cpp:21:0:
src/pal/src/map/virtual.cpp: In member function ‘void ExecutableMemoryAllocator::TryReserveInitialMemory()’:
src/pal/src/map/virtual.cpp:2192:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     _ASSERTE(sizeOfAllocation >= (UINT_PTR)m_nextFreeAddress - (UINT_PTR)m_startAddress);
                               ^
src/pal/src/include/pal/dbgmsg.h:372:35: note: in definition of macro ‘_ASSERTE’
 #define _ASSERTE(expr) do { if (!(expr)) { ASSERT("Expression: " #expr "\n"); } } while(0)
                                   ^
src/pal/src/map/virtual.cpp: In member function ‘void* ExecutableMemoryAllocator::AllocateMemory(SIZE_T)’:
src/pal/src/map/virtual.cpp:2222:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ((allocationSize > 0) && (allocationSize <= m_remainingReservedMemory))
                                                 ^
src/pal/src/map/virtual.cpp: In member function ‘void* ExecutableMemoryAllocator::AllocateMemoryWithinRange(const void*, const void*, SIZE_T)’:
src/pal/src/map/virtual.cpp:2258:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (allocationSize == 0 || allocationSize > m_remainingReservedMemory)
                                               ^
src/pal/src/misc/environ.cpp: In function ‘char* EnvironGetenv(const char*, BOOL)’:
src/pal/src/misc/environ.cpp:930:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (strlen(palEnvironment[i]) < nameLength)

[  8%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/safecrt/sscanf_s.cpp.o
src/pal/src/misc/miscpalapi.cpp: In function ‘void PAL_Random(LPVOID, DWORD)’:
src/pal/src/misc/miscpalapi.cpp:271:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (n == -1)
                       ^
[  8%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/safecrt/strcat_s.cpp.o
In file included from src/pal/src/safecrt/splitpath_s.cpp:31:0:
src/pal/src/safecrt/tsplitpath_s.inl: In function ‘errno_t _splitpath_s(const char*, char*, size_t, char*, size_t, char*, size_t, char*, size_t)’:
src/pal/src/safecrt/tsplitpath_s.inl:144:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(iIndex = 0; iIndex < length; iIndex++)
                                    ^
[  9%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/shmemory/shmemory.cpp.o
In file included from src/pal/src/safecrt/wsplitpath_s.cpp:30:0:
src/pal/src/safecrt/tsplitpath_s.inl: In function ‘errno_t _wsplitpath_s(const __wchar_16_cpp__*, __wchar_16_cpp__*, size_t, __wchar_16_cpp__*, size_t, __wchar_16_cpp__*, size_t, __wchar_16_cpp__*, size_t)’:
src/pal/src/safecrt/tsplitpath_s.inl:144:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(iIndex = 0; iIndex < length; iIndex++)

In file included from src/pal/src/sharedmemory/sharedmemory.cpp:7:0:
src/pal/src/sharedmemory/sharedmemory.cpp: In static member function ‘static void SharedMemoryHelpers::SetFileSize(int, SIZE_T)’:
src/pal/src/sharedmemory/sharedmemory.cpp:318:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     _ASSERTE(static_cast<off_t>(byteCount) == byteCount);
                                            ^
src/pal/src/include/pal/dbgmsg.h:372:35: note: in definition of macro ‘_ASSERTE’
 #define _ASSERTE(expr) do { if (!(expr)) { ASSERT("Expression: " #expr "\n"); } } while(0)
                                   ^
src/pal/src/sharedmemory/sharedmemory.cpp: In static member function ‘static void SharedMemoryHelpers::BuildSharedFilesPath(PathCharString&, const char*, int)’:
src/pal/src/sharedmemory/sharedmemory.cpp:398:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     _ASSERTE(strlen(suffix) == suffixCharCount);
                             ^
src/pal/src/include/pal/dbgmsg.h:372:35: note: in definition of macro ‘_ASSERTE’
 #define _ASSERTE(expr) do { if (!(expr)) { ASSERT("Expression: " #expr "\n"); } } while(0)
                                   ^
In file included from src/pal/src/thread/process.cpp:21:0:
src/pal/src/thread/process.cpp: In function ‘BOOL GetProcessIdDisambiguationKey(DWORD, UINT64*)’:
src/pal/src/thread/process.cpp:2240:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     _ASSERTE(chars > 0 && chars <= sizeof(statFileName));
                                 ^
src/pal/src/include/pal/dbgmsg.h:372:35: note: in definition of macro ‘_ASSERTE’
 #define _ASSERTE(expr) do { if (!(expr)) { ASSERT("Expression: " #expr "\n"); } } while(0)
                                   ^
src/pal/src/thread/process.cpp: In function ‘CorUnix::ProcessModules* CreateProcessModules(DWORD, LPDWORD)’:
src/pal/src/thread/process.cpp:3038:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     _ASSERTE(chars > 0 && chars <= sizeof(mapFileName));
                                 ^
src/pal/src/include/pal/dbgmsg.h:372:35: note: in definition of macro ‘_ASSERTE’
 #define _ASSERTE(expr) do { if (!(expr)) { ASSERT("Expression: " #expr "\n"); } } while(0)
                                   ^
In file included from src/pal/src/numa/numa.cpp:19:0:
src/pal/src/numa/numa.cpp: In function ‘void GetCurrentProcessorNumberEx(PPROCESSOR_NUMBER)’:
src/pal/src/numa/numa.cpp:744:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     _ASSERTE(cpu < g_possibleCpuCount);
                  ^
src/pal/src/include/pal/dbgmsg.h:372:35: note: in definition of macro ‘_ASSERTE’
 #define _ASSERTE(expr) do { if (!(expr)) { ASSERT("Expression: " #expr "\n"); } } while(0)
                                   ^
src/pal/src/numa/numa.cpp: In function ‘void* VirtualAllocExNuma(HANDLE, LPVOID, SIZE_T, DWORD, DWORD, DWORD)’:
src/pal/src/numa/numa.cpp:871:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (nndPreferred <= g_highestNumaNode)
                          ^
In file included from src/pal/src/numa/numa.cpp:19:0:
src/pal/src/numa/numa.cpp: In function ‘BOOL SetThreadIdealProcessorEx(HANDLE, PPROCESSOR_NUMBER, PPROCESSOR_NUMBER)’:
src/pal/src/numa/numa.cpp:979:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         _ASSERTE(prevCpu < g_possibleCpuCount);
                          ^
src/pal/src/include/pal/dbgmsg.h:372:35: note: in definition of macro ‘_ASSERTE’
 #define _ASSERTE(expr) do { if (!(expr)) { ASSERT("Expression: " #expr "\n"); } } while(0)
                                   ^
[ 10%] Linking CXX static library libcoreclrpal.a
[ 10%] Built target coreclrpal

**Comment by RussKeldorph** [comment]
@janvorli

**Comment by franksinankaya** [comment]
Fixed with 7760228f08059e6f3ed90e56dbae74eac495aa98
