### ISSUE TITLE
fpermissive compilation warnings with GNU C++ compiler

### ISSUE THREAD

**Issue by franksinankaya** [dotnet/coreclr#22404]
src/pal/tests/palsuite/threading/CreateThread/test2/test2.cpp: In function ‘DWORD Thread(LPVOID)’:
src/pal/tests/palsuite/threading/CreateThread/test2/test2.cpp:26:25: warning: cast from ‘LPVOID {aka void*}’ to ‘DWORD {aka unsigned int}’ loses precision [-fpermissive]
dwThreadId1[(DWORD) lpParameter] = GetCurrentThreadId();
^
src/pal/tests/palsuite/threading/CreateThread/test2/test2.cpp:27:21: warning: cast from ‘LPVOID {aka void*}’ to ‘DWORD {aka unsigned int}’ loses precision [-fpermissive]
bResult[(DWORD) lpParameter] = TRUE;
^
src/pal/tests/palsuite/threading/CreateThread/test2/test2.cpp:28:20: warning: cast from ‘LPVOID {aka void*}’ to ‘DWORD {aka unsigned int}’ loses precision [-fpermissive]
return (DWORD) lpParameter;
src/pal/tests/palsuite/threading/ExitThread/test1/test1.cpp: In function ‘DWORD ExitThreadTestThread(LPVOID)’:
src/pal/tests/palsuite/threading/ExitThread/test1/test1.cpp:25:40: warning: cast from ‘LPVOID {aka void*}’ to ‘DWORD {aka unsigned int}’ loses precision [-fpermissive]
dwExitThreadTestParameter = (DWORD)lpParameter;
^
src/pal/tests/palsuite/threading/ExitThread/test1/test1.cpp: In function ‘BOOL ExitThreadTest()’:
src/pal/tests/palsuite/threading/ExitThread/test1/test1.cpp:80:53: warning: cast from ‘LPVOID {aka void*}’ to ‘DWORD {aka unsigned int}’ loses precision [-fpermissive]
if (dwExitThreadTestParameter != (DWORD)lpParameter)
^
src/pal/tests/palsuite/threading/ResumeThread/test1/test1.cpp: In function ‘DWORD ResumeThreadTestThread(LPVOID)’:
src/pal/tests/palsuite/threading/ResumeThread/test1/test1.cpp:28:42: warning: cast from ‘LPVOID {aka void*}’ to ‘DWORD {aka unsigned int}’ loses precision [-fpermissive]
dwResumeThreadTestParameter = (DWORD)lpParameter;
^
src/pal/tests/palsuite/threading/ResumeThread/test1/test1.cpp: In function ‘BOOL ResumeThreadTest()’:
src/pal/tests/palsuite/threading/ResumeThread/test1/test1.cpp:104:67: warning: cast from ‘LPVOID {aka void*}’ to ‘DWORD {aka unsigned int}’ loses precision [-fpermissive]
if (dwResumeThreadTestParameter != (DWORD)lpParameter)
src/pal/tests/palsuite/threading/SleepEx/test2/test2.cpp: In function ‘DWORD SleeperProc(LPVOID)’:
src/pal/tests/palsuite/threading/SleepEx/test2/test2.cpp:155:24: warning: cast from ‘LPVOID {aka void*}’ to ‘BOOL {aka int}’ loses precision [-fpermissive]
Alertable = (BOOL) lpParameter;
src/pal/tests/palsuite/threading/SwitchToThread/test1/test1.cpp: In function ‘void Run_Thread(LPVOID)’:
src/pal/tests/palsuite/threading/SwitchToThread/test1/test1.cpp:86:17: warning: cast from ‘LPVOID {aka void*}’ to ‘int’ loses precision [-fpermissive]
int Id=(int)lpParam;
src/pal/tests/palsuite/threading/WaitForMultipleObjectsEx/test2/test2.cpp: In function ‘DWORD WaiterProc(LPVOID)’:
src/pal/tests/palsuite/threading/WaitForMultipleObjectsEx/test2/test2.cpp:149:24: warning: cast from ‘LPVOID {aka void*}’ to ‘BOOL {aka int}’ loses precision [-fpermissive]
Alertable = (BOOL) lpParameter;
src/pal/tests/palsuite/threading/WaitForMultipleObjectsEx/test5/test5.cpp: In function ‘DWORD WaitForProcess(LPVOID)’:
src/pal/tests/palsuite/threading/WaitForMultipleObjectsEx/test5/test5.cpp:77:21: warning: cast from ‘LPVOID {aka void*}’ to ‘DWORD {aka unsigned int}’ loses precision [-fpermissive]
index = (DWORD) lpParameter;
src/pal/tests/palsuite/threading/WaitForMultipleObjectsEx/test6/test6.cpp: In function ‘DWORD TestThread(PVOID)’:
src/pal/tests/palsuite/threading/WaitForMultipleObjectsEx/test6/test6.cpp:157:26: warning: cast from ‘PVOID {aka void*}’ to ‘DWORD {aka unsigned int}’ loses precision [-fpermissive]
src/pal/tests/palsuite/threading/WaitForSingleObject/WFSOExMutexTest/WFSOExMutexTest.cpp: In function ‘DWORD WaiterProc(LPVOID)’:
src/pal/tests/palsuite/threading/WaitForSingleObject/WFSOExMutexTest/WFSOExMutexTest.cpp:181:24: warning: cast from ‘LPVOID {aka void*}’ to ‘BOOL {aka int}’ loses precision [-fpermissive]
Alertable = (BOOL) lpParameter;
^
src/pal/tests/palsuite/threading/WaitForSingleObject/WFSOExSemaphoreTest/WFSOExSemaphoreTest.cpp: In function ‘DWORD WaiterProc(LPVOID)’:
src/pal/tests/palsuite/threading/WaitForSingleObject/WFSOExSemaphoreTest/WFSOExSemaphoreTest.cpp:148:24: warning: cast from ‘LPVOID {aka void*}’ to ‘BOOL {aka int}’ loses precision [-fpermissive]
Alertable = (BOOL) lpParameter;
^
src/pal/tests/palsuite/threading/WaitForSingleObject/WFSOExThreadTest/WFSOExThreadTest.cpp: In function ‘DWORD WaiterProc(LPVOID)’:
src/pal/tests/palsuite/threading/WaitForSingleObject/WFSOExThreadTest/WFSOExThreadTest.cpp:156:24: warning: cast from ‘LPVOID {aka void*}’ to ‘BOOL {aka int}’ loses precision [-fpermissive]

**Comment by RussKeldorph** [comment]
@janvorli

**Comment by franksinankaya** [comment]
Fixed with

https://github.com/dotnet/coreclr/commit/34d50b056150ba9101ee977dded9cee3c663fab6
