### ISSUE TITLE
[arm32/64][Ubuntu] CoreFX System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_EntireTreeTerminated fails

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#22413]
The test fails with:
```
System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_EntireTreeTerminated [FAIL]
System.AggregateException : Not all processes in process tree could be terminated. (No such process)
---- System.ComponentModel.Win32Exception : No such process

```
[ci example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/110/)

For arm32 the test was excluded under #16001

**Comment by danmosemsft** [comment]
@bgribaudo WaitForPipeDrain is not supported on Unix:
```
            void SendMessage(string message, string handleAsString)
            {
                using (var client = new AnonymousPipeClientStream(PipeDirection.Out, handleAsString))
                {
                    using (var sw = new StreamWriter(client))
                    {
                        sw.WriteLine(message);
                        client.WaitForPipeDrain(); <<<<<<
                    }
                }
            }

```
I guess it is better to use some event instead. Do you have time to take a look?

If not I could disable the test for Unix for now.

I have no idea why this is not failing in CoreFX runs. The code seems fairly plain, it will always throw on Unix.

```c#

        // Blocks until the other end of the pipe has read in all written buffer.
        public void WaitForPipeDrain()
        {
            CheckWriteOperations();
            if (!CanWrite)
            {
                throw Error.GetWriteNotSupported();
            }

            // For named pipes on sockets, we could potentially partially implement this
            // via ioctl and TIOCOUTQ, which provides the number of unsent bytes.  However, 
            // that would require polling, and it wouldn't actually mean that the other
            // end has read all of the data, just that the data has left this end's buffer.
            throw new PlatformNotSupportedException(); // not fully implementable on unix
        }
```

**Comment by bgribaudo** [comment]
@danmosemsft, I join you in being puzzled by why we this failure didn't show up before. 

I can't promise that I'll have time in the short term to try reworking this.

**Comment by wfurt** [comment]
Even it this predominately fails on ARM, there are occasional failures on x64 as well. 
This seems like test problem. Is the intention to create process in blocked state @bgribaudo? 
I can take a look but I'm also inclined to remove the ARM label as this does not seems architecture dependent to me.

**Comment by wfurt** [comment]
got the PNSP when running on 64bit Ubuntu 18.04

```
      System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_EntireTreeTerminated [STARTING]

  Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
     at System.IO.Pipes.PipeStream.WaitForPipeDrain() in /mnt/github/wfurt-corefx/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 298
     at System.Diagnostics.Tests.ProcessTests.<CreateProcessTree>g__SendMessage|209_4(String message, String handleAsString) in /mnt/github/wfurt-corefx/src/System.Diagnostics.Process/tests/ProcessTests.netcoreapp.cs:line 365
     at System.Diagnostics.Tests.ProcessTests.<CreateProcessTree>b__209_8(String c1hs) in /mnt/github/wfurt-corefx/src/System.Diagnostics.Process/tests/ProcessTests.netcoreapp.cs:line 319
  --- End of stack trace from previous location where exception was thrown ---
     at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/github/wfurt-corefx/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 92
      System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_EntireTreeTerminated [FINISHED] Time: 0.3008999s
```

**Comment by danmosemsft** [comment]
Just noticed the top post was a different symptom, 'No such process'. That is less obvious.

**Comment by bgribaudo** [comment]
@wfurt
>This seems like test problem. Is the intention to create process in blocked state @bgribaudo?

The goal is for `WaitForever()` to force the process to stay around until it is killed externally (either by one of the variants of `Process.Kill()` or by test cleanup code.

**Comment by wfurt** [comment]
the test did not fail since updating the test. closing for now.

**Comment by sandreenko** [comment]
> the test did not fail since updating the test. closing for now.

Did not fail where? The test is excluded for both arm32/arm64 using coreclr\tests\arm(64)\corefx_linux_test_exclusions.txt, can we reenable it?

**Comment by wfurt** [comment]
we have ARM64 daily runs: https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190312.2

I also have access to test result database and I can queries for official runs as well PRs.

Do we publish coreclr runs to helix result database?

**Comment by sandreenko** [comment]
> I also have access to test result database and I can queries for official runs as well PRs.

Got it, thank you, I will try to reenable it in our testing.

> Do we publish coreclr runs to helix result database?

We do not publish Jenkins test results to Kusto anymore. We have results for ADO, but they are not that intresting for CoreFX testing ( we do not run arm32/arm64 there).

**Comment by wfurt** [comment]
BTW ARM32 is in progress. Without daily runs it would be difficult for us to work on fixes. 
ARM64 runs are pretty clean now - with similar random failures as x64.
