### ISSUE TITLE
[arm64] Frequent test timeouts

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#22419]
We seem to be seeing more frequent test timeouts recently, especially superpmicollect. When run locally on a Windows arm64 machine, this test finishes in about 3.5 minutes, when run alone (not in parallel with anything else). When run in the CI (on a faster machine) under xunit, with "-parallel all", it frequently times out at 15 minutes.

e.g.,
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_tailcallstress_tst/60/consoleFull#-9820345932d31e50d-1517-49fc-92b3-2ca637122019

**Comment by AndyAyersMS** [comment]
Perhaps addressed by #22605?

@sandreenko can you take a look?

**Comment by sandreenko** [comment]
I think it is the same issue as #11921, when we run tests in parallel (by default it is on) some of them work significantly slower that we run them sequentially. 
For example my local run with #22474 showed that the fastest instance of that chaos took 20s, the slowest 278s. 
So it is a parallelism issue.
