### ISSUE TITLE
[Windows/x86][GCStress] Test failure: GC\API\GC\Collect\Collect.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#22443]
With:

```
set COMPlus_TieredCompilation=0
set COMPlus_GCStress=0xC
set COMPlus_ZapDisable=1
set COMPlus_ReadyToRun=0
```

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable/116/consoleFull

I can repro locally.

```
BEGIN EXECUTION
 "f:\gh\coreclr10\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" Collect.exe
Array is in generation: 0
Array is in generation: 0
Test for GC.Collect() failed!
Expected: 100
Actual: 1
END EXECUTION - FAILED
```

**Comment by BruceForstall** [comment]
@Maoni0

**Comment by Maoni0** [comment]
ok...these tests are definitely causing more trouble than they are worth for GCStress - I'll do a pass on them tomorrow and make all the ones that verify generations of objects GCStresss incompatible.

**Comment by BruceForstall** [comment]
> ok...these tests are definitely causing more trouble than they are worth for GCStress - I'll do a pass on them tomorrow and make all the ones that verify generations of objects GCStresss incompatible.

@Maoni0 Have you had a chance to do this yet?

**Comment by Maoni0** [comment]
sorry I have not had time for this :( ... basically any test that checks for # of GCs or generation of objects don't make sense to run with GCStress.

**Comment by Maoni0** [comment]
looks like this is done...closing.
