### ISSUE TITLE
[Windows] corefx tests are all timing out

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#22442]
The Windows x86 corefx test runs have almost all timed out (after 6 hours) since about Jan. 23.

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/

The last command run is:
```
build.cmd -test -Release /p:OSGroup=Windows_NT /p:ArchGroup=x86   /p:WithoutCategories=IgnoreForCI /p:PreExecutionTestScript=D:\j\workspace\x86_checked_w---fbe14ed2\SetStressModes.bat
```

(SetStressModes.bat just contains `set COMPlus_TieredCompilation=0`)

From the log file, it looks like all time is taken by Microsoft.Win32.SystemEventsTests. Here's a log fragment:
```
14:55:16      Microsoft.Win32.SystemEvents.Tests: [Long Running Test] 'Microsoft.Win32.SystemEventsTests.PowerModeTests.SignalsPowerModeChanged', Elapsed: 05:32:57
14:55:16   [Long Running Test] 'Microsoft.Win32.SystemEventsTests.SessionEndedTests.SignalsSessionEnded', Elapsed: 05:32:57
14:55:16   [Long Running Test] 'Microsoft.Win32.SystemEventsTests.CreateTimerTests.ConcurrentTimers', Elapsed: 05:32:57
14:55:16   [Long Running Test] 'Microsoft.Win32.SystemEventsTests.UserPreferenceTests.SignalsUserPreferenceEventsAsynchronously', Elapsed: 05:32:57
14:57:15      Microsoft.Win32.SystemEvents.Tests: [Long Running Test] 'Microsoft.Win32.SystemEventsTests.PowerModeTests.SignalsPowerModeChanged', Elapsed: 05:34:57
14:57:15   [Long Running Test] 'Microsoft.Win32.SystemEventsTests.SessionEndedTests.SignalsSessionEnded', Elapsed: 05:34:57
14:57:15   [Long Running Test] 'Microsoft.Win32.SystemEventsTests.CreateTimerTests.ConcurrentTimers', Elapsed: 05:34:57
14:57:15   [Long Running Test] 'Microsoft.Win32.SystemEventsTests.UserPreferenceTests.SignalsUserPreferenceEventsAsynchronously', Elapsed: 05:34:57
```

The stress modes have the same behavior, e.g.,
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstress1/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstress2/

**Comment by BruceForstall** [comment]
@danmosemsft Do you know what's going on here? Can you get someone to investigate?

**Comment by danmosemsft** [comment]
I have no idea. Is it only SystemEVentsTests? In that case feel free to not run these tests in CoreCLR. They are tests for a legacy library. Unless you think there may be a bug in CoreCLR.

@kouvel @ericstj

**Comment by BruceForstall** [comment]
For this flavor of test run, we just run whatever CoreFX has. We do pass `/p:WithoutCategories=IgnoreForCI`. We could ignore other categories as well, if you have any suggestions.

**Comment by ericstj** [comment]
Jan 23 saw a change to some of these tests with https://github.com/dotnet/corefx/commit/8c7771a74510479afc7417041cb5208354164ff6.  I wouldn't expect that to cause them all to hang but I wouldn't rule it out.  @maryamariyan 

Did anything happen to change in CoreCLR that would make waits spin instead of yield or change thread priority?

**Comment by BruceForstall** [comment]
> Jan 23 saw a change to some of these tests with [dotnet/corefx@8c7771a](https://github.com/dotnet/corefx/commit/8c7771a74510479afc7417041cb5208354164ff6). I wouldn't expect that to cause them all to hang but I wouldn't rule it out. @maryamariyan

That change looks very relevant

> Did anything happen to change in CoreCLR that would make waits spin instead of yield or change thread priority?

Not that I know of. @jkotas?

**Comment by jkotas** [comment]
> > CoreCLR that would make waits spin instead of yield or change thread priority?
> Not that I know of. @jkotas?

I am not aware of anything like this either. If this was changed by accident, it would show up in many different tests.

If you get a local repro, attaching a debugger should give you a pretty good clue where the test is stuck.

**Comment by BruceForstall** [comment]
@ericstj @maryamariyan Did you have a chance to investigate this? We're still seeing consistent timeouts in these jobs.

**Comment by ericstj** [comment]
Let's just make every test that relies on passing window-messages outerloop.

**Comment by BruceForstall** [comment]
@ericstj @karelz We're still seeing almost every corefx x86/x64 Windows run fail due to timeout:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_baseline

AFAICT it's Microsoft.Win32.SystemEventsTests

**Comment by danmosemsft** [comment]
@BruceForstall can you please disable these tests from your checked runs.

**Comment by BruceForstall** [comment]
Unfortunately, we have no mechanism to be able to disable corefx tests for Windows x86/x64 :-(

This test run mechanism/infrastructure doesn't use the new granular test exclusion mechanism. Maybe now that corefx is using new RunTests.cmd/sh and new xunit, we could add this?

**Comment by danmosemsft** [comment]
You can't use your json file? There arent many tests in this library.

**Comment by BruceForstall** [comment]
The json exclusion file is not used by the mechanism used to run these tests; it's only used by the "innerloop" corefx run.

**Comment by BruceForstall** [comment]
Nobody in corefx has investigated this failure, so we are still getting timeouts. It affects both Windows x86 and Windows x64:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/

Unfortunately, this is leading us to miss failures, as I found a JIT assert that was not reported due to the timeouts.

**Comment by BruceForstall** [comment]
@danmosemsft @ericstj @karelz A question:

In the coreclr CI, for the "outerloop" (non-Pri0/innerloop) runs, we currently run the corefx tests all on a single machine by constructing a "build.cmd -test" command line, e.g.:
```
build.cmd -configuration Release -framework netcoreapp -os Windows_NT -arch x86 -buildtests  /p:ArchiveTests=Tests -test  /p:WithoutCategories=IgnoreForCI /p:PreExecutionTestScript=D:\j\workspace\x86_checked_w---fbe14ed2\SetStressModes.bat
```

I notice that now the generated corefx `RunTests.cmd` scripts take a `--rsp-file` option that takes a file path to pass to xunit as `@<filename>` (as a "response file").

Is there any way we can pass an argument to the above `build.cmd` (and equivalently, `build.sh`) that would cause the `RunTests.cmd` files to be invoked with a `--rsp-file FOO` with a `FOO` of my choosing? I'm thinking as a temporary hack-around, maybe we can construct an xunit response file that passes the appropriate `-noclass`, `-nomember`, etc., that would allow us to disable tests that are problematic.

**Comment by BruceForstall** [comment]
cc @sandreenko

**Comment by ViktorHofer** [comment]
> Is there any way we can pass an argument to the above build.cmd (and equivalently, build.sh) that would cause the RunTests.cmd files to be invoked with a --rsp-file FOO with a FOO of my choosing?

Sure and I wouldn't even call it a hack as sourcelink is now also using this new mechanism to disable tests. When you build your tests (`-buildtests`) you can add this property `/p:TestRspFile=<path-to-file>` which will be passed down to the test execution script: https://github.com/dotnet/arcade/blob/5c40ffc8d160681c1ff39f69ec8fd893795bd520/src/Microsoft.DotNet.CoreFxTesting/build/core/Core.targets#L202

**Comment by BruceForstall** [comment]
Thanks @ViktorHofer ! I'll try it.

FWIW, the problem seems to be two tests (based on the "[Long Running Test]" output:
```
'Microsoft.Win32.SystemEventsTests.SessionSwitchTests.SignalsSessionSwitch', Elapsed: 05:37:11   
'Microsoft.Win32.SystemEventsTests.CreateTimerTests.ConcurrentTimers', Elapsed: 05:37:11           
```

**Comment by BruceForstall** [comment]
@ViktorHofer Do you know if the xunit response file format allows for an ignored "comment line" syntax? E.g., prefix with "#" to ignore the rest of the line?

**Comment by ViktorHofer** [comment]
Yes: https://github.com/dotnet/arcade/blob/0d3112d5fd33028bbee4326e1446b0e488a859f9/src/Microsoft.DotNet.XUnitConsoleRunner/src/CommandLine.cs#L121

**Comment by BruceForstall** [comment]
fyi, I put up a PR (https://github.com/dotnet/coreclr/pull/24201) that (finally!) allows us to add exclusions when running the jobs that use the (expected to die relatively soon) `run-corefx-tests.py` mechanism. That should allow us to exclude this misbehaving `Microsoft.Win32.SystemEventsTests`, for example.

**Comment by BruceForstall** [comment]
The test legs are no longer timing out because the mal-behaving tests have been disabled with https://github.com/dotnet/coreclr/pull/24201, so I'm closing this.

**Comment by stephentoub** [comment]
I investigated one test that was hanging in corefx CI and put up a fix for it here: https://github.com/dotnet/corefx/pull/37426.
