### ISSUE TITLE
can't build coreclr in vs2019

### ISSUE THREAD

**Issue by wwh1004** [dotnet/coreclr#22446]
E:\clrandjit\coreclr-master>build.cmd -skiptests
BUILD: Starting Build at 17:30:46.25
BUILD: Searching for Visual Studio 2017 or 2015 installation
BUILD: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\Tools\VsDevCmd.bat"
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.0.0-pre.2.2
** Copyright (c) 2018 Microsoft Corporation
**********************************************************************
BUILD: Commencing CoreCLR product build
BUILD: Checking prerequisites
BUILD: Number of processor cores 6
Tools are already initialized.
Running: msbuild.exe /nologo /verbosity:minimal /clp:Summary /nodeReuse:false  /l:BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true  /p:UsePartialNGENOptimization=false /maxcpucount  E:\clrandjit\coreclr-master\build.proj /t:GenerateVersionHeader /p:GenerateVersionHeader=true /p:NativeVersionHeaderFile="E:\clrandjit\coreclr-master\bin\obj\_version.h"  /p:__BuildOS=Windows_NT /p:__BuildType=Debug /p:__BuildArch=x64

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:00.10
BUILD: Laying out dynamically generated files consumed by the native build system
BUILD: Laying out dynamically generated Event test files and etmdummy stub functions
 Generating Dummy Event Headers
 Generating Event Headers
BUILD: Laying out dynamically generated EventPipe Implementation
BUILD: Laying out ETW event logging interface
BUILD: Laying out dynamically generated EventSource classes
BUILD: Commencing build of native components for Windows_NT.x64.Debug
BUILD: Using environment: "\..\..\VC\vcvarsall.bat" x86_amd64
系统找不到指定的路径。
BUILD: Regenerating the Visual Studio solution
CMake Error at CMakeLists.txt:9 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.0.360-preview+g9781d96883
    版权所有(C) Microsoft Corporation。保留所有权利。

    生成启动时间为 2019/2/6 17:30:52。
    “Configuration”属性是全局属性，不能修改。
    “Configuration”属性是全局属性，不能修改。
    “VisualStudioVersion”属性是全局属性，不能修改。
    “Configuration”属性是全局属性，不能修改。
    节点 1 上的项目“E:\clrandjit\coreclr-master\bin\obj\Windows_NT.x64.Debug\CMakeFiles\3.9.6\VCTargetsPath.vcxproj”( 默认目标)。
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [E:\clrandjit\coreclr-master\bin\obj\Windows_NT.x64.Debug\CMakeFiles\3.9.6\VCTargetsPath.vcxproj]
    已完成生成项目“E:\clrandjit\coreclr-master\bin\obj\Windows_NT.x64.Debug\CMakeFiles\3.9.6\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “E:\clrandjit\coreclr-master\bin\obj\Windows_NT.x64.Debug\CMakeFiles\3.9.6\VCTargetsPath.vcxproj”(默认目标) (1) ->
    (_CheckForInvalidConfigurationAndPlatform 目标) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(775,5): error : The OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [E:\clrandjit\coreclr-master\bin\obj\Windows_NT.x64.Debug\CMakeFiles\3.9.6\VCTargetsPath.vcxproj]

        0 个警告
        1 个错误

    已用时间 00:00:00.10

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "E:/clrandjit/coreclr-master/bin/obj/Windows_NT.x64.Debug/CMakeFiles/CMakeOutput.log".
BUILD: Error: failed to generate native component build project

**Comment by Wraith2** [comment]
It might be the same as this https://github.com/dotnet/corefx/issues/34613 issue.

**Comment by danmosemsft** [comment]
In CoreFX we are waiting on a CMAKe that supports VS2019

**Comment by safern** [comment]
CoreFX PR is out, since cmake release 3.14-rc1 today and it now supports VS2019 :smile: 

https://github.com/dotnet/corefx/pull/35197

**Comment by wwh1004** [comment]
Will coreclr supports vs2019 soon? I use cmake 3.14.0-rc1 and try building latest coreclr again, then it fails.
