### ISSUE TITLE
CoreCLR  Debug Problem

### ISSUE THREAD

**Issue by caozhiyuan** [dotnet/coreclr#22459]
i built coreclr ,use VS2017 open Windows_NT.x64.Debug\CoreCLR.sln to debug.

1、debug INSTALL run corerun.exe , if not set CORE_LIBRARIES=%ProgramFiles%\dotnet\shared\Microsoft.NETCore.App\2.2.0, it will raise error.
this is doc [(debugging-instructions.md)](https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md)

2、debug GCSample error, how to run it rightly?
i try this it can run
GCHeap::Initialize  changed g_gc_pFreeObjectMethodTable = g_gc_pFreeObjectMethodTable==NULL?GCToEEInterface::GetFreeObjectMethodTable():g_gc_pFreeObjectMethodTable;
gcenv.ee.cpp changed AppDomainCanAccessHandleTable return to true

**Comment by jkotas** [comment]
> debug GCSample error, how to run it rightly?

It is likely that the GCSample has bit-rotten. Could you please submit PR with the fixes that you have made to make it work again?

**Comment by caozhiyuan** [comment]
@jkotas i'm a beginner, make gc team fix it @Maoni0
