### ISSUE TITLE
Set up and validate IBC/PGO data

### ISSUE THREAD

**Issue by sbomer** [dotnet/coreclr#22467]
I believe we need to be passing IBC/PGO-related arguments to the build scripts in the new infrastructure like we were before. I don't know much about the IBC/PGO data - we should probably work with someone familiar with the perf infra to validate that it is being used correctly.
@RussKeldorph I believe this is something we should prioritize for 3.0.

**Comment by RussKeldorph** [comment]
@adiaaida @brianrob

**Comment by brianrob** [comment]
If you're changing build infrastructure, then yes, we definitely do want to make sure that PGO and IBC are enabled for release builds.

Are the build infrastructure changes already in-place?  If so, can you point to an official build that came from the new infrastructure?  By looking at the binaries and build logs I should be able to tell if things are correct.

**Comment by sbomer** [comment]
Thanks @brianrob! Here is an official build on the new infrastructure: https://dnceng.visualstudio.com/internal/_build/results?buildId=92197. We don't yet pass PGO-related args to our build in the new infrastructure. I'm fairly sure they'll need to be added to https://github.com/dotnet/coreclr/blob/f2ca070a0ab3b75054a225d5908405f83268c920/eng/build-job.yml#L101 and https://github.com/dotnet/coreclr/blob/f2ca070a0ab3b75054a225d5908405f83268c920/eng/build-job.yml#L92.

**Comment by brianrob** [comment]
There are a few phases of PGO and IBC that we need to account for on each platform - Windows x64, Windows x86 and Linux x64:

1. Generate training data for coreclr and clrjit using PGO (VC++ on Windows, LLVM on Linux)
2. Generate training data for System.Private.CoreLib.dll using IBC.
3. Consume the PGO data during the release build.
4. Consume the IBC data during the release build.

I am looking into each of these to see if they are covered.

Windows (x86, x64):
1. Currently generating data.  @sbomer are you going to make a change that would break this?  We build the repo from scratch and specify the PGOInstrument flag.
2. Currently generating data.  @sbomer are you going to make a change that would break this?  We build the repo from scratch and specify the IBCInstrument flag.
3. This works today on release builds - I confirmed that it worked in the build you specified.  There are no special flags that need to be passed to the build on the command line but there is machinery under the hood that downloads the data and then passes it to the build.
4. I am working to confirm that this works on the build you provided.

Linux (x64):
1. Currently generating data.  @sbomer are you going to make a change that would break this?  We build the repo from scratch and specify the PGOInstrument flag.
2. Currently generating data.  @sbomer are you going to make a change that would break this?  We build the repo from scratch and specify the IBCInstrument flag.
3. @adiaaida, how can I tell if LLVM PGO is working? I looked at the logs and it appears that the right CMAKE flag is being set, but I can't tell if it actually works.
4. I am working to confirm that this works on the build you provided.

**Comment by sbomer** [comment]
@brianrob I don't currently intend to make any changes that would change the behavior of our build scripts. I'm mostly concerned about this because I noticed mentions of IBC and PGO in our old buildpipeline definitions, but I'm not doing anything special for them in the new .yml build definitions.

Where is the data generated and used? It would be nice to know about any builds owned by other teams that depend on the behavior of build.sh/cmd just in case we do want to make any changes to these in the future (for example, as part of arcade onboarding).

It looks like IbcOptimize in build.cmd defaults to false, in case that's relevant.

**Comment by brianrob** [comment]
Thanks @sbomer.  I did some experiments, and it looks like IBC optimization is not happening in the builds.  As you point out, IbcOptimize defaults to false.  Official release builds should pass IbcOptimize to build.cmd.  Can you make this change?  Once this is done I can validate that it had the intended effect.

The data is generated in an internal training repo and posted to a MyGet feed which then gets consumed by the official build.

@adiaaida, can you tell me how to tell if LLVM PGO is working correctly?  I see the CMAKE flag being set, but I don't see any console text that indicates it is working.

Other than Linux PGO and Windows/Linux IBC I think everything else is working as expected.

**Comment by adiaaida** [comment]
Other than the flag being set, I don't actually know of a way to tell, other than building a version without pgo and testing to see if perf/size/etc is different.

**Comment by brianrob** [comment]
Thanks @adiaaida.  @sbomer is it possible to do a release build in the lab where PgoOptimize is set to false?  If so, we could do one with it set to true and one with it set to false for the same commit hash and then I could compare the outputs.

**Comment by jkoritzinsky** [comment]
I've done a build on a Linux machine with PgoOptimize set to true and false, and the built binaries are different sizes, so I'm going to take that as PGO being correctly enabled on Linux.

**Comment by brianrob** [comment]
That is likely true.  Can you share the binary drops for those two builds?  I'd like to do a bit of testing on them.

**Comment by jkoritzinsky** [comment]
The files are too big to upload to GitHub, so I'll shoot you an email with them.

**Comment by brianrob** [comment]
Sounds great.  If you can drop them on a share and send me a link in e-mail that would be awesome.  Thanks.

**Comment by jkoritzinsky** [comment]
Sent you a link
