### ISSUE TITLE
Support for async main method in clr

### ISSUE THREAD

**Issue by vladshestel** [dotnet/coreclr#22463]
According to [documentation](https://github.com/dotnet/roslyn/blob/master/docs/features/async-main.md) async main method feature is just a kind of syntactical sugar.
[This](https://blogs.msdn.microsoft.com/mazhou/2017/05/30/c-7-series-part-2-async-main/) blog post from msdn in Conclusion section says, that it was made because it doesn't require any "_CLR code change_".
Since dotnet core 3 has a breaking-change version number, why not implement support for the type of main methods from a clr side?
If I do understand correctly, this improvement will [release](https://github.com/aspnet/AspNetCore/blob/master/src/Hosting/Hosting/src/WebHostExtensions.cs#L66) extra worker thread for all asp.net core applications.

**Comment by stephentoub** [comment]
I don't understand the suggestion.  If the main thread returns, the process will exit.  What are proposing it do instead?

**Comment by vladshestel** [comment]
I expect that clr will use await mechanism inside for asynchronous entry points. So process will exit only when main returned task will be in completed state.
Is it technically possible?

**Comment by stephentoub** [comment]
> So process will exit only when main returned task will be in completed state.

And what prevents the process from exiting?

**Comment by vladshestel** [comment]
I can't give you recipe of how to implement this feature because I don't have enough knowledges about clr internals. It is more philosophical question.:)

In my imagination host thread should start a child thread for executing Main method code and then use [poll](https://linux.die.net/man/2/poll) (or something similar) kernel function to wait for it execution without blocking.

**Comment by stephentoub** [comment]
This would be challenging, without a lot of benefit: the most you save is a single non-runnable thread, when there are already likely many other threads in the process: finalizer thread, GC threads, debugger thread, thread pool threads, and so on.

**Comment by vladshestel** [comment]
I am agree, it is not The-World-Changing-Feature. But it would be nice if someone someday made beautiful dotnet world step closer to perfection.:)
The main point that it is theoretically possible.

**Comment by jkotas** [comment]
@vladshestel Thanks for the suggestion. As @stephentoub said, this would be a lot of work for very little gain. Not worth it to keep this issue open.
