### ISSUE TITLE
We can encapsulate the creation of siVarLoc in case a change in the way of reporting variables

### ISSUE THREAD

**Issue by BrianBohe** [dotnet/coreclr#22473]
We had this code https://github.com/dotnet/coreclr/blob/master/src/jit/codegencommon.cpp#L10366-L10525 that actually is in charge of filling the "siVarLoc" structure depending of the case of variable type and if it's in a register, the stack or both.

I believe it can be moved to Compiler.h in order to make "genSetScopeInfo" a little more clearer/shorter. Also it would be easier to change the way one is reporting the debugger info for variables if it is something desired (or that could change).

I have open this PR for this:
[https://github.com/dotnet/coreclr/pull/22472](https://github.com/dotnet/coreclr/pull/22472)

**Comment by BrianBohe** [comment]
@BruceForstall @sandreenko @CarolEidt

**Comment by sandreenko** [comment]
@dotnet/jit-contrib

**Comment by BrianBohe** [comment]
The PR has been merged so I would say the issue has been solved.
