### ISSUE TITLE
[x64] Test failed: System.SpanTests.IndexerTests.IndexerWithRangeTest 

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22509]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_jitstressregs0x1000/735/

**Failed tests:**
System.Tests.RangeTests.ToStringTest
System.Tests.RangeTests.EqualityTest
System.Tests.RangeTests.HashCodeTest
System.Buffers.Text.Tests.FormatterTests.TestBadFormat(integerType: typeof(float))
System.Buffers.Text.Tests.FormatterTests.TestBadFormat(integerType: typeof(double))
System.Buffers.Text.Tests.FormatterTests.TestGFormatWithPrecisionNotSupported(type: typeof(double))
System.Buffers.Text.Tests.FormatterTests.TestGFormatWithPrecisionNotSupported(type: typeof(float))
System.Tests.RangeTests.CreationTest
System.Tests.IndexTests.CreationTest
System.Tests.IndexTests.ImplicitCastTest
System.SpanTests.IndexerTests.IndexerWithRangeTest

**Log:**
```
System.Tests.RangeTests.CreationTest [FAIL]
  [m[31;1m[m[37m      System.MissingMethodException : Method not found: 'System.Range System.Range.Create(System.Index, System.Index)'.
  [m[31;1m[m[37m      System.MissingMethodException : Method not found: 'System.Range System.Range.Create(System.Index, System.Index)'.
      System.Tests.RangeTests.HashCodeTest [FAIL]
      System.Tests.RangeTests.ToStringTest [FAIL]
  [m[31;1m[m[37m      System.MissingMethodException : Method not found: 'System.Range System.Range.Create(System.Index, System.Index)'.
  [m[31;1m[m[37m      System.MissingMethodException : Method not found: 'System.Range System.Range.Create(System.Index, System.Index)'.
      System.Tests.RangeTests.EqualityTest [FAIL]
```

**Comment by RussKeldorph** [comment]
I assume this was just a transient problem while a breaking change was propagating.
