### ISSUE TITLE
GC_Initialize and GC_VersionInfo no longer exported from coreclr.dll

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#22517]
As of #21924, `GC_Initialize` and `GC_VersionInfo` are no longer exported from `coreclr.dll`.  @janvorli mentioned them [here](https://github.com/dotnet/coreclr/pull/21924#issuecomment-456827677).  Is this intentional?  Should they be added to [mscorwks_ntdef.src](https://github.com/dotnet/coreclr/blob/master/src/dlls/mscoree/mscorwks_ntdef.src)?  And on Unix?

/cc @sandreenko @jkotas  @maoni0

**Comment by jkotas** [comment]
I think these were exported from `coreclr.dll` by mistake. They should not need to be exported from `coreclr.dll`.

Is this causing anything to fail?

**Comment by RussKeldorph** [comment]
I found this when investigating the desktop build break mentioned by @sandreenko [here](https://github.com/dotnet/coreclr/pull/21924#issuecomment-462013797).  I thought they might have been mistakenly exported as well, but @janvorli's comment linked above made me question that assumption.  If it was indeed a mistake, feel free to close the issue.

**Comment by RussKeldorph** [comment]
@jkotas, if they are only supposed to be exported from the shared lib and note coreclr, nevermind.
