### ISSUE TITLE
[x64] Failed to locate the downloaded library

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22510]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_jitstress1_tst/104/

**Log:**
```
Generating MSBuild file /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_jitstress1_tst/tests/src/Common/stress_dependencies/obj/stress_dependencies.csproj.nuget.g.props.
  Generating MSBuild file /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_jitstress1_tst/tests/src/Common/stress_dependencies/obj/stress_dependencies.csproj.nuget.g.targets.
  Restore completed in 2.98 sec for /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_jitstress1_tst/tests/src/Common/stress_dependencies/stress_dependencies.csproj.
Failed to locate the downloaded library
Failed to set up stress dependencies.
```

**Comment by AndyAyersMS** [comment]
Seems like an issue locating coredistools...

```14:18:51   Installing runtime.ubuntu.14.04-x86.Microsoft.NETCore.CoreDisTools 1.0.1-prerelease-00002.
14:18:51   Installing runtime.ubuntu.14.04-x64.Microsoft.NETCore.CoreDisTools 1.0.1-prerelease-00002.
14:18:51   Generating MSBuild file /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_jitstress2_tst/tests/src/Common/stress_dependencies/obj/stress_dependencies.csproj.nuget.g.props.
14:18:51   Generating MSBuild file /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_jitstress2_tst/tests/src/Common/stress_dependencies/obj/stress_dependencies.csproj.nuget.g.targets.
14:18:51   Restore completed in 3.02 sec for /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_jitstress2_tst/tests/src/Common/stress_dependencies/stress_dependencies.csproj.
14:18:51 Failed to locate the downloaded library
14:18:51 Failed to set up stress dependencies.
```
Fail messages come from:

https://github.com/dotnet/coreclr/blob/3c2e989c61c7466bc6d061e03277dbbd8a7e54e9/tests/setup-stress-dependencies.sh#L104-L122

So wonder if something about the RID has changed recently?

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
@jashook Given your recent RID work, anything jump out at you?

**Comment by jashook** [comment]
This should be unrelated. I wonder if we have an ubuntu 14.04 uri for cordistools. Checking.

**Comment by jashook** [comment]
Looks like someone/somehow the rid changed to ubuntu16.04.

https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.ubuntu.16.04-x64.Microsoft.NETCore.CoreDisTools

**Comment by jashook** [comment]
I do not know where these packages are being uploaded. @swaroop-sridhar I believe you were the last person to upload these packages, do you have more insight?

**Comment by jashook** [comment]
After some thought I believe we should move these packages out of nuget and just publish them to azure storage. We are no longer regularly building llilc and updates are going to be manual either way. Seems like we can standardize this with the formatting clang packages.

**Comment by swaroop-sridhar** [comment]
CC: @zamont, who worked on the CoreDisTools package last year.

**Comment by jashook** [comment]
Unless there is objection. I will move the packages to azure storage.

**Comment by jashook** [comment]
The issue is not the package location. After some investigation the rid from the new dotnetcli is returning ubuntu.18.04. Which we do not have a package for.

**Comment by jashook** [comment]
Our rid choice here like normal is flakey.
