### ISSUE TITLE
LNK4221 warnings in the Windows build

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#2252]
The Windows build generates quite a few LNK4221 warnings. Almost all of them are caused by .cpp files that are included in the build but have their entire content ifdefed out. For example, appdomainhelper.cpp, message.cpp and crossdomaincalls.cpp are used only if FEATURE_REMOTING is enabled.

It seems to me that all such files should simply be removed from build to cleanup the linker warnings. Or they should be included in the build conditionally, if the features that need them are enabled. I prototyped such a solution but it seems more trouble than it's worth, it's unlikely that features like remoting will ever come back to CoreCLR. Opinions?

A (not necessarily exhaustive) list of features that are currently disabled but have files included in build:
```
FEATURE_METHOD_RENTAL
FEATURE_FUSION
FEATURE_PERFMAP
FEATURE_TYPEEQUIVALENCE
FEATURE_PROFAPI_ATTACH_DETACH
FEATURE_INTERPRETER
FEATURE_REMOTING
FEATURE_CAS_POLICY
FEATURE_RWLOCK
FEATURE_MIXEDMODE
```

**Comment by jkotas** [comment]
I agree that it would be nice to cleanup these warnings. 

These warnings should be globally suppressed: https://github.com/dotnet/coreclr/blob/master/CMakeLists.txt#L389 . I am not sure why the global suppression does not work.

Simply removing files that have no code for CoreCLR from the CMake build sounds good. But disabling the warning may be more appropriate for files that contribute code for some configs, but not others.

**Comment by mikedn** [comment]
> I am not sure why the global suppression does not work.

I think that CMAKE_SHARED_LINKER_FLAGS applies only to dlls. These warnings come from static library projects.

> Simply removing files that have no code for CoreCLR from the CMake build sounds good. But disabling the warning may be more appropriate for files that contribute code for some configs, but not others.

Then let's just include files conditionally. When I first saw the warning I thought "let's just disable the warning since the build works anyway" but after I saw the handlers.obj issue I'm a bit reluctant about disabling this warning.

**Comment by jasonwilliams200OK** [comment]
We can make the inclusion of those [sources conditional](https://github.com/libgd/libgd/pull/192/files#diff-95e351a3805a1dafa85bf20b81d086e6), so they never get introduced to the build system if certain feature is unavailable.

**Comment by benpye** [comment]
@mikedn Adding the suppression to CMAKE_STATIC_LINKER_FLAGS as well should fix it then?

**Comment by mikedn** [comment]
@benpye Yes, that works.

**Comment by mikedn** [comment]
I think I'll give up on conditionally including files. Initially I though that features are enabled in the root makefiles and never changed after that but it turns out some features are later disabled in dac.cmake and crossgen.cmake and that may result in files being included even though the corresponding features have been disabled. I don't think this is the right approach but that's another issue.

For now I think that we should simply remove those files that do not make sense in CoreCLR (fusion, CAS and remoting I'd say) and disable 4221 via CMAKE_STATIC_LINKER_FLAGS.

**Comment by jkotas** [comment]
I think you can safely exclude these as well:

- vm\umthunkhash.cpp - All other mixed-mode specific files are excluded already.
- vm\typeequivalencehash.cpp - I doubt that the non-PIA type equivalence will ever come to .NET Core or CoreCLR. It solved a narrow COM interop scenario on desktop, but it was found to be not applicable beyond it.

LGTM otherwise. Could you please squash it into fewer commits so it is ready to merge? Thank you!
