### ISSUE TITLE
[Arm64] Loader/NativeLibs test failing

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#22549]
This test:
```
   Loader_NativeLibs._FromNativePaths_FromNativePaths_._FromNativePaths_FromNativePaths_sh
```
Is failing with:
```
   Unable to find an entry point named 'NativeFunc' in shared library 'FromNativePaths_lib
```
Example: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_minopts_tst/113/testReport/

**Comment by CarolEidt** [comment]
@janvorli - I see that you modified the .csproj file for this test recently. Could you take a look?

**Comment by RussKeldorph** [comment]
@jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
@swaroop-sridhar can you take a look?

**Comment by swaroop-sridhar** [comment]
The problem here is that the in [this test](https://github.com/dotnet/coreclr/tree/master/tests/src/Loader/NativeLibs), the NativeFunc symbol is not a publicly exported symbol.
```bash
$ nm -C --defined-only FromNativePaths_lib.so
...
00000000000006f8 t NativeFunc
...
```
We load the library OK, but fail to locate the `NativeFunc` symbol because it is not exported.
