### ISSUE TITLE
Cannot cross compile for arm64 with clang 3.5

### ISSUE THREAD

**Issue by manu-st** [dotnet/coreclr#2255]
I tried to cross compile CoreCLR for arm64 and it does compile the native code out of the box with clang 3.5. The error I'm getting is:

```
/usr/bin/aarch64-linux-gnu-ld: CMakeFiles/ryujit.dir/__/compiler.cpp.o(.debug_info+0x2423d): R_AARCH64_ABS64 used with TLS symbol gTlsCompiler
/usr/bin/aarch64-linux-gnu-ld: ../../pal/src/libcoreclrpal.a(seh.cpp.o): unrecognized relocation (0x20c) in section `.text'
/usr/bin/aarch64-linux-gnu-ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm not sure about the first issue regarding TLS, but for the second issue I found that it seems to be a known issue with clang 3.5 fixed in 3.6, and I confirm that compiling against 3.6 works. Did it even worked before? Should we upgrade the based requirement of clang to be 3.6, at least when targeting arm64?

PS1: I'm using the Intel 64-bit version of Ubuntu 14.04.
PS2: @benpye this is what I mentioned a week ago on gitter.
PS3: As of this writing, you need to add the following lines to tryrun.cmake from cross/arm64 to be able to pass the prerequisites:

```
SET( HAVE_CLOCK_THREAD_CPUTIME_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_SCHED_GETCPU_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)
```

see PR #2253 for more details.

**Comment by benpye** [comment]
Have you used ARM64 hardware to get these values? I did ask @kangaroo what they should be but he hadn't yet got back to me.

**Comment by manu-silicon** [comment]
No just cross compiling from Linux 64-bit on Intel. I do not have yet a 64-bit arm board.

**Comment by jashook** [comment]
I encountered this problem as well on arm64 hardware. The machine I was using could build but not link correctly due to what looked like a bug in llvm. See PR #2154 or https://llvm.org/bugs/show_bug.cgi?id=21077, this bug was filed to address relocating tls symbols.

**Comment by kangaroo** [comment]
I was using the following clang for bring up:

```
linaro@linaro-alip:~$ clang --version
Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: aarch64-unknown-linux-gnu
Thread model: posix
```

Thats running on target though.  I'll confirm the new cmake cache values now.

**Comment by kangaroo** [comment]
Both the values @manu-silicon has are correct.  Do you want to submit a PR, or would you like me to?

**Comment by manu-silicon** [comment]
@kangaroo Have you tried recently compiling CoreCLR natively on ARM64 to see if you are getting the same issue as when you do cross compilation?

**Comment by kangaroo** [comment]
@manu-silicon I compiled it today, thats how I confirmed the CMake cache values.

**Comment by manu-silicon** [comment]
The bug I had is described [here](https://llvm.org/bugs/show_bug.cgi?id=22408) and the fix was added to llvm 3.6.

@kangaroo  I wonder how your setup differs from @jashook.

**Comment by benpye** [comment]
Is it possible that some distributions backport fixes?

**Comment by avi9111** [comment]
I did use mac10.10.5, but it's strange that I compiler protobuf, then run on simulator ,they say it's arch missing .used clang to compile

**Comment by fbmnds** [comment]
I have the same issue im arm64 hardware (Pine64)

**Comment by jkotas** [comment]
Cross-compilation for arm64 works fine now (enabled in CI). Using clang3.8.
