### ISSUE TITLE
VS2019 build doesn't work for x86

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/coreclr#22566]
#22525 Added support to build using VS2019. However, there seems to be a bug in the cmake generator for VS2019. Specifying x86 as the architecture still uses the x64 variant of CL in the generator and the step that tries to consume the generated vcxproj files fails - at least locally. All the generated files seem to target x64 as well. I've opened an issue against cmake to see if there is a workaround.

**Comment by AaronRobinsonMSFT** [comment]
@RussKeldorph Unsure what our timeline for moving to the latest VS, but this might be something to keep an eye on.

**Comment by tannergooding** [comment]
This might be a case where we should explicitly specify `-A Win32`. Right now we are just leaving it up to the CMake default.

**Comment by tannergooding** [comment]
CC. @safern as this might be a concern for CoreFX as well.

**Comment by tannergooding** [comment]
@hoyosjs, could you try adding the following line to https://github.com/tannergooding/coreclr/blob/master/src/pal/tools/gen-buildsys-win.bat#L29 and seeing if that fixes your issue?
```
if /i "%__Arch%" == "x86" (set __ExtraCmakeParams=%__ExtraCmakeParams% -A Win32)
```

(if not, that is fine, and I will test in the morning)

**Comment by hoyosjs** [comment]
This seems to fix the issue indeed. I'll make the PR now. Thanks!
