### ISSUE TITLE
New GNU Compiler Warning: error: 'visibility' attribute ignored on non-class types

### ISSUE THREAD

**Issue by franksinankaya** [dotnet/coreclr#22571]
[ 42%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/file.cpp.o
In file included from coreclr/src/pal/src/include/pal/palinternal.h:333:0,
                 from coreclr/src/pal/src/cruntime/file.cpp:22:
coreclr/src/pal/inc/pal.h:2415:22: error: 'visibility' attribute ignored on non-class types [-Werror=attributes]
 PAL_GetStackBase(VOID);
                      ^
coreclr/src/pal/inc/pal.h:2420:23: error: 'visibility' attribute ignored on non-class types [-Werror=attributes]
 PAL_GetStackLimit(VOID);
                       ^
coreclr/src/pal/inc/pal.h:2666:32: error: 'visibility' attribute ignored on non-class types [-Werror=attributes]
 PAL_LOADLoadPEFile(HANDLE hFile);
                                ^
In file included from coreclr/src/pal/src/include/pal/palinternal.h:333:0,
                 from coreclr/src/pal/src/cruntime/file.cpp:22:
coreclr/src/pal/inc/pal.h:5159:34: error: 'visibility' attribute ignored on non-class types [-Werror=attributes]
 PAL_GetNativeExceptionHolderHead();
                                  ^
cc1plus.exe: all warnings being treated as errors
make[2]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/file.cpp.o] Error 1
make[1]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/all] Error 2
make: *** [all] Error 2

**Comment by franksinankaya** [comment]
It can be workedaround with 
add_compile_options(-Wno-attributes)

. I'm not sure if this is the right thing to do.

**Comment by RussKeldorph** [comment]
@am11 @janvorli

**Comment by am11** [comment]
@RussKeldorph, thanks for the ping, looking into it.
@franksinankaya, in Ubuntu with `coreclr/build.sh x64 checked gcc`, I got error:

```sh
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_LTO
-- Performing Test HAVE_LTO - Success
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc
Detected Linux x86_64
CMake Error at src/corefx/System.Globalization.Native/CMakeLists.txt:19 (message):
  Cannot find libicuuc, try installing libicu-dev (or the appropriate package
  for your platform)


-- Configuring incomplete, errors occurred!
```

although i have `libicu-dev` installed.
If i drop `gcc` or explicitly use `clang`, then it doesn't give this error (and i get 100% build succeeds).
Do you apply some workaround before invoking `coreclr/build.sh`?

**Comment by franksinankaya** [comment]
GCC integration is not final yet. I'm using hacks to remove all components except PAL.

**Comment by franksinankaya** [comment]
https://gist.github.com/franksinankaya/1b4e5e9d1cf9cfc28af27bc2fe03f0e5

**Comment by am11** [comment]
thanks! 😎 
```sh
curl https://gist.githubusercontent.com/franksinankaya/1b4e5e9d1cf9cfc28af27bc2fe03f0e5/raw/4c36d5129f4282875d52fae0ac6e189bb500cc4e/coreclr%2520gnu%2520compile%2520for%2520pal | git apply -
```
