### ISSUE TITLE
JIT: type equivalence leads to an assert when tracking class types

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#22583]
Reproing an issue that came up in desktop testing.

Compile the following to a base library (say base.dll)
```C#
using System;
using System.Runtime.InteropServices;

[assembly:Guid("a95d54f0-5e7c-46e0-a15f-59ab08d41c38")]
[assembly:ImportedFromTypeLib("test")]

public delegate int XD();
```
and then link this into a library (lib.dll)
```C#
// compile via  /t:library lib.cs /l:base.dll
using System;

public class Lib
{
    public static int F() => 33;
    public static XD GetDelegate() => F;
}
```
and separately into an executable that refers to both:
```C#
// compile via /o+ /debug- ex.cs /r:lib.dll /l:base.dll
using System;
using System.Runtime.InteropServices;

class X
{
    static int F() => 3;
    public static int Main()
    {
        XD x = F;
        XD y = Lib.GetDelegate();
        return x() + y() + 64;
    }
}
```
Then a checked jit at Tier1 (or with tiering disabled) will assert in `mergeClasses` jitting `X.Main`:
```
Assert failure(PID 27240 [0x00006a68], Thread: 26064 [0x65d0]): merged == reflexive

CORECLR! CEEInfo::mergeClasses + 0x264 (0x00007ffc`f53751f4)
CLRJIT! Compiler::lvaUpdateClass + 0x154 (0x00007ffd`031c45ac)
CLRJIT! Compiler::lvaUpdateClass + 0x59 (0x00007ffd`031c476d)
CLRJIT! Compiler::impImportBlockCode + 0x13EC (0x00007ffd`03191dc0)
```
The issue is that there are two different delegate types here -- `Lib.XD` and `X.XD` -- that are type equivalent, and so the result of `mergeClasses` is order dependent.

This doesn't cause any codegen issues in release builds because delegates are largely opaque to the jit. So one possible fix is to relax the assertion checks in `mergeClasses` for types with type equivalence.

It may be possible to find a similar example where two non-delegate classes are type equivalent, the jit's type tracking gets confused or is mislead, and optimizations misfire. Still working to see if I can arrange this somehow. It looks like perhaps one cannot expose a class type from the base library, and so we would not see other types assigned across equivalent types, so maybe delegates are a special case?

cc @dotnet/jit-contrib @jkotas 

I remember Jan you warned me that there might be issues in `mergeClasses`...

**Comment by jkotas** [comment]
> maybe delegates are a special case

Type equivalence in desktop can be applied also to interfaces and valuetypes. You should be able to hit this with two type equivalent interfaces as well.

**Comment by AndyAyersMS** [comment]
`mergeClasses` already expects that interface merges might not be reflexive, so it won't assert. And I think the jit is ok getting back either answer for interfaces since those types are never exact and so don't have much influence on optimization.

The jit won't call `mergeClasses` for value types.

So I think we can simply check for delegates on the jit side and avoid calling `mergeClasses` in that case.

**Comment by jkotas** [comment]
You can do that, but I think it would be more robust design to have an JIT/EE interface API that does what you need - and not try to stitch it together on the JIT side.

**Comment by AndyAyersMS** [comment]
Ok, let me work on that.
