### ISSUE TITLE
Tiered JIT compilation causes profilers to not resolve method names.  

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#22585]
@geoffkizer  found this this problem doing an performance investigation on V3.0  If Tiered JIT is on by default in V2.2 (#18973 says that it is), then the issue is there as well.

SYMPTOM: 
PerfView has more ?!? entries that you would expect (indicating that there are addresses for which it does not have symbolic information.  

In general the symptom is that a profiler like PerfView will not resolve ALL (indeed the hottest) managed method names in CPU stack traces if the trace was started after the process of interest was started and warmed up.   

ISSUE:
Profilers like PerfView work by capturing a list of memory addresses inside methods at the time the sample was taken.   These addresses then need to be mapped into symbolic names.   For JIT generated code, is this mapping changes from run to run and thus must be dump on every data collection.  

The way this is typically done is something called 'rundown' where the profiler sends a runtime a command to emit events with that mapping for each method.  This is typically done just before the session ends. 

The bug is that when this enumeration happens, only the original (ReJitID==0) ranges are dumped.   Thus any frames pointed at methods that were rejitted, simply don't have information associated with them.  

This will require a runtime fix to dump all version of JIT compiled methods on rundown.    It should be a easy fix.   You can confirm that you succeeded by taking a 'attach' trace with PerfView /KeepAllEvents (normally runodown events are discarded after processing) and confirming that the 
```
       Microsoft-Windows-DotNETRuntimeRundown/Method/DCStopVerbose
```
Include methods with a ReJITID > 0 (today they are always 0).  

Workarounds include
1. Turning off Tiered JIT compilation (set COMPlus_TieredCompilation=0)
2. Insuring the that trace includes everything from process startup (in which case the rundown is not needed).  

@noahfalk @jorive

**Comment by noahfalk** [comment]
@kouvel

**Comment by vancem** [comment]
I have determined that this is a problem getting the version of the native code (what we call the RejitID).  Methods that have been reJitted erroneously say they are ID 0 (that is they are the first version).  There is some code designed to avoid races in ETW::MethodLog (eventtrace.cpp)
```
        if ((rejitID == 0) && (codeStart != PCODEToPINSTR(pMD->GetNativeCode())))
            continue;
```
That simply skips code when it is rejitID == 0 and it is not the 'current' code for the MethodDesc and this seems to be filtering these out.

**Comment by vancem** [comment]
The rejitID is zero because this code set it to zero 
```
        ReJITID rejitID =
            fGetReJitIDs ? ReJitManager::GetReJitIdNoLock(pMD, codeStart) : 0;
```
(fGetRejitIDs is false unless we are dumping JIT methods when an AppDomain is being unloaded).   

There are comments that talk about having lock problems (that is deadlock), and this was a way out.

**Comment by vancem** [comment]
There is some confusion/ambiguity about what a rejitID means.   When we log when a method is JIT compiled we use
```
            ETW::MethodLog::MethodJitted(this,
                &namespaceOrClassName,
                &methodName,
                &methodSignature,
                pCode,
                pConfig->GetCodeVersion().GetVersionId(),   /** This is the REJIT ID */
                pConfig->ProfilerRejectedPrecompiledCode(),
                pConfig->ReadyToRunRejectedPrecompiledCode());
```
where the ReJitID Is the pConfig->GetCodeVersion().GetVersionId() expression which returns a NATIVE code version number and passes it as the ReJit ID.  

However when we compute the rejit ID during rundown, we call ReJitManager::GetReJitIdNoLock which give IL version number (that is how many times the profilers has update the IL body for the method).

**Comment by kouvel** [comment]
I think the intention is to have it always be the native code version ID, which just increments from zero for each native code version generated regardless of IL version. I'm planning on updating the event data to specify the tier separately.

**Comment by vancem** [comment]
This issue was fixed partially by #22905.  There is still a lingering problem getting line level profiling working that is tracked by #22904.

We also discovered a lower priority bug where the ID for the native code version is not correct on rundown which is tracked by #22908. 

So this issue has served its purpose and can be closed.

**Comment by vancem** [comment]
Closing this as the remaining issues are tracked independently.

**Comment by vancem** [comment]
Closing this as the remaining issues are tracked independently.
