### ISSUE TITLE
WaitHandleBase and WaitHandle object layout differs

### ISSUE THREAD

**Issue by filipnavara** [dotnet/coreclr#22592]
The [unmanaged code](https://github.com/dotnet/coreclr/blob/9d932bb6af40e78c83d98ed280465c7024884d52/src/vm/object.h#L2138-L2140) uses the following layout:

```
    SAFEHANDLEREF   m_safeHandle;
    LPVOID          m_handle;
    CLR_BOOL        m_hasThreadAffinity;
```

The [manged code](https://github.com/dotnet/coreclr/blob/9d932bb6af40e78c83d98ed280465c7024884d52/src/System.Private.CoreLib/src/System/Threading/WaitHandle.cs#L29-L35) uses this layout:

```c#
        private IntPtr waitHandle;
        internal volatile SafeWaitHandle _waitHandle;
        internal bool hasThreadAffinity;
```

Notice that the first two fields are reversed.

Am I missing something that makes this ok? /cc @jkotas

**Comment by hughbe** [comment]
I **think** that reference types are laid out first, then value . types in order. Looking at this comment in `CultureInfo`:

> //  !!!! NOTE WHEN CHANGING THIS CLASS !!!!
//
//  If adding or removing members to this class, please update CultureInfoBaseObject
//  in ndp/clr/src/vm/object.h. Note, the "actual" layout of the class may be
//  different than the order in which members are declared. For instance, all
//  reference types will come first in the class before value types (like ints, bools, etc)
//  regardless of the order in which they are declared. The best way to see the
//  actual order of the class is to do a !dumpobj on an instance of the managed
//  object inside of the debugger.

**Comment by filipnavara** [comment]
@hughbe Great observation, that explains it.

I'm planning to do some cleanup on the code and wanted to make sure I understand correctly how it works.
