### ISSUE TITLE
CoreCLR subscription job is failing

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#22646]
@tannergooding commented on [Fri Feb 15 2019](https://github.com/dotnet/versions/issues/429)

It looks like the CoreCLR subscription job has been failing since https://github.com/dotnet/coreclr/pull/22525 was merged with:
```
Searching for Visual Studio 2017 or later installation
Visual Studio 2017 or later not found
Error: Visual Studio 2017 or 2019 required.
       Please see https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md for build instructions.
```

It looks like this is likely due to us dropping support for VS2015.

---

@tannergooding commented on [Fri Feb 15 2019](https://github.com/dotnet/versions/issues/429#issuecomment-464217316)

CC. @dagood, @jkotas 

---

@dagood commented on [Fri Feb 15 2019](https://github.com/dotnet/versions/issues/429#issuecomment-464219020)

Moving to CoreCLR, nobody tracks dotnet/versions issues.

**Comment by tannergooding** [comment]
Pushed a manual update here: https://github.com/dotnet/coreclr/pull/22647

**Comment by dagood** [comment]
I'd suggest resolving this by removing the dependency on Visual Studio in this scenario, there's no reason dependency update should need a VS toolset.

**Comment by tannergooding** [comment]
@dagood, is there guaranteed to be a suitable `msbuild.exe` (meaning v14 or above) or `dotnet.exe` on the path?

**Comment by dagood** [comment]
Not sure, but I think that would be another reasonable way to go if so.

You might want to do what CoreFX did and make a dedicated script: https://github.com/dotnet/corefx/blob/master/eng/update-dependencies.cmd. (Those commands might not work for CoreCLR, but the idea of setting up basic tooling and using it in a single script would let you leave out the VS detection code.)

**Comment by jkotas** [comment]
Could you please shed some light for me why updating of the repo dependencies runs build?

**Comment by tannergooding** [comment]
@jkotas, they call `build.proj /t:UpdateDependenciesAndSubmitPullRequest <parameters>`, so they only run the necessary targets. For example, CoreCLR (master) does: https://github.com/dotnet/versions/blob/master/Maestro/subscriptions.json#L169-L185

**Comment by tannergooding** [comment]
Re-opening until https://github.com/dotnet/versions/pull/430 is merged.

**Comment by dagood** [comment]
Done. Here's a direct link to the Maestro-triggered build def to look for successes, for convenience: https://devdiv.visualstudio.com/DevDiv/_build?definitionId=2249

**Comment by tannergooding** [comment]
Just as a final followup, we have had multiple jobs succeed since this was merged.

**Comment by ViktorHofer** [comment]
Does somebody know if CoreClr still needs to push to dotnet/versions?

**Comment by dagood** [comment]
Yes, AFAIK, until https://github.com/dotnet/arcade/issues/1818 is completed.
