### ISSUE TITLE
Span<T>.Clear is slower than Array.Clear for reference types

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#22644]
`Span<T>.Clear` is faster than `Array.Clear` for `Int32` but slower for `String`.
Both implementations are based on `SpanHelpers` and I expect `Span<T>.Clear` to be faster in both cases because it's generic thus it's able to check T for references in [compile time](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Span.Fast.cs#L192).
From a quick glance It looks like Array's [GetRawArrayGeometry ](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Array.CoreCLR.cs#L181)intrinsic is faster than `(nuint)_length * (nuint)(Unsafe.SizeOf<T>() / sizeof(nuint))` ? Or is it a penalty for using `new Span()`?

BTW, does it make sense to replace `Array.Clear(myArray)` with `myArray.AsSpan().Clear()` in lots of places in CoreFX and CoreCLR, e.g. [here](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/IO/MemoryStream.cs#L618)? Or maybe to add a new API to Array.cs - `Array.Clear<T>(T[] a)`.

### T is `String`:

|     Method |           array | arraySize |         Mean |     Error |    StdDev |
|----------- |---------------- |---------- |-------------:|----------:|----------:|
|  **SpanClear** | **System.String[]** |         **1** |    **18.335 ns** | **0.0100 ns** | **0.0052 ns** |
| ArrayClear | System.String[] |         1 |     4.861 ns | 0.0015 ns | 0.0008 ns |
|  **SpanClear** | **System.String[]** |        **10** |    **18.196 ns** | **0.0124 ns** | **0.0065 ns** |
| ArrayClear | System.String[] |        10 |     5.819 ns | 0.0005 ns | 0.0002 ns |
|  **SpanClear** | **System.String[]** |       **100** |    **34.331 ns** | **0.0124 ns** | **0.0065 ns** |
| ArrayClear | System.String[] |       100 |    24.237 ns | 0.0324 ns | 0.0169 ns |

### T is `Int32`:

|     Method |          array | arraySize |       Mean |     Error |    StdDev |
|----------- |--------------- |---------- |-----------:|----------:|----------:|
|  **SpanClear** | **System.Int32[]** |         **1** |   **2.613 ns** | **0.0047 ns** | **0.0025 ns** |
| ArrayClear | System.Int32[] |         1 |   6.471 ns | 0.0021 ns | 0.0009 ns |
|  **SpanClear** | **System.Int32[]** |        **10** |   **3.284 ns** | **0.0164 ns** | **0.0086 ns** |
| ArrayClear | System.Int32[] |        10 |   7.080 ns | 0.0035 ns | 0.0018 ns |
|  **SpanClear** | **System.Int32[]** |       **100** |   **6.422 ns** | **0.0445 ns** | **0.0233 ns** |
| ArrayClear | System.Int32[] |       100 |   9.969 ns | 0.0423 ns | 0.0188 ns |
```
BenchmarkDotNet=v0.11.4, OS=Windows 10.0.17134.590 (1803/April2018Update/Redstone4)
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
Frequency=3609380 Hz, Resolution=277.0559 ns, Timer=TSC
.NET Core SDK=3.0.100-preview4-010329
  [Host]     : .NET Core 3.0.0-preview4-27413-9 (CoreCLR 4.6.27413.71, CoreFX 4.7.19.11315), 64bit RyuJIT
  Job-OLAAWV : .NET Core 3.0.0-preview4-27413-9 (CoreCLR 4.6.27413.71, CoreFX 4.7.19.11315), 64bit RyuJIT
```
Benchmark:
```csharp
public class P
{
    static void Main(string[] args) => 
        BenchmarkSwitcher.FromAssembly(typeof(P).Assembly).Run(args);
}

[GenericTypeArguments(typeof(int))]
[GenericTypeArguments(typeof(string))]
public class ClearBenchmarks<T>
{
    public IEnumerable<object[]> TestData()
    {
        yield return new object[] { new T[1], 1 };
        yield return new object[] { new T[10],  10};
        yield return new object[] { new T[100],  100 };
        yield return new object[] { new T[10000], 10000 };
    }

    [Benchmark]
    [ArgumentsSource(nameof(TestData))]
    public void SpanClear(T[] array, int arraySize) => new Span<T>(array).Clear();

    [Benchmark]
    [ArgumentsSource(nameof(TestData))]
    public void ArrayClear(T[] array, int arraySize) => Array.Clear(array, 0, array.Length);
}
```

**Comment by AndyAyersMS** [comment]
Might be the same issue as in #10258.

There is some extra overhead in the `Span<T>(T[])` constructor for ref type `T` that the jit doesn't optimize away -- checking that the type of the arg is exactly `T[]`.

**Comment by EgorBo** [comment]
Ah, ok, closing as a duplicate
