### ISSUE TITLE
Dictionary should tell which key is not found in dictionary.

### ISSUE THREAD

**Issue by fuszenecker** [dotnet/coreclr#2265]
The error message "The given key was not present in the dictionary." should be a bit more informative, it could also tell which key is not found in the dictionary.

**Comment by i3arnon** [comment]
See https://github.com/dotnet/corefx/issues/1187

**Comment by joshfree** [comment]
Hi @fuszenecker,
I'm closing this out as a duplicate of https://github.com/dotnet/corefx/issues/1187.  Thank you
