### ISSUE TITLE
TypeSpec usage

### ISSUE THREAD

**Issue by iskiselev** [dotnet/coreclr#22658]
Looks like in some case usage of TypeSpec is not governed by ECMA-335 specification strict enough - resulting in not sync of PEVerify, runtime and other tools in ecosystem.
I've done some test of using TypeSpec in extends clause of class (looks like there is nothing in specification that state that next samples invalid):
```IL
public class SomeModReq {}

public class Generic`1<T> {
  .method public specialname rtspecialname instance void .ctor() cil managed
  {
    ldarg.0      // this
    call         instance void .base::.ctor()
    ret
  }
}

public class ClassWithNonGenericTypeSpec extends class System.Object
{
  .method public specialname rtspecialname instance void .ctor() cil managed
  {
    ldarg.0      // this
    call         instance void .base::.ctor()
    ret
  }
}

public class ClassWithModReqInTypeSpec extends class Generic`1<int32> modreq(SomeModReq )
{
  .method public specialname rtspecialname instance void .ctor() cil managed
  {
    ldarg.0      // this
    call         instance void .base::.ctor()
    ret
  }
}
```

For both ClassWithNonGenericTypeSpec and ClassWithModReqInTypeSpec  PEVerify shows error:
```
[MD]: Error: TypeDef extends a TypeSpec (...) that is not an instantiated type. [token: ...]
```
In run-time, attempt to load ClassWithNonGenericTypeSpec results in `System.TypeLoadException Could not load TypeSpec from assembly`. C# compiler don't have any problems with using this class.

In run-time, attempt to load/create instance of ClassWithModReqInTypeSpec  works without any problem. At runtime ClassWithModReqInTypeSpec can be casted to Generic1<int32>. C# does not allow direct cast from ClassWithModReqInTypeSpec to Generic<int32> (compilation error), but such class can be casted through previous cast to object.

I'm not sure, if ECMA-335 is not strict enough and should be update by next edition or CLR/PEVerify should work correctly with it. Current work of C# compiler is fully aligned with current ECMA-335 spec here.

**Comment by MichalStrehovsky** [comment]
Legal forms of TypeSpec are all defined in ECMA-335:

![typespec](https://user-images.githubusercontent.com/13110571/53342587-9134e900-390e-11e9-9f0e-0c8bdc9bc364.png)

The examples above all violate the spec and are therefore invalid. Various tools take various approached to deal with it. I think they should all be erroring out, because it's bad input.

We can reopen if you have other concerns.
