### ISSUE TITLE
Some Win/ARM32/64 CI jobs are failing

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#22654]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_innerloop_tst_prtest/

I think this is due to #22452.

**Comment by tannergooding** [comment]
Looking. It seems to only be impacting arm jobs at first glance

Also seems like it might be specific to `Windows_NT arm`, which doesn't appear to have been triggered for my pr.

**Comment by RussKeldorph** [comment]
@tannergooding We don't have enough hardware to trigger win-arm jobs on every PR.  They have to be explictly requested, unfortunately.

**Comment by AndyAyersMS** [comment]
Also impacting Windows arm64

**Comment by RussKeldorph** [comment]
See also: #22618

**Comment by tannergooding** [comment]
Looks like the failure is because the arm jobs never run `init-tools.cmd` (they just download the test zip, extract it, and call `runtest.cmd`) so they never get the `Tools` folder restored.

**Comment by tannergooding** [comment]
test Windows_NT arm Cross Checked Innerloop Build and Test
test Windows_NT arm64 Cross Checked Innerloop Build and Test
