### ISSUE TITLE
Arm32 Ubuntu CLR host failing with symbol lookup error.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#22653]
Example output:
```
15:48:19 /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/artifacts/bin/tests/System.Threading.Tasks.Dataflow.Tests/netcoreapp-Linux-Release-arm /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/artifacts/bin/tests/System.Threading.Tasks.Dataflow.Tests/netcoreapp-Linux-Release-arm
15:48:19 /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm/dotnet: symbol lookup error: /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm/shared/Microsoft.NETCore.App/9.9.9/libhostpolicy.so: undefined symbol: __atomic_fetch_add_4
15:48:19 /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/artifacts/bin/tests/System.Threading.Tasks.Dataflow.Tests/netcoreapp-Linux-Release-arm
15:48:19 ----- end 23:48:19 ----- exit code 127 ----------------------------------------------------------
15:48:19 Looking around for any Linux dump...
15:48:19 ... found no dump in /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/artifacts/bin/tests/System.Threading.Tasks.Dataflow.Tests/netcoreapp-Linux-Release-arm
```

Look like `undefined symbol: __atomic_fetch_add_4` is the important part here.

[ci example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/64/console)

That issue means we can't test CoreFX arm32 Ubuntu now.

**Comment by sandreenko** [comment]
Probably something was broken in dotnet/core-setup.
cc @livarcocc @BruceForstall @dotnet/jit-contrib

**Comment by MichaelSimons** [comment]
I just encountered this issue while trying to produce the latest 3.0 preview3 Docker ARM32 images for https://github.com/dotnet/dotnet-docker.  I view this as a blocker for 3.0 preview3.

CC @leecow

**Comment by livarcocc** [comment]
@dagood for core-setup

**Comment by dagood** [comment]
This would be the host area. @vitek-karas, any ideas?

**Comment by AaronRobinsonMSFT** [comment]
I didn't see this issue. This is blocking preview 3. I will make a fix in core-setup.

**Comment by RussKeldorph** [comment]
@AaronRobinsonMSFT Should this move to core-setup?

**Comment by AaronRobinsonMSFT** [comment]
Actually is probably should. I don't know how to do that though. This is also tracking a disabled test in coreclr, so unclear if this should be closed or not. I am planning on addressing this tomorrow.

**Comment by AaronRobinsonMSFT** [comment]
@sandreenko I just checked in a fix for this into core-setup/master. Was the offending scenario blocked or should the changes flow here and CoreFX testing on ARM32 resume?

**Comment by sandreenko** [comment]
> @sandreenko I just checked in a fix for this into core-setup/master. Was the offending scenario blocked or should the changes flow here and CoreFX testing on ARM32 resume?

Thanks for that, the scenario now is blocked because of another infra issue https://github.com/dotnet/coreclr/issues/22823 that I hope will be fixed soon.
