### ISSUE TITLE
(System.Numerics) Cross Product for Vector2 and Vector4

### ISSUE THREAD

**Issue by micampbell** [dotnet/coreclr#22673]
While it is mathematically true that you can only take the cross product of vectors of length 3, there is often a need in 2D geometry to perform the cross product. This technically creates a new vector only in the out-of-plane or z-direction. But it is just as common to call such a function as it is to call the dot-product. For example, for offsetting, or for determining if the next edge in a polygon turns right or left (or convex or concave).
I suggest adding the following to Vector2_Instrinsics.cs (under Dot() line 109):
```C#
        /// <summary>
        /// Returns the z-value of the cross product of two vectors.
        /// Since the Vector2 is in the x-y plane, a 3D cross product
        /// only produces the z-value
        /// </summary>
        /// <param name="value1">The first vector.</param>
        /// <param name="value2">The second vector.</param>
        /// <returns>The value of the z-coordinate from the cross product.</returns>
        [JitIntrinsic]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float Cross(Vector2 value1, Vector2 value2)
        {
            return value1.X * value2.Y 
                   - value1.Y * value2.X;
        }
```

Perhaps, it is misleading to call it Cross. I'm okay with something like CrossZValue, but I feel strongly that it should be on par with Dot in terms of the SIMD optimization as it is likely to be called quite often. While we're at it. We might as well Cross to Vector4 as well, since this is to be typically used to represent homoegeneous coordinates. I suggest adding the following to Vector4_Instrinsics.cs (under Dot() line 157):
```C#
        /// <summary>
        /// Computes the cross product of two vectors. For homogeneous
        /// coordinates, the product of the weights is the new weight
        /// for the resulting product.
        /// </summary>
        /// <param name="vector1">The first vector.</param>
        /// <param name="vector2">The second vector.</param>
        /// <returns>The cross product.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector4 Cross(Vector4 vector1, Vector4 vector2)
        {
            return new Vector4(
                vector1.Y * vector2.Z - vector1.Z * vector2.Y,
                vector1.Z * vector2.X - vector1.X * vector2.Z,
                vector1.X * vector2.Y - vector1.Y * vector2.X,
                vector1.W * vector2.W);
        }
```

**Comment by RussKeldorph** [comment]
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

@karelz @danmosemsft I don't seem to have permission to Transfer this to `dotnet/corefx`.  Could you move it?

@CarolEidt @eerhardt @tannergooding

**Comment by tannergooding** [comment]
> I don't seem to have permission to Transfer this to `dotnet/corefx`. Could you move it?

Unfortunately, you currently require admin permissions on both the source and destination repositories to use the built-in GitHub functionality.

**Comment by tannergooding** [comment]
I think the proposal, overall, is reasonable.

Looking at a couple of other graphics oriented vector math libraries:
* Unity nor XNA/FNA provides `Cross` for `Vector2`/`Vector4`
* DirectXMath does provide `Cross for `Vector2`/`Vector4`

**Comment by danmosemsft** [comment]
@RussKeldorph for those with contributor access to move issues, we recommend using https://github-issue-mover.appspot.com

**Comment by danmosemsft** [comment]
This issue was moved to dotnet/corefx#35434
