### ISSUE TITLE
Many tests failed with System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#22676]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_r2r_jitstressregs8_tst/39/

**one of failed log:**
```
baseservices_compilerservices._dynamicobjectproperties_test448035_test448035_._dynamicobjectproperties_test448035_test448035_cmd [FAIL]
        
  Unhandled Exception: System.IO.FileNotFoundException: ZapRequire: Could not get native image for test448035.
  Use FusLogVw.exe to check the reason.
  A subdirectory or file IL already exists.
        The system cannot find the file specified.
        Error compiling test448035.org: The system cannot find the file specified. (Exception from HRESULT: 0x80070002 (COR_E_FILENOTFOUND))
EXEC : error : file "test448035.org" or one of its dependencies was not found [C:\j\workspace\arm_cross_che---1b7b6972\tests\runtest.proj]
```

**Comment by BruceForstall** [comment]
Also fails with JITMinOpts:
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_r2r_jitminopts_tst/39

Doesn't fail on Linux.

@kouvel @sergiy-k Can someone look?

**Comment by sergiy-k** [comment]
@fadimounir, could you please take a look?
@BruceForstall, is this issue specific to the JitStress job?

**Comment by BruceForstall** [comment]
Maybe it's fixed? Doesn't fail in the latest:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_r2r_jitminopts_tst/41
(one other known failure)

The stress mode that opened this issue looks broken in other infrastructure ways.

**Comment by RussKeldorph** [comment]
hasn't failed recently
