### ISSUE TITLE
Data structures don't support true 64 bits

### ISSUE THREAD

**Issue by franksinankaya** [dotnet/coreclr#22690]
As an effort to support GCC compiler, several compiler warnings showed up that indicate that there are data structures that handle object pointers but store them as 32 bits. Later same object is fetched and retrieved for consumption.

These data structures need to handle the entire void pointer. This can only be guaranteed by using DWORD_PTR type not DWORD.

    src/classlibnative/../vm/gchandleutilities.h:45:92: warning: cast from ‘void*’ to ‘DWORD {aka unsigned int}’ loses precision [-fpermissive]
         DWORD context = (DWORD)GCHandleUtilities::GetGCHandleManager()->GetHandleContext(handle);

src/vm/crossloaderallocatorhash.inl: In static member function ‘static INT32 GCHeapHashDependentHashTrackerHashTraits::Hash(LoaderAllocator**)’:
src/vm/crossloaderallocatorhash.inl:204:20: warning: cast from ‘GCHeapHashDependentHashTrackerHashTraits::PtrTypeKey {aka LoaderAllocator*}’ to ‘INT32 {aka int}’ loses precision [-fpermissive]
     return (INT32)*pValue;

**Comment by franksinankaya** [comment]
@am11 @jkotas @janvorli

**Comment by jkotas** [comment]
This code uses the context as 32-bit index. There is nothing wrong with it.

**Comment by franksinankaya** [comment]
hash? collision?

0x1abcdef00 vs 0xabcdef00

**Comment by franksinankaya** [comment]
Other interesting warnings that are about to be suppressed:

https://github.com/dotnet/coreclr/pull/22810/commits/23fecf24dd1ab57a7090ab4b4c9c7b4b6997a882

**Comment by janvorli** [comment]
@franksinankaya this issue can be closed, right?

**Comment by franksinankaya** [comment]
I have not seen a fix. Somebody complained about the samething on another issue for HPC apps

**Comment by janvorli** [comment]
> I have not seen a fix.

The code in `src/vm/gchandleutilities.h` is gone. And the code `src/vm/crossloaderallocatorhash.inl` is intentionally using just 32 bits of the key as the hash. Collisions are unlikely to happen there (allocation of LoaderAllocator would have to end up with addresses where lower 32 bits match for two LoaderAllocators)

**Comment by franksinankaya** [comment]
I think there's a really dangerous assumption here that applications will never need more than 4GB.

I really don't like these size_t casts in the code. These need to go away to achieve scalability.

**Comment by janvorli** [comment]
@franksinankaya can you please be more specific which place are you referring to? None of the places you've mentioned in this issue seems to be that case.

**Comment by franksinankaya** [comment]
23fecf2

**Comment by janvorli** [comment]
I don't see any problem in those. All but one are hashes, so it doesn't matter how the hash is computed (we have decided to take the low 32 bits as the hash value since such hash seems reasonable). Even if the hashes collide, it is not a problem. No matter what algorithm you chose to compute the hash, you always can have hash collisions (unless you have perfect hashing function).
The one that is not hash - the `ZapDynamicHelperCell::GetKind()` is special. It uses the case when the GetHandle() result bit 0 is set to 1. In such case, the handle stores `CORCOMPILE_FIXUP_BLOB_KIND` enum values shifted to the left by 1 and bit 0 set to 1.

**Comment by franksinankaya** [comment]
Why not use the full pointer value as hash?

**Comment by janvorli** [comment]
Every hash table entry would then be larger by 32 bits and I still don't see any benefit. The fact that two hashes don't collide doesn't mean that the hash table entry indices for each of the hashes won't be the same. The table has a limited size and the initial index is `hash % table_size`.

**Comment by franksinankaya** [comment]
I see. Does the code handle collisions? Or assume that it will never collide.

If former, the issue can be closed. If latter, code needs to be made more reliable. 

I assumed that table is resizing based on number of entries present.

**Comment by janvorli** [comment]
Hash table implementations need to handle collisions. It is practically unavoidable without knowing all the possible key values in advance. We use open addressing to handle collisions. See the https://en.wikipedia.org/wiki/Hash_table for details.
