### ISSUE TITLE
AmbiguousImplementationException should be in the System.Runtime namespace

### ISSUE THREAD

**Issue by terrajobst** [dotnet/coreclr#22748]
Looks like #22280 added the exception in the wrong namespace (`System.Runtime.Serialization` vs. `System.Runtime`). We should fix this to match the [approved API](https://github.com/dotnet/corefx/issues/34124).

/cc @stephentoub @jkotas

**Comment by jkotas** [comment]
This was fixed by https://github.com/dotnet/coreclr/pull/22291
