### ISSUE TITLE
Enum.ToString() can return wrong value

### ISSUE THREAD

**Issue by Tadimsky** [dotnet/coreclr#22750]
I encountered a really strange issue where calling `ToString()` on an `enum` was returning a value different from the actual value of the enum. It turned out to be caused by me having a bug with my bit-shift direction and having two enums with the same value.
However, I thought that this was still strange behavior for the `ToString()` function.

Repro:

```csharp
using System;
					
public class Program
{
    public enum Geography
    {
        Worldwide = 0,
        Europe = Worldwide << 1
    }
	
	public static void Main()
	{
            var ww = Geography.Worldwide;
	    var eu = Geography.Europe;

	    Console.WriteLine(ww);		
	    Console.WriteLine(eu);
	}
}
```

Expected output:
```
Worldwide
Europe
```

Actual output:
```
Worldwide
Worldwide
```

https://dotnetfiddle.net/CYblev

I looked at the code for ToString and it makes sense how this is happening. However, in the debugger, VS tells me that me geo is the correct one (Europe for eu and Worldwide for ww).
So it seems interesting that VS knows the type of the enum even though it's value is the same, but `ToString()` returns the wrong one.

**Comment by rducom** [comment]
You are right shifting 0000000 by one position, so result is still 0000000. That's "by design". Try right shifting 0000001 instead

**Comment by Tadimsky** [comment]
Yeah, that's the bug I was mentioning I have.
But that's not the issue I'm reporting.

**Comment by Tadimsky** [comment]
For example, I'll do this instead:

```csharp
using System;
                    
public class Program
{
    public enum Geography
    {    
        A = 0,		
        B = 0,
        C = 0,		
        D = 0
    }
    
    public static void Main()
    {
        var a = Geography.A;
        var b = Geography.B;		
        var c = Geography.C;


        Console.WriteLine(a);		
        Console.WriteLine(b);		
        Console.WriteLine(c);
    }
}
```

Output:
```
B
B
B
```

**Comment by Tadimsky** [comment]
And then adding one more type to the enum results in different output:

```csharp
using System;
                    
public class Program
{
    public enum Geography
    {    
        A = 0,		
        B = 0,
        C = 0,		
        D = 0,
        E = 1
    }
    
    public static void Main()
    {
        var a = Geography.A;
        var b = Geography.B;		
        var c = Geography.C;


        Console.WriteLine(a);		
        Console.WriteLine(b);		
        Console.WriteLine(c);
    }
}
```

Output:
```
C
C
C
```

So this seems kind of bad as we're just doing a binary search through the values and getting the middle value. It means that adding or removing an enum will cause your string value to change.

**Comment by rducom** [comment]
enum allows multiple enum values to share the same value, by design in the C# specs, however, this is not a recommended usage.
I don't get the point of why such an enum would be used, but the behavior you are seeing is known, [and is documented here ](https://docs.microsoft.com/en-us/dotnet/api/system.enum.getname?redirectedfrom=MSDN&view=netframework-4.7.2#System_Enum_GetName_System_Type_System_Object_)

> If multiple enumeration members have the same underlying value, the GetName method guarantees that it will return the name of one of those enumeration members. However, it does not guarantee that it will always return the name of the same enumeration member. As a result, when multiple enumeration members have the same value, your application code should never depend on the method returning a particular member's name.

**Comment by bartonjs** [comment]
As @rducom said, this is a documented behavior for this method.

If you looked at the compiled output of the test case in https://github.com/dotnet/coreclr/issues/22750#issuecomment-466163375 in reflector/ilspy/etc it would probably have replaced all three variable assignments with the same `Geography` member (which one would depend on the particular tool being used).

The IL emitted by the compiler just declares 3 locals of type `Geography`, then loads the numeric literal (`0` in this case) into it; the notion of the name you used in the source code doesn't actually survive compilation.

(Changing the name of an enum field is a compile breaking change without a runtime breaking change; the runtime always just sees it as a "typed literal integer")
