### ISSUE TITLE
Ensure that HW Intrinsics producing small int results have casts as needed

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#22758]
See #22666 and #22667 for discussion

**Comment by CarolEidt** [comment]
@tannergooding - you mentioned here: https://github.com/dotnet/coreclr/pull/22666#issuecomment-466189282 that you'd be willing to take a look at this - is this still something you would be willing to do?

**Comment by tannergooding** [comment]
Yes. I should be able to finish this before end of the week.

**Comment by RussKeldorph** [comment]
@tannergooding Any update?

**Comment by tannergooding** [comment]
Yes. I went through the various APIs and they look to be functioning as expected.

**Comment by RussKeldorph** [comment]
@tannergooding Thank you!
