### ISSUE TITLE
[x64] Error occured when running run-corefx-tests.py

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22778]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_jitstress1/862/

**Log:**
```
[/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstress1/tests/scripts/run-corefx-tests.py]: Error: exit code 256
```

**Comment by echesakovMSFT** [comment]
@sandreenko Is this fixed by https://github.com/dotnet/coreclr/pull/22773?

**Comment by sandreenko** [comment]
Yes, it should be.
