### ISSUE TITLE
Replace calls to GetThread with INLINE_GETTHREAD in arm/arm64 assembly stubs

### ISSUE THREAD

**Issue by fadimounir** [dotnet/coreclr#22772]
INLINE_GETTHREAD will be available when #22560 gets merged

**Comment by janvorli** [comment]
@RussKeldorph do you think this needs to be marked as blocking-3.0-preview-5? It is just a perf optimization.

**Comment by RussKeldorph** [comment]
@janvorli Nope.  Removed.  FYI, I applied the label indiscriminately to all ARM64 3.0 issues.  Feel free to remove it based on your judgment.

**Comment by fadimounir** [comment]
Fixed
