### ISSUE TITLE
[arm32][Windows] Interop/COM/NETClientEvents fails

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#22784]
It fails almost in all PRs, [queue 
](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_innerloop_tst_prtest)
```
15:21:56     Starting:    Interop.COM.XUnitWrapper
15:22:02 
      Interop_COM._NETClients_Events_NETClientEvents_NETClientEvents_._NETClients_Events_NETClientEvents_NETClientEvents_cmd [FAIL]
15:22:02         
15:22:02   
15:22:02   Return code:      1
```

The similar issue #20682  points to future, so I mark this as Future as well.

cc @dotnet/jit-contrib

**Comment by sandreenko** [comment]
The test was added in #22721.

The strange thing is that it doesn't fail in coreclr-ci (Test Pri0 Windows_NT arm checked) and that ado tests were not run in this PR, @echesakov do you know why?

**Comment by sandreenko** [comment]
Revert #22785  when it is fixed.

**Comment by echesakovMSFT** [comment]
@sandreenko We don't run both Linux and Windows arm32 and Windows/arm64 testing in AzDO yet due to limited hardware resources and incompatibility with Jenkins.

**Comment by AaronRobinsonMSFT** [comment]
Closing as duplicate of https://github.com/dotnet/coreclr/issues/20682.
