### ISSUE TITLE
[x64] Test failed: JIT_Methodical._MDArray_basics_stringarr_cs_d_stringarr_cs_d_._MDArray_basics_stringarr_cs_d_stringarr_cs_d_cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22780]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_zapdisable_jitstress2/125/

**Failed tests:**
JIT_Methodical._MDArray_basics_stringarr_cs_d_stringarr_cs_d_._MDArray_basics_stringarr_cs_d_stringarr_cs_d_cmd

**Log:**
```
> set CORE_ROOT=D:\j\workspace\x64_checked_w---23ee0b70\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
  > D:\j\workspace\x64_checked_w---23ee0b70\bin\tests\Windows_NT.x64.Checked\JIT\Methodical\MDArray\basics\stringarr_cs_d\stringarr_cs_d.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x64_checked_w---23ee0b70\bin\tests\Windows_NT.x64.Checked\TestWrappers\JIT.Methodical\JIT.Methodical.XUnitWrapper.cs(107069,0): at JIT_Methodical._MDArray_basics_stringarr_cs_d_stringarr_cs_d_._MDArray_basics_stringarr_cs_d_stringarr_cs_d_cmd()
      JIT_Methodical._MDArray_basics_stringarr_cs_d_stringarr_cs_d_._MDArray_basics_stringarr_cs_d_stringarr_cs_d_cmd [FAIL]
```

**Comment by BruceForstall** [comment]
@erozenfeld This passed in the latest run (https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_zapdisable_jitstress2/128). Can we close the issue?

**Comment by erozenfeld** [comment]
I wasn't able to repro this in tens of thousands of tries on my machine. Closing for now.
