### ISSUE TITLE
BroadcastScalarToVector256(byte*) broadcasts not correct value?

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#22815]
From https://twitter.com/HaroldAptroot/status/1099389327245828096

```csharp
public static void Main(string[] args)
{
    Console.WriteLine(test(128));
}

static unsafe Vector256<byte> test(byte v)
{
    Vector256<byte> x = Avx2.BroadcastScalarToVector256(&v);
    return x;
}
```
Outputs for debug
```
<224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224>
```
Outputs for release
```
<32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32>
```
Produces the following asm
```asm
; Lcl frame size = 0

G_M25726_IG01:
       vzeroupper 
       nop      
       mov      dword ptr [rsp+10H], edx

G_M25726_IG02:
       lea      rax, bword ptr [rsp+10H]
       vpbroadcastb ymm0, yrax
       vmovupd  ymmword ptr[rcx], ymm0
       mov      rax, rcx

G_M25726_IG03:
       vzeroupper 
       ret      

; Total bytes of code 30, prolog size 5 for method Program:test(ubyte):struct
```
It inlines into the Main method producing the following asm
```asm

G_M42296_IG01:
       sub      rsp, 88
       vzeroupper 
       vmovaps  qword ptr [rsp+40H], xmm6
       vmovaps  qword ptr [rsp+30H], xmm7

G_M42296_IG02:
       mov      dword ptr [rsp+2CH], 128
       lea      rcx, bword ptr [rsp+2CH]
       vpbroadcastb ymm6, yrcx
       mov      rcx, 0xD1FFAB1E
       vextractf128 ymm7, ymm6, 1
       call     CORINFO_HELP_NEWSFAST
       vinsertf128 ymm6, ymm7, 1
       vmovupd  ymmword ptr[rax+8], ymm6
       mov      rcx, rax
       call     Console:WriteLine(ref)
       nop      

G_M42296_IG03:
       vmovaps  xmm6, qword ptr [rsp+40H]
       vmovaps  xmm7, qword ptr [rsp+30H]
       vzeroupper 
       add      rsp, 88
       ret      

; Total bytes of code 98, prolog size 19 for method Program:Main()
```

Contrast with
```csharp
static unsafe Vector256<byte> test(byte v)
{
    Vector256<byte> x = Vector256.Create(v);
    return x;
}
```
Which produces
```asm
G_M25727_IG02:
       movzx    rax, dl
       vmovd    xmm0, eax
       vpbroadcastb ymm0, ymm0
       vmovupd  ymmword ptr[rcx], ymm0
       mov      rax, rcx
```
And correctly outputs
```
<128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128>
```

/cc @tannergooding @fiigii

**Comment by mikedn** [comment]
`GenTreeHWIntrinsic::OperIsMemoryLoad()` doesn't handle this case correctly. Local variable addresses sometimes have type `TYP_BYREF` (odd, but that's another story) and `OperIsMemoryLoad` only checks for `TYP_I_IMPL`.

**Comment by fiigii** [comment]
> `GenTreeHWIntrinsic::OperIsMemoryLoad()` doesn't handle this case correctly. Local variable addresses sometimes have type `TYP_BYREF` (odd, but that's another story) and `OperIsMemoryLoad` only checks for `TYP_I_IMPL`.

@mikedn Thank you so much for the information, I did not know that... Are you working on a fix? If not, I can submit a PR.

**Comment by fiigii** [comment]
> The memory versions of these intrinsics should have been different (e.g. `NI_AVX2_BroadcastScalarMemToVector256`).

I agree that an internal intrinsic ID is better for JIT perf and avoiding the similar bugs.

**Comment by mikedn** [comment]
@fiigii Maybe I'll make a fix this evening, if nobody does it before.

**Comment by tannergooding** [comment]
> I think that changing the semantics based on the type of an operand is asking for trouble.

What's the differing semantic here? Is it `reg32` vs `mem8`?

If so, we actually have a number of cases like that. All of the scalar floating-point operations, for example; which are `reg128` vs `mem32` or `mem64`.

**Comment by tannergooding** [comment]
Also, CC. @CarolEidt as an FYI on the bug here.

**Comment by mikedn** [comment]
> If so, we actually have a number of cases like that. All of the scalar floating-point operations, for example; which are reg128 vs mem32 or mem64.

Which ones to be precise? I don't see anything like that in `OperIsMemoryLoad`.

**Comment by tannergooding** [comment]
> Which ones to be precise? I don't see anything like that in `OperIsMemoryLoad`.

Ah, you're right. Those are handled via the explicit `LoadVector` intrinsics and then containing the memory load in lowering.

Looking at this (and I've likely just forgotten) why do we need both a `InsertVector128(V256<T>, V128<T>, byte)` and a `InsertVector128(V256<T>, T*, byte)` overload? Unlike `Broadcast` which exposes just the mem overload in AVX and adds the register overload later, `InsertVector128` exposes both the reg and the mem overload simultaneously, so I would expect it could just work via a single overload and containment.

I'm also not sure why `Gather` is marked as `MaybeMemoryLoad`, since it is always a memory load, which would leave only `Broadcast` as needing "special casing", since there are distinct instructions in separate ISAs for mem vs reg.

**Comment by mikedn** [comment]
> Looking at this (and I've likely just forgotten) why do we need both a InsertVector128(V256<T>, V128<T>, byte) and a InsertVector128(V256<T>, T*, byte) overload?

Uh oh, didn't notice that. I think those should be removed.

> I'm also not sure why Gather is marked as MaybeMemoryLoad, since it is always a memory load

Yeah, but it's also `HW_Category_IMM` so it can't be `HW_Category_MemoryLoad` as well. That's fishy but I don't know if there's a better way. It seems that `HW_Category_MemoryLoad` should perhaps be a flag and not a category.

**Comment by tannergooding** [comment]
> Uh oh, didn't notice that. I think those should be removed.

@fiigii, just want to double check if you can think of anything that would prevent this. If not, I'll open an issue and push it through API review ASAP.

**Comment by mikedn** [comment]
Apparently `ExtractVector128` is in the same boat. Though it could be argued that it's a bit more difficult to get the `m128, ymm2, imm8` encoding without those memory overloads.

**Comment by tannergooding** [comment]
> Apparently `ExtractVector128` is in the same boat. Though it could be argued that it's a bit more difficult to get the `m128, ymm2, imm8` encoding without those memory overloads.

Yeah, I was actually going to ask about that as well. We would need to have `ExtractVector128` be contained in a `StoreVector128` to get this working with a single overload, right?

**Comment by mikedn** [comment]
> We would need to have ExtractVector128 be contained in a StoreVector128 to get this working with a single overload, right?

Yes. I don't think the JIT does anything like this today. But it does something more complicated - generates RMW instructions like `add mem, reg` by containing the `ADD` and `IND` in `STOREIND`. So if it can do that I don't think there'll be any problem attempting to contain an `ExtractVector` in a `StoreVector`.

Hmm, I suppose a quick prototype wouldn't hurt before deciding to remove all these overloads.

**Comment by mikedn** [comment]
Not exactly an elegant implementation but it gets the job done as a prototype: https://github.com/mikedn/coreclr/commit/a00b42e9442ceeeacda7981bbb462bb8ec7a8a21
```C#
        Avx2.Store(p, Avx2.ExtractVector128(Avx2.Add(x, y), 0));
```
generates
```asm
       C5FD1001             vmovupd  ymm0, ymmword ptr[rcx]
       C5FC5802             vaddps   ymm0, ymm0, ymmword ptr[rdx]
       C4C37D190002         vextractf128 xmmword ptr [r8], ymm0, 0
```

**Comment by fiigii** [comment]
> > Looking at this (and I've likely just forgotten) why do we need both a InsertVector128(V256, V128, byte) and a InsertVector128(V256, T*, byte) overload?

> Uh oh, didn't notice that. I think those should be removed.

`ExtractVector128`/`InsertVector128` is used for storing/loading `Vector256` 16-byte by 16-byte, which is a common optimization in AVX SIMD programming. However, RyuJIT currently cannot fold "stores", so I added the pointer overload for `ExtractVector128`. Meanwhile, `InsertVector128` pointer version is added for balancing user experience and avoiding exposing compiler implementation details to API design.

**Comment by fiigii** [comment]
> Not exactly an elegant implementation but it gets the job done as a prototype: [mikedn@a00b42e](https://github.com/mikedn/coreclr/commit/a00b42e9442ceeeacda7981bbb462bb8ec7a8a21)

If we can fold `ExtractVector128`/`InsertVector128` simultaneously, I am ok to remove the pointer overloads of these two APIs.

**Comment by mikedn** [comment]
Might be worth pointing out that native intrinsics don't seem to have a memory version of broadcast. Instead, they produce the mem form by containing a set1 intrinsic, for example `_mm_broadcastb_epi8(_mm_set1_epi8(*c))` generates `vpbroadcastb    xmm1, byte ptr [rdx]`.

Funnily enough, they do this with various levels of success, for example ICC manages to emit 2 broadcasts:
```asm
vpbroadcastb xmm1, BYTE PTR [rdx]
vpbroadcastb xmm3, xmm1 
```

**Comment by tannergooding** [comment]
> Might be worth pointing out that native intrinsics don't seem to have a memory version of broadcast.

I think, for the integral broadcast, we can just get rid of the memory specific overload. It makes things significantly simpler, if nothing else (as AVX2 introduces both `VPBROADCAST reg, reg` and `VPBROADCAST reg, mem`.

The problem then ends up being what to do with the `float`/`double` broadcast methods. The AVX ISA only introduced the `VBROADCAST reg, mem` and AVX2 introduces `VBROADCAST reg, reg`. We could likely only expose a single overload if we can easily say "on a machine with only AVX support, we must stack spill op1 and consume it from memory" (or its exact location if already coming from memory).
