### ISSUE TITLE
Assertion failed 'featureSIMD' 

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22824]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_jitnosimd_tst/59/

**Failed tests:**
baseservices_compilerservices._modulector_runmoduleconstructor_runmoduleconstructor_._modulector_runmoduleconstructor_runmoduleconstructor_cmd

**Log:**
```
baseservices_compilerservices._modulector_runmoduleconstructor_runmoduleconstructor_._modulector_runmoduleconstructor_runmoduleconstructor_cmd [FAIL]
        
        Assert failure(PID 12496 [0x000030d0], Thread: 7956 [0x1f14]): Assertion failed 'featureSIMD' in 'System.SpanHelpers:IndexOf(byref,ubyte,int):int' (IL size 1166)
        
            File: d:\j\workspace\arm64_cross_c---0aaef436\src\jit\simd.cpp Line: 124
            Image: C:\j\workspace\arm64_cross_c---5ab754b1\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root\CoreRun.exe
  Return code:      1
```

**Comment by RussKeldorph** [comment]
@tannergooding @CarolEidt @fiigii

**Comment by tannergooding** [comment]
Issue should be resolved with https://github.com/dotnet/coreclr/pull/22831
