### ISSUE TITLE
The AssemblyLoadContext method calls the LoadFromStream method at runtime to throw an AssemblyLoadContext_Verify_NotUnloading exception.

### ISSUE THREAD

**Issue by fanliang11** [dotnet/coreclr#22902]
Hello .Net Core Community,
[Surging](https://github.com/dotnetcore/surging)  Is a service engine framework based on dotnetcore. It has a problem for a long time. Can you help me? Because need to make the business module hot update, need to generate a dynamic proxy at runtime to achieve grayscale publishing, but use AssemblyLoadContext hot The update loader throws an exception `AssemblyLoadContext is unloading or was already unloaded.`, the code  follows:
```c#
        var stream = CompilationUtilitys.CompileClientProxy(trees,
                assemblys
                    .Select(a => MetadataReference.CreateFromFile(a.Location))
                    .Concat(new[]
                    {
                        MetadataReference.CreateFromFile(typeof(Task).GetTypeInfo().Assembly.Location)
                    }),
                _logger);

            using (stream)
            {
#if NET
                var assembly = Assembly.Load(stream.ToArray());
#else
                var assembly = AssemblyLoadContext.Default.LoadFromStream(stream);
#endif
               return assembly.GetExportedTypes();
}
```

After checking the [AssemblyLoadContext](https://github.com/dotnet/coreclr/blob/2c61b985c0513d9a70eee7221fa15910e7003d16/src/System.Private.CoreLib/shared/System/Runtime/Loader/AssemblyLoadContext.cs), when calling LoadFromStream, first call VerifyIsAlive to check, and when the AssemblyLoadContext is destructed, it will set _state to InternalState.Unloading, which causes the AssemblyLoadContext.Default.LoadFromStream to throw an AssemblyLoadContext_Verify_NotUnloading exception. Can you help me solve it? ?
     Greetings
     Fanly

**Comment by janvorli** [comment]
The Default assembly load context should never be destroyed, it is not collectible. So its internal state should always be "Alive" and never "Unloading". However looking at the code, it seems we have a bug there where we would try to initiate unloading of any context at the process exit. Is it possible that you were getting the exception at the process exit time?

**Comment by fanliang11** [comment]
Thanks for your reply, the process gets an exception when exiting? I temporarily don't have this requirement, can you help me solve it as soon as possible? I am doing a hot update grayscale release now.

**Comment by jeffschwMSFT** [comment]
@fanliang11 can you share a bit more on when this code is executing?  Have you hooked an event to execute on process shutdown?
