### ISSUE TITLE
Tiered JIT compilation causes profilers to not allow source line profiling. 

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#22904]
This is a follow-on issue for issue #22585.    We have applied a patch which fixes the problem where method names are not resolved, but did not solve it completely (line level profiling is still broken),   This issue tracks fixing that. 

SYMPTOM:  If you collect a profile by attaching and detaching from a program, and Tiered JITTing is turned on (it is the default), and the methods of interest are reasonably hot (so that Tiered JIT is likely to have replaced them), then PerfVIew's 'goto Source' feature on those methods do not work.  

The workarounds in #22585 do work here as well. 

The problem can be tested for more easily by running the following program [Program.txt](https://github.com/dotnet/coreclr/files/2912775/Program.txt)

Build with 
```
dotnet build -c Release 
```
so it is non-debug code, and then start collection with 'PerfView collect /maxCollectSec=10' and run the program.   PerfView will stop before the program ends. Then look at the data with 
```
PerfView /keepAllEvents
```
And look at all the events
```
Microsoft-Windows-DotNETRuntimeRundown/Method/DCStopVerbose
Microsoft-Windows-DotNETRuntimeRundown/Method/ILToNativeMapDCStop
```
In the process you ran.  
There should be one ILToNativeMapDCStop  for ever DCStopVerbose but there is not.   WHen that is true it is fixed.

You can also do and end-to-end test where you start the program then collect a profile for 10 sec after the program has started but before it ended.   if you can then look at routines like 'Program.DoLocal1' and do 'GotoSource' then it works.

**Comment by vancem** [comment]
@noahfalk  @jorive  FYI

**Comment by vancem** [comment]
Please consider also addressing #22908 which is related code.

**Comment by noahfalk** [comment]
@kouvel @davmason - One of you guys should probably own this but I am not sure who : )

**Comment by tommcdon** [comment]
@kouvel do you have time to take a look?

**Comment by kouvel** [comment]
> do you have time to take a look?

I'll track it and will try to fix but I can't be sure at the moment

**Comment by tommcdon** [comment]
Thanks @kouvel!
