### ISSUE TITLE
WebBrowser.ObjectForScripting doesn't work

### ISSUE THREAD

**Issue by albahari** [dotnet/coreclr#22916]
(Note: this has also been logged in the winforms repo: https://github.com/dotnet/winforms/issues/248. I've logged it here at the request of @AaronRobinsonMSFT due to the fix requiring work in coreclr.)

When you set the ObjectForScripting property on a WinForms WebBrowser control and then click a link that calls a method on the ObjectForScripting, it displays a script error dialog instead of calling the specified method. It works as expected in .NET Framework.

(A presumably related issue is that HtmlElement.AttachEventHandler appears to be a no-op.)

Note that this issue is blocking a release of LINQPad for .NET Core 3.

**Comment by AaronRobinsonMSFT** [comment]
Fixed with #22930
