### ISSUE TITLE
[JitStress=2] Assertion failed 'curArgTabEntry->regNum == regNum' in 'BringUpTest Main() in morph.cpp line 1285

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#2294]
Configuration:
Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
CoreFX assemblies and CoreCLR tests: release

Env Setting:
COMPlus_JitStress=2

The following CoreCLR tests fail with the above mentioned assertion
1) JIT/CodeGenBringUpTests/FPAvg6
2) JIT/CodeGenBringUpTests/InstanceCalls
3) JIT/CodeGenBringUpTests/StaticCalls
4) JIT/jit64/gc/misc/structfp1_4

**Comment by hoyMS** [comment]
Fix checked in as 2609.
