### ISSUE TITLE
[JitStres=2] Assertion failed 'varDsc->lvDontPromote' in 'System.Decimal Remainder(struct,struct) in lowerxarch.cpp line 297

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#2295]
Configuration:
 Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreCLR tests: release

Env Setting:
COMPlus_JitStress=2

The following tests fail with the above assertion
1) JIT/Directed/coverage/oldtests/lclfldrem_cs_d
2) JIT/Directed/coverage/oldtests/lclfldrem_cs_do
3) JIT/Directed/coverage/oldtests/lclfldrem_cs_r
4) JIT/Directed/coverage/oldtests/lclfldrem_cs_ro
5) JIT/Methodical/divrem/rem/decimalrem_cs_d
6) JIT/Methodical/divrem/rem/decimalrem_cs_do
7) JIT/Methodical/divrem/rem/decimalrem_cs_r
8) JIT/Methodical/divrem/rem/decimalrem_cs_ro
9) JIT/Methodical/divrem/rem/i4rem_cs_d
10) JIT/Methodical/divrem/rem/i4rem_cs_do
11) JIT/Methodical/divrem/rem/i4rem_cs_r
12) JIT/Methodical/divrem/rem/i4rem_cs_ro
13) JIT/Methodical/divrem/rem/i8rem_cs_d
14) JIT/Methodical/divrem/rem/i8rem_cs_do
15) JIT/Methodical/divrem/rem/i8rem_cs_r
16) JIT/Methodical/divrem/rem/i8rem_cs_ro
17) JIT/Methodical/divrem/rem/overldrem_cs_d
18) JIT/Methodical/divrem/rem/overldrem_cs_do
19) JIT/Methodical/divrem/rem/overldrem_cs_r
20) JIT/Methodical/divrem/rem/overldrem_cs_ro
21) JIT/Methodical/divrem/rem/u4rem_cs_d
22) JIT/Methodical/divrem/rem/u4rem_cs_do
23) JIT/Methodical/divrem/rem/u4rem_cs_r
24) JIT/Methodical/divrem/rem/u4rem_cs_ro
25) JIT/Methodical/divrem/rem/u8rem_cs_d
26) JIT/Methodical/divrem/rem/u8rem_cs_do
27) JIT/Methodical/divrem/rem/u8rem_cs_r
28) JIT/Methodical/divrem/rem/u8rem_cs_ro
29) JIT/Methodical/inlining/bug505642/test
30) JIT/Methodical/MDArray/DataTypes/decimal_cs_do
31) JIT/Methodical/MDArray/DataTypes/decimal_cs_ro

Coregen repro steps:
crossgen /App_Paths . /Platform_Assemblies_Paths . /MissingDependenciesOK ./mscorlib.dll

Also happens for Microsoft.CodeAnalysis.VisualBasic.dll and Microsoft.CodeAnalysis.Workspaces.dll 
 and Microsoft.CodeAnalysis.Workspaces.portable.dll.

Before fixing this issue, please verify both the repro steps.

**Comment by LLITCHEV** [comment]
The issue here is that when a shadow variable is created, if it's type is a struct, the lvDontPromote flag is not set. Testing a fix.
