### ISSUE TITLE
[JitStress=2] Assertion failed 'op2->TypeGet() == TYP_STRUCT' in 'System.DateTimeFormat in importer.cpp line 13640

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#2296]
Configuration:
 Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreCLR tests: release

Env Setting:
COMPlus_JitStress=2

The following tests fail with the above assertion
1) JIT/Regression/CLR-x86-JIT/V1-M09/b13647/b13647
2) Regressions/common/AboveStackLimit
3) Regressions/common/CompEx
4) Regressions/common/date
5) Regressions/common/Marshal
6) Regressions/common/pow3
7) Regressions/common/ToLower
8) Regressions/common/Unsafe

**Comment by sejongoh** [comment]
I cannot reproduce the failures.
