### ISSUE TITLE
[Windows x64|x86|arm64] Native vararg test failures

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#22974]
This is a recent regression that causes the following tests to fail:

```
JIT_jit64._mcc_interop_mcc_i11_mcc_i11_._mcc_interop_mcc_i11_mcc_i11_cmd
JIT_jit64._mcc_interop_mcc_i10_mcc_i10_._mcc_interop_mcc_i10_mcc_i10_cmd
JIT_jit64._mcc_interop_mcc_i12_mcc_i12_._mcc_interop_mcc_i12_mcc_i12_cmd
JIT_jit64._mcc_interop_mcc_i13_mcc_i13_._mcc_interop_mcc_i13_mcc_i13_cmd
```

```
0xC0000005
 at MCCTest.MyClass.Sum(Single, ...)
 at MCCTest.MyClass.GetSum()
 at MCCTest.MyClass.Main(System.String[])


Return code: 1
Raw output file: C:\\dotnetbuild\\work\\308bb24e-1a5a-44e4-b913-92d855d0490c\\Work\\68e84c2c-3ffc-49aa-b877-1064b1f421fc\\Exec\\Reports\\JIT.jit64\\mcc\\interop\\mcc_i13\\mcc_i13.output.txt
Raw output:
BEGIN EXECUTION\r
 1 file(s) copied.\r
\" C:\\dotnetbuild\\work\\308bb24e-1a5a-44e4-b913-92d855d0490c\\Payload\\crossgen.exe\" /Platform_Assemblies_Paths C:\\dotnetbuild\\work\\308bb24e-1a5a-44e4-b913-92d855d0490c\\Payload;C:\\dotnetbuild\\work\\308bb24e-1a5a-44e4-b913-92d855d0490c\\Work\\68e84c2c-3ffc-49aa-b877-1064b1f421fc\\Exec\\mcc\\interop\\mcc_i13\\IL;C:\\dotnetbuild\\work\\308bb24e-1a5a-44e4-b913-92d855d0490c\\Work\\68e84c2c-3ffc-49aa-b877-1064b1f421fc\\Exec\\mcc\\interop\\mcc_i13 /in mcc_i13.org /out mcc_i13.exe\r
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0\r
Copyright (c) Microsoft Corporation. All rights reserved.\r
\r
Warning: Could not load type 'System.Runtime.CompilerServices.AssemblyAttributesGoHere' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. while resolving 0x1000016 - System.Runtime.CompilerServices.AssemblyAttributesGoHere.\r
COMPILATION FAILED: file: lclvars.cpp:380 compiling method MCCTest.Common:CheckResult(struct,int):int reason Too many arguments for the \"ret\" instruction to pop\r
COMPILATION FAILED: file: lclvars.cpp:380 compiling method MCCTest.Common:CheckResult(struct,int):int reason Too many arguments for the \"ret\" instruction to pop\r
The JIT compiler encountered invalid IL code or an internal limitation. while compiling method MCCTest.Common.CheckResult\r
COMPILATION FAILED: file: lclvars.cpp:380 compiling method MCCTest.VTypeF:Add(struct):this reason Too many arguments for the \"ret\" instruction to pop\r
COMPILATION FAILED: file: lclvars.cpp:380 compiling method MCCTest.VTypeF:Add(struct):this reason Too many arguments for the \"ret\" instruction to pop\r
The JIT compiler encountered invalid IL code or an internal limitation. while compiling method MCCTest.VTypeF.Add\r
COMPILATION FAILED: file: lclvars.cpp:380 compiling method MCCTest.VTypeF:Check(struct):this reason Too many arguments for the \"ret\" instruction to pop\r
COMPILATION FAILED: file: lclvars.cpp:380 compiling method MCCTest.VTypeF:Check(struct):this reason Too many arguments for the \"ret\" instruction to pop\r
The JIT compiler encountered invalid IL code or an internal limitation. while compiling method MCCTest.VTypeF.Check\r
COMPILATION FAILED: file: lclvars.cpp:380 compiling method MCCTest.Common2`1[VTypeF][MCCTest.VTypeF]:CheckResult(struct,int):int reason Too many arguments for the \"ret\" instruction to pop\r
COMPILATION FAILED: file: lclvars.cpp:380 compiling method MCCTest.Common2`1[VTypeF][MCCTest.VTypeF]:CheckResult(struct,int):int reason Too many arguments for the \"ret\" instruction to pop\r
The JIT compiler encountered invalid IL code or an internal limitation. while compiling method MCCTest.Common2`1[VTypeF][MCCTest.VTypeF].CheckResult\r
Native image mcc_i13.exe generated successfully.\r
 \"C:\\dotnetbuild\\work\\308bb24e-1a5a-44e4-b913-92d855d0490c\\Payload\\corerun.exe\" mcc_i13.exe \r
Expected: 100\r
Actual: -1073741819\r
END EXECUTION - FAILED\r
FAILED\r
Test Harness Exitcode is : 1\r

To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\308bb24e-1a5a-44e4-b913-92d855d0490c\\Payload
> C:\\dotnetbuild\\work\\308bb24e-1a5a-44e4-b913-92d855d0490c\\Work\\68e84c2c-3ffc-49aa-b877-1064b1f421fc\\Exec\\mcc\\interop\\mcc_i13\\mcc_i13.cmd
\r
Expected: True\r
Actual: False
```

**Comment by AndyAyersMS** [comment]
@jashook have you started looking into this? If not, I'll investigate.

**Comment by jashook** [comment]
I have not looked at this yet. Feel free to re-assign.

**Comment by AndyAyersMS** [comment]
I can't repro the crossgen errors, but the tests fail just running normally (even with tier0/minopts):
```
% corerun.exe mcc_i11.exe

System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at MCCTest.MyClass.Sum(Single, ...)
   at MCCTest.MyClass.Sum(Single, ...)
   at MCCTest.MyClass.Main(System.String[])
```
Will update when I know more.

**Comment by AndyAyersMS** [comment]
C/C++ expects floats to be promoted to doubles when passed as varargs, seems like we lost that somewhere. The native side of these tests scans through the varargs values looking for a `-1` sentinel value, so failure to promote leads to the scan continuing on until it runs into an inaccessible stack page and the tests AVs.

Not sure yet if the jit or the stub is responsible for this promotion.

**Comment by AndyAyersMS** [comment]
Regressions come from #22821 where the native side of the test code was modified.

**Comment by AndyAyersMS** [comment]
Could not find anything definitive on whether or not float->double promotion should happen for native varargs. Currently we do not promote, but it seems odd to do things this way, as not promoting means the native side must be non-conforming.

@dotnet/jit-contrib @jkotas anyone know more about this?

**Comment by jkotas** [comment]
I do not think we should be promoting. The managed C++ compiler takes care of it. 

If we started promoting ourselves, we would have a different set of inconsistencies, e.g. should ArgInterator promote too?

**Comment by AndyAyersMS** [comment]
I could be wrong, but it seems like we could promote float to double in the native varargs cases without impacting anything else. We already do a bunch of the magic swizzling in the pinvoke stub (eg passing the first few args in both int and float regs) and it seems like we could be promoting too.

But it's also easy to fix these cases so that we're explicitly promoting in the user code and not pass values with small types, so unless someone objects, that's what I'll do.

**Comment by jkotas** [comment]
This is not just about the JIT. There are number of places that would need to be fixed in VM as well for consistency, e.g. https://github.com/dotnet/coreclr/blob/master/src/vm/clrvarargs.cpp:
- `CalcVaListSize` and `MarshalToUnmanagedVaList` would need to promote too
- `MarshalToManagedVaList` would not round-trip anymore and I am not sure how we would fix that

My point is that vararg support is designed for managed C++. Managed C++ does the promotions in the front end before it gets to us. If you pass `float` vararg in managed C++, we will see it as `double` in the IL signature.

**Comment by jashook** [comment]
If I remember correctly our calling convention doc calls out that we do pass in-promoted types. Following convention here imo would be breaking any existing back compact we support.

My preference would be to continue supporting passing un promoted types and change any test which has a native non managed c++ component to just use promoted types explicitly
