### ISSUE TITLE
[UWP] Unhandled Exception ShardLibary.dll / A fail fast exception occurred.

### ISSUE THREAD

**Issue by AwsomeCode** [dotnet/coreclr#22996]
I am unable to find the cause of this error

App is working with Microsoft.NETCore.UniversalWindowsPlatform -Version 6.2.0-preview1-26926-04 
But Not working with Microsoft.NETCore.UniversalWindowsPlatform -Version 6.1.9 
Native Toolchain is enable in debug mode.

Because of pre Version 6.2.0-preview1 I am not able to update the app on store.

Error
![image](https://user-images.githubusercontent.com/11809653/53752911-f15ef880-3ed5-11e9-9c50-262480a92656.png)

![image](https://user-images.githubusercontent.com/11809653/53752952-09cf1300-3ed6-11e9-9074-a38c681e9ccc.png)

**Comment by sergiy-k** [comment]
Hi @AwsomeCode, Visual Studio 15.9 (or later) contains released/stable version of UWP 6.2.x. You should be able to use it to submit your app to the store.

Any chance you could provide a repro app for the issues that you have encountered? Thank you!

**Comment by jeffschwMSFT** [comment]
@AwsomeCode if you are still seeing an issue, can you help file an issue with VS Feedback (following these instructions).  https://github.com/dotnet/core/blob/master/Documentation/ilcRepro.md  Thanks

**Comment by AwsomeCode** [comment]
@jeffschwMSFT Its working now. Thanks
