### ISSUE TITLE
MemoryFailPoint doesn't work in a docker container

### ISSUE THREAD

**Issue by Cryowatt** [dotnet/coreclr#23011]
I've run into an issue where `MemoryFailPoint` is unable to track memory usage correctly in a docker container. I've created a repo containing a reproduction of the issue [here](https://github.com/Cryowatt/MemoryHole).

The expected behavior is the `MemoryFailPoint` should be able to throw a catchable `InsufficientMemoryException` before the application is OOMKilled by docker. However, the actual behavior is the MemoryFailPoint never throws and the app is killed.

I've been poking around the coreclr and corefx and it seems this issue is tied to some unimplemented sections around memory in Linux. However, I had a similar issue running this code in a Windows container.

**Comment by stephentoub** [comment]
cc: @janvorli, @richlander

**Comment by janvorli** [comment]
The MemoryFailPoint does not work on Unix at all. It was not implemented yet. There was an attempt to enable it (#12362), but it cannot work due to the VirtualQuery behavior difference between Windows and Unix. There is issue #13560 to implement necessary PAL support to enable the MemoryFailPoint assigned to me, but there were other higher priority things that kept me from working on it.

**Comment by Cryowatt** [comment]
Memory in docker containers gets extra hairy as the typical commands for querying memory don't behave in the way you'd might expect. For example, if you run `docker run --rm --memory=40mb alpine free` you'd might expect the results to be 40mb. However the `--memory=40mb` argument doesn't change the available memory, it just changes the amount the process is allowed to use before it's killed.

As far as I can tell the only way to get the actual memory limits from a docker container is be checking cgroups like this:
```PS C:\> docker run --rm --memory=40mb alpine cat /sys/fs/cgroup/memory/memory.limit_in_bytes
41943040```

**Comment by janvorli** [comment]
Right. We already have support for cgroups in coreclr that is currently used for GC, so we can reuse it.

**Comment by Cryowatt** [comment]
This looks like it works now with the latest dotnet core 3.0 preview images.
