### ISSUE TITLE
Race condition in DateTimeFormatInfo.DateTimeOffsetPattern

### ISSUE THREAD

**Issue by ccurrens** [dotnet/coreclr#2301]
There is a race condition that I've seen in some of our services in `DateTimeFormatInfo.DateTimeOffsetPattern`. I was seeing the failure when `DateTimeOffset.ToString()` was returning a string with two offsets, like `12/10/2015 22:13:23 +00:00 +00:00`. I originally noticed this in the full .NET Framework, but was able to reproduce it in CoreCLR, as well.

Upon further investigation, it looks like the race condition can cause one of two formats:

* `MM/dd/yyyy HH:mm:ss`
* `MM/dd/yyyy HH:mm:ss zzz zzz`

In our production code that was occasionally hitting this bug, we weren't directly using `DateTimeFormatInfo`. We were seeing the issue when using a basic `string.Format` with a `DateTimeOffset` as one of the arguments.

Since `CultureInfo` holds onto an instance of `DateTimeFormatInfo`, if your code executes just right you can have all `DateTimeOffset.ToString()` calls with incorrect formats for the life of your application. You can force the `DateTimeFormatInfo` to regenerate the format string calling the setter on the `LongTimePattern` or `ShortDatePattern` properties (although there's no guarantee you won't immediately hit the race condition again).

I've [created a gist](https://gist.github.com/ccurrens/4d3a2670429a9e68064e) that can demonstrates the race condition.

The race is caused because the code is directly working against the `dateTimeOffsetPattern` member when building the pattern string. The pattern string is the concatenation of the short date and long time patterns. Some cultures include the offset in the long time pattern, so the code checks for that. In the case where the offset is not included in the string, it concatenates the offset format like so:

    if (!foundZ) {
        dateTimeOffsetPattern = dateTimeOffsetPattern + " zzz";
    }

Depending on execution order, sometimes this gets executed twice or executed in one thread and not in another.

A non-intrusive fix would be to use a temporary variable to build pattern instead of directly assigning it to the class member. In the case where multiple threads are causing the property to be evaluated, they'll do duplicate work (as it currently does) but will each produce the same correct format string.

**Comment by eerhardt** [comment]
The [MSDN doc for DateTimeFormatInfo](https://msdn.microsoft.com/en-us/library/system.globalization.datetimeformatinfo(v=vs.110).aspx) says:

> Thread Safety
Any public static (Shared in Visual Basic) members of this type are thread safe. Any instance members are not guaranteed to be thread safe.

**Comment by eerhardt** [comment]
Not that I'm saying we shouldn't fix this.  ;).  I'm just calling out that it is documented that the objects are not thread safe.

**Comment by mikedn** [comment]
> The MSDN doc for DateTimeFormatInfo says:

Maybe the documentation is incorrect? It looks like different threads can share the same CultureInfo object (see example below) so that would imply that CultureInfo and related classes must be thread safe.

```C#
            CultureInfo c1 = null, c2 = null;

            var t1 = new Thread(() => { c1 = Thread.CurrentThread.CurrentCulture; });
            var t2 = new Thread(() => { c2 = Thread.CurrentThread.CurrentCulture; });

            t1.Start();
            t2.Start();
            t1.Join();
            t2.Join();

            Console.WriteLine(ReferenceEquals(c1, c2)); // prints true
```

**Comment by stephentoub** [comment]
> Maybe the documentation is incorrect?

Yeah, it appears to be.  That's just the default boilerplate that gets added to docs for .NET types unless overridden, and it doesn't apply well here.  CultureInfo instances are exposed from statics and thus logically their public instance members can be considered to follow the statics guidelines.
cc: @rpetrusha

**Comment by stephentoub** [comment]
> Yeah, it appears to be

I should clarify my comments.  It's possible the docs are in fact correct, in which case we potentially have bugs to fix.

Accessing members of a CultureInfo retrieved from a public static propery that publishes that instance to multiple threads needs to be safe to do from multiple threads concurrently... if it already is (aside from the random bug like the one highlighted in this issue), then we should update the docs (and fix any other bugs we might find). And if the docs are correct and there are actually bugs here, then we should find and fix those in the source.

It may also be that the runtime only publishes certain instances (e.g. like a singleton for invariant culture), in which case it may be that the docs are correct in general but should have a caveat about these certain cases.  And we should ensure that for those specific cases it actually is safe in the implementation.

**Comment by rpetrusha** [comment]
It's worth noting that the gist instantiates a DateTimeFormatInfo object by calling the class constructor, which returns an instance DateTimeFormatInfo object. If the code is changed to return the object from a static property (like DateTimeFormatInfo.InvariantInfo) or CultureInfo.InvariantCulture, the race condition disappears, and the ToString method works as expected.
We'll devote some attention in the documentation to noting which culture-related members return types that are not thread-safe.

**Comment by ccurrens** [comment]
@rpetrusha I don't think that the race condition disappears, I think it just becomes *far* less likely that you'll hit it.

We were seeing this simply by having two threads calling `DateTimeOffset.ToString()` at nearly the same time. `DateTimeOffset` uses `DateTimeFormatInfo.CurrentInfo` (which in turn pulls from the thread's `CurrentCulture` property). Granted, we only saw it occasionally. I chose to use an `DateTimeFormatInfo` instance in order to quickly and easily reproduce the bug.

**Comment by stephentoub** [comment]
@rpetrusha, @ccurrens is correct.  @ccurrens example was just highlighting the possibility of the race condition by using new objects each time, whereas changing it to use a static means that once the object's field has been initialized there's no longer the possibility of a race condition, but there was still one during the initialization.

In briefly looking through the code, I think the docs are technically correct, they're just misleading due to the absence of a discussion of instances being available through the statics.
