### ISSUE TITLE
InvalidOperationException when calling GetData on IDataObject

### ISSUE THREAD

**Issue by livarcocc** [dotnet/coreclr#23042]
@nick-beer commented on [Fri Nov 16 2018](https://github.com/dotnet/core-sdk/issues/156)

In porting our test suite to .NET Core 3.0, I'm seeing a new failure in one of our tests.  When trying to call the GetData API on an instance of IDataObject returned from Clipboard.GetDataObject, I get an InvalidOperationException with the following message:

*This type has a ComVisible(false) parent in its hierarchy, therefore QueryInterface calls for IDispatch or class interfaces are disallowed*

This may be related to issue #149

To reproduce the issue:
- clone the repo https://github.com/nick-beer/IDataObjectBug
- Run the test *DataObject_Fails* from within the 'Tests' folder

**Comment by danmosemsft** [comment]
@AaronRobinsonMSFT yes - the recommended way is to use https://github-issue-mover.appspot.com. It is "approved" for these repos.

**Comment by AaronRobinsonMSFT** [comment]
@ericstj, @jkotas, or @danmosemsft  Do any of you have a suggestion on what could better convey the issue to the user?

> "This type has a ComVisible(false) parent in its hierarchy... "

Is technically the issue and 

> ... therefore QueryInterface calls for IDispatch or class interfaces are disallowed."

is some implementation detail about what the `ComVisible` attribute implies. I am struggling to come up with a message that could convey the issue in an actionable way by the user. Suggestions are welcome.

**Comment by danmosemsft** [comment]
Can the message include the name of the type ("this type") and name of the problematic "parent"?

We can also, if it's helpful, add a fwlink to some documentation that explains what to do. It's pretty ugly but there is precedent. Usually folks just search for the message string or error code.

eg
```
 3343:     <value>Type '{0}' cannot be serialized by XmlSerializer, serialization code for the type is missing. Consult the SDK documentation for adding it as a root serialization type. http://go.microsoft.com/fwlink/?LinkId=613136</value>
```

**Comment by AaronRobinsonMSFT** [comment]
Including the current type is possible. Getting at the parent is going to require a bit more work. We use a flag that was set to indicate some base class isn't visible. This means we would need to walk the hierarchy again, not impossible just annoying.

I guess it is the right thing to do so I will do it. Thanks for the suggestion.

**Comment by AaronRobinsonMSFT** [comment]
@ericstj I don't think your small example fails anymore. I am not entirely sure why it doesn't, but I can't get it to fail with the latest Core 3.0 preview.

**Comment by ericstj** [comment]
We worked around that specific case in WPF by making it do the same thing WinForms was doing. https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted/commit/78579857c2a7226db1e08d3c8b818bc9f83aa149?refName=refs%2Fheads%2Fmaster&_a=compare&path=%2Fsrc%2FWPF%2Fsrc%2FPresentationCore%2FCSharp%2FSystem%2FWindows%2Fclipboard.cs

You'll need to construct a different repro to test this, sorry.

**Comment by AaronRobinsonMSFT** [comment]
@ericstj Oh, glad you were able to work around it. Thanks for the clarification.
