### ISSUE TITLE
ToString Hour Not Working According To Spec

### ISSUE THREAD

**Issue by philippemercure** [dotnet/coreclr#23049]
You can try this code in try.net.code

TLTR : DateTime.ToString("h"), not working ; DateTime.ToString("h "), working

using System;
using System.Collections.Generic;
using System.Linq;

public class Program
{
  public static void Main()
  {
    var dateTime = DateTime.Now; // 12:43:20 AM
    
    // All Working In Complexe Format
    Console.WriteLine("DateTime: " + dateTime.ToString("hh:mm:ss tt")); // Output; DateTime: 12:43:20 AM
    Console.WriteLine("DateTime: " + dateTime.ToString("HH:mm:ss tt")); // Output; DateTime: 00:43:20 AM

    // Hour Working With An Extra Space
    var hours1 = dateTime.ToString("h ");
    Console.WriteLine("Hours 1: " + hours1); // Output; Hours 1: 12

    try
    {
      // Hour Not Working, But It Should According To : https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      var hours2 = dateTime.ToString("h");
      Console.WriteLine("Hours 2: " + hours2); // Won't output
    }
    catch (Exception exception)
    {
      Console.WriteLine("Hours 2: " + exception.Message); // Output; Hours 1: Input string was not in a correct format
    }
  }
}

**Comment by stephentoub** [comment]
While a bit strange, this is actually by design and documented:
https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#the-h-custom-format-specifier
"If the "h" format specifier is used without other custom format specifiers, it is interpreted as a standard date and time format specifier and throws a FormatException."

The same applies to other format specifiers, like "K": when used on its own, it means one thing, and when used as part of a larger string, it means something else... the presence of that extra space means it switches from one case to the other.

Hope that helps.

**Comment by philippemercure** [comment]
I would have understand this behaviour if the h format was use as a "Standard Date and Time Format Strings" but it is not. Is it because of optimisation that the "h" format is interpreted this way when it is pass alone. I have a UseCase that would require to only have the hour of a DateTime in a UI. I'm generating the string for the display DateTime in the backend according to the user language and according to the business request. I need to display in English : "Wednesday, March 6, 7 AM to 9 AM" or "Wednesday, March 6, 7:30 AM to 9:30 AM" and in French : "Mercredi 6 mars, 7 h à 9 h" or "Mercredi 6 mars, 7 h 30 à 9 h 30". Those string couldn't be build with a simple Standard format. Right now, I'm passing custom string format down a stack to build this. Without the custom "h" format specifier I need to do a special logic to handle the fact that I can't use the custom "h" format specifier alone. I'm left with a strange final code that you can see in the print screen. Could this custom "h" format specifier and other could be handle in any way. Thanks.

![code](https://user-images.githubusercontent.com/4966091/53886119-493c5300-3fed-11e9-9d68-7f51685a9ec4.jpg)
![output french](https://user-images.githubusercontent.com/4966091/53886120-493c5300-3fed-11e9-93cc-ebf4e3861ad0.jpg)
![output english](https://user-images.githubusercontent.com/4966091/53886121-49d4e980-3fed-11e9-84fc-1c48cc92f412.jpg)

**Comment by stephentoub** [comment]
> Could this custom "h" format specifier and other could be handle in any way

cc: @tarekgh, @krwq

**Comment by tarekgh** [comment]
Why you can just handle this by creating the proper format pattern instead of formatting every date/time part separately? so you may write GetTime like:

```C#
        static string HoursWithMinutesFormat;
        static string HoursOnlyFormat;

        static void CreateFormatPattern(string twoLettersCultureName)
        {
            if (twoLettersCultureName == "en")
            {
                HoursWithMinutesFormat = "hmm tt";
                HoursOnlyFormat = "h tt";
                return;
            }

            HoursWithMinutesFormat = "H 'h'mm";
            HoursOnlyFormat = "H 'h'";
        }

        static string GetTime(DateTime dateTime, string HoursWithMinutesFormat, string HoursOnlyFormat)
        {
            return dateTime.Minute > 0 ? dateTime.ToString(HoursWithMinutesFormat) : dateTime.ToString(HoursOnlyFormat);
        }
```

As @stephentoub pointed  out in the docs having single letter specifier will have different meaning. let me know if you have any other questions.

**Comment by philippemercure** [comment]
Mmm, that work pretty well. I didn't know we could escape text in a format specifier, the more you know, :). Thanks for you help.
