### ISSUE TITLE
pmi-diff jobs fail because of the wrong folder path.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#23045]
[ci example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_pmi_asm_diffs_prtest/17/consoleFull#-410211996a086b3e-df04-41d2-bc4d-43e8f9406d07)

We run them like:
```
python -u %WORKSPACE%\tests\scripts\run-pmi-diffs.py -arch x64 -ci_arch x64 -build_type Checked
powershell -NoProfile -Command "Add-Type -Assembly 'System.IO.Compression.FileSystem'; [System.IO.Compression.ZipFile]::CreateFromDirectory('_\pmi\asm', '.\dasm.Windows_NT.x64.Checked.zip')"
```
the second command expects diffs to be in `%WORKSPACE%\_\pmi\asm` but it was changed by #20812
that deleted this code:
```
if scratch_root is None:
  scratch_root = os.path.join(diff_root, '_', 'pmi')
else:
  scratch_root = os.path.abspath(scratch_root)
```
that was creating this folder, so now diffs are in `%WORKSPACE%`.

Probably on other platforms there are different failures, PR that ran several job #22963.

PTAL @jashook, @BruceForstall

**Comment by BruceForstall** [comment]
Looks like the Linux arm64 pmi asm diffs task fails because it uses `zip`, which isn't on the machine. Should convert that to `tar`
