### ISSUE TITLE
Assertion failed '(varDsc->lvIsParam && !varDsc->lvIsRegArg) || isPrespilledArg'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#23059]
40 tests fail with this assert.

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_jitx86hwintrinsicnosimd/384/consoleFull

e.g.,
```
Assert failure(PID 6252 [0x0000186c], Thread: 6160 [0x1810]): Assertion failed '(varDsc->lvIsParam && !varDsc->lvIsRegArg) || isPrespilledArg' in 'System.Runtime.Intrinsics.X86.Ssse3:Abs(struct):struct' (IL size 7)
01:26:52         
01:26:52             File: d:\j\workspace\x86_checked_w---d6dc6bd7\src\jit\compiler.hpp Line: 2039
01:26:52             Image: D:\j\workspace\x86_checked_w---d6dc6bd7\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

with:
```
set COMPlus_TieredCompilation=0
set COMPlus_EnableIncompleteISAClass=1
set COMPlus_FeatureSIMD=0
```

**Comment by BruceForstall** [comment]
@fiigii @tannergooding @CarolEidt

**Comment by tannergooding** [comment]
This first failed in job 383 which was commit `04fed62`. Job 382 also failed, but due to other reasons and was commit `9d3f264`.

**Comment by tannergooding** [comment]
The list of new commits tested in job 383 are the following (which means one of them is the likely culprit for the regression):
* Fix condition for calling EvalArgsToTemps (commit: 30996b8) (detail / githubweb)
* Update dependencies from https://github.com/dotnet/core-setup build (commit: 8409f2a) (detail / githubweb)
* Move EEClassLayoutInfo::CollectLayoutFieldMetadataThrowing to class.cpp (commit: 1278da1) (detail / githubweb)
* Fix rid choice setup stress (#23004) (commit: 36cf483) (detail / githubweb)
* Disable tests for open issues (#22976) (commit: d17b66c) (detail / githubweb)
* Publish logs as pipeline artifacts for build-job.yml and test-job.yml (commit: 857567c) (detail / githubweb)
* Update dependencies from https://github.com/dotnet/corefx build (commit: 0b6aa70) (detail / githubweb)
* Pass -priority= argument directly to build-test.cmd (#23007) (commit: a217ea2) (detail / githubweb)
* Remove BEGIN/END_EXCEPTION_GLUE from botr (commit: 77fcaf6) (detail / githubweb)
* Remove loose dependency in runtime on System.ComponentModel. (#23010) (commit: 88ada23) (detail / githubweb)
* Do not treat warnings as errors during corefx build in docker. (#23014) (commit: 14caedf) (detail / githubweb)
* Remove dead ContainToAppDomain (#23021) (commit: 7d54e61) (detail / githubweb)
JIT: remove unneeded ref count updating traversal from optimizer (commit: 04fed62) (detail / githubweb)

**Comment by tannergooding** [comment]
I am working on bisecting these commits to determine which was the actual cause of failure.

**Comment by tannergooding** [comment]
@CarolEidt, looks like this failure is caused by https://github.com/dotnet/coreclr/pull/22791

**Comment by tannergooding** [comment]
This requires both `TieredCompilation=0` and `FeatureSIMD=0` to reproduce.

**Comment by CarolEidt** [comment]
@tannergooding - thanks for narrowing this down! I'll look at it.
