### ISSUE TITLE
Remove signing workaround of crossgen assemblies

### ISSUE THREAD

**Issue by chcosta** [dotnet/coreclr#23081]
This should no longer be necessary with a new version of Arcade SDK - https://github.com/dotnet/coreclr/blob/7d6d1eaa02c46cdabde9bef8a3f08cd58775bc08/eng/Versions.props#L26-L28

https://github.com/dotnet/arcade/pull/2079 fixed this

/cc @hoyosjs @RussKeldorph

**Comment by hoyosjs** [comment]
We haven't been able to consume a more recent version of the SDK's. Helix fails on Mac for us right now starting `2.0.0-beta.19151.5`, where Mac agents cant find the payload. I asked alex and he didn't see something off the bat, but I didn't continue investigating.

**Comment by hoyosjs** [comment]
Once I get that in I'll take a look at removing this piece and test all works as expected.

**Comment by RussKeldorph** [comment]
@hoyosjs Thanks for volunteering.

@jashook @sbomer @echesakov

**Comment by hoyosjs** [comment]
Can't be fixed until #22967 gets merged
