### ISSUE TITLE
Config file validation

### ISSUE THREAD

**Issue by cshung** [dotnet/coreclr#23083]
In general, input validation is weak, the earlier we can block bad input, the more reliable the system is.

- [ ] Handle if a key is specified is not in the set of expected set 
- [ ] Handle if the specified provider value is invalid (according to the provider grammar)
- [ ] Handle if the specified output path does not exist.
- [ ] Handle if the specified circularMB is not a positive number (showing me something, not just silently default) [should really have a range check to avoid DoS]
- [ ] Handle if the specified processID is not a positive number
- [x] Handle if the specified multiFileSec is not a positive number [should really have a range check to avoid DoS]

Provider grammar:
- [ ] Empty provider name
- [ ] Empty keyword
- [ ] Level not a number (showing me something, not just silently default)
- [ ] Level not in range
- [ ] Empty filter data key
- [ ] Empty filter data value (allowed?)
- [ ] Duplicated filter data key

Nice to have:
- [ ] Consider canonicalizing the casing for the keys
- [ ] Consider providing a mechanism for writing comments
- [ ] Consider supporting hexadecimal numbers

All of the above should be tested that it doesn't break anything - data validation implemented or not.

**Comment by cshung** [comment]
CC @vancem

**Comment by jorive** [comment]
One way to deal with internal errors, and provide a way to surface it to the clients could be to create an event that can be seen by an event listener.
Another way could be to provide a way to register a callback/event to "EventSource"?

**Comment by tommcdon** [comment]
cc @jorive

**Comment by tommcdon** [comment]
@jorive can this issue be resolved?

**Comment by noahfalk** [comment]
I opened #24112 to track getting rid of the config file. I think that renders this issue moot. Even if we don't do #24112 right away we are re-affirming that the config file was an undocumented and unsupported option that we do not plan to invest in further.
