### ISSUE TITLE
Dotnet new project create automatically sln

### ISSUE THREAD

**Issue by aclerbois** [dotnet/coreclr#23107]
Hello, 

An improvment valuable for the dotnet creation template should be to add a parameter to create a new sln file and attach the new project into. 

Current scenario : 

dotnet new "template" -n "ProjectName"
dotnet new sln -n "ProjectName"
dotnet sln add "ProjectName/ProjectName.csproj"

Have only one line for example : 

dotnet new "template" -n "ProjectName" -newSln

What do you think about this idea ? 

Best regards,

Adrien C.

**Comment by AaronRobinsonMSFT** [comment]
@aclerbois, Thanks for the suggestion. This repo is for the clr itself rather than `dotnet` and other CLI tools. I would suggest this be moved to the https://github.com/dotnet/core-sdk repo where it can receive the appropriate attention.
