### ISSUE TITLE
[arm64] Improve prolog/epilog single reg save/restore w/SP adjustment

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#23102]
`CodeGen::genPrologSaveReg` and `CodeGen::genEpilogRestoreReg()` should fold in an optional `spDelta` adjustment to the STR/LDR instruction as pre-index/post-index, if possible.

**Comment by AndyAyersMS** [comment]
If this is really an enhancement we should move it to future.

**Comment by BruceForstall** [comment]
I implemented this with https://github.com/dotnet/coreclr/pull/23119, just forgot to reference / close the issue.
