### ISSUE TITLE
Slowness running jobs

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#23118]
Windows/arm:

I see in https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_r2r_jitstressregs8_flow/50/console:
```
01:58:09 Started by an SCM change
01:58:09 Building remotely on win2012-19a9f0 (win2012-20180911) in workspace D:\j\workspace\arm_cross_che---fbdfb62b
01:58:09 [WS-CLEANUP] Deleting project workspace...
01:58:09 Selected Git installation does not exist. Using Default
01:58:09 Cloning the remote Git repository
```

but it's been doing this for 4 days and 14 hours!

**Comment by BruceForstall** [comment]
@jashook @RussKeldorph I haven't paid attention to the Windows/arm32 machines/jobs lately, but I saw this once or twice. Should I/we create a core-eng issue and get someone to look at this?

**Comment by jashook** [comment]
@BruceForstall yes, this looks like it should have an eng issue.
