### ISSUE TITLE
JIT/Methodical/Boxing/misc/_dbgconcurgc_il/_dbgconcurgc_il.sh fails

### ISSUE THREAD

**Issue by hoyMS** [dotnet/coreclr#2311]
The test is disabled in this PR : https://github.com/dotnet/coreclr/pull/2288

**Comment by sivarv** [comment]
This test fails only on Linux as per Pull request that disabled this test.

**Comment by hoyMS** [comment]
This appears to be a test issue : System.Threading.Thread::Abort is not supported in coreclr.

**Comment by hoyMS** [comment]
Fix  checked in as 2592.
