### ISSUE TITLE
Find out if EventSource callbacks may lead to recursive call

### ISSUE THREAD

**Issue by sywhang** [dotnet/coreclr#23126]
In EventCounter's current implementation, under CounterGroup::OnEventSourceCommand there is a comment that says:

```
// Recursion through EventSource callbacks possible.  When we enable the timer
// we synchonously issue a EventSource.Write event, which in turn can call back
// to user code (in an EventListener) while holding this lock.   This is dangerous
// because it means this code might inadvertantly participate in a lock loop. 
// The scenario seems very unlikely so we ignore that problem for now.  
lock (this)      // Lock the CounterGroup
```

I have not looked deep into the EventSource callback implementation to see whether this is possible, but if it is, it may lead to a deadlock we don't want. We should investigate & add test for it as needed.

**Comment by tommcdon** [comment]
@sywhang has this issue been investigated or do we have evidence this is occuring?  I'm moving this issue out to future, though feel free to move it back to 3.0 if needed

**Comment by sywhang** [comment]
This issue is fixed in master now.
