### ISSUE TITLE
Performance regression in .Net Core 3.0 -- private working set

### ISSUE THREAD

**Issue by jmiddour** [dotnet/coreclr#23139]
We converted a console application to .Net core from the full framework.  When targeting .Net Core 2.2, the memory & wall clock performance was very close to full framework targeting 4.6.2 and running on 4.7.  This was on Enterprise Client 1709 and using VS2019P3.

However, when targeting .net core 3.0, performance was significantly worse.  We noticed that private working set increased from 8Mb to ~450Mb.  Wall clock time was also about 20% worse.

We collected the following information to aid in investigation.  We plan to go into production on .Net Core 2.2, but are completely blocked from .Net Core 3.

On the left is the VM map from .Net Core 3.0.  On the right is from the full framework
![VmMap1](https://user-images.githubusercontent.com/18984850/54053475-628ffb80-41b5-11e9-9750-630e44e6ef93.png)

On the left is full framework.  On the right is .Net Core 3.0.  The lines are (in order):
process.privateworkingset64
gc.totalmemory(false)
gc.totalmemory(true)
process.privateworkingset64
![vmmap2](https://user-images.githubusercontent.com/18984850/54053701-227d4880-41b6-11e9-8124-2bb2fc4bc3fb.png)

VM Map from .Net Core 2.2:
![vmmap3](https://user-images.githubusercontent.com/18984850/54053809-74be6980-41b6-11e9-8597-d4d3bdef4fef.png)

We also tested tiered compilation both enabled on 2.2 and disabled on 3.0 and that did not change the results.

@richlander  @rido-min

**Comment by jkotas** [comment]
The numbers suggest memory leak. [perfview](https://github.com/Microsoft/perfview/blob/master/documentation/Downloading.md) or any other memory profiler is the way to trade it down.

Vance's tutorial for how to trade down the managed memory leaks using [perfview](https://github.com/Microsoft/perfview/blob/master/documentation/Downloading.md):  https://channel9.msdn.com/Series/PerfView-Tutorial/Tutorial-10-Investigating-NET-Heap-Memory-Leaks-Part1-Collecting-the-data

**Comment by richlander** [comment]
I was working with this developer. I got them to create Perfview traces but forgot them. They are going to send them to me on Monday.

**Comment by RussKeldorph** [comment]
@richlander did you get the traces?

**Comment by richlander** [comment]
@RussKeldorph The traces were re-created today. We should have them later today.

**Comment by jmiddour** [comment]
The traces have been recreated and sent.  Thank you for looking at the issue with us.

**Comment by jkotas** [comment]
This was tracked down to GC behavior differences related to job objects.

The GC is allocating excessively large amount of memory for mark list when the process is running inside job objects in current .NET Core 3.0.

It just happens that https://github.com/dotnet/cli/pull/10720 changed `dotnet run` to run child processes inside job object as well. It makes running inside job object much more common compared to what it used to be.

**Comment by richlander** [comment]
Any update on this @Maoni0 ?

**Comment by Maoni0** [comment]
this was an issue with processes running in a job object that does NOT have a memory limit specified. fixed with [#23297](https://github.com/dotnet/coreclr/pull/23297).

**Comment by jmiddour** [comment]
All,
We have re-run our code using the preview 4 SDK (from @richlander) and can confirm that the issue has been resolved.
In fact, total memory usage is down ~10% from Core 2.2 now.  Thank you all for your efforts!

**Comment by Maoni0** [comment]
great! thanks for verifying. I'll close this then.

**Comment by clickschools** [comment]
> All,
> We have re-run our code using the preview 4 SDK (from @richlander) and can confirm that the issue has been resolved.
> In fact, total memory usage is down ~10% from Core 2.2 now. Thank you all for your efforts!

Screenshot this and share here also

**Comment by galmok** [comment]
How does one get "private working set" in dotnet core 3?
