### ISSUE TITLE
IsEquivalentTo returns false for equivalent types in .NET Core preview 3

### ISSUE THREAD

**Issue by ymassad** [dotnet/coreclr#23131]
I am trying to play with [type equivalence in .NET](https://docs.microsoft.com/en-us/dotnet/framework/interop/type-equivalence-and-embedded-interop-types). I was able to make it work for both the .NET Framework and .NET Core.

It seems that .NET Core before V3.0 did not support this feature. Or at least I was not able to make it work.

The source code is available here:
https://github.com/ymassad/TypeEquivalenceExample

The issue is that, the [IsEquivalentTo method](https://docs.microsoft.com/en-us/dotnet/api/system.type.isequivalentto?view=netframework-4.7.2) returns False when it should return True. It returns False although equivalent types are used interchangeably. It returns True when using the .NET Framework.

**Comment by jkotas** [comment]
We are missing `IsEquivalentTo` override on `RtType`

cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
I honestly didn't know this API existed. We have a test hole. Will get this handled today.

@ymassad Thanks for reporting it!
