### ISSUE TITLE
Assert during MScorlib crossgen

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#2314]
I looked into this and it appears to be a regression introduced by the following change from Matt that introduced SecurityCritical SafeSortHandle type that is being referenced in the Transparent CompareInfo.ctor in CompareInfo.Unix.cs. Matt, can you please look into this?

Thanks,
Gaurav

Commit: 6e2b263b0b1925f1e1d99c652afef460b63c620d[6e2b263]
Parents: daa24b15ea
Author: Matt Ellis <matell@microsoft.com>
Date: November 19, 2015 at 3:00:20 PM PST
Commit Date: November 20, 2015 at 1:33:34 PM PST

Cache UCollators in CompareInfo

Creating a UCollator is an expensive operation and we are presently
doing it on ever collation operation. We can improve this by caching
the UCollators we use for collation on the CompareInfo object itself.

This change introduces a new method GetSortHandle which gives back an
opaque wrapper which can be used in collation operations instead of a
culture name.

Internally we represent this is a struct holding the two types of
UCollators we care about (if we add additional collators per locale with
different options to handle other types of CompareOption flags, we can
cache these as well). Collation methods can get a `const UCollator*`
reference from the sort handle which is safe to share across
threads (per the ICU Design Guidelines[1]).

Unfortunately, tracking the lifetime of the SortHandle itself is not as
straightfoward as I would like. Right now, we use a SafeHandle to wrap
the internal handle and rely on the finalizer of the class to clean up
the native resources. However this means that the following code sample
will create two finalizable objects:

```csharp
var c1 = new CultureInfo("en-US").CompareInfo;
var c2 = new CultureInfo("en-US").CompareInfo;
```

If this ends up being an issue, we could explore an approach where we
keep a cahce of SortHandles in managed code and pass out references to
that SortHandle which would let us share a single SortHandle for a given
locale across more than one CompareInfo object.

Wins are seeing in places where we previously did lots of string
comparisions in a tight loop (for example: dotnet/corefx#3811) moving
these operations down to ~6ms per iteration vs ~330ms on my local machine.

[1]: http://userguide.icu-project.org/design

 Repro output:

# ./crossgen ./mscorlib.dll
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.
 
 
Assert failure(PID 7323 [0x00001c9b], Thread: 7323 [0x1c9b]): Consistency check failed: Accessibility check failed while compiling platform assembly. Are you missing FriendAccessAllowed attribute? Caller: mscorlib System.Globalization.CompareInfo .ctor Target: SafeSortHandleFAILED: !pContext->GetCallerAssembly()->GetManifestFile()->IsProfileAssembly()
    File: /home/lubo/SVS/src/vm/clsload.cpp Line: 5136
    Image: /home/lubo/coreclr-tests/Windows_NT.x64.Debug/Tests/coreoverlay/crossgen
 
Aborted (core dumped)
root@lubo-Virtual-Machine:~/coreclr-tests/Windows_NT.x64.Debug/Tests/coreoverlay#

@LLITCHEV

**Comment by ellismg** [comment]
@gkhanna79 Do you understand why this only fails during crossgen?  Is it because the type is not is not treated as opportunistically critical unlike at runtime?

I'm going to fix up these annotations but I don't understand why we aren't also seeing this at runtime?

**Comment by gkhanna79** [comment]
I believe this will fail at runtime as well as JIT will be asked to generate code to invoke the FieldAccessException helper that will raise the exception when the attempt to access the field takes place. There is no automatic accessibility changes that happen at runtime.
