### ISSUE TITLE
ThreadPool and GetMinThreads in Linux .NET Core

### ISSUE THREAD

**Issue by zcsizmadia** [dotnet/coreclr#23176]
I am using using .NET Core for Linux in NUMA nodes (64+ cores). It seems the ThreadPool behaves differently under Windows and Linux if the machine has more than 24 cores. Running the code below under Windows maximizes CPU usage  and the ThreadPool grows until the CPUs are 100% utilized, however under Linux, the total CPU utilization is only ~30%.

It looks like Windows GetMinThreads(...) returns the number of cores, Linux returns (24,24) for a machine with 128GB RAM and 88 cores, and (32,32) for a machine with 64GB RAM and 96 cores. BTW the code below runs correctly if SetMinThread or COMPlus_ThreadPool_ForceMinWorkerThreads is used to force the min thread count.

Is the correct workaround to tweak SetMinThreads or tweak the thread pool climbing parameters?

Thanks!

```
public static int Main(String[] args) {  
    // Create many tasks to use ALL the CPU cores for expectedTotalRunLengthMs
    // Every task is using a specific CPU for a duration of taskRunLengtMs
    // We expect all the tasks to be done in expectedTotalRunLengthMs if all CPUs are used all the time

    int expectedTotalRunLengthMs = 10000;
    int taskRunLengthMs = 10;
    int numberOfTasks = (expectedTotalRunLengthMs/taskRunLengthMs) * Environment.ProcessorCount;

    Console.WriteLine($"Number of processors = {Environment.ProcessorCount}");
    Console.WriteLine($"Task run time = {taskRunLengthMs} ms");
    Console.WriteLine($"Total execution time = {expectedTotalRunLengthMs} ms");
    Console.WriteLine($"Number of tasks = {numberOfTasks}");

    Task[] tasks = new Task[numberOfTasks];
    Stopwatch w = Stopwatch.StartNew();
            
    for (int i = 0; i < tasks.Length; i++)
        tasks[i] = Task.Run(() => {
            // Eat CPU cycles
            Stopwatch lw = Stopwatch.StartNew();
            double d = 1;
            while (lw.Elapsed.TotalMilliseconds < taskRunLengthMs)
                d += Math.Sqrt(d);
            });
            
    Task.WaitAll(tasks);
    w.Stop();

    Console.WriteLine($"Done in {w.Elapsed.TotalMilliseconds} ms (expected {expectedTotalRunLengthMs} ms).");

    return 0;
} 
```

**Comment by stephentoub** [comment]
cc: @kouvel

**Comment by janvorli** [comment]
@zcsizmadia NUMA is not supported in the official builds of .NET Core on Unix yet. I have recently found that our official build machines are missing the libnuma dev package installation (pending PR https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/74 should fix that) and so we build coreclr with NUMA support disabled even though the support for NUMA was added to our source code base quite some time ago. But even when built locally with the NUMA support enabled, we've found there are some issues with specific processor / NUMA node configurations in GC. This was fixed in #22861.

However, even without the NUMA enabled in our official builds, we should support the first 64 CPUs.

**Comment by zcsizmadia** [comment]
@janvorli Thanks for your support! Is there a dirty way of building 2.2.3 and force my development environment to use this custom build, before it is officially released?

**Comment by janvorli** [comment]
What you can do to try that (on Linux) is:
* publish your app for the linux-x64 RID (`dotnet publish -r linux-x64`)
* rebuild the coreclr repo from the same commit as 2.2.3 uses, with the libnuma-dev installed. You can find the commit number using `strings libcoreclr.so | grep "@(#)"` on the libcoreclr.so from the publish folder and then use `git checkout that_commit_number` in the coreclr repo. Use `build.sh x64 release` command for building the repo. See https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md if you need more help.
* copy all files from bin/Product/Linux.x64.Release directory in the coreclr repo to the publish folder that the dotnet publish command prints during the build.
* launch your app using the executable from the publish folder

**Comment by zcsizmadia** [comment]
So the next official release of 2.2 (2.2.3) will  have numa enabled?

**Comment by zcsizmadia** [comment]
@janvorli I rebuilt my coreclr with numa-dev packages installed on my local machine with "./build.sh x64 release", but ran int the following problem. It seems my libnuma.so is loaded, however InitCPUGroupInfoAPI (src/utilscode/utils.cpp), because  GetLogicalProcessorInformationEx is not available in the module referenced by GetCLRModule().

If I grep the "nm -D" of all the .so files in the bin/Product/Linux.x64.Release folder, only libsuperpmi-shim-*.so files seem to export that function.

Can you give me a pointer what I might be missing in my build process?

**Comment by janvorli** [comment]
Ah, ok, this was a bug fixed recently. Can you try to add GetLogicalProcessorInformationEx, GetNumaHighestNodeNumber, VirtualAllocExNuma, SetThreadGroupAffinity, GetThreadGroupAffinity and GetNumaProcessorNodeEx to https://github.com/dotnet/coreclr/blob/master/src/dlls/mscoree/mscorwks_unixexports.src?

**Comment by zcsizmadia** [comment]
Is this the preferred way to fix the dynamic function linking, fixed by #22861 (static linking vs GetProcAddress)?

**Comment by janvorli** [comment]
The dynamic linking was there from old times when .NET needed to work on Windows older than Windows 7 that didn't have these functions, thus they were optionally dynamically loaded at runtime. It is not needed on Windows anymore since we don't support such old windows systems and it is not needed on Unix as the functions are always implemented in PAL.

**Comment by kouvel** [comment]
Sounds like this has been resolved, closing. Please reopen if there is work remaining.
