### ISSUE TITLE
Accessing auto-property performance regression

### ISSUE THREAD

**Issue by stevenbrix** [dotnet/coreclr#23181]
Accessing Auto-Properties compared to using a field seems to have regressed in 3.0. 

[Here](https://github.com/dotnet/coreclr/files/2953667/CSharpNetCoreConsolePlayground.zip) is a repro that cross-targets netfx, netcore2.1, and netcore3.0 and shows about an 18% slowdown.

**Comment by epeshk** [comment]
Are you sure? I'm try to reproduce this measurement with Benchmark.NET and get same results. 
```BenchmarkDotNet=v0.11.4, OS=Windows 10.0.17134.1 (1803/April2018Update/Redstone4)
Intel Core i5-5200U CPU 2.20GHz (Broadwell), 1 CPU, 4 logical and 2 physical cores
Frequency=2143475 Hz, Resolution=466.5321 ns, Timer=TSC
.NET Core SDK=3.0.100-preview-010184
  [Host]     : .NET Core 3.0.0-preview-27324-5 (CoreCLR 4.6.27322.0, CoreFX 4.7.19.7311), 64bit RyuJIT
  DefaultJob : .NET Core 3.0.0-preview-27324-5 (CoreCLR 4.6.27322.0, CoreFX 4.7.19.7311), 64bit RyuJIT
```

```using System;
using System.Collections.Generic;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace ConsoleApp1
{
    class A
    {
        public double P { 
            [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get; 
        
            set; }
    }
    class B
    {
        public double P;
    }

    public class Benchmarks
    {
        static int LEN = 20000000;
        
        List<A> a = new List<A>(LEN);
        List<B> b = new List<B>(LEN);

        [GlobalSetup]
        public void Setup()
        {
            Random r = new Random(DateTime.Now.Millisecond);

            for (int i = 0; i < LEN; i++)
            {
                double p = r.NextDouble();
                a.Add(new A() { P = p });
                b.Add(new B() { P = p });
            }
        }

        [Benchmark]
        public double Property()
        {
            var d = 0d;
            for (int i = 0; i < LEN; i++)
            {
                d += a[i].P;
            }

            return d;
        }

        [Benchmark]
        public double Field()
        {
            var d = 0d;
            for (int i = 0; i < LEN; i++)
            {
                d += b[i].P;
            }

            return d;
        }
    }

    
    class Program
    {
         static void Main(string[] args)
         {
             BenchmarkRunner.Run<Benchmarks>();
         }
    }
}```

**Comment by stevenbrix** [comment]
Oh hey sorry! Can you remove the `AggressiveInlining` attribute and try again? that wasn't intended to be there

**Comment by stevenbrix** [comment]
I guess it doesn't seem like that actually does anything.

But to answer your question, yes i was pretty sure, otherwise i wouldn't have filed a bug. Can you explain why the repro i gave you shows a difference when running on .NET Core and not on .NET Fx? And why is it a bad repro since running this in Benchmark says they are the same?

**Comment by epeshk** [comment]
Ooh, looks like it is tiered compilation feature. See https://github.com/dotnet/coreclr/issues/21172

**Comment by kouvel** [comment]
Yes this is due to https://github.com/dotnet/coreclr/issues/19751. There are several workarounds, see the issue description for more info. For testing perf a small project with loops, the easiest solution for now may be to add `<DisableTier0Jit>true</DisableTier0Jit>` to the project file under a `PropertyGroup` element, or to disable tiered compilation. I'm currently investigating to see if something can be done by default so that a workaround would not be necessary.
