### ISSUE TITLE
Unable to cast int32 to int16

### ISSUE THREAD

**Issue by Symbai** [dotnet/coreclr#23191]
The following code raises an exception claiming it's unable to cast int32 into int16. But the value 81 (0x51) which can be casting into int16 without any problems.

Fails:
```
object value1 = null;
int val1 = (int) 0x51;
value1 = val1;
Test((short) value1); //exception

static void Test(short val){ }
```

Works:
```
int value1 = 0;
int val1 = (int) 0x51;
value1 = val1;
Test((short) value1);

static void Test(short val){ }
```

Works as well but seems completely unnecessary to me:
```
object value1 = null;
int val1 = (int)0x51;
value1 = val1;
int unnecessaryVariable = (int)value1;
Test((short)unnecessaryVariable);

static void Test(short val){ }
```

When the interpreter KNOWS the object variable holds a value of type int32, why does it fails when the 2nd example where the variable is int32 holding a value of type int32 does not fail. Creating a second variable where I explicit cast the object back into an integer works as well, but is kinda messy.

**Comment by stephentoub** [comment]
See https://blogs.msdn.microsoft.com/ericlippert/2009/03/19/representation-and-identity/ for a thorough explanation of why this is by design.  Here's the punchline:

>This would be a huge amount of code to generate, and it would be very slow. The code is of course so large that you would want to put it in its own method and just generate a call to it. Rather than do that by default, and always generate code that is slow, large and fragile, instead we’ve decided that unboxing can only unbox to the exact type. If you want to call the slow method that does all that goo, it’s available – you can always call Convert.ToInt32, which does all that analysis at runtime for you. We give you the choice between “fast and precise” or “slow and lax”, and the sensible default is the former. If you want the latter then call the method.

**Comment by Symbai** [comment]
Thanks for the link, pretty much explains it.
