### ISSUE TITLE
ToolsError build failures in 'official/dotnet/coreclr/refs/heads/release/3.0' - '20190308.710'

### ISSUE THREAD

**Issue by robertborr** [dotnet/coreclr#23192]
@dotnet-mc-bot commented on [Sat Mar 09 2019](https://github.com/dotnet/core-eng/issues/5443)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=119432
  - **Agent:** a0000JN
  - **Error log:** /root/.nuget/packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19128.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(0,0): error : Work item Interop.PInvoke in job 17f8755a-8595-4b7c-b0ff-a927c816f283 has Failed with exit code ...

@robertborr

---

@robertborr commented on [Mon Mar 11 2019](https://github.com/dotnet/core-eng/issues/5443#issuecomment-471614570)

Build FAILED.

/root/.nuget/packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19128.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Work item Interop.PInvoke in job 17f8755a-8595-4b7c-b0ff-a927c816f283 has Failed with exit code -3 [/__w/3/s/tests/helixpublishwitharcade.proj]
/root/.nuget/packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19128.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Job '17f8755a-8595-4b7c-b0ff-a927c816f283' has 1 failed work items. [/__w/3/s/tests/helixpublishwitharcade.proj]
/root/.nuget/packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19128.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Work item Interop.PInvoke in job c0f2531e-c6fd-49d2-ade6-50726750b028 has Failed with exit code -3 [/__w/3/s/tests/helixpublishwitharcade.proj]
/root/.nuget/packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19128.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Job 'c0f2531e-c6fd-49d2-ade6-50726750b028' has 1 failed work items. [/__w/3/s/tests/helixpublishwitharcade.proj]
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:17:55.10
Build failed (exit code '1').

---

@robertborr commented on [Mon Mar 11 2019](https://github.com/dotnet/core-eng/issues/5443#issuecomment-471615159)

notify @jashook 

---

@robertborr commented on [Mon Mar 11 2019](https://github.com/dotnet/core-eng/issues/5443#issuecomment-471742583)

test failures, class sourcecode, and move to coreclr

**Comment by RussKeldorph** [comment]
Not clear what this was.
