### ISSUE TITLE
OS X build on a case-sensitive fs

### ISSUE THREAD

**Issue by combinatorylogic** [dotnet/coreclr#232]
```
diff --git a/src/pal/src/CMakeLists.txt b/src/pal/src/CMakeLists.txt
index 52bbd61..924647c 100644
--- a/src/pal/src/CMakeLists.txt
+++ b/src/pal/src/CMakeLists.txt
@@ -13,7 +13,7 @@ if(CMAKE_SYSTEM_NAME STREQUAL Darwin)
   add_definitions(-D_TARGET_MAC64)
   set(PLATFORM_SOURCES
     arch/i386/context.S
-    arch/i386/dispatchexceptionwrapper.S
+    arch/i386/dispatchexceptionwrapper.s
     exception/machexception.cpp
     exception/machmessage.cpp
     locale/locale.cpp
```

**Comment by janvorli** [comment]
The correct fix is to rename the file instead. The extension has to stay upper case. The reason is that `make` treats that differently from the lower case .s. The files with upper case .S extension are passed through C preprocessor first, while the ones with lower case .s are not.

**Comment by combinatorylogic** [comment]
Oops. Sorry. It makes sense. The file must be renamed then.

**Comment by kangaroo** [comment]
PR here: https://github.com/dotnet/coreclr/pull/239

**Comment by kangaroo** [comment]
PR merged -- can someone close this out?
