### ISSUE TITLE
ToolsError build failures in 'official/dotnet/coreclr/refs/heads/release/3.0' - '20190312.73'

### ISSUE THREAD

**Issue by robertborr** [dotnet/coreclr#23214]
@dotnet-mc-bot commented on [Tue Mar 12 2019](https://github.com/dotnet/core-eng/issues/5476)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=122003
  - **Agent:** a0000JI
  - **Error log:** /root/.nuget/packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19128.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(0,0): error : Work item Interop.PInvoke in job b9b1947c-418b-42dd-9003-2f1aea486cff has Failed with exit code ...

@robertborr

---

@robertborr commented on [Tue Mar 12 2019](https://github.com/dotnet/core-eng/issues/5476#issuecomment-472187470)

Build FAILED.

/root/.nuget/packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19128.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Work item Interop.PInvoke in job b9b1947c-418b-42dd-9003-2f1aea486cff has Failed with exit code -3 [/__w/3/s/tests/helixpublishwitharcade.proj]
/root/.nuget/packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19128.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Job 'b9b1947c-418b-42dd-9003-2f1aea486cff' has 1 failed work items. [/__w/3/s/tests/helixpublishwitharcade.proj]
/root/.nuget/packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19128.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Work item Interop.PInvoke in job 85038072-1219-4870-8239-4b7c2132b9a5 has Failed with exit code -3 [/__w/3/s/tests/helixpublishwitharcade.proj]
/root/.nuget/packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19128.3/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Job '85038072-1219-4870-8239-4b7c2132b9a5' has 1 failed work items. [/__w/3/s/tests/helixpublishwitharcade.proj]
    0 Warning(s)
    4 Error(s)

---

@robertborr commented on [Tue Mar 12 2019](https://github.com/dotnet/core-eng/issues/5476#issuecomment-472188172)

closing sourcecode, moving to coreclr per previous test issues

**Comment by jkoritzinsky** [comment]
Looks like Helix just failed to download the payload. Closing this as it seems to have been a transient infra issue.
