### ISSUE TITLE
tracing\keyword\TwoKeywords often fails with timeout

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#23235]
This test often fails on x86 release with "Timed Out".

The test was added in #23094. 

[An example from x86 release scheduled job. ](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_release_windows_nt/6462/)
[
example from a PR triggered job](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_release_windows_nt_innerloop_prtest/13430/).

Looks like it happens only on x86 release.

**Comment by cshung** [comment]
https://github.com/dotnet/coreclr/issues/23224

**Comment by sandreenko** [comment]
Closed as a duplicate.
