### ISSUE TITLE
C:\J\w\perf_throughp---a214e272>exit 1 

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#23254]
failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_throughput_perflab_Windows_NT_x64_full_opt_ryujit_pgo/4084/

failed log:
C:\J\w\perf_throughp---a214e272>exit 0 
[perf_throughp---a214e272] $ cmd /c call C:\Users\ADMINI~1\AppData\Local\Temp\jenkins2075244839426956935.bat

C:\J\w\perf_throughp---a214e272>C:\Tools\nuget.exe install Microsoft.BenchView.ThroughputBenchmarks.x64.Windows_NT -Source https://dotnet.myget.org/F/dotnet-core -OutputDirectory "C:\J\w\perf_throughp---a214e272" -Prerelease -ExcludeVersion 
Feeds used:
  https://dotnet.myget.org/F/dotnet-core

  GET https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='Microsoft.BenchView.ThroughputBenchmarks.x64.Windows_NT'
  OK https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='Microsoft.BenchView.ThroughputBenchmarks.x64.Windows_NT' 30085ms
Unable to find package 'Microsoft.BenchView.ThroughputBenchmarks.x64.Windows_NT'

C:\J\w\perf_throughp---a214e272>exit 1 
Build step 'Execute Windows batch command' marked build as failure

**Comment by RussKeldorph** [comment]
Seems to have been temporary.
