### ISSUE TITLE
RyuJIT's early array length propagation misses trivial case

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#2325]
The following code
```C#
int[] a = new int[42];
int s = 0;
for (int i = 0; i < a.Length; i++)
    s += a[i];
return s;
```
generates
```
G_M9117_IG02:
       48B92A6FDC01F97F0000 mov      rcx, 0x7FF901DC6F2A
       BA2A000000           mov      edx, 42
       E8581A3F5F           call     CORINFO_HELP_NEWARR_1_VC
       33D2                 xor      edx, edx
       33C9                 xor      ecx, ecx
       83780800             cmp      dword ptr [rax+8], 0 ; this should have been eliminated
       7E10                 jle      SHORT G_M9117_IG04
G_M9117_IG03:
       4C63C1               movsxd   r8d, ecx
       4203548010           add      edx, dword ptr [rax+4*r8+16]
       FFC1                 inc      ecx
       83F92A               cmp      ecx, 42 ; length propagated correctly
       7CF1                 jl       SHORT G_M9117_IG03
```
This seems to happen because earlyprop runs only on blocks marked with `BBF_HAS_INDX` and the importer sets that flag when it encounters `ldelem` instructions but not when it encounters `ldlen` instructions.

On a side note, it seems strange that earlyprop wasn't implemented on top of VN. Maybe that would have avoided the need to restrict the analysis to certain blocks.

**Comment by cmckinsey** [comment]
Good catch. Should be an easy fix.

The VN framework already does this but because we ultimately want this phase ordering: loop-opts+global-opts(i.e.value-numbering + others) we need an early phase to do the rewrites. Value-numbering is too expensive to run multiple times.

**Comment by cmckinsey** [comment]
For some reason cannot assign to hoyMS, but @hoyMS take a look.

**Comment by hoyMS** [comment]
Thanks for the heads-up. Yes, we don't do array length propagation for blocks that only have ldlen instructions currently. Will fix it.

**Comment by mikedn** [comment]
> but because we ultimately want this phase ordering: loop-opts+global-opts(i.e.value-numbering + others) we need an early phase to do the rewrites

Is this something that will happen in the future? Right now earlyprop runs exactly before value numbering so I don't quite understand where loop optimizations fit in.

**Comment by hoyMS** [comment]
The loop optimizer will fit between earlyprop and value numbering. So the flow will be something like
1. SSA construction
2. Early prop
3. Loop optimization
4. Value numbering
5. CSE
6. Copy prop
7. Assert Prop
8. Range opt
