### ISSUE TITLE
Debugging managed assemblies with VS Code in custom host

### ISSUE THREAD

**Issue by thorwe90** [dotnet/coreclr#23284]
Hello everyone,

I cannot get debugging of managed assemblies running in a custom .NET Core runtime host to work. VSCode (vsdbg) always returns 0x80131c08 after a few seconds when trying to attach to the process.

I've basically followed this guide (https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting)and consulted this (https://github.com/dotnet/coreclr/tree/master/src/coreclr/hosts) to make it run on macOS.

So, what do I currently do?

I initialise the CoreCLR using

> coreclr_initialize(...)

 and then basically running a function using 

> coreclr_create_delegate(...)

while not shutting down the runtime and it works just fine. Tried it in a command line tool and Cocoa app, both run but no debugging.

Question is: is there some kind of flag I have to provide to coreclr_initialize or other stuff I have to do to get debugging working? 

For reference, this is the "basic" implementation of my "runtime" written in Swift: [ClrRuntimeHost.txt](https://github.com/dotnet/coreclr/files/2970826/ClrRuntimeHost.txt)

Thank you very much in advance.

**Comment by janvorli** [comment]
@mikem8361 do you have any idea why the debugger would timeout connecting to coreclr hosted in a custom host?

**Comment by tdecroyere** [comment]
Hello,

I'm currently doing the same thing as you. I'm writing a 3D engine in .net core 3.0 and for the MacOS version, I have a swift host. (using Cocoa and Metal)

Debugging with vscode works great in my case. Comparing to your code, for the properties list, I only use the "THRUSTED_PLATFORM_ASSEMBLIES" property. 

Maybe you can compare your code with mine if it can help. Because like that I don't know what is going wrong with your code.

Here is the swift function in my code that get the pointer to the C# functions:

    func initCoreClrSwift() {
    let appPath = Bundle.main.bundleURL.appendingPathComponent("Contents/CoreClr")
    let coreLibPath = appPath.appendingPathComponent("libcoreclr.dylib").path
    
    let handle = dlopen(coreLibPath, RTLD_NOW | RTLD_LOCAL)
    
    let coreClrInitializeHandle = dlsym(handle, "coreclr_initialize")
    let coreclr_initialize = unsafeBitCast(coreClrInitializeHandle, to: coreclr_initialize_ptr.self)
    
    let coreClrCreateDelegateHandle = dlsym(handle, "coreclr_create_delegate")
    let coreclr_create_delegate = unsafeBitCast(coreClrCreateDelegateHandle, to: coreclr_create_delegate_ptr.self)

    // TPA List
    let fileManager = FileManager.default
    var tpaList: [String] = []
    
    do {
        var assembliesList = try fileManager.contentsOfDirectory(at: appPath, includingPropertiesForKeys: nil, options: [])
        assembliesList = assembliesList.filter{ $0.pathExtension == "dll" }
        
        for assembly in assembliesList {
            tpaList.append(assembly.path)
            //print(assembly.path)
        }
        //print("TPA list:", tpaList.joined(separator: ":") )

    } catch {
        print("ERROR: Could not find CoreCLR path")
    }
    
    let propertyKeys = [ "TRUSTED_PLATFORM_ASSEMBLIES" ]
    let propertyValues = [ tpaList.joined(separator: ":") ]
    var hostHandle: UnsafeMutableRawPointer? = nil
    var domainId: UInt32 = 0
    var managedDelegate: UnsafeMutableRawPointer? = nil
    
    var cargs = propertyKeys.map { UnsafePointer(strdup($0)) }
    var cargs2 = propertyValues.map { UnsafePointer(strdup($0)) }
    
    defer {
        //cargs.forEach { free($0) }
    }
    var result = coreclr_initialize(appPath.path,
                                    "CoreEngineAppDomain",
                                    1,
                                    &cargs,
                                    &cargs2,
                                    &hostHandle,
                                    &domainId)

    if (result == 0) {
        result = coreclr_create_delegate(hostHandle!, 
                                        domainId,
                                        "CoreEngine",
                                        "CoreEngine.Bootloader",
                                        "StartEngine",
                                        &managedDelegate)

        if (result == 0) {
            startEnginePointer = unsafeBitCast(managedDelegate!, to: StartEnginePtr.self)
        }

        result = coreclr_create_delegate(hostHandle!, 
                                        domainId,
                                        "CoreEngine",
                                        "CoreEngine.Bootloader",
                                        "UpdateEngine",
                                        &managedDelegate)

        if (result == 0) {
            updateEnginePointer = unsafeBitCast(managedDelegate!, to: UpdateEnginePtr.self)
        }
    }
    
    // TODO: Do not forget to call the shutdownCoreClr method
    
    //dlclose(handle)
}

Also, here is my launch settings to debug in the managed DLL with VSCode. 

    {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "args": ["EcsTest"],
            "stopAtEntry": false,
            "externalConsole": false,
            "osx": {
                "cwd": "${workspaceFolder}/build/MacOS/CoreEngine.app/Contents/MacOS/",
                "program": "./CoreEngine"
            },
            "windows": {
                "cwd": "${workspaceFolder}/build/Windows/",
                "program": "./CoreEngine.exe"
            }
        }

**Comment by thorwe90** [comment]
Actually, launching the custom host instead of attaching (or some random change I made) somehow did the trick for me. Thank you very much.

**Comment by janvorli** [comment]
@tdecroyere thank you a lot for providing help!
