### ISSUE TITLE
Pending IPC work items

### ISSUE THREAD

**Issue by jorive** [dotnet/coreclr#23299]
## Pending IPC work items
- [x] Add tests
- [x] Add streaming functionality
- [x] Repurpose LF_REMOTING (currently used under the Diagnostics STRESS_LOG usage)
- [x] Replace the use of LOG under the Diagnostics Server with STRESS_LOG
- [x] Revisit the IPC mode of sending messages (byte vs message)
- [x] Handle shutdown on non-Windows platform (Need to unlink socket on the filesystem when the runtime exit with Ctrl-C/Ctrl-Break)

**Comment by josalem** [comment]
@jorive is this still tracking active work?  It looks like we've completed everything in this list.

**Comment by jorive** [comment]
@josalem Not fully done yet. Ctrl-C needs to be properly fixed (need to look at what the debugger does), and add tests for all the new features.

**Comment by sywhang** [comment]
PR is out for cleaning up the socket on Ctrl-C: https://github.com/dotnet/coreclr/pull/25976

**Comment by sywhang** [comment]
https://github.com/dotnet/coreclr/pull/25976 should check the last checkbox. Closing the issue as all checkboxes are marked as done.
