### ISSUE TITLE
Leaked reference when linking profiler against libcoreclr.so

### ISSUE THREAD

**Issue by k15tfu** [dotnet/coreclr#23304]
Hi again!

When linking ReJITEnterLeaveHooks profiler (https://github.com/Microsoft/clr-samples) against `libcoreclr.so` I faced with unexpected behavior: the runtime loaded that profiler, dlsym'd + called its `DllMain`, and then dlsym'd `PAL_RegisterModule` in the current `dl_handle` and found it in `libcoreclr.so` and then called it also.  So `DllMain` was called for CorProfiler.so (aka ReJITEnterLeaveHooks ) but  `PAL_RegisterModule` was called for its dependent library `libcoreclr.so`.

Here is the logs for CorProfiler.so linked against libcoreclr.so:
```
{0x870-0x7fbc132b4040} ENTRY [LOADER ] at /home/user/p/coreclr/2/src/pal/src/loader/module.cpp.229: LoadLibraryExW (lpLibFileName=000000000256CB48 (/home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so))
{0x870-0x7fbc132b4040} TRACE [LOADER ] at LOADLoadLibraryDirect.1410: dlopen() found module /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so handle 000000000258CF30
{0x870-0x7fbc132b4040} TRACE [LOADER ] at LOADAddModule.1523: Module doesn't exist : creating /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so.
{0x870-0x7fbc132b4040} TRACE [LOADER ] at LOADRegisterLibraryDirect.1578: Calling DllMain (00007FBC100FB0F0) for module /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so dl_handle 000000000258CF30
{0x870-0x7fbc132b4040} TRACE [LOADER ] at LOADRegisterLibraryDirect.1584: dlsym(PAL_RegisterModule) = 00007FBC13296010, module /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so
{0x870-0x7fbc132b4040} TRACE [LOADER ] at LOADRegisterLibraryDirect.1588: dladdr(dlsym(PAL_RegisterModule)) = 1, dli_fname /home/user/p/coreclr/2/bin/Product/Linux.x64.Debug/libcoreclr.so
{0x870-0x7fbc132b4040} TRACE [LOADER ] at LOADLoadLibraryDirect.1410: dlopen() found module /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so handle 000000000258CF30
{0x870-0x7fbc132b4040} TRACE [LOADER ] at LOADAddModule.1509: Found matching module 00000000025187F0 for module name /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so
{0x870-0x7fbc132b4040} TRACE [LOADER ] at operator().1194: Calling DllMain (00007FBC100FB0F0) for module /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so
```

the logs without linking against libcoreclr.so
```
{0x80c-0x7f880be23040} ENTRY [LOADER ] at /home/user/p/coreclr/2/src/pal/src/loader/module.cpp.229: LoadLibraryExW (lpLibFileName=0000000000D56B48 (/home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so))
{0x80c-0x7f880be23040} TRACE [LOADER ] at LOADLoadLibraryDirect.1410: dlopen() found module /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so handle 0000000000D76F30
{0x80c-0x7f880be23040} TRACE [LOADER ] at LOADAddModule.1523: Module doesn't exist : creating /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so.
{0x80c-0x7f880be23040} TRACE [LOADER ] at LOADRegisterLibraryDirect.1578: Calling DllMain (00007F88084690E0) for module /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so dl_handle 0000000000D76F30
{0x80c-0x7f880be23040} TRACE [LOADER ] at LOADRegisterLibraryDirect.1584: dlsym(PAL_RegisterModule) = 0000000000000000, module /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so
{0x80c-0x7f880be23040} TRACE [LOADER ] at LOADRegisterLibraryDirect.1588: dladdr(dlsym(PAL_RegisterModule)) = 0, dli_fname
{0x80c-0x7f880be23040} TRACE [LOADER ] at operator().1194: Calling DllMain (00007F88084690E0) for module /home/user/p/clr-samples/ProfilingAPI/ReJITEnterLeaveHooks/CorProfiler.so
```

As you can see, in the first case `dlsym(PAL_RegisterModule)` returned the address located in `/home/user/p/coreclr/2/bin/Product/Linux.x64.Debug/libcoreclr.so`, but NULL in the second case.

So, could anyone tell me whether it's okay to link against `libcoreclr.so`?

And finally, the reason why I'm asking is that:  `PAL_RegisterModule` increments refcount for CorProfiler.so, so after calling `LoadLibrary` the resulted module will have 2 references, but if I call `FreeLibrary` only one reference will be released because no matching `PAL_UnregisterModule` will be get called ([link](https://github.com/dotnet/coreclr/blob/73484d4664d75aafaaccbbd86f8204bd4f106ae8/src/pal/src/loader/module.cpp#L1099)).

**Comment by k15tfu** [comment]
btw, looks like the issue was introduced in https://github.com/dotnet/coreclr/pull/1125

**Comment by jkotas** [comment]
> So, could anyone tell me whether it's okay to link against libcoreclr.so?

It is not ok. We consider the set of APIs exported by `libcoreclr.so` to be internal implementation detail and changing it frequently.

**Comment by k15tfu** [comment]
@jkotas Wow, okay! Does it mean that coreclr users (profiler developers, etc) are not permitted to use WinAPI functions implemented in coreclr also?

If yes, is there an another .so library (in this project/organization) that implements WinAPI and is legal to use? (just interesting)

**Comment by jkotas** [comment]
Correct. We do not support the partial Win32 emulation APIs outside CoreCLR. 

If somebody (profiler, etc.) calls one of these APIs and reports an issue that it does not behave the same way as its Windows equivalent or that the API disappeared in newer CoreCLR version, we are unlikely to fix it. It is by design.

The ultimate Win32 emulator on Linux is Wine, but it is not a good fit for libraries. Number of projects out there have a PAL layer like CoreCLR. The PALs are typically implemented to do just enough to support the project, but nothing more. I have not seen a PAL layer with complete Win32 emulation. If your project has a need for PAL layer, I would recommend to introduce one that does just enough for what the project needs.

The alternative is to program against standard C/C++ libraries. It is better than what it used to be:  The modern C/C++ exposes many primitives (e.g. synchronization) that the PAL layers were historically used to abstract out.

**Comment by k15tfu** [comment]
@jkotas Okay, I got you. Thanks.
