### ISSUE TITLE
LNK4098: defaultlib 'libcmt.lib' conflicts with use of other libs

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#23324]
Apparently starting with https://github.com/dotnet/coreclr/pull/23106, we have this new build warning:

```
libcmtd.lib(initializers.obj) : warning LNK4098: defaultlib 'libcmt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library [D:\j\workspace\checked_windo---14fb495b\bin\obj\Windows_NT.x64.Checked\src\dlls\mscoree\coreclr\coreclr.vcxproj]
```

First merge job with failure (Windows x64 Checked build):
https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt/11655

@jorive PTAL

**Comment by jorive** [comment]
Taking a look.
