### ISSUE TITLE
[SOS] Source code line numbers are not available in ClrStack and PrintException commands

### ISSUE THREAD

**Issue by 6opuc** [dotnet/coreclr#23338]
### Problem description:
When I open core dump using lldb+sosplugin and use commands like PrintException or ClrStack then I get only method names without line numbers. 

### Steps to reproduce:
1. Run app with unhandled exception, for example: `docker run -it 6opuc/lldb-netcore-use-cases UnhandledException`. Exception stack trace with source code line numbers is printed in app output.
2. Open core dump of crashed application with lldb and sosplugin
3. Run command `sos PrintException`
## Expected result:
Exception stack trace with source code line numbers
## Actual result:
Exception stack trace **without** source code line numbers

### Remarks:
Tested in v2.2.3 and v2.1.9 branches of coreclr.
LLDB versions 3.9 and 4.0.
Also no source code line numbers in lldb and sos if I create full core dump of running application  using `createdump -u`.

**Comment by janvorli** [comment]
cc: @mikem8361

**Comment by mikem8361** [comment]
To get source/line numbers with the PrintException you need to add "-lines"

    pe -lines

"pe" and "printexception" are aliases to "sos PrintException".  See `soshelp` for more.

`clrstack` should print the source/line info for all the frames that have .pdbs without any options.  If you are still having problems can you upload the coredump file?

The new SOS in the[ diagnostics ](https://github.com/dotnet/diagnostics) repo has symbol downloading support for the runtime assemblies and modules.  See https://github.com/dotnet/diagnostics#installing-sos for details.

**Comment by 6opuc** [comment]
I have line numbers in my app output(exception stack trace):
```
docker run -it 6opuc/lldb-netcore-use-cases UnhandledException

Unhandled Exception: System.DivideByZeroException: Attempted to divide by zero.
   at Runner.UnhandledException.Calc(Input input) in /sources/src/Runner/UnhandledException.cs:line 23
   at Runner.UnhandledException.Run(String[] args) in /sources/src/Runner/UnhandledException.cs:line 17
   at Runner.Program.Main(String[] args) in /sources/src/Runner/Program.cs:line 27
```
So I expect that I'll have line numbers in `pe -lines` and `clrstack` when I'll open coredump, but I have the following:
```
(lldb) pe -lines
Exception object: 00007f4f5a8eeef8
Exception type:   System.DivideByZeroException
Message:          Attempted to divide by zero.
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    00007FFDFCE5C490 00007F4F73593AB8 Runner.dll!Unknown+0x38
    00007FFDFCE5C4C0 00007F4F735939F0 Runner.dll!Unknown+0x160
    00007FFDFCE5C530 00007F4F7359253E Runner.dll!Unknown+0x20e

StackTraceString: <none>
HResult: 80020012

(lldb) clrstack
OS Thread Id: 0x1 (1)
        Child SP               IP Call Site
00007FFDFCE5B240 00007f4fed29c529 [FaultingExceptionFrame: 00007ffdfce5b240]
00007FFDFCE5C490 00007F4F73593AB8 /app/Runner.dll!Unknown
00007FFDFCE5C4C0 00007F4F735939F0 /app/Runner.dll!Unknown
00007FFDFCE5C530 00007F4F7359253E /app/Runner.dll!Unknown
00007FFDFCE5C8A8 00007f4fec74b17f [GCFrame: 00007ffdfce5c8a8]
00007FFDFCE5CCB0 00007f4fec74b17f [GCFrame: 00007ffdfce5ccb0]
```

I expect to see the same line numbers in core dump as in the app output, but I have only:
```
/app/Runner.dll!Unknown
```
Core dump in attachment:
[core.1.gz](https://github.com/dotnet/coreclr/files/2986649/core.1.gz)


Also I tried to create full dump of running process using `createdump -u`.
In full core dump I have more details: I can see method names instead of 'Unknown', but still without line numbers. Full coredump file is too huge to attach here even for tiny app with managed heap < 1MB(I've already reported that here: https://github.com/dotnet/coreclr/issues/10524)

Thanks for the links, but currently I don't need runtime debugging symbols, I need detailed exception stack trace of my app's methods.

**Comment by 6opuc** [comment]
And in windows with windbg I have expected output:
```
0:000> !pe -lines
Exception object: 0000017216e04c90
Exception type:   System.DivideByZeroException
Message:          Attempted to divide by zero.
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    00000063A0D7D5D0 00007FFA0A9B3432 Runner!Runner.UnhandledException.Calc(Input)+0x32 [C:\projects\lldb-netcore-use-cases\src\Runner\UnhandledException.cs @ 23]
    00000063A0D7D610 00007FFA0A9B336C Runner!Runner.UnhandledException.Run(System.String[])+0x15c [C:\projects\lldb-netcore-use-cases\src\Runner\UnhandledException.cs @ 17]
    00000063A0D7D690 00007FFA0A9B1F32 Runner!Runner.Program.Main(System.String[])+0x202 [C:\projects\lldb-netcore-use-cases\src\Runner\Program.cs @ 27]
```

**Comment by mikem8361** [comment]
The “Unknown” is because the core dumps don’t have the assembly metadata not because there are no symbols.  This is issue https://github.com/dotnet/diagnostics/issues/56.  The fix is to provide SOS with the metadata from the assembly if it can find it locally or after downloading it from the symbol server for runtime assemblies.  The reason this works on Windows is because windbg/cdb does this for SOS where lldb doesn’t.

Currently there is a work around in the createdump in master/3.0 that adds all the metadata from the assemblies to the dump.  We don’t want this to be the permanent solution but it adds quite a bit to the dumps.

**Comment by 6opuc** [comment]
I've run my test app with environment variables "COMPlus_DbgEnableMiniDump=1" and "COMPlus_DbgMiniDumpType=4" and now core dump is created THREE times:
1. by Linux in app work directory(core.1)
2. by dotnet /tmp/coredump.1
3. by dotnet, overwriting file in the same path: /tmp/coredump.1
Here is app output:
```
Unhandled Exception: System.DivideByZeroException: Attempted to divide by zero.
   at Runner.UnhandledException.Calc(Input input) in /sources/src/Runner/UnhandledException.cs:line 23
   at Runner.UnhandledException.Run(String[] args) in /sources/src/Runner/UnhandledException.cs:line 17
   at Runner.Program.Main(String[] args) in /sources/src/Runner/Program.cs:line 27
Writing full dump to file /tmp/coredump.1
Written 2688286720 bytes (656320 pages) to core file
Writing full dump to file /tmp/coredump.1
Written 2688286720 bytes (656320 pages) to core file
```
Should I report another issue about second coredump in /tmp/coredump.1?

As for current issue:
After opening coredump with lldb and sos I still don't have source code line numbers:
```
(lldb) sos PrintException -lines
Exception object: 00007fe8cde8eef8
Exception type:   System.DivideByZeroException
Message:          Attempted to divide by zero.
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    00007FFD488D5520 00007FE8E6B53AB8 Runner.dll!Runner.UnhandledException.Calc(Input)+0x38
    00007FFD488D5550 00007FE8E6B539F0 Runner.dll!Runner.UnhandledException.Run(System.String[])+0x160
    00007FFD488D55C0 00007FE8E6B5253E Runner.dll!Runner.Program.Main(System.String[])+0x20e

StackTraceString: <none>
HResult: 80020012
```

So I think that there are two issues here:
1. dotnet/diagnostics#56
2. Source code line numbers are not available even in full dumps(using createdump -u or env. COMPlus_DbgMiniDumpType=4)

**Comment by mikem8361** [comment]
I'm vacation for 3 weeks so I won't be able to investigate this.  

This is probably something to do with running in a docker container and that the pid for processes starts as "1".  Not sure why two dumps are being generated by the runtime. 

Do you open the core dump in the docker container? Are the PDBs for your app accessible under the same path?

**Comment by 6opuc** [comment]
My bad, my PDBs were in different location.
After mounting PDBs in the same path as in crashed docker container everything is fine.

As for two dumps created by runtime, I'll report separate issue later.
