### ISSUE TITLE
Bad IL format exception

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#23330]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_r2r_tst/47/

**Failed tests:**
baseservices_threading._generics_threadstart_GThread20_GThread20_._generics_threadstart_GThread20_GThread20_cmd

**Log:**
```
baseservices_threading._generics_threadstart_GThread20_GThread20_._generics_threadstart_GThread20_GThread20_cmd [FAIL]
Exception: Unhandled Exception: Unhandled Exception: Unhandled Exception: System.BadImageFormatException: Bad IL format.
           at IGen`1.Target[U]()
           at System.Threading.ThreadStart.Invoke()
           at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/coreclr/issues/23278

**Comment by BruceForstall** [comment]
Also:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt_r2r/3322

**Comment by BruceForstall** [comment]
Looks like it started with https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt_r2r/3297/

which was from: https://github.com/dotnet/coreclr/pull/22830

@MichalStrehovsky Can you take a look?

cc @jkotas

**Comment by MichalStrehovsky** [comment]
@jashook was validating if that was indeed the cause in #23291. I think we should just merge that. Ready to run has some odd dependency on the cargo cult code I deleted. That one is tracked in #23317 and we'll likely be able to rollback the rollback once that's fixed.
