### ISSUE TITLE
Loading a .NET Core 2.0 assembly in Core 3.0 runtime.

### ISSUE THREAD

**Issue by chethanvasishta** [dotnet/coreclr#23337]
We're adding support to our C++ application, to be able to interop with .NET Core. Users will be able to call functions in assemblies (their own or third party) built against .NET Core (version 1, 2 or 3). 

To do this, we thought of hosting the latest core runtime, and load all assemblies in this runtime. However, the [version selection document](https://docs.microsoft.com/en-us/dotnet/core/versions/selection) indicates that core runtimes are not backward compatible across major versions, i.e. a core assembly built for 2.0 cannot be loaded in the 3.0 runtime. 

I wrote a simple example to test this behavior. I'm able to load a 2.0 assembly in a hosted 3.0 runtime and call functions in it successfully! So, here are my questions:

1. Is loading a 2.0 assembly in a 3.0 runtime a supported behavior?
2. If it is not supported, what kinds of errors/failures can be expected while loading assemblies built against a different version, apart from missing types and missing API exceptions?

**Comment by jkotas** [comment]
CoreCLR is tightly coupled with CoreFX. Using CoreFX 2.x with CoreCLR 3.0, or vice versa is not supported.

Yes, the most common failure mode are going to be missing type and missing method exceptions.
