### ISSUE TITLE
Support simple assembly names in startup hook

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/coreclr#23343]
`STARTUP_HOOK` runtime property allows injecting code before application main - see the [spec](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/host-startup-hook.md) for details.

Currently it's a delimited list of fully qualified file paths - paths to assemblies.
This means that the user (either env. variable or native host) must know the full path to the assembly. That is typically not a problem for assemblies which are not part of the app, which is the most common use case of startup hooks. But in some scenarios the startup hook is part of the app (or even a framework - ASP.NET is planning to have one). In this case it would be much easier to specify the assembly only by its name, not a full path.

The proposal is to change the handling of items in the `STARTUP_HOOK` to something like this:
``` C#
if (Path.IsPathFullyQualified(item))
{
    startupHookAssembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(item);
}
else
{
    startupHookAssembly = AssemblyLoadContext.Default.LoadFromAssemblyName(new AssemblyName(item));
}
```

The if branch is what the startup hook implementation uses currently. Note that `AssemblyLoadContext.LoadFromAssemblyPath` only accepts fully qualified paths, it will throw if the argument is not a fully qualified path.

The else branch is new and it would allow items to specify assembly name instead of full path. The assembly name would be resolved in the `Default` load context. It means the assembly would need to be part of the TPA most likely.

**Comment by vitek-karas** [comment]
@davidfowl  @sbomer @jeffschwMSFT @sdmaclea

**Comment by sdmaclea** [comment]
`if (Path.IsPathFullyQualified(item))` seems suspicious.  Why not `STARTUP_HOOK_ASSEMBLYNAME`?

**Comment by vitek-karas** [comment]
Why do you think `IsPathFullyQualified` is suspicious? That exactly what `LoadFromAssemblyPath` calls to validate its arguments. Which means that the proposed change does not limit any of the existing functionality.

It definitely possible to introduce another runtime property and environment variable, it just doesn't feel necessary.

**Comment by sbomer** [comment]
Discussion copied from https://github.com/dotnet/core-setup/issues/5556:

@jkotalik in https://github.com/dotnet/core-setup/issues/5556#issue-425120882
> I am trying to use a Startup Hook to specify a first chance exception handler for a scenario in ASP.NET Core. However, I don't necessarily know where the dll location, it could be part of the app (current directory), part of the shared framework (or a nuget package), or a different folder entirely. As we don't know the exact location, we can't use the feature to specify a startup hook.
> 
> If we could instead specify the assembly name, that would allow us to work around this issue. 
> 
> cc @vitek-karas @sdmaclea

@sdmaclea in https://github.com/dotnet/core-setup/issues/5556#issuecomment-476414795

> We would need a well defined algorithm for finding the assembly.  
> 
> Usually when we resolve by AssemblyName, we have the *.deps.json contained in the app path to help us identify the paths to search.  We may be able to use the same algorithm as the App, but it certainly doesn't  satisfy your arbitrary folder requirement `a different folder entirely`
> 
> Any particular reason there needs to be more than one of these?  Why can't a single startup hook always be deployed with asp.net?

@jkotalik in https://github.com/dotnet/core-setup/issues/5556#issuecomment-476419902
> > but it certainly doesn't satisfy your arbitrary folder requirement a different folder entirely
> 
> Let me be clear, the dll path will be in the `*.deps.json` file. My ask is to use that for loading the startup hook given an assembly name.
> 
> > Why can't a single startup hook always be deployed with asp.net?
> 
> If you are a native hoster that want's to run hostfxr in the same process and you want a startup hook, you will need to know where a) hostfxr is and b) the user dll that contains Main(). We want to add a startup hook to ASP.NET, which will live in a dll that is part of the shared framework. By requiring a full path, this suddenly puts a 3rd requirement on hosters to find the dll that contains the startup hook. It could either be in the same directory as your app, inside of the shared framework, etc. Finding the dll shouldn't be a responsibility of the shared hoster.

**Comment by jkotalik** [comment]
Thanks @sbomer didn't realize there was an issue already filed. I always get confused by what is in core-setup vs coreclr 😄
