### ISSUE TITLE
Wired length comperer GenTrees in RangeCheck optimization section

### ISSUE THREAD

**Issue by ArtBlnd** [dotnet/coreclr#23340]
I don't know why some array length check dump shows like this

```
N009 ( 14, 12) [000009] -A-X--------              \--*  JTRUE     void
N007 (  1,  1) [000007] ------------                 |  /--*  CNS_INT   int    4 $42
N008 ( 12, 10) [000008] JA-X---N----                 \--*  LE        int    $182
N005 (  3,  2) [000159] ------------                    |  /--*  LCL_VAR   int    V03 cse0          $180
N006 ( 10,  8) [000160] -A-X--------                    \--*  COMMA     int    $180
N002 (  3,  3) [000006] ---X--------                       |  /--*  ARR_LENGTH int    $180
N001 (  1,  1) [000005] ------------                       |  |  \--*  LCL_VAR   ref    V00 arg0         u:1 $80
N004 (  7,  6) [000158] -A-X----R---                       \--*  ASG       int    $VN.Void
N003 (  3,  2) [000157] D------N----                          \--*  LCL_VAR   int    V03 cse0 
```

It should be like I think.
```
     (  7,  7)              [000007] ------------              *  STMT      void  (IL 0x000...0x005)
N005 (  7,  7)              [000006] ---X--------              \--*  JTRUE     void  
N003 (  1,  1)              [000004] ------------                 |  /--*  CNS_INT   int    4 $42
N004 (  5,  5)              [000005] J--X---N----                 \--*  LE        int    $182
N002 (  3,  3) CSE #01 (def)[000003] ---X--------                    \--*  ARR_LENGTH int    $180
N001 (  1,  1)              [000002] ------------                       \--*  LCL_VAR   ref    V00 arg0         u:1 $80
```

seems RangeCheck optimization processes after CSE optimization.
is this something wrong with CSE?

code in C#
```
if (array.Length > 4)
{
    // some value modifications
}
```

Related to https://github.com/dotnet/coreclr/pull/22848

**Comment by AndyAyersMS** [comment]
This form is expected, after CSE runs -- CSE creates embedded assignments with commas. You should see other trees simplified to just use `cse0` instead of arr_length.

If what you are saying is that CSEs of array lengths mess up RangeCheck, that's certainly possible. If we put CSE temps into SSA (see [this comment](https://github.com/dotnet/coreclr/issues/21973#issuecomment-463012984) for a link to a prototype) then range check should be able to get back to the length.

**Comment by ArtBlnd** [comment]
Thanks, so should I wait for that prototype patch? or should I just simplify codes?
I don't think its modified on RangeCheck section. so any way  to check that `GT_LCL_VAR` is length?

**Comment by AndyAyersMS** [comment]
I'll put up a PR for the CSE var in SSA changes once master is no longer auto-merging into 3.0. Probably a couple of weeks? 

In the meantime you can build on the prototype for your own testing.
