### ISSUE TITLE
concurgc.il test fails on linux x64 debug

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#2336]
The test

- JIT/Methodical/Boxing/misc/_relconcurgc_il/_relconcurgc_il.sh

failed on linux. See

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_ubuntu_tst_prtest/527/.

The message was:

```
terminate called after throwing an instance of 'PAL_SEHException'
```

**Comment by wtgodbe** [comment]
This test now passes.
