### ISSUE TITLE
JIT doesn't compile with GCC

### ISSUE THREAD

**Issue by franksinankaya** [dotnet/coreclr#23386]
There is a desire to compile CoreCLR with GCC compiler.
There are two benefits to this approach.

1. Code coverage and bugs.
This allows us to find bugs that were not previously caught by clang and MSVC compilers. GCC also has a much more stricter compliance requirements than other compilers. This allows code to be future proof.

2. Porting to other platforms
There are several operating systems where GCC is supported natively but clang is not. This wll allows CoreCLR to reach out to more platforms and increase usage.

While # 2 is a long term goal, # 1 is very valuable.

Several GCC portability changes have been already merged into CoreCLR baseline. Code is %90 compilable. 

Remaining issues are: guid support (declspec(uuid)) and JIT compilation issues.

uuid has been discussed here. https://github.com/dotnet/coreclr/issues/22745 Implementation is to do.

This issue has been raised to support JIT.

Immediate Problem:
JIT compiler makes use of __declspec(property) attributes. GCC compiler doesn't support this construct.

Suggestion:
Recommendation is to remove property usage and do a direct function calls.  The change is very mechanical.

find src/jit -type f -exec sed -i -e 's/->genEmitter/->getEmitter()/g' {} \;
find src/jit -type f -exec sed -i -e 's/\.genEmitter/\.getEmitter()/g' {} \;
find src/jit -type f -exec sed -i -e 's/genEmitter->/getEmitter()->/g' {} \;

Impacts:
This will have rebase issues for ongoing reviews. While this has been raised as a big impact, fixing the issue is as simple as changing calling convention from genEmitter to getEmitter(). 

category:implementation
theme:jit-coding-style
skill-level:beginner
cost:medium

**Comment by franksinankaya** [comment]
@am11 @janvorli @jkotas 

cc @dotnet/jit-contrib

**Comment by mikedn** [comment]
cc @dotnet/jit-contrib

**Comment by sandreenko** [comment]
> GCC also has a much more stricter compliance requirements than other languages

What do you call  languages?

> This allows us to find bugs that were not previously caught by clang and MSVC compilers.

 I think the set of warnings is almost the same for these platforms, but we have many warnings disabled for Clang and VS, does GCC find them?

**Comment by franksinankaya** [comment]
It is a typo. I tried to mean other compilers here when talking about other languages.

We are also suppressing the same level of warnings for GCC. You can see them here:
https://github.com/dotnet/coreclr/blob/f61314dab43e29eaa5c4323a890bc408be014f83/configurecompiler.cmake#L459

On the other hand, GCC found a handful of integer conversion issues, undefined behavior due to assignment of uninitialized variables, narrrowing warnings that were fixed already or logged.

https://github.com/dotnet/coreclr/issues/22690

You can see some of the fixed issues here: 

https://github.com/dotnet/coreclr/pull/23321
https://github.com/dotnet/coreclr/pull/23162
https://github.com/dotnet/coreclr/pull/23307
https://github.com/dotnet/coreclr/pull/23179
https://github.com/dotnet/coreclr/pull/23180
https://github.com/dotnet/coreclr/pull/23093
https://github.com/dotnet/coreclr/pull/22872

**Comment by franksinankaya** [comment]
@BruceForstall @sandreenko 

Is there any concern here?

I posted the full patchset here: https://github.com/dotnet/coreclr/pull/23418 to give an idea of what it will take to get there. 

I'm suggesting to absorb small patches such as https://github.com/dotnet/coreclr/pull/23323

**Comment by CarolEidt** [comment]
AFAIK we don't have specific guidelines for getters and setters in the jit coding conventions. I would prefer *not* to have them all start with `Get` or `get`. Rather I think the name should indicate what's being returned, and boolean value should generally start with `Is` or `Has` and others should simply express what's being queried - e.g. for `bbTreeList` in #23323 I would prefer to see it as `BBTreeList()`, and where there's backing store I believe the convention is for it to start with an underscore, and make it private.
That said, my general coding convention leanings don't always align with the rest of the team, so I think this is something we should have a discussion about.
@dotnet/jit-contrib - thoughts?

**Comment by CarolEidt** [comment]
And perhaps it goes without saying, but whatever we agree upon should be added to the coding conventions document: https://github.com/dotnet/coreclr/blob/master/Documentation/coding-guidelines/clr-jit-coding-conventions.md

**Comment by franksinankaya** [comment]
Let's discuss #23323, I can adjust per your recommendation. Please post comments as what you'd like to see.

**Comment by mikedn** [comment]
>  I would prefer not to have them all start with Get or get

IMO `Get`/`get` should be the default. Of course, `bool` returning functions should use `Is`/`Has` but that's just common sense - I don't expect anyone to suggest that `GetIsLive` would be preferable.

Dropping the get prefix could be OK in some cases but I think I little care is in order. For example, in my GT_PHI/GT_LIST PR I have `GenTree* Use::Node()` but I'm considering making it `GenTree* Use::GetNode()` and keeping `Node` for `GenTree*& Use::Node()`. I'd very much like to not have to expose a reference to the `GenTree*` data member but some parts of the JIT need that and it would take a while to get rid of that, if ever.

And `BBTreeList()` would IMO be OK if it returns a STL-like container that allows it to work with range-for. Otherwise, it would be best to stick to the current `getBBTreeList`.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib ping
I'd like to see consensus on general naming conventions before we merge #23323, and so that we can allow @franksinankaya to proceed on other renamings.

**Comment by AndyAyersMS** [comment]
> IMO Get/get should be the default. 

Agree...

**Comment by tannergooding** [comment]
I also agree, prefixing with `Get`/`Set` is the convention I generally see in C/C++ code bases.

**Comment by franksinankaya** [comment]
Can I assume that everybody agrees to Get/Set?

**Comment by CarolEidt** [comment]
> Can I assume that everybody agrees to Get/Set?

Yes, I think that's the consensus.

**Comment by franksinankaya** [comment]
https://github.com/dotnet/coreclr/pull/27341

**Comment by sandreenko** [comment]
Thanks @franksinankaya for the consistent and accurate port!

**Comment by BruceForstall** [comment]
@franksinankaya So is the port complete now?

Do you have a plan to keep it building? We currently have no plan to add gcc compilation to the CI system, so I expect that someone will need to submit periodic fixes if gcc compilation is broken.

**Comment by franksinankaya** [comment]
Sure, let's start this conversation too. I'm adding @jkotas here.

Previous conversation was to support GCC in CoreCLR CI only if it passes certain quality gates (build and test). Both of these have been achieved.

I'm looking at @jkotas for the long term commitment statement here.

**Comment by franksinankaya** [comment]
Regarding whether the port is complete or not, JIT port is complete.
I have about 12 patches left. 1 of them is blocked until SELECTANY in LTTNG is refactored. There is work going on in this area.

11 of them need to be generalized.

https://github.com/franksinankaya/coreclr/commits/gcc_port_10222019

I'll get to them next.

**Comment by jkotas** [comment]
We are minimizing changes in the coreclr/corefx CI systems since they are going be to shutdown in a few months after dotnet/runtime repo merge.

Once the CI stabilizes after dotnet/runtime repo merge, we will need to look at adding coverage for the community configs in the dotnet/runtime: We have promised Samsung to add some coverage for their config. Building with gcc is in the same boat.

> the long term commitment 

We can plug the leg into the CI system, but you would be still responsible for maintaining it and making sure that it is reliable.

**Comment by franksinankaya** [comment]
No problems with maintaining.
