### ISSUE TITLE
EventPipe: Add telemetry for dropped events

### ISSUE THREAD

**Issue by sywhang** [dotnet/coreclr#23414]
Ran into this issue while helping @andy-ms with some GC traces he was collecting on Linux. With ETW, we can diagnose whether events are dropped in a trace because it keeps track when events are dropped due to insufficient buffer size, etc. EventPipe doesn't keep track when events are dropped, so it's hard to see whether a trace has dropped events when it doesn't have events that we expect it to have. 

One option to do this might be to add a field in the payload for the Rundown Event that reports how many events were dropped. Or it could be its own event that gets emitted at rundown.

**Comment by sywhang** [comment]
cc @jorive @noahfalk @vancem

**Comment by tommcdon** [comment]
@noahfalk any objections moving this to future?

**Comment by noahfalk** [comment]
If we had to I'd be OK cutting this, but I'm really hoping we don't have to go this deep just yet. Not knowing if you lost events is pretty rough.

**Comment by noahfalk** [comment]
This has been implemented in #24853 using sequence numbers and is exposed via the DroppedEvents property in EventPipeEventSource.

**Comment by noahfalk** [comment]
TraceEvent part is in https://github.com/microsoft/perfview/pull/948
