### ISSUE TITLE
JIT SSE ConvertToInt64 intrinsic has unexpected result

### ISSUE THREAD

**Issue by gdkchan** [dotnet/coreclr#23438]
The ConvertToInt64 intrinsic is using the xmm -> r32 encoding, rather than xmm -> r64. The codegen for the sample program provided below (plus some debug code that affects the registers used but that doesn't matter) looks more or less like this:
```
vcvtss2si ecx, xmm6
```
Rather than:
```
vcvtss2si rcx, xmm6
```
Which means it can't convert values that don't fit on a 32-bits integer, even though it returns a 64-bits integer.

Here's a sample program that demonstrates the issue:
```cs
using System;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

namespace SseTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Vector128<float> val = Vector128.Create(BitConverter.Int32BitsToSingle(0x4f800000));

            long result = Sse.X64.ConvertToInt64(val);

            Console.WriteLine(result);
        }
    }
}
```
Expected result: 4294967296
Actual result: 2147483648

I believe that it has the same codegen as the `ConvertToInt32` intrinsic method, but returning a long instead, so it seems to be a JIT bug.

fyi @LDj3SNuD since he is the one that is trying to use the intrinsic and found the problem.

cc @fiigii

**Comment by tannergooding** [comment]
Also CC. @CarolEidt

I'll take a look at this.

**Comment by fiigii** [comment]
@tannergooding Thanks!

**Comment by tannergooding** [comment]
Fix is here: https://github.com/dotnet/coreclr/pull/23461
