### ISSUE TITLE
Fatal Race Condition in Lazy<T>

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/coreclr#23432]
Hi All,
We're running into what seems to be a race condition of some sort with Lazy<T>.

My understanding is that System.Threading.LazyThreadSafetyMode.None should allow the Lazy<T> to be called from multiple threads concurrently with the side effect that it is possible that the lazily initialized value could be created twice.

We are seeing that in some situations, we're getting errors instead.

The code below demonstrates the issue.

````
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace LazyTests {
    class Program {
        static async Task Main(string[] args) {


            var ToTest = new List<Foo>();

            for (int i = 0; i < 1000; i++) {
                ToTest.Add(new Foo());
            }

            var Token = new System.Threading.CancellationTokenSource();
            

            var Tasks = new[] {
                Task.Run(() => DoTest(ToTest, Token)),
                Task.Run(() => DoTest(ToTest, Token)),
                Task.Run(() => DoTest(ToTest, Token)),
            };
            Token.Cancel();


            await Task.WhenAll(Tasks);

        }

        private static async Task DoTest(List<Foo> ToTest, CancellationTokenSource Token) {
            try {
                await Task.Delay(Timeout.InfiniteTimeSpan, Token.Token)
                    .ConfigureAwait(false)
                    ;
            } catch (Exception ex) {
                
            }

            foreach (var item in ToTest) {
                var V = item.Test.Value;
            }

        }

    }

    public class Foo {
        public Lazy<String> Test = new Lazy<string>(() => {
            System.Threading.Thread.Sleep(10);

            return "DONE!";
        }, System.Threading.LazyThreadSafetyMode.None);

    }

}
````

**Comment by EgorBo** [comment]
I guess it's by design:

> The Lazy<T> instance is not thread safe; if the instance is accessed from multiple threads, its behavior is undefined. Use this mode only when high performance is crucial and the Lazy<T> instance is guaranteed never to be initialized from more than one thread.

so `LazyThreadSafetyMode.None` can be used only when you 100% sure your Lazy objects won't be called from different threads.

**Comment by stephentoub** [comment]
> My understanding is that System.Threading.LazyThreadSafetyMode.None should allow the Lazy to be called from multiple threads concurrently with the side effect that it is possible that the lazily initialized value could be created twice.

That is definitely not the case.  `None` means there is no thread safety at all.  If you opt-in to that and multiple threads access the `Lazy<T>` concurrently, any aspect of it could be corrupted.

> I guess it's by design

Correct.

**Comment by TonyValenti** [comment]
What is the correct mode for me to use to achieve what I'm looking for then?

Tony Valenti

Schedule a meeting with me
<https://www.fasterlaw.com/book-online/tony-valenti>

**Comment by stephentoub** [comment]
If you're going to be accessing the `Lazy<T>` concurrently, then either the default, which maps to ExecutionAndPublication, or PublicationOnly, which per above "means that if multiple threads race to initialize the `Lazy<T>`, multiple `T`s may end up getting created, but only one will actually be published for all to consume from `Value`."
