### ISSUE TITLE
CoreRun.exe exited with 134 code

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#23452]
failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_Ubuntu16.04_x64/1737/

failed log:
[./tests/scripts/run-xunit-perf.py]: taskset 0x00000002 nice --adjustment=-10 /home/administrator/jenkins/w/dotnet_coreclr/perf/master/perf_Ubuntu16.04_x64/bin/sandbox/corerun PerfHarness.dll /home/administrator/jenkins/w/dotnet_coreclr/perf/master/perf_Ubuntu16.04_x64/bin/sandbox/SciMark.exe --perf:outputdir /home/administrator/jenkins/w/dotnet_coreclr/perf/master/perf_Ubuntu16.04_x64/bin/sandbox_logs/Microbenchmarks/Off/SciMark --perf:runid Perf-Off --perf:collect stopwatch
[./tests/scripts/run-xunit-perf.py]: CoreRun.exe exited with 134 code
*** Error in `/home/administrator/jenkins/w/dotnet_coreclr/perf/master/perf_Ubuntu16.04_x64/bin/sandbox/corerun': free(): invalid pointer: 0x00007f815be26020 ***

**Comment by RussKeldorph** [comment]
Job is being replaced.
