### ISSUE TITLE
error MSB4024

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#23453]
failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_full_opt_ryujit_smoketest/2519/

failed log: 
D:\j\w\perf_perflab_---83658a1e\Tools\BuildVersion.targets(10,3): error MSB4024: The imported project file "D:\j\w\perf_perflab_---83658a1e\bin\obj\BuildVersion-20190326.props" could not be loaded. The process cannot access the file 'D:\j\w\perf_perflab_---83658a1e\bin\obj\BuildVersion-20190326.props' because it is being used by another process. [D:\j\w\perf_perflab_---83658a1e\tests\src\Loader\versioning\coverage\AssemblyAttrs.csproj]
D:\j\w\perf_perflab_---83658a1e\tests\dir.traversal.targets(25,5): error : (No message specified) [D:\j\w\perf_perflab_---83658a1e\tests\src\dirs.proj]
D:\j\w\perf_perflab_---83658a1e\tests\dir.traversal.targets(25,5): error : (No message specified) [D:\j\w\perf_perflab_---83658a1e\tests\build.proj]

**Comment by RussKeldorph** [comment]
Seems to be intermittent failure.  Please log additional instances here if you see them.
