### ISSUE TITLE
What exactly is safe to be used after `fork()` call on *nix?

### ISSUE THREAD

**Issue by kekekeks** [dotnet/coreclr#23482]
Unfortunately `Process.Start` API is quite limited: we can't pass the new process a custom fd as stdin/stdout, can't call `setsid` or do `ioctl`  before calling `execvpe`, etc. That's needed to properly set up a custom pseudo-TTY for the new process which is needed for interacting with applications that do care about having an actual TTY (e. g. `sudo` or `openvpn` use `open("/dev/tty")` to ask for credentials). This is also needed if we are trying to create a terminal emulator.

So we have to use `fork()` manually from our code. The problem is that `fork()` only preserves the calling thread, other threads just aren't present in the new process. That seems to be potentially disastrous for C# code. 

So the question: is it safe to call `fork()` if I make sure that it's called in `TryStartNoGCRegion` section and code after `fork()` call does only P/Invoke calls via prepared delegates (dlopen+dlsym+Marshal.GetDelegateForFunctionPtr) without managed heap allocations?

This code seems to be working, but I'm not sure if it would *always* work.
```cs
public unsafe class Program
{
	[DllImport("libdl.so.2", EntryPoint = "dlopen")]
	private static extern IntPtr dlopen_lin(string path, int flags);

	[DllImport("libdl.so.2", EntryPoint = "dlsym")]
	private static extern IntPtr dlsym_lin(IntPtr handle, string symbol);

	[DllImport("libSystem.dylib", EntryPoint = "dlopen")]
	private static extern IntPtr dlopen_mac(string path, int flags);

	[DllImport("libSystem.dylib", EntryPoint = "dlsym")]
	private static extern IntPtr dlsym_mac(IntPtr handle, string symbol);

	static T GetProc<T>()
	{
		if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
		{
			var dl = dlopen_mac("libSystem.dylib", 2);
			var a = dlsym_mac(dl, typeof(T).Name);
			return Marshal.GetDelegateForFunctionPointer<T>(a);
		}
		else
		{
			var dl = dlopen_lin("libc.6.so", 2);
			var a = dlsym_lin(dl, typeof(T).Name);
			return Marshal.GetDelegateForFunctionPointer<T>(a);
		}
	}

	delegate void dup2(int oldfd, int newfd);
	delegate int fork();
	delegate void setsid();

	delegate void ioctl(int fd, int ctl, int arg);
	delegate void close(int fd);
	delegate int open([MarshalAs(UnmanagedType.LPStr)] string file, int flags);
	delegate IntPtr ptsname(int fd);
	delegate void grantpt(int fd);
	delegate void unlockpt(int fd);
	delegate void execvp(IntPtr path, IntPtr* argv);

	delegate void _exit(int code);

	delegate int getdtablesize();

	class Argv : IDisposable
	{
		public IntPtr* List { get; }
		private List<IntPtr> _list;

		public Argv(IEnumerable<string> args)
		{
			_list = args.Select(x => Marshal.StringToHGlobalAnsi(x)).ToList();
			List = (IntPtr*)Marshal.AllocHGlobal(IntPtr.Size * _list.Count + 1);
			for (var c = 0; c < _list.Count; c++)
				List[c] = _list[c];
			List[_list.Count] = IntPtr.Zero;

		}
		public void Dispose()
		{
			Marshal.FreeHGlobal((IntPtr)List);
			foreach (var s in _list)
				Marshal.FreeHGlobal(s);
		}
	}

	static (int pid, int fd) ForkTty(string proc, string[] args)
	{
		// Prepare P/Invoke functions ahead of time
		var open = GetProc<open>();
		var ptsname = GetProc<ptsname>();
		var grantpt = GetProc<grantpt>();
		var unlockpt = GetProc<unlockpt>();
		var fork = GetProc<fork>();
		var close = GetProc<close>();
		var dup2 = GetProc<dup2>();
		var getdtablesize = GetProc<getdtablesize>();
		var setsid = GetProc<setsid>();
		var ioctl = GetProc<ioctl>();
		var execvp = GetProc<execvp>();
		var exit = GetProc<_exit>();
		
		var fdm = open("/dev/ptmx", 0x0402);
		grantpt(fdm);
		unlockpt(fdm);
		var namep = ptsname(fdm);
		var name = Marshal.PtrToStringAnsi(namep);
		var fds = open(name, 2);

		int pid = 0;
		
		// Prepare UTF8 versions of strings ahead of time in form of usable IntPtrs
		var argv = new Argv(new[] {proc}.Concat(args ?? new string[0]));
		var procu = Marshal.StringToHGlobalAnsi(proc);
		
		
		if (fdm != -1 || fds != -1)
		{
			if (!GC.TryStartNoGCRegion(4096))
			{
				close(fdm);
				close(fds);
				throw new OutOfMemoryException("Not enough memory to enter No-GC region");
			}
			pid = fork();
			if (pid == 0)
			{
				// NO heap allocations or custom marshalling are allowed in this region
				setsid();
				ioctl(fds, 0x540E, 0);
				dup2(fds, 0);
				dup2(fds, 1);
				dup2(fds, 2);
				for (int i = getdtablesize(); i >= 3; --i)
					close(i);
				execvp(procu, argv.List);
				exit(1);
			}
			GC.EndNoGCRegion();
		}
		argv.Dispose();
		Marshal.FreeHGlobal(procu);
		if (pid == 0)
			throw new Win32Exception("Unable to create a PTY");
		close(fds);
		return (pid, fdm);
	}

	public static void Main()
	{
		var (pid, fd) = ForkTty("bash", new[] {"-c", "echo Hello world!"});
		
		var s = new FileStream(new SafeFileHandle(new IntPtr(fd), true), FileAccess.Read);
		var buf = new byte[1];
		while (true)
		{
			try
			{
				if (s.Read(buf, 0, 1) == 0)
					return;
			}
			catch (IOException)
			{
				return;
			}
			
			Console.Write((char) buf[0]);
		}
	}
}

**Comment by danmosemsft** [comment]
@tmds

**Comment by tmds** [comment]
This is a very interesting question.

> if I make sure that it's called in TryStartNoGCRegion section

Why should you stop the GC?

> execvp(procu, argv.List);

I'd stick to one of the execs from the signal safety list: http://man7.org/linux/man-pages/man7/signal-safety.7.html. Those shouldn't mess with global state (including the allocator).

> return Marshal.GetDelegateForFunctionPointer<T>(a);

I don't know what guarantees the runtime gives you for this delegate. We don't want to trigger any allocations/JIT when invoking it.

CC @jkotas

**Comment by kekekeks** [comment]
>Why should you stop the GC?

I might be misunderstanding how GC safepoints work, but there might be a safepoint right after the `fork()` call and GC might have marked the thread to be stopped at the nearest safepoint when we have startedP/Invoking the `fork`, but before the actual syscall is made. So we fork, the child process reaches the safepoint and stops the thread, but there is no GC to resume it.

>I don't know what guarantees the runtime gives you for this delegate

Should I use `calli` opcode instead?

**Comment by jkotas** [comment]
It is not safe to return to managed code in forked processes in .NET Core today. It will result into intermittent hangs and crashes.

**Comment by kekekeks** [comment]
Additional info: `MAP_JIT` `mmap` flag (required to support hardened runtime on OSX) doesn't allow the pages to be inherited by the forked process. So I guess even if the runtime had support for it, the control can't be returned to the JITed code anyway.
