### ISSUE TITLE
Where is the clr code which handling try-catch-finally?

### ISSUE THREAD

**Issue by yukozh** [dotnet/coreclr#23484]
![image](https://user-images.githubusercontent.com/2216750/55076115-903ed500-50cf-11e9-8bc5-e63069e03b86.png)

In this case, the exception 3 will be thrown. However I have seen the exception 2 is also thrown in events.

![image](https://user-images.githubusercontent.com/2216750/55076141-a9478600-50cf-11e9-9ef9-fcc6d3262a96.png)

I want to know why it will throw the latest exception(exception 3) only in this situation? I would be appreciate if someone could explain me this. Why not throw an AggregatedException includes both exception 2 & 3 or support enumerate exceptions in catch scope?

**Comment by Suchiman** [comment]
As far as i know, the runtime only supports throwing one exception at a time (per thread). `finally` is guaranteed to execute unless the process goes down due to critical failure. The `finally` clause will override the currently pending exception that got thrown by the `catch` clause (it would also override `exception 1` if you would have no `catch` handler). Throwing Aggregate exceptions is something that is done by (C#) Framework Code during `async` (the runtime itself doesn't know about `async`) or other occurences

**Comment by yukozh** [comment]
So where is the override logic in code? I would be appreciate if you can point it to me?  https://github.com/dotnet/coreclr/blob/master/src/vm/exceptionhandling.cpp

**Comment by svick** [comment]
Why do you want to see the code?

Generally, if you want to understand how something like this behaves in detail, it's enough to look at [the specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#the-try-statement):

> If an exception is thrown during execution of a `finally` block, and is not caught within the same finally block, the exception is propagated to the next enclosing `try` statement. If another exception was in the process of being propagated, that exception is lost.

**Comment by poizan42** [comment]
@yukozh AFAICT exceptions are ultimately thrown by RaiseException, here: https://github.com/dotnet/coreclr/blob/9f285b762839d916683f08b06d450fd9969004fe/src/vm/excep.cpp#L2974, so the code you want to look at is the Windows source code for Windows or the [RaiseException implementation in PAL](https://github.com/dotnet/coreclr/blob/9f285b762839d916683f08b06d450fd9969004fe/src/pal/src/exception/seh-unwind.cpp#L468).

**Comment by mattwarren** [comment]
The question intrigued me! 

I don't have a full answer, but I wrote up some notes/info/thoughts in [this gist](https://gist.github.com/mattwarren/1cc41a93924f2fb2400843e11dc73095) (maybe I'll turn it into a blog post in the new few weeks). It shows the debug logs from the CLR itself, when executing your code sample, so it gives a good idea of the flow (you can then easily search the source code for the log statements)

If you want more info on 'how exceptions work', I put together a list in a [previous post](https://mattwarren.org/2019/01/21/Stackwalking-in-the-.NET-Runtime/#exception-handling).
