### ISSUE TITLE
 Assertion failed '!foundDiff' in 'Node[__Canon][System.__Canon]:Search(ref,ref):ref:this' in lsra.cpp line 2330

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#2349]
Configuration:
 Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreFX tests: release

The following test fails:
System.Collections.Immutable.Tests

Coregen repro steps:
crossgen /App_Paths . /Platform_Assemblies_Paths . /MissingDependenciesOK ./Microsoft.CodeAnalysis.CSharp.dll

Also happens for System.Collection.Immutable.dll.

Stress modes or other flags make no difference for this assert. Running with JITMinOpts set runs clean with no assert.

Before closing this issue please verify both the repro steps.

**Comment by LLITCHEV** [comment]
After investigating with @sivarv this looks like a new state introduced by the recursive tail call feature that lsra is not currently dealing with.

**Comment by LLITCHEV** [comment]
This happens on Windows as well.

**Comment by LLITCHEV** [comment]
Assigned to @sivarv since it is most likely a LSRA issue.

**Comment by LLITCHEV** [comment]
This issue seems to stil repro for Issue #2510. Reopening it.

**Comment by LLITCHEV** [comment]
Still happens with the latest sources (as of 2/13/2016). Happens for System.Collections.Immutable.dll.

**Comment by LLITCHEV** [comment]
Seems to pass. The failure I was observing was because the loader was picking up a crossgen from an old DNX installation instead the one from the current folder.
