### ISSUE TITLE
[arm64] JIT_superpmi._superpmicollect_superpmicollect_._superpmicollect_superpmicollect_cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#23508]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_jitstress1_tiered_tst/32/

**Failed tests:**
JIT_superpmi._superpmicollect_superpmicollect_._superpmicollect_superpmicollect_cmd

**Log:**
```
JIT_superpmi._superpmicollect_superpmicollect_._superpmicollect_superpmicollect_cmd [FAIL]
EXEC : error : unknown exception running collection: Operation did not complete successfully because the file contains a virus or potentially unwanted software. [C:\j\workspace\arm64_cross_c---982b2c6a\tests\runtest.proj]
Return code:      1
```

**Comment by RussKeldorph** [comment]
Virus scanner.  Definitions will likely be updated by the time this runs again.
