### ISSUE TITLE
[RuyJIT/ARM] Generated code quaility

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#23520]
As I remember there was no any activities to check whether RuyJIT generates well optimized code. So how we can do it and what is the references to check with?
The easiest way I see is look to generated code and search not efficient places. For test programs could be used:

1. Benchmarks/micro-benchmarks, but they are quite far from real user scenarios 
1. Real applications (we can analyze only hot methods, to reduce amount of work).

@jkotas could you recommend some other ways and metrics? I'm looking approaches:

1. How to search problem places
1. How to find ways to fix them
1. How to estimate gain (it's nice to make optimizations but they should be valuable for real scenarios=\ )

**Comment by jkotas** [comment]
> How to search problem places

We typically compare the benchmarks on two different platforms and investigate outliers. For example, you may find that most benchmarks are 5x slower on ARM than they are on x64 in your runs. The benchmarks that are much slower than 5x on ARM are worth looking into.

https://github.com/dotnet/performance is the repository where we are concentrating the benchmarks for runtime testing.

cc @dotnet/jit-contrib  @adamsitnik

**Comment by adamsitnik** [comment]
As pointed by @jkotas you can use https://github.com/dotnet/performance to run all the benchmarks we have.

[This](https://github.com/dotnet/performance/blob/master/scripts/benchmarks_ci.py) python 3 script can download the latest dotnet cli for you and run the benchmarks for specified architecture.

On ARM machine you need to run:

```cmd
git clone https://github.com/dotnet/performance
py .\performance\scripts\benchmarks_ci.py -f netcoreapp3.0 --architecture arm64 --filter *
```

On x64 machine:

```cmd
git clone https://github.com/dotnet/performance
py .\performance\scripts\benchmarks_ci.py -f netcoreapp3.0 --architecture x64 --filter *
```

Then copy all the exported result files to one machine and use [ResultsComparer](https://github.com/dotnet/performance/tree/master/src/tools/ResultsComparer) to find the diff. The results are sorted descending by base/diff ratio:

```cmd
dotnet run --base "C:\results\arm64" --diff "C:\results\x64" --threshold 5% --top 10
```

I know that @AndyAyersMS have already tested this workflow to compare ARM64 vs x64

**Comment by alpencolt** [comment]
Finally I've run benchmarks on ARM and x64: https://gist.github.com/alpencolt/0580af0be86e49bb9d89508dabcd8615
We'll check it more detailed, but it looks there are some issues withs string manipulations.

**Comment by BruceForstall** [comment]
@alpencolt This is a great start; thanks for doing this. Keep us up to date with what you find. It looks like you have many possibilities for investigation. I haven't used them in a while, but maybe valgrind/callgrind can help with individual test investigations.

**Comment by CarolEidt** [comment]
> it looks there are some issues withs string manipulations.

Some of the string manipulation methods are using vector intrinsics on x64. We don't have any support on Arm32 for vector intrinsics (though there are some preliminary intrinsics supported for arm64, I don't think they are yet being used in the frameworks).

**Comment by BruceForstall** [comment]
There's certainly an open question here about how we should prioritize adding SIMD and hardware intrinsics support to arm32.

**Comment by tannergooding** [comment]
For hardware intrinsics, I've been working on ensuring the ARM64 surface design can be reused for ARM32 where possible (see https://github.com/dotnet/corefx/issues/37199).

**Comment by BruceForstall** [comment]
As this was initially a question, that appears to be answered, I'm closing this.

If there are individual performance (code quality) bugs, please open individual items. Or open a new general issue for overall issues/questions.
