### ISSUE TITLE
Jenkins CI missing Linux R2R test coverage

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#23525]
For Linux R2R stress jobs, we pass various `--jitstress`, `--jitstressregs`, and other options to the runtest.sh script, based on the optimization mode of the job. These cause runtest.sh to directly set the corresponding `COMPlus` variable, which is then in effect when runtest.py is called.

However, we don't set `COMPlus_TieredCompilation=0` or `COMPlus_TieredCompilation=1`, as required by the netci.groovy `r2rStressScenarios` settings. So, now, since tiering is enabled by default, we are never disabling it as we should be for these jobs.

The obvious change is to create a `--test-env` script, as for other JIT stress modes. However, we also need to make sure these settings are used for precompiling the framework assemblies as well, in the runtest.py function `precompile_core_root`.

**Comment by BruceForstall** [comment]
@RussKeldorph @jashook @echesakovMSFT

**Comment by RussKeldorph** [comment]
This should be fixed in DevOps and the Jenkins jobs deleted.

**Comment by echesakovMSFT** [comment]
> This should be fixed in DevOps and the Jenkins jobs deleted.

To be able to run R2R jobs in AzDO on Linux/OSX we would need to implement some mechanism for running CrossGen on the framework assemblies. As far as I know, this is the only reason why R2R Linux/OSX jobs are disabled right now https://github.com/dotnet/coreclr/blob/4a4ba4d379002c8b8e77ef968f510cf0283201d0/eng/test-job.yml#L71-L75

As the comment above says it could be done in build-test.sh. However, I personally don't like the idea of having this logic duplicated (tripled) in the different places - build-test.cmd, build-test.sh and runtest.py. 

As an alternative, the crossgen logic could be re-implemented in MSBuild. It shouldn't be no harder than a having a separate target that discovers all assemblies that are needed to be crossgen-d, and running Exec task with appropriate arguments on them. Next step is just to call the MSBuild target from build-test.cmd and build-test.sh.

**Comment by BruceForstall** [comment]
> As an alternative, the crossgen logic could be re-implemented in MSBuild

You're making me cry...

**Comment by jashook** [comment]
To me this sounds very similar to our crossgen of SPC. Having crossgen logic split between build.cmd/build-test.cmd and build.sh/build-test.sh is already bad enough. Adding a fifth place seems like the wrong direction to take. 

It is still unclear to me what the R2R jobs look like long term. I am not very happy with how they are implemented in the old official build model.

**Comment by RussKeldorph** [comment]
The R2R stuff mentioned by @echesakovMSFT was fixed by @sergiy-k in #23781, #23801, etc.

I think the other stuff is Jenkins-specific, but please re-open (and fix the title) if I'm wrong.
