### ISSUE TITLE
[JITMinOpts=1]  Assertion Failure 'nextStmtExpr->gtOper == GT_RETURN' in RetBufferBug:Tailaller() in morph.cpp line 6671

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#2353]
Configuration:
 Debug Coreclr and Mscorlib.dll
 Release CoreFx assemblies 
 Release CoreCLR tests
 OS: Linux

Test case:
JIT/Methodical/tailcall_v4/smallFrame/smallFrame.exe

Without COMPlus_JITMinOpts=1
 Pass

With COMPlus_JITMinOpts=1
Fails with the above mentioned assert failure.

**Comment by hoyMS** [comment]
Fix checked in as 2628.
