### ISSUE TITLE
Question about forwarded type loading.

### ISSUE THREAD

**Issue by clamp03** [dotnet/coreclr#23543]
I am investigating coreclr to reduce launching time in Tizen.
I found that forwarded types are loaded in below codes of DoFullyLoad (src/vm/methodtable.cpp)
```
            else if (pMD->IsZapped() && pMD->HasForwardedValuetypeParameter())
            {     
                pMD->WalkValueTypeParameters(this, LoadTypeDefOrRefAssembly, NULL);
                locals.fDependsOnEquivalentOrForwardedStructs = TRUE; 
            } 
```
It takes time over 5% during xamarin application launching.
In comments for the codes, it explains that "Fully load exact parameter types for value type parameters opted into equivalence.".
As I understand, it loads the exact parameter type for equivalent type before entering prestub because of GC in prestub.
However, it checks "type forwarded parameter" not "type equivalence type" in the codes. (In my environment, FEATURE_TYPEEQUIVALENCE is disabled.)

I think forwarded parameters are guaranteed to have loaded in caller before entering prestub, aren't they? If then, is it possible to skip that codes?
Thank you in advance for your help.
DongHeon.

**Comment by jkotas** [comment]
> I think forwarded parameters are guaranteed to have loaded in caller before entering prestub, aren't they?

They are not guaranteed to be loaded. Otherwise, this code would not exist.

**Comment by clamp03** [comment]
@jkotas Thank you for your comment. But, I am still confusing. 
#1. Comments in DoFullyLoad method explains problems in case of type equivalence. I cannot understand why the codes should be executed even if FEATURE_TYPEEQUIVALENCE is disabled.
#2. To call a method which only depends forwarded type, I think caller should know types of callee's parameters to make the parameter value like ordinary parameter. Could you please give an example (which shows forwarded parameters are not loaded in caller before entering Prestub)? It is really helpful to me.
Thank you for your consideration.

**Comment by clamp03** [comment]
This is exploration comment in DoFullyLoad
```
    // Fully load exact parameter types for value type parameters opted into equivalence. This is required in case GC is
    // triggered during prestub. GC needs to know where references are on the stack and if the parameter (as read from
    // the method signature) is a structure, it relies on the loaded type to get the layout information from. For ordinary
    // structures we are guaranteed to have loaded the type before entering prestub - the caller must have loaded it.
    // However due to type equivalence, the caller may work with a different type than what's in the method signature.
    //    
    // We deal with situation by eagerly loading types that may cause these problems, i.e. value types in signatures of
    // methods introduced by this type. To avoid the perf hit for scenarios without type equivalence, we only preload
    // structures that marked as type equivalent. In the no-PIA world
    // these structures are called "local types" and are usually generated automatically by the compiler. Note that there
    // is a related logic in code:CompareTypeDefsForEquivalence that declares two tokens corresponding to structures as
    // equivalent based on an extensive set of equivalency checks..
    //    
    // To address this situation for NGENed types and methods, we prevent pre-restoring them - see code:ComputeNeedsRestoreWorker
    // for details. That forces them to go through the final stages of loading at run-time and hit the same code below.
```

**Comment by jkotas** [comment]
> Could you please give an example (which shows forwarded parameters are not loaded in caller before entering Prestub)?

The examples for these cases are usually very complex. These problems manifest as intermittent crashes during GC.

The fundamental problem is the same for both forwarded parameters and equivalent types. For both these cases, the typeloading can go through multiple hops and the fragile NGen design requires all hops to be pre-initialized up in case the GC is triggered during PreStub.

As you may know, we are not happy with the fragile NGen designs for multiple reason. The current CoreCLR master is not using fragile NGen by default anywhere, and we will be disabling it in the build at some point. (We will still leave the code around since we know you are using it.)

cc @alpencolt @davidwrighton

**Comment by clamp03** [comment]
I know fragile NGen will be deprecated and R2R is recommended than fragil NGen.
However, some our products still use fragile NGen and require better launching time.
Thank you for your understanding.
