### ISSUE TITLE
CurlHandler.EasyRequest.SetProxyOptions() throws ArgException when default credentials used

### ISSUE THREAD

**Issue by rtwede** [dotnet/coreclr#2355]
Data Point 1:
When default credentials are used with the System.Net.Http.CurlHandler.Proxy as is the case in tools such as the DNX tools it results in ArgumentExceptions being thrown due to empty credentials/username.

Data Point 2:
System.Net.CredentialCache.DefaultCredentials is immutably set to a default SystemNetworkCredential (all empty strings for user, password, domain).

Data Point 3:
http://dotnet.github.io/getting-started/
Following the recommended steps to install .net core on Ubuntu Linux includes the step "dotnet restore" and exposes this failure whenever a simple proxy server is configured (e.g http_proxy=http://myserver.domain:8080/)

DNX tools grab the default credendtials and the entire installation fails due to the exception in SetProxyOptions().  It's clear the intention is that the Curl library should detect the lack of credentials and not attempt to use them.  Presently it only succeeds if creds are null, but not when username is an empty string as in the case of the default creds used by DNX tools.

Conclusion:
Fundamentally this is an incompatibility between the three implementations: DNX tools, the CurlHandler.SetproxyOptions() and DefaultCredentials.  One of the three needs to be changed so that the three are compatible with one another.  Arguably the DNX tools or the default credentials could be faulted, but SetProxyOptions seems the friendliest change to the contract between these three components because other clients might similarly use default empty credentials in the case where none are specified or present.

**Comment by tzwlai** [comment]
@SidharthNabar @CIPop PTAL

**Comment by joshfree** [comment]
I've moved this active issue to the corefx repo.  https://github.com/dotnet/corefx/issues/5538
