### ISSUE TITLE
Quationable issues found during nullable annotation

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/coreclr#23573]
During nullable annotation work we encountering some questionable behaviors need more/proper review/discussion
Here is one example: we might want throw exception instead of returning null
```csharp
                default:
                    Debug.Fail("Invalid primitive type");
                    return null!;
```

https://github.com/dotnet/coreclr/pull/23539/files#r270432973

**Comment by jkotas** [comment]
This is unreachable code. The `return null` is there just to make the compiler happy in the least invasive way. What you have done to fix this is fine.
