### ISSUE TITLE
fatal error: 'unixasmmacros.inc' on mac

### ISSUE THREAD

**Issue by ckkashyap** [dotnet/coreclr#2357]
Hi,

I am new to this project - I am very excited after seeing the this talk http://www.infoq.com/presentations/design-c-sharp-7

I tried building coreclr on my mac today and found an issue with icu4c - I have installed homebrew inside my home directory instead of standard path (that requires su) - This got resolved once I edited src/corefx/System.Globalization.Native/CMakeLists.txt and changed ICU_HOMEBREW_INC_PATH to point to my include path under home dir.

After this, build seemed to go through - but with an error 

coreclr/src/vm/amd64/calldescrworkeramd64.S:7:10: fatal error: 'unixasmmacros.inc' file not found

I am on this source - f309d9ebda3ac9d1f254a3c0d6122e40354c826e

Regards,
Kashyap

**Comment by ckkashyap** [comment]
My clang version is this -
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

Based on some searches on issues it seemed to be related to old clang - but it appears that my clang is new.

**Comment by rainersigwald** [comment]
I saw this too on a fresh laptop with `cmake` installed via `brew`. Uninstalling cmake and installing CMake 3.3.2 from https://cmake.org/download/ got me way past that point of failure, so I think this is the same thing as #2054.

**Comment by joshfree** [comment]
@ellismg @eerhardt PTAL

**Comment by janvorli** [comment]
I have fixed that in #2529
