### ISSUE TITLE
Intrinsic byte array search

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#2359]
Was: `Vector.Dot<byte>` is not an intrinsic 

`Vector.Dot<byte>` is [not an intrinsic](https://github.com/dotnet/coreclr/blob/master/src/jit/simd.cpp#L2392) single CPU instruction and is instead composed of a [new object create] (https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/src/System/Numerics/Vector.cs#L4142) followed by [32 byte multiply instructions and 32 byte addition instructions](https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/src/System/Numerics/Vector.cs#L4145) (depending on arch). 

For the aspnet5 server Kestrel this adds up to being 8.23% of the *total* server CPU load as it makes heavy use of it when parsing the ASCII headers.

![dotproduct-cpu](http://aoa.blob.core.windows.net/aspnet/dotproduct.png)

It is correctly listed in [jit/simdintrinsiclist.h](https://github.com/dotnet/coreclr/blob/master/src/jit/simdintrinsiclist.h#L114) as not an intrinsic; but it would help perf greatly if it was (is currently only supported for floats).

Also marking the functions in some why to indicate what is hardware accelerated and what isn't would be helpful.

**Comment by GuardRex** [comment]
@benaadams You rock.

**Comment by PureKrome** [comment]
![](http://www.reactiongifs.com/r/2013/10/tim-and-eric-mind-blown.gif)

**Comment by mikedn** [comment]
And how do you suggest this be implemented given that there's no instruction that actually does this?

**Comment by benaadams** [comment]
@mikedn Working on that bit... or alternative approach. I assume multiple instructions would be ok?

**Comment by GuardRex** [comment]
![842f6fc8db8b35162409154c17d047f7](https://cloud.githubusercontent.com/assets/1622880/11836370/2f206446-a38f-11e5-92f1-71c2793251cb.gif)

**Comment by mikedn** [comment]
> I assume multiple instructions would be ok?

Well, yes, to some extent. The float versions are implemented using shuffles in CPUs that do not have DPPS. But the problem with a byte dot product is that you lack the essential instruction - a packed byte multiplication instruction. Without that you don't have much of a choice but to use 16/32 individual multiplication instructions and that's not very different from what we have now.

**Comment by benaadams** [comment]
Seeing if can use alternative algorithm (instruction-wise) that doesn't use dot product for the same effect; then will see if there are any gaps now know where to check.

**Comment by benaadams** [comment]
@mikedn Ignoring DotProduct as that's just an implementation detail...

Would it be possible to expose `_mm_cmpestri` which would be even better to achieve the same effect and more flexible?

**Comment by benaadams** [comment]
And also `_mm_unpacklo_epi8` and `_mm_unpackhi_epi8` while I'm asking ;-)

**Comment by benaadams** [comment]
Otherwise would probably need a integer horizontal add and a bitscan (the unpacks would still be a bonus)

**Comment by benaadams** [comment]
Added workaround for now https://github.com/aspnet/KestrelHttpServer/pull/494 gives 23% improvement

**Comment by mikedn** [comment]
> Would it be possible to expose  _mm_cmpestri  which would be even better to achieve the same effect and more flexible?

I have no idea if PCMPESTRI has a suitable equivalent on other architectures. It seems a bit too specialized for that to be the case. Unpacks are more likely to have an equivalent but that equivalent might not operate exactly the same.

In general, the idea that one could use a SIMD via a high level API such as the one provided by .NET and write code that works reasonably well on different architectures is a bit naïve. Stuff like adding 2 vectors of 4 floats will usually work fine but beyond that the reality isn't pretty.

**Comment by benaadams** [comment]
PCMPESTRI might work instead for an implementation detail of something like `Span<T>.IndexOf(Span<T>)` where `T` is byte\char\int?

**Comment by mikedn** [comment]
Yes, IMO it would make more sense that existing functionality (Span.IndexOf, Array.IndexOf, String.IndexOf etc.) to somehow make use of whatever advanced instructions the underlying platform has instead of trying to expose those instructions via a general purposes managed API. But that doesn't really solve the problem we are having in the first place - how to expose such instructions to managed code? 

Maybe they don't need to do that, maybe they could just implement some general purpose "find" functions in the native side of the runtime which managed code could call. But what happens in corert where the tendency is to avoid having such stuff implemented in the native runtime?

**Comment by benaadams** [comment]
Closing this, will reopen if have something more concrete.

**Comment by RussKeldorph** [comment]
Closing on @benaadams behalf.

@CarolEidt above discussion FYI.
