### ISSUE TITLE
Linux arm build break.

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2362]
/home/ubuntu/hdd/Projects/coreclr/tests/src/JIT/jit64/mcc/interop/native_i0c.cpp:8:16: error: calling
      convention '__cdecl' ignored for this target [-Werror,-Wignored-attributes]
MCC_API VType0 __cdecl sum(unsigned __int64 first, ...) {

Introduced from bb07af3e0b0e6bf2b9b733ac8b9acd4936e04141.

**Comment by mzaky** [comment]
comment in coreclr/CMakeLists.txt line 467 like:
# All warnings that are not explicitly disabled are reported as errors
#add_compile_options(-Werror)

**Comment by LLITCHEV** [comment]
@jashook @joshfree PR #2567 should fix this issue. Please verify it is fixed and close this issue.
