### ISSUE TITLE
11.5% Regression on ASP.NET Empty App Start-Up

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#23640]
The ASP.NET empty web template app created by running ```dotnet new web``` is 11.5% slower to start-up when running on .NET Core 3.0 vs. 2.2.

Source code for measurement app: 
---------------------------------------
https://github.com/brianrob/tests/tree/master/managed/aspnet_start/src

Start-up time as reported by the app:
-----------------------------------------
This is time from entering main to the app reporting that it is ready.

2.2: 139.6273ms
3.0: 155.7803ms

Analysis of profiles:
---------------------

The profiles for each of these runs show that the main difference is in how much time is spent looking up entry points for R2R methods:

3.0:
![image](https://user-images.githubusercontent.com/6210322/55367157-84bd2680-54a0-11e9-8b8c-8cc5ab823fcd.png)

2.2:
![image](https://user-images.githubusercontent.com/6210322/55367186-ab7b5d00-54a0-11e9-8a94-d3feead32836.png)

This appears to be related to the switch-over of System.Private.CoreLib from fragile NGEN to R2R.  The number of calls into ```ReadyToRunInfo::GetEntryPoint``` has increased from 1546 on 2.2 to 3119 on 3.0.  The big difference is in the number of R2R methods coming from CoreLib (as expected).

I also did a quick test against 3.0 by compiling System.Private.CoreLib using fragile NGEN, and this closed the entire gap.

From what I can see in the traces, it does not appear that code quality is the issue here, but instead, the lookup of the entrypoint.  The bulk of the CPU time looks to be coming from the type system:
![image](https://user-images.githubusercontent.com/6210322/55367446-e762f200-54a1-11e9-9343-c5936661dc01.png)

I'd like to understand what can be done to help mitigate this startup regression, as it impacts every ASP.NET app, and likely every real app.  I can share traces offline if desired.

**Comment by brianrob** [comment]
@fadimounir @jkotas @sergiy-k

**Comment by davidfowl** [comment]
cc @sebastienros @DamianEdwards

**Comment by fadimounir** [comment]
@davidwrighton assigning this to you since you're currently working on perf.

**Comment by sebastienros** [comment]
All the scenarios we track however show better startup

![image](https://user-images.githubusercontent.com/1165805/59472733-5048dd80-8df4-11e9-8b8d-ec1edbddc69e.png)

But we have some differences with the default template, like we don't enable logging, also we keep the default TieredCompilation settings, meaning it's not enabled in 2.2 but it is in 3.0.

**Comment by jkotas** [comment]
> All the scenarios we track however show better startup

Thanks for confirming this. 

We have made number of changes for 3.0, we have still several changes in flight for 3.0, and we will continue looking on startup beyond 3.0.
