### ISSUE TITLE
[3.0.100-preview3] StartsWith bug

### ISSUE THREAD

**Issue by RUSshy** [dotnet/coreclr#23649]
Hello

The following code will produce wrong result:

```c#
            var myString = "hello";


            if (myString == "a")
            {
                
            }
            else if (myString == "b")
            {
                
            }
            else if (myString.StartsWith("ho"))
            {
                Console.WriteLine("you shouldn't be there");
            }
            else if (myString.StartsWith("he"))
            {
                Console.WriteLine("hi");
            }
```

It should print ``hi`` but i get: ``you shouldn't be there`` instead

I'm not sure where to report it so i tried here, sorry if that's not the right place!

Version: 3.0.100-preview3-010431
OS: Windows 10 x64

EDIT:

When using Rider, i get the right result

It's only if i run it from the console; or via third-party program such as RenderDoc

EDIT 2:

Looks like it is a StartsWith bug:

```c#
var myString = "hello";
if (myString.StartsWith("ho"))
{
    Console.WriteLine("you shouldn't be there");
}
```
This will print the message..

**Comment by RussKeldorph** [comment]
@danmosemsft @GrabYourPitchforks Sound familiar?  I couldn't immediately repro this with 3.0.100-preview4-011024 based on the limited information provide.

**Comment by stephentoub** [comment]
@RUSshy, what is the value of CultureInfo.CurrentCulture when you get the unexpected behavior and then when you get the expected behavior?  The StartsWith overload you're using is culture-sensitive.

**Comment by stephentoub** [comment]
> It's only if i run it from the console

Also, can you share exactly how you're building and running it?

**Comment by RUSshy** [comment]
``Console.WriteLine(CultureInfo.CurrentCulture);``

print:

``en-US``

**Comment by RUSshy** [comment]
@RussKeldorph where can i find the preview 4 ? so i can also test this version, maybe it was fixed

**Comment by stephentoub** [comment]
@RUSshy, can you share a zip of the repro?  I'm unable to repro what you're seeing with the information shared.

However, I see `Microsoft.DotNet.ILCompiler` in your .csproj, as well as the rd.xml mention.  Are you actually trying to do something with corert or .NET Native?

**Comment by RussKeldorph** [comment]
@RUSshy I installed a daily from https://github.com/dotnet/core-sdk.

**Comment by RUSshy** [comment]
> @RUSshy, can you share a zip of the repro? I'm unable to repro what you're seeing with the information shared.
> 
> However, I see `Microsoft.DotNet.ILCompiler` in your .csproj, as well as the rd.xml mention. Are you actually trying to do something with corert or .NET Native?

I tried with a new blank project and i still get the issue, at this point i have no idea what could be wrong on my side

**Comment by stephentoub** [comment]
> I tried with a new blank project and i still get the issue

Can you .zip up the project and share it?

**Comment by GrabYourPitchforks** [comment]
Can you also please provide the output of the following lines?

```cs
var sortInfo = CultureInfo.CurrentCulture.CompareInfo.GetSortKey("hello");
Console.WriteLine(sortInfo);
Console.WriteLine(BitConverter.ToString(sortInfo));
```

(And also the same thing for the string "ho".)

**Comment by RUSshy** [comment]
@stephentoub i put project on my repo: https://github.com/RUSshy/arc/

@GrabYourPitchforks is crash with this:

```
Unhandled Exception: System.ArgumentException: External component has thrown an exception.
   at System.Globalization.CompareInfo.CreateSortKey(String source, CompareOptions options)
   at System.Globalization.CompareInfo.GetSortKey(String source)
   at Hello.Program.Main(String[] args) in C:\Users\rus\dev\arc_cs\samples\01_hello\Hello\Program.cs:line 59
```

**Comment by GrabYourPitchforks** [comment]
@RUSshy One final thing to try, please. Let us know the output.

```cs
using System;
using System.Collections.Generic;

public class Program
{
  public static void Main()
  {
    HashSet<string> hashSet = new HashSet<string>(StringComparer.CurrentCulture);
    Console.WriteLine(hashSet.Add("hello"));
    Console.WriteLine(hashSet.Add("he"));
    Console.WriteLine(hashSet.Add("ho"));
  }
}
```

You definitely shouldn't be seeing an exception from `CompareInfo.CreateSortKey`. I'll pull in some experts from the OS side of things to see if they have any thoughts.

**Comment by RUSshy** [comment]
@GrabYourPitchforks 

It also crash:

```
Unhandled Exception: System.ArgumentException: External component has thrown an exception.
   at System.Globalization.CompareInfo.GetHashCodeOfStringCore(ReadOnlySpan`1 source, CompareOptions options)
   at System.Globalization.CompareInfo.GetHashCodeOfString(String source, CompareOptions options)
   at System.CultureAwareComparer.GetHashCode(String obj)
   at System.Collections.Generic.HashSet`1.InternalGetHashCode(T item)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at System.Collections.Generic.HashSet`1.Add(T item)
   at Hello.Program.Main(String[] args) in C:\Users\rus\dev\arc_cs\samples\01_hello\Hello\Program.cs:line 28
```

**Comment by RUSshy** [comment]
![image](https://user-images.githubusercontent.com/18348637/55676371-71f98600-58d4-11e9-8f9d-21f399b4e373.png)

![image](https://user-images.githubusercontent.com/18348637/55676378-7de54800-58d4-11e9-8d73-d642edab851b.png)


I am using an azerty keyboard on an english system, maybe that can causes confusions ?, but again why would it work fine with visual studio and rider, problem might be on the windows Console

**Comment by tarekgh** [comment]
@RUSshy 

Could you please send the following info:

- All contents of the files and folders (names and sizes) under the path C:\Windows\Globalization
- run winver on the machine and send the exact version number of the OS 

Try the following too:

before doing any string search or comparison, execute the following 

CultureInfo.CurrentCulture = new CultureInfo("en-GB"); 

then let me know if this make any difference. 

Thanks for your help.

**Comment by RUSshy** [comment]
Globalization folder: https://send.firefox.com/download/4e946affa3811302/#8uQ7n9XpCIrzhgi2RBxNCQ

winver: Version 1809 (OS Build 17763.379)

![image](https://user-images.githubusercontent.com/18348637/55692469-a3dc1c80-59a8-11e9-9c9b-76e05d3622a1.png)

No luck with this code :/

```c#
CultureInfo.CurrentCulture = new CultureInfo("en-GB"); 

var myString = "hello";
if (myString.StartsWith("ho"))
{
    Console.WriteLine("you shouldn't be there");
}
```

**Comment by RUSshy** [comment]
Something to note: it only happen with Debug build, not with release ( dotnet run --project ..\samples\01_hello\Hello\Hello.csproj --configuration Release )

**Comment by tarekgh** [comment]
@RUSshy I am not seeing anything wrong with the machine which make the case very interesting. could you please try the following code too and send the output? 

```C#

        private const uint FIND_STARTSWITH = 0x00100000;

        [DllImport("kernel32.dll")]
        internal static extern int GetLastError();

        [DllImport("kernel32.dll", CharSet=CharSet.Unicode)]
        internal static extern int FindNLSStringEx(
                    string lpLocaleName,
                    uint dwFindNLSStringFlags,
                    string lpStringSource,
                    int cchSource,
                    string lpStringValue,
                    int cchValue,
                    IntPtr pcchFound,
                    IntPtr lpVersionInformation,
                    IntPtr lpReserved,
                    long sortHandle);

            Console.WriteLine($"FindNLSStringEx Return = {FindNLSStringEx("en-US", FIND_STARTSWITH, "hello", "hello".Length, "ho", "ho".Length, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero, 0)}, {GetLastError()}");
            Console.WriteLine($"FindNLSStringEx Return = {FindNLSStringEx("en-US", FIND_STARTSWITH, "hello", "hello".Length, "he", "he".Length, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero, 0)}, {GetLastError()}");
```

**Comment by RUSshy** [comment]
@tarekgh 

Here is the result:
```
FindNLSStringEx Return = -1, 0
FindNLSStringEx Return = 0, 0
```

**Comment by tarekgh** [comment]
@RUSshy I assume you have ran the code in Debug build when the original problem happen. right?

**Comment by RUSshy** [comment]
yes, from the console, with debug build

**Comment by tarekgh** [comment]
One more request:

Could you please publish the bits, ```dotnet publish -r win-x64``` and then share the whole produced bits? just ensure running the app from the published bits on the machine before you share and ensure you see the problem with the bits. I assume your machine is x64, if it is x86, use ```dotnet publish -r win-x86``` instead to publish.

**Comment by RUSshy** [comment]
Also something interesting is i copied the project folder from ``arc_cs`` to ``arc_cs_test`` and i tested from there and it works fine, but the result of FindNLSStringEx is the same:

```
FindNLSStringEx Return = -1, 0
FindNLSStringEx Return = 0, 0
```

Here  is publish for: arc_cs

https://send.firefox.com/download/17a9bb6952ab138c/#sYpbAibIiNP5S1S3O3vUCg

Here is publish for: arc_cs_test

https://send.firefox.com/download/067de0d0f0c832b5/#1a1O4a9muPcmLMwf6-5fjA

At first look they look the same, but why changing the folder solved the issue ?

**Comment by tarekgh** [comment]
I have tried the bits from your arc_cs and arc_cs_test on my machine and both are working fine. I have used same folder names arc_cs and arc_cs_test.

do you have the folder arc_cs somehow listed in the %PATH% in your machine? maybe something conflicting there.

**Comment by RUSshy** [comment]
Here is a screenshot of my path:

![image](https://user-images.githubusercontent.com/18348637/55764348-642a3900-5a6b-11e9-8e6b-f912f2c850b7.png)


I moved the content of publish from arc_cs to a different folder and no issue!!

There must be something happening or registered for that path i don't know..

**Comment by tarekgh** [comment]
Maybe the easiest way to investigate this is, debug the app when running on arc_cs. Try set breakpoints on 

```C#
myString.StartsWith("ho")
```

and try to look at what point this start to report incorrect values. for example, the code path should eventually do a call to FindNLSStringEx  (not the one you defined in your test). 

I hope I had access to your machine to help you with that.

**Comment by tarekgh** [comment]
or you may try to create [iDNA](https://blogs.windows.com/buildingapps/2017/09/27/time-travel-debugging-now-available-windbg-preview/) debugger dump and share it and I may try to take a look on that.

**Comment by RUSshy** [comment]
I generated the file with iDNA as requested, it is a really large file so i compressed it with 7zip

https://send.firefox.com/download/9b803b14837d7048/#NEIc1lKn-oqCdeoVi8_t5g

**Comment by RUSshy** [comment]
I don't know how to use IDNA really well, i ran it as admin and launched process with generate Time Travel, and it produced the files

I will also try set breakpoint into the StartsWith

**Comment by RUSshy** [comment]
Oh but the problem is the code is fine when i run it with Visual Studio or Rider, so with the debugger it won't help me debug the issue

**Comment by RUSshy** [comment]
Ok i put the code in a while loop and i'm able to debug it by attaching it to process

But it doesn't step into the StartsWith method

From Visual Studio:

![image](https://user-images.githubusercontent.com/18348637/55767382-f2f18280-5a78-11e9-94eb-446882250103.png)

**Comment by tarekgh** [comment]
in Debug->Options->General try to uncheck the following options:

- Enable Just My Code
- Step over properties and operators (Managed only)

then tr to debug again.

**Comment by tarekgh** [comment]
https://send.firefox.com/download/9b803b14837d7048/#NEIc1lKn-oqCdeoVi8_t5g has expired too. 

One thing you can try too, set a breakpoint and run then look at all loaded modules and compare if it is exact same loaded modules when you run from other folder. and it is loaded from the expected path. 

Debug->Windows->Modules

**Comment by tarekgh** [comment]
I am closing this issue as it is really machine environment issue. 

@RUSshy feel free to reply back and we'll continue help you. I hope you can reach the bottom of this issue.
