### ISSUE TITLE
[arm64/windows]Test failed:System.Net.Tests.HttpWebRequestTest.ContentLength_Get_ExpectSameAsGetResponseStream(remoteServer: http://corefx-net-http11.azurewebsites.net/Echo.ashx)

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#23646]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_minopts_tst/27/

**Failed test:**
System.Net.Tests.HttpWebRequestTest.ContentLength_Get_ExpectSameAsGetResponseStream(remoteServer: http://corefx-net-http11.azurewebsites.net/Echo.ashx)

**Failed log:**
```
System.Net.Tests.HttpWebRequestTest.ContentLength_Get_ExpectSameAsGetResponseStream(remoteServer: http://corefx-net-http11.azurewebsites.net/Echo.ashx) [FAIL]
      Assert.Equal() Failure
      Expected: 735
      Actual:   -1
      Stack Trace:
        D:\j\workspace\arm64_cross_c---d6aee07b\_\fx\src\System.Net.Requests\tests\HttpWebRequestTest.cs(236,0): at System.Net.Tests.HttpWebRequestTest.ContentLength_Get_ExpectSameAsGetResponseStream(Uri remoteServer)
        --- End of stack trace from previous location where exception was thrown ---
  Finished:    System.Net.Requests.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Requests.Tests  Total: 655, Errors: 0, Failed: 1, Skipped: 6, Time: 11.739s
----- end  5:48:31.91 ----- exit code 1 ----------------------------------------------------------
COREFX TEST FAILED
```

**Comment by BruceForstall** [comment]
@wfurt @danmosemsft Random test failure?

cc @sandreenko another one for the disable list?

**Comment by wfurt** [comment]
yes, this depends on external services and we lately see many failures either one just like this or getting 500 internal error from Azure. 

One way for coreclr to get more stable runs is to exclude OutLoop tests. For networking that should exclude all external and unreliable tests.

**Comment by RussKeldorph** [comment]
@wfurt We'd prefer to retain as much *reliable* coverage as possible.  Any idea what fraction of outerloop tests are reliable?  If most of them are, I wonder if it would be worth separating the reliable ones from the unreliable ones with another attribute we could use to differentiate.

**Comment by danmosemsft** [comment]
I assumed that essentailly all our `[OuterLoop]` tests are networking (ie if that was less relevant to runtime testing you coudl disable all outerloop) but I did a quick grep and it's only 20%. The largest part of the rest are threading/tasks/parallelism related which are probably important to keep running in CoreCLR.

We should probably do a pass at some point to identify tests that are stable, fast and safe and promot them to innerloop.

**Comment by wfurt** [comment]
This is definitely infrastructure issue and dup of https://github.com/dotnet/corefx/issues/36220
