### ISSUE TITLE
System.Collections.BitArray.Clone() fails when Length near Int32.MaxValue

### ISSUE THREAD

**Issue by speshuric** [dotnet/coreclr#2366]
I found that `System.Collections.BitArray.Clone()` fails when `BitArray` `Length` near `Int32.MaxValue`

**_Repro:**_

``` c#
    int i = 30; // i can be 0..30 and that is valid
    BitArray ba = new BitArray(Int32.MaxValue - i);
    BitArray ba2 = (BitArray)ba.Clone();
    Console.WriteLine(ba2.Length);
```

Expected: `ba2.Length == Int32.MaxValue - i`
Fact: `System.ArgumentException` occurs

**_Analysis**_
This is caused by wrong using of the constructor `BitArray(int[])` in `Clone()` method: 

``` c#
public Object Clone()
{
    Contract.Ensures(Contract.Result<Object>() != null);
    Contract.Ensures(((BitArray)Contract.Result<Object>()).Length == this.Length);

    BitArray bitArray = new BitArray(m_array); // <--- bug is here
    bitArray._version = _version;
    bitArray.m_length = m_length;
    return bitArray;
}
```

Actual Length of `int[] m_array` is `1<<26` and thus there is `Int32.MaxValue+1` bits in it and overflow check in constructor `BitArray(int[])` throws exception.
**_Solution**_
I think that method can be fixed:

``` c#
public Object Clone()
{
    Contract.Ensures(Contract.Result<Object>() != null);
    Contract.Ensures(((BitArray)Contract.Result<Object>()).Length == this.Length);

    return new BitArray(this); 
}
```

Constructor `BitArray(BitArray bits)` works fine and do that it should.
I ready to open PR right now, but I'm in doubt about where should I place unit tests for this case. I checked this fix in the command line app with CoreCLD built from sources.

**_Additional suggestions:**_
Originaly I found this bug in another case. Code was something like this

``` c#
BitArray ba = new BitArray(Int32.MaxValue, true);
// do something with ba
int[] arr = new int[Int32.MaxValue/32 + 1];
ba.CopyTo(arr, 0);
// do something with arr, clear some large regions for example

// now how can I create BitArray from arr?
ba = new BitArray(arr); //exception as expected ...
// there is no good solutions in current API
```

Good solution can be to write constructors like `public BitArray(int[] values, int actualLength)`, where actualLength is exact number of copied bits, but there is API change. 

**_The last suggestion**_
Why `BitArray` is in CoreCLR, but not in CoreFX? This class isn't used in other CoreCLR classes (except one test where it can be replaced easily). This class is not GC/IL/runtime specific. Is it because the class is `[ComVisible]` or there are another reasons?
Dubugging and testing in CoreFX is much easily. Can I help to move this class to CoreFX?

**Comment by speshuric** [comment]
I've found tests for `BitArray`. They are in [CoreFx](https://github.com/dotnet/corefx/tree/master/src/System.Collections/tests/BitArray)
If I add tests now then build will be broken because `BitArray` is in coreclr. What should I do?

**Comment by AlexGhiondea** [comment]
The way we can handle the addition of tests is to wait until the code change is integrated into CoreCLR and a new package is created that has the fix.. Then we can add the tests

**Comment by speshuric** [comment]
> to wait until the code change is integrated into CoreCLR 

How do I know that this happened?

**Comment by AlexGhiondea** [comment]
@speshuric there is no good way to know that yet.
The best I can think of is to see when the version of the coreclr package used in CoreFx has changed to have the fix.

One way to do this is to create a PR with your tests, submit it. The PR will fail until we get the updated CoreCLR package.

/cc @ericstj in case he has a better suggestion.

**Comment by speshuric** [comment]
@AlexGhiondea thanks, I think I'll create PR to coreFX
But what about possibility of moving `BitArray` to coreFX? At the least I can rewrite [test GCQueue.cs]
(dotnet/coreclr/blob/master/tests/src/GC/Stress/Tests/GCQueue.cs) to eliminate the use of `BitArray`. In fact this test uses `BitArray` as "an object to take place in the heap" and test GCQueue.cs is the only usage of BitArray in public repo CoreCLR
