### ISSUE TITLE
MultiByteToWideChar removed from unix exports

### ISSUE THREAD

**Issue by gbalykov** [dotnet/coreclr#23683]
Could you, please, clarify, why #22500 removed `MultiByteToWideChar` from unix exports (`src/dlls/mscoree/mscorwks_unixexports.src`)?

We use this function in Tizen application loader for string conversion. Is there another function to use instead?

cc @alpencolt @alexander-aksenov @jkotas

**Comment by jkotas** [comment]
These exports are meant to be used by ` System.Private.CoreLib` only. We are removing them as CoreLib keeps using less of them.

Why do you need to convert strings to UTF16 in the Tizen application loader? Can you use the "Unix hosting APIs" that take UTF8 strings? https://github.com/dotnet/coreclr/blob/master/src/dlls/mscoree/mscorwks_unixexports.src#L2

**Comment by gbalykov** [comment]
We use `MultiByteToWideChar` to pass argument to `SetEnvironmentVariableW`, which sets environment variable just before the call to `coreclr_execute_assembly`. These are the only two functions we use, which are not from "Unix hosting API". 

What should be the correct approach here?

**Comment by janvorli** [comment]
@gbalykov could you call linux setenv function before calling `coreclr_initialize`? The PAL initialization copies all the env variables from the system environment into its local data structures.

**Comment by jkotas** [comment]
Also, what is the environment that you are setting? Another option may be to pass the piece of data as  key/value pair and fetching it using `AppContext.GetData` on the managed side.

**Comment by gbalykov** [comment]
@janvorli @jkotas 

We need to setup XDG_DATA_HOME right before coreclr_execute_assembly. 

We initialize CoreCLR before application is known, so, during call to coreclr_initialize, correct value of XDG_DATA_HOME is not yet known. Application becomes known only before coreclr_execute_assembly.

SetEnvironmentVariableW was also removed recently. What do you think about adding new Unix hosting API `coreclr_set_environment_variable`?

cc @alpencolt

**Comment by jkotas** [comment]
Would creating a delegate to `Environment.SetEnvironmentVariable` using `coreclr_create_delegate` and calling that to set the environment variable work?

**Comment by gbalykov** [comment]
`Environment.SetEnvironmentVariable` is overloaded and `coreclr_create_delegate` is not allowed to create delegate for overloaded methods, see: https://github.com/dotnet/coreclr/blob/84dc3732c6fd0f4739214eb83ffd643a33a5da17/src/vm/corhost.cpp#L865

What do you think about adding `Environment.SetEnvVariable` with the same signature as `SetEnvironmentVariable`?

```
public static void SetEnvVariable(string variable, string? value)
```

**Comment by jkotas** [comment]
Do you have any convenient assembly in your apps to put this wrapper into?

**Comment by gbalykov** [comment]
Yes, solution with delegate for wrapper, located in our Tizen specific lib, works, thank you!
