### ISSUE TITLE
utf8.cpp returns the address of a stack variable

### ISSUE THREAD

**Issue by omajid** [dotnet/coreclr#23689]
https://github.com/dotnet/coreclr/blob/dffb3d30790131166c848283947125c59e428f38/src/pal/src/locale/utf8.cpp#L1242 returns the address of stack variable `bytes` via `byteUnknown`.

The variable is initialized here: https://github.com/dotnet/coreclr/blob/dffb3d30790131166c848283947125c59e428f38/src/pal/src/locale/utf8.cpp#L1174

 This looks like a bug porting the original code from C# to C.

cc @tmds

**Comment by RussKeldorph** [comment]
@janvorli

**Comment by omajid** [comment]
Thanks for the quick fix!
