### ISSUE TITLE
Remove unused TRACE_LEVEL_NONE

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#23711]
Just chatting with @chrisnas and his team noticed that TRACE_LEVEL_NONE is documented as "Tracing is not on" which isn't really what it means. Level 0 refers to events that will always be sent and they can not be disabled via a level-based filter. It doesn't appear any code actually uses the constant in which case we could delete it.

https://github.com/dotnet/coreclr/blob/dbf6006da52845624577f88f3200447c4a1d8db2/src/inc/eventtracebase.h#L164

**Comment by sywhang** [comment]
There are some code paths that checks whether the level is 0 ... but they don't use this macro. (Just checks by using `==0`. Should we delete this macro? Or should we just change these paths to actually use this macro for better readability?

**Comment by vandebm** [comment]
Prior to removal I did trace TRACE_LEVEL_NONE via the assert to the gcinterface.h
enum GCEventLevel
{
    GCEventLevel_None = 0,
    ...
}
further assertion is based on GCEventLevel_None
