### ISSUE TITLE
Why ICollectionDebugView name as a naming conventions of interface but it is a class

### ISSUE THREAD

**Issue by lindexi** [dotnet/coreclr#23724]
The ICollectionDebugView is a class which name is start with `I` that is the naming conventions of interface.

https://github.com/dotnet/corefx/blob/184089d748b705438a117002143ebb4429ce0d97/src/Common/src/CoreLib/System/Collections/Generic/ICollectionDebugView.cs#L9

**Comment by stephentoub** [comment]
The naming convention is generally `TypeNameDebugView`, and in this case, `TypeName` is `ICollection`, hence `ICollectionDebugView`.  It also doesn't really matter as it's an internal type.
