### ISSUE TITLE
Marshal.PtrToStringUTF8(IntPtr, int) has a different behavior

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#23723]
The `Marshal.PtrToStringUTF8(IntPtr, int)` method has a different behavior as compared to the other `Marshal.PtrToString*(IntPtr, int)` methods.

In particular, the other `PtrToString` methods will throw if `ptr == IntPtr.Zero`. However, `PtrToStringUTF8` will return `null`.

We should resolve these to be consistent.

**Comment by tannergooding** [comment]
It's worth noting that the `PtrToString` methods that just take `IntPtr` (and do not take a length) do return `null` for `ptr == IntPtr.Zero`.

**Comment by tannergooding** [comment]
CC. @jkoritzinsky, @jkotas, @stephentoub

**Comment by jkotas** [comment]
We should sort this out in 3.0 now that `PtrToStringAuto` forwards to `PtrToStringUTF8`. It should be fine to fix `PtrToStringUTF8` to do the same arg validation as other flavors.
