### ISSUE TITLE
Unmanaged generic constrained not respected at runtime

### ISSUE THREAD

**Issue by Doraku** [dotnet/coreclr#23722]
I'm not sure this is the right place but I have encountered something strange (while doing something strange I'll give you that). It seems the `unmanaged` generic constrain which is applied correctly at compile time is not checked at runtime if you were to use reflection to create a generic type with a declaration as such.

This is a small code to reproduce the unexpected behaviour:
```
using System;

namespace UnmanagedFail
{
    class Program
    {
        private interface Ping
        {
            string Pong();
        }

        private class Unmanaged<T> : Ping
            where T : unmanaged
        {
            public string Pong() => "unmanaged";
        }

        private class Managed<T> : Ping
        {
            public string Pong() => "managed";
        }

        private class Generic<T>
        {
            public static Ping Get()
            {
                try
                {
                    return (Ping)Activator.CreateInstance(typeof(Unmanaged<>).MakeGenericType(typeof(T)));
                }
                catch
                {
                    return new Managed<T>();
                }
            }
        }

        private struct NonBlittable
        {
            public object O;
        }

        static void Main(string[] args)
        {
            Console.WriteLine(Generic<bool>.Get().Pong()); // unmanaged
            Console.WriteLine(Generic<string>.Get().Pong()); // managed
            Console.WriteLine(Generic<NonBlittable>.Get().Pong()); // unmanaged ?!

            // not working at compile time as expected
            // Error CS8377  The type 'Program.NonBlittable' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'Program.Unmanaged<T>'
            //Console.WriteLine(new Unmanaged<NonBlittable>.Get().Pong());
        }
    }
}
```

I tried to replace the `unmanaged` constrain with `Enum` and this time got the expected result so some constrains are definitely respected even at runtime when trying to cheat with reflection but not `unmanaged`. I have the same result on netcoreapp2.1 and net472.

I am using this for serialization, to introduce a fast path for blittable type which can just be copied using pointer, setting a delegate in a generic type in its static constructor. Maybe there is a less "hacky" way to detect a type is blittable at runtime?

**Comment by GrabYourPitchforks** [comment]
Just a quick heads up - "unmanaged" doesn't mean that a type can be blittably serialized. It just means that the type contains no reference fields.

"Unmanaged" types are not guaranteed to have the same internal field layouts across versions of the runtime, meaning that on the receiving end you could be deserializing bad data. Additionally, unsafe casting bypasses the normal validation checks a ctor would've performed, meaning that if somebody can manipulate the contents of the serialized buffer they could induce undefined behavior in the receiving application.

**Comment by Doraku** [comment]
> Just a quick heads up - "unmanaged" doesn't mean that a type can be blittably serialized. It just means that the type contains no reference fields.

Even so the `NonBlittable` struct contains an Object field so it definitely does not respect the `unmanaged` constrain as correctly checked at compile time.

> "Unmanaged" types are not guaranteed to have the same internal field layouts across versions of the runtime, meaning that on the receiving end you could be deserializing bad data. Additionally, unsafe casting bypasses the normal validation checks a ctor would've performed, meaning that if somebody can manipulate the contents of the serialized buffer they could induce undefined behavior in the receiving application.

Indeed this is something I am fine with. Data will be platform specific anyway as this is for game development. I have a json like serialisation for development which can be changed to binary optimised later on.

**Comment by GrabYourPitchforks** [comment]
For the runtime portion of your question, see https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.3/blittable.

"The unmanaged constraint is not enforced by CLR, only by the language."

I suspect this is because we wanted developers to be able to use the unmanaged constraint in existing Full Framework applications, where the check is a compile time only check and the runtime isn't aware of this new language keyword. Reflection allows you to violate a whole slew of things the compiler would otherwise enforce. :)

**Comment by GrabYourPitchforks** [comment]
FWIW the fact that reflection allows you to violate the "unmanaged" constraint is still fully type safe, so I cannot think of a good reason we'd introduce a change to block it.

**Comment by Doraku** [comment]
Reading the documentation it is indeed by design that it is only enforced in compilation... Shame, and since I am in unsafe territory I guess I can't really complain for unintended consequences :/ It may still be type safe but I can't help felling weird about ending with a non unmanaged type in a generic type with unmanaged constrain at runtime, guess I'll have to manually check if the type is really unmanaged.

Should I just close this issue then? Thanks for looking into it btw.

**Comment by MichalStrehovsky** [comment]
> Should I just close this issue then? Thanks for looking into it btw.

The `unmanaged` constraint is a C# language semantic. It's not expected that reflection (or other languages) will enforce this.

It's different from e.g. the `new()` constraint that is part of the ECMA-335 specification.

Let's close this.
