### ISSUE TITLE
RyuJIT: Methods containing PInvoke calls are not inlined

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#2373]
I expect TestGetCurrentProcessorNumberInlined call to be inlined into TestGetCurrentProcessorNumber method. But the fact that the method contains a pinvoke call makes it non-inlinable.
Even flagging with AggressiveInlining doesn't help.

Seems that it is a change from .NET 4.5.1 behavior, though not sure - I don't have any pre 4.6 machines to check that.

```C#
[MethodImpl(MethodImplOptions.NoInlining)]
static int TestGetCurrentProcessorNumber()
{
    return TestGetCurrentProcessorNumberInlined();
}

[MethodImpl(MethodImplOptions.AggressiveInlining)]
static int TestGetCurrentProcessorNumberInlined()
{
    return GetCurrentProcessorNumber();
}

[DllImport("kernel32"), System.Security.SuppressUnmanagedCodeSecurity]
public static extern int GetCurrentProcessorNumber();
```

Calling GetCurrentProcessorNumber  via a wrapper makes it twice slower compared with calling it directly.
Here is the numbers on Windows 7:

Direct      |       Wrapper
-------------|-------------------
90.35      |     45.49

Is it a required change?

**Comment by AndyAyersMS** [comment]
@omariom I see it getting inlined ... can you double-check your results?  Please make sure your test case is compiled for optimized codegen (eg /debug:pdbonly). I

If you can repro, it would help if you could share your test case exe.

```
Inlines into Test:TestGetCurrentProcessorNumber():int
  [IL=0000 TR=000001] [aggressive inline attribute] Test:TestGetCurrentProcessorNumberInlined():int
```

**Comment by omariom** [comment]
@AndyAyersMS 

My bad. I didn't check the generated output and assumed it was uninlining.

The issue is that when `GetCurrentProcessorNumber` is called via an inlined wrapper is gets slow.
The code I used:

```C#
         var sw = Stopwatch.StartNew();
         TestGetCurrentProcessorNumber();
         Console.WriteLine(sw.ElapsedMilliseconds);

//...

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void TestGetCurrentProcessorNumber()
        {
            for (int i = 0; i < 10000000; i++)
            {
                int num = GetCurrentProcessorNumber();
                //int num = TestGetCurrentProcessorNumberInlined();
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static int TestGetCurrentProcessorNumberInlined()
        {
            return GetCurrentProcessorNumber();
        }

        [DllImport("kernel32")]
        public static extern int GetCurrentProcessorNumber();
```
It is 150 ms vs about 2000.

Codegen for calling via wrapper:
```ASM
; Assembly listing for method CoreClrTest.Program:TestGetCurrentProcessorNumber()
G_M60093_IG01:
       56                   push     rsi
       4883EC20             sub      rsp, 32

G_M60093_IG02:
       33F6                 xor      esi, esi

G_M60093_IG03:
       E804D0FFFF           call     CoreClrTest.Program:GetCurrentProcessorNumber():int
       FFC6                 inc      esi
       81FE80969800         cmp      esi, 0x989680
       7CF1                 jl       SHORT G_M60093_IG03

G_M60093_IG04:
       4883C420             add      rsp, 32
       5E                   pop      rsi
       C3                   ret      

; Total bytes of code 28, prolog size 5 for method CoreClrTest.Program:TestGetCurrentProcessorNumber()
; ============================================================
```
Direct call:
```ASM
; Assembly listing for method CoreClrTest.Program:TestGetCurrentProcessorNumber()
G_M60092_IG01:
       55                   push     rbp
       4157                 push     r15
       4156                 push     r14
       4155                 push     r13
       4154                 push     r12
       57                   push     rdi
       56                   push     rsi
       53                   push     rbx
       4883EC68             sub      rsp, 104
       488DAC24A0000000     lea      rbp, [rsp+A0H]

G_M60092_IG02:
       488D4D90             lea      rcx, bword ptr [rbp-70H]
       498BD2               mov      rdx, r10
       E8ECD9CC5E           call     CORINFO_HELP_INIT_PINVOKE_FRAME
       488BF0               mov      rsi, rax
       4C8BDC               mov      r11, rsp
       4C895DB0             mov      qword ptr [rbp-50H], r11
       4C8BDD               mov      r11, rbp
       4C895DC0             mov      qword ptr [rbp-40H], r11
       33FF                 xor      edi, edi

G_M60092_IG03:
       4533DB               xor      r11, r11
       48B8485FC6C4FB7F0000 mov      rax, 0x7FFBC4C65F48
       488945A0             mov      qword ptr [rbp-60H], rax
       488D0517000000       lea      rax, G_M60092_IG05
       488945B8             mov      qword ptr [rbp-48H], rax
       488D4590             lea      rax, bword ptr [rbp-70H]
       48894610             mov      qword ptr [rsi+16], rax
       C6460C00             mov      byte  ptr [rsi+12], 0

G_M60092_IG04:
       FF155312E9FF         call     [CoreClrTest.Program:GetCurrentProcessorNumber():int]

G_M60092_IG05:
       C6460C01             mov      byte  ptr [rsi+12], 1
       833D9009046000       cmp      dword ptr [(reloc)], 0
       7406                 je       SHORT G_M60092_IG06
       FF15A8650360         call     [CORINFO_HELP_STOP_FOR_GC]

G_M60092_IG06:
       488B4598             mov      rax, bword ptr [rbp-68H]
       48894610             mov      qword ptr [rsi+16], rax
       FFC7                 inc      edi
       81FF80969800         cmp      edi, 0x989680
       7CAD                 jl       SHORT G_M60092_IG03

G_M60092_IG07:
       C6460C01             mov      byte  ptr [rsi+12], 1

G_M60092_IG08:
       488D65C8             lea      rsp, [rbp-38H]
       5B                   pop      rbx
       5E                   pop      rsi
       5F                   pop      rdi
       415C                 pop      r12
       415D                 pop      r13
       415E                 pop      r14
       415F                 pop      r15
       5D                   pop      rbp
       C3                   ret      

; Total bytes of code 159, prolog size 24 for method CoreClrTest.Program:TestGetCurrentProcessorNumber()
; ============================================================
```

**Comment by AndyAyersMS** [comment]
@omariom thanks, I see what you're getting at -- the version that uses the inline wrapper ends up more poorly optimized. Let me dig in a bit and see why.

**Comment by AndyAyersMS** [comment]
This is deliberate behavior by the jit. The method `impCheckForPInvokeCall` is responsible for checking if an "inline pinvoke" is possible (by which we mean: the various bits of setup required for pinvoke are inlined; the call itself is not). But the call to this check from `impIimportCall` is done only when looking at code from the root method. So if a pinvoke call is propagated into a method via inlining it doesn't get this treatment.

There is some trickiness involved in measuring pinvoke overhead. In the inline case some of the pinvoke cost is paid in the caller's prolog and epilog. So if a method has an inlined pinvoke call in a loop the overhead per call is lower than if there wasn't a loop.

To illustrate this, I [updated your example](https://github.com/AndyAyersMS/coreclr/tree/PinvokeBench) to show 4 variations on a theme: calling the pinvoke directly or via a wrapper, and having the call be directly in a loop or in a noinline method that's invoked in a loop. The results were as follows:

| Call Site In Loop | Call Via Wrapper | Time | Note |
|----|----|----|---|
| Yes | No   | 159 | inline, loop |
| No   | No   | 214 | inline, isolated |
| Yes | Yes | 232 | via stub |
| No   | Yes | 239 | via stub, isolated |

So there are basically 3 levels of performance: calling via the pinvoke stub (slowest), calling via an isolated inline pinvoke (middle), and calling via an inline pinvoke in a loop (fastest). For the isolated cases, the inline pinvoke sequence saves a little bit of time (~10%) over calling via a stub, but costs quite a bit of extra code size (around 100 bytes in your example above)

So we're trying to strike a balance between faster code (always use the inline sequence) and smaller code (never use the inline sequence).  Not optimizing pinvokes pulled in by inlines is one way to keep code size contained while not overly hurting performance of the typical pinvoke (the isolated case).

I was curious to see if we could estimates the potential code size growth if we more aggressively expanded pinvokes inline, so I made the logic in `impImportCall` apply to inlinees as well. But I hit asserts downstream, so there are apparently deeper issues that will require fixing before we can experiment further.

We don't have any immediate plans of changing behavior here, but would be interested to hear about non-benchmarky cases where the current behavior has a noticeable performance impact.

**Comment by omariom** [comment]
Now it is much more clear. The mistake was to call it in a loop.

Is it  still worth calling pinvoked method directly  when there are more than one call sites of it in a caller method? 
For methods  like`GetCurrentProcessorNumber`, which are a few instructions in user mode, it might save on establishing   pinvoke infrastructure.

**Comment by AndyAyersMS** [comment]
The whole reason that the inline pinvoke setup splits into two parts is so that when you call a pinvoke in a loop the overhead is reduced. So I wouldn't say what you did was a *mistake* -- it was an opportunity to observe that the underlying behavior is a bit more complicated than it might seem.

As per your question: direct pinvoke calls at multiple sites in a single method would provide a good size/speed tradeoff. Whether it is worth it or not I can't say. My recommendation would be to first of all try and write clear and understandable code. If performance becomes an issue then you then might consider reshaping the code to work better given the current behavior of the jit and runtime.

I'm also curious to see if other people have made the same reasonable assumption you did, and call pinvokes via `AggressiveInlining` wrappers. Since the jit know knows the reason why inlnee code was brought into a method, I think we can get some data here. I'll report back in a bit.

**Comment by AndyAyersMS** [comment]
Looking at the crossgen of mscorlib (~20,000 methods), there aren't any pinvokes from `AggressiveInline` inlinees. There are 137 pinvoke call sites in normal inlinees, with 65 distinct pinvoke targets. I don't know offhand how many of these inlinees look like simple wrappers.

Mscorlib may be a special case, though. So I also tried CscBench (it is fairly jit-intensive, jitting over 4000 methods) and saw only 10 call sites where pinvokes were brought in via inlining, none from aggressive inlines.

So given this admittedly limited look at code samples, pinvoke wrappers don't appear to be very common.

**Comment by omariom** [comment]
Then I suppose..

![184c7ad6a602de574707d1006faabb7d](https://cloud.githubusercontent.com/assets/1781701/13547711/cabcd22a-e2ed-11e5-8942-4e1a95e23cf7.jpg)

**Comment by glenn-slayden** [comment]
Is there any effect from (or relevance to) applying `[MethodImpl(MethodImplOptions.AggressiveInlining)]` to the P/Invoke declaration *itself*, and/or did you examine this? Such an application *is* semantically accepted by the attribution system.

**Comment by AndyAyersMS** [comment]
Adding AggressiveInlining to a pinvoke declaration has no effect.
