### ISSUE TITLE
[Alpine.38.Arm64] Unable to load shared library 'System.Native' or one of its dependencies

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#23749]
After https://github.com/dotnet/coreclr/issues/23621 had been fixed I re-ran testing in https://github.com/dotnet/coreclr/pull/23702 and there is another issue came up with running the tests on Alpine.38.Arm64
```
+ /root/helix/work/correlation/corerun /root/helix/work/correlation/xunit.console.dll baseservices.compilerservices.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -notrait 'category=outerloop' -notrait 'category=failing'

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'System.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libSystem.Native: No such file or directory
   at Interop.Sys.Stat(Byte& path, FileStatus& output)
   at Interop.Sys.Stat(ReadOnlySpan`1 path, FileStatus& output)
   at System.IO.FileSystem.FileExists(ReadOnlySpan`1 fullPath, Int32 fileType, ErrorInfo& errorInfo)
   at System.IO.File.Exists(String path)
   at Xunit.AssemblyHelper..ctor(String assemblyFileName, IMessageSink internalDiagnosticsMessageSink)
   at Xunit.AssemblyHelper.SubscribeResolveForAssembly(Type typeInAssembly, IMessageSink internalDiagnosticsMessageSink)
   at Xunit.ConsoleClient.Program.Main(String[] args)
Aborted (core dumped)
```

I am going to do initial investigation so assigning to myself

/cc @janvorli @RussKeldorph

**Comment by janvorli** [comment]
My wild guess is that we have a similar problem in corefx to the one we had in coreclr. In other words, the System.Native.so has missing symbols.

**Comment by echesakovMSFT** [comment]
I think you are right 
corefx has this https://github.com/dotnet/corefx/blob/871c5eae12ce339221ef0329009470c9945e34e5/cross/toolchain.cmake#L63
as well as core-setup
https://github.com/dotnet/core-setup/blob/7c5ad7177d42e70641677bd039f5d4e889832e0b/cross/toolchain.cmake#L63

**Comment by echesakovMSFT** [comment]
Are toolchain.cmake supposed to be exactly the same in all three repos?

**Comment by janvorli** [comment]
Yes. I am sorry I have not realized it before. In fact, we have already created a copy of the whole cross folder in arcade. We have it mapped in eng/common/cross. We should start using that instead so that we don't have to update the three locations every time.

**Comment by echesakovMSFT** [comment]
Looks like System.Native.so is linked against glibc
```
/coreclr/tests/Linux.arm64.Checked/Tests/Core_Root $ readelf -d System.Native.so

Dynamic section at offset 0xfd80 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000003 (PLTGOT)             0x1ffe8
 0x0000000000000002 (PLTRELSZ)           3480 (bytes)
 0x0000000000000017 (JMPREL)             0x42c0
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000007 (RELA)               0x41b8
 0x0000000000000008 (RELASZ)             264 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          4
 0x0000000000000006 (SYMTAB)             0x228
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x20b8
 0x000000000000000a (STRSZ)              6283 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x3948
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-aarch64.so.1]
 0x000000000000000e (SONAME)             Library soname: [System.Native.so]
 0x000000000000000c (INIT)               0x5058
 0x000000000000000d (FINI)               0xc764
 0x000000000000001a (FINI_ARRAY)         0x1fd70
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000019 (INIT_ARRAY)         0x1fd78
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000006ffffff0 (VERSYM)             0x3eac
 0x000000006ffffffc (VERDEF)             0x4138
 0x000000006ffffffd (VERDEFNUM)          1
 0x000000006ffffffe (VERNEED)            0x4154
 0x000000006fffffff (VERNEEDNUM)         3
 0x0000000000000000 (NULL)               0x0
```

**Comment by janvorli** [comment]
Ah, so it seems we are pulling in a wrong nuget package, right?

**Comment by echesakovMSFT** [comment]
Yep, this one is wrong
`runtime.linux-arm64.microsoft.private.corefx.netcoreapp/4.6.0-preview4.19201.9`

I am trying to find where we define the dependency in MSBuild

**Comment by echesakovMSFT** [comment]
When we restore **microsoft.private.corefx.netcoreapp** targeting linux-musl-arm64 the wrong **runtime.linux-arm64.microsoft.private.corefx.netcoreapp** got restored. Filed https://github.com/dotnet/corefx/issues/36617

**Comment by echesakovMSFT** [comment]
https://github.com/dotnet/corefx/pull/36636 is merged in - as soon as the corefx publishes official build with these changes - I will re-run testing in https://github.com/dotnet/coreclr/pull/23702 to confirm.

**Comment by echesakovMSFT** [comment]
Closed with https://github.com/dotnet/corefx/pull/36636
