### ISSUE TITLE
Provide an Out-of-Process Control Mechanism for EventPipe that is usable by external customers

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#23780]
This is the same as #18658 with the explicit requirement that external customers can use the control mechanism. This means it has to have a public and documented API.

**Comment by noahfalk** [comment]
I'm removing the documentation tag. Although that is a part of it, the primary effort here should be around API review (amongst our team, not official BCL review) and deciding what we want to support for customers. This is a higher bar than we'd hold for internal APIs because we want to maintain compat across versions and make sure we are using best practices for naming and design. Its likely there will be implementation adjustments that fall out from the API review. We also need to get the library published on NuGet.

**Comment by noahfalk** [comment]
@tommcdon - if you care, this issue could be migrated to diagnostics repo - there is no runtime work tracked here because the library is out of band.

**Comment by tommcdon** [comment]
Moved to dotnet/diagnostics#191
