### ISSUE TITLE
[Cross-build for Android] Failed to download termux packages

### ISSUE THREAD

**Issue by lujiaxing** [dotnet/coreclr#23807]
Hello everyone,

I'm trying to make a cross-build for android. And i had some issue on initializing toolchain.
Several packages from termux are missing. But there's another version of these packages. I'm not sure to change the package version will lead to other problems or not.

`libicu_60.2 → libicu_64.1`
`libicu-dev_60.2 → libicu-dev_64.1`
`libandroid-support_22 → libandroid-support_24`
`liblzma-dev_5.2.3 → liblzma-dev_5.2.4`
`libunwind-dev_1.2.20170304 → libunwind-dev_1.3.1`
`libunwind_1.2.20170304 → libunwind_1.3.1`

Another proplem is one of the packaged called "`libandroid-support-dev`" are totally removed from termux packages. Nowhere to find it, and difficult to corss-compile it for AARCH64 platform.

![image](https://user-images.githubusercontent.com/7188738/55716868-9d8e8480-5a2a-11e9-9625-c84bea0a4b37.png)

![image](https://user-images.githubusercontent.com/7188738/55718273-ec89e900-5a2d-11e9-8c94-efe067b8ec81.png)

Can i just remove it, or somebody workaround for this???

Related file:
[https://github.com/dotnet/coreclr/blob/master/cross/build-android-rootfs.sh](url)

Related issue:
[https://github.com/dotnet/coreclr/issues/10997](url)

**Comment by am11** [comment]
For `libandroid-support-dev`, we can replace it with `ndk-sysroot`, based on https://github.com/Auxilus/termux-makepkg/pull/1.
Can you try rebuilding after `ndk-sysroot` replacement and updating the other package versions your mentioned? If it works (compiles + [PAL tests](https://github.com/dotnet/coreclr/blob/42bc2de2c63fe0c95a582e642ff97b2fe0d4bb7e/Documentation/building/unix-test-instructions.md#pal-tests) pass), you can send a pull request.

**Comment by lujiaxing** [comment]
> For `libandroid-support-dev`, we can replace it with `ndk-sysroot`, based on [Auxilus/termux-makepkg#1](https://github.com/Auxilus/termux-makepkg/pull/1).
> Can you try rebuilding after `ndk-sysroot` replacement and updating the other package versions your mentioned? If it works (compiles + [PAL tests](https://github.com/dotnet/coreclr/blob/42bc2de2c63fe0c95a582e642ff97b2fe0d4bb7e/Documentation/building/unix-test-instructions.md#pal-tests) pass), you can send a pull request.

yep. it works. thanks.

**Comment by lujiaxing** [comment]
Additionally, I had to add
[http://termux.net/dists/stable/main/binary-aarch64/gettext-dev_0.19.8.1-1_aarch64.deb  ](url)
to make compiler happy.

btw: Changing "build-android-rootfs.sh" every time is always not a good solution. And those third-party packages can break compilation at any time
cc @janvorli

**Comment by janvorli** [comment]
> btw: Changing "build-android-rootfs.sh" every time is always not a good solution.

I completely agree, it is unfortunate. I was thinking in the past that we might remedy the changing versions issue by reading and parsing the http://termux.net/dists/stable/main/binary-aarch64/Packages file. But given the fact that you had to add a new package and replace a package that got removed by another one makes this idea useless.
