### ISSUE TITLE
[x86] Test failed: System.IO.Tests.CloseTests.AfterDisposeThrows

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#23802]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstress1/771/

**Failed tests:**
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly(chunkedTransfer: True, connectionClose: True, mode: Token)
System.IO.Tests.CloseTests.AfterDisposeThrows
System.IO.Tests.CloseTests.AfterCloseThrows
System.IO.Tests.StreamWriterWithBufferedStream_CloseTests.AfterDisposeThrows
System.IO.Tests.StreamWriterWithBufferedStream_CloseTests.AfterCloseThrows
System.Tests.BufferTests.BlockCopy_Invalid
System.Runtime.InteropServices.Tests.PtrToStringUniTests.PtrToStringUni_NegativeLength_ThrowsArgumentExeption
System.Runtime.InteropServices.Tests.PtrToStringUTF8.PtrToStringUTF8_ZeroPointer_ReturnsNull
System.Runtime.InteropServices.Tests.PtrToStringUTF8.PtrToStringUTF8_Win32AtomPointer_ReturnsNull
System.Runtime.InteropServices.Tests.PtrToStringUTF8.PtrToStringUTF8_NegativeLength_ThrowsArgumentOutOfRangeExeption
System.Runtime.InteropServices.Tests.PtrToStringAnsiTests.PtrToStringAnsi_NegativeLength_ThrowsArgumentExeption

**Log:**
```
System.IO.Tests.CloseTests.AfterDisposeThrows [FAIL]
        Assert.Null() Failure
        Expected: (null)
        Actual:   MemoryStream { CanRead = False, CanSeek = False, CanTimeout = False, CanWrite = False, Capacity = (throws ObjectDisposedException), ... }
        Stack Trace:
          D:\j\workspace\x86_checked_w---5bf0b08a\_\fx\src\System.IO\tests\StreamWriter\StreamWriter.CloseTests.cs(44,0): at System.IO.Tests.CloseTests.ValidateDisposedExceptions(StreamWriter sw)
```

**Comment by BruceForstall** [comment]
@stephentoub Just curious: you closed this. It that because it's been fixed? (PR?), or ???

**Comment by stephentoub** [comment]
It was a moment-in-time issue.  The jitstress tests run against a live corefx; any time there's a purposeful breaking change made in coreclr, we can't fix the corefx tests to validate the new behavior until the coreclr build is published and ingested into corefx.  If the jitstress tests run in that interim, they see inconsistent results.

**Comment by BruceForstall** [comment]
Great. "Point in time due to intentional breaking change" is what I wanted to know.
