### ISSUE TITLE
Shared static lock in Exception.RestoreDispatchState

### ISSUE THREAD

**Issue by kevingosse** [dotnet/coreclr#23811]
We ran into an issue where a service would become unresponsive with 100% CPU, with 200 threads stuck in `Exception.RestoreDispatchState`. This method is called by `ExceptionDispatchInfo.Throw`, itself called by the TaskAwaiter when a faulted task is awaited: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Runtime/CompilerServices/TaskAwaiter.cs#L183

The issue with `Exception.RestoreDispatchState` is that it tries to acquire a static shared lock: https://github.com/dotnet/coreclr/blob/de68c9ddd18f863fd67098ab28d19206c9c66627/src/System.Private.CoreLib/src/System/Exception.CoreCLR.cs#L364-L370

The scenario we ran into is basically:
 - a service processes a high number of requests (4000+ per second)
 - for some reason, a bunch of them suddenly fail, throwing exceptions
 - the sudden lock contention + spinning increases the CPU usage and causes other requests to timeout
 - the timeouts cause exceptions that contend the lock even more...

We've mitigated the issue by chaining an empty `ContinueWith` to prevent `await` from throwing, then manually extracting the exception to log it. Still, I wonder if the static lock was necessary in the first place.

**Comment by danmosemsft** [comment]
@stephentoub thoughts?

**Comment by danmosemsft** [comment]
@noahfalk do you have context on the need for this lock? It seems something the diagnostics team must have more context on:

https://github.com/dotnet/coreclr/blob/de68c9ddd18f863fd67098ab28d19206c9c66627/src/System.Private.CoreLib/src/System/Exception.CoreCLR.cs#L362-L363

**Comment by jkotas** [comment]
This lock prevents getting into inconsistent state when one exception instance is thrown from multiple threads.

This is description from TFS changeset 483095 that introduced it:

Title: Fix for DD 318658

Issue description:
  If a managed stacktrace contains dynamic frames, then the exception
  object maintains a separate array to track the corresponding resolver
  objects to ensure that the dynamic frames are kept alive. Until now, the
  access to the stacktrace and the dynamic method array was not
  synchronized. Thus, when the same exception object, containing dynamic
  frames as part of the stacktrace, is thrown across multiple threads,
  then the stacktrace and the dynamic method array go out of sync, leading
  to possible buffer overrun occasionally.

Change description:
  This change fixes the problem by ensuring that the stacktrace and the
  dynamic method array are accessed in a synchronized fashion. Thus, they
  will not go out of sync, removing the potential for an overrun.

**Comment by stephentoub** [comment]
> This lock prevents getting into inconsistent state when one exception instance is thrown from multiple threads.

That couldn't be achieved by locking on the exception object itself or on some object it contains, rather than on a static?

**Comment by jkotas** [comment]
> That couldn't be achieved by locking on the exception object itself or on some object it contains

Yes, it can. 

A slightly more involved fix would be to use immutable pattern to store the stacktraces. It should avoid the need to copy them in `ExceptionDispatchInfo.Throw`. I think the copying of the stacktraces for each async rethrow is contributing to problem. It just got amplified by the global lock.

cc @janvorli

**Comment by GSPP** [comment]
A few years ago I examined exception rethrowing scalability with EDI. I found that it does not scale at all with rising thread count. Maybe this issue is the same issue that I found or maybe there was another.

Maybe it's worth setting up a very simple benchmark that continuously rethrows from multiple threads. This should show very severe contention points.

**Comment by kevingosse** [comment]
I kinda forgot this issue. Tests on https://github.com/dotnet/coreclr/pull/26950 show that, while the shared lock has a dramatic effect on .net framework, it doesn't seem to cause any trouble on .net core.
