### ISSUE TITLE
CoreRun not parsing CORE_LIBRARIES correctly

### ISSUE THREAD

**Issue by eli-fin** [dotnet/coreclr#23820]
The documentation [here](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingCoreRun.md) says the `CORE_LIBRARIES` environment variable is "A Semicolon separated list of directories to look for DLLS to resolve any assembly references".
However, it didn't seem to work for me.

As you can see in the [code](https://github.com/dotnet/coreclr/blob/2516a53b75ef74b585cc507e07d39e37675993b9/src/coreclr/hosts/corerun/corerun.cpp#L273), the value is not split by semicolons and a '\\\\' is appended only to it's end (and not after each ';').

I guess either the documentation or the code should be fixed.

In any case, is there another way to get CoreRun to recognize more than 1 library folder?

**Comment by RussKeldorph** [comment]
@jeffschwMSFT

**Comment by swaroop-sridhar** [comment]
SImilarly for UnixCorerun; In the unix case, the issue affects both TPA and NativeDllSearchDirectories.

**Comment by janvorli** [comment]
I believe the bug is in the doc, the code predates the doc by at least a couple of years and the CORE_LIBRARIES was intended to contain path to a single directory. 
The intention was that corerun would look for assemblies into two directories - the directory where the application assembly resides and the directory where the runtime  / FX libraries reside.
For more complex lookup policies, the dotnet / apphost was created.

**Comment by janvorli** [comment]
@eli-fin is there a reason why you would like to use corerun instead of the dotnet host?

**Comment by eli-fin** [comment]
@janvorli,
Not really, I guess.
I just wasn't very familiar with .net core and wanted to test something quickly with my own runtime build.
CoreRun seemed like the quickest way to do it and I was counting on the documented behavior of `CORE_LIBRARIES`.

**Comment by sdmaclea** [comment]
Fixed doc.

**Comment by xiangzhai** [comment]
> @eli-fin is there a reason why you would like to use corerun instead of the dotnet host?

Because there is only `./bin/Product/Linux.mips64.Debug/corerun` available at very begining when porting CoreCLR to other targets, for example, mips64el:

```
$ ./bin/Product/Linux.x64.Debug/corerun HelloWeb.dll

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

```

Workaround patch:

```
diff --git a/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp b/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp
index f97f262993..428a472b66 100644
--- a/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp
+++ b/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp
@@ -328,12 +328,18 @@ int ExecuteManagedAssembly(
     char *coreLibraries = getenv("CORE_LIBRARIES");
     if (coreLibraries)
     {
-        nativeDllSearchDirs.append(":");
-        nativeDllSearchDirs.append(coreLibraries);
-        if (std::strcmp(coreLibraries, clrFilesAbsolutePath) != 0)
-        {
-            AddFilesFromDirectoryToTpaList(coreLibraries, tpaList);
-        }
+        char *coreLibrary = NULL;
+        const char *delim = ":";
+        coreLibrary = strtok(coreLibraries, delim);
+        while (coreLibrary != NULL) {
+            nativeDllSearchDirs.append(":");
+            nativeDllSearchDirs.append(coreLibrary);
+            if (std::strcmp(coreLibrary, clrFilesAbsolutePath) != 0)
+            {
+                AddFilesFromDirectoryToTpaList(coreLibrary, tpaList);
+            }
+            coreLibrary = strtok(NULL, delim);
+       }
     }
 
     nativeDllSearchDirs.append(":");
```

So it is able to use `CORE_LIBRARIES` as a `:` separated list of directories:

```
$ export CORE_LIBRARIES="/home/loongson/zhaixiang/coreclr-2.1/Tools/dotnetcli/shared/Microsoft.NETCore.App/2.1.0:/home/loongson/zhaixiang/coreclr-2.1/Tools/dotnetcli/shared/Microsoft.AspNetCore.App/2.1.3"
```

**Comment by janvorli** [comment]
@xiangzhai you could just copy the assemblies to the same folder as corerun or corerun to the same folder as the assemblies instead of making a change to the corerun. Would that work for you?

**Comment by xiangzhai** [comment]
> @xiangzhai you could just copy the assemblies to the same folder as corerun or corerun to the same folder as the assemblies instead of making a change to the corerun. Would that work for you?

Works :P
