### ISSUE TITLE
string.Normalize(NormalizationForm.FormKD) behaves differently on different platforms

### ISSUE THREAD

**Issue by Leon99** [dotnet/coreclr#23831]
ASP.NET Core 2.2, `string.Normalize(NormalizationForm.FormKD)` behaves as expected on Windows 10 and Ubuntu 18.04, but when executed on (kind of Linux that is used in Azure App Services for Linux ), it behaves as `string.Normalize(NormalizationForm.FormC)`/`string.Normalize(NormalizationForm.FormKC)`
Example:
`"ü".Normalize(NormalizationForm.FormKD).Count(x => x < 128)` returns 1 on my Windows 10 dev box, as well as on Ubuntu 18.04 build machine, but 0 in when it runs in Azure. `string.Normalize(NormalizationForm.FormC)`/`string.Normalize(NormalizationForm.FormKC)` also return 0 on Win10/Ubuntu (didn't try in Azure).

**Comment by RussKeldorph** [comment]
@tarekgh

**Comment by tarekgh** [comment]
@Leon99 In general .NET Core gets the normalization behavior from the underlying OS, so in some cases it is expected to see some differences. But in this case, I suspect the globalization invariant mode is enabled when running on Azure. could you please check when you run on Azure if the environment variable DOTNET_SYSTEM_GLOBALIZATION_INVARIANT is defined there?

**Comment by tarekgh** [comment]
I suspect this is similar to https://github.com/dotnet/corefx/issues/36631 because of  globalization environment mode.

**Comment by Leon99** [comment]
@tarekgh DOTNET_SYSTEM_GLOBALIZATION_INVARIANT is not defined.
I'm not sure if there is a simple way to execute arbitrary C# code in Azure App Services for Linux. Is there anything I could check from its SSH console?

**Comment by tarekgh** [comment]
could you please try 2 things:

- dump all environment variables on the image and sent it out.
- check if libicu is installed on this image.

Also, maybe if you have the file /etc/os-release or /etc/redhat-release, send the contents to know what version of Linux you are running on.

thanks for your help here.

**Comment by Leon99** [comment]
Environment variables:
```
APPDATA = /opt/Kudu/local
ASPNETCORE_ENVIRONMENT = Test
ASPNETCORE_URLS = http://0.0.0.0:8181
COMPUTERNAME = RD0003FF671D44
DEBIAN_FRONTEND = noninteractive
DOTNET_CLI_TELEMETRY_PROFILE = AzureKudu
DOTNET_RUNNING_IN_CONTAINER = true
DOTNET_SKIP_FIRST_TIME_EXPERIENCE = 1
DOTNET_USE_POLLING_FILE_WATCHER = true
FRAMEWORK = DOTNETCORE
FRAMEWORK_VERSION = 2.2
HOME = /home
HOSTNAME = 5d8784a90ecb
HTTP_HOST = xxx.scm.azurewebsites.net
HTTP_LOGGING_ENABLED = 1
KUDU_APPPATH = /opt/Kudu
KUDU_RUN_USER = xxx
LANG = C.UTF-8
MSI_ENDPOINT = 
MSI_SECRET = 
NUGET_PACKAGES = /var/nuget
NUGET_XMLDOC_MODE = skip
OLDPWD = /
PATH = /home/site/deployments/tools:/opt/Kudu/Scripts:/usr/bin:/usr/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools:/opt/nodejs/9/bin
PORT = 8181
PWD = /opt/Kudu
PYTHONIOENCODING = UTF-8
REMOTEDEBUGGINGVERSION = 15.0.28010.00
SHLVL = 1
SITE_BITNESS = AMD64
WEBSITE_AUTH_ENABLED = False
WEBSITE_AUTH_ENCRYPTION_KEY = xxx
WEBSITE_AUTH_SIGNING_KEY = xxx
WEBSITE_HTTPLOGGING_RETENTION_DAYS = 1
WEBSITE_INSTANCE_ID = xxx
WEBSITE_OWNER_NAME = xxx
WEBSITE_RESOURCE_GROUP = xxx
WEBSITE_ROLE_INSTANCE_ID = 0
WEBSITE_SITE_NAME = xxx
_ = /sbin/runuser
```
 /etc/os-release:
```                                                                                                                                                         NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.2
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```
Happy to check for libicu if you tell me how to do it.

**Comment by tarekgh** [comment]
Thanks for the info. you are running on Alpine which I learned the Alpine images enable the globalization invariant mode https://github.com/dotnet/dotnet-docker/blob/master/2.2/runtime-deps/alpine3.8/amd64/Dockerfile#L22. We have informed the team creating such image about this issue and they are working to fix that. You may follow the issue https://github.com/Microsoft/Oryx/issues/68 which tracking the same the problem but with different symptoms.

The interesting thing here is the environment flag is not showing in your list which I am not sure if the invariant mode is enabled by different way. Is it possible to run your service and then dump all modules loaded in the service process? this can tell if ICU libraries loaded or not. Or is it possible you can create a simple net core 2.2 console project on other machine and publish it and then copy the published folder to the Alpine image and run it through the ssh.  I mean something like:

```Xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>
</Project>
```
And your C# code will be something simple like:

```C#
using System;
using System.Globalization;

class Program
{
    static void Main(string[] args)
    {
         Console.WriteLine($"{System.Globalization.CultureInfo("it").EnglishName}");
    }
}
```

Then you can compile and publish like:

```
dotnet restore
dotnet build 
dotnet publish -r linux-x64
```

then copy the published bits to the azure machine and run it through ssh

thanks again for your help.

**Comment by tarekgh** [comment]
CC @kichalla who is looking at similar issue.

**Comment by tarekgh** [comment]
@Leon99 any news? I just want to confirm you are running with Invariant Globalization mode to ensure this is the same issue as https://github.com/Microsoft/Oryx/issues/68 and we are not missing anything.

**Comment by Leon99** [comment]
I gave up on doing it this way and solved my problem differently (all I needed was removing diacritics).
