### ISSUE TITLE
GCPROTECT_BEGININTERIOR on a OBJECTREF* in methodtable.cpp

### ISSUE THREAD

**Issue by omajid** [dotnet/coreclr#23842]
https://github.com/dotnet/coreclr/blob/b1042c7a758f032c4effb96d429c95ad1280295a/src/vm/methodtable.cpp#L3231-L3232

We are calling `GCPROTECT_BEGININTERIOR` on a `OBJECTREF*`, not an `OBJECTREF`. Is that right? `frames.h` talks about doing a `sizeof` on the argument, which doesn't seem like it would work well with the pointer.

**Comment by jkotas** [comment]
`GCPROTECT_BEGININTERIOR` is meant to be used on pointers into the middle of the object. It can be used on any pointer - `int*`, `void*`, and `OBJECTREF*` too.

I do not see any problem with this code.
