### ISSUE TITLE
ilasm / ildasm should be independent of a .NET Core installation

### ISSUE THREAD

**Issue by jaredpar** [dotnet/coreclr#23840]
The ilasm / ildasm tools are essentially native tools yet they have a dependency on .NET Core in order to create the metadata reader / writer APIs. While they depend on .NET Core the packages they are shipped in do not deploy it. Correctly deploying a .NET Core installation on top if ilasm / ildasm is left as an exercise to the consumer. 

That exercise is **painful**. Every time Roslyn has to update to a new version it takes 2-4 days in order to do this correctly. Mostly due to dependencies in the required packages having conflicting versions of matching DLLs. 

Issue #15059 already aims at fixing the packaging but that seems to miss the point a bit. The more root issue seems to be that ilasm / ildasm shouldnt' have a .NET Core dependency at all. If they're pure native tools then the packaging and consumption story are both dramatically easier. 

After discussing with @RussKeldorph and @MichalStrehovsky this seems to be doable. If the metadata APIs are factored out into a static lib this could then be linked into both the ilasm and coreclr libraries. That would break the dependency.

**Comment by MichalStrehovsky** [comment]
I believe this is fixed in master with #25144. I assume we want this in 3.next, so keeping this issue open for tracking.

**Comment by jkotas** [comment]
3.next = 5.0 = current master.

David did not merge this in before the final snap for 3.x because the change looked too risky for 3.x.
