### ISSUE TITLE
ParseCommandLine in util.cpp handles pdst being null inconsistently

### ISSUE THREAD

**Issue by omajid** [dotnet/coreclr#23866]
Initially, `ParseCommandLine` does checks to handle the case where `pdst` can be null:

https://github.com/dotnet/coreclr/blob/289b7036dfa172fcbdb812c03ccfd599d6d09724/src/vm/util.cpp#L44

But later on, it seems to mix up that assumption by unconditionally doing `pdst++`:

https://github.com/dotnet/coreclr/blob/289b7036dfa172fcbdb812c03ccfd599d6d09724/src/vm/util.cpp#L94

Perhaps this code should assume/assert that `pdst` can never be null?

**Comment by janvorli** [comment]
It seems the code is correct. IThe pdst needs to be incremented so that it we can return how much space is needed in case the pdst was NULL. See the comment on the ParseCommandLine:
https://github.com/dotnet/coreclr/blob/289b7036dfa172fcbdb812c03ccfd599d6d09724/src/vm/util.cpp#L26-L29

**Comment by omajid** [comment]
Ah. Sorry for the noise, then.
