### ISSUE TITLE
Re-enable System.Text.Encoding tests in CoreCLR

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/coreclr#23864]
We have some unit tests from the __System.Text.Encoding.Tests__ project suppressed in __CoreFX.issues.json__ since they were failing while the UTF-8 work was taking place. This is a tracking issue to re-enable them once the tests are fixed in CoreFX and make their way over here.

**Comment by jkotas** [comment]
We are not tracking removing individual entries in CoreFX.issues.json. The plan is to delete all exclusions in CoreFX.isssues.json once the CoreFX test drop is updated.
