### ISSUE TITLE
[x64] Precondition failure in x64_checked_windows_nt_corefx

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#23860]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/826/

**Log:**
```
Assert failure(PID 4764 [0x0000129c], Thread: 7676 [0x1dfc]): Precondition failure: FAILED: !(section->Characteristics & ~((0x00000020 | 0x00000040 | 0x00000080| 0x02000000 | 0x04000000 | 0x08000000 | 0x20000000 | 0x40000000 | 0x80000000 | 0x10000000)))
  	 FAILED: CheckNTHeaders()
  		d:\j\workspace\x64_checked_w---a7bd363e\src\inc\pedecoder.inl, line: 701
```

**Comment by BruceForstall** [comment]
@sergiy-k Something your team can look at?

Unfortunately, these runs normally time out so we don't have good history.

**Comment by RussKeldorph** [comment]
@fadimounir

**Comment by fadimounir** [comment]
Thanks. I'll take a look

**Comment by fadimounir** [comment]
@BruceForstall It's not clear to me which test is failing or what are the steps to reproduce this issue locally. Could you please send me some repro instructions?

**Comment by BruceForstall** [comment]
@fadimounir It doesn't fail all the time; the last job passed. Here's the latest failure, from May 2:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/852/consoleFull#2080323506f66db340-b3cd-4e23-8190-9b52cb916333

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/852/

Honestly, I'm not sure which test caused this assert. The corefx test runs interleave multiple threads of output, so it's impossible to tell what is running. And it appears that a VM assert is not properly treated as a test failure by the corefx test harness.

**Comment by sergiy-k** [comment]
@RussKeldorph, I'm curious why you marked this issue as area-ReadyToRun?

**Comment by RussKeldorph** [comment]
@sergiy-k Best guess given that R2R has some effect on the file format and @fadimounir's willingess to take a look.  Not much more than that.  If you don't think it's the correct area, feel free to change it, but I'd prefer to keep it *some* area.  We try pretty hard to assign areas to almost all issues (at least non-milestone:Future) so it's pretty clear who is responsible for driving them to closure.

**Comment by fadimounir** [comment]
Not much can be done with this bug now. Jenkings is gone, and not sure which corefx test caused this failure anymore. Closing issue.
If this comes back wit the azure runs, we'll be able to investigate better
