### ISSUE TITLE
We JIT some methods that should already have R2R code, even when tiered compilation is disabled

### ISSUE THREAD

**Issue by fadimounir** [dotnet/coreclr#23873]
Repro app: https://github.com/ridomin/msix-catalog

1. cd msix.catalog.app
2. set ReadyToRun property to true in the .core.csproj file
3. Add this workaround to the csproj (#23872):
`  <ItemGroup>
    <ReadyToRunExclude Include="DirectWriteForwarder.dll" />
  </ItemGroup>`
4. dotnet publish -r win-x64 to produce the R2R images
5. set COMPLUS_TieredCompilation=0 and run the app

This will require the SDK bits from here for now: https://github.com/fadimounir/sdk/tree/CrossgenRefList:
1) clone repo
2) build
3) eng\dogfood.cmd and dotnet publish the app from there

Running this under PerfView, we can see that JIT is triggered for some methods that should be compiled in R2R images.
Example: System.Configuration.ClientConfigurationHost.get_HasRoamingConfig() in assembly System.Configuration.ConfigurationManager.dll

Note: crossgen will emit warnings when unable to compile a method due to a missing feature when using the /verbose switch, but for the example method above, crossgen's stdout indicates that the method has been compiled correctly.

We need to investigate:
1) If the method has really been compiled in the R2R image
2) Why it's being rejitted even with COMPLUS_TieredCompilation=0

**Comment by fadimounir** [comment]
/cc @brianrob @jkotas 

Brian, if you have some free cycles, feel free to pick this up and investigate why we're jitting something that should have R2R code. It might be a by-design limitation, or a missing feature... who knows.

i'm currently working on functional issues, so it might take me a while to get back to this issue.

**Comment by brianrob** [comment]
@fadimounir thanks for sharing.  If I can, I will take a look.  It may take me some time as well to get to this one, but appreciate you sharing.

**Comment by AndyAyersMS** [comment]
ETW jit events should indicate when there was R2R code for a method that could not be used.

**Comment by brianrob** [comment]
Yes, and if memory serves, I have updated PerfView to actually consume these bits so that they show up properly in the Events view.

**Comment by fadimounir** [comment]
I investigated this with the latest bits, and I can't find such cases anymore. I did however find another interesting opportunity for pinvoke compilation, for "out" byref parameters in signatures. 

Closing this issue
