### ISSUE TITLE
Potentially missing checks for intrinsics modeled as Calls in the morph and optimizer phases.

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#2388]
In order to allow for the optimizers to optimize special calls (object GetType()) for example, they are converted to intrinsics for the optimizer phases and then back to calls.
There is a potential of missing code to deal with the new intrinsics in the optimizers. Before this change, they were GT_CALL trees and now they are GT_INTRINSIC tree.
I have added TODO comments in the places I spotted going through the code (there might be more). There is a Keyword that identifies these places. Searching for IntrinsicsModeledAsACall should result in the places I have spotted.

**Comment by LLITCHEV** [comment]
A version of the code with the TODOs mentioned above is at PR https://github.com/dotnet/coreclr/pull/2390
Or branch RemorphAssert or fork: http://github.com/LLITCHEV/coreclr.

**Comment by sivarv** [comment]
Given the fix that is checked-in to model Obj.GetType() intrinsic's side effect  as throwing an exception using GTF_EXCEPT flag, correctness issue is addressed.  The only remaining issue, is tail prefixed intrinsics implemented by backend as calls.  JIT right now ignores tail prefix on those calls by converting them to GT_INTRINSIC nodes.

**Comment by hoyMS** [comment]
#3254 checked in.
