### ISSUE TITLE
new AV during crossgen introduced by PR 23828

### ISSUE THREAD

**Issue by marklio** [dotnet/coreclr#23939]
Commit 5608b4ff0f81b99a5d436dec1e23b393503a4e07 introduced the check:

```
    if (IsReadyToRunCompilation() && !m_pImage->GetCompileInfo()->IsInCurrentVersionBubble(m_pEEJitInfo->getMethodModule(method)))
```

There are cases where method can be null here, which leads to an eventual AV.  SharpDX  (https://www.nuget.org/packages/SharpDX/2.6.3) is an example of a NuGet package that hits this. I'd be happy to provide others.

**Comment by marklio** [comment]
assigning fadi since he made the original change.

**Comment by fadimounir** [comment]
Thanks @marklio. I was just investigating that and will send a PR with a fix :)
