### ISSUE TITLE
Switch to workstation GC in case of constrained CPU resources

### ISSUE THREAD

**Issue by luhenry** [dotnet/coreclr#23949]
Right now, if the user sets the configuration so that the server GC is used, the server GC will be loaded even in conditions where we know the workstation GC would fare better. An example of such conditions is constrained environment where there is only 1 or less CPU or with very low memory.

This can be harmful if users deploy the same projects on different kind of platforms: deploying to a 20+ cores server and to Azure Functions will require largely different configurations for the runtime.

A constraint is we do not necessarily want to transparently switch under the hood, without leaving the final choice to the user.

There are already multiple ways for the user to specify to use the server GC or not:
 - setting `COMPlus_gcServer` as an environment variable
 - setting `gcServer` in the configuration file
 - setting `System.GC.Server` passed to `coreclr_initialize`

The questions are:
 1. is it ok to switch under the hood, even going against the user's request?
 1. if so, how do we signal it?
 1. if not, how do we surface this possibility of using the server GC if and only if the resources on the machine allows it?

I would favor surfacing to the user a knob (fitting in the existing ones) to try loading the server GC, knowing that it will fallback to workstation GC in case of low resources.

/cc @Maoni0 @jkotas @sergiy-k @davidwrighton

**Comment by Maoni0** [comment]
actually the current behavior is already automatically using workstation GC if you are running an uni-proc machine so this switching is implicit. container should follow the same policy.

**Comment by luhenry** [comment]
@Maoni0 where do we automatically fallback to using workstation GC in case of an uni-proc machine?

**Comment by Maoni0** [comment]
hmm, based on a cursory look of coreclr source it's apparently not the case. on full CLR we've always had this. that's a bug then and should be fixed, for both with and without a container.
