### ISSUE TITLE
AssemblyLoadContext.EnterContextualReflection could produce a null reference exception

### ISSUE THREAD

**Issue by safern** [dotnet/coreclr#23952]
During nullable annotations I noticed that when calling `AssemblyLoadContext.EnterContextualReflection(Assembly)` with an implementation of `Assembly` that it's base type is not `RuntimeAssembly` it would produce a null reference exception. 

We call `GetLoadContext` which will return null if the `Assembly` is not a `RuntimeAssembly` -- then we try to dereference it without checking for null.

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.CoreCLR.cs#L257

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Runtime/Loader/AssemblyLoadContext.cs#L513

cc: @stephentoub @jkotas @sdmaclea

**Comment by sdmaclea** [comment]
This is the fix I would recommend.
```C#
public static ContextualReflectionScope EnterContextualReflection(Assembly? activating)
{
    AssemblyLoadContext? assemblyLoadContext = (activating != null) ? 
        GetLoadContext(activating) : null;
    return assemblyLoadContext?.EnterContextualReflection() ?? ContextualReflectionScope(null);
}
```

@safern I can create the PR or let you.

**Comment by sdmaclea** [comment]
@jkotas Perhaps `GetLoadContext` shouldn't return `null`.  Like this...
```C#
// Returns the load context in which the specified assembly has been loaded
public static AssemblyLoadContext GetLoadContext(Assembly assembly)
{
    if (assembly == null)
    {
        throw new ArgumentNullException(nameof(assembly));
    }

    // If the assembly is not a RuntimeAssemby of GetLoadAssembly(rtAsm) returns null, 
    // then the assembly was bound using the TPA binder
    AssemblyLoadContext loadContextForAssembly = AssemblyLoadContext.Default;

    RuntimeAssembly rtAsm = assembly as RuntimeAssembly;

    // We only support looking up load context for runtime assemblies.
    if (rtAsm != null)
    {
        IntPtr ptrAssemblyLoadContext = GetLoadContextForAssembly(rtAsm);
        if (ptrAssemblyLoadContext != IntPtr.Zero)
        {
            loadContextForAssembly = (AssemblyLoadContext)(GCHandle.FromIntPtr(ptrAssemblyLoadContext).Target);
        }
    }

    return loadContextForAssembly;
}
``

**Comment by jkotas** [comment]
> Perhaps GetLoadContext shouldn't return null. Like this...

I do not think that returning Default context as fallback for non-runtime assemblies would make sense. The alternative would be to throw `Argument_MustBeRuntimeAssembly`, but that would be a breaking change that I do not think we should make.

**Comment by jkotas** [comment]
I have submitted doc update in https://github.com/dotnet/dotnet-api-docs/pull/2300. Also, I have noticed that we do not have a test coverage for the non-runtime assembly case. @sdmaclea Could you please take care of adding it?

**Comment by sdmaclea** [comment]
@jkotas How do I load a non-runtime assembly?

**Comment by jkotas** [comment]
The reflection object model is abstract. Runtime provides one implementation of it, but the same object model can have other independent implementations. For example, we are shipping MetadataLoadContext in 3.0 that is non-runtime implementation of reflection object model (more details in https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-1-and-open-sourcing-windows-desktop-frameworks/).

Here is an example of CoreFX test that tests similar codepaths: https://github.com/dotnet/corefx/blob/09f4f7ed59992bc7bff6fe42bc75ef5b08c8c4e2/src/System.Resources.ResourceManager/tests/ResourceManagerTests.cs#L385
