### ISSUE TITLE
Assertion failed '!inlineeLocal.lclIsPinned'

### ISSUE THREAD

**Issue by marklio** [dotnet/coreclr#23950]
See IL repro at the bottom. Please let me know if you need more info, or a repro of a different form. This assert is seen on 479 real assemblies from NuGet.org. This IL pattern seems to be an older pattern formerly produced by csc for fixed blocks, but the code for the packages I could find no longer produces this pattern on recent compilers (there is a &int32 that is pinned rather than the int32*).

Save the IL below as test.il
ilasm test.il /dll
run amd64 CHK crossgen on test.dll:
crossgen.exe /in test.dll /out test.ni /nologo /verbose /platform_assemblies_paths "paths_to_il"
Expected: successful compilation
Actual:
```
Opening input file
Preloading input file D:\scratch\crossgenrepros\!inlineeLocal.lclIsPinned\test.dll
Compiling input file D:\scratch\crossgenrepros\!inlineeLocal.lclIsPinned\test.dll
Compiling method Program.Main

Assert failure(PID 30140 [0x000075bc], Thread: 25608 [0x6408]): Assertion failed '!inlineeLocal.lclIsPinned' in 'Program:Main(ref):int' (IL size 12)

    File: c:\users\markmil\source\repos\coreclr\src\jit\importer.cpp Line: 19084
    Image: C:\Users\markmil\Source\Repos\PMIExperiment\CrossGenner\bin\Debug\netcoreapp3.0\coreclr\crossgen.exe
```
IL Repro:

```
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}

.assembly Test
{
  .custom instance void [mscorlib]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 ) 
  .custom instance void [mscorlib]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
                                                                                                             63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )       // ceptionThrows.
  .hash algorithm 0x00008004
  .ver 1:0:0:0
}
.module Test.dll
.imagebase 0x00400000
.file alignment 0x00000200
.stackreserve 0x00100000
.subsystem 0x0003       // WINDOWS_CUI
.corflags 0x00020003    //  ILONLY 32BITPREFERRED

.class public sequential ansi sealed beforefieldinit Program
	extends [mscorlib]System.Object
{
	.method private hidebysig static 
		int32 Main (
			string[] args
		) cil managed 
	{

		.maxstack 1
		.entrypoint
		.locals init (
			[0] int32
		)
		nop
		ldc.i4.s 100
		stloc.0
		ldloca.s 0
		call int32 Program::GetValueUnsafe(int32&)
		ret
	}

	.method private hidebysig 
		static int32 GetValueUnsafe (
			int32& buffer
		) cil managed 
	{
		.maxstack 3
		.locals init (
			[0] int32* pinned
		)

		ldarg.0
		stloc.0
		ldloc.0
		ldind.i4
		ret
	}
}
```

**Comment by AndyAyersMS** [comment]
Looks like an overly cautious assert.

**Comment by AndyAyersMS** [comment]
Hmm, maybe not quite that simple.

We now assume only GC refs are pinnable, and this matters because we allow inlining methods with pinned locals (in some cases) and need to unpin them (as part of nulling out all local GC refs), and that won't suffice for cases where the pinned local is not explicitly a GC ref.

So if we see pinned pointer locals, we either need to bail out of inlining or adjust the post-inline nulling logic to also null out these locals.

**Comment by marklio** [comment]
I can get information about the patterns that we see in the ecosystem if it helps make a decision about how to handle these.

**Comment by AndyAyersMS** [comment]
I'm planning on  broadening out the current nulling code to handle these -- it is relatively straightforward.

**Comment by VSadov** [comment]
Does `int32* pinned` actually pin anything?

There seems nothing in the spec that prevents adding `pinned` to any local. But I wonder if doing that with `int32*`, `native int` or anything else that is not a manged pointer/reference has any effect?

**Comment by VSadov** [comment]
Old CSC had bugs in this area. Instead of pinning the original managed reference it could unintentionally pin the unmanaged pointer copy (which was supposed to be created _after_ pining). 

I just wonder whether it still worked.

**Comment by AndyAyersMS** [comment]
> Does `int32* pinned` actually pin anything?

Good point; `int32* pinned` does not pin anything, at least not with current RyuJit. 

But it looks like jit32 will handle this. Let me dig in some more.
```
43             |             [ESP+00H] an untracked pinned byref local
F0 02          |             iptrMask = 02
9B             | 0014        call 0 [ ESI']
```

**Comment by VSadov** [comment]
That makes it irrelevant whether `int32*` are zeroed or not. The assert still needs to be fixed one way or another.

**Comment by AndyAyersMS** [comment]
Right, I am thinking now that the jit should just ignore the pinned modifiers on locals unless they are of type class or byref.

**Comment by marklio** [comment]
> Right, I am thinking now that the jit should just ignore the pinned modifiers on locals unless they are of type class or byref.

It is interesting that this pattern is a pattern that was produced by some version of the C# compiler in response to "fixed" blocks and is in use in a number of NuGet packages like SharpDX and some others. Has this usage of pinned ever been honored?

**Comment by AndyAyersMS** [comment]
I don't see how it ever could have been honored. Jit32 has more or less identical logic and only will report pinned GC refs. Have not looked at Jit64 yet.

Presumably the C# compiler versions with the bug would get pinning right most of the time and there's  some particular rare pattern or construct that leads to mistakenly pinning the unmanaged pointer. @VSadov do you have more info on this issue?

And unfortunately you can get away with not pinning things much of the time, so perhaps this has just gone under the radar?

**Comment by VSadov** [comment]
I do not remember exactly. I think it was only in few cases.

There are only 3 forms of fixed that old compiler supported - 
1. fixed arrays
2. fixed strings
3. fixed references (less common)

This is the case `#3`
I will check the other cases.

**Comment by VSadov** [comment]
Strings and arrays are pinned correctly.

```cs
unsafe class C1
{
	public static void Main()
	{
		string s = "qqqq";
		fixed(char* ch = s)
		{
			System.Console.WriteLine(*ch);
		}

		char[] a = new char[10];
		fixed(char* ch = a)
		{
			System.Console.WriteLine(*ch);
		}

	}
}
```

results in:

old CSC  ( C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe ):
```
.method public hidebysig static 
	void Main () cil managed 
{
	// Method begins at RVA 0x2050
	// Code size 78 (0x4e)
	.maxstack 2
	.entrypoint
	.locals init (
		[0] string,
		[1] char*,
		[2] char[],
		[3] char& pinned,
		[4] string pinned,
		[5] char[]
	)

	IL_0000: ldstr "qqqq"
	IL_0005: stloc.0
	IL_0006: ldloc.0
	IL_0007: stloc.s 4
	IL_0009: ldloc.s 4
	IL_000b: conv.i
	IL_000c: dup
	IL_000d: brfalse.s IL_0015

	IL_000f: call int32 [mscorlib]System.Runtime.CompilerServices.RuntimeHelpers::get_OffsetToStringData()
	IL_0014: add

	IL_0015: stloc.1
	IL_0016: ldloc.1
	IL_0017: ldind.u2
	IL_0018: call void [mscorlib]System.Console::WriteLine(char)
	IL_001d: ldnull
	IL_001e: stloc.s 4
	IL_0020: ldc.i4.s 10
	IL_0022: newarr [mscorlib]System.Char
	IL_0027: stloc.2
	IL_0028: ldloc.2
	IL_0029: dup
	IL_002a: stloc.s 5
	IL_002c: brfalse.s IL_0034

	IL_002e: ldloc.s 5
	IL_0030: ldlen
	IL_0031: conv.i4
	IL_0032: brtrue.s IL_0039

	IL_0034: ldc.i4.0
	IL_0035: conv.u
	IL_0036: stloc.3
	IL_0037: br.s IL_0042

	IL_0039: ldloc.s 5
	IL_003b: ldc.i4.0
	IL_003c: ldelema [mscorlib]System.Char
	IL_0041: stloc.3

	IL_0042: ldloc.3
	IL_0043: conv.i
	IL_0044: ldind.u2
	IL_0045: call void [mscorlib]System.Console::WriteLine(char)
	IL_004a: ldc.i4.0
	IL_004b: conv.u
	IL_004c: stloc.3
	IL_004d: ret
} // end of method C1::Main
```

Roslyn:
```
.method public hidebysig static 
	void Main () cil managed 
{
	// Method begins at RVA 0x2050
	// Code size 69 (0x45)
	.maxstack 2
	.entrypoint
	.locals init (
		[0] char*,
		[1] string pinned,
		[2] char*,
		[3] char[] pinned
	)

	IL_0000: ldstr "qqqq"
	IL_0005: stloc.1
	IL_0006: ldloc.1
	IL_0007: conv.u
	IL_0008: stloc.0
	IL_0009: ldloc.0
	IL_000a: brfalse.s IL_0014

	IL_000c: ldloc.0
	IL_000d: call int32 [mscorlib]System.Runtime.CompilerServices.RuntimeHelpers::get_OffsetToStringData()
	IL_0012: add
	IL_0013: stloc.0

	IL_0014: ldloc.0
	IL_0015: ldind.u2
	IL_0016: call void [mscorlib]System.Console::WriteLine(char)
	IL_001b: ldnull
	IL_001c: stloc.1
	IL_001d: ldc.i4.s 10
	IL_001f: newarr [mscorlib]System.Char
	IL_0024: dup
	IL_0025: stloc.3
	IL_0026: brfalse.s IL_002d

	IL_0028: ldloc.3
	IL_0029: ldlen
	IL_002a: conv.i4
	IL_002b: brtrue.s IL_0032

	IL_002d: ldc.i4.0
	IL_002e: conv.u
	IL_002f: stloc.2
	IL_0030: br.s IL_003b

	IL_0032: ldloc.3
	IL_0033: ldc.i4.0
	IL_0034: ldelema [mscorlib]System.Char
	IL_0039: conv.u
	IL_003a: stloc.2

	IL_003b: ldloc.2
	IL_003c: ldind.u2
	IL_003d: call void [mscorlib]System.Console::WriteLine(char)
	IL_0042: ldnull
	IL_0043: stloc.3
	IL_0044: ret
} // end of method C1::Main

```

**Comment by VSadov** [comment]
I checked SharpDX sources (https://github.com/sharpdx/SharpDX/search?q=fixed&unscoped_q=fixed)

Yes, many of `fixed` there fit the pattern that old compiler was not good at. That could lead to  rare/stress failures unless the referred memory does not move for some other reasons.

I'd still recommend to rebuild with newer compiler. 
Unless we are looking at some old packages...

CC: @xoofx

**Comment by marklio** [comment]
The bad IL definitely exists in old packages. I can do deeper analysis on versions to track conversion to new compilers to see how bad the issue is.

**Comment by jkoritzinsky** [comment]
@VSadov just want to clarify: pinning `ref` variables was buggy in the old compiler?

Also re SharpDX: the newer package versions (4.X) are built on the newer compiler through the .NET SDK. I can’t vouch for the 3.X packages though.

**Comment by VSadov** [comment]
The form   `fixed (type* unmanaged = &managed){ } `  was broken.

The `<managed>` here could be anything expression that represents a location - ref parameter, field of an object, array element, etc ...
