### ISSUE TITLE
#enhancement fullnameof and other

### ISSUE THREAD

**Issue by lobster2012-user** [dotnet/coreclr#23968]
Hi!
There is a very convenient operator - nameof.
He cuts all after the last point.
But sometimes it is useful to display the full name.
* fullnameof
    ```csharp
   fullnameof (NameSpace.Class.Property)
   fullnameof (ObjectName.Property)
   ```

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/csharplang/issues/2154
