### ISSUE TITLE
[JitStressRegs=4, 0x80] System.Text.Encoding.Extensions.Tests fails with EncodingTests.UTF7.GetBytes_BufferBoundary_Pointer [FAIL]

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#2397]
**Configuration**
 Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreFX tests: release
  
 **Run run-test with sudo** to avoid corefx test hang

**Failures**

Pass without JitStressRegs=4/0x80
Fail with JitStressRegs=4 and returns exit code 33. Report 33 test failures
Fail with JitStressRegs=0x80 and returns exit code 2. Report 2 test failures.

The error messages are:

Assert.Equal() Failure
      Expected: 1276448408
      Actual:   0

Test names:

EncodingTests.UTF7.GetBytes_BufferBoundary_Pointer
EncodingTests.UTF7.GetBytes_BufferBoundary
EncodingTests.UTF7.CorrectClassesOfInput
EncodingTests.UTF8.WellFormedByteSequence
EncodingTests.UTF7.CorrectClassesOfInput
EncodingTests.UTF32LE.Surrogates

Stack trace:

EncodingTests.UTF7.GetBytes_BufferBoundary_Pointer [FAIL]
      Assert.Equal() Failure
      Expected: 1276448408
      Actual:   0
      Stack Trace:
            at EncodingTests.EncodingTestHelper.GetBytesTestAutoBuffer(Encoding encoding, Char[] inputBuffer, Int32 inputIndex, Int32 inputCount, Int32 outputIndex, Byte[] expectedOutput, Int32 expectedOutputCount)
            at EncodingTests.UTF7.GetBytes_BufferBoundary_Pointer()

For the details, search for result="Fail" in:
[testResults.xml.txt](https://github.com/dotnet/coreclr/files/67288/testResults.xml.txt)

**Comment by hoyMS** [comment]
Not repro
