### ISSUE TITLE
Add hardware intrinsic: AddWithCarry

### ISSUE THREAD

**Issue by mazong1123** [dotnet/coreclr#23975]
Related to #22343

Some arithmetic operations in BigInteger can be improved by using `_addcarry_*` intrinsics. Taking [BigInteger.Add()](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Number.BigInteger.cs#L393-L395) as an example:

```csharp
                while (smallIndex < smallLength)
                {
                    // *** could be improved by using _addcarry_u32 ***
                    ulong sum = carry + large._blocks[largeIndex] + small._blocks[smallIndex];
                    carry = sum >> 32;
                    // *** could be improved by using _addcarry_u32 ***

                    result._blocks[resultIndex] = (uint)(sum);

                    largeIndex++;
                    smallIndex++;
                    resultIndex++;
                }
```

Adding `_addcarry_*` series of intrinsics is the prerequisite to improve the performance of `BigInteger`.

**Comment by ericwj** [comment]
Why `uint*` and `ulong*`? Shouldn't this be `ref uint` and `ref ulong`? It would be just as useful to have this in UWP for example, where `unsafe` is not allowed.

**Comment by tannergooding** [comment]
> It would be just as useful to have this in UWP for example, where unsafe is not allowed.

All of the Hardware Intrinsics are considered platform specific and currently only expose overloads that operate on pointers.

This is likely an API that could be exposed in a platform agnostic manner via something like `System.Numerics.BitOperations` or under `System.Math`. Those overloads would themselves likely take `ref` or `out`.

**Comment by tannergooding** [comment]
In either case; proposals for new public APIs should be made against dotnet/corefx and follow the API review process: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md#steps. They should also likely follow the "good template" example given under step 1 at the given URL.

https://github.com/dotnet/coreclr/issues/22343 is sufficient to track the prototyping of `AddWithCarry` for internal use in CoreCLR.
