### ISSUE TITLE
Enable Tests for Ubuntu in CoreCLR

### ISSUE THREAD

**Issue by schellap** [dotnet/coreclr#2399]
@adityamandaleeka, as we want to run CoreCLR tests in CoreRT repo's Ubuntu builds, we would like CoreCLR to first run tests on Ubuntu as well in the CI.

/Cc @gkhanna79

**Comment by adityamandaleeka** [comment]
@schellap I might be misunderstanding what this issue is about, but the CoreCLR CI already runs tests on Ubuntu.

**Comment by schellap** [comment]
@gkhanna79, can this be closed? I checked CoreCLR CI that tests are running on Ubuntu, could you let me know why you mentioned there were few email threads about this?

**Comment by schellap** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_ubuntu_tst_prtest/661/console

Tests run on Ubuntu in coreclr so closing this issue.
