### ISSUE TITLE
src\pal\src\arch\i386\context.S missing license header

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#240]

**Comment by jkotas** [comment]
@kangaroo Could you please fix this since you have added the file?

**Comment by kangaroo** [comment]
Fixed in kangaroo/master 874d582 which already has a pending PR for another minor issue here:

https://github.com/dotnet/coreclr/pull/239

I can split them out if its a big deal, but they're both pretty minor changes.

**Comment by jkotas** [comment]
Fixed via #239
