### ISSUE TITLE
Exception thrown 'Unable to find an entry point named 'CopyMemory' in DLL 'kernel32.dll'.' on WPF project with .NET Core 3.0

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/coreclr#24008]
_From @Ebenezer94 on Monday, 15 April 2019 17:50:37_

We have used the CopyMemory method in our project to copies memory from source to destination. While copying, exception thrown like "'Unable to find an entry point named 'CopyMemory' in DLL 'kernel32.dll'.'". This code works fine in WPF with .NET Framework. But, we are facing an issue in WPF with .NET Core. I have added the simple code snippet to reproduce the issue in WPF with .NETCore. The simple sample can be download from below link,

.NET Core3.0

http://www.syncfusion.com/downloads/support/directtrac/general/ze/NETCOR~1263359629.zip

.NET Framework

http://www.syncfusion.com/downloads/support/directtrac/general/ze/CopyMemory_NetFramework542091517.zip

Code snippet :

```
[DllImport("kernel32.dll", EntryPoint = "CopyMemory", SetLastError = false)]
public static extern void CopyMemory(IntPtr dest, IntPtr src, uint count);
public MainWindow()
{
    const int size = 200;
    IntPtr memorySource = Marshal.AllocHGlobal(size);
    Marshal.WriteInt32(memorySource, 35);
    IntPtr memoryTarget = Marshal.AllocHGlobal(size);
    CopyMemory(memoryTarget, memorySource, size);
    bool val = Marshal.ReadInt32(memoryTarget) == 35;
}
```

Please find the required configuration below.

.NET Framework                                 : 4.6
.NET Core                                           : 3.0
Operating System                              : Windows 10
Preferred Programming Language    : C#
Visual Studio                                      : Visual Studio 2017

_Copied from original issue: dotnet/wpf#586_

**Comment by vatsan-madhavan** [comment]
_From @vatsan-madhavan on Monday, 15 April 2019 19:44:57_

This doesn't seem specific to WPF. Happens in a general .NET Core application as well. 

```C#
using System;
using System.Runtime.InteropServices;

namespace test1
{
    class Program
    {
        static void Main(string[] args)
        {
            bool val = false;
            
            try
            {
                const int size = 200;
                IntPtr memorySource = Marshal.AllocHGlobal(size);
                Marshal.WriteInt32(memorySource, 35);
                IntPtr memoryTarget = Marshal.AllocHGlobal(size);
                CopyMemory(memoryTarget, memorySource, size);
                val = Marshal.ReadInt32(memoryTarget) == 35;
            }
            catch(EntryPointNotFoundException e)
            {
                Console.WriteLine(e.ToString());
            }
            
            
            Console.WriteLine($"Successfully read from CopyMemory ? : {val}");
        }
        
        [DllImport("kernel32.dll", EntryPoint = "CopyMemory", SetLastError = false)]
        public static extern void CopyMemory(IntPtr dest, IntPtr src, uint count);

    }
}
```

```
\test1>bin\Debug\netcoreapp3.0\test1.exe
System.EntryPointNotFoundException: Unable to find an entry point named 'CopyMemory' in DLL 'kernel32.dll'.
   at test1.Program.CopyMemory(IntPtr dest, IntPtr src, UInt32 count)
   at test1.Program.Main(String[] args) in D:\Temp\netcore\test1\Program.cs:line 18
Successfully read from CopyMemory ? : False

\test1>bin\Debug\net472\test1.exe
Successfully read from CopyMemory ? : True
```

@AaronRobinsonMSFT, should be this be moved to coreclr?

**Comment by vatsan-madhavan** [comment]
_From @AaronRobinsonMSFT on Monday, 15 April 2019 20:51:42_

@vatsan-madhavan This is failing for an absolutely insane reason. There are no words for the nonsense.. Feel free to push this issue over to CoreCLR and mark it as 3.0.

cc @jeffschwMSFT

**Comment by vatsan-madhavan** [comment]
_From @AaronRobinsonMSFT on Monday, 15 April 2019 22:00:59_

I didn't realize this was just reported via WPF.

@Ebenezer94 In .NET Framework there was a special case for a few function names and `CopyMemory` happened to be one of them. The special case was removed in .NET Core. In order to address this in your code, please update the attribute to include the following: `[DllImport EntryPoint="RtlMoveMemory"]`. If the `EntryPoint` property is set as above, the P/Invoke will work in both .NET Framework and .NET Core.

**Comment by AaronRobinsonMSFT** [comment]
@Ebenezer94 As an FYI, there were a few special cased P/Invoke names in .NET Framework: `MoveMemory`, `CopyMemory`, `FillMemory`, and `ZeroMemory`. All of these will work when pointing at `kernel32` on .NET Framework, but will fail on .NET Core. Please use the `EntryPoint` property in the `DllImport` attribute to get the desired behavior. The proper export names can be found using `dumpbin /exports kernel32.dll` from a Visual Studio command prompt.

**Comment by vatsan-madhavan** [comment]
BTW, @AaronRobinsonMSFT asked me offline whether this affects the WPF codebase itself. The answer is no. We looked through the P/Invokes in the codebase, and found that the P/Invoke for `MoveMemory` in the WPF codebase explicitly specifies an entrypoint (`RtlMoveMemory`).
