### ISSUE TITLE
DIM allows interfaces to be expanded, reevaluate variance restrictions?

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/coreclr#24033]
I'm under the impression one of the reasons for disallowing variance on class type arguments was that implementers could easily shoot their future selves in the foot if they didn't judiciously add variance markers to type arguments. 

As variance limits the positions that a type argument can appear in you might not foresee that you'd want to use a type argument in opposite position in new methods you add later on.

Now that DIM would open up that possibility for interfaces too is it worth re-examining variance restrictions?

**Comment by jkotas** [comment]
cc @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
Classes are still quite different from interfaces that have instance methods, because classes have state.

Quick search for "class covariant Lippert" didn't disappoint: https://stackoverflow.com/questions/2733346/why-isnt-there-generic-variance-for-classes-in-c-sharp-4-0/2734070#2734070

**Comment by NinoFloris** [comment]
The problem here is mutability, covariance is never safe if allowed near mutable constructs. 

State isn't so important, interfaces can expose methods that allow you to mutate that state too so I wouldn't say that to be the defining argument.

**Comment by NinoFloris** [comment]
To add, covariance would be great for Task<T>, all [ImmutableCollections](https://github.com/dotnet/corefx/issues/35892) and more of these Immutable types that would benefit tremendously from it too!

**Comment by MichalStrehovsky** [comment]
DIMs didn't make implementing this any easier/cleaner.

The only way we would implement this if this came as a feature request from the C# language team (e.g. same way the C# team requested the default interface methods). Working on a runtime feature that won't be exposed from C# is not worth the effort. The C# team made a decision on this in the past: dotnet/roslyn#171. To get any traction on this, you need to build a case for this in the dotnet/csharplang repo.
