### ISSUE TITLE
x86 legacy backend unexpected output

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2406]
x86 LEGACY_BACKEND failure

unexpected output received.

May or may not be the same errors.
To Repro.

\GC\Features\HeapExpansion\Finalizer\Finalizer.cmd
\JIT\Directed\PREFIX\unaligned\1\arglist\arglist.cmd
\JIT\Directed\PREFIX\unaligned\2\arglist\arglist.cmd
\JIT\Directed\PREFIX\unaligned\4\arglist\arglist.cmd
\JIT\Directed\PREFIX\volatile\1\arglist\arglist.cmd
\JIT\Methodical\doublearray\dblarray4_cs_d\dblarray4_cs_d.cmd
\JIT\Methodical\doublearray\dblarray4_cs_do\dblarray4_cs_do.cmd
\JIT\Methodical\doublearray\dblarray4_cs_r\dblarray4_cs_r.cmd
\JIT\Methodical\doublearray\dblarray4_cs_ro\dblarray4_cs_ro.cmd
\JIT\Methodical\ELEMENT_TYPE_IU\_il_dbgsizeof\_il_dbgsizeof.cmd
\JIT\Methodical\ELEMENT_TYPE_IU\_il_relsizeof\_il_relsizeof.cmd
\JIT\Methodical\xxobj\sizeof\_il_dbgsizeof\_il_dbgsizeof.cmd
\JIT\Methodical\xxobj\sizeof\_il_dbgsizeof32\_il_dbgsizeof32.cmd
\JIT\Methodical\xxobj\sizeof\_il_dbgsizeof64\_il_dbgsizeof64.cmd
\JIT\Methodical\xxobj\sizeof\_il_relsizeof\_il_relsizeof.cmd
\JIT\Methodical\xxobj\sizeof\_il_relsizeof32\_il_relsizeof32.cmd
\JIT\Methodical\xxobj\sizeof\_il_relsizeof64\_il_relsizeof64.cmd
\JIT\opt\perf\doublealign\Locals\Locals.cmd
\JIT\Regression\Dev11\External\dev11_239804\ShowLocallocAlignment\ShowLocallocAlignment.cmd
\JIT\SIMD\CircleInConvex\CircleInConvex.cmd
\JIT\Regression\CLR-x86-JIT\V1.2-Beta1\b103058\b103058\b103058.cmd
\JIT\Directed\lifetime\lifetime2\lifetime2.cmd
\JIT\Regression\CLR-x86-JIT\V1-M09\b16102\b16102\b16102.cmd

**Comment by BruceForstall** [comment]
The 'arglist' tests fail because they use varargs, which is not supported in .NET Core.

The only other test failure is:
JIT\Regression\Dev11\External\dev11_239804\ShowLocallocAlignment\ShowLocallocAlignment.cmd

**Comment by BruceForstall** [comment]
ShowLocallocAlignment covered by #7163

**Comment by BruceForstall** [comment]
This bug is no longer needed
