### ISSUE TITLE
GetDirectoryName : different behavior in windows or linux

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/coreclr#24084]
Steps:
1. dotnet new console -o dirpath
2. change Program.cs to 

```csharp
using System;

namespace dirpath
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(System.IO.Path.GetDirectoryName("//a/b/c/bin/d/d.e/NS/b.c.f.g.dll"));
            Console.WriteLine(System.IO.Path.GetDirectoryName(@"\\a\b\c\bin\d\d.e\NS\b.c.f.g.dll"));
            Console.WriteLine("Hello World!");
        }
    }
}

```

Output on windows:
```cmd
XX>y\dotnet-sdk-2.2.202-win-x64\dotnet.exe run
\\a\b\c\bin\d\d.e\NS
\\a\b\c\bin\d\d.e\NS
Hello World!
XX>
```

Output on Linux:
```bash
testadm@asdi1-1:~/dirpath$ dotnet run
/a/b/c/bin/d/d.e/NS

Hello World!
```

Problem: 
`Console.WriteLine(System.IO.Path.GetDirectoryName(@"\\a\b\c\bin\d\d.e\NS\b.c.f.g.dll"));` gives no output on Linux.

Expected:
Behavior on windows and Linux is same.

Real world use case:
To get the path of executing assembly, `assemnly.codebase` is [recommended](https://stackoverflow.com/questions/52797/how-do-i-get-the-path-of-the-assembly-the-code-is-in).
In below code on `Linux`, variable `path` is in `\\a\b\c\a.dll` format.
```cs
            var path = new System.Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath;
            var dirPath = Path.GetDirectoryName(path); // empty on Linux and right on windows.
```

**Comment by stephentoub** [comment]
`\` is not a directory separator on Linux. It's a valid filename character.

**Comment by danmosemsft** [comment]
@ashishnegi  as above this is by design. I'm going to close but feel free to reopen if you have other questions, etc.

**Comment by ashishnegi** [comment]
@danmosemsft Should `new System.Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath`  give path with name-separator character as `/` and not `\` ?

The path returned by above code is not usable in linux as `\` is treated not as name-separator-char but as part of file-name.

**Comment by stephentoub** [comment]
> Should new System.Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath give path with name-separator character as / and not \ ?

Can you open a separate issue for that?  That question is about Uri.LocalPath forcing `\` on all operating systems; a fine question, but a different issue from GetDirectoryName.  Thanks.

**Comment by ashishnegi** [comment]
Opened #24117.
