### ISSUE TITLE
Error: Failed to restore the optimization data package

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#24083]
failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_scenarios_Windows_NT_x64_min_opt_ryujit/1207/

failed log:
C:\J\w\perf_scenario---af7a1e00\packages\microsoft.dotnet.buildtools\3.0.0-preview4-03913-01\lib\tool-runtime\project.csproj : error NU3004: Package 'System.Collections.Immutable 1.3.1' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
  Installing Newtonsoft.Json 10.0.3.
  Installing NETStandard.Library 2.0.0.
C:\J\w\perf_scenario---af7a1e00\packages\microsoft.dotnet.buildtools\3.0.0-preview4-03913-01\lib\tool-runtime\project.csproj : error NU3004: Package 'System.Net.NameResolution 4.3.0' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
C:\J\w\perf_scenario---af7a1e00\packages\microsoft.dotnet.buildtools\3.0.0-preview4-03913-01\lib\tool-runtime\project.csproj : error NU3004: Package 'Microsoft.NETCore.DotNetHostPolicy 2.0.0' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
C:\J\w\perf_scenario---af7a1e00\packages\microsoft.dotnet.buildtools\3.0.0-preview4-03913-01\lib\tool-runtime\project.csproj : error NU3004: Package 'Newtonsoft.Json 10.0.3' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
C:\J\w\perf_scenario---af7a1e00\packages\microsoft.dotnet.buildtools\3.0.0-preview4-03913-01\lib\tool-runtime\project.csproj : error NU3004: Package 'NETStandard.Library 2.0.0' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
  Restore failed in 27.81 sec for C:\J\w\perf_scenario---af7a1e00\packages\microsoft.dotnet.buildtools\3.0.0-preview4-03913-01\lib\tool-runtime\project.csproj.

C:\J\w\perf_scenario---af7a1e00>set RESTORE_ERROR_LEVEL=1 
ERROR: An error occured when running: '"C:\J\w\perf_scenario---af7a1e00\.dotnet\dotnet.exe" restore "C:\J\w\perf_scenario---af7a1e00\packages\microsoft.dotnet.buildtools\3.0.0-preview4-03913-01\lib\\tool-runtime\project.csproj" --no-cache --packages "C:\J\w\perf_scenario---af7a1e00\packages" --source https://dotnet.myget.org/F/roslyn/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://api.nuget.org/v3/index.json  --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnetfeed.blob.core.windows.net/dotnet-coreclr/index.json'. Please check above for more details.
BUILD: Error: Failed to restore the optimization data package.
Build step 'Execute Windows batch command' marked build as failure

**Comment by RussKeldorph** [comment]
This jobs are obsolete and removed.

**Comment by janvorli** [comment]
This keeps happening quite often both in the CI and on my local machine. See the `Test Pri0 Windows_NT arm checked Job` leg in https://dev.azure.com/dnceng/public/_build/results?buildId=170454 from today.

**Comment by RussKeldorph** [comment]
@janvorli  Apologies.  I thought this was specific to the perf jobs.  I believe this is dotnet/core-eng#6160.

@brianrob Are you aware of an investigation into this (given its association with opt data)?

**Comment by brianrob** [comment]
I'm not.  I glanced at the notes in https://github.com/dotnet/core-eng/issues/6160 but I didn't see anything specific to optimization data.  Did I just miss it?

I can say that we're seeing something similiar in optimization training jobs as well - it happens during builds of CoreCLR, so it could definitely be the same issue.

**Comment by RussKeldorph** [comment]
@brianrob I've seen it a couple more times this week and both times it hit during the optimization package restore.  That may just be because the optimization package is earlier in the restore process(?).  Again, I think this is more likely just a feed outtage, but I thought you might have heard of something.  I'm going to take this up in dotnet/core-eng#6160.

**Comment by RussKeldorph** [comment]
Re-opening since we can fix by updating the SDK per dotnet/core-eng#6160.
