### ISSUE TITLE
error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

### ISSUE THREAD

**Issue by IgorXq** [dotnet/coreclr#24086]
Cannot get rid of  weird error

>  error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

when I build the project with CLI  **dotnet build**  

Had to uninstall all related .Net stuff (all SDKs, .Net runtimes and VS2017 )  then reinstalled VS2019 Community from scratch. The issue is still the same - I am able to build and run the application with VS but can **not** build  or run any of existing proejcts from CLI. 
It still fails with mentioned error.

It is not obvious what version of SDK it complains for, I try to install consecutively all SDKs from Microsoft "downloads" page but nothing helps.

Currently 
**dotnet --list-sdks**

produces the output:

> 2.1.602 [C:\Program Files\dotnet\sdk]
> 2.2.105 [C:\Program Files\dotnet\sdk]
> 2.2.106 [C:\Program Files\dotnet\sdk]
> 2.2.202 [C:\Program Files\dotnet\sdk]
> 2.2.203 [C:\Program Files\dotnet\sdk]

I have checked several related issues here but all of them have been closed and none of them proposes  relevant solution.

**Comment by RussKeldorph** [comment]
@IgorXq Have you tried asking in the https://github.com/dotnet/cli or https://github.com/dotnet/core-sdk repos?  I would try them first.

**Comment by IgorXq** [comment]
@RussKeldorph Thank you, published the issus in CLI repo.

https://github.com/dotnet/cli/issues/11206#
