### ISSUE TITLE
Question - string pool

### ISSUE THREAD

**Issue by Korporal** [dotnet/coreclr#24097]
This may not be the correct place for my question, if so just let me know.

I'm interested in programmatically opening an assembly DLL file and then getting at every string constant that is present.

Is there a way to get at this data? I'd expect to see an array or sequence of string values, I do not care where these were declared/defined, seeing all strings as a simple sequence/arrays is all I need.

Thanks

**Comment by sdmaclea** [comment]
I do not think the runtime exposes this functionality directly.

Running `ildasm` would make the strings obvious.

**Comment by jkotas** [comment]
https://www.nuget.org/packages/System.Reflection.Metadata/ package provides low-level metadata access. You should be able to get to all strings in the assembly using this library, e.g. take a look at `public static System.Reflection.Metadata.UserStringHandle MetadataReaderExtensions.GetNextHandle (this System.Reflection.Metadata.MetadataReader reader, System.Reflection.Metadata.UserStringHandle handle)` method.
