### ISSUE TITLE
Remove SOS and lldb plugin from the coreclr repo

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#24092]
SOS and the lldb plugin now live in the [diagnostics](https://github.com/dotnet/diagnostics.git) repo.  We are almost ready to remove them from the coreclr repo probably in the Preview 6 time frame.

We are still waiting for the new SOS to shipping with the next public release of the Windows debugger (windbg) and there are still some OS/architecture holes in the diagnostics repo's build (and test) matrix (i.e. arm, arm64, FreeBSD, etc.).

**Comment by cup** [comment]
https://github.com/dotnet/coreclr/issues/24092
https://github.com/dotnet/coreclr/issues/24397
https://github.com/mono/linker/issues/607

**Comment by stephentoub** [comment]
> @tommcdon removed this from the 3.0 milestone

Does this mean an SOS built out of the coreclr repo is going to ship in 3.0? If so, I want to port from the diagnostics repo some changes that were made only there when it was stated that SOS would not ship out of dotnet/coreclr in 3.0.

**Comment by mikem8361** [comment]
I still won't bother with merging the changes into coreclr.  The diagnostics repo SOS has a lot of new features and fixes that coreclr doesn't.  

I need to discuss this with Tom, but I still do want to remove SOS from coreclr in the Preview 7 timeframe otherwise it will probably ship with 3.0.

**Comment by mikem8361** [comment]
Diagnostics repo SOS release criteria (ready to remove from the runtime/coreclr repo)
- [x] All SOS commands ported and working in diagnostics repo
- [x] Windows x64, x86 and arm supported and tested
- [x] Linux x64 supported and tested
- [ ] Linux arm and arm64 supported and tested
- [x] Linux MUSL based distros (i.e. Alpine) supported
- [x] Windows SOS published in the internal extension gallery 
- [ ] Windows SOS shipped with the latest public/external Windows debugger release
- [x] Out of band SOS installation for Linux and macOS (dotnet-sos) finished

**Comment by tommcdon** [comment]
@mikem8361 I've moved the issue back to 3.0.  Thanks for putting together the release checklist!
