### ISSUE TITLE
x86 legacy backend Assertion failure Unhandled Exception: System.InvalidOperationException: Cannot call Set on a null context

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2410]
x86 LEGACY_BACKEND failure

Assert Failure: Unhandled Exception: System.InvalidOperationException: Cannot call Set on a null context

To Repro:

Build x86 LEGACY_BACKEND.

\JIT\Methodical\Boxing\misc\_dbgconcurgc_il\_dbgconcurgc_il.cmd
\JIT\Methodical\Boxing\misc\_relconcurgc_il\_relconcurgc_il.cmd

**Comment by BruceForstall** [comment]
Actual tests:

JIT\Methodical\Boxing\misc\_dbgconcurgc_il\_dbgconcurgc_il.cmd
JIT\Methodical\Boxing\misc\_relconcurgc_il\_relconcurgc_il.cmd

**Comment by BruceForstall** [comment]
Tests pass.
