### ISSUE TITLE
 [arm64] Assertion failed: 'comp->featureSIMD'

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24109]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitnosimd_tst/166/

**Failed tests:**
JIT/Regression/JitBlue/DevDiv_714266/DevDiv_714266/DevDiv_714266.sh

**Log:**
```
JIT/Regression/JitBlue/DevDiv_714266/DevDiv_714266/DevDiv_714266.sh [FAIL]
        
        Assert failure(PID 830 [0x0000033e], Thread: 830 [0x033e]): Assertion failed 'comp->featureSIMD' in 'DevDiv_714266:MethodWithManyLiveVectors()' (IL size 200)
```

**Comment by RussKeldorph** [comment]
Fixed by #24071.
