### ISSUE TITLE
Assert failure ... CONTRACT VIOLATION by ThreadExceptionState::GetThrowable

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#2411]
The following tests failed with this failure:

```
Assert failure ... CONTRACT VIOLATION by ThreadExceptionState::GetThrowable 
  at "d:\j\workspace\dotnet_coreclr\debug_windows_nt_prtest\src\vm\exstate.cpp" @ 157
```
- JIT\Methodical\varargs\seh\filter_il_d\filter_il_d.cmd
- JIT\Methodical\varargs\seh\filter_il_r\filter_il_r.cmd

on debug win64.

**Comment by kouvel** [comment]
@LLITCHEV, I have a fix for the assert in the unhandled exception filter (basically disable the assert), but the test is failing after the fix. It looks to me like the IL is trying to catch the DivideByZeroException, but somehow the exception is going unhandled. Could you please take a look?

**Comment by LLITCHEV** [comment]
I will.

**Comment by LLITCHEV** [comment]
Actually, come to think of it, there have been cases in the past that the VM will not propagate the exception to the managed code (just eat it up). Is it possible that this is another instance of this?

**Comment by janvorli** [comment]
@LLITCHEV Please note this isssue is on Windows, not Unix.

**Comment by LLITCHEV** [comment]
I noticed that after I posted the last comment. I think it is still worthed to check if the exception is delivered to the managed frame.

**Comment by kouvel** [comment]
I tried a simple test case with a try/catch, and it catches the exception. Not sure what's different about the IL test.


________________________________

**Comment by janvorli** [comment]
I have enabled logging of exception handling using
```cmd
set COMPlus_LogEnable=1
set COMPlus_LogToConsole=1
set COMPlus_LogFacility=4000
set COMPlus_LogLevel=6
```
From the log, it is obvious that the filter was called and then the catch handler was called as well. But in the handler, the native runtime has thrown an exception in MemberLoader::ThrowMissingMethodException and that one went unhandled.
```
TID 8a7c: StackTraceInfo::ClearStackTrace (000000CA4D526978)
TID 8a7c: ..  considering filter clause [37,51], ControlPc is inside clause (offset 45)
TID 8a7c: ..  clause covers ControlPC
TID 8a7c: ..  calling filter
TID 8a7c: ..    calling handler at 0x00007FF9186404F0, sp = 0x000000CA4D45CAF0
TID 8a7c: EX_THROW Type = 0x45452020 HR = 0x80131513, d:\git\coreclr\src\vm\memberload.cpp line 125
```

**Comment by janvorli** [comment]
Running it under windbg, I can see that the szClassName in the MemberLoader::ThrowMissingMethodException is System.ArgIterator and the szMethod is .ctor.
@LLITCHEV isn't this another test that should have been disabled due to the usage of the unsupported arg iterator?

**Comment by LLITCHEV** [comment]
@janvorli @jkotas My understanding is that on Windows when using the non-portable profile the varargs should work properly. At least the Jit for CoreCLR is accepting IL with varargs and many vararg tests that are excluded on *nix are passing on Windows. JanK, could you please confirm that understanding is correct?
With that said, it clearly looks like this test uses managed classes/methods that are not present in the mscorlib.dll on CoreCLR, so it should be disabled/excluded from the runs. I would just exclude it right now, so it doesn't fail or remove it permanently if that functionality is not supported on CoreCLR, based on JanK's answer.

**Comment by jkotas** [comment]
> on Windows when using the non-portable profile the varargs should work properly

Correct.

> it clearly looks like this test uses managed classes/methods that are not present in the mscorlib.dll 

What methods are you talking about? I do not see any.

**Comment by janvorli** [comment]
@jkotas System.ArgIterator..ctor

**Comment by jkotas** [comment]
I see, I have not realized that ArgIterator ctor is not in mscorlib ... this test should be deleted then.

**Comment by jkotas** [comment]
There are a few other tests that are using ArgIterator as well. We should delete/cleanup those as well.

**Comment by janvorli** [comment]
I've inspected the mscorlib.dll and it actually does contain the ArgIterator ctor, but it is internal.

**Comment by LLITCHEV** [comment]
I got behind my computer again and double checked to see what I was seeing earlier was right...
Here is what I see in the source as constructors...
File: 
        <git repo>\\src\mscorlib\src\System\ArgIterator.cs

Constructors for ArgIterator:
        [System.Security.SecuritySafeCritical]  // auto-generated
        public ArgIterator(RuntimeArgumentHandle arglist) : this(arglist.Value)

        [System.Security.SecurityCritical]  // auto-generated
        [MethodImplAttribute(MethodImplOptions.InternalCall)]

        private unsafe extern ArgIterator(IntPtr arglist, void *ptr);

        public unsafe ArgIterator(RuntimeArgumentHandle arglist, void* ptr) : this(arglist.Value, ptr)
        {
        }

In the mscorlib.dll I see only 2 of the constructors (the second and the third). Shall we add also the first one for completeness for the Windows non-portable profile. And the test will work there too. I wonder what is compiling it out...

**Comment by jkotas** [comment]
> we add also the first one for completeness for the Windows non-portable profile

We should not be doing any additions to the non-portable profile.

> I wonder what is compiling it out...

The BCL rewriter tool.

**Comment by LLITCHEV** [comment]
@jkotas Thanks! So it looks like these are bad tests then.

**Comment by LLITCHEV** [comment]
@richardlford Please remove all the tests that use ArgIterator since it is not available on CorCLR.

**Comment by LLITCHEV** [comment]
@richardlford I think these tests should still be enabled for the non CoreCLR products.

**Comment by jkotas** [comment]
> @richardlford I think these tests should still be enabled for the non CoreCLR products.

**Comment by jkotas** [comment]
> @richardlford I think these tests should still be enabled for the non CoreCLR products.

This means that these tests should stay in the internal full .NET Framework test suite, but they can still be deleted on GitHub. We do not want to have the full .NET Framework-specific tests in CoreCLR repo.

**Comment by BruceForstall** [comment]
The varargs tests were removed with 0a427c6d6d87e69ce0f87dafd2f965ee989e6d29
