### ISSUE TITLE
AccessViolationException in .NET Core 3.0 Preview 4

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [dotnet/coreclr#24114]
I'm using [scriban](https://github.com/lunet-io/scriban) in one of my projects. When switching to .NET Core 3.0 Preview 4, unit tests started to crash in release mode with an `ExecutionEngineException` (see lunet-io/scriban#163). I narrowed this down to the following, minimal code example which will run fine in debug mode, but throw an `AccessViolationException` in release mode (on both linux-x64 and win10-x64):

```
using System;

namespace ConsoleApp1
{
    class Program
    {

        static void Main(string[] args)
        {
            var options = LexerOptions.Default;
        }

    }

    public struct LexerOptions
    {

        public static readonly LexerOptions Default = new LexerOptions()
        {

        };

    }

}
```

Sample project: [coreclr-24114.zip](https://genes.pics/s/G6Sde2LWscKr5Rm)

**Environment**

> .NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

> Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\

> Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

> .NET Core SDKs installed:
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]

> .NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by EgorBo** [comment]
3.0.100-preview4-010961: doesn't reproduce.
3.0.100-preview5-011468: reproduces.

**Comment by jkotas** [comment]
Crash in the JIT:

```
(45d4.4840): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
clrjit!GenTreeStmt::getNextStmt:
00007ffc`26ce634c 488b4120        mov     rax,qword ptr [rcx+20h] ds:00000000`00000020=????????????????
0:000> k
 # Child-SP          RetAddr           Call Site
00 000000ab`d758c918 00007ffc`26c8c897 clrjit!GenTreeStmt::getNextStmt [f:\workspace\_work\1\s\src\jit\gentree.h @ 4906] 
01 000000ab`d758c920 00007ffc`26cdf8b9 clrjit!Compiler::impGetStructAddr+0x87 [f:\workspace\_work\1\s\src\jit\importer.cpp @ 1479] 
02 000000ab`d758c970 00007ffc`26cdb9d8 clrjit!Compiler::impImportBlockCode+0x2dd9 [f:\workspace\_work\1\s\src\jit\importer.cpp @ 12939] 
03 000000ab`d758d590 00007ffc`26cdb863 clrjit!Compiler::impImportBlock+0x108 [f:\workspace\_work\1\s\src\jit\importer.cpp @ 16903] 
04 000000ab`d758d680 00007ffc`26cd9a89 clrjit!Compiler::impImport+0x7e3 [f:\workspace\_work\1\s\src\jit\importer.cpp @ 17974] 
05 (Inline Function) --------`-------- clrjit!Compiler::fgImport+0xf [f:\workspace\_work\1\s\src\jit\flowgraph.cpp @ 6818] 
06 000000ab`d758d6d0 00007ffc`26cd49bf clrjit!Compiler::compCompile+0xb9 [f:\workspace\_work\1\s\src\jit\compiler.cpp @ 4366] 
07 000000ab`d758d820 00007ffc`26cc2ec4 clrjit!Compiler::compCompileHelper+0x39f [f:\workspace\_work\1\s\src\jit\compiler.cpp @ 6015] 
08 000000ab`d758d8d0 00007ffc`26cc41d4 clrjit!Compiler::compCompile+0x414 [f:\workspace\_work\1\s\src\jit\compiler.cpp @ 5360] 
09 000000ab`d758d970 00007ffc`26d0de52 clrjit!jitNativeCode+0x250 [f:\workspace\_work\1\s\src\jit\compiler.cpp @ 6643] 
0a 000000ab`d758db20 00007ffc`1e3cf675 clrjit!CILJit::compileMethod+0x92 [f:\workspace\_work\1\s\src\jit\ee_il_dll.cpp @ 332] 
```

cc @RussKeldorph @dotnet/jit-contrib

**Comment by AlgorithmsAreCool** [comment]
@sandreenko did this fix make it into Preview 5?

I seem to be hitting it or something similar in the new release with scriban.

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23
```

**Comment by jkotas** [comment]
@AlgorithmsAreCool This fix is in preview5. Could you please open a new issue on the crash that you are hitting?

**Comment by AlgorithmsAreCool** [comment]
Sure, i'll work on a minimal repo
