### ISSUE TITLE
x86 legacy backend Assertion failed 'spill->spillVarDsc'

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2412]
x86 LEGACY_BACKEND failure

Assertion failed 'spill->spillVarDsc'

To Repro:

build x86 LEGACY_BACKEND

\JIT\Methodical\divrem\rem\u8rem_cs_do\u8rem_cs_do.cmd
\JIT\Methodical\divrem\rem\u8rem_cs_ro\u8rem_cs_ro.cmd

**Comment by BruceForstall** [comment]
Dup of #12467
