### ISSUE TITLE
x86 legacy backend Assertion failed '!Mapped(uEntry)'

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2413]
x86 LEGACY_BACKEND failure

Assertion failed '!Mapped(uEntry)'

To Repro:

build x86 LEGACY_BACKEND

JIT\Methodical\divrem\div\u8div_cs_do\u8div_cs_do.cmd
\JIT\Methodical\divrem\div\u8div_cs_ro\u8div_cs_ro.cmd

**Comment by BruceForstall** [comment]
Dup of #12469
