### ISSUE TITLE
x86 legacy backend Assertion failed 'genActualType(op1->TypeGet()...

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2415]
x86 LEGACY_BACKEND failure

Assertion failed 'genActualType(op1->TypeGet()) == genActualType(op2->TypeGet()) || varTypeIsI(op1->TypeGet()) && varTypeIsI(op2->TypeGet()) || varTypeIsFloating(op1->gtType) && varTypeIsFloating(op2->gtType)

To Repro:

build x86 LEGACY_BACKEND

\JIT\Methodical\ELEMENT_TYPE_IU\_il_dbgi_array_merge\_il_dbgi_array_merge.cmd
\JIT\Methodical\ELEMENT_TYPE_IU\_il_dbgu_array_merge\_il_dbgu_array_merge.cmd
\JIT\Methodical\ELEMENT_TYPE_IU\_il_reli_array_merge\_il_reli_array_merge.cmd
\JIT\Methodical\ELEMENT_TYPE_IU\_il_relu_array_merge\_il_relu_array_merge.cmd

**Comment by BruceForstall** [comment]
These all pass.
