### ISSUE TITLE
Investigate x86 requirement for "this" ptr in register

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#24166]
In https://github.com/dotnet/coreclr/pull/24043 I did some clean up of the weird semantics of `RequiresRegister()`, changing non-`ActualRef` `RefPosition`s to be marked `RegOptional`.
This changed the behavior under stress  (specifically jitStressRegs 0x1000, which is the regOptionalNoAlloc). `RefTypeParamDef`s aren't considered "ActualRefs" but previously weren't marked `RegOptional`. However, the x86 gc encoding doesn't seem to expect the 'this' ptr not to get a register (it can be spilled, but there's a dependency somewhere on it getting an initial register assignment).
Investigate this, and determine whether it's a fundamental requirement that should be explicitly specified in the register allocator. (As it is, it will always get a register, since it occupies one to begin with, and therefore has at least that register available to it.)

**Comment by AndyAyersMS** [comment]
@CarolEidt is this a 3.0 issue... guessing not.

**Comment by CarolEidt** [comment]
Yes, sorry. I should have marked it as "future".
