### ISSUE TITLE
Feature Request: A mechanism for unloading and reloading unmanaged libraries while using P/Invoke

### ISSUE THREAD

**Issue by hez2010** [dotnet/coreclr#24165]
Currently there's no way to unload unmanaged dynamic libraries while using P/Invoke.  

Sometimes we need to hot-upgrade without restarting host process, absolutely that we can use LoadLibrary/FreeLibrary to achieve that but it's really inconvenient, and also we cannot invoke methods in dll directly by calling their method names/ordinals.  

So I think it is necessary to provide a mechanism for unloading/reloading dlls while using P/Invoke.

**Comment by RussKeldorph** [comment]
@janvorli

**Comment by AaronRobinsonMSFT** [comment]
This isn't something we are likely to change via the `DllImport` approach. There are several reasons, but mostly it will lead to invalid P/Invoke stubs that could result in unsafe execution if the associated native library is unloaded.

>absolutely that we can use LoadLibrary/FreeLibrary to achieve that but it's really inconvenient, and also we cannot invoke methods in dll directly by calling their method names/ordinals.

Agreed. The proposed [C# function pointer](https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md) feature along with the [`NativeLibrary`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.nativelibrary) should make much of this less onerous.
