### ISSUE TITLE
Tests fail with unhandled null reference

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#2416]
The following tests fail (on debug win64 job) with unhandled null reference exception.

```
JIT\Directed\coverage\importer\Desktop\ldelemnullarr1_il_d\ldelemnullarr1_il_d.cmd
JIT\Directed\coverage\importer\Desktop\ldelemnullarr1_il_r\ldelemnullarr1_il_r.cmd
JIT\Directed\coverage\importer\Desktop\nonrefsdarr_il_d\nonrefsdarr_il_d.cmd
JIT\Directed\coverage\importer\Desktop\nonrefsdarr_il_r\nonrefsdarr_il_r.cmd
```

**Comment by sivarv** [comment]
These tests are expected to produce NullReferenceException (Verified both on Desktop and CoreCLR).  Looks like we are missing something while porting these tests from Desktop.  On Desktop I see there are some pre-command and post-command executed.  We need to understand how this test is getting executed/run on desktop and if it applies to CoreCLR see how best to adopt for CoreCLR purpose.

Marking it as test-issue.

**Comment by jashook** [comment]
These tests force the verifier to run in desktop and expect a verification exception to pass. They are probably useful tests, but need to be converted to force verification in a different way for coreclr. Unknown if this is important enough to do before rtm though @RussKeldorph opinions?

**Comment by RussKeldorph** [comment]
@jashook Add these tests to #4851 and close this as a duplicate.

**Comment by jashook** [comment]
Added
