### ISSUE TITLE
[arm/windows]Test failure: JIT\superpmi\superpmicollect\superpmicollect.cmd

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#24181]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_jitstress2_jitstressregs4_tst/69/

**Failed test:**
JIT_superpmi._superpmicollect_superpmicollect_.JIT\\superpmi\\superpmicollect\\superpmicollect.cmd

**Failed with log:**
```
JIT\superpmi\superpmicollect\superpmicollect.cmd [FAIL]
EXEC : error : replay of final file is not error free [C:\j\workspace\arm_cross_che---a21256ac\tests\runtest.proj]
        
        Return code:      1
```

**Comment by BruceForstall** [comment]
SuperPMI error:
```
MISSING: Method context 19 failed to replay: SuperPMI assertion 'ResolveToken->GetIndex(key) != -1' failed ("Didn't find 2b000326")
```

We should look at the other Windows/arm32 runs to see if it repros.

cc @sandreenko

**Comment by BruceForstall** [comment]
Looks like other non-baseline runs also fail with this, e.g.:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_jitstress1_tiered_flow/42/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_jitstress1_flow/78/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_jitstress2_jitstressregs1_flow/78/

**Comment by RussKeldorph** [comment]
This appears to be passing consistently on `win-arm` for the last couple of months at least.
