### ISSUE TITLE
x86 legacy backend could not load file or assembly

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2418]
x86 LEGACY_BACKEND failure

Could not load file or assembly System...

May or may not be the same errors.
To Repro.

\JIT\Regression\CLR-x86-JIT\V1-M10\b04914\b04914\b04914.cmd
\JIT\Regression\VS-ia64-JIT\V1.2-M02\b108129\b108129\b108129.cmd
\JIT\Regression\CLR-x86-EJIT\V1-M09.5-PDC\b14426\b14426\b14426.cmd
\JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b57367\b57367\b57367.cmd
\JIT\Regression\CLR-x86-JIT\V1-M09\b15307\b15307\b15307.cmd
\JIT\Regression\CLR-x86-JIT\V1-M09\b14585\b14585\b14585.cmd
\JIT\Regression\CLR-x86-JIT\V1-M09\b13621\b13621\b13621.cmd
\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b399444\b399444a\b399444a.cmd

**Comment by BruceForstall** [comment]
These all pass for me
