### ISSUE TITLE
Assertion failed 'result == lateArgs->gtOp.gtOp1'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#24185]
Happens in CI:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstress1/785/consoleText

Doesn't require JitStress. I repro'ed locally (after setup using `run-corefx-tests.py`):
```
f:\gh\coreclr11\_\fx_x86\artifacts\bin\tests\System.Threading.Tasks.Tests\netcoreapp-Windows_NT-Release-x86>RunTests.cmd --runtime-path f:\gh\coreclr11\_\fx_x86\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-x86 --dotnet-root f:\gh\coreclr11\_\fx_x86\.dotnet
----- start 22:50:37.71 ===============  To repro directly: =====================================================
pushd f:\gh\coreclr11\_\fx_x86\artifacts\bin\tests\System.Threading.Tasks.Tests\netcoreapp-Windows_NT-Release-x86\
set COMPlus_TieredCompilation=0
"f:\gh\coreclr11\_\fx_x86\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-x86\dotnet.exe" xunit.console.dll System.Threading.Tasks.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=failing -notrait category=OuterLoop
popd
===========================================================================================================

f:\gh\coreclr11\_\fx_x86\artifacts\bin\tests\System.Threading.Tasks.Tests\netcoreapp-Windows_NT-Release-x86>set COMPlus_TieredCompilation=0

f:\gh\coreclr11\_\fx_x86\artifacts\bin\tests\System.Threading.Tasks.Tests\netcoreapp-Windows_NT-Release-x86>"f:\gh\coreclr11\_\fx_x86\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-x86\dotnet.exe" xunit.console.dll System.Threading.Tasks.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=failing -notrait category=OuterLoop
  Discovering: System.Threading.Tasks.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tasks.Tests (found 539 of 715 test cases)
  Starting:    System.Threading.Tasks.Tests (parallel test collections = on, max threads = 8)
    System.Threading.Tasks.Tests.TaskSchedulerTests.GetTaskSchedulersForDebugger_DebuggerAttached_ReturnsAllSchedulers [SKIP]
      Condition(s) not met: "DebuggerIsAttached"
    System.Threading.Tasks.Tests.TaskSchedulerTests.GetScheduledTasksForDebugger_DebuggerAttached_ReturnsTasksFromCustomSchedulers [SKIP]
      Condition(s) not met: "DebuggerIsAttached"

Assert failure(PID 22808 [0x00005918], Thread: 6384 [0x18f0]): Assertion failed 'result == lateArgs->gtOp.gtOp1' in 'System.Threading.Tasks.Tests.TaskRtTests_Core:RunTaskWaitTest_NegativeTests()' (IL size 667)

    File: f:\gh\coreclr11\src\jit\gentree.cpp Line: 7962
    Image: f:\gh\coreclr11\_\fx_x86\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-x86\dotnet.exe

----- end 22:51:41.72 ----- exit code -1073740286 ----------------------------------------------------------
```

**Comment by BruceForstall** [comment]
Maybe related to https://github.com/dotnet/coreclr/pull/23858?

@sandreenko 
cc @dotnet/jit-contrib

**Comment by sandreenko** [comment]
For such tree:
```
N015 ( 46, 27) [000537] --CXG-------                 \--*  CALL nullcheck int    System.Collections.ObjectModel.ReadOnlyCollection`1[__Canon][System.__Canon].get_Count $de
N013 ( 32, 20) [000536] --CXG------- this in ecx        \--*  CALL nullcheck ref    System.AggregateException.get_InnerExceptions $4db
N011 ( 18, 13) [000535] --CXG------- this in ecx           \--*  CALL help ref    HELPER.CORINFO_HELP_CHKCASTCLASS $1f6
N007 (  3,  2) [000531] ------------ arg1 in edx              +--*  LCL_VAR   ref    V03 loc3         u:2 $4d4
N008 (  1,  4) [000532] -------N---- arg0 in ecx              \--*  CNS_INT(h) int    0xBA80E68 class $15c
```

`optAssertionProp_Call` can replace [000535] with [000531], it will be done with `optAssertionProp_Update` that calls `gtFindLink` 
and updates pointer in [000536] that points to [000535] to [000531].

So after that we will have such tree:
```
N015 ( 46, 27) [000537] --CXG-------                 \--*  CALL nullcheck int    System.Collections.ObjectModel.ReadOnlyCollection`1[__Canon][System.__Canon].get_Count $de
N013 ( 32, 20) [000536] --CXG------- this in ecx        \--*  CALL nullcheck ref    System.AggregateException.get_InnerExceptions $4db
N007 (  3,  2) [000531] ------------ this in edx           \-*  LCL_VAR   ref    V03 loc3         u:2 $4d4
```

but `optAssertionProp_Update` doesn't update `call 000536->fgArgInfo` and it will continue reference [000535] until we finish with the current statement and call re-morph (`fgMorphBlockStmt(block, stmt DEBUGARG("optAssertionPropMain"));`) that recreates `call->fgArgInfo`. So we have an interval between the first call to `optAssertionProp_Update` when the parent is a call until  we remorph the statement. During this interval `call->fgArgInfo` is incorrect. That what we were catching and fixing in `GenTree* Compiler::gtGetThisArg(GenTreeCall* call)` before my change. 

`optAssertionPropagatedCurrentStmt == true` means that a assertion propagation took place and some (which exactly?) links are incorrect and the code under this condition restored the updated value from `call->gtCallLateArgs`.

I do not see a nice solution here, I do not understand why it is x86 specific. I will try to create a small repro to understand it. I am planning to return code 
in `gtGetThisArg` with some additional comments so nobody else would be confused by that block.


Of course, it would be nice to get rid of such logic, for example, `optAssertionProp_Update` calls `gtFindLink` to update the link and inside `gtFindLink` we know the parent of the replaced node if it is a call, we can update the arg table as well. Maybe then we would not need to call `fgMorphBlockStmt(block, stmt DEBUGARG("optAssertionPropMain"));` after each statement. However, this code is so unpredictable that I do not have enough courage to touch it (especially after this regression introduced by my change).

**Comment by mikedn** [comment]
> optAssertionProp_Update doesn't update call 000536->fgarginfo

Sadly the (lack of) updates to `fgArgInfo` have caught people of guard before, it's a ugly area of the IR where a "use" of a node is present in multiple places and needs to be replaced everywhere. There's `GenTreeCall::ReplaceCallOperand` (and `GenTree::ReplaceOperand`) which supposedly do this but I don't know how well it works in this case, last time I checked the main use of these was in LIR, not HIR.

> Of course, it would be nice to get rid of such logic, for example, optAssertionProp_Update calls gtFindLink to update the link and inside gtFindLink we know the parent of the replaced node if it is a call, we can update the arg table as well.

I'm hoping to experiment with the removal of the `fgArgTabEntry` side table soon enough, that would avoid the need for updating it in such cases. Still, re-morphing would probably still be needed to deal with late args.

**Comment by BruceForstall** [comment]
Assuming this is a regression due to https://github.com/dotnet/coreclr/pull/23858, that PR indicates it was a cleanup.

Did it fix any bugs?

If not, it might be appropriate to revert it to fix this regression.

**Comment by sandreenko** [comment]
> Did it fix any bugs?


It was a cleanup. There was a bug with non-unique tree id during this optimization but we have not had an issue for that.

> If not, it might be appropriate to revert it to fix this regression.

I will revert the changed part in `gtGetThisArg(GenTreeCall* call)` and it will fix the regression. I have a repro case now and I need a bit more time to understand why it doesn't repro on x64 before I push the fix.

**Comment by sandreenko** [comment]
An update about x64. For such tree:
```
***** BB05, stmt 19
     ( 52, 37) [000093] ------------              *  STMT      void  (IL 0x02F...0x040)
N018 ( 52, 37) [000092] --CXG-------              \--*  JTRUE     void  
N016 (  1,  1) [000090] ------------                 |  /--*  CNS_INT   int    1 $42
N017 ( 50, 35) [000091] N-CXG--N-U--                 \--*  NE        int    $341
N015 ( 48, 33) [000089] --CXG-------                    \--*  CALL nullcheck int    System.Collections.ObjectModel.ReadOnlyCollection`1[__Canon][System.__Canon].get_Count $2c4
N013 ( 34, 26) [000088] --CXG------- this in rcx           \--*  CALL nullcheck ref    System.AggregateException.get_InnerExceptions $261
N011 ( 20, 19) [000087] --CXG------- this in rcx              \--*  CALL help ref    HELPER.CORINFO_HELP_CHKCASTCLASS $214
N007 (  3,  2) [000083] ------------ arg1 in rdx                 +--*  LCL_VAR   ref    V01 loc0         u:2 $25a
N008 (  3, 10) [000084] -------N---- arg0 in rcx                 \--*  CNS_INT(h) long   0x7ffe742c1b18 class $146
```
when `HELPER.CORINFO_HELP_CHKCASTCLASS` is known to be true we also propagate `LCL_VAR` and get:
```
     ( 52, 37) [000093] ------------              *  STMT      void  (IL 0x02F...0x040)
N018 ( 52, 37) [000092] --CXG-------              \--*  JTRUE     void  
N016 (  1,  1) [000090] ------------                 |  /--*  CNS_INT   int    1 $42
N017 ( 50, 35) [000091] N-CXG--N-U--                 \--*  NE        int    $341
N015 ( 48, 33) [000089] --CXG-------                    \--*  CALL nullcheck int    System.Collections.ObjectModel.ReadOnlyCollection`1[__Canon][System.__Canon].get_Count $2c4
N013 ( 34, 26) [000088] --CXG------- this in rcx           \--*  CALL nullcheck ref    System.AggregateException.get_InnerExceptions $261
N007 (  3,  2) [000083] ------------ this in rcx              \--*  LCL_VAR   ref    V01 loc0         u:2 $25a
```

with incorrect links in `fgArgInfo` for `000088`.

Then we call `optNonNullAssertionProp_Call` for `000088` (as we do on x86) and it calls `gtGetThisArg` that accesses incorrect `fgArgInfo` (returns deleted `000087` instead of `000083`).

Then we skip code under `!FEATURE_FIXED_OUT_ARGS` because it is x64 and return an incorrect value from `gtGetThisArg`. 

https://github.com/dotnet/coreclr/blob/713091f4e504b9a194dcb2cfda180baa21572c58/src/jit/gentree.cpp#L7950-L7969

https://github.com/dotnet/coreclr/blob/713091f4e504b9a194dcb2cfda180baa21572c58/src/jit/assertionprop.cpp#L3654-L3659

In debug, this code now always returns null because I added `DEBUG_DESTROY` call for a replaced node, in release (or in debug before my cleanup) we probably can have a `lcl_var ` that passes this check and leads to using a deleted node for optimization in `optNonNullAssertionProp_Call`. 

So as a summary: the code is not correct for x64/arm and we were unlucky that we had not noticed it before. We need an additional cleaning to delete this difference behavior between x86 and other platforms to make sure that  `optNonNullAssertionProp_Call` doesn't use incorrect nodes.

I will also try to modify my test to show the diff between x86 and x64 (the first will use the correct data and will be able to do an additional VN propagation).

Note: when `optNonNullAssertionProp_Call` uses an outdated tree from `gtGetThisArg` it probably doesn't lead to a bad CodeGen because this tree was a previously correct `this` for the call, it just doesn't use the results of others propagations to do its work better. If we can prove that it is safe to use an outdated tree there we can:
1. delete code under `#if !FEATURE_FIXED_OUT_ARGS` in `gtGetThisArg` to unify all platforms 
2. delete
```
            // Old tree should not be referenced anymore.
            DEBUG_DESTROY_NODE(tree);
```
with a comment that the old tree still can be accessed via `fgArgInfo` and it is expected.

**Comment by sandreenko** [comment]
Yes, for such expr:
```
if (!(e is AggregateException) ||                    
    !((((AggregateException)e).InnerExceptions[0] is ArgumentException) 
    || ((AggregateException)e).InnerExceptions[0] is AggregateException))
```
x86 can get rid of the second null check in `(AggregateException)e).InnerExceptions[0] is AggregateException)` and x64 cannot.

**Comment by CarolEidt** [comment]
> when optNonNullAssertionProp_Call uses an outdated tree from gtGetThisArg it probably doesn't lead to a bad CodeGen because this tree was a previously correct this for the call, it just doesn't use the results of others propagations to do its work better. If we can prove that it is safe to use an outdated tree ...

I think that's a dangerous path to go down. It would be great if we eliminated the need for the `fgArgInfo` to capture the tree node, though I suspect that's going to be quite a long lead-time task. I'm not sure why you wouldn't fix the argInfo, rather than working around this.

**Comment by sandreenko** [comment]
> I'm not sure why you wouldn't fix the argInfo, rather than working around this.

I can fix only `fgArgTabEntry->node` link, not other fields like `numRegs`, `needTmp`, `needPlace`. So I am not sure that it is safe to update only `node` (that we use in `gtGetThisArg`) and leave others outdated, for example morph can skip updating this `fgArgTabEntry` if it sees that `node` is correct (I do not know what it actually does, but I think we can assume worst).

**Comment by CarolEidt** [comment]
I believe that the node is the only thing that can change. Theoretically, I suppose that `needTmp` or `needPlace` could change, but I don't think a legal transformation would cause those to be required when they were not initially. They are added to deal with side-effects and nested calls; if we added those post-morph I think we'd have more problems than updating the arg table. Most of the fields reflect ABI requirements, which can't change when you change the actual node for the argument.

**Comment by sandreenko** [comment]
@CarolEidt thank you! I will try to fix `argInfo` then, especially because x64/arm do not have `call->regArgList` field that was used in this additional search for x86.
