### ISSUE TITLE
x86 legacy backend Unexpected exception thrown

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2419]
x86 LEGACY_BACKEND failure

Unexpected exception thrown

To Repro

\JIT\Methodical\Arrays\misc\_il_dbgarrres\_il_dbgarrres.cmd
\JIT\Methodical\Arrays\misc\_il_relarrres\_il_relarrres.cmd

**Comment by BruceForstall** [comment]
Actual tests:

JIT\Methodical\Arrays\misc\_il_reladdress\_il_reladdress.cmd
JIT\Methodical\Arrays\misc\_il_dbgaddress\_il_dbgaddress.cmd

**Comment by BruceForstall** [comment]
These tests pass for me.
