### ISSUE TITLE
x86 legacy backend Invalid program exception

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2420]
x86 LEGACY_BACKEND failure

Invalid program exception

To Repro:

build x86 LEGACY_BACKEND

\JIT\opt\Tailcall\TailcallVerifyWithPrefix\TailcallVerifyWithPrefix.cmd

**Comment by BruceForstall** [comment]
Test is invalid for x86 legacy backend, and has been disabled.

**Comment by sandreenko** [comment]
Is this test valid for RyuJit? Can be turn it on since legacy has been deleted?

**Comment by BruceForstall** [comment]
Maybe you can enable it and submit a PR, and see how the testing goes?
