### ISSUE TITLE
Test failed: System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24208]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/179/

**Failed tests:**
System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest

**Log:**
```
System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Threading.ThreadPool/tests/ThreadPoolTests.cs(117,0): at System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest()
```

**Comment by stephentoub** [comment]
This is a moment-in-time discrepancy between coreclr and corefx.  We fixed a bug in coreclr, and until corefx ingests a new coreclr and updates the test to match, running a live coreclr against a live corefx will fail.

**Comment by BruceForstall** [comment]
fwiw, fails on other platforms, too: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_minopts/789/#showFailuresLink

**Comment by stephentoub** [comment]
> fails on other platforms, too

Yes, it's not specific to any specific platform.  Argument validation behavior changed.

This should also now be fixed as of https://github.com/dotnet/corefx/pull/37141.
