### ISSUE TITLE
x86 legacy backend System.NotSupportedException: Specified method is not supported

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2421]
x86 LEGACY_BACKEND failure

System.NotSupportedException: Specified method is not supported

To Repro:

build x86 LEGACY_BACKEND

\JIT\Regression\CLR-x86-JIT\V1.2-M02\b20785\b20785\b20785.cmd

**Comment by BruceForstall** [comment]
Test was deleted on 12/23/2015
