### ISSUE TITLE
Satellite Lookup on case sensitive file systems...

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#24211]
@tarekgh Made a request for searching for Satellite Assemblies using case insensitive path search.

Initial prototype of the case insensitive search illustrated the complexity of such an approach.

The prototype case insensitive search code was removed and this issue was opened for the design discussion.

@jkotas made the alternative suggestion that we control the build tooling.  We could simply `lower case` the culture directories....

See discussion which started here https://github.com/dotnet/coreclr/pull/24191#discussion_r277793894

**Comment by tarekgh** [comment]
> @jkotas made the alternative suggestion that we control the build tooling. We could simply lower case the culture directories....

This is reasonable but I would still think in addition to lower cased name we support the official culture name casing too (e..g. CultureInfo.Name, for example en-US) for app compat reasons and also the scenarios people manually create/copy resources.
Our probe will be the exact case then fallback to lower casing. if we do that, we can even not need to do anything in the tools if we decide to and we'll be compatible with the desktop resources too.
