### ISSUE TITLE
Profiler API: Add COR_PRF_MONITOR_LARGEOBJECT_ALLOCATED to complement COR_PRF_MONITOR_OBJECT_ALLOCATED

### ISSUE THREAD

**Issue by mjsabby** [dotnet/coreclr#24217]
When `COR_PRF_MONITOR_OBJECT_ALLOCATED` is enabled, every object allocation is notified to the Profiler API. This can be very expensive in production monitoring.

Adding a `COR_PRF_MONITOR_LARGEOBJECT_ALLOCATED` can enable this only for LOH allocations, which are considerably less in most applications. This can then be enabled in production to track LOH allocations efficiently (when profiler monitoring is enabled for all allocations the slow allocation helpers are used) without resorting to enabling monitoring for ALL object allocations.

**Comment by mjsabby** [comment]
cc @Maoni0 @davmason @noahfalk

**Comment by noahfalk** [comment]
Mukul can you let us know what you get out of being able to only track LOH objects? If @Maoni0 made a change in the future which changed the threshold at which objects qualified as small or large such that object notifications you got in one release were not being delivered in the next release how would your profiler deal with that uncertainty?

**Comment by mjsabby** [comment]
As long as a concept like Large Objects stay in the runtime it'll be a useful concept. If it changes from 85K to 10K, it'll be just as valuable if the same heuristics apply in how LOH impacts the heap (i.e. its performance). Today LOH objects are special in that a lot of LOH allocations impact the performance of an application more adversely than smaller SOH (of course, big caveat .. but on an avergage) and therefore is valuable.

**Comment by noahfalk** [comment]
No objections from me as long as @davmason and @Maoni0 are on-board.

**Comment by davmason** [comment]
I have no objections either. Is there anything else we want to add about large objects as part of this work? Maybe querying for the LOH threshold (it already can be changed with COMPLUS_GCLOHThreshold)

I am not necessarily pushing for any more, just trying to think the scenario through.

**Comment by Maoni0** [comment]
I have no objection.

in 3.0 the LOH threshold is not fixed, it's obtained by `g_pConfig->GetGCLOHThreshold()`.

**Comment by mjsabby** [comment]
Good point. I will incorporate that info.
