### ISSUE TITLE
[arm64] Test failed: JIT/Performance/CodeQuality/BenchmarksGame/mandelbrot/mandelbrot-7/mandelbrot-7.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#24224]
In R2R GCStress=F run:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_r2r_gcstress15_tst/29/consoleFull

Failure has been consistent over several runs, and I can repro it locally.

Possibly related: https://github.com/dotnet/coreclr/issues/23804

```
$ ./mandelbrot-7.sh -coreroot=/home/brucefo/build/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root
BEGIN EXECUTION
in takeLock
/home/brucefo/build/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun mandelbrot-7.exe ''
P4
80 80
                                                                                      /                                            G          @                     7     ?        ?           ?                ?                 ?        ?    7                      @         G                                             /                                    in ReleaseLock
Expected: 100
Actual: 255
END EXECUTION - FAILED
```

**Comment by CarolEidt** [comment]
@BruceForstall - This doesn't repro if I simply set "RunCrossGen" before running the test script. How did you repro this locally? Did you do the entire test run with the crossgen option?

**Comment by BruceForstall** [comment]
I had to crossgen the framework first. So I ran:
```
perl ~/build/coreclr/tests/runtest.py -arch arm64 -build_type Checked -test_location /home/brucefo/build/coreclr/bi
n/tests/Linux.arm64.Checked -core_root /home/brucefo/build/coreclr/bin/tests/Linux.arm64.Checked/Tests/Core_Root --precompile_core_root --limited_core_dumps
```

then cancelled it when it started running tests, then set `RunCrossGen=1`, plus `GCStress=F` and `TieredCompilation=0`, then ran the individual test.

**Comment by CarolEidt** [comment]
Thanks, I am now able to repro this.
