### ISSUE TITLE
x86 legacy backend System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2422]
x86 LEGACY_BACKEND failure

System.ComponentModel.Win32Exception: The system cannot find the file specified

To Repro:

build x86 LEGACY_BACKEND

\JIT\Regression\CLR-x86-JIT\V1.2-Beta1\b101136\b101136\b101136.cmd

**Comment by BruceForstall** [comment]
This test was deleted.
