### ISSUE TITLE
Official build fails restoring IBCMerge package

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#24247]
Restoring packages for F:\workspace\_work\1\s\src\.nuget\optdata\ibcmerge.csproj...
F:\workspace\_work\1\s\src\.nuget\optdata\ibcmerge.csproj : error NU1101: Unable to find package microsoft.dotnet.ibcmerge. No packages exist with this id in source(s): dotnet-core, dotnet-coreclr, myget.org dotnet-core, nuget.org

I suspect this is related to #24205

**Comment by RussKeldorph** [comment]
@jkoritzinsky @brianrob

**Comment by brianrob** [comment]
Looks like things are still failing, now with a 401 (unauthorized) error because the feed requires authentication.

```
Running: dotnet restore src/.nuget/optdata/ibcmerge.csproj --no-cache --packages "F:\workspace\_work\1\s\packages" --source "https://devdiv.pkgs.visualstudio.com/_packaging/dotnet-core-internal-tooling/nuget/v3/index.json"
  Restoring packages for F:\workspace\_work\1\s\src\.nuget\optdata\ibcmerge.csproj...
F:\workspace\_work\1\s\.dotnet\sdk\2.1.503\NuGet.targets(114,5): error : Unable to load the service index for source https://devdiv.pkgs.visualstudio.com/_packaging/dotnet-core-internal-tooling/nuget/v3/index.json. [F:\workspace\_work\1\s\src\.nuget\optdata\ibcmerge.csproj]
F:\workspace\_work\1\s\.dotnet\sdk\2.1.503\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [F:\workspace\_work\1\s\src\.nuget\optdata\ibcmerge.csproj]
Could not find IBCMerge at F:\workspace\_work\1\s\packages\microsoft.dotnet.ibcmerge\5.0.6-beta.19203.1\tools\netcoreapp2.0\ibcmerge.dll
```

@adiaaida do you know what needs to be done to resolve this?

**Comment by adiaaida** [comment]
The official builds used to do this (it's only possible on official builds). I'm pretty sure that the ibcmerge restore will need to happen outside of the build script (hence why it wasn't there in the first place). Let me see how corefx does it.

**Comment by adiaaida** [comment]
Corefx restores it via their tools.csproj: https://github.com/dotnet/corefx/blob/10d7d6f812295a572eb148aedb19efd2f96fbe17/eng/common/internal/Tools.csproj#L11

Package version should be in dependencies.props: https://github.com/dotnet/corefx/blob/eb2d732bf8d35186c70c743812e5d17584b6975f/eng/dependencies.props#L43

**Comment by brianrob** [comment]
Do you know how authentication works?  It looks like the feed is explicitly provided in the CoreFx case as well, but no authentication info, so I suspect credentials are being provided in some other way.

**Comment by mjsabby** [comment]
Is there an ETA for this? Bing is taking near daily bits of the core-setup SDK/runtime packages, but the CoreCLR bits in the SDK/Runtime are now a couple of days old and I need to get fixes for https://github.com/dotnet/coreclr/pull/24235 and https://github.com/dotnet/coreclr/pull/24235.

**Comment by brianrob** [comment]
@jkoritzinsky thanks for fixing this.  I have confirmed via official build that x86 and x64 versions of System.Private.CoreLib have IBC data embedded.
