### ISSUE TITLE
Test failed: System.IO.Tests.CtorTests.NullEncodingThrows

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24265]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_baseline/911/

**Failed tests:**
System.IO.Tests.CtorTests.NullEncodingThrows

**Log:**
```
System.IO.Tests.CtorTests.NullEncodingThrows [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentNullException)
        Actual:   (No exception was thrown)
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/src/System.IO/tests/StreamWriter/StreamWriter.CtorTests.cs(41,0): at System.IO.Tests.CtorTests.NullEncodingThrows()
```

**Comment by BruceForstall** [comment]
This is all platform.

Linux/arm: https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_corefx_baseline_tst/73/consoleFull

**Comment by BruceForstall** [comment]
@stephentoub Do you know if this is another "point in time" failure?

**Comment by stephentoub** [comment]
@BruceForstall, it is, yes, sorry.  It'll be fixed once corefx consumes a new coreclr and we merge https://github.com/dotnet/corefx/pull/36959.

**Comment by BruceForstall** [comment]
@stephentoub fwiw, we now have a way to disable a single corefx test in the "run-corefx-tests.py" harness that we use for almost all of the corefx test runs in the coreclr CI: https://github.com/dotnet/coreclr/blob/master/tests/scripts/run-corefx-tests-exclusions.txt. So, I've excluded this failing test.

I'd love to see us add one of these "corefx_baseline" jobs to coreclr PR testing, but I guess we need to wait for the new AzDO corefx-in-coreclr system.

cc @jkotas
