### ISSUE TITLE
Unexpected error CS0433: Type 'SerializableAttribute' exists in both 

### ISSUE THREAD

**Issue by ddobric** [dotnet/coreclr#24268]
Hi all,

have a project, which references .NET Standard (2.0) library (MyLib), which references Akka.Net. Akka.Net has a library, which provides type '**Serializable**'.

**_MyProject->MyLib->Akka_**

I have a class in my project decorated with **SerializableAttribute**. 

![image](https://user-images.githubusercontent.com/1756871/56785150-227fe900-67f4-11e9-89cc-5982fc7a9b8d.png)

Although there is no **using** pointing to Akka and only explicit reference to 'System.Serialization' is provided,  I get following error:

`error CS0433: The type 'SerializableAttribute' exists in both 'Akka, Version=1.3.12.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

**Comment by jkotas** [comment]
Akka.Net defines these attributes as public, in the System namespace https://github.com/akkadotnet/akka.net/blob/master/src/core/Akka/Util/Internal/NetCorePolyfills.cs

You can workaround this by defining `<Aliases>` for the Akka project: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias

This is really an issue with the Akka library. They should not be defining these polyfills as public to avoid this problem.

**Comment by ddobric** [comment]
I agree. It is definitely an issue of Akka.Net. Using System namespace should be in Microsoft ownership only.

Thanks
