### ISSUE TITLE
Assertion failed '(type >= TYP_BYTE) && (type <= TYP_DOUBLE)

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#24260]
Found this regression in a local pmi run:
```
PREPONE type# 1260 method# 18850 System.Runtime.Intrinsics.X86.Avx2::ConvertToVector256Int16
Assert failure(PID 15436 [0x00003c4c], Thread: 20236 [0x4f0c]): Assertion failed '(type >= TYP_BYTE) && (type <= TYP_DOUBLE)' in 'System.Runtime.Intrinsics.X86.Avx2:ConvertToVector256Int16(long):struct' (IL size 7)

    File: f:\git\coreclr\src\jit\hwintrinsicxarch.h Line: 181
    Image: F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe
```

In order to repro run corerun.exe on pmi.dll for System.Private.CoreLib.dll:
`F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe C:\git\tools\jitutils\bin\pmi.dll prepone F:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\System.Private.CoreLib.dll 18850
`
After the fix please check that PrepAll works as well.

I reproduced it on the current and 3 days old versions.

Used default complus_*:
```
COMPlus_ContinueOnAssert=0
COMPlus_NoGuiOnAssert=0
complus_TieredCompilation=0
```

**Comment by sandreenko** [comment]
cc @dotnet/jit-contrib

**Comment by tannergooding** [comment]
This comes down to the assert here: https://github.com/dotnet/coreclr/blob/master/src/jit/hwintrinsicxarch.h#L181 Probably need a check that returns `INS_invalid` if the type isn't within the allowed range...

I'm not sure what change has caused this to start showing however, as I don't think anything has changed with regards to type checking before this line is hit... CC. @CarolEidt, anything come to your mind?

**Comment by CarolEidt** [comment]
I don't have any specific thoughts, especially given our recent discussion about how we're currently exploding all the overloads. Perhaps PMI is able to construct types that are not actually exposed? In any event, this should clearly needs to be made more robust against unsupported types.

**Comment by CarolEidt** [comment]
... and I should clarify that by "robust" I mean that we should always return `nullptr` for unexpected types or methods.

**Comment by tannergooding** [comment]
@CarolEidt, I determined the issue. The root problem is that we have some new overloads of `Avx2.ConvertToVector256*` which take a pointer as the first and only parameter. We can't determine the base type from the result and must determine it from the pointer argument....

However, I am unsure how to determine the underlying type of a pointer given the `CorInfoType` or `sig`/`arg`/`argClass` (and can't seem to find any existing examples)... Could you help point me in the right direction?

**Comment by tannergooding** [comment]
(I have the rest of the changes already prepped, including fixing `lookupIns` to account for invalid `baseType`; so I'm just stuck on this part)

**Comment by tannergooding** [comment]
Figured it out. Once I've determined it is a `CORINFO_TYPE_PTR`, I can call `getChildType(argClass)` to get the underlying type of the pointer.

**Comment by tannergooding** [comment]
PR resolving this should be here: https://github.com/dotnet/coreclr/pull/24289

@sandreenko, I tested `prepall` locally and it looks to pass. Might be good if you could also validate, however.
