### ISSUE TITLE
Exceptions in methods called from Finalize

### ISSUE THREAD

**Issue by cincuranet** [dotnet/coreclr#24297]
The [documentation for Finalize method](https://docs.microsoft.com/en-us/dotnet/api/system.object.finalize?view=netcore-2.2) states:
>If any exceptions thrown by methods called from the Finalize method are unhandled by the Finalize method, the runtime assumes that the Finalize method returned and continues to call the Finalize methods of other objects. 

But I don't see this behavior happening. I created a simple class with finalizer:
```csharp
class FinalizeMe
{
	~FinalizeMe()
	{
		Console.WriteLine($"In finalizer {nameof(FinalizeMe)}");
		Throw();
		Console.WriteLine("After exception");
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	void Throw()
	{
		throw new ArgumentException();
	}
}
```

And simulating what the docs says should happen:
```csharp
static void Main(string[] args)
{
	Test();
	GC.Collect();
	GC.WaitForPendingFinalizers();
}

static void Test()
{
	var a = new FinalizeMe();
	var b = new FinalizeMe();
	Console.WriteLine(a);
	Console.WriteLine(b);
}
```

And with this I see only one `In finalizer FinalizeMe` being printed on console. Basically I just see is:
> If Finalize or an override of Finalize throws an exception, and the runtime is not hosted by an application that overrides the default policy, the runtime terminates the process and no active try/finally blocks or finalizers are executed. This behavior ensures process integrity if the finalizer cannot free or destroy resources. 

Is the documentation correct?

**Comment by EgorBo** [comment]
> ... continues to call the Finalize methods of **_other_** objects.

so in order to see this behavior you need to define more types with finalizers, the exception thrown in `~FinalizeMe()` won't call `Console.WriteLine("After exception");` but it will continue calling other finalizers.

**Comment by jkotas** [comment]
Yes, the documentation is incorrect. Submitted PR to https://github.com/dotnet/dotnet-api-docs/pull/2380/ to delete it.

**Comment by cincuranet** [comment]
Great, good to know.
