### ISSUE TITLE
[Linux] build.sh fails to remove the binaries/../../debug directory 

### ISSUE THREAD

**Issue by shahid-pk** [dotnet/coreclr#243]
I think the recent changes to build.sh and setup-compiler-clang.sh are responsible for this.
Testing Ubuntu 14.04.1 clang 3.5 , llvm 3.5
> rm: cannot remove ‘/home/shahid/AspVnext/dotnet/coreclr/binaries/intermediates/amd64/debug’: Is a        directory
> Checking pre-requisites...
   Commencing CoreCLR Repo build
Doing a clean build
rm: cannot remove ‘/home/shahid/AspVnext/dotnet/coreclr/binaries/intermediates/amd64/debug’: Is a directory
Checking pre-requisites...
Please install clang before running this script

**Comment by poizan42** [comment]
Well, that error has been there from day 1: https://github.com/poizan42/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/build.sh#L44

**Comment by shahid-pk** [comment]
That was not their for  me before ... i build it daily

**Comment by shahid-pk** [comment]
and what about the clang error ?

**Comment by shahid-pk** [comment]
yes #245  fixes one of the issue. The other one is pending

**Comment by poizan42** [comment]
@shahid-pk The clang check is unchanged. What is the output of `which clang` ?

**Comment by shahid-pk** [comment]
for me its not **which clang** for me it is **which clang-3.5** and that is exactly the problem here i think.Because i think the code looks for clang although on Ubuntu its given name is clang-3.5 if you install it from official sources.

 > /usr/bin/clang-3.5

i am not shore which commit break this but it used to look for this scenario too.

**Comment by akoeplinger** [comment]
The clang check didn't work for me even several days ago, so I don't think it's related to the recent changes to build.sh. Looking at the build.sh history it always did `which clang` so I think this never worked correctly with the `clang-3.5` from Ubuntu repos.

**Comment by shahid-pk** [comment]
probably a regular expression is needed  a simple one.

**Comment by poizan42** [comment]
So are we going to look for every possible future version of clang that isn't named clang?

**Comment by akoeplinger** [comment]
I think something similar is already done for llvm in https://github.com/dotnet/coreclr/blob/master/src/pal/tools/gen-buildsys-clang.sh#L29-L33

**Comment by shahid-pk** [comment]
well then its solved

**Comment by poizan42** [comment]
I wouldn't call that "solved". It works specifically for llvm-3.5. It breaks for llvm-3.6, llvm-3.7 and every future version. We could enumerate every executeable starting with clang- and llvm- in the path, but that doesn't feel like the right way to do this. This problem must have been solved by other projects using clang.

**Comment by shahid-pk** [comment]
It would be something like this **llvm-[0-9].[0-9]** , a regular expression can do it.But it is just that i can not recall bash's regular expressions syntax.

**Comment by shahid-pk** [comment]
But actually we do not need to check for every possible version because clang-3.5 is supporten linux and just clang on OSX

**Comment by poizan42** [comment]
I have created a separate issue for the clang problem: #250
