### ISSUE TITLE
Interop/NativeLibraryResolveCallback/CallbackStressTest/CallbackStressTest.sh Timed Out

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#24305]
https://mc.dot.net/#/user/dotnet-mc-bot-2/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190429.72/workItem/Interop/analysis/xunit/Interop_NativeLibraryResolveCallback._CallbackStressTest_CallbackStressTest_~2F_CallbackStressTest_CallbackStressTest_sh

**Affected queues**
OSX.1013.Amd64-x64-
OSX.1012.Amd64-x64-

**Comment by RussKeldorph** [comment]
@sergiy-k

**Comment by RussKeldorph** [comment]
This isn't limited to OSX.  It can time out on other platforms, so we need to disable it everywhere for instead of just unix like I did in #24306.

https://dev.azure.com/dnceng/internal/_build/results?buildId=173566&view=ms.vss-test-web.build-test-results-tab

**Comment by fadimounir** [comment]
@RussKeldorph is there a way to increase the time limit for this test? I fined tuned it to run within the limits of CI, but it still looks like it can time out. This is not a bug. This test stresses some behavior of the system

**Comment by RussKeldorph** [comment]
@fadimounir The timeout is already 10 minutes, and we don't have a good way to change it without changing it for all the tests.  Stress tests aren't appropriate for these CI legs.  There is already enough "stress" on the system created by running many tests in parallel, and we currently have extremely high variability in test run times due to this--a 10X or more run time difference between the same test running in two identical test runs.

If you need stress type tests in CI, we should meet to talk about how to support that in a different way, either with special jobs or by adding functionality to tolerate the type of work these tests need to do.  If you don't want to do that, I recommend tuning the test to run at a tiny fraction of the timeout--significantly less than one minute.
