### ISSUE TITLE
GC heap affinitization on Windows machines with multiple CPU groups

### ISSUE THREAD

**Issue by vkvenkat** [dotnet/coreclr#24319]
Identified a GC heap affinitization issue in my Windows machine with 112 logical cores and 2 CPU groups in set_thread_affinity_for_heap. GC Heaps 0-55 are correctly affinitized to cores 0-55 & to group 0. But, GC heaps 56-111 are incorrectly affinitized to cores 64-119, instead of cores 56-111. This issue is Windows-only and the behavior is as expected on Linux.

The issue surfaces in [GCToOSInterface::GetProcessorForHeap](https://github.com/dotnet/coreclr/blob/master/src/vm/gcenv.os.cpp#L982-L983) which initializes the GroupProcNo constructor and then calls GetCombinedValue. The [GroupProcNo constructor](https://github.com/dotnet/coreclr/blob/master/src/vm/gcenv.os.cpp#L47) makes the assumption that Group 1 always starts from core 64, but it starts from core 56 in this case.

cc @janvorli @Maoni0

**Comment by janvorli** [comment]
> [GroupProcNo constructor](https://github.com/dotnet/coreclr/blob/master/src/vm/gcenv.os.cpp#L47) makes the assumption that Group 1 always starts from core 64

The GroupProcNo is just a wrapper for the group and the processor index in the group. The GetCombinedValue is not meant to be a value linearly representing CPUs. 
So it seems the issue would be in CPUGroupInfo::GetGroupForProcessor. That one is supposed to perform mapping the linear procIndex to group / in-group proc index.

**Comment by vkvenkat** [comment]
`CPUGroupInfo::GetGroupForProcessor` appears to behave as expected. It correctly fetches the group number & group processor number from procIndex in this case. Here is a debug dump:

![image](https://user-images.githubusercontent.com/14947878/56991659-0c07c380-6b4d-11e9-9b83-a3fe4de2f707.png)


For procIndex 56, `CPUGroupInfo::GetGroupForProcessor` correctly sets `gn` to 1 and `gpn` to 0. However, the `proc_no` returned by `GroupProcNo::GetCombinedValue` is set to 64. This is set in the `GroupProcNo` constructor using `((group << 6) | procIndex)` which may need to be revisited.

**Comment by janvorli** [comment]
> However, the proc_no returned by GroupProcNo::GetCombinedValue is set to 64.

That is correct. The 64 doesn't mean processor with global index 64. It means group 1 processor 0. As I've said in my previous comment, the proc_no is a packed form of gn and gpn represented by 16 bits.

**Comment by janvorli** [comment]
We always extract gn / gpn out of it before using it. See:
https://github.com/dotnet/coreclr/blob/5f7d459bf1a23f7e773c56eb5ef5425505b8eb0a/src/vm/gcenv.os.cpp#L213-L217

**Comment by vkvenkat** [comment]
Thanks for the explanation! I got it now. Let me close this issue.
