### ISSUE TITLE
Dynamically generated method throws System.BadImageFormatException: 'Bad IL format.'

### ISSUE THREAD

**Issue by pavelovcharov** [dotnet/coreclr#24330]
.NET Core Version: 3.0.100-preview6-011672

In our project, we are using Reflection.Emit to create a class descendant at runtime. When we call the dynamically generated method of this descendant, it throws the BadImageFormatException with the message 'Bad IL format'. The same code works without any exceptions in .Net Framework 4.7.2.

I've prepared a small sample to demonstrate the issue: https://github.com/pavelovcharov/netcore3_dynamicassembly

**Comment by jkotas** [comment]
`gen.Emit(OpCodes.Call, getServiceMethod)` is the problem. It calls interface method non-virtually. It is not a valid IL - it just happened to work fine in earlier .NET versions.

Could you please change your dynamic generator to use `OpCodes.Callvirt` to call interface methods instead?

Related to #22407

cc @MichalStrehovsky

**Comment by pavelovcharov** [comment]
@jkotas Thank you, now the code works as expected.

**Comment by MichalStrehovsky** [comment]
I've put the breaking change label on the pull request. Is there anything else I need to do to make sure it's document in the release notes?

Cc @AlekseyTs
