### ISSUE TITLE
Finish porting Jit stress jobs from Jenkins to ADO

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#24358]
The list of Jit testing jobs that are not currently available in ADO:

- [x]  tailcallstress,
- [x]  jitsse2only,
- [x]  jitnosimd,
- [x]  jitincompletehwintrinsic (EnableIncompleteISAClass="1"),
- [x]  jitx86hwintrinsicnoavx (EnableIncompleteISAClass="1" EnableAVX="0"),
- [x]  jitx86hwintrinsicnoavx2 (EnableIncompleteISAClass="1" EnableAVX2="0"),
- [x]  jitx86hwintrinsicnosimd (EnableIncompleteISAClass="1" FeatureSIMD="0"),
- [x]  jitnox86hwintrinsic (EnableIncompleteISAClass="1" EnableSSE="0" EnableSSE2="0" ,EnableSSE3="0"),
- [x]  zapdisable,
- [x]  heapverify1,
- [x]  gcstress0xc_zapdisable,
- [x]  gcstress0xc_zapdisable_jitstress2,
- [x]  gcstress0xc_zapdisable_heapverify1,
- [x]  gcstress0xc_jitstress1,
- [x]  gcstress0xc_jitstress2,
- [x]  gcstress0xc_jitminopts_heapverify1.

So the task is:
1. create a grouping for them (I think we can add tailcallstress to coreclr-outerloop-jitminopts-jitstress1-jitstress2, create a new group for SIMD/SSE/AVX/HW tests, add gcstess falvors to coreclr-outerloop-gcstress0x3-gcstress0xc, I am not sure about zapdisable and heapverify1).

**Note**: there is an inconsistency between naming policy for `outerloop-jitstressregs` and, for example, fo `outerloop-jitminopts-jitstress1-jitstress2` or `outerloop-gcstress0x3-gcstress0xc`. In the first case, we have just a general name in the second all actual scenario names. Do we want to rename `outerloop-jitminopts-jitstress1-jitstress2` to `outerloop-jitstress` so it would be easier to add new modes there?

2. Add the groups  to coreclr\eng\test-job.yml;

3. Define the possible triggers/platforms for the new groups in coreclr\azure-pipelines.yml;

4. Add a schedule to run them via web ADO UI;

5. Find a way to see our utilization rate for ADO/Helix machines so that we do not schedule too many jobs at one time because they will start to fail with a global timeout (that includes time when a job was scheduled but not started).

There are other jobs that we have only in Jenkins but they need special handling: 

- [x] formatting,
- [x] CoreFX, 
- [ ] PMI diffs, 
- [ ] Perf jobs,
- [x] crossgen_comparison, 
- [ ] ilrt, illink, 
- [ ] longgc, gcsimulator, standalone_gc, 
- [x] r2r stress testing,
- [x] forcerelocs.

Have I missed any?

**Comment by sandreenko** [comment]
cc @RussKeldorph @echesakovMSFT @BruceForstall @sbomer

**Comment by BruceForstall** [comment]
Grouping:
1. I agree tailcallstress should go in the existing coreclr-outerloop-jitminopts-jitstress1-jitstress2, which could for simplicity just be named coreclr-outerloop-jitstress.
2. ZapDisable should probably go in that group.
3. The xarch-specific SIMD/HW intrinsics tests should get a group. Maybe coreclr-outerloop-xarch.
4. The additional gcstress jobs, including HeapVerify, could be in a separate group coreclr-outerloop-gcstress-extra.

I'm not sure which of the simd/hw intrinsics jobs apply also to arm64. But we'll probably want a coreclr-outerloop-arm64.

**Comment by echesakovMSFT** [comment]
We need to do our best to minimize a number of build definitions (i.e. coreclr-outerloop-xarch, coreclr-outerloop-jitminopts-jitstress1-jitstress2 etc). As far as I know, we can configure them only manually and they are hard to maintain.

**Comment by sandreenko** [comment]
@fadimounir I was told that you was interested in more r2r testing, currently Jitci has:

- r2r_jitstress1,
- r2r_jitstress2,
- r2r_jitstress1_tiered,
- r2r_jitstress2_tiered,
- r2r_jitstressregs1,
- r2r_jitstressregs2,
- r2r_jitstressregs3,
- r2r_jitstressregs4,
- r2r_jitstressregs8,
- r2r_jitstressregs0x10,
- r2r_jitstressregs0x80,
- r2r_jitstressregs0x1000,
- r2r_jitminopts,
- r2r_jitforcerelocs,
- r2r_gcstress15,
- r2r_no_tiered_compilation

Do you want to have them in ADO? I can add them or show you how to do that.

**Comment by fadimounir** [comment]
@sandreenko I was interested in a R2R+GCStress run, and looks like it's already included in the list you sent (r2r_gcstress15). Just to make sure, this sets the RunCrossgen variable to 1 to compile each test into a R2R image, and run it with gcstress, correct?

**Comment by sandreenko** [comment]
> @sandreenko I was interested in a R2R+GCStress run, and looks like it's already included in the list you sent (r2r_gcstress15). Just to make sure, this sets the RunCrossgen variable to 1 to compile each test into a R2R image, and run it with gcstress, correct?

So do you want to port them from Jenkins to AzDO yourself?

**Comment by fadimounir** [comment]
> So do you want to port them from Jenkins to AzDO yourself?

I can port a few whenever I have free cycles if you show me how :)

**Comment by tannergooding** [comment]
Marked the stress jobs that are covered by https://github.com/dotnet/coreclr/pull/24630.

**Comment by BruceForstall** [comment]
@sandreenko Is there anything left to do here? If so, perhaps we should open individual issues and close this one.

From the remaining "un-checked" list above:

-  CoreFX: done
-   PMI diffs: we won't add this to AzDO. The plan is to add SuperPMI asm diffs, when available.
-   Perf jobs: I think @adiaaida is doing something related to this?
-   ilrt, illink: needs a separate issue?
-   longgc, gcsimulator, standalone_gc: I think @VSadov is working on this
-   forcerelocs: is it already part of one of our jit or gc stress combos?

**Comment by adiaaida** [comment]
Perf pipeline has been checked in. We still need to officially create the pipeline in AzDO.

**Comment by sandreenko** [comment]
> @sandreenko Is there anything left to do here? If so, perhaps we should open individual issues and close this one.

Yes, I think it will be good to open individual issues with assigned people/teams and close this one.

**Comment by sandreenko** [comment]
Close this one, the biggest part was implemented, refer to the individual issues for the unfinished tasks, thanks @jashook for tracking/opening them. 
Link #26377, #26376, #26375.

The only question is Perf jobs, I have not seen an AzDO job for it, so looks like it is unfinished and needs an issue as well?
