### ISSUE TITLE
Assert failure(PID 217128 [0x00035028], Thread: 229384 [0x38008]): Precondition failure: FAILED: g_fEEStarted

### ISSUE THREAD

**Issue by cshung** [dotnet/coreclr#24385]
I hit this assert when I tried to run `dotnet trace` as soon as the named pipe is initialized.

```
Assert failure(PID 217128 [0x00035028], Thread: 229384 [0x38008]): Precondition failure: FAILED: g_fEEStarted

CORECLR! CHECK::Trigger + 0x2F8 (0x0f3efab8)
CORECLR! EnsureComStarted + 0x1F0 (0x0f4eac80)
CORECLR! Thread::SetApartment + 0x645 (0x0f5470a5)
CORECLR! ThreadpoolMgr::TimerThreadStart + 0x73 (0x0fa784e3)
KERNEL32! BaseThreadInitThunk + 0x19 (0x76fe0419)
NTDLL! RtlGetAppContainerNamedObjectPath + 0xED (0x777a662d)
NTDLL! RtlGetAppContainerNamedObjectPath + 0xBD (0x777a65fd)
    File: C:\Dev\coreclr\src\vm\interoputil.cpp Line: 2254
    Image: C:\Dev\coreclr\bin\tests\Windows_NT.x86.Debug\Tests\Core_Root\CoreRun.exe
```

I believe this is caused by the fact that EventPipe uses ThreadPool too early before the runtime is completely initialized.

To reproduce this issue, clone and build the [diagnostics repo](https://github.com/dotnet/diagnostics), check out [my branch](https://github.com/cshung/coreclr/tree/dev/andrewau/auto-trace) and update [autotrace.cpp](https://github.com/cshung/coreclr/blob/dev/andrewau/auto-trace/src/vm/autotrace.cpp) so that it launches in the right path.

Once the setup is done, build the coreclr repo and run the [eventlistener test](https://github.com/cshung/coreclr/blob/dev/andrewau/auto-trace/tests/src/tracing/eventlistener/EventListener.cs), it should repro the assertion.

**Comment by tommcdon** [comment]
@cshung are you interested in fixing this?
