### ISSUE TITLE
error CS1513

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24398]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_corefx_jitstress1/75/

**Log:**
HttpClientHandlerTest.Http2.cs(1352,10): error CS1513: } expected [/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstress1/_/fx/src/System.Net.Http/tests/FunctionalTests/System.Net.Http.Functional.Tests.csproj]

**Comment by stephentoub** [comment]
This was fixed 2 days ago in https://github.com/dotnet/corefx/commit/3075793b035cfa51d5b2a8aa0d388ee41faf2bf9.
