### ISSUE TITLE
CI failures

### ISSUE THREAD

**Issue by tarekgh** [dotnet/coreclr#24453]
https://mc.dot.net/#/user/coreclr-ci/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F24443~2Fmerge/test~2Ffunctional~2Fcli~2F/20190507.721/workItem/baseservices.threading/wilogs

Ubuntu.1804.Arm64.Open-arm64:Checked
Details from Job 360c3f70-4d7a-4e0c-b07f-f3d6d1d50ca7
ExitCode: -3 
Ran on Machine: DDARM64S-024 
Get Repro environment 
DownloadError: Unable to download https://helixexternaldrops.blob.core.windows.net/helix-job-75691982-4ea1-4d86-9c57-2afce2333af4f1a0935b3664120aa/d2412905-594f-4a8d-b0e0-2f8901e0d4cd.zip after retrying. Execution may fail as a result.
Console
Warning! No Log Available

**Comment by echesakovMSFT** [comment]
This is a known infrastructure issue. Tracked by https://github.com/dotnet/core-eng/issues/6266
