### ISSUE TITLE
[EventPipe] Event missing when long string as an event argument

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/coreclr#24470]
Test:
coreclr\tests\src\tracing\eventsource\eventsourcetrace\EventSourceTrace.cs

Line 28:
Set messageIterations = 5000;

Line 74:
Add following code:
```
for (int j = 0; j < 10; j++)
{
formula = formula + formula;
}
```

Actual: 4999
Expected: 5000;
netperf file size: 153497 KB

**Comment by tommcdon** [comment]
@cshung please investigate.  Possibly related to #24468

**Comment by jorive** [comment]
I believe this is `EventSource`, not `EventPipe`.

**Comment by cshung** [comment]
I confirm the netperf generated have only 4,999 events, the event is dropped inside the runtime somewhere
