### ISSUE TITLE
Proposal: Add support for ArraySegment<byte> in MemoryStream constructor

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#2449]
Since we've added a `TryGetBuffer(out ArraySegment<byte>)` method to `MemoryStream` in .NET 4.6, can we support it in the MS constructor as well? We can add these constructors to the class:

- `MemoryStream(ArraySegment<byte>)`
- `MemoryStream(ArraySegment<byte>, bool writable)`

I can open a PR myself if no one is willing.

**Comment by weshaggard** [comment]
@jamesqo I assume you want this just for convenience as https://github.com/dotnet/corefx/blob/master/src/System.IO/ref/System.IO.cs#L100 actually covers the scenario, correct?

**Comment by jamesqo** [comment]
Correct, this is purely for better code readability.

**Comment by jamesqo** [comment]
Moved to CoreFX: dotnet/corefx#6740
