### ISSUE TITLE
[Proposal] Allow sizeof(T) where T: unmanaged

### ISSUE THREAD

**Issue by dangi12012** [dotnet/coreclr#24490]
int size = sizeof(T) //Compiler error only works in unsafe context.
While the above error generally is true the same cannot be said for the constraint:
```
void foo<T>() where T: unmanaged
int size = sizeof(T) //This should work since unmanaged only allows known size elements
```
This adaption would make work with MemoryMarshal and Memorymapped files faster. Spans can be cast to Span<byte> and Unsafe.Sizeof<T> is not free, but sizeof(T) is, and should work with T: unmanaged.

**Comment by svick** [comment]
A comment on https://github.com/dotnet/csharplang/issues/1508 (which you have also created) says:

> The `sizeof` IL instruction is always verifiable and perfectly safe.

I think this means there is nothing for the coreclr to do here, it's all about the language (and the compiler).

**Comment by dangi12012** [comment]
Right! It says it is safe AND should work without unmanaged keyword. The thread is over a year old now and still open. So maybe it is a coreclr issue.

**Comment by MichalStrehovsky** [comment]
> So maybe it is a coreclr issue.

No, still a C# language issue, sorry.
