### ISSUE TITLE
Improve CoreFX test runs 

### ISSUE THREAD

**Issue by davmason** [dotnet/coreclr#24501]
#24259 enabled corefx runs, here is the remaining work:

- Enabling for the rest of the test matrix (checked, linux, etc)
- Going through disabled tests and seeing what should be disabled and what shouldn't, this will likely involve removing all exclusions from CoreFX.issues.rsp and then analyzing the failures
- Getting more up to date CoreFX dependencies (talk to @ViktorHofer)
- Getting a way to disable namespaces on a per assembly basis rather than globally. Currently we only support global exclusions, and that means if there are duplicate namespaces we unintentionally disable those tests too

**Comment by ViktorHofer** [comment]
> Getting more up to date CoreFX dependencies

We just published `Microsoft.Private.CoreFx.OOB` to the blob-feed (+ darc). I recommend to replace the static list of OOB packages with this package.

Also Mono and CoreFx would like to use the same mechanism that was implemented here. Is it possible to move most of the logic to `Microsoft.DotNet.CoreFxTesting`?

**Comment by BruceForstall** [comment]
https://github.com/dotnet/coreclr/pull/25326 enabled the rest of the test matrix. There could be more done, like corefx + R2R, corefx + gcstress. We need to enable Windows/arm32 when corefx publishes those test packages. And Windows/arm64 when we have enough hardware.

Dependencies now use a corefx meta-package reference.

As for: 
> Getting a way to disable namespaces on a per assembly basis rather than globally. 
we will not do this. We will continue to use a single, unconditional exclusion file, for the simplicity of it. This does have the potential to over-exclude, but we will live with that.

The remaining work here:
. Document current corefx repro steps and running instructions for devs to repro a failure seen in these runs.
. Update CoreFX.issues.rsp, and triage issues that remain in there, ensuring GitHub issues for each.

**Comment by ViktorHofer** [comment]
> Update CoreFX.issues.rsp, and triage issues that remain in there, ensuring GitHub issues for each.

+100

**Comment by BruceForstall** [comment]
This work is complete, except for adding Windows/arm, which is tracked by https://github.com/dotnet/coreclr/issues/25435

The runtest.cmd options CoreFXTests and CoreFXTestsAll have been removed.
