### ISSUE TITLE
Distinct Linux failures

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#2450]
The following tests fail on Linux but do not have a corresponding exclusion on Windows.
These need further analysis.

```
JIT/Directed/IL/mutualrecurthd-tailcall/mutualrecurthd-tailcall/mutualrecurthd-tailcall.sh
JIT/Directed/Misc/function_pointer/mutualthdrecur-fptr/mutualthdrecur-fptr.sh
JIT/Directed/perffix/primitivevt/identity3_il_d/identity3_il_d.sh
JIT/Directed/pinning/object-pin/object-pin/object-pin.sh
JIT/jit64/regress/vsw/546707/sql_stress4/sql_stress4.sh
JIT/Methodical/Boxing/xlang/_relsin_il_il/_relsin_il_il.sh
JIT/Methodical/Coverage/arglist_pos/arglist_pos.sh
JIT/Methodical/eh/deadcode/badcodeafterfinally_d/badcodeafterfinally_d.sh
JIT/Methodical/eh/deadcode/badcodeafterfinally_r/badcodeafterfinally_r.sh
JIT/Methodical/eh/interactions/cornucopia1_d/cornucopia1_d.sh
JIT/Methodical/eh/interactions/cornucopia1_r/cornucopia1_r.sh
JIT/Regression/CLR-x86-JIT/V1.2-Beta1/b213516/b213516/b213516.sh
JIT/Regression/CLR-x86-JIT/V1.2-M01/b08707/b08707/b08707.sh
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b26324/b26324a/b26324a.sh
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b26324/b26324b/b26324b.sh
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b27098/b27098/b27098.sh
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b28911/b28911/b28911.sh
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b28949/b28949b/b28949b.sh
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b47584/b47584/b47584.sh
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b51416/b51416/b51416.sh
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b56272/b56272/b56272.sh
JIT/Regression/VS-ia64-JIT/V1.2-M01/b11959/b11959/b11959.sh
JIT/Regression/VS-ia64-JIT/V1.2-M02/b16933/b16933/b16933.sh
JIT/Regression/VS-ia64-JIT/V1.2-M02/b22545/b22545/b22545.sh
JIT/Regression/VS-ia64-JIT/V1.2-M02/b22591/b22591/b22591.sh
JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b416776/b416776/b416776.sh
```

**Comment by LLITCHEV** [comment]
@richardlford 
I have taken a look at these and below are my findings. Please, move/build/remove the tests as noted in the notes.

JIT/Directed/IL/mutualrecurthd-tailcall/mutualrecurthd-tailcall/mutualrecurthd-tailcall.sh
    Passed when run with latest bits.

JIT/Directed/Misc/function_pointer/mutualthdrecur-fptr/mutualthdrecur-fptr.sh
    The test is not built when following the instructions for running coreclr tests. The binaries from the test don't exist

JIT/Directed/perffix/primitivevt/identity3_il_d/identity3_il_d.sh
    Passed with latest bits.

JIT/Directed/pinning/object-pin/object-pin/object-pin.sh
    Uses mirror.dll in the test which seem not to be build for Linux. This is a native SL.

JIT/jit64/regress/vsw/546707/sql_stress4/sql_stress4.sh
    It looks like some of the attributes in the IL are preventing the VM from loading the test on Linux. The VM bails out before even trying to do any compilations. This file contains Thread.Aboart(), which is not allowed for the portable profile. The test should fail compiling. It looks like the test (and many others) for Linux are compiled against the Desktop libraries (which is wrong) instead of the targetLibs for the platform.

JIT/Methodical/Boxing/xlang/_relsin_il_il/_relsin_il_il.sh
    It looks lik ethe sinlib_il library is not compiled. Needs to be, I think.

JIT/Methodical/Coverage/arglist_pos/arglist_pos.sh
    Uses varargs call (not supported in the portable profile). Please move the test to Unsupported on non Windows platforms file from the Failing on Windows Platforms.

JIT/Methodical/eh/deadcode/badcodeafterfinally_d/badcodeafterfinally_d.sh
    This seems to be bad IL. RyuJit (differently to jit64) enforces not to have a jump (or any other way to get out) of try block, but a leave instruction.

JIT/Methodical/eh/deadcode/badcodeafterfinally_r/badcodeafterfinally_r.sh
    Same as above.

JIT/Methodical/eh/interactions/cornucopia1_d/cornucopia1_d.sh
    There are no tests executables built for this test.

JIT/Methodical/eh/interactions/cornucopia1_r/cornucopia1_r.sh
    There are no test executables built for this test.

JIT/Regression/CLR-x86-JIT/V1.2-Beta1/b213516/b213516/b213516.sh
    Looks like the test is not compiled against the platform targetLibs. It looks compiled against the Desktop libraries. System.Console.WriteLine(System.String) doesn't exist on Linux (in the portable profile). The manifest (target files) direct it to a different method when compiled.

JIT/Regression/CLR-x86-JIT/V1.2-M01/b08707/b08707/b08707.sh
    The binaries for the test don't exist.

JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b26324/b26324a/b26324a.sh
    This test need to be moved to the Unsupported on non-Windows platforms file. It has varargs that is not supported on the portable profile.

JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b26324/b26324b/b26324b.sh
    This test need to be moved to the Unsupported on non-Windows platforms file. It has varargs that is not supported on the portable profile.

JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b27098/b27098/b27098.sh
    No executable for the test is built.

JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b28911/b28911/b28911.sh
    No executable for the test is built.

JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b28949/b28949b/b28949b.sh
    No executable for the test is built.
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b47584/b47584/b47584.sh
    No executable for the test is built.

JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b51416/b51416/b51416.sh
    No executable for the test is built.

JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b56272/b56272/b56272.sh
    No executable for the test is built.

JIT/Regression/VS-ia64-JIT/V1.2-M01/b11959/b11959/b11959.sh
    No executable for the test is built.

JIT/Regression/VS-ia64-JIT/V1.2-M02/b16933/b16933/b16933.sh
    No executable for the test is built.

JIT/Regression/VS-ia64-JIT/V1.2-M02/b22545/b22545/b22545.sh
    No executable for the test is built.

JIT/Regression/VS-ia64-JIT/V1.2-M02/b22591/b22591/b22591.sh
    No executable for the test is built.

JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b416776/b416776/b416776.sh
    No executable for the test is built.
