### ISSUE TITLE
object-pin.cmd pinvoke fails to find Ret_Ptr entrypoint

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#2452]
On a debug win64 test job, the 

```
JIT\Directed\pinning\object-pin\object-pin\object-pin.cmd
```

test failed with this message:

```
Unhandled Exception: System.EntryPointNotFoundException: 
  Unable to find an entry point named 'Ret_Ptr' in DLL 'Mirror'.
```

The mirror.dll is present in the right place and the export
file lists Ret_Ptr as being exported, but for some reason
it is not being found.

**Comment by hoyMS** [comment]
Fixed. Merged in as #2563.
