### ISSUE TITLE
throwincascadedcatchnofin_d.sh fails on OS X

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#2454]
The following tests:

```
JIT/Methodical/eh/nested/cascadedcatchret/throwincascadedcatchnofin_d/throwincascadedcatchnofin_d.sh
JIT/Methodical/eh/nested/cascadedcatchret/throwincascadedcatchnofin_r/throwincascadedcatchnofin_r.sh
```

fails on OS X, e.g. job
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_osx_tst_prtest/264

The job failed with a timeout.

**Comment by sivarv** [comment]
Please rule out that this is not a test issue.  One quick way to check is by running the same test binary against desktop and checking whether it fails there as well.  This will work provided test is not using any API surface which is ProjectK specific, which I believe is the case for these tests.

**Comment by RussKeldorph** [comment]
This test is now passing and has been re-enabled.
