### ISSUE TITLE
Unobtrusive/Extrospection API for JIT events?

### ISSUE THREAD

**Issue by jzabroski** [dotnet/coreclr#24567]
@jkotas Is there any way I can check whether the JIT has inlined something?

For example from some code I have written, how would I tell this has been inlined:

```csharp
static class Constructor<T>
  where T : new()
{
  public static readonly Func<IScope, T> Empty = Expression.Lambda<Func<IScope, T>>(scope => scope.Exists<T>() ?? new T()).Compile();
}
```

Similarly, is there any "Auditing Machine" I can query inside the runtime to determine how far away the code is/was from being JIT'ed?

Alternatively, is there a simple test harness where I can write some C#, verify it compiles down to specific IL, then verify that IL maps to specific hot path optimizations?  (Are there performance test case examples of how the CoreCLR team verifies code generation passes as being useful?)

Possibly related: https://github.com/dotnet/coreclr/issues/18330 - this is not quite the same thing, because this related issue seems to be more about "data warehouse" facilities that dovetail off of such an "auditing machine".

**Comment by stephentoub** [comment]
The JIT outputs ETW events for every method it compiles, showing what was inlined, and if something wasn't, why not. You can see these in PerfView, for example.

**Comment by jzabroski** [comment]
OK, hope it's OK to close this and re-open if I have further questions on slicing and dicing. Thanks @stephentoub for your help!

**Comment by jzabroski** [comment]
Actually, one last question to help me connect the dots - if https://github.com/dotnet/coreclr/issues/18330 is not closed and ETW+PerfView is how to do extrospection/warehousing, how do things like the newer runtime performance profiles work and tiered compilation work?  (I'm not sure how I would necessarily come up with my own example to observe tiered compilation...)

**Comment by mattwarren** [comment]
> ... and ETW+PerfView is how to do extrospection/warehousing, how do things like the newer runtime performance profiles work and tiered compilation work?

If it helps, the recent versions of PerfView [give you some information](https://github.com/microsoft/perfview/pull/679) about 'Tiered Compilation' in the "JIT Stats" section:
![image](https://user-images.githubusercontent.com/157298/57763125-b7417c80-76f8-11e9-9853-b554153d7c61.png)

With regards to inlining, you might also find the [Inlining Analyzer](https://marketplace.visualstudio.com/items?itemName=StephanZehetner.InliningAnalyzer) useful (VS 2017/19 only). It uses the same ETW events that PerfView can display.
