### ISSUE TITLE
Test failed: System.SpanTests.ReadOnlySpanTests.TestMatchLastIndexOfAny_Byte_ManyByte

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24583]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_minopts_tst/196/

**Failed tests:**
System.SpanTests.ReadOnlySpanTests.TestMatchLastIndexOfAny_Byte_ManyByte

**Log:**
```
System.SpanTests.ReadOnlySpanTests.TestMatchLastIndexOfAny_Byte_ManyByte [FAIL]
      Assert.Equal() Failure
      Expected: 78
      Actual:   79
      Stack Trace:
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_minopts/_/fx/src/System.Memory/tests/ReadOnlySpan/LastIndexOfAny.byte.cs(391,0): at System.SpanTests.ReadOnlySpanTests.TestMatchLastIndexOfAny_Byte_ManyByte()
```

**Comment by BruceForstall** [comment]
Started https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_minopts_flow/235/ to see if it repros

**Comment by BruceForstall** [comment]
Didn't repro.
