### ISSUE TITLE
Add Encoding.GetByteCount(string, offset, count)

### ISSUE THREAD

**Issue by bartonjs** [dotnet/coreclr#2460]
There's the unsafe version (`GetByteCount(char*, count)`), and there's the data extractor (`GetBytes(string, strOffset, count, buffer, bufOffset)`), but there's not a way to know ahead of time the accurate byte count of the UTF-8 encoding of a portion of a string without `unsafe`.

Workarounds do exist, like:
- Call Substring on the string
- Call ToCharArray on the string
- Just call the unsafe version

I'd even suggest doing it as something like

``` C#
public virtual int GetByteCount(string s, int charIndex, int charCount)
{
    // Preconditions go here.

    unsafe
    {
        fixed (char* ptr = s)
        {
            return GetByteCount(ptr + charIndex, charCount);
        }
    }
}
```

And it's a functioning addition.

**Comment by tarekgh** [comment]
@bartonjs just wondering why you cannot use unsafe? is it just for convenience to call the API without pinning the string? or there is any other reason?

**Comment by bartonjs** [comment]
@tarekgh Mainly I was surfacing it as "there's a gap in the matrix between GetByteCount and GetBytes".  But also, because @morganbr scolded me.

Really, I guess, I don't even care about that GetByteCount method; `byte[] GetBytes(string str, int offset, int count)` would more match what I was looking for.  Just a safe way to do an encoding of a substring without allocating the `char[]` or having to call substring and allocate a new `string` object to just immediately throw away.

**Comment by bartonjs** [comment]
Submitted API proposal as https://github.com/dotnet/corefx/issues/14255

**Comment by tarekgh** [comment]
Closing this one as we already tracking this on corefx now.
