### ISSUE TITLE
[X86/Linux] Fail to SkipCrossgen when enabled Interpreter

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/coreclr#24627]
Hi,

`FEATURE_INTERPRETER` and `CROSSGEN_COMPILE` are mutually exclusive https://github.com/dotnet/coreclr/pull/11252

So how to disable `CROSSGEN_COMPILE`?  skipcrossgen doesn't work:

```
./build.sh cmakeargs "-DFEATURE_INTERPRETER=1" skipcrossgen

...
/home/loongson/zhaixiang/coreclr/src/inc/switches.h:199:9: warning: defined(FEATURE_INTERPRETER) && defined(CROSSGEN_COMPILE)
      [-W#pragma-messages]
#pragma message("defined(FEATURE_INTERPRETER) && defined(CROSSGEN_COMPILE)")
        ^

```

Then `FEATURE_INTERPRETER` is undefined, not be enabled https://github.com/dotnet/coreclr/issues/17294#issuecomment-493071519 

```
diff --git a/src/inc/switches.h b/src/inc/switches.h
index 6003460..7f735f3 100644
--- a/src/inc/switches.h
+++ b/src/inc/switches.h
@@ -196,5 +196,6 @@
 #endif // !defined(CROSSGEN_COMPILE)
 
 #if defined(FEATURE_INTERPRETER) && defined(CROSSGEN_COMPILE)
+#pragma message("defined(FEATURE_INTERPRETER) && defined(CROSSGEN_COMPILE)")
 #undef FEATURE_INTERPRETER
 #endif
```

Please give me some hint about how to SkipCrossgen.

Thanks,
Leslie Zhai

**Comment by jkotas** [comment]
You can try adding `DFEATURE_INTERPRETER` to `remove_definitions` section in https://github.com/dotnet/coreclr/blob/master/crossgen.cmake to make this cleaner.

**Comment by xiangzhai** [comment]
Hi @jkotas 

Thanks for your kind response!

> You can try adding `DFEATURE_INTERPRETER` to `remove_definitions` section in https://github.com/dotnet/coreclr/blob/master/crossgen.cmake to make this cleaner.

Another question is how to just enable `FEATURE_INTERPRETER` but *disable* `CROSSGEN_COMPILE` for hacking Interpreter.

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi @jkotas and @RussKeldorph 

Please review it https://github.com/dotnet/coreclr/pull/24653

Thanks,
Leslie Zhai
