### ISSUE TITLE
SemaphoreSlim.WaitAsync(CancellationToken) allocates an unnecessary CancellationTokenSource

### ISSUE THREAD

**Issue by sharwell** [dotnet/coreclr#24622]
`SemaphoreSlim.WaitAsync(CancellationToken)` chains to `SemaphoreSlim.WaitAsync(int, CancellationToken)` and always uses `Timeout.Infinite`.

https://github.com/dotnet/coreclr/blob/b4c2b142c700e8ec58783138aca2340ac05b24d5/src/System.Private.CoreLib/shared/System/Threading/SemaphoreSlim.cs#L507-L510

The callee eventually calls `WaitUntilCountOrTimeoutAsync`, where a `CancellationTokenSource` is used to support the combination of a timeout and the cancellation token:

https://github.com/dotnet/coreclr/blob/b4c2b142c700e8ec58783138aca2340ac05b24d5/src/System.Private.CoreLib/shared/System/Threading/SemaphoreSlim.cs#L719-L729

For the specific case of `Timeout.Infinite`, the `CancellationTokenSource` is unnecessary, and the method could be written to avoid this allocation.

:link: This was observed while reviewing https://developercommunity.visualstudio.com/content/problem/569307/roslyncodeanalysisservice32-is-topped-out-at-3gb-m.html, but did not play a substantial role in the final outcome.

**Comment by gfoidl** [comment]
>  the `CancellationTokenSource` is unnecessary, and the method could be written to avoid this allocation.

Even for `Timeout.Infinite` there has to be a way to cancel the task. Is there any way to cancel a task without this pattern? I know the way via `TaskCompletionSource` and `cancellationToken.Register -> TrySetResult` and `Task.WhenAny`, but this would save the allocation for the `CancellationTokenSource` at the cost of another allocation -- so no save in total.

**Comment by stephentoub** [comment]
@sharwell, what did you have in mind?

**Comment by sharwell** [comment]
Between the approach here and the approach for `WithCancellationSlow` in Microsoft/vs-threading, I'm not certain which is the best. I imagine setting up a benchmark for it with BenchmarkDotNet would be particularly informative.

**Comment by stephentoub** [comment]
My expectation is the other will be better (for the case where there's no timeout and the token is cancelable), in particular because it allows the registration with the CTS to be on the existing one rather than on a new one, which will cause the CTS's internal data structures to be initialized.  That's different from "allocates an unnecessary CancellationTokenSource", however.
