### ISSUE TITLE
XmlSerializer.Deserialize causing Kestrel failure in .NET Core 3.0 Preview 5

### ISSUE THREAD

**Issue by Kaelum** [dotnet/coreclr#24643]
I have been using the XmlSerializer for years, and I am using it in a project that I upgraded to .NET Core 3.0 Preview 5 today.  After the upgrade, I receive the following exception when I try to XmlSerialize.Deserialize (Stream) the Request stream in a custom middleware component:

**Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead**

Prior to the upgrade, everything was working fine, so there is definitely something broken in in this serializer.  If I update the Kestrel options as follows, it works fine:

```
.UseKestrel((context, options) =>
{
	// Temporary? The XmlSerializer is only performing synchronous operations.
	options.AllowSynchronousIO = true;
})
```

**Comment by kevingosse** [comment]
What has changed isn't the XmlSerializer but Kestrel. The default value of `AllowSynchronousIO` was `true`, it has been changed to `false` in 3.0: https://github.com/aspnet/AspNetCore/commit/93a24b03bbda1aa0ab9b553a50b70dd36d554934

**Comment by Kaelum** [comment]
So is changing it to `true` the recommended action?  Or should we be doing something different?

**Comment by jkotas** [comment]
Answered in https://github.com/aspnet/AspNetCore/issues/7644#issuecomment-493632670
