### ISSUE TITLE
Where is the comamand csc c# compiler?

### ISSUE THREAD

**Issue by quantrpeter** [dotnet/coreclr#24651]
Hi
  Where is the command **csc** c# compiler?
thanks
Peter

**Comment by jkotas** [comment]
.NET Core SDK has `dotnet build` verb that will invoke csc for you, with the right command line. It does not have first class support for invoking csc compiler directly.

If you really need to invoke csc directly for some reason, you can do by using full path to csc.dll that is part of .NET Core SDK. For example, like this:
```
dotnet "C:\Program Files\dotnet\sdk\3.0.100-preview6-011681\Roslyn\bincore\csc.dll"
```

More discussion on this is in https://github.com/dotnet/cli/issues/7689
