### ISSUE TITLE
Incorrect parameters passed when profiler set COR_PRF_DISABLE_INLINING

### ISSUE THREAD

**Issue by iskiselev** [dotnet/coreclr#24676]
When profiler `SetEventMask` with `COR_PRF_DISABLE_INLINING` flag set (disable inlining), method get incorrect arguments (on Linux and MacOs, it works correct on Windows).
Try to use next application (compile with release from console app template):
```c#
using System;

namespace repro
{
    public class SomeClass
    {
        public string SomeMethod(string s1, string s2,
            string s3, string s4, string s5, string s6)
        {
            Console.WriteLine($"{s1}:{s2}:{s3}:{s4}:{s5}:{s6}");
            return s1;
        }
    }

    public struct Struct
    {
        public object o1;
        public object o2;
    }

    public static class BadClass
    {
        //[MethodImpl(MethodImplOptions.NoInlining)]
        public static string BadInline(string s1,
            string s2, Struct @struct, string s3, string s4,
            string s5, string s6)
        {
                var mapperExpression = new SomeClass().SomeMethod(s1, s2,
                    s3, s4, s5, s6);
                return mapperExpression;
        }
    }
    
    class Program
    {
        static void Main(string[] args)
        {
            BadClass.BadInline(
                "s1",
                "s2",
                new Struct(), 
                "s3",
                "s4",
                "s5",
                "s6");
        }
    }
}
```
Expected console output: `s1:s2:s3:s4:s5:s6`
Broken console output: `s1:s2:s3:s4:s6:s6`

If `BadInline` method marked with `MethodImplOptions.NoInlining` issue is not reproducible.
Issue is only reproducible when profiler that set `COR_PRF_DISABLE_INLINING`  is loaded.
I've reproduced it on version 2.2.5 and only with test application release build.

If it is required, I may create test sample with profiler included (thought it will take some time).

Automapper 8.0 use pattern affected by this issue, so some of applications that use Automapper  will crash if loaded with profiler requested `COR_PRF_DISABLE_INLINING`.

**Comment by AndyAyersMS** [comment]
Seems like this could be the same issue as in #22330.

**Comment by AndyAyersMS** [comment]
@iskiselev does this repro in 3.0?

**Comment by iskiselev** [comment]
Tried with fresh docker image mcr.microsoft.com/dotnet/core/sdk:3.0 - I was not able to reproduce it with both setting of "System.Runtime.TieredCompilation" (true/false).
I was also not able to reproduce it on 2.2, even calling `BadInline` method lot's of times.
For reference:
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     debian
 OS Version:
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview5-011568/

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  3.0.100-preview5-011568 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by AndyAyersMS** [comment]
I can repro on 2.2.5 if I modify your example to match what we did in #22330 -- just add `[MethodImpl(MethodImplOptions.NoOptimization)]` to `Main`.
```
andy@ANDYA16:~/bugs/24676$ dotnet run -c Release -f netcoreapp2.2
s1:s2:s3:s4:s6:s6

andy@ANDYA16:~/bugs/24676$ dotnet run -c Release -f netcoreapp3.0
s1:s2:s3:s4:s5:s6

.NET Core runtimes installed:

  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

The bug in 2.2 is in the way that `BadInline` tail calls `SomeMethod`. When you block inlining of a method via an attribute, you also block making tail calls from that method (the assumption being that you really want that method to have a distinct stack frame). But when the profiler blocks inlining we don't get the follow-on impacts to tail calls.

Marking `Main` as no-optimization inhibits inlining of `BadInline` without altering the codegen of `BadInline` and so also allows the bug to repro.

This is the second report of this bug against 2.2 and it seems like we should consider porting the fix from master/3.0 over there.

cc @RussKeldorph

**Comment by iskiselev** [comment]
I also reproduced the issue on 2.1, which wary me even more, as 2.1 is LTS and will be supported even longer than 2.2.
Can fix be also ported to 2.1?

**Comment by AndyAyersMS** [comment]
> Can fix be also ported to 2.1?

It's possible, yes. Can you say more how likely it is that somebody using Automapper will run into this?

**Comment by iskiselev** [comment]
Most of users of Automapper will be affected. Issue occurs inside AutoMapper.Mapper.Initialize (can't be avoid to use Automapper) if user have at least one Nullable<T> in source class.

**Comment by daniel-white** [comment]
i'd appreciate a fix in 2.1

**Comment by iskiselev** [comment]
Issue can be reproduced even with enabled TieredCompilation.

**Comment by AndyAyersMS** [comment]
@jashook are you going to work on the proposal for a 2.1 port of #22775?

**Comment by jashook** [comment]
Yes I can do this.

**Comment by iskiselev** [comment]
Do you have plans to port it into 2.2 also or it will be only 2.1 and 3.0?

**Comment by AndyAyersMS** [comment]
This fix will also flow into 2.2.

**Comment by AndyAyersMS** [comment]
#24954 merges the fix into the 2.2 branch.

I'll update this issue once we release a new 2.2 version that includes this.

**Comment by AndyAyersMS** [comment]
@iskiselev The fix is included in the just-released 2.1.12 and 2.2.6. Can you verify when you get a chance?

**Comment by stricq** [comment]
My team has hit this in 2.2.2 with a pretty basic setup so I suspect this is a common problem.  We set COMPlus_TieredCompilation=1 and this fixed the problem.  We will upgrade to 2.2.6 as soon as we can.

**Comment by lucaspimentel** [comment]
We ran [this program](https://github.com/DataDog/dd-trace-dotnet/blob/develop/reproductions/AutomapperTest/Program.cs) to test AutoMapper and we no longer get the error message. 🎉 

notes:
- profiler sets `COR_PRF_DISABLE_INLINING` in `SetEventMask()`
- also setting `COR_PRF_DISABLE_OPTIMIZATIONS` would avoid the error in previous versions
- tested on `mcr.microsoft.com/dotnet/core/sdk:2.2.301-bionic` (error happens with `2.2.300`) targeting both `netcoreapp2.2` and `netcoreapp2.1`
- tested on `mcr.microsoft.com/dotnet/core/sdk:2.1.701-bionic` (error happens with `2.1.700`) targeting `netcoreapp2.1` only

**Comment by iskiselev** [comment]
We don't see this problem on latest update also.

**Comment by AndyAyersMS** [comment]
Good to hear. I am going to close this one out.
