### ISSUE TITLE
[ARM64/Linux] error MSB6006: "csc.dll" exited with code 139.

### ISSUE THREAD

**Issue by directhex** [dotnet/coreclr#24683]
I'm trying to do a Mono `--with-core=only` build, which uses a stock .NET Core to build our System.Private.CoreLib:

`dotnet build -p:TargetsUnix=true  -v:diag -p:BuildArch=arm64 -p:OutputPath=bin/arm64 -p:RoslynPropsFile="../../../netcore/roslyn/packages/microsoft.net.compilers.toolset/3.1.0-beta3-19213-02/build/Microsoft.Net.Compilers.Toolset.props" System.Private.CoreLib.csproj`

This errors out in Roslyn, with no more detail than `/tmp/mono/netcore/roslyn/packages/microsoft.net.compilers.toolset/3.1.0-beta3-19213-02/tasks/netcoreapp2.1/Microsoft.CSharp.Core.targets(58,5): error MSB6006: "csc.dll" exited with code 139. [/tmp/mono/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]`

Using all the most bleeding edge things - dotnet 3.0.100-preview5-011568, Roslyn 3.1.0-beta3-19213-02, on Ubuntu 16.04 on AMD Opteron A1170 (SoftIron Overdrive 3000)

Example failure on https://dev.azure.com/dnceng/public/_build/results?buildId=194840

[msbuild.binlog.zip](https://github.com/dotnet/coreclr/files/3202924/msbuild.binlog.zip)

**Comment by RussKeldorph** [comment]
@jaredpar

**Comment by RussKeldorph** [comment]
@directhex Could you try preview6 and, if it still crashes, could you see if you can gather a crashdump by setting the following before the build?  That might be the fastest way for us to start investigating.

`export COMPlus_DbgEnableMiniDump=1`

FYI: https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md#configurationpolicy

@mikem8361 @agocke

**Comment by BruceForstall** [comment]
Stale bug; closing.
