### ISSUE TITLE
WPF Applications crashing when loading DWrite

### ISSUE THREAD

**Issue by rladuca** [dotnet/coreclr#24705]
* .NET Core Version: 3.0.100-preview6-012012, regression from preview5, exact build that regresses unknown at this time.
* Windows version: N/A
* Does the bug reproduce also in WPF for .NET Framework 4.8?:No

 
 
 **Problem description:**
 When a WPF application loads DirectWriteForwarder, the module constructor attempts to load DirectWrite and instantiate the appropriate factory for use with font rendering.  In this build, the invocation of the creation function for the factory fails with an invalid cast HResult.

The offending function is in Factory,cpp on line 122 (pasted here as this source is not currently available):
```c#
  __declspec(noinline) void Factory::Initialize(
                                                 FactoryType factoryType
                                                 )
    {
        IUnknown* factoryTemp;
        DWRITECREATEFACTORY pfnDWriteCreateFactory = (DWRITECREATEFACTORY)GetDWriteCreateFactoryFunctionPointer();

        HRESULT hr = (*pfnDWriteCreateFactory)(
            DWriteTypeConverter::Convert(factoryType),
            (REFIID)(*(_guidForIDWriteFactory->Value)),
            &factoryTemp
            );
        
        ConvertHresultToException(hr, "Factory::Initialize");

        _pFactory = (IDWriteFactory*)factoryTemp;
    }
```
 **Actual behavior:** Invalid cast exception.
 
 **Expected behavior:** DirectWrite is initialized.
 
 **Minimal repro:** https://github.com/rladuca/DWriteIssue

@dotnet/wpf-developers

**Comment by jkotas** [comment]
> Shouldn't GUID be `CORINFO_FLG_CUSTOMLAYOUT`?

Yes, it should.

This is regression introduced by https://github.com/dotnet/coreclr/pull/23013/ . Before this change, `pEEClassLayoutInfoOut->SetHasExplicitSize(TRUE)` got called for this struct that in turn set the custom layout flag. The `SetHasExplicitSize(TRUE)` call was delete in this change with no replacement.

Note that the bug repros only with optimizations on. You have to turn off tiered JITing; or run the repro in a loop; to see it.

@jkoritzinsky Could you please take a look?

cc @AaronRobinsonMSFT @jeffschwMSFT

**Comment by DotNetAppCompatFeiWang** [comment]
@dotnet-actwx-bot  FYI
