### ISSUE TITLE
Jit Generic typeof branch elimination

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#2473]
This [comment](https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/src/System/Numerics/Vector.cs#L14-L20) in `System.Numeric.Vectors` suggests that as `typeof(T)` is a JIT time constant all the if branches will be eliminated.

>     * PATTERN:
    *    if (typeof(T) == typeof(Int32)) { ... }
    *    else if (typeof(T) == typeof(Single)) { ... }
    * EXPLANATION:
    *    At runtime, each instantiation of Vector<T> will be type-specific, and each of these typeof blocks will be eliminated,
    *    as typeof(T) is a (JIT) compile-time constant for each instantiation. This design was chosen to eliminate any overhead from
    *    delegates and other patterns.

However this does not appear to be the case when testing as the Generic function with `typeof(T) ==` tests is an order of magnitude slower than a function without the if tests; also the generic casting could be eliminated at Jit time ([again same pattern as Vectors](https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/src/System/Numerics/Vector.cs#L387)):

https://gist.github.com/benaadams/c6c109982f50c6f69af2#gistcomment-1657847

              Method |     AvrTime |    StdDev |           op/s |
-------------------- |------------ |---------- |--------------- |
         NoBranching |   1.1020 ns | 0.0109 ns | 907,486,211.81 |
     NoBranchingCast |   2.5056 ns | 0.0685 ns | 399,389,638.69 |
 GenericTypeOfObject |  39.3704 ns | 0.7175 ns |  25,408,031.54 |
       GenericTypeOfPostCast |  61.0448 ns | 1.4029 ns |  16,389,697.19 |
 GenericTypeOfTyped |  95.7968 ns | 1.5708 ns |  10,441,515.63 |

**Comment by mikedn** [comment]
I don't understand what your sample code has to do with the pattern used by `Vector<T>`. In your code `T` is not a value type.

**Comment by benaadams** [comment]
Can the same optimization not be applied to reference types? Have use case for both. 

Reference types: https://github.com/aspnet/HttpAbstractions/issues/522

Value types: https://github.com/dotnet/coreclr/issues/2430#issuecomment-166618789

**Comment by benaadams** [comment]
However it doesn't look like it works with struct valuetypes either

https://gist.github.com/benaadams/fb0493aefe84be42da0f

                Method |     AvrTime |    StdDev |           op/s |
---------------------- |------------ |---------- |--------------- |
           NoBranching |   8.7080 ns | 0.1631 ns | 114,876,223.77 |
       NoBranchingCast |  10.0584 ns | 0.0195 ns |  99,419,999.74 |
   GenericTypeOfObject |  72.7640 ns | 1.3407 ns |  13,747,635.93 |
 GenericTypeOfPostCast |  71.1234 ns | 1.3011 ns |  14,064,570.74 |
    GenericTypeOfTyped |  56.9035 ns | 0.1155 ns |  17,573,669.87 |

**Comment by benaadams** [comment]
Changing test to struct have some fields

**Comment by mikedn** [comment]
> Can the same optimization not be applied to reference types? Have use case for both.

It could work (I haven't checked) if the method is inlined. Otherwise it only works for value types because in the case of value types type parameters the generated code is specialized for a particular value type.

> Reference types: aspnet/HttpAbstractions#522

That design seems a bit peculiar to me but I'm not really familiar with the code. Anyway, a generic version can still be useful because it avoids `Type` object creation.

> Value types: #2430 (comment)

As mentioned in that thread what's really needed is a `IsBlittable` type property. Such a property can be simulated to an extent by using a bunch of if checks to detect primitive types but primitive types are only a small subset of blittable types so it's not useful. Besides, such if checks may result in worse code generation if the `T` is a reference type.

**Comment by benaadams** [comment]
> It could work (I haven't checked) if the method is inlined.

Nice one! It does :+1:  Results here https://gist.github.com/benaadams/c6c109982f50c6f69af2#gistcomment-1657847

Question on whether `AggressiveInlining` works across assemblies, I hope so.

**Comment by mikedn** [comment]
> Question on whether  AggressiveInlining  works across assemblies, I hope so.

In general inlining works across assemblies even without AggresiveInlining. Otherwise trivial things like getting the `Count` of a `List<T>` would be pretty heavy. Still, there may be scenarios where cross assembly inlining is blocked - ReadyToRun for example.

**Comment by benaadams** [comment]
So close... but alas can't in-line a virtual or interface method only a concrete one. 

So a derived generic method can't be "unwrapped" and jitted to a branchless version but will remain as the shared code version.
