### ISSUE TITLE
No usable version of the libssl was found (openssl 1.1.1b)

### ISSUE THREAD

**Issue by s0dy** [dotnet/coreclr#24757]
I get a message "No usable version of the libssl was found" when I run the build.sh (Exherbo linux)

`
/usr/x86_64-pc-linux-gnu/lib/libssl.so.1.1* 
`
`
/usr/x86_64-pc-linux-gnu/lib/libssl.so -> libssl.so.1.1
`

I launched two containers that were offered in the documentation to see the libraries used

Alpine container
`
/usr/lib/libssl.so -> libssl.so.1.0.0
`
`
/usr/lib/libssl.so.1.0.0 -> ../../lib/libssl.so.1.0.0
`

Ubuntu container
`
libssl.so -> /lib/x86_64-linux-gnu/libssl.so.1.0.0
`

I thought it was now possible to compile with openssl 1.1.1. If so, how should you do it?

**Comment by jkotas** [comment]
This error message comes from here: https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Security.Cryptography.Native/opensslshim.c#L84

The logic that loads libssl is right above it. You should cross-check it with your distro (e.g. copy & paste it into a small standalone program and see where it does not work). 

Also, you can try experimenting with setting `CLR_OPENSSL_VERSION_OVERRIDE` environment variable.

**Comment by janvorli** [comment]
I guess this issue is due to the dotnet cli version used for building coreclr. Until a couple of days ago, we were using a 2.1.503 version that didn't have support for openssl1.1.
@s0dy can you please sync to the latest master and try again? If the issue is due to what I've mentioned, it should work for you now as we've moved to a 3.0 version that supports openssl 1.1.

**Comment by embix** [comment]
Using `CLR_OPENSSL_VERSION_OVERRIDE ="1.1"` I get 

```
Cannot get required symbol CRYPTO_add_lock from libssl
```

when building `msbuild-16.0.461.62831` with `build.sh` which fetches coreclr as dependency.

I use openssl-1.1.1d. If I don't set `CLR_OPENSSL_VERSION_OVERRIDE ` at all I get 

```
No usable version of the libssl was found
```

**Comment by janvorli** [comment]
cc: @bartonjs -  any idea why the CRYPTO_add_lock would be missing from openssl-1.1.1d?

**Comment by embix** [comment]
My current CRYPTO exports:

```
nm -D /usr/lib/libssl.so.1.1 |grep CRYPTO
                 U CRYPTO_clear_free
                 U CRYPTO_dup_ex_data
                 U CRYPTO_free
                 U CRYPTO_free_ex_data
                 U CRYPTO_get_ex_data
                 U CRYPTO_get_ex_new_index
                 U CRYPTO_malloc
                 U CRYPTO_memcmp
                 U CRYPTO_mem_ctrl
                 U CRYPTO_memdup
                 U CRYPTO_new_ex_data
                 U CRYPTO_realloc
                 U CRYPTO_secure_free
                 U CRYPTO_secure_zalloc
                 U CRYPTO_set_ex_data
                 U CRYPTO_strdup
                 U CRYPTO_strndup
                 U CRYPTO_THREAD_lock_free
                 U CRYPTO_THREAD_lock_new
                 U CRYPTO_THREAD_read_lock
                 U CRYPTO_THREAD_run_once
                 U CRYPTO_THREAD_unlock
                 U CRYPTO_THREAD_write_lock
                 U CRYPTO_zalloc
```

Build configuration was:
```
$ ./config --prefix=/usr         \
         --openssldir=/etc/ssl \
         --libdir=lib          \
         shared                \
         zlib-dynamic
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 1.1.1d (0x1010104fL) for linux-x86_64
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile
...
```
I created [a gist from `$ perl configdata.pm --dump`](https://gist.github.com/embix/84ab4d768f59ec91d9c35bdaff0e81a1), just in case. HTH
