### ISSUE TITLE
[ARM64] Missing target process's ModuleLoad Event

### ISSUE THREAD

**Issue by WardenGnaw** [dotnet/coreclr#24766]
Runtime version: _dotnet-runtime-3.0.0-preview5-27626-15_

When debugging a target process in ARM64, the process only sends a ModuleLoad event for System.Private.CoreLib.dll. There is no event for the target process's own dll. 

Even if the target process is a infinite loop and after the module load of SPC, the DBI will send a ProcessExited event and stop running when it should still be running.

**Comment by tommcdon** [comment]
@hoyosjs is investigating

**Comment by hoyosjs** [comment]
Fixed by #25089
