### ISSUE TITLE
[Question] Another Build System

### ISSUE THREAD

**Issue by redradist** [dotnet/coreclr#24789]
MSBuild is not a perfect Build Tool ...
Unfortunately it is not easy to create custom target and extend Build Tool with plugin ...

Do you consider a switch at least to other Build System ?

On other hand there is exist Gradle. It is very extensible Build System and very easily extended with custom plugin.
There is an open issue https://github.com/gradle/gradle/issues/1428 which is relates to support of C# and .sln

I know there are people which is annoying that Gradle is written on JVM, but at the end of the day it s just a technology, and does not matter on which language it is built in ... Matter only quality of the technology ...

Do you consider possibility to switch or at least add plugin support to Gradle for C# language ?

P.S.: This question is also asked on MSBuild https://github.com/microsoft/msbuild/issues/4404

**Comment by svick** [comment]
What exactly do you find hard about extending MSBuild when compared with Gradle? What makes you think that switching to a completely separate tool would be easier than improving the exiting one?

**Comment by danmosemsft** [comment]
Closing this in favor of the duplicate that is in the more appropriate repo.

**Comment by danmosemsft** [comment]
Amongst other problems, Gradle would require a new prereq (or two)

**Comment by redradist** [comment]
@svick You wrote:
> What exactly do you find hard about extending MSBuild when compared with Gradle? What makes you think that switching to a completely separate tool would be easier than improving the exiting one?

What is hard !? Okay, how to add custom target without adding feature to MSBuild and recompile it ?
Gradle made it a lot easier, you can write in declarative way and also in imperative way ... It much more flexible than MSBuild ever be (:
