### ISSUE TITLE
All ci jobs are failing with TF400677: Host does not exist.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#24787]
https://dev.azure.com/dnceng/public/_build?definitionId=228&_a=summary:
Save product build as pipeline artifact:
```
##[section]Starting: Save product build as pipeline artifact
==============================================================================
Task         : Publish Pipeline Artifact
Description  : Publish Pipeline Artifact
Version      : 0.139.0
Author       : Microsoft Corporation
Help         : Publish a local directory or file as a named artifact for the current pipeline.
==============================================================================
Uploading pipeline artifact from F:\workspace\_work\1\s\bin\Product\Windows_NT.x64.Debug for build #202179
##[error]TF400677: Host b55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8 does not exist.
##[section]Finishing: Save product build as pipeline artifact
```

CoreFX/RT are working fine.

PTAL @MattGal @RussKeldorph @echesakovMSFT

**Comment by echesakovMSFT** [comment]
It could be due to this change https://github.com/microsoft/azure-pipelines-agent/pull/2225. Our builds started failing right after the PR was merged and the changes alter behavior of PublishPipelineArtifact task. 

cc: @jahsu-MSFT @TingluoHuang

I am trying to switch away from using PublishPipelineArtifact to PublishBuildArtifacts and see whether this helps to unblock CI (https://github.com/dotnet/coreclr/pull/24788)

**Comment by TingluoHuang** [comment]
@echesakovMSFT the agent PR shouldn't affect production since i haven't release a newer version agent which contains the new change.

**Comment by AaronRobinsonMSFT** [comment]
cc @elinor-fung

**Comment by jahsu-MSFT** [comment]
Do we know what's really causing ci jobs failing? (switching away from using PublishPipelineArtifact to PublishBuildArtifacts should just be a temporary approach to unblock CI builds)

**Comment by echesakovMSFT** [comment]
@dotnet/dnceng Can someone follow up on the issue and check telemetry for the failing builds (starting with https://dev.azure.com/dnceng/public/_build/results?buildId=201475)?

**Comment by MattGal** [comment]
@echesakov yes I am chatting with some AzDO folks now and we have a thread going.  Can you help confirm if you've seen this anywhere since yesterday?  It may be already resolved, but thus far I haven't found anyone already aware of it and/or with a tracking issue.

**Comment by echesakovMSFT** [comment]
This seems to be the last failure https://dev.azure.com/dnceng/public/_build/results?buildId=202501

**Comment by MattGal** [comment]
Sent summary, basically there was a server migration that didn't go super well.  Exact timestamps in the mail, I wouldn't expect this to recur (until the next server migration, then all bets are off :) )

**Comment by echesakovMSFT** [comment]
@MattGal Thanks for investigation - I am closing the issue.
