### ISSUE TITLE
Add ability to get CoreCLR version in ICLRProfiling

### ISSUE THREAD

**Issue by ww898** [dotnet/coreclr#24806]
It would be great showing real CoreCLR version in attach UI where list of ready to attach processes contains runtime information such as type and version. I think that `ICLRProfiling` (may be `ICLRProfiling2`) is good place for that.

**Comment by RussKeldorph** [comment]
@noahfalk

**Comment by tommcdon** [comment]
cc @davmason

**Comment by davmason** [comment]
@ww898 Can you tell me what problem you're trying to solve? As I mentioned in the other issue ICLRProfiling is removed starting with 3.0 preview 6 so adding methods to it won't be possible.

**Comment by ww898** [comment]
@davmason Well I understand, `ICLRProfiling` is obsolete in preview6. Well, my question is changed: is it possible to add ability in future to receive the CoreCLR version through IPC protocol? The target of my question is UX because every process has it's own CoreCLR version and this information can be important for user.
