### ISSUE TITLE
AF: IsEnabled() in tracevalidation\\inducedgc test

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#24807]
```
Assert failure(PID 3928 [0x00000f58], Thread: 5200 [0x1450]): IsEnabled()

CORECLR! GetCLRRuntimeHost + 0xE2F83 (0x00007ffb`39c26733)
CORECLR! GetCLRRuntimeHost + 0x651F22 (0x00007ffb`3a1956d2)
CORECLR! GetCLRRuntimeHost + 0x651B4B (0x00007ffb`3a1952fb)
CORECLR! GetCLRRuntimeHost + 0xA4027 (0x00007ffb`39be77d7)
CORECLR! GetCLRRuntimeHost + 0xA40F7 (0x00007ffb`39be78a7)
CORECLR! GetCLRRuntimeHost + 0xA6A25 (0x00007ffb`39bea1d5)
CORECLR! GetCLRRuntimeHost + 0xA6D53 (0x00007ffb`39bea503)
CORECLR! GetCLRRuntimeHost + 0xA4227 (0x00007ffb`39be79d7)
CORECLR! GetCLRRuntimeHost + 0xA4330 (0x00007ffb`39be7ae0)
CORECLR! GetCLRRuntimeHost + 0x651AD4 (0x00007ffb`3a195284)
    File: f:\\workspace\\_work\\1\\s\\src\\vm\\eventtrace.cpp Line: 7481
    Image: C:\\dotnetbuild\\work\\1115ea7a-695a-46da-87f1-de435a13b3fc\\Payload\\CoreRun.exe


Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\1115ea7a-695a-46da-87f1-de435a13b3fc\\Work\\1bb4c00c-c172-42fe-a37d-fe5a1ca7ba33\\Exec\\tracing\\tracevalidation\\Reports\\tracing.tracevalidation\\inducedgc\\inducedgc\\inducedgc.output.txt
```

**Comment by jkotas** [comment]
Failed in https://github.com/dotnet/coreclr/pull/24797 on Test Pri0 Windows_NT x64_checked

**Comment by danmosemsft** [comment]
Just curious, would the magic that generates this stack give function names if the PDB was found? Seems pretty unlikely someone is going to find the offsets useful. Except possibly comparing another similar crash by eye.

**Comment by jkotas** [comment]
> would the magic that generates this stack give function names if the PDB was found?

Yes

**Comment by danmosemsft** [comment]
Is there an infrastructure work item tracking putting that PDB in place so these reports are more useful?

**Comment by hoyosjs** [comment]
@sywhang @kouvel @dotnet/dotnet-diag

**Comment by hoyosjs** [comment]
https://github.com/jkotas/coreclr/blob/baa1d3a3e89cd8b7a3611e5b709ceb0daef53af4/src/vm/eventtrace.cpp#L7481

**Comment by hoyosjs** [comment]
Looks like IsEnabled is returning false because `ETW_TRACING_CATEGORY_ENABLED` returns false. @sywhang, not sure if this is related to the initialization delay or something like it.

**Comment by kouvel** [comment]
I should probably remove those asserts, as the tracing can be stopped at any time
