### ISSUE TITLE
IBC Training Against System.Private.CoreLib is Broken

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#24813]
As of #24625, IBC training against System.Private.CoreLib does not produce any data.  I've confirmed this by performing a ```git bisect``` against CoreCLR sources using the training infrastructure.

It appears that no IBC files are written to disk after shutdown of the process.

**Comment by brianrob** [comment]
@jkotas, can you please take a look?  If you like I can provide instructions offline for how to repro this using the training infrastructure on your local machine.

**Comment by jkotas** [comment]
I will take a look.

**Comment by brianrob** [comment]
Thanks @jkotas!
