### ISSUE TITLE
[X86/Linux] Fail to disable JIT when enabled Interpreter

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/coreclr#24824]
Hi,

Just follow @kangaroo porting work https://github.com/dotnet/coreclr/pull/1292#issuecomment-125688792 enabled interpreter and still tracking `JitFunctionTrace` to see whether or not disable JIT totally:

```
export COMPlus_DumpInterpreterStubs=1
export COMPlus_Interpret=*
export COMPlus_InterpreterPrintPostMortem=1
export COMPlus_InterpreterDoLoopMethods=1
export COMPlus_TieredCompilation=1
export COMPlus_JITMinOpts=1
export COMPlus_ZapDisable=1
export COMPlus_JitFunctionTrace=1
```

But it is still `Start Jitting` in the `Jitted Entry` when such `Method` doesn't meet the `IsEligibleForTieredCompilation` condition:

```
...
Generating interpretation stub (# 5 = 0x5, hash = 0x69bf8d7c) for <>c:.ctor.
START 5, <>c:.ctor()
     0: ldarg.0
   0x1: call
  Returning to method <>c:.ctor(), stub num 5.
   0x6: ret
DONE 5, <>c:.ctor()
  Returning to method <>c:.cctor(), stub num 4.
   0x5: stsfld
   0xa: ret
DONE 4, <>c:.cctor()
   0xa: dup
   0xb: brtrue.s
   0xd: pop
   0xe: ldsfld
  0x13: ldftn
  0x19: newobj
{ Start Jitting System.MulticastDelegate:CtorClosed(ref,long):this (MethodHash=ad3a8451)
} Jitted Entry 149 at 00007f7a`601cd0a0 method System.MulticastDelegate:CtorClosed(ref,long):this size 0000006f
  Returning to method System.Console:get_Out():class, stub num 3.
  0x1e: dup
  0x1f: stsfld
  0x24: call
{ Start Jitting DomainBoundILStubClass:IL_STUB_InstantiatingStub(byref,ref):ref (MethodHash=294d3ab2)
} Jitted Entry 14a at 00007f7a`601cd530 method DomainBoundILStubClass:IL_STUB_InstantiatingStub(byref,ref):ref size 0000003f
Generating interpretation stub (# 6 = 0x6, hash = 0xbf685470) for System.Console:EnsureInitialized.
START 6, System.Console:EnsureInitialized(byref,class):class
     0: ldarg.0
   0x1: ldsflda
...
```

Hacking JIT by commenting `CompileMethodWithEtwWrapper` to force disable JIT, but, of course, fail to initialize:

```
diff --git a/src/vm/jitinterface.cpp b/src/vm/jitinterface.cpp
index 502b5ada13..87de5f0e9e 100644
--- a/src/vm/jitinterface.cpp
+++ b/src/vm/jitinterface.cpp
@@ -12158,7 +12158,8 @@ CorJitResult invokeCompileMethodHelper(EEJitManager *jitMgr,
             }
         }
     }
-    
+
+#if 0
     if (FAILED(ret) && jitMgr->m_jit)
     {
         ret = CompileMethodWithEtwWrapper(jitMgr, 
@@ -12168,6 +12169,7 @@ CorJitResult invokeCompileMethodHelper(EEJitManager *jitMgr,
                                           nativeEntry,
                                           nativeSizeOfCode);
     }
+#endif
 
     if (interpreterFallback == true)
     {
```

OpenJDK is able to just enable interpreter:

```
java -Xint
```

or just enable JIT compilers:

```
java -Xcomp
```

or mixed:

```
java -Xmixed
```

How to disable JIT when enabled Interpreter for corerun?  Please give me some hint.

Thanks,
Leslie Zhai

**Comment by AndyAyersMS** [comment]
The logic around when to interpret is currently tied into tiered compilation, so I think your will need to modify the logic.

If you change `TieredCompilationManager::GetJitFlags` to stop setting `CORJIT_FLAG_MAKEFINALCODE` and then set `COMPlus_InterpreterJITThreshold` to a very large number, you should be able to stop jitting.

**Comment by xiangzhai** [comment]
Hi @AndyAyersMS 

Thanks for your kind response!

> The logic around when to interpret is currently tied into tiered compilation, so I think your will need to modify the logic.
> 
> If you change `TieredCompilationManager::GetJitFlags` to stop setting `CORJIT_FLAG_MAKEFINALCODE` and then set `COMPlus_InterpreterJITThreshold` to a very large number, you should be able to stop jitting.

I will try.

Thanks,
Leslie Zhai
