### ISSUE TITLE
build failed with vs2019 16.1.1 and windows sdk 10.0.18362

### ISSUE THREAD

**Issue by smartmaster** [dotnet/coreclr#24828]
failed to cmake \tests\src\Interop\WinRT\NativeComponent, the output is 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

BUILDTEST: Commencing build of native test components for x64/Debug
BUILDTEST: Using environment: "e:\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\\..\..\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.1.1
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.
CMake Deprecation Warning at src/Interop/PInvoke/DllImportPath/CMakeLists.txt:11 (cmake_policy):
  The OLD behavior for policy CMP0037 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Using Windows SDK version 10.0.18362.0 for WinRT interop tests.
CMake Error at src/Interop/WinRT/NativeComponent/CMakeLists.txt:42 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.


-- Configuring incomplete, errors occurred!
See also "D:/git-repo/r/bin/tests/obj/Windows_NT.x64.Debug/Native/CMakeFiles/CMakeOutput.log".
BUILDTEST: Failed to generate test native component build project

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jkoritzinsky** [comment]
Can you check this path on your machine, `C:/Program Files/Windows Kits/10/References/10.0.18362/windows.foundation.foundationcontract/`, for me? It looks like there's at least some component of the Windows 10 SDK that didn't get installed.

Looks like I need to add more diagnostics here in the CMake file...

**Comment by smartmaster** [comment]
@jkoritzinsky 
my windows sdk installed in E volume, tree and dir command output are

~~~~~~~~~~~~~~~~~
E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract>tree . /f
Folder PATH listing for volume New Volume
Volume serial number is 54FC-578B
E:\WINDOWS KITS\10\REFERENCES\10.0.18362.0\WINDOWS.FOUNDATION.FOUNDATIONCONTRACT
└───3.0.0.0
    │   Windows.Foundation.FoundationContract.winmd
    │
    ├───de
    │       Windows.Foundation.FoundationContract.xml
    │
    ├───en
    │       Windows.Foundation.FoundationContract.xml
    │
    ├───es
    │       Windows.Foundation.FoundationContract.xml
    │
    ├───fr
    │       Windows.Foundation.FoundationContract.xml
    │
    ├───it
    │       Windows.Foundation.FoundationContract.xml
    │
    ├───jp
    │       Windows.Foundation.FoundationContract.xml
    │
    ├───ko
    │       Windows.Foundation.FoundationContract.xml
    │
    ├───ru
    │       Windows.Foundation.FoundationContract.xml
    │
    ├───zh-hans
    │       Windows.Foundation.FoundationContract.xml
    │
    └───zh-hant
            Windows.Foundation.FoundationContract.xml
~~~~~~~~~~~~~~~~~


E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract>dir /s /a
 Volume in drive E is New Volume
 Volume Serial Number is 54FC-578B

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract

05/27/2019  12:44 AM    <DIR>          .
05/27/2019  12:44 AM    <DIR>          ..
05/27/2019  12:47 AM    <DIR>          3.0.0.0
               0 File(s)              0 bytes

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0

05/27/2019  12:47 AM    <DIR>          .
05/27/2019  12:47 AM    <DIR>          ..
05/27/2019  12:47 AM    <DIR>          de
05/27/2019  12:45 AM    <DIR>          en
05/27/2019  12:47 AM    <DIR>          es
05/27/2019  12:47 AM    <DIR>          fr
05/27/2019  12:47 AM    <DIR>          it
05/27/2019  12:47 AM    <DIR>          jp
05/27/2019  12:47 AM    <DIR>          ko
05/27/2019  12:47 AM    <DIR>          ru
03/18/2019  01:38 PM            24,064 Windows.Foundation.FoundationContract.winmd
05/27/2019  12:47 AM    <DIR>          zh-hans
05/27/2019  12:47 AM    <DIR>          zh-hant
               1 File(s)         24,064 bytes

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\de

05/27/2019  12:47 AM    <DIR>          .
05/27/2019  12:47 AM    <DIR>          ..
09/08/2018  05:14 PM           110,818 Windows.Foundation.FoundationContract.xml
               1 File(s)        110,818 bytes

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\en

05/27/2019  12:45 AM    <DIR>          .
05/27/2019  12:45 AM    <DIR>          ..
09/08/2018  05:14 PM           103,778 Windows.Foundation.FoundationContract.xml
               1 File(s)        103,778 bytes

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\es

05/27/2019  12:47 AM    <DIR>          .
05/27/2019  12:47 AM    <DIR>          ..
09/08/2018  05:14 PM           109,225 Windows.Foundation.FoundationContract.xml
               1 File(s)        109,225 bytes

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\fr

05/27/2019  12:47 AM    <DIR>          .
05/27/2019  12:47 AM    <DIR>          ..
09/08/2018  05:14 PM           109,223 Windows.Foundation.FoundationContract.xml
               1 File(s)        109,223 bytes

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\it

05/27/2019  12:47 AM    <DIR>          .
05/27/2019  12:47 AM    <DIR>          ..
09/08/2018  05:14 PM           108,512 Windows.Foundation.FoundationContract.xml
               1 File(s)        108,512 bytes

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\jp

05/27/2019  12:47 AM    <DIR>          .
05/27/2019  12:47 AM    <DIR>          ..
09/08/2018  05:14 PM           113,991 Windows.Foundation.FoundationContract.xml
               1 File(s)        113,991 bytes

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\ko

05/27/2019  12:47 AM    <DIR>          .
05/27/2019  12:47 AM    <DIR>          ..
09/08/2018  05:14 PM           109,260 Windows.Foundation.FoundationContract.xml
               1 File(s)        109,260 bytes

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\ru

05/27/2019  12:47 AM    <DIR>          .
05/27/2019  12:47 AM    <DIR>          ..
09/08/2018  05:14 PM           140,385 Windows.Foundation.FoundationContract.xml
               1 File(s)        140,385 bytes

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\zh-hans

05/27/2019  12:47 AM    <DIR>          .
05/27/2019  12:47 AM    <DIR>          ..
09/08/2018  05:14 PM            95,256 Windows.Foundation.FoundationContract.xml
               1 File(s)         95,256 bytes

 Directory of E:\Windows Kits\10\References\10.0.18362.0\Windows.Foundation.FoundationContract\3.0.0.0\zh-hant

05/27/2019  12:47 AM    <DIR>          .
05/27/2019  12:47 AM    <DIR>          ..
09/08/2018  05:14 PM            97,102 Windows.Foundation.FoundationContract.xml
               1 File(s)         97,102 bytes

     Total Files Listed:
              11 File(s)      1,121,614 bytes
              35 Dir(s)  400,160,858,112 bytes free

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by smartmaster** [comment]
@jkoritzinsky 
i created a junction by 

mklink /j "C:\Program Files (x86)\Windows Kits\10" "E:\Windows Kits\10" 

it looks fine till now. if you can provide a fix, it would be better.

thanks & regards.
