### ISSUE TITLE
Several tracing test failures in official build on Linux/ARM, Linux/ARM64 and Win7

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#24839]
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190529.1/workItem/PayloadGroup0

@sywhang @jorive @noahfalk @dotnet/dotnet-diag

**Comment by RussKeldorph** [comment]
Another view if you prefer:
https://dev.azure.com/dnceng/internal/_build/results?buildId=204169&view=ms.vss-test-web.build-test-results-tab

**Comment by tommcdon** [comment]
@jorive can you take a look?

**Comment by tommcdon** [comment]
@hoyojs can you also help out?

**Comment by RussKeldorph** [comment]
@hoyosjs

**Comment by jorive** [comment]
Taking a look.

**Comment by RussKeldorph** [comment]
These are still taking down official builds.  @dotnet/dotnet-diag Is it reasonable to disable them if they can't be fixed by EOD?

https://mc.dot.net/#/user/dotnet-helix-bot/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190531.1/workItem/PayloadGroup0

**Comment by jorive** [comment]
We are working on fixes for `EventPipe::Disable` that should make this tests pass. Would you prefer if we disable the tests first?

**Comment by RussKeldorph** [comment]
@jorive, actually, I would strongly prefer a fix or disabling before noon.  Otherwise, we'll need to port the fix to the `release/3.0` branch.  Not the end of the world, and if you plan to *fix* as opposed to just disabling the tests in Preview6 anyway, it's ok to wait for the fix--whenever it's available.

**Comment by RussKeldorph** [comment]
This was incorrectly closed per comment in #24862

**Comment by tommcdon** [comment]
Fixed in release/3.0 on #24924
