### ISSUE TITLE
Compile runtime with -fvisibility=hidden

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#2484]
-fvisibility=hidden enables several important optimizations:
- Access to static variables will be faster, without GOT indirection. We can get rid of PREPARE_EXTERNAL_VAR on x64 and instead access the static variables directly, like on Windows.
- Access to current thread object will be faster. it is known bottleneck in allocation helpers.

**Comment by jkotas** [comment]
cc @sergiy-k @janvorli 

More details at https://gcc.gnu.org/wiki/Visibility

BTW: I have done it for CoreRT in https://github.com/dotnet/corert/pull/571 (it actually started as a fix to a register corruption in write barrier helper).

**Comment by jkotas** [comment]
Here is the expected saving for __thread variable access:

Without -fvisibily=hidden (current):

```
       data16
       leaq   p@TLSGD(%rip), %rdi
       data16
       data16
       rex64
       callq  __tls_get_addr@PLT
       movq   (%rax), %rax
```

With -fvisibility=hidden:

```
       leaq   p@TLSLD(%rip), %rdi
       callq  __tls_get_addr@PLT
       movq   p@DTPOFF(%rax), %rax
```

**Comment by tzwlai** [comment]
@sergiy-k, assigning this to you for now.

**Comment by gkhanna79** [comment]
Moving to 1.2.0.

**Comment by gkhanna79** [comment]
@janvorli Could you PTAL?

**Comment by janvorli** [comment]
I've tried to add that option to coreclr build and it results in no symbols exported from the shared libraries at all, even though we have the linker script that explicitly lists functions that should be visible. It looks like the linker script is just a post-filter. So we would also need to add visibility attribute to each function we export.

**Comment by janvorli** [comment]
@fiigii is working on that: https://github.com/dotnet/coreclr/pull/14725

**Comment by RussKeldorph** [comment]
Assuming this isn't happening for 2.1

**Comment by jkotas** [comment]
@kasper3 Are you planning to work on this one? I can assign it to you for clarity if you would like.

**Comment by kasper3** [comment]
@jkotas, sure, does it involve getting rid of `PREPARE_EXTERNAL_VAR`? I couldn't find `PREPARE_EXTERNAL_MACRO` in the code, is that something else?

**Comment by jkotas** [comment]
Right, that is an optimization that this can enable. I would do the follow up optimizations like this one in follow up PRs. The first PR should be to just make the runtime compile and work with this option.

**Comment by jkotas** [comment]
I have sent you collaborator invite so that I can assign the issue you. Accepting used to set the "Watch" setting for the repo to everything. You may want to switch it back to "Not Watching - only when I am mentioned".
