### ISSUE TITLE
Collection<T>.AddRange should validate its parameters

### ISSUE THREAD

**Issue by justinvp** [dotnet/coreclr#24885]
I missed this in #23166. Current it's defined as:

https://github.com/dotnet/coreclr/blob/b8d5b7b760f64d39e00554189ea0e5c66ed6bd62/src/System.Private.CoreLib/shared/System/Collections/ObjectModel/Collection.cs#L72

But it should be something like:

```c#
public void AddRange(IEnumerable<T> collection)
{
    if (items.IsReadOnly)
    {
        ThrowHelper.ThrowNotSupportedException(ExceptionResource.NotSupported_ReadOnlyCollection);
    }

    if (collection == null)
    {
        ThrowHelper.ThrowArgumentNullException(ExceptionArgument.collection);
    }

    int index = items.Count;
    InsertItemsRange(index, collection!); // TODO-NULLABLE: Remove ! when [DoesNotReturn] respected
}
```

**Comment by safern** [comment]
This APIs got deleted because of: https://github.com/dotnet/corefx/issues/38085 -- so this should be considered when adding them back again as part of: https://github.com/dotnet/corefx/issues/10752
