### ISSUE TITLE
JIT compilation compitible with .NET Framework 4.x ?

### ISSUE THREAD

**Issue by LiangChow** [dotnet/coreclr#2489]
The CoreCLR ``corinfo.h`` & ``corjit.h`` compatible with .NET Framework 4.x or only support .NET Framework 4.6 ? I tried on FW 4.0 doesn't work.

**Comment by jkotas** [comment]
`corinfo.h`  &  `corjit.h` are internal unstable frequently changing interfaces. No compatibility guarantees accross different runtimes or runtime versions.

**Comment by LiangChow** [comment]
Thank you for your response.
