### ISSUE TITLE
Perf: Using Any() on a Collection

### ISSUE THREAD

**Issue by RealDotNetDave** [dotnet/coreclr#24907]
I have done testing on performance between Clr 4.7.2 and Core 3. I have found a performance issue with using Any() on a collection. Below is the test code, the collection has 10,000 items in it.

public bool TestCollectionValidationWithAny01()
{
    return _fakePersonFixedCollection.Any();
}

The performance results are:
'COLLECTION HAS ITEMS: With Any()' | X64 | Clr | 6,213.0 ns
'COLLECTION HAS ITEMS: With Any()' | X64 | Core | 13,957.9 ns

BenchmarkDotNet Configuration:
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17763.503 (1809/October2018Update/Redstone5)
Unknown processor
.NET Core SDK=3.0.100-preview5-011568
  [Host]     : .NET Core 3.0.0-preview5-27626-15 (CoreCLR 4.6.27622.75, CoreFX 4.700.19.22408), 64bit RyuJIT
  Job-DPAAVV : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.8.3801.0
  Job-ZMVORE : .NET Core 3.0.0-preview5-27626-15 (CoreCLR 4.6.27622.75, CoreFX 4.700.19.22408), 64bit RyuJIT
OutlierMode=All  InvocationCount=1  IterationCount=25  
MinIterationCount=50  MinWarmupIterationCount=10  UnrollFactor=1

**Comment by stephentoub** [comment]
What kind of collection? How are you invoking the benchmark? Please share the whole repro. Thanks.

**Comment by billwert** [comment]
I'm not able to repro this.

|  Method |  Job | Runtime | length |     Mean |     Error |    StdDev | Ratio |
|-------- |----- |-------- |------- |---------:|----------:|----------:|------:|
| IntList |  Clr |     Clr |     10 | 12.97 ns | 0.0225 ns | 0.0188 ns |  1.00 |
| IntList | Core |    Core |     10 | 11.05 ns | 0.0552 ns | 0.0490 ns |  0.85 |
|         |      |         |        |          |           |           |       |
| ObjList |  Clr |     Clr |     10 | 15.06 ns | 0.0134 ns | 0.0112 ns |  1.00 |
| ObjList | Core |    Core |     10 | 13.97 ns | 0.0661 ns | 0.0618 ns |  0.93 |

```
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17763.503 (1809/October2018Update/Redstone5)
Intel Core i7-7700K CPU 4.20GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100-preview5-011568
  [Host] : .NET Core 3.0.0-preview5-27626-15 (CoreCLR 4.6.27622.75, CoreFX 4.700.19.22408), 64bit RyuJIT
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3416.0
  Core   : .NET Core 3.0.0-preview5-27626-15 (CoreCLR 4.6.27622.75, CoreFX 4.700.19.22408), 64bit RyuJIT
```

(I tried other lengths, got the same answer, and omitted them. As you'd expect.)

[Code](https://gist.github.com/billwert/999d8886238819b79c1c08a1f2e8962d)

**Comment by RealDotNetDave** [comment]
The collection is a List<> of a business object that holds person data. For this test, there are 10,000 items in this collection. I plan to do smaller ones, but for now, that is what I used for my performance book I released a few months ago.

The repository is here: https://dev.azure.com/RockYourCode/Code%20and%20App%20Performance%20for%20Microsoft%20.NET
Shoot me your username for Azure DevOps and I will give you access.

**Comment by billwert** [comment]
That should be basically the same as my test.

My AzDO login is my github username @microsoft.com.

**Comment by stephentoub** [comment]
> Shoot me your username for Azure DevOps and I will give you access.

Can you just post a standalone benchmark that repros this?  Everyone in the community should be able to participate in an issue that's opened citing a problem. Thanks!

**Comment by RealDotNetDave** [comment]
I changed my tests around for collections that it tests three different sizes. As you can see below, a smaller List performs better than a large one. The reason I am using a large size of 10K is that I use to work on a contract that users could easily have a collection of this size sitting in memory in an ASP.NET site.

10K:
Clr: 3,202 ns
Core: 7,348 ns

2K:
Clr: 2,828 ns
Core: 2,595 ns

100:
Clr: 1,345 ns
Core: 1,085 ns

**Comment by stephentoub** [comment]
This is why we need to see the benchmark. I don't see how this could just be testing Enumerable.Any() on a List, as any count > 1 should be irrelevant.

**Comment by stephentoub** [comment]
This was a bug in the perf tests being used.  Closing.
