### ISSUE TITLE
Windows PGO Optimization Broken Due to #23897

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#24900]
Windows PGO optimization is broken as of #23897 per ```git bisect```.

The runs fail with ```System.Exception: Failed training for CLRx86WINmas: the last training scenario did not produce any data```.

**Comment by brianrob** [comment]
@jkoritzinsky can you please take a look?  If needed, I can provide offline instructions to reproduce/test fixes.

**Comment by jkoritzinsky** [comment]
@brianrob can you send me instructions on how to repro the issue?

**Comment by brianrob** [comment]
@jkoritzinsky, sent them to you via e-mail.
