### ISSUE TITLE
.net core 3 large object heap compaction

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/coreclr#24911]
We have a .net 4x app that we are having LOH fragmentation issues with. To work around the issue, we are now only using node-based collections.

Does .net core 3 ever compact the LOH?  Is there any way to make .net 4 compact the LOH?

**Comment by gfoidl** [comment]
See [GCSettings.LargeObjectHeapCompaction](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.gcsettings.largeobjectheapcompactionmode?view=netcore-3.0).

**Comment by Maoni0** [comment]
LOH is automatically compacted when running with (hardlimit)[https://github.com/dotnet/coreclr/pull/22180]. and yes you can also use @gfoidl mentioned which also works in core.
