### ISSUE TITLE
Guarantee devirtualization of calls to struct default interface methods.

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/coreclr#24916]
See https://github.com/dotnet/csharplang/issues/2577

It is currently illegal to write:

```csharp
interface I
{
    int a() => 1;
}    
struct S : I
{
    int b() => a() + 5; // CS0103: The name 'a' does not exist in the current context
}
```

This is apparently in order to prevent implicit boxing of the `this`.

However it seems to me that the JIT should always be able to devirtualize the call here, in the same way as it devirtualizes `Equals`, `ToString`, `GetHashCode` and `GetType`.

If so it would be useful if the JIT could guarantee this, and then C# would be able to take advantage of such a guarantee to improve the experience using DIMs with structs.

**Comment by mikedn** [comment]
> If so it would be useful if the JIT could guarantee this, and then C# would be able to take advantage of such a guarantee to improve the experience using DIMs with structs.

This doesn't sound like something that the JIT by itself can do. In general optimizing compilers do not guarantee that optimizations are performed. This needs to be discussed from a runtime perspective as it requires a certain semantic to be agreed upon and enforced.

Interfaces are reference types and required a boxed `this`. The JIT could devirtualize, inline and remove boxing. But inlining is kind of impossible to guarantee and without that you're back to boxing.

Now, if the runtime is willing to cooperate and magically produce versions of method `a()` that accept a byref `this` then maybe this could work. But that's probably quite an involved change.

**Comment by MichalStrehovsky** [comment]
It's easy to come up with a default interface method where boxing is unavoidable. Here is a useless one:

```csharp
interface I
{
    int a()
    {
        I[] foo = new I[1];

        // need a reference type `this` no matter what. need to box if it's a byref
        I[0] = this;
        I other = foo[0];

        // if `this` were a byref, updateState would update state of a boxed copy
        other.updateState();
    }

    int updateState();
}    
```

It's better to get predictable boxing at the callsite of the interface method than to get unexpected boxing somewhere else.

**Comment by YairHalberstadt** [comment]
@MichalStrehovsky

Thanks for your example. I guess things weren't as simple as I thought.

Do you think the number of cases where devirtualization wont occur is great enough that the risk of implicit boxing due to allowing structs to access DIMs is greater than the benefits of allowing them to do so?

**Comment by MichalStrehovsky** [comment]
> Do you think the number of cases where devirtualization wont occur is great enough that the risk of implicit boxing due to allowing structs to access DIMs is greater than the benefits of allowing them to do so?

Yes, that was [the C# language design meeting decision](https://github.com/dotnet/csharplang/blob/master/meetings/2017/LDM-2017-04-19.md#structs-and-default-implementations) on it.
