### ISSUE TITLE
`typeof(object).IsAssignableFrom(typeof(int*));` evaluates to true

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/coreclr#24934]
Discovered as part of https://github.com/mono/mono/pull/14733

`typeof(object).IsAssignableFrom(typeof(int*))` evaluates to true, yet `typeof(object[]).IsAssignableFrom(typeof(int*[]))` evaluates to false. The CLI standard (I.8.7.1) says "6. T is an array with rank r and element type V, and U is an array with the same rank r and element type W, and V is array-element-compatible-with W.", which the above behavior appears to be inconsistent with. 

As far as I can tell by the standard, the the first expression should evaluate to false. The `int*[]` test case and `int* y = (int*)IntPtr.Zero; object x = y;` failing to compile would both suggest the same. Once this is figured out, I'll update mono's behavior to match.

**Comment by jkotas** [comment]
> `typeof(object).IsAssignableFrom(typeof(int*))` evaluates to true

It evaluates to false in .NET Core. I guess you have tested this in .NET Framework that is missing a lot of bug fixes made in .NET Core.

This bug was fixed for .NET Core 2.0 by https://github.com/dotnet/coreclr/issues/10646

**Comment by CoffeeFlux** [comment]
Ah whoops. Thanks!
