### ISSUE TITLE
Review and update THIRD-PARTY-NOTICES.TXT for 3.0

### ISSUE THREAD

**Issue by leecow** [dotnet/coreclr#24947]
Review and update repo THIRD-PARTY-NOTICES.TXT as appropriate. Work should be completed for Preview 7.

**Comment by RussKeldorph** [comment]
@danmosemsft @jkotas @richlander Are you familiar with the process for auditing this?  How has this been done in the past, and who usually drives it?

**Comment by danmosemsft** [comment]
No. You could summarize it in an email to your team and ask whether anything seems missing.

**Comment by danmosemsft** [comment]
cc @tannergooding who will do ours

**Comment by richlander** [comment]
dotnet/coreclr and dotnet/corefx should be update to date AFAIK. I recently completed a review of our source for copyright.
