### ISSUE TITLE
[Linux / perfcollect] R2R image perf map offsets don't correspond with offsets collected in perf trace

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#24966]
I see stacks like this:

```
Name
 test.dll!unknown
+ System.Private.CoreLib.dll!unknown
|+ libcoreclr.so!CallDescrWorkerInternal
```

This is with test.dll crossgen'ed with R2R. Sometimes it says "unknown" and sometimes (often in System.Private.CoreLib), it shows an incorrect method.

test.ni.{guid}.map - these are the only methods from test.dll that show up in the perf trace, and the first two are the lowest offsets in the map:

```
00028450 147 void [test] PerfViewTierEventsTest::Main()[ReadyToRun]
000285a0 3a void [test] PerfViewTierEventsTest::Run(bool)[ReadyToRun]
...
0002ba80 16 instance void [test] PerfViewTierEventsTest+<>c::<Main>b__0_0()[ReadyToRun]
```

perf.data.txt - code offsets recorded for test.dll are lower than the lowest entries in test.ni.{guid}.map and don't correspond with methods in the map:

```
	          250e7e DelayLoad_MethodCall (/home/kount/temp/dotnet/test/libcoreclr.so)
	            84ea [unknown] (/home/kount/test/code.r2r/test.dll)
	          250cbf CallDescrWorkerInternal (/home/kount/temp/dotnet/test/libcoreclr.so)
```

```
	            85cf [unknown] (/home/kount/test/code.r2r/test.dll)
	            ba90 [unknown] (/home/kount/test/code.r2r/test.dll)
```

Looks like the map is using a different base for calculating the offset than the base being used for code offsets that are collected in the trace.

**Comment by tommcdon** [comment]
load balancing to @cshung

**Comment by tommcdon** [comment]
@davmason do you have time to take a look?

**Comment by davmason** [comment]
I took a look at this tonight, the issue is fundamentally the same as #25371. In `perfmap.cpp` the `ReadyToRunInfo::MethodIterator` will only iterate through non-generic methods.

It should be not too expensive to fix, but I don't think it will get in for the preview 7 cutoff on Wednesday.

https://github.com/dotnet/coreclr/blob/46b22d8706a17d48de1259b3cd75a55903bd2dfd/src/vm/perfmap.cpp#L351-L364

**Comment by kouvel** [comment]
The methods above are not generic, and they are listed in the perf map but with a different offset than what `perf` reports for the same methods, so PerfView is not able to associate the offset reported by `perf` with the method in the perf map.

**Comment by kouvel** [comment]
I used the test case from here: https://github.com/dotnet/coreclr/issues/25015#issuecomment-499789460

**Comment by davmason** [comment]
There were two issues going on, one is that generic methods were missing, #25518 fixes that. The second issue is that the offsets are wrong and is going to be looked in to by @cshung

**Comment by cshung** [comment]
Some notes on the investigation:
Map file lookup is done [here](https://github.com/microsoft/perfview/blob/234398a44fbfee5b828272b8201d19d10c7f3578/src/PerfView/OtherSources/Linux/LinuxPerfScriptEventParser.cs#L810).
