### ISSUE TITLE
Unnecessary instructions after generic specialization optimization of struct

### ISSUE THREAD

**Issue by rvhelden** [dotnet/coreclr#24976]
When looking at this sample in [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsAChiAJirLlxAMyVVlKgHZlAb3Lnyyi+T5RWE7BhjkAgoIDu2AJ64AChEFpL3JccgBecgATGAAzbAZBDAAKN08ff0CwLwBKRSVrW3tHZy5sMAALGAAeVO8/AKCAPhCwcPImGHdyUorq2vSGrMak3KsLMfMdclYWcgAVWQwAITwYEYnyM2sN62JDcgwoBmcAfnJ1chBzvOsAXw2NqZmMecWqdfyLLfHP60n93A0UTlCAJSIjchnC5XVQ3Cz3X6WRFPWYLXAYVQfazfcw7Cx7FrcbBMCFQqiXa4bBEIrS6NTdMqVKpzDJNDbuSqweasrIUgCSPK8pmUAEhCg4nNzBsE+NK2tE4gkMHkNgBtACyMAwIMifP4giSmu1EF1+oA8nw2BAmICXABzO2wXC4ewwPlMQJMGZ27IAXUeumAEACDJJ2Q2Jjx5lYMXISW1rEBssyXiBILBI3DiOxUb+BMOxzhf3ICOL5hgglwMFzkezZYJcUrMCLf1uIpFVOUNKUtJCBbAL369RT/MFwqUIqmQZDwNBgnB2XCzQLza7mhUumeIjiMnIAul45F08E5FnGdGSluQA==) It looks like the first 2 instructions (MOV & CMP) for the method Program.Test2 are not needed. Also the first CMP instruction of Test1 seems unnecessary

**Comment by mikedn** [comment]
Those are needed in case the involved references are `null`, without those instructions a `NullReferenceException` wouldn't be thrown as the semantics of the original code requires.

**Comment by rvhelden** [comment]
But for the method Test1 it is a struct that it is using (s) and that could never be null.

For Test2 the whole reference is optimized away so there is no reference and seems to me that it will never be possible for the reference that is not there anymore to be null.

**Comment by mikedn** [comment]
> But for the method Test1 it is a struct that it is using (s) and that could never be null.

But `this` can be `null` because in IL it is not guaranteed to be non-null like in C#. And that's what `cmp [ecx], ecx` does - `ecx` contains `this` and if it is null the instruction will raise an exception.

> For Test2 the whole reference is optimized away so there is no reference and seems to me that it will never be possible for the reference that is not there anymore to be null.

It doesn't matter if it's optimized away, it was there. If you have code like:
```
int x = y.z;
```
and `y` is `null` then you're supposed to get a `NullReferenceException` even if `x` is not used and thus `y.z` is apparently not needed.

**Comment by AndyAyersMS** [comment]
Even in C# you can use reflection to break what you might think of as an invariant:
```C#
class PrivateReflector
{
    public static void Main()
    {
        var p = new Program();
        Type t = typeof(Program);
        FieldInfo f = t.GetField("sc", BindingFlags.NonPublic | BindingFlags.Instance);
        Console.WriteLine($"p.sc is {f.GetValue(p)}");
        f.SetValue(p, null);
        Console.WriteLine($"p.sc is now {f.GetValue(p)}");
        int result = -1;
        try 
        { 
           result = p.Test2();
        }
        catch (NullReferenceException nre)
        {
            Console.WriteLine($"Caught: {nre.Message}");
        }
        Console.WriteLine($"Result is {result}");
    }
}
```
produces:
```
p.sc is Cache`1[AlwaysPolicy]
p.sc is now
Caught: Object reference not set to an instance of an object.
Result is -1
```

**Comment by AndyAyersMS** [comment]
@rvhelden hopefully this explains things -- the jit must preserve exceptional behavior when optimizing, as that behavior is part of the spec.
