### ISSUE TITLE
memory on Ubuntu

### ISSUE THREAD

**Issue by markusmobius** [dotnet/coreclr#24977]
We have been running a server command line program that uses about 80GB of memory (scraping and data processing) with lots of concurrent threads.

The programs run on both Ubuntu and Windows server under Netcore 3.0 preview (same size of VM on Azure with 120GB of memory). Until preview 3 everything worked flawlessly with similar resource consumption on both Windows and Ubuntu. 

But with Preview 4 the Ubuntu version regularly runs out of memory while the Windows version seems to work as before. 

We now reverted back to Preview 3 and the program now runs fine again.

The program runs with server garbage collection:

 ` <PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>`

Were there any changes in memory management from Preview 3 to 4 that could cause these problems and any way to mitigate them?

PS: I might have answered my own question. When running with ConcurrentGarbageCollection=false the memory consumption on Preview 3 decreases a lot. I'll try Preview 4 with that setting next.

Update: Yes memory consumption is much reduced with ConcurrentGarbageCollection=false. It would be great to have this information more easily available (I don't really know what this settings does either  way).

**Comment by janvorli** [comment]
In Preview 4, my change has introduced the problem when ideal thread processor was treated as hard affinitization. That is fixed in Preview 5. @markusmobius could you please try preview 5 to see if it behaves better?

**Comment by sergiy-k** [comment]
@janvorli, did you mean to say that it was fixed in preview 6?

**Comment by janvorli** [comment]
@sergiy-k, ah you are right, I've somehow lost track of what got into preview 5.

**Comment by markusmobius** [comment]
Great - I will try Preview 6 when it comes out. We are currently running Preview 5 on Windows but Preview 3 on Linux.

**Comment by janvorli** [comment]
@markusmobius the Preview 6 is out, could you please give it a try and let us know whether your issue got fixed?

**Comment by markusmobius** [comment]
I upgraded to preview 6 on both Ubuntu and windows and will report back (it takes a day for a full run). Thanks for all your work!

**Comment by janvorli** [comment]
@markusmobius thank you for the update!
