### ISSUE TITLE
Failed to run xunit-reporter.py

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24996]
**Job:**
https://mc.dot.net/#/user/coreclr-ci/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F24823~2Fmerge/test~2Ffunctional~2Fcli~2F/20190605.40/workItem/baseservices.threading/wilogs

**Log:**
```
+ python /root/helix/work/correlation/xunit-reporter.py
Traceback (most recent call last):
  File "/root/helix/work/correlation/xunit-reporter.py", line 5, in <module>
    import helix.azure_storage
  File "/root/helix/scripts/helix/__init__.py", line 1, in <module>
    import helix.depcheck
  File "/root/helix/scripts/helix/depcheck.py", line 66
    def _is_legal_module(module_name: str) -> bool:
                                    ^
SyntaxError: invalid syntax
+ exit 139
```

**Comment by RussKeldorph** [comment]
https://mc.dot.net/#/user/coreclr-outerloop-jitstress/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190604.1/workItem/PayloadGroup0/wilogs

@dotnet/dnceng Can you take a look?  Should this be moved to dotnet/core-eng?

**Comment by MattGal** [comment]
@RussKeldorph this is still fallout from the migration from Python 2 -> 3 necessitated by its EOL-iness.

mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.8-helix-45b1fa2-20190327215821 has Python 2 as its default entry point for python, so it fails that way.  We should be able to update the relevant DockerFiles to use Python 3 to unblock this. 

As for OSX machines though, they will be converted to Python3  as the DDFUn folks are able to migrate them.

**Comment by RussKeldorph** [comment]
@mattgal is there an issue tracking the conversion you can link to this?

**Comment by jonfortescue** [comment]
@RussKeldorph Matt's oof today, but I believe that the conversion is being tracked here https://github.com/dotnet/core-eng/issues/5480. @ilyas1974 is likely the best person to confirm that.

**Comment by ilyas1974** [comment]
@jonfortescue is correct - as part of the deployment of the 10.14 systems, the systems are being set up to utilize python3. At this point, we are still rolling out the new systems. Once that is completed, we will go back and re-deploy the existing systems with python3.
