### ISSUE TITLE
CMake mmap config uses non-existing directory

### ISSUE THREAD

**Issue by Therzok** [dotnet/coreclr#25000]
See this conditional:
https://github.com/dotnet/coreclr/blob/5d4ff2f11a87d7d434d05e72744946f48e017b11/src/pal/src/configure.cmake#L535-L588

It tries to use `mkstemp` on a directory which does not exist as part of its template.

From the man pages:
```
ERRORS
     The mkstemp(), mkostemp(), mkstemps(), mkostemps(), and mkdtemp() functions may set errno to one of the
     following values:

     [ENOTDIR]          The pathname portion of the template is not an existing directory.
```

**Comment by janvorli** [comment]
It is interesting that Linux man pages doesn't specify the ENOTDIR as a possible error code, but OSX one does.

**Comment by Therzok** [comment]
Ah, my bad, I should've mentioned this! Thanks for taking a look and fixing it, too 🎉
