### ISSUE TITLE
Let the runtime optimize type switches 

### ISSUE THREAD

**Issue by msedi** [dotnet/coreclr#25013]
I'm using a lot of generic structures for number crunching and I have to do a lot of type comparisons like the example below:

```
namespace Test {
  public readonly struct Vector<T> where T : struct {
    public readonly T[] Data;

    public Vector (T[] data) {
      Data = (T[]) data.Clone ();
    }

    public Vector<Tout> Add<Tout> (Vector<Tout> v1, Vector<Tout> v2) where Tout : struct {
      Tout[] newdata = new Tout[v1.Data.Length];

      if (typeof (T) == typeof (int)) {
        for (int i = 0; i < v1.Data.Length; i++) {
          newdata[i] = (Tout) (object) ((int) (object) v1.Data[i] + (int) (object) v2.Data[i]);
        }
      } else if (typeof (T) == typeof (float)) {
        for (int i = 0; i < v1.Data.Length; i++) {
          newdata[i] = (Tout) (object) ((float) (object) v1.Data[i] + (float) (object) v2.Data[i]);
        }
      }

      return new Vector<Tout> (newdata);
    }
  }
}
```

What happens is that the code has many `if...then`s that have to be evaluated on every call. So it would be nice if the runtime could optimize this by simply eliminating the pathes that won't run due to the restriction of the type. So if `Vector<int>` is used, the float path and all the other pathes not shown in this short example are dropped and no `if..then` is available in the code.

**Comment by AndyAyersMS** [comment]
The jit does exactly this optimization (and has done so for quite a while now) -- do you see examples where it is not happening?

**Comment by msedi** [comment]
@AndyAyersMS: Thanks for the reply. I was currently testing it again, and obviously made some mistakes in SharpLab. Yes, I can see exactly what you said. Sorry for that, very nice work. If you generics will be fully supported with operators I will be the happiest man on earth ;-)
