### ISSUE TITLE
.NET Core TcpClient NetworkStream WriteAsync never returns when pending ReadAsync

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#2501]
.NET Core TcpClient NetworkStream WriteAsync doesn't return when there is a pending ReadAsync

The stacktrace of WriteAsync shows it is waiting for a semaphore. Looking at [Stream.cs](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Stream.cs) shows
BeginReadInternal and WriteReadInternal use the same semaphore.

A read and write should be supported simultaneous for a TCP stream. This code is working fine on the .NET Framework.

**Comment by tmds** [comment]
I am using 1.0.0-rc1-update1 on Windows 10.

**Comment by ayende** [comment]
WriteAsync is implemented as:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Stream.cs#L710

No semaphore here, there is blocking in the default BeginWrite in the Stream class, but NetworkStream.cs (from here, but should be essentially the same) overrides them to properly work in a fully async manner:
http://referencesource.microsoft.com/#System/net/System/Net/Sockets/NetworkStream.cs,901

**Comment by tmds** [comment]
Stack trace of NetworkStream WriteAsync call:
![stacktrace](https://cloud.githubusercontent.com/assets/1025424/12072322/86e299c2-b0d9-11e5-8e3b-ab52bb3563ce.png)

**Comment by ayende** [comment]
That isnt network stream. It override the method
What is the full assembly qualified name of the type

**Comment by tmds** [comment]
"System.Net.Sockets.NetworkStream, System.Private.Networking, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

The code works when it is running on the full framework.
Also, the write works when there is no pending receive.

**Comment by ayende** [comment]
Where is the source for that?
This is the first I hear about this assembly, at a guess, this is a
separate NetworkStream.cs implementation than the one here:

https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs#L985



*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by tmds** [comment]
Don't know where the source is, I get it by referencing System.Net.Sockets:

![dependencies](https://cloud.githubusercontent.com/assets/1025424/12073466/6fc4b628-b122-11e5-9d07-ff5310b38e6c.png)

**Comment by ayende** [comment]
Can you check the decompiled NetworkStream from there? Using reflector or
dotPeek?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by tmds** [comment]
The decompiled version of NetworkStream has a BeginWrite method, but dotPeek doesn't show an override keyword:
```
public IAsyncResult BeginWrite(byte[] buffer, int offset, int size, AsyncCallback callback, object state)
```
Just like the one in the in [corefx](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs#L773)

**Comment by ayende** [comment]
Hm... that is a bug, then.
But the WriteAsync should be calling those methods, not the base class one.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by SidharthNabar** [comment]
@tmds and @ayende - To clarify a little, networking assemblies such as System.Net.Sockets were earlier implemented via System.Private.Networking which was not building from the GitHub sources. This has now been updated and each assembly has a separate implementation assembly that is built from source code in GitHub. Please try a version of the library greater than rc2-23608 from https://www.myget.org/feed/dotnet-core/package/nuget/System.Net.Sockets

**Comment by tmds** [comment]
Works with 4.1.0-rc2-23704
