### ISSUE TITLE
System.InvalidProgramException when stackalloc'ing a span of ints

### ISSUE THREAD

**Issue by AndreasTruetschel** [dotnet/coreclr#25041]
I run into a `System.InvalidProgramException` when I try to stackalloc a `Span<int>` via
```
Span<int> columnWidths = stackalloc int[dataDebuggerPreview.ColumnView.Length];
```
This occurs on Windows 10 (x64) with .Net Core 3.0 preview 5.  

Repro:  
[TaxiFarePrediction.zip](https://github.com/dotnet/coreclr/files/3268322/TaxiFarePrediction.zip)

Memory-dump:  
[TaxiFarePrediction_MemDump.zip](https://github.com/dotnet/coreclr/files/3268323/TaxiFarePrediction.zip)

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/dotnet/roslyn/issues/35764, which has already been fixed and the fix should be there in a future preview.

**Comment by jkotas** [comment]
Duplicate of dotnet/roslyn#35764
