### ISSUE TITLE
GetManifestResourceStream giving Null Reference exception 

### ISSUE THREAD

**Issue by ateregulov** [dotnet/coreclr#25052]
using (var resourceStream = GetType().Assembly.GetManifestResourceStream("MyProject.MyFile.pfx"))
            using (var ms = new MemoryStream())
            {
                resourceStream.Position = 0;
                resourceStream.CopyTo(ms);
                ...
            }

This code work on my Ubuntu 18 server with dotnet version 2.2.103

But I have error on dotnet version 2.2.300:

Unhandled Exception: System.ArgumentNullException: Value cannot be null.

**Comment by jkotas** [comment]
Could you please share the stacktrace for the exception and more complete repro?

**Comment by ateregulov** [comment]
The reason was the absence of a file appsettings.json
