### ISSUE TITLE
Source-build patches removal for CoreCLR

### ISSUE THREAD

**Issue by crummel** [dotnet/coreclr#25058]
Source-build has some patches that we are currently applying to your repo.  This issue tracks removing the patches.  These patches can be found at https://github.com/dotnet/source-build/tree/release/3.0/patches/coreclr.

Patches that have the responsibility "Repo" and the Disposition "Incorporate" are patches that we believe are valid source-build fixes that should be moved into your repo.  Please let us know if these don't seem like good patches.  Any changes with the responsibility "source-build" is something that we plan to keep going forward or integrate in another way - please also let us know if you think there may be problems with those patches.

Patch name | Type | Disposition | Responsibility | Notes
-- | -- | -- | -- | --
coreclr/0001-Allow-separate-tool-and-SDK-directories.patch | Build | Incorporate | Repo |

**Comment by jashook** [comment]
Partially address with https://github.com/dotnet/coreclr/pull/24929. Note we dot not use init-tools anymore. @crummel What is the priority for windows? Adding the hook seemed not interesting in the PR.

**Comment by crummel** [comment]
We would like to keep Windows working if possible, especially since CoreCLR is near the start of the build.  We've both talked about killing it off and about source-build becoming the first-class build so it'd be nice to keep our options open.

**Comment by jashook** [comment]
Will address windows once the prebuilts are finished then.

**Comment by jashook** [comment]
Punting this from 3.0.
