### ISSUE TITLE
Skip ForceGC if it is not necessary

### ISSUE THREAD

**Issue by cshung** [dotnet/coreclr#25069]
Suppose I have a long-running application (e.g. ASP.NET Core), after taking a heap dump using the ForceGC keyword, the next session should not trigger a ForceGC behavior.

**Repro**

1. Create a .NET Core 3 console application that blocks on `Console.ReadLine()`.
2. Launch it under a native debugger
3. Set a breakpoint on `ETW::GCLog::ForceGC`
4. Launch `dotnet-trace` with the ForceGC keyword enabled (do not stop the session)
5. Launch another `dotnet-trace` with the ForceGC keyword disabled

**Expected**: The second session does not hit the `ForceGC` breakpoint.
**Actual**: The second session does hit the `ForceGC` breakpoint.

@dotnet/dotnet-diag

**Comment by noahfalk** [comment]
I think the logic works out better in some cases, but it still appears like there is a missing recalculation of the remaining keywords/level when a session is disabled. I expect it works when the session you are disabling is the only one currently active, but if we modify the setup slightly I bet we can still repro it. For example if we enabled some other session first (ie you had a EventListener running) then I'd anticipate the callback isn't correct and you would still be able to repro the bug described above.

**Comment by tommcdon** [comment]
Closing this issue as "fixed" and tracking the above comment on #25298
