### ISSUE TITLE
Avoid using Timer for event counters

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#25071]
If the application is experiencing thread pool starvation it would be ideal if event counters didn't suffer as a result. Maybe counters should use a dedicated thread to push counter updates on the specified interval.

cc @noahfalk @sywhang

**Comment by noahfalk** [comment]
Agreed. (and I suspect I've seen this happen in practice during some of my recent experiments, but I hadn't yet investigated to confirm)

**Comment by noahfalk** [comment]
We also switched the underlying IPC event serialization for all EventPipe events from timer to dedicated thread for similar reasons.

**Comment by sywhang** [comment]
Closing this issue via #25864 and #25978.

**Comment by davidfowl** [comment]
👏
