### ISSUE TITLE
.Net Core does not produce Watson crash reports

### ISSUE THREAD

**Issue by leculver** [dotnet/coreclr#25083]
.Net Core cannot currently generate actionable Watson reports.  We are actively investigating why with the DEX (windbg) team.  We need to be sure not to ship 3.0 RTM until we have this resolved (or understood).

**Comment by MeiChin-Tsai** [comment]
Is this blocking preview 6?

**Comment by leecow** [comment]
Seems like something we would want for Preview 7, if possible.

**Comment by leculver** [comment]
@MeiChin-Tsai No, this is not intended to be blocking preview 6.  I intended this to be "Blocking RTM", but preferably fixed in Preview 7.  There wasn't a good tag to convey that.

**Comment by tommcdon** [comment]
@mikem8361 @noahfalk

**Comment by leculver** [comment]
(Please note I'm not a security expert.  This is my layman's understanding of certs and what happened here based on some investigation.)

.Net Core used to have 2 certificates: a sha1 – Microsoft Root Certificate, and a sha256 – Application Root Certificate.  It’s unclear to me why our sha256 cert would be of a different kind.  The feature that makes WER accept our auxiliary data dll (mscordaccore.dll) only accepts Microsoft Root Certificates, but that was OK because we had the sha1 cert which passed.

In .Net Core 3, we removed the sha1 cert, leaving only the sha256 cert, which is rejected by dbgeng because it’s an application root certificate.  This is still a valid cert, but if dbgeng/WER is to accept it, they will need to make a code change for it.  This is really bad for us because code changes in Windows can take months to reach end-user machines, and we’ll also have to convince them to backport this change to previous versions of Win10…which they would not do for us in the past.

I'm taking a look at what we can do for preview7 or RTM.

**Comment by leculver** [comment]
(Please note this is my layman's understanding of certificates and what's happening here.  I'm not a security expert.)

.Net Core used to have 2 certificates: a sha1 – Microsoft Root Certificate, and a sha256 – Application Root Certificate.  It’s unclear to me why our sha256 cert would be of a different kind.  The feature that makes WER accept our auxiliary data dll (mscordaccore.dll) only accepts Microsoft Root Certificates, but that was OK because we had the sha1 cert which passed.

In .Net Core 3, we removed the sha1 cert, leaving only the sha256 cert, which is rejected by dbgeng because it’s an application root certificate.  This is still a valid cert, but if dbgeng/WER is to accept it, they will need to make a code change for it.  This is really bad for us because code changes in Windows can take months to reach end-user machines.

**Comment by tommcdon** [comment]
Fixed on #25205
