### ISSUE TITLE
Assertion when coregen-ing Microsoft.Build.Tasks.CodeAnalysis.dll

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#2508]
This is a failing assertion for Windows.

One assertion failure for JitStress=1 and JitStress=2.
Assertion failure in src\vm\i386\stublinker86.cpp, line 6052.
The command causing the assert is:
crossgen /App_Paths . /Platform_Assemblies_Paths . /MissingDependenciesOK  ./Microsoft.Build.Tasks.CodeAnalysis.dll

Exact assertion failure.
Assert failure(PID 20676 [0x000050c4], Thread: 22660 [0x5884]): rangeOffset >= (offset + (sizeof(void*) * 3))

CROSSGEN! EncodeGCOffsets + 0x1F6 (0x00007ff6`6bf05c36)
CROSSGEN! StubLinkerCPU::CreateTailCallCopyArgsThunk + 0x1304 (0x00007ff6`6bf04f24)
CROSSGEN! CEEInfo::getTailCallCopyArgsThunk + 0x7F (0x00007ff6`6bdb2b2f)
CROSSGEN! ZapInfo::getTailCallCopyArgsThunk + 0x38 (0x00007ff6`6c266bb8)
CROSSGEN! Compiler::fgMorphTailCall + 0x564 (0x00007ff6`6c162624)
CROSSGEN! Compiler::fgMorphCall + 0x62D (0x00007ff6`6c15026d)
CROSSGEN! Compiler::fgMorphTree + 0x513 (0x00007ff6`6c162be3)
CROSSGEN! Compiler::fgMorphStmts + 0x2F0 (0x00007ff6`6c1614b0)
CROSSGEN! Compiler::fgMorphBlocks + 0x187 (0x00007ff6`6c14f2a7)
CROSSGEN! Compiler::fgMorph + 0x333 (0x00007ff6`6c14c203)
    File: d:\repos\coreclr\src\vm\i386\stublinkerx86.cpp Line: 6052
    Image: D:\repos\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\crossgen.exe

**Comment by hoyMS** [comment]
Not repro.
