### ISSUE TITLE
Question: Why is there no bit-test-and-set opcode in the IL instruction set?

### ISSUE THREAD

**Issue by Korporal** [dotnet/coreclr#25099]
Given that locking always ultimately rests upon hardware bit test and set instructions, why was no IL instruction defined that abstracts this, making it easier to write platform agnostic locking code?

For example here is the Intel [instruction](https://www.felixcloutier.com/x86/cmpxchg) that does this on their x86 hardware.

**Comment by mikedn** [comment]
> For example here is the Intel instruction that does this on their x86 hardware.

I don't follow. The instruction in exposed via `Interlocked.CompareExchange` that is treated as an intrinsic by the JIT compiler. What exactly are you asking for?

**Comment by Korporal** [comment]
> > For example here is the Intel instruction that does this on their x86 hardware.
> 
> I don't follow. The instruction in exposed via `Interlocked.CompareExchange` that is treated as an intrinsic by the JIT compiler. What exactly are you asking for?

I had no idea that was an "intrinsic" I looked at that code recently and saw it [here](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/threading/interlocked.cs#L144).

It seemed to call out some external method (I assumed it was some native method called via interop).

Also I did some benchmarks a few days ago and found that calls to Interlocked.CompareExchange seemed to incur rather higher cost than the C# "lock" keyword, I assumed this was die to interop overheads.

Why did Interlocked.CompareExchange seem to incur greater CPU cost than "lock"?

**Comment by mikedn** [comment]
> It seemed to call out to some external method (I assumed it was some native method called via interop).

That doesn't prevent the JIT from recognizing it and emitting the appropriate instruction for the target architecture: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgBUALWbAEwEsAdgHMA3DWIBmJqQYBhBgG8aDFQwAOUPgDdsGGA0EYDY6qqZTiKBgFkAFAEpFys6oCSAvVAA2EMAGsYHhZZCHw1bFgAUQQwDmxhGFtYADMDNAYUUnSUCXsTMwBfGgKgA==

> Why did Interlocked.CompareExchange seem to incur greater CPU cost than "lock"? (My test code called Yield() when the caller failed to "get" ownership of the word).

Was that involving primitive types of reference types? For reference types `Interlocked.CompareExchange` does indeed generate a call because it needs a GC write barrier and that's more complicated than a simple `cmpxchg` instruction.

**Comment by Korporal** [comment]
> > It seemed to call out to some external method (I assumed it was some native method called via interop).
> 
> That doesn't prevent the JIT from recognizing it and emitting the appropriate instruction for the target architecture: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgBUALWbAEwEsAdgHMA3DWIBmJqQYBhBgG8aDFQwAOUPgDdsGGA0EYDY6qqZTiKBgFkAFAEpFys6oCSAvVAA2EMAGsYHhZZCHw1bFgAUQQwDmxhGFtYADMDNAYUUnSUCXsTMwBfGgKgA==
> 
> > Why did Interlocked.CompareExchange seem to incur greater CPU cost than "lock"? (My test code called Yield() when the caller failed to "get" ownership of the word).
> 
> Was that involving primitive types of reference types? For reference types `Interlocked.CompareExchange` does indeed generate a call because it needs a GC write barrier and that's more complicated than a simple `cmpxchg` instruction.

@mikedn 

OK thanks.

I can't recall the exact code (it was at my home) so will need to review it, I'll try to post it too.

The args to CompareExchange were "ref long" against a long field inside an object.

The object had a "DoWork" method and this was called by competing threads (accessing the same object).

DoWork either used lock() or the looped CompareExchange and it then simply incremented three int fields to simulate "work".

I think the threads ended after the incremented values hit 10^9 or something.

Actually here is the code or pretty close to:

https://github.com/Korporal/hodgepodge/tree/master/Locking/NativeCriticalSections

I put this together when discussing the subject of locks on this [thread](https://github.com/dotnet/csharplang/issues/2554).

I was experimenting with way to implement a spin lock by looping but if I recall the results seemed to indicate CompareExchange had some unanticipated overhead...

**Comment by mikedn** [comment]
> Actually here is the code or pretty close to

That `SpinLockObject` seems to be using `Thread.Sleep(1)`. I don't see how that could ever be efficient. In general, it's difficult to get spinning right and the framework already offers a spinlock facility.

> I put this together when discussing the subject of locks on this thread

Oh, that thread...

**Comment by Korporal** [comment]
> > Actually here is the code or pretty close to
> 
> That `SpinLockObject` seems to be using `Thread.Sleep(1)`. I don't see how that could ever be efficient. In general, it's difficult to get spinning right and the framework already offers a spinlock facility.
> 
> > I put this together when discussing the subject of locks on this thread
> 
> Oh, that thread...

Yes you're right that code has Sleep rather than Yield - I should clean up the benchmark code I think and come back to you with something solid.

Yup...that thread...

**Comment by benaadams** [comment]
[`Thread.Sleep(1)`](https://github.com/Korporal/hodgepodge/blob/13c851ade15278093e438ce2a36b399ec4ac4835/Locking/NativeCriticalSections/CriticalSections/SpinLockedObject.cs#L18) can be up to 16ms; normally want to go through various backoff stages

[SpinLock](https://github.com/dotnet/coreclr/blob/96c8a1259f5605f52a4d08d804c5f0cdb59308b2/src/System.Private.CoreLib/shared/System/Threading/SpinLock.cs#L53) might be something to use.

Also [SpinWait](https://github.com/dotnet/coreclr/blob/96c8a1259f5605f52a4d08d804c5f0cdb59308b2/src/System.Private.CoreLib/shared/System/Threading/SpinWait.cs#L160-L239) (as used by SpinLock) might be something to look at for an implementation as it already provides increasing backoff on its spins

e.g. changing your example, something like:

```csharp
public abstract class SpinLockedObject
{
    public int spinner = 0;

    protected void LockMe()
    {
        if (Interlocked.CompareExchange(ref spinner, 1, 0) == 1)
        {
            LockContended();
        }
    }

    private void LockContended()
    {
        var wait = new SpinWait();
        while (Interlocked.CompareExchange(ref spinner, 1, 0) == 1)
        {
            wait.SpinOnce();
        }
    }

    protected void UnlockMe()
    {
        Volatile.Write(ref spinner, 0);
    }
}
```

**Comment by Korporal** [comment]
@benaadams - This is helpful, very interesting - much appreciated.

**Comment by benaadams** [comment]
With SpinLock you might do something like
```csharp
public abstract class SpinLockedObject
{
    private SpinLock _spinner = new SpinLock(enableThreadOwnerTracking: false);

    protected void LockMe()
    {
        bool lockTaken = false;
        try
        {
            _spinner.Enter(ref lockTaken);
        }
        catch
        {
            if (lockTaken)
            {
                _spinner.Exit();
            }

            throw;
        }
    }

    protected void UnlockMe()
    {
        _spinner.Exit(useMemoryBarrier: true);
    }
}
```
