### ISSUE TITLE
Assertion when coregen-ing Microsoft.Build.Tasks.CodeAnalysis.dll on Linux

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#2509]
A failure in the VM code. Happens with no stress modes or special flags - just debug build of the CoreCLR. Assertion failure in pefile.cpp, line 4612.
Command to get it:
crossgen /App_Paths . /Platform_Assemblies_Paths . /MissingDependenciesOK  ./Microsoft.Build.Tasks.CodeAnalysis.dll
Also happens for csc.exe and CodeAnalysis' Microsoft.CodeAnalysis.Workspaces.Desktop.dll.
Stress modes or other flags (including minopts) make no difference for this assert.

Exact assertion failure:
Warning: .

Assert failure(PID 49611 [0x0000c1cb], Thread: 49611 [0xc1cb]): i[0] == W('\\') || i[0] == W('/')
    File: /home/lubo/SVS/src/vm/pefile.cpp Line: 4612
    Image: /home/lubo/coreclr-tests/Windows_NT.x64.Debug/Tests/coreoverlay/crossgen

Aborted (core dumped)

**Comment by gkhanna79** [comment]
>> crossgen /App_Paths . /Platform_Assemblies_Paths . /MissingDependenciesOK ./Microsoft.Build.Tasks.CodeAnalysis.dll

@LLITCHEV You should be specifying the absolute path and not the ".". Does it not work when you do so?

**Comment by gkhanna79** [comment]
@JohnChen0 - FYI

**Comment by LLITCHEV** [comment]
@gkhanna79 @JohnChen0 Specifying the full path probably works (have not tried yet - in the middle of another thing). However, on *nix using the shortcuts .,..,~ is a very common practice. The paths could get really long. I think canonical-izing/normalizing the path or in case of . or .. prepending the current directory could make it way more user friendlier.

**Comment by gkhanna79** [comment]
I dont believe crossgen ever supported using shortcuts on any platform (atleast that is what the assert is also indicative of). Shortcut support can be looked into for a future release.

**Comment by LLITCHEV** [comment]
Sure. I wonder whether on Windows the .\ sequence is allowed?

**Comment by LLITCHEV** [comment]
@gkhanna79 Please, assign the issue as appropriate. Thanks!

**Comment by JohnChen0** [comment]
I'm no longer able to repro this issue.

@LLITCHEV Please let me know if you can still repro it.
