### ISSUE TITLE
[Test failed] baseservices_threading._waithandle_waitall_waitallex10a_waitallex10a_._waithandle_waitall_waitallex10a_waitallex10a_sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25108]
**Job:**
https://mc.dot.net/#/user/coreclr-outerloop-jitstress/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190610.1/workItem/baseservices.threading/analysis/xunit/baseservices_threading._waithandle_waitall_waitallex10a_waitallex10a_~2F_waithandle_waitall_waitallex10a_waitallex10a_sh

**Failed tests:**
baseservices_threading._waithandle_waitall_waitallex10a_waitallex10a_._waithandle_waitall_waitallex10a_waitallex10a_sh

**Log:**
```
Return code:      1
Raw output file:      /root/helix/work/workitem/baseservices/threading/Reports/baseservices.threading/waithandle/waitall/waitallex10a/waitallex10a.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun waitallex10a.exe '/size:64' '/pos:0'
Abandon during a wait, signaling others - 64, 0
Waiting...
AbandonedMutexException was not thrown!
Test Failed
Expected: 100
Actual: 255
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/baseservices/threading/waithandle/waitall/waitallex10a/waitallex10a.sh
Expected: True
Actual:   False
```

**Comment by kouvel** [comment]
Test issue, I'm fixing, but moving to future
