### ISSUE TITLE
Hook getEHinfo

### ISSUE THREAD

**Issue by danysu** [dotnet/coreclr#2514]
Hi,
I want develop a JIT Hook, I know how to hook `compileMethod` but I don't understand how to Hook `getEHinfo` , I have not found an example for hook JIT functions.

Thanks in advance.

category:proposal
theme:jit-ee-interface
skill-level:intermediate
cost:small

**Comment by LiangChow** [comment]
I'm trying the following method for hooked ``getEHinfo`` but ``my_getEHinfo`` method parameters return incorrectly value, Where is my mistake? 
I will appreciate your help.

````C++
typedef void(__stdcall *getEHinfo_def)(ULONG_PTR classthis, CORINFO_METHOD_HANDLE ftn, unsigned EHnumber, CORINFO_EH_CLAUSE* clause);

struct EH
{
	getEHinfo_def getEHinfo;
};

getEHinfo_def orig_getEHinfo;

void __stdcall my_getEHinfo(ULONG_PTR classthis, CORINFO_METHOD_HANDLE ftn, unsigned EHnumber, CORINFO_EH_CLAUSE* clause)
{
	orig_getEHinfo(classthis, ftn, EHnumber, clause);
}

int __stdcall my_compileMethod(ULONG_PTR classthis, ICorJitInfo *comp,
								   CORINFO_METHOD_INFO *info, unsigned flags,         
								   BYTE **nativeEntry, ULONG  *nativeSizeOfCode)
{
   EH * pEh = (EH *)*(UINT_PTR*)comp + 8;
   DWORD OldProtect = 0;
   VirtualProtect(pEh, sizeof(ULONG_PTR), PAGE_READWRITE, &OldProtect);
   orig_getEHinfo = pEh->getEHinfo;						
   pEh->getEHinfo = &my_getEHinfo;
   VirtualProtect(pEh, sizeof(ULONG_PTR), OldProtect, &OldProtect);

   return origCompileMethod(classthis, comp, info, flags, nativeEntry, nativeSizeOfCode);
}
````

**Comment by bprg** [comment]
This method works on .Net FW 2.x, 3.x but doesn't works on .Net FW 4.x I think is bug!?

**Comment by LiangChow** [comment]
You are right only work with framework 2, It is a strange behavior.

**Comment by jkotas** [comment]
As I have said in https://github.com/dotnet/coreclr/issues/2489, the JIT EE interface is internal unstable frequently changing interfaces. There are no compatibility guarantees accross different runtimes or runtime versions. It is absolutely expected that hacks like this that happen to work on one particular runtime version won't work on other runtime versions.

**Comment by BruceForstall** [comment]
I'm closing this issue.

General comment: please do NOT hook the JIT-EE interface.
