### ISSUE TITLE
DiagnosticCounter locks on a string

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#25157]
https://github.com/dotnet/coreclr/blob/b62e7765e7f4171461b2597fe3174c211957f3ee/src/System.Private.CoreLib/shared/System/Diagnostics/Tracing/DiagnosticCounter.cs#L94

This is generally a no-no, as it effectively leaks the lock to anyone else in the process (with only one AppDomain) locking on the same string object.

**Comment by jkotas** [comment]
It is better to lock on `this`.

**Comment by jkotas** [comment]
Also, do you need to also lock on the consuming side?

**Comment by stephentoub** [comment]
> Also, do you need to also lock on the consuming side?

It looks like all of the consumers do, just at a higher level.  It'd be nice if there were `Debug.Assert(Monitor.IsEntered(MyLock));`s in the GetMetadataString to make that more obvious.

I don't know how performance-sensitive this code is, but there's also improvements that could be done around allocations and the like.
