### ISSUE TITLE
why so slow in ubuntu 14.04 with  Hello world ?

### ISSUE THREAD

**Issue by joostshao** [dotnet/coreclr#2515]
http://dotnet.github.io/getting-started/

ubuntu@ubt:/media/ubuntu/mnt/dotnet$ time dotnet run
Hello World!

real	0m2.592s
user	0m2.377s
sys	0m0.191s

**Comment by shahid-pk** [comment]
yea i noticed that too. startup time is really poor. But if you publish it it is a little bit better and very fast when compiled to native. but still would love to see the managed version start up a bit faster.

**Comment by davidfowl** [comment]
Try running `dotnet -v run` it'll show more info.

**Comment by shahid-pk** [comment]
@davidfowl  the output is here https://gist.github.com/shahid-pk/04d95b94906cc9160081

**Comment by zpodlovics** [comment]
The `dotnet run` is a bit misleading - it will compile the source first and after that will run it.

```
time dotnet run -c Release
Hello World!

real	0m2.904s
user	0m2.452s
sys	0m0.332s
```

```
time dotnet compile -c Release
Compiling test for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.1679085


real	0m2.097s
user	0m1.808s
sys	0m0.248s
```

```
time /usr/share/dotnet/bin/corerun bin/Release/dnxcore50/test.dll 
Hello World!

real	0m0.038s
user	0m0.024s
sys	0m0.012s
```

```
 time dotnet compile -c Release --native
Compiling test for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.1729382

Input Assembly: PATH_TO/bin/Release/dnxcore50/test.dll

real	0m7.414s
user	0m5.868s
sys	0m1.356s
```

```
time ./bin/Release/dnxcore50/native/test 
Hello World!

real	0m0.008s
user	0m0.004s
sys	0m0.000s
```

**Comment by davidfowl** [comment]
That's the point of the command. It's just like `go run` and previously `dnx run` which will make sure the project is built before running. Now we could do things to make it incremental but we don't right now.

**Comment by joostshao** [comment]
thank you all.
