### ISSUE TITLE
Array.GetValue has slowed down in .NET Core 3.0

### ISSUE THREAD

**Issue by msedi** [dotnet/coreclr#25175]
C# generic support for arrays is not very good. In my case I did a few benchmarks since I have to deal with a lot of different and large array types. I often need to cast from one type into another. Therefore I have was thinking of creating an ArrayView wrapper, that delegates the cast to the indexer, so that anytime I access the indexer, the cast is executed. You might think this is nonsense, but I have many cases where the data is stored as byte|uint|int|... but some algorithms only work with arrays. In most cases the data is around 512x512x1000 elements large. So my approach was like this:

```
  public class ArrayView<Tin, Tout> where Tin : struct where Tout : struct
    {
        private Tin[] array;

        public ArrayView(Tin[] array_in)
        {
            array = array_in;
        }

        public Tout this[int index] => (Tout)array[index];

        public Tout this[int index]
        {
            get
            {
                switch (Type.GetTypeCode(typeof(Tin)))
                {
                    case TypeCode.Byte: return (Tout)array[index];
                }
            }
        }
    }
```

But this one doesn't work. `Span<T>` also do not have some sort of `static_cast<>` which I can use. What I tried then, was to benchmark a regular array index access vs. Array.GetValue() and I thought Array.GetValue is recognized by the CLR and optimized well, but when I compare my benchmark this looks horrible. Is there an explanation for this and some sort of solution for the example above?

```
 public class ArrayGet
    {
        public int[] ArraySource1;
        public Array ArraySource2;
        public int N = 1000;

        [GlobalSetup]
        public void Setup()
        {
            ArraySource1 = new int[N];
            for (int i = 0; i < N; i++) ArraySource1[i] = i;

            ArraySource2 = ArraySource1;
        }

        [Benchmark]
        public void SumClassic()
        {
            int sum = 0;

            for (int i = 0; i < N; i++)
                sum += ArraySource1[i];
        }

        [Benchmark]
        public void SumArrayGetValue()
        {
            int sum = 0;

            for (int i = 0; i < N; i++)
                sum += (int)ArraySource2.GetValue(i);
        }
    }
```

```
|           Method | Runtime |     Toolchain |        Mean |        Error |       StdDev | Ratio | RatioSD |
|----------------- |-------- |-------------- |------------:|-------------:|-------------:|------:|--------:|
|       SumClassic |     Clr |        net472 |          NA |           NA |           NA |     ? |       ? |
|       SumClassic |    Core | netcoreapp2.2 |    707.1 ns |     1.793 ns |     1.497 ns |  1.00 |    0.00 |
|       SumClassic |    Core | netcoreapp3.0 |    732.1 ns |     4.750 ns |     4.211 ns |  1.04 |    0.01 |
|                  |         |               |             |              |              |       |         |
| SumArrayGetValue |     Clr |        net472 |          NA |           NA |           NA |     ? |       ? |
| SumArrayGetValue |    Core | netcoreapp2.2 | 76,886.0 ns | 1,467.282 ns | 1,372.496 ns |  1.00 |    0.00 |
| SumArrayGetValue |    Core | netcoreapp3.0 | 79,786.7 ns | 1,128.441 ns | 1,055.544 ns |  1.04 |    0.02 |
```

**Comment by Suchiman** [comment]
Well GetValue returns object so it means every access while get boxed, that is super expensive as you can see when you slap `[MemoryDiagnoser]` on the benchmark
``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17763.529 (1809/October2018Update/Redstone5)
Intel Core i5-4670K CPU 3.40GHz (Haswell), 1 CPU, 4 logical and 4 physical cores
.NET Core SDK=3.0.100-preview6-012264
  [Host]     : .NET Core 3.0.0-preview6-27804-01 (CoreCLR 4.700.19.30373, CoreFX 4.700.19.30308), 64bit RyuJIT
  DefaultJob : .NET Core 3.0.0-preview6-27804-01 (CoreCLR 4.700.19.30373, CoreFX 4.700.19.30308), 64bit RyuJIT


```
|           Method |        Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |------------:|----------:|----------:|-------:|------:|------:|----------:|
|       SumClassic |    501.1 ns |  1.178 ns |  1.102 ns |      - |     - |     - |         - |
| SumArrayGetValue | 46,094.7 ns | 63.912 ns | 56.656 ns | 7.6294 |     - |     - |   24000 B |

Indexer access to the array is as fast as it gets as it's just `dereference(basePtr + (elementSize * offset))`

**Comment by msedi** [comment]
@Suchiman: I understand your point with the object, but that does not really explain why it has slowed down in .NET Core 3.0, right?

IN the end, my question goes into the direction of how I can accomplish the casting situation above, since I cannot currently do it with C#.

**Comment by jkotas** [comment]
> does not really explain why it has slowed down in .NET Core 3.0, right?

The benchmark is allocation heavy. It spends most of the time allocating the boxed ints. The allocation heavy benchmarks are noisy. 4% is well within the typical noise for benchmarks like this. The results depend on many factors like memory alignment. I am not able to see any consistent slow down of `Array.GetValue`.

I have also run our own microbenchmark we have for `Array.GetValue`: https://github.com/dotnet/performance/blob/0c626c0de72e9e018bb02d0f92b97117098f1fee/src/benchmarks/micro/corefx/System.Runtime/Perf.Array.cs#L120

It shows a slightly better results on netcoreapp3.0 for me, but again it is just noise.

netcoreapp2.1:
| ArrayRetrieve1D | 2.786 ms | 0.0281 ms |

netcoreapp3.0:
| ArrayRetrieve1D | 2.656 ms | 0.0635 ms |

**Comment by msedi** [comment]
@jkotas: Thanks for verifying. I'm glad to hear that there is no drop in performance.
