### ISSUE TITLE
Lttng tracepoints enabled unnecessarily?

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#25178]
@chrisnas sent some feedback:

Last but not least, a little related bug:
If the CLR is compiled but there is no LTTng library, the genLttngProvider.py script will generate a stub for this method tracepoint_enabled:
#define tracepoint_enabled(provider, name) TRUE
And this function is used, in the end, by GCToEEInterface::UpdateGCEventStatus method. And as the value is TRUE, the GC events will be emitted anyway. Should we set it to FALSE instead?

[Noah]: At first glance I agree that seems odd. We can take a look : )

**Comment by sywhang** [comment]
Fixed with #25459
