### ISSUE TITLE
Test failed: System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_NextValue_ProcessorCounter

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25192]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstress2-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190615.1/workItem/System.Diagnostics.PerformanceCounter.Tests/analysis/xunit/System.Diagnostics.Tests.PerformanceCounterTests~2FPerformanceCounter_NextValue_ProcessorCounter

**Failed tests:**
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_NextValue_ProcessorCounter

**Log:**
```
Assert.True() Failure
Expected: True
Actual:   False
```

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/38180
