### ISSUE TITLE
Running build.sh on a clean checkout complains about missing pipeline-logging-functions.sh

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#25203]
I checked out the latest coreclr master, ran git clean -xdf and then ./build.sh. While the build works, I can see this printed to the console right after running the build.sh:
```
Commencing CoreCLR Repo build
__DistroRid: linux-x64
__RuntimeId: linux-x64
Setting up directories for build
Checking prerequisites...
/home/janvorli/git/coreclr/eng/common/tools.sh: line 359: /pipeline-logging-functions.sh: No such file or directory
/home/janvorli/git/coreclr/eng/common/tools.sh: line 359: /pipeline-logging-functions.sh: No such file or directory
```
The `pipeline-logging-functions.sh` exists in the `eng/common`, but it is invoked as `"$scriptroot/pipeline-logging-functions.sh"` and the scriptroot is not set anywhere in the script.

**Comment by echesakovMSFT** [comment]
@chcosta Does this belong to dotnet/arcade?

**Comment by jkoritzinsky** [comment]
The Pri0 R2R OSX x64 Checked leg of https://dev.azure.com/dnceng/public/_build/results?buildId=228032&view=logs failed due to this issue.

**Comment by RussKeldorph** [comment]
dotnet/arcade#3076

Thanks @am11!
