### ISSUE TITLE
Concurrent GC isn't disabled automatically when attach memory profiler to .NET Core v3.0.0-preview6 process

### ISSUE THREAD

**Issue by ww898** [dotnet/coreclr#25225]
I receive `CORPROF_E_CONCURRENT_GC_NOT_PROFILABLE` for memory profiler during `SetEventMask` call in `InitializeForAttach` callback. The error appears under .NET Core v3.0.0-preview6, but the same code works properly under .NET Framework v4.5+.

P.S. I assume that there is the bug with attach thread detection: https://github.com/dotnet/coreclr/blob/be5445e56ea2bdb6de907e3f892ca732fc802f0f/src/vm/eetoprofinterfaceimpl.cpp#L2389-L2396

**Comment by RussKeldorph** [comment]
@maoni0 @noahfalk @dotnet/dotnet-diag

**Comment by davmason** [comment]
I’ll take a look, it probably is a bug with the attach thread detection with the new attach mechanism.
