### ISSUE TITLE
gcConcurrent flag in App.config is not taken into account for .net core 3.0 apps

### ISSUE THREAD

**Issue by Anna-Guseva** [dotnet/coreclr#25226]
I created a simple console app with target framework .NET Core 3.0 (preview6 is installed on my machine). 'gcServer enabled' is set to false and gcConcurrent enabled=false in App.config.

```
<configuration>
  <runtime>
    <gcServer enabled="false"/> 
    <gcConcurrent enabled="false"/>
  </runtime>
</configuration>
```

When I try to attach memory profiler to already started app, attach fails with ```CORPROF_E_CONCURRENT_GC_NOT_PROFILABLE``` error.

It looks like concurrent GC isn't disabled despite the config file.

**Comment by Suchiman** [comment]
App.config isn't respected by .NET Core.
You need to configure this via the `*.runtimeconfig.json` file.
There are several ways to do this, the easiest way is specifying
```csproj
<PropertyGroup>
  <!-- <ServerGarbageCollection>true</ServerGarbageCollection> -->
  <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
</PropertyGroup>
```
in your csproj

**Comment by Anna-Guseva** [comment]
Editing csproj file works in our case. Thank you for the information.
