### ISSUE TITLE
EventPipe events should only be sent to sessions that are listening to the event

### ISSUE THREAD

**Issue by tommcdon** [dotnet/coreclr#25232]
Track active listening sessions on `EventPipeEvent` (using a 64-bit mask). Currently, providers track listening session by using a 64-bit bitmask. We should track at the event level instead, so sessions will listen to the events they requested.

**Comment by noahfalk** [comment]
To head off any potential confusion, PR #25358 partially mitigates this problem but it does not solve it. For an example which remains unresolved, consider tracing a process using two sessions, one that gathers verbose JIT events and one that gathers information GC events. Neither of those sessions is configured to listen to verbose GC events, but the union of all session keywords and level will include the GC keyword and it will have the verbose level. As-is EventPipe would log the event to both sessions when the correct behavior is not to log it to either session.
