### ISSUE TITLE
Provide a way for casting a datatype to another datatype

### ISSUE THREAD

**Issue by msedi** [dotnet/coreclr#25248]
Coming from this issue: [#25175](https://github.com/dotnet/coreclr/issues/25175)

In need to deal with a lot of data and there are many occasions where the data needs to be stored internally with the most memory saving datatype. In many cases I need to store the datatype as byte or int (doesn't matter if unsigned or not). The data type is variable at runtime so I cannot bind myself to a specific datatype.

For algorithms it's sometimes necessary though that I work with floats, for two reasons:

1. Because otherwise I would have to write code for any datatype
2. There is no numeric support on generics in C#

For that reason, any time an algorithm needs to work on the data, the data is cast upfront to float and then the algorithms works on this data, but of course I have an additional cost of allocating new data and casting the data.

So my idea was to write some sort of a view on the data, the implicitly does a `reinterpret_cast`.
But there are two problems.

1. I cannot cast
2. The unmanaged type is returned by value

```
    public class ArrayView<Tin, Tout> where Tin : struct where Tout : unmanaged
    {
        private Tin[] array;

        public ArrayView(Tin[] array_in)
        {
            array = array_in;
        }

        public Tout this[int index] => (Tout)array[index];
    }
```

Looking at a "typed" version it works, of course, but still the problem of the "by value" return

```
  public class ArrayView
    {
        private readonly int[] array;

        public ArrayView(int[] array_in)
        {
            array = array_in;
        }

        public float this[int index] => (float)array[index];
    }
```

So my proposal would be following:

1. Provide a way to have some sort of reinterpret_cast
2. Provide a possibility to not return the cast value as "by value", but rather return it directly (somehow). Obviously ref returns are not possible here.
3. Make the runtime recognize the indexer and perform some optimization.

I'm really open for discussions on this, because I'm not sure if I understood the components of the runtime that are necessary to perform this task. I'm also not really able to do benchmarks since it's currently not possible in C#. I'm thinking of a generic implementation in IL.

**Comment by Suchiman** [comment]
You're asking for reinterpret_cast but in #25175 you wrote
> MemoryMarshal does not really do the same as the example above. MemoryMarshal does some sort of pointer reinterpret_cast but not a type cast.

`MemoryMarshal.Cast` does just that, reinterpret_casting the underlying array, so you could basically do
```csharp
public ref float this[int index] => ref MemoryMarshal.Cast<int, float>(array.AsSpan())[index];
```
But why would you need that? reinterpret_casting between integer and floats will cause "garbage data" if viewed with the other representation and they have the same storage size (32bit) so no space saving gained here either.

**Comment by mikedn** [comment]
> Provide a possibility to not return the cast value as "by value", but rather return it directly (somehow). Obviously ref returns are not possible here.

What does that mean? What's wrong with returning it by value?

> Make the runtime recognize the indexer and perform some optimization.

What kind of optimization do you have in mind?

**Comment by msedi** [comment]
@Suchiman: Maybe I used the wrong wording. What I need in the end is a type cast, in the end 

`public static Tout Cast<Tin, Tout>(Tin value)=>(Tout)value;`

So I think the MemoryMarshal does not work. I'm not how the wording was in C++, I assume it's more like a static_cast, right?

Working with memory reinterpretation does not work in my case, I really need a direct type cast from one type into the other. Of course if I have an int and need to cast to a float (32bit -> 32bit), there is no memory saving, but there is from short to float.

In the end it's all about not having to cast the whole array at once and keeping a copy of it all the time.

**Comment by msedi** [comment]
@mikedn:

> What's wrong with returning it by value?
I'm assuming (but I'm not sure), first, there is a type cast from the source type into the target type (which is one type of memory "transport". Then, when the value needs to be returned to another variable. So for example.

```
int[] MyArray = new int[]{1,2,3,4,5,6,7};
ArrayView<int,float> av = new ArrayView<int,float>(MyArray);

float value = av[0]; // Since it's a value type it's copied from a[0] to value, correct?

```

If it would work like this, I at least can omit the last assignment

`ref float value = ref av[0]; `

> 2. What kind of optimization do you have in mind?
I assume that only for Span<T> the runtime made optimizations for the indexer, right? Regular indexers are still having an additional getter method call. If the runtime already makes optimization on this, you can of course forget what I said ;-)

**Comment by mikedn** [comment]
> If it would work like this, I at least can omit the last assignment

It's a value type but to be more precise it is a primitive type. As such I do not understand what assignment issue you're talking about. The conversion `int` -> `float` has to happen and it will happen in registers and/or memory depending on the surrounding code and JIT's optimization abilities. There's no way to have something like `ref float value = ref av[0];`.

> I assume that only for Span the runtime made optimizations for the indexer, right? Regular indexers are still having an additional getter method call. If the runtime already makes optimization on this, you can of course forget what I said ;-)

Well, yes. But if we can get the indexer to inlined then it should work fine. Or at least almost fine. The JIT can be thrown of track by extra complexity in code.

But first we need to figure out what functionality you really want. Would something like bellow fit the bill?
```C#
struct FloatArrayView<T> where T : struct
{
    private readonly T[] _array;

    public FloatArrayView(T[] array) => _array = array;

    public float this[int index]
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            if (typeof(T) == typeof(byte))
                return (byte)(object)_array[index];
            if (typeof(T) == typeof(short))
                return (short)(object)_array[index];
            if (typeof(T) == typeof(int))
                return (int)(object)_array[index];
            throw new NotSupportedException();
        }
    }
}
```

**Comment by msedi** [comment]
@mikedn: Thanks for pointing a few things out, that helps.

Thank you for the example that's what I have tried before, but the performance was not as expected. But honestly, I need to to a few more tests on this. Hopefully at the end of the day I can provide some results of a native implementation vs. the generic one, just to see if there are differences.

**Comment by msedi** [comment]
@mikedn. I have managed to provide some example and some benchmarks. There are some intersting findings I do not quite understand. Here's the benchmark code:

```
        [Benchmark]
        public void CastByHand()
        {
            var value = (float)Value;
        }

        [Benchmark]
        public void CastByIL()
        {
            var value = MathIL<int, float>.To(Value);
        }

        [Benchmark]
        public void CastByToSingle()
        {
            var value = (float)Convert.ToSingle(Value);
        }

        [Benchmark]
        public void CastByToSingleIL()
        {
            var value = (float)MathIL<int, float>.ToSingle(Value);
        }

        [Benchmark]
        public void CastByChangeType()
        {
            var value = (float)Convert.ChangeType(Value, typeof(float));
        }
```

And here are the results. I'm not quite sure about the iterations to make. For example CastByHand has maybe to less iterations. It's OK that CastByHand is the fastest. But what I don't understand is that CastByToSingle is faster. I assume that this is due to not enough iterations. Maybe you have an idea of how I can improve the test. I had the tests with arrays before, but I wanted to get rid of all the memory allocations happening in between.

What is also interesting is that my own CastByToSingleIL by only two opcodes is slower then the Convert.ToSingle.

```
|           Method |       Mean |     Error |    StdDev |     Median |
|----------------- |-----------:|----------:|----------:|-----------:|
|       CastByHand |  0.0294 ns | 0.0448 ns | 0.0628 ns |  0.0000 ns |
|         CastByIL | 49.9722 ns | 0.3497 ns | 0.3271 ns | 49.8400 ns |
|   CastByToSingle |  0.0038 ns | 0.0067 ns | 0.0063 ns |  0.0000 ns |
| CastByToSingleIL |  0.0168 ns | 0.0189 ns | 0.0176 ns |  0.0115 ns |
| CastByChangeType | 44.5242 ns | 0.2385 ns | 0.1992 ns | 44.5430 ns |
```

Although a bit lengthy I also add the IL code in here, Later I will try to push it to an example on github.

```
.assembly extern mscorlib {auto}
.assembly extern System.Runtime {auto}
.assembly siemens.CSharp.IL {}
.module siemens.CSharp.IL.dll

.namespace siemens.CSharp.IL
{
	.class public auto ansi MathIL<valuetype Tin, valuetype Tout>
	{
		.field public static initonly class [System.Runtime]System.RuntimeTypeHandle ToutType

		.method public static float32 ToSingle(!Tin a) cil managed aggressiveinlining
		{
			.maxstack 1

			ldarg.0
			conv.r4
			ret
		}

		.method public static !Tout To(!Tin a) cil managed aggressiveinlining
		{
			.maxstack 3

			ldarg.0

			ldtoken !Tout
			ldtoken uint8
			call bool [System.Runtime]System.Type::Equals(class [System.Runtime]System.Object, class [System.Runtime]System.Object)
			brtrue CastTo_uint8

			ldtoken !Tout
			ldtoken int8
			call bool [System.Runtime]System.Type::Equals(class [System.Runtime]System.Object, class [System.Runtime]System.Object)
			brtrue CastTo_int8

			ldtoken !Tout
			ldtoken uint16
			call bool [System.Runtime]System.Type::Equals(class [System.Runtime]System.Object, class [System.Runtime]System.Object)
			brtrue CastTo_uint16

			ldtoken !Tout
			ldtoken int16
			call bool [System.Runtime]System.Type::Equals(class [System.Runtime]System.Object, class [System.Runtime]System.Object)
			brtrue CastTo_int16

			ldtoken !Tout
			ldtoken uint32
			call bool [System.Runtime]System.Type::Equals(class [System.Runtime]System.Object, class [System.Runtime]System.Object)
			brtrue CastTo_uint32

			ldtoken !Tout
			ldtoken int32
			call bool [System.Runtime]System.Type::Equals(class [System.Runtime]System.Object, class [System.Runtime]System.Object)
			brtrue CastTo_int32

			ldtoken !Tout
			ldtoken uint64
			call bool [System.Runtime]System.Type::Equals(class [System.Runtime]System.Object, class [System.Runtime]System.Object)
			brtrue CastTo_uint64

			ldtoken !Tout
			ldtoken int64
			call bool [System.Runtime]System.Type::Equals(class [System.Runtime]System.Object, class [System.Runtime]System.Object)
			brtrue CastTo_int64

			ldtoken !Tout
			ldtoken float32
			call bool [System.Runtime]System.Type::Equals(class [System.Runtime]System.Object, class [System.Runtime]System.Object)
			brtrue CastTo_float32

			ldtoken !Tout
			ldtoken float64
			call bool [System.Runtime]System.Type::Equals(class [System.Runtime]System.Object, class [System.Runtime]System.Object)
			brtrue CastTo_float64


CastTo_uint8:
			conv.u1		
			ret

CastTo_int8:
			conv.i1		
			ret

CastTo_uint16:
			conv.u2		
			ret

CastTo_int16:
			conv.i2		
			ret

CastTo_uint32:
			conv.u4		
			ret

CastTo_int32:
			conv.i4		
			ret

CastTo_uint64:
			conv.u8		
			ret

CastTo_int64:
			conv.i8		
			ret
			
CastTo_float32:
			conv.r4			
			ret

CastTo_float64:
			conv.r8			
			ret

		}

		/*
		.method private hidebysig specialname rtspecialname static 
			void .cctor () cil managed 
		{
			// Method begins at RVA 0x20a9
			// Code size 31 (0x1f)
			.maxstack 8

			IL_000f: ldtoken !Tout
			IL_0019: stsfld class [System.Runtime]System.RuntimeTypeHandle class siemens.CSharp.IL.MathIL<!Tin, !Tout>::ToutType
			IL_001e: ret
		} 
		*/

	}	
}

```

**Comment by mikedn** [comment]
> var value = (float)Value;

I don't know what `Value` is but this benchmark is in general not good as the result value isn't used. The JIT will simply drop the cast to `float`.

> var value = MathIL<int, float>.To(Value);

It's not clear why do you need custom IL for that. I'm not sure if that particular IL will be recognized by the JIT, which has special code to recognize patterns emitted by C# and probably other compilers (e.g. `typeof(T) == typeof(int)`). That's the likely reason for it being slow.

>  var value = (float)Convert.ToSingle(Value);

I take it from other code that `Value` is `int` so this is no different from a normal C# cast.

>   var value = (float)MathIL<int, float>.ToSingle(Value);

Same as a normal C# cast.

>  var value = (float)Convert.ChangeType(Value, typeof(float));

This will never fly performance wise as it leads to boxing and runtime type checks.

**Comment by mikedn** [comment]
> Thank you for the example that's what I have tried before, but the performance was not as expected

Is the real world code that needs this relatively complex? I can imagine that this approach may cause some problems when JITing large methods. In a trivial example this approach does generate the expected code:
```C#
            var v = new FloatArrayView<byte>(new byte[] { 1, 2, 3, 4, 5 });

            float sum = 0.0f;
            for (int i = 0; i < v.Length; i++)
            {
                sum += v[i];
            }
```
generates the following loop code:
```asm
00007FF9958608C7 C4 E1 78 57 C0       vxorps      xmm0,xmm0,xmm0  
    37:             for (int i = 0; i < v.Length; i++)
00007FF9958608CC 33 D2                xor         edx,edx  
00007FF9958608CE 8B 48 08             mov         ecx,dword ptr [rax+8]  
00007FF9958608D1 85 C9                test        ecx,ecx  
00007FF9958608D3 7E 1E                jle         00007FF9958608F3  
    38:             {
    39:                 sum += v[i];
00007FF9958608D5 4C 63 C2             movsxd      r8,edx  
00007FF9958608D8 46 0F B6 44 00 10    movzx       r8d,byte ptr [rax+r8+10h]  
00007FF9958608DE C4 E1 70 57 C9       vxorps      xmm1,xmm1,xmm1  
00007FF9958608E3 C4 C1 72 2A C8       vcvtsi2ss   xmm1,xmm1,r8d  
00007FF9958608E8 C4 E1 7A 58 C1       vaddss      xmm0,xmm0,xmm1  
    37:             for (int i = 0; i < v.Length; i++)
00007FF9958608ED FF C2                inc         edx  
00007FF9958608EF 3B CA                cmp         ecx,edx  
00007FF9958608F1 7F E2                jg          00007FF9958608D5  
    40:             }
```

**Comment by mikedn** [comment]
Another approach that may work better in some cases is to have specialized array views and instead make the computation code generic over the view type:
```C#
interface IArrayFloatView
{
    int Length { get; }
    float this[int index] { get; }
}

struct Int16ArrayFloatView : IArrayFloatView
{
    private readonly short[] _array;
    public Int16ArrayFloatView(short[] array) => _array = array;
    public int Length => _array.Length;
    public float this[int index] => _array[index];
}

struct Int32ArrayFloatView : IArrayFloatView
{
    private readonly int[] _array;
    public Int32ArrayFloatView(int[] array) => _array = array;
    public int Length => _array.Length;
    public float this[int index] => _array[index];
}

class Program
{
    static void Main()
    {
        var v16 = new Int16ArrayFloatView(new short[] { 1, 2, 3, 4, 5 });
        Console.WriteLine(Sum(v16));
        var v32 = new Int32ArrayFloatView(new int[] { 1, 2, 3, 4, 5 });
        Console.WriteLine(Sum(v32));
    }

    private static float Sum<V>(V v) where V : IArrayFloatView
    {
        float sum = 0.0f;
        for (int i = 0; i < v.Length; i++)
            sum += v[i];
        return sum;
    }
}
```
This produces the same code as before in this simple example:
```asm
00007FF995850943 C4 E1 78 57 C0       vxorps      xmm0,xmm0,xmm0  
    39:         for (int i = 0; i < v.Length; i++)
00007FF995850948 33 C0                xor         eax,eax  
00007FF99585094A 8B 51 08             mov         edx,dword ptr [rcx+8]  
00007FF99585094D 85 D2                test        edx,edx  
00007FF99585094F 7E 1E                jle         00007FF99585096F  
00007FF995850951 4C 63 C0             movsxd      r8,eax  
00007FF995850954 4E 0F BF 44 41 10    movsx       r8,word ptr [rcx+r8*2+10h]  
00007FF99585095A C4 E1 70 57 C9       vxorps      xmm1,xmm1,xmm1  
00007FF99585095F C4 C1 72 2A C8       vcvtsi2ss   xmm1,xmm1,r8d  
00007FF995850964 C4 E1 7A 58 C1       vaddss      xmm0,xmm0,xmm1  
00007FF995850969 FF C0                inc         eax  
00007FF99585096B 3B D0                cmp         edx,eax  
00007FF99585096D 7F E2                jg          00007FF995850951
```
but it is possible that it works better in more complex situations.

**Comment by msedi** [comment]
@mikedn:

> I don't know what Value is but this benchmark is in general not good as the result value isn't used. The JIT will simply drop the cast to float.

You are right, I currently don't know a good approach to keep this, since every command I write might be optimized, since I don't use the result. Even just writing a sum could be optimized away, since the result is not used.

> It's not clear why do you need custom IL for that. I'm not sure if that particular IL will be recognized by the JIT, which has special code to recognize patterns emitted by C# and probably other compilers (e.g. typeof(T) == typeof(int)). That's the likely reason for it being slow.

Youu are right, I really don't want the custom IL code. But there are two questions you poiinted out. I was assuming that the optimization is done on IL code level, because otherwise the JIT could not create inidividual functions for generic methods. But I don't know to which level the JIT is really able to optimize. Maybe tiered compiliation could help, but that's something for the future.

In the end I was hoping to get an elegant way of casting, but it's currently not possible with C#' currently behavior with generics (they are not templates...). So thank you very much for elaborating some examples. I will give it a try. Maybe you are right that your approach is the currently best solution.

> This will never fly performance wise as it leads to boxing and runtime type checks.

Sure, I was only surpirised that my IL code is slower than the ChangeType.

**Comment by mattwarren** [comment]
> You are right, I currently don't know a good approach to keep this, since every command I write might be optimized, since I don't use the result. Even just writing a sum could be optimized away, since the result is not used.

@msedi BenchmarkDotNet was designed so that 'returning' the value out of your benchmark function *should* be enough to [avoid dead code elimination](https://benchmarkdotnet.org/articles/guides/good-practices.html#avoid-dead-code-elimination). I'd suggest you change your benchmarks from:

``` cs
[Benchmark]
public void CastByHand()
{
    var value = (float)Value;
}
```

to

``` cs
[Benchmark]
public float CastByHand()
{
    return (float)Value;
}
```

If that still doesn't work, I'd suggest you [open an issue](https://github.com/dotnet/BenchmarkDotNet/issues) or post a question on the [gitter channel](https://gitter.im/dotnet/BenchmarkDotNet), as there might be other ways to get BenchmarkDotNet to help you out here.

**Comment by msedi** [comment]
@mattwarren: Thanks for the hint. I should have read this better ;-)
