### ISSUE TITLE
StringComparers may return different HashCodes for equal string values

### ISSUE THREAD

**Issue by slepmog** [dotnet/coreclr#25250]
The problem: currently some `StringComparer`s may return different hash codes for strings which they themselves declare to be `Equal()`.

This breaks the fundamental principle that any two equal objects must have same hash, and makes it impossible to safely pass collections of strings to LINQ operators that group and sort them.

The problem was first raised on StackOverflow: https://stackoverflow.com/q/54243461/11683,  
then reported at https://developercommunity.visualstudio.com/content/problem/430327/stringcomparers-may-return-different-hashcodes-for.html.

It was then closed as wontfix because for backward compatibility reasons hash values need to remain the same.

While I understand that reasoning, I also believe that it was documented somewhere that hash codes *may* specifically be different between "very major" versions of .NET, so one should not rely on them staying the same between those.  
Building on that, I believe it would be important **use the upcoming .NET 5 release as an opportunity to fix this hash code issue and change the hash code generation** so that strings that are `Equal()` do have same hash codes like they should.

---
Code to reproduce the issue (also found at the links above):

```cs
static void Main(string[] args)
{
    string s1 = "";
    string s2 = "\0\0\0"; // Can be any number of \0's

    Test(nameof(StringComparer.CurrentCulture), StringComparer.CurrentCulture, s1, s2);
    Test(nameof(StringComparer.CurrentCultureIgnoreCase), StringComparer.CurrentCultureIgnoreCase, s1, s2);
    Test(nameof(StringComparer.InvariantCulture), StringComparer.InvariantCulture, s1, s2);
    Test(nameof(StringComparer.InvariantCultureIgnoreCase), StringComparer.InvariantCultureIgnoreCase, s1, s2);

    Console.ReadLine();
}

private static void Test(string comparer_name, StringComparer sc, string s1, string s2)
{
    Console.WriteLine(comparer_name); // cs.GetType().Name does not return that, unfortunately
    Console.WriteLine("Hash 1: {0}", sc.GetHashCode(s1));
    Console.WriteLine("Hash 2: {0}", sc.GetHashCode(s2));
    Console.WriteLine("Strings equal: {0}", sc.Equals(s1, s2));
    Console.WriteLine();
}
```

**Comment by EgorBo** [comment]
Duplicates https://github.com/dotnet/corefx/issues/34662

**Comment by danmosemsft** [comment]
Thanks for the report. It is a duplicate. I agree it would be good to fix if it could be done without perf effects.
