### ISSUE TITLE
Remove Python dependency

### ISSUE THREAD

**Issue by OtherCrashOverride** [dotnet/coreclr#2525]
The scripts here https://github.com/dotnet/coreclr/tree/master/src/scripts depend on Python.  We should replace them with C# equivalents.  A working C# compiler and runtime is already a dependency to build CoreCLR.  Removing Python lowers the barrier to entry (one less language, runtime and/or IDE) and eliminates breaking changes beyond the control of CoreCLR such as the change from Python2 to 3.

**Comment by ramarag** [comment]
The scripts are used during the native build process of coreclr, as such we try to avoid using any dependencies which would in turn depend on coreclr for building coreclr as this will lead to bootstrapping issues when we try to get the build going on a new platform. [ Though we already have this bootstrapping issue for mscorlib, let us not try to extend it]. That is the reason we did not want to implement the functionality in C#

I understand the issue with transition from Python 2 to 3, we are trying to work around it by using features which are common to both, apart from that we have few good alternatives. If the issue becomes pressing I see us transitioning the functionality to C++ and not C#
