### ISSUE TITLE
Investigate if event pipe sample profiling is not disabled when the client disconnects

### ISSUE THREAD

**Issue by tommcdon** [dotnet/coreclr#25258]
Per https://github.com/dotnet/diagnostics/issues/189#issuecomment-502841560: the sample provider is not disabled when dotnet-trace exits.

**Comment by jorive** [comment]
@tommcdon  We call `SampleProfiler::Enable` but on the method we check if enabled:
https://github.com/dotnet/coreclr/blob/master/src/vm/sampleprofiler.cpp#L88
Is the condition not working? Or is this a refactoring request?

**Comment by tommcdon** [comment]
@jorive I think you are correct.  Reading https://github.com/dotnet/diagnostics/issues/189#issuecomment-502841560 closer it looks like sampling is not disabled when dotnet-trace disconnects.

**Comment by tommcdon** [comment]
duplicate to #25268
