### ISSUE TITLE
Coreclr x64 Jit doesn't optimize first static readonly access

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#2526]
From https://github.com/dotnet/corefx/issues/5152#issuecomment-168791165

Full framework x64 (.NET 4.6.1) jit resolves the first access to a `static readonly` to a constant value; however coreclr x64 embeds initialization checks into the first function jitted that accesses these values; and after that treats them as constants.

This means with full framework you are fine; but with coreclr you don't want the first access to be a hot function.

Difference in jitted output on coreclr:

```
    83:                     case 102:
    84:                         return _bytesStatus102;
00007FFEA7A8DF42  mov         rcx,7FFEA7970B28h  
00007FFEA7A8DF4C  mov         edx,3Fh  
00007FFEA7A8DF51  call        00007FFF0757BC50  
00007FFEA7A8DF56  mov         rcx,20AED0D7BB0h  
00007FFEA7A8DF60  mov         rax,qword ptr [rcx]  
00007FFEA7A8DF63  jmp         00007FFEA7A8E749  
    85:                     case 200:
    86:                         return _bytesStatus200;
00007FFEA7A8DF68  mov         rcx,7FFEA7970B28h  
00007FFEA7A8DF72  mov         edx,3Fh  
00007FFEA7A8DF77  call        00007FFF0757BC50  
00007FFEA7A8DF7C  mov         rcx,20AED0D7BB8h  
00007FFEA7A8DF86  mov         rax,qword ptr [rcx]  
00007FFEA7A8DF89  jmp         00007FFEA7A8E749  
    87:                     case 201:
    88:                         return _bytesStatus201;
00007FFEA7A8DF8E  mov         rcx,7FFEA7970B28h  
00007FFEA7A8DF98  mov         edx,3Fh  
00007FFEA7A8DF9D  call        00007FFF0757BC50  
00007FFEA7A8DFA2  mov         rcx,20AED0D7BC0h  
00007FFEA7A8DFAC  mov         rax,qword ptr [rcx]  
00007FFEA7A8DFAF  jmp         00007FFEA7A8E749  
```

on full framework

```
                    case 102:
                        return _bytesStatus102;
00007FFD82D7133A  mov         rax,2306A5D59A8h  
00007FFD82D71344  mov         rax,qword ptr [rax]  
00007FFD82D71347  jmp         00007FFD82D71781  
                    case 200:
                        return _bytesStatus200;
00007FFD82D7134C  mov         rax,2306A5D59B0h  
00007FFD82D71356  mov         rax,qword ptr [rax]  
00007FFD82D71359  jmp         00007FFD82D71781  
                    case 201:
                        return _bytesStatus201;
00007FFD82D7135E  mov         rax,2306A5D59B8h  
00007FFD82D71368  mov         rax,qword ptr [rax]  
00007FFD82D7136B  jmp         00007FFD82D71781 
```

Which is also the same output if you have already accessed the fields prior to the function being jitted on coreclr.

category:cq
theme:class-init
skill-level:intermediate
cost:medium

**Comment by jkotas** [comment]
This is trade-off between predictable behavior (ie compatibility) and performance. Triggering static constructors during JITing that is required to eliminate the cctor probe on first access results in unpredictable timing of when static constructors run. JIT optimization changes (e.g. changes in inlining heuristic) tend to change the timing. We had a number of cases where these changes broke libraries and applications. Thus, we have opted for slower more predictable code.

BTW: You will get the cctor probe on every access in NGen images. This limits usefulness of this optimization since a lot of code tends to be NGened.

Fixing this is "easy": return false from `MethodTable::RunCCTorAsIfNGenImageExists` for CoreCLR, but dealing with the potential consequences of the fix may be non-trivial.

**Comment by benaadams** [comment]
Not sure I follow. .NET 4.6.1 does the trigger which is ok for compat; but coreclr doing it causes compat issues? Is it in x-plat situations? (these are `beforefieldinit`default cctors). Or is it because they are jitting slightly differently due to using different frameworks?

> BTW: You will get the cctor probe on every access in NGen images. 

Makes sense as you don't have the runtime state of the platform when the code is complied; this would also apply to dotnet `--native`? Something to consider when choosing deployment type and what is in the hot path.

**Comment by omariom** [comment]
Can we have another attribute? SureBeforefieldInit? ;)

**Comment by GSPP** [comment]
There is a [C# language proposal to be able to configure the beforefieldinit behavior](https://github.com/dotnet/roslyn/issues/4448), fyi.

**Comment by benaadams** [comment]
@jkotas this is fixed by Tiered Jit?

**Comment by jkotas** [comment]
Right
