### ISSUE TITLE
Perf: string.Compare() 10x slower on Linux

### ISSUE THREAD

**Issue by wangzhaoguan** [dotnet/coreclr#25274]
the multi-thread concurrent scene, the response time increases linearly with the number of threads, even if The same is true with the core 3.0 Dailybuild version.

===windows dotnet core string.Compare()=====================
C:\Perf\netcoreapp2.1>dotnet ConsoleApp1.dll
Hello World!
1
00:00:00.8478962

C:\Perf\netcoreapp2.1>dotnet ConsoleApp1.dll
Hello World!
4
00:00:00.8120719
00:00:00.8238833
00:00:00.8282159
00:00:00.8294329

C:\Perf\netcoreapp2.1>dotnet ConsoleApp1.dll
Hello World!
8
00:00:00.7845833
00:00:00.8064471
00:00:00.8182836
00:00:00.8183194
00:00:00.8448840
00:00:00.8520638
00:00:00.8669487
00:00:00.8785265

====Linux dotnet core 3.0-latest string.Compare()======================
[root@localhost StrCompare3]# ../dotnet3/DailyBuild0618/dotnet bin/Release/netcoreapp3.0/T03.dll
Hello World!
1
00:00:00.6937323

[root@localhost StrCompare3]# ../dotnet3/DailyBuild0618/dotnet bin/Release/netcoreapp3.0/T03.dll
Hello World!
4
00:00:03.6639762
00:00:03.9747772
00:00:04.0261278
00:00:04.0363920

[root@localhost StrCompare3]# ../dotnet3/DailyBuild0618/dotnet bin/Release/netcoreapp3.0/T03.dll
Hello World!
8
00:00:05.3930968
00:00:05.4181619
00:00:07.2108449
00:00:07.3992779
00:00:07.5118132
00:00:07.7925471
00:00:07.8082617
00:00:07.8567605

===Demo Code==================================================

    static void Main(string[] args)
    {
         Console.WriteLine("Hello World!");
         string input = Console.ReadLine();
         int num = 1;
         int.TryParse(input, out num);
         if (num <= 0)
         {
              num = 1;
         }

        for (int t = 0; t < num; t++)
        {
            Thread td = new Thread(() =>
            {
                DateTime dt = DateTime.Now;
                for (int i = 0; i <= 3000000; i++)
                {
                    string.Compare("t1", "xyz", true);
                }

                Console.WriteLine(DateTime.Now - dt);

            });
            td.Start();
        }

        Console.ReadLine();
    }

**Comment by benaadams** [comment]
Should be fixed in the latest nightly https://github.com/dotnet/coreclr/pull/24973

/cc @adamsitnik

**Comment by wangzhaoguan** [comment]
2019-06-18日的Daily Build版本仍有此问题，重新下载今天的Daily Build版本验证有了大幅提升，希望Release版本是稳定的。
