### ISSUE TITLE
EventPipe IPC CollectTracing operation has an outputPath parameter it does not use

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#25275]
The IPC payload for CollectTracing is implemented to include an output path. This path is never used in the implementation.

We should either use the argument or remove it from the protocol definition.

cc @jorive @josalem

**Comment by noahfalk** [comment]
cc @nattress

**Comment by jorive** [comment]
I would remove it, and if ever needed we could add it back.

**Comment by josalem** [comment]
If I recall, the `OutputPath` argument was originally meant to be used by the runtime, when _it_ was writing the file _a_ _la_ when you turn EventPipe on via environment variables.  Do we have any need for this for the IPC mechanism?  If we do not, I agree, we should remove the field while we still can.

**Comment by noahfalk** [comment]
Just as a heads up, preview7 snap is the last chance for breaking changes. Its not a huge a deal if this doesn't get fixed, but one way or another whatever is in the code Wednesday is how the protocol will be defined forever. Making a change after that point will involve allocating a new command code for an updated version of the API while leaving the previous one in place. FWIW, https://github.com/dotnet/coreclr/issues/25268 seems very likely to trigger a second version of the API in the near future because we'll probably need a flag to control whether rundown is emitted or not.

**Comment by noahfalk** [comment]
> Do we have any need for this for the IPC mechanism?

We are not currently supporting an IPC request that writes the trace to a file, so no it isn't needed right now.

**Comment by josalem** [comment]
Since this would technically be a breaking change, I can go ahead and remove it from the protocol before the snap.

**Comment by jorive** [comment]
> Since this would technically be a breaking change, I can go ahead and remove it from the protocol before the snap.

Yes, please :)
