### ISSUE TITLE
Support for testing with corefx is broken

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#25283]
The test script here: https://github.com/dotnet/coreclr/blob/master/tests/runtest.sh#L90 and the documentation here: https://github.com/dotnet/coreclr/blob/master/Documentation/building/testing-with-corefx.md#running-against-a-cached-copy-of-the-corefx-tests reference the `tests/CoreFX/CoreFXTestListURL*.txt` files that have now been deleted.

In addition, the `tests/scripts/run-corefx-tests.py` script references a path that no longer exists:
```
    fx_runtime = os.path.join(fx_root,
                             'artifacts',
                             'bin',
                             'testhost',
                             'netcoreapp-%s-%s-%s' % (clr_os, 'Release', arch),
                             'shared',
                             'Microsoft.NETCore.App',
                             '9.9.9')
```
It seems that instead of `9.9.9` we now have `3.0.0`. I'm attempting to rebuild with that change, but it may be that it should be determined based on whatever the current version is.

The obsolete references should be removed, and the documentation and appropriate scripts should be updated to reflect the current state.

**Comment by CarolEidt** [comment]
I see that @BruceForstall merged a fix for the `run-corefx-tests.py` script in https://github.com/dotnet/coreclr/pull/25265.
But the documentation issue remains, as well as guidance on the best way to reproduce bugs found in the CI system.

**Comment by BruceForstall** [comment]
@CarolEidt With the latest https://github.com/dotnet/coreclr/blob/master/Documentation/building/testing-with-corefx.md, I think the documentation is now correct. I'm going to close this. Feel free to reopen (or create a new issue) if additional documentation clarification is needed.

**Comment by CarolEidt** [comment]
Yes, it looks good now. Thanks.
