### ISSUE TITLE
Hosting Blazor (client side) in IIS under Core 3 Preview 6 doesn't work

### ISSUE THREAD

**Issue by JoelW187** [dotnet/coreclr#25289]
Hosting Blazor apps in IIS doesn't seem to work under Preview 6. I always get the message "This localhost page can’t be found" (Chrome). The app runs fine in Visual Studio 2019 Preview (16.2.0 Preview 2.0). It also works if I run the server executable from the command line (i.e., WebApplication1.Server.exe) and then navigate the browser to http://localhost:5000. But when I publish the code to an IIS website I get the error. I'm thinking it has something to do with the new MapFallbackToClientSideBlazor call in Startup.Configure (but that's just a guess). Wondering if anyone else is having the same problem OR if anyone else has successfully hosted a Preview 6 Blazor app in IIS (and, yes, I installed the Preview 6 Runtime & Hosting Bundle).

**Comment by sdmaclea** [comment]
@pakrym @jkotalik This seems like this issue belongs in ASP.NET for initial triage.

**Comment by jkotalik** [comment]
@anurse please transfer. Also @JoelW187 can you give use either a repro or a sample application that is seeing this behavior?

**Comment by anurse** [comment]
I can't transfer since I don't have write permission to this repo.

**Comment by anurse** [comment]
@JoelW187 can you please file this in https://github.com/aspnet/AspNetCore ? Then we can triage it appropriately and sort this issue out!

**Comment by sdmaclea** [comment]
Manually transferred to aspnet/AspNetCore#11449
