### ISSUE TITLE
Setting PublishTrimmed=true breaks ASP.NET core applications

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/coreclr#25296]
**Repro:**
- `mkdir MyApp`
- `cd MyApp`
- `dotnet new mvc`
- Add the following to the `MyApp.csproj`
```xml
    <OutputType>Exe</OutputType>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
```
- `dotnet publish -c release` (There will be a bunch of warnings from `ReadyToRunCompiler`)
- Go to the publish folder and open `MyApp.exe` 
- Navigate to https://localhost:5001

**Expected:**
App runs successfully

**Actual:**
500 - `System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

**Workaround:**
Set `PublishTrimmed` to `false`.

Note: This issue does not occur for console applications

<details>
<summary>Dotnet Info</summary>

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by sbomer** [comment]
@ajaybhargavb, could you try adding the following to your project?
```
<ItemGroup>
  <TrimmerRootAssembly Include="System.Threading.Tasks" />
</ItemGroup>
```
In general, we expect to see issues like this due to reflection, and are attempting to provide guidance at https://aka.ms/dotnet-illink - let me know if anything could be made clearer. Since this looks like it will be a very common case, we may be able to make this more automatic in the future (by shipping ASP.NET Core with some default roots, or similar).

**Comment by ajaybhargavb** [comment]
@sbomer, I tried it but that still doesn't help. I get the same error.

**Comment by sbomer** [comment]
@ajaybhargavb adding that root assembly fixes the issue when I try it, using the same version of the SDK that you're using. Did you re-run the publish command after adding the root? Could you make sure your project file matches the following?
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="System.Threading.Tasks" />
  </ItemGroup>

</Project>
```

**Comment by ajaybhargavb** [comment]
@sbomer you are right, it works. I must have messed something up when I tried it the other day. 

> In general, we expect to see issues like this due to reflection, and are attempting to provide guidance at https://aka.ms/dotnet-illink - let me know if anything could be made clearer. Since this looks like it will be a very common case, we may be able to make this more automatic in the future (by shipping ASP.NET Core with some default roots, or similar).

Yes, this looks to be a very common case. It happens in our web project templates.

**Comment by xhanb** [comment]
I ran into a similar problem. My project was built using .net core WPF preview6 and referenced MahApps.Metro 2.0.0-alpha0391.
* **Add the following to the .csproj:**
```C#
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
```
* **then run:**
```C#
dotnet publish -c release
```
* **I get the  error:**
> C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(281,28): error MSB4094: "obj\Release\netcoreapp3.0\win-x64\linked\Microsoft.Win32.Registry.dll;obj\Release\netcoreapp3.0\win-x64\linked\Microsoft.Win32.Registry.dll" is an invalid value for the "CompilationEntry" parameter of the "RunReadyToRunCompiler" task. Multiple items cannot be passed into a parameter of type "Microsoft.Build.Framework.ITaskItem".

**Comment by sbomer** [comment]
@xhanb that looks like a separate issue (https://github.com/dotnet/sdk/issues/3257) which has been fixed. Could you please try the preview7 bits, and if you still see this, open a new issue? Thanks!

**Comment by sbomer** [comment]
Moving to mono/linker.
