### ISSUE TITLE
[Perf] Plaintext scenario allocations

### ISSUE THREAD

**Issue by sebastienros** [dotnet/coreclr#25300]
We detected a regression in allocations on Linux and Windows for Plaintext, which impacts the working set.

Using dotnet counters, the allocation rate increases from `1,146,482` to `12,379,455` in B/s.

![image](https://user-images.githubusercontent.com/1165805/59890757-417ba100-9387-11e9-91c2-2e546f5d4a79.png)

I isolated the issue in NetCore.App between these two versions:
- `3.0.0-preview7-27819-08`
- `3.0.0-preview7-27819-11`

Which point to these commits:
- CoreFX: https://github.com/dotnet/corefx/compare/edc88b0fe55278ee43c821ab05707d8bb0befded...5ec88f81af71d253cfa74f9982abf748ccbd529b
- CoreCLR: https://github.com/dotnet/coreclr/compare/eafa8648ebee92de1380278b15cd5c2b6ef11218...15ece8e1b587edd35af4c092e30e8666b2d9e66f

After taking a trace, this is what appears at the top of the GC/AllocationTick event:

![image](https://user-images.githubusercontent.com/1165805/59890562-50ae1f00-9386-11e9-869b-dc220e206443.png)

And it matches this commit from the changesets above:
https://github.com/dotnet/coreclr/commit/70febbad4bbe23326c26480b2848cdfe9fc8450c

/cc @jkoritzinsky @davidfowl

**Comment by jkotas** [comment]
Fixed by #25292
