### ISSUE TITLE
Guideline for supporting a new CPU architecture

### ISSUE THREAD

**Issue by zhengwb** [dotnet/coreclr#25309]
Although .NET Core now supports x86 and ARM platforms, some people in the community still want to add more CPU architecture. Is it possible to provide a guideline of support a new CPU architecture based on the experience of ARM?

**Comment by danmosemsft** [comment]
@zhengwb I'm curious what architecture(s) you have in mind?

cc @richlander

**Comment by RussKeldorph** [comment]
@zhengwb I'm not aware of a one-stop shop for porting guidance.  The possibility has been discussed in the past, and you might find some useful info in issues #969 and #17294 among others.  #8188 contains a record of bringing up x86/Linux support, though a completely new architecture would probably be quite a bit more work than this was.

I think the way it has been done in the past is to defer the JIT work (the biggest single work item) by bringing up the interpreter on the new platform first.  JIT porting began once basic tests were running.  People have provided additional detail in the issues above, but it's not a definitive guide.  While it would certainly be useful to produce such a guide, Microsoft doesn't plan to create one at this time.  We'd certainly be supportive of a community effort, however.

**Comment by zhengwb** [comment]
> @zhengwb I'm curious what architecture(s) you have in mind?
> 
> cc @richlander

Some customers want our application to run on MIPS.

**Comment by zhengwb** [comment]
> @zhengwb I'm not aware of a one-stop shop for porting guidance. The possibility has been discussed in the past, and you might find some useful info in issues #969 and #17294 among others. #8188 contains a record of bringing up x86/Linux support, though a completely new architecture would probably be quite a bit more work than this was.
> 
> I think the way it has been done in the past is to defer the JIT work (the biggest single work item) by bringing up the interpreter on the new platform first. JIT porting began once basic tests were running. People have provided additional detail in the issues above, but it's not a definitive guide. While it would certainly be useful to produce such a guide, Microsoft doesn't plan to create one at this time. We'd certainly be supportive of a community effort, however.

Thanks a lot, It's very useful. But it's really a big challenge for the first time to do this job.

**Comment by forestbat** [comment]
#https://github.com/dotnet/core/issues/2778

**Comment by MeiChin-Tsai** [comment]
@zhengwb this is Mei-Chin. We don't have official guidance on porting to new architecture. But we don't mind to guide you through it.

**Comment by MetSystem** [comment]
Some customers want our application to run on MIPS.

**Comment by harsha544** [comment]
@MeiChin-Tsai I am evaluating effort required to port coreclr to POWER (ppc64le arch) Systems, is there slack or it's equivalent where I can follow up on guidance to port to new architecture ?

**Comment by patriziobruno** [comment]
https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/botr/guide-for-porting.md

**Comment by richlander** [comment]
I think we can safely close this now.
