### ISSUE TITLE
ETW events broken in daily Preview7 builds

### ISSUE THREAD

**Issue by mjsabby** [dotnet/coreclr#25342]
I noticed that the ETW stackwalker is unable to crawl the stack for our application now. We set the following EventPipe related environment variable.

`SET COMPlus_EnableEventPipe=0`

However, upon further inspection it looks like all ETW events are broken except the following

![image](https://user-images.githubusercontent.com/1930559/59983479-0a023400-95d5-11e9-8769-15813cdf408d.png)

The change that broke this happened in between the following commits

BEFORE --> https://github.com/dotnet/coreclr/commit/fdcfdaf734584ca4b6066a7344eecffeeafdaa9a

AFTER --> https://github.com/dotnet/coreclr/commit/56d57afaab150be6d1cf39869a917efe9ec5ff43

I think the most likely candidate is https://github.com/dotnet/coreclr/pull/25221

@sywhang @noahfalk 

@sywhang notice that some events were not impacted, so maybe that gives you some clue.

**Comment by tommcdon** [comment]
@noahfalk

**Comment by sywhang** [comment]
Just finished root-causing this. I'm verifying my fix now and will be sending out a PR shortly.
