### ISSUE TITLE
Test failure: Interop_PInvoke._Varargs_VarargsTest_VarargsTest_/_Varargs_VarargsTest_VarargsTest_cmd

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#25376]
The test `Interop_PInvoke._Varargs_VarargsTest_VarargsTest_/_Varargs_VarargsTest_VarargsTest_cmd` has failed.

Failure Message:
```
Unhandled exception. System.InvalidProgramException: Vararg calling convention not supported.\r
   at PInvokeTests.VarargsTest.Main()\r
\r
Return code:      1\r
Raw output file:      D:\\dotnetbuild\\work\\9f345f5d-310d-4ab2-820e-52e69849fa06\\Work\\9bb35690-0c47-4d3c-95ea-86c9cdcbcdf3\\Exec\\Interop\\PInvoke\\Reports\\Interop.PInvoke\\Varargs\\VarargsTest\\VarargsTest.output.txt\r
Raw output:\r
BEGIN EXECUTION\r
 \"D:\\dotnetbuild\\work\\9f345f5d-310d-4ab2-820e-52e69849fa06\\Payload\\corerun.exe\" VarargsTest.exe \r
Expected: 100\r
Actual: -532462766\r
END EXECUTION - FAILED\r
FAILED\r
Test Harness Exitcode is : 1\r
To run the test:\r
> set CORE_ROOT=D:\\dotnetbuild\\work\\9f345f5d-310d-4ab2-820e-52e69849fa06\\Payload\r
> D:\\dotnetbuild\\work\\9f345f5d-310d-4ab2-820e-52e69849fa06\\Work\\9bb35690-0c47-4d3c-95ea-86c9cdcbcdf3\\Exec\\Interop\\PInvoke\\Varargs\\VarargsTest\\VarargsTest.cmd\r
Expected: True\r
Actual:   False
```

Stack Trace:
```
   at Interop_PInvoke._Varargs_VarargsTest_VarargsTest_._Varargs_VarargsTest_VarargsTest_cmd() in F:\workspace.1\_work\1\s\bin\tests\Windows_NT.arm.Release\TestWrappers\Interop.PInvoke\Interop.PInvoke.XUnitWrapper.cs:line 8304
```

Build : Master - 20190624.1 (Core Tests)
Failing configurations:
- Windows.10.Arm64-arm
  - 
  - 
Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190624.1/workItem/Interop/analysis/xunit/Interop_PInvoke._Varargs_VarargsTest_VarargsTest_~2F_Varargs_VarargsTest_VarargsTest_cmd

**Comment by AriNuer** [comment]
Tests failed with similar exception:
```
JIT_Directed._PREFIX_unaligned_1_arglist_arglist_/_PREFIX_unaligned_1_arglist_arglist_cmd 
JIT_jit64._gc_misc_funclet_funclet_/_gc_misc_funclet_funclet_cmd
JIT_jit64._mcc_interop_mcc_i00_mcc_i00_/_mcc_interop_mcc_i00_mcc_i00_cmd 
JIT_Methodical._refany__il_dbgseq__il_dbgseq_/_refany__il_dbgseq__il_dbgseq_cmd
JIT_Methodical._Coverage_arglist_pos_arglist_pos_/_Coverage_arglist_pos_arglist_pos_cmd
JIT_Regression._CLR_x86_EJIT_V1_M12_Beta2_b26323_b26323_b26323_/_CLR_x86_EJIT_V1_M12_Beta2_b26323_b26323_b26323_cmd 
JIT_Regression._CLR_x86_JIT_V1_M09_5_PDC_b16423_b16423_b16423_/_CLR_x86_JIT_V1_M09_5_PDC_b16423_b16423_b16423_cmd 
JIT_Regression._CLR_x86_JIT_V1_M12_Beta2_b31745_b31745_b31745_/_CLR_x86_JIT_V1_M12_Beta2_b31745_b31745_b31745_cmd
```
Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190624.1

**Comment by RussKeldorph** [comment]
Related to #25316.

/cc @jashook

**Comment by jashook** [comment]
Correcting related pr: https://github.com/dotnet/coreclr/pull/25320

**Comment by jashook** [comment]
Strange that these tests did not fail during the outerloop testing...

**Comment by jashook** [comment]
Will disable.

**Comment by echesakovMSFT** [comment]
There are around 50 tests that fail on Windows_NT/arm

https://dnceng.visualstudio.com/public/_build/results?buildId=237935&view=ms.vss-test-web.build-test-results-tab&runId=5909370&paneView=debug

**Comment by jashook** [comment]
Trying to investigate why https://dev.azure.com/dnceng/public/_build/results?buildId=234303&view=logs would pass coreclr-outloop started from the PR and https://dev.azure.com/dnceng/public/_build/results?buildId=237121&view=ms.vss-test-web.build-test-results-tab&runId=5884598&paneView=debug failed (merge job).

**Comment by jashook** [comment]
Seems like there is some infrastructure problem with the PR job.

**Comment by jashook** [comment]
Looks like the arm test run was skipped. Even though the coreclr-outerloop job was requested. See https://dev.azure.com/dnceng/public/_build/results?buildId=234303&view=logs

**Comment by VincentBu** [comment]
Also seen in:
https://mc.dot.net/#/user/coreclr-ci/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190625.38/workItem/Interop/analysis/xunit/Interop_PInvoke._Varargs_VarargsTest_VarargsTest_~2F_Varargs_VarargsTest_VarargsTest_cmd
