### ISSUE TITLE
[createdump/Linux] NT_FILE note should have offset in pages.

### ISSUE THREAD

**Issue by makxenov** [dotnet/coreclr#25383]
`createdump` currently writes byte offset into NT_FILE note in minidump when Linux kernel writes page offset in coredumps. So, tools for coredump analysis like `readelf`
![Screenshot from 2019-06-25 17-07-30](https://user-images.githubusercontent.com/48908790/60108619-90ec1380-9771-11e9-8c50-d67712eb208e.png) and `gdb` 
![Screenshot from 2019-06-25 16-57-43](https://user-images.githubusercontent.com/48908790/60108752-d7da0900-9771-11e9-915e-444cf7e4388c.png) can't parse minidumps properly.

**Comment by tommcdon** [comment]
@mikem8361
