### ISSUE TITLE
Some events are always fired and cannot be disabled

### ISSUE THREAD

**Issue by sywhang** [dotnet/coreclr#25405]
Found this while testing https://github.com/dotnet/coreclr/pull/25374. 

These 3 events are always fired via `FireEtw`... methods without checking whether they are enabled:

ThreadPoolWorkerThread/Start
ThreadPoolWorkerThread/Stop
ThreadPoolWorkerThread/Wait

We should add the appropriate checks to not fire them via ETW_PROVIDER_ENABLED macro as appropriate.

**Comment by ehsansajjad465** [comment]
is it still open?
