### ISSUE TITLE
EventListener uses too much memory by default

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#25413]
Discussion was originally started [here](https://github.com/dotnet/coreclr/issues/23562#issuecomment-505424078) 

EventListener is intended to be used for some relatively low overhead scenarios but the implementation still allows high memory usage by default. In 2.2 the default was 1GB which was lowered to 256MB for 3.0, but that still seems large. We could take several actions to improve this:

1) Lower the default significantly, perhaps 10MB?
The buffer grows when the in-proc reader can't keep pace with in-proc writers. If this situation is momentary then the buffer helps absorb brief bursts of load, but if the imbalance is ongoing then it is just a matter of time for any sized buffer to fill after which the steady-state % of events lost will be the same. 
2) Store stacks as variable size instead of fixed size (this accounts for 800 bytes per event)
3) Improve the throughput of the event reader thread so that it can handle higher sustained event processing rates without putting back-pressure on the buffers.

(1) would be pretty cheap for 3.0 and could go a long way to mitigating the issue. (2) and (3) feel more costly and questionable if we could get them done for 3.0.

**Comment by sywhang** [comment]
Actually... I think the default is currently 1024MB: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Diagnostics/Eventing/EventPipeEventDispatcher.cs#L113

**Comment by tommcdon** [comment]
Resolving this issue for now since we have decreased the buffer size from 1 GB to 10 MB, and will revisit this based off of customer feedback
