### ISSUE TITLE
Diagnostics Server IPC thread causes 20-40ms shutdown delays on Windows

### ISSUE THREAD

**Issue by tommcdon** [dotnet/coreclr#25463]
The Diagnostics Server IPC thread on Windows blocks in IpcStream::DiagnosticsIpc::Accept during shutdown.  The blocking call resulting in the shutdown delay is located here:

https://github.com/dotnet/coreclr/blob/b388f6cd87d87f4a07fe966aaa1bc92f245165d9/src/debug/debug-pal/win/diagnosticsipc.cpp#L64

**Comment by tommcdon** [comment]
@jorive @noahfalk @cshung

**Comment by tommcdon** [comment]
Re-opening this issue to track porting the fix to 3.0

**Comment by noahfalk** [comment]
@tommcdon  Are we good with this in 3.1 only? It doesn't seem that it would merit a 3.0 port and the issue is not currently assigned to 3.0 milestone. Recommend we close it.
