### ISSUE TITLE
Debugging core dump - lldb "Failed to start stalk walk: 80070057" on linux host

### ISSUE THREAD

**Issue by MatthewLymer** [dotnet/coreclr#25478]
I am trying to debug a core dump generated from kubernetes node.

## Steps to generate dump

1. Get process id from kubernetes node (`ps -aux | grep <my-container-name>`)
2. Create core dump using `gcore <process-id>` (massive 8.3gb dump due to virtual memory)
3. Open core dump using `lldb-4.0 --core core.32004` (32004 was the pid)

## The result / REPL

	(lldb) target create --core "./core.32004"
	Core file '/mnt/c/Users/Matthew/Downloads/debugging/./core.32004' (x86_64) was loaded.
	(lldb) plugin load /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.5/libsosplugin.so

	(lldb) clrthreads
	ThreadCount:      94
	UnstartedThread:  0
	BackgroundThread: 86
	PendingThread:    0
	DeadThread:       7
	Hosted Runtime:   no
																											Lock
		   ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
	XXXX    1    1 0000000001990250  2020020 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn
	XXXX    2    f 000000000198D5E0    21220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Finalizer)
	XXXX    3   10 00007FC7640009F0  1020220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX    5   13 00007FC76800A460    21220 Preemptive  00007FC779FE8A38:00007FC779FEA8B8 000000000198AD20 0     Ukn
	XXXX    7   16 0000000001BAAEA0  2021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn
	XXXX    8   17 0000000001BD34A0    21220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn
	XXXX   14   31 00007FC744016010  2021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn
	XXXX   15   32 00007FC754018370  2021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn
	XXXX   24 5089 00007FC73C0781B0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   31 515a 00007FC73C0D48A0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   26 515b 00007FC72C084BF0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   30 515c 00007FC72C009C30  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   13 5173 00007FC7440391C0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   27 5184 00007FC744056820  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX    9 5194 00007FC7180655C0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   16 51b4 00007FC73C1D6E70  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   21 51c6 00007FC75C0A4CB0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   17 51e6 00007FC6E00827F0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   22 51e7 00007FC73C06ABF0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   25 51e8 00007FC6C40027E0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   23 51f6 00007FC73C140C10  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   32 520a 00007FC6E00802D0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   10 520e 00007FC7100018D0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   19 5210 00007FC7100094D0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   29 5227 00007FC71000B430  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX    4 522d 00007FC71000FB00  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   20 522e 00007FC75C05CF00  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   11 523c 00007FC71C00EEA0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX    6 523d 00007FC710006DD0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   33 5253 00007FC710008050  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   34 525d 00007FC71000CAD0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   35 525e 00007FC714004B30  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   36 5271 00007FC70C009DB0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   37 5273 00007FC70C0A5A50  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   38 5277 00007FC6E00A66B0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   39 527a 00007FC6E00A7930  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   40 527c 00007FC6B401C710  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   41 5289 00007FC6E00A8BB0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   42 528a 00007FC740035DD0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   43 528e 00007FC6D00008C0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   44 5292 00007FC7400044E0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   28 529e 00007FC6BC0076F0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   45 52a4 00007FC740094830  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   47 52ad 00007FC6C0003650  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   48 52ac 00007FC6B80012B0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   49 52b0 00007FC6AC0012E0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   46 52c2 00007FC71400D450  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   50 52c7 00007FC714003390  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   51 52c8 00007FC714003EC0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   52 52cc 00007FC71400F2F0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   53 52cd 00007FC7140008C0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   54 52d2 00007FC714001760  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   55 52e2 00007FC71400C510  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   56 52f2 00007FC68C003250  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   60 5323 00007FC7140099E0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   59 5324 00007FC7140A20E0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   12    0 00007FC714006A30  1031820 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   18 533f 00007FC678005030  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   63 5340 00007FC674001290  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   64    0 00007FC67C001210  1031820 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   65    0 00007FC6700032C0  1031820 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   66 5354 00007FC678019BF0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   67 5355 00007FC6600157B0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   68 5356 00007FC67800A190  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   62 537e 00007FC7140A2D10  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   61 5381 00007FC714007660  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   58 5388 00007FC714008770  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   57    0 00007FC714010FE0  1031820 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   69 53a2 00007FC654002FA0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   70    0 00007FC6540049B0  1031820 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   71 53a4 00007FC648001290  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   72 53ab 00007FC640001C40  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   73    0 00007FC64C0070B0  1031820 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   74 53ad 00007FC640003970  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   75 540a 00007FC714012260  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   76 540e 00007FC714013D00  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   77 5410 00007FC64C002EE0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   78 5411 00007FC64C00FD30  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   79 5412 00007FC6540012E0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   80 5422 00007FC64C004970  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   81 5423 00007FC654008590  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   84    0 00007FC624003180  1031820 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   83 542c 00007FC620002C50  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   85 542e 00007FC6280023C0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   82 5494 00007FC628004050  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   86 549f 00007FC6280056C0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   87 54af 00007FC620001C90  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   88 54b2 00007FC624019700  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   89 54b1 00007FC61802BFF0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   90 55c7 00007FC604003240  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   91 55d5 00007FC7140158C0  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   92 55d7 00007FC714017480  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   93 55d9 00007FC714019190  3021220 Preemptive  0000000000000000:0000000000000000 000000000198AD20 0     Ukn (Threadpool Worker)
	XXXX   94 55db 00007FC71401AEA0  1021220 Preemptive  00007FC77A0241F0:00007FC77A0248F0 000000000198AD20 0     Ukn (Threadpool Worker)

	(lldb) t 3
	(lldb) * thread #3, stop reason = signal SIGSTOP
		frame #0: libc.so.6`check_arrival(mctx=0x00007fc80f11e000, path=0x0000000000000000, top_node=0, top_str=234390057, last_node=0, last_str=0, type=0) at regexec.c:2878

		
		
	(lldb) clrstack
	OS Thread Id: 0x7dd1 (3)
	Unable to walk the managed stack. The current thread is likely not a
	managed thread. You can run clrthreads to get a list of managed threads in
	the process
	Failed to start stack walk: 80070057

It doesn't matter what thread I switch to, I always get the same "Unable to walk the managed stack".

**Comment by mikem8361** [comment]
gcore doesn't collect all the necessary managed state for SOS to work. I recommend "createdump" that comes with the runtime. See https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md#configurationpolicy. It works like gcore (takes a pid) but collects all the required managed state.

**Comment by MatthewLymer** [comment]
@mikem8361 your suggestion to use `createdump` get's me closer to what I want, now I'm able to do `clrstack` and get a somewhat meaningful stacktrace.

However, now I'm running into the `!Unknown` issue:

```
clrstack
OS Thread Id: 0x1 (1)
        Child SP               IP Call Site
00007FFDA9EBD7C0 00007f8bab58c15f [GCFrame: 00007ffda9ebd7c0]
00007FFDA9EBD8A0 00007f8bab58c15f [HelperMethodFrame_1OBJ: 00007ffda9ebd8a0] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
00007FFDA9EBD9D0 00007F8B3079A192 System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
00007FFDA9EBDA60 00007F8B307509E9 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)
00007FFDA9EBDAC0 00007F8B30750879 System.Threading.Tasks.Task.InternalWaitCore(Int32, System.Threading.CancellationToken)
00007FFDA9EBDB20 00007F8B307ABE96 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
00007FFDA9EBDB40 00007F8B32D2629B /app/Microsoft.AspNetCore.Hosting.dll!Unknown
00007FFDA9EBDB60 00007F8B30C81F17 /app/MyApp.Api.dll!Unknown
00007FFDA9EBDE40 00007f8ba9e2feaf [GCFrame: 00007ffda9ebde40]
00007FFDA9EBE240 00007f8ba9e2feaf [GCFrame: 00007ffda9ebe240]
```

From what I read in other articles that I must pass in `--full` when creating the crashdump otherwise symbols do not get loaded properly, however, when I do so I am greeted with (when using `--diag`):

```
... (lots of these lines)
*00007ffda9ed2000 - 00007ffda9ed4000 (000002) 0000000000000000 45
Writing memory region headers to core file
Writing process information to core file
Writing 20 auxv entries to core file
Writing 563 NT_FILE entries to core file
Writing 19 thread entries to core file
Writing 1113 memory regions to core file
WriteData FAILED Cannot allocate memory
```

Any idea on how to get symbols working?

**Comment by mikem8361** [comment]
Symbol support is in the new SOS from the diagnostics repo.  The !Unknown function issue also has been fixed.  You can install it with the directions here: https://github.com/dotnet/diagnostics#installing-sos.

**Comment by mikem8361** [comment]
I'll file an issue on the createdump --full out of memory issue you hit.

**Comment by MatthewLymer** [comment]
Wow, thanks a lot for your help @mikem8361 !

```
OS Thread Id: 0x1 (1)
        Child SP               IP Call Site
00007FFDA9EBD7C0 00007f8bab58c15f [GCFrame: 00007ffda9ebd7c0]
00007FFDA9EBD8A0 00007f8bab58c15f [HelperMethodFrame_1OBJ: 00007ffda9ebd8a0] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
00007FFDA9EBD9D0 00007F8B3079A192 System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
00007FFDA9EBDA60 00007F8B307509E9 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/Task.cs @ 2978]
00007FFDA9EBDAC0 00007F8B30750879 System.Threading.Tasks.Task.InternalWaitCore(Int32, System.Threading.CancellationToken) [/root/coreclr/src/mscorlib/src/System/Threading/Tasks/Task.cs @ 2917]
00007FFDA9EBDB20 00007F8B307ABE96 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) [/root/coreclr/src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs @ 146]
00007FFDA9EBDB40 00007F8B32D2629B Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(Microsoft.AspNetCore.Hosting.IWebHost) [/_/src/Microsoft.AspNetCore.Hosting/WebHostExtensions.cs @ 60]
00007FFDA9EBDB60 00007F8B30C81F17 MyApp.Api.Startup.Main(System.String[]) [/app/src/MyApp.Api/Startup.cs @ 88]
00007FFDA9EBDE40 00007f8ba9e2feaf [GCFrame: 00007ffda9ebde40]
00007FFDA9EBE240 00007f8ba9e2feaf [GCFrame: 00007ffda9ebe240]
```
