### ISSUE TITLE
Allocations of CultureInfo in Assembly.GetName()

### ISSUE THREAD

**Issue by iSazonov** [dotnet/coreclr#25474]
PerfView shows that PowerShell Core allocates a lot of CultureInfo objects in some scenarios.
There is many calls of Assembly.GetName() in PowerShell type resolver.
Assembly.GetName() calls GetLocale() 
https://github.com/dotnet/coreclr/blob/a64cb0a41a4ebeb4a61b8b0f1f2eeeff8dd539c9/src/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs#L538-L548

Is it possible replace the `new CultureInfo(locale)` with `CultureInfo.GetCultureInfo(locale)`?

/cc @tarekgh

**Comment by jkotas** [comment]
It should be fine. Are you interested in submitting PR?

**Comment by iSazonov** [comment]
I never submitted PR in CoreCLR. If it is as simple as fork and pull the change I am ready.

**Comment by jkotas** [comment]
Yes, it is that simple.
