### ISSUE TITLE
SIGBUS on ARM platform due to unaligned result of operator new()

### ISSUE THREAD

**Issue by kfrolov** [dotnet/coreclr#25475]
We have discovered bug in CoreCLR project, which leads to process termination with SIGBUS signal. Signal caused by access to unaligned data region, address of which region is the result of call to operator new() redefined in EEConfig class:

https://github.com/dotnet/coreclr/blob/6ab02e1cc487c64fb733fbb9d1be653337691aff/src/vm/eeconfig.cpp#L149

````
BYTE g_EEConfigMemory[sizeof(EEConfig)];

void *EEConfig::operator new(size_t size)
{
    CONTRACT(void*) {
        FORBID_FAULT;
        GC_NOTRIGGER;
        NOTHROW;
        MODE_ANY;
        POSTCONDITION(CheckPointer(RETVAL));
    } CONTRACT_END;

    RETURN g_EEConfigMemory;
}
````

As you can see, return value of operator new() here might be unaligned to __BIGGEST_ALIGNMENT__ (as it should be), because g_EEConfigMemory is only byte-aligned by linker.

Currently bug is only reproducible on Tizen/ARM platform (32-bit), when CoreCLR was build in "Checked" mode. In debug or release builds this bug wasn't reproduced because of different memory layout.

We have prepared following patch against this bug (see below), but I think some other solution needed, I think authors of this code should decide...

Patch:
````
diff --git a/src/vm/eeconfig.cpp b/src/vm/eeconfig.cpp
index a11dacd01d..523a9644b3 100644
--- a/src/vm/eeconfig.cpp
+++ b/src/vm/eeconfig.cpp
@@ -151,7 +151,12 @@ HRESULT EEConfig::Setup()
 
 /**************************************************************/
 // For in-place constructor
-BYTE g_EEConfigMemory[sizeof(EEConfig)];
+union
+{
+       BYTE _g_EEConfigMemory[sizeof(EEConfig)];
+       uint64_t dummy;
+       operator void* () { return &dummy; }
+} g_EEConfigMemory;
 
 void *EEConfig::operator new(size_t size)
 {
````

@jkotas @alpencolt

**Comment by RussKeldorph** [comment]
@janvorli
