### ISSUE TITLE
[Windows] GC\\Regressions\\v3.0\\25252\\25252\\25252.cmd fails intermittently

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#25480]
This repros with no stress. See: https://dev.azure.com/dnceng/public/_build/results?buildId=239912&view=ms.vss-test-web.build-test-results-tab&runId=6029722&paneView=attachments&resultId=100001

```
Assert failure(PID 11108 [0x00002b64], Thread: 11792 [0x2e10]): Consistency check failed: AV in clr at this callstack:
------
<no module>! <no symbol> + 0x0 (0x00000000)
-----
.AV on tid=0x2e10 (11792), cxr=0057DAA8, exr=0057DC48
FAILED: false

<no module>! <no symbol> + 0x0 (0x00000000)
    File: f:\workspace\_work\1\s\src\vm\excep.cpp Line: 7601
    Image: C:\dotnetbuild\work\713fef24-f582-4b65-94f5-1fed0c7766b9\Payload\CoreRun.exe


Return code:      1
Raw output file:      C:\dotnetbuild\work\713fef24-f582-4b65-94f5-1fed0c7766b9\Work\da77f33a-5615-422b-8d89-4fd72fa2afa1\Exec\GC\Regressions\Reports\GC.Regressions\v3.0\25252\25252\25252.output.txt
Raw output:
BEGIN EXECUTION
 "C:\dotnetbuild\work\713fef24-f582-4b65-94f5-1fed0c7766b9\Payload\corerun.exe" 25252.exe 
SIGSEGV upcoming
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\dotnetbuild\work\713fef24-f582-4b65-94f5-1fed0c7766b9\Payload
> C:\dotnetbuild\work\713fef24-f582-4b65-94f5-1fed0c7766b9\Work\da77f33a-5615-422b-8d89-4fd72fa2afa1\Exec\GC\Regressions\v3.0\25252\25252\25252.cmd


```

**Comment by jashook** [comment]
Note that this has only failed into two outerloop jobs.

**Comment by jashook** [comment]
See Kusto Query: 

```
TestResults
    | where Method contains "_v3_0_25252_25252_25252_cmd"
        and Result == "Fail"
    | limit  100
    | project Name=JobName, Message, Type, Method, Duration, Exception
| join (Jobs) on Name
    | sort by Started desc 
```

**Comment by jashook** [comment]
@VSadov looks like this test was recently added in #25403

**Comment by jashook** [comment]
Removing windows arm as this failed on x86 windows as well.

**Comment by VSadov** [comment]
The bug was reproducible. If it was not fixed, it should be a failure every time. 
Did the run use the product bits before the fix by any chance?

**Comment by VSadov** [comment]
Or the test may be hitting another bug...

**Comment by jashook** [comment]
For the PR I had, it it very possible that happened as I retried the test legs. I cannot seem to find the second build that kusto is spitting out.

**Comment by jashook** [comment]
Looks like the merge job for #25403  `pr/dotnet/coreclr/refs/pull/25403/merge`. But the build number is missing from ADO...

**Comment by VSadov** [comment]
I also seen a failure on an ancient PR after I forced it to rerun tests.

**Comment by jashook** [comment]
Ah I see that build number must have been superseded when the retry happened. This can be closed then as it has not reprod in any newer jobs.

**Comment by jashook** [comment]
thanks!
