### ISSUE TITLE
[Arm32/Linux] Assert in System.Number.FormatDouble / FormatSingle

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#25487]
When running `System.Tests.RealFormatterTests` from `System.Runtime.Tests` suite and `System.Buffers.Text.Tests.RealFormatterTests` from `System.Memory.Tests` suite, I am consistently hitting assert in `System.Number.FormatSingle(ref ValueStringBuilder sb, single value, ReadOnlySpan<char> format, NumberFormatInfo info)` and `System.Number.FormatDouble(ref ValueStringBuilder sb, double value, ReadOnlySpan<char> format, NumberFormatInfo info)`:
https://github.com/dotnet/coreclr/blob/141d587472ee2fe6ab522c603c352936defeaac3/src/System.Private.CoreLib/shared/System/Number.Formatting.cs#L562
https://github.com/dotnet/coreclr/blob/141d587472ee2fe6ab522c603c352936defeaac3/src/System.Private.CoreLib/shared/System/Number.Formatting.cs#L650
I have debugged the Single version and I could see that at it has called the NumberToSingle, so the last part of the conditional expression was executed.

The tests call these methods ofter with various arguments and only one of the cases actually triggered the assert. I have not looked into which values were problematic.

**Comment by RussKeldorph** [comment]
@tannergooding

**Comment by tannergooding** [comment]
@janvorli, are you on the latest sources? This was believed to have been resolved in https://github.com/dotnet/coreclr/pull/25096

**Comment by tannergooding** [comment]
It would also be helpful if you could share what the input value is and what the current state of NumberBuffer is. I'll work on trying to get a repro together, but if you already have an environment it may be much faster if you could share as well.

**Comment by RussKeldorph** [comment]
Curious if this might also be related to #25468 since, assuming the two numbers output in the assertion are decimal, both numbers happen to be exactly representable by a float32.

**Comment by tannergooding** [comment]
Do we ensure that `FPSCR.FZ==0` as part of ARM32 state setup?

If not, and it is set to `1` instead, then denormals would be flushed to zero for all float/double inputs of all instructions; which could result in differences for some operations...

**Comment by janvorli** [comment]
I am just wrapping up stuff before my week of vacations (I only have an hour left now), so I am unable to get more details on this.
However, I have checked if I've built stuff that includes the change in #25096 and I found my state was two days older, so it is possible that that change fixed that.

**Comment by tannergooding** [comment]
I'm not able to repro on Windows on ARM with the latest (but am with a build from before the change).

I can't test Linux until later tonight as I don't have a device handy.

**Comment by RussKeldorph** [comment]
@tannergooding Did you get a change to try on Linux?

**Comment by tannergooding** [comment]
Sorry. I haven't had the chance to look yet. I got pulled onto some other work. I'll need to see if I can find my rPi 2...

**Comment by janvorli** [comment]
I've verified that I cannot repro the issue anymore on my RPI3, so I believe it was really fixed.
