### ISSUE TITLE
ReadyToRunInfo::GetEntryPoint event is expensive

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#25492]
@brianrob from https://github.com/dotnet/coreclr/pull/23662#issuecomment-506911715 :

Yes, I intend to move this so it doesn't get enabled by default. @billwert and I were discussing this a few weeks back.

**Comment by tommcdon** [comment]
@brianrob are you intending to fix this for .NET Core 3, if so can you prep a PR before 7/9?

**Comment by brianrob** [comment]
@tommcdon yes, and yes.  Thanks for the ping on this.

**Comment by tommcdon** [comment]
Thanks @brianrob!
