### ISSUE TITLE
Formatting Windows_NT x64 CI leg failing 100%

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#25499]
This failure was introduce by deployment of updated VS2017 build images with broken VS C++ installation (parts of the default UCRT are missing in the image).

https://github.com/dotnet/coreclr/pull/25444 worked around this issue for build legs. The formatting leg needs a different workaround.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by erozenfeld** [comment]
Fixed by #27514.
