### ISSUE TITLE
Bad globalization behavior in docker with CultureInfo.CurrentCulture

### ISSUE THREAD

**Issue by reality77** [dotnet/coreclr#25506]
**Issue**

The current culture is not used correctly when displaying a date in a docker environment

**How to reproduce**

A simple test to reproduce this issue can be found here https://github.com/reality77/culture-test

**Info**

dotnet

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.204
 Commit:    8757db13ec

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.204/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.204 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

docker

`Docker version 18.06.1-ce, build e68fc7a`

**Comment by reality77** [comment]
After other researchs, I found the issue.

I am using the mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine image.
This image doesn't seem to have other locales than English.

It works fine with the standard image : mcr.microsoft.com/dotnet/core/aspnet:2.2

**Comment by jkotas** [comment]
.NET Core Alpine docker images are built with [globalization invariant mode](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md) to make them as small as possible.

If your app needs full globalization support, you can use Debian or Ubuntu based images.
