### ISSUE TITLE
Test failed: Interop_ICustomMarshaler._Primitives_ICustomMaraler_ICustomMaraler_._Primitives_ICustomMarshaler_ICustomMarshaler_sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25509]
**Job:**
https://mc.dot.net/#/user/coreclr-gcstress-extra/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190629.1/workItem/Interop/analysis/xunit/Interop_ICustomMarshaler._Primitives_ICustomMaraler_ICustomMaraler_~2F_Primitives_ICustomMarshaler_ICustomMarshaler_sh

**Failed tests:**
Interop_ICustomMarshaler._Primitives_ICustomMaraler_ICustomMaraler_._Primitives_ICustomMarshaler_ICustomMarshaler_sh

**Log:**
```
/root/helix/work/workitem/Interop/ICustomMarshaler/Primitives/ICustomMarshaler/ICustomMarshaler.sh: line 259:  1356 Aborted                 (core dumped) $LAUNCHER $ExePath \"${CLRTestExecutionArguments[@]}\"

Return code:      1
Raw output file:      /root/helix/work/workitem/Interop/ICustomMarshaler/Reports/Interop.ICustomMarshaler/Primitives/ICustomMarshaler/ICustomMarshaler.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun ICustomMarshaler.exe ''
Discovering...
Running 25 of 25 tests...
Finished: 25 tests in 379.385s (0 failed, 0 skipped)
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Interop/ICustomMarshaler/Primitives/ICustomMarshaler/ICustomMarshaler.sh
Expected: True
Actual:   False
```

**Comment by BruceForstall** [comment]
GCStress=C, ZapDisable, JitStress=2

**Comment by RussKeldorph** [comment]
Looks like a one-off failure that passed on the next run.  I suspect this is a reliability issue like #24028 that just happened to hit this test this time.  I'm not sure this is going to be actionable without a crashdump.

@VSadov
