### ISSUE TITLE
Test failed: ilasm_System._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25510]
**Job:**
https://mc.dot.net/#/user/coreclr-gcstress-extra/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190629.1/workItem/PayloadGroup0/analysis/xunit/ilasm_System._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_~2F_Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_sh

**Failed tests:**
ilasm_System._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_sh

**Log:**
```
Return code:      1
Raw output file:      /home/helixbot/work/8a6018bc-45e6-42d2-a3c8-0aa958a91fed/Work/21f80e77-4aaa-40a3-a3c4-fb7a50c11df0/Exec/ilasm/System/Reports/ilasm.System/Runtime/CompilerServices/MethodImplOptionsTests/MethodImplOptionsTests.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/8a6018bc-45e6-42d2-a3c8-0aa958a91fed/Payload/corerun MethodImplOptionsTests.exe ''
AggressiveOptimizationTest

Assembling 'MiAggressiveOptimization.il'  to DLL --> 'MiAggressiveOptimization.dll'
Source file is ANSI

Assembled method Program::Main
Creating PE file

Emitting classes:
Class 1:\tProgram

Emitting fields and methods:
Global \t
Class 1\tMethods: 1;\t

Emitting events and properties:
Global \t
Class 1\t
Writing PE file
Operation completed successfully
Timed out waiting for ilasm to exit
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/8a6018bc-45e6-42d2-a3c8-0aa958a91fed/Payload
> /home/helixbot/work/8a6018bc-45e6-42d2-a3c8-0aa958a91fed/Work/21f80e77-4aaa-40a3-a3c4-fb7a50c11df0/Exec/ilasm/System/Runtime/CompilerServices/MethodImplOptionsTests/MethodImplOptionsTests.sh
Expected: True
Actual:   False
```

**Comment by BruceForstall** [comment]
GCStress=C, ZapDisable, HeapVerify=1

**Comment by RussKeldorph** [comment]
Test is hitting an internal timeout, usually under `Checked-gcstress0xc_zapdisable_heapverify1` config, but once under Checked-gcstress0xc_zapdisable_jitstress2`.  If the internal timeout can be removed in favor of the overall workitem timeout, that might be preferred.

@kouvel @sergiy-k

**Comment by sergiy-k** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/26258
