### ISSUE TITLE
PublishReadyToRun should not compile mscorlib

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#25522]
ReadyToRun compilation of self-contained apps compiles mscorlib.dll to generate the native image. 

See: https://github.com/dotnet/sdk/pull/3381 where an SDK test failed recently, because mscorlib.ni.pdbs started showing up in app publish directory (unexpectedly). 

This issue tracks shipping the native image in the .net core runtime-pack.

**Comment by sergiy-k** [comment]
@fadimounir, should this be fixed in 3.0?

**Comment by fadimounir** [comment]
We could fix it for 3.0 yes. I'll take a look to figure out what needs to be done to fix this issue

**Comment by fadimounir** [comment]
mscorlib has code because of some attribute types emitted by the C# compiler. The compiler should be tweaked to not do this.

**Comment by sergiy-k** [comment]
I assume this was introduce by the NRT feature in Roslyn?
/cc: @agocke

**Comment by safern** [comment]
This was introduced by me: https://github.com/dotnet/corefx/commit/797afb9194c3d69a12e838b331179043a61c9542

I'm fixing this now. cc: @danmosemsft @wtgodbe this will need to go into 3.0 branch.

**Comment by safern** [comment]
@fadimounir does this has to go into preview 7?

**Comment by fadimounir** [comment]
@safern no, it can go with the final 3.0 release.

**Comment by sergiy-k** [comment]
Preview 8, right?
