### ISSUE TITLE
Test failed: Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25528]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstress2-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190701.1/workItem/System.Security.Cryptography.Csp.Tests/analysis/xunit/System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span~2FRsaCryptRoundtrip_OaepSHA1

**Log:**
```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : An internal error occurred
```

**Comment by BruceForstall** [comment]
JitStress=2, JitStressRegs=4

**Comment by RussKeldorph** [comment]
@AndyAyersMS If this isn't specific to jitstress, please notify corefx owner (bartonjs?).

**Comment by AndyAyersMS** [comment]
I can't repro this, and it looks like it has only happened one time. Will keep trying for a while....

**Comment by bartonjs** [comment]
"An internal error occurred" == NTE_FAIL, which means that Windows hit an internally inconsistent state.  Their answers upon inquiry have been (paraphrased) "shrug it off, it happens".  If we can catch it as a stable repro, amazing.  If we can catch it under time travel debugging, actionable.  Otherwise it's not actionable (they've also consistently avoided answering if it's safe for the managed layer to add a retry in these cases, so we don't).

**Comment by bartonjs** [comment]
(I've tried GCStress-based runs, in case it was us moving a buffer or something similar... but no repro to be found)

**Comment by AndyAyersMS** [comment]
Thanks.... my only trick for reproing these is to run on heavily loaded machines, so will try that for a while. Know any way to tell xunit to just runt tests repeatedly... ? Looks like there isn't.

**Comment by bartonjs** [comment]
> Know any way to tell xunit to just runt tests repeatedly

Nope,

```cmd
for /L %a in (1,1,10000) do @(
echo BEGINNING RUN %a
command_goes_here
)
```

(direct command invocation, not escaped for being in a .cmd/.bat)

is the best I came up with.

**Comment by AndyAyersMS** [comment]
Let it run overnight and have 5 failures (out of about 5000 runs), but not the one above:
* 4x       Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : A device attached to the system is not functioning.
* 1x       System.Security.Cryptography.CryptographicException : Cryptography_OAEPDecoding

**Comment by AndyAyersMS** [comment]
Got one more System.Security.Cryptography.CryptographicException : Cryptography_OAEPDecoding, so 6 in all over 10,000 runs. Failing test cases were:
```
System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span.RsaCryptRoundtrip_OaepSHA1 [FAIL]
System.Security.Cryptography.Rsa.Tests.SignVerify_Array.UseAfterDispose(importKey: False) [FAIL]
System.Security.Cryptography.Csp.Tests.RSACryptoServiceProviderBackCompat.ApiInterop_OldToNew [FAIL]
System.Security.Cryptography.Rsa.Tests.SignVerify_Span.InvalidKeySize_DoesNotInvalidateKey [FAIL]
System.Security.Cryptography.Csp.Tests.RSACryptoServiceProviderBackCompat.ApiInterop_OldToNew_Positional [FAIL]
System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span.RsaDecryptAfterExport [FAIL]
```
I'll see if I can catch a failure with time travel debugging.

**Comment by BruceForstall** [comment]
@AndyAyersMS are you repro'ing this with baseline switches (e.g., `COMPlus_TieredCompilation=0`), or with the JitStress=2, JitStressRegs=4 (and implicit `COMPlus_TieredCompilation=0`) this bug was opened with?

**Comment by AndyAyersMS** [comment]
So far I've been running with stress settings, but I'm guessing this will repro without. Even if it only repros with stress, it might not be codegen related -- could be that stress alters timing and makes it more likely to expose a race or something similar.

**Comment by AndyAyersMS** [comment]
Hmm, ttt not happy:
```
Microsoft (R) TTTClient 2.03.06
Release: 10.0.16235.1007
...
Running "E:\repos\corefx\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-x64\dotnet.exe" xunit.console.dll System.Security.Cryptography.Csp.Tests.dll -xml testResults.xml -nologo -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=OuterLoop -notrait category=failing -maxthreads unlimited
...
Warning: Nirvana reported an unsupported instruction at address 0x7ffaf865395b
```

**Comment by AndyAyersMS** [comment]
Updated to newer TTT and this is now running under tracing.

However, under TTT, the full test assembly appears to be running very very slowly, so there is nochance  I can get the 1500 or so runs in that seem to be needed to repro the failures.

Original version took around 7.5 seconds, so you could expect to see one failure every 3 hours or so.

The version running under TTT has not completed the first run yet and has been running ~4 hours.... maybe there is some way to lighten up TTT or run less stuff, but I'd have to try and repro the bug without TTT first to be sure it is still possible.

**Comment by AndyAyersMS** [comment]
Trying to see if this will repro without any special COMPlus settings... about 1000 iterations in and no luck so far.

**Comment by AndyAyersMS** [comment]
Got a repro of a similar failure w/o stress settings (after 1457 runs):
```
      Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : A device attached to the system is not functioning.
      Stack Trace:
        E:\repos\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\CapiHelper.Windows.cs(1214,0): at Internal.NativeCrypto.CapiHelper.SignValue(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash)
        E:\repos\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.Windows.cs(507,0): at System.Security.Cryptography.RSACryptoServiceProvider.SignHash(Byte[] rgbHash, Int32 calgHash)
        E:\repos\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.Windows.cs(444,0): at System.Security.Cryptography.RSACryptoServiceProvider.SignData(Byte[] buffer, Int32 offset, Int32 count, Object halg)
        E:\repos\corefx\src\System.Security.Cryptography.Csp\tests\RSACryptoServiceProviderBackCompat.cs(46,0): at System.Security.Cryptography.Csp.Tests.RSACryptoServiceProviderBackCompat.ApiInterop_OldToNew_Positional()
```
Pretty sure this is not a codegen issue at this point.

@bartonjs do you have an open issue anywhere I could link to?

**Comment by bartonjs** [comment]
@AndyAyersMS You can call it https://github.com/dotnet/corefx/issues/38837.  Do you have a TTD trace?  If not, it'll just sit with all the other "Windows mysteriously intermittently fails, and their dev team seem to think that's OK" unactionable reports.

**Comment by AndyAyersMS** [comment]
Sorry, no trace. Using TTD took > 4hrs for just one test run; it would take months to get a TTD repro at this rate.

Not sure why TTD has so much overhead here. I've seen claims that the overhead is ~30x worst case, which if true, might allow us to get a trace in a few days, but the overhead I see is way beyond that.

I'm going to close this; if we see more repros (we've just had one in CoreCLR CI) or come up with some other clever idea, we can revisit.
