### ISSUE TITLE
Add Span<T>.AsReadOnly()

### ISSUE THREAD

**Issue by lidgren** [dotnet/coreclr#25521]
As far as I can tell; there's no way to convert an instance of `Span<T>` to a `ReadOnlySpan<T>` without having a reference to the underlying data. Adding the method `AsReadOnly()` to `Span<T>` or a constructor/implicit conversion to `ReadOnlySpan<T>` would be useful.

**Comment by tannergooding** [comment]
`Span<T>` is already implicitly convertible to `ReadOnlySpan<T>`: https://source.dot.net/#System.Private.CoreLib/shared/System/Span.Fast.cs,301

**Comment by tannergooding** [comment]
(Closing since you listed implicit conversion as covering this, feel free to reopen if you strongly feel a constructor or explicit method is still needed).
