### ISSUE TITLE
App will crash when using the when keyword in a catch expression

### ISSUE THREAD

**Issue by walterlv** [dotnet/coreclr#25534]
We know that we can add a when keyword after a catch filter. But if there is another exception happened in the when expression, the app will totally crash.

This happens in .NET Framework 4.8 but in .NET Core 3.0, it works correctly as the document says.

Maybe this is a bug in the .NET Framework 4.8 CLR.

---

## The `when` in the official document

You can view the official document here:

- [Using User-Filtered Exception Handlers - Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/using-user-filtered-exception-handlers)

There is such a sentence here:

> The expression of the user-filtered clause is not restricted in any way. If an exception occurs during execution of the user-filtered expression, that exception is discarded and the filter expression is considered to have evaluated to false. In this case, the common language runtime continues the search for a handler for the current exception.

When there is an exception occurred in the when expression the exception will be ignored and the expression will return false.

## A demo

We can write a demo to verify this behavior of the official document.

```csharp
using System;
using System.IO;

namespace Walterlv.Demo.CatchWhenCrash
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            try
            {
                try
                {
                    Console.WriteLine("Try");
                    throw new FileNotFoundException();
                }
                catch (FileNotFoundException ex) when (ex.FileName.EndsWith(".png"))
                {
                    Console.WriteLine("Catch 1");
                }
                catch (FileNotFoundException)
                {
                    Console.WriteLine("Catch 2");
                }
            }
            catch (Exception)
            {
                Console.WriteLine("Catch 3");
            }
            Console.WriteLine("End");
        }
    }
}
```

Obviously, the `FileName` property will keep `null` in the first when expression and will cause a `NullReferenceException`. It is not recommended to write such the code but it can help us verify the behavior of the `catch`-`when` blocks.

If the official document is correct then we can get the output as `Try`-`Catch 2`-`End` because the exception in the `when` will be ignored and the outer `catch` will not catch it and then the `when` expression returns false so that the exception handling goes into the second one.

## In .NET Core 3.0 and in .NET Framework 4.8

The pictures below show the actual output of the demo code above in .NET Core 3.0 and in .NET Framework 4.8.

![.NET Core 3.0](https://user-images.githubusercontent.com/9959623/60511400-729f8e00-9d04-11e9-8141-f0ef9b7a757b.png)

![.NET Framework 4.8](https://user-images.githubusercontent.com/9959623/60511422-7d5a2300-9d04-11e9-8195-138dd379ff48.png)

Only in the .NET Core 3.0, the output behaves the same as the official document says. But in .NET Framework 4.8, the `End` even not appear in the output. We can definitely sure that the app crashes in .NET Framework 4.8.

If we run the app step by step in Visual Studio, we can see that a CLR exception happens.

![CLR error](https://user-images.githubusercontent.com/9959623/60511439-88ad4e80-9d04-11e9-89f9-50725f9fa94a.png)

This animated picture below shows how the code goes step by step.

![Step debugging](https://user-images.githubusercontent.com/9959623/60511487-b0041b80-9d04-11e9-9f9a-9aa7c6ba23f2.gif)

**Comment by janvorli** [comment]
This issue is a .NET Framework 4.8 problem, nothing to do in coreclr.

**Comment by jkotas** [comment]
This behavior change was introduced by a security fix in .NET Framework 4.8. From https://github.com/microsoft/dotnet/blob/master/releases/net48/dotnet48-changes.md: 

Process corrupting exceptions in exception filter (like access violation) now result in aborting the current process. [110375, clr.dll, Bug, Build:3694]

The previous behavior can be enable via legacyCorruptedStateExceptionsInFilterPolicy configuration switch.

**Comment by walterlv** [comment]
@jkotas Thanks for telling me this release note and the configuration switch.
