### ISSUE TITLE
The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found

### ISSUE THREAD

**Issue by hynguyen2610** [dotnet/coreclr#2553]
I have VS 2015 community installed with C++ (all ticked, ,included VS tool for C++), but when run the build.bat, I got this error (Log attached)
[log.txt](https://github.com/dotnet/coreclr/files/80654/log.txt)

Build FAILED.
"c:\git\coreclr-master\bin\obj\Windows_NT.x64.Debug\install.vcxproj" (default target) (1) ->
"C:\git\coreclr-master\bin\obj\Windows_NT.x64.Debug\ALL_BUILD.vcxproj" (default target) (2) ->
"C:\git\coreclr-master\bin\obj\Windows_NT.x64.Debug\src\jit\dll\ClrJit.vcxproj" (default target) (3) ->
"C:\git\coreclr-master\bin\obj\Windows_NT.x64.Debug\ZERO_CHECK.vcxproj" (default target) (4) ->
(PlatformPrepareForBuild target) -> 
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\git\coreclr-master\bin\obj\Windows_NT.x64.Debug\ZERO_CHECK.vcxproj]

**Comment by jashook** [comment]
Closing, stale
