### ISSUE TITLE
Profiler memory leaks under .NET Core v3.0.0-preview6

### ISSUE THREAD

**Issue by ww898** [dotnet/coreclr#25567]
Sometimes one or two times from about 100 runs I got profiler memory leaks because CoreCLR doesn't call `Release()` for profiler. Looks that this block of code in CoreCLR wasn't called: https://github.com/dotnet/coreclr/blob/67a66156d0307b49522a13618522d289268bc1f9/src/vm/eetoprofinterfaceimpl.cpp#L912-L983 The managed application should be short to reproduce the bug:  mine one contains only one `Console.WriteLine("QQQ");`.Only .NET Core v3.0.0-preview6 tests are flaky.  .NET Core v1.x/2.x are stable.

Part of logs with leaks:
```
000011BC 1 0000000000000000 BProf::Shutdown res=ok
000011BC 0 0000000000000000 ProcessDetach
000011BC 0 0000000000000000 SEU::Term
000011BC 0 0000000000000000 SEU::Term res=ok
000011BC 0 0000000000000000 Finished
Detected memory leaks!
Dumping objects ->
{3787} normal block at 0x000001D9720B2CF0, 96 bytes long.
 Data: < 7>/            > E0 37 3E 2F FE 7F 00 00 01 00 00 00 01 00 00 00 
{3253} normal block at 0x000001D97214A940, 32 bytes long.
 Data: <                > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
{3231} normal block at 0x000001D9720900C0, 8 bytes long.
 Data: <        > 00 00 00 00 00 00 00 00 
```

Part of logs without leaks:
```
0000180C 1 0000000000000000 BProf::Shutdown res=ok
0000180C 0 0000000000000000 BProf::Release totalRef=6 ref=6
0000180C 0 0000000000000000 BProf::Release totalRef=5 ref=5
0000180C 0 0000000000000000 BProf::Release totalRef=4 ref=4
0000180C 0 0000000000000000 BProf::Release totalRef=3 ref=3
0000180C 0 0000000000000000 BProf::Release totalRef=2 ref=2
0000180C 0 0000000000000000 BProf::Release totalRef=1 ref=1
0000180C 0 0000000000000000 BProf::Release totalRef=0 ref=0
0000180C 1 0000000000000000 BProf::DeleteProfiler hasDetachDoneEvent=false
0000180C 0 0000000000000000 BProf::DeleteProfiler res=ok
0000180C 0 0000000000000000 SEU::Disable ref=0
0000180C 0 0000000000000000 ProcessDetach
0000180C 0 0000000000000000 SEU::Term
0000180C 0 0000000000000000 SEU::Term res=ok
0000180C 0 0000000000000000 Finished
```

**Comment by tommcdon** [comment]
@davmason @noahfalk

**Comment by davmason** [comment]
Hi @ww898, this is expected if you have profiler code that is still executing inside the process when you call detach. If we detect that you are trying to detach and another thread is still executing code in a callback then we skip cleanup because it would cause the other thread to crash and potentially bring down the whole process.

Can you verify if that is the case you are seeing?

**Comment by ww898** [comment]
Hi @davmason, I have checked all my tests, I got memory leaks in tests where there are no attach and detach.

**Comment by davmason** [comment]
We will skip freeing the profiler if a profiler is currently executing code inside the runtime even during the non-detach case (i.e. at process shutdown). Could you verify that you don't have any other threads currently calling in to the runtime when you see the leak?

**Comment by ww898** [comment]
Hi @davmason, I think that the root of all problems is receiving `ICorProfilerCallback` calls after `ICorProfilerCallback::Shutdown()`. It' a good question why! I had implemented the protection against it in my profiler - callback are ignored after `ICorProfilerCallback::Shutdown()`. I think that `ProfilingAPIUtility::IsProfilerEvacuated()` detected the issue above. And very important thing: I got the issue in test profiler == all callbacks are empty.

**Comment by davmason** [comment]
@ww898 what is your profiler doing? I will spend some time investigating but it might be reliant on specific features, any information you can give me would help

**Comment by davmason** [comment]
@ww898 I spent some time testing this, I ran a sample profiler in a loop and never saw the behavior you described. If you can either give me more details or a memory dump of the issue it would help track this down.

**Comment by noahfalk** [comment]
It appears this issue has gone dead, closing for now. We can reopen if needed.
