### ISSUE TITLE
[Linux ARM64] Step controls causes debugger to crash

### ISSUE THREAD

**Issue by WardenGnaw** [dotnet/coreclr#25575]
Step controls (in, over, out) cause the debugger to crash due to `symbol lookup error: ...libmscoredbi.so: undefined symbol: FPFillR8`

Possible reason is this line is missing ARM64 https://github.com/dotnet/coreclr/blob/e985b20260631c98a09f08cb67e93d690a6ffd0b/src/debug/di/CMakeLists.txt#L94

and there is no `coreclr/src/debug/di/arm64/floatconversion.S`

@tommcdon @hoyosjs

**Comment by tommcdon** [comment]
@sdmaclea
