### ISSUE TITLE
Rename WIN64EXCEPTIONS to FEATURE_EH_FUNCLETS

### ISSUE THREAD

**Issue by k15tfu** [dotnet/coreclr#25571]
Found surprising the fact it's defined when building Linux x64. Just want to confirm that it's not an error =)

**Comment by jkotas** [comment]
WIN64EXCEPTIONS means funclet-based exception handling. It is expected to be defined on Linux. It means the same thing as `FEATURE_EH_FUNCLETS` that is used in part of the codebase.

We should rename `WIN64EXCEPTIONS` to `FEATURE_EH_FUNCLETS` after we fork for 3.0 to avoid this confusion.
