### ISSUE TITLE
Test failed: Loader_classloader._DefaultInterfaceMethods_aredgenerics_aredgenerics_d_aredgenerics_d_._DefaultInterfaceMethods_sharedgenerics_sharedgenerics_d_sharedgenerics_d_sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25587]
**Job:**
https://mc.dot.net/#/user/coreclr-gcstress-extra/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190706.1/workItem/Loader.classloader/analysis/xunit/Loader_classloader._DefaultInterfaceMethods_aredgenerics_aredgenerics_d_aredgenerics_d_~2F_DefaultInterfaceMethods_sharedgenerics_sharedgenerics_d_sharedgenerics_d_sh

**Failed tests:**
Loader_classloader._DefaultInterfaceMethods_aredgenerics_aredgenerics_d_aredgenerics_d_._DefaultInterfaceMethods_sharedgenerics_sharedgenerics_d_sharedgenerics_d_sh

**Log:**
```
/root/helix/work/workitem/Loader/classloader/DefaultInterfaceMethods/sharedgenerics/sharedgenerics_d/sharedgenerics_d.sh: line 252:  1547 Segmentation fault      $LAUNCHER $ExePath \"${CLRTestExecutionArguments[@]}\"

Return code:      1
Raw output file:      /root/helix/work/workitem/Loader/classloader/Reports/Loader.classloader/DefaultInterfaceMethods/sharedgenerics/sharedgenerics_d/sharedgenerics_d.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun sharedgenerics_d.exe ''
Calling IFoo<string>.Foo on FooBar<string, object> - expecting default method IFoo<string>.Foo
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Loader/classloader/DefaultInterfaceMethods/sharedgenerics/sharedgenerics_d/sharedgenerics_d.sh
Expected: True
Actual:   False
```

**Comment by BruceForstall** [comment]
Related? https://github.com/dotnet/coreclr/issues/25586

**Comment by fadimounir** [comment]
Similar to #25586, can't repro even with running the test in a loop with a few combinations of stress modes (jitstress/heapverify/gcstress). Closing issue.
