### ISSUE TITLE
Question: Is it possible to get a callstack (IP/SP only) with managed/coreclr frames using standard tools on Linux/MacOs?

### ISSUE THREAD

**Issue by k15tfu** [dotnet/coreclr#25607]
Hi!

In 
[Debugging CoreCLR on Linux and macOS](https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md#debugging-coreclr-on-linux-and-macos) it's said that for debugging managed programs I have to use lldb with SOS.
Does it mean that I can't get a sequence of frames with IP/SP using GDB/libunwind/whatever?

Do managed frames conform to System V AMD64 ABI calling convention on Linux/MacOs?

**Comment by mattwarren** [comment]
> Does it mean that I can't get a sequence of frames with IP/SP using GDB/libunwind/whatever?

Interestingly enough, CoreCLR itself uses [libunwind](https://github.com/dotnet/coreclr/search?o=desc&q=libunwind&s=committer-date&type=Commits) for stack-walking on Linux/MacOS (it even has its [own copy of the source](https://github.com/dotnet/coreclr/tree/master/src/pal/src/libunwind)). 

However (as far as I understand it), this will only help for 'native frames' on the stack. 'Managed frames' are a bit more complicated and they require more information that only the Runtime itself understands. For more info see the BOTR entry ['Stackwalking in the CLR'](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/stackwalking.md#making-frames-crawlable) ('Making Frames Crawlable') and `<shameless plug>` I also wrote a blog post about the same topic ["Stack Walking" in the .NET Runtime](https://mattwarren.org/2019/01/21/Stackwalking-in-the-.NET-Runtime/#unwinding-jitted-code) `</shameless plug>`

> Do managed frames conform to System V AMD64 ABI calling convention on Linux/MacOs?

See [CLR ABI - System V x86_64 support](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md#system-v-x86_64-support) for some information on this

**Comment by janvorli** [comment]
Right, managed frames use Windows style unwind info on all platforms, so GDB / libunwind cannot unwind those. 
As for the System V AMD64 ABI, managed code conforms to that.

**Comment by k15tfu** [comment]
@mattwarren nice article, thanks! :)

@janvorli I'm asking because sometimes during stack unwinding I get a frame (i.e. IP) which is not managed (in terms of GetFunctionFromIP), but it has non-standard convention and libunwind & GDB is unable to unwind this frame correctly. This pice of code has no prologue/epilogue, it has only few instructions, doesn't have a debug info, and it doesn't belong to any module. I think it may be some kind of trampoline, tail call, or a stub function, which is also produced by JIT (probably), but I don't understand how to unwind it to get a managed frame for DoStackSnapshot.

Do you have any thoughts what it is, how to unwind it, and why the runtime doesn't unwind it by itself?

**Comment by janvorli** [comment]
@k15tfu can you please share a call stack from GDB showing such frame so that I can figure out what is that stuff? We do generate some very short stubs that have no unwind info and tail call to other code so they are present on stack for a very brief period of time.

**Comment by k15tfu** [comment]
@janvorli sure, if you need more just tell me.

```
#10 <signal handler called>
#11 0x00007fa76b61e043 in ?? ()
#12 0x00007fa76cd03747 in ?? ()
#13 0x00007ffcf2dbb730 in ?? ()
#14 0x00007fa734030108 in ?? ()
#15 0x00007ffcf2dbbb68 in ?? ()
#16 0x973096d283ab9500 in ?? ()
#17 0x00007ffcf2dbb7a0 in ?? ()
#18 0x00007fa76cd02b72 in ?? ()
#19 0x0000000000000000 in ?? ()
(gdb) x/20i $pc-37
   0x7fa76b61e01e:      add    %al,(%rax)
   0x7fa76b61e020:      add    %al,(%rax)
   0x7fa76b61e022:      add    %al,(%rax)
   0x7fa76b61e024:      add    %al,(%rax)
   0x7fa76b61e026:      add    %al,(%rax)
   0x7fa76b61e028:      add    %al,(%rax)
   0x7fa76b61e02a:      add    %al,(%rax)
   0x7fa76b61e02c:      add    %al,(%rax)
   0x7fa76b61e02e:      add    %al,(%rax)
   0x7fa76b61e030:      movabs $0x7fa76cf40310,%rax
   0x7fa76b61e03a:      cmp    %rax,(%rdi)
   0x7fa76b61e03d:      jne    0x7fa76b64d075
=> 0x7fa76b61e043:      movabs $0x7fa76cd038b0,%rax
   0x7fa76b61e04d:      jmpq   *%rax
   0x7fa76b61e04f:      int3
   0x7fa76b61e050:      xor    %al,(%rax)
   0x7fa76b61e052:      add    %al,(%rax)
   0x7fa76b61e054:      add    %al,(%rax)
   0x7fa76b61e056:      add    %al,(%rax)
   0x7fa76b61e058:      add    %eax,(%rax)
```

where `0x7fa76cd038b0` is a normal JITe'd method.

**Comment by k15tfu** [comment]
I have created a separate issue for it (if you don't mind): https://github.com/dotnet/coreclr/issues/25676 .
