### ISSUE TITLE
Assert failure: _safePointDecoder.IsSafePoint(curOffs)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25605]
**Job:**
https://mc.dot.net/#/user/coreclr-gcstress-extra/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190707.1/workItem/baseservices.threading.generics/analysis/xunit/baseservices_threading._generics_WaitCallback_thread24_thread24_~2F_generics_WaitCallback_thread24_thread24_sh

**Failed tests:**
baseservices_threading._generics_WaitCallback_thread24_thread24_._generics_WaitCallback_thread24_thread24_sh

**Log:**
```
Assert failure(PID 750 [0x000002ee], Thread: 767 [0x02ff]): _safePointDecoder.IsSafePoint(curOffs)
    File: /__w/12/s/src/vm/eetwain.cpp Line: 5034
    Image: /home/helixbot/work/5c8f0cff-288f-47af-9316-09a50887d615/Payload/corerun

/home/helixbot/work/5c8f0cff-288f-47af-9316-09a50887d615/Work/d46f1605-4c0d-402b-bf21-9e4768a52468/Exec/baseservices/threading/generics/WaitCallback/thread24/thread24.sh: line 252:   750 Aborted                 (core dumped) $LAUNCHER $ExePath \"${CLRTestExecutionArguments[@]}\"

Return code:      1
Raw output file:      /home/helixbot/work/5c8f0cff-288f-47af-9316-09a50887d615/Work/d46f1605-4c0d-402b-bf21-9e4768a52468/Exec/baseservices/threading/Reports/baseservices.threading/generics/WaitCallback/thread24/thread24.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/5c8f0cff-288f-47af-9316-09a50887d615/Payload/corerun thread24.exe ''
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/5c8f0cff-288f-47af-9316-09a50887d615/Payload
> /home/helixbot/work/5c8f0cff-288f-47af-9316-09a50887d615/Work/d46f1605-4c0d-402b-bf21-9e4768a52468/Exec/baseservices/threading/generics/WaitCallback/thread24/thread24.sh
Expected: True
Actual:   False
```

**Comment by BruceForstall** [comment]
`COMPlus_GCStress=C`, `COMPlus_ZapDisable=1`

**Comment by RussKeldorph** [comment]
@Briansull can you take a look?  Looks like #25048

**Comment by BruceForstall** [comment]
I ran `baseservices_threading.generics_WaitCallback_thread24_thread24._generics_WaitCallback_thread24_thread24_sh` more than 37000 times in a loop overnight (with `GCStress=C/ZapDisable=1`, on hardware Linux/x64 Ubuntu 16.04) and didn't see any failure.

Maybe should try running in the same container (?) environment as Helix?

**Comment by briansull** [comment]
Did you also set:

COMPlus_TieredCompilation=0

**Comment by BruceForstall** [comment]
I forgot to do that. Now, I've also set `COMPlus_TieredCompilation=0` and restarted the run, with over 1000 executions run successfully so far.

**Comment by RussKeldorph** [comment]
Moving milestone out as we strongly suspect this issue is specific to GCStress.  If it ends up being a customer-facing issue, we'll re-evaluate.

**Comment by BruceForstall** [comment]
@briansull fwiw, I ran it over 110,000 times, with "stress" also running on the machine, and didn't get a failure.

**Comment by briansull** [comment]
Kusto Data indicate that we now longer have hit this issue this issue since 07/07/2019

**Comment by briansull** [comment]
Resolving this issue
