### ISSUE TITLE
Performance regression on String.Equals

### ISSUE THREAD

**Issue by Symbai** [dotnet/coreclr#25635]
While .NET Core is faster if the string matches, it's much slower than .NET Framework if not. It doesn't matter if Equals or == is used. See below:

```
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.18362
Intel Core i7-4960X CPU 3.60GHz (Haswell), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100-preview7-012593
  [Host] : .NET Core 3.0.0-preview7-27824-03 (CoreCLR 4.700.19.32302, CoreFX 4.700.19.32001), 64bit RyuJIT
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.8.3815.0
  Core   : .NET Core 3.0.0-preview7-27824-03 (CoreCLR 4.700.19.32302, CoreFX 4.700.19.32001), 64bit RyuJIT
```

|  Method |  Job | Runtime |      Mean |     Error |    StdDev |    Median | Rank | Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------- |----- |-------- |----------:|----------:|----------:|----------:|-----:|------:|------:|------:|----------:|
|   Match |  Clr |     Clr | 1.5775 ns | 0.0641 ns | 0.0629 ns | 1.5568 ns |    2 |     - |     - |     - |         - |
| NoMatch |  Clr |     Clr | **3.6239 ns** | 0.1036 ns | 0.1108 ns | 3.6961 ns |    3 |     - |     - |     - |         - |
|   Match | Core |    Core | 0.7763 ns | 0.0489 ns | 0.0502 ns | 0.7364 ns |    1 |     - |     - |     - |         - |
| NoMatch | Core |    Core | **5.4398 ns** | 0.0852 ns | 0.0755 ns | 5.4599 ns |    4 |     - |     - |     - |         - |

Benchmark:
```
[ClrJob]
[CoreJob]
[MemoryDiagnoser]
[RPlotExporter, RankColumn]
public class StringTest
{
    string One = "sguiosdgsuodg";
    string Two = "sguiosdgsuodg";
    string Three = "ugitfgnhfihnf";

    [Benchmark]
    public bool Match()
    {
        return One.Equals(Two);
    }
    [Benchmark]
    public bool NoMatch()
    {
        return One.Equals(Three);
    }

}
```

**Comment by EgorBo** [comment]
The current implementation works extremely well for equal (especially when two strings are not the same object like in your case) or almost equal strings. But I don't see a "fast out" implementation (compare only first bytes). e.g.

```csharp
if (first != second)
    return false;
```
here: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/SpanHelpers.Byte.cs#L1314

Instead - we double check that two sequences are the same object and then - doing SIMD stuff.
/cc: @benaadams

**Comment by Symbai** [comment]
When checking for something to be equal it's rather more often the case it's not than it is. Which means that the "no match" part should have higher priority in performance than the "match" part.... in my opinion. Because the higher the chances that it matches, the less the chance that we are checking for equality.

Hopefully there is space for improving the no match while keeping the existing improvements for match.

**Comment by benaadams** [comment]
Simple enough https://github.com/dotnet/coreclr/pull/25639

**Comment by jkotas** [comment]
Thank you for reporting this issue. The particular case (strings of the same length that differ in the first character) is one of the rare cases that is slower on .NET Core compared to .NET Framework. Fixing it to match .NET Framework would slow down many other cases that we do not believe is a good trade-off.
