### ISSUE TITLE
Single.GetHashCode should be marked AgressiveInlining

### ISSUE THREAD

**Issue by billwert** [dotnet/coreclr#25632]
A change (dotnet/coreclr#18645) affected the inlining decision for `Single.GetHashCode`. `Double.GetHashCode` is marked `AgressiveInlining`, and so should `Single`.

This surfaces as a perf regression in one of our tests for `Vector2` and `Vector3`.

|               Method |     Toolchain |     Mean |
|--------------------- |-------------- |---------:|
| GetHashCodeBenchmark | netcoreapp2.2 | 2.336 ns |
| GetHashCodeBenchmark | netcoreapp3.0 | 4.509 ns |

**Comment by danmosemsft** [comment]
Because it's now a readonly struct? Is there an issue to fix the inlining decision so customers don't have to annotate in this way?

**Comment by AndyAyersMS** [comment]
No, this is not directly related to readonly: #18645 made the IL for `Single.GetHashCode` larger and more complex than it was in 2.2, and so it no longer inlines without a nudge.

**Comment by mikedn** [comment]
Also note that `Double.GetHashCode` is already aggressive inlined, that one generates even larger code. In both cases there are some JIT tweaks that could be made to make the generates native code slightly smaller, just to further skew the inliner's native code size estimates :)
