### ISSUE TITLE
Child process debugging on Linux

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#25641]
There is a nice tool for VS for doing Child Process Debugging: https://devblogs.microsoft.com/devops/introducing-the-child-process-debugging-power-tool/.

I'm not sure what hooks are in coreclr/corefx to make this work.

Is there a way to achieve something like this when debugging on Linux?

**Comment by noahfalk** [comment]
> I'm not sure what hooks are in coreclr/corefx to make this work.
Is there a way to achieve something like this when debugging on Linux?

If I recall correctly, VS is using its ability to do managed and native debugging simultaneously on windows to get CreateProcess notifications. On Linux no managed+native equivalent has been created yet. Should we treat this issue as a request for that feature?

**Comment by tmds** [comment]
> Should we treat this issue as a request for that feature?

No, I'm fine without it. I was just wondering it it was possible already.
fyi, gdb has some way to debug child processes. It may be worth looking into if you want to make this a feature on Linux.
