### ISSUE TITLE
Dictionary ctor in .NET Standard is missing

### ISSUE THREAD

**Issue by glucaci** [dotnet/coreclr#25642]
The following constructor can be found in `Microsoft.NetCore.App 2.2.0`
```csharp
public Dictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection);
```
Why is this constructor missing in `NetStandard.Library 2.0.3`?

**Comment by jkotas** [comment]
.NET Standard 2.0 was the common subset of .NET Core and .NET Framework 4.7.2. This constructor is not present in .NET Framework 4.6.1, and thus it could not have been included in .NET Standard 2.0.
