### ISSUE TITLE
Performance regression on Object.Equals

### ISSUE THREAD

**Issue by Symbai** [dotnet/coreclr#25643]
When it's equal .NET Core is faster but when not, which happens probably more often, .NET Framework is faster.

```
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.18362
Intel Core i7-4960X CPU 3.60GHz (Haswell), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100-preview7-012593
  [Host] : .NET Core 3.0.0-preview7-27824-03 (CoreCLR 4.700.19.32302, CoreFX 4.700.19.32001), 64bit RyuJIT
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.8.3815.0
  Core   : .NET Core 3.0.0-preview7-27824-03 (CoreCLR 4.700.19.32302, CoreFX 4.700.19.32001), 64bit RyuJIT
```

|  Method |  Job | Runtime |     Mean |     Error |    StdDev |
|-------- |----- |-------- |---------:|----------:|----------:|
| NoMatch |  Clr |     Clr | 2.297 ns | 0.0784 ns | 0.0992 ns |
| NoMatch | Core |    Core | 2.566 ns | 0.0853 ns | 0.0757 ns |

```
[ClrJob]
[CoreJob]
[RPlotExporter]
public class ObjectTest
{
    object One = new object();
    object Two = new object();

    [Benchmark]
    public bool NoMatch() => One.Equals(Two);

}
```

**Comment by danmosemsft** [comment]
@symbai would you mind comparing 2.1 or 2.2? If it's a regression its more interesting.

**Comment by Symbai** [comment]
|  Method |     Job | Runtime |     Toolchain |     Mean |     Error |    StdDev |
|-------- |-------- |-------- |-------------- |---------:|----------:|----------:|
| NoMatch | Default |    Core | .NET Core 2.2 | 3.650 ns | 0.0032 ns | 0.0025 ns |
| NoMatch |     Clr |     Clr |       Default | 2.264 ns | 0.0011 ns | 0.0010 ns |
| NoMatch |    Core |    Core |       Default | 2.474 ns | 0.0011 ns | 0.0008 ns |

**Comment by mikedn** [comment]
Can't seem to reproduce this either:
```
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.18932
Intel Core i5-4440 CPU 3.10GHz (Haswell), 1 CPU, 4 logical and 4 physical cores
.NET Core SDK=3.0.100-preview8-012936
  [Host] : .NET Core 3.0.0-preview8-27908-04 (CoreCLR 4.700.19.35801, CoreFX 4.700.19.35705), 64bit RyuJIT
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.8.3752.0
  Core   : .NET Core 3.0.0-preview8-27908-04 (CoreCLR 4.700.19.35801, CoreFX 4.700.19.35705), 64bit RyuJIT
```
|  Method |  Job | Runtime |     Mean |     Error |    StdDev |
|-------- |----- |-------- |---------:|----------:|----------:|
| NoMatch |  Clr |     Clr | 2.923 ns | 0.0285 ns | 0.0267 ns |
| NoMatch | Core |    Core | 2.671 ns | 0.0443 ns | 0.0414 ns |

**Comment by Symbai** [comment]
After installing Preview 8 and repeating the same in a larger benchmark, .NET Core is faster. Guess its no issue at all then, I'm closing.

|  Method |  Job | Runtime |     Mean |     Error |    StdDev |
|-------- |----- |-------- |---------:|----------:|----------:|
| NoMatch |  Clr |     Clr | 24.14 ms | 0.2484 ms | 0.2202 ms |
| NoMatch | Core |    Core | 23.31 ms | 0.3056 ms | 0.2386 ms |

```
[ClrJob]
[CoreJob]
[RPlotExporter]
public class ObjectTest
{
    const int Number = 5000000;
    object[] Objects = new object[Number];
    object[] ObjectsTwo = new object[Number];

    [GlobalSetup]
    public void Setup()
    {
        for (int i = 0; i < Number; i++)
        {
            Objects[i] = new object();
            ObjectsTwo[i] = new object();
        }
    }

    [Benchmark]
    public bool NoMatch()
    {
        var result = false;
        for (int i = 0; i < Number; i++)
        {
            result = Objects[i].Equals(ObjectsTwo[i]);
        }
        return result;
    }

}
```
