### ISSUE TITLE
Reversed fixed? convert byte* to byte[]

### ISSUE THREAD

**Issue by ayende** [dotnet/coreclr#2565]
I have some code that works with memory mapped file, as such, I deal a lot with byte pointers (byte*).
I need to interact with streams, which takes Write(byte[] data, int offset, int count);

If I have a byte[], I can use fixed to get the pointer. But there isn't any way to go the reverse.
Currently I have to copy to a temporary buffer to be able to interact with this API. 

Is there any way (current or future) to avoid this?

**Comment by mikedn** [comment]
> But there isn't any way to go the reverse.

How could there be? A byte[] implies a certain layout - method table, array length, array elements. A byte* only has array elements.

**Comment by jkotas** [comment]
The future way to deal with this problem is likely to make streams and other common types [`Span<T>`](https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/src/System/Span.cs) aware.

**Comment by AaronRobinsonMSFT** [comment]
Closing this issue now that `Span<T>` support is in.
