### ISSUE TITLE
Arm64 ICorDebug* float/double register debug on Linux is failing

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#25694]
After implementing #25597, there are a few cases where the debugger is reporting an incorrect value for doubles.

Root cause(s) is not completely understood.

Observed symptoms:

- Initial value of class member variable is wrong
- Using single step to step out of a return function reports the wrong value
- Using single step to step out of a function changes the return value

Testing has also reported `ICorDebugRegisterSet.GetRegisterSet` is returning `E_FAIL` when when stackwalking.

Quick audit of the code showed three sections where arm64 implementation was missing.

**Comment by hoyosjs** [comment]
The debugger team confirmed it's `ICorDebugThread.GetRegisterSet` that's failing.

**Comment by hoyosjs** [comment]
Shortcoming on `FloatRegValueHome::SetEnregisteredValue` too, which will hit on value reassignment for floating point for enregistered variables.

**Comment by tommcdon** [comment]
@sdmaclea is this issue completed for all branches?

**Comment by sdmaclea** [comment]
Thanks.  Yes it is fixed on 5.0 & 3.0
