### ISSUE TITLE
"Build CoreCLR on Windows" Instructions for VS2019

### ISSUE THREAD

**Issue by ivanbuha** [dotnet/coreclr#25723]
In order to build CoreCLR when using VS2019, its required to install MSVC v142 - VS 2019 C++  Toolset (x86, x64) on top of the requirements for VS2017. Instructions do not contain specific requirements for VS2019 and its easy to miss to install a required component.

**Comment by danmosemsft** [comment]
@ivanbuha thanks. Would you like to off a PR with the edits, since you know what they are?

**Comment by ivanbuha** [comment]
> @ivanbuha thanks. Would you like to off a PR with the edits, since you know what they are?

Yes, already started putting a draft. Will finalize it soon.
