### ISSUE TITLE
Calling function from native code from multiple threads doesn't work

### ISSUE THREAD

**Issue by gdkchan** [dotnet/coreclr#25733]
I have been trying to call managed methods from native code. I do so getting the function pointer with `RuntimeMethodHandle.GetFunctionPointer`, then hardcoding the function address on the native code (it is generated at runtime with LLVM).

It seems to work fine when the method is called from a single thread. However as soon as I have multiple threads calling the managed method concurrently, it quickly breaks. I get random exceptions on each run, usually caused by an access violation on some GC function, from what I know this indicates managed heap corruption.

I managed to create a very simple sample program that exhibits the issue, at least on Windows 10, I still need to test it on linux. The code can be found [here](https://gist.github.com/gdkchan/5898d573f41431722e99907be4612407).

Running the above code here shows the issue very quickly. It usually shows the following exception with the latest .NET Core 3.0 Preview:
```
Internal CLR error. (0x80131506)
   at System.GC.Collect()
   at gccrash.Program.GCStress()
   at gccrash.Program+<>c__DisplayClass0_0.<Main>g__Work|0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```
A few observations that I was able to make about this issue:
- It only happens when the managed code is called from native code on multiple threads. On a single threaded environment it seems to work. Puting a lock on the managed method also seems to fix the issue. Seems to be some sort of race condition.
- Passing a delegate to the native method rather than the pointer directly also seems to fix it for the miltithreaded scenario, but that's not really suitable for what I do.

So, I'm not sure about what is causing this issue. Are we not supposed to pass the pointer from `GetFunctionPointer` to native functions? I don't see anything indicating that on the documentation.

**Comment by jkoritzinsky** [comment]
You should be using [`System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getfunctionpointerfordelegate?view=netframework-4.8) to get a function pointer that you can pass to native code. The function this points to will do the interop marshalling to marshal your arguments if they have a different native representation then their managed representation. It will also set the GC to correct mode and let the runtime know about the native->managed transition.

The function pointer from `RuntimeMethodHandle.GetFunctionPointer` is only meant to be used from within managed code or within CoreCLR itself.

Passing a delegate to the native method does the exact same work as `GetFunctionPointerForDelegate` under the hood. Why is that not suitable for what you do?

**Comment by gdkchan** [comment]
Thanks for the information. `GetFunctionPointerForDelegate` does work. The only problem is that I have quite a lot of methods that are called from native code, and I'd need to create a delegate for each one of them. With `RuntimeMethodHandle.GetFunctionPointer` I can just get the `MethodInfo` from the C# method and then get the pointer from that. Anyway, thanks for the help. I will use delegates on my code then.

I believe it would be worth to update the documentation with the intended use cases of the `GetFunctionPointer` as it's not obvious that it can't be passed to native code (at least it wasn't for me), and I beleive the primary use case for getting those function pointers is passing them to native code.

**Comment by danmosemsft** [comment]
@gdkchan no obligation to do so, but if you want to tweak the doc it's easy to make a PR here: https://github.com/dotnet/dotnet-api-docs

For small changes it's even possible to use Github's built in editor to create PR.

**Comment by AaronRobinsonMSFT** [comment]
@gdkchan I have submitted an update to the docs that mentions that the [`System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.marshal.getfunctionpointerfordelegate) should be used. Feel free to follow the PR: https://github.com/dotnet/dotnet-api-docs/pull/2779

**Comment by gdkchan** [comment]
Thanks for updating it, and sorry for the delay.

For those with the same problem I had, I managed to come up with a way to get the function pointer that can be used on native code from the MethodInfo. It does that by creating the delegate type, then the delegate at runtime, and then calling `Marshal.GetFunctionPointerForDelegate` using that.

The code used to create the delegate type is based on the (private) method `MakeNewCustomDelegate` at `System.Linq.Expressions.Compiler.DelegateHelpers`.
```cs
static class MethodHelpers
{
    private const string DelegateTypesAssemblyName = "JitDelegateTypes";

    private static ModuleBuilder _modBuilder;

    private static ConcurrentDictionary<(string, object), Delegate> _delegatesCache;
    private static ConcurrentDictionary<string, Type>               _delegateTypesCache;

    static MethodHelpers()
    {
        AssemblyBuilder asmBuilder = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName(DelegateTypesAssemblyName), AssemblyBuilderAccess.Run);

        _modBuilder = asmBuilder.DefineDynamicModule(DelegateTypesAssemblyName);

        _delegatesCache     = new ConcurrentDictionary<(string, object), Delegate>();
        _delegateTypesCache = new ConcurrentDictionary<string, Type>();
    }

    public static IntPtr GetFunctionPointerForNativeCode(MethodInfo meth, object instance = null)
    {
        string funcName = GetFullName(meth);

        Delegate dlg = _delegatesCache.GetOrAdd((funcName, instance), (_) =>
        {
            Type[] parameters = meth.GetParameters().Select(x => x.ParameterType).ToArray();

            Type delegateType = GetDelegateType(parameters, meth.ReturnType);

            return Delegate.CreateDelegate(delegateType, instance, meth);
        });

        return Marshal.GetFunctionPointerForDelegate<Delegate>(dlg);
    }

    private static string GetFullName(MethodInfo meth)
    {
        return $"{meth.DeclaringType.FullName}.{meth.Name}";
    }

    private static Type GetDelegateType(Type[] parameters, Type returnType)
    {
        string key = GetFunctionSignatureKey(parameters, returnType);

        return _delegateTypesCache.GetOrAdd(key, (_) => MakeDelegateType(parameters, returnType, key));
    }

    private const MethodAttributes CtorAttributes =
        MethodAttributes.RTSpecialName |
        MethodAttributes.HideBySig |
        MethodAttributes.Public;

    private const MethodImplAttributes ImplAttributes =
        MethodImplAttributes.Runtime |
        MethodImplAttributes.Managed;

    private const MethodAttributes InvokeAttributes =
        MethodAttributes.Public |
        MethodAttributes.HideBySig |
        MethodAttributes.NewSlot |
        MethodAttributes.Virtual;

    private const TypeAttributes DelegateTypeAttributes =
        TypeAttributes.Class |
        TypeAttributes.Public |
        TypeAttributes.Sealed |
        TypeAttributes.AnsiClass |
        TypeAttributes.AutoClass;

    private static readonly Type[] _delegateCtorSignature = { typeof(object), typeof(IntPtr) };

    private static Type MakeDelegateType(Type[] parameters, Type returnType, string name)
    {
        TypeBuilder builder = _modBuilder.DefineType(name, DelegateTypeAttributes, typeof(MulticastDelegate));

        builder.DefineConstructor(CtorAttributes, CallingConventions.Standard, _delegateCtorSignature).SetImplementationFlags(ImplAttributes);

        builder.DefineMethod("Invoke", InvokeAttributes, returnType, parameters).SetImplementationFlags(ImplAttributes);

        return builder.CreateTypeInfo();
    }

    private static string GetFunctionSignatureKey(Type[] parameters, Type returnType)
    {
        string sig = GetTypeName(returnType);

        foreach (Type type in parameters)
        {
            sig += '_' + GetTypeName(type);
        }

        return sig;
    }

    private static string GetTypeName(Type type)
    {
        return type.FullName.Replace(".", string.Empty);
    }
}
```
I'm not sure myself how safe creating those delegates at runtime is, but so far it seems to be working well.
