### ISSUE TITLE
Multiple test legs failing due to versioning issue

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#25754]
Fireballs across the board:
https://mc.dot.net/#/user/coreclr-ci/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F25752~2Fmerge/test~2Ffunctional~2Fcorefx~2F/20190717.21

@wtgodbe, is this due to branding changes?  The tests are all failing early with:
```
~/work/a2bb0df6-4eb8-45cf-880f-93332bbf5a72/Work/5f4d5f80-f259-4465-8bb8-6ad90b69bff5/Exec ~/work/a2bb0df6-4eb8-45cf-880f-93332bbf5a72/Work/5f4d5f80-f259-4465-8bb8-6ad90b69bff5/Exec
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - The following frameworks were found:
      5.0.0 at [/home/helixbot/work/a2bb0df6-4eb8-45cf-880f-93332bbf5a72/Payload/shared/Microsoft.NETCore.App]
```

**Comment by wtgodbe** [comment]
Yes, I think we need to update some hardcoded TFMs from 3.0 -> 5.0, see https://github.com/dotnet/coreclr/pull/25750#issuecomment-512550807. CC @BruceForstall @ericstj. I'm going to fire off a CoreFx -> CoreClr update as well to see if that helps (my DARC enlistment is on the fritz right now, but as soon as I get it fixed I'll fire off the update).

**Comment by wtgodbe** [comment]
This PR has the new new 5.0.0 versions from CoreFx: https://github.com/dotnet/coreclr/pull/25719

**Comment by wtgodbe** [comment]
Looks like we just needed the new versions from CoreFx, the CoreFx tests are green in the maestro PR linked above.

**Comment by ViktorHofer** [comment]
I'm surprised as that shouldn't happen as the TestHost's version maps to the ProductVersion which is already updated in coreclr. https://github.com/dotnet/coreclr/blame/be31aaea6402390d808fa41d4cd1fa9b68f4cdd0/tests/dir.props#L140

**Comment by ViktorHofer** [comment]
As soon as CI works again I'll check if this is still happening.

**Comment by wtgodbe** [comment]
Looks like this is resolved (e.g. https://github.com/dotnet/coreclr/pull/25770)
