### ISSUE TITLE
Frequent package restore failures when building tests

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#2575]
I probably build the CoreCLR test tree way too often, but am seeing about a 50% failure rate in the package restore step for tests. I also see the restore for mscorlib fail, but much less often, maybe 5% of the time. This is on windows on a machine running Server 2012.

What's odd is that if I then run the failing command myself it always succeeds, and then a subsequent test build will usually succeed too. For instance ...
```
>> buildtest x64 release
...
Time Elapsed 00:00:03.15
Starting the Managed Tests Build

  Restoring all packages...
EXEC : warning : FindPackagesById: System.IO.FileSystem [C:\Repos\coreclr\tests\build.proj]
EXEC : warning : FindPackagesById: System.IO.FileSystem [C:\Repos\coreclr\tests\build.proj]
EXEC : warning : FindPackagesById: System.IO.FileSystem [C:\Repos\coreclr\tests\build.proj]
EXEC : warning : FindPackagesById: System.IO.FileSystem [C:\Repos\coreclr\tests\build.proj]
EXEC : warning : FindPackagesById: System.IO.FileSystem.Primitives [C:\Repos\coreclr\tests\build.proj]
EXEC : warning : FindPackagesById: System.IO.FileSystem.Primitives [C:\Repos\coreclr\tests\build.proj]
EXEC : error : FindPackagesById: System.IO.FileSystem.Primitives [C:\Repos\coreclr\tests\build.proj]
    An error occurred while sending the request.
EXEC : warning : FindPackagesById: System.IO.FileSystem [C:\Repos\coreclr\tests\build.proj]
EXEC : error : FindPackagesById: System.IO.FileSystem [C:\Repos\coreclr\tests\build.proj]
    An error occurred while sending the request.
C:\Repos\coreclr\tests\build.proj(23,5): error MSB3073: The command ""C:\Repos\coreclr\tests\packages\/dnx-coreclr-win-
x86.1.0.0-rc2-16128/\bin\dnu.cmd" restore --packages "C:\Repos\coreclr\tests\packages" "C:\Repos\coreclr\tests\src"" ex
ited with code 1.
Test build failed. Refer to C:\Repos\coreclr\tests\..\bin\Logs\Tests_Managed_Windows_NT__x64__Release.log for details

>> & "C:\Repos\coreclr\tests\packages\/dnx-coreclr-win-x86.1.0.0-rc2-16128/\bin\dnu.cmd" restore --packages "C:\Repos\coreclr\tests\packages" "C:\Repos\coreclr\tests\src"
Microsoft .NET Development Utility CoreClr-x86-1.0.0-rc2-16128

  CACHE https://www.myget.org/F/dotnet-core/
  CACHE https://www.myget.org/F/dotnet-buildtools/
  CACHE https://www.myget.org/F/dotnet-coreclr-testdependecies/
  CACHE https://www.nuget.org/api/v2/
Restoring packages for C:\Repos\coreclr\tests\src\baseservices\compilerservices\dynamicobjectproperties\project.json
Following lock file C:\Repos\coreclr\tests\src\baseservices\compilerservices\dynamicobjectproperties\project.lock.json
Restore complete, 267ms elapsed
...
(success!)
```

Since the lab doesn't seem to hit this with anything near the same frequency it's obviously not some widespread problem. But other people have reported hitting it too.

**Comment by markwilkie** [comment]
There's quite a bit of work on going on to stabilize this and Davis is currently on point.  (sorry for the random finger typos Chris and Nate)

**Comment by dagood** [comment]
I didn't have coreclr in mind for package restore, thanks for the issue.

Unfortunately, the only near-term plan to help `restore` stability in the open is to retry a few times. Everything else is for our internal builds right now.

It does seem fishy to have a 50% restore rate that always succeeds on a manual attempt though. Do you have any verbose logs of the failures that I could take a look at, @AndyAyersMS?

**Comment by AndyAyersMS** [comment]
Just happened again ... (Here's the log.)[https://gist.github.com/AndyAyersMS/d9abdecbc0f0a1255e31]

**Comment by dagood** [comment]
Thanks. The errors do just look like simple network failures. I tried a few times locally and didn't see any restore errors (aside from ones I simulated with Fiddler).

To see if a basic 3x retry will fix this scenario, could you try replacing your `BatchRestorePackages` target in `tests\build.proj` with this?

    <Target Name="BatchRestorePackages">
      <Message Importance="High" Text="Restoring all packages..." />
      
      <Exec Command="$(DnuRestoreCommand) $(DnuRestoreDirs)" StandardOutputImportance="Low" CustomErrorRegularExpression="^Unable to locate .*"
            ContinueOnError="WarnAndContinue">
        <Output TaskParameter="ExitCode" PropertyName="RestoreErrorCode" />
      </Exec>
      <Message Importance="high" Text="$(RestoreErrorCode)" />
      
      <Exec Command="$(DnuRestoreCommand) $(DnuRestoreDirs)" StandardOutputImportance="Low" CustomErrorRegularExpression="^Unable to locate .*"
            ContinueOnError="WarnAndContinue"
            Condition="'$(RestoreErrorCode)'!='0'">
        <Output TaskParameter="ExitCode" PropertyName="RestoreErrorCode" />
      </Exec>
      <Exec Command="$(DnuRestoreCommand) $(DnuRestoreDirs)" StandardOutputImportance="Low" CustomErrorRegularExpression="^Unable to locate .*"
            ContinueOnError="WarnAndContinue"
            Condition="'$(RestoreErrorCode)'!='0'">
        <Output TaskParameter="ExitCode" PropertyName="RestoreErrorCode" />
      </Exec>
      
      <Exec Command="$(DnuRestoreCommand) $(DnuRestoreDirs)" StandardOutputImportance="Low" CustomErrorRegularExpression="^Unable to locate .*"
            Condition="'$(RestoreErrorCode)'!='0'">
        <Output TaskParameter="ExitCode" PropertyName="RestoreErrorCode" />
      </Exec>
    </Target>

**Comment by AndyAyersMS** [comment]
Sure, can't hurt.

**Comment by AndyAyersMS** [comment]
Ran with that in place most of the day and it helps but there's still the occasional failure.

What I don't really understand is why it does any network access at all. Typically nothing has changed in any of the project.jsons when I build, I'm just tweaking code in the tests themselves, so it seems like everything that's needed should already be locally cached.

**Comment by dagood** [comment]
Good point. It looks like there are two factors here: [unlocked project.lock.json files](https://github.com/dotnet/coreclr/search?l=json&q=%22locked%22%3A+false%2C&utf8=%E2%9C%93) and 30-minute cache expiration on `FindPackagesById` ([hardcoded into DNX](https://github.com/aspnet/dnx/blob/08cf2d3586472267ab3dbb47aa93eb8cfdc2fe33/src/Microsoft.Dnx.Tooling/Restore/NuGet/NuGetv3Feed.cs#L54)). If the project.lock.json is locked and the packages exist in the packages directory, DNX doesn't even check the http cache, explaining why there are only http requests/cache hits for the unlocked project.json files.

A fix for this scenario for now is to make the lockfiles locked. (Although the connection won't be any more reliable when you *do* need a fresh restore.)

@ericstj Is the above correct? It seems logical to me from what I know about lockfiles, but I don't remember taking it into account when discussing the impact of removing lockfiles from corefx+wcf. Do you know what the plan is for this, especially with locked=true being deprecated?

**Comment by ericstj** [comment]
If the project doesn't use * versioning and there is already an exact match in the packages folder I'd expect DNX not to go to the internet.  If it does that sounds like a bug to me.

**Comment by dagood** [comment]
@ericstj Hmm, ok. Right now NuGet and DNX have the same behavior. Should I file an issue to NuGet to see what they think?

**Comment by AndyAyersMS** [comment]
Looks like `tests\src\GC\Performance\Framework\project.lock.json` never actually got locked, so this could explain why there's always some network traffic. I will fix.

**Comment by dagood** [comment]
@ericstj Looking through the nuget.exe detailed output more carefully, I figured out that these issues:

    WARNING: Dependency specified was System.IO (≥ 4.0.10-beta-23302) but ended up with System.IO 4.0.10.

caused the requests. Setting locked=true does prevent them, but only because the lockfile has the "ended up with" version specified. My mistake!

(It doesn't look like DNU works that way, though.)

**Comment by ericstj** [comment]
That project should be fixed.  It referencing a package version that doesn't exist.

**Comment by dagood** [comment]
Yep, definitely. There are enough of these in all the repos, though, that I'm wondering if we can wait for some tooling to detect/fix them: https://github.com/dotnet/buildtools/pull/365.

**Comment by ericstj** [comment]
At one point we had discussed tooling that diffed the resolved package version against the referenced one (for direct references) and error-ed.

**Comment by ericstj** [comment]
So once that's resolved, if we still see nuget/DNU hitting the web for cases where packages are already local we need to file that bug.  That's a bad perf problem.

**Comment by AndyAyersMS** [comment]
Issues seem to be fixed now that all the lock files are really locked.
