### ISSUE TITLE
Make array types always represented as method tables.

### ISSUE THREAD

**Issue by VSadov** [dotnet/coreclr#25778]
Currently array types can be represented by either a method table or by a TypeDesc. 

It could be confusing since otherwise TypeDescs are only used for types that do not have method tables (method pointers, byref types, etc). Having arrays in that mix adds special cases.

Scenarios where we start from an instance, get a method table and then need to transition to TypeDesc seem unnatural as well. 
Another problem is that dual representation enables cases where representations may not match (i.e. in terms of element type), which could be a source of bugs. 

The reason for all this is mostly historical - from times when array method tables could be shared between arrays of different element types while storing element type info in instances.
That approach is no longer in use (although there are still comments referring to that).

It feels like making array types always represented as unique method tables would be more consistent.

**Comment by danmosemsft** [comment]
We're trying to use a single area label to avoid double counting

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/runtime/pull/1201
