### ISSUE TITLE
CMake Error: Could not create named generator Visual Studio 16 2019

### ISSUE THREAD

**Issue by aggieben** [dotnet/coreclr#25785]
I cloned the repository and tried running `build.cmd`, but experienced this failure:

![image](https://user-images.githubusercontent.com/1321/61497811-7844d700-a986-11e9-9f2d-5cf4508f9eca.png).

There aren't any instructions specific to VS 2019, so I'm a bit unsure where to go from here.

**Comment by EgorBo** [comment]
I guess you need to update your cmake (mine is 3.14.0-rc2)

**Comment by jkoritzinsky** [comment]
You need at least CMake 3.14 to generate VS2019 projects.

**Comment by ivanbuha** [comment]
> I cloned the repository and tried running `build.cmd`, but experienced this failure:
> 
> ![image](https://user-images.githubusercontent.com/1321/61497811-7844d700-a986-11e9-9f2d-5cf4508f9eca.png).
> 
> There aren't any instructions specific to VS 2019, so I'm a bit unsure where to go from here.

I was able to build coreclr after I installed CMake version 3.14.5 (latest stable at the moment) and all MSVC v142 - VS 2019 C++ tools when installing VS.

**Comment by aggieben** [comment]
After updating CMake I got past this issue, but now I have a different built error.  Thanks!

**Comment by danmosemsft** [comment]
Ideally we would explicitly check the CMake version upstream in the build.
