### ISSUE TITLE
JIT Minopts Failures (Checked x64)

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2578]
These tests fail with Complus_JitMinOpts=1 set on windows, checked, x64.

~~\JIT\opt\Tailcall\TailcallVerifyWithPrefix\TailcallVerifyWithPrefix.exe~~
\JIT\SIMD\CircleInConvex\CircleInConvex.exe
~~\JIT\SIMD\VectorArgs\VectorArgs.exe~~
\JIT\SIMD\VectorReturn\VectorReturn.exe
~~\JIT\jit64\regress\ddb\87766\ddb87766\ddb87766.exe~~

----------------------------------------------------------------------------------------------------------

Output for:

CircleInConvex.exe

Assert failure(PID 53020 [0x0000cf1c], Thread: 26564 [0x67c4]): Assertion failed '(allRegs(theInterval->registerType) & mask) != 0' in 'System.Linq.Enumerable:Last(ref):struct' (IL size 101)

 File: d:\fork\public\coreclr\src\jit\lsra.cpp Line: 738

----------------------------------------------------------------------------------------------------------

Output for:

VectorReturn.exe

Assert failure(PID 41084 [0x0000a07c], Thread: 13388 [0x344c]): Assertion failed '!"Incompatible types for gtNewTempAssign"' in 'VectorTest:F2(float):struct' (IL size 97)

 File: d:\fork\public\coreclr\src\jit\gentree.cpp Line: 10974

**Comment by RussKeldorph** [comment]
@jashook See #2329 TailcallVerifyWithPrefix is simply incompatible with Minopts.  @sivarv FYI.

**Comment by RussKeldorph** [comment]
@jashook pretty sure VectorArgs is covered by #2328.

**Comment by sivarv** [comment]
test JIT\jit64\regress\ddb\87766\ddb87766\ddb87766.exe failing under JitMinopts is by design.  It is testing that method VInline.Accumulate(int32 a) is inlined inside Main() method.  Under JitMinopts in-lining is turned off.  We should exclude this test from running under jitminopts=1.

**Comment by sivarv** [comment]
Post Carol's Linux SIMD check-in, circleinconvex.exe and vectorreturn.exe are no longer repro'ing.
