### ISSUE TITLE
Enabling GCServer for server apps

### ISSUE THREAD

**Issue by cheers00** [dotnet/coreclr#2579]
Do I need to enable  ```gcServer``` explicitly for asp.net 5 web apps running on multi node servers? Can I do this by adding the following line to project.json?

```<gcServer enabled="true"/>```

**Comment by sergiy-k** [comment]
Hi @cheers00, are you talking about Windows or Linux? DNX on Windows enables Server GC by default.
This is not yet available on Linux. It is work in progress: https://github.com/dotnet/cli/issues/488

**Comment by cheers00** [comment]
Windows. Thanks.
