### ISSUE TITLE
A question about CLR

### ISSUE THREAD

**Issue by forestbat** [dotnet/coreclr#25805]
I read CLR via C# （4th version in 2014），it says that MS's purpose is decreasing GC's time to less than a normal memory page fault's time，so today do you keep the purpose or abandone it？

**Comment by Maoni0** [comment]
yes, we always aim to improve GC efficiency which includes pause time. obviously pause time needs to be balanced against other perf metrics of a GC; we plan to give you a finer grain choice of specifying which one(s) you care about the most (pause, heap size, GC CPU time)
