### ISSUE TITLE
error MSB3721: The command "ml64.exe ..." exited with code 1

### ISSUE THREAD

**Issue by aggieben** [dotnet/coreclr#25809]
I'm trying to build coreclr on Windows 10, `release/3.0` branch with VS 2019.  I've gone through the list of VS 2017 prerequisites and tried to make sure I have all those, as well as an updated version of CMake (VS2019 doesn't appear to be documented at this point).  The build fails like this (two of these in the log):

![image](https://user-images.githubusercontent.com/1321/61582158-bb20bf00-aaec-11e9-839c-093f45f94c2a.png)

Also a bit further down, 
![image](https://user-images.githubusercontent.com/1321/61582181-edcab780-aaec-11e9-91c6-f629efd7e0dd.png)

Any pointers appreciated.

**Comment by danmosemsft** [comment]
Did you reboot since the last VS install? Are you building within a VS command prompt? I am not sure, but we may find lib.exe by environment variables.

**Comment by aggieben** [comment]
@danmosemsft Strangely enough, a reboot appears to have fixed this.  I've had VS2019 for a long time.  Maybe installing specific dependencies is what supplied the correct tooling, and had to be picked up on a reboot?  I don't know.  Thanks for the tip.

**Comment by danmosemsft** [comment]
> Maybe installing specific dependencies is what supplied the correct tooling, and had to be picked up on a reboot?

This is very likely the case. Although, VS should prompt to reboot in this case...

**Comment by danmosemsft** [comment]
I'll close, please reopen if this isn't properly fixed

**Comment by aggieben** [comment]
This may be a different issue, but I just ran into this again, but in a PowerShell Cmder tab.  Works fine in a VS 2019 command prompt.
