### ISSUE TITLE
Test failed: System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25811]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstress/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190720.1/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Tests.FontTests~2FToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint:%20AntiAlias,%20expectedQuality:%203)

**Failed tests:**
System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected

**Log:**
```
Assert.Equal() Failure
Expected: -13
Actual:   178639260
```

**Comment by BruceForstall** [comment]
This fails every day on Windows/x86 with tailcallstress.

**Comment by BruceForstall** [comment]
Dup of https://github.com/dotnet/coreclr/issues/25961
