### ISSUE TITLE
JIT: Recognize blsr in "x & (x - 1)"

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#25820]
E.g. https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Bits.cs#L40-L51

![image](https://user-images.githubusercontent.com/523221/61669260-0eab2c80-ace8-11e9-8276-9c89b60703ef.png)

I guess it can be implemented the same way it was done for `ror`

**Comment by EgorBo** [comment]
Same for `bzhi` e.g. https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Security/Cryptography/Asn1Reader/AsnWriter.BitString.cs#L287-L294:
```csharp
bool CheckValidLastByte(byte lastByte, int unusedBitCount)
{
    // If 3 bits are "unused" then build a mask for them to check for 0.
    // 1 << 3 => 0b0000_1000
    // subtract 1 => 0b000_0111
    int mask = (1 << unusedBitCount) - 1;
    return ((lastByte & mask) == 0);
}
```
C++:
```asm
  bzhi eax, edi, esi
  sete al
  ret
```
C#:
```asm

G_M6200_IG01:
G_M6200_IG02:
       mov      eax, 1
       mov      ecx, r8d
       shl      eax, cl
       dec      eax
       movzx    rdx, dx
       test     edx, eax
       sete     al
       movzx    rax, al

G_M6200_IG03:
       ret      
; Total bytes of code: 24
```

**Comment by mikedn** [comment]
Recognizing that `CheckValidLastByte` seems to be pretty involved and it's not clear how common this pattern is for the extra code added to the JIT to be useful. Besides, `bzhi` is exposed as an intrinsic so people can use it if they truly need it.

But I'm baffled by the generated code - there's a `movzx rdx, dx` somewhere in the middle but it seems that it should have been `movzx rdx, dl`. Hopefully that's just a disasm error and not an actual JIT bug.

**Comment by EgorBo** [comment]
>  I don't know where did you get movzx rdx, dx:

@mikedn oops, sorry I was on that branch with `goto CM_OP_EQ`  will fix that first.

> You may want to first solicit feedback from the JIT team first before attempting to implement any of this. 

That's why I filed this issue first, to hear your thoughts, thanks!

**Comment by mikedn** [comment]
> That's why I filed this issue first, to hear your thoughts, thanks!

Well, I was referring to the official JIT team people :smile:
