### ISSUE TITLE
Math.FusedMultiplyAdd suboptimal codegen

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#25829]
I was implementing a popular math `Lerp` function using `FusedMultiplyAdd` (see [this post](https://devblogs.nvidia.com/lerp-faster-cuda/) in Nvidia's blog) and noticed that `MathF.FusedMultiplyAdd` only generates `vfmadd213ss` and doesn't care about signs.

So my Lerp is:
```csharp
static float Lerp(float v0, float v1, float t)
{
    return MathF.FusedMultiplyAdd(t, v1, MathF.FusedMultiplyAdd(-t, v0, v0));
}
```
RuyJIT:
```asm
; Method Lerp(float,float,float):float

G_M3843_IG01:
       vzeroupper 

G_M3843_IG02:
       vmovaps  xmm3, xmm2
       vmovss   xmm4, dword ptr [reloc @RWD00]
       vxorps   xmm2, xmm4
       vmovaps  xmm4, xmm0
       vfmadd213ss xmm2, xmm4, xmm0
       vmovaps  xmm0, xmm3
       vfmadd213ss xmm0, xmm1, xmm2

G_M3843_IG03:
       ret      
RWD00  dd	80000000h
; Total bytes of code: 38

```

Clang/gcc:
```asm
       vfnmadd213ss xmm0, xmm2, xmm0 # xmm0 = -(xmm2 * xmm0) + xmm0
       vfmadd231ss xmm0, xmm2, xmm1 # xmm0 = (xmm2 * xmm1) + xmm0
       ret
```

So even a simple:
```csharp
MathF.FusedMultiplyAdd(a, -b, -c);
```
generates redundant xors:
```asm
       vmovss   xmm3, dword ptr [reloc @RWD00]
       vxorps   xmm1, xmm3
       vmovss   xmm3, dword ptr [reloc @RWD00]
       vxorps   xmm2, xmm3
       vfmadd213ss xmm0, xmm1, xmm2
```
while could be just:
```asm
vfnmsub213ss
```
Depending on signs it can be:
```asm
vfnmadd213ss
vfnmsub213ss
vfmadd213ss
vfmsub213ss
```

PS: I think all C# game engines have `Lerp` function so probably it makes sense to add it to `Math`, e.g.:
[OpenTK](https://github.com/opentk/opentk/blob/06a0a63993dfd253cfc197549232204a48e6bcd8/src/OpenToolkit.Mathematics/MathHelper.cs#L1145-L1149)
[Unity3d](https://docs.unity3d.com/ScriptReference/Mathf.Lerp.html)
[Xenko](https://github.com/xenko3d/xenko/blob/master/sources/core/Xenko.Core.Mathematics/MathUtil.cs#L365-L368)

category:cq
theme:intrinsics
skill-level:expert
cost:medium

**Comment by EgorBo** [comment]
hm.. workaround:
```csharp
static float Lerp(float v0, float v1, float t)
{
    Vector128<float> vv0 = Vector128.CreateScalarUnsafe(v0);
    Vector128<float> tt = Vector128.CreateScalarUnsafe(t);

    return Fma.MultiplyAddScalar(tt, Vector128.CreateScalarUnsafe(v1), 
                Fma.MultiplyAddNegatedScalar(tt, vv0, vv0)).ToScalar();
}
```

**Comment by tannergooding** [comment]
Yeah, the initial intrinsic support I did was very limited. It needs to be updated for .NET 5 to recognize the various common patterns and to emit the appropriate instruction overload.

**Comment by 4creators** [comment]
Is there a chance to accept #27060 as a servicing update / back-port for v3.1? Current implementation should not be called FMA as it slows down several paths and may be misleading with regard to what code is generated by the intrinsic. On the other hand, full FMA implementation will provide significant benefits for many users. Actually, problems with current v3.0 FMA implementation were reported just after its release.

Some examples of the algorithms which are affected are `color space conversions`, `NAMD`, `multi-body`.

@BruceForstall @jkotas @CarolEidt @tannergooding

**Comment by tannergooding** [comment]
I don't think it is worth backporting. If their code path is actually perf critical, then they do have the option of directly using HWIntrinsics.

> Current implementation should not be called FMA as it slows down several paths and may be misleading with regard to what code is generated by the intrinsic

The function executes a "fused multiply-addition" as defined by the IEEE spec. There is no guarantee that it is hardware accelerated or what codegen will be generated. The fact that we can generate more optimal code is just a benefit of the underlying hardware (and not all hardware will support it -- namely FMA3 was first introduced in 2013; so it won't be uncommon for machines to still be in use that can't accelerate the functionality).

As is, the code is correct and accelerated; it just doesn't produce "optimal" codegen in all scenarios.

**Comment by EgorBo** [comment]
@tannergooding speaking of that, does Is `Math.FusedMutltiplyAdd` hw-accelerated on AArch64? (it is on Mono).

**Comment by tannergooding** [comment]
That depends on if the underlying CRT implementation accelerates it. The JIT doesn't currently and won't until we expose the ARM64 FMA intrinsics.
