### ISSUE TITLE
System.IO.IOException : The process cannot access the file

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25825]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190722.1/workItem/System.IO.FileSystem.Tests/analysis/xunit/System.IO.Tests.EncryptDecrypt~2FEncryptDecrypt_Read

**Log:**
```
System.IO.IOException : The process cannot access the file 'C:\\Users\\runner\\AppData\\Local\\Temp\\tmp823A.tmp' because it is being used by another process.
   at System.IO.FileSystem.ThrowExceptionEncryptDecryptFail(String fullPath) in /_/src/System.IO.FileSystem/src/System/IO/FileSystem.Win32.cs:line 60
   at System.IO.FileSystem.Encrypt(String path) in /_/src/System.IO.FileSystem/src/System/IO/FileSystem.Win32.cs:line 26
   at System.IO.File.Encrypt(String path) in /_/src/System.IO.FileSystem/src/System/IO/File.cs:line 651
   at System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read() in /_/src/System.IO.FileSystem/tests/File/EncryptDecrypt.cs:line 45
```

**Comment by danmosemsft** [comment]
This test does `Path.GetTempFileName()` with `uUnique==0` which should reliably create a new file. Then it does `File.WriteAllText` to it and `File.ReadAllText` from it. Both of those close the handle. Then `File.Encrypt` method calls `EncryptFileW` passing that path and it's reporting it's not able to open the file for write.

So it's not clear what's going on. A bug in `EncryptFileW` ? Another test opening this temp file concurrently even though it did not create it?

cc @jeremykuhne

**Comment by JeremyKuhne** [comment]
Windows.10.Amd64.Open-x64-Checked

I presume antivirus. Unless we see this in the history I'd close it personally. It _might_ possibly help to not be creating a file in the root of the temp folder. (On the off chance there is some other test cruising the root of the temp folder.)

**Comment by danmosemsft** [comment]
Let see whether it reoccurs in this test specifically.
