### ISSUE TITLE
Assert failure: (GetComponentSize() <= 2) || IsArray()

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25826]
**Job:**
https://mc.dot.net/#/user/coreclr-gcstress-extra/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190721.1/workItem/baseservices.threading.generics/analysis/xunit/baseservices_threading._generics_WaitCallback_thread25_thread25_~2F_generics_WaitCallback_thread25_thread25_sh

**Failed tests:**
baseservices_threading._generics_WaitCallback_thread25_thread25_._generics_WaitCallback_thread25_thread25_sh

**Log:**
```
Assert failure(PID 32568 [0x00007f38], Thread: 32568 [0x7f38]): (GetComponentSize() <= 2) || IsArray()
    File: /__w/5/s/src/vm/methodtable.cpp Line: 8113
    Image: /home/helixbot/work/1479037d-a2c3-4a8f-9fae-a9e48a5eb9a3/Payload/corerun

/home/helixbot/work/1479037d-a2c3-4a8f-9fae-a9e48a5eb9a3/Work/7e947ed3-e119-4450-ab18-e829320aab6d/Exec/baseservices/threading/generics/WaitCallback/thread25/thread25.sh: line 252: 32568 Aborted                 (core dumped) $LAUNCHER $ExePath \"${CLRTestExecutionArguments[@]}\"

Return code:      1
Raw output file:      /home/helixbot/work/1479037d-a2c3-4a8f-9fae-a9e48a5eb9a3/Work/7e947ed3-e119-4450-ab18-e829320aab6d/Exec/baseservices/threading/Reports/baseservices.threading/generics/WaitCallback/thread25/thread25.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/1479037d-a2c3-4a8f-9fae-a9e48a5eb9a3/Payload/corerun thread25.exe ''
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/1479037d-a2c3-4a8f-9fae-a9e48a5eb9a3/Payload
> /home/helixbot/work/1479037d-a2c3-4a8f-9fae-a9e48a5eb9a3/Work/7e947ed3-e119-4450-ab18-e829320aab6d/Exec/baseservices/threading/generics/WaitCallback/thread25/thread25.sh
Expected: True
Actual:   False
```

**Comment by BruceForstall** [comment]
This was `gcstress0xc_zapdisable_jitstress2`

**Comment by BruceForstall** [comment]
@sergiy-k @kouvel

**Comment by sergiy-k** [comment]
@MichalStrehovsky, could you please take a look?

**Comment by MichalStrehovsky** [comment]
I'm not able to hit an assert. I built the x64 checked version of the product, ran `./build-test.sh x64 checked priority1` and then:

```
export COMPlus_JitStress=2
export COMPlus_GCStress=0xC 
export COMPlus_ZapDisable=1
gdb --args /home/michals/git/coreclr/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun /home/mi
chals/git/coreclr/bin/tests/Linux.x64.Checked/baseservices/threading/generics/WaitCallback/thread25/thread25.exe
```

Then in gdb:

```
(gdb) run
Starting program: /home/michals/git/coreclr/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun /home/michals/git/coreclr/bin/tests/Linux.x64.Checked/baseservices/threading/generics/WaitCallback/thread25/thread25.exe
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffffc910700 (LWP 27740)]
[New Thread 0x7ffffc100700 (LWP 27741)]
[New Thread 0x7ffffb8f0700 (LWP 27742)]
[New Thread 0x7ffffa840700 (LWP 27743)]
[New Thread 0x7ffffa030700 (LWP 27744)]
[New Thread 0x7ffff9820700 (LWP 27745)]
[New Thread 0x7ffff9010700 (LWP 27746)]
[New Thread 0x7fffff510700 (LWP 27747)]
[New Thread 0x7fffebff0700 (LWP 27748)]
[New Thread 0x7fffff4a0700 (LWP 27749)]

Thread 1 "corerun" received signal SIGSEGV, Segmentation fault.
0x00007fff8457dcc7 in ?? ()
(gdb) bt
#0  0x00007fff8457dcc7 in ?? ()
#1  0x0000000000000000 in ?? ()
```

So yep, it's a corruption, and the stack is garbage. But this is not the assert that is in the top-post and I'm hitting this segfault for all tests (or at least a random sample I did).

I think I'm doing something wrong.

Also, the repro environment in the Helix results doesn't work (cannot get the repro API key because the repro azure app doesn't exist).

**Comment by BruceForstall** [comment]
This is GCStress, so you're probably hitting the GCStress-added illegal instructions. If you look at disassembly, you'll probably see lots of "hlt" instructions. I think there's a way to get gdb/lldb to ignore them, but I don't remember the incantation right now. They're also not as flexible as windbg in ignoring just the GCStress ones. Make sure you try to repro without GCStress first, just to check.

**Comment by AndyAyersMS** [comment]
For LLDB, see https://github.com/dotnet/coreclr/issues/19211#issuecomment-459925499

```
process handle -n FALSE -p TRUE -s FALSE SIGILL SIGRTMIN
```
also you will want to set stress env vars from inside the debugger, not in the debugger ambient environment, as SOS will invoke a CLR and pick up those ambient settings (that is, you don't want SOS running under gc stress too).

**Comment by MichalStrehovsky** [comment]
Thanks for the hints. I think I'm not doing something right though.

When I pick a random test (e.g. `reflection/ldtoken/byrefs`), I consistently get segfaults even without a debugger:

```
michals@michals-dev:~$ /home/michals/git/coreclr/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun /home/michals/git/coreclr/bin/tests/Linux.x64.Checked/reflection/ldtoken/byrefs/byrefs.exe
Segmentation fault (core dumped)
```

Once I clear out COMPlus_GCStress, the test works:

```
michals@michals-dev:~$ export COMPlus_GCStress=
michals@michals-dev:~$ /home/michals/git/coreclr/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun /home/michals/git/coreclr/bin/tests/Linux.x64.Checked/reflection/ldtoken/byrefs/byrefs.exe
ByRefs look good
```

Is it possible GCStress doesn't work in WSL? Do I have to actually have to install Linux?

**Comment by AndyAyersMS** [comment]
DId you install the stress support bits into Core_Root via `tests\setup-stress-dependencies.sh` ?

**Comment by MichalStrehovsky** [comment]
> DId you install the stress support bits into Core_Root via `tests\setup-stress-dependencies.sh` ?

The build-tests.sh script already installs those, but I re-ran it to be sure. Didn't help.

I ended up trying on a real Ubuntu box and there it doesn't segfault. So maybe the segfault under GCStress is WSL-specific.

I'm running the test in a loop hoping for a crash now.

**Comment by sergiy-k** [comment]
Hi @MichalStrehovsky, was there a conclusion on this issue?

**Comment by MichalStrehovsky** [comment]
I couldn't get a repro.

**Comment by sergiy-k** [comment]
OK. So should this issue then be closed as No Repro to get a new report if it happens again?

**Comment by MichalStrehovsky** [comment]
Sure - I didn't know what the process is. This is the first GCStress bug I can't repro.
