### ISSUE TITLE
Returning a UTF-8 string from unmanaged code

### ISSUE THREAD

**Issue by ddobrev** [dotnet/coreclr#25849]
How should UTF-8 strings be returned from C++ code? Does:

```cs
[return: MarshalAs(UnmanagedType.LPUTF8Str)]
public static extern string function();
```

always work or should we use IntPtr + manual marshalling for most cases? In case it's the latter, why isn't [Marshal.PtrToStringUTF8](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.ptrtostringutf8?view=netstandard-2.1) available in .NET Framework too?

**Comment by jeffschwMSFT** [comment]
cc @jkoritzinsky

**Comment by jkoritzinsky** [comment]
@ddobrev the `[return: MarshalAs(UnmanagedType.LPUTF8Str)]` should work for returning null-terminated strings from C++ to C#. 

Are you encountering an issue with it?

**Comment by ddobrev** [comment]
@jkoritzinsky no but I have encountered it with LPStr and LPWStr. Returning such in this manner causes crashes because it relies on the native memory having been allocated with CoMemTask<something>. This is why strings in such situations must be returned with IntPtr + Marshal.PtrToStringAnsi/Uni instead. I'm asking if the same applies to LPUTF8Str.

**Comment by jkoritzinsky** [comment]
The LPUTF8Str marshaler also requires you to allocate with the CoTaskMemAlloc allocator on Windows like the other string marshalers (on non-Windows it's just malloc). So if your issue is with the allocator, then you will not be able to use the LPUTF8Str marshaler.

I personally can't comment on why `Marshal.PtrToStringUTF8` was not added to .NET Framework since I wasn't working on the product at that time. As an alternative, you could use the `System.Text.Encoding` APIs (which is what the Marshal APIs use under the hood anyway) to convert a null-terminated UTF8 string to a C# string.

**Comment by ddobrev** [comment]
@jkoritzinsky in such a case would you happen to have a complete example of returning a non-comem-ed UTF-8 string to C#?

**Comment by jkoritzinsky** [comment]
Here's an example I just put together that should work. Let me know if it works for you.

```csharp
using System;
using System.Text;
using System.Runtime.InteropServices;
public class C {
    [DllImport("NativeLibrary")]
    private static extern unsafe byte* GetUtf8String();
    
    public unsafe void M() {
        byte* str = GetUtf8String();
        int length = 0;
        for (byte* i = str; *i != 0; i++, length++);
        var clrString = Encoding.UTF8.GetString(str, length);
        Marshal.FreeHGlobal((IntPtr)str);
    }
}
```

**Comment by ddobrev** [comment]
@jkoritzinsky thank you even though I'd already found a similar example. Tell me, though, why do you free the memory with FreeHGlobal? Isn't it only applicable for memory allocated with AllocHGlobal?

**Comment by jkoritzinsky** [comment]
FreeHGlobal matches up with malloc/free. If you want to de-allocate a different way, then you can replace the deallocation call.
