### ISSUE TITLE
IL Opcode for Range and Bound Checks

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/coreclr#25847]
Should we consider adding an opcode for;
range (`lowest <= value <= highest`) and
bound (`lowest<=value < highest `).
Then let the underlying runtime / jit / compiler take care of how it it is handled?
Eg the cpu has a dedicated range comparison instruction.  

It would take three arguments, (Value, Lowest, Highest) then set Equals flag to true if in the value, otherwise set NotEquals flag to true. The IL produce by the compiler (such as Roslyn) would shorter.
```vbnet
    Function IsWithin(Value As Int32, Lowest As Int32, Highest As Int32) As Boolean
    Return (Lowest <= Value) And (Value<=Highest)
    End Function  
```
```il
        IL_0000: ldarg.1
        IL_0001: ldarg.0
        IL_0002: cgt
        IL_0004: ldc.i4.0
        IL_0005: ceq
        IL_0007: ldarg.0
        IL_0008: ldarg.2
        IL_0009: cgt
        IL_000b: ldc.i4.0
        IL_000c: ceq
        IL_000e: and
        IL_000f: ret
```
would become
```il
        IL_0000: ldarg.0
        IL_0001: ldarg.1
        IL_0002: ldarg.2
        IL_0003: range   ' result is push onto stack
        IL_0005: ret
```

**Comment by danmosemsft** [comment]
I believe we generally prefer that codegen learn to recognize IL patterns (like this one) rather than attempt to represent them with new IL opcodes since that would also require changes not only to the compiler as well but every tool everywhere that decompiles or analyzes IL and also would not benefit existing binaries.

**Comment by BruceForstall** [comment]
Does the JIT generate sub-optimal code for this pattern currently?

**Comment by mikedn** [comment]
> Eg the cpu has a dedicated range comparison instruction.

It does not. So this issues doesn't make a lot of sense.

**Comment by BruceForstall** [comment]
Given that it's extremely difficult to add a new CIL opcode, and there's no evidence (though perhaps no investigation) that the JIT is not already generating good code, I'm going to close this issue.
