### ISSUE TITLE
COMPlus_GCHeapHardLimit no longer functioning

### ISSUE THREAD

**Issue by sudeepagarwal** [dotnet/coreclr#25889]
Bing uses Heap Hard Limit and Large Pages, and we noticed that it is no longer being respected when used with COMPlus_LargePages=1 ... we have not yet confirmed if this is because of LargePages config entry being incorrectly read or of HardLimit config entry being misread.

**Comment by hoyosjs** [comment]
@Maoni0 @andy-ms

**Comment by Maoni0** [comment]
yes, I just submitted a PR for this: https://github.com/dotnet/coreclr/pull/25890. 
really sorry about this...

**Comment by sergiy-k** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/25890
