### ISSUE TITLE
MSI installer is not signed

### ISSUE THREAD

**Issue by bendono** [dotnet/coreclr#2589]
Following the .NET Core installation instructions for Windows, I downloaded the MSI installer.
Path: https://dotnet.github.io/getting-started/
OS: Windows 10

Upon installation, SmartScreen will attempt to block installation.
![msi](https://cloud.githubusercontent.com/assets/846533/12213523/f51de5de-b6bc-11e5-8a53-92acbf93c1e8.png)
Likely this is because the Publisher is not defined.

**Comment by mikedn** [comment]
This issue most likely belongs in the cli repo, no such MSI is built in this repo.

**Comment by ellismg** [comment]
Moved to dotnet/cli#777
