### ISSUE TITLE
dotnet run: Access to path... AppData\Local\Application Data is denied

### ISSUE THREAD

**Issue by bendono** [dotnet/coreclr#2590]
Following the .NET Core installation instructions for Windows, I issue the command "dotnet run". This results in the following error: Access to path... AppData\Local\Application Data is denied

![dotnet_error](https://cloud.githubusercontent.com/assets/846533/12213548/93aa118c-b6bd-11e5-9212-a35f48b190be.png)

Path: https://dotnet.github.io/getting-started/

Note that running PowerShell as an Admin does not help, either.
Not sure if it is related, but I notice that the restore and run are trying to use my user account from the C: drive. My user account is defined to be on D:. Should this use the defined user path, or is it hard-coded to C:?

**Comment by benaadams** [comment]
Strangely our paths are the same: https://github.com/dotnet/cli/issues/686

**Comment by tzwlai** [comment]
@bendono, I have moved this to the CLI repo: https://github.com/dotnet/cli/issues/845
