### ISSUE TITLE
PublishSingleFile for Asp.NetCore's WorkDirectory issue.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [dotnet/coreclr#25918]
If publish aspnetcore program to single self-contained executable file, all file will extract to temp dir, but I think program work dir should be executable file's stqrtup path, not temp path, because temp path can not manage and inconvenient.

**Comment by jeffschwMSFT** [comment]
cc @swaroop-sridhar

**Comment by swaroop-sridhar** [comment]
Related Issue: https://github.com/dotnet/core-setup/issues/7491

**Comment by mihaimyh** [comment]
I am getting the following error in Windows Logs while trying to run a self-contained Wpf app:

Description: A .NET Core application failed.
Application: Helper.exe
Path: D:\c026dmial\gitRepos\sdehelper\SdeHelper.WpfUI.Core\bin\publish\Helper.exe
Message: Failure processing application bundle.
Failed to commit extracted to files to directory [C:\Users\C026DM~1\AppData\Local\Temp\.net\SDE Helper\rm2gtdkz.o5o]
A fatal error was encountered. Could not extract contents of the bundle

Does the user needs to have admin rights for the extraction to be successful?

**Comment by jeffschwMSFT** [comment]
@mihaimyh they do not need admin rights to extract, though the file extraction can fight with antivirus software.  Does this happen all the time, or only occasionally?

**Comment by swaroop-sridhar** [comment]
The main issue (working directory determination) is a dup of https://github.com/dotnet/core-setup/issues/7491
