### ISSUE TITLE
Managed calling conventions and calli

### ISSUE THREAD

**Issue by sakno** [dotnet/coreclr#25916]
I'm playing with different combinations of managed calling conventions (defined by `System.Reflection.CallingConventions`) and `calli` IL instruction and found the following things:
1. Static method can be called successfully with `HasThis` calling convention if its first parameter of reference type or managed pointer to value type
1. Instance non-virtual method can be called successfully with `Standard` calling convention if its first argument is passed explicitly as type `O` or `&`.

ECMA-334 is unclear about this. Chapter III.3.2 0 saying that:
> The calling convention is not checked dynamically, so code that uses a calli instruction will not work correctly if the destination does not actually use the specified calling convention.

It's OK that `calli` cannot check actual calling convention because the target method is unknown at compile time. However, my experiments showing that mismatch in calling convention is normal for CLR.
My question is it legal to use `HasThis` CC to call static methods and `Standard` to call instance methods through `calli`?

**Comment by jkotas** [comment]
> My question is it legal to use HasThis CC to call static methods and Standard to call instance methods through calli?

It is not legal and it does not work in general. It happens to work for some signatures. Also, the exact shape of signatures that it happens to work for differs between platforms (e.g. x64 vs. arm64) and between runtime versions.

**Comment by jkotas** [comment]
vm

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md describes the current managed calling convention.
