### ISSUE TITLE
Gen2 Collections happening without Gen1 Collections

### ISSUE THREAD

**Issue by mateusz-osojca** [dotnet/coreclr#25935]
We are using .NET 4.7.2 and developing WPF application (GC workstation mode). Once every 30seconds we have seen quite big CPU load on our process. What we discovered is that during that, GC jumps in with the collection of Generation 2. We tried to investigate what exactly is happening (and what is the root cause of that, since our application is not executing any user code at that time...), and what we see in GC stats is that we are getting only collections on GEN 0 and Gen2. I could explain that to myself if that would be triggered by Large Allocations but it is Small allocations that is actually happening (at least up to PerFiew stats). 
The weird thing is that we don't see  (in the dumps compare in the PerfView)any allocations of our types, all we get is the allocations of internal .NET / WPF types (at least to our knowledge)
Here You can see the GC Stats  ()All GC Events):

![image](https://user-images.githubusercontent.com/48021601/62106615-f28a2b00-b2a5-11e9-801a-b74fa7749e77.png)

GC Rollup By Generation: 
![image](https://user-images.githubusercontent.com/48021601/62106662-1483ad80-b2a6-11e9-9c0a-c5c806e97d5b.png)

Condemned reasons for GC:
![image](https://user-images.githubusercontent.com/48021601/62106693-28c7aa80-b2a6-11e9-9d65-b9d9d0e8b55b.png)

Finalized Object Counts:
![image](https://user-images.githubusercontent.com/48021601/62106718-367d3000-b2a6-11e9-924d-b3ed9d36dc19.png)

And the PerGeneration GC Events from Excel:

![image](https://user-images.githubusercontent.com/48021601/62107905-f4092280-b2a8-11e9-94b2-f9af71e9f8ed.png)

Since this bug was discovered quite recently and also few months ago we upgraded the .NET to 4.7.2 (from 4.6) we tried to downgrade to 4.6 but still having the same issue. 

Could You help out what could be the root-cause? Maybe even exaplnation of how is it possible to collect Gen2 withoug Gen1? I guess it could be those finalizable objects but the Gen1 would have to happen anyway and GC would see that some of the objects are "Finnalizable" so it would land in Que for finalization in Gen 2...? Or we are missing something here?

**Comment by Maoni0** [comment]
you don't need to see a gen1 before gen2. what happens here is

+ gen0's alloc budget is exceeded (indicated by Trigger Reason is AllocSmall)
+ Time tuning elevates to gen1 (indicated by 1 in the Time Tuning column)
+ because we are now doing gen1 we also check gen2's budget see if it's exceeded and it is (indicated by 2 in the Generation Budget Exceeded column)

**Comment by mateusz-osojca** [comment]
Thanks a lot Maoni! So what exactly "Time tuning elevates to gen1" means? And how exactly got Gen2's budget exceeded if we didn't allocate anything there? Or if we did actually what is the "source" of allocation in Gen2?
I thought the object could land in Gen2 either from allocating in LOH or promotted from Gen 1....

**Comment by Maoni0** [comment]
for workstation we have time tuning that says if we haven't done gen1 after 10 gen0s or in the past 10s we would elevate to doing a gen1. 
you could allocate into gen2 during previous gen1s which would have consumed gen2 budget.

**Comment by mateusz-osojca** [comment]
Thanks a lot!
