### ISSUE TITLE
SIGSEGV is not transformed into NullReferenceException in WSL

### ISSUE THREAD

**Issue by scalablecory** [dotnet/coreclr#25945]
Under WSL (at least Ubuntu 18.04, and seemingly OpenSUSE 15) , SIGSEGV is not caught and transformed into a `NullReferenceException` as it is on other platforms.

Repro:

```c#
class Program
{
    static unsafe void Main(string[] args)
    {
        int* ptr = null;
        Console.WriteLine(*ptr);
    }
}
```

```
cory@conelso1:~/39732-smtp-segfault$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview7-012821/

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  3.0.100-preview7-012821 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
cory@conelso1:~/39732-smtp-segfault$ ./bin/Debug/netcoreapp3.0/39732-smtp-segfault
Segmentation fault (core dumped)
```

Found during our investigation of https://github.com/dotnet/corefx/issues/39732

cc @janvorli @wfurt

**Comment by mjsabby** [comment]
This is a regression in preview7. Likely https://github.com/dotnet/coreclr/pull/25196

**Comment by janvorli** [comment]
Thanks @mjsabby, it is possible that WSL reports the alternate stack in some weird way that we cannot detect. I'll look into it.

**Comment by janvorli** [comment]
I've looked into it. The problem is that WSL doesn't report the alternate stack in the `uc_stack` member of the `ucontext_t` passed to the sigsegv handler. All the `uc_stack` fields are zero. That prevents detection of whether the signal handler is executing on an alternate stack or not. This detection was added in the #25196 to fix issue #25166.

This is unfortunate. Thinking about possible solutions:
* Add an env variable that could be used to disable this check and consider the sigsegv handler to always run on an alternate stack. Setting this variable would effectively disable the fix #25196. Anyone running dotnet core apps on WSL would have to set it.
* Similar to the previous one, but instead of introducing an env variable, detect that we are running on WSL. I'm not sure if such detection is feasible though. 
* Check if it works fine with WSL2 and if it does, consider only the WSL2 as supported for .NET core.

@jkotas, @sergiy-k any thoughts?

**Comment by jkotas** [comment]
Can se detect that ‘uc_stack’ was not set - is ‘uc_stack’ ever set to null when it works correctly?

**Comment by janvorli** [comment]
* On glibc based Linux, when the sigsegv handler is executed on a regular stack, the uc_stack members are 0  too except for the ss_flags that contains 2 (SS_DISABLE). 
* On MUSL based Linux, the uc_stack members are all zeros when the sigsegv handler is executed on a regular stack
* On WSL, all the uc_stack members are 0 no matter whether the alternate stack is enabled or disabled.

In other words, uc_stacks being all zeros means:
* WSL when running both on regular and alternate stack
* MUSL when running on alternate stack

So we could possibly say that we don't support MUSL based distros under WSL and have #ifdef for MUSL / GLIBC that would add a check for GLIBC builds that would consider the case when uc_stack.ss_flags is zero as "running on alternate stack".

**Comment by janvorli** [comment]
I was also thinking about a solution that would not rely on the info provided in the uc_stack and keep a global data structure containing ranges of all allocated alternate stacks (as we cannot access TLS) instead. But it would have to be something clever that would provide a reasonably fast lookup even in presence of many threads and be able to handle the fact that entries can be added and removed by newly created threads at the same time we perform the lookup.

**Comment by mjsabby** [comment]
@janvorli given we’re running out of time for 3.0 what would we a reasonable thing to do for 3.0 to bring back WSL support?

**Comment by janvorli** [comment]
Thinking about it more, it seems that a reasonable fix for 3.0 could be:
* Introduce an env var that would enable the alternate stack check (if that variable is set)
* Without that variable set, the sigsgegv_handler would be considered to be always running on an alternate stack (like it was before #25196)

So users of .NET Core apps that use a third party native library that registers its own SIGSEGV handler without an alternate stack enabled (which is likely a very small percentage of apps) would have to set this env var.

@jkotas, does it sound reasonable to you?

cc: @PiotrSpikowski

**Comment by janvorli** [comment]
cc: @sergiy-k

**Comment by sergiy-k** [comment]
Thank you @janvorli. It sounds reasonable to me to revert to the previous (Core 2.x) behavior by default and make the new behaviour an opt in option for special cases.
