### ISSUE TITLE
 Marshal.ReleaseComObject and .NET 2.0 / 4.6.1 / Core 3.0

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/coreclr#25950]
Hi All,
I have a few questions about .NET and Com Interop.  Specifically as it relates to .NET core and the .NET framework.

I remember back in the old days, whenever you worked with a COM object (for example, Outlook interop), you had to remember to call ````Marshal.ReleaseComObject(o)````.

In the modern .NET 4.x and .Net Core 3.0 days, do I still need still need to do that or does that happen automatically when the object falls out of scope or is GCed?

**Comment by TonyValenti** [comment]
Also, related to this, I've seen a lot of code showing ReleaseComObject, but this article:
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.releasecomobject?view=netframework-4.8

says only use it if absolutely necessary and this article (the comment with 7 upvotes):
https://stackoverflow.com/questions/15728676/proper-way-of-releasing-com-objects

says don't use it at all.

**Comment by jkoritzinsky** [comment]
Unless you really need a deterministic call to `Release` on your COM object (like if your COM object creates some temporary state on disk that is cleans up when released and you don't want to rely on GC to clean it up), waiting for a GC after the last use is too long (your application doesn't generate enough memory usage to trigger a GC) or you need to guarantee that the COM object gets released (GC doesn't run on all RCWs on shutdown), you shouldn't call `Marshal.ReleaseComObject`.  The COM object will automatically be `Release`d when the last managed object referencing it is GC'd.

I've seen only a small number of use cases (specifically the first "temporary state on disk" case) where a `Marshal.ReleaseComObject` is needed. For almost all cases, just relying on the GC should work as you need.
