### ISSUE TITLE
dotnet-diagnostic sockets lingering after crash

### ISSUE THREAD

**Issue by spencercw** [dotnet/coreclr#25968]
.NET Core version: 3.0.0-preview7-27912-14 Linux

My target is an arm64 embedded platform, but I am seeing the same behaviour on my x64 dev machine.

The runtime is leaving these diagnostic sockets with names like `dotnet-diagnostic-28148-23379390-socket` under /tmp if the process exits with an unhandled exception. If the process is repeatedly crashing in this way then these sockets pile up, using more and more memory (/tmp is mounted in RAM on my system), eventually overwhelming the system. Is there a way to prevent these sockets from being created, or ensuring that they are cleaned up properly on an unhandled exception?

How I am running my executable:
```
$ dotnet test.dll
Unhandled exception. [Trim]
Aborted
```

**Comment by spencercw** [comment]
Thanks for fixing this. Is this going to be applied to .NET Core 3.0 or will it only appear in .NET 5? I have just tried .NET Core 3.0 preview 8 and the issue is still occurring.

**Comment by sywhang** [comment]
The master branch is .NET 5. The fix wasn't ported to 3.0 branch though because the bar for getting fixes into 3.0 is pretty high now as we're closing down on preview releases and getting ready for the GA release. Is there a particular scenario this issue would block you?

**Comment by spencercw** [comment]
Hi @sywhang. It's not so much blocking anything, but it presents a platform reliability issue for us. Essentially, if our software gets into some faulty state that it is constantly crashing and restarting, it will eventually overwhelm the system by using all available memory just to store these diagnostic sockets. Granted I can ensure this won't occur by just creating a cron job to delete the sockets, but it would be preferable for the runtime to clean up after itself.

I wouldn't be surprised if this catches a few people out and takes down the odd production system by consuming either all available memory or all available disk space.

**Comment by sywhang** [comment]
Thanks @spencercw -- let me try to bring this up and see if I can port the fix to 3.0.

**Comment by sywhang** [comment]
@spencercw The fix has been merged to 3.0 branch -- it will be available in .NET Core 3.0 Preview 9. Thanks for reporting the issue!

**Comment by spencercw** [comment]
Great, thanks for pushing that through. :)
