### ISSUE TITLE
.NET Core apps emitting bad ETW events through DotNetRuntime provider

### ISSUE THREAD

**Issue by davidmikh** [dotnet/coreclr#25982]
Steps to repro:

1) Create a .NET Core console app
2) Add some basic code so there's some activity to profile (I used the following to repro this issue)

        static void Main(string[] args)
        {
            Stopwatch watch = new Stopwatch();
            watch.Start();
            while(true)
            {
                System.Console.WriteLine("CONTINUE WRITING LINES");
                if (watch.ElapsedMilliseconds > 5000)
                {
                    return;
                }
            }
        }

3) Build the application
4) Profile the application's exe using perfview (Collect -> Run), the only provider you need to enable is `Microsoft-Windows-DotNETRuntime::Verbose`

![image](https://user-images.githubusercontent.com/12531222/62333223-75aeab00-b477-11e9-8e04-32bc5e40f009.png)

5) Open the events view of the generated ETL file
6) Open the event type `Microsoft-Windows-DotNETRuntime/Method/ILToNativeMap`

Perfview is unable to load any events for `Microsoft-Windows-DotNETRuntime/Method/ILToNativeMap`

This was done using .NET Core 3.0.100-preview8-013437

**Comment by noahfalk** [comment]
This appears to be by (questionable) design. coreclr is emitting the events and they are being recorded in the .etl file. However when PerfView converts the .etl file into an .etlx file it special cases certain known events such as ILToNativeMap. Rather preserving these events in the form of events their data gets composed into other data structures. In the case of ILToNativeMap events the .eltx file builds a dictionary of method -> ILMapping information. Once this transformation happens the events are no available for viewing in the event view.

I checked this out a few different ways:
1) Under the 'Advanced Group' folder you can find an 'EventStats' report. This report includes a count for ILToNativeMap events
2) I wrote a sample snippet that parsed the etl file directly without converting it to .etlx and confirmed the callback for ILToNative events was triggered.

```
using (var traceSource = new ETWTraceEventSource(@"C:\Users\noahfalk\Downloads\PerfViewData.etl", TraceEventSourceType.FileOnly))
            {
                traceSource.Clr.MethodILToNativeMap += Clr_MethodILToNativeMap;
                traceSource.Process();
            }
```

3) I debugged the conversion code for eltx and confirmed that ILToNative events were observed during the conversion: https://github.com/microsoft/perfview/blob/master/src/TraceEvent/TraceLog.cs#L8853

4) TraceLog supports a KeepAllEvents option (https://github.com/microsoft/perfview/blob/master/src/TraceEvent/TraceLog.cs#L10347) that prevents the ILToNative events from being discarded. Setting that to true the Events view in the UI works how you would expect and the events are listed.

**Comment by tommcdon** [comment]
Closed and transferred to the perfview repo on microsoft/perfview#982
