### ISSUE TITLE
JIT Optimization: Replace a bunch of cmp with a single shr

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#25985]
```csharp
bool IsReservedCharacter(char character)
{
    return (character == ';')
        || (character == '/')
        || (character == ':')
        || (character == '@')
        || (character == '&')
        || (character == '=')
        || (character == '+')
        || (character == '$')
        || (character == ',');
}
```
Currently generates:
```asm
; Method ConsoleApp176.Program:IsReservedCharacter1(ushort):bool
G_M56726_IG01:
       nop      

G_M56726_IG02:
       movzx    rax, cx
       cmp      eax, 59
       je       SHORT G_M56726_IG04
       cmp      eax, 47
       je       SHORT G_M56726_IG04
       cmp      eax, 58
       je       SHORT G_M56726_IG04
       cmp      eax, 64
       je       SHORT G_M56726_IG04
       cmp      eax, 38
       je       SHORT G_M56726_IG04
       cmp      eax, 61
       je       SHORT G_M56726_IG04
       cmp      eax, 43
       je       SHORT G_M56726_IG04
       cmp      eax, 36
       je       SHORT G_M56726_IG04
       cmp      eax, 44
       sete     al
       movzx    rax, al

G_M56726_IG03:
       ret      

G_M56726_IG04:
       mov      eax, 1

G_M56726_IG05:
       ret      
; Total bytes of code: 64
```
LLVM (Clang/Mono-LLVM) generates:
```asm
; IsReservedCharacter(unsigned short):
        add edi, -36
        cmp di, 28
        ja .LBB0_2
        mov eax, 314575237
        shrx eax, eax, edi ; or shr if shrx is not available
        and al, 1
        ret
.LBB0_2:
        xor eax, eax
        ret
```

So if values are close to each other it's possible to calculate a special bit-map (`314575237` in this case) and apply a shift to find out whether `c` is one of the chars or not (or, in some cases, even a jump table). Btw, LLVM's opt converts it to a switch and then DAG calculates the bitmap and insert the shift op.

There are really a lot of affected places in CoreFX, especially around URL parsing, examples:
[Uri.cs:L550](https://github.com/dotnet/corefx/blob/954b1fdab8e98060cce3d0d88a34c3b0587a6acb/src/System.Private.Uri/src/System/Uri.cs#L550)
[Uri.cs:L5555](https://github.com/dotnet/corefx/blob/954b1fdab8e98060cce3d0d88a34c3b0587a6acb/src/System.Private.Uri/src/System/Uri.cs#L5555)
[Uri.cs:L5587](https://github.com/dotnet/corefx/blob/954b1fdab8e98060cce3d0d88a34c3b0587a6acb/src/System.Private.Uri/src/System/Uri.cs#L5587)
[Uri.cs:L5626](https://github.com/dotnet/corefx/blob/954b1fdab8e98060cce3d0d88a34c3b0587a6acb/src/System.Private.Uri/src/System/Uri.cs#L5626)
[Convert.cs:L2776](https://github.com/dotnet/corefx/blob/954b1fdab8e98060cce3d0d88a34c3b0587a6acb/src/Common/src/CoreLib/System/Convert.cs#L2776)
[IPv4AddressHelper.Common.cs:L128](https://github.com/dotnet/corefx/blob/954b1fdab8e98060cce3d0d88a34c3b0587a6acb/src/Common/src/System/Net/IPv4AddressHelper.Common.cs#L128)

**Comment by mikedn** [comment]
Seems like a subset of #12477

**Comment by EgorBo** [comment]
@mikedn Oh, indeed! Closing this.
