### ISSUE TITLE
Wrong reflection invocation on ARM64 with HFAs

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/coreclr#25993]
The following example should print 1 twice but prints 0 when invoked through reflection on ARM64:
```csharp
public struct Hfa
{
    public double A, B, C, D;
    public Hfa(double a, double b, double c, double d)
    {
        A = a;
        B = b;
        C = c;
        D = d;
    }
}
public class Program
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static double Foo(double a, Hfa b, Hfa c) => c.B;

    internal static void Main()
    {
        Console.WriteLine(Foo(0, new Hfa(), new Hfa(0, 1, 0, 0)));

        object[] arr = { 0d, new Hfa(), new Hfa(0, 1, 0, 0) };
        MethodInfo fooMI = typeof(Program).GetMethod("Foo");
        Console.WriteLine(fooMI.Invoke(null, arr));
    }
}
```

**Comment by jashook** [comment]
This most likely is related to #10257

**Comment by jashook** [comment]
As in a case we do not have testing for.

**Comment by jashook** [comment]
Verified this change is an incorrect marshaling of HFA types during reflection invocation. @sergiy-k any suggestions on routing?

**Comment by jakobbotsch** [comment]
As part of a fix to this issue the following method can be removed from the ABI stress test and regular reflection can be used instead:
https://github.com/dotnet/coreclr/blob/fdb2bc4233bf93e44bda4b1ae3b1432e80c9f0da/tests/src/JIT/Stress/ABI/Program.cs#L421-L439

https://github.com/dotnet/coreclr/blob/fdb2bc4233bf93e44bda4b1ae3b1432e80c9f0da/tests/src/JIT/Stress/ABI/Program.cs#L403-L404

https://github.com/dotnet/coreclr/blob/fdb2bc4233bf93e44bda4b1ae3b1432e80c9f0da/tests/src/JIT/Stress/ABI/Program.cs#L415-L416
