### ISSUE TITLE
[Missing?] documentation

### ISSUE THREAD

**Issue by fr0stbyte** [dotnet/coreclr#26]
At https://github.com/dotnet/coreclr/blob/master/src/gc/gc.cpp#L10 it is mentioned some documentation living at ../../doc/BookOfTheRuntime/GC/GCDesign.doc

Is it possible to make that documentation available, or at least the BookOfTheRuntime ?

Thanks

**Comment by gkhanna79** [comment]
Thanks fr0stbyte. We are working on getting the documentation up for various key pieces of the runtime.
@brianrob - FYI

**Comment by brianrob** [comment]
@fr0stbyte, this doc is now available at https://github.com/dotnet/coreclr/blob/master/Documentation/garbage-collection.md.  It has been there since we starting adding Book of the Runtime docs, but I just noticed that I hadn't responded back to this one.

**Comment by fr0stbyte** [comment]
@brianrob thanks -- did noticed the document going up
