### ISSUE TITLE
STATUS_STACK_BUFFER_OVERRUN in corefx consuming updated coreclr

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#26010]
https://github.com/dotnet/corefx/pull/39995#issuecomment-518300413
![image](https://user-images.githubusercontent.com/2642209/62488304-f6c8b380-b791-11e9-940f-a542148ea2f2.png)

From @jkotas:
"This is most likely caused by @janvorli change dotnet/coreclr#25795 . @janvorli Could you please take a look?"

**Comment by jkotas** [comment]
@janvorli is on vacation. I am reverting the problematic change in #26029
