### ISSUE TITLE
Missing script: makeSmOpcodeDef.pl

### ISSUE THREAD

**Issue by bugproof** [dotnet/coreclr#26038]
https://github.com/dotnet/coreclr/blob/master/src/jit/smopcode.def

> To generate this file, run "makeSmOpcodeDef.pl > smopcode.def"                        

But there's no such script in the repo.

category:implementation
theme:inlining
skill-level:beginner
cost:small

**Comment by BruceForstall** [comment]
I don't think we're going to ever fix this, but you can find the script in the unmerged PR https://github.com/dotnet/coreclr/issues/26038 at least for now.
