### ISSUE TITLE
Publishing runtime.linux-arm64.Microsoft.NETCore.ILAsm?

### ISSUE THREAD

**Issue by omajid** [dotnet/coreclr#26077]
I noticed that https://www.nuget.org/packages/runtime.linux-arm.Microsoft.NETCore.ILAsm/ (arm 32) exists, but not https://www.nuget.org/packages/runtime.linux-arm64.Microsoft.NETCore.ILAsm/ (arm64). Is this intentional? Is this a bug I can contribute a fix for?

**Comment by AaronRobinsonMSFT** [comment]
I think @jkoritzinsky has recently been working with the ILDasm/ILAsm packages. Perhaps he would know.

**Comment by omajid** [comment]
FWIW, this prevents corefx from building on arm64 (not cross compiled, but a hosted build)

**Comment by jkoritzinsky** [comment]
@omajid if you look at the pre-release package feed for CoreCLR (https://dotnetfeed.blob.core.windows.net/dotnet-coreclr/index.json), you'll see the linux-arm64 package for ILAsm exists.

**Comment by omajid** [comment]
Ah, so I was looking in the wrong place. Thanks for the clarification! I am going to close this issue now.
