### ISSUE TITLE
Incorrect copy prop substitution

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#2610]
Repro program:

<text>
using System;
using System.Runtime.CompilerServices;

namespace ConsoleApplication1
{
    public struct MyValue
    {
        public long val;
        public MyValue(long a) 
       { val = a; }
    }

    public struct MyStruct
    {
        public MyValue v1;
        public MyValue v2;

        public MyStruct(MyValue a, MyValue b)
        { v1 = a; v2 = b; }
    }
    class Program
    {
        static void Main(string[] args)
        {
            MyValue p1 = new MyValue(10);
            MyValue p2 = new MyValue(20);

            MyStruct c1 = new MyStruct(p1, p2);
            MyStruct c2 = new MyStruct(p2, p1);
           
            bool b1 = Program.IsXGeater(c1);
            bool b2 = Program.IsXGeater(c2);
            bool b3 = Program.IsXGeater(c1);
            bool b4 = Program.IsXGeater(c2);

            Console.WriteLine(b1);
            Console.WriteLine(b2);
            Console.WriteLine(b3);
            Console.WriteLine(b4);
        }

        // Return true if p1.x > p2.y
        [MethodImplAttribute(MethodImplOptions.NoInlining)]
        public static bool IsXGeater(MyStruct line)
        {
            if (line.v1.val > line.v2.val)
            {                
                line = new MyStruct(line.v2, line.v1);
                return true;
            }

            return false;
        }
    }
}
</text>

Expected:
False
True
False
True

Observed:
False
True
False
False

Initial investigation reveals there is a bug in jitted code of main method.

// input code fragment
bool b1 = Program.IsXGeater(c1);
bool b2 = Program.IsXGeater(c2);
bool b3 = Program.IsXGeater(c1);
bool b4 = Program.IsXGeater(c2);

<text>
// Correct code that is supposed to be generated
// Since structs are passed by value, caller is supposed to make a copy and pass it by reference
tmp = c1
b1 = IsXGreater(&tmp)
tmp = c2
b2 = IsXGreater(&tmp)
tmp = c1
b3 = IsXGreater(&tmp)
tmp = c2
b4 = IsXGreater(&tmp)

// Actual code generated
tmp = c1
b1 = IsXGreater(&c1)
tmp = c2
b2 = IsXGreater(&c2)
tmp = c1
b3 = IsXGreater(&tmp)
tmp = c2
b4 = IsXGreater(&tmp)
</text>

That is, instead of passing tmp by reference, jitted code is passing c1 and c2 by reference.  The second IsXGreater() call will modify its input argument thinking that the caller has passed a copy and hence the fourth call will return wrong result.

Substitution of c2 by c1 in GT_ADDR(lcl_Var c2) is done by Copy Prop incorrectly.  

Note: Copy prop is supposed to not make such a substitution for addr-exposed variables.  Double check whether tmp is getting marked as addr-exposed or a such a check is needed in copy prop code.

**Comment by clrjunkie** [comment]
I can't manage to reproduce this using VS2015 U1 (release/debug) as well as by directly compiling corefx/coreclr and corerun from yesterday git clone.

False
True
False
True

**Comment by hoyMS** [comment]
Fixed.

**Comment by CarolEidt** [comment]
@hoyMS Please in future include the issue # in the PR. (In this case #2612)
