### ISSUE TITLE
GregorianCalendarHelper.GetLeapMonth always returns 0?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#26103]
https://github.com/dotnet/coreclr/blob/c9150c99d4c5c565ca6958bcf9434e7a4b7868a0/src/System.Private.CoreLib/shared/System/Globalization/GregorianCalendarHelper.cs#L593-L597

At best this is wasting CPU.
At worst it's giving the wrong answer to its callers.

cc: @tarekgh

**Comment by tarekgh** [comment]
@stephentoub This method is used by the east Asian calendars only which should return 0 all the time. the call to GetGregorianYear is needed for validation and throwing the proper exception.

**Comment by stephentoub** [comment]
In that case it should just be a void-returning Validate* method.

**Comment by tarekgh** [comment]
> In that case it should just be a void-returning Validate* method.

I am neutral how to write it, but this will need to have us edit all calendars using this method and explicitly return 0 from there after calling this validating method. I am not sure if this is worth to do it.
