### ISSUE TITLE
Creating a custom debugger

### ISSUE THREAD

**Issue by raffaeler** [dotnet/coreclr#26117]
Hello, I am trying to understand how to create a custom debugger allowing the user to make some very basic investigation.
* Running or attaching some .NET Core code on Linux (pdb is available)
* Setting one or more breakpoints
* Stepping through the code
* Getting the local variables after each step
I started investigating clrmd but I can't see anything helpful to step and setting breakpoints.

It looks like @mikem8361 is working on that (https://github.com/dotnet/coreclr/issues/10568#issuecomment-290771734) but still not sure how can I setup a simple example to start from.

Thanks for any advice.

**Comment by noahfalk** [comment]
I wound up helping @raffaeler offline so I think this is resolved now.
