### ISSUE TITLE
WSL Ubuntu 18: System.Environment.GetFolder returns null

### ISSUE THREAD

**Issue by capra314cabra** [dotnet/coreclr#26110]
I ran `System.Environment.GetFolder()` by each values on WSL and got the result followings:

|Enum Value|Return|
|---|---|
|Desktop||
|Programs||
|MyDocuments|/home/capra|
|MyDocuments|/home/capra|
|Favorites||
|Startup||
|Recent||
|SendTo||
|StartMenu||
|MyMusic||
|MyVideos||
|DesktopDirectory||
|MyComputer||
|NetworkShortcuts||
|Fonts||
|Templates||
|CommonStartMenu||
|CommonPrograms||
|CommonStartup||
|CommonDesktopDirectory||
|ApplicationData||
|PrinterShortcuts||
|LocalApplicationData||
|InternetCache||
|Cookies||
|History||
|CommonApplicationData|/usr/share|
|Windows||
|System||
|ProgramFiles||
|MyPictures||
|UserProfile|/home/capra|
|SystemX86||
|ProgramFilesX86||
|CommonProgramFiles||
|CommonProgramFilesX86||
|CommonTemplates||
|CommonDocuments||
|CommonAdminTools||
|AdminTools||
|CommonMusic||
|CommonPictures||
|CommonVideos||
|Resources||
|LocalizedResources||
|CommonOemLinks||
|CDBurning||

This results contained `null` values more than I had expected.
So can I know whether it was working right or not?
Thank you for your help.

Environment: .NET SDK 3.0.100-preview7-012821

**Comment by capra314cabra** [comment]
I built sources for linux-x64 on Windows and ran the binary on WSL.

**Comment by danmosemsft** [comment]
@capra314cabra any interest in debugging a little to figure out what's going on?

**Comment by capra314cabra** [comment]
I have. I will try it.

**Comment by capra314cabra** [comment]
@danmosemsft Sorry, it's not a bug but my mistake. It caused because the expected paths such as '/home/[user name]/.config' doesn't exist.
``` C#
// Failed verification.  If None, then we're supposed to return an empty string.
// If Create, we're supposed to create it and then return the path.
if (option == SpecialFolderOption.None)
{
    return string.Empty;
}
```

**Comment by danmosemsft** [comment]
Not a problem...thanks for checking!
