### ISSUE TITLE
Optimization issue in Bytemark IDEA

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#2615]
See #2614.

IDEA fails validation with RyuJit. Passes with min opts, passes with Jit64, passes with LLILC. So seems to be an optimizer bug.

To repro, remove these lines in bytemark.cs and recompile:
```
        // Disable IDEA for now since it doesn't validate.
        global.ideastruct.bRunTest = false;
        OutputString("** Note: IDEA disabled **");
        OutputString("");        
```

Note there's a second patch of code toward the end of the file to disable IDEA when used as an xunit-performance benchmark; this should likewise be removed once the bug is fixed.

You can run just this test by passing the appropriate config file on the command line, for instance
```
corerun Bytemark.exe -ccommands\idea.dat
```
(the commands file directory lives with the sources).

Isolation with `COMPlus_JitMinOpts` indicates the issue is in `IDEAEncryption::cipher_idea`.

This test uses a lot of 16-bit math. I tried cherry-picking #2568 but it didn't help.

**Comment by hoyMS** [comment]
Not repro. Likely fixed by 

commit 952a540d6d08619fc690b783035eb54233139355
Merge: bae54c9 63268a3
Author: Sejong Oh <sejooh@microsoft.com>
Date:   Mon Jan 11 12:58:40 2016 -0800

    Merge pull request #2568 from sejongoh/bugfix_unsigned_16bit_cmp_codegen

    Fix bad codegen for comparing 16-bit unsigned values
