### ISSUE TITLE
Should have variable to disable tests via pipeline variable

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/coreclr#26162]
There should be a way to disable the test runs when queuing a build. This could be limited to only `internal.yml` but we should have a way so testing certain non-test related pipeline changes could be done faster.

/cc @dotnet/coreclr-infra

**Comment by jashook** [comment]
This would be an overall improvement to our system but I am unsure of how to actually implement this. It seems like azure dev ops would have to implement queuing pipelines with variables.

**Comment by jashook** [comment]
@echesakovMSFT may have ideas.

**Comment by elinor-fung** [comment]
I thought this was already possible? You can edit the pipeline variables on the build definition in Azure DevOps to add a variable with a default value and allow setting it at queue time (and make the yml respect it). I think we already do something similar for `_SignType` in the internal build?

**Comment by jashook** [comment]
This is defiantly possible. For some reason I read this as being able to pass parameters from the pipeline invocation in Github.

**Comment by AaronRobinsonMSFT** [comment]
Nope. This would only be on internal builds.

**Comment by jashook** [comment]
I can see value in potentially skipping on request in a or as well. But that seems less possible.

**Comment by echesakovMSFT** [comment]
We can create a pipeline variable and set condition in test-job.yml that checks the value. For example, something like this
`condition: ne(variables['_TestBuild'], 'skip'):` and also specify the variable in UI so it can be configured during queuing a job in the internal build definition
