### ISSUE TITLE
ICorDebug: Allow setting function breakpoints when not stopped

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/coreclr#26182]
Currently when calling `ICorDebugFunction.CreateBreakpoint()` when the debuggee is running you get an error:

```
System.Runtime.InteropServices.COMException (0x80131302): Process not synchronized. (Exception from HRESULT: 0x80131302)
```

From @noahfalk: Its by design (perhaps not by good or intentional design though). The source for Function.CreateBreakpoint() requires the debuggee is already stopped:
https://github.com/dotnet/coreclr/blob/master/src/debug/di/rsfunction.cpp#L411

Whereas in the ICorDebugCode::CreateBreakpoint path that check isn’t there and the implementation will automatically pause/resume the debuggee if you call it while the debuggee is running:
https://github.com/dotnet/coreclr/blob/master/src/debug/di/breakpoint.cpp#L172

We should consider switching `ICorDebugFunction.CreateBreakpoint` to allow running debuggee, it should automatically pause/resume like `ICorDebugCode.CreateBreakpoint`.

**Comment by noahfalk** [comment]
Thanks for the suggestion @KirillOsenkov! I agree this would be an improvement. Given the availability of a workaround (call Stop(), then CreateBreakpoint(), then Continue()), the very low usage of ICorDebug APIs, and our many other issues which don't have such easy alternatives I'm going to close this "Won't Fix" so we can prioritize other work.
