### ISSUE TITLE
Does 'System.Runtime.Loader, Version=4.1.0.0' will support to 'standard2.1'?

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/coreclr#26187]
I intend to add AssemblyManagement to my library, which requires System.Runtime.Loader `AssemblyLoadContext.Unload`.  Will the official package this feature? Or let it run on the standard2.1.

**Comment by jkotas** [comment]
netstandard2.1 does not support System.Runtime.Loader contract. This contract was explicitly excluded from netstandard2.1: https://github.com/dotnet/standard/blob/master/docs/planning/netstandard-2.1/README.md
