### ISSUE TITLE
Trimming defaults cause WPF app to crash on launch

### ISSUE THREAD

**Issue by onovotny** [dotnet/coreclr#26196]
With the latest code of NuGet Package Explorer in master, I added <PublishTrimmed>true</PublishTrimmed> to the main exe csproj and then published as self-contained x64. The app  failed to launch. When I set that published exe as the startup object in the debugger, I got a lot of exceptions (attached).

There appear to be two main categories:

1.	Things attached to ConfigurationManager that has a wide impact
2.	Issues with ETW sources (look for the EventSource ERROR in the log)

[NPE debug log with trimming.txt](https://github.com/dotnet/coreclr/files/3507367/NPE.debug.log.with.trimming.txt)

**Comment by jeffschwMSFT** [comment]
@onovotny the mono/linker is not enlighted about most reflection based discovery.  In these cases we can help you craft a roots file to ensure the right details are rooted (leading to your application working).

cc @sbomer @tlakollo

**Comment by sbomer** [comment]
Moved to mono/linker
