### ISSUE TITLE
Modernize TypedReference

### ISSUE THREAD

**Issue by sakno** [dotnet/coreclr#26201]
The current proposal is about how to make `typedref` usable in the same way as `Span`/`ReadOnlySpan`:
1. Allow to create `typedref` using static factory method without magic of undocumented `__makeref` keyword
1. Allow to return `typedref` from the method
1. Allow to pass `typedref` by reference
1. Allow to declare `typedref` as a member of another by-ref-like value
1. Rewrite internals of `typedref` in the way when this value type can be treated like regular by-ref-like value type
1. Allow to obtain raw managed pointer (probably, protected with `ref readonly`) to the stored reference.
1. Allow to obtain reference to the field without knowing actual type of the field

The rewritten version of this type could by look like this (existing methods are omitted):
```csharp
public ref struct TypedReference
{
  private readonly RuntimeTypeHandle _type;
  private readonly ByReference<byte> _reference;
  //new members
  public static TypedReference Make<T>(ref T value);
  public static TypedReference Make<T>(in T obj, RuntimeFieldHandle field);
  public bool IsTypeOf<T>();
  public ref readonly T AsRef<T>();
  public ref readonly byte RawData { get; }
  //existing members
  public static Type GetTargetType (TypedReference value);
  public static TypedReference MakeTypedReference (object target, System.Reflection.FieldInfo[] flds);
  public static void SetTypedReference (TypedReference target, object value);
  public static object ToObject (TypedReference value);
}
```

`Make` and `IsTypeOf` can be implemented as JIT intrinsics or using pure IL.

Overloaded `Make` method allows to create a reference to the specified field. `in` is required to avoid boxing if `T` is value type

`RawData` allows to obtain managed pointer to the data referenced by `typedref` without knowing of actual type. All other manipulations can be done using `Unsafe` class.

`AsRef` is type-safe version which is alternative to `__refval` keyword in C#. `readonly` is needed here because typed reference may represent `initonly` field. If consumer knows that the typed reference is mutable then `Unsafe` class can be used to convert immutable ref to mutable ref.

Two internal `IntPtr` fields can be replaced with `ByReference` and `RuntimeTypeHandle`. After such modification, CLR and GC can interpret typed reference as regular by-ref-like value type.

Optionally, the type can be marked as CLS compliant.

Modernized version of `TypedReference` can be used to solve the following issues:
1. [Reflection support for Span&lt;T&gt;](https://github.com/dotnet/coreclr/issues/17296)
1. [GetRawData](https://github.com/dotnet/corefx/issues/33706) method which can return a typed reference constructed dynamically for the first field in the class.
1. [GetRawArrayData](https://github.com/dotnet/corefx/issues/36133) method which can return a typed reference for the first array item

There is one drawback: at this moment it is possible to declare unmanaged pointer to `typedref`, see #25697 . This proposal breaks this ability.

**Comment by MichalStrehovsky** [comment]
API suggestions happen in the CoreFX and follow the [api review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).

Sounds related to dotnet/corefx#29736 - maybe the conversation can be moved there?

**Comment by sakno** [comment]
I thought that `TypedReference` is a special typed treated by CLR so I create this conversion here. I'm closing this ticket. Should I copy proposal text to the ticket mentioned by you?

**Comment by MichalStrehovsky** [comment]
It would be great if you could highlight details not already discussed in the CoreFX issue (your proposal calls out for the ability to get the address of the captured reference _without_ having to provide the type, concerns about readonly, etc.). Thanks!

**Comment by sakno** [comment]
Sure, no problem
