### ISSUE TITLE
COM Interop: support custom marshalling

### ISSUE THREAD

**Issue by bclothier** [dotnet/coreclr#26207]
The documentations for .NET Framework for various methods / objects defined within `System.Runtime.InteropServices` has been marked with `Obsolete,` mainly with comment that it may be unavailable in future releases. I'm including few samples:

[ICustomQueryInterface](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.icustomqueryinterface?view=netframework-4.8)
[DispatchWrapper](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dispatchwrapper?view=netframework-4.8)
[Marshal.GetObjectForNativeVariant](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getobjectfornativevariant?view=netframework-4.8)

I would very much rather that the .NET Core continue to support those functionalities, even if it ends up being slightly different from what is available currently in .NET framework. For our project, we do use the `ICustomQueryInterface` and we have a need to use `GetObjectForNativeVariant` (and its siblings) but it being marked as obsolete makes us worried.

**Comment by jeffschwMSFT** [comment]
cc @jkoritzinsky @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@bclothier Thank you for bringing this up. The marking of obsolete on these types and methods and various other COM related methods/attributes/types was done a while ago by an overaggressive automated process. Rest assured that COM compatibility is a priority for .NET Core. The support may not necessarily be bug-for-bug compatible with .NET Framework but support for COM scenarios to help users transition to .NET Core is a goal.

I hope this goes without saying but for the sake of the community I will mention it, support for these functions is in most cases limited to Windows only and users should _not_ assume support on non-Windows platforms. That isn't meant to indicate they won't work simply that their existence is for porting .NET Framework applications with COM to .NET Core with COM which implies Windows only.

For questions/concerns regarding types marked with `ObsoleteAttribute`, please file bugs in https://github.com/dotnet/corefx.
