### ISSUE TITLE
memory violation sig=6

### ISSUE THREAD

**Issue by hours10000** [dotnet/coreclr#26249]
Hi All，
Recently, my .net core console app was crashed several times. Because the production enviroment does not enable coredump，so I did not get any userful information.But "/var/log/audit/audit.log" has a log:

`type=ANOM_ABEND msg=audit(1563179050.707:241662): auid=1000 uid=1000 gid=1000 ses=25261 pid=2840 comm="dotnet" reason="memory violation" sig=6`

I know sig=6 was triggered by system ,they aren't exceptions, they're signaled from the OS。I did not get any idea on why I met this error。I searched github, did not get any signs。

Any ideas? Thanks  .

(Today, I enable core dump on production enviroment.If it crash again ,I will upload the trace info.)

`
**OS**: gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
      Linux version 3.10.0-957.27.2.el7.x86_64 
      CentOS Linux release 7.6.1810 (Core)
**.net core**: 
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]`

**Comment by janvorli** [comment]
The sig 6 is SIGABRT. This usually happens when there is an unhandled managed exception, an assert or an unrecoverable error occurs in the runtime. If you manage to get the crore dump, it should be easy to figure out which one of those happened.

**Comment by hours10000** [comment]
The console app crashed agian this morning, but we did not get any coredump file，what a pity!
If we kill the console app with command "kill -6 ourPID", there will be a coredump file。
I don't know why there is no coredump file。We need further investigation to verify this issue

**Comment by hours10000** [comment]
OK, We find out the reason why it does not generate core dump file. So , I will waiting for the next crash....

**Comment by hours10000** [comment]
The console app crashed last night, and we found out the reason why it crashed. It's a bug in our code。Thanks all.
