### ISSUE TITLE
Wrong value in native callback method | or | Issue with enum equality

### ISSUE THREAD

**Issue by RUSshy** [dotnet/coreclr#26267]
```c#
			[UnmanagedFunctionPointer(CallingConvention.Cdecl), SuppressUnmanagedCodeSecurity]
			public delegate GLFWkeyfun glfwSetKeyCallback(IntPtr window, GLFWkeyfun cbfun);

		[UnmanagedFunctionPointer(CallingConvention.Cdecl), SuppressUnmanagedCodeSecurity]
		public delegate void GLFWkeyfun(IntPtr window, int key, int scancode, int action, int mods);


(...)

        private GlfwNative.GLFWkeyfun _keyFunc;

(...)

            _keyFunc = keyCallback;
            GlfwNative.glfwSetKeyCallback(_window, _keyFunc);

(..)

        private void keyCallback(IntPtr window1, int key, int scancode, int action, int mods)
        {
            switch (action)
            {
                case GlfwNative.GLFW_PRESS:
                    var convertedKey = convertGlfwKey(key);
                    
                    if(convertedKey == Keys.META_ALT_RIGHT_ON)
                        throw new Exception($"oops: {key}:{scancode} {convertedKey}");
                    
                    
```

![rider64_XMYuP8Qx1d](https://user-images.githubusercontent.com/18348637/63307644-693ba680-c2ef-11e9-8f79-a3fea5295bc1.png)

As you can see: ``key`` is 68 wich translate to enum: ``Keys.D`` but i get something different: ``Keys.META_ALT_RIGHT_ON``
interesting enough, it correspond to the value i get with ``scancode`` param

It doesn't happen all the time, but i can reproduce if i press the key D on my keyboard

I am using

 ```
λ dotnet --version
3.0.100-preview8-013656
```

**Comment by jkoritzinsky** [comment]
Can you post the definition of the `Keys` enum?

**Comment by RUSshy** [comment]
Here: https://gist.github.com/RUSshy/49d72797223420e31edb9ff0d070b2c0

It also contains the extension method to convert the into into the corresponding enum

**Comment by RUSshy** [comment]
I'll upload a project to reproduce issue tomorrow

**Comment by jkoritzinsky** [comment]
The `D` field and the `META_ALT_RIGHT_ON` field both have the same value of `32`. In C#, there's no distinction between the two fields. The debugger will pick one of them to represent the name (in this case it picks the first appearance of the value in the enum's members).

**Comment by RUSshy** [comment]
Ohh i didn't know that, that explains everything then, thanks a lot!!!
