### ISSUE TITLE
[release/3.0-preview9] CoreCLR build failing upload to BAR

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#26294]
It looks like this is a result of CoreCLR not naming its build manifests with a '.xml' extension, a result of this change 

Builds have been failing for quite a while (since about the 9th) but were not noticed because they rarely pass even when completing the build portion.

**Comment by mmitche** [comment]
Should be resolved with #26295

**Comment by jashook** [comment]
@mmitche any action on our part?

**Comment by mmitche** [comment]
Nope, fixed.
