### ISSUE TITLE
#ifdef checks to WRITE_0_BYTES_HANGS_TTY ignores 0 value being set to it

### ISSUE THREAD

**Issue by heinzo** [dotnet/coreclr#263]
in https://github.com/dotnet/coreclr/blob/master/src/pal/src/file/file.cpp, the '#ifdef WRITE_0_BYTES_HANGS_TTY' check ignores the value of 0 being set to the macro.

Either we modify the check to say '#if defined(WRITE_0_BYTES_HANGS_TTY) && (WRITE_0_BYTES_HANGS_TTY != 0)', or we undefing WRITE_0_BYTES_HANG_TTY in config.h.linux and config.h.osx

**Comment by kangaroo** [comment]
We should change this to #if WRITE_0_BYTES_HANG_TTY to be consistent with the rest of the PAL.  Every other variable requires a 0/1 set, so I don't see a need to deviate here.

**Comment by janvorli** [comment]
I agree

**Comment by DickvdBrink** [comment]
fixed by #526?

**Comment by heinzo** [comment]
yup. #526 fixes this
