### ISSUE TITLE
Set GCLOHCompact =CompactOnce in Environmental variable

### ISSUE THREAD

**Issue by dingsongjie** [dotnet/coreclr#26326]
In dotnet core 2.2.6
Set `GCLOHCompact =CompactOnce` in Environmental variable   equals 
`GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce` ?

If not ,Can I set  `GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce`  use  Environmental variable?

**Comment by Maoni0** [comment]
that env var is merely for testing. we never intended for it to be officially supported. 
what's it that you are trying achieve?

**Comment by dingsongjie** [comment]
I want  LargeObjectHeap Compacted  when gc.
because I My application have a lot of objs  in LOH , When gc happens they become Free but are not compressed ，This program uses a total of 1.2G memory, 800M is free in LOH .

**Comment by dingsongjie** [comment]
> that env var is merely for testing. we never intended for it to be officially supported.
> what's it that you are trying achieve?

I want LargeObjectHeap Compacted when gc.
because I My application have a lot of objs in LOH , When gc happens they become Free but are not compressed ，This program uses a total of 1.2G memory, 800M is free in LOH .

**Comment by Maoni0** [comment]
the 800mb free will be used for allocations in LOH. are you seeing it's not used or not used much?

**Comment by dingsongjie** [comment]
> the 800mb free will be used for allocations in LOH. are you seeing it's not used or not used much?
I want to make it's memory lower ,the memory grows day more than a day ,There is some program memory that grows to 10g-11g ,and throw out of memory exception

**Comment by dingsongjie** [comment]
I got a weird data yesterday. another applicaiton use 2.7G memory, I create a dumpfire ,It seems It's GC heap size was about 600M 
```log
> eeheap -gc                                                                                                                                                                                                                                    
Number of GC Heaps: 1
generation 0 starts at 0x00007F7D6D38E150
generation 1 starts at 0x00007F7D6D2AEBA0
generation 2 starts at 0x00007F7EAFFFF000
ephemeral segment allocation context: none
         segment             begin         allocated              size
00007F7EAFFFE000  00007F7EAFFFF000  00007F7EBFFFDFF0  0xfffeff0(268431344)
00007F7DC7FFE000  00007F7DC7FFF000  00007F7DD71EA358  0xf1eb358(253670232)
00007F7D6D0F8000  00007F7D6D0F9000  00007F7D6D3E6A40  0x2eda40(3070528)
Large object heap starts at 0x00007F7EBFFFF000
         segment             begin         allocated              size
00007F7EBFFFE000  00007F7EBFFFF000  00007F7EC4F3B6D8  0x4f3c6d8(83085016)
Total Size:              Size: 0x24414460 (608257120) bytes.
------------------------------
GC Heap Size:    Size: 0x24414460 (608257120) bytes.
```

**Comment by GSPP** [comment]
Is it intentional that these environment variables are available in production builds? People are going to take dependencies on any such setting that is exposed, regardless of its documentation status.

**Comment by GSPP** [comment]
Maybe it is undesirable from a compatibility standpoint that knobs are exposed which are intended for non-public use. After a few years, it is going to become very hard to alter or remove those knobs. Maybe I misunderstand and these knobs are intended to be fully supported.
