### ISSUE TITLE
TplEventSource TaskWaitSend event's field ContinueWithTaskID is always "0" since .NET Core 2.1

### ISSUE THREAD

**Issue by Temp1ar** [dotnet/coreclr#26333]
We are using these events in profiler to recreate proper stacktrace for continuations and it's become impossible since .NET Core 2.1.

Looks like there is no more ContinuationWrapper created for continuation action therefore AsyncMethodBuilderCore.TryGetContinuationTask(continuation) always returns null.

Simple steps for reproducing:
- Create .NET Core Console application targeting netcoreapp2.1
- Paste this
```csharp
internal class Program
    {
        public static void Main(string[] args)
        {
            {   // Just to make sure AsyncCausalityTracer is On
                var t = Type.GetType("System.Threading.Tasks.AsyncCausalityTracer");
                var loggingOnPropertyInfo = t.GetProperty("LoggingOn", BindingFlags.Static | BindingFlags.NonPublic);
                var value = loggingOnPropertyInfo.GetValue(t);
                Console.WriteLine("AsyncCausalityTracer.LoggingOn: " + value);
            }

            Console.WriteLine("Waiting for a key press");
//            Console.ReadKey();
            Console.WriteLine("Running async method");
            Calculate().Wait();
//            Console.ReadKey();
        }

        private static async Task Calculate()
        {
            Console.WriteLine("Start");
            await Task.Delay(5000);
            Console.WriteLine("Finish");
        }
    }
```
- Collect TPL events using PerfView
- There are two TaskWait/Send events, both with ContinueWithTaskID="0"

If you change target framework to netcoreapp2.0 then first TaskWait/Send event will have ContinueWithTaskID="2"

**Comment by jeffschwMSFT** [comment]
@tommcdon

**Comment by Temp1ar** [comment]
Is there any chance it will be fixed earlier, than 5.0? It breaks async/await support in profilers for people using .NET Core

**Comment by stephentoub** [comment]
I believe this is a dup of https://github.com/dotnet/coreclr/issues/27076 and this should already be fixed in 3.1.  Can you try out 3.1 Preview and confirm?

**Comment by Temp1ar** [comment]
Great news! I tested and it is actually working now in 3.1 Preview. Thank you very much.

**Comment by stephentoub** [comment]
Thanks for confirming.
