### ISSUE TITLE
Change number font for Farsi Culture Info

### ISSUE THREAD

**Issue by soroshsabz** [dotnet/coreclr#26330]
ITNOA

When I use below `ToString` for printing Persian date time

```csharp
DateTime.Now.ToString("f", CultureInfo.CreateSpecificCulture("fa-IR"));
```

I see something like "جمعه, 1 شهریور 1398 06:38 ب.ظ" but in another Library like [MD.PersianDateTime](https://github.com/Mds92/MD.PersianDateTime) I see something like "جمعه، ۰۱ شهریور ۱۳۹۸ ساعت ۱۸:۴۰:۰۰" the interesting part of this result is number in this string is Persian style and font ( for example `nine` in English is `9` but `nine` in Persian is `۹` ) instead of native dot net library.

I think the correct form of number in Persian is something like [MD.PersianDateTime](https://github.com/Mds92/MD.PersianDateTime) So I want to know how to change number to Persian correct form for "fa-IR" culture?

What component or class of [coreclr](https://github.com/dotnet/coreclr) is responsible for something like above?

Thanks a lot

**Comment by jkotas** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
> What component or class of coreclr is responsible for something like above?

None, choosing the right shape of the digits and the the way the string get displayed has nothing to do with .NET. The formatting APIs in .NET just produce a string with ASCII digits all the time. When it get rendered and displayed by whatever rendering engine in the OS or the APP, it will get shaped by that engine and then displayed. Usually the shaping engine uses BiDi Algorithm to decide which part of the string should be rendered as right to left text and which other parts are left to right. 

https://docs.microsoft.com/en-us/windows/win32/intl/digit-shapes

**Comment by tarekgh** [comment]
Adding some links for parts from different rendering libraries for how to control the digit substitution:

https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.numbersubstitution?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/bidirectional-features-in-wpf-overview#number-substitution
https://docs.microsoft.com/en-us/dotnet/api/system.drawing.stringformat.setdigitsubstitution?view=netframework-4.8#System_Drawing_StringFormat_SetDigitSubstitution_System_Int32_System_Drawing_StringDigitSubstitute_
