### ISSUE TITLE
Memory access violation? with tail. prefixed generic function call

### ISSUE THREAD

**Issue by acple** [dotnet/coreclr#26358]
I've tested the tailcall optimization with `tail.` prefixed functions, it causes some weired test failing, seems access violation?

This is caused only on .NET Core 3.0 SDK for macOS and for Linux (alpine:Docker). Works properly on for Windows.

Minimal repro project: https://github.com/acple/AccessViolationWithTail

---

The function is added `tail.` prefix for `ToString` by Fody add-in,

```csharp
public static string TestFunction<T>(T value)
    => value.ToString();
```

is compiled to:

```
.method public hidebysig static 
	string TestFunction<T> (
		!!T 'value'
	) cil managed 
{
	.maxstack 8

	IL_0000: ldarga.s  'value'
	IL_0002: constrained. !!T
	IL_0008: tail.
	IL_000A: callvirt  instance string [netstandard]System.Object::ToString()
	IL_000F: ret
} // end of method Class1::TestFunction
```

and call this from xUnit test method,

```csharp
[Fact]
public void CharAccessViolationTest()
{
    var input = 'a';
    Assert.Equal(input.ToString(), Class1.TestFunction(input));
}
```

is failed on macOS with strange result.

```
  X AccessViolationWithTail.UnitTest1.CharAccessViolationTest [< 1ms]
  Error Message:
   Assert.Equal() Failure
          ↓ (pos 0)
Expected: a
Actual:   羘
          ↑ (pos 0)
  Stack Trace:
     at AccessViolationWithTail.UnitTest1.CharAccessViolationTest() in /build/AccessViolationWithTail/UnitTest1.cs:line 14
```

Some types cause same problem, but some others work properly.
Please check my repro project for details.

env:
* OK:
  * Windows10 Pro 1903 + .NET Core SDK 3.0 Preview8 (3.0.100-preview8-013656)
    * `dotnet test -c Release`
* NG:
  * macOS Mojave 10.14.6 + .NET Core SDK 3.0 Preview8 (3.0.100-preview8-013656)
    * `dotnet test -c Release`
  * Docker Desktop community 2.1.0.1 (for mac) + dotnet/core/sdk:3.0.100-preview8-alpine
    * `docker build .`

**Comment by jakobbotsch** [comment]
You are not allowed to add a `tail` prefix in this case because you are passing the address of a local variable on the current stack frame in this call. Here is a more clear illegal example:
```csharp
static string Illegal()
{
  int a = 0;
  return tail ToString(ref a); // illegal
}

static string ToString(ref int a) => a.ToString();
```

It is not easy for the JIT to figure out whether any reference point to the local frame in the call and it assumes the compiler (adding the prefix) has done this analysis.

**Comment by acple** [comment]
Ah ok I see. That is clearly illegal...
But, why this works correctly with SDK on Windows? This problem is only caused with macOS or Docker. What does Windows runtime do?

**Comment by jakobbotsch** [comment]
On Windows the ABI means the caller has allocated 32 bytes of stack space even though the argument is passed in a register. The compiled code uses this space to store the argument:
```asm
; Assembly listing for method TailCallTestAssembly.Class1:TestFunction(ushort):ref
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; fully interruptible
; Final local variable assignments
;
;  V00 arg0         [V00    ] (  3,  3   )  ushort  ->  [rsp+0x08]   do-not-enreg[X] addr-exposed ld-addr-op
;# V01 OutArgs      [V01    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]   "OutgoingArgSpace"
;
; Lcl frame size = 0

G_M20841_IG01:
       894C2408             mov      dword ptr [rsp+08H], ecx
       90                   nop

G_M20841_IG02:
       488D4C2408           lea      rcx, bword ptr [rsp+08H]
       48B8D81F04AFF97F0000 mov      rax, 0x7FF9AF041FD8

G_M20841_IG03:
       48FFE0               rex.jmp  rax
```

This is still illegal if the tail-called method chooses to make use of this space, but it is less likely to cause problems than on Linux where this space does not exist.

**Comment by acple** [comment]
OK, I don't understand assembly language well, however, I got that on Windows seems to be working but still illegal.
I fixed it to don't add `tail.` for method that has any byreference parameter or is possible valuetype instance method.
I know this is too much restriction, but is a possible workaround.

Thank you for your clear answer!
And I really want an official compiler option for `tail.`ing!
