### ISSUE TITLE
Under the tier 1 flag, consider not falling back to min-opts based on high IL size

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#26419]
@BruceForstall pointed out that while R2R code for a large method may be optimized, when it is rejitted there is a heuristic that falls back to min-opts due to the large size of the method. Since tier 1 jitting is typically done in the background, it probably would be ok to spend extra time/resources to JIT the method. Probably would be good to do the same for methods flagged with AggressiveOptimization.

**Comment by sandreenko** [comment]
Right now the only obvious case where rejitting generates a worse code is when we fall back to minopts because of ILCode size, but probably we will have more cases like this in the future.
