### ISSUE TITLE
Conversion between managed uint and unmanaged C Unsigned Long

### ISSUE THREAD

**Issue by jmlidbetter** [dotnet/coreclr#26444]
## .NET Runtime Info

- .Net Core version 2.1.302
- OS: Centos 7 64bit

## Description

I have come accross a curious issue that occurs when unsigned ints are passed from C# into an external C function.

Take the following small C program:
```C
#include <stdio.h>

int FnTakingUnsignedLong(unsigned long val)
{
    printf("Recived 0x%lX\n", val);
    return(0); 
}
```
and compile it into a shared library `libtest.so`.

Then call it from C# as follows:

```C#
using System;
using System.Runtime.InteropServices;

namespace Test
{
    class Program
    {
        const string dllName = "test";

        [DllImport(dllName, CallingConvention=CallingConvention.Cdecl)]
        static extern void FnTakingUnsignedLong(uint val);

        static void Main(string[] args)
        {
            uint value = 0x7FFFFFFF;
            Console.WriteLine($"Supplying 0x{value:X}");
            FnTakingUnsignedLong(value);

            Console.WriteLine("--------");
            value += 1;
            Console.WriteLine($"Supplying 0x{value:X}");
            FnTakingUnsignedLong(value);
        }
    }
}
```

Running this code gives the following output:
```
Supplying 0x7FFFFFFF
Recived 0x7FFFFFFF
--------
Supplying 0x80000000
Recived 0xFFFFFFFF80000000
```
As can be seen when going from C# to C dotnet left pads the uint with `FFFFFFFF` implying that at the point of conversion the `0x80000000` is treated as a signed long and hence becomes `0xFFFFFFFF80000000` whereas one would expect it to be converted to `0x0000000080000000`.

Further comment: since C does not guarentee the size of unsigned long it makes sense to use uint since this is the minimum size of an unsigned long and so will avoid any overflow errors if we're running on a different architecture or non-standard C flags were used when compiling the library. FYI my use case is pythonnet so it's difficult to provide compile time guarentees of what flags were used to compile cpython (as far as I'm aware, if there's an easy way to do `sizeof(long)` for a C long please let me know!). There is a pythonnet issue for this [here](https://github.com/pythonnet/pythonnet/issues/950).

**Comment by jkotas** [comment]
The managed signature has to match the unmanaged signature. If they do not match, you may get a very surprising results as you have observed.

The most appropriate type to use for `uint` in C# is `uint32_t` in C/C++. It is guaranteed to match and  avoids problems with the size of `long` varying based on environment.

**Comment by jmlidbetter** [comment]
Ok, so I guess this falls firmly in the "undefinded behaviour" camp. The problem is made harder because I have no control of the C code being called (in fact the actual function being called can be found [here](https://github.com/python/cpython/blob/master/Objects/longobject.c#L388)). Interestingly, mono does not seem to suffer this odd behaviour when there's a size mismatch.
