### ISSUE TITLE
Proposal: Modify Object class, remove ToString, static and instance Equals, and GetHashCode methods; and the == operator

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/coreclr#26459]
These methods should never have been members of the Object class.
- ToString only makes sense for a tiny subset of types which have a string representation: primitives, enums, and few other "value types" such as DateTime. These can implement IFormattable (which they already do anyway). Absolutely no need to have it for all types. Removing it would force everybody to start using the appropriate attribute for debugger string representation.
- Equals only makes sense for comparable types, which include all of the types mentioned above, plus a couple of other categories, for example, application entity classes. Again, we already have IEquatable and IEqualityComparer - implement these if you need. Dictionary<,> starts requiring that TKey implements IEquatable, and maybe another type CustomDictionary<,> needs a IEqualityComparer<TKey>. 
- All of the above applies to GetHashCode, too. I would only add that I would split it away from Equals, in some rare cases Equals is needed but GetHashCode is not. For example, HashSet<> and Dictionary<,> need both, whereas the == operator only needs Equals. (See below) Basically, we'll have IEquatable, IHashable, and IEquatableHashable (useful for Dictionary<,> and HashSet<>).
- The == operator causes great confusion in C#. (I know this is CLR repo but bear with me for a second.) Reference equality is one the least used features ever; it also causes problems with boxed types, etc. "Content" equality (using Equals) only makes sense for those types that implement IEquatable. I think out of the box the == operator should be defined only for those types which implement IEquatable. I'm not sure though if compiler should auto-define == operator for types if IEquatable is implemented; maybe it should be defined manually, in addition to Equals.

**Comment by jkotas** [comment]
This would be a massive breaking change for the existing .NET ecosystem. There is no way a change like this would ever happen in .NET Core.

**Comment by TahirAhmadov** [comment]
I know it's massive and difficult, but incremental steps can be taken to accomplish this. As a first step, all of the new interfaces, types and methods can be added. Then, the old Equals, GetHashCode and ToString methods can be deprecated. In 2-3 major versions, it's entirely feasible to accomplish the goal. Imagine how many bugs will be prevented and how much bad code will not be written if this is done.

**Comment by Suchiman** [comment]
.net core tried to make less severe breaking changes (e.g. refactoring reflection apis, see typeinfo), and they had to backpedal on it because .net folks hate breaking changes. this change is just so much worse, e.g. it would require a redesign of basically every .net library because the string.format(string, object[]) overloads would become invalid... this just isn't absolutely **ever** going to happen

**Comment by TahirAhmadov** [comment]
@Suchiman I understand that if we suddenly dropped the string.Format(string, object[]) overload, it would create a gajillion build errors everywhere. We don't have to do that though; first, string.Format(string, IFormattable[]) is introduced, which causes most of the typical calls to bind to the new version on next build. Then the object[] overload is deprecated with a warning, etc., you get the idea.
