### ISSUE TITLE
Consider detecting and optimizing common range check patterns

### ISSUE THREAD

**Issue by VSadov** [dotnet/coreclr#26469]
It is very common to see code such as:
`(num >= '0' && num <= '9')`

The efficient way to emit such checks is: 
`(uint)(num - '0') <= ('9' '- '0')`

That often comes up in code reviews (see:https://github.com/dotnet/corefxlab/pull/1616 )

It should not be too hard to handle this kind of strength reduction in th ecompiler.

**Comment by EgorBo** [comment]
I wrote a blog-post about it in LLVM 🙂 https://egorbo.com/llvm-range-checks.html

**Comment by mikedn** [comment]
Duplicate of #12477

**Comment by BruceForstall** [comment]
Closing as dup
