### ISSUE TITLE
Could not load file or assembly ... The object already exists. (0x80071392)

### ISSUE THREAD

**Issue by hans-olav** [dotnet/coreclr#26468]
We're running .NET Core 3.0.0-preview7-27912-14 in SQL Server test infra and we're seeing a puzzling assembly load error. I've never seen this before and neither has the internet it looks like from some quick searches.

It appears to be some sort of race in the assembly loader. We've had 92 hits over the past 20 days. In the same period we ran this command ~3 million times, so a hit rate of 0.003 %.

This is the error:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The object already exists. (0x80071392)
File name: 'System.Threading.Tasks, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at Vfs.Common.CommandLine.CommandParser.ExecuteAndHandle(String programName, String[] args, ICommand[] commands)
at Vfs.Driver.Program.Main(String[] args)
```

We're going to try updating to preview8 to see if that solves it and report back, but wanted to get this logged since I didn't see a fixed bug relating to this.

Given the low occurrence rate I don't think we can expect a repro, but if there are logging/tracing we can turn on to collect info, we can do so.

**Comment by hans-olav** [comment]
FYI: We've put preview8 in prod. We'll need a couple days to gather enough data to see if the issue reoccurs.

**Comment by jeffschwMSFT** [comment]
@hans-olav I have not see this before.  If possible can you grab a dump?

**Comment by hans-olav** [comment]
Is there a simple way to make the process dump itself when this happens? Or is procdump or gflags or something the best way? By the time we see the exit code or the stdout, the process may already be gone. We're at 65K executions on preview8 now, no repro so far :-)

**Comment by jeffschwMSFT** [comment]
This appears to be running on Window and since this appears to be a crash with an unhandled exception you could configure Watson to take a dump on exit.  The dump would then be on disk and you an share.

**Comment by hans-olav** [comment]
We now have 205K executions on preview8 and it has not yet reproed. Statistically we should have seen it by now. In interest of keeping the bug list focused on real issues, I am going to close the bug for now and reopen if we get a repro and a dump.
