### ISSUE TITLE
Deadlock - managed\unmanaged code

### ISSUE THREAD

**Issue by fayilt** [dotnet/coreclr#26498]
(apologies if this is not the right place for this)
When investigating a potential deadlock I came across a windbg error:

```
0:000> !VerifyHeap
Failed to request SyncBlk at index 1806.
```

When running !SyncBlk I get this:
```
0:000> !SyncBlk
Index         SyncBlock MonitorHeld Recursion Owning Thread Info          SyncBlock Owner
SyncBlock 1806 is invalid, continuing...
SyncBlock 1812 is invalid, continuing...
-----------------------------
Total           5722
CCW             432
RCW             146
ComClassFactory 0
Free            4928

```

And locks doesn't return anything (but I know there are definitely locks:

```
0:000> !locks

Scanned 3810 critical sections
```

Can anyone tell me if this is a sign of a corrupted heap?

Thanks

**Comment by jeffschwMSFT** [comment]
cc @tommcdon

**Comment by tommcdon** [comment]
@mikem8361

**Comment by fayilt** [comment]
ok, doens't look like I'm getting any response, I'll ask a different question.

Assuming sync block is corrupted, is there any way to continue the VerifyHeap command or will it always fail on first error? Also, is there any way for me to see what sync block contains, even if it's invalid?

**Comment by mikem8361** [comment]
I don't know all the details about how use SOS especially in the corrupted heap case.  I'm including some others to see if they have any input: @Maoni0, @noahfalk.

**Comment by jkotas** [comment]
> Can anyone tell me if this is a sign of a corrupted heap?

Yes, this is a sign of corrupted heap.

> locks doesn't return anything (but I know there are definitely locks)

`locks` looks at `CRITICAL_SECTION`s only. The locks that you are aware of are likely some other kind of locks.

> is there any way to continue the VerifyHeap command or will it always fail on first error?

VerifyHeap command always fails on first error.

> Also, is there any way for me to see what sync block contains, even if it's invalid?

The syncblocks are stored in a table that `coreclr!g_pSyncTable` global variable points at. For example, here is example of how to dump syncblock 1:

```
0:009> dt coreclr!g_pSyncTable
0x000001bd`24a0fda0 
   +0x000 m_SyncBlock      : (null) 
   +0x008 m_Object         : VolatilePtr<Object,Object *>
0:009> dq 0x000001bd`24a0fda0 
000001bd`24a0fda0  00000000`00000000 baadf00d`baadf00d
000001bd`24a0fdb0  000001bd`24a70818 000001bd`26774668
000001bd`24a0fdc0  000001bd`24a70868 000001bd`26774978
000001bd`24a0fdd0  000001bd`24a708b8 000001bd`26774ab0
000001bd`24a0fde0  000001bd`24a70908 000001bd`26774f40
000001bd`24a0fdf0  00000000`00000000 baadf00d`baadf00d
000001bd`24a0fe00  00000000`00000000 baadf00d`baadf00d
000001bd`24a0fe10  00000000`00000000 baadf00d`baadf00d
0:009> !do 000001bd`26774668
Name:        Interop+Advapi32+EtwEnableCallback
MethodTable: 00007ff7cdf9eff8
EEClass:     00007ff7cdfad330
Size:        64(0x40) bytes
File:        D:\coreclr\bin\Product\Windows_NT.x64.Checked\System.Private.CoreLib.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ff7cdd00ed0  400011a        8        System.Object  0 instance 000001bd267745e0 _target
00007ff7cdd00ed0  400011b       10        System.Object  0 instance 0000000000000000 _methodBase
00007ff7cde22428  400011c       18        System.IntPtr  1 instance     7ff7cdd5fc30 _methodPtr
00007ff7cde22428  400011d       20        System.IntPtr  1 instance                0 _methodPtrAux
00007ff7cdd00ed0  40001ac       28        System.Object  0 instance 0000000000000000 _invocationList
00007ff7cde22428  40001ad       30        System.IntPtr  1 instance                0 _invocationCount
0:009> dt coreclr!SyncBlock 000001bd`24a70818
   +0x000 m_Monitor        : AwareLock
   +0x030 m_pInteropInfo   : 0x000001bd`24a80140 InteropSyncBlockInfo
   +0x038 m_pEnCInfo       : (null) 
   +0x040 m_Link           : SLink
   +0x048 m_dwHashCode     : 0
   +0x04c m_BSTRTrailByte  : 0 ''
```

**Comment by fayilt** [comment]
Thanks very much Jan, this is extremely useful! We're observing the same issue in both core and .net framework versions of the service. Can you please let me know what the command will look like for the .net framework dump?

dt coreclr!g_pSyncTable

**Comment by jkotas** [comment]
>  Can you please let me know what the command will look like for the .net framework dump?

`dt clr!g_pSyncTable`

**Comment by fayilt** [comment]
@jkotas 

I'm not able to run this command for some reason:
```
0:000> dt clr!g_pSyncTable
Symbol clr!g_pSyncTable not found.
```
I've got most of the symbol files loaded, but it did complain about ni files (System.ni, System.Core.ni etc), which is the ngen optimized version of the assemblies? Do I need them as well in order to be able to see g_pSyncTable?

**Comment by jkotas** [comment]
The publicly accessible symbols for .NET Framework have stripped implementation details. It is the standard policy for all Microsoft closed source products. `dt` does not work with the stripped symbols. To workaround it, you can use direct pointer arithmetic, e.g.: 

```
0:000> ? poi(clr!g_pSyncTable)
Evaluate expression: 1430983352976 = 0000014d`2d412290
0:000> dq 0000014d`2d412290
0000014d`2d412290  00000000`00000000 baadf00d`baadf00d
0000014d`2d4122a0  0000014d`2d47bfd8 0000014d`2f2b5970 <- sync block 1
0000014d`2d4122b0  baadf00d`baadf00d baadf00d`baadf00d <- sync block 2
0000014d`2d4122c0  baadf00d`baadf00d baadf00d`baadf00d ...
0000014d`2d4122d0  baadf00d`baadf00d baadf00d`baadf00d
0000014d`2d4122e0  baadf00d`baadf00d baadf00d`baadf00d
0000014d`2d4122f0  baadf00d`baadf00d baadf00d`baadf00d
0000014d`2d412300  baadf00d`baadf00d baadf00d`baadf00d
```
