### ISSUE TITLE
runtime get crashed when allocate a large string 

### ISSUE THREAD

**Issue by DionYe** [dotnet/coreclr#2650]
In src/mscorlib/src/System/StubHelpers.cs code line 175:

ptrToFirstChar = (byte *)Win32Native.SysAllocStringByteLen(null, lengthInBytes).ToPointer();

it seems we should check whether ptrToFirstChar is NULL.  we get runtime crashed when we run a stress test and find runtime get crashed at this code line

**Comment by tzwlai** [comment]
@yizhang82, PTAL

**Comment by yizhang82** [comment]
@DionYe Thanks for catching this issue and you are right that this is a bug. The fix should be as simple as adding a NULL check and throw OutOfMemoryException. Feel free to submit a PR.

**Comment by yizhang82** [comment]
Thanks @DionYe and @jkotas!
