### ISSUE TITLE
[Bug] Portable Class Library compilation gets broken when a target is _removed_

### ISSUE THREAD

**Issue by dsaf** [dotnet/coreclr#2651]
Steps to reproduce:

1) Create a new PCL project targeting .NET 4.5, Win 8 and SL 5 (Profile47)
2) Change ```Class1.cs``` to following code (notice it compiles):
```csharp
    public class Class1
    {
        private void Test()
        {
            IConvertible test;
        }
    }
```
3) Disable SL 5 target in project settings, notice a message *"The following will be automatically targeted because they support the same set of portable APIs: ASP.NET Core 5.0"*. Project changes to Profile7

4) Compilation is now broken: *"CS0246 The type or namespace name 'IConvertible' could not be found (are you missing a using directive or an assembly reference?)"*

The code could be relying on value types inheriting ```IConvertible``` as well, so it needs the interface. There are likely to be other similar breaking changes around Reflection APIs.

Effectively there seems to be a bug in some piece of code that tells that a set of portable APIs is common when in fact it is not. I don't know where it is: in PCL profile configuration, Visual Studio or .NET Framework.

Removing a target should not be a breaking change.

**Comment by tzwlai** [comment]
@dsaf, I have moved this to the CoreFX repo: https://github.com/dotnet/corefx/issues/5422
