### ISSUE TITLE
Object.ToString() returns hex E28892 instead of D2 for minus signs on Linux

### ISSUE THREAD

**Issue by SWarnberg** [dotnet/coreclr#26538]
# Issue Title

Invalid unicode character is returned by Object.ToString() when running on Linux for minus.

# General

When using Object.ToString() on an object of type Int16, Int32 etc, with a negative value, for instance -32, the return value is "-32". However, this method behaves differently on Windows and Linux, which causes problems when forwarding this string to another environment, for instance SQL Server.

- On Windows, the minus sign is of hex code 2D (Hyphen minus), see https://www.fileformat.info/info/unicode/char/2d/index.htm.
- On Linux, the minus sign is of hex code E28892, see https://www.fileformat.info/info/unicode/char/2212/index.htm.

This causes problems, for instance when passing a SQL statement to another machine (on Windows) in SQL Server. E28892 is not considered as a negative number in SQL Server. When following is executed:
`
EXEC sp_myproc @mydata = -32
`
then the following error message is returned:

`Incorrect syntax near '−'.`

**Comment by stephentoub** [comment]
> Also, shouldn't ToString() give the exact result, irrespective of locale, for minus signs?

No, it uses https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.negativesign, which is defined by the culture.  If you want to use invariant formatting, you can pass CultureInfo.InvariantCulture to number.ToString.

**Comment by tarekgh** [comment]
We are using the underlying OS to get the cultures data. It is expected can find some differences between the OS's data. you shouldn't make hard dependency on the culture data as the data can change at any time. As @stephentoub mentioned, if you want to guarantee consistent formatting and parsing, you'll need to use Invariant culture for that. or you can create your own NumberFormatInfo and override the negative sign and pass this object to ToString(). 

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.negativesign?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.int32.tostring?view=netframework-4.8#System_Int32_ToString_System_IFormatProvider_

**Comment by tarekgh** [comment]
To add more info for this specific case: 

CLDR data is using 0x2212 for the negative sign. Windows is converting this sign to regular hyphen. I am following up with Windows team why they are doing that.
https://st.unicode.org/cldr-apps/v#/sv/Symbols/2f08b5ebf85e1e8b

https://unicode.org/cldr/trac/ticket/9851
https://unicode.org/cldr/trac/ticket/10779

**Comment by SWarnberg** [comment]
Well, as my first comment in this thread; if Windows would change it's behaviour and return 2212, they would need to support it in SQL Server as well.

**Comment by SWarnberg** [comment]
> We are using the underlying OS to get the cultures data. It is expected can find some differences between the OS's data. you shouldn't make hard dependency on the culture data as the data can change at any time. As @stephentoub mentioned, if you want to guarantee consistent formatting and parsing, you'll need to use Invariant culture for that. or you can create your own NumberFormatInfo and override the negative sign and pass this object to ToString().
> https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.negativesign?view=netframework-4.8
> https://docs.microsoft.com/en-us/dotnet/api/system.int32.tostring?view=netframework-4.8#System_Int32_ToString_System_IFormatProvider_

Problem is that we're using Object.ToString(), which doesn't have formatting options, since we don't know the datatype. We can of course try to convert it.

**Comment by stephentoub** [comment]
> Problem is that we're using Object.ToString(), which doesn't have formatting options, since we don't know the datatype. We can of course try to convert it.

You can use `Convert.ToString(yourObject, CultureInfo.InvariantCulture)`, which just does the relevant checks for you.
