### ISSUE TITLE
Is Activator.CreateInstance(Type) able to return null?

### ISSUE THREAD

**Issue by sharwell** [dotnet/coreclr#26539]
The method is declared as returning `object?`, but my understanding was the implementation would either throw an exception or return a non-null instance.

https://github.com/dotnet/coreclr/blob/f821e2ac58f096bf5c5a830064345c5b16f1db27/src/System.Private.CoreLib/shared/System/Activator.cs#L36

**Comment by stephentoub** [comment]
Yes, e.g.
```C#
Activator.CreateInstance(typeof(int?))
```
