### ISSUE TITLE
make CI test results available via jenkins

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#2653]
The LLILC CI tests have a [link to test results](http://dotnet-ci.cloudapp.net/job/dotnet_llilc_release_win64/lastCompletedBuild/testReport) including useful stuff like how long the test took and sorting. If this exists in CoreCLR I can't easily find it...

**Comment by tzwlai** [comment]
@markwilkie and @Chrisboh, whom should this go to?

**Comment by markwilkie** [comment]
@gkhanna79 Adding Gaurav who has more info on which CoreCLR tests are being run in Jenkins.

**Comment by gkhanna79** [comment]
@AndyAyersMS Please work with @ramarag who implemented the CoreCLR repo test infrastructure for this. Here is the link to similar CoreCLR repo test report:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_windows_nt_prtest/2996/testReport/

**Comment by AndyAyersMS** [comment]
Results seem to be there now for many test CI legs, so let's hold off on this unless I run into one again that is missing test results.
