### ISSUE TITLE
AssemblyLoadContext Unload does not release assembly lock on Windows

### ISSUE THREAD

**Issue by uffebjorklund** [dotnet/coreclr#26566]
This is a question about how things are supposed to work, but if my suspicion is right I will file a sample project where I reproduce the issue I am experiencing.

## Background

I have a project that downloads zip files with assemblies. These assemblies are then loaded into a custom assembly load context. Later on the ALC will be unloaded and then the Unloading event fires (and all assemblies loaded will be unloaded).

I see no increase in memory when repeating this scenario so I guess that the assemblies are unloaded. A weird thing (not important here) is that the global tool `dotnet-counters` never decrease the number of assemblies loaded. The count increases for every time I create a new ALC, I thought that unloading would make the count decrease.

## The Issue

When the Unloading of a ALC is completed my assumption was that the assemblies would be released/unlocked on windows so that I actually can remove them form the file system. However, this is not the case.
If assemblies can be unloaded it would make sense to also let us delete the plugins since we might update the plugins later on and on windows we get exceptions since we cant delete the locked assemblies loaded by the ALC even though the ALC is long gone and the assemblies unloaded from dotnet core.

The be more specific the assemblies are written to a shared docker volume, since we want to persist these assemblies between if the container restarts.

## Workaround

I have solved this temporary by only storing a zip with the actual assemblies in the shared volume, and then I load the assemblies inside the container so that windows cant lock them.
However, this will probably not work when we later on will use windows containers since my guess is that they will be locked inside the container by windows then.

## Environment

Host: Win10 Enterprise 1903
Docker Desktop
Base Image: mcr.microsoft.com/dotnet/core/runtime-deps:3.0-alpine
Application: dotnet core 3 preview9 

The issue only occurs when running containers on windows (Mac/Linux works just fine).

**Comment by uffebjorklund** [comment]
Im starting to think that this might be something within our application. Will try to reproduce in a simple example. I added WeakReference and it stays alive for ever in our application, so I guess we have some reference to the ALC that we to not dispose of in a correct way.

Will update this issue and hopefully close it if I get a simple example to work as expected.

**Comment by janvorli** [comment]
@uffebjorklund you should be able to delete the assemblies if the unload succeeded, so it seems there is really some issue blocking the unloading. The following article I have written in the past may help you to debug your issue: https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability-howto

**Comment by uffebjorklund** [comment]
@janvorli thanks!
I found that article this weekend, it made me think that we have another issue. My guess is that we have to change the way we use the ALC. Today we have a few services injected into our custom ALC. Guessing that we cant do it that way since all examples I can find showing unloading use ALC in a more isolated way than we do.

**Comment by uffebjorklund** [comment]
Managed to create a simpler ALC and successfully unloaded assemblies. Did not try it on windows yet, but I saw that the number of loaded assemblies decreased in dotnet-counters.

Will close this and hopefully get everything working on windows as well.
