### ISSUE TITLE
Wrong comhost.dll used by build

### ISSUE THREAD

**Issue by weltkante** [dotnet/coreclr#26578]
I'm building with todays nightly (5.0.100-alpha1-014083) to get progids registered (#25966). This works on a fresh VS 2019 preview install, but not on my dev machine which has a history of various older previews being installed. Both building inside VS and with `dotnet build` fail to produce a comhost which supports progids (they are in the clsidmap resource but don't get registered)

I did a full repair install of VS 2019 preview, followed by a repair install of the nightly installer. Attached is a [binlog](https://github.com/dotnet/coreclr/files/3586622/msbuild.binlog.zip) showing that it still picks up the comhost.dll from the wrong location.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Can you validate the correct `comhost.dll` is being used?

**Comment by jkoritzinsky** [comment]
I believe this is an SDK issue where the .NET Core 5.0 SDK bits are resolving the netcoreapp3.0 TFM to the 3.0.0 Preview 7 App Host pack. Looking at the binlog, it resolves the app-host to the same folder.

**Comment by jkoritzinsky** [comment]
Opened an issue on the SDK repo. I'm closing this issue in favor of that one: https://github.com/dotnet/sdk/issues/3614
