### ISSUE TITLE
Question: COR_PRF_SUSPEND_REASON when requested by profiler

### ISSUE THREAD

**Issue by k15tfu** [dotnet/coreclr#26576]
Is there a plan to add a new value in `COR_PRF_SUSPEND_REASON` for the case when RuntimeSuspendStarted() is called right after `ICorProfilerInfo10::SuspendRuntime()`? Something like `COR_PRF_SUSPEND_FOR_PROFILER` I guess.

cc @davmason

**Comment by davmason** [comment]
Yes, this was an oversight as part of the 3.0 work. I plan to add it for 5.0.

**Comment by k15tfu** [comment]
@davmason I prepared a PR for this issue, and also hope it will be included in 3.1. I think this is really important for ICorProfilerInfo10::SuspendRuntime()-based sampling profiler to distinguish the reason why the runtime was suspended, because it can just ignore all callbacks with COR_PRF_SUSPEND_FOR_PROFILER reason.

**Comment by k15tfu** [comment]
Hi! @davmason. Glad to hear you thought about this issue too =)

The fix for this looked pretty simple, like adding a few lines of code, so I decided that I could try to do it myself. Here is PR: https://github.com/dotnet/coreclr/pull/27041

I think it is very important for ICorProfilerInfo10::SuspendRuntime()-based sampling profiler to distinguish the reason why the runtime was suspended, because it can just ignore all callbacks with COR_PRF_SUSPEND_FOR_PROFILER reason. Can we include this fix in 3.1?
