### ISSUE TITLE
HashCode.Combine perf is worse than HashHelpers.Combine

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#26582]
We made the public HashCode.Combine method so that developers would use it any time combining is necessary in their own hash code computations.  But we use it internally in very few of our own GetHashCode methods, instead preferring to use either the internal HashHelpers.Combine:
https://github.com/dotnet/coreclr/blob/456afea9fbe721e57986a21eb3b4bb1c9c7e4c56/src/System.Private.CoreLib/shared/System/Numerics/Hashing/HashHelpers.cs#L11-L17
or using a custom combine that's generally something as simple as an xor.  HashCode.Combine is 3-4x slower than HashHelpers.Combine in today use, e.g. if used in ValueTuple.GetHashCode.

We should either determine that the extra benefits of HashCode.Combine are "worth it" and use it everywhere instead of HashHelpers.Combine, or we should fix HashCode.Combine's perf (likely at the expense of those "benefits") so that it becomes usable.  At the moment if we're not comfortable using it ourselves, it's unclear how we could promote it for others to use.

**Comment by jkotas** [comment]
The trade-offs were discussed in depth in https://github.com/dotnet/corefx/issues/14354 . 

Related: #15508 and https://github.com/dotnet/corefx/issues/25986

**Comment by stephentoub** [comment]
@jkotas, thanks. I've read that thread, but we're using it in very few places internally.  We're only using it today in {ReadOnly}Memory, Range, Vector64/128/256, and in ~6 places in corefx, most of which appear to be due to it sneaking in during "cleanup" PRs.

In contrast we have 85 call sites in Corelib to HashHelpers.Combine in ArraySegment, ValueTuple`1 through ValueTuple`8, and Vector (which is where most of the call sites are), and another 42 in corefx. There are also dozens upon dozens of types that do their own combining, generally via xor.

Should all of these be updated to use HashCode.Combine?  I hope the answer is "yes".  If it's not, how are our customers going to decide when they shouldn't use it either?

**Comment by jkotas** [comment]
> Should all of these be updated to use HashCode.Combine

Yes, that was the plan. We even had PRs opened in coreclr and corefx to do it, but they were abandoned.

**Comment by EgorBo** [comment]
it looks like some of the HashCode.Combine methods can be improved a bit (vectorized), e.g this piece https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/HashCode.cs#L136-L139 (avx512)

**Comment by danmosemsft** [comment]
@EgorBo maybe worth opening an issue for that.

**Comment by EgorBo** [comment]
@danmosemsft I am afraid the vectorization of those methods indeed require AVX512 coreclr doesn't support (to make 4 rol at once - we can use SSE/AVX to vectorize "software" fallback of RotateLeft but last time I tried it it was slower than the current impl.
