### ISSUE TITLE
JIT doesn't fold x * c / c constants

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#26636]
C#:
```csharp
public static int TestAddSub(int x)
{
    return x + 3 - 3; // return x;
}

public static int TestMulDiv(int x)
{
    return x * 3 / 3; // return x;
}
```
IL
```c++
// TestAddSub
        IL_0000: ldarg.0
        IL_0001: ldc.i4.3
        IL_0002: add
        IL_0003: ldc.i4.3
        IL_0004: sub
        IL_0005: ret


// TestMulDiv
        IL_0000: ldarg.0
        IL_0001: ldc.i4.3
        IL_0002: mul
        IL_0003: ldc.i4.3
        IL_0004: div
        IL_0005: ret
```
Codegen:
```asm
; TestAddSub(int):int
       mov      eax, ecx
       ret      
; Total bytes of code: 3


; TestMulDiv(int):int
       lea      edx, [rcx+2*rcx]
       mov      ecx, 0xD1FFAB1E
       mov      eax, ecx
       imul     edx:eax, edx
       mov      eax, edx
       mov      edx, eax
       shr      edx, 31
       add      eax, edx
       ret      
; Total bytes of code: 22
```
So the JIT is able to fold `+ 3 - 3` into `0` but can't do it for `* 3 / 3` pair.
Here is where `+3 - 3` folding is implemented: https://github.com/dotnet/coreclr/blob/master/src/jit/morph.cpp#L12865-L12869
(GT_DIV/GT_MUL nodes nearby don't have similar logic)

**Comment by jakobbotsch** [comment]
I don't think this is a valid transformation due to overflow. For example:
`715827883 * 3 / 3 = -715827882`

**Comment by EgorBo** [comment]
@jakobbotsch so `int.MaxValue + 3 - 3` should not work as well, right? ;-)

**Comment by jakobbotsch** [comment]
Since overflow on addition is defined to wrap around that transformation is actually ok.

**Comment by EgorBo** [comment]
Yeah I understand, was just wondering if it's possible to align this behavior with other programming languages (which usually fold such constants)

**Comment by jakobbotsch** [comment]
The spec here says that the upper bits are truncated on overflow so I don't think there is much that can be done.

**Comment by EgorBo** [comment]
@jakobbotsch makes sense, thanks!
