### ISSUE TITLE
ArrayWithOffset marshalling and asynchronous interop call

### ISSUE THREAD

**Issue by AlexandreBossard** [dotnet/coreclr#26658]
I have this native C library asynchronous function:
```C
future_t *stream_read(stream_t * stream, uint8_t* buffer, int64_t buffer_size)
```
This function takes an opaque object `stream` and fills the buffer with at most `buffer_size` bytes.
The read byte count is returned through a future when the read is complete.

At first I bound the function like so:
```C#
[DllImport(@"mylib")]
internal static extern IntPtr stream_read(IntPtr stream, [Out] byte[] buffer, Int64 buffer_size)
```
This works. But while encapsulating this function (and others) with a System.IO.Stream, I ran through ReadAsync():
```C#
class MyStream : System.IO.Stream
{
// ....
public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
{
   GCHandle bufferHandle;
   try
   {
       bufferHandle = GCHandle.Alloc(buffer, GCHandleType.Pinned);
       var intPtr = await Future.GetTask(MyLib.stream_read(this.MyStream, buffer, count));
       return intPtr.ToInt32();
   }
   finally
   {
       bufferHandle.Free();
   }
}
}
```

I don't know how to handle the `offset` parameter. `unsafe` context is not allowed in async function and a `fixed` scope won't cut it anyway since the pointer needs to be pinned until the future/task completes.

Then I came across [`Interop.ArrayWithOffset`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.arraywithoffset?view=netcore-2.2) which looked exactly like what I wanted.
I replaced the `[Out] byte[] buffer` parameter by `[In, Out] ArrayWithOffset buffer` but sadly my buffer is never filled. I suspect the array is not blitted and the buffer is copied back to the caller too early.

Is there a way to do this without resorting to a temporary buffer and a copy back to the readAsync() parameter? How can I get a blittable pointer from a `byte[]` in an async context?

**Comment by jkotas** [comment]
The best way to do this is to split the function into two: The async entrypoint and non-async helper method that has all the unsafe arithmetic.

**Comment by AlexandreBossard** [comment]
I've tried that, but all the unsafe headaches asides, they are but an hindrance. The problem is that the C function is asynchronous and fill the passed output buffer after the call returned, when the future/task completes. My problem is how to get an offsetted `byte[]` blittable pointer, and how to pin it. GCHandle.Alloc(buffer, Pinned) works usually.

**Comment by jkotas** [comment]
Try this:

```
[DllImport(@"mylib")]
internal static extern IntPtr stream_read(IntPtr stream, IntPtr buffer, Int64 buffer_size)
```

```
class MyStream : System.IO.Stream
{
// ....
public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
{
   GCHandle bufferHandle;
   try
   {
       bufferHandle = GCHandle.Alloc(buffer, GCHandleType.Pinned);
       var intPtr = await Future.GetTask(MyLib.stream_read(this.MyStream, bufferHandle.AddrOfPinnedObject() + offset, count));
       return intPtr.ToInt32();
   }
   finally
   {
       bufferHandle.Free();
   }
}
}
```

**Comment by jkotas** [comment]
For arrays, `AddrOfPinnedObject` returns the pointer to first element.

**Comment by AlexandreBossard** [comment]
That's Great! I would have loved to read that somewhere in the doc!

**Comment by jkotas** [comment]
I have submitted https://github.com/dotnet/dotnet-api-docs/pull/3169 to update the docs. Please take a look.
