### ISSUE TITLE
Issue with AsyncLocal execution context when used within a Middleware with dependency injection

### ISSUE THREAD

**Issue by passuied** [dotnet/coreclr#26713]
Hi,

We ran into an interesting scenario in one of our middlewares.
We rely on AsyncLocal to expose context data within our application using the ContextAccessor pattern (similar to HttpContextAccessor). 

The middleware is capturing information within the request headers and updating the values in the AsyncLocal instance. 
The middleware uses dependency injection to resolve the context accessor (that wraps AsyncLocal) and also a Logger object (ILog).

When we added some logic in the DI registration of ILog to resolve an object that has itself a dependency to the Context accessor, it created an abnormal behavior where the values set the AsyncLocal in a request would be kept across subsequent requests!
Beyond the fact that the logic was flawed, as we resolve the context before the middleware ran and set the values, I can't wrap my head around why the values are persisted in AsyncLocal...

I realize this might be complicated to understand all these details so I have recreated the issue in the following repo: https://github.com/passuied/TestAsyncLocalMiddleware

You can find details in README about how to reproduce the issue...

Hope it makes sense!

**Comment by passuied** [comment]
An update to the issue above.
I have added more details in the README of the repo provided.
I have also identified this behavior doesn't occur when running the service using `Microsoft.AspNetCore.TestHost.TestServer` or using IISExpress...

Could it be a bug in Kestrel?

**Comment by davidfowl** [comment]
@jkotas can you close this issue? It's an ASP.NET problem.

**Comment by passuied** [comment]
@davidfowl is it a known issue? Or you're just saying this because of my comment above?

**Comment by davidfowl** [comment]
I looked at the problem and it's not a clr issue.
