### ISSUE TITLE
CoreCLR silently ignores exceptions from DangerousRelease in marshalling

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#26730]
From https://github.com/mono/mono/issues/16859#issue-494056862:

CoreCLR silently ignores exceptions from DangerousRelease in marshalling https://github.com/dotnet/coreclr/blob/7adc7249f71679b6a1727e17cd15df4db5d621b3/src/System.Private.CoreLib/src/System/StubHelpers.cs#L1646-L1652

It seems it could hide legitimate bugs or race condition

**Comment by AaronRobinsonMSFT** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/26732
