### ISSUE TITLE
[CI] Git checkout sometimes fails unable to find the PR merge commit

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#26733]
Seems like somehow the checkout sometimes is shallow depth=1, which may not have the correct merge commit. @trylek 

https://dev.azure.com/dnceng/public/_build/results?buildId=355295

**Comment by trylek** [comment]
Indeed, I think that's what Egor advised me to use in the first place:

https://github.com/dotnet/coreclr/blob/afd8b1f80a90a37d6b73987cbf9fdf03e8945250/eng/checkout-job.yml#L53

I can easily remove this clause if it causes issues.

**Comment by jashook** [comment]
We should probably put the fetch depth to 5 or 10, it should avoid these issues hopefully most of the time.

**Comment by stephentoub** [comment]
cc: @danmosemsft, @mmitche, @jaredpar

**Comment by mmitche** [comment]
I think the default in AzDO might actually be 5 (for PRs)

**Comment by jashook** [comment]
I was under the impression there was a minimum of 5, but that may have only been enforced on the ui. The default checkout depth for anything on azure seemed unbounded. @jaredpar should have more info on that.

**Comment by jaredpar** [comment]
The AzDO Documentation for shallow fetch explicitly calls out this scenario as a possibility. See the Note at the end of this section:

> https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops#shallow-fetch

For this reason Roslyn set our shallow fetch depth at 5, not 1. So far we haven't seen any issues.

**Comment by jaredpar** [comment]
For transparency I wanted to say we chose a fetch depth of 5 not because of any hard reasoning. Instead we read that article, decided we needed a number higher than 1 and 10 sounded too high so we picked 5 because it was in the middle.

If anyone reading this has a better way to reason about this number I'm excited to hear about it :smile:

**Comment by danmosemsft** [comment]
Just curious, given the "depth" back to the first commit is "thousands", intuitively I would expect 1, 5 or 10 to pull much the same number of blobs?

**Comment by jaredpar** [comment]
Correct. 

One thing to remember though is that for a CI job Azure is not just fetching the branch you're building against. Rather it's fetching for every branch and tag in the remote repository. That means you're pulling `fetchDepth` commits from every branch + tag.
