### ISSUE TITLE
Consider removing IsFastSort optimizations from String

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/coreclr#26758]
We might not actually need these optimizations in practice, and removing them would allow to simplify the code. See also https://github.com/dotnet/coreclr/pull/24400 and https://github.com/dotnet/coreclr/issues/19672#issuecomment-415974153.

**Comment by GrabYourPitchforks** [comment]
Related: https://github.com/dotnet/coreclr/pull/10632

/cc @tarekgh

**Comment by adamsitnik** [comment]
> We might not actually need these optimizations in practice, and removing them would allow to simplify the code
