### ISSUE TITLE
Redundant `xor eax eax` in Bmi1.TrailingZeroCount ?

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#26775]
I was implement Bmi1/Bmi2 intrinsics in mono and noticed that coreclr emits `xor eax, eax`  for this case, is it needed here? without it `tzcnt    eax, ecx` still returns correct values for 0/MaxValue  on my PC (llvm doesn't emit it for @llvm.cttz.i32, also see [godbolt](https://godbolt.org/z/zqy9Ac)).
```csharp
[MethodImpl(MethodImplOptions.AggressiveOptimization)]
static uint TrailingZeroCount(uint a) => Bmi1.TrailingZeroCount(a);
```
Codegen:
```asm
; Method FFF:TrailingZeroCount(int):int
G_M46836_IG01:
G_M46836_IG02:
       xor      eax, eax
       tzcnt    eax, ecx
G_M46836_IG03:
       ret      
; Total bytes of code: 7
```
Same for `LeadingZeroCount`
Also, noticed a suboptimal codegen for `Bmi1.BitFieldExtract` but there is already an issue for it: https://github.com/dotnet/coreclr/issues/25907

**Comment by mikedn** [comment]
See #19555

**Comment by EgorBo** [comment]
@mikedn ouch, good to know! thanks

**Comment by EgorBo** [comment]
hm.. llvm doesn't emit it even for the problematic haswell (unlike gcc): https://godbolt.org/z/NXhlrn
