### ISSUE TITLE
The burgers performance test fails non-deterministically

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#2679]
A number of CI runs are seeing failures in the `jit\Performance\CodeQuality\Burgers` test, failing in `GetCalculated3` which exercises SIMD code. The failures are non-deterministic and I haven't been able to reproduce them locally. The failures are mostly in release and mostly seen on dci-win-bld-5, but there has been at least one failure in debug and a few on other build machines.

The failure is an array out of bounds access
```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Burgers.GetCalculated3(Int32 nt, Int32 nx, Double dx, Double dt, Double nu, Double[] initial)
at Burgers.Main()
```
The [code that fails](https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/Performance/CodeQuality/Burgers/Burgers.cs#L130-L166) doesn't do any conditional array dereferences, so the non-determinism here is a puzzler.

**Comment by RussKeldorph** [comment]
@AndyAyersMS @CarolEidt 
This is 100% repro on my only AVX2 machine.  0% repro on said machine with COMPlus_EnableAVX=0 set.

**Comment by AndyAyersMS** [comment]
Ah, good. Guess that means some but not all lab HW has AVX2?

Since you can repro, can you test a fix?

Change line 142 to:
```C#
            for (int i = 1; i < nx2 - Vector<double>.Count + 1; i += Vector<double>.Count)
```

**Comment by CarolEidt** [comment]
@RussKeldorph - let me know if you are not able to test this, and I can do it. I looked at this and didn't think it would be the issue, because nx2 has been assured to be a multiple of Vector<double>.Count - but I hadn't internalized that because the loop starts at 1, the loop itself isn't "aligned". I was able to determine that it is the first constructor that fails on the upper bound.

**Comment by RussKeldorph** [comment]
@AndyAyersMS @CarolEidt Confirmed no more crash post Andy's change.
