### ISSUE TITLE
Dotnet processes are too numerous to differentiate between specific applications

### ISSUE THREAD

**Issue by stuyun** [dotnet/coreclr#26811]
dotnet.exe App1.dll
dotnet.exe App2.dll
dotnet.exe App3.dll
dotnet.exe App4.dll

Process names are all dotnet and can't distinguish between specific applications

**Comment by benaadams** [comment]
In 3.0 building now also creates and exe; and the process names should be the created .exe name even when you use `dotnet run` (though you will also have a process which is .NET Core Host `dotnet run`; which doesn't exist if you run the built exe)

**Comment by benaadams** [comment]
e.g. with 3.0 it would now be

App1.exe
App2.exe
App3.exe
App4.exe

**Comment by jkotas** [comment]
As @benaadams said.
