### ISSUE TITLE
Every method is JIT'ted twice in x64?

### ISSUE THREAD

**Issue by MulleDK19** [dotnet/coreclr#26831]
Don't know if a bug, or some obscure feature, but it applies to both .NET Core 2.0 and .NET Framework all the way back to 2.0.

In x86, the first call to a method invokes a JIT stub through a function point. The stub compiles the method and replaces the function pointer with the address of the compiled code, then redirects to the compiled code. Any subsequent calls will jump directly to the already compiled code.

I was debugging a x64 process, and was expecting the same behavior. But to my surprise, the JIT stub was called on the second call too. It eventually calls the initially compiled code, but it runs through hundreds of instructions before getting there. On the third call to a method, the JIT stub has been replaced by a direct jump to the compiled code.

This happens with every method. First and second call of every method invokes the JIT compiler stub, any subsequent calls jump to the compiled code directly.

Is this a bug no one has noticed, or just some undocumented feature of the x64 JIT'ter? Haven't been able to find anything about it anyway. I tried patching the stub to jump to the compiled method after the first JIT, and it didn't seem to have any side effects for subsequent calls.

**Comment by Joe4evr** [comment]
This is likely the [Tiered JIT](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/tiered-compilation.md) at work.

**Comment by jkotas** [comment]
Invoking the JIT compiler stub second time does not actually cause the method to be JITed second time. The system will quickly find that the method was JITed already and it will just use the existing JITed code.

The general design principle of .NET engine is to be lazy: do the work only once it is clear that it is worth doing it. Majority of methods in typical program execution are called exactly once. It means that patching the stub eagerly is wasted effort for most methods. It explains what we chose to implement it this way.

The trade-offs and the implementation are different between x86 and all other platforms for historic reasons. It is explains the difference between x86 and x64 that you are seeing.
