### ISSUE TITLE
Comparing types for equality may fail while guid are equals.

### ISSUE THREAD

**Issue by mgth** [dotnet/coreclr#26838]
.Net Core 3.0 RC1
Sometimes 

typeA != typeB
althrought 
typeA.GUID == typeB.GUID

In my case types ares the same, and it worked in dot net framework.
One type is obtained by reflection for a property type.
The other is obtained by reflexion on the class itself.

**Comment by jkotas** [comment]
> One type is obtained by reflection for a property type.
> The other is obtained by reflexion on the class itself.

You are likely loading the same type twice.

**Comment by mgth** [comment]
Unfortunately I tried many ways to reproduce in a smaller environnement but could not.
It is well possible that the type get loaded twice because I load assemblies by hand. I did not know it could happened.
The exact same code works well in .Net framework

**Comment by mgth** [comment]
Just double checked an I realize that a dll was loaded twice, so it's ok now.
