### ISSUE TITLE
ValueType.Equals doesn't use bit comparsion

### ISSUE THREAD

**Issue by Melchy** [dotnet/coreclr#26833]
ValueType.Equals() defined [here](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/ValueType.cs) should compare bits of objects if the compared type doesn't contain any reference type. But it seems that it always uses reflection to check equality. (Corect behavior is described [here](https://docs.microsoft.com/dotnet/api/system.valuetype.equals).)

For example folowing code prints True:

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        TestStruct f, s;
        f.variable = 0.0f;
        s.variable = -0.0f;
	
        Console.WriteLine(f.Equals(s)); //True -> binary check was not used
    }
}

public struct TestStruct
{
    public float variable;
}
 ```

This is probably bug because same code on .Net 4.7.2 prints False. If this is intended feature than there should not be line 42 and 43 in file [ValueType.cs](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/ValueType.cs)

**Comment by EgorBo** [comment]
It's intentional, see https://github.com/dotnet/coreclr/pull/13164

**Comment by jkotas** [comment]
The documentation needs updating

**Comment by tannergooding** [comment]
Right, it isn't safe to assume that bitwise equality is valid for any two arbitrary structs.

There may be cases where two structs with different bitwise values are considered equal and even some cases (like floating-point NaN) where two bitwise equal values should be considered inequal.

The only safe thing for `System.ValueType` to do is invoke the appropriate `.Equals` method for each field.
