### ISSUE TITLE
Directory.GetCurrentDirectory inconsistency between Windows and Mac

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/coreclr#26844]
Original issue: https://github.com/aspnet/AspNetCore-ManualTests/issues/22

**Repro steps:**
- mkdir consoleapp
- cd consoleapp
- `dotnet new console`
- Edit `Program.cs` to output `Directory.GetCurrentDirectory()`
- `dotnet publish -c release`
- Open the folder in Finder `/bin/release/netcoreapp3.0/publish`
- Double click `webapp`

Expected output:

`/Users/username/Github/temp/webapp/bin/release/netcoreapp3.0/publish`

Actual output:

`/Users/username`

Dotnet version:
3.0.100-preview9-014004

**Comment by jkotas** [comment]
This behavior is by design.

This is how the different operating system shells set the current directory. .NET Core does not try to override it.
