### ISSUE TITLE
[Linux] Add initial perf jitdump support

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#26842]
Linux uses the perf tools to profile application. The linux 4.10 kernel added support for a `perf` `jitdump` format.

It has allows better JIT support for perf. Specifically allowing adding:

- native code so `perf` can show disassembly of JIT functions.
- adding debug info to support source line annotation.
- adding unwind info to better support stack unwind.

I believe this will also allow us to properly support `ready to run` images.

The app must 
- create the jitdump file. [Specification](https://elixir.bootlin.com/linux/v4.10/source/tools/perf/Documentation/jitdump-specification.txt)
- Inform `perf inject` of its presence by calling `mmap` with the filename.
- Add `JIT_CODE_LOAD` records
- Optionally add `JIT_DEBUG_INFO` records
- Optionally add `JIT_CODE_UNWINDING_INFO` records

It is used like this
```
perf record <app>
perf inject --jit
perf report
```

/cc @dotnet/dotnet-diag

**Comment by adamsitnik** [comment]
Is this going to help with https://github.com/dotnet/coreclr/issues/25965 ?

/cc @damageboy

**Comment by damageboy** [comment]
@adamsitnik I definitely think so!

@sdmaclea I noticed you self-asssigned this.
Does this mean you will be working on this or is this "up for grabs"?

**Comment by sdmaclea** [comment]
I am debugging a draft patch to implement the `JIT_CODE_LOAD records`. I plan to create a WIP PR today.

The current patch allows annotating the disassembly of the JITted functions.

I will start looking ar the ReadyToRun functions soon.

I don't plan to add the JIT_DEBUG_INFO or JIT_CODE_UNWINDING_INFO records yet, so that would be "up for grabs".

**Comment by damageboy** [comment]
@sdmaclea Very cool!

I'd love to test this out if you feel like sharing a branch at some point.

I might also look into the JIT_DEBUG_INFO records, I've peeked around CoreCLR code previously around the internal representation, would be interesting to see if I could pull that off :)

**Comment by sdmaclea** [comment]
@damageboy Thanks for the offer to help.  I uploaded #26897, additional debugging would be helpful.

**Comment by damageboy** [comment]
@sdmaclea 
I'm just finishing a family vacation. Will start testing early next week!
