### ISSUE TITLE
 EventListener does not receive events from RuntimeEventSource until dotnet-counters is explicitly started

### ISSUE THREAD

**Issue by neyromant** [dotnet/coreclr#26880]
Hi.
I wrote simple code for in-proc receive stat events from [RuntimeEventSource](https://github.com/dotnet/coreclr/blob/release/3.0/src/System.Private.CoreLib/src/System/Diagnostics/Eventing/RuntimeEventSource.cs)
```
using System;
using System.Diagnostics.Tracing;

namespace TestEventSource
{
    class Program
    {
        static void Main(string[] args)
        {
            var eventListener = new CustomEventListener();
            Console.WriteLine("Press Enter to stop");
            Console.ReadLine();
            eventListener.Dispose();
        }
    }

    class CustomEventListener : EventListener
    {
        protected override void OnEventSourceCreated(EventSource eventSource)
        {
            if(eventSource.Name == "System.Runtime")
                EnableEvents(eventSource, EventLevel.Verbose, EventKeywords.All);
        }

        protected override void OnEventWritten(EventWrittenEventArgs eventData)
        {
            Console.WriteLine($"Event written at {DateTime.Now}");
        }
    }
}

```
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

</Project>
```

The problem: OnEventWritten calls only if I run 'dotnet-counters' tool for this console app.

Can I subscribe to RuntimeEventSource events from my application to get the statistics it provides?

I try to run under Windows 10.
dotnet --version
3.0.100

**Comment by noahfalk** [comment]
@sywhang can you help here?

> Can I subscribe to RuntimeEventSource events from my application to get the statistics it provides?

Yep! A quick answer that might be enough, try this:

```
    protected override void OnEventSourceCreated(EventSource eventSource)
    {
        Dictionary<string,string> filterArgs = new Dictionary<string,string>();
        filterArgs["EventCounterIntervalSec"] = "1";
        if(eventSource.Name == "System.Runtime")
             EnableEvents(eventSource, EventLevel.Verbose, EventKeywords.All, filterArgs);
    }
```

That last argument tells the counters how frequently you want them trigger.

**Comment by neyromant** [comment]
>  Dictionary<string,string> filterArgs = new Dictionary<string,string>();
>         filterArgs["EventCounterIntervalSec"] = "1";

It works! Thank you very match!
