### ISSUE TITLE
Determine whether a running app is "PublishSingleFile" or not

### ISSUE THREAD

**Issue by zeroskyx** [dotnet/coreclr#26881]
Greetings,

using the new PublishSingleFile feature in .NET Core 3, is it possible to determine during runtime whether the running application is a PublishSingleFile-app or not?

Thanks in advance
-Simon

**Comment by jkotas** [comment]
Could you please share with us what you would like to use this for?

We plan to evolve how the single file publishing works for .NET 5. For example, we have a plan to stop extracting the managed binaries to %TEMP% and load them directly from the single file binary directly instead (more details in https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md). We would like to make sure that our guidelines are compatible with the future evolution of single file publishing.

As workaround, to communicate to your app binary whether it is published as single file, you can emit a custom attribute by adding the following to your .csproj file:

```
  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute" Condition="'$(PublishSingleFile)' == 'true'">
        <_Parameter1>SingleFile</_Parameter1>
        <_Parameter2>true</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
```

And then check for presence of this custom attribute at runtime.

cc @swaroop-sridhar

**Comment by zeroskyx** [comment]
Hi jkotas,

thanks for your answer. I am trying to address a situation where an application has assets that are either "embedded" into the single-file and thus extracted into the temp directory, and "dynamic" assets that are distributed along the single-file. 
Since several file APIs work differently on single file (AppContext.BaseDirectory for instance), it is important to know whether the app is single-file or not for shared libraries.

**Comment by jkotas** [comment]
Our recommendation for cases like these is to bundle the assets as embedded managed resources. It will continue to work fine once we stop extracting the files into a TEMP directory in .NET 5. There are existing APIs like `Assembly.GetManifestResourceStream` or `Assembly.GetManifestResourceNames` that allow accessing managed resources today and that will continue to work.

**Comment by zeroskyx** [comment]
Works for me, thank you!

**Comment by john-cullen** [comment]
@jkotas will that attribute not always be set if you have set PublishSingleFile in the csproj file instead of supplying it as a parameter to `dotnet publish` ?

**Comment by jkotas** [comment]
Right, the workaround that I have suggested does not work well if you set PublishSingleFile as csproj property.
