### ISSUE TITLE
[Linux] Segfault when AssemblyBuilder.DefineDynamicAssembly and PerfMap

### ISSUE THREAD

**Issue by klesta490** [dotnet/coreclr#26883]
Hi!
When I build app with final **.NET Core v3.0.0** and run it with
`COMPlus_PerfMapEnabled=1`

```
static void Main(string[] args)
{
     AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Sth.dll"), AssemblyBuilderAccess.RunAndCollect);
}
```

I get instantly **Segmentation faul**t.

It seems it is working fine on Preview9 (I was not testing any other versions).

It migh be related to [Link](https://github.com/dotnet/coreclr/issues/26830) 

Fun fact,
with `COMPlus_PerfMapEnabled=1`  
I get segfault for 

`dotnet new console`
`dotnet tool install -g dotnet-sos`   
That makes it real fun to diagnose.

Maybe this stack trace helps
```
frame #0: 0x00007f5a43d32caa libcoreclr.so`PerfInfo::LogImage(PEFile, char16_t) + 90
frame #1: 0x00007f5a43d31e57 libcoreclr.so`PerfMap::LogImage(PEFile*) + 279
frame #2: 0x00007f5a43e6c56a libcoreclr.so`Assembly::CreateDynamic(AppDomain, CreateDynamicAssemblyArgs) + 2538
frame #3: 0x00007f5a43ec052a libcoreclr.so`AppDomainNative::CreateDynamicAssembly(AssemblyNameBaseObject, StackCrawlMark, int) + 234
```
Of course I can disable it, but this prevents me from profiling apps :-(

**Comment by karelz** [comment]
@janvorli @jkotas any thoughts?
@klesta490 does it happen on more than 1 machine? This is highly suspicious.

**Comment by karelz** [comment]
Cc @noahfalk

**Comment by jkotas** [comment]
> @jkotas any thoughts?

Plain vanilla bug in the PerfMap implementation.

>  does it happen on more than 1 machine? This is highly suspicious

It is 100% repro.

**Comment by jkotas** [comment]
Likely introduced by https://github.com/dotnet/coreclr/pull/26403

cc @brianrob

**Comment by danmosemsft** [comment]
I set 3.0.x so it doesn't get lost, feel free to change.

**Comment by brianrob** [comment]
Yup, this was caused by #26403.  I am working on a fix.

**Comment by danmosemsft** [comment]
cc @jeffschwMSFT for shiproom.

**Comment by jkotas** [comment]
@brianrob Could you please prepare PR to back port this?

**Comment by jeffschwMSFT** [comment]
@brianrob we should consider this for 3.0.x servicing.  Can you create a cheery picked PR against the release/3.0 and mark with label:ask-mode.  We can then have it reviewed/approved by tactics.

cc @MeiChin-Tsai

**Comment by brianrob** [comment]
Yup, I'm already doing that.  Didn't mean to use the magic word to get GitHub to close this.  Will post the PR shortly.

**Comment by brianrob** [comment]
@jeffschwMSFT, I've posted #26910 and marked it with label:ask-mode.

**Comment by klesta490** [comment]
Is there any WA? I don't want to rebuild all images back to Preview9 :-/

**Comment by jeffschwMSFT** [comment]
The servicing fix is currently slated for 3.0.2.  +@brianrob on any potential workarounds.

**Comment by brianrob** [comment]
Unfortunately, I'm not aware of any workaround, short of not generating any dynamic assemblies.

**Comment by sdmaclea** [comment]
@brianrob Can this be closed?

**Comment by brianrob** [comment]
Yes, this has now been merged for 3.0.2.

**Comment by TheAngryByrd** [comment]
Any idea when 3.0.2 will be released?

**Comment by jeffschwMSFT** [comment]
cc @leecow

**Comment by leecow** [comment]
3.0.2 will be out January.

**Comment by baronfel** [comment]
Bit of clarification, this looks like it's part of the newly-release 3.0.1 Runtime as described here: https://github.com/dotnet/coreclr/pull/26910 and here: https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=milestone%3A3.0.1+label%3Aservicing-approved+sort%3Aupdated-desc

Thanks for the work, y'all!
