### ISSUE TITLE
VS2019.3.0 "Hello World" stackoverflow exception

### ISSUE THREAD

**Issue by sanchoflat** [dotnet/coreclr#26909]
Created empty .net core 3.0 console project. Press F5 and it fell down with StackOverFlow Exception. .exe file works from Debug folder fine. 

**System**
```
Windows 10
VisualStudio 2019.3.0
.NET Core Version: 3.0.100
.NET Core Commit: 04339c3a26
```

**Exception details** 
```
System.StackOverflowException
HResult=0x800703E9
Message=Exception of type 'System.StackOverflowException' was thrown.
```

![Animation](https://user-images.githubusercontent.com/6221261/65725036-608e7b00-e0ba-11e9-8f90-5a78a09ca78e.gif)

**Comment by Gnbrkm41** [comment]
Wonder if there's any stack trace / dumps that can be provided? I'm not having this issue at all.

**Comment by sanchoflat** [comment]
Stack trace is empty. Created dump file from test project debugging process. 
![Screenshot_6](https://user-images.githubusercontent.com/6221261/65779077-c24cf480-e14f-11e9-9b7d-6d23885680ad.png)

Maybe it is VS bug?

UPD. I switched to core 2 (2.1 and 2.2) and it works. Core 3.0 doesn't.

**Comment by jeffschwMSFT** [comment]
@sanchoflat can you try running the .NET Core 3 helloworld outside of VS?  Does it still crash?  What if you run in VS without the debugger attached?  
If we feel this is related to VS, we should move the investigation to VS Feedback.  If you file an issue and link it here, I can help route it to the right team.

**Comment by sanchoflat** [comment]
@jeffschwMSFT running without debugger still crashes. 
.exe files from Debug and Release folders work fine. Running .dll from command line works fine too.

> we should move the investigation to VS Feedback

Where can I file an issue to VS?

**Comment by jeffschwMSFT** [comment]
> Where can I file an issue to VS?

Within VS it is the 'send feedback' button in the upper right hand corner.  (looks like a person talking emoji). 

We can continue here, but if this ends up being a VS issue we will need to move there anyhow. Thanks

**Comment by sanchoflat** [comment]
> We can continue here, but if this ends up being a VS issue we will need to move there anyhow. Thanks
Thank you.
Sended a feedback to VS. Will print their answer here.

**Comment by jeffschwMSFT** [comment]
@sanchoflat, can you share the link here?  I can intercept and route as appropriate.  Also, do you happen to have a dump of the failure?

**Comment by jeffschwMSFT** [comment]
Got it, thanks: https://developercommunity.visualstudio.com/content/problem/755674/vs201930-hello-world-stackoverflow-exception.html

**Comment by sanchoflat** [comment]
@jeffschwMSFT sended two dump files. Hope they will help.
