### ISSUE TITLE
Fix corrupted mini-dumps on Windows that VS can not load

### ISSUE THREAD

**Issue by pr8x** [dotnet/coreclr#26907]
I am hosting a dotnet module inside my native C++ application and use google breakpad to generate minidumps. I noticed that only `MiniDumpWithFullMemory` seems to be useful for getting proper managed stacks. Some of these dumps can get quite big however. I was wondering if you guys have some clue on reducing the size a bit. Exporting "every readable page in the process" seems quite extreme. 
http://www.debuginfo.com/tools/clrdump.html claims to reduce the size of .NET dumps while maintaining relevant stack/thread information. It's not open-source AFAICT and seems to be targeting .NET Framework (not .NET Core!). Apparently he's using (according to https://stackoverflow.com/a/8258911/2354690):
```
MiniDumpNormal
MiniDumpWithProcessThreadData
MiniDumpWithThreadInfo
MiniDumpWithUnloadedModules
```

They don't seem to work for me. Any ideas?

**Comment by noahfalk** [comment]
@mikem8361, can you help here?

**Comment by noahfalk** [comment]
Ping @mikem8361 : )

In the meantime here are some things that may help:
env vars to take (small) dumps on crash: https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md#configurationpolicy
a tool that can take small dumps: https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-dump-instructions.md
The source in the dotnet-dump tool which calls MiniDumpWriteDump:
https://github.com/dotnet/diagnostics/blob/master/src/Tools/dotnet-dump/Dumper.Windows.cs#L27

**Comment by mikem8361** [comment]
You may not need all the flags that dotnet-dump collect uses.  I need to look into it because windbg/cdb's `.dump /mw <dump_name>` generates a "heap" dump and it uses just MiniDumpWithTokenInformation + MiniDumpWithPrivateReadWriteMemory (0x40200).

**Comment by pr8x** [comment]
I tried using the flags: 
```
 MiniDumpWithDataSegs |
        MiniDumpWithPrivateReadWriteMemory |
        MiniDumpWithHandleData |
        MiniDumpWithUnloadedModules |
        MiniDumpWithFullMemoryInfo |
        MiniDumpWithThreadInfo |
        MiniDumpWithTokenInformation
```
But I keep getting a symbol error when trying to "Debug with mixed". **Oddly, I don't get this when I generate with full memory**. 
![image](https://user-images.githubusercontent.com/4670166/66041014-19204880-e519-11e9-8b35-384619c6e91c.png)

It seems like it's failing to retrieve `System.Runtime.dll` symbols from the symbol server. 
> SYMSRV:  HTTPGET: /download/symbols/System.Runtime.dll/EB15006C/System.Runtime.dll
> SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND

Could be an issue with VS, but it seems to be somehow related to the minidump flags. How come it successfully resolves symbols for fully memory dumps?

**Comment by mikem8361** [comment]
I'm currently investigating this problem.  Sorry for the delay.

**Comment by pr8x** [comment]
Any update on this issue ... 😄?

**Comment by mikem8361** [comment]
I think I’ve narrowed it down to the DAC’s (mscordaccore) memory enumeration API faulting.  It may take me a while to figure out the root cause.  The bad news if it is in the DAC the fix will have to go out in the next service release.

**Comment by pr8x** [comment]
I changed the title. It sounded like **I** fixed them 😄

**Comment by pr8x** [comment]
Hey @mikem8361, did you figure out what is causing the issue?

**Comment by pr8x** [comment]
That's great news! Do you have any tracking ticket for the Visual Studio update?

**Comment by pr8x** [comment]
Hi, sorry to bump this again. Is there any release candidate for Visual Studio that fixes this issue? I am currently running VS2019 **16.3.7** and it seems to be still broken. I created a small repro here: https://github.com/pr8x/netcore31_bug_minidump

**Comment by pr8x** [comment]
Hi, Sorry for the bump, but do you happen to know if there's a release candidate for Visual Studio that fixes the issue? I am currently running **VS2019 v16.3.7** and the problem still exists. I created a small repro here: https://github.com/pr8x/netcore31_bug_minidump

**Comment by mikem8361** [comment]
It looks like the VS fixes are going into 16.5 preview 1. @chuckries can answer for sure. You will also need .NET Core 3.1 coming out in December for minidumps to work end-to-end.

**Comment by mikem8361** [comment]
This issue is just waiting for @chuckries to confirm the VS version.

**Comment by pr8x** [comment]
Hey, sorry to revive this issue. But it seems like that with .NET Core 3.1 and Visual Studio 16.4.0 it is still crashing while generating the dump. This time it's a couple of `Microsoft C++ HRException` thrown within the DAC (Flags used: `MiniDumpWithTokenInformation | MiniDumpWithPrivateReadWriteMemory):
`
> KernelBase.dll!RaiseException()
mscordaccore.dll!_CxxThrowException(void * pExceptionObject, const _s__ThrowInfo * pThrowInfo) Line 133
	at d:\agent\_work\2\s\src\vctools\crt\vcruntime\src\eh\throw.cpp(133)
mscordaccore.dll!DacError(HRESULT err) Line 118
	at f:\workspace\_work\1\s\src\debug\daccess\dacfn.cpp(118)
mscordaccore.dll!DacGetThreadContext(Thread * thread, _CONTEXT * context) Line 95
	at f:\workspace\_work\1\s\src\debug\daccess\reimpl.cpp(95)
mscordaccore.dll!Thread::EnumMemoryRegionsWorker(CLRDataEnumMemoryFlags flags) Line 8780
	at f:\workspace\_work\1\s\src\vm\threads.cpp(8780)
mscordaccore.dll!Thread::EnumMemoryRegions(CLRDataEnumMemoryFlags flags) Line 8743
	at f:\workspace\_work\1\s\src\vm\threads.cpp(8743)
mscordaccore.dll!ThreadStore::EnumMemoryRegions(CLRDataEnumMemoryFlags flags) Line 8915
	at f:\workspace\_work\1\s\src\vm\threads.cpp(8915)
mscordaccore.dll!ClrDataAccess::EnumMemDumpAllThreadsStack(CLRDataEnumMemoryFlags flags) Line 1173
	at f:\workspace\_work\1\s\src\debug\daccess\enummem.cpp(1173)
mscordaccore.dll!ClrDataAccess::EnumMemoryRegionsWorkerHeap(CLRDataEnumMemoryFlags flags) Line 337
	at f:\workspace\_work\1\s\src\debug\daccess\enummem.cpp(337)
mscordaccore.dll!ClrDataAccess::EnumMemoryRegionsWrapper(CLRDataEnumMemoryFlags flags) Line 1831
	at f:\workspace\_work\1\s\src\debug\daccess\enummem.cpp(1831)
mscordaccore.dll!ClrDataAccess::EnumMemoryRegions(ICLRDataEnumMemoryRegionsCallback * callback, unsigned int miniDumpFlags, CLRDataEnumMemoryFlags flags) Line 1935
	at f:\workspace\_work\1\s\src\debug\daccess\enummem.cpp(1935)
dbgcore.dll!GenGetProcessInfo(unsigned long,struct _MINIDUMP_STATE *,struct _INTERNAL_PROCESS * *,struct _LIST_ENTRY *)
dbgcore.dll!MiniDumpProvideDump()
dbgcore.dll!MiniDumpWriteDump()


@chuckries Do you already know which version of VS is shipping the fixes?

**Comment by danmosemsft** [comment]
@pr8x it might be better to open a new issue with a link back to this closed one
