### ISSUE TITLE
Missing [Serializable] on List<>.Enumerator

### ISSUE THREAD

**Issue by LunicLynx** [dotnet/coreclr#26919]
I just ran into an Serialization issue with List<>.Enumerator.

This worked on .NET Framework, but doesn't work on .NET Core.

The documentation states that the Enumerator should have the Serializable attribute, but currently it doesn't.

Docs:
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.enumerator?view=netcore-3.0

Code:
https://github.com/dotnet/coreclr/blob/0d1c180164555513cbdb206dd4546007cbb3a42c/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs#L1075-L1079

**Comment by jkotas** [comment]
.NET Core supports binary serialization for a subset of types: https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization . `List.Enumerator` is not on this list. 

> The documentation states that the Enumerator should have the Serializable attribute, but currently it doesn't.

This is a bug in the documentation: https://github.com/dotnet/dotnet-api-docs/issues/3149

**Comment by LunicLynx** [comment]
Understood. DataContractSerializer also counts as binary serialization because of serialization of private fields?
I just want to make sure i understand what `binary serialization` means. Until now i thought xml is not binary, but i guess i was looking at it from the wrong angle?

**Comment by jkotas** [comment]
Yes, some of the serializers out there - including DataContractSerializer - use the binary serialization contract as one of their serialization mechanisms.
