### ISSUE TITLE
Extend generic constraint checks to cover the attribute <Flags> on enum.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/coreclr#26921]
It would be helpful if the clr could valid that a enum constraint, also has the attribute `System.Flags`
So the it possible to implement generic methods that apply to all enums that are semantically treated as flags.

eg.
```vbnet
<Extension>
Public Function AreAllFlagsSet(Of T As {Structure, <Flags>Enum})( value As T, flags As T ) As T
  Return (value And flags) = flags
End Function

<Extension>
Public Function AnyOfFlagsSet(Of T As {Structure, <Flags>Enum})( value As T, flags As T ) As T
  Return (value And flags) <> 0
End Function

<Extension>
Public Function SetFlags(Of T As {Structure, <Flags>Enum})( value As T, flags As T ) As T
  Return value Or flags
End Function

<Extension>
Public Function ClearFlags(Of T As {Structure, <Flags>Enum})( value As T, flags As T ) As T
  Return value And Not flags
End Function
```

Note: I implemented a set of operators over `flags enum` that effectively lowered the implementation in to the above implementations. An effect of do that was constant folding was applied a compile-time, effectively optimising the checks.

**Comment by MichalStrehovsky** [comment]
We keep a high bar for file format changes - adding a new kind of constraint that the runtime enforces would be a file format change.

The CLR cares very little about `FlagsAttribute` - this could be implemented purely in the language (same as e.g. how the C# team added the `unmanaged` generic constraint in the past).

It also wouldn't make sense to add the constraint without exposing it from C#/VB/F#. As such, this should start as an issue in the vblang repo (I'll move this issue there). If this gets commited and file format change is really needed, we would file a new issue in the CLR/Mono/... repo.

**Comment by MichalStrehovsky** [comment]
Okay, seems like I can't transfer issues to that repo. Please open a new issue in the dotnet/vblang repo.
