### ISSUE TITLE
Failed to load libhostfxr.so, error: /lib/libstdc++.so.6: version `GLIBCXX_3.4.18' not found

### ISSUE THREAD

**Issue by nnhy** [dotnet/coreclr#26929]
root@A1:~# uname -a
Linux A1 3.2.0 #561 Mon Mar 13 13:36:13 CST 2017 armv7l GNU/Linux
root@A1:~# cat /proc/version 
Linux version 3.2.0 (gcc version 4.7.3 20130226 (prerelease) (crosstool-NG linaro-1.13.1-4.7-2013.03-20130313 - Linaro GCC 2013.03) ) #561 Mon Mar 13 13:36:13 CST 2017
root@A1:~# dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
root@A1:~# dotnet --info
Failed to load ¼, error: /lib/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /usr/share/dotnet/host/fxr/3.0.0/libhostfxr.so)
The library libhostfxr.so was found, but loading it from /usr/share/dotnet/host/fxr/3.0.0/libhostfxr.so failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063370
root@A1:~# strings /lib/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by janvorli** [comment]
This means that your Linux distro is too old (having the libstdc++.so.6 that is too old) and it is not supported due to to that.

**Comment by whuanle** [comment]
@janvorli Replace libstdc++. So,.net Core will work?

**Comment by janvorli** [comment]
I am not sure what Linux distro you are using and what is its policy in updating standard C and C++ libraries. If you can upgrade the libstdc++ to a newer version, that would fix the problem you are seeing. There might possibly be other issues that show up after you upgrade.

**Comment by jashook** [comment]
@janvorli is this issue worth closing?

**Comment by janvorli** [comment]
@nnhy can we close this issue?

**Comment by nnhy** [comment]
We have upgraded the Linux system to solve this problem.
