### ISSUE TITLE
[Snap] [dotnet-sdk] Segmentation Fault

### ISSUE THREAD

**Issue by deinok** [dotnet/coreclr#26931]
OS: ubuntu-desktop_19.04
SDK: 3.0.100

# How to reproduce it
- install dotnet-sdk via snap and alias dotnet-sdk.dotnet to dotnet
- create a webapi project using the CLI
- Run `dotnet run` - No message / Not running
- Run `dotnet *.dll` - Works as expected
- Run the executable generated -  `Segmentation fault (core dumped)`

**Comment by kevingosse** [comment]
Probably the same issue as https://github.com/dotnet/core-setup/issues/8306

**Comment by deinok** [comment]
@kevingosse Yes, it's exactly the same. Closing this and moving the conversation to that issue.
