### ISSUE TITLE
Compile without switch optimizations

### ISSUE THREAD

**Issue by shargon** [dotnet/coreclr#26949]
# Issue Title

Is possible to specify some flags in the compiler for disable some optimizations? 

# General

As i know, when a switch have a lot of entries, is added a method `ComputeStringHash` is possible to prevent this optimizations?

**Comment by mikedn** [comment]
This looks like an issue for https://github.com/dotnet/roslyn

The runtime (JIT) doesn't do anything about string typed switches. These don't even explicitly exist in IL.

**Comment by shargon** [comment]
Thanks!
