### ISSUE TITLE
3.0 is fine, but 3.0 preview9 libcoreclr.so symbols weren't stripped (Ubuntu 16.04)

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#26946]
Bringing this up to make sure it's known, in case it's some flakiness that might show up in a future 3.0 servicing release.

In https://github.com/dotnet/core/issues/3494, @sdmaclea noted that `libcoreclr.so` for 3.0 p9 on Ubuntu 16.04 had symbols inside, rather than them being stripped like would be expected for an official build:

> Symbols were in `3.0.0-preview9-19423-09/libcoreclr.so`

There was a symbol stripping issue fixed with https://github.com/dotnet/coreclr/pull/22083, but that seems much earlier than p9.

@sbomer @jashook @RussKeldorph, do you know why this could have happened for p9 but not GA?

(If this isn't concerning or interesting, feel free to close. I'm not very in touch with which releases had which infra changes in CoreCLR--perhaps there was a big enough refactor somewhere that it doesn't matter why this happened in P9.)

**Comment by sbomer** [comment]
Interesting - I don't see anything obvious in the build definitions that would have caused this.

**Comment by sdmaclea** [comment]
I vaguely remember an issue where something was lost off the servers...  Engineering rebuilt/replaced them.  Could that be the root cause???

**Comment by dagood** [comment]
Interesting... if it were accidentally run as Debug somehow, that would explain it. I'm not familiar with what happened, though.
