### ISSUE TITLE
[Linux] PAL functions usage from native code (debugger)

### ISSUE THREAD

**Issue by viewizard** [dotnet/coreclr#26964]
Hello,
I noticed, that in CoreCLR 3.0 preview7 was added https://github.com/dotnet/coreclr/commit/a6292a6573e1f7d6e218293773e443280683cd83 commit, that remote export for PAL functions. For now, we use them in our NetCoreDBG debugger (https://github.com/Samsung/netcoredbg/blob/886fd637f4c6d4eeca077cb5d5a1eacc95a813ea/src/debug/netcoredbg/symbolreader.cpp#L177). Is it possible revert back export for PAL in order to make native->native usage of PAL functions? Or qcalls is the only way for direct PAL usage from now and this feature will be available in future CoreCLR versions for sure?

**Comment by jkotas** [comment]
We consider the Windows PAL to be internal implementation detail of CoreCLR. We plan to make it smaller and lighter weight over time. Ideally, it would disappear eventually.

The 5 functions you have linked are trivial wrappers over malloc/free. You should be able to make a local version of these wrappers in NetCoreDBG to avoid depending of CoreCLR internals.

**Comment by viewizard** [comment]
@jkotas, you right, looks like I could just implement this 5 functions. Thanks for your help!
