### ISSUE TITLE
x64 Windows does not correctly handle __m128 returns.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#27002]
The default calling convention for x64 Windows specifies that `__m128`, `__m128i`, and `__m128d` are returned in XMM0: https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=vs-2019#return-values

These types correspond to the `System.Runtime.Intrinsics.Vector128<T>` type on the managed side and it is not currently being returned in XMM0.

https://github.com/dotnet/coreclr/pull/23899 adds support for passing `Vector128<T>` across interop boundaries and so this will need to be correctly handled.

**Comment by tannergooding** [comment]
CC. @CarolEidt

**Comment by CarolEidt** [comment]
How is this distinct from #15943?

**Comment by tannergooding** [comment]
I forgot I logged the former and couldn't find it in GitHub search. I'll update the former with this specific scenario shortly and then will close this one.
