### ISSUE TITLE
Private static readonly unused intializers removed from optimized build.

### ISSUE THREAD

**Issue by malylemire1** [dotnet/coreclr#27016]
Here is an example of the behavior I get :

public class MyClass
{
        private static readonly MyClass _instance = new MyClass();

        private MyClass()
        {
            Console.WriteLine("Never called in release build.");
        }

        ~MyClass()
        {
            Console.WriteLine("Never called in release build.");
        }
}

public class MyClass
{
        private static readonly MyClass _instance;

	static MyClass()
        {
            _instance = new MyClass();
        }

        private MyClass()
        {
            Console.WriteLine("Called in release build.");
        }

        ~MyClass()
        {
            Console.WriteLine("Called in release build.");
        }
}

**Comment by malylemire1** [comment]
Sorry about this. I'm using .net full framework. Don't know if you can reproduce the behavior in .net core.

**Comment by jkotas** [comment]
The behavior you are seeing is expected. Your first example has "before field init" constructor that is not guaranteed to run. The runtime can choose whether to run it or not, and the behavior can differ between debug and release builds.

https://github.com/dotnet/coreclr/issues/1193 and https://github.com/dotnet/coreclr/issues/25580 have more discussion about this problem.
