### ISSUE TITLE
Should globalization native shim support older ICU versions on alpine?

### ISSUE THREAD

**Issue by safern** [dotnet/coreclr#27018]
The coreclr musl build was moved to now build on alpine-3.9. If people try to use a build of the product that contains latest .NET 5 coreclr on < alpine-3.9 and hits any globalization path, it would fail with: 

```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
at System.Environment.FailFast(System.String)
at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
at System.Globalization.GlobalizationMode..cctor()
at System.Globalization.GlobalizationMode.get_Invariant()
at System.Globalization.CultureData.CreateCultureWithInvariantData()
at System.Globalization.CultureData.get_Invariant()
at System.Globalization.CultureInfo..cctor()
at System.Globalization.CultureInfo.get_CurrentCulture()
```

The reason for that is because we try to load the ICU version that we compiled against (defined in the headers) and 20+ versions of it. 
https://github.com/dotnet/coreclr/blob/190888373afe4f526de2bd7f366ffe53cced0325/src/corefx/System.Globalization.Native/pal_icushim.c#L57-L58

@janvorli commented:

"_The reason to not to always start from the version 50 (the first one that we can possibly work with and the one present on CentOS 7) was to ensure that we do a minimal amount of scanning when we build for specific distro. Another reason was that on glibc based distros, build from a newer distro can never work on an older one anyways.
The MUSL based distros are different though, build created on a newer Alpine actually works on an older one, so it would make sense to make the initial version constant for MUSL based distros (I would use the version from 3.6)_"

For more details see: https://github.com/dotnet/corefx/pull/41280#issuecomment-537710811 

cc: @wfurt @jkoritzinsky

**Comment by xiangzhai** [comment]
Hi,

Workaround:

```
export CLR_ICU_VERSION_OVERRIDE="52.1"
```

For other older libicu:

```
$ rpm -ql libicu
/usr/lib64/libicudata.so.52
/usr/lib64/libicudata.so.52.1
/usr/lib64/libicui18n.so.52
/usr/lib64/libicui18n.so.52.1
/usr/lib64/libicuio.so.52
/usr/lib64/libicuio.so.52.1
/usr/lib64/libicule.so.52
/usr/lib64/libicule.so.52.1
/usr/lib64/libiculx.so.52
/usr/lib64/libiculx.so.52.1
/usr/lib64/libicutest.so.52
/usr/lib64/libicutest.so.52.1
/usr/lib64/libicutu.so.52
/usr/lib64/libicutu.so.52.1
/usr/lib64/libicuuc.so.52
/usr/lib64/libicuuc.so.52.1
...
```

Thanks,
Leslie Zhai
