### ISSUE TITLE
Current executing assembly location is wrong for single file published project

### ISSUE THREAD

**Issue by IustinMicu** [dotnet/coreclr#27033]
# Current executing assembly location is wrong when the project is published as a single file

# General

I upgraded a .net core 2.2 application to 3.0 and I enabled the PublishSingleFile feature.
Unfortunately the current executing assembly location is not the directory where the executable is located. It is something like this: 

> \%AppData%\Local\Temp\.net\<project_name>\q1upmq4v.zgw

- This is how the single file publish feature is configured:
    `<TargetFramework>netcoreapp3.0</TargetFramework>`
    `<PublishSingleFile>true</PublishSingleFile>`
    `<RuntimeIdentifier>win-x64</RuntimeIdentifier>`
    `<PublishTrimmed>true</PublishTrimmed>`
    `<OutputType>Exe</OutputType>`

- This is how I get the location of the current executing assembly:
   `var location = System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);`

**Comment by MichalStrehovsky** [comment]
Cc @vitek-karas @swaroop-sridhar

**Comment by swaroop-sridhar** [comment]
The assermbly-location is the location of the main application DLL, which will be the temporary extraction directory. You can use something like: 
Process.GetCurrentProcess().MainModule.FileName

Or pinvoke into GetModuleFileNameW(Null, <buffer>, <len>)

**Comment by swaroop-sridhar** [comment]
This is a dup of https://github.com/dotnet/core-setup/issues/7491
