### ISSUE TITLE
Debug.Assert is causing hard crashes

### ISSUE THREAD

**Issue by ayende** [dotnet/coreclr#2704]
If a Debug.Assert fails, the result is a hard crash, without any additional information on the source of the crash, the Debug.Assert message, etc.

I was debugging a heap corruption failure (caused by me not keeping track of the size of the buffer I was using), and after I fixed that, the system kept getting hard crashes. It took me a long while to figure out that the error was actually a debug assert firing, because the error behaved in the same manner as heap corruption. 

Debug Assert failure should result in a nice message box, or at least an exception being thrown, not a FailFast call with no additional info

**Comment by ellismg** [comment]
> Debug Assert failure should result in a nice message box, or at least an exception being thrown, not a FailFast call with no additional info

What version of System.Diagnostics.Debug library are you using?  In CoreFX we throw an exception today unless a debugger is attached.  If a debugger is attached we ask the debugger to break instead.

**Comment by ayende** [comment]
Using System.Diagnostics.Debug, Version=4.0.11.0

This is the result of what you get when running the previous code, without debugger attached.
In coreclr update1, 64 bits.

![image](https://cloud.githubusercontent.com/assets/116915/12371729/4b666860-bc46-11e5-98e6-13c0f77415eb.png)

This is what happens when you click debug:
![image](https://cloud.githubusercontent.com/assets/116915/12371733/7bf377fc-bc46-11e5-8ea9-736bc24063b4.png)

**Comment by ellismg** [comment]
I see.  This is a difference between the RC1 and RC2 behaviors.  In RC1, we called FailFast.  In RC2, we changed the behavior (see dotnet/corefx@68e46ff1b9bf5dea3490028bcd9742bd3dd92fc7) to throw an exception.  dotnet/corefx#3708 tracks having a nicer experience (e.g. popping up a dialog).
