### ISSUE TITLE
Build VB code

### ISSUE THREAD

**Issue by romrom38** [dotnet/coreclr#2708]
One working exemple for VB would be great.
I've found the corefx project Microsoft.VisualBasic witch is written in VB but it did not help much.

I can't manage to build a VB helloworld project with the "dnx run" command.
Could you confirm it can be done ? Or has the project to be built using other tools ?

The error I get is : 'helloworld_vb' does not contain a 'Program' type suitable for an entry point

main.vb:

Imports System

Public Module Hello
   Sub Main()
     Console.WriteLine ("Hello, Linux")
   End Sub
End Module

Here is the project.json file used:
{
    "version": "1.0.0-*",
    "compile": "*.vb",
    "definitions": {
		  "compilationOptions": {
			  "properties": {
			    "languageVersion": "experimental"
        }
      }
    },
    "frameworks" : {
        "dnx451" : { },
        "dnxcore50" : {
            "dependencies": {
                "System.Console": "4.0.0-beta-*",
                "Microsoft.VisualBasic": "10.0.0"                
            }
        }
    }
}

I tried the following commands but it didn't help:

wget https://www.nuget.org/api/v2/package/Microsoft.VisualBasic/10.0.0 -C Microsoft.VisualBasic
dnu packages add Microsoft.VisualBasic
dnu restore
dnx run

**Comment by davidfowl** [comment]
Theres no support for visual basic in the DNX. See this issue for .NET CLI support https://github.com/dotnet/cli/issues/72

**Comment by romrom38** [comment]
Thanks !
Following ☺

De : David Fowler [mailto:notifications@github.com]
Envoyé : samedi 16 janvier 2016 17:46
À : dotnet/coreclr <coreclr@noreply.github.com>
Cc : Romain FABBRI <romain.fabbri@alienconsulting.net>
Objet : Re: [coreclr] Build VB code (#2708)


Theres no support for visual basic in the DNX. See this issue for .NET CLI support dotnet/cli#72<https://github.com/dotnet/cli/issues/72>
