### ISSUE TITLE
ngen output too verbose

### ISSUE THREAD

**Issue by tamlin-mike** [dotnet/coreclr#27085]
ngen.exe 4.8.3752.0

While attempting to ngen a (local bugfixed) VS dll, last step would be to ngen it. While it ultimately failed (even with strong name verification skipping it failed), it displayed a problem with the verbosity of ngen output on failure:

```
>ngen install Microsoft.VisualStudio.LanguageServices.dll
Microsoft (R) CLR Native Image Generator - Version 4.8.3752.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Failed to compile C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\Microsoft.VisualStudio.LanguageServices.dll because of the following error: Strong name validation failed. (Exception from HRESULT: 0x8013141A).
Uninstalling assembly C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\Microsoft.VisualStudio.LanguageServices.dll because of an error during compilation: Failed to compile C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\Microsoft.VisualStudio.LanguageServices.dll because of the following error: Strong name validation failed. (Exception from HRESULT: 0x8013141A).
Strong name validation failed. (Exception from HRESULT: 0x8013141A)
```

It doesn't look extremely bad like this, when the lines are allowed to extend to column 557, but look at how it becomes in a console window where the output wraps:

--- begin blob ---
Microsoft (R) CLR Native Image Generator - Version 4.8.3752.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Failed to compile C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\Microsoft.VisualStudio.LanguageServices.dll because of the following error: Strong name validation failed. (Exception from HRESULT: 0x8013141A).
Uninstalling assembly C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\Microsoft.VisualStudio.LanguageServices.dll because of an error during compilation: Failed to compile C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\Microsoft.VisualStudio.LanguageServices.dll because of the following error: Strong name validation failed. (Exception from HRESULT: 0x8013141A).
Strong name validation failed. (Exception from HRESULT: 0x8013141A)
--- end blob ---

That blob of text is quite unreadable. Provided ngen is single-threaded in this scenario, or have a unique "job id" per assembly it's trying to install, would it perhaps make sense to display that job it (possibly prepended by process id) on the first mention of the file name (which, let's face it, can be of almost arbitrary length up to 32K), and after that only display that unique identifier?

It would still be uniquely identifying the very same file, but would be _way_ more readable.

Example of cleaned up output, with stripping of redundant exception output added in for good measure:
```
Microsoft (R) CLR Native Image Generator - Version 4.8.3752.0
Copyright (c) Microsoft Corporation.  All rights reserved.
1234/0123 ERR: Failed to compile C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\Microsoft.VisualStudio.LanguageServices.dll
1234/0123 Strong name validation failed. (Exception from HRESULT: 0x8013141A)
1234/0123 Uninstalling assembly because of an error during compilation.
```

Comments?

**Comment by jeffschwMSFT** [comment]
@tamlin-mike thanks for the .NET Framework feedback.  Can you share this feedback via VS Feedback?  dotnet/coreclr is primarily for .NET CORE.  Once you have a link, please share it here and I can help triage it internally.

**Comment by tamlin-mike** [comment]
@jeffschwMSFT As requested. Did not intend to start this off at the wrong end.
[DC](https://developercommunity.visualstudio.com/idea/767936/ngen-output-too-verbose.html)

On a sidenote, that blob of text looks much more representative here in the github issue, where column width is not as wide. :-)

**Comment by jeffschwMSFT** [comment]
Thanks @tamlin-mike, I am going to close this issue and we can track it in VS Feedback.
