### ISSUE TITLE
Supress Ilasm warnings

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/coreclr#27105]
I was wondering if there is a way to suppress Ilasm warnings such as this - 

`System.IdentityModel.Services.il(8810): warning : Method has no body, 'ret' emitted` 

One could always add empty method body but in some cases it seems like an arduous task. A way to suppress warnings would be very helpful.  

[This](https://github.com/dotnet/source-build-reference-packages/blob/dff61f31f7ff7fa85addda69514f5ece82fc3ff8/src/targetPacks/buildTargettingPackages.proj#L36) is the current set of arguments I am feeding.

**Comment by jeffschwMSFT** [comment]
@BruceForstall

**Comment by BruceForstall** [comment]
I'm not aware of any way to suppress warnings. Documentation: https://docs.microsoft.com/en-us/dotnet/framework/tools/ilasm-exe-il-assembler

Source: https://github.com/dotnet/coreclr/tree/master/src/ilasm

**Comment by adaggarwal** [comment]
Is this something that can be easily added?

**Comment by BruceForstall** [comment]
Potentially, but it's hard to imagine we would prioritize this work.

**Comment by adaggarwal** [comment]
I understand. Thanks for providing all the pertinent information 👍
