### ISSUE TITLE
Looking for a reference page in coreclr listing area owners per area-label

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/coreclr#27111]
Since we are looking to consolidate corefx and coreclr repos together, it is worth understanding who the area owners are for each area label in coreclr. This might be implicitly known by the coreclr members but if we can identify that, then the labeler can reliably set owners as reviewers to issues/PR at the time of assigning labels.

The existing list of area owners maintained for corefx can be found here:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md
The goal of this issue is to compile something similar to the issue-guide above (as a single source of truth), but for coreclr instead.

Related to https://github.com/dotnet/coreclr/issues/26175

**Comment by maryamariyan** [comment]
Below is the list of areas I found:

area-AssemblyLoader
area-Build
area-CodeGen
area-CrossGen/NGEN
area-crossgen2
area-Diagnostics
area-ExceptionHandling
area-GC
area-Host
area-ILTools
area-Infrastructure
area-Interop
area-Meta
area-Meta-corelib
area-Microsoft.CSharp
area-PAL
area-R2RDump
area-ReadyToRun
area-SDK
area-Serialization
area-Setup
area-Snap
area-System.Buffers
area-System.Collections
area-System.Data.SqlClient
area-System.Diagnostics
area-System.Diagnostics.Process
area-System.Diagnostics.Tracing
area-System.Drawing
area-System.Globalization
area-System.IO
area-System.IO.Pipelines
area-System.Linq.Expressions
area-System.Memory
area-System.Net
area-System.Numerics
area-System.Reflection
area-System.Reflection.Emit
area-System.Resources
area-System.Runtime
area-System.Runtime.Extensions
area-System.Security
area-System.Threading
area-System.Threading.Tasks
area-System.Transactions
area-TieredCompilation
area-Tracing
area-TypeSystem
area-VM

**Comment by sandreenko** [comment]
cc @jeffschwMSFT as a repo owner.

area-CodeGen - @BruceForstall or @dotnet/jit-contrib 
area-Infrastructure - @dotnet/coreclr-infra

**Comment by AaronRobinsonMSFT** [comment]
@maryamariyan It is a bit crusty, but https://github.com/dotnet/coreclr/blob/master/CODE_OWNERS.TXT has some context.

**Comment by AaronRobinsonMSFT** [comment]
area-Interop - @jeffschwMSFT @AaronRobinsonMSFT 
area-AssemblyLoader - @jeffschwMSFT @vitek-karas 
area-Host - @jeffschwMSFT @vitek-karas 
area-GC - @Maoni0 
area-Diagnostics - @tommcdon 
area-ExceptionHandling - @janvorli

**Comment by maryamariyan** [comment]
Thank you for the responses. Please feel free to update my comment above containing the table with the appropriate entries.

**Comment by BruceForstall** [comment]
area-CrossGen/NGEN area-crossgen2 -- @nattress ?
area-VM -- @sergiy-k ?
area-System.Threading, area-System.Threading.Tasks -- @kouvel ?
area-PAL -- @janvorli

**Comment by fadimounir** [comment]
area-CrossGen/NGEN @fadimounir
area-crossgen2 @nattress @MichalStrehovsky @trylek @fadimounir  
area-ReadyToRun @fadimounir

**Comment by jkotas** [comment]
The owners for `area-System.*` should be identical to CoreFX. Link to the CoreFX doc https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md to avoid duplication?

**Comment by maryamariyan** [comment]
Thanks @jkotas. Updated table by linking to that page for area-System.* items.

about 6 more areas left.

**Comment by BruceForstall** [comment]
area-Tracing: @sywhang @josalem ?
area-Setup, area-Snap: these don't exist

**Comment by maryamariyan** [comment]
Thanks @BruceForstall. I noticed area-Setup and area-Snap labels are for core-setup labels.
They were originally in the list above because the below issues got transferred from coreclr to core-setup.
https://github.com/dotnet/core-setup/issues/8306
https://github.com/dotnet/core-setup/issues/8368

I'll ignore them. Thanks

**Comment by kouvel** [comment]
area-TieredCompilation -- @kouvel, updated

**Comment by maryamariyan** [comment]
Closing as the table is completed now. 

Thanks everyone for your help and contribution on filling out the blanks.
