### ISSUE TITLE
Blocked state for Task when Wait(), GetResult() called

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#2712]
If asynchronous completion is desired it can be achieved either by `RunContinuationsAsynchronously` or by calling the completions on the Threadpool.

However if the caller is on a threadpool thread and has called `.Wait()` its has now reduced the threadpool by one thread so there is one less thread to complete with; if enough have done this then there won't be enough threadpool threads to unblock them.

If `.Wait()` marked the continuation as blocked then it would be safe to unblock them synchronously without stealing the callers thread.

(Example situation IO thread; notifying synchronous Stream Read/Write)

The pattern would be something like:

```csharp
foreach (var continuation in _blockedContinuations)
{
    continuation.Invoke();
}
foreach (var continuation in _otherContinuations)
{
    ThreadPool.QueueUserWorkItem(continuation);
}
```
or
```csharp
foreach (var continuation in _continuations)
{
    if (continuation.IsSyncBlocked)
    {
        continuation.Invoke();
    }
    else
    {
        ThreadPool.QueueUserWorkItem(continuation);
    }
}
```
This could either be a Task method that handled these actions; extra param on TCS TrySetResult/Cancelled/Exception to take async: true or a property of the Task - although a property on the task would only work for one waiting item?

**Comment by stephentoub** [comment]
I'm not understanding the suggestion. Which task are you waiting on? What does this have to do with Stream.Read/Write (which don't use continuations)? Why is synchronous blocking being used, and if it is, aren't there bigger scalability issues at play? And in terms of exhausting the ThreadPool, while there could be small pauses as it infects more threads, on 64-bit by default it would take 32k of them before it was actually exhausted.

In past when we've looked into chaining waits and inlining, it's never proven worthwhile. That's not say never will, of course, but I am a bit skeptical it's really worth both the effort and costs.

**Comment by NickCraver** [comment]
I think the "exhaust" terminology here with the threadpool is accurate, in rapid thread usage (when not returned) it happens continually before each growth phase from the dozens all the way to 32k in every scenario we run into issues with it. Given that it grows on an interval you can exhaust the current cap it until the next interval very quickly.

**Comment by benaadams** [comment]
> What does this have to do with Stream.Read/Write (which don't use continuations)? Why is synchronous blocking being used

Maybe there is a better way to implement this. However, the this issue is captured by well by the scenario of exposing a `Stream` wrapper, for portability, around an implementation that is purely `async` and has no real sync implementation.

I currently see three approaches:

1. Throw a `NotImplementedException` in the synchronous methods - this would make people very unhappy.
2. Use a custom base class/interface such as https://github.com/dotnet/coreclr/issues/2179 and don't use `Stream` to not expose sync methods, probably hard to get traction/interop without wider support.
3. Synchronous blocking similar to

```csharp
public override void Write(byte[] buffer, int offset, int count)
{
    WriteAsync(buffer, offset, count, CancellationToken.None).GetAwaiter().GetResult();
}

public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken token)
{
    // ....
}
```
> and if it is, aren't there bigger scalability issues at play?

Yes and no. Yes because there would be; no because the first issue you'll hit is blocking on thread pool delays for new thread creation. This is further complicated as there is no `ThreadPool.SetMinThreads` option for coreclr https://github.com/dotnet/corefx/issues/3392 (Does it increase at a rate of 1 per second?)

So for example if there was a method in a web request that made a synchronous write call that did not complete immediately; if you fired off 100 requests to it concurrently, although the IO would complete quite quickly (as that is handled separately) the requests themselves would make very slow progress as their notifications/actiivations are coming back on the threadpool and have to wait for new threads to be completed - so they would be blocking themselves.

**Comment by benaadams** [comment]
Could always deprecate `Stream`'s sync methods :stuck_out_tongue_winking_eye:

**Comment by benaadams** [comment]
A specific relevant implementation https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/SocketOutput.cs#L375-L392

**Comment by benaadams** [comment]
For the particular implementation, could maybe use something other than a TCS and have something more custom for `.GetAwaiter().GetResult()` rather than something in coreclr?

**Comment by stephentoub** [comment]
@benaadams, let me try this again.

Your proposal suggests something related to continuations, waiting on tasks, and blocking.  I don't understand what you're proposing.  *Can you please elaborate what it is specific to continuations that you're suggesting be done?*  It's not clear to me.  (Note that .Wait/GetResult()'ing on a delegate-backed Task is already able to execute that task on the current thread, subject to the whims of the associated TaskScheduler and that the Task hasn't yet begun executing.)

Separate from that, your proposal mentions Stream.Read/WriteAsync.  I'm well aware of the implementation, and I'm well aware of various Stream implementations that rely on the base behavior of simply queueing the call to Read/Write.  *Is your proposal actually to ensure that the task returned by such Stream.Read/WriteAsync methods can be inlined as discussed above, regardless of the implementation?*  That would have nothing to do with continuations, as the base implementation doesn't use continuations.  It likely wouldn't be too difficult to add some slight changes to the base implementation to enable that, but it wouldn't be done in the manners you suggest above.

I also don't understand in the Kestrel example you linked to why it's using WriteAsync at all... if the method is supposed to be synchronous, why doesn't it just call the synchronous Write?

**Comment by benaadams** [comment]
> Can you please elaborate what it is specific to continuations that you're suggesting be done?

Continuation might have been the wrong word to use as that means something else. I mean entirely within the scope of Async and doing a sync wait on an Async method. 

> I also don't understand in the Kestrel example you linked to why it's using WriteAsync at all... if the method is supposed to be synchronous, why doesn't it just call the synchronous Write?

There is no synchronous Write, there is only an async write that either completes immediately (if not too much is buffered); or uses a TCS to cause awaitable backpressure. The sync Write method then calls the Async method and does a `.GetAwaiter().GetResult()` on the returned task.

The main issue arises because the thread completing the tasks doesn't want the completion (other half of the await) running on it. For async tasks queuing the completion to the threadpool solves this, however for blocked tasks (.Wait/GetResult()) this is a bad approach and they can just be completed by that thread as they already have their own thread to run on (the one they have blocked).

Not sure there is a generalised solution. However, I may have found a specific solution for this use case (as its all internal). Would you be ok to review that when I've got something working?

**Comment by stephentoub** [comment]
> Would you be ok to review that when I've got something working?

Happy to.

> I mean entirely within the scope of Async and doing a sync wait on an Async method.

I see. Ok, thanks for the clarification.  I was confused by the terminology being used.

> however for blocked tasks (.Wait/GetResult()) this is a bad approach and they can just be completed by that thread as they already have their own thread to run on (the one they have blocked).

This is what I was alluding to earlier.  TPL already has a mechanism built-in that enables Wait/GetResult() to execute the task being waited on synchronously as part of the call to Wait/GetResult().  For that to happen, it requires the the Task have a delegate associated with it (e.g. it was created with Task.Run, Task.Factory.StartNew, etc.), that it be ready to run (e.g. if it was created with ContinueWith, the antecedent of that continuation needs to have already completed), that it not yet be executing, and that the associated TaskScheduler allows it to be executed (a call is made to TaskScheduler.TryExecuteInline).  

What I was saying related to Stream.Read/WriteAsync is that, although a task is created to execute the corresponding Read/Write method, the task that's returned from Read/WriteAsync isn't actually one backed by a delegate, so the aforementioned inlining doesn't work.  But I was also suggesting that I might be able to modify it address that.

**Comment by benaadams** [comment]
> What I was saying related to Stream.Read/WriteAsync is that, although a task is created to execute the corresponding Read/Write method, the task that's returned from Read/WriteAsync isn't actually one backed by a delegate, so the aforementioned inlining doesn't work.

Don't think that would help as its a TCS Task that gets triggered at some future point.

What I'm thinking of is a variant/custom TCS where `.GetAwaiter().GetResult()` will emit a new object that will be marked in the TCS as sync blocked (similar to how CTS and CancelationToken works) and when the TCS is completed it will trigger the sync blocked items directly and add the other Actions to the threadpool. Although it should be either sync blocked or awaited and not both.

Not fully thought it through though.

**Comment by stephentoub** [comment]
> Don't think that would help as its a TCS Task that gets triggered at some future point.

Correct, it would only help if you were Wait'ing on the delegate-backed Task.

> and when the TCS is completed it will trigger the sync blocked items directly and add the other Actions to the threadpool... Not fully thought it through though.

I'm still not understanding.  Are you saying that if you have:
```C#
t.GetAwaiter().GetResult();
Foo();
```
that when t is completed, you want the thread that's completing t to execute Foo() as part of its completion, similar to what would happen if the code were instead:
```C#
await t;
Foo();
```
?

**Comment by benaadams** [comment]
Simplified it would be more
```csharp

public override void Write(byte[] buffer, int offset, int count)
{
    WriteAsyncCore(buffer, offset, count, CancellationToken.None, isSync: true)
        .GetAwaiter().GetResult();
}

public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken token)
{
    return WriteAsyncCore(buffer, offset, count, CancellationToken.None, isSync: false);
}

private Task WriteAsyncCore(byte[] buffer, int offset, int count, CancellationToken token, bool isSync)
{
     var tcs = new TaskCompletionSource<object>();
     QueueWork(tcs, isSync);
     return tcs.Task;
}

private void WorkComplete(TaskCompletionSource<object> tcs, bool isSync)
{
    if (isSync)
    {
        tcs.TrySetResult(null);
    }
    else
    {
        ThreadPool.QueueUserWorkItem(
            o => ((TaskCompletionSource<object>)o).TrySetResult(null), 
            tcs);
    }
}
```
Then the thread calling WorkComplete wouldn't be running either what happens after the sync call (as it already has its own thread); or what happens after the async call, as its on the threadpool.

But the sync call won't use up 2 threads (one blocked and one for the notification)

Should work?

**Comment by stephentoub** [comment]
This might be simplified too much, as I'm still not getting it.  Sorry if I'm just being slow.

- If you're telling WriteAsyncCore in WriteAsync that work should be done synchronously, why doesn't WriteAsyncCore just do the work synchronously rather than queuing it?

- When a task completes, it already first queues an asynchronous invocations and then invokes any synchronous continuations, which includes setting an event that code calling GetResult is waiting on, so with what's already in place today, when code waits on a tcs.Task, it's going to wake up the moment the task completes (subject to OS scheduling), but it's not going to continue executing on the same thread that completed the task... it's already a separate thread.

What am I missing?  I still don't understand the problem being solved here.  In your code, assuming QueueWork is queueing a work item to do some work and isn't calling WorkComplete until that work is actually complete, then you've still go two threads involved: the thread blocked on GetResult and the thread performing the work.

**Comment by benaadams** [comment]
> If you're telling WriteAsyncCore in WriteAsync that work should be done synchronously, why doesn't WriteAsyncCore just do the work synchronously rather than queuing it?

Constraints. There are no synchronous writes; there are only writes with completion callbacks IOCP style.

There is a regular thread per core (non-thread pool); that are servicing all of the write requests and callbacks for all of the threadpool threads - when there is a completion they just want to activate a threadpool thread with the minimum amount of work and continue notifying other callbacks; or sending other data. 

The IO is bonded to that thread and no other thread can directly make an IO request otherwise it will fail; so it needs to add it to a queue for the IO thread to pick up.

> What am I missing? I still don't understand the problem being solved here

Will an `await`ed Task never continue on the thread that completes the await?

**Comment by stephentoub** [comment]
Ok, I think I understand now what you're trying to achieve. You want to prevent continuations from running on a specific thread completing a task, but you want to unblock synchronous waiters on that task without requiring an extra queued work item to do so, right?

**Comment by stephentoub** [comment]
> Will  MoreWork  ever run on the thread that calls  tcs.TrySetResult(null); 

It depends on the context/scheduler involved, but yes, it can.

**Comment by benaadams** [comment]
> You want to prevent continuations from running on a specific thread completing a task, but you want to unblock synchronous waiters on that task without requiring an extra queued work item to do so, right?

Yep; otherwise the synchronous unblock is clogging the threadpool unnecessarily; as its now using 2 threads. Whereas the async path only ever uses either one thread or zero.

Still scalability issues with using the blocking methods; but that's a different issue.

**Comment by stephentoub** [comment]
Until very recently, RunContinuationsAsynchronously gave you exactly the behavior you want.  Even though .Wait() is implemented internally via a form of continuation, it was a special internal continuation that would always be invoked synchronously.  https://github.com/dotnet/coreclr/pull/2026 was done because most of these special internal continuations have the potential to run arbitrary user code, and thus should be subject to RunContinuationsAsynchronously, however the one used by Wait() and a few others do not and need not be subject to RunContinuationsAsynchronously (they're internal implementation details that happen to use the continuation mechanism for memory reasons, perform only a known and small amount of work on each invocation, etc.)  I've submitted https://github.com/dotnet/coreclr/pull/2718 to distinguish the two cases; with that, you can create a RunContinuationsAsynchronously task, but no additional work item will be queued for code .Wait/Result/GetResult()'ing on the task.

**Comment by benaadams** [comment]
Thank you :+1:
