### ISSUE TITLE
Add a runtime configuration to disable diagnostics server

### ISSUE THREAD

**Issue by sywhang** [dotnet/coreclr#27134]
Currently the diagnostics server is always created and there is no way of configuring the runtime to not do this. We should add an optional config switch that allows users to disable creation of the diagnostics server thread entirely. 

cc @noahfalk @josalem

**Comment by noahfalk** [comment]
I'd recommend reusing the switch we already have: COMPLUS_EnableDiagnostics

@hoyosjs - this could also be used as a workaround to the performance issue you mentioned. I wasn't able to find it or I would I have linked it.

**Comment by noahfalk** [comment]
I think we should do this for 3.1. The implementation should be super-cheap and it is a good risk mitigation against future diagnostics server bugs we may discover.

**Comment by hoyosjs** [comment]
#26246 was the issue @duskembayev was seeing. After shutdown the pipe seems to linger doing ACL queries under a sandboxed scenario. This is exactly the fix he had tried but it was just never hooked to the check. #27137 fixes it, is there any way you can give this a try? Does this unblock you?

**Comment by sywhang** [comment]
Reopening for 3.1 port

**Comment by sywhang** [comment]
Fix has been merged to master. 3.1 port is here: #27140

**Comment by sywhang** [comment]
Closing as 3.1 port has been merged.
