### ISSUE TITLE
ARM64 intrinsics: Support Vector64<double>, Vector64<long>, and Vector64<ulong>

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#27154]
The ARM hardware supports several instructions that operate on `64x1_t` types. These effectively correspond to `Vector64<double>`, `Vector64<long>`, and `Vector64<ulong>` on the managed side.

However, the JIT does not currently handle these types appropriately and needs to be updated before the corresponding HWIntrinsics can be exposed.

category:implementation
theme:intrinsics
skill-level:intermediate
cost:medium

**Comment by tannergooding** [comment]
CC. @CarolEidt, @echesakovMSFT, @TamarChristinaArm

**Comment by echesakovMSFT** [comment]
I am going to take a look at this issue
