### ISSUE TITLE
Test Pri0 Linux x64 checked failed

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#27155]
PR testing is red, Linux x64 jobs are failing with:
```
/__w/1/s/.packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19463.3/tools/azure-pipelines/AzurePipelines.MultiQueue.targets(43,5): error : Request to https://dev.azure.com/dnceng/public/_apis/test/runs/11941794?api-version=5.0 returned failed status 503 Service Unavailable [/__w/1/s/tests/helixpublishwitharcade.proj]
/__w/1/s/.packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19463.3/tools/azure-pipelines/AzurePipelines.MultiQueue.targets(43,5): error :  [/__w/1/s/tests/helixpublishwitharcade.proj]
/__w/1/s/.packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19463.3/tools/azure-pipelines/AzurePipelines.MultiQueue.targets(43,5): error : {"$id":"1","innerException":null,"message":"TF10216: Azure DevOps services are currently unavailable. Try again later. Activity Id: 7a0bdde5-a2ae-47cc-bfda-b57cdac2d1ac","typeName":"Microsoft.VisualStudio.Services.CircuitBreaker.CircuitBreakerShortCircuitException, Microsoft.VisualStudio.Services.Common","typeKey":"CircuitBreakerShortCircuitException","errorCode":0,"eventId":3000} [/__w/1/s/tests/helixpublishwitharcade.proj]
##[error].packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19463.3/tools/azure-pipelines/AzurePipelines.MultiQueue.targets(43,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Request to https://dev.azure.com/dnceng/public/_apis/test/runs/11941794?api-version=5.0 returned failed status 503 Service Unavailable

{"$id":"1","innerException":null,"message":"TF10216: Azure DevOps services are currently unavailable. Try again later. Activity Id: 7a0bdde5-a2ae-47cc-bfda-b57cdac2d1ac","typeName":"Microsoft.VisualStudio.Services.CircuitBreaker.CircuitBreakerShortCircuitException, Microsoft.VisualStudio.Services.Common","typeKey":"CircuitBreakerShortCircuitException","errorCode":0,"eventId":3000}
```
examples: https://dev.azure.com/dnceng/public/_build/results?buildId=386209, https://dev.azure.com/dnceng/public/_build/results?buildId=386034&view=logs

**Comment by sandreenko** [comment]
PTAL @dotnet/coreclr-infra @dotnet/dnceng

**Comment by trylek** [comment]
I think it works now but we should still follow up to understand such outages and hopefully prevent them in the future (or at least clearly communicate them in case of maintenance outages and such); I hit the same issue myself in my yesterday PR.

**Comment by trylek** [comment]
Hmm, I spoke too soon, apparently it's still broken actually :-(.

**Comment by trylek** [comment]
Hmm, I spoke too soon, apparently it's still broken actually :-(.

**Comment by trylek** [comment]
@MattGal - this is apparently still happening on and off (on Saturday it was malfunctioning, on Sunday it was fine, earlier today one of my lab runs passed fine but the second one is on the floor). Are you the right person to take a look? This is my latest WIP Crossgen2 run that hit this several hours back:

https://dev.azure.com/dnceng/public/_build/results?buildId=386987

**Comment by mmitche** [comment]
@ilyas1974 @dotnet/dnceng since @MattGal is out of town.

**Comment by riarenas** [comment]
Filed https://github.com/dotnet/arcade/issues/4113 so that we can investigate this.

**Comment by sandreenko** [comment]
@mikedn  @franksinankaya we have a ci issue that makes all PR red, I will restart testing on your PRs manually once it is fixed.

**Comment by jashook** [comment]
@sandreenko thank you for opening the issue

**Comment by jkotas** [comment]
This is fixed now.
