### ISSUE TITLE
GetDelegateForFunctionPointer should allow generic types which have all parameters set

### ISSUE THREAD

**Issue by hamarb123** [dotnet/coreclr#27168]
When you call `Marshal.GetDelegateForFunctionPointer(IntPtr, Type)`, it does a series of checks to ensure your parameters are valid and make sense (see [Marshal.cs](https://github.com/dotnet/corefx/blob/d58a51f911efb3c98beca21b6cf08cc703424fdf/src/Common/src/CoreLib/System/Runtime/InteropServices/Marshal.cs#L857)).
But one of these checks does not make complete sense, the check I am talking about is:
```cs
if (t.IsGenericType)
{
    throw new ArgumentException(SR.Argument_NeedNonGenericType, nameof(t));
}
```
My problem with this check is that the code should work on constructed generic types (eg. `Action<int>` instead of `Action<T>`), and it does if you write some code that directly uses `GetDelegateForFunctionPointerInternal(IntPtr, Type)` (shown at the bottom of this issue), but the public member `GetDelegateForFunctionPointer(IntPtr, Type)` does not allow it as it checks if it is a generic type.

Here is what the check should be:
```cs
if (t.IsGenericType && !t.IsConstructedGenericType)
{
    throw new ArgumentException(SR.Argument_NeedNonGenericType, nameof(t));
}
```
The reason this is annoying to me is that I have some code that needs to be able to dynamically load a native function with a delegate specified on the go and they are always either a `Func` or an `Action` (usually with generic parameters); I cannot do this without either using my workaround which could break if `GetDelegateForFunctionPointerInternal` is renamed or the suggested change to Marshal.cs.

Here is some sample code that should work:
```cs
[DllImport("kernel32", CharSet = CharSet.Unicode)]
public static extern IntPtr LoadLibrary(string fileName);
  
[DllImport("kernel32", CharSet = CharSet.Ansi)]
public static extern IntPtr GetProcAddress(IntPtr module, string procName);

...

var x = Marshal.GetDelegateForFunctionPointer<Func<uint, uint, int>>(GetProcAddress(LoadLibrary("kernel32.dll"), "Beep"));
x(440, 1000);
```
But it throws the following error: `System.ArgumentException: 'The specified Type must not be a generic type definition. '`, so here is my current solution
```cs
[DllImport("kernel32", CharSet = CharSet.Unicode)]
public static extern IntPtr LoadLibrary(string fileName);
  
[DllImport("kernel32", CharSet = CharSet.Ansi)]
public static extern IntPtr GetProcAddress(IntPtr module, string procName);

...

var x = (Func<uint, uint, int>)GetDelegateForFunctionPointerFix(GetProcAddress(LoadLibrary("kernel32.dll"), "Beep"), typeof(Func<uint, uint, int>));
x(440, 1000);
```

So basically, all I want to change is in [Marshal.cs](https://github.com/dotnet/corefx/blob/d58a51f911efb3c98beca21b6cf08cc703424fdf/src/Common/src/CoreLib/System/Runtime/InteropServices/Marshal.cs#L871 from `if (t.IsGenericType)` to `t.IsGenericType && !t.IsConstructedGenericType`

My current solution:
```cs
private static Func<IntPtr, Type, Delegate> GetDelegateForFunctionPointerInternalPointer;
public static Delegate GetDelegateForFunctionPointerFix(IntPtr ptr, Type t)
{
    //Validate the parameters (modified from https://referencesource.microsoft.com/#mscorlib/system/runtime/interopservices/marshal.cs)
    if (ptr == IntPtr.Zero)
    {
        throw new ArgumentNullException(nameof(ptr));
    }

    if (t is null)
    {
        throw new ArgumentNullException(nameof(t));
    }
	
    //skip the IsRuntimeImplemented check as IsRuntimeImplemented is not visible and I cannot be bothered
	
    if (t.IsGenericType && !t.IsConstructedGenericType)
    {
        throw new ArgumentException("The specified Type must not be an open generic type definition.", nameof(t));
    }

    Type? c = t.BaseType;
    if (c != typeof(Delegate) && c != typeof(MulticastDelegate))
    {
        throw new ArgumentException("Type must derive from Delegate or MulticastDelegate.", nameof(t));
    }
	
    if (GetDelegateForFunctionPointerInternalPointer is null)
    {
        GetDelegateForFunctionPointerInternalPointer = (Func<IntPtr, Type, Delegate>)typeof(Marshal).GetMethod("GetDelegateForFunctionPointerInternal", BindingFlags.Static | BindingFlags.NonPublic).MakeDelegate(null);
    }

    return GetDelegateForFunctionPointerInternalPointer(ptr, t);
}
```

Tested on .NET Core 3.0 on Windows 10 x64 (running as AnyCPU though).
If there are any issues/problems with this idea, please let me know!

**Comment by jkotas** [comment]
>If there are any issues/problems with this idea, please let me know!

If you are using private reflection to hack on the runtime internals, you are in 100% unsupported territory. There are know cases where the generic delegates do not work as expected for interop. 

Fixing this properly is tracked by https://github.com/dotnet/coreclr/issues/25973
