### ISSUE TITLE
Apply new GC suppression attribute

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/coreclr#27185]
Once https://github.com/dotnet/corefx/issues/40740 is completed, the new API should be applied to the following APIs:

[Interop.GetCurrentProcessId](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/Interop/Windows/Kernel32/Interop.GetCurrentProcessId.cs)
[Interop.GetCurrentThreadId](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/Interop/Windows/Kernel32/Interop.GetCurrentThreadId.cs)
[Interop.GetStdHandle](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/Interop/Windows/Kernel32/Interop.GetStdHandle.cs)
[Interop.SetThreadErrorMode](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/Interop/Windows/Kernel32/Interop.SetThreadErrorMode.cs)

All instances of the previous attribute name should be updated as well - see https://github.com/dotnet/coreclr/pull/26458.

**Comment by AaronRobinsonMSFT** [comment]
@GrabYourPitchforks Let me know if you want me to apply the new suppress GC attribute to anything for you.

**Comment by AaronRobinsonMSFT** [comment]
@JeremyKuhne I will be applying this functionality to the above functions in SPCL when the API review is complete. Feel free to add to the list here if you have APIs in SPCL to also consider.

**Comment by JeremyKuhne** [comment]
> Feel free to add to the list here if you have APIs in SPCL to also consider.

Nothing else sticks out in SPCL.

**Comment by GrabYourPitchforks** [comment]
I can't think offhand of any areas of ownership I have in coreclr / corefx that might benefit from this. Might just need to find all `DllImportAttribute` instances and take a look.

**Comment by JeremyKuhne** [comment]
To be clear- I have a number of candidates, but they're not in SPCL. :)

**Comment by danmosemsft** [comment]
It will only be respected within corelib?

**Comment by jkotas** [comment]
It will be available everywhere once it is approved as public API: https://github.com/dotnet/corefx/issues/40740
