### ISSUE TITLE
Failed to load CoreCLR.dll

### ISSUE THREAD

**Issue by Cr4zyPh1l** [dotnet/coreclr#2721]
Hello,

I've compiled the .Net CoreCLR for Windows x64 in Debug and Release.
I've tried it with the corerun.exe application, but I've got an error.

 HOSTLOG: Host directory: C:\Users\A\Desktop\Demo\
 HOSTLOG: Attempting to load: C:\Users\A\Desktop\Demo\CoreCLR.dll
 HOSTLOG: Failed to load: C:\Users\A\Desktop\Demo\CoreCLR.dll
 HOSTLOG: Error code: 193
 HOSTLOG: Attempting to load: C:\Users\A\Desktop\Demo\CoreCLR.dll
 HOSTLOG: Failed to load: C:\Users\A\Desktop\Demo\CoreCLR.dll
 HOSTLOG: Error code: 193
 HOSTLOG: Attempting to load: C:\Windows\system32\CoreCLR.dll
 HOSTLOG: Failed to load: C:\Windows\system32\CoreCLR.dll
 HOSTLOG: Error code: 126
 HOSTLOG: Unable to load CoreCLR.dll
 HOSTLOG: Loading: [Application Path]\application.exe
 HOSTLOG: Unable to load CoreCLR.dll
 HOSTLOG: Execution failed

Please tell me how to correct it.

Regards

Phil

**Comment by Cr4zyPh1l** [comment]
Hello,
I've forgotten to say my OS, Windows 7 x64

and CoreCLR compiled with Visual Studio 2015

Regards

Phil

**Comment by janvorli** [comment]
@Cr4zyPh1l The error 193 means "bad exe format". It looks as if the CoreCLR.dll or the corerun.exe was 32 bit version, so a 32 bit corerun would be trying to load a 64 bit coreclr or vice versa.
Would you be able to post C:\Users\A\Desktop\Demo\CoreCLR.dll and corerun.exe (from whatever place you run it) somewhere so that I can inspect them?
Another idea - I wonder if it could be the case when you have some other corerun.exe on your PATH and it gets loaded instead the one you are trying to run. Can you try to specify full page to the corerun.exe when running it?

**Comment by Cr4zyPh1l** [comment]
Hello,

I've compiled only 64 bit version (target x64 in build.cmd command), so I don't think that is the problem.

Moreover, I have no other corerun.exe in my PATH, and when I have tried to launch corerun.exe from his full path, it have generated the same error.

Well, I use the api-ms*** to try to launch the corerun, perhaps there is a cpu target problem (x86 instead of x64); by the way, would there a answer to avoid these libraries.

Thank you

Regards

Phil
[CoreRunAndCoreCLR.zip](https://github.com/dotnet/coreclr/files/95036/CoreRunAndCoreCLR.zip)

**Comment by janvorli** [comment]
@Cr4zyPh1l As you've expected, the exe / dll are both ok, both 64 bit flavor. So let's try to shift focus on the way you launch corerun.exe. Can you tell me how exactly you are trying to launch it?

**Comment by Cr4zyPh1l** [comment]
Hello,

To launch it, I do a "cd" to the directory where are my files (coreclr.dll, api-ms**.dll, corerun.exe, mscorlib.dll and my application), and I type "corerun.exe /v Application.exe"

I've try to compile and run an x86 version of the coreCLR, and it load it. So, maybe it the api-ms** which are only in x86. For more, I would like to avoid this api-ms**.dll, is it possible ?

But, I get another error, :

HOSTLOG: Host directory: C:\Users\A\Desktop\Demo\32\
HOSTLOG: Attempting to load: C:\Users\A\Desktop\Demo\CoreCLR.dll
HOSTLOG: Failed to load: C:\Users\A\Desktop\Demo\CoreCLR.dll
HOSTLOG: Error code: 193
HOSTLOG: Attempting to load: C:\Users\A\Desktop\Demo\32\CoreCLR.dll
HOSTLOG: Loaded: C:\Users\A\Desktop\Demo\32\CoreCLR.dll
HOSTLOG: Loading: [Application.exe]
 HOSTLOG: Finding GetCLRRuntimeHost(...)
 HOSTLOG: Calling GetCLRRuntimeHost(...)
 HOSTLOG: Setting ICLRRuntimeHost2 startup flags
 HOSTLOG: Server GC enabled: false
 HOSTLOG: Concurrent GC enabled: true
 HOSTLOG: Starting ICLRRuntimeHost2
 HOSTLOG: Failed to start CoreCLR. ERRORCODE: 0x80004005/E_FAIL
 HOSTLOG: Execution failed

Thank you for your help

Regards,

Phil

**Comment by janvorli** [comment]
@Cr4zyPh1l The error you are getting with x86 is most likely due to the mscorlib.dll not matching the coreclr.dll. That can be caused by the coreclr.dll being release build and the mscorlib.dll being debug one or vice versa. Or due to the mscorlib.dll being an amd64 build.

**Comment by Cr4zyPh1l** [comment]
Ok, I haven't compiled the mscorlib.dll, I'm doing this, and I try. But, normally, mscorlib is not MSIL code ? So, it must work on AnyCPU ?

**Comment by janvorli** [comment]
mscorlib is managed code, but it is tightly bound to the coreclr.dll. Some objects shared between those two have size and layout dependent on the architecture and debug / release build (imagine e.g. a shared object that has some additional fields for debugging purposes for debug build).

**Comment by Cr4zyPh1l** [comment]
Ok, I haven't tested yet because I have some problems with package downloading, but when I can, I will test. Nonetheless, I would like to know if I can use the mscorlib.dll from the "classic" Microsoft .Net Framework (and if yes, which version) with the coreCLR. If it's not the case, what are the differences between the two of them. And, I insist maybe, but can we don't use api-ms**.dll ? I'm asking you these precise questions because I've seen, in your profile, that you work at Microsoft.

Regards,

Phil

**Comment by janvorli** [comment]
@Cr4zyPh1l You cannot use mscorlib.dll from the full desktop .Net. While they share most of the source code base, there are parts that are different and the interface between the mscorlib.dll and the coreclr.dll has some different stuff. Also the sizes and layout of some objects shared between mscorlib.dll and the coreclr.dll are different.
@stephentoub, are there some additional differences that I have not mentioned?

Regarding your question
> And, I insist maybe, but can we don't use api-ms**.dll?

I am not sure I understand what you mean.

**Comment by Cr4zyPh1l** [comment]
Ok, so I must recompile an application to target the CoreCLR's mscorlib, and run on it ? Or I can keep the application and just change mscorlib file ? For more, do you know a link, or a datasheet, to the inner workings of the full desktop .Net, and especially its launching (for example, application call _CorExeMain function from mscoree.dll, which call another function, etc... until the managed program main function) ? 

To execute the corerun.exe, and of course load the coreCLR, I had to put some "extra" dlls in its folder. these dlls have a name starting with "api-ms-win-", I've understood that they contains some functions from another system (Win 8) for compatibility with windows 7. Because I think this could be the source of my first problem.

Regards

Phil

**Comment by janvorli** [comment]
Regarding the application targetting CoreCLR, you need to build it against reference assemblies of the core profile. That ensures that it doesn't reference functionality that is not present in the core profile supported by the CoreCLR.

The api-ms-win* have a slightly different purpose from what you expect. They are just forwarding API calls to the actual dlls that implement them (you can view it as an indirection for the dynamic linker). There is no code in these dlls. See the article below for a detailed description:
https://msdn.microsoft.com/en-us/library/windows/desktop/hh802935(v=vs.85).aspx

**Comment by Cr4zyPh1l** [comment]
Ok, so my second problem could come from my application which isn't built with CoreCLR reference ? It's a simple application which just show a message in the console.

Do you know where I can get a list of differences between features supported in the full desktop .Net Runtime and not in CoreCLR (and the opposite) ?

In conclusion, I can't delete these references (api-ms**) ?

And, do you have a datasheet, or link to the internal running of the full .Net (as I said before, mainly on its start-up) ?

Thank you for your help, and sorry to reply late, it's time difference.

Phil

**Comment by Cr4zyPh1l** [comment]
It works, almost for the x86 architecture. I have compiled the CoreCLR mscorlib, and launch my application successfully.

I think my first problem is about the api-ms** dlls which are x86 DLLs (I'm not sure if it the case). Could it be ?

Thank you for help

Phil
