### ISSUE TITLE
CoreCLR failed to build due to error MSB3246 with MSVC on windows.

### ISSUE THREAD

**Issue by spacelg** [dotnet/coreclr#27258]
We tried to build CoreCLR and it failed to build due to error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible with MSVC on windows. It can be reproduced on latest  revision fd0ca05. But it can be build pass on 1ced1af. It should be a CoreCLR source issue. Could you look at this issue? Thanks a lot.

Repro steps:
1.git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2.Open a clean x86 prompt and browse to D:\CoreCLR\src
3.build x86 release -- /clp:ShowCommandLine

[log_x86_build.zip](https://github.com/dotnet/coreclr/files/3737807/log_x86_build.zip)

Error info:
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Base-Util-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Core-Kernel32-Private-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Core-Kernel32-Private-L1-1-1.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Core-Kernel32-Private-L1-1-2.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Core-PrivateProfile-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Core-ProcessTopology-Obsolete-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Core-String-L2-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Core-StringAnsi-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-EventLog-Legacy-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Eventing-ClassicProvider-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Eventing-Consumer-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Eventing-Controller-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Eventing-Legacy-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Eventing-Provider-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-Security-LsaPolicy-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-devices-config-L1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\API-MS-Win-devices-config-L1-1-1.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\api-ms-win-core-com-l1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\api-ms-win-core-com-private-l1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\api-ms-win-core-comm-l1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\api-ms-win-core-console-l1-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]
D:\CoreCLR\src\.dotnet\sdk\3.0.100-preview7-012821\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Assembly file 'D:\CoreCLR\src\.packages\microsoft.dotnet.coreclr.testdependencies\1.0.0-prerelease\lib\aspnetcore50\api-ms-win-core-console-l2-1-0.dll' could not be opened -- PE image doesn't contain managed metadata. [D:\CoreCLR\src\tests\src\Common\test_runtime\test_runtime.csproj]

**Comment by jashook** [comment]
Dup of https://github.com/dotnet/coreclr/issues/27258
