### ISSUE TITLE
Fix AppContext locking on 2 different objects

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/coreclr#2727]
A similar fix to the one in [CoreFx](https://github.com/dotnet/corefx/pull/5517) needs to be made here.

@JonHanna let me know if you want to make the same change here as well, otherwise I'll go ahead and do it.

**Comment by JonHanna** [comment]
Sure, I'll push it here in two minutes.

**Comment by AlexGhiondea** [comment]
This has been ported.
