### ISSUE TITLE
Problem cross compiling for Android

### ISSUE THREAD

**Issue by maveilleux** [dotnet/coreclr#27287]
Hello,
I try to cross compile for Android and I am getting when running the build.sh script. 
Running the command `CONFIG_DIR='realpath cross/android/arm64' ROOTFS_DIR='realpath /media/ubuntu/Android_1804/netcore2/coreclr/cross/android-rootfs/toolchain/arm64/sysroot' ./build.sh cross arm64 skipgenerateversion skipnuget cmakeargs -DENABLE_LLDBPLUGIN=0 cmakeargs -DFEATURE_EVENT_TRACE=0 cmakeargs -DFEATURE_EVENT_TRACE=0` and I am getting the following output:
`Commencing CoreCLR Repo build
__DistroRid: android.21-arm64
__RuntimeId: android.21-arm64
Setting up directories for build
Checking prerequisites...
Laying out dynamically generated EventSource classes
Commencing build of CoreCLR component for Linux.arm64.Debug in /media/ubuntu/Android_1804/netcore2/coreclr/bin/obj/Linux.arm64.Debug
Invoking "/media/ubuntu/Android_1804/netcore2/coreclr/src/pal/tools/find-clang.sh" 3 "9"
Invoking "/media/ubuntu/Android_1804/netcore2/coreclr/src/pal/tools/gen-buildsys.sh" "/media/ubuntu/Android_1804/netcore2/coreclr" "/media/ubuntu/Android_1804/netcore2/coreclr/bin/obj/Linux.arm64.Debug" arm64 Debug   -DCLR_CMAKE_TARGET_OS=Linux -DCLR_CMAKE_PACKAGES_DIR=/media/ubuntu/Android_1804/netcore2/coreclr/.packages -DCLR_CMAKE_PGO_INSTRUMENT=0 -DCLR_CMAKE_OPTDATA_VERSION=99.99.99-master-20190716.1 -DCLR_CMAKE_PGO_OPTIMIZE=1  -DENABLE_LLDBPLUGIN=0 -DFEATURE_EVENT_TRACE=0
loading initial cache file /media/ubuntu/Android_1804/netcore2/coreclr/cross/android/arm64/tryrun.cmake
CMake Error: The source directory "/media/ubuntu/Android_1804/netcore2/coreclr/bin/obj/Linux.arm64.Debug" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Failed to generate CoreCLR component build project!`

The folder `/media/ubuntu/Android_1804/netcore2/coreclr/bin/obj` constains the files ibcoptdataversion.txt, optdataversion.txt and version.c, but the file CMakeLists.txt is not present.

I am missing some tool on the host machine?

I am running this command on a Ubuntu 18.04 64 bits computer.

Thank you

**Comment by jeffschwMSFT** [comment]
cc @janvorli @jashook

**Comment by janvorli** [comment]
@maveilleux after a change that came in today or yesterday, it is required to use cmake version 3.14 or higher. I've hit this misleading error message myself today. It happens due to the fact that the build is now using a new command line option that was not present before and old cmake misinterprets the command line.
@jkoritzinsky said he'll add checking cmake version to the build scripts and print a meaningful error message instead.

**Comment by maveilleux** [comment]
It corrected that issue.
It now fails with this error message:
`loading initial cache file /media/ubuntu/Android_1804/netcore2/coreclr/cross/android/arm64/tryrun.cmake
-- The C compiler identification is Clang 3.8.275480
-- The CXX compiler identification is Clang 3.8.275480
-- Check for working C compiler: /media/ubuntu/Android_1804/netcore2/coreclr/cross/android-rootfs/toolchain/arm64/bin/aarch64-linux-android-clang
-- Check for working C compiler: /media/ubuntu/Android_1804/netcore2/coreclr/cross/android-rootfs/toolchain/arm64/bin/aarch64-linux-android-clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /media/ubuntu/Android_1804/netcore2/coreclr/cross/android-rootfs/toolchain/arm64/bin/aarch64-linux-android-clang++
-- Check for working CXX compiler: /media/ubuntu/Android_1804/netcore2/coreclr/cross/android-rootfs/toolchain/arm64/bin/aarch64-linux-android-clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang
-- Found assembler: /media/ubuntu/Android_1804/netcore2/coreclr/cross/android-rootfs/toolchain/arm64/bin/aarch64-linux-android-clang
-- Performing Test COMPILER_SUPPORTS_F_ALIGNED_NEW
-- Performing Test COMPILER_SUPPORTS_F_ALIGNED_NEW - Failed
Detected Linux ARM64
CMake Error at configuretools.cmake:19 (message):
  Unable to find llvm tool for: ar.
Call Stack (most recent call first):
  configuretools.cmake:23 (locate_llvm_exec)
  CMakeLists.txt:115 (include)


-- Configuring incomplete, errors occurred!
See also "/media/ubuntu/Android_1804/netcore2/coreclr/bin/obj/Linux.arm64.Debug/CMakeFiles/CMakeOutput.log".
See also "/media/ubuntu/Android_1804/netcore2/coreclr/bin/obj/Linux.arm64.Debug/CMakeFiles/CMakeError.log".
Failed to generate CoreCLR component build project!`

It looks like the executable llvm-ar is not present on Android NDK r14. I will try to use a more recent NDK that has that executable.

**Comment by janvorli** [comment]
> It looks like the executable llvm-ar is not present on Android NDK r14

The build doesn't need tools from the Android NDK. The llvm-ar is missing in your host OS. Most likely the llvm-dev package is not installed.

**Comment by maveilleux** [comment]
Thank you, the llvm package was not completely installed on my host OS.
I now get the error below. What can be the cause of it.

Thank you

```
Commencing CoreCLR Repo build
__DistroRid: android.21-arm64
__RuntimeId: android.21-arm64
Setting up directories for build
Checking prerequisites...
Laying out dynamically generated EventSource classes
Commencing build of CoreCLR component for Linux.arm64.Debug in /media/ubuntu/Android_1804/netcore2/coreclr/bin/obj/Linux.arm64.Debug
Invoking "/media/ubuntu/Android_1804/netcore2/coreclr/src/pal/tools/find-clang.sh" 3 "9"
Invoking "/media/ubuntu/Android_1804/netcore2/coreclr/src/pal/tools/gen-buildsys.sh" "/media/ubuntu/Android_1804/netcore2/coreclr" "/media/ubuntu/Android_1804/netcore2/coreclr/bin/obj/Linux.arm64.Debug" arm64 Debug   -DCLR_CMAKE_TARGET_OS=Linux -DCLR_CMAKE_PACKAGES_DIR=/media/ubuntu/Android_1804/netcore2/coreclr/.packages -DCLR_CMAKE_PGO_INSTRUMENT=0 -DCLR_CMAKE_OPTDATA_VERSION=99.99.99-master-20190716.1 -DCLR_CMAKE_PGO_OPTIMIZE=1  -DENABLE_LLDBPLUGIN=0 -DFEATURE_EVENT_TRACE=0
loading initial cache file /media/ubuntu/Android_1804/netcore2/coreclr/cross/android/arm64/tryrun.cmake
Detected Linux ARM64
PGO data file NOT found: /media/ubuntu/Android_1804/netcore2/coreclr/.packages/optimization.linux-arm64.pgo.coreclr/99.99.99-master-20190716.1/data/clrjit.profdata
PGO data file NOT found: /media/ubuntu/Android_1804/netcore2/coreclr/.packages/optimization.linux-arm64.pgo.coreclr/99.99.99-master-20190716.1/data/coreclr.profdata
-- Configuring done
CMake Error at src/gc/CMakeLists.txt:95 (add_dependencies):
  The dependency target "eventing_headers" of target "clrgc" does not exist.


CMake Error at src/utilcode/CMakeLists.txt:136 (add_dependencies):
  The dependency target "eventing_headers" of target "utilcode" does not
  exist.


CMake Error at src/utilcode/CMakeLists.txt:138 (add_dependencies):
  The dependency target "eventing_headers" of target "utilcodestaticnohost"
  does not exist.


CMake Error at src/utilcode/CMakeLists.txt:137 (add_dependencies):
  The dependency target "eventing_headers" of target "utilcode_crossgen" does
  not exist.


CMake Error at src/utilcode/CMakeLists.txt:135 (add_dependencies):
  The dependency target "eventing_headers" of target "utilcode_dac" does not
  exist.


CMake Error at src/vm/CMakeLists.txt:924 (add_dependencies):
  The dependency target "eventing_headers" of target "cee_dac" does not
  exist.


CMake Error at src/vm/wks/CMakeLists.txt:16 (add_dependencies):
  The dependency target "eventing_headers" of target "cee_wks" does not
  exist.


CMake Error at src/debug/daccess/CMakeLists.txt:42 (add_dependencies):
  The dependency target "eventing_headers" of target "daccess" does not
  exist.


CMake Error at src/debug/ee/dac/CMakeLists.txt:9 (add_dependencies):
  The dependency target "eventing_headers" of target "cordbee_dac" does not
  exist.


CMake Error at src/debug/ee/wks/CMakeLists.txt:41 (add_dependencies):
  The dependency target "eventing_headers" of target "cordbee_wks" does not
  exist.


CMake Error at src/debug/di/CMakeLists.txt:83 (add_dependencies):
  The dependency target "eventing_headers" of target "cordbdi" does not
  exist.


CMake Error at src/strongname/api/CMakeLists.txt:28 (add_dependencies):
  The dependency target "eventing_headers" of target "strongname_wks" does
  not exist.


CMake Error at src/strongname/api/CMakeLists.txt:32 (add_dependencies):
  The dependency target "eventing_headers" of target "strongname_crossgen"
  does not exist.


CMake Error at src/strongname/api/CMakeLists.txt:23 (add_dependencies):
  The dependency target "eventing_headers" of target "strongname_dac" does
  not exist.


CMake Error at src/binder/CMakeLists.txt:102 (add_dependencies):
  The dependency target "eventing_headers" of target "v3binder_crossgen" does
  not exist.


CMake Error at src/binder/CMakeLists.txt:96 (add_dependencies):
  The dependency target "eventing_headers" of target "v3binder" does not
  exist.


CMake Error at src/classlibnative/bcltype/CMakeLists.txt:19 (add_dependencies):
  The dependency target "eventing_headers" of target "bcltype" does not
  exist.


CMake Error at src/classlibnative/float/CMakeLists.txt:15 (add_dependencies):
  The dependency target "eventing_headers" of target "comfloat_wks" does not
  exist.


CMake Error at src/vm/crossgen/CMakeLists.txt:272 (add_dependencies):
  The dependency target "eventing_headers" of target "mscorlib_crossgen" does
  not exist.


CMake Error at src/vm/crossgen/CMakeLists.txt:263 (add_dependencies):
  The dependency target "eventing_headers" of target "cee_crossgen" does not
  exist.


CMake Error at src/unwinder/CMakeLists.txt:24 (add_dependencies):
  The dependency target "eventing_headers" of target "unwinder_wks" does not
  exist.


CMake Error at src/unwinder/CMakeLists.txt:33 (add_dependencies):
  The dependency target "eventing_headers" of target "unwinder_dac_amd64"
  does not exist.


CMake Error at src/unwinder/CMakeLists.txt:28 (add_dependencies):
  The dependency target "eventing_headers" of target "unwinder_dac" does not
  exist.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Failed to generate CoreCLR component build project!
```

**Comment by jashook** [comment]
@maveilleux our build system has been changing significantly lately. The issue you have shown seems difficult to explain the problem. Before looking further into it is this still the same failure mode?

**Comment by maveilleux** [comment]
When compiling I had the issue describe in  #15687 . I added the `cmakeargs -DFEATURE_EVENT_TRACE=0` argument, as suggested by @jkotas. This removes the module `eventing_headers` from being compiled. It seems that this module is required by others.
I switched to using the tag v2.2.7 and I was able to compile.

**Comment by jashook** [comment]
Cool thanks for the quick response and explanation on how this was resolved.. Closing this issue.
