### ISSUE TITLE
[JitStress] JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests fails

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#27289]
It fails on different platforms with JitStress mode with:
FAILURE (AllocateSimpleClassesAndEQCompareThem): unexpected allocation of 48 bytes

The simplest platform is Windows_NT x64 Checked jitstress2_tiered @ Windows.10.Amd64.Open,
[example](https://dev.azure.com/dnceng/public/_build/results?buildId=392704&view=ms.vss-test-web.build-test-results-tab&runId=12202734&paneView=debug).

[The last successful run](https://dev.azure.com/dnceng/public/_build/results?buildId=387947) 10-14,
[the first failed run](https://dev.azure.com/dnceng/public/_build/results?buildId=389381) 10-15.

**Comment by sandreenko** [comment]
@erozenfeld could you please take a look?

**Comment by erozenfeld** [comment]
Fixed by #27344 .
