### ISSUE TITLE
CscBench test failing spuriously

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#2728]
Test case tests\src\JIT\Performance\CodeQuality\Roslyn\CscBench.cs seems to be failing in the CI spuriously.  I think I remember seeing this on both Windows and Linux, but the only examples I can find are on Ubuntu, so perhaps assume it is Linux-specific for now.

**From Andy:**
I wonder if it’s some kind of race condition or similar setting up the overlay test directory. I noticed in the past that it was easy to end up with different resolved versions in the various project.json files and when the overlay processing goes to flatten all these into one directory, I wonder if sometimes (or just on some machines, or just on Ubuntu, etc) it ends up with a different set of implementation assemblies.

It feels like either we should head towards having all tests in CoreCLR share a single project.json so we can’t have version mismatches like this, or have one overlay directory per project.json, or may be do something else to keep things straight.

**Examples of (probably) spurious failures:**
 http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_ubuntu_tst_prtest/969/testReport/junit/JIT.Performance.CodeQuality.Roslyn/CscBench/CscBench/
 http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_ubuntu_tst_prtest/971/testReport/junit/JIT.Performance.CodeQuality.Roslyn/CscBench/CscBench/

**Sample output from CI:**
MESSAGE:
BEGIN EXECUTION /mnt/j/workspace/dotnet_coreclr/release_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/corerun CscBench.exe libust[34441/34441]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup_local_apps() at lttng-ust-comm.c:305) Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.AddSyntaxTrees(IEnumerable`1 trees) at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(String assemblyName, CSharpCompilationOptions options, IEnumerable`1 syntaxTrees, IEnumerable`1 references, CSharpCompilation previousSubmission, Type returnType, Type hostObjectType, Boolean isSubmission) at CscBench.CompileBench() at CscBench.Main() ./CscBench.sh: line 55: 34441 Aborted (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" CscBench.exe $CLRTestExecutionArguments $Host_Args Expected: 100 Actual: 134 END EXECUTION - FAILED
+++++++++++++++++++
STACK TRACE:

**Comment by AndyAyersMS** [comment]
Failures mostly (exclusively?) happen on dci-ub-fbld-2.

**Comment by ellismg** [comment]
We hit similar things a while back in CoreFX where we constructed a test overlay by doing complicated find magic.  I found that the order of enumeration of the FS would differ across machines and so we'd actually end up copying different files due to our last one wins strategy.

**Comment by AndyAyersMS** [comment]
Was curious why the closely related `managed\Compilation` test didn't hit this issue. Turns out it's excluded in the "unsupported outside windows list".

I hate to just disable this test too, but it is causing enough spurious failures that it seems that is the sensible thing to do.

**Comment by RussKeldorph** [comment]
@wtgodbe Can you take this?  We either need to fix runtest.sh or start enforcing a compatible pattern that tests must follow (such as a single common version of each assembly).

**Comment by wtgodbe** [comment]
@RussKeldorph I can take a crack, but I may need a bit of help. @ellismg could you elaborate a bit on what you meant here?

> The problem with #2728 is due to how you build out your test runtime folders. As @AndyAyersMS on certain machines we enumerate directories differently and can end up copying over different versions of System.Runtime.dll which can cause bind errors if an older version is copied instead of a newer one.

> @RussKeldorph Is there someone from your team who owns the end-to-end testing process? You should probably move away from the find magic here https://github.com/dotnet/coreclr/blob/master/tests/runtest.sh#L334. One option would be to restore a specific project.json file with the newest versions of your dependencies and copy the output of that instead to the overlay (we do something similar in CoreFX with the "test-runtime"). If there's someone that better understands exactly what you need to do for setup they can probably fix this faster than me.

**Comment by sergiy-k** [comment]
I think the wrong version of System.Runtime gets copied from the Linux.AnyCPU.Debug\RemoteExecutorConsoleApp folder.
@wtgodbe, excluding this folder from the search path can be used as short term workaround until you implement a proper fix.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/3241 here's a workaround as suggested by @sergiy-k, for now.

**Comment by stephentoub** [comment]
CscBench failed here, though it looks like with a different failure:
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/checked_ubuntu_tst_prtest/908/consoleFull
```
21:15:22 FAILED   - JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh
21:15:22                BEGIN EXECUTION
21:15:22                /mnt/j/workspace/dotnet_coreclr/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun CscBench.exe
21:15:22                
21:15:22                Unhandled Exception: System.TypeInitializationException: The type initializer for 'SHA1' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
21:15:22                Parameter name: type
21:15:22                   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
21:15:22                   at Roslyn.Utilities.PortableShim.SHA1..cctor()
21:15:22                   --- End of inner exception stack trace ---
21:15:22                   at Roslyn.Utilities.SHA1CryptoServiceProvider..ctor()
21:15:22                   at Microsoft.CodeAnalysis.CryptographicHashProvider.ComputeSha1(Byte[] bytes)
21:15:22                   at Microsoft.CodeAnalysis.AssemblyIdentity.CalculatePublicKeyToken(ImmutableArray`1 publicKey)
21:15:22                   at Microsoft.CodeAnalysis.AssemblyIdentity.get_PublicKeyToken()
21:15:22                   at Microsoft.Cci.MetadataWriter.AssemblyReferenceComparer.GetHashCode(IAssemblyReference reference)
21:15:22                   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
21:15:22                   at Microsoft.Cci.MetadataWriter.HeapOrReferenceIndex`1.AddItem(T item, Int32 index)
21:15:22                   at Microsoft.Cci.MetadataWriter.HeapOrReferenceIndexBase`1.Add(T item)
21:15:22                   at Microsoft.Cci.MetadataWriter.HeapOrReferenceIndexBase`1.GetOrAdd(T item)
21:15:22                   at Microsoft.Cci.MetadataWriter.CreateInitialAssemblyRefIndex()
21:15:22                   at Microsoft.Cci.MetadataWriter.CreateIndices()
21:15:22                   at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(BlobBuilder metadataWriter, BlobBuilder debugMetadataWriterOpt, PdbWriter nativePdbWriterOpt, BlobBuilder ilWriter, BlobBuilder mappedFieldDataWriter, BlobBuilder managedResourceDataWriter, Int32 methodBodyStreamRva, Func`2 calculateMappedFieldDataStreamRva, Int32& moduleVersionIdOffsetInMetadataStream, Int32& pdbIdOffsetInPortablePdbStream, Int32& entryPointToken, MetadataSizes& metadataSizes)
21:15:22                   at Microsoft.Cci.PeWriter.WritePeToStream(MetadataWriter mdWriter, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt)
21:15:22                   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, Func`1 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, CancellationToken cancellationToken)
21:15:22                   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
21:15:22                   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
21:15:22                   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CancellationToken cancellationToken)
21:15:22                   at CscBench.CompileBench()
21:15:22                   at CscBench.Bench()
21:15:22                   at CscBench.Main()
21:15:22                ./CscBench.sh: line 58: 58738 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" CscBench.exe $CLRTestExecutionArguments $Host_Args
21:15:22                Expected: 100
21:15:22                Actual: 134
21:15:22                END EXECUTION - FAILED
```

**Comment by AndyAyersMS** [comment]
Yes, this is failing pretty often on Ubuntu now, and with a different failure mode than the one that led to the previous stretch of exclusion.

**Comment by janvorli** [comment]
There is an issue in the GC stack scanning that might be related (#3584). The problem happens when an exception is thrown from nested finallys, there are objects on the stack of the parent of the finally and GC is triggered while the exception is being processed. The issue causes some stack objects not being reported as alive.
I am almost done fixing it, so we'll see.

**Comment by RussKeldorph** [comment]
I'm also seeing failures on Windows that seem to have started around midnight PST.

Examples:
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_checked_windows_nt_jitstress2_jitstressregs2/21/testReport/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_checked_windows_nt_jitstress2_jitstressregs0x80/19/testReport/

**Comment by AndyAyersMS** [comment]
The new stress failures are a different issue -- an assert I just introduced. Set up a new issue for it and assign to me.

**Comment by RussKeldorph** [comment]
@AndyAyersMS Create #3586 for stress failures.

**Comment by AndyAyersMS** [comment]
Thanks. I can repro, should be quick to fix.
