### ISSUE TITLE
XML ENTITY not working with references to external xml files in .NET 4.7.2

### ISSUE THREAD

**Issue by mrboersm** [dotnet/coreclr#27345]
I have constructed an application that reads XML content and in the XML content it uses ENTITY components (file references) to reference other XML files. This worked when we were building with .NET Framework 4.0, but it stopped working in 4.5 and is still not working in 4.7.2. This is a critical issue for releasing a product of ours. I have attached a sample App that demonstrates the problem. See the instructions.txt file included in the zip for workflows/information.
[XMLEntityReference.zip](https://github.com/dotnet/coreclr/files/3752941/XMLEntityReference.zip)

**Comment by KalleOlaviNiemitalo** [comment]
Most overloads of [XmlDocument.Load](https://docs.microsoft.com/dotnet/api/system.xml.xmldocument.load?view=netframework-4.8) disable both DTD processing and external entity expansion. Can you use XmlDocument.Load(XmlReader) and configure the XmlReader to allow those features? See the [XmlReaderSettings.DtdProcessing](https://docs.microsoft.com/dotnet/api/system.xml.xmlreadersettings.dtdprocessing?view=netframework-4.8), [XmlReaderSettings.MaxCharactersFromEntities](https://docs.microsoft.com/dotnet/api/system.xml.xmlreadersettings.maxcharactersfromentities?view=netframework-4.8), and [XmlReaderSettings.XmlResolver](https://docs.microsoft.com/dotnet/api/system.xml.xmlreadersettings.xmlresolver?view=netframework-4.8) properties.

**Comment by mrboersm** [comment]
I read on the XmlReaderSettings that the default value for the Resolver changed.  This appears to be the breaking change that I was trying to find.  We will explicitly set these now.  Thanks for the response.
