### ISSUE TITLE
Question Jit Allocation reuse

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#27357]
Jit allocations hang around; I assume the memory is reused rather than leaked? (e.g. have 12MB of unreleased Jit allocations in this trace)

![image](https://user-images.githubusercontent.com/1142958/67254274-2a070e80-f474-11e9-8b37-6850d373d6f7.png)

Sample chain

![image](https://user-images.githubusercontent.com/1142958/67254241-f88e4300-f473-11e9-9d6f-3569248186ab.png)

**Comment by jkotas** [comment]
Yes, this memory is reused. It is freed by the finalizer thread if it was not used for a while (look for `JitHost::Reclaim`).

**Comment by benaadams** [comment]
Yes see that; maybe need to run it for longer

![image](https://user-images.githubusercontent.com/1142958/67255482-31c9b180-f47a-11e9-8201-d29efd5613c8.png)
