### ISSUE TITLE
Feature Request - string.Join() overload which accepts a character

### ISSUE THREAD

**Issue by jasonwilliams200OK** [dotnet/coreclr#2736]
Current situation:

```c#
char separator = ':';
string joined = string.Join(separator.ToString(), "one", "two", "three");
```

With `char` overload, users will be able to join string without calling `ToString()`
i.e. `string joined = string.Join(separator, "one", "two", "three");`

This will reduce at least one string allocation per call: https://github.com/dotnet/coreclr/blob/80c2952/src/mscorlib/src/System/Char.cs#L145-L168.

**Comment by tzwlai** [comment]
@joshfree, PTAL

**Comment by joshfree** [comment]
We're tracking API additions in the corefx repo.

**Comment by joshfree** [comment]
Moved to https://github.com/dotnet/corefx/issues/5552

**Comment by jasonwilliams200OK** [comment]
Thanks @joshfree.
