### ISSUE TITLE
Marshalling pointers to non-blittable structs is sometimes allowed

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/coreclr#27408]
```csharp
[StructLayout(LayoutKind.Sequential)]
struct NonBlittable
{
    bool _nonBlittable;
}

[DllImport("Unused")]
private static extern void PointerToNonBlittableType(NonBlittable* pNonBlittable, string unused);
```

Calling above method will throw a `MarshalDirectiveException` because pointers to nonblittable structs cannot be marshalled across the p/invoke boundary.

But dropping the `string unused` argument will make the p/invoke work. That looks like a bug that makes it look like it's okay to take dependency on non-blittable managed layout on the native side.

~~Making this throw is likely compat-breaking.~~

**Comment by jkotas** [comment]
This is also different between optimizations on/off: Debug does throw the exception as expected, Release does not throw the exception.

The bug is in `NDirect::MarshalingRequired`. This method checks for pointers, but it does not check whether the pointer points to a blittable struct.

**Comment by MichalStrehovsky** [comment]
Ah, cool. I crossed off the "compat breaking" part of the original issue description. If this reliably throws on Debug, the chances fixing this is going to break someone are pretty low.

**Comment by jkotas** [comment]
If we want to do something about this, we may want to remove this check from the non-optimized path for consistency. Pointers to non-blittable structs are considered to be blittable in other contexts. E.g.:

```
[StructLayout(LayoutKind.Sequential)]
struct NonBlittable
{
    bool _nonBlittable;
}

[StructLayout(LayoutKind.Sequential)]
struct ThisStructIsBlittable
{
    NonBlittable* _pNonBlittable;
}
```

**Comment by jkoritzinsky** [comment]
I'd be ok with either behavior since we still block creating pointers to non-"unmanaged" types in the compiler and pointers are an inherently unsafe feature, so some "unexpected" behavior of no marshalling of a non-blittable struct passed via a pointer is understandable.

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/runtime/pull/1866
