### ISSUE TITLE
String.IndexOf(String) extremely slow

### ISSUE THREAD

**Issue by xjru** [dotnet/coreclr#27407]
Hi,

I noticed that String.IndexOf(String) is extremely slow compared to V8 (90 times faster), OpenJDK 13 (270 times faster) and my own naive IndexOf implementation on the same .NET Core version (250 times faster).

It's .NET Core 3.1.100-preview1-014459 on macOS 10.15.
.NET Core 3.0 has the same issue.

```C#

static int TestDotNetIndexOf()
{
    const int N = 1_000_000;
    var count = 0;

    for (int i = 0; i < N; ++i)
    {
        var s = i.ToString();
        if (s.IndexOf("999") != -1)
        {
            ++count;
        }
    }

    return count;
}
```

It's obviously a trvial micro benchmark that comes with all the usual caveats, but that doesn't explain a two orders of magnitude performance difference. I did print the result of the test function in all implementations to make sure the code is actually executed.

You might suspect that int.ToString() could be the culprit as well, but it's not.

**Comment by xjru** [comment]
OK, I think I figured this out. It's only the culture specific implementations that are so slow. InvariantCulture is "only" about 3 times slower than other platforms/languages. I also believe that this issue doesn't belong in coreclr, so I'm closing the issue.

**Comment by benaadams** [comment]
> InvariantCulture is "only" about 3 times slower than other platforms/languages.

Try Ordinal?

>  I also believe that this issue doesn't belong in coreclr, so I'm closing the issue.

Is the correct place for `string`

**Comment by xjru** [comment]
@benaadams You're right, Ordinal is pretty fast (70 ms). It's still slower than my own implementation (52 ms) and Java (45 ms). 

But that's perfectly fine. I wasn't trying to fine tune, I just thought there must be a bug when I saw the orders of magnitude difference. Turns out that was an apples to oranges comparison to begin with.

**Comment by benaadams** [comment]
There's some overhead from the vectorization in short strings for Ordinal; you should find that the time doesn't increase as fast when the string gets longer

**Comment by xjru** [comment]
Thanks, that's good to know!
