### ISSUE TITLE
jit\jitstd\hashtable.h and its inheritors do not compile/work

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#27492]
We currently don't instantiate them, using coreclr\src\jit\jithashtable.h instead.
So these three: hashtable, unordered_set, and unordered_map have 0 uses.

If you try to instantiate them you will see many compile errors and they are not straightforward to fix.

I think it is better to delete them completely for now so nobody can waste their time trying to use them.

If we decide to fix them then we need to make sure to add unit tests for them. However, I think that the cost will be too high.

Repro:
```
    typedef jitstd::unordered_set<unsigned, GenTree*, JitSmallPrimitiveKeyFuncs<unsigned>> MySet;
    typedef jitstd::unordered_map<ValueNum, LclVarsSet*, JitSmallPrimitiveKeyFuncs<unsigned>> MyMap;
    MyMap myMap(allocator);
```

@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Makes sense to delete it, if unused. We use `JitHashTable` pervasively, so that seems unlikely to change.
