### ISSUE TITLE
__cxa_begin_catch conflicts with its declaration in include/c++/v1/cxxabi.h Clang 9

### ISSUE THREAD

**Issue by k15tfu** [dotnet/coreclr#27503]
```
/opt/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/../include/c++/v1/cxxabi.h:55:1: error: conflicting types for '__cxa_begin_catch'
__cxa_begin_catch(void *exceptionObject) throw();
^
/home/user/p/coreclr/2/src/pal/inc/pal_unwind.h:80:11: note: previous declaration is here
    void *__cxa_begin_catch(void *exceptionObject);
          ^
1 error generated.
```

cc @jkotas What can we do here?

**Comment by jkotas** [comment]
Is this used for anything? Can this whole file be deleted?

**Comment by janvorli** [comment]
Some of the stuff the header defines is used in src/vm/exceptionhandling.cpp (in UnhandledExceptionHandlerUnix).

**Comment by janvorli** [comment]
But it seems we could move the bits that are needed  to the exceptionhandling.cpp

**Comment by k15tfu** [comment]
@janvorli I cannot find any explicit use of `__cxa_begin_catch` / `__cxa_end_catch`. Do we really need these prototypes?

**Comment by janvorli** [comment]
No, we don't.
