### ISSUE TITLE
Some System.Math methods are slower on Linux

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/coreclr#27545]
I know that @tannergooding is aware of this problem, the goal of this issue is to track this difference.

```log
  Operating System: Ubuntu 18.04.3 LTS
  Kernel: Linux 4.15.0-66-generic
  Architecture: x86-64
```

| Slower                             | Lin/Win | Win Median (ns) | Lin Median (ns) | Modality|
| ---------------------------------- | -------:| ---------------:| ---------------:| --------:|
| System.MathBenchmarks.Double.Log10 |    2.65 |        33007.81 |        87377.67 |         |
| System.MathBenchmarks.Double.Tan   |    2.38 |        35724.84 |        84962.04 |         |
| System.MathBenchmarks.Double.Tanh  |    2.36 |        30740.39 |        72599.71 |         |
| System.MathBenchmarks.Double.Log   |    2.27 |        30167.45 |        68601.42 |         |
| System.MathBenchmarks.Single.Tanh  |    2.09 |        30841.95 |        64380.41 |         |
| System.MathBenchmarks.Double.Exp   |    1.98 |        30664.80 |        60690.88 |         |
| System.MathBenchmarks.Double.Cos   |    1.73 |        34771.40 |        60302.41 |         |
| System.MathBenchmarks.Double.Atan  |    1.71 |        36068.64 |        61519.15 |         |
| System.MathBenchmarks.Single.Tan   |    1.70 |        28023.28 |        47518.78 |         |
| System.MathBenchmarks.Double.Sin   |    1.64 |        30243.80 |        49700.56 |         |
| System.MathBenchmarks.Single.Sinh  |    1.41 |        51766.23 |        72770.61 |         |
| System.MathBenchmarks.Double.Atan2 |    1.35 |        83593.96 |       112919.34 |         |
| System.MathBenchmarks.Double.Pow   |    1.33 |       150783.62 |       200252.56 |         |
| System.MathBenchmarks.Single.Log10 |    1.33 |        27941.41 |        37070.20 |         |
| System.MathBenchmarks.Single.Atan2 |    1.24 |        55150.96 |        68594.50 |         |
| System.MathBenchmarks.Single.Exp   |    1.21 |        25007.72 |        30219.17 |         |
| System.MathBenchmarks.Single.ILogB |    1.18 |        25150.55 |        29565.47 |         |
| System.MathBenchmarks.Single.Atan  |    1.15 |        28287.01 |        32637.26 |         |
| System.MathBenchmarks.Double.ILogB |    1.09 |        26461.51 |        28958.54 |         |
| System.MathBenchmarks.Double.Sinh  |    1.09 |        61913.71 |        67701.47 |         |

| Faster                              | base/diff | Win Median (ns) | Lin Median (ns) | Modality|
| ----------------------------------- | ---------:| ---------------:| ---------------:| --------:|
| System.MathBenchmarks.Single.ScaleB |      8.27 |       218656.86 |        26429.65 |         |
| System.MathBenchmarks.Double.ScaleB |      6.70 |       187523.74 |        27982.89 |         |
| System.MathBenchmarks.Single.Log2   |      4.95 |       112273.57 |        22676.69 |         |
| System.MathBenchmarks.Double.Cbrt   |      3.21 |       225640.63 |        70400.98 |         |
| System.MathBenchmarks.Single.Cbrt   |      2.75 |       174730.42 |        63505.97 |         |
| System.MathBenchmarks.Single.Acosh  |      1.68 |        88747.63 |        52749.32 |         |
| System.MathBenchmarks.Double.Asinh  |      1.51 |       126682.20 |        84071.64 |         |
| System.MathBenchmarks.Single.Sin    |      1.43 |        30199.89 |        21081.45 |         |
| System.MathBenchmarks.Single.Cos    |      1.37 |        30516.63 |        22221.49 |         |
| System.MathBenchmarks.Single.Asin   |      1.35 |        36137.70 |        26684.82 |         |
| System.MathBenchmarks.Single.Asinh  |      1.31 |       108885.46 |        83032.52 |         |
| System.MathBenchmarks.Double.Asin   |      1.22 |        55290.31 |        45233.87 |         |
| System.MathBenchmarks.Single.Cosh   |      1.18 |        47673.41 |        40552.20 |         |
| System.MathBenchmarks.Single.Acos   |      1.13 |        34760.29 |        30737.36 |         |
| System.MathBenchmarks.Single.Log    |      1.11 |        26502.90 |        23915.95 |         |
| System.MathBenchmarks.Double.Atanh  |      1.09 |        75313.10 |        68834.58 |         |
| System.MathBenchmarks.Single.Atanh  |      1.07 |        68894.80 |        64466.47 |         |

The [benchmarks](https://github.com/dotnet/performance/tree/19733ffe853bc3384cf94c6e250bb8d661938e86/src/benchmarks/micro/coreclr/Math/Functions):

```cmd
git clone https://github.com/dotnet/performance.git
python3 ./performance/scripts/benchmarks_ci.py -f netcoreapp5.0 --filter 'System.MathBenchmarks*'
```

Recommended profiler is [VTune](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-corefx.md#VTune).

**Comment by adamsitnik** [comment]
Most probably in all of the cases we are limited by the available APIs.

```cs
static int Main(string[] args)
{
   int result = 0;
   for (int i = 0; i < 100_000; i++)
       result += (int) Log10Test();

   return result;
}

private static double Log10Test()
{
    var result = 0.0; var value = 0.0;

    for (var iteration = 0; iteration < 5000; iteration++)
    {
        value += 0.0004;
        result += Math.Log10(value);
    }

    return result;
}
```

![image](https://user-images.githubusercontent.com/6011991/67850968-bfa43d00-fb09-11e9-9911-8a659572ab4f.png)

**Comment by EgorBo** [comment]
NOTES:
1) Some PAL_* functions may contain additional conditions for corner cases on some platforms for some math functions
2) Most important one: On windows we use `/fp:fast` for most of them (`#pragma float_control(precise, off)`) and nothing similiar for gcc/clang/*nix (see https://github.com/dotnet/coreclr/pull/9369)

**Comment by jkotas** [comment]
Closing as dup
