### ISSUE TITLE
collectdump failed in container

### ISSUE THREAD

**Issue by northtyphoon** [dotnet/coreclr#27548]
I run an aspnetcore app in docker container (hosted in AKS). I want to collect the memory dump to investigate an issue. I terminal to the container and run the following command from shell, it failed as access denied.

```
/usr/share/dotnet/shared/Microsoft.NETCore.App/2.2.7/createdump 1
open (/proc/1/mem) FAILED 13 (Permission denied)
```
Any suggestion?

**Comment by josalem** [comment]
Collecting dumps in containers requires you to have a couple configuration flags set with the container host, namely `--cap-add=SYS_PTRACE --security-opt seccomp=unconfined`.  Since you're in k8s, you may also need to take a look [here](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) and see if your configuration has what's required for core dumps.

CC - @mikem8361

**Comment by mikem8361** [comment]
Yes, josalem is correct.

**Comment by northtyphoon** [comment]
@josalem @mikem8361 thanks for the suggestion, is it secure to enable the flag in production environment in general? When I need to collect the dump for analysis, it's usually a production environment. Based on your knowledge, do you recommend to enable the flags by default?

**Comment by josalem** [comment]
@northtyphoon, that's going to depend on what you are comfortable with.  The `seccomp` option is used to [white-list the syscalls available to the applications inside the container](https://docs.docker.com/engine/security/seccomp/).  The `unconfined` setting unblocks _all_ syscalls.  That's a bit coarse-grained.  You could write your own profile that only adds what syscalls `dotnet-dump` needs to operate to the white-list (the ptrace family mainly).

These settings only modify what the applications inside the container are capable of, so how much power you give them depends on how trustworthy your applications are.  If your application is running unverified or untrustworthy code, I would keep that in mind when deciding whether to turn these on in production environments. 

If you're running in Azure and using AKS, you could take a look at AKS Dev Spaces (https://docs.microsoft.com/en-us/azure/dev-spaces/quickstart-team-development) and then create a custom version of your container that has these flags on and do your triage dev loop that way.  This would let you do some triage "in production" without having all traffic go through your debug container.

Hopefully that helps you come to a decision 😄

**Comment by northtyphoon** [comment]
@josalem thanks again for all the suggestion. It's very helpful. I will also talk to Dev Spaces to learn how they are doing.

**Comment by northtyphoon** [comment]
Quick update, for K8S, `--security-opt seccomp=unconfined` is default if no other pod security policy applied (https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccom). I only need to add the following setting (https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/) in container spec to be able to create dump. Thanks again for the help.

```
securityContext:
  capabilities:
    add:
    - SYS_PTRACE
```
