### ISSUE TITLE
How to debug program terminating with uncaught exception of type PAL_SEHException

### ISSUE THREAD

**Issue by liiri** [dotnet/coreclr#27546]
I'm testing how my dotnet core application behaves on no internet connection. The program always crashes with

```
libc++abi.dylib: terminating with uncaught exception of type PAL_SEHException
```
I tried to find what command is triggering it but could not find it by manual trial and error.

I know it has something to do with the network connection since I don't get this crash when network is stable. I'm seeing fine responses from my external API calls (failing with WebException).

How can I debug this?

I'm using dotnet core `3.0.100` and `OSX 10.14.5`

**Comment by jkotas** [comment]
cc @janvorli

**Comment by liiri** [comment]
Thanks, currently its not that simple to reproduce it outside of my current debugger (JetBrains Rider). I'll close and reopen once I manage to get a stack trace.
