### ISSUE TITLE
Remove duplicates/unused code from src\jit\jitstd.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#27557]
[`jitstd`](https://github.com/dotnet/coreclr/tree/master/src/jit/jitstd) has methods that also exist in `std` namespace that is declared in [`src\inc\clr_std\utility`.](https://github.com/dotnet/coreclr/tree/master/src/inc/clr_std)

For example `swap`, `pair`, `forward` etc.
Also, it has many methods that are unused, for example `utility::set_union`, `utility::set_difference` etc.

So the task is:

- [x] delete the duplicates, replace existing uses of `jitstd::swap/pair/*` with `std::swap/pair/*` resolving including errors along the way;
- [x] delete unused function and files after the first step (`pair.h`, `functional.h` etc).

That is a follow up from #27492.

Keep that issue as a "good first issue" in case we have another hackathon or smth.

category:implementation
theme:jit-coding-style
skill-level:beginner
cost:small

**Comment by clearlove4399** [comment]
0.0.0

**Comment by olivia8090** [comment]
Make Real Money That,s Real Job Not Fack

like Andrew responded I'm in shock that people able to profit $4494 in four weeks on the internet .my Aunt Kyler George got a very nice BMW X 3 S just by some part-time working online with a computer. take a look at the site here
:) AND GOOD LUCK.:)

HERE →→→→→ www.securework99.com

**Comment by DmitriyMaksimov** [comment]
@sandreenko  I'm happy to work on this issue. Did a quick spike - shouldn't be hard.
Please let me know if it's Ok to make changes and create PR.

**Comment by sandreenko** [comment]
@DmitriyMaksimov thanks for taking these, you are welcome to make changes. Please ping me if you have any questions.

**Comment by DmitriyMaksimov** [comment]
@sandreenko created [PR](https://github.com/dotnet/runtime/pull/1272) but some checks (tests) failed.
Trying to understand why, but logs are not very informative (at least for me).
Could you please give me an idea what's wrong?

**Comment by sandreenko** [comment]
Fixed by https://github.com/dotnet/runtime/pull/1272 by @DmitriyMaksimov, thank you.
