### ISSUE TITLE
Publish single file without deps.json

### ISSUE THREAD

**Issue by Logerfo** [dotnet/coreclr#27550]
I have a custom workflow that uses a project only in the building phase, which means that this projects DLL file is not needed during the execution. However, the DLL appears in the `.deps.json` file, which causes the application to crash during the initialization phase.
The `.deps.json` file is optional, which means that the application will execute normally even if the file does not exist and, in my case, **only** if the file does not exist.
For that matter, I chose to not dig into the reason why the file contains the unused DLL. Instead, I chose to automatically delete the file with a post-build task:
```csproj
<Target Name="PostBuild" BeforeTargets="PostBuildEvent">
  <Exec Command="del $(TargetDir)$(TargetName).deps.json" />
</Target>
```
Now I need to publish my application as a single file executable, but:
1) If I keep the file (remove the task), the application never opens. Windows event log says that the problem is the not found DLL;
2) If I delete the file (keep the task), the publish will fail:
    > MSB4018: The "GenerateBundle" task failed unexpectedly. System.IO.FileNotFoundException: Could not find file: '...deps.json'.

Why isn't the file optional at publishing phase as well? I think there should be at least an opt-in configuration for the optionality.

**Comment by swaroop-sridhar** [comment]
@Logerfo  deleting the deps.json manifest is not a good practice -- it hampers the dependency-validation by the host, and may preclude your apps from using certain features like loading plugins.

I think what you need is to add `<ReferenceOutputAssembly>false</ReferenceOutputAssembly>` to the project references that are actually not used. This will exclude the unnecessary DLLs from the output directory (and the single-file) as well as generate a valid `deps.json` file.

**Comment by Logerfo** [comment]
@swaroop-sridhar you're correct, thanks!
