### ISSUE TITLE
TotalAvailableMemoryBytes does not reflect COMPlus_GCHeapHardLimit's value

### ISSUE THREAD

**Issue by mattzink** [dotnet/coreclr#27570]
SDK: 3.0.100
OS: CentOS 7 (x64)

We are not seeing the value we configure in the `COMPlus_GCHeapHardLimit` environmental variable being reflected in `GC.GetGCMemoryInfo().TotalAvailableMemoryBytes` as documented [here](https://docs.microsoft.com/en-us/dotnet/api/system.gcmemoryinfo.totalavailablememorybytes?view=netcore-3.0#remarks). We are therefore unsure if this heap limit is actually configured.

Repro:
```shell
$ dotnet new console
$ sed -i 's/"Hello World!"/GC.GetGCMemoryInfo().TotalAvailableMemoryBytes/g' Program.cs
$ dotnet run
8370458624
$ COMPlus_GCHeapHardLimit=100000000 dotnet run
4294967296
$ COMPlus_GCHeapHardLimit=50000000 dotnet run
1342177280
```

**Comment by jkotas** [comment]
Related / duplicate of https://github.com/dotnet/coreclr/issues/25552

cc @Maoni0

**Comment by mattzink** [comment]
So the documentation is wrong? COMPlus_GCHeapHardLimit and Server.GC.HeapHardLimit are not meant to be used?

**Comment by Maoni0** [comment]
I just checked - 
[#25437](https://github.com/dotnet/coreclr/pull/25437) is in 3.0 

```c++
*totalAvailableMemoryBytes = gc_heap::heap_hard_limit != 0 ? gc_heap::heap_hard_limit : gc_heap::total_physical_mem;
```
it should give you the correct number... could you please check what heap_hard_limit is set to?

**Comment by mattzink** [comment]
> could you please check what heap_hard_limit is set to?

Is that question addressed to @jkotas? I thought `GC.GetGCMemoryInfo().TotalAvailableMemoryBytes` was the managed equivalent to that.

**Comment by mattzink** [comment]
Note from the repro, setting the env. variable does effect the returned hard limit, just not to the value that was intended. Setting it to 100mb makes it consistently return ~4gb, and setting it to 50mb consistently returns ~1gb as the heap limit, etc.

**Comment by Maoni0** [comment]
all coreclr env vars interpret the number you specify as a hex number, (unfortunately) not dec :) we will make sure to document this.

**Comment by mattzink** [comment]
```
$ COMPlus_GCHeapHardLimit=5f5e100 dotnet run
100000000
```

@Maoni0 That was the missing link. I should have figured that out. Thanks!
