### ISSUE TITLE
Fix handling of ComVisible on Mac

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#276]
See https://github.com/dotnet/corefx/issues/779.  From @jkotas:

> Methods that read ComVisible attribute in vm\interoputil.cpp are not under FEATURE_COMINTEROP, and I guess there is a problem on that path somewhere. coreclr side of the fix should include placing the ComVisible attribute reading under FEATURE_COMINTEROP

**Comment by yizhang82** [comment]
It is actually under #ifdef FEATURE_COMINTEROP now. Vim tells me there is one #ifdef FEATURE_COMINTEROP covers https://github.com/dotnet/coreclr/blob/master/src/vm/interoputil.cpp#L2001-L7034. so we are good.
