### ISSUE TITLE
Test failed: JIT\Directed\pinvoke\pinvoke-examples\pinvoke-examples.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#27602]
**Job:**
[coreclr-outerloop #20191031.9](https://dev.azure.com/dnceng/public/_build/results?buildId=410191)

**Detail:**
win x64: https://helix.dot.net/api/2019-06-17/jobs/2f8bb55c-fb3a-40b5-9b30-696161509e41/workitems/JIT.Directed/console
win x86: https://helix.dot.net/api/2019-06-17/jobs/ed071453-f02c-4175-a131-e2de111b1b30/workitems/JIT.Directed/console

**OS & Arch:**
windows x64/x86

**Mode:**
win x64: 
RunCrossGen=1
COMPlus_TieredCompilation=0

win x86:
not set

**Note:**
Thisi failure doesn't repro on both windows x64 and x86 machines.

**Log:**
```
JIT\Directed\pinvoke\pinvoke-examples\pinvoke-examples.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\dotnetbuild\work\2f8bb55c-fb3a-40b5-9b30-696161509e41\Work\e2a9fa77-ebf5-4371-b7cf-8d0feb8ac60f\Exec\JIT\Directed\Reports\JIT.Directed\pinvoke\pinvoke-examples\pinvoke-examples.output.txt
      Raw output:
      BEGIN EXECUTION
              1 file(s) copied.
      " C:\dotnetbuild\work\2f8bb55c-fb3a-40b5-9b30-696161509e41\Payload\crossgen.exe"  /Platform_Assemblies_Paths C:\dotnetbuild\work\2f8bb55c-fb3a-40b5-9b30-696161509e41\Payload;C:\dotnetbuild\work\2f8bb55c-fb3a-40b5-9b30-696161509e41\Work\e2a9fa77-ebf5-4371-b7cf-8d0feb8ac60f\Exec\JIT\Directed\pinvoke\pinvoke-examples\IL;C:\dotnetbuild\work\2f8bb55c-fb3a-40b5-9b30-696161509e41\Work\e2a9fa77-ebf5-4371-b7cf-8d0feb8ac60f\Exec\JIT\Directed\pinvoke\pinvoke-examples /in pinvoke-examples.org /out pinvoke-examples.dll
      Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
      Copyright (c) Microsoft Corporation.  All rights reserved.
      
      Native image pinvoke-examples.dll generated successfully.
       "C:\dotnetbuild\work\2f8bb55c-fb3a-40b5-9b30-696161509e41\Payload\corerun.exe" pinvoke-examples.dll 
      Expected: 100
      Actual: -1
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
```

**Comment by BruceForstall** [comment]
@AaronRobinsonMSFT area-Crossgen, or area-Interop?
cc @jkoritzinsky

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall @jkotas My thought was merely for a first pass. Since this is happening for CrossGen in a JIT test I would assume that area should do a first pass. Definitely could be an Interop issue related to recent marshalling work.

**Comment by AaronRobinsonMSFT** [comment]
The name of this test is very misleading. This test is relying on a QCall and that is it:

``` csharp
[DllImport(JitHelpers.QCall, CharSet = CharSet.Unicode)]
private static extern int GetProcessorCount();
```

I don't see how this is related to anything that @jkoritzinsky has been doing. I will try to reproduce this, but it is very unlikely this has anything to do with recent changes in any Interop scenario.
