### ISSUE TITLE
Zero locals using SIMD

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#27608]
It's not an issue, more like a question, we have a lot of places where we create and pass empty (null) spans here and there, e.g. here https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Int64.cs#L79 (second `null` is a Span)

I've noticed a difference between how Mono-LLVM inits an empty Span and RuyJIT does:
```csharp
static ReadOnlySpan<char> GetEmptySpan()
{
    return null;

    //// same as:
    // return default;

    //// same as:
    // return new ReadOnlySpan<char>();

    //// same as:
    // return ReadOnlySpan<char>.Empty;
}
```

RuyJIT:
```asm
G_M7406_IG01:
G_M7406_IG02:
       xor      rax, rax
       mov      bword ptr [rcx], rax
       xor      eax, eax
       mov      dword ptr [rcx+8], eax
       mov      rax, rcx
G_M7406_IG03:
       ret      
; Total bytes of code: 14
```

Mono-LLVM-JIT:
```asm
<BB>:1
       vxorps   xmm0,xmm0,xmm0
       vmovups  XMMWORD PTR [rdi],xmm0
       ret
```
Does this approach make sense in terms of performance (also is there a related issue/request?)
As far as I understand Span takes 12 bytes on x86_64 so if it's aligned/padded to 16 bytes...

**Comment by omariom** [comment]
When assigned to a ref `default` is [treated differently](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQZoG8aGenykmKBgFlyAClgAzBgCUY2ACYB5AHYAbAJ4BlAA7YVAHjAALbFAB8DXDoCU3Xl2q9nVnQwC8DFQFc1agNz2PAC+QexOvMT8giKkEjDScoqqmrr6RqYWrnYRPI4uvNYeDAoJ2L4YgbkModVhUQJJyuraeoYmZpaiYjnO+QVMAOxevgFhtc710U0prekdWcJxvQ5hzsTDpZLlapXjNMFAA=)

**Comment by EgorBo** [comment]
@omariom hm.. interesting.
In case of `Int32.ToString()` it's:
```csharp
static string Int32ToString()
{
    return FormatInt32(42, null);
}

[MethodImpl(MethodImplOptions.NoInlining)]
public static string FormatInt32(int value, ReadOnlySpan<char> format)
{
    return null;
}
```
And the asm for `Int32ToString` is:
```asm
G_M19329_IG01:
       sub      rsp, 56
       xor      rax, rax
       mov      qword ptr [rsp+28H], rax
G_M19329_IG02:
       xor      rdx, rdx
       xor      ecx, ecx
       lea      rax, bword ptr [rsp+28H]
       mov      bword ptr [rax], rdx
       mov      dword ptr [rax+8], ecx
       lea      rdx, bword ptr [rsp+28H]
       mov      ecx, 42
       call     Program:FormatInt32(int,struct):ref
       nop      
G_M19329_IG03:
       add      rsp, 56
       ret      
; Total bytes of code: 47
```

Mono-LLVM-JIT:
```asm
    push   rax
    movabs rax,0xc0aa68
    mov    edi,0x2a
    xor    esi,esi   ;; two xors over 64bit registers
    xor    edx,edx
    call   QWORD PTR [rax]
    pop    rcx
    ret
```

**Comment by mikedn** [comment]
You seem to do a bit of apples to oranges comparisons - first talk about passing parameters but then showing codegen for returns and then mixing up win-x64 and linux-x64 ABI.

But yes, there's an issue in that JIT is overly aggressive with struct promotion. Some sort of store coalescing would help but breaking things up only to have to stitch them together later doesn't sound like a very constructive approach for a JIT.

And there definitely are issues with struct passing and returning in the JIT. Hopefully my current crusade against the poor handling of structs in the in JIR IR will fix at least some of that eventually.

Other than that, the JIT does use SIMD to initialize structs and has done that for quite some time now.

**Comment by EgorBo** [comment]
@mikedn yeah, sorry, I forgot that my mono-llvm under WSL is actually linux 😄  so it's a different ABI indeed. Thanks for the feedback.
