### ISSUE TITLE
clr-configuration-knobs.md is probably out of date

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#27611]
[clr-configuration-knobs.md](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md#tiered-compilation-configuration-knobs) states that `TC_QuickJit` is `0` by default but it's set to `1` in 
[clrconfigvalues.h](https://github.com/dotnet/coreclr/blob/master/src/inc/clrconfigvalues.h#L636).

**Comment by tannergooding** [comment]
There has been a few discussions on removing the markdown file, namely because it consistently gets out of date.

CC. @jkotas
