### ISSUE TITLE
JIT: suboptimal codegen for inlined local function

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/coreclr#27630]
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgJgIwCwAUFgMwAEu5AwsQN7HlOUVZ4AM5AsngBQCWAOxjl+ASkbMGRZrMoAWcgBleY8gF4AfKIDUOgNyS5y1YZnHKAdlEA6ACoB7AMowEQgOamj5AL7fvZJQc3DgCwqIS5kzSFroG3rJY1vz2zq4eXlG+/lmBWIpcpGEi4t4xFvkmalpxZrEqYnUVeACcAo3eflkBrAXyxRFlCcz8ek3GbG3i49lEPkA===

Source:
```csharp
using System;
public class C
{
    public string M1(int i)
    {
        void L() => i++;
        L();
        return i.ToString();
    }
    
    public string M2(int i)
    {
        i++;
        return i.ToString();
    }
    
    public void M3(int i)
    {
        void L() => i++;
        L();
        Console.WriteLine(i);
    }
    
    public void M4(int i)
    {
        i++;
        Console.WriteLine(i);
    }
}
```

ASM(master on 24 Sep 2019):
```asm
C.M1(Int32)
    L0000: push eax
    L0001: xor eax, eax
    L0003: mov [esp], eax
    L0006: mov [esp], edx
    L0009: mov ecx, [esp]
    L000c: inc ecx
    L000d: mov [esp], ecx
    L0010: lea ecx, [esp]
    L0013: mov ecx, [ecx]
    L0015: xor edx, edx
    L0017: push 0x0
    L0019: push edx
    L001a: xor edx, edx
    L001c: call System.Number.FormatInt32(Int32, System.ReadOnlySpan`1<Char>, System.IFormatProvider)
    L0021: pop ecx
    L0022: ret

C.M2(Int32)
    L0000: inc edx
    L0001: mov ecx, edx
    L0003: xor edx, edx
    L0005: push 0x0
    L0007: push edx
    L0008: xor edx, edx
    L000a: call System.Number.FormatInt32(Int32, System.ReadOnlySpan`1<Char>, System.IFormatProvider)
    L000f: ret

C.M3(Int32)
    L0000: lea ecx, [edx+0x1]
    L0003: call System.Console.WriteLine(Int32)
    L0008: ret

C.M4(Int32)
    L0000: inc edx
    L0001: mov ecx, edx
    L0003: call System.Console.WriteLine(Int32)
    L0008: ret
```

Surprisingly, the best codegen seems to be `M3`: JIT knows edx is unused, and doesn't write it.

The major difference on IL of `M1` and `M3` is how to fetch `i`: `M3` uses it by value, uses `ldloc` and `ldfld` which means a hidden copy. `M1` uses `ldloca` and `ldflda` to make changes happens on original address. But `Int32` is readonly struct, JIT should be aware about this and treat the two operations identical.

category:cq
theme:optimization
skill-level:expert
cost:medium

**Comment by BruceForstall** [comment]
@AndyAyersMS

**Comment by AndyAyersMS** [comment]
@huoyaoyuan `M1` and `M2` are quite different methods than `M3` and `M4`, so we would not expect similar code for all these methods. In particular `M1` and `M2` have to pass a struct to `FormatInt32` and this struct has to be on the stack per calling conventions.

We would expect code for `M1` and `M2` to be similar to each other, and likewise for `M3` and `M4`.

The latter two are already pretty close, so to my mind the interesting question is why `M1` and `M2` differ.

**Comment by mikedn** [comment]
The local functions in M1 and M3 do variable capture, that's not going to be easy to handle well in the JIT.

**Comment by huoyaoyuan** [comment]
I'm more surprised that why `M4` doesn't use `lea`.
Given this code:
```csharp
        [Benchmark]
        public int M3()
        {
            int i = random.Next();
            void L() => i++;
            L();
            return i;
        }

        [Benchmark]
        public int M4()
        {
            int i = random.Next();
            i++;
            return i;
        }
```
The benchmark result is:

| Method |     Mean |     Error |    StdDev |
|------- |---------:|----------:|----------:|
|     M3 | 6.365 ns | 0.0078 ns | 0.0073 ns |
|     M4 | 6.430 ns | 0.0223 ns | 0.0174 ns |

Although the big part should be random itself, doing an capture here is slightly faster than not. It generates identical code to `return i+1;`.

**Comment by mikedn** [comment]
> Given this code:

These versions of M3 and M4 produce identical code:
```asm
G_M1962_IG01:
       4883EC28             sub      rsp, 40
G_M1962_IG02:
       488B4910             mov      rcx, gword ptr [rcx+16]
       488B01               mov      rax, qword ptr [rcx]
       488B4048             mov      rax, qword ptr [rax+72]
       FF5028               call     qword ptr [rax+40]System.Random:Next():int:this
       FFC0                 inc      eax
G_M1962_IG03:
       4883C428             add      rsp, 40
       C3                   ret
```
I don't know how come on your machine one ends up being faster than the other but anyway, the difference is 0.01x or 0.065ns. I'll let you figure out how long a 3-4GHz CPU cycle takes and if a 0.065ns difference is relevant or not :)

**Comment by huoyaoyuan** [comment]
> These versions of M3 and M4 produce identical code:

I used random to make the code testable.
If using this code:
```csharp
        public int M3(int i)
        {
            void L() => i++;
            L();
            return i;
        }

        public int M4(int i)
        {
            i++;
            return i;
        }
```

Sharplab says their ASM are different.
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHufv6GAlgDsMDALJ0AFMNECAlF149O1JWqYoGAGUlyGAXgB8ggNQmA3IvU8dcy6us9iAdkH3rAXxpWl/GeJRpEUEFBzUVRx4BM3dIplcBWLUvag8gA==

**Comment by mikedn** [comment]
> I used random to make the code testable.

Yes, but the generated code is different from the original version so you're testing something else.

As for the original version, while it may be good for JIT to have more consistent codegen in such cases (this particular issue has to do with a long standing JIT issue - lack of so called forward substitution - and possibly with register allocation as well) it's not readily obvious that one version is truly better than the other. The `LEA` version is one byte shorter but at the same time `LEA` has lower throughput than `INC` on common processors such as Skylake.

**Comment by BruceForstall** [comment]
It seems like the question here is answered, so closing. If this is incorrect, please re-open.

**Comment by huoyaoyuan** [comment]
The minor case was answered, but the major case is not though.

> so to my mind the interesting question is why M1 and M2 differ


I'd like to keep this open until I see some change in sharplab.

**Comment by mikedn** [comment]
> but the major case is not though.

Are we still talking about the difference between LEA and INC? As in
```asm
C.M3(Int32)
    L0000: lea ecx, [edx+0x1]
    L0003: call System.Console.WriteLine(Int32)
    L0008: ret

C.M4(Int32)
    L0000: inc edx
    L0001: mov ecx, edx
    L0003: call System.Console.WriteLine(Int32)
    L0008: ret
```
What exactly is "major" about this?

**Comment by huoyaoyuan** [comment]
> What exactly is "major" about this?

The difference of these two functions:
```csharp
    public string M1(int i)
    {
        void L() => i++;
        L();
        return i.ToString();
    }
    
    public string M2(int i)
    {
        i++;
        return i.ToString();
    }
```
and their asm:
```csharp
C.M1(Int32)
    L0000: push eax
    L0001: xor eax, eax
    L0003: mov [esp], eax
    L0006: mov [esp], edx
    L0009: mov ecx, [esp]
    L000c: inc ecx
    L000d: mov [esp], ecx
    L0010: lea ecx, [esp]
    L0013: mov ecx, [ecx]
    L0015: xor edx, edx
    L0017: push 0x0
    L0019: push edx
    L001a: xor edx, edx
    L001c: call System.Number.FormatInt32(Int32, System.ReadOnlySpan`1<Char>, System.IFormatProvider)
    L0021: pop ecx
    L0022: ret

C.M2(Int32)
    L0000: inc edx
    L0001: mov ecx, edx
    L0003: xor edx, edx
    L0005: push 0x0
    L0007: push edx
    L0008: xor edx, edx
    L000a: call System.Number.FormatInt32(Int32, System.ReadOnlySpan`1<Char>, System.IFormatProvider)
    L000f: ret
```

**Comment by stephentoub** [comment]
Just to make sure we're all on the same page, the code generated by Roslyn for M1 is much more complicated than what's in M2 or even what appears to be there in M1:
```C#
    [StructLayout(LayoutKind.Auto)]
    [CompilerGenerated]
    private struct <>c__DisplayClass0_0
    {
        public int i;
    }

    public string M1(int i)
    {
        <>c__DisplayClass0_0 <>c__DisplayClass0_ = default;
        <>c__DisplayClass0_.i = i;
        <M1>g__L|0_0(ref <>c__DisplayClass0_);
        return <>c__DisplayClass0_.i.ToString();
    }

    [CompilerGenerated]
    private static void <M1>g__L|0_0(ref <>c__DisplayClass0_0 P_0)
    {
        P_0.i++;
    }
```

**Comment by mikedn** [comment]
OK, I'm not sure what version of the JIT is available on sharplab so to be sure we're looking at current codegen here's what I get from the runtime/master branch:
```asm
; M1:
G_M28834_IG01:
       55           push     ebp
       8BEC         mov      ebp, esp
       50           push     eax
       33C0         xor      eax, eax
       8945FC       mov      dword ptr [ebp-04H], eax
                                                ;; bbWeight=1    PerfScore 3.50
G_M28834_IG02:
       894DFC       mov      dword ptr [ebp-04H], ecx
       8B4DFC       mov      ecx, dword ptr [ebp-04H]
       41           inc      ecx
       894DFC       mov      dword ptr [ebp-04H], ecx
       8D4DFC       lea      ecx, bword ptr [ebp-04H]
       8B09         mov      ecx, dword ptr [ecx]
       33D2         xor      edx, edx
       6A00         push     0
       52           push     edx
       33D2         xor      edx, edx
       E8ECFEFFFF   call     System.Number:FormatInt32(int,System.ReadOnlySpan`1[Char],System.IFormatProvider):System.String
                                                ;; bbWeight=1    PerfScore 9.25
G_M28834_IG03:
       8BE5         mov      esp, ebp
       5D           pop      ebp
       C3           ret

; M2
G_M11520_IG01:
       55           push     ebp
       8BEC         mov      ebp, esp
                                                ;; bbWeight=1    PerfScore 1.25
G_M11520_IG02:
       41           inc      ecx
       33D2         xor      edx, edx
       6A00         push     0
       52           push     edx
       33D2         xor      edx, edx
       E8B8FAFFFF   call     System.Number:FormatInt32(int,System.ReadOnlySpan`1[Char],System.IFormatProvider):System.String
                                                ;; bbWeight=1    PerfScore 3.75
G_M11520_IG03:
       5D           pop      ebp
       C3           ret
```
As already pointed out above, the local function version is much more complicated. Not because of the local function itself but because that local function captures variables. That's rather problematic for the JIT. Not to say that the JIT couldn't/shouldn't improve, but in general I would simply not expect a function with captured variables to perform as good as a non capturing one.

**Comment by huoyaoyuan** [comment]
> the code generated by Roslyn for M1 is much more complicated than what's in M2 or even what appears to be there in M1

Yes, I'm totally aware about that. Given a local function that not captured by delegate is emitted in static, the story is about inlining of the JIT. Since it's able to inline M4, I'd expect it to also inline M2 into optimized form, because their callee should be identical (same function body, same closure shape).
The issue should be in structure promotion?

**Comment by huoyaoyuan** [comment]
> Not to say that the JIT couldn't/shouldn't improve, but in general I would simply not expect a function with captured variables to perform as good as a non capturing one.

I fact I didn't expect JIT to do the optimization until i saw that `M4` is perfectly inlined.

**Comment by mikedn** [comment]
> In fact I didn't expect JIT to do the optimization until i saw that M4 is perfectly inlined.

Yes but in `M4` the `int` value is passed "by value" to `WriteLine`, that avoids `i` becoming address exposed. So it's clearly a very different situation.

The real question is what exactly is the difference between `M1` & `M2`. From the JIT dumps it appears that there's more to it than just the capture stuff, I'm taking a closer look.

**Comment by mikedn** [comment]
Ha ha, this is our lovely friend `GT_ADDR`, its lovely cousin `GT_FIELD`, the drunken `GTF_GLOB_REF` that comes to the party uninvited and all the nonsense that made a trivial problem turn into an intractable one. Well, not really intractable but convoluted enough that everyone ends up getting it wrong somehow.

The inliner has a check for "invariant" arguments that affords it some simplification of argument handling. This includes a check for "address of a local", which is, of course, invariant. But it fails to recognize the "address of a field of a local" case and even if would it, the address has a `GTF_GLOB_REF` on it for no reason.

Net result is that the inliner spills the address of the field to a temp, that's something that is difficult to recover from and ends up leaving the local variable address exposed.

So the precise difference between `M1` and `M2` is that one calls `ToString` on a local variable and the other calls it on a field of a struct local variable. 

Interestingly this seems to be x86 specific. Haven't bothered to check why. I wasted already too much time on something which I hope to address by simply removing the `ADDR` (and related) nonsense. Though I'm not sure when exactly I'll get to the importer part of it...

**Comment by huoyaoyuan** [comment]
I'm interested that if you can optimize readonly struct method in another way.
Readonly struct and readonly methods mean that _hidden copy won't change the semantics_.  While compiler uses them to **reduce hidden copy**, sometimes **adding hidden copy** will perform better.

**Comment by AndyAyersMS** [comment]
Updating the inliner to use the result of `impIsAddressInLocal` (which is already calling anyways, earlier in `impInlineRecordArgInfo`) to better detect invariant local addresses gives us the same code for `M1` and `M2` on x86.
