### ISSUE TITLE
CI configuration problem: coreclr-gc-longrunning

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#27710]
https://dev.azure.com/dnceng/public/_build/results?buildId=416055&view=results

```
Job build_test_p1_OSX_x64_release depends on unknown job build_OSX_x64_release.
Job run_test_p1__Linux_x64_release depends on job build_test_p1_OSX_x64_release which creates a cycle in the dependency graph.
```

Related to https://github.com/dotnet/coreclr/issues/27666?

**Comment by BruceForstall** [comment]
@trylek @jashook

**Comment by trylek** [comment]
Hi Bruce!

I believe I fixed this yesterday with 

https://github.com/dotnet/coreclr/commit/d37ca4290cb1cc82f347475ab72d39252185d9f0

and Vlad seemed satisfied. Is there a way to double-check whether the job you mention is older or newer than my change?

Thanks a lot

Tomas

**Comment by BruceForstall** [comment]
It says "Scheduled yesterday at 3:00 am" so that would presumably be before your change. I'll close this; it will come back if it continues to be a problem.

**Comment by trylek** [comment]
Thank you! As part of my testing, I launched a private coreclr-gc-longrunning pipeline on my change,
https://dev.azure.com/dnceng/public/_build/results?buildId=416504
and it managed to launch successfully. I then canceled it at Vlad's suggestion as it would have been a waste of CPU time to actually run the long-running GC tests, I just had to verify that the pipeline graph is consistent.
