### ISSUE TITLE
Test failure : System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_EntireTreeTerminated

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#27723]
**Job:**
[coreclr-corefx-jitstress:20191105.1](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=417295)

**Details:**
https://helix.dot.net/api/2019-06-17/jobs/627db8f7-fc83-49e4-a05e-643d903e29f1/workitems/System.Diagnostics.Process.Tests/console

**OS & Arch:**
Linux x64

**Mode:**
export COMPlus_TieredCompilation=0
export COMPlus_DbgEnableMiniDump=1
export COMPlus_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export COMPlus_ReadyToRun=0
export COMPlus_ZapDisable=1

**Log:**
```
~/work/627db8f7-fc83-49e4-a05e-643d903e29f1/Work/760c06b2-9f16-40c8-b3a7-da9077b7c051/Exec ~/work/627db8f7-fc83-49e4-a05e-643d903e29f1/Work/760c06b2-9f16-40c8-b3a7-da9077b7c051/Exec
  Discovering: System.Diagnostics.Process.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.Process.Tests (found 214 of 272 test cases)
  Starting:    System.Diagnostics.Process.Tests (parallel test collections = on, max threads = 2)
    System.Diagnostics.Tests.ProcessStartInfoTests.ShellExecute_Nano_Fails_Start [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"
Linux
Linux
Linux
Linux
None of the following programs were installed on this machine: xdg-open,gnome-open,kfmclient.
    System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_EntireTreeTerminated [FAIL]
      Assert.Equal() Failure
      Expected: Boolean[] [True, True, True]
      Actual:   List<Boolean> [True, True, False]
      Stack Trace:
        /_/src/System.Diagnostics.Process/tests/Helpers.cs(29,0): at System.Diagnostics.Tests.Helpers.RetryWithBackoff(Action action, Int32 delayInMilliseconds, Int32 times)
        /_/src/System.Diagnostics.Process/tests/ProcessTests.cs(2130,0): at System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_EntireTreeTerminated()
        --- End of stack trace from previous location ---
    System.Diagnostics.Tests.ProcessTests.TestProcessRecycledPid [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
  Finished:    System.Diagnostics.Process.Tests
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.Process.Tests  Total: 268, Errors: 0, Failed: 1, Skipped: 2, Time: 129.059s
~/work/627db8f7-fc83-49e4-a05e-643d903e29f1/Work/760c06b2-9f16-40c8-b3a7-da9077b7c051/Exec
----- end Wed Nov 6 08:09:22 UTC 2019 ----- exit code 1 ----------------------------------------------------------
```

**Comment by danmosemsft** [comment]
it waits just over 10 seconds for all the processes in the tree to terminate, and one of them didn't.

**Comment by BruceForstall** [comment]
@danmosemsft Should the test be updated to wait longer? Is there someone on your team who should own this?

**Comment by danmosemsft** [comment]
The special settings above -- would they make things significantly slower? This test (and this test library in general) would start a bunch of processes. In most cases, it invokes `dotnet exec` with a parameter indicating what method to call. So if `dotnet exec` is going to be significantly slower that could cause tests of this kind to be flaky.

**Comment by BruceForstall** [comment]
> The special settings above -- would they make things significantly slower?

The special settings are to disable the use of ReadyToRun images, so every function must be JIT compiled. If the wait is happening during a period that requires a lot of JIT compilation, then the test will be slower.

It seems like 10 seconds is quite low. Is there a downside to waiting longer?

**Comment by danmosemsft** [comment]
We can easily extend this wait especially given it should rarely be hit. Will have to do this when repo opens again, or you can.

**Comment by BruceForstall** [comment]
This testing system is now obsolete, so closing.
