### ISSUE TITLE
azdo shows red build but UI shows that all jobs passed.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#27750]
https://dev.azure.com/dnceng/public/_build/results?buildId=418806&view=logs shows:
![image](https://user-images.githubusercontent.com/22642771/68430995-09be9b80-0166-11ea-97f3-cdd60faebec8.png)

but I have not seen any red jobs there.

@jashook could you please take a look if it is a known problem/a new one/or I am missing something?

Note: In [the PR](https://github.com/dotnet/coreclr/pull/27732/checks?check_run_id=292709812) it looks even strange, it is red with many pending jobs.

**Comment by jashook** [comment]
@MattGal has this been seen before?

**Comment by MattGal** [comment]
new to me, taking a peek.

**Comment by MattGal** [comment]
Chatting with some AzDO folks now, bring me examples.

**Comment by sandreenko** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=418806 is the only one that I am aware of.

**Comment by MattGal** [comment]
Symptoms-wise it's similar to what was reported in https://github.com/dotnet/core-eng/issues/8239.  I'm going to put all three builds in an IcM ticket and track it via that issue.  Feel free to close this one; it's not your problem for sure.
