### ISSUE TITLE
StackTrace reports wrong line number for throwing if-statement

### ISSUE THREAD

**Issue by glatzert** [dotnet/coreclr#27765]
A similar case has been reported in #25740 for while loops.

The debug output of a thrown exception will report the wrong line in stack-traces.

## Repro:
```
using System;

namespace WrongExceptionLine
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            if (System.DateTime.Today.Year > 2000)
                throw new Exception("Exception line should be 12.");

            Console.WriteLine("Goodbye World!");
        }
    }
}
```

Will report 
> Hello World!
> Unhandled exception. System.Exception: Exception line should be 12.
   at WrongExceptionLine.Program.Main(String[] args) in C:\...\WrongExceptionLine\Program.cs:line 14

**Comment by mikem8361** [comment]
Fix in PR https://github.com/dotnet/runtime/pull/2269
