### ISSUE TITLE
Crossgen segfaulting on System.Collections.

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/coreclr#27780]
The crossgen built from 0e97c7389d70551ff4179b922b700d9ff41eded3 is segfaulting when trying to crossgen System.Collections from CoreFX newer than https://github.com/dotnet/corefx/commit/475778fa982064e26a8b3a5d7545112f6586ac61 (this one succeeded).

This is blocking a new uptake of CoreFX into Core-Setup (https://github.com/dotnet/core-setup/pull/8796) and will cause issues when trying to get a live-live build set up in the consolidated repository.

cc: @fadimounir

**Comment by ViktorHofer** [comment]
@fadimounir we need to get this in today or latest tomorrow to unblock the repository consolidation which is happening tomorrow (11/13). Can you please prioritize this work item. Thanks.

**Comment by jeffschwMSFT** [comment]
cc @sergiy-k

**Comment by fadimounir** [comment]
I'm taking a look now. @jkoritzinsky could you please provide me with the repro steps?

**Comment by jkoritzinsky** [comment]
- Clone the generated PR merge commit on dotnet/core-setup#8796

```
git clone https://github.com/dotnet/core-setup
git fetch origin +refs/heads/*:refs/remotes/origin/* +refs/pull/8796/merge:refs/remotes/pull/8796/merge
git checkout refs/remotes/pull/8796/merge
```

- Run `build.cmd` in the root of core-setup. It will fail on System.Collections and output the failing command.
- From there, you can build a local crossgen and substitute in your crossgen for the one in the command for debugging/testing.

**Comment by fadimounir** [comment]
Fixed
