### ISSUE TITLE
CoreCLR failed to run test on release and debug configuration on latest reversion with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [dotnet/coreclr#27809]
CoreCLR failed to run test on release and debug configuration with MSVC on windows again. It can be reproduced on latest revision 1b26121. It should be a CoreCLR source issue. Could you look at this issue? Thanks a lot.

Repro steps:
1. git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2. Open a clean x86 prompt and browse to D:\CoreCLR\src
3. build x86 release -- /clp:ShowCommandLine
4. build-test.cmd x86 release -- /clp:ShowCommandLine
5. tests\runtest.cmd x86 release

[log_x86_test.log](https://github.com/dotnet/coreclr/files/3829873/log_x86_test.log)

Error info:
[executing command] tests\runtest.cmd x86 release 
python "D:\CoreCLR\src\tests\runtest.py" -arch x86 -build_type Release --generate_layout
host_os                  :Windows_NT
arch                     :x86
build_type               :Release
coreclr_repo_location    :D:\CoreCLR\src
product_location         :D:\CoreCLR\src\bin\Product\Windows_NT.x86.Release
core_root                :D:\CoreCLR\src\bin\tests\Windows_NT.x86.Release\Tests\Core_Root
test_location            :D:\CoreCLR\src\bin\tests\Windows_NT.x86.Release
test_native_bin_location :None
Restoring packages...
D:\CoreCLR\src\dotnet.cmd msbuild /nologo /verbosity:minimal /clp:Summary /nodeReuse:false /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true /p:UsePartialNGENOptimization=false /maxcpucount D:\CoreCLR\src\tests\build.proj /fileloggerparameters:"Verbosity=normal;LogFile=D:\CoreCLR\src\bin\Logs\Restore_ProductWindows_NT_x86_Release.log" /fileloggerparameters1:"WarningsOnly;LogFile=D:\CoreCLR\src\bin\Logs\Restore_ProductWindows_NT_x86_Release.wrn" /fileloggerparameters2:"ErrorsOnly;LogFile=D:\CoreCLR\src\bin\Logs\Restore_ProductWindows_NT_x86_Release.err" /t:BatchRestorePackages /p:__BuildType=Release /p:__BuildArch=x86 /p:__BuildOS=Windows_NT

Creating Core_Root...
D:\CoreCLR\src\dotnet.cmd msbuild /nologo /verbosity:minimal /clp:Summary /nodeReuse:false /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true /p:UsePartialNGENOptimization=false /maxcpucount D:\CoreCLR\src\tests\src\runtest.proj /fileloggerparameters:"Verbosity=normal;LogFile=D:\CoreCLR\src\bin\Logs\Tests_Overlay_ManagedWindows_NT_x86_Release.log" /fileloggerparameters1:"WarningsOnly;LogFile=D:\CoreCLR\src\bin\Logs\Tests_Overlay_ManagedWindows_NT_x86_Release.wrn" /fileloggerparameters2:"ErrorsOnly;LogFile=D:\CoreCLR\src\bin\Logs\Tests_Overlay_ManagedWindows_NT_x86_Release.err" /t:CreateTestOverlay /p:__BuildType=Release /p:__BuildArch=x86 /p:__BuildOS=Windows_NT

Copying Product Bin to Core_Root:
cp -r D:\CoreCLR\src\bin\Product\Windows_NT.x86.Release\* D:\CoreCLR\src\bin\tests\Windows_NT.x86.Release\Tests\Core_Root
---------------------------------------------------------------------

Core_Root setup.

Traceback (most recent call last):
  File "D:\CoreCLR\src\tests\runtest.py", line 2143, in <module>
    sys.exit(main(args))
  File "D:\CoreCLR\src\tests\runtest.py", line 2117, in main
    lambda path: do_setup(host_os,
  File "D:\CoreCLR\src\tests\runtest.py", line 543, in create_and_use_test_env
    ret_code = func(None)
  File "D:\CoreCLR\src\tests\runtest.py", line 2126, in <lambda>
    path))
  File "D:\CoreCLR\src\tests\runtest.py", line 2075, in do_setup
    run_in_context=unprocessed_args.run_in_context)
  File "D:\CoreCLR\src\tests\runtest.py", line 973, in run_tests
    if run_crossgen2_tests:
NameError: global name 'run_crossgen2_tests' is not defined
[command took 34 seconds]

**Comment by janvorli** [comment]
cc: @trylek - I can see `NameError: global name 'run_crossgen2_tests' is not defined`, so I was wondering if you may have any insight.

**Comment by BruceForstall** [comment]
cc @jashook

**Comment by jashook** [comment]
I encountered this over the weekend. Will send out a pr soon.
