### ISSUE TITLE
[interpreter] error: use of undeclared identifier 'g_pExecuteBackoutCodeHelperMethod'

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/coreclr#27848]
Hi,

Base on https://github.com/dotnet/coreclr/commit/03b7b318ab6641c20baeb37f963c4599a97d9276

Build option:

```
./build.sh cmakeargs "-DFEATURE_INTERPRETER=1" skipcrossgen ignorewarnings
```

Build error:

```
[ 94%] Building CXX object src/vm/wks/CMakeFiles/cee_wks.dir/__/amd64/unixstubs.cpp.o
/home/zhaixiang/coreclr/src/vm/interpreter.cpp:10213:23: error: use of undeclared identifier 'g_pExecuteBackoutCodeHelperMethod'
                pMD = g_pExecuteBackoutCodeHelperMethod;  // A random static method.
                      ^

```

I found that `g_pExecuteBackoutCodeHelperMethod` was deprecated by https://github.com/dotnet/coreclr/commit/4c0b70ea5f81c810a375db688a5d1ac3aee0b2ca 
 commit. So how to migrate Interpreter for it?

\cc @jkotas

Thanks,
Leslie Zhai

**Comment by jkotas** [comment]
This should be replaced by a different random static method. For example, change `g_pExecuteBackoutCodeHelperMethod` to `MscorlibBinder::GetMethod(METHOD__INTERLOCKED__COMPARE_EXCHANGE_OBJECT)`. Would you like to submit PR once you verify that it works?

**Comment by xiangzhai** [comment]
Hi @jkotas 

Please review it  https://github.com/dotnet/coreclr/pull/27850

Thanks,
Leslie Zhai
