### ISSUE TITLE
Wrong ApplicationBase with SingleFile deployment

### ISSUE THREAD

**Issue by havotto** [dotnet/coreclr#27864]
I publish my app this way:

dotnet publish --configuration Release --framework netcoreapp3.0 --runtime linux-x64 -v n /p:PublishSingleFile=true /p:PublishTrimmed=true

In this case Path.GetDirectoryName(Assembly.GetEntryAssembly().Location) and AppDomain.CurrentDomain.SetupInformation.ApplicationBase is /var/tmp/.net/... instead of the directory I copied the app into.

How can I get this original directory programatically?

**Comment by swaroop-sridhar** [comment]
@havotto  The assermbly-location is the location of the main application DLL, which will be the temporary extraction directory in the case of single-file apps today. 

To get the directory containing the actual single-file app, you can use: `Process.GetCurrentProcess().MainModule.FileName` or pinvoke into `GetModuleFileNameW(Null, , )`

**Comment by swaroop-sridhar** [comment]
Dup of https://github.com/dotnet/core-setup/issues/7491

**Comment by havotto** [comment]
Thanks!
