### ISSUE TITLE
Align missing libintl behavior of macOS and Alpine / musl-libc portable

### ISSUE THREAD

**Issue by am11** [dotnet/coreclr#27884]
<ins>libintl: the last unavoidable runtime dependency</ins>

For the operating systems which do not have libc providing gettext or libintl functionality out of the box, there is a UNIXTODO:

https://github.com/dotnet/coreclr/blob/ed5dc831b09a0bfed76ddad684008bebc86ab2f0/src/pal/src/locale/unicode.cpp#L592-L595

On macOS, regardless we have ran `brew install gettext` on the CoreCLR build machine, it gets skipped due to this condition:

https://github.com/dotnet/coreclr/blob/ed5dc831b09a0bfed76ddad684008bebc86ab2f0/src/pal/src/configure.cmake#L49-L51

However, it seems that the build machine dedicated for musl-libc portable, there is gettext installed, so consumers get this as a hard runtime dependency. On Alpine Linux, we need to install `libintl` package; on Void Linux (muscle edition), the smallest available (yet baggy) package `gettext` is required. A bit more unfortunate case is Single EXE / "bundle" apps, where this inobvious dependency is required as well.

For that matter, we have recently added a check in `dotnet-install` script: https://github.com/dotnet/cli/blob/ba194e4e6fe356af1e82abdca03e9cfbb2e3ca28/scripts/obtain/dotnet-install.sh#L258.

Proposal: Make `HAVE_LIBINTL_H`  always-false for Alpine Linux just like macOS (for now™️).

PS - BTW, there is no issue tracking that UNIXTODO; was the original plan to implement the required functionality in CoreCLR?

/cc @janvorli, @jkotas

**Comment by janvorli** [comment]
The gettext functionality was added at the beginning of porting coreclr to Unix in an anticipation that we will soon need to add localized strings for stuff from the native runtime (like exception messages). However, it never happened and the gettext stuff remained there as a dummy thing that is still executed, but effectively does nothing. So I think we can remove that stuff for now and if the need for it comes in the future, we can always restore it from the history and finalize it in a way that would not make it a hard dependency on MUSL (glibc has the gettext stuff built-in IIRC).

**Comment by am11** [comment]
@janvorli, could it be included in 3.1? It will benefit musl-libc based distros, and otherwise no impact on the product.

**Comment by janvorli** [comment]
I think it would make sense. @jkotas do you agree?

**Comment by jkotas** [comment]
@janvorli 3.1 is LTS. The servicing bar for LTS is critical fixes only. This does not look like a critical fix to me, but you can do a bar check with servicing shiproom to confirm.
