### ISSUE TITLE
GetCustomAttribute throws NullReferenceException on undefined or empty Attributes

### ISSUE THREAD

**Issue by yaugenka** [dotnet/coreclr#27882]
`Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyDescriptionAttribute>().Description;`
This call will throw NullReferenceException when `Description` is not defined or defined with empty value like `<Description></Description>`

In Framework it returns an empty string.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas and @stephentoub Seems like this is a change in behavior from .NET Framework. Are we still working to align API semantics with .NET Framework even though we have said we are [complete](https://github.com/dotnet/announcements/issues/130)? Doesn't seem to be too much of an issue to fix, but users may have started taking a dependency on the new behavior.

**Comment by jkotas** [comment]
This is not change in the runtime behavior. This is change in the build tooling behavior.

In .NET Framework, the build tooling always emits `AssemblyDescriptionAttribute`, even if there is no description.
In .NET Core, the build tooling emits `AssemblyDescriptionAttribute` only if the Description project property is non-empty.

The .NET Core behavior looks correct. It is a waste to emit AssemblyDescriptionAttribute with no description.

 This problem can be worked around by either checking for `null` returned by `GetCustomAttribute`; or specifying non-empty `<Description>...</Description>` property in the `.csproj` file.

**Comment by jkotas** [comment]
Thank you for reporting this anyway!
