### ISSUE TITLE
Single .NET Core app targeting multiple runtimes

### ISSUE THREAD

**Issue by Ghasan** [dotnet/coreclr#27908]
I am sorry if is this the wrong repo, I am not sure where to ask.

I have a .NET Core app project that calls a native library using `[DllImport]`. I have 3 versions of the native library for win-x86, win-x64, and linux-x64 inside `runtimes` folder following this structure: `runtimes\win-x86\native\native.dll`, and the same for the others (except Linux as `libnative.so`).

And I have this in the project file:
```xml
    <Content Include="runtimes\**\*">
      <PackagePath>%(Identity)</PackagePath>
      <Pack>true</Pack>
    </Content>
```
When I run the app, it crashes with "DLL not found" errors, even though the runtimes folder is correctly copied to the output folder.

I have tried to use MSBuild targets, and it works by placing the `native.dll` next to `myapp.dll` in the output folder. But I don't want this, since I want a single built app to work for all supported runtimes specified above, I don't want to build 3 separate builds. I am expect .NET Core host to choose the proper one based on RID of the host.

Is this possible?

I have noticed that if I package my the native.dlls to a `nupkg`, and then import it to myapp project, it will work, and .NET Core runtime can find the proper native.dll inside `runtimes` folder. But I don't want to keep packaging to a nupkg locally and copying it to .nuget cache each time the native libraries change.

Btw, SkiaSharp, HarfBuzzSharp, SharpFont, all of them keep their native libraries in the `runtimes` folder, and they work like a charm.

Appreciate your help.
Is this possible?

**Comment by jeffschwMSFT** [comment]
> I have noticed that if I package my the native.dlls to a nupkg, and then import it to myapp project, it will work

The reason this works is that by adding this via nuget the native dependency is known at build time and the corresponding native library is correctly added to the deps.json.  Once it is in the deps.json, the host will inform the runtime on where to load this file at runtime.  When looking for native binaries at runtime, coreclr only looks in 3 places: paths declared by the deps.json, next to the assembly, and via dlopen/loadlibrary.

You can emulate this same behavior by adding the necessary entries to the deps.json.  There is no official way to update the deps.json after build, though I think it is worth an investigation as a potential mitigation.  

cc @nguerrera

**Comment by Ghasan** [comment]
Thanks, Jeff. I see now, why it behaves so. I found those tickets too regarding the same thing:
dotnet/sdk#765
NuGet/Home#4514

I think I might look into specifying the library path in code.

You may close this ticket.
