### ISSUE TITLE
JIT: Duplicated addition in compiled IL

### ISSUE THREAD

**Issue by dryszkowski** [dotnet/coreclr#27903]
The JIT compiles IL code below into something that seems to be incorrect
```
    call       void [mscorlib]System.Diagnostics.Debugger::Break()
    ldarg.0
    ldc.i4 100
    
    Label_A:
    add
    dup
    ldc.i4.0
    brtrue.s   Label_A
    
    starg.s    theSequenceNumber
    pop
    ldarg.0
    ret
```
```
01130950 56                   push        esi  
01130951 8B F1                mov         esi,ecx  
01130953 E8 30 E4 74 71       call        7287ED88  
01130958 8B D6                mov         edx,esi  
0113095A B8 64 00 00 00       mov         eax,64h  
0113095F 83 C2 64             add         edx,64h  
01130962 03 C2                add         eax,edx  
01130964 5E                   pop         esi  
01130965 C3                   ret  
```
Signature of this method is
```
  .method public hidebysig static int32 Test1(int32 theSequenceNumber) cil managed
```
`ECX` contains value of `theSequenceNumber` argument

In produced compiled code addition occurs twice but if I remove
```
    ldc.i4.0
    brtrue.s   Label_A
```
everything back to normal and addition is not duplicated anymore. IL code from my example is simplified version of code that after obfuscation start to behave differently from original version.

**Comment by mikedn** [comment]
What .NET Core version are you using? The current master build generates:
```
G_M46009_IG01:
G_M46009_IG02:
       83C164               add      ecx, 100
       8BC1                 mov      eax, ecx
G_M46009_IG03:
       C3                   ret
```
And even if there is a JIT bug that results in duplicate addition due to the weird loop I don't see how the JIT could generate the code like `cmp eax,0FFFFh` from the presented IL. Are you sure you have posted the correct/entire example?

**Comment by dryszkowski** [comment]
I'm sorry, I removed part of IL code to create a shorter example but pasted result from longer one. The result from shorter one is code below (also edited in question).
```
01130950 56                   push        esi  
01130951 8B F1                mov         esi,ecx  
01130953 E8 30 E4 74 71       call        7287ED88  
01130958 8B D6                mov         edx,esi  
0113095A B8 64 00 00 00       mov         eax,64h  
0113095F 83 C2 64             add         edx,64h  
01130962 03 C2                add         eax,edx  
01130964 5E                   pop         esi  
01130965 C3                   ret  
```
I'm using .Net Framework probably 4.8, but I'm not sure and for the moment I can't access machine with reproduction (I can confirm that tomorrow).

**Comment by AndyAyersMS** [comment]
This looks like an issue with the code generated by .Net Framework's Jit32 (note: slightly modified repro, adds 110 instead of 100):
```asm
;; .Net Framework x86
01670870 55                   push        ebp  
01670871 8B EC                mov         ebp,esp  
01670873 8B D1                mov         edx,ecx  
01670875 B8 6E 00 00 00       mov         eax,6Eh  
0167087A 83 C2 6E             add         edx,6Eh  
0167087D 03 C2                add         eax,edx  
0167087F 5D                   pop         ebp  
01670880 C3                   ret  
```
As noted by @mikedn, .Net Core jits handle this properly:

```asm
;; .Net Core x86
G_M8576_IG01:
       55           push     ebp
       8BEC         mov      ebp, esp

G_M8576_IG02:
       83C16E       add      ecx, 110
       8BC1         mov      eax, ecx

G_M8576_IG03:
       5D           pop      ebp
       C3           ret
```
@dryszkowski since this is an .Net Framework issue, you will need to report this via the [VS Developer Community Portal](https://developercommunity.visualstudio.com/) or the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) tool.

**Comment by dryszkowski** [comment]
@AndyAyersMS Thanks for redirection to VS Developer Community Portal. If anyone have similar problem [here](https://developercommunity.visualstudio.com/content/problem/834591/jit-duplicated-addition-in-compiled-il.html) is continuation of this issue.
