### ISSUE TITLE
Patching of the SCD based deployement.

### ISSUE THREAD

**Issue by RajeshAKumar** [dotnet/coreclr#27913]
We are shipping a product where a service component uses ASP.NET Core 3.0 in Self Contained deployment model.
Does Dot net core register this anywhere to be patched via MS update?
Or are we responsible to patch whenever newer framework version comes up.
If later, that is a big commitment from our part and reduces the usability of SCD especially considering the security.

It is hard to explain to normal IT admins that our service has a very small attack surface area and only when it runs, not otherwise.
The fact that we are carrying and running a web server, the IT can be after us.

Please advise.

**Comment by jeffschwMSFT** [comment]
Here is a bit more information about self contained publishes: https://docs.microsoft.com/en-us/dotnet/core/deploying/

> Or are we responsible to patch whenever newer framework version comes up.

The owner of the application is responsible for ensuring the package is patched and up to date.

**Comment by RajeshAKumar** [comment]
@jeffschwMSFT Thank you.
