### ISSUE TITLE
QueryInterface() returns "no interface" when IUnknown is requested

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/coreclr#2796]
`HRESULT MergeTokenManager::QueryInterface(REFIID riid, void **ppUnk)`
`HRESULT CMapToken::QueryInterface(REFIID riid, void **ppUnk)`

both yield `E_NOINTERFACE` if `IUnknown` IID is passed as `riid`. That's a major violation of COM requirements. If this is intentional it should be explained but I guess it's a bug.

**Comment by tzwlai** [comment]
@yizhang82 PTAL

**Comment by yizhang82** [comment]
@Dmitry-Me Thanks for logging those issues. I believe those classes are internal implementation that are not "proper" COM objects which are reusable by other components. Having said that, implementing IUnknown properly doesn't hurt. Feel free to submit a PR.

**Comment by Dmitry-Me** [comment]
@yizhang82 I submitted https://github.com/dotnet/coreclr/issues/2839

**Comment by yizhang82** [comment]
Thanks, @Dmitry-Me 
@gkhanna79 This is metadata API. Can you get someone in your team to take a look at the PR?

**Comment by gkhanna79** [comment]
I will take a look at the PR.

**Comment by jkotas** [comment]
nice to have cleanup

**Comment by tishion** [comment]
PR #4563
