### ISSUE TITLE
Unable to delete assembly file after plugin uninstall

### ISSUE THREAD

**Issue by zengqinglei** [dotnet/coreclr#27974]
**Describe the bug**

When I use the sample code: https://github.com/dotnet/samples/tree/master/core/tutorials/Unloading
Then I want to remove the assembly file after the plugin is uninstalled and I get an exception:

![image](https://user-images.githubusercontent.com/7374317/70961451-cb998d80-20bc-11ea-837c-601b70c8e52a.png)

**Run Environment**
* .NET CORE 3.1
* Windows 10 
![image](https://user-images.githubusercontent.com/7374317/70961722-a8231280-20bd-11ea-852a-eb42a443ac45.png)

I hope to get your help soon, thank you!

**Comment by jeffschwMSFT** [comment]
@janvorli

**Comment by janvorli** [comment]
Closing as a dup of https://github.com/dotnet/runtime/issues/976 where I have already responded.
