### ISSUE TITLE
List<T> should use Array.Empty<T>() (a.k.a. EmptyArray<T>.Value)

### ISSUE THREAD

**Issue by gsfreema** [dotnet/coreclr#2801]
Instead of creating its own empty static array (_emptyArray), List<T> could piggyback on the existing EmptyArray<T>.Value which would provide a slight memory gain by better reusing EmptyArray<T>.Value.

**Comment by stephentoub** [comment]
Thanks, but see https://github.com/dotnet/coreclr/pull/1596
