### ISSUE TITLE
What's the Platform ID for NetBSD?

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#2805]
I want to set `IMAGE_FILE_MACHINE_NATIVE_OS_OVERRIDE` for NetBSD, but I don't know from where come the constant values.

Similar issue for Linux, MacOSX and FreeBSD: https://github.com/dotnet/coreclr/issues/1035

Code reference:
https://github.com/dotnet/coreclr/blob/master/src/inc/pedecoder.h#L95

**Comment by jkotas** [comment]
These IDs are just randomly chosen numbers.

**Comment by krytarowski** [comment]
Does 0x1993 work for you? It's the date of starting the NetBSD CVS repo.

**Comment by jkotas** [comment]
Yes, it works.
