### ISSUE TITLE
Not working on systems with newer libicu.

### ISSUE THREAD

**Issue by Marqin** [dotnet/coreclr#2834]
Hello,

Most distributions ( Ubuntu, Arch, etc. ) moved to libicu 55. And System.Globalization.Native.so bundled with DNX coreclr does need to dynamically link libicu 52.

I see two possible solutions:
1. Bundle libicu 52 with coreclr ( it's MIT licensed from what I see ).
2. Build two versions of System.Globalization.Native.so and make DNX install that one which will be working on target distro ( check icu version ), or just name it differently and document in Install notes how to swap those .so.

**Comment by ellismg** [comment]
We are one the (2) plan.  The general idea is that we are producing packages of the native components which are specific to a target runtime identifier (which is per distro).  DNX/dotnet cli are responsible for getting the correct packages pulled in at install time.

We already produce packages for CentOS 7.1 (which uses an even earlier version of ICU) and will be adding more for other supported distros.  Soon we should also have enough of the infrastructure needed for folks to produce their own version of these packages for distros the team does not official support.

In the mean time, you can build System.Globalization.Native.so on your target platform and replace the version that ships with DNX/dotnet cli.

**Comment by krytarowski** [comment]
How do you plan to handle cases like pkgsrc? It's the base package manager in SmartOS, NetBSD, Minix etc - it's released quarterly and it's detached from the base in regards of package versions/release plan.

For example `NetBSD 7.0` can be used with `pkgsrc-2015Q4` and soon `pkgsrc-2016Q1`. Will be there need to ship a matrix of `7.0-2015Q4`, `7.0-2016Q1`?

```
$ pkg_info |grep icu
icu-56.1            Robust and full-featured Unicode services
```

**Comment by sergiy-k** [comment]
Hi @ellismg, can this issue be closed now or there is still work that needs to be done to address it?

**Comment by ellismg** [comment]
We are executing on (2) and have already done this for other Linux distros we support.  We don't yet have a strategy for rolling releases like pkgsource except that we hope the CLI and shared framework will make their way into these systems such that they can be rebuilt from source when dependencies are updated.

The work we plan to do for RTM has already been done.

**Comment by sergiy-k** [comment]
@ellismg, thank you. In this case, I'm going to move it out from RTM.

**Comment by gkhanna79** [comment]
@ellismg What are the next steps here?

**Comment by ellismg** [comment]
#7773 will address a fair amount of the pain here.

**Comment by gkhanna79** [comment]
@ellismg I dont believe we intend to take that change for 1.1.0.

**Comment by ellismg** [comment]
@gkhanna79  Then push this out, #7773 reflects the way we want to handle this.

**Comment by danmosemsft** [comment]
@gkhanna79 is this planned for 2.0?

**Comment by janvorli** [comment]
@danmosemsft I am not sure what's missing here. The #7773 I've committed last October seems to handle the issue completely.

**Comment by danmosemsft** [comment]
@janvorli great, I was just going through issues marked 2.0 that weren't clearly 2.0 work. If this is done, I'll close.

**Comment by danmosemsft** [comment]
@gkhanna79 fyi.
