### ISSUE TITLE
x86 Checked Build Break

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2874]
daccess.lib(nidump.obj) : error LNK2019: unresolved external symbol "class __VoidPtr __stdcall GetUnwindDataBlob(unsigned long,class __DPtr<struct _RUNTIME_FUNCTION>,unsigned long *)" (?GetUnwindDataBlob@@YG?AV__VoidPtr@@KV?$__DPtr@U_RU
NTIME_FUNCTION@@@@PAK@Z) referenced in function "public: void __thiscall NativeImageDumper::DumpReadyToRunMethod(unsigned long,class __DPtr<struct _RUNTIME_FUNCTION>,class SString &)" (?DumpReadyToRunMethod@NativeImageDumper@@QAEXKV?$__
DPtr@U_RUNTIME_FUNCTION@@@@AAVSString@@@Z) [D:\Projects\coreclr\bin\obj\Windows_NT.x86.Checked\src\dlls\mscordac\mscordaccore.vcxproj]
D:\Projects\coreclr\bin\obj\Windows_NT.x86.Checked\src\dlls\mscordac\Checked\mscordaccore.dll : fatal error LNK1120: 1 unresolved externals [D:\Projects\coreclr\bin\obj\Windows_NT.x86.Checked\src\dlls\mscordac\mscordaccore.vcxproj]

**Comment by gkhanna79** [comment]
@noahfalk Can you please route this?

**Comment by mikem8361** [comment]
@jashook can you send me exactly what build options and version of the coreclr sources you are building?  I just built the latest with "build.cmd x86 release" on windows and no errors.

**Comment by erozenfeld** [comment]
@mikem8361 @jashook The error is with build.cmd x86 checked and I already submitted a PR with a fix: #2916

**Comment by mikem8361** [comment]
Great. Thanks.

**Comment by jashook** [comment]
Correct that is the same link error. Closing
