### ISSUE TITLE
x86 legacy backend failures

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2877]
TODO:

Test failures need to be triaged a little more.

JIT\Methodical\divrem\rem\u8rem_cs_do\u8rem_cs_do.cmd
Interop\ICastable\Castable\Castable.cmd
JIT\Regression\VS-ia64-JIT\V2.0-Beta2\b410474\b410474\b410474.cmd
JIT\Directed\rvastatics\rvastatic2\rvastatic2.cmd
JIT\Regression\CLR-x86-JIT\V1-M09\b14585\b14585\b14585.cmd
JIT\Methodical\switch\switch1\switch1.cmd
JIT\Directed\coverage\importer\Desktop\bleref_il_d\bleref_il_d.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b57367\b57367\b57367.cmd
~~JIT\Directed\PREFIX\unaligned\1\arglist\arglist.cmd~~
JIT\Directed\intrinsic\interlocked\rva_rvastatic4\rva_rvastatic4.cmd
JIT\Methodical\cctor\misc\tail_il_r\tail_il_r.cmd
JIT\Methodical\cctor\misc\global_il_d\global_il_d.cmd
JIT\Methodical\divrem\div\u8div_cs_ro\u8div_cs_ro.cmd
JIT\Regression\CLR-x86-JIT\V1.2-Beta1\b102637\b102637\b102637.cmd
JIT\Methodical\tailcall_il_dbgpointer_il_dbgpointer.cmd
~~JIT\Methodical\xxobj\sizeof_il_dbgsizeof64_il_dbgsizeof64.cmd~~
~~JIT\Methodical\ELEMENT_TYPE_IU_il_relu_array_merge_il_relu_array_merge.cmd~~
JIT\Methodical\tailcall_il_dbgtest_implicit_il_dbgtest_implicit.cmd
JIT\Methodical\Arrays\misc_il_dbgarrres_il_dbgarrres.cmd
JIT\Methodical\switch\switch7\switch7.cmd
JIT\jit64\opt\cse\HugeArray1\HugeArray1.cmd
JIT\Methodical\tailcall_il_reltest_void_il_reltest_void.cmd
JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b321799\b321799\b321799.cmd
~~JIT\Methodical\doublearray\dblarray4_cs_r\dblarray4_cs_r.cmd~~
JIT\Methodical\xxobj\operand_il_dbglocalloc_il_dbglocalloc.cmd
JIT\Methodical\tailcall_il_dbgrecurse_ep_void_il_dbgrecurse_ep_void.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b65423\b65423\b65423.cmd
JIT\jit64\localloc\verify\verify01_dynamic\verify01_dynamic.cmd
~~JIT\Methodical\doublearray\dblarray4_cs_d\dblarray4_cs_d.cmd~~
JIT\Performance\CodeQuality\Serialization\Serialize\Serialize.cmd
~~JIT\Directed\PREFIX\unaligned\2\arglist\arglist.cmd~~
JIT\Methodical\Boxing\xlang_relsin_il_il_relsin_il_il.cmd
JIT\Regression\CLR-x86-JIT\V1.2-M01\b08046\b08046\b08046.cmd
~~JIT\Methodical\xxobj\sizeof_il_dbgsizeof32_il_dbgsizeof32.cmd~~
JIT\Directed\coverage\importer\Desktop\ldelemnullarr1_il_r\ldelemnullarr1_il_r.cmd
JIT\Regression\CLR-x86-JIT\V1.2-Beta1\b103058\b103058\b103058.cmd
~~JIT\Directed\PREFIX\volatile\1\arglist\arglist.cmd~~
JIT\Regression\Dev11\dev10_865840\dev10_865840\dev10_865840.cmd
JIT\Methodical\Boxing\xlang_odbgsin_il_il_odbgsin_il_il.cmd
JIT\Methodical\switch\switch6\switch6.cmd
~~JIT\Methodical\doublearray\dblarray4_cs_do\dblarray4_cs_do.cmd~~
JIT\SIMD\CircleInConvex\CircleInConvex.cmd
JIT\Directed\lifetime\lifetime2\lifetime2.cmd
JIT\Methodical\cctor\simple\precise3_il_d\precise3_il_d.cmd
JIT\Methodical\cctor\misc\tail_il_d\tail_il_d.cmd
JIT\SIMD\CircleInConvex_r\CircleInConvex_r.cmd
JIT\Directed\coverage\importer\Desktop\badldsfld_il_d\badldsfld_il_d.cmd
JIT\Methodical\switch\switch11\switch11.cmd
JIT\jit64\regress\ndpw\21220\b21220\b21220.cmd
JIT\Methodical\tailcall_il_dbgpointer_i_il_dbgpointer_i.cmd
JIT\Directed\rvastatics\rvastatic4\rvastatic4.cmd
~~JIT\Methodical\ELEMENT_TYPE_IU_il_relsizeof_il_relsizeof.cmd~~
JIT\Directed\pinvoke\preemptive_cooperative\preemptive_cooperative.cmd
JIT\Directed\tls\mutualrecurthd-tls\mutualrecurthd-tls.cmd
JIT\Methodical\Arrays\misc_il_relarrres_il_relarrres.cmd
~~JIT\Methodical\xxobj\sizeof_il_dbgsizeof_il_dbgsizeof.cmd~~
JIT\SIMD\CircleInConvex_ro\CircleInConvex_ro.cmd
JIT\Methodical\cctor\misc\global_il_r\global_il_r.cmd
JIT\IL_Conformance\Old\Conformance_Base\rem_r4\rem_r4.cmd
JIT\Methodical\tailcall_il_relrecurse_ep_void_il_relrecurse_ep_void.cmd
~~JIT\Methodical\ELEMENT_TYPE_IU_il_dbgsizeof_il_dbgsizeof.cmd~~
JIT\Directed\RVAInit\overlap\overlap.cmd
JIT\Methodical\Boxing\xlang_orelsin_il_cs_orelsin_il_cs.cmd
JIT\Performance\CodeQuality\V8\DeltaBlue\DeltaBlue\DeltaBlue.cmd
~~JIT\Methodical\xxobj\sizeof_il_relsizeof32_il_relsizeof32.cmd~~
JIT\Regression\CLR-x86-EJIT\v1-m10\b07847\b07847\b07847.cmd
JIT\Methodical\Boxing\xlang_odbgsin_il_il_odbgsin_il_il.cmd
JIT\Methodical\switch\switch9\switch9.cmd
JIT\Regression\Dev11\External\dev11_239804\ShowLocallocAlignment\ShowLocallocAlignment.cmd
JIT\Directed\coverage\importer\Desktop\bleref_il_r\bleref_il_r.cmd
JIT\jit64\localloc\verify\verify01_small\verify01_small.cmd
JIT\Directed\coverage\importer\Desktop\badldsfld_il_r\badldsfld_il_r.cmd
~~JIT\Methodical\ELEMENT_TYPE_IU_il_reli_array_merge_il_reli_array_merge.cmd~~
JIT\Methodical\switch\switch2\switch2.cmd
JIT\Directed\intrinsic\interlocked\rva_rvastatic3\rva_rvastatic3.cmd
JIT\Methodical\varargs\seh\fault_il_d\fault_il_d.cmd
JIT\Regression\CLR-x86-JIT\V1.2-Beta1\b101136\b101136\b101136.cmd
JIT\Methodical\tailcall\Desktop_il_relthread-race_il_relthread-race.cmd
JIT\Methodical\switch\switch10\switch10.cmd
JIT\Methodical\eh\deadcode\badcodeafterfinally_r\badcodeafterfinally_r.cmd
GC\Features\HeapExpansion\Finalizer\Finalizer.cmd
JIT\opt\perf\doublealign\Locals\Locals.cmd
JIT\Methodical\Boxing\misc_dbgconcurgc_il_dbgconcurgc_il.cmd
JIT\Methodical\switch\switch5\switch5.cmd
JIT\Methodical\varargs\seh\filter_il_d\filter_il_d.cmd
JIT\Regression\CLR-x86-JIT\V1-M09\b15307\b15307\b15307.cmd
JIT\Methodical\divrem\div\u8div_cs_do\u8div_cs_do.cmd
JIT\Methodical\varargs\seh\fault_il_r\fault_il_r.cmd
JIT\Regression\CLR-x86-JIT\V1-M09\b16102\b16102\b16102.cmd
JIT\Directed\rvastatics\rvastatic3\rvastatic3.cmd
JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b399444\b399444a\b399444a.cmd
JIT\Directed\RVAInit\extended\extended.cmd
JIT\Directed\rvastatics\rvastatic1\rvastatic1.cmd
JIT\Regression\VS-ia64-JIT\V1.2-M02\b108129\b108129\b108129.cmd
JIT\Methodical\Boxing\xlang_dbgsin_il_cs_dbgsin_il_cs.cmd
JIT\Regression\CLR-x86-JIT\V1-M09\b13621\b13621\b13621.cmd
JIT\Regression\CLR-x86-JIT\V1-M10\b04914\b04914\b04914.cmd
JIT\Directed\intrinsic\interlocked\rva_rvastatic2\rva_rvastatic2.cmd
JIT\Methodical\varargs\seh\filter_il_r\filter_il_r.cmd
JIT\jit64\regress\vsw\102754\test2\test2.cmd
~~JIT\Methodical\xxobj\sizeof_il_relsizeof_il_relsizeof.cmd~~
JIT\Methodical\switch\switch8\switch8.cmd
~~JIT\Methodical\doublearray\dblarray4_cs_ro\dblarray4_cs_ro.cmd~~
~~JIT\Directed\PREFIX\unaligned\4\arglist\arglist.cmd~~
JIT\Methodical\tailcall_il_reltest_implicit_il_reltest_implicit.cmd
JIT\Methodical\Boxing\xlang_relsin_il_cs_relsin_il_cs.cmd
JIT\Methodical\switch\switch3\switch3.cmd
JIT\Directed\coverage\importer\Desktop\nonrefsdarr_il_r\nonrefsdarr_il_r.cmd
JIT\Regression\CLR-x86-EJIT\V1-M09.5-PDC\b14426\b14426\b14426.cmd
JIT\opt\Tailcall\TailcallVerifyWithPrefix\TailcallVerifyWithPrefix.cmd
JIT\Methodical\cctor\misc\threads3_il_d\threads3_il_d.cmd
JIT\Methodical\switch\switch4\switch4.cmd
JIT\Methodical\tailcall_il_dbgtest_void_il_dbgtest_void.cmd
~~JIT\Methodical\ELEMENT_TYPE_IU_il_dbgi_array_merge_il_dbgi_array_merge.cmd~~
JIT\Methodical\Boxing\xlang_odbgsin_il_cs_odbgsin_il_cs.cmd
JIT\Methodical\eh\deadcode\badcodeafterfinally_d\badcodeafterfinally_d.cmd
JIT\Methodical\xxobj\operand_il_rellocalloc_il_rellocalloc.cmd
JIT\jit64\regress\vsw\102754\test1\test1.cmd
JIT\Directed\intrinsic\interlocked\rva_rvastatic1\rva_rvastatic1.cmd
JIT\Directed\coverage\importer\Desktop\nonrefsdarr_il_d\nonrefsdarr_il_d.cmd
JIT\Methodical\tailcall_il_relpointer_il_relpointer.cmd
JIT\Regression\CLR-x86-JIT\V1.2-M01\b03689\b03689\b03689.cmd
JIT\Methodical\tailcall_il_relpointer_i_il_relpointer_i.cmd
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b49644\b49644\b49644.cmd
~~JIT\Methodical\xxobj\sizeof_il_relsizeof64_il_relsizeof64.cmd~~
~~JIT\Methodical\structs\systemvbringup\structinregs\structinregs.cmd~~
JIT\jit64\localloc\verify\verify01_large\verify01_large.cmd
JIT\Directed\tls\test-tls\test-tls.cmd
JIT\Methodical\divrem\rem\u8rem_cs_ro\u8rem_cs_ro.cmd
JIT\Regression\CLR-x86-JIT\V1.2-M02\b20785\b20785\b20785.cmd
Interop\NativeCallable\NativeCallableTest\NativeCallableTest.cmd
JIT\Methodical\cctor\misc\threads3_il_r\threads3_il_r.cmd
~~JIT\Methodical\ELEMENT_TYPE_IU_il_dbgu_array_merge_il_dbgu_array_merge.cmd~~
JIT\Directed\coverage\importer\Desktop\ldelemnullarr1_il_d\ldelemnullarr1_il_d.cmd
JIT\Methodical\Boxing\misc_relconcurgc_il_relconcurgc_il.cmd
JIT\Methodical\Boxing\xlang_dbgsin_il_il_dbgsin_il_il.cmd
JIT\Methodical\Boxing\xlang_orelsin_il_il_orelsin_il_il.cmd
JIT\Methodical\cctor\simple\precise3_il_r\precise3_il_r.cmd
JIT\Directed\rvastatics\rvastatic5\rvastatic5.cmd
JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i\conv_ovf_i8_i.cmd

**Comment by pgavlin** [comment]
@jashook do we still need to be tracking this, or can we close this issue?

**Comment by BruceForstall** [comment]
@jashook I'm going to close this.
