### ISSUE TITLE
On windows, simple text output requires exception throw/catch.

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#288]
When simple console output tests on Windows in the default OEM codepage (437) there's an exception thrown and caught in `System.Text.Encoding::GetEncoding(int32)`.

Seems like we should avoid exceptions for common things like this.

**Comment by weshaggard** [comment]
@pallavit has made a fix for in the standalone System.Console implementation that we have on corefx, although I don't think it has made it into onto github yet.

**Comment by ellismg** [comment]
I'm going to take @pallavit's fix and get it working for this case.  We have a similar problem in Unix that I would like to fix as well.

**Comment by MattWhilden** [comment]
@ellismg How'd it go? What's the word? Did you crack it? etc etc.

**Comment by AndyAyersMS** [comment]
@ellismg is changing this still on the table? LLILC's current limitations around EH aside, it seems like removing an exception throw/catch from most every console app's startup path is not a bad thing.

**Comment by ellismg** [comment]
This should be done now.  If you are still seeing this, please let me know what version of System.Console.dll you're getting from NuGet.

**Comment by AndyAyersMS** [comment]
Looks like it is:
```
--a-- W32i   DLL ENU     1.0.22412.0 shp     65,712 04-02-2015 system.console.dll
System.Reflection.AssemblyFileVersionAttribute = ... // ...1.0.22412.00.
```

**Comment by ellismg** [comment]
We need to get you on they newest version from MyGet.  It has the fix for this issue.
