### ISSUE TITLE
Assembly::CLRPrivResourceAssembly::QueryInterface() fails to retrieve ICLRPrivResource

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/coreclr#2895]
`Assembly::CLRPrivResourceAssembly::QueryInterface()` is coded such that it returns `E_NOINTERFACE` if `ICLRPrivResource` is requested which is one of the interfaces implemented by the class. The class has this description

    // Nested class used to implement ICLRPriv binder related interfaces

so I'd guess it must implement both and must proper retrieve both interfaces. Otherwise either one of those base interfaces must be removed or this magic must be explained.

**Comment by jkotas** [comment]
There are many places where the interfaces used internally within the runtime violate COM conventions one way or the other. Cleaning it up is nice to have ... it has also potential to introduce regressions.

**Comment by jkotas** [comment]
#2796 is another instance.

**Comment by tishion** [comment]
PR #4562
