### ISSUE TITLE
DateTime.Parse does not preserve UTC for ISO8601 "Z"

### ISSUE THREAD

**Issue by Rast1234** [dotnet/coreclr#2896]
If I have a `DateTime.UtcNow.ToString("o")` with **"Z"** in the end, and then use `DateTime.Parse(str)`, I get a DateTime with `DateTimeKind.Local`. Why? It is meant to be UTC date by ISO8601, but it is converted to local by default here: https://github.com/dotnet/coreclr/blob/43b39a73cbf832ec13ec29ed356cb75834e7a8d7/src/mscorlib/src/System/Globalization/DateTimeParse.cs#L2608

I know the way to parse it correctly with `DateTimeStyles.RoundtripKind`. Why it's not the default behavior?

**Comment by tarekgh** [comment]
This is the original design which intentionally always return the datetime in local TZ if the parsed string contains TZ specifier. you may look at the following doc for more information:

https://msdn.microsoft.com/en-us/library/system.datetime.parse(v=vs.110).aspx

and yes if you want to get it in UTC, you'll need to use RoundtripKind. the documentation says that too.

sorry, we'll not be able to change this design now as it will be big breaking change. please let me know if you have any other question

**Comment by tarekgh** [comment]
I am closing the issue but feel free to reply back or re-open if there is any more follow up needed. Thanks for bringing the issue.
