### ISSUE TITLE
adding a trailing slash to the --temp-output path causes an illegal character in path error

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/coreclr#2897]
C:\temp\test>dotnet compile --temp-output "c:\temp\test\obj\"
Illegal characters in path.
Parameter name: path

Removing the trailing slash fixes it, or removing the quotes fixes it. I suspect all quoted paths will have this issue.

Note also that these output strings are not formatted in way that VS recognizes them as errors or warning. This means they will appear in the output window (and the build will fail) but they will not included in the error list.  Ideally all these tools would output errors in a canonical format

**Comment by piotrpMSFT** [comment]
@BillHiebert I believe this is already fixed given the state of VS/CLI integration. If not, can you re-open in CLI repo and mark partner-blocking?
