### ISSUE TITLE
DirectoryInfo.Exists returns incorrect results when it is cast from FileSystemInfo

### ISSUE THREAD

**Issue by troydai** [dotnet/coreclr#29]
When test the same directory, `DirectoryInfo` and `Directory.Exist(...)` gives different answers. The bug is repo on `System.IO.FileSystem 4.0.0-beta-22530`.

The issue can't be reproduced on CLR.

Repo code:
```
var root = Path.GetTempFileName();
File.Delete(root);
Directory.CreateDirectory(root);

var testDir = new DirectoryInfo(root);
var betaDir = Path.Combine(root, "beta");

Directory.CreateDirectory(betaDir);

var beta = testDir.EnumerateFileSystemInfos("beta", SearchOption.TopDirectoryOnly).First() as DirectoryInfo;
Console.WriteLine("Test {0} using DirectoryInfo: {1}", beta.FullName, beta.Exists);
Console.WriteLine("Test {0} using Directory.Exist: {1}", betaDir, Directory.Exists(betaDir));
```

**Comment by davidfowl** [comment]
Seems like this is in the wrong place

**Comment by stephentoub** [comment]
@troydai, thanks for the issue, but this should be closed and instead opened on the CoreFX repo:
https://github.com/dotnet/corefx

**Comment by troydai** [comment]
Yeah, i just closed the issue over there. :) I'll reopen that one.

**Comment by troydai** [comment]
Open at corefx: https://github.com/dotnet/corefx/issues/616

**Comment by stephentoub** [comment]
Thanks
