### ISSUE TITLE
Unix: Unecessary struct copy while passing by value on stack

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#2908]
Say caller foo() is passing a struct 's' by value on stack to bar(), at high-level code generated is

// Make a copy of s by assigning to a local t on foo()'s stack frame
t = s
copy t on to stack
bar()

t = s copy is unnecessary as 's' could be directly copied to stack.

**Comment by sejongoh** [comment]
#6266, #6265, and #6264 are opened for cases not handled by #6037.

**Comment by CarolEidt** [comment]
Closing this, as #18358 addressed the extra copies when passed on stack. #6264 remains open because it includes extra copies when passed in registers.
