### ISSUE TITLE
Incorrect use of [Obsolete] attribute in PasswordDeriveBytes.cs

### ISSUE THREAD

**Issue by gafter** [dotnet/coreclr#291]
The following appears in `PasswordDeriveBytes.cs`

```cs
        [System.Security.SecuritySafeCritical]  // auto-generated
        [Obsolete("Rfc2898DeriveBytes replaces PasswordDeriveBytes for deriving key material from a password and is preferred in new applications.")]
// disable csharp compiler warning #0809: obsolete member overrides non-obsolete member
#pragma warning disable 0809
        public override byte[] GetBytes(int cb) {
```

As you can see from https://github.com/dotnet/roslyn/issues/108 this is not a correct use of the Obsolete attribute, as no caller will ever bind to this method and see the desired diagnostic. The compiler will tell you that you are using the obsolete attribute incorrectly, but you suppress the warning.

**Comment by MattWhilden** [comment]
Hey @sandkum are we going to blast this attribute? Seems like an easy enough fix. If you're jammed, it's always nice to have a few super easy tasks tagged as "up for grabs" to point people to who want to get started.
