### ISSUE TITLE
libunwind not available in NetBSD

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#2910]
Currently there is no port of `libunwind` to NetBSD. Is it possible to add a stub for such platforms, just to push build forward with missing partial functionality?

**Comment by jasonwilliams200OK** [comment]
https://github.com/dotnet/coreclr/issues/810 is already tracking this issue.

BTW, CoreFX native shims are decoupled from CoreCLR and not dependent on libunwind etc. I once started porting the CoreFX native and sent some PRs. There were couple of things left at the time. But if someone try again, chances are CoreFX native shim will land on NestBSD sooner than CoreCLR (although CoreFX native shim without CoreCLR will not enable you consuming .NET5, but small/independent code base is a good start):

```sh
# install NetBSD
# pkgsrc git, cmake and some other stuff
# see https://gist.github.com/jasonwilliams200OK/6efa7907e66275df2d24 for
# more info on its close cousin freebsd
#
git clone https://github.com/dotnet/corefx
cd corefx
setenv TZ UTC ; setenv MONO_THREADS_PER_CPU 50 ; ./build.sh native clang3.7

# and start hacking by fixing compile errors one at a time and send pull requests upstream!
```

**Comment by krytarowski** [comment]
Interesting, I will have a look at CoreFX.

**Comment by jkotas** [comment]
libunwind is pretty essential dependency. It should not be hard to stub it out, but not much will run without it.

**Comment by krytarowski** [comment]
OK, so I will try porting of HP libunwind.

I read in several threads that people keep having ideas to stop using the HP flavor https://github.com/dotnet/coreclr/issues/872 https://github.com/dotnet/coreclr/issues/862

**Comment by benpye** [comment]
I would assume LLVM's libunwind is available on NetBSD? It may then be worth reconsidering #872 though I think the issue of lacking context pointers remains.

**Comment by janvorli** [comment]
The LLVM's libunwind should work for NetBSD (provided it is available for that platform), since it is what we currently use for OSX. There is a workaround for the lack of context pointers. It is not ideal, but it works.

**Comment by jasonwilliams200OK** [comment]
@benpye, nope it isn't available. But krytarowski is porting libunwind to NetBSD as per my conversation with him on #NetBSD-pl on freenode (IRC). Currently he is away. :)

@janvorli, Ben's #3045 is equally useful in opinion of some people including @krytarowski on IRC; for the systems where HP libunwind is not available. Until of course llilic fellows put some effort and make LLVM's libunwind equally useful. :)

**Comment by jasonwilliams200OK** [comment]
We are trying to ping OpenBSD and DragonflyBSD guys to team up and join the forces. :)

**Comment by benpye** [comment]
@jasonwilliams200OK Another motivation for me for #3045 is to narrow down the still existing ARM unwinding issue. If I can try an alternative unwind library then I may have some better luck tracking the issue.

**Comment by krytarowski** [comment]
This is our home-grown implementation for libunwind:

https://github.com/IIJ-NetBSD/netbsd-src/blob/master/lib/libexecinfo/unwind.h

I can see LLVM libunwind in the NetBSD base sources.. but I cannot build pristine upstream version. I will need to investigate it.

@benpye do you think our implementation is sufficient?

First I want to build 100% of the sources and upstream all remaining patches before I will be touching libunwind in CoreCLR. I'm still new to unwinding. 

https://github.com/IIJ-NetBSD/netbsd-src/tree/master/sys/lib/libunwind/unwind.h

I plan to port HP libunwind anyway to get all the features in the future and enable more VMs on NetBSD.

**Comment by krytarowski** [comment]
Upstream version of the LLVM libunwind has been ported (but not tested) to NetBSD

**Comment by jasonwilliams200OK** [comment]
:+1: 
Just tried https://github.com/llvm-mirror/libunwind HEAD on NetBSD7, now it builds! :smile: 
Need to make libunwind.h visible for CoreCLR.

Thanks @krytarowski for porting LLVM libunwind. At some point nognu-libunwind (aka HP libunwind) can also be ported.
