### ISSUE TITLE
where is Assembly.GetTypes in dnxcore50?

### ISSUE THREAD

**Issue by giancarloa** [dotnet/coreclr#2926]
hello... I am trying to port to dnxcore50... however I am having a hard time trying to figure out how to convert Assembly.GetTypes... this method as everyone knows gives me all the types in the assembly... how do I do that in dnxcore50???? I have not been able to find a concrete answer in this... thank you

**Comment by weshaggard** [comment]
Assembly.GetTypes will be added back as part of https://github.com/dotnet/corefx/issues/5381.

**Comment by giancarloa** [comment]
thanks @weshaggard ... but is there an alternative in the meantime??? and do you know if it's going to be added back as part of the final rtm 1.0 release????

**Comment by weshaggard** [comment]
Yes our goal is to get it added for RTM. In the mean time you can use Assembly.DefinedTypes property.
