### ISSUE TITLE
Unix/OSX: Add codegen support for Enter/Leave/TailCall callbacks

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#2927]
Existing Enter/Leave (ELT) Callback functionality works for Amd64 Windows.  This needs to be revisited to make necessary changes to make it work for Unix Amd64.

Issue #2520 enables profiling on Unix/OSX without ELT callbacks.  This issue is for tracking JIT side of the work.

**Comment by RussKeldorph** [comment]
@davmason @sywhang I believe this should have been closed with #12603.  Please re-open if you disagree.
