### ISSUE TITLE
wchar_t redefinition broken on NetBSD

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#2937]
Currently the `wchar_t` redefinition on NetBSD is broken https://github.com/dotnet/coreclr/blob/master/src/pal/inc/pal_char16.h#L32

```
In file included from /tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/src/safecrt/safecrt_output_l.c:70:
/usr/pkg/bin/../lib/clang/3.9.0/include/stddef.h:90:24: error: typedef redefinition with different types ('int' vs 'unsigned short')
typedef __WCHAR_TYPE__ wchar_t;
                       ^
/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/inc/pal_char16.h:32:17: note: expanded from macro 'wchar_t'
#define wchar_t __wchar_16_cpp__
                ^
/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/inc/pal_char16.h:44:24: note: previous definition is here
typedef unsigned short wchar_t;
                       ^
/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/inc/pal_char16.h:32:17: note: expanded from macro 'wchar_t'
#define wchar_t __wchar_16_cpp__
                ^
1 error generated.
```

My local patch for it is as follows:

```
    $NetBSD$
     
    --- src/pal/inc/pal_char16.h.orig       2016-01-28 19:04:13.000000000 +0000
    +++ src/pal/inc/pal_char16.h
    @@ -29,6 +29,8 @@ This file is used to define the wchar_t
     #ifndef PAL_STDCPP_COMPAT
     #if defined (PLATFORM_UNIX) && defined(__GNUC__)
     #undef wchar_t
    +#undef __WCHAR_TYPE__
    +#define __WCHAR_TYPE__ __wchar_16_cpp__
     #define wchar_t __wchar_16_cpp__
     #endif // PLATFORM_UNIX
     
    @@ -39,8 +41,12 @@ This file is used to define the wchar_t
     #if !defined(_WCHAR_T_DEFINED) || !defined(_MSC_VER)
     #if defined (PLATFORM_UNIX)
     #if defined(__cplusplus)
    +#undef __WCHAR_TYPE__
    +#define __WCHAR_TYPE__ char16_t
     typedef char16_t wchar_t;
     #else
    +#undef __WCHAR_TYPE__
    +#define __WCHAR_TYPE__ unsigned short
     typedef unsigned short wchar_t;
     #endif // __cplusplus
     #endif // PLATFORM_UNIX
    @@ -49,4 +55,3 @@ typedef unsigned short wchar_t;
     #endif // !_WCHAR_T_DEFINED
     #endif // !_WCHAR_T_DEFINED || !_MSC_VER
     #endif // !PAL_STDCPP_COMPAT
    -
     
```

And it passes build further.

I was warned by a NetBSD developer that `wchar_t` is owned by system and it will break.

**Comment by krytarowski** [comment]
While there `char16_t` is part of C11.

I don't know whether it's on purpose, but we define `wchar_t` twice in this file. Please error log.

**Comment by jasonwilliams200OK** [comment]
`wchar_t` on OSX is 32-bit and on Windows and other Unices it is 16-bit.
`char16_t` and `char32_t` are more transparent, fixed sized types on each platforms.
Since `wchar_t` is explicitly defined as `unsigned short`, I think it can be defined as `char16_t` (same width) as all supported compilers to build CoreCLR (including VS2013 / 2015) identify this C++11 type. If that doesn't break any CI scenario, probably would be a good idea to replace all occurrences of `wchar_t` with `char16_t` to avoid confusion.

**Comment by jkotas** [comment]
`#include` order is carefully crafted in the PAL to avoid this type of problems. I suspect that this problem got introduced by your proposed fix for https://github.com/dotnet/coreclr/pull/2940

**Comment by krytarowski** [comment]
No, these issues are unrelated. I was fixing `cstdargs` later.

**Comment by krytarowski** [comment]
I will leave this file for ending. I want to build all the sources with a patch for `wchar_t` first.
