### ISSUE TITLE
[Question] Is offset to first array element the sam for all Sz arrays?

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#2942]
Slices project in CoreFX Lab uses  [a helper to get offset to the first element of an SzArray](https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/src/System/SpanHelpers.cs#L26).

Is the offset the same for all sz arrays of primitives, values types and references?

**Comment by jkotas** [comment]
I happens to be the case for CoreCLR runtime today, but it is internal implementation detail that may not hold for other runtimes, e.g. it was not the case in earlier versions of the full .NET Framework.

**Comment by omariom** [comment]
Thanks, that's interesting to know.
