### ISSUE TITLE
Decimal.GetHashCode shouldn't generate different values for numbers with different scale

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/coreclr#2944]
See https://connect.microsoft.com/VisualStudio/feedback/details/776203/
http://stackoverflow.com/questions/8533449/

Marking connect issue as won't fix without any comment is not nice. This issue makes decimal completely useless as a key in collections, that rely on GetHashCode result, like Dictionary or HashSet.

**Comment by tfenise** [comment]
Well, unlike the Stackoverflow question, the connect issue didn't give an example that would produce the bug.

**Comment by jkotas** [comment]
The code has logic that is supposed to “fix” this problem but this logic is not reliable – it just reduces frequency of the bug: https://github.com/dotnet/coreclr/blob/master/src/classlibnative/bcltype/decimal.cpp#L115 

The proper way to fix this would be to normalize the decimal before computing the hashcode.
