### ISSUE TITLE
NetBSD doesn't implement pthread_getcpuclockid(3)

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#2947]
This function is part of the optional part of POSIX:

> If `_POSIX_THREAD_CPUTIME` is defined, implementations shall support clock ID values obtained by invoking pthread_getcpuclockid(), which represent the CPU-time clock of a given thread. Implementations shall also support the special clockid_t value CLOCK_THREAD_CPUTIME_ID, which represents the CPU-time clock of the calling thread when invoking one of the clock_*() or timer_*() functions. For these clock IDs, the values returned by clock_gettime() and specified by clock_settime() shall represent the amount of execution time of the thread associated with the clock. Changing the value of a CPU-time clock via clock_settime() shall have no effect on the behavior of the sporadic server scheduling policy (see Scheduling Policies).

-- http://pubs.opengroup.org/onlinepubs/9699919799/functions/clock_getres.htm

This function is used in `src/pal/src/thread/thread.cpp`

I'm thinking whether there is need to implement it in NetBSD.

**Comment by krytarowski** [comment]
It's available in:
- FreeBSD,
- AIX,
- QNX,
- Linux.

**Comment by jkotas** [comment]
This is used for undocumented resource monitoring feature (`FEATURE_APPDOMAIN_RESOURCE_MONITORING`). AFAIK, nobody is using this feature on CoreCLR today. Everything should be fine if you do not implement this API for NetBSD - just return zeros from the API.

**Comment by krytarowski** [comment]
Thank you @jkotas for your feedback.

**Comment by jasonwilliams200OK** [comment]
This can be closed. :)

**Comment by krytarowski** [comment]
Please keep it open. NetBSD still doesn't implement this function and it's still in potential use in CoreCLR.

**Comment by jasonwilliams200OK** [comment]
> potential use

Reading @jkotas made me think that this is an optional feature which is disabled by #2976. If the NetBSD OS doesn't support this, then keeping it in CoreCLR issue tracker doesn't make much sense, don't you agree?

**Comment by krytarowski** [comment]
This patch hasn't fixed it by walking around the missing API or similar, we disabled the feature. I want to keep it on my TODO list.

**Comment by krytarowski** [comment]
`pthread_getcpuclockid`(3) and `clock_getcpuclockid`(2) landed NetBSD-current. For the current code there has been implemented intermediate solution.

Closing
