### ISSUE TITLE
Command line arguments that terminate with a / are causing the terminating double quote to be escaped

### ISSUE THREAD

**Issue by livarcocc** [dotnet/coreclr#2957]
When we have an argument in the command line of the format "\some stuff\", what is being passed to the main function in string[] args is some \stuff". This is wrong, the opening and closing double braces should be treated as string delimiters themselves and should not be escaped.

This is related to https://github.com/dotnet/cli/issues/1073.

**Comment by sergiy-k** [comment]
@wtgodbe, could you please take a look?

**Comment by wtgodbe** [comment]
@livarcocc are you talking about arguments to corerun?

**Comment by wtgodbe** [comment]
@livarcocc  Could you give me an example of a command-line invocation of corerun that reproduces this? I suppose I'm able to reproduce it locally, but the behavior of escape characters and quotes appears to be as-expected.

**Comment by livarcocc** [comment]
@wtgodbe I actually could not repro this today, and our CLI command that was failing seems to be working again with the slash.

This is what I tried before and fail and which succeeded now: dotnet publish --output "c:\users\licavalc\t
emp\"
