### ISSUE TITLE
Investigate if it is needed to model return registers after a call that is consumed by a return immediately.

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#2966]
In codegenxarch.cpp there in genStructReturn an assumption is made that the GT_CALL node has already stored the return values of multi-register return struct in the proper registers - RAX and RDX. A following GT_RETURN is assumed not to need to reload this registers in RAX and RDX.
Confirm that this assumption is right for the LSRA stress modes. Add necessary noway_asserts to make sure we detect if this assumption gets broken for any reason.

**Comment by CarolEidt** [comment]
This is not an issue to investigate. And it is not optional to ensure that registers are accurately modeled. It is a requirement.

**Comment by LLITCHEV** [comment]
Thanks for the clarification.

**Comment by pgavlin** [comment]
Should this be closed?

**Comment by LLITCHEV** [comment]
Dup of issue #2907
