### ISSUE TITLE
corerun fails on Linux: Managed object size does not match unmanaged object size

### ISSUE THREAD

**Issue by cnblogs-dudu** [dotnet/coreclr#298]
Build the up-to-date coreclr repo and corerun any .NET app, always get the following failures:
```
Assert failure (unable to format)
/data/git/coreclr/src/vm/binder.cpp
Consistency check failed: Managed object size does not match unmanaged object size
man: 0x18, unman: 0x20, Name: System.Runtime.InteropServices.CriticalHandle
FAILED: size == expectedsize
**** MessageBox invoked, title 'Assert failure (unable to format)' ****
  Consistency check failed: Managed object size does not match unmanaged object size
man: 0x18, unman: 0x20, Name: System.Runtime.InteropServices.CriticalHandle
FAILED: size == expectedsize
********

Assert failure (unable to format)
/data/git/coreclr/src/vm/binder.cpp
pFD != NULL
**** MessageBox invoked, title 'Assert failure (unable to format)' ****
  pFD != NULL
********
```

**Comment by cnblogs-dudu** [comment]
Fixes it by replacing release build of mscorlib.dll with debug build.

**Comment by linquize** [comment]
Is it normal "by replacing release build of mscorlib.dll with debug build"?

**Comment by janvorli** [comment]
@linquize No, it is not normal. But the mscorlib and libcoreclr.so are bound together so if they go out of sync (for example, you are trying to use a mscorlib built before a change in an object size happened and libcoreclr.so built from sources after the change, you would get this problem.
So I guess that the release build was fresher than the debug one in this case.

**Comment by linquize** [comment]
So, should we use the corresponding `mscorlib.dll`?
- mscorlib.dll Debug x64 with coreclr Debug x64
- mscorlib.dll Release x64 with coreclr Release x64

**Comment by cnblogs-dudu** [comment]
@linquize I tested the 4 combinations:
* [OK] mscorlib.dll Debug x64 with coreclr Debug x64.
* [FAIL] mscorlib.dll Release x64 with coreclr Debug x64
```
Consistency check failed: Managed object size does not match unmanaged object size
man: 0x18, unman: 0x20, Name: System.Runtime.InteropServices.CriticalHandle
FAILED: size == expectedsize
```
* [OK] mscorlib.dll Release x64 with coreclr Release x64
* [FAIL] mscorlib.dll Debug x64 with coreclr Release x64
```
terminate called after throwing an instance of 'PAL_SEHException'
Aborted
```
