### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Security ...' ocurring in windows rc1-final and osx rc1-update1

### ISSUE THREAD

**Issue by mogarick** [dotnet/coreclr#2980]

**Comment by mogarick** [comment]
I found out that the problem could belong to corefx not coreclr.
Sorry for the confussion.

**Comment by triciap** [comment]
Thanks for clearing that up for me. I didn't know the difference between my knees to my nipples before you posted this. Thanks 


Sent from my MetroPCS 4G LTE Android device-------- Original message --------From: mogarick <notifications@github.com> Date: 2/2/2016  5:48 PM  (GMT-08:00) To: dotnet/coreclr <coreclr@noreply.github.com> Subject: Re: [coreclr] System.IO.FileNotFoundException: Could not load file or
  assembly 'System.Net.Security ...' ocurring in windows rc1-final and osx
  rc1-update1 (#2980) 
I found out that the problem could belong to corefx not coreclr.

Sorry for the confussion.

**Comment by sergiy-k** [comment]
Hi @mogarick, would you be OK with closing this issue since you opened a corresponding issue in corefx (https://github.com/dotnet/corefx/issues/5858)? Thank you.

**Comment by mogarick** [comment]
Hi @sergiy-k 
Of course there's no problem. I wanted to close it by myself but I didn't find out how.

**Comment by sergiy-k** [comment]
Thank you, @mogarick! Please feel to re-open the issue if needed.
