### ISSUE TITLE
Conflicts with system headers on NetBSD

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#2993]
There are few conflicts with system headers on NetBSD

```
In file included from /tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/tests/palsuite/threading/GetThreadTimes/test1/test1.c:18:
In file included from /usr/include/sched.h:37:
In file included from /usr/include/sys/sched.h:73:
/usr/include/sys/types.h:54:18: error: typedef redefinition with different types ('__int8_t' (aka 'signed char') vs 'char')
typedef __int8_t        int8_t;
                        ^
/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/inc/pal_mstypes.h:224:16: note: previous definition is here
typedef __int8 int8_t;
               ^
```

```
In file included from /tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/tests/palsuite/threading/GetThreadTimes/test1/test1.c:18:
In file included from /usr/include/sched.h:40:
/usr/include/time.h:75:8: error: redefinition of 'tm'
struct tm {
       ^
/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/inc/pal.h:6374:8: note: previous definition is here
struct tm {
       ^
```

**Comment by jkotas** [comment]
Conflicts like this are dealt with by defining / undefing the symbol in `src\pal\src\include\pal\palinternal.h`, e.g. look for `fpos_t`.

**Comment by krytarowski** [comment]
`fpos_t` gives me headache too and I'm locally `ifdef`ing code using it.

**Comment by krytarowski** [comment]
I can see that these typedefs are under `!defined(PAL_STDCPP_COMPAT) && !defined(PAL_IMPLEMENTATION)`

```
#ifndef PAL_STDCPP_COMPAT
// Defined in gnu's types.h. For non PAL_IMPLEMENTATION system
// includes are not included, so we need to define them.
#ifndef PAL_IMPLEMENTATION
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
#endif // PAL_IMPLEMENTATION
```

-- `src/pal/inc/pal_mstypes.h`

We define `PAL_IMPLEMENTATION` in:
- `src/debug/debug-pal/CMakeLists.txt`
- `src/pal/src/include/pal/palinternal.h`

If I understand it correctly, on NetBSD we mustn't define `PAL_STDCPP_COMPAT` as we are already POSIX-like and must't define `PAL_IMPLEMENTATION` when consuming PAL.

What's the clean way to handle it? Stop including `<sched.h>` in the test?

**Comment by jkotas** [comment]
> Stop including  <sched.h>  in the test?

Yes. The PAL tests are not supposed to include system headers.

**Comment by krytarowski** [comment]
> Yes. The PAL tests are not supposed to include system headers.

Thank you! it's now clear. I'm going to drop this header and try to push building forward.

**Comment by krytarowski** [comment]
I got 98% and no other issues so far.
