### ISSUE TITLE
ASP.NET Core 1.0 Global exception handler in console application (DNX) 

### ISSUE THREAD

**Issue by dotnetshadow** [dotnet/coreclr#2999]
How do you catch global exceptions in an asp.net core console application? In previous versions we had AppDomain.CurrentDomain.UnhandledException but this doesn't seem to work in rc1

```
public class Program
{
    [STAThread]
    public static void Main(string[] args)
    {           
        #if !DNXCORE50
        // Register unhandled exception handler
        AppDomain.CurrentDomain.UnhandledException += new UnhandledExceptionEventHandler(UnhandledExceptionHandler);

        // Throw exception
        throw new Exception("1");

        #endif            
        Console.ReadLine();
    }



    #if !DNXCORE50


    /// <summary>
    ///  Catch all unhandled exceptions in all threads.
    /// </summary>
    /// <param name="sender"></param>
    /// <param name="args"></param>
    private static void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs args)
    {
        try
        {
            // Get the exception that was thrown
            Exception exceptionThrown = (Exception)args.ExceptionObject;

            Console.WriteLine("Information coming from exception handler");                                
        }
        catch (Exception ex)
        {                
            Console.WriteLine(ex.ToString());                
        }
    }
    #endif
}
```

The above only works in 4.5.1 but not dnxcore50, As soon as the exception is thrown the code breaks. Is there any way in a dnx app to catch unhandled exceptions?

**Comment by NickCraver** [comment]
I'm also curious what the mechanism is as well. We have global exception handlers that attach this way and log to a central location - some equally global capture method is really needed in .Net Core.

**Comment by janvorli** [comment]
@NickCraver, @dotnetshadow, there is currently no way to get event on unhandled exceptions in the .Net Core, mostly due to the fact that there is no AppDomain class, so the event has disappeared with it.
But I agree that it is a useful feature that we should put back. I am currently working on figuring out where to put such event.

**Comment by NickCraver** [comment]
@janvorli Totally understand on the app domain side; I think we all only care for the existence of the event not particularly where it lives. I don't really have a good solution for placement in mind but happy to help if we can.

**Comment by terrajobst** [comment]
Following our [API review process](http://aka.ms/apireview) I've file #CoreFX/6398.

**Comment by janvorli** [comment]
Closing this as the AppDomain.CurrentDomain.UnhandledException was added back in https://github.com/dotnet/corefx/pull/11275
