### ISSUE TITLE
Support VS 2015 as well?

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#30]
Installation of VS 2013 is a pre-requisite to build this repository.

I don't want to have both installed on my machine. Does it rely on anything specifically in VS 2013?

**Comment by gkhanna79** [comment]
Hi David,

Bringing VS 2015 support is of the top items on our list. Stayed tuned.

**Comment by davidfowl** [comment]
:sparkles:

**Comment by MattWhilden** [comment]
Anyone know what state this is in?

**Comment by MattWhilden** [comment]
I spoke to some follks around here about this and this is obviously still on the roadmap. Marking it as up-for-grabs because we believe that anyone with some gumption and VS2015 could get this put together. When things settle down internally, we'll pick this up if it's not corrected.

**Comment by jasonwilliams200OK** [comment]
@DickvdBrink and I can build coreclr master on VS2015 RC, https://github.com/dotnet/coreclr/issues/1033#issuecomment-104688632. Please reconfirm and update [this](https://github.com/dotnet/coreclr/blob/f185bf3ad3cd245bed9ca7f78c824865c2f450ec/Documentation/windows-instructions.md#visual-studio).

**Comment by DickvdBrink** [comment]
@jasonwilliams200OK, there seems to be something wrong now.. creating a debug build works but a release build fails with some `jit` issues I believe.

**Comment by jasonwilliams200OK** [comment]
@DickvdBrink, yes, mostly unresolved symbols in WKS etc. I am getting Linker errors.
