### ISSUE TITLE
Enable signing for CoreCLR binaries

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3019]

**Comment by gkhanna79** [comment]
@livarcocc I am assigning this to you since you are driving the overall signing integration for all the repos. 

CC @markwilkie @weshaggard

**Comment by gkhanna79** [comment]
@jhendrixMSFT Should this be assigned to you?

**Comment by gkhanna79** [comment]
@jhendrixMSFT Do we have the next steps identified for signing the binaries built in the open?

**Comment by gkhanna79** [comment]
@wtgodbe I have assigned this to you since you will be driving the signing of binaries using the build pipeline.

CC @sergiy-k

**Comment by gkhanna79** [comment]
@jhendrixMSFT I am assigning this to you to enable signing for native binaries in CoreCLR repo. If you have a tracking issue for driving that engineering work, please let me know.

CC @markwilkie @sergiy-k

**Comment by gkhanna79** [comment]
@jhendrixMSFT Can this be closed or is there anything outstanding?

**Comment by jhendrixMSFT** [comment]
@gkhanna79 This is now complete.
