### ISSUE TITLE
PAL fpos_t clash with NetBSD libraries

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#3029]
```
/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/src/cruntime/file.cpp:858:20: error: no viable overloaded '='
        native_pos = *pos;
        ~~~~~~~~~~ ^ ~~~~
```

**Comment by krytarowski** [comment]
```
/usr/include/stdio.h:67:16: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'PAL_fpos_t' (aka 'unsigned long') to 'const __sfpos' for 1st argument
typedef struct __sfpos {
               ^
/usr/include/stdio.h:67:16: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'PAL_fpos_t' (aka 'unsigned long') to '__sfpos' for 1st argument
/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/src/cruntime/file.cpp:860:14: error: assigning to 'PAL_fpos_t' (aka 'unsigned long') from incompatible type 'fpos_t' (aka '__sfpos')
        *pos = native_pos;
             ^ ~~~~~~~~~~
/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/pal/src/cruntime/file.cpp:904:20: error: no viable overloaded '='
        native_pos = *pos;
        ~~~~~~~~~~ ^ ~~~~
/usr/include/stdio.h:67:16: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'const PAL_fpos_t' (aka 'const unsigned long') to 'const __sfpos' for 1st argument
typedef struct __sfpos {
               ^
/usr/include/stdio.h:67:16: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'const PAL_fpos_t' (aka 'const unsigned long') to '__sfpos' for 1st argument
3 errors generated.
```

**Comment by jasonwilliams200OK** [comment]
See http://cvsweb.netbsd.org/bsdweb.cgi/src/include/stdio.h.diff?r1=1.79&r2=1.80&only_with_tag=MAIN&f=h and http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=commitdiff;h=f2c88dc.

(untested)

```c
 if (pos) {
#ifdef FPOST_IS___SFPOS_STRUCT
     native_pos->_pos = *pos;   // either it is _pos or _offset, I couldn't test
#else
     native_pos = *pos;
#endif
```

If we care about NetBSD < v6, then we can check `__NetBSD_Version__ >= 600000000` as before v6, it used to be an integer type. Same fix is for CYGWIN, which is not supported at the moment.

**Comment by jasonwilliams200OK** [comment]
Will still need to figure out how to detect `FPOST_IS___SFPOS_STRUCT` in cmake smartly. :wink:

**Comment by krytarowski** [comment]
Wow! good point! I will make the CMake part.

**Comment by krytarowski** [comment]
@jkotas I had a hack session with @jasonwilliams200OK and there are conclusions.

I don't understand how `PAL_STDCPP_COMPAT` is supposed to work, whether it should be defined, if so when? In what circumstances on what platforms?

Why `fpos_t` isn't reused from the system defines? Is it supposed to do it? Is it supposed to redefine its own `fpos_t` type?

Why `PAL_STDCPP_COMPAT` is defined for Unix in `src/ToolBox/SOS/Strike/CMakeLists`, why it's defined in `src/scripts/genXplatLttng.py`?

If everything is fine, then the right solution might be OS specific. Checking whether struct members exist isn't enough. Knowing the underlaying OS is needed to implement it. For NetBSD this looks correct:

```
diff --git a/coreclr-git/patches/patch-src_pal_src_cruntime_file.cpp b/coreclr-git/patches/patch-src_pal_src_cruntime_file.cpp
new file mode 100644
index 0000000..5322a23
--- /dev/null
+++ b/coreclr-git/patches/patch-src_pal_src_cruntime_file.cpp
@@ -0,0 +1,35 @@
+$NetBSD$
+
+--- src/pal/src/cruntime/file.cpp.orig 2016-01-28 19:04:13.000000000 +0000
++++ src/pal/src/cruntime/file.cpp
+@@ -844,6 +844,15 @@ PAL_fgetpos (
+     // TODO: implement for Linux if required
+     ASSERT(FALSE);
+     return -1;
++#elif defined(__NetBSD__)
++    off_t native_pos;
++
++    if ((native_pos = ftello(f->bsdFilePtr)) == -1)
++        return -1;
++
++    *pos = native_pos;
++
++    return 0;
+ #else
+     int    nRetVal = -1;
+     fpos_t native_pos;
+@@ -890,6 +899,14 @@ PAL_fsetpos (
+     // TODO: implement for Linux if required
+     ASSERT(FALSE);
+     return  -1;
++#elif defined(__NetBSD__)
++    off_t native_pos;
++
++    native_pos = *pos;
++    if (fseeko(f->bsdFilePtr, native_pos, SEEK_SET) == -1)
++        return -1;
++
++    return 0;
+ #else
+     int    nRetVal = -1;
+     fpos_t native_pos;
```

**Comment by krytarowski** [comment]
@jkotas When I will bring up debug messages and asserts from the `#else` code, are you OK with this patch?

**Comment by jkotas** [comment]
> Why  fpos_t  isn't reused from the system defines?

The PAL is designed to provide 100% abstraction from system headers.

> Why  PAL_STDCPP_COMPAT  is defined for Unix in  src/ToolBox/SOS/Strike/CMakeLists , why it's defined in  src/scripts/genXplatLttng.py ?

PAL_STDCPP_COMPAT allows some limited mixing and matching of PAL with system headers in a few places (essentially, violate the above design point).

**Comment by jkotas** [comment]
Both fgetpos and fsetpos looks like a dead code - the red flag is the comment `TODO: implement for Linux if required`, and I do not see it used anywhere.

So the best way to deal with this is to just delete these two function.

**Comment by jkotas** [comment]
(as well as PAL version of fpos_t)

**Comment by krytarowski** [comment]
Thank you. It's now clear. I'm going to submit a patch erasing these code-parts.
