### ISSUE TITLE
Cannot load CoreCLR.dll

### ISSUE THREAD

**Issue by wjk** [dotnet/coreclr#3047]
I am currently trying to debug a nasty problem in my CoreCLR GUI app (private repo). See #3040 for background. `coreclr.dll` is being found and loaded successfully, but when I call `ICLRRuntimeHost2::Start()` I always get HRESULT `HOST_E_INVALIDOPERATION`. No matter what I do, I cannot get that function call to succeed. However, an older version of this code loads CoreCLR just fine. In addition, having looked at the source for that function in corhost.cpp, I cannot find any immediate cause for this return code, beyond having called Start() twice (which I have proved is not the culprit through the C++ debugger).

@janvorli @JohnChen0 I see you have some experience triaging VM-related issues. Is there anything you can do to help me here? My project is completely blocked waiting for this issue to be solved.

**Comment by wjk** [comment]
My environment is Windows 10 x64, with Visual Studio 2015, if you're wondering.

**Comment by janvorli** [comment]
@wjk Would you be able to create a simple repro for the issue (where the app code would contain just an attempt to initialize coreclr)? If you shared that with me (ideally as a zip with all the files in folders where you want to have them), I can take a look at that on Monday.

**Comment by wjk** [comment]
Of course! How do you want it sent to you?

**Comment by wjk** [comment]
I have prepared a zip file of my application’s full built products. These are the exact files that I am using that exhibit this issue. (Even though this is my real app’s code, the reason why I can share it as-is is because the app itself hasn’t been written yet; all that has been implemented currently is a testing scaffold.)

Run the `EnvMgr.exe` file within the zip file > build directory. The PDB for that program is included; its filename is `EnvMgr.Launcher.pdb`. The source files for the `EnvMgr.exe` program are provided inside the zip file > src directory.

**Comment by gkhanna79** [comment]
Can you point me to the zip?

**Comment by wjk** [comment]
@gkhanna79 Interestingly, I solved this on my end last night. The problem was twofold: One, placing `coreclr.dll` in an SxS assembly doesn’t work; two, there seems to be a bug in 1.0.2-prerelease that prevents its loading with or without an SxS assembly. (I filed #3057 for that latter issue.) I ended up solving the problem by removing the SxS module entirely, and configuring CoreCLR to look for DLLs that are used as P/Invoke targets (which was the original source of this issue to begin with) using the [`NATIVE_DLL_SEARCH_DIRECTORIES`](https://github.com/dotnet/coreclr/blob/master/src/coreclr/hosts/coreconsole/coreconsole.cpp#L459) CLR property key.

If you still want the zip, I can throw it on my OneDrive, but this issue has been definitively solved now.

**Comment by gkhanna79** [comment]
> placing coreclr.dll in an SxS assembly doesn’t work;

I am not sure what you mean by SxS assembly. Can you please elaborate?

> configuring CoreCLR to look for DLLs that are used as P/Invoke targets (which was the original source of this issue to begin with) using the NATIVE_DLL_SEARCH_DIRECTORIES CLR property key.

This is the expected design. CoreCLR will only search folder specified by the property above to look for PInvoke target module resolution. How are you building and executing your app? With .NET CLI, this shouldnt be an issue for you.

**Comment by wjk** [comment]
SxS assemblies are [described on MSDN here](https://msdn.microsoft.com/en-us/library/windows/desktop/ff951640(v=vs.85).aspx). In addition, I understand that the `NATIVE_DLL_SEARCH_DIRECTORIES` value is the expected design; I spent a not-insignificant amount of time beating around the bush and ignoring the solution right in front of my nose.

Finally, I am not using .NET CLI because I am writing a GUI app on Windows, which necessitates the use of a custom `WinMain`-based entry point. .NET CLI cannot currently generate those, and nor should it (the correct design of such an entry point is very dependent on the specifics of the GUI framework being used).

**Comment by janvorli** [comment]
@wjk I am glad to hear that you've managed to solve the issue. Since it is clear what was going on, I don't think I need the package.

**Comment by sergiy-k** [comment]
Closing the issue since it seems to be resolved. @wjk, please let me know if that's not the case.
