### ISSUE TITLE
windows debug rebuilds may cause linker crashes

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#3049]
If you build x64 debug on windows, then modify some .cpp file and rebuild, you may see the linker crash. This is evidently will be fixed in VS2015 Update2, but for now, we should either disable /guard for debug builds, or disable incremental linking.

```
libcmtd.lib(loadcfg.obj) : fatal error LNK1000: Internal error during IMAGE::Pass2
[C:\Repos\coreclr\bin\obj\Windows_NT.x64.Debug\src\tools\crossgen\crossgen.vcxproj]
```

**Comment by gkhanna79** [comment]
Closing since fixed.
