### ISSUE TITLE
[JitStress=2] JIT/Regression/CLR-x86-JIT/V1.2-Beta1/b178119/b178119/b178119.exe Assert failure

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#3054]
x64 checked OSX
COMPlus_JitStress=2

https://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_checked_osx_jitstress2_rc2_tst/6/testReport/

MESSAGE:
BEGIN EXECUTION /Users/dotnet-bot/j/workspace/dotnet_coreclr/x64_checked_osx_jitstress2_rc2_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun b178119.exe Assert failure(PID 92218 [0x0001683a], Thread: 35438731 [0x21cc08b]): PTR_VOID(pRD->SP) >= pRD->_pThread->GetCachedStackLimit() File: /Users/dotnet-bot/j/workspace/dotnet_coreclr/checked_osx_rc2/src/vm/threads.cpp Line: 8243 Image: /Users/dotnet-bot/j/workspace/dotnet_coreclr/x64_checked_osx_jitstress2_rc2_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun **** MessageBox invoked, title 'corerun - Assert Failure (PID 92218, Thread 35438731/0x21cc08b)' **** PTR_VOID(pRD->SP) >= pRD->_pThread->GetCachedStackLimit() /Users/dotnet-bot/j/workspace/dotnet_coreclr/checked_osx_rc2/src/vm/threads.cpp, Line: 8243 Abort - Kill program Retry - Debug Ignore - Keep running Image: /Users/dotnet-bot/j/workspace/dotnet_coreclr/x64_checked_osx_jitstress2_rc2_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun ******** ./b178119.sh: line 55: 92218 Abort trap: 6 $_DebuggerFullPath "$CORE_ROOT/corerun" b178119.exe $CLRTestExecutionArguments $Host_Args Expected: 100 Actual: 134 END EXECUTION - FAILED
+++++++++++++++++++

**Comment by LLITCHEV** [comment]
This is a known issue in Mac OS, having to do with incorrectly reporting the stack limit. It was resolved in OSX version 10.11.2. There was an upgrade of the lab machines to El Capitan OS around the time the issue stopped reproducing. Closing this issue as resolved.
