### ISSUE TITLE
CoreCLR Loading Fails on 1.0.2-prerelease

### ISSUE THREAD

**Issue by wjk** [dotnet/coreclr#3057]
I was trying to get my Core GUI app (private repo) to run, and it could not load CoreCLR. (See #3047 for details.) However, if I remove my SxS setup (see #3040 for more details on that), `ICLRRuntimeHost2::Start()` still fails. The only way I can successfully load CoreCLR is to use version `1.0.1-beta-23225`. I have not been able to get version `1.0.2-prerelase` to load successfully _at all_. Does anyone else have any problems with this version of CoreCLR?

**Comment by ellismg** [comment]
I assume you are talking about the Microsoft.DotNet.CoreCLR package on the [dotnet-core](https://dotnet.myget.org/gallery/dotnet-coreclr) feed?

The packages on that feed are very old and out are no longer updated.  You should be using packages from the [dotnet-core](https://dotnet.myget.org/gallery/dotnet-core) feed.  You'll find newer versions of the 1.0.1 package you were using there.  Are you seeing the same issue on 1.0.1-rc2 or 1.0.1-rc3 builds?

@weshaggard Is it possible to un-list all the packages on that feed so folks don't get confused?  I know we already say the feed is deprecated, but if we can unlist the packages it will make it even harder for folks to pick up these old packages.

**Comment by wjk** [comment]
@ellismg And you would be correct. The only reason I used that feed at all was because I needed PDBs for `coreclr.dll` to help debug my problem, and that was the only place I could find them. However, I have since solved the original problem, and ceased usage of these deprecated packages. Is it OK to close this issue?

**Comment by ellismg** [comment]
Sound good.  I will bug folks to see what the plan on symbols is, we should have a better story than what you had to deal with.

**Comment by weshaggard** [comment]
@ellismg even if we were to unlist the package that wouldn't stop anyone from directly querying for that package at it would still work. unlisting only removes it from the full package query list but people can still get it directly if they reference the specific version.
