### ISSUE TITLE
Remove useless security checks

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#3064]
Investigate why the original fix caused spurious out of memory exceptions and remove it again:

https://github.com/dotnet/coreclr/pull/3027
https://github.com/dotnet/coreclr/pull/3063

**Comment by sergiy-k** [comment]
Hi @jkotas, is there anything else that needs to be done here in addition to https://github.com/dotnet/coreclr/pull/3233?

**Comment by jkotas** [comment]
This is all done.
