### ISSUE TITLE
Access violation exception when building Kestrel

### ISSUE THREAD

**Issue by ayende** [dotnet/coreclr#3065]
I'm trying to build Kestrel, specifically this version:
https://github.com/aspnet/KestrelHttpServer/commit/fa181819c1c97620d930b3006d529a2b83675815

When running the build.cmd command, it runs for a while, and then I get this error:

```
fail: Exit code -1073741819 from dotnet
fail: Stack trace:
   at View113af183da4a4e99a095e7cda4bb2c2e.RenderViewLevel0() in c:\Users\Ayende\AppData\Local\Temp\5b0a6408103e49e78333e18ab81c2b20-1.cs:line 11777
   at View113af183da4a4e99a095e7cda4bb2c2e.Render() in c:\Users\Ayende\AppData\Local\Temp\5b0a6408103e49e78333e18ab81c2b20-1.cs:line 12202
   at Sake.Engine.Loader.DefaultLoader.Load(Options options)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```

And looking into the debugger, we have:

```
Unhandled exception at 0x00007FF974B9C0CB (coreclr.dll) in dotnet.exe: 0xC0000005: Access violation reading location 0x00007FF9AE0CA7F4.

If there is a handler for this exception, the program may be safely continued.
```

This is 100% reproducible on my machine.

**Comment by ellismg** [comment]
@jkotas @JohnChen0 

The AV is in coreclr!ExternalMethodFixupWorker

```
0:000> kL
 # Child-SP          RetAddr           Call Site
00 000000dc`0ed7de00 00007ffa`013ca581 coreclr!ExternalMethodFixupWorker+0x1df
01 000000dc`0ed7e190 00007ffa`14874af7 coreclr!DelayLoad_MethodCall+0x71
02 000000dc`0ed7e240 00007ffa`1483d675 System_Reflection_Metadata_ni!System.Reflection.Internal.FileStreamReadLightUp.IsFileStream(System.IO.Stream)+0x37
03 000000dc`0ed7e270 00007ff9`a183d778 System_Reflection_Metadata_ni!System.Reflection.PortableExecutable.PEReader..ctor(System.IO.Stream, System.Reflection.PortableExecutable.PEStreamOptions, System.Nullable`1<Int32>)+0xa5
04 000000dc`0ed7e2f0 00000294`2906e810 Microsoft_DotNet_ProjectModel!Microsoft.DotNet.ProjectModel.Resolution.PackageDependencyProvider+<GetDependencies>d__5.MoveNext()+0xc8
05 000000dc`0ed7e2f8 00000294`2906e710 0x00000294`2906e810
06 000000dc`0ed7e300 00000000`00000000 0x00000294`2906e710
```

Specifically, here:

https://github.com/dotnet/coreclr/blob/release/1.0.0-rc2/src/vm/prestub.cpp#L1871

The AV happens while trying to do the dereference for `pSignatures[index]`.  This is the most recent build of RC2.  I'm on Windows 10.

**Comment by jkotas** [comment]
This should be fixed by #3059 and other native image related fixes that I have made in last day.

**Comment by sergiy-k** [comment]
Hi @ayende, may I please ask you to confirm that the problem that you reported has been fixed by https://github.com/dotnet/coreclr/pull/3059 so we could close the issue?

**Comment by ayende** [comment]
I'm not getting access violation any longer, but Kestrel isn't actually building.

PS C:\Work\KestrelHttpServer> dotnet --version
.NET Command Line Tools (1.0.0-beta-001598)

I'll close this and open a new bug for Kesterl
