### ISSUE TITLE
Enable incremental linking with CFG

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3069]
Essentially, undo the change required for https://github.com/dotnet/coreclr/issues/3049 once VS comes out with the fix.

**Comment by gkhanna79** [comment]
This is not a blocker for RTM and can be moved out.

**Comment by gkhanna79** [comment]
Removing the incremental:No option results in a break since /incremental (default) is not compatible with the explicitly specified /DebugType (https://github.com/dotnet/coreclr/blob/master/CMakeLists.txt#L338).

Per the docs (at https://msdn.microsoft.com/en-us/library/dn823750.aspx), specifying Fixup is helpful for kernel mode debugging. If we do not need to enable that, then CV need not be specified as it is implied when /DEBUG is specified (which we do).

Given the above, should we consider removing /DebugType statement completely @jkotas ?

**Comment by jkotas** [comment]
I think so. We have used the overridden DebugType to make the tools that analyzed PDBs work. We are not using those tools anymore.
