### ISSUE TITLE
cmake does not check libunwind on linux

### ISSUE THREAD

**Issue by linquize** [dotnet/coreclr#307]
cmake does not check libunwind on linux.
I did not install libunwind header, so it fails to compile in the middle.

I suggest to let cmake check that.

Also update doc to install `libunwind8-dev`
https://github.com/dotnet/coreclr/wiki/Building-and-Running-CoreCLR-on-Linux

**Comment by sergiy-k** [comment]
@janvorli was working on adding this check.

**Comment by kangaroo** [comment]
@sergiy-k I can bang this out today without any problem, so I'll submit a PR in a few hours (thus the self-assign :))

**Comment by janvorli** [comment]
@kangaroo That would be great! Thanks a lot.

**Comment by kangaroo** [comment]
PR: https://github.com/dotnet/coreclr/pull/310

Waiting for linux CI, since I didn't have time to check that fully before heading to work, but it should be ok.

**Comment by kangaroo** [comment]
PR merged, closing out.
