### ISSUE TITLE
Alleviate the need to have two mscorlib.dll in CoreCLR Nuget package

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3078]
This is required for Nuget rails verification, so we should figure out how to avoid this if we can help.

**Comment by gkhanna79** [comment]
Moving to 1.1.0 since this does not meet RTM bar.

**Comment by gkhanna79** [comment]
@ericstj Is this actionable or can it be closed?

**Comment by danmosemsft** [comment]
@ericstj ping for above q

**Comment by gkhanna79** [comment]
I believe this can be closed since now we only have s.p.c.dll in the nuget package.

**Comment by danmosemsft** [comment]
@ericstj closed as above

**Comment by ericstj** [comment]
FWIW the coreclr package is still containing both the NI and IL for System.Private.CoreLib.  Gaurdrails is no longer an issue but both files may be included for other reasons.  It'd probably be a good idea for folks working on the CLR to review all the content they are contributing to shared-framework / Core.App package and confirm that its all there and has a good reason for being there.

**Comment by gkhanna79** [comment]
With https://github.com/dotnet/coreclr/pull/11040, only a single SPC.dll is in the package - and it is either the IL assembly or NI renamed to SPC.dll.
