### ISSUE TITLE
Build break on non-Windows if Mono not installed

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#3085]
build.sh now has a dependency on Mono.  Without it, the non-Windows build will fail with the following.

  /bin/sh: 3: /tmp/tmp21cf5dbdf36948e8b3a4aaeb74ac2ff9.exec.cmd: resgen: not found

This fails even if `skipmscorlib` is passed to build.sh.  The `skipmscorlib` option should either be removed or made to work.  Please at least use this issue to fix that, even if you decide the Mono dependency is "by design."

Also, the docs like https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md still imply Mono is optional in places, e.g. "*(requires Mono)*", so IMO the docs should be updated even if this dependency isn't going to be removed immediately.

**Comment by gkhanna79** [comment]
Fixed with https://github.com/dotnet/coreclr/issues/3086
