### ISSUE TITLE
MScorlib builds depends upon Mono

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3090]
Looking into Mono's resgen invocation, it is getting invoked from GenerateSplitStringResources task in <repo_root>\src\mscorlib\GenerateSplitStringResources.targets.

This should be fixed to use dotnet-resgen to alleviate the additional Mono dependency. As part of fixing this, please remove the Mono check from build.sh

**Comment by ellismg** [comment]
I am going to fix this.

**Comment by gkhanna79** [comment]
@ellismg Thanks for fixing this Matt. Do we need to update CoreCLR's build tools version to pickup this change?

**Comment by ellismg** [comment]
I have updated my PR in CoreCLR to consume this stuff.

**Comment by borgdylan** [comment]
@ellismg I have recently switched to amd64 and managed to build coreclr itself. I can't seem to build mscorlib however. The CLI gets downloaded but msbuild's exe is not anywhere to be found.
