### ISSUE TITLE
NotFound pkgs on 'dotnet restore' (or dnu restore)

### ISSUE THREAD

**Issue by aviviadi** [dotnet/coreclr#3098]
With the following dependencies in project.json :
```
"frameworks": {
    "dnxcore50": {
      "dependencies": {

        "NETStandard.Library": "1.0.0-*",

        "Microsoft.AspNet.Hosting": "1.0.0-*",

        "Microsoft.AspNet.Hosting.Abstractions": "1.0.0-*",
        "Microsoft.AspNet.WebSockets.Server": "1.0.0-*",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-*"

      }
    }
  }

```
when I perform dotnet (dotnet-nightly from yesterday), or using dnu restore, there are many NotFound packages:
```
info :   NotFound https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.framework.configurationmodel/index.json 11489ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnet.websockets.server/index.json 13416ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json 13765ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnet.hosting.abstractions/index.json 13743ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.framework.configurationmodel/index.json 14038ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnet.server.kestrel/index.json 13550ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnet.hosting/index.json 14077ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.extensions.fileproviders.abstractions/index.json 25062ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json 25874ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnet.websockets.protocol/index.json 25915ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnet.hosting.server.abstractions/index.json 25976ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.configuration.json/index.json 25953ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnet.http.extensions/index.json 26300ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.options/index.json 26322ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnet.http.abstractions/index.json 26380ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.dependencyinjection/index.json 26224ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.configuration.abstractions/index.json 26469ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.platformabstractions/index.json 26318ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.configuration.commandline/index.json 26406ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.fileproviders.physical/index.json 26573ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.configuration.environmentvariables/index.json 26728ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.configuration/index.json 26759ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.fileproviders.abstractions/index.json 27097ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnet.http/index.json 26979ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.logging/index.json 26963ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.extensions.options/index.json 27917ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.logging.abstractions/index.json 27231ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.extensions.fileproviders.physical/index.json 28977ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/system.threading.tasks.extensions/index.json 29475ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnet.http.features/index.json 22548ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.primitives/index.json 19675ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnet.webutilities/index.json 13183ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/system.buffers/index.json 14053ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.net.http.headers/index.json 14153ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.configuration.fileextensions/index.json 13672ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/runtime.native.system.security.cryptography/index.json 1043ms
```
and obviously as a result my compilation fails.

I do able to compile successfully if I 'dnu restore' using :
```
"frameworks": {
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Console": "4.0.0-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Threading": "4.0.11-beta-23516",
        "Microsoft.AspNet.Hosting": "1.0.0-rc1-final",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
        "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
        "Microsoft.AspNet.WebSockets.Server":  "1.0.0-rc1-final"
      }
    }
  }
```

So, moving to dotnet cli and the new packages is impossible.
_Problem found on Ubuntu 14.04 (and I saw also Windows machine with the same fault)_

**Comment by shahid-pk** [comment]
package names that include AspNet  name have been renamed to AspNetCore in place AspNet.
see this announcement https://github.com/aspnet/Announcements/issues/144
You can take clues from these samples https://github.com/aspnet/cli-samples

**Comment by aviviadi** [comment]
Thanks for your reply.
I've change to AspNetCore.. still getting :
`
info :   NotFound https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.framework.configurationmodel/index.json 989ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting.abstractions/index.json 972ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json 1096ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.kestrel/index.json 1099ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.websockets.server/index.json 1103ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hosting/index.json 1117ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnetcore.websockets.server/index.json 1800ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnetcore.hosting/index.json 1871ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnetcore.hosting.abstractions/index.json 1882ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.framework.configurationmodel/index.json 1922ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnetcore.server.kestrel/index.json 1911ms
`

still doesn't find, also from NETStandard.Library..

**Comment by shahid-pk** [comment]
did you tried the samples for cli-samples repo ?

**Comment by aviviadi** [comment]
I used the cli-samples NuGet.config.  Now everything back to normal with 'dotnet' cli. 
Thanks for the help shahid-pk.

**Comment by aviviadi** [comment]
Sorry, I thought it was good.  
It seems it is narrowed to kestrel related missing packages..
My NuGet.config :
`<add key="AspNetCI" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="dotnet-cli" value="https://www.myget.org/F/dotnet-cli/api/v3/index.json" />
`

dotnet restore :
`
error: Unable to load package 'Microsoft.AspNet.Server.Kestrel'.
`

dotnet build
`
Could not find file '.../.nuget/packages/Newtonsoft.Json/6.0.6/lib/portable-net45+wp80+win8+wpa81+aspnetcore50/Newtonsoft.Json.dll'.
`

this is with updated dotnet-nightly.

**Comment by shahid-pk** [comment]
the package is Microsoft.AspNetCore.Server.Kestrel , you missed the core in the name  :+1:

**Comment by shahid-pk** [comment]
and this issue belongs to aspnet/home repository :smile:

**Comment by aviviadi** [comment]
`Unable to load package 'Microsoft.AspNetCore.Server.Kestrel'.... `
Maybe I should ask : **how can I print which packages are included in a specific feed ?** (and by that leave the issue here ;) )

**Comment by sergiy-k** [comment]
Hi @aviviadi, is this still an issue for you?

**Comment by aviviadi** [comment]
I am following Ayende's solution (https://gitter.im/dotnet/coreclr) - it works for him on Windows 10 (not windows 8), and I'll try it later today/tomorrow on Ubuntu.

**Comment by aviviadi** [comment]
I am closing this one (the problem as I understand is being treated)
