### ISSUE TITLE
 System.Security.Cryptography.X509Certificates Namespace missing from this repro and the need to validate its security?

### ISSUE THREAD

**Issue by duaneking** [dotnet/coreclr#31]
Earlier in the year I was digging deep into the .Net x509certificate2 and x509certificate objects (I was building a full blown CA from scratch) and noticed that both the certificate classes serialize the private key to disk by default due to the verifiable use of Persist-Key options in the constructors of the x509certificate2 and x509certificate classes using a default option set for CspProviderFlags that does not include CspProviderFlags.CreateEphemeralKey. This is verifiable via any number of web sites that show the source for .Net as well as with many different tools should you choose to do it yourself.

Looking further, In fact these .Net objects simply seem to be wrappers for a central old style crypto32.dll cryptographic context. What worries me about this is that looking at the code deeper I find that it seems to explicitly look in an on-disk file storage for public and private keys in the getters and setters for the PublicKey field on the x509certificate2 and x509certificate object.. despite the fact that I would otherwise expect them to only exist in memory. Based on this knowledge it seems to store my private key in this storage even if I do not want it to do so, because the constructor does not allow you to change this option and turn it off based on the constructor list I am seeing when I look at the documentation; So if you set() or get() from the PrivateKey field it is really just collecting it from this file/registry store behind the scenes.

I was very happy to see the .Net Core uploaded here, but I am not able to find the  System.Security.Cryptography.X509Certificates namespace or the objects so described in this repro.  

Please add them so that we can as a community validate the security of these objects as they currently looks to be insecure / backdoored if one wanted to be paranoid.

**Comment by xplicit** [comment]
@duaneking maybe you are looking for this? 

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Security/Cryptography/X509Certificates/X509Certificate.cs

and this (reference source for .NET)

https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/security/cryptography/x509certificates/x509certificate.cs

**Comment by jkotas** [comment]
System.Security.Cryptography.* is going to be published as a set of separate libraries in http://github.com/dotnet/corefx

**Comment by YingP99** [comment]
It's a working in progress. We need to port other security related libraries first before porting the X509Certificate; such as various hashing algorithms etc.

**Comment by duaneking** [comment]
@xplicit No these do not include everything.  Or even the X509Certificate2 object; you pointed to the older one.

@jkotas The source for it is available online easily already why not just add it to the repro? We can already see due to sites that host the reference source that the private keys are stored in a crypto context even if that was not the plan of the developer using the object, for example.

@YingP99 What is so bad about the code that already exists and is available through publicly available  reference source already?

**Comment by duaneking** [comment]
This should be reopened.

**Comment by jkotas** [comment]
@duaneking Please open a new issue in https://github.com/dotnet/corefx/issues repo with details if you believe there is more to fix.

**Comment by shanselman** [comment]
https://github.com/dotnet/corefx/tree/master/src/System.Security.Cryptography.X509Certificates ?
