### ISSUE TITLE
Seg Fault in ETW::MethodLog::MethodJitted on Ubuntu

### ISSUE THREAD

**Issue by eerhardt** [dotnet/coreclr#3101]
The https://github.com/dotnet/cli build is currently broken on Ubuntu because of a seg fault.

When I attached a debugger, I got the following stack trace:

```
(lldb) Process 19292 stopped
* thread #6: tid = 19300, 0x00007ffff79c021f libpthread.so.0`start_thread + 351, name = 'dotnet', stop reason = thread exiting
    frame #0: 0x00007ffff79c021f libpthread.so.0`start_thread + 351
-> 0x7ffff79c021f <start_thread+351>: addq   $0x90, %rsp
   0x7ffff79c0226 <start_thread+358>: xorb   %al, %al
   0x7ffff79c0228 <start_thread+360>: popq   %rbx
   0x7ffff79c0229 <start_thread+361>: retq
  thread #16: tid = 19317, 0x00007ffff641fc8c libcoreclr.so`ETW::MethodLog::MethodJitted(MethodDesc*, SString*, SString*, SString*, unsigned long, unsigned long) + 204, name = 'dotnet', stop reason = invalid address (fault address: 0x0)
    frame #0: 0x00007ffff641fc8c libcoreclr.so`ETW::MethodLog::MethodJitted(MethodDesc*, SString*, SString*, SString*, unsigned long, unsigned long) + 204
-> 0x7ffff641fc8c <ETW::MethodLog::MethodJitted+204>: movq   (%rdi), %rax
   0x7ffff641fc8f <ETW::MethodLog::MethodJitted+207>: movq   0x10(%rax), %rax
   0x7ffff641fc93 <ETW::MethodLog::MethodJitted+211>: callq  *%rax
   0x7ffff641fc95 <ETW::MethodLog::MethodJitted+213>: movl   $0x40000, %esi
```

To repro:

- git clone https://github.com/dotnet/cli.git
- cd cli
- ./build.sh

There will be a compile error of the form:

```
Compiling Microsoft.DotNet.ProjectModel for DNXCore,Version=v5.0
/home/eerhardt/git/cli/.dotnet_stage0/ubuntu.14.04-x64/share/dotnet/cli/bin/dotnet "compile-csc" "@/home/eerhardt/git/cli/src/Microsoft.DotNet.ProjectModel/obj/Debug/dnxcore50/dotnet-compile.rsp" returned Exit Code 139
```

if you run that command `/home/.../bin/dotnet "compile-csc" @".../dnxcore50/dotnet-compile.rsp"` in a loop, you will see `Segmentation fault (core dumped)`

Note: We are currently on build rc2-23805 in the dotnet/cli repo.

**Comment by piotrpMSFT** [comment]
Thanks for assigning. This issue is currently blocking CLI CI builds.

**Comment by janvorli** [comment]
This looks like the same as #5780 which I have failed to reproduce.

**Comment by eerhardt** [comment]
My machine repros it in the CLI build one in every two or three runs.

**Comment by piotrpMSFT** [comment]
@janvorli this repros on at least one flavor of Linux for every CI build of CLI awaiting merge. I also have a fairly stable repro on an Ubuntu14.04 VM if that helps.

**Comment by jkotas** [comment]
The crash happens at the following line in eventtrace.cpp because of g_pDebugInterface is null:

  ```
          // g_pDebugInterface is initialized on startup on desktop CLR, regardless of whether a debugger
            // or profiler is loaded.  So it should always be available.
            _ASSERTE(g_pDebugInterface != NULL);
            g_pDebugInterface->InitializeLazyDataIfNecessary();
```

The crash happens during process shutdown. We have executed TerminateDebugger that clears `g_pDebugInterface`, but there are still other threads running in the process that may be accessing it.

**Comment by jkotas** [comment]
So there are really two problems:
- Why is this expensive logging turned on by default on Unix? It does not look like the results are actually logged.
- The logging has races with shutdown that can lead to crash.

**Comment by piotrpMSFT** [comment]
@jankotas what controls logging on Unix? I can check if our build scripts are setting the flag...

**Comment by jkotas** [comment]
It seems to be unconditionally hardwired to be on in src\inc\eventtracebase.h:
`#define ETW_TRACING_CATEGORY_ENABLED(Context, Level, Keyword) (TRUE)`

**Comment by piotrpMSFT** [comment]
ok. We'll try out a fix once ready :)

**Comment by jkotas** [comment]
cc @ramarag @brianrob Could you please take a look at this? It is crash in the Unix event tracing during shutdown.

**Comment by jkotas** [comment]
#3110 should mitigate this crash. Leaving this open to implement the proper fix.

**Comment by sergiy-k** [comment]
@brianrob, do you have a fix for this issue?

**Comment by brianrob** [comment]
I don't have a final fix for this, but #3110 should have mitigated the crash.  Are you still seeing this?

**Comment by sergiy-k** [comment]
PR https://github.com/dotnet/coreclr/pull/3110 mitigated the crash by disabling event logging by default. I assume the issue will happen again if event logging gets enabled.

**Comment by brianrob** [comment]
The issue was that even when tracing was disabled (off) the crash still occurred because more code ran than should have.  #3110 fixed that, but you're right, with tracing on, it could still happen fort processes that terminate during the tracing session.

**Comment by leculver** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/5066.
