### ISSUE TITLE
CoreClr should provide a way to retrieve the verbatim command line string

### ISSUE THREAD

**Issue by cdmihai** [dotnet/coreclr#3103]
MSBuild currently relies on receiving the verbatim string from the command line so it can interpret it itself. In the full framework it used [Environment.CommandLine](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Environment.cs#L338) to obtain this string.

CoreClr changes the command line string (e.g. it removes un-escaped quotes) and thus breaks behaviour in MSBuild.

For apps that need the verbatim command line string, there should be a way to obtain this string. There are various scenarios where this is necessary like an app that wants to log the exact commandline that it was started with.

**Comment by jkotas** [comment]
The verbatim command line string is Windows-specific feature. It does not exist on Unix.

If you need this, you can just P/Invoke to GetCommandLineW when you are running on Windows...

**Comment by jkotas** [comment]
cc @pallavit

**Comment by pallavit** [comment]
@cdmihai   The following link has the review discussion where we chose not to expose Environment.CommandLine - https://github.com/dotnet/apireviews/blob/175fbe079d8190b3e1b617693863358cdae00162/2015-10-30_misc/README.md

As @jkotas mentioned it was primarily not exposed due to x-plat concerns.

**Comment by cdmihai** [comment]
Apparently it is possible to get this info on Linux and OSX:
http://stackoverflow.com/questions/821837/how-to-get-the-command-line-args-passed-to-a-running-process-on-unix-linux-syste
http://superuser.com/questions/27748/how-to-get-command-line-of-unix-process

Don't know if it is the raw command line though it looks like it.

**Comment by jkotas** [comment]
This won't help you to solve the problem with custom escape processing. 

The string you will get via this method will have the exact same arguments as what is returned by GetCommandLineArgs() - except that they will be in one long string, separated by spaces.

The command line escaping/expansion on Unix is done by shell only (and the rules differ from shell to shell). The "create process" system call on Unix gets array of strings as argument, and this exact same array is what the process sees.

**Comment by pallavit** [comment]
> The command line escaping/expansion on Unix is done by shell only (and the rules differ from shell to shell). The "create process" system call on Unix gets array of strings as command line arguments, and this exact same array is what the process sees as command line argument.

That is correct. Since, you seem to require this support only on Windows as @jkotas suggested it would be best to take dependency on GetCommandLineW directly.

**Comment by pallavit** [comment]
dotnet/apireviews/pull/19

**Comment by pallavit** [comment]
@cdmihai Let me know if you see any issues with the suggested work-around else I will go ahead and close this bug.

**Comment by cdmihai** [comment]
For now, we decided to accept different behaviour between platforms: on !windows, users have to explicitly escape the quotes: https://github.com/Microsoft/msbuild/issues/471#issuecomment-183053180

In the future we may look into modifying our parsing logic.

**Comment by pallavit** [comment]
Thanks :)
