### ISSUE TITLE
Initializing a class with static members depends on ordering. (throws TypeInitializationException)

### ISSUE THREAD

**Issue by hughbe** [dotnet/coreclr#3109]
Hi, I'm not sure if this is the right place for this (maybe dotnet/roslyn makes more sense).

I encountered the following code that *really* stumped me. The following code crashes with a TypeInitializationException, if you follow the comments below.

```
class Program
{
    static unsafe void Main(string[] args)
    {
        new InvalidClass();
    }
}

public class InvalidClass
{
    // UNCOMMENT this: works!
    /*private static readonly char[] s_hexUpperChars =
    {
        '0', '1', '2', '3', '4', '5', '6', '7',
        '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'
    };*/

    private static readonly char[] s_specialCharacterChars = new char[] { '%', '@', ',', '?' };
    private static readonly string[] s_specialCharacterHexEscapedStrings = HexEscapeCharsToStrings(s_specialCharacterChars);


    // Uncomment this: crashes with TypeInitializationException
    /*private static readonly char[] s_hexUpperChars =
    {
        '0', '1', '2', '3', '4', '5', '6', '7',
        '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'
    };*/

    private static unsafe string[] HexEscapeCharsToStrings(char[] characters)
    {
        var strings = new string[characters.Length];
        char* chars = stackalloc char[3];
        chars[0] = '%';

        for (int i = 0; i < characters.Length; i++)
        {
            char c = characters[i];
            Debug.Assert(c <= 0xFF);

            chars[1] = s_hexUpperChars[(c & 0xf0) >> 4];
            chars[2] = s_hexUpperChars[c & 0xf];
            strings[i] = new string(chars, 0, 3);
        }

        return strings;
    }
}
```

I think this is because members are initialized in order of appearance, since, if I move `s_hexUpperChars` above where `HexEscapeCharsToStrings` is called, there is no exception thrown.

This is confusing behaviour IMO, and should be corrected. I'm not sure if this is by design or a bug.

There are some solutions:
- On the compiler side, warn the user if calling a static property before its initialized if a situation where a TypeInitializationException is thrown occurs
The compiler could tell this if it detects that a function is called which references a static member is not initialized, and then give a warning saying this may cause a TypeInitializationException,

- Do not rely on the ordering of members when initializing them. Instead form some sort of dependency graph that detects the correct ordering of initializing members so that a TypeInitializationException is not thrown at runtime.

- Keep as is

**Comment by mikedn** [comment]
> Hi, I'm not sure if this is the right place for this (maybe dotnet/roslyn makes more sense).

Yep, Roslyn would make more sense, the runtime can't automagically fix broken code produced by the user/compiler.

> On the compiler side, warn the user if calling a static property before its initialized if a situation where a TypeInitializationException is thrown occurs.

How would the compiler know that a TypeInitializationException would be thrown at runtime?

> Fix the initialization process for static properties to call the constructor for a static property if it hasn't been initialized yet and appears after the function that calls it

What's a "constructor for the static property"?

**Comment by hughbe** [comment]
I've migrated this to dotnet/roslyn, so I'll close this now
