### ISSUE TITLE
Support on CentOS 7.1 

### ISSUE THREAD

**Issue by rohitshrivastava04** [dotnet/coreclr#3129]
In our organization, we are planning to develop our next big project on .Net Core and deploy on Linux. As of now its supported only on ubuntu. One thing which I am keen to know is when is the target to support coreclr on CentOS.

Can anyone tell me where is the CentOS support on the roadmap?

**Comment by jasonwilliams200OK** [comment]
@rohitshrivastava04, see 
https://github.com/dotnet/coreclr/blob/master/README.md#build-status
CoreCLR  and CoreFX builds on many Linux including CentOS, Red Hat Linux, Fedora, openSUSE and Ubuntu. You can even download the installer for CentOS7.1 from CLI repo https://github.com/dotnet/cli#installers.

**Comment by ellismg** [comment]
@leecow can comment on behalf of Microsoft's support promises around CentOS.  However, I can say that from an engineering standpoint CentOS 7 as a high priority target.  We get coverage per PR and per merge in CI, produce nuget packages with CentOS bits in them and the dotnet CLI also produces releases for CentOS.  If you find CentOS specific issues, we would love to hear them.

**Comment by rohitshrivastava04** [comment]
@jasonwilliams200OK at the suggested link (https://github.com/dotnet/coreclr/blob/master/README.md#build-status) I can see CentOS build status as unknown. 

![image](https://cloud.githubusercontent.com/assets/3762001/13055437/31f4611a-d407-11e5-9cd5-220d9909870c.png)

**Comment by shahid-pk** [comment]
@rohitshrivastava04  this is a point in time , this can happen to any os in ci. sometimes build breaks sometimes some pr that is not being merged yet has problems. you could try the dotnet/cli bits from its repo they have centos too i think. if that works fine you are good to go in my opinion. But if you want official Microsoft support (as in help support) you should wait for official reply.

**Comment by rohitshrivastava04** [comment]
@shahid-pk I have never seen anything but unknown.

**Comment by shahid-pk** [comment]
@rohitshrivastava04  may be the links to the ci jobs are broken(i am just speculating here) . Because on prs they are passing. look in any pending pr you will see.

**Comment by rohitshrivastava04** [comment]
@shahid-pk sorry for my lack of understanding on the term prs, could you please tell me what is prs and point me the link so that I can explore more.

**Comment by shahid-pk** [comment]
pr means pull request.
i think you need to try some examples on centos and if they don't work you need to log issues for these specific scenarios.

**Comment by ellismg** [comment]
There is a problem with the CI system right now where we are not running a bunch of jobs on merges into master.  This was an unintentional fallout of a refactoring.  We are going to re-enable the jobs today.  @shahid-pk is correct that we run CentOS build before any change is merged into the product.  In addition we have a bunch of internal testing that runs on CentOS we do inside Microsoft.

**Comment by ellismg** [comment]
The CI problem has been fixed and the CentOS jobs are now happening on ever merge and the badges are green.

**Comment by leecow** [comment]
As Matt mentions CentOS is a high priority target to support and is key to our internal testing. We're still working through what will be on the officially supported OS matrix for release time. With a bit of luck we'll be able to publish the initial matrix before too long.

**Comment by sergiy-k** [comment]
CentoOS is on the roadmap and is officially supported.
dotnet/cli can be downloaded from https://github.com/dotnet/cli/
I'm closing this issue but please feel free to re-open it if needed.
