### ISSUE TITLE
more clearly separate out or hide inlining provisional state in jit dumps

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#3134]
During inlining, the jit dump becomes hard to read. Information about prospective inlines (and their possible inline candidates) gets interleaved with information about ongoing compilation of the root function. The jit may do a fair amount of work with substantial amounts of dump output before an inline fails and the whole thing is tossed out. Most developers probably don't care to see any of this "in progress" inlining status and would be happy just seeing a summary of the final decision and  the new IR that makes it into the root method via inlining.

**Comment by omariom** [comment]
:+1:  because I quite often just do Ctrl+F "inlin".

**Comment by briansull** [comment]
Fixed with PR #6036

**Comment by RussKeldorph** [comment]
@briansull Did you intend to close this?

**Comment by briansull** [comment]
Yes
