### ISSUE TITLE
[Question] Where do I report a VS2015 CoreCLR tooling bug?

### ISSUE THREAD

**Issue by redknightlois** [dotnet/coreclr#3141]
I found a bug in the Solution Explorer using CoreCLR. Visual Studio 2015 wont show any file which has the form ```Filename.*.cs``` but CoreCLR will compile them. 

Where do I report that?

**Comment by jasonwilliams200OK** [comment]
Maybe roslyn? 

https://github.com/dotnet/roslyn/labels/Area-IDE

**Comment by redknightlois** [comment]
Closing, reposted at Roslyn.
