### ISSUE TITLE
dbgshim should be removed from the CoreCLR nuget package

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#3165]
The CoreCLR nuget package currently includes [lib]dbgshim.[dll/so/dylib] with it. This file is only used by debuggers, and isn't tightly coupled to the target CoreCLR. So this should be moved to its own NuGet package that clrdbg (the .NET Core debugger) can depend on, and no one else needs it.

**Comment by gkhanna79** [comment]
I have filed #3223 and assigned to @noahfalk to look into packaging for dbgshim.dll.

**Comment by gkhanna79** [comment]
I will remove dbgshim.dll reference from the CoreCLR package.

**Comment by gregg-miskelly** [comment]
Sounds good, but please wait for the new package to be created before you remove it from the existing one.

**Comment by noahfalk** [comment]
Gregg how urgent is it to get a new package? I'm trying to figure out if we can wait for Mike to finish his mac exceptions work or if its really urgent I can run with it.

**Comment by noahfalk** [comment]
@mikem8361

**Comment by gregg-miskelly** [comment]
As long as it isn't urgent to remove it from the main package (and I don't know why it would be -- I am the one who noticed that it was still in there when it shouldn't be), there is no great rush in creating the dbgshim package.

**Comment by gkhanna79** [comment]
@noahfalk Please remove dbgshim from the CoreCLR package (from both open and closed builds) as part of fixing https://github.com/dotnet/coreclr/issues/3224

**Comment by mikem8361** [comment]
@gregg-miskelly, @noahfalk , @gkhanna79. I really don't see why we need to remove dbgshim unless the 3meg or so is too much disk space.  This would require any third party debuggers (someday maybe) to also include this binary. Even though it isn't version dependent on coreclr, I think it would be simpler to always have all the binaries needed to debug coreclr together.

**Comment by gkhanna79** [comment]
Given that it is not required for runtime scenario, it maybe reasonable to take it out and any debugger requiring it should be able to pull it in via its nuget package.

And yes, 3MB can be a lot of disk space depending upon that target device (e.g. IoT, Phones, etc).

**Comment by bendono** [comment]
For current DotNet Full, I do a lot of onsite debugging. This requires that matching versions of clr.dll, mscordacwks.dll, and sos.dll are all on the machine. When this takes time, I may take a dump and analyze it on another machine, of course copying the above files along too.

In the future, we'll likely target CLR Core. I don't yet have experience with Core debugging, but I question how the removal of dbgshim will affect the onsite debugging process. Will any copy of the file be enough? Or is it version-dependent that must match the installation? If the latter, I image the removal would make debugging more difficult and would much prefer that it be included in the runtime nuget. Also, for some customers, it is quite difficult to get approval to copy an external file (dbgshim) from USB / CD / network to a production server. Having it all in one place upfront would be preferable in such cases.

Another option is to document that the file is not required and let those with limited disk space remove it at will.

**Comment by gregg-miskelly** [comment]
dbgshim doesn't need to match the version of CoreCLR you are running.

**Comment by gregg-miskelly** [comment]
Put another way - dbgshim is different from the other debugger components. The other components (sos, dac, dbi) are all tightly coupled with the runtime, so there is a reasonable argument for including them in the CoreCLR package. Dbgshim is really a utility library for debuggers which target CoreCLR. So any given debugger might care about what version of dbgshim they are using (because new capabilities are added over time) but it should be distributed with these debuggers rather than CoreCLR.

**Comment by bendono** [comment]
@gregg-miskelly Thanks for the explanation. Looks like my concerns were unfounded.

**Comment by tzwlai** [comment]
After discussing with @mikem8361 and @lt72, I'm moving this out to 1.1 since it's not critical for RTM.

**Comment by mikem8361** [comment]
Just a reminder: if dbgshim is removed from the main package, a new separate package will have to be created. Otherwise, our debugger tests will be broken and any other third party managed debugger (if any exist) won't have access to the shim for launch.

**Comment by lt72** [comment]
@gregg-miskelly: this issue did not see any action fora long time and size on disk is not a concern for 2.1. Do you still need this change or should we close it?

**Comment by gregg-miskelly** [comment]
I opened the bug for the CLR's benefit. So do what you want with it.
