### ISSUE TITLE
gen-dactable-rva.sh does not print to dactablerva.h

### ISSUE THREAD

**Issue by jasonwilliams200OK** [dotnet/coreclr#3168]
@mikem8361,

We are getting build breakage at 99% on NetBSD due to the gen-dactable-rva.sh not writing define statement to dactablerva.h.

Investigated further and found the term g_dacTable doesn't exists in libcoreclr.so, but there are couple of g_dac available when searched with this command:

`grep -C 1 g_dac /tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/bin/obj/NetBSD.x64.Debug/src/dlls/mscoree/coreclr/libcoreclr.so -a > dump`

Is there another / better way to implement it?

cc @krytarowski

**Comment by krytarowski** [comment]
I'm working on it. Yes, `g_dacTable` is unavailabl in `libcoreclr.so` - I'm investigating it.

**Comment by krytarowski** [comment]
It looks like the symbol is present in `cordbee_wks` but once linked into `liboreclr.so` it's hidden or dropped.

**Comment by jasonwilliams200OK** [comment]
It looks like this note is related:
https://github.com/dotnet/coreclr/blob/c4a0fb1/src/dlls/mscoree/coreclr/CMakeLists.txt#L62-L87

> \# IMPORTANT! Please do not rearrange the order of the libraries. The linker on Linux is
\# order dependent and changing the order can result in undefined symbols in the shared 
\# library.

Although we haven't changed the order; one major difference is that we are using llvm libunwind on NetBSD, instead of HP libunwind.

**Comment by krytarowski** [comment]
I have got a working patch. I'm going to prepare Pull-Request soon. Thanks @brucem for pointing out what's wrong.

**Comment by jasonwilliams200OK** [comment]
Thanks @krytarowski for the fix! :tada:
