### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'System.Runtime' in Ubuntu 15.10

### ISSUE THREAD

**Issue by elw00d** [dotnet/coreclr#3174]
Tried to `dotnet run` for hello-world app (from https://dotnet.github.io/getting-started/ guide). Build was successfull, but execution has failed with error:

```
$ dotnet run
Compiling dotnet for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.4364181


Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Version of dotnet was 1.0.0.001331-1

**Comment by ellismg** [comment]
Presently we only support Ubuntu 14.04.  Support for 15.10 for CoreCLR, CoreFX and CLI is on the roadmap, but not everything has landed yet.

**Comment by jkotas** [comment]
Many different Linux distros are supported now: https://www.microsoft.com/net/learn/get-started/linuxredhat
