### ISSUE TITLE
Figure out how to handle 'libcorlib.so' in mscorlib build

### ISSUE THREAD

**Issue by kangaroo** [dotnet/coreclr#318]
The mscorlib unix build currently assumes that libcoreclr.so is the target, which obviously doesn't work on mac.

We should figure out what the plan is here.  I don't particularly like the idea of having a 'mac' build of mscorlib, since it shouldn't be needed.

For mono what we did was allow people to do:

[DllImport("coreclr")]

Then we would fallback to a defined series of probes, check the exact name, add platform prefix ('lib'), probe, add platform suffix ('.dylib'), probe, etc.  Not the most elegant solution, and the dll map stuff was even worse.

I'm not sure what a great middle ground is.  Change it to "libcoreclr", and always append the platform specific suffix?

Thoughts?

**Comment by sergiy-k** [comment]
@kangaroo Yes, we should remove the ".so" from DllImport. PAL should already be able to take care of that. That's the change I want to do as well - just have not had a chance to do that.

**Comment by kangaroo** [comment]
This was merged.
