### ISSUE TITLE
Add TryParse overloads accepting substrings

### ISSUE THREAD

**Issue by jack-pappas** [dotnet/coreclr#3184]
With the current .NET APIs, there's no way to use the `TryParse` methods (e.g., for `Int32`, `Double`, `DateTime`) on just part of a `string` instance (a substring). The only way to implement such a thing using the current `TryParse` APIs is to first call [`String.Substring(int,int)`](https://msdn.microsoft.com/en-us/library/aka44szs%28v=vs.110%29.aspx) on the string to first extract the substring, then pass the new string instance to whatever `TryParse` method you're calling. The downside is that this allocates an unnecessary string instance for every field you need to extract; the only workaround is to manually implement the specific parsing method you need, but then you lose the extra functionality provided by the `Parse` / `TryParse` methods such as octal and hex integer parsing.

For example, [`Double.TryParse`](https://msdn.microsoft.com/en-us/library/994c0zb1%28v=vs.110%29.aspx) would get an additional overload with a signature like:

``` csharp
public static bool TryParse(string s, int startIndex, int length, out double result)
```

**Comment by omariom** [comment]
It is very likely that such methods will get overloads taking [Slices](https://github.com/dotnet/roslyn/issues/120).

**Comment by varocarbas** [comment]
Not sure if I can propose this here (or only the .NET team can participate in the implementation of these proposals), but I wouldn't mind to take care of this functionality (in case of being accepted). 

Note that I have recently been working on optimising the method which analyses the input strings to all the numeric-type Parse/TryParse. That's why I am quite familiar with this part of the code.

**Comment by omariom** [comment]
@varocarbas 
Then you  probably will be interested in [this project in CoreFx Lab](https://github.com/dotnet/corefxlab/wiki/System.Text.Formatting). It is about efficient parsing and formatting.

**Comment by varocarbas** [comment]
@omariom Thanks for the info.

Just to clarify, I do have recent relevant experience in the exact part of code which takes care of what @jack-pappas  is requesting; at least for numeric types. That is: int.Parse/int.TryParse, decimal.Parse,ParseTryParse, etc. all their inputs are analysed by precisely this function (no experience in DateTime.Parse or others; although it should be quite similar).

What you say has also to do with parsing, but is not so related to my current experience. In any case, what do you mean exactly? Shall I take a look at the opened issues there? Is my proposal acceptable? Can I propose to write the code which is required to implement an opened issue or only .NET team members can do that?

**Comment by omariom** [comment]
@varocarbas 
System.Text.Formatting  is being developed in open. And it is not only about Datetime. So you can help with bug reports, implementing functionality, fixing bugs, improving performance etc.

**Comment by varocarbas** [comment]
@omariom  It sounds good. I will take a look. Thanks.

Do you know the answer to my doubt (= writing the code for an issue anyone vs. only the .NET team)? Or there is no general policy on this front?

**Comment by shahid-pk** [comment]
@varocarbas anyone can fix a bug or write code for any issue and propose their fix with a pr. Then the fix or pr is reviewed by team members , they will suggest some changes and ask you some questions if they don't understand the intents of your change. They will merge your pr/fix once every concern is tackled. This is a general workflow for some simple contributions they will just merge them. 
 Their are contribution guidelines in this repository's documentation directory. You can get more info their about the coding style and other things.

**Comment by varocarbas** [comment]
@shahid-pk  Thanks for your answer.

So, I can go ahead and write a code implementing jack-pappas's suggestion (by assuming that he doesn't mind), submit a pull-request and wait for the .NET team decision. Right?

**Comment by stephentoub** [comment]
The process for adding new public APIs is outlined here:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

**Comment by shahid-pk** [comment]
@varocarbas  as stephentoub (coreclr team member) pointed out if your change/pr  contains api's that are public you have to go through the process that he has provide link to and about wheather jack-pappas will mind or not only jack-pappas can answer.

**Comment by varocarbas** [comment]
Thanks to everyone for the answers.

I had a free a while and decided to go ahead and give it a shot. I have implemented and tested a first version for numeric types (i.e., working with one, but extending it to others wouldn't take more than 1 min., because all of them rely on the same methods). It follows the original structure perfectly, doesn't have any impact on performance (BTW, I have pulled a modification to appreciably improve the performance of all the Parse/TryParse methods; so, even a little impact might have been OK) and can easily be used anywhere else (e.g., DateTime).

What should I do with this code? Delete it (it was a not-too-long and nice distraction, so no problem; as said, I have quite good recent experience in exactly this part)? Share it? Pull it?

**Comment by Yves57** [comment]
@davidfowl has the same request in aspnet/AspLabs#3

I tried to add the missing methods in [Number.cs](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Number.cs):
```
internal unsafe static Boolean TryStringToNumber(String str, Int32 index, NumberStyles options, ref NumberBuffer number, StringBuilder sb, NumberFormatInfo numfmt, Boolean parseDecimal)
{.....}
internal unsafe static Boolean TryParseInt32(String s, Int32 index, NumberStyles style, NumberFormatInfo info, out Int32 length, out Int32 result)
{.....}
```

They are just copy/paste of the existing methods with very few modifications, and it works very well. The best is that nothing has to be changed in the complex `Number.ParseNumber()` method.

So I think it could be easy to add:
```
struct Int32
{
   int Parse(String s, Int32 index);
   int Parse(String s, Int32 index, NumberStyles style);
   int Parse(String s, Int32 index, IFormatProvider provider);
   int Parse(String s, Int32 index, NumberStyles style, IFormatProvider provider);
   int Parse(String s, Int32 index, out Int32 length);
   int Parse(String s, Int32 index, NumberStyles style, out Int32 length);
   int Parse(String s, Int32 index, IFormatProvider provider, out Int32 length);
   int Parse(String s, Int32 index, NumberStyles style, IFormatProvider provider, out Int32 length);
   bool TryParse(String s, Int32 index, out Int32 value);
   bool TryParse(String s, Int32 index, out Int32 value, out Int32 length);
   bool TryParse(String s, Int32 index, NumberStyles style, IFormatProvider provider, out Int32 value);
   bool TryParse(String s, Int32 index, NumberStyles style, IFormatProvider provider, out Int32 value, out Int32 length);
}
```

And the same for the other types...

**Comment by stephentoub** [comment]
This will be satisfied by https://github.com/dotnet/corefx/issues/22403, so I'm going to close this issue.
