### ISSUE TITLE
Building arm64 cross debug from ubuntu fails compiling gccover.cpp

### ISSUE THREAD

**Issue by dls314** [dotnet/coreclr#3186]
The instruction defines in gccover.h (https://github.com/dotnet/coreclr/blob/master/src/vm/gccover.h#L98-L105) used in gccover.cpp (https://github.com/dotnet/coreclr/blob/master/src/vm/gccover.cpp#L1135-L1147) cause compilation to fail because they are too large.

I'm not sure what the intent is here, but for what it's worth, I think that the comment is incorrect and these instructions would fall in the instructions covered in section C3.5.1 Add/subtract (extended register) range for the arm64 v8 specification mentioned.

In any case, this is blocking amd64 cross debug build for me on Ubuntu 14.04.3 as per the instructions in https://github.com/dotnet/coreclr/blob/master/Documentation/building/cross-building.md

It seems possible that this might be skipped with skiptests, I'll try that.

**Comment by sdmaclea** [comment]
@jashook I did not see an issue here.  This should be closed.

**Comment by jeffschwMSFT** [comment]
Closing per the commend above
