### ISSUE TITLE
ildasm issue when loaded from PATH on Linux

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/coreclr#3190]
I've copied ildasm, libcoreclr.so and mscorlib.dll in a bin folder of my home directory and added it to my path (```/home/user/bin```):

```
> echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/user/bin
```

When I execute ```ildasm``` directly as below, it gives a not so meaningful error message:
```
> ildasm ~/local/System.Runtime.dll
Error: Fail to load /libcoreclr.so
```

If I execute it with the explicit path, then it works just fine:
```
> ./bin/ildasm ~/local/System.Runtime.dll

//  Microsoft (R) .NET Framework IL Disassembler.  Version 4.5.22220.0
```

The issue seems to be in the unix core loader, and the usage of the GetAbsolutePath which returns an empty string. Looking at why this is failing.

**Comment by manu-silicon** [comment]
Found that the implementation of GetAbsolutePath relies on realpath which relies on the path existing, which is not the case when you get ilasm from the PATH environment variable.

**Comment by wtgodbe** [comment]
@manu-silicon was this fixed by https://github.com/dotnet/coreclr/issues/3191 as you expected?

**Comment by manu-silicon** [comment]
Yes, closing the issue.
