### ISSUE TITLE
Bench.asm.exe generated for a few benchmarks

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#3202]
A few of the BenchF benchmarks generate a .asm.exe file in addition to .exe file
For example: 
coreclr\bin\tests\Windows_NT.x64.Release\JIT\Performance\CodeQuality\BenchF\Adams\Adams\Adams.asm.exe
coreclr\bin\tests\Windows_NT.x64.Release\JIT\Performance\CodeQuality\BenchF\InvMt\InvMt\InvMt.asm.exe
coreclr\bin\tests\Windows_NT.x64.Release\JIT\Performance\CodeQuality\BenchF\LLoops\LLoops\LLoops.asm.exe
coreclr\bin\tests\Windows_NT.x64.Release\JIT\Performance\CodeQuality\BenchF\Romber\Romber\Romber.asm.exe

I think this is to test the ildasm/ilasm version of the benchmark? 
Do we need to generate/measure against these tests in the CoreCLR tree, if not, would be good to get rid of the .asm.exe tests.

**Comment by AndyAyersMS** [comment]
Suspect it's the 
```
    <IlasmRoundTrip>true</IlasmRoundTrip>
```
in the csproj that is the culprit. I don't think we need this. @kyulee1 do you agree?
