### ISSUE TITLE
Make ConditionalWeakTable the same as in CoreRT

### ISSUE THREAD

**Issue by mjp41** [dotnet/coreclr#3206]
There are several concurrency issues in the [ConditionalWeakTable](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/CompilerServices/ConditionalWeakTable.cs), these have been fixed in CoreRT's [ConditionWeakTable](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/ConditionalWeakTable.cs).  

The redesign in CoreRT should be integrated into CoreCLR.

**Comment by stephentoub** [comment]
It'd be nice to bring over the CoreRT design for other reasons... IIRC, the CoreRT ConditionalWeakTable provides for lock-free reads, whereas the CoreCLR one requires a lock.

**Comment by mjp41** [comment]
I think it is attempting to do lock-free reads here:

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/CompilerServices/ConditionalWeakTable.cs#L238

But I don't think that is correct.  The CoreRT version does this correctly.

**Comment by stephentoub** [comment]
> I think it is attempting to do lock-free reads here

No, TryGetValue takes a lock:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/CompilerServices/ConditionalWeakTable.cs#L109

**Comment by mjp41** [comment]
Sorry, you are correct.  I had spent too much time starring at the other.  Thank you.  I think the version is correct, so I retract my comments on concurrency.  

But making them the same would be good.  I am planning to address an [issue](https://github.com/dotnet/corert/issues/872) in CoreRT for the ConditionalWeakTable.

**Comment by stephentoub** [comment]
I'll take a look at porting the corert lock-free reads support back to CoreCLR...
