### ISSUE TITLE
Failure at runtime when IL DLL filename does not match IL source assembly name.

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#3216]
Suppose an IL file, e.g. sinlib.il, has these directives inside it:

```
.module 'sinlib_il.dll'
.assembly 'sinlib_il' {}
```

but that sinlib.il is compiled as part of a sinlib_il_r.ilproj file, yielding a
sinlib_il_r.dll.

If another project, e.g. sin.csproj, has a project reference to sinlib_il_r.ilproj,
then in the runtime directory sinlib_il_r.dll will be present, but the
program at runtime will fail, with a message like this:

```
  Unhandled Exception: System.IO.FileNotFoundException: 
  Could not load file or assembly 'sinlib_il, Version=0.0.0.0, Culture=neutral, 
  PublicKeyToken=null' or one of its dependencies. 
  The system cannot find the file specified.
           at SinCalc.SinCalc.Main()
```

The following tests (to be added soon) fail because of this:

```
JIT\methodical\boxing\xlang\_dbgsin_cs_il.csproj
JIT\methodical\boxing\xlang\_odbgsin_cs_il.csproj
JIT\methodical\boxing\xlang\_relsin_cs_il.csproj
JIT\methodical\boxing\xlang\_orelsin_cs_il.csproj
```

**Comment by gkhanna79** [comment]
Since the reference inserted during managed compilation (of sinlib_il_r.dll) is for "sin_il", the loader will look for the latter only. There is no way for it know which file contains the assembly other than the one that has the same name as the assembly.

The test should be fixed.

**Comment by BruceForstall** [comment]
It seems like these work now.

**Comment by RussKeldorph** [comment]
Closing stale
