### ISSUE TITLE
Please provide intrinsics for SIMD bit shift operations

### ISSUE THREAD

**Issue by m08pvv** [dotnet/coreclr#3226]
Please provide intrinsics for operations like vprold, vprord, etc.

This instructions are quite often used in functions like hash functions and it's necessary to have intrinsics for the operations for the best performance. It's not always possible to leave managed code for calculations because of related overhead.

It would be really nice to have this intrinsics in RyuJIT and in System.Numerics.Vectors

**Comment by benaadams** [comment]
Already does in CoreCLR? Patterns recognised https://github.com/dotnet/coreclr/blob/master/src/jit/morph.cpp#L12430-L12465

**Comment by m08pvv** [comment]
@benaadams It seems to be related to already closed issue #1619 and it works great. But I need SIMD shift instructions to be able to do 4 shifts with a single instruction. And it seems to be not implemented yet.

**Comment by redknightlois** [comment]
@benaadams No, that particular one is for single register ror instructions. What @m08pvv probably needs is the SSE equivalent (shift with mask or shuffle bytes).

You should add the support here: https://github.com/dotnet/corefx/issues/2209

**Comment by m08pvv** [comment]
@redknightlois Yes, it's AVX-512 instructions, but it would be nice to have as much as possible of SIMD instruction intrinsics.

**Comment by krytarowski** [comment]
How about `NEON` for `ARM`?

**Comment by redknightlois** [comment]
@krytarowski ```NEON``` seams to be a higher level function set (specially DSP and Physics) but probably many of the math functions would be part of the intrisics support of ```System.Numerics``` namespace if ARM NEON is supported at all.

**Comment by 4creators** [comment]
Issue is currently under formal API proposal review [API Proposal: ShiftLeft, ShiftRight for Vector<T>](https://github.com/dotnet/corefx/issues/16835)

**Comment by 4creators** [comment]
@jkotas Prhaps it could be closed as it is now tracked by [API Proposal: ShiftLeft, ShiftRight for Vector&lt;T%gt;](https://github.com/dotnet/corefx/issues/16835)

**Comment by jkotas** [comment]
ok
