### ISSUE TITLE
DateTime comparison code duplicated

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/coreclr#3227]
`public int CompareTo(Object value)` first checks the other object is `DateTime` and then does what `public int CompareTo(DateTime value)`. Also `public static int Compare(DateTime t1, DateTime t2)`
does essentially the same as what `CompareTo(DateTime value)` does.

Is there any need for that? If not then `public static int Compare(DateTime t1, DateTime t2)` should be kept unchanged and the other two methods should reuse it.

**Comment by tarekgh** [comment]
This is done
