### ISSUE TITLE
Implement Marshal.GetFunctionPointerForDelegate for Linux and OSX

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/coreclr#324]
We need to implement Marshal.GetFunctionPointerForDelegate for Linux and OSX because it is required for implementation of managed debugger.

In order to make Marshal.GetFunctionPointerForDelegate work, we need to implement assembly code for the UM*Stub functions. These functions are currently stubbed out in src/vm/amd64/unixstubs.cpp. Windows implementation of this functions is located in src/vm/amd64/UMThunkStub.asm. We need to create src/vm/amd64/umthunkstub.S for Linux and port Windows code in there.

Here is a simple example that can be used to test this code:

using System;
using System.Runtime.InteropServices;

namespace ConsoleApplication1
{
    class Program
    {
        [DllImport("libdl", SetLastError = true, CharSet = CharSet.Ansi)]
        static extern IntPtr dlopen([MarshalAs(UnmanagedType.LPStr)]string lpFileName, int mode);

        [DllImport("libdl", CharSet = CharSet.Ansi, ExactSpelling = true, SetLastError = true)]
        internal static extern IntPtr dlsym(IntPtr hModule, string procName);

        const int RTLD_NOW = 0x2;

        // Handle returned by dlopen()
        static IntPtr s_moduleHandle = IntPtr.Zero;

        static void Main(string[] args)
        {
            s_moduleHandle = dlopen("libc.so.6", RTLD_NOW);
            if (s_moduleHandle != IntPtr.Zero)
            {
                TestGetDelegateForFunctionPointer();
                TestGetFunctionPointerForDelegate();
            }
            else
            {
                Console.WriteLine("Failed to load libc");
            }
        }

        public delegate uint GetCurrentProcessIdDelegate();
        static void TestGetDelegateForFunctionPointer()
        {
            Console.WriteLine("TestGetDelegateForFunctionPointer");

            // Get getpid Function Pointer
            IntPtr ptr = dlsym(s_moduleHandle, "getpid");
            if (ptr != IntPtr.Zero)
            {
                // Convert Function Pointer to Delegate
                GetCurrentProcessIdDelegate getCurrentProcessIdDelegate = (GetCurrentProcessIdDelegate)Marshal.GetDelegateForFunctionPointer(ptr, typeof(GetCurrentProcessIdDelegate));

                // Call getpid()
                Console.WriteLine("Current process id: {0}", getCurrentProcessIdDelegate.Invoke());
            }
        }

        public delegate int CompareCallBackDelegate(IntPtr value1, IntPtr value2);
        public delegate int ScanDirecroriesDelegate(string dir, ref IntPtr namelist, IntPtr filterCallback, IntPtr compareCallBack);
        static void TestGetFunctionPointerForDelegate()
        {
            IntPtr namelist = IntPtr.Zero;

            Console.WriteLine("TestGetFunctionPointerForDelegate");

            IntPtr ptr = dlsym(s_moduleHandle, "scandir");
            if (ptr != IntPtr.Zero)
            {
                // Convert Function Pointer into Delegate
                ScanDirecroriesDelegate scanDelegate = (ScanDirecroriesDelegate)Marshal.GetDelegateForFunctionPointer(ptr, typeof(ScanDirecroriesDelegate));

                // Create a Delegate
                CompareCallBackDelegate callbackDelegate = CompareDirectoriesCallBack;

                // Get Function pointer from Delegate
                IntPtr callback = Marshal.GetFunctionPointerForDelegate(callbackDelegate);

                Console.WriteLine("Invoking scandir via deligate...");
                // Call scandir Func Pass Function point to native side as call back
                scanDelegate.Invoke(".", ref namelist, IntPtr.Zero, callback);
            }
        }

        public static int CompareDirectoriesCallBack(IntPtr value1, IntPtr value2)
        {
            Console.WriteLine("in CompareDirectoriesCallBack...");
            return 0;
        }
    }
}

**Comment by kangaroo** [comment]
I'll take this, should be easy enough.

**Comment by sergiy-k** [comment]
@kangaroo Thank you!

**Comment by kangaroo** [comment]
```
basalt:debug plasma$ lldb ./corerun -c . gfpfd.exe 
(lldb) target create "./corerun" --core "."
error: Unable to find process plug-in for core file '/Users/plasma/Work/dotnet/ports/osx/binaries/Product/amd64/debug'
(lldb) settings set -- target.run-args  "gfpfd.exe"
(lldb) r
Process 69508 launched: './corerun' (x86_64)
TestGetDelegateForFunctionPointer
Current process id: 69508
TestGetFunctionPointerForDelegate
Invoking scandir via deligate...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
in CompareDirectoriesCallBack...
Process 69508 exited with status = 0 (0x00000000) 
```

**Comment by jkotas** [comment]
#337
