### ISSUE TITLE
[Linux][Struct passing] Make structDesc field of GenTreeCall to a pointer and should be initialized with invalid values in gtNewCallNode()

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#3246]
Two issues that i happened to notice during a code review:

1) structDesc field of GenTreeCall node is getting initialized with valid values immediately after return from gtNewCallNode().  As a result, if in some code path JIT fails to initialize structDesc by calling eeGetSystemVAmd64PassStructInRegisterDescriptor(typeHnd, &call->strctDesc) then it will still look like a valid structDesc.  This will lead to SBCG.  Instead we should initialize it with invalid values when gtNewCallNode() returns so that any code paths that don't initialize it will be exposed.

2) structDesc field is of type SYSTEMV_AMD64_CORINFO_STRUCT_REG_PASSING_DESCRIPTOR which is a big struct and will bloat the size of GenTreeCall nodes unnecessarily even if the call is not returning TYP_STRUCT value.  The suggestion is to replace it with a ptr and initialize it to nullptr if the call return type is not a struct. This would mean that structDesc will be dynamically allocated at the point of initializing it.

**Comment by LLITCHEV** [comment]
As we discussed:
1. The struct has a constructor which initializes the eightByteCount to 0. The elements of the eightByteClassifications field are initialized to SystemVClassificationTypeUnknown. There are multiple places in the code where assertions validate the state of the struct instance and makes sure the struct is initialized.
2. I just double checked to make sure. The size of the struct is exactly 8 bytes (it was designed that way). Making it a pointer will not result in any size saving, but will introduce an unnecessary layer of indirection for accessing the struct elements.

As we discussed this issue should be closed and I am doing so.
