### ISSUE TITLE
Can't run crossgen without mscorlib being in the same folder

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#3249]
Crossgen exists in the runtime package in the tools folder but you can't run it directly from the package since mscorlib isn't side by side.

/cc @gkhanna79 @JohnChen0

**Comment by gkhanna79** [comment]
@davidfowl What is the command line you used? Specifying the /Platform_Assemblies_Path to the location of coreclr.dll/mscorlib.ni.dll should work for compiling an assembly. @JohnChen0 can add more context.

**Comment by JohnChen0** [comment]
I have confirmed that by adding the location of mscorlib.ni.dll to /Platform_Assemblies_Path, crossgen can work successfully. There is no need to add location of coreclr.dll. For example:

    C:\dotnet\tools\crossgen.exe /platform_assemblies_paths "C:\dotnet\runtimes\win7-x64\lib\dotnet;..." myAssembly.dll

@davidfowl Please provide more details if this doesn't work for you.

**Comment by gkhanna79** [comment]
@davidfowl Please reopen if you think there are product issues.
