### ISSUE TITLE
GC Tests : Red Black Tree does not correctly implement a red black tree

### ISSUE THREAD

**Issue by mjp41** [dotnet/coreclr#3251]
The red black tree in the GC Stress tests does not correctly implement a red/black tree.  There are at least two bugs:

1) The parent point is not updated in this rotation case: [https://github.com/dotnet/coreclr/blob/master/tests/src/GC/Stress/Tests/RedBlackTree.cs#L239-L268](https://github.com/dotnet/coreclr/blob/master/tests/src/GC/Stress/Tests/RedBlackTree.cs#L239-L268)

2) One of the rotation cases, doesn't perform rotation, and thus breaks the red node with red child invariant. 
[https://github.com/dotnet/coreclr/blob/master/tests/src/GC/Stress/Tests/RedBlackTree.cs#L274-L289](https://github.com/dotnet/coreclr/blob/master/tests/src/GC/Stress/Tests/RedBlackTree.cs#L274-L289)

The second leads to the tree not being balanced, which probably does not mater for the GC benchmarking, but the first leads to objects being live longer than they should be.

**Comment by swgillespie** [comment]
Fixed by #3252
