### ISSUE TITLE
Infinite loop in dynamic dispatch code when calling through contravariant delegate

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#3258]
When upgrading from CoreCLR 23803 to 3818 we are now seeing an infinite loop in the dynamic dispatch code. I have not been able to come up with a minimal repro that I can attach to this bug, but I have a trivial one that I can email anyone who wants it. In the bug we are calling into a delegate of type Action<... my-class>, and the target of the delegate uses an interface for the last argument. If I change the delegate to also use an interface, the issue goes away.

The infinite loop is in code labeled as 'Lightweight Function' by the managed debugger:

`System.Dynamic.Runtime.dll!System.Runtime.CompilerServices.CallSiteBinder.BindCore<System.Action<System.Runtime.CompilerServices.CallSite, System.Action<string, object, OpenDebug.DispatchResponder>, string, object, OpenDebug.DispatchResponder>>(System.Runtime.CompilerServices.CallSite<System.Action<System.Runtime.CompilerServices.CallSite, System.Action<string, object, OpenDebug.DispatchResponder>, string, object, OpenDebug.DispatchResponder>> site, object[] args) Line 133` <-- This function is called infinately
 `[Lightweight Function]` **<-- Hang here**
`OpenDebugAD7.dll!OpenDebug.DispatcherProtocol.Dispatch(string req)` <-- My code calling delegate.Invoke

Looking at the stack in Windbg, I think Windbg gives the method this name:
`26 00000027`ac5fec80 0000019d`bcc88cc8 DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Action'3<System.String,System.Object,OpenDebug.DispatchResponder>, System.String, System.Object, OpenDebug.DispatchResponder)+0x2c2`

**Comment by jkotas** [comment]
Looks dup / related to https://github.com/dotnet/corefx/issues/5610. @gregg-miskelly Could you please  to copy over System.Linq.Expressions.dll from the working build and check whether the problem goes away? (I would allow us to confirm that it is a bug in System.Linq.Expressions.dll.)

**Comment by CarolEidt** [comment]
@jkotas where does one find the "working build"?

**Comment by CarolEidt** [comment]
This does look like a dup of dotnet/corefx#5610. The JIT is repeatedly being invoked on `DynamicClass::CallSite.Target`

**Comment by gregg-miskelly** [comment]
Thanks Jan, yes using an older System.Linq.Expression resolves the problem. Is there a newer version of System.Linq.Expressions that would have this issue fixed? Or is this issue still active?

Here is the version I have:
4.06.23818.0	2/17/2016 8:02 PM

**Comment by jkotas** [comment]
@gregg-miskelly Could you please reopen this issue in corefx repo? It is where System.Linq.Expression.dll lives.

cc @VSadov

**Comment by VSadov** [comment]
CallSite.Target is the redirection point in the callsites self-modification strategy. 
All dynamic calls will end up invoking the Target. If Target cannot handle passed in arguments, it will ask binder to create a new Target that can, then it will self-modify and invoke the Target again.

 It is ok to see Target called multiple times, but infinite loop is obviously bad. It means that binder produces code specialized to given arguments that keeps rejecting those same arguments.

It could be that you do not have a fix for  dotnet/corefx#5610 or (worse) that the fix was not sufficient in your case.

Could you send me a more detailed repro?

**Comment by gregg-miskelly** [comment]
I opened dotnet/corefx/issues/6258 to track this.
