### ISSUE TITLE
Instructions Needed: How do I get mscorlib to build on Ubuntu 15.10 for x64?

### ISSUE THREAD

**Issue by borgdylan** [dotnet/coreclr#3271]
I have managed to build the CLR itself but could not build mscorlib itself. I have tried to use mscorlib from a Ci build package but stuff fails even if I copy over my copy of the CLR. I get `Failed to initialize CoreCLR, HRESULT: 0x80004005` which is quite a generic error.

**Comment by ellismg** [comment]
There shouldn't be anything specific to Ubuntu 15.10 for mscorlib.  The native bits will have specific references by any mscorlib complied for "linux" should be fine.

Can you please point to the exact mscorlib you are picking up, the exact commit hash for CoreCLR you're building from and what if anything else you're doing?

Note that mscorlib and then rest of the runtime are tightly coupled so a release mscorlib will not work with a debug runtime (and vice versa).

**Comment by borgdylan** [comment]
Mscorlib was not building at all so I picked one from the .net cli. I thought I'd be able to get it built but msbuild for coreclr is missing in the coreclr repo.

**Comment by borgdylan** [comment]
Also, the CI is not building mscorlib at all under 15.10. Compare the artifacts with 14.04.

**Comment by borgdylan** [comment]
I managed to get the build to move further by installing the libicu52 package from a prior ubuntu version. I hope that the built output ill link against libicu55.

**Comment by borgdylan** [comment]
The build fails with:
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Build.CommandLine.MSBuildApp' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'Dup' in DLL 'System.Native'.
   at Interop.Sys.Dup(Int32 oldfd)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(Func`1 fdFunc)
   at System.ConsolePal.OpenStandardOutput()
   at System.Console.<>c.<get_Out>b__13_0()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.WriteLine(String value)
   at Microsoft.Build.CommandLine.MSBuildApp.HandleConfigurationException(Exception ex)
   at Microsoft.Build.CommandLine.MSBuildApp..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
```

**Comment by ellismg** [comment]
FWIW, This isn't supported today, so there isn't a super clear path forward.  My recommendation is just to pick mscorlib.dll from a Ubuntu 14.04 build in CI.  `mscorlib.dll` itself doesn't have any distro specific dependencies.

**Comment by ellismg** [comment]
@borgdylan The issue are hitting there is a known issue that can happen due to bugs in `dotnet restore` picking the wrong set of packages to restore due to race conditions.  We plan to update the version of dotnet restore we use in the next couple of days to pick up a fix for the issue.

In the mean time, you can try forcing a re-download of the tools (doing this from the root of the repository)

```
rm -rf Tools   # remove the tools folder
rm -rf ~/.local/share/dnu ~/.local/share/NuGet  # clean out any existing nuget/dnu caches
./init-tool.sh  # try to initialize the tools again
./Tools/corerun ./Tools/MSBuild.exe  # see if it worked
```

And see if you get lucky.  The other option is to just hold off building mscorlib on Linux until we update the dotnet version.  @dagood is working on this, there's a few things he needs to shake out.

**Comment by borgdylan** [comment]
@ellismg It worked OK. I cannot build corefx however. Would I be able to use this fresh coreclr that uses icu v. 55 with corefx packages obtained from myget? I'd like to test a library of mine that I've been cross compiling against the reference assemblies.

**Comment by jeffschwMSFT** [comment]
Closing this issue, as this should now be working as expected
