### ISSUE TITLE
Add Debian and RH 7.2 to CI

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3276]
@mmitche We are tracking their status on the main repo page, so should also ensure that they are getting validated in CI as well.

CC @ellismg @weshaggard @joshfree

**Comment by ellismg** [comment]
We make a specific decision here to not run them per PR when we added them.  I don't believe it's worthwhile to add every single distro to every single PR.  If you are doing something that you worry about getting individual coverage on, we have triggers you can use to request runs against a PR, but I'd rather us not burn a bunch of machine time for little gain.

**Comment by mmitche** [comment]
@ellismg Agreed.  We don't need to validate every OS on every PR.
