### ISSUE TITLE
Archive CoreCLR builds

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#328]

**Comment by mmitche** [comment]
This is being done now.

**Comment by linquize** [comment]
where to find?

**Comment by mmitche** [comment]
You can find them on the artifacts page for the various builds:
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_linux_debug/lastSuccessfulBuild/artifact/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_linux_release/lastSuccessfulBuild/artifact/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_windows_release/lastSuccessfulBuild/artifact/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_windows_debug/lastSuccessfulBuild/artifact/
