### ISSUE TITLE
Redundant calls to static helpers in R2R images

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#3281]
```
static int s;

static void Main() {
   s++;
   s++;
}
```

```
csc /o+ test.cs
crossgen test.exe
```

Result: The method has 4 calls to static helper. Instead, it should have just one.

```
sub     esp,20h
call    qword ptr [test_ni+0x1020 (00007ffd`c20d1020)]
mov     rsi,rax
call    qword ptr [test_ni+0x1020 (00007ffd`c20d1020)]
mov     eax,dword ptr [rax+34h]
inc     eax
mov     dword ptr [rsi+34h],eax
call    qword ptr [test_ni+0x1020 (00007ffd`c20d1020)]
mov     rsi,rax
call    qword ptr [test_ni+0x1020 (00007ffd`c20d1020)]
mov     eax,dword ptr [rax+34h]
inc     eax
```

**Comment by jkotas** [comment]
Looks like a missing case in value numbering.

**Comment by briansull** [comment]
I can take a look.
What is different about R2R IL that causes this?

**Comment by jkotas** [comment]
It has a new helper ID: `CORINFO_HELP_READYTORUN_STATIC_BASE`

The helper does not argument. Instead, this helper is called via indirection. `gtCall.gtEntryPoint.addr` The indirection address should be used as the key to compute the value number instead of the argument.

Thanks for taking a look at this, Brian!

**Comment by briansull** [comment]
If the args are not represent in the IR then we will have to special case this call in fgValueNumberHelperCallFunc.

Additionally I don't believe that we have yet asked for the indirect call target at this point in the JIT.
So we might have to ask for this value twice or find a way to cache it until we need it again during codegen.

**Comment by briansull** [comment]
Eugene will take a look at this
