### ISSUE TITLE
Investigate which signals really need to be blocked on Unix

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#3305]
In PAL, we currently block signals of many types. We have already hit two issues where this has caused a trouble and the signals needed to be enabled. 
So we should investigate which (if any) signals need to be blocked and enable all that doesn't have to.

**Comment by janvorli** [comment]
Here is a list of signals that we block with the default action and description:

Signal | Default action | Description
--------|--------|--------
SIGHUP | Terminate | Hangup
SIGABRT | Terminate (core dump) | Process abort signal
SIGEMT | Terminate (core dump) | Emulator trap
SIGSYS | Terminate (core dump) | Bad system call
SIGALRM | Terminate | Alarm clock
SIGURG | Ignore | High bandwidth data is available at a socket
SIGTTIN | Stop | Background process attempting read
SIGTTOU | Stop | Background process attempting write
SIGIO | Ignore | A file descriptor is ready to perform input or output
SIGXCPU | Terminate (core dump) | CPU time limit exceeded
SIGXFSZ | Terminate (core dump) | File size limit exceeded
SIGVTALRM | Terminate | Virtual timer expired
SIGWINCH | Ignore | Window size changed
SIGINFO | Ignore | A status (info) request is received from the controlling terminal
SIGPIPE  | Terminate | Write on pipe with no-one to read it
SIGUSR1 | Terminate | User defined signal 1
SIGUSR2 | Terminate | User defined signal 2

**Comment by janvorli** [comment]
From the list, it looks like there is no reason for blocking any of these signals and we should let them be handled by their default handler.

**Comment by janvorli** [comment]
Fixed by #4863

**Comment by davidfowl** [comment]
@janvorli is this in a doc? We should doc this. 

/cc @richlander @terrajobst

**Comment by janvorli** [comment]
@davidfowl I am sorry for the late reply, I've missed your comment before. I am not sure what would you like to have in a doc - the fact that we don't block any signals?

**Comment by Ozonni** [comment]
Is it possible to override the default behavior e.g. SIGUSR1 doesn't terminate the process?

**Comment by janvorli** [comment]
@Ozonni I think you could be able to do that using a small native shared library that would mask the signal. In your managed code, you would use interop to call a function in this library that would mask the signal.
