### ISSUE TITLE
./build.sh on Ubuntu 15.10 fails

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#3318]
I am trying to build the coreclr repository on ubuntu wily.

At some point the build script downloads https://dotnetcli.blob.core.windows.net/dotnet/dev/Binaries/1.0.0.000973/dotnet-ubuntu-x64.1.0.0.000973.tar.gz

Then it tries to execute:
dotnet restore /home/tmds/repos/coreclr/Tools/1.0.25-prerelease-00171/project.json --packages /home/tmds/repos/coreclr/packages --source https://www.myget.org/F/dotnet-buildtools/

This step fails, stracing it shows the executable is looking for "System.Globalization.Native". It does this at a bunch of locations starting at "/home/tmds/repos/coreclr/Tools/dotnetcli/bin/System.Globalization.Native".

The tar file downloaded earlier does contain a ./Tools/dotnetcli/bin/System.Globalization.Native.so, so I guess the lack of the ".so" suffix causes the tool to not find the library and fail.

**Comment by sergiy-k** [comment]
I think this is due to https://github.com/dotnet/coreclr/issues/2834.
You need to install libicu 5.2 that is required by System.Globalization.Native. Could please try this and check whether it will fix the issue that you are seeing? Thank you.

**Comment by tmds** [comment]
I am no longer actively looking at this. I will close the issue since I won't be able to provide the necessary input.
