### ISSUE TITLE
Do not add FX assemblies to TPA when running tests

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#3321]
When tests are run all fx assemblies & other dependencies are copied to core_root making them trusted assemblies. All dependencies should be copied to test/application directory and only runtime (coreclr & mscorlib) should be present in core_root.

**Comment by gkhanna79** [comment]
@rahku Does this break anything?

**Comment by AndyAyersMS** [comment]
@rahku CoreCLR builds ~5900 test executables, seems like taking your suggestion literally would create a lot of file copies.

**Comment by rahku** [comment]
@AndyAyersMS No if you create hardlinks instead of copies.

**Comment by rahku** [comment]
@gkhanna79 No it does not break anything but it does not catch bugs when these assemblies are not TPA.

**Comment by rahku** [comment]
closing as it seems we no longer have the concept of non-tpa for netcore. Everything is TPA now.
