### ISSUE TITLE
Hardcode CP_ACP to UTF8 on Linux

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#333]
CP_ACP is hardcoded to UTF8 in the PAL on Mac. It provides UTF8 marshalling via CharSet.Ansi as side-effect. From locale\unicode.cpp:

// We hardcode the system's default codepage to be UTF-8.
// There are several reasons for this:
// - HFS+ file names are encoded as UTF-8.
// - When writing strings to the console, the Terminal.app will interpret them as UTF-8.
static const UINT PAL_ACP = 65001;

We should hardcode it to UTF8 on Linux too (ie remove the HAVE_COREFOUNDATION ifdef). It will make us consistent between Mac and Linux, makes the PInvoke marshalling work, and gets rid of a pile of globalization code from CoreCLR PAL.

**Comment by benpye** [comment]
This is a bit further than the scope of .NET Core, and maybe should be aimed at CoreFX or some other place. Would their be any consideration for providing UTF-8 marshalling on Windows also as despite Windows itself not using UTF-8, many third party libraries still do.

**Comment by jkotas** [comment]
@benpye Our strategy is to switch away from runtime magic for the interop marshaling. You can get the idea from [.NET Native and MCG](http://blogs.msdn.com/b/dotnet/archive/2014/06/13/net-native-deep-dive-debugging-into-interop-code.aspx) blog post written by @yizhang82. Once we get there, it will be become much easier to support new kinds of marshalling, like UTF8 marshalling that you are asking for.

For now, it is necessary to write or autogenerate a bit of extra code to marshal strings as UTF8. For example, check http://stackoverflow.com/questions/17438339/c-marshall-strings-to-utf8-char.
