### ISSUE TITLE
Potential bug in handling Funclets in compMethodReturnsRetBufAddr() method in compiler.h

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#3330]
It is not clear whether the type of a funclet is changed when calling this function from flowgraph.h.
This issue exists on Windows and Linux when isProfilerHook enabled.
It is potentially possible to change the type of the funclet based on the value of the main method's compRetBufArg.
This issue was introduced by a recent refactoring related to fixes in oneReturn code in flowgraph.
It is possible that there are no problems, but it is not clear to me.
Please, refer to comments in PR #3319 (https://github.com/dotnet/coreclr/pull/3319/files#r53845164)
I am putting this PR on hold while this bug is fixed.
Currently on Linux the codegenxarch.cpp is not changing the return type based on the existence of implicit RetBuf. It simply puts the address of the RetBuf in RAX when the return statement is generated.

**Comment by sivarv** [comment]
There is no bug in compMethodReturnsRetBufAddr() nor in compMethodHasRetVal() when called from flowgraph.cpp::fgAddInternal() and morph.cpp::fgMorphBlocks() for the reason that latter call comp*() methods only in the context of a block whose jumpkind is BBJ_RETURN.  In case of funclet methods, none of its basic blocks will have jumpkind BBJ_RETURN instead it will end with one of BBJ_EHFINALLYRET/BBJEHFILTERRET/BBJEHCATCHRET.
