### ISSUE TITLE
ARM64: Implement table switch based codegen

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3332]
Sample test case:

timespanadd.exe_2389

"Need GT_SWITCH_TABLE expansion for ARM64"' in 'System.Globalization.CalendarData:InitializeEraNames(ref,int):this' (IL size 476)

**Comment by cmckinsey** [comment]
Is this for perf only? We should give it the optimization label if that's the case so we can treat this as lower priority than regular bring-up functionality.

**Comment by briansull** [comment]
Yes, It is an optimization issue and we currently generate a potentially very long sequence of cmp and beq instructions.
