### ISSUE TITLE
[RyuJIt][SIMD] RyuJit assumes that Vector3 type args passed in registers or on stack is rounded to 16-bytes with upper 4-bytes being zero

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#3347]
RyuJIt back-end makes two assumptions about Vector3 types

Assumption1: Vector3 type args passed in registers or on stack is rounded to POINTER_SIZE and hence on 64-bit targets it can be read/written as if it were TYP_SIMD16.

Assumption2: Vector3 args passed in registers (e.g. unix) or on stack have their upper 4-bytes being zero.  Similarly Vector3 return type value returned from a method will have its upper 4-bytes zeroed out.

The above two assumptions hold for RyuJIT generated code and it not clear whether they will hold for inter-op cases (e.g PInvoke returning Vector3 type value or RPInvoke passing a Vector3 type arg).
This needs investigation.  

#1678 is related to this issue that has implications based on the investigation or decisions made w.r.t this issue.

**Comment by RussKeldorph** [comment]
@sivarv Is @sejongoh's investigation and #4398 sufficient to close this in your opinion?

**Comment by sivarv** [comment]
@sejongoh @RussKeldorph - I had a relook at the test cases more closely and left some comments. 


The most important assumption to validate is  that when Vector3 args are passed by native layer to managed through RPInvoke, native layer is zero initializing upper 4 bytes to zero.  We need to make sure RPInvoke signature is such that we have one vector3 arg passed in registers (x64 unix) and another vector3 arg is passed on stack.

If we have a successful test runs with the suggested modifications, we can close this investigation.

**Comment by sejongoh** [comment]
PRs for testcases:
https://github.com/dotnet/coreclr/pull/4398
https://github.com/dotnet/coreclr/pull/4578

Related issues:
https://github.com/dotnet/coreclr/issues/4607
https://github.com/dotnet/coreclr/issues/4720
https://github.com/dotnet/coreclr/issues/4412
https://github.com/dotnet/coreclr/issues/4529
https://github.com/dotnet/coreclr/issues/4893

Related PRs:
https://github.com/dotnet/coreclr/pull/4690
https://github.com/dotnet/coreclr/pull/4705

**Comment by sejongoh** [comment]
@sivarv I think that we close this since we are done with writing testcases. Could you confirm it?

We have a separate issue for the known bug, https://github.com/dotnet/coreclr/issues/4893.

**Comment by sivarv** [comment]
Issue #4893 on x64 Unix is that upper 4 bytes of a Vector3 arg passed on stack is not guaranteed to be zero initialized by native compiler and hence RPInvoke to managed has failed.

Does native compiler or ABI spec provide a guarantee that upper 4-bytes of a Vector3 arg passed in register will be zero initialized?  Please double check that we are not getting lucky since native compiler is using movss instruction for loading into xmm register.

**Comment by sejongoh** [comment]
I couldn't find such spec. We are probably lucky with movss. I will include this problem into #4893.

**Comment by sivarv** [comment]
Sounds good to me. We can close this investigation work item.
