### ISSUE TITLE
SOS version mismatch message

### ISSUE THREAD

**Issue by bendono** [dotnet/coreclr#3352]
While looking into a dump (CLI #1576), I noticed that the coreclr and sos versions did not match. There is a warning message about it, but it only appears on the second+ sos command issued. It does not occur on the first sos command issued.
![sos](https://cloud.githubusercontent.com/assets/846533/13311054/a6006742-dbce-11e5-94a6-dc6a5b9927e0.png)
While minor, I would expect it to be consistent and output the same message on the first sos command that is issued as well.

**Comment by mikem8361** [comment]
Your screen shot didn't show the "lm" command that shows the coreclr.dll path.  Is it the same path as sos.dll? If so, then there is some problem with the package.  Try installing a later one.

**Comment by bendono** [comment]
Here is the output for lm v m coreclr:

0:000> lm v m coreclr
Browse full module list
start             end                 module name
00007ffe`c3f90000 00007ffe`c4543000   coreclr    (export symbols)       coreclr.dll
    Loaded symbol image file: coreclr.dll
    Image path: C:\Program Files\dotnet\bin\coreclr.dll
    Image name: coreclr.dll
    Browse all global symbols  functions  data
    Timestamp:        Mon Jan 04 15:30:35 2016 (568A118B)
    CheckSum:         005AA01F
    ImageSize:        005B3000
    File version:     4.6.23704.0
    Product version:  4.0.23704.0
    File flags:       8 (Mask 3F) Private
    File OS:          4 Unknown Win32
    File type:        2.0 Dll
    File date:        00000000.00000000
    Translations:     0409.04b0
    CompanyName:      Microsoft Corporation
    ProductName:      Microsoft® .NET Framework
    InternalName:     coreclr.dll
    OriginalFilename: coreclr.dll
    ProductVersion:   4.6.23704.0
    FileVersion:      4.6.23704.0 built by: PROJECTK
    PrivateBuild:     DDBLD655B
    FileDescription:  Microsoft .NET Runtime Common Language Runtime - WorkStation
    LegalCopyright:   © Microsoft Corporation.  All rights reserved.
    Comments:         Flavor=Retail

I manually searched C:\Program Files\dotnet\bin and sos.dll does not exist. Rather, it is located in C:\Program Files\dotnet\bin\dnx, so I loaded it from there.

0:000> .load C:\Program Files\dotnet\bin\dnx\sos.dll

First sos command does not show a version mismatch. Here is !threads.

0:000> !threads
PDB symbol for clr.dll not loaded
ThreadCount:      4
UnstartedThread:  0
BackgroundThread: 3
PendingThread:    0
DeadThread:       0
Hosted Runtime:   no
                                                                                                        Lock  
       ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
   0    1 2964 0000029b33f702d0    2a020 Preemptive  0000029EB46E4FD8:0000029EB46E5FD0 0000029b33f14a40 0     MTA System.ArgumentException 0000029eb46dbe58
  10    2 390c 0000029b342a5640    2b220 Preemptive  0000000000000000:0000000000000000 0000029b33f14a40 0     MTA (Finalizer) 
  11    3 4b34 0000029fbfbefbc0  8029220 Preemptive  0000029B343F1968:0000029B343F1FD0 0000029b33f14a40 0     MTA (Threadpool Completion Port) 
  13    4 5e30 0000029fbfc04da0  8029220 Preemptive  0000000000000000:0000000000000000 0000029b33f14a40 0     MTA (Threadpool Completion Port) 

If I do !threads again, though, it now shows a version mismatch.
Shouldn't it show that there is a version mismatch the first time as well?

0:000> !threads
The version of SOS does not match the version of CLR you are debugging.  Please
load the matching version of SOS for the version of CLR you are debugging.
CLR Version: 4.6.23704.0
SOS Version: 4.6.23516.1
ThreadCount:      4
UnstartedThread:  0
BackgroundThread: 3
PendingThread:    0
DeadThread:       0
Hosted Runtime:   no
                                                                                                        Lock  
       ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
   0    1 2964 0000029b33f702d0    2a020 Preemptive  0000029EB46E4FD8:0000029EB46E5FD0 0000029b33f14a40 0     MTA System.ArgumentException 0000029eb46dbe58
  10    2 390c 0000029b342a5640    2b220 Preemptive  0000000000000000:0000000000000000 0000029b33f14a40 0     MTA (Finalizer) 
  11    3 4b34 0000029fbfbefbc0  8029220 Preemptive  0000029B343F1968:0000029B343F1FD0 0000029b33f14a40 0     MTA (Threadpool Completion Port) 
  13    4 5e30 0000029fbfc04da0  8029220 Preemptive  0000000000000000:0000000000000000 0000029b33f14a40 0     MTA (Threadpool Completion Port) 

Here is the .chain info:

0:000> .chain
Extension DLL search Path:
    C:\Debuggers\Windows 10\x64\WINXP;C:\Debuggers\Windows 10\x64\winext;C:\Debuggers\Windows 10\x64\winext\arcade;C:\Debuggers\Windows 10\x64\pri;C:\Debuggers\Windows 10\x64;C:\Debuggers\Windows 10\x64\winext\arcade;c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.7.0_45\bin;C:\Program Files (x86)\CMake\bin;C:\ProgramData\chocolatey\bin;c:\Program Files\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\110\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;c:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;c:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\nodejs\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\dotnet\bin;C:\Users\Ben\AppData\Local\atom\bin;C:\Users\Ben\AppData\Roaming\npm;C:\Program Files\Git\bin;C:\Program Files (x86)\CMake\bin;C:\Python34
Extension DLL chain:
    C:\Program Files\dotnet\bin\dnx\sos.dll: image 4.6.23516.1, API 1.0.0, built Mon Nov 16 14:08:51 2015
        [path: C:\Program Files\dotnet\bin\dnx\sos.dll]
    dbghelp: image 10.0.10586.15, API 10.0.6, built Fri Nov 20 13:55:01 2015
        [path: C:\Debuggers\Windows 10\x64\dbghelp.dll]
    ext: image 10.0.10586.0, API 1.0.0, built Fri Oct 30 11:11:48 2015
        [path: C:\Debuggers\Windows 10\x64\winext\ext.dll]
    exts: image 10.0.10586.0, API 1.0.0, built Fri Oct 30 11:10:57 2015
        [path: C:\Debuggers\Windows 10\x64\WINXP\exts.dll]
    uext: image 10.0.10586.0, API 1.0.0, built Fri Oct 30 11:10:50 2015
        [path: C:\Debuggers\Windows 10\x64\winext\uext.dll]
    ntsdexts: image 10.0.10586.0, API 1.0.0, built Fri Oct 30 11:40:30 2015
        [path: C:\Debuggers\Windows 10\x64\WINXP\ntsdexts.dll]

> Try installing a later one.

This issue was noticed in the sos supplied in CLI (DNX). While I can manually compile a newer version of CoreClr and SOS, I do not think that DNX supplies a later version yet.
That is why in CLI #1576 (https://github.com/dotnet/cli/issues/1576), I asked "For CoreCLR, is there any reason that SOS.dll cannot be located in the same folder as CORECLR.dll is in?"

I can retry when there is a new CLI package.

**Comment by mikem8361** [comment]
This is the problem which I think you already realize.  The dnx subdirectory is old and doesn’t exist on new (which I just tried) installations (you should probably delete it at some point).  And your ask of why can’t sos.dll be located in the same directory as coreclr.dll should has been addressed by @gkhanna79.

Comments: Flavor=Retail

I manually searched C:\Program Files\dotnet\bin and sos.dll does not exist. Rather, it is located in C:\Program Files\dotnet\bin\dnx, so I loaded it from there.

0:000> .load C:\Program Files\dotnet\bin\dnx\sos.dll

First sos command does not show a version mismatch. Here is !threads.

**Comment by bendono** [comment]
I have uninstalled previous CLI installer as well as removed the entire Program Files\dotnet folder.
I then re-installed the latest CLI installer.
Indeed, there is no dnx subdirectory anymore.

CoreClr module details:

0:000> lm v m coreclr
Browse full module list
start             end                 module name
00007ffe`bea40000 00007ffe`beff3000   coreclr    (deferred)             
    Image path: C:\Users\Ben\.nuget\packages\runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR\1.0.1-rc2-23811\runtimes\win7-x64\native\coreclr.dll
    Image name: coreclr.dll
    Browse all global symbols  functions  data
    Timestamp:        Thu Feb 11 15:17:51 2016 (56BC278F)
    CheckSum:         005A45CF
    ImageSize:        005B3000
    File version:     4.6.23811.0
    Product version:  4.0.23811.0
    File flags:       8 (Mask 3F) Private
    File OS:          4 Unknown Win32
    File type:        2.0 Dll
    File date:        00000000.00000000
    Translations:     0409.04b0
    CompanyName:      Microsoft Corporation
    ProductName:      Microsoft® .NET Framework
    InternalName:     coreclr.dll
    OriginalFilename: coreclr.dll
    ProductVersion:   4.6.23811.0
    FileVersion:      4.6.23811.0 built by: PROJECTKREL
    PrivateBuild:     DDBLD705C
    FileDescription:  Microsoft .NET Runtime Common Language Runtime - WorkStation
    LegalCopyright:   © Microsoft Corporation.  All rights reserved.
    Comments:         Flavor=Retail

Searching for SOS, it now appears to be available in a tools subdirectory.
Ideally I would prefer it to in the same folder as coreclr.dll, but at least the correct version is available.

Loading it...
.load C:\Users\Ben\.nuget\packages\runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR\1.0.1-rc2-23811\tools\sos.dll

.chain shows:
(partial extract)
    C:\Users\Ben\.nuget\packages\runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR\1.0.1-rc2-23811\tools\sos.dll: image 4.6.23811.0, API 1.0.0, built Thu Feb 11 15:23:00 2016
        [path: C:\Users\Ben\.nuget\packages\runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR\1.0.1-rc2-23811\tools\sos.dll]

There are no more version mismatches.
Unless someone disagrees, I think that this can closed now.
Thank you.

**Comment by mikem8361** [comment]
@gkhanna79 can answer this more definitively but I think in a future dotnet clr version sos.dll will be in the same directory as coreclr.dll. I could be wrong though.

**Comment by gkhanna79** [comment]
You are correct. Sos would be next to coreclr soon. The difference is because the current published packages come from closed build and not open build.
