### ISSUE TITLE
 System.Runtime.InteropServices.RuntimeInformation.Tests fails

### ISSUE THREAD

**Issue by hoyMS** [dotnet/coreclr#3367]
**Configuration**
    Checked CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
     CoreFX assemblies and CoreFX tests: release

**This only happened with Linux-build corefx. Building corefx on windows and copying binaries to Linux didn't repro.**

./build.sh /p:ConfigurationGroup=Release /p:BUILDTOOLS_OVERRIDE_RUNTIME=~/git/coreclr/bin/Pro
duct/Linux.x64.Checked

     System.Runtime.InteropServices.RuntimeInformationTests.CheckArchitectureTests.VerifyArchitecture [FAIL]
        System.EntryPointNotFoundException : Unable to find an entry point named 'SystemNative_GetOSArchitecture' in DLL 'System.Native'.
        Stack Trace:
              at Interop.Sys.GetOSArchitecture()
              at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture()
              at System.Runtime.InteropServices.RuntimeInformationTests.CheckArchitectureTests.VerifyArchitecture()

**Comment by hoyMS** [comment]
Looks like we are missing api-ms-win-core-sysinfo-l1-2-0.dll as a native library on Linux.

**Comment by RussKeldorph** [comment]
I can't repro this anymore.
