### ISSUE TITLE
Poor code quality of `List<T>`

### ISSUE THREAD

**Issue by NightElfik** [dotnet/coreclr#3373]
Hi coreclr hackers,

Recently I have been digging around implementation of `List<T>` in mscorlib and I was quite surprised of poor quality of code formatting.

I have found dozens of typos in comments that are not even XMLdoc (are they supposed to be?), inconsistencies in coding style (somewhere there are braces, somewhere there are not, sometimes there is new lie, sometimes not, etc.) and even misleading comments (default ctor promises that after adding an element to the empty list the size will be 16 but constant is defined as 4).

I was wondering if fixing those formatting issues would be welcome here or if I should not bother.

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/List.cs

Cheers,
Marek

**Comment by mjsabby** [comment]
Absolutely, the community welcomes it.

https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md#typos

**Comment by NightElfik** [comment]
@mjsabby Thanks for the answer and for the link! I am wondering what about comments style (XMLdoc vs. plain) and maximum preferred line lengths (for code and for comments)? Those are not mentioned in the linked style guide.

**Comment by jkotas** [comment]
The contributing doc above says `DO NOT send PRs for style changes.` that the reformatting falls under.

Also, we expect to eventually switch over to implementations of List.cs, etc. from corefx repo, e.g. https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/List.cs, and stop using the ones here. You will notice that copies in the corefx repo has received a lot more attention on making the code look pretty.

**Comment by NightElfik** [comment]
@jkotas I see, thanks for the explanation. In that case I am closing this issue.
