### ISSUE TITLE
Bring Longfile path fixes to mscorlib

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3384]

**Comment by gkhanna79** [comment]
CC @JohnChen0 @ramarag

**Comment by gkhanna79** [comment]
CC @weshaggard

**Comment by sergiy-k** [comment]
cc @weshaggard, Are you on track with work item for RC2?

**Comment by weshaggard** [comment]
This isn't going to happen in the RC2 time frame we will track it for RTM.

**Comment by JeremyKuhne** [comment]
Critical code has made it back through.
