### ISSUE TITLE
Audit GC tests that consume lots of resources and/or take a long time

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#3392]
There are number of GC tests that are very useful for bug-finding, but either take a very long time to run (>10 minutes) or consume a lot of memory. We need to figure out when we want to run these and ensure that our infrastructure can handle the resource consumption that these tests perform. We will also want to examine these tests with ETW to ensure that they are testing what they claim to test and if they are useful.

There are a number of these tests that are excluded in `issues.targets` and marked with this issue that I identified as following into this category of tests.

**Comment by swgillespie** [comment]
Done as part of #3622.

**Comment by BruceForstall** [comment]
@swgillespie There are many tests in tests\issues.targets that still reference this issue number, but this issue is marked as Closed. Is that correct? Or, can the tests be removed from the issues.targets exclusion list?

**Comment by swgillespie** [comment]
@BruceForstall I think these tests can be removed completely, when I analyzed them they behaved poorly and didn't provide any additional coverage over what we already have. I'll take a minute to remove them. The ones that were good and provided unique test coverage got moved to the long GC test job.

**Comment by swgillespie** [comment]
@BruceForstall (and @sergiy-k) Following up on this. The tests on this list allocate an unreasonable amount of memory, some of them even allocating repeatedly until the whole machine runs out of memory and we raise an OOM exception. While OOM testing is important (and it's done already as part of the long GC test run, but more reasonably), the rates in which these tests allocate begin to perturb other tests running on the same machine, to the point that random tests in other jobs fail and the only way to find the root cause is to correlate jobs that ran on the same machine.

Furthermore, we still have problems in the GC when in extreme low memory situations, such as https://github.com/dotnet/coreclr/issues/5906#issuecomment-227613661 , so these tests are naturally flaky. 

We can use job objects on Windows to lower the maximum working set to a more reasonable amount, but there's no direct equivalent on Linux or OSX. Linux has `cgroups`, which will allow us to limit the maximum working set, but it does not guarantee that the OOM killer will not kill the process anyway if it reaches its limit. Also, even if you turn off the OOM killer for a cgroup, Linux will never schedule the OOM process and it will hang indefinitely. As far as I know the Darwin kernel doesn't offer any resource management at all.

At any rate, these tests are useful to have because they can be run manually when making changes to the GC that can have effects in OOM scenarios, but they probably aren't appropriate to run on our current test infrastructure.

**Comment by BruceForstall** [comment]
Makes sense.
