### ISSUE TITLE
Package binding of JIT tests needs to avoid conflict

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#3396]
This issue is a result of PR #3383 . The problem there was some of the jit/config/*/project.json specified one version of System.IO.FileSystem, and one project.json specified another. There was some issue where the version dropped in the binaries used for testing was wrong for some tests.

@pgavlin suggests we need an issue to discuss/track pinning of all tests' project.json files to avoid future conflicts.

**Comment by AndyAyersMS** [comment]
There are no more project.json files, so suggest we close this.
