### ISSUE TITLE
Make SingleProducerSingleConsumerQueue<T> public

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#3413]
In this "After Midori" age such high performance low level building blocks should be available for us too  :)

It is already used in at least three places: [TPL Dataflow](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Dataflow/src/Internal/ProducerConsumerQueues.cs#L101), [CoreFx Lab's Channels](https://github.com/dotnet/corefxlab/blob/master/src/System.Threading.Tasks.Channels/System/Collections/Concurrent/SingleProducerConsumerQueue.cs#L17) and [ConcurrentExclusiveSchedulerPair](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Tasks/ProducerConsumerQueues.cs#L95) and been in .NET internally since, if not mistaken, v4.0.

@stephentoub @KrzysztofCwalina

**Comment by omariom** [comment]
And I promise to contribute my time to make it even more faster :)

**Comment by stephentoub** [comment]
I can make it public in the channels library.

**Comment by omariom** [comment]
Great!
