### ISSUE TITLE
Disagreement between JIT coding conventions and real world

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#3414]
The JIT coding conventions say that function names should be Pascal cased but in all recent commits (inlining, allocator) camel case names have been used. Personally I prefer Pascal case but I'm fine with either convention as long as it used consistently.

@BruceForstall @AndyAyersMS @pgavlin

**Comment by AndyAyersMS** [comment]
I hear you. I'm probably the worst at introducing inconsistencies.

We'd like to move the jit code base to a tool-enforceable (and for many things, tool-fixable) formatting and naming policy. Hopefully soon. Here's a [clang-format prototype](https://github.com/AndyAyersMS/coreclr/tree/RyuJitClangFormat) to handle the formatting side. Maybe clang-tidy can do the naming aspects.

When we do this, we can clean everything up in one or two big waves.

**Comment by BruceForstall** [comment]
I'm sure you've also noticed that there is a lot of inconsistency in the code base. The JIT coding conventions were written long after much of the JIT itself was written. It tried to be aspirational in specifying the direction where we want to code to go, but not be too dictatorial for things we deemed "didn't matter", or at least weren't worth fighting about. If we can get to a tool-enforced solution, perhaps that will work.

I'm guessing one of the reasons for recent "transgressions" is that we have a lot of new people working on the JIT, who probably aren't used to the new conventions they are now working with.

**Comment by mikedn** [comment]
> I'm sure you've also noticed that there is a lot of inconsistency in the code base.

Yes but I'm only talking about new code. There were a few style comments in recent PRs but nobody from the JIT team noticed this discrepancy so I thought that maybe coding conventions are actually incorrect and perhaps need updating. That said, I didn't notice this myself. Due to lower case prefixes that are everywhere (`fg`, `gt`...) it's easy to think that camel case is the convention.

I don't expect code to be updated now so I'll close this, it was only meant to draw attention to the team to something that was missed during PR reviews.
