### ISSUE TITLE
[NetBSD] Consistency check failed: Managed object size does not match unmanaged object size

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#3416]
```
Running tests in /tmp/bin/tests/FreeBSD.AnyCPU.Debug//Common.Tests/dnxcore50
./corerun xunit.console.netcore.exe Common.Tests.dll -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=nonlinuxtests -notrait Benchmark=true


Assert failure(PID 29691 [0x000073fb], Thread: -134260736 [0xf7ff5800]): Consistency check failed: Managed object size does not match unmanaged object size
man: 0x18, unman: 0x20, Name: System.Runtime.InteropServices.CriticalHandle
FAILED: size == expectedsize
    File: /tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/vm/binder.cpp Line: 538
    Image: /tmp/bin/tests/FreeBSD.AnyCPU.Debug/Common.Tests/dnxcore50/corerun


Assert failure(PID 29691 [0x000073fb], Thread: -134260736 [0xf7ff5800]): Consistency check failed: Managed object size does not match unmanaged object size
man: 0x18, unman: 0x20, Name: System.Runtime.InteropServices.CriticalHandle
FAILED: size == expectedsize
    File: /tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/vm/binder.cpp Line: 538
    Image: /tmp/bin/tests/FreeBSD.AnyCPU.Debug/Common.Tests/dnxcore50/corerun

Assert Failure (PID 29691, Thread -134260736/0xf7ff5800)Consistency check failed: Managed object size does not match unmanaged object size
man: 0x18, unman: 0x20, Name: System.Runtime.InteropServices.CriticalHandle
FAILED: size == expectedsize

/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/vm/binder.cpp, Line: 538

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
/tmp/bin/tests/FreeBSD.AnyCPU.Debug/Common.Tests/dnxcore50/corerun
**** MessageBox invoked, title 'corerun - Assert Failure (PID 29691, Thread -134260736/0xf7ff5800)' ****
  Consistency check failed: Managed object size does not match unmanaged object size
man: 0x18, unman: 0x20, Name: System.Runtime.InteropServices.CriticalHandle
FAILED: size == expectedsize

/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/vm/binder.cpp, Line: 538

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
/tmp/bin/tests/FreeBSD.AnyCPU.Debug/Common.Tests/dnxcore50/corerun
```

I was suggested to run FreeBSD assemblies. I don't know if that matters.

**Comment by krytarowski** [comment]
Discussion: https://github.com/dotnet/buildtools/pull/477

**Comment by krytarowski** [comment]
Is that because of not using netbsdmscorlib (freebsdmscorlib)?

**Comment by ellismg** [comment]
You are using a release mscorlib and a debug CoreCLR or vise versa.  Likely the first case as the assert would not be printed in release mode, IIRC.

**Comment by krytarowski** [comment]
I was using default build options in both projects... I was worried that this is due to target OS-mismatch.

I will try again. Thanks!

**Comment by krytarowski** [comment]
I'm still getting the same result. I was trying combinations of Debug + Debug, Release + Release, NetBSD and FreeBSD target for CoreFX. Can it be something else?

I'm trying to investigate

**Comment by ellismg** [comment]
Can you share you exact `run-test.sh` invocation?  The assert means that mscorlib and the runtime disagree about the size of CriticalHandle, which has a [debug only](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/InteropServices/CriticalHandle.cs#L150) field to store an allocation stack trace.  From the assert, it looks like the field is not present in the managed version but is present in the native version.

**Comment by krytarowski** [comment]
```
$ pwd
/tmp/pkgsrc-tmp/wip/corefx-git/work/corefx
$ ./run-test.sh \
--coreclr-bins /usr/pkg/CoreCLR/ \
--mscorlib-bins /public/Tools \
--corefx-tests /public/bin/tests/FreeBSD.AnyCPU.Debug/ \
--corefx-native-bins ./bin/NetBSD.x64.Debug/Native/
```

My steps:
1. Build CoreCLR (with pkgsrc-wip/coreclr-git) on NetBSD x64 Debug and install the `Product` dir to `/usr/pkg/CoreCLR`
2. Build CoreFX native x64 Debug and the work (build) dir is in `/tmp/pkgsrc-tmp/wip/corefx-git/work/corefx`
3. Build CoreCLR Debug x64 on Linux and copy `mscorlib.dll` from `./bin/Product/Linux.x64.Debug/mscorlib.dll` to NetBSD machine under `/usr/pkg/CoreCLR` + copy `./Tools` to NetBSD machine under `/public/Tools`
4. Build CoreFX Debug x64 on Linux and copy `bin/` to NetBSD machine under `/public/bin`
5. Try to run `./run-test.sh` and see ` Consistency check failed: Managed object size does not match unmanaged object size

````
Image:
/public/bin/tests/FreeBSD.AnyCPU.Debug/InterProcessCommunication.Tests/dnxcore50/corerun

********


Assert failure(PID 4059 [0x00000fdb], Thread: -134260736 [0xf7ff5800]): Consistency check failed: Managed object size does not match unmanaged object size
man: 0x18, unman: 0x20, Name: System.Runtime.InteropServices.CriticalHandle
FAILED: size == expectedsize
    File: /tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/vm/binder.cpp Line: 538
    Image: /public/bin/tests/FreeBSD.AnyCPU.Debug/Microsoft.Win32.Registry.Tests/dnxcore50/corerun


Assert failure(PID 4059 [0x00000fdb], Thread: -134260736 [0xf7ff5800]): Consistency check failed: Managed object size does not match unmanaged object size
man: 0x18, unman: 0x20, Name: System.Runtime.InteropServices.CriticalHandle
FAILED: size == expectedsize
    File: /tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/vm/binder.cpp Line: 538
    Image: /public/bin/tests/FreeBSD.AnyCPU.Debug/Microsoft.Win32.Registry.Tests/dnxcore50/corerun

Assert Failure (PID 4059, Thread -134260736/0xf7ff5800)Consistency check failed: Managed object size does not match unmanaged object size
man: 0x18, unman: 0x20, Name: System.Runtime.InteropServices.CriticalHandle
FAILED: size == expectedsize

/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/vm/binder.cpp, Line: 538

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
/public/bin/tests/FreeBSD.AnyCPU.Debug/Microsoft.Win32.Registry.Tests/dnxcore50/corerun
**** MessageBox invoked, title 'corerun - Assert Failure (PID 4059, Thread -134260736/0xf7ff5800)' ****
  Consistency check failed: Managed object size does not match unmanaged object size
man: 0x18, unman: 0x20, Name: System.Runtime.InteropServices.CriticalHandle
FAILED: size == expectedsize

/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/vm/binder.cpp, Line: 538

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
/public/bin/tests/FreeBSD.AnyCPU.Debug/Microsoft.Win32.Registry.Tests/dnxcore50/corerun
```

**Comment by ellismg** [comment]
`--mscorlib-bins` should point to the directory the mscorlib you built is in.  In your case, I believe that's `/usr/pkg/CoreCLR/`.  The way you have it now the test scripts are picking up the runtime that you built yourself and the `mscorlib.dll` that came as part of the toolset.  That is going to be Release and not Debug.

I believe that you shouldn't need to copy the Tools folder over in order to use `run-test.sh`

**Comment by krytarowski** [comment]
Thank you @ellismg -- I think I have some progress.

Here is a partial log:

ftp://ftp.netbsd.org/pub/NetBSD/misc/kamil/corefx-tests-netbsd-1.txt

It's still running, I will check after some hours when I will be back to it.

While there, many tests fail due to missing `Microsoft.Win32` tests/code/support or missing `Microsoft.VisualBasic.Tests.dll` etc. Is it relevant to NetBSD? If not, how to disable Windows-specific tests on NetBSD?

**Comment by nbyouri** [comment]
Great to see some progress for NetBSD!

**Comment by ellismg** [comment]
> missing Microsoft.VisualBasic.Tests.dll

It's possible that the tests just don't get built when building CoreFX on Linux (Maybe VB projects are disabled in general or something?). We still build managed code on Windows all the time when we want to run tests, so we don't see this in CI.

> If not, how to disable Windows-specific tests on NetBSD?

We have some metadata in the CoreFX projects to state if they are [not applicable to some platforms](https://github.com/dotnet/corefx/blob/master/src/Microsoft.Win32.Registry/tests/Microsoft.Win32.Registry.Tests.csproj#L14), which [run-test.sh consumes](https://github.com/dotnet/corefx/blob/master/run-test.sh#L140).  You'll likely want to augment this metadata with NetBSD as a platform.

**Comment by krytarowski** [comment]
@ellismg thanks! I'm still running the tests (a process was hanging for 12h in win32 registers.. I had to kill it to push things forward).

So far there are some bugs triggered, but general numbers doesn't look too bad:

```
   System.Collections.NonGeneric.Tests  Total: 737, Errors: 0, Failed: 0, Skipped: 0, Time: 62,347s
   System.Collections.Tests  Total: 18973, Errors: 0, Failed: 0, Skipped: 0, Time: 1233,538s
```

This issue has been fixed, I'm closing it. Thank you!

**Comment by ellismg** [comment]
Awesome to see the progress, @krytarowski!  Really cool to the see algorithmic stuff like collections working!
