### ISSUE TITLE
build.sh doesn't offer Xmscorlib

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#3417]
https://github.com/dotnet/coreclr/blob/master/Documentation/building/freebsd-instructions.md says:

`D:\git\coreclr> build.cmd freebsdmscorlib`

I don't see this command parameter for `build.sh`.

**Comment by krytarowski** [comment]
@jkotas ^

**Comment by jkotas** [comment]
This option does not exist in build.sh today. I think it would be better to get rid of these one-off paths through build.sh/build.cmd scripts, and instead directly use the msbuild command for bootstrapping. It should be something like:

`Tools/corerun Tools/MSBuild.exe src/mscorlib/mscorlib.csproj /p:__BuildOS=NetBSD /p:__BuildArch=x64 /p:__BuildType=Debug`

BTW: You should be able to use Linux mscorlib.dll for NetBSD bootstrapping just fine. There are unlikely to ever be any differences between Linux mscorlib.dll and NetBSD mscorlib.dll.

**Comment by krytarowski** [comment]
Closing as not an issue.
