### ISSUE TITLE
ARM CI builds broken

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/coreclr#3419]
I was looking at the ARM builds on the Jenkins server and I decided to take a look at the logs for the Ubuntu ARM builds to see if I can figure out why they're failing.  It looks like they're missing the ABI linker package (also known as the emulation mode), which is causing the build to fail almost immediately. Any chance that can be fixed so that the ARM issues can be more easily tracked down?

**Comment by myungjoo** [comment]
I and @leemgs are also interested in adding ARM/Linux CI.
We are actually considering creating one based on our test ARM devices or with developmental ARM emulators _after_ stabilizing coreclr for ARM/Linux, (or at least "release" build starts running the minimal test app) which I don't know when it will be satisfactory.

(we don't have any idea on how to do that for github, yet. so we will need a lot of inputs once we decide to do that.)

Anyway, it would be great if someone else bring it up before we actually start working on it. :)

**Comment by benpye** [comment]
Once @mikem8361 fixes #3487 and #3512 is merged we should be in a position where the ARM build works again. @mmitche would it possible to look at getting this working?

**Comment by mmitche** [comment]
@benpye Yes we can definitely do this. We mostly need to modify the rootfs and get that working again right?  Any thoughts on native compilation?

**Comment by benpye** [comment]
Yep, if the rootfs is regenerated then it should work. Locally at least the scripts produce a usable environment. By native do you mean compilation on the ARM target? If so then that does work for me too.

**Comment by leemgs** [comment]
@benpye, @mmitche, Regarding ARM/Linux CI, the native compilation on the ARM target is too slow.  the cross compilation on Ubuntu 14.04 X64 is better than native compilation on the ARM target in order to generate frequently ARM/Linux binary.

**Comment by benpye** [comment]
@leemgs I agree that native builds are generally going to be slower for lack of sufficiently fast ARM hardware. However I have found that the Jetson TK1 board I have is reasonably fast, though I am generally only doing partial builds. It would probably still be too slow for CI on every commit but certainly fast enough for nightly build and test runs I would believe.

**Comment by myungjoo** [comment]
CC: @prajwal-aithal

**Comment by benpye** [comment]
@mmitche And we need to make sure the correct packages are installed, looks like the bintfmt package might be missing, could be others.

**Comment by mmitche** [comment]
@benpye Is that script that sets up the rootfs up to date?

**Comment by benpye** [comment]
@mmitche Should be, I would ensure that you have all the packages on the host mentioned at https://github.com/dotnet/coreclr/blob/master/Documentation/building/cross-building.md too. Additionally (and somewhat annoyingly) that work around currently has to be done manually but I could possibly modify the rootfs script to update the file automatically.

**Comment by leemgs** [comment]
\CC: @prajwal-aithal , Please check the required packages mentioned at `https://github.com/dotnet/coreclr/blob/master/Documentation/building/cross-building.md` in order that we include ARM CI ( Compilation of .CoreCLR/CoreFX with Linux/ARM Emulator for evaluating .Net Core) into the existing .Net Core CI (e.g., https://github.com/dotnet/dotnet-ci )

**Comment by mmitche** [comment]
@leemgs I fixed up the basic VM image for cross build ARM/ARM64 using the existing ROOTFS @benpye defined in cross\build-rootfs.sh.  I am going to enable that image today, which should cause the build to run again at least.

What kind of changes need to be made to the rootfs/what arm sim needs to be installed on the ubuntu image?  If it's relatively simple I can do it.  Otherwise I can give you access to a VM and you can make the necessary changes (which I'll then capture and apply to existing runs).

**Comment by benpye** [comment]
@mmitche As I said above, pretty sure the change documented in https://github.com/dotnet/coreclr/blob/master/Documentation/building/cross-building.md needs to be applied still, other than that no changes will be needed for a build to complete. However for an emulator to be used for CI I'll leave that to @leemgs .

**Comment by mmitche** [comment]
@benpye I believe i applied that change if the doc was up to date in master as of Wednesday mid-morning

**Comment by benpye** [comment]
Yep then you would of.

**Comment by leemgs** [comment]
>@leemgs I fixed up the basic VM image for cross build ARM/ARM64 using the existing ROOTFS @benpye defined in cross\build-rootfs.sh. 

@mmitche , Thanks, For reference, there are two compilation methods to compile CoreCLR/CoreFX. 
First, Build CoreCLR/CoreFX with cross-build using `cross\build-rootfs.sh `  for Linux/ARM.
   (Fast compilation speed,  !{easy to use} )
Second, Build CoreCLR/CoreFX with native-build using `qemu-arm-static+Chroot `  for Linux/ARM.
   (Easy to use, Support running as well as building, Low compilation speed)

**Comment by leemgs** [comment]
To All

BTW, To talk continually about ARM CI, 
Which better between here and https://github.com/dotnet/dotnet-ci ?

**Comment by mmitche** [comment]
Here is better, dotnet-ci is just for general infrastructure, not necessarily CLR infra.

**Comment by BruceForstall** [comment]
This issue looks obsolete; I am going to close it.
