### ISSUE TITLE
license to distrbute nuget coreclr and corefx packages

### ISSUE THREAD

**Issue by cheers00** [dotnet/coreclr#3420]
What is the license to distribute our coreclr application built with coreclr and corefx packages from nuget? Is it still MIT license?

Thanks

**Comment by jkotas** [comment]
Lookup the package on https://www.nuget.org/. The link to the license is there.

**Comment by cheers00** [comment]
Thanks. I just wanted to confirm. I was bit confused as All MS nuget packages (CLR and CoreCLR) take us to the same Microsoft license web page.
