### ISSUE TITLE
AF: TypeName_path_size == TypeName_full_name_path_size line 563 in eventprovdotnetruntime.cpp

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#3421]
JIT.Generics.Coverage.chaos65204782.cs test hit intermittent crash on Ubuntu x64 Debug on #3410

**Comment by jkotas** [comment]
ASSERT FAILED Expression: TypeName_path_size == TypeName_full_name_path_size Location: line 563 in /mnt/j/workspace/dotnet_coreclr/checked_ubuntu_prtest/bin/obj/Linux.x64.Checked/Generated/eventprovider/lttng/eventprovdotnetruntime.cpp Function: FireEtXplatGCAllocationTick_V3 Process: 12351 ./chaos65204782cs_o.sh: line 58: 12351 Aborted (core dumped)

**Comment by leculver** [comment]
This will be fixed by https://github.com/dotnet/coreclr/pull/5068 as we've re-written these code paths.
