### ISSUE TITLE
Remote debug via SOS plugin

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/coreclr#3426]
Current dotnet core does not seem to provide remote debugging tools. Is there anyway to remote debug managed code now(ex. Remote Debugging from x64/86 host to arm32/64 target)?

**Comment by mikem8361** [comment]
Both native debuggers (windbg for Windows and lldb for Linux/OSX/*BSD) that SOS runs on provide remote debugging.  I never used it on lldb but http://lldb.llvm.org/.

For remote managed debugging I think the Windows desktop Visual Studio will be able to remotely debug a Linux/OSX machine.  This is still a work in progress.

**Comment by chunseoklee** [comment]
@mikem8361 Would you tell me expected date for VS remote (managed code) debugging tool ?

**Comment by zach-folwick** [comment]
This is something that is of great interest to our team as well.

**Comment by mikem8361** [comment]
@gregg-miskelly could you give a better answer on when xplat VS managed debugging will be available?

**Comment by gregg-miskelly** [comment]
@chunseoklee are you asking about Windows support or OSX/Linux?
If Windows - if you aren't compiling to portable PDBs then any version of VS 2015 should work. If you are using portable PDBs, then use VS 2015 Update 2 CTP.
If OSX/Linux - we have a preview of debugging in VS Code which we hope to release _very_ soon. Once we finish testing and work out a few finial licensing things it should hopefully go up on the VS Code gallery.

**Comment by lemmaa** [comment]
Hi @gregg-miskelly, I'm interested in ARM Linux target, such as Raspberry-Pi running Ubuntu, from Windows host with VS2015. Do you have any plan or schedule for this?

**Comment by lemmaa** [comment]
Hi @gregg-miskelly , I also really interested in this topic. Just for check my understanding, you mean that debugging managed code running on remote ARM Linux target, such as Raspberry-Pi running Ubuntu, from Windows host with VS 2015 is working currently?

**Comment by gregg-miskelly** [comment]
No, if your target device is Windows, VS 2015 will work. 
If your target device is x64 OSX/Ubuntu 14.04, we will have local support in VS Code very soon.
We are also planning to support remote from VS to x64 OSX/Ubuntu 14.04 in various forms, but it will be more than just a few days.

Support for versions of Linux other than x64 Ubuntu 14.0 is something that I would expect to come. But right now there is very little support for these from CoreCLR/FX itself.

**Comment by seanshpark** [comment]
@gregg-miskelly, hi, thanks for the info. I want to try the first one. `target device is Windows, VS 2015 will work.`. I've installed VS 2015 Update 2 CTP. Is the any document or notes that I can follow?

**Comment by seanshpark** [comment]
Or, can you verify what I've done?
1) Install VS 2015 Update 2 CTP
2) File > New > Project > (Installed > Templates > Visual C# > Web) > ASP.NET Web Application
3) Select ASP.NET Templates(not sure) > Jumps to a Web Page.
3) Download and Install `AspNet5.ENU.RC1_Update1_KB3137909`
4) Restart VS2015
5) Do again 2)
6) Select ASP.NET 5 Templates > Web Application
7) (New project will be added)
8) Drop down `IIS Express` in Toolbar (usually the debug go button)
9) Select `CLR Type(Profile)` to `.NET Core`
10) Add some line and a break-point
11) Debug-Go
What I see in the `Output` is lots of `.dll` loaded from `.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-update1` folder.

**Comment by mikem8361** [comment]
@gregg-miskelly does @seanshpark's previous comment look correct? Thanks.

**Comment by gregg-miskelly** [comment]
Sorry, no, I wouldn't expect that to work. I was really talking about just the debugging side of things, but your asking about the full end-to-end experience with the project system, and I am afraid I don't know the answer to that. @BillHiebert is there any public .NET CLI ASP.NET VS tooling that @seanshpark can use?

**Comment by BillHiebert** [comment]
Not yet.

**Comment by tzwlai** [comment]
[ASP.NET Core RC2] (https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2) is out!  We also have updated the [Web Development Tools] (https://blogs.msdn.microsoft.com/visualstudio/2016/05/16/announcing-updated-web-development-tools-for-asp-net-core-rc2).  Please give it a try.  Note that remote debugging support for Azure Websites will soon follow (in the next few days) in [Azure SDK 2.9.1] (https://azure.microsoft.com/en-us/downloads) for VS 2015.
