### ISSUE TITLE
Release and maintain a build compiled to asm.js

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/coreclr#344]
The official CLR running on a browser might be neat. Could be an opportunity for C# devs to author code in a similar fashion to GWT.

**Comment by erik-kallen** [comment]
There are other options for that, eg. http://github.com/erik-kallen/SaltarelleCompiler

**Comment by atrauzzi** [comment]
This is more about building the interpreter to run bytecode, not transpiling.

**Comment by MattWhilden** [comment]
Hey @atrauzzi. Thanks for your interest in the project. Someone mentioned this exact thing over at http://www.gitter.im/dotnet/coreclr. While interesting, there's currently no plans to support an asm.js version.

**Comment by MattWhilden** [comment]
There doesn't seem to be much community interest here (unlike say the BSD port efforts) so I'm going to close it out for now. If a group of people get together and want to undertake this, feel free to open a new issue to rally around.
