### ISSUE TITLE
Generate RyuJIT Nuget package using CLI

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3442]
Currently, it appears that RyuJIT nuget package for x64 is only built for Windows (on non-Windows, BuildNugetPackage is false when msbuild is invoked) and is built using nuget.exe that requires Mono to be present.

We would like to eliminate this dependency. Similar work was done for CoreCLR - Please see https://github.com/dotnet/coreclr/commit/f025f9c678b7194d3b125d0cfa4f8c8e9d27beab as an example of how it should be done.

CC @russellhadley

**Comment by kyulee1** [comment]
Should the version number and name convention match with CoreCLR package? Or should I use a prerelease version/name same as now?

**Comment by gkhanna79** [comment]
Given that the JIT will eventually be built in its own repo, it is fine for it to have a different versioning than CoreCLR.

**Comment by RussKeldorph** [comment]
@pgavlin pls look

**Comment by pgavlin** [comment]
This was fixed by #4478.
