### ISSUE TITLE
Use System.Runtime.InteropServices.RuntimeInformation for checking architecture in Test

### ISSUE THREAD

**Issue by kyulee1** [dotnet/coreclr#3443]
Currently we use environment variable to check target architecture. For instance:
https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/Directed/intrinsic/pow/pow1.cs#L25-L26
When this API is fully functional for all targets/platforms, we should use it instead for cross-platforms.

**Comment by stephentoub** [comment]
> When this API is fully functional for all targets/platforms, we should use it instead for cross-platforms.

What "targets/platforms" is it missing?

**Comment by kyulee1** [comment]
As commented here https://github.com/dotnet/coreclr/pull/3429, when I tried it for ARM64/Windows, I got null object.

**Comment by BruceForstall** [comment]
stale; closing
