### ISSUE TITLE
Incorrect result for long to double conversion on Ubuntu with optimizations on

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#3449]
```
using System;

public class Program
{
    public static void Main(string[] args)
    {
        ulong uu = 0x84595161401484A0UL;
        double f = (double)uu;
        Console.WriteLine(String.Format("{0:x}", BitConverter.DoubleToInt64Bits(f)));
    }
}
```

Compile and run using `dotnet run` on Ubuntu 14.04: `43e08b2a2c280290`
Compile and run using `dotnet run -c Release` on Ubuntu 14.04: `43e08b2a2c280291`

Actual result: debug and release builds print different number (last digit is different)
Expected result: debug and release builds print same number

**Comment by jkotas** [comment]
Looks like a bug in JIT optimizations.

**Comment by mikedn** [comment]
When optimizing the JIT is doing constant folding and the cast is replaced with a double constant computed by using C++ code. When optimizations are disabled the JIT generates code that performs the cast at runtime. The code generated by Clang and the code generated by the JIT do not agree and we end up with different results. Eh, did anyone think that constant folding is a trivial optimization? :smile:

**Comment by sejongoh** [comment]
Just to add more details, the release build folds cast instruction in the tree below and generates a double constant which ends up with being 43e08b2a2c280291. The debug build doesn't do this optimization and use cvtsi2sd instruction, which produces 43e08b2a2c280290.

```
Folding fp operator with constant nodes into a fp constant:
               [000002] ---------U--             *  cast      double <- ulong
               [000001] ------------             \--*  const     long   0x84595161401484a0
Bashed to fp constant:
               [000002] ------------             *  dconst    double 9.5367431640625009e+18
```

Debug:
```
IN0006:        mov      rax, 0x84595161401484A0
IN0007:        mov      qword ptr [V01 rbp-10H], rax
IN0008:        mov      rax, qword ptr [V01 rbp-10H]
IN0009:        xorps    xmm0, xmm0
IN000a:        cvtsi2sd xmm0, xrax
```

Release:
```
   @CNS00   DQ      9536743164062500864.000000
IN0001:        movsd    xmm0, qword ptr [reloc @RWD00]
IN0002:        movsd    qword ptr [V03 rbp-10H], xmm0
```

**Comment by sejongoh** [comment]
gcc returns 43e08b2a2c280291.

```
#include <iostream>
#include <stdint.h>

using namespace std;

main()
{
	uint64_t uu = 0x84595161401484A0UL;
	double f = (double)uu;
	uint64_t n = *(uint64_t*)&f;
	cout << hex << uu  << std::endl;
	cout << dec << uu  << std::endl;
	cout << hex << n  << std::endl;
}

> a.out
84595161401484a0
9536743164062500000
43e08b2a2c280291
```

**Comment by sejongoh** [comment]
84595161401484a0 doesn't fit the fraction part of double (52 bits). 

The binary number of 84595161401484a0 is:
```
1000010001011001010100010110000101000000000101001000010010100000
```
and it seems to be rounded up to fit in 52 bits.
```
10000100010110010101000101100001010000000001010010001 
```                                                                                                                    

I am wondering if cvtsi2sd uses a different round mode. I am not very familiar with floating point arithmetic. If I am wrong, please correct me.

**Comment by mikedn** [comment]
> I am wondering if cvtsi2sd uses a different round mode

It's not only `cvtsi2sd` that plays a part here, your disassembly of the conversion code is incomplete. It is:

```
vcvtsi2sd xmm0, rax
test     rax, rax
jge      SHORT G_M26725_IG04
vaddsd   ymm0, qword ptr [reloc @RWD00]
G_M26725_IG04:
```

`cvtsi2sd` converts only signed integers. In the case of unsigned integers the compiler treats the integer as signed and then adjusts the result by adding 2^64 if the integer was negative.

Because the bit pattern that is converted by `cvtsi2sd` is not 
```
1000010001011001010100010110000101000000000101001000010010100000 (64 bits)
```

but its absolute value
```
0111101110100110101011101001111010111111111010110111101101100000
```
and this is converted to
```
01110111010011010101110100111101011111111101011011111 (52 bits and exponent 62)
```
Obviously, this conversion is done using round to nearest as expected (that's the default for `cvtsi2sd`).

But then 2^64 needs to be added to this value. I haven't done the FP math but I suspect that a bit will end up being lost along the way and the final result looks like it was rounded down instead to nearest.

I haven't checked what code GCC/Clang generate but obviously they're doing something that looks like round to nearest. The C++ standard doesn't impose a particular rounding mode on such conversions so both VC++ and GCC/Clang are correct (though it could be argued that GCC/Clang result is more accurate). The JIT ends up being caught in the middle, it generates code like VC++ but does constant folding like VC++ or Clang depending on how the platform.

**Comment by mikedn** [comment]
> The C++ standard doesn't impose a particular rounding mode on such conversions so both VC++ and GCC/Clang are correct 

BTW, the IL spec doesn't seem to say anything about this issue either. It may be that both results are "correct", the main issue is the inconsistency between debug and release which is IMO a bit undesirable.

**Comment by mikedn** [comment]
> the main issue is the inconsistency between debug and release which is IMO a bit undesirable

I'm stupid. The same inconsistency can show up in release builds. It's not like the JIT can always constant fold expressions that aren't constant. IMO, it would be nice to change the way the conversion is done to be consistent with the native compilers of the platform the runtime runs on.

**Comment by sejongoh** [comment]
Oh i see. I totally missed the adjustment part. FYI, GCC generates:

```
  4006db:       48 89 45 f8             mov    %rax,-0x8(%rbp)
  4006df:       48 8b 45 f8             mov    -0x8(%rbp),%rax
  4006e3:       48 85 c0                test   %rax,%rax
  4006e6:       78 07                   js     4006ef <main+0x22>
  4006e8:       f2 48 0f 2a c0          cvtsi2sd %rax,%xmm0
  4006ed:       eb 15                   jmp    400704 <main+0x37>
  4006ef:       48 89 c2                mov    %rax,%rdx
  4006f2:       48 d1 ea                shr    %rdx
  4006f5:       83 e0 01                and    $0x1,%eax
  4006f8:       48 09 c2                or     %rax,%rdx
  4006fb:       f2 48 0f 2a c2          cvtsi2sd %rdx,%xmm0
  400700:       f2 0f 58 c0             addsd  %xmm0,%xmm0
  400704:       f2 0f 11 05 4c 09 20    movsd  %xmm0,0x20094c(%rip)        # 601058 <f>
```

**Comment by mikedn** [comment]
Makes sense, by dividing by 2 it avoids feeding negative values to `cvtsi2sd`. Also note how bit0 is "mixed" with bit1 to prevent rounding down instead of to nearest.

**Comment by sejongoh** [comment]
Fixed: https://github.com/dotnet/coreclr/pull/3655/
