### ISSUE TITLE
Implement ExternalMethodFixupStub, VirtualMethodFixupStub and StubDispatchFixupStub for UNIX

### ISSUE THREAD

**Issue by kangaroo** [dotnet/coreclr#345]
I'll take this.

Needed for https://github.com/dotnet/coreclr/issues/227

**Comment by richlander** [comment]
Just a suggestion. When you take it, can you self-assign?

**Comment by kangaroo** [comment]
@richlander When I got moved from the org to the pub-org, I no longer have permission to do that.  I think I sent you a mail about that?
