### ISSUE TITLE
Patch 266ee6 breaks ARM Build

### ISSUE THREAD

**Issue by myungjoo** [dotnet/coreclr#3453]
The following patch (@mikem8361):

> commit 266ee6dc6d688ec973acfee2e30d61877cd288be
> Author: Mike McLaughlin <mikem@microsoft.com>
> Date:   Sat Feb 20 00:27:33 2016 -0800
> 
>     Create a version resilient interface between sos (libsos.so) and the lldb plugin
>     (libsosplugin.so). There is a ILLDBServices interface between the two with a proper
> 

breaks ARM build (and is expected to break all other 32bit architectures)
because it unconditionally says to build "DBIT64".

```
@@ -1,16 +1,18 @@
 project(sosplugin)
 
 set(CMAKE_INCLUDE_CURRENT_DIR ON)
 
+add_definitions(-DPAL_STDCPP_COMPAT -DBIT64)
+
 if(CLR_CMAKE_PLATFORM_ARCH_AMD64)
     add_definitions(-D_TARGET_AMD64_=1)
     add_definitions(-DDBG_TARGET_64BIT=1)
```

Please revert or fix the commit 266ee6dc6d688ec973acfee2e30d61877cd288be

**Comment by mikem8361** [comment]
Fixed.
