### ISSUE TITLE
lldb debug error in libmscordaccore.so

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/coreclr#3454]
I am following the debug instruction in https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md
I am working on x64 ubuntu 14.04 with commit 0a3fe0f45ae75f31db0b5d2518847ed51b4f13dd
I just stucked in loading libmscordaccore.so 
The log is as follows :
  
$ lldb-3.6 -o "plugin load libsosplugin.so" -o "process launch -s" -o "process handle -s false SIGUSR1 SIGUSR2" -o "setclrpath ./" -- corerun -c ./ HelloWorld.exe
(lldb) target create "corerun"
Current executable set to 'corerun' (x86_64).
(lldb) settings set -- target.run-args  "-c" "./" "HelloWorld.exe"
(lldb) plugin load libsosplugin.so
(lldb) process launch -s
Process 12082 launching
(lldb) Process 12082 launched: '/home/twoflower/Downloads/tmp/coreclr/bin/Product/Linux.x64.Debug/corerun' (x86_64)
(lldb) process handle -s false SIGUSR1 SIGUSR2
NAME        PASS   STOP   NOTIFY
==========  =====  =====  ======
SIGUSR1     true   false  true 
SIGUSR2     true   false  true 
(lldb) setclrpath ./
Set load path for sos/dac/dbi to './'
(lldb) bpmd
Failed to load data access DLL, 0x80004005
You can run the debugger command 'setclrpath' to control the load of libmscordaccore.so.
If that succeeds, the SOS command should work on retry.
bpmd  failed
(lldb) 

all .so files are in the same disrectory of HelloWorld.exe and libsosplugin.so. Instead of relative path  `./` , applying absolute path like `setclrpath /home/dotnet/bin/Linux.x64.Debug/` does not work either.

**Comment by chunseoklee** [comment]
This issue is resolved by myself :)
except from soshelp bpmd 

This brings up a good question: "I want to set a breakpoint on the main
method of my application. How can I do this?"
  1) Stop after coreclr is loaded - TBD
  2) Add the breakpoint with command such as:
       bpmd myapp.exe MyApp.Main
  3) g
  4) You will stop at the start of MyApp.Main. If you type "bl" you will
     see the breakpoint listed.

Thus, we can do 1) by commanding ``` breakpoint set -n LoadLibraryExW ``` and continue.

**Comment by janvorli** [comment]
For 1), You can also use breakpoint set -n coreclr_execute_assembly

**Comment by leemgs** [comment]
@myungjoo , @chunseoklee , @benpye , @jkotas , @janvorli 

Here is another issue of SOS-Plugin on Linux/ARM. I have tried to run `hello.exe `with LLDB + SOS-Plugin on Ubuntu/ARM 14.04 32bit in order to enable release mode of Linux/ARM as well as debug mode of that. At that time, I used the commit number  of CoreCLR+CoreFX that are released on Mar-17-2015 to apply the latest changes of LLDB + SOS-Plugin. Unfortunately, I have met the **Segmentation fault** when I tried to run **breakpoint set -n LoadLibraryExw** as following: 

```
(lldb) Process 28143 launched: '/opt/dotnet/hardfp-runtime/runtime-hardfp-debug-mode-20160318.2/corerun' (arm)
(lldb) breakpoint set -n LoadLibraryExW
Segmentation fault
(trusty)root@localhost:/opt/dotnet/hardfp-runtime/runtime-hardfp-debug-mode-20160318.2# lldb-3.6  -o "plugin load libsosplugin.so" -o "process launch -s" corerun  ./HelloWorld.exe
(lldb) target create "corerun"
Current executable set to 'corerun' (arm).
(lldb) settings set -- target.run-args  "./HelloWorld.exe"
(lldb) plugin load libsosplugin.so
(lldb) process launch -s
Process 28241 launching
(lldb) Process 28241 launched: '/opt/dotnet/hardfp-runtime/runtime-hardfp-debug-mode-20160318.2/corerun' (arm)
(lldb) breakpoint set -n LoadLibraryExw
Segmentation fault
```

Anyone who had the similar experience on Linux/ARM? To narrow the issue scope of `Segmentation Fault`,  I have checked the function of LLDB itself.  It's ok. It seems that this issue happens by " libsosplugin.so" plugin. If someone give us a hint or a clue on this issue, I will be happy. : ) 

```
(trusty)root@localhost:/opt/dotnet/hardfp-runtime/runtime-hardfp-debug-mode-20160318.2# lldb-3.6 corerun
(lldb) target create "corerun"
Current executable set to 'corerun' (arm).
(lldb) br set main
error: invalid combination of options for the given command
(lldb) breakpoint set main
error: invalid combination of options for the given command
(lldb) breakpoint set -n main
Breakpoint 1: 2 locations.
(lldb) r
Process 29482 launching
Process 29482 launched: '/opt/dotnet/hardfp-runtime/runtime-hardfp-debug-mode-20160318.2/corerun' (arm)
(lldb) Segmentation fault
(trusty)root@localhost:/opt/dotnet/hardfp-runtime/runtime-hardfp-debug-mode-20160318.2# 
(trusty)root@localhost:/opt/dotnet/hardfp-runtime/runtime-hardfp-debug-mode-20160318.2# 
(trusty)root@localhost:/opt/dotnet/hardfp-runtime/runtime-hardfp-debug-mode-20160318.2# 
```

**Comment by benpye** [comment]
Are you certain that lldb works without the plugin? I recall it seg-faulting on ARM on any binary. Perhaps this has changed, that was version 3.6.

**Comment by manu-silicon** [comment]
@benpye @leemgs For me, lldb is simply not working on ARM, it segfaults immediately after starting a process.

**Comment by chunseoklee** [comment]
For me, lldb-3.6 not working on ARM Linux with the same pattern as manu-ailicon. I cannot launch a process in lldb.
