### ISSUE TITLE
Question - What is the most optimal way to return an empty List<T> instance in .NET Core?

### ISSUE THREAD

**Issue by jasonwilliams200OK** [dotnet/coreclr#3465]
```c#
/*
   Method signature:
   List<T> GetList<T>(); // frequently called and returns an empty list if someCondition is met
*/

return Enumerable.Empty<T>().ToList();
// or
return Array.Empty<T>().ToList();
// or
return new List<T>(0);
// or
return new List<T>();
// or would a proposal for List.Empty<T>() make any sense?
```

**Comment by mikedn** [comment]
Why would you even consider anything other than `new List<T>()`? All other variants are more complicated and thus inherently less efficient.

> or would a proposal for List.Empty<T>() make any sense?

Nope, unlike empty arrays empty lists aren't immutable.

**Comment by i3arnon** [comment]
What are you using this instance for?
If you plan on possibly mutating it then it must be a new instance each time so `new List<T>()` (which is equivalent to `new List<T>(0)`).

If you want to imitate `Enumerable.Empty<T>()` for read-only usage I would use `IReadOnlyCollection<T>` (or `IReadOnlyList<T>`) and return the same empty instance for all calls (i.e. `Array.Empty`).

**Comment by jasonwilliams200OK** [comment]
Thanks @mikedn for mentioning the mutability, I totally forgot about that. I think reusing the same instance of empty list would make sense or the `IReadOnlyList` (as @i3arnon suggested) will also work in my use case.

> What are you using this instance for?

I am returning list of online users' nicknames (fetched from the Azure table storage) to a method (aspnet-core API action), which serializes the list in JSON (, merges another JSON metadata chunk to it) and responds to HTTP requests.
