### ISSUE TITLE
ecall.cpp "id != 0" assertion

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#3474]
While running CoreFX on NetBSD tests I'm getting the following assert:

```
**** MessageBox invoked, title 'corerun - Assert Failure (PID 18572, Thread -271511552/0xefd11000)' ****
  id != 0

/tmp/pkgsrc-tmp/wip/coreclr-git/work/coreclr/src/vm/ecall.cpp, Line: 547

Abort - Kill program
Retry - Debug
Ignore - Keep running
```

**Comment by ellismg** [comment]
I'm not an expert in this area, but looking at the code in question it looks like the runtime is unable to find a corresponding native method for a QCall (which is a call from the mscorlib.dll into the runtime itself).

You might try exporting `COMPlus_ConsistencyCheck=1` to have the runtime provide more diagnostics about mismatches between mscorlib and coreclr.  I expect it will assert on boot and might give a clearer picture around what is failing.

The other option would be to debug this with lldb, use sos to dump the MethodTable and then look at the source to figure out exactly what QCall we were trying to use and figure out why the target does not exist in your build of CoreCLR.

**Comment by krytarowski** [comment]
Ah, good pointers. Thank you!

**Comment by krytarowski** [comment]
I'm not seeing it any more
