### ISSUE TITLE
Way to exclude tests under specific test modes (jitstress, gcstress, etc.)

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#3485]
Some tests fail by design under certain test modes.  When running under those modes, certain tests shouldn't be run or their failures should be ignored or "baselined away."  For example:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_checked_windows_nt_jitstress2/27/testReport/

**Comment by AndyAyersMS** [comment]
We have the ability to specify multiple exclude files so you could have a stress-specific exclude set that the stress job knows to use.

**Comment by RussKeldorph** [comment]
@AndyAyersMS Right, I'm currently assuming the solution will involve exclude files in some form.  I'm pretty sure the test scripts will require some amount of work, though.  Like I don't think runtest.sh supports additional exclusion files beyond the default.

**Comment by RussKeldorph** [comment]
Fixed by #3659
