### ISSUE TITLE
JIT\Directed\forceinlining\PositiveCase failing under some JitStress modes

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#3486]
If this test is simply incompatible with these modes and needs to be excluded, just refer to #3485 and close this issue.

Examples (there are more if you need them)
Windows x64 Checked
set COMPlus_JitStress=2
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_checked_windows_nt_jitstress2/lastCompletedBuild/testReport/JIT/_Directed_forceinlining_PositiveCases_PositiveCases_/_Directed_forceinlining_PositiveCases_PositiveCases_cmd/

Ubuntu x64 Checked
export COMPlus_JitStress=2
export COMPlus_JitStressRegs=4
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_checked_ubuntu_jitstress2_jitstressregs4_tst/lastCompletedBuild/testReport/JIT.Directed.forceinlining/PositiveCases/PositiveCases/

**Comment by AndyAyersMS** [comment]
`JitStress=2` doesn't play nicely with inlining tests. It may toggle on force inline or min opts, and it does so deterministically but unpredictably (via the method hash).

I'll double check this case just to be sure that's what is happening, but it seems pretty likely.

**Comment by RussKeldorph** [comment]
@AndyAyersMS That's what I figured.  Just wanted to give you a chance to confirm.

**Comment by AndyAyersMS** [comment]
In this test the inlines into `Main` are crucial and `JitStress=2` recompiles it with min-opts. So referring to #3845 and closing.
