### ISSUE TITLE
Remove dotnet restore CORE_ROOT workaround when CLI is upgraded

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#3493]
In order to work around https://github.com/dotnet/cli/issues/1663 for dotnet CLI 1.0.0.001504, these workarounds were put in place to unset `CORE_ROOT` during restore:

* https://github.com/dotnet/coreclr/blob/0d71a87375bfa54af10b68b74a4c8d93430ed308/tests/dir.props#L78
* https://github.com/dotnet/coreclr/blob/0d71a87375bfa54af10b68b74a4c8d93430ed308/dir.props#L99

When CLI is upgraded these workarounds should be removed.

**Comment by sergiy-k** [comment]
Hi @dagood, can this workaround be removed now?

**Comment by dagood** [comment]
Yeah, we should be able to remove it now, I'll try it out. Thanks for the reminder!
