### ISSUE TITLE
Jit interface: add helper method to raise NullReferenceException

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/coreclr#350]
This should be similar to the existing helpers for OverflowException and DivideByZeroException.  Adding this will simplify the task of a jit implementing implicit MSIL null checks.

Per @jkotas, implementation should be straight-forward boilerplate, so I'm tentatively assigning this to myself and will take a stab at putting a PR together.

**Comment by jkotas** [comment]
@russellhadley is working on JIT-EE interface change as well - it may be easiest to fold the two together.

**Comment by JosephTremoulet** [comment]
@russellhadley, what do you think?  Do you want to pull [my changes](https://github.com/JosephTremoulet/coreclr/tree/issue-350) in with yours, or should we go separate?

**Comment by russellhadley** [comment]
Joe let's pull your changes in with mine.  I'll also need to fold these in with my superPMI changes.  To maintain the SuperPMI testing harness parallel changes need to be made in other source code.  (and I've already worked through how to test it)

**Comment by jkotas** [comment]
Fixed by #485
