### ISSUE TITLE
Build fails on Windows 7 Professional x64

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/coreclr#3510]
After updating to the latest head of the repo, installing dependencies, and running `build clean`, the build fails, looking for `CoreRun.exe` in the wrong place:

>   '"D:\DEVELOPMENTDIR\coreclr\Tools/CoreRun.exe"' is not recognized as an internal or external command,
>  operable program or batch file.

Full output from the build process can be found [here](http://pastebin.com/WzqkE42x), to avoid spamming up this issue report with >100 KB of stuff that may or may not be relevant.  As you can see, CoreRun.exe is getting generated, just not in the directory it's looking for it in at the point of failure.

**Comment by masonwheeler** [comment]
After discussing this with @AndyAyersMS and @RichiCoder1, it appears that the problem is that the build script uses classes that are not supported in PowerShell 2.0, the version installed by default in Windows 7, and [the readme for building CoreCLR on Windows](https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md) only says that PowerShell is needed, without specifying a minimum supported version.

**Comment by mkborg** [comment]
The same problem with CoreRun.exe on recent master (0166b60325807abea17f3dd36ec729216ec7da81)

> C:\git\coreclr\src\mscorlib\Tools\BclRewriter\BclRewriter.targets(27,5): error MSB3073: The command ""C:\git\coreclr\Tools/CoreRun.exe" "C:\git\coreclr\Tools/BclRewriter.exe" -in:"C:\git\coreclr\bin\obj\Windows_NT.x64.Debug\mscorlib.dll" -out:"C:\git\coreclr\bin\obj\Windows_NT.x64.Debug\\BclRewriter\mscorlib.dll" -include:"C:\git\coreclr\src\mscorlib\model.xml" -platform:win -architecture:amd64 -flavor:chk ...  -keepTempFiles+" exited with code 9009. [C:\git\coreclr\src\mscorlib\mscorlib.csproj]

but with powershell v.4.0:
> C:\git\coreclr>powershell get-host
Name             : ConsoleHost
Version          : **4.0**
InstanceId       : 76109ca6-3aa2-4cf6-8480-0cd1ce1d78f5
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : ru-RU
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

Probably build scripts look for CoreRun.exe in wrong place:
> $ find . -iname corerun.exe
./coreclr/bin/obj/Windows_NT.x64.Debug/src/coreclr/hosts/corerun/Debug/CoreRun.exe
./coreclr/bin/Product/Windows_NT.x64.Debug/CoreRun.exe

**Comment by mkborg** [comment]
I have compared 'release/1.0.0-rc2' and 'master' build trees and found the difference:
> $ find . -iname corerun.exe
./coreclr/bin/obj/Windows_NT.x64.Debug/src/coreclr/hosts/corerun/Debug/CoreRun.exe
./coreclr/bin/Product/Windows_NT.x64.Debug/CoreRun.exe
**./coreclr/Tools/CoreRun.exe**
./coreclr/Tools/dotnetcli/bin/CoreRun.exe

Looks like in case of 'master' build scripts do not install 'CoreRun.exe' into 'Tools' subdirectory.

**Comment by mkborg** [comment]
According to time-stamp 'CoreRun.exe' in 'Tools' subdirectory is not built but installed from external source:
> $ ls -l \`find . -iname corerun.exe\`
-rwxrwx---+ 1 john None 1096704 Apr  5 14:50 ./coreclr/bin/obj/Windows_NT.x64.Debug/src/coreclr/hosts/corerun/Debug/CoreRun.exe
-rwxrwx---+ 1 john None 1096704 Apr  5 14:50 ./coreclr/bin/Product/Windows_NT.x64.Debug/CoreRun.exe
-rwxrwx---+ 1 john None  108456 **Mar  6** 20:45 ./coreclr/Tools/CoreRun.exe
-rwxrwx---+ 1 john None   37800 Feb 29 21:06 ./coreclr/Tools/dotnetcli/bin/CoreRun.exe

```

**Comment by AndyAyersMS** [comment]
With older powershells, the build tool restore step fails quietly, and the build then fails in a fairly obscure fashion.

The restore failure should really be more prominent.

It is extra confusing because the build tool restore downloads a prebuilt CoreCLR, so as you note there is more than one CoreCLR.exe around....

You can [download](http://social.technet.microsoft.com/wiki/contents/articles/21016.how-to-install-windows-powershell-4-0.aspx) more recent powershell for Win7 SP1.

**Comment by mkborg** [comment]
That 'hidden' download is very annoying. If it fails for any reason then the only solution is to restart build and watch how it redownloads almost everything again and again. In my case time spent for dowload several times exceeds time spent for actual build. I would prefer to explicitly download all dependencies only once and reuse them on each rebuild.

**Comment by masonwheeler** [comment]
@AndyAyersMS Having the download link there is useful.  Having it [in the official build process documentation](https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md) would be much more useful.  Right now, anyone who doesn't know to look at this specific issue has no way of knowing that the build process requires a certain minimum version of PowerShell.

**Comment by AndyAyersMS** [comment]
Agreed.  I've started working on a patch to detect this and other issues in tools restore. Not sure I have the ability to properly test it, though.

**Comment by AndyAyersMS** [comment]
@mkborg can you test out [this potential patch](https://github.com/AndyAyersMS/coreclr/tree/CheckToolRestore)? If It works I'll update the docs too.

I'll see if I can find a Win7 box to try it on... maybe I have one lying around here somewhere.

**Comment by AndyAyersMS** [comment]
This is mainly to detect and flag errors, so it may not keep you from needing to repeatedly try downloads if there are network issues. But once one download succeeds it should be good for a while, until you sync a change where someone's updated the buildtools....

**Comment by mkborg** [comment]
Unfortunately right now I am far away from my Windows box. I will be able to test the patch only on Monday when I return back.

**Comment by AndyAyersMS** [comment]
I found win7 box, and verified that the powershell version check fires. Will send this out for PR.

**Comment by sergiy-k** [comment]
Addressed by https://github.com/dotnet/coreclr/pull/4374. Thank you!
