### ISSUE TITLE
Windows on ARM has already bitrotted

### ISSUE THREAD

**Issue by kika123** [dotnet/coreclr#3514]
Windows on ARM 32-bits support has already started bitrotting and is currently uncompilable without patches

**Comment by AndyAyersMS** [comment]
@sergiy-k we can close this now, right?

**Comment by sergiy-k** [comment]
Yes, I think so.

**Comment by AndyAyersMS** [comment]
@kika123 windows on arm32 support is currently alive and well, so closing this.
