### ISSUE TITLE
ARM64: NYI assert in vm\arm64\stubs.cpp for RedirectedHandledJITCaseForGCThreadControl_Stub

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3515]
Several tests that normally pass will intermittently fail with this assert:
  !"ARM64:NYI"
d:\projectk\src\ndp\clr\src\vm\arm64\stubs.cpp, Line: 1039

%CORERUN% JIT\Methodical\int64\arrays\_speed_dbglcs_ulong\_speed_dbglcs_ulong.exe

**Comment by briansull** [comment]
Tests that occasionally fail with this assert:

_il_dbglcs_long.exe_4054
_speed_dbglcs_long.exe_4061
_speed_dbglcs_ulong.exe_4062

**Comment by rahku** [comment]
Verified that the above tests pass with fixes in above PR Except below two tests which are no longer in cache copy of build
b425314.exe_5446 # JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314\b425314.exe
 b426654.exe_5447 # JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b426654\b426654\b426654.exe
