### ISSUE TITLE
RyuJIT x86: Alignment assert when emitting a floating-point convert instruction

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#3516]
This assert in emitxarch.cpp (near line 8730):
Assertion failed '(emitChkAlign==false) || (ins == INS_lea) || (((size_t)addr & (byteSize - 1)) == 0)'

Is being hit in the following tests:
JIT\Regression\CLR-x86-JIT\V1.2-Beta1\b220968\b220968\b220968.cmd
in 'ILGEN_0x5c19e96e:f():int' (IL size 81)
JIT\Methodical\ELEMENT_TYPE_IU\_il_dbgsizeof\_il_dbgsizeof.cmd
in '_simple:main(ref):int' (IL size 79)
JIT\Methodical\stringintern\_XModuletest1-xmod\_XModuletest1-xmod.cmd
in 'FullProof:Main():int' (IL size 66)
JIT\IL_Conformance\Old\Conformance_Base\ldarga_i8\ldarga_i8.cmd
in 'ConvTest:test1():byte' (IL size 23)
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b59948\b59948\b59948.cmd
in 'FloatOvfToInt:TestValuesFloatInt():int' (IL size 81)
JIT\Methodical\int64\signed\_il_dbgs_ldc_mul\_il_dbgs_ldc_mul.cmd
in '_simple:main(ref):int' (IL size 51)
JIT\IL_Conformance\Old\Conformance_Base\div_r8\div_r8.cmd
in 'ConvTest:test1():byte' (IL size 23)
JIT\Directed\coverage\oldtests\cse1_cs_d\cse1_cs_d.cmd
in 'ILGEN_0xbffa35b3:Method_0xe384245b(long,double,int,char,int):char' (IL size 116)
JIT\Methodical\int64\signed\_rels_ldc_mulovf\_rels_ldc_mulovf.cmd
in 'FloatOvfToInt:TestValuesFloatInt():int' (IL size 81)

**Comment by CarolEidt** [comment]
I had a one-off error in my processing of the failures. Here is the correct list:
JIT\Regression\CLR-x86-JIT\V1-M10\b05637\b05637\b05637.cmd
in '_simple:main(ref):int' (IL size 79)
JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b323557\b323557-dbg\b323557-dbg.cmd
in 'FullProof:Main():int' (IL size 66)
JIT\Methodical\NaN\r4nanconv_il_r\r4nanconv_il_r.cmd
in 'ConvTest:test1():byte' (IL size 23)
JIT\Methodical\Overflow\FloatInfinitiesToInt_do\FloatInfinitiesToInt_do.cmd
in 'FloatOvfToInt:TestValuesFloatInt():int' (IL size 81)
JIT\Regression\CLR-x86-JIT\V1-M10\b05617\b05617\b05617.cmd
in '_simple:main(ref):int' (IL size 51)
JIT\Methodical\NaN\r4nanconv_il_d\r4nanconv_il_d.cmd
in 'ConvTest:test1():byte' (IL size 23)
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b69848\b69848\b69848.cmd
in 'ILGEN_0xbffa35b3:Method_0xe384245b(long,double,int,char,int):char' (IL size 116)
JIT\Methodical\Overflow\FloatInfinitiesToInt_ro\FloatInfinitiesToInt_ro.cmd
in 'FloatOvfToInt:TestValuesFloatInt():int' (IL size 81)

**Comment by BruceForstall** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/4646
