### ISSUE TITLE
Nuget Command to Build and Run on Unix Appears Out of Date

### ISSUE THREAD

**Issue by evolvedmicrobe** [dotnet/coreclr#352]
In the `Build and Run on Unix Tutorial' (https://github.com/dotnet/coreclr/wiki/Building-and-Running-CoreCLR-on-Linux) one instruction says to get the dll's from Nuget via this command:    

    mono nuget.exe restore -Source https://www.myget.org/F/dotnet-corefx/ -PackagesDirectory .

However this fails with:

    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    WARNING: Error: SendFailure (Error writing headers)
    Unable to find version '4.0.0-beta-22512' of package 'System.Console'.
    Unable to find version '4.0.0-beta-22512' of package 'System.Diagnostics.Contracts'.
    Unable to find version '4.0.10-beta-22512' of package 'System.Diagnostics.Debug'.
    Unable to find version '4.0.0-beta-22512' of package 'System.Diagnostics.Tools'.
    Unable to find version '4.0.10-beta-22512' of package 'System.Globalization'.
    Unable to find version '4.0.10-beta-22512' of package 'System.IO'.
    Unable to find version '4.0.0-beta-22512' of package 'System.IO.FileSystem.Primitives'.
    Unable to find version '4.0.10-beta-22512' of package 'System.Reflection'.
    Unable to find version '4.0.0-beta-22512' of package 'System.Resources.ResourceManager'.
    Unable to find version '4.0.20-beta-22512' of package 'System.Runtime'.
    Unable to find version '4.0.10-beta-22512' of package 'System.Runtime.Extensions'.
    Unable to find version '4.0.0-beta-22512' of package 'System.Runtime.Handles'.
    Unable to find version '4.0.20-beta-22512' of package 'System.Runtime.InteropServices'.
    Unable to find version '4.0.10-beta-22512' of package 'System.Text.Encoding'.
    Unable to find version '4.0.10-beta-22512' of package 'System.Text.Encoding.Extensions'.
    Unable to find version '4.0.0-beta-22512' of package 'System.Threading'.
    Unable to find version '4.0.10-beta-22512' of package 'System.Threading.Tasks'.

**Comment by akoeplinger** [comment]
@evolvedmicrobe this looks like an error with the HTTPS certificates, try running `mozroots --import --sync` if you're running Mono before version 3.12 (on newer versions the certificate import happens automatically).

**Comment by evolvedmicrobe** [comment]
Wow, yep that did it!  Though I was running mono 3.12, so I am not sure why it failed.  In any event, thanks kindly for the tip!

**Comment by akoeplinger** [comment]
@evolvedmicrobe did you install mono 3.12 from the xamarin repositories or did you compile it yourself? In the latter case it would be expected, since the certificate sync happens as a hook in the .deb package.

**Comment by evolvedmicrobe** [comment]
Ah, not I compiled myself from the tarball, so that explains it.  

Unrelated to this, do you know if I can just copy the rest of the CLR .dll files over from a windows build onto a unix machine and run them? (or add them to the nuget package list?).  Am very excited about getting a working coreclr runtime going on ubuntu, and would love to add the rest of the libraries.

**Comment by akoeplinger** [comment]
Do you mean the base class libraries from CoreFx? That is already outlined in the guide.

**Comment by evolvedmicrobe** [comment]
Yes, the BCL libraries.  I compiled all of the corefx libraries on a windows machine per the instructions and moved them over to the directory with the ./corerun script.  I was hoping that these two simple things would be enough to allow me to run .NET assemblies using the coreclr.  However, after taking an exe that runs in mono and calling it with the corerun script, the following error appears:



    Assert failure (unable to format)
    /home/UNIXHOME//git/coreclr/src/utilcode/ccomprc.cpp
    false && "UNIXTODO: Implement string loading from resources"
    **** MessageBox invoked, title 'Assert failure (unable to format)' ****
      false && "UNIXTODO: Implement string loading from resources"
    ********    

    {0x7f7f421a4780-0x7f7f40c07d10} ASSERT [DEBUG  ] at /home/UNIXHOME//coreclr/src/pal/src/arch/i386/context.cpp.678: Got unknown signal number 11 with code 128
    Segmentation fault (core dumped)
    user@node:~/coreclr/runtime$ ./corerun Test.exe
    Assert failure (unable to format)
    /home/UNIXHOME/git/coreclr/src/utilcode/ccomprc.cpp
    false && "UNIXTODO: Implement string loading from resources"
    **** MessageBox invoked, title 'Assert failure (unable to format)' ****
      false && "UNIXTODO: Implement string loading from resources"
    ********    

    {0x7fa9d5e33780-0x7fa9d4896d10} ASSERT [DEBUG  ] at /home/UNIXHOME//git/coreclr/src/pal/src/arch/i386/context.cpp.678: Got unknown signal number 11 with code 128
    Segmentation fault (core dumped)

I am guessing that although hello world works, other command line applications may not.  Is that a good summary of the state of things? Is there a way to tell what will/will not work ahead of time?

**Comment by kangaroo** [comment]
Did you build the exe against System.Runtime?  That crash looks like missing assemblyref to me.

**Comment by evolvedmicrobe** [comment]
Hmm not sure, I have tried three different ways to compile.  

1 - Compile in VS2013 and copy to ubuntu - This results in the error shown above.
2 - Compile with mcs on ubuntu using a standard command or
3 - Compile with mcs on ubuntu but using the flags and specific references as in the hello world example. 

The last two of these give me a different error shown below:

    ********    

    Assert failure(PID 7157 [0x00001bf5], Thread: 691022304 [0x293029e0]): Assertion failed '(int)offs >= 0' in 'TransitionTime:ValidateTransitionTime(struct,int,int,int,int)' (IL size 220)    

        File: /home/UNIXHOME//git/coreclr/src/jit/emitxarch.cpp, Line: 1758 Image:
    /home/UNIXHOME//coreclr/runtime/corerun
    **** MessageBox invoked, title 'corerun - Assert Failure (PID 7157, Thread 691022304/293029e0)        ' ****
      Assertion failed '(int)offs >= 0' in 'TransitionTime:ValidateTransitionTime(struct,int,int,int,int)' (IL size 220)    
    
    /home/UNIXHOME//git/coreclr/src/jit/emitxarch.cpp, Line: 1758    

    Abort - Kill program
    Retry - Debug
    Ignore - Keep running    
    

    Image:
    /home/UNIXHOME//coreclr/runtime/corerun    
    
    ********

Any chance you see a quick fix here?

**Comment by kangaroo** [comment]
That assert is different, your code is triggering something that shouldn't happen in that case.  Make a testcase that exhibits it and submit an issue?

**Comment by evolvedmicrobe** [comment]
Thanks, just submitted small test case as an issue.
