### ISSUE TITLE
Cannot update Microsoft.NETCore.UniversalWindowsPlatform package

### ISSUE THREAD

**Issue by arturl** [dotnet/coreclr#3520]
Repro steps:

1. Create a blank UWP app using VS 2015U1
2. Open References | Manage NuGet Package
3. Try to update Microsoft.NETCore.UniversalWindowsPlatform package to 5.2.0-rc3-23904

Results:

Many packages are reported as "not compatible with UWP", such as:

Microsoft.Win32.Primitives 4.0.1-rc3-23904 is not compatible with UAP,Version=v10.0.
System.Diagnostics.StackTrace 4.0.1-rc3-23904 is not compatible with UAP,Version=v10.0.
...

**Comment by weshaggard** [comment]
Microsoft.NETCore.UniversalWindowsPackage 5.2.0 is prerelease and isn't yet supported to be consumed by UWP apps. It currently gets built and pushed to our dev feed but we are in a transition with our packages which makes it not functional with existing tools. 

For UWP you should stick to the packages that are nuget.org.

**Comment by markmnl** [comment]
When will be able to use any recent NET Core from UWP? 

I have been waiting months to use the new (old) Socket API which was committed to corefx Oct 2015: https://github.com/dotnet/corefx/pull/4079/files

**Comment by weshaggard** [comment]
I've added a tracking issue on corefx https://github.com/dotnet/corefx/issues/7466 to have this looked in more closely to make sure our prerelease packages can function in UWP.

**Comment by markmnl** [comment]
Thanks

**Comment by JijoBose** [comment]
I'm not able to update **Microsoft.NETCore.UniversalWindowsPlatforms** nuget package to 5.1.0, 
Here's the error I receive.


`Restoring packages for 'App3'.
Restoring packages for D:\project\Github\App3\App3\project.json...

Microsoft.NETCore.Portable.Compatibility 1.0.0 provides a compile-time reference assembly for mscorlib on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.

Some packages are not compatible with UAP,Version=v10.0 (win10-arm).

Microsoft.NETCore.Portable.Compatibility 1.0.0 provides a compile-time reference assembly for mscorlib on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.

Some packages are not compatible with UAP,Version=v10.0 (win10-x64).

Microsoft.NETCore.Portable.Compatibility 1.0.0 provides a compile-time reference assembly for mscorlib on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86.
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).

Package restore failed for 'App3'.

Package restore failed. 
Rolling back package changes for 'App3'.

========== Finished ==========`

**Comment by dimitrijevic** [comment]
This might be wrong now, but that package's latest prerelease, now works only on VS2017?
