### ISSUE TITLE
src/pal/tests/palsuite/exception_handling/pal_sxs/test1/exceptionsxs.cpp compile failure on ARM

### ISSUE THREAD

**Issue by benpye** [dotnet/coreclr#3526]
On ARM `__cdecl` is ignored. This has been added to the test `src/pal/tests/palsuite/exception_handling/pal_sxs/test1` in the commit 9f6654b . @mikem8361 is this required for the test to work on OS X and so should it be `__cdecl` in an `#ifdef` for OS X or should we have this as non `__cdecl` for just ARM?

**Comment by mikem8361** [comment]
Even though I added with my OSX exception changes, it is valid and runs on Linux.

The only __cdecl I see is the one on main() which all the other paltests have.  Are you change all the rest of the pal tests?

**Comment by benpye** [comment]
Ah woops. appears the actual issue is this test doesn't include palsuite.h . I believe we define `__cdecl` to be harmless on ARM normally.

**Comment by mikem8361** [comment]
I don’t remember exactly but I think the reason I didn’t include palsuite.h in exceptionsxs.cpp is because it includes platform specific h files directly.

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/3656
