### ISSUE TITLE
Make ReadyToRun images work with COMPlus_ZapRequire

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3527]
Loading ReadyToRun images fails when COMPlus_ZapRequire is set and the corresponding assembly is in COMPlus_ZapRequireList. The suggested fix is to add

```
#ifdef FEATURE_READYTORUN
   if(m_pFile->GetLoaded()->HasReadyToRunHeader())
        return;
#endif
```

to DomainFile::CheckZapRequired

**Comment by JohnChen0** [comment]
Fixed with PR #3536.
