### ISSUE TITLE
IL Tools: Create NuGet packages for IL tools ilasm.exe, ildasm.exe and possible new tools (ilsub.exe, iloptim.exe)

### ISSUE THREAD

**Issue by nietras** [dotnet/coreclr#3534]
`ilasm.exe` and `ildasm.exe` are already part of coreclr. However, there does not appear to be any NuGet packages for them. Since these sometimes are useful for scripting (build or similar) it would be great to have these as separate nugettable packages.

In fact, it would be great if there would be a whole family of IL tools e.g.:

`ilasm.exe`: (IL Assembler) generates a portable executable (PE) file from Common Intermediate Language (CIL) code.

`ildasm.exe`: (IL Disassembler) takes a portable executable (PE) file that contains intermediate language (IL) code and creates a text file suitable as input to `ilasm.exe`.

`ilsub.exe`: (IL Substituter) see https://github.com/dotnet/corefxlab/tree/master/src/System.Slices/tools/ILSub , a tool for substituting a method body with hand-written IL e.g. as in https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/PtrUtils.cs#L102:
```csharp
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        [ILSub(@"
            sizeof !!T
            ret")]
        public static int SizeOf<T>() { return default(int); }
```

`iloptim.exe`: (IL optimizer) basically my idea for a tool that can optimize/merge/inline IL to form an optimized basis for JIT scenarios. The CLR JIT is known to generate suboptimal code in the face of many inlined calls. That is, inlining is ok, but the code generated after inlining is not optimal. The tool would, thus, be somewhere inbetween native compilation and normal JIT. This tool could also be used to reduce size by doing simple obfuscation/reduction of type and method names, for example.

Why not use native compilation instead of `iloptim.exe`? Well in some cases distributing as IL is better/easier when targetting multiple platforms. This distribution could then be optimized like optimization is done for native compilation, but here IL is still the output.

**Comment by omariom** [comment]
:+1:  for ILSub. I am using it in my experiments with delegates.

**Comment by RussKeldorph** [comment]
I believe @kyulee1 is working on packaging ilasm and ildasm.

@nietras I recommend breaking this into two or three separate issues.  I make no prediction on the likelihood of ilsub and/or iloptim requests being addressed, but those requests are very different than the ilasm/ildasm one IMO.

**Comment by nietras** [comment]
@RussKeldorph I agree. I have split out `ilsub` https://github.com/dotnet/coreclr/issues/3579 and `iloptim` https://github.com/dotnet/coreclr/issues/3580 and created a separate issue for nuget packages for https://github.com/dotnet/coreclr/issues/3581.
