### ISSUE TITLE
CharUnicodeInfo.GetUnicodeCategory classifies U+2028 as Format

### ISSUE THREAD

**Issue by gafter** [dotnet/coreclr#3542]
`'\u2028'` (aka LINE SEPARATOR) should be classified by `CharUnicodeInfo.GetUnicodeCategory` as
`UnicodeCategory.LineSeparator` but is incorrectly categorized as `UnicodeCategory.Format`.

See http://www.fileformat.info/info/unicode/char/2028/index.htm

This is the root cause of the Roslyn compiler bug https://github.com/dotnet/roslyn/issues/9484

**Comment by tarekgh** [comment]
I'll take a look

**Comment by tarekgh** [comment]
@gafter I cannot repro this issue. doing 

        UnicodeCategory uc = CharUnicodeInfo.GetUnicodeCategory('\u2028');
        Console.WriteLine(uc);    

producing "LineSeparator"

**Comment by gafter** [comment]
I think I was just wrong. Sorry.
