### ISSUE TITLE
Is remote debug/deploy from Visual Studio a planned feature for release?

### ISSUE THREAD

**Issue by OtherCrashOverride** [dotnet/coreclr#3544]
Over the course of this project I have continued to ask about debugging.  There has never been a confirmation or denial of it.  So this is as explicitly as I can think of to ask the question.

**Comment by noahfalk** [comment]
Not sure if you saw the \\build presentation last spring, but yes the Visual studio guys are working in this area. Last I heard remote debugging will probably show up in the RC release of VS, not as certain if that release will cover remote deployment as well. 

Separate from VS but potentially also interesting to you, there was an announcement earlier today about a pre-release version of VSCode that supports debugging .Net Core/CLI:
https://blogs.msdn.microsoft.com/visualstudioalm/2016/03/10/experimental-net-core-debugging-in-vs-code/

HTH,
 -Noah

**Comment by OtherCrashOverride** [comment]
Now that this year's BUILD event is over with, is there any status update for this?  There was talk of remote debug, but I did not see any actual "here is how you do it" information.  Particularly dismaying is that it appears I need to install Java, the Android SDK, and the Android NDK to remote debug a Linux session that is not running any of those things.  Ironically, if i was actually using Java and Android, the non Visual Studio IDEs already support remote debug/deploy for it.

Although I am capable of using command line debuggers, in the year 2016 I should not have to.

**Comment by noahfalk** [comment]
@gregg-miskelly any additional info beyond what is already called out here? (Gregg works on the VS debugger team)

**Comment by gregg-miskelly** [comment]
Now that VS 2015 Update 2 is out, the required bits on the VS side have shipped. So we just need to put together some instructions on how to set things up (in an off-road way). We should be able to put these together soon. Hopefully in the next week or so.

**Comment by gregg-miskelly** [comment]
I posted off road VS instructions: https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio

Let me know if you have troubles. Thanks!
Gregg

**Comment by OtherCrashOverride** [comment]
Thanks for this information.  As an interim solution, it may satisfy the "letter" of the request, but it certainly circumvents the "spirit" of it.

Many developers have "locked down" environments where installing a gigabyte or more of dependencies (java, android sdk, android emulator) is simply not possible for anything other than test systems.  As these items are not even used for remote debugging, they should not be a required dependency.

Those like myself that use full Visual Studio, rather than VS Code or a simple text editor, do so because it offers a GUI that speeds and simplifies non-coding related tasks.  Particularly, the code/run/debug cycle productivity is impeded by the manual nature of the provided solution.

I personally expected remote debugging to be as simple as "hit F5" after filling some settings in a full featured GUI dialog box.  I have done this with Monodevelop and a custom plugin via SSH in the past.  Therefore, I am aware of the technical aspects involved and do not believe it is beyond the capabilities of Visual Studio.

**Comment by gregg-miskelly** [comment]
I don't disagree. We aren't where we want to be on this stuff yet.

BTW: You don't need the Android SDK, Java, etc.

**Comment by sayedihashimi** [comment]
@OtherCrashOverride are you asking specifically for Remote Debugging a .NET Core app on ***Linux***? Or are you also asking about Windows/Azure?

For windows in VS you can use the `Attach To Process` menu option to start a remote debugging session. For Azure you can start remote debugging in the server explorer. We have a bug in RC1 where we don't attach to the correct process for dnx/dotnet apps. I'm hoping that issue will be resolved in RC2 and if not by RTW for sure. In the mean time you can use the Attach To Process dialog to start remote debugging for dnx/dotnet apps in Azure (_also works on your own server as I mentioned previously_) https://azure.microsoft.com/en-us/blog/introduction-to-remote-debugging-on-azure-web-sites/.

If you're asking specifically about Remote Debugging a .NET Core app running on a Linux machine. We are very interested in enabling this scenario. First, I'd like to get this on par with the experience we have today for Windows, and then later perhaps look to improve all of them. Similar to a one click `Build->Deploy->Attach`. The reason why it's not on par today is not from a lack of interest. We've been developing tools for Windows for about two decades. We are now just getting started with Linux. It will take us some time to get there. One of the big gaps was a the Linux debugging support. We now have that. Another significant gap in the lack of support for [publishing a .NET Core project to a Linux box](https://github.com/aspnet/Tooling/issues/98). I've been wanting to get the team to get started with that item but we've been focused on more fundamental issues.

Right now we are focused on getting RC2 out the door, so I can't make any promises. I'll be meeting with people over the course of the next week or so to get more info here.

FYI we have a related thread at https://github.com/aspnet/Tooling/issues/416.

**Comment by OtherCrashOverride** [comment]
@sayedihashimi 
The case I am interested is the latter: deploy/debug CoreCLR running on Linux in a non-Azure environment from an independent Windows Visual Studio development machine.

The conciseness of your reply is greatly appreciated.  I look forward to future progress in this area.

**Comment by Meai1** [comment]
Hi, I have a problem. The offroad debugging instructions work but only if I compile the dotnet app on linux. Both .net core versions (linx+windows) are identical, shouldn't it be possible to build on windows and still have it attach/debug fine on linux?

Here is the error I'm getting: 
![capture](https://cloud.githubusercontent.com/assets/1112157/16684204/1d87ef8a-4504-11e6-99d1-d496074a8cd0.PNG)

**Comment by gregg-miskelly** [comment]
@Meai1 Yes, you can build your app on Windows. The three possibilities that I can think of for what is going wrong are --

1. You app is somehow binding to the RC2 version of the runtime when using the Windows-built version. I believe you could add a bit of code to your app to use reflection to output the assembly containing the definition for object -- `Console.WriteLine(typeof(object).GetTypeInfo().Assembly.FullName)`. If you get System.Private.CoreLib then you are indeed running on an RTM runtime.
2. You are launching the app incorrectly -- this error just implies that the process that we started never started the CoreCLR (or it is an old version that didn't raise the CLR started event). I don't know how this could be connected with building on Windows vs. Linux, but if you wind up telling the debugger to spawn some parent process which only launches the app as a child process then debugging will not work and you will see this problem. You could try dumping out the process id of the current process to confirm or deny this theory -- `Console.WriteLine(System.Diagnostics.Process.GetCurrentProcess().Id)`
3. The app itself is falling over trying to initialize. Perhaps because it can't find the right dependencies to start the CoreCLR.

**Comment by Meai1** [comment]
@gregg-miskelly : I don't think any of those are true. I debugged into the dotnet cli project and it appears that at some point there is a cached .SDKVersion being written into some temporary build output and that .SDKVersion file contains an OS string (e.g: win10-x64), which will then on 'dotnet run' make the comparison for "is this already built with the same .netcore" on startup return false.
It doesn't make sense to me why such a string is written out but I assume it was or still is necessary for the .netcore devs to know what OS built an app.

**Comment by gregg-miskelly** [comment]
@Meai1 are you saying that if you run the Windows-built version that it doesn't start (3 from above)?

If so -- you should certainly be able to do a 'dotnet publish' and copy the output from the command and use it. I would have thought for a simple app you could skip this step and just directly copy over files from the 'bin' folder. But I could be wrong. We can ask a .NET CLI person if this is what you are asking about.

**Comment by Meai1** [comment]
Yes, I guess (3) does fit but I dont see how it has anything to do with dependencies, I mean maybe. I dont know how I can debug a failing .netcore app start. 
Using the VisualStudio command results in the error in the screen = the app doesn't start on Linux.
Running "dotnet run" on Linux makes the app recompile first before it starts.

I use shared vmware folders, so I don't copy anything manually I just directly use the same folders at all times both on Windows and Linux.
