### ISSUE TITLE
Stack Limit Assertion Failure (ARM/Linux/Debug)

### ISSUE THREAD

**Issue by myungjoo** [dotnet/coreclr#3546]
I'm having the following issue in ARM/Linux/Debug (b440fdf5e0ed03e511a9adcb9196ce324ab2e09a)
with the HelloWorld.cs from linux-instruction.md

```
sh-3.2# ./corerun HelloWorld.exe linux
Hello, Linux...

Assert failure(PID 6651 [0x000019fb], Thread: 6651 [0x19fb]): newSP >= m_crawl.pThread->GetCachedStackLimit()
    File: /home/abuild/rpmbuild/BUILD/coreclr-0.0.1/src/vm/stackwalk.cpp Line: 2557
    Image: /sdcard/CC/alldll/corerun

**** MessageBox invoked, title 'corerun - Assert Failure (PID 6651, Thread 6651/0x19fb)' ****
  newSP >= m_crawl.pThread->GetCachedStackLimit()

/home/abuild/rpmbuild/BUILD/coreclr-0.0.1/src/vm/stackwalk.cpp, Line: 2557

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
/sdcard/CC/alldll/corerun

********

Aborted
sh-3.2#
```

The failure is caused by the managed stack frame SP goes beyond StackLimit; however,
in the context of Thread::StackWalkFramesEx() in src/vm/stackwalk.cpp, other managed frames seem to be less than StackLimit (0xbe800000 and 0xb1cff000, measured once at the start).

Before digging deeper, I want to know:

**Is it correct to depend on pthread_attr_getstack() executed while corerun is being initialized for MANAGED STACKS? ** pthread_attr_getstack() is used to determine if the stack of managed code is in the range (which fails in runtime of ARM/Linux during GC)

I'm still not well aware of the mechanism of managed code; however, I imagine that the managed stacks may have different ranges in their stack pointers. We cannot track into managed stacks from native stacks with native debuggers or unwind tools. 

Getting the answer of the question above will give me a lot of hints. Thank you in advance.

(tracking more in detail at https://github.com/myungjoo/coreclr/issues/2 )

**Comment by janvorli** [comment]
@myungjoo There is no distinction between managed and native stack - there is just one stack per thread, containing intermixed native and managed frames.
It seems that there might be a problem with the value reported by the pthread_addr_getstack on ARM. On x64, the stack limit (which is the lowest allowed stack address) never moves below the initially reported one. It only moves up when OS needs more virtual memory and it needs to recover some from the original range of the stack. If the limit can move down at runtime on ARM, then it is a trouble that we will need to solve.

**Comment by myungjoo** [comment]
@janvorlli Thank you.

The current preposition of the error is coming from the incorrect operations between iter.Init() to iter.Next() in Thread::StackWalkFrameEx(), which gives incorrect SP values for managed stack. (detail at https://github.com/myungjoo/coreclr/issues/2 )

I may be able to return to this issue many days later. :(
( @leemgs @mylibero @prajwal-aithal If any of you make a significant progress on the current task or have some time between build/test iterations, you may jump into this one.)

**Comment by leemgs** [comment]
Here is my test result on my test board.  The result of "Helloworld" is ok on my test environment. 
Refer to #Issue https://github.com/dotnet/coreclr/issues/3784

**Comment by myungjoo** [comment]
This error no more appears with recent commits.
