### ISSUE TITLE
RyuJIT x86: Code generation/encoding issue for ckfinite

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#3549]
These tests generate the following assert:
Assert failure(PID 128 [0x00000080], Thread: 11276 [0x2c0c]): Assertion failed 'size <= EA_PTRSIZE || IsSSEOrAVXInstruction(ins)'
File: d:\git\coreclr\src\jit\emitxarch.cpp Line: 3371

It is generating a mov from fp to int register, but is assuming that it can move a double to a long this way.

JIT\IL_Conformance\Old\Conformance_Base\sub_r8\sub_r8.cmd
in '_sub:checkfinite(double):int' (IL size 127)
JIT\IL_Conformance\Old\Conformance_Base\ckfinite_r8\ckfinite_r8.cmd
in '_ckfinite:r8(double):int' (IL size 62)
JIT\Regression\VS-ia64-JIT\M00\b108366\b108366\b108366.cmd
in '_div:checkfinite(double):int' (IL size 129)
JIT\IL_Conformance\Old\Conformance_Base\add_r8\add_r8.cmd
in '_add:checkfinite(double):int' (IL size 127)
JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b323557\b323557-ret\b323557-ret.cmd
in 'FullProof:Test():int' (IL size 77)
JIT\IL_Conformance\Old\Conformance_Base\rem_r8\rem_r8.cmd
in '_rem:checkfinite(double):int' (IL size 122)
JIT\IL_Conformance\Old\Conformance_Base\div_r8\div_r8.cmd
in '_div:checkfinite(double):int' (IL size 129)
JIT\IL_Conformance\Old\Conformance_Base\ldc_ckfinite_r8\ldc_ckfinite_r8.cmd
in '_ckfinite:r8_0(double):int' (IL size 72)
JIT\IL_Conformance\Old\Conformance_Base\neg_r8\neg_r8.cmd
in '_neg:checkfinite(double):int' (IL size 127)
JIT\IL_Conformance\Old\Base\ckfinite\ckfinite.cmd
in '_ckfinite:_ckfinite(double):int' (IL size 29)
JIT\IL_Conformance\Old\Conformance_Base\mul_r8\mul_r8.cmd
in '_mul:checkfinite(double):int' (IL size 127)

**Comment by BruceForstall** [comment]
Also:
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b59948\b59948\b59948.cmd
in 'ILGEN_0xa20b8571:Method_0x15903b4b(byte,double,long,ubyte):int' (IL size 284)
