### ISSUE TITLE
SIGABRT_libcoreclr.so!Thread::VirtualUnwindToFirstManagedCallFrame

### ISSUE THREAD

**Issue by schaabs** [dotnet/coreclr#3550]
This appears to be a failure where we are handling a native exception and trying to create a managed exception out of it (Presumably a heap corruption which results in a segsiv we are trying to turn into a null reference exception, but I haven't verified this).  However in this case there are no managed frames to dispatch the exception to so we end up crashing in **VirtualUnwindToFirstManagedCallFrame**.  This makes it so the context of the original native exception is not preserved.

libc.so.6!gsignal
libc.so.6!abort
libcoreclr.so!PROCEndProcess
libcoreclr.so!SafeExitProcess
libcoreclr.so!EEPolicy::HandleFatalError
**libcoreclr.so!Thread::VirtualUnwindToFirstManagedCallFrame**
libcoreclr.so!DispatchManagedException
libcoreclr.so!PreStubWorker
libcoreclr.so!ThePreStub
libcoreclr.so!FastCallFinalizeWorker
libcoreclr.so!MethodTable::CallFinalizer
libcoreclr.so!MethodTable::CallFinalizer
libcoreclr.so!FinalizerThread::DoOneFinalization
libcoreclr.so!FinalizerThread::DoOneFinalization
libcoreclr.so!FinalizerThread::FinalizeAllObjects
libcoreclr.so!FinalizerThread::FinalizerThreadWorker
libcoreclr.so!ManagedThreadBase_DispatchOuter
libcoreclr.so!ManagedThreadBase_DispatchOuter
libcoreclr.so!ManagedThreadBase_DispatchOuter
libcoreclr.so!ManagedThreadBase_DispatchOuter
libcoreclr.so!ManagedThreadBase_DispatchOuter
libcoreclr.so!ManagedThreadBase::FinalizerBase
libcoreclr.so!ManagedThreadBase::FinalizerBase
libcoreclr.so!FinalizerThread::FinalizerThreadStart
libcoreclr.so!CorUnix::CPalThread::ThreadEntry
libpthread.so.0!start_thread
libc.so.6!clone

The following dumps are available for this failure:
[projectk-23902-00-amd64chk_00B9](https://dotnetjobresults.blob.core.windows.net/projectk-23902-00-stress/b8d84231-bfa0-4adc-a66a-a29ba9fff8db/stress/generated/09_01hr/projectk-23902-00-amd64chk_00B9/projectk-23902-00-amd64chk_00B9.csproj/projectk-23902-00-amd64chk_00B9.zip?sv=2015-04-05&sr=c&sig=6KxVqZbsAaAIyiRvWzyl0J%2FHK6%2FEVaQyb%2BqJDtORajg%3D&se=2017-03-04T03:45:11Z&sp=rw)
[projectk-23902-00-amd64ret_00DD](https://dotnetjobresults.blob.core.windows.net/projectk-23902-00-stress/b8d84231-bfa0-4adc-a66a-a29ba9fff8db/stress/generated/09_01hr/projectk-23902-00-amd64chk_00EE/projectk-23902-00-amd64chk_00EE.csproj/projectk-23902-00-amd64chk_00EE.zip?sv=2015-04-05&sr=c&sig=6KxVqZbsAaAIyiRvWzyl0J%2FHK6%2FEVaQyb%2BqJDtORajg%3D&se=2017-03-04T03:45:11Z&sp=rw)
[projectk-23902-00-amd64ret_005A](https://dotnetjobresults.blob.core.windows.net/projectk-23902-00-stress/205a2398-dc2e-44be-9125-57ca41f21391/stress/generated/07_02hr/projectk-23902-00-amd64ret_005A/projectk-23902-00-amd64ret_005A.csproj/projectk-23902-00-amd64ret_005A.zip?sv=2015-04-05&sr=c&sig=6KxVqZbsAaAIyiRvWzyl0J%2FHK6%2FEVaQyb%2BqJDtORajg%3D&se=2017-03-04T03:45:11Z&sp=rw)

**Comment by janvorli** [comment]
Reassigning that to myself. I think I know what's wrong.

**Comment by janvorli** [comment]
Fixed by #3588
