### ISSUE TITLE
RyuJit x86: Assert with spilled double return value

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#3551]
The following tests get this assert:
Assert failure(PID 2288 [0x000008f0], Thread: 2952 [0x0b88]): Assertion failed 'temp != nullptr'
File: d:\git\coreclr\src\jit\regset.cpp Line: 3098

It appears to be the case that the return is marked as spilled, though from a quick look at the first test case, it doesn't seem that it is being spilled by the register allocator.

JIT\Methodical\NaN\r8nanconv_il_r\r8nanconv_il_r.cmd
in 'ConvTest:test13():float' (IL size 27)
JIT\Methodical\NaN\r8nanconv_il_d\r8nanconv_il_d.cmd
in 'ConvTest:test13():float' (IL size 27)
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b37238\b37238\b37238.cmd
in 'ILGEN_0x7fee1ca2:Method_0x54eb(long,short,int,char,byte,short,byte):float' (IL size 84)
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b80043\b80043\b80043.cmd
in 'ILGEN_0x7a14cd08:Method_0xe36037f1(char,int,short,float,float):double' (IL size 48)
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b71999\b71999\b71999.cmd
in 'ILGEN_0xaca96c86:Method_0x88567f92(int,float):double' (IL size 15)
JIT\Methodical\flowgraph\dev10_bug679053\cpblkInt32\cpblkInt32.cmd
in 'ILGEN_0xb8816d7d:Method_0xac55c91a(float,short,short,char,ubyte,char):float' (IL size 375)

**Comment by BruceForstall** [comment]
These are currently passing (with NYI)
