### ISSUE TITLE
RyuJIT x86: Reg pointer tracking bug

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#3554]
The following tests get this assert:
Assert failure(PID 120 [0x00000078], Thread: 5580 [0x15cc]): Assertion failed 'nonVarPtrRegs == 0'
File: d:\git\coreclr\src\jit\codegenxarch.cpp Line: 700

managed\Compilation\Compilation\Compilation.cmd
in 'Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol:GetDeclaredBaseType(ref):ref:this' (IL size 43)
JIT\Methodical\stringintern\test1-xassem\test1-xassem.cmd
in 'Test1:TestSameObjRef():bool' (IL size 417)
JIT\Methodical\stringintern\_XModuletest1-xmod\_XModuletest1-xmod.cmd
in 'Test1:TestSameObjRef():bool' (IL size 417)
JIT\Methodical\stringintern\_XAssemblytest1-xassem\_XAssemblytest1-xassem.cmd
in 'Test1:TestSameObjRef():bool' (IL size 417)
JIT\Methodical\stringintern\_Simpletest1\_Simpletest1.cmd
in 'Test1:TestSameObjRef():bool' (IL size 417)
JIT\Performance\CodeQuality\Roslyn\CscBench\CscBench.cmd
in 'Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol:GetDeclaredBaseType(ref):ref:this' (IL size 43)

Note that there seem to be only two distinct methods in the above tests.
This assert usually indicates that the code generator has marked a register as containing a pointer, and then failed to clear it when its last use has been issued.

**Comment by BruceForstall** [comment]
I currently see this failing in:

JIT\Methodical\stringintern\_Simpletest1\_Simpletest1.cmd
JIT\Methodical\stringintern\_XAssemblytest1-xassem\_XAssemblytest1-xassem.cmd
JIT\Methodical\stringintern\_XModuletest1-xmod\_XModuletest1-xmod.cmd
JIT\Methodical\stringintern\test1-xassem\test1-xassem.cmd

**Comment by BruceForstall** [comment]
In Checked only,
JIT\Performance\CodeQuality\V8\DeltaBlue\DeltaBlue\DeltaBlue.cmd
