### ISSUE TITLE
x86: long/int mismatch in importer

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#3557]
The following tests get this assert in the importer, both with the "frankenjit" as well as RyuJIT:

Assert failure(PID 6824 [0x00001aa8], Thread: 13280 [0x33e0]): Assertion failed 'genActualType(op1->TypeGet()) == genActualType(op2->TypeGet()) || varTypeIsI(op1->TypeGet()) && varTypeIsI(op2->TypeGet()) || varTypeIsFloating(op1->gtType) && varTypeIsFloating(op2->gtType) : Possibly bad IL with CEE_ceq at offset 0100h (op1=long op2=int stkDepth=0)'
File: d:\git\coreclr\src\jit\importer.cpp Line: 10323

JIT\Methodical\ELEMENT_TYPE_IU\_il_dbgi_array_merge\_il_dbgi_array_merge.cmd
in 'Test:Main():int' (IL size 287)
JIT\Methodical\ELEMENT_TYPE_IU\_il_reli_array_merge\_il_reli_array_merge.cmd
in 'Test:Main():int' (IL size 287)
JIT\Methodical\ELEMENT_TYPE_IU\_il_relu_array_merge\_il_relu_array_merge.cmd
in 'Test:Main():int' (IL size 287)
JIT\Methodical\ELEMENT_TYPE_IU\_il_dbgu_array_merge\_il_dbgu_array_merge.cmd
in 'Test:Main():int' (IL size 287)

**Comment by BruceForstall** [comment]
This no longer repros for either x86 or RyuJIT/x86.
