### ISSUE TITLE
RyuJIT x86: Tree order assert after Lowering decomposition of longs

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#3560]
The following tests get this assert:
Assert failure(PID 11860 [0x00002e54], Thread: 2936 [0x0b78]): Assertion failed 'treeNodeCount == linearNodeCount'
File: d:\git\coreclr\src\jit\flowgraph.cpp Line: 21052

JIT\Directed\refbyref\ref2byref_il_d\ref2byref_il_d.cmd
in '<Module>:Main():int' (IL size 206)
JIT\Directed\refbyref\ref2byref_il_r\ref2byref_il_r.cmd
in '<Module>:Main():int' (IL size 206)

This is a nested tree of binary operators, with embedded statements, which have presumably been threaded incorrectly after decomposing the nodes.

**Comment by BruceForstall** [comment]
This no longer repros.
