### ISSUE TITLE
IntPtrGetHashCode test failing

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#3566]
EGIN EXECUTION
 "E:\git\coreclr\tests\..\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\corerun.exe" IntPtrGetHashCode.exe  
Beginning test case IntPtr.GetHashCode() at 3/7/2016 5:15:53 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

[Positive]
ERROR!!!-002: expect IntPtr.GetHashCode() equals the address

Ending test case at 3/7/2016 5:15:54 PM
FAIL
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1

@vcsjones can you take a look?
I beleive this was originally introduced in https://github.com/dotnet/coreclr/pull/3511/files and https://github.com/dotnet/coreclr/pull/3538

**Comment by ramarag** [comment]
The Ci report can be seen here:
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1_prtest/1/testReport/CoreMangLib/_cti_system_intptr_IntPtrGetHashCode_IntPtrGetHashCode_/_cti_system_intptr_IntPtrGetHashCode_IntPtrGetHashCode_cmd/

**Comment by vcsjones** [comment]
This was brought up on the PR as well, https://github.com/dotnet/coreclr/pull/3511. Thanks for making an issue.

**Comment by vcsjones** [comment]
@ramarag I do not see the failure for the UIntPtr case that you included in the issue. It appears to be passing in CI, or am I looking in the wrong place? http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1_prtest/1/testReport/CoreMangLib/_cti_system_uintptr_UIntPtrGetHashCode_UIntPtrGetHashCode_/

**Comment by ramarag** [comment]
my bad, my local test build was out of date only IntPtr version is problematic
