### ISSUE TITLE
RyuJIT x86: Liveness assert for upper part of long

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#3569]
Assert failure(PID 16116 [0x00003ef4], Thread: 15408 [0x3c30]): Assertion failed 'VarSetOps::Equal(this, VarSetOps::Intersection(this, life, block->bbLiveIn), life)'
File: d:\git\coreclr\src\jit\liveness.cpp Line: 2820

This is in the following test:
JIT\Regression\Dev11\dev10_94677\loopvt\loopvt.cmd
in 'DblArray3:f4(ref,int)' (IL size 88)

It appears that V13 (T11) has a definition that is not marked GTF_VAR_DEF

**Comment by BruceForstall** [comment]
This now passes, probably due to NYI.
