### ISSUE TITLE
IL Tools: Create new `iloptim` tool and create nuget package

### ISSUE THREAD

**Issue by nietras** [dotnet/coreclr#3580]
`ilasm.exe` and `ildasm.exe` are already part of coreclr. However, an idea for a new tool is:

`iloptim.exe`: (IL optimizer) basically my idea for a tool that can optimize/merge/inline IL to form an optimized basis for JIT scenarios. 

The tool would, thus, be somewhere inbetween native compilation and normal JIT. This tool could also be used to reduce size by doing simple obfuscation/reduction of type and method names, for example.

Why not use native compilation instead of `iloptim.exe`? Well in some cases distributing as IL is better/easier when targetting multiple platforms. This distribution could then be optimized like optimization is done for native compilation, but here IL is still the output.

This request has been split out from https://github.com/dotnet/coreclr/issues/3534

**Comment by jkotas** [comment]
It would be more appropriate for this tool to live in its own repo.

**Comment by RussKeldorph** [comment]
@erozenfeld @swaroop-sridhar @sbomer Would https://github.com/mono/linker fit this description, or at least aspire to do so?

**Comment by swaroop-sridhar** [comment]
Yes ILLinker is an IL-IL optimization for code-size reduction. But there are other optimizations possible for (ex inline) which may be implemented as plugins to ILLinker or as separate tools. There are also frameworks like [Fody](https://github.com/Fody/Fody) for custom IL transformations.

I'm not sure ILoptim should be one tool. But I agree with @jkotas  that they should live in their own repositories.
