### ISSUE TITLE
IL Tools: Create NuGet packages for IL tools ilasm.exe, ildasm.exe

### ISSUE THREAD

**Issue by nietras** [dotnet/coreclr#3581]
`ilasm.exe` and `ildasm.exe` are already part of coreclr. However, there does not appear to be any NuGet packages for them. Since these sometimes are useful for scripting (build or similar) it would be great to have these as separate nugettable packages.

This issue originates from https://github.com/dotnet/coreclr/issues/3534

**Comment by jkotas** [comment]
cc @kyulee1 @mellinoe

**Comment by jamesqo** [comment]
Agreed, I think this would be a great idea since as of right now there's no way to use ilasm/dasm on Unix without 1) building the repo or 2) resorting to Mono. This would allow .NET Core-based projects to use IL code and be able to build on non-Windows platforms.

**Comment by agocke** [comment]
This is a bit of a blocker for Roslyn running some its unit tests cross platform -- we currently have a large number of tests which use ilasm to construct assemblies which aren't expressible in C#. On Windows we just grab the ilasm out of the framework, but that's not possible on other platforms. Could we get an accelerated milestone for this package?

cc @gkhanna79

**Comment by gkhanna79** [comment]
ILAsm and ILDasm is already published in its own packages. Does that not help? 

CC @RussKeldorph

**Comment by agocke** [comment]
@gkhanna79 That totally works! Can you point me to the packages? This issue seemed to indicate there was nowhere to get these tools except by building the repo.

**Comment by gkhanna79** [comment]
See https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.ILAsm and https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.ILDAsm (the corresponding runtime.* packages are on the same feed as well).

**Comment by RussKeldorph** [comment]
Looks like this got lost when it was moved to Future w/o assigning an area.  #5172 seems to be a duplicate.

**Comment by nietras** [comment]
Great, can these be run with `dotnet run` and thus without corresponding runtime?

**Comment by gkhanna79** [comment]
I believe you should be able to run them independently - @RussKeldorph can confirm though.

**Comment by jkotas** [comment]
ilasm/ildasm depend on CoreCLR.dll/so

**Comment by RussKeldorph** [comment]
AFAIK they are 100% native code with no dependency on .NET.  Might be nice to have managed versions akin to Roslyn, but I suspect that's pretty far down the priority list.

**Comment by RussKeldorph** [comment]
Oops, I defer to jkotas. :)
