### ISSUE TITLE
Arm64 Build Failure

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3582]
@mmitche I see the following error in latest commit from @kyulee1 (http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/arm64_cross_release_windows_nt/486/console):

06:35:01 Connection failed
06:35:02 Traceback (most recent call last):
06:35:02   File "C:\users\dotnet-bot\arm64\parser.py", line 5, in <module>
06:35:02     with open(sys.argv[1]) as file_handle:
06:35:02 IOError: [Errno 2] No such file or directory: 'output.xml'
06:35:02 Build step 'Execute Windows batch command' marked build as failure

The repo built fine but the abovve resulted in build marked as failed. Do you know why?

**Comment by mmitche** [comment]
@jashook Looks like your stuff.

**Comment by jashook** [comment]
Reset the system, testing to make sure it is functioning correctly. Looks like the connection dropped between the arm64 machines for some reason. Will investigate further.

**Comment by gkhanna79** [comment]
@jashook any update on this?

**Comment by jashook** [comment]
I have not been able to recreate this problem. It occurred because the arm64 machine was unable to be connected to for a period of time. I am still trying to recreate how this actually happened to let this fail more gracefully next time.

I am going to keep it open for now and assign it to myself.

**Comment by jashook** [comment]
Fixed with Kyungwoo's CI changes.
