### ISSUE TITLE
Assertion failed 'inlIsPrejitRoot' in 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol:AddNonTypeMembers(ref,struct,ref):this' (IL size 1484)

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#3586]
Assertion failed 'inlIsPrejitRoot' in 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol:AddNonTypeMembers(ref,struct,ref):this' (IL size 1484)

Examples:
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_checked_windows_nt_jitstress2_jitstressregs2/21/testReport/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_checked_windows_nt_jitstress2_jitstressregs0x80/19/testReport/

Specifically CscBench and Compilation failures.

**Comment by AndyAyersMS** [comment]
The inliner may see repeated `CALLSITE_TOO_MANY_LOCALS` observations while in a failing state. The observation comes from `lvaGrabTemp`, which has no mechanism for propagating inlining failure upwards.

The fix is to tolerate repeated instances of this observation.
