### ISSUE TITLE
ICastable test failure on non-windows

### ISSUE THREAD

**Issue by tijoytom** [dotnet/coreclr#3593]
ICastable  tests seem to fail on non-windows platform , ICastable is important for cross platform interop scenarios. This could well be a test issue.

**Comment by tijoytom** [comment]
Moving from rc2 since ICastable now used by couple of teams using Com API interop and they haven't reported any issue. Likely a test issue.

**Comment by yizhang82** [comment]
The test is using user32.dll...
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'user32.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Program.NativeMethods.EnumWindows(IntPtr enumProc, IntPtr lParam)
   at TestNativeCallable()
   at Program.TestNativeCallableValid()
   at Program.Main()

**Comment by yizhang82** [comment]
@tijoytom Which platform are you seeing the failure? It's working on Mac:

Yis-MacBook-Pro:Castable yizhang$ ../../../../coreclr/bin/Product/OSX.x64.Debug/corerun Castable.exe
IsInstanceOfInterface has been called for type IRetThis
IsInstanceOfInterface has been called for type IUnimplemented
IsInstanceOfInterface has been called for type IRetThis
IsInstanceOfInterface has been called for type IUnimplemented
IsInstanceOfInterface has been called for type IRetThis
GetImplType has been called for type IRetThis
RetThis has been called.
GetImplType has been called for type IRetThis
GetMyType has been called. My type is Castable
IsInstanceOfInterface has been called for type IUnimplemented
IsInstanceOfInterface has been called for type IUnimplemented
IsInstanceOfInterface has been called for type IRetArg`1[System.String]
GetImplType has been called for type IRetArg`1[System.String]
ReturnArg has been called.
IsInstanceOfInterface has been called for type IRetArg`1[System.Int32]
GetImplType has been called for type IRetArg`1[System.Int32]
Generic ReturnArg has been called. My type is Castable
InnocentMethod has been called. My type is Castable
IsInstanceOfInterface has been called for type IUnimplemented
IsInstanceOfInterface has been called for type IRetThis
IsInstanceOfInterface has been called for type IRetThis
IsInstanceOfInterface has been called for type IRetThis
InnocentMethod has been called. My type is Castable
GetImplType has been called for type IRetThis
RetThis has been called.
Test PASSED!

**Comment by tijoytom** [comment]
@yizhang82 Someone had this test marked as failing in 'testfailingoutsidewindows.txt'  and that's why i create the bug.Guess you already removed it from exclusion list.

**Comment by tijoytom** [comment]
@yizhang82 I just tried it on Ubuntu 14.04 and it's fine there too..

**Comment by yizhang82** [comment]
yep. I've removed it from the exclusion txt and it's working.
