### ISSUE TITLE
RyuJIT x86: GC encoding expects EITHER lvRegister OR lvOnFrame

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#3597]
This assert:
Assert failure(PID 9500 [0x0000251c], Thread: 15184 [0x3b50]): Assertion failed 'varDsc->lvRefCnt == 0'
File: d:\git\coreclr\src\jit\gcencode.cpp Line: 1788

Is hit by this test:
JIT\Performance\CodeQuality\Serialization\Serialize\Serialize.cmd
in 'System.Xml.XmlUTF8NodeWriter:SetOutput(ref,bool,ref):this' (IL size 42)

This is happening in this code from `GCInfo::gcMakeRegPtrTable()`
```C++
/* Has this argument been enregistered? */
if  (varDsc->lvRegister)
{
    /* if a CEE_JMP has been used, then we need to report all the arguments
       even if they are enregistered, since we will be using this value
       in JMP call.  Note that this is subtle as we require that
       argument offsets are always fixed up properly even if lvRegister
       is set */
    if (!compiler->compJmpOpUsed)
        continue;
}
else
{
    if  (!varDsc->lvOnFrame)
    {
        /* If this non-enregistered pointer arg is never
         * used, we don't need to report it
         */
        assert(varDsc->lvRefCnt == 0);
        continue;
    }
```
The issue arises because with RyuJIT we only set `lvRegister` if a lclVar is in the SAME register throughout the method - but `lvOnFrame` may not be true if it has never been spilled (e.g. it may have multiple disjoint lifetimes that reside in different registers).

**Comment by adiaaida** [comment]
This seems to still fail for gcstress 0xC zapdisable tests:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_ryujit_checked_windows_nt_gcstress0xc_zapdisable/1/testReport/junit/JIT/_Generics_Exceptions_general_class_instance01_general_class_instance01_/_Generics_Exceptions_general_class_instance01_general_class_instance01_cmd/

**Comment by BruceForstall** [comment]
@adiaaida there's a problem with that test job: it's reporting the assert **at the line number it used to exist at**. The assert no longer is at that line number, due to my changes. So it hasn't picked up my change, but apparently did pick up the issues.targets that no longer excludes the test. How does that happen?

**Comment by adiaaida** [comment]
When was your change? This ran on Aug 28, 2016 7:30:58 PM

**Comment by BruceForstall** [comment]
Looks like yesterday: https://github.com/dotnet/coreclr/pull/6946

Had the job ever run before? It's asserting on lots of test cases that were never disabled.

**Comment by adiaaida** [comment]
It was one of the jitstress/gcstress jobs I enabled on Friday. That was the first time it was ever run.

**Comment by BruceForstall** [comment]
Ok, I'm going to re-close this issue. If it happens again, with the new source, we can re-open.
