### ISSUE TITLE
Implement RtlRestoreContext for Linux and OSX

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/coreclr#360]
This function is currently stubbed out in src\pal\src\debug\debug.cpp. It is required to make managed exception handling work on Linux and Mac.

**Comment by kangaroo** [comment]
@sergiy-k Whats the issue with the OS X side here?  It seems to be complete for the variants of CONTEXT restore flags that I can see?

**Comment by janvorli** [comment]
@kangaroo @sergiy-k From what I can see in the OSX code for the context setting (```CONTEXT_SetThreadContextOnPort```), it seems that we don't need to implement anything additional.

**Comment by kangaroo** [comment]
@janvorli I had the thought.  It seems complete.

**Comment by janvorli** [comment]
Implemented as #380
