### ISSUE TITLE
ReadyToRun: StackOverflow when crossgen-ing JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.exe

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3600]
Test: JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.exe

Repro steps:
Git commit hash: c89bf3f87b0d8df4865bd9b50ad8ef14c2655d39

E:\coreclr>rd /s/q E:\coreclr\bin\tests
E:\coreclr>build checked skiptests
E:\coreclr>tests\buildtest.cmd checked crossgen
E:\coreclr>tests\runtest.cmd checked

StackOverflow happens in
 	crossgen.exe!Compiler::fgDfsInvPostOrderHelper(BasicBlock * block, unsigned __int64 * & visited, unsigned int * count) Line 2424	C++

**Comment by LLITCHEV** [comment]
Known issue. @briansull is looking into it.

**Comment by gkhanna79** [comment]
Also fails on GCStress

**Comment by briansull** [comment]
We do not drop to MinOpts when running ngen or crossgen

**Comment by gkhanna79** [comment]
This is passing on Ubuntu - http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_ubuntu_pri1r2r_tst/lastCompletedBuild/testReport/JIT.jit64.opt.cse/

**Comment by cmckinsey** [comment]
Fixed with PR #3914
