### ISSUE TITLE
ReadyToRun: Assertion failed 'emitPrologIG == emitCurIG' when crossgen-ing Regressions\common\AboveStackLimit.exe

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3601]
Test: Regressions\common\AboveStackLimit.exe

Repro steps:
Git commit hash:  c89bf3f 

E:\coreclr>rd /s/q E:\coreclr\bin\tests
E:\coreclr>build checked skiptests
E:\coreclr>tests\buildtest.cmd checked crossgen
E:\coreclr>tests\runtest.cmd checked

Assert failure(PID 37332 [0x000091d4], Thread: 25980 [0x657c]): Assertion failed 'emitPrologIG == emitCurIG' in 'Test:Main():int' (IL size 48286)

            File: e:\coreclr\src\jit\emit.cpp Line: 1533
            Image: E:\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\crossgen.exe

**Comment by LLITCHEV** [comment]
It seems while crossgen-ing we exceed the funclet prolog instruction group size.
When jitting...
      G_M43043_IG406:        ; offs=032EA5H, funclet=00
*************** In genFuncletProlog()
IN5cca:        push     rbp
IN5ccb:        push     r15
IN5ccc:        push     r14
IN5ccd:        push     r13
IN5cce:        push     r12
IN5ccf:        push     rdi
IN5cd0:        push     rsi
IN5cd1:        push     rbx
IN5cd2:        xor      rbp, rbp
Marking regs modified: [rbp] ([rax rcx rdx rbx rsi rdi r8-r15] => [rax rcx rdx rbx rbp rsi rdi r8-r15])
IN5cd3:        test     rbp, qword ptr [rsp+rbp]
IN5cd4:        sub      rbp, 0x1000
IN5cd5:        cmp      rbp, -0xFD28
IN5cd6:        jge      -20
IN5cd7:        sub      rsp, 0xFD28
IN5cd8:        mov      rbp, qword ptr [rcx+FD18H]
IN5cd9:        mov      qword ptr [rsp+FD18H], rbp
IN5cda:        lea      rbp, [rbp+1F9E0H]
Removing modified regs: [rbp] ([rax rcx rdx rbx rbp rsi rdi r8-r15] => [rax rcx rdx rbx rsi rdi r8-r15])

When crossgen-ing...
      G_M43043_IG406:        ; offs=032E9FH, funclet=00
*************** In genFuncletProlog()
IN5cca:        push     rbp
IN5ccb:        push     r15
IN5ccc:        push     r14
IN5ccd:        push     r13
IN5cce:        push     r12
IN5ccf:        push     rdi
IN5cd0:        push     rsi
IN5cd1:        push     rbx
IN5cd2:        xor      rbp, rbp
Marking regs modified: [rbp] ([rax rcx rdx rbx rsi rdi r8-r15] => [rax rcx rdx rbx rbp rsi rdi r8-r15])

**Comment by gkhanna79** [comment]
This fails two tests (1 each in P0 and P1 Debug runs). @LLITCHEV should this be assigned to you?

**Comment by erozenfeld** [comment]
The assert fires when emitter::emitGetPrologOffsetEstimate() is called from CodeGen::genPrologPadForReJit() when generating prolog for a funclet. The difference between jit and crossgen cases is that in crossgen case CORJIT_FLG_PROF_REJIT_NOPS is set and in jit case it's not.
The assert checks that we are generating main function prolog but in this case we are generating a funclet prolog. We don't need to insert nops in funclet prolog for rejitting so we should detect that in CodeGen::genPrologPadForReJit() and return.

That said, in release we generate unnecessary nops in funclet prolog but everything works fine so this is not a correctness issue.

**Comment by RussKeldorph** [comment]
@erozenfeld Thanks for the help!

**Comment by LLITCHEV** [comment]
Fixed by PR #4045
