### ISSUE TITLE
ReadyToRun: StackOverflowException in JIT\Regression\JitBlue\devdiv_902271\DevDiv_902271\DevDiv_902271.exe

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3608]
Test:
JIT\Regression\JitBlue\devdiv_902271\DevDiv_902271\DevDiv_902271.exe

Repro steps:
Git commit hash:  c89bf3f  

E:\coreclr>rd /s/q E:\coreclr\bin\tests
E:\coreclr>build checked skiptests
E:\coreclr>tests\buildtest.cmd checked crossgen
E:\coreclr>tests\runtest.cmd checked

BEGIN EXECUTION
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image E:\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\Regression\JitBlue\devdiv_902271\DevDiv_902271\test.ni.exe generated successfully.
 "E:\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" DevDiv_902271.exe

Process is terminated due to StackOverflowException.
Expected: 100
Actual: 255
END EXECUTION - FAILED
FAILED

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/3674
