### ISSUE TITLE
ReadyToRun: StackOverflowException in JIT\jit64\regress\vsw\546707\sql_stress4\sql_stress4.exe

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3610]
Test:
 JIT\jit64\regress\vsw\546707\sql_stress4\sql_stress4.exe

Repro steps:
 Git commit hash:  c89bf3f  

E:\coreclr>rd /s/q E:\coreclr\bin\tests
E:\coreclr>build checked skiptests
E:\coreclr>tests\buildtest.cmd checked crossgen
E:\coreclr>tests\runtest.cmd checked

BEGIN EXECUTION
 "E:\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" sql_stress4.exe

Process is terminated due to StackOverflowException.
Expected: 100
Actual: 255
END EXECUTION - FAILED
FAILED

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/3674
