### ISSUE TITLE
ReadyToRun:4 test failures under JIT\Regression\CLR-x86-JIT with FF result

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3613]
Tests:
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b66226\b66226\b66226.exe
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b44204\b44204\b44204.exe
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b70994\b70994\b70994.exe
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b75944\b75944\b75944.exe

Repro steps:
 Git commit hash:  c89bf3f  

E:\coreclr>rd /s/q E:\coreclr\bin\tests
E:\coreclr>build checked skiptests
E:\coreclr>tests\buildtest.cmd checked crossgen
E:\coreclr>tests\runtest.cmd checked

Output for the first of these tests:

BEGIN EXECUTION
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image E:\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b66226\b66226\ILGEN_0x9b859686.ni.exe generated successfully.
 "E:\coreclr\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" b66226.exe  
Expected: 100
Actual: 255
END EXECUTION - FAILED
FAILED

**Comment by LLITCHEV** [comment]
This looks like a VM exception handler issue.
This happens only for
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b66226\b66226\b66226.exe
 JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b44204\b44204\b44204.exe

The other passed.
It fails on the ngened and non ngened executable with the following exception/stack trace.
**** MessageBox invoked, title 'CoreRun.exe - Assert Failure (PID 15880, Thread 10424/0x28b8)' ****
  Consistency check failed: AV in clr at this callstack:
------
CORECLR! CLRVectoredExceptionHandlerShim + 0x11C (0x00007ffc`d319e95c)
NTDLL! RtlRestoreContext + 0x182 (0x00007ffd`00a25ef2)
NTDLL! RtlRaiseException + 0xE33 (0x00007ffd`00a24713)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffd`00a6258a)
<no module>! <no symbol> + 0x0 (0x00000000`00000007)
<no module>! <no symbol> + 0x0 (0x00000001`00000000)
<no module>! <no symbol> + 0x0 (0x000000c9`45ee3780)
-----
.AV on tid=0x28b8 (10424), cxr=000000C945E2CDB0, exr=000000C945E2D2A0
FAILED: false

CORECLR! CHECK::Trigger + 0x2C4 (0x00007ffc`d2fcfcac)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x3A6 (0x00007ffc`d319e78e)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x71 (0x00007ffc`d319e1c9)
CORECLR! CLRVectoredExceptionHandler + 0x1C5 (0x00007ffc`d319e13d)
CORECLR! CLRVectoredExceptionHandlerShim + 0xBA (0x00007ffc`d319e8fa)
NTDLL! RtlRestoreContext + 0x182 (0x00007ffd`00a25ef2)
NTDLL! RtlRaiseException + 0xE33 (0x00007ffd`00a24713)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffd`00a6258a)
CORECLR! CLRVectoredExceptionHandlerShim + 0x11C (0x00007ffc`d319e95c)
NTDLL! RtlRestoreContext + 0x182 (0x00007ffd`00a25ef2)

d:\repos\coreclr\src\vm\excep.cpp, Line: 8141

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
D:\repos\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe

********

**Comment by jkotas** [comment]
Dup of https://github.com/dotnet/coreclr/issues/3604
