### ISSUE TITLE
ReadyToRun: JIT\Methodical\tailcall_v4\hijacking\hijacking.exe fails with 0x65 result 

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3619]
Test:
 JIT\Methodical\tailcall_v4\hijacking\hijacking.exe

Repro steps:
 Git commit hash:  c89bf3f  

E:\coreclr>rd /s/q E:\coreclr\bin\tests
E:\coreclr>build checked skiptests
E:\coreclr>tests\buildtest.cmd checked crossgen
E:\coreclr>tests\runtest.cmd checked

BEGIN EXECUTION
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image E:\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\Methodical\tailcall_v4\hijacking\hijacking.ni.exe generated successfully.
 "E:\coreclr\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" hijacking.exe  
Executed 361 GCs
Executed 4 tail calls before failing
Expected: 100
Actual: 101
END EXECUTION - FAILED

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/3674
