### ISSUE TITLE
About failure of "crossgen mscorlib.dll" command  on Linux/ARM32 board

### ISSUE THREAD

**Issue by leemgs** [dotnet/coreclr#3635]
Now, we can successfully get the `mscorlib.ni.dll` file from `mscorlib.dll` by running "`u14.04$> crossgen mscorlib.dll`" command on ubuntu x86 64bit PC. Anyone who tried to run "`arm32$> crossgen mscorlib.dll`" command on Linux/ARM32 board such as Raspberry Pi2 board and Linux/ARM emulator? In my case, I have been getting below error messages on my Linux/ARM reference board.

\cc @benpye , @jkotas , @kangaroo , @myungjoo 

```
root:/dotnet/runtime-debug-20160307.2> file ./crossgen 
./crossgen: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=e4575c5b6655e47e8b1e57d94bd1c68c991ccf24, not stripped
root:/dotnet/runtime-debug-20160307.2> 
root:/dotnet/runtime-debug-20160307.2> file ./mscorlib.dll 
./mscorlib.dll: PE32 executable (DLL) (console) ARMv7 Thumb Mono/.Net assembly, for MS Windows
root:/dotnet/runtime-debug-20160307.2> 

root:/dotnet/runtime-debug-20160307.2> time ./crossgen ./mscorlib.dll 
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.



Assert failure(PID 733 [0x000002dd], Thread: 733 [0x02dd]): id != 0
    File: /work/dotnet/arm-32/coreclr/src/vm/ecall.cpp Line: 547
    Image: /dotnet/runtime-debug-20160307.2/crossgen

Command terminated by signal 6
real	30m 57.46s
user	29m 59.49s
sys	0m 38.49s
root:/dotnet/runtime-debug-20160307.2> 
root:/dotnet/runtime-debug-20160307.2> 
root:/dotnet/runtime-debug-20160307.2> 

```

This error happens by incorrect Qcall implementation for Linux/ARM device as following: 

```
LPVOID ECall::GetQCallImpl(MethodDesc * pMD)
{
    CONTRACTL
    {
        THROWS;
        GC_TRIGGERS;
        MODE_ANY;
        PRECONDITION(pMD->IsNDirect());
    }
    CONTRACTL_END;

    DWORD id = ((NDirectMethodDesc *)pMD)->GetECallID();
    if (id == 0)
    {
        id = ECall::GetIDForMethod(pMD);
        _ASSERTE(id != 0);

        // Cache the id
        ((NDirectMethodDesc *)pMD)->SetECallID(id);
    }

    ECFunc * cur = FindECFuncForID(id);

#ifdef _DEBUG
    CONSISTENCY_CHECK_MSGF(cur != NULL, 
        ("%s::%s is not registered in ecall.cpp",
        pMD->m_pszDebugClassName, pMD->m_pszDebugMethodName));

    CONSISTENCY_CHECK_MSGF(cur->IsQCall(), 
        ("%s::%s is not registered using QCFuncElement macro in ecall.cpp",
        pMD->m_pszDebugClassName, pMD->m_pszDebugMethodName));

    CONSISTENCY_CHECK_MSGF(pMD->HasSuppressUnmanagedCodeAccessAttr(),       
        ("%s::%s is not marked with SuppressUnmanagedCodeSecurityAttribute()", 
        pMD->m_pszDebugClassName, pMD->m_pszDebugMethodName));

    DWORD dwAttrs = pMD->GetAttrs();
    BOOL fPublicOrProtected = IsMdPublic(dwAttrs) || IsMdFamily(dwAttrs) || IsMdFamORAssem(dwAttrs);

    // SuppressUnmanagedCodeSecurityAttribute on QCalls suppresses a full demand, but there's still a link demand 
    // for unmanaged code permission. All QCalls should be private or internal and wrapped in a managed method 
    // to suppress this link demand.
    CONSISTENCY_CHECK_MSGF(!fPublicOrProtected,
        ("%s::%s has to be private or internal.",
        pMD->m_pszDebugClassName, pMD->m_pszDebugMethodName));
#endif
 
    return cur->m_pImplementation;
}

```

**Comment by jkotas** [comment]
This is again mismatch between managed and unmanaged bits. Looking at `pMD->m_pszDebugClassName` and `pMD->m_pszDebugMethodName` should give you clue what to look for.

**Comment by manu-silicon** [comment]
It might be the issue about missing Xplat, see #3857 and #3879

**Comment by myungjoo** [comment]
This looks like Xplat issue as @manu-silicon has mentioned. @leemgs, Let's retry this with recent binary. It looks like it is going to success this time.

**Comment by leemgs** [comment]
> It might be the issue about missing Xplat, see #3857 and #3879

 @manu-silicon , FYI. I  tried to test the effect of your PR some days ago in order to know whether or not the PR could normally run "`arm#> crossgen mscorlib.dll`" command on Linux/ARM emulator. At that time, I confirmed that the PR could not resolve this issue. 

>  Let's retry this with recent binary. It looks like it is going to success this time. (with the binary that successfully executes Roslyn at ARM)

@myungjoo, I have tried to test the "`arm#> crossgen mscorlib.dll`"  command again with 1) the latest commit number (f21291a702a4247b1dd1c3219eaf5319e94df061) and 2) PR(#3879).  The result is same(failure).

```
arm@bash-3.2# time ./crossgen ./mscorlib.dll 
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Assert failure(PID 10470 [0x000028e6], Thread: 10470 [0x28e6]): id != 0
    File: /work/dotnet/arm-32/coreclr/src/vm/ecall.cpp Line: 543
    Image: /nfs/runtime-hardfp-abi-vfp-debug-mode-20160416/crossgen

real	19m50.481s
user	19m48.056s
sys	0m1.080s
arm@bash-3.2# 
arm@bash-3.2# 
```

>  (with the binary that successfully executes Roslyn at ARM)

BTW, What do you mean by that? Is it related to https://github.com/dotnet/coreclr/issues/4354? do you mean that we can run  "**arm#> crossgen mscorlib.dll**" command  with (1) latest commit number and (2) the below your local patch ?  I will check it after the business trip. 

> https://github.com/dotnet/coreclr/issues/4354
> Although there is a local patch that is not yet verified to be good or bad:
```
diff --git a/src/vm/arm/stubs.cpp b/src/vm/arm/stubs.cpp
index cd58f29..483e2db 100644
--- a/src/vm/arm/stubs.cpp
+++ b/src/vm/arm/stubs.cpp
@@ -2237,7 +2237,7 @@ void UpdateRegDisplayFromCalleeSavedRegisters(REGDISPLAY * pRD, CalleeSavedRegis
     pRD->pCurrentContextPointers->R9 = (PDWORD)&pRegs->r9;
     pRD->pCurrentContextPointers->R10 = (PDWORD)&pRegs->r10;
     pRD->pCurrentContextPointers->R11 = (PDWORD)&pRegs->r11;
-    pRD->pCurrentContextPointers->Lr = NULL;
+    pRD->pCurrentContextPointers->Lr = (PDWORD)&pRegs->r14;
 }
 #ifndef CROSSGEN_COMPILE
```

**Comment by myungjoo** [comment]
That error used to shown up with MSCORLIB.DLL if there is a P/Invoking function from MSCORLIB.DLL to libcoreclr.so, which is missing in libcoreclr.so. By enabling FEATURE_EVENT_TRACE in CMakeList as a workaround mentioned in #4354, the function was enabled in libcoreclr.so and the error was gone.

**Comment by myungjoo** [comment]
You can further look into this issue by printing out the contents of pMD at the failed assertion. If the missing function is being disabled by #if macro in CoreCLR source code, it's almost certain that it's to be fixed by the workaround mentioned in #4354 or by the PR proposed by manu-silicon.

**Comment by manu-silicon** [comment]
Now that PR #3879 is merged, can you update the status of this issue?

**Comment by leemgs** [comment]
@manu-silicon , I will check it as soon as go back the office from the business trip. Thank you for your contribution.

**Comment by leemgs** [comment]
@manu-silicon ,  I have tested the "arm@emul#> ./crossgen mscorlib.dll" command on Linux/ARM Emulator with the latest commit number that you mentioned. The result is same (failure). Please refer to the below contents. In your case, Can you normally generate the mscorlib.ni.dll after applying the PR #3879 ?

* Build command:
@u1404:/work/dotnet/arm-32/coreclr$ time ROOTFS_DIR=/work/dotnet/rootfs-coreclr/arm ./build.sh arm debug clean cross


* commit number:
commit 21597ece522339ffdd127508c111a7748963d507
Merge: 0eff733 4537051
Author: Rahul Kumar <rahku@microsoft.com>
Date:   Tue Apr 19 22:40:03 2016 -0700

* Test case:  (I have tested the crossgen command on Linux/ARM Emulator)
emul@bash-3.2# time ./crossgen ./mscorlib.dll 
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.


Assert failure(PID 13272 [0x000033d8], Thread: 13272 [0x33d8]): Consistency check failed: No method entry found for System.StubHelpers.StubHelpers::MulticastDebuggerTraceHelper.
FAILED: 0 != id
    File: /work/dotnet/arm-32/coreclr/src/vm/ecall.cpp Line: 270
    Image: /nfs/runtime-hardfp-abi-vfp-debug-mode-20160420.xplat/crossgen

real	20m31.978s
user	20m27.252s
sys	0m1.160s
emul@bash-3.2#

**Comment by myungjoo** [comment]
The error message from @leemgs case implies that

FEATURE_STUBS_AS_IL is disabled as supposed for Linux/ARM for libcoreclr.so (native part of CoreCLR)
FEATURE_STUBS_AS_IL is ENABLED for mscorlib.dll.

As observed with another issue, #4354, (although it is resolved by a workaround), the compiler options (macros) are not being consistent between native build and managed build. We need some mechanisms to guarantee the consistency between the two build even if the managed part is built in a completely different environment. (native in ARM, managed in x64, but the given build.sh option said "arm")

**Comment by jkotas** [comment]
> where values such as "FEATURE_STUBS_AS_IL" are defined for mscorlib.dll 

It is defined here: https://github.com/dotnet/coreclr/blob/master/clr.coreclr.props#L91. Adding `Condition="'$(TargetArch)' != 'arm'" to it should fix this problem.

**Comment by jkotas** [comment]
> We need some mechanisms to guarantee the consistency between the two build

The asserts that you are hitting are the mechanism to verify the consistency.

**Comment by myungjoo** [comment]
> The asserts that you are hitting are the mechanism to verify the consistency.

Ultimately (not a urgent issue to be resolve for now), such consistency should be guaranteed, not checked dynamically (depending on test cases).
Or at least, it should be verified statically and deterministrically.

Thank you for showing us the direction on how to make it consistent.
I'll keep in mind that any changes in CMakeList may require updates in mscorlib.dll side as well.

**Comment by myungjoo** [comment]
Note that the PR #4673 above partially fixes this issue and introduces yet another bug:

```
sh-3.2# ./crossgen mscorlib.dll 
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Segmentation fault (core dumped)
sh-3.2#
```
