### ISSUE TITLE
Relocate APISet dependency to NETCoreApp MetaPackage

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3636]
For RTM, we should move the APISet dependency from the CoreCLR nuget package to become a dependency of NETCoreApp metapackage since CoreCLR is no longer expected to rely on them and we need them for the FX pieces. 

This will ensure the right dependencies are located correctly. for RC2, we keep things as-is.

**Comment by gkhanna79** [comment]
CC @weshaggard

**Comment by gkhanna79** [comment]
Closing since this is no longer required.

**Comment by weshaggard** [comment]
Did we remove the dependency from the runtime package already?

**Comment by gkhanna79** [comment]
I believe the apiset package dependency was removed from coreclr package as part of the apiset cleanup work that was done by John Chen.  Nothing was ever moved to m.n.app as it was not required.

Is that something you didn't expect @weshaggard?


Thanks,
Gaurav
________________________________

**Comment by weshaggard** [comment]
I expected this now and I also commented on the other issue specifically tracking that work.
