### ISSUE TITLE
 coreclr/tests/src/baseservices/threading/generics/Monitor/TryEnter06.cs fails on Windows

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#3646]
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1/342/

Added in https://github.com/dotnet/coreclr/pull/3497

@adityamandaleeka it looks like this was one of the tests added in your port, can you take a look?

**Comment by adityamandaleeka** [comment]
This is probably related to the OOM scenario that was causing strange failures last month. Since that's been addressed and this doesn't seem to be occurring anymore, I'm closing this issue now.
