### ISSUE TITLE
baseservices/exceptions/simple/HardwareEh.cs failing on Ubuntu

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#3648]
This test was added in https://github.com/dotnet/coreclr/pull/3489. @rahku can you take a look?

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_ubuntu_pri1_tst/lastCompletedBuild/testReport/baseservices.exceptions.simple/HardwareEh/HardwareEh/

**Comment by rahku** [comment]
Copying result from the above link
               BEGIN EXECUTION
               /mnt/j/workspace/dotnet_coreclr/x64_release_ubuntu_pri1_tst/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/corerun HardwareEh.exe
               Beginning test case Hardware exceptions: handled at 3/10/16 3:42:57 PM
               Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
               
               [Postive]
               Beginning scenario: PosTest1: Set misaligned field expect DataMisalignment Exception (IA64 only)
               Beginning scenario: PosTest2: Get misaligned field expect DataMisalignment Exception (IA64 only)
               Beginning scenario: PosTest3: NullReference
               Beginning scenario: PosTest4: NullReference (generic)
               Beginning scenario: PosTest5: NullReference (nullable)
               Beginning scenario: PosTest6: DivideByZero (int64)
               Beginning scenario: PosTest7: DivideByZero (int32)
               Beginning scenario: PosTest8: OverflowException (int64)
               Beginning scenario: PosTest9: OverflowException (int32)
               Beginning scenario: PosTest11: OutOfMemory
               
               Unhandled Exception: OutOfMemoryException.
               ./HardwareEh.sh: line 58: 54615 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" HardwareEh.exe $CLRTestExecutionArguments $Host_Args
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED

**Comment by rahku** [comment]
This is a behavior difference between windows & non-windows. On Windows OutOfMemoryException thrown by managed code can be caught whereas on non-windows it goes unhandled.

**Comment by rahku** [comment]
@janvorli this looks like a product bug

**Comment by rahku** [comment]
FYI @gkhanna79

**Comment by rahku** [comment]
Here is test code
https://github.com/dotnet/coreclr/blob/master/tests/src/baseservices/exceptions/simple/HardwareEh.cs#L118

**Comment by janvorli** [comment]
@rahku I am unable to repro it. I have tried both debug and release builds. In both cases, it behaved as expected and succeeded. I have tried to set the virtual memory limit to various low and high values and never got the failure. 
Unfortunately, the original link to the binaries doesn't work anymore. Do you still happen to have a local copy? And how much physical memory did you have in your machine when testing it?

**Comment by rahku** [comment]
I have not tried this locally. You could try if this still repros on CI machines.

**Comment by gkhanna79** [comment]
I have seen it repro on CI from time to time though it appears to be an infra issue.


Thanks,
Gaurav

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/3840 solves this issue for now

**Comment by sergiy-k** [comment]
This is related to how Linux manages (overcommits) its memory.

**Comment by janvorli** [comment]
I was recently looking into some other issues related to OOM. I have found that there are cases where the OutOfMemoryException is intentionally not handled - when we consider the process state to be corrupted. One such case is when we get OOM while trying to get resource string of a message for an exception. 
See CEHelper::CanMethodHandleException:
https://github.com/dotnet/coreclr/blob/master/src/vm/excep.cpp#L11736
I believe that was the case here - so I am closing this as won't fix.
