### ISSUE TITLE
SIGSEGV_HEAPCORRUPT_CollidedUnwind!CollidedUnwindTest.Bar 

### ISSUE THREAD

**Issue by schaabs** [dotnet/coreclr#3661]
**The notes in this bug refer to the dump [projectk-23907-00-amd64chk_005A](https://dotnetjobresults.blob.core.windows.net/projectk-23907-00-stress/3301cde5-c222-4b36-b5d7-78439bbdf1f5/stress/generated/07_02hr/projectk-23907-00-amd64chk_005A/projectk-23907-00-amd64chk_005A.csproj/projectk-23907-00-amd64chk_005A.zip?sv=2015-04-05&sr=c&sig=TUKChKMQxnFxn49F%2B8SOxcd%2B5Og5XYhyL8RMzQeIVSs%3D&se=2017-03-11T02:25:37Z&sp=rw). While some sos functionality is not available to fully diagnose this from the dump, this should repro under gcstress 3.**  

**This failure is a heap corruption where we segfault in mark phase of a GC.  The segfault is because we have an invalid root in CollidedUnwind!CollidedUnwindTest.Bar on thread 6 of the dump.**

    FAILURE_HASH:
    SIGSEGV_HEAPCORRUPT_CollidedUnwind!CollidedUnwindTest.Bar

    FAULT_STACK:
    libcoreclr.so!WKS::gc_heap::mark_object_simple
    libcoreclr.so!WKS::gc_heap::mark_object_simple
    libcoreclr.so!WKS::gc_heap::mark_object_simple
    libcoreclr.so!WKS::gc_heap::mark_object_simple
    libcoreclr.so!WKS::GCHeap::Promote
    libcoreclr.so!GcInfoDecoder::EnumerateLiveSlots
    libcoreclr.so!EECodeManager::EnumGcRefs
    libcoreclr.so!GcStackCrawlCallBack
    libcoreclr.so!Thread::MakeStackwalkerCallback
    libcoreclr.so!Thread::StackWalkFramesEx
    libcoreclr.so!Thread::StackWalkFrames
    libcoreclr.so!GCToEEInterface::GcScanRoots
    libcoreclr.so!GCToEEInterface::GcScanRoots
    libcoreclr.so!WKS::gc_heap::mark_phase
    libcoreclr.so!WKS::gc_heap::gc1
    libcoreclr.so!WKS::gc_heap::garbage_collect
    ...
    
    CORRUPT_ROOT_THREAD:
    thread #6: tid = 53675, 0x00007fcc02ee1414 libpthread.so.0`__pthread_cond_wait + 196 at pthread_cond_wait.S:185, stop reason = signal SIGSEGV

    CORRUPT_ROOT_FRAME_PC:
    0x7fcb887a1c6c

    CORRUPT_ROOT_FRAME:
    CollidedUnwind!CollidedUnwindTest.Bar

**Looking at thread 6 we can see that we are in Pass 2 of managed exception handling.  And we appear to have a nested exception on the thread originating from CollidedUnwind!CollidedUnwindTest.Bar, the method with the corrupted root**
 
    0       0x7fcc02ee1414 libpthread.so.0!__pthread_cond_wait
    1       0x7fcc01efff62 libcoreclr.so!CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*)
    2       0x7fcc01effc20 libcoreclr.so!CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*)
    3       0x7fcc01f04701 libcoreclr.so!CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int)
    4       0x7fcc01f04822 libcoreclr.so!WaitForSingleObjectEx
    5       0x7fcc01b20641 libcoreclr.so!CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*)
    6       0x7fcc01b2063c libcoreclr.so!CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*)
    7       0x7fcc01b20633 libcoreclr.so!CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*)
    8       0x7fcc01b205d0 libcoreclr.so!CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*)
    9       0x7fcc01b24dd3 libcoreclr.so!Thread::RareDisablePreemptiveGC()
    10      0x7fcc01b42cde libcoreclr.so!ProcessCLRException
    11      0x7fcc01b42cc3 libcoreclr.so!ProcessCLRException
    12      0x7fcc01b42cba libcoreclr.so!ProcessCLRException
    13      0x7fcc01b42ca7 libcoreclr.so!ProcessCLRException
    14      0x7fcc01b47029 libcoreclr.so!UnwindManagedExceptionPass2(PAL_SEHException&, _CONTEXT*)
    15      0x7fcc01b4775b libcoreclr.so!DispatchManagedException(PAL_SEHException&)
    16      0x7fcc01abe703 libcoreclr.so!IL_Throw(Object*)
    17      0x7fcb887a279f CollidedUnwind!CollidedUnwindTest.Fubar()
    18      0x7fcb887a2471 CollidedUnwind!CollidedUnwindTest.FnDDD()
    19      0x7fcb887a2131 CollidedUnwind!CollidedUnwindTest.FnCCC()
    20      0x7fcb887a1c6c CollidedUnwind!CollidedUnwindTest.Bar()
    21      0x7fcb887a08b1 CollidedUnwind!CollidedUnwindTest.FnBBB()
    22      0x7fcb8879ff71 CollidedUnwind!CollidedUnwindTest.FnAAA()
    23      0x7fcb8879f41c CollidedUnwind!CollidedUnwindTest.Foo()
    24      0x7fcb8879ecfa CollidedUnwind!CollidedUnwindTest.Run()
    25      0x7fcb8879dfeb CollidedUnwind!TestSet.MainMethod()
    26      0x7fcb8879de64 CollidedUnwind!TestSet.TestRunner()
    27      0x7fcb8879ca5e projectk-23907-00-amd64chk_005A!stress.generated.UnitTests.UT12()
    28      0x7fcb8879bf58 stress.execution!stress.execution.UnitTest.Execute()
    ...
    
    (lldb) pe -nested
    Exception object: 00007fcb600821a8
    Exception type:   CollidedUnwindTest+ExType2
    Message:          <none>
    InnerException:   <none>
    StackTrace (generated):
        SP               IP               Function
    --> 00007FCB875298F0 00007FCB887A1D00 CollidedUnwind.dll!CollidedUnwindTest.Bar()+0x110 <--
        00007FCB8752D4B0 00007FCB887A08B1 CollidedUnwind.dll!CollidedUnwindTest.FnBBB()+0x71
        00007FCB8752D4E0 00007FCB8879FF71 CollidedUnwind.dll!CollidedUnwindTest.FnAAA()+0x71
        00007FCB8752D510 00007FCB8879F41C CollidedUnwind.dll!CollidedUnwindTest.Foo()+0x7c
        00007FCB8752D560 00007FCB8879ECFA CollidedUnwind.dll!CollidedUnwindTest.Run()+0xca

    StackTraceString: <none>
    HResult: 80131500

    Nested exception -------------------------------------------------------------
    Exception object: 00007fcb6006c000
    Exception type:   CollidedUnwindTest+ExType1
    Message:          <none>
    InnerException:   <none>
    StackTrace (generated):
        SP               IP               Function
        00007FCB8752D3B0 00007FCB887A279F CollidedUnwind.dll!CollidedUnwindTest.Fubar()+0xaf
        00007FCB8752D400 00007FCB887A2471 CollidedUnwind.dll!CollidedUnwindTest.FnDDD()+0x71
        00007FCB8752D430 00007FCB887A2131 CollidedUnwind.dll!CollidedUnwindTest.FnCCC()+0x71
        00007FCB8752D460 00007FCB887A1C6C CollidedUnwind.dll!CollidedUnwindTest.Bar()+0x7c
        00007FCB8752D4B0 00007FCB887A08B1 CollidedUnwind.dll!CollidedUnwindTest.FnBBB()+0x71
        00007FCB8752D4E0 00007FCB8879FF71 CollidedUnwind.dll!CollidedUnwindTest.FnAAA()+0x71
        00007FCB8752D510 00007FCB8879F41C CollidedUnwind.dll!CollidedUnwindTest.Foo()+0x7c

**Comment by janvorli** [comment]
This issue was fixed by my recent change #3584. I was able to repro it locally with the files from the crashdump package and replacing the coreclr with the latest build fixed the problem. To be really sure, I've synced my sources back before my fix, rebuilt and ran the test with the resulting binaries - it crashed soon.
