### ISSUE TITLE
ARM64: zeroInit tests regression 

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3665]
The following two tests regressed after the update to the latest test build

init_int32.exe_773 :: JIT\Directed\zeroinit\init_int32\init_int32.exe
init_uint32.exe_776 :: JIT\Directed\zeroinit\init_uint32\init_uint32.exe

Running the test yields:
%CORERUN% JIT\Directed\zeroinit\init_uint32\init_uint32.exe
Error 113

**Comment by kyulee1** [comment]
Fixed by #3687
