### ISSUE TITLE
ARM64: Tests failing due to unexpected OverflowException

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3667]
After the test update these tests regressed and now fail with 
Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.

b43121.exe_4925 :: JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b43121\b43121\b43121.exe 
b68045.exe_5200 ::  JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b68045\b68045\b68045.exe

**Comment by kyulee1** [comment]
I have a fix for b68045. It appears b43121 is another issue.

**Comment by kyulee1** [comment]
Fixed by #3692 and #3698
