### ISSUE TITLE
Strip symbols on release builds into a separate binary

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#3669]
Enabling the source/line info for release builds for internal and CSS dev support caused the coreclr nuget packages to bloat considerable. Fix this by stripping the symbols into a separate symbols binary.

For the Linux distros and FreeBSD (probably NetBSD too), this can be added to the build of the native binaries in coreclr:

objcopy --only-keep-debug $@ $@.dbg
objcopy --strip-unneeded $@
objcopy --add-gnu-debuglink=$@.dbg $@

$@ is the binary.

For OSX:
dsymutil libcoreclr.dylib -o libcoreclr.dSYM
strip -S libcoreclr.dylib

**Comment by mikem8361** [comment]
There are still open questions about how to package the resulting symbol files in a way that can be easy installed side-by-side with the nuget ones.

**Comment by sergiy-k** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/3872
