### ISSUE TITLE
Need SOS gcinfo and related options ported to xplat

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#3676]
This seriously impacts our ability to investigate heap corruption failures from our stress runs and partner teams.

GCInfo           - this function is present but it doesn’t work, give error ‘AMD64Machine::DumpGCInfo not implemented’
clru -gcinfo   - currently the u function works but doesn’t recognize the -gcinfo switch
clrstack -gc   - this function is available and recognizes the -gc switch but segfaults when the -gc switch is passed in

The work is mostly removing the use of Windows fibers from the gcinfo related code.

**Comment by janvorli** [comment]
The clrstack -gc actually worked for me when live debugging something, so it segfaults just in some cases.

**Comment by mikem8361** [comment]
Created #4725 for the clru -gcinfo option.
