### ISSUE TITLE
COMPLUS_ContinueOnAssert has no effect on Linux

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/coreclr#3686]
I have a piece of unsafe/unverifiable IL which works under normal .NET but causes an assert violation under CoreCLR. On Windows if I set COMPLUS_ContinueOnAssert to 1, it will ignore it and continue. However on Linux, the setting has no effect and my program will exit.

**Comment by janvorli** [comment]
I guess you have spelled it as COMPlus_ContinueOnAssert, right?

**Comment by manu-silicon** [comment]
Looks like I haven't. The doc is confusing as you see various spelling of it. I'll propose a PR to fix those.

**Comment by manu-silicon** [comment]
See PR #3745
