### ISSUE TITLE
setup-runtime-dependencies bad temp file management

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#3688]
coreclr/tests/setup-runtime-dependencies.* writes a project.json file in their own folder.  Temp files belong under %TMP% if possible or under coreclr/bin if absolutely necessary.

Also, there are failure paths along which the temp project.json is not deleted.  Please fix that as well.

**Comment by RussKeldorph** [comment]
Sorry to pile to onto this, but this script also fails if it is run from the tests folder (and many other places).  It should do the right thing regardless of the current working directory.

**Comment by sejongoh** [comment]
I fixed the window script and will update the Linux one.

**Comment by sejongoh** [comment]
Fixed.
