### ISSUE TITLE
Failed To Find NI image

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3689]
JIT._jit64_opt_cse_hugeexpr1_hugeexpr1_._jit64_opt_cse_hugeexpr1_hugeexpr1_cmd
\r\nAssert failure(PID 4784 [0x000012b0], Thread: 12636 [0x315c]): ZapRequire: Could not get native image for hugeexpr1.\r\nUse FusLogVw.exe to check the reason.\r\n\r\nCORECLR! DomainFile::CheckZapRequired + 0x43B (0x00007ff8`e90b718b)\r\nCORECLR! DomainAssembly::FindNativeImage + 0xCC1 (0x00007ff8`e90ba6a1)\r\nCORECLR! DomainFile::DoIncrementalLoad + 0x28C (0x00007ff8`e90b882c)\r\nCORECLR! AppDomain::TryIncrementalLoad + 0x2A9 (0x00007ff8`e8e758e9)\r\nCORECLR! AppDomain::LoadDomainFile + 0xB67 (0x00007ff8`e8e57d07)\r\nCORECLR! AppDomain::LoadDomainAssemblyInternal + 0x9BF (0x00007ff8`e8e5701f)\r\nCORECLR! AppDomain::LoadDomainAssembly + 0xF8 (0x00007ff8`e8e565f8)\r\nCORECLR! AssemblySpec::LoadDomainAssembly + 0x8F0 (0x00007ff8`e8fa4d50)\r\nCORECLR! AssemblySpec::LoadAssembly + 0x17B (0x00007ff8`e8fa3a7b)\r\nCORECLR! AssemblySpec::LoadAssembly + 0x3FA (0x00007ff8`e8fa43da)\r\n    File: c:\kgk\github\gkhanna79\coreclr\src\vm\domainfile.cpp Line: 963\r\n    Image: C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\CoreRun.exe\r\n\r\n\n\nRaw output:      C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Reports\JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.output.txt\nTo run the test:\n> set CORE_ROOT=C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\n> C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.cmd\n\r\nExpected: True\r\nActual:   False
   at JIT._jit64_opt_cse_hugeexpr1_hugeexpr1_._jit64_opt_cse_hugeexpr1_hugeexpr1_cmd() in C:\KGK\GitHub\gkhanna79\coreclr\tests\src\TestWrappers_x64_Debug\JIT\JIT.XUnitWrapper.cs:line 96341
34.4400749s 

✘  JIT._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_do_bigvtbl_cs_do_._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_do_bigvtbl_cs_do_cmd
\r\nAssert failure(PID 10728 [0x000029e8], Thread: 11628 [0x2d6c]): ZapRequire: Could not get native image for bigvtbl_cs_do.\r\nUse FusLogVw.exe to check the reason.\r\n\r\nCORECLR! DomainFile::CheckZapRequired + 0x43B (0x00007ff8`e90b718b)\r\nCORECLR! DomainAssembly::FindNativeImage + 0xCC1 (0x00007ff8`e90ba6a1)\r\nCORECLR! DomainFile::DoIncrementalLoad + 0x28C (0x00007ff8`e90b882c)\r\nCORECLR! AppDomain::TryIncrementalLoad + 0x2A9 (0x00007ff8`e8e758e9)\r\nCORECLR! AppDomain::LoadDomainFile + 0xB67 (0x00007ff8`e8e57d07)\r\nCORECLR! AppDomain::LoadDomainAssemblyInternal + 0x9BF (0x00007ff8`e8e5701f)\r\nCORECLR! AppDomain::LoadDomainAssembly + 0xF8 (0x00007ff8`e8e565f8)\r\nCORECLR! AssemblySpec::LoadDomainAssembly + 0x8F0 (0x00007ff8`e8fa4d50)\r\nCORECLR! AssemblySpec::LoadAssembly + 0x17B (0x00007ff8`e8fa3a7b)\r\nCORECLR! AssemblySpec::LoadAssembly + 0x3FA (0x00007ff8`e8fa43da)\r\n    File: c:\kgk\github\gkhanna79\coreclr\src\vm\domainfile.cpp Line: 963\r\n    Image: C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\CoreRun.exe\r\n\r\n\n\nRaw output:      C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Reports\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_do\bigvtbl_cs_do.output.txt\nTo run the test:\n> set CORE_ROOT=C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\n> C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_do\bigvtbl_cs_do.cmd\n\r\nExpected: True\r\nActual:   False
   at JIT._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_do_bigvtbl_cs_do_._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_do_bigvtbl_cs_do_cmd() in C:\KGK\GitHub\gkhanna79\coreclr\tests\src\TestWrappers_x64_Debug\JIT\JIT.XUnitWrapper.cs:line 240056
70.4580959s 

✘  JIT._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_ro_bigvtbl_cs_ro_._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_ro_bigvtbl_cs_ro_cmd
\r\nAssert failure(PID 10868 [0x00002a74], Thread: 1492 [0x05d4]): ZapRequire: Could not get native image for bigvtbl_cs_ro.\r\nUse FusLogVw.exe to check the reason.\r\n\r\nCORECLR! DomainFile::CheckZapRequired + 0x43B (0x00007ff8`ec3d718b)\r\nCORECLR! DomainAssembly::FindNativeImage + 0xCC1 (0x00007ff8`ec3da6a1)\r\nCORECLR! DomainFile::DoIncrementalLoad + 0x28C (0x00007ff8`ec3d882c)\r\nCORECLR! AppDomain::TryIncrementalLoad + 0x2A9 (0x00007ff8`ec1958e9)\r\nCORECLR! AppDomain::LoadDomainFile + 0xB67 (0x00007ff8`ec177d07)\r\nCORECLR! AppDomain::LoadDomainAssemblyInternal + 0x9BF (0x00007ff8`ec17701f)\r\nCORECLR! AppDomain::LoadDomainAssembly + 0xF8 (0x00007ff8`ec1765f8)\r\nCORECLR! AssemblySpec::LoadDomainAssembly + 0x8F0 (0x00007ff8`ec2c4d50)\r\nCORECLR! AssemblySpec::LoadAssembly + 0x17B (0x00007ff8`ec2c3a7b)\r\nCORECLR! AssemblySpec::LoadAssembly + 0x3FA (0x00007ff8`ec2c43da)\r\n    File: c:\kgk\github\gkhanna79\coreclr\src\vm\domainfile.cpp Line: 963\r\n    Image: C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\CoreRun.exe\r\n\r\n\n\nRaw output:      C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Reports\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_ro\bigvtbl_cs_ro.output.txt\nTo run the test:\n> set CORE_ROOT=C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\n> C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_ro\bigvtbl_cs_ro.cmd\n\r\nExpected: True\r\nActual:   False
   at JIT._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_ro_bigvtbl_cs_ro_._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_ro_bigvtbl_cs_ro_cmd() in C:\KGK\GitHub\gkhanna79\coreclr\tests\src\TestWrappers_x64_Debug\JIT\JIT.XUnitWrapper.cs:line 240166

**Comment by jkotas** [comment]
hugeexpr1 is dup of #3600.

**Comment by gkhanna79** [comment]
Please use http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_pri1r2r/lastCompletedBuild/testReport/ to determine how many of these are outstanding in the current runs.

**Comment by fadimounir** [comment]
This issue no longer repros with the latest runtime. Closing.
