### ISSUE TITLE
Assert failure(PID 17308 [0x0000439c], Thread: 15216 [0x3b70]): !RequiresInstArg()

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3690]
CoreMangLib._system_delegate_generics_NG_Standard_NG_Standard_._system_delegate_generics_NG_Standard_NG_Standard_cmd
\r\nAssert failure(PID 17308 [0x0000439c], Thread: 15216 [0x3b70]): !RequiresInstArg()\r\n\r\nCORECLR! MethodDesc::TryGetMultiCallableAddrOfCode + 0x231 (0x00007ff8`ed3aff91)\r\nCORECLR! MethodDesc::GetMultiCallableAddrOfCode + 0x17E (0x00007ff8`ed3a5cfe)\r\nCORECLR! DynamicHelperFixup + 0xDB0 (0x00007ff8`ed24ad30)\r\nCORECLR! DynamicHelperWorker + 0x298 (0x00007ff8`ed250478)\r\nCORECLR! DelayLoad_Helper_ObjObj + 0x7A (0x00007ff8`ed7a307a)\r\nNG_STANDARD.NI! COM+_Entry_Point + 0xFFFFFFFF (0x00007ff9`17714de3)\r\nCORECLR! CallDescrWorkerInternal + 0x83 (0x00007ff8`ed8fba53)\r\nCORECLR! CallDescrWorkerWithHandler + 0x1DE (0x00007ff8`ed42529e)\r\nCORECLR! MethodDescCallSite::CallTargetWorker + 0xDBB (0x00007ff8`ed42606b)\r\nCORECLR! MethodDescCallSite::Call_RetArgSlot + 0xE9 (0x00007ff8`ed0de769)\r\n    File: c:\kgk\github\gkhanna79\coreclr\src\vm\method.cpp Line: 2316\r\n    Image: C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\CoreRun.exe\r\n\r\n\n\nRaw output:      C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Reports\CoreMangLib\system\delegate\generics\NG_Standard\NG_Standard.output.txt\nTo run the test:\n> set CORE_ROOT=C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\n> C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\CoreMangLib\system\delegate\generics\NG_Standard\NG_Standard.cmd\n\r\nExpected: True\r\nActual:   False
   at CoreMangLib._system_delegate_generics_NG_Standard_NG_Standard_._system_delegate_generics_NG_Standard_NG_Standard_cmd() in C:\KGK\GitHub\gkhanna79\coreclr\tests\src\TestWrappers_x64_Debug\CoreMangLib\CoreMangLib.XUnitWrapper.cs:line 124336

**Comment by JohnChen0** [comment]
Fix has been committed to master branch and release/1.0.0-rc2 branch.
