### ISSUE TITLE
Test Timed out

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3691]
GC._Regressions_v2_0_beta2_462651_462651_462651_._Regressions_v2_0_beta2_462651_462651_462651_cmd
cmdLine:C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\GC\Regressions\v2.0-beta2\462651\462651\462651.cmd Timed Out\r\n\n\nRaw output:      C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Reports\GC\Regressions\v2.0-beta2\462651\462651\462651.output.txt\nTo run the test:\n> set CORE_ROOT=C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\n> C:\KGK\GitHub\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Debug\GC\Regressions\v2.0-beta2\462651\462651\462651.cmd\n\r\nExpected: True\r\nActual:   False
   at GC._Regressions_v2_0_beta2_462651_462651_462651_._Regressions_v2_0_beta2_462651_462651_462651_cmd() in C:\KGK\GitHub\gkhanna79\coreclr\tests\src\TestWrappers_x64_Debug\GC\GC.XUnitWrapper.cs:line 6361

**Comment by JohnChen0** [comment]
The test didn't time out when run manually. This is a long test that needs at least 256 seconds to run, so it might time out in an automated run if too many processes are competing for resources or if timeout isn't configured correctly. Moving to RTM as this doesn't appear to be an RC2 blocker.

**Comment by mkborg** [comment]
I have got almost the same issue:
> 1:2>C:\git\2273881\coreclr\bin\tests\Windows_NT.x64.Debug\TestWrappers\GC\GC.XUnitWrapper.cs(8799): error : GC._Regressions_v2_0_beta2_462651_462651_462651_._Regressions_v2_0_beta2_462651_462651_462651_cmd [FAIL] [C:\git\2273881\corec
lr\tests\runtest.proj]

Is there any way to increase timeout?

**Comment by JohnChen0** [comment]
Closed #3691 via #4829.
