### ISSUE TITLE
Missing projects in AllTestProjects.sln

### ISSUE THREAD

**Issue by shiftkey** [dotnet/coreclr#37]
Opening `.\tests\src\AllTestProjects.sln` in VS2013 indicates a couple of `csproj` files are missing:

> C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Framework\ReliabilityFramework.csproj : error  : The project file could not be loaded. Could not find file 'C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Framework\ReliabilityFramework.csproj'.  C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Framework\ReliabilityFramework.csproj
>
> C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Tests\GC_Stress_tests_collection.csproj : error  : The project file could not be loaded. Could not find file 'C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Tests\GC_Stress_tests_collection.csproj'.  C:\Users\brendanforster\Documents\windows\coreclr\tests\src\GC\Stress\Tests\GC_Stress_tests_collection.csproj

There's source code at these locations, so I guess something got lost in the transition. I gather these use a similar csproj setup as other test projects - if there's nothing fancy about them it should be easy to include...

**Comment by ramarag** [comment]
Thanks shiftkey for reporting the issue
The project files were not added in my previous commit. I have them now in https://github.com/dotnet/coreclr/pull/38

**Comment by shiftkey** [comment]
@ramarag :+1:
