### ISSUE TITLE
Enable CI support for Ready2Run Tests

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3707]
1) Enable Pri1 R2R tests per commit
2) Enable Pri0 R2R tests with trigger phrase

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/3705 should take care of this. Read the description at the top of that PR to see all the possible trigger phrases. I went ahead and enabled trigger phrases for both Pri0 and Pri1 R2R tests, in addition to per-commit pri1 R2R tests.

**Comment by wtgodbe** [comment]
We'll have to wait until the CI is back up to see if this works, and even then we won't be able to use the trigger phrases until the PR is merged (i.e., we can't test the trigger phrases by using them on that PR)

**Comment by wtgodbe** [comment]
Solved by https://github.com/dotnet/coreclr/pull/3705
