### ISSUE TITLE
Enable Perf infrastructure support for Ready2Run

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3709]
We should have a mode/support/tests for Ready2Run performance analysis and regression. This includes Size, Working set, warm startup measurements.

**Comment by lt72** [comment]
We have dev-time automation available through the CLI performance tests. We will not cover anything but execution speed in the RTM time frame, and stretch goal is to automate such tests as part of Jenkins functional tests run for JIT.
