### ISSUE TITLE
Feature complete SOS for arrm64 windows

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3712]
Implement and validate all remaining SOS commands

**Comment by ramarag** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/4021/commits/6a2e3b34c3c9ac32456d38567b9f44ab6aea2f63

**Comment by janvorli** [comment]
@ramarag, I am not sure how the referred change implements and validates all the remaining SOS commands. There were no additions of new commands and no additions of missing options to existing SOS commands.

**Comment by ramarag** [comment]
@janvorli : why do you think that we have to add new commands and why would there be missing options to existing commands? It would be great if you could point out an example

**Comment by janvorli** [comment]
@ramarag Maybe I misunderstood the purpose of this github issue. The description says "Implement and validate all remaining SOS commands". So I have thought the goal is to implement all SOS commands (and all their options) for CoreCLR on Unix. So far, we have implemented only a subset of the commands, see https://github.com/dotnet/coreclr/blob/master/src/ToolBox/SOS/lldbplugin/soscommand.cpp#L124

**Comment by ramarag** [comment]
Ah yes, you have misunderstood, this is to track for windows arm64. may be we should start tagging platforms too, closing it again
