### ISSUE TITLE
CoreCLR nuget package missing runtime.json

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3724]
At https://github.com/dotnet/coreclr/commit/af1b954466de2b931809434bf8ad4dc355dc3e98 commit, building CoreCLR repo produces a nuget package that contains a runtime.json in the redirection package.

After https://github.com/dotnet/coreclr/commit/227e648d5b2d605e81498ab0b9a06d5e2998590b commit, which updated the BuildTools package from 177 to 196, the redirection package no longer contains runtime.json.

@weshaggard @joperezr Is this expected?

CC @rahku

**Comment by weshaggard** [comment]
@ericstj @chcosta do you guys think it has anything to do with the FAT package work we did?

**Comment by ericstj** [comment]
You need to explicitly opt-into including the runtime.json via the `IncludeRuntimeJson` property : https://github.com/dotnet/buildtools/blob/d858d541fb3eda3cf9e4c93b732c5e15f0409229/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets#L593

**Comment by gkhanna79** [comment]
@ericstj When did this behavior change? It appears to be breaking since this was working earlier.

**Comment by gkhanna79** [comment]
@ericstj Also, should this property be set only for the redirection package's pkgproj?
