### ISSUE TITLE
ARM64: implement profiler apis 

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#3732]

**Comment by ramarag** [comment]
@noahfalk  please reassign this as appropriate

**Comment by BruceForstall** [comment]
@noahfalk Is this still an active issue?

**Comment by noahfalk** [comment]
Unless someone already implemented it then its still tracking work that needs to be done eventually, but I'm happy to chat about prioritization, timelines, or if there is another more useful way to track it?

**Comment by noahfalk** [comment]
@davmason - based on your recent success with profiler testing on arm64 are you aware of any work needing to happen here? If not please close : )

**Comment by davmason** [comment]
@noahfalk I've only tested linux arm64, so I am not aware of any work but also have not tested windows yet. I'm in progress on testing windows but running in to other issues preventing me from actually running the tests so far

**Comment by noahfalk** [comment]
Ah got it, thanks!

**Comment by davmason** [comment]
Testing is done on windows for arm64 as well
