### ISSUE TITLE
buildtest failing. "Windows.props' not found"

### ISSUE THREAD

**Issue by cheers00** [dotnet/coreclr#374]
coreClr build succeeded but tests build is failing. 

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\AppxPackage\Microsoft.AppXPackage.Targets(451,9): error APP
X1639: File 'Windows.props' not found. See http://go.microsoft.com/fwlink/?prd=12395&pver=1.0&plcid=0x409&ar=MSDN&sar=P
latformMultiTargeting&o1=C:\Program Files (x86)\Microsoft SDKs\Portable\v12.0&o2=Portable for more information. [C:\Pro
jects\GitHub\coreclr\tests\src\Common\Coreclr.TestWrapper\Coreclr.TestWrapper.csproj]
```

**Comment by ramarag** [comment]
HI Cheers00 Thank you for reporting this issues. 
Can you describe your VS installation and 
also did you try installing http://msdn.microsoft.com/en-us/windows/desktop/bg162891.aspx as described in http://stackoverflow.com/questions/23442152/file-windows-props-not-found

**Comment by cheers00** [comment]
I've successfully built using VS 2013. I recently installed VS 2015 CTP6 and wondering VS 15 is causing this error.

**Comment by Parthas-Menethil** [comment]
Take a look at https://github.com/dotnet/coreclr/issues/30

**Comment by cheers00** [comment]
It helps. I installed VS 2013 ultimate with update again and now I can build without any problems. I don't know if this has any effect on VS 2015 CTP6 yet.
