### ISSUE TITLE
ARM64: assert: '!"Unsupported TYP_STRUCT arg kind"

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3748]
The following three tests fail with this assert:

seq_byte_1_d.exe_3327 # JIT\Methodical\explicit\coverage\seq_byte_1_d\seq_byte_1_d.exe (IL size 6940)
seq_byte_1_r.exe_3328 # JIT\Methodical\explicit\coverage\seq_byte_1_r\seq_byte_1_r.exe (IL size 6940)
TailCallCases.exe_4413 # JIT\opt\ETW\TailCallCases\TailCallCases.exe (IL size 103)

**Comment by kyulee1** [comment]
This is the case when we pass the struct whose size is 3,5, or 7 (not 2^n and a single reg pass).
One way we could do is like https://github.com/dotnet/coreclr/pull/5287/files to handle such case in morph. I leave this is up to you since it's related to struct passing API that you're working on.

**Comment by briansull** [comment]
Fixed
