### ISSUE TITLE
Defects in PATENTS.TXT

### ISSUE THREAD

**Issue by nathanaeljones** [dotnet/coreclr#375]
PATENTS.TXT is defective; the patent grant is limited  to runtime implementations compliant with "**[additional functionality in Microsoft's .NET Framework, as described in Microsoft's API documentation on its MSDN website](https://github.com/dotnet/corefx/blob/master/PATENTS.TXT#L37,L39)**".

There are many problems with this phrase (clause b), including

* Compliance with nebulous and changing documentation on a *massive website*.
* Compliance with documentation which is known to  *incorrectly* describe actual behavior and interfaces of any .NET runtime. *No* runtime compliant strictly compliant with this clause exists.
* The inherent prevention from enhancing or moving APIs forward, which is one of the purposes behind Core CLR.

**In my interpretation, this clause alone invalidates the entire grant for the purposes of .NET runtime development**.

Clause (a), ECMA-335 compliance, appears identical to [the community promise from 2007](http://www.microsoft.com/openspecifications/en/us/programs/community-promise/default.aspx). This has been critiqued before, but continues to brings up concerns, such as:
* Are all Microsoft .NET variants actually ECMA-335? Would coreclr and .NET Native (as-is) be on this list? 
* Is the /corefx repository ECMA-335 compliant? 
* How does this permit for innovation or experimentation?

The [clause in full](https://github.com/dotnet/corefx/blob/master/PATENTS.TXT#L37,L39):

> ".NET Runtime" means any compliant implementation in software of (a) all of 
the required parts of the mandatory provisions of Standard ECMA-335 – Common 
Language Infrastructure (CLI); and (b) if implemented, any additional 
functionality in Microsoft's .NET Framework, as described in Microsoft's API 
documentation on its MSDN website. For example, .NET Runtimes include 
Microsoft's .NET Framework and those portions of the Mono Project compliant 
with (a) and (b). 

If Microsoft doesn't wish to restrict the grant so heavily, as interpreted here, **why is the applicability to Mono so qualified**? ->  ["portions of the Mono Framework compliant"](https://github.com/dotnet/corefx/blob/master/PATENTS.TXT#L40). 

It's clear that there's a concern over forking of the runtime, but embracing forking (and re-merging, which often brings great leaps), is part of open-source development. **Developers will always want all the libraries and tools they love to be compatible and work together.** I don't think this is something Microsoft needs to enforce or police; it will happen naturally.  Severe compatibility changes are rarely made by communities; rather, they typically originate with owner companies or BDFLs.  

I would encourage replacing PATENTS.TXT with something with precise and deterministically interpretable; the Apache 2 patent grants are an excellent candidate.  This will help eliminate another source of .NET FUD. Please note that some of these concerns have been brought up on other blogs, and are not original.

**Comment by shanselman** [comment]
@smuckwell

**Comment by ellismg** [comment]
@richlander Do you want to take a crack at this with the lawyers to figure out what, if any, of these concerns can be addressed?

**Comment by nathanaeljones** [comment]
In addition to removing clause (b), it might be good to clarify the purpose of the patent grant in a license file, perhaps by some explanatory text, such as:

> While the MIT license allows you to to copy the source code, many Microsoft patents apply to the software represented by that source code, and you may be infringing upon those patents by using that software outside the context of a ECMA-335-compliant runtime (or application targeting such a runtime).

Talking to a few other users, it's clear that this is *NOT* well communicated. They assumed [that open-source definition (particularly criteria 6, 8, 9, and 10)](http://opensource.org/osd-annotated) applied to the software as a whole, and not just the copyrights. There's an implicit assumption that something MIT/BSD licensed simply has no relevant patents; often this is stated explicitly with a project. 

If available, a list of applicable patents could eventually be helpful to assist users in avoiding infringement. This is somewhat low priority, as I wouldn't expect to see open source reuse outside of the .NET context this early.

**Comment by LongLiveCHIEF** [comment]
@ellismg @richlander have there been any updates to the status of this one behind the scenes?

**Comment by masonwheeler** [comment]
Not a lawyer, but didn't the Supreme Court recently rule in Alice v. CLS Bank that software patents on "generic computer functions" are invalid?  Seeing as how the entire point of a low-level runtime is to provide "generic computer functions" for programmers to build upon, there could very well be nothing to protect here anymore...

**Comment by richlander** [comment]
I had the opportunity to talk to @nathanaeljones at a conference about his concerns, back in 2015. We haven't see any more concerns on this issue, so I'm taking the opportunity to close this old issue.

**Comment by LongLiveCHIEF** [comment]
To be clear, a lack of annoying bumps is not the same as the lack of concerns.

**Comment by masonwheeler** [comment]
Agreed.  Has this actually been fixed?  If not, it shouldn't be closed.

**Comment by nathanaeljones** [comment]
As I understand, the runtime clause was intended to increase, not decrease, the scope - however, those were not the legal words used, and without context - does not parse that way.

Interpreted strictly, this patent non-assertion promise only applies to usage of source code acquired from the coreclr and corefx repositories, and combined with the .NET Runtime restriction, seems unlikely to be interpreted in a way that covers un-merged pull requests or forks. 

I don't really have a dog in this fight, but I think this can easily be cleared up. PR incoming.
