### ISSUE TITLE
Test Cleanup: Move test invocation script to runtest.cmd 

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3759]
Today, buildtest.cmd generates the script required to invoke the tests. This also bakes into the script runtime configuration pieces (e.g. crossgen of test or setting GC stress level). This forces one to do two different test builds, as an example, if different test configurations are required.

We should move the batch file generation to runtest.cmd so that a single test build can be used for various scenarios.

**Comment by AndyAyersMS** [comment]
@gkhanna79 isn't there already a way to tailor execution at runtime? Eg for testing LLILC we were able to set a bunch of COMPlus variables around each test invocation. We use this now to enable stress modes and the like in the CI. 

Look at the `TestEnv` option to `runtest.cmd`, and how it's used in `netci.groovy` for various stress modes.

**Comment by gkhanna79** [comment]
Yes, looks like that is an option that can be used to move both these operations out. However, for crossgen, in addition to environment variable setting, an additional command would need to be inserted to perform the compile.
