### ISSUE TITLE
JIT Tests Failing in CI for Ubuntu and OSX

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3763]
I see two tests failing in Ubuntu and OSX:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_osx_tst_prtest/70/testReport/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/79/testReport/

These are failing due to missing assemblies. Is this due to the test refresh?

CC @briansull

**Comment by jkotas** [comment]
I have disabled these tests in https://github.com/dotnet/coreclr/pull/3755

**Comment by jashook** [comment]
The test refresh we did for arm64 should have no relation to these failing tests. Removing myself.

**Comment by dagood** [comment]
I fixed some errors like these while upgrading the test dependencies so I could add in version validation. Looking into if this can be fixed the same way and trying to set up a repro locally.

**Comment by dagood** [comment]
Starting from https://github.com/dotnet/coreclr/issues/3664#issuecomment-198072221 downward I investigated this issue over there. I didn't come up with a way to solve it though. Basically it's a fusion mismatch where it expects the package version, gets the just-built corefx version, and doesn't like it.

**Comment by dagood** [comment]
These tests were reenabled by https://github.com/dotnet/coreclr/pull/4397.
