### ISSUE TITLE
GCStress Failure: GC._API_GC_KeepAliveRecur

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3765]
GC._API_GC_KeepAliveRecur_KeepAliveRecur_._API_GC_KeepAliveRecur_KeepAliveRecur_cmd
\n\nRaw output:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Reports\GC\API\GC\KeepAliveRecur\KeepAliveRecur.output.txt\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\GC\API\GC\KeepAliveRecur\KeepAliveRecur.cmd\n\r\nExpected: True\r\nActual:   False
   at GC._API_GC_KeepAliveRecur_KeepAliveRecur_._API_GC_KeepAliveRecur_KeepAliveRecur_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x64_Release\GC\GC.XUnitWrapper.cs:line 2786

**Comment by JohnChen0** [comment]
Unable to repro this issue, and this test case is succeeding in recent GC Stress runs in CI.
