### ISSUE TITLE
TripleDESCryptoServiceProvider support

### ISSUE THREAD

**Issue by sadjadbp** [dotnet/coreclr#3769]
Hi, 

Any plans to support TripleDESCryptoServiceProvider under System.Security.Cryptograph

**Comment by morganbr** [comment]
Triple DES is supported via the TripleDES class (https://github.com/dotnet/corefx/blob/bd7aceca7da2301cd9bc720034870dd4e5fa08bf/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/TripleDES.cs). You can use TripleDES.Create() to get an instance.

cc: @bartonjs

**Comment by sergiy-k** [comment]
Hi @sadjadbp, I assume this can be closed now?

**Comment by sadjadbp** [comment]
Hi,

Thanks for the response.
