### ISSUE TITLE
Should coreclr for OS X be packaged as a bare .dylib or inside of a framework bundle?

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#377]
There are presumably benefits and drawbacks to either. I'm filing this issue for tracking and as a place to discuss the various options.

**Comment by pgavlin** [comment]
@kangaroo @sergiy-k FYI.

**Comment by richlander** [comment]
@migueldeicaza likely has an opinion on this. I believe that Mono and some parts of Xamarin uses the framework bundle approach.

**Comment by kangaroo** [comment]
.dylib please.  .framework's are intended to be shared, and my understanding is coreclr is meant to be app local.

**Comment by MattWhilden** [comment]
so it seems like .dylib is the way to go. I presume the current answer to "how is this packaged today?" is "it isn't"?

If that's the case we should just re-purpose this issue to track that work.

**Comment by ellismg** [comment]
It is already a dylib
