### ISSUE TITLE
Where is more sample demos for Linux/ARM?

### ISSUE THREAD

**Issue by leemgs** [dotnet/coreclr#3784]
After we displayed the simple console hello world a few days ago thanks to @benpye and @jkotas , we have successfully run Graphical Hello World that is released by Corefx Lab community as following:  
https://github.com/dotnet/corefxlab/tree/master/demos/CoreClrConsoleApplications/HelloWorld

We have attached screenshot; We have run the Graphical Hello world!!! on Linux/ARM Emulator (supporting both [1] hard-floating point based Loader and [2] soft-floating point based Loader) 

BTW, Where can we download more sample applications to evaluate more various C# codes?

#### Windows Logo 
![1458201888494](https://cloud.githubusercontent.com/assets/82404/13840119/b1978e64-ec63-11e5-94a8-a5a41070974d.jpeg)

#### Linux Logo 
![dotnet-hell-linux-graphic](https://cloud.githubusercontent.com/assets/82404/13840366/76eaf15a-ec65-11e5-9aab-78495835f5d0.jpg)

#### FreeBSD Logo
![dotnet-hello-freebsd-graphic](https://cloud.githubusercontent.com/assets/82404/13840504/367e0322-ec66-11e5-82e9-6099d4553042.jpg)

#### Mac Log
![dotnet-hello-mac-graphic](https://cloud.githubusercontent.com/assets/82404/13840512/4135f3b0-ec66-11e5-8ac0-ed3ab1e5e5fb.jpg)

**Comment by manu-silicon** [comment]
:+1: I'm also able to run this demo, however it crashes for me after pressing enter with the following trace:

```
 where
#0  0xb59e3a62 in ?? () from /usr/lib/arm-linux-gnueabihf/libunwind-arm.so.8
#1  0xb59e3f5e in _Uarm_is_signal_frame () from /usr/lib/arm-linux-gnueabihf/libunwind-arm.so.8
#2  0xb62c208c in PAL_VirtualUnwind (context=0xbe7fdf70, contextPointers=0x0)
    at /home/ubuntu/local/Microsoft/coreclr/src/pal/src/exception/seh-unwind.cpp:286
#3  0xb5bb5934 in Thread::VirtualUnwindToFirstManagedCallFrame (pContext=0xbe7fdf70)
    at /home/ubuntu/local/Microsoft/coreclr/src/vm/stackwalk.cpp:781
#4  0xb5d3bbb4 in DispatchManagedException (ex=...) at /home/ubuntu/local/Microsoft/coreclr/src/vm/exceptionhandling.cpp:4665
#5  0xb5f24414 in PreStubWorker (pTransitionBlock=0xbe7fe4d4, pMD=0xb515ccf0)
    at /home/ubuntu/local/Microsoft/coreclr/src/vm/prestub.cpp:1040
#6  0xb5d4e708 in ThePreStub () at asmhelpers.S:787
#7  0x00720064 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by manu-silicon** [comment]
The next logical step would be to run the CoreCLR test suite and try fixing tests to be in par with x64.

**Comment by leemgs** [comment]
>  I'm also able to run this demo, however it crashes for me after pressing enter with the following trace:

@manu-silicon ,  In my case, No crashes after pressing enter.  I have tested the graphical hello word.!!!  without any crashes at the below TestBeds. 
```
1) On our Linux/ARM Emulator
2) On Raspberry Pi2 Emulator 
3) On TM1 mobile device
4) On Samsung ARM ChreomeBook
```

**Comment by sergiy-k** [comment]
Hi @leemgs, I don't think we have many sample apps. I agree with @manu-silicon's suggestion to run CoreCLR tests as the next step.

**Comment by leemgs** [comment]
@sergiy-k, Now, there are seven demos in https://github.com/dotnet/corefxlab/tree/master/demos from CoreFXLab. Could not we currently get the more demo applicationa to make more robust .net core (e.g., CoreCLR + CoreFX) for Linux/ARM?

1. CoreClrConsoleApplications/HelloWorld
2. CoreService	
3. EchoService
4. LibuvWithNonAllocatingFormatters
5. LowAllocationWebServer	
6. QotdService	
7. dotnet

**Comment by janvorli** [comment]
@leemgs for making the .NET core on ARM more robust, I would recommend using the CoreCLR managed tests, which are in the src/tests subfolder of the source tree. There are about 6000 of them. They are focused on testing various parts of the runtime, including exception handling.
And once these work, you can move to CoreFX tests.
You can find a description on how to build and run the CoreCLR tests on Unix here:
https://github.com/dotnet/coreclr/blob/master/Documentation/building/unix-test-instructions.md

**Comment by manu-silicon** [comment]
@janvorli I just tried to run the test on arm, but I'm getting:
```
../src/pal/tests/palsuite/runpaltests.sh: line 129: /home/ubuntu/local/Microsoft/coreclr/bin/obj/Linux.arm.Debug/src/pal/tests/palsuite/c_runtime/fopen/test1/paltest_fopen_test1: No such file or directory
```

Indeed I do not have a tests folder under src/pal. What does it take to have it?

**Comment by manu-silicon** [comment]
@janvorli Nevermind, I had skipped the tests on my initial builds and forgot about it.

**Comment by synercoder** [comment]
@janvorli The test you mentioned are already being run and their progress is tracked on another thread: #3977

**Comment by synercoder** [comment]
As you apparently know since you already commented on that thread. :)
