### ISSUE TITLE
JIT should be packaged as a Nuget Package

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3788]
We should use this to determine how JIT gets consumed for RTM.

CC @cmckinsey @RussKeldorph @russellhadley

**Comment by pgavlin** [comment]
@gkhanna79 JIT packages are now being produced by the build. All that's left is signing and publishing. AFAIK that work is on your plate as part of the VSO build setup, so I'm assigning this issue to you for tracking.

cc @russellhadley

**Comment by gkhanna79** [comment]
The signing and publishing is being done as part of work @wtgodbe is doing. I think we can close this issue.
