### ISSUE TITLE
Enable Ready2Run generics support.

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3802]

**Comment by gkhanna79** [comment]
@JohnChen0 Assigning to you since you are doing/driving the work.

**Comment by DavidObando** [comment]
:eyes:

**Comment by gkhanna79** [comment]
@fadimounir @JohnChen0 Please link your PRs pertaining to the feature with this issue before we close it.

**Comment by gkhanna79** [comment]
Closing since completed! Cheers to @JohnChen0 @fadimounir and @jkotas :)

**Comment by JohnChen0** [comment]
For the record, here are the changes and bug fixes associated with this feature:
* #3735: Hashtable of types for R2R modules
* #4556: Ready-to-Run support for generic methods without generic dictionary
* #4738: Fix build break
* #4883: Fix CrossGen to skip some methods that require generic dictionary
* #4932: Fix contract violations in Ready to Run code
* #4945: JIT interface changes needed for upcoming shared generics
* #4519: Initial implementation of generic dictionary access for R2R (Supports TypeHandles on Windows x64 only)
* #5079: Implementation of method dictionary entry kinds for R2R shared generics
* #5052: Initial Ready-to-Run tests for generics
* #5122: Resolve two issues that cause pri1r2r test timeout on Ubuntu
