### ISSUE TITLE
Delegate.BeginInvoke/EndInvoke should throw PlatformNotSupportedException

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/coreclr#3811]
See discussion in dotnet/corert#1027.

https://github.com/dotnet/coreclr/blob/1a9eb1c5f4d9f257f3f96ef5205a0eb1a23395c3/src/vm/comdelegate.cpp#L2468

**Comment by adityamandaleeka** [comment]
Fixed by #4693
