### ISSUE TITLE
Schedule ARM64: First Class Structs

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3816]
Area: ABI
Estimate: 4 weeks

**Comment by russellhadley** [comment]
@CarolEidt this is the tracking item for the first class struct work.  Estimate is still a bit rough.  Do you have a better idea when this work might land?  For context #3819 is the tracking issue for the RA work and #3817 is the item for doing the decomposition step in lower.

**Comment by BruceForstall** [comment]
@CarolEidt Looks like this can be closed?

**Comment by CarolEidt** [comment]
@BruceForstall Yes, I think this can be closed.
