### ISSUE TITLE
Schedule ARM64: LSRA support for 16 byte structs

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3819]
Area: LSRA
Estimate: 2 weeks

**Comment by russellhadley** [comment]
@RussKeldorph @sivarv This item tracks the work needed in the the LSRA for 16 byte structs on ARM64.  @sivarv is this on your near term schedule?  Should I assign it to you?

**Comment by sivarv** [comment]
Closing this work item as we have tackled this work item by decomposing 16-byte structs into two 8-bytes.
