### ISSUE TITLE
WaitHandle.WaitAll: exception not caught on Windows x86 Release

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/coreclr#3832]
The tests 'baseservices/threading/waithandle/waitall/waitallex8' and 'waitallex8a' are failing on x86 Release (both for the same reason), and it may be a real runtime bug.

The tests do the following:

```c#
        try
        {
            WaitHandle.WaitAll(wh);
        }
        catch(ArgumentException)
        {
            ...
        }
        catch(Exception e)
        {
            ...
        }
```
and we crash with `Unhandled Exception: System.ArgumentException: Value does not fall within the expected range.`

I looked at `CorWaitMultipleNative` and its callees, and the source of the exception is in `Thread::DoAppropriateWaitWorker` (vm/threads.cpp, near line 4495):

```c++
    if (ret == WAIT_FAILED)
    {
        DWORD errorCode = ::GetLastError();
        if (errorCode == ERROR_INVALID_PARAMETER)
        {
            if (CheckForDuplicateHandles(countHandles, handles))
                COMPlusThrow(kDuplicateWaitObjectException);
            else
                COMPlusThrowHR(HRESULT_FROM_WIN32(errorCode));  /////// <--------- here is where we throw
        }
```

The thrown exception appears to be handled properly on everything except x86 release. I haven't looked into all the exception handling code (and the macros we use for catching exceptions in these calls) to understand why this is occurring yet.

**Comment by janvorli** [comment]
Fixed by #3873
