### ISSUE TITLE
Dynamic Code Generation accepts invalid Mul (?)

### ISSUE THREAD

**Issue by damageboy** [dotnet/coreclr#3834]
Hi,
I originally opened this bug for the mono team for what I thought was an error in Mono:
https://bugzilla.xamarin.com/show_bug.cgi?id=39775

The issue seems to be the DynamicMethod.CreateDelegate will accept the following stream of MSIL
(This is obviously pseudo code, here for clarity):

```
.locals init (
	[0] int32,
	[1] float64,
)
IL_0000: ldloc.0  // This is of type int32
IL_0001: ldloc.1 // This is of type Double
IL_0002: mul
```

And happily compile it.

Here is a sample program the compiles cleanly in CoreCLR / MS.NET (Note this is also a bug in the "standard .NET" distribution):
https://gist.github.com/damageboy/887a87b14bc3eb5f2212

The CIL spec clearly disallows this:
http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf
(Page 302, Table III.2: Binary Numeric Operations)

I've copy-pasted the table for reference:
![image](https://cloud.githubusercontent.com/assets/125730/13903851/93474c74-ee93-11e5-8477-158464c02551.png)

As you can see, any operation between different types, is generally disallowed according to the spec...

I've checked the program compiled and runs to completion on both MS.NET 4.6.x and CoreCLR `1.0.0-beta-001598`.

This is of course undesired behavior as the program should (?) report invalid MSIL being constructed, as other illegal MSIL streams often do in DynamicMethods...

**Comment by mikedn** [comment]
> the program should (?) report invalid MSIL being constructed

The ECMA spec doesn't have such a requirement:

> III.1.8 ... The operation of CIL sequences that do not meet the CIL correctness requirements is unspecified.

**Comment by m0sa** [comment]
If you want verification of IL, try [Sigil](https://github.com/kevin-montrose/Sigil)

**Comment by damageboy** [comment]
@m0sh I was just thinking about using Sigil irregardless, thanks for the reminder.

@m0sa I don't mind that, but isn't this kind of a potential security issue?

I mean, accepting undefined MSIL could potentially lead to generating code that could crash the program, or worse than that, generate native code that could be abused for malicious intentions, no?

I didn't know Microsoft was so relaxed about invalid MSIL, I still remember stuff like this:
https://technet.microsoft.com/library/security/ms10-077

Which, to me, sounds related (at least in spirit) to the type of code that undefined MSIL could potentially generate.

Anyway, I'd love for someone from CoreCLR/MS to explain the rational of not checking this in a more strict way...

**Comment by mikedn** [comment]
> I don't mind that, but isn't this kind of a potential security issue?

I haven't tried but given how the JIT code looks I would expect your code to fail to run if verification is enabled. In your case verification is probably disabled and then the security aspect is irrelevant.

**Comment by damageboy** [comment]
I don't remember turning it off by force in any way,  the code snippet I
provided is pretty plain vanilla,  as you can see for yourself...

I verification on by default?

**Comment by mikedn** [comment]
> I verification on by default?

Not really. It's on by default only in low/partial trust scenarios and those are kind of rare these days.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
Feel free to re-open if you don't consider this answered.
