### ISSUE TITLE
What are the Linux runtime dependencies?

### ISSUE THREAD

**Issue by ctaggart** [dotnet/coreclr#3835]
The build toolchain dependencies are documented at https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md. Which of those dependencies are runtime dependencies?

I currently install all of them:
```
apt-get -q -y install cmake llvm-3.5 clang-3.5 lldb-3.6 lldb-3.6-dev libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev
```
but I'd like to trim it down if some are not needed at runtime.

1. cmake 
2. llvm-3.5 
3. clang-3.5 
4. lldb-3.6
5. lldb-3.6-dev
6. libunwind8 
7. libunwind8-dev 
8. gettext libicu-dev 
9. liblttng-ust-dev 
10. libcurl4-openssl-dev 
11. libssl-dev 
12. uuid-dev

**Comment by shahid-pk** [comment]
lldb , clang . llvm , cmake are all not required at runtime.

**Comment by jkotas** [comment]
https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/docker/ubuntu/Dockerfile has list broken down to what are the CoreCLR dependencies vs. build env dependencies.

**Comment by ctaggart** [comment]
@shahid-pk Are you sure `lldb` isn't required? The reason I ask is because the `dotnet-sharedframework-ubuntu-x64.latest.deb` package lists `liblldb-3.6` as dependency. 

```
ar p dotnet-sharedframework-ubuntu-x64.latest.deb control.tar.gz | tar xzf - ./control -O | grep Depends:
Depends: libc6 (>= 2.14), libcurl3 (>= 7.28.0), libgcc1 (>= 1:4.1.1), libgssapi-krb5-2 (>= 1.10+dfsg~), libicu52 (>= 52~m1-1~), liblldb-3.6, liblttng-ust0, libssl1.0.0 (>= 1.0.1), libstdc++6 (>= 4.8), libunwind8, libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4), dotnet-host
```

**Comment by shahid-pk** [comment]
lldb is required for debugging , so yes for development it is required But i don't think it is required for anything else.

**Comment by adityamandaleeka** [comment]
Sounds like this has been answered, so I'm closing the issue. Please reopen if necessary.
