### ISSUE TITLE
TypeLoadException without any type information

### ISSUE THREAD

**Issue by rolfik** [dotnet/coreclr#3836]
I am working on new UWP application using .net core libraries generated from xprojs.

Recently after some more changes I have got stuck with TypeLoadException without any information about type being loaded while debugging.

See the attached image for more details:

![epos - typeloadexception with no type info](https://cloud.githubusercontent.com/assets/4658651/13914302/b6c41ed8-ef4d-11e5-9499-eb12ef8916f2.png)

How can I troubleshoot it?

**Comment by rolfik** [comment]
After more investigation I have found the cause:

My main control set as content of UWP main window is this shell user control:

    public abstract class ShellBase :
        UserControl,
        IViewOf<ShellViewModel>
    {
        public ShellViewModel Model
        {
            get { return DataContext as ShellViewModel; }
            internal set { DataContext = value; }
        }
        IViewModel IView.Model
        {
            get { return Model; }
        }
    }

    public sealed partial class Shell :
        ShellBase
    { ... }

and the `IViewOf` is:

    public interface IView
    {
        IViewModel Model { get; }
    }

    public interface IViewOf<out T> :
        IView
        where T : IViewModel
    {
        new T Model { get; }
    }

and the problem is `out` qualifier in `IViewOf<out T>`. When removed the TypeLoadException disappears.

**Comment by MattWhilden** [comment]
It sounds like you're unblocked but if you'd be able to help us out a bit I'd love to figure out what's going on here. Is there any difference in RELEASE or DEBUG for this case? If the problem only manifests itself in RELEASE then it may be a bug in the .NET Native runtime or compiler and we'd need to get a different set of folks to investigate it.

**Comment by rolfik** [comment]
I have managed to reproduce the problem in stripped down version of my current application (Epos.TypeLoadException/UWP solution), but not in minimalistic sample one (TypeLoadExceptionMinimalCase solution).

See:
[TypeLoadException.zip](https://github.com/dotnet/coreclr/files/185745/TypeLoadException.zip)

**Comment by sergiy-k** [comment]
cc @gkhanna79, @fadimounir

**Comment by fadimounir** [comment]
@rolfik I'm no longer able to reproduce this issue with the latest netcore runtime (3.0 Preview 5). It could have been fixed sometime along the way. Not sure which PR fixed this issue. Closing for now.
