### ISSUE TITLE
dotnet core does not run on elementary OS ubuntu 14.04 based

### ISSUE THREAD

**Issue by luisgarciaalanis** [dotnet/coreclr#3837]
Elementary OS Freya is ubunut 14.04 based, and it even uses ubuntu's repositories.

is there a way to tell the runtime to treat is as ubuntu 14.04?

dotnet restore
log  : Restoring packages for /home/luis/src/web/dotnet/test/project.json...
error: Microsoft.Win32.Primitives 4.0.1-rc2-23901 provides a compile-time reference assembly for Microsoft.Win32.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.AppContext 4.1.0-rc2-23901 provides a compile-time reference assembly for System.AppContext on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Collections 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Collections on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Console 4.0.0-rc2-23901 provides a compile-time reference assembly for System.Console on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Diagnostics.Debug 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Diagnostics.Debug on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Diagnostics.Tools 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Diagnostics.Tools on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Diagnostics.Tracing 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Diagnostics.Tracing on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Globalization 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Globalization on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Globalization.Calendars 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Globalization.Calendars on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.IO 4.1.0-rc2-23901 provides a compile-time reference assembly for System.IO on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.IO.FileSystem 4.0.1-rc2-23901 provides a compile-time reference assembly for System.IO.FileSystem on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Net.Primitives 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Net.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Net.Sockets 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Net.Sockets on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Reflection 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Reflection on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Reflection.Extensions 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Reflection.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Reflection.Primitives 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Reflection.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Reflection.TypeExtensions 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Reflection.TypeExtensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Resources.ResourceManager 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Resources.ResourceManager on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Runtime 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Runtime on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Runtime.Extensions 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Runtime.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Runtime.Handles 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Runtime.Handles on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Runtime.InteropServices 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Runtime.InteropServices on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-23901 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Text.Encoding 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Text.Encoding on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Text.Encoding.Extensions 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Text.Encoding.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Threading.Tasks 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Threading.Tasks on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: System.Threading.Timer 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Threading.Timer on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
error: Some packages are not compatible with .NETStandardApp,Version=v1.5 (elementary os.0.3.2-x64).
info : Committing restore...
log  : Restore failed in 903ms.

Errors in /home/luis/src/web/dotnet/test/project.json
    Microsoft.Win32.Primitives 4.0.1-rc2-23901 provides a compile-time reference assembly for Microsoft.Win32.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.AppContext 4.1.0-rc2-23901 provides a compile-time reference assembly for System.AppContext on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Collections 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Collections on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Console 4.0.0-rc2-23901 provides a compile-time reference assembly for System.Console on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Diagnostics.Debug 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Diagnostics.Debug on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Diagnostics.Tools 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Diagnostics.Tools on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Diagnostics.Tracing 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Diagnostics.Tracing on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Globalization 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Globalization on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Globalization.Calendars 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Globalization.Calendars on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.IO 4.1.0-rc2-23901 provides a compile-time reference assembly for System.IO on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.IO.FileSystem 4.0.1-rc2-23901 provides a compile-time reference assembly for System.IO.FileSystem on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Net.Primitives 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Net.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Net.Sockets 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Net.Sockets on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Reflection 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Reflection on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Reflection.Extensions 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Reflection.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Reflection.Primitives 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Reflection.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Reflection.TypeExtensions 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Reflection.TypeExtensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Resources.ResourceManager 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Resources.ResourceManager on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Runtime 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Runtime on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Runtime.Extensions 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Runtime.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Runtime.Handles 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Runtime.Handles on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Runtime.InteropServices 4.1.0-rc2-23901 provides a compile-time reference assembly for System.Runtime.InteropServices on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-23901 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Text.Encoding 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Text.Encoding on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Text.Encoding.Extensions 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Text.Encoding.Extensions on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Threading.Tasks 4.0.11-rc2-23901 provides a compile-time reference assembly for System.Threading.Tasks on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    System.Threading.Timer 4.0.1-rc2-23901 provides a compile-time reference assembly for System.Threading.Timer on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with elementary os.0.3.2-x64.
    Some packages are not compatible with .NETStandardApp,Version=v1.5 (elementary os.0.3.2-x64).

**Comment by ellismg** [comment]
@piotrpMSFT Is there a way to tell CLI to use a different RID during restore and deployment?

**Comment by piotrpMSFT** [comment]
you can pass -r [--runtime] to specify the RID desired.

**Comment by JCKodel** [comment]
-r WHAT?

Which runtime we must use in this case?

**Comment by piotrpMSFT** [comment]
Things have changed a bit since March :) Add the following snippet as a peer to `frameworks` in your project.json:

````
  "runtimes": {
    "ubuntu.14.04-x64": {}
  }
````

Now do the following:
1. `dotnet restore`
2. `dotnet publish -r ubuntu.14.04-x64

The published output, under the bin directory, will now include an ubuntu host along with your application.

**Comment by adityamandaleeka** [comment]
@piotrpMSFT Can this issue be closed?

**Comment by piotrpMSFT** [comment]
I have no issue with closing it. @luisgarciaalanis seems to be unblocked.

**Comment by MirzaD** [comment]
If someone still has there problems here is a workaround.

Modify /etc/os-release to look someting like:
`NAME="Ubuntu"
VERSION="14.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"`

Just make sure to backup the original file first.

**Comment by janvorli** [comment]
Issue moved to [dotnet/cli #7246](https://github.com/dotnet/cli/issues/7246) via [**ZenHub**](https://www.zenhub.com/)
