### ISSUE TITLE
Arm64: Test run start fails

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3844]
@jashook Can you please take a look?

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_windows_nt/49/consoleFull

**Comment by jashook** [comment]
Ya I noticed this this morning. It should be up and running now but I need to figure out why this happened.

**Comment by jashook** [comment]
Fixed with Kyungwoo's changes to the CI.
