### ISSUE TITLE
"build.cmd clean" has unrecognized option

### ISSUE THREAD

**Issue by krk** [dotnet/coreclr#385]
mscorlib build failing on Windows 8.1.

```CSC : error CS2007: Unrecognized option: '/test:moduleName=CommonLanguageRuntimeLibrary' [C:\coreclr\src\mscorlib\mscorlib.cs
proj]```

**Comment by leppie** [comment]
This is not only for clean. It happens on my system too. I have never heard of the test option, and considering it is used when `$(UseRoslynCompiler)'!='true'`, it looks like this scenario has never been tested.

**Comment by leppie** [comment]
I found out why this is happening.

There are leftovers from VS Express installations in `AppData\Local\Microsoft`.

Just delete all the `XXExpress` directories and the build will work fine.

**Comment by krk** [comment]
I have checked and I do not have any folders named *Express in %AppData%\Local\Microsoft

**Comment by leppie** [comment]
Do you perhaps have a Roslyn extension installed for VS2013? It may be that it is outdated. Also look in process explorer to see if `VBCSCompiler.exe` (I think that was the name) process is running. That is what pointed me to the VS extension issue.

**Comment by krk** [comment]
Indeed, I have the Roslyn extension for VS2013.

**Comment by krk** [comment]
Unrecognized option is added in ```\coreclr\src\mscorlib\GenerateCompilerResponseFile.targets:13```

Relevant part of the file is here:

```xml
<!-- When Roslyn is NOT enabled, we need to set the module name for mscorlib -->
<WriteLinesToFile Condition="'$(UseRoslynCompiler)'!='true'"
				  File="$(IntermediateOutputPath)\moduleName.rsp"
				  Lines="/test:moduleName=CommonLanguageRuntimeLibrary"
				  Overwrite="true" />

<!-- When Roslyn is enabled we need to set the runtimemetadataversion -->
<WriteLinesToFile Condition="'$(UseRoslynCompiler)'=='true'"
				  File="$(IntermediateOutputPath)\moduleName.rsp"
				  Lines="/runtimemetadataversion:v4.0.30319"
				  Overwrite="true" />
```

**Comment by rkeithhill** [comment]
So on Windows does this mean we need Roslyn i.e. VS 2015 to compile CoreClr?  I have only VS 2013 with no Roslyn integration and I'm getting this error as well.

**Comment by DickvdBrink** [comment]
Same here, I was able to build it using another system with VS 2015 though (with lots of hacks)

**Comment by gkhanna79** [comment]
@tarekgh Can you please take a  look?

**Comment by tarekgh** [comment]
I think this is a typo in the targets files and meant to be /reference and not /test. anyway will try to repro it and fix it.

**Comment by weshaggard** [comment]
No the /test option is an option that is needed for the old native csc.exe compiler while building mscorlib.

The root issue here is that we don't have any good way to detect if we are compiling with Roslyn or not. The best I think we can do is to offer a workaround of setting "UseRosylnCompiler=true" for cases were the compiler is known to be Roslyn (i.e. VS 2015 or Roslyn extensions). I think a lot of our build scripts already do set this.

**Comment by weshaggard** [comment]
cc @AlexGhiondea it also looks like we are not settng the module name to CommonLanguageRuntimeLibrary when compiling with Roslyn. We should consider doing that.

**Comment by tarekgh** [comment]
assigned the issue to @AlexGhiondea  as he has more context. also I couldn't get the issue repro even compiling with VS2013

**Comment by jkotas** [comment]
This issue was specific to VS2013. The minimum VS version to build the repo is VS2015 now.
