### ISSUE TITLE
CentOS debug/release master builds aren't happening

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#3860]
Note that there's only two builds here:
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/release_centos7.1/
and they're ones I manually kicked off, one from two weeks ago and one from today.

In contrast there's a build here for each set of changes to master:
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/release_ubuntu/

**Comment by wtgodbe** [comment]
This is intentional - I only enabled per-commit CentOS test suites in the CI recentl, and decided to start with just Checked so as not to add too much additional stress to the lab machines. If @mmitche thinks it's alright I can enable Release & Debug as well.

**Comment by stephentoub** [comment]
Thanks. If we're going to start with anything it should be release, as corefx has a dependency on that, pulling the latest successful coreclr release build for a platform when running tests on a platform.

**Comment by wtgodbe** [comment]
Gotcha. I have a meeting in 10, I'll put up a PR after that.

**Comment by stephentoub** [comment]
Thanks.  It doesn't necessarily have to be per-commit... if we were really concerned about lab stress, we could do it nightly or something, though I think it makes sense to be consistent with the other unix builds.  We could also consider changing corefx to use a checked build instead of release, but againI think it makes sense to be consistent.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/3866 should resolve this.
