### ISSUE TITLE
Pin managed objects pointed to by nonvolatile registers stored on stack

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#387]
Currently managed objects pointed to by nonvolatile registers are not pinned and so GC needs to update the values of these registers stored on the stack when it moves the respective objects. 
This requires that the native code unwinding is able to provide context pointers pointing to the locations of those registers on the stack. 
While the current libunwind that we are using on Linux provides support for getting these pointers, the native libunwind on OSX doesn't provide such support.
A way to solve this issue is to remove the need for the context pointers. If we ensure that managed objects that are pointed to by nonvolatile registers stored on stack are always pinned, the address of the objects will not change and so GC doesn't need to update the registers stored on the stack.

**Comment by kangaroo** [comment]
@janvorli I had some questions about the performance implications of this.  I would hazard a guess that the majority of times an object was pointed to by a nonvol reg, that it would be pointing to a nursery object.  Pinning those will certainly have a non-zero cost -- no?

**Comment by Maoni0** [comment]
If it's indeed to nursery objects, let's say it points to a gen0 object and when the next gen0 GC happens it's no longer pinned, then yes the cost completely doesn't exist.

The part I can't be confident about is if the *majority* falls into this case; and when it doesn't fall into this case how long the object will be pinned. Someone from the JIT team can comment better. @BruceForstall ?

**Comment by janvorli** [comment]
Implemented by #465

**Comment by jkotas** [comment]
The fix essentially implemented partially-conservative GC. Yes, the pinning will have non-zero cost. I expect it to be within noise because of it should be rare.

**Comment by janvorli** [comment]
I've forgotten about one more place which needs to be modified to handle the context pointer being NULL - the `ExceptionTracker::UpdateNonvolatileRegisters`. I'm going to fix it.
@kangaroo FYI
