### ISSUE TITLE
Add a configuration mechanism for runtime properties

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/coreclr#3884]
Enable the configuration of runtime options (such as whether server GC is enabled or the value for MinThreads for the ThreadPool worker pool) to be performed through key-value pairs passed in by hosts (see https://github.com/dotnet/cli/pull/1987 for an example of how dotnet/cli would use this), and provide a sane way for callers to query for the values of those properties.

**Comment by sergiy-k** [comment]
LGTM

**Comment by sergiy-k** [comment]
Fixed by PR https://github.com/dotnet/coreclr/pull/3950
