### ISSUE TITLE
Two versions of mscorlib.txt?

### ISSUE THREAD

**Issue by svick** [dotnet/coreclr#39]
There seem to be two different versions of mscorlib.txt in the repo: [src/mscorlib/mscorlib.txt](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/mscorlib.txt) and [src/mscorlib/src/mscorlib.txt](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/mscorlib.txt).

Is there any reason for that?

**Comment by AlexGhiondea** [comment]
The one outside the src folder is not needed. I will clean that up.

**Comment by AlexGhiondea** [comment]
This was merged in with PR #46.
