### ISSUE TITLE
Stack unwinder for producing stack traces on unhandled exceptions should parse portable PDB for line number info

### ISSUE THREAD

**Issue by agocke** [dotnet/coreclr#3906]

**Comment by sergiy-k** [comment]
cc @tzwlai

**Comment by mikem8361** [comment]
Implemented with PR #5078 and #8670

**Comment by petrsorfa** [comment]
Hi, could I potentially help out here? I have a strong background in Debugging as I used to maintain the Unixware debugger and was involved in the DWARF standard.

**Comment by mikem8361** [comment]
Thanks for the offer, but this issue has already been done.  It involved supporting the new PortablePDB format symbol file for managed assemblies in the runtimes unhandled exception stack trace (and SOS).

**Comment by petrsorfa** [comment]
Thanks for the update. Let me know I can help out anywhere (even outside of Debug specific stuff).
