### ISSUE TITLE
sigsegv_handler hangs if the underlying access violation is in the heap

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#3912]
I don't have a nice trivial repro all cooked up, but this should work:

1. Have a managed app/native app that loads CoreCLR
2. Have a bug somewhere in the app that corrupts the heap
3. Try and call free

Expected:
App should crash

Actual:
Dead lock in the PAL. The problem is that heap functions aren't signal-safe, and so we get a dead lock here:

      libc.so.6!__lll_lock_wait_private()
      libc.so.6!_L_lock_12779
      libc.so.6!__GI___libc_malloc(size_t bytes=32)
      libpthread.so.0!pthread_getattr_np(pthread_t thread_id=139974527678208, pthread_attr_t * attr=0x7f4e5bffdc60)
      libcoreclr.so!CorUnix::CPalThread::GetStackLimit()
      libcoreclr.so!sigsegv_handler(int code=11, siginfo_t * siginfo=0x7f4e5bffe430, void * context=0x7f4e5bffe300)

The stack of the 'free' call that hit the deadlock in my case was:

 	libc.so.6!malloc_consolidate(mstate av, mstate av@entry) Line 4149	C
 	libc.so.6!_int_free(mstate av, mchunkptr p, int have_lock) Line 4057	C
	libcoreclr.so!HeapFree(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem) Line 293	C++

**Comment by janvorli** [comment]
Fixed by #4330
