### ISSUE TITLE
PAL WCHAR definition is wrong under PAL_STDCPP_COMPAT

### ISSUE THREAD

**Issue by jamesallen426** [dotnet/coreclr#3922]
Currently the definition lies in ```pal_mstypes.h``` line [606](https://github.com/dotnet/coreclr/blob/release/1.0.0-rc2/src/pal/inc/pal_mstypes.h#L606) and [610](https://github.com/dotnet/coreclr/blob/release/1.0.0-rc2/src/pal/inc/pal_mstypes.h#L606):
```c++
#ifdef PAL_STDCPP_COMPAT
...
typedef char16_t WCHAR;

#else // PAL_STDCPP_COMPAT

typedef wchar_t WCHAR;
...
#endif // PAL_STDCPP_COMPAT
```

But when ```PAL_STDCPP_COMPAT``` is defined I'm expecting PAL headers to be compatible with system headers, which requires ```wchar_t```  instead of ```char16_t```.
So in my opinion the two typedef's should be switched.
Am I getting some wrong idea towards the ```PAL_STDCPP_COMPAT``` switch?

**Comment by jkotas** [comment]
The PAL always matches the width of Windows-specific types (the upper case ones) to the width on native Windows. E.g.:

- `WCHAR` is 16-bit type on Windows, so PAL always defines it as 16-bit. Even though `wchar_t` may be 32-bit type.
- `LONG` is 32-bit type on Windows, so PAL always defines it as 32-bit. Even though `long` may be 64-bit type.

These approach worked best for the CoreCLR codebase.

**Comment by jamesallen426** [comment]
Thanks for the clarification
