### ISSUE TITLE
Setup-Runtime-Dependencies must pull coredistools for the correct architecture

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#3925]
after doping a "dotnet restore" the runtest script copies over any coredistools libarary available in the packages directory to the overlay directory.
https://github.com/dotnet/coreclr/blob/master/tests/setup-runtime-dependencies.cmd#L92 
https://github.com/dotnet/coreclr/blob/master/tests/setup-runtime-dependencies.sh#L129

But it should actually copy the libraries corresponding to the target architecture.

**Comment by swaroop-sridhar** [comment]
@sejongoh, I think for windows this can be achieved by changing 

https://github.com/dotnet/coreclr/blob/master/tests/setup-runtime-dependencies.sh#L129 to 
`FOR /F "delims=" %%i IN ('dir %__PackageDir%\runtime.win7-%__BuildArch%.Microsoft.NETCore.CoreDisTools\coredistools.dll /b/s') DO set __LibPath=%%i`

For linux, __BuildArch is not available in the runtime.sh script, so it'll require some more wiring.
`

**Comment by sejongoh** [comment]
@swaroop-sridhar Does dotnet restore downloads multiple dlls? It downloaded only one dll for a current runtime. Is it changed now?

**Comment by swaroop-sridhar** [comment]
@sejongoh looks like the restore script restored both X86 and x64 versions:
```
15:49:49 "D:\j\workspace\x64_checked_w---e32b5c4f\tests\..\Tools\dotnetcli\bin\dotnet.exe" restore "C:\Users\DOTNET~1\AppData\Local\Temp\coreclr_gcstress_13618\project.json" --source https://dotnet.myget.org/F/dotnet-core/ --packages "D:\j\workspace\x64_checked_w---e32b5c4f\tests\..\Packages"
15:49:49 log  : Restoring packages for C:\Users\dotnet-bot\AppData\Local\Temp\coreclr_gcstress_13618\project.json...
15:49:50 info :   GET https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='Microsoft.NETCore.CoreDisTools'
15:49:50 info :   OK https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='Microsoft.NETCore.CoreDisTools' 414ms
15:49:50 info :   GET https://dotnet.myget.org/F/dotnet-core/api/v2/package/Microsoft.NETCore.CoreDisTools/1.0.1-prerelease-00001
15:49:51 info :   OK https://dotnet.myget.org/F/dotnet-core/api/v2/package/Microsoft.NETCore.CoreDisTools/1.0.1-prerelease-00001 530ms
15:49:51 log  : Installing Microsoft.NETCore.CoreDisTools 1.0.1-prerelease-00001.
15:49:51 info :   GET https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.win7-x64.Microsoft.NETCore.CoreDisTools'
15:49:51 info :   GET https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.win7-x86.Microsoft.NETCore.CoreDisTools'
15:49:51 info :   OK https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.win7-x64.Microsoft.NETCore.CoreDisTools' 81ms
15:49:51 info :   GET https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.win7-x64.Microsoft.NETCore.CoreDisTools/1.0.1-prerelease-00001
15:49:51 info :   OK https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='runtime.win7-x86.Microsoft.NETCore.CoreDisTools' 246ms
15:49:51 info :   OK https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.win7-x64.Microsoft.NETCore.CoreDisTools/1.0.1-prerelease-00001 159ms
15:49:51 info :   GET https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.win7-x86.Microsoft.NETCore.CoreDisTools/1.0.1-prerelease-00001
15:49:51 info :   OK https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.win7-x86.Microsoft.NETCore.CoreDisTools/1.0.1-prerelease-00001 96ms
15:49:54 log  : Installing runtime.win7-x86.Microsoft.NETCore.CoreDisTools 1.0.1-prerelease-00001.
15:50:11 log  : Installing runtime.win7-x64.Microsoft.NETCore.CoreDisTools 1.0.1-prerelease-00001.
15:50:11 info : Committing restore...
15:50:11 log  : C:\Users\DOTNET~1\AppData\Local\Temp\coreclr_gcstress_13618\project.json
15:50:11 log  : Restore completed in 4688ms.
```

**Comment by swaroop-sridhar** [comment]
@sejongoh I think the script should be fixed to copy the correct DLL regardless of the above restore issue, because when running `runtest.cmd` locally, we may have packages for multiple architectures restored in the same directory.

**Comment by sejongoh** [comment]
@swaroop-sridhar Thanks for explanation. The script originally queried runtime information and used it, but I removed it since dotnet restore was updated to automatically find it. It looks like we need this again to handle the problems you mentioned above. I will update the scripts.

**Comment by sejongoh** [comment]
@swaroop-sridhar We can get runtime id like below and use it. We can do a similar thing for Windows. If you are urgent, please go ahead.

rid=\`$dotnetCmd --version | grep 'Runtime Id:' | sed 's/^ *Runtime Id: *//g'\`
		
bash -c -x "$dotnetCmd restore $jsonFilePath --source https://dotnet.myget.org/F/dotnet-core/ --packages $packageDir --runtime $rid"	

libPath=\`find $packageDir | grep $rid | grep -m 1 libcoredistools\`

**Comment by sejongoh** [comment]
The scripts were updated.
