### ISSUE TITLE
Invalid branching generated by ildasm

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/coreclr#3927]
I've being playing with ildasm on Unix (although I do not think it matters Windows or Unix) to generate some IL from an existing assembly, then assembling it with ilasm where the later would crash. So I went over to Windows and ran ildasm (from the official Microsoft .NET delivery) on the same assembly. When I compared the generated IL, I was surprised to see that all branchings are wrong by an offset of 0x0100.

For example I would see:
```
brtrue.s IL_0111
```
when
```
brtrue.s IL_0011
```
is expected. The CoreCLR ildasm branching is definitely wrong especially when IL_0111 does not exist as the method goes up to IL_005a in this particular case.

I did not look for the root cause of this, but filling the issue to not forget about it.

**Comment by sergiy-k** [comment]
cc @RussKeldorph

**Comment by RussKeldorph** [comment]
@kyulee1 Could you assess impact for triage?

**Comment by kyulee1** [comment]
@manu-silicon Can you provide a repro?

**Comment by manu-silicon** [comment]
@kyulee1 I'll try to reproduce it on a smaller assembly over the week-end and send it.

**Comment by manu-silicon** [comment]
I must had have some stalled changes somewhere as I'm not able to reproduce this at all. A typical code that had the branchign was:

```
 internal void DestroyAllSoundInstances()
        {
            foreach (var instance in instances)
            {
                instance.ToLower();
            }
            instances.Clear();
        }

        private readonly HashSet<string> instances = new HashSet<string>();
```

I'm closing this. However I still have the crash on trying to generate the assembly from the IL on the ```ilasm``` side. I'll fill a report once I found out which piece is causing the failure.
