### ISSUE TITLE
Threading Interlocked Failures

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3938]
Repro steps:

1) Build.cmd Release x86 skiptests
2) Download the latest build of runtimes.Win7-x86.Microsoft.NETCore.Runtime.CoreCLR packageand replace the contents of bin\product\WindowsNT.x86_Release with the package contents.
2) tests\buildtest.cmd Release x86 priority 1
3) tests\runtest.cmd x86Release

baseservices._threading_interlocked_add_InterlockedAddLongWithSubtract_InterlockedAddLongWithSubtract_._threading_interlocked_add_InterlockedAddLongWithSubtract_InterlockedAddLongWithSubtract_cmd
cmdLine:C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\baseservices\threading\interlocked\add\InterlockedAddLongWithSubtract\InterlockedAddLongWithSubtract.cmd Timed Out\r\n\n\nReturn code:      -100\nRaw output file:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Reports\baseservices\threading\interlocked\add\InterlockedAddLongWithSubtract\InterlockedAddLongWithSubtract.output.txt\nRaw output:\nBEGIN EXECUTION\r\n "C:\Github\gkhanna79\coreclr\tests\..\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\corerun.exe" InterlockedAddLongWithSubtract.exe /loops:500000 /addVal:1  \r\nExpected: 0\r\nActual:   0\r\nTest Passed\r\nExpected: 100\r\nActual: 100\r\nEND EXECUTION - PASSED\r\nPASSED\r\ncmdLine:C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\baseservices\threading\interlocked\add\InterlockedAddLongWithSubtract\InterlockedAddLongWithSubtract.cmd Timed Out\r\nTest Harness Exitcode is : -100\r\n\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\baseservices\threading\interlocked\add\InterlockedAddLongWithSubtract\InterlockedAddLongWithSubtract.cmd\n\r\nExpected: True\r\nActual:   False
   at baseservices._threading_interlocked_add_InterlockedAddLongWithSubtract_InterlockedAddLongWithSubtract_._threading_interlocked_add_InterlockedAddLongWithSubtract_InterlockedAddLongWithSubtract_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x86_Release\baseservices\baseservices.XUnitWrapper.cs:line 22116

**Comment by adityamandaleeka** [comment]
This is the same issue as described in this comment: https://github.com/dotnet/coreclr/issues/3937#issuecomment-217296974
