### ISSUE TITLE
String.Format  Unit Tests?

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/coreclr#3951]
Where can I find the unit test for String Formats?
`String.Format( )` and `.ToString( )`

**Comment by akoeplinger** [comment]
A quick search revealed these, maybe there are more somewhere else:
- https://github.com/dotnet/corefx/blob/eb7f20165401267af4329253fa31b45d279ebd84/src/System.Runtime/tests/System/String.cs#L846
- https://github.com/dotnet/coreclr/blob/master/tests/src/CoreMangLib/cti/system/string/stringformat1.cs
- https://github.com/dotnet/coreclr/blob/master/tests/src/CoreMangLib/cti/system/string/stringformat2.cs

**Comment by AdamSpeight2008** [comment]
@akoeplinger Thank You, I'll check those out later.

**Comment by hughbe** [comment]
Most of them are in https://github.com/dotnet/corefx/blob/eb7f20165401267af4329253fa31b45d279ebd84/src/System.Runtime/tests/System/Text/StringBuilder.cs as well (string uses a string builder in the implementation of string.format)

**Comment by AdamSpeight2008** [comment]
@hughbe Thank You.
That should help a lot.

**Comment by sergiy-k** [comment]
The issue seems to be resolved. Closing.
