### ISSUE TITLE
CORINFO_METHOD_INFO->scope is unique value for each process ?

### ISSUE THREAD

**Issue by danysu** [dotnet/coreclr#3952]
Hi,
The `CORINFO_METHOD_INFO->scope` always return unique value for each process ? I noticed that sometimes the value changes, Which variable returns unique value for each process ?

**Comment by jkotas** [comment]
None of the handles on JIT-EE interface are meant to be unique for each process.

**Comment by BruceForstall** [comment]
stale;closing
