### ISSUE TITLE
tests/src/JIT/SIMD/CircleInConvex.cs failure

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#3964]
Test returns 0 on x86.  I suspect the problem is the epsilon check here

  https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/SIMD/CircleInConvex.cs#L263

The inequality operator appears to be reversed.  The test passes on x64 because the error is greater than what is ostensibly expected.

**Comment by RussKeldorph** [comment]
Should check w/ and w/o SIMD.

**Comment by RussKeldorph** [comment]
@CarolEidt I hope this is just a difference-in-precision issue, but if you could take I a look I'd appreciate it.  I believe the test should be fixed to reverse the inequality, and then we need to understand if the difference between the actual result and expected result (about 7 if I recall) is correct given x64 precision.

**Comment by CarolEidt** [comment]
I will look at this. One possible issue is that I think it should use `Single.Epsilon` instead of `1E-9F`, but I don't know if there are other issues (e.g. algorithmic losses in precision) that would cause the result to be off by more than that.
