### ISSUE TITLE
ARM64: Test OverwriteArray fails, regression from March 14th

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3969]
Test ID: [OverwriteArray.exe_5426]
Repro:
%CORERUN% JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b309042\OverwriteArray\OverwriteArray.exe
Trying to stelem.i4 directly into an int32[0...]
Shouldn't be here...
FAIL

**Comment by kyulee1** [comment]
Fixed via https://github.com/dotnet/coreclr/pull/4414
