### ISSUE TITLE
ARM64: Test NonVirtualCall fails, regression from March 14th

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3971]
Test ID: [NonVirtualCall.exe_3436]
Repro:%CORERUN% JIT\Methodical\flowgraph\bug619534\NonVirtualCall\NonVirtualCall.exe  
Error: Test_CallNonFinalVirtualOutside_Neg did not throw an exception
Test Failed

**Comment by kyulee1** [comment]
Fixed via https://github.com/dotnet/coreclr/pull/4414
