### ISSUE TITLE
ARM64: Assertion failed 'varTypeIsGC(objRef->TypeGet()) || objRef->TypeGet() == TYP_I_IMPL'

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3973]
Test ID: [b431011.exe_5448]
Repro:
%CORERUN%  JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b431011\b431011\b431011.exe 
Assert failure(PID 11964 [0x00002ebc], Thread: 4876 [0x130c]): Assertion failed 'varTypeIsGC(objRef->TypeGet()) || objRef->TypeGet() == TYP_I_IMPL' in 'cs1:Main(ref):int' (IL size 61)

    File: d:\dd\projectk\src\ndp\clr\src\jit\morph.cpp Line: 5187
    Image: X:\arm64coresyschk\CoreRun.exe

**Comment by kyulee1** [comment]
This test was deleted via 4d3b8acd161bcd5890be78af5130526575264ccc as security transparency tests.
