### ISSUE TITLE
Confusing comment about Silverlight and culture in Environment.GetResourceString

### ISSUE THREAD

**Issue by svick** [dotnet/coreclr#3979]
Just before `Environment.GetResourceString(string)` is [this comment](https://github.com/dotnet/coreclr/blob/bad0651a18a2e9dc276961076e7c17d70570ab49/src/mscorlib/src/System/Environment.cs#L1310-L1321):

```c#
// #threadCultureInfo
// Currently in silverlight, CurrentCulture and CurrentUICulture are isolated 
// within an AppDomain. This is in contrast to the desktop, in which cultures 
// leak across AppDomain boundaries with the thread. 
// 
// Note that mscorlib transitions to the default domain to perform resource 
// lookup. This causes problems for the silverlight changes: since culture isn't
// passed, resource string lookup won't necessarily use the culture of the thread 
// originating the request. To get around that problem, we pass the CultureInfo 
// so that the ResourceManager GetString(x, cultureInfo) overload can be used. 
// We first perform the same check as in CultureInfo to make sure it's safe to 
// let the CultureInfo travel across AppDomains. 
```

I find it confusing for two reasons:

1. It's talking about Silverlight, which I believe is not relevant for CoreCLR.
2. It's talking about passing `CultureInfo`, so that the correct resource string can be retrieved, but the methods that follow don't do anything like that.

Do I understand it correctly that this comment is obsolete? Should it be removed?

**Comment by jkotas** [comment]
> Do I understand it correctly that this comment is obsolete? Should it be removed?

Yes.
