### ISSUE TITLE
How to print exception message and type from IL_Throw?

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/coreclr#3986]
Is there an easy way to print the exception object from gdb when we are in DispatchManagedException? I cannot do lldb as I'm on arm where it is not working.'

Thanks!

**Comment by jkotas** [comment]
@janvorli Do you have set of tricks for this?

**Comment by janvorli** [comment]
@manu-silicon sorry for not responding earlier, I am on a sick leave at the moment and so I monitor my emails only once a day.
At the DispatchManagedException, you'd need to go up the stack to IL_Throw to access the exception object and then use ```p *((ExceptionObject*)obj)->_message.m_asString->m_Characters```  to get the exception message. 
You can also set a breakpoint at RaiseTheExceptionInternalOnly and then 
do ```p *((ExceptionObject*)throwable)->_message.m_asString->m_Characters```, which works for the case when the DispatchManagedException was called from IL_Rethrow too.

There is a also a way to turn on exception processing logging where you can see various details on how the managed frames are being processed (including method names for each frame), which clauses are being considered, etc. Use the following settings (the LogFacility value picks the EH logs):
```
export COMPlus_LogEnable=1
export COMPlus_LogToConsole=1
export COMPlus_LogFacility=4000
export COMPlus_LogLevel=6
```

**Comment by manu-silicon** [comment]
@janvorli Not a problem. I was able to get the message from the exception and this was very helpful. I also enabled the logging but it does not print the message part.
