### ISSUE TITLE
Issues when building mscorlib in VS

### ISSUE THREAD

**Issue by svick** [dotnet/coreclr#3988]
I attempted to build mscorlib (i.e. mscorlib.csproj) from Visual Studio but encountered several issues. None of them are fatal, since editing from VS and then building from the command line works, but they are annoying.

1. There is no solution file that contains mscorlib.csproj (not even after running build.cmd from the command line). This is slightly annoying by itself, but worse, when I directly open mscorlib.csproj in VS and attempt to build, I get the error:

 > Solution is not saved. Please save your solution before managing NuGet packages.

 Just saving the autogenerated single-project mscorlib.sln to disk fixes this.

2. When I try to build after that, I get this error:

 > error CS2007: Unrecognized option: '/test:moduleName=CommonLanguageRuntimeLibrary'

3. All .cs files are shown duplicated in Solution Explorer:

 ![Solution Explorer screenshot](http://i.imgur.com/LmSm7Lo.png)

**Comment by jkotas** [comment]
cc @AlexGhiondea @tarekgh

**Comment by AlexGhiondea** [comment]
1. Have you tried disabling the restore of the Nuget packages? Mscorlib has no dependencies so there are no packages to restore. We can create a solution for mscorlib or we can consider plugging it into the VS solution created for the native code.

2. That error comes from us trying to use the native (pre-Roslyn) compilers and passing in a flag that only those understand. We should be able to get rid of that now as we don't use the native compilers anymore.

3. The duplicated list of files I am not sure where it is coming from.

I will try to take a look at this tomorrow.

**Comment by svick** [comment]
1. I have updated to VS 2015 Update 2 and this error doesn't seem to happen anymore.
