### ISSUE TITLE
Empty Product directory after the build

### ISSUE THREAD

**Issue by xplicit** [dotnet/coreclr#40]
after running `./build.sh` on Ubuntu 14.04

I've got the mesage

    ...
    Repo successfully built.
    Product binaries are available at /home/user/coreclr/binaries/Product/amd64/debug

but this directory is empty

**Comment by ellismg** [comment]
Since support for Linux is still coming online, we haven't taken the time to actually produce a single directory which contains all the build components you would need to run an application.

The most interesting artifacts are just under the CMake folder right now:

`/CMake/src/coreclr/hosts/unixcorerun/corerun` (The native application which hosts CoreCLR.)
`/CMake/src/dlls/mscoree/coreclr/libcoreclr.so` (The CoreCLR Runtime.)

Within the next few days we'll document how to combine these plus managed libraries to get a run-time that can actually run simple managed code (unfortunately the process is quite rough right now).  Note the runtime itself is in a very alpha state on Linux right now.  Simple things work, but there's still a ton of work to be done.

**Comment by Piot** [comment]
Please let me know if there is anything I can help out with!

Trying to run a hello world now results in:

`dlopen failed to open the libcoreclr.so with error /home/peter/test/libcoreclr.so: undefined symbol: CHAIN_SUCCESS_COUNTER`

**Comment by janvorli** [comment]
This is strange, the libcoreclr.so should load fine. I've seen people from the community reporting that in the GIT forums - they get ExecuteAssembly failed - status: 0x80004005, which means that the libcoreclr.so was loaded successfully. The CHAIN_SUCCESS_COUNTER resides in the src\vm\amd64\virtualcallstubamd64.S, so I wonder if it is possible that these files are not being assembled / added to the cee_wks library. 
Could you please try to modify the CMakeLists.txt in src/vm folder by adding 
message("Assembler files: ${VM_SOURCES_WKS_AMD64_ASM}") 
before the add_subdirectory(dac) by the end of the file and run make to see what cmake displays? (cmake will be automatically run by make if there is a change in a CMakeLists.txt)

**Comment by directhex** [comment]
FWIW, I am *not* seeing the issue reported by @Piot  - maybe it should be split out as a distinct issue from this one?

**Comment by sergiy-k** [comment]
@Piot I’m curious whether you are building a debug or release version of CoreClr?

**Comment by sergiy-k** [comment]
Binplacing of native CoreCLR binaries on Linux has been enabled today. So the Product folder should no longer be empty. But we still need to publish instruction describing how to build managed framework libraries and applications for Linux before you can actually start playing with it.

**Comment by Piot** [comment]
@sergiy-k Linux binaries are now placed correctly (e.g. binaries/Product/amd64/debug), tested ef73ad8

**Comment by Piot** [comment]
@sergiy-k I used the debug version, is there a way to build mscorlib and run a hello_world.exe?

**Comment by Piot** [comment]
@sergiy-k @directhex I would suggest an official chat room for dotnet/coreclr, but please join https://gitter.im/Piot/coreclr for now.

**Comment by ellismg** [comment]
I will be publishing directions on how to run hello world later tonight or tomorrow.

**Comment by shahid-pk** [comment]
@ellismg 
great waiting.

**Comment by Piot** [comment]
I suggest closing this issue, the files are placed correctly now.
The `CHAIN_SUCCESS_COUNTER` problem is reported as #95.

**Comment by ellismg** [comment]
@Piot FYIm I published some directions on how to run build and run Hello World [on the wiki](https://github.com/dotnet/coreclr/wiki/Building-and-Running-CoreCLR-on-Linux)

**Comment by janvorli** [comment]
@ellismg Matt, looking at the instructions - we don't need the nasm, we were just considering it at one point, but then dropped the idea.

**Comment by ellismg** [comment]
@janvorli Good to know!  I will update the docs.

**Comment by Piot** [comment]
Thanks a lot @ellismg!
