### ISSUE TITLE
Why is the entire GC source in one file?

### ISSUE THREAD

**Issue by ala53** [dotnet/coreclr#401]
Looking at the code for the garbage collector, everything is in a single file. Is there a specific reason or is it a result of some sort of incremental design? Everything from GC statistics to allocation to background and blocking garbage collection is all in one file totaling ~36,000 lines and 1.2 megabytes of text.

I ask because I would like to clean it up (move GCStatistics into its own header and CPP file, move background GC code into its own file, etc.) but want to make sure that there is not a specific reason for its current state (shared codebase, etc.).

**Comment by ala53** [comment]
Looking a bit more, it seems that the GC code is a bit of a mess:

From gcpriv.h:

```

//#define dprintf(l,x) {if (trace_gc && (l<=print_level)) {GCLog x;}}
//#define dprintf(l,x) {if ((l==SEG_REUSE_LOG_0) || (l==SEG_REUSE_LOG_1) || (trace_gc && (l<=3))) {GCLog x;}}
//#define dprintf(l,x) {if (l == DT_LOG_0) {GCLog x;}}
//#define dprintf(l,x) {if (trace_gc && ((l <= 2) || (l == BGC_LOG) || (l==GTC_LOG))) {GCLog x;}}
//#define dprintf(l,x) {if (l==GTC_LOG) {GCLog x;}}
//#define dprintf(l,x) {if (trace_gc && ((l <= 2) || (l == 1234)) ) {GCLog x;}}
//#define dprintf(l,x) {if ((l <= 1) || (l == 2222)) {GCLog x;}}
#define dprintf(l,x) {if ((l <= 1) || (l == GTC_LOG)) {GCLog x;}}
//#define dprintf(l,x) {if ((l <= 1) || (l == GTC_LOG) ||(l == DT_LOG_0)) {GCLog x;}}
//#define dprintf(l,x) {if ((l==GTC_LOG) || (l <= 1)) {GCLog x;}}
//#define dprintf(l,x) {if (trace_gc && ((l <= print_level) || (l==GTC_LOG))) {GCLog x;}}
//#define dprintf(l,x) {if (l==GTC_LOG) {printf ("\n");printf x ; fflush(stdout);}}
```
Note that only one of the #defines is in use but there's 11 other commented out ones.

**Comment by cnblogs-dudu** [comment]
> IIRC, it was originally machine-generated... from LISP code written by David Bacon, under contract from the then-GC owner Patrick Dussud.

From: https://news.ycombinator.com/item?id=8994408

**Comment by ala53** [comment]
That explains a lot...So moving it into multiple files won't cause me to get lynched?

**Comment by cnblogs-dudu** [comment]
@ala53 
You will save people who wants read GC source from lynch.

**Comment by ala53** [comment]
Also, what is this mysterious "Book of the Runtime?" It would probably be useful to figure out what the GC is doing.

gc.cpp, line 12:
```
// GC automatically manages memory allocated by managed code. 
// The design doc for GC can be found at 
// file:../../doc/BookOfTheRuntime/GC/GCDesign.doc
```

**Comment by cnblogs-dudu** [comment]
@ala53 See https://github.com/dotnet/coreclr/blob/master/Documentation/garbage-collection.md

**Comment by MattWhilden** [comment]
It seems like the discussion for this has been moved to #408. I'm closing this one out. Let me know if this is in error.
