### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by sparkmxx** [dotnet/coreclr#4026]
environment：server2008r2 vs2015 
Unable to start the program , lost api-ms-win-core-winrt-l1-1-0.dll

**Comment by jkotas** [comment]
This is likely fixed by #4014. Could you please try now?

**Comment by adityamandaleeka** [comment]
@sparkmxx I hope you're able to build now. Since there's been no update on this issue since March, I'm going to close it. Please open a new issue if you're unable to build in the future.
