### ISSUE TITLE
Mark libcoreclr.so as not needing executable stack

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#4048]
See http://linux.die.net/man/8/execstack

**Comment by jkotas** [comment]
This is needed to reduce CoreCLR attack surface

**Comment by morganbr** [comment]
Is there something similar for managed code that we'd be able to enable?

**Comment by jkotas** [comment]
Managed code (IL) does not have this problem to start with.

**Comment by schaabs** [comment]
Every .so file needs this as well.  Specifically I found that this is an issue with the DAC having this bit set.

**Comment by ericeil** [comment]
This is also needed to run CoreCLR in the new "Ubuntu on Windows" environment, which seems to refuse to load a .so without this set.
