### ISSUE TITLE
NullReferenceException from CharEnumerator after calling Reset

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/coreclr#4055]
Ran into this rather surprising behavior, but it seems it's been there all along.

``` csharp
class Repro
{
    static void Main()
    {
        var e = "bar".GetEnumerator();
        e.Dispose();
        e.Reset();
        e.MoveNext(); // throws NullReferenceException
    }
}
```

It seems that calling `Reset` after `Dispose` should be a no-op (or throw `ObjectDisposedException` but that could rank higher on a breaking change scale) rather than resetting the cursor back to -1.

**Comment by danmosemsft** [comment]
@stephentoub thoughts about this one? This is desktop behavior also. Dictionary<> and List<> both do nothing in Dispose. CharEnumerator releases its string. We could change Dispose to do nothing, but it would leak the string if someone was expecting it to release it -- this seems an unlikely scenario, to hold an enumerator indefinitely.

I think it's fair to say that after disposing, the object is expected to be useless. MSDN isn't [prescriptive](https://msdn.microsoft.com/en-us/library/78dfe2yb(v=vs.110).aspx) about what should happen though. @bartdesmet points out that ODE is typical.

**Comment by stephentoub** [comment]
From my perspective, using an object after disposing it results in undefined behavior and all bets are off. While throwing null refs isn't great, I wouldn't spend much time or energy to change it. If it's a super easy fix with zero impact on any other use case, fine.

**Comment by karelz** [comment]
Closing based on info above. If someone has a simple no-impact fix, please say so and we can reopen.

**Comment by stephentoub** [comment]
If the desire is just to avoid the exception, a simple fix would likely be to just assign the string to Empty rather than null in Dispose. Don't know if it's worthwhile, though.
