### ISSUE TITLE
R2R: Support for Rare Static fields

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#4070]
Build the tests with crossgen flag and run them on non-Windows. The following rare fields not supported issue comes up (impacts 23 tests in Release build):

BEGIN EXECUTION /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/crossgen /Platform_Assemblies_Paths /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay:/mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Release/JIT/Directed/intrinsic/interlocked/rva_rvastatic1 rva_rvastatic1.exe Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0 Copyright (c) Microsoft Corporation. All rights reserved. ReadyToRun: Rare kinds of static fields not supported Error 2147500033 (Exception from HRESULT: 0x80004001 (E_NOTIMPL)) while compiling method IntrinsicTest.MainTest ReadyToRun: Rare kinds of static fields not supported Error 2147500033 (Exception from HRESULT: 0x80004001 (E_NOTIMPL)) while compiling method IntrinsicTest..cctor Native image /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Release/JIT/Directed/intrinsic/interlocked/rva_rvastatic1/o.ni.exe generated successfully. /mnt/resource/j/workspace/dotnet_coreclr/master/x64_release_centos7.1_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/corerun rva_rvastatic1.exe Unhandled Exception: System.TypeInitializationException: The type initializer for 'IntrinsicTest' threw an exception. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. at IntrinsicTest..cctor() --- End of inner exception stack trace --- at IntrinsicTest.MainTest() at IntrinsicTest.Main() ./rva_rvastatic1.sh: line 76: 9987 Aborted $_DebuggerFullPath "$CORE_ROOT/corerun" rva_rvastatic1.exe $CLRTestExecutionArguments $Host_Args Expected: 100 Actual: 134 END EXECUTION - FAILED

**Comment by jkotas** [comment]
There are bad tests. They fail under various circumstances even without R2R - see https://github.com/dotnet/coreclr/issues/2433.

**Comment by gkhanna79** [comment]
Bad tests, so moving to post-RTM for cleaning them up.

**Comment by gkhanna79** [comment]
Issues being tracked by JIT team in https://github.com/dotnet/coreclr/issues/2451

**Comment by gkhanna79** [comment]
@JohnChen0 Since these tests have been removed, do you want to close the issue?
