### ISSUE TITLE
CultureInfo.CurrentCulture not being preserved across Threads on Linux

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/coreclr#4088]
MVC seems to have encountered a problem whereby the CurrentUICulture is not preserved across threads on Linux (windows works fine). If you run [this](https://github.com/ryanbrandenburg/Demo/tree/modified) project on windows, go to /Home/Index and request "fr" as your language all the fields should display french data. However, if you run it on Linux AND the Controller and View execute on different threads then you will get English as the CurrentUICulture of the View because it's not preserved across the thread switch and English is the default.

Here's a screenshot of what it looks like when this happens:
![threadculture](https://cloud.githubusercontent.com/assets/14987221/14292505/3a6908b8-fb1d-11e5-8eff-b81ab2d88fc6.png)

Basically we set the CurrentUICulture of the thread based on your request (query-string, header or cookie), the Controller [receives](https://github.com/ryanbrandenburg/Demo/blob/modified/src/Demo/Controllers/HomeController.cs#L31) that Culture without trouble, we do something async, then create our View. The view [doesn't have the same culture](https://github.com/ryanbrandenburg/Demo/blob/modified/src/Demo/Views/Home/Index.cshtml#L6) as the Controller by the time it executes. 

Also of note is that if you keep trying this you will stop getting the English results because it becomes more and more likely that the View thread will be "pre-populated" with french from when it previously hosted the Controller.

CC @rynowak and @javiercn to make sure I explained it fully and understandably.

**Comment by Eilon** [comment]
Marking as `blocking-partner` because this is a critical ASP.NET scenario.

@DamianEdwards FYI

**Comment by janvorli** [comment]
@stephentoub - this is a corefx rather than coreclr issue, right?

**Comment by stephentoub** [comment]
@janvorli, if there's a bug here, it would actually be due to code in coreclr/mscorlib as that's where the implementation for all the relevant types live, e.g. CultureInfo, ExecutionContext, etc.

@ryanbrandenburg, how is work being passed across threads, i.e. what APIs are being used?  Are you queuing work with Tasks?  Using just async/await?   Is there a custom SynchronizationContext involved?  Etc.  It'd help if you could provide a small console-based repro using just the relevant APIs, outside of all of the MVC machinery.

cc: @tarekgh

**Comment by janvorli** [comment]
@stephentoub Ah, right, I got somehow confused.

**Comment by rynowak** [comment]
@stephentoub this is all async/await without a custome context.

Simplified, the execution graph looks like:
````
Loc Middleware (sets Culture) -> MVC Invoker -> Controller (user code) -> Task.Delay
                                                                                 -> View (user code)
````

All the arrows represent `await`s and the second piece of user code (View) is observing an unexpected value of the culture. I'll talk to @ryanbrandenburg about putting together an isolated (non-MVC) repro when he arrives.

**Comment by tarekgh** [comment]
this could be because we have different globalization code used in Linux than Windows. but having non MVC sample will help in the repro. I'll try to take a look later today.

**Comment by ryanbrandenburg** [comment]
Here is a repro app https://github.com/ryanbrandenburg/ThreadedCultureRepro. As with the MVC repro, it works as you would expect on windows but gives the wrong culture when the second half happens on a different thread in linux.

**Comment by tarekgh** [comment]
Thanks @ryanbrandenburg I'll try that. I am seeing the Linux code is not having the async logic with the current cultures so I am working to fix that. will update you when I have more news.

**Comment by tarekgh** [comment]
CC @ericeil as FYI

**Comment by ryanbrandenburg** [comment]
@tarekgh we'll pick get this fix the next time we pick up new CoreCLR packages now that it's merged, correct? If so I'll close this out.

**Comment by tarekgh** [comment]
@ryanbrandenburg yes it is merged. I am currently adding the test for it. you can close this one if you like.

**Comment by ryanbrandenburg** [comment]
Thanks!

**Comment by DamianEdwards** [comment]
I notice this issue is in the RTM milestone. We want this for RC2, do we need to change anything here?

**Comment by tarekgh** [comment]
@joshfree could you help please answering @DamianEdwards question?

**Comment by joshfree** [comment]
@tarekgh @DamianEdwards you can bring it through Shiproom/war if you want to reset rc2 escrow.
/cc @leecow @Petermarcu

**Comment by tarekgh** [comment]
@DamianEdwards it this really needed for rc? can't wait for rtm? I am asking because I want to have the fix exercised before rushing it during the escrow mode.

**Comment by DamianEdwards** [comment]
And we'd similarly like customers to be able to use and verify the ASP.NET Core localization on Linux before we RTM. This is blocking that from happening. Additionally, it's a take back from our RC1 story as we used to make this work in DNX.

**Comment by stephentoub** [comment]
@DamianEdwards, given its importance, why was it only discovered two days ago?  Also, when you say we used to make this work, you mean that DNX had special code to enable this, or you mean that this functionality in CoreCLR used to work and has since regressed?

**Comment by DamianEdwards** [comment]
@stephentoub yes, it worked in DNX because we had code. It was only found recently because we've only recently got bits up and running again in CI to test this stuff (I still don't have a consumer-level build I can use to start verification).

**Comment by tarekgh** [comment]
https://github.com/dotnet/coreclr/pull/4154

**Comment by tarekgh** [comment]
This the fix is merged to the rc release branch.

**Comment by joshfree** [comment]
please be sure to verify the fix in this morning's release build.

**Comment by tarekgh** [comment]
I have verified the fix is in the release shares:

``` 
\\cpvsbuild\Drops\dev14\ProjectKRel\raw\24008.00\binaries.amd64ret\Linux\ProjectK\Runtime
\\cpvsbuild\Drops\dev14\ProjectKRel\raw\24008.00\binaries.amd64ret\OSX\ProjectK\Runtime

```
