### ISSUE TITLE
Script Download and Placement of Native Symbols

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#4091]
Package a script alongside the runtime that can download its symbols and place them next to each binary so that debuggers and tracers automatically pick them up.

Ideally, the script is version agnostic so that it can be copied amongst versions of the runtime without concern that the wrong symbols will be placed and thus rejected by tools.

**Comment by brianrob** [comment]
cc: @lt72, @gkhanna79, @schaabs, @brthor

**Comment by mikem8361** [comment]
Change the --strip-debug back to --strip-unneeded in the strip_symbols cmake function.

**Comment by dagood** [comment]
The first challenge here is to find a way to associate a `.so`/`.dylib` file with a package id and version. I see a few options:

1. Read the `<project-name>.deps.json` file. 
  * It looks like we can rely on this being in the publish dir: https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/specs/runtime-configuration-file.md
2. Add some extra metadata to each package that publishes into the publish dir containing the package id, version, and list of native binaries in that package.
3. Inject more info into our binaries to associate them with package id+versions.
  * At that point, we could go all-out and inject an identifier that can link a `.so`/`.dylib` to a `.so.dbg`/`.dylib.dwarf` and make a symbol server like we have for `.dll` -> `.pdb`.

(1) seems to me like what we should go for. (3) is something that we'll want at some point that requires more investigation and coordination with server implementations, but with (1) we just need the script.

Assigning to myself for more thoughts on the script itself when I get back on Tues. I haven't seen parsing JSON in a sh script before.

**Comment by brthor** [comment]
Why must this be a bash script?

**Comment by dagood** [comment]
It doesn't have to be, but it seems to me like the easiest way to get this done with the bare minimum dependencies. We could compile some tool for each platform instead, or use some higher-level thing that we can depend on. (Not managed code, because if we need symbols that might mean the runtime isn't working.)

**Comment by lt72** [comment]
@dagood: on the email thread you mention a build hash that is already in the binary. Please post the details on this thread when you get a chance

**Comment by dagood** [comment]
(@lt72 I was actually just finishing up this comment now! :smile:)

Turning on the build pipeline has been my main focus this week so far, but now I have an update about a pretty major change in what I think our approach should be: I think we should go straight to making a "proper" symbol server. A meeting I had on Tuesday with @brianrob and @schaabs showed me that a script like (1) or (2) doesn't really work for their scenarios (can't rely on that metadata being available at debug-time), and making a symbol server is actually **much** easier than I was thinking it would be.

The biggest thing that makes it easier to make the symbol server is that there's already a BuildID in Linux `.so`s and a UUID in OSX `.dylibs` that's shared with their `.dbg` and `.dwarf` symbol files. With this ID, we can set up a simple path convention in an Azure blob storage account that gets the exact right symbol file for a `.so` without shipping any new metadata.

An interesting effect is that the symbol server should work with existing files, so no CoreCLR changes are needed to index the symbols and any version of a symbol fetch tool could be used on older binaries. (I.e. the tool and indexing can be OOB with RTM.)

I'll be sending out a OneNote page internally with some more details later today. (There have been a few email threads that I'll be merging.)

**Comment by lt72** [comment]
cc:@leculver

**Comment by tzwlai** [comment]
We have a new design for this which doesn't have to version with the runtime.  Moving this out of 1.0 since we currently planning to ship OOB.

**Comment by brianrob** [comment]
cc: @ellismg

**Comment by lt72** [comment]
Superseded by #10868, #10872, and #10873.
