### ISSUE TITLE
Replace the DbgTransportSession::CheckBufferAccess with better validation

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#4094]
The debugger transport memory validation function used for Read/Write memory APIs should be replaced with something that doesn't use probe wrapped in a try/catch. Because the xplat C++ runtimes don't expect an exception at random instructions, the probing code is very fragile even with all the noinline/optnone attributes and the throw PAL_SEHException hack.

**Comment by mikem8361** [comment]
@jkotas (and @janvorli) do you think it is important to get rid of this try/except and probe access validation and use this write/read to pipe approach?

http://stackoverflow.com/questions/7134590/how-to-test-if-an-address-is-readable-in-linux-userspace-app

**Comment by jkotas** [comment]
I would be useful to find out whether it is at least as portable as what we got. Does it work on both Linux and Mac?

**Comment by janvorli** [comment]
@mikem8361 do we still have the problem with catching the hardware exception after I've changed the hardware exception handling when the exception stems from native code under the hardware exception holder? I have thought that change would likely solve this problem.

**Comment by mikem8361** [comment]
The current try/except probing is working fine even before your changes but the concern that the current solution was too fragile to ship. Your changes have made it a lot less fragile, but is it enough?

**Comment by mikem8361** [comment]
It isn’t clear if these works on Mac or the other Unixes like FreeBSD.  Probably have to actually try it out on all the different platforms to answer this. The reason I started this thread is to avoid to any more work on this because we already have a lot work before RTM.

**Comment by janvorli** [comment]
It should work on FreeBSD and NetBSD - that's why I have made the change to enable the hardware exception test in PAL that verifies that.
As for OSX, that's a question though.

**Comment by tzwlai** [comment]
Moving this out to 1.1 after discussing with @mikem8361.

**Comment by mikem8361** [comment]
Fixed with PR: https://github.com/dotnet/coreclr/pull/9122
