### ISSUE TITLE
Implement Array.StableSort

### ISSUE THREAD

**Issue by iCodeSometime** [dotnet/coreclr#4098]
I am working towards implementing List<T>.StableSort, as per dotnet/corefx#4696. It makes more sense to implement in CoreCLR first, as discussed [here](https://github.com/dotnet/corefx/issues/4696#issuecomment-161290987). I'm cloning the repo now, and should have a pull request ready in a short while.

**Comment by svick** [comment]
If this is about adding a public method, then you should still follow [the API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) by having an issue in corefx and not submitting a PR until the API is accepted. This applies even to types that are implemented in coreclr.

**Comment by kennycoc** [comment]
Oh, for whatever reason, I thought that label just generally meant it was working on the API. Thanks for clarifying!

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/4696
