### ISSUE TITLE
Exception filters have different behavior when invoked via reflection and the filter throws an exception

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#410]
This is ported over from Roslyn Issue #[1114](https://github.com/dotnet/roslyn/issues/1114).

When invoking a method with an exception filter where the conditional expression for the filter throws an exception, the thrown exception should be swallowed and the filter treated as if the conditional expression returned false.

However, when the method is invoked via reflection, the exception thrown by the conditional expression for the filter is not swallowed and is instead wrapped by a TargetInvocationException and rethrown.

The expected behavior should be for the exception to still be swallowed and the original exception wrapped by a TargetInvocationException and rethrown.

Console Application:
```VB
Imports System

Public Class Program

    Public Shared Sub Main()
        Console.WriteLine("TestExceptionFilter() Direct Invocation")
        Invoke(Sub() TestExceptionFilter())
        Console.WriteLine()

        Console.WriteLine("TestExceptionFilter() Invocation via Reflection")
        Invoke(Sub() GetType(Program).GetMethod("TestExceptionFilter").Invoke(Nothing, New Object() {}))
        Console.WriteLine()

#If DEBUG Then
        Console.WriteLine("Press any key to exit...")
        Console.ReadKey()
#End If

    End Sub

    Public Shared Sub Invoke(ByRef action As Action)
        Try
            action()
        Catch ex As Exception
            Console.WriteLine(ex)
        End Try
    End Sub

    Public Shared Sub TestExceptionFilter()
        Try
            Throw New Exception("Original Exception")
        Catch ex As Exception When MyCondition()
            Console.WriteLine(ex)
        End Try
    End Sub

    Public Shared Function MyCondition() As Boolean
        Throw New Exception("Condition Exception")
    End Function

End Class
```
Expected Output:
Direct Invocation catches the original exception.
Invocation via Reflection catches a TargetInvocationException that wraps the original exception.
> TestExceptionFilter() Direct Invocation
> System.Exception: Original Exception
>    at ConsoleApplication1.Program.TestExceptionFilter() in Program.vb:line 31
>    at ConsoleApplication1.Program._Lambda$__1() in Program.vb:line 7
>    at ConsoleApplication1.Program.Invoke(Action& action) in Program.vb:line 23
> 
> TestExceptionFilter() Invocation via Reflection
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Original Exception
>    at ConsoleApplication1.Program.TestExceptionFilter() in Program.vb:line 31
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    at ConsoleApplication1.Program._Lambda$__2() in Program.vb:line 11
>    at ConsoleApplication1.Program.Invoke(Action& action) in Program.vb:line 23
> 
> Press any key to exit...

Actual Output:
Direct Invocation catches the original exception.
Invocation via Reflection catches a TargetInvocationException that wrapping the condition exception.
> TestExceptionFilter() Direct Invocation
> System.Exception: Original Exception
>    at ConsoleApplication1.Program.TestExceptionFilter() in Program.vb:line 31
>    at ConsoleApplication1.Program._Lambda$__1() in Program.vb:line 7
>    at ConsoleApplication1.Program.Invoke(Action& action) in Program.vb:line 23
> 
> TestExceptionFilter() Invocation via Reflection
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Condition Exception
>    at ConsoleApplication1.Program.MyCondition() in Program.vb:line 38
>    at ConsoleApplication1.Program.TestExceptionFilter() in Program.vb:line 32
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    at ConsoleApplication1.Program._Lambda$__2() in Program.vb:line 11
>    at ConsoleApplication1.Program.Invoke(Action& action) in Program.vb:line 23
> 
> Press any key to exit...

**Comment by tannergooding** [comment]
*ping*
Issue has not been looked at yet.

**Comment by tannergooding** [comment]
@jkotas Could you see if someone can route/assign this as appropriate?

**Comment by jkotas** [comment]
@gkhanna79 Could you please take a look when you get a chance?

**Comment by sjwoodard** [comment]
Any update on this?

**Comment by gkhanna79** [comment]
Sorry, I am just getting to this - I will take care of it.

**Comment by gkhanna79** [comment]
This issue has been present in the VM for pretty much as long as I can remember. The problem happens when we have a nested exception (E2) that is caught within the VM (using EX_CATCH), we do not reset the managed thread state tracking the last thrown exception object to be in sync with the outer exception (E1) tracked by the topmost exception tracker (corresponding to the top-most active tracker).  Thus, managed thread still says active exception is E2 even though it should be E1.

As a result, when the dispatch for E1 continues and is caught within the VM again (which is what happens for Reflection based invocation and in the failing repro for this bug), VM uses GET_THROWABLE macro to access the thrown object. Since that is pulled from managed thread object, we get E2 instead of E1.

While this is broken even when exception is caught in managed code, and not the VM, it happens to work since the exception object passed to the catch funclet is pulled from the active exception tracker and not the managed thread.

I have a fix for this and validated it addresses the repro in this bug. I will test it more and hope to check it in next week.
