### ISSUE TITLE
ContentEncoding header stripped out of response.header.content.contentEncoding

### ISSUE THREAD

**Issue by jehine-MSFT** [dotnet/coreclr#4114]
I've noticed that when getting a response with "gzip" as the content encoding, this value is not populated into the response.Header.Content.contentEncoding object. If the value is "foo" this value is properly propagated from the response to the header object.

**Comment by sergiy-k** [comment]
Yes, please. Thank you!

**Comment by sergiy-k** [comment]
Closing. See https://github.com/dotnet/corefx/issues/9481 for details.
