### ISSUE TITLE
Unix MSCorlib contains windows p-invokes

### ISSUE THREAD

**Issue by ericstj** [dotnet/coreclr#4121]
I am noticing the following windows-specific PInvokes in the unix builds of MSCorlib:
.module extern advapi32.dll
.module extern mscoree.dll

advapi32.dll is being brought in by [ManifestEtw.EventUnregister](https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/mscorlib/src/Microsoft/Win32/UnsafeNativeMethods.cs#L126).

mscoree.dll is being brought in by [Marshal](https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/mscorlib/src/System/Runtime/InteropServices/Marshal.cs#L408)

/cc @jkotas @ellismg

**Comment by yizhang82** [comment]
These Read* APIs are already deprecated and I don't think we should keep supporting them in CoreCLR.   I don't expect developers to use them and I've never seen people actually using the object overload version. Can we remove them from .NET Core?

**Comment by jkotas** [comment]
You can welcomed to remove them - it is nice to have cleanup.

There is quite a bit of clutter in CoreCLR mscorlib.dll that can be removed. I have done some of it recently (e.g. see #3852, #3863, #3900, #3930, ...). One can spend many months cleaning it up - there is a lot of it, and it is not easy to tease it apart.

It may be actually better to start with ProjectN System.Private.CoreLib.dlll - where we have done this cleanup, and add back the stuff needed by CoreCLR instead...

**Comment by yizhang82** [comment]
Thanks, Jan. I've created #4145 to track the Marshal API removal. Unfortunately they are in the contract and we need to remove them first (they are already deprecated and not showing up by default in intelli-sense)

**Comment by jkotas** [comment]
#4161 took care of mscoree.dll. The advapi32.dll issue is tracked as #1151.
