### ISSUE TITLE
Update OS X build instructions to state that OS 10.11 is the minimum supported version

### ISSUE THREAD

**Issue by ezephir** [dotnet/coreclr#4133]
The instructions say that building on OS X has been validated for Yosemite. However,  https://github.com/dotnet/corefx/issues/4654 & https://github.com/dotnet/corefx/pull/7558#issuecomment-206594879 says that the minimum supported OS is El Capitan (10.11).

Does the [documentation](https://github.com/dotnet/coreclr/blob/e3ad4b489429edd6d7f8315e0bc218c32bf6315f/Documentation/building/osx-instructions.md) need to be updated to reflect this?

**Comment by ellismg** [comment]
Yeah, we should fix this.  Ideally we'll take a clean install of El Capitan (+ relevant updates) and then install whatever version of the command line tools we need + openssl from brew and document how all that works.

**Comment by ezephir** [comment]
@ellismg Is this something I can help with? The CoreCLR instructions seem to work okay on El Capitan, but I can verify on a clean install to be sure.

**Comment by ellismg** [comment]
That would be great!

**Comment by ezephir** [comment]
@ellismg I wasn't able to make the instructions work simply by following them.

* CoreCLR builds without issue as per the instructions.
* CoreFX builds fine but hangs while running tests. 
  * The last completed is System.Runtime.Serialization.Json
  * A large number exceptions get thrown about missing DLLs and unsupported features. These mostly seem to revolve around networking.
  * I worked around this by passing the skiptests flag.

* The nuget restore doesn't work because it isn't able to find packages with the specified versions.
  * The tool prints the text `The remote server returned an error: (404) Not Found,` followed by `Unable to find version <version> of package <package>`
  * The version numbers are the same as they are in the Windows build.

This was done on a clean install of 10.11 with:
* Xcode 7.3 installed from the app store (with no command line tools or additional installations, since the instructions don't explicitly call that out)
* 32-bit mono from the mono website via it's installer, 
* the appropriate tools from homebrew (installed at /usr/local),
* the single ulimit change. 

I believe that I can install mono from homebrew instead of from the mono website. It doesn't seem to change these results.

**Comment by ezephir** [comment]
For other potential content changes:
* The page makes a reference to needing Windows in the environment section, but it's no longer used anywhere on the page.
* Another reference to Windows at the end of the git section.
* The ulimit command is easy to miss (since it's bundled under the mono heading)
* The Xcode reference is no longer relevant since the minimum version of Xcode for El Capitan is 7.3.

**Comment by ezephir** [comment]
#816 covers the updates for the nuget section.

@ellismg Do you have any suggestions regarding getting started with the CoreFX tests on OS X? Is running plain "build.sh" still the right thing? The build bot seems to be doing something a bit more complicated than what's in the instructions.

**Comment by jeffschwMSFT** [comment]
Our minimal version of supported OSX is now 10.13
