### ISSUE TITLE
"dotnet build" cannot find Serializable type

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/coreclr#4138]
I am trying to port mdbg into Linux with dotnet-cli.
For the first step, I selected some cs files and tried to build files as library using dotent-cli
my test project is located in https://github.com/chunseoklee/dotnetcli_test and dotnet-cli version is `.NET Command Line Tools (1.0.0-beta-001598)`
Currently, dotnet build failed with the following errors.

```
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(19,22): error CS0234: The type or namespace name 'Serialization' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(1068,43): error CS0246: The type or namespace name 'SafeHandleZeroOrMinusOneIsInvalid' could not be found (are you missing a using directive or an assembly reference?)
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(1079,33): error CS0115: 'SafeWin32Handle.ReleaseHandle()': no suitable method found to override
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(81,6): error CS0246: The type or namespace name 'SerializableAttribute' could not be found (are you missing a using directive or an assembly reference?)
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(81,6): error CS0246: The type or namespace name 'Serializable' could not be found (are you missing a using directive or an assembly reference?)
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(137,46): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(137,70): error CS0246: The type or namespace name 'StreamingContext' could not be found (are you missing a using directive or an assembly reference?)
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(1360,60): warning CS0618: 'UnmanagedType.Struct' is obsolete: 'Applying UnmanagedType.Struct is unnecessary when marshalling a struct. Support for UnmanagedType.Struct when marshalling a reference type may be unavailable in future releases.'
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(1157,49): error CS0246: The type or namespace name 'SafeHandleZeroOrMinusOneIsInvalid' could not be found (are you missing a using directive or an assembly reference?)
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(1161,37): error CS0115: 'NativeMethods.SafeMapViewHandle.ReleaseHandle()': no suitable method found to override
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(1199,53): error CS0246: The type or namespace name 'SafeHandleZeroOrMinusOneIsInvalid' could not be found (are you missing a using directive or an assembly reference?)
/home/twoflower/usr/dev/mdbg_dotnetcli/NativeImports.cs(1208,37): error CS0115: 'NativeMethods.SafeLoadLibraryHandle.ReleaseHandle()': no suitable method found to override

Compilation failed.
    8 Warning(s)
    11 Error(s)

```
From to http://dotnet.github.io/api/,  I cannot find any reference about Serializable. 
In coreclr source tree, it is defined in src/mscorlib/src/System/Reflection/TypeAttributes.cs file. Should I include mscorlib.dll as a reference ? But, in issue #154 , @ellismg suggested not to use mscorlib.dll.  
Am I missing something or such type defined in another place ?

**Comment by jkotas** [comment]
cc @noahfalk

**Comment by noahfalk** [comment]
.Net Core doesn't support Serializable as far as I know, so the only options are to remove its usage or replace it with an alternative serialization mechanism. There is some more general info about porting and tooling to help identify issues here: https://github.com/Microsoft/dotnet-apiport

In this particular case its probably pretty easy. I'm guessing these are Serializable attributes on Exception objects in which case MDbg was just following a common convention to make Exceptions serializable. MDbg doesn't actually ever serialize/deserialize those types so removing the Serializable attribute won't break anything.

Just to give you a heads up we are working to port MDbg to .Net Core so that it runs on Linux/OSX internally and we plan to make it open source. I don't have a specific ETA for you however.

**Comment by chunseoklee** [comment]
@noahfalk For curiosity, clrdbg mentioned in MIEngine repo is the port of mdbg or something else? Thank you for your help.

**Comment by noahfalk** [comment]
clrdbg is something else - specifically its a port of Visual Studio's managed debugger. Compared to MDbg the VS one has many additional features and is correspondingly larger and more complex.

**Comment by chunseoklee** [comment]
Thank you for help.
