### ISSUE TITLE
BitConverter: Write bytes to exisiting array

### ISSUE THREAD

**Issue by Toxantron** [dotnet/coreclr#4142]
Hello,

are there any ambitions to provide an API to BitConverter that takes an exisiting `byte[]` and position to include the bytes of a primitive? 

Right now I have an additional converter based on BitConverter that has methods like this:

```c#
    /// <summary>
    /// Includes an int into an array of bytes
    /// </summary>
    public unsafe static void Include(int value, byte[] bytes, int index)
    {
        // Error handling and parameter validation
        if (bytes == null)
            throw new ArgumentNullException(nameof(bytes));
        if (index + 4 > bytes.Length)
            throw new ArgumentOutOfRangeException(nameof(index));
        fixed (byte* b = bytes)
            *((int*)(b + index)) = value;
    }

    /// <summary>
    /// Includes a long into an array of bytes
    /// </summary>
    [System.Security.SecuritySafeCritical]  // auto-generated
    public unsafe static void Include(long value, byte[] bytes, int index)
    {
        // Error handling and parameter validation
        if (bytes == null)
            throw new ArgumentNullException("bytes");
        if (index + 8 > bytes.Length)
            throw new ArgumentOutOfRangeException("index");
        fixed (byte* b = bytes)
            *((long*)(b + index)) = value;
    }
```

I think it would be great to have those methods as well whenever we try to serialize values into an array without having to use `Array.Copy` all the time. To avoid redundant code the `GetBytes` methods should then just call the new methods.

```c#
        // Converts an int into an array of bytes with length 
        // four.
        [System.Security.SecuritySafeCritical]  // auto-generated
        public unsafe static byte[] GetBytes(int value)
        {
            Contract.Ensures(Contract.Result<byte[]>() != null);
            Contract.Ensures(Contract.Result<byte[]>().Length == 4);

            byte[] bytes = new byte[4];
            Include(value, bytes, 0);
            return bytes;
        }
      
        // Converts a long into an array of bytes with length 
        // eight.
        [System.Security.SecuritySafeCritical]  // auto-generated
        public unsafe static byte[] GetBytes(long value)
        {
            Contract.Ensures(Contract.Result<byte[]>() != null);
            Contract.Ensures(Contract.Result<byte[]>().Length == 8);

            byte[] bytes = new byte[8];
            Include(value, bytes, 0);
            return bytes;
        }
```

I would be happy to create a PR if this is considered a valid API addition.

**Comment by hughbe** [comment]
I can see the use case for this - but should this API-addition issue be migrated to corefx where most additions are discussed?

**Comment by Toxantron** [comment]
Well, you tell me. ;) I thought since the class is located here and
description talks about low level classes this would be the perfect place.

**Comment by hughbe** [comment]
I suggest moving this to corefx. Here are my reasons
- more (Microsoft) people checkout the corefx issue list so you're more likely to get feedback
- the code for BitConverter.cs is also in corefx. I recall that for API additions for an object in corefx AND coreclr, corefx takes priority
- there are existing issues in corefx proposing API additions

**Comment by Toxantron** [comment]
Ok. Should I close this one and open a new one?

**Comment by hughbe** [comment]
Yeah why not - leave a comment here saying you've migrated it for the record :)

**Comment by Toxantron** [comment]
Moved to corefx.
