### ISSUE TITLE
why is there umount in cross/build-rootfs.sh?

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#4143]
There's a line in `cross/build-rootfs.sh` that un-mounts the folder before and after preparing arm root-fs.
```
umount $__RootfsDir/*
rm -rf $__RootfsDir
...
umount $__RootfsDir/*
```
do anyone know the reason? is this (still) valid ?

**Comment by mkborg** [comment]
During rootfs preparation some scripts from .deb packages are executed. Some of them can mount some directory inside chroot.

**Comment by seanshpark** [comment]
thanks, I'll close this issue after a day or two.
