### ISSUE TITLE
JIT asserts don't display message box

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4156]
On Windows desktop CLR, when you hit a JIT assert, you get a pop-up message box. When you hit "Retry" on this, and you are running under a debugger, the debugger stops at the assert.

On Windows CoreCLR, this is not working.

This is because the CLR fails in LateboundMessageBoxW():

```
#if defined(FEATURE_CORESYSTEM) && !defined(CROSSGEN_COMPILE)
    // Some CoreSystem OSs will support MessageBoxW via an extension library. The following technique is what
    // was recommeded by Philippe Joubert from the CoreSystem team.
    HMODULE hGuiExtModule = WszLoadLibrary(W("ext-ms-win-ntuser-gui-l1"), NULL, 0);
#else
```

namely, it fails to load this library.

The call stack is:

```
>	coreclr.dll!LateboundMessageBoxW(HWND__ * hWnd, const wchar_t * lpText, const wchar_t * lpCaption, unsigned int uType) Line 1002	C++
 	coreclr.dll!MessageBoxImpl(HWND__ * hWnd, const wchar_t * message, const wchar_t * title, const wchar_t * detailedText, unsigned int uType) Line 113	C++
 	coreclr.dll!UtilMessageBoxNonLocalizedVA(HWND__ * hWnd, const wchar_t * lpText, const wchar_t * lpTitle, const wchar_t * lpDetails, unsigned int uType, int displayForNonInteractive, int showFileNameInTitle, int * pInputFromUser, char * args) Line 435	C++
 	coreclr.dll!UtilMessageBoxNonLocalizedVA(HWND__ * hWnd, const wchar_t * lpText, const wchar_t * lpTitle, unsigned int uType, int displayForNonInteractive, int showFileNameInTitle, int * pInputFromUser, char * args) Line 322	C++
 	coreclr.dll!UtilMessageBoxCatastrophicNonLocalizedVA(const wchar_t * lpText, const wchar_t * lpTitle, unsigned int uType, int showFileNameInTitle, char * args) Line 598	C++
 	coreclr.dll!UtilMessageBoxCatastrophicNonLocalized(const wchar_t * lpText, const wchar_t * lpTitle, unsigned int uType, int showFileNameInTitle, ...) Line 539	C++
 	coreclr.dll!_DbgBreakCheck(const char * szFile, int iLine, const char * szExpr, int fConstrained) Line 471	C++
 	coreclr.dll!CEEInfo::doAssert(const char * szFile, int iLine, const char * szExpr) Line 9989	C++
```

The function then returns zero, which propagates back to _DbgBreakCheck(), which calls TerminateProcess().

(Apparently we used to always tell the caller to break, but that is #if 0'ed for some reason:
```
    case 0:
#if 0
        // The message box was not displayed. Tell caller to break.
        return true;
#endif
```
)

This hampers JIT team productivity because:
1. it prevents using a just-in-time debugger,
2. it requires always setting a breakpoint on clrjit.dll!assertAbort() or similar, instead of using the existing message box mechanism.

**Comment by BruceForstall** [comment]
@jkotas @janvorli Maybe one of you know about this, in particular about this code:

```
    // Some CoreSystem OSs will support MessageBoxW via an extension library. The following technique is what
    // was recommeded by Philippe Joubert from the CoreSystem team.
    HMODULE hGuiExtModule = WszLoadLibrary(W("ext-ms-win-ntuser-gui-l1"), NULL, 0);
```

**Comment by janvorli** [comment]
I have tried to load that library just using a simple C++ app on Windows and it has also failed. But it seems that we have the name wrong. If I try to load ext-ms-win-ntuser-gui-l1**-1-0**, then it works.
But I am not an expert on the contract dlls, so I don't know if adding the -1-0 is future proof.
@jkotas any idea on this?

**Comment by jkotas** [comment]
We should delete the apiset code and always load user32, even for CoreCLR. user32 is available on all OS SKUs where it makes sense to display message box.

**Comment by tishion** [comment]
I think this is obviously incorrect usage of windows API. Although windows introduced api-set schema from windows 7, the upper layer application should still use APIs from win32 subsystem modules. Those modules with prefix API-MS-WIN or EXT-MS-WIN contain only API redirection information. Each of these modules is a collection of the APIs within the same functional category. But the real implementations of these APIs are still reside in the win32 subsystem modules(kernel32, kernelbase, user32 and gdi32 etc.)
So this code:
> HMODULE hGuiExtModule = WszLoadLibrary(W("ext-ms-win-ntuser-gui-l1"), NULL, 0);
will not work on any desktop version of windows.

Actually these api sets are used for windows mincore internally, not for developers to use directly.

**Comment by mikedn** [comment]
> Actually these api sets are used for windows mincore internally, not for developers to use directly.

That's not quite true, universal apps actually link directly to api sets. And AFAIR apps intended to run on Nano server do the same thing. Maybe they were initially intended to be used internally but that's no longer the case. And the only reason why "normal" desktop apps don't usually use these api sets is that some/all of these api sets do no exist on earlier version of Windows.

But @jkotas is right, you only want this particular message box in a classic desktop environment and such an environment will have user32.dll for the foreseeable future. Using the ntuser contract in this case it's just unnecessary complication.
