### ISSUE TITLE
Linked CancellationTokenSource Race Condition

### ISSUE THREAD

**Issue by Lukazoid** [dotnet/coreclr#4167]
There appears to be a race condition with `CancellationTokenSource` when using `CreateLinkedTokenSource` and disposing of the linked `CancellationTokenSource` while `Cancel()` is called for the original `CancellationToken`.

I noticed this issue because we are having to wrap a lot of `CancellationTokens` in linked cancellation token sources to eliminate the memory leak which has subsequently been fixed by: https://github.com/dotnet/corefx/commit/ace2b3d7a9d45d97d9bdf650c4f70482be7bf731

My use case is quite simply:

    using (var cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken))
    {
        return await GetSomeResultAsync(cts.Token).ConfigureAwait(false);
    }

If `cts` is disposed at the same time `cancellationToken` is canceled, there is a race condition which results in an `ObjectDisposedException`, the stack trace is:

>  System.ObjectDisposedException: The CancellationTokenSource has been disposed.
>   at System.Threading.CancellationTokenSource.Cancel (Boolean throwOnFirstException)
>   at System.Threading.CancellationTokenSource.Cancel ()
>   at System.Threading.CancellationTokenSource.LinkedTokenCancelDelegate (System.Object source)
>   at System.Threading.CancellationCallbackInfo.ExecutionContextCallback (System.Object obj) 
>   at System.Threading.CancellationCallbackInfo.ExecuteCallback ()
>   at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork (CancellationCallbackCoreWorkArguments args)
>   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (Boolean throwOnFirstException)
> 

It appears the mono guys also know about this issue: https://github.com/mono/mono/blob/bf5947a/mcs/class/corlib/Test/System.Threading/CancellationTokenSourceTest.cs#L454

This is incredibly hard to reproduce as `cts.Dispose()` needs to be called after `cancellationToken` has a reference to the callback delegate but before the callback delegate is invoked.

This may be one for @stephentoub

**Comment by stephentoub** [comment]
I'll take a look today.

**Comment by Lukazoid** [comment]
What's the best workaround for this currently?

**Comment by stephentoub** [comment]
> Thanks for managing to produce a fix. 

Thanks for opening the issue.

>  I was just wondering what's the best workaround for this currently?

If you control the code calling Cancel, you could wrap it in a try/catch.  You could also skip using CreateLinkedTokenSource, create your own CTS instance, and just do your own linking and unlinking (where you register with each constituent token and have that registration call Cancel on your CTS, basically what LCTS does for you), which would let you wrap the exact location where your "linked" cts has its Cancel method called.  (In either case, it won't be perfectly safe, but as rare as this issue already is, it'd be even more rare for it to actually cause corruption.)
