### ISSUE TITLE
RyuJIT x86: NYI: "GT_IND of TYP_LONG"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4170]
This assert: 

NYI: "GT_IND of TYP_LONG"
File: coreclr\src\jit\lower.cpp Line:382

Is hit in these tests:
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b49335\b49335\b49335.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b63730\b63730\b63730.cmd
JIT\Directed\coverage\oldtests\stfldstatic2_il_r\stfldstatic2_il_r.cmd
JIT\Directed\coverage\oldtests\ldfldstatic_il_d\ldfldstatic_il_d.cmd
JIT\Methodical\Invoke\ctor\_il_relval_ctor_newobj\_il_relval_ctor_newobj.cmd
JIT\IL_Conformance\Old\Conformance_Base\clt_u8\clt_u8.cmd
JIT\Directed\coverage\oldtests\stfldstatic1_il_d\stfldstatic1_il_d.cmd
JIT\Regression\VS-ia64-JIT\V1.2-M02\b26496\b26496\b26496.cmd
JIT\IL_Conformance\Old\Conformance_Base\and_u8\and_u8.cmd
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b14350\b14350\b14350.cmd

**Comment by BruceForstall** [comment]
This was fixed.
