### ISSUE TITLE
RyuJIT x86: NYI: "GT_NEG of TYP_LONG"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4171]
This assert:

NYI: "GT_NEG of TYP_LONG"
File: coreclr\src\jit\lower Line: 403

Is hit in these tests:
JIT\jit64\mcc\interop\mcc_i00\mcc_i00.cmd
JIT\IL_Conformance\Old\Conformance_Base\neg_i8\neg_i8.cmd
JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b94306\b94306\b94306.cmd
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b48554\b48554b\b48554b.cmd
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b44879\b44879\b44879.cmd
JIT\Directed\intrinsic\pow\pow3_cs_r\pow3_cs_r.cmd
JIT\Regression\VS-ia64-JIT\M00\b102759\b102759\b102759.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b67987\b67987\b67987.cmd
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b29456\b29456\b29456.cmd
JIT\Directed\intrinsic\pow\pow3_cs_d\pow3_cs_d.cmd

**Comment by RussKeldorph** [comment]
Assigned to @mikedn.
