### ISSUE TITLE
RyuJIT x86: NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4172]
This assert:

NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
File: coreclr\src\jit\codegencommon.cpp Line: 766

Is hit by these tests:
JIT\Methodical\MDArray\InnerProd\structarr_cs_d\structarr_cs_d.cmd
JIT\Regression\VS-ia64-JIT\V1.2-Beta1\b102860\b102860\b102860.cmd
JIT\Methodical\explicit\rotate\_il_relrotarg_valref\_il_relrotarg_valref.cmd
JIT\Methodical\explicit\misc\_il_relrefarg_box_val\_il_relrefarg_box_val.cmd
JIT\Methodical\explicit\rotate\_relrotarg_valref\_relrotarg_valref.cmd
JIT\Methodical\explicit\rotate\_dbgrotarg_valref\_dbgrotarg_valref.cmd
JIT\Directed\zeroinit\Dev10_863995\Dev10_863995.cmd
JIT\jit64\valuetypes\nullable\castclass\null\castclass-null045\castclass-null045.cmd
JIT\Methodical\explicit\rotate\_opt_dbgrotarg_valref\_opt_dbgrotarg_valref.cmd
JIT\jit64\gc\misc\struct9_2\struct9_2.cmd

**Comment by BruceForstall** [comment]
This is in Compiler::compHelperCallKillSet().

**Comment by pgavlin** [comment]
Closed by #7125.
