### ISSUE TITLE
RyuJIT x86: NYI: "StoreInd of of TYP_LONG"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4173]
This assert:

NYI: "StoreInd of of TYP_LONG"
File: coreclr\jit\src\lower.cpp Line: 375

Is hit by these tests:
JIT\Methodical\int64\signed\_il_rels_ldc_mul\_il_rels_ldc_mul.cmd
JIT\Directed\coverage\oldtests\lclfldsub_cs_do\lclfldsub_cs_do.cmd
JIT\Methodical\explicit\misc\_relexplicit6\_relexplicit6.cmd
JIT\Methodical\fp\exgen\200w1d-02_cs_r\200w1d-02_cs_r.cmd
JIT\Directed\shift\uint64_ro\uint64_ro.cmd
JIT\jit64\valuetypes\nullable\box-unbox\generics\box-unbox-generics010\box-unbox-generics010.cmd
JIT\Methodical\int64\arrays\_speed_rellcs_long\_speed_rellcs_long.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b60142\b60142\b60142.cmd
JIT\Regression\CLR-x86-JIT\V1.2-Beta1\b178128\b178128\b178128.cmd
JIT\Methodical\flowgraph\dev10_bug675304\loopIV_init\loopIV_init.cmd

**Comment by mikedn** [comment]
Should this be closed now that #5380 has been merged?

**Comment by sejongoh** [comment]
Yep. Thanks.
