### ISSUE TITLE
RyuJIT x86: NYI: "unknown target"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4177]
This NYI:

NYI: "unknown target"
File: coreclr\src\jit\lclvars.cpp Line: 2815

Is hit by these tests:
JIT\Methodical\Invoke\SEH\_il_relcatchfinally_jmp\_il_relcatchfinally_jmp.cmd
JIT\Methodical\Invoke\SEH\_il_relcatchfault_jmp\_il_relcatchfault_jmp.cmd
JIT\Methodical\Invoke\SEH\_il_dbgcatchfinally_jmp\_il_dbgcatchfinally_jmp.cmd
JIT\Methodical\Invoke\SEH\_il_dbgcatchfault_jmp\_il_dbgcatchfault_jmp.cmd
JIT\Methodical\VT\callconv\_il_reljumps5\_il_reljumps5.cmd
JIT\Methodical\Invoke\fptr\_il_dbgrecurse_jmp\_il_dbgrecurse_jmp.cmd
JIT\IL_Conformance\Old\Base\jmp\jmp.cmd
JIT\Methodical\flowgraph\dev10_bug642944\GCMaskForGSCookie\GCMaskForGSCookie.cmd
JIT\Methodical\Invoke\fptr\_il_dbgrecurse_jmpi\_il_dbgrecurse_jmpi.cmd
JIT\Methodical\Invoke\SEH\_il_dbgcatchfinally_jmpind\_il_dbgcatchfinally_jmpind.cmd

**Comment by BruceForstall** [comment]
This is in LclVarDsc::lvaArgType(): "Get type of a variable when passed as an argument."
