### ISSUE TITLE
RyuJIT x86: NYI_X86: "EH for RyuJIT x86"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4178]
This NYI:

NYI_X86: "EH for RyuJIT x86"
File: coreclr\src\jit\codegenxarch.cpp Line: 995
and
File: coreclr\src\jit\codegenxarch.cpp Line: 1012

Is hit by these tests:
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b84971\b84971\b84971.cmd
JIT\Directed\FaultHandlers\Simple\Simple\Simple.cmd
JIT\Methodical\eh\basics\tryfault_d\tryfault_d.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b55216\b55216\b55216.cmd
JIT\Directed\ExcepFilters\mixed3\mixed3\mixed3.cmd
JIT\Methodical\eh\basics\tryfaulttrycatch_r\tryfaulttrycatch_r.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b51875\b51875\b51875.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b70909\b70909\b70909.cmd
JIT\Regression\VS-ia64-JIT\M00\b112982\b112982\b112982.cmd
JIT\Directed\leave\filter3_r\filter3_r.cmd

**Comment by mikedn** [comment]
Wasn't this fixed by #6101?

**Comment by BruceForstall** [comment]
Yep.
