### ISSUE TITLE
RyuJIT x86: NYI_X86: "GT_OBJ"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4179]
This NYI:

NYI_X86: "GT_OBJ"
File: coreclr\src\jit\lowerxarch.cpp Line: 1204

Is hit by these tests:
JIT\jit64\valuetypes\nullable\castclass\null\castclass-null038\castclass-null038.cmd
JIT\jit64\hfa\main\testE\hfa_sf0E_r\hfa_sf0E_r.cmd
JIT\Methodical\eh\cs\unsafe_r\unsafe_r.cmd
JIT\Methodical\refany\_dbgnative\_dbgnative.cmd
JIT\jit64\mcc\interop\mcc_i86\mcc_i86.cmd
JIT\Methodical\refany\_il_dbgstress2\_il_dbgstress2.cmd
JIT\Methodical\tailcall_v4\tailcall_AV\tailcall_AV.cmd
JIT\jit64\mcc\interop\mcc_i11\mcc_i11.cmd
JIT\SIMD\VectorAbs_r\VectorAbs_r.cmd
JIT\SIMD\VectorSqrt_ro\VectorSqrt_ro.cmd

**Comment by CarolEidt** [comment]
Fixed with #7252
