### ISSUE TITLE
RyuJIT x86: NYI_X86: "Implement GT_END_LFIN for x86"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4180]
This NYI:

NYI_X86: "Implement GT_END_LFIN for x86"
File: coreclr\src\jit\lowerxarch.cpp Line: 157

Is hit by these tests:
JIT\Methodical\eh\finallyexec\tryCatchFinallyThrow_nonlocalexit1_do\tryCatchFinallyThrow_nonlocalexit1_do.cmd
JIT\Methodical\ELEMENT_TYPE_IU\_il_reli_seq\_il_reli_seq.cmd
JIT\Generics\ConstrainedCall\class2_cs_r\class2_cs_r.cmd
JIT\Methodical\Boxing\functional\_orelfibo_cs\_orelfibo_cs.cmd
JIT\Directed\Misc\function_pointer\funcptrtest\funcptrtest.cmd
JIT\Methodical\eh\generics\trycatchnestedtype_r\trycatchnestedtype_r.cmd
JIT\Directed\coverage\importer\Desktop\nullsdarr_il_d\nullsdarr_il_d.cmd
JIT\Directed\coverage\importer\ceeillegal\ceeillegal.cmd
JIT\SIMD\VectorInit_ro\VectorInit_ro.cmd
JIT\Methodical\eh\nested\general\throwinnestedfinally_do\throwinnestedfinally_do.cmd

**Comment by mikedn** [comment]
Wasn't this fixed by #6101?

**Comment by BruceForstall** [comment]
Yep.
