### ISSUE TITLE
RyuJIT x86: NYI_X86: "Math intrinsics Cos, Sin and Round"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4184]
This NYI:

NYI_X86: "Math intrinsics Cos, Sin and Round"
File: coreclr\src\jit\lowerxarch.cpp Line: 658

Is hit by these tests:
JIT\Methodical\Boxing\functional\_orelsin_cs\_orelsin_cs.cmd
JIT\Methodical\Boxing\xlang\_odbgsin_cs_cs\_odbgsin_cs_cs.cmd
JIT\opt\Inline\tests\mathfunc\mathfunc.cmd
JIT\CodeGenBringUpTests\FPMath\FPMath.cmd
JIT\Performance\CodeQuality\BenchF\FFT\FFT\FFT.cmd
JIT\Methodical\Boxing\morph\_orelsin_cs\_orelsin_cs.cmd
JIT\Performance\CodeQuality\BenchF\BenchMrk\BenchMrk\BenchMrk.cmd
JIT\Performance\CodeQuality\BenchF\Whetsto\Whetsto\Whetsto.cmd
JIT\Methodical\Boxing\xlang\_orelsin_cs_cs\_orelsin_cs_cs.cmd
JIT\Performance\CodeQuality\BenchF\BenchMk2\BenchMk2\BenchMk2.cmd

**Comment by adiaaida** [comment]
@pgavlin you took this one right?

**Comment by pgavlin** [comment]
Yes.

**Comment by pgavlin** [comment]
Fixed by #7023.
