### ISSUE TITLE
RyuJIT x86: NYI: "Arithmetic binary operators on TYP_LONG - GT_UMOD"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4190]
This NYI:

NYI: "Arithmetic binary operators on TYP_LONG - GT_UMOD"
File: coreclr\src\jit\lower.cpp Line:480

Is hit by this test:
JIT\Regression\Dev11\External\dev11_239804\ShowLocallocAlignment\ShowLocallocAlignment.cmd

**Comment by pgavlin** [comment]
Closed by #7105.
