### ISSUE TITLE
RyuJIT x86: NYI: "Arithmetic binary operators on TYP_LONG - SHIFT"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4191]
This NYI:

NYI: "Arithmetic binary operators on TYP_LONG - SHIFT"
File: coreclr\src\jit\lower.cpp Line: 480

Is hit by these tests:
JIT\IL_Conformance\Old\Conformance_Base\shr_i8\shr_i8.cmd
JIT\IL_Conformance\Old\Conformance_Base\shl_u8\shl_u8.cmd

**Comment by adiaaida** [comment]
I have this plumbed through DecomposeLongs to convert the shifts into their respective helpers, however, we have a bug where the helpers expect the args to be in registers (eax:edx for the long, ecx for the shift), but we push the halves of the longs on the stack, so we get the wrong answer.

**Comment by mikedn** [comment]
What about long shift by constant? It is usually implemented using SHLD/SHRD rather than helpers.

**Comment by adiaaida** [comment]
The helper does the shld/shrd. In legacy backend, we have special handling for shifting by a constant in codegen, but we don't have the mechanism to plumb the shld/shrd from decompose to codegen, as it requires 3 operands, as far as I can tell.
