### ISSUE TITLE
MarshalStructAsLayoutSeq fails on non-windows platform.

### ISSUE THREAD

**Issue by tijoytom** [dotnet/coreclr#4196]

**Comment by yizhang82** [comment]
This looks like another instance of HVA/HFA issue:

native code is using rdi/rsi:

->  0x102fb2ee4 <+4>:  movl   %edi, -0x18(%rbp)
    0x102fb2ee7 <+7>:  movq   %rsi, -0x10(%rbp)

While our IL stub is passing through xmm0:

x108b5f793: vmovdqu -0x50(%rbp), %xmm0

**Comment by yizhang82** [comment]
Confirmed this is a CoreCLR bug and my PR fixes this.
