### ISSUE TITLE
Need to ensure Path.GetTempPath() / other APIs work as expected on cross-plat coreclr fwk

### ISSUE THREAD

**Issue by MattGal** [dotnet/coreclr#420]
See this thread:   

https://github.com/aspnet/HttpAbstractions/issues/168
 
... basically the expectation is that Path.GetTempPath() may fail on Unix or MacOS systems when switching to the cross-plat coreclr implementation.  From reading the current implementation, it still depends on the API in Kernel32.

**Comment by stephentoub** [comment]
@MattGal, have you seen a problem at run time, or is this just based on code inspection?  P/Invokes to kernel32.dll in mscorlib get redirected by the runtime to its PAL layer, so a call to GetTempPath on Unix doesn't actually try to load kernel32.dll, but instead uses the native implementation from libcoreclr.  Today I believe it only goes to /tmp/, but it could certainly be extended to first check an environment variable, and that is indeed the plan for when Path is instead exposed in a standalone System.Runtime.Extensions library implemented in managed code over on https://github.com/dotnet/corefx.

**Comment by felipepaixao** [comment]
Same issue

**Comment by stephentoub** [comment]
@felipepaixao, can you on the issue you're seeing? How is it failing?

**Comment by felipepaixao** [comment]
Hi, @stephentoub 
I'm having an issue when my application, which is hosted in a Linux vm, tries to access the default temporary location.
Here's the detailed exception error:

>An unhandled exception occurred while processing the request.

>DirectoryNotFoundException: Exception of type 'System.IO.DirectoryNotFoundException' was thrown.
>Microsoft.AspNet.Http.Core.BufferingHelper.get_TempDirectory () [0x00000] in , line 0

**Comment by stephentoub** [comment]
Thanks. This is using the ASP.NET BufferingHelper, which is a wrapper around Path.GetTempPath(), but only as a fallback:
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Core/BufferingHelper.cs
What's the value of the "ASPNET_TEMP" environment variable it's checking first? Are you sure it's falling back to GetTempPath?

**Comment by felipepaixao** [comment]
Hey!
Here's the detailed error: 

>Microsoft.AspNet.Http.Core.BufferingHelper.get_TempDirectory () [0x00000] in <filename unknown>
    Microsoft.AspNet.Http.Core.BufferingHelper.EnableRewind (Microsoft.AspNet.Http.HttpRequest request, Int32 bufferThreshold) [0x00000] in <filename unknown>
    Microsoft.AspNet.Http.Core.FormFeature+<ReadFormAsync>d__12.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter`1[Microsoft.AspNet.Http.IFormCollection].GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Mvc.AntiForgeryTokenStore+<GetFormTokenAsync>d__4.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter`1[Microsoft.AspNet.Mvc.AntiForgeryToken].GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Mvc.AntiForgeryWorker+<ValidateAsync>d__15.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Mvc.AntiForgery+<ValidateAsync>d__5.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Mvc.ValidateAntiForgeryTokenAuthorizationFilter+<OnAuthorizationAsync>d__2.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Mvc.FilterActionInvoker+<InvokeAuthorizationFilterAsync>d__35.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Mvc.FilterActionInvoker+<InvokeAuthorizationFilterAsync>d__35.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Mvc.FilterActionInvoker+<InvokeAllAuthorizationFiltersAsync>d__34.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Mvc.FilterActionInvoker+<InvokeAsync>d__32.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Mvc.MvcRouteHandler+<InvokeActionAsync>d__3.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Mvc.MvcRouteHandler+<RouteAsync>d__2.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Routing.Template.TemplateRoute+<RouteAsync>d__25.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Routing.RouteCollection+<RouteAsync>d__9.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Builder.RouterMiddleware+<Invoke>d__5.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1+<Invoke>d__11[Microsoft.AspNet.Security.Cookies.CookieAuthenticationOptions].MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1+<Invoke>d__11[Microsoft.AspNet.Security.Cookies.CookieAuthenticationOptions].MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1+<Invoke>d__11[Microsoft.AspNet.Security.Cookies.CookieAuthenticationOptions].MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1+<Invoke>d__11[Microsoft.AspNet.Security.Cookies.CookieAuthenticationOptions].MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1+<Invoke>d__11[Microsoft.AspNet.Security.Cookies.CookieAuthenticationOptions].MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1+<Invoke>d__11[Microsoft.AspNet.Security.Cookies.CookieAuthenticationOptions].MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1+<Invoke>d__11[Microsoft.AspNet.Security.Cookies.CookieAuthenticationOptions].MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    Microsoft.AspNet.Security.Infrastructure.AuthenticationMiddleware`1+<Invoke>d__11[Microsoft.AspNet.Security.Cookies.CookieAuthenticationOptions].MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    System.Threading.Tasks.TaskExtensions+CultureAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Diagnostics.Entity.MigrationsEndPointMiddleware+<Invoke>d__5.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    System.Threading.Tasks.TaskExtensions+CultureAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext () [0x00000] in <filename unknown>
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
    System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
    Microsoft.AspNet.Diagnostics.ErrorPageMiddleware+<Invoke>d__4.MoveNext () [0x00000] in <filename unknown>

**Comment by stephentoub** [comment]
@felipepaixao, thanks.  I was curious though about the configuration of your machine.  A few questions:
1. What distro of Linux are you running on?
2. Are you running on Mono or on CoreCLR?
3. Do you have a /tmp directory on your machine?
4. What's the value of the ASPNET_TEMP environment variable? Try "printenv ASPNET_TEMP" from the terminal.
5. If you set the ASPNET_TEMP environment variable to some temporary directory of your choosing, does that make the error go away?

**Comment by felipepaixao** [comment]
Hi, @stephentoub 
Thanks for your reply.
I Will check everything and I will give you a feedback.
And thanks again for your attention and for your advices.

**Comment by stephentoub** [comment]
Excellent, thanks.

**Comment by davidfowl** [comment]
I can chime in here. We added ASPNET_TEMP because IIS usually runs without a user profile under a service account. In those cases without carefully choosing a temp path, it ends up in a bizzare folder (system32 something). When we run in IIS, Helios (the IIS native module) sets ASPNET_TEMP to something appropriate.

When running self hosted however, the intent was to fall back to the regular temp path.

**Comment by davidfowl** [comment]
@stephentoub This is also likely a mono stacktrace as nobody has built core clr dnx besides @ellismg and I :smile:

**Comment by stephentoub** [comment]
Thanks, David. Regarding Mono, that's what I was assuming, but, well, we all know what happens when people assume :smile: Hence the questions.

**Comment by stephentoub** [comment]
There doesn't actually appear to be a CoreCLR problem here, and with https://github.com/dotnet/coreclr/commit/43e28513e1dd446d8536c54a5b05cde56d38d191 we now also check TMPDIR prior to just returning /tmp/, so I'm closing this. If an issue is discovered here subsequently, we can reopen or open a new issue.
