### ISSUE TITLE
OSX: System.ComponentModel.Win32Exception: Undefined error: 0, when launching process (repeatedly)

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/coreclr#4201]
I observed a process hang while redirecting stdout for processes launched via System.Diagnotics.Process.  In an attempt to repro that issue, I ran into a different issue.  The attached code launches "find . -name "*" -print" 10,000 times.  Deterministically after the 216's launch it fails with the following:
Unhandled Exception: System.ComponentModel.Win32Exception: Undefined error: 0
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at HangTest.Main(String[] args)
[repro.tar.gz](https://github.com/dotnet/coreclr/files/210811/repro.tar.gz)
[crash.txt](https://github.com/dotnet/coreclr/files/210812/crash.txt)

**Comment by adityamandaleeka** [comment]
I wasn't able to repro this on Ubuntu. Were you only hitting this on OS X?

**Comment by jeffschwMSFT** [comment]
Sorry, yes Mac OS.

**Comment by dmccaffery** [comment]
Just hit this issue as well. :(

**Comment by TingluoHuang** [comment]
+1, i am hitting this as well when my .net core app launch git on OSX.

**Comment by karelz** [comment]
@Priya91 should we move the bug to corefx repo under System.Diagnostics.Process?

**Comment by dmccaffery** [comment]
As an FYI: I believe this issue is related to the default child process limit on macOS. I was able to work around this by creating a property list at: /Library/LaunchDaemons/limit.maxproc.plist

```xml
<?xml version="1.0" encoding="UTF-8"?>  
<!DOCTYPE plist PUBLIC "-//Apple/DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">  
  <plist version="1.0">
    <dict>
      <key>Label</key>
        <string>limit.maxproc</string>
      <key>ProgramArguments</key>
        <array>
          <string>launchctl</string>
          <string>limit</string>
          <string>maxproc</string>
          <string>2048</string>
          <string>2048</string>
        </array>
      <key>RunAtLoad</key>
        <true />
      <key>ServiceIPC</key>
        <false />
    </dict>
  </plist>
```

Might also need to up the max files limits at: /Library/LaunchDaemons/limit.maxproc.plist

```xml
<?xml version="1.0" encoding="UTF-8"?>  
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"  
        "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">  
  <dict>
    <key>Label</key>
    <string>limit.maxfiles</string>
    <key>ProgramArguments</key>
    <array>
      <string>launchctl</string>
      <string>limit</string>
      <string>maxfiles</string>
      <string>524288</string>
      <string>524288</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>ServiceIPC</key>
    <false/>
  </dict>
</plist>
```

A reboot is required after making these changes and it does not require disabling secure boot on OS X El Capitan or macOS Sierra.

To test your changes (after a reboot):

```bash
dmccaffery@dm-macbook-pro : ~/Repos/pb/open/condo
 [develop ≡ +28 ~76 -1 | +3 ~23 -23] ==> ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 524288
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2048
virtual memory          (kbytes, -v) unlimited
```

**Comment by Priya91** [comment]
> @Priya91 should we move the bug to corefx repo under System.Diagnostics.Process?

As per @dmccaffery's investigation, seems like it's an OS enforced limitation. If the issue still persists, then we can move to corefx.

**Comment by karelz** [comment]
Closing for now then. If there is anything the platform can do, please open an issue in corefx repo, thanks!
