### ISSUE TITLE
ARM softFP in the JIT

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4204]
# Problem

Have JIT generate ARM32 code without using floating-point registers, aka softFP. Floating-point operations will happen via helper calls. The resulting code can run on platforms without floating-point hardware.
# Questions
1. Is this feature actually needed?
2. Who is going to use this feature, if implemented?
3. Who is planning to work on this feature?
4. Would the JIT be built in a special mode (that is, with a special `#ifdef`) to enable this? Or would determining whether to generate softFP code happen dynamically?
5. How important is floating-point performance? Does the JIT optimizer need to optimize floating-point operations, or can it just treat all floating-point operations as opaque calls? Presumably, if a platform doesn't have floating-point hardware, then floating-point performance is not important.
6. Do software and hardware floating-point implementations, if both available on a platform, need to return identical results?
# Goals for JIT implementation
1. It works for LEGACY_BACKEND, which is what will be used in the short term for ARM32 code generation.
2. It works without changing the legacy backend, or without making many changes to it. As described by the name, this code is legacy, and any work done here is throwaway work on the way to a real, RyuJIT backend port. A RyuJIT implementation might not use the same mechanism.
3. The changes are simple, isolated, and don't interact, as much as possible, with the rest of the JIT.
# Options for implementation

It turns out that there already is code in the JIT to do this under `#if !CPU_HAS_FP_SUPPORT`. It has not been used for a while, and it doesn't currently compile, so it would need to be updated.
1. It morphs floating-point operations to helper calls. In particular, see `Compiler::fgMorphToEmulatedFP()`.
2. It was implemented with the legacy backend, so that support is at least partially there.
3. The helper calls would need to be defined and implemented.

**Comment by BruceForstall** [comment]
@manu-silicon @leemgs @myungjoo @lemmaa @papaslavik: I created this issue to start a conversation about the possible next level of ARM32 softFP support, related to #3785. Comments?

**Comment by myungjoo** [comment]
First of all, the recent "softfp" patches are about calling conventions, not about floating point instructions. You may keep using VFP or Neon while "softfp" calling conventions are used.

Small/micro devices traditionally supposed to run "RTOS" might not have the luxury of VFP. If a software platform targets to support such devices, it may choose to use "softfp" as the standard ABI (arm-linux-gnueabi) to support both devices with VFP an devices without VFP. Note that using softfp (gnueabi) as the ABI format does NOT mean that VFP or NEON is not used. Using softfp means that a binary becomes compatible for both types of devices and with Linux kernel's VFP emulation, even having VFP instruction won't matter for the binary compatibility. On the other hand, software platforms (at least for ARM) targeting mainly servers or desktops may totally forget about devices without VFP; many Linux distros walk this path (I don't think they are targeting "micro devices" with binary compatibility)

Even though softfp is used between CoreCLR and external .so files, we may keep using "hardtop" calling convention for internal calls. I believe @wateret is working on it. However, unless we have a lot of FP functions calls, softfp won't show visible performance deterioration against hardfp; most difference comes from VFP / NEON vs SOFT-emulation, not from the calling convention.

Therefore, please note that your question 4, 5, and 6 are irrelevant; using "softfp" calling convention does not mean that we are not using VFP of Neon. JIT may (and highly recommended to do so) keep using VFP or Neon instructions while using softfp calling convention to call .so files.

Anyway, for question 1~3:
Yes. There are Linux-based software platforms using softfp calling conventions even if target devices have VFP and Neon. (in order not to create binary incompatibility hell; although @leemgs has provided us a software platform basis that supports both softfp and hardfp (armel and armhf) simultanously, it means that we are going to waste a lot of precious storage of embedded devices).

**Comment by wateret** [comment]
@myungjoo I was working on keeping *hardfp* ABI for calling from managed to managed when *softfp* mode. However it seems like there exists calling from native to managed and that makes coreclr hard to have two different ABIs. It may be possible in theory but I don't think it is worth it (at least for now).

**Comment by BruceForstall** [comment]
To summarize: it sounds like the JIT will always continue to generate VFP/NEON instructions. In the case of running on a platform without VFP, the OS will be responsible for emulating these instructions if the VFP/NEON hardware is missing. Thus, the softFP calling-conventions that have recently been implemented are the only changes required for FP for all ARM platforms.

**Comment by russellhadley** [comment]
@BruceForstall I'm not sure I follow.  Certainly if people are interested in working on full softfp - no VFP/NEON - then we'd give them advice and take patches.  It seems a strong assertion that the current set of changes are the only ones required for FP on all ARM platforms.

**Comment by BruceForstall** [comment]
@russellhadley Sure, but nobody has spoken up to require that.

**Comment by russellhadley** [comment]
@BruceForstall On this thread for sure, but given the asks bubbling up around ARM32, and the amount of ARM32 devices that don't support hardware FP, but I would bet on needing to plan for the eventuality.

**Comment by OtherCrashOverride** [comment]
> and the amount of ARM32 devices that don't support hardware FP

Any ARM devices that would actually use CoreCLR are going to have at least a VFP (armv6, Cortex-A).  Anything that does not (Cortex-M), is probably a highly embedded system lacking the resources to run CoreCLR and better suited to .Net Microframework.

**Comment by myungjoo** [comment]
> Any ARM devices that would actually use CoreCLR are going to have at least a VFP (armv6, Cortex-A). Anything that does not (Cortex-M), is probably a highly embedded system lacking the resources to run CoreCLR and better suited to .Net Microframework.

Note that some of Cortex-A (e.g., A5) microarchitectures say VFP is "optional". Although it might not be Cortex-M series, it is highly probable that there soon will be "micro" devices loaded with Linux (not uclinux or some freaky small folks), which will probably try CoreCLR. Budget-wise (not power-wise), such cheap Cortex-A SoCs may beat the price of Cortex-M SoCs (often seen an A7+512MB is cheaper then an M4+4MB). Anyway, if I were them, I'd simply rely on Linux kernel's FP emulation to reuse all the "armel" binaries loaded with VFP instructions.

**Comment by OtherCrashOverride** [comment]
> Note that some of Cortex-A (e.g., A5) microarchitectures say VFP is "optional".

Even the cheapest ($25) Cortex-A5 board I know of (Odroid C0) has both VFP and NEON.  I do not think its unreasonable at all to always use the VFP instructions and rely on the hardware+OS illegal instruction trap to provide emulation when absent.

As mentioned before CoreCLR is not a low resource stack; .Net MF is.  It seems perfectly within reason to have VFP (or OS level instruction emulation) as a minimum 32bit ARM requirement for CoreCLR.

Also as mentioned before, while there is a need for "softfp" ABI support for some OS's, this does not imply the hardware lacks a VFP.

CoreCLR (1)running on ARM32 hardware that (2)lacks VFP and (3)has an OS that can not emulate it would be very 'niche'.

**Comment by BruceForstall** [comment]
I'm going to close this issue, assuming we won't support ARM chips without VFP for the foreseeable future.
