### ISSUE TITLE
build warnings: "RC4005: 'VER_FILEDESCRIPTION_STR' : redefinition"

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4208]
There are now lots of the following warnings in the build (this is just a sample). There should be no build warnings.

    12>D:\gh\coreclr\bin\obj\_version.h(2): warning RC4005: 'VER_FILEDESCRIPTION_STR' : redefinition [D:\gh\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]
    12>D:\gh\coreclr\bin\obj\_version.h(3): warning RC4005: 'VER_INTERNALNAME_STR' : redefinition [D:\gh\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]
    12>D:\gh\coreclr\bin\obj\_version.h(4): warning RC4005: 'VER_ORIGINALFILENAME_STR' : redefinition [D:\gh\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]
    12>D:\gh\coreclr\bin\obj\_version.h(5): warning RC4005: 'VER_PRODUCTNAME_STR' : redefinition [D:\gh\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]
    12>D:\gh\coreclr\bin\obj\_version.h(6): warning RC4005: 'VER_PRODUCTVERSION' : redefinition [D:\gh\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]
    12>D:\gh\coreclr\bin\obj\_version.h(7): warning RC4005: 'VER_PRODUCTVERSION_STR' : redefinition [D:\gh\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]
    12>D:\gh\coreclr\bin\obj\_version.h(8): warning RC4005: 'VER_FILEVERSION' : redefinition [D:\gh\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]
    12>D:\gh\coreclr\bin\obj\_version.h(9): warning RC4005: 'VER_FILEVERSION_STR' : redefinition [D:\gh\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]
    12>D:\gh\coreclr\bin\obj\_version.h(10): warning RC4005: 'VER_LEGALCOPYRIGHT_STR' : redefinition [D:\gh\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]
    12>D:\gh\coreclr\bin\obj\_version.h(11): warning RC4005: 'VER_DEBUG' : redefinition [D:\gh\coreclr\bin\obj\Windows_NT.x64.Debug\src\dlls\mscoree\coreclr\coreclr.vcxproj]

**Comment by BruceForstall** [comment]
@joperezr is this yours?

**Comment by BruceForstall** [comment]
This was from a default x64 debug build, but I believe all build types show these warnings.

**Comment by joperezr** [comment]
yes this is mine. I'll fix this. Sorry for the trouble

**Comment by joperezr** [comment]
Once the PR in buildtools is merged and we update buildtools in coreclr, the warnings will go away.
