### ISSUE TITLE
coreclr native components build is not fully incremental

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4238]
If I run a build.cmd twice in a row, the second time should do nothing. However, I could (from the log), at least the following tool invocations:

2 CL.exe
14 LINK.exe
13 rc.exe
1 lib.exe

**Comment by danmosemsft** [comment]
@gkhanna79 is this required for 2.0?

**Comment by gkhanna79** [comment]
It is not blocking.

**Comment by janvorli** [comment]
I believe this was fixed in #9982 and #10045. @BruceForstall are you aware of anything else that needs to be done here?

**Comment by BruceForstall** [comment]
No, I think this is fixed now.
