### ISSUE TITLE
Intermittent Interop.MarshalAPI.Copy.CopyCharArray.CopyCharArray failure on Mac

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#4254]

**Comment by jkotas** [comment]
This test failed in CI on commit that should not have affected it: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_osx_tst_prtest/592/testReport/junit/Interop.MarshalAPI.Copy/CopyCharArray/CopyCharArray/

**Comment by yizhang82** [comment]
This is pretty rare but it happens every few hundred tries on my machine. Looking...
