### ISSUE TITLE
Unable to debug coreclr apps on Debian 8.2

### ISSUE THREAD

**Issue by caslan** [dotnet/coreclr#4263]
With the latest clrdbg bits and RC2 coreclr bits, debugging fails to start on Debian 8.2. CLR debugging services API returns CORDBG_E_UNSUPPORTED error on trying to attach the process.

The issue appears to be an invalid rpath setting in libmscordbi.so component. 
- If you do “ldd” on libmscordbi.so that is installed with the shared framework you can see it cannot find libmscordaccore.so
- Running clrdbg under native debugger, I can see that we are picking up libmscordbi.so correctly (i.e. from shared framework) but we are picking up libmscordaccore.so next to us (clrdbg) instead of from next to libmscordbi.so. If I patch libmscordbi.so and add $ORIGIN to rpath, the issue goes away.

**Comment by janvorli** [comment]
@mikem8361 can you take a look into it please?

**Comment by mikem8361** [comment]
It should be fixed now.

**Comment by dleeapho** [comment]
@mikem8361 will the fix be in rc2 drops of CoreClr? Debian support for dotnet CLI is something we want for rc2.
