### ISSUE TITLE
Upgrade lldb version to 3.8 for SOS plugin

### ISSUE THREAD

**Issue by Dmitri-Botcharnikov** [dotnet/coreclr#4264]
lldb 3.6 has no/partial support for Linux/arm32 platform. E.g. it misses implementation of RegisterContext for this combination of OS and CPU. We propose to upgrade lldb to version 3.8 as it's the last stable release and includes Linux/arm32 support.

**Comment by seanshpark** [comment]
+1

**Comment by seanshpark** [comment]
#4299

**Comment by seanshpark** [comment]
as #4290 landed, we need to fix https://github.com/dotnet/coreclr/blob/master/src/ToolBox/SOS/lldbplugin/CMakeLists.txt also. 
@Dmitri-Botcharnikov , have you made a patch?

**Comment by seanshpark** [comment]
@janvorli , @jkotas

**Comment by Dmitri-Botcharnikov** [comment]
Yes we have a patch for SOS plug-in to build it with llvm/lldb 3.8. We polish and prepare PR ASAP.

**Comment by Dmitri-Botcharnikov** [comment]
Closed by #4473
