### ISSUE TITLE
tests\src\JIT\Performance\CodeQuality\BenchmarksGame\spectralnorm perf test failing

### ISSUE THREAD

**Issue by dsgouda** [dotnet/coreclr#4270]
The tests under tests\src\JIT\Performance\CodeQuality\BenchmarksGame\spectralnorm seem to be failing with the following stack trace 
Test Failed 
 Unhandled exception of type 'System.Exception': System.Exception : Benchmark failed to validate 
 at SpectralNorm.Bench() in C:\github\coreclr\tests\src\JIT\Performance\CodeQuality\BenchmarksGame\spectralnorm\spectralnorm.cs:line 58 

@AndyAyersMS  Could you please take a look and fix the issue

**Comment by AndyAyersMS** [comment]
I assume this failure comes from running under xunit-performance?

Underlying code is fine since it runs as a correctness test in CoreCLR. So assuming the above it looks like the validation is a bit off for xunit-performance. Fix looks simple enough.
