### ISSUE TITLE
Target .NET Platform Standard in VS2015.2 doesn't work

### ISSUE THREAD

**Issue by grokys** [dotnet/coreclr#4271]
Creating a new Portable Class Library in VS2015.2 and then clicking "Target .NET Platform Standard" in the project properties causes the project to break with errors like:

```
Predefined type 'System.Object' is not defined or imported
Predefined type 'System.Void' is not defined or imported
```

It seems that a NuGet package cannot be located:

```
Unable to resolve NETStandard.Library (>= 1.0.0-rc2-23910) for .NETStandard,Version=v1.5.
```

Is this feature ready for use? I've not seen any mention of it anywhere.

**Comment by ayende** [comment]
+1

**Comment by ericstj** [comment]
We haven't published the package to NuGet.org yet.  /cc @Pilchie 

It will be published soon, in the meantime you can add the feed https://dotnet.myget.org/F/dotnet-core/api/v3/index.json.

**Comment by karelz** [comment]
Should be resolved by now
