### ISSUE TITLE
[RyuJIT][Linux] Codegen of Multi-reg return value store for var=call requires that var is not struct promoted, but such a condition is not always ensured

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#4276]
Repro steps:
Codegen routine that generates multi-reg struct return value of a call to a struct var:
genStoreRegisterReturnInLclVar(GenTreePtr treeNode)

Add the following assert in this routine, after we have VarDSc of the local to which the return value of call is stored

assert(varDsc->lsIsMultiRegArgOrRet)

Do a checked build on x64 Unix with the above change made.  Towards the end of the build crossgen of mscorlib will fail with the above assert.  Essentially this assert indicates that there are some code paths in importer/morph that are not setting lvIsMultiRegArgOrRet on struct var in var=call.  This needs further investigation as it could be a correctness issue or for some other reason such struct vars are not getting promoted though lvIsMultiRegArgOrRet is not true on them.

One can get a list of all the methods hitting the assert by replacing assert with

```
if (!varDsc->lsIsMultiRegArgOrRet)
{
   printf("Method: %s\n", compiler->info.compFullName);
}
```

**Comment by LLITCHEV** [comment]
Fixed y PR #4346
