### ISSUE TITLE
Publish NuGet symbol package in open builds

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#4321]
Currently symbol packages are created (https://github.com/dotnet/coreclr/issues/4090 in PR https://github.com/dotnet/coreclr/pull/4218) but they aren't published in the current builds. This issue tracks getting the symbol package published from the new open coreclr build.

**Comment by gkhanna79** [comment]
This is only about publishing the packages (which are being produced in the open).

**Comment by gkhanna79** [comment]
@wtgodbe I am assigning this to you as this should be done alongwith publishing of all packages produced in the build.

**Comment by gkhanna79** [comment]
@wtgodbe Should this be closed now?

**Comment by wtgodbe** [comment]
Indeed it should.
