### ISSUE TITLE
System.Security.Cryptography.CryptoStream.Dispose throws an exception

### ISSUE THREAD

**Issue by kosta-arnorsky** [dotnet/coreclr#4329]
If Dispose method of System.Security.Cryptography.CryptoStream class which uses AES/Rijndael algorithm with padding is called before the ends of decryption a target data stream it throws the exception: System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
It's especially unpleasant when decryption is interrupted by an uncaught exception:

```
using (var transform = new System.Security.Cryptography.AesManaged().CreateDecryptor(key, iv))
using (var cryptoStream = new System.Security.Cryptography.CryptoStream(encryptedDataStream, transform, System.Security.Cryptography.CryptoStreamMode.Read))
using (var decryptedStream = new System.IO.MemoryStream())
{
    var buffer = new byte[5000];
    var readed = cryptoStream.Read(buffer, 0, buffer.Length);
    decryptedStream.Write(buffer, 0, readed);
    throw new Exception("Something bad has happend.");
}
```
Actual Result: Dispose throws the exception:
```
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
```
I've created a [small example](https://github.com/kosta-arnorsky/CryptoStream-Dispose-Exception-Sample) to demonstrate this behavior.

**Comment by janvorli** [comment]
@kosta-arnorsky This is a corefx, not coreclr issue. Could you please report it in the corefx repo?

**Comment by joshfree** [comment]
I moved this to https://github.com/dotnet/corefx/issues/7779

**Comment by nerradchoong** [comment]
did AesManaged() get implemented at all? I don't seem to be able to call this from RC2 or core version
