### ISSUE TITLE
Static link libvcruntime.lib to eliminate dependency on VCRuntime140.dll

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#4334]
CC @ericstj - Filing this to track the work for RTM per our discussion.

@weshaggard @ianhays - Filed https://github.com/dotnet/corefx/issues/7748 for CoreFX

@schellap - Filed https://github.com/dotnet/cli/issues/2503 for host.

**Comment by ericstj** [comment]
The uber goal of this is to make xcopy work well for both DOTNET CLI and standalone apps.  Today they require VCRedist: a machine-wide install.  This change eliminates the dependency on VC redist and only depends on the UCRT OS update.  That update is pushed through WU so most machines will have it, whereas most machines will not have VCRedist.  Keeping UCRT dynamic keeps our servicing cost down.

**Comment by gkhanna79** [comment]
I have a PR to fix this at https://github.com/dotnet/coreclr/pull/4381

**Comment by ianhays** [comment]
CoreFX equivalent - https://github.com/dotnet/corefx/pull/7840
