### ISSUE TITLE
Enable Serviceable Attribute for mscorlib

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#4336]
@weshaggard I am assigning this to you to look into enabling the attribute for mscorlib build.

**Comment by weshaggard** [comment]
@joperezr can you please add the extra metadata need to get the serviceable attribute applied to mscorlib.

**Comment by joperezr** [comment]
Sure, does this mean you want to move that attribute down to the versioning targets instead of having it in the common targets?

**Comment by weshaggard** [comment]
No. For mscorlib just set those metadata properties in the mscorlib project (or targets).
