### ISSUE TITLE
Add a command option to crossgen to not run SN verification

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#4345]
Adding this per our discussion...
Add a command option to crossgen to not run SN verification

**Comment by jkotas** [comment]
There should be no SN verification in crossgen at all. I got rid of it some time ago.

**Comment by LLITCHEV** [comment]
@jkotas Few days ago I had issues loading old (internally built) libraries while crossgenning due to SSn verify. Talked to @JohnChen0 and had to disable it in the code. He suggested I open this issue.

**Comment by JohnChen0** [comment]
Verified that SN verification in CrossGen was already removed.
