### ISSUE TITLE
[Arm64]Jit Assert Failed (isValidSimm19(dstOffs)) in crossgen

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#4350]
**Assert failure(PID 3884 [0x00000f2c], Thread: 4696 [0x1258]): Assertion failed 'isValidSimm19(dstOffs)' in 'ValueCollection[Guid,Byte][System.Guid,System.Byte]:System.Collections.Generic.IEnumerable<TValue>.GetEnumerator():ref:this' (IL size 17)

    File: e:\git\coreclr\src\jit\emitarm64.cpp Line: 7852**

**Comment by ramarag** [comment]
@kyulee1 can you take a look ?

**Comment by kyulee1** [comment]
Of course. Thanks for reporting this.
