### ISSUE TITLE
Remove APISet Nuget package Dependency from CoreCLR package

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#4366]

**Comment by gkhanna79** [comment]
CC @weshaggard @schellap @piotrpMSFT

**Comment by gkhanna79** [comment]
@weshaggard I have removed all APISet imports from CoreCLR and fixed the Interop ones to be delayloaded (on Win8+). The only ones that will remain are for uCRT by design.

I am looking into removing the dependency on APISet nuget package and during the initial P0 run, I see that there are bunch of failures since FX has dependencies called out on APISets for PInvoke (https://github.com/dotnet/corefx/blob/2ff9b2a1e367a9694af6bdaf9856ea12f9ae13cd/src/Common/src/Interop/Windows/Interop.Libraries.cs).

I dont suppose there are any plans to address this for RTM, right?

**Comment by weshaggard** [comment]
No we don't currently have any plans to stop using Api-sets for the Pinvokes in the managed libraries. However we could potentially pull in the ApiSet package at a higher level than the Runtime package. @ericstj what would be a good layer to pull in ApiSets if Runtime no longer needs them?

**Comment by ericstj** [comment]
We could treat them like the UNIX shims.

**Comment by weshaggard** [comment]
Yes lets do that.

**Comment by gkhanna79** [comment]
@weshaggard Assigned this to you to drive this ahead.

CC @rahku

**Comment by weshaggard** [comment]
I chatted with @gkhanna79 and for 1.0 rtm we are going to continue to have the Api-set package referenced from the runtime.

**Comment by gkhanna79** [comment]
Closing since this is done.

**Comment by weshaggard** [comment]
Nevermind my question on the other issue as this is the issue that removed the apiset dependency from the runtime package.

**Comment by weshaggard** [comment]
Although it would be good to link to the actual change that fixed this.

**Comment by gkhanna79** [comment]
Fixed in https://github.com/dotnet/coreclr/pull/8624
