### ISSUE TITLE
Corerun (or something) munges the task description on windows

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#4367]
When running the CoreCLR tests, the corerun processes hack the description seen in TaskManager to just say `build`.
This seems to be a recent innovation.

![image](https://cloud.githubusercontent.com/assets/10121823/14573796/1206a992-030c-11e6-8543-2ee84f06223b.png)

**Comment by AndyAyersMS** [comment]
(edit) -- it's the task description, not the command line.

**Comment by mikedn** [comment]
This probably entered with #4308 or a related change. CoreRun has a native.rc file which defines `#define FX_VER_FILEDESCRIPTION_STR "Microsoft CoreCLR EXE launcher\0"` but then there's fxver.rc and _version.h with their `#define VER_FILEDESCRIPTION_STR     "build"`

**Comment by joperezr** [comment]
Re-opening since we still need to consume the changes of buildtools in order for this to be fixed
