### ISSUE TITLE
PAL_VirtualUnwind - is there need to add special case for NetBSD?

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#4380]
File: src/pal/src/exception/seh-unwind.cpp

```
BOOL PAL_VirtualUnwind(CONTEXT *context, KNONVOLATILE_CONTEXT_POINTERS *contextPointers)
{
    int st;
    unw_context_t unwContext;
    unw_cursor_t cursor;

#if defined(__APPLE__) || defined(__FreeBSD__) || defined(_ARM64_) || defined(_ARM_)
    DWORD64 curPc;
#endif

    if ((context->ContextFlags & CONTEXT_EXCEPTION_ACTIVE) != 0)
    {
        // The current frame is a source of hardware exception. Due to the fact that
        // we use the low level unwinder to unwind just one frame a time, the
        // unwinder doesn't have the signal_frame flag set. So it doesn't
        // know that it should not decrement the PC before looking up the unwind info.
        // So we compensate it by incrementing the PC before passing it to the unwinder.
        // Without it, the unwinder would not find unwind info if the hardware exception
        // happened in the first instruction of a function.
        CONTEXTSetPC(context, CONTEXTGetPC(context) + 1);
    }

#if UNWIND_CONTEXT_IS_UCONTEXT_T
    WinContextToUnwindContext(context, &unwContext);
#else
    st = unw_getcontext(&unwContext);
    if (st < 0)
    {
        return FALSE;
    }
#endif
    st = unw_init_local(&cursor, &unwContext);
    if (st < 0)
    {
        return FALSE;
    }

#if !UNWIND_CONTEXT_IS_UCONTEXT_T
    // Set the unwind context to the specified windows context
    WinContextToUnwindCursor(context, &cursor);
#endif

#if defined(__APPLE__) || defined(__FreeBSD__) || defined(_ARM64_) || defined(_ARM_)
    // OSX and FreeBSD appear to do two different things when unwinding
    // 1: If it reaches where it cannot unwind anymore, say a 
    // managed frame.  It wil return 0, but also update the $pc
    // 2: If it unwinds all the way to _start it will return
    // 0 from the step, but $pc will stay the same.
    // The behaviour of libunwind from nongnu.org is to null the PC
    // So we bank the original PC here, so we can compare it after
    // the step
    curPc = CONTEXTGetPC(context);
#endif

    st = unw_step(&cursor);
    if (st < 0)
    {
        return FALSE;
    }

    // Check if the frame we have unwound to is a frame that caused
    // synchronous signal, like a hardware exception and record it
    // in the context flags.
    if (unw_is_signal_frame(&cursor) > 0)
    {
        context->ContextFlags |= CONTEXT_EXCEPTION_ACTIVE;
    }
    else
    {
        context->ContextFlags &= ~CONTEXT_EXCEPTION_ACTIVE;
    }

    // Update the passed in windows context to reflect the unwind
    //
    UnwindContextToWinContext(&cursor, context);
#if defined(__APPLE__) || defined(__FreeBSD__) || defined(_ARM64_) || defined(_ARM_)
    if (st == 0 && CONTEXTGetPC(context) == curPc)
    {
        CONTEXTSetPC(context, 0);
    }
#endif

    if (contextPointers != NULL)
    {
        GetContextPointers(&cursor, &unwContext, contextPointers);
    }
    return TRUE;
}
```

How to check if I need the extra code path enabled also for NetBSD?

**Comment by krytarowski** [comment]
@janvorli ^

**Comment by janvorli** [comment]
To check if you need that, just create a simple .NET app that throws an unhandled exception - as simple as throwing Exception from Main without any try / catch around it. If the app hangs, you need the workaround. If it prints the unhandled exception message and then dumps core, you don't.

**Comment by krytarowski** [comment]
I gave this a try:

```
diff --git a/src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest1.cpp b/src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest1.cpp
index 8aa7a0f..316dd17 100644
--- a/src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest1.cpp
+++ b/src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest1.cpp
@@ -28,31 +28,31 @@ int DllTest1()
 {
     Trace("Starting pal_sxs test1 DllTest1\n");
 
-    PAL_TRY(VOID*, unused, NULL)
-    {
+//    PAL_TRY(VOID*, unused, NULL)
+//    {
         volatile int* p = (volatile int *)0x11; // Invalid pointer
 
         bTry = TRUE;                            // Indicate we hit the PAL_TRY block
         *p = 1;                                 // Causes an access violation exception
 
         Fail("ERROR: code was executed after the access violation.\n");
-    }
-    PAL_EXCEPT(EXCEPTION_EXECUTE_HANDLER)
-    {
-        if (!bTry)
-        {
-            Fail("ERROR: PAL_EXCEPT was hit without PAL_TRY being hit.\n");
-        }
-
-        // Validate that the faulting address is correct; the contents of "p" (0x11).
-        if (ex.ExceptionRecord.ExceptionInformation[1] != 0x11)
-        {
-            Fail("ERROR: PAL_EXCEPT ExceptionInformation[1] != 0x11\n");
-        }
-
-        bExcept = TRUE;                         // Indicate we hit the PAL_EXCEPT block 
-    }
-    PAL_ENDTRY;
+//    }
+//    PAL_EXCEPT(EXCEPTION_EXECUTE_HANDLER)
+//    {
+//        if (!bTry)
+//        {
+//            Fail("ERROR: PAL_EXCEPT was hit without PAL_TRY being hit.\n");
+//        }
+//
+//        // Validate that the faulting address is correct; the contents of "p" (0x11).
+//        if (ex.ExceptionRecord.ExceptionInformation[1] != 0x11)
+//        {
+//            Fail("ERROR: PAL_EXCEPT ExceptionInformation[1] != 0x11\n");
+//        }
+//
+//        bExcept = TRUE;                         // Indicate we hit the PAL_EXCEPT block 
+//    }
+//    PAL_ENDTRY;
 
     if (!bTry)
     {
chieftec$ git diff src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest1.cpp|tee 
diff --git a/src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest1.cpp b/src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest1.cpp
index 8aa7a0f..316dd17 100644
--- a/src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest1.cpp
+++ b/src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest1.cpp
@@ -28,31 +28,31 @@ int DllTest1()
 {
     Trace("Starting pal_sxs test1 DllTest1\n");
 
-    PAL_TRY(VOID*, unused, NULL)
-    {
+//    PAL_TRY(VOID*, unused, NULL)
+//    {
         volatile int* p = (volatile int *)0x11; // Invalid pointer
 
         bTry = TRUE;                            // Indicate we hit the PAL_TRY block
         *p = 1;                                 // Causes an access violation exception
 
         Fail("ERROR: code was executed after the access violation.\n");
-    }
-    PAL_EXCEPT(EXCEPTION_EXECUTE_HANDLER)
-    {
-        if (!bTry)
-        {
-            Fail("ERROR: PAL_EXCEPT was hit without PAL_TRY being hit.\n");
-        }
-
-        // Validate that the faulting address is correct; the contents of "p" (0x11).
-        if (ex.ExceptionRecord.ExceptionInformation[1] != 0x11)
-        {
-            Fail("ERROR: PAL_EXCEPT ExceptionInformation[1] != 0x11\n");
-        }
-
-        bExcept = TRUE;                         // Indicate we hit the PAL_EXCEPT block 
-    }
-    PAL_ENDTRY;
+//    }
+//    PAL_EXCEPT(EXCEPTION_EXECUTE_HANDLER)
+//    {
+//        if (!bTry)
+//        {
+//            Fail("ERROR: PAL_EXCEPT was hit without PAL_TRY being hit.\n");
+//        }
+//
+//        // Validate that the faulting address is correct; the contents of "p" (0x11).
+//        if (ex.ExceptionRecord.ExceptionInformation[1] != 0x11)
+//        {
+//            Fail("ERROR: PAL_EXCEPT ExceptionInformation[1] != 0x11\n");
+//        }
+//
+//        bExcept = TRUE;                         // Indicate we hit the PAL_EXCEPT block 
+//    }
+//    PAL_ENDTRY;
 
     if (!bTry)
     {
```

And the result is as follows:

```
$ LD_LIBRARY_PATH=. ./paltest_pal_sxs_test1 
PAL_SXS test1 SIGSEGV handler 0x0
Starting pal_sxs test1 DllTest2
DLLTest2 PASSED
Starting pal_sxs test1 DllTest1
pal_sxs test1: signal handler called
ERROR: executed signal handler NOT from try/catch
```

Is it everything to check? Is it fine?

**Comment by janvorli** [comment]
No, I meant testing it with a managed app. Or, alternatively, you can try to get a current context somewhere with a call stack containing only native frames and then calling the PAL_VirtualUnwind on that context in a loop until you get zero in the IP. If it keeps looping forever, you need that fix. So something like this:
```C++
CONTEXT context;
RtlCaptureContext(&context);
do
{
     PAL_VirtualUnwind(&context, NULL);
}
while (GetIP(context) != 0);
```

**Comment by krytarowski** [comment]
Thank you, I will test it.

**Comment by myungjoo** [comment]
If you are confident with GDB and C/C++ programming, you may test with a sample C app that has functions calls from main() and see what libunwind (unw_step() ) returns with the topmost stack starting from main(). If cursor has already reached the topmost and calling unw_step() on the cursor again returns 0 and the same PC, you need this.

That "special" condition is required for the case where PAL_VirtualUnwind() does not properly tell you if it has reached the top (or the bottom depending on the convention) or not; e.g., PC in context is kept unchanged if it has reached the end.

**Comment by krytarowski** [comment]
It's worth to add such check for PAL tests.

According to my tests I think I need this patch too.

When running CoreFX tests, I have got more tests passed:

```
$ cat /tmp/log-without.txt   | gawk 'match($0, /Total: ([0-9]+), Errors: ([0-9]+), Failed: ([0-9]+), Skipped: ([0-9]+), Time: ([^s]+)s/, a) { t["Total"]+ 
Total: 19787 Errors: 0 Failed: 2 Skipped: 0 Time: 5494
$ cat /tmp/log-with.txt   | gawk 'match($0, /Total: ([0-9]+), Errors: ([0-9]+), Failed: ([0-9]+), Skipped: ([0-9]+), Time: ([^s]+)s/, a) { t["Total"]+ 
Total: 16655 Errors: 0 Failed: 2 Skipped: 0 Time: 4603

**Comment by krytarowski** [comment]
With increased timeout for a test from 15min to 45min:

```
Total: 89989 Errors: 0 Failed: 2 Skipped: 0 Time: 9797
```

**Comment by krytarowski** [comment]
Status update (Mon Apr 25 03:00:48 CEST 2016)

   Microsoft.CSharp.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 12,558s
   System.AppContext.Tests  Total: 15, Errors: 0, Failed: 0, Skipped: 0, Time: 17,236s
   System.Buffers.Tests  Total: 45, Errors: 0, Failed: 0, Skipped: 0, Time: 28,749s
   System.ComponentModel.Annotations.Tests  Total: 286, Errors: 0, Failed: 0, Skipped: 0, Time: 29,197s
   System.Collections.NonGeneric.Tests  Total: 738, Errors: 0, Failed: 0, Skipped: 0, Time: 62,855s
   System.Collections.Concurrent.Tests  Total: 154, Errors: 0, Failed: 0, Skipped: 0, Time: 290,486s
   System.Collections.Tests  Total: 19150, Errors: 0, Failed: 0, Skipped: 0, Time: 1078,366s
   System.Data.Common.Tests  Total: 3, Errors: 0, Failed: 0, Skipped: 0, Time: 11,615s
   System.ComponentModel.Tests  Total: 2, Errors: 0, Failed: 0, Skipped: 0, Time: 15,000s
   System.ComponentModel.Primitives.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 14,854s
   System.ComponentModel.EventBasedAsync.Tests  Total: 42, Errors: 0, Failed: 0, Skipped: 0, Time: 16,355s
   System.Composition.Convention.Tests  Total: 84, Errors: 0, Failed: 0, Skipped: 0, Time: 23,637s
   System.ComponentModel.TypeConverter.Tests  Total: 100, Errors: 0, Failed: 0, Skipped: 0, Time: 13,501s
   System.Console.Tests  Total: 94, Errors: 0, Failed: 1, Skipped: 0, Time: 46,106s
   System.Composition.Tests  Total: 143, Errors: 0, Failed: 0, Skipped: 0, Time: 46,670s
   System.Diagnostics.Contracts.Tests  Total: 22, Errors: 0, Failed: 0, Skipped: 0, Time: 7,879s
   System.Diagnostics.Tools.Tests  Total: 6, Errors: 0, Failed: 0, Skipped: 0, Time: 16,119s
   System.Diagnostics.TextWriterTraceListener.Tests  Total: 45, Errors: 0, Failed: 0, Skipped: 0, Time: 18,141s
   System.Drawing.Primitives.Tests  Total: 227, Errors: 0, Failed: 0, Skipped: 0, Time: 18,231s
   System.Diagnostics.DiagnosticSource.Tests  Total: 21, Errors: 0, Failed: 0, Skipped: 0, Time: 52,707s
   System.Diagnostics.Tracing.Tests  Total: 26, Errors: 0, Failed: 0, Skipped: 0, Time: 79,719s
   System.Globalization.Calendars.Tests  Total: 2086, Errors: 0, Failed: 0, Skipped: 0, Time: 63,208s
   System.IO.FileSystem.Primitives.Tests  Total: 4, Errors: 0, Failed: 0, Skipped: 0, Time: 12,405s
   System.IO.Compression.ZipFile.Tests  Total: 24, Errors: 0, Failed: 0, Skipped: 0, Time: 24,833s
   System.IO.UnmanagedMemoryStream.Tests  Total: 29, Errors: 0, Failed: 0, Skipped: 0, Time: 45,139s
   System.IO.Tests  Total: 417, Errors: 0, Failed: 0, Skipped: 0, Time: 44,399s
   System.IO.Packaging.Tests  Total: 131, Errors: 0, Failed: 0, Skipped: 0, Time: 45,442s
   System.Globalization.Tests  Total: 1278, Errors: 0, Failed: 1, Skipped: 0, Time: 76,717s
   System.Linq.Parallel.Tests  Total: 50904, Errors: 0, Failed: 0, Skipped: 0, Time: 945,631s
   System.Reflection.CoreCLR.Tests  Total: 4, Errors: 0, Failed: 0, Skipped: 0, Time: 13,463s
   System.Net.WebSockets.Tests  Total: 133, Errors: 0, Failed: 0, Skipped: 0, Time: 15,620s
   System.Reflection.DispatchProxy.Tests  Total: 22, Errors: 0, Failed: 0, Skipped: 0, Time: 18,712s
   System.Reflection.Emit.Lightweight.Tests  Total: 110, Errors: 0, Failed: 0, Skipped: 0, Time: 13,532s
   System.Reflection.Emit.Tests  Total: 704, Errors: 0, Failed: 0, Skipped: 0, Time: 24,752s
   System.ObjectModel.Tests  Total: 1828, Errors: 0, Failed: 0, Skipped: 0, Time: 75,896s
   System.Reflection.TypeExtensions.CoreCLR.Tests  Total: 8, Errors: 0, Failed: 0, Skipped: 0, Time: 16,702s
   System.Reflection.Extensions.Tests  Total: 39, Errors: 0, Failed: 0, Skipped: 0, Time: 19,583s
   System.Resources.Writer.Tests  Total: 7, Errors: 0, Failed: 0, Skipped: 0, Time: 16,217s
   System.Resources.Reader.Tests  Total: 25, Errors: 0, Failed: 0, Skipped: 0, Time: 18,992s
   System.Resources.ResourceManager.Tests  Total: 22, Errors: 0, Failed: 0, Skipped: 0, Time: 13,662s
   System.Resources.ReaderWriter.Tests  Total: 23, Errors: 0, Failed: 0, Skipped: 0, Time: 13,864s
   System.Reflection.TypeExtensions.Tests  Total: 598, Errors: 0, Failed: 0, Skipped: 0, Time: 14,640s
   System.Reflection.Metadata.Tests  Total: 153, Errors: 0, Failed: 0, Skipped: 0, Time: 59,440s
   System.Reflection.Tests  Total: 750, Errors: 0, Failed: 0, Skipped: 0, Time: 19,829s
   System.Runtime.InteropServices.Tests  Total: 11, Errors: 0, Failed: 0, Skipped: 0, Time: 18,072s
   System.Runtime.Loader.Tests  Total: 10, Errors: 0, Failed: 0, Skipped: 0, Time: 15,951s
   System.Runtime.Loader.DefaultContext.Tests  Total: 2, Errors: 0, Failed: 0, Skipped: 0, Time: 14,141s
   System.Runtime.Handles.Tests  Total: 9, Errors: 0, Failed: 0, Skipped: 0, Time: 14,914s
   System.Runtime.InteropServices.PInvoke.Tests  Total: 13, Errors: 0, Failed: 0, Skipped: 0, Time: 17,490s
   System.Runtime.Serialization.Json.Tests  Total: 110, Errors: 0, Failed: 0, Skipped: 0, Time: 52,236s
   System.Runtime.Serialization.Xml.Tests  Total: 141, Errors: 0, Failed: 0, Skipped: 0, Time: 83,981s
   System.Security.Claims.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 18,007s
   System.Threading.Tasks.Extensions.Tests  Total: 30, Errors: 0, Failed: 0, Skipped: 0, Time: 21,910s
   System.Text.Encoding.Extensions.Tests  Total: 126, Errors: 0, Failed: 0, Skipped: 0, Time: 25,982s
   System.Text.RegularExpressions.Tests  Total: 825, Errors: 0, Failed: 0, Skipped: 0, Time: 38,855s
   System.Text.Encoding.Tests  Total: 697, Errors: 0, Failed: 0, Skipped: 0, Time: 25,637s
   System.Threading.Tasks.Parallel.Tests  Total: 160, Errors: 0, Failed: 0, Skipped: 0, Time: 61,195s
   System.Threading.Tasks.Dataflow.Tests  Total: 319, Errors: 0, Failed: 0, Skipped: 0, Time: 519,887s
   System.Text.Encodings.Web.Tests  Total: 302, Errors: 0, Failed: 0, Skipped: 0, Time: 2441,658s
   System.Threading.Timer.Tests  Total: 27, Errors: 0, Failed: 0, Skipped: 0, Time: 17,102s
   System.ValueTuple.Tests  Total: 23, Errors: 0, Failed: 0, Skipped: 0, Time: 20,501s
   System.Threading.Tests  Total: 124, Errors: 0, Failed: 0, Skipped: 0, Time: 317,805s
   System.Xml.RW.XmlReader.Tests  Total: 8, Errors: 0, Failed: 0, Skipped: 0, Time: 16,020s
   System.Xml.RW.XmlWriter.Tests  Total: 12, Errors: 0, Failed: 0, Skipped: 0, Time: 15,565s
   System.Xml.RW.XmlSystemPathResolver.Tests  Total: 4, Errors: 0, Failed: 0, Skipped: 0, Time: 19,224s
   System.Xml.RW.XmlReader.ReadContentAs.Tests  Total: 667, Errors: 0, Failed: 0, Skipped: 0, Time: 17,020s
   System.Xml.XDocument.Axes.Tests  Total: 36, Errors: 0, Failed: 0, Skipped: 0, Time: 20,066s
   System.Xml.XDocument.Properties.Tests  Total: 176, Errors: 0, Failed: 0, Skipped: 0, Time: 30,148s
   System.Xml.XDocument.SDMSample.Tests  Total: 106, Errors: 0, Failed: 0, Skipped: 0, Time: 26,010s
   System.Xml.XDocument.xNodeReader.Tests  Total: 5, Errors: 0, Failed: 0, Skipped: 0, Time: 13,161s
   System.Xml.XDocument.TreeManipulation.Tests  Total: 2, Errors: 0, Failed: 0, Skipped: 0, Time: 14,460s
   System.Xml.XDocument.xNodeBuilder.Tests  Total: 19, Errors: 0, Failed: 0, Skipped: 0, Time: 12,254s
   System.Xml.XDocument.Streaming.Tests  Total: 41, Errors: 0, Failed: 0, Skipped: 0, Time: 138,247s
   System.Xml.XDocument.Misc.Tests  Total: 285, Errors: 0, Failed: 0, Skipped: 0, Time: 280,619s
   System.Xml.XDocument.Events.Tests  Total: 264, Errors: 0, Failed: 0, Skipped: 0, Time: 761,947s
   System.Xml.XPath.XmlDocument.Tests  Total: 1477, Errors: 0, Failed: 0, Skipped: 0, Time: 82,982s
   System.Xml.XPath.Tests  Total: 1477, Errors: 0, Failed: 0, Skipped: 0, Time: 116,676s
   System.Xml.XPath.XDocument.Tests  Total: 1475, Errors: 0, Failed: 0, Skipped: 0, Time: 595,527s
   System.Net.NameResolution.Functional.Tests  Total: 3, Errors: 0, Failed: 0, Skipped: 0, Time: 11,859s
   Common.Tests  Total: 352, Errors: 0, Failed: 0, Skipped: 0, Time: 233,958s
   System.Globalization.Extensions.Tests  Total: 172, Errors: 0, Failed: 0, Skipped: 0, Time: 384,277s
   System.Private.Uri.Tests  Total: 128, Errors: 0, Failed: 0, Skipped: 0, Time: 12,986s

Total: 90143 Errors: 0 Failed: 2 Skipped: 0 Time: 9998
