### ISSUE TITLE
Dockerize coreclr

### ISSUE THREAD

**Issue by andredublin** [dotnet/coreclr#44]
This might not be the place to put this issue but how about adding a docker image of coreclr?

**Comment by davidfowl** [comment]
@andredublin what would you do with it?

**Comment by andredublin** [comment]
@davidfowl not sure yet, but maybe package it as a dockerized runtime container that can be used to compile code against might be one use case.

**Comment by kangaroo** [comment]
Is this an issue?  If someone wants to do this, and push it to the docker registry, fantastic.  I'm not sure how this is an issue for the repo tho?

**Comment by MattWhilden** [comment]
This doesn't seem actionable from our side. I'm going to close this out. Let me know if it's in error.

If someone gets around to dockerizing this and has issues that they need help with from our end. Let us know.
