### ISSUE TITLE
Callstack is trashed after an exception

### ISSUE THREAD

**Issue by bendono** [dotnet/coreclr#4402]
The native callstack is trashed after a managed exception is thrown.

Environment: Windows 7 64-bit.

Reproduction steps:
1. Compile a simple program that throws an uncaught exception. Example used here:
`
using System;

public class Foo
{
	public Foo()
	{
		Console.WriteLine("[Foo] Constructor");
	}

	public void Set(object o)
	{
		Console.WriteLine("[Foo] Set");

		if (o != null)
		{
			InternalSet(o);
		}
	}

	private void InternalSet(object o)
	{
		Console.WriteLine("[Foo] InternalSet: {0}", o);
	}
}

public class Program
{
	private static Foo foo = new Foo();

	public static void Main (string[] args)
	{
		A();
		foo.Set(123);
	}

	static void A()
	{
		Console.WriteLine("A");
		B();
	}

	static void B()
	{
		Console.WriteLine("B");
		foo.Set("abc");
		C();
	}

	static void C()
	{
		Console.WriteLine("C");
		Error();
	}

	static void Error()
	{
		foo.Set("Error!");
		throw new Exception();
	}
}
`

2. Run above assembly in a debugger. Using WinDbg here.
3. Wait until coreclr loads.
	sxe ld coreclr
	g
4. Set breakpoint.
	bp CoreCLR!RunMain
	g
5. Step through until "EX_END_NOCATCH" near the end of the function.
6. Check the call stack.
![01](https://cloud.githubusercontent.com/assets/846533/14628110/cbb5a3bc-0635-11e6-9209-f1f61b1b0397.png)

Comment: Looks good. NTDLL starts a user thread and CoreRun starts, and CoreCLR runs. All as expected.

7: Step over the above "EX_END_NOCATCH".
There is now a CLR exception, presumably the one thrown in the sample assembly.
![02](https://cloud.githubusercontent.com/assets/846533/14628116/d80b7a2e-0635-11e6-8a27-c46ef0ab7034.png)

8: Check the stack to see where we are.
![03](https://cloud.githubusercontent.com/assets/846533/14628123/e61954e2-0635-11e6-954e-86d346e210b8.png)

Not a very useful stacktrace... It looks like the stack has been trashed.
I would expect to continue to see the CLR and CoreRun frames, as well as the standard ntdll!RtlUserThreadStart at the bottom.

**Comment by jkotas** [comment]
The "Unable to read dynamic function table entries" error messages are WinDbg security feature that prevents loading unknown out of proc stack walkers. To get rid of these errors:

- Add the full path to mscordaccore.dll that lives next to the coreclr.dll to `HKLM\Software\Microsoft\Windows NT\CurrentVersion\KnownFunctionTableDlls` registry key
--- or --- 
- Run `.settings set EngineInitialization.VerifyFunctionTableCallbacks=false` on windbg prompt. It will allow windbg to load arbitrary out-of-process callback dlls.
--- or ---
- (Least secure) Run `.settings set EngineInitialization.VerifyFunctionTableCallbacks=false` followed by `.settings save`. It will persist setting for all future debugger launches.

**Comment by jkotas** [comment]
cc @mikem8361

**Comment by bendono** [comment]
@jkotas Thank you. I was not aware that mscordacwks.dll needed to be whitelisted in KnownFunctionTableDlls. Full .Net seems to register it, too, which is obviously why I have not run into this before. After doing that, the stack looks good:
![04](https://cloud.githubusercontent.com/assets/846533/14630421/968a7cc2-0648-11e6-9644-e3724d794d93.png)

As does the mixed stack trace:
![05](https://cloud.githubusercontent.com/assets/846533/14630443/b98cdb7a-0648-11e6-90fe-59dc998d9ad4.png)

So this issue can probably be closed.
However, regarding the need to register mscordacwks.dll in M\Software\Microsoft\Windows NT\CurrentVersion\KnownFunctionTableDlls, I can see this becoming a minor frustration point for developers in the future. With Full .Net, the installation had a fixed path at Windows\Microsoft.NET\Framework\<version>\mscordacwks.dll, so it is easy enough to register once and be done with it. However, CoreCLR being a private deployment does not have a fixed path. There could even be multiple copies of it on a single machine. Of the three options that you gave to handle this, registering the full path in the registry is ideal, but not practical for CoreCLR. Manually disabling it each time is undesirable, and disabling the error opens security issues. A fourth option seems to be needed. Is there anything that can be done on the side of CoreCLR to make this a non-issue?

**Comment by jkotas** [comment]
We should set the registry key for the shared runtime installed via the MSI. It will fix the problem for some cases at least.

**Comment by mikem8361** [comment]
I'll do that but it won't help the standalone case.  Isn't that more typical?

**Comment by jkotas** [comment]
Depend on the defaults for given app type, e.g. I believe that ASP.NET apps default to use the shared runtime.

**Comment by bendono** [comment]
Hi @mikem8361 . I rebuilt the repository and dumping the stack works without need of disabling the warning about dynamic functions. It is convenient that it is disabled when SOS is loaded. However, not sure if it is related to this change or not, but the resulting stack dumps no longer look correct. Using the same sample program as above, the new mixed mode callstack and native callstacks are as follows:
![13](https://cloud.githubusercontent.com/assets/846533/14774306/cf2557e0-0aef-11e6-9bd7-f789f9b117e3.png)

Compared to the above, earlier screen capture, there is significant number of frames missing in both. Everything before the managed assembly begins is missing: ntdll!RtlUserThreadStart, kernel32!BaseThreadInitThunk, CoreCLR!wmain, TryRun, ExecuteAssemebly, RunMain.

As this is happening to k as well, though, it might be related. Not sure.

**Comment by mikem8361** [comment]
I'm not sure why.  Could you try to unload sos to eliminate it as the problem? sos can affect even the "k" command. If the native frame is still incomplete, maybe the windbg unwinder is having problems with the jit'ted code now (meaning the jit is producing invalid unwind info or something).

**Comment by mikem8361** [comment]
I just sync'ed to the latest and tried your test app and both clrstack -f and k displayed the full stack. Did you copy the CoreClr.dll pdb?

0:000> !clrstack -f
OS Thread Id: 0xca94 (0)
        Child SP               IP Call Site
000000d11fbccbb0 00007ffb6c401f28 KERNELBASE!RaiseException + 104
000000d11fbccc90 00007ffb276aca23 CoreCLR!`RaiseTheExceptionInternalOnly'::`81'::__Body::Run + 883 at c:\ssd\coreclr\src\vm\excep.cpp:3114
000000d11fbccdd0 00007ffb276a6256 CoreCLR!RaiseTheExceptionInternalOnly + 1750 at c:\ssd\coreclr\src\vm\excep.cpp:3114
000000d11fbccfb0 00007ffb27762c26 CoreCLR!IL_Throw + 1126 at c:\ssd\coreclr\src\vm\jithelpers.cpp:5378
000000d11fbcd1a8                  [HelperMethodFrame: 000000d11fbcd1a8] 
000000d11fbcd4b0 00007ffac8ae2fc5 HelloWorld4.exe!Program.Error() + 133 [c:\ssd\builds\HelloWorld\HelloWorld4.cs @ 56]
000000d11fbcd500 00007ffac8ae2f21 HelloWorld4.exe!Program.C() + 49 [c:\ssd\builds\HelloWorld\HelloWorld4.cs @ 52]
000000d11fbcd530 00007ffac8ae2c95 HelloWorld4.exe!Program.B() + 117 [c:\ssd\builds\HelloWorld\HelloWorld4.cs @ 46]
000000d11fbcd570 00007ffac8ae0a11 HelloWorld4.exe!Program.A() + 49 [c:\ssd\builds\HelloWorld\HelloWorld4.cs @ 39]
000000d11fbcd5a0 00007ffac8ae04b7 HelloWorld4.exe!Program.Main(System.String[]) + 55 [c:\ssd\builds\HelloWorld\HelloWorld4.cs @ 32]
000000d11fbcd600 00007ffb27f03783 CoreCLR!CallDescrWorkerInternal + 131 at c:\ssd\coreclr\src\vm\amd64\CallDescrWorkerAMD64.asm:101
000000d11fbcd640 00007ffb27a1448e CoreCLR!CallDescrWorkerWithHandler + 478 at c:\ssd\coreclr\src\vm\callhelpers.cpp:90
000000d11fbcd6c0 00007ffb27a1525b CoreCLR!MethodDescCallSite::CallTargetWorker + 3515 at c:\ssd\coreclr\src\vm\callhelpers.cpp:635
000000d11fbcdd20 00007ffb274dd9cd CoreCLR!MethodDescCallSite::Call + 29 at c:\ssd\coreclr\src\vm\callhelpers.h:420
000000d11fbcdd50 00007ffb279b2da5 CoreCLR!``RunMain'::`30'::__Body::Run'::`5'::__Body::Run + 597 at c:\ssd\coreclr\src\vm\assembly.cpp:2592
000000d11fbcddf8                  [GCFrame: 000000d11fbcddf8] 
000000d11fbcdf00 00007ffb279b2f05 CoreCLR!`RunMain'::`30'::__Body::Run + 133 at c:\ssd\coreclr\src\vm\assembly.cpp:2608
000000d11fbcdf80 00007ffb279b320e CoreCLR!RunMain + 414 at c:\ssd\coreclr\src\vm\assembly.cpp:2608
000000d11fbce020 00007ffb279ab372 CoreCLR!Assembly::ExecuteMainMethod + 1042 at c:\ssd\coreclr\src\vm\assembly.cpp:2715
000000d11fbce4e0 00007ffb274e2534 CoreCLR!CorHost2::ExecuteAssembly + 1316 at c:\ssd\coreclr\src\vm\corhost.cpp:1343
000000d11fbce6e0                  [GCFrame: 000000d11fbce6e0] 
000000d11fbce7a0 00007ff76b655ef8 CoreRun!TryRun + 3160 at c:\ssd\coreclr\src\coreclr\hosts\corerun\corerun.cpp:572
000000d11fbcf810 00007ff76b6574cb CoreRun!wmain + 331 at c:\ssd\coreclr\src\coreclr\hosts\corerun\corerun.cpp:685
000000d11fbcf8b0 00007ff76b6efb04 CoreRun!invoke_main + 52 at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:80
000000d11fbcf8f0 00007ff76b6efa0e CoreRun!__scrt_common_main_seh + 302 at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:255
000000d11fbcf950 00007ff76b6ef8ce CoreRun!__scrt_common_main + 14 at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:300
000000d11fbcf980 00007ff76b6efb19 CoreRun!wmainCRTStartup + 9 at f:\dd\vctools\crt\vcstartup\src\startup\exe_wmain.cpp:17
000000d11fbcf9b0 00007ffb6d618102 KERNEL32!BaseThreadInitThunk + 34
000000d11fbcf9e0 00007ffb6f3fc5b4 ntdll!RtlUserThreadStart + 52

**Comment by bendono** [comment]
Hi @mikem8361 . Sorry for the delayed response. I doubled checked this today. I re-synced and re-built everything. I have ProcDump (Sysinternals) setup as the AeDebug postmortem debugger. This can be setup with the following command line: `procdump -ma -i C:\Dumps` . This is to catch any crashing processes for later analysis. Coincidentally, this sample program throws an exception so that I can easily load the dump in WinDbg.

Indeed, with the latest build, the displayed callstack is incomplete. As shown below, the symbols are available and SOS is not yet loaded. (Loading SOS does not make a difference, though.)
![15](https://cloud.githubusercontent.com/assets/846533/14840027/f38bc246-0c6a-11e6-8fe8-e86273f740fc.png)

This analysis was done on a Windows 7 Enterprise machine with WinDbg 10.0.10586.567, which I think is the latest publicly released version. Copying the same dump (and symbols) to a Windows 10 machine (same WinDbg version) produces the same incomplete callstack.

However, live debugging does not have this problem. In other words, 1) start CoreRun in WinDbg with HelloWorld.exe as the argument, 2) set sxe clr to break on all managed exceptions, then 3) dump the stack with k works as expected. Here is the callstack on the same Win7 machine as above.
![16](https://cloud.githubusercontent.com/assets/846533/14840097/bfa626b4-0c6b-11e6-84b2-10ae7825696a.png)

If you think it would useful, I can upload the dump file (and optionally symbols) to OneDrive or Dropbox. Let me know.

**Comment by mikem8361** [comment]
Since sos hasn’t been loaded there isn’t anything I can do other than trying to run this command:

.settings set EngineInitialization.VerifyFunctionTableCallbacks=false

**Comment by bendono** [comment]
@mikem8361 Thanks for the suggestion. I gave it a try on the same dump, but there were no differences.
![17](https://cloud.githubusercontent.com/assets/846533/14840755/18838a28-0c72-11e6-9156-0eda8d7dddd6.png)

**Comment by mikem8361** [comment]
@jkotas and @janvorli do you guys have any ideas?

**Comment by jkotas** [comment]
The public and MS-internal windbg builds have different behaviors. In the public builds, you can get the managed stacktrace via the sos command only. In the MS-internal builds, you can get the managed stacktrace via regular `k` command as well.
