### ISSUE TITLE
Build.cmd fails to download necessary files

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/coreclr#4407]
With the latest coreclr checkout, when running `build clean` on Windows 7, one of the initial steps is to download build tools. This step is currently failing:

```
D:\DevFolder\coreclr>build clean
BUILD: Commencing CoreCLR Repo build
BUILD: Doing a clean build
Could Not Find D:\DevFolder\coreclr\bin\Logs\*_Windows_NT__x64__Debug.*
BUILD: Checking prerequisites
Installing dotnet cli...
ERROR: Could not install dotnet cli correctly. See 'D:\DevFolder\coreclr\init-tools.log' for more details.
ERROR: Could not restore build tools.
```

The contents of `init-tools.log`:

> Running "D:\DevFolder\coreclr\"init-tools.cmd 
> Installing 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0-beta-002173/dotnet-dev-win-x64.1.0.0-beta-002173.zip' to 'D:\DevFolder\coreclr\Tools\dotnetcli\dotnet-dev-win-x64.1.0.0-beta-002173.zip' 
> Exception calling "DownloadFile" with "2" argument(s): "The operation has 
> timed out"
> At line:1 char:1
> - (New-Object 
>   Net.WebClient).DownloadFile('https://dotnetcli.blob.core.windows.net ...
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> ```
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : WebException
> 
> Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find 
> file 'D:\DevFolder\coreclr\Tools\dotnetcli\dotnet-dev-win-x64.1.0.0-beta-0
> 02173.zip'."
> At line:1 char:369
> + (New-Object 
> Net.WebClient).DownloadFile('https://dotnetcli.blob.core.windows.net ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> ```
> + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
> + FullyQualifiedErrorId : FileNotFoundException
> ```

This appears to be a problem of poor synchronization between the build script and the servers.  Can someone look into it?

**Comment by adityamandaleeka** [comment]
@masonwheeler Are you still facing this problem?
