### ISSUE TITLE
What is Ready2Run?

### ISSUE THREAD

**Issue by svick** [dotnet/coreclr#4417]
I've found some references mentioning the AOT technology Ready2Run (mostly in issues), but what I haven't found (by searching this repo or googling) is any actual documentation or explanation about it. My questions:

* What is Ready2Run?
* Where is it documented?
* What is the difference between Ready2Run and NGEN?

**Comment by mikedn** [comment]
Hmm, did you find [this](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/readytorun-overview.md) in your searches?

**Comment by svick** [comment]
Oh, it's ReadyToRun, not Ready2Run, thanks.

**Comment by omariom** [comment]
Always wanted to ask but didn't dare to know )
