### ISSUE TITLE
Regression failure: AboveStackLimit

### ISSUE THREAD

**Issue by japj** [dotnet/coreclr#442]
Running all the tests on the current master tree resulted in a failure:

<pre>
BEGIN EXECUTION
"C:\GitHub\coreclr\tests\..\binaries\tests\Windows_NT.x64.debug\\Tests\Core_Root\corerun.exe" "AboveStackLimit.exe"  
**** MessageBox invoked, title 'CoreRun.exe - Assert Failure (PID 30900, Thread 30904/78b8)        ' ****
  Assertion failed 'initReg == REG_EAX' in 'Test:Main():int' (IL size 48301)

c:\github\coreclr\src\jit\codegencommon.cpp, Line: 5430

Abort - Kill program
Retry - Debug
Ignore - Keep running

Image:
C:\GitHub\coreclr\binaries\tests\Windows_NT.x64.debug\Tests\Core_Root\CoreRun.exe

********

Expected: 100
Actual: 255
END EXECUTION - FAILED
FAILED

Test Harness Exitcode is : 1
</pre>

**Comment by japj** [comment]
This is on a Windows8.1 Pro machine, AMD Athlon X4 760K, 32Gb memory.
Using Visual Studio 2013 Premium Update 4

**Comment by jkotas** [comment]
@japj Thank you for noticing it!

@mmitche It is failing in the CI as well, but it is not highlighted in red - it is easy to miss. Would it be possible to show the CI result in red if there are any test failures?

@LLITCHEV This regression was likely introduced by one of your recent changes. Could you please take a look ASAP?

**Comment by japj** [comment]
Jenkins thinks build 219 was the first with this issue at 
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_windows_debug/219/ 
the related commit is https://github.com/dotnet/coreclr/commit/676045c22be1eb8edda157fad496deeba2f79fe4

**Comment by LLITCHEV** [comment]
Thank you very much for noticing this, Jeroen.
Could you, please tell me the test that fails? You can drop me the source at my public Microsoft e-mail. Thank you so much, again!

**Comment by japj** [comment]
It might be a little difficult to see in the console output I pasted but it is the AboveStackLimit testcase that is failing.

Sourcecode is at https://github.com/dotnet/coreclr/blob/master/tests/src/Regressions/common/AboveStackLimit.cs

**Comment by LLITCHEV** [comment]
Thanks much again!

**Comment by mmitche** [comment]
@jkotas There's no way to directly highlight the console output log, but you'll notice that the test failure is directly called out on the build page

**Comment by LLITCHEV** [comment]
Addressed by https://github.com/dotnet/coreclr/pull/484

**Comment by LLITCHEV** [comment]
Merged fix in master.
