### ISSUE TITLE
ARM, SOS: failed to load sos.so with lldb + libsosplugin.so

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#4428]
I'm getting this error when I try to run any `sos` command

```
(lldb) sos ClrStack
dlopen(/home/sean/xp_seanrpi2/dotnet.38/libsos.so) failed /home/.../libsos.so:
undefined symbol: _ZTV10ARMMachine
```
Anyone know or managed to handle this?

Environment
* running in Raspberry Pi 2 wit Ubuntu mate (15.10) 
* CoreCLR + CoreFX + LLDB-3.8

Symbols are listed but seems undefined.
```
$ readelf -a libsos.so | grep _ZTV10ARMMachine
000b40ec  00004215 R_ARM_GLOB_DAT    00000000   _ZTV10ARMMachine
    66: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZTV10ARMMachine
 27894: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZTV10ARMMachine
```

I've built coreclr like this.
```
ROOTFS_DIR=(path to rootfs of ARM Ubuntu 15.10) \
LLDB_LIB_DIR=(path to arm llvm lib) \
LLDB_INCLUDE_DIR=/(path to arm llvm include) \
./build.sh arm cross skipmscorlib clang3.8 skiptests
```
I've added some changes to work with LLVM-3.8 (clang, lldb):  https://github.com/seanshpark/coreclr/commit/05a2c9a69ae872dd7a54ecc7731a69bf17c65976

**Comment by seanshpark** [comment]
A simple test I've done with `clang++` in Ubuntu 14.04 x86_64

Source code: testARM.cpp
```
class MyIMachine {
public:
  virtual void DoTest() = 0;
protected:
  MyIMachine()  {}
  virtual ~MyIMachine() {}
};

class MyARMMachine : public MyIMachine {
public:
  static MyIMachine* GetInstance()
    { static MyARMMachine s_ARMMachineInstance; return &s_ARMMachineInstance; }

  virtual void DoTest();

private:
  MyARMMachine()  {}
  ~MyARMMachine() {}
  MyARMMachine(const MyARMMachine& machine);      // undefined
  MyARMMachine & operator=(const MyARMMachine&);  // undefined
};

inline void MyARMMachine::DoTest() {

}
```

compile for x86_64 native:
```
clang++ -o testARM.cpp.o -c testARM.cpp
```
and the symbol:
```
$ nm testARM.cpp.o
0000000000000000 r GCC_except_table2
                 U __gxx_personality_v0
                 U _Unwind_Resume
                 U _ZdlPv
0000000000000000 W _ZN10MyIMachineD2Ev
0000000000000000 W _ZN12MyARMMachine6DoTestEv
0000000000000000 W _ZN12MyARMMachineD0Ev
0000000000000000 W _ZN12MyARMMachineD2Ev
0000000000000000 V _ZTI10MyIMachine
0000000000000000 V _ZTI12MyARMMachine
0000000000000000 V _ZTS10MyIMachine
0000000000000000 V _ZTS12MyARMMachine
0000000000000000 V _ZTV12MyARMMachine
                 U _ZTVN10__cxxabiv117__class_type_infoE
                 U _ZTVN10__cxxabiv120__si_class_type_infoE
```

cross compile to ARM
```
clang++ --sysroot=/home/maxwell/zarm-rootfs-wily \
-target armv7-linux-gnueabihf -mthumb -mfpu=vfpv3 \
-o testARM.cpp.o -c testARM.cpp
```

and the symbol for ARM:
```
$ nm testARM.cpp.o
00000000 n $d.0
00000000 n $d.1
```
Anyone know about what I am missing with the options maybe? or this is absolutely normal?

where clang is 
```
$ clang++ -v
clang version 3.8.1 (https://github.com/llvm-mirror/clang.git 9fd77bd68130d9b2fbc56a3138b6f981d560480a) (https://github.com/llvm-mirror/llvm.git 8b47c17a53d683f313eaaa93c4a53de26d8fcba5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/maxwell/bin/llvm/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

when using g++ / arm-linux-gnueabi-g++, same thing happens.

**Comment by manu-silicon** [comment]
I'm no C++ expert but objdump -d on the generated .o file shows that no code is being generated at all! 
So this is not surprising that you have unresolved externals.

**Comment by seanshpark** [comment]
@manu-silicon , thank you for the comment.
> that no code is being generated at all! 
yes, I think this is the problem. When I run `sos ClrStack` in lldb, it fails in `dlopen` maybe cause of no vtable symbol. 
>  you have unresolved externals.
Can you point what is the externals in above test code? or what I should do?

**Comment by manu-silicon** [comment]
Someone with more C++ knowledge would know what is happening. I also checked that g++ does the exact same thing on arm.

**Comment by myungjoo** [comment]
Maybe sos-arm is trying to use `ARMMachine(const ARMMachine& machine);`, not `ARMMachine();`. `SOS_TARGET_ARM` is surely defined during the build, right?

**Comment by seanshpark** [comment]
@myungjoo , problem seems not with SOS but how ARM compiler works with above `testARM.cpp` source. It doesn't generate any code in compile time.

**Comment by myungjoo** [comment]
Yeah... this looks like ARM compiler bugs. However, if you pull ARMMachine::ARMMachine() out of class declaration (take all method definitions out of class):

```
class ARMMachine{
...
};

ARMMachine::ARMMachine() {}
```

suddenly we get proper objects.

This Is Really Strange. (may need to report for both gcc and llvm community)

**Comment by seanshpark** [comment]
@myungjoo , Yes, something like that. I think we've to go with a workaround. There needs some changes in also SOS/Strike/disasmARM.cpp. I'll make a PR.

**Comment by seanshpark** [comment]
I may have to wait a patch to enable `lldb-3.8` before making this PR.

**Comment by myungjoo** [comment]
GCC-ARM optimises this out thinking it is an inline function.
-fkeep-inline-functions allows GCC-ARM to keep the function definitions intact.
Maybe Clang has similar options to give you easy workaround as well..

**Comment by seanshpark** [comment]
Couldn't find something like `-fkeep-inline-functions` in Clang. :(

**Comment by seanshpark** [comment]
Closing this issue, PR has landed.
