### ISSUE TITLE
Versioning and loading libraries

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#444]
As discussed in #441, we are currently brittle with regards to our usage of dlopen, which requires that we provide the name of a library that includes version information.  We need to figure out how we want to handle this, for the specific case discussed in #441, for DllImports in general, and for anywhere else we may rely on loading arbitrary libraries.

**Comment by Tragetaschen** [comment]
FWIW, that's already a common grief for users of aspnet/KestrelHttpServer on Linux, so it would be great if this becomes a general solution that is available for all packages outside.

Usually, you use something like `pkg-config` to learn about the installed library version when building from source and calling the C-linker.

Mono uses `<dllmap/>` in global and application specific `config` files to translate between a library name on a DllImport and the versioned library name like `libc` -> `libc.so.6`. The global `/etc/mono/config` is distribution-specific and filled when mono is built for that distribution.

**Comment by akoeplinger** [comment]
As @Tragetaschen said, this is a common problem and Mono's solution to this is dllmap as described [here](http://www.mono-project.com/docs/advanced/pinvoke/#library-names).

While browsing the net, I found that Julia also has an interesting approach: they [provide an api](https://github.com/JuliaLang/julia/blob/6856f9db32de2d8f547455319c9cee2e842db1c3/src/ccall.cpp#L5-L86) that reads the output of `/sbin/ldconfig -p` and creates a map of all the libraries, e.g.:
```
$ /sbin/ldconfig -p | grep libcrypto
	libcrypto.so.1.0.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
```

... which means one can just call the wrapper function with the "simple" module name and get pack the proper name incl. version.

**Comment by kangaroo** [comment]
The Julia approach seems particularly nice, I've never liked having to ship dllmaps, they're a pain and confusing for users.

**Comment by natemcmaster** [comment]
I also agree that dllMaps are ugly, but it would be good to have a general solution for per-platform library names. 

Adding to Kestrel user's grief: trying to get [Microsoft.Data.Sqlite](https://github.com/aspnet/Microsoft.Data.Sqlite) to load native sqlite calls is pain because DllImportAttribute requires a constant library name. On Windows it's "sqlite3" and OS X and *nix it's "libsqlite3".

**Comment by bricelam** [comment]
Please, please, please build on [all the great work of Mono](http://www.mono-project.com/docs/advanced/pinvoke/).

**Comment by jeffschwMSFT** [comment]
https://github.com/dotnet/coreclr/pull/19373

**Comment by swaroop-sridhar** [comment]
Closing this issue, the matter is tracked by dotnet/corefx#32015.
