### ISSUE TITLE
Marshal.AllocHGlobal should not throw OOM Exception

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/coreclr#4440]
Calls to `Marshal.AllocHGlobal` should not throw `System.OutOfMemoryException` since that may not actually be the reason for failure to allocate. In addition many times when a developer is explicitly allocating unmanaged memory in .NET they can recover from the failure themselves. 

In .NET Framework I worked around this by simply making my own "Alloc" method that called `LocalAlloc` itself and threw `System.InsufficientMemoryException` on failure with a `System.ComponentModel.Win32Exception` as the inner exception with the real issue. This allowed me to handle the issue myself, and sometimes the answer was to shutdown. Obviously this solution is Windows only so cannot be used for .NET Core but I believe something like it should be used.

**Comment by yizhang82** [comment]
@SamuelEnglard Always throwing OutOfMemoryException might be overly simplifying, but I'd be curious  to see what kind of specific errors you are interested with LocalAlloc. Do you have some examples?

**Comment by SamuelEnglard** [comment]
I don't remember the exact error messages but they were fragmentation issues not a lack of actual memory

**Comment by yizhang82** [comment]
I see. But in that case what would you do?
I would expect such fragmentation issues are typically difficult to handle - you need to try different strategy if the memory becomes fragmented, for example, free some extra memory, and try again. And even then it is difficult to predict whether it is going to help it succeed or not. I would argue that for such sophisticated applications that handle memory allocation strategies, the convenience of having Marshal.AllocHGlobal telling you the exact error seems pretty small - you are probably rolling your own memory management cache/pool anyway. I remembered in the past someone suggested a somewhat related idea - to do a GC and try the allocation again if OutOfMemoryException were to thrown. For similar reasons, I don't think that we should put such policy into simple allocation functions like this into the APIs.

**Comment by SamuelEnglard** [comment]
I was in fact rolling my own pool. 

I don't think i would call anything on the `Marshal` class simple. Any developer using those APIs is doing something complex.

Maybe the solution is a different or overload of `AllocHGlobal` that doesn't throw OOM?

**Comment by yizhang82** [comment]
@SamuelEnglard We could add an overload in theory, but again most people wouldn't use this overload because they would prefer the OOM overload. I think the right solution here would be defining your own p/invoke and wrap it with the right error recovery strategy that is tailored for your application. I'm closing this issue for now as I'm not seeing strong value in this new API proposal. Please feel free to let us know if you believe otherwise.

**Comment by SamuelEnglard** [comment]
I can see you're points. I think I'll look into adding that as something to add to the documentation for the API though.
