### ISSUE TITLE
[Unix] CORINFO_HELP_STOP_FOR_GC helper preserves all registers that can be used for return values.  But on Unix JIT is modelling this helper call as preserving rax/xmm0 only.

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#4445]
See vm\amd64\unixasmhelpers.S:: JIT_RareDisableHelper.  

Look at RBM_STOP_FOR_GC_TRASH definition for amd64 unix.

**Comment by janvorli** [comment]
@sivarv This file is not used for Unix. The Unix implementation is in vm\amd64\asmHelpers.S and it saves all of those four registers.

**Comment by sivarv** [comment]
@janvorli - Thanks.

Jit is still modelling this helper call as preserving just rax/xmm0 on Unix.  This can be improved since VM helper is saving all 4 return regs.  I am going to re-purpose this bug for JITchange.
