### ISSUE TITLE
ARM64: Funclet calling convention

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#4465]
The funclet argument order used on x64 - first arg is establisher frame first, exception object second - allows for more compatibility between the various runtimes. We should change ARM64 to use the same order (it is passing the exception object first currently).

category:cq
theme:runtime
skill-level:intermediate
cost:small

**Comment by jkotas** [comment]
cc @russellhadley @BruceForstall

**Comment by BruceForstall** [comment]
@briansull @kyulee1 Kyungwoo: maybe you should take this?

**Comment by kyulee1** [comment]
Yep. I can take this.

**Comment by BruceForstall** [comment]
@jkotas Do you think this is important?

It looks like arm32 and arm64 do the same thing: they expect the exception object in r0, and establisher frame (CallerSP) in r1 for filter only. The comments for x86 w/ funclets also expects eax to be the exception object, and no mention of establisher frame, but I don't trust those comments.

It seems like a simple enough change to make in the JIT, but I don't know where to change the VM, and it doesn't seem important to me.

**Comment by jkotas** [comment]
I do not think this is important anymore.
