### ISSUE TITLE
RyuJIT attempts to optimize integer constant multiply and fails

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#447]
See comment in the generated assembly code.

```C#
class Program {
    static int Main(string[] args) {
        int x = args.Length;
        for (int i = 0; i < int.MaxValue; i++) {
            x *= 12;
        }
        return x;
    }
}
```

Code generated by RyuJIT:
```
00007FFC7D3F0480 8B 41 08             mov         eax,dword ptr [rcx+8]  
00007FFC7D3F0483 33 D2                xor         edx,edx  

; probably this was supposed to be lea eax, [eax+eax*2]
00007FFC7D3F0485 6B C0 03             imul        eax,eax,3
00007FFC7D3F0488 C1 E0 02             shl         eax,2  

00007FFC7D3F048B FF C2                inc         edx  
00007FFC7D3F048D 81 FA FF FF FF 7F    cmp         edx,7FFFFFFFh  
00007FFC7D3F0493 7C F0                jl          00007FFC7D3F0485  
00007FFC7D3F0495 C3                   ret  
```

**Comment by jkotas** [comment]
@cmckinsey Could somebody on your team please take a look?

**Comment by cmckinsey** [comment]
Today RyuJIT only handles shift/add expansions for multiplies with certain constant values (see morph line 9668). The formation of LEA is missing in codegenxarch.cpp line 1862. This was something we didn't get to before our recent push to ship .NET 4.6. We should be able to get a short term improvement for the basic cases. Eventually we'll probably won't to come back and do something more sophisticated to handle more complex constant multipliers.

I'll see if someone on the team or myself can get to the quick fix soon.

**Comment by mikedn** [comment]
In case the LEA code isn't added in time for release I'd say that the optimization should be disabled (LEA_AVAILABLE = 0), otherwise it ends up being a de-optimization due to the use of both `imul` and `shl`.

I'd love to fix this myself but it will likely take a while to sort out the CLA with my employer so I can't promise anything unfortunately.

**Comment by cmckinsey** [comment]
No problem. I have another dev testing this change. I can't assign this to him until he gets a github account (Brian: hint, hint).

**Comment by cmckinsey** [comment]
PR #578 fixed this issue by replacing the imul 3 with an lea which should be faster.
