### ISSUE TITLE
Intermittent OSX PAL test failures dealing with deleting files

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#4476]
@briansull has reported a few PAL test failures that appear to be unrelated to the change under test.  I have no evidence to decide whether these are infrastructure issues on the Mac machines versus test issues versus product bugs.  I just want to capture some of them here in case it's useful to do so.

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_osx_prtest/1168/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_osx_prtest/1184/

```
c_runtime._wfopen.test6 (from (empty))
ERROR: Failed to delete "testfile". Error is 170
```

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_osx_prtest/1180/

```
file_io.DeleteFileA.test1 (from (empty))
DeleteFileA: ERROR: Couldn't delete DeleteFileA's "testFile03.txt" Error is 170
```

**Comment by RussKeldorph** [comment]
@sergiy-k  @mmitche FYI

**Comment by sergiy-k** [comment]
@wtgodbe has already been looking into these failures but he has not yet been able to identify the root cause. It looks like a test issue.

**Comment by wtgodbe** [comment]
Believe this was fixed a while back, we haven't seen these (or any) PAL failures in recent memory - https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx_prtest/
