### ISSUE TITLE
Jit: verify check and retail produce same results

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#4494]
Create a script to verify there's no difference in jit outputs for check versus debug builds.

Automate this checking and run it as part of the regular CI rotation.

**Comment by RussKeldorph** [comment]
Thanks @AndyAyersMS.  I'm going to optimistically pull this into RTM for now.

**Comment by LLITCHEV** [comment]
I did a crossgen on mscorlib.dll on Linux and Windows using Checked and Debug build using COMPLus_NgenDisasm=*. No diffs in the disassembly. This confirms Debug and Checked builds generate same code.

**Comment by adiaaida** [comment]
I did a crossgen of mscorlib.dll on Windows using a Checked clrjit.dll and a Release clrjit.dll. Diffing both the nis generated and output generated by nidump showed no diffs.

Opened #5063 to track automating this process.
