### ISSUE TITLE
[ARM32] Sudden assertion failure with the recent commit

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#4499]
CoreCLR from 0ce162fee93d48408f7677a48db7a324bc901a18 suddenly shows the following assert failure for Hello, World example:
```
{0x9ab-0x76a4f7b1} ASSERT [PROCESS] at /home/parjong/projects/toolchains/coreclr/src/pal/src/thread/process.cpp.1821: sem_open(/clrct000009ab00000000018ccf89) failed: 38 (Function not implemented)
```

**Comment by manu-silicon** [comment]
Which version of the OS are you using? I found this which seems to relate to your error:

http://stackoverflow.com/questions/270113/how-do-i-stop-sem-open-failing-with-enosys

**Comment by parjong** [comment]
@manu-silicon I used the ARM emulator that cat be downloaded from #3805.

**Comment by parjong** [comment]
It seems that b7d76075a8d2321c14fc4b0a761d24c56621d078 is the first commit related with this assertion failure. I have no assertion failure with 50cf7134f60b050c82eef03a8c38ac2499199282.

**Comment by parjong** [comment]
CC: @jkotas, @leemgs, @myungjoo

**Comment by manu-silicon** [comment]
That commit seems to have shuffled the ordering of semaphore creation but there were no changes in flag that could explain why it would now fail. I'll update my arm board and see if I get this too.

**Comment by parjong** [comment]
I can execute Hello, World example after mounting tmpfs at /dev/shm.

**Comment by manu-silicon** [comment]
So it might just be an issue with the way the arm emulator is setup.

**Comment by parjong** [comment]
I think so. However, I'm not sure whether /dev/shm is mounted for all the environment. In addition, this is the first time that I see this assertion failure. Before b7d7607, CoreCLR just works even if /dev/shm is not mounted.

**Comment by leemgs** [comment]
>However, I'm not sure whether /dev/shm is mounted for all the environment. 

@manu-silicon , @parjong , The traditional Linux distributions (e.g., Ubuntu, Fedora, RHEL/CentOS, OpenSUSE, ...) generally support the /dev/shm facility as a default inter-process communication (IPC).  However, the popular Android software platform supports the Binder IPC (/dev/binder) instead of the traditional IPCs (/dev/shm).  

Anyway, I will add the /dev/shm into the next version shortly because the arm emulator is based on the traditional Linux distribution.
