### ISSUE TITLE
Deprecate DateTime.Now

### ISSUE THREAD

**Issue by mj1856** [dotnet/coreclr#45]
I would like to propose that [`DateTime.Now`](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/mscorlib/src/System/DateTime.cs#L904-L920) be deprecated.  This is most developer's first introduction to working with time, and is also a root cause of bugs related to daylight saving time and time zones.

Developers should get in the habit of thinking globally, rather than locally - especially when designing for the web.  Even on desktop and mobile applications that only run in a single time zone, this can create the kind of bugs that pull developers out of bed at 2AM on the morning of a daylight saving time transition.

More supporting arguments:
- [The Case Against DateTime.Now](http://www.codeofmatt.com/2013/04/25/the-case-against-datetime-now/) - Matt Johnson (me)
- [What's Wrong with DateTime Anyway](http://blog.nodatime.org/2011/08/what-wrong-with-datetime-anyway.html) - Jon Skeet

Given the widespread nature of this API, I suggest *not* removing it from coreclr - but rather marking it with an `[Obsolete]` attribute.  I can send a PR if the suggestion is approved.

**Comment by mj1856** [comment]
The obsolete message would be something like:

> Using a `DateTime` to represent time in the local time zone can lead to globalization errors.  Please consider using `DateTimeOffset.Now` when working with the local time zone.  When working with UTC, use `DateTime.UtcNow` or `DateTimeOffset.UtcNow`.

**Comment by telekenetix** [comment]
You should probably just make the PR and if they approve the idea, then it will be even simpler to get into the pipe. :)

**Comment by gaochundong** [comment]
Great Idea~~

**Comment by davidfowl** [comment]
Why is this in coreclr and not corefx?

**Comment by Alexx999** [comment]
@mj1856 and what if I want to get current time in user's time zone? Calculate time using UtcNow and timezone offset?
The real problem is that DateTime.Now is the *most obvious* way of working with time. Probably it should've been named the other way - Now returning UTC time and LocalNow returning local time, but now it's probably too late for that.

**Comment by mj1856** [comment]
@davidfowl System.DateTime is in mscorlib.

@Alexx999 You should use `DateTimeOffset.Now` for that, and ideally never convert it to a `DateTime.

**Comment by mj1856** [comment]
@davidfowl - or by "this" did you mean the objects themselves?  I'd be all for migrating `DateTime`, `DateTimeOffset`, `TimeZoneInfo` and perhaps `TimeSpan` over to corefx - if that is possible.

**Comment by ellismg** [comment]
The factoring here is a little confusing.  In .NET Core we want to decouple the idea of the contract which exposes a type and the runtime assembly that implements that contract.  So the API surface area exposed by .NET Core lives in the corefx repository.  It happens that much of the implementation also lives there, but for some types, like System.DateTime, the implementation lives with the runtime itself in mscorlib.

For .NET Core, we're trying to pull as much of the implementation of the framework out of specific libraries tied to the runtime (like mscorlib) and into libraries that can be used across all .NET stacks.

For now the general guidance is if you have an issue with the framework itself (adding new surface area, removing or obsoleting existing surface are), you should discuss it in the CoreFX repo, even though the code might not live there.  If there's an issue with how a type is implemented (e.g, bug, performance issue, etc.) and that type is implemented in mscorlib, then it makes sense to discuss it here.

This is a little confusing, I know, but doing it this way gives the best chance that all the relevant folks see the issue and act on it in a timely manner.

I have gone ahead and opened a corresponding version of this issue in CoreFX and I'm going to close this issue to make sure the discussion doesn't get split across the two threads.

**Comment by mj1856** [comment]
@ellismg - thanks for the clarification.
