### ISSUE TITLE
Is it possible to build coreclr for ARM on Windows?

### ISSUE THREAD

**Issue by mkborg** [dotnet/coreclr#4505]
I have tried to run "build.cmd arm" and "build.cmd arm64" on Windows 7 with Visual Studio Community. In first case it said  "Only AMD64, ARM64 and I386 are supported". In second case it complained that "MC not found".

I looked at CI results in one arbitrary chosen PR and didn't find reference to ARM on Windows build:

> CentOS7.1 x64 Debug Build and Test — Build finished. 809 tests run, 0 skipped, 0 failed.
FreeBSD x64 Checked Build — Build finished. 809 tests run, 0 skipped, 0 failed.
OSX x64 Checked Build and Test — Build finished. No test results found.
Ubuntu arm Cross Checked Build — Build finished. No test results found.
Ubuntu arm Cross Debug Build — Build finished. No test results found.
Ubuntu arm Cross Release Build — Build finished. No test results found.
Ubuntu x64 Checked Build and Test — Build finished. No test results found.
Windows_NT x64 Debug Build and Test — Build finished. 6414 tests run, 0 skipped, 0 failed.
Windows_NT x64 Release Priority 1 Build and Test — Build finished. 9315 tests run, 0 skipped, 0 failed.
Windows_NT x86 Debug Legacy Backend Build and Test — Build finished. No test results found.
Windows_NT x86 Release Legacy Backend Build and Test — Build finished. No test results found.

Is it possible to build coreclr for ARM on Windows?

**Comment by jkotas** [comment]
> Is it possible to build coreclr for ARM on Windows?

It is not possible to build the repo for ARM on Windows today. The PRs to make it work are welcomed. (The sources are building using the legacy internal MS build system - it should be just about fixing up the make files.)

**Comment by jkotas** [comment]
The Windows ARM build works now - enabled in CI by #7123
