### ISSUE TITLE
String.Join(string, object[]) bug when first item is null

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#4506]
Continuing my series to break the BCL for fun and no profit here's another `string.Join` bug:

```
String.Join(",", new object[] { null, "x" })
```

returns `""`. It should return `",x"`.

This bug exists in CoreCLR, in 4.6.2 and in the recently merged `string.Join` fix.

**Comment by bbowyersmyth** [comment]
It's a documented bug so that makes it a feature :wink:
https://msdn.microsoft.com/en-us/library/dd988350(v=vs.110).aspx

@jkotas What is the viewpoint on quirking old bugs on the new core platforms?

**Comment by jkotas** [comment]
It is case by case. 

cc @AlexGhiondea

**Comment by GSPP** [comment]
@bbowyersmyth oh no! Haha that is so unfortunate.

**Comment by jamesqo** [comment]
IMO I think this should be fixed for .NET Core; this behavior is unintuitive, especially considering the fact that if you cast to `IEnumerable<object>` (or cast to `object[]` from `string[]`, since arrays are covariant) you will get different behavior. This makes it very hard to write correct code.

**Comment by jamesqo** [comment]
@jkotas, you mentioned in the Tuple PR that commits that may cause compatibility issues with the desktop are simply not cherry-picked. Would it make sense to remove the bug now and fix the documentation?

**Comment by jkotas** [comment]
I do not have an option on this one.
@stephentoub Do you happen to know about similar examples in corefx, to see where we are setting the bar on issues like this one?

**Comment by stephentoub** [comment]
> @stephentoub Do you happen to know about similar examples in corefx, to see where we are setting the bar on issues like this one?

I thought I responded to this a few weeks ago, but apparently my comment didn't take.  I don't really know of similar examples.  We've certainly taken bug fixes that haven't yet been ported back to desktop.  But we've also avoided making some kinds of fixes when the benefit is very low and the observable difference could cause cross-platform compatibility issues, e.g. throwing an ArgumentOutOfRangeException instead of an IndexOutOfRangeException.

I similarly don't have a strong opinion on this particular case.  This behavior is documented, which is unfortunate, but it's also quite strange and inconsistents, e.g. that these two Console.WriteLine calls output different results:
```C#
var args = new[] { null, "x" };
Console.WriteLine(string.Join(",", (object[])args));
Console.WriteLine(string.Join(",", (string[])args));
```
so I'd be ok seeing it fixed as long as it was ported back to desktop.

**Comment by AlexRadch** [comment]
@stephentoub This behavior is documented in note **as issue** and have number of workarounds.

**Comment by danmosemsft** [comment]
This was fixed in #8114.

**Comment by weshaggard** [comment]
@AlexGhiondea we don't have the netfx tags in the coreclr repo what is the best way to get this tracked for desktop?

**Comment by AlexGhiondea** [comment]
@weshaggard the easiest way is to create an issue in the CoreFx repo and tag that with Netflix-port-consider.

**Comment by weshaggard** [comment]
@AlexGhiondea we should probably do that for this issue if we haven't already.

**Comment by AlexGhiondea** [comment]
I have tagged https://github.com/dotnet/corefx/pull/13747 with netfx-port-consider.

**Comment by karelz** [comment]
Updated PR # in @AlexGhiondea's comment to the new one (dotnet/corefx#14083).

@AlexRadch please consider all impact of your PR switches in future.

**Comment by danmosemsft** [comment]
I see no use for this issue. fixed by https://github.com/dotnet/corefx/pull/13747

**Comment by danmosemsft** [comment]
Oh, it was clsoed already. My bad

**Comment by jayaranigarg** [comment]
@danmosemsft : Is this ported to netfx yet?
