### ISSUE TITLE
StringBuilder.Replace NullReferenceException

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#4511]
var sb = new StringBuilder();

            var str = new string('x', checked(1024 * 1024 * 256));
            for (int i = 0; i < 7; i++)
                sb.Append(str);

            sb.Insert(0, "x");
            sb.Replace("x", str); //NRE
            Console.WriteLine(new { sb.Length, sb.Capacity, sb.MaxCapacity });

This crashes, likely due to exceeding the maximum allowed capacity and overflowing some internal value.

**Comment by AlexGhiondea** [comment]
This should be fixed by #4833
