### ISSUE TITLE
[jitstressregs=1] Vector3Interop Access Violation

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#4529]
(Also fails with jitstressregs=8)

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_jitstressregs1/41/testReport/

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at RPInvokeTest.nativeCall_RPInvoke_Vector3Ret(CallBackDelegate_RPInvoke_Vector3Ret callBack)
   at RPInvokeTest.test()
   at Test.Main()

**Comment by sejongoh** [comment]
It looks like the address of the return buffer from the callback function is zero. 

```
EXPORT(bool) __stdcall nativeCall_RPInvoke_Vector3Ret(
  CallBack_RPInvoke_Vector3Ret notify)
{
...
....
00007FFE634E79CF  call        qword ptr [notify]  
00007FFE634E79D6  lea         rcx,[rsp+40h]  
00007FFE634E79DB  mov         rdi,rcx  
00007FFE634E79DE  mov         rsi,rax    ;  rax == 0
00007FFE634E79E1  mov         ecx,0Ch  
00007FFE634E79E6  rep movs    byte ptr [rdi],byte ptr [rsi]  ; rsi == rax == 0
```

Without JitStressRegs=1, rax is used for the return buffer address on the managed side. JitStressRegs=1 uses rsi instead of rax but it looks like there is no move from rsi to rax. I will double check this.

**Comment by sejongoh** [comment]
@sivarv My understanding is that return address should be in rax. Please correct me if I am wrong. The register allocator assigned rsi to RetBuf. Should the allocator assign rax here or is there other logic that can insert 'rax <= rsi'?

Without JitStressRegs=1
```
     (  7,  7) [000036] ------------             *  stmtExpr  void  (top level) (IL 0x01B...0x01C)
N051 (  3,  2) [000030] -------N----             |  /--*  lclVar    simd16 V02 loc1          REG mm0
N053 (  1,  1) [000031] ------------             |  +--*  lclVar    byref  V00 RetBuf        REG rax
N055 (  5,  5) [000035] -------NR---             \--*  storeIndir simd12 REG NA
```

With JitStressRegs=1
```
***** BB06, stmt 8 (top level)
     (  7,  7) [000036] ------------             *  stmtExpr  void  (top level) (IL 0x01B...0x01C)
N051 (  3,  2) [000030] -------N----             |  /--*  lclVar    simd16 V02 loc1          REG mm6
N053 (  1,  1) [000031] ------------             |  +--*  lclVar    byref  V00 RetBuf        REG rsi
N055 (  5,  5) [000035] -------NR---             \--*  storeIndir simd12 REG NA
```

**Comment by sivarv** [comment]
@sejongoh - it is not return address but rather RetBuf, which is the arg passed by caller method to Callee and Callee returns a struct > 16-bytes (on Unix) by writing to RetBuf address.  When Callee returns, Caller would find the return value at memory address given by Retbuf.  As per UNIX ABI, the Callee method also returns address of RetBuf as its return value.  But RyuJIT doesn't depend on it and doesn't use it.

Under JitStressRegs=1, register allocation could change but that doesn't mean it is a bug.  I am not sure that I understood what the issue that you are pointing at.  Please share me JitDump of the method that you think is at fault via e-mail.

**Comment by sivarv** [comment]
@sejongoh - looks like this is a RPInvoke test failure on windows.  Is the native method expecting RetBuf address return from managed method in RAX?  On x64 windows, Managed code deosn't return  RetBuf in RAX.

**Comment by sejongoh** [comment]
@sivarv Yeah, the native code expects the address to be in rax.

**Comment by sivarv** [comment]
This makes me believe that RPInvoke method is missing some required declaration to make aware the native compiler of x64 Windows CLR calling convention. As per x64 Windows ABI, managed methods don't return RetBuf addr as the return value.  You might want to check if we have any existing RPInvoke tests on desktop and how they are declared.

**Comment by sejongoh** [comment]
Do you mean that the RPInvoke method needs some declaration to make the native compiler understand the CLR calling convention?  Please correct me if I misunderstood what you said. I couldn't find a way for that from coreclr testcases. Where are testcases located on Desktop?

With the following declarations, doesn't CLR needs to follow the native calling convetion?

```
    [UnmanagedFunctionPointer(CallingConvention.StdCall, CharSet = CharSet.Unicode)]        
    [return: MarshalAs(UnmanagedType.Struct)]
    public delegate Vector3 CallBackDelegate_RPInvoke_Vector3Ret();
```

**Comment by sivarv** [comment]
Yes, is there a method annotation needed on native side for native compiler to follow x64 CLR convention?  I have no idea where desktop RPInvoke tests are.  You might have to search around or ask an interop owner.
