### ISSUE TITLE
GC Stress Test Sanity Run

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#4534]
Currently the smallest execution time for each GC stress is ~1 min, please consider dropping it down to seconds so that CI can run it or schedule a weekly full run whichever sounds good.

I am ensuring that all tests are loadable by sepcifying -1 to be the exceution time in https://github.com/dotnet/coreclr/pull/4533. Change it to seconds if possible

**Comment by swgillespie** [comment]
Changing the units of time to seconds is kind of a pain, so I think we'll opt for the weekly CI run instead.
