### ISSUE TITLE
What to do after building

### ISSUE THREAD

**Issue by luisgarciaalanis** [dotnet/coreclr#4538]
I downloaded coreclr, and build it on Ubuntu 16.04.

it created a folder coreclr/bin/Product/Linux.x64.Debug

Now what? how do I install it on /usr/local/*

Do I need to set any env variables on the profile?

I think the build instructions are incomplete.

Help appreciated.
Luis

**Comment by pgavlin** [comment]
@richlander do we have an explanation of the deployment strategy for .Net Core somewhere?

**Comment by svick** [comment]
Do you actually want just the CoreCLR, or do you want all the tooling for compiling and running projects? Because in that case, you probably want [the `dotnet` CLI](https://github.com/dotnet/cli/)

**Comment by karelz** [comment]
Old and likely answered. Please reopen if more info is still needed.
