### ISSUE TITLE
Addition ConditionalWeakTable.AddOrUpdate

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#4545]
Or indexer setter?

At the moment you need to do 
```csharp
lock (cwt) {
    cwt.Remove(key);
    cwt.Add(key, newValue);
}
```
Would be nicer if you could just do
```csharp
cwt[key] = newValue;
```
or
```csharp
cwt.AddOrUpdate(key, newValue);
```

**Comment by svick** [comment]
I believe API changes [should follow the API review process](https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/Documentation/project-docs/contributing-workflow.md#suggested-workflow), namely they should be posted to the corefx repo, even if the implementation is in coreclr.

**Comment by benaadams** [comment]
Raised https://github.com/dotnet/corefx/issues/8429
