### ISSUE TITLE
Move wiki to GitHub Pages

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/coreclr#456]
Currently there is the [coreclr-wiki repo](https://github.com/dotnet/coreclr-wiki) that is manually synced with the internal wiki in this repo. This seems overly complex for little gain as the internal wiki is pretty limited.

I propose moving the wiki to GitHub Pages, like the Orleans team (https://github.com/dotnet/orleans/tree/gh-pages -> http://dotnet.github.io/orleans/) and Mono (https://github.com/mono/website -> http://www.mono-project.com) did.

What do folks think?

**Comment by jkotas** [comment]
@richlander ?

**Comment by richlander** [comment]
I think it's a good idea. I'm happy to move to the approach that the Orleans team is using, and put our existing wiki in an orphan gh-pages branch in the coreclr repo.

The lack of a PR mechanism is a major issue, IMO.

That all said, we should decide as a group, for coreclr, corefx and roslyn. Best if we all do the same thing.

@terrajobst, @jaredpar, @ellismg ??

**Comment by akoeplinger** [comment]
Here's another approach from the ASP.NET team: https://github.com/aspnet/Docs.

**Comment by richlander** [comment]
@akoeplinger That's more for conceptual docs, than a wiki. We are working with the aspnet team on that project. Not surprisingly, we're building the bottom part (metadata reading) and they are building the RTD integration.

We'll be looking at making .NET conceptual docs available through that same system.

**Comment by ellismg** [comment]
For what it's worth.  I really like how easy it is to edit the wiki.  My concern about moving to something like GitHub pages would be how easy it is to edit existing pages and add new ones.  Do I actually have to break out my editor and local clone of the repository or can I do everything from within the GitHub website?

I understand the desire to have some sort of PR flow for larger scale edits.  However, most of my interaction with the wiki so far as been of the form "oh, there's a typo here" or "these links are wrong" and I hope I don't have to break out emacs and git to make these sorts of edits.

Aside from the lack of PRs, is there anything else the wiki isn't giving us?  Are others hitting other limitations?

**Comment by akoeplinger** [comment]
> Do I actually have to break out my editor and local clone of the repository or can I do everything from within the GitHub website?

You can do everything from the website as well (though the online editor is a bit different).

> Aside from the lack of PRs, is there anything else the wiki isn't giving us? Are others hitting other limitations?

One of the major limitations of the integrated wiki is that you can't have subfolders, everything is in the root folder which makes it cluttered.

**Comment by richlander** [comment]
@ellismg The editor would look like this: https://github.com/dotnet/coreclr/edit/master/Documentation/clr-code-guide.md.

It isn't just the lack of PRs for "larger scale edits", it's that the community cannot make any edits at all (via PRs).

The other part is that our wiki is a narrowly defined slice of our documentation. Most of our docs (when we finally open source them) will not be in the wiki.

**Comment by ellismg** [comment]
Thanks Rich!  That editing experience seems workable.  As long as I can continue to write Markdown in my browser, I'm happy.

**Comment by richlander** [comment]
I wonder what @terrajobst thinks.

**Comment by richlander** [comment]
Was thinking about this. I now have a complementary, but slightly different proposal.

Here are the characteristics that I find valuable (some of which are overlapping):

- Docs and source available in the same repo.
- Docs and source viewable at the same time in the current branch.
- All of our docs together
- Viewable in a nice format
- Editable via git workflow or a browser

Integrated wiki supports the last 2. gh-pages supports the first one and the last 2.

Alternate proposal (which mostly satisfies all of these):

- Add the wiki into Documentation directory
- Primary viewing is through the regular markdown viewing experience, for however you view markdown.
- A subset of the wiki (and any other docs we want) are published/hosted @ http://dotnet.github.io as http://dotnet.github.io/CoreCLR or http://dotnet.github.io/dotnetcore. Rosyln and Orleans could also use this model. 
   - This is the same model as http://facebook.github.io/react/. See: https://github.com/facebook/react/tree/master/docs. 
   - React does have a wiki, but you can see that it is used for a different purpose: https://github.com/facebook/react/wiki. 

Thoughts?

**Comment by akoeplinger** [comment]
> Add the wiki into Documentation directory

:+1:, was thinking about this as well, sounds like a good compromise.

> A subset of the wiki (and any other docs we want) are published/hosted @ http://dotnet.github.io

I don't think this is really necessary when the wiki isn't used for conceptual docs (as you said you'll be using the readthedocs system like aspnet) but primarily for content that is interesting to developers/contributors like coding guidelines and build instructions.

Facebook's React website hosts their actual consumer-facing docs, so it makes sense for them to publish it as a website.

**Comment by jaredpar** [comment]
CC @DustinCampbell, @kuhlenh from the Roslyn side.

**Comment by richlander** [comment]
@akoeplinger Good point on the gh.io site. We should wait until we have some more polished docs to publish on such a website. Once we have installers for .NET Core, I think we'll have a reason to create the site.

I'll see if I can get feedback from the relevant folks.

Tangentially related PR: #483.
