### ISSUE TITLE
Policy of Build Modes (e.g., Release, Debug, * )

### ISSUE THREAD

**Issue by leemgs** [dotnet/coreclr#4582]
## [W.I.P] Documentation: The Policy of the Build Modes on CoreCLR (for Linux/ARM)

As some Linux/ARM engineers already know, we have still got the "segmentation fault" error whenever we tried to run "hello world!!!" on Linux/ARM CoreCLR generated with release mode. However, in the debug mode, this issue is not always reproduced. Before continuing the finding a reason of this issue, I have some questions about the build mode (e.g. **./build.sh debug** or **./build.sh release**). 

Could someone tell us the difference between debug mode and release mode? Basically, it seems that the major difference is `_DEBUG` macro, `_DEBUG_IMPL` macro , and  `COMPlus_***` variable.  Is it correct? If I am wrong, Please, correct me. I have summarized the difference between two the build modes.
### Table: Difference Summary among  Five Build Modes of CoreCLR

```
--------------------------------------------------------------------------------------
Content             DEBUG         CHECKED      RELWITHDEBINFO(F)   RELEASE     MINSIZEREL(F)
                   (1)             (2)               (3)             (4)            (5)
--------------------------------------------------------------------------------------
LLDB/SOS-Plugin       O              O            O               O                 O

GDB/DWARF (-g)        -g            -g             -g            -g0             -g0 

Optimization level    -O0           -O2           -O3           -O3            -Os

COMPlus_* variables   O              X              X              X               X         

_DEBUG (macro)        O              X              X               X               X   

_DEBUG_IMPL (macro)   O              X              X               X               X   

Not Stripped          O              O             O                X              X   

LOG()                 ?              ?               ?               ?             ?

Profiling API        ?              ?               ?                ?             ?

```

**Reference**
a. -O sets the clang compiler's optimization level. 
-       clang(llvm): http://clang.llvm.org/docs/CommandGuide/clang.html
-       clang(freebsd): https://www.freebsd.org/cgi/man.cgi?query=clang
-       gcc: http://www.rapidtables.com/code/linux/gcc/gcc-o.htm
-       msc: https://msdn.microsoft.com/en-us/library/k1ack8f1.aspx

Let's see the different name of the optimization level between Visual Studio on Windows and Clang/LLVM on Linux.

```
Visual Studio (Win)               Clang/LLVM (Linux)
-------------------------------------------------------
Disabled (/Od)                     -O0 (debug)
Minimize Size (/O1)                -Oz (to be determined)
Maximize Speed (/O2)               -Ofast (to be determined)
Full Optimization (/Ox)            -O3 (release)
```

![optimization-table](https://cloud.githubusercontent.com/assets/82404/14564527/e67a81d0-0361-11e6-8466-a9e1ec1a568c.png)
- https://github.com/dotnet/coreclr/issues/4583 (Difference of clang optimization levels among -O0, -O1, -O2, -O3, -Os/-Oz, and -Ofast)

b. -g sets the clang compiler's debug level. 

```
   -g0: no debug information
   -g1: minimal debug information
     -g:    default debug information(*)
   -g3: maximal debug information
```
-       clang: http://clang.llvm.org/docs/CommandGuide/clang.html
-       gcc: http://www.rapidtables.com/code/linux/gcc/gcc-g.htm

c. '?': It is not related to the build mode

d. 5 build modes:  There are five build types are DEBUG, CHECKED, RELEASE, RELWITHDEBINFO, and MINSIZEREL in `./src/pal/tools/gen-buildsys-clang.sh` file. These build types is created based on CMake manual (e.g., https://cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html).
-       DEBUG: No optimizations, enable full debug features, no stripped, not handle memory foot print, and not optimize fie sizes for helping the developers. 
-       CHECKED: Add running tests with asserts as well as the all settings of the above DEBUG.
-       RELEASE: Optimizations, No debug features, and stripped files for deploying the .NET Core based commercial devices. 
-       RELWITHDEBINFO: Generate two format  files such as an exectuable and a debug info (not-exectuable) file (*.dbg) from RELEASE. 
-       MINSIZEREL: support low memory foot print, small file size to support embedded devices

e. '(F)': Todo 

f. _DEBUG (macro)   : It calls  304,954 gettid(2) syscalls in Linux-based platform. 

f. LTO (Link-Time Optimization)
- By enabling link-time optimizations (-O3 -flto) we make it possible for the compiler to optimize across the whole program.
- TroubleShooting: Changing default binutils from ld.bfd to ld.gold to resolve "LTO not working: File format not recognized"

```
$ vi ./hello.cpp
#include <iostream>

int main()
{
  std::cout << "Hello World\n";
  return 0;
}

$ clang++  -O3 -flto -c hello.cpp
$ ls -l /usr/bin/ld*
$ sudo rm /usr/bin/ld
$ sudo ln -s ld.gold /usr/bin/ld
$ clang++ -flto hello.o -o hello
$ ./hello
Hello World
```

**File size comparison of build modes**
Below is the comparison result of the file size of two binaries between `debug` mode and `release` mode. 

```
* Debug Build + O0(by default) : stripped
-rwxr-xr-x   1 invain invain    122,677  7월 13 10:34 corerun
-rwxr-xr-x   1 invain invain  3,795,108  7월 21 18:35 libclrjit.so
-rwxr-xr-x   1 invain invain  9,491,356  7월 21 18:35 libcoreclr.so


* Release Build + O3(by default): stripped
-rwxr-xr-x   1 invain invain     24,945  7월 21 16:14 corerun
-rwxr-xr-x   1 invain invain  1,508,764  7월 21 18:33 libclrjit.so
-rwxr-xr-x   1 invain invain  4,455,728  7월 21 18:33 libcoreclr.so

* Release Build + Ofast: stripped
-rwxr-xr-x 1 root root    18,496 Jul 26 05:00 ./corerun
-rwxr-xr-x 1 root root 1,508,764 Jul 26 04:59 ./libclrjit.so
-rwxr-xr-x 1 root root 4,455,728 Jul 26 04:59 ./libcoreclr.so

* Release Build + Oz: stripped
-rwxr-xr-x 1 root root    14,400 Jul 26 05:02 ./corerun
-rwxr-xr-x 1 root root 1,181,160 Jul 26 04:40 ./libclrjit.so
-rwxr-xr-x 1 root root 3,407,200 Jul 26 04:40 ./libcoreclr.so


```

The attribution of the two files is  "ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=db9de22900c4dc357b3968ebea232f74037349c2, **not stripped**"

**Comment by leemgs** [comment]
This issue is derived from the #3926 in order to complete the unfinished build modes.

For example, 
before) DEBUG CHECKED RELEASE

after)    DEBUG  CHECKED  **RELWITHDEBINFO(※)**  RELEASE  **MINSIZEREL(※)**

**Comment by karelz** [comment]
@leemgs what is the action item here? Adding new docs? Bug in code or infra?
