### ISSUE TITLE
[Linux] Structs with 16 1-byte fields throw assert violation

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/coreclr#4584]
On Linux, If you have a struct with exactly 16 fields of type byte, the runtime with stop execution with an assert violation in src/vm/methodtable.cpp:

```
_ASSERTE(helperPtr->currentUniqueOffsetField < SYSTEMV_MAX_NUM_FIELDS_IN_REGISTER_PASSED_STRUCT);
```

It seems that it should be ```<=```.

PS: There are 3 occurrences of this assert in this file.

**Comment by LLITCHEV** [comment]
Fixed by Fix for a badly placed assert in the *nix arg passing classification. #4608

**Comment by manu-silicon** [comment]
Thanks
