### ISSUE TITLE
ci.cmd has incorrect TestHost path?

### ISSUE THREAD

**Issue by japj** [dotnet/coreclr#461]
It seems ci,cmd points to a TestHost 1.0.1 path, while the source tree actually contains a newer tests\src\packages\Microsoft.DotNet.TestHost.1.0.2-prerelease

I am wondering, is ci.cmd still used?

**Comment by jkotas** [comment]
@mmitche  ?

**Comment by mmitche** [comment]
We don't actually use this any longer.  Will remove.

**Comment by mmitche** [comment]
Closed with PR #464
