### ISSUE TITLE
tests\buildtest.cmd fails if a new test is added in correspondence to any changes made in src\mscorlib

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#462]
**Issue**
tests\buildtest.cmd (and build.cmd) fails if a new test is added in correspondence to any changes made in src\mscorlib.

The buildtest.cmd picks up mscorlib (and related assemblies, such as System.Runtime.Extensions) from the portable reference assemblies path by default (%ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\mscorlib.dll on my machine).

**Comment by tannergooding** [comment]
Should clarify that tests\buildtest.cmd (and build.cmd) should attempt to use the local binaries from src\mscorlib (binaries\product\$(BuildOS).$(Platform).$(Configuration)) by default.

**Comment by jkotas** [comment]
@AlexGhiondea what should be the developer workflow in this case?

**Comment by AlexGhiondea** [comment]
This should work. 

@ramarag since you are more familiar with the buildtest.cmd script -- do we not pick up the assemblies from the binary output folder?

**Comment by ramarag** [comment]
The tests are built against contracts, the same way https://github.com/dotnet/corefx builds test
The clean way to write the test is to expose the functionality via a contract and build the tests against them

The alternative is a hacky way of compiling the test against mscorlib like the test in https://github.com/dotnet/coreclr/tree/master/tests/src/managed/Compilation
and then execute it with "%Core_Root%\corerun.exe" <app.exe>

@AlexGhiondea : is there a formal way of creating the contracts from https://github.com/dotnet/corefx ?

**Comment by tannergooding** [comment]
@AlexGhiondea, @ramarag, Has there been any update here?

**Comment by ramarag** [comment]
You can use  <LinkLocalMscorlib>true</LinkLocalMscorlib> in your csproj, for example take a look at  : [https://github.com/ramarag/coreclr/blob/master/tests/src/Interop/ICastable/Castable.csproj]Castable.csproj

But there is a caveat, you can not use any of the corefx contracts, so your packages.config should not have them, Ex- [https://github.com/ramarag/coreclr/blob/master/tests/src/Interop/ICastable/packages.config]packages.config
