### ISSUE TITLE
How to build demo project with dotnet-cli toolchain and run it with compiled corerun?

### ISSUE THREAD

**Issue by AlekseyVereshchagin** [dotnet/coreclr#4630]
I built CoreCLR and CoreFX from sources according to build [instruction](https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md) for Linux on Ubuntu 14.04.
How should I build and run demo project now? Can I use [dotnet-cli](https://github.com/dotnet/cli) toolchain to generate new project and restore dependencies? How should I build and run demo using fresh compiled binaries? Should I use dotnet-cli or mono similar to MAC OS X [instructions](https://github.com/dotnet/coreclr/blob/master/Documentation/building/osx-instructions.md)?

**Comment by janvorli** [comment]
One way is to use the dotnet cli for compiling your app and restoring the dependencies, then do dotnet publish and then copy the built coreclr files (.so, mscorlib.*, corerun) to the target folder of the publish. 
Then you can run your app with the new runtime bits.

**Comment by AlekseyVereshchagin** [comment]
Yes, I think it works, thank you.

With mono it is possible to build binaries that can be executed in this way:

> ./corerun HelloWorld.exe

Can I get similar result with dotnet toolchain?

**Comment by karelz** [comment]
@janvorli ping?

**Comment by janvorli** [comment]
@AlekseyVereshchagin I am sorry, I have missed your additional question back in April. You can find details on various ways of deploying CoreCLR apps here:
https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/deploying/

**Comment by AlekseyVereshchagin** [comment]
@janvorli I think, good answer to original question now available in project documentation: [UsingYourBuild.md](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md) and [UsingCoreRun.md](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingCoreRun.md). And ".NET Core Application Deployment" article you refer is useful too. Thank you for answer. I think, issue can be closed.
