### ISSUE TITLE
Unix hosting APIs (coreclr_initialize, etc) should use UTF-8 on all platforms

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#4634]
Currently the CoreCLR hosting APIs (coreclr_initialize, etc) are using UTF-8 on Unix, but regular only MBCS strings on Windows. This means that they cannot support Unicode characters in paths.

These APIs should change to use UTF-8 characters on all platforms, or they should be removed for Windows since they are broken.

**Comment by gkhanna79** [comment]
CC @janvorli @schellap

**Comment by schellap** [comment]
This PR would have to be reverted to go back to UTF8. With current code in the cli repo, this is a 1 line change.

https://github.com/dotnet/cli/pull/2673

**Comment by schellap** [comment]
@janvorli are we supposed to use a different API on Windows? Or CoreCLR would make this change?

**Comment by janvorli** [comment]
Fixed by #4894
