### ISSUE TITLE
ARM/Linux "seh_tests" unit test fails

### ISSUE THREAD

**Issue by myungjoo** [dotnet/coreclr#4638]
CoreCLR unit test case of "JIT.IL_Conformance.Old.objectmodel.seh_tests.seh_tests" fails in ARM/Linux:

```
bash-3.2# ./corerun seh_tests.exe  

Unhandled Exception: System.Exception: Exception of type 'System.Exception' was thrown.
   at seh.main(String[] A_0)
Aborted (core dumped)
bash-3.2# echo echo $?
echo 134
```
, where the exit code is supposed to be 100.

It looks like that exception handling for this instance is not working well.

ps. I'm traversing each failed unit test case of https://github.com/dotnet/coreclr/issues/3977 . Many of the current 395 failed cases seem to be caused by simple runtime environment (filesystem mount conditions), we expect the number to decrease significantly with next iteration of test run soon.

**Comment by parjong** [comment]
@myungjoo #4503, #4581 seems to be related with this issue. When those patches are applied, CoreCLR from c4767162f22398e553d70c8099d25bfe478a439a works as expected (if it is built with Debug mode).

**Comment by myungjoo** [comment]
@parjong As https://github.com/dotnet/coreclr/pull/4581 looks counter-intuitive to me, I'll test with more intuitive approaches and will report back to you.

**Comment by myungjoo** [comment]
The functions of `ehhelpers.S` have bugs in handling sp/fp as @parjong has mentioned.
However, there are similar, but more bugs in `asmhelpers.S` and those are generating side-effects on `ehhelpers.S` so that correct bugfix of `ehhelpers.s` generates segmentation faults.

I'm starting with WIP patch for this one. (need clean ups and need to make sure that this covers all)
