### ISSUE TITLE
ARM64: InvalidProgramException is thrown when generating R2R images

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#4649]
Repro:
crossgen.exe /ReadyToRun system.dll

InvalidProgramException while compiling method System.Text.RegularExpressions.Regex..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.Regex.InitializeReferences
InvalidProgramException while compiling method System.Text.RegularExpressions.Regex.Run
InvalidProgramException while compiling method System.Text.RegularExpressions.Regex.CacheCode
InvalidProgramException while compiling method System.Text.RegularExpressions.Regex..cctor
InvalidProgramException while compiling method System.Text.RegularExpressions.CachedCodeEntry..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.ExclusiveReference.Get
InvalidProgramException while compiling method System.Text.RegularExpressions.ExclusiveReference.Release
InvalidProgramException while compiling method System.Text.RegularExpressions.SharedReference..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexBoyerMoore..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.Capture..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.CaptureCollection..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.CaptureCollection.GetEnumerator
InvalidProgramException while compiling method System.Text.RegularExpressions.CaptureCollection.GetCapture
InvalidProgramException while compiling method System.Text.RegularExpressions.CaptureEnumerator..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexCharClass..cctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexCharClass..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexCharClass..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexCharClass.AddSubtraction
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexCharClass.AddLowercaseRange
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexCharClass.ParseRecursive
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexCode..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexFCD.FirstChars
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexFCD.Prefix
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexFCD..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexFCD.PushInt
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexFCD.PushFC
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexFCD.CalculateFC
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexFC..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexFC..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexFC..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexPrefix..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexPrefix..cctor
InvalidProgramException while compiling method System.Text.RegularExpressions.Group..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.Group.get_Captures
InvalidProgramException while compiling method System.Text.RegularExpressions.Group..cctor
InvalidProgramException while compiling method System.Text.RegularExpressions.GroupCollection..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.GroupCollection.GetGroupImpl
InvalidProgramException while compiling method System.Text.RegularExpressions.GroupCollection.GetEnumerator
InvalidProgramException while compiling method System.Text.RegularExpressions.GroupEnumerator..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexRunner.Scan
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexRunner.InitMatch
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexRunner.DoubleTrack
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexRunner.DoubleStack
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexRunner.DoubleCrawl
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexInterpreter..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.Match..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.Match.Reset
InvalidProgramException while compiling method System.Text.RegularExpressions.Match.get_Groups
InvalidProgramException while compiling method System.Text.RegularExpressions.Match..cctor
InvalidProgramException while compiling method System.Text.RegularExpressions.MatchSparse..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.MatchSparse.get_Groups
InvalidProgramException while compiling method System.Text.RegularExpressions.MatchCollection..ctor
Method not found: 'Boolean System.CompatibilitySwitches.get_IsAppEarlierThanWindowsPhone8()'. while compiling method System.Text.RegularExpressions.MatchCollection.CopyTo
InvalidProgramException while compiling method System.Text.RegularExpressions.MatchCollection.GetEnumerator
InvalidProgramException while compiling method System.Text.RegularExpressions.MatchEnumerator..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.MatchEnumerator.MoveNext
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexNode..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexNode.ReduceAlternation
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexNode.ReduceConcatenation
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexNode.AddChild
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.Parse
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.ParseReplacement
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.SetPattern
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.ScanRegex
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.ScanReplacement
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.ScanCharClass
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.ScanBackslash
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.NoteCaptureName
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.NoteCaptures
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.AssignNameSlots
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.AddConcatenate
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.PushGroup
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.PopGroup
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.StartGroup
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.AddAlternate
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.AddUnitOne
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.AddUnitNotone
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.AddUnitSet
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.AddUnitNode
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.AddUnitType
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser.AddGroup
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexParser..cctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexReplacement..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexTree..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexWriter..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexWriter.PushInt
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexWriter.RegexCodeFromRegexTree
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexMatchTimeoutException..ctor
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexMatchTimeoutException.Init
InvalidProgramException while compiling method System.Text.RegularExpressions.RegexMatchTimeoutException.Init
InvalidProgramException while compiling method System.Diagnostics.Debug..cctor
InvalidProgramException while compiling method System.Diagnostics.AssertWrapper.ShowMessageBoxAssert
InvalidProgramException while compiling method System.Diagnostics.MessageBoxPopup..ctor
InvalidProgramException while compiling method System.Collections.Generic.BitHelper..ctor
InvalidProgramException while compiling method System.ComponentModel.DataErrorsChangedEventArgs..ctor
InvalidProgramException while compiling method System.ComponentModel.BindableAttribute..cctor
InvalidProgramException while compiling method System.ComponentModel.BrowsableAttribute..cctor
InvalidProgramException while compiling method System.ComponentModel.DesignTimeVisibleAttribute..cctor
InvalidProgramException while compiling method System.CodeDom.Compiler.GeneratedCodeAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Action
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Appearance
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Asynchronous
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Behavior
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Data
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Default
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Design
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_DragDrop
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Focus
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Format
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Key
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Layout
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Mouse
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_WindowStyle
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.CategoryAttribute.get_Category
InvalidProgramException while compiling method System.ComponentModel.ComplexBindingPropertiesAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.ComplexBindingPropertiesAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.ComplexBindingPropertiesAttribute..cctor
InvalidProgramException while compiling method System.ComponentModel.DefaultBindingPropertyAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultBindingPropertyAttribute..cctor
InvalidProgramException while compiling method System.ComponentModel.DefaultEventAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultEventAttribute..cctor
InvalidProgramException while compiling method System.ComponentModel.DefaultPropertyAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultPropertyAttribute..cctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DefaultValueAttribute.SetValue
InvalidProgramException while compiling method System.ComponentModel.DescriptionAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DescriptionAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.DescriptionAttribute.set_DescriptionValue
InvalidProgramException while compiling method System.ComponentModel.DescriptionAttribute..cctor
InvalidProgramException while compiling method System.ComponentModel.LookupBindingPropertiesAttribute..ctor
InvalidProgramException while compiling method System.ComponentModel.LookupBindingPropertiesAttribute..cctor
InvalidProgramException while compiling method System.ComponentModel.PropertyChangedEventArgs..ctor
InvalidProgramException while compiling method System.ComponentModel.PropertyChangingEventArgs..ctor

**Comment by gkhanna79** [comment]
Is JIT raising these?

**Comment by rahku** [comment]
it is raised by VM (jitinterface) when jit fails to compile a method.
