### ISSUE TITLE
R2R Bringup of FX Assemblies

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#4650]
We should ensure that FX assemblies (which are in Test_Core_Root) can be compiled with R2R and test run is clean.

**Comment by rahku** [comment]
Following is the list of tests that pass without R2R and fail when test assemblies are crossgen'd
RelativePath=JIT\jit64\hfa\main\testA\hfa_sd2A_d\hfa_sd2A_d.cmd
RelativePath=JIT\jit64\hfa\main\testA\hfa_sd2A_r\hfa_sd2A_r.cmd
RelativePath=JIT\jit64\hfa\main\testA\hfa_sf2A_d\hfa_sf2A_d.cmd
RelativePath=JIT\jit64\hfa\main\testA\hfa_sf2A_r\hfa_sf2A_r.cmd
RelativePath=JIT\jit64\hfa\main\testB\hfa_sd2B_d\hfa_sd2B_d.cmd
RelativePath=JIT\jit64\hfa\main\testB\hfa_sd2B_r\hfa_sd2B_r.cmd
RelativePath=JIT\jit64\hfa\main\testB\hfa_sf2B_d\hfa_sf2B_d.cmd
RelativePath=JIT\jit64\hfa\main\testB\hfa_sf2B_r\hfa_sf2B_r.cmd
RelativePath=JIT\jit64\hfa\main\testC\hfa_sd2C_d\hfa_sd2C_d.cmd
RelativePath=JIT\jit64\hfa\main\testC\hfa_sd2C_r\hfa_sd2C_r.cmd
RelativePath=JIT\jit64\hfa\main\testC\hfa_sf2C_d\hfa_sf2C_d.cmd
RelativePath=JIT\jit64\hfa\main\testC\hfa_sf2C_r\hfa_sf2C_r.cmd
RelativePath=JIT\jit64\localloc\call\call04_large\call04_large.cmd
RelativePath=JIT\jit64\localloc\call\call05_large\call05_large.cmd
RelativePath=JIT\jit64\localloc\eh\eh03_large\eh03_large.cmd
RelativePath=JIT\jit64\localloc\eh\eh04_large\eh04_large.cmd
RelativePath=JIT\jit64\localloc\ehverify\eh12_large\eh12_large.cmd
RelativePath=JIT\jit64\localloc\ehverify\eh13_large\eh13_large.cmd
RelativePath=JIT\jit64\localloc\unwind\unwind04_large\unwind04_large.cmd
RelativePath=JIT\jit64\localloc\unwind\unwind05_large\unwind05_large.cmd
RelativePath=JIT\SIMD\VectorReturn_ro\VectorReturn_ro.cmd

**Comment by rahku** [comment]
The tests were failing due to filenotfound during crossgen. This was fixed in PR #5935. After this test infra issue fix below are the results:
first 12 test fail due to JIT assert during test execution - issue #5967
next 8 pass 
last one fails due to jit assert during crossgen - issue #5965

**Comment by rahku** [comment]
Closing as we have issues open for respective bugs
