### ISSUE TITLE
[corelib] Remove unused types/members

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#4651]
Ran into this issue while trying to create perf benchmarks for #4540. It looks like the types in the decompiled output of mscorlib:

![mscorlib-io-types](https://cloud.githubusercontent.com/assets/9159214/14900506/d602cec8-0d5e-11e6-8734-f1d4cfacc055.PNG)

are missing a lot of types from what's actually [there in the sources](https://github.com/dotnet/coreclr/tree/master/src/mscorlib/src/System/IO). Can those missing types be removed without causing a build break with the full framework? (Their primary implementations seem to live in corefx, so if I'm not mistaken this should be no different than removing `Console`, right?)

List of some types that don't appear in the decompiled output:
- Directory
- DirectoryInfo
- DriveInfo
- File
- FileAttributes
- FileSystemEnumerable
- FileSystemInfo
- ReadLinesIterator
- SearchOption

cc @jkotas 

**edit:** It also looks like `FileStream` (and probably many other of the `File*` types) could be removed as well (even though they appear in the decompiled output), if the `StreamWriter`, `StreamReader`, and `ResourceReader` constructors which accept a path string were removed (which aren't exposed in the contract), since they're the only ones that depend on `FileStream`. See this snapshot:

![mscorlib-fs](https://cloud.githubusercontent.com/assets/9159214/14900956/1cf68f70-0d61-11e6-95c6-c8f6c042cce4.PNG)

**Comment by jkotas** [comment]
We have older CoreCLR workloads that we still need to support, and that depend on these types being in mscorlib.  We can remove these only once it is cleaned up (no timeline yet).

**Comment by jkotas** [comment]
cc @AlexGhiondea @weshaggard

**Comment by danmosemsft** [comment]
@jkotas what are these older CoreCLR workloads? Is this no longer the case now we have given up on project K mirroring?

**Comment by jkotas** [comment]
Yes, number of these unused types can be deleted now. It is step 2 mentioned in https://github.com/dotnet/coreclr/issues/972.

https://github.com/dotnet/coreclr/issues/8732 or https://github.com/dotnet/corefx/issues/12678 overlaps with this as well.

**Comment by jamesqo** [comment]
@jkotas I will grab this issue.

**Comment by jamesqo** [comment]
@jkotas, I am thinking of deleting more than just the System.IO files-- I would like to delete the old files in other namespaces you mentioned above, such as System.Security. Can all files that are duplicated between here and corefx (besides the ones in the `corefx/` folder) be deleted? If not, how can I tell which ones are safe to delete?

**Comment by jkotas** [comment]
I do not think there is simple rule how to identify parts that can be deleted without breaking stuff. I would do this in two steps.

First step:

Compare corelib before and after BCLRewriter build step, and physically remove methods and types that BCL rewriter removes. It should be very mechanical (though tedious) change. There may be some outliers where BCL rewriter deletes internal constants and enums, but you need to keep them to make things compile. As follow up change, BCLRewriter tool can be removed from the build and model.xml deleted.

Second step:

Cleaning up what remains will typically require changes in other places to make sure everything still works:

1. Identify a good cluster of types to delete. Smaller clusters are better.
2. Get corelib building with the files deleted.
3. Run corefx tests against the trimmed corelib.
4. Submit PR
5. Repeat

For example, src\mscorlib\src\System\Security\Principal\* (duplicated with corefx) should be a good cluster to delete. `FEATURE_IMPERSONATION` can be deleted together with it.

**Comment by danmosemsft** [comment]
Another link. https://github.com/dotnet/corefx/issues/5540

**Comment by jamesqo** [comment]
Great, thanks to both of you for the advice/related issue.

**Comment by jamesqo** [comment]
@jkotas I used [Mono.Cecil](http://www.mono-project.com/docs/tools+libraries/libraries/Mono.Cecil/faq/) to print out a list of all types not in the rewritten assembly; see [here](https://gist.github.com/jamesqo/719d955e4e1edd78a426df1123a3c8b0#file-program-cs). I will be removing the types in that list.

**Comment by jkotas** [comment]
Some of the types in your list do not look right, e.g. ValueTuple* or ConfigurableArrayPool should stay. Do you have latest builds of both .dlls?

**Comment by jamesqo** [comment]
@jkotas I rebased to lastest master and re-ran the program ([updated the gist](https://gist.github.com/jamesqo/719d955e4e1edd78a426df1123a3c8b0/revisions)). `ValueTuple` and `ConfigurableArrayPool` have disappeared.

**Comment by AlexGhiondea** [comment]
@jamesqo BCL Rewriter will dump out a file containing the implementation closure based on the roots in model.xml. You can probably use that file to figure out exactly what can be removed.

**Comment by jamesqo** [comment]
@AlexGhiondea Which file is it?

**Comment by danmosemsft** [comment]
@jamesqo the files seem to be 
```
coreclr\bin\obj\Windows_NT.x64.Debug\BclRewriter\System.Private.CoreLib.apiClosure.xml
coreclr\bin\obj\Windows_NT.x64.Debug\BclRewriter\System.Private.CoreLib.implClosure.xml
```

Those list the API it kept, and can be compared with https://github.com/dotnet/coreclr/blob/master/src/mscorlib/model.xml. 

Looking at BCL Rewriter code at https://github.com/dotnet/buildtools/tree/master/src/BinaryRewriting it does not seem to have a way to dump what it decided to strip. it could be taught to, or there are other ways. (Simply diffing the public API of course doesn't help us see any dead private API)

**Comment by AlexGhiondea** [comment]
@jamesqo I did a diff of the APIs in S.P.CoreLib before and after BCLRewriter runs and I have attached the results to this issue. 

That list is the list of members that can be safely removed from code as they get stripped away by the rewriter anyway.
[APIsRemovedByBCLRewriter.xlsx](https://github.com/dotnet/coreclr/files/694464/APIsRemovedByBCLRewriter.xlsx)

**Comment by danmosemsft** [comment]
We may want to use a rewriter for this as there are just so many types and methods that it will be a long time doing it piecewise.

**Comment by danmosemsft** [comment]
@jamesqo let me know if you believe I missed anything.

**Comment by jamesqo** [comment]
@danmosemsft Great to see that PR merged! While there is a lot less cruft in corelib now, I still see many types that were not being removed by the rewriter in the first place, but don't look like they belong in coreclr, e.g. https://github.com/dotnet/coreclr/tree/master/src/mscorlib/src/System/Security/Util. Maybe we should keep this open for such types.

**Comment by danmosemsft** [comment]
That's part of CAS, which is still there because it's used -- https://github.com/dotnet/coreclr/issues/9321. As I noted in that issue, unfortunately it's not so easy to remove as even in full trust it effectively performs some of the parameter checks, or did so historically. @JeremyKuhne may have more to say about that.

Seperate to that I have a suspicion that the rewriter was not deleting all the code that was in fact dead. Eg., I manually removed an empty interface and a field that wasn't getting used. So it may be there is more to do later. Perhaps there is a tool we can use to find that (a start would be to find anything not reachable by a public entry point, a second phase would be to find anything not reachable through the few CoreFX contracts that reference corlib)

**Comment by JeremyKuhne** [comment]
Those types were just a little more cumbersome to disentangle the pertinent functionality. It looks like @jkotas is in the process of doing so.
