### ISSUE TITLE
WARNING: The target process exited without raising a CoreCLR started event.

### ISSUE THREAD

**Issue by dutts** [dotnet/coreclr#4657]
Following the instructions on https://dotnet.github.io/getting-started/ for OS X and loading the sample Hello World application in Visual Studio Code, if I attempt to debug I see Hello World! in the output but also get the following warning:

> WARNING: The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use NETStandard 1.0.0-rc3-23829 or newer. This may be expected if the target process did not run .NET code.

**Comment by sergiy-k** [comment]
Hi @dutts, which version do you have installed? Can you please try installing the latest version of dotnet/cli from https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-osx-x64.latest.pkg?

@Petermarcu, https://dotnet.github.io/getting-started/ for OS X seems to point to a very old version of the dotnet tools. Any reason why it has not been updated?

**Comment by amarinov** [comment]
@sergiy-k The link you've given install SDK version 1.0.0-rc2-002673 . Where can I get  1.0.0-rc3-23829 from?

**Comment by sergiy-k** [comment]
Yeah, the versioning is a bit confusing. The RC2 version that you posted is actually the version of the dotnet cli tools (it is not the version of CoreCLR).

Please note that the version of CoreCLR from the warning message (1.0.0-rc3-23829) corresponds to a build from the master branch on Feb 29. The link that I gave you installs the latest build of CoreCLR from the RC2 (release/1.0.0-rc2) branch. This what we will ship soon as you can see from this blog: https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/

**Comment by sergiy-k** [comment]
Please let me know if you still have this problem after upgrading to the released RC2 build. Closing the issue for now.

**Comment by ppatel26** [comment]
@sergiy-k I just recently downloaded the latest build (1.0.0-preview2-003131) and I still end up getting that message when executing Hello World! application

**Comment by sergiy-k** [comment]
@mikem8361, could you please take a look?

**Comment by mikem8361** [comment]
@gregg-miskelly @caslan does this look like a versioning problem with dbgshim or the bug we found and fixed in dbgshim?

**Comment by caslan** [comment]
Is the app targeting full framework? If so, the app would launch and then you would see that error.

**Comment by gregg-miskelly** [comment]
@ppatel26 can you tell us more about your scenario? 

The most common known reasons for this are: 

1. As Charlie said, on Windows, trying to debug a full framework app
2. Trying to debug a process where the interesting code is in a child process. `dotnet run` in the most common case like this.

**Comment by ppatel26** [comment]
@gregg-miskelly @caslan @sergiy-k @mikem8361 Here are some screenshots. I am using a Mac   OS X (10.9.5)

![screen shot 2016-10-18 at 2 46 03 pm](https://cloud.githubusercontent.com/assets/22735144/19497596/f2626edc-9541-11e6-9f08-bf5f0a2aae3f.jpeg)

When I do the run from the terminal. I don't end up getting the warning. It shows up after the debug run from Visual Studio Code. 

![screen shot 2016-10-18 at 2 46 07 pm](https://cloud.githubusercontent.com/assets/22735144/19497638/25ffd3b0-9542-11e6-8360-a9a70f3bbc52.jpeg)

**Comment by gregg-miskelly** [comment]
@ppatel26 what does your launch.json look like?

**Comment by ppatel26** [comment]
@gregg-miskelly Here yo go.

![screen shot 2016-10-18 at 3 14 32 pm](https://cloud.githubusercontent.com/assets/22735144/19498438/b37d3cca-9545-11e6-93fb-7cbed8c76e3c.jpeg)

**Comment by gregg-miskelly** [comment]
Three questions: 
1. What version of the .NET Core Shared Framework do you have installed? You can run `dotnet` in terminal to see. (see below for an example)
2. What version of the VS Code C# extension do you have installed? You can see this in the extensions pan in VS Code.
3. Can you test if `vmmap` is working for you (see below for instructions).

Example output from `dotnet`:
```
MAC:~/cliver> dotnet

Microsoft .NET Core Shared Framework Host

  Version  : 1.0.1
  Build    : cee57bf6c981237d80aa1631cfe83cb9ba329f12
````

Testing vmmap: 
1. Open a C# source file in vscode
2. Find the OmniSharp process id (`ps -A | grep OmniSharp`)
3. See if vmmap can tell you the path to libcoreclr.dylib (`vmmap <pid> | grep coreclr.dylib | head -1`)

Example:
```
MAC:~/cliver> ps -A | grep OmniSharp | head -1
16508 ??         0:13.76 /Users/greggm/.vscode/extensions/ms-vscode.csharp-1.3.0/out/.omnisharp-coreclr/OmniSharp -s /Users/greggm/cliver --hostPID 16494 DotNet:enablePackageRestore=false --stdio
MAC:~/cliver> vmmap 16508 | grep coreclr.dylib | head -1
__TEXT                 0000000100824000-0000000100bc0000 [ 3696K] r-x/rwx SM=COW  /Users/greggm/.vscode/extensions/ms-vscode.csharp-1.3.0/out/.omnisharp-coreclr/libcoreclr.dylib
```

**Comment by ppatel26** [comment]
@gregg-miskelly 
1) .NET Core version 1.0.1
![screen shot 2016-10-18 at 8 51 24 pm](https://cloud.githubusercontent.com/assets/22735144/19505147/f938307e-9574-11e6-86f4-fdf51da71589.jpeg)

2) VS Code C# extension version 1.4.1

3) `parvs-mbp:~ parvpatel$ ps -A | grep OmniSharp
  503 ??         0:07.68 /Users/parvpatel/.vscode/extensions/ms-vscode.csharp-1.4.1/out/.omnisharp-coreclr/OmniSharp -s /Users/parvpatel/Desktop/Programming Projects/CSharp Projects/testhw --hostPID 478 DotNet:enablePackageRestore=false --encoding utf-8 --stdio
  526 ttys000    0:00.00 grep OmniSharp
parvs-mbp:~ parvpatel$ vmmap 503 | grep coreclr.dylib | head -1
__TEXT                 000000010c655000-000000010c9f1000 [ 3696K] r-x/rwx SM=COW  /Users/parvpatel/.vscode/extensions/ms-vscode.csharp-1.4.1/out/.omnisharp-coreclr/libcoreclr.dylib
`

**Comment by gregg-miskelly** [comment]
@ppatel26 that all looks reasonable. 
@mikem8361 any other guesses? Anything @ppatel26 can do to troubleshoot this?

**Comment by mikem8361** [comment]
I’ll try to repro locally on my Windows dev machine.

**Comment by gregg-miskelly** [comment]
@mikem8361 this is just debugging hello world, so its not going to be something you will be able to repro locally. There must be something configured differently on ppatel26's macOS box that breaks dbgshim.

**Comment by mikem8361** [comment]
Oops. For some reason I thought this was on Windows.  

I'm not sure what to do now.

**Comment by gregg-miskelly** [comment]
Can @ppatel26 check for the existence of semaphores and/or check if they can be successfully created? Would it make sense to provide a private dbgshim with some logging?

**Comment by mikem8361** [comment]
There is some logging that can be enabled in a debug build. Not sure how to get a debug dbgshim.dylib to ppatel26.  On OS X, the semaphores used in the handshake are not visible from the file system like they are in Linux.

**Comment by mikem8361** [comment]
To enable this logging on a debug dbgshim, this environment variable would have to be set before running vscode/coreclr:

export PAL_DBG_CHANNELS="+PROCESS.TRACE"

**Comment by mikem8361** [comment]
I'm building a debug dbgshim with the above tracing enabled.

**Comment by mikem8361** [comment]
@ppatel26 I have a debug dbgshim.dylib that you can try but I'm not sure how to get a binary to you.

**Comment by gregg-miskelly** [comment]
@mikem8361 can you zip it and attach it to this issue? @ppatel26 to try Mike's tracing:

```
cd ~/.vscode/extensions/ms-vscode.csharp-1.4.1/coreclr-debug/debugAdapters
mv libdbgshim.dylib libdbgshim.dylib.bak
cp <path-you-downloaded> .
```

**Comment by mikem8361** [comment]
[dbgshim.zip](https://github.com/dotnet/coreclr/files/542774/dbgshim.zip)

**Comment by mikem8361** [comment]
The logging should be a file called "dbgshimtrace.txt"

**Comment by ppatel26** [comment]
@gregg-miskelly I copied @mikem8361 provided dbgshim.dylib into its respective directory and debugged the Hello World app. Still the same warning!

@mikem8361 Not sure where to get that log file form. Can you provide some directions. Thanks.

**Comment by mikem8361** [comment]
I'm not sure exactly where it would put the dbgshimtrace.txt log file.  First look in ~/.vscode/extensions/ms-vscode.csharp-1.4.1/coreclr-debug/debugAdapter. Then you may need to search with something like 

`find ~ -name "dbgshimtrace.txt"`

**Comment by ppatel26** [comment]
@mikem8361 @gregg-miskelly here you go. 

This is what the log file says. 

```
{0x38e5c-0x1073d5800}` TRACE [PROCESS] at PROCAddThread.3288: Thread 0x00007FC756000600 (id 0x38e5c) added to the process thread list
{0x38e5c-0x1073d5800} TRACE [PROCESS] at Register.1599: PAL_RuntimeStartupHelper.Register creating startup '/clrst000009420000000058093f84' continue '/clrco000009420000000058093f84'
{0x38e5c-0x1073d5800} TRACE [PROCESS] at PROCAddThread.3288: Thread 0x00007FC756800000 (id 0) added to the process thread list
{0x38ea2-0x1073d5800} TRACE [PROCESS] at StartupHelperThread.1790: PAL's StartupHelperThread starting
{0x38ea2-0x1073d5800} TRACE [PROCESS] at IsCoreClrProcessReady.1696: IsCoreClrProcessReady: stat(/tmp/clr-debug-pipe-2370-1477001092-in) FAILED: errno is 2 (No such file or directory)
{0x38ea2-0x1073d5800} TRACE [PROCESS] at StartupHelperThread.1762: sem_wait(startup)
{0x38ea2-0x1073d5800} TRACE [PROCESS] at InvokeStartupCallback.1727: InvokeStartupCallback executing callback 000000010C938000 /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.0.1/libcoreclr.dylib
{0x38ea2-0x1073d5800} TRACE [PROCESS] at PROCRemoveThread.3332: Thread 0x00007FC756800000 (id 0x38ea2) removed from the process thread list
```

**Comment by mikem8361** [comment]
This logging says basically we waited until coreclr was ready and then called back from the "PAL" code to the "dbgshim" code without any problems.  Even though all of this code is in the same module, it is layered in a way that makes it hard to log anything in the dbgshim code using the PAL tracing.

There are a few things that can fail once we call the dbgshim but before we call VS back:
1) libmscordbi.dylib isn't in /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.0.1 (where libcoreclr.dylib is)
2) Can't find the CoreCLRCreateCordbObject entry on libmscordbi.dylib (not very likely)
3) Error creating the ICorDebug instance

Even if any of these things fail, VS will get called back with an error (which is probably where the error message is coming from).

**Comment by lakartoza** [comment]
Hey guys, Noob contributor here. 

I had a similar situation where I had the error 
>WARNING: The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use NETStandard 1.0.0-rc3-23829 or newer. This may be expected if the target process did not run .NET code.

It didn't work even after installing the `Nuget package Microsoft.NETCore.App 1.0.1` but when I changed the version to `Nuget package Microsoft.NETCore.App 1.0.0` it started right up and launched localhost:5000 etc etc

**Comment by gregg-miskelly** [comment]
@lakartoza if you are still interested in troubleshooting this -- when you were using 1.0.1, did the app start correctly?
