### ISSUE TITLE
RyuJIT x86: using temps during long decomposition to avoid bad codegen

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4659]
JIT\Methodical\AsgOp\i8\i8_cs_d\i8_cs_d.cmd
JIT\Methodical\AsgOp\i8\i8_cs_do\i8_cs_do.cmd
JIT\Methodical\AsgOp\i8\i8_cs_r\i8_cs_r.cmd
JIT\Methodical\AsgOp\i8\i8_cs_ro\i8_cs_ro.cmd

test output:

Initial parameters: x is -10 and y is 4.
f11     x += x - y failed.
x: -8589934616,         expected: -24

Initial parameters: x is -10 and y is 4.
f18     x += x ^ y failed.
x: -4294967320,         expected: -24

Initial parameters: x is -10 and y is 4.
f19     x += x | y failed.
x: -4294967316,         expected: -20
Expected: 100
Actual: 1

**Comment by mikedn** [comment]
Eww, `x += x - y` generates the sequence `sub, add, sbb, adc`, the lo and hi parts are out of order.

**Comment by mikedn** [comment]
It looks like the fix done in #3296 is incorrect, the lo and hi nodes need to be chained after the original `GT_LONG` node to ensure that both halves have been already computed. Instead they are chained after `GT_LONG`'s sources.

**Comment by mikedn** [comment]
And I suspect this can't be easily fixed as the required linear order is not a valid tree traversal order. Some temporaries and some embedded statements need to be introduced.

**Comment by BruceForstall** [comment]
Looks like we have a pretty fundamental issue with how we model long operations. In general, the decomposition converts as follows:
```
		+ (long(lo1, hi1), long(lo2, hi2))
		=>
		long (+ (lo1, lo2), +Hi (hi1, hi2))
```
but what if lo1 is '+' and hi1 is '+Hi'? So:
```
		+ (long( + (lo3, lo4), +Hi (hi3, hi4) ), long(lo2, hi2))
		=>
		long (+ ( + (lo3, lo4), lo2), +Hi ( +Hi (hi3, hi4), hi2))
```
But we can't put any instructions between `+ (lo3, lo4)` and `+Hi (hi3, hi4)` or we’ll lose the carry bits. Maybe we need temps here, but I think we might need to reconsider how we model it altogether.

**Comment by mikedn** [comment]
> Maybe we need temps here, but I think we might need to reconsider how we model it altogether.

I'm not sure if there are many options available. It's either decomposition in lowering + temps (and this isn't the only case where temps are needed, the int->long cast needs a temp too) or no decomposition in lowering + reg alloc and code gen for `TYP_LONG` ops.

**Comment by BruceForstall** [comment]
The decomposition was intended to make reg alloc simpler, but it seems it's just moved the complexity elsewhere. LSRA previously did handle "reg pair" allocation for longs (where nodes remain longs and aren't decomposed), but it was pretty complex. That was a while ago, though; perhaps the reg alloc experts will have a different perspective now.

**Comment by mikedn** [comment]
Well, at least for add/sub there's a 3rd option: allow true linear IR to be used in lowering :)

**Comment by BruceForstall** [comment]
Converted to NYI with #4782.

**Comment by mikedn** [comment]
@BruceForstall FWIW I've played with decomposition and got these tests to pass. The fixed code doesn't look any more complicated than the old code to me. However, it needs better handling of the introduced temporaries, at a minimum they should be reused instead of being created every time when a node is decomposed. Because of these temporaries the CQ is worse than in the old JIT:
```
       8B442410     mov      eax, dword ptr [esp+10H]
       8B542414     mov      edx, dword ptr [esp+14H]
       8B4C2408     mov      ecx, dword ptr [esp+08H]
       8B74240C     mov      esi, dword ptr [esp+0CH]
       2BC1         sub      eax, ecx
       1BD6         sbb      edx, esi
       8B4C2410     mov      ecx, dword ptr [esp+10H]
       8B742414     mov      esi, dword ptr [esp+14H]
       03C1         add      eax, ecx
       89442410     mov      dword ptr [esp+10H], eax
       13D6         adc      edx, esi
       89542414     mov      dword ptr [esp+14H], edx
       8B442410     mov      eax, dword ptr [esp+10H]
       8B542414     mov      edx, dword ptr [esp+14H]
```
versus
```
       8B4C2410     mov      ecx, dword ptr [esp+10H]
       8B742414     mov      esi, dword ptr [esp+14H]
       8BC1         mov      eax, ecx
       8BD6         mov      edx, esi
       2B442408     sub      eax, dword ptr [esp+08H]
       1B54240C     sbb      edx, dword ptr [esp+0CH]
       03C1         add      eax, ecx
       13D6         adc      edx, esi
       8BC8         mov      ecx, eax
       8BF2         mov      esi, edx
       8BC1         mov      eax, ecx
       8BD6         mov      edx, esi
```

If the team is interested in continuning on the decomposition path I could help. My experimental changes are [here](https://github.com/mikedn/coreclr/blob/decompose/src/jit/lower.cpp#L424).

**Comment by BruceForstall** [comment]
@mikedn Excellent! I was planning on implementing this when I had the chance. We talked about this implementation option internally, and were worried about both CQ and complexity of the IR (the dumps with lots of embedded statements are going to be very hard to read/understand). Perhaps these operations are handling "contained" memory operands (in your examples, everything is in registers). Or perhaps LSRA will require some preferencing tweaks.

/cc @CarolEidt @sivarv @RussKeldorph @adiaaida

**Comment by sivarv** [comment]
Right now lowering reg specification for 'hi' opers is not marking containable second immediate/memory operand as contained.  'Hi' opers in lowerxarch.cpp::TreeNodeInfoInit() are defaulting to srcCount=2 and dstCount=1.  Fixing this should help CQ quite a bit.

**Comment by mikedn** [comment]
> the dumps with lots of embedded statements are going to be very hard to read/understand

I was concerned about getting nested embedded statements but that doesn't happen in the test I used (`x += x - y;` from method `f11`). The IR dump (before LSRA) looks like this:
```
***** BB01, stmt 2 (top level)
     ( 36, 28) [000008] ------------             *  stmtExpr  void  (top level) (IL 0x000...0x005)
     (  4,  3) [000025] ------------             |        {  *  stmtExpr  void  (embedded) (IL 0x000...0x005)
N007 (  3,  2) [000014] ------------             |        {  |  /--*  lclVar    int    V03 rat1          REG NA
N009 (  4,  3) [000023] DA----------             |        {  \--*  st.lclVar int    V07 rat5          REG NA
     (  4,  3) [000029] ------------             |        {  *  stmtExpr  void  (embedded) (IL 0x000...0x005)
N011 (  3,  2) [000003] ------------             |        {  |  /--*  lclVar    int    V04 rat2          REG NA $81
N013 (  4,  3) [000027] DA----------             |        {  \--*  st.lclVar int    V08 rat6          REG NA
     (  4,  3) [000033] ------------             |        {  *  stmtExpr  void  (embedded) (IL 0x000...0x005)
N015 (  3,  2) [000016] ------------             |        {  |  /--*  lclVar    int    V05 rat3          REG NA
N017 (  4,  3) [000031] DA----------             |        {  \--*  st.lclVar int    V09 rat7          REG NA
     (  4,  4) [000041] ------------             |        {  *  stmtExpr  void  (embedded) (IL 0x000...0x005)
N019 (  1,  1) [000020] ------------             |        {  |     /--*  lclVar    int    V06 rat4          (last use) REG NA
N021 (  1,  1) [000028] ------------             |        {  |     +--*  lclVar    int    V08 rat6          (last use) REG NA
N023 (  3,  3) [000004] ------------             |        {  |  /--*  -         int    REG NA $140
N025 (  4,  4) [000039] DA----------             |        {  \--*  st.lclVar int    V10 rat8          REG NA
     (  4,  4) [000045] ------------             |        {  *  stmtExpr  void  (embedded) (IL 0x000...0x005)
N027 (  1,  1) [000024] ------------             |        {  |     /--*  lclVar    int    V07 rat5          (last use) REG NA
N029 (  1,  1) [000032] ------------             |        {  |     +--*  lclVar    int    V09 rat7          (last use) REG NA
N031 (  3,  3) [000034] ------------             |        {  |  /--*  -Hi       int    REG NA
N033 (  4,  4) [000043] DA----------             |        {  \--*  st.lclVar int    V11 rat9          REG NA
     (  4,  3) [000049] ------------             |        {  *  stmtExpr  void  (embedded) (IL 0x000...0x005)
N035 (  3,  2) [000001] ------------             |        {  |  /--*  lclVar    int    V02 rat0          REG NA $80
N037 (  4,  3) [000047] DA----------             |        {  \--*  st.lclVar int    V12 rat10         REG NA
     (  4,  3) [000053] ------------             |        {  *  stmtExpr  void  (embedded) (IL 0x000...0x005)
N039 (  3,  2) [000036] ------------             |        {  |  /--*  lclVar    int    V03 rat1          REG NA
N041 (  4,  3) [000051] DA----------             |        {  \--*  st.lclVar int    V13 rat11         REG NA
     ( 36, 28) [000057] ------------             |        {  *  stmtExpr  void  (embedded) (IL 0x000...  ???)
N043 (  1,  1) [000040] ------------             |        {  |     /--*  lclVar    int    V10 rat8          (last use) REG NA
N045 (  1,  1) [000048] ------------             |        {  |     +--*  lclVar    int    V12 rat10         (last use) REG NA
N047 ( 26, 20) [000005] ------------             |        {  |  /--*  +         int    REG NA $141
N049 ( 36, 28) [000007] BA----------             |        {  \--*  st.lclVar int    V02 rat0          REG NA
N051 (  1,  1) [000044] ------------             |     /--*  lclVar    int    V11 rat9          (last use) REG NA
N053 (  1,  1) [000052] ------------             |     +--*  lclVar    int    V13 rat11         (last use) REG NA
N055 ( 26, 20) [000054] ------------             |  /--*  +Hi       int    REG NA
N057 ( 36, 28) [000056] B-----------             \--*  st.lclVar int    V03 rat1          REG NA
```
Besides, `fgInsertEmbeddedFormTemp` is a blunt hammer. You get an embedded statement and a temp even they aren't needed. In the case of `f11` it should be possible to use the original GT_LCL_VAR nodes, there's no need to introduce temporaries.

> Right now lowering reg specification for 'hi' opers is not marking containable second immediate/memory operand as contained...

I'll take a look, thanks for the hint!

**Comment by mikedn** [comment]
@sivarv It seems to me that the second memory operand is not always contained even for non "hi" opers:
```C#
static int Add(int a, int b, int c, int d, int x, int y) => x + y;
```
generates
```
8B442428             mov      eax, dword ptr [rsp+28H]
8B542430             mov      edx, dword ptr [rsp+30H]
03C2                 add      eax, edx
```
This probably happens because `isMemoryOp` doesn't recognize `GT_LCL_VAR`.

**Comment by CarolEidt** [comment]
@mikedn Thanks for all of this - it doesn't look nearly as bad as I feared. Regarding the non-containment of the lclVar, that is something that I have been aware of as a possibility, but hadn't had the focused time to find examples. I assume that those are register candidates, which I believe is how they fall through the cracks - if they don't actually get a register, I don't think we have the logic to make them contained.

**Comment by mikedn** [comment]
@CarolEidt My first impression is that containment is a bit of a chicken & egg problem. `TreeNodeInfoInit` doesn't know that a lclVar will end up in memory or in a register before LSRA runs and then LSRA tries to allocate a register because the node isn't contained. Now, the above examples may hit a special case, those lclVars are non-register method parameters. But in the general case it seems that containment decision would somehow be LSRA's job.

I'll test with more complicated long expressions that use fields instead and see how it goes. The test that I picked up is a bit unfortunate as it hits a problem that's not specific to decomposition.

**Comment by mikedn** [comment]
FYI I tried to use fields in long expressions and had to add support for `GT_IND`/`GT_STOREIND`. These have their own specific problem - the address needs to be put in a temp. But simply making a temp from the address isn't good enough from a CQ point of view because you end up with address expressions like `((base + fieldOffset) + 4)` where `(base + fieldOffset)` uses a `lea`. Ideally we need to create a temp out of base so we get `base + (fieldOffset + 4)` with `fieldOffset + 4` being folded in the memory operand offset. At this point I wonder if it wouldn't be better to make decomposition after lowering, when we have GT_LEA nodes.

**Comment by mikedn** [comment]
I managed to convince decomposition to transform
```C#
    void Test()
    {
        w = x + (y - z) + w; // all variables are instance fields
    }
```
into
```
G_M55886_IG02:
       8B4104       mov      eax, dword ptr [ecx+4]
       8B5108       mov      edx, dword ptr [ecx+8]
       8B710C       mov      esi, dword ptr [ecx+12]
       8B7910       mov      edi, dword ptr [ecx+16]
       2B7114       sub      esi, dword ptr [ecx+20]
       1B7918       sbb      edi, dword ptr [ecx+24]
       03C6         add      eax, esi
       13D7         adc      edx, edi
       03411C       add      eax, dword ptr [ecx+28]
       135120       adc      edx, dword ptr [ecx+32]
       89411C       mov      dword ptr [ecx+28], eax
       895120       mov      dword ptr [ecx+32], edx
```
It's not ideal but it's similar to the JIT32 output and even a bit better (JIT32 puts a temporary on the stack).

**Comment by BruceForstall** [comment]
Nice!

**Comment by BruceForstall** [comment]
I reopened the issue and changed the title to more accurately describe the discussion.

**Comment by RussKeldorph** [comment]
@mikedn Does this issue hold value after LIR?

**Comment by mikedn** [comment]
@RussKeldorph The original issue no longer exists but the NYI is still [there](https://github.com/dotnet/coreclr/blob/master/src/jit/decomposelongs.cpp#L804). I'll use the existing #5884 to remove it (sometime this weekend).
