### ISSUE TITLE
RyuJIT x86: Silent bad codegen with 10w5d_cs

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4660]
JIT\Methodical\fp\exgen\10w5d_cs_d\10w5d_cs_d.cmd
JIT\Methodical\fp\exgen\10w5d_cs_do\10w5d_cs_do.cmd
JIT\Methodical\fp\exgen\10w5d_cs_r\10w5d_cs_r.cmd
JIT\Methodical\fp\exgen\10w5d_cs_ro\10w5d_cs_ro.cmd

test output: 

*lots of omitted output*
Func_0_4_3_1_1: != true
Func_0_4_2_5_4: <= true
Func_0_4_2_5_1: != true

Unhandled Exception: System.OverflowException: Value was either too large or too small for an Int16.
   at System.Convert.ThrowInt16OverflowException()
   at System.Convert.ToInt16(Int64 value)
   at testout1.Func_0_4_2_2_1()
   at testout1.Func_0_4_2_2()
   at testout1.Func_0_4_2()
   at testout1.Func_0_4()
   at testout1.Func_0()
   at testout1.Main()
Expected: 100
Actual: -532462766

**Comment by mikedn** [comment]
Likely another #4664. The value that feeds into the second `Convert.ToInt16` from `Func_0_4_2_2_1` is an `int` converted to `long` via `* 1L`.

**Comment by mikedn** [comment]
Once the cast is fixed the following 2 tests
JIT\Methodical\fp\exgen\10w5d_cs_do\10w5d_cs_do.cmd
JIT\Methodical\fp\exgen\10w5d_cs_ro\10w5d_cs_ro.cmd
fail the following assertion:
```
Assert failure(PID 10116 [0x00002784], Thread: 9348 [0x2484]): Assertion failed 'addr->OperIsAddrMode() || (addr->IsCnsIntOrI() && addr->isContained()) || !addr->isContained()' in 'testout1:Func_0_4_2_2_1():double' (IL size 112)

    File: d:\projects\coreclr\src\jit\emitxarch.cpp Line: 2698
    Image: D:\Projects\coreclr\bin\Product\Windows_NT.x86.Debug\CoreRun.exe
```
Both `OperIsAddrMode` and `IsCnsIntOrI` are false but `isContained` is true.

**Comment by mikedn** [comment]
Seems like LSRA did not allocate a register for a GT_ADD node:
```
N041 (  1,  4) [000016] ------------             |     |              /--*  const(h)  int    0x5953694 static Fseq[vtstatic_0_4_2_2_1] REG NA $100
N043 (  3,  6) [000017] ------------             |     |           /--*  indir     ref    REG ecx $143
N045 (  1,  1) [000018] ------------             |     |           +--*  const     int    4 Fseq[#FirstElem, a0_0_4_2_2_1] REG NA $82
N047 (  4,  7) [000019] -------N----             |     |        /--*  +         byref  REG NA $183
N049 (  6,  9) [000020] *--XG-------             |     |     /--*  indir     int    REG ecx <l:$1c4, c:$341>
```

**Comment by mikedn** [comment]
Looks the assert is my fault, I used `fgInsertEmbeddedFormTemp` when fixing the cast. The newly created statement is not lowered and address mode generation no longer works correctly.

**Comment by BruceForstall** [comment]
Closing as dup of #4664. Converted to NYI with https://github.com/dotnet/coreclr/pull/4732.
