### ISSUE TITLE
RyuJIT x86: Silent bad codegen with ldc_div/mul/mulovf family

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4663]
JIT\Methodical\int64\signed\_dbgs_ldc_div\_dbgs_ldc_div.cmd
JIT\Methodical\int64\signed\_dbgs_ldc_mul\_dbgs_ldc_mul.cmd
JIT\Methodical\int64\signed\_dbgs_ldc_mulovf\_dbgs_ldc_mulovf.cmd
JIT\Methodical\int64\signed\_il_dbgs_ldc_div\_il_dbgs_ldc_div.cmd
JIT\Methodical\int64\signed\_il_dbgs_ldc_mul\_il_dbgs_ldc_mul.cmd
JIT\Methodical\int64\signed\_il_dbgs_ldc_mulovf\_il_dbgs_ldc_mulovf.cmd
JIT\Methodical\int64\signed\_rels_ldc_div\_rels_ldc_div.cmd
JIT\Methodical\int64\signed\_rels_ldc_mul\_rels_ldc_mul.cmd
JIT\Methodical\int64\signed\_rels_ldc_mulovf\_rels_ldc_mulovf.cmd
JIT\Methodical\int64\unsigned\_dbgldc_mul\_dbgldc_mul.cmd
JIT\Methodical\int64\unsigned\_dbgldc_mulovf\_dbgldc_mulovf.cmd
JIT\Methodical\int64\unsigned\_il_dbgldc_mul\_il_dbgldc_mul.cmd
JIT\Methodical\int64\unsigned\_il_dbgldc_mulovf\_il_dbgldc_mulovf.cmd
JIT\Methodical\int64\unsigned\_relldc_mul\_relldc_mul.cmd
JIT\Methodical\int64\unsigned\_relldc_mulovf\_relldc_mulovf.cmd

The test cases and failures all look similar.

**Comment by mikedn** [comment]
Looks like #4664 again. IL code for the first failing test:
```
IL_0068:  ldc.i4.m1
IL_0069:  conv.i8
IL_006a:  ldc.i4.s   -2
IL_006c:  conv.i8
```

I'm not quite sure what's the point of creating issues for all the x86 failing tests when simply inspecting `Lowering::DecomposeNode` would reveal tons of issues right anyway.

**Comment by BruceForstall** [comment]
Actual test names:

JIT\Methodical\int64\signed\_dbgs_ldc_div\_dbgs_ldc_div.cmd
JIT\Methodical\int64\signed\_dbgs_ldc_mul\_dbgs_ldc_mul.cmd
JIT\Methodical\int64\signed\_dbgs_ldc_mulovf\_dbgs_ldc_mulovf.cmd
JIT\Methodical\int64\signed\_il_dbgs_ldc_div\_il_dbgs_ldc_div.cmd
JIT\Methodical\int64\signed\_il_dbgs_ldc_mul\_il_dbgs_ldc_mul.cmd
JIT\Methodical\int64\signed\_il_dbgs_ldc_mulovf\_il_dbgs_ldc_mulovf.cmd
JIT\Methodical\int64\signed\_rels_ldc_div\_rels_ldc_div.cmd
JIT\Methodical\int64\signed\_rels_ldc_mul\_rels_ldc_mul.cmd
JIT\Methodical\int64\signed\_rels_ldc_mulovf\_rels_ldc_mulovf.cmd
JIT\Methodical\int64\unsigned\_dbgldc_mul\_dbgldc_mul.cmd
JIT\Methodical\int64\unsigned\_dbgldc_mulovf\_dbgldc_mulovf.cmd
JIT\Methodical\int64\unsigned\_il_dbgldc_mul\_il_dbgldc_mul.cmd
JIT\Methodical\int64\unsigned\_il_dbgldc_mulovf\_il_dbgldc_mulovf.cmd
JIT\Methodical\int64\unsigned\_relldc_mul\_relldc_mul.cmd
JIT\Methodical\int64\unsigned\_relldc_mulovf\_relldc_mulovf.cmd

**Comment by BruceForstall** [comment]
Closing as dup of #4664. Converted to NYI with #4732.
