### ISSUE TITLE
RyuJIT x86: NYI: "Lowering of signed cast TYP_INT->TYP_LONG"

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4664]
JIT\Methodical\MDArray\DataTypes\long_cs_d\long_cs_d.cmd
JIT\Methodical\MDArray\DataTypes\long_cs_do\long_cs_do.cmd
JIT\Methodical\MDArray\DataTypes\long_cs_r\long_cs_r.cmd
JIT\Methodical\MDArray\DataTypes\long_cs_ro\long_cs_ro.cmd

sample test output:

```
ERROR:
result is: -1
2darr[0, 1] is: 4294967295
and they are NOT equal !

ERROR:
result is: -1
cl1.long2darr[0, 1] is: 4294967295
and they are NOT equal !

ERROR:
result is: -1
long3darr[1,0,1] is: 4294967295
and they are NOT equal !

ERROR:
result is: -1
cl1.long3darr[1,0,1] is: 4294967295
and they are NOT equal !

ERROR:
Decimal_result is: -1
2darr[0, 1] is: 4294967295
and they are NOT equal !

ERROR:
Decimal_result is: -1
cl1.long2darr[0, 1] is: 4294967295
and they are NOT equal !

ERROR:
Decimal_result is: -1
long3darr[1,0,1] is: 4294967295
and they are NOT equal !

ERROR:
Decimal_result is: -1
cl1.long3darr[1,0,1] is: 4294967295
and they are NOT equal !

ERROR:
Double_result is: -1
2darr[0, 1] is: 4294967295
and they are NOT equal !

ERROR:
Double_result is: -1
cl1.long2darr[0, 1] is: 4294967295
and they are NOT equal !

ERROR:
Double_result is: -1
long3darr[1,0,1] is: 4294967295
and they are NOT equal !

ERROR:
Double_result is: -1
cl1.long3darr[1,0,1] is: 4294967295
and they are NOT equal !

ERROR:
Single_result is: -1
2darr[0, 1] is: 4294967295
and they are NOT equal !

ERROR:
Single_result is: -1
cl1.long2darr[0, 1] is: 4294967295
and they are NOT equal !

ERROR:
Single_result is: -1
long3darr[1,0,1] is: 4294967295
and they are NOT equal !

ERROR:
Single_result is: -1
cl1.long3darr[1,0,1] is: 4294967295
and they are NOT equal !


Unhandled Exception: System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at longMDArrTest.Main()
Expected: 100
Actual: -532462766
```

**Comment by mikedn** [comment]
This is caused by incomplete int -> long cast code in [`Lowering::DecomposeNode`](https://github.com/dotnet/coreclr/blob/master/src/jit/lower.cpp#L346), it always zero extends.

**Comment by BruceForstall** [comment]
@mikedn Thanks for all the analysis!

**Comment by mikedn** [comment]
I verified that all but 2 tests from #4660 pass is the cast is fixed.

**Comment by BruceForstall** [comment]
Converted to NYI with https://github.com/dotnet/coreclr/pull/4732.

**Comment by mikedn** [comment]
@BruceForstall Does it make sense to send a PR that replaces the NYI with the correct implementation or should this wait until it is decided if decomposition is the way to go?

**Comment by BruceForstall** [comment]
If you already have an implementation that uses temps that fixes this (and I think you do), I would go ahead and submit the PR. We've still been having conversations internally about the possibility of dropping decomposition and instead teaching LSRA about how the more complicated multi-reg lifetime transitions of non-decomposed nodes, and how codegen would use the reg alloc results. (We should probably summarize those meetings on GitHub somewhere.) But those conversations are still speculative, and if you have something that works, it would be good to go ahead and get it in.
