### ISSUE TITLE
RyuJIT x86: Silent bad codegen in Linq.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4666]
JIT\Performance\CodeQuality\Linq\Linq\Linq.cmd

test output:

```
Expected: 100
Actual: -1
```

**Comment by mikedn** [comment]
This one works fine for me.

**Comment by BruceForstall** [comment]
I normally run Debug tests. If you run Checked or Release, you might have different input IL, which might hide the bug. That's unfortunate. Ideally, we would run all tests built all ways. No matter what, we should pick a compilation method and always use it. I opened #4724 to track this.

**Comment by BruceForstall** [comment]
This failure is because the GC write barrier helper calls trash EDX, but that wasn't being properly modeled. In this case, EDX held an address that was expected to be live across the helper call, so we trashed some random memory, and didn't write to the correct slot of an object.

The method with the failure was <GetEnumerator>d__3[__Canon][System.__Canon]:MoveNext():bool:this, the the helper was CORINFO_HELP_CHECKED_ASSIGN_REF_EAX.
