### ISSUE TITLE
RyuJIT x86: Silent bad codegen in b12053

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4667]
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b12053\b12053\b12053.cmd

Issue with long? or neg?

test output:

```
2147483648 != 2147483648
Test failed!
Expected: 100
Actual: 1
```

correct output:

```
2147483648 != -2147483648
Test passed.
Expected: 100
Actual: 100
```

**Comment by mikedn** [comment]
Same as #4664. `ian` should be sign extended and 0x80000000 should be zero extended but both are zero extended.

**Comment by BruceForstall** [comment]
Closing as dup of #4664. Converted to NYI with #4732.
