### ISSUE TITLE
RyuJIT x86: Silent bad codegen in Haar-likeFeaturesGeneric_r.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4668]
JIT\SIMD\Haar-likeFeaturesGeneric_r\Haar-likeFeaturesGeneric_r.cmd

Test output:

```
Expected: 100
Actual: 0
END EXECUTION - FAILED
```

**Comment by mikedn** [comment]
Another #4664 it seems. The `generateAndMask` contains and int->long cast as well:
```
res[i] = BitConverter.Int64BitsToDouble(-1);
```
that generates
```
       33C0         xor      eax, eax
       50           push     eax
       B8FFFFFFFF   mov      eax, -1
       50           push     eax
```
Hard to say if this is the only issue that test has, I suppose I could fix the cast and see what happens.

**Comment by BruceForstall** [comment]
Closing as dup of #4664. Converted to NYI with #4732.
