### ISSUE TITLE
ARM, SOS: segment fault while debugging with LLDB-3.8

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#4672]
These commands don't work properly
- [x] DumpStack (dumpstack)
- [x] EEStack (eestack)
- [x] ClrStack (clrstack)

Use source and steps in #4671 , give above commands, in (lldb) prompt.

Result:
```
(lldb) dumpstack
Segmentation fault (core dumped)
```

**Comment by seanshpark** [comment]
CC @lucenticus

**Comment by lucenticus** [comment]
I've got a segmentation fault with hello.exe application from emulator too. But when I tried to run lldb under gdb, lldb doesn't crash and `dumpstack` command seems workning. 
` gdb --args ~/llvm-rasp-arm-debug/bin/lldb -o "plugin load libsosplugin.so" -o "process launch -s" -o "process handle -s false SIGUSR1 SIGUSR2" -o "breakpoint set -n LoadLibraryExW" -o "process continue" -o "dumpstack" corerun hello.exe`

Can you reproduce this issue under gdb?

**Comment by seanshpark** [comment]
Yes, running inside `gdb` works.
But result seems strange. (Raspberry Pi 2, Ubuntu Mate 15.10), (each line of output is cutoff cause of long string, Caller and Callee seems valid output)
```
...
(lldb) dumpstack
OS Thread Id: 0x20eb (1)
TEB information is not available so a stack size of 0xFFFF is assumed
Current frame: libcoreclr.so!LoadLibraryExW + 0 
ChildFP  RetAddr  Caller, Callee
63CFD6B8 ??v%?>t libcoreclr.so!SetLastError + 0
63CFD6B8 L??~ libcoreclr.so!operator delete[](void*) + 0
63CFD6B8  libcoreclr.so!SBuffer::DeleteBuffer(unsigned char*, unsigned int) + 0
...
```
`RetAddr` doesn't seem to be a valid output. 

When I run the same thing with `lldb` (with a debug build) in x86_64 (Ubuntu 14.04) `RetAddr` output seems ok
```
...
(lldb) dumpstack
OS Thread Id: 0x562a (1)
TEB information is not available so a stack size of 0xFFFF is assumed
Current frame: libcoreclr.so!LoadLibraryExW + 0x23
Child-SP         RetAddr          Caller, Callee
00007FFFFFFF76F0 00007ffff6607fd6 libcoreclr.so!CorUnix::CPalThread::SetLastError(unsigned int) + 0x16 
00007FFFFFFF7710 00007ffff6671e33 libcoreclr.so!SetLastError + 0x13
00007FFFFFFF7730 00007ffff5a52539 libcoreclr.so!operator delete[](void*) + 0x39 
00007FFFFFFF7750 00007ffff5a4d7a1 libcoreclr.so!SBuffer::DeleteBuffer(unsigned char*, unsigned int) + 0xd1
...
```

**Comment by seanshpark** [comment]
One problem found is in `src/pal/inc/pah.h`, line about 4710,
```
typedef struct _RUNTIME_FUNCTION {
    DWORD BeginAddress;
    DWORD EndAddress;
    DWORD UnwindData;
} RUNTIME_FUNCTION, *PRUNTIME_FUNCTION;
```
and in about 2967,
```
typedef struct _IMAGE_ARM_RUNTIME_FUNCTION_ENTRY {
    DWORD BeginAddress;
    union {
        DWORD UnwindData;
        struct {
            DWORD Flag : 2;
            DWORD FunctionLength : 11;
            DWORD Ret : 2;
            DWORD H : 1;
            DWORD Reg : 3;
            DWORD R : 1;
            DWORD L : 1;
            DWORD C : 1;
            DWORD StackAdjust : 10;
        };
    };
} IMAGE_ARM_RUNTIME_FUNCTION_ENTRY, * PIMAGE_ARM_RUNTIME_FUNCTION_ENTRY;
```
structure size is compare but as it is different in `src/unwider/unwider.cpp` `GetFunctionEntry()` so it return `E_INVALIDARG`.

```
HRESULT OOPStackUnwinder::GetFunctionEntry(                       DWORD64 address,
                                           __out_ecount(cbBuffer) PVOID   pBuffer,
                                                                  DWORD   cbBuffer)
{
    if (cbBuffer < sizeof(T_RUNTIME_FUNCTION))
    {
        return E_INVALIDARG;
    }
```

**Comment by seanshpark** [comment]
Reason for strange output
```
63CFD6B8 ??v%?>t libcoreclr.so!SetLastError + 0
```
is because of
```
DMLOut("%p %s ", (ULONG64)vEBP, DMLIP(IP));
```
casting `(ULONG64)` to the pointer making 64bit that works fine with x64 or arm64 but not for arm 32bit.

@mikem8361 , there are lots of `ULONG64` casting in SOS source and types derived from it. In what way would it be appropriate to change this? 
1) just fix the bug for now, change `"%p"` related arguments cast to ULONG
2) change all address pointers type in SOS to architecture type (32 or 64), not sure the effects.
3) any other way...

**Comment by seanshpark** [comment]
I've found `SOS_PTR()` that is defined as in `strike.h`
```
#ifdef FEATURE_PAL
#define SOS_PTR(x) (size_t)(x)
#else // FEATURE_PAL
#define SOS_PTR(x) (unsigned __int64)(x)
#endif // FEATURE_PAL else
```
Could we use this for all `"%p"`?

**Comment by mikem8361** [comment]
It looks like the bug is in the xplat DMLOut/ExtOut formatting (via g_ExtControl->OutputVaList).  OutputVaList is implemented in xplat/dbgeng.h.  It uses PAL__vsnprintf in pal\src\cruntime\printfcpp.cpp to do the formatting since lldb doesn’t support a lot of the special formatting chars.  The bug is the difference between how %p is defined by the dbgeng apis (the arg is always 64 bits) and the PAL printf code which the arg bitness is based on the platform.  The problem is that the PAL printf code can’t be changed because that is what is expected by the VM code.

**Comment by mikem8361** [comment]
Yes, it looks like the SOS_PTR macro will work on xplat (where the bitness needs to match the platform) but still work on Windows/Windbg where %p is always ULONG64 even on x86/arm.

**Comment by seanshpark** [comment]
OK, I'll go with SOS_PTR(x). Simple test using `(LPVOID)` seems to work with above 3 commands.

**Comment by seanshpark** [comment]
Seems working now.
