### ISSUE TITLE
Cannot clear console

### ISSUE THREAD

**Issue by frapid** [dotnet/coreclr#4683]
Console.Clear() is missing on RC1. Is there a different way of doing this?

**Comment by stephentoub** [comment]
It's available in RC2.  If you pick up the latest packages, you should be able to use it.  As for a workaround on RC1, it would basically be doing the same thing that we do in the Console implementation: P/Invoking at Windows (https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Windows.cs#L757) and writing out the correct ANSI escape string on Unix (https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs#L194).  I expect it'd be easier for you to just move to a more recent version that has the functionality enabled.

**Comment by frapid** [comment]
@stephentoub, I will update to RC2. Thank you for the information.

**Comment by frapid** [comment]
@stephentoub, is there a documentation I can follow to move to RC2? I have installed RC2 build but Visual Studio does not show DNX SDK version "1.0.0-rc2.." on project properties.

**Comment by stephentoub** [comment]
@richlander, can you point @frapid to appropriate docs?
