### ISSUE TITLE
GC\API\GC\GetTotalMemory test fails approx. 15% of runs under GCStress=3

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#4708]
Flavor: Windows x64 Checked (not necessarily specific to that)
Repro (set CORE_ROOT first):
```
@echo off
set COMPlus_GCStress=3
:start
call GetTotalMemory.cmd|findstr END|findstr "PASSED FAILED"
goto :start
```
Expected: FAILED never output
Observed: FAILED sometimes output

Marking this a Test-Issue due to inconsistency and the fact that it only occurs under GCStress.  If this is a real product bug, feel free to reassign.

**Comment by swgillespie** [comment]
This repros on Release as well.

**Comment by RussKeldorph** [comment]
@swgillespie If you won't have a fix immediately, would you mind disabling this under gcstress for the time being?

**Comment by swgillespie** [comment]
@RussKeldorph Yeah, I'll do that - I believe this is a test issue anyway.

**Comment by swgillespie** [comment]
Just disabled the test for GCStress - Going to leave this open while I investigate what's going on.

**Comment by swgillespie** [comment]
Triaged this issue again - this doesn't appear to be a product issue, just an issue with the test. Since the test has been disabled for GCStress, I'm fine leaving it that way.
