### ISSUE TITLE
Build cross-targeting standalone clrjit.dll

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#4717]
As discussed in https://github.com/dotnet/coreclr/pull/4684, we need to build a standalone clrjit.dll for cross-compilation scenarios. We should look into fixing this for RTM.

**Comment by RussKeldorph** [comment]
It's my understanding that the blocking-release label refers to x86 & AMD64 only.

**Comment by pgavlin** [comment]
We already do this.
