### ISSUE TITLE
Disable optimization for debugging?

### ISSUE THREAD

**Issue by terrajobst** [dotnet/coreclr#4722]
On behalf of @SamuelEnglard:

> Is there a way to have the Core JIT not optimize code? Debugging inside CoreFX/Mscorlib is hard with optimizations!

**Comment by briansull** [comment]
You can set the environment variable 
COMPlus_JITMinOpts=1
That will turn off all JIT optimizations

**Comment by RussKeldorph** [comment]
Calling this answered and closing.  Feel free to re-open if the answer isn't sufficient.

**Comment by terrajobst** [comment]
Thanks @briansull!

**Comment by xhafan** [comment]
does not work for me, third party library still shows as optimized in Modules.
