### ISSUE TITLE
Make `System.Runtime.InteropServices.SafeHeapHandle` Public

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/coreclr#4730]
`System.Runtime.InteropServices.SafeHeapHandle` is a class that almost every developer who has used unmanaged memory has had to write. Having it built in would solve many issues and increase the odds of developers who don't know they needed it finding it.

cc: @terrajobst

**Comment by terrajobst** [comment]
@weshaggard @stephentoub @yizhang82

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #18107](https://github.com/dotnet/corefx/issues/18107) via [**ZenHub**](https://www.zenhub.com/)

**Comment by danmosemsft** [comment]
api discussions in corefx
