### ISSUE TITLE
Locals missing in Visual Studio when debugging

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/coreclr#4733]
When I'm debugging ASP.NET Core RC1 in Visual Studio lots of locals will be missing from the debugger. It will not see them in the Locals window, on hover in code, or if I try to use them in the immediate window. There doesn't seem to be a pattern to what is missing, can be anything really even parameters.

Maybe optimization is on by accident?

**Comment by borgdylan** [comment]
The same happens in VSCode using the rtm version of coreclr

**Comment by gkhanna79** [comment]
CC @lt72 @noahfalk

**Comment by borgdylan** [comment]
Since then, my issues got fixed.

**Comment by gkhanna79** [comment]
Very well. I will close this for now.
