### ISSUE TITLE
'Inspecting the state of an object in the debuggee of type System.Type is not supported in this context.'

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/coreclr#4734]
What does this error mean?!?!?

cc: @terrajobst

**Comment by terrajobst** [comment]
@noahfalk might be able help.

**Comment by noahfalk** [comment]
What were you doing that leads up to the error and where does the error appear?

**Comment by SamuelEnglard** [comment]
The stack was in mscorlib if that helps?

**Comment by noahfalk** [comment]
Sorry I don't mean to be pedantic but the error string alone isn't unique enough for me to infer very much yet. You mentioned 'stack' and the error message has the word 'debuggee' in it so would I be safe to assume you were using a debugger? Was the debugger Visual Studio? Was the debuggee an application using .Net Core? 

The error text looks like something that would probably be produced by Visual Studio debugger's expression evaluator. The expression evaluator gets invoked in response to many different situations so without knowing more of what you were doing at the time I'd only be able to give a vague description that some debugger action, either directly or indirectly, was trying to get information from an instance of a System.Type. Whatever that information was it wasn't available so the error was likely produced instead. I'm happy to try giving a more specific interpretation if I had more context and I can ask a Visual Studio debugger dev to come take a look at the thread if it is indeed Visual Studio that you are using?

**Comment by SamuelEnglard** [comment]
Ah. Ok. Sorry, was late and i wasn't thinking. 

I was debugging using VS2015 Update 2 on Win 8.1. The application was an x86 .NET Core, ASP.NET Core. 

Anything else?

**Comment by noahfalk** [comment]
@gregg-miskelly works on VS debugger and might be able to provide a little more precision.

Where did the error string appear within the Visual Studio UI? Next to a particular expression in the locals window? In the immediate window? In a tooltip? Somewhere else? In order to determine why the debugger was trying to inspect a System.Type instance we'd need to understand what the debugger was trying to do for you.

**Comment by SamuelEnglard** [comment]
In the local window

**Comment by gregg-miskelly** [comment]
Were you inspecting a reflection object (ex:System.Type, TypeInfo, etc), or something else?

This means that -- you were stopped in a place where the debugger can not func-eval (force the target process to execute a function) so we had to interpret the code to try and evaluate properties and what the debugger was trying to do required inspecting a reflection type. But the CLR doesn't provide APIs to allow the debugger to understand what a System.Type instance represents. So the debugger fails with this error.

**Comment by SamuelEnglard** [comment]
I was debugging `TypeBuilder` code so that sounds about right

**Comment by noahfalk** [comment]
If the error has been reasonably described are we good to close this issue?

**Comment by SamuelEnglard** [comment]
I understand it. think a better error message should be given or even better not happen but that's a different issue

**Comment by Iniii** [comment]
Same problem: I'm debugging in the .net source. I'm hovering over a predicate in System.Linq.Enumberable.Where
"Inspecting the state of an object in the debuggee of type System.Delegate is not supported in this context."

**Comment by zipswich** [comment]
![image](https://user-images.githubusercontent.com/6095671/62426081-4cc42b00-b6ae-11e9-8c3b-1b52092a5cbe.png)
![image](https://user-images.githubusercontent.com/6095671/62426085-59488380-b6ae-11e9-8579-f9977a9a2e66.png)
