### ISSUE TITLE
Viva64 has checked coreclr with their static analyser

### ISSUE THREAD

**Issue by KOLANICH** [dotnet/coreclr#474]
http://www.viva64.com/en/b/0310/
http://habrahabr.ru/company/pvs-studio/blog/253280/

P.S. I am not affiliated with viva but just saw their article and have not found an issue here.

**Comment by jkotas** [comment]
@cmckinsey  Could you please go over the ones in the JIT? I went over the ones outside JIT.

**Comment by cmckinsey** [comment]
Change #591 fixes the set of important issues.
