### ISSUE TITLE
iconUrl in project.json with local file

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/coreclr#4749]
if I use `"iconUrl": ".\\Icon.png"` in my project file with dnx 1.0.0-rc1-16231 I get a compile error that it cannot find the icon.

**Comment by adityamandaleeka** [comment]
@SamuelEnglard. This issue belongs on the aspnet/DNX repo. However, DNX has been deprecated/retired in favor of .NET CLI so I'm not sure anyone would be able to address DNX issues.
