### ISSUE TITLE
Build mac os x x64 error

### ISSUE THREAD

**Issue by proydakov** [dotnet/coreclr#475]
evgenys-iMac:coreclr proydakov$ uname -a
Darwin evgenys-iMac.local 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
evgenys-iMac:coreclr proydakov$ ./build.sh
Commencing CoreCLR Repo build
Setting up directories for build
Checking pre-requisites...
Commencing build of native components for mac.x64.debug
Invoking cmake with arguments: "/Users/proydakov/repository/coreclr" DEBUG
CMake Warning at src/ToolBox/SOS/lldbplugin/CMakeLists.txt:26 (message):
  Cannot find lldb-3.5 or lldb-3.6.  Try installing lldb-3.6-dev (or the
  appropriate package for your platform)

CMake Error at CMakeLists.txt:343 (message):
  error: Detected non x86_64 target processor.  Not supported!

-- Configuring incomplete, errors occurred!
See also "/Users/proydakov/repository/coreclr/binaries/intermediates/mac.x64.debug/CMakeFiles/CMakeOutput.log".
See also "/Users/proydakov/repository/coreclr/binaries/intermediates/mac.x64.debug/CMakeFiles/CMakeError.log".
Failed to generate native component build project!
evgenys-iMac:coreclr proydakov$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
evgenys-iMac:coreclr proydakov$

**Comment by janvorli** [comment]
@proydakov, Could you please try to add this to the root CMakeLists.txt:
`message("Detected processor: ${CMAKE_SYSTEM_PROCESSOR}")`
right before the 
`message(FATAL_ERROR "error: Detected non x86_64 target processor. Not supported!")`
and then run the build again?
It will print what it has found as the system processor.

**Comment by proydakov** [comment]
evgenys-iMac:coreclr proydakov$ ./build.sh
Commencing CoreCLR Repo build
Setting up directories for build
Checking pre-requisites...
Commencing build of native components for mac.x64.debug
Invoking cmake with arguments: "/Users/proydakov/repository/coreclr" DEBUG
CMake Warning at src/ToolBox/SOS/lldbplugin/CMakeLists.txt:26 (message):
  Cannot find lldb-3.5 or lldb-3.6.  Try installing lldb-3.6-dev (or the
  appropriate package for your platform)


Detected processor: i386
CMake Error at CMakeLists.txt:344 (message):
  error: Detected non x86_64 target processor.  Not supported!


-- Configuring incomplete, errors occurred!
See also "/Users/proydakov/repository/coreclr/binaries/intermediates/mac.x64.debug/CMakeFiles/CMakeOutput.log".
See also "/Users/proydakov/repository/coreclr/binaries/intermediates/mac.x64.debug/CMakeFiles/CMakeError.log".
Failed to generate native component build project!

But i have 64 bit mac:

evgenys-iMac:coreclr proydakov$ file /bin/ls
/bin/ls: Mach-O 64-bit executable x86_64

**Comment by proydakov** [comment]
I detect problem. On mac need install cmake 3.0.1

evgenys-iMac:resources proydakov$  /Applications/CMake.app/Contents/bin/cmake --version
cmake version 3.0.1

I use 2 cmake. As the main 2.8.12.2

evgenys-iMac:coreclr proydakov$ cmake --version
cmake version 2.8.12.2

Need edit cmake_minimum_required for mac os x in root CMakeLists.txt

# Require at least version 2.8.12 of CMake
cmake_minimum_required(VERSION 2.8.12)

**Comment by janvorli** [comment]
@proydakov Thank you for testing it and figuring it out. I was just about to ask you about your version of the cmake.
