### ISSUE TITLE
O_RDWR flag for sem_open is invalid on FreeBSD

### ISSUE THREAD

**Issue by brunolauze** [dotnet/coreclr#4752]
O_RDWR  is passed to sem_open  which is not valid in FreeBSD 

https://www.freebsd.org/cgi/man.cgi?query=sem_open

affected file:
src/pal/src/thread/process.cpp

I didn't want to post a pull request here because i think we should review syscalls for FreeBSD and NetBSD and OpenBSD at the same time and that i don't want to suggest any fix.

But a fix example could be:

example from src/pal/src/thread/process.cpp:1549

#if defined(__FreeBSD__)
 m_startupSem = sem_open(startupSemName, O_CREAT | O_EXCL, S_IRWXU, 0);
#else
 m_startupSem = sem_open(startupSemName, O_CREAT | O_EXCL | O_RDWR, S_IRWXU, 0);
#endif

**Comment by janvorli** [comment]
@brunolauze It looks like even on Linux and OSX, the O_RDWR should not be passed in, according to the doc:
http://man7.org/linux/man-pages/man3/sem_open.3.html
https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man2/sem_open.2.html
So we should just fix it by removing the O_RDWR for all platforms.
CC: @mikem8361

**Comment by mikem8361** [comment]
I assumed that the O_RDWR is needed so both ends of the semaphore (debugger and debuggee processes) could write (sem_post) and read (sem_wait). Looking back at the man page below and the one I found a while back, they don’t explicitly say the O_ flags are necessary:

       The oflag argument specifies flags that control the operation of the
       call.  (Definitions of the flags values can be obtained by including
       <fcntl.h>.)  If O_CREAT is specified in oflag, then the semaphore is

I can remove it and run the debugger tests to make sure nothing is broken.

**Comment by janvorli** [comment]
The OSX doc for sem_open states the list of flags explicitly:
```
The value of oflag is formed by or'ing the following values:

           O_CREAT         create the semaphore if it does not exist
           O_EXCL          error if create and semaphore exists
```

**Comment by mikem8361** [comment]
Should I use 0 (zero) for the oflag parameter instead of O_RDWR? In fcntl.h (which defines the oflags for open() at least) O_RDONLY is 0 so that is why I used O_RDWR.

// Does the continue semaphore exists? If it does, the runtime is ready to be debugged.
        continueSem = sem_open(continueSemName, O_RDWR);
        if (continueSem != SEM_FAILED)
        {

**Comment by janvorli** [comment]
I guess using 0 is the way. The FreeBSD doc for sem_open says the same thing as the OSX one, with little added precision:
> The following **bits**	may be set in the oflag	argument:

**Comment by brunolauze** [comment]
@janvorli :+1:  for the 0. I suppose all OS ignores the extra flag and FreeBSD throw EINVAL(22) looking at the time it's been here. The behavior is ok when not mix on the creation, sem_open(O_RDWR) will work but sem_open(O_CREAT | O_EXCL | ORDWR) won't.

**Comment by krytarowski** [comment]
https://man-k.org/man/netbsd/3/sem_open?r=1&q=sem_open

```

DESCRIPTION
The sem_open() function creates or opens the named semaphore specified by name. The returned semaphore may be used in subsequent calls to sem_getvalue(3), sem_timedwait(3), sem_trywait(3), sem_wait(3), sem_post(3), and sem_close().

The following bits may be set in the oflag argument:

O_CREAT
    Create the semaphore if it does not already exist.

    The third argument to the call to sem_open() must be of type mode_t and specifies the mode for the semaphore. Only the S_IWUSR, S_IWGRP, and S_IWOTH bits are examined; it is not possible to grant only “read” permission on a semaphore. The mode is modified according to the process's file creation mask; see umask(2).

    The fourth argument must be an unsigned int and specifies the initial value for the semaphore, and must be no greater than SEM_VALUE_MAX.
O_EXCL
    Create the semaphore if it does not exist. If the semaphore already exists, sem_open() will fail. This flag is ignored unless O_CREAT is also specified.

The sem_close() function closes a named semaphore that was opened by a call to sem_open().

The sem_unlink() function removes the semaphore named name. Resources allocated to the semaphore are only deallocated when all processes that have the semaphore open close it.
```

NetBSD doesn't note  O_RDWR either.
