### ISSUE TITLE
Change the error message from "Process is terminated" to "Process was terminated"

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/coreclr#4756]
Change the error message: https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/vm/eepolicy.cpp#L1366

https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/pal/src/include/pal/palinternal.h#L689

from
"Process is terminated due to StackOverflowException.\n"
to
"Process was terminated due to StackOverflowException.\n"

**Comment by jkotas** [comment]
Fixed by #4786
