### ISSUE TITLE
GetCurrentProcessCpuCount is called > 20 times during EEStartupHelper

### ISSUE THREAD

**Issue by Maoni0** [dotnet/coreclr#4769]
Each time this is called it's making an OS call. This is really unnecessary. We should store the result somewhere.

**Comment by tishion** [comment]
hmm.. It seems that there is a better implementation of  GCToOSInterface in file 

> coreclr\src\gc\sample\gcenv.windows.cpp

but this file is one part of project **GCSample**, which is not the component of CoreCLR

The implementation of GCToOSInterface which is used by CoreCLR is located in:

> dotnet\coreclr\src\vm\gcenv.os.cpp

So I'll try to replace it with the better implementation.

**Comment by janvorli** [comment]
@Maoni0 Looking at the implementation of the GetCurrentProcessCpuCount, I can see that it already caches the result - see https://github.com/dotnet/coreclr/blob/master/src/utilcode/util.cpp#L1203
So it seems we don't need to change anything, right?

**Comment by tishion** [comment]
Alright. I thought GetCurrentProcessCpuCount was a native windows API. Really don't need to change anything.

**Comment by Maoni0** [comment]
oh yeah, you are right. I think I accidently got rid of some code when I was testing. my bad!
