### ISSUE TITLE
If and Else code the same in threadsuspend.cpp

### ISSUE THREAD

**Issue by calebnelton** [dotnet/coreclr#477]
In http://github.com/dotnet/coreclr/blob/master/src/vm/threadsuspend.cpp, when checking for HasLockInCurrentDomain() is true, the if and else sections contain the exact same code.

    void Thread::SetRudeAbortEndTimeFromEEPolicy()
    {
        LIMITED_METHOD_CONTRACT;
        DWORD timeout;
        if (HasLockInCurrentDomain())
        {
           timeout = GetEEPolicy()->GetTimeout(OPR_ThreadRudeAbortInCriticalRegion);
        }
        else
        {
            timeout = GetEEPolicy()->GetTimeout(OPR_ThreadRudeAbortInCriticalRegion);
        }
        ULONGLONG newEndTime;
        if (timeout == INFINITE)
        {
            newEndTime = MAXULONGLONG;
        }
        else
        {
            newEndTime = CLRGetTickCount64() + timeout;
        }
        SetAbortEndTime(newEndTime, TRUE);
    }

**Comment by jkotas** [comment]
Fixed by #476
