### ISSUE TITLE
[RFC] Suggestion on System.PlatformID (mscorlib)

### ISSUE THREAD

**Issue by myungjoo** [dotnet/coreclr#4777]
Today's mscorlib's Environment/OSVersion has "PlatformID" and "Version" information for the given OS. However, the expression power of it is limited and focussed on Windows only. Although we can express "Win32NT 4.5.0.0", we cannot express "Linux 3.10" or "Ubuntu/Linux 3.10".

`src/mscorlib/src/System/PlatformID.cs` of today defined PlatformID as follows:
```
     public enum PlatformID
     {
        Win32S        = 0,
        Win32Windows  = 1,
        Win32NT       = 2,
        WinCE         = 3,      
        Unix          = 4,
        Xbox          = 5,
        MacOSX        = 6
    }
```

With minimal changes on PlatformID, we can expand the expression power greatly:

```
    public enum PlatformID
    {
        // 0xXX000000 : Platform Major-Class (e.g., Windows, UNIX, ...)
        // 0x00XXX000 : Platform Minor-Class (e.g., Linux, FreeBSD, SunOS, ...)
        //       if XXX == 0x000, minor-class is "unspecified"
        // 0x00000XXX : Platform Subclass (e.g., Linux-ubuntu, Linux-fedora, ...)
        //       if XXX == 0x000, subclass is "unspecified"
        Windows         = 0x1000000,
            Win32S              = Windows | 0x1000,
            Win32Windows        = Windows | 0x2000,
            Win32NT             = Windows | 0x3000,
            WinCE               = Windows | 0x4000,
            Xbox                = Windows | 0x5000,

        Unix            = 0x2000000;
            MacOSX              = Unix | 0x1000,
            Linux               = Unix | 0x2000,
                Debian                  = Linux | 0x210,
                Ubuntu                  = Linux | 0x220,
                Fedora                  = Linux | 0x230,
                Redhat                  = Linux | 0x240,
                Slackware               = Linux | 0x250,
            FreeBSD             = Unix | 0x3000,

        MajorClass      = 0xFF000000
        MinorClass      = 0x00FFF000
        SubClass        = 0x00000FFF
    } 
```

I have started writing related code based on the above.

It would be much appreciated if I could get some input/feedback on this approach.
(Adding individual platforms may wait. We can start with "small" examples.)

**Comment by ellismg** [comment]
I do not believe this is a good direction.  We should be changing the underlying enumeration values.  This will break binary compatibility with existing code.

We have added the [RuntimeInformation class](https://github.com/dotnet/corefx/blob/eb1f7d63bf6f126e24d06b95fb64bb1c9fd06451/src/System.Runtime.InteropServices.RuntimeInformation/ref/System.Runtime.InteropServices.RuntimeInformation.cs) in CoreFX and we're using that to expose this sort of open ended configuration information.

If that's not sufficient, we should figure out how to extend that class instead of trying to shoehorn stuff into PlatformID, IMHO.

**Comment by krytarowski** [comment]
I don't like these changes, better to navigate towards just UNIX or POSIX. Using bits for Linux distros I'm afraid is questionable.

**Comment by myungjoo** [comment]
Looks like RuntimeInformation class is going to satisfy the need. Thanks.
