### ISSUE TITLE
If and Else code the same in CodeGen::ins_Copy of jit/instr.cpp

### ISSUE THREAD

**Issue by calebnelton** [dotnet/coreclr#478]
In http://github.com/dotnet/coreclr/blob/master/src/jit/instr.cpp#L3422 when checking the value of dstType the exact same code is in the If and Else block

    /*****************************************************************************
     *
     *  Get the machine dependent instruction for performing a reg-reg copy for dstType
     *
     *  Parameters
     *      dstType   - destination type
     */
    instruction         CodeGen::ins_Copy(var_types   dstType)
    {
    #if defined(_TARGET_XARCH_) && !defined(LEGACY_BACKEND)
        if (varTypeIsSIMD(dstType))
        { 
            return INS_movaps;
        }
        else if (varTypeIsFloating(dstType))
        {
            if (dstType == TYP_FLOAT)
            {
                return INS_movaps;
            }
            else
            {
                return INS_movaps;
            }
        }
        else
        {
            return INS_mov;
        }
    #elif defined (_TARGET_ARM64_)
        if (varTypeIsFloating(dstType))
        {
            return INS_fmov;
        }
        else
        {
            return INS_mov;
        }
    #elif defined(_TARGET_ARM_)
        assert(!varTypeIsSIMD(dstType));
        if (varTypeIsFloating(dstType))
        {
            return INS_vmov;
        }
        else
        {
            return INS_mov;
        }
    #elif defined(_TARGET_X86_)
        assert(!varTypeIsSIMD(dstType));
        assert(!varTypeIsFloating(dstType));
        return INS_mov;
    #else // _TARGET_*
    #error "Unknown _TARGET_"
    #endif
    }

**Comment by mikedn** [comment]
The code is actually correct but perhaps a comment should have been added to explain it. In theory the `else` should use `INS_movapd` but both `movaps` and `movapd` do the same thing. `movaps` is preferred because it's one byte shorter.

**Comment by calebnelton** [comment]
Would it be appropriate to submit a pull request that contains a comment containing this information?

**Comment by mikedn** [comment]
I don't know what the team thinks but it seems like a reasonable request to me. Note that `ins_Load` contains a similar comment:

```
// SSE2 Note: always prefer movaps/movups over movapd/movupd since the
// former doesn't require 66h prefix and one byte smaller than the
// latter.
return (aligned) ? INS_movaps : INS_movups;
```

**Comment by cmckinsey** [comment]
Hi Caleb, as mikedn points out both instructions have the same effect. And yes it's appropriate to submit a PR to add a comment for this.

**Comment by cmckinsey** [comment]
Folded the then/else and added short comment in #591.
