### ISSUE TITLE
Testing libsosplugin

### ISSUE THREAD

**Issue by kvochko** [dotnet/coreclr#4781]
We would like to have a way to test libsosplugin in ARM. For this we considered two options. 
The first one is to write python scripts which will load at the start of lldb and run some scenario. After testing this approach on the host we found that python scripting within lldb is quite unstable and often produces segmentation faults.
Another option is to write a scenario as a set of lldb commands in a text file and provide this file as a `--source` argument to lldb in command line. This approach suffers from reduced flexibility - arguments to SOS commands would have to be hardcoded in the scenario, meaning compiled .exe files will have to be provided along with tests and complicating the writing of new tests.
Is there a better approach to testing libsosplugin?
 FYI @Dmitri-Botcharnikov @lucenticus @seanshpark

**Comment by seanshpark** [comment]
cc @chunseoklee

**Comment by adityamandaleeka** [comment]
@kvochko Now that #4954 is merged, can this issue be closed, or is there some more work remaining?

**Comment by kvochko** [comment]
@adityamandaleeka There will besome tests coming soon, but I think this issue can be closed. Thanks!
