### ISSUE TITLE
crossgen does not properly initialize a dynamically-loaded JIT

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#4785]
In particular, it does not call `sxsJitStartup`. From [zapper.cpp:750](https://github.com/dotnet/coreclr/blob/master/src/zap/zapper.cpp#L750):

```
#if (defined(FEATURE_CORECLR) || !defined(SELF_NO_HOST)) && !defined(CROSSGEN_COMPILE)
    typedef void (__stdcall* pSxsJitStartup) (CoreClrCallbacks const & cccallbacks);
    pSxsJitStartup sxsJitStartupFn = (pSxsJitStartup) GetProcAddress(*phJit, "sxsJitStartup");
    if (sxsJitStartupFn == NULL)
    {
        Error(W("Unable to load Jit startup function: %s\r\n"), pwzJitName);
        ThrowLastError();
    }

    CoreClrCallbacks cccallbacks = GetClrCallbacks();
    (*sxsJitStartupFn) (cccallbacks);
#endif
```

Unfortunately, simply changing the condition on the `#if` to `(defined(FEATURE_CORECLR) || !defined(SELF_NO_HOST)) && !(defined(CROSSGEN_COMPILE) && defined(FEATURE_MERGE_JIT_AND_ENGINE))` doesn't quite get there, as `GetClrCallbacks` asserts.

**Comment by gkhanna79** [comment]
@pgavlin I believe the issue is that clrjit.dll (JIT32) needs to export "jitStartup" similar to what is done for clrjit.dll (x64). Otherwise, not just crossgen but even the runtime will not be able to consume the JIT. Is there a reason why that export is missing?

CC @RussKeldorph

**Comment by pgavlin** [comment]
@gkhanna79 the `jiStartup` function is optional; it is only called if it is exported. The `sxsJitStartup` function, however, is mandatory: it must exist and must always be called as the first step in initializing the JIT after it is loaded.

**Comment by gkhanna79** [comment]
@pgavlin Assigning to you since you are fixing this.

**Comment by pgavlin** [comment]
This has been fixed.
