### ISSUE TITLE
Identical expressions to the left and right of the || operator

### ISSUE THREAD

**Issue by calebnelton** [dotnet/coreclr#479]
This is in http://github.com/dotnet/coreclr/blob/master/src/jit/lsra.cpp

    void  LinearScan::buildRefPositionsForNode(GenTree *tree, ....)
    {
      ....
        // A special case for the GT_CLS_VAR update case, or the GT_CLS_VAR
        // or GT_IND floating point conversion case, where it must produce both
        // a value (of the type of the node) and an address (of TYP_PTR)
        // TODO-Cleanup: Split these to avoid this case.  (This may already have been done
        // by Rationalizer?)
        if ((tree->gtOper == GT_CLS_VAR || tree->gtOper == GT_CLS_VAR) && i == 1)
        {
            registerType = TYP_PTR;
            currCandidates = allRegs(TYP_PTR);
        }
      ....
    }

Probably should be another constant besides GT_CLS_VAR in the expression after the ||.

**Comment by cmckinsey** [comment]
Assigned to Carol. Agreed there is probably an oversight here but not immediately clear what other gt oper should be checked for.

**Comment by CarolEidt** [comment]
I believe (as noted in the comment) that this code is no longer needed, as GT_CLS_VAR is now rationalized properly to avoid the two-value definition problem.  I will look into removing this altogether.

**Comment by ellismg** [comment]
Fixed with #563

**Comment by CarolEidt** [comment]
My commit comment references the wrong issue number.  It should have been this one.
