### ISSUE TITLE
GcStress: Race between background-GC and RedirectionFrame setup 

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#4794]
Windows NT X64 GCStress 0xC failure.

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_gcstress0xc/7/consoleFull

```
set CORE_ROOT=D:\j\workspace\x64_checked_w---cae8e941\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
21:15:06   > D:\j\workspace\x64_checked_w---cae8e941\bin\tests\Windows_NT.x64.Checked\JIT\IL_Conformance\Old\Conformance_Base\shr_u8\shr_u8.cmd
21:15:06   
21:15:06         Expected: True
21:15:06         Actual:   False
21:15:06           src\TestWrappers_x64_Checked\JIT\JIT.XUnitWrapper.cs(88149,0): at JIT._IL_Conformance_Old_Conformance_Base_shr_u8_shr_u8_._IL_Conformance_Old_Conformance_Base_shr_u8_shr_u8_cmd()
21:16:22 D:\j\workspace\x64_checked_w---cae8e941\tests\src\TestWrappers_x64_Checked\JIT\JIT.XUnitWrapper.cs(259476): error : JIT._Methodical_MDArray_DataTypes_bool_cs_do_bool_cs_do_._Methodical_MDArray_DataTypes_bool_cs_do_bool_cs_do_cmd [FAIL] [D:\j\workspace\x64_checked_w---cae8e941\tests\runtest.proj]
21:16:22         
21:16:22         Assert failure(PID 12112 [0x00002f50], Thread: 7868 [0x1ebc]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"
21:16:22         
21:16:22         CORECLR! DoJITFailFast + 0x119 (0x00007ffc`d004d739)
21:16:22         CORECLR! CrawlFrame::SetCurGSCookie + 0x1A (0x00007ffc`cff29eae)
21:16:22         CORECLR! CrawlFrame::GotoNextFrame + 0x11F (0x00007ffc`cff274f3)
21:16:22         CORECLR! StackFrameIterator::NextRaw + 0xD74 (0x00007ffc`cff29350)
21:16:22         CORECLR! StackFrameIterator::Next + 0xC3 (0x00007ffc`cff2851b)
21:16:22         CORECLR! Thread::StackWalkFramesEx + 0x168 (0x00007ffc`cff2a850)
21:16:22         CORECLR! Thread::StackWalkFrames + 0x159 (0x00007ffc`cff2a651)
21:16:22         CORECLR! ScanStackRoots + 0x228 (0x00007ffc`d040c628)
21:16:22         CORECLR! GCToEEInterface::GcScanRoots + 0x1E3 (0x00007ffc`d040b947)
21:16:22         CORECLR! WKS::gc_heap::background_mark_phase + 0x12B2 (0x00007ffc`d04df696)
21:16:22             File: d:\j\workspace\x64_checked_w---cae8e941\src\vm\jithelpers.cpp Line: 5639
21:16:22             Image: D:\j\workspace\x64_checked_w---cae8e941\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
21:16:22         
21:16:22         cmdLine:D:\j\workspace\x64_checked_w---cae8e941\bin\tests\Windows_NT.x64.Checked\JIT\Methodical\MDArray\DataTypes\bool_cs_do\bool_cs_do.cmd Timed Out
21:16:22         
21:16:22   
21:16:22   Return code:      -100
21:16:22   Raw output file:      D:\j\workspace\x64_checked_w---cae8e941\bin\tests\Windows_NT.x64.Checked\Reports\JIT\Methodical\MDArray\DataTypes\bool_cs_do\bool_cs_do.output.txt
21:16:22   Raw output:
```

**Comment by RussKeldorph** [comment]
Update from @swaroop-sridhar:

The problem here is that duriong StackWalking, we run into an invalid frame.

I now know why this is caused, and it appears to be a GCStress specific issue.

The thread suspension routine introduces a RedirectedThreadFrame into the pFrame chain: 
```C++
Thread::RedirectedHandledJITCase() {

    Frame.push()  // https://github.com/dotnet/coreclr/blob/master/src/vm/threadsuspend.cpp#L4160 

      // Runs GCStress – via background GC
      DoGCStress() // https://github.com/dotnet/coreclr/blob/master/src/vm/threadsuspend.cpp#L4166    

    Frame.pop()  //  https://github.com/dotnet/coreclr/blob/master/src/vm/threadsuspend.cpp#L4272 

}
```
Here’s how the run goes wrong:

* RedirectedHandledJITCase runs on the main thread and spawns off the GC-thread for background GC.
* The background thread captures the frame chain in the crawl-structure
* Main thread is woken up while we’re still in the stack walk (!)
* The redirected-thread chan in popped off
* The GC thread tries to work with the popped-off dangling frame, and will then crash.

**Comment by RussKeldorph** [comment]
#3896 seems to have made this dramatically easier to repro

**Comment by swaroop-sridhar** [comment]
I figured out the problem causing this race.  It’s a bug in the GCStress implementation.

For an inlined PInvoke stub, the JIT generates the following code

```
call    CORINFO_HELP_INIT_PINVOKE_FRAME // Obtain the thread pointer
…
mov      byte  ptr [rsi+12], 0   // Switch to preemptive mode [thread->premptiveGcDisabled = 0]
call     rax                                   // The actual native call, in preemptive mode
mov      byte  ptr [rsi+12], 1    // Switch the thread to Cooperative mode
cmp      dword ptr [(reloc 0x7ffd1bb77148)], 0  // if(g_TrapReturningThreads)
je       SHORT G_M40565_IG05
call     [CORINFO_HELP_STOP_FOR_GC]             // Call RarePremptiveGcDisable()
…
```

When running under GCStress, the GCCoverage code sprinkles breakpoints at safepoints.
It does so at both the above indirect calls, including the call to Stop_For_GC() itself !

So, the code now looks like

```
call    CORINFO_HELP_INIT_PINVOKE_FRAME // Obtain the thread pointer
…
mov      byte  ptr [rsi+12], 0   // Switch to preemptive mode [thread->premptiveGcDisabled = 0]
cli                                               // INTERRUPT_INSTR_CALL
mov      byte  ptr [rsi+12], 1    // Switch the thread to Cooperative mode
cmp      dword ptr [(reloc 0x7ffd1bb77148)], 0  // if(g_TrapReturningThreads)
je       SHORT G_M40565_IG05
cli                                                  // INTERRUPT_INSTR_CALL
…
```

So, in the failing case, the order of events is:
1)	At the first safepoint, we notice that our thread is in preemptive mode during the call for GCStress, and put it in cooperative mode for the purpose of GCStress (fPremptiveGcDisabledForGcStress)
2)	We DoGCStress(). Start-off background GC in a different thread.
3)	Put the thread back to preemptive mode (because that’s where it was). So this thread continues execution along with the GC thread.
4)	The Jitted code puts our thread to cooperative mode, as part of PInvoke epilog
5)	Now instead of StopForGC(), we hit the GCStress trap and start another round of GCStress while in Cooperative mode.
6)	Now, it’s a matter of timing where this thread modifies the stack while the GCStress is scanning it.

A similar sequence of events is possible even without concurrent GC, but the problem is much more likely with backgroundGC.

This problem can be fixed by teaching SprinkleBreakPoints() to recognize indirect calls that call `CORINFO_HELP_STOP_FOR_GC()` and leave them alone.

**Comment by RussKeldorph** [comment]
@swaroop-sridhar Thanks (assuming you're right. :))!
@rahku @adityamandaleeka @gkhanna79 @sergiy-k @jkotas FYI

**Comment by swaroop-sridhar** [comment]
Leaving open until merged to release branch.

**Comment by swaroop-sridhar** [comment]
Fixed by merge https://github.com/dotnet/coreclr/commit/54b743d47fb7be47ead72d1910bd8cb4cfd38e63
