### ISSUE TITLE
UnmanagedMemoryAccessor.ReadArray unavailable from the contract

### ISSUE THREAD

**Issue by am11** [dotnet/coreclr#4799]
The `ReadArray` method can be found in the CoreCLR source [UnmanagedMemoryAccessor.cs#L577-L625](https://github.com/dotnet/coreclr/blob/21f8416/src/mscorlib/src/System/IO/UnmanagedMemoryAccessor.cs#L577-L625), but it does not seem to be exposed to be available in CoreFX [variant](https://github.com/dotnet/corefx/blob/master/src/System.IO.UnmanagedMemoryStream/src/System/IO/UnmanagedMemoryAccessor.cs).

Also, it is missing from the doc: https://dotnet.github.io/api/System.IO.UnmanagedMemoryAccessor.html

Is the usage of `UnmanagedMemoryAccessor.ReadArray` deprecated in favour of some other API in netstandard1.0?
Any recommendations what should we use to efficiently read a chunk of array from the accessor object?

**Comment by thomasnunity3d** [comment]
I've run into this as well, and Read<T> is also missing from the CoreFX version of UnmanagedMemoryAccessor.  Curious as to why, as the underlying SafeBuffer.Read<T> does appear to exist.

**Comment by karelz** [comment]
Seems to be exposed now: https://github.com/dotnet/corefx/blob/1ee59d81e35fb9576ba37d0071388da0d8a6cc5e/src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L60-L61

**Comment by am11** [comment]
Thanks for the heads up @karelz! :)

cc @oschwald.
