### ISSUE TITLE
Bug in multidim array get accessor

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#4805]
From:
http://stackoverflow.com/questions/36588365/why-the-enumeration-value-from-a-multi-dimensional-array-does-not-equal-to-itsel/36633230#36633230

Compile the following /platform:x86 /debug and run the exe.  Should say false, correct response is true.

Source:
using System;

public class Test
{
    enum State : sbyte { OK = 0, BUG = -1 }

    static void Main(string[] args)
    {
        var s = new State[1, 1];
        s[0, 0] = State.BUG;
        State a = s[0, 0];
        Console.WriteLine(a == s[0, 0]); // False
    }
}

**Comment by sergiy-k** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/4808.
