### ISSUE TITLE
NetBSD in 1.0.0-rtm?

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#4824]
The 1.0.0 version is coming pretty close.

Lately I'm being contacted by dozens of .NET and NetBSD users and developers about the port to .NET Core 1.0.0, both privately and in public (like by by @joeduffy on Twitter or @ghuntley on Gitter), with questions about NetBSD unikernels (http://rumpkernel.org/).

I saw news about the NetBSD port and unikernel dreams on Hacker News, Reddit, Phornonix and few other sites. Last I check over 500 people liked or upvoted these news.

I started to work on .NET for NetBSD last year with porting LLDB -- when I got to the point of passing 1/3 debugger tests, I moved on to CoreRT, CoreCLR, CoreFX, llilc etc.

However it's my spare time activity and so with volunteer effort it will unlikely land in the 1.0.0 version and any unikernel activity will remain longer as pipe dreams. Are there team plans to prioritize NetBSD amd64 support for 1.0.0 and help to get official full support for the 1.0.0-rtm version?

CoreCLR passes 100% PAL tests, there are over 90k managed code tests passed on CoreFX. Everything seems to be pretty close, I think the missing parts are:
- fix remaining bugs in managed tests crashing CoreCLR.
- add NetBSD support in ~10 remaining libraries in CoreFX,
- bootstrap CLI.
- finish CoreRT. llilc etc. (I think we just need NetBSD nuget kits here as everything used to be buildable).

After getting there I will work on evbarm (ARM in .NET nomenclature) port for 1.1.0 and then rump unikernel target. The current process of bootstrapping assemblies and tests on Linux is very time-consummating and I can fully understand why the FreeBSD team gave up..

By help I mean to get more people from the .NET domain working on the missing port bits together.

NetBSD unikernels are readily available for languages like Lua, Erlang, Ruby, NodeJS, Python or Rust: https://github.com/rumpkernel/rumprun-packages

A short technical look at this technology is available here: https://www.usenix.org/system/files/login/articles/login_1410_03_kantee.pdf

I was encouraged to ask this question by the C# community excited about unikernels.

**Comment by janvorli** [comment]
CC: @richlander

**Comment by krytarowski** [comment]
I closed this, as 1.0.0 is out.
