### ISSUE TITLE
[ARM/Linux] JIT32_GCENCODER is not switched for _TARGET_ARM_

### ISSUE THREAD

**Issue by papaslavik** [dotnet/coreclr#4825]
There's a naming related question of whether it's good that JIT32_GCENCODER is only defined (and actually supported) for _TARGET_X86_ which, for instance, leads to a call of CodeGen::genCreateAndStoreGCInfoX64 for _TARGET_ARM_ when we try to crossgen-build mscorlib.ni.dll for ARM on Linux.

crossgen mscorlib.ni.dll for ARM eventually crashes with an illegal opcode 
Program received signal SIGILL, Illegal instruction.
0xb6d2abe4 in main_arena () from /lib/arm-linux-gnueabihf/libc.so.6

**Comment by myungjoo** [comment]
The code of crossgen/jit32_gcencoder looks as if ARM-support was dropped in the middle of development. What's the "policy" or "direction" on the development of crossgen? Is it going to be discontinued? (and merged into corert?)

**Comment by papaslavik** [comment]
From some comments in code I got that someone already wondered about CodeGen::genCreateAndStoreGCInfoX64 defined for ARM architecture.

It sounds like it's the portable way.

Also I specially looked through all of the uses of JIT32_GCENCODER and didn't see any 64-bit specific stuff there.

**Comment by papaslavik** [comment]
@myungjoo is there any progress on the mscorlib.ni.dll building for ARM?

According to the crash I saw the last time, it was some stack corruption. I think that it was a stack corruption seems in the crash place it wouldn't show the whole backtrace, but you could walk into the crash place from outside...

**Comment by myungjoo** [comment]
@papaslavik Nope. I have tried juggling around for crossgen and mscorlib.ni.dll. But I do not have any clue yet and I think I'd better get back to coreclr and corefx unit test fail cases.

**Comment by AndyAyersMS** [comment]
I don't think this issue is relevant any more.
