### ISSUE TITLE
ARM64: StackWalk support for FastTailCall

### ISSUE THREAD

**Issue by kyulee1** [dotnet/coreclr#4827]
Need a special handling to detect tail call implemented by epilog + jmp.

category:cq
theme:tail-call
skill-level:expert
cost:medium

**Comment by sdmaclea** [comment]
@janvorli Is this still needed?

**Comment by BruceForstall** [comment]
@janvorli @jashook @adityamandaleeka The JIT has supported fast tailcall on arm64 for a long time, so I'm going to close this. If there still is something needed in the VM in StackWalk, please reopen with details.
