### ISSUE TITLE
JIT32 import libs are incorrect

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#4835]
Standalone JIT32 is linking against VCRuntime140.dll and api-set for uCRT. It should, instead, follow the approach implemented in https://github.com/dotnet/coreclr/commit/7902a3a3eee17378a61ef6817af5e73dc3050cfc#diff-af3b638bc2a3e6c650974192a53c7291 so that we only have runtime dependencies on uCRT for Release build of the JIT and always statically linking the CRT. This enables xcopy distribution of .NET Core simpler.

CC @russellhadley @pgavlin

**Comment by pgavlin** [comment]
This has been fixed in TFS.
