### ISSUE TITLE
Test JIT\IL_Conformance\Old\Conformance_Base\conv_ovf_i8_i fails on x64

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#4850]
Expected: 100
Actual: 0

Prior test harness claimed tests was invalid for 64-bit architectures.  Understand why and either fix the test or disable it only for 64-bit.

**Comment by mikedn** [comment]
Yeah, that test is invalid for 64 bit. It converts `long.MinValue` to `native int` and assumes that an `OverflowException` will be thrown. Of course, that doesn't happen on 64 bit since `native int` is 64 bit and the conversion is a no-op.

Relevant IL code:
```
	ldc.i8			0x8000000000000000
	ldc.i4			0x00000000
	call		int32 conv_ovf_i4::conv(int64,int32)
```

```
.method public static		int32 conv(int64,int32) {
.locals		(class [mscorlib]System.OverflowException, native int)
.maxstack	2
try_start:
	ldarg		0
	conv.ovf.i                        ; no-op for 64 bit
	stloc.1
	leave.s	try_end
try_end:
	ldloc.1                            ; this executes because the expected exception isn't thrown
	ldarg		1
	ceq                                ; compares long.MinValue to 0             
	brfalse			FAIL
```

**Comment by RussKeldorph** [comment]
@mikedn Thanks!  Saved me some time.
