### ISSUE TITLE
JIT\Methodical\varags\seh\fault_il failing

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#4855]
Config: Windows x64 Checked
````
JIT\Methodical\varargs\seh\fault_il_d\fault_il_d.cmd
JIT\Methodical\varargs\seh\fault_il_r\fault_il_r.cmd
```
Output
```
Fault handler.
Fault handler.
vaFault(1) failed.
Expected: 100
Actual: 1
```

**Comment by RussKeldorph** [comment]
Hoping this is a test issue, but not sure.

**Comment by BruceForstall** [comment]
The failure is when the JIT asks the VM to resolve the ArgIterator ctor token.

.NET Core does not support varargs. However, the VM should reject the function, not the JIT (suggested by @jkotas)

Related: #4940

**Comment by BruceForstall** [comment]
I'm going to close this, as #4940 will track it.
