### ISSUE TITLE
Support for IL verification (for debugging frontends)

### ISSUE THREAD

**Issue by DemiMarie** [dotnet/coreclr#4856]
While CoreCLR does not need IL verification for _security_, it would still be helpful for debugging of frontends that produce CIL, since a verification failure is much more helpful than a random segfault or `ExecutionEngineException`.

This does not need to be integrated with the runtime &ndash; it can be a separate library.  However, it would still be nice for it to be available at runtime, so that code that generates CIL can (in debug mode) verify the CIL to check for bugs in the CIL emitter.

**Comment by RussKeldorph** [comment]
See also #295.

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/coreclr/issues/295
