### ISSUE TITLE
How to print JIT statistic?

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/coreclr#487]
There is the `Compiler::compShutdown()` method in `coreclr\src\jit\compiler.cpp`. If some constants are defined (e.g. `DEBUG`, `DISPLAY_SIZES`, `COUNT_LOOPS`, and so on), useful JIT statistic can be printed. For example,

```
    fprintf(fout, "---------------------------------------------------\n");
    fprintf(fout, "Loop stats\n");
    fprintf(fout, "---------------------------------------------------\n");
    fprintf(fout, "Total number of methods with loops is %5u\n",        totalLoopMethods);
    fprintf(fout, "Total number of              loops is %5u\n",        totalLoopCount);
    fprintf(fout, "Maximum number of loops per method is %5u\n",        maxLoopsPerMethod);
    fprintf(fout, "# of methods overflowing nat loop table is %5u\n",   totalLoopOverflows);
    fprintf(fout, "Total number of 'unnatural' loops is %5u\n",         totalUnnatLoopCount);
    fprintf(fout, "# of methods overflowing unnat loop limit is %5u\n", totalUnnatLoopOverflows);
    fprintf(fout, "Total number of loops with an         iterator is %5u\n", iterLoopCount);
    fprintf(fout, "Total number of loops with a simple   iterator is %5u\n", simpleTestLoopCount);
    fprintf(fout, "Total number of loops with a constant iterator is %5u\n", constIterLoopCount);
```

How I can activate this feature?

**Comment by BruceForstall** [comment]
It varies. First, make sure they are compiled in (e.g., under #ifdef DEBUG, and you are running a debug build). Some are not undef #ifdef DEBUG. For non-debug build, or those not under #ifdef DEBUG, you need to change jit.h to redefine COUNT_LOOPS or MEASURE_INLINING, or one of those, and rebuild.

For COUNT_LOOPS, and many of them, it will always print when the process exits. For some, you might need to set a COMPLUS_xxx style environment variable.

**Comment by cmckinsey** [comment]
You can change the CMakeLists.txt to have something like

add_definitions(-DCOUNT_LOOPS)

or edit the jit.h directly.

Matt Mitchell has opened #489 to add support to the build system to allow overriding defines on the build line.

**Comment by AndreyAkinshin** [comment]
@BruceForstall,
> it will always print when the process exits

I have rebuilt CoreCLR in Debug mode with `COUNT_LOOPS` and `MEASURE_INLINING`, but I don't have such output. Maybe I should do something in addition or run my program special way for showing the JIT statistic output?

> For some, you might need to set a COMPLUS_xxx style environment variable.

Where I can read more about these variables?

@BruceForstall, @cmckinsey, Can you provide some full instruction example for printing JIT statistic? I think, such example will be very useful for other developers. It can help to understand how JIT works.

**Comment by mikedn** [comment]
It seems to me that there is some conflicting information. COUNT_LOOPS cannot be specified on the compiler command line because jit.h contains `#define COUNT_LOOPS 0`. That means that the only way to achieve this is to modify jit.h, modifying CMakeLists.txt won't help.

**Comment by AndreyAkinshin** [comment]
@mikedn, thanks! Now I did it! Indeed, I can't print JIT statistics with help of cmake, only `jit.h` editing helps me.

**Comment by BruceForstall** [comment]
Regarding:

> Where I can read more about these variables?

I couldn't find any documentation about this on GitHub... yet.

Very short explanation: check out clrconfigvalues.h. Most of those can be used by setting COMPLUS_var=foo for some "var" mentioned in the file, and "foo" being either a string or integer, depending on the variable. E.g., COMPLUS_JitDump=* is very useful for debugging the JIT.

**Comment by MattWhilden** [comment]
Hey @AndreyAkinshin, this seems to have been resolved-ish. Is there any more follow up here?

**Comment by AndreyAkinshin** [comment]
No, thank you.
