### ISSUE TITLE
JIT32 is failing with assert in master

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#4876]
JIT32 fails with the following assert in master branch when generating NI image:

c:\Github\gkhanna79\coreclr\bin\Product\Windows_NT.x86.Debug>crossgen.exe mscorlib.dll
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assert failure(PID 28796 [0x0000707c], Thread: 28140 [0x6dec]): THE_ALLOCATOR_BASE_SIZE != 0
    File: c:\github\gkhanna79\coreclr\src\jit32\alloc.cpp Line: 61
    Image: c:\Github\gkhanna79\coreclr\bin\Product\Windows_NT.x86.Debug\crossgen.exe

**Comment by gkhanna79** [comment]
@russellhadley @pgavlin Is this a known issue?

**Comment by pgavlin** [comment]
Yes, this is related to the https://github.com/dotnet/coreclr/issues/4785. The necessary fix was merged into TFS this morning.

**Comment by pgavlin** [comment]
I've verified that this does not repro with the latest changes in TFS and GitHub.
