### ISSUE TITLE
Arm64: SP, Fp is trashed in CallDescrWorkerInternal

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#4879]
EPILOG_RESTORE_REG      x19, #16    ;the stack slot at sp+24 is empty for 16 byte alligment
ldr         x19,[sp,#0x10]

System.Numerics.Vectors.Tests.dll

**Comment by rahku** [comment]
codegen for the bleow method is incorrect. Saved FP on the stack is overwritten in the method body. Look for **** in below codegen

0:000> !u 00007ffe`247937b0
Normal JIT generated code
System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateConstrainedBillboardAlongAxisTest3()
Begin 00007ffe247937b0, size 228

D:\corefxGit\corefx\src\System.Numerics.Vectors\tests\Matrix4x4Tests.cs @ 2086:
00007ffe`247937b0 d10dc3ff sub         sp,sp,#0x370
00007ffe`247937b4 a901fbfd stp         fp,lr,[sp,#0x18] ***********FP saved at sp+0x18
00007ffe`247937b8 910063fd add         fp,sp,#0x18
00007ffe`247937bc 910283a1 add         x1,fp,#0xA0
00007ffe`247937c0 d2800562 mov         x2,#0x2B
00007ffe`247937c4 a8817c3f stp         xzr,xzr,[x1],#0x10
00007ffe`247937c8 f1000442 subs        x2,x2,#1
00007ffe`247937cc 54ffffc8 bhi         System_Numerics_Vectors_Tests!System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateConstrainedBillboardAlongAxisTest3()+0x14 (00007ffe`247937c4)
00007ffe`247937d0 f900003f str         xzr,[x1]
00007ffe`247937d4 f9000fa0 str         x0,[fp,#0x18]

D:\corefxGit\corefx\src\System.Numerics.Vectors\tests\Matrix4x4Tests.cs @ 2088:
00007ffe`247937d8 d503201f nop
00007ffe`247937dc 910d23a0 add         x0,fp,#0x348
00007ffe`247937e0 1e211000 fmov        s0,#3
00007ffe`247937e4 1e221001 fmov        s1,#4
00007ffe`247937e8 1e229002 fmov        s2,#5

D:\corefxGit\corefx\src\System.Numerics.Vectors\tests\Matrix4x4Tests.cs @ 2089:
00007ffe`247937ec 97cd9445 bl          system_numerics_vectors!System.Numerics.Vector3..ctor(Single, Single, Single) (00007ffe`23af8900)
00007ffe`247937f0 910ce3a0 add         x0,fp,#0x338
00007ffe`247937f4 4f00e400 movi        v0.16b,#0
00007ffe`247937f8 1e2e1001 fmov        s1,#1
00007ffe`247937fc 4f00e402 movi        v2.16b,#0

D:\corefxGit\corefx\src\System.Numerics.Vectors\tests\Matrix4x4Tests.cs @ 2090:
00007ffe`24793800 97cd9440 bl          system_numerics_vectors!System.Numerics.Vector3..ctor(Single, Single, Single) (00007ffe`23af8900)
00007ffe`24793804 910d23a1 add         x1,fp,#0x348
00007ffe`24793808 910a63a0 add         x0,fp,#0x298
00007ffe`2479380c 52800182 mov         w2,#0xC
00007ffe`24793810 97af3f16 bl          CORINFO_HELP_MEMCPY (00007ffe`23363468)
00007ffe`24793814 f9419fa1 ldr         x1,[fp,#0x338]
00007ffe`24793818 f941a3a2 ldr         x2,[fp,#0x340]
00007ffe`2479381c 910a23a0 add         x0,fp,#0x288
00007ffe`24793820 1e249000 fmov        s0,#10
00007ffe`24793824 97cd8d5d bl          System.Numerics.Vector3.op_Multiply(System.Numerics.Vector3, Single) (00007ffe`23af6d98)
00007ffe`24793828 f9414fa1 ldr         x1,[fp,#0x298]
00007ffe`2479382c f94153a2 ldr         x2,[fp,#0x2A0]
00007ffe`24793830 f94147a3 ldr         x3,[fp,#0x288]
00007ffe`24793834 f9414ba4 ldr         x4,[fp,#0x290]
00007ffe`24793838 9109e3a0 add         x0,fp,#0x278
00007ffe`2479383c 97cd8d3f bl          System.Numerics.Vector3.op_Addition(System.Numerics.Vector3, System.Numerics.Vector3) (00007ffe`23af6d38)
00007ffe`24793840 9109e3a1 add         x1,fp,#0x278
00007ffe`24793844 910ca3a0 add         x0,fp,#0x328
00007ffe`24793848 52800182 mov         w2,#0xC

D:\corefxGit\corefx\src\System.Numerics.Vectors\tests\Matrix4x4Tests.cs @ 2093:
00007ffe`2479384c 97af3f07 bl          CORINFO_HELP_MEMCPY (00007ffe`23363468)
00007ffe`24793850 1c000c40 ldr         s0,System_Numerics_Vectors_Tests!System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateConstrainedBillboardAlongAxisTest3()+0x228 (00007ffe`247939d8)
00007ffe`24793854 97cdb5d7 bl          System_Numerics_Vectors_Tests!System.Numerics.MathHelper.ToRadians(Single) (00007ffe`23b00fb0)
00007ffe`24793858 bd0277a0 str         s0,[fp,#0x274]
00007ffe`2479385c 9108c3a0 add         x0,fp,#0x230
00007ffe`24793860 d2804e91 mov         xip1,#0x274
00007ffe`24793864 fc716ba0 ldr         d0,[fp,xip1]
00007ffe`24793868 97cdb61e bl          system_numerics_vectors!System.Numerics.Matrix4x4.CreateRotationY(Single) (00007ffe`23b010e0)
00007ffe`2479386c f941a7a1 ldr         x1,[fp,#0x348]
00007ffe`24793870 f941aba2 ldr         x2,[fp,#0x350]
00007ffe`24793874 9107c3a0 add         x0,fp,#0x1F0
00007ffe`24793878 97cdb45c bl          System.Numerics.Matrix4x4.CreateTranslation(System.Numerics.Vector3) (00007ffe`23b009e8)
00007ffe`2479387c 9106c3a2 add         x2,fp,#0x1B0
00007ffe`24793880 f90053a2 str         x2,[fp,#0xA0]
00007ffe`24793884 9108c3a1 add         x1,fp,#0x230
00007ffe`24793888 9103a3a0 add         x0,fp,#0xE8
00007ffe`2479388c 52800802 mov         w2,#0x40
00007ffe`24793890 97af3ef6 bl          CORINFO_HELP_MEMCPY (00007ffe`23363468)
00007ffe`24793894 9107c3a1 add         x1,fp,#0x1F0
00007ffe`24793898 9102a3a0 add         x0,fp,#0xA8
00007ffe`2479389c 52800802 mov         w2,#0x40
00007ffe`247938a0 97af3ef2 bl          CORINFO_HELP_MEMCPY (00007ffe`23363468)
00007ffe`247938a4 f94053a0 ldr         x0,[fp,#0xA0]
00007ffe`247938a8 9103a3a1 add         x1,fp,#0xE8
00007ffe`247938ac 9102a3a2 add         x2,fp,#0xA8
00007ffe`247938b0 97cdb642 bl          system_numerics_vectors!System.Numerics.Matrix4x4.op_Multiply(System.Numerics.Matrix4x4, System.Numerics.Matrix4x4) (00007ffe`23b011b8)
00007ffe`247938b4 9106c3a1 add         x1,fp,#0x1B0
00007ffe`247938b8 910ba3a0 add         x0,fp,#0x2E8
00007ffe`247938bc 52800802 mov         w2,#0x40

D:\corefxGit\corefx\src\System.Numerics.Vectors\tests\Matrix4x4Tests.cs @ 2094:
00007ffe`247938c0 97af3eea bl          CORINFO_HELP_MEMCPY (00007ffe`23363468)
00007ffe`247938c4 52800001 mov         w1,#0
00007ffe`247938c8 910683a0 add         x0,fp,#0x1A0
00007ffe`247938cc 52800182 mov         w2,#0xC
00007ffe`247938d0 97af3ee2 bl          CORINFO_HELP_MEMSET (00007ffe`23363458)
00007ffe`247938d4 910d23a1 add         x1,fp,#0x348
00007ffe`247938d8 910643a0 add         x0,fp,#0x190
00007ffe`247938dc 52800182 mov         w2,#0xC
00007ffe`247938e0 97af3ee2 bl          CORINFO_HELP_MEMCPY (00007ffe`23363468)
00007ffe`247938e4 910ce3a1 add         x1,fp,#0x338
00007ffe`247938e8 910603a0 add         x0,fp,#0x180
00007ffe`247938ec 52800182 mov         w2,#0xC
00007ffe`247938f0 97af3ede bl          CORINFO_HELP_MEMCPY (00007ffe`23363468)
00007ffe`247938f4 910683a0 add         x0,fp,#0x1A0
00007ffe`247938f8 1e3e1002 fmov        s2,#-1
00007ffe`247938fc 4f00e401 movi        v1.16b,#0
00007ffe`24793900 4f00e400 movi        v0.16b,#0
00007ffe`24793904 97cd93ff bl          system_numerics_vectors!System.Numerics.Vector3..ctor(Single, Single, Single) (00007ffe`23af8900)
00007ffe`24793908 52800001 mov         w1,#0
00007ffe`2479390c 9105c3a0 add         x0,fp,#0x170
00007ffe`24793910 52800182 mov         w2,#0xC
00007ffe`24793914 97af3ed1 bl          CORINFO_HELP_MEMSET (00007ffe`23363458)
00007ffe`24793918 9105c3a0 add         x0,fp,#0x170
00007ffe`2479391c 1e3e1002 fmov        s2,#-1
00007ffe`24793920 4f00e401 movi        v1.16b,#0
00007ffe`24793924 4f00e400 movi        v0.16b,#0
00007ffe`24793928 97cd93f6 bl          system_numerics_vectors!System.Numerics.Vector3..ctor(Single, Single, Single) (00007ffe`23af8900)
00007ffe`2479392c f940d3a1 ldr         x1,[fp,#0x1A0]
00007ffe`24793930 f940d7a2 ldr         x2,[fp,#0x1A8]
00007ffe`24793934 f90003e1 str         x1,[sp]
00007ffe`24793938 f90007e2 str         x2,[sp,#8]
00007ffe`2479393c f940bba1 ldr         x1,[fp,#0x170]
00007ffe`24793940 f940bfa2 ldr         x2,[fp,#0x178]
00007ffe`24793944 f9000be1 str         x1,[sp,#0x10]
*********BUG***************************BUG ******************************************************************
00007ffe`24793948 f9000fe2 str         x2,[sp,#0x18]    *******************Bug overwrites saved FP*****************************************************************************************************
00007ffe`2479394c f940cba1 ldr         x1,[fp,#0x190]
00007ffe`24793950 f940cfa2 ldr         x2,[fp,#0x198]
00007ffe`24793954 f94197a3 ldr         x3,[fp,#0x328]
00007ffe`24793958 f9419ba4 ldr         x4,[fp,#0x330]
00007ffe`2479395c f940c3a5 ldr         x5,[fp,#0x180]
00007ffe`24793960 f940c7a6 ldr         x6,[fp,#0x188]
00007ffe`24793964 9104c3a0 add         x0,fp,#0x130
00007ffe`24793968 97cdb418 bl          System.Numerics.Matrix4x4.CreateConstrainedBillboard(System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3) (00007ffe`23b009c8)
00007ffe`2479396c 9104c3a1 add         x1,fp,#0x130
00007ffe`24793970 910aa3a0 add         x0,fp,#0x2A8
00007ffe`24793974 52800802 mov         w2,#0x40

D:\corefxGit\corefx\src\System.Numerics.Vectors\tests\Matrix4x4Tests.cs @ 2095:
00007ffe`24793978 97af3ebc bl          CORINFO_HELP_MEMCPY (00007ffe`23363468)
00007ffe`2479397c 910ba3a1 add         x1,fp,#0x2E8
00007ffe`24793980 910183a0 add         x0,fp,#0x60
00007ffe`24793984 52800802 mov         w2,#0x40
00007ffe`24793988 97af3eb8 bl          CORINFO_HELP_MEMCPY (00007ffe`23363468)
00007ffe`2479398c 910aa3a1 add         x1,fp,#0x2A8
00007ffe`24793990 910083a0 add         x0,fp,#0x20
00007ffe`24793994 52800802 mov         w2,#0x40
00007ffe`24793998 97af3eb4 bl          CORINFO_HELP_MEMCPY (00007ffe`23363468)
00007ffe`2479399c 910183a0 add         x0,fp,#0x60
00007ffe`247939a0 910083a1 add         x1,fp,#0x20
00007ffe`247939a4 97ffdb3d bl          System_Numerics_Vectors_Tests!System.Numerics.MathHelper.Equal(System.Numerics.Matrix4x4, System.Numerics.Matrix4x4) (00007ffe`2478a698)
00007ffe`247939a8 b9012fa0 str         w0,[fp,#0x12C]
00007ffe`247939ac d295f801 mov         x1,#0xAFC0
00007ffe`247939b0 f2b420a1 movk        x1,#0xA105 lsl #0x10
00007ffe`247939b4 f2c05081 movk        x1,#0x284 lsl #0x20
00007ffe`247939b8 f9400021 ldr         x1,[x1]
00007ffe`247939bc b9812fa0 ldrsw       x0,[fp,#0x12C]
00007ffe`247939c0 97cd9412 bl          xunit_assert!Xunit.Assert.True(Boolean, System.String) (00007ffe`23af8a08)

D:\corefxGit\corefx\src\System.Numerics.Vectors\tests\Matrix4x4Tests.cs @ 2096:
00007ffe`247939c4 d503201f nop
00007ffe`247939c8 d503201f nop
00007ffe`247939cc a941fbfd ldp         fp,lr,[sp,#0x18]
00007ffe`247939d0 910dc3ff add         sp,sp,#0x370
00007ffe`247939d4 d65f03c0 ret         lr

**Comment by rahku** [comment]
CC: @gkhanna79 @briansull

**Comment by briansull** [comment]
I believe that I have discovered this issue and I have a fix for it 
I discovered it during my HFA argument passing work.

**Comment by kyulee1** [comment]
I'd like to understand the issue. How to repro this?

**Comment by rahku** [comment]
See instructions on arm64 one note on how to run corefx tests. The steps were added by @ramarag

**Comment by kyulee1** [comment]
System.Numerics.Vectors.Tests are all passed  (1062 tests). I believe this is due to Brian's HFA argument work.
I validated the assembly looks reasonable. So I close this issue.
