### ISSUE TITLE
Undefined symbols in Mac Release build

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#488]
Undefined symbols for architecture x86_64:
  "int ValueNumStore::CoerceTypRefToT<int>(ValueNumStore::Chunk*, unsigned int)", referenced from:
      RangeCheck::MergeEdgeAssertions(GenTree*, unsigned long, Range*) in libClrJit.a(rangecheck.cpp.o)
      RangeCheck::GetLimitMax(Limit&, int*) in libClrJit.a(rangecheck.cpp.o)
      RangeCheck::ComputeRange(BasicBlock*, GenTree*, GenTree*, SimplerHashTable<GenTree*, PtrKeyFuncs<GenTree>, BasicBlock*, DefaultSimplerHashBehavior>*, bool) in libClrJit.a(rangecheck.cpp.o)
      Compiler::optIsTreeKnownIntValue(bool, GenTree*, long*, unsigned int*) in libClrJit.a(assertionprop.cpp.o)
      Compiler::optVnConstantAssertionProp(GenTree*, GenTree*) in libClrJit.a(assertionprop.cpp.o)
      Compiler::optAssertionPropGlobal_RelOp(unsigned long, GenTree*, GenTree*) in libClrJit.a(assertionprop.cpp.o)
      Compiler::optAssertionProp_BndsChk(unsigned long, GenTree*, GenTree*) in libClrJit.a(assertionprop.cpp.o)
      ...
  "long ValueNumStore::CoerceTypRefToT<long>(ValueNumStore::Chunk*, unsigned int)", referenced from:
      GenTree::IsFieldAddr(Compiler*, GenTree**, GenTree**, FieldSeqNode**) in libClrJit.a(gentree.cpp.o)
      Compiler::optIsTreeKnownIntValue(bool, GenTree*, long*, unsigned int*) in libClrJit.a(assertionprop.cpp.o)
      Compiler::optVnConstantAssertionProp(GenTree*, GenTree*) in libClrJit.a(assertionprop.cpp.o)
      Compiler::optAssertionPropGlobal_RelOp(unsigned long, GenTree*, GenTree*) in libClrJit.a(assertionprop.cpp.o)
      Compiler::optVNIsLoopInvariant(unsigned int, unsigned int, SimplerHashTable<unsigned int, SmallPrimitiveKeyFuncs<unsigned int>, bool, DefaultSimplerHashBehavior>*) in libClrJit.a(optimizer.cpp.o)
  "unsigned long ValueNumStore::CoerceTypRefToT<unsigned long>(ValueNumStore::Chunk*, unsigned int)", referenced from:
      Compiler::optAssertionPropGlobal_RelOp(unsigned long, GenTree*, GenTree*) in libClrJit.a(assertionprop.cpp.o)
      Compiler::optComputeLoopSideEffectsOfBlock(BasicBlock*) in libClrJit.a(optimizer.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/dlls/mscoree/coreclr/libcoreclr.dylib] Error 1
make[1]: *** [src/dlls/mscoree/coreclr/CMakeFiles/coreclr.dir/all] Error 2

**Comment by jkotas** [comment]
Fixed by #491
