### ISSUE TITLE
Uncaught exceptions cause an access violation under the CoreCLR debugger

### ISSUE THREAD

**Issue by barrytang** [dotnet/coreclr#4892]
I've noticed this in a variety of contexts, but it is very easy to get a simple repro:

````CSharp
namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            throw new System.Exception();
        }
    }
}
````

When running under the VS debugger, it is expected that the debugger will halt at this first line and show information about the exception. Instead, when using the CoreCLR debugger, an access violation appears to occur, and the debugger terminates, along with the debugged program. This works as expected with the full framework debugger. Under CoreCLR, this message appears in the Debug log:

````
Exception thrown: 'System.Exception' in ConsoleApp4.dll
The program '[14340] dotnet.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.
````

This does not only occur in the simple example above. I see it in any place where an uncaught exception occurs.

Version Info:
Microsoft .NET Core Tools (Preview 1) 14.1.20504.0

**Comment by barrytang** [comment]
Opened on behavior of @mellinoe

**Comment by gkhanna79** [comment]
@mikem8361This sounds like the issue you have been investigating recently.

CC  @noahfalk @tzwlai

**Comment by tzwlai** [comment]
You can work around this by going to "Tools" -> "Options" -> "Debugging" -> "General" and disabling the checkbox for "Unwind the call stack on unhandled exceptions".  

We'll address this in the RTM timeframe.

**Comment by mikem8361** [comment]
/cc @tzwlai, @gregg-miskelly

I can repro the problem with the RC2 version 1.0.0.2702 of .NET Core but if use a newer version (1.0.0.2959_ the bug does NOT repro anymore. I'm using "Tooling Preview 1" version 1.0.20526.21 of the VS package.

The project.json that repo's the problem:
```
{
    "version": "1.0.0-*",
    "buildOptions": {
        "emitEntryPoint": true,
        "defines": [ "DEBUG" ]
    },
    "dependencies": {
        "Microsoft.NETCore.App": {
            "type": "platform",
            "version": "1.0.0-rc2-3002702"
        }
    },
    "frameworks": {
        "netcoreapp1.0": {
            "imports": "dnxcore50"
        }
    }
}
```
The project.json that works:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc3-004373"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by mikem8361** [comment]
Closing this issue as not repro.
