### ISSUE TITLE
Can't built, it turns out 'warning C4819'

### ISSUE THREAD

**Issue by actboy168** [dotnet/coreclr#49]
```
1>e:\work\coreclr-master\src\vm\generics.h : error C2220: 警告被视为错误 - 没有生成“object”文件 (E:\work\coreclr-master\src\debug\ee\debuggermodule.cpp)
1>e:\work\coreclr-master\src\vm\generics.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 (E:\work\coreclr-master\src\debug\ee\debuggermodule.cpp)
```

**Comment by mmdriley** [comment]
src\vm\generics.h has [a § symbol at line 29](https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/vm/generics.h#L29). In the file it's encoded as 0xA7, which is valid in [CP1251](https://msdn.microsoft.com/en-US/goglobal/cc305144) but is a lead byte in [CP936](https://msdn.microsoft.com/en-US/goglobal/cc305153).

**Comment by ellismg** [comment]
Thanks @mmdriley.  Looking over the files, it seems we unfortunately use CP1252 all over the place in our native files.  The managed ones look like they are pretty good about using UTF-8 either with or without a byte order marker.

I'll do a pass and try to clean this up and see if this fixes @actboy168's issue.

**Comment by ellismg** [comment]
@actboy168 can you grab [ellismg:clean-unicode-characters](https://github.com/ellismg/coreclr/tree/clean-unicode-characters) and see if that fixes your problem?  I'm having a bit of trouble getting my local machine in a state where I can reproduce your issue, so I can't verify it myself.

**Comment by ellismg** [comment]
@actboy168 Nevermind, I was finally able to reproduce the issue locally, so I can verify my fix.

**Comment by anydream** [comment]
@ellismg 
'clean-unicode-characters' branch solved code page problems, but new error occurs:

       “D:\proj\coreclr-u\binaries\CMake\install.vcxproj”(rebuild target) (1) ->

       “D:\proj\coreclr-u\binaries\CMake\ALL_BUILD.vcxproj”(default target) (2:2) ->

       “D:\proj\coreclr-u\binaries\CMake\src\vm\wks\cee_wks.vcxproj”(default target)
 (4:3
       ) ->
       (PreBuildEvent target) ->
         D:/proj/coreclr-u/binaries/CMake/src/vm/wks/AsmConstants.tmp(118): fat
       al error C1012: 不匹配的括号 unmatched parenthesis : missing “)” [D:\proj\coreclr-u\binaries\CMak
e\src\vm\
       wks\cee_wks.vcxproj]

**Comment by ellismg** [comment]
@anydream Thanks for the heads up.  Can you share out the entire AsmConstants.tmp file either in a gist or e-mail it to me (my e-mail address is in my profile).

What is your system locale set to?  I had mine set to Chinese (Simplified) and I wasn't hitting this, but it's possible that my settings weren't influencing powershell which runs the script that generates this file.

**Comment by anydream** [comment]
Yes, my locale is Chinese (Simplified) CP936, the generated file AsmConstants.tmp was e-mail to you.

**Comment by anydream** [comment]
Aha, I know why occurs this error...
Because my console width is set to 80 characters..
![default](https://cloud.githubusercontent.com/assets/3724537/6036862/dacf53a2-ac86-11e4-8d9c-79ebbe658755.png)

**Comment by ellismg** [comment]
@anydream Intersesting.  My console is also set to 80 characters, but I'm not seeing an issue.  I think something might have changed between powershell versions to make the default host have a larger width for it's internal buffer.

What version of Windows are you running?  7?

**Comment by anydream** [comment]
I am now using Windows 7 Ultimate SP1.
Change the console width was resolved that problem and now I have successfully built CoreCLR :)
Perhaps that is because of the different locale strategies of cmd.exe?

**Comment by ellismg** [comment]
Not sure.  I'm glad you're unblocked for now.  I'm going to spin up a Windows 7 VM locally and figure out how to repro the issue and then squash the bug.  Thanks very much for your help here, I really appreciate it!

**Comment by OtherCrashOverride** [comment]
I am also seeing the issue with AsmConstants.tmp.  It occurs for me on Windows 7.

**Comment by anydream** [comment]
Correction: set up console default 'buffer width' value can solve that problem

**Comment by OtherCrashOverride** [comment]
I set a console width of 132; however, I encounter other error(s) attempting to build.

Abridged output:
      (PreBuildEvent target) ->
        coreclr-master/binaries/CMake/src/vm/wks/AsmConstants.tmp(193): fatal error C1017:
       invalid integer constant expression [coreclr-master\binaries\CMake\src\vm\wks\cee_w
      ks.vcxproj]
        C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(122,5): error MSB3073: The command "set
      local\r [coreclr-master\coreclr-master\binaries\CMake\src\vm\wks\cee_wks.vcxproj]

**Comment by ellismg** [comment]
@OtherCrashOverride Can you please share out a gist of the generated AsmConstants.tmp file?

**Comment by anydream** [comment]
@OtherCrashOverride I set console 'buffer width' to 300 then it works

**Comment by OtherCrashOverride** [comment]
https://gist.github.com/OtherCrashOverride/1b3c1c2011a8143873af

**Comment by OtherCrashOverride** [comment]
Trying again with a console width of 300.

**Comment by anydream** [comment]
@OtherCrashOverride at line 192 of your code, the maximum character length is 131....so you need larger width value

**Comment by ellismg** [comment]
I believe that [ellismg:fix-h2inc-line-wrapping](https://github.com/ellismg/coreclr/tree/fix-h2inc-line-wrapping) addresses this issue, independent of what your console settings are.  This was a problem with Windows 7 regardless of locale (I could reproduce the hard wrapping behavior on an en-US Windows 7 VM).

I verified that that the generated file is not wrapped, but I haven't completed a build.  @anydream or @OtherCrashOverride can you give it a whirl (you'll need the other fix as well, to address the Unicode issues).

**Comment by actboy168** [comment]
@ellismg 
Yes, It's fixed.
Thanks very much for your help.

**Comment by OtherCrashOverride** [comment]
Confirmed that changing the console width to 300 allows the build to succeed.

Very impressive terminals at Microsoft ;)

**Comment by OtherCrashOverride** [comment]
Testing patch.

**Comment by OtherCrashOverride** [comment]
Build with patch in a 80x25 console succeeded.

**Comment by ellismg** [comment]
@OtherCrashOverride Thanks!

**Comment by anydream** [comment]
@ellismg Yes it works :+1:

**Comment by Janiels** [comment]
That patch fixes the issue for me as well.
