### ISSUE TITLE
VM should reject any function with varargs

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4940]
varargs are not supported on .NET Core. However, today, the VM lets varargs functions through to the JIT at least on Windows. Later, the JIT fails if it happens to call the ArgIterator ctor.

Instead, the VM should immediately reject any app with a function with varargs, and not leave it to the JIT.

Related: #4855.

**Comment by RussKeldorph** [comment]
As part of this work, please delete any and all tests currently using vararg, arglist, ArgIterator, etc. (whether or not they are currently disabled), except that I recommend retaining or creating tests that explicitly check that such features are categorically rejected.

**Comment by gkhanna79** [comment]
@jkotas Is this a blanket rejection of methods containing varargs or will we support them for forward pinvoke?

**Comment by jkotas** [comment]
Our own corefx is calling printf vararg methods without the special PInvoke support, e.g.: https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/Common/src/Interop/Unix/System.Native/Interop.PrintF.cs#L12. I think that we should start by rejecting them wholesale - we can relax it later.

@yizhang82 Do you have anything to add about vararg support in forward PInvoke?

**Comment by gkhanna79** [comment]
@stephentoub @weshaggard - FYI

**Comment by stephentoub** [comment]
> Our own corefx is calling printf vararg methods without the special PInvoke support

@jkotas, what do you recommend we do here instead?  Use __arglist?  Expose multiple exports from the native shim, one for each needed set of args?

**Comment by stephentoub** [comment]
FWIW, I've found it incredibly helpful while debugging to be able to quickly add:
```C#
[DllImport("libc")] // or "msvcrt" on Windows
private static extern int printf(string format, string arg);
```
to some code I'm working on in order to be able to literally do printf debugging.

**Comment by jkotas** [comment]
@stephentoub The current corefx wrapper for `printf` should be just fine.

This issue is about `__arglist`.

**Comment by stephentoub** [comment]
Ah, ok, I misunderstood the comments then; I thought the implication was that the current code was bad.

**Comment by yizhang82** [comment]
@jkotas Thanks for letting me know. I'm fine with not supporting it for .NET Core for RTM. Personally I've never had the need to use vararg interop. 
@BruceForstall Just curious, I'm assuming we are talking about RyuJIT here - have vararg always been missing in RyuJIT - that seems unlikely to me. Is this related to x-plat?

**Comment by BruceForstall** [comment]
@yizhang82 No, this is not RyuJIT. This is for .NET Core overall, as a feature choice. RyuJIT for Windows does support varargs. We haven't implemented it for non-Windows because there was a feature choice made earlier to not support it on .NET Core. This issue is just to properly, early, bail out if it is seen in the IL.

**Comment by yizhang82** [comment]
@BruceForstall I see. So this is simply scoping for .Net Core x-plat. Thanks!

**Comment by drbo** [comment]
What was the reason to not support it in .NET Core?

**Comment by gkhanna79** [comment]
It is not consistently implemented (see discussion above). To ensure that code works consistently across platforms, this is required. 

We could, in future, consider enabling it uniformly.

**Comment by gkhanna79** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/5075

**Comment by gkhanna79** [comment]
Reopening to look into this further.

**Comment by gkhanna79** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/5124
