### ISSUE TITLE
Mscorlib failing to build in some tests

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#4960]
Getting the following in http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1_prtest/1928/

error CS1719: Error opening Win32 resource file 'D:\j\workspace\x86_ryujit_ch---7ecedcb1\bin\obj/\Windows_NT.x86.Checked\/Native.res' -- 'The process cannot access the file 'D:\j\workspace\x86_ryujit_ch---7ecedcb1\bin\obj\Windows_NT.x86.Checked\Native.res' because it is being used by another process.' [D:\j\workspace\x86_ryujit_ch---7ecedcb1\src\mscorlib\System.Private.CoreLib.csproj]
Indication 1 

This is usually an indication that certain msbuild properties are not being cleared/set properly in Project Reference dependencies, and a project is erroneously being built twice.

/cc @RussKeldorph @weshaggard @gkhanna79

**Comment by gkhanna79** [comment]
@joperezr Can you PTAL?

CC @weshaggard

**Comment by weshaggard** [comment]
@AlexGhiondea This is likely because System.Private.CoreLib is building the same files in the same location.
