### ISSUE TITLE
Add package authoring for openSUSE 13.2

### ISSUE THREAD

**Issue by joshfree** [dotnet/coreclr#5018]
Tracking issue for /dotnet/coreclr repo package authoring changes.

Related tracking issues for corefx and cli repos
* https://github.com/dotnet/corefx/issues/8584
* https://github.com/dotnet/cli/issues/3054

/cc @ellismg @gkhanna79

**Comment by gkhanna79** [comment]
https://github.com/dotnet/coreclr/issues/4987 is the issue for Fedora 23 and Ubuntu 16.04

**Comment by gkhanna79** [comment]
@ellismg Please note that src\.nuget (where you will add definitions for these platforms) builds both JIT and CoreCLR packages and they both need to be updated.

CC @pgavlin @russellhadley

**Comment by ellismg** [comment]
This is done now (and also in 1.0.0/release)
