### ISSUE TITLE
Porting Diagnostic Tests

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#5029]
We have a variety of test assets for ICorDebug, SOS, and ICorProfiler APIs that have not yet been made available as OSS. Our current plan to try placing these assets in a seperate github repo so they can be easily reused by a variety of different projects (coreclr would be one of them, corert would be another)
- [x] [Port] MDbg and MDbg based test scripts for validating ICorDebug APIs
- [x] [Port] SOS test runner and SOS test scripts
- [x] [Port] ICorProfiler tests

**Comment by noahfalk** [comment]
@mikem8361 @kspawa

**Comment by mikem8361** [comment]
I think we have done all of the above items.  More tests can be added in the future but I think there are enough of all three categories now to close this issue.
