### ISSUE TITLE
Case-sensitive issue in Linux

### ISSUE THREAD

**Issue by jyoungyun** [dotnet/coreclr#5035]
In Linux, it seems that csc does not find exisiting file by case-sensitive issue.

```
CSC : error CS2001: Source file '/home/jyoung/git/dotnet/coreclr_buildtestsh/tests/src/Interop/MarshalAPI/Miscellaneous/../../Common/Assertion.cs' could not be found.
```
```
~/git/dotnet/coreclr_buildtestsh$ vi tests/src/Interop/common/
Assertion.cs  types.h       xplatform.h 
```
```
 30   <ItemGroup>                                                                   
 31     <Compile Include="AutoLayoutStructure.cs" />                                
 32     <Compile Include="..\..\Common\Assertion.cs" />                             
 33   </ItemGroup> 
```
As per MSBuild guideline, the element and attribute names are case-sensitive but the others like property, item, and metadata name are not.
(MSBuild guideline: https://msdn.microsoft.com/en-us/library/dd393574.aspx)

The same code was built successfully in Windows.

**Comment by stephentoub** [comment]
@jyoungyun, are you referring to the file paths themselves? Those are expected to be case-sensitive on Linux, as are file paths in general.

**Comment by jyoungyun** [comment]
@stephentoub No, this is the original CoreCLR test codes. There are a lot of code which is case-insensitive matching in tests directory. Thanks for comments! I will post a PR soon.

**Comment by stephentoub** [comment]
Ah, I think I misunderstood your comments. I thought you were saying that you were expecting MSBuild to always treat paths as case-insensitive, even on Linux.  Rather, you're saying that because the paths are being treated as case-sensitive, and because there's a mismatch between what's specified in the .csproj and what's on disk, you're getting failures.  Right?  If so, the .csproj should just be updated to match the on-disk casing.

**Comment by jyoungyun** [comment]
@stephentoub Right. I will post PR soon. :) Anyway I think the MSBuild guideline should be updated because the file path is not case-sensitive on Linux. What do you think about it ? And how can I fix the msdn guideline ?

**Comment by janvorli** [comment]
@jyoungyun The path actually **is** case sensitive - different case in the filesystem from the path in the project files means the paths are different. Case insensitive would mean that you could use a different casing in your project files and different in the file system and things would still work.

**Comment by jyoungyun** [comment]
@janvorli Oh, sorry. That's my mistake. I want to say the file path **is** case sensitive but the guideline in msdn said the file path **is not** case-sensitive. As you know, CoreCLR can be built on different file system. Someone implement the file path as case-insensitive on Windows, it will be make build break issue on Linux. So I thought that the msdn comments should be updated for multi file system.
