### ISSUE TITLE
Issue with DllImport

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/coreclr#5038]
While exploring how DllImport worked on Linux, I found the following issue at this line: https://github.com/dotnet/coreclr/blob/master/src/vm/dllimport.cpp#L7165

It seems that the code forgot to assign the result of the call to `LoadFromNativeDllSearchDirectories` to hmod. Is this expected?

**Comment by adityamandaleeka** [comment]
@manu-silicon You're right. Thanks for finding this issue!

**Comment by manu-silicon** [comment]
@adityamandaleeka You are welcome.

**Comment by whoisj** [comment]
Wouldn't it be nice if the language / compiler complained loudly when return values were ignored?

https://twitter.com/xjoeduffyx/status/730991667960893440

:smirk:

**Comment by yizhang82** [comment]
@adityamandaleeka I just discovered this as well and I have a fix (https://github.com/dotnet/coreclr/pull/5048) that fixes this as well as a different issue. Our PR probably going to conflict since I'm moving that exact same code.

**Comment by adityamandaleeka** [comment]
@yizhang82 I've closed my PR, and am reassigning this issue to you.

**Comment by yizhang82** [comment]
@adityamandaleeka Thank you!

**Comment by yizhang82** [comment]
Fixed with #5048

**Comment by manu-silicon** [comment]
@yizhang82 By the way, how one can set NATIVE_DLL_SEARCH_DIRECTORIES?

**Comment by yizhang82** [comment]
Only host can. See https://github.com/dotnet/coreclr/blob/f4fe31a03dca4ede37bd6451d0c81365ee9ee7e4/src/coreclr/hosts/corerun/corerun.cpp

**Comment by manu-silicon** [comment]
I see. Is there a way to have that set of directories searched too for PInvoke? That would help tremendously!

**Comment by yizhang82** [comment]
Yep. It is being searched already and that's exactly what LoadFromNativeDllSearchDirectories does. My other PR #5048 only changes the order.

**Comment by manu-silicon** [comment]
Actually I found that one could define the CORE_LIBRARIES environment variable but this only seems to work on Windows. The unix version of corerun doesn't check for it. Would be nice to have them consistent.

**Comment by yizhang82** [comment]
@manu-silicon That's a host specific issue since host owns translating the environment variables into NATIVE_DLL_SEARCH_DIRECTORIES that is understood by the runtime. 
@schellap Can you take a look?
/cc @gkhanna79

**Comment by manu-silicon** [comment]
In the meantime, I'll work on porting the Windows code to unixcoreruncommon to fetch the value of CORE_LIBRARIES as I need this to run some program on Unix. Thanks!

**Comment by gkhanna79** [comment]
Corelibraries is for internal development. We should probably clean it up and remove it. You should use native ski search path envvar only.

**Comment by manu-silicon** [comment]
Not sure to understand what native ski means. I just made a patch for picking up from CORE_LIBRARIES. See https://github.com/dotnet/coreclr/compare/master...manu-silicon:core_libraries?expand=1 Let me know if this is worth creating a pull request.

**Comment by gkhanna79** [comment]
@manu-silicon Sorry, auto-correct on phone does its own thing.

CORE_LIBRARIES is just a development/internal-testing environment variable and should not be relied upon. If you wish to add it to unixcorerun for consistentcy, that is fine. But this is not expected to be formally supported in any host used in formal scenarios. The formal way to specify the folders to look for pinvoke targets is NATIVE_DLL_SEARCH_PATHS.

**Comment by manu-silicon** [comment]
@gkhanna79 I understand that but how do I set this as a user? I only found CORE_LIBRARIES as a solution.

**Comment by gkhanna79** [comment]
You cannot - this is a host property and you will need to write a host that sets it. For .NET Core, this is automatically computed based upon the app manifest and .NET Host passes it to the runtime. If you have a scenario where you wish to have an external user specify such a value, consider authoring a host.

**Comment by manu-silicon** [comment]
I was thinking about an app manifest too. Is this supported just for Windows?

**Comment by gkhanna79** [comment]
.NET Core is available cross-plat - https://www.microsoft.com/net/core#macosx

**Comment by manu-silicon** [comment]
Being rusty on the app manifest. Does anyone have an example of a manifest that add to the NATIVE_DLL_SEARCH_PATHS?

**Comment by schellap** [comment]
https://github.com/dotnet/cli/blob/rel/1.0.0-preview1/TestAssets/TestProjects/PortableTests/PortableAppWithNative/

dotnet restore, publish

**Comment by manu-silicon** [comment]
@schellap This is confusing. I'm not using dotnet/cli. I'm looking at ways to tell CoreCLR where to look for my native dlls.

**Comment by schellap** [comment]
@manu-silicon no need to use CLI. You can take a look at how the dotnet host sets it from its app manifest for the .net core app model and implement something similar.

However, I would suggest porting the CORE_LIBRARIES as it would be a smaller change than go down the app manifest route since your objective is just hooking the native paths.

Here is relevant code:
https://github.com/dotnet/cli/blob/rel/1.0.0/src/corehost/cli/hostpolicy.cpp#L62
