### ISSUE TITLE
[OSX]: Failed to initialize CoreCLR, HRESULT: 0x800700CE

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/coreclr#5046]
Running a coreclr app with a long path fails with the below error
> Failed to initialize CoreCLR, HRESULT: 0x800700CE

Repro: 
- Download and unzip this tarball - [toolongpath.tar.gz](https://github.com/dotnet/coreclr/files/269720/toolongpath.tar.gz)
- From the unzipped folder run `./release_osx_x64_prtest/cli/test/dotnet-publish.Tests/bin/Debug/netcoreapp1.0/PublishOptionsTest3/TestAppWithLibrary/TestApp/bin/Debug/netcoreapp1.0/osx.10.11-x64/publish/TestApp`

CoreCLR version - 1.0.2-rc3-24113-00

cc: @gkhanna79 @schellap

**Comment by gkhanna79** [comment]
Was this working before?

**Comment by Sridhar-MS** [comment]
I think so. I started noticing this in CLI jenkins builds in my PR - https://github.com/dotnet/cli/pull/3060 to move from RC2 to RC3.

**Comment by janvorli** [comment]
The error code represents win32 error ERROR_FILENAME_EXCED_RANGE, so we somewhere actively determine that a path is too long. Let me try to find out where it stems from (seems like it would be somewhere in the PAL)

**Comment by gkhanna79** [comment]
@JeremyKuhne Could this be from your change?

**Comment by JeremyKuhne** [comment]
That was the error I was getting with long paths on Windows before I _just_ checked in #4902. Possible it is the same thing. The log I got was:

```
 HOSTLOG: AppDomainCompatSwitch=UseLatestBehaviorWhenTFMNotSpecified
 HOSTLOG: APP_LOCAL_WINMETADATA=
 HOSTLOG: Failed call to CreateAppDomainWithManager. ERRORCODE: 0x800700ce
 HOSTLOG: Execution failed
```

**Comment by janvorli** [comment]
I have pulled down the tar and was able to repro it. Then I've copied the last coreclr stuff over the one in the tar and the error is no more. So obviously @JeremyKuhne's change fixed it.

**Comment by janvorli** [comment]
Closing the issue since it is fixed in the latest coreclr.
