### ISSUE TITLE
Some badges in the repo's README are broken

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#5056]
The CentOS7.1 Debug badge is showing as green, but when you click on it, that job hasn’t been run since early March.

The RHEL7.2 debug badge links to a page that comes back with an HTTP ERROR with a Not Found reason.

OpenSUSE13.2’s Debug badge links to a job that doesn’t appear to have been built since early April.

There may be others as well, those are just the ones I noticed.

**Comment by adityamandaleeka** [comment]
I just fixed the broken RHEL link and checked that all the links work.

As for updating the badge status for jobs that haven't run in a long time, @mmitche, is there something we can do about that? Can we either make those jobs run more frequently (once a week?) or perhaps have some kind of 'stale' badge where we don't claim that the build is passing if it hasn't run for a long time?
