### ISSUE TITLE
SHA1CryptoServiceProvider in .Net core

### ISSUE THREAD

**Issue by acesiddhu** [dotnet/coreclr#5058]
Hi,
Are there plans to expose SHA1CryptoServiceProvider in .net core? Any short term way we can use it today?

**Comment by bartonjs** [comment]
SHA1 is only exposed via `SHA1.Create()`; the SHA1CryptoServiceProvider type doesn't exist in .NET Core.

(This issue would better belong in dotnet/corefx, since it's about framework libraries instead of the runtime layer)

**Comment by acesiddhu** [comment]
Thanks @bartonjs . Agree that it should be in corefx.
