### ISSUE TITLE
[Windows] Crossgen'ed binary throws InvalidCastException

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/coreclr#5064]
Repro Steps
1. Unzip this zip file which contains crossgen'ed .NET CLI - http://www.filedropper.com/cli-crossgened
2. git clone https://github.com/dotnet/cli
3. cd {cli_repo_root}\tools\RuntimeGraphGenerator
4. {path_to_cli_from_step1}\dotnet.exe restore
5. {path_to_cli_from_step1}\dotnet.exe publish

CoreCLR Version - 1.0.2-rc3-24113-00

Below exception is thrown
System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken at

>   Newtonsoft.Json.dll!Newtonsoft.Json.Linq.Extensions.Convert<Newtonsoft.Json.Linq.JToken, System.__Canon>(Newtonsoft.Json.Linq.JToken token) Line 267    C#
>     Newtonsoft.Json.dll!Newtonsoft.Json.Linq.JToken.Value<System.__Canon>(object key) Line 325  C#
>   Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.ProjectReader.GetPackOptionsValue<Newtonsoft.Json.Linq.JToken>(string option, Newtonsoft.Json.Linq.JObject rawProject, Newtonsoft.Json.Linq.JObject rawPackOptions, Microsoft.DotNet.ProjectModel.Project project) Line 678 C#
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.ProjectReader.GetPackOptions(Newtonsoft.Json.Linq.JObject rawProject, Microsoft.DotNet.ProjectModel.Project project) Line 654   C#
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.ProjectReader.ReadProject(System.IO.Stream stream, string projectName, string projectPath, Microsoft.DotNet.ProjectModel.ProjectReaderSettings settings) Line 202   C#
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.ProjectReader.TryGetProject(string path, out Microsoft.DotNet.ProjectModel.Project project, Microsoft.DotNet.ProjectModel.ProjectReaderSettings settings) Line 54   C#
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.Workspace.AddProjectEntry(string projectDirectory, Microsoft.DotNet.ProjectModel.Workspace.FileModelEntry<Microsoft.DotNet.ProjectModel.Project> currentEntry) Line 117 C#
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.Workspace.GetProjectCore.AnonymousMethod__11_0(string key) Line 97  C#
>     System.Collections.Concurrent.dll!System.Collections.Concurrent.ConcurrentDictionary<string, Microsoft.DotNet.ProjectModel.Workspace.FileModelEntry<Microsoft.DotNet.ProjectModel.Project>>.AddOrUpdate(string key, System.Func<string, Microsoft.DotNet.ProjectModel.Workspace.FileModelEntry<Microsoft.DotNet.ProjectModel.Project>> addValueFactory, System.Func<string, Microsoft.DotNet.ProjectModel.Workspace.FileModelEntry<Microsoft.DotNet.ProjectModel.Project>, Microsoft.DotNet.ProjectModel.Workspace.FileModelEntry<Microsoft.DotNet.ProjectModel.Project>> updateValueFactory)   Unknown
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.Workspace.GetProjectCore(string projectDirectory) Line 95   C#
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.Workspace.CreateBaseProjectBuilder.AnonymousMethod__16_0(string path) Line 230  C#
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.Resolution.ProjectDependencyProvider.GetDescription(string name, string path, Microsoft.DotNet.ProjectModel.Graph.LockFileTargetLibrary targetLibrary, System.Func<string, Microsoft.DotNet.ProjectModel.Project> projectCacheResolver) Line 27 C#
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.ProjectContextBuilder.ScanLibraries(Microsoft.DotNet.ProjectModel.Graph.LockFileTarget target, Microsoft.DotNet.ProjectModel.Graph.LockFileLookup lockFileLookup, System.Collections.Generic.Dictionary<Microsoft.DotNet.ProjectModel.ProjectContextBuilder.LibraryKey, Microsoft.DotNet.ProjectModel.LibraryDescription> libraries, Microsoft.DotNet.ProjectModel.Resolution.MSBuildDependencyProvider msbuildResolver, Microsoft.DotNet.ProjectModel.Resolution.PackageDependencyProvider packageResolver, Microsoft.DotNet.ProjectModel.Resolution.ProjectDependencyProvider projectResolver) Line 552   C#
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.ProjectContextBuilder.Build() Line 276  C#
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.ProjectContextBuilder.BuildAllTargets() Line 171    C#
>     mscorlib.ni.dll!System.Collections.Generic.List<Microsoft.DotNet.ProjectModel.ProjectContext>.InsertRange(int index, System.Collections.Generic.IEnumerable<Microsoft.DotNet.ProjectModel.ProjectContext> collection)   Unknown
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.Workspace.AddProjectContextEntry(string projectDirectory, Microsoft.DotNet.ProjectModel.ProjectContextCollection currentEntry) Line 199 C#
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.Workspace.GetProjectContextCollection.AnonymousMethod__8_0(string key) Line 66  C#
>     System.Collections.Concurrent.dll!System.Collections.Concurrent.ConcurrentDictionary<string, Microsoft.DotNet.ProjectModel.ProjectContextCollection>.AddOrUpdate(string key, System.Func<string, Microsoft.DotNet.ProjectModel.ProjectContextCollection> addValueFactory, System.Func<string, Microsoft.DotNet.ProjectModel.ProjectContextCollection, Microsoft.DotNet.ProjectModel.ProjectContextCollection> updateValueFactory)   Unknown
>     Microsoft.DotNet.ProjectModel.dll!Microsoft.DotNet.ProjectModel.Workspace.GetProjectContextCollection(string projectPath) Line 64   C#
>     dotnet.dll!Microsoft.DotNet.Tools.Publish.PublishCommand.SelectContexts(string projectPath, NuGet.Frameworks.NuGetFramework framework, string runtime) Line 419 C#
>     dotnet.dll!Microsoft.DotNet.Tools.Publish.PublishCommand.TryPrepareForPublish() Line 54 C#
>     dotnet.dll!Microsoft.DotNet.Tools.Publish.PublishCommand.Run.AnonymousMethod__0() Line 56   C#
>     dotnet.dll!Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(string[] args) Line 279  C#
>     dotnet.dll!Microsoft.DotNet.Tools.Publish.PublishCommand.Run(string[] args) Line 68 C#
>     dotnet.dll!Microsoft.DotNet.Cli.Program.ProcessArgs(string[] args, Microsoft.DotNet.Cli.ITelemetry telemetryClient) Line 144    C#
>     dotnet.dll!Microsoft.DotNet.Cli.Program.Main(string[] args) Line 59 C#

cc @gkhanna79 @JohnChen0

**Comment by gkhanna79** [comment]
@Sridhar-MS Does this work if the binary is not crossgened?

@JohnChen0 Can you PTAL?

**Comment by Sridhar-MS** [comment]
Yes.

**Comment by JohnChen0** [comment]
The InvalidCastException has been fixed by PR #4519. Please use a later build of CoreCLR and this issue should go away.

However, I'm seeing a different issue after going past the InvalidCastException. I'm receiving the following errors, even when Ready-to-Run images are not used:

    Can not find runtime target for framework '.NETStandardApp,Version=v1.5' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64' Possible causes:
    1. The project has not been restored or restore failed - run `dotnet restore`
    2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.

I suspect this new error is due to NuGet configuration, not Ready to Run.

@Sridhar-MS: Could you please try using a newer CoreCLR? Thanks.

**Comment by gkhanna79** [comment]
@Sridhar-MS Assigning this back to you.

**Comment by gkhanna79** [comment]
Closing since the issue was addressed long ago.
