### ISSUE TITLE
Ensure IlasmRoundTrip logic does not need a seperate Test Build

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#5082]
Please refactor using https://github.com/dotnet/coreclr/pull/5028/files as a template

A light weight template can also be found in the way GC tests are run in https://github.com/dotnet/coreclr/pull/5621/files

**Comment by ramarag** [comment]
cc @russellhadley  @gkhanna79 , This issue tracks the only remaining artifact which triggers a separate test build

**Comment by sbomer** [comment]
work in progress: [8039](https://github.com/dotnet/coreclr/pull/8039)

**Comment by RussKeldorph** [comment]
@sbomer Is this still on your radar?

@russellhadley

**Comment by sbomer** [comment]
It hasn't been, but I'll take another look this week. Thanks!

**Comment by sbomer** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/11178
