### ISSUE TITLE
Ensure GCStress logic does not need a seperate Test Build

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#5083]
use https://github.com/dotnet/coreclr/pull/5028 as a template

**Comment by fadimounir** [comment]
All tests under 'CoreMangLib\cti\system\weakreference' should be excluded somehow from the GCStress run, because they'll keep failing (by-design). (See #3792 for more information).

**Comment by ramarag** [comment]
One possible way to achieve this end could be to  set a property which will unset unconditionally the guard variable using the logic like https://github.com/dotnet/coreclr/pull/5028/files#diff-55dc052d26409738efcf7ff51f94d445R26

You could exclude an entire directory and sub directory from there on by adding this property to a dir.props file in that directory

**Comment by swgillespie** [comment]
@ramarag Is this issue for GCStress tests or for long running GC tests and GCSimulator? Or both?

**Comment by ramarag** [comment]
Any GC test scenario which is currently reliant on a building test separately, i believe they are : 
/p:GCStressLevel=%__GCStressLevel%   
/p:GCLongRunning=true
/p:GCSimulatorRun=true 

These properties should not be passed to the build, and instead should be passed to the runtest.cmd and runtest.sh

**Comment by swgillespie** [comment]
Sounds good!

**Comment by ramarag** [comment]
/p:GCStressLevel=%__GCStressLevel% has been removed from build by https://github.com/dotnet/coreclr/pull/5261
