### ISSUE TITLE
Crossgen of System.Private.CoreLib is failing

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#5088]
Hi, I just rebased my git clone of CoreCLR to the latest changes. When I attempt to run

```cmd
build release skipnative skiptests
```

so I can generate both the IL/native image version of mscorlib (or I guess System.Private.CoreLib now), I'm getting an error from crossgen about how it can't build System.Private.CoreLib:

```cmd
BUILD: Generating native image of System.Private.CoreLib for Windows_NT.x64.Release
BUILD: Error: CrossGen System.Private.CoreLib build failed. Refer to the build log file for details:
    C:\Users\James\Code\git\coreclr\bin\Logs\CrossgenCoreLib_Windows_NT__x64__Release.log
```

When I open the log, I get nearly-17000 lines saying that `System.Object` cannot be loaded from the assembly. I made a gist here so you can see: https://gist.github.com/jamesqo/8134bd224b5743e15210263555896c50

Is this a known issue/what can I do to fix this? Thanks.

**Comment by gkhanna79** [comment]
Can you please ensure that you are doing a clean build?

**Comment by gkhanna79** [comment]
Please do "git clean -xdf" and "build.cmd clean skiptests Release"

**Comment by jamesqo** [comment]
@gkhanna79 Thanks for helping! It seems to be working after I do a clean build :smile:
