### ISSUE TITLE
Make ValueType.Equals and ValueType.HashCode JIT intrinsics

### ISSUE THREAD

**Issue by drbo** [dotnet/coreclr#5090]
ValueType.Equals and ValueType.HashCode should be JIT intrinsics, with specialized code generated for each value type.  This would be a big perf win.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib 
@jkotas

**Comment by jkotas** [comment]
This would need to be done completely in the VM. JIT is not involved.

**Comment by jkotas** [comment]
This is actually tracked by https://github.com/dotnet/coreclr/issues/1341 already
