### ISSUE TITLE
Create the up-for-grabs label

### ISSUE THREAD

**Issue by shiftkey** [dotnet/coreclr#51]
It's mentioned in the [README](https://github.com/dotnet/coreclr/blob/master/README.md#how-to-engage-contribute-and-provide-feedback) but doesn't exist in the labels list

![screen shot 2015-02-04 at 5 01 57 pm](https://cloud.githubusercontent.com/assets/359239/6035862/9263d27e-ac8f-11e4-9b85-80b36b796607.png)

**Comment by ellismg** [comment]
Done.
