### ISSUE TITLE
Vector<T> constructor not recognized for ubyte, byte, short or ushort

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#5116]
The entry for .ctor (with a scalar argument) doesn't include ushort, but the other sub-int types are not recognized either, because the arg type is int, and therefore is not considered a match.
I am labeling this "Future" because I don't think these element types get significant use.

**Comment by benaadams** [comment]
`char` provides an alas for `ushort`, in a way?

**Comment by CarolEidt** [comment]
Oh yes, good point - thanks! It's just not getting matched for the same reason as the others.

**Comment by benaadams** [comment]
Oh.. actually I'm doing it the other way using `ushort` for `char` as char isn't a vector type: https://github.com/aspnet/KestrelHttpServer/pull/811/files 

Doing string operations and initializing with `Unsafe.Read<Vector<ushort>>`

**Comment by halter73** [comment]
@CarolEidt Does this mean that `Vector<byte/short>` operations aren't properly hardware optimized?

> I am labeling this "Future" because I don't think these element types get significant use.

`Vector<byte>` is used pretty heavily by Kestrel.

**Comment by CarolEidt** [comment]
Yes, that's the case. I hadn't realized that Kestrel was using these heavily - so perhaps this should be bumped up in priority.

**Comment by benaadams** [comment]
Is it just the scalar .ctor that's not hardware accl or other operations also?

**Comment by CarolEidt** [comment]
It is just the constructor. I found this while working on #2554.
