### ISSUE TITLE
How is Server GC set?

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#5117]
The RC2 templates use:
```json
"runtimeOptions": {
    "gcServer": true
},
```
The [dotnet cli says](https://github.com/dotnet/cli/blob/master/Documentation/specs/runtime-configuration-file.md#runtimeoptions-section-runtimeconfigjson) 
```json
"runtimeOptions": {
    "configProperties": {
        "System.GC.Server": true,
        "System.GC.Concurrent": true,
```
However, there is nothing in cli for that parsing and the only thing I can find in coreclr is in [mscoree/unixinterface.cpp](https://github.com/dotnet/coreclr/blob/master/src/dlls/mscoree/unixinterface.cpp#L96)

```cpp
if (Configuration::GetKnobBooleanValue(W("System.GC.Concurrent"), CLRConfig::UNSUPPORTED_gcConcurrent))
```

**Comment by benaadams** [comment]
Putting them both in for now which generates a `.runtimeconfig.json` of
```json
{
  "runtimeOptions": {
    "gcServer": true,
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```

**Comment by benaadams** [comment]
```json
"runtimeOptions": {
    "gcServer": true
}
```
Doesn't particularly seem to do anything but the other seems to work
```json
"configProperties": {
    "System.GC.Server": true
}
```
However does that mean the RC2 templates are wrong?

**Comment by Maoni0** [comment]
@adityamandaleeka made the [change](https://github.com/dotnet/coreclr/commit/1aa1b8ba64365f8b93a505d4f6165c6eaad84a7a)  ~2 months ago that reads System.GC.Server instead of gcServer from the config. You can still specify with the env var complus_gcServer to enable Server GC.

**Comment by benaadams** [comment]
@Maoni0 thank you, have raised issue with aspnet tooling https://github.com/aspnet/Tooling/issues/505
