### ISSUE TITLE
Personality routines for Unix asm stubs are incorrect

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#513]
The personality routines used in the Unix asm stubs like UmThunkStub are incorrect. The windows personality routines are specified there and the Unix ones have completely different signatures.
Some of them are probably even useless on Unix.
We need to asses all of them and create Unix versions of those that need to be kept and remove the others.

**Comment by janvorli** [comment]
All of them except of debugger related FuncEvalHijackPersonalityRoutine and ExceptionHijackPersonalityRoutine fixed by #518

**Comment by mikem8361** [comment]
Even though funceval isn't highest priority of managed debugging, it will still be necessary.  So the above FuncEvalHijackPersonalityRoutine is used and we will need to support it. I'm assigning this issue back to Jan.

**Comment by janvorli** [comment]
Fixed by #1515
