### ISSUE TITLE
System.DllNotFoundException 'api-ms-win-core-processenvironment-l1-1-0.dll'

### ISSUE THREAD

**Issue by SilenceDoGood** [dotnet/coreclr#5134]
Have a test application attempting to use `Directory.GetCurrentDirectory()` from the System.IO assembly. `dotnet restore` finishes completelys with no errors or warnings. When attempting to `dotnet run` the application I get the following exception. 

`Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processenvironment-l1-1-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.GetCurrentDirectory(Int32 nBufferLength, StringBuilder lpBuffer)
   at System.IO.Win32FileSystem.GetCurrentDirectory()
   at mp_submissiongenerator.Program.Main(String[] args)`

I've look around some of the past issues, and have noticed some breaking changes and missing platform compatible assemblies. I'm wondering if we are a recurrence in RC2 of the same issue.

Below is my project.json. Let me know if there is a different package I could include that has the proper platform specific assembly. 

{
  "version": "1.0.0-*",
  "description": "Generates Submission CSVs for InDesign, which are used to produce submissions.",
  "authors": [ "Peter", "Robert" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    },
      "System.IO": "4.0.11-rc2-23614",
      "System.IO.FileSystem": "4.0.0",
      "Microsoft.Extensions.Configuration": "1.0.0-rc1-final",
      "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
      "Newtonsoft.Json": "8.0.3"
  },

  "commands": {
    "mp_submissiongenerator": "mp_submissiongenerator"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50",
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Console": "4.0.0-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  }
}

**Comment by gkhanna79** [comment]
@SilenceDoGood Did you install the .NET Core Shared Framework?

CC @weshaggard

**Comment by RussKeldorph** [comment]
Not sure it's the same issue, but something that looks like this is causing thousands of failures in our test passes, e.g. http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst/645/testReport/.  Particularly interesting that what appear to be windows-specific DLLs are being referenced on non-windows.

**Comment by swgillespie** [comment]
I'm also seeing this issue in the CI: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_ubuntu_gcsimulator_tst/4/console

**Comment by weshaggard** [comment]
@russellhadley @swgillespie that tells me that you guys are trying to run some windows libraries on those OS's and it is most likely a configuration issue.

**Comment by weshaggard** [comment]
@SilenceDoGood what OS are you running on?

**Comment by RussKeldorph** [comment]
My problem was cause by runtest.sh fragility combined with a recent CoreFx change.  It was fixed by a19e82fe9e7ae44136ce7eee5892de7471533d6b.  It may not be related to other people's experiences.

**Comment by SilenceDoGood** [comment]
@weshaggard  This was being executed on Mac OS X 10.10.
@gkhanna79  I'm not sure to be honest, I went through the RC2 setup on the machine and installed dotnet though brew, if the Shared Framework is included in that installation process, then yes, otherwise no.

I was able to resolve the exception by changing the System.IO dependency to a different version. It seems as though some of the NuGet packages don't contain references to Assemblies targeted to Unix/Linux platforms, or at least that is my guess.

**Comment by weshaggard** [comment]
@SilenceDoGood good that you got this working. I didn't even notice until now you were mixing in some older beta packages which might cause errors like this to pop out. For reference try to use RC2 corefx package versions https://github.com/dotnet/versions/blob/master/build-info/dotnet/corefx/release/1.0.0-rc2/Latest_Packages.txt and hopefully that will help you have a more consistent set.
