### ISSUE TITLE
Vector<T> op_Explicit does not seem to be tested

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#5135]
This is defined as an intrinsic (in simdintrinsiclist.h) but does not seem to be tested by any of the tests in the JIT/SIMD test directory. Such a test should be added, and it should use the `JitLog` class in VectorUtil.cs to ensure that the intrinsic is recognized appropriately.

**Comment by RussKeldorph** [comment]
Not blocking RTM.

**Comment by mikedn** [comment]
@BruceForstall @RussKeldorph In case you missed it I have a PR opened for this.

**Comment by RussKeldorph** [comment]
@mikedn I did!  Thanks!
