### ISSUE TITLE
Fix and re-enable SIMD log testing for x86

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#5141]
The JitLog capability added to fix Issue #2554 does not seem to be working on x86.

**Comment by CarolEidt** [comment]
This is because jit32 doesn't have the JitFuncInfoLogFile capability. So even RyuJIT/x86, if it falls back to x86 on any of these methods, will fail the test.
So, the issue is to find a way to detect that methods are compiled with a non-RyuJIT backend - or, simply make the test more forgiving in the non-accelerated case.

**Comment by pgavlin** [comment]
This no longer repros.

**Comment by CarolEidt** [comment]
@pgavlin Thanks - It took me a while to recall the context for this. AFAIK jit32 still doesn't support the JitFuncInfoLogFile, but I changed the checking behavior to always assume success if there's no log file. It will print a "No JITLogFile" message to stdout, but will report success. So, I apparently went with the "make the test more forgiving" option but forgot to close this issue.
