### ISSUE TITLE
Change tests to use one common project.json

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#5174]
The CoreCLR tests have many local project.json file. To run the tests, we go over all project.json files and copy the dependencies into a single directory. If two project.json files specify different versions of packages, the last one copied wins that may not be the right one. I have run into many problems with mismatched versions while working on https://github.com/dotnet/coreclr/pull/5154

We should switch to just use one common project.json file instead.

**Comment by jkotas** [comment]
cc @gkhanna79

**Comment by RussKeldorph** [comment]
Superset of #3396?
