### ISSUE TITLE
SIGSEGV_HEAPCORRUPT_libcoreclr.so!MethodTable::SanityCheck

### ISSUE THREAD

**Issue by schaabs** [dotnet/coreclr#5194]
**The notes in this bug refer to the Ubuntu.14.04 dump [24117-00-1_0060](https://rapreqs.blob.core.windows.net/bryanar/BodyPart_f94f3cea-b93e-4748-8bd9-921ee9848e0b?sv=2015-04-05&sr=b&sig=MBsuTkwIn%2BTbdqooVAgAC8AqvabzFMt9fBNVTR3iuos%3D&st=2016-05-20T22%3A44%3A58Z&se=2017-05-20T22%3A44%3A58Z&sp=r).  Other dumps are available if needed.**

**This is a heap corruption bucket that has many hits, but what is intersting is we only hit this on the background gc thead, never when validating the heap from a blocking GC.  So it seems possible that this is a bug in HeapVerify when running on the BGC thread.**

    STOP_REASON:
    SIGSEGV

    FAULT_SYMBOL:
    libcoreclr.so!MethodTable::SanityCheck

    FAILURE_HASH:
    SIGSEGV_HEAPCORRUPT_libcoreclr.so!MethodTable::SanityCheck

    FAULT_STACK:
    libcoreclr.so!MethodTable::SanityCheck()
    libcoreclr.so!WKS::GCHeap::ValidateObjectMember(Object*)
    libcoreclr.so!Object::ValidateInner(int, int, int)
    libcoreclr.so!WKS::gc_heap::verify_heap(int)
    libcoreclr.so!WKS::gc_heap::gc1()
    libcoreclr.so!WKS::gc_heap::bgc_thread_function()
    libcoreclr.so!WKS::gc_heap::bgc_thread_stub(void*)
    libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*)

    FAULT_THREAD:
    thread #1: tid = 2759, 0x00007f0a5b1f9b8e libcoreclr.so`MethodTable::SanityCheck() + 14, name = 'corerun', stop reason = signal SIGSEGV
    (lldb)
 
 **Looking at where we are crashing we can see that the object we're trying to validate has a bogus address 0xcccccccccccccccc**
    
    (lldb) disassemble -F intel
    libcoreclr.so`MethodTable::SanityCheck:
        0x7f0a5b1f9b80 <+0>:   push   rbp
        0x7f0a5b1f9b81 <+1>:   mov    rbp, rsp
        0x7f0a5b1f9b84 <+4>:   push   r15
        0x7f0a5b1f9b86 <+6>:   push   r14
        0x7f0a5b1f9b88 <+8>:   push   r12
        0x7f0a5b1f9b8a <+10>:  push   rbx
        0x7f0a5b1f9b8b <+11>:  mov    r15, rdi
    ->  0x7f0a5b1f9b8e <+14>:  mov    rbx, qword ptr [r15 + 0x28]

    (lldb) register read rdi r15
         rdi = 0xcccccccccccccccc
         r15 = 0xcccccccccccccccc
         
 **Stepping up a level we can see that rdi comes from [rax] which comes from [r15] which is not a valid object according to dumpobj**
 
     (lldb) disassemble -F intel
        libcoreclr.so`WKS::GCHeap::ValidateObjectMember:
            0x7f0a5b424340 <+0>:   push   rbp
            0x7f0a5b424341 <+1>:   mov    rbp, rsp
            0x7f0a5b424344 <+4>:   push   r15
            0x7f0a5b424346 <+6>:   push   r14
            0x7f0a5b424348 <+8>:   push   r13
            0x7f0a5b42434a <+10>:  push   r12
            0x7f0a5b42434c <+12>:  push   rbx
            0x7f0a5b42434d <+13>:  sub    rsp, 0x18
            ...
            0x7f0a5b4243f3 <+179>: jmp    0x7f0a5b424404            ; <+196>
            0x7f0a5b4243f5 <+181>: nop    word ptr cs:[rax + rax]
            0x7f0a5b424400 <+192>: add    r15, 0x8
            0x7f0a5b424404 <+196>: cmp    r15, rbx
            0x7f0a5b424407 <+199>: jae    0x7f0a5b424430            ; <+240>
            0x7f0a5b424409 <+201>: mov    rax, qword ptr [r15]
            0x7f0a5b42440c <+204>: test   rax, rax
            0x7f0a5b42440f <+207>: je     0x7f0a5b424400            ; <+192>
            0x7f0a5b424411 <+209>: mov    rdi, qword ptr [rax]
            0x7f0a5b424414 <+212>: and    rdi, -0x2
            0x7f0a5b424418 <+216>: call   0x7f0a5b1f9b80            ; MethodTable::SanityCheck()
        ->  0x7f0a5b42441d <+221>: test   eax, eax
    
    (lldb) register read r15
        r15 = 0x00007f09bc478028
        
    (lldb) memory read -f x -s 8 -c 1 0x00007f09bc478028
    0x7f09bc478028: 0x00007f09bc808740
    (lldb) memory read -f x -s 8 -c 1 0x00007f09bc808740
    0x7f09bc808740: 0xcccccccccccccccc

    (lldb) dumpobj 0x00007f09bc808740
    <Note: this object has an invalid CLASS field>
    Invalid object
    DumpObj 0x00007f09bc808740  failed

**Comment by janvorli** [comment]
@kouvel this might be related to what I've fixed in https://github.com/dotnet/coreclr/pull/5183 (just checked that in)

**Comment by kouvel** [comment]
@schaabs this looks like a release build, but I don't see the symbol files in the zip. Do you happen to have those?

**Comment by kouvel** [comment]
So far:
- Checked the stress log and I can't find any of the relevant pointers here in the log
- Tried for a repro with debug and release bits, stress run finished successfully

I'll try a longer run to see if it repros. Any other ideas? @janvorli is there anything I can look for in a dump to see if it's the same issue that you have fixed?

**Comment by janvorli** [comment]
@kouvel You can try to run the "sos VerifyHeap" to see all the corrupted objects in the heap. You can also try to use the sos histXXX commands. I would try to find the address of the object ('this') in Object::ValidateInner, see if that object has a reasonable address. Then run histobjfind with the object as a parameter. If you are lucky, you'd get a history showing the roots. Then use histroot on the roots to see how the object value was changing.
You can also run the histxxx commands on the addresses of corrupted objects the VerifyHeap dumps.

**Comment by schaabs** [comment]
@kouvel I don't have the symbols for the dump mentioned in this bug.  Unfortunately, they were deleted from the build drop before we triaged it.  I have a couple of new runs I'm triaging today.  If I get a repro I'll get you a dump with symbols.

**Comment by kouvel** [comment]
Thanks @janvorli. I wasn't able to find the Hist* commands on Linux, but I found the roots of the object. It looks like there are stack references from a thread that is testing SortedSet, and one of the nodes has a pointer pointing into the middle of a free object slot (filled with 0xcc when HeapVerify is on). So it looks like the object got collected but the rest of the tree is live. Maybe an issue with software write watch missing a reference. I'll try to repro by running just this test case in a loop. Let me know if you have any other ideas.

**Comment by janvorli** [comment]
I have added the Hist* commands a week ago:
https://github.com/dotnet/coreclr/pull/5127
You could just get the latest libsosplugin.so and libsos.so and then you should be able to use them. But they are just an easier way to parse the stress log, you can find all the details from them. If you can find in which generation the object was relocated, then you can look at the stack scanning in that generation, find the thread of interest based on the root address and then see which methods' frames were scanned on the stack of that thread. You'll need to use ip2md to get the methods from the controlPC in the log.

**Comment by sergiy-k** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/5718
