### ISSUE TITLE
ByteComparer optimization is actually a perf slowdown

### ISSUE THREAD

**Issue by mburbea** [dotnet/coreclr#52]
`EqualityComparer<byte>.Default` is specialized to use a `ByteComparer`. This primarily exists so that `Array<byte>.IndexOf` can use a specialized version of IndexOf optimized for bytes. The actual implementation is done in `Buffer.ByteIndexOf` which takes a `byte*` instead of an array.
see here:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/EqualityComparer.cs#L49

The actual method `ByteEqualityComparer.IndexOf` is reasonably fast. However, because of all the hoops that get jumped through and the two rounds of parameters and contract checking (once on array.IndexOf and again on the byte comparer method), it ends up being much much slower than a simple naive for-loop implementation. 
I wrote a simple little benchmark to show the issue. Modified off some work I was doing for some SQL CLR so the implementation was mainly around byte arrays of 8000 or less bytes which I believe is a very common case. Here is the results. Since the `Vector<T>` doesn't seem to work any more since I installed the CTP5 here is my benchmark without it.
Running on RyuJIT x64 on my low voltage i5 laptop
```
Array_IndexOf
Average:111.20
Total:6,783.00
Program_Naive
Average:87.00
Total:5,307.00
Program_Unsafe
Average:76.15
Total:4,645.00
ByteEqualityComparer_IndexOf
Average:82.92
Total:5,058.00
```
And the code is here:
https://gist.github.com/mburbea/21a3182473591f84b0cd
I tried to be fair and include all the validation that the byte comparer for my 2 implementations. I included a simple Naive loop which is basically what the non-specialized version of Array.IndexOf would do (which is what I would recommend doing for minimal effort). And an unsafe version optimized for 64 bit, similar to what the `Buffer.ByteIndexOf` method actually does. I'm sure it could be optimized as I'm no expert on unsafe code. A version that uses SSE2 or AVX registers would obviously be faster.

**Comment by kangaroo** [comment]
Ping @richlander -- the PR has been closed.  Can we also close out the issue please?
