### ISSUE TITLE
Limit exports of the jitter shared library

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#5202]
As for now, the jitter shared library exports all symbols on Unix, including everything from PAL. In total, there are 3619 exports. We need to limit those to the necessary exports only, like we do for libcoreclr. See the generate_exports_file usage and --version-script / -exported_symbols_list linker options in src/dlls/mscoree/coreclr/CMakeLists.txt.

`nm -D libclrjit.so | grep " T " | wc -l`
3619
`nm -D libcoreclr.so | grep " T " | wc -l`
94

**Comment by pgavlin** [comment]
cc @russellhadley @RussKeldorph 

We probably want to get this done for RTM.

**Comment by RussKeldorph** [comment]
Agreed.

**Comment by pgavlin** [comment]
Closed by #5248.
