### ISSUE TITLE
CoreCLR /release/1.0.0 CI is broken (missing several fixes)

### ISSUE THREAD

**Issue by joshfree** [dotnet/coreclr#5222]
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/checked_osx_tst_prtest/lastCompletedBuild/testReport/

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/debug_centos7.1_prtest/10/testReport/junit/threading/NamedMutex/test1/

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/checked_ubuntu_tst_prtest/lastCompletedBuild/testReport/

**Comment by ellismg** [comment]
My recent PR was clean.  This should be resolved.
