### ISSUE TITLE
[docs] More prominently featuring the RyuJIT configuration knobs

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#5258]
To view the disassembly of a fresh build of CoreCLR, you have to do the following steps:

- Make a new .NET Core application (`cd foo && dotnet new`)
- Do a `dotnet publish -c Release` to produce a standalone app
- Overwrite the CLR dlls with your locally-built ones (I made a [shell script](https://gist.github.com/jamesqo/4751c2b5c7dc8c5b06f77a3f8766f88f) to automate doing this, as they are overwritten every time you rebuild with `dotnet publish`)
- Do an `export COMPlus_JitDisasm=MethodToView` (or `set` if you're using the Windows cmd)
- Run the published version of your app (also [made a script](https://gist.github.com/jamesqo/eddd1dc2ea4e02e87408f362d679c78c) for this)

Unfortunately, none of the first few steps are mentioned in the docs (perhaps other people do it differently?) and the `COMPlus_JitDisasm` variable is only mentioned [one time](https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=COMPlus_JitDisasm&type=Code), near the bottom of the [RyuJIT Overview](https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/Documentation/botr/ryujit-overview.md) document which is pretty lengthy.

Maybe we should separate the bottom part of that document (after [Dumps and Other Tools](https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/Documentation/botr/ryujit-overview.md#dumps-and-other-tools)) into a new one, for people who don't have the patience to read through the rest of the overview of the technical details of the JIT? Also, we may want to have something like a Contributing FAQ where we tell people how to do this by linking to this document.

cc: @ellismg

**Comment by AndyAyersMS** [comment]
Most of these will require checked or debug builds of the jit.

The script that produces the automatically formatted knobs md file probably won't see the Jit config values anymore. They now are defined in src\jit\jitconfigvalues.h.

**Comment by jamesqo** [comment]
@AndyAyersMS Ah yeah I forgot to mention that too, I overwrote my binaries with a Debug build of the jit. :+1:
