### ISSUE TITLE
EventSource Events that use complex types do not get logged 

### ISSUE THREAD

**Issue by davmason** [dotnet/coreclr#5284]
When complex types were added to EventSource (in V4.6) there was a latent bug where if the event had specified keywords the event would not be emitted to TraceEvent-style ETW controlers (e.g. PerfVIew). Basically there was confusion between a session bitmask (where the bits were 0, 1, 2, and 3), and the ETW keywords bitmask which uses different bits and the 'ToEventKeywords() morphs from one to the other. 

This bug has existed for a while, but we are now using both of those features (keywords and complex types), in the DiagnosticEventSource and when we started to really use it we found the problem.

**Comment by sergiy-k** [comment]
@davmason, PR https://github.com/dotnet/coreclr/pull/5348 has been merged. Can this issue be closed now?
/cc @vancem
