### ISSUE TITLE
Document performance collection practices for Windows and Linux

### ISSUE THREAD

**Issue by lt72** [dotnet/coreclr#5291]
We need to document the best practices for collecting performance data on Windows and Linux. 
Currently we have a pointer on the following page of CoreCLR repo
https://github.com/dotnet/coreclr/tree/master/Documentation 
that points directly to the PerfCollect script.

it should point to a small page with information specific to Windows and Linux

for Windows, it will be sufficient to point to th3e extensive PerfView material already available on the web

For Linux we should have a short explanation of what PerfCollect does and how to use it with PerfView to troubleshoot issues.

**Comment by brianrob** [comment]
Fixed via #5511.
