### ISSUE TITLE
Cannot build 'System.Private.CoreLib.dll' for ARM cross build

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#5319]
`` build.sh clean debug arm cross verbose "clang3.6" `` shows the following output at the end:
```
System.Private.CoreLib.dll build unsupported.
Nuget package generation unsupported.
Repo successfully built.
Product binaries are available at /home/parjong/projects/toolchains/coreclr/bin/Product/Linux.arm.Debug
```
Since MSBuild runs on x64 machine while cross build, it seems that there is no obstacle to build System.Private.CoreLib.dll in this setting.

**Comment by myungjoo** [comment]
We've lost the ability to build System.Private.CoreLib.dll quite recently (a few days ago).
This is a regression fix that requires quick attention. Thanks @parjong.
