### ISSUE TITLE
Ready-to-Run module can be used before fully activated

### ISSUE THREAD

**Issue by JohnChen0** [dotnet/coreclr#5330]
This issue tracks porting PR #5288 to release/1.0.0 branch.

Under certain conditions, a Ready-to-Run module is not yet fully activated when its contents are used. This can cause asserts in debug build. It can also cause module constructor to be run too late.

**Comment by gkhanna79** [comment]
@JohnChen0 Should we close this since https://github.com/dotnet/coreclr/pull/5332 is merged?

CC @sergiy-k

**Comment by sergiy-k** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/5332
