### ISSUE TITLE
ARM64: verify codegen for IBC and managed profile

### ISSUE THREAD

**Issue by russellhadley** [dotnet/coreclr#5337]
We should be able to run the IBC crossgen as well as insert probes correctly for ARM64.

**Comment by sdmaclea** [comment]
@russellhadley @BruceForstall Can you explain further?  I do not know what IBS is?  What do you mean by probes?

**Comment by BruceForstall** [comment]
Can you answer, @briansull ?

IBC is "Instrumented Block Counts". It's when you compile with crossgen using "/Tuning", run a profile scenario, use the ibcmerge tool to merge collected data, and rebuild, optimizing using those collected profiles.

E.g., https://github.com/dotnet/coreclr/pull/10113

cc @RussKeldorph @dotnet/arm64-contrib

**Comment by briansull** [comment]
I believe that everything should be working on ARM64.

**Comment by sdmaclea** [comment]
So close this?

**Comment by RussKeldorph** [comment]
Closing based on @briansull's assertion.  We'll find out if/when we try to enable it.
