### ISSUE TITLE
R2R: InvalidProgramException on Ubuntu and OSX

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#5341]
Ubuntu failure:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_ubuntu_pri1r2r_tst/lastCompletedBuild/testReport/baseservices.threading.generics.TimerCallback/thread22/thread22/

OSX Failure:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_osx_pri1r2r_tst/lastCompletedBuild/testReport/baseservices.threading.generics.WaitCallback/thread22/thread22/

Passes on Windows:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1r2r/lastCompletedBuild/testReport/baseservices/_threading_generics_TimerCallback_thread22_thread22_/_threading_generics_TimerCallback_thread22_thread22_cmd/

CC @sergiy-k @fadimounir @JohnChen0

**Comment by gkhanna79** [comment]
@fadimounir Is this dup of #5343 ? If so, should this be closed as dup of #5343?

**Comment by fadimounir** [comment]
Yes, it's a dup of #5343
