### ISSUE TITLE
VS launch of cordbg.exe test.exe pops "A fatal error has occurred..."

### ISSUE THREAD

**Issue by kingces95** [dotnet/coreclr#5354]
I'd like to launch and debug tests for coreclr using VS as managed only debugger. After building coreclr I open any test project and set `debug > start external program` to `\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\corerun.exe`. For the command line I use `F:\git\coreclr\bin\tests\Windows_NT.x64.Debug\path\to\exe`. When I hit `F5` VS pops a dialog

> A fatal error has occurred and debugging needs to be terminated.

I expected it to attach and execute.

If I change the program to throw an exception in main, run the program, wait for the OS to pop a dialog asking if I want to attach a debugger, then go to VS and use `debug > attach to process` and select only managed debugging, hit pause, hit `debug` on the `Microsoft CoreCLR EXE launcher` has stopped working dialog, then hit ok on the warning about another debugger attached, then hit no on the `Visual Studio Just-In-Time Debugger` dialog, then VS does attach at the exception. 

So once attached things work however launching under a debugger and using the VS JIT Debug dialog do not work. Will those two scenarios eventually be supported?

**Comment by kingces95** [comment]
VS doesn't continue (DBG_CONTINUE) after receiving this exception throw [here](https://github.com/dotnet/coreclr/blob/b7704374e683a8d3644a0640010936a22296967a/src/debug/ee/debugger.cpp#L1830-L1830). I'd guess because `corerun.exe` is unmanaged and so VS unaware that eventually a runtime will be loaded...

**Comment by jkotas** [comment]
cc @noahfalk

**Comment by kingces95** [comment]
Still reproduces on Update 3 RC.

**Comment by noahfalk** [comment]
CC @gregg-miskelly

**Comment by mikem8361** [comment]
@kingces95 are you trying to use VS to debug the coreclr runtime natively or debug the managed test code? It isn't clear what type of VS project you are using (.NET Core project type) or how you are attaching (Managed (CoreCLR) code type)

**Comment by gregg-miskelly** [comment]
@mikem8361 since this bug is just ever so slightly stale I am not sure how relevant it will be :) But I am fairly certain what was going on here was the @kingces95 had his project configured to use the Desktop CLR debugger. If you still have projects that are relevant, you can either configure them to use the CoreCLR debugger, or if they don't have an exposed option, force it with --

```xml
  <PropertyGroup>
    <StartAction>Program</StartAction>
    <StartProgram>add-path-to-dotnet-exe-here</StartProgram>
    <StartArguments>add-path-to-project-here</StartArguments>
    <!--Force the debugger to use CoreCLR-->
    <DebugEngines>{2E36F1D4-B23C-435D-AB41-18E608940038}</DebugEngines>
  </PropertyGroup>
```

**Comment by mikem8361** [comment]
I'm closing this issue.
