### ISSUE TITLE
R2R Windows Pri1 Failures

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#5366]
The following tests fail in Windows Pri1 R2R (see http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_pri1r2r_prtest/2/):

JIT._Regression_clr_x64_JIT_v4_0_devdiv374539_DevDiv_374539_DevDiv_374539_._Regression_clr_x64_JIT_v4_0_devdiv374539_DevDiv_374539_DevDiv_374539_cmd **[Only on Windows]**

Loader._classloader_generics_Instantiation_Negative_abstract01_abstract01_._classloader_generics_Instantiation_Negative_abstract01_abstract01_cmd

Loader._classloader_regressions_429802_CMain_CMain_._classloader_regressions_429802_CMain_CMain_cmd

**Comment by JohnChen0** [comment]
The following failure has been fixed with PR #5383 (master branch) and #5395 (release/1.0.0 branch): JIT.Regression_clr_x64_JIT_v4_0_devdiv374539_DevDiv_374539_DevDiv_374539._Regression_clr_x64_JIT_v4_0_devdiv374539_DevDiv_374539_DevDiv_374539_cmd

**Comment by JohnChen0** [comment]
All failures associated with this issue have been fixed in master and release/1.0.0.
