### ISSUE TITLE
Product file metadata

### ISSUE THREAD

**Issue by bendono** [dotnet/coreclr#5397]
Environment: Windows 10
Language: English

The generated files have an assortment of metadata issues. Below is a list that I have noticed:

```bat
coreclr.dll:
	Details -> Original filename: CoreCLR.dll (spacing differences)
```

```bat
ildasmrc.dll:
	Details -> Original filename: UNKNOWN_FILE
```

```bat
clrjit.dll:
ilasm.exe:
ildasm.exe:
	Details ->	File description: <blank>
				File verison: <blank>
				Product name: <blank>
				Product version: <blank>
				Copyright: <blank>
				Language: <blank>
```

```bat
mscorlib.dll:
mscorlib.ni.dll:
	Details -> File description: mscorlib
```

```bat
sos.dll:
	Details -> Original filename: SOS.dll (spacing differences)
```

```bat
System.Private.CoreLib.dll:
System.Private.CoreLib.ni.dll:
	Details -> File description: build
			-> Original filename: build
```

**Comment by bendono** [comment]
@jkotas Not sure who decides these things. Could you recommend someone to review this? Thanks.

**Comment by jkotas** [comment]
cc @leecow @gkhanna79

**Comment by gkhanna79** [comment]
@RussKeldorph Can you please have someone look into the ILAsm/ILDasm/CLRJIT issues?

**Comment by gkhanna79** [comment]
@AlexGhiondea @weshaggard FYI

**Comment by gkhanna79** [comment]
@AlexGhiondea Can you please look into fixing the facade and core library?

**Comment by RussKeldorph** [comment]
ilasm/ildasm/clrjit forked off into #5408.

/cc @kyulee1 @pgavlin @russellhadley

**Comment by kyulee1** [comment]
I'm not sure about Product file metadata. How do we generate and/or access them?

**Comment by AlexGhiondea** [comment]
@gkhanna79 are the errors about the NI image or the actual facade/implementation assembly?

**Comment by gkhanna79** [comment]
@AlexGhiondea I believe it is about IL assembly but we should look into for both IL and NI.

**Comment by jkotas** [comment]
NI images have copy of the version metadata from the IL image. It means that the filename in the version metadata does not match if the NI image has .ni.dll suffix. It is expected.

**Comment by gkhanna79** [comment]
@jkotas Sounds good. @AlexGhiondea Can you please look into fixing the IL for facade and core library?

**Comment by gkhanna79** [comment]
CoreCLR side of issues fixed by https://github.com/dotnet/coreclr/pull/5409

**Comment by AlexGhiondea** [comment]
@leecow @gkhanna79 -- what should we use for mscorlib and system.private.corelib for file description? Should we use the assembly name, or something different?

**Comment by leecow** [comment]
I would be fine with the assembly name if something more descriptive isn't possible or appropriate.

**Comment by gkhanna79** [comment]
mscorlib - Core library facade
SPC - Core runtime library

My 2 cents.

**Comment by joperezr** [comment]
It is not super straight forward to change the file description, since we would have to add some code in buildtools, plus some changes in coreclr to make that work. @gkhanna79 I have a fix for them having the assembly name, should I go with that or would you rather have me add the descriptions you suggested?

**Comment by gkhanna79** [comment]
Ok - in that case, keep the filename.

**Comment by joperezr** [comment]
Ok, that will be fixed as soon as my PR gets merged. Do we need this only in master branch, or should we also cherry-pick the change for a different branch?

**Comment by joperezr** [comment]
BTW also, the reason why clrjit.dll, ilasm.exe, ildasm.exe don't have any metadata is because they are using function _add_executable instead of add_executable_clr, which apparently excludes the native resource compilation even when there are native resources that get passed in. @rahku looks like you added the functions, do you know why this might be happening?

**Comment by rahku** [comment]
clrjit.dll actually uses add_library_clr
https://github.com/dotnet/coreclr/blob/master/src/jit/standalone/CMakeLists.txt#L11. So I don't think the issue is due to the function used.

**Comment by kyulee1** [comment]
ildasm/ilasm/clrjit issues are already merged via https://github.com/dotnet/coreclr/pull/5417

**Comment by AlexGhiondea** [comment]
@gkhanna79 I believe all the issues mentioned in this issue have been resolved.
