### ISSUE TITLE
Thread.IsThreadPoolThread not exposed in coreclr 

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#5407]
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Thread.cs#L645-L649

Some times we want to queue things on the threadpool; but if we are already on the threadpool continue executing rather than queue - however the thread can't be checked if is threadpool thread currently.

**Comment by karelz** [comment]
Seems to be back in .NET Standard 2.0: https://github.com/dotnet/corefx/blob/ddd1e5ce0f81f7091e544c65f99c37bf52a4ded9/src/System.Threading.Thread/ref/System.Threading.Thread.cs#L49
