### ISSUE TITLE
No documentation for building PAL

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#541]
### Issue
Their doesn't appear to be much, if any, documentation on the PAL. Further, it is not immediately apparent that the full PAL library is not built and tested when you execute `build.cmd`.

### Suggested Fix
Provide more documentation on modifying, building, and testing PAL.

**Comment by kangaroo** [comment]
@tannergooding Can you expand on your expectation?  The PAL isn't meant to be built or tested on windows.  Its the "Platform Abstraction Layer" which implements the pieces of WinAPI that Linux/MacOSX need.

**Comment by tannergooding** [comment]
@kangaroo My expectation is that you should be able to modify, build, and test PAL in order to extend the CoreCLR on existing platforms (Windows, Linux, MacOS) or to support new platforms.

I am working on dotnet/corefx#1151, which will extend the CoreCLR to support an extended mathematics library and provide support for single-precision implementations of methods in the existing math library.

These modifications will require changes on both the CoreFX and CoreCLR side, and while there is still some discussion on how best to implement the new APIs moving forward, some of the code (namely the PAL and JIT modifications) can be made and tested before the API decisions are made.

In order to extend the mathematics library, the PAL will need to be modified to support more functions from the CMATH library (`cbrt`, `hypot`, `acosh`, etc...). The intrinsic and FCALL support would then be added to the JIT compiler, which would call the CMATH functions (as the existing `System.Math` FCALLs do) with additional checks to ensure that the FCALLs handle NaN and Infinity as per ECMA-335.

In order to perform these changes, I would expect that I could modify `src\pal\inc\pal.h`, `src\pal\src\include\pal\palinternal.h`, and `src\pal\src\cruntime\finite.cpp` to support the rest of the CMATH library. I would also expect that I could add new tests to 'src\pal\palsuite\c_runtime` in order to properly test the changes made to the PAL.

**Comment by janvorli** [comment]
@tannergooding PAL is really not expected to be used on Windows. Why would you need PAL on Windows to achieve your goal? 
Coreclr uses Windows APIs and other library functions, like printf and many others. When running on Windows, the needed headers are directly included and appropriate libraries are linked in. On non Windows systems, no platform specific headers are included in the coreclr and stub headers with the same names as the real ones are included instead. These stubs all point to the palrt.h.
So the actual implementation of the necessary Windows APIs and other functions is in the PAL.
In your case, you would just include necessary headers with the new cmath functions in coreclr and add stub headers with the same name, but with just #include "palrt.h" in them (provided you need some new headers). Then you'd add the new functions to PAL.
Does it make sense?

**Comment by tannergooding** [comment]
@janvorli The changes to PAL wouldn't be for Windows, it would be to support Linux/MacOS. My understanding is that any new changes, when possible should also be made to support Linux/MacOS.

The new math functions already exist through the references to `<math.h>`. So the Windows implementation should be fine. However, without making the PAL modifications (and subsequently being able to build and test the changes), any modifications to extend the math library could potentially break on a platform where the MSVCRT (Microsoft Visual C Runtime) is not used.

Many of the C mathematical functions will raise a domain error if the input is outside the specified range (for `acos`, this is `[-1, +1]`). However, as per `7.12.1` of the [C11 Language Specification](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf), the return value, when a domain error occurs, is implementation defined. So for any math function that can raise a domain error, a PAL implementation needs to be provided to ensure that it provides the same functionality as the Windows version.

Except from **C11 Language Specification - 7.12.1 Treatment of error conditions**:
>For all functions, a *domain error* occurs if an input argument is outside the domain over
>which the mathematical function is defined. The description of each function lists any
>required domain errors; an implementation may define additional domain errors, provided
>that such errors are consistent with the mathematical definition of the function. On a
>domain error, the function returns an implementation-defined value; if the integer
>expression **math_errhandling & MATH_ERRNO** is nonzero, the integer expression
>**errno** acquires the value **EDOM**; if the integer expression **math_errhandling &
>MATH_ERREXCEPT** is nonzero, the ‘‘invalid’’ floating-point exception is raised.

Some of these functions (those that are already used by `System.Math`) are implemented as follows:
`src\pal\inc\rt\palrt.h` references `src\pal\inc\pal.h`, which defines PAL implementations of the math functions (such as `#define acos    PAL_acos`), which are then implemented in `src\pal\src\cruntime\finite.cpp`,

So, my current understanding is that, to support the math extensions on Linux/MacOS, I would need to add definitions for each CRT math function that can have implementation defined behavior to `src\pal\inc\pal.h` (done) and then implement said function in `src\pal\src\cruntime\finite.cpp` (done).

However, the method for building and testing PAL once the above steps have been completed is not obvious in the wiki's.

**Comment by kangaroo** [comment]
@tannergooding To add, built and test an addition such as you suggested, you need to do it on Linux or Mac

**Comment by tannergooding** [comment]
@kangaroo I seem to have had some kind of issue with my Linux build environment. Rebuilding from a clean install of Ubuntu 14.04 (plus the dependencies) appears to have fixed it.
