### ISSUE TITLE
Loader tests fail due to missing dependencies under ReadyToRun

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#5419]
Suggest disabling or fixing for RTM.

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/x64_checked_ubuntu_r2r_jitstress2_tst/1/testReport/
```
Loader.classloader.rmv.il.RMV-4-1-6a.RMV-4-1-6a
Loader.classloader.rmv.il.RMV-4-1-6b.RMV-4-1-6b
Loader.classloader.rmv.il.RMV-4-1-6d.RMV-4-1-6d
Loader.classloader.rmv.il.RMV-4-1-6d-two.RMV-4-1-6d-two
Loader.classloader.rmv.il.RMV-4-1-6e.RMV-4-1-6e
Loader.classloader.rmv.il.RMV-4-1-6e-two.RMV-4-1-6e-two
Loader.classloader.rmv.il.RMV-4-2-4.RMV-4-2-4
Loader.classloader.rmv.il.RMV-4-2-4-two.RMV-4-2-4-two
Loader.classloader.rmv.il.RMV-4-3-4.RMV-4-3-4
Loader.classloader.rmv.il.RMV-4-3-4-two.RMV-4-3-4-two
Loader.classloader.rmv.il.RMV-4-3-7.RMV-4-3-7
Loader.classloader.rmv.il.RMV-4-3-7-two.RMV-4-3-7-two
Loader.classloader.rmv.il.RMV-4-3-8.RMV-4-3-8
Loader.classloader.generics.Variance.Regressions.dev10_468712.dev10_468712.dev10_468712
Loader.classloader.regressions.163172.MethodImplFinal.MethodImplFinal
```

**Comment by RussKeldorph** [comment]
@gkhanna79 @JohnChen0

**Comment by gkhanna79** [comment]
@fadimounir PTAL

**Comment by RussKeldorph** [comment]
@fadimounir @gkhanna79 Regarding this issue as well as #5428: why do these not fail on Windows?  Are these indeed bad tests, or is there a bug in R2R on Unix?

**Comment by fadimounir** [comment]
@RussKeldorph I am not sure why they are not failing on Windows. Also when I manually tried to repro the failures on Windows and on Ubuntu, the tests passed (IL and R2R configurations). The tests needed fixing anyways, and the RMV* ones were just bad tests, not testing what they were really supposed to be testing anyways, so I'm deleting them.

**Comment by gkhanna79** [comment]
@fadimounir Are the following also passing on manual reruns?

> Loader.classloader.generics.Variance.Regressions.dev10_468712.dev10_468712.dev10_468712
> Loader.classloader.regressions.163172.MethodImplFinal.MethodImplFinal

If so, please use this issue to disable the tests, port the change to release branch and then move this issue to 1.1.0 so that we can fix the tests post RTM.

**Comment by RussKeldorph** [comment]
@gkhanna79 @fadimounir These still seem to be failing in the lab: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/x64_checked_ubuntu_r2r_jitforcerelocs_tst/3/testReport/.  If they are passing on manual reruns but failing in the lab, doesn't that suggest that we are not using the correct manual repro steps?  I don't think it's acceptable to disable/modify tests that we think ought to pass but clearly don't in the lab scenario.

If the answer ultimately comes down to "unfulfillable dependencies aren't supported by R2R," I guess I could believe that is viable for RTM, but it should be a conscious decision and a documented breaking difference for R2R.  I also don't think it's acceptable not to be able to answer why they don't fail on Windows.  That suggests we don't truly understand what's going on here.

If this has already been investigated, understood, and decided that the best course of action is to disable the tests, please just loop me in and I'll commit #5432 to fix the JIT tests.

**Comment by fadimounir** [comment]
@RussKeldorph I just realized I had accidentally dropped the Microsoft.VistualBasic.dll assembly in my test folder when attempting to repro the failure manually, and that's why it passed, So the missing dependency does really cause the test to fail. With my fix to remove the dependency on MVB, the tests are now passing also in the CI job associated with my PR (#5435).

**Comment by gkhanna79** [comment]
@fadimounir This sounds great! The outstanding failures in the PR are known issues - https://github.com/dotnet/coreclr/issues/5467 and https://github.com/dotnet/coreclr/issues/5428

**Comment by RussKeldorph** [comment]
@fadimounir But why are these passing on Windows in the lab?  Is Microsoft.VisualBasic.dll accidentally available there?

**Comment by fadimounir** [comment]
PR #5435 merged into master.

**Comment by RussKeldorph** [comment]
@fadimounir To answer my own question: these do indeed fail on Windows for me locally.  I'm not sure why they did not fail in the last runs on Windows, but we haven't had a lab run for 2+ days, so something could have changed in R2R since then, I suppose.  I hope it was intentional.
