### ISSUE TITLE
String to implement IReadOnlyList<char> instead of IEnumerable<char>

### ISSUE THREAD

**Issue by stas-sultanov** [dotnet/coreclr#542]
I would like to suggest to make class String to implement IReadOnlyList{char} instead of IEnumerable{char}.

Possibly interface should be implemented explicitly because of the Length property, which is extern and hardcoded in JIT. On the other hand Length could be deprecated and Count should be used instead.

**Comment by pharring** [comment]
@stas-sultanov Thanks for the suggestion. Can you give an example of where this would be useful?

**Comment by stas-sultanov** [comment]
Sure. Here is an example from one of my projects:
A ConvertEx class which provides a set of methods to convert data from base-n string to byte array and vice-versa. This class has a lot of methods like:
```C#
public static TryResult<String> TryToBase16String(byte[] data, int offset, int length)
public static TryResult<Byte[]> TryFromBase16String(string data, int offset, int length)
```
for this methods i'd like to use single method that checks arguments
```C#
    private static void CheckArguments<T>(IReadOnlyCollection<T> data, int offset, int length)
  	{
  	  	if (data == null)
		  	throw new ArgumentNullException(@"data");
  		if (length < 0)
	  		throw new ArgumentOutOfRangeException(@"length", length, @"Is less than 0.");
  		if (offset < 0)
	  		throw new ArgumentOutOfRangeException(@"offset", offset, @"Is less than 0.");
  		if (offset > (data.Count - length))
	  		throw new ArgumentOutOfRangeException(@"data", data.Count, @"Offset plus length is greater than the length of data.");
  	}
```
But unfortunately it is not possible because byte[] and string has only one common interface ```IEnumerable<T>```. Use ```IEnumerable<T>``` and get length via ```Count()``` method is not an option due to performance consideration.

**Comment by pharring** [comment]
A non-generic overload of CheckArguments would solve this, of course.

**Comment by stas-sultanov** [comment]
of course it would, and that it is the way it is made now. :) but it dose not looks like a good design.

maybe example is not good enough, however i strongly believe that this small change would made coreclr more versatile.

**Comment by SamuelEnglard** [comment]
Just a quick point but unless I'm wrong array's don't implement `IReadOnlyList<T>` so you'd still have to use the `Enumerable.Count()`. Do access the length/count of both an array and string in an efficient manner we'd have to `Enumerable.Count()` smarter. It already looks for types that implement `ICollection` or `ICollection<T>` and uses the `Count` property instead of looping. If we add a shortcut for `IReadOnlyList<T>` to that too then you could do what you want.

**Comment by stas-sultanov** [comment]
Arrays do implement `IReadOnlyList<T>`, please take a look at comments of [Array](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Array.cs) class.
Or try to compile followin code:
```C#
IReadOnlyList<int> test = new [] {1, 2, 3};
```
the Enumerable class that implemnt Count method is not included in corelclr.

**Comment by JohanLarsson** [comment]
[Not much perf diff between .Count() and .Length for an array](http://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,1191)

**Comment by SamuelEnglard** [comment]
Ah yes, I had looked before posting but missed that comment. My bad. So then yes I'm all for making string implement `IReadOnlyList<T>`. Sorry about that

**Comment by stas-sultanov** [comment]
> Not much perf diff between .Count() and .Length for an array

indeed, but once again:

> the Enumerable class that implements Count method is not part of the coreclr.

**Comment by VladimirGnenniy** [comment]
I believe that this would be nice improvement of the architecture of the .net classes.

**Comment by terrajobst** [comment]
@KrzysztofCwalina How do you think about this? It seems that `String` would eventually support `Span<char>`, would this additional interface make sense in general?

**Comment by Lukazoid** [comment]
+1 for this, would be really useful to be able to pass strings directly as IReadOnlyList<char>/IReadOnlyCollection<char> parameters instead of going via .ToCharArray() or using a wrapper class.

**Comment by KrzysztofCwalina** [comment]
To me string is a primitive type. I think it's already a mistake that it implements IEnumerable<char>.

**Comment by sharwell** [comment]
@KrzysztofCwalina I totally get that view. It leads to [special cases](https://github.com/antlr/antlrcs/blob/bff09d7d1f25c64b680268d218e8461d4666501a/Antlr4.StringTemplate/Interpreter.cs#L1280-L1282) in certain code that isn't required in, [say, Java](https://github.com/antlr/stringtemplate4/blob/master/src/org/stringtemplate/v4/Interpreter.java#L1111-L1127). But that ship has sailed.

Given that string already implements `IEnumerable<char>` (and that isn't going to change), the question is whether or not it should also implement `IReadOnlyList<char>`.

:thought_balloon: I think it makes sense specifically for some cases where code currently needs to call `ToCharArray()`. I couldn't find any clear-cut cases where the new implementation would simplify my own existing code, but especially given it already implements `IEnumerable<char>` I think it makes sense to implement `IReadOnlyList<char>` as well.

**Comment by KrzysztofCwalina** [comment]
If we implemented it explicitly and made sure the Linq extensions don't show on String, then I guess it would be fine.

**Comment by sharwell** [comment]
@KrzysztofCwalina It already implements `IEnumerable<char>`, so the LINQ extensions already appear.

**Comment by KrzysztofCwalina** [comment]
Hmmm, I was under the impression that we special cased it in C#.

**Comment by KrzysztofCwalina** [comment]
@jaredpar, @MadsTorgersen, I thought C# was special cased to not show Linq methods on String?

**Comment by sharwell** [comment]
In the PCL, `string` only implements `IEnumerable` (not `IEnumerable<char>`), so only `OfType` and `Cast` appear. When I target .NET 4.5+ desktop, I see the LINQ methods appearing in VS 2015 RC.

**Comment by MadsTorgersen** [comment]
@KrzysztofCwalina I think you just spent too much time with PCL. :-) In the full framework, LINQ always worked over string - for better or worse.

**Comment by KrzysztofCwalina** [comment]
Yeah, it's all slowly coming to me. I think we initially wanted to special case it, but then we just decided to implement IEnumerable. Then in 8.1 we added IEnumerable<char> (why?), and we are back to the original problem that string intellisense shows all these linq methods that probably should not be used on strings.

**Comment by danmosemsft** [comment]
API request -- moving to CoreFX

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #14336](https://github.com/dotnet/corefx/issues/14336) via [**ZenHub**](https://www.zenhub.com/)
