### ISSUE TITLE
Is the CONTRACTS_FULL symbol needed anymore?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#5437]
Doing a search for [CONTRACTS_FULL](https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=CONTRACTS_FULL) throughout the repo turns up 22 files, all of them C# or text. Based on that, I'm assuming the symbol isn't being defined anymore throughout the repo, and everything under an `#if CONTRACTS_FULL` is dead code.

Would it be okay to remove all of these code blocks under `CONTRACTS_FULL`, or would doing so cause problems since the mscorlib sources are shared with the full framework?

The reason I'm asking is because there appears to be a *lot* of code we could eliminate if that isn't the case; for example, the `ArrayContracts` class in Array.cs alone takes up [almost 200 lines](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Array.cs#L2834).

cc: @jkotas

**Comment by jkotas** [comment]
cc @AlexGhiondea 

I think it should be fine to remove ifdef for these. The Conditional attributes should stay.
