### ISSUE TITLE
Update Windows debugging instructions

### ISSUE THREAD

**Issue by bendono** [dotnet/coreclr#545]
The [Windows debugging instructions](https://github.com/dotnet/coreclr/wiki/Windows-instructions) appear to be out date with the current implementation.

From the instructions, steps 2, 6, and 8 are no longer valid.

> 2. Open \binaries\Cmake\CoreCLR.sln in VS.

Perhaps this is a regression, but CoreCLR.sln is now found in binaries\intermediates\Windows_NT.x64.debug.

> 6. Set Command=$(SolutionDir)..\product\$(Platform)\$(Configuration)\corerun.exe

Due to (2), the Command path will no longer resolve.
Further, $(Platform) is "x64", but this should now be "Windows_NT.x64.debug".
Also, while minor, "product" should be "Product".

Changed to: $(SolutionDir)..\..\Product\Windows_NT.x64.debug\corerun.exe

> 8. Set Working Directory=$(SolutionDir)..\product\$(Platform)\$(Configuration)

Due to (2), this no longer points to the CoreCLR binaries.
Changed to: $(SolutionDir)..\..\Product\Windows_NT.x64.debug

Need confirmation:
* Is the change from binaries\Cmake to binaries\intermediates\Windows_NT.x64.debug intentional?
* Windows_NT.x64.debug contains three pieces of information that may be better split into multiple folders, such as \Windows_NT\x64\debug. The order could be changed, but this could re-enable use of the VS macros such as $Configuration ("Debug") and $(Platform) ("x64").

**Comment by tzwlai** [comment]
The [Windows debugging instructions](https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md) have been updated.  Please feel free to reopen this if you have additional questions.
