### ISSUE TITLE
[sos] Wrong IL dump (ildasm vs dumpil)

### ISSUE THREAD

**Issue by sam-baravy** [dotnet/coreclr#5457]
CIL dump of _DumpIL_ command doesn't match that of _ildasm_ utility.
Tested with csc.exe and gmcs compilers; CIL does differ in a minor way but behavior holds.

Method of a class:

```
static void DumpIL()
{
    Console.WriteLine("test dumpil");
}
```

Output of **ildasm** (note a call to WriteLine):

```
IL_0000:  nop
IL_0001:  ldstr      "test dumpil"
IL_0006:  call       void [mscorlib]System.Console::WriteLine(string)
IL_000b:  nop
IL_000c:  ret
```

Output of **sos DumpIL** (no WriteLine at all):

```
IL_0000: nop 
IL_0001: ldstr "test dumpil"
IL_000a: stloc.0 
IL_000b: nop 
IL_000c: ret
```

In host assembler calls to WriteLine are present and a program runs flawlessly:

```
Normal JIT generated code
Test.DumpIL()
...
00007fff7d09b4f9 48bf68100068ff7f0000 movabs  rdi, 0x7fff68001068
00007fff7d09b503 488b3f               mov     rdi, qword ptr [rdi]
00007fff7d09b506 e88d8d79ff           call    0x7fff7c834298 (System.Console.WriteLine(System.String), mdToken: 000000000600183C)
...
```

Expected result: the same output of _ildasm_ and sos _DumpIL_.

**Comment by sam-baravy** [comment]
@Dmitri-Botcharnikov

**Comment by sam-baravy** [comment]
Guys,

I made a research and it turned out that the bug is caused by _readData<long>_ (coreclr/src/ToolBox/SOS/Strike/sildasm.cpp).
_Long_ is 4 bytes on both 32bit and 64bit Windows, it is 8 bytes on 64bit Linux though.

Obviously, _readData<long>_ was meant to get 4 bytes. The problem is that two approaches to define the size of variables are used in _sildasm.cpp_ file: '(un)signed short/int/long' and BYTE/WORD/DWORD. I substituted _long_ with _int32_t_ in _sildasm.cpp_ which resolved the issue.

Could you advice a better / proper way?

**Comment by Dmitri-Botcharnikov** [comment]
CC @mikem8361 @janvorli

**Comment by mikem8361** [comment]
I think it would be more consistent to use "LONG" for "long", ULONG when it should be unsigned (that may be hard to tell), "WORD" for "unsigned short", and "LONG64" for __int64. 

That would be a lot more changes but it would be clearer (coming from Windows) what the sizes are.

I would also be find with just changing "long" to "LONG".
