### ISSUE TITLE
[R2R] InvalidCastException in timer tests

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#5467]
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_pri1r2r_tst_prtest/11/#showFailuresLink

MESSAGE:
BEGIN EXECUTION in takeLock /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/crossgen /Platform_Assemblies_Paths /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay:/mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Checked/baseservices/threading/generics/TimerCallback/thread20 thread20.exe Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0 Copyright (c) Microsoft Corporation. All rights reserved. Native image /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Checked/baseservices/threading/generics/TimerCallback/thread20/thread20.ni.exe generated successfully. in ReleaseLock /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun thread20.exe Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Threading.TimerQueueTimer' to type 'System.Threading.ManualResetEvent'. at Gen`1.Target[U](Object p) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.TimerQueueTimer.CallCallback() at System.Threading.TimerQueueTimer.Fire() at System.Threading.TimerQueue.FireNextTimers() ./thread20.sh: line 108: 47217 Aborted (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" thread20.exe $CLRTestExecutionArguments Expected: 100 Actual: 134 END EXECUTION - FAILED
+++++++++++++++++++
STACK TRACE:

Stacktrace

MESSAGE:
BEGIN EXECUTION in takeLock /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/crossgen /Platform_Assemblies_Paths /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay:/mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Checked/baseservices/threading/generics/WaitCallback/thread20 thread20.exe Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0 Copyright (c) Microsoft Corporation. All rights reserved. Native image /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Checked/baseservices/threading/generics/WaitCallback/thread20/thread20.ni.exe generated successfully. in ReleaseLock /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_pri1r2r_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun thread20.exe Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Threading.QueueUserWorkItemCallbackDefaultContext' to type 'System.Threading.ManualResetEvent'. at Gen`1.Target[U](Object p) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch() ./thread20.sh: line 108: 48380 Aborted (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" thread20.exe $CLRTestExecutionArguments Expected: 100 Actual: 134 END EXECUTION - FAILED
+++++++++++++++++++
STACK TRACE:

CC @JohnChen0 @fadimounir @jkotas

**Comment by fadimounir** [comment]
Fixed and merged into master
