### ISSUE TITLE
CMake does not find libunwind.h in /usr/local/include

### ISSUE THREAD

**Issue by janhenke** [dotnet/coreclr#547]
I have a problem with CMake not finding the libunwind header files in /usr/local/include.

In src/pal/src/configure.cmake:22 there is this line: 
`check_include_files(libunwind.h HAVE_LIBUNWIND_H)`

Digging through several mailing list postings confirmed; CMake is supposed to look in /usr/local/include too, but apparently it does not. I am not seeing the reason here. Maybe someone else has an idea how to fix this?

This issue is currently blocking the build efforts on FreeBSD.

**Comment by janvorli** [comment]
@janhenke It seems you can fix it easily by setting the CMAKE_REQUIRED_INCLUDES variable to /usr/local/include before running the check_include_files. 
See below:
http://www.cmake.org/cmake/help/v3.0/module/CheckIncludeFile.html?highlight=cmake_required_includes

**Comment by janhenke** [comment]
Thanks @janvorli, but it does not change anything. That is the reason I do not understand this behaviour. It should work this way, but it does not. :(

**Comment by kangaroo** [comment]
@janhenke check the CMake output and error logs.  Its likely something else going on.

**Comment by janhenke** [comment]
@kangaroo Sadly not as helpful as I was hoping. CMakeError.log:
```
Determining if files libunwind.h exist failed with the following output:
Change Dir: /home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/local/bin/gmake" "cmTryCompileExec727676088/fast"
/usr/local/bin/gmake -f CMakeFiles/cmTryCompileExec727676088.dir/build.make CMakeFiles/cmTryCompileExec727676088.dir/build
gmake[1]: Entering directory '/usr/home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp'
/usr/local/bin/cmake -E cmake_progress_report /home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec727676088.dir/CheckIncludeFiles.c.o
/usr/bin/clang  -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200809L -Wall -std=c11    -o CMakeFiles/cmTryCompileExec727676088.dir/CheckIncludeFiles.c.o   -c /home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp/CheckIncludeFiles.c
/home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:10: fatal error: 'libunwind.h' file not found
#include <libunwind.h>
         ^
1 error generated.
CMakeFiles/cmTryCompileExec727676088.dir/build.make:57: recipe for target 'CMakeFiles/cmTryCompileExec727676088.dir/CheckIncludeFiles.c.o' failed
gmake[1]: Leaving directory '/usr/home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp'
gmake[1]: *** [CMakeFiles/cmTryCompileExec727676088.dir/CheckIncludeFiles.c.o] Error 1
Makefile:118: recipe for target 'cmTryCompileExec727676088/fast' failed
gmake: *** [cmTryCompileExec727676088/fast] Error 2

Source:
/* */
#include <libunwind.h>


int main(void){return 0;}
```
It tries to compile the simple source with default include paths, which should include /usr/local/include, but I even set that explicitly with the CMAKE_REQUIRED_INCLUDES parameter. But no way.

**Comment by janvorli** [comment]
What version of the CMake are you using? It seems that the minimum required version 2.8.12 doesn't support the CMAKE_REQUIRED_INCLUDES variable. If that's what you're using, could you please try to use a higher version, like 3.0.0 or newer? It may also solve the issue without the need to add the variable (just guessing)

**Comment by janhenke** [comment]
FreeBSD ships CMake 3.1.3, so that is unfortunately not the problem.

**Comment by janvorli** [comment]
@janhenke Could you show me please where you have added setting of the CMAKE_REQUIRED_INCLUDES? Was it in the src/pal/src/configure.cmake? Or somewhere else?
Maybe we should add 
```cmake
include_directories(/usr/local/include)
```
to the src/pal/src/CMakeLists.txt before it includes the configure.cmake. It should be under an if() for the BSD. It will be needed for the build on BSD anyways.

**Comment by janhenke** [comment]
In src/pal/src/configure.cmake:
```
if(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
  set(CMAKE_REQUIRED_INCLUDES "/usr/local/include /usr/include")
endif()
```

But I think we should look in /usr/local/include on all platforms anyway! Even on Linux it is perfectly valid to have libunwind or other dependencies installed under /usr/local instead of /usr.

**Comment by janvorli** [comment]
The way you set it doesn't seem correct. You have put them all in a single string. I believe they should be a list.
Also, are you sure that the if  is correct there? 
As a first step, I would try to use this unconditionally:
```cmake
set(CMAKE_REQUIRED_INCLUDES /usr/local/include)
```
and see if it fixed the issue.

**Comment by janhenke** [comment]
No change, also the log output did not change to reflect the change. No extra include directory added to the test compile. This is exactly the reason I do not understand why it does not work.

**Comment by janvorli** [comment]
You can try to modify the check_include_file_macro and put some diagnostic message(...) in there to see e.g. what it set the CHECK_INCLUDE_FILE_C_INCLUDE_DIRS to, etc.
The macro is defined in the CheckIncludeFile.cmake in the Modules folder. On my Ubuntu, it is in /usr/share/cmake-2.8/Modules/, so I guess your path will be similar, just reflecting the different version.

**Comment by janhenke** [comment]
At last some progress:
```
Determining if files libunwind.h exist failed with the following output:
Change Dir: /home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/local/bin/gmake" "cmTryCompileExec2397334251/fast"
/usr/local/bin/gmake -f CMakeFiles/cmTryCompileExec2397334251.dir/build.make CMakeFiles/cmTryCompileExec2397334251.dir/build
gmake[1]: Entering directory '/usr/home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp'
/usr/local/bin/cmake -E cmake_progress_report /home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec2397334251.dir/CheckIncludeFiles.c.o
/usr/bin/clang  -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200809L -Wall -std=c11  -I/usr/local/include    -o CMakeFiles/cmTryCompileExec2397334251.dir/CheckIncludeFiles.c.o   -c /home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp/CheckIncludeFiles.c
In file included from /home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:
In file included from /usr/local/include/libunwind.h:23:
In file included from /usr/local/include/libunwind-x86_64.h:37:
/usr/include/ucontext.h:50:2: error: unknown type name 'stack_t'
        stack_t         uc_stack;
        ^
1 error generated.
CMakeFiles/cmTryCompileExec2397334251.dir/build.make:57: recipe for target 'CMakeFiles/cmTryCompileExec2397334251.dir/CheckIncludeFiles.c.o' failed
gmake[1]: Leaving directory '/usr/home/janhenke/coreclr/binaries/intermediates/freebsd.x64.debug/CMakeFiles/CMakeTmp'
gmake[1]: *** [CMakeFiles/cmTryCompileExec2397334251.dir/CheckIncludeFiles.c.o] Error 1
Makefile:118: recipe for target 'cmTryCompileExec2397334251/fast' failed
gmake: *** [cmTryCompileExec2397334251/fast] Error 2

Source:
/* */
#include <libunwind.h>


int main(void){return 0;}
```

With this added to src/pal/src/configure.cmake:
```
if(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
  set(CMAKE_REQUIRED_INCLUDES "/usr/local/include" "/usr/include")
endif()
```

But how do I fix the missing stack_t type now. Bootstrapping can be tiresome.

**Comment by janvorli** [comment]
@janhenke There was a similar issue on CentOS (see #300). Please take a look if it gives you some hints on how to fix it.

**Comment by janhenke** [comment]
An update after digging through some of the system header files. It seems that stack_t needs __XSI_VISIBLE to be defined to non-zero. __XSI_VISIBLE is defined in <sys/cdefs.h>. It appears that strict C11 mode (`#elif defined(_C11_SOURCE)      /* Localism to specify strict C11 env. */` deactivates the several POSIX features including stack_t.

Right now I am a bit undecided how the best way to address this issue looks like.

**Comment by janhenke** [comment]
Follow up, it seems FreeBSD (like Darwin) does not work with _DEFAULT_SOURCE and _POSIX_C_SOURCE. I am getting past that problem now.
