### ISSUE TITLE
Incorrect allocation failure handling in PAL

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#5488]
While investigating OOM related issues, I have hit two places where we were
not handling correctly the case when memory allocation failed.
In the StackString::OpenStringBuffer, when the Resize failed to allocate
properly sized buffer, we were returning the small internal buffer instead
of NULL. So the caller expected that the full requested size was prepared
and filled it with data, overwriting memory.
In CorUnix::InternalMapViewOfFile, when we have failed to allocate the
PMAPPED_VIEW_LIST to hold information on the mapping, we have unmapped
the memory again, but we have still returned the address of the now
unmapped mapping. The caller, MapViewOfFileEx, then returned this
address to its caller, since it didn't expect the CorUnix::InternalMapViewOfFile
to set its output parameter in the case of failure.

**Comment by janvorli** [comment]
Fixed by #5473

**Comment by sergiy-k** [comment]
https://github.com/dotnet/coreclr/pull/5489
