### ISSUE TITLE
Extend testing harness to enable A/B comparisons for codegen changes

### ISSUE THREAD

**Issue by russellhadley** [dotnet/coreclr#549]
Be able to drive the XUnit harness to produce baseline/diff output for codegen changes.  This will also be used to validate any development using the alternate jit vs fall back jit.  Changes should be maintained in coreclr tree.

Requirements:
- Cross platform friendly script
- Allow for asm diff and IR diff 
- Provide features for building a validation script for alt vs fall back jit baselines (ensuring the alt jit is still compiling the same set of methods)

@libengu has been working on a prototype for this so we have some initial thoughts.

@jkotas - Not sure who the right people are that should review this.  We can do the work but I want to make sure we all agree on where we're going with the solution.

**Comment by jkotas** [comment]
I assume that it is not going to require changes in xunit. It is just a wrapper script around existing xunit-based tests. Correct?

I think @BruceForstall is a good person to review this. He built the code-diffs for RyuJIT.

**Comment by russellhadley** [comment]
I've got a current prototype of this functionality here:  https://github.com/russellhadley/mcgutils  This will be put up in dotnet repo called jitutils once I do another round of renaming.  The functionality to integrate it to runtest is also inflight on my machine.

**Comment by AndyAyersMS** [comment]
Think we can close this now. The [dotnet/jitutils](https://github.com/dotnet/jitutils) tool suite seems to be working well for jit developers.
