### ISSUE TITLE
Assert failure(PID 10096 [0x00002770], Thread: 28568 [0x6f98]): rangeOffset >= (offset + (sizeof(void*) * 3))

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#5490]
**Environment**
```
Windows x64 Checked
COMPlus_TailCallStress=1
```
**Failing tests**
```
managed\Compilation\Compilation\Compilation.cmd
JIT\Performance\CodeQuality\Roslyn\CscBench\CscBench.cmd
```
**Output**
```
        Assert failure(PID 10096 [0x00002770], Thread: 28568 [0x6f98]): rangeOffset >= (offset + (sizeof(void*) * 3))

        CORECLR! EncodeGCOffsets + 0x20C (0x00007fff`0c895c18)
        CORECLR! StubLinkerCPU::CreateTailCallCopyArgsThunk + 0x1008 (0x00007fff`0c893674)
        CORECLR! CEEInfo::getTailCallCopyArgsThunk + 0x164 (0x00007fff`0ca27794)
        CLRJIT! Compiler::fgMorphTailCall + 0x311 (0x00007fff`2459b3e5)
        CLRJIT! Compiler::fgMorphCall + 0x4B6 (0x00007fff`2458ec8e)
        CLRJIT! Compiler::fgMorphTree + 0x43B (0x00007fff`2459b87f)
        CLRJIT! Compiler::fgMorphStmts + 0x1FD (0x00007fff`2459a815)
        CLRJIT! Compiler::fgMorphBlocks + 0x114 (0x00007fff`2458dfb8)
        CLRJIT! Compiler::fgMorph + 0x23F (0x00007fff`2458bde3)
        CLRJIT! Compiler::compCompile + 0x1D6 (0x00007fff`244e0e1e)
            File: c:\git\coreclr\src\vm\i386\stublinkerx86.cpp Line: 6051
            Image: C:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
```

**Comment by RussKeldorph** [comment]
Putting this in 1.0.0-rtm unless/until we can determine this doesn't make the bar.

**Comment by erozenfeld** [comment]
This appears to be an off-by-one bug in EncodeGCOffsets in this code:
https://github.com/dotnet/coreclr/blob/6a2e3b34c3c9ac32456d38567b9f44ab6aea2f63/src/vm/i386/stublinkerx86.cpp#L6047:L6054

**Comment by erozenfeld** [comment]
This appears to be an off-by-one bug in EncodeGCOffsets in [this code]
(https://github.com/dotnet/coreclr/blob/6a2e3b34c3c9ac32456d38567b9f44ab6aea2f63/src/vm/i386/stublinkerx86.cpp#L6047:L6054).
These lines:
```
_ASSERTE(rangeOffset >= (offset + (sizeof(void*) * 3))); 
delta = rangeOffset - (offset + (sizeof(void*) * 3)); 
```
should be
```
_ASSERTE(rangeOffset >= (offset + (sizeof(void*) * 2))); 
delta = rangeOffset - (offset + (sizeof(void*) * 2)); 
```
I believe this is a GC hole. The GC layout of the frame used for a tail call via helper may be encoded incorrectly.
@jkotas @gkhanna79 can you please take a look?

**Comment by jkotas** [comment]
@janvorli Would you like to take a look at this one since you are ramping up on the tailcalls?

**Comment by janvorli** [comment]
I have analyzed the code and I agree that it is wrong. It generates information that is correct when there are four or more offsets in a run, but when there are three, it asserts in debug and generates incorrect delta (-1) in release build. It should be fixed as @erozenfeld has said.
But there is one more place that needs to be fixed - the FrameOffsetDecoder::MoveNext that reads the encoded offsets, since the formulas for delta at the encoding and decoding sides must match.
```C++
offsetEnd += sizeof(void*) * 3;
```
It should be 
```C++
offsetEnd += sizeof(void*) * 2;
```
It is in this block of code:
https://github.com/dotnet/coreclr/blob/master/src/vm/i386/stublinkerx86.cpp#L5914:L5925

**Comment by sergiy-k** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/5540
