### ISSUE TITLE
Is Mono still required to build CoreCLR on OS X?

### ISSUE THREAD

**Issue by jasonwilliams200OK** [dotnet/coreclr#5497]
According to doc: https://github.com/dotnet/coreclr/blob/775003a/Documentation/building/osx-instructions.md, OS X requires Mono to build CoreFX.

However, PCL dependency is long gone from CoreFX build process: https://github.com/dotnet/corefx/pull/6077.

Should that [section]( https://github.com/dotnet/coreclr/blob/775003a/Documentation/building/osx-instructions.md#Mono) be removed altogether?

**Comment by ellismg** [comment]
Yes, it can be removed.  build.sh will even do the ulimit thing for you now.  We no longer need mono for anything.

**Comment by jasonwilliams200OK** [comment]
Thanks Matt, I will prepare a PR pronto. :)
