### ISSUE TITLE
CentOS R2R Test run fails due to invalid directory

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#5502]
09:06:29 + ./tests/runtest.sh --testRootDir=/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_pri1r2r_tst/bin/tests/Windows_NT.x64.Checked --testNativeBinDir=/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_pri1r2r_tst/bin/obj/Linux.x64.Checked/tests --coreClrBinDir=/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_pri1r2r_tst/bin/Product/Linux.x64.Checked --mscorlibDir=/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_pri1r2r_tst/bin/Product/Linux.x64.Checked '--coreFxBinDir=/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_pri1r2r_tst/bin/Linux.AnyCPU.Release;/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_pri1r2r_tst/bin/Unix.AnyCPU.Release;/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_pri1r2r_tst/bin/AnyOS.AnyCPU.Release' --coreFxNativeBinDir=/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_pri1r2r_tst/bin/Linux.x64.Release --crossgen --runcrossgentests
09:06:29 Directory specified in --coreFxBinDir does not exist: /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_pri1r2r_tst/bin/Linux.AnyCPU.Release
09:06:29 
Build step 'Execute shell' marked build as failure

**Comment by wtgodbe** [comment]
Not yet fixed - the issue I fixed was actually different than this.

**Comment by wtgodbe** [comment]
Actually, never mind, turns out my change did fix this issue. See a working CentOS job here - http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_centos7.1_pri1_tst_prtest/2/consoleFull
