### ISSUE TITLE
Managed COM activation in .NET Core

### ISSUE THREAD

**Issue by yizhang82** [dotnet/coreclr#5506]
CoreCLR doesn't support managed COM activation today - it does not have a DllGetClassObject implementation. We can either enable it, or write a special shim that launches CoreCLR and returns the factory object that creates the object (through reflection).

**Comment by AaronRobinsonMSFT** [comment]
https://github.com/dotnet/core-setup/pull/4577
https://github.com/dotnet/sdk/pull/2814

**Comment by AaronRobinsonMSFT** [comment]
Host work is complete with https://github.com/dotnet/core-setup/pull/4577
CoreCLR work is also complete. Waiting on developer experience, but closing this since dev experience is track with https://github.com/dotnet/sdk/pull/2814.
