### ISSUE TITLE
Expose DependentHandle

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#5508]
The `DependentHandle` struct is a useful form of a GCHandle. Currently, it's only exposed as part of the `ConditionalWeakTable` class. `ConditionalWeakTable` is quite a heavy-weight object. It does more than is often needed. If there's only a need for a single object pair using `ConditionalWeakTable` seems inappropriate and quite expensive.

Also, `ConditionalWeakTable` is synchronized internally. This means that it does not scale across many cores. For that reason it is not a good workaround to simply maintain a global `ConditionalWeakTable` for the entire application.

I suggest that the `DependentHandle` struct is being cleaned up and exposed for public consumption. As far as I can tell only cosmetic changes need to be made to make the type "nice". A namespace change is probably in order as well. It should be placed next to `GCHandle`.

**Comment by jfrijters** [comment]
+1 It is a shame to have such a powerful feature and not expose it.

**Comment by weltkante** [comment]
I created a proposal for implementing a `ConditionalWeakReference<TKey, TValue>` under #26505

This is different from just exposing DepedentHandle but I think adding a high level primitive is more likely to be accepted than exposing an "unsafe" low level primitive. In our own applications we started to build this by using reflection to get access to the native static methods on DependentHandle, so you can actually do this today, but having to reflect into runtime internals is not great.

**Comment by weltkante** [comment]
I created a proposal for implementing a `ConditionalWeakReference<TKey, TValue>` under #26505

Note that this is different from this issue requesting exposal of DepedentHandle as analogue to GCHandle, my proposal adds a new primitive analogous to WeakReference (which currently does not exist at all).

We'll see if adding a high level primitive is more likely to be accepted than exposing an "unsafe" low level primitive, both are valuable to have, but I'd be content with a "safe" high level primitive.

**Comment by jkotas** [comment]
Format API proposal: https://github.com/dotnet/corefx/issues/40805
