### ISSUE TITLE
Correct .net core version

### ISSUE THREAD

**Issue by avikenjale** [dotnet/coreclr#5510]
I am bit confused, when I run `dotnet --version` thru command line, I get `1.0.0-preview1-002702` however when I see `C:\Program Files\dotnet\shared\Microsoft.NETCore.App` I see `1.0.0-rc2-3002702`. 

Which one is latest and i can switch from `preview1` to `rc2`, how?  
Also, are both stable versions?

Any way to get correct documentation for **preview1** vs **rc2** ?

**Comment by blackdwarf** [comment]
@avikenjale the tools and the runtime are on different versions. What you get when you run the `dotnet --version` command is the version of the **tooling** which is, at this point, on Preview 1. The runtime and its libraries, what `Microsoft.NETCore.App` meta-package represents, are on RC2 version. You can read more about the *why* of it on [Scott Hunter's blog post](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/). 

Both are stable and pre-release versions, yes.

**Comment by danmosemsft** [comment]
@gkhanna79 what are we leaving this issue open for -- is there action here (other than clarifying our versioning system -- which is perhaps not best tracked here)?

**Comment by gkhanna79** [comment]
@richlander @bleroy Are driving this.

**Comment by gkhanna79** [comment]
This is being driven in Core-Setup repo, so I will close this one.
