### ISSUE TITLE
SIGABRT_ASSERT_libcoreclr.so!VirtualFree

### ISSUE THREAD

**Issue by schaabs** [dotnet/coreclr#5515]
**The notes in this bug refer to the Ubuntu.14.04 dump [rc3-24131-01_001F](https://rapreqs.blob.core.windows.net/sschaab/BodyPart_826333fd-2d98-42db-8555-4d56d6c189ff?sv=2015-04-05&sr=b&sig=4Q1DOMWTz8yM8DZdYs6mJRCfNYrczUJInJW8C9K%2FDY0%3D&st=2016-06-03T22%3A02%3A31Z&se=2017-06-03T22%3A02%3A31Z&sp=r).  Other dumps are available if needed.**

**This issue seems likely to be related to issue [#5188](https://github.com/dotnet/coreclr/issues/5188) however with a different failure pattern on CHK builds where we assert on VirtualFree**

    STOP_REASON:
    SIGABRT

    FAULT_SYMBOL:
    libcoreclr.so!VirtualFree

    FAILURE_HASH:
    SIGABRT_libcoreclr.so!VirtualFree

    FAULT_STACK:
    libc.so.6!__GI_raise
    libc.so.6!__GI_abort
    libcoreclr.so!UNKNOWN
    libcoreclr.so!sigtrap_handler(int, siginfo_t*, void*)
    libclrjit.so!sigtrap_handler(int, siginfo_t*, void*)
    libpthread.so.0!???
    libcoreclr.so!DBG_DebugBreak
    libcoreclr.so!DebugBreak
    libcoreclr.so!VirtualFree
    libcoreclr.so!EEVirtualFree(void*, unsigned long, unsigned int)
    libcoreclr.so!CExecutionEngine::ClrVirtualFree(void*, unsigned long, unsigned int)
    libcoreclr.so!non-virtual thunk to CExecutionEngine::ClrVirtualFree(void*, unsigned long, unsigned int)
    libcoreclr.so!ClrVirtualFree(void*, unsigned long, unsigned int)
    libcoreclr.so!GCToOSInterface::VirtualDecommit(void*, unsigned long)
    libcoreclr.so!WKS::gc_heap::decommit_heap_segment_pages(WKS::heap_segment*, unsigned long)
    libcoreclr.so!WKS::gc_heap::decommit_ephemeral_segment_pages()
    libcoreclr.so!WKS::gc_heap::gc1()
    libcoreclr.so!WKS::gc_heap::garbage_collect(int)
    libcoreclr.so!WKS::GCHeap::GarbageCollectGeneration(unsigned int, WKS::gc_reason)
    libcoreclr.so!WKS::gc_heap::trigger_full_compact_gc(WKS::gc_reason, oom_reason*)
    libcoreclr.so!WKS::gc_heap::allocate_small(int, unsigned long, alloc_context*, int)
    libcoreclr.so!WKS::gc_heap::try_allocate_more_space(alloc_context*, unsigned long, int)
    libcoreclr.so!WKS::gc_heap::allocate_more_space(alloc_context*, unsigned long, int)
    libcoreclr.so!WKS::gc_heap::allocate(unsigned long, alloc_context*)
    libcoreclr.so!WKS::GCHeap::Alloc(alloc_context*, unsigned long, unsigned int)
    libcoreclr.so!Alloc(unsigned long, int, int)
    libcoreclr.so!FastAllocatePrimitiveArray(MethodTable*, unsigned int, int)
    libcoreclr.so!JIT_NewArr1(CORINFO_CLASS_STRUCT_*, long)
    libcoreclr.so!JIT_NewArr1VC_MP_FastPortable(CORINFO_CLASS_STRUCT_*, long)
    System.Threading.Tasks.Dataflow.dll!System.Threading.Tasks.SingleProducerSingleConsumerQueue`1+Segment[[System.Int32, System.Private.CoreLib]]..ctor(Int32)
    System.Threading.Tasks.Dataflow.dll!System.Threading.Tasks.SingleProducerSingleConsumerQueue`1[[System.Int32, System.Private.CoreLib]]..ctor()
    System.Threading.Tasks.Dataflow.dll!System.Threading.Tasks.Dataflow.Internal.SourceCore`1[[System.Int32, System.Private.CoreLib]]..ctor(System.Threading.Tasks.Dataflow.ISourceBlock`1<Int32>, System.Threading.Tasks.Dataflow.DataflowBlockOptions, System.Action`1<System.Threading.Tasks.Dataflow.ISourceBlock`1<Int32>>, System.Action`2<System.Threading.Tasks.Dataflow.ISourceBlock`1<Int32>,Int32>, System.Func`4<System.Threading.Tasks.Dataflow.ISourceBlock`1<Int32>,Int32,System.Collections.Generic.IList`1<Int32>,Int32>)
    
**Looking at the source line from frame 8 it looks like we get back MAP_FAILED from mmap() and assert with the message "mmap() returned an abnormal value.\n"**

    (lldb) fr s 8
    frame #8: 0x00007fe6b7267c40 libcoreclr.so`::VirtualFree(lpAddress=0x00007fe621e2d000, dwSize=1617920, dwFreeType=16384) + 2192 at virtual.cpp:1844
    (lldb) fr v
    (LPVOID) lpAddress = 0x00007fe621e2d000
    (SIZE_T) dwSize = 1617920
    (DWORD) dwFreeType = 16384
    (BOOL) bRetVal = YES
    (CorUnix::CPalThread *) pthrCurrent = 0x00007fe5e0014170
    (UINT_PTR) StartBoundary = 140626387718144
    (SIZE_T) MemSize = 1617920
    (PCMI) pUnCommittedMem = 0x00000000010c1bf0
    (PAL_EnterHolder) __holder = (m_fEntered = NO, m_palError = 0)

    #if MMAP_DOESNOT_ALLOW_REMAP
            // if no double mapping is supported, 
            // just mprotect the memory with no access
            if (mprotect((LPVOID)StartBoundary, MemSize, PROT_NONE) == 0)
    #else // MMAP_DOESNOT_ALLOW_REMAP
            // Explicitly calling mmap instead of mprotect here makes it
            // that much more clear to the operating system that we no
            // longer need these pages.
    #if RESERVE_FROM_BACKING_FILE
            if ( mmap( (LPVOID)StartBoundary, MemSize, PROT_NONE,
                       MAP_FIXED | MAP_PRIVATE, gBackingFile,
                       (char *) StartBoundary - (char *) gBackingBaseAddress ) !=
                 MAP_FAILED )
    #else   // RESERVE_FROM_BACKING_FILE
            if ( mmap( (LPVOID)StartBoundary, MemSize, PROT_NONE,
                       MAP_FIXED | MAP_ANON | MAP_PRIVATE, -1, 0 ) != MAP_FAILED )
    #endif  // RESERVE_FROM_BACKING_FILE
    #endif // MMAP_DOESNOT_ALLOW_REMAP
            {
    #if (MMAP_ANON_IGNORES_PROTECTION && !MMAP_DOESNOT_ALLOW_REMAP)
                if (mprotect((LPVOID) StartBoundary, MemSize, PROT_NONE) != 0)
                {
                    ASSERT("mprotect failed to protect the region!\n");
                    pthrCurrent->SetLastError(ERROR_INTERNAL_ERROR);
                    munmap((LPVOID) StartBoundary, MemSize);
                    bRetVal = FALSE;
                    goto VirtualFreeExit;
                }
    #endif  // MMAP_ANON_IGNORES_PROTECTION && !MMAP_DOESNOT_ALLOW_REMAP

                SIZE_T index = 0;
                SIZE_T nNumOfPagesToChange = 0;

                /* We can now commit this memory by calling VirtualAlloc().*/
                index = (StartBoundary - pUnCommittedMem->startBoundary) / VIRTUAL_PAGE_SIZE;
                
                nNumOfPagesToChange = MemSize / VIRTUAL_PAGE_SIZE;
                VIRTUALSetAllocState( MEM_RESERVE, index, 
                                      nNumOfPagesToChange, pUnCommittedMem ); 
    #if MMAP_DOESNOT_ALLOW_REMAP
                VIRTUALSetDirtyPages( 1, index, 
                                      nNumOfPagesToChange, pUnCommittedMem ); 
    #endif // MMAP_DOESNOT_ALLOW_REMAP

                goto VirtualFreeExit;    
            }
            else
            {
                ASSERT( "mmap() returned an abnormal value.\n" );
                bRetVal = FALSE;
                pthrCurrent->SetLastError( ERROR_INTERNAL_ERROR );
                goto VirtualFreeExit;
            }

**Comment by janvorli** [comment]
mmap returning anormal value in this case is a problem with too many memory mappings. Linux has a default limit of 65530 memory mappings per process. 
The excessive mappings usually come from tests that use System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly with AssemblyBuilderAccess.Run parameter. It creates reflection modules, but never destroys them (by definition). So running such test in a loop in stress tests inevitably leads to exceeding the number of mappings.
This test suite contains such tests. A lot of System.Reflection.Emit tests seem to fall into this category.
You can recognize this issue from the core dump if you run sos eeheap command. In this case, it dumps hundreds of thousands of modules.
I believe we should exclude this kind of tests from the stress suites.

**Comment by schaabs** [comment]
System.Reflection.Emit tests have been excluded from test runs at the assembly level.
