### ISSUE TITLE
SIGABRT_ASSERT_libcoreclr.so!CorUnix::CPalThread::ThreadEntry

### ISSUE THREAD

**Issue by schaabs** [dotnet/coreclr#5516]
**The notes in this bug refer to the Ubuntu.14.04 dump [mnhh5ztw](https://rapreqs.blob.core.windows.net/sschaab/BodyPart_5315b3e6-7f56-4a1d-8896-fd92989e2c24?sv=2015-04-05&sr=b&sig=GnZYiXW3AvxBZBxjogx4digvftPsonSMVFMVBvOXlJ4%3D&st=2016-06-03T22%3A01%3A54Z&se=2017-06-03T22%3A01%3A54Z&sp=r).  Other dumps are available if needed.**

    STOP_REASON:
    SIGABRT

    FAULT_SYMBOL:
    libcoreclr.so!CorUnix::CPalThread::ThreadEntry

    FAILURE_HASH:
    SIGABRT_libcoreclr.so!CorUnix::CPalThread::ThreadEntry

    FAULT_STACK:
    libc.so.6!__GI_raise
    libc.so.6!__GI_abort
    libcoreclr.so!PROCAbort
    libcoreclr.so!sigtrap_handler(int, siginfo_t*, void*)
    libclrjit.so!sigtrap_handler(int, siginfo_t*, void*)
    libpthread.so.0!???
    libcoreclr.so!DBG_DebugBreak
    libcoreclr.so!DebugBreak
    libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*)
    libpthread.so.0!start_thread
    libc.so.6!__clone

    FAULT_THREAD:
    thread #1: tid = 5027, 0x00007fa33db4dcc9 libc.so.6`__GI_raise(sig=6) + 57 at raise.c:56, name = 'corerun', stop reason = signal SIGABRT
    
**Looking at the source for frame 8 it looks like pthread_getschedparam returned zero so it asserts with the message "Unable to get current thread scheduling information\n"**

    (lldb) fr s 8
    frame #8: 0x00007fa33d58e6fa libcoreclr.so`CorUnix::CPalThread::ThreadEntry(pvParam=0x00007fa244009090) + 1226 at thread.cpp:1690
    (lldb) fr v
    (CorUnix::CPalThread *) pvParam = 0x00007fa244009090
    (CorUnix::PAL_ERROR) palError = 8
    (CorUnix::CPalThread *) pThread = 0x00007fa244009090
    (PTHREAD_START_ROUTINE) pfnStartRoutine = 0x00007fa33e915338 (libpthread.so.0..bss + 56)
    (CorUnix::CPalThread *) pvPar = 0x00007fa24c01dd80
    (DWORD) retValue = 32674
    (PAL_EnterHolder) __holder = (m_fEntered = NO, m_palError = 0)
    
    
    /* get the previous thread schedule parameters.  We need to know the 
       scheduling policy to determine the priority range */
    if (pthread_getschedparam(
            pTargetThread->GetPThreadSelf(),
            &policy, 
            &schedParam
            ) != 0)
    {
        ASSERT("Unable to get current thread scheduling information\n");
        palError = ERROR_INTERNAL_ERROR;
        goto InternalSetThreadPriorityExit;
    }

**Comment by sergiy-k** [comment]
Hi @schaabs, could you please add a link to the crash dump for this issue? Thank you!

**Comment by schaabs** [comment]
@sergiy-k Sorry about that I've included it in the original comment of this issue

**Comment by sergiy-k** [comment]
The failure is due to OOM.  When PAL is starting a new thread, the  CPalThread::ThreadEntry function calls pThread->suspensionInfo.InternalSuspendNewThreadFromData(pThread) which returned ERROR_NOT_ENOUGH_MEMORY in this case. On debug builds we have an assert that checks the returned value. This assert caused a crash in this test. On a release build, the code will handle the error, prevent the new thread from being started and report an error to the caller.

**Comment by adityamandaleeka** [comment]
@sergiy-k Can we close this issue? I don't really think it's valuable to remove or modify that assert.
