### ISSUE TITLE
Enable Serviceable attribute for assemblies and Nuget packages

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#5530]
Details are in https://github.com/dotnet/corefx/issues/9072. We need to update:

1) CoreCLR package to have the attribute
2) Mscorlib and System.Private.CoreLib to have the Serviceable attribute.

@AlexGhiondea @weshaggard Is there anything else required?

CC @pgavlin @leecow 

@schellap Can you please take a look at this asap?

**Comment by joshfree** [comment]
@ericstj is there actual work to do here or was this handled by your previous change?

**Comment by ericstj** [comment]
Packages all have the attribute.  @schellap can you double check that your IL has the assembly level attribute?

**Comment by gkhanna79** [comment]
Associated PRs:

https://github.com/dotnet/coreclr/pull/5575
https://github.com/dotnet/coreclr/pull/5547
https://github.com/dotnet/coreclr/pull/5584

**Comment by gkhanna79** [comment]
> can you double check that your IL has the assembly level attribute?

@ericstj Do you expect mscorlib facade and system.private.corelib to have the assembly level attribute? If so, @AlexGhiondea would need to make the relevant changes if they are not already done.

CC @weshaggard

**Comment by schellap** [comment]
```
.custom instance void [System.Private.CoreLib]System.Reflection.AssemblyMetadataAttribute::.ctor(string,
                                                                                                   string) = ( 01 00 00 00 00 00 ) 
```

Where is the serviceable attribute stored? This is what I see in mscorlib.dll in the packages.

**Comment by schellap** [comment]
Here it is for `System.Private.CoreLib.dll` from `runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR.1.0.2-rc4-24208-03`.

```
  .custom instance void System.Reflection.AssemblyMetadataAttribute::.ctor(string,
                                                                           string) = ( 01 00 0B 53 65 72 76 69 63 65 61 62 6C 65 04 54   // ...Serviceable.T
                                                                                       72 75 65 00 00 )                                  // rue..
```

**Comment by gkhanna79** [comment]
My understanding is that assemblies, which need to be used on the Desktop, need to have these attributes.  If so, then mscorlib facade and SPC.dll of CoreCLR should not be getting used on the Desktop (they are not PLibs), so servicing attribute on them should not be required.

Is that correct @ericstj and @weshaggard?

**Comment by schellap** [comment]
`mscorlib.dll` facade does NOT have the serviceable attribute. However, System.Private.CoreLib RC3 and RC4 have the attribute.

**Comment by gkhanna79** [comment]
@ericstj Is there any action item here?

**Comment by ericstj** [comment]
> Is that correct @ericstj and @weshaggard?

Yeah, if CoreCLR repo is not producing any assemblies which support deskop then you don't need the attribute.

**Comment by gkhanna79** [comment]
I dont believe there is any. @AlexGhiondea Can you confirm?

**Comment by AlexGhiondea** [comment]
The only managed assemblies we produce are System.Private.CoreLib.dll and the mscorlib.dll facade which are not going to be consumed on Desktop.

**Comment by schellap** [comment]
Closing...
