### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80070057

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/coreclr#5541]
On Linux, I have a system where if I use corerun my_program.exe everything works fine. However if I do `dotnet exec my_program.exe` it fails with:

```Failed to initialize CoreCLR, HRESULT: 0x80070057```

Now I found out a workaround, but I'd like to understand why it works with just `corerun`. 

The issue is that my program has a bunch of pinvoke calls to native libraries from /usr/lib, so to make them work, I've created symbolic links to them from where `my_program.exe` is. So it looks like this:

```
lrwxrwxrwx  1 ubuntu ubuntu      40 Jun  7 08:41 freetype.dll -> /usr/lib/x86_64-linux-gnu/libfreetype.so
-rwxrw-r--  1 ubuntu ubuntu     135 May 25 15:00 my_program.runtimeconfig.json
-rwxrwx---  1 ubuntu ubuntu   22688 Jun  6 17:41 my_program.exe
```

Turns out that `dotnet exec` doesn't like the symbolic link if present and fails immediately on launch. If I actually copy the shared library, then it works fine.

The runtimeconfig.json files is required for dotnet exec and its content is:
```
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.0.0-preview1-002702"
    }
  }
}
```

Any idea on how to avoid the failure or the need to use copy the shared library?

Thanks!

PS: This came after a few trials to make my program run under dotnet-cli, see https://github.com/dotnet/cli/issues/3232

**Comment by gkhanna79** [comment]
Why is the symlink having extension as .DLL (that is, for sure, not supported on non-Windows as valid pinvoke target extension)?

**Comment by manu-silicon** [comment]
It is called with the .dll extension because this is the name in the DllImport attribute. What should be the recommended name to put in the DllImport custom attribute so that one assembly would work the same on both Unix and Windows?

**Comment by sergiy-k** [comment]
I think you should be able to specify just the name of the library without extension (for example, "freetype" in your case).

**Comment by manu-silicon** [comment]
I definitely should do that and report if this changes anything. Thanks!

**Comment by manu-silicon** [comment]
It certainly fixes the issue as it now loads the native library. However I still need the symbolic link as some native libraries have completely different names between Unix and Windows and I do not necessarily want to have 2 versions of the same assembly only differing by the string provided in DllImport.

I'll check if the symbolic link works if the name of the shared library is .so instead of .dll.

**Comment by manu-silicon** [comment]
I'm not experiencing this problem anymore. Not sure if this is because now I'm using the native shared library extensions of the underlying platform or  if this was fixed in the released version of .NET Core I installed.
