### ISSUE TITLE
[ARM/Linux]  undefined symbol s_forcedGCInProgress

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#5546]
On ARM/Linux, running "Hello, world" app shows the following error message if I use CoreCLR built from 3a4711b18816:
```
dlopen failed to open the libcoreclr.so with error /mnt/dotnet-latest/Linux.arm.Debug/libcoreclr.so: undefined symbol: s_forcedGCInProgress
```

**Comment by adityamandaleeka** [comment]
Looks like the problem is a combination of:

```cmake
if(CLR_CMAKE_PLATFORM_LINUX AND CLR_CMAKE_TARGET_ARCH_AMD64)
  set(FEATURE_EVENT_TRACE 1)
endif()
```
(https://github.com/dotnet/coreclr/blob/master/clrdefinitions.cmake#L10)

and 

```cmake
if(FEATURE_EVENT_TRACE)
    list(APPEND VM_SOURCES_WKS
        eventtrace.cpp
        )
endif(FEATURE_EVENT_TRACE)
```
(https://github.com/dotnet/coreclr/blob/master/src/vm/CMakeLists.txt#L253)

and the fact that that variable is defined in eventtrace.cpp.

@davmason

**Comment by parjong** [comment]
@adityamandaleeka @davmason It seems that FEATURE_EVENT_TRACE is not set on ARM/Linux, but 223256668d2c73d2ca2a54a1 introduces the reference on s_forcedGCInProgress in ``vm/finalizerthread.cpp``. Is it possible to disable those changes if FEATURE_EVENT_TRACE is not set?

**Comment by parjong** [comment]
@adityamandaleeka @davmason I can run "Hello, World" app on ARM/Linux with PR #5550. Please take a look.

**Comment by leemgs** [comment]
@prajwal-aithal , Please take a look.  It seems that we have still been experiencing the regression issues because of  the lack of the Linux/ARM CI.
\CC: @myungjoo

**Comment by prajwal-aithal** [comment]
@leemgs ARM CI can only prevent build errors. As I gather from the information posted above, this is not a build error (rather a runtime error). This cannot be prevented using CI check.

**Comment by leemgs** [comment]
> https://github.com/dotnet/coreclr/pull/5550

Acked-by: Geunsik Lim <geunsik.lim@samsung.com>

* Before 5550:
```
arm-emnul# time ./corerun ../../example/hello.exe/runtime-arm-u1404-release-mode-201606
dlopen failed to open the libcoreclr.so with error /nfs/runtime-collect-ubuntu-arm/runtime-arm-u1404-release-mode-20160607/libcoreclr.so: undefined symbol: s_forcedGCInProgress

real	0m1.122s
user	0m0.070s
sys	0m0.050s
```

* After 5550:
```
arm-emnul# time ./corerun ../../example/hello.exe/runtime-arm-u1404-release-mode-201606
Hello World

real	0m5.070s
user	0m2.250s
sys	0m0.330s
```

**Comment by mkborg** [comment]
@prajwal-aithal to catch runtime errors ARM CI shall execute tests
