### ISSUE TITLE
RuyJIT: structs in parameters and enregistering

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#5556]
When we pass a struct by value JIT makes a copy in the stack of the caller and passes ref to the callee.

I see an  opportunity for JIT to enregister fields of such params as it does when the params are explicitly copied to  locals of the callee.

Here is an example with `Span<T>` from[ CoreFxLab's Slices](https://github.com/dotnet/corefxlab/blob/master/src/System.Slices/System/Span.cs#L19).

``` C#
[MethodImpl(MethodImplOptions.NoInlining)]
public static long SpanAsParam(Span<long> span)
{
    long value = 0;
    for (int i = 0; i < span.Length; i++)
    {
        value = span[i];
    }
    return value;
}

[MethodImpl(MethodImplOptions.NoInlining)]
public static long SpanWithLocalCopy(Span<long> span)
{
    var spanLocal = span;
    long value = 0;
    for (int i = 0; i < spanLocal.Length; i++)
    {
        value = spanLocal[i];
    }
    return value;
}

```

``` ASM
; SpanAsParam

000000 sub      rsp, 40
000004 xor      rax, rax
000006 xor      edx, edx
000008 cmp      dword ptr [rcx+16], 0
00000C jle      SHORT G_M48226_IG05
G_M48226_IG03:
00000E mov      eax, dword ptr [rcx+16]
000011 cmp      edx, eax
000013 jae      SHORT G_M48226_IG06
000015 mov      rax, gword ptr [rcx]
000018 mov      r8, qword ptr [rcx+8]
00001C movsxd   r9, edx
00001F add      rax, r8
000022 mov      rax, qword ptr [rax+8*r9]
000026 inc      edx
000028 cmp      edx, dword ptr [rcx+16]
00002B jl       SHORT G_M48226_IG03
G_M48226_IG05:
00002D add      rsp, 40
000031 ret      
G_M48226_IG06:
000032 call     System.Contract:NewArgumentOutOfRangeException():ref
000037 mov      rcx, rax
00003A call     CORINFO_HELP_THROW
00003F int3     

; Total bytes of code 64, prolog size 4
```

``` ASM
; SpanWithLocalCopy

000000 sub      rsp, 40
000004 mov      rax, gword ptr [rcx]
000007 mov      rdx, qword ptr [rcx+8]
00000B mov      ecx, dword ptr [rcx+16]
00000E xor      r8, r8
000011 xor      r9d, r9d
000014 test     ecx, ecx
000016 jle      SHORT G_M48226_IG05
G_M48226_IG03:
000018 cmp      r9d, ecx
00001B jae      SHORT G_M48226_IG07
00001D movsxd   r8, r9d
000020 mov      r10, rax
000023 add      r10, rdx
000026 mov      r8, qword ptr [r10+8*r8]
00002A inc      r9d
00002D cmp      r9d, ecx
000030 jl       SHORT G_M48226_IG03
G_M48226_IG05:
000032 mov      rax, r8
000035 add      rsp, 40
000039 ret      
G_M48226_IG07:
00003A call     System.Contract:NewArgumentOutOfRangeException():ref
00003F mov      rcx, rax
000042 call     CORINFO_HELP_THROW
000047 int3     

; Total bytes of code 72, prolog size 4
```

**Comment by RussKeldorph** [comment]
@CarolEidt @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
@omariom this is something that would be part of [First Class Structs](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/first-class-structs.md), see work item 9 [here](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/first-class-structs.md#dependent-work-items). I will add a reference to this issue.

**Comment by pgavlin** [comment]
@CarolEidt is this issue sufficiently tracked by first class structs s.t. we can close it, or would you prefer to leave it open for tracking?

**Comment by CarolEidt** [comment]
> is this issue sufficiently tracked by first class structs s.t. we can close it, or would you prefer to leave it open for tracking?

I would like to continue to leave this open. Indeed, I had originally planned to open individual issues for all of the work items listed in  [First Class Structs](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/first-class-structs.md), since I think they are easier to find, and of a more appropriate granularity than having a single issue for all of the struct-related perf issues.

**Comment by pgavlin** [comment]
SGTM; thanks!

**Comment by CarolEidt** [comment]
@omariom - The code generated for this has improved, as now the bounds check is eliminated, and it appears that the loop body is the same for most targets except for x86, where it is impacted by the restriction of not promoting incoming arguments with more than a single field.

**Comment by omariom** [comment]
@CarolEidt
