### ISSUE TITLE
Bytemark benchmarks Linux vs. Windows

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#5559]
Several Bytemark benchmarks show double-digit perf difference Linux vs. Windows (lower number is better in the table below). The data was collected using xunit-perf.
OS versions: Windows 10 Enterprise OS Build 10586.218 and Ubuntu 14.04 LTS

| Benchmark | Windows | Margin of error | Linux | Margin of error | (L - W) / W |
| --- | --- | --- | --- | --- | --- |
| Bytemark.BenchBitOps | 879 | 0.62% | 978 | 0.83% | 11.26% |
| Bytemark.BenchEmFloatClass | 1040 | 1.23% | 930 | 0.14% | -10.58% |
| Bytemark.BenchLUDecomp | 1120 | 0.63% | 1300 | 0.42% | 16.07% |
| Bytemark.BenchAssignJagged | 882 | 0.51% | 1160 | 0.18% | 31.52% |
| Bytemark.BenchEmFloat | 1000 | 0.09% | 931 | 0.07% | -6.90% |
| Bytemark.BenchAssignRectangular | 1670 | 0.36% | 1560 | 0.28% | -6.59% |
| Bytemark.BenchStringSort | 1030 | 0.29% | 1040 | 0.25% | 0.97% |
| Bytemark.BenchFourier | 1030 | 0.07% | 1220 | 0.07% | 18.45% |
| Bytemark.BenchIDEAEncryption | 1100 | 0.07% | 1220 | 0.07% | 10.91% |
| Bytemark.BenchNeuralJagged | 1180 | 0.12% | 1700 | 0.18% | 44.07% |
| Bytemark.BenchNumericSortRectangular | 1070 | 0.31% | 1320 | 0.06% | 23.36% |
| Bytemark.BenchNumericSortJagged | 995 | 0.19% | 1260 | 0.13% | 26.63% |
| Bytemark.BenchNeural | 1020 | 0.12% | 936 | 0.10% | -8.24% |

**Comment by BruceForstall** [comment]
It would be useful re-collecting this data as part of a general performance push. However, this issue is stale; closing.
