### ISSUE TITLE
Raspberry Pi 3 - Segmentation fault

### ISSUE THREAD

**Issue by techyian** [dotnet/coreclr#5561]
Hi,

I've tried building from source on my Raspberry Pi 3 and receive a Seg Fault in corhlpr.h within the struct COR_ILMETHOD referencing line 610. I've followed the build instructions and have also built libunwind from source which includes the required change mentioned to prevent access to inaccessible memory. This is using the latest Raspbian build.

I appreciate that ARM is still not fully supported. Has anyone had any success with building coreclr on the pi yet? Possibly with the Pi 2?

Thanks,

Ian

**Comment by shahid-pk** [comment]
yes people are building coreclr on Pi 2 with good success for example see this issue for the progress https://github.com/dotnet/coreclr/issues/3977

**Comment by techyian** [comment]
It's good to know there's success with the Pi 2. I'd be interested to find out whether anyone else has a Pi 3 and are having similar problems?

**Comment by cyplo** [comment]
Hi, is this still an issue ?

**Comment by jkotas** [comment]
The current RPi instructions are at: https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md .  It has been running on my RPi3 just fine.
