### ISSUE TITLE
baseservices\threading\mutex\openexisting\openmutexpos4 failing under gcstress 0xf+Ready2Run

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#5562]
**Environment**
Windows x64
COMPlus_gcstress=0xf
RunCrossGen=1
**Output**
```
BEGIN EXECUTION
" C:\michelm\dotnet-coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\crossgen.exe" /Platform_Assemblies_Paths C:\michelm\dotnet-coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root;C:\michelm\dotnet-coreclr\bin\tests\Windows_NT.x64.Checked\baseservices\threading\mutex\openexisting\openmutexpos4\ openmutexpos4.exe
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image C:\michelm\dotnet-coreclr\bin\tests\Windows_NT.x64.Checked\baseservices\threading\mutex\openexisting\openmutexpos4\openmutexpos4.ni.exe generated successfully.
 "C:\michelm\dotnet-coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" openmutexpos4.exe
Inside thread which creates a mutex
Waiting to reuse mutex
Mutex created
Error, created new mutex!
Mutex reused True
Test failed
Expected: 100
Actual: 97
END EXECUTION - FAILED
FAILED
```

**Comment by RussKeldorph** [comment]
@gkhanna79 FYI.  We've got one machine that repros this locally and one that doesn't.  Still trying to get a consistent repro locally, but this came from http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/x64_release_windows_nt_gcstress15_pri1r2r/6/testReport/junit/baseservices/_threading_mutex_openexisting_openmutexpos4_openmutexpos4_/_threading_mutex_openexisting_openmutexpos4_openmutexpos4_cmd/

On the machine where it repros, it repros without both R2R and GCStress.

**Comment by RussKeldorph** [comment]
I think this is just a bad test.  It depends on the outcome of a race.

**Comment by wtgodbe** [comment]
@RussKeldorph do you think we should just get rid of this test?

**Comment by RussKeldorph** [comment]
@wtgodbe The most important thing is that the test not spuriously fail.  If you can't achieve that and still have it test something useful, yes, it should be deleted.  @sergiy-k had this suggestion: "one thing to try would be to store the mutex object created by CreateMutexThread() in a static field or to add KeepAlive() at the end of the method."

**Comment by wtgodbe** [comment]
@RussKeldorph how can I get access to the machine where this repros locally? I can't produce a repro on my machine.

**Comment by RussKeldorph** [comment]
@wtgodbe I believe the VM running the job I linked above has been reclaimed.  You could ask @mmitche how to get access to one like it.  You could also reach out to @adiaaida to see if she can provide access to her machine.  Those are the only places I've seen it repro.

That said, I would think it would be sufficient for your purposes to force the repro on your machine by modifying the test slightly.  I'm able to provoke it by introducing a delay in ReuseMutexThread immediately before the Mutex constructor.  Both Thread.Sleep and a busy loop on a volatile work.  I don't know why either of those techniques would invalidate the repro or do anything more than make the outcome of the race more consistent, but I could be missing something.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/5713 should resolve this.
