### ISSUE TITLE
CI R2R testing should be fixed to produce R2R images without the .ni.* extension, and replace the IL image with the generated R2R image

### ISSUE THREAD

**Issue by fadimounir** [dotnet/coreclr#5567]
This is in order to test the shipping configuration. We don't ship .ni.dll R2R images placed next to their IL images, we just replace the IL images with the generated R2R images, using the same exact file name.

(Related to issue #5537)

**Comment by gkhanna79** [comment]
@fadimounir PTAL :)

**Comment by fadimounir** [comment]
Note: Need to look at runtest.[cmd|sh] on how they process the –docrossgen and –runcrossgen arguments.

**Comment by gkhanna79** [comment]
@wtgodbe Can this be closed?

**Comment by wtgodbe** [comment]
Yes
