### ISSUE TITLE
coredistools isn't restoring for OSX

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#5602]
This prevents GCStress=C jobs from running successfully, e.g. http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/x64_checked_osx_gcstress0xc_tst/2/testReport

From the log:
```
22:02:23 Downloading CoreDisTools package
[snip]
22:02:24 + exit_with_error 1 'Failed to restore the package'
```

**Comment by RussKeldorph** [comment]
@jashook please work with @swaroop-sridhar to sort this out.

**Comment by swaroop-sridhar** [comment]
OSX packages available in the dotnet-core feed were for osx.10.10.
I've now pushed the packages for osx.10.11

**Comment by swaroop-sridhar** [comment]
I've submitted a new job: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/x64_checked_osx_gcstress0xc_tst/3

pending execution
