### ISSUE TITLE
Limit what's stripped from OS X Release binaries

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/coreclr#5608]
Binaries built in Release configuration on OS X have so much information stripped from them (even more than we strip on Linux) that we are making the diagnostic experience unnecessarily difficult. For instance, you can't even see function names by default when debugging or profiling release mode binaries.

With a small change to the arguments we pass to `strip`, we can remove only the debugging symbol table entries, but keep the function name information intact. This has a small impact on binary size (for instance, a stripped libcoreclr.dylib is ~76% of its original size rather than ~62%).

The change enables some useful functionality including (but not limited to) the following: LLDB will be able to set function breakpoints in Release binaries with no additional setup, otool will be able to display disassembled operands symbolically, and Instruments will be able to show function names automatically without needing to locate and load dSYM files (which is currently a manual step because of the way CoreCLR dSYMs are created).

@sergiy-k

**Comment by sergiy-k** [comment]
https://github.com/dotnet/coreclr/pull/5586
