### ISSUE TITLE
[Arm64] Debugger Test AV in clr callstack

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#5615]
STDERROR: 35.887: 
    STDERROR: 35.887: Assert failure(PID 12920 [0x00003278], Thread: 10324 [0x2854]): Consistency check failed: AV in clr at this callstack:
    STDERROR: 35.887: ------
    STDERROR: 35.887: CORECLR! ComInterfaceSlotIs + 0x1DC (0x00007ff8`1ab94bc4)
    STDERROR: 35.887: CORECLR! GetCCWFromIUnknown + 0x470 (0x00007ff8`1ac8d040)
    STDERROR: 35.887: CORECLR! GetObjectRefFromComIP + 0x550 (0x00007ff8`1afc1060)
    STDERROR: 35.887: CORECLR! FieldMarshaler_Interface::UpdateCLRImpl + 0x388 (0x00007ff8`1b2f53a0)
    STDERROR: 35.887: CORECLR! FieldMarshaler::UpdateCLR + 0x100 (0x00007ff8`1b2f3020)
    STDERROR: 35.887: CORECLR! LayoutUpdateCLR + 0x31C (0x00007ff8`1b2e8a2c)
    STDERROR: 35.887: CORECLR! MarshalNative::PtrToStructureHelper + 0x3E4 (0x00007ff8`1b2d80e4)
    STDERROR: 35.887: SYSTEM.PRIVATE.CORELIB.NI! <no symbol> + 0x0 (0x00007ff8`18caeeb8)
    STDERROR: 35.903: <no module>! <no symbol> + 0x0 (0x00007ff7`bbed4290)
    STDERROR: 35.903: -----
    STDERROR: 35.903: .AV on tid=0x2854 (10324), cxr=0000004FA4BFCB70, exr=0000004FA4BFCF00
    STDERROR: 35.903: FAILED: false
    STDERROR: 35.903: 
    STDERROR: 35.903: CORECLR! CHECK::Trigger + 0x2C4 (0x00007ff8`1b3b3b04)
    STDERROR: 35.903: CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x224 (0x00007ff8`1acd028c)
    STDERROR: 35.903: CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x68 (0x00007ff8`1accfd40)
    STDERROR: 35.903: CORECLR! CLRVectoredExceptionHandler + 0x18C (0x00007ff8`1accfc2c)
    STDERROR: 35.903: CORECLR! CLRVectoredExceptionHandlerShim + 0xC8 (0x00007ff8`1acd0590)
    STDERROR: 35.903: NTDLL! RtlIsProcessorFeaturePresent + 0x1D8 (0x00007ff8`4f3a6f88)
    STDERROR: 35.903: NTDLL! RtlLogStackBackTrace + 0x198 (0x00007ff8`4f40b1d8)
    STDERROR: 35.903: NTDLL! KiUserExceptionDispatcher + 0x28 (0x00007ff8`4f3821c8)
    STDERROR: 35.903: CORECLR! ComInterfaceSlotIs + 0x1DC (0x00007ff8`1ab94bc4)
    STDERROR: 35.903: CORECLR! GetCCWFromIUnknown + 0x470 (0x00007ff8`1ac8d040)
    STDERROR: 35.903:     File: f:\dd\ndp\clr\src\vm\excep.cpp Line: 8141

**Comment by ramarag** [comment]
This bug actually occurs on the debugger and not the debugee, will update with more info soon

**Comment by rahku** [comment]
Marshalling hints for Arm64Context in mdbg were incorrect. nested type Arm64FloatingPointRegisters inside Arm64Context should be maked as struct and not class. Also there isn't a need to do explicit layout of fields for Arm64Context. Making above changes fixes this error.
