### ISSUE TITLE
Preprocessor directives not respected

### ISSUE THREAD

**Issue by Auersberg** [dotnet/coreclr#5634]
I am developing and supporting a library project (https://github.com/blackcity/backload). Some people at Microsoft also use this component ;-). In this project we target multiple framework flavors (net40, net45, net451, netcoreapp1.0). The component usually runs in an ASP.NET environment which uses the libraries.
The component consists of two core libraries: The main assembly implements the business logic while the second assembly includes almost only interfaces or contracts to be used by the main assembly, third party applications or plugins.

We use Visual Studio with the latest .NET Core SDK and the new project types (project.json).
To enable multi targeting we use some preprocessor directives. E.g. for net40 and net45 we need `System.Web.HttpRequestBase` for net451 or netcoreapp1.0 targets we need `Microsoft.AspNetCore.Http.HttpRequest`. In our project.json file we set these targets exactly with the TFM mentíoned before. So, our code is straight forward and looks like this:

<pre>
// Backload.Contracts.dll (interfaces):
public interface IWebContext
{
#if !(NET40 || NET45)
    Microsoft.AspNetCore.Http.HttpRequest Request { get; set; } 
#else
    System.Web.HttpRequestBase Request { get; set; } 
#endif
}

// Backload.dll (implementation):
public class WebContext : IWebContext
{
#if !(NET40 || NET45)
    public Microsoft.AspNetCore.Http.HttpRequest Request { get; set; } 
#else
    public System.Web.HttpRequestBase Request { get; set; } 
#endif
}
</pre>

The problem: When compiling we get errors in the main library (backload.dll) complaining that it is not implementing `System.Web.HttpRequestBase` for net451 and netcoreapp1.0 targets where we need `Microsoft.AspNetCore.Http.HttpRequest`. The strange thing is, when we package the interface assembly (Backload.Contracts.dll) and reference the NuGet package instead of the code directly, everything is ok. So, the problem occurs when we reference a second project (source code) not a NuGet package.

It seems, that the compiler always uses net40 target output of the interface code while compiling a different target in the main (referencing) code. Are we missing something?

**Comment by AndyAyersMS** [comment]
@Auersberg is  this still an issue? If so we should move it over to the SDK repo.

**Comment by Auersberg** [comment]
Found a way around this issue. You can close it.
