### ISSUE TITLE
ARM64 R2R: Could not load file or assembly RMV-4-CA

### ISSUE THREAD

**Issue by kyulee1** [dotnet/coreclr#5643]
Loader\classloader\rmv\il\RMV-4-1-6a\RMV-4-1-6a.cmd
Loader\classloader\rmv\il\RMV-4-1-6b\RMV-4-1-6b.cmd
Loader\classloader\rmv\il\RMV-4-1-6d\RMV-4-1-6d.cmd
Loader\classloader\rmv\il\RMV-4-1-6d-two\RMV-4-1-6d-two.cmd
Loader\classloader\rmv\il\RMV-4-1-6e\RMV-4-1-6e.cmd
Loader\classloader\rmv\il\RMV-4-2-4\RMV-4-2-4.cmd
Loader\classloader\rmv\il\RMV-4-1-6e-two\RMV-4-1-6e-two.cmd
Loader\classloader\rmv\il\RMV-4-3-4\RMV-4-3-4.cmd
Loader\classloader\rmv\il\RMV-4-2-4-two\RMV-4-2-4-two.cmd
Loader\classloader\rmv\il\RMV-4-3-7\RMV-4-3-7.cmd
Loader\classloader\rmv\il\RMV-4-3-4-two\RMV-4-3-4-two.cmd
Loader\classloader\rmv\il\RMV-4-3-7-two\RMV-4-3-7-two.cmd
Loader\classloader\rmv\il\RMV-4-3-8\RMV-4-3-8.cmd
```
BEGIN EXECUTION
" C:\Users\ddjoin\scratch\crossgen.exe" /Platform_Assemblies_Paths C:\Users\ddjoin\scratch;C:\Users\ddjoin\CoreClrTests-afa7fe5486fc90fec7df52bd134b789c568c8b45\Loader\classloader\rmv\il\RMV-4-1-6d-two\ RMV-4-1-6d-two.exe
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Error: Could not load file or assembly 'RMV-4-CA, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. (Exception from HRESULT: 0x80070002 (COR_E_FILENOTFOUND))
Error compiling RMV-4-1-6d-two.exe: Could not find or load a specific file. (Exception from HRESULT: 0x80131621 (COR_E_FILELOAD))
Error: compilation failed for "RMV-4-1-6d-two.exe" (0x80131621)
Crossgen failed with exitcode - -2146232799
```

**Comment by gkhanna79** [comment]
I think these were go away once you refresh the test build since @fadimounir cleaned these up.

**Comment by fadimounir** [comment]
@kyulee1 these tests no longer exist. I recently deleted them.

**Comment by kyulee1** [comment]
Okay. Will update test binaries.

**Comment by kyulee1** [comment]
Fixed via https://github.com/dotnet/coreclr/pull/5667
