### ISSUE TITLE
Functions to port to managed code

### ISSUE THREAD

**Issue by TimLovellSmith** [dotnet/coreclr#565]
Was reading the Book of the Runtime and noted:

"We have ported some parts of the CLR that were heavily reliant on FCalls to managed code in the past (such as Reflection and some Encoding & String operations), and we want to continue this momentum. We may port our number formatting & String comparison code to managed in the future."

I think you need an issue here to track discussion of what are good things that you would like to be ported to managed.

e.g. what are the number formatting functions the above is referring to: would those be Int32ToDecStr, Int64ToHexStr and their ilk?

**Comment by jkotas** [comment]
The simple answer is all of them.

We have most of the managed ports done internally for .NET Native. Open sourcing them is not a priority for the team at the moment, but do plan to get to it (no timeline yet).

cc @weshaggard @migueldeicaza

**Comment by TimLovellSmith** [comment]
OK, so basically you are not looking for any contributions to address this.

**Comment by weshaggard** [comment]
@TimLovellSmith thanks for your interest but most (if not all) of that work is already done as part of our .NET Native effort. Later once our plans around .NET Native become clearer we will open up that source code.
