### ISSUE TITLE
Profiling API Documentation: Using certain enumerations in SetEventMask will crash the program

### ISSUE THREAD

**Issue by mjsabby** [dotnet/coreclr#5659]
I'm not sure we can fix this for RTM, but at least document that these enumerations will fatally end the target process.

I found this when I was doing (#4312 -- Enable ReJIT on all platforms)

Using any of these enumerations on Linux failed to start the program.

`COR_PRF_DISABLE_ALL_NGEN_IMAGES`
`COR_PRF_USE_PROFILE_IMAGES`
`COR_PRF_REQUIRE_PROFILE_IMAGE`

I'm guessing we will document which enumerations we've tested to work (and for which platform, etc.), but having a list of what absolutely will not work is helpful, since we expect other enumerations to work, but can't promise or guarantee it.

**Comment by mjsabby** [comment]
cc @noahfalk @kspawa

**Comment by kspawa** [comment]
Thanks Mukul! I have already sent a PR with the document I am planning to start and all this information will be invaluable. Please feel free to provide feedback to the format of the document if you find other sections required. Thanks!

**Comment by lt72** [comment]
This should be fixed, please re-open if you find out it is still causing troubles.
