### ISSUE TITLE
ARM64 GCStress: Corrupt SyncBlock

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#5674]
```
TEST_CMD_LINE: JIT\Generics\Typeof\class01> D:\coreclr\bin\tests\Windows_NT.arm64.Debug\JIT\Generics\Typeof\class01\class01.cmd 

BEGIN EXECUTION
 "D:\coreclr\bin\tests\Windows_NT.arm64.Debug\Tests\Core_Root\corerun.exe" class01.exe 

Assert failure(PID 652 [0x0000028c], Thread: 5984 [0x1760]): SyncTableEntry::GetSyncTableEntry()[sbIndex].m_Object == obj

CORECLR! ObjHeader::Validate + 0x4EC (0x00007ff8`6fe9a6bc)
CORECLR! Object::ValidateInner + 0x1A8 (0x00007ff8`6fdcd5e8)
CORECLR! Object::Validate + 0xD8 (0x00007ff8`6fdccd28)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x330 (0x00007ff8`709c8230)
CORECLR! GcInfoDecoder::ReportSlotToGC + 0x10C (0x00007ff8`709c85e4)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x1178 (0x00007ff8`709c67a8)
CORECLR! EECodeManager::EnumGcRefs + 0x554 (0x00007ff8`705105ec)
CORECLR! GcStackCrawlCallBack + 0x4D0 (0x00007ff8`704f6240)
CORECLR! Thread::MakeStackwalkerCallback + 0x70 (0x00007ff8`6fec85e8)
CORECLR! Thread::StackWalkFramesEx + 0x188 (0x00007ff8`6fecbf88)
    File: d:\coreclr\src\vm\syncblk.cpp Line: 2530
    Image: D:\coreclr\bin\tests\Windows_NT.arm64.Debug\Tests\Core_Root\CoreRun.exe
```

Repro steps in #3825

**Comment by adiaaida** [comment]
We are also seeing this issue in x86.

**Comment by sdmaclea** [comment]
This ia a symptom of a garbage collector hole.  Several of these were fixed by the GC hole PRś currently open.  @jashook I believe this can close when the GC Hole PRs land

**Comment by Maoni0** [comment]
Taking off the area-GC tag as this is most likely a GC hole.

**Comment by danmosemsft** [comment]
needs to be area- something. Tizen I guess

**Comment by sdmaclea** [comment]
@danmosemsft JIT is probably generatinig incorrect GCInfo, so should be area JIT

**Comment by RussKeldorph** [comment]
I assume the x86 issue was fixed so this is ARM64-specific.

**Comment by AndyAyersMS** [comment]
Would be nice to know if this still repros.

**Comment by sdmaclea** [comment]
I have not seen this particular failure on Linux-arm64, but I haven't ever tried setting 
```
set COMPlus_GCStressOnDirectCalls=1
set COMPlus_SOProbeAssertOnOverrun=1
```

Looks like GCStressOnDirectCalls doesn't exist in the code anymore

**Comment by AndyAyersMS** [comment]
it is a runtime config setting. It triggers new behavior in gcover.cpp.

**Comment by BruceForstall** [comment]
@AndyAyersMS I'm inclined to close this under the assumption that we have good arm64 (and other arch) coverage in Jenkins now. Comments?

As for the the question about `COMPlus_GCStressOnDirectCalls=1`:

- is it important?
- if so, why is it not the default?
- if so, should we always set it, or should we add a new CI job for it? (in combination with ???)

**Comment by AndyAyersMS** [comment]
Agree we can close this. `GCStressOnDirectCalls` is now always on by default: see #8241 (though it evidently can be improved -- see large comment block above `GCCoverageInfo::SprinkleBreakpoints`).

We should remove the option as it doesn't do anything.
