### ISSUE TITLE
Comment - what is FEATURE_BASICFREEZE all about?

### ISSUE THREAD

**Issue by TimLovellSmith** [dotnet/coreclr#568]
There's the #ifdefs looking for it, but I didn't see a #define for it. I guessed but wrongly that I would find the explanation of what it does or who uses it in gc.h or gcpriv.h. Does it need to be maintained?

**Comment by jkotas** [comment]
This feature allowed freezing string literals and other simple objects in native images. More details are in https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.stringfreezingattribute.aspx

It was deprecated for full framework and CoreCLR, but it is used in other runtimes that share the same GC. It needs to be maintained under src\gc\... only.

cc @Maoni0

**Comment by jkotas** [comment]
@TimLovellSmith Could you please submit a PR that with explanation comment, if you see a good place for it?

**Comment by TimLovellSmith** [comment]
Which way should understand this: are those other runtimes 'forks' of coreclr, or are they taking a 'dependency' on coreclr code where they occasionally snap to coreclr code?

Is this kind of dependency one of the reasons why things like reorganizing gc.cpp is being frowned on by some folks? (referring to https://github.com/dotnet/coreclr/issues/408 )

**Comment by jkotas** [comment]
The other runtimes snap copy of the GC sources regularly.

**Comment by MattWhilden** [comment]
@TimLovellSmith It looks like this question has been answered so I'll close this out. Let me know if this is in error.
