### ISSUE TITLE
Test failed: Loader\classloader\explicitlayout\objrefandnonobjrefoverlap\case15: Cannot print exception string because Exception.ToString() failed

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#5686]
I was not able to repro this.  Opening the issue to note the failure for reference in case it is seen again.

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_jitstressregs0x10_tst/lastCompletedBuild/testReport/

```
BEGIN EXECUTION /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_jitstressregs0x10_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun case15.exe
Unhandled Exception: Cannot print exception string because Exception.ToString() failed.
./case15.sh: line 108: 5451 Aborted (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" case15.exe $CLRTestExecutionArguments
Expected: 100
Actual: 134
END EXECUTION - FAILED
```

**Comment by RussKeldorph** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/2850/testReport/junit/Loader.classloader.explicitlayout.objrefandnonobjrefoverlap/case14/case14/

**Comment by gkhanna79** [comment]
@adityamandaleeka Similar to the other issue you have seen? Did it repro recently?

**Comment by BruceForstall** [comment]
stale;closing
