### ISSUE TITLE
ARM64: !gcinfo does not work

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#5705]
neither !gcinfo nor !u -gcinfo seems to be working for me

**Comment by ramarag** [comment]
Could you add more details like what you expected and what was missing ?

**Comment by rahku** [comment]
from jit dump i can see that the method Xunit.ConsoleClient.CommandLine:Parse(ref):ref:this does have gcinfo but !u -gcinfo does not report it. So i am skeptical if it works for any method. If you do get the correct data for trivial methods....I can provide repro details for this.

**Comment by rahku** [comment]
while you are at it ...can you also look into @kyulee1 last comment in this PR https://github.com/dotnet/coreclr/pull/5694/files/73528790be5bf318af49ee457f6b5dad003f94db#r66682143

**Comment by ramarag** [comment]
replied in https://github.com/dotnet/coreclr/pull/5694#discussion_r66684166
