### ISSUE TITLE
SIGSEGV_libcoreclr.so!WKS::gc_heap::a_fit_segment_end_p

### ISSUE THREAD

**Issue by schaabs** [dotnet/coreclr#5709]
**Notes in this dump are for Ubuntu 14.04 core file [rc3-24209-01_0001](https://rapreqs.blob.core.windows.net/dotnetbot/BodyPart_9e733e9c-48c0-4e65-aac9-15c2b91d3a39?sv=2015-04-05&sr=b&sig=A3zVRRJ2MR0%2Fhjq17QT6BciMb6NRxvthOHbzRYBFAO8%3D&st=2016-06-10T21%3A31%3A41Z&se=2017-06-10T21%3A31%3A41Z&sp=r)**

    STOP_REASON:
    SIGSEGV

    FAULT_SYMBOL:
    libcoreclr.so!WKS::gc_heap::a_fit_segment_end_p

    FAILURE_HASH:
    SIGSEGV_libcoreclr.so!WKS::gc_heap::a_fit_segment_end_p

    FAULT_STACK:
    libcoreclr.so!WKS::gc_heap::a_fit_segment_end_p(int, WKS::heap_segment*, unsigned long, alloc_context*, int, int*)
    libcoreclr.so!WKS::gc_heap::allocate_small(int, unsigned long, alloc_context*, int)
    libcoreclr.so!WKS::gc_heap::try_allocate_more_space(alloc_context*, unsigned long, int)
    libcoreclr.so!WKS::GCHeap::Alloc(alloc_context*, unsigned long, unsigned int)
    libcoreclr.so!AllocateObject(MethodTable*)
    libcoreclr.so!EEException::CreateThrowable()
    libcoreclr.so!CreateCOMPlusExceptionObject(Thread*, _EXCEPTION_RECORD*, int)
    libcoreclr.so!ExceptionTracker::GetOrCreateTracker(unsigned long, StackFrame, _EXCEPTION_RECORD*, _CONTEXT*, int, bool, ExceptionTracker::StackTraceState*)
    libcoreclr.so!ProcessCLRException
    libcoreclr.so!UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*)
    libcoreclr.so!DispatchManagedException(PAL_SEHException&)
    libcoreclr.so!HandleHardwareException(PAL_SEHException*)
    libcoreclr.so!SEHProcessException(_EXCEPTION_POINTERS*)
    libcoreclr.so!common_signal_handler(int, siginfo_t*, void*, int, ...)
    libcoreclr.so!sigsegv_handler(int, siginfo_t*, void*)
    libclrjit.so!sigsegv_handler(int, siginfo_t*, void*)
    libpthread.so.0!UNKNOWN
    System.Private.CoreLib.ni.dll!System.Reflection.Emit.DynamicMethod.GetMethodDescriptor()
    System.Private.CoreLib.ni.dll!System.Reflection.Emit.DynamicMethod.CreateDelegate(System.Type, System.Object)
    System.Linq.Expressions.dll!System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
    System.Linq.Expressions.dll!System.Linq.Expressions.Compiler.LambdaCompiler.Compile(System.Linq.Expressions.LambdaExpression)
    System.Linq.Expressions.dll!System.Linq.Expressions.Expression`1[[System.__Canon, System.Private.CoreLib]].Compile(Boolean)
    System.Linq.Expressions.dll!System.Linq.Expressions.Expression`1[[System.__Canon, System.Private.CoreLib]].Compile()
    System.Composition.TypedParts.dll!System.Composition.TypedParts.Discovery.DiscoveredPart.GetActivator(System.Composition.Hosting.Core.DependencyAccessor, System.Collections.Generic.IEnumerable`1<System.Composition.Hosting.Core.CompositionDependency>)
    System.Composition.TypedParts.dll!System.Composition.TypedParts.Discovery.DiscoveredExport+<>c__DisplayClass11_0.<GetExportDescriptorPromise>b__1(System.Collections.Generic.IEnumerable`1<System.Composition.Hosting.Core.CompositionDependency>)
    System.Private.CoreLib.ni.dll!System.Lazy`1[[System.__Canon, System.Private.CoreLib]].CreateValue()
    System.Private.CoreLib.ni.dll!System.Lazy`1[[System.__Canon, System.Private.CoreLib]].LazyInitValue()
    System.Composition.Hosting.dll!System.Composition.Hosting.Core.ExportDescriptorPromise.GetDescriptor()
    System.Linq.dll!System.Linq.Enumerable+SelectArrayIterator`2[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].ToArray()
    System.Linq.dll!System.Linq.Enumerable.ToArray[[System.__Canon, System.Private.CoreLib]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
    System.Composition.Hosting.dll!System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.Execute(System.Composition.Hosting.Core.CompositionContract)
    System.Composition.Hosting.dll!System.Composition.Hosting.Core.ExportDescriptorRegistry.TryGetSingleForExport(System.Composition.Hosting.Core.CompositionContract, System.Composition.Hosting.Core.ExportDescriptor ByRef)
    System.Composition.Hosting.dll!System.Composition.Hosting.Core.LifetimeContext.TryGetExport(System.Composition.Hosting.Core.CompositionContract, System.Object ByRef)
    System.Composition.Runtime.dll!System.Composition.CompositionContext.GetExport(System.Composition.Hosting.Core.CompositionContract)
    System.Composition.Runtime.dll!System.Composition.CompositionContext.GetExport[[System.__Canon, System.Private.CoreLib]](System.String)
    System.Composition.Tests.dll!System.Composition.UnitTests.SharingTest.GetExportsCreatesInstancedObjectByDefault()
    rc3-24209-01_0001.exe!stress.generated.UnitTests.UT38()
    stress.execution.dll!stress.execution.UnitTest.Execute()
    stress.execution.dll!stress.execution.DedicatedThreadWorkerStrategy.RunWorker(stress.execution.ITestPattern, System.Threading.CancellationToken)
    stress.execution.dll!stress.execution.DedicatedThreadWorkerStrategy+<>c__DisplayClass1_0.<SpawnWorker>b__0()
    System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.Execute()
    System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
    System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
    System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.ExecuteEntry(Boolean)
    System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
    libcoreclr.so!CallDescrWorkerInternal
    libcoreclr.so!MethodDescCallSite::CallTargetWorker(unsigned long const*)
    libcoreclr.so!ThreadNative::KickOffThread_Worker(void*)
    libcoreclr.so!ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)
    libcoreclr.so!ManagedThreadBase::KickOff(ADID, void (*)(void*), void*)
    libcoreclr.so!ThreadNative::KickOffThread(void*)
    libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*)
    libpthread.so.0!start_thread

    FAULT_THREAD:
    thread #1: tid = 43495, 0x00007f1e20f5e018 libcoreclr.so`WKS::gc_heap::a_fit_segment_end_p(int, WKS::heap_segment*, unsigned long, alloc_context*, int, int*) + 120, name = 'corerun', stop reason = signal SIGSEGV

**Comment by swgillespie** [comment]
Here we are trying to allocate the exception at the end of the ephemeral segment, but we SEGV when we dereference the pointer to the ephemeral segment, since apparently it has been unmapped. Sounds like this got fixed by https://github.com/dotnet/coreclr/pull/5623 ?
