### ISSUE TITLE
Old links in Developer-Guide to Documentation

### ISSUE THREAD

**Issue by mbrenn** [dotnet/coreclr#571]
The following page includes some links link to an index.md. 

https://github.com/dotnet/coreclr/wiki/Developer-Guide

The index.md is not existing anymore. I can create a patch, if recommended

**Comment by jkotas** [comment]
Thanks for noticing it. It would be awesome if you create a patch with the fix.

cc @richlander

**Comment by richlander** [comment]
Yup. I have been moving files around and knew that there would be orphan links, but didn't want to take the time to find them all. Please do help us fix any bad links you find.

**Comment by richlander** [comment]
Fixed.
