### ISSUE TITLE
SIGABRT_System.ExecutionEngineException_libcoreclr.so!WKS::gc_heap::plan_phase

### ISSUE THREAD

**Issue by schaabs** [dotnet/coreclr#5710]
**Notes in this dump are for Ubuntu 14.04 core file [rc3-24209-01_0002](https://rapreqs.blob.core.windows.net/dotnetbot/BodyPart_7cfdc7c0-4a37-46ed-b56c-9a165e530639?sv=2015-04-05&sr=b&sig=qMKy6z%2FGybDEpc4w2jRUXj%2FP25joVmkILS6dis5JMo4%3D&st=2016-06-10T21%3A32%3A52Z&se=2017-06-10T21%3A32%3A52Z&sp=r)**

    LAST_EXCEPTION:
    Exception object: 00007fbbfffff1e0
    Exception type:   System.ExecutionEngineException
    Message:          <none>
    InnerException:   <none>
    StackTrace (generated):
    <none>
    StackTraceString: <none>
    HResult: 80131506

    STOP_REASON:
    SIGABRT

    FAULT_SYMBOL:
    libcoreclr.so!WKS::gc_heap::plan_phase

    FAILURE_HASH:
    SIGABRT_System.ExecutionEngineException_libcoreclr.so!WKS::gc_heap::plan_phase

    FAULT_STACK:
    libc.so.6!__bsd_signal
    libc.so.6!__bsd_signal
    libcoreclr.so!SafeExitProcess(unsigned int, int, ShutdownCompleteAction)
    libcoreclr.so!EEPolicy::HandleFatalError(unsigned int, unsigned long, char16_t const*, _EXCEPTION_POINTERS*)
    libcoreclr.so!UNKNOWN
    libcoreclr.so!WKS::gc_heap::plan_phase(int)
    libcoreclr.so!WKS::gc_heap::gc1()
    libcoreclr.so!WKS::gc_heap::garbage_collect(int)
    libcoreclr.so!WKS::GCHeap::GarbageCollectGeneration(unsigned int, WKS::gc_reason)
    libcoreclr.so!WKS::gc_heap::allocate_small(int, unsigned long, alloc_context*, int)
    libcoreclr.so!WKS::gc_heap::try_allocate_more_space(alloc_context*, unsigned long, int)
    libcoreclr.so!WKS::GCHeap::Alloc(alloc_context*, unsigned long, unsigned int)
    libcoreclr.so!FastAllocatePrimitiveArray(MethodTable*, unsigned int, int)
    libcoreclr.so!JIT_NewArr1(CORINFO_CLASS_STRUCT_*, long)
    System.Private.CoreLib.ni.dll!System.Collections.Generic.List`1[[System.Byte, System.Private.CoreLib]].set_Capacity(Int32)
    System.Private.CoreLib.ni.dll!System.Collections.Generic.List`1[[System.Byte, System.Private.CoreLib]].Add(Byte)
    System.Runtime.Numerics.Tests.dll!System.Numerics.Tests.MyBigIntImp.ShiftLeftDrop(System.Collections.Generic.List`1<Byte>)
    System.Runtime.Numerics.Tests.dll!System.Numerics.Tests.MyBigIntImp.Multiply(System.Collections.Generic.List`1<Byte>, System.Collections.Generic.List`1<Byte>)
    System.Runtime.Numerics.Tests.dll!System.Numerics.Tests.MyBigIntImp.Pow(System.Collections.Generic.List`1<Byte>, System.Collections.Generic.List`1<Byte>)
    System.Runtime.Numerics.Tests.dll!System.Numerics.Tests.MyBigIntImp.DoBinaryOperatorMine(System.Numerics.BigInteger, System.Numerics.BigInteger, System.String)
    System.Runtime.Numerics.Tests.dll!System.Numerics.Tests.StackCalc.DoNextOperation()
    System.Runtime.Numerics.Tests.dll!System.Numerics.Tests.powTest.VerifyPowString(System.String)
    System.Runtime.Numerics.Tests.dll!System.Numerics.Tests.powTest.RunPowPositive()
    rc3-24209-01_0002.exe!stress.generated.UnitTests.UT3()
    stress.execution.dll!stress.execution.UnitTest.Execute()
    stress.execution.dll!stress.execution.DedicatedThreadWorkerStrategy.RunWorker(stress.execution.ITestPattern, System.Threading.CancellationToken)
    stress.execution.dll!stress.execution.DedicatedThreadWorkerStrategy+<>c__DisplayClass1_0.<SpawnWorker>b__0()
    System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.Execute()
    System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
    System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
    System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.ExecuteEntry(Boolean)
    System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
    libcoreclr.so!CallDescrWorkerInternal
    libcoreclr.so!MethodDescCallSite::CallTargetWorker(unsigned long const*)
    libcoreclr.so!ThreadNative::KickOffThread_Worker(void*)
    libcoreclr.so!ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)
    libcoreclr.so!ManagedThreadBase::KickOff(ADID, void (*)(void*), void*)
    libcoreclr.so!ThreadNative::KickOffThread(void*)
    libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*)
    libpthread.so.0!start_thread

    LAST_EXCEPTION_TYPE:
    System.ExecutionEngineException

    FAULT_THREAD:
    thread #1: tid = 9990, 0x00007fbca1729c37 libc.so.6`__bsd_signal + 4 at sigset.h:117, name = 'corerun', stop reason = signal SIGABRT

**Comment by sergiy-k** [comment]
This crash dump contains an old version of coreclr (from end of May). This issue should have been fixed by https://github.com/dotnet/coreclr/pull/5623.
