### ISSUE TITLE
Rethrow of managed exception from native code failure on Unix

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#5712]
The problem happens when managed exception is caught in native code, 
rethrown and then caught and passed to DispatchManagedException
to be propagated further through managed code frames.
The problem is that while the exception was rethrown, it still has the
TargetFrameSp member set to the frame that has caught it and so the
DispatchManagedException thinks it is just continuing to propagate it in the
second pass instead of starting a new first pass.
The UnwindManagedExceptionPass2 then asserts, because the TargetFrameSp is
below the frame it is about to process.

**Comment by janvorli** [comment]
Fixed by #5697

**Comment by sergiy-k** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/5711 in the release branch.
