### ISSUE TITLE
Make search in TimeZoneInfo.GetAdjustmentRuleForTime more efficient

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#5716]
While investigating dotnet/coreclr#5558 it was noted that TimeZoneInfo.GetAdjustmentRuleForTime can be made more efficient, especially on Linux.

@eerhardt noted:

The Adjustment Rules between Windows and Linux are vastly different.

On Windows, for a given time zone, there are usually < 5.  And they contain general rules like:
-          Before 2006, DST starts on the first Sunday in April and ends on the last Sunday in October
-          After 2007, DST starts on the last Sunday in March and ends on the first Sunday in November

The Windows format is not precise enough to be accurate for all the different time zone rules in the world.

On Linux, the standard is to use the Olson tzdata files.  Their format is:
-          For a given time zone, every time the offset from UTC changes, make an entry
-          For something like the US, there will be one of these entries 2x for every year (one when DST turns on, one when off)

Both of these formats get turned into “AdjustmentRules”.  On Windows there will be only a handful.  On Linux there will be a lot.

For both platforms, finding the Adjustment rule starts at the beginning and ‘for’s through the list until it finds it.  For windows it is quick because there aren’t that many. On Linux, I can see it taking much longer.

I can imagine a good fix here would be to binary search the adjustment rules instead.  We have some good tests, so we would know pretty quick if something was broken.

@mconnew suggested an alternative approach: 
An optimization I plan on testing would be to maintain a year based index of starting points in the array. So if I have a date from 1985, it will return the index to the first potential matching rule, then the loop would simply start at that point. I presume the rules are already sorted in date order?

@mj1856 noted:
Given the size of the data for each individual time zone, I really don’t think there's going to be a considerable difference between a simple binary search and searching a precomputed index.  However, building the index will require a full pass through the data, and a small bit of memory to hold the index.  It's a classic trade-off.

Also consider that even if the index yield faster lookup time for bulk operations, it adds unnecessary latency for single-use operations, which can be just as common.

So while I can see how the index approach might work, I think it's not warranted yet.  Let's see first how a binary search performs.  It will probably be good enough.

**Comment by AlexGhiondea** [comment]
@erozenfeld @tarekgh do we know if this is something we are currently running into? Is this a significant source of performance issues? Or have we ran into it during investigation and we would like to fix?

Bottom line: do we want to tackle this in the 2.0 timeframe?

**Comment by erozenfeld** [comment]
This is something I found when investigating Linux vs. Windows perf differences for some benchmarks back in June. I don't know if this is still an issue and can't comment on when this should be addressed.

**Comment by karelz** [comment]
It's blocking #16636 which we need to prioritize. Flipping to 2.0.

**Comment by tarekgh** [comment]
> It's blocking dotnet/corefx#16636 which we need to prioritize. Flipping to 2.0.

why this issue blocking the other issue?

**Comment by karelz** [comment]
I didn't realize it's not directly linked: https://github.com/dotnet/coreclr/issues/5558#issuecomment-288569461
cc @mellinoe

**Comment by eerhardt** [comment]
I can fix this. My thought is to use a binary search on the rules, since they are already sorted.

I'll make a fix this week.
