### ISSUE TITLE
Stackalloc is slow

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#5719]
Stackalloc can be around x10 slower than heap alloc, not sure why

Its often use case if to prevent future GC time; while it makes runtime more predictable by not adding to GC pause; due to the time it takes it doesn't often add to saved runtime

**Comment by mikedn** [comment]
Related to #1279 perhaps?

**Comment by benaadams** [comment]
Its all going to be L1 cache so should affect it too badly? However, I have a now test comparison now as know how to avoid `localsinit`

**Comment by benaadams** [comment]
@mikedn also heap alloc does a clear, so avoiding clear on stack alloc should be a bonus rather than an extra

**Comment by mikedn** [comment]
> also heap alloc does a clear, so avoiding clear on stack alloc should be a bonus rather than an extra

It does but it doesn't do it when you allocate an object, it does it before allocation, in bulk.

**Comment by mattwarren** [comment]
There's some info about this topic in [On ‘stackalloc’ Performance and The Large Object Heap](http://blogs.microsoft.co.il/sasha/2013/10/17/on-stackalloc-performance-and-the-large-object-heap/), i.e. for large allocations `stackalloc` wins due to the LOH

**Comment by jkotas** [comment]
Could you please attach a small repro the demonstrates the problem that this issue is about?

**Comment by benaadams** [comment]
@jkotas is covered by this one https://github.com/dotnet/coreclr/issues/1279

**Comment by benaadams** [comment]
@jkotas @mikedn I think I found what the performance issue was; have raised issue https://github.com/dotnet/coreclr/issues/8534
