### ISSUE TITLE
R2R images not resilient against System.Private.CoreLib

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#5720]
Repro: Overwrite CoreCLR in release CLI with checked CoreCLR build, but leave everything else intact.

Result: Any CLI operation (e.g. dotnet restore) will crash with a callstack related to safe handles.

**Comment by jkotas** [comment]
The problem is that crossgen picks up fragile native image content from System.Private.CoreLib.ni.dll when generating R2R images that breaks version resiliency. The fix is to stop picking up fragile native image content when generating R2R images.

**Comment by gkhanna79** [comment]
CC @fadimounir @JohnChen0 @sergiy-k

**Comment by gkhanna79** [comment]
Closing since this is resolved now.

**Comment by gkhanna79** [comment]
Release branch PR: https://github.com/dotnet/coreclr/pull/5732/
