### ISSUE TITLE
dotnet restore just hangs in docker container on mac

### ISSUE THREAD

**Issue by nertim** [dotnet/coreclr#5736]
hangs at
root@95ca144e02f4:/opt/dev/projects/cs/helloworld# dotnet new
Created new C# project in /opt/dev/projects/interview/cs/helloworld.
root@95ca144e02f4:/opt/dev/projects/cs/helloworld# dotnet restore
log  : Restoring packages for /opt/dev/projects/cs/helloworld/project.json...

root@95ca144e02f4:/opt/dev/projects/cs/helloworld# dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64

**Comment by nertim** [comment]
after waiting for a little bit I get
root@95ca144e02f4:/opt/dev/projects/cs/helloworld# dotnet restore
log  : Restoring packages for /opt/dev/projects/interview/cs/helloworld/project.json...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   An error occurred while sending the request.
error:   Couldn't resolve host name

**Comment by shahid-pk** [comment]
better place for this issue would be dotnet/cli repository in my opinion.

**Comment by nertim** [comment]
actually I did docker-machine restart and tried again and that seems to have fixed the issue.
