### ISSUE TITLE
MScorlib facade should be shipped as .dll

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#5739]
MScorlib facade is no different from any upstack assembly and thus, should be shipped as R2R image (instead of mscorlib.ni.dll).

And consider moving it to be an upstack nuget package.

CC @jkotas

**Comment by gkhanna79** [comment]
Moving this out to 1.2.0 since this does not meet the bar for 1.1.0.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/coreclr/issues/7607 related

**Comment by AlexGhiondea** [comment]
Let's track this with #7607
