### ISSUE TITLE
Fix theorerical race in lowest/highest_address updates

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#5741]
-   Stop sharing card_table, lowest_address and highest_address globals between the GC and the runtime/write-barriers by GC-local clone of them
-   Add card_table, lowest_address and highest_address as arguments of StompWriteBarrier. The runtime will use these arguments to update its copy of them.
-   Move StompWriteBarrier to GCToEEInterface

**Comment by jkotas** [comment]
cc @sergiy-k @gkhanna79

**Comment by jkotas** [comment]
cc @swgillespie GC interface refactoring

**Comment by swgillespie** [comment]
Fixed by #8359
