### ISSUE TITLE
Update SpecializeComparer to catch up with corelib changes

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#5751]
The logic in `SpecializeComparer` https://github.com/dotnet/coreclr/blob/master/src/vm/compile.cpp#L5429 should be updated to catch up with https://github.com/dotnet/coreclr/pull/5503

**Comment by jkotas** [comment]
@jamesqo Would you like to take care of this?

**Comment by jamesqo** [comment]
Sure, I'll see what I can do.
