### ISSUE TITLE
Provide KeyValuePair.Create static factory method

### ISSUE THREAD

**Issue by kzu** [dotnet/coreclr#5752]
Just like `Tuple.Create` cuts down the noise and annoyance of having to specify all the Ts when you already have typed values to provide, a similarly designed `KeyValuePair.Create` factory method would make code that creates those pairs (i.e. public APIs that expose [IEnumerable{KeyValuePair}](https://github.com/search?q=public%2BIEnumerable%3CKeyValuePair%3C&type=Code&utf8=%E2%9C%93) significantly more concise and readable. 

This is so useful that it's even [defined](https://github.com/dotnet/roslyn/blob/master/src/Debugging/Microsoft.DiaSymReader.PortablePdb/Utilities/KeyValuePair.cs#L9) in dotnet's own repos [multiple](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/InternalUtilities/KeyValuePair.cs#L9) [times](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Parallel/tests/Helpers/KeyValuePair.cs#L11) and `new KeyValuePair` [shows up a lot](https://github.com/search?l=csharp&q=new%2BKeyValuePair+user%3Adotnet&ref=searchresults&type=Code&utf8=%E2%9C%93) too.

**Comment by mikedn** [comment]
Looks like a duplicate of https://github.com/dotnet/corefx/issues/2127

**Comment by kzu** [comment]
Duplicate of #2127 indeed. Updating commit/PR to point to original issue.
