### ISSUE TITLE
Intermittent SIGSEGV in CoreCLR on Unix

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#5772]
The CLI lab jobs have recently started to experience intermittent SIGSEGV in CoreCLR on Unix. One of the cases was a memory corruption when a memory of a PE file header was partially overwritten by MethodDesc structure.

**Comment by janvorli** [comment]
The analysis of core dumps has revealed that some memory blocks allocated by the virtual allocator and PE mapper in PAL overlap. Later, we have realized that the executable memory allocator was not being called under a critical section in the PE mapper.

**Comment by gkhanna79** [comment]
@janvorli Are you intentionally tracking this differently from https://github.com/dotnet/coreclr/issues/5672?

**Comment by janvorli** [comment]
@gkhanna79 I was looking for the issue, but couldn't find it. Thanks for pointing it out.

**Comment by janvorli** [comment]
Duplicate of #5672
