### ISSUE TITLE
ARM64: !u does not mark the correct current instruction

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#5780]
!u 00007ff8`4862e69c
**Actual**

**>>>** 00007ff8`4862e698 aa1503e0 mov         x0,x21

00007ff8`4862e69c 97ffd4af bl          System.String.Equals(System.String, System.String) (00007ff8`48623958)

4862e6a0 7100001f cmp         w0,#0 (gcstress)

Expected:

00007ff8`4862e698 aa1503e0 mov         x0,x21

**>>>** 00007ff8`4862e69c 97ffd4af bl          System.String.Equals(System.String, System.String) (00007ff8`48623958)

4862e6a0 7100001f cmp         w0,#0 (gcstress)

**Comment by ramarag** [comment]
@rahku : I do not see any difference between actual and expected values above. Can you explain more ?

**Comment by rahku** [comment]
!u <addr>
The above command is expected to unassembled jitted method at address <addr> and in addition also put marker ">>>" at the address <addr> in the printed unassembled code. However currently for arm64 marker ">>>" is placed at address <addr>-4. This does not match !u command for other architetcures.
