### ISSUE TITLE
TlbImp, RegAsm support (and other .NET SDK tools) for .NET Core

### ISSUE THREAD

**Issue by yizhang82** [dotnet/coreclr#5790]
Today TlbImp does not support .NET Core due to two problems:
1. It references mscorlib
2. It references types that does not exist in .NET Core. Some examples including:

`
ImportedFromTypeLibAttribute
TypeLibFuncAttribute
TypeLibTypeAttribute
TypeLibVersionAttribute
`
3.  It needs to correctly handle features that are not available in .NET Core and take proper actions (such as warnings)

In order to work around this, people need to use ILDASM or ILSpy to decompile the generated IL into IL and C#, and fix up the code manually. The C# decompilation route is probably much easier since you don't need to manually change all the references from mscorlib to the right contracts - C# compiler should do that automatically. The caveat being that certain IL features are not correctly supported in C#, such as this one (https://github.com/dotnet/roslyn/issues/11967).

RegAsm has different problems - it emits reference to mscoree.dll which would activate the DLL in desktop CLR.

**Comment by yizhang82** [comment]
THis is mostly a dup of https://github.com/dotnet/coreclr/issues/5790. RegAsm issue should be tracked separately as it is a entirely new feature

**Comment by livarcocc** [comment]
@yizhang82 you closed this issue as a dup of itself. Did you mean to reference a different issue?

**Comment by yizhang82** [comment]
Sorry. I meant https://github.com/dotnet/coreclr/issues/10684 and https://github.com/dotnet/corefx/pull/18532. I just tried reference a tlbimp generated dll in a .NET Core 2.0 console project and I didn't hit any typeload exceptions.

**Comment by jefffhaynes** [comment]
I'm sure this is the wrong place but I've used TlbImp to generate an assembly for spellcheck.idl.  I removed the unsupported TypeLibType as you noted and the rest compiles fine.  However, when I instantiate the resulting SpellCheckerFactory class I get an ExecutionEngineException with no additional information.
