### ISSUE TITLE
Unable to view RyuJIT dump on Linux

### ISSUE THREAD

**Issue by choikwa** [dotnet/coreclr#5801]
I followed the instructions at [LINK](https://github.com/dotnet/coreclr/blob/master/Documentation/building/viewing-jit-dumps.md)
but was unable to get anything to print out to stdout. 
I tried with both Ubuntu 14.04 and LInuxMint 17.3 to no avail.
Does anyone else have this issue or are the instructions outdated?

**Comment by AndyAyersMS** [comment]
They should be reasonably accurate.

Did you overlay a DEBUG or CHECKED build of CoreCLR onto the CLI?

RELEASE builds will not generate dumps.

**Comment by choikwa** [comment]
I compiled Debug CoreCLR, copied binaries over to **Debug** published test app, still getting no stdout. I tried it on Windows 10 as well to no avail. I could be doing something wrong that's not obvious to me.

**Comment by choikwa** [comment]
Found the dump to output by running just the command `corerun Program.exe`
Program.exe was generated by mcs/csc.

`dotnet run` seems to suppress dump.
