### ISSUE TITLE
[CoreCLR][RC2] Content-Type is removed from the response if it is not in "type/subtype" format

### ISSUE THREAD

**Issue by erezvani1529** [dotnet/coreclr#5806]
The content-type property is being stripped off of response if it is not in "type/subtype" format.

Information on the project and target frameworks:
- .NetCore Console App
- project.json

{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

    "dependencies": {
        "Microsoft.NETCore.App": {
            "type": "platform",
            "version": "1.0.0-rc2-3002702"
        },
        "WindowsAzure.Storage": "7.0.2-preview"
    },

  "frameworks": {
    "netcoreapp1.0": {
        "imports": [
            "dnxcore50",
            "portable-net451+win8"
        ]
    }
  }
}

Sample fiddler trace using WindowsAzure.Storage client library(CoreCLR RC2 release):

User-Agent: Azure-Storage/7.0.2-preview (.NET Core 5.0)
x-ms-content-language: languagevalue
x-ms-content-type: contenttypevalue---> Content type header is sent successfully
x-ms-client-request-id: 271c0518-3f42-4a05-89f0-27fcdf082d25
x-ms-version: 2015-07-08
x-ms-date: Wed, 08 Jun 2016 21:12:46 GMT
----------------------
Content-Type: contenttypevalue --> the stored content type returned from server
Content-Language: languagevalue
Last-Modified: Wed, 08 Jun 2016 21:12:45 GMT
ETag: "0x8D38FE1A3263418"
Server: Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: cf262393-001a-0014-27ca-c18fe2000000
x-ms-version: 2015-07-08
x-ms-type: File
Date: Wed, 08 Jun 2016 21:14:23 GMT

result: ContentType doesn't have the specified value (null value is retuned in the application).

Note: I have tried  the same scenario with a content-type with "type/subtype" format such as:
"contenttypeva/lue" and it works fine.

Please let me know if there are any more information required to investigate this issue.

Thanks!

**Comment by ericstj** [comment]
This is an HTTPClient issue and should be opened in the CoreFx repo.  I will close this and open there.
