### ISSUE TITLE
Linux, SOS: Symbol reader doesn't support getting locals from portable PDB

### ISSUE THREAD

**Issue by lucenticus** [dotnet/coreclr#5809]
Sinse pull requests  https://github.com/dotnet/coreclr/pull/5688 and https://github.com/dotnet/corefx/pull/9281 implement reading portable PDB for Linux,  we have to  support `SymbolReader::GetNamedLocalVariable` similar to `SymbolReader::ResolveSequencePoint`.
Here is a signature for the method:
`HRESULT SymbolReader::GetNamedLocalVariable(ISymUnmanagedScope * pScope, ICorDebugILFrame * pILFrame, mdMethodDef methodToken, ULONG localIndex, __inout_ecount(paramNameLen) WCHAR* paramName, ULONG paramNameLen, ICorDebugValue** ppValue)`
Related issue: https://github.com/dotnet/coreclr/issues/4798
CC @kvochko, @Dmitri-Botcharnikov, @seanshpark, @mikem8361

**Comment by lucenticus** [comment]
@mikem8361 Does this issue was closed accidentally? Perhaps, you would like to close the issue #4798?

**Comment by mikem8361** [comment]
Sorry, I closed the wrong issue.

**Comment by lucenticus** [comment]
I found that `SymbolReader::GetNamedLocalVariable` is called only when using clrstack command with option` -i`. But if we implements reading local variables from portable pdb, then I think we have to support getting such kind of information even without option `-i`. Current `clrstack -a` command prints locals like this: 

> 00007FFFFFFFD390 00007FFF7D084599 HelloWorld3.Program.show_message()
>     PARAMETERS:
>         this (0x00007FFFFFFFD3B0) = 0x00007fff60009830
>     LOCALS:
>         0x00007FFFFFFFD3A8 = 0x00007fff60009848
>         0x00007FFFFFFFD3A0 = 0x0000000000000000
> ...

Am I right understand that we have to change `ClrStackImpl` class to enable reading locals, parameters and lines from portable pdb? Maybe you can suggest better way to read symbols for `clrstack` command?

**Comment by lucenticus** [comment]
CC @janvorli

**Comment by mikem8361** [comment]
I'm not sure why clrstack -a doesn't print local names. Probably historical reasons lost over time. 

The best way to get locals is the implement the ifdef'ed FEATURE_PAL sections in GetNamedLocalVariable in util.cpp with calls to the portable pdb reader.  I really haven't studied the details of this code.
