### ISSUE TITLE
Broken Unwind: SIGABRT_Xunit.Sdk.EqualException_xunit.assert.dll!Xunit.Assert.Equal[[System.Int32, System.Private.CoreLib]]

### ISSUE THREAD

**Issue by schaabs** [dotnet/coreclr#5811]
**Notes for this dump are for the Ubuntu 14.04 dump http://dotnetrp.azurewebsites.net/dumpling/download/1434**

    LAST_EXCEPTION:
    Exception object: 00007f8fec13eb60
    Exception type:   Xunit.Sdk.EqualException
    Message:          Assert.Equal() Failure
    InnerException:   <none>
    StackTrace (generated):
        SP               IP               Function
        00007F9088FD3A40 00007F90120FD305 xunit.assert.dll!Xunit.Assert.Equal[[System.Int32, System.Private.CoreLib]](Int32, Int32, System.Collections.Generic.IEqualityComparer`1<Int32>)+0xd5
        00007F9088FD3A80 00007F90120EA0B0 System.Dynamic.Runtime.Tests.dll!ManagedTests.DynamicCSharp.Conformance.dynamic.context.indexer.regclass.regclass029.regclass029.Test.Finalize()+0x4b0

    StackTraceString: <none>
    HResult: 80131500

    STOP_REASON:
    SIGABRT

    FAULT_SYMBOL:
    xunit.assert.dll!Xunit.Assert.Equal[[System.Int32, System.Private.CoreLib]]

    FAILURE_HASH:
    SIGABRT_Xunit.Sdk.EqualException_xunit.assert.dll!Xunit.Assert.Equal[[System.Int32, System.Private.CoreLib]]

    FAULT_STACK:
    libc.so.6!__bsd_signal
    libc.so.6!__bsd_signal
    xunit.assert.dll!Xunit.Assert.Equal[[System.Int32, System.Private.CoreLib]](Int32, Int32, System.Collections.Generic.IEqualityComparer`1<Int32>)
    System.Dynamic.Runtime.Tests.dll!ManagedTests.DynamicCSharp.Conformance.dynamic.context.indexer.regclass.regclass029.regclass029.Test.Finalize()

    LAST_EXCEPTION_TYPE:
    Xunit.Sdk.EqualException

    FAULT_THREAD:
    thread #1: tid = 9452, 0x00007f908bb18c37 libc.so.6`__bsd_signal + 4 at sigset.h:117, name = 'corerun', stop reason = signal SIGABRT
    
**The failure in the core dump is actually expected as we're throwing an exception out of a finalizer.  However the unexpected behavior here is that we have a callstack which the debugger can't unwind passed System.Dynamic.Runtime.Tests.dll!ManagedTests.DynamicCSharp.Conformance.dynamic.context.indexer.regclass.regclass029.regclass029.Test.Finalize()**

    (lldb) clrstack -F
    OS Thread Id: 0x24ec (1)
            Child SP               IP Call Site
    00007F9088FD26E8 00007F908BB18C37 libc.so.6!__bsd_signal + 71 at /build/eglibc-3GlaMS/eglibc-2.19/signal/../sysdeps/unix/sysv/linux/bits/sigset.h:117
    00007F9088FD26E8 00007F908BB18C33 libc.so.6!__bsd_signal + 67 at /build/eglibc-3GlaMS/eglibc-2.19/signal/../sysdeps/unix/sysv/linux/bits/sigset.h:117
    00007F9088FD3920                  [HelperMethodFrame: 00007f9088fd3920]
    00007F9088FD3A40 00007F90120FD305 xunit.assert.dll!Xunit.Assert.Equal[[System.Int32, System.Private.CoreLib]](Int32, Int32, System.Collections.Generic.IEqualityComparer`1<Int32>) + 213
    00007F9088FD3A80 00007F90120EA0B0 System.Dynamic.Runtime.Tests.dll!ManagedTests.DynamicCSharp.Conformance.dynamic.context.indexer.regclass.regclass029.regclass029.Test.Finalize() + 1200
    00007F9088FD3D10                  [DebuggerU2MCatchHandlerFrame: 00007f9088fd3d10]

**Comment by janvorli** [comment]
@schaabs the issue here is that the machine you are opening the logs on has different version of the libc.so than the one on the machine that generated the dump. Looking at the stack, I can see a return address 0x00007f908bb1c028:
```
(lldb) x/32gx $rsp
0x7f9088fd26e8: 0x00007f908bb1c028 0x0000000000000020
```
That address is in libc.so.6`__GI_abort:
```
    0x7f908bb1c01e <+142>: movl   $0x6, %edi
    0x7f908bb1c023 <+147>: callq  0x7f908bb18c00            ; __bsd_signal + 16 at signal.c:36
    0x7f908bb1c028 <+152>: movq   %fs:0x10, %rdx
```
The __bsd_signal is definitely not the function it is calling. First, the comment shows __bsd_signal **+ 16** and second, the __bsd_signal function is a function that sets signal handler, which doesn't make sense in the __GI_abort.

Disassing the function at 0x7f908bb18c00 and finding the same code in libc.so.6 when debugging a live process shows that it is __GI_raise
Disass from the dump:
```
    0x7f908bb18c00 <+16>:  movl   %fs:0x2d4, %ecx
    0x7f908bb18c08 <+24>:  movl   %fs:0x2d0, %esi
    0x7f908bb18c10 <+32>:  testl  %esi, %esi
    0x7f908bb18c12 <+34>:  jne    0x7f908bb18c48            ; <+88> at signal.c:46
    0x7f908bb18c14 <+36>:  movl   $0xba, %eax
    0x7f908bb18c19 <+41>:  syscall
    0x7f908bb18c1b <+43>:  movl   %eax, %ecx
    0x7f908bb18c1d <+45>:  movl   %eax, %fs:0x2d0
    0x7f908bb18c25 <+53>:  movl   %eax, %esi
    0x7f908bb18c27 <+55>:  movslq %edi, %rdx
    0x7f908bb18c2a <+58>:  movslq %esi, %rsi
    0x7f908bb18c2d <+61>:  movslq %ecx, %rdi
    0x7f908bb18c30 <+64>:  movl   $0xea, %eax
    0x7f908bb18c35 <+69>:  syscall
->  0x7f908bb18c37 <+71>:  cmpq   $-0x1000, %rax            ; imm = 0xFFFFFFFFFFFFF000
    0x7f908bb18c3d <+77>:  ja     0x7f908bb18c5d            ; <+109> at signal.c:50
    0x7f908bb18c3f <+79>:  rep
    0x7f908bb18c40 <+80>:  retq
    0x7f908bb18c41 <+81>:  nopl   (%rax)
    0x7f908bb18c48 <+88>:  testl  %ecx, %ecx
    0x7f908bb18c4a <+90>:  jg     0x7f908bb18c27            ; <+55> at signal.c:47
    0x7f908bb18c4c <+92>:  movl   %ecx, %eax
    0x7f908bb18c4e <+94>:  negl   %eax
    0x7f908bb18c50 <+96>:  andl   $0x7fffffff, %ecx         ; imm = 0x7FFFFFFF
    0x7f908bb18c56 <+102>: cmovel %esi, %eax
    0x7f908bb18c59 <+105>: movl   %eax, %ecx
    0x7f908bb18c5b <+107>: jmp    0x7f908bb18c27            ; <+55> at signal.c:47
    0x7f908bb18c5d <+109>: movq   0x387204(%rip), %rdx
    0x7f908bb18c64 <+116>: negl   %eax
    0x7f908bb18c66 <+118>: movl   %eax, %fs:(%rdx)
    0x7f908bb18c69 <+121>: orq    $-0x1, %rax
    0x7f908bb18c6d <+125>: retq
```
Disass from live process:
```
libc.so.6`__GI_raise:
    0x7ffff6e09c90 <+0>:   movl   %fs:0x2d4, %eax
    0x7ffff6e09c98 <+8>:   movl   %eax, %ecx
    0x7ffff6e09c9a <+10>:  movl   %fs:0x2d0, %esi
    0x7ffff6e09ca2 <+18>:  testl  %esi, %esi
    0x7ffff6e09ca4 <+20>:  jne    0x7ffff6e09cd8            ; <+72> at raise.c:53
    0x7ffff6e09ca6 <+22>:  movl   $0xba, %eax
    0x7ffff6e09cab <+27>:  syscall
    0x7ffff6e09cad <+29>:  movl   %eax, %ecx
    0x7ffff6e09caf <+31>:  movl   %eax, %fs:0x2d0
    0x7ffff6e09cb7 <+39>:  movl   %eax, %esi
    0x7ffff6e09cb9 <+41>:  movslq %edi, %rdx
    0x7ffff6e09cbc <+44>:  movslq %esi, %rsi
    0x7ffff6e09cbf <+47>:  movslq %ecx, %rdi
    0x7ffff6e09cc2 <+50>:  movl   $0xea, %eax
    0x7ffff6e09cc7 <+55>:  syscall
    0x7ffff6e09cc9 <+57>:  cmpq   $-0x1000, %rax            ; imm = 0xFFFFFFFFFFFFF000
    0x7ffff6e09ccf <+63>:  ja     0x7ffff6e09cea            ; <+90> at raise.c:56
    0x7ffff6e09cd1 <+65>:  rep
    0x7ffff6e09cd2 <+66>:  retq
    0x7ffff6e09cd3 <+67>:  nopl   (%rax,%rax)
    0x7ffff6e09cd8 <+72>:  testl  %eax, %eax
    0x7ffff6e09cda <+74>:  jg     0x7ffff6e09cb9            ; <+41> at raise.c:56
    0x7ffff6e09cdc <+76>:  movl   %eax, %ecx
    0x7ffff6e09cde <+78>:  negl   %ecx
    0x7ffff6e09ce0 <+80>:  testl  $0x7fffffff, %eax         ; imm = 0x7FFFFFFF
    0x7ffff6e09ce5 <+85>:  cmovel %esi, %ecx
    0x7ffff6e09ce8 <+88>:  jmp    0x7ffff6e09cb9            ; <+41> at raise.c:56
    0x7ffff6e09cea <+90>:  movq   0x387177(%rip), %rdx
    0x7ffff6e09cf1 <+97>:  negl   %eax
    0x7ffff6e09cf3 <+99>:  movl   %eax, %fs:(%rdx)
    0x7ffff6e09cf6 <+102>: orq    $-0x1, %rax
    0x7ffff6e09cfa <+106>: retq
```

**Comment by janvorli** [comment]
So we will need to pack the shared libraries used by the process from the machine that produced the dump and then let the lldb use them when loading the dump. 
See this for some guidelines:
http://lists.llvm.org/pipermail/lldb-dev/2016-January/009236.html

**Comment by schaabs** [comment]
@janvorli thanks for the information.  I'm closing the issue as we already have a solution for this.  We have a script to load all the shared libraries off the machine using the debugger to locate them, but we haven't turned it on in our clients yet, b/c the clients currently don't have the debugger installed.  However, I'll push to enable this on our stress clients asap so we ensure we're debugging with all the right modules including modules not owned by us.
