### ISSUE TITLE
ARM64: Incorrect gcinfo in method System.Reflection.RuntimeParameterInfo.GetParameters

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#5817]
This method is in system.private.corlib. So you can use crossgen to repro the case.
For below 
System.Reflection.RuntimeParameterInfo.GetParameters(System.IRuntimeMethodInfo, System.Reflection.MemberInfo, System.Signature, System.Reflection.ParameterInfo ByRef, Boolean)
Begin 00007ff8a0d785d0, size 484

at offset around 0xbc there is a call to method static method _GetMetadataImport. This method returns valuetype System.Reflection.MetadataImport. Sos shows the size of type to be 32 bytes so this should be returned using retbuf. However, I do not see that happening. It seems code is expecting return value in x0. See below

```
00007ff8`a0d7868c 97ee82c1 bl          CORINFO_HELP_MEMSET (00007ff8`a0919190)
00007ff8`a0d78690 aa1b03e0 mov         x0,x27

00007ff8`a0d78694 97f0254f bl          System.RuntimeTypeHandle._GetMetadataImport(System.RuntimeType) (00007ff8`a0981bd0)
00007ff8`a0d78698 f9002fa0 str         x0,[fp,#0x58]
00007ff8`a0d7869c f9002bbb str         x27,[fp,#0x50]
```

```
0:000> !DumpVC 00007ff8a10e9268 000001f1c716efb8   
Name:        System.Reflection.MetadataImport
MethodTable: 00007ff8a10e9268
EEClass:     00007ff8a02edab0
Size:        32(0x20) bytes
File:        R:\corefxtests\System.Linq.Expressions.Tests\System.Private.CoreLib.ni.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ff8a10f6ab8  4001574        8        System.IntPtr  1 instance                0 m_metadataImport2
00007ff8a10dd7c0  4001575        0        System.Object  0 instance 0000000000000000 m_keepalive
00007ff8a10e9268  4001576      b88 ...on.MetadataImport  1   shared           static EmptyImport
                                 >> Domain:Value  000001f1c5197370:NotInit  <<
```

**Comment by kyulee1** [comment]
I'm not sure if this is an issue.
`System.RuntimeTypeHandle:GetMetadataImport(ref):struct` is inlined.
The inlined call `System.RuntimeTypeHandle._GetMetadataImport(ref):long` is the right signature. The returned value goes to the property `m_metadataImpor2` at offset 8 shown in the code `str x0,[fp, #0x58]`. It's also correct the RuntimeType `x27` goes to the property `m_keepalive` at offset 0 shown in the code `str x27,[fp,#0x50]`.
I think the reason of size 32 is because it has additional 16 byte shared static field `EmptyImport`. So the entire operations seems reasonable to me at least for this instance.
BTW how did you get `000001f1c716efb8` address above in your `DumpVC command`? Is this `fp+0x50`?

**Comment by rahku** [comment]
ok Thanks I missed that it was inlined and there was a function with similar name inside the call.
The error i was tracking is actually a gcinfo issue for this same method(System.Reflection.RuntimeParameterInfo.GetParameters). Some instructions after this code the valuetype is copied to stack at offset 0x78 & 0x80. Then later on it is passed in regs before call to System_Private_CoreLib_ni!System.Reflection.RuntimeParameterInfo..ctor

00007ff8`a0d787c0 f9403fa2 ldr         x2,[fp,#0x78]

00007ff8`a0d787c4 f94043a3 ldr         x3,[fp,#0x80]

00007ff8`a0d787c8 f90013a9 str         x9,[fp,#0x20]

00007ff8`a0d787cc aa0903e0 mov         x0,x9

00007ff8`a0d787d0 aa1303e1 mov         x1,x19

00007ff8`a0d787d4 2a1c03e4 mov         w4,w28

00007ff8`a0d787d8 b9806ba5 ldrsw       x5,[fp,#0x68]

00007ff8`a0d787dc b98077a6 ldrsw       x6,[fp,#0x74]

00007ff8`a0d787e0 aa1403e7 mov         x7,x20

00007ff8`a0d787e4 9400011b bl          System_Private_CoreLib_ni!System.Reflection.RuntimeParameterInfo..ctor(System.Signature, System.Reflection.MetadataImport, Int32, Int32, System.Reflection.ParameterAttributes, System.Reflection.MemberInfo) (00007ff8`a0d78c50)


The above code region is an interruptible code region (around offset 0x1f4)  is within interruptible code region.

Defining interruptible range: [0x58, 0xe4).
Defining interruptible range: [0xe8, 0x290).
Defining interruptible range: [0x294, 0x334).
Defining interruptible range: [0x338, 0x39c).
Defining interruptible range: [0x3b8, 0x4d0).

However register x2 which stores the m_keepalive value is not marked as live. So it gets collected before the call to System_Private_CoreLib_ni!System.Reflection.RuntimeParameterInfo..ctor() if a gc happens between call and move to x2.

see jitdump https://gist.githubusercontent.com/rahku/00fc18932666fb3f92271ea1ae07026a/raw/08edd363ec70503296ff2fbd1af92114e5cf83be/a.log

and codegen 
https://gist.githubusercontent.com/rahku/00fc18932666fb3f92271ea1ae07026a/raw/08edd363ec70503296ff2fbd1af92114e5cf83be/b.txt

**Comment by kyulee1** [comment]
Thanks for the repro. I think we have a gc hole when we pass struct with multi-reg.
Continue investigating for the right fix.

**Comment by kyulee1** [comment]
I sent PR for the fix https://github.com/dotnet/coreclr/pull/5865
Do you have an actual failing test? Let me know this works for you.
