### ISSUE TITLE
Update Windows build to use VC 2015 Update 3

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#5823]
This will address warnings with (__vcrt_trace_logging_provider::_TlgWrite). Needs to be done on CI and build machines, in addition to doc updates.

**Comment by gkhanna79** [comment]
@dleeapho Do you know what VS version and Update is being used for Windows builds?

**Comment by dleeapho** [comment]
They should be using VS2015 Update 3 already.

**Comment by gkhanna79** [comment]
Is there a way to confirm? I would like to close this if it is already the case.

**Comment by dleeapho** [comment]
DDIT has confirmed. I've also looked at VSTS Agent capability configs.
