### ISSUE TITLE
CoreCLR stable package references pre-release ARM packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/coreclr#5834]
Restore below project

```
{
  "dependencies": { "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0" },
  "frameworks": { "uap10.0": { } },
  "runtimes": { "win10-arm": {} }
}
```

Expected: only installs stable packages
Actual: installs pre-release ARM coreclr package: `runtime.win8-arm.Microsoft.NETCore.Runtime.CoreCLR 1.0.2-rc4-24123-00`

NuGet doesn't block restore because the pre-release package is only in the runtime.json.

I missed this in manual validation because the addition of the external reference to the TFS version happened at the same time I was making the stable changes and I didn't catch it when I rebased.
https://github.com/dotnet/coreclr/blob/af356a0b1a80c2620f51c1463107a9cbe59abe32/src/.nuget/Microsoft.NETCore.Runtime.CoreCLR/Microsoft.NETCore.Runtime.CoreCLR.pkgproj#L15

NuGet never catches the pre-release ref so packages restore fine.

The ARM package is only used for UWP scenarios and we don't even use its content (it gets replaced with the debug coreclr APPX package).

If I mock up what would happen if we only released the stable package on nuget.org (and not this pre-release version) I see that NuGet pulls down the RTM version without any warnings/errors:

```
log  : Installing runtime.win8-arm.Microsoft.NETCore.Runtime.CoreCLR 1.0.2
```

I'd recommend won't fixing this for RTM.  We'll improve our build infra to catch this: https://github.com/dotnet/buildtools/issues/820.  We can decide if we want to "doctor" the runtime.json in the CoreCLR package we publish on Nuget.  Given the fact that it does the right thing so long as we don't publish the pre-release package I'm apt to leave the runtime.json alone.

**Comment by gkhanna79** [comment]
@ericstj Is there anything actionable here for 1.1.0?

**Comment by ericstj** [comment]
No, we can punt.  I believe I just opened this for RTM because it was something that I wanted shiproom to be aware of.

**Comment by gkhanna79** [comment]
Moved to 1.2.0. Please close if it is not actionable at all.

**Comment by gkhanna79** [comment]
@ericstj Is this actionable?

**Comment by danmosemsft** [comment]
@ericstj is this on track for ZBB or is it fixed or something else? Are you the right owner?
@weshaggard

**Comment by ericstj** [comment]
This should be owned by @gkhanna79.

In 1.0 the CoreCLR package didn't mark all of its runtime packages as stable, nor did it trim the unstable ones out.  The result was that folks could get unstable bits by referencing a stable package and restoring for a particular runtime.  It also meant that we had to publish those unstable bits on NuGet.org when folks weren't necessarily ready to do that.

Whether or not this is an issue for 2.0 depends on what @gkhanna79's plans are for the packages produced and published out of the CoreCLR repo.

Look at all of the packages you are producing today.  Are you going to make them all stable in 2.0?  If so great close this issue.
If not, then look at the package closure (including runtime-specific packages).  If anywhere you will violate the rule that stable cannot reference unstable you should consider removing those dependencies for 2.0 release.  If not, close this issue.

**Comment by gkhanna79** [comment]
Yes, in 2.0 (as we have done for 1.1.0 as well), we stabilize all our packages. However, we will choose to publish (to nuget) only certain packages and exclude some (e.g. Arm32 and Arm64).

> If anywhere you will violate the rule that stable cannot reference unstable you should consider removing those dependencies for 2.0 release

I don't believe this issue exists anymore and thus, I think we can close this.

@weshaggard Any concerns with this?

**Comment by weshaggard** [comment]
>exclude some (e.g. Arm32 and Arm64).

I think we should publish all the packages we produce and stabilize to nuget.org, otherwise there will be dangling dependencies which we want to avoid.

**Comment by gkhanna79** [comment]
We can chat about this offline. For now, I think we can close this issue since it is addressed (i.e. there will not be stable->unstable references).
