### ISSUE TITLE
[ARM/Linux] Build failure - undefined reference to `DBG_DebugBreak_End' 

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#5845]
CoreCLR build failed for ARM/Linxux with the following message:
```
...
../libcoreclrpal.a(debug.cpp.o): In function `IsInDebugBreak':
/home/parjong/projects/toolchains/coreclr/src/pal/src/debug/debug.cpp:444: undefined reference to `DBG_DebugBreak_End'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [src/pal/src/examples/palexmpl] Error 1
```

**Comment by myungjoo** [comment]
Anyway.. do you think it'd be ok to revert ARM part only? (or are we going to create END label manually for the src/pal/src/debug.cpp?)

**Comment by parjong** [comment]
@myungjoo I'm currently testing the following patch:
```
diff --git a/src/pal/src/arch/arm/debugbreak.S b/src/pal/src/arch/arm/debugbreak.S
index 76b304f..863d7cf 100644
--- a/src/pal/src/arch/arm/debugbreak.S
+++ b/src/pal/src/arch/arm/debugbreak.S
@@ -10,5 +10,5 @@
 LEAF_ENTRY DBG_DebugBreak, _TEXT
     EMIT_BREAKPOINT
     bx lr
-LEAF_END DBG_DebugBreak, _TEXT
+LEAF_END_MARKED DBG_DebugBreak, _TEXT
```
I'll let you know when I get the result :D

**Comment by parjong** [comment]
@myungjoo The above patch works for ARM Debug build, and I'll check it again for Release build :)

**Comment by janvorli** [comment]
That's the right fix. I have made the same for AMD64 and forgotten to do the same for ARM. Actually, could you please make the same change for ARM64? It has the same problem.

**Comment by parjong** [comment]
@janvorli I think that the following patch might solve the build issue in ARM64: 
```
diff --git a/src/pal/src/arch/arm64/debugbreak.S b/src/pal/src/arch/arm64/debugbreak.S
index b57934a..0dc5bb6 100644
--- a/src/pal/src/arch/arm64/debugbreak.S
+++ b/src/pal/src/arch/arm64/debugbreak.S
@@ -7,5 +7,5 @@
 LEAF_ENTRY DBG_DebugBreak, _TEXT
     EMIT_BREAKPOINT
     ret
-LEAF_END DBG_DebugBreak, _TEXT
+LEAF_END_MARKED DBG_DebugBreak, _TEXT
```
Unfortunately, I currently cannot build ARM64 and thus can't check its correctness. Is it okay to make this change without checking the correctness?

**Comment by janvorli** [comment]
@parjong Yes, I should have changed it that way when I was doing my change, so this is a correct change.

**Comment by parjong** [comment]
@janvorli I submitted PR. Please take a look.
