### ISSUE TITLE
Add Span<T> and ReadOnlySpan<T> APIs

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/coreclr#5857]
We should add more APIs to Span<T> and ReadOnlySpan<T> (along the lines what we have in https://github.com/KrzysztofCwalina/corefxlab/blob/master/src/System.Slices/System/Span.cs

Span<T> Slice(int)
void Set(T[])
void Set(ReadOnlySpan<T>)
void Set(byte*, int)
bool TryCopyTo(T[])
bool TryCopyTo(Span<T>)
bool TryCopyTo(byte*, int)
static implicit operator ReadOnlySpan<T> (Span<T>)

**Comment by KrzysztofCwalina** [comment]
FYI @adamsitnik volunteered to work on this.

**Comment by KrzysztofCwalina** [comment]
The copy methods should use cpblk instruction (or equivalent).

**Comment by KrzysztofCwalina** [comment]
Actually, I just realized Set needs to take ReadOnlySpan. Updated above.

**Comment by adamsitnik** [comment]
@KrzysztofCwalina just FYI: I have started working on that, will implement TryCopyTo first

**Comment by KrzysztofCwalina** [comment]
@adamsitnik, Thanks!

**Comment by KrzysztofCwalina** [comment]
@adamsitnik, is that something you are still working on?

**Comment by adamsitnik** [comment]
@KrzysztofCwalina Hi! Sorry for my lack of updates!

In general I got simple version working (by simple I mean based on cpblk) quite easily. Then I started comparing it's performance with System.Buffer.Copy methods. In general it was slower. Sometimes the difference was even 30%?!?

Inspired by the [comment in the code in System.Buffer](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Buffer.cs#L283) I decided to simply call `internal unsafe static void Memmove(byte* dest, byte* src, uint len)` of `System.Buffer`. Then I realized that it [does not support types with references](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Buffer.cs#L121).

Then I tried to write similar external method for Slices, but I failed.

Would you like me to push a PR with cpbulk based implementation or maybe I could get some of your help with implementing efficient `private bool IsPrimitiveTypeSlice()`? Once again I am sorry for the delay and lack of contact.

**Comment by KrzysztofCwalina** [comment]
I think it's worth pushing cpblk version now and then improve the perf incrementally.

@jkotas, @CarolEidt, thoughts?

**Comment by jkotas** [comment]
`cpblk` does not support types with references either. A simple working implementation would copy one element at a time.

The check for primitive slices should not be hard to add - here is how to do it:
- Add `static bool ContainsReferences<T>()` method (e.g. the existing JitHelpers would be a good candidate for it).
- Recognize it in getILIntrinsicImplementation in `vm\jitinterface.cpp`
- The IL you tell JIT to use should be simply return 1 if the instantiation argument is valuetype and it contains references; 0 otherwise.

**Comment by CarolEidt** [comment]
Is there some reason why `cpobj` would not be the "simple initial solution"? It will perform the same as `cpblk` if there are no gc refs, but will correctly handle the gc refs when present.

**Comment by jkotas** [comment]
> It will perform the same as `cpblk`

It copies one element at a time - it won't be same as `cpblk`.

**Comment by CarolEidt** [comment]
`cpobj` doesn't copy one element at a time if there are no gc refs - the JIT queries the runtime to get the gc layout, and then if there are no gc refs, it changes it to a `cpblk`.

**Comment by jkotas** [comment]
The problem here is to copy block of elements. 

The pseudo code for it using `cpblk` would be (works for non-gc ref containg types only): `cpblk(source, destination, count * sizeof(T))`. 

The equivalent using `cpobj` would be (works for all types): `for (int i = 0; i < count; i++) { cpobj(source, destination); source += sizeof(T); destination += sizeof(T); }`, It is not as efficient.

**Comment by CarolEidt** [comment]
Ah, yes; I was forgetting the whole point. Adding an intrinsic would be good; would it make sense to expose the interface to retrieve the layout? Our perhaps if there are any GC refs it would be just as well to use a lip over cpobj

**Comment by adamsitnik** [comment]
> if the instantiation argument is reference type or valuetype that contains references; 0 otherwise.

@jkotas This was the missing part for me! Thanks!

@KrzysztofCwalina I will try to add some tests and post a PR this week.

**Comment by adamsitnik** [comment]
```
void Set(T[])
void Set(ReadOnlySpan)
void Set(byte, int)
bool TryCopyTo(T[])
bool TryCopyTo(Span)
bool TryCopyTo(byte, int)
static implicit operator ReadOnlySpan (Span)
```

done

 > Span Slice(int)

@KrzysztofCwalina what do you mean by that?

`Span<T> Slice(int start)` or `Span<T> Slice(int start, int length)` or both?

also what about the enumerators? should I add them as well?

**Comment by adamsitnik** [comment]
@KrzysztofCwalina you can close this one ;)

btw. I was thinking about implementing both enumerators and Cast method for Span. Would such PR be welcomed?

**Comment by KrzysztofCwalina** [comment]
@adamsitnik, thanks one more time for the PR! I will close this issue now.

As to Cast, @jkotas would like it to be unsafe. The reason is that it's only efficient if the data is aligned. 
AsBytes():Span<byte> could-be/is always efficient, and so it could be safe. I think it would be great if you opened a discussion about it, we would all agree on the APIs, and then do the PR.

As to enumerators, I am a bit concerned about them. To me Span<T> is a very low level and simple primitive, yet our enumerators carry so much complexity from the times of non-generic collections, COM (IEnumerator.Reset), etc. Do we really need spans to be collections? Especially since span will be stack only, it will not be boxable (convertible to IEnumerable<T>).
