### ISSUE TITLE
Pulling out x86 decomposition code 

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#5866]
As discussed in #5380, pulling out the decomposition code is suggested to prevent the lowering class and file from being huge and complicated.

**Comment by sejongoh** [comment]
I assigned this to Bruce, so that he can take a look about the idea.

**Comment by BruceForstall** [comment]
@sejongoh @mikedn @adiaaida @CarolEidt I'm planning to refactor x86 long decomposition code into its own file and class, per this issue request. Seems like a very good idea. It will cause nasty manual merge issues for anyone working on this code, however.

**Comment by adiaaida** [comment]
Thanks for the heads up.
