### ISSUE TITLE
Manual lowering or decomposition due to embedded statements

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#5867]
In lowering or decomposition, when a new statement containing embedded statements is inserted before the current statement, those embedded statements requires manual lowering or decomposition. We may want to come up with a better way instead of manual lowering.

The details are discussed in #5380.

**Comment by russellhadley** [comment]
@pgavlin This looks like  stale issue now with LIR.  Can it be closed?

**Comment by pgavlin** [comment]
Yup.
