### ISSUE TITLE
Refactor GCToEEInterface::CreateBackgroundThread

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#5878]
Refactor the GCToOSInterface::CreateBackgroundThread, bgc_thread_stub and bgc_thread_function to return fully initialized thread. See the discussion in #5840 for more details.

**Comment by jkotas** [comment]
cc @swgillespie GC interface refactoring

**Comment by janvorli** [comment]
Oops, I meant GCToEEInterface, not GCToOSInterface.

**Comment by janvorli** [comment]
Fixed by #6384
