### ISSUE TITLE
Loader\classloader\regressions\523654 fails intermittently

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#5880]
There is a race among 10 threads to update A::i.  I suspect that the fix is to use Interlocked.Increment(ref i) instead of [++i](https://github.com/dotnet/coreclr/blob/79ae4d44b7dc71f098ab97e712f8af7c493e720f/tests/src/Loader/classloader/regressions/523654/test532654_b.cs#L49).

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_osx_minopts_tst/75/testReport/Loader.classloader.regressions.523654/test532654_b/test532654_b/

```
T6: Inside meth<int>
T2: Inside meth<int>
T10: Inside meth<int>
T7: Inside meth<int>
T1: Inside meth<int>
T4: Inside meth<int>
T5: Inside meth<int>
T3: Inside meth<int>
T9: Inside meth<int>
T8: Inside meth<int>
i should be 10
i = 9
FAIL
```

**Comment by sergiy-k** [comment]
@wtgodbe, could you please take a look?

**Comment by wtgodbe** [comment]
Can do.

**Comment by wtgodbe** [comment]
Your suggestion seems to have down the trick @RussKeldorph - https://github.com/dotnet/coreclr/pull/5889
