### ISSUE TITLE
Update prerelease label and bump package versions

### ISSUE THREAD

**Issue by ericstj** [dotnet/coreclr#5883]
CoreCLR needs to update pre-release label to beta and increment the 3rd portion of all package versions.

**Comment by gkhanna79** [comment]
The following needs to happen:

- [ ] Update closed build to publish 1.0.3-beta arm package
- [ ] Update open build to reference beta and increment 3rd portion of package versions. @ericstj did initial update [here](https://github.com/dotnet/coreclr/commit/4d0f26aeeae7fbbd3ede20bc89f9acd6e7a7eac6#diff-db6c934e3fc9f3fef2ac8eda683192e5).
- [ ] Update bot to account for the changes for preReleaseNumber update

@wtgodbe Does the new pipeline rely on these package versions?
@dagood I will coordinate with you on driving the 3rd part of the change.

**Comment by wtgodbe** [comment]
Is this just a change in the name of these packages? If so, the pipeline shouldn't be affected.

**Comment by gkhanna79** [comment]
Yes, it will be just a change in the name of the packages.

**Comment by wtgodbe** [comment]
Then I don't believe this will break anything in the pipeline. @dagood might see something I'm missing in the publishing step, though.

**Comment by gkhanna79** [comment]
@ericstj Will you (or someone) be updating the packages, published from closed build, to be updated to use "beta" prerelease moniker?

**Comment by gkhanna79** [comment]
I ask because when that happens, @dagood would need to update the preReleaseVersion update bot in sync with it and also update https://github.com/dotnet/coreclr/blob/master/dir.props#L155 to reflect the "beta".

**Comment by dagood** [comment]
@wtgodbe I don't know if it will break things, but there is the `Release` variable in the pipeline definition, currently `rc4`. At the very least, that would mislabel things, so might as well update it when the time comes.

@gkhanna79 That *should* be automatic, since the `rc4`/`beta` bit of that is part of https://github.com/dotnet/versions/blob/master/build-info/dotnet/projectk-tfs/release/1.0.0/Latest.txt, and isn't handled specially along the way. Once we get a set of packages with the new version, an auto-PR should come in to make that change to `beta`.

**Comment by ericstj** [comment]
> @ericstj Will you (or someone) be updating the packages, published from closed build, to be updated to use "beta" prerelease moniker?

Already done.

**Comment by gkhanna79** [comment]
@ericstj Was the change to "beta" done today? I ask because I dont see, as an example, beta package for APISets at https://dotnet.myget.org/gallery/dotnet-core.

**Comment by gkhanna79** [comment]
Thanks @dagood. In that case, I will mark item (3) above as done.

**Comment by dagood** [comment]
It looks like CoreCLR hasn't had a successful build since the change: https://devdiv.visualstudio.com/DevDiv/Net%20CoreFX/_build?definitionId=1832&_a=completed. I'll take a look.

**Comment by gkhanna79** [comment]
What about APISet package? I dont see beta version of the same as well.

**Comment by wtgodbe** [comment]
@dagood the official builds have been failing because the Mac machines we usually run jobs on have been offline since Saturday, so the failures could be unrelated.

**Comment by gkhanna79** [comment]
> but there is the Release variable in the pipeline definition, currently rc4

@wtgodbe What is this used for?

**Comment by dagood** [comment]
@wtgodbe Ah, yeah, the build pipeline's just failing to queue the builds, so I'd say it's that.

**Comment by wtgodbe** [comment]
@gkhanna79 we use that variable as part of a unique identifier for each orchestrated build - something like 'coreclr-rc4-20160620-01'. That name gets assigned to the azure blob where the packages get published to, then the job that sends those packages to myget/VSTS knows it can find those packages in a blob with that name. It doesn't affect the name of the actual packages themselves. But, for consistency's sake, it would be good to have that variable match the version in the name of the packages (so once your change gets merged in, I can update it from 'rc4' to 'beta').

**Comment by gkhanna79** [comment]
Sounds good @wtgodbe

**Comment by gkhanna79** [comment]
The PR is merged. @wtgodbe can you please update the mast branch pipeline definition to specify beta as the release?
