### ISSUE TITLE
[ARM/Linux] Assert Failure ("Unrecognized ETW root kind") when using CoreCLRProfiler

### ISSUE THREAD

**Issue by sam-baravy** [dotnet/coreclr#5918]
Corerun crashes when I try to use CoreCLRProfiler (https://github.com/david-mitchell/CoreCLRProfiler.git) on arm-softfp:

> GarbageCollectionStarted
> ObjectsAllocatedByClass
> 
> Assert failure(PID 27673 [0x00006c19], Thread: 27673 [0x6c19]): !"Unrecognized ETW root kind"
>     File: /home/i.baravy/work/repo/coreclr/src/vm/eetoprofinterfaceimpl.cpp Line: 1641
>     Image: /opt/home/i.baravy/work/repo/coreclr/bin/Product/Linux.arm-softfp.Debug/corerun
> 
> **** MessageBox invoked, title 'corerun - Assert Failure (PID 27673, Thread 27673/0x6c19)' ****
>   !"Unrecognized ETW root kind"
> 
> /home/i.baravy/work/repo/coreclr/src/vm/eetoprofinterfaceimpl.cpp, Line: 1641
> 
> Abort - Kill program
> Retry - Debug
> Ignore - Keep running
> 
> 
> Image:
> /opt/home/i.baravy/work/repo/coreclr/bin/Product/Linux.arm-softfp.Debug/corerun
> 
> ********
> 
> Aborted (core dumped)

Steps to reproduce:

1. Clone CoreCLR to Ubuntu 14.04.4 LTS

2. Install dependencies:
`$ sudo apt-get install cmake llvm-3.6 clang-3.6 lldb-3.6 lldb-3.6-dev libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev`
`$ sudo apt-get install qemu qemu-user-static binfmt-support debootstrap`
`$ sudo apt-get install binutils-aarch64-linux-gnu`

3. Prepare rootfs:
`$ sudo ./cross/build-rootfs.sh arm-softfp`

4. Cross-build CoreCLR:
`$ ./build.sh arm-softfp clean cross skiptests`

5. Clone CoreCLRProfiler demo profiler:
`$ git clone https://github.com/david-mitchell/CoreCLRProfiler.git`
`$ cd CoreCLRProfiler`
  
6. Add profiling of GC:
`$ git diff`
`diff --git a/profiler.cpp b/profiler.cpp`
`index 081d613..8970e6f 100644`
`--- a/profiler.cpp`
`+++ b/profiler.cpp`
`@@ -51,7 +51,7 @@ HRESULT STDMETHODCALLTYPE Profiler::Initialize(IUnknown *pICorProfilerInfoUnk)`
`HRESULT hr = pICorProfilerInfoUnk->QueryInterface(IID_ICorProfilerInfo3, (void **) &info);`
`if (hr == S_OK && info != NULL)`
`{`
`- info->SetEventMask(COR_PRF_MONITOR_JIT_COMPILATION | COR_PRF_MONITOR_ASSEMBLY_LOADS | COR_PRF_MONITOR_CLASS_LOADS);`
`+ info->SetEventMask(COR_PRF_MONITOR_JIT_COMPILATION | COR_PRF_MONITOR_ASSEMBLY_LOADS | COR_PRF_MONITOR_CLASS_LOADS | COR_PRF_MONITOR_GC);`
` `
`info->Release();`
`info = NULL;`
 
7. Create cross-build script: [make-arm.sh](https://github.com/dotnet/coreclr/files/327964/make-arm.sh.txt)
 
8. Build:
`$ CORECLR_ARCH=arm-softfp ./make-arm.sh`
 
9. Copy _profiler.so_ to the target coreclr directory.

10. Build the attached test program [sqrt.cs](https://github.com/dotnet/coreclr/files/327815/sqrt.cs.txt) and copy it to the target.

11. Run on target:
`$ CORECLR_PROFILER={912E73AF-F51D-4E80-894D-F4E9E6DD7C2E} CORECLR_ENABLE_PROFILING=1 CORECLR_PROFILER_PATH=./profiler.so  ./corerun sqrt.exe`
 
12. Result:
`Assert failure(PID 27673 [0x00006c19], Thread: 27673 [0x6c19]): !"Unrecognized ETW root kind"`
`    File: /home/i.baravy/work/repo/coreclr/src/vm/eetoprofinterfaceimpl.cpp Line: 1641`

.  

.  

The issue is caused by following code:
```
src/vm/eetoprofinterfaceimpl.cpp: 1636
    switch(dwEtwRootKind)
    {    
    default:
        // If a new ETW root kind is added, create a profapi root kind as well, and add
        // the appropriate case below
        _ASSERTE(!"Unrecognized ETW root kind");
```

```
src/gc/gc.h: 230
#ifdef FEATURE_EVENT_TRACE
        dwEtwRootKind = kEtwGCRootKindOther;
#endif // FEATURE_EVENT_TRACE
```
```
src/pal/CMakeLists.txt: 5
if(CLR_CMAKE_PLATFORM_LINUX AND CLR_CMAKE_PLATFORM_ARCH_AMD64)
  set(FEATURE_EVENT_TRACE 1)
endif()
```

**Comment by sam-baravy** [comment]
@Dmitri-Botcharnikov

**Comment by jkotas** [comment]
Looks like the ifdef @ gc.h:230 is wrong. It should be:

`#if defined(GC_PROFILING) || defined(FEATURE_EVENT_TRACE)`

**Comment by sam-baravy** [comment]
Jan,
thank you for the patch, it works for me, i.e. profiler runs flawlessly on arm-softfp.
Should I proceed with such a trivial PR?

**Comment by jkotas** [comment]
Yes, submit PR for it please. Thanks!
