### ISSUE TITLE
Fix for #450 accidentally reverted

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#592]
The fix for #450 that was made in 96f473c37e7ea46c96811cbc690dfeb40bf4beb6 has been accidentally reverted in 68562e7bd43ef8789e5674b053f5021192f3b70d.

@cmckinsey I left a note on 68562e7bd43ef8789e5674b053f5021192f3b70d but I'm not sure you'll see it (I've left the note after the PR was already merged) so I created this issue. It seems that I can't reopen the existing one.

**Comment by cmckinsey** [comment]
Thanks. Fixed with PR #593
