### ISSUE TITLE
[SOS][Linux] Getting source line by native offset doesn't  work

### ISSUE THREAD

**Issue by lucenticus** [dotnet/coreclr#5920]
I'm trying to enable printing source lines in sos commands like `clrstack`, `ip2md` etc. using portable pdb reader. At this moment [GetLineByOffset](https://github.com/dotnet/coreclr/blob/master/src/ToolBox/SOS/Strike/util.cpp#L5859) contains code with `#ifndef FEATURE_PAL` directives. It seems that we can get information using `SymbolReader`, but I have some difficulties with calculation of `IlOffset` 
```
        DEBUG_MODULE_AND_ID id;
        DEBUG_SYMBOL_ENTRY symInfo;
        if (FAILED(spSym3->GetSymbolEntryByToken(modBase, MethodToken, &id))
            || FAILED(spSym3->GetSymbolEntryInformation(&id, &symInfo)))
        {
            hr = E_FAIL;
            goto fallback;
        }

        IlOffset = symInfo.Offset + MethodOffs;
```
Could you explain what `symInfo.Offset` means? Can we obtain this information from portable pdb?
CC @mikem8361 @Dmitri-Botcharnikov @seanshpark @chunseoklee

**Comment by mikem8361** [comment]
This code is using the windbg symbol interfaces to read the regular managed pdb on windows.  I don’t know the equivalent portable PDB apis for GetSymbolEntryByToken/GetSymbolEntryInformation. Thomas Matousek would know but I can’t find his github id. The windbg api reference (see below) probably has more info on what symInfo.Offset is in this case.

g_ExtSymbols->GetLineByOffset() on xplat can only handle native offset/symbols.

DEBUG_SYMBOL_ENTRY structure
The DEBUG_SYMBOL_ENTRY structure describes a symbol in a symbol group.
Syntax
C++

typedef struct _DEBUG_SYMBOL_ENTRY {
  ULONG64 ModuleBase;
  ULONG64 Offset;
  ULONG64 Id;
  ULONG64 Arg64;
  ULONG   Size;
  ULONG   Flags;
  ULONG   TypeId;
  ULONG   NameSize;
  ULONG   Token;
  ULONG   Tag;
  ULONG   Arg32;
  ULONG   Reserved;
}  DEBUG_SYMBOL_ENTRY, *PDEBUG_SYMBOL_ENTRY;

Members
ModuleBase
The base address of the module in the target's virtual address space.
Offset
The location of the symbol in the target's virtual address space.
Id
The symbol ID of the symbol. If the symbol ID is not known, Id is DEBUG_INVALID_OFFSET.
Arg64
The interpretation of Arg64 depends on the type of the symbol. If the value is not known, Arg64 is zero.
Size
The size, in bytes, of the symbol's value. This might not be known or might not completely represent all of the data for a symbol. For example, a function's code might be split among multiple regions and the size only describes one region.
Flags
Symbol entry flags. Currently, no flags are defined.
TypeId
The type ID of the symbol.
NameSize
The size, in characters, of the symbol's name. If the size is not known, NameSize is zero.
Token
The managed token of the symbol. If the token value is not known or the symbol does not have a token, Token is zero.
Tag
The symbol tag for the type of the symbol. This is a value from the SymTagEnum enumeration.
Arg32
The interpretation of Arg32 depends on the type of the symbol. Currently, the value of Arg32 is the register that holds the value or a pointer to the value of the symbol. If the symbol is not held in a register, or the register is not known, Arg32 is zero.
Reserved
Set to zero.
Requirements
Header

DbgEng.h (include DbgEng.h, DbgHelp.h, or DbgHelp.h)

See also
IdebugSymbolGroup2::GetSymbolEntryInformation<mk:@MSITStore:C:\Program%20Files\Debugging%20Tools%20for%20Windows%20(x64)\debugger.chm::/debugger/getsymbolentryinformation2.htm>
IdebugSymbols3::GetSymbolEntryInformation<mk:@MSITStore:C:\Program%20Files\Debugging%20Tools%20for%20Windows%20(x64)\debugger.chm::/debugger/getsymbolentryinformation.htm>


Send comments about this topic to Microsoft<mailto:wsddocfb@microsoft.com?subject=Documentation%20feedback%20[debugger\debugger%5d:%20DEBUG_SYMBOL_ENTRY%20structure%20%20RELEASE:%20(7/6/2015)&body=%0A%0APRIVACY%20STATEMENT%0A%0AWe%20use%20your%20feedback%20to%20improve%20the%20documentation.%20We%20don't%20use%20your%20email%20address%20for%20any%20other%20purpose,%20and%20we'll%20remove%20your%20email%20address%20from%20our%20system%20after%20the%20issue%20that%20you're%20reporting%20is%20fixed.%20While%20we're%20working%20to%20fix%20this%20issue,%20we%20might%20send%20you%20an%20email%20message%20to%20ask%20for%20more%20info.%20Later,%20we%20might%20also%20send%20you%20an%20email%20message%20to%20let%20you%20know%20that%20we've%20addressed%20your%20feedback.%0A%0AFor%20more%20info%20about%20Microsoft's%20privacy%20policy,%20see%20http://privacy.microsoft.com/en-us/default.aspx.>
© 2015 Microsoft. All rights reserved.

**Comment by tmat** [comment]
@tmat Tagging myself

**Comment by tmat** [comment]
Can WinDbg call managed code to read the information?

**Comment by lucenticus** [comment]
@tmat, I'm not sure that I understand your question correctly. We are using libsosplugin + lldb and reading portable PDB on Linux. We call managed code from System.Diagnostics.Debug.SymbolReader.dll https://github.com/dotnet/corefx/pull/9281 to read lines and IL offsets. See also PR https://github.com/dotnet/coreclr/pull/5688/. 
Do I understand correctly that for xplat `symInfo.Offset` is an IL offset of the method beginning?  It seems that this IL offset always equals to zero for methods, is it correct?

**Comment by tmat** [comment]
@lucenticus I see, so you already have the IL offset from the Portable PDB and have a problem translating it to native offset.

**Comment by tmat** [comment]
So if I understand this well, symInfo.Offset should be RVA of the first instruction of a given method? If so then that information needs to be calculated from the PE image. The method body RVA is in MethodDef table. That RVA points to a start of the method body header. Method body format is either "tiny" or "fat" - that's determined by the first byte of the header. If the lowest 2 bits are 0b10 it's tiny and the IL starts at the next byte. Otherwise it's fat and the IL starts at offset +12 from the body header start.

**Comment by lucenticus** [comment]
I need to convert Native offset to IL Offset. I've tried to use just `MethodOffs` without `symInfo.Offset` and it works. Thanks!
