### ISSUE TITLE
Remove CoreCLR's dependency on the diasymreader.dll installed as part of the full .NET Framework on Desktop

### ISSUE THREAD

**Issue by tzwlai** [dotnet/coreclr#5922]
We have discovered that CoreCLR relies on the diasymreader.dll installed as part of the full .NET Framework on Desktop in order to resolve traditional PDBs and print source line numbers in Exception.ToString() (and likely System.Diagnostics.StackTrace as well).  We should be able to use Microsoft.DiaSymReader.Native to have our own copy of diasymreader.dll.

**Comment by mikem8361** [comment]
Done.
