### ISSUE TITLE
Threadpool: High CPU usage in spin-wait for work items

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#5928]
High CPU usage in ThreadpoolMgr::UnfairSemaphore::Wait when the thread pool receives work items in bursts and the work item queue becomes empty between bursts. Repro:

``` c#
        int maxWorkItemCount = 2;
        int workItemCount = 0;
        var allWorkItemsQueued = new ManualResetEvent(false);
        var allWorkItemsProcessed = new AutoResetEvent(false);

        WaitCallback DoWork = state =>
        {
            allWorkItemsQueued.WaitOne();
            if (Interlocked.Decrement(ref workItemCount) == 0)
                allWorkItemsProcessed.Set();
        };

        while (true)
        {
            Interlocked.Exchange(ref workItemCount, maxWorkItemCount);
            for (int i = 0; i < maxWorkItemCount; ++i)
                ThreadPool.QueueUserWorkItem(DoWork);
            allWorkItemsQueued.Set();
            allWorkItemsProcessed.WaitOne();
            allWorkItemsQueued.Reset();
        }
```

I believe the spinning allows threads that recently completed work to be used again, to avoid a context switch, and to allow old threads to remain idle and be considered for termination. This doesn't seem to work very well when work items come in as bursts with idle time in-between bursts.

**Comment by choikwa** [comment]
Looking at UnfairSemaphore::Wait(), it looks like it has 3 while loops. The middle while loop does the spin and appears to be a polling loop and not a busy-waiting loop. It would be interesting to see how many threads are spinning vs. waiting. I found the comment in the else section confusing (not sure if Windows SleepEx specific).

>                         // We yield to other threads using SleepEx rather than the more traditional SwitchToThread.
                        // This is because SwitchToThread does not yield to threads currently scheduled to run on other
                        // processors.  On a 4-core machine, for example, this means that SwitchToThread is only ~25% likely
                        // to yield to the correct thread in some scenarios.
                        // SleepEx has the disadvantage of not yielding to lower-priority threads.  However, this is ok because
                        // once we've called this a few times we'll become a "waiter" and wait on the CLRSemaphore, and that will
                        // yield to anything that is runnable.

Also, in the the spinner, this appears to be a rather unnecessarily expensive way to calculate spinLimit.
```
                    double spinnersPerProcessor = (double)currentCounts.spinners / ThreadpoolMgr::NumberOfProcessors;
                    int spinLimit = (int)((m_spinLimitPerProcessor / spinnersPerProcessor) + 0.5);
                    if (numSpins >= spinLimit)
```

A cursory perf annotate shows it lighting up with two double precision divides (divsds) on x86. I'm not sure if this code was intentional (annotate shows nothing), but above can be simplified to integer multiply and shifts. Clang/LLVM Compiler didn't seem to catch this.

**Comment by sdmaclea** [comment]
@kouvel Testing on arm64 switching UnfairSemaphore to ClrSemaphore showed no performance degradation on the one ASP.NET benchmark I was using.  The UnfairSemaphore design seems to favor low CPU count (2-4) processors.

**Comment by kouvel** [comment]
Yea it needs to be a proper LIFO semaphore. Currently it uses spinning to imitate that and it doesn't work very well.

**Comment by sdmaclea** [comment]
I have an optimization drafted which helps a bit.  In the scenario I was testing, it reduced sensitivity to spin count allowing it to be reduced substantially on 48 core.  I am chasing another bigger issue so I am not quite prepared to upload it.

**Comment by kouvel** [comment]
In CoreRT, @jkoritzinsky implemented the unfair semaphore (or LIFO semaphore as it's called there) using I/O completion ports. Perhaps the same thing can be done in CoreCLR to eliminate the spinning altogether.

**Comment by sdmaclea** [comment]
IOCP is not directly available on Linux, but perhaps PAL could provide reasonable emulation @janvorli Is this already implemented, planned or feasible.

**Comment by janvorli** [comment]
We don't have IOCP implemented in PAL and there are no plans to add it. As for feasibility to implement that on Linux, I don't have a clear idea on that. But it looks like it depends on Windows ThreadPool that isn't implemented in PAL either, so it seems it would be a pretty complex change.

**Comment by kouvel** [comment]
On Linux since the PAL has control over the wait queue, for this purpose it could be tweaked to offer a LIFO semaphore. IOCP is just a handy way of implementing that on Windows.
