### ISSUE TITLE
Threadpool: High CPU usage in work stealing queue

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#5930]
High CPU usage in `ThreadPoolWorkQueue.Dequeue` and `ThreadPoolWorkQueue+WorkStealingQueue.TrySteal`. This is more noticeable when the minimum worker thread count is set to a high number, and fast-running work is queued. Perhaps more threads than required are awakened, and once the queued work is depleted by some threads, the remaining awakened threads spin for more work. Perhaps there is also too much spinning happening. Repro:

``` c#
        // Increase the min worker threads to increase the CPU impact of Dequeue/TrySteal
        //     set COMPlus_ThreadPool_ForceMinWorkerThreads=500

        int maxWorkItemCount = Environment.ProcessorCount;
        int workItemCount = 0;
        var allWorkItemsProcessed = new AutoResetEvent(false);

        WaitCallback DoWork = state =>
        {
            if (Interlocked.Decrement(ref workItemCount) == 0)
                allWorkItemsProcessed.Set();
        };

        while (true)
        {
            Interlocked.Exchange(ref workItemCount, maxWorkItemCount);
            for (int i = 0; i < maxWorkItemCount; ++i)
                ThreadPool.QueueUserWorkItem(DoWork);
            allWorkItemsProcessed.WaitOne();
        }
```

**Comment by benaadams** [comment]
Was seeing this in https://github.com/dotnet/coreclr/pull/5156#issuecomment-220880511

**Comment by benaadams** [comment]
May also be cache line thrashing on the queues from false sharing as there is no padding on the SpinLock https://github.com/dotnet/coreclr/pull/5938 or the queue entries

**Comment by benaadams** [comment]
May also be cache line thrashing on the queues from false sharing as there is no padding on the SpinLock https://github.com/dotnet/coreclr/pull/5938 or the queue entries https://github.com/dotnet/coreclr/pull/5943

**Comment by benaadams** [comment]
Resolved by https://github.com/dotnet/coreclr/pull/5943 ?

**Comment by benaadams** [comment]
There are also high costs in the native "thread start"/reuse

High thread count native costs high in ThreadpoolMgr::WorkerThreadStart
4 Cores
![](https://aoa.blob.core.windows.net/aspnet/threadpoolnative.png)

8 HT Cores (4 Cores)
![](https://aoa.blob.core.windows.net/aspnet/threadpoolnative-3.png)

**Comment by kouvel** [comment]
#9279 seems to have fixed a chunk of this. The rest is just a result of iterating other threads' queues, which probably can't be helped with the current design.

**Comment by stephentoub** [comment]
> The rest is just a result of iterating other threads' queues, which probably can't be helped with the current design.

There are various things we could explore doing here if this becomes a real issue, e.g.
- Limit the number of other threads' queues each thread is able to search.  This would result in decreased searching costs at the expense of some work items potentially not getting stolen.  The problem today is that, in the worst case, the search across the pool is O(N^2): if N threads run out of work, each of them will examine N threads' queues.
- Having a thread steal multiple items at the same time, using one and pushing the rest into its own queue for others to steal from it.  Especially if we did the limited search above, this could potentially help to spread things out.

**Comment by kouvel** [comment]
In this worst case example, I was seeing about 9% time taken in TryDequeue, most of which was in walking other threads' queues, which are all empty. If I remember correctly, before I was seeing about 30-50% time spent there. I was also thinking of a couple of things if we continue to see this being an issue:
- To help cases where most of the work items are not local, could keep a total count of thread-local work items and avoid walking
- When a work item is stolen, perhaps that thread could move some items to the global queue

It would be good to revisit the thread pool as a whole at some point.

**Comment by kouvel** [comment]
Maybe if threads are available for work, a new work item could go into the global queue to avoid having those threads search the local queues, or having some limit on how many items go into the local queue before they start going into the global queue. It would be good to create a comprehensive perf suite that uses the thread pool in all sorts of ways to measure throughput/latency to see the effects of experimentation and direct choices, for other issues too, like handling blocking work, bursty work, long CPU-bound work, etc., all of which the thread pool has issues with.

**Comment by benaadams** [comment]
> perhaps that thread could move some items to the global queue

This could greatly increase the contention on multi-core and NUMA

**Comment by benaadams** [comment]
May want to also entertain NUMA queues, when nodes exist; rather than a single global queue - with stealing between the NUMA queues.

Likely would need to affinitize the threadpool threads to a node and queue to local NUMA queue; with the VM releasing a correct node affinitized thread based on node reporting rather than a general demand for threads by the pool. So wouldn't be a simple change.

Currently the easiest way to make use of numa nodes is to launch a process per node; which is affinized to it (via a [Jobs for control over other factors like memory](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684161%28v=vs.85%29.aspx))

But that doesn't provide even utilization as work needs to be split between processes and isn't easily shared as well as being an advanced implementation; whereas machines with NUMA nodes aren't uncommon in servers. Something also to consider...

**Comment by kouvel** [comment]
> This could greatly increase the contention on multi-core and NUMA

Depends on the scenario, if one thread is generating a lot more work than others, it won't be able to handle all of its own work, moving some to the global queue could help out
