### ISSUE TITLE
Coreclr has missing FPREG entries causing the build to fail on FreeBSD

### ISSUE THREAD

**Issue by josteink** [dotnet/coreclr#594]
I'm creating a separate issue/bug for this, because I'd like it to get some scrutiny.

I did hack a little bit at this myself, but I literally have zero experience doing direct FPU-programming. While I've fixed the related compiler-warnings and errors, I can in no way guarantee that the following code is correct:

````c++
// from x86/fpu.h: struct __envxmm64
#define FPREG_ControlWord(uc)   (((savefpu*)((uc)->uc_mcontext.mc_fpstate))->sv_env.en_cw)
#define FPREG_StatusWord(uc)    (((savefpu*)((uc)->uc_mcontext.mc_fpstate))->sv_env.en_sw)
#define FPREG_TagWord(uc)       (((savefpu*)((uc)->uc_mcontext.mc_fpstate))->sv_env.en_tw)
#define FPREG_ErrorOffset(uc)   (((savefpu*)((uc)->uc_mcontext.mc_fpstate))->sv_env.en_rip)                 // *(DWORD*)&((uc)->__fpregs_mem.rdp)
#define FPREG_ErrorSelector(uc) *((WORD*) &(((savefpu*)((uc)->uc_mcontext.mc_fpstate))->sv_env.en_rip) + 2) // *(((WORD*)&((uc)->__fpregs_mem.rip)) + 2)
#define FPREG_DataOffset(uc)    (((savefpu*)((uc)->uc_mcontext.mc_fpstate))->sv_env.en_rdp)                 // *(DWORD*)&((uc)->__fpregs_mem.rdp)
#define FPREG_DataSelector(uc)  *((WORD*) &(((savefpu*)((uc)->uc_mcontext.mc_fpstate))->sv_env.en_rdp) + 2) // *(((WORD*)&((uc)->__fpregs_mem.rdp)) + 2)
#define FPREG_MxCsr(uc)         (((savefpu*)((uc)->uc_mcontext.mc_fpstate))->sv_env.en_mxcsr)
#define FPREG_MxCsr_Mask(uc)    (((savefpu*)((uc)->uc_mcontext.mc_fpstate))->sv_env.en_mxcsr_mask)
````

(From https://github.com/josteink/coreclr/commit/3dab47d18a16742ce618cea8d996cfc861e7bccc )

Especially [these lines](https://github.com/josteink/coreclr/blob/3dab47d18a16742ce618cea8d996cfc861e7bccc/src/pal/src/arch/i386/context.cpp#L143-L146) where the original code I based it on had lots of pointer-magic going on, I have no idea if are translated correctly.

Any feedback or assistance on this issue would be appreciated.

**Comment by josteink** [comment]
With that PR merged, we have 10 out of 11 registers worked out. Only 1 left to go. I've given it a try, but I don't really feel like I'm making any headway.

Anyone else care to have a look at this? @ajensenwaud ? @kangaroo ? @janhenke ?

**Comment by janhenke** [comment]
I will try to take a look later. No promise on a solution though.

**Comment by janhenke** [comment]
I did not come any further on this issue yet, if anybody else has an idea, be my guest. FPU/SSE/AVX state handling is also something new for me.

**Comment by josteink** [comment]
Anyone else willing to take a cursory look at this one?

@edmaste : You're already involved with FreeBSD and the LLVM-projects. Any chance you could contribute here, or find other suitable candidates?

Any help is appreciated. This is literally the last compilation bug to get coreclr into the linking-phase on FreeBSD.

**Comment by josteink** [comment]
Anyone else willing to take a cursory look at this one?

@emaste : You're already involved with FreeBSD and the LLVM-projects. Any chance you could contribute here, or find other suitable candidates?

Any help is appreciated. This is literally the last compilation bug to get coreclr into the linking-phase on FreeBSD.

**Comment by ajensenwaud** [comment]
I already had a look over the last week but am not familiar enough with FPREG to fix it.

Anders Jensen-Waud

**Comment by emaste** [comment]
Which one is still missing? I'll try to take a look but haven't set up a build environment for this so can't easily check the remaining error.

**Comment by josteink** [comment]
This is the part where we're literally missing one line of code:

https://github.com/dotnet/coreclr/blob/master/src/pal/src/include/pal/context.h#L128-L144

**Comment by emaste** [comment]
I think you want sv_fp[index].fp_acc

**Comment by josteink** [comment]
That seems to build! That's *awesome*! Thanks for the help!

I'll prepare a PR to close this issue now :)

**Comment by janvorli** [comment]
LGTM, it is great to see to have the compilation issues behind us :-)

**Comment by josteink** [comment]
@janvorli  Did you mean to comment on PR? :)

**Comment by janvorli** [comment]
@josteink I am sorry, I keep mixing PRs with issues.
