### ISSUE TITLE
RyuJIT x86: NYI: "Hi and Lo cannot be reordered"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#5957]
File: coreclr\src\jit\lower.cpp: 1901

When we push the args of a call, we push the hi part of the arg first, then the lo part. In doing this, we perform any hi arithmetic before the lo. If an arg is a long add or sub, we cannot reorder the operations. The lo operation needs to be performed first, saved, then the hi can be performed and pushed, followed by the lo.

**Comment by BruceForstall** [comment]
This NYI was removed (and fixed) with the LIR work #6689.
