### ISSUE TITLE
ARM64 R2R: Assertion failed 'varDsc->lvOnFrame'

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#5967]
Repro
1. set RunCrossGen=1
2. JIT\jit64\hfa\main\testA\hfa_sd2A_d\hfa_sd2A_d.cmd -coreroot r:\coreclrdbg

Assert failure(PID 6444 [0x0000192c], Thread: 2528 [0x09e0]): Assertion failed 'varDsc->lvOnFrame' in 'DomainBoundILStubClass:IL_STUB_PInvoke(float,double,float,double,float,double,float,double,float,double,float,double,float,struct):double' (IL size 160)

    File: f:\coreclrgit\coreclr\src\jit\codegenarm64.cpp Line: 6509
    Image: r:\coreclrdbg\CoreRun.exe

**Comment by rahku** [comment]
Current copy of coreclrtests.zip has a bug in JIT\jit64\hfa\main\testA\hfa_sd2A_d\hfa_sd2A_d.cmd file.
Due to which it will throw FileNotFoundException at the time of crossgen. To fix this replace following in file JIT\jit64\hfa\main\testA\hfa_sd2A_d\hfa_sd2A_d.cmd
/Platform_Assemblies_Paths %CORE_ROOT%;%~dp0
with 
/Platform_Assemblies_Paths %CORE_ROOT%;%cd%

**Comment by rahku** [comment]
This is affecting following 12 tests:
JIT\jit64\hfa\main\testA\hfa_sd2A_d\hfa_sd2A_d.cmd
JIT\jit64\hfa\main\testA\hfa_sd2A_r\hfa_sd2A_r.cmd
JIT\jit64\hfa\main\testA\hfa_sf2A_d\hfa_sf2A_d.cmd
JIT\jit64\hfa\main\testA\hfa_sf2A_r\hfa_sf2A_r.cmd
JIT\jit64\hfa\main\testB\hfa_sd2B_d\hfa_sd2B_d.cmd
JIT\jit64\hfa\main\testB\hfa_sd2B_r\hfa_sd2B_r.cmd
JIT\jit64\hfa\main\testB\hfa_sf2B_d\hfa_sf2B_d.cmd
JIT\jit64\hfa\main\testB\hfa_sf2B_r\hfa_sf2B_r.cmd
JIT\jit64\hfa\main\testC\hfa_sd2C_d\hfa_sd2C_d.cmd
JIT\jit64\hfa\main\testC\hfa_sd2C_r\hfa_sd2C_r.cmd
JIT\jit64\hfa\main\testC\hfa_sf2C_d\hfa_sf2C_d.cmd
JIT\jit64\hfa\main\testC\hfa_sf2C_r\hfa_sf2C_r.cmd

**Comment by rahku** [comment]
These test pass without R2R.

**Comment by kyulee1** [comment]
This is dup of https://github.com/dotnet/coreclr/issues/5639
