### ISSUE TITLE
Fix remaining switch related warnings in jitter

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#598]
There is a group of warnings disabled by the -Wno-switch compiler option in the jitter. These warnings are due to switch commands on enum that don't handle all possible values of the enum (either by using the default case or explicitly having case statement for each enum value).
To get to the warning free state, we need to fix these.
To get the warnings reported during build, the following line needs to be deleted from the root CMakeLists.txt:
add_compile_options(-Wno-switch)

**Comment by briansull** [comment]
I am investigating this issue

**Comment by jasonwilliams200OK** [comment]
#855 is merged; suggests closing this issue.
