### ISSUE TITLE
Compiler::gtUpdateSideEffects is incorrect.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#5999]
https://github.com/dotnet/coreclr/blob/master/src/jit/gentree.cpp#L7114

The intent of this function is to update the side effects for a tree after one of its children has been rewritten. Unfortunately, it is broken in two significant ways:
- It does not take into account side-effects from the siblings of the rewritten tree
- It does not take into account side-effects from the parent node itself

As a concrete example, consider the following tree:

```
               [000036] ------------                /--*  const     int    -1
               [000037] ---XG----U--             /--*  +_ovfl    int   
               [000034] ------------             |  |  /--*  lclVar    int    V01 loc0         
               [000035] ---XG----U--             |  \--*  +_ovfl    int   
               [000032] ------------             |     |  /--*  const     int    0
               [000033] ---XG-------             |     \--*  []        int   
               [000031] ------------             |        \--*  lclVar    ref    V02 loc1         
               [000039] -A-XG-------             *  =         int   
               [000038] D------N----             \--*  lclVar    int    V03 loc2
```

If the array index expression was hoisted to a temp and replaced with a use of the temp, the tree should become something like:

```
               [000036] ------------                /--*  const     int    -1
               [000037] ---XG----U--             /--*  +_ovfl    int   
               [000034] ------------             |  |  /--*  lclVar    int    V01 loc0         
               [000035] ---X-----U--             |  \--*  +_ovfl    int   
               [000033] ------------             |     \--*  lclVar    int    V04 tmp0         
               [000039] -A-XG-------             *  =         int   
               [000038] D------N----             \--*  lclVar    int    V03 loc2
```

In particular, note that both adds still have the exception flag set. Unfortunately, if `gtUpdateSideEffects` was called with the original array index expression and its replacement temp, it would produce the following tree:

```
               [000036] ------------                /--*  const     int    -1
               [000037] ---------U--             /--*  +_ovfl    int   
               [000034] ------------             |  |  /--*  lclVar    int    V01 loc0         
               [000035] ---------U--             |  \--*  +_ovfl    int   
               [000033] ------------             |     \--*  lclVar    int    V04 tmp0         
               [000039] -A----------             *  =         int   
               [000038] D------N----             \--*  lclVar    int    V03 loc2
```

In particular, `oldGtFlags` would be `GTF_EXCEPT | GTF_GLOB_REF` and `newGtFlags` would be `0`. The body of the loop would then walk up the ancestors of the new tree, clearing the flags in `oldGtFlags` and setting those in `newGtFlags`. This information might lead further phases to make incorrect decisions about e.g. code motion.

I haven't found an example of SBCG caused by this bug in the wild. The problematic function is only used during array length and runtime type handle propagation, so any bugs that may exist would be rooted therein.

**Comment by pgavlin** [comment]
cc @dotnet/jit-contrib 

The larger issue at hand here is whether or not it is even possible to recompute the side-effect flags for a particular node. in other words, given an arbitrary IR node and a set of side-effect flags, can we compute which flags are set due that node (not its children)?

**Comment by mikedn** [comment]
> given an arbitrary IR node and a set of side-effect flags, can we compute which flags are set due that node (not its children)?

I don't think there's any such functionality right now. Side effect flags are set all other the place in the importer and in morpher. One would need to collect all the set flags logic from those places and put it in a reusable function. Trouble is, those places that set the flags now have more information available and not all of it is preserved. 

For example, `STIND` is imported as `GT_ASG` with `GTF_EXCEPT` but `GT_ASG` is also used for `STLOC` which doesn't need `GTF_EXCEPT`.

**Comment by pgavlin** [comment]
> I don't think there's any such functionality right now.

I agree.

> Trouble is, those places that set the flags now have more information available and not all of it is preserved.

Yes, exactly. A moderately straightforward solution might be to add a second field on non-leaf nodes to track the side effects that a node contributes directly, then replace direct writes to `gtFlags` with an accessor that appropriately updates both the "node" and "tree" flags. The node flags could then be used when recomputing (and checking) the tree flags.

**Comment by mikedn** [comment]
>  A moderately straightforward solution might be to add a second field on non-leaf nodes to track the side effects that a node contributes directly,

Yes, but that increases the size of tree nodes. Unfortunately there aren't many alternatives.

I wonder how often are side effects queried, maybe tree side effects could be computed only when needed and the gtFlags would simply store the node's own side effects.

**Comment by pgavlin** [comment]
> Yes, but that increases the size of tree nodes. Unfortunately there aren't many alternatives.

After considering the side effect flags themselves, it looks like the only two flags that we could at least derive `GTF_CALL` and `GTF_ASG` can be from `gtOper` (certainly the latter, which is rooted at `GT_ASG` and block operation nodes). If we could find three spare bits in `gtFlags`--say, for example, the bits used by `GTF_REDINDEX_CHECK`, `GTF_ZSF_SET`, and `GTF_SET_FLAGS/GTF_IND_NONFAULTING`--we could stash the node flags in `gtFlags` as well as the tree flags. It looks like we might also be able to use the bit used by `GTF_DEAD` with a very minor change to CSE (i.e. instead of setting the `GTF_DEAD` flag on removed trees, just rely on the check that `tree->gtCSEnum == NO_CSE`, which should be equivalent).

> I wonder how often are side effects queried, maybe tree side effects could be computed only when needed and the gtFlags would simply store the node's own side effects.

In general the side effect flags are queried any time the JIT needs to perform code motion. This includes (but is probably not limited to) the importer, loop hoisting, CSE, morph, and any code that calls `gtSetEvalOrder`. Unfortunately, I expect that the time cost due to the query (incl. any memory cost implied by making the query non-recursive) would be more prohibitive than the cost of adding a field to non-leaf nodes.

**Comment by pgavlin** [comment]
After further thought, I think that the cleanest thing to do is move the four debug-only flags--`GTF_MORPHED`, `GTF_NODE_SMALL`, GTF_NODE_LARGE`, and `GTFD_VAR_CSE_REF` into a new field (and a new namespace) that is only available in debug builds. The three bits freed up by the first three flags can then be used for the node side effect flags.

**Comment by mikedn** [comment]
>  I think that the cleanest thing to do is move the four debug-only flags--GTF_MORPHED, GTF_NODE_SMALL, GTF_NODE_LARGE, andGTFD_VAR_CSE_REF` into a new field 

Sounds great.

>  for example, the bits used by GTF_REDINDEX_CHECK, GTF_ZSF_SET, and GTF_SET_FLAGS/GTF_IND_NONFAULTING

`GTF_ZSF_SET` and `GTF_SET_FLAGS` are currently used only by the legacy backend but one of them may be needed for decomposition. And the other one might be needed to avoid compare instructions when the necessary CPU flags are already available from a previous instruction.

**Comment by CarolEidt** [comment]
> it looks like the only two flags that we could at least derive GTF_CALL and GTF_ASG can be from gtOper (certainly the latter, which is rooted at GT_ASG and block operation nodes).
These are not node-specific. They indicate that the tree _contains_ a call or asg, not (just) that the node itself might be such a thing.

**Comment by pgavlin** [comment]
> These are not node-specific. They indicate that the tree contains a call or asg, not (just) that the node itself might be such a thing.

Yes. What I meant was that whether or not the node itself contributes to this flag can be derived from the node's operator--the flag itself would still take into account the node's child trees.

**Comment by CarolEidt** [comment]
@pgavlin - got it, thanks.

**Comment by erozenfeld** [comment]
#13668 fixed gtUpdateSideEffects to be conservatively correct for all flags and exact for GTF_EXCEPT and GTF_ASG. It also enabled checking of GTF_EXCEPT and GTF_ASG in fgDebugCheckFlags.
The work to do the same for the remaining side effect flags is tracked by #17794, #17795, #17796. The work to enable checking of side effect flags in LIR is tracked by #17797.
Closing this issue.
