### ISSUE TITLE
Unable to #define MEASURE_GCINFO

### ISSUE THREAD

**Issue by mattwarren** [dotnet/coreclr#6008]
It appears that when you add `#define MEASURE_GCINFO` to the source, the code no longer compiles? 

This is because some of the code within `#ifdef MEASURE_GCINFO` guard clauses is invalid. To make it compile, I had to make this change in [gcinfoencoder.h](https://github.com/dotnet/coreclr/blob/master/src/inc/gcinfoencoder.h#L95-L138)
``` diff
 struct GcInfoSize
     ....
     size_t ChunkTransitionSize;

     GcInfoSize();
-    GcInfoSize& operator+=(GcInfoSize& other);
+    GcInfoSize& operator+=(const GcInfoSize& other);
     void Log(DWORD level, const char * header);
 };
```

plus this one in [gcinfoencoder.cpp](https://github.com/dotnet/coreclr/blob/master/src/gcinfo/gcinfoencoder.cpp#L337)
``` diff
- GcInfoSize& operator+=(const GcInfoSize& other)
+ GcInfoSize& GcInfoSize::operator+=(const GcInfoSize& other)
```

Also various logging statements in [gcinfoencoder.cpp](https://github.com/dotnet/coreclr/blob/master/src/gcinfo/gcinfoencoder.cpp) need to be removed because they refer to fields that don't exist in `GcInfoSize`, such as `UntrackedSlotSize`, `NumUntrackedSize` and `EncPreservedSlots`

I don't know enough C++ to send a PR and more importantly I'm not sure if this code is even meant to be activated? But I just wanted to point it out.

**Comment by mattwarren** [comment]
And (possible) related, but if I also `#define VERIFY_GCINFO`, I get the following error:

```
c:\coreclr\src\gcinfo\gcinfoencoder.cpp(454): error C2664: 'DbgGcInfo::GcInfoEncoder::GcInfoEncoder(DbgGcInfo::GcInfoEncoder &&)': cannot convert argument 3 from 'IAllocator *' to 'IJitAllocator *' [C:\coreclr\bin\obj\Windows_NT.x64.Debug\src\gcinfo\lib\gcinfo.vcxproj]
  c:\coreclr\src\gcinfo\gcinfoencoder.cpp(454): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
```

**Comment by mattwarren** [comment]
Is there any interest in this, does it even need to be fixed?

If not, I'm happy to close it. The the errors only happen when you explicitly add `#define MEASURE_GCINFO` to the source.

**Comment by janvorli** [comment]
@jkotas do you think this define might be useful in the future and so it is worth fixing or should we just remove it?

**Comment by jkotas** [comment]
I think it may be potentially useful. @swaroop-sridhar is about to work on tweaks for gcinfo encoding and may find it useful.

**Comment by RussKeldorph** [comment]
@pgavlin @dotnet/jit-contrib FYI

**Comment by mazong1123** [comment]
@jkotas I'm willing to work on this issue. However, in my mind this kind of change may require a unit test to verify it. I'm not able to find any test or unit test for this module under test/src. Could you please guide me where should I add the tests?

Moreover, seems like there's no tests for native code under test/src directory. Am I missing something or we just test the native part from managed code on purpose?

**Comment by jkotas** [comment]
@swaroop-sridhar Have you used `MEASURE_GCINFO` during your recent GCInfo changes? What do you think would make most sense here?

**Comment by swaroop-sridhar** [comment]
@jkotas I did not use the MEASURE_GCINFO measurement much -- I only used the TotalBytes written count. However, I did fix the MEASURE_GCINFO code for the ReturnKind and RevPInvokeFrame info.

@mazong1123: I think it is a good idea to get MEASURE_GCINFO working, and its great you've come forward to do it.

I'm not sure what you mean by test case -- We can observe the log-spew wrt GcInfo size for any method. Do you mean: (a) Doing a MEASURE_GCINFO build regularly to ensure that it is not broken, or (b) comparing the GCInfo measurement log with a fixed baseline for some tests?

**Comment by jkotas** [comment]
It should be fine to unconditionally enable `MEASURE_GCINFO` in debug builds.

**Comment by mazong1123** [comment]
@swaroop-sridhar For test case, I don't know if it is applicable to this particular case, but in my mind it should cover:

1. When MEASURE_GCINFO enabled, the code should be compiled correctly.
2. When MEASURE_GCINFO disabled, the code should be compiled correctly.
3. When MEASURE_GCINFO enabled, all functions within #ifdef MEASURE_GCINFO should work correctly. For instance, in one of our test cases, we should:
1. \#define MEASURE_GCINFO
2. Prepare a GCInfoSize instance.
3. call GcInfoSize& operator+=(const GcInfoSize& other), pass the prepared GCInfoSize instance in.
4. Validate the outcome - if it is as expect.

If this can be achieved, we may eliminate any manual measurement. The test cases will help us to validate the logic every time a change made.

**Comment by swaroop-sridhar** [comment]
Probably the best way to test this feature is to set up a lab job that:
a) Does a debug build with MEASURE_GCINFO defined
b) Runs crossgen on System.Private.Corlib.dll (and prints the cumulative GCInfo size data).

Since GCInfo doesn't change often, it is sufficient to run this job once a week or fortnight (plus on demand). It would be good to keep track of the size this way too. 
@jashook what do you think having this job in the lab? 

@mazong1123 if you can get MEASURE_GCINFO to work correctly and print the relevant results (run crossgen locally for interim testing), we can then setup the lab job to do the testing routinely.

**Comment by jkotas** [comment]
> Does a debug build with MEASURE_GCINFO defined

This is way to expensive for the value that it provides. If we want to make sure that `MEASURE_GCINFO` works fine, we should build it by default into debug builds.

**Comment by swaroop-sridhar** [comment]
OK we can do that too. 
@mazong1123 can you please put the code under the DEBUG switch instead of MEASURE_GCINFO. 
The results can be printed under a COMPlus switch.
Since we can test it by running almost any test, I don't think adding new tests are necessary for it. Thanks.

**Comment by mazong1123** [comment]
@swaroop-sridhar  OK I'll do that.
