### ISSUE TITLE
*_PROFILER_PATH should come in 32 and 64 bit flavors

### ISSUE THREAD

**Issue by MattWhilden** [dotnet/coreclr#601]
As per @sawilde over on #445:
Do you know why *_PROFILER_PATH doesn't come in 32 and 64 bit versions - it limits this feature as the processes being profiled could be a combination of both but you can only register one.

**Comment by noahfalk** [comment]
Hi @sawilde
I certainly agree, 32 and 64 bit versions are more useful. Interestingly we made a similar change for the full CLR not long ago and Jan just integrated it.
https://github.com/dotnet/coreclr/pull/607
That change only modified the environment variables for full CLR and you probably want to make a similar change to CoreCLR. We’d probably get to porting it eventually, but also happy to review a PR if you want to test a similar change yourself. 

Thanks!
  -Noah

**Comment by MattWhilden** [comment]
@noahfalk I'm adding you as the "assignee" so that if someone picks this up they'll know who to bother about PRs and questions. Let me know if this is in error.
