### ISSUE TITLE
RyuJIT: Methods that store to arguments can't be inlined

### ISSUE THREAD

**Issue by redknightlois** [dotnet/coreclr#6014]
EDIT: Modified after figuring out the reason. 

The following code wont be inlined because the arguments are modified inside the method body:
```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
private static void WildCopy(byte* dest, byte* src, byte* destEnd)
{
    // This copy will use the same data that has already being copied as source
    // It is more of a repeater than a copy per-se. 

    do
    {
        *((ulong*)dest) = *((ulong*)src);
        dest += sizeof(ulong);
        src += sizeof(ulong);
    }
    while (dest < destEnd);
}
```

However this code which clone the arguments is inlined without questions:

```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
private static void WildCopy(byte* destPtr, byte* srcPtr, byte* destEndPtr)
{
    byte* dest = destPtr;
    byte* src = srcPtr;
    byte* destEnd = destEndPtr;

    // This copy will use the same data that has already being copied as source
    // It is more of a repeater than a copy per-se. 

    do
    {
        *((ulong*)dest) = *((ulong*)src);
        dest += sizeof(ulong);
        src += sizeof(ulong);
    }
    while (dest < destEnd);
}
```

**Comment by mikedn** [comment]
I haven't checked but I doubt this has anything to do with pointers. The first version is not inlined because the method modifies its arguments.

**Comment by redknightlois** [comment]
I'll check in a minute and let you know. However in that case, it should still be eligible for inlining as the pointers are passed by value. There is nothing that prevents the JIT to realize that.

**Comment by cmckinsey** [comment]
There is a limitation in the inlined mechanics when parameters are written in the method body. It's on the list of things to fix. I'm certain there is a TFS work-item tracking this, not sure about Github. @AndyAyersMS

**Comment by redknightlois** [comment]
Confirmed, using pointers copies works. :) 

Now I know why and can make changes in the code to account for that

**Comment by AndyAyersMS** [comment]
Inlining is currently blocked by STARG in the callee. In principle, it should be easy to remove this restriction, since the jit will inline calles with LDARGA, which should present similar issues. 

@JosephTremoulet looked into fixing this, and (IIRC) ran into some complications.

We don't have a GitHub issue open for this, so @redknightlois feel free to create one.

**Comment by redknightlois** [comment]
@AndyAyersMS Should we just edit this one?

**Comment by JosephTremoulet** [comment]
I didn't get very far into my investigation before getting pulled off to other things.  My first naive attempt to test the hypothesis by copying some code from the ldarga-handling paths to starg-handling paths fixed a unit test but had errors compiling pretty much anything else; for all I know the issues were trivial.

**Comment by AndyAyersMS** [comment]
Sure. Updated title....

**Comment by AndyAyersMS** [comment]
Oops, didn't mean to overwrite your update -- forgot to hit save and when I did I saw you'd already updated.

**Comment by redknightlois** [comment]
@AndyAyersMS Yours is better :)

**Comment by choikwa** [comment]
Is a viable fix for this creating temp copies for pass-by-value arguments and letting subsequent opt passes take care of redundant copies?

**Comment by AndyAyersMS** [comment]
More or less, yes. 

There are already many other cases that require a temp. See `fgInlinePrependStatements` and  `impInlineFetchLocal` for some analysis.

LDARGA is the most similar opcode, so support for STARG should parallel that...

**Comment by choikwa** [comment]
More trivial example:

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static int inlineMe(int a, int b, int c)
        {
            a = 1;
            return a + b + c;
        }
        public static void Main(string[] args)
        {
            int a = 0;
            int b = 1;
            int c = 2;
            
            int res = inlineMe(a, b, c);
            Console.WriteLine($"res={res}");
        }

JitDump:
> INLINER: Marking ConsoleApplication.Program:inlineMe(int,int,int):int as NOINLINE because of stores to argument
> INLINER: during 'fgInline' result 'failed this callee' reason 'stores to argument'

This is actually pretty bad. All that is required to invalidate inlining a callee was that a parameter was killed. After removing InlineObservation::CALLEE_STORES_TO_ARGUMENT, I'm getting type mismatch TYP_REF != TYP_LONG.

**Comment by jbayardo** [comment]
Hello. Is this going to be in 2.0, or are we getting it in 1.1?.

Thanks.

**Comment by AndyAyersMS** [comment]
It is there in 1.1, along with the must-throw/no-return changes.
