### ISSUE TITLE
Error during restoring packages on Ubuntu

### ISSUE THREAD

**Issue by AndreyAkinshin** [dotnet/coreclr#602]
I'm trying to install coreclr on Ubuntu 14.04 (https://github.com/dotnet/coreclr/wiki/Linux-instructions)

The command

```
$ mono nuget.exe restore -Source https://www.myget.org/F/dotnet-corefx/ -PackagesDirectory .
```
prints:
```
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
WARNING: Error: SendFailure (Error writing headers)
Unable to find version '4.0.0-beta-22703' of package 'System.Console'.
Unable to find version '4.0.0-beta-22703' of package 'System.Diagnostics.Contracts'.
Unable to find version '4.0.10-beta-22703' of package 'System.Diagnostics.Debug'.
Unable to find version '4.0.0-beta-22703' of package 'System.Diagnostics.Tools'.
Unable to find version '4.0.10-beta-22703' of package 'System.Globalization'.
Unable to find version '4.0.10-beta-22703' of package 'System.IO'.
Unable to find version '4.0.0-beta-22703' of package 'System.IO.FileSystem.Primitives'.
Unable to find version '4.0.10-beta-22703' of package 'System.Reflection'.
Unable to find version '4.0.0-beta-22703' of package 'System.Resources.ResourceManager'.
Unable to find version '4.0.20-beta-22703' of package 'System.Runtime'.
Unable to find version '4.0.10-beta-22703' of package 'System.Runtime.Extensions'.
Unable to find version '4.0.0-beta-22703' of package 'System.Runtime.Handles'.
Unable to find version '4.0.20-beta-22703' of package 'System.Runtime.InteropServices'.
Unable to find version '4.0.10-beta-22703' of package 'System.Text.Encoding'.
Unable to find version '4.0.10-beta-22703' of package 'System.Text.Encoding.Extensions'.
Unable to find version '4.0.10-beta-22703' of package 'System.Threading'.
Unable to find version '4.0.10-beta-22703' of package 'System.Threading.Tasks'.
```

Also I haven't found the dotnet-corefx feed on myget. What should I do for restoring packages?

**Comment by akoeplinger** [comment]
@AndreyAkinshin are you running the latest Mono 3.12? This is a common issue on earlier versions where the CA root certificates aren't imported in Mono's trust store automatically (you need to run `mozroots --import --sync`).

**Comment by AndreyAkinshin** [comment]
@akoeplinger,

> are you running the latest Mono 3.12?

Yes.

> you need to run `mozroots --import --sync`

It helps, thanks! Can you update the wiki?

**Comment by akoeplinger** [comment]
@AndreyAkinshin It should work automatically on Mono 3.12, presuming you've installed from the mono-project.com packages (there's an install hook in those packages that runs the new [cert-sync](http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync) tool, mozroots shouldn't be required anymore). Did you maybe compile Mono from source?

**Comment by AndreyAkinshin** [comment]
> Did you maybe compile Mono from source?

Yes.

**Comment by akoeplinger** [comment]
That explains it then ;) You should be able to run `sudo cert-sync /etc/ssl/certs/ca-certificates.crt` in that case to get the same effect.

**Comment by MattWhilden** [comment]
I've added a "NOTE" in the wiki. Let me know if you think that'll keep others from falling into this cleverly laid trap. :smile:

**Comment by akoeplinger** [comment]
@MattWhilden thanks :) Can we change the first part of the sentence to "This assumes you **installed Mono** from..." and link to the [specifc comment](https://github.com/dotnet/coreclr/issues/602#issuecomment-88203778) with the solution?

**Comment by MattWhilden** [comment]
Done. Let me know if anything else needs fixing up.

**Comment by saper** [comment]
Quick note: besides certificate installation, it seems that Mono fails on TLS when `TZ` environment variable is unset (should assume UTC). Running `env TZ=UTC mono ...` fixed the issues :/
