### ISSUE TITLE
Are there any zip for binary of basic x64 linux?

### ISSUE THREAD

**Issue by Thaina** [dotnet/coreclr#6023]
I try to use dotnet sdk in AWS Lambda by download binary zip at [dotnet/cli](/dotnet/cli#installers-and-binaries)

And it error on libunwind8 which I think it missing on lambda machine

AWS lambda machine can run any linux x64 binary. But it can put file only in specific folder and cannot download anything with yum, cannot even sudo, so it must use pure binary file with all library was packed in the same place

So, are there dotnet sdk binary in that version? with libunwind8 and anything already packed and don't need to use chmod or sudo to run anything?

If it not how can I pack it myself?

ps. AWS lambda can only upload 50mb of zip. So I use curl command to download SDK binary and extract it to run in aws lambda

**Comment by myungjoo** [comment]
Can't you simply put those libunwind*.so files that fit with your system appended into your "zip" file and make it ld-loaded at runtime?

**Comment by Thaina** [comment]
@myungjoo I'm not sure which folder dotnet will look for missing lib. Could I just to put all missing lib at the same folder as dotnet?

**Comment by myungjoo** [comment]
That wouldn't look beautiful, but that would work.
If that doesn't work, use LD_LIBRARY_PATH

**Comment by Thaina** [comment]
@myungjoo Thanks a lot

And could you please guide me how can I get all .so that dotnet depend on easily?

Most of my life I use windows so I'm not familiar with linux much

**Comment by myungjoo** [comment]
If libunwind is the only missing component you only need to extract .so files from the build of libunwind based on libraries you already use for your system. If you do not know what's missing, you need tedious work identifying what's missing.

**Comment by gkhanna79** [comment]
@janvorli Do you have suggestions on what else is required at runtime? libicu?

**Comment by janvorli** [comment]
The full list of transitive dependencies for the case you use dotnet core for Ubuntu 14.04 as a base is below (you'd need to get the binaries from an Ubuntu 14.04 installation in this case). 
libicudata.so.52
libicui18n.so.52
libcrypto.so.1.0.0
libicuuc.so.52
libkrb5.so.3
libgnutls.so.26
libsqlite3.so.0
libasn1.so.8
libkrb5.so.26
libgcrypt.so.11
libcurl.so.4
libssl.so.1.0.0
libldap_r-2.4.so.2
liblttng-ust.so.0
libhx509.so.5
libgssapi_krb5.so.2
libp11-kit.so.0
libgssapi.so.3
libidn.so.11
libhcrypto.so.4
libk5crypto.so.3
libwind.so.0
liblzma.so.5
libsasl2.so.2
librtmp.so.0
libroken.so.18
libtasn1.so.6
libunwind-x86_64.so.8
liblber-2.4.so.2
libheimbase.so.1
libunwind.so.8
libkrb5support.so.0
libcrypt.so.1
liblttng-ust-tracepoint.so.0
libheimntlm.so.0
libffi.so.6
liburcu-cds.so.1
liburcu-bp.so.1
libuuid.so.1
libgpg-error.so.0
libkeyutils.so.1
libcom_err.so.2

**Comment by myungjoo** [comment]
Dotnet/Coreclr is already mature enough to have various build-specifications for various Linux distros although many of they might not be "official".

It'd be natural to have "dist" directory and put some related (e.g., RPM *.spec files for Tizen, Redhat, Fedora, openSUSE, and so on, deb building files for Debian and Ubuntu) and maintain (or at least just keep them) them here.

Such "RPM spec" or debian-control files are required to have all dependencies (both run/install-time and build-time) for their corresponding Linux distros, which eases most of dockerizing or any other packaging processes.

Example: https://git.tizen.org/cgit/platform/upstream/coreclr/plain/packaging/coreclr.spec?h=tizen

**Comment by danmosemsft** [comment]
Tihs seems answered. feel free to reopen if not.
