### ISSUE TITLE
Console App with Dependency Injection

### ISSUE THREAD

**Issue by pantonis** [dotnet/coreclr#6026]
Hello. Where can I find an example of a .net core console app that uses Dependency Injection.
Cannot find anything online.

**Comment by adityamandaleeka** [comment]
Hi @pantonis, this area is intended for posting issues with the runtime. Perhaps you could try asking this question on the .NET Gitter or Slack? You can find links to them on the main page of the repo: https://github.com/dotnet/coreclr#chat-room

**Comment by pantonis** [comment]
thanks
