### ISSUE TITLE
RyuJIT: Throw block optimization does not hit on methods that only throw in their body.

### ISSUE THREAD

**Issue by redknightlois** [dotnet/coreclr#6028]
I noticed that blocks that have a throw statement are moved outside of the critical path. However, after further inspection it seems like the rearranging of the blocks is done without further analysis outside of the call site (which makes sense btw).

The problem is that the optimization is defeated by a pretty well known pattern used along the way in lots of software (even CoreFX). 

``` csharp
        private static void ThrowException( string message )
        {
            throw new Exception(message);
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static void DoesItReorder(int integer, string value)
        {
            if (integer < 0)
                ThrowException("message");

            Console.WriteLine("This is the body.");
            for (int i = 0; i < integer; i++)
            {
                if (i > 100)
                    ThrowException("message");

                Console.WriteLine($"Line {i}");
            }                
        }
```

I tend to believe this is by-design at the moment and I don't know if there is a solution for it without whole-program optimization, but wanted to raise it (even if it works for "documentation" of an edge case).

**Comment by mikedn** [comment]
> I tend to believe this is by-design at the moment and I don't know if there is a solution for it without whole-program optimization.

Yes, currently the JIT doesn't know that a method like `ThrowException` always throws therefore it cannot mark the caller block as cold. And it's true that normally this needs WPO but it's not impossible for the JIT to look at `ThrowException` and figure out what happens. In fact, the JIT already analyzes `ThrowException` for inline purposes and it's surprising that it didn't inline it in your example.

See the more or less related #1270.

**Comment by mikedn** [comment]
> It is inlining it, see the actual code (the original title was poorly written, that is why I edited it).

So this is an extension of #1270. The JIT should not inline `ThrowException` and it should know that `ThrowException` does not return and mark the caller block as cold.

**Comment by briansull** [comment]
@AndyAyersMS 
I am very surprised that the RyuJit is inlining a method that unconditionally throws.
I dont believe that this was the ace in older versions of the Jit.

**Comment by mikedn** [comment]
> I dont believe that this was the ace in older versions of the Jit.

The current JIT32 and JIT64 also inline such methods so this is not RyuJIT specific.

**Comment by briansull** [comment]
OK well then it is a good area to improve on.
When we consider such a method for inlining we should:
1: Decline to inline it 
2: Mark the block that  contains the call as RarelyRun

**Comment by mikedn** [comment]
This should have been fixed by #6103. I'll try to post the generated code for this assembly later today when I have some time.

**Comment by mikedn** [comment]
The code generated for `DoesItReorder` is now:
```
G_M52579_IG01:
       57                   push     rdi
       56                   push     rsi
       4883EC28             sub      rsp, 40
       8BF1                 mov      esi, ecx

G_M52579_IG02:
       85F6                 test     esi, esi
       7C59                 jl       SHORT G_M52579_IG07

G_M52579_IG03:
       48B978307A3895020000 mov      rcx, 0x295387A3078
       488B09               mov      rcx, gword ptr [rcx]
       E8EACBD95D           call     System.Console:WriteLine(ref)
       33FF                 xor      edi, edi
       85F6                 test     esi, esi
       7E3A                 jle      SHORT G_M52579_IG06

G_M52579_IG04:
       83FF64               cmp      edi, 100
       7F4E                 jg       SHORT G_M52579_IG08

G_M52579_IG05:
       48B9C033BF40F97F0000 mov      rcx, 0x7FF940BF33C0
       E86803435F           call     CORINFO_HELP_NEWSFAST
       48B980307A3895020000 mov      rcx, 0x295387A3080
       488B09               mov      rcx, gword ptr [rcx]
       897808               mov      dword ptr [rax+8], edi
       488BD0               mov      rdx, rax
       E880C70A5E           call     System.String:Format(ref,ref):ref
       488BC8               mov      rcx, rax
       E8B0CBD95D           call     System.Console:WriteLine(ref)
       FFC7                 inc      edi
       3BFE                 cmp      edi, esi
       7CC6                 jl       SHORT G_M52579_IG04

G_M52579_IG06:
       4883C428             add      rsp, 40
       5E                   pop      rsi
       5F                   pop      rdi
       C3                   ret

G_M52579_IG07:
       48B970307A3895020000 mov      rcx, 0x295387A3070
       488B09               mov      rcx, gword ptr [rcx]
       E841FBFFFF           call     Program:ThrowException(ref)

G_M52579_IG08:
       48B970307A3895020000 mov      rcx, 0x295387A3070
       488B09               mov      rcx, gword ptr [rcx]
       E82FFBFFFF           call     Program:ThrowException(ref)
       CC                   int3
```

**Comment by AndyAyersMS** [comment]
@mikedn very nice indeed.

I vaguely recall that there were still cases where the throws were not getting moved properly out of line. If you know of any, please open an issue with some examples.

**Comment by mikedn** [comment]
> I vaguely recall that there were still cases where the throws were not getting moved properly out of line. 

I'll look into this before closing this issue, I can use this example and switch to the legacy policy to see what's going on.

**Comment by mikedn** [comment]
@AndyAyersMS It looks like `fgInsertInlineeBlocks` manages to reset `BBF_RUN_RARELY` when inheriting the block weight from the call block (see `block->inheritWeight(iciBlock)` at line 22269). I don't know if inheriting is the right thing to do in the general case but it's clear that for throw blocks this should not be done.

I think that now this particular case won't be hit anymore. If the JIT does end up inlining a throw helper it is because it has more than one block and that likely means that the throw block won't be the first anymore and `modifyBBWeight` will be used instead of `inheritWeight`.

**Comment by mikedn** [comment]
An example of throw helper that currently is still inlined is this (rather contrived):
```C#
private static void ThrowException(string message)
{
    if (message == null)
        throw new Exception(message);
    else
        throw new Exception();
}
```
However, in this case the first block is a `BBJ_COND` and it will inherit the call block weight. The throw blocks won't be affected and they'll keep their `BBF_RUN_RARELY` flag.

So, we have 2 possible scenarios:
* the throw helper has a single block - it won't be inlined and the call block will have its `BBF_RUN_RARELY` flag set.
* the throw helper has multiple blocks - it might get inlined and the first inlined block will inherit the call block weight. But that first block is unlikely to be a throw block so there's probably no `BBF_RUN_RARELY` to loose.

I suppose we can declare this fixed unless we find a case where the first inlined block is not a throw block but has `BBF_RUN_RARELY` set for other reasons.

**Comment by benaadams** [comment]
@redknightlois This now is resolved?

@mikedn your non returning method with multiple throws can be resolved throw a second method, which also resolves too much being inlined on older runtimes? e.g.
```csharp
[MethodImpl(MethodImplOptions.NoInlining)] // For older runtimes
private static void GetException(string message)
{
    if (message != null)
        return new Exception(message);
    else
        return new Exception();
}

private static void ThrowException(string message)
{
    throw GetException(message);
}
```

**Comment by redknightlois** [comment]
Uffff, this is old!!! ```ThrowException``` now is marked as cold, so JIT is moving the code outside (or I got too automated to deal with that code and do not see the issue anymore). AFAIK @mikedn code is not automatically picked up yet (haven't checked though on 2.1 branch).

**Comment by mikedn** [comment]
> your non returning method with multiple throws can be resolved throw a second method, which also resolves too much being inlined on older runtimes? e.g.

I haven't tried that but yes, it looks like it should work.

**Comment by mikedn** [comment]
> AFAIK @mikedn code is not automatically picked up yet (haven't checked though on 2.1 branch).

I'm not sure what you mean. The PR was merged into master back in Aug 5 2016, 2.x branches have been created after that.

It's also present in .NET 4.7.1 x64 (x86 doesn't use RyuJIT)

**Comment by redknightlois** [comment]
My bad, it is picked too on 2.0 branch even if you have conditionals; wasn't on the 1.x branch when I tested that. Closing afaik this is done.
