### ISSUE TITLE
StackTrace only has one frame?

### ISSUE THREAD

**Issue by JakeGinnivan** [dotnet/coreclr#6029]
I am trying to get a stack trace for https://github.com/TestStack/TestStack.BDDfy

Am using this code:

```
try
{
    throw new Exception();
}
catch (Exception e)
{
    stackTrace = new StackTrace(e, false);
}
```

The StackTrace only contains one frame, is there a way to get the complete stack trace?

**Comment by adityamandaleeka** [comment]
I believe this is the expected behavior. The StackTrace you create in the catch block will only include the frames between the point where the exception is thrown and where you catch it. It's built up frame-by-frame as exception dispatch occurs.

**Comment by adityamandaleeka** [comment]
@noahfalk

**Comment by noahfalk** [comment]
Environment.StackTrace will give you a full stack trace to the root, albeit as a string, not as an object model.

https://github.com/dotnet/corefx/issues/1797 has some discussion about implementing other stacktrace functionality that might be of interest to you.

**Comment by JakeGinnivan** [comment]
Is there any way to turn that string into a proper stack trace?

Would be good to have proper stack trace functionality as it is one of the main things holding back porting features to dotnet core.

**Comment by noahfalk** [comment]
> Is there any way to turn that string into a proper stack trace?

If you mean is there an API where the string goes in and System.Diagnostics.StackTrace comes out, no afraid not. If you want a System.Diagnostics.StackTrace instance then dotnet/corefx#1797 is probably the one to watch (or contribute to : )

There is a general effort underway to add more of the API surface that is in .Net 4.6 but not in .Net Core (https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/). It seems reasonable that 1797 will fall into that scope, but I don't think anyone has done that detailed of an analysis yet.

HTH,
 -Noah
