### ISSUE TITLE
Configure the number of threads used by ServerGC

### ISSUE THREAD

**Issue by MendelMonteiro** [dotnet/coreclr#6052]
It would be great to be able to limit the number of foreground/background GC threads that are used for ServerGC.

By using one thread per core the whole machine is dedicated to performing the GC which can negatively impact other processes that run on the machine at the same time.  This is exacerbated by the fact that the GC threads run at High Priority.

With modern server machines that have 20+ cores there is already a huge degree of parallelism that can be achieved without using all of the cores available.

**Comment by swgillespie** [comment]
cc @Maoni0 @sergiy-k

**Comment by Maoni0** [comment]
Yes, allowing to specify the # of heaps was something I was already considering. BTW, background GC threads do not run at high priority, only Server GC threads. 

You could limit this yourself today by affinitizing your process with fewer processors (eg, you have 20+ core but you affinitize your process to only half of those cores). Of course that also means other threads in the process are also limited to only those processors so this may not be desired. And the config would only limit the GC threads, not user threads.

**Comment by MendelMonteiro** [comment]
For the affinity workaround the affinity would have to be set when launching the process, I'm assuming the runtime doesn't detect changes to the affinity mask?

**Comment by Maoni0** [comment]
You need to affinitize before CLR is loaded (ie, before GC's initialization is called), for most people this means setting the affinity mask when launching, like you said. GC does not detect affinity mask changes.

**Comment by Maoni0** [comment]
#6104

**Comment by Maoni0** [comment]
closing the issue as this was checked in. Please reactivate if you are not satisfied.

**Comment by MendelMonteiro** [comment]
Awesome, I'm assuming this has made it into .net 4.7? If so I can try this out asap on our test environments.

**Comment by Maoni0** [comment]
yes, this was checked into 4.7.

**Comment by GSPP** [comment]
Doesn't the fact that the GC uses all cores at high priority imply that even a background G2 collection would effectively block the application workload almost entirely for its duration? One could argue that the background GC feature is ineffective for that reason. @Maoni0

**Comment by Maoni0** [comment]
@GSPP  background GC threads run at normal priority.
