### ISSUE TITLE
Enable Arm64 build in build pipeline

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#6056]
With https://github.com/dotnet/coreclr/issues/6000, we now generate Arm64 nuget packages for Windows. We should, now, build it in the pipeline.

@wtgodbe Can you PTAL? This should be similar to the x64 build definitions you have. For now please *do not* enable signing and publishing of the artifacts - just build.

**Comment by gkhanna79** [comment]
CC @weshaggard

**Comment by wtgodbe** [comment]
Do you expect us to ever want to sign binaries for an Arm64 build? If not, I can add logic to sign.builds to only sign binaries if the architecture is not Arm64, and we can reuse the same build definition that we use for x64. If not, I'll probably have to create another build definition (like the one we have for x86).

**Comment by weshaggard** [comment]
We will likely want to sign them at some point but I think it is better to disable them in the sign.builds file for now as opposed to creating new build definitions.

**Comment by wtgodbe** [comment]
@jhendrixMSFT what's the best way to apply this condition to sign.builds (only sign non-arm64 binaries)?

**Comment by jhendrixMSFT** [comment]
You should condition the FilesToSign item groups and targets GetFilesToSignItems and CleanUpMarkerFiles to be executed when BuildArch != arm64.

**Comment by wtgodbe** [comment]
I just queued an orchestrated build that should build arm64 Windows alongside x64. I'll update once the build completes.

**Comment by wtgodbe** [comment]
@gkhanna79 @weshaggard @jhendrixMSFT it looks like arm64 Windows builds require a toolset_dir to be passed in via the command line - do any of you guys have an example of what this looks like? Without it, the arm64 build fails.

**Comment by wtgodbe** [comment]
I see in netci.groovy we do "build.cmd /toolset_dir C:\\ats2' - can we assume the same thing will work on our build machines?

**Comment by jhendrixMSFT** [comment]
@wtgodbe Seems unlikely as this directory doesn't exist on the build machines.  What is it supposed to contain?

**Comment by wtgodbe** [comment]
I don't actually know, the documentation in build.cmd is very vague for it.

"arm64 builds currently use private toolset which has not been released yet"

"A toolset directory is required for the Arm64 Windows build. Use the toolset_dir argument."

@rahku do you know more about this?

**Comment by wtgodbe** [comment]
@jashook do you know anything about the 'toolset_dir' arg for arm64 windows builds? What is the directory supposed to contain? Where does it come from?

**Comment by rahku** [comment]
I have sent you link on how to do arm64 builds. build.cmd takes an extra param(toolset_dir) to set the environment for arm64 builds as neither VS nor cmake currently support arm64

**Comment by jashook** [comment]
Correct, at the moment a subset of the CI machines have this toolset directory installed and is referenced in our ci script accordingly.

**Comment by wtgodbe** [comment]
@jashook how can we go about getting this directory installed on our VSO build machines?

**Comment by wtgodbe** [comment]
Scratch that, the instructions Rahul sent me have instructions. I'll go test them out.

**Comment by wtgodbe** [comment]
I've emailed the DDIT guys about getting the Arm64 toolset dir put into the base image for our Windows build machines. Once it's there, we should be able to build Arm64 as part of the pipeline.

**Comment by wtgodbe** [comment]
This is now complete - check out the package feed/azure portal to see arm64 packages being published, and look at the latest coreclr master orchestrated build (which succeeded) - Build 20160707-04.

**Comment by gkhanna79** [comment]
@wtgodbe To confirm, we are not signing and only publishing to Azure blob and not any public feed, right? And this is only enabled for master branch, correct?

**Comment by wtgodbe** [comment]
We are not signing, and the Master branch is the only one currently enabled - however, if a Release branch build were kicked off, it would also build arm64. I think if we wanted not to build arm64 for Release, we'd need a separate pipelines.json file for the Release definition. As for the feed, the publish step is still set up to publish packages to https://dotnet.myget.org/F/dotnet-core/api/v2/package - would you expect this to have changed (I didn't make any changes to publishing as part of this change)?
