### ISSUE TITLE
ARM64 GCStress: Assert failure: !IsNull()

### ISSUE THREAD

**Issue by kyulee1** [dotnet/coreclr#6062]
```
CORECLR! coreclr_shutdown + 0x10424 (0x00007ffa`6515f3c4)
CORECLR! coreclr_shutdown + 0x7D584 (0x00007ffa`651cc524)
CORECLR! GetCLRRuntimeHost + 0x3655D8 (0x00007ffa`655385c8)
CORECLR! GetCLRRuntimeHost + 0x3653C4 (0x00007ffa`655383b4)
CORECLR! GetCLRRuntimeHost + 0x650818 (0x00007ffa`65823808)
CORECLR! GetCLRRuntimeHost + 0xC6D18 (0x00007ffa`65299d08)
CORECLR! GetCLRRuntimeHost + 0xC82E4 (0x00007ffa`6529b2d4)
CORECLR! GetCLRRuntimeHost + 0xC8154 (0x00007ffa`6529b144)
CORECLR! GetCLRRuntimeHost + 0x650F9C (0x00007ffa`65823f8c)
CORECLR! GetCLRRuntimeHost + 0x650354 (0x00007ffa`65823344)
    File: e:\github\coreclr\src\inc\fixuppointer.h Line: 259
    Image: c:\Users\ddjoin\core_root\CoreRun.exe
```
This happens under COMPlus_GcStress=0x3 or 0xC
Interop\SimpleStruct\SimpleStruct\SimpleStruct.cmd 
Interop\RefCharArray\RefCharArrayTest\RefCharArrayTest.cmd

This happens under COMPlus_GcStress=0xC
JIT\jit64\opt\cse\VolatileTest_op_xor\VolatileTest_op_xor.cmd

**Comment by rahku** [comment]
This is GCInfo bug in method System.Diagnostics.StackTrace.ToString(int)

register x0 is marked to be live from 0x3cc to 0x3e0
 Below is the codegen for those offsets from 0x3c8 to 0x3e0

00007ffb`c99e0058 aa1303e0 mov         x0,x19

00007ffb`c99e005c f9400269 ldr         x9,[x19]

00007ffb`c99e0060 f9402d29 ldr         x9,[x9,#0x58]

00007ffb`c99e0064 f9400529 ldr         x9,[x9,#8]

00007ffb`c99e0068 d63f0120 blr         x9

00007ffb`c99e006c f90013a0 str         x0,[fp,#0x20]

00007ffb`c99e0070 f94013a0 ldr         x0,[fp,#0x20] (gcstress)

Even at offset 0x3dc register x0 is marked as live which I believe is incorrect. Volatile regs as well as return register isn't marked as live after call instruction.

**Comment by rahku** [comment]
System.Diagnostics.StackTrace.ToString(int) is present in System.Private.CoreLib.ni.dll

**Comment by rahku** [comment]
test JIT\jit64\opt\cse\VolatileTest_op_xor\VolatileTest_op_xor.cmd appears to be hanging for me under gcstress

**Comment by rahku** [comment]
Interop\SimpleStruct\SimpleStruct\SimpleStruct.cmd 
Interop\RefCharArray\RefCharArrayTest\RefCharArrayTest.cmd

both fail due to same issue above

**Comment by kyulee1** [comment]
I think `blr x9` is a virtual call to `System.Reflection.MethodBase.GetParameters` which returns an object. So we have gc reg birth from the return value after the call. So `x0` is just alive continuously across the call site. I think the issue is something else.

**Comment by rahku** [comment]
I don't think currently jit reports return register to be live just after call instruction. If that were the case then it should be doing this for all call which return an object. I don't find jit doing that. For example System.Diagnostics.StackTrace.ToString(int) returns an object but the caller does not report x0 to be live just call instruction.
