### ISSUE TITLE
ARM64 GCStress: Timeout

### ISSUE THREAD

**Issue by kyulee1** [dotnet/coreclr#6065]
These should be disabled for automation. But keep this list for tracking purpose.
This is under `COMPlus_GcStress=0x3` which took longer than 1 hour.
JIT\Performance\CodeQuality\V8\DeltaBlue\DeltaBlue\DeltaBlue
baseservices\threading\regressions\269336\objmonhelper\objmonhelper
JIT\Methodical\Arrays\lcs_dbglcsvalbox_dbglcsvalbox
JIT\Methodical\Arrays\lcs_rellcsvalbox_rellcsvalbox
JIT\Methodical\Arrays\lcs_speed_dbglcsvalbox_speed_dbglcsvalbox
JIT\Methodical\Arrays\lcs_speed_rellcsvalbox_speed_rellcsvalbox
JIT\Performance\CodeQuality\BenchmarksGame\binarytrees\binarytrees\binarytrees

This is under `COMPlus_GcStress=0xc`
JIT\jit64\opt\cse\HugeArray1\HugeArray1.cmd 
JIT\jit64\opt\cse\HugeField1\HugeField1.cmd
JIT\jit64\opt\cse\HugeField2\HugeField2.cmd 
JIT\jit64\opt\cse\VolatileTest_op_div\VolatileTest_op_div.cmd 
JIT\jit64\opt\cse\VolatileTest_op_mod\VolatileTest_op_mod.cmd 
JIT\jit64\opt\cse\VolatileTest_op_mul\VolatileTest_op_mul.cmd
JIT\jit64\opt\cse\VolatileTest_op_or\VolatileTest_op_or.cmd
JIT\jit64\rtchecks\overflow\overflow01_add\overflow01_add.cmd 
JIT\jit64\valuetypes\nullable\box-unbox\box-unbox\box-unbox007\box-unbox007.cmd
JIT\jit64\opt\cse\VolatileTest_op_sub\VolatileTest_op_sub.cmd
JIT\Methodical\VT\port_dbglcs_gcref_dbglcs_gcref.cmd 
JIT\Methodical\VT\port_rellcs_gcref_rellcs_gcref.cmd
JIT\Methodical\VT\port_speed_dbglcs_gcref_speed_dbglcs_gcref.cmd
JIT\Methodical\VT\port_speed_rellcs_gcref_speed_rellcs_gcref.cmd 
JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_d\bigvtbl_cs_d.cmd
JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_r\bigvtbl_cs_r.cmd

**Comment by BruceForstall** [comment]
Closing old arm64 GCStress bugs. We have CI automation for these, and will monitor that for failures/regressions.
