### ISSUE TITLE
ARM64 GCStress: Assert failure: m_alignpad == 0

### ISSUE THREAD

**Issue by kyulee1** [dotnet/coreclr#6066]
```
CORECLR! GetCLRRuntimeHost + 0xAA5D0 (0x00007ffa`6527d5c0)
CORECLR! GetCLRRuntimeHost + 0x78F22C (0x00007ffa`6596221c)
CORECLR! GetCLRRuntimeHost + 0x7798DC (0x00007ffa`6594c8cc)
CORECLR! GetCLRRuntimeHost + 0x7796B4 (0x00007ffa`6594c6a4)
CORECLR! GetCLRRuntimeHost + 0x74FBFC (0x00007ffa`65922bec)
CORECLR! GetCLRRuntimeHost + 0x74F588 (0x00007ffa`65922578)
CORECLR! GetCLRRuntimeHost + 0x752D20 (0x00007ffa`65925d10)
CORECLR! GetCLRRuntimeHost + 0x58103C (0x00007ffa`6575402c)
CORECLR! GetCLRRuntimeHost + 0x1727CC (0x00007ffa`653457bc)
CORECLR!  + 0x0 (0x00007ffa`65141954)
    File: e:\github\coreclr\src\vm\syncblk.cpp Line: 3659
    Image: c:\Users\ddjoin\core_root\CoreRun.exe
```

JIT\Methodical\fp\exgen\10w5d_cs_d\10w5d_cs_d.cmd
JIT\Methodical\fp\exgen\10w5d_cs_r\10w5d_cs_r.cmd

**Comment by kyulee1** [comment]
@rahku Can you take a look? This happens under complus_gcstress=0xc.

**Comment by rahku** [comment]
GCInfo for the method testout1..cctor is not correct. For below excerpt of the method it is expected that 
register X14 which become alive at 5c8 should remain alive atleast till offset 5d4 but it becomes dead prematurely at offset 5d0. This is causing managed heap to get corrupted.
10w5d_cs_d!testout1..cctor()+0x5a0 [e:\GithubRepo\coreclr\tests\src\JIT\Methodical\fp\exgen\10w5d.cs @ 9836]:
00007ff9`6eb66bc8 d286d411 mov         xip1,#0x36A0
00007ff9`6eb66bcc 8b1103a0 add         x0,fp,xip1
00007ff9`6eb66bd0 52800021 mov         w1,#1
00007ff9`6eb66bd4 97ffa579 bl          testout1+VT_0_6_6_3_4..ctor(Int32) (00007ff9`6eb501b8)
00007ff9`6eb66bd8 d286d411 mov         xip1,#0x36A0
00007ff9`6eb66bdc 8b1103ad add         x13,fp,xip1
00007ff9`6eb66be0 d28a9e0e mov         x14,#0x54F0
00007ff9`6eb66be4 f2ab194e movk        x14,#0x58CA lsl #0x10
00007ff9`6eb66be8 f2c047ee movk        x14,#0x23F lsl #0x20
00007ff9`6eb66bec f94001ce ldr         x14,[x14]
00007ff9`6eb66bf0 910021ce add         x14,x14,#8
00007ff9`6eb66bf4 97ffe76d bl          CORINFO_HELP_ASSIGN_BYREF (00007ff9`6eb609a8)
00007ff9`6eb66bf8 f84085ac ldr         x12,[x13],#8
00007ff9`6eb66bfc f80085cc str         x12,[x14],#8
00007ff9`6eb66c00 d290db80 mov         x0,#0x86DC

0:000> !gcinfo 0x7ff96eb66c00
entry point 00007ff96eb66628
000005a0 -X0(interior)
000005a8 +X0(interior)
000005b0 -X0(interior)
000005b8 +X13(interior)
000005c8 +X14
000005cc -X14 +X14(interior)
000005d0 -X14(interior) -X13(interior)

**Comment by rahku** [comment]
assigning to JIT team

**Comment by sdmaclea** [comment]
@jashook Reevaluate with #9498

**Comment by AndyAyersMS** [comment]
Would be good to know if this still repros.

**Comment by BruceForstall** [comment]
This passes now.
