### ISSUE TITLE
String IndexOf method return different results on mac an windows

### ISSUE THREAD

**Issue by fujihara** [dotnet/coreclr#6087]
IndexOf method of string class is returning different results on macOs and Windows. 

This issue started after .NET Core release update. 

```
var str = "The quick brown fox jumps over the lazy dog\r\n";
if (str.IndexOf("\n") >= 0) {
    Console.WriteLine("OK");
}
else {
    Console.WriteLine("BAD");
}
```

On Windows machine it always print:
`OK`

On Mac it prints:
`BAD`

I fixed my code passing a char to IndexOf instead string:
`if (str.IndexOf('\n') >= 0)`

But would be better if both platform to work consistently.

Thanks

PS: I had posted this issue on core repository (https://github.com/dotnet/core/issues/193)

**Comment by jasonwilliams200OK** [comment]
Related: https://github.com/dotnet/corefx/issues/9202

**Comment by stephentoub** [comment]
Looks like https://github.com/dotnet/corefx/issues/4587

**Comment by danmosemsft** [comment]
I agree it seems to be dotnet/corefx#4587. Please see explanation there
