### ISSUE TITLE
Windows: AsmConstants.tmp(118): fatal error C1012: unmatched parenthesis : missing ')'

### ISSUE THREAD

**Issue by Nassiel** [dotnet/coreclr#61]
While compiling I receive the next error:

  mscorlib -> T:\CoreCLR\binaries\intermediates\amd64\Debug\mscorlib.dll
  Try to compile package from 'Microsoft.DotNet.CoreCLR.nuspec'.
  File not found: '..\clretwrc.dll'.

T:\CoreCLR\build.proj(60,5): error MSB3073: The command "T:\CoreCLR\\binaries\to
ols\NuGet.exe pack "T:\CoreCLR\\binaries\Product\x64\debug\.nuget\Microsoft.Dot
Net.CoreCLR.nuspec" -NoPackageAnalysis -OutputDirectory "T:\CoreCLR\\binaries\P
roduct\x64\debug\.nuget"" exited with code 1.
MScorlib build failed. Refer T:\CoreCLR\\binaries\Logs\MScorlib_x64__debug.log f
or details.

I'll try to find how to solve it.

PD: The original text is in Spanish, I can't change the SO language, so I translate if by my self.

**Comment by Nassiel** [comment]
T:/CoreCLR/binaries/CMake/src/vm/wks/AsmConstants.tmp(118): fatal error C1012: unmatched parenthesis : missing ')' [T:\CoreCLR\binaries\CMake\src\vm\wks\cee_wks.vcxproj]

Here is the core problem, at line 118 this is what is always generating:
(118) #if defined(_DEBUG) && !defined(DACCESS_COMPILE) && (defined(_TARGET_X86_) || d
(119) efined(_TARGET_AMD64_))

CMake is splitting a single line in two lines. So the compilation doesn't finish and Nuget expects more dlls. Now the question is why it breaks it? I'm using CMake 3.1.1, the latest release.

**Comment by ErikEJ** [comment]
Maybe this https://github.com/dotnet/coreclr/issues/57 ?

**Comment by Nassiel** [comment]
But in theory that bug is solved, because I download it after he upload the bug, and well it could be of course but why is happening again? If it's the same (to my have all the sense)

Despite, thanks Erik :+1:

**Comment by ellismg** [comment]
I would try to delete the binaries directory (so the AsmConstants.tmp file is recreated), make sure you have the fix in your local tree and try again.  If it's still any issue let me know.

**Comment by Nassiel** [comment]
Well, I feel like a noob... but now it runs smoothly. Thanks to all!

**Comment by jkotas** [comment]
Very likely dup of #57
