### ISSUE TITLE
Error running build.cmd due to missing Visual Studio (Update 3)

### ISSUE THREAD

**Issue by hughbe** [dotnet/coreclr#6107]
I have Visual Studio Community Update 3 installed on my PC, and just tried to run build.cmd (build skiptests), and got the following error.

"Visual Studio 2015 (Community is free) is a prerequisite to build this repository"

The docs seem to suggest that Update 3 is supported, but perhaps the build script hasn't been updated yet?

**Comment by hughbe** [comment]
Removing this line in build.cmd seems to fix the error (but obviously causes errors down the line)

**Comment by mkborg** [comment]
@hughbe see https://github.com/dotnet/coreclr/issues/4301#issuecomment-210381609
