### ISSUE TITLE
Decimal does not contain a definition for 'Round'

### ISSUE THREAD

**Issue by scottdorman** [dotnet/coreclr#6111]
When trying to port an existing application that uses Decimal.Round, you get the following error (or a variation of it):

> error CS0117: 'decimal' does not contain a definition for 'Round'

The method exists in the source, https://github.com/dotnet/coreclr/blob/release/1.0.0/src/mscorlib/src/System/Decimal.cs#L764 but they aren't exposed for some reason. 

This appears to be similar to #2317 and is something that would fall under the notion of API convergence.

**Comment by jkotas** [comment]
Yes, this method should be coming back.

cc @danmosemsft

**Comment by danmosemsft** [comment]
This will be exposed in the upcoming .NET Core release, next year
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs
