### ISSUE TITLE
Incorrect FreeBSD requirements/unable to build coreclr

### ISSUE THREAD

**Issue by fzzzt** [dotnet/coreclr#6116]
Since there's no port/pkg/runtime download I could find I decided to try building it. Following along with coreclr/Documentation/building/freebsd-instructions.md, I didn't get very far:
```
# ./build.sh
Commencing CoreCLR Repo build
Unknown CPU amd64 detected, configuring as if for x64
Setting up directories for build
Checking prerequisites...
Laying out dynamically generated files consumed by the build system
Laying out dynamically generated Event Logging Test files
./build.sh: line 107: python: command not found
```
Python should be added to the list in the documentation.
```
# pkg install -y python # 2.7.11
[ ... ]
# ./build.sh
Commencing CoreCLR Repo build
Unknown CPU amd64 detected, configuring as if for x64
Setting up directories for build
Checking prerequisites...
Laying out dynamically generated files consumed by the build system
Laying out dynamically generated Event Logging Test files
Generating Event Logging Tests
Cleaning the temp folder of dynamically generated Event Logging files
Updating /root/git/coreclr/bin/obj/FreeBSD.x64.Debug/Generated/eventprovider with /root/git/coreclr/bin/obj/FreeBSD.x64.Debug/Generated/eventprovider_new
Commencing build of native components for FreeBSD.x64.Debug in /root/git/coreclr/bin/obj/FreeBSD.x64.Debug
Invoking "/root/git/coreclr/src/pal/tools/gen-buildsys-clang.sh" "/root/git/coreclr" 3 5 x64 Debug  Include_Tests
Including tests directory in build.
Unable to locate llvm-ar
Failed to generate native component build project!
# find / -name llvm-ar
/usr/local/llvm37/bin/llvm-ar
# rehash
# ./build.sh
[ same error ]
# setenv PATH /usr/local/llvm37/bin:${PATH}
# ./build.sh
[ ... ]
Scanning dependencies of target tracepointprovider
[  0%] Generating exports file /root/git/coreclr/bin/obj/FreeBSD.x64.Debug/src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest2.exports
[  1%] Generating exports file /root/git/coreclr/bin/obj/FreeBSD.x64.Debug/src/pal/tests/palsuite/exception_handling/pal_sxs/test1/dlltest1.exports
[  1%] Building CXX object src/pal/src/CMakeFiles/tracepointprovider.dir/misc/tracepointprovider.cpp.o
[  1%] Built target dlltest2_exports
clang++: error: unknown argument: '-fstack-protector-strong'
--- src/pal/src/CMakeFiles/tracepointprovider.dir/misc/tracepointprovider.cpp.o ---
*** [src/pal/src/CMakeFiles/tracepointprovider.dir/misc/tracepointprovider.cpp.o] Error code 1
```
I really hope the runtime doesn't require Python. That would be unfortunate (and weird, or at least unexpected). Google seems to think that fstack-protector-strong is gcc-specific, but I haven't touched c++ in over 10 years so I won't pretend to know much about that.

This is on FreeBSD 10.3/amd64 with clang 3.4.1, running in Hyper-V on my Win8.1 PC.

**Comment by akoeplinger** [comment]
I'm pretty sure the coreclr build needs at least clang 3.5. The build docs for FreeBSD even mention to install clang-3.7 so maybe you could try with that one?

**Comment by fzzzt** [comment]
You're right, building with the correct version worked. For some reason putting llvm37 in the path first didn't make my shell use the new one, even after a rehash. build.sh worked after a reboot, but didn't create libcoreclrpal.so. Both corerun and libcoreclr.so were created. Building corefx didn't work:

# ./build.sh native
[ ... ]
[  6%] Linking CXX shared library System.IO.Compression.Native.so
/root/corefx/src/Native/System.Native/pal_errno.cpp:173:14: error: use of undeclared identifier 'ENODATA'
        case ENODATA:
             ^
/root/corefx/src/Native/System.Native/pal_errno.cpp:352:20: error: use of undeclared identifier 'ENODATA'
            return ENODATA;
                   ^
2 errors generated.

git should also be listed as a dependency, now that I think about it.

I'm giving up at this point, it's requiring more time than I have to spare. I thought I would be coding by now. I hope the effort progresses on FreeBSD, though.
