### ISSUE TITLE
Question: .NET memory model and lightweight barrier for writes

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#6121]
@stephentoub @jkotas 

.NET `.volatile` writes don't  prevent any writes from floating above them - that's the semantics of store-release. So in the following scenario..
```C#
Voltile.Write(ref locationA, 1);
locationB = 2; // normal write
```
those 2 writes can be reordered.

@JPWatson suggested putting a dummy volatile read from the just written location to form a single barrier that doesn't pass reads/writes below itself nor allows writes to float above it.
```C#
Voltile.Write(ref locationA, 1);
_dummy = Voltile.Read(ref locationA);
locationB = 2; // normal write
```
The reasoning is this: 
1. volatile reads can't be reordered with the writes to the same memory location
2. volatile operations can't be eliminated
3. no memory operations can be reordered with a previous volatile read
4. no memory operations can be reordered with a following volatile write

It looks legitimate according to ECMA CLI
>A volatile read has “acquire semantics” meaning that the read is guaranteed to occur prior to any
references to memory that occur after the read instruction in the CIL instruction sequence. A
volatile write has “release semantics” meaning that the write is guaranteed to happen after any
memory references prior to the write instruction in the CIL instruction sequence.
...
An optimizing compiler that converts CIL to native code shall not remove any volatile operation,
nor shall it coalesce multiple volatile operations into a single operation.

For reads this trick won't work because in such scenario, thanks to store buffer forwarding, reads **can** be reordered with the dummy read.  @joeduffy explained it [here ](http://joeduffyblog.com/2008/07/16/loads-cannot-pass-other-loads-is-a-myth/)and [here](http://joeduffyblog.com/2009/05/16/loads-cannot-pass-other-loads-revisited/).

**Is it a legitimate way to create a barrier for following writes or we have to use full memory barrier?**

**Comment by jkotas** [comment]
Related https://github.com/dotnet/coreclr/issues/2555

**Comment by omariom** [comment]
It all started [here](https://github.com/AdaptiveConsulting/Aeron.NET/pull/43)
```C#
Volatile.Write(ref length, 1);
// bunch of normal writes to other memory locations
Volatile.Write(ref length, 2);
```
The idea is to try to not use heavyweight MemoryBarrier between first write to `length` and normal writes of data, relying only on ECMA CLI.

**Comment by omariom** [comment]
I can't check what the code is generated for ARM.
This is how it looks on .NET CLR 4.6.1 x64.
```C#
static volatile int a;
static int b, dummy;

[MethodImpl(MethodImplOptions.NoInlining)]
static void LightweightStoreFence()
{
    a = 1;
    dummy = a;
    b = 2;
}

```
```ASM
mov         dword ptr [7FE988F47A0h],1  
mov         eax,dword ptr [000007FE988F47A0h]  
mov         dword ptr [000007FE988F47A8h],eax  
mov         dword ptr [7FE988F47A4h],2  
ret
```
Everything seems ok. `b = 2;` after `a = 1;` and x86 doesn't reorder writes.

But will it be the same on other CPUs? For example, if we read to a local var 
```C#
a = 1;
var dummy = a;
b = 2;
```
JIT removes the volatile read completely.
```ASM
mov         dword ptr [7FE989047A0h],1
mov         dword ptr [7FE989047A4h],2
ret  
```
 And it is not clear if JIT did it because it realized it can remove the dummy read preserving the  order  dictated by CLI rules or the order just happened to be preserved.

**Comment by jkotas** [comment]
The JIT does not do any reordering over volatile ops today - https://github.com/dotnet/coreclr/blob/master/src/jit/importer.cpp#L11296

**Comment by mikedn** [comment]
> The JIT does not do any reordering over volatile ops today

Unless it happens to be [buggy](https://github.com/dotnet/coreclr/issues/2286) :)

**Comment by omariom** [comment]
@mikedn That's not counted :)

@jkotas 
>The JIT does not do any reordering over volatile ops today

So we can rely on that dummy volatile read to a local var to be a barrier for following writes? In the future and across different CPUs because this is how ECMA CLI rules must be understood?

**Comment by jkotas** [comment]
I think so.

**Comment by omariom** [comment]
@jkotas 
Would be nice to have simple tests that validate JIT against the model described in ECMA spec.
How similar conditions are usually tested by the team?

**Comment by jkotas** [comment]
cc @dotnet/jit-contrib 

There are number of tests that are validating this in the repo (look for `volatile` under tests\src\JIT). If you believe that there is anything particular missing, we would be happy to take PR with improvements.

Fully validating it is hard problem. It would need to prove that no combination of different optimizations violates the invariants ... https://en.wikipedia.org/wiki/Formal_methods or https://en.wikipedia.org/wiki/Model_checking are there to help.

**Comment by pgavlin** [comment]
(@ericeil can point out any flaws in my understanding and/or logic :smile:)

**Comment by CarolEidt** [comment]
@pgavlin - I don't believe that you need condition 3 to ensure that the volatile read is not moved above the volatile write. The first paragraph of I.12.6.4 in the spec ensures that:

> Conforming implementations of the CLI are free to execute programs using any technology that guarantees, within a single thread of execution, that side-effects and exceptions generated by a thread are visible in the order specified by the CIL. For this purpose only volatile operations (including volatile reads) constitute visible side-effects.

**Comment by pgavlin** [comment]
Ah, perfect! I couldn't find that language under I.12.6.7, which covers volatile read and write semantics specifically. Thanks!

**Comment by pgavlin** [comment]
@omariom: @RussKeldorph pointed out that I managed to skim over the assembly dump you posted. That assembly (which I've reproduced locally) indicates that there is a bug in the JIT that is causing us to drop the volatile read, as ECMA specifically disallows removing or coalescing volatile operations. I've opened #6172 to track.

**Comment by omariom** [comment]
@CarolEidt 
> side-effects and exceptions generated by a thread are visible in the order specified by the CIL. For this purpose only volatile operations (including volatile reads) constitute visible side-effects.

 Does it mean a volatile write can't be reordered with a following volatile read **from a different location**?

**Comment by omariom** [comment]
@pgavlin wow! I thought that was legal.

**Comment by CarolEidt** [comment]
@omariom - yes, the way I would read that section is that it would be illegal to reorder _any_ volatile operations relative to one another, even if they involve different locations. Though, to be fair, it is often been observed that the section in question is not as rigorous as it could be.

**Comment by mikedn** [comment]
> yes, the way I would read that section is that it would be illegal to reorder any volatile operations relative to one another, even if they involve different locations.

This is not what happens currently. The JIT doesn't use any fences for volatile load/stores and x86 allows some load/store reordering. That said, on x86 stores aren't reordered so in this particular case the load isn't actually needed.
