### ISSUE TITLE
ARM64 GCStress:Assert failure: ExceptionTracker::HasFrameBeenUnwoundByAnyActiveException(&m_crawl)

### ISSUE THREAD

**Issue by kyulee1** [dotnet/coreclr#6122]
```
CORECLR! GetCLRRuntimeHost + 0xC4BBC (0x00007ffe`467f7bac)
CORECLR! GetCLRRuntimeHost + 0xC6DF0 (0x00007ffe`467f9de0)
CORECLR! GetCLRRuntimeHost + 0xC82F8 (0x00007ffe`467fb2e8)
CORECLR! GetCLRRuntimeHost + 0xC8154 (0x00007ffe`467fb144)
CORECLR! GetCLRRuntimeHost + 0x650CF4 (0x00007ffe`46d83ce4)
CORECLR! GetCLRRuntimeHost + 0x6500AC (0x00007ffe`46d8309c)
CORECLR! GetCLRRuntimeHost + 0x78756C (0x00007ffe`46eba55c)
CORECLR! GetCLRRuntimeHost + 0x779624 (0x00007ffe`46eac614)
CORECLR! GetCLRRuntimeHost + 0x77940C (0x00007ffe`46eac3fc)
CORECLR! GetCLRRuntimeHost + 0x74F954 (0x00007ffe`46e82944)
    File: d:\j\workspace\arm64_cross_c---0e6c28c6\src\vm\stackwalk.cpp Line: 1866
    Image: C:\Users\ddjoin\scratch\CoreRun.exe
```

This happens under `COMPlus_GcStress=0x3`
JIT\jit64\opt\cse\HugeField2.HugeField2

**Comment by rahku** [comment]
We this assert when stackwalking for a very large jitted method. Jit emits code fragments instead of a large method each of which has its own runtime_function_entry and unwind data. As per arm64 spec it is expected that the unwind data for the fragments should specify phantom prolog. VM uses this phantom prolog to detect if this is a fragment. It fails to do so for this method and so stackwalker code incorrectly assumes it to be a funclet and hits this assert. 
I have discussed this with @BruceForstall and he found that jit is not generating phantom prologs for arm64 yet. So assigning this to jit team.

**Comment by kyulee1** [comment]
This seems related to https://github.com/dotnet/coreclr/issues/6064.
I'm also trying to fix via https://github.com/dotnet/coreclr/pull/6277 (in testing)
Basically I don't create a copied prolog but leave an empty prolog as phantom prolog and added detection logic in vm. I'm not sure if this is a right approach though. @BruceForstall Any though?

**Comment by briansull** [comment]
Bruce knows what needs to happen here.  Also Arm32 already has most of this stuff implemented.

**Comment by BruceForstall** [comment]
By the spec, we need to add an end_c code first to indicate a phantom prolog. On ARM32 it was a "F" bit in the header, which doesn't exist in ARM64. We create fragments in unwindarm.cpp, UnwindInfo::AddFragment() as well as HotColdSplitCodes(). (btw, it looks like there's an existing bug here where AddFragment should be setting ufiHasPhantomProlog = true but isn't. That probably affects large arm32 functions).

I think these places need to not just call CopyPrologCodes, but first add the end_c. Unfortunately, UnwindPrologCodes::CopyFrom is very particular about there not being anything currently there, which would need to be relaxed.

**Comment by BruceForstall** [comment]
There's a stress mode that should be used to test this: COMPlus_JitSplitFunctionSize. Set it to something small (e.g., 32, as in 32 bytes) and it will break up the code into lots of fragments.

**Comment by kyulee1** [comment]
AddFragment for arm32 is okay since the constructor UnwindFragmentInfo() already sets `ufiHasPhantomProlog  = true`

My understanding is UnwindPrologCodes constructor initializes the 4 byte of `UWC_END`
Are you saying we should call CopyPrologCodes somehow which copies prolog code after one `UWC_END`?
As in #6277, instead I leave the code as with `UWC_END` only.  It appears we always find the host frame (the first fragment) by traversing back-backward and get the real prolog. I don't see why we need to copy the same prologs for all subsequent fragment unwind blob (even for arm32).

**Comment by BruceForstall** [comment]
We never set the end_c code (0xE5), as per the spec, so IsFunctionFragment() will always return FALSE. I think after CopyPrologCodes is called (which copies all the UnwindPrologCodes memory / state), we should call AddCode(0xE5).

**Comment by BruceForstall** [comment]
Oh, I see, in #6277 you're just changing the definition of what is required for fragments. I don't think that's wise, because it means we're not implementing the precise spec. That can be confusing, and won't work well if/when we generate true native images (e.g., CoreRT).
