### ISSUE TITLE
AssemblyName.CultureName not settable

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/coreclr#6123]
AssemblyName.CultureName is currently not set-able although the setter appears to exist in [the code](https://github.com/dotnet/coreclr/blob/release/1.0.0/src/mscorlib/src/System/Reflection/AssemblyName.cs#L96) and other similar properties appear to be set-able. Because of this anyone who wants to use the AssemblyName to look for a culture-specific assembly (as we do in aspnet/Localization#257 to work around dotnet/corefx#9766) must instead do so with manual string manipulation.

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/issues/9643#issuecomment-230459531

**Comment by danmosemsft** [comment]
This is in Corefx now and going to be in the next version of .NET Core
