### ISSUE TITLE
csc hung when compiling a project on macOS

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/coreclr#6128]
https://gist.github.com/BrennanConroy/33b3462798c3eca3b9915290e565a772

I have the process running currently if anyone has suggestions for things to look at.

**Comment by jkotas** [comment]
The first step to analyze crashes like this one is to get symbols - to make stacktraces to contain meaningful method names.

@mikem8361 Do we have instructions somewhere how to download coreclr symbol files on macOS?

**Comment by mikem8361** [comment]
The 1.0.0 RTM coreclr symbols are located here (see "Download symbols" on the right):

https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.2

**Comment by danmosemsft** [comment]
@BrennanConroy I'm going to close this as we can't make progress without that info. Please reactivate if you have it!
