### ISSUE TITLE
[LSRA stress] Add JitCI stress leg for new LSRA stress mode 0x1000

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#6129]
This new stress mode doesn't even attempt to allocate a reg to reg-optional ref positions and meant to exercise and verify that lsra/codegen code paths correctly handle contained Lcl Var nodes.

COMPlus_JitStressRegs=0x1000

LSRA_REG_OPTIONAL_NO_ALLOC = 0x1000

**Comment by RussKeldorph** [comment]
Do while you're in there for TailcallStress

**Comment by BruceForstall** [comment]
Fixed with #10013
