### ISSUE TITLE
Consider using stackalloc for string.Split

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#6136]
Right now, `string.Split` allocates a new int array for both the [`char`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L1060) and [`string`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L1116-L1117) versions. We might want to consider using `stackalloc` here instead for strings of lengths under a certain threshold.

Alternatively, we could introduce some type of `ArrayPool`-like API to mscorlib and use that, or just forego allocating anything altogether and simply count the length needed for the resulting array on our first pass.

**Comment by gkhanna79** [comment]
CC @danmosemsft @AlexGhiondea

**Comment by AlexGhiondea** [comment]
Sounds like a great idea for an enhancement. Anyone interested in picking this up?

**Comment by 4real** [comment]
I'm looking into it, seems like a nice introduction to coreclr.

**Comment by danmosemsft** [comment]
@karelz can you please give @4real  this issue

@4real whatever you do will need a fair bit of performance measurement to find and prove the best approach on various inputs. We usually use Benchmark.NET.

**Comment by karelz** [comment]
@4real, invite sent to, please ping us when you accept.

@danmosemsft I thought you have same admin permissions as I do ... we should fix that ;-)

**Comment by 4real** [comment]
@karelz Accepted invite!

@danmosemsft Thanks, I'll have a look at Benchmark.NET. I take it that sufficient proof is empirical evidence a new solution is significantly faster and there being a line of reasoning as to why that is? Should I wrote a performance test for this issue specifically? (Apologies if this is covered by the documentation, I haven't processed it all yet.)

**Comment by danmosemsft** [comment]
@4real there aren't really hard rules but generally we're looking for 
(1) parity or faster across all interesting ranges of inputs 
(2) improvement is worth any increase in code complexity and maintenance cost. This depends on how heavily used/critical the API is. We have taken and will continue to take quite hairy changes eg in Encoding or StringBuilder because those show up in key performance scenarios. In something that's less performance critical we are more wary of accepting code complexity. Of course lower in the stack, the worse it is if we have a bad impact on some scenario. Sometimes changes take a long time to get right and often they don't work out and have to be aborted.
(3) no affect on functional behavior

Of course there are plenty of perf changes where it's a no brainer and sometimes we don't even bother measuring (eg just removing redundant code).

**Comment by danmosemsft** [comment]
Incidentally for profiling you can use the Visual Studio 2017 profiler but many of us use [PerfView](https://www.microsoft.com/en-us/download/details.aspx?id=28567) as it's owned by our team. It's very powerful and has good tutorials.

**Comment by 4real** [comment]
Thanks, I'll have a look at PerfView too.

From what I can tell, there are XUnit.Performance tests in the codebase for the GC and JIT, but not mscorlib. So instead, I will create a Benchmark.NET performance test for string.Split which will not be included in the commit, but for which I will post the results of here - does this seem like the correct approach? I will however create a functional test to show correctness of changes to string.Split if deemed not covered by existing tests.

**Comment by danmosemsft** [comment]
@4real correct, that's what we normally do -- have a throwaway perf test -- of course you could archive it in a gist with a link in the PR in case we want it again.

There are lots of XUnit.Performance tests in the repo and they are run regularly but those are to catch regressions and there is a certain cost to maintaining them (watching results). So we could consider adding one if it was an important scenario that might regress. Normally we don't. In fact we may delete some of those tests -- they need an audit.

**Comment by danmosemsft** [comment]
@4real still planning to take a look? just realized I never checked back. it would be nice to optmize this.

**Comment by cod7alex** [comment]
I would like to give it a try if nobody is looking

**Comment by 4real** [comment]
Hello, feel free to take it over, I've just realized how much time this has been resting. My attention has been shifted elsewhere unfortunately and I wouldn't start working on this within reasonable time.

**Comment by karelz** [comment]
@cod7alex I sent you Collaborator invite - that will allow to assign the issue to you (GH limitation). Ping me when you accept.
ProTip: Accepting will automatically subscribe you to all notifications. There's plenty (500+ per day). We recommend to disable them and use just notifications for your mentions and explicit subscriptions to issues.

**Comment by danmosemsft** [comment]
@cod7alex to restate the above, we typically use [PerfView](https://www.microsoft.com/en-us/download/details.aspx?id=28567) to profile, Benchmark.NET to prove the win (post results here).

To run corefx tests (where most tests are) against changes made in coreclr (where string is) look at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits to see the flag to force this to happen.

If the benchmark results and change is satisfactory we will want to check in benchmark tests.Currently we still use xunit.perf for checked-in tests (that may change) - see existing tests in corefx\src\System.Runtime\tests\Performance\Perf.String.cs. This may be helpful
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/performance-tests.md

I think we need better docs on using Benchmark.NET against private coreclr changes, based on https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md. Hopefully @ViktorHofer can throw up some notes he has. We can also help answer questions.

**Comment by cod7alex** [comment]
thank you @danmosemsft

**Comment by ViktorHofer** [comment]
BenchmarkDotNet instructions not yet reviewed available here: https://github.com/dotnet/corefx/pull/25612

**Comment by cod7alex** [comment]
@ViktorHofer this guide is very helpful, i was able to run benchmark.
First thing i have done was to use stackalloc for int array when string length is less than 512.
Results for benchmark that does 10000 string splits are the following:

Nightly corefx:
``` ini

BenchmarkDotNet=v0.10.11, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.64)
Processor=Intel Core i5-7500 CPU 3.40GHz (Kaby Lake), ProcessorCount=4
Frequency=3328125 Hz, Resolution=300.4695 ns, Timer=TSC
.NET Core SDK=2.2.0-preview1-007622
  [Host]     : .NET Core ? (Framework 4.6.25929.01), 64bit RyuJIT
  Job-MYMOYO : .NET Core 2.1.0-preview1-25929-02 (Framework 4.6.25929.01), 64bit RyuJIT

Runtime=Core  InvocationCount=1  LaunchCount=1  
TargetCount=3  UnrollFactor=1  WarmupCount=1  

```
|           Method |      Mean |     Error |    StdDev |      Gen 0 | Allocated |
|----------------- |----------:|----------:|----------:|-----------:|----------:|
|  StringLength100 |  7.992 ms |  3.892 ms | 0.2199 ms |  4000.0000 |  12.44 MB |
|  StringLength500 | 33.999 ms |  4.375 ms | 0.2472 ms | 19000.0000 |  59.13 MB |
| StringLength1000 | 67.912 ms | 14.136 ms | 0.7987 ms | 39000.0000 | 117.49 MB |

With stackalloc:
``` ini

BenchmarkDotNet=v0.10.11, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.64)
Processor=Intel Core i5-7500 CPU 3.40GHz (Kaby Lake), ProcessorCount=4
Frequency=3328125 Hz, Resolution=300.4695 ns, Timer=TSC
.NET Core SDK=2.2.0-preview1-007622
  [Host] : .NET Core ? (Framework 4.6.26029.0), 64bit RyuJIT

Toolchain=InProcessToolchain  InvocationCount=1  LaunchCount=1  
TargetCount=3  UnrollFactor=1  WarmupCount=1  

```
|           Method |      Mean |    Error |    StdDev |      Gen 0 | Allocated |
|----------------- |----------:|---------:|----------:|-----------:|----------:|
|  StringLength100 |  8.601 ms | 11.36 ms | 0.6418 ms |  2000.0000 |   8.77 MB |
|  StringLength500 | 35.117 ms | 11.94 ms | 0.6747 ms | 13000.0000 |  41.73 MB |
| StringLength1000 | 70.412 ms | 42.57 ms | 2.4052 ms | 39000.0000 | 117.49 MB |

There are of course reduced allocations, but it takes slightly more time (i guess for this string length checking). Going to try something else.

**Comment by cod7alex** [comment]
Can someone help me with Spans? If i have the code like the following, can i pass Span to function and fill it? Is it even a good idea?
````     
private unsafe Span<int> CreateSeparatorList(int length)
{
    if (Length < 512)
    {
        int* stackBuffer = stackalloc int[length];
            return new Span<int>(stackBuffer, length);
    }
    return new int[length];
}
```

**Comment by Rattenkrieg** [comment]
@cod7alex this is explicitly forbidden by design of `Span`. Memory it points will be reclaimed when you leave `CreateSeparatorList`'s activation record. Spans (actually anything stacalloced) can only be passed from callers to callees.

**Comment by cod7alex** [comment]
thanks @Rattenkrieg, I am not really familiar with stackalloc. So it means I should inline this everywhere it is needed?

**Comment by Rattenkrieg** [comment]
@cod7alex if you know desired size in advance you can allocate span in top level method and pass it by ref where it will be populated.
 if you will ever hit _unexplainable_ performance degradation caused by stackalloc this may shed some light: #5719 #8534 #1279

**Comment by cod7alex** [comment]
@Rattenkrieg many thanks

**Comment by jamesqo** [comment]
@cod7alex By the way, you don't have to stackalloc a temporary ptr and then create a span from that. You can just stackalloc a Span directly. https://github.com/dotnet/corefx/pull/24212/files

**Comment by cod7alex** [comment]
@jamesqo yes, i have found that information recently. Thank you.
