### ISSUE TITLE
What is JIT_MonEnterWorker_InlineGetThread (high cpu burn)

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#6144]
Is it `lock()` or `Montior.Enter` statements?

I'm seeing a high percentage of cpu used in it, which is front-end bound and has bad speculation; when running Kestrel plaintext benchmarks

![](https://aoa.blob.core.windows.net/aspnet/kesstrel-monenter-1.png)

![](https://aoa.blob.core.windows.net/aspnet/kesstrel-monenter-2.png)

Which relate to lines https://github.com/dotnet/coreclr/blob/master/src/vm/amd64/JitHelpers_InlineGetThread.asm#L515-L518

Alas I don't have call stacks so I can't determine what initiates it.

**Comment by jkotas** [comment]
> Is it  `lock()` or `Monitor.Enter` statements?

It can be either. `lock()` is translated to `Monitor.Enter` calls.

**Comment by jkotas** [comment]
Related to https://github.com/dotnet/coreclr/issues/5927

cc @kouvel

**Comment by kouvel** [comment]
Closing in favor of https://github.com/dotnet/coreclr/issues/13949
