### ISSUE TITLE
PAL's context2.S causes build to fail on FreeBSD

### ISSUE THREAD

**Issue by josteink** [dotnet/coreclr#615]
This file did not cause issues back in February when the first attempts to port coreclr to FreeBSD was made. Since then only a few commits have been made.

These commits seems to have introduced platform-specific use of macros, which may or may not be the cause of the errors observed.

Error from the build can be seen below:
````
Commencing CoreCLR Repo build
Setting up directories for build
Checking pre-requisites...
Commencing build of native components for freebsd.x64.debug
Invoking cmake with arguments: "/home/josteink/build/coreclr" DEBUG
 -- Configuring done
 -- Generating done
 -- Build files have been written to: /home/josteink/build/coreclr/binaries/intermediates/freebsd.x64.debug
Executing make install -j 3 [ 0%]
Built target debug-pal [ 0%]
Built target gcinfo [ 0%]
Building ASM object src/pal/src/CMakeFiles/CoreClrPal.dir/arch/i386/context2.S.o [ 1%]
Building CXX object src/utilcode/staticnohost/CMakeFiles/utilcodestaticnohost.dir/__/sstring_com.cpp.o 
/home/josteink/build/coreclr/src/pal/src/arch/i386/context2.S:93:10: error: unknown token in expression
 je 0f
    ^
/home/josteink/build/coreclr/src/pal/src/arch/i386/context2.S:109:11: error: unknown token in expression
 jmp 1f
     ^
/home/josteink/build/coreclr/src/pal/src/arch/i386/context2.S:114:10: error: unknown token in expression
 je 2f
    ^
/home/josteink/build/coreclr/src/pal/src/arch/i386/context2.S:135:10: error: unknown token in expression
 je 3f
    ^ 
/home/josteink/build/coreclr/src/pal/src/arch/i386/context2.S:139:10: error: unknown token in expression
 je 4f
    ^ 
/home/josteink/build/coreclr/src/pal/src/arch/i386/context2.S:158:42: error: unexpected token in argument list
 mov DWORD PTR [rdi + 6*8], (0x100000 | (1 | 2 | 8) | 4)
                                      ^
--- src/pal/src/CMakeFiles/CoreClrPal.dir/arch/i386/context2.S.o 
--- *** [src/pal/src/CMakeFiles/CoreClrPal.dir/arch/i386/context2.S.o] 
Error code 1
make[2]: stopped in /usr/home/josteink/build/coreclr/binaries/intermediates/freebsd.x64.debug
1 error
make[2]: stopped in /usr/home/josteink/build/coreclr/binaries/intermediates/freebsd.x64.debug --- src/pal/src/CMakeFiles/CoreClrPal.dir/all
--- *** [src/pal/src/CMakeFiles/CoreClrPal.dir/all]
Error code 2
make[1]: stopped in /usr/home/josteink/build/coreclr/binaries/intermediates/freebsd.x64.debug A failure has been detected in another branch of the parallel make 
make[2]: stopped in /usr/home/josteink/build/coreclr/binaries/intermediates/freebsd.x64.debug 
--- src/vm/dac/CMakeFiles/cee_dac.dir/all 
--- *** [src/vm/dac/CMakeFiles/cee_dac.dir/all]
Error code 2
make[1]: stopped in /usr/home/josteink/build/coreclr/binaries/intermediates/freebsd.x64.debug A failure has been detected in another branch of the parallel make
make[2]: stopped in /usr/home/josteink/build/coreclr/binaries/intermediates/freebsd.x64.debug --- src/utilcode/staticnohost/CMakeFiles/utilcodestaticnohost.dir/all 
--- *** [src/utilcode/staticnohost/CMakeFiles/utilcodestaticnohost.dir/all] 
Error code 2 
make[1]: stopped in /usr/home/josteink/build/coreclr/binaries/intermediates/freebsd.x64.debug 3 errors make[1]: stopped in /usr/home/josteink/build/coreclr/binaries/intermediates/freebsd.x64.debug 
*** [all] Error code 2 make: stopped in /usr/home/josteink/build/coreclr/binaries/intermediates/freebsd.x64.debug 
make: stopped in /usr/home/josteink/build/coreclr/binaries/intermediates/freebsd.x64.debug 
Failed to build coreclr components.
````

**Comment by janvorli** [comment]
My change mostly just converted the file to the intel asm language syntax and added wrapper macros around the function name so that it generates proper name based on the target platform. 
The wrappers don't seem to be related to the issues. It seems to complain about the numeric local labels syntax and also about the DWORD PTR (but it is happy with BYTE PTR). 
I wonder if it is possible that the cmake uses some other assembler than the internal one in clang. 
Could you please try go to /home/josteink/build/coreclr/src/pal/src and run "make -n"? You should then see the command line it used to compile the context2.S.

**Comment by josteink** [comment]
The logs gots their formatting ruined when pasted to Github. It's not the DWORD it fails at, it failed ath the first pipe when trying to bitwise OR things together. You can see this if you inspect the column-number too.

You're still right about it complaining about number-formats though. I didn't think about that when submitting this!

Checking out "make -n" yielded some (to me) unsatisfactory results, so I'll get a clean environment and clean build and retry.

**Comment by josteink** [comment]
Are you sure "make -n" is the right command? After running a regular configure and build, this is the output I'm getting:
````
$ cd src/pal/src
$ make -n
make: no target to make.
 
make: stopped in /usr/home/josteink/build/cc2/src/pal/src
$ cd ..
$ make -n
make: no target to make.
 
make: stopped in /usr/home/josteink/build/cc2/src/pal
$ cd ..
$ make -n
make: no target to make.
 
make: stopped in /usr/home/josteink/build/cc2/src
$
````

**Comment by janvorli** [comment]
I've tried something more specific on my Ubuntu. In the src/pal/src folder, I've issued this:
```sh
make -n -B arch/i386/context2.o
```
And the output was:
```sh
cd /home/janvorli/git/build && make -f src/pal/src/CMakeFiles/CoreClrPal.dir/build.make src/pal/src/CMakeFiles/CoreClrPal.dir/arch/i386/context2.S.o
/usr/bin/cmake -E cmake_progress_report /home/janvorli/git/build/CMakeFiles
/usr/bin/cmake -E cmake_echo_color --switch= --green "Building ASM object src/pal/src/CMakeFiles/CoreClrPal.dir/arch/i386/context2.S.o"
cd /home/janvorli/git/build/src/pal/src && /usr/bin/clang-3.5  -DBIT64=1 -DBUILDENV_CHECKED=1 -DCORECLR=1 -DDEBUG -DFEATURE_PAL=1 -DLP64COMPATIBLE=1 -DPIC=1 -DPLATFORM_UNIX=1 -DURTBLDENV_FRIENDLY=Checked -DWRITE_BARRIER_CHECK=1 -D_DBG -D_DEBUG -D_WIN64=1 -D__LINUX__=1 -g -I/home/janvorli/git/build/src/pal/src -I/home/janvorli/git/src/src/pal/src -I/home/janvorli/git/src/src/pal/inc -I/home/janvorli/git/src/src/pal/../inc -I/home/janvorli/git/src/src/pal/src/include    -gdwarf-3 -fexceptions -fstack-protector-all -fno-builtin -fPIC -o CMakeFiles/CoreClrPal.dir/arch/i386/context2.S.o -c /home/janvorli/git/src/src/pal/src/arch/i386/context2.S
```

**Comment by jkotas** [comment]
For the last one, try whether either of these will help - both of these are changes towards the classic Intel syntax:
- change 0x100000 constant at the top of the file to 100000h
- change | (pipe) to OR

**Comment by kangaroo** [comment]
You can also use make VERBOSE=1, but it certainly does look like some other assembler is being used.

**Comment by josteink** [comment]
@janvorli It may be worth noting that I don't try to build PAL directly, but rather try to build it indirectly by building entire coreclr.

As far as I can tell src/pal/src doesn't have any makefile or CMakeFiles-folder. Thus the output from make -n -B ... doesn't seem consistent with the rest of the build as a whole:

````
$ make -n -B arch/i386/context2.o
cc -O2 -pipe    -c arch/i386/context2.S
$ cc --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.1
Thread model: posix
$ cc -O2 -pipe -c arch/i386/context2.S
arch/i386/context2.S:12:10: fatal error: 'unixasmmacros.inc' file not found
#include "unixasmmacros.inc"
         ^
1 error generated.
$
````

There's a few obvious things to notice here:

* the make command doesn't look right at all.
* clang is supposedly getting invoked, but not with any proper arguments.
* the error reported here doesn't show up in the real build.

Anyway, I would definitely agree with @kangaroo: It doesn't seem like the right tools are getting invoked, and I'd rather look into why that is happening, than you guys providing work-arounds at source-level.

If I find a way to make this build correctly, what do you want me to do with that information? Create a PR for the readme with FreeBSD build-configuration instructions? Or something else?

@janvorli : I'll do some more checking with the build commands and verify that this builds properly, given the proper input.  

@jkotas : I'll also check your suggestions, but if the wrong tools are getting invoked, I think it's better to fix the real problem instead of patching our way around it.

**Comment by josteink** [comment]
Using clang3.5 fixes this issue. The error is not detecting it on FreeBSD.

I will prepare a pull-request for this and that should be the end of this issue.

**Comment by janvorli** [comment]
LGTM, it is great to see this mystery resolved.

**Comment by kangaroo** [comment]
@janvorli I think you meant to LGTM on the PR (https://github.com/dotnet/coreclr/pull/624) not the issue?
