### ISSUE TITLE
Cancelled Task.Delay not scalable

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#6155]
I have a scenario where a lot of timeout tasks (`Task.Delay`) are started. They are almost always cancelled before completion. The workload looks like this in a hot loop:

```
        var cts = new CancellationTokenSource();
        var delayTask = Task.Delay(TimeSpan.FromDays(1), cts.Token);
        cts.Cancel();
        delayTask.ContinueWith(_ => { }, TaskContinuationOptions.ExecuteSynchronously).Wait();
```

Unfortunately, this code does not scale beyond 2 CPU cores:

```
Threads: 1, 669406/s, duration: 1,494s.
Threads: 2, 1142099/s, duration: 0,876s.
Threads: 3, 1277886/s, duration: 0,783s.
Threads: 4, 1366085/s, duration: 0,732s.
Threads: 5, 1394991/s, duration: 0,717s.
Threads: 6, 1315112/s, duration: 0,760s.
Threads: 7, 1322821/s, duration: 0,756s.
Threads: 8, 1323647/s, duration: 0,755s.
```

This is a profile of the 8 core case. I don't see anything particularly suspicious:

![image](https://cloud.githubusercontent.com/assets/12032350/16632515/ad2e6e5c-43c4-11e6-8b8d-eaa3cf42e2de.png)

Here the program. It will lock up your machine for about 10 seconds at high process priority.

```
    static void Main()
    {
        Process.GetCurrentProcess().PriorityClass = ProcessPriorityClass.High;

        var totalCount = 1000000;

        for (int i = 1; i <= Environment.ProcessorCount; i++)
            RunTest(totalCount, i);
    }

    static void RunTest(int totalCount, int threadCount)
    {
        var countPerThread = totalCount / threadCount;

        var sw = Stopwatch.StartNew();
        var tasks = Enumerable.Range(0, threadCount).Select(_ => Task.Run(() => { RunLoop(countPerThread); })).ToArray();
        Task.WaitAll(tasks);
        sw.Stop();

        Console.WriteLine($"Threads: {threadCount}, {totalCount / sw.Elapsed.TotalSeconds:F0}/s, duration: {sw.Elapsed.TotalSeconds:F3}s.");
    }

    static void RunLoop(int count)
    {
        for (int i = 0; i < count; i++)
        {
            RunIteration();
        }
    }

    static void RunIteration()
    {
        var cts = new CancellationTokenSource();
        var delayTask = Task.Delay(TimeSpan.FromDays(1), cts.Token);
        cts.Cancel();
        delayTask.ContinueWith(_ => { }, TaskContinuationOptions.ExecuteSynchronously).Wait(); //Wait without throwing.
    }
```

This is .NET 4.6 x64 Release without debugger and with scalable GC configured:

```
   <runtime>
     <gcConcurrent enabled="true" />
     <gcServer enabled="true" />
   </runtime>
```

Without those GC settings the GC shows up in the profile a lot more.

**Comment by stephentoub** [comment]
Thanks, though I'm not sure this is really about Task.Delay.  A Delay task just wraps a Timer, and your RunIteration function is essentially just creating a Timer and then immediately destroying it, e.g. as if you replaced by the body of RunIteration with:
```C#
var t = new Timer(delegate { }, null, TimeSpan.FromDays(1), Timeout.InfiniteTimeSpan);
t.Dispose();
```
While the overall throughput of that snippet will differ (since the Task-based code is doing more work), I assume this hits a similar bottleneck?  Assuming yes, that would be due to the fact that creating/destroying timers takes a process-wide lock, so for the most part the program that's just creating and destroying lots of timers is getting serialized.

**Comment by GSPP** [comment]
Yes, this hits the same bottleneck:

```
Threads: 1, 2758262/s, duration: 0,363s.
Threads: 2, 2765757/s, duration: 0,362s.
Threads: 3, 2797112/s, duration: 0,358s.
Threads: 4, 2448631/s, duration: 0,408s.
Threads: 5, 2249026/s, duration: 0,445s.
Threads: 6, 2381978/s, duration: 0,420s.
Threads: 7, 2302040/s, duration: 0,434s.
Threads: 8, 2289202/s, duration: 0,437s.
```

In the age of async IO we need to rely more on timers than before. Async IO on Windows does not support intrinsic timeouts. This means that any async socket-based API will need to resort to creating it's own timers.

Maybe this is a good time to revisit the global lock design. As a cheap band-aid lock striping comes to mind. Create N queues backed by N OS timers and enqueue timers into queue (ThreadID % N).

So I guess my request is to eliminate any bottleneck that stands in the way of the code that I posted. I think that code is quite representative for a component that's in many real world loads.

**Comment by stephentoub** [comment]
cc: @ericeil, @kouvel

**Comment by GSPP** [comment]
As a related issue there is an efficiency problem when many timers exist. The algorithm that expires due timers is linear in the number of existing timers (not expiring timers).

It takes about 1e6 timers to drive one CPU core to 100%. Not sure how important that scenario is to you. It's not important to me, I was just curious.

```
            var timers = Enumerable.Range(0, 1000000).Select(_ => new Timer(delegate { }, null, TimeSpan.FromDays(1), Timeout.InfiniteTimeSpan)).ToList();
            var t = new Timer(delegate { }, null, TimeSpan.Zero, TimeSpan.FromMilliseconds(1));

            Thread.Sleep(TimeSpan.FromSeconds(10));

            GC.KeepAlive(timers);
            GC.KeepAlive(t);
```

The potential fix would be to use a sorted data structure.

So if the algorithm to expire timers is just a linear pass... what about removing the global lock and using a `ConcurrentDictionary` for the timers? Use the dictionary as a set.

**Comment by benaadams** [comment]
Resolved by Reduce Timer lock contention #14527 ?

**Comment by stephentoub** [comment]
On my quad core, the repro in https://github.com/dotnet/coreclr/issues/6155#issue-164160917 yields:
```
Threads: 1, 1381140/s, duration: 0.724s.
Threads: 2, 1652512/s, duration: 0.605s.
Threads: 3, 1585796/s, duration: 0.631s.
Threads: 4, 1501549/s, duration: 0.666s.
Threads: 5, 1323481/s, duration: 0.756s.
Threads: 6, 1353807/s, duration: 0.739s.
Threads: 7, 1367147/s, duration: 0.731s.
Threads: 8, 1359102/s, duration: 0.736s.
```
After my change in #14527, it yields:
```
Threads: 1, 1657470/s, duration: 0.603s.
Threads: 2, 2945481/s, duration: 0.340s.
Threads: 3, 4670483/s, duration: 0.214s.
Threads: 4, 5144962/s, duration: 0.194s.
Threads: 5, 5996948/s, duration: 0.167s.
Threads: 6, 6259734/s, duration: 0.160s.
Threads: 7, 6776771/s, duration: 0.148s.
Threads: 8, 5287363/s, duration: 0.189s.
```

**Comment by kouvel** [comment]
Appears to be resolved, closing
