### ISSUE TITLE
32 bit Linux

### ISSUE THREAD

**Issue by hultqvist** [dotnet/coreclr#6162]
I can't find 32 bit Linux support mentioned in the roadmap.

Are there any plans?

**Comment by jkotas** [comment]
It is in roadmap, but it does not have date attached to it yet. From project goals at https://github.com/dotnet/core/blob/master/roadmap.md:
- There are high-quality ports for Linux, macOS and Windows
- There are high-quality ports for X64, X86, ARM32, and ARM64

In the meantime, we would be happy to take PRs towards making it work.

**Comment by jkotas** [comment]
cc @sergiy-k @adityamandaleeka

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/issues/1264 has some earlier discussion about it.

**Comment by jkotas** [comment]
Let's use https://github.com/dotnet/coreclr/issues/8188 to track the Linux x86 port.
