### ISSUE TITLE
Integrate Profiler Test run within CI and Pipeline infrastructure

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#6166]
We should look into integrating it closer to the product to identify regressions and status sooner.

CC @sergiy-k

**Comment by lt72** [comment]
We will not have the bandwidth to pull this off for v1.1. Moving to 1.2.

**Comment by gkhanna79** [comment]
@lt72 Is this happening for 2.0? If not, can you please move this to future?

**Comment by lt72** [comment]
Updated milestone according to current planning ==> 2.1

**Comment by lt72** [comment]
Completed.
