### ISSUE TITLE
[ARM/Linux] Regression in Unittest - Exception.ToString() failed

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#6179]
Running unittest using Release build CoreCLR from aab8856ce03 and Release build TC incurs many TC failures with the following message:
```
FAILED   - [ 000 :    3 sec ] baseservices/compilerservices/dynamicobjectproperties/Dev10_535767/Dev10_535767.sh
               BEGIN EXECUTION
               /opt/dotnet/Linux.tm1.Release/corerun Dev10_535767.exe
               
               Unhandled Exception: 
                  Cannot print exception string because Exception.ToString() failed.
               ./Dev10_535767.sh: line 117: 18972 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" Dev10_535767.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

I observed that 85 TC shows the similar failure (when I running 905 tests). 

Is there any change that may be related with this?

**Comment by parjong** [comment]
It seems that  aab8856  causes this issue. When I reverted aab8856, the above error does not happen. @CarolEidt could you please take a look?

\CC @jyoungyun @lemmaa @wateret @chunseoklee

**Comment by jyoungyun** [comment]
When I checked the aab8856ce0365ede77bb8ca8c208538a72185a54 patch, almost tc failed with below errors.
```
Unhandled Exception: 
   Cannot print exception string because Exception.ToString() failed.
Aborted
```
@CarolEidt Did the issue what I mentioned in #6021 pass in your side?

**Comment by wateret** [comment]
I tested it with debug-build-coreclr for both debug and release TC, and passed.

**Comment by leemgs** [comment]
>  @mkborg commented 5 days ago
>  CoreCLR Bin Dir  : /coreclr-testing/20160706/odroid-2.arm-softfp/odroid-2.coreclr_46d3809.corefx_860d28c.arm-softfp/
> CORECLR_NATIVE/coreclr/bin/Product/Linux.arm-softfp.> Debug
>   Tests Discovered : 9870
>   Passed           : 9124
>   Failed           : 394
>   Skipped          : 352
> Is it my local issue or actual regression?

@CarolEidt , 394 failures is result from the https://github.com/dotnet/coreclr/pull/6021. Please, revert the #6021 or fix the regression of #6021. 
/CC: @jkotas , @janvorli

**Comment by CarolEidt** [comment]
I have not been able to successfully run the emulator, and I am wondering if we can take a next step by having you try to get a jitdump from one of the failing tests. Is this reproducible in a Debug or Checked build? If not, you can copy a Checked version of clrjit.dll into the Release product directory. Then, if you know what the failing methods are, you can set COMPlus_JitDump=<method name>. Otherwise, perhaps you could run it with COMPlus_JitDisasm=* to get the disassembly for all the methods, to help narrow it down.

**Comment by parjong** [comment]
@CarolEidt I failed to reproduce the error in a Debug build. I currently attempt to build Checked CoreCLR, but there is some build issue.

**Comment by parjong** [comment]
I found the following error message:
```
: In function `Thread':
/home/parjong/projects/toolchains/coreclr/src/pal/tests/palsuite/threading/CriticalSectionFunctions/test8/test8.c:71: undefined reference to `InterlockedIncrement'
/home/parjong/projects/toolchains/coreclr/src/pal/tests/palsuite/threading/CriticalSectionFunctions/test8/test8.c:97: undefined reference to `InterlockedDecrement'
```

**Comment by parjong** [comment]
@CarolEidt The error happens only for Release build:
```
$ Linux.arm-softfp.Release/corerun ut/baseservices/compilerservices/dynamicobjectproperties/TestAPIs/TestAPIs.exe
Unhandled Exception:
   Cannot print exception string because Exception.ToString() failed.

$ Linux.arm-softfp.Debug/corerun ut/baseservices/compilerservices/dynamicobjectproperties/TestAPIs/TestAPIs.exe
Test Passed

```
I'll try whether it is reproducible in Checked build after fixing #6268.

**Comment by CarolEidt** [comment]
@parjong - If the Checked build at least succeeds in building the clrjit.dll, you could copy that into the directory where you are running the corerun.exe from, and you should be able to produce the jitdumps. That would be very helpful. Alternatively, if you are able to at least get any dump or disassembly from the failing method, that would also help.

**Comment by wateret** [comment]
@CarolEidt I successfully built with mode `arm-softfp checked`, and the test above passed. Instead I was able to get the same error for `JIT/Regression/CLR-x86-JIT/V1.2-M01/b07369`. 

I attached jit dump and disasm in case it might help. [dump.txt](https://github.com/dotnet/coreclr/files/368315/dump.txt)

Environment:
```
export COMPlus_JitDump="ILGEN_0x1c9344b9:*"
export COMPlus_JitDisasm="ILGEN_0x1c9344b9:*"
```

**Comment by CarolEidt** [comment]
@wateret - that doesn't appear to be the dump for the failing method. If it is also failing in Exception.ToString() with a null "this" pointer, then we need to print the method that is calling it. Do you have a dump or stack trace from when it fails?

**Comment by parjong** [comment]
@CarolEidt @wateret From bdfce9ed7fb, I found ``baseservices/exceptions/regressions/V1/SEH/VJ/NestedEx1`` failed.

For that test, I observed the followings:

 - The Debug build works well as follows:
```
$ ...
   at TestClass.TestMain()
Test Passed.
Done
```

 - The Checked build terminates abnormally:
```
$ ...
Didn't catch specific exception.
Didn't catch enough exceptions.
Didn't execute enough finallys.
Test FAILED.
Done
```

 - The Release build crashes:
```
$ ...
Unhandled Exception:
   Cannot print exception string because Exception.ToString() failed.
crashed [1468851501] processname=corerun, pid=18400, tid=18400, signal=6./run: line 12: 18400 Segmentation fault
```

**Comment by wateret** [comment]
@CarolEidt Here is the backtrace. Seems like compilation is successful, crashes in managed code.

```
Program received signal SIGSEGV, Segmentation fault.
0xb1fed724 in ?? ()
(gdb) bt
#0  0xb1fed724 in ?? ()
#1  0xb1fed5e6 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

**Comment by wateret** [comment]
@parjong I get the exactly same results with you got for that test case(NestedEx1).
