### ISSUE TITLE
Abbreviation: What does it mean? 

### ISSUE THREAD

**Issue by leemgs** [dotnet/coreclr#6181]
As we all know, there are a lot of abbreviations as terminology in ./coreclr/src/ folder. 
Where we can find the the original meaning of the abbreviations?

While browsing the source codes of coreclr to enable .NET Core on Linux: ARM, 
I often wonder about the meaning of the abbreviations. If there are not a related documentation,
I would like to create "TERMINOLOGY" file in ../coreclr/ folder. How about we append the file to keep
the existing(and new) terminologies?

* For example: 
```
botr: Book of the Runtime
classlibnative: Native Class Library 
coreclr: Core Common Language Runtime
dac: Data Access Component
gc: Garbage Collector
ilasm: Intermediate Language Assembler
ildasm: Intermediate Language Disassembler
jit: Just-In-Time
mscorlib: Microsoft Core Library
nativeresources: Native Resources
nig: Native Image Generator
pal: Platform Adaptation Layer
palrt: Platform Adaptation Layer's Run-Time
pe: Portable Executable 
vm: Virtual Machine

ToolBox: ???
binder: ???
corefx: 
debug: 
dlls: 
gcdump: 
gcinfo: 
inc: 
ipcman: 
md: 
scripts: 
strongname: 
tools: 
unwinder: 
utilcode: 
zap: 
and so on....
```

**Comment by lemmaa** [comment]
Anyway, we already have a https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/glossary.md . How about update this one?

**Comment by leemgs** [comment]
>  How about update this one?

Thanks. I will send a PR after writing the original meaning of the other abbreviations.

**Comment by leemgs** [comment]
The related PR is https://github.com/dotnet/coreclr/pull/6372. Closed.
