### ISSUE TITLE
Wrong symlinkEntrypointExecutable define for FreeBSD

### ISSUE THREAD

**Issue by sec** [dotnet/coreclr#6184]
This is defiend in - src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp
To get current process under FreeBSD, when using procfs, this should point to:
/proc/curproc/file

**Comment by gkhanna79** [comment]
CC @janvorli

**Comment by janvorli** [comment]
We should not be using procfs on FreeBSD, since it is not turned on by default. We should rather follow the NetBSD way and use the sysctl with KERN_PROC_PATHNAME.
NetBSD build falls back to procfs if the KERN_PROC_PATHNAME is not defined, but I don't know if that's necessary for FreeBSD too.

**Comment by brunolauze** [comment]
I don't think procfs should be in the picture since it's phasing out, not maintained, and from my understanding procfs would probably always fail if sysctl is failing in the first place. But we definitly want to run dotnet without procfs.

**Comment by josteink** [comment]
I can probably port/copy-paste my patch from core-setup https://github.com/dotnet/core-setup/pull/213 to fix this, but from what I can see, the existing NetBSD code might be able to work on FreeBSD too if we adapt the guards as needed.

My patch is simpler IMO, but using it would result in more code-duplication. Anyone have any opinions on the best approach forward?

**Comment by josteink** [comment]
Actually looking over the existing NetBSD code, the arguments for sysctl()'s mib section seems to be in a different order, there other, different constants in the code, making code re-use a bit more cumbersome than I think is worthwhile.

Unless anyone objects, I'll create a separate guard for FreeBSD with similar code as found in the PR linked above and use that.
