### ISSUE TITLE
AssemblyLoadContext: allow customizing key used lookup cached assemblies

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/coreclr#6187]
When AssemblyLoadContext triggers an assembly load, it first checks for cached assemblies already loaded. If I'm not mistaken, the key used for the cache is "Name+Version+Culture+PublicKey".

It would be useful to add additional assembly characteristics to the key (i.e. AssemblyInformationalVersion or AssemblyFileVersion).

Scenario: patch version upgrades to assemblies often carry the same name and AssemblyVersionAttribute, but patch upgrades may carry implementation changes (or security patches). If the default load context loaded an older assembly and assembly load context wants a newer, patched assembly, the load context will still get the older version because the patched version's assembly name+version didn't change.

Currently the only way to ensure the newer assembly version is loaded is to explicitly trigger an assembly load by calling `AssemblyLoadContext.LoadFromAssemblyName` before an automatic load has been triggered.

**Comment by natemcmaster** [comment]
cc @gkhanna79

**Comment by natemcmaster** [comment]
Btw, this could help us enable ASP.NET/EF Core tools on .NET Standard class library projects and improve how they work for .NET Core apps.

cc @NTaylorMullen @prafullbhosale

**Comment by jkotas** [comment]
`AssemblyLoadContext` is used to resolve assembly references. The assembly reference (ie key for `AssemblyLoadContext`) is specified as exactly `Name+Version+Culture+PublicKey` in the [ECMA 335](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/dotnet-standards.md) spec. The entire .NET ecosystem depends on this, it is not something that can be realistically changed. 

Could you please describe the problem/scenario you are trying to solve, without going into details on how to solve it?

**Comment by gokarnm** [comment]
I'm hitting this same issue with my scenario, here is what I'm trying to do.
 
I'm creating a custom AssemblyLoadContext in my application to load a plugin from a directory. The plugin can have additional dependencies on CoreFX or third party libraries. These dependencies can be same as my application's dependencies but the plugin may use a different version. A newer version of a CoreFX package could mean a patch version update in which case only the AssemblyInformationalVersion would be changed but the AssemblyVersion may remain the same. The plugin directory contains the plugin DLL and all its dependencies.
 
If the dependencies used by the plugin are already loaded into the default load context, the plugin also ends up using the same version as the application and not the version that the plugin provided. The Load method or Resolve event of the custom ALC is never called. The only way to have the plugin use the correct version of its dependencies is by calling the custom ALC's AssemblyLoadContext.LoadFromAssemblyName method and explicitly loading the dependency before it's automatically resolved. Also, I don't encounter the issue if the dependency is not referenced by the application therefore it's not loaded into default ALC.
 
I need to have copies of a dependency (same or different versions) loaded into default and custom ALC. Is there a way to provide isolation for an assembly loaded in a custom ALC (this works) and all it's dependencies (this doesn't work) irrespective of what's loaded in the default ALC? How can I intercept the resolution of a dependency of an assembly in an ALC, when the same dependency has been already loaded into the default ALC? I can provide a sample which replicates this issue if needed.

**Comment by jkotas** [comment]
> If the dependencies used by the plugin are already loaded into the default load context, the plugin also ends up using the same version as the application and not the version that the plugin provided. The Load method or Resolve event of the custom ALC is never called.

This looks like a bug. The Load method should be called in this case. @gkhanna79 Do you agree?

**Comment by gkhanna79** [comment]
@gokarnm do you have a repro for this? IIRC, there was a bug at somepoint that has been since fixed.

**Comment by gkhanna79** [comment]
CC @rahku

**Comment by gokarnm** [comment]
Yes, you are right, this was fixed previously #6269
