### ISSUE TITLE
Adding a skipcsc option to the build script to run crossgen of mscorlib, but not compilation of C# => IL

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#6191]
Right now it's impossible with the build script to get a good look at the outputted disassembly for mscorlib, mainly since this means you have to do a debug build of the runtime (e.g. so it'll understand environment variables like `COMPlus_NgenDisasm`) and a release build of mscorlib (so the IL won't be littered with `nop` instructions and the like). It would be nice if we could add a `skipcsc` option for only ngenning, but not compiling mscorlib to a .NET assembly. Then we could view the disassembly like this:

```cmd
set COMPlus_JitDisasm=Method
build skipmscorlib debug
build windowsmscorlib release
:: Copy over the release mscorlib/System.Private.CoreLib into the debug folder
build skipcsc skipnative
```

**Comment by jkotas** [comment]
The right way to do this is to copy debug clrjit.dll into release directory.

**Comment by jamesqo** [comment]
Ah OK then, I hadn't thought of it the other way around. Never mind :smile:
