### ISSUE TITLE
CoreMangLib/cti/system/globalization/regioninfo/RegionInfoCurrentRegion test fails on Debian

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#6196]
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_debian8.4_pri1_tst/51/testReport/CoreMangLib.cti.system.globalization.regioninfo/RegionInfoCurrentRegion/RegionInfoCurrentRegion/

The test fails with the following:

ERROR!!!-002: Unexpect exception:System.ArgumentException: There is no region associated with the Invariant Culture (Culture ID: 0x7F). Parameter name: name at System.Globalization.RegionInfo..ctor(String name) at RegionInfoCurrentRegion.PosTest1()

**Comment by tarekgh** [comment]
these tests has been already deleted from coreclr repo awhile ago as we have the full test coverage in corefx repo.
