### ISSUE TITLE
Environment.set_ExitCode doesn't change process' exit code

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#6206]
set_ExitCode is supposed to enable changing the exit code of an app with a void-returning Main method, but on CoreCLR setting it doesn't propagate accordingly, e.g. set it to 42, and the process' exit code is still 0.

**Comment by jkotas** [comment]
From https://github.com/dotnet/coreclr/pull/6207#issuecomment-231795793:

It would be nice if the fix preserved this desktop and Mono behavior:

```
using System;
class Program
{
    static int Main(string[] args)
    {
        AppDomain.CurrentDomain.ProcessExit += (sender, e) => {
            Console.WriteLine("Original exit code:" + Environment.ExitCode);
            Environment.ExitCode = 123;
            Console.WriteLine("New exit code:" + Environment.ExitCode);
        };
        return 12;
    }
}
```

Result:

```
Original exit code:12
New exit code:123

C:\>echo %errorlevel%
123
```

**Comment by mazong1123** [comment]
@jkotas I just ran your example by current code. The output is:

```
Original exit code:0
New exit code:123
```

To be clarified, the new exit code is correct on current code. Do you expect changing the code so that the original exit code could be `12` ?

And since I can't find `errorcode` as a environment variable on Linux, could you please guide me how to output %errorlevel% on Linux? Thanks.

**Comment by jkotas** [comment]
> Do you expect changing the source code so that the `Original exit code` could be `12` ?

Yes.

> could you please guide me how to output %errorlevel% on Linux?

`echo $?`

**Comment by gkhanna79** [comment]
@danmosemsft Is this for 2.0?

**Comment by danmosemsft** [comment]
I don't see it as essential. I see there's a potential fix in progress, so it may get fixed for 2.0.
@stephentoub @AlexGhiondea please push back if appropriate.

**Comment by gkhanna79** [comment]
@danmosemsft Please assign to whoever is driving the fix.

**Comment by jkotas** [comment]
This is CoreCLR bug. @mazong1123 submitted CoreCLR with the proposed fix. @janvorli and me are reviewers.

**Comment by danmosemsft** [comment]
Yep. @karelz can you please add @mazong1123 so he can be assigned this.

**Comment by danmosemsft** [comment]
OK @mazong1123 when you accept the invite I can assign you issues. You may get an invite for corefx also.

**Comment by mazong1123** [comment]
@danmosemsft I've accepted the invitation. Thanks!

**Comment by danmosemsft** [comment]
Welcome aboart @mazong1123 !

**Comment by karelz** [comment]
Thanks @mazong1123 for your contribution!
If you're interested in helping more, please checkout https://github.com/dotnet/corefx/issues/17619 and https://github.com/dotnet/corefx/wiki/New-contributor-Docs (the spirit applies to CoreCLR contributions as well).

**Comment by jkotas** [comment]
The corefx test is still disabled against this bug. https://github.com/dotnet/corefx/blob/0ebc867d6bad9d777dd61afb78d0445c86143b34/src/System.Runtime.Extensions/tests/System/Environment.Exit.cs#L52
@mazong1123 Could you please submit PR to enable the test? Removing ActiveIssue attribute should do the trick.

**Comment by mazong1123** [comment]
@jkotas The tests have been enabled and merged. I think this issue can be closed? 

Related PR: https://github.com/dotnet/corefx/pull/19232

**Comment by jkotas** [comment]
Yes, this can be closed now. Thanks again!
