### ISSUE TITLE
Environment.StackTrace includes unnecessary internal calls

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#6209]
With the move of Environment to corefx, StackTrace now goes through up to two additional call sites (Environment.StackTrace in corefx => EnvironmentAugments.StackTrace in coreclr => Environment.StackTrace in coreclr).  We should fix up the implementation to avoid this.

(Original comment from @jkotas: https://github.com/dotnet/coreclr/pull/6205#discussion_r70182553)

**Comment by mikem8361** [comment]
@stephentoub I'm don't understand what exactly needs to be done to the implementation.  Are those extra call sites really a (perf) problem? 

@Jiayili1 what tests were disabled?  This doesn't sound like an actual bug; more like a perf problem.

**Comment by stephentoub** [comment]
@mikem8361, my concern isn't perf: it's usability, and that the resulting trace you get shows extra, unnecessary gook.

**Comment by stephentoub** [comment]
> What tests were disabled?

https://github.com/dotnet/corefx/blob/124af1ea2f3e42736e81dae6b36c91f800108f2d/src/System.Diagnostics.TraceSource/tests/TraceEventCacheClassTests.cs#L60

**Comment by jkotas** [comment]
@mikem8361 We need to take the CoreFX->CoreCLR forwarder into account when generating the stacktrace and we need to make sure that the forwarder is noninlineable to get predictable behavior.

Let me know if you would prefer me to take care of this ... I know exactly what needs to be done here.

**Comment by mikem8361** [comment]
It would be great if you could do this one.  Thanks.
