### ISSUE TITLE
How to change to copy test native binaries in runtest.sh

### ISSUE THREAD

**Issue by YongseopKim** [dotnet/coreclr#6214]
Hello all.

I think some code in copy_test_native_bin_to_test_root function in tests/runtest.sh

``` bash
    # Copy native test components from the native test build into the respective test directory in the test root directory
    find "$testNativeBinDir" -type f -iname '*.$libExtension' |
        while IFS='' read -r filePath || [ -n "$filePath" ]; do
            local dirPath=$(dirname "$filePath")
            local destinationDirPath=${testRootDir}${dirPath:${#testNativeBinDir}}
            if [ ! -d "$destinationDirPath" ]; then
                exit_with_error "$errorSource" "Cannot copy native test bin '$filePath' to '$destinationDirPath/', as the destination directory does not exist."
            fi
            cp -f "$filePath" "$destinationDirPath/"
        done
```

Above '_.$libExtension' should be replaced with "_.$libExtension".

**Comment by YongseopKim** [comment]
Result&Reference: https://github.com/dotnet/coreclr/pull/6213

**Comment by YongseopKim** [comment]
Talking about wrong var in copy_test_native_bin_to_test_root function in #6213 leads to talking about how to change the way to copy test native binaries in runtest.sh.

According to @adityamandaleeka 's suggestion, that talking has started here since now.

**Comment by gkhanna79** [comment]
@wtgodbe can chime in as well.
