### ISSUE TITLE
Result of static code analysis with cppcheck

### ISSUE THREAD

**Issue by janhenke** [dotnet/coreclr#623]
I ran a static code analysis with cppcheck on the complete CoreCLR code base. The result can be seen here: http://jenkins.taujhe.de/job/CoreCLR%20Debug/cppcheckResult

In total cppcheck reported 5009 lines of code with different severity. If possible all reported lines should be checked and if necessary fixed.

This issue should be used to track progress and discuss general questions.

**Comment by janvorli** [comment]
@janhenke I've tried to take a look at one of the reported issues and it seems I don't have rights to do so. I got this message:

No valid permission
The current user must have the WORKSPACE permission for the job.

**Comment by janvorli** [comment]
@janhenke It seems that there is quite a number of "toomanyconfigs" issue, which says:
Too many #ifdef configurations - cppcheck only checks 12 of 75 configurations. Use --force to check all configurations.
It seems it would be nice to add the suggested --force parameter to get the full report.

**Comment by janhenke** [comment]
@janvorli I set that permission flag for the anonymous user on the project. Please check again if you can access the details.

For the latter I also added the `--force` flag. Before I trigger a new run though I want to be sure we do not have to change any other configuration, as cppcheck needs around 35 hours to go though the complete code (with force probably significantly longer).

**Comment by janvorli** [comment]
@janhenke Great, I can access the details now.

**Comment by janhenke** [comment]
In the mean time a new build is running. It should take at least 24 hours more, then we should have the results with the `--force` set.

**Comment by janvorli** [comment]
@janhenke - it has been a long time since you've tried to run the cppcheck with all the combinations of defines enabled. Last I've heard, it was running for about a month and still progressing.
So I'd like to check with you to see what we should do with this github issue.

**Comment by janhenke** [comment]
The second run sadly crashed before completion, after running for about 4 weeks. I still think such a static code analysis is useful, but it needs to run on something, where it finishes in much shorter time.

I talked about this on gitter, but must have forgotten to post here as well.

So we just have the results of the first run at this point.

**Comment by janvorli** [comment]
@janhenke Thanks for the info.

**Comment by janhenke** [comment]
I think this issue is of no further use. Closing it now.
