### ISSUE TITLE
Bad interaction between constant prop and CSE

### ISSUE THREAD

**Issue by papaslavik** [dotnet/coreclr#6234]
Exploring the invariant hoisting code I found that it doesn't work with the assignments.

In optimizer.cpp there's a code:

```
   if (treeIsInvariant)
    {
        // Tree must be a suitable CSE candidate for us to be able to hoist it.
        treeIsHoistable = optIsCSEcandidate(tree);

```

optIsCSEcandidate is false for assignments.

Though it won't work with the assignment the analysis will detect that the the expression subtree of the assignment is invariant and will actually clone the expression to the prehead block of the loop.

We'll get a tree looking e.g. like this:

```
------------ BB04 [029..???), preds={BB01} succs={BB02}

***** BB04, stmt 8 (top level)
     (  5,  5) [000098] -------------             *  stmtExpr  void  (top level) (IL   ???...  ???)
N006 (  0,  0) [000096] -------------             |  /--*  nop       void  
N007 (  5,  5) [000097] -------------             \--*  comma     void  
N004 (  1,  1) [000095] -------H-----                |  /--*  lclVar    int    V04 loc3         u:3 <l:$46, c:$1c1>
N005 (  5,  5) [000091] -------H-----                \--*  +         int    <l:$4a, c:$1c6>
N002 (  1,  1) [000094] -------H-----                   |  /--*  lclVar    int    V03 loc2         u:3 <l:$44, c:$1c0>
N003 (  3,  3) [000092] -------H-----                   \--*  +         int    <l:$49, c:$1c5>
N001 (  1,  1) [000093] -------H-----                      \--*  lclVar    int    V02 loc1         u:3 <l:$42, c:$101>

------------ BB02 [029..043) -> BB02 (cond), preds={BB02,BB04} succs={BB03,BB02}

```

The result of such a tree is not used and on the code generator no code is produced for such a tree.

/cc @BruceForstall @brucehoult @briansull @Dmitri-Botcharnikov

**Comment by papaslavik** [comment]
If we try to avoid the check for assignments then we'll anyway face to another check in 
Compiler::optTreeIsValidAtLoopHead:

```
// If the loop does not contains the SSA def we can hoist it.                                                                                                                                                                        if (!optLoopTable[lnum].lpContains(lvaTable[lclNum].GetPerSsaData(lclVar->GetSsaNum())->m_defLoc.m_blk))
                return true;
```

**Comment by papaslavik** [comment]
If we workaround the check with the code:
`treeIsHoistable = optIsCSEcandidate(tree) || (tree->gtFlags & GTF_ASG);`

We'll anyway get aborted by Compiler::optTreeIsValidAtLoopHead because the following check won't work:
```
        // If the loop does not contains the SSA def we can hoist it.
        if (!optLoopTable[lnum].lpContains(lvaTable[lclNum].GetPerSsaData(lclVar->GetSsaNum())->m_defLoc.m_blk))
            return true;
```

**Comment by briansull** [comment]
The hoisting logic in the JIT leaves the assignment there and hoist out a copy of the rvalue from the assignment

 while (!done) {
    j = a+b+c;
    ...
}

That should turn into 

cse0 = (a+b+c);
while (!done) {
    j = cse0;     
}

**Comment by papaslavik** [comment]
It should, I believe, according to the logic in the code: (a+b+c) is treated as subtree of j = a+b+c;
the subtree is hoisted. But the resulting tree which we copy to the loop pre-head is useless. I think that is because in Compiler::optPerformHoistExpr we have such a code:
```
    GenTreePtr hoist = hoistExpr;
    // The value of the expression isn't used (unless it's an assignment).
    if (hoistExpr->OperGet() != GT_ASG)
    {
        hoist = gtUnusedValNode(hoistExpr);
    }
```

So we get such tree (for which e.g. the codegen doesn't do anything)

```
------------ BB04 [029..???), preds={BB01} succs={BB02}

***** BB04, stmt 8 (top level)
     (  5,  5) [000098] -------------             *  stmtExpr  void  (top level) (IL   ???...  ???)
N006 (  0,  0) [000096] -------------             |  /--*  nop       void  
N007 (  5,  5) [000097] -------------             \--*  comma     void  
N004 (  1,  1) [000095] -------H-----                |  /--*  lclVar    int    V04 loc3         u:3 <l:$46, c:$1c1>
N005 (  5,  5) [000091] -------H-----                \--*  +         int    <l:$4a, c:$1c6>
N002 (  1,  1) [000094] -------H-----                   |  /--*  lclVar    int    V03 loc2         u:3 <l:$44, c:$1c0>
N003 (  3,  3) [000092] -------H-----                   \--*  +         int    <l:$49, c:$1c5>
N001 (  1,  1) [000093] -------H-----                      \--*  lclVar    int    V02 loc1         u:3 <l:$42, c:$101>

------------ BB02 [029..043) -> BB02 (cond), preds={BB02,BB04} succs={BB03,BB02}
```


That's why I named the issue not just for assignments.

**Comment by mikedn** [comment]
Do you have a complete example? I'm sure I've seen invariant hoisting working, albeit with various limitations.

**Comment by papaslavik** [comment]
My example was similar to the one shown by @briansull 

```
internal class Program                                                                                                                                                                                                                                                         
{                                                                                                                                                                                                                                                                              
    public static int ii;
    private static int Main(string[] args)
    {
        int res = 0;
        ii = 99;
          int b = ii;
          int d = ii - 98;
          int e = ii - 93;
          int f = 0;
          for (int i = 0; i < b; ++i) {
             f = b + d + e;
             res += f;
          }
         return res;
    }
}

```

**Comment by papaslavik** [comment]
The result for that code is the following (also showing the overhead of static variable load, stores and address computation, but the latter is codegen related):

                                                                                              

```
G_M35508_IG01:
000000  E92D 4818      push    {r3,r4,r11,lr}
000004  F10D 0B08      add     r11, sp, 8

G_M35508_IG02:
000008  2000           movs    r0, 0
00000A  2363           movs    r3, 99
00000C  F243 02C4      movw    r2, 0x30c4
000010  F2CB 5287      movt    r2, 0xb587
000014  6013           str     r3, [r2]
000016  F243 02C4      movw    r2, 0x30c4
00001A  F2CB 5287      movt    r2, 0xb587
00001E  6812           ldr     r2, [r2]
000020  F243 03C4      movw    r3, 0x30c4
000024  F2CB 5387      movt    r3, 0xb587
000028  681B           ldr     r3, [r3]
00002A  F1A3 0462      sub     r4, r3, 98
00002E  F243 03C4      movw    r3, 0x30c4
000032  F2CB 5387      movt    r3, 0xb587
000036  681B           ldr     r3, [r3]
000038  F1A3 0E5D      sub     lr, r3, 93
00003C  2300           movs    r3, 0
00003E  2A00           cmp     r2, 0
000040  DD05           ble     SHORT G_M35508_IG04

G_M35508_IG03:
000042  1911           adds    r1, r2, r4
000044  4471           add     r1, lr
000046  4408           add     r0, r1
000048  3301           adds    r3, 1
00004A  4293           cmp     r3, r2
00004C  DBF9           blt     SHORT G_M35508_IG03

G_M35508_IG04:
00004E  E8BD 4818      pop     {r3,r4,r11,lr}
000052  4770           bx      lr

; Total bytes of code 84, prolog size 8 for method Program:Main(ref):int
; ============================================================

```

**Comment by papaslavik** [comment]
x64 version (albeit an earlier one) - has all the similar issues:

```
G_M35508_IG01:
       55                   push     rbp
       488BEC               mov      rbp, rsp

G_M35508_IG02:
       33C0                 xor      eax, eax
       48BF6439E283477F0000 mov      rdi, 0x7F4783E23964
       C70763000000         mov      dword ptr [rdi], 99
       8B3F                 mov      edi, dword ptr [rdi]
       48BE6439E283477F0000 mov      rsi, 0x7F4783E23964
       8B36                 mov      esi, dword ptr [rsi]
       83C69E               add      esi, -98
       48BA6439E283477F0000 mov      rdx, 0x7F4783E23964
       8B12                 mov      edx, dword ptr [rdx]
       83C2A3               add      edx, -93
       33C9                 xor      ecx, ecx
       85FF                 test     edi, edi
       7E10                 jle      SHORT G_M35508_IG04

G_M35508_IG03:
       448D0437             lea      r8d, [rdi+rsi]
       4403C2               add      r8d, edx
       4103C0               add      eax, r8d
       FFC1                 inc      ecx
       3BCF                 cmp      ecx, edi
       7CF0                 jl       SHORT G_M35508_IG03

G_M35508_IG04:
       5D                   pop      rbp
       C3                   ret      

```

**Comment by papaslavik** [comment]
I think that GT_ASG should be allowed and when we check the SSA variable assignment in the loop block, we should check that there's a phi-node for that value in the loop instead.

**Comment by papaslavik** [comment]
Even if I add what I propose to the code: 
`optIsCSEcandidate(tree) || (tree->gtFlags & GTF_ASG);`

and to Compiler::optTreeIsValidAtLoopHead:

```
// If the tree is the non-phi def itself then its the invariant assignment
        GenTreePtr def_tree = lvaTable[lclNum].GetPerSsaData(lclVar->GetSsaNum())->m_defLoc.m_tree;
        if (def_tree == tree && tree->OperIsNonPhiLocal())
            return true;

        // If the loop does not contains the SSA def we can hoist it.
        if (!optLoopTable[lnum].lpContains(lvaTable[lclNum].GetPerSsaData(lclVar->GetSsaNum())->m_defLoc.m_blk))
            return true;
```

The assignment will be hoisted.
But the previous expression inside the loop will still be there, and in the end we again get the non-hoisted code generated.

**Comment by papaslavik** [comment]
In fact such a hoisted assignment, of course, breaks the SSA because the value has to defs now.
So the def in loop should be removed and the block for the SSA def should be redirected to the loop pre head.

**Comment by mikedn** [comment]
> I think that GT_ASG should be allowed and when we check the SSA variable assignment in the loop block, we should check that there's a phi-node for that value in the loop instead.

That may not be enough. The check in `optIsCSEcandidate` doesn't specifically check if the node is an assignment, it checks if the tree contains any assignments.

Also, in this particular case the best solution would be to just get rid of the `f` variable which is simply not needed. This is something that come up before, for example in #1993.

**Comment by papaslavik** [comment]
Of course we shouldn't change the code for CSE, we'd rather make that in a somewhat different manner. For my workaround to test it I did just
`optIsCSEcandidate(tree) || (tree->gtFlags & GTF_ASG);`

But then there's an obstacle that once you have a ssa def in the loop for the value, you won't be allowed to hoist the tree.

As I wrote above I bypassed those check-related issues, but the result is bad SSA, and the original tree is still in the loop.

**Comment by papaslavik** [comment]
@mikedn what do you mean by getting rid of the f variable?
it doesn't matter if you use the variable or not, you won't have invariant motion either way.

**Comment by papaslavik** [comment]
The issue you mentioned above #1993 is a more general one.
The trees correspond to IL expressions and they live like that till the codegen. It was just the reason why I looked at the invariant motion.

I wanted to see how it will do some inter-tree thing on the example of invariant motion, but the latter just doesn't work.

**Comment by papaslavik** [comment]
Being said that the invariant motion is not so inter-tree activity anyway. It can just hoist some trees or subtrees without merging any trees with different IL's.

But cloning a tree to the loop prehead ir doesn't specify any IL:
`(  5,  5) [000098] -------------             *  stmtExpr  void  (top level) (IL   ???...  ???)`

 So, I hypothesize that IL pc is not that important to be preserved till the code generation.

**Comment by mikedn** [comment]
> it doesn't matter if you use the variable or not, you won't have invariant motion either way.

Right, because anyway there's the assignment to `res` so we're probably back at square one.

**Comment by papaslavik** [comment]
@briansull 
```

while (!done) {
j = a+b+c;
...
}

That should turn into

cse0 = (a+b+c);
while (!done) {
j = cse0;

}
```

Did you actually mean that it could work the following way:

```
while (!done) {
j = a+b+c;
...
}

That should turn into

cse0 = a+b+c;
while (!done) {
j = a+b+c;

}

And then presumably a subsequent CSE would do:
cse0 = (a+b+c);
while (!done) {
j = cse0;

}
```

I believe CSE won't push expression copies to the loop though.

**Comment by papaslavik** [comment]
A straight cse example also doesn't work
```
res += b + d + e;
res += b + d + e;
```
The generated code still does all the things twice:

```
000030  1898           adds    r0, r3, r2
000032  4408           add     r0, r1
000034  4418           add     r0, r3
000036  4410           add     r0, r2
000038  4408           add     r0, r1

```

```
for (int i = 0; i < b; ++i) {
          res += (b + d + e) + (b + d + e);
        }
        return res;

```

The result is:
```
G_M10576_IG03:
000042  4418           add     r0, r3
000044  4408           add     r0, r1
000046  4420           add     r0, r4
000048  4418           add     r0, r3
00004A  4408           add     r0, r1
00004C  4420           add     r0, r4
00004E  3201           adds    r2, 1
000050  429A           cmp     r2, r3
000052  DBF6           blt     SHORT G_M10576_IG03
```

**Comment by mikedn** [comment]
> A straight cse example also doesn't work...

This looks like a different issue: #3169

**Comment by papaslavik** [comment]
@mikedn so, do you mean that the re-association is the root for the no cse application in that case?

**Comment by papaslavik** [comment]
Ok @mikedn I got it. I made an example in which cse works but in a similar example LICH fails:

So here's the example with working cse:

```
internal class Program                                                                                                                                                                                                                                                         
{                                                                                                                                                                                                                                                                              
    public static int ii;
    private static int Main(string[] args)
    {
        int res = 0;
        ii = 99;
        int b = ii;
        int a = ii - 1;
        int f = (b+a);          
        for (int i = 0; i < b; ++i) {
           int res1 = (b+a);
           res += res1;
        }
        res += f;
        return res;
    }
}

```

The ARM code is:

```
..................
..................
..................
00002C  1911           adds    r1, r2, r4
00002E  2300           movs    r3, 0
000030  2A00           cmp     r2, 0
000032  DD03           ble     SHORT G_M24129_IG04

G_M24129_IG03:
000034  4408           add     r0, r1
000036  3301           adds    r3, 1
000038  4293           cmp     r3, r2
00003A  DBFB           blt     SHORT G_M24129_IG03

```

So in this example it really made what we wanted it to do for LICH.

But then we remove the f local variable:

```
internal class Program                                                                                                                                                                                                                                                         
{                                                                                                                                                                                                                                                                              
    public static int ii;
    private static int Main(string[] args)
    {
        int res = 0;
        ii = 99;
        int b = ii;
        int a = ii - 1;
//        int f = (b+a);          
        for (int i = 0; i < b; ++i) {
           int res1 = (b+a);
           res += res1;
        }
//        res += f;
        return res;
    }
}
```

And we expect the expression to be hoisted and then cse-ed.
But the resulting code still has the expression in the loop:

```
G_M19493_IG03:
000032  1911           adds    r1, r2, r4
000034  4408           add     r0, r1
000036  3301           adds    r3, 1
000038  4293           cmp     r3, r2
00003A  DBFA           blt     SHORT G_M19493_IG03

```

**Comment by mikedn** [comment]
As far as I can tell there are multiple issues. One is re-association. Another one might involve assignments but it's not clear to me what exactly is going on in that case. That said, given the existing code I'm pretty sure that the JIT should handle something like this:

```C#
var r = new Random();
int x = r.Next();
int y = r.Next();
int z = r.Next();

for (int i = 0; i < 10; i++)
    Console.WriteLine((x * y * z).ToString());
```
There's no re-association and there's no assignment yet it doesn't work:
```
G_M51147_IG03:
       8BCF                 mov      ecx, edi
       0FAFCB               imul     ecx, ebx
       0FAFCE               imul     ecx, esi
       894DD8               mov      dword ptr [rbp-28H], ecx
       488D4DD8             lea      rcx, bword ptr [rbp-28H]
       E89D301C5E           call     System.Int32:ToString():ref:this
       488BC8               mov      rcx, rax
       E89563E05D           call     System.Console:WriteLine(ref)
       41FFC6               inc      r14d
       4183FE0A             cmp      r14d, 10
       7CDB                 jl       SHORT G_M51147_IG03
```
Smells like a genuine bug to me and not some kind of JIT limitation.

**Comment by papaslavik** [comment]
Is that still the same if you remove z?

In fact I can tell that the subtree is hoisted, albeit as **unused** one in Compiler::optPerformHoistExpr.

Then in fact CSE would need to detect the similarity. But somehow that doesn't happen.

**Comment by mikedn** [comment]
> Is that still the same if you remove z?

Yup. 

There's seems to be an `GT_ARGPLACE` for which `optIsCSEcandidate` returns false but I don't see what that has to do with the multiplication.

**Comment by papaslavik** [comment]
Try placing this before the loop:
`int xyz = (x * y * z);`

and this after the loop:
`Console.WriteLine((x * y * z).ToString());`

**Comment by mikedn** [comment]
I had to change the example a bit, it appears that the use of `ToString` introduces a `GT_ASG`. So:

```C#
[MethodImpl(MethodImplOptions.NoInlining)]
static void use(int x)
{
}

static void Main()
{
    var r = new Random();
    int x = r.Next();
    int y = r.Next();
    int z = r.Next();
    int xyz = (x * y * z);

    for (int i = 0; i < 10; i++)
        use(x * y * z);

    use(x * y * z);
}
```
No luck, there's no CSE and no hoisting. Only `xyz` got eliminated.
```
G_M51147_IG03:
       8BCF                 mov      ecx, edi
       0FAFCB               imul     ecx, ebx
       0FAFCE               imul     ecx, esi
       E892FBFFFF           call     ConsoleApplication16.Program:use(int)
       41FFC6               inc      r14d
       4183FE0A             cmp      r14d, 10
       7CEA                 jl       SHORT G_M51147_IG03

G_M51147_IG04:
       0FAFFB               imul     edi, ebx
       8BCF                 mov      ecx, edi
       0FAFCE               imul     ecx, esi
       E87CFBFFFF           call     ConsoleApplication16.Program:use(int)
       90                   nop
```

**Comment by mikedn** [comment]
This works:
```C#
    use(x * y * z);

    for (int i = 0; i < 10; i++)
        use(x * y * z);

    use(x * y * z);
```
```
       0FAFFB               imul     edi, ebx
       8BF7                 mov      esi, edi
       0FAFF0               imul     esi, eax
       8BCE                 mov      ecx, esi
       E897FBFFFF           call     ConsoleApplication16.Program:use(int)
       33FF                 xor      edi, edi

G_M51147_IG03:
       8BCE                 mov      ecx, esi
       E88EFBFFFF           call     ConsoleApplication16.Program:use(int)
       FFC7                 inc      edi
       83FF0A               cmp      edi, 10
       7CF2                 jl       SHORT G_M51147_IG03

G_M51147_IG04:
       8BCE                 mov      ecx, esi
       E880FBFFFF           call     ConsoleApplication16.Program:use(int)
```
But this is CSE, not genuine LICH.

**Comment by papaslavik** [comment]
Yeah, just wanted to tell you that  use(x * y * z); should have been replaced with 
use(xyz); cause otherwise xyz must be eliminated earlier.

But in your latest example it is what we wanted.

Yeah, removing the upper use() call you'll lose the invariant hoisted.

**Comment by papaslavik** [comment]
So the problem seems to be like this. Although the invariant hoisting is actually happens for the subtree the tree generated from that is somehow **wrong** for cse to do anything with it.

**Comment by papaslavik** [comment]
So dumping the compilation, after optHoistLoopCode() we do have such trees:

```
.................
.................
------------ BB04 [024..???), preds={BB01} succs={BB02}

***** BB04, stmt 7 (top level)
     ( 11,  9) [000073] -------------             *  stmtExpr  void  (top level) (IL   ???...  ???)
N006 (  0,  0) [000071] -------------             |  /--*  nop       void  
N007 ( 11,  9) [000072] -------------             \--*  comma     void  
N004 (  1,  1) [000070] -------H-----                |  /--*  lclVar    int    V02 loc2         u:3 <l:$45, c:$201>
N005 ( 11,  9) [000066] -------H-----                \--*  *         int    <l:$4b, c:$204>
N002 (  1,  1) [000069] -------H-----                   |  /--*  lclVar    int    V01 loc1         u:3 <l:$43, c:$200>
N003 (  6,  5) [000067] -------H-----                   \--*  *         int    <l:$49, c:$203>
N001 (  1,  1) [000068] -------H-----                      \--*  lclVar    int    V00 loc0         u:3 <l:$42, c:$1c0>

------------ BB02 [024..03A) -> BB02 (cond), preds={BB02,BB04} succs={BB03,BB02}

***** BB02, stmt 8 (top level)
     (  2,  3) [000061] -------------             *  stmtExpr  void  (top level) (IL   ???...  ???)
N005 (  2,  2) [000059] -------------             |     *  phi       int   
N001 (  0,  0) [000064] -------------             |     /--*  phiArg    int    V03 loc3         u:5
N002 (  0,  0) [000062] -------------             |     \--*  phiArg    int    V03 loc3         u:3 $40
N007 (  2,  3) [000060] -A------R----             \--*  =         int   
N006 (  1,  1) [000058] D------N-----                \--*  lclVar    int    V03 loc3         d:4

***** BB02, stmt 9 (top level)
     ( 27, 20) [000039] -------------             *  stmtExpr  void  (top level) (IL 0x024...0x031)
N009 ( 27, 20) [000037] --C-G--------             \--*  call      void   Program.use $VN.Void
N006 (  1,  1) [000035] -------------                |  /--*  lclVar    int    V02 loc2         u:3 <l:$45, c:$201>
N007 ( 11,  9) [000036] ------------- arg0 in r0     \--*  *         int    <l:$4b, c:$204>
N004 (  1,  1) [000033] -------------                   |  /--*  lclVar    int    V01 loc1         u:3 <l:$43, c:$200>
N005 (  6,  5) [000034] -------------                   \--*  *         int    <l:$49, c:$203>
N003 (  1,  1) [000032] -------------                      \--*  lclVar    int    V00 loc0         u:3 <l:$42, c:$1c0>

.............................
........................
........................
```

But it doesn't go anywhere for the subsequent CSE

**Comment by mikedn** [comment]
I think my example accidentally uncovered another LICH issue - VN can't recognize the result of `Random.Next()` as being loop invariant. `optVNIsLoopInvariant` relies on a `VNFunc` being recorded for that call but there isn't one. In the absence of that it can't map the VN to its SSA def so it can't tell if it's invariant or not.

Now that we know the various limitations JIT's LICH has we can put together an example that actually works:

```C#
static int foo(int x, int y, int z) {
    int r = 0;
    for (int i = 0; i < 10; i++)
        r += x * y * z;
    return r;
}
```
```
G_M52166_IG02:
       33C0                 xor      eax, eax
       4533C9               xor      r9d, r9d
       0FAFCA               imul     ecx, edx
       8BD1                 mov      edx, ecx
       410FAFD0             imul     edx, r8d

G_M52166_IG03:
       03C2                 add      eax, edx
       41FFC1               inc      r9d
       4183F90A             cmp      r9d, 10
       7CF5                 jl       SHORT G_M52166_IG03
```

**Comment by briansull** [comment]
The way that this works is that "hoisting" isn't actually moving anything, so don't think of it as actually hoisting anything.

Instead for some invariant expressions inside of loops, we have the method optPerformHoistExpr make a new copy of the invariant expression and place in a possibly newly created loop pre-header block.

We then expect that the CSE phase will see that both expressions have the same value number and that CSE will perform it optimization so that we are left with the constant expression being computer once outside the loop and a CSE ref inside the loop.

If you have a test case where this isn't happening (and from the above discussion it sounds like we do)
then we will investigate and find out why this isn't happening and likely fix.

Things that could prevent this from happening:
1. The Value Number don't match so no CSE.
2.  The CSE hueristic decides for dsome reason that it isn't profitable to perform a CSE subsitution.
3.  Some other transformation interferes before the CSE phase runs. Maybe (a + (b +c)) is changed into ((a +b) +c) for one of the two expressions.

Even if the CSE phase decides not to perfom  a CSE subsitution, I think that the code inserted in the preheader will typically be eliminated as "dead code" as the value computed is not used and there are no side-effects.

**Comment by mikedn** [comment]
> Instead for some invariant expressions inside of loops, we have the method optPerformHoistExpr make a new copy of the invariant expression and place it a newly created loop pre-header block.

Yes, but there are multiple cases where the compiler fails to detect that an expression is invariant so we don't even get to the actual hosting and CSE.

**Comment by briansull** [comment]
> there are case where the compiler fails to detect that an expression 

That is also true.

**Comment by mikedn** [comment]
> Things that could prevent this from happening:
> 1. The Value Number doesn't match so no CSE.
> 2. The CSE heuristic decides for some reason that it isn't profitable to perform a CSE substitution.
> 3. Some other transformation interferes before the CSE phase runs. 
> Maybe (a + (b +c)) is changed into ((a +b) +c) for one of the two expressions.

Add 4 - VN identifies the invariant expression as being constant and CSE rejects constants. 

Right, who would want to CSE a constant? But if it's constant why wasn't the tree replaced with the actual constant? And of course, while constants are invariant it is usually pointless to hoist them.

If we make `ii` volatile then @papaslavik 's example works as expected:
```
       03CA                 add      ecx, edx
       4103C8               add      ecx, r8d

G_M32463_IG03:
       448BC1               mov      r8d, ecx
       4103C0               add      eax, r8d
       41FFC1               inc      r9d
       443BCA               cmp      r9d, edx
       7CF2                 jl       SHORT G_M32463_IG03
```

**Comment by papaslavik** [comment]
thanks @briansull I've already grasped the idea :)

@mikedn so making it volatile works, you say. But why then CSE seemed to be working in the case:

```
        int f = (b+a);          
        for (int i = 0; i < b; ++i) {
           int res1 = (b+a);
           res += res1;
        }

```

**Comment by mikedn** [comment]
> But why then CSE seemed to be working in the case

I looked a bit at the dump generated by that example and I think that copy propagation did it. The two `(b+a)` have the same VN so copy prop replaces `res1` with `f`. Then `res1` becomes dead and it is eliminated in a subsequent phase.

**Comment by mikedn** [comment]
I created #6303 for my `Random.Next` example, it seems to be very different from @papaslavik's example that started this issue.

**Comment by mikedn** [comment]
> VN identifies the invariant expression as being constant and CSE rejects constants. 

There's a bit of conflict between constant propagation and CSE. Constant propagation uses conservative VNs and thinks that the expression is not a constant because other threads may change the static variable `ii`. CSE uses liberal VNs and thinks that the expression is a constant so it ignores it.

The fact that constant prop uses conservative VNs is debatable given that `ii` isn't volatile. But if that's how it's supposed to work then `optValnumCSE_Locate` should also use conservative VNs to identify constant expressions.

**Comment by JosephTremoulet** [comment]
Updated title to reflect the concrete issue.

> The fact that constant prop uses conservative VNs is debatable 

I agree it seems odd to restrict constant propagation to conservative VNs.  I suppose the fear would be that a constant is store to a memory location that is used in a bounds check and to index into an array -- constant-prop removing the bound check without removing the load to index into the array could break memory safety.  But I think what would be best is doing the constant propagation with the "liberal VN" view and guarding against that situation, e.g. by actually replacing the constants instead of just flagging them without any guarantees about what will be rewritten.

> if that's how it's supposed to work then `optValnumCSE_Locate` should also use conservative VNs to identify constant expressions

I definitely agree with that.  It could also dovetail with an earlier constant-prop rewrite since presumably the replaced constants would have constant conservative VNs.
