### ISSUE TITLE
RyuJIT x86: Silent bad codegen in signed genCompareLong 

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#6238]
We have a silent bad codegen bug with signed compare. Currently, we do an unsigned set after possibly doing a signed compare/jump from the hi comparison:

cmp      edx, esi
jg          SHORT G_M17400_IG04
jne        SHORT G_M17400_IG04
cmp      eax, ecx

G_M17400_IG04:
setb     al

In a signed comparison, the hi operation needs a signed set, and the lo operation needs an unsigned set.

Test case that generates this bad code:

   [MethodImplAttribute(MethodImplOptions.NoInlining)]
   public static int compareLong(long a, long b)
   {
       if (a < b)
           return 5;
       else
           return 0;
   }
   public static int Main()
   {
       long a = -2L;
       long b = 0L;
       int c = compareLong(a, b);

       if (c == 5)
           return 100;
       else
            return 0;
   }

**Comment by BruceForstall** [comment]
@adiaaida is this issue now fixed (by #6219)? Can it be closed?

**Comment by adiaaida** [comment]
Yes, sorry.
