### ISSUE TITLE
Missing implementation in exception/seh.cpp breaks build on FreeBSD

### ISSUE THREAD

**Issue by josteink** [dotnet/coreclr#626]
Currently the build breaks with the following errors on FreeBSD:

````
/home/josteink/build/cc2/src/pal/src/exception/seh.cpp:179:2: error: not yet implemented
#error not yet implemented
 ^
/home/josteink/build/cc2/src/pal/src/exception/seh.cpp:206:2: error: not yet implemented
#error not yet implemented
 ^
In file included from /home/josteink/build/cc2/src/pal/src/exception/seh.cpp:211:
/home/josteink/build/cc2/src/pal/src/exception/seh-unwind.cpp:33:10: fatal error: 'libunwind.h' file not found
#include <libunwind.h>
         ^
````

There's also a failed attempt to resolve libunwind.h, even though no complaints are made during configuration.

**Comment by kangaroo** [comment]
For the seh.cpp changes, you can likely safely add FreeBSD to the __LINUX__ block.

**Comment by josteink** [comment]
Libunwind is installed and I think detected during configuration. I'll use your VERIFY trick to see what include folders are passed along to clang.

**Comment by kangaroo** [comment]
I think you mean VERBOSE? :)

**Comment by josteink** [comment]
I'm on vacation and doing all this work on a Nexus 7 (no really!), so I will have to blame autocorrect ;)

**Comment by kangaroo** [comment]
Its ok, I'm on vacation and not doing work :+1:

**Comment by josteink** [comment]
As for libunwind, it is installed, but for some reason /usr/local/include does not get invoked:

````
cd /home/josteink/build/cc/bin/obj/FreeBSD.x64.Debug/src/utilcode/staticnohost && /usr/local/bin/clang++35   -DAMD64 -DBETA=0 -DBIT64=1 -DBUILDENV_CHECKED=1 -DCONDITION_HANDLING=1 -DDBG_TARGET_AMD64 -DDBG_TARGET_A
MD64_UNIX -DDEBUG -DDEBUGGING_SUPPORTED -DDEV10 -DDEVL=1 -DDISABLE_CONTRACTS -DFEATURE_APPDOMAIN_RESOURCE_MONITORING -DFEATURE_ARRAYSTUB_AS_IL -DFEATURE_ASYNC_IO -DFEATURE_BCL_FORMATTING -DFEATURE_COLLECTIBLE_TYPE
S -DFEATURE_CORECLR -DFEATURE_COREFX_GLOBALIZATION -DFEATURE_CORESYSTEM -DFEATURE_CORRUPTING_EXCEPTIONS -DFEATURE_DBGIPC_TRANSPORT_DI -DFEATURE_DBGIPC_TRANSPORT_VM -DFEATURE_EXCEPTIONDISPATCHINFO -DFEATURE_FRAMEWORK_INTERNAL -DFEATURE_HOSTED_BINDER -DFEATURE_HOST_ASSEMBLY_RESOLVER -DFEATURE_ICASTABLE -DFEATURE_IMPLICIT_TLS -DFEATURE_ISYM_READER -DFEATURE_LEGACYNETCF -DFEATURE_LEGACYNETCFFAS -DFEATURE_LEGACYNETCF_DBG_HOST_CONTROL -DFEATURE_LOADER_OPTIMIZATION -DFEATURE_MAIN_CLR_MODULE_USES_CORE_NAME -DFEATURE_MANAGED_ETW -DFEATURE_MANAGED_ETW_CHANNELS -DFEATURE_MERGE_CULTURE_SUPPORT_AND_ENGINE -DFEATURE_MULTICOREJIT -DFEATURE_NORM_IDNA_ONLY -DFEATURE_PAL -DFEATURE_PAL_SXS -DFEATURE_PREJIT -DFEATURE_STANDALONE_SN -DFEATURE_STRONGNAME_DELAY_SIGNING_ALLOWED -DFEATURE_STRONGNAME_MIGRATION -DFEATURE_STUBS_AS_IL -DFEATURE_SVR_GC -DFEATURE_SYMDIFF -DFEATURE_SYNTHETIC_CULTURES -DFEATURE_USE_ASM_GC_WRITE_BARRIERS -DFEATURE_VERSIONING -DFEATURE_WIN32_REGISTRY -DFEATURE_WINDOWSPHONE -DFEATURE_WINMD_RESILIENT -DFX_BRANCH_SYNC_COUNTER_VALUE=0 -DNO_CRT -DNTDDI_VERSION=NTDDI_WIN8 -DNTMAKEENV -DNT_INST=0 -DOFFICIAL_BUILD=0 -DPLATFORM_UNIX=1 -DSELF_NO_HOST -DUNICODE -DUNIX_AMD64_ABI -DURTBLDENV_FRIENDLY=Checked -DWIN32 -DWIN32_LEAN_AND_MEAN=1 -DWINNT=1 -DWINVER=0x0602 -DWRITE_BARRIER_CHECK=1 -D_AMD64_ -D_AMD64_SIMULATOR_ -D_AMD64_SIMULATOR_PERF_ -D_AMD64_WORKAROUND_ -D_BLD_CLR -D_CRT_STDIO_ARBITRARY_WIDE_SPECIFIERS -D_DBG -D_DEBUG -D_NEW_SDK=1 -D_SECURE_SCL=0 -D_SKIP_IF_SIMULATOR_ -D_TARGET_AMD64_=1 -D_UNICODE -D_WIN32_IE=0x0900 -D_WIN32_WINNT=0x0602 -D_WIN64 -Wall -Wno-null-conversion -std=c++11 -nostdinc++ -g -O0 -I/home/josteink/build/cc/bin/obj/FreeBSD.x64.Debug/src/utilcode/staticnohost -I/home/josteink/build/cc/src/utilcode/staticnohost -I/home/josteink/build/cc/src/pal/prebuilt/inc -I/home/josteink/build/cc/src/pal/inc -I/home/josteink/build/cc/src/pal/inc/rt -I/home/josteink/build/cc/src/pal/src/safecrt -I/home/josteink/build/cc/src/inc -I/home/josteink/build/cc/src/strongname/inc -I/home/josteink/build/cc/src/inc/winrt -I/home/josteink/build/cc/src/debug/inc -I/home/josteink/build/cc/src/debug/inc/amd64 -I/home/josteink/build/cc/src/debug/inc/dump -I/home/josteink/build/cc/src/md/inc -I/home/josteink/build/cc/src/classlibnative/bcltype -I/home/josteink/build/cc/src/classlibnative/cryptography -I/home/josteink/build/cc/src/classlibnative/inc    -ferror-limit=4096 -Wno-unused-private-field -Wno-dangling-else -Wno-implicit-exception-spec-mismatch -Wno-overloaded-virtual -Wno-unused-variable -Wno-switch -Wno-microsoft -Wno-tautological-compare -Wno-constant-logical-operand -Wno-unknown-warning-option -Wno-invalid-offsetof -Wno-delete-non-virtual-dtor -Wno-incompatible-ms-struct -fms-extensions -nostdinc -fPIC -o CMakeFiles/utilcodestaticnohost.dir/__/stgpool.cpp.o -c /home/josteink/build/cc/src/utilcode/stgpool.cpp
--- src/pal/src/CMakeFiles/CoreClrPal.dir/all ---
In file included from /home/josteink/build/cc/src/pal/src/exception/seh.cpp:211:
/home/josteink/build/cc/src/pal/src/exception/seh-unwind.cpp:33:10: fatal error: 'libunwind.h' file not found
#include <libunwind.h>
         ^
1 warning and 1 error generated.
````

There's no `-I` for `/usr/include` nor `/usr/local/include` (where libunwind.h) resides, despite it getting detected at configure-time.

**Comment by kangaroo** [comment]
@josteink /usr/local/include isn't usually included by default.  You can use the LLDB_INCLUDE_DIR env var to force the LLDB pass to look there.

**Comment by janhenke** [comment]
I think we fixed the `/usr/local/include` for PAL only so far. It seems we have to take a look at the `CMakeLists.txt` for this part too.

**Comment by josteink** [comment]
@janhenke Right. But the file failing is `./src/pal/src/exception/seh-unwind.cpp`. Isn't that part of PAL? Am I overlooking something stupid?

@kangaroo Is there any specific reason for not by default *always* including `/usr/local/include`? What harm could it do?

If possible, wouldn't it be better to include this folder in CMake at the top-level, rather than in specific submodules?

**Comment by kangaroo** [comment]
@josteink Its just "the way things are".  Traditionally /usr/lib || /usr/include was "system-safe" and "usr/local" was "your playground."  In my (shallow and frequently out of date) experience, its not included because it fucks up ports, unless explicily needed and dead.

Looking at the configure.make you referenced, I'm going to go out on a limb and guess your lldb is in /usr/include/lldb-something, which is insufficient for the check.  Use LLDB_INCLUDE_DIR like I said.  On OSD it was:

```
$: export LLDB_INCLUDE_DIR=/Users/plasma/Work/lldb/include/
```
Which is $(checkout)/include

**Comment by josteink** [comment]
Again: Excuse me if I'm missing something obvious, but I'm not working with LLDB here. I'm trying to get `seh-unwind.cpp` to compile.

For that to compile `libunwind.h` needs to be resolved. And that file is present in `/usr/local/include/`, which from what I [cmake is being told to include](https://github.com/dotnet/coreclr/blob/master/src/pal/src/configure.cmake#L10), which I expected to be passed to clang:

````cmake
if(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
  set(CMAKE_REQUIRED_INCLUDES "/usr/local/include" "/usr/include")
elseif(NOT CMAKE_SYSTEM_NAME STREQUAL Darwin)
  set(CMAKE_REQUIRED_DEFINITIONS "-D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200809L")
endif()
````

At what point does `LLDB` enter the picture?

**Comment by janvorli** [comment]
@josteink 
> The way I'm reading it the cmake-docs says that CMAKE_REQUIRED_INCLUDES is only used for CHECK_INCLUDE_FILE-statements.

Yes, that true. We have fixed the libunwind.h for its presence checking only before, now we need to add the /usr/local/include for the FreeBSD to the set of include folders for PAL build,
I recommend adding it to the src/pal/src/CMakeLists.txt conditionaly for the FreeBSD (use the include_directories command)

**Comment by josteink** [comment]
@janvorli Already done. See https://github.com/dotnet/coreclr/pull/655 :)

**Comment by janvorli** [comment]
@josteink Ah, I am sorry for missing that. I've just got back from my Easter vacation and I am catching up with my emails.

**Comment by josteink** [comment]
With those PRs merged, I'm closing this issue and consider it resolved. Thanks!
