### ISSUE TITLE
ARM64: [Question] ARMv8's load-aquire and store-release insructions

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#6260]
Does ARM64 codegen use  these new instructions for enforcing memory barriers? 
According to the docs they are  lighter than `DMB` and map to volatile operations almost directly.

http://www.realworldtech.com/arm64/5/
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/CJAIAJFI.html

**Comment by briansull** [comment]
We are currently using 

CodeGen::instGen_MemoryBarrier()
 getEmitter()->emitIns_BARR(INS_dmb, INS_BARRIER_SY);

 *     Note: all MemoryBarriers instructions can be removed by
 *           SET COMPlus_JitNoMemoryBarriers=1

**Comment by briansull** [comment]
In the Codegen for Arm64 we aren't currently doing anything for GTF_IND_VOLATILE or GTF_FLD_VOLATILE

**Comment by omariom** [comment]
> Note: all MemoryBarriers instructions can be removed by
SET COMPlus_JitNoMemoryBarriers=1

To find bugs related to incorrectly put barriers?

**Comment by briansull** [comment]
> To find bugs related to incorrectly put barriers?

No, more like measuring the cost in performance of the memory barriers.

**Comment by jkotas** [comment]
> In the Codegen for Arm64 we aren't currently doing anything for GTF_IND_VOLATILE or GTF_FLD_VOLATILE

@briansull Is it still the case? It looks like a bug to me. Volatile load/stores do need explicit barriers on arm64 - same as on arm.

**Comment by briansull** [comment]
Only the old codegenLegacy (on arm32) does anything with the  GTF_IND_VOLATILE or GTF_FLD_VOLATILE flags.

The newer RyuJit backend needs to be updated to generate  memory barriers for all architectures that need them. (Which are Arm32 and Arm64)

**Comment by briansull** [comment]
Opened issue #9711
