### ISSUE TITLE
RyuJIT: improve CQ for amd64 localloc with constant size and initialized memory

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#6261]
Primarily, this will commonize code with x86 and reduce #ifdefs, but will also improve amd64 CQ.

Related to #6251

**Comment by jamesqo** [comment]
+1, I think this was one of the reasons using a `uint` rather than `stackalloc char[2]` in #6141 proved to be a bit faster.

**Comment by BruceForstall** [comment]
This was done with
```
e8bdf3: Merge pull request #6276 from BruceForstall/LocAllocCleanup
```
