### ISSUE TITLE
AssemblyLoadContext: Provide isolation for dependencies of an assembly loaded in ALC

### ISSUE THREAD

**Issue by gokarnm** [dotnet/coreclr#6269]
I'm creating a custom AssemblyLoadContext in my application to load a plugin from a directory. The plugin can have additional dependencies on CoreFX or third party libraries. These dependencies can be same as my application's dependencies but the plugin may use a different version. A newer version of a CoreFX package could mean a patch version update in which case only the AssemblyInformationalVersion would be changed but the AssemblyVersion may remain the same. The plugin directory contains the plugin DLL and all its dependencies.

If the dependencies used by the plugin are already loaded into the default load context, the plugin also ends up using the same version as the application and not the version that the plugin provided. The Load method or Resolve event of the custom ALC is never called. The only way to have the plugin use the correct version of its dependencies is by calling the custom ALC's AssemblyLoadContext.LoadFromAssemblyName method and explicitly loading the dependency before it's automatically resolved. Also, I don't encounter the issue if the dependency is not referenced by the application therefore it's not loaded into default ALC.

I need to have copies of a dependency (same or different versions) loaded into default and custom ALC. Is there a way to provide isolation for an assembly loaded in a custom ALC (this works) and all it's dependencies (this doesn't work) irrespective of what's loaded in the default ALC? How can I intercept the resolution of a dependency of an assembly in an ALC, when the same dependency has been already loaded into the default ALC? I can provide a sample which replicates this issue if needed.

This is similar to the issue discussed in #6187 , I'm opening a new issue as this is not a feature request. I would like to know if this scenario is currently supported.

**Comment by jkotas** [comment]
> If the dependencies used by the plugin are already loaded into the default load context, the plugin also ends up using the same version as the application and not the version that the plugin provided. The Load method or Resolve event of the custom ALC is never called.

This looks like a bug. The Load method should be called in this case. 

cc @gkhanna79

**Comment by gkhanna79** [comment]
> I need to have copies of a dependency (same or different versions) loaded into default and custom ALC.

If the dependency version is different from what is loaded in DefaultContext, then the Load override for the custom ALC will be invoked. The scenario where it does not appear to work (i.e. return the version loaded in DefaultContext which is what you are seeing) is when the Assembly version is the one loaded in DefaultContext but not in the custom LoadContext.

> This looks like a bug. The Load method should be called in this case.

I suspect what is happening is that when a load is attempted, we first lookup the AppDomain wide cache for the assembly. If it is not found in the LoadContext where load is attempted, we fallback to TPA binder directly, bypassing the Load method.

I will take a look at this.

**Comment by gokarnm** [comment]
Thanks for the quick turnaround!! I'll test this and get back if I see any issues.
