### ISSUE TITLE
FreeBSD port-team need dedicated VMs

### ISSUE THREAD

**Issue by josteink** [dotnet/coreclr#629]
Currently we have:

* portteam.cloudapp.net (A2 FreeBSD azure instance)

We also need:

* portteam-eu.cloudapp.net (A2 FreeBSD azure instance, west-europe. Lower latency for EU developers)
* portteam-lldb.cloudapp.net (Temporary A3 FreeBSD azure instance, west-europe. **NO PORTING!** LLDB setup research only).

These instances are being set up by @ghuntley.

Additionally it would be nice to have OpenBSD and NetBSD VMs for patch interop-testing, but these are not supported OSes on Azure. @ajensenwaud is attempting to set up some images for these OSes and @phillipkent from Interroute is offering to host them.

For now (as far as I can tell) NetBSD is not really a supported build-target by coreclr at all, so priority should IMO be on the OpenBSD-image.

Opinions, anyone?

**Comment by ajensenwaud** [comment]
If anyone can provide even just a VM, i am happy to set up netbsd and OpenBSD infrastructure up. I have vms running on my own laptop atm, but permanent VMs in the cloud would be immensely helpful. Even a small instance. Thank you, Anders.

**Comment by phillipkent** [comment]
@ajensenwaud Hello Anders, in a couple of days I will set up a new account where you can create and manage VMs as you need them. If you contact me via email we can work this out in details. Thx Phillip.

**Comment by phillipkent** [comment]
Hello @ajensenwaud. The project account is up and running so please get in touch when you are ready to launch VMs.

**Comment by ajensenwaud** [comment]
Thank you, I am off on Easter break, will get in touch when I am back on Thursday. Cheers!

Anders Jensen-Waud

**Comment by ajensenwaud** [comment]
Hi Phillip

I am back from my break now. I am getting in touch via email now to proceed
with the setup.

Cheers

Anders

**Comment by josteink** [comment]
@ghuntley: Any news on the EU and LLDB instances?

**Comment by ajensenwaud** [comment]
Guys, I now have an OpenBSD machine running on Interoute VDC; it is working
very well.

The setup is quite beefy (12 vcpus and 32 GB RAM) -- let me know if you are
keen to help with setting up the build environment.

On Sat, Apr 11, 2015 at 7:34 PM, Jostein Kjønigsen <notifications@github.com

**Comment by janhenke** [comment]
How about adding the account with the SSH keys from the Volunteers needed issue?

**Comment by ajensenwaud** [comment]
Good idea, will do. 

Anders Jensen-Waud

**Comment by josteink** [comment]
@qbit Any chance of you helping out here?

This task here definitely seems to be the one which fits your interests and capabilities the most so far.

**Comment by josteink** [comment]
@ghuntley: Still around? No news on the instances in over two weeks time means I'm seriously reconsidering accepting the offer from Matt (.NET foundation) at this point.

**Comment by ajensenwaud** [comment]
Jostein we can set one up on Interoute where our OpenBSD is also running. Let me know what specific configuration we need and I will set it up (tonight).

Anders Jensen-Waud

**Comment by josteink** [comment]
A 4 core 4 GB instance in Europe for regular work, plus a separate and temporary 4 core 4 gb instance for lldb research will be plenty.

**Comment by qbit** [comment]
@josteink which task is this? Build machines?

There is some work going on to get llvm in a more up-to-date state. Apparently ours is a clobbering of older-than-3.5 and 3.5.

**Comment by josteink** [comment]
@qbit yeah. setting up openbsd build-machines. And potentially verifying if we are making headway there as well.

**Comment by qbit** [comment]
Ok, looks like the machine exists.  Is it running -current or a release? Running release will make things much much harder as most of the changes to the ports system that we will need are going to be in -current.

**Comment by phillipkent** [comment]
@josteink Hi all, Interoute VDC has zones in EU/USA/Asia regions and you are welcome to set up VMs in each region. I have explained to @ajensenwaud how to do this. We also have a nice feature (which you maybe don't need for this particular project) of integrated private VPN networking between zones (based on high-bandwidth private fibre network operated by Interoute, not Internet overlays). Keep it in mind for your next commercial projects ;-).

**Comment by ajensenwaud** [comment]
Jostein could you please send me your public ssh key. I have a FreeBSD 10.1 instance running in HK ready for us.

Anders Jensen-Waud

**Comment by josteink** [comment]
@ajensenwaud 

Note: I was asking for a **EU** instance because I was a bit annoyed by the latency of the US instance ghuntley setup on Azure. In that regard I'm not sure HK is going to be any better.

Anyway, if you already got an instance running, here's on SSH key and I can see how it works out:

````
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMaGl5KG5P6fogg5B5tY9K26X2rx0d7MZg7x28TYxICZGK1aHCODylNy3WfnBFvQ5hRsrf0kCT2u36JUmgJzXTBx6Vc3AchrEOMJLRl3KvJfsbpANrymkW666sDgQW6PyqXSZ8f17vREGZrvFa41/dwAxMvxlQELwS8HRgNzY8GoZBP9BTm6qqZFozBf25nZLN/p3/X3w3GxW4USJutnH5T2oBJc3TqVnBFSgrsnHMMlmV+Xj0EMBy4di+JoNBm78hCDwt1QVMJ+NDOH224LuWgTlhOIRRDZfNee3qGHOB1llI78BZkc4x/9SJR8Fiv13pUINHc1zfLBzmB1PPLztLS2j8kOTh/ymr3Gc5+8iGgPX9ZideNLoTjD9necwQ+GhPdys/DkU8idYkCJnVPv6il+OOwk55xopyyfs11660xlAxJKdNy8D3lbSBSQQCGMRKAXhXxUsQr1R64fScZ0NejmpXwYR+9vybymKbiMWizxYQ8ap/KxOAs3znPWYpu2mjldkHqKd0Wc5z4/pgZS/m2KVHr95oy1Lx/O77x6QSy9h7Wu1xIcayV5R+wIvfz6BhQ7Hpr2Lu2MHpNQr2T4UzIodfSJ/LWp/xo37Fl7Bg9SntEC4NepSW9FFSJ0q48/CfcTJYMvLTvqGYn85Y8PnlrKsr295RiRyMiD3Ys4RNtw== jostein@irssi
````

Worst case scenario, is it much work to create a new instance in EU or move this one?

**Comment by ajensenwaud** [comment]
Let's try. Otherwise I can quickly set up another one in EU.

Anders Jensen-Waud
+61 427 948 715

**Comment by josteink** [comment]
@ajensenwaud It seems like your replies by mail get cut off a little and I can't find details on the instance. What DNS name do I connect to? Is the user josteink as here on github?

**Comment by josteink** [comment]
@ajensenwaud I still don't know what the name or IP of the HK machine is.

**Comment by ajensenwaud** [comment]
It is on the way, I am setting it up in London as we speak so you don't get any network latency issues. Please give me a few hours!!

**Comment by ajensenwaud** [comment]
Hi Jostein,

Can you please use:

Host: freebsd-london.zbsd.org
User: josteink
Use your ssh key above to log on.

It has 12 cores and 32 GB of RAM, running in the Interoute London DC. I had
to install from the Interoute FreeBSD 10.0 base image and upgraded it to
10.1 overnight.

Thanks to Interoute for sponsoring this instance!

Others -- please let me know if you would like access.

On Sun, Apr 19, 2015 at 7:15 PM, Jostein Kjønigsen <notifications@github.com

**Comment by janhenke** [comment]
Hi @ajensenwaud I would also be interested in access to that machine if possible.

Key is the same as here: https://github.com/dotnet/coreclr/issues/455#issuecomment-83439951

Thanks to Interroute for the sponsoring of the BSD porting effort!

**Comment by ajensenwaud** [comment]
Hi Jan, I have set up you as well -- your username is
janhenke@freebsd-london.zbsd.org.

Cheers

Anders

**Comment by janhenke** [comment]
Thanks!

**Comment by josteink** [comment]
@ajensenwaud I don't think the key was added correctly, because I'm getting asked for password.

Is the permissions on the `.ssh`-folder and `authorized_keys`-file set correctly?

**Comment by ajensenwaud** [comment]
Jostein -- send me an email on Anders at jensenwaud dot com and we will sort it out.

Anders Jensen-Waud
+61 427 948 715

**Comment by josteink** [comment]
Thanks. Will do.

**Comment by ajensenwaud** [comment]
Hi all,

We have shifted the London instance to the Frankfurt data centre.
Jostein/Jan, please connect to freebsd-frankfurt.zbsd.org going forward
instead of freebsd-london.

Apologies for the outage.

If anyone else from the port team would like access, please le me know.

Anders

On Mon, Apr 20, 2015 at 4:09 PM, Jostein Kjønigsen <notifications@github.com

**Comment by josteink** [comment]
That works for me :+1:

**Comment by ajensenwaud** [comment]
Did your new account work?

Anders Jensen-Waud

**Comment by josteink** [comment]
No problem.

Emacs and clang installed, and build getting to that same almost but not quite 100%.

Like I said: looking good. :)

**Comment by janhenke** [comment]
Looks good here too.

**Comment by janhenke** [comment]
Hmm suddenly my shell is gone. I did not change anything, was just cloning my repository with git. Is there a kind of hang on the machine?

**Comment by josteink** [comment]
Yeah. Machine seems completely frozen for me as well now.

Emacs wont update/respond, in a open shell, I cant get "top" to load, and opening a new shell inside screen fails too.

It seems pretty hosed :)

**Comment by xied75** [comment]
Hi guys,

If it's the frankfurt VM we are talking about, it seems there are some attack going on from China. :)

I'll see how we block it from the VDC level.

**Comment by ajensenwaud** [comment]
Hi all,

I can't login either from the ESX web console either -- I can login in, but
login cannot hand off to tcsh and stalls.

This issue was the reason we migrated from the London DC to Frankfurt.

I will try and reboot the instance now and see if that helps.

**Comment by ajensenwaud** [comment]
ZFS had some extremely low vm kmem and arc size preinstalled by the FreeBSD
template. I have removed the low memory limits so ZFS allocates as much as
possible (the VM has 32 GB RAM so there should be plenty). I assume this is
what could have caused the kernel to hang. Let me know if the issue still
persists.

**Comment by ajensenwaud** [comment]
How's the Frankfurt VM running now after the adjustments?

Anders Jensen-Waud
+61 427 948 715

**Comment by janhenke** [comment]
Log in works again, but the disk is completely full.

**Comment by xied75** [comment]
Please add a new DATA disk and extend the ZFS partitions. We probably need to rebuild the template with bigger root.

Best,

Dong

**Comment by ajensenwaud** [comment]
the base template it came out of only had 10 GB (that was using the default
FreeBSD 10.0 install). I am rebuilding a new VM manually now and will
revert once it is set up.

**Comment by ajensenwaud** [comment]
Hi jostein / Jan, Can you please try logging in again -- I have rebuilt the
instance with a 100GB drive and more memory.

**Comment by josteink** [comment]
Next time (if) you (need to) rebuild it, you should consider not changing the host-keys.

Other than that, it works fine now, with insane amounts of memory available :)

**Comment by janhenke** [comment]
Thanks, seems to work nicely.

**Comment by ghuntley** [comment]
@josteink yep still around, have been awol due to moving house. Congratulations on getting the build working. ```portteam-lldb.cloudapp.net``` and ```portteam-eu.cloudapp.net``` have been running for the week, all SSH keys are installed. I see many more servers have been setup on Interoute - shall we call that home and eventually retire the ```portteam*``` series of servers? No rush.

**Comment by ajensenwaud** [comment]
I would say that Interoute is a good home for us as we do not have any
restrictions on specific OS'es as long as it runs on VMware (= OpenBSD and
NetBSD can run there as well). In addition, the Interoute infrastructure
has worked really well for us for FreeBSD as well. I am keen to continue
admin and support this for the FreeBSD Port Team in addition to porting the
code itself.

**Comment by josteink** [comment]
@ghuntley Oh? really? I guess I never checked, but expected you to announce when they were up. You know what they say about assumptions and mothers and such :)

That said, I think I agree with @ajensenwaud. Currently the Interroute machines have served us well, and they leave us room for testing on other BSDs should the time come for that to be 
interesting.

If you don't mind, I still think having the EU-instance around as backup would be nice. 

As for the LLDB-instance... Currently @ajensenwaud is conducting some work on LLDB (in [this issue](https://github.com/dotnet/coreclr/issues/797)), so I'm not sure if we still need the LLDB instance. Any opinions?

**Comment by ghuntley** [comment]
@josteink I'll keep mine up/running then as backup and the team can primarly use Interroute which due to being VMware based is perfect fit for NetBSD/OpenBSD + there has been some enquiries about  Solaris derivatives in the future.

@ajensenwaud can you please create an account for @kangaroo  / Geoff Norton.

    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+/V9QIR/V81lACsLDh6NLcPZl/kAoV2ZWD2Re9rYlJSy8kpXizH/Q67yKOi78gB2qeEHuMtBpjoWOK3zmJLmnxGdMiwtrkPIuUNKHgfsqiFCjunFKkdZgxgVChuFd/SupgfFBRBBrDmsvOqyZNUAMKjukW5U7taI0JS2643CxlPIPojTvDhn13t+XVAuzbBkSF1+gSHT23Zxjw8u3kSitU7uKaosLbthwvSpCvCIDB4nl0Ns+m/NeJ2or/dmj3C6zbQ56TuaUNVsLPcrl2IDP3glbqbz6PpA91MdYSI453KE/1NcUjpF6at7VjKd9AjCc3DIHI73xHBjA9Fsf6cBd

**Comment by ajensenwaud** [comment]
Sure, will do!

Anders Jensen-Waud

**Comment by ajensenwaud** [comment]
@kangaroo has now been added to freebsd-frankfurt.zbsd.org with username
``kangaroo'' and the above SSH key. Geoff, can you please let me know if
this works?

**Comment by josteink** [comment]
I think this one has been achieved and can be considered done by now.

Other bsds can have their own issues where their progress is tracked individually.

Sounds OK? Any objections?
