### ISSUE TITLE
WaitForMultipleObjectsEx in PAL doesn't verify no duplicate named objects

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#630]
WaitForMultipleObjectsEx is documented to fail if the same object is provided multiple times, and a System.Runtime test is verifying this behavior with named objects as the .NET WaitHandle equivalent function provides the same guarantee, but the PAL implementation doesn't do this verification.

**Comment by kouvel** [comment]
I'll check if we're doing this properly for unnamed sync objects
