### ISSUE TITLE
Build fails on 32bit Windows 10

### ISSUE THREAD

**Issue by mazong1123** [dotnet/coreclr#6308]
I ran below command to build the coreclr from source on 32bit Windows 10:
build clean x86

After stuck in "Installing dotnet cli..." for 5 mins, I got following error:
dotnet.exe is not compatible with current running Windows version.

So is build coreclr from source supported on Windows 10?

**Comment by jkotas** [comment]
The dotnet.exe is hardcode to x64 in https://github.com/dotnet/coreclr/blob/master/init-tools.cmd#L47. To fix this, we would need to detect that we are running on 32bit windows (e.g. using `PROCESSOR_ARCHITECTURE` env variable), and switch to x86 version instead.

Variants of `init-tools.cmd` script is used in multiple dotnet repos, so the change would need to be ported to all of them to make dotnet buildable on 32-bit Windows machines.

**Comment by mazong1123** [comment]
I'll work on this. I'd like to send a PR for this repo first.
