### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by essial** [dotnet/coreclr#6309]
When compiling my asp.net core website using dotnet build, it works on windows, but in linux it simply says:
The given key was not present in the dictionary.

This error does NOT show if I remove this from the project.json:
"preserveCompilationContext": true,

But this line is ~required~ for MVC views to work properly; by ommiting that line it builds and runs, but asp.net core barfs. I'm completely stuck right now.

I'm using dotnet version 1.0.0-preview2-003121. I've tried the latest build as well but not only do I get the same error, omnisharp does not work in VSCode at all, so I dropped back to the 3121 build.

[project.json.txt](https://github.com/dotnet/coreclr/files/367960/project.json.txt)

**Comment by jkotas** [comment]
Could you please open this issue in dotnet/cli instead? It is not a bug in CoreCLR.
