### ISSUE TITLE
Self-contained application not working on Mac because of openssl

### ISSUE THREAD

**Issue by bluemmc** [dotnet/coreclr#6312]
The docs state that it is possible to deploy a self-contained application via xcopy because there are no external dependencies but on Mac OS X this is not true. The Mac version requires a non-standard version of openssl that Apple does not support to be installed globally. This openssl version should be a part of dot net core files if needed.

**Comment by jkotas** [comment]
Could you please open this issue in dotnet/corefx repo instead?
