### ISSUE TITLE
Breaking out of multiple loops

### ISSUE THREAD

**Issue by tomspilman** [dotnet/coreclr#6319]
A fairly minor annoyance...  but sometimes you end up with code like this:
```
void function()
{
   foreach ()
   {
      bool stop = false;
      foreach ()
      {
          if (condition)
          {
             stop = true;
             break;
          }
      }
      if (stop)
         break;
   }
   // Do some final work.
}
```
Often suggestions are to use a temporary like this or split this into two different functions.

It would be nice if you could just call break more than once in a single statement to jump out of nested loops:
```
void function()
{
   foreach ()
   {
      foreach ()
      {
          if (condition)
             break break;
      }
   }
   // Do some final work.
}
```
Specifying one too many `break` statements would cause a syntax error at compile time.

**Comment by mikedn** [comment]
Looks like a language issue so it should be in the Roslyn repository.

**Comment by tomspilman** [comment]
Thanks @mikedn ...  I moved this there.  https://github.com/dotnet/roslyn/issues/12583
