### ISSUE TITLE
Failure in ARM emulator CI - umount: /opt/linux-arm-emulator-root/dev: device is busy.

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#6329]
@prajwal-aithal this is to cover the issue mentioned in #6310.

The emulator failures seem to have happened in #6177 also.

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/arm_emulator_cross_debug_ubuntu_prtest/559/console
00:01:27.252 + sudo umount /opt/linux-arm-emulator-root/dev
00:01:27.260 umount: /opt/linux-arm-emulator-root/dev: device is busy.
00:01:27.260 (In some cases useful info about processes that use
00:01:27.260 the device is found by lsof(8) or fuser(1))
00:01:27.265 Build step 'Execute shell' marked build as failure

**Comment by prajwal-aithal** [comment]
@danmosemsft As observed before, this error has become regular in both coreclr and corefx. This error does not appear in our local testing.

@sjsinju is handling the ARM CI checks, and he will disable the Emulator checks until we figure out what is going wrong.

**Comment by danmosemsft** [comment]
Yes, that's fine -- I simply opened  this issue so that others have an ID # to track. thanks!

**Comment by danmosemsft** [comment]
I gues this was fixed by the commit  above.
