### ISSUE TITLE
Dependencies of 'mscorlib.dll' 

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#6333]
While investigating dependencies between DLL(s), I found that mscorlib.dll depends on those three DLL(s):
```
$ ls mscorlib.dll | mono-find-requires
mono(System.Private.CoreLib) = 4.0.0.0
mono(System.Security.Claims) = 4.0.0.0
mono(System.Security.Cryptography.Primitives) = 4.0.0.0
```
It is a bit strange that mscorlib.dll depends on the DLL in CoreFX. Is it intended?

**Comment by jkotas** [comment]
We have moved the implementation of the core runtime to `System.Private/CoreLib`. `mscorlib` does not contain any code anymore. It is facade that forwards the implementation to where it actually lives. We will be adding more of these forwarders as part of https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/, so you will see a mscorlib to depend on a lot more other assemblies in near future.

**Comment by parjong** [comment]
@jkotas Thanks for your kind answer. Then, does it mean that System.Private.CorLib.dll will be the only library that CoreCLR provides, and mscorlib.dll will be moved into CoreFX eventually?

**Comment by jkotas** [comment]
Yes. In fact, it is being worked on in the dev/api branch in corefx (https://github.com/dotnet/corefx/tree/dev/api/src/mscorlib).

**Comment by parjong** [comment]
@jkotas Thanks! I understood how it is going on 👍

**Comment by parjong** [comment]
@jkotas May I close this issue? If you don't mind, I want to close this.
