### ISSUE TITLE
Decide on separate nuget package for cross-target tools/components

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#6341]
Currently all cross components binaries are being published in coreclr runtime package. They need not be as they are only required on build machines and during development. They are not required at runtime. Should they be published together in a separate nuget package that also includes clrjit.dll

**Comment by kasper3** [comment]
Decided and fixed https://github.com/dotnet/core-setup/issues/3987
@sdmaclea, @eerhardt

**Comment by BruceForstall** [comment]
@eerhardt Can this issue be closed?

**Comment by eerhardt** [comment]
I'm not sure on exactly what @rahku had in mind.  It looks like he wanted separate packages, but today we are putting them together, I believe.

@rahku ?

**Comment by BruceForstall** [comment]
@eerhardt Note that @rahku stopped working on coreclr long ago, so don't expect an answer.
