### ISSUE TITLE
Buffer.MemoryCopy: P/Invoke can be unnecessarily called for small buffers

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#6345]
`Buffer.MemoryCopy` has [this segment](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Buffer.cs#L273-L279) of code that (supposedly from what the comment says) is intended to 'check if the buffers overlap' and fallback to the P/Invoke version if so:

```cs
// P/Invoke into the native version when the buffers are overlapping and the copy needs to be performed backwards
// This check can produce false positives for lengths greater than Int32.MaxInt. It is fine because we want to use PInvoke path for the large lengths anyway.

#if BIT64
    if ((ulong)dest - (ulong)src < len) goto PInvoke;
#else
    if (((uint)dest - (uint)src) < len) goto PInvoke;
#endif
```

However, it appears to me that if `dest` is at a lower memory address than `src`, then the unsigned subtraction will overflow even when the buffers don't overlap, and report false unless `len` is somehow very large. Therefore, we may be actually making a lot of unnecessary P/Invoke calls for small buffers when the address of `dest` < the address of `src`.

Note that this also affects many common String operations, since many of them call `wstrcpy` (e.g. [Substring](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L1326)) which [forwards to Buffer](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L1581) for the implementation.

cc @jkotas

**Comment by jkotas** [comment]
Yes, the unsigned subtraction will overflow, the result will be really big number, and the condition will be false. Unless len is also a really big number - in which case we want to use PInvoke implementation as well.

**Comment by jkotas** [comment]
If you believe there is a real problem, build a repro for it...
