### ISSUE TITLE
Question: Does pinning a string array also pin its elements?

### ISSUE THREAD

**Issue by roterdam** [dotnet/coreclr#6351]
```csharp
string[] strings = new strings[10];
GCHandle.Alloc(strings, GCHandleType.Pinned);
```

Is it possible to now take address of each element of string array? Or is pinning only for array and not individual elements?

**Comment by redknightlois** [comment]
AFAIK pinning will only pin the array. You have to pin the strings themselves if you need to do pointer arithmetics on them.

**Comment by swgillespie** [comment]
Yes, @redknightlois is correct, only the array will be pinned. The GC will be free to relocate any of the strings in that array, since being referenced by a pinned object does not cause the referent to be pinned.

**Comment by roterdam** [comment]
Thank you.
