### ISSUE TITLE
Marshal.SizeOf<T> wont work if the struct is enclosed in a generic type even if size is not dependent on it

### ISSUE THREAD

**Issue by redknightlois** [dotnet/coreclr#6352]
Probably I am missing something and that is the reason why it fails, but this is the example:

``` csharp
public class C<T>
{
   public struct S 
   { 
        public int I 
   };

   public C () { Marshal.SizeOf<S>() };
}
```

While this wont:

``` csharp
public struct S { public int I };

public class C<T>
{ 
   public C () { Marshal.SizeOf<S>() };
}
```

Even though the size of `S` is independent from `T`. It looks as if it is checking against `C<T>` instead of `S`

Probably another edge case is this one:

``` csharp
public struct S<T> where T : struct
{ 
   public int I;
   public T Value { get { return (T)(object) I; } }
};
```

I know I am abusing the language, but the JIT will generate a very specific assembler for this :)

**Comment by mikedn** [comment]
> Even though the size of S is independent from T. It looks as if it is checking against C<T> instead of S

Even if S doesn't use `T` it's still considered to be a generic type. As in `Console.WriteLine(typeof(C<>.S).IsGenericType)` prints `true` and `Console.WriteLine(typeof(C<string>.S) == typeof(C<int>.S))` prints `false`.

I suppose `Marshal.SizeOf` could be more relaxed and reject only those types where the layout really depends on a `T`. But do you really need `Marshal.SizeOf`? I've seen plenty of cases where it incorrectly used in code that has nothing to do with marshaling. Perhaps you should be using `Unsafe.SizeOf` which works fine in your case.

> Probably another edge case is this one

What's up with that one?

**Comment by redknightlois** [comment]
I didnt know that ```Unsafe.SizeOf``` would work. Either way based on what I am seeing the problem itself is that structs which have a generic method are not considered ```struct``` anymore regarding most of the conversion rules. 

For example, say I have this: 

```
struct node
{
     public int Base;
     public int Check;
}

struct CedarNode
{
     public int Base;
     public int Check;
     public T Value { get{ return (T)(object)Base; } 
}
```
From the storage point of view this two are exchangeable, but they are not, it is impossible to do a cast from one to the other (using the general language rules). Probably ```Unsafe.As``` and ```Unsafe.AsRef``` would work for that though (I will try). 

About the edge case, well... that is a union of a generic primitive type :)

**Comment by mikedn** [comment]
> Either way based on what I am seeing the problem itself is that structs which have a generic method are not considered struct anymore regarding most of the conversion rules.

Well, they're different types. As in the above mentioned `Console.WriteLine(typeof(C<string>.S) == typeof(C<int>.S))` prints false.

> Probably Unsafe.As and Unsafe.AsRef would work for that though (I will try). 

Yep, those should work. Arguably this is exactly what they are for, allowing different types with identical layouts to be used interchangeably.

> About the edge case, well... that is a union of a generic primitive type :)

I don't see anything that looks like an union. But the main question was what that example has to do with the issue. Were you trying to use `Marshal.SizeOf` on it? Then `Unsafe.SizeOf` should work just fine on that type as well. More generally, if you don't marshal stuff don't bother with `Marshal.SizeOf`.

**Comment by redknightlois** [comment]
Tried, the problem is still that you cannot cast (even with ```Unsafe.Read```) to an struct that has a type parameter even if it's size is independent of it.

**Comment by mikedn** [comment]
Well, show an example that uses `Unsafe.Read` and doesn't do what you need. Maybe someone can help.

**Comment by jkotas** [comment]
I agree - `Unsafe.Read` should work for this.

**Comment by redknightlois** [comment]
@jkotas My bad it works, I tried to get the reference for it (which cannot be done) instead of copy it to the stack. Later when I am done I will profile to see what is better (if using ```Unsafe.Read``` or just go straight for:

```csharp
private T GetNodeValue(node* n)
{
    return (T)(object)n->Base;
}

private void SetNodeValue(node* n, T value)
{
    n->Base = (int)(object)value;
}
```

**Comment by gkhanna79** [comment]
@redknightlois Can this issue be closed?

**Comment by redknightlois** [comment]
Unsafe is a workaround.
