### ISSUE TITLE
jitOverview.doc

### ISSUE THREAD

**Issue by cheers00** [dotnet/coreclr#636]
Wondering if there is any plan to opensource jitOverview.doc on github. 

At jit\compiler.cpp, the following comment refers to jitOverview.doc but I can not find it.

```
// This is the most interesting 'toplevel' function in the JIT.  It goes through the operations of
// importing, morphing, optimizations and code generation.  This is called from the EE through the
// code:CILJit::compileMethod function.  
// 
// See the document jitOverview.doc file in this directory for an overview of the structure of the JIT. 
//  
```

**Comment by MattWhilden** [comment]
@richlander @terrajobst Any ideas?

**Comment by cmckinsey** [comment]
That document in its current form is quite out of date and would probably be just as misleading as helpful. We have been working on a replacement/update of that document specifically to share here on github. Its in review right now for accuracy and should be available soon.
