### ISSUE TITLE
Just-In-Time debugger does not work for .Net Core

### ISSUE THREAD

**Issue by svick** [dotnet/coreclr#6380]
When I create a .Net Core 1.0 RTM application that crashes and run it on Windows 10 with .NET Core Tooling Preview 2 for VS2015 installed, the Just-In-Time debugger window is shown, but trying to use it does not let me debug the .Net Core application.

This might be related to #6381.
1. `dotnet new`
2. Change Program.cs to `throw new Exception();`.
3. `dotnet restore`, `dotnet run`.
4. Start JIT debugging, don't check "Manually choose the debugging engines":
   
   ![JIT debugger](http://imgur.com/UujbhWl.png)
5. No useful information:
   
   ![Unhadled exception dialog](http://imgur.com/q4cgX3O.png) ![Call Stack window](http://imgur.com/HiECZUS.png)
6. Try again, this time check "Manually choose the debugging engines".
7. Both "Managed (CoreCLR)" and "Native" are selected, leave it as it is:
   
   ![Attach to Process dialog](http://imgur.com/rHKApA1.png)
8. Fails to attach to process, error message says that interop debugging is not supported:
   
   ![Error message when trying to attach to process](http://imgur.com/4lFW0h9.png)
9. Try again, this time try to uncheck "Native". Not possible, apparently "Native" is required for the current exception:
   
   ![Error message when trying to uncheck "Native"](http://imgur.com/T5NxYdE.png)

Is this expected to work now? Can I expect it to work in the future?

(This was originally reported in https://github.com/dotnet/core/issues/121.)

**Comment by svick** [comment]
cc: @gregg-miskelly

**Comment by gregg-miskelly** [comment]
This feature requires work on the VS Debugger side and coreclr. I added a tracking item for the VS side.

cc @caslan @qubitron

**Comment by lt72** [comment]
@mikem8361 : this seems related to #12074

**Comment by gregg-miskelly** [comment]
Personally I think we should merge the two issues together.

**Comment by mikem8361** [comment]
Closing since we have #12074.

**Comment by mikem8361** [comment]
Done.
