### ISSUE TITLE
Cannot parse custom date string using ParseExact

### ISSUE THREAD

**Issue by internetbird** [dotnet/coreclr#6382]
I encounterd this question on StackOverflow :
 http://stackoverflow.com/questions/38502540/cannot-parse-custom-date-string-using-parseexact

For some reason ParseExact can parse the following:

`DateTime.TryParseExact("3 04 05", "M dd yy", CultureInfo.InvariantCulture, DateTimeStyles.None, out date);`

But cannot parse:

`DateTime.TryParseExact("30405", "Mddyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out date);`

Why is that?

**Comment by jasonwilliams200OK** [comment]
Use `03` instead of `3` for month, as narrow specifier `M` without separator gets confused and apparently there is no better way to go about it. This behavior is consistent with full framework (for example, .NET Framework 4.5). See `Note` at https://msdn.microsoft.com/en-us/library/w2sa9yss(v=vs.110).aspx#Anchor_2:

> If *format* is a custom format pattern that does not include date or time separators (such as "yyyyMMddHHmm"), use the invariant culture for the *provider* parameter and the widest form of each custom format specifier. For example, if you want to specify hours in the format pattern, specify the wider form, "HH", instead of the narrower form, "H".

Instead of `TryParseExact`, use `ParseExact` to unveil the actual exception:

```c#
DateTime.ParseExact("3 04 05", "M dd yy", CultureInfo.InvariantCulture, DateTimeStyles.None);

// 3/4/2005 12:00:00 AM

DateTime.ParseExact("30405", "Mddyy", CultureInfo.InvariantCulture, DateTimeStyles.None);

// Unhandled Exception: System.FormatException: String was not recognized as a valid DateTime.
//   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)

DateTime.ParseExact("030405", "Mddyy", CultureInfo.InvariantCulture, DateTimeStyles.None);

// 3/4/2005 12:00:00 AM
```

**Comment by gkhanna79** [comment]
@internetbird Does the above answer your question and can this be closed?

CC @danmosemsft

**Comment by internetbird** [comment]
@gkhanna79  Yes. It can be closed. Thanks.
