### ISSUE TITLE
Make 3rd party notice addition for #6125

### ISSUE THREAD

**Issue by richlander** [dotnet/coreclr#6390]
Looks like we missed adding an entry to the 3PN file for #6125

/cc @martinwoodward

**Comment by jkotas** [comment]
The code snippet in the final version of this PR came from: https://graphics.stanford.edu/~seander/bithacks.html#ZeroInWord . It is declared as public domain.

This particular page is pretty popular to copy from. We have been doing it before, e.g. here:
https://github.com/dotnet/corefx/blob/master/src/System.Buffers/tests/ArrayPool/UnitTests.cs#L283.

**Comment by jkotas** [comment]
#6430

**Comment by martinwoodward** [comment]
Thanks @jkotas - all good. While we don't have to add attribution - I'll do a quick PR to put something in the 3rd Party Notices file to give kudos to Sean Eron Anderson as it's very cool stuff.
