### ISSUE TITLE
[Win 7] Cannot target windows 7 32bit runtime

### ISSUE THREAD

**Issue by ameno-** [dotnet/coreclr#6391]
Cannot target windows 7 32bit runtime in .NET core console application.
My project.json
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },
  "runtimes": {
    "win7-x32": {},
    //"win7-x64": {},
    //"win10-x64": {}
  }
}
```

[Supported architectures](https://github.com/dotnet/core/blob/master/roadmap.md)

**Comment by ameno-** [comment]
Targeting `win7-x86`  does not work either

**Comment by jkotas** [comment]
I guess you are missing the runtime argument for dotnet publish: `dotnet publish --runtime win7-x86`

This is discussed in: http://stackoverflow.com/questions/38235488/asp-net-core-1-how-change-the-target-runtime-to-x86/
