### ISSUE TITLE
Possible timer drift

### ISSUE THREAD

**Issue by jnm2** [dotnet/coreclr#6408]
Because `timerInfo->FiringTime` is set to `currentTime + timerInfo->Period` instead of `timerInfo->FiringTime + timerInfo->Period`, drift could happen when `currentTime` and `timerInfo->FiringTime` are different. What could cause them to be different? The [thread sleep](https://github.com/dotnet/coreclr/blob/726d1a3244b80bf963fd0d51e57d4bb90af1e426/src/vm/win32threadpool.cpp#L5011) might not get back exactly at the requested `nextFiringInterval`.

This means that `FireTimers` runs when one timer is expired, but potentially a little later. It runs at time `timerInfo->FiringTime + sleepDelta` where `sleepDelta` is the amount of time later than planned that it is scheduled and runs due to the previous thread sleep. At time `timerInfo->FiringTime + sleepDelta`, `currentTime = GetTickCount()` is taken. That means `currentTime = timerInfo->FiringTime + sleepDelta`. Then **each** time the timer does fire, `timerInfo->FiringTime = currentTime+timerInfo->Period`; substituting currentTime, `timerInfo->FiringTime = timerInfo->FiringTime + sleepDelta + timerInfo->Period`.

It would be nice if the timer itself was rock-solid. I'm curious why the team didn't go with `timerInfo->FiringTime += timerInfo->Period`.

Here it seems that `SleepEx` is expected to be within 150 ms or 10% for longer intervals: [test1.c](https://github.com/dotnet/coreclr/blob/726d1a3244b80bf963fd0d51e57d4bb90af1e426/src/pal/tests/palsuite/threading/SleepEx/test1/test1.c#L70) That doesn't make me feel better about the delay between the timer's planned expiry time and executing `currentTime = GetTickCount()`. I don't want my timers to be expected to drift up to 150 ms or 10% of the interval on every tick.

Thanks!

**Comment by jkotas** [comment]
cc @ericeil

**Comment by ericeil** [comment]
cc @kouvel

**Comment by kouvel** [comment]
System.Threading.Timer registers the native app domain timer it creates as a non-repeating timer. However, Timer.FireNextTimers in Timer.cs also has the same issue, and both should be fixed.

**Comment by jnm2** [comment]
I see this is labeled as a 2.0 bug and the deadline is getting closer. Is it still possible for me to submit a PR to fix this?

**Comment by kouvel** [comment]
I'm planning on fixing it soon for 2.0.

**Comment by jnm2** [comment]
@ayende Hey, remember this conversation?

**Comment by ayende** [comment]
@jnm2 Context?

**Comment by jnm2** [comment]
https://ayende.com/blog/174850/how-timers-works-in-the-clr comments.

**Comment by ayende** [comment]
Looks good

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
