### ISSUE TITLE
Cannot find source [build.sh]

### ISSUE THREAD

**Issue by yorickdewid** [dotnet/coreclr#6409]
As reported earlier in #4558 CMake fails due to a missing source file in the objects folder. This is not related to ARM and seems to occur on Debian 8.5.

```
CMake Error at functions.cmake:174 (add_library):
  Cannot find source file:

    /coreclr/bin/obj/Linux.x64.Debug/version.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  src/corefx/System.Globalization.Native/CMakeLists.txt:55 (_add_library)


-- Build files have been written to: /coreclr/bin/obj/Linux.x64.Debug
```

This is possible related to the MSbuild.exe error shown before the failure.

**Comment by janvorli** [comment]
The version.cpp is generated by managed code right before building native code. If that fails, it would lead to this error. I don't know why it fails in your case, but a workaround is to pass `skipgenerateversion` argument to the build.sh.

**Comment by yorickdewid** [comment]
I've cloned the source, installed the dependencies and then ran the build script. Workaround is good enough for now but it doesn't fix the bug (if any). I'll see if I can reproduce the error on an other machine.

**Comment by janvorli** [comment]
Can you see any error message from the phase that generates the version.cpp? This is the piece of code that's reponsible for that:
https://github.com/dotnet/coreclr/blob/master/build.sh#L178-L185
Maybe you can try to pass in the `verbose` option and see if it dumps some useful details on the problem.

**Comment by yorickdewid** [comment]
Verbose doesn't do much. I believe the version generation part reports this:

**Comment by janvorli** [comment]
Then the init_tools.sh failed and the culprit should be visible in init-tools.log in the root folder of the coreclr repo.

**Comment by yorickdewid** [comment]
Somehow not the entire NuGet package was downloaded into Tools/ but since the package.json existed the init-tools.sh skipped over the download operation resulting in this error. Working now :+1:
