### ISSUE TITLE
CoreCLR CreateDelegate

### ISSUE THREAD

**Issue by matiasinsaurralde** [dotnet/coreclr#6421]
Hi, my program is crashing when using ```coreclr_create_delegate```, I'm using .NET Core 1.0.0 (from the git tag), I've read that it could be related to the delegate function, I've tried many things but no luck.
I'm loading ```coreclr_create_delegate``` with dlsym and I'm sure this is fine, then ```_CreateDelegate``` is called and the program crashes there, any tip or idea about this?

My implementation is pretty much the same as [Edge](https://github.com/tjanczuk/edge/blob/24d147c3152a8be5f5cd6ae5b368747be420b0f5/src/CoreCLREmbedding/coreclrembedding.cpp#L56), with a different assembly name of course.

```
#define CREATE_DELEGATE(functionName, functionPointer)\
	result = createDelegate(\
			hostHandle,\
			appDomainId,\
			"EdgeJs",\
			"CoreCLREmbedding",\
			functionName,\
			(void**) functionPointer);\
	pal::clr_palstring(functionName, &functionNameString);\
	\
	if (FAILED(result))\
	{\
		throwV8Exception("Call to coreclr_create_delegate() for %s failed with a return code of 0x%x.", functionNameString.c_str(), result);\
		return result;\
	}\
	\
	trace::info(_X("CoreClrEmbedding::Initialize - CoreCLREmbedding.%s() loaded successfully"), functionNameString.c_str());\
```

Under some situations I've been getting ```0x80131022 / HOST_E_INVALIDOPERATION```.

Thanks

**Comment by jkotas** [comment]
This error means that the hosting APIs are called in bad sequence, e.g. calling initialize twice or not calling it at all.

**Comment by matiasinsaurralde** [comment]
I've got it working, the order seemed to be fine, however I my delegate "wrapper" function was wrong.
Thank you
