### ISSUE TITLE
Buffer.BlockSet (memset for .NET) like Buffer.BlockCopy is memcpy for .NET

### ISSUE THREAD

**Issue by elisee** [dotnet/coreclr#6439]
Hi! This is a quick proposal for a new function for fast raw initialization of memory.

`Buffer.BlockCopy` provides an equivalent to `memcpy` for fast raw copy. A `Buffer.BlockSet` function (to mirror `memset`) for fast raw initialization would be useful, especially for gamedev where we work with a lot of arrays with primitive types (vertex data, level data, etc.)

It seems to be currently possible using [dynamic IL generation tricks](http://stackoverflow.com/a/25808955/915914) and the `InitBlk` opcode but having it built-in would be very nice.

**Comment by mikedn** [comment]
Presumably you want to be able to fill arrays with values other than zero? Otherwise you could simply use Array.Clear.

**Comment by elisee** [comment]
Yeah, non-zero values. A  use case might be 4-byte patterns too. Not sure if something like OS X's [`memset_pattern*`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/memset_pattern4.3.html) are available on all OSes.

**Comment by jamesqo** [comment]
+1 for this. I made a similar proposal a couple of months ago-- dotnet/corefx#6710-- except for an unsafe `void*`-based overload. Maybe we could name it `Buffer.FillBlock` and name the other method `FillMemory`-- which conveys the meaning better (and sounds more natural) than `BlockSet` or `MemorySet` for people who aren't familiar with C.

**Comment by elisee** [comment]
> Maybe we could name it `Buffer.FillBlock`

Not that naming is the hard part here, but `Buffer.BlockFill` would probably be best to be consistent with `Buffer.BlockCopy`.

**Comment by redknightlois** [comment]
+1 on this too. We are using unmanaged one for posix and win32 alike. Would be great to have a single one. Also the version of ```FillBlock``` with a buffer size of ```n``` (kinda repeat).

**Comment by jamesqo** [comment]
I'm not sure why I didn't mention this earlier, however the `Unsafe.InitBlock` method that was added with dotnet/coreclr#7966 seems to fit the needs here-- it's just a wrapper around the `initblk` opcode that lets you initialize memory to a single value. So perhaps adding another `BlockFill` / `BlockSet` method would be redundant.

**Comment by gkhanna79** [comment]
CC @danmosemsft

**Comment by karelz** [comment]
If you are still interested in the API, please create a new issue in https://github.com/dotnet/corefx, ideally with [formal API proposal](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md)
