### ISSUE TITLE
Make Profiling doc available on BOTR

### ISSUE THREAD

**Issue by hmemcpy** [dotnet/coreclr#644]
http://devdiv/sites/CLR/ProfilingAPI/Shared%20Documents/ImplementingProfilability.doc

Thanks!

**Comment by MattWhilden** [comment]
@hmemcpy Thanks for letting us know your interested. It helps us prioritize getting these doc into a cleaned up state and put out on github.

@richlander will probably be able to comment better about the state of that effort overall and @noahfalk could potentially field specific questions in the mean time.

**Comment by hmemcpy** [comment]
Thank you, really appreciate it!

**Comment by richlander** [comment]
Here: https://github.com/dotnet/coreclr/blob/master/Documentation/profilability.md
