### ISSUE TITLE
IEnumerator<T> should not inherit IDisposable

### ISSUE THREAD

**Issue by stas-sultanov** [dotnet/coreclr#645]
I would like to suggest to make interface `IEnumerator<T>` to not implement `IDisposable`.

i've looked in [Sources](http://referencesource.microsoft.com/#mscorlib/system/collections/generic/ienumerator.cs,893e8cdebffde2da,references) and found that almost all types in .NET that implements `IEnumerator<T>` has no unmanaged resources to dispose. Actually there are some implementations of `IDisposable`, but they looks like a [useless code](http://referencesource.microsoft.com/#mscorlib/system/charenumerator.cs,115aa972d94acf7f,references).

According to my own experience, i can not find any example of type that implements `IEnumerator<T>` and has unmanaged resources to dispose.

**Comment by MattWhilden** [comment]
Thanks for your interest in the project.

However, removing this interface is a breaking change. Consider the code below. Removing IDisposable will cause the compiler to kick out this error:
Error	1	'ConsoleApplication5.IFoo' does not contain a definition for 'Dispose' and no extension method 'Dispose' accepting a first argument of type 'ConsoleApplication5.IFoo' could be found (are you missing a using directive or an assembly reference?)	c:\users\mwhilden\documents\visual studio 2013\Projects\ConsoleApplication5\ConsoleApplication5\Program.cs	21	17	ConsoleApplication5

```csharp
    static class AwesomeFooManipulator
    {
        static void FooMethod(IFoo foo)
        {
            foo.Dispose();
        }
    }

    interface IFoo //: IDisposable
    {
        void Bar();
    }

    class Foo : IFoo
    {
        public void Bar()
        {
            
        }

        public void Dispose()
        {
            
        }
    }
```

**Comment by Maxwe11** [comment]
>I would like to suggest to make interface IEnumerator<T> to not implement IDisposable.

What benefits it will bring? Perf issue of calling empty `Dispose` could be resolved (or maybe it's already resolved :smile:) on JIT level.

>According to my own experience, i can not find any example of type that implements IEnumerator<T> and has unmanaged resources to dispose.

Take a look closer e.g. in FileSystem API

**Comment by mburbea** [comment]
While you don't see a need there are plenty of usecases.
```csharp
using(var conn = new SqlConnection(...)){
using(var cmd = new SqlCommand(...)){
using(var datareader = cmd.ExecuteReader(...)){
using(var myReader = new StreamReader(datareader.getStream(0)){
     while(!eof)
      yield myReader.ReadLine();
```

Doing this is a useful pattern as it allows you to tie lifecycle to iteration.

**Comment by mmdriley** [comment]
In addition to the great points raised above, iterator blocks (C# functions that use "yield return" and return IEnumerator<T>) rely on IEnumerator<T>.Dispose() to invoke any code in the finally {} block that wraps the most recent "yield return".

See v5 of the C# spec, §10.14.4.3.

**Comment by stas-sultanov** [comment]
> See v5 of the C# spec, §10.14.4.3.

well yeah, it explains much. my bad.

however i believe that in case of `yield` enumerator it could be much better solution to generate a class that explicitly inherits from `IDisposable` and does all the stuff described in the spec.

If we will take a look at [CharEnumerator](http://referencesource.microsoft.com/#mscorlib/system/charenumerator.cs,0969ce79660adf73,references), [IdentityReferenceEnumerator](http://referencesource.microsoft.com/#mscorlib/system/security/principal/ircollection.cs,b4b50e30d9daadeb,references) we will see that this types explicitly inherits `IDisposable`.

If `IEnumerator<T>` implements `IDisposable` it is not clear to understand why `IEnumerator` does not inherit `IDisposable`. The oblivious reason is only `yield` enumerator.

Considering all above it makes coreclr to look like inconsistent and not well designed. :(

**Comment by MattWhilden** [comment]
We've certainly made cuts such that code that used to run on Full Framework doesn't work on CoreCLR (see appdomains etc). However, we still want most code to be able to run "out of the box". This mean that changes like this will not be merged.

If someone wishes to start a fork with a less cautious approach, then there'd be a huge number of things they could go tackle. :-)
