### ISSUE TITLE
string.Compare unintentionally doing O(n) compare

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#6465]
`string.Compare` has some logic to short-circuit if the strings it's comparing are equal, and the indices are equal. Except, it looks like it's calling String's overload of `==` instead of a reference comparison: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.cs#L2124

This probably hasn't been discovered before since if 2 strings are ordinally equal, then they should be equal for all the other types (CurrentCulture, InvariantCulture, *IgnoreCase, etc.) as well.

I'm going to submit a PR soon which includes a fix for this anyway, but I just wanted to let people know/confirm that this wasn't intentional.

cc @jkotas @bbowyersmyth @GSPP

**Comment by bbowyersmyth** [comment]
Yeah we were trying to figure that out a while back. https://github.com/dotnet/coreclr/pull/3113
I think it was intended to be a reference check. If someone can make a call on it, i'll close my PR that attempted to reduce the overhead of the equals.

**Comment by gkhanna79** [comment]
Is this still an actively worked upon issue @jamesqo ?

**Comment by jamesqo** [comment]
@gkhanna79 I already fixed this in a PR. Closing now
