### ISSUE TITLE
Debugging HowTo with *.dbg on Linux

### ISSUE THREAD

**Issue by leemgs** [dotnet/coreclr#6469]
> I will update the debugging instructions as soon as 
> I have a complete story/solution on the packaging of the *.dbg (and *.dwarf on OS X).
> https://github.com/dotnet/coreclr/pull/4023#issuecomment-204473326

@mikem8361 , Could you share us the debugging instruction If you have done documentation about the debugging using `*.dbg` file + `gdb` command? I could not find any documentation from https://github.com/dotnet/coreclr/tree/master/Documentation.
- Some files including *.dbg:

```
invain@db400:/nfs/runtime-collect-ubuntu-arm/runtime-arm-u1404-release-mode$ ls -al corerun*
-rwxr-xr-x 1 invain invain  24921  7월 25 16:41 corerun
-rw-r--r-- 1 invain invain 114531  7월 25 16:41 corerun.dbg
invain@db400:/nfs/runtime-collect-ubuntu-arm/runtime-arm-u1404-release-mode$ ls -al libcoreclr*
-rwxr-xr-x 1 invain invain  6094126  7월 25 16:41 libcoreclr.so
-rw-r--r-- 1 invain invain 61809426  7월 25 16:41 libcoreclr.so.dbg
invain@db400:/nfs/runtime-collect-ubuntu-arm/runtime-arm-u1404-release-mode$ 
```

As we all know, when we build the CoreCLR source with `release` flag, We can check the separated two files (e.g., foo and foo.dbg) compared to the `debug` build mode. Anyone who have a debugging experience with *.dbg on the Linux distributions such as Ubuntu, CentOS, and RedHat?

\CC:  @jkotas , @janvorli , @lemmaa , @chunseoklee , @sjsinju , @myungjoo

**Comment by mikem8361** [comment]
My experience has only been on Ubuntu and OSX with lldb (not gdb).  On Ubuntu, if the *.dbg files are next to the *.so file, lldb automatically loads it without any extra commands.  On OSX, there is a lldb needed to loaded them “target symbols add libcoreclr.dylib.dwarf”.

I haven’t updated any instructions yet because we don’t have a good story/solution yet as far as getting/downloading the symbol packages.

**Comment by leemgs** [comment]
> My experience has only been on Ubuntu and OSX with lldb (not gdb).  

@mkikem8361 , Thank you for sharing your experience on the CoreCLR debugging. 

> On Ubuntu, if the *.dbg files are next to the *.so file, lldb automatically loads it without any extra commands

@chunseoklee , Please, refer to the issuecomment https://github.com/dotnet/coreclr/issues/6469#issuecomment-235140123 before starting a debugging with LLDB + SOS Plug-in  on the Linux/ARM boards.

**Comment by lt72** [comment]
@mikem8361: please verify that the debugging instructions for linux are at the desired quality level and add the link to the symbols page.

**Comment by mikem8361** [comment]
See this link on core dump debugging with the new SOS: https://github.com/dotnet/diagnostics#installing-sos

See this link on new SOS symbol features: https://github.com/dotnet/diagnostics#new-features
