### ISSUE TITLE
Allow EventHandler with multiple generic parameters - EventHandler<TEventArgs1,TEventArgs2,...>

### ISSUE THREAD

**Issue by manish** [dotnet/coreclr#648]
Many mscorlib types allow multiple generic parameters like [Tuple](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Tuple.cs#L26-L51)

where I can create `Tuple<int>` or `Tuple<Type, string>` or `Tuple<string, Type>` which saves me from creating types just to hold these variables when I am going to use this data only a few times

Right now we only have an option of using either non-generic `EventHandler` or generic `EventHandler<TEventArgs>`. With the latter I need to create a new type for holding extra information where I could have just used EventHandler with two generic types

```
public class DataHolder
{
    public Type DataType { get; set; }

    public int Position { get; set; }
}

public event EventHandler<DataHolder> Changed;

obj.Changed += (object o, DataHolder args) => { };
```

can be just written as

```
public event EventHandler<Type, int> Changed;

obj.Changed += (object o, Type args1, int args2) => { } ;
```

Is there a design decision or compatibility issue as to why multiple generic parameter version of EventHandler cannot be provided?

**Comment by mikedn** [comment]
What's stopping you from using `Action<T1, T2, ...>` instead of `EventHandler<T1, T2, ...>`?

**Comment by stas-sultanov** [comment]
> What's stopping you from using Action<T1, T2, ...> instead of EventHandler<T1, T2, ...>?

I believe that this would break the Event Handler pattern.

The problem with more arguments is the following:
what name they should take? of course it is possible to give names like Item1, Item2, ItemN but they are meaningless.

I believe that the following code would do just what you expect:
`public event EventHandler<Tuple<Type, int>> Changed;`

**Comment by mikedn** [comment]
> I believe that this would break the Event Handler pattern.

You're breaking it anyway if you add `EventHandler` types with more than one `T`. The whole point of the EventHandler/EventArgs dance is that it avoids all kind of problems like too many parameters, parameter name issues, impossibility of adding more parameters without breaking existing code and requiring `out` parameters for cancel style events.

**Comment by stas-sultanov** [comment]
> You're breaking it anyway

Following solution does not break the pattern
`public event EventHandler<Tuple<Type, int>> Changed;`

**Comment by mikedn** [comment]
Well, I was specifically referring to the initial proposal. Adding EventHandler types with multiple `T`s breaks the pattern and if you don't care about the pattern you can simply use whatever delegate type you want, including `Action`.

The `Tuple` suggestion is debatable. Tuples are horrible for typical usage because their properties have meaningless names. And it's not clear why `EventHandler<T>` lacks a `T : EventArgs` constraint. If you look at the MSDN documentation you'll see that it says that the second parameter is derived from `EventArgs` so it's possible that the lack of constraint is an accident. 

Not using `EventArgs` as a base has the unfortunate side-effect that the event can no longer be handled by a `handler(object, EventArgs)` method, this sometimes useful and I consider this to be a part of the EventHandler pattern.

**Comment by stephentoub** [comment]
> If you look at the MSDN documentation you'll see that it says that the second parameter is derived from EventArgs so it's possible that the lack of constraint is an accident. 

Sounds like the docs should be updated.  The constraint was removed in .NET 4.5 so as to broaden allowed usage, in particular to help with avoiding allocations for cases where an event is raised frequently and the wrapper EventArgs instance is pure overhead.

**Comment by sharwell** [comment]
Following up on what @stephentoub said, the primary place I see it used is [`Progress<T>.ProgressChanged`](https://msdn.microsoft.com/en-us/library/hh137516.aspx).

**Comment by terrajobst** [comment]
I don't think we'd do that. The point of `EventArgs<T>` is to encode the conventional signature of events, which is to take exactly arguments and returning void. For arbitrary signatures, you'd use `Action<...>`.

Hence, I'm closing this.
