### ISSUE TITLE
Crossgen: Copy all entries of Debug Directory Table

### ISSUE THREAD

**Issue by tmat** [dotnet/coreclr#6482]
Roslyn may emit multiple entries to Debug Directory Table depending on configuration. 
- `IMAGE_DEBUG_TYPE_CODEVIEW` encoding PDB path and GUID
- `IMAGE_DEBUG_TYPE_REPRO` indicating that the compilation was deterministic and thus timestamps in the PE image can't be interpreted as date time
- `IMAGE_DEBUG_TYPE_EMBEDDED_PORTABLE_PDB` whose data payload contains a compressed Portable PDB if the /debug:embedded was used.

Other tools might add additional entries as noted in a TODO comment https://github.com/dotnet/coreclr/blob/master/src/zap/zapheaders.cpp#L342:

``` C++
// @TODO: pDebugEntry is an array of IMAGE_DEBUG_DIRECTORYs. Some tools
// (like ibcmerge) add an extra dummy IMAGE_DEBUG_DIRECTORY to indicate
// that the image was modified post-link.
// We need to copy all the IMAGE_DEBUG_DIRECTORYs. For now, we only copy
// the first one as it holds the relevant debug information.
```

Crossgen should copy all entries and their associated data blobs.

**Comment by JohnChen0** [comment]
Resolved with #7849.
