### ISSUE TITLE
CoreCLR won't run on win7 after build

### ISSUE THREAD

**Issue by jakesays** [dotnet/coreclr#65]
I get "The program can't start because api-ms-win-core-winrt-string-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem." after building.

Environment: Win 7 64bit, Vs 2013.

Build according to directions - build completes fine. Run CoreConsole.exe and get the above message.

**Comment by gkhanna79** [comment]
@KrzysztofCwalina can you please take a look? Looks like the apiset dependency is not installed as part of CoreConsole.

**Comment by ramarag** [comment]
Yes the apiset are not installed as part of product build. If you run <repo_root>tests\runtest.cmd, it will populate a folder with all the apisets needed and framework implementations used by the tests

**Comment by donaldcao** [comment]
After run runtest.cmd, still missing API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL DCOMP.DLL and IESHIMS.DLL, others copied to the output folder.

**Comment by gkhanna79** [comment]
@KrzysztofCwalina Do you have any thoughts on how to package the dependencies for the Console example?

**Comment by KrzysztofCwalina** [comment]
It would be great if the CoreCLR build system dropped all the Win7 dependencies to some folder so that people can for now manually just copy the files. Long term, we need a better packaging story and nuget-msbuild integration. I am in some discussions about this this week, but I think it's going to take some time before we have an answer that does not involve committing hundreds of binaries to the corefxlab depot.

**Comment by jakesays** [comment]
@gkhanna79 @KrzysztofCwalina Is there documentation available that describes these dependencies? They seem to be 8.x related, and it would be nice to target win7 specifically. I'd be willing to work on this if you can provide guidance.

**Comment by Nassiel** [comment]
I tried with Dependency walker and the only dependencies are against MSVCR120.dll and Kernel32.dll. Tomorrow I'l try with a more powerful tool detect why is searching for an api which actually is not referenced as a dependency.

Also MSVCR120.dll should link against the right dll core, not against windows 8.x api (WINRT)

**Comment by Alexx999** [comment]
This libs are documented here: https://msdn.microsoft.com/en-us/library/windows/desktop/hh802935%28v=vs.85%29.aspx
And it's stated that they are not available for Win7 and lower

**Comment by jkotas** [comment]
We are going to have package that emulates the apisets on Win7. This package is used by the tests today. Until we sort the CoreCLR packaging for Win7, you can workaround it by copying the api-ms-*.dll from under test directory next to coreclr.dll.

These apiset .dlls are forwarding the APIs to the Win7 implementation .dlls. They do not contain any actual code.

**Comment by Nassiel** [comment]
I see that in newapis.h/cpp you only evaluates if it's windows 7 or upper but this methods are not able in Win7, you're going to include more validations and a api redirection there?

**Comment by Nassiel** [comment]
I try to copy the api-ms and now, it's ok doesn't launch a dynamic link exception but actually every test, all of them launch a -1 error. corerun.exe never launch the .net exe application.

I theory I don't need any dll from the coreFx to run the coreCLR test, don't? Despite of that I try to build a extremely basic app (console hello world) and I added the System.Console.dll from the coreFx and the result is exactly the same.

With the verbose output I receive that CoreCLR.dll failed to load: Error code 193.

**Comment by KrzysztofCwalina** [comment]
I just committed a fix to HelloWorld console app in the CoreFxLab repo. To compile the application for Windows 7, you need to get the new bits and follow the instructions described in the CoreFxLab wiki, i.e. uncomment a line in the HelloWorld.csproj file that enables Windows 7 build.

**Comment by PiDiBi** [comment]
if you try to compile from command line with csc.exe thius solution works: http://forums.dotnetfoundation.org/t/coreclr-on-win7-api-ms-win-core-winrt-string-l1-1-0-is-missing/853

**Comment by eladkarako** [comment]
If you need the dependencies along see
https://github.com/dotnet/coreclr/issues/157#issuecomment-516187117 or 
https://gist.github.com/eladkarako/ff2b36ff2f8e199d597bd903cc412bad
