### ISSUE TITLE
[ARM/Linux] Question about .NET Core release criteria.

### ISSUE THREAD

**Issue by lemmaa** [dotnet/coreclr#6501]
As the number of failed unit test count come close to zero, I’m thinking about the release on the next step, and thereby may have questions.

Are there criteria of release of .NET Core? What we should meet, if we include ARM linux port to official release. Just making unit test fail to 0 is enough? Or any another tasks we should complete to release?
1. What component we should prepare. 
2. What condition we should meet for each component.
3. What others?

cc: @richlander @hongsekim

**Comment by janvorli** [comment]
An additional step would be verifying that CoreFX tests are passing as well.

**Comment by gkhanna79** [comment]
Tests should be passing in CoreCLR/CoreFx/Core-Setup repos in addition to Tizen specific test passes. You should also account for necessary performance, stress and reliability testing.

CC @leecow @brianrob

**Comment by hqueue** [comment]
@gkhanna79 Should we add tests(esp. performance and stress) with current build configuration for arm and armel ? As you already knew, currently .NET Core for arm and armel are built using clang 3.6 `-O1` optimization. To enable agressive optimization with  `-O3`, I think we have to enable clang 3.9 for arm and armel first to test performance correctly, as we discussed at https://github.com/dotnet/core-setup/issues/1411. What do you think of it?

**Comment by richlander** [comment]
I have been thinking along the same lines. I would like to include ARM32 as an official release. At the very least, I was planning on drawing more attention to ARM32 builds and using that as means of getting more mileage on them. After a period of time, if our own tests and the feedback come back "green", then that would compel me to call the builds official, which would be in everyone's interests.

Cool?

**Comment by brianrob** [comment]
cc: @valenis

**Comment by lemmaa** [comment]
I think that it is going well and close the issue. Please open anybody if necessary. Thank you.
