### ISSUE TITLE
[Benchmark] How to benchmark coreclr?

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#6503]
I'm trying to measure performance and memory usage on a arm32 device. I wonder if there is a typical way to do that for coreclr. Specifically I'd like to compare coreclr with mono. Currently I'm trying to run tests `tests/src/JIT/Performance` with `RunBenchmarks` driver.

/cc @kyulee1 @lemmaa @hongsekim @sjsinju

**Comment by gkhanna79** [comment]
@brianrob should be able to chime in as well.

**Comment by brianrob** [comment]
Yes, we have a benchmark harness called xunit.performance that you should be able to use, though it doesn't look like it will work on mono until 2.0 based on https://docs.microsoft.com/en-us/dotnet/articles/standard/library.

@DrewScoggins can you please point @wateret to instructions on how to run the coreclr benchmarks manually?

**Comment by danmosemsft** [comment]
@DrewScoggins ?

**Comment by DrewScoggins** [comment]
I have this [PR](https://github.com/dotnet/coreclr/pull/11297) open to add these instructions.

**Comment by DrewScoggins** [comment]
Just merged the PR, closing this issue.
