### ISSUE TITLE
Update toolchain to C# compiler with by ref returns

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/coreclr#6505]
We need the new compiler feature to make progress on Span<T>, i.e. I talked to @jkotas and he identified toolchanin update as a prerequisite to merging the span branch to main.

**Comment by KrzysztofCwalina** [comment]
@weshaggard, as we talked, I filed this issue and assigned it to you.

**Comment by weshaggard** [comment]
@markwilkie We need to update the compiler toolsets we are using. Who would be a good person to do that update?

**Comment by markwilkie** [comment]
Just CoreCLR or CoreFx too?  I think that @wtgodbe is most familiar w/ CoreCLR and probably @chcosta for CoreFx if that's needed.

**Comment by wtgodbe** [comment]
I'm unsure if I'm the right person for this (although it's very possible that I am, and I just know of the compiler toolset by a different name). What would I be changing here?

**Comment by weshaggard** [comment]
We will need to update both coreclr and corefx toolset.

**Comment by tannergooding** [comment]
FYI. @jaredpar, @angocke.

**Comment by jaredpar** [comment]
We're talking about merging this but haven't really discussed how this fits into the language. Seems premature.

**Comment by jkotas** [comment]
> What would I be changing here

This is about changing the C# compiler that is used to build coreclr/corefx to the prerelease version from https://www.nuget.org/packages/Microsoft.Net.Compilers

**Comment by omariom** [comment]
@KrzysztofCwalina 
The same should probably be done for CoreFxLab too.

**Comment by chcosta** [comment]
Ack, I'll take a look for CoreFx

**Comment by chcosta** [comment]
Is this the related issue?  https://github.com/dotnet/roslyn/issues/118  I want to ensure we are consuming the correct version of the compiler which has the fixes required.

**Comment by tannergooding** [comment]
@chcosta, that issue tracks the proposal and general discussion around the feature. Any of the recent builds of Roslyn should work, including the one shipped with Dev15 Preview 3 (https://www.nuget.org/packages/Microsoft.Net.Compilers/2.0.0-beta3).

If a newer build is desired then you should coordinate with @jaredpar so a newer build can get uploaded to nuget.

**Comment by jkotas** [comment]
Microsoft.Net.Compilers/2.0.0-beta3 is fine. I have been using for my experiments.

**Comment by jaredpar** [comment]
Cc @stephentoub as he has some requirements on which compiler we use in CoreFX. In that repo we are taking a dependency on the task like c# 7 support. That is a new feature so it should work just fine for all of the ref needs.
