### ISSUE TITLE
!VerifyHeap doesn't work on ARM64

### ISSUE THREAD

**Issue by billwert** [dotnet/coreclr#6514]
I have a simple C# program that is just a ReadLine so I have a handy place to pause the debugger.

When I debug this program, load SOS, and run !VerifyHeap, I get this output:
0:006> !verifyheap
Error getting card table lowest address
Error getting card table lowest address
Error getting card table lowest address
Error getting card table lowest address
Error getting card table lowest address
Error getting card table lowest address
Error getting card table lowest address
Error getting card table lowest address
Error getting card table lowest address
Error getting card table lowest address
Error getting card table lowest address
<Previous line repeats 287 more times>
Object 0000024eae881038:  missing card_table entry for 0000024EAE881220
Last good object: 0000024EAE881018.
Error getting card table lowest address
<Previous line repeats 9 times>
Object 0000024eae883050:  missing card_table entry for 0000024EAE883060
Last good object: 0000024EAE883030.
Error getting card table lowest address
<Previous line repeats 64 times>
Object 0000024eae883488:  missing card_table entry for 0000024EAE883498
Last good object: 0000024EAE883468.

**Comment by gkhanna79** [comment]
@ramarag Can you please look into this once your MDbg RI completes?
