### ISSUE TITLE
RyuJIT: Eliminating CORINFO_HELP_ARRADDR_ST calls for arrays of sealed types

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#6537]
In C# you're allowed to have covariant arrays if one type is a subclass of another. This can lead to runtime exceptions if you attempt to write an element that doesn't subclass the underlying type, e.g.

``` cs
string[] strings = { "1", "2", "3" };
object[] objects = strings; // no copying, direct assignment
objects[0] = new object(); // runtime exception!
```

Since we know this is never going to happen for sealed classes like `string` or `StringBuilder`, e.g. if you write a `string` to a `string[]` it will always be valid, it would be nice to elide these checks for such classes.
## Minimal repro code

``` cs
var array = new string[1];
array[0] = "str";
```

Generated assembly:

``` asm
G_M64216_IG02:
       48B90A84337AFD7F0000 mov      rcx, 0x7FFD7A33840A
       BA01000000           mov      edx, 1
       E8C879D05F           call     CORINFO_HELP_NEWARR_1_OBJ
       488BC8               mov      rcx, rax
       49B8683077956F020000 mov      r8, 0x26F95773068
       4D8B00               mov      r8, gword ptr [r8]
       33D2                 xor      edx, edx
       E8415BD05F           call     CORINFO_HELP_ARRADDR_ST
       90                   nop
```

[`CORINFO_HELP_ARRADDR_ST`](https://github.com/dotnet/coreclr/blob/b9f5ae88cc49836c8d31f07db7800707165cdb06/src/inc/corinfo.h#L473) is the method that does type-checking before writing to the array.

I was recently rewriting [string.Concat](https://github.com/dotnet/coreclr/blob/b9f5ae88cc49836c8d31f07db7800707165cdb06/src/mscorlib/src/System/String.cs#L3301) to use pooled arrays, and even with all of the array/string allocations + `FillStringChecked` overhead + virtual method calls to `ToString`, this call takes up about 10% of the time in the method. (It's increased to more than 15% with the array allocations taken out.)

It would be awesome if RyuJIT could eliminate calls to that method for sealed types :)

cc @mikedn @CarolEidt @jkotas @omariom

category:cq
theme:helpers
skill-level:expert
cost:medium

**Comment by omariom** [comment]
Yes, JIT could do bounds check inline and then call write barrier which is used with field assignments.

**Comment by mikedn** [comment]
This optimization would be nice to have but it's a bit problematic to implement at the moment because the JIT doesn't keep track of types unless verification is enabled. And verification is not enabled in CoreCLR...

Since you have already done some measurements it would be interesting to apply a workaround that avoids `CORINFO_HELP_ARRADDR_ST` and see how much performance improves. Make a struct containing a string field and then assign the string to that struct field:

```C#
struct Foo { public string s; }
Foo[] f = new Foo[42];
f[0].s = "a";
```

**Comment by jamesqo** [comment]
@mikedn It sounds crazy, but... I just tried what you said (stealing the implementation from [System.Collections.Immutable](https://github.com/dotnet/corefx/blob/master/src/System.Collections.Immutable/src/System/Collections/Immutable/RefAsValueType.cs#L23) since they do that as well). I can't say for the version we have now in CoreCLR, but in my experimental version of the method replacing `string` with `RefAsValueType<string>` consistently resulted in a *more than 50%* speedup in the method (from ~8-9 seconds to 3.5). Woot! :smile:

Before this I had actually spent a couple of days trying to figure out why my pooled-array version in `Concat` was barely faster than the one we have now. I guess this issue proved to be the real bottleneck in the method.

**Comment by mikedn** [comment]
It seems like a pretty good improvement to have.

Something that's worth pointing out is that the types do not have to be sealed. If the array allocation is visible to the JIT compiler then there's no need for types to be sealed:

```C#
A[] a = new A[42];
a[3.14] = new A(); // it's obvious that a type check is not required here
```

Of course, `sealed` is still useful in cases where the array allocation isn't visible to the compiler.

Unfortunately none of this helps with generic collections such as `List<T>`. `T` is not known to be sealed and without WPO it's impossible to prove that the items array is always of type `T[]`.

**Comment by omariom** [comment]
@mikedn Is that because the same code is generated for ref types?

**Comment by mikedn** [comment]
@omariom Yup.

**Comment by pgavlin** [comment]
@AndyAyersMS how does this intersect (if at all) with the type tracking we're now doing for devirt?

**Comment by AndyAyersMS** [comment]
It's closely related.

I've looked a similar problem: the span constructor has an array type check we'd like to optimize (#10258) -- since spans are not covariant and allow writes, so we have to check the types at construction time. See for instance [this prototype](https://github.com/AndyAyersMS/coreclr/tree/OptimizeSpanCtorTypeTest) on my CoreCLR fork.

Right now we don't track array types during importation since array construction is quite varied and I believe (despite the approach taken above) it's not worth digging through the array constructor expansion into IR to figure out what kind of array we have made. Instead we need to annotate the resulting tree node with type (as proposed in #10732) or defer expansion of array construction until after importation, which we're not quite ready for yet.

Once we have type info on tree nodes, when we have an array and we know the type we're assigning is compatible, then it is simple enough to omit the store covariance check. We'd still need a write barrier so it would not be a direct store, but it would be faster.

**Comment by AndyAyersMS** [comment]
Have this implemented, see [CovariantStoreImporterOpts](https://github.com/dotnet/coreclr/compare/master...AndyAyersMS:CovariantStoreImporterOpts)

Diffs are generally positive, but the loop cloner gets triggered by now-explicit array accesses and causes some sizeable regressions:
```
Total bytes of diff: -27916 (-0.07% of base)
    diff is an improvement.

Top file regressions by size (bytes):
        1349 : System.Data.Common.dasm (0.09% of base)
         602 : System.Linq.Expressions.dasm (0.08% of base)
         201 : System.Collections.Specialized.dasm (0.79% of base)
         125 : System.Reflection.DispatchProxy.dasm (0.50% of base)
         106 : System.Collections.Concurrent.dasm (0.03% of base)

Top file improvements by size (bytes):
      -12978 : Microsoft.Diagnostics.Tracing.TraceEvent.dasm (-0.41% of base)
       -6458 : Microsoft.CodeAnalysis.VisualBasic.dasm (-0.12% of base)
       -3051 : Microsoft.CodeAnalysis.CSharp.dasm (-0.07% of base)
       -1570 : System.Private.Xml.dasm (-0.04% of base)
        -725 : System.Net.HttpListener.dasm (-0.32% of base)

99 total files with size differences (82 improved, 17 regressed), 30 unchanged.

Top method regressions by size (bytes):
         576 (26.10% of base) : System.Linq.Expressions.dasm - StackSpiller:RewriteListInitExpression(ref,int):struct:this
         444 (13.12% of base) : Microsoft.CodeAnalysis.CSharp.dasm - LocalRewriter:RewriteMultiDimensionalArrayForEachStatement(ref):ref:this
         322 ( 7.27% of base) : Microsoft.CodeAnalysis.CSharp.dasm - MethodBodySynthesizer:ConstructFieldLikeEventAccessorBody_Regular(ref,bool,ref,ref):ref
         322 (61.22% of base) : System.Private.CoreLib.dasm - MethodBase:CheckArguments(ref,ref,int,ref,ref):ref:this
         280 (17.41% of base) : System.Private.CoreLib.dasm - RuntimeType:MakeGenericType(ref):ref:this (2 methods)

Top method improvements by size (bytes):
       -1439 (-8.21% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Binder:ReportOverloadResolutionFailureForASingleCandidate(ref,ref,int,byref,struct,struct,bool,bool,bool,bool,ref,ref,bool,ref,ref):this
        -350 (-9.14% of base) : System.Private.CoreLib.dasm - CalendarData:CreateInvariant():ref (2 methods)
        -330 (-3.64% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - SyntaxFactory:GetNodeTypes():ref
        -305 (-0.95% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - VisualBasicCommandLineParser:Parse(ref,ref,ref,ref):ref:this
        -195 (-0.82% of base) : Microsoft.CodeAnalysis.CSharp.dasm - CSharpCommandLineParser:Parse(ref,ref,ref,ref):ref:this

Top method regressions by size (percentage):
         114 (83.82% of base) : System.Collections.Specialized.dasm - NameObjectCollectionBase:BaseGetAllKeys():ref:this
         114 (83.82% of base) : System.Collections.Specialized.dasm - NameObjectCollectionBase:BaseGetAllValues():ref:this
          75 (65.22% of base) : System.IO.FileSystem.DriveInfo.dasm - DriveInfo:GetDrives():ref
          90 (61.64% of base) : System.Data.Common.dasm - FieldNameLookup:.ctor(ref,int):this
         322 (61.22% of base) : System.Private.CoreLib.dasm - MethodBase:CheckArguments(ref,ref,int,ref,ref):ref:this

Top method improvements by size (percentage):
         -41 (-14.19% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - SynthesizedMyGroupCollectionPropertyGetAccessorSymbol:GetMethodBlock(ref,ref,ref):ref:this
         -41 (-14.19% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - SynthesizedMyGroupCollectionPropertySetAccessorSymbol:GetMethodBlock(ref,ref,ref):ref:this
         -37 (-13.17% of base) : System.Private.CoreLib.dasm - NativeRuntimeEventSource:MethodJitInliningSucceeded(ref,ref,ref,ref,ref,ref,ref,ref,ref,ushort):this
         -37 (-13.17% of base) : System.Private.CoreLib.dasm - NativeRuntimeEventSource:MethodJitInliningFailedAnsi(ref,ref,ref,ref,ref,ref,ref,ref,ref,bool):this
         -37 (-13.17% of base) : System.Private.CoreLib.dasm - NativeRuntimeEventSource:MethodJitTailCallFailedAnsi(ref,ref,ref,ref,ref,ref,ref,ref,ref,bool):this

4129 total methods with size differences (3799 improved, 330 regressed), 199577 unchanged.
```
So may need to address #2634, #12836 first...
