### ISSUE TITLE
Fix unaligned memory access in Buffer.MemoryCopy

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#6540]
According to my code review, `Buffer.MemoryCopy(..., ..., 4, 4)` executes `*(int *)dest = *(int *)src` (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Buffer.cs#L302). This will be an unaligned access if one of the pointers is not 4 byte aligned. I'm not sure about the performance implications on x86. On ARM this (allegedly) faults. I can't test on ARM so I thought I'd report it to have this reviewed.

If this is OK a comment should be added explaining why.

**Comment by jkotas** [comment]
The unaligned memory access is faster on x86 that manual one byte at a time copy, and it does not fault on ARM variants that CoreCLR runs on.

**Comment by benaadams** [comment]
Don't think x86 has had huge issues with unaligned memory by itself for a while http://agner.org/optimize/microarchitecture.pdf (Memory Access sections)

Intel Core2 had issues with straddling a cache line (64bytes) e.g. 2 bytes in one, 2 bytes in another (12 clock read, 10 clock write). Nehalem onwards has been ok. 

Atom has issue with crossing 64 byte boundary (16 clocks).

VIA Nano 2000 crossing 32byte, 3000 crossing 64byte. (18 clock read, 37 clock write).
 
AMD Bulldozer, Piledriver & Steamroller have slight latency if you cross a cache line (2/3 clocks), a bigger one if you cross a page boundary (21 clocks).

AMD Bobcat and Jaguar have a penalty for a misaligned read crossing a 16 byte boundary (3 clocks).

**Comment by jamesqo** [comment]
@jkotas 

> and it does not fault on ARM variants that CoreCLR runs on.

Just curious, then why is [this ifdef](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Buffer.cs#L253) here to P/Invoke into a native method when calling `Buffer.Memcpy`? I had assumed before it was due to these unaligned memory accesses that the method would have issues on ARM.

**Comment by jkotas** [comment]
@jamesqo This ifdef is not PInvoke - it is FCall. It was that done for Windows Phone 8.0 (the first time CoreCLR run on ARM) as a performance fix. This was a hot function in number of real-world apps and the ARM JIT did not generate good code for the managed implementation at that time.

**Comment by tannergooding** [comment]
I had thought that if destination is unaligned, then you should do a single unaligned write, then adjust to be aligned and continue. You would end up writing `(byteCount mod alignment)` twice, but overall would have better performance than doing all unaligned writes (and better performance than writing single bytes multiple times to reach alignment).

**Comment by choikwa** [comment]
[Intel 64 & 32-IA Optimization Arch manual](http://www.intel.com/content/www/us/en/architecture-and-technology/64-ia-32-architectures-optimization-manual.html) section 11.6.3 states
>Unaligned stores are likely to cause greater performance degradation than unaligned loads, since there is a very high penalty on stores to a split cache-line that crosses pages. This penalty is estimated at **150** cycles. Loads that cross a page boundary are executed at retirement.

**Comment by benaadams** [comment]
@choikwa some extreme analysis and fixes being done here https://github.com/dotnet/coreclr/pull/6638

**Comment by jamesqo** [comment]
@choikwa 

> that crosses pages.

A page is typically ~4K or ~8K in size, so crossing a page boundary would be a very rare occurrence. Also keep in mind that all the writes during the main loop are the aligned, although the reads may not be.

**Comment by choikwa** [comment]
@jamesqo This may be more relevant.
>When using Intel AVX with unaligned 32-byte vectors, every second load is a cache-line split, since the cache-line is 64 bytes. This doubles the cache line split rate compared to Intel SSE code that uses 16- byte vectors. Even though split line access penalties were reduced significantly since Intel microarchitecture code name Nehalem, a high cache-line split rate in memory-intensive code may cause performance degradation.

The idea is that using 16 byte vectors vs. 32 may reduce cache line split rate.

**Comment by jkotas** [comment]
This was fine tuned for x86/x64 in https://github.com/dotnet/coreclr/pull/9786 . I am going to open a new issue to look at tuning this for arm/arm64.
