### ISSUE TITLE
What places in mscorlib could use array pooling?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#6545]
Due to the lack of availability of `ArrayPool` in mscorlib, I'm planning to introduce an `ArrayCache` class to CoreCLR that implements similar functionality except using `ThreadStatic` and only holding one array at a time, similar to the [`StringBuilderCache`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/StringBuilderCache.cs) we have now.

What commonly used functions/methods in mscorlib would benefit from this? Here's a mini-list I have so far:
- String.Split (for the int array separators)
- Lots of System.Reflection.Emit (though I'm going to wait on that, until at least the code is [properly formatted](https://github.com/dotnet/coreclr/issues/972)/refactored)
- [Potentially MemoryStream](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/MemoryStream.cs#L289) when `_expandable` is true (meaning the backing `byte[]` wasn't user-supplied)
  - The corresponding changes in CoreFX could be made using `ArrayPool`

Those are just a few examples, I'm sure there are many more. (Very unfortunately this can't be done with `Stream.CopyTo` since it looks like dotnet/corefx#6473 opted to not do this for arrays that can be exposed to the end-user.) I'm opening this issue so I can gather feedback from y'all and potentially submit PRs to those places that could use array caching :smile:

cc @jkotas @omariom @mikedn @GSPP

**Comment by jkotas** [comment]
There is ArrayPool in corefx but it is very hard to find places where its use would be both safe and beneficial. There has been multiple discussions about it in corefx. I doubt that it will be different in mscorlib.

**Comment by jkotas** [comment]
> the int array separators

These would be best stack-allocated. There are several different patterns that can be used for this.

> System.Reflection.Emit

System.Reflection.Emit implementation in CoreCLR is overall pretty slow. Local fixes won't really move the needle. If you are interested in fast System.Reflection.Emit, take a look at  https://github.com/jfrijters/Managed.Reflection. I believe it is multiple times faster that CoreCLR refemit, and it is the right way to implement Reflection.Emit - decoupled from the runtime.

**Comment by benaadams** [comment]
Could use an internal struct with a fixed sized array and then `Span<T>` over it; would use a tiny bit less memory and drop an object reference which would be one less thing for the GC to look at. Not sure it would be worth it though.

**Comment by jkotas** [comment]
We use ArrayPool in number of places now.
