### ISSUE TITLE
Windows Pri1 testing broken?

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#6554]
It looks like #6400 has broken Windows Pri1 testing:
- http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1_prtest/4253/console
- http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1_prtest/4254/console
- http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1_prtest/4252/console

Not sure if the other legs are okay.

**Comment by pgavlin** [comment]
cc @Priya91

**Comment by adityamandaleeka** [comment]
Based on those logs, it looks like the problem is that `-priority 1` needs to be `-priority=1`. I wish it were clearer where those args are coming from though.

**Comment by Priya91** [comment]
#6557 addresses this issue.

**Comment by Priya91** [comment]
I get this error in the pri1 builds, this doesn't seem related to the build scripts change..
```
error MSB4186: Invalid static method invocation syntax: "[System.IO.Path]::GetFullPath()". Method 'System.IO.Path.GetFullPath' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). 
```

**Comment by pgavlin** [comment]
It turns out that #6400 also appears to have drastically slowed down the Windows x64 Debug test leg: the jobs used to take ~1:15 as per @mmitche and now we're frequently hitting the 2 hour timeout. We should consider rolling the change back.

**Comment by Priya91** [comment]
Potential fix for timeouts: #6565

**Comment by Priya91** [comment]
#6566 should fix the msbuild error on getFullPath.

**Comment by Priya91** [comment]
All issues in this thread are fixed.
