### ISSUE TITLE
Make sure that EE/debugger allocates executable memory only when it's needed for patches

### ISSUE THREAD

**Issue by Djuffin** [dotnet/coreclr#657]
Right now all the memory allocated by EE/debugger via DebuggerHeap is executable. Given that on Linux we have only one real heap, it leads to a situation when random pages of data heap marked as executable. We need to localize places where EE/debugger allocated executable patches and make sure   that everything else is allocated in non-executable memory.

**Comment by tzwlai** [comment]
This issue should have been taken care of by #2264 as well.

CC @adityamandaleeka
