### ISSUE TITLE
int? is not nullable<int> anymore?

### ISSUE THREAD

**Issue by liuliang-wt** [dotnet/coreclr#6570]
then how do I differentiate int from int?

and this is even more worse:

int? a = null;
Type test = a.GetType();

it just throw an null reference exception...

is this by design or you are going to fix it?

**Comment by jkotas** [comment]
It is by design - it is explained in https://msdn.microsoft.com/en-us/library/ms366789.aspx:

    Calling GetType on a Nullable type causes a boxing operation to be performed when the type is implicitly converted to Object. 

The null nullable is boxed as null. GetType called on null results into NullReferenceException.
