### ISSUE TITLE
Improper casing causes lldb-3.7 to not be found. Error: "Cannot find lldb-3.5 or lldb-3.6"

### ISSUE THREAD

**Issue by Nassiel** [dotnet/coreclr#658]
If I execute lldb -v I have the version 3.7.

I tried to modify the CMakeList and I add to the find_library function lldb-3.7 but even with it, the system still repeat the same error.

¿Any idea?

**Comment by MattWhilden** [comment]
Can you post what your changes are? You may also be able to get help in the chat at http://gitter.im/dotnet/coreclr

**Comment by pgavlin** [comment]
I think I've hit the same issue--there is a casing problem in lldbplugin/CMakeLists.txt--the patch below should fix it. @MattWhilden I'll submit a PR for this momentarily.

```
diff --git a/src/ToolBox/SOS/lldbplugin/CMakeLists.txt b/src/ToolBox/SOS/lldbplugin/CMakeLists.txt
index 25ccf6b..50aa543 100644
--- a/src/ToolBox/SOS/lldbplugin/CMakeLists.txt
+++ b/src/ToolBox/SOS/lldbplugin/CMakeLists.txt
@@ -18,7 +18,7 @@ if(NOT ENABLE_LLDBPLUGIN)
 endif()

 # Check for LLDB library
-find_library(LLDB NAMES lldb-3.6 lldb-3.5 LLDB PATHS "${WITH_LLDB_LIBS}")
+find_library(LLDB NAMES lldb-3.6 lldb-3.5 LLDB lldb PATHS "${WITH_LLDB_LIBS}")
 if(LLDB STREQUAL LLDB-NOTFOUND)
     if(REQUIRE_LLDBPLUGIN)
         message(FATAL_ERROR "Cannot find lldb-3.5 or lldb-3.6. Try installing lldb-3.6-dev (or the appropriate package for your platform)")
```

**Comment by pgavlin** [comment]
PR #671

**Comment by ellismg** [comment]
@Nassiel Now that #671 has been merged, are things working for you?

**Comment by MattWhilden** [comment]
@ellismg I'll optimistically close this bug for now.

@Nassiel I'm happy to reopen it if you continue to have issues.

**Comment by lithiumlab** [comment]
Just happened to me using latest instructions form here:
using yosemite

https://github.com/dotnet/coreclr/blob/63766f74c4a641a274cd2933b9b7fd7bbddef2dd/Documentation/building/osx-instructions.md#openssl


```
Cannot find lldb-3.5 or lldb-3.6.  Try installing lldb-3.6-dev (or the
  appropriate package for your platform)
 ```

**Comment by jda808** [comment]
Happening here as well. 

coreclr versionator$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004

**Comment by ellismg** [comment]
@jda808 What version of XCode do you have installed?

**Comment by jda808** [comment]
it's failing with 7.2, 7.31, and 8 GM Seed. I can run 'xcodebuild -version -sdk' on the other systems if that helps. Here's a dump from 7.2

:~ jda808$ xcodebuild -version -sdk
MacOSX10.11.sdk - OS X 10.11 (macosx10.11)
SDKVersion: 10.11
Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
PlatformVersion: 1.1
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
ProductBuildVersion: 15C43
ProductCopyright: 1983-2015 Apple Inc.
ProductName: Mac OS X
ProductUserVisibleVersion: 10.11.2
ProductVersion: 10.11.2

iPhoneOS9.2.sdk - iOS 9.2 (iphoneos9.2)
SDKVersion: 9.2
Path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk
PlatformVersion: 9.2
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
ProductBuildVersion: 13C75
ProductCopyright: 1983-2015 Apple Inc.
ProductName: iPhone OS
ProductVersion: 9.2

iPhoneSimulator9.2.sdk - Simulator - iOS 9.2 (iphonesimulator9.2)
SDKVersion: 9.2
Path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk
PlatformVersion: 9.2
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
ProductBuildVersion: 13C75
ProductCopyright: 1983-2015 Apple Inc.
ProductName: iPhone OS
ProductVersion: 9.2

AppleTVOS9.1.sdk - tvOS 9.1 (appletvos9.1)
SDKVersion: 9.1
Path: /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS9.1.sdk
PlatformVersion: 9.1
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform
ProductBuildVersion: 13U78
ProductCopyright: 1983-2015 Apple Inc.
ProductName: Apple TVOS
ProductVersion: 9.1

AppleTVSimulator9.1.sdk - Simulator - tvOS 9.1 (appletvsimulator9.1)
SDKVersion: 9.1
Path: /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk
PlatformVersion: 9.1
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform
ProductBuildVersion: 13U78
ProductCopyright: 1983-2015 Apple Inc.
ProductName: Apple TVOS
ProductVersion: 9.1

WatchOS2.1.sdk - watchOS 2.1 (watchos2.1)
SDKVersion: 2.1
Path: /Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS2.1.sdk
PlatformVersion: 2.1
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform
ProductBuildVersion: 13S660
ProductCopyright: 1983-2015 Apple Inc.
ProductName: Watch OS
ProductVersion: 2.1

WatchSimulator2.1.sdk - Simulator - watchOS 2.1 (watchsimulator2.1)
SDKVersion: 2.1
Path: /Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator2.1.sdk
PlatformVersion: 2.1
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform
ProductBuildVersion: 13S660
ProductCopyright: 1983-2015 Apple Inc.
ProductName: Watch OS
ProductVersion: 2.1

Xcode 7.2
Build version 7C68

**Comment by JohnGorter** [comment]
Is there a fix to this problem: "Cannot find lldb-3.5,lldb-3.6, lldb-3.8 or lldb-3.9.  Try installing
  lldb-3.6-dev (or the appropriate package for your platform)"

coreclr is not building without problems.. 

I've tried every suggestion I found. updating brew, installing llvm --with-lldb linking it, nothing seems to work..

**Comment by janvorli** [comment]
@JohnGorter you can disable the lldb plugin compilation by adding `cmakeargs -DENABLE_LLDBPLUGIN=0` to your build.sh command line. You may need to delete the `bin` folder to make cmake pick this change.
If you want to build the plugin, you'll need to build lldb from sources first to get the necessary headers and libraries. I think they are not available as a package on OSX.
It is described here:
https://github.com/dotnet/coreclr/blob/master/Documentation/building/buildinglldb.md

**Comment by JohnGorter** [comment]
@janvorli, first thanx for the reply. Second: tried a ./clean.sh and afterwards a ./build.sh cmakeargs -DENABLE_LLDBPLUGIN=0.

This did not change anything..

**Comment by janvorli** [comment]
@JohnGorter I am sorry, it should be `-DSKIP_LLDBPLUGIN=1` instead of `-DENABLE_LLDBPLUGIN=0`

**Comment by JohnGorter** [comment]
It still failes:

Command execution succeeded.
Command successfully completed.
~/desktop/core2/coreclr/bin/obj/OSX.x64.Debug ~/desktop/core2/coreclr
Invoking "/Users/johngorter/desktop/core2/coreclr/src/pal/tools/gen-buildsys-clang.sh" "/Users/johngorter/desktop/core2/coreclr" 3 5 x64 Debug  Include_Tests  -DCLR_CMAKE_TARGET_OS=OSX -DCLR_CMAKE_PACKAGES_DIR=/Users/johngorter/desktop/core2/coreclr/packages -DCLR_CMAKE_PGO_INSTRUMENT=0 -DSKIP_LLDBPLUGIN=1
Including tests directory in build.
Detected OSX x86_64
CMake Warning at src/ToolBox/SOS/lldbplugin/CMakeLists.txt:64 (message):
  Cannot find lldb-3.5,lldb-3.6, lldb-3.8 or lldb-3.9.  Try installing
  lldb-3.6-dev (or the appropriate package for your platform)


-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   BestFitMappingNative
   BoolNative
   ForeignThreadExceptionsNative


And later on:
Scanning dependencies of target cordbee_dac
[  0%] Building CXX object src/md/hotdata/dac/CMakeFiles/mdhotdata_dac.dir/__/hotheapsdirectoryiterator.cpp.o
/Users/johngorter/desktop/core2/coreclr/src/pal/src/exception/seh.cpp:56:12: error:
      explicit specialization of non-template struct 'remove_reference'
    struct remove_reference<T&>
           ^               ~~~~
/Users/johngorter/desktop/core2/coreclr/src/pal/src/exception/seh.cpp:62:12: error:
      explici....

John.

**Comment by janvorli** [comment]
@JohnGorter but this failure is due to another reason - the case where I have asked you for generating the preprocessed file. The *Cannot find lldb-3.5,lldb-3.6, lldb-3.8 or lldb-3.9* is now just a warning with the SKIP_LLDBPLUGIN defined.

**Comment by JohnGorter** [comment]
I guess my problem with building the coreclr is related to issues we are discussing on another thread :)

Thanx for your assistance....
