### ISSUE TITLE
ARM64: take a look at todo in debugger code

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#6580]
debug\di\arm64\cordbregisterset.cpp:    // @ARM64TODO: floating point support
ToolBox\SOS\Strike\disasmARM64.cpp:    // ARM64TODO: needs to be implemented for jump stubs for ngen case
ToolBox\SOS\Strike\disasmARM64.cpp:    // ARM64TODO: not (yet) implemented. perhaps we don't need it at all.
ToolBox\SOS\Strike\disasmARM64.cpp:            // ARM64TODO: we could possibly handle adr(p)/ldr pair too.
ToolBox\SOS\Strike\util.h://ARM64TODO: Verify the correctness of the following for ARM64

**Comment by ramarag** [comment]
- debug\di\arm64\cordbregisterset.cpp:    // @ARM64TODO: floating point support
- ToolBox\SOS\Strike\disasmARM64.cpp:    // ARM64TODO: needs to be implemented for jump stubs for ngen case
- ToolBox\SOS\Strike\disasmARM64.cpp:    // ARM64TODO: not (yet) implemented. perhaps we don't need it at all.
- ToolBox\SOS\Strike\disasmARM64.cpp:            // ARM64TODO: we could possibly handle adr(p)/ldr pair too.
~~ToolBox\SOS\Strike\util.h://ARM64TODO: Verify the correctness of the following for ARM64 ~!~

**Comment by ramarag** [comment]
@noahfalk @mikem8361 
can you comment on https://github.com/dotnet/coreclr/blob/master/src/ToolBox/SOS/Strike/disasmARM64.cpp#L128

**Comment by ramarag** [comment]
@noahfalk @mikem8361 
can you also provide some guidance on how to test, when implementation is added for 

https://github.com/dotnet/coreclr/blob/master/src/debug/di/arm64/cordbregisterset.cpp#L66
https://github.com/dotnet/coreclr/blob/master/src/ToolBox/SOS/Strike/disasmARM64.cpp#L68
https://github.com/dotnet/coreclr/blob/master/src/ToolBox/SOS/Strike/disasmARM64.cpp#L361

**Comment by mikem8361** [comment]
I don't have anything to add about the todo's or the code.  I'm not that familiar with it.

As far as testing, we do have some SOS tests in the debuggertests repo but nothing that covers the "u" command.  You would have to manually test it.

**Comment by noahfalk** [comment]
For debug/di/arm64/cordbregisterset.cpp I would use mdbg or VS to look at the registers manually for some managed code. Any pre-existing tests we have for this at best are just going to print all the registers and verify it doesn't crash. There is no way a test would have predicted what the correct register values would be for ARM64 before we had ever created the port.

@mikem8361 - I'm not familiar with disasmARM64.cpp either. Your call how much effort you want to put into reviewing it.

**Comment by BruceForstall** [comment]
@noahfalk @mikem8361 I still see the following `@ARM64TODO` in debug/SOS code:

```
debug\di\arm64\cordbregisterset.cpp:    // @ARM64TODO: floating point support
ToolBox\SOS\Strike\disasmARM64.cpp:    // ARM64TODO: needs to be implemented for jump stubs for ngen case
ToolBox\SOS\Strike\disasmARM64.cpp:    // ARM64TODO: not (yet) implemented. perhaps we don't need it at all.
ToolBox\SOS\Strike\disasmARM64.cpp:            // ARM64TODO: we could possibly handle adr(p)/ldr pair too.
```

**Comment by BruceForstall** [comment]
@mikem8361 I created https://github.com/dotnet/diagnostics/issues/40

**Comment by BruceForstall** [comment]
But should this stay open for the `debug\di\arm64\cordbregisterset.cpp` case?

**Comment by mikem8361** [comment]
Yes.

**Comment by BruceForstall** [comment]
Leaving this in "Future" milestone since floating point register support only applies to optimized code debugging, which isn't supported.

**Comment by tommcdon** [comment]
This bug is tracking the work in debug\di\arm64

**Comment by cshung** [comment]
We have a bigger problem here - our API - `ICorDebugRegisterSet2::GetRegisters()` does not support register with more than 64 bits, it is hurting not just ARM64, but also AMD64 XMM registers.

Closing this one and track the bigger issue in #22836
