### ISSUE TITLE
ARM64: Assertion failed '((consume == 0) && (produce == 0)) || (ComputeAvailableSrcCount(tree) == consume)

### ISSUE THREAD

**Issue by kyulee1** [dotnet/coreclr#6583]
C:\Users\DDJOIN\scratch\System.Private.CoreLib.dll Test compiled Assert failure(PID 9744 [0x00002610], Thread: 6016 [0x1780]): 
Assertion failed '((consume == 0) && (produce == 0)) || (ComputeAvailableSrcCount(tree) == consume)' in 'Microsoft.Cci.PeWriter:WritePeToStream(ref,ref,ref,ref):bool:this' (IL size 908) File: d:\j\workspace\arm64_cross_c---f41ee988\src\jit\lsra.cpp Line: 3311
```
JIT\Performance\CodeQuality\Roslyn\CscBench.CscBench
managed\Compilation\Compilation.Compilation
```

**Comment by kyulee1** [comment]
@briansull Can you take a look?

**Comment by briansull** [comment]
In the dump I see that we are examining the following node:


N2001 (  7,  5) [002379] ------------- arg11 out+18|  +--*  putarg_stk [+0x18] void   REG NA
N2003 (  1,  1) [001798] ------------- List Item 0 |  |  /--*  lclVar    ref    V97 tmp59        u:6 (last use) REG NA $30f
N2005 (  1,  1) [001799] ------------- List Item 1 |  |  +--*  lclVar    ref    V98 tmp60        u:6 (last use) REG NA $30e

**Comment by briansull** [comment]
@pgavlin says that he understands this issue and will have a fix shortly
