### ISSUE TITLE
"build.sh" no longer has a option for clean build

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/coreclr#6590]
I regularly do `./build.sh clean` to get a clean build but it looks like that option has been removed with the recent changes to the build scripts. 

According to the help text, there is a `-Rebuild` option that claims to force a clean build, but it doesn't seem to be doing so (at least not for the native stuff).

**Comment by adityamandaleeka** [comment]
@Priya91

**Comment by Priya91** [comment]
-rebuild passes /t:rebuild to msbuild, for deleting the directories, ```clean.cmd/clean.sh``` to be used.

**Comment by adityamandaleeka** [comment]
1)	Before, you could do `./build.sh clean RELEASE` or `./build.sh clean x86` or whatever and it would clean just the stuff related to the one flavor you are interested in. Clean.sh doesn’t do that.

2)	Build.sh claims in the help text: `-Rebuild: force a clean build ^(default is to perform an incremental build^).` As mentioned above, this doesn’t seem to be the case (at least for native code). If that’s intentional, then at least the help text should make it clear what it’s actually doing.

**Comment by Priya91** [comment]
1) - tracked in backlog in eng infra.
2) - #6592

**Comment by Priya91** [comment]
@RussKeldorph this will be picked up by the infra work, assigning to @markwilkie for triage.
