### ISSUE TITLE
consider make List's InitSize bigger 

### ISSUE THREAD

**Issue by egmkang** [dotnet/coreclr#6599]
i found List<T> and ArrayList's InitSize is **4**. it's a very small number.
Do you think it would get this bigger.

**Comment by SunnyWar** [comment]
You can initialize it to any size you like rather than use the default.  I think 4 seems like a perfectly fine initial size given no other information on who many items the lists will contain.

`public List(
	int capacity
)
`

`public ArrayList(
	int capacity
)
`

**Comment by egmkang** [comment]
i looked Jawa's ArrayList, it's default size is 10. and i tested my application, 4 is really too small, after change it to 8~16, it got 5%(at least) time reduction.

**Comment by mikedn** [comment]
> and i tested my application, 4 is really too small, after change it to 8~16, it got 5%(at least) time reduction. 

Maybe your application is faster as a result of this change but then other applications could be slower due to increased memory usage and more GC. There's really no such thing as optimum initial list size, it depends too much on how lists are used.

**Comment by SunnyWar** [comment]
> after change it to 8~16, it got 5%(at least) time reduction. 

If you application benefits from a change like this, then your application would benefit from initializing the array to larger number...which is provided by setting the _capacity_.

**Comment by jnm2** [comment]
Is there a writeup on how the number 4 was chosen? Would be an interesting read.
