### ISSUE TITLE
Thread object's handles accumulate over time to a high number

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#6602]
A thread that is created allocates some handles in Thread::AllocHandles(). After it terminates, the managed thread object needs to be collected by a GC for the handles to be released. Some applications that are mostly idle but have a timer ticking periodically will cause a thread pool thread to be created on each tick, and over time the number of handles accumulates to a high value. Thread creation adds some memory pressure, but that does not force a GC until a sufficiently large handle count, and for some mostly idle apps, that can be very long.

Add a time-based heuristic that takes into account the number of threads that have terminated but have not yet been released by the GC, to trigger a GC and keep the number of open handles to a relatively low value.

**Comment by kouvel** [comment]
Fix should be ported to desktop as well

**Comment by kuacci** [comment]
Will you fix this issue in next release of .net framework?

**Comment by kouvel** [comment]
Yes that's the plan

**Comment by kuacci** [comment]
Is there any timeline existed for this fix?

**Comment by kouvel** [comment]
@kuacci, I have put up a PR now

**Comment by kuacci** [comment]
Thanks for your excellent work! When can we expect this fix to release?
