### ISSUE TITLE
Backport "CoreCLR runtime doesn't work on Linux kernel 4.6.x #6016" to 1.0.x

### ISSUE THREAD

**Issue by joshfree** [dotnet/coreclr#6604]
Tracking issue for servicing issue https://github.com/dotnet/coreclr/issues/6016 / PR https://github.com/dotnet/coreclr/pull/6027

**Comment by joshfree** [comment]
cc: @leecow @sergiy-k

**Comment by NinoFloris** [comment]
How's it going?

**Comment by janvorli** [comment]
It was backported few days ago and the fixed version of the runtime seems that it is now available:
https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR
@joshfree / @leecow am I right that the version 1.0.4 contains that fix?

**Comment by joshfree** [comment]
Yes, the fix is now backported.  I think we need @leecow to update the git tag and release notes next.

I think this tracking bug can be safely closed at this point.

**Comment by leecow** [comment]
Notes updated - https://github.com/dotnet/coreclr/releases/tag/v1.0.4 

@joshfree @janvorli @NinoFloris

**Comment by NinoFloris** [comment]
Great thank you all!
