### ISSUE TITLE
Improving NullReferenceException: Reporting what was null?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/coreclr#661]
Not sure where to post this ... let me know if this should go to dotnet/roslyn

Following a comment made by [Joel Kauffman](https://www.linkedin.com/pub/joel-kauffman/10/390/100) @ifranto on [.NET Rocks!](http://dotnetrocks.com/default.aspx?showNum=1122) today, is it possible for NullReferenceException to report more detail on the source of the exception? I think everyone has had a few "object reference not set to instance of object" head scratchers. Can it throw with more detail (e.g., if we pass a null var to something not expecting it, can it state the var as part of the exception)?

**Comment by akoeplinger** [comment]
There's already an issue for this: https://github.com/dotnet/coreclr/issues/25
