### ISSUE TITLE
Unable to run NuGet.exe on mac

### ISSUE THREAD

**Issue by ckkashyap** [dotnet/coreclr#6615]
I built coreclr and corefx on my mac OSX El Capitan(10.11.6). The builds went through successfully. However when I tried to run nuget.exe I got this error

~DotNet/coreclr/bin/Product/OSX.x64.Debug/corerun ~/DotNet/corefx/Tools/NuProj/NuGet.exe 

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly '~/DotNet/corefx/Tools/NuProj/NuGet.exe'. An attempt was made to load a program with an incorrect format.

Abort trap: 6

Am I missing something here?

**Comment by mellinoe** [comment]
Unless something has changed, NuGet.exe is not a .NET Core program and can't be run with CoreCLR. Even still, your error seems to indicate that it failed to load because it was a 32-bit application. It's probably not going to work either way.

Your options are:
* Run nuget.exe with mono (disclaimer: no idea how well this works)
* Use `dotnet` (https://github.com/dotnet/cli) and it's nuget-related features.

You may also have better luck asking in the nuget repo (https://github.com/nuget/home).

**Comment by ckkashyap** [comment]
Thanks Eric ... What I am trying to do is build an existing solution on my mac (it builds fine on Windows). Running nuget with mono works.
Which msbuild is recommended to try to build my solution - I tried corefx/Tools/msbuild.sh but that gives an error - Task failed because "corerun" was not found.

Is there some place I can read about the right way to go to port an existing C# app from windows to mac?

**Comment by mellinoe** [comment]
Well, it sort of depends on what you are trying to do. Are you trying to run your program on mono? If so, then this probably isn't the right place, and I'm not sure how to help in that direction. If you are trying to port your application to .NET Core, then you will have the most luck right now using the `dotnet` CLI tooling, [over here](https://github.com/dotnet/cli). We are going to be moving the tooling for building .NET Core apps over to MSBuild soon, but that stuff hasn't landed yet. There are [ways to do it now](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/target-dotnetcore-with-msbuild.md), but it's less pretty than it will be in the future. It's also going to require you have recent versions of VS, MSBuild, etc. and isn't easy to get working on other OS's (keyword *yet*). Right now the recommended thing to do is use the `dotnet` CLI and build your project using the project.json-based tooling.

**Comment by ckkashyap** [comment]
Thanks Eric for the links...I'll give them a shot.
