### ISSUE TITLE
EventSources do not include Messages on Linux through LTTNG

### ISSUE THREAD

**Issue by davmason** [dotnet/coreclr#6632]
Consider the following event:
`        [Event(1, Message = "Hello World {1}")]
        public void HelloWorld(string name)
        {
            WriteEvent(1, name);
        }
`

On Linux if written out to lttng, you get the following: `DotNETRuntime:EventSource: { cpu_id = 2 }, { vpid = 51678, vtid = 51678, procname = "dotnet" }, { EventID = 1, EventName = "HelloWorld", EventSourceName = "FabricEvents", Payload = "{\"name\":\"samplename\"}" }`

There is no way to know what the Message field (i.e. `"Hello World {1}"`) is of the original Event.

We should put this as part of the serialization for EventSource messages through lttng.

**Comment by lt72** [comment]
@Davmason: can you look into this issue and see what the cost of fixing it is?

**Comment by vancem** [comment]
Including the stack trace 

### 00007FFFFFFF4FE0 00007FFF7C9E712B System.Diagnostics.Tracing.EventWrittenEventArgs.get_Level()
00007FFFFFFF4FF0 00007FFF7D038929 System.Fabric.Common.Tracing.NativeEventListener.OnEventWritten(System.Diagnostics.Tracing.EventWrittenEventArgs)
00007FFFFFFF50A0 00007FFF7C92ADF3 System.Diagnostics.Tracing.EventSource.WriteStringToAllListeners(System.String, System.String)
00007FFFFFFF5100 00007FFF7C92E838 System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage(System.String, Boolean)
00007FFFFFFF5190 00007FFF7C92BA1C System.Diagnostics.Tracing.EventSource.DoCommand(System.Diagnostics.Tracing.EventCommandEventArgs)
00007FFFFFFF7500 00007ffff6163d4d [HelperMethodFrame: 00007fffffff7500]
00007FFFFFFF7620 00007FFF7CC60D5E System.Diagnostics.Tracing.ManifestBuilder.ManifestError(System.String, Boolean)
00007FFFFFFF7640 00007FFF7C960D44 System.Diagnostics.Tracing.ManifestBuilder.GetOpcodeName(System.Diagnostics.Tracing.EventOpcode, System.String)
00007FFFFFFF7680 00007FFF7C95E5AB System.Diagnostics.Tracing.ManifestBuilder.StartEvent(System.String, System.Diagnostics.Tracing.EventAttribute)
00007FFFFFFF76C0 00007FFF7C92D4A2 System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors(System.Type, System.String, System.Diagnostics.Tracing.EventSource, System.Diagnostics.Tracing.EventManifestOptions)
00007FFFFFFF78B0 00007FFF7C92BC26 System.Diagnostics.Tracing.EventSource.EnsureDescriptorsInitialized()
00007FFFFFFF7970 00007FFF7C92B64F System.Diagnostics.Tracing.EventSource.DoCommand(System.Diagnostics.Tracing.EventCommandEventArgs)
00007FFFFFFF79D0 00007FFF7C92B58F System.Diagnostics.Tracing.EventSource.SendCommand(System.Diagnostics.Tracing.EventListener, Int32, Int32, System.Diagnostics.Tracing.EventCommand, Boolean, System.Diagnostics.Tracing.EventLevel, System.Diagnostics.Tracing.EventKeywords, System.Collections.Generic.IDictionary`2<System.String,System.String>)
00007FFFFFFF7A30 00007FFF7C95A28C System.Diagnostics.Tracing.EventListener.EnableEvents(System.Diagnostics.Tracing.EventSource, System.Diagnostics.Tracing.EventLevel, System.Diagnostics.Tracing.EventKeywords, System.Collections.Generic.IDictionary`2<System.String,System.String>)
00007FFFFFFF7A60 00007FFF7C95A21F System.Diagnostics.Tracing.EventListener.EnableEvents(System.Diagnostics.Tracing.EventSource, System.Diagnostics.Tracing.EventLevel)
00007FFFFFFF7A70 00007FFF7D031786 System.Fabric.Common.Tracing.FabricEvents..ctor()
00007FFFFFFF7AE0 00007FFF7D0308E6 System.Fabric.Common.Tracing.FabricEvents..cctor()
00007FFFFFFF7DF0 00007ffff6175097 [GCFrame: 00007fffffff7df0]
00007FFFFFFF8760 00007ffff6175097 [HelperMethodFrame: 00007fffffff8760]
00007FFFFFFF8E30 00007FFF7D030839 System.Fabric.Common.Tracing.FabricEvents.get_Events()
00007FFFFFFF8E50 00007FFF7D02D1D6 System.Fabric.Common.Tracing.FabricEvents+ExtensionsEvents..cctor()
00007FFFFFFF9FC0 00007ffff6175097 [GCFrame: 00007fffffff9fc0]
00007FFFFFFFA930 00007ffff6175097 [HelperMethodFrame: 00007fffffffa930]
00007FFFFFFFB000 00007FFF7D02D0EB System.Fabric.Common.Tracing.FabricEvents+ExtensionsEvents.GetEventSource(System.Diagnostics.Tracing.EventTask)
00007FFFFFFFB030 00007FFF7D02D06F System.Fabric.FabricDeployer.DeployerTrace..cctor()
00007FFFFFFFB330 00007ffff6175097 [GCFrame: 00007fffffffb330]
00007FFFFFFFBCA0 00007ffff6175097 [HelperMethodFrame: 00007fffffffbca0]
00007FFFFFFFC370 00007FFF7D02CFE6 System.Fabric.FabricDeployer.DeployerTrace.WriteInfo(System.String, System.Object[])
00007FFFFFFFC390 00007FFF7CDB937B System.Fabric.FabricDeployer.Program.Main(System.String[])
00007FFFFFFFC728 00007ffff6175097 [GCFrame: 00007fffffffc728]
00007FFFFFFFCB30 00007ffff6175097 [GCFrame: 00007fffffffcb30]

It shows that this particular callback was trying to report a error when it failed.   Thus the interesting problem is what that failure is.

**Comment by vancem** [comment]
I believe I understand the problem.   The repro is that you need to have an eventListener that calls EventWrittenEventArgs.Level and have a bad EventSource that will be caught when the EventSource starts up.    The EventSource tries to log this error but the EventSource is not quite set up enough for the EventWrittenEventArgs.Level callback to work (in particular m_eventData is null)

I believe the fix is straightforward.   Properties of EventWrittenEventArgs already have a case to handle TraceLogging style events (which have no m_eventData either).  These are distinguished because their EventID is , 0.   By changing this test to be <= 0 we opt in the 0 event, which is the one that is used to log these messages.     There are 6 places to update, but it is trivial.

I will see about a pull request.   

You an work around this by fixing the issue that causes the error message.  No error message, no event, which makes things 'just work'.

**Comment by vancem** [comment]
Pull request #7361 addresses this issue.   Before this change the LTTng payload had a JSON object that has Key-Value pairs where the keys are the names of the event properties and the values are the values of those properties.  

The change above will add a new field called

      EventSource_Message

whose value is the UNSUBSITUTED message associate with the event.  Thus if you have an event 

class MyEventSource : EventSource  {

    [Event(1, Message="MyEvent Message = {0}"]
    public void MyEvent(string value) { WriteEvent(1, value); }
}

Then the key-values will include

     "EventSource_Message" : "MyEvent Message = {0}"

**Comment by vancem** [comment]
This was resolved with 

commit 408aaf09accf61b8ffe6d5dee5e768f5b9b6245a
Author: Vance Morrison <vancemorrison@comcast.net>
Date:   Mon Sep 26 11:49:28 2016 -0700
    Add the serialization of the Message field when writting LTTng events on Linux.
