### ISSUE TITLE
Freebsd ELF binary type "0" not known.

### ISSUE THREAD

**Issue by udonne** [dotnet/coreclr#6650]
I try to build dotnet on a FreeBSD 10.3
Do i miss a package? linux_base is installed

Thanks for your help

`./build-native.sh
Unsupported OS 'FreeBSD' detected. Downloading ubuntu-x64 tools.
Installing dotnet cli...
Restoring BuildTools version 1.0.26-prerelease-00704-01...
ELF binary type "0" not known.
/tmp/git/corefx/init-tools.sh: Zeile 78: /tmp/git/corefx/Tools/dotnetcli/dotnet: Kann die Binärdatei nicht ausführen: Exec format error
ERROR: Could not restore build tools correctly. See '/tmp/git/corefx/init-tools.log' for more details.
Initializing BuildTools...
/tmp/git/corefx/init-tools.sh: Zeile 84: /tmp/git/corefx/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00704-01/lib/init-tools.sh: No such file or directory
ERROR: An error occured when trying to initialize the tools. Please check '/tmp/git/corefx/init-tools.log' for more details.`

`cat /tmp/git/corefx/init-tools.log
Running: /tmp/git/corefx/init-tools.sh
Installing 'https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-002733/dotnet-dev-ubuntu-x64.1.0.0-preview2-002733.tar.gz' to '/tmp/git/corefx/Tools/dotnetcli/dotnet.tar'
Running: /tmp/git/corefx/Tools/dotnetcli/dotnet restore "/tmp/git/corefx/Tools/1.0.26-prerelease-00704-01/project.json" --no-cache --packages /tmp/git/corefx/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
Running: /tmp/git/corefx/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00704-01/lib/init-tools.sh /tmp/git/corefx /tmp/git/corefx/Tools/dotnetcli/dotnet /tmp/git/corefx/Tools`

**Comment by X86BSD** [comment]
I stumbled across this error post on twitter but the issue shown above unless I am corrected is because you are trying to use a 64 bit Linux binary on FreeBSD which does not currently support 64 bit Linux binaries in it's Linux emulation yet. However I thought, maybe this has changed, that the dotnet folks had a group of BSD people that had CoreCLR building and running just fine on FreeBSD. I would probably do that rather than try and build the linux version under emulation since it obviously will not work as of yet.

**Comment by sigmundkreuzer** [comment]
That is exactly that tutorial where i have problems.

**Comment by sec** [comment]
@udonne the tutorial is a bit, out-of-date, but you should be able to compile native part on FreeBSD without errors:
`pkg install bash cmake libunwind gettext llvm38 icu krb5`
and then
`build.sh -clang3.8`
to build managed parts on Windows use `build.cmd freebsdmscorlib`

now for corefx:
`src/Native/build-native.sh freebsd x64 debug cmakeargs -DHAVE_IN_PKTINFO=0`
and managed under windows `build-managed.cmd -os=FreeBSD -SkipTests`

**Comment by wfurt** [comment]
The ELF 0 comes from attempt to execute Linux binaries. 
That can be fixed by running `# kldload linux64`.
That however is not sufficient to get Linux SDK working on FreeBSD. 

Current  2.x and master builds don't do this any more so I'm going to close this issue.
