### ISSUE TITLE
[Tracking]Provide a common directory (or another solution) where profiler writers can put their assemblies

### ISSUE THREAD

**Issue by kspawa** [dotnet/coreclr#6672]
For the full .NET Framework, we have the GAC where most of the profiler assemblies exist so that they are available for use in all apps. For .NET Core, we need to have a design such that there is either a common place or some other solution available to Profiler writers so that they do not have to jump through a lot of hoops to make their assemblies available to all applications. @noahfalk please add any more details in case you have thoughts on the design.

**Comment by noahfalk** [comment]
Just fyi, this is probably a dupe of https://github.com/dotnet/coreclr/issues/3894 : ) Given the additional discussion that has already occurred there perhaps we should close this one and use 3894 instead.

**Comment by kspawa** [comment]
Closing this and adding more info in #3894.
