### ISSUE TITLE
Tuple.GetHashCode needs to be updated to match ValueTuple's implementation

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#6697]
I made changes awhile ago to change the `ValueTuple.GetHashCode` implementation that were recently merged: dotnet/corefx#8964. The implementation in Tuple probably needs to be updated as well. Unfortunately I'll be away from my x64 Windows computer for about a week, so I'm unable to verify/test these changes until I get back.

**Comment by jamesqo** [comment]
Note that this will probably have to be ifdef'd under `FEATURE_CORECLR`. I think I saw an answer to an SO question once that recommended

```cs
return Tuple.GetHashCode(_field1, _field2, ...).GetHashCode();
```

as an overridden GetHashCode implementation to newbies, so this may be more likely to be breaking. (can't find the answer though)

**Comment by jamesqo** [comment]
Also using `EqualityComparer<T>.Default` could be breaking, since it looks like both `Tuple.Equals` and `GetHashCode` currently determine equality using [`EqualityComparer<object>`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Tuple.cs#L129), which does boxing for valuetypes. Very unfortunate.

cc @omariom

**Comment by DemiMarie** [comment]
There needs to be no boxing for value types here.

**Comment by omariom** [comment]
> Also using  `EqualityComparer<T>.Default`  could be breaking, since it looks like both  Tuple.Equals  and  GetHashCode  currently determine equality using  `EqualityComparer<object>` , so this will be breaking if the  `IEquatable<T>`  implementation is different from the  Equals(object)  one.

IMO, a type with different implementations of `object.Equals` and `IEquatable.Equals` is already broken :)
For example, it behaves differently in `Dictionary` and `Hashtable`.
