### ISSUE TITLE
CI: One or more packages are incompatible with .NETFramework,Version=v4.5

### ISSUE THREAD

**Issue by ghost** [dotnet/coreclr#6716]
A CI job http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x86_ryujit_checked_windows_nt_prtest/2859/ failed with:

> One or more packages are incompatible with .NETFramework,Version=v4.5.

Previously spotted by @dagood at https://github.com/dotnet/coreclr/pull/6479#issuecomment-235642555.

**Comment by dagood** [comment]
I don't know for sure if this is how Jenkins works, but I spotted a pattern for `.*(One or more packages are incompatible.*)`. Maybe the difference between a success and failure is whether or not the restore task logs that message to a place where Jenkins can pattern match it.

Something to look into is whether there's a newer version of `xunit.runner.msbuild` that fixes the issue so this error doesn't have to be ignored anymore.

**Comment by jasonwilliams200OK** [comment]
> whether there's a newer version of `xunit.runner.msbuild`

seems like there is 2.2 beta: http://www.nuget.org/packages/xunit.runner.msbuild/2.2.0-beta2-build3300 (since nuget is still using 2.1.0: https://github.com/NuGet/NuGet.Client/blob/6a340b5/.nuget/packages.config#L4)

**Comment by dagood** [comment]
This shouldn't happen anymore in master after merging https://github.com/dotnet/coreclr/pull/6791.
