### ISSUE TITLE
C#/VB UWP App failed to debug launch on Emulator

### ISSUE THREAD

**Issue by cshung** [dotnet/coreclr#6719]
When running UWP with the CoreCLR in emulator, the debuggee stucks. It does launch successfully without using the debugger.

**Comment by mikem8361** [comment]
It looks like you need to just wait longer for the app to start.  It is slow almost painfully slow to start, but it does eventually start for me.  This is with x86 on the "10.0.10586.0 WVGA 4 inch 512MB" emulator. The 1GB emulator does starts little faster.
