### ISSUE TITLE
Document how to build SOS Plugin on OSX

### ISSUE THREAD

**Issue by ellismg** [dotnet/coreclr#673]
On Linux this happenes automatically if you apt-get the correct packages.  What's the right way to do it on OSX?

/cc @pgavlin who I believe has multiple ways of doing this.

**Comment by kangaroo** [comment]
Its a pain currently.  You need to manually get a checkout of the headers, and point LLDB_INCLUDE_DIR there.  LLDB_LIB_DIR gets pointed to the private LLDB.framework in Xcode.

I'm not particularly happy about the current status, but not entirely sure yet what should be done to improve it either.

**Comment by ellismg** [comment]
Thanks!  At a minimum I would like to go through the painful process on our CI machines so we check the plugin with PRs and produce it in our builds.

Would it be reasonable to provide something like a homebrew recipe which actually fetched the headers and built the LLDB components you needed and then have that be an optional thing you could brew install before building?

**Comment by kangaroo** [comment]
If we're willing to take a dependency on homebrew, we can use the lldb their llvm package already provides:

```
brew install llvm --with-lldb --with-clang
```

With that we should be able to do:

```
LLDB_LIB_DIR=/usr/local/opt/llvm/lib
LLDB_INCLUDE_DIR=/usr/local/opt/llvm/include
```

**Comment by ellismg** [comment]
Thanks, @kangaroo.  I gave this a shot and while it built, it seems there are problems at runtime with this approach.  Trying to start the DAC was failing, and it looked like the problem was when it was trying to call LLDB methods via DebugClient, we were getting back invalid data.  I assume this is due to a mismatch between the LLDB I was using (from XCode) and the one I was building against (Homebrew).  I also was unable to use the homebrew lldb to debug things, since it couldn't figure out how to find debugserver.

I did use your instructions to point `LLDB_LIB_DIR` to the private framework and use the headers provided by homebrew, and things worked.

I'll try to get our CI system set up to do this so at least our official builds produce these libraries.

**Comment by kangaroo** [comment]
@ellismg I'm not surprised that apple's lldb didn't work with the plugin built against home-brew.  If we're going to go the 'brew' route, you should use that lldb which should be in /usr/local/opt/llvm/bin/lldb iirc.

**Comment by ellismg** [comment]
As part of this work we should also get whatever we decide to use building in the CI system.

**Comment by mikem8361** [comment]
Matt, I take this one.  I'm currently trying to figure out how to get my OSx lldb build to work and hopefully can document the process to build once I get it figured out.

**Comment by vors** [comment]
@mikem8361 any luck with it?

btw, converted sos plugin docx file to md https://github.com/dotnet/coreclr/pull/3097
