### ISSUE TITLE
PATENTS.TXT does not cover CoreCLR extensions to the MSDN APIs

### ISSUE THREAD

**Issue by DemiMarie** [dotnet/coreclr#6730]
PATENTS.TXT does not cover CoreCLR extensions to the MSDN APIs.  One example that I know is patented is the hosting API, and a Unix version of said API would not be covered by the patent promise.

**Comment by jkotas** [comment]
cc @martinwoodward @richlander

**Comment by DemiMarie** [comment]
One solution that would solve the problem permanently would be to use the patent grant from the Apache License, or to dual-license under MIT/Apache 2 (like Rust).

**Comment by DemiMarie** [comment]
PATENTS.TXT also does not cover CoreCLR to the extent that CoreCLR has bugs that cause it to not conform to the ECMA standard or the MSDN docs.

**Comment by martinwoodward** [comment]
Apologies - I'm not quite sure I understand which API's you are referring to by 'MSDN API's' but the PATENTS.TXT is fairly explicit in that it refers to the code contributed to the CoreCLR (along with CoreRT) repos so we're pretty happy with it alongside the MIT license of the repo and the [.NET Foundation CLA](http://cla2.dotnetfoundation.org). Note that all people (including Microsoft engineers) have to sign the CLA when making significant contributions.

We discussed the license extensively at the time we were creating the project and settled on MIT for maximum compatibility with other open source licenses. The MIT or Apache 2 dual license approach is an interesting one, but the decision we made at the time was (for better or worse) to try and keep things simple.

FYI - the ECMA 334 committee have met recently to update the spec. You can follow along with the drafts [here](http://www.ecma-international.org/memento/TC49-TG2M.htm).

Many thanks!

Martin.

**Comment by jasonwilliams200OK** [comment]
> CoreCLR has bugs that cause it to not conform to the ECMA standard

In the interested of seeking knowledge, does this also hold if v8 or Gecko have bugs in ECMA's standard defined for JavaScript? Or this logic exclusively applied to Microsoft family of products? :smirk:

**Comment by danmosemsft** [comment]
@ghost does not exist, this seems resolved so I'll close. If not please reopen
