### ISSUE TITLE
Add Task.IsCompletedSuccessfully

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#6732]
`Task` already has a few shortcut properties: `IsFaulted`, `IsCancelled`, `IsCompleted`. These are useful because they provide a way to write certain conditions very succinctly.

The only such property missing is `IsCompletedSuccessfully`. It should be added.

The workarounds are a little awkward: `t.Status == TaskStatus.RanToCompletion` and `!t.IsFaulted && !t.IsCanceled`. They are longer, don't express meaning well and sometimes are written incorrectly (e.g. forgetting about cancellation).

Is there a reason `IsCompletedSuccessfully` can/should not exist?

**Comment by omariom** [comment]
`IsSucceeded`?

**Comment by benaadams** [comment]
`IsCompletedSuccessfully` would match `ValueTask` which has it

https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Extensions/src/System/Threading/Tasks/ValueTask.cs#L135-L136

**Comment by GSPP** [comment]
Yes, I think Task and ValueTask should have as much common surface area as possible to make it easy to switch between the two.

It might even make sense to add a `Status` property to `ValueTask` and synthesize a suitable status in case the object is not based on a task.

**Comment by jamesqo** [comment]
Since `ValueTask` has it, 👍

**Comment by GSPP** [comment]
I believe mscorlib types are supposed to be discussed here. I always check the file system on Github first to see where a given type lives. @jamesqo

**Comment by omariom** [comment]
> `IsCompletedSuccessfully` would match `ValueTask` which has it

Is it late to change ValueTask? )

**Comment by jasonwilliams200OK** [comment]
> `IsSucceeded`?

`HasSucceeded`?

*just bikesheding ..* :)

**Comment by gkhanna79** [comment]
Issue moved to [dotnet/corefx #16745](https://github.com/dotnet/corefx/issues/16745) via [**ZenHub**](https://www.zenhub.com/)
