### ISSUE TITLE
Feature request: Iterated register coalesing register allocator

### ISSUE THREAD

**Issue by DemiMarie** [dotnet/coreclr#6739]
This is a feature request for a graph coloring register allocator – specifically, using iterated register coalescing.  This might need to be opt-in.

**Comment by pgavlin** [comment]
cc @russellhadley @sivarv @CarolEidt @dotnet/jit-contrib

**Comment by pgavlin** [comment]
I don't think that this is actionable in the near- or medium-term, so I am going to close this issue for now while we are concentrated on pushing the existing allocator as far as we can.
