### ISSUE TITLE
Optimization discussion: Shrinking Dictionary by 3 fields

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#6750]
Right now [Dictionary](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Dictionary.cs) has quite a few fields in its layout:

```cs
public class Dictionary<TKey, TValue>
{
    int[] buckets; // 1 word
    Entry[] entries; // 1 word
    int count; // 4 bytes
    int version; // 4 bytes
    int freeList; // 4 bytes
    int freeCount; // 4 bytes
    IEqualityComparer<TKey> comparer; // 1 word
    KeyCollection keys; // 1 word
    ValueCollection values; // 1 word
    object _syncRoot; // 1 word
}
```

This totals to 48 + 16 == 64 bytes for x64, for the fields alone. In fact [in my test](https://dotnetfiddle.net/vDDU0p) I'm finding the entire object (including method table and all) to total to 80 bytes, and that doesn't even include any of the arrays/other objects that are being allocated.

I'm experimenting [**here**](https://github.com/dotnet/corefx/compare/master...jamesqo:patch-2) with cutting out those last 4 fields and replacing them with a single field, `object comparerOrCollections`. Basically how it works is, if `Keys` / `Values` / `SyncRoot` has not been called yet, it will be set to the equality comparer. Otherwise, if `Keys` / `Values` are called (which any code that cares about perf [really shouldn't](https://github.com/dotnet/corefx/pull/7765#discussion_r59931593)), it's going to create a new, intermediate object that is responsible for lazy-initialization of `Keys` / `Values`. Since this intermediate object is never going to be seen by the outside world, we can improvise further and use it as the `SyncRoot`.

Obviously this will incur a bit more overhead for `Keys` / `Values`, as there will be an additional allocation + `CompareExchange` on lazy initialization, not to mention another pointer indirection. This could also affect usage of `comparer` since we don't know exactly which field it's in until we typecast.

The payoff for all of this is a 33% reduction in size of Dictionary (80 bytes -> 56).

Thoughts? @mikedn, @omariom, @benaadams? (Note the commit I linked to is basically a draft, I have not run tests with it yet since I don't want to put too much work in if this is not the way to go.)

**Comment by mikedn** [comment]
> I'm experimenting here with cutting out those last 4 fields and replacing them with a single field, object comparerOrCollections.

I don't think that a change that increases the cost of accessing the comparer object is a good change. All interesting dictionary operations use the comparer.

> which any code that cares about perf really shouldn't

That's taking things out of context. While it is true that it doesn't make much sense to use the keys and values collections with `foreach` that doesn't mean that there aren't other valid uses of those collections. Anytime you need an IEnumerable of keys or values you can just use those collections directly without creating an intermediary list or array.

Anyway, these collections are not commonly used so maybe the added cost of a cast is not a problem, especially that the cast is fast due to these type being sealed.

> Since this intermediate object is never going to be seen by the outside world, we can improvise further and use it as the SyncRoot

SyncRoot is a very unfortunate leftover from the .NET 1 days. It would be nice to get rid of it but I'm concerned that mixing it with key and values collection will add significant complexity due to SyncRoot requiring thread safety. I suppose we'll see.

**Comment by omariom** [comment]
Leave `comparer` alone! :smile: 
It could be used  for devirtualization of `Equals` and `GetHashCode` calls when [ intrinsification of `EqualityComparer.Default`](https://github.com/dotnet/coreclr/issues/6688) is ready.

**Comment by mikedn** [comment]
>It could be used for devirtualization of Equals and GetHashCode calls when intrinsification of EqualityComparer.Default is ready

It seems unlikely. `Dictionary` accepts a user specified comparer of type `IEqualityComparer<T>` so one way or another you're still dealing with a comparer object of unknown type.

**Comment by omariom** [comment]
Most of the times the passed comparer is null so we could replace 
```C#
this.comparer = comparer ?? EqualityComparer<TKey>.Default;
```
with 
```C#
// in ctor
if (comparer != null && comparer != EqualityComparer<TKey>.Default)
{
    this.comparer = comparer;
}
// and then
private bool KeysEqual(TKey k1, TKey k2)
{
    if (comparer != null)
       return comparer.Equals(k1, k2);
    return EqualityComparer<TKey>.Default.Equals(k1, k2);
}
```

I think the scenario when custom comparer is passed in will not suffer much.

**Comment by benaadams** [comment]
@jamesqo might want to look at how Task handles `m_contingentProperties`

**Comment by jamesqo** [comment]
Closing, as the PR was closed (see there for why).
