### ISSUE TITLE
[ARM/Linux] incorrect use of symbolic name _TARGET_ARM_  instead of _ARM_ in pr6700

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#6755]
My previous PR #6700 does not work as intended, due to wrong symbolic name `_TARGET_ARM_`.
`_ARM_ `should be applied instead of `_TARGET_ARM_ `here.

This time, I ran tests with caution and it works.

**Comment by hqueue** [comment]
It seems that src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp is built more than once for different purpose as described below.

1. coreclr/bin/obj/Linux.arm-softfp.Release/src/coreclr/hosts/unixcoreruncommon
    Only -D_ARM_ is defined.

2. coreclr/bin/obj/Linux.arm-softfp.Release/src/ToolBox/SOS/Strike
    Both -D_ARM_ and -D_TARGET_ARM_=1 are defined.

I couldn't understand how it works yet.

**Comment by jkotas** [comment]
> assuming  `_ARM_`  is for host and  `_TARGET_ARM_`  is for target but I found that there is also  `_HOST_ARM_` 

Your assumption is correct. `_HOST_ARM_` is same as `_ARM_`.
