### ISSUE TITLE
The type or namespace name 'HandleRef' does not exist in the namespace 'System.Runtime.InteropServices'

### ISSUE THREAD

**Issue by dlahlou** [dotnet/coreclr#6758]
I'm trying to port a project from mono to dotnet, and I'm struggling to reference System.Runtime.InteropServices.HandleRef used by SWIG. I believe the one to be used is [here](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.handleref%28v=vs.110%29.aspx) , but I don't know how I can do this.
My project.json looks like this :
`"frameworks": {`
`"net45": {`
`"dependencies": {`
`...`
 `"System.Runtime.InteropServices": "4.1.0",`
`...`
`}`
`},`
`"netcoreapp1.0": {`
`"dependencies": {`
`"Microsoft.NETCore.App": {`
`"type": "platform",`
`"version": "1.0.0"`
`}`
`},`
`"imports": "dnxcore50",`
`}`
`}`

Thank you

**Comment by jkotas** [comment]
`HandleRef` is not available in .NET Core right now, but it should be coming back as part of netstandard 2.0 work.

cc @yizhang82 @danmosemsft

**Comment by dlahlou** [comment]
Thank you for your reply @jkotas

**Comment by jkotas** [comment]
Fixed for .NET Standard 2.0 by https://github.com/dotnet/corefx/issues/12162

See https://github.com/dotnet/core/blob/master/roadmap.md for ship dates.
