### ISSUE TITLE
[ARM/Linux] Collator is cloned on initialzation which is expensive in terms of the dirty memory

### ISSUE THREAD

**Issue by papaslavik** [dotnet/coreclr#6760]
It's found on an ARM device that about 900K of Private_Dirty memory is allocated at each application run due to string comparison happening in the very initialization process.

The exact symptom looks like the following:

in the file src/mscorlib/corefx/System/Globalization/TextInfo.Unix.cs there's a function NeedsTurkishCasing and it is called on the initialization.

The function body has a compare call
`CultureInfo.GetCultureInfo(localeName).CompareInfo.Compare("\u0131", "I", CompareOptions.IgnoreCase)`

and the `CompareOptions.IgnoreCase` option then leads to the collator cloning:
see src/corefx/System.Globalization.Native/collation.cpp `GetCollatorFromSortHandle` invoked from 
`GlobalizationNative_CompareString`

Perhaps the right solution would be to prepare the collators in advance and just map it sharing among all the processes.

@brucehoult @Dmitri-Botcharnikov @lemmaa @leemgs @wateret

**Comment by stephentoub** [comment]
cc: @ellismg, @eerhardt

**Comment by eerhardt** [comment]
What if we just lazy-loaded the value, i.e. if we didn't calculate `m_needsTurkishCasing` until it is actually used?  It looks like it is only used in the `ChangeCase` method, which is only called from `ToLower` and `ToUpper` methods.

**Comment by papaslavik** [comment]
I think it would be good.

But anyway any use of Compare  CompareOptions.IgnoreCase would cause the same RAM overhead.
Although it doesn't seem to be called much at startup.

**Comment by papaslavik** [comment]
The simple fix merged.
