### ISSUE TITLE
NullReferenceException when using EventListener on linux in some cases

### ISSUE THREAD

**Issue by novino** [dotnet/coreclr#6768]
I'm getting foll: exception when using EventListener on linux for CoreClr in our code (ServiceFabric)

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Diagnostics.Tracing.EventWrittenEventArgs.get_Level()
   at System.Fabric.Common.Tracing.NativeEventListener.OnEventWritten(EventWrittenEventArgs eventData)

My EventListener is as follows and i get the callback on OnEventWritten, upon checking eventData wasn't null, however when trying to get any of the properties of eventData i get null ref. exception.

    internal class NativeEventListener : EventListener
    {
        protected override void OnEventWritten(EventWrittenEventArgs eventData)
        {
            Console.WriteLine("Event recieved");
            try
            {
                if (eventData == null)
                {
                    Console.WriteLine("EventData was null");
                    return;
                }

                Console.WriteLine("EventLevel = {0}, EventOpcode = {1}", eventData.Level, eventData.Opcode);
            }
            catch (Exception e)
            {
                Console.WriteLine("{0}", e);
            }
//            TraceViaNative.Write(eventData.Task.ToString(), eventData.EventName, eventData.EventId.ToString(), (ushort)eventData.Level, FabricEvents.GetMessageFromEventData(eventData));
        }
    }

CoreClr dotnet version on linux is 1.0.0-preview3-003171
When writing a simple standalone hello eventsource/eventlistener example we're not able to reproduce this problem with same dotnet version.

However when used as part of our service fabric code this problem crops up.

**Comment by jkotas** [comment]
@davmason Is Linux eventsource maintained by you or somebody else?

**Comment by lt72** [comment]
David will look into this for the short term until we find a new owner.

**Comment by vancem** [comment]
This issue was fixed by commit #7359
