### ISSUE TITLE
Add Centos 6 support

### ISSUE THREAD

**Issue by agonzalezm** [dotnet/coreclr#6792]
I am trying to run .net core and powershell on Centos 6 but get error:

/usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.18' not found

Would be possible you add support for Centos6? Centos6 is used in lot of servers. You are supporting  and providing packages for last two version of Ubuntu and Ubuntu 14.04.

Would be great you support last two centos major version.

**Comment by pgavlin** [comment]
cc @ellismg @richlander

**Comment by nebulaeonline** [comment]
You need an updated glibc, because the 2.12 from the el6 branches is quite outdated.  This presents a problem as el6 kernels are "2.6.32" series.  I suspect that although Red Hat's kernels sport that version number, they have seen backports from newer kernels.  The major issue is that a glibc new enough to run dotnet core requires at least a 3.3 series kernel to build.  Now glibc can be built on a more modern distribution (same arch/bitness), as it is "guaranteed" to run on any kernel older than the one it was built with.  It's about 2-4 hours of work to rebuild glibc and stash the newer libc somewhere out of the way.  

Your other alternative is to simply follow the yellow brick road and see exactly what specific library imports target the newer glibc version(s) than you have available and to write workaround(s) / platform-specific patches.

I suspect that's the core of the issue here.  I'm sure Microsoft would love to get the core clr on el6, but tbh, it's hard enough on CentOS 7.  Server admins are likely not going to want to support a massively intrusive install like a new and completely unsupported parallel glibc, and Microsoft and the community don't want to litter the code with platform specific bits for pre-3.3 kernels.

**Comment by ckuhn203** [comment]
This is really disappointing. A number of VPS providers don't give you CentOS 7 as an option, only 6.
I understand why you wouldn't want to add support for an old version of an OS, but this does mean that dotnet core won't run on CentOS 6.

https://github.com/dotnet/cli/issues/3298

**Comment by joshfree** [comment]
Following up on an old issue.  Here's a link to @janvorli 's doc: [How to use .NET Core on RHEL 6 / CentOS 6](https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md).

**Comment by rubberduck203** [comment]
FWIW I’m running my Core apps in a Docker container. Works just fine.

**Comment by joshfree** [comment]
Thanks for following up @rubberduck203.  I'll close out this issue.

**Comment by agonzalezm** [comment]
great news! is not necessary to change glibc anymore? are there specific .net core rpms for centos 6 or you have to build from scratch?

**Comment by janvorli** [comment]
@agonzalezm the CentOS/RHEL 6 version is currently available as a preview runtime. There is no SDK yet, so you need to build your app on another Linux and target `rhel.6-x64` RID. 
There is no need to change glibc, this version of the runtime is build on CentOS 6, targeting the glibc that's present there. The only thing you need to build from sources and install on the target box is the CURL library. Please see my doc mentioned in one of the comments above for step by step instructions on preparing the runtime environment.

**Comment by maximusjunior** [comment]
@janvorli I've tried to build coreclr on Centos 6 (branch "release/2.1") following [these instructions](https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md) but no luck. Latest error I got and can't resolve is "Cannot find LLDB.h Try installing lldb-3.9-dev...".
Library llvm-dev installed, but there is no LLDB.h file nor lldb* in repos...

Highly appreciate any help or suggestions!

**Comment by janvorli** [comment]
@maximusjunior the doc is about preparing a runtime environment for running dotnet core on RHEL / CentOS 6, not for building it. For building, it is more involved. You need to build clang + lldb 3.9 yourself.
Fortunately, we have a Dockerfile that I can share and you can either use to build the stuff in docker container or just to make the steps from the Dockerfile manually on your Centos 6 machine.
The steps in the dockerfile prepare a build environment in which you can then build any of the dotnet repositories.
https://gist.github.com/janvorli/ea160cef429c88ff152c6923c3f0c1b9

**Comment by maximusjunior** [comment]
@janvorli thanks a lot! It works!

**Comment by maximusjunior** [comment]
@janvorli, sorry for disturbing you, but I got another error. I can't run MVC Core 2 application on this CentOS 6 instance. 
When I try to run webapp published with an option PublishWithAspNetCoreTargetManifest=false, I'm getting error:
 (Exception from HRESULT: 0x8007007E)) (Unable to load DLL 'libuv': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)) ---> System.DllNotFoundException: Unable to load DLL 'libuv': The specified module or one of its dependencies could not be found.
 
Without this option: 
  An assembly specified in the application dependencies manifest (MyApp.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml

Both errors occurs even when I run publish command on target machine with CentOS 6.

# dotnet --version
2.2.0-preview1-008003

# dotnet --info
.NET Command Line Tools (2.2.0-preview1-008003)

Product Information:
 Version:            2.2.0-preview1-008003
 Commit SHA-1 hash:  839eccbcaf

Runtime Environment:
 OS Name:     rhel
 OS Version:  6
 OS Platform: Linux
 RID:         rhel.6-x64
 Base Path:   /root/.dotnet/sdk/2.2.0-preview1-008003/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26116-04
  Build    : eeb3a84e2142aba791fe003564b8afd048c45ff9

# dotnet --list-runtimes
Microsoft.NETCore.App 2.1.0-preview1-26116-04 [/root/.dotnet/shared]
Microsoft.NETCore.App 2.0.5 [/root/.dotnet/shared]

# dotnet --list-sdks
2.2.0-preview1-008003 [/root/.dotnet/sdk]

Highly appreciate any help!

**Comment by janvorli** [comment]
@JohnRusk The RHEL 6 is special and is not supported by the portable runtime (alias targeting linux-x64). Please see my explanation here:
https://github.com/dotnet/cli/issues/9375#issuecomment-393843956
