### ISSUE TITLE
An unhandled exception of type 'System.ExecutionEngineException' occurred in Unknown Module

### ISSUE THREAD

**Issue by al1b** [dotnet/coreclr#6795]
1. Create a simple dotnet core console application.
2. Run the project, it will works fine
3. Update `Microsoft.NETCore.App` to version _1.0.0_ with nuget.

```
  "dependencies": {
    "Microsoft.NETCore.App": "1.0.0"
  },
```
1. Compile the project will be failed, it does need to specify runtimes in `project.json' like below.

```
  "runtimes": {
    "win10-x64": { }
  },
```
1. Compile the project and run, project will be compiled but will throw the exception below:

```
An unhandled exception of type 'System.ExecutionEngineException' occurred in Unknown Module
```

**My simple project code:**

```
namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!"); // error will happen
        }
    }
}
```

**Comment by al1b** [comment]
I think I found the problem.

`project.json` should be something like below:

```
{
  "version": "1.0.0-*",

  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": { 
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "NETStandard.Library": "1.6.0"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```

I removed `runtimes` section and I defined `type: platform` for `Microsoft.NETCore.App` and problem solved.

**Comment by gkhanna79** [comment]
Correct - M.N.App is a metapackage and "type: Platform" is how this is indicated when building a portable .NET Core app.

CC @weshaggard

**Comment by gkhanna79** [comment]
Can this issue be closed @al1b ?

**Comment by al1b** [comment]
@gkhanna79 Yes, it can be closed.
