### ISSUE TITLE
Change constructors of Dictionary<TKey, TValue> class

### ISSUE THREAD

**Issue by stas-sultanov** [dotnet/coreclr#680]
I wold like to suggest  to replace following constructors of `Dictionary<TKey, TValue>` class
`public Dictionary(IDictionary<TKey,TValue> dictionary)`
`public Dictionary(IDictionary<TKey,TValue> dictionary, IEqualityComparer<TKey> comparer)`

with following
`public Dictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection)`
`public Dictionary(IEnumerable<KeyValuePair<TKey, TValue>> collection, IEqualityComparer<TKey> comparer)`

reason: can not create `Dictionary<TKey, TValue>` from `IReadOnlyDictionary<TKey, TValue>`

**Comment by Therzok** [comment]
I wouldn't go as far as replacing them. This can cause performance issues for some applications which use those constructors.

Wouldn't a more valid proposal be to add additional constructors from IReadOnlyCollection<KeyValuePair<TKey, TValue>> and IEnumerable variant?

**Comment by stas-sultanov** [comment]
I believe that it is possible to make those constructors to work as fast as current one
take a look on implementation of `public List(IEnumerable<T> collection)` constructor

**Comment by iamthemovie** [comment]
I agree with @Therzok, adding another set of constructors would surely be a better idea?

In the .NET framework ConcurrentDictionary has the constructors you're suggesting as well.

**Comment by Therzok** [comment]
Well, if it checks for IDictionary/IReadOnlyDictionary/ICollection<KeyValuePair<TKey, TValue>> internally before enumerating, I'm totally okay with that.

Thanks @stas-sultanov forgot that List did that internally.

**Comment by MattWhilden** [comment]
@ellismg Who from your side can take a look?

**Comment by ellismg** [comment]
Thanks for the suggestion, we should track this in the CoreFX repo  I have written up a speclet there and marked the issue as Ready for API review.  Please provide feedback over there, and I'll close this up.
