### ISSUE TITLE
Implement new System.Globalization Functions

### ISSUE THREAD

**Issue by sokket** [dotnet/coreclr#6803]
Implement the stubbed out System.Globalization functions in `src\mscorlib\corefx\System\Globalization\STUBS.cs`

And
`src\mscorlib\src\System\Globalization\STUBS.cs`

And a native implementations for
`COMNlsInfo::nativeNormalizationInitNormalization`,
`COMNlsInfo::InternalGetNlsVersionEx`,
`COMNlsInfo::InternalGetSortVersion`

And uncomment the implementation for `IdnMapping::GetAscii` which requires VM code changes

**Comment by tarekgh** [comment]
thanks @sokket. I believe we exposed the normalization in the Globalization.Extensions so I am not sure if we still need to expose it here. but I'll follow up anyway. 

Sorting need to be implemented though.

**Comment by sokket** [comment]
Also - string normalization functions had to be #ifdef'd out in mscorlib/src/System/Text/Normalization.cs
