### ISSUE TITLE
Policy on "documentation comments" in code

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#6814]
In some places throughout mscorlib there are documentation-like comments explaining what the public API of the method does. For example, take [this code snippet in Encoding](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/Encoding.cs#L1350-L1361):

``` cs
        // Returns a Decoder object for this encoding. The returned object
        // can be used to decode a sequence of bytes into a sequence of characters.
        // Contrary to the GetChars family of methods, a Decoder can
        // convert partial sequences of bytes into partial sequences of characters
        // by maintaining the appropriate state between the conversions.
        //
        // This default implementation returns a Decoder that simply
        // forwards calls to the GetCharCount and GetChars methods to
        // the corresponding methods of this encoding. Encodings that require state
        // to be maintained between successive conversions should override this
        // method and return an instance of an appropriate Decoder
        // implementation.
        //

        public virtual Decoder GetDecoder()
        {
            return new DefaultDecoder(this);
        }
```

Searching for "returns a" in that file will reveal ~20 more of these comments I'm talking about.

There are literally hundreds of these comments all over the place in the source code, and IMO they add no value. They really don't tell us anything MSDN doesn't, and chances are if you're looking at the source code then you already have a general idea of what these functions do. Removing them could shave off probably a couple thousand lines of code.

@jkotas would it be okay to remove them?

**edit:** Just to be clear I am not talking about the XML-style `///` comments, like those found in Task, which actually get reflected in the compiled binary. Only the double-slash ones which are removed during compilation.

**Comment by jkotas** [comment]
These comments look fine to me. I do not see a reason why they should be removed.

> the XML-style `///` comments, like those found in Task, which actually get reflected in the compiled binary

These comments do not get reflected in the compiled binary.

Also check https://github.com/dotnet/corefx/issues/230

**Comment by jamesqo** [comment]
Ok, I misunderstood then, the `///` comments are not actually reflected in the binary. Still, I'm more OK with them than the `//` comments describing the public API of a method. I tend to see `//` comments as more of a description of how something works/an explanation for some kind of workaround, rather than documenting what the method does.

Maybe the `//` comments I linked to should be converted to XML doc ones.

**Comment by danmosemsft** [comment]
In general if there are poor comments, or missing comments, feel free to submit a PR to correct them.
