### ISSUE TITLE
Validate that dstCount is 0 on nodes which produce no value

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#6825]
If `GenTree::IsValue()` returns false, `dstCount` should be 0 (and conversely).

**Comment by CarolEidt** [comment]
This was suggested in the context of PR #6816, which fixed a bug in lowerarm64.cpp, where the `dstCount` was being set to 1 for `GT_RETURNTRAP`.

**Comment by jasonwilliams200OK** [comment]
Fixed by #6827.
