### ISSUE TITLE
XmlSerializer throws MethodAccessException if assembly has AllowPartiallyTrustedCallersAttribute

### ISSUE THREAD

**Issue by ngbrown** [dotnet/coreclr#6835]
I'm porting a library to the CoreCLR, and the assembly has this in AssemblyInfo.cs:

```
[assembly: AllowPartiallyTrustedCallersAttribute()]
```

The type being serialized had various attributes:

```cs
[System.CodeDom.Compiler.GeneratedCodeAttribute("HbmXsd", "3.2.0.1001")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("any", IsNullable=false)]
public class MySerializableType {
```

and `new XmlSerialize(typeof(MySerializableType))` throws a `MethodAccessException` on each of the attributes, even if I remove them one by one.

like this:

```
Attempt to access method System.Xml.Serialization.XmlTypeAttribute..ctor() in violation of security transparency rules failed.
```

When I remove `AllowPartiallyTrustedCallersAttribute` from the assembly, it works.  What should I do in this case?  

I saw that there was a fix for #5975 with the `SecurityTransparentAttribute`. Does it apply to this as well?

**Comment by jkotas** [comment]
#5975 should fix it. It would be nice to confirm it.

**Comment by gkhanna79** [comment]
@rahku Can we close this?

**Comment by rahku** [comment]
Works fine for me now.
