### ISSUE TITLE
Unittest `Interop/StringMarshalling/LPSTR`

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#6838]
This test always returns PASS even if it actually failed.
I was going to fix it by myself but the file `src/Interop/StringMarshalling/LPSTR/LPSTRTest.cs` is UTF-16 encoded and git thinks it is a binary file. So the changes are not shown on github. (Here is the changes. https://github.com/wateret/coreclr/commit/c4ff2e26a40e05b46b0f924d973ad11a18e815b3)
Is this file supposed to be in UTF-16?

/cc @tijoytom - the author of this file.

**Comment by gkhanna79** [comment]
CC @yizhang82

**Comment by danmosemsft** [comment]
@yizhang82 @tijoytom what is the importance for 2.0 & will it happen for 2.0? If not can you please move to Future.

**Comment by yizhang82** [comment]
Thanks @wateret for looking into it! I just created a PR out to make git treat those files properly (and fix the encoding) https://github.com/dotnet/coreclr/pull/11065. Once it's merged, @wateret please feel free to submit a new PR (if you are still interested to make the fix). Thanks!
@danmosemsft Moving to future.

**Comment by yizhang82** [comment]
Addressed by https://github.com/dotnet/coreclr/pull/11096
