### ISSUE TITLE
x86: JIT inliner assert running CscBench test

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#6844]
Same assert for both RyuJIT and legacy backend.

```
Assert failure(PID 17324 [0x000043ac], Thread: 9244 [0x241c]): Assertion failed 'm_IsPrejitRoot || (obs == InlineObservation::CALLSITE_TOO_MANY_LOCALS)' in 'Microsoft.CodeAnalysis.CommonReferenceManager`2[__Canon,__Canon][System.__Canon,System.__Canon]:ResolveMetadataReferences(ref,ref,byref,byref,byref,byref,byref,ref):struct:this' (IL size 1115)

    File: d:\gh\coreclr3\src\jit\inlinepolicy.cpp Line: 155
    Image: d:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

**Comment by BruceForstall** [comment]
cc @AndyAyersMS @kyulee1

**Comment by BruceForstall** [comment]
@kyulee1 Since this is inlining related, does it make sense for you to look at this? Is this something you will have time to look at?

**Comment by kyulee1** [comment]
Will take a look.

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib should we re-enable Roslyn collection in the superpmi test now that this is fixed?

**Comment by BruceForstall** [comment]
> @dotnet/jit-contrib should we re-enable Roslyn collection in the superpmi test now that this is fixed?

It wouldn't hurt, although the superpmi test collection only used Rosyln because it is large and diverse. In general, the set of superpmi test collection test assets was chosen to be "a few large tests", nothing more sophisticated than that.
