### ISSUE TITLE
Possible assert in COMModule::GetStringConstant

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#6856]
There's a dubious [assert](https://github.com/dotnet/coreclr/blob/45c827a17a746c5caba200594021ddb38743a711/src/vm/commodule.cpp#L772) in `COMModule::GetStringConstant`. `hr` can be set to a different value when the following exception happens:

> An unhandled exception of type 'System.Runtime.InteropServices.COMException' occurred in mscorlib.dll
> Additional information: No logical space left to create more user strings. (Exception from HRESULT: 0x80131198)

This should be triggered by:

            var assemblyBuilder = AppDomain.CurrentDomain.DefineDynamicAssembly(new AssemblyName("x"), AssemblyBuilderAccess.RunAndSave);
            var dynamicModule = assemblyBuilder.DefineDynamicModule("x");

            for (int i = 0; i < 1048576 * 16 * 2; i++)
            {
                dynamicModule.GetStringConstant(i.ToString());
            }

Since I don't have a checked CLR build that I can run I could not verify that the assert indeed fires but it should. So this might be a bug.

**Comment by jkotas** [comment]
It should be fine to remove the assert.

**Comment by mazong1123** [comment]
@jkotas How about remove the "hr == E_OUTOFMEMORY" but keep "!"Unknown failure in DefineUserString"" ? So the final result is:

```cpp
_ASSERTE(!"Unknown failure in DefineUserString");
```

**Comment by jkotas** [comment]
We use asserts for conditions that always hold. Assert should never fire. if the assert fires, it means there is a bug.

Since this can fail for number of different reasons, the right way to fix is to delete the assert.
