### ISSUE TITLE
CoreCLR pri1 test failure (baseservices._compilerservices_dynamicobjectproperties_TestAPIs_TestAPIs_._compilerservices_dynamicobjectproperties_TestAPIs_TestAPIs_cmd)

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#6857]
https://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1_prtest/4883/

MESSAGE:
\n\nReturn code: 1\nRaw output file: D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\Reports\baseservices\compilerservices\dynamicobjectproperties\TestAPIs\TestAPIs.output.txt\nRaw output:\nBEGIN EXECUTION\r\n "D:\j\workspace\x64_release_w---0575cb46\tests\..\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe" TestAPIs.exe \r\nTest threw unexpected exception:\nSystem.TypeLoadException: Could not load type 'CreateValueCallback' from assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.\r\n at Driver`2.GetValueValidations(K[] keys, V[] values)\r\n at TestAPIs.Main() in D:\j\workspace\x64_release_w---0575cb46\tests\src\baseservices\compilerservices\dynamicobjectproperties\testapis.cs:line 508\r\nExpected: 100\r\nActual: 102\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\n\nTo run the test:\n> set CORE_ROOT=D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\n> D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\baseservices\compilerservices\dynamicobjectproperties\TestAPIs\TestAPIs.cmd\n\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at baseservices._compilerservices_dynamicobjectproperties_TestAPIs_TestAPIs_._compilerservices_dynamicobjectproperties_TestAPIs_TestAPIs_cmd() in D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\TestWrappers\baseservices\baseservices.XUnitWrapper.cs:line 243

**Comment by gkhanna79** [comment]
@ramarag Can you PTAL?

**Comment by jkotas** [comment]
mscorlib.dll produced by the coreclr build has wrong forwarder for CreateValueCallback type. From ildasm of mscorlib.dll:

```
.class extern CreateValueCallback
{
  .class extern System.Runtime.CompilerServices.CompilerMarshalOverride
}
```

Instead, it should look like this:

```
.class extern CreateValueCallback
{
  .class extern System.Runtime.CompilerServices.ConditionalWeakTable`2
}
```

**Comment by jkotas** [comment]
@weshaggard This looks like a bug in the genfacades.exe tool.

**Comment by ramarag** [comment]
yes that is correct #6899 will fix it
