### ISSUE TITLE
Infra: is Documentation/project-docs/ci-trigger-phrases.md outdated?

### ISSUE THREAD

**Issue by choikwa** [dotnet/coreclr#6884]
I couldn't get \@ dotnet-bot to trigger jobs by trigger-phrases from Documentation/project-docs/ci-trigger-phrases.md

but test {full test string shown in the PR} seems to have worked. Is the doc outdated?

**Comment by jasonwilliams200OK** [comment]
> Test Windows_NT pri1

or

> @dotnet-bot, test Windows_NT pri1

or

> @dotnet-bot, test Windows_NT pri1 please

All of these work.

In the [trigger phrases doc](https://github.com/dotnet/coreclr/blob/d3cba55/Documentation/project-docs/ci-trigger-phrases.md), the right hand side is the actual trigger phrase in the list, for example the following:

> **Windows_NT x64 Release Priority 1 Build & Test:** "test Windows_NT pri1"

Refers `Test Windows_NT pri1` to be the actual trigger phrase.

Probably doc can be restructured a bit as it bolds the wrong side of the text, maybe use tables without bold text and quotes?

Suite Name | Trigger Phrase
---|---
Windows_NT x64 Release Priority 1 Build & Test | test Windows_NT pri1
Windows_NT x64 Release IL RoundTrip Build & Test | test Windows_NT ilrt

and so on ..

That would make it more clear IMO.

**Comment by choikwa** [comment]
Table would be nice.
Also, is this 
Ubuntu arm64 Release Cross Build: "test Ubuntu arm64"
an alias for
Linux ARM Emulator Cross Release Build?

I tried the Trigger Phrase to no avail, but the actual strings shown by the plugin worked.
For reference, https://github.com/dotnet/coreclr/pull/6801

**Comment by jasonwilliams200OK** [comment]
> Ubuntu arm64 Release Cross Build: "test Ubuntu arm64"
an alias for
Linux ARM Emulator Cross Release Build?

seems like that job doesn't exist by that name.

cc @wtgodbe

**Comment by choikwa** [comment]
Another design change that would be nice to have is if the build history was preserved. However, this work is probably for the Jenkins WebHook.

**Comment by BruceForstall** [comment]
I updated the documentation.
