### ISSUE TITLE
RyuJIT: fgOptimizeBranch loses bbFlags while duplicating the conditional block

### ISSUE THREAD

**Issue by echesakov** [dotnet/coreclr#6886]
When `fgOptimizeBranch` procedure duplicates the conditional basic block it does not copy flags of the `bDest` block to the `bJump` block. For example, if a flag `BBF_HAS_NEWOBJ` was set in `bDest`, but not in `bJump` when the branch optimization is done the flags of `bJump` will not reflect the fact that we have construction of new object in this block. We need to decide which flags we are going to copy over to the `bJump` block. The current workaround is copying the following flags: `BBF_HAS_NEWOBJ` , `BBF_HAS_NEWARRAY`, `BBF_HAS_NULLCHECK`.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib Volunteers?
