### ISSUE TITLE
Modify build.sh to have correct usage statement regarding AMD64/x64 BuildArch

### ISSUE THREAD

**Issue by vindicatorr** [dotnet/coreclr#689]
"x64" -> "amd64"
Otherwise, build fails at 100% with "no rule to make target 'x64'"

./build.sh
  Usage()
...
\- Line 6: "    echo "BuildArch can be: x64""
\+ Line 6: "    echo "BuildArch can be: amd64""
...

**Comment by linquize** [comment]
On Windows, it is called x64.
But on Linux, it is called amd64.

**Comment by vindicatorr** [comment]
I don't know the rationale between the two conventions, but I did specify it was in the "build.sh" file.

**Comment by MattWhilden** [comment]
We have "AMD64" and "x64" strings all over stuff inside the company... Mostly just accidental with no real hard rules. Am I to understand the convention for unix is "amd64"?

@pgavlin, care to comment?

**Comment by kangaroo** [comment]
@MattWhilden There is no convention on unix.  You'll see x86_64, amd64, and probably some other variants as well.

**Comment by MattWhilden** [comment]
Thanks for the reply @kangaroo.

Given that, do we just say, "Our convention for this project is x86/x64/ARM etc" or is it better for our scripts to unify some of the various names?

**Comment by vindicatorr** [comment]
I'll give my vote for whatever convention is most common in linux at the most basic level (kernel|compiler).
eg.
gcc (-march): https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Submodel-Options.html#Submodel-Options
I think that would be the architectures i386, x86_64, ARM, AArch64.

vs
kernel (arch): https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/arch/x86/configs?id=refs/tags/v4.0
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/arch?id=refs/tags/v4.0
Which would be i386, x86_64, arm, arm64

I vote "i386, x86_64, arm, arm64" if these are my only options.

My preference would be x86-32, x86-64 to denote intel/amd, then for arm, arm-32, arm-64.

Eventually 32-bit will become extinct and a future bit system (128) will push forth so you could drop the naming for *-32 and create *-128.
Essentially it would be <base/common-system-name>-<bits>.

**Comment by MattWhilden** [comment]
I'll follow up with folks here and see what the consensus is. I don't know how much will actually change or if we'll just document the current state with potential followup but I'll let you know.

**Comment by vindicatorr** [comment]
I think I'm needing to reiterate the OP is about a failed build due to the incorrect parameter used per "help" usage output.

"./build.sh" says to use "x64", but the build will fail at the very end.
The parameter needs to be "amd64" in order for the build to succeed.

**Comment by MattWhilden** [comment]
*facepalm* that's an even easier fix for now. Goes to show how easy it is to get distracted. That fix seems easy enough.
