### ISSUE TITLE
Consider avoiding using "which" to validate prereqs

### ISSUE THREAD

**Issue by mellinoe** [dotnet/coreclr#6904]
`which` is not universally available, and is not even installed by default in some cases (docker images). We should consider using a more universally available method for checking. Answers online recommend using `command` or `type` to do this.

**Comment by mellinoe** [comment]
[This](https://github.com/dotnet/coreclr/blob/master/build.sh#L5) is what I'm referring to, for clarity.

```sh
# resolve python-version to use
if [ "$PYTHON" == "" ] ; then
    if which python >/dev/null 2>&1
    then
       PYTHON=python
    elif which python2 >/dev/null 2>&1
    then
       PYTHON=python2
...
```

**Comment by adityamandaleeka** [comment]
I've opened a PR to address this.

**Comment by jkotas** [comment]
Rolled back in #7025
