### ISSUE TITLE
RyuJIT/x86 Windows work items

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#6927]
# Summary
This issue summarizes all the remaining work necessary to complete the RyuJIT/x86 porting effort. Most items are linked to GitHub issues tracking the individual item work.  Note that only work required to port to Windows is tracked below.  Tasks specifically required to enable Unix/x86 support are not tracked here.

# GitHub issue query
RyuJIT/x86 issues should be marked with labels "x86" and "CodeGen", and milestone 1.2.0. The query for this is:

https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3Ax86%20label%3ACodeGen%20milestone%3A1.2.0

# Implementation

## Silent Bad Code Generation (SBCG)
| Title  | Issue No. | Time Remaining|
| --------| ----- | --------------- |
|RyuJIT x86: SharpChess benchmark crashes bug CodeGen x86|#7113|7d|
|RyuJIT x86: Incorrect code motion in long compare codegen bug CodeGen x86|#7038|7d|
|RyuJIT x86: double alignment test failure bug CodeGen x86|#7008|7d|
|RyuJIT x86: audit "last use" bit during decomposition CodeGen x86|#6998|7d|
|RyuJIT x86: audit DecomposeLongs to ensure proper flags propagation bug CodeGen x86|#6931|7d|

## Asserts

| Assert  | Issue | Time Remaining|
| --------| ----- | --------------- |
|~~GC encoding expects EITHER lvRegister OR lvOnFrame~~|#3597|2d|
|~~JIT\SIMD\CircleInConvex assertion failure~~|#4992 |0d|
|~~!"Illegal TYP_LONG node in Lowering."~~|#6097|7d|
|EBP frame is sometimes required if overflow operations are present|#5699|7d|
|~~JIT inliner assert running CscBench test~~|#6844|7d|
|RyuJIT x86: assertion failed: '(op2 == idx) \|\| (op2->gtEffectiveVal() == idx)'|#6920|1d|
|RyuJIT x86: Assertion failed '!"gtArgEntryByNode: node not found"' bug CodeGen JitStress x86|#7144|7d|
|RyuJIT x86: Assertion failed '(farthestRefPhysRegRecord == nullptr) \|\| (farthestRefPosWeight < getWeight(refPosition))' bug CodeGen JitStress x86|#7143|7d|
|RyuJIT x86: Assertion failed 'regRecord->assignedInterval == nullptr' bug CodeGen JitStress x86|#7094|7d|
|RyuJIT x86: Assertion failed 'VarSetOps::Equal(this, VarSetOps::Intersection(this, life, block->bbLiveIn), life)' bug CodeGen JitStress x86|#7090|7d|
|RyuJIT x86: Assertion failed '(farthestRefPhysRegRecord != nullptr) && (farthestLocation > refLocation \|\| refPosition->isFixedRegRef) bug CodeGen JitStress x86|#7087|7d|

## Long ints

Open issue: how to handle decomposition of longs that are struct field members? E.g., can a struct with long local fields be promoted? Decomposition turns longs into a "promoted struct" of two "int" fields currently. Does that clash with struct long members?

| NYI| Issue |Time Remaining|
| ----- | ----- | --------------- |
|~~Casts from TYP_LONG~~|#4169|0d|
|~~TYP_LONG cast with overflow~~|#4174 |0d|
|~~Unimplemented type for Lowering of cast to TYP_LONG~~|#4175|0d|
|st.lclFld of of TYP_LONG| #4176|14d|
|~~Arithmetic binary operators on TYP_LONG - GT_MUL~~|#4188|0d|
|~~Arithmetic binary operators on TYP_LONG - GT_UMOD~~|#4190|0d|
|~~Arithmetic binary operators on TYP_LONG - SHIFT~~|#4191|0d|
|~~Lowering of signed cast TYP_INT->TYP_LONG~~|#4664|0d|
|Change long decomposition to no longer create temps for operands|#6925|1d|
|Don't use helper for shifts if the shift amount is a GT_CNS_INT|#6999|2d|
|~~Rotation of a long value by variable amount~~|#7110|1d|
|Long compare/reload/jtrue sequence|#7038|7d|
|RyuJIT x86: handle long struct field|#6778|7d|

## Floating point

Open issue: have we implemented double alignment?

| NYI | Issue | Time Remaining|
| --- | ------ | --------------- |
|~~Math intrinsics Cos, Sin and Round~~|#4184|0d|
|Double alignment test failure|#7008|2d|

## ABI / Calling Convention

| NYI | Issue | Time Remaining|
| --- | ------ | --------------- |
|~~GT_OBJ~~|#4179|0d|

## SIMD
Enable FEATURE_SIMD.

This might require encoder/codegen cleanup where things were put under `_TARGET_AMD64_` for the x64 SIMD implementation, where those things will be applicable to x86 as well.

## Tailcall

There is a tailcall-related NYI, but it is not currently hit in any test.  Is GS cookie checking disabled for CoreCLR?

| Title | Issue | Time Remaining|
| --- | ------ | --------------- |
|Tail calls from methods that need GS check||7d|

## Misc. features

| NYI | Issue | Time Remaining|
| --- | ------ | --------------- |
|MKREFANY|#4183|7d|
|Virtual Stub dispatched call lowering via dictionary lookup|#4186|7d|
|~~Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch~~|#4172|7d|

## LSRA (register allocation)

| Title | Issue No. | Time Remaining|
| --- | ------ | --------------- |
|Tune for small register set.|||
|Permit all operands to be marked "reg optional" to allow for more addressing modes and fewer temp registers.|||
|RyuJIT x86: JitStressRegs=1 or 8 needs to ensure that the candidate set has minimum 2 regs CodeGen Test-Issue x86|#7167|7d|

## General tuning

We will do a considerable amount of code quality, code size, throughput, and memory usage tuning before release.

| Title | Issue No. | Time Remaining|
| --- | ------ | --------------- |
|~~Improve fgMorphArgs, especially for x86/RyuJIT~~|#6286|TODO|

# Testing

We need a broad set of testing before release.

## CI system
- [x] Fixed

Bring x86 CI system automated testing to parity with x64

|Title|Issue No.|Time Remaining|
| --------| ----- | --------------- |
|~~RyuJIT x86: enable stress jobs~~|#6924|2d|

**Comment by jashook** [comment]
Sounds like SPMI should be hoisted into a separate unrelated issue.

**Comment by jashook** [comment]
SuperPMI is now being tracked with [#32](https://github.com/dotnet/jitutils/issues/32)

**Comment by pgavlin** [comment]
CQ suite NYIs are tracked by #6981.

**Comment by adiaaida** [comment]
Long GT_MUL and shift are done.

**Comment by adiaaida** [comment]
I just opened issues #7086-#7094 that were exposed by the JitStress and GCStress lab jobs.

**Comment by adiaaida** [comment]
Just ran another full test suite run, and it looks like we've made it to a new NYI. Opened #7110 to track, and added it to the list.

**Comment by RussKeldorph** [comment]
Tracking this with the shiny new Projects feature.  [RyuJIT/x86](https://github.com/dotnet/coreclr/projects/1)
