### ISSUE TITLE
AF: Precondition failure: Can only CloseBuffer() after a call to OpenBuffer()

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#6930]
Repro: Press "Retry" in assert dialog to attach debugger

Result: Another assert dialog

The problem is that ClrGetCurrentDirectory in https://github.com/dotnet/coreclr/blob/master/src/utilcode/safewrap.cpp#L44 is calling CloseBuffer without matching OpenBuffer.

**Comment by jkotas** [comment]
Regression introduced by https://github.com/dotnet/coreclr/tree/7045ca7a6de381b382a709dc0a61f49ca713d160

@ramarag Could you please take a look?

**Comment by ramarag** [comment]
I understand the nature of the bug and will try to change all other instances where this might happen. But i am still curious on the repro. Which assert needs to get fired for the bug to repro ?

**Comment by jkotas** [comment]
Adding `ASSERTE(false)` somewhere to startup path should repro it.
