### ISSUE TITLE
RyuJIT x86: audit DecomposeLongs to ensure proper flags propagation

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#6931]
DecomposeInd(), for example, doesn't propagate flags from the low to high part of the indirection. It seems it should propagate GTF_ALL_EFFECT.

This should be audited for all DecomposeLongs functions.

**Comment by mikedn** [comment]
`DecomposeStoreLclVar` suffers from a similar issue, the pre-LIR PR #6462 contained an attempted fix.

**Comment by adiaaida** [comment]
closed by #7428.
