### ISSUE TITLE
Enable profiler enter/leave hooks on ARM

### ISSUE THREAD

**Issue by kvochko** [dotnet/coreclr#6939]
There are a number of issues regarding this (#445, #2927, #5660), but none of them are talking about ARM specifically. I have prepared a commit (a88f2b4433764009fcf7945413f03b4238186736) that enables this functionality on ARM, and it seems to work fine in the test environment - ARM/softfp, Linux, but I am wondering if this covers the entire problem. Is there something I am missing regarding these two callbacks?
@kspawa @Dmitri-Botcharnikov @myungjoo

**Comment by rahku** [comment]
@kvochko added some comments to your commit

**Comment by kvochko** [comment]
@rahku thanks for the comments! Regarding r0 and r1 holding return value - currently the compiler moves r0 to r2 before writing the functionId to it (as seen in #6138), and doesn't pass anything for the location of args (for ProfileLeaveNaked). For ProfileEnterNaked there aren't any such problems.
Padding was there because ARM requires all double values on stack to be 8-byte aligned (but you're right, it's not needed there now, will remove it).

**Comment by kvochko** [comment]
I am not really familiar with JIT, but the following commit makes it save r1 to r3 before calling ProfileLeave callback and pass args location in r1. Would really appreciate any feedback.

**Comment by rahku** [comment]
Please create a PR and dotnet/jit-contrib & noahfalk to them. It is easier to review and provide feedback using PR.

**Comment by kvochko** [comment]
Resolved by #6976
