### ISSUE TITLE
superpmi: enable build using coredistools

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#6942]
superpmi was open sourced with disasm support disabled. Its build needs to change to define USE_COREDISTOOLS, and properly compile against and use the coredistools package. It should be verified after doing this that superpmi asm diffs works.

**Comment by AndyAyersMS** [comment]
@BruceForstall is this still relevant?

**Comment by BruceForstall** [comment]
@AndyAyersMS no, this is done. I should open an issue to track adding coredistools for more architectures, though.
