### ISSUE TITLE
[ARM32] bpmd fails on arm32/linux

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/coreclr#6955]
coreclr commit: 633a65e6e671afdb1379e705cf0ac333bfbcf8b0
corefx commit : df94809e03ade0c702

bpmd command not working on ARM32/Linux. 
It abort on https://github.com/dotnet/coreclr/blob/master/src/ToolBox/SOS/Strike/util.cpp#L6163
When I have tested with the same corefx dll set, it works find on x64/linux. 

```
sh-3.2# gdb --args lldb-3.8.1 -o "target create corerun" -o "settings set target.run-args hello.dll" -o "plugin load libsosplugin.so" -o "process launch -s" -o "process handle -s false SIGUSR1 SIGUSR2" -o "breakpoint set -n EEStartup" -o "process continue" -o "thread step-out" -o "br del"
..
..
(lldb) bpmd hello.cs:27
[New LWP 15787]
[New LWP 15788]
[New LWP 15789]

Program received signal SIGSEGV, Segmentation fault.
0xa960ac2a in ?? ()
(gdb) bt
#0  0xa960ac2a in ?? ()
#1  0xa960ac12 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 

```

**Comment by chunseoklee** [comment]
@Dmitri-Botcharnikov @lucenticus

**Comment by lucenticus** [comment]
@chunseoklee I can reproduce this crash, but didn't find the reason of this issue yet. Probably, we should try another version of dlls

**Comment by chunseoklee** [comment]
@lucenticus Did you mean that you cannot run this PR on arm32/linux ? or you have a solution ?
In issue #6853 , the solution is building corefx dll set by running script as in coreclr overlay test. 
However, keep failing on arm32.

**Comment by chunseoklee** [comment]
rebasing on #6956 does not resolve my seg fault. It seems like @Dmitri-Botcharnikov has a solution since he success on the latest upstream.

**Comment by Dmitri-Botcharnikov** [comment]
I've tested #6956 on arm/hardfp (odroid + ubuntu 14.04)

**Comment by chunseoklee** [comment]
@Dmitri-Botcharnikov Could you share how to gather/build corefx dlls on ordroid ?

**Comment by Dmitri-Botcharnikov** [comment]
I've build managed part of corefx, and get new version of two assemblies `System.Runtime.InteropServices.dll` and `System.Reflection.Metadata.dll`. All other assemblies are unchanged.
