### ISSUE TITLE
Possible contention issue sharing ports on Ubuntu 

### ISSUE THREAD

**Issue by wjdavis5** [dotnet/coreclr#6957]
Possible contention issue sharing ports on Ubuntu 
-----------------------------------------------------------
**clr: 1.0.0-preview2-003121**

I have 2 instances of a single app running on Ubuntu 14.04. They are sharing port 20400. In the image below you can see cpu utilization over time as I test a few things. As you can see when both instances are running sharing this port CPU holds steady at about 40%. When only one instance is running cpu doesnt spike above 2 %.

I suspect there may be an issue with sharing ports here so I made a quick change:

I updated the code to make the listen port configurable. If you look at the highlighted bubble you can see that once I changed the instances to use different ports that both are running together and not peaking 2 % CPU.

It looks like there may in fact be a problem sharing ports causing high cpu utilization.

![image](https://cloud.githubusercontent.com/assets/2580575/18052346/d71b37c2-6dc7-11e6-978c-5b9a9b2c042d.png)

**Comment by adityamandaleeka** [comment]
Perhaps it would be useful to collect a CPU trace to better understand what exactly is on the CPU when this occurs.

**Comment by wjdavis5** [comment]
@adityamandaleeka Thanks for the info, I'll get that setup. FWIW I was running top throughout the test the only other thing I saw was the datadog collection agent (statsd).

**Comment by wjdavis5** [comment]
After some further troubleshooting I noticed that what was happening. We had an random empty catch clause that wasnt logging the thrown exception. In this case the port sharing attempt was actually throwing an exception. Logic has been added to prevent that and cpu utilization is normal.
