### ISSUE TITLE
Do we still need those [DebuggerHidden]/[DebuggerStepThrough] attributes on Reflection methods?

### ISSUE THREAD

**Issue by ghost** [dotnet/coreclr#6965]
All of the Reflection apis of the Invoke/GetValue/SetValue persuation are difficult to analyze and understand because these attributes are preventing source-stepping through with the debugger.

Do these debug attributions still have any value?

And if we do have to keep them, does anyone have any insight on either:
- A way to get your local VS to not honor those attributes?
- A blessing to #if those attributes so they appear where they need to and not where they aren't (where the latter category hopefully includes this repo.)

**Comment by weshaggard** [comment]
My guess is that you are one of the few people that actually want to step into these methods, so I think there is still value.

While not the greatest workaround in the past I've stepped into these types of methods by switching to the disassembly view and F10'ing through the code until you hit the real call code and then step into it. I think you can also put break-points in the methods. 

If that still doesn't work then perhaps an #ifndef DEBUG around them might be a good proxy so in debug builds we wouldn't have them but they would be there for release builds which is what most people would have.

**Comment by jkotas** [comment]
cc @noahfalk 

> perhaps an #ifndef DEBUG around them 

This would break debugger tests running on debug builds...

**Comment by noahfalk** [comment]
@gregg-miskelly - Gregg, do you know of anything cheap that disables VS from the various attribute-based special stepping behavior it does?

**Comment by gregg-miskelly** [comment]
@noahfalk: No. Those attributes are always respected.
