### ISSUE TITLE
Resource-generation fails on FreeBSD, with almost all resources getting msgid "80000000"

### ISSUE THREAD

**Issue by josteink** [dotnet/coreclr#698]
When the build comes to the point where resources are to be generated, the build fails with the following errors (repeated to excess):

````
/home/josteink/build/cc/bin/obj/FreeBSD.x64.Debug/src/dlls/mscorrc/full/mscorrc.debug.po:4: duplicate message definition...
/home/josteink/build/cc/bin/obj/FreeBSD.x64.Debug/src/dlls/mscorrc/full/mscorrc.debug.po:2: ...this is the location of the first definition
/home/josteink/build/cc/bin/obj/FreeBSD.x64.Debug/src/dlls/mscorrc/full/mscorrc.debug.po:7: duplicate message definition...
/home/josteink/build/cc/bin/obj/FreeBSD.x64.Debug/src/dlls/mscorrc/full/mscorrc.debug.po:2: ...this is the location of the first definition
/home/josteink/build/cc/bin/obj/FreeBSD.x64.Debug/src/dlls/mscorrc/full/mscorrc.debug.po:10: duplicate message definition...
/home/josteink/build/cc/bin/obj/FreeBSD.x64.Debug/src/dlls/mscorrc/full/mscorrc.debug.po:2: ...this is the location of the first definition
````

Excerpt from `mscorrc.debug.po` as generated by the build:

````
msgid "80000000"
msgstr "<Unknown %1>"

msgid "80000000"
msgstr "<Unknown>"

msgid "80000000"
msgstr "<In Memory Module>"

msgid "80000000"
msgstr "Application has generated an exception that could not be handled.\n\nProcess ID=0x%x (%d), Thread ID=0x%x (%d).$
````

Not all message-ids are resolved to this value though. We have 68 different entries:

````bash
$ grep "msgid" /home/josteink/build/cc/bin/obj/FreeBSD.x64.Debug/src/dlls/mscorrc/full/mscorrc.debug.po | sort | uniq | wc -l
68
````

Those values can be found here:

````
msgid "2711"
msgid "2712"
msgid "2713"
msgid "2714"
msgid "2715"
msgid "2716"
msgid "2717"
msgid "2718"
msgid "2719"
msgid "271A"
msgid "271B"
msgid "271C"
msgid "271D"
msgid "271E"
msgid "271F"
msgid "2720"
msgid "2721"
msgid "2722"
msgid "2723"
msgid "2724"
msgid "2725"
msgid "2726"
msgid "2727"
msgid "2728"
msgid "2729"
msgid "272A"
msgid "272B"
msgid "272C"
msgid "272D"
msgid "272E"
msgid "272F"
msgid "2730"
msgid "2731"
msgid "2732"
msgid "2733"
msgid "2734"
msgid "2735"
msgid "2736"
msgid "2737"
msgid "2738"
msgid "2739"
msgid "273A"
msgid "273B"
msgid "80000000"
msgid "80070002"
msgid "80070004"
msgid "80070005"
msgid "8007000B"
msgid "80070020"
msgid "80070021"
msgid "8007006D"
msgid "8007006F"
msgid "80070070"
msgid "8007007B"
msgid "8007007F"
msgid "800700B7"
msgid "800703ED"
msgid "800703EE"
msgid "8007045A"
msgid "800704E5"
msgid "80070570"
msgid "80070571"
msgid "800C0006"
msgid "800C0007"
msgid "800C0008"
msgid "800C000D"
msgid "800C000E"
msgid "80131522"
````

@janvorli: You wanted to take a look at this?

Something is obviously going wrong when it attempts to generate/resolve the message-id, but without looking further into it, I'm not sure what and where. It might also be that something goes wrong before it gets processed by [the awk-scripts](https://github.com/janvorli/coreclr/blob/master/src/dlls/mscorrc/rctopo.awk).

**Edit:** A quick analysis seems to indicate that entries ending up with msgid 80000000 has used a const for their msgid-definition in the original rc-file (`IDS_EE_NAME_INMEMORYMODULE`, `IDS_EE_NAME_UNKNOWN`, `IDS_EE_NAME_UNKNOWN_UNQ`, `IDS_DEBUG_UNHANDLEDEXCEPTION` etc)

**Comment by janvorli** [comment]
@josteink The issue is in the evaluation of the resource value expressions. Here is the piece of code in the awk script that does that:
```awk
        # evaluate the resource id expression and format it as hex number
        cmd = "echo $(("expression"))";
        cmd | getline var;
        close(cmd);
```
So it calls shell with command
```sh
echo $((expression))
```
where the `expression` is the resource id expression. It looks like it doesn't understand the hexadecimal prefix. The only weird thing are the values larger than 0x80000000. According to your list, these seem to be evaluated correctly. 

Could you please try to run the following from your shell and see what it prints?
```sh
echo $((0x1a0c))
echo $((0x800703EE))
echo $(((0x6000 + (((0x12bb) & 0xFFFF)))))
```

**Comment by josteink** [comment]
Done and done:

````bash
$ echo $((0x1a0c))
6668
$ echo $((0x800703EE))
2147943406
$ echo $(((0x6000 + (((0x12bb) & 0xFFFF)))))
29371
$
````

To me that looks right, but my current-user is running zsh as shell:

Which leaves me the question: How does awk decide which shell to branch out to?

Iirc FreeBSD's default shell is tcsh and that reaps the following results:

````bash
josteink@:~ % echo $((0x1a0c))
Illegal variable name.
josteink@:~ % echo $((0x800703EE))
Illegal variable name.
josteink@:~ % echo $(((0x6000 + (((0x12bb) & 0xFFFF)))))
Illegal variable name.
josteink@:~ %
````

From what I can tell, this output is not sent to stdout, but stderr, which may explain why we end up with a default 0x80000000.  Using bash however, yields the same results as zsh:

````bash
[josteink@ ~]$ echo $((0x1a0c))
6668
[josteink@ ~]$ echo $((0x800703EE))
2147943406
[josteink@ ~]$ echo $(((0x6000 + (((0x12bb) & 0xFFFF)))))
29371
[josteink@ ~]$
````

So maybe it's a matter of which shell is getting invoked? If so, we can control that by setting our cmd-expression accordingly.

**Comment by janvorli** [comment]
Ok, it could be that, but then I don't understand why some values evaluate correctly. Could you please do one more experiment - modify the `src/dlls/mscorrc/processrc.awk` by commenting out the following lines (putting `#` at the beginning)?
```awk
        if (var >= 2147483648)
        {
            var = var - 4294967296;
        }
        var = sprintf("%X", var);
```
Then run the build and dump the first bunch of lines from the `mscorrc.debug.po` or maybe post the whole `mscorrc.debug.po` somewhere so that I can take a look.

**Comment by josteink** [comment]
Commenting out those lines seems to fix the issue, and brings the build further on to a new error:

````
/usr/bin/ld: Dwarf Error: found dwarf version '3', this reader only handles version 2 information.
````

We can verify the .po-file too, and see that the IDs are now handled properly:

````
msgid "6668"
msgstr "<Unknown %1>"

msgid "6663"
msgstr "<Unknown>"

msgid "6664"
msgstr "<In Memory Module>"

msgid "6071"
msgstr "Application has generated an exception that could not be handled.\n\nProcess ID=0x%x (%d), Thread ID=0x%x (%d).\n\nClick OK to terminate the application.\nClick CANCEL to debug the application."

msgid "6068"
msgstr "Application Error"

msgid "6401"
msgstr "A call to PInvoke function '%1$s' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature."

msgid "6432"
msgstr "The assembly named '%1$s' was loaded from '%2$s' using the LoadFrom context. The use of this context can result in unexpected behavior for serialization, casting and dependency resolution. In almost all cases, it is recommended that the LoadFrom context be avoided. This can be done by installing assemblies in the Global Assembly Cache or in the ApplicationBase directory and using Assembly.Load when explicitly loading assemblies."

msgid "6443"
msgstr "The assembly with display name '%1$s' loaded from code base '%2$s' failed to load in the '%3$s' binding context of the AppDomain with ID %4$d. The cause of the failure was: %5$s"

msgid "6402"
msgstr "The '%1$s' configuration file is invalid."
````

The full file can be [found here](http://invalid.ed.ntnu.no/~jostein/mscorrc.txt) if you're still interested.

**Comment by janvorli** [comment]
Hmm, then the issue is not in the shell. Based on the full .po file from you, all the resource ids are evaluated correctly in shell, but the formatting performed by the following line in the awk script doesn't work:
```awk
var = sprintf("%X", var);
```
But that is really strange since when the resource id is defined as a decimal value (e.g. value 10001 which is 0x2711), the `sprintf` works correctly, according to your very first log of distinct ids before removing the few lines of awk code that should just format the value to hex.
So the only idea I have left is that for some of the ids, the type of the `var` ends up being string and so the %X format fails on those.
@josteink, could you please do one more experiment for me? Please put back the lines you have commented out and add this line right before them:
```awk
var = var + 0;
```
According to the awk manual, this should ensure that if the var is a string containing a number, it gets converted to a number.

As for the `ld` issue, it looks like the problem described here:
https://groups.google.com/forum/#!topic/mailing.freebsd.questions/v83_xd7QQi8

**Comment by josteink** [comment]
Good news: Running the build with that one type-coercion yields a good result too!

Yay!

If you don't mind, can you provide the PR and commit? I'm still trying to get the threading-fix cleaned up besides 20 other tasks at work :)

As for the `ld` issue I didn't intend to mix it up with this issue, just making a note of the fact that the build had moved on. I'm not fully on top of it *yet*, but I'll look further into it later, and at worst create a separate issue for it.

**Comment by janvorli** [comment]
@josteink - Sure, I'll do that.

**Comment by josteink** [comment]
Sounds great!

The good news is that with this (and apart from a few unresolved issues), we now have coreclr for FreeBSD actually past compilation and well into the linking-phase.

I can tell there's still enough challenges ahead, but I think we're making pretty good headway. Thanks for the help for so!

**Comment by MattWhilden** [comment]
I am straight up ecstatic at this news! Nice work!

**Comment by josteink** [comment]
I can confirm that the merged PR has fixed this issue. Thanks!
