### ISSUE TITLE
RyuJIT x86: address NYIs blocking CQ tests.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#6981]
The following NYIs are blocking our internal CQ suite:

- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\decomposelongs.cpp:226 - NYI: "Arithmetic binary operators on TYP_LONG - SHIFT"
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:819 - NYI: "Can't decompose expression tree TYP_LONG node"
- src\jit\lowerxarch.cpp:2192 - NYI_X86: "Math intrinsics Cos, Sin and Round"
- src\jit\codegencommon.cpp:650 - NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
- src\jit\lower.cpp:2864 - NYI_X86: "Virtual Stub dispatched call lowering via dictionary lookup"
- src\jit\decomposelongs.cpp:178 - NYI: "st.lclFld of of TYP_LONG" (#6982)

Below are two different transpositions of the data: one table of assertions per benchmark and one of benchmarks per assertion.

# System.XML
- src\jit\decomposelongs.cpp:819 - NYI: "Can't decompose expression tree TYP_LONG node"
 
# SharpChess
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:178 - NYI: "st.lclFld of of TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\decomposelongs.cpp:819 - NYI: "Can't decompose expression tree TYP_LONG node"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# v8-richards
- src\jit\decomposelongs.cpp:819 - NYI: "Can't decompose expression tree TYP_LONG node"
 
# v8-crypto
- src\jit\decomposelongs.cpp:226 - NYI: "Arithmetic binary operators on TYP_LONG - SHIFT"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\decomposelongs.cpp:819 - NYI: "Can't decompose expression tree TYP_LONG node"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# v8-deltablue
- src\jit\decomposelongs.cpp:819 - NYI: "Can't decompose expression tree TYP_LONG node"
 
# bio-mums
- src\jit\codegencommon.cpp:650 - NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\decomposelongs.cpp:819 - NYI: "Can't decompose expression tree TYP_LONG node"
- src\jit\lower.cpp:2864 - NYI_X86: "Virtual Stub dispatched call lowering via dictionary lookup"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# Fractals
- src\jit\decomposelongs.cpp:819 - NYI: "Can't decompose expression tree TYP_LONG node"
 
# bzip2
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# Crafty
- src\jit\codegencommon.cpp:650 - NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
- src\jit\decomposelongs.cpp:226 - NYI: "Arithmetic binary operators on TYP_LONG - SHIFT"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\decomposelongs.cpp:819 - NYI: "Can't decompose expression tree TYP_LONG node"
- src\jit\lower.cpp:2864 - NYI_X86: "Virtual Stub dispatched call lowering via dictionary lookup"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# mono-knucleotide
- src\jit\codegencommon.cpp:650 - NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
- src\jit\lower.cpp:2864 - NYI_X86: "Virtual Stub dispatched call lowering via dictionary lookup"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# mono-pi-digits
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# BenchI-array1
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
 
# BenchI-pi
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
 
# BenchI-quicksrt
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
 
# BenchF-benchmk2
- src\jit\lowerxarch.cpp:2192 - NYI_X86: "Math intrinsics Cos, Sin and Round"
 
# BenchF-benchmrk
- src\jit\lowerxarch.cpp:2192 - NYI_X86: "Math intrinsics Cos, Sin and Round"
 
# BenchF-fft
- src\jit\lowerxarch.cpp:2192 - NYI_X86: "Math intrinsics Cos, Sin and Round"
 
# BenchF-whetsto
- src\jit\lowerxarch.cpp:2192 - NYI_X86: "Math intrinsics Cos, Sin and Round"
 
# ByteMark-assignjagged
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-assignrect
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-bitfield
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-emfclass
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-emfstruct
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-four
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:2192 - NYI_X86: "Math intrinsics Cos, Sin and Round"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-huff
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-idea
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-lu
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-nnetjagged
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-nnetrect
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-numsortjagged
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-numsortrect
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-stringsort
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# CoreMark
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# SciMark
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\lowerxarch.cpp:2192 - NYI_X86: "Math intrinsics Cos, Sin and Round"
 
# FSharpFFT
- src\jit\lowerxarch.cpp:2192 - NYI_X86: "Math intrinsics Cos, Sin and Round"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# Rotate
- src\jit\decomposelongs.cpp:226 - NYI: "Arithmetic binary operators on TYP_LONG - SHIFT"
 
 
# src\jit\codegencommon.cpp:650 - NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
- bio-mums
- Crafty
- mono-knucleotide
 
# src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- SharpChess
- bio-mums
- bzip2
- ByteMark-assignjagged
- ByteMark-assignrect
- ByteMark-assignjagged
- ByteMark-assignrect
- ByteMark-bitfield
- ByteMark-emfclass
- ByteMark-emfstruct
- ByteMark-four
- ByteMark-huff
- ByteMark-idea
- CoreMark
- SciMark
 
# src\jit\decomposelongs.cpp:178 - NYI: "st.lclFld of of TYP_LONG"
- SharpChess
 
# src\jit\decomposelongs.cpp:226 - NYI: "Arithmetic binary operators on TYP_LONG - SHIFT"
- v8-crypto
- Crafty
- Rotate
 
# src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- SharpChess
- v8-crypto
- bio-mums
- bzip2
- Crafty
- mono-pi-digits
- BenchI-array1
- BenchI-pi
- BenchI-quicksrt
- ByteMark-assignjagged
- ByteMark-assignrect
- ByteMark-bitfield
- ByteMark-emfclass
- ByteMark-emfstruct
- ByteMark-four
- ByteMark-huff
- ByteMark-idea
- ByteMark-lu
- ByteMark-nnetjagged
- ByteMark-nnetrect
- ByteMark-numsortjagged
- ByteMark-numsortrect
- ByteMark-stringsort
- CoreMark
- SciMark
 
# src\jit\decomposelongs.cpp:819 - NYI: "Can't decompose expression tree TYP_LONG node"
- System.XML
- SharpChess
- v8-richards
- v8-crypto
- v8-deltablue
- bio-mums
- Fractals
- Crafty
 
# src\jit\lower.cpp:2864 - NYI_X86: "Virtual Stub dispatched call lowering via dictionary lookup"
- bio-mums
- Crafty
- mono-knucleotide
 
# src\jit\lowerxarch.cpp:2192 - NYI_X86: "Math intrinsics Cos, Sin and Round"
- BenchF-benchmk2
- BenchF-benchmrk
- BenchF-fft
- BenchF-whetsto
- ByteMark-four
- SciMark
- FSharpFFT
 
# src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
- SharpChess
- v8-crypto
- bio-mums
- bzip2
- Crafty
- mono-knucleotide
- mono-pi-digits
- ByteMark-assignjagged
- ByteMark-assignrect
- ByteMark-bitfield
- ByteMark-emfclass
- ByteMark-emfstruct
- ByteMark-four
- ByteMark-huff
- ByteMark-idea
- ByteMark-lu
- ByteMark-nnetjagged
- ByteMark-nnetrect
- ByteMark-numsortjagged
- ByteMark-numsortrect
- ByteMark-stringsort
- CoreMark
- SciMark
- FSharpFFT

Given the data, we are prioritizing the following NYIs:
- src\jit\decomposelongs.cpp:819 - NYI: "Can't decompose expression tree TYP_LONG node"
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
- src\jit\decomposelongs.cpp:226 - NYI: "Arithmetic binary operators on TYP_LONG - SHIFT"
- src\jit\lowerxarch.cpp:2192 - NYI_X86: "Math intrinsics Cos, Sin and Round"
 
Fixing these four NYIs will light up the following benchmarks:
- System.XML
- v8-richards
- v8-deltablue
- fractals
- BenchI-array1
- BenchI-pi
- BenchI-quicksrt
- BenchF-benchmk2
- BenchF-benchmrk
- BenchF-FFT
- BenchF-whetsto
- Rotate
 
Once these are fixed, we should move on to the following:
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
 
Fixing these two NYIs will then light up the following benchmarks:
- v8-crypto
- bzip2
- mono-pi-digits
- ByteMark-assignjagged
- ByteMark-assignrect
- ByteMark-bitfield
- ByteMark-emfclass
- ByteMark-emfstruct
- ByteMark-four
- ByteMark-huff
- ByteMark-idea
- ByteMark-lu
- ByteMark-nnetjagged
- ByteMark-nnetrect
- ByteMark-numsortjagged
- ByteMark-numsortrect
- ByteMark-stringsort
- CoreMark
- SciMark
- FSharpFFT
 
Once these are fixed, the only remaining benchmarks will be Roslyn, SharpChess, bio-mums, Crafty, mono-knucleotide, Json-Serialize, Json-Deserialize, TrueTypeBench, and mono-fannkuch-redux. The first five benchmarks will light up once we fix the remaining three NYIs:
- src\jit\codegencommon.cpp:650 - NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
- src\jit\decomposelongs.cpp:178 - NYI: "st.lclFld of of TYP_LONG"
- src\jit\lower.cpp:2864 - NYI_X86: "Virtual Stub dispatched call lowering via dictionary lookup"
 
The last two will need to be manually investigated. The latter fails with the assertion mentioned in #6920; the former times out.

**Comment by pgavlin** [comment]
#7023 worked around the NYI for math intrinsics.

**Comment by adiaaida** [comment]
#6988 Implemented TYP_LONG shift. Opened #6999 for optimization of shifts.

**Comment by pgavlin** [comment]
#4986 addressed `src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"`

**Comment by pgavlin** [comment]
We've taken care of a number of these NYIs in the last week or so. Here's an updated table:

# System.XML
- src\jit\codegenxarch.cpp:2015 - NYI: "Casts from TYP_LONG"
 
# v8-crypto
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# bio-mums
- src\jit\codegencommon.cpp:650 - NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lower.cpp:2864 - NYI_X86: "Virtual Stub dispatched call lowering via dictionary lookup"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# bzip2
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# Crafty
- src\jit\codegencommon.cpp:650 - NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
- src\jit\codegenxarch.cpp:2435 - NYI: "Long compare/reload/jtrue sequence"
- src\jit\lower.cpp:2864 - NYI_X86: "Virtual Stub dispatched call lowering via dictionary lookup"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# mono-knucleotide
- src\jit\codegencommon.cpp:650 - NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
- src\jit\lower.cpp:2864 - NYI_X86: "Virtual Stub dispatched call lowering via dictionary lookup"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# mono-pi-digits
- src\jit\codegencommon.cpp:650 - NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# BenchI-pi
- src\jit\codegenxarch.cpp:2435 - NYI: "Long compare/reload/jtrue sequence"
 
# BenchI-quicksrt
- src\jit\decomposelongs.cpp:478 - NYI: "Lowering of signed cast TYP_INT->TYP_LONG"
 
# BenchF-benchmk2
- src\jit\lowerxarch.cpp:2192 - NYI_X86: "Math intrinsics Cos, Sin and Round"
 
# ByteMark-assignjagged
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-assignrect
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-bitfield
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-emfclass
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-emfstruct
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-four
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-huff
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-idea
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-lu
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-nnetjagged
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-nnetrect
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-numsortjagged
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-numsortrect
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# ByteMark-stringsort
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# CoreMark
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\codegenxarch.cpp:2435 - NYI: "Long compare/reload/jtrue sequence"
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# SciMark
- src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- src\jit\codegenxarch.cpp:2435 - NYI: "Long compare/reload/jtrue sequence"
 
# FSharpFFT
- src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
 
# src\jit\codegencommon.cpp:650 - NYI: "Model kill set for CORINFO_HELP_ASSIGN_BYREF on target arch"
- bio-mums
- Crafty
- mono-knucleotide
- mono-pi-digits
 
# src\jit\codegenxarch.cpp:2004 - NYI: "Casts from TYP_LONG"
- bio-mums
- bzip2
- mono-pi-digits
- ByteMark-assignjagged
- ByteMark-assignrect
- ByteMark-assignjagged
- ByteMark-assignrect
- ByteMark-bitfield
- ByteMark-emfclass
- ByteMark-emfstruct
- ByteMark-four
- ByteMark-huff
- ByteMark-idea
- ByteMark-lu
- CoreMark
- SciMark

# src\jit\codegenxarch.cpp:2435 - NYI: "Long compare/reload/jtrue sequence"
- Crafty
- BenchI-pi
- CoreMark
- SciMark
 
# src\jit\lower.cpp:2864 - NYI_X86: "Virtual Stub dispatched call lowering via dictionary lookup"
- bio-mums
- Crafty
- mono-knucleotide
 
# src\jit\lowerxarch.cpp:527 - NYI_X86: "GT_OBJ"
- v8-crypto
- bio-mums
- bzip2
- Crafty
- mono-knucleotide
- mono-pi-digits
- ByteMark-assignjagged
- ByteMark-assignrect
- ByteMark-bitfield
- ByteMark-emfclass
- ByteMark-emfstruct
- ByteMark-four
- ByteMark-huff
- ByteMark-idea
- ByteMark-lu
- ByteMark-nnetjagged
- ByteMark-nnetrect
- ByteMark-numsortjagged
- ByteMark-numsortrect
- ByteMark-stringsort
- CoreMark
- SciMark
- FSharpFFT

In addition, SharpChess is now crashing with what looks to be an issue with frame chains (#7113).

The following benchmarks are now running without NYIs:
- v8-richards
- v8-deltablue
- Fractals
- BenchI-array1
- BenchI-quicksrt
- BenchF-benchmk2
- BenchF-benchmrk
- BenchF-fft
- BenchF-whetsto
- Rotate

The `GT_OBJ` and `Cast from TYP_LONG` asserts remain the heavy hitters. I believe that the changes in #7099 may at least partially address the latter.

**Comment by pgavlin** [comment]
#7141 tracks the VSD NYI.

**Comment by CarolEidt** [comment]
@pgavlin can this be closed now?

**Comment by pgavlin** [comment]
I think so, yes. I haven't had a chance to verify that none of the cqPerf tests have NYIs any longer, so I've left it open. I will run that check today.

**Comment by pgavlin** [comment]
Confirmed. The CQ tests are now NYI-free.
