### ISSUE TITLE
RyuJIT x86: audit "last use" bit during decomposition

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#6998]
I noticed what looks like an issue with LONG vars that are marked "last use" (`GTF_VAR_DEATH`). E.g., in the loopEH test case, function Test (JIT\jit64\eh\basics\loopEH.cs), I see:

```
Decomposing TYP_LONG tree.  BEFORE:
N001 (  3,  2) [000041] ------------       t41 =    lclVar    long   V04 arg4         u:3 (last use) $340

New refCnts for V04: refCnt =  3, refCntWtd = 12
New refCnts for V04: refCnt =  4, refCntWtd = 16
New refCnts for V04: refCnt =  5, refCntWtd = 20
Decomposing TYP_LONG tree.  AFTER:
N001 (  3,  2) [000041] ------------       t41 =    lclFld    int    V04 arg4         u:3[+0] (last use)

               [000205] ------------      t205 =    lclFld    int    V04 arg4         [+4]

                                                 /--*  t41    int
                                                 +--*  t205   int
               [000206] ------------      t206 = *  gt_long   long
```

so the "last use" bit is marked on the low half but not high half. Presumably it should be marked on both, since they are lclFld accesses, and not just on the high half, which comes later in evaluation order.

**Comment by BruceForstall** [comment]
@CarolEidt @pgavlin @adiaaida comments?

**Comment by pgavlin** [comment]
What does this look like after liveness?

**Comment by BruceForstall** [comment]
Looks like the bit moves to the "hi" part after liveness:
```
N001 (  3,  2) [000041] ------------       t41 =    lclFld    int    V04 arg4         u:3[+0]
               [000205] ------------      t205 =    lclFld    int    V04 arg4         [+4] (last use)
```
so as long as nobody depends on the bit before liveness is run, maybe we're ok.

I guess I should talk to you about the liveness model for the decomposed vars. It seems like these should be independent from a liveness perspective.

**Comment by BruceForstall** [comment]
In fact, in the same function, in a different location, before liveness, we have:
```
                                                 /--*  t41    int
                                                 +--*  t43    int
N003 ( 10, 16) [000044] ------------       t44 = *  +Lo       int

                                                 /--*  t205   int
                                                 +--*  t207   int
               [000209] ------------      t209 = *  +Hi       int

                                                 /--*  t44    int
N005 ( 17, 22) [000046] DA----------             *  st.lclFld int    V04 arg4         d:4[+0]

                                                 /--*  t209   int
               [000211] D-----------             *  st.lclFld int    V04 arg4         [+4]
```
and after:
```
                                                 /--*  t41    int
                                                 +--*  t43    int
N003 ( 10, 16) [000044] ------------       t44 = *  +Lo       int

                                                 /--*  t205   int
                                                 +--*  t207   int
               [000209] ------------      t209 = *  +Hi       int

                                                 /--*  t209   int
               [000211] D-----------             *  st.lclFld int    V04 arg4         [+4]
```
(I'm look at https://github.com/dotnet/coreclr/issues/6778)
It seems like the store is removed because the V04 long is treated as a unit, where the 2nd store makes the first store dead. In this case, V04 is:
```
;  V04 arg4             long  do-not-enreg[H]
```
In particular, we don't promote it because it is marked lvDoNotEnregister. It seems like liveness still needs to be able to treat the two halve separately.

@CarolEidt Why did you not promote do-not-enregister LONGs?

**Comment by BruceForstall** [comment]
If I allow promoting these "do-not-enreg" locals, then the tests in #6778 pass.

**Comment by BruceForstall** [comment]
It seems like we need to promote long locals even if `CLFLG_REGVAR` is not set, for the same reason: even if we aren't enregistering variables, we still need to decompose the longs.

**Comment by CarolEidt** [comment]
@BruceForstall The last use information should be corrected, but for the time being (due to older issues with liveness and the ordering of lclVars within a statement) we recompute last uses in LSRA, in `setLastUses`. I hope that we can eliminate that soon (#7256)

**Comment by pgavlin** [comment]
@CarolEidt: do you think that we'll get to #7256 before 1.2? If not, we may want to consider moving this item out to Future (or at least marking it as lower-priority), as it is somewhat contingent upon that work.

**Comment by CarolEidt** [comment]
I think that both should be moved to Future, especially since, taken together, they aren't correctness issues.

**Comment by pgavlin** [comment]
Done. Thanks!

**Comment by pgavlin** [comment]
I think that the real question here is "do we need to maintain last use information during decomp/lowering/etc.". Thankfully, the answer is "no": this information will be recomputed during liveness for LSRA, which runs after decomp and lowering. We do need to make sure that we do not invalidate this information in TreeNodeInfoInit, however, as that currently runs after liveness (although at the moment LSRA will correct any mistakes we've made b/c the last use information as computed by liveness is inherently incorrect (#7256)).

As such, I'm going to close this issue.
