### ISSUE TITLE
Parsing string to enum with digit as first char takes a very long time

### ISSUE THREAD

**Issue by FWest98** [dotnet/coreclr#70]
From https://github.com/dotnet/corefx/issues/594

When parsing strings to enums with TryParse, in some cases this takes way longer than in all the other cases. After a bit of research I found that all the strings with a digit as first char are slower. This is due to the attempt to parse the string to the underlying type (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Enum.cs#L396) with a Convert.ChangeType, which can throw an exception, because further down the line it uses (for example) Int32.Parse instead of TryParse (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Convert.cs#L1118).

The time it takes to create the Exception is significant. In my project I ended up writing a new Enum parser to circumvent this issue.
"Something": 240.49 ns per parse
"1Somethin": 37178.57 ns per parse
"123456789": 485.63 ns per parse

As users expect Convert.ToXxx() to throw an exception when it fails, changing this is a bad idea I think. Possible solutions I can think of:
- Extend the Convert class with Try-methods that don't throw exceptions, and use those while trying to parse an enum (much work)
- Instead of checking whether the first character is a digit (https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/enum.cs#L434), change that line to a TryParse of the whole string (the easier way)
- One of the options @Alexx99 posted in the other issue (https://github.com/dotnet/corefx/issues/594#issuecomment-72893658)

**Comment by Alexx999** [comment]
Okay, it seems I've got working fix, but without tests it's quite hard to check if it's correct. I've opened issue #78 to address this.

**Comment by FWest98** [comment]
What exactly did you change to fix this? Can you post the new implementation here while we're waiting for the tests?

**Comment by Alexx999** [comment]
I want to run a few tests to be sure it works fine at some edge cases, and then I'll probably open a pull request - if it won't be accepted then at least we'll get some feedback on this

**Comment by kangaroo** [comment]
@richlander ping -- not sure who owns this, but its aging.

**Comment by AlexGhiondea** [comment]
@alex999 submitted PR #81 to fix this. Unfortunately we were not able to accept it.

**Comment by FWest98** [comment]
@AlexGhiondea I don't really see the problem with the PR. It seems all possible problems are resolved by creating a fallback. Just that it "doesn't meet the required level" isn't really explaining to me why it can't be accepted.
