### ISSUE TITLE
[ARM/Linux] Is `ARM_HAZARD_AVOIDANCE` for Krait still effective?

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#7003]
While working on #7002, I found that an extra `nop.w` instructions is added sometimes for direct calls. According to the comment, it says it is a Krait processor bug. Actually I can't find more information about this on the web.

Is it still effective? If so, I was just thinking that we may not need to have this flag on by default.

/cc @dotnet/jit-contrib @hqueue

**Comment by hqueue** [comment]
@wateret If it is a kind of errata in Krait, I think we can remove extra `nop.w` for other SoC. I will take a look into it too.

**Comment by briansull** [comment]
You can probably change the define to remove the extra NOP's .

It think that it was a pretty rare issue, so its not very likely to cause failures even on hardware with the issue.  If such hardware is still in use.
