### ISSUE TITLE
String encoding bug

### ISSUE THREAD

**Issue by andrew-vandenbrink** [dotnet/coreclr#7035]
```
 address = SymmetricEncryptionAPI.Decrypt(address, _option.Value["XXX"]);
```
![image](https://cloud.githubusercontent.com/assets/12871379/18196178/2c4f9ea6-70f0-11e6-8523-eded614e8a10.png)

![image](https://cloud.githubusercontent.com/assets/12871379/18196186/3a9c2d44-70f0-11e6-97be-fe5dca1a9354.png)

![image](https://cloud.githubusercontent.com/assets/12871379/18196202/4a74e49a-70f0-11e6-87fc-3fc047d7c219.png)

Notice the "+" just gone from the string

**Comment by mikedn** [comment]
It's not clear where the supposedly broken code is or if it's even in .NET Core to begin with. String doesn't have methods such as FromBase64String or ToByteArray, those are probably your own extension methods.

**Comment by andrew-vandenbrink** [comment]
It's already broken before the extension methods is called

input variable: address
method: Decrypt

the variable inside method Decrypt: chiper

the value "+" just gone inside method Decrypt
The value of "chiper" should be equal "address" obviously 

The issue exists on passing variable between method, not the method it self

**Comment by andrew-vandenbrink** [comment]
```
System.Text.UTF8Encoding.UTF8.GetBytes(address.Substring(0,11))
```
produce
```
[0]: 118
    [1]: 55
    [2]: 103
    [3]: 86
    [4]: 104
    [5]: 74
    [6]: 103
    [7]: 57
    [8]: 67
    [9]: 43
    [10]: 52
```

```
System.Text.UTF8Encoding.UTF8.GetBytes(chiper.Substring(0,11))
```

produce

```
{byte[11]}
    [0]: 118
    [1]: 55
    [2]: 103
    [3]: 86
    [4]: 104
    [5]: 74
    [6]: 103
    [7]: 57
    [8]: 67
    [9]: 32
    [10]: 52
```

byte[9] changed from 43 to 32 by it self

**Comment by andrew-vandenbrink** [comment]
![image](https://cloud.githubusercontent.com/assets/12871379/18199711/dbb1fcca-7101-11e6-9fa1-5bd5b9cc0d67.png)

Both have utf 8 encoding


At this moment I implement workaround to replace the whitespace with + before converting from base64

**Comment by andrew-vandenbrink** [comment]
Issue is on System.Net.WebUtility.UrlDecode

will move the issue
