### ISSUE TITLE
RyuJIT x86: Incorrect code motion in long compare codegen

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#7038]
The following program crashes with an `IndexOutOfRangeException`:
```C#
class Program
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static void Test(int[] a, int[] b)
    {
        for (uint i = 0; i < 3UL; i++)
            a[i] = b[i];
    }

    static void Main()
    {
        Test(new int[3], new int[3]);
    }
}
```
Generated code:
```
G_M51005_IG03:
       8975F0       mov      dword ptr [ebp-10H], esi
       3BC6         cmp      eax, esi
       7331         jae      SHORT G_M51005_IG05
       8B5C8208     mov      ebx, dword ptr [edx+4*eax+8]
       897DEC       mov      dword ptr [ebp-14H], edi
       3BC7         cmp      eax, edi
       7326         jae      SHORT G_M51005_IG05
       895C8108     mov      dword ptr [ecx+4*eax+8], ebx
       40           inc      eax
       33DB         xor      ebx, ebx
       BE03000000   mov      esi, 3
       33FF         xor      edi, edi
       8B75F0       mov      esi, dword ptr [ebp-10H] ; these 2 are reloads inserted by LSRA
       8B7DEC       mov      edi, dword ptr [ebp-14H] ; between the compare and the branch
       3BDF         cmp      ebx, edi
       72D6         jb       SHORT G_M51005_IG03
       7704         ja       SHORT G_M51005_IG04
       3BC6         cmp      eax, esi
       72D0         jb       SHORT G_M51005_IG03
```
Dump fragment:
```
  N071.                    il_offset IL offset: 14 REG NA
  N073.                    V02(eax)
  N075. ebx             =  const     0 REG ebx
  N077.                    gt_long  
  N079. esi             =  const     3 REG esi
  N081. edi             =  const     0 REG edi
  N083.                    gt_long  
  N085.                    <        ; eax,ebx,esi,edi
  N001.                    V04(esi)R
  N001.                    V05(edi)R
  N087.                    jmpTrue  
```

This happens because codegen moves the compare code past the reloads and the reloads kill compare operands that have already been consumed.

**Comment by mikedn** [comment]
Found while investigating `JIT\Performance\CodeQuality\BenchI\Pi\Pi\Pi.cmd` failure in #4986.

**Comment by mikedn** [comment]
@BruceForstall @adiaaida This issue appears to have been introduced with #6219 which tried to solve the opposite issue - reloads were execute too late. Now they're executed too early and we're back at square one.

IMO it would be better to deal with long compares in lowering instead of passing them to codegen. I suppose it would be slightly more complicated because it requires flowgraph manipulation but it's probably less risky than doing tricks in codegen. The main drawback of doing it in lowering is that we'll end up with 3 compares instead of 2 because there's currently no optimization that would allow us to reuse the flags from a previous compare. But such an optimization should be added anyway because it's useful in other situations.

Another quick solution is to change `jtrue(cmp(lx, ly))` to `jtrue(ne(cmp(lx, ly), 0)` in lowering. It's easy to implement but produces slightly worse code. Something like:
```C++
GenTree* Lowering::LowerCompare(GenTree* node)
{
    GenTree* next = node->gtNext;
    LIR::Use use;

    if (varTypeIsLong(node->gtGetOp1()) &&
        BlockRange().TryGetUse(node, &use) &&
        (use.User()->OperGet() == GT_JTRUE))
    {
        GenTree* zero = comp->gtNewZeroConNode(node->TypeGet());
        GenTree* test = comp->gtNewOperNode(GT_NE, node->TypeGet(), node, zero);
        BlockRange().InsertAfter(node, zero, test);
        use.ReplaceWith(comp, test);
    }

    return next;
}
```
```
       33DB         xor      ebx, ebx
       BE03000000   mov      esi, 3
       33FF         xor      edi, edi
       3BDF         cmp      ebx, edi
       7502         jne      SHORT G_M51005_IG04
       3BC6         cmp      eax, esi

G_M51005_IG04:
       0F92C3       setb     bl
       0FB6DB       movzx    ebx, bl
       85DB         test     ebx, ebx
       8B75F0       mov      esi, dword ptr [ebp-10H]
       8B7DEC       mov      edi, dword ptr [ebp-14H]
       75CA         jne      SHORT G_M51005_IG03
```

**Comment by mikedn** [comment]
I've made an [experiment](https://gist.github.com/mikedn/db69abfe359867ee788ed590b4c7bc5f) to see how long compare lowering could look and what code would it generate. CQ could be better if temporaries aren't unnecessarily introduced, in this specific case we have constants that could be contained.

**Comment by BruceForstall** [comment]
It does seem like exposing all the flow to liveness and LSRA is the "correct" solution here.

I assume the bug seen above is due to LSRA/liveness thinking the variables die at the GT_CMP, but we actually defer the compare generation to the GT_JTRUE. Presumably another solution would be to "teach" LSRA/liveness about this special-case deferral.

An advantage of introducing flow would be that LSRA has more insight into the liveness of the code, and can insert reloads/spills in more places, probably creating less constrained register allocation.

@CarolEidt @sivarv -- comments?

**Comment by BruceForstall** [comment]
btw, we should really add this as a new test case

**Comment by mikedn** [comment]
Looks like I've ran into another instance of this issue, `JIT\Methodical\int64\arrays\_il_rellcs_ulong\_il_rellcs_ulong.cmd` failed in #7099. Similar loop test with a long compare but this time only registers are involved:
```
G_M42670_IG11:                                  ; eax is live on entry
       8BF3         mov      esi, ebx
       83FE04       cmp      esi, 4
       0F83A5020000 jae      G_M42670_IG28
       8D4CF008     lea      ecx, bword ptr [eax+8*esi+8]
...
       33C0         xor      eax, eax
       8BC1         mov      eax, ecx           ; eax reload overwrites the 0 we just generated
       3BF8         cmp      edi, eax
       0F821CFFFFFF jb       G_M42670_IG11
       7708         ja       SHORT G_M42670_IG14
       3BDA         cmp      ebx, edx
       0F8212FFFFFF jb       G_M42670_IG11
```

**Comment by CarolEidt** [comment]
I think it would be a mistake to add special case support for keeping the sources of the `GT_CMP` live to the branch, unless, I suppose, one were to treat the `GT_CMP` as if it were contained - but that's only a solution if *all* the code generation is deferred until the branch, which is likely to result in considerably more conservative register allocation.

**Comment by BruceForstall** [comment]
@CarolEidt I believe that in this case (long CMP/JMP), all the code generate _is_ deferred until the branch. This was how legacy JIT did it, also.

@mikedn: @sivarv suggested to me that at the GT_JMP, we should assert (currently, until this issue is resolved) that the GT_JMP gtPrev node (previous node in linear order) is the GT_CMP node that is GT_JMP->gtOp1. Would that catch these cases as an assert?

**Comment by BruceForstall** [comment]
@mikedn -- w.r.t. your experiment, I wonder if there's some way we can mark the second branch / compare / block to not require the generation of any cmp, which is unnecessary in this case. We'd have to ensure legality, but presumably we won't have any subsequent flowgraph transformations that would alter this flow structure. There are definitely a lot of temps in your example. Is that because it's minopts?

**Comment by mikedn** [comment]
> all the code generate is deferred until the branch.

Yes, code generation is deferred but operand consumption is not. Ultimately this doesn't work because the deferral is done by codegen and LSRA knows nothing about it. I suppose that a contained `GT_CMP` would fix this. But that means that up to 4 registers will need to be allocated to `GT_JTRUE` and those registers cannot be live at the top loop entry anymore because LSRA now has no place to insert reloads.

>  Would that catch these cases as an assert?

Presumably by assert you mean NYI. I suppose it should work, I'll try it in #7099.

> w.r.t. your experiment, I wonder if there's some way we can mark the second branch / compare / block to not require the generation of any cmp, which is unnecessary in this case. We'd have to ensure legality, but presumably we won't have any subsequent flowgraph transformations that would alter this flow structure.

I was thinking of something like that. The only flowgraph transformation that I've seen in/post lowering is switch lowering, I don't think it will affect cmp/jtrue. But I wonder if we won't need to special case this in LSRA as well, I suspect that we may end up with some unnecessary reloads otherwise.

> There are definitely a lot of temps in your example. Is that because it's minopts?

No, it's because of the temporaries that I have introduced. They're not necessary in this case as one of the operands is already a lclvar and the other a constant. If those temporaries aren't introduced then the generated code is closer to the current version. 

In fact it's even better because we can now contain the constant operands. Currently this doesn't seem to work due to `GT_LONG` nodes that are between the compare and its actual operands. In turn, the lack of containment increases the number of required registers and thus the chances that we spill and reload something (`esi` and `edi` in this case).

**Comment by mikedn** [comment]
Here's how it looks without temporaries:
```
G_M55886_IG02:
       33C0         xor      eax, eax
       8B7204       mov      esi, dword ptr [edx+4]
       8B7904       mov      edi, dword ptr [ecx+4]

G_M55886_IG03:
       3BC6         cmp      eax, esi
       7323         jae      SHORT G_M55886_IG05
       8B5C8208     mov      ebx, dword ptr [edx+4*eax+8]
       3BC7         cmp      eax, edi
       731B         jae      SHORT G_M55886_IG05
       895C8108     mov      dword ptr [ecx+4*eax+8], ebx
       40           inc      eax
       33DB         xor      ebx, ebx
       85DB         test     ebx, ebx
       72E9         jb       SHORT G_M55886_IG03
       33DB         xor      ebx, ebx
       85DB         test     ebx, ebx
       7705         ja       SHORT G_M55886_IG04
       83F803       cmp      eax, 3
       72DE         jb       SHORT G_M55886_IG03
```
There are 2 useless `xor ebx, ebx`. In fact both hi part compares are useless because both high parts are always 0 in this case. But that's another story, probably morph should have caught this.

**Comment by mikedn** [comment]
And a version where the long constant has been replaced with a long method parameter:
```
G_M55886_IG03:
       3B4204       cmp      eax, dword ptr [edx+4]
       7335         jae      SHORT G_M55886_IG05
       8B4C8208     mov      ecx, dword ptr [edx+4*eax+8]
       8B75F0       mov      esi, gword ptr [ebp-10H]
       3B4604       cmp      eax, dword ptr [esi+4]
       7329         jae      SHORT G_M55886_IG05
       894C8608     mov      dword ptr [esi+4*eax+8], ecx
       40           inc      eax
       33C9         xor      ecx, ecx
       8B7D0C       mov      edi, dword ptr [ebp+0CH]
       3BCF         cmp      ecx, edi
       8975F0       mov      gword ptr [ebp-10H], esi
       72DE         jb       SHORT G_M55886_IG03
       33C9         xor      ecx, ecx
       8B7D0C       mov      edi, dword ptr [ebp+0CH]
       3BCF         cmp      ecx, edi
       7707         ja       SHORT G_M55886_IG04
       8B4D08       mov      ecx, dword ptr [ebp+08H]
       3BC1         cmp      eax, ecx
       72CE         jb       SHORT G_M55886_IG03
```
For some reason operand containment fails on all compares.

**Comment by kyulee1** [comment]
This is another instance in System.Collections.Concurrent.ConcurrentQueue`1[__Canon][System.__Canon]:GetHeadTailPositions(byref,byref,byref,byref):this of cscbench.

```
       8B02         mov      eax, dword ptr [edx]
       8B5204       mov      edx, dword ptr [edx+4]
       8B5DE0       mov      ebx, dword ptr [ebp-20H]
       8B5DE4       mov      ebx, gword ptr [ebp-1CH]  ---> ebx for cmp (below) is trashed by this reload.
       3BDA         cmp      ebx, edx
       0F8F44FFFFFF jg       G_M11801_IG03
       7C08         jl       SHORT G_M11801_IG05
       3BC8         cmp      ecx, eax
       0F873AFFFFFF ja       G_M11801_IG03
```

**Comment by pgavlin** [comment]
I think it's pretty clear that the correct long-term solution is to expose all of the control flow and model the `EFLAGS` register in some reasonably first-class manner. In the short term, it sounds like we have two reasonable proposals:
- Mark the comparison as contained and do not expose the internal control flow to LSRA etc. This has the unfortunate side effect of requiring at worst four values live in registers at the jump.
- Fully expose the control flow for the long comparison. A naive implementation requires that all operands to the comparison are spilled into local variables (if they are not already local variables) s.t. they can be referenced by other blocks.

I wonder if there's an intermediate solution here: perhaps we could introduce a new node and jump kind, `JTRUE_HI` and `BBJ_COND_HI`, that allow three successors: one for the target, one for the fallthrough, and one for the low comparison. We could then decompose from IR such as:


```
BB_0 (BBJ_COND):
    ...
    t0 = v0_lo_part
    t1 = v0_hi_part
    t2 = GT_LONG t0, t1
    t3 = v1_lo_part
    t4 = v1_hi_part
    t5 = GT_LONG t3, t4
    GT_GT t2, t5
    GT_JTRUE BB_2

BB_1:
    ...

BB_2:
   ...
```

to

```
BB_0 (BBJ_COND_HI):
    t0 = v0_lo_part
    stloc rat0, t0
    t1 = v0_hi_part
    t3 = v1_lo_part
    stloc rat1, t3
    t4 = v1_hi_part
    GT_GT t1, t4
    JTRUE_HI BB_1, BB_2 ; first label is the original fallthrough block, second is the original target

BB_3 (BBJ_COND):
    t6 = rat0
    t7 = rat1
    GT_GT t6, t7
    JTRUE BB_2

BB_1:
    ...

BB_2:
```

This avoids the need to spill the upper parts of the GT_LONG nodes into lclVars and allows the codegen for the JTRUE_HI to reuse EFLAGS for the second conditional jump while still exposing the independent liveness of the two halves of each long value.

**Comment by pgavlin** [comment]
(perhaps we would also want additional comparison operators with this approach: `GT_GT_HI`, etc.)

**Comment by pgavlin** [comment]
@BruceForstall:

> but presumably we won't have any subsequent flowgraph transformations that would alter this flow structure.

I think that this is correct, but I'm not certain: we do run flowgraph optimization after lowering, but IIRC we don't do anything that would invalidate the necessary layout. Seems like a bit of a risk, though.

**Comment by mikedn** [comment]
> I think it's pretty clear that the correct long-term solution is to expose all of the control flow and model the EFLAGS register in some reasonably first-class manner

Hmm, I was thinking of treating EFLAGS like some kind of global variable and adding GT_COND, GT_SET_COND, GT_CMP and GT_JCC. Sounds a bit crazy I suppose :)

> Mark the comparison as contained and do not expose the internal control flow to LSRA etc. This has the unfortunate side effect of requiring at worst four values live in registers at the jump.

It seems to me that lowering to `jtrue(ne(cmp(lx, ly), 0)` would be better as it gives LSRA freedom to insert reloads between compare and jump. And the generated code isn't as bad as I thought initially, after all it trades a `jcc` for a `setcc` and adds a `movzx` and a `test` which are cheap.

> Fully expose the control flow for the long comparison. A naive implementation requires that all operands to the comparison are spilled into local variables (if they are not already local variables) s.t. they can be referenced by other blocks.

Experimental PR #7165.

> I wonder if there's an intermediate solution here: perhaps we could introduce a new node and jump kind, JTRUE_HI and BBJ_COND_HI, that allow three successors: one for the target, one for the fallthrough, and one for the low comparison. We could then decompose from IR such as:

I thought about that but it seems like a very intrusive solution as some flow graph handling functions will probably have to be changed to support the new kind of block.

**Comment by pgavlin** [comment]
> Hmm, I was thinking of treating EFLAGS like some kind of global variable and adding GT_COND, GT_SET_COND, GT_CMP and GT_JCC. Sounds a bit crazy I suppose :)

This isn't too far off from some of what I was considering.

> It seems to me that lowering to jtrue(ne(cmp(lx, ly), 0) would be better as it gives LSRA freedom to insert reloads between compare and jump. And the generated code isn't as bad as I thought initially, after all it trades a jcc for a setcc and adds a movzx and a test which are cheap.

Is the `GT_NE` there just to force the result of the `cmp` into a register? If so, I wonder if there's another way to achieve the same effect without adding the `GT_NE` node. @sivarv @CarolEidt any suggestions?

> I thought about that but it seems like a very intrusive solution as some flow graph handling functions will probably have to be changed to support the new kind of block.

It is probably rather intrusive, yes: liveness, flow graph optimization, etc. would need to be updated. Perhaps a hybrid of this and @BruceForstall's suggestion would be best: introduce a new niladic node, `GT_JTRUE_HI`, that is used to generate the second `jcc`. This node must be the only node in its containing block and must immediately succeed the `GT_JTRUE` used for the first part of the high comparison.

**Comment by mikedn** [comment]
> It seems to me that lowering to jtrue(ne(cmp(lx, ly), 0) would be better

So if we look at the assembly generated in this case:
```
       3BDF         cmp      ebx, edi
       7502         jne      SHORT G_M51005_IG04
       3BC6         cmp      eax, esi

G_M51005_IG04:
       0F92C3       setb     bl
       0FB6DB       movzx    ebx, bl
       85DB         test     ebx, ebx
       8B75F0       mov      esi, dword ptr [ebp-10H]
       8B7DEC       mov      edi, dword ptr [ebp-14H]
       75CA         jne      SHORT G_M51005_IG03
```
What stops us from changing it to
```
       3BDF         cmp      ebx, edi
       7502         jne      SHORT G_M51005_IG04
       3BC6         cmp      eax, esi

G_M51005_IG04:
       8B75F0       mov     esi, dword ptr [ebp-10H]
       8B7DEC       mov     edi, dword ptr [ebp-14H]
       75CA         jb      SHORT G_M51005_IG03
```
which is better than what JIT32 produces (ignoring compare operands containment issues)?

**Comment by pgavlin** [comment]
@mikedn: I experimented with adding a new node, `GT_JCC`, on top of the changes in your PR: https://github.com/mikedn/coreclr/compare/x86-cmp-long...pgavlin:x86-cmp-long

With this approach, RyuJIT generates the following for the long compare in the test program you posted:

```
       85DB         test     ebx, ebx
       7707         ja       SHORT G_M50523_IG04
       72E7         jb       SHORT G_M50523_IG03
       83F803       cmp      eax, 3
       72E2         jb       SHORT G_M50523_IG03
```

This is identical to the code generated by JIT32 with the exception of the register allocations. The full disassembly for RyuJIT and JIT32 can be found [here](https://gist.github.com/pgavlin/323ff73e061ea4aa70ed7a1af43c1c97) and [here](https://gist.github.com/pgavlin/0bf88a1228d16fa0069fe74fc295bfe4), repsectively.

**Comment by mikedn** [comment]
> Is the GT_NE there just to force the result of the cmp into a register?

Yes.

>  If so, I wonder if there's another way to achieve the same effect without adding the GT_NE node

We should be able to modify `TreeNodeInfoInit` to not clear destination count of the compare when handling `GT_JTRUE`. And then we probably need to generate a `test` as part of `GT_JTRUE` codegen.

But I played a bit more with this approach and realized that its CQ isn't great. The examples I posted above are ok but that's for unsigned compares. For signed compares we need two `setcc` instead of one and a `jmp` so it's worse than what JIT32 did. Besides, this approach doesn't solve the issue of the compare requiring up to 4 registers.

> I experimented with adding a new node, GT_JCC, on top of the changes in your PR

Cool, thanks! I see that you also got rid of the extra edges that caused 2 tests to fail.

I'm a bit concerned about `GT_JCC` pulling data out of thin air but after all that's how `GT_JTRUE` already works, it expects that there's nothing that can modify flags between it and its compare operand. Same for `GT_ADD_HI`/`GT_ADD_LO`.

I'm also wondering if it will be useful in other cases (removing redundant compares) or it will be only a long compare specific workaround.

**Comment by pgavlin** [comment]
> I'm a bit concerned about GT_JCC pulling data out of thin air but after all that's how GT_JTRUE already works, it expects that there's nothing that can modify flags between it and its compare operand. Same for GT_ADD_HI/GT_ADD_LO.

This is how I fell as well. FWIW, it probably wouldn't be too much work to do some basic validation of flags usage by marking nodes that produce and consume flags. Given the transformations done by the backend we could probably get away with something as simple as "if an instruction produces flags, those flags must be consumed by some successive instruction" (i.e. there are no unused defs of EFLAGS).

> I'm also wondering if it will be useful in other cases (removing redundant compares) or it will be only a long compare specific workaround.

I think that it could be useful for such cases, but probably not without a more formal modeling of the flags.

If you're comfortable with the approach, I can go ahead and submit a PR based on the changes in my branch (or you can incorporate those changes into your own and update your pre-existing PR).

**Comment by mikedn** [comment]
> If you're comfortable with the approach, I can go ahead and submit a PR based on the changes in my branch (or you can incorporate those changes into your own and update your pre-existing PR).

Let's do this. IMO there should be 2 separate commits/PRs, one for `GT_JCC` and one for compare lowering since they're more or less independent.

**Comment by pgavlin** [comment]
SGTM. I'll move the changes that are independent of `GT_JCC` into a single commit and post a PR with 1 commit each for the compare decomposition and the introduction of `GT_JCC`.
