### ISSUE TITLE
Space requirements for coreclr build

### ISSUE THREAD

**Issue by cydhaselton** [dotnet/coreclr#7039]
I'm currently building coreclr on an Android tablet.  What are the space requirements for this and the corefx build?

**Comment by gkhanna79** [comment]
Are you looking for space requirements for the built binaries to execute OR to build on an Android VM itself?

**Comment by cydhaselton** [comment]
I was looking for space requirements to build on Android; I've since found out they are larger than the capacity of a "standard" Android device.
