### ISSUE TITLE
C# generic is so expensive?

### ISSUE THREAD

**Issue by egmkang** [dotnet/coreclr#7053]
```
class Test<T> where T : new()
{
      public static T Instance()
      {
          return new T();
      }
}
```

on x86:
`Test<object>.Instance()` : `90 ~ 100 ns/op`
`new object` : `5.0 ~ 5.8 ns/op`
on x64:
`Test<object>.Instance()` : `76 ns/op`
`new object` : `2.7 ns/op`

why generic code runs so slow, and should i avoid using generic code?

PS:
i got it.
C# translate `new T()` into `System.Activator.CreateInstance<T>()`.

**Comment by mikedn** [comment]
Generic code is normally just as fast as non-generic code but there are a few patterns that are slower. `new T()` is probably the slowest of them all as it is translated to a call to `Activator.CreateInstance` which is rather slow. If this is a problem in your code then you could pass a factory method via a delegate, should be faster and also allows you to pass parameters.

**Comment by danmosemsft** [comment]
This discussion seems to have ended. Feel free to reopen..
