### ISSUE TITLE
Array.CreateInstance allows an array of a static class

### ISSUE THREAD

**Issue by hughbe** [dotnet/coreclr#7057]
The following test demonstrates this.
```
[Fact]
public void CreateInstance_StaticClass_Works()
{
    Array array = Array.CreateInstance(typeof(StaticClass), 5);
    Assert.Null(array.GetValue(0));
}
public static class StaticClass { }
```

However, C# doesn't allow arrays of static classes:
```
var x = new StaticClass[2];
// ERROR: "'StaticClass': array elements cannot be of a static type"
```

I'd be interested in hearing if this is by design (if so, why), or just an oversight.

**Comment by jkotas** [comment]
I believe that this is by design. IL and BCL are sometimes more permissive than C# language. There are actually quite a few of similar corner case mismatches, `sizeof(T)` - valid and verifiable in IL, disallowed in C#.

**Comment by mikedn** [comment]
There's no such thing as static class, that's a sealed abstract class. As far as the runtime is concerned there's no reason to block the creation of an array of this class. Sure, such an array is kind of pointless but that doesn't imply that it is also invalid.

**Comment by hughbe** [comment]
Thanks for the info - I'll close this off then
