### ISSUE TITLE
StreamReader.ReadBuffer should not be virtual

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#7060]
It's an [internal virtual method](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/StreamReader.cs#L563) that is overriden nowhere except `NullStreamReader`. Since it's used in many places throughout the class, like `ReadToEnd` / `ReadLine` / etc, it may be worthwhile to make it non-virtual.

**Comment by gkhanna79** [comment]
CC @danmosemsft @AlexGhiondea

**Comment by karelz** [comment]
Does not look like must have for 2.0

**Comment by WinCPP** [comment]
@karelz If I am not missing something, this looks like simple code clean up. May I grab it?

**Comment by karelz** [comment]
Let's check with IO owners first that it won't have any undesired side-effect, esp. on appcompat ... @ianhays @JeremyKuhne can you please chime in?
Assigning to you ...

**Comment by karelz** [comment]
@WinCPP invitations are per repo (GitHub restriction), please accept and ping me, I will assign it to you then.

**Comment by WinCPP** [comment]
@karelz Thanks. I got the invitation and have accepted it. Between, I did subbmit code changes for CoreClr for one of the CoreFx issues which required API addition, but that time it allowed me do check-ins in CoreClr without formal invitation... Just thought I would bring this to your notice if there was some gap in following processes on my side.

I will wait for inputs from IO owners as you have suggested...

**Comment by karelz** [comment]
GitHub supports assigning issues to their authors, to repo collaborators (requires the invite) and to organization members (also requires invite). Last time you created the PR, so you were author. This time you are not ;-)

**Comment by ianhays** [comment]
>Let's check with IO owners first that it won't have any undesired side-effect, esp. on appcompat ... @ianhays @JeremyKuhne can you please chime in?

There isn't any that I can think of. Being internal means we don't have to worry too much about changing it as long as we're sure it isn't being overridden anywhere important.

**Comment by karelz** [comment]
Thanks for confirmation @ianhays! I thought so as well, but I didn't feel brave enough to make general claims ;-)
@WinCPP you have green light on the change ;-)

**Comment by karelz** [comment]
@ianhays would it make sense to move the issue into IO area path? (I don't have strong opinion here)

**Comment by ianhays** [comment]
>would it make sense to move the issue into IO area path?

Yes.

**Comment by WinCPP** [comment]
Thanks @ianhays @karelz will start working on this!
