### ISSUE TITLE
Are the *_Prop properties in StreamReader and StreamWriter still needed?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#7061]
There are a [bunch of properties,](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/StreamReader.cs#L1114) such as `CharLen_Prop` in StreamReader, that seemingly just wrap an underlying field except with an uglier syntax. This is apparently for "performance for MarshalByRefObject-derived types," since accessing instance fields of such objects is slow. However, I fail to see how these properties make things any faster, since all they do is wrap the underlying field (and their accessors will probably be inlined). Maybe it would be OK to remove them?

cc @jkotas

**Comment by jkotas** [comment]
The field access for objects that derive from MarshalByRefObject is not always single instruction. It is sometimes compiled into calls to JIT helpers like `JIT_GetField32` on platforms that support remoting.

StreamReader/StreamWriter do not inherit from MarshalByRefObject, so the problem with slow field access does not actually exist for them. I checked the history - somebody was fixing the issue with slow field access in a number of places, and it looks like the workarounds were applied to more places than necessary.

It should be fine to remove these useless private properties from StreamReader/Writer.

**Comment by karelz** [comment]
Does not look like must have for 2.0.

**Comment by WinCPP** [comment]
@jamesqo @jkotas @karelz May I work on this?

**Comment by karelz** [comment]
Sure @WinCPP, go for it.
@jkotas should be able to provide guidance if needed.

**Comment by jkotas** [comment]
We have not unified the StreamReader/Writer between CoreCLR and CoreRT yet. The CoreCLR one lives in CoreCLR repo, the CoreRT one lives in CoreFX repo. Could you please do the same change in both places? It should be a simple find&replace.

**Comment by WinCPP** [comment]
@jkotas Yup. I will make the required changes for CoreRT as well...

**Comment by WinCPP** [comment]
@jamesqo @jkotas I could not find implementation for StreamWriter in CoreClr repo. Just wanted to confirm that there isn't any in CoreClr repo...

**Comment by jkotas** [comment]
You are right ... there is no StreamWriter in CoreCLR repo.
