### ISSUE TITLE
RyuJIT x86: Assertion failed '!comp->getNeedsGSSecurityCookie()'

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7086]
In Windows_NT.ryujit.x86.Checked.jit_stress.2.jit_stress_regs.0x10

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStress=2
set COMPlus_JitStressRegs=0x10

/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b441487/b441487/b441487.cmd

> D:\j\workspace\x86_ryujit_ch---b330cdd2\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(366081): error : JIT._Regression_CLR_x86_JIT_V2_0_Beta2_b441487_b441487_b441487_._Regression_CLR_x86_JIT_V2_0_Beta2_b441487_b441487_b441487_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---b330cdd2\tests\runtest.proj]
> Assert failure(PID 1816 [0x00000718], Thread: 7556 [0x1d84]): Assertion failed '!comp->getNeedsGSSecurityCookie()' in 'Test.FooException`1[Int32][System.Int32]:.ctor():this' (IL size 7)
> File: d:\j\workspace\x86_ryujit_ch---b330cdd2\src\jit\lower.cpp Line: 1697
> Image: D:\j\workspace\x86_ryujit_ch---b330cdd2\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---b330cdd2\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b441487\b441487\b441487.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---b330cdd2\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" b441487.exe
> Running tests for System.String
> Foo
> hello from System.String
> CatchMe
> Test.FooException`1[System.String]: hello from System.String
> at Test.Widget`1.CatchMe() in D:\j\workspace\x86_ryujit_ch---b330cdd2\tests\src\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b441487\b441487.il:line 120
> SyncIt
> hello from System.String
> Running tests for System.Int32
> Foo
> hello from System.Int32
> CatchMe
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

**Comment by BruceForstall** [comment]
There are many, many cases in the stress runs. Here's another:

JIT\Methodical\tailcall\_il_reldeep_inst\_il_reldeep_inst.cmd
