### ISSUE TITLE
Fix or document the requirement for LD_LIBRARY_PATH to be set to the runtime path

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#709]
After the change to move PAL to a separate module (libcoreclrpal.so) is causing the following problem. A workaround for now is to set the LD_LIBRARY_PATH environment variable to the runtime binaries (where corerun/lib* are). The reason we didn’t hit this problem is because LD_LIBRARY_PATH is required to use the lldb sos plugin and debugger binaries.  

We need to look at removing the environment variable requirement by looking for libraries in corerun's directory or document this new requirement.

./corerun HelloWorld.exe linux
dlopen failed to open the libcoreclr.so with error libcoreclrpal.so: cannot open shared object file: No such file or directory

**Comment by janvorli** [comment]
@mikem8361, the libcoreclrpal.so should be in the same folder as the libcoreclr.so. Then there won't be any problem, I believe.

**Comment by mikem8361** [comment]
Yes, libcoreclrpal.so is the same directory as libcoreclr.so and you would expect it to be found by the Linux loader, but that doesn’t seem to be the case.  If I remove my LD_LIBRARY_PATH, corerun fails like the issue says.  It looks like from the dlopen man page that only the path is searched and not the directory the loading module is in:

The function dlopen() loads the dynamic library file named by the null-terminated string filename and returns an opaque "handle" for the dynamic library.  If filename  is
       NULL,  then the returned handle is for the main program.  If filename contains a slash ("/"), then it is interpreted as a (relative or absolute) pathname.  Otherwise, the
       dynamic linker searches for the library as follows (see ld.so(8) for further details):

       o   (ELF only) If the executable file for the calling program contains a DT_RPATH tag, and does not contain a DT_RUNPATH tag, then the directories listed in the  DT_RPATH
           tag are searched.

       o   If,  at  the  time that the program was started, the environment variable LD_LIBRARY_PATH was defined to contain a colon-separated list of directories, then these are
           searched.  (As a security measure this variable is ignored for set-user-ID and set-group-ID programs.)

       o   (ELF only) If the executable file for the calling program contains a DT_RUNPATH tag, then the directories listed in that tag are searched.

       o   The cache file /etc/ld.so.cache (maintained by ldconfig(8)) is checked to see whether it contains an entry for filename.

       o   The directories /lib and /usr/lib are searched (in that order).

       If the library has dependencies on other shared libraries, then these are also automatically loaded by the dynamic linker using the same rules.  (This process  may  occur
       recursively, if those libraries in turn have dependencies, and so on.)

**Comment by janvorli** [comment]
I am sorry, I have realized that I am wrong and deleted the message. Obviously, it has reached you before that.
This is unfortunate, since we want all shared libs to be in the same folder together, but not necessarily together with the corerun. The corerun has a command line option to specify where the shared libs are stored.
I actually wonder if setting the LD_LIBRARY_PATH in the corerun to contain the path from which we load the libcoreclr.so would fix the issue. That might be the easiest fix. Since we would set the env var before attempting to load libcoreclr.so, it seems it could work.

**Comment by mikem8361** [comment]
The variable has to be set before the process is started.  I think I tried this for the debugger modules and it didn’t work.

o   If,  at  the  time that the program was started, the environment variable LD_LIBRARY_PATH was defined to contain a colon-separated list of directories, then these are
           searched.  (As a security measure this variable is ignored for set-user-ID and set-group-ID programs.)

**Comment by janvorli** [comment]
@mikem8361, I was thinking about it a bit more and I think that we can overcome the issue by preloading the libcoreclrpal.so before the libcoreclr.so is loaded in the corerun. I think that when the libcoreclrpal.so is already loaded in the process, the libcoreclr.so will pick it.

**Comment by mikem8361** [comment]
I’ll try that and if it works use that to fix this issue.

**Comment by ellismg** [comment]
We will need to make the same fixes to DNX.
