### ISSUE TITLE
RyuJIT x86: Assertion failed 'VarSetOps::Equal(this, VarSetOps::Intersection(this, life, block->bbLiveIn), life)'

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7090]
In Windows_NT.ryujit.x86.Checked.jit_stress.2.jit_stress_regs.0x80

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStress=2
set COMPlus_JitStressRegs=0x80

/JIT/opt/virtualstubdispatch/bigvtbl/bigvtbl_cs_d/bigvtbl_cs_d.cmd

> D:\j\workspace\x86_ryujit_ch---945650c9\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(300669): error : JIT._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_d_bigvtbl_cs_d_._opt_virtualstubdispatch_bigvtbl_bigvtbl_cs_d_bigvtbl_cs_d_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---945650c9\tests\runtest.proj]
> Assert failure(PID 3096 [0x00000c18], Thread: 7756 [0x1e4c]): Assertion failed 'VarSetOps::Equal(this, VarSetOps::Intersection(this, life, block->bbLiveIn), life)' in 'CTest:Main():int' (IL size 149274)
> File: d:\j\workspace\x86_ryujit_ch---945650c9\src\jit\liveness.cpp Line: 3058
> Image: D:\j\workspace\x86_ryujit_ch---945650c9\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---945650c9\bin\tests\Windows_NT.x86.Checked\Reports\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_d\bigvtbl_cs_d.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---945650c9\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" bigvtbl_cs_d.exe
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

**Comment by BruceForstall** [comment]
I don't see this assert. I do see a crash:
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory
is corrupt.
   at System.Console.OpenStandardOutput()
   at System.Console.<>c.<get_Out>b__25_0()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at CTest.Main() in D:\gh\coreclr3\tests\src\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl.cs:line 15051
```
