### ISSUE TITLE
RyuJIT x86: Assertion failed 'currentInterval && (currentInterval->isLocalVar || currentRefPosition->isFixedRegRef || currentInterval->hasConflictingDefUse)'

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7091]
Windows_NT.ryujit.x86.Checked.jit_stress_regs.8

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStressRegs=8

/JIT/jit64/rtchecks/overflow/overflow01_sub/overflow01_sub.cmd

> D:\j\workspace\x86_ryujit_ch---f8df01d4\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(128997): error : JIT._jit64_rtchecks_overflow_overflow01_sub_overflow01_sub_._jit64_rtchecks_overflow_overflow01_sub_overflow01_sub_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---f8df01d4\tests\runtest.proj]
> Assert failure(PID 8196 [0x00002004], Thread: 8780 [0x224c]): Assertion failed 'currentInterval && (currentInterval->isLocalVar || currentRefPosition->isFixedRegRef || currentInterval->hasConflictingDefUse)' in 'OVFTest:Test_byte(ubyte):ubyte' (IL size 18)
> File: d:\j\workspace\x86_ryujit_ch---f8df01d4\src\jit\lsra.cpp Line: 6943
> Image: D:\j\workspace\x86_ryujit_ch---f8df01d4\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---f8df01d4\bin\tests\Windows_NT.x86.Checked\Reports\JIT\jit64\rtchecks\overflow\overflow01_sub\overflow01_sub.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---f8df01d4\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" overflow01_sub.exe
> Runtime Checks [OP: sub.ovf]
> Type 'byte' . . : Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

**Comment by BruceForstall** [comment]
cc @CarolEidt @sivarv

**Comment by sivarv** [comment]
This is a JitStressRegs=8 only issue on x86.

**Comment by sivarv** [comment]
On further investigation, this turns out to be a non-stress mode issue caused by an aggressive assert.
