### ISSUE TITLE
RyuJIT x86: Assertion failed 'emitVerifyEncodable(ins, EA_SIZE(attr), ireg)'

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7092]
In Windows_NT.ryujit.x86.Checked.jit_stress_regs.1

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStressRegs=1

/JIT/Regression/JitBlue/DevDiv_199169/DevDiv_199169/DevDiv_199169.cmd

> D:\j\workspace\x86_ryujit_ch---95c7955c\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(373533): error : JIT._Regression_JitBlue_DevDiv_199169_DevDiv_199169_DevDiv_199169_._Regression_JitBlue_DevDiv_199169_DevDiv_199169_DevDiv_199169_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---95c7955c\tests\runtest.proj]
> Assert failure(PID 9792 [0x00002640], Thread: 9136 [0x23b0]): Assertion failed 'emitVerifyEncodable(ins, EA_SIZE(attr), ireg)' in '<Module>:main(ref):int' (IL size 58)
> File: d:\j\workspace\x86_ryujit_ch---95c7955c\src\jit\emitxarch.cpp Line: 4364
> Image: D:\j\workspace\x86_ryujit_ch---95c7955c\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---95c7955c\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Regression\JitBlue\DevDiv_199169\DevDiv_199169\DevDiv_199169.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---95c7955c\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" DevDiv_199169.exe
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

**Comment by BruceForstall** [comment]
The problem is genCodeForInitBlkUnroll() is trying to generate:
```
mov byte ptr [edi], si
```
here:
```
    if ((size & 1) != 0)
    {
        emit->emitIns_AR_R(INS_mov, EA_1BYTE, valReg, dstAddr->gtRegNum, offset);
    }
```
which is not legal: ebp/esi/edi/esp don't have byte register versions on x86.

Note that legacy JIT generates `stosb` for this test.
