### ISSUE TITLE
x86: Assertion failed 'genActualType(tree->gtType) == TYP_LONG'

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7093]
Note that this is in codegenlegacy.cpp, suggesting that the fallback is failing in this particular case.

Windows_NT.ryujit.x86.Checked.jit_stress.2.jit_stress_regs.4

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStress=2
set COMPlus_JitStressRegs=4

/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b309548/b309548/b309548.cmd

> D:\j\workspace\x86_ryujit_ch---5357ccf8\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(385056): error : JIT._Regression_VS_ia64_JIT_V2_0_Beta2_b309548_b309548_b309548_._Regression_VS_ia64_JIT_V2_0_Beta2_b309548_b309548_b309548_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---5357ccf8\tests\runtest.proj]
> Assert failure(PID 6492 [0x0000195c], Thread: 3368 [0x0d28]): Assertion failed 'genActualType(tree->gtType) == TYP_LONG' in 'AA:Static3(char):ref' (IL size 73)
> File: d:\j\workspace\x86_ryujit_ch---5357ccf8\src\jit\codegenlegacy.cpp Line: 13220
> Image: D:\j\workspace\x86_ryujit_ch---5357ccf8\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---5357ccf8\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Regression\VS-ia64-JIT\V2.0-Beta2\b309548\b309548\b309548.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---5357ccf8\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" b309548.exe
> Testing AA::Static3
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

**Comment by BruceForstall** [comment]
The only thing required to repro is:
```
set COMPlus_JitStress=2
```
(no need to set COMPlus_AltJit, COMPlus_AltJitName, COMPlus_JitStressRegs)
