### ISSUE TITLE
RyuJIT x86: Assertion failed 'regRecord->assignedInterval == nullptr'

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7094]
Windows_NT.ryujit.x86.Checked.jit_stress_regs.3

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStressRegs=3

/JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b71099/b71099/b71099.cmd

> D:\j\workspace\x86_ryujit_ch---9ec8b55e\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(351660): error : JIT._Regression_CLR_x86_JIT_V1_M12_Beta2_b71099_b71099_b71099_._Regression_CLR_x86_JIT_V1_M12_Beta2_b71099_b71099_b71099_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---9ec8b55e\tests\runtest.proj]
> Assert failure(PID 3644 [0x00000e3c], Thread: 5700 [0x1644]): Assertion failed 'regRecord->assignedInterval == nullptr' in 'Test.AA:Static3(byref,byref):bool' (IL size 110)
> File: d:\j\workspace\x86_ryujit_ch---9ec8b55e\src\jit\lsra.cpp Line: 11256
> Image: D:\j\workspace\x86_ryujit_ch---9ec8b55e\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---9ec8b55e\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b71099\b71099\b71099.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---9ec8b55e\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" b71099.exe
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

**Comment by BruceForstall** [comment]
cc @CarolEidt @sivarv
