### ISSUE TITLE
RyuJIT x86: Assert failure '!emitComp->opts.compReloc || memBase->IsIconHandle()' while ngen'ing mscorlib

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#7100]
'!emitComp->opts.compReloc || memBase->IsIconHandle()' in 'System.Security.Cryptography.RSASignaturePadding:Equals(ref):bool:this'

    File: d:\projectk2\src\ndp\clr\src\jit\emitxarch.cpp Line: 3735

**Comment by BruceForstall** [comment]
We're trying to generate
```
cmp ebx, dword ptr [0000H]
```
(due to inlining). But, emitInsBinary() doesn't expect a zero address that is not a relocatable handle.
