### ISSUE TITLE
dynamic does not work with internal visibility and InternalsVisibleTo

### ISSUE THREAD

**Issue by treziac** [dotnet/coreclr#7103]
Using VS2015 Update 3 with netcoreapp1.0
(sdk: "1.0.0-preview2-003121")
- Create an assembly with a class A with internal property `prop`
- Make this assembly visible to an other assembly : `[assembly: InternalsVisibleTo("Test")]`
- in assembly Test, try to access prop with both dynamic and typed variables : 

```
var typed = new A();
dynamic dyn = new A();
```

`typed.prop` works but `dyn.prop`generates RuntimeBinderException

In net451-net461, both work

**Comment by mklinke** [comment]
I can confirm this also for VS2017 with netcoreapp1.1, sdk 1.0.0.

**Comment by gkhanna79** [comment]
@jaredpar Is this being targeted for 2.0?

**Comment by jaredpar** [comment]
@VSadov can you take a look at this?

**Comment by VSadov** [comment]
Will take a look. It could be that we do something different, but also could be that reflection behaves differently.

**Comment by gkhanna79** [comment]
@jaredpar Is this for 2.0? If not, can you please move this out?

**Comment by VSadov** [comment]
Looking at this right now. We should fix this in 2.0 unless it is really hard to do.

**Comment by VSadov** [comment]
The bug appears to be fixed by the switch to the newly re-added API for comparing assembly names.
(https://github.com/dotnet/corefx/commit/501c2632493796ba50b43ec06d2e930cd556fc23)

Adding a test: 
https://github.com/dotnet/corefx/pull/19265
