### ISSUE TITLE
[RC2] CoreCLR has various issues on systems with SELinux enabled

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#711]
Commit [57f1e08](https://github.com/dotnet/coreclr/commit/57f1e08d204dc9af74e3e56375c79e23cf476703) added some code to support managed debugging that attempts to elevate the permissions on a heap-allocated page from RW to RWX. SELinux's execheap module rejects the call, causing the debugger to assert and the runtime to eventually segfault.

SELinux log message (from `/var/log/audit/audit.log`):

```
type=AVC msg=audit(1429132481.885:2941): avc:  denied  { execheap } for  pid=13929 comm="corerun" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0
```

corerun output (abridged):

```
Assert failure (unable to format)
/home/pgavlin/dev/coreclr/src/debug/ee/debugger.cpp
!"VirtualProtect failed to make this memory executable"
**** MessageBox invoked, title 'Assert failure (unable to format)' ****
  !"VirtualProtect failed to make this memory executable"
********

{0x371e-0x7eff96758fb0} ASSERT [EXCEPT ] at /home/pgavlin/dev/coreclr/src/pal/src/exception/signal.cpp.566: Unhandled hardware exception
...repeats...
{0x371e-0x7eff96758fb0} ASSERT [EXCEPT ] at /home/pgavlin/dev/coreclr/src/pal/src/exception/signal.cpp.566: Unhandled hardware exception
Segmentation fault (core dumped)
```

**Comment by pgavlin** [comment]
@ellismg @stephentoub @janvorli @Djuffin @mikem8361 FYI.

I am not sure what happens when running a release build, but I suspect that things will appear to work until the debugger support attempts to emit code into an allocation and execute the result.

**Comment by pgavlin** [comment]
It's worth noting that Fedora and RHEL both ship with SELinux enabled by default.

**Comment by Djuffin** [comment]
I'll look into the way JIT allocates executable memory and will try to do the same for debugger heap.

**Comment by pgavlin** [comment]
The JIT emits code into a `LoaderHeap` that has been created with `fMakeExecutable` set to `TRUE`, so all of its pages are mapped in with the correct protections. You'll probably need to ensure that the debugger allocates its memory similarly.

**Comment by pgavlin** [comment]
The relevant `LoaderHeap` (actually `UnlockedLoaderHeap`) constructor is here: https://github.com/dotnet/coreclr/blob/master/src/utilcode/loaderheap.cpp#L901-L954

Part of the relevant code in the VM is here (I think):https://github.com/dotnet/coreclr/blob/master/src/vm/loaderallocator.cpp#L996-L1008

**Comment by pgavlin** [comment]
FWIW, I've verified that a release build of CoreCLR runs successfully despite the `VirtualProtect` failure. I have not tried managed debugging.

**Comment by pgavlin** [comment]
Bumping this. I've noticed that on recent Fedora releases (FC22 at least) this causes extremely high CPU usage due to the audit failures triggering `setroubleshootd`.

**Comment by pgavlin** [comment]
(Oh, and I should not that the extremely high CPU usage is something that triggers on all builds, not just debug builds)

**Comment by joshfree** [comment]
moving this SELinux bug up from rtm to rc2. /cc @tzwlai

**Comment by rhatdan** [comment]
Does turning on the allow_execheap  help the problem?

setsebool -P allow_execheap 1

**Comment by adityamandaleeka** [comment]
#2264 has been merged. Breakpoints and funcevals, which were both previous trying to allocate executable memory on the heap, will no longer do so on platforms where `FEATURE_PAL` is defined.

I believe this issue can be closed if there are no other problems.

**Comment by pgavlin** [comment]
I can confirm that this appears to be fixed.

**Comment by Djuffin** [comment]
@adityamandaleeka Good job!
