### ISSUE TITLE
RyuJIT x86: NYI: "Rotation of a long value by variable amount"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7110]
This NYI:

NYI: "Rotation of a long value by variable amount"
File: coreclr\src\jit\morph.cpp:14244

Is hit in these tests:
JIT\CodeGenBringUpTests\Rotate\Rotate.cmd

**Comment by adiaaida** [comment]
In legacy backend, we don't do any special handling of rotates. This assert is for a very specific case where:

!shiftIndexWithoutAdd->IsCnsIntOrI() && (rotatedValueBitSize == 64)

The comment suggests introducing a helper here. Another option is to do what legacy backend does and just return the original tree.

**Comment by mikedn** [comment]
> In legacy backend, we don't do any special handling of rotates

JIT32 didn't have any kind of rotation support, this was added recently to RyuJIT x64 by @erozenfeld in #1830.

> The comment suggests introducing a helper here. Another option is to do what legacy backend does and just return the original tree.

IMO we should simply disable this optimization for long on x86. Using a helper won't be very efficient anyway.

**Comment by adiaaida** [comment]
@mikedn That's what I was thinking too.

**Comment by erozenfeld** [comment]
If we return the original tree we will end up with two helper calls: CORINFO_HELP_LLSH and CORINFO_HELP_LRSZ. Introducing a helper for rotations will save a helper call and also can use rol/ror if shift index is between 0 and 31.

**Comment by adiaaida** [comment]
@RussKeldorph

**Comment by RussKeldorph** [comment]
We should do the expedient thing to get it correct now and track the single-helper option as an optimization issue.

**Comment by erozenfeld** [comment]
SGTM as long as we have an issue opened to track that

**Comment by adiaaida** [comment]
closed by #7187.
Opened #7192 to track optimizing this case.
