### ISSUE TITLE
Encoding.GetString throwing NullReferenceException when used with CodePagesEncodingProvider

### ISSUE THREAD

**Issue by slozier** [dotnet/coreclr#7124]
The following code is throwing an unexpected `NullReferenceException` on the last line:
```
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
Encoding e = Encoding.GetEncoding(1252, EncoderFallback.ExceptionFallback, DecoderFallback.ExceptionFallback);            
byte[] bytes = e.GetBytes("abc");
Console.WriteLine(e.GetString(bytes));
```
Also fails on net46, but works (on net46) if I comment out the first line.

**Comment by tarekgh** [comment]
This is fixed with the PR https://github.com/dotnet/corefx/pull/11485

the nuget package containing the fix looks not published yet on https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Text.Encoding.CodePages but should get published soon
