### ISSUE TITLE
Parameter "targetPlatformVersion" cannot be null - SDK 10.0.14393.0

### ISSUE THREAD

**Issue by eyasso** [dotnet/coreclr#7134]
Hello,
When trying to create new UWP project I am getting following error: "error : Parameter "targetPlatformVersion" cannot be null.".
csproj were not created.
I have Visual Studio 2015 community update 3 installed on clean OS.
I have installed SDK 10.0.14393.0 and my Windows 10 is up to date with all updates.
Has anyone else encountered that?
I’d appreciate you help.

**Comment by gkhanna79** [comment]
@barrytang Which repo this issue move to?

**Comment by barrytang** [comment]
@srivatsn @Pilchie ?

**Comment by Pilchie** [comment]
This should be filed internally against the UWP tools team.

**Comment by gkhanna79** [comment]
@Pilchie Can you please file an issue internally and close this one?

**Comment by gkhanna79** [comment]
Filed an internal issue and closing this.

**Comment by borrrden** [comment]
What is the status of this?  I am running up against this in my CI environment.
