### ISSUE TITLE
[Linux][SOS] Show local variables using gdb-jit interface 

### ISSUE THREAD

**Issue by lucenticus** [dotnet/coreclr#7138]
I'm working on implementation of  Dwarf information generation for local variables using gdb-jit interface.  The major issue I met is mapping native vars to IL vars. I successfully get native vars info `ICorDebugInfo::NativeVarInfo` by calling `DebugInfoManager::GetBoundariesAndVars`, but I don't know how to map `NativeVarInfo` to IL variables. @mikem8361, @janvorli, could you guide us how can we get such information?

\CC: @Dmitri-Botcharnikov @chunseoklee

**Comment by mikem8361** [comment]
I probably won’t be much help with this. There are still parts of the debugging code I’m still getting up to speed on myself.  Maybe one of Jan’s or Noah can help.

@noahfalk @jkotas

**Comment by noahfalk** [comment]
Try looking at CordbNativeCode::ILVariableToNative(...) in 
https://github.com/dotnet/coreclr/blob/6e3c1a63e683b9c825c218efc6d75bf5e430f474/src/debug/di/module.cpp. I didn't check if the exact code you need is right there, but its probably a good place to start following the code.

Under the paradigm of giving a man a fish vs. teaching how to fish, I didn't recall the exact function name from memory either. I found it by searching the entire source base here on github for "ICorDebugInfo::NativeVarInfo" and then filtered from there. I was probably able to filter faster based on background knowledge, but its only a modest advantage ; )

**Comment by lucenticus** [comment]
@noahfalk, this is exactly what I need, thanks! Yes, I had to evaluate search results carefully:)
