### ISSUE TITLE
Optimize JIT helpers for memory copy operations on Intel architecture.

### ISSUE THREAD

**Issue by lt72** [dotnet/coreclr#7146]
The current implementation for JIT_MemSet / Jit_MemCpy is not up-to-date with the latest processors architecture. Such helpers are triggered through InitBlk and CpBlk MSIL opcodes, and Buffer::BlockCopy and Buffer::InternalBlockCopy would benefit from the same optimizations as well, although through a slightly different code path.

**Comment by swaroop-sridhar** [comment]
Fixed by 3bfe9a089128e11494a09b959000f99e0010adad

**Comment by swaroop-sridhar** [comment]
Opening until checked into 1.1 branch

**Comment by RussKeldorph** [comment]
Closing since this should naturally flow into release/1.2.0.
