### ISSUE TITLE
ARM64: Assertion failed '!"Non-store block node in Lowering"

### ISSUE THREAD

**Issue by kyulee1** [dotnet/coreclr#7160]
Assert failure(PID 1832 [0x00000728], Thread: 444 [0x01bc]): Assertion failed '!"Non-store block node in Lowering"' in 'DomainBoundILStubClass:IL_STUB_PInvoke(double,double,double,double,double,double,double,double,struct):struct' (IL size 110)

    File: e:\github\coreclr\src\jit\lowerarm64.cpp Line: 529

There are many tests failing due to this. One of them is:
JIT\Directed\StructABI\StructABI

More failing tests are:
Release:  http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_windows_nt/1/

Checked: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt/22/#showFailuresLink

**Comment by CarolEidt** [comment]
I have opened issues #7195, #7196, and #7197 for the 9 remaining failures.
