### ISSUE TITLE
List<T>.AddRange should not allocate a temporary array to add the range if items.  

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#7161]
List<T>'s AddRange method immediately defers to List<T>.InsertRange which has the following code

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/List.cs#L695

It has a special case if the passed IEnumerable is an ICollection, so that it can determine how many things will be added and do an EnsureCapacity so there will only be at most one resize operation.  This is great.  However it then allocates a temporary array and copies the range into that array and into the target list.   This is very inefficient (there is an unnecessary allocation as well as two rather than one copy per element).

Fix this so that instead of using CopyTo it simply enumerates the values and places the in the correct locations in the target array.    This is always more efficient, and a minor code change. 

@stephentoub  @jkotas 

If someone does not beat me to it, I will prepare a pull request for this.

**Comment by jkotas** [comment]
This was proposed in https://github.com/dotnet/coreclr/pull/6892 . 

cc @jamesqo

**Comment by vancem** [comment]
Jan, given that two independent people ran into this, and the effect can be large (if you are adding a large range), it seems worth fixing.  

My suggestion is simply to replace the copying into an array and that from that array with an enumeration of the range setting the target _items list as you go.   

Yes, under races the behavior may be different, but I don't think that is the bar (the previous code can produce questionable results under those conditions as well).

Copying only once (and avoiding the allocation) seems worth it.

Comments?

**Comment by jkotas** [comment]
Sounds good to me.

**Comment by jkotas** [comment]
@jamesqo Could you please reopen the PR with the change?

**Comment by jamesqo** [comment]
@jkotas Gladly. Just one thing though-- if I understand correctly, what's being proposed is to change the code to

```cs
int index = 0;
foreach (var item in c)
{
    _items[index++] = item;
}
```

Won't this be slower, actually, than what we currently have? Although we are no longer allocating an array or copying twice, we are now making 2 virtual method calls for every element in the collection (`MoveNext` and `Current`) whereas before, we were only making 1 total (`CopyTo`).

**Comment by jkotas** [comment]
I have not realized that your proposal and @vancem proposal are different.

@vancem Do you have opinion on whether to use CopyTo (faster, more risky) or enumerator (slower, less risky) here?

**Comment by vancem** [comment]
I see now that there is a tradeoff involved.   

My original suggestion was in fact to enumerate the IEnumerable representing the range which does mean doing a move-next and current per element.    This eliminates the need for a temporary buffer.  

@jamesqo's suggestion was to call the range's 'CopyTo directly on the underlying array for the List<T>.   This also eliminates the need for temporary, and is more efficient, but does mean that List<T>'s underlying array has 'leaked' out of the class (technically a malicious class could hold onto this reference and try to corrupt the values at a later point).  

Like @jamesqo I question the value of the temporary array.   In a world of hostile code it would make sense, but it is not clear we are in this world.   

Including @KrzysztofCwalina for his opinion.

For what it is worth, we have already made this leap of trusting other classes 'CopyTo' methods to not keep pointers the array passed to it.   If you look in the List(IEnumerable<T> collection) you will see the3 following code 

                    c.CopyTo(_items, 0);

Which is basically doing what @jamesqo was suggesting (and trusting the range's CopyTo method to not be malicious with the internal _items array.    However if I look on the Desktop, I find that the List(IEnumerable<T> collection) constructor does what I suggested (loop over the range adding it to the array).  

I think it is reasonable to fix both the constructor and AddRange to be consistent, however they do it.   If there is no concern about the 'leakage' then we should just trust the CopyTo function (that is easy).  

This boils down to an architectural decision about whether we want strong guarantees about things like ownership / read-onlyness or whether these properties are not strongly enforced but simply strong expressions of programmer intent.   

My personal bias is toward perf (since given private reflection and other 'escapes' I question the value of 'strong' enforcement).  

Comments?

**Comment by KrzysztofCwalina** [comment]
Alternatively, we would only do the optimization (CopyTo) if the inserted IEnumerable<T> is one of known collections (i.e. not malicious).
Otherwise, we for each.

**Comment by vancem** [comment]
@KrzysztofCwalina  what do you think is the right choice?   Certainly just trusting the CopyTo is easiest (it is not clear to me which collections to opt-in, and if the list is larger than 3 it is probably a poor perf tradeoff).    So unless there are objections, I think we should go with that.

Any objections?

**Comment by KrzysztofCwalina** [comment]
I have no strong opinion what's the right choice here. Trusting CopyTo will definitely be the easiest and the fastest, but probably not the most defensive from security and correctness perspective. Having said that, maybe we are not trying to be defensive about malicious code running in the same process/domain anymore.

**Comment by vancem** [comment]
OK, this is the last call.    The plan of record is to simply remove the array allocation and copy from the InsertRange function (so it is like the constructor).   It is pretty much a 3 line change, which is guaranteed to be faster in all cases.    If someone does not beat me to it, I will prepare such a pull request today or tomorow, but I am happy if someone beats me to it.

**Comment by KrzysztofCwalina** [comment]
sounds good to me

**Comment by jamesqo** [comment]
I have reopened my pull request at #6892.

**Comment by jamesqo** [comment]
@vancem This can be closed since the PR was merged.
