### ISSUE TITLE
x86: ShowLocallocAlignment test failure

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#7163]
test:
JIT\Regression\Dev11\External\dev11_239804\ShowLocallocAlignment\ShowLocallocAlignment.cmd

results:
Address1: Misaligned (0000000002abde04)
Address2: Misaligned (0000000002abde04)

Test failed.
Expected: 100
Actual: 101

**Comment by RussKeldorph** [comment]
Maybe delete the `Legacy Backend` label when this is closed.

**Comment by BruceForstall** [comment]
This test still fails with x86.

Is it required that localloc return 8-byte aligned memory?
