### ISSUE TITLE
ARM64: Bad code gen on 1 % 1

### ISSUE THREAD

**Issue by kyulee1** [dotnet/coreclr#7168]
```
using System;
class T
{
 public static void Main()
 {
   long a= (long)1;
   long b= (long)1;

   long c = a%b;
   Console.WriteLine(c.ToString());
  }
}
```

With optimization, this prints -1 instead of 0.
This is a root-cause for https://github.com/dotnet/corefx/issues/9631.

**Comment by jashook** [comment]
No longer repros. #11832 adds 1 % 1 to the mod bringup test.
