### ISSUE TITLE
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.ni.dll

### ISSUE THREAD

**Issue by HamedFathi** [dotnet/coreclr#7186]
based on this [issue](https://github.com/dotnet/coreclr/issues/7154)
I tried another way for loading assembly so I wrote a snippet code for loading assembly 

```
    public class Program
    {
        public static void Main(string[] args)
        {
            var name = AssemblyLoadContext.GetAssemblyName(@"C:\MainParser.Contract.dll");
            var loaded = Assembly.Load(name);
        }
    }
```

error message 
```
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.ni.dll

Additional information: Could not load file or assembly 'MainParser.Contract, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

![untitled](https://cloud.githubusercontent.com/assets/8418700/18518447/4a9fb002-7ab5-11e6-9211-6966287d3561.png)

Microsoft .NET Core Shared Framework Host

  Version  : 1.0.1
  Build    : cee57bf6c981237d80aa1631cfe83cb9ba329f12

dotnet --version
1.0.0-preview2-003131

seems name variable get info from .dll file correctly but Why in loading said FileNotFound ?

**Comment by gkhanna79** [comment]
To load the assembly, it must be available in the application's transitive closure. Getting an AssemblyName from a physical path has no bearing for assembly load resolutions.

**Comment by HamedFathi** [comment]
@gkhanna79  thanks for your response
