### ISSUE TITLE
Add missing "Computer Language Benchmarks Game" benchmarks

### ISSUE THREAD

**Issue by cmckinsey** [dotnet/coreclr#7190]
We are missing these benchmarks knucleotide, regexdna, revcomp in the JIT benchmark suite. Please add.

http://benchmarksgame.alioth.debian.org/

**Comment by benaadams** [comment]
Also contribute updates back? http://benchmarksgame.alioth.debian.org/play.html

Not sure their implementations are the best

**Comment by RussKeldorph** [comment]
Updated link: https://benchmarksgame-team.pages.debian.net/benchmarksgame/

Also consider adding the FSharp benchmarks assuming we can add the infra to build them.

**Comment by BruceForstall** [comment]
Looks like we have these now
