### ISSUE TITLE
ARM64: Assertion failed 'gtOper == GT_CNS_INT' in '_cpblk:main(ref):int'

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#7195]
This occurs in the latest sources, but was not occurring prior to #7027. It was not fixed by PR #7188 which fixed some other failures due to that PR. This affects the following two tests:
JIT\Directed\PREFIX\volatile\1\cpblk\cpblk.cmd
JIT\opt\Inline\tests\UnsafeBlockCopy\UnsafeBlockCopy.cmd

**Comment by rahku** [comment]
CC @gkhanna79
