### ISSUE TITLE
ARM64: Assert failure: (value != 0) && ((value & (value-1)) == 0)

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#7196]
This occurs in the latest sources, but was not occurring prior to #7027. It was not fixed by PR #7188 which fixed some other failures due to that PR. This affects the following four tests:
JIT\Directed\perffix\primitivevt\mixed1_cs_do\mixed1_cs_do.cmd
JIT\Directed\perffix\primitivevt\mixed1_cs_ro\mixed1_cs_ro.cmd 
JIT\Methodical\fp\exgen\10w5d_cs_do\10w5d_cs_do.cmd
JIT\Methodical\fp\exgen\10w5d_cs_ro\10w5d_cs_ro.cmd
At first look, it seems to be asserting when getting a register.

**Comment by rahku** [comment]
CC @gkhanna79
