### ISSUE TITLE
ARM64: New test failures

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#7197]
These tests fail with the latest sources, but were not failing prior to #7027. It was not fixed by PR #7188 which fixed some other failures due to that PR. This affects the following three tests (though I don't know for certain that they are caused by the same issue):
JIT\Generics\Fields\static_passing_class01\static_passing_class01.cmd
JIT\Generics\Fields\static_passing_struct01\static_passing_struct01.cmd
JIT\SIMD\Ldind_ro\Ldind_ro.cmd

**Comment by rahku** [comment]
CC @gkhanna79

**Comment by CarolEidt** [comment]
This is an error in the order in which the operands to the block op are consumed in the code generator.
