### ISSUE TITLE
Reuse StringBuilder in StreamReader.ReadLine()

### ISSUE THREAD

**Issue by Knagis** [dotnet/coreclr#72]
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/StreamReader.cs#L715

A new `StringBuilder` is created for each line. Instead a single instance could be cached in the `StreamReader` itself, reducing the number of object allocations and increasing performance.

**Comment by AlexGhiondea** [comment]
Thanks for reporting this. 

Adding a cache for this might indeed speed up the code. Do you have any benchmarks to show how big this improvement would be?

**Comment by brianrob** [comment]
If you want to write a quick benchmark for this, take a look at http://blogs.msdn.com/b/vancem/archive/2009/02/06/measureit-update-tool-for-doing-microbenchmarks.aspx.  MeasureIt makes writing benchmarks very simple and solves a large number of the issues that crop up around them.

As an FYI, we'll have some official guidance on using MeasureIt soon.

**Comment by Knagis** [comment]
Very quick test - reading 10MB (~147k lines) text file - the reuse of `StringBuilder` gains ~30-40ms on my machine.

The source - CommonMark.NET parser. This optimization (custom `ReadLine()` by using only `Read()` calls) gets me from ~280ms to ~240ms for the whole process (read/parse/write) - a very significant improvement.

**Comment by Knagis** [comment]
Results from MeasureIt (since I realised my code uses the builder much more often for multiple purposes). I ran the tool on .NET 4.5.2. The StreamReader code was taken from this repository.

        timer10.Measure("StreamReader.Bad", 1, delegate
        {
            using (var reader = new System.IO.Bad.StreamReader(path))
                while (reader.ReadLine() != null) { }
        });

        timer10.Measure("StreamReader.Good", 1, delegate
        {
            using (var reader = new System.IO.Good.StreamReader(path))
                while (reader.ReadLine() != null) { }
        });

				      Median      Mean        Mean%   Min        Min%
    Without reuse     43527980    45161760    100%    41866530   100%
    Reusing builder:  39564030    38943990    86%     29291970   70%

[Source file used](https://github.com/Knagis/CommonMarkBenchmark/blob/master/MarkdownCompare/Tests/progit.md)

**Comment by brianrob** [comment]
@Knagis, it looks like the source file link didn't take me to the right place.  Can you check on this?

Considering the simplicity of the change, feel free to code it up, and submit a pull request and we can review it from there.  Thanks.

**Comment by panost** [comment]
I don't think that timer benchs should be used in such cases (ie different object allocations algorithms). The state of the memory after the two cases are finished are vastly different.

Including in the timer results, a full GC collection might bring more accurate results, but still how can you compare a case that needed 300MB of heap memory to complete vs a case that needed only 1MB.

Anyway in this particular case I think the possibility of using the StringBuilderCache methods (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/StringBuilderCache.cs) should also be invistigated, given that the most common line lengths are below it's limit (360 chars)

**Comment by Knagis** [comment]
@brianrob - I meant to show the text file I was using for the benchmark, not the modified source code (since I only changed the one method).

@panost - looking at how `StringBuilderCache` is used it seems that the cached instance is never held longer than the time of a single framework method call. 

The `StreamReader` case is different since the instance would he held for much longer (the lifetime of the reader) - since I think that a reasonable assumption is that if there was one very long line then the others might be as long and in such case StringBuilderCache would not help at all. 

Of course, the smaller/simpler change could be to just rely on `StringBuilderCache` instead of creating a new one every time it is needed. Either way the change would increase performance.

**Comment by jkotas** [comment]
You should be able to checkout the StringBuilder from the StringBuilderCache for just the duration of the ReadLine method.

**Comment by brianrob** [comment]
Thanks for clarifying @Knagis .

@jkotas, I'm a bit concerned about the potential memory cost of using StringBuilderCache because it creates a per-thread cache which is never freed.  This can grow especially in server cases where the number of threads in the ThreadPool is large and the ThreadPool doesn't need to shrink.  My preference would be to use a single instance which is lazily constructed in the StreamReader when needed.  Then when the StreamReader is collected so is the StringBuilder.  What do you think?

**Comment by Knagis** [comment]
I vote for a `StringBuilder` created within `StreamReader`. The cost of a single additional allocation will be completely insignificant (taking into account that the underlying operation is reading stream of some sort which is rather expensive - as opposed to formatting a `TimeSpan`). But it will also give consistent performance improvement always (not only when the line lengths are below 360).

**Comment by mikedn** [comment]
I don't think caching a `StringBuilder` in `StreamReader` is a good idea. The builder will end up having the same lifetime as the reader and that may very well be a long lifetime. Remember that a reader can read data from sources other than files. For example you can read data from a `NetworkStream` and data may arrive occasionally throughout a long period of time.

Framework classes should strive to minimize allocations but I don't think that they should do so at the cost of holding onto potentially large objects for extensive time.

**Comment by jkotas** [comment]
@brianrob I do not have a strong opinion on whether to use a stringbuildercache here. I was just pointing out that it should be reasonable to use stringbuildercache here if we wanted to.

I share your concern about caching a string builder per thread. I do not think it is too big a deal in mscorlib because of mscorlib is large library, and StringBuilderCache is used by many codepaths - the cost of the cached copy is likely to be amortized. However, it is worrying me for the small libraries in corefx. The pattern used in corefx is to create one private per library stringBuilderCache that leads to one cached StringBuilder per library per thread. IIRC, there was a discussion about it, but I do not remember the outcome.

**Comment by panost** [comment]
The StringBuilderCache most probably will be allocated, whether you use it or not, since It's already be used by many mscorlib methods.

**Comment by brianrob** [comment]
@Knagis, I agree with you that a StringBuilder cached per StreamReader, and lazily initialized in the ReadLine method is a good way to go.

@mikedn, I suspect that the cost of caching one StringBuilder won't clear the noise floor, especially if the StringBuilder is cleared before ReadLine returns.  This ensures that the accumulated strings are dumped and subsequently collected.  If you look at the other cached items in this class, I doubt that caching a StringBuilder is going to have a material effect.

**Comment by Knagis** [comment]
I created the pull request with this change. The interesting find was that use of `StringBuilderCache` turned out to be even slower than no caching at all.

**Comment by kangaroo** [comment]
@jkotas ping on the PR and the issue -- what do we need to move forward on this?

**Comment by jkotas** [comment]
The PR is assigned to @ericstj to handle it. @ericstj do you have a plan to move forward on this?

**Comment by ericstj** [comment]
I had an open question on the PR.  I just clarified the question.

**Comment by brianrob** [comment]
Closing this issue, as there is now a PR for this at #129.

**Comment by terrajobst** [comment]
@ericstj is the implementation actually in `mscorlib`, i.e. in the runtime package or does it live in CoreFX? It it lives in CoreFX we should move the issue/PR there.

**Comment by ericstj** [comment]
Yeah, it's in mscorlib.  System.IO is still entirely in mscorlib for coreclr.  We might move stuff like this up to the a partial façade once we can support it, but at the moment it is still in mscorlib.

**Comment by brianrob** [comment]
Closing as #129 has been merged.
