### ISSUE TITLE
Fix all or most of the remaining warnings in CoreCLR on Linux

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#720]
There are some remaining disabled warning categories in the CoreCLR. 
Ideally, it would be great to get warning free, but for some of the warnings it can be difficult.
Here is an overview of all the remaining disabled warnings with some description added, followed by a simple difficulty classification:
### -Wno-unused-private-field

There are private fields in classes that are not being used. There are two kinds of these. One are members that are really obsolete and not used anymore. The other is caused by `#ifdefs` that for some combinations of defines cause the member to not to be used.
### -Wno-dangling-else

There are conditions like 

``` c
if () {...} else command;
```

These are mostly generated by the following macro:

``` c
#define return if (0 && __ReturnOK::safe_to_return()) { } else return
```
### -Wno-implicit-exception-spec-mismatch

Function previously declared with an explicit exception specification redeclared with an implicit exception specification - all on operator delete 
### -Wno-overloaded-virtual

A derived class defines a virtual method with the same name as its base class, but different set of parameters.
### -Wno-unused-variable

There are locals that are not used.
### -Wno-switch

Enum value is not handled in a switch (and there is no default clause). Remaining cases are in JIT only
### -Wno-microsoft

Explicit constructor calls are not supported by clang (`this->ClassName::ClassName()`)
### -Wno-tautological-compare

This warning is caused by comparing `'this'` to `NULL`
### -Wno-constant-logical-operand

There are constants of type `BOOL` used in a condition. But `BOOL` is defined as int and so the compiler thinks that there is a mistake.
### -Wno-unknown-warning-option

Some of the warning disabling options exist only on clang 3.6 so clang 3.5 complained it doesn't know them.
### -Wno-invalid-offsetof

 __builtin_offsetof(type, field) is applied to a non-standard-layout type
### -Wno-delete-non-virtual-dtor

Class with pure virtual methods has non-virtual destructor
### -Wno-incompatible-ms-struct

The warning indicates that an attribute `__attribute__((__ms_struct__))` was applied to a struct or a class that has virtual members or a base class. In that case, clang  may not generate the same object layout as MSVC.

The following ones should be reasonably fixable:
`-Wno-implicit-exception-spec-mismatch`
`-Wno-switch`
`-Wno-microsoft`
`-Wno-constant-logical-operand`
`-Wno-delete-non-virtual-dtor`
`-Wno-unused-variable`

The following ones are more difficult to fix:
`-Wno-overloaded-virtual` - it seems it would require renaming the methods or figuring out if there is an attribute to mark those methods
`-Wno-unused-private-field` - might require nontrivial amount of `#ifdefs` being added to the class declarations
`-Wno-incompatible-ms-struct` - we use this attribute for structs / classes that are to be marshalled between different platforms, maybe there would be a way to refactor the problematic classes to fix that
`-Wno-invalid-offsetof` - similar to the previous one, we might be able to refactor the problematic classes
`-Wno-tautological-compare` - it needs to be figured out if we can get rid of comparing this to NULL somehow.
`-Wno-dangling-else` - The `return` macro would need to be redesigned to not to use if / else to fix this problem

**Comment by janvorli** [comment]
`-Wno-dangling-else` fixed by #723

**Comment by richlander** [comment]
@janvorli Curious, is this up-for-grabs or should someone (like you) self-assign?

**Comment by janvorli** [comment]
Remaining disabled warnings:
**-Wno-microsoft**
**-Wno-constant-logical-operand**
**-Wno-unused-variable**
**-Wno-unused-private-field** (see #1051 for an attempt to fix that showed that fixing it introduces quite a lot of clutter and we might want to keep this disabled)
**-Wno-incompatible-ms-struct** - we use the `__attribute__((__ms_struct__))` on some classes that have base classes.
**-Wno-invalid-offsetof**
**-Wno-tautological-compare**
