### ISSUE TITLE
Lost all ProjectTemplates and ItemTemplates

### ISSUE THREAD

**Issue by KeyurRamoliya** [dotnet/coreclr#7203]
First of all, Guide me for the correct repo if issue is not related to this repo.

After installing .Net Core 1.0.1(latest version), I lost my ProjectTemplates as well as ItemTemplates from the Visual Studio New Project and New Item wizard respectively.

For the solution, I had already tried all the process available on internet but still ProjectTemplates and ItemTemplates are not visible. I even reset my Visual Studio settings.

Please give the solution if any one have.

**Comment by gkhanna79** [comment]
@barrytang Which repo should this issue be moved to?

**Comment by barrytang** [comment]
Hi, is this for VS 2015 or VS 2017?

**Comment by gkhanna79** [comment]
@KeyurRamoliya I am closing this issue for now. Once you have specific details for repro that @barrytang can use, please feel free to reopen the issue.

**Comment by KeyurRamoliya** [comment]
@barrytang @gkhanna79 This issue is in Visual Studio 2015. I think this issue for CoreCLR repo but if not please tell me repo that is related to this issue.

**Comment by gkhanna79** [comment]
@barrytang Can you please move this issue to the appropriate repo?

**Comment by barrytang** [comment]
https://developercommunity.visualstudio.com/spaces/8/index.html is the right place to open a VS issue.

@mlorbetske, can you see if you can help @KeyurRamoliya here?

**Comment by mlorbetske** [comment]
Hi @KeyurRamoliya, could you try opening the `Developer Command Prompt for VS 2015` and running `devenv /setup` please? This should put the templates back in working order. Please do file an issue on Developer Community and post a link to the issue here so that we can continue the conversation over there.
