### ISSUE TITLE
RyuJIT x86: lower long compares that are materialized into a register

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#7210]
This is an optimization to decrease register pressure. See #7189 for more details.

**Comment by mikedn** [comment]
I can work on this. The only "difficulty" here is to decide if we keep the current `setcc` based codegen (that will likely require adding `GT_SETCC`) or if we drop back to the JIT32 codegen that basically transformed these compares into `cmp(x, y) ? 1 : 0` and thus simply builds upon the existing compare lowering.

```
JIT32 code -------------------------------------------------------------------------
G_M55886_IG01:
       55           push     ebp
       8BEC         mov      ebp, esp
G_M55886_IG02:
       8B4510       mov      eax, dword ptr [ebp+10H]
       8B5514       mov      edx, dword ptr [ebp+14H]
       3B550C       cmp      edx, dword ptr [ebp+0CH]
       7F07         jg       SHORT G_M55886_IG03
       7C09         jl       SHORT G_M55886_IG04
       3B4508       cmp      eax, dword ptr [ebp+08H]
       7204         jb       SHORT G_M55886_IG04
G_M55886_IG03:
       33C0         xor      eax, eax
       EB05         jmp      SHORT G_M55886_IG05
G_M55886_IG04:
       B801000000   mov      eax, 1
G_M55886_IG05:
       5D           pop      ebp
       C21000       ret      16
; Total bytes of code 34, prolog size 3 for method Program:Test(long,long):bool

RyuJITx86 code --------------------------------------------------------------------
G_M55886_IG01:
       55           push     ebp
       8BEC         mov      ebp, esp
       56           push     esi
G_M55886_IG02:
       8B4510       mov      eax, dword ptr [ebp+10H]
       8B5514       mov      edx, dword ptr [ebp+14H]
       8B4D08       mov      ecx, dword ptr [ebp+08H]
       8B750C       mov      esi, dword ptr [ebp+0CH]
       3BD6         cmp      edx, esi
       750A         jne      SHORT G_M55886_IG03
       3BC1         cmp      eax, ecx
       0F92C0       setb     al
       0FB6C0       movzx    eax, al
       EB06         jmp      SHORT G_M55886_IG04
G_M55886_IG03:
       0F9CC0       setl     al
       0FB6C0       movzx    eax, al
G_M55886_IG04:
       5E           pop      esi
       5D           pop      ebp
       C21000       ret      16
; Total bytes of code 41, prolog size 4 for method Program:Test(long,long):bool
```

At the first look the `setcc` based implementation might be a waste of time as it generates larger code. I'll try to see if it's faster, otherwise it's really useless.

**Comment by pgavlin** [comment]
Sounds good to me.

**Comment by mikedn** [comment]
I did some [tests](https://gist.github.com/mikedn/c27d340841e80fca057730ab5d997447) and what's clear is that the JIT32 implementation is slow for random input. Also
* With one exception `setcc` versions do better even for constant inputs (though I need to review the results as some of them don't seem quite right).
* The `movcc` version does really well

It's tempting to use the `movcc` version, not only it is fast but it also doesn't increases the number of basic blocks. However, adding both `GT_SETCC` and `GT_MOVCC` seems a bit much. Also, this version needs one temporary register.

**Comment by mikedn** [comment]
Unsigned and equality compares are much simpler and as such offer fewer implementation choices. The code that RyuJIT currently generates for `ulx < uly` is
```
       3BD6         cmp      edx, esi
       7502         jne      SHORT G_M55886_IG03

       3BC1         cmp      eax, ecx

G_M55886_IG03:
       0F92C0       setb     al
       0FB6C0       movzx    eax, al
```
Generating this in lower pretty much requires us to introduce both `GT_CMP` and `GT_SETCC`. I was hoping that we could get away with `GT_SETCC` only but it looks like this might not be possible (unless we fallback to the JIT32 variant).

**Comment by mikedn** [comment]
Hrm, all implementations except the `movcc` one use control flow and require splitting the current block at an arbitrary point. `fgSplitBlockAfterNode` doesn't handle this properly, it ignores use-def edges that cross the new basic block boundary and need to be transformed into lclvars. There's also an issue with decomposition running multiple times on nodes that are after the split point.

Maybe we should just use `movcc` and call it a day. The drawback of that version is that it generates larger code (larger that what RyuJIT does currently but still smaller than what JIT32 did) and requires a temp register.

Thoughts anyone?

**Comment by pgavlin** [comment]
> Maybe we should just use movcc and call it a day. The drawback of that version is that it generates larger code (larger that what RyuJIT does currently but still smaller than what JIT32 did) and requires a temp register.

This seems like a fine solution to me.

**Comment by mikedn** [comment]
Meh, all discussed implementations are lame, we can do better:
1. EQ/NE is obvious - `(x == y) == (x - y == 0)`. Testing if a `long` is 0 is trivial, just OR the low and high parts.
2. LT is obvious as well - `(x < y) == (x - y < 0)`. Testing if a `long` is negative is negative is also trivial - check the sign of the high part.
3. LE is a little obvious but works too - `(x <= y) = !(x > y) = !(y < x)` and we're back at testing the sign of high part.

**Comment by AndyAyersMS** [comment]
For EQ/NE, `x-y` still has a borrow. If we can't introduce control flow, how about `(x.lo - y.lo) | (x.hi - y.hi)`? And if `y == 0`, `x.lo | x.hi`.

**Comment by mikedn** [comment]
> how about (x.lo - y.lo) | (x.hi - y.hi)?

Yup, already done:
```asm
       8B4510       mov      eax, dword ptr [ebp+10H]
       8B5514       mov      edx, dword ptr [ebp+14H]
       8B4D08       mov      ecx, dword ptr [ebp+08H]
       8B750C       mov      esi, dword ptr [ebp+0CH]
       2BC1         sub      eax, ecx
       2BD6         sub      edx, esi
       0BC2         or       eax, edx
       0F94C0       sete     al
       0FB6C0       movzx    eax, al
```
> And if y == 0, x.lo | x.hi.

Right, yet to do that.

It also turns out that the negative test doesn't work very well:
```asm
       2BC1         sub      eax, ecx
       1BD6         sbb      edx, esi
       85D2         test     edx, edx  ; need to fix #7566 as well to get rid of this
       0F9CC0       setl     al
       0FB6C0       movzx    eax, al
```

**Comment by mikedn** [comment]
Hmm, for LT/LE/GT/GE the first `sub` can be a `cmp` since we only need `CF` from it. But for that we need to add `GT_CMP`...

**Comment by mikedn** [comment]
@AndyAyersMS Since you mentioned it here's an example diff for the y == 0 case:
```diff
       mov      edx, dword ptr [eax]
+      or       edx, dword ptr [eax+4]
-      mov      eax, dword ptr [eax+4] 
-      xor      ecx, ecx
-      xor      esi, esi
-      cmp      eax, esi
-      jne      SHORT G_M32688_IG03
-      cmp      edx, ecx
-G_M32688_IG03:
       setne    al
       movzx    eax, al
```
11 bytes of code less in the method :)

**Comment by AndyAyersMS** [comment]
Looks awesome.
