### ISSUE TITLE
Add Cast() and AsBytes() to Span and ReadOnlySpan

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/coreclr#7211]
This issue is [continuation of discussion that has started](https://github.com/dotnet/coreclr/issues/5857#issuecomment-246719466) in #5857

The initial implementation of Slices contains `Cast` method which allows to cast slice of one value type to slice of another value type. Most probably we all agree that this is a great feature. The question is how to limit it to keep not only usability but also type and memory safety?

So far the proposed API is following:
* `Span<byte> AsBytes<TFrom>()`
* `unsafe Span<TTo>  NonPortableCast<TFrom, TTo>()` (first idea was to call it Cast)

Requirements:
* `TFrom` and `TTo` must be a value types (compilation check)
* `TFrom` and `TTo` must not contain pointers (runtime check)

what are your thoughts on it?

Jan may I ask why do you think that `Cast` should be marked as `unsafe`?

@KrzysztofCwalina @jkotas @omariom

**Comment by jkotas** [comment]
> Jan may I ask why do you think that Cast should be marked as unsafe?

My concern is that it is not no-portable to platforms that do not support misaligned memory access. For example, it won't work well to cast Span<byte> to Span<float> on ARM.

I think it is a good idea to have the API there for power users, but it should be in the non-portable/unsafe set – you have to know what you are doing and that it will work. The "unsafe" marker like you have suggested does not do anything - it just applies to implementation, it is not visible to whoever it using the API. It should be captured in the name to make it clear, something like: `Span<TTo> NonPortableCast<TFrom, TTo>()`

**Comment by KrzysztofCwalina** [comment]
We could also add safe TryCast that succeeds for aligned casts.

**Comment by janvorli** [comment]
@KrzysztofCwalina it seems that whether the underlying memory is aligned or not is kind of "random", depending on from what the original span was created. So I am not sure how the TryCast would be used and how would a developer handle the case when this fails in a meaningful way.

**Comment by jkotas** [comment]
Fixed by #7220
