### ISSUE TITLE
RyuJIT x86: [JitStressRegs=1 or 2 or 8] JIT\Methodical\explicit\coverage\expl_byte_1_r\expl_byte_1_r.exe test failure

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#7224]
```
12:11:10   Raw output file:      D:\j\workspace\x86_ryujit_ch---5e4f5952\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Methodical\explicit\coverage\expl_byte_1_r\expl_byte_1_r.output.txt
12:11:10   Raw output:
12:11:10   BEGIN EXECUTION
12:11:10          "D:\j\workspace\x86_ryujit_ch---5e4f5952\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" expl_byte_1_r.exe 
12:11:10         test_3_4() failed.
12:11:10         Expected: 100
12:11:10         Actual: 159
12:11:10         END EXECUTION - FAILED
12:11:10         FAILED
12:11:10         Test Harness Exitcode is : 1

```

**Comment by adiaaida** [comment]
This still repros with the following output:

JIT\Methodical\explicit\coverage\expl_byte_1_r\expl_byte_1_r.cmd
BEGIN EXECUTION
 "C:\michelm\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" expl_byte_1_r.exe
test_2_4() failed.
Expected: 100
Actual: 141
END EXECUTION - FAILED
FAILED

**Comment by adiaaida** [comment]
For JitStressRegs=1, we generate this for test_2_4:

```
06EF3C39  push        esi  
06EF3C3A  push        ebx  
06EF3C3B  mov         esi,dword ptr ds:[8471C0Ch]  
06EF3C41  movzx       eax,cl  
06EF3C44  mov         edi,eax  
06EF3C46  cmp         edi,dword ptr [esi+4]  
06EF3C49  jae         06EF3C5F  
06EF3C4B  imul        ebx,**edi**,30h  
06EF3C4E  lea         esi,[esi+ebx+8]  
06EF3C52  lea         ebx,[esi+8]  
**06EF3C55  add         byte ptr [ebx],bh**  
06EF3C57  movzx       eax,byte ptr [esi+8]
```

Note the bolded disasm. BH is not the register we want to be using in this add. We are looking for the equivalent of BL for EDI, which is where 100 is stored (and what the expected output is). In non-jitstressregs scenarios, we generate:

```
0A873B40  mov         eax,dword ptr ds:[08401C0Ch]  
0A873B45  movzx       edx,cl  
0A873B48  cmp         edx,dword ptr [eax+4]  
0A873B4B  jae         0A873B5E  
0A873B4D  imul        ecx,**edx**,30h  
0A873B50  lea         eax,[eax+ecx+8]  
0A873B54  lea         ecx,[eax+8]  
**0A873B57  add         byte ptr [ecx],dl**  
0A873B59  movzx       eax,byte ptr [eax+8]  
```

Note that we are using the lo byte of edx, which has 100 in it.

**Comment by sivarv** [comment]
This looks like we have the following IR and not setting src candidates on the operands of GT_ADD to be confined to bytable regs in lowerxarch.cpp:TreeNodeInfoInit()

GT_ADD(TYP_INT, mem of TYP_BYTE,  reg of TYP_INT or TYP_BYTE)

The condition under which we set src candidates to be equal to bytable registers is may not be handling the above kind of node.
