### ISSUE TITLE
.NET Core caches windows runtime delegates too aggressively

### ISSUE THREAD

**Issue by TautvydasZilys** [dotnet/coreclr#7231]
It seems that .NET Core manages to call wrong native function when a single native object implements several Windows Runtime delegate interfaces. Basically, the repro comes down to this:

IDL:

``` IDL
[uuid(AADBCEBF-C4C0-477A-AC48-1710ECAB2224)]
[version(1.0)]
delegate HRESULT DelegateTakingAndReturningInt([in] INT32 value, [out, retval] INT32* result);

[uuid(9DFC8ED3-1168-4F55-BC47-056EFAEC4BA2)]
[version(1.0)]
delegate HRESULT DelegateTakingAndReturningFloat([in] FLOAT value, [out, retval] FLOAT* result);

[uuid(D3CC7651-FA13-46EE-B227-4F8010D37B52), version(1.0)]
interface IDelegateProviderStatics : IInspectable
{
    HRESULT GetDelegateThatMultipliesIntByTwo([out, retval] DelegateTakingAndReturningInt** value);
    HRESULT GetDelegateThatDividesFloatByTwo([out, retval] DelegateTakingAndReturningFloat** value);
}

[version(1.0), static(IDelegateProviderStatics, 1.0)]
runtimeclass DelegateProvider
{
}
```

C++:

``` C++
class MultiDelegate :
    public RuntimeClass<RuntimeClassFlags<ClassicCom>, IDelegateTakingAndReturningInt, IDelegateTakingAndReturningFloat>
{
    virtual HRESULT STDMETHODCALLTYPE Invoke(INT32 value, INT32* result) override { *result = 2 * value; return S_OK; }
    virtual HRESULT STDMETHODCALLTYPE Invoke(FLOAT value, FLOAT* result) override { *result = value / 2.0f; return S_OK; }
};

class DelegateProvider :
    public ActivationFactory<IDelegateProviderStatics>
{
    InspectableClassStatic(RuntimeClass_DelegateProvider, BaseTrust);

public:
    DelegateProvider() : m_Delegate(Make<MultiDelegate>()) { }

    virtual HRESULT STDMETHODCALLTYPE GetDelegateThatMultipliesIntByTwo(IDelegateTakingAndReturningInt** value) override
    {
        return m_Delegate.CopyTo(value);
    }

    virtual HRESULT STDMETHODCALLTYPE GetDelegateThatDividesFloatByTwo(IDelegateTakingAndReturningFloat** value) override
    {
        return m_Delegate.CopyTo(value);
    }

private:
    ComPtr<MultiDelegate> m_Delegate;
};

ActivatableStaticOnlyFactory(DelegateProvider)
```

C#:

``` C#
var d1 = DelegateProvider.GetDelegateThatMultipliesIntByTwo();
var d2 = DelegateProvider.GetDelegateThatDividesFloatByTwo();
Console.WriteLine(ReferenceEquals(d1, d2)); // Prints true
Console.WriteLine(d1(12)); // Prints 24, as expected
Console.WriteLine(d2(325.34f)); // Prints garbage, calls the method that takes int
```

I could reproduce this on both desktop .NET and .NET Core, but it does not reproduce on .NET Native. It seems that .NET Core caches the delegates based on their IUnknown, and doesn't realize that their types don't match when retrieving the managed object from the cache (I haven't verified this, but I imagine that's what happens). .NET native, on the other hand, always seems to create a new managed delegate instance every time one is returned from native code, regardless of whether it has seen it before or not. I've attached a repro project which you can simply run from VS and see wrong function invoked in action:

[DotNetCoreWrongFunctionCalled.zip](https://github.com/dotnet/coreclr/files/477490/DotNetCoreWrongFunctionCalled.zip)

**Comment by mellinoe** [comment]
@yizhang82

**Comment by yizhang82** [comment]
@TautvydasZilys Thanks for reporting this issue! As discussed offline (last year), this is an interesting case where a WinRT object implements multiple WinRT delegate interfaces. Typically there is 1:1 relationship between .NET objects and WinRT objects, but this is a case where the same WinRT object has multiple .NET object identity. In practice this would only happen if you managed to get WRL C++ implemented delegates from WinRT code and this almost never happens. I'm closing this issue for now and we'll fix this if this become a real issue.
