### ISSUE TITLE
RyuJIT x86: [JitStress=2][JitStressRegs=4 or 8] JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.exe test failure with OOM exception

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#7235]
```
11:53:19   Unhandled Exception: OutOfMemoryException.
11:53:19   
11:53:19   
11:53:19   Return code:      1
11:53:19   Raw output file:      D:\j\workspace\x86_ryujit_ch---2044ccf6\bin\tests\Windows_NT.x86.Checked\Reports\JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.output.txt
11:53:19   Raw output:
11:53:19   BEGIN EXECUTION
11:53:19          "D:\j\workspace\x86_ryujit_ch---2044ccf6\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" hugeexpr1.exe 
11:53:19         Expected: 100
11:53:19         Actual: -532462766
11:53:19         END EXECUTION - FAILED
11:53:19         FAILED
11:53:19         Test Harness Exitcode is : 1
```

**Comment by pgavlin** [comment]
@sivarv: on which machine were you able to repro this? I can't repro this at all anymore, and the max. memory usage I see for the relevant process is ~1.8 GB.

**Comment by sivarv** [comment]
These were the failures when I triggered stress runs on OSS CI after fixing LSRA stress on x86.  These were filed at least 2 weeks back and quite a few x86 RyuJIT changes/fixes were checked-in since then.  It is quite possible they are no longer repro now. Feel free to close them if no longer repro'ing against latest.

**Comment by pgavlin** [comment]
Cool--just wanted to make sure.

**Comment by sivarv** [comment]
Please make sure these issues are not repro'ing on OSS CI stress runs.
Btw, to repro these issues, one has to run checked tests against checked coreclr.
