### ISSUE TITLE
RyuJIT x86: [JitStress=2][JitStressRegs=8] JIT\Methodical\unsafecsharp\_speed_dbgunsafe-4\_speed_dbgunsafe-4.exe test fails with IndexOutOfRange exception

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#7236]
```
11:53:18 D:\j\workspace\x86_ryujit_ch---2044ccf6\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(283074): error : JIT._Methodical_unsafecsharp__speed_dbgunsafe_4__speed_dbgunsafe_4_._Methodical_unsafecsharp__speed_dbgunsafe_4__speed_dbgunsafe_4_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---2044ccf6\tests\runtest.proj]
11:53:18         
11:53:18   Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
11:53:18            at TestApp.test_25(B* pb, Int64[,,] i, Int64 ii, Byte jj) in D:\j\workspace\x86_ryujit_ch---2044ccf6\tests\src\JIT\Methodical\unsafecsharp\unsafe-4.cs:line 28
11:53:18            at TestApp.Main() in D:\j\workspace\x86_ryujit_ch---2044ccf6\tests\src\JIT\Methodical\unsafecsharp\unsafe-4.cs:line 306
11:53:18   
11:53:18   
11:53:18   Return code:      1
11:53:18   Raw output file:      D:\j\workspace\x86_ryujit_ch---2044ccf6\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Methodical\unsafecsharp\_speed_dbgunsafe-4\_speed_dbgunsafe-4.output.txt
11:53:18   Raw output:
11:53:18   BEGIN EXECUTION
11:53:18          "D:\j\workspace\x86_ryujit_ch---2044ccf6\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" _speed_dbgunsafe-4.exe 
11:53:18         Expected: 100
11:53:18         Actual: -532462766
11:53:18         END EXECUTION - FAILED
11:53:18         FAILED
11:53:18         Test Harness Exitcode is : 1
```

**Comment by pgavlin** [comment]
This one is interesting. This turns out to occur because the code generator attempts to spill a non-byte-addressable register using a byte-sized store:

```
;  V03 arg3         [V03,T05] (  2,   2  )   ubyte  ->  [esp+0x20]  
...
Generating: N021 (  1,  1) [000062] ------------             *  lclVar    ref    V01 arg1         u:2 edx REG edx RV $c0
Generating:                [000132] ------------             *  copy      ref    REG ebx
Generating: N023 (  3,  2) [000054] -----------Z             *  lclVar    int    V03 arg3         u:2 esi REG esi RV $140
Generating:                [000130] ------------             *  copy      int    REG eax
Generating: N025 (  4,  4) [000053] -----------Z             *  cast      int <- ubyte <- int REG ebx $240

      G_M14742_IG06:        ; offs=00000EH, funclet=00
IN0006:        mov      byte  ptr [V03 esp+20H], sl
							V03 in reg esi is becoming dead  [000054]
							Live regs: 000000C6 {ecx edx esi edi} => 00000086 {ecx edx edi}
```

As a result, the instruction we emit ends up doing the wrong thing: we emit `IN0006: 00001B 88742420     mov      byte  ptr [esp+20H], sl`, which is actually `mov      byte  ptr [esp+20H], dh`.

I am not sure what the solution is here: the local variable's type in the lclVar table is `ubyte`, but all uses in the function treat it as an `int` (i.e. all uses are of the form `lclVar int V03`). @sivarv @CarolEidt : should LSRA/lowering be constraining this lclVar's references to byte-addressable registers, or is something going wrong earlier in the pipeline?

**Comment by CarolEidt** [comment]
Once a lclVar has been promoted to a register, I believe it should be spilled and reloaded as a `TYP_INT`. Any truncation or sign extension will already have been done at the time(s) the variable is defined.
@sivarv would you agree?

**Comment by pgavlin** [comment]
Just to be clear, the byte-typed lclVar appears to be allocated to a stack slot ([esp + 20H] in this case), but is also given an "initial argument register" of ESI.

**Comment by CarolEidt** [comment]
Right - that's what's done when a register candidate lclVar is spilled (i.e. it gets a stack slot in addition to its initial register assignment). The question (to which I *think* the answer is "yes") is whether all the definitions ensure that it has the appropriately sign-/zero-extended value when it is in a register, in which case we can always spill and reload it as TYP_INT.

**Comment by sivarv** [comment]
I would agree with @CarolEidt.  As per my understanding, Small type locals on stack are normalized on store to a reg.

**Comment by pgavlin** [comment]
I've posted the full JIT dump here for context: https://gist.github.com/pgavlin/a91fdf6c716c494bc15d99673b0a149a
