### ISSUE TITLE
Make Decimal.GetBits(decimal d, byte[])

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#7247]
Would make it easier to write data to an existing buffer that way.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #12673](https://github.com/dotnet/corefx/issues/12673) via [**ZenHub**](https://www.zenhub.com/)

**Comment by danmosemsft** [comment]
Moved as FX API requests go in CoreFX, whereever the implmentation is.
