### ISSUE TITLE
Add Guid.GetBytes(byte[])

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#7251]
Today the supported way to get the `byte[]` representation of a guid is to use ToByteArray() https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Guid.cs#L893, which allocates a byte[]. Instead it would be great if there was an overload that could write into an existing `byte[]`

**Comment by mikedn** [comment]
`Guid.GetBytes(Span<byte>)`?

**Comment by davidfowl** [comment]
Would be even better. When `Span<T>` exists

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #12672](https://github.com/dotnet/corefx/issues/12672) via [**ZenHub**](https://www.zenhub.com/)
