### ISSUE TITLE
dotnet crashes with type initializer for 'CryptoInitializer' threw an exception

### ISSUE THREAD

**Issue by walkingcarpet** [dotnet/coreclr#7264]
I have downloaded the latest OpenSSL source and built/installed. 

```
which openssl
/usr/local/bin/openssl
openssl version
OpenSSL 1.1.0  25 Aug 2016
``` 

OpenSSL 1.1.0 binary, libs and includes are all in the "/usr/local" prefix. However the error dotnet is throwing when running "dotnet new" is:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6
```

As many know, the old OpenSSL (v 0.9.8) is still installed on Mac OS X. The libs are located in /usr/lib. The above error seems to indicate that dotnet is finding/using the old libs in /usr/lib rather than the new ones contained in /usr/local/lib.

Here is my dotnet info:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.10
 OS Platform: Darwin
 RID:         osx.10.10-x64
```

I've tried a couple suggestions from other threads (like adding simlinks to new libs) but so far no luck. Not sure if I'm missing something or if this is an issue with the latest when running this on OS X Yosemite. I have not tried homebrew to install OpenSSL as I've been trying to avoid homebrew so far.

**Comment by jkotas** [comment]
cc @bartonjs

**Comment by bartonjs** [comment]
@walkingcarpet We're not capable of finding the old OpenSSL because our binding is to the versioned filename (e.g. libcrypto.1.0.0.dylib).  If you believe that your library is installed properly, you can verify it with otool, e.g.:

```
bartonjs@jsb-mac:~/coreclr $ otool -L /usr/local/lib/libssl.1.0.0.dylib 
/usr/local/lib/libssl.1.0.0.dylib:
    /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/Cellar/openssl/1.0.2h_1/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
bartonjs@jsb-mac:~/coreclr $ otool -L /usr/local/lib/libcrypto.1.0.0.dylib 
/usr/local/lib/libcrypto.1.0.0.dylib:
    /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

bartonjs@jsb-mac:~/coreclr $ otool -L /usr/local/lib/libssl.1.0.0.dylib 
/usr/local/lib/libssl.1.0.0.dylib:
    /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/Cellar/openssl/1.0.2h_1/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by walkingcarpet** [comment]
Here is my output:

```
cmbp:~ chris$ otool -L /usr/local/lib/libssl.1.1.dylib 
/usr/local/lib/libssl.1.1.dylib:
	/usr/local/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

cmbp:~ chris$ otool -L /usr/local/lib/libcrypto.1.1.dylib 
/usr/local/lib/libcrypto.1.1.dylib:
	/usr/local/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by bartonjs** [comment]
@walkingcarpet Right, you've named your library 1.1.1, but we're binding on the 1.0.0 ABI name.

You'll want to make a symlink `/usr/local/lib/libssl.1.0.0.dylib` -> `/usr/local/lib/libssl.1.1.1.dylib` (and similarly for libcrypto).

**Comment by walkingcarpet** [comment]
Ah okay, I missed that. I've got a different error now. Will try to investigate that.

**Comment by walkingcarpet** [comment]
FYI - Not sure if this is a known issue, but my latest problem after the symlink fix is I get this when running dotnet new:

```
dyld: lazy symbol binding failed: Symbol not found: _CRYPTO_num_locks
  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.0.1/System.Security.Cryptography.Native.dylib
  Expected in: /usr/local/lib/libcrypto.1.0.0.dylib
```

I've been digging around trying to find info when I stumbled upon a release comment in the openssl Github (https://github.com/openssl/openssl/blob/master/CHANGES):

```
New function "CRYPTO_num_locks" that returns CRYPTO_NUM_LOCKS.
     Whoever hopes to achieve shared-library compatibility across versions
     must use this, not the compile-time macro.
```

**Comment by bartonjs** [comment]
Oh! I totally spaced on that part.  We don't support 1.1.0.  You need 1.0.2 on macOS (1.0.1 should work, but 1.0.2 is what everyone using Homebrew gets, and that's what we build against).  The 1.1 ABI is actually a breaking change.  Sorry for suggesting symlinks there, I really read "1.0.1" instead of "1.1.0".

**Comment by walkingcarpet** [comment]
No problem. I was actually in the middle of downgrading to 1.0.2 (then down to 1.0.0) and I was still having problems so I have abandoned installing openssl via source. Hopefully I removed all the bits that the various old versions installed (no "uninstall" target defined) O.o

I really don't want to install homebrew <sigh> but looks like I have no choice if I want .NET Core installed on my Mac.

**Comment by bartonjs** [comment]
Since the problem you originally had was that we don't support OpenSSL 1.1 yet I'm going to go ahead and close this issue.  If you get to a state where you think it should be working and things keep blowing up you can continue to post on this issue, or open a new one describing that problem in [dotnet/corefx](https://github.com/dotnet/corefx).
