### ISSUE TITLE
dbgshim!RegisterForRuntimeStartup has timing issue on Windows

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#7274]
**Repro steps**:

1. CreateProcess(... CREATE_SUSPENDED ...)
2. RegisterForRuntimeStartup for the new process
3. Wait 1+ seconds
4. ResumeThread

**Result**:
RegisterForRuntimeStartup will (sometimes?) send an error back to the caller with HRESULT_FROM_WIN32(ERROR_PARTIAL_COPY).

In VS this shows this error: Unable to attach to CoreCLR. Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

**Issue**
The failure seems to be coming from this line: https://github.com/dotnet/coreclr/blob/98577b986fbb79b74088a5ab3804a3ff00efbe7f/src/dlls/dbgshim/dbgshim.cpp#L472
I think we need this line to change to ignore failures from trying to enumerate the initial modules:
https://github.com/dotnet/coreclr/blob/98577b986fbb79b74088a5ab3804a3ff00efbe7f/src/dlls/dbgshim/dbgshim.cpp#L520

**Comment by mikem8361** [comment]
Waiting for shiproom approval.

**Comment by mikem8361** [comment]
It is in.
