### ISSUE TITLE
JIT LSRA: Eliminate copying of internal registers to GT_IND

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#7290]
There is code in `LinearScan::resolveRegisters()` that copies the internal registers to the `GT_IND` node from its address node. I believe it's the case that this code is obsolete and should no longer be necessary. Also, we should examine the subsequent code that does the same for `GT_ARR_ELEM` because I believe it is also obsolete.
Note that this led to #7196 on Arm64, because it was also being applied to other indirections.

**Comment by pgavlin** [comment]
@CarolEidt I think this has been resolved, no?

**Comment by CarolEidt** [comment]
Ah yes - I'd forgotten that I'd even filed an issue on this. Fixed with #12857
