### ISSUE TITLE
Building with build.cmd on Windows 8.1 fails for MSCorLib

### ISSUE THREAD

**Issue by damageboy** [dotnet/coreclr#73]
I'm not sure why, but when I build on a Windows 8.1 machine, the coreclr build for the native part finishes without any problems, but when it continues into the mscorlib part, I get the following error:

```
Commencing build of mscorlib for x64/release

C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(617,5): error : The OutputPath property is not set for project 'build.proj'.  Please check to make sure that you have specified a valid com bination of Configuration and Platform for this project.  Configuration='release'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a
non-default Configuration or Platform that doesn't exist for this project. [C:\projects\public\coreclr.git\build.proj]
MScorlib build failed. Refer C:\projects\public\coreclr.git\\binaries\Logs\MScorlib_x64__release.log for details.
```

I have VS 2015 CTP 5 installed on this machine, but this is a build triggered from the VS 2013 x64 command prompt...

**Comment by Alexx999** [comment]
I had this issue too - the problem is that you try to build from VS command prompt. It's solved by simply running from normal console

**Comment by damageboy** [comment]
Thanks!, works now!

**Comment by gkhanna79** [comment]
The invariant of requiring a clean command prompt for doing the build is documented in the Development Guide - https://github.com/dotnet/coreclr/wiki/Developer-Guide
