### ISSUE TITLE
JIT LSRA Throughput: Use streamlined resolution for MinOpts

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#7300]
When jitting with MinOpts, we could simplify register resolution by never splitting edges, and always spilling to memory on each side of a conflict (but still keeping the existing register live for those paths that match).

**Comment by pgavlin** [comment]
@CarolEidt I think this is done, is it not?

**Comment by pgavlin** [comment]
(inasmuch as we've eliminated resolution when not unregistering lclVars)

**Comment by CarolEidt** [comment]
Yes, this is now moot. Cleaerly I need to do a better job of cleaning up my issues!
