### ISSUE TITLE
mscorlib's MAX_PATH / MAX_DIRECTORY_PATH are Win32 values

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#731]
Path.MAX_PATH and Path.MAX_DIRECTORY_PATH are used to set buffer sizes and make decisions about whether paths are valid.  But they're hardcoded to Win32 values.  On Unix, they should pull the relevant values from pathconf.

**Comment by stephentoub** [comment]
cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment]
Related to #1776

**Comment by gkhanna79** [comment]
@ramarag Should your PAL changes for long file path fix this as well?

**Comment by gkhanna79** [comment]
CC @janvorli

**Comment by ramarag** [comment]
The native pieces will be done by https://github.com/dotnet/coreclr/pull/3441 
Assigning this to Jeremy for the managed part

**Comment by JeremyKuhne** [comment]
For critical paths in mscorlib the max path is now `short.MaxValue`.

I'm looking to remove preemptive checks in the next version.  #8655
