### ISSUE TITLE
Simplified GC

### ISSUE THREAD

**Issue by jdh30** [dotnet/coreclr#732]
My personal feeling is that a lot of GC and PL-implementation research is tainted by the JVM. Therefore, I think the ability to run tests on Core CLR would be extremely valuable. Consequently, I would like to propose the idea of a simple GC drop-in for Core CLR that provides minimal features in the simplest possible way and can serve as a foundation for anyone interested to start working on garbage collection in Core CLR. For example, a stop-the-world mark-sweep GC using malloc and free with a no-op write barrier.

Some things I would like to use this for:
1. Quantify the accuracy of the generational hypothesis in the context of a VM with value types. What proportion of objects really do die young in real programs?
2. Try a mark region based GC. How much slower is a non-moving GC when the generational hypothesis applies?
3. See how much lost performance can be regained by coding in a different style. Can we parse text files as quickly without a generational GC by using string slices instead of copying substrings?

**Comment by Maoni0** [comment]
The topic of replacing the GC implementation in CoreCLR with a different one was touched on in issue #430. That's a long thread so I'll copy the relevant comment from @jkotas here:

The "alt-gc" direction is possible, but not as easy.

The GC features that the CoreCLR runtime depends on (for full functionality) are pretty rich. It includes features that are not always found in experimental GC implementations out there such as interior pointers or pinning. It is non-trivial to build an alternative implementation of the rich advanced feature set.

Integrating a new GC was actually done as research project back in 2003 on top of Rotor. Some of the difficulties highlighted by the project report are not valid anymore - the interface between the CoreCLR runtime and GC is much cleaner than it used to be back in 2003. However, a lot of it is still holds - the issues listed in 5.1 "Integration Issues and Solutions" in particular.

**Comment by jdh30** [comment]
Pinning would be a no-op with a non-moving collector. I didn't know .NET supported interior pointers so I don't know what a simple solution would look like but I guess a range tree?

> Integrating a new GC was actually done as research project back in 2003 on top of Rotor. Some of the difficulties highlighted by the project report are not valid anymore - the interface between the CoreCLR runtime and GC is much cleaner than it used to be back in 2003. However, a lot of it is still holds - the issues listed in 5.1 "Integration Issues and Solutions" in particular.

Do you have a link to that project report? I cannot find it...

**Comment by Maoni0** [comment]
Sorry, I didn't notice that the link was not copied - here it is: http://wscg.zcu.cz/Rotor/NET_2004/papers/c37.pdf.

**Comment by jkotas** [comment]
http://tooslowexception.com/zero-garbage-collector-for-net-core/ has an excellent walk-through on how to build a trivial GC replacement.
