### ISSUE TITLE
Make sure morph tree narrowing code supports all relevant operator kinds

### ISSUE THREAD

**Issue by cmckinsey** [dotnet/coreclr#7350]
@mikedn  mentions morph is missing support for GT_NOT in #7099 , there may be others missing. Should audit and update to handle the relevant operators. In general any operator such that a resulting bit in position N does not depend upon an input bit in position >N can be narrowed.

**Comment by mikedn** [comment]
The obvious missing list is `GT_NOT`, `GT_NEG`, `GT_SUB` and `GT_LSH`.

`GT_RSZ`/`GT_RSH` can also be optimzed on x86 but they're special cases and likely won't fit in `optNarrowTree`. These 2 could be handled in lowering.

**Comment by erozenfeld** [comment]
Fixed by #11209
