### ISSUE TITLE
Is there a reason short.GetHashCode differs from ushort.GetHashCode?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#7351]
I noticed recently while writing tests for `EqualityComparer` that short.GetHashCode differs from ushort.GetHashCode. [The former](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Int16.cs#L70) utilizes all the bits of the int, while [the latter](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/UInt16.cs#L67) simply does a cast to int. Same for sbyte/byte.

Is there any reason calculating the hash of signed integral types should be more expensive than hashing unsigned ones?

**Comment by benaadams** [comment]
Sign extend? Short puts whether its an negative number in the high bytes?

If its a positive number they will both hash the same. If negative it will hash in sort order. Though not sure what that adds verses just casting to int which would also sign extend (though have different low bytes to the positive version)

**Comment by danmosemsft** [comment]
@jkotas do you believe there is work necessary here or should we close ?

**Comment by jkotas** [comment]
I think this can be closed.

The performance overhead of the extra xor is neglible, and there is a non-zero chance that programs and libraries out there took a hard dependency on the exact hash algorithm used for primitive types.

It has been like that forever (went back to 2001).
