### ISSUE TITLE
Dictionary should not explicitly initialize buckets to -1

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#7369]
[Dictionary](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Dictionary.cs#L219) explicitly initializes its buckets to -1 to represent an untaken bucket. We should take advantage of zero initialization and make the bitwise complement or `- 1` of a slot in the buckets represent the actual index.

**Comment by mikedn** [comment]
The only thing special about filling the array with `0` versus filling it with `-1` is the fact that we have `Array.Clear` but we don't yet have `Array.Fill`/`Buffer.BlockSet`/whatever that could do the job efficiently. It seems better to wait for the proper tools to be added rather than adding `-1` all other the place.

**Comment by jamesqo** [comment]
@mikedn `Array.Clear` is not needed, the buckets are zero-initialized. If you take a look at the PR it is completely removing the loop where we initialize things to -1.

**Comment by gkhanna79** [comment]
@danmosemsft @AlexGhiondea PTAL

**Comment by danmosemsft** [comment]
@jamesqo the outcome of the PR way back was perf data was needed. Do you expect to take another look at this? If there is a signficant perf improvement it would be interesting.

**Comment by jamesqo** [comment]
@danmosemsft I probably won't have the time since I've been pretty busy lately. You can mark this 'up for grabs' so other contributors can take it up if they're interested.

**Comment by danmosemsft** [comment]
@jamesqo that's fine, just wanted to give you first dibs. Let me know if there's other kinds of work you're interested in and I can keep my eyes open. Eg., we are working on [regex perf ](https://github.com/dotnet/corefx/issues/27124) right now.

**Comment by jkotas** [comment]
This was fixed.
