### ISSUE TITLE
Remote deploy+debug projects from Visual Studio to Linux/XPlat

### ISSUE THREAD

**Issue by OtherCrashOverride** [dotnet/coreclr#7375]
Followup to #3544

**Comment by gregg-miskelly** [comment]
@OtherCrashOverride it is somewhat unclear what this bug tracks precisely. Excluding VS for Mac and VS Code, VS has support for --
1. Local and remote Windows debugging
2. Remote attach to Linux/OSX over SSH: https://blogs.msdn.microsoft.com/visualstudioalm/2017/01/26/debugging-net-core-on-unix-over-ssh/
3. Launch to Linux/OSX over Docker

Does 2 resolve this? If not, what is your feature request?

**Comment by OtherCrashOverride** [comment]
The feature desired is analogous to the "Visual C++ for Linux Development" included in VS2017.  Instead of C++, it is desirable for C# (dotnet coreclr).
https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/

From within Visual Studio, the project is remote compiled (deployed) and debugged at the click of a button.  Remote server connections are seamlessly integrated into the IDE.

**Comment by gregg-miskelly** [comment]
@OtherCrashOverride thanks! In this case you want the .NET Core project system team.

@Andrew-MSFT is there a place we can port this issue to?

**Comment by Andrew-MSFT** [comment]
@gregg-miskelly log issues against the .NET Core project system at https://github.com/dotnet/roslyn-project-system/issues

**Comment by gregg-miskelly** [comment]
This issue was moved to dotnet/roslyn-project-system#1721
