### ISSUE TITLE
Instructions for installing on FreeBSD?

### ISSUE THREAD

**Issue by matt-richardson** [dotnet/coreclr#7387]
I see that there are instructions for [building on FreeBSD](https://github.com/dotnet/coreclr/blob/master/Documentation/building/freebsd-instructions.md), but there doesn't appear to be any instructions for how to install the built version on https://www.microsoft.com/net/core.

I see that [FreeBSD builds](http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_freebsd/) are all looking happy, and looking through the issues, I cant actually tell if FreeBSD is considered complete or not.

If it is complete, can instructions be added, or if not, can some information be added somewhere to clarify the status.

Thanks!

**Comment by gkhanna79** [comment]
@matt-richardson .NET Core builds for various platforms that we build are available at `Daily Builds` section at https://github.com/dotnet/core-setup/blob/master/README.md. 

CoreCLR is built for FreeBSD but .NET Core is not (yet).

**Comment by danmosemsft** [comment]
Please reopen if not sufficient..
