### ISSUE TITLE
coreclr fails final linking on FreeBSD due to PIC-errors

### ISSUE THREAD

**Issue by josteink** [dotnet/coreclr#739]
Attempting to build coreclr gets the build to almost 100%, where it fails with the following error:

````
$ VERBOSE=1 ./build.sh
...
Linking CXX shared library libcoreclr.so
cd /home/josteink/build/cc/bin/obj/FreeBSD.x64.Debug/src/dlls/mscoree/coreclr && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/coreclr.dir/link.txt --verbose=1
/usr/local/bin/clang++35  -fPIC  -Wall -Wno-null-conversion -std=c++11 -nostdinc++ -g -O0  -shared -Wl,-soname,libcoreclr.so -o libcoreclr.so CMakeFiles/coreclr.dir/__/mscoree.cpp.o CMakeFiles/coreclr.dir/__/unixinterface.cpp.o ../../../utilcode/dyncrt/libutilcode.a ../../../debug/ee/wks/libcordbee_wks.a ../../../debug/debug-pal/libdebug-pal.a ../../../unwinder/wks/libunwinder_wks.a ../../../vm/wks/libcee_wks.a ../../../md/compiler/wks/libmdcompiler_wks.a ../../../md/runtime/wks/libmdruntime_wks.a ../../../md/enc/wks/libmdruntimerw_wks.a ../../../md/hotdata/full/libmdhotdata_full.a ../../../classlibnative/bcltype/libbcltype.a ../../../md/ceefilegen/libceefgen.a ../../../jit/libClrJit.a ../../../classlibnative/float/libcomfloat_wks.a ../../../inc/libcorguids.a ../../../gcinfo/libgcinfo.a ../../../debug/ildbsymlib/libildbsymlib.a ../../../strongname/api/wks/libstrongname_wks.a ../../../utilcode/dyncrt/libutilcode.a ../../../binder/libv3binder.a ../../../pal/src/libcoreclrpal.so ../../../palrt/libpalrt.a -lpthread -lrt /usr/local/lib/libunwind.so /usr/local/lib/libintl.so -Wl,-rpath,/home/josteink/build/cc/bin/obj/FreeBSD.x64.Debug/src/pal/src:/usr/local/lib:
clang: warning: argument unused during compilation: '-nostdinc++'
/usr/bin/ld: ../../../debug/ee/wks/libcordbee_wks.a(dbghelpers.S.o): relocation R_X86_64_PC32 against `FuncEvalHijackWorker' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
*** [src/dlls/mscoree/coreclr/libcoreclr.so] Error code 1
````

As I'm reading this `libcordbee_wks` is not built with PIC enabled, but as far as I'm reading the [CMakeLists.txt for wks](https://github.com/dotnet/coreclr/blob/master/src/debug/ee/wks/CMakeLists.txt), it should be:

````cmake
if (WIN32)
...
else ()
add_compile_options(-fPIC)
add_library(cordbee_wks ${CORDBEE_SOURCES_WKS} ../amd64/dbghelpers.S)
endif (WIN32)
````

Any advice is appreciated.

**Comment by janvorli** [comment]
This is not caused by the missing `-fPIC` option, although the error message suggests that. The file where the issue occurs is an assembler file and the `-fPIC` option is for C/C++ compiler. 
The most likely reason is that the `dbghelpers.S` refers to a symbol that is not defined anywhere. This kind of a problem tends to exhibit this way for assembler code.
From the error I guess the `FuncEvalHijackWorker` is not being built for FreeBSD.

**Comment by janvorli** [comment]
It seems that it is being built for FreeBSD, but it looks to me that the problem could be that the  FuncEvalHijackWorker  is not defined as extern "C" and so the assembler code doesn't see it since it is mangled. 
You can try to dump the funceval.cpp.o using `objdump -t funceval.cpp.o` and see if it is that case. The .o file should be in your build folder in the following subfolder:
`/src/debug/ee/wks/CMakeFiles/cordbee_wks.dir/__/funceval.cpp.o`
On my Ubuntu, I can see the following line in the resulting dump:
`00000000000083f0 g     F .text  0000000000000963 FuncEvalHijackWorker`

**Comment by josteink** [comment]
Hey Jan! Thanks for help. I checked into it and I get the *exact* same result here, so I'm guessing it has to be something different.

````bash
$ find . -name funceval.cpp.o                                                     
./bin/obj/FreeBSD.x64.Debug/src/debug/ee/wks/CMakeFiles/cordbee_wks.dir/__/funceval.cpp.o
$ objdump -t ./bin/obj/FreeBSD.x64.Debug/src/debug/ee/wks/CMakeFiles/cordbee_wks.dir/__/funceval.cpp.o | grep FuncEvalHijackWorker
00000000000083f0 g     F .text  0000000000000963 FuncEvalHijackWorker
$
````
Any other "obvious" theories or common issues worth looking into?

**Comment by kangaroo** [comment]
@josteink objdump the archive file (libcordbee_wks) and see if the symbol is present there.

**Comment by josteink** [comment]
@kangaroo That gives me some *interesting* results:

````bash
$ find . -name 'libcordbee_wks.*'                                                                     
./bin/obj/FreeBSD.x64.Debug/src/debug/ee/wks/libcordbee_wks.a
$ objdump -t ./bin/obj/FreeBSD.x64.Debug/src/debug/ee/wks/libcordbee_wks.a | grep FuncEvalHijackWorker
0000000000000000         *UND*  0000000000000000 FuncEvalHijackWorker
00000000000083f0 g     F .text  0000000000000963 FuncEvalHijackWorker
0000000000000000         *UND*  0000000000000000 FuncEvalHijackWorker
$ 
````

The symbol seems to have one definition matching (exactly) the one from `funceval.cpp.o`, but two undefined ones. I'm going to venture a guess that this is not how things are supposed to be :)

**Comment by josteink** [comment]
Hey @ajensenwaud & @janhenke .

Any of you think you can take a look at this issue? The next few weeks I'll be overly busy IRL and wont have time to do any hacking on this project, and right now this seems to be the only left which blocks
further progress.

**Comment by janhenke** [comment]
I am also constrained on time right now, but I will try to take a look at this one too.

**Comment by janvorli** [comment]
@josteink The `objdump` result you are getting is actually ok. The lib is a collection of multiple `.o` files and only one of them implements the `FuncEvalHijackWorker` while the other two just refer to it. One of them is the `dbghelpers.S.o`.
I get the same result on my Ubuntu.
Now I think I know what causes this issue. In the `src/dlls/mscoree/coreclr/CMakeLists.txt`, there is this piece of code:
```cmake
if(CMAKE_SYSTEM_NAME STREQUAL Linux)
# This option is necessary to ensure that the overloaded delete operator defined inside
# of the utilcode will be used instead of the standard library delete operator.
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Xlinker -Bsymbolic-functions")

# The following linked options can be inserted into the linker libraries list to 
# ensure proper resolving of circular references between a subset of the libraries.
    set(START_LIBRARY_GROUP -Wl,--start-group)
    set(END_LIBRARY_GROUP -Wl,--end-group)

# These options are used to force every object to be included even if it's unused.
    set(START_WHOLE_ARCHIVE -Wl,--whole-archive)
    set(END_WHOLE_ARCHIVE -Wl,--no-whole-archive) 
endif(CMAKE_SYSTEM_NAME STREQUAL Linux)
```
The `if` needs to be changed to include FreeBSD as well.
And you'll need to do the same in `src/dlls/mscordac/CMakeLists.txt`

**Comment by janhenke** [comment]
Thanks @janvorli for the hint. That seems to fix it. We got a new linker problem though
```
Linking CXX executable corerun
cd /home/janhenke/coreclr/bin/obj/FreeBSD.x64.Debug/src/coreclr/hosts/unixcorerun && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/corerun.dir/link.txt --verbose=1
/usr/local/bin/clang++35    -Wall -Wno-null-conversion -std=c++11 -g -O0   CMakeFiles/corerun.dir/corerun.cpp.o  -o corerun  -ldl 
/usr/bin/ld: cannot find -ldl
```
What is libdl? Is it being build by coreclr or do we miss a dependency?

**Comment by janhenke** [comment]
Found it out. libdl provides dlopen on Linux and OS X. On FreeBSD it does not exists. dlopen is implemented in libc.

\o/ I got a complete build here. Let me prepare a PR. :)
