### ISSUE TITLE
Clarifying .NET Core roadmap regarding .NET Standard 2.0

### ISSUE THREAD

**Issue by johnbraden** [dotnet/coreclr#7396]
Reading [the recent blog post](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) from Immo Landwerth (Program manager on the .NET team at Microsoft) on .NET Standard 2 developments leaves open questions about some key features of .NET Core.

Recently we have published our product (100,000+ installations) with netstandard1.6 target to be executed on Windows, Linux and Mac OS and we are very happy about the cross platform capabilities of .NET Core. Installation is straight-forward, no platform specific code, it just works. If someone is interested, the .NET Core Developer package can be downloaded at https://github.com/blackcity/backload/wiki or https://www.backload.org. 

Maybe I am wrong, but the article sounds to me like the .NET team gives up the platform portability (Win/Linux/Mac) feature in order to become .NET Standard 2 compliant. I doubt, that a .NET Standard 2 base infrastructure will ever come to non Windows systems. Can you clarify this?

**Comment by shahid-pk** [comment]
Net Standard 2 has already started coming to .net core these [issues] (https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+label%3Anetstandard2.0) track the work  , and it is already present in 4.6.1 .

Disclaimar: This is my observation as user of .net core, .net core team can answer more appropriately. :smile:

**Comment by davidfowl** [comment]
> Maybe I am wrong, but the article sounds to me like the .NET team gives up the platform portability (Win/Linux/Mac) feature in order to become .NET Standard 2 compliant. I doubt, that a .NET Standard 2 base infrastructure will ever come to non Windows systems. Can you clarify this?

That's indeed incorrect. It's about bringing back more APIs, that were originally on .NET Framework and that exists on Xamarin platforms. Nobody is giving up on platform portability. In fact, if you watch the CoreCLR and CoreFX repositories you'll see most of the APIs that are coming back have a cross platform implementation where possible.

**Comment by adityamandaleeka** [comment]
@terrajobst

**Comment by danmosemsft** [comment]
@johnbraden yes whereever possible we are adding API in a cross plat fashion. Is there anything we can clarify? @terrajobst
