### ISSUE TITLE
Integrate BouncyCastle into CLR Core and CoreFX

### ISSUE THREAD

**Issue by KOLANICH** [dotnet/coreclr#74]
[BouncyCastle](http://www.bouncycastle.org/csharp/) is a free crypto library which implements a lot of functionality missing in System.Security.Cryptography. But it was designed in that way that they don't use System.Security.Cryptography at all and a lot of crypto primitives are reimplemented there and designed not in the best and optimal way. Also its API is not very convenient.
It is bad because better to have one implementation relying low level libraries and drivers to achieve better security and performance than a lot of different implementations with different APIs and which are incompatible with each other. For example, BC supports OpenPGP keyrings, System.Security.Cryptography doesn't and if I want to use OpenPGP-compatible crypto I have to use BC instead of System.Security.Cryptography.

So I think we should merge BC and System.Security.Cryptography. Both these projects use MIT licenses (BC uses ["an adaptation of the MIT X11 License"](http://www.bouncycastle.org/csharp/licence.html)), so I think there will be no licensing problems.

[Issue on CoreFX bug tracker](https://github.com/dotnet/corefx/issues/647)
[Issue on BC bug tracker](http://www.bouncycastle.org/jira/browse/BMA-131)

**Comment by robertsundstrom** [comment]
@KOLANICH This seems to be a framework question. Could you repost and elaborate in the dotnet/corefx repository? Please.

**Comment by KOLANICH** [comment]
System.Security is not a part of CoreFX

**Comment by ErikEJ** [comment]
No yet! http://blogs.msdn.com/b/dotnet/archive/2015/01/28/net-core-open-source-update.aspx
