### ISSUE TITLE
Crossgen builds will be broken when 1.1 branch is mirrored to ProjectKRel

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#7408]
When/if the 1.1 changes for PR #7342 are mirror'ed to the ProjectKRel branch the crossgen builds (x86, amd64 and arm) will be broken because the wrong ifdefs were used to define the symbol reader dll name. Should use AMD64/X86/ARM/ARM64 instead of the TARGET_* versions.

**Comment by gkhanna79** [comment]
1.1.0 is not being mirrored to KRel. Is this issue still actionable for 1.1.0?

**Comment by mikem8361** [comment]
If 1.1.0 is never mirrored to a tfs enlistment then this issue/PR can be closed.
