### ISSUE TITLE
Reference counter can work together with Mark-Compact GC

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#741]
In the topic "https://github.com/dotnet/coreclr/issues/430#issuecomment-85859392", someone mentioned reference counter as alternative garbage collector, but I think reference counter and Mark-Compact GC can work together. C# and other dotnet language should allow programmers to alloc some objects managed by RC(reference counter), for example, use keyword "rc_new" to alloc them. Even if an object is managed by RC, it is managed by GC too, for solving reference loop problem. 
When the reference count of an object is zero, it should not be freed at once, it should be freed during the next GC time. Thus, reference count seems no use, however, it can be useful if CLR organizes the memory of objects whose reference count is zero to be a linklist before they are freed by GC, and alloc memory from the linklist in priority when allocing RC objects with "rc_new". Normal objects alloced by "new" is not affected.

**Comment by jkotas** [comment]
cc @Maoni0 

Thanks for the suggestion. [Garbage Collection Handbook](http://gchandbook.org) lists hundreds of interesting memory management ideas, a few of them pretty similar to this one, with links to detailed papers written on them. The hard part is to make these ideas to work well-enough to be beneficial.

@ygc369 Are you interested in doing the experiment to prove that this particular idea is beneficial?

**Comment by Maoni0** [comment]
Yeah, feel free to experiment.

It's very common that RCed objects are not immediately freed when their ref count gets to 0 - getting rid of cycles is one reason as you pointed out; another common reason being ref counts are often only kept from heap objects to heap objects (heap RCs) and not from stack to heap objects because it's a very frequent operation that stack would hold/let go references to heap objects. So people usually don't keep track of those with mutator operations and only count them when a GC actually happens. This is a common practice in modern RC GCs.

**Comment by ygc369** [comment]
@Maoni0 
What you said is just what I want to add. Heap RC is enough, no need for stack RC if CLR only check RC after local variables are released. Keeping track of RC will let CLR know which part of allocated memory can be reused before GC happens, so GC would not have to happen frequently.
There are other benefits of RC, for example, "copy on write(COW)".tech need it. If I can get the RC of an object at any time, I can modify the object itself when its rc is one, while copy it and modify the new one when its rc is two or more.

**Comment by ygc369** [comment]
@Maoni0 
(Add Note: objects managed by RC can't be weak referenced, otherwise reusing their memory will cause problems.)
I have an idea for optimization of RC, that is grouping objects which need RC.
All objects in a group share the reference count of the group leader object, and CLR only keep track of the RC of the group leader object. When the rc of the group leader object is zero, all memory of the group can be reused. Objects in the same group can reference each other without increasing RC, but when objects not in the group reference objects in the group, the RC of the group leader object must be increased. (An alternative policy is that objects outside the group can only reference the group leader object, of course, must increase RC, if objects outside the group try to reference other objects in the group, cause exception.)
For example:
class A {int a; B pointback};
class B { A a0; int[] c };
class C {B bb;};
B b=rc_new B(); //b is managed by RC
b.a0=new(b) A(); //b.a0 belongs to group b whose group leader is object b
b.c=new(b) int[10]; //b.c belongs to group b too
b.a0.pointback=b; //no need to increase rc of b, because b.a0 and b both belong to group b
//When CLR find that object b's rc is zero, all memory of b and b.a0 and b.c can be reused
var x=b.a0; //no need to increase rc, because x is a local variable.
B b0=new B();
b0.a0=b.a0; //increase rc of b, or cause exception, because b0 is an object outside group b
C c0=new C();
c0.bb=b; //increase rc of b

**Comment by ygc369** [comment]
This feature is too complex, I give up.
