### ISSUE TITLE
Socket.Select / Read and Socket.Handle

### ISSUE THREAD

**Issue by samirparekh** [dotnet/coreclr#7413]
Hi, we have an application which we intend to port to .NETCore. This application is a latency sensitive application and it requires to monitor >100 sockets for incoming (high frequency) financial market data.

I have gone throught the implementation of Socket.Select for windows and Linux (from the available source code).

It seems like for Linux the framework allocates a stack based pointer list (in case when the provided socket list length is < 80) else on the heap. Surprising enough the same approach could have benefited wider group of windows users.

Moreover in my case where i can not go for allocating an array of >100 sockets , in my previous implementation I had a pre-allocated array/list of socket pointers/handles and reused it through the process lifecycle(thus eleminating the performance penalty imposed by GC in case of constantly re-allocating IntPtr arrays).

It seems like in the current code base it is no longer possible to get an IntPtr / handle to a socket which makes the above code optimization impossible.

May I request you (in the interest of broader community) to rethink the various scenarios and advice the possible cource of action.

Thanks

**Comment by gkhanna79** [comment]
CC @brianrob

**Comment by stephentoub** [comment]
This issue should really be in CoreFx.

> It seems like for Linux the framework allocates a stack based pointer list (in case when the provided socket list length is < 80) else on the heap. Surprising enough the same approach could have benefited wider group of windows users.

Yes, that should be doable for Windows as well.

> It seems like in the current code base it is no longer possible to get an IntPtr / handle to a socket which makes the above code optimization impossible.

Socket.Handle has been exposed.  It's not available in .NET Core 1.x, but is in .NET Core 2.0.

**Comment by gkhanna79** [comment]
Issue moved to [dotnet/corefx #16744](https://github.com/dotnet/corefx/issues/16744) via [**ZenHub**](https://www.zenhub.com/)
