### ISSUE TITLE
ICorProfilerInfo::GetCodeInfo doesn't work on NGEN images

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#7426]
We got a report from @mjsabby that this didn't work.

**Comment by noahfalk** [comment]
@msjabby - I've lost context on this one, would you mind adding an update here if this is still an active issue for you?

**Comment by noahfalk** [comment]
@mjsabby - Oops typo prevented you from getting the earlier notification. Sorry about that.

**Comment by lt72** [comment]
Please re-open if this is still a concern.
