### ISSUE TITLE
RyuJit SIMD, generates odd code indexing into a vector by a constant

### ISSUE THREAD

**Issue by mburbea** [dotnet/coreclr#7442]
Currently, if you access an AVX register used in a Vector<T> by a constant index less than 16 bytes (so on a ulong that would be 1, an int32 1,2 or 3) it generates a a shift followed by a mov operator. For 16 bytes exactly it likes to use `vextractf128` followed by a `vmov`. For anything that exceeds 16 bytes it does `vextractf128` followed by a shift and then a mov operator. I'm assuming this behavior is allowing the code to reduce to an already solved problem.  Even if vextractf128 followed by the shift is optimal (why doesn't it just generate a shift 24?), why can't ryujit realize that xmm1 has the result it needs and use it in the following code.
Here is the comment https://github.com/aspnet/KestrelHttpServer/issues/1129#issuecomment-250921745 where I saw this
Here is the relevant snipped of code::
```csharp
offset = 2;
if (_vectorUlongSpan < 4 || (u = vector64[2]) == 0)
{
        offset = 3;
        if (_vectorUlongSpan < 4 || (u = vector64[3]) == 0)
        {
```
And the assembly it generated:
```x86
vextractf128 xmm1,ymm0,1  
vmovd       rdi,xmm1  
test        rdi,rdi  
jne         00007FFF07225841  
mov         esi,3  
vextractf128 xmm1,ymm0,1  
vpsrldq     ymm1,ymm1,8  
vmovd       rdi,xmm1  
```

**Comment by sivarv** [comment]
@CarolEidt @JosephTremoulet @russellhadley 
CC: @dotnet/jit-contrib 

If I understood correctly, there were two questions asked here:

Q1:  Why generate vextractf128 followed by shift, why not just use shift if the vector element accessed is beyond 16 bytes.
Answer: AVX doesn't have an instruction to shift the entire 32-byte YMM register. AVX supports instructions to shift lower and upper 16-byte halves of a YMM register independently.  For that reason, if the element to be accessed is in upper 16-bytes, it is first extracted to a XMM register and shifted to access the right element.

Q2. When two successive indexed accesses of a SIMD vector take place why not RyuJIT optimize vextractf/shift operations generated?

Anwer: That is doable.  One possible route is that SIMD Vector index operations are expanded into Extract and Shift operations early in front-end phase.   CSE phase could evaluate Extract operation into a temp and replace all further occurrences that could be eliminated with the temp.

Right now we have issue #7422 tracking all such front-end optimizations that RyuJIT can do for SIMD types.

**Comment by sivarv** [comment]
@mburbea, @benaadams - unrolling the loop in FindFirstByteEquals() is one of the things that we have identified as potential optimizations that RyuJIT can do.  Issue #7422 tracks it as well.

**Comment by sivarv** [comment]
Optimizing vextractf128 when two successive SIMD vector elements are accessed is added to the list of possible front-end SIMD optimizations (issue #7422).

Closing this issue as issue #7422 encompasses this one as well.
