### ISSUE TITLE
Port CoreConsole runner to Unix

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/coreclr#747]
This is need to in order to be able to run Roslyn cross-platform.
The Windows version of CoreConsole can be found here: src\coreclr\hosts\coreconsole

**Comment by adityamandaleeka** [comment]
While looking at the difference between CoreRun and CoreConsole, I realized that a lot of code can be shared between the two. I will send a PR soon that will add the directories `unixcoreconsole` and `unixcoreruncommon` as peers to the existing `unixcorerun` under src/coreclr/hosts.

- `unixcoreconsole` will contain the new Unix version of CoreConsole.
- `unixcoreruncommon` will contain code that is shared between the two runners.
- The code under `unixcorerun` will be modified to use what's under `unixcoreruncommon`.

**Comment by stephentoub** [comment]
I'm curious, do we actually need two different runners?  Or if the primary difference is that unixcoreconsole will automatically try to load a .dll of the same name, could we just add that behavior into corerun somehow?

**Comment by adityamandaleeka** [comment]
It's possible, but we'd have to change how the arguments work. Today, `./corerun HelloWorld foo` will run HelloWorld and pass `foo` as an argument, but if we were to make CoreRun work like CoreConsole, it would try to execute corerun.dll and pass `HelloWorld` and `foo` as arguments to it.

We'd have to disambiguate between the two cases with some extra information (perhaps an argument that tells it to ignore the name of the current executable and use the user-specified one instead).

Are we okay with changing the current behavior of CoreRun?

**Comment by stephentoub** [comment]
> (perhaps an argument that tells it to ignore the name of the current executable and use the user-specified one instead)

Another option would be to say that "corerun" is a reserved name; if you invoke with "corerun", then it does the corerun behavior, and with any other name it does the CoreConsole behavior.

> Are we okay with changing the current behavior of CoreRun?

I don't know, but having two different runners that are otherwise identical seems a bit unfortunate.  Any other opinions?  @janvorli? @kangaroo? @jkotas?

**Comment by jkotas** [comment]
I would prefer to have multiple different runners. 

The runner is not that much code. I do not see a problem with having multiple copies. Consider - if we went with the unified runner - are we going to also unify it with the dnx runner (it is also very similar...)?

Lesson from the past - we had one unified runner in the Silverlight days and it was non-maintainable disaster.

**Comment by akoeplinger** [comment]
I'm in favor of unifying the two, they are so similar that it's just confusing IMO. Making corerun a reserved name as @stephentoub suggested seems fine to me.

**Comment by janvorli** [comment]
I'd prefer to have multiple runners, provided they build from a common source.

**Comment by sergiy-k** [comment]
I agree with @janvorli and @jkotas especially given that the core code will be shared between the two.
