### ISSUE TITLE
RyuJIT compare codegen doesn't handle regOptional

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#7480]
`TreeNodeInfoInitCmp` may mark a compare operand as reg optional. This requires codegen to release the spill temporary but compare codegen doesn't do that. Code to release the temporary was added to `emitInsBinary` but compares unfortunately don't use that.

The lack of temporary releases results in the exhaustion of pre-allocated temporaries and I believe that's the cause of the assert in #7448:

```
D:\j\workspace\x86_ryujit_ch---7ecedcb1\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(307224): error : JIT._Performance_CodeQuality_Serialization_Serialize_Serialize_._Performance_CodeQuality_Serialization_Serialize_Serialize_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---7ecedcb1\tests\runtest.proj]
        
        Assert failure(PID 5372 [0x000014fc], Thread: 5780 [0x1694]): Assertion failed 'temp != nullptr' in 'System.Uri:CheckAuthorityHelper(int,char,char,byref,byref,ref,byref):char:this' (IL size 1908)
        
            File: d:\j\workspace\x86_ryujit_ch---7ecedcb1\src\jit\regset.cpp Line: 3241
            Image: D:\j\workspace\x86_ryujit_ch---7ecedcb1\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

**Comment by mikedn** [comment]
Hrm, I was looking in the wrong place, compare codegen does use `emitInsBinary`. There's something else about reg optional that messes up temporaries.

**Comment by mikedn** [comment]
Sheesh, this is one of those codegen tricks that IMO shouldn't be there. There's this strange quark called "contained GT_AND" which is used to transform `x and c == 0` into `x test c`. This probably worked fine until reg optional was introduced and the meaning of `isContained` changed slightly. Now:

* `GT_AND` isn't actually contained, it does generate an `and` instruction
* the result of `GT_AND` is spilled (that's kind of weird since it will be used in the next instruction but that's another story)
* `genCompareInt` calls `genConsumeOperands` which does nothing because `GT_AND` is spilled and reg optional
* `genCompareInt` then thinks that `GT_AND` is contained because of `isContainedSpillTemp` and passes the first operand of `GT_AND` to `emitInsBinary` instead of passing the `GT_AND` node itself
* `emitInsBinary` now sees a `GT_IND`, this one is not reg optional so the temporary used to spill `GT_AND` isn't released

**Comment by BruceForstall** [comment]
cc @sivarv

**Comment by sivarv** [comment]
@mikedn - genCompareInt() logic needs to be fixed to consider GT_AND is marked as contained by lowerxarch only under the following condition.  This roughly corresponds to line 6069 in codegenxarch.cpp

```
if ((op1->OperGet() == GT_AND) && (op->GtGetOp2()->IsisContainedIntOrIImmed()))
{
                ins = INS_test;        // we will generate "test andOp1, andOp2CnsVal"
                op2 = op1->gtOp.gtOp2; // must assign op2 before we overwrite op1
                op1 = op1->gtOp.gtOp1; // overwrite op1

                if (op1->isContainedMemoryOp())
                {
                    // use the size andOp1 if it is a contained memoryop.
                    cmpAttr = emitTypeSize(op1->TypeGet());
                }
                // fallthrough to emit->emitInsBinary(ins, cmpAttr, op1, op2);
}
```

Can you give me an idea of the tree under GT_EQ/NE node?

If it is GT_EQ/NE(GT_AND(op1, GT_CNS_INT(c)), GT_CNS_INT(0)), how come TreeNodeInfoInitCmp() is not marking GT_AND as contained?

If it is some other tree because of which TreeNodeInfoInitCmp() didn't mark GT_AND as contained, then how come the following assert on line 6071 in codegenxarch.cpp wasn't fired before emitInsBinary() call is made?

`noway_assert(op1->gtOp.gtOp2->isContainedIntOrIImmed());`

**Comment by mikedn** [comment]
> Can you give me an idea of the tree under GT_EQ/NE node?

It's actually a `GT_GT` node, for some reason the C# compiler emits `x and c > 0` instead of `x and c != 0`. The method code is [here](https://github.com/dotnet/corefx/blob/f85ed12e53cca24d7c35ed86009f2aad13402adf/src/System.Private.Uri/src/System/Uri.cs#L3945). The IR that leads to the assert is the following:
```
N089 (???,???) [003451] -----------Z     t3451 =    LCL_VAR   byref  V99 rat14         eax REG eax RV

                                                 /--*  t3451  byref  
N091 (  3,  2) [000039] *--XG------Z       t39 = *  IND       int    REG eax $440

N093 (???,???) [003452] -----------z     t3452 =    LCL_VAR   byref  V99 rat14         (last use) REG eax

                                                 /--*  t3452  byref  
N095 (???,???) [003453] ------------     t3453 = *  LEA(b+4)  ref    REG NA

                                                 /--*  t3453  ref    
N097 (???,???) [003454] *--XG------Z     t3454 = *  IND       int    REG eax

N099 (  3, 10) [000040] ------------       t40 =    CNS_INT   int    0 REG NA

N101 (???,???) [003456] ------------     t3456 =    CNS_INT   int    2 REG NA

                                                 /--*  t39    int    
                                                 +--*  t40    int    
N103 ( 10, 16) [000041] ---XG------Z       t41 = *  AND       int    REG eax

                                                 /--*  t3454  int    
                                                 +--*  t3456  int    
N105 (???,???) [003458] ---XG------Z     t3458 = *  AND       int    REG eax

N107 (  3, 10) [000043] ------------       t43 =    CNS_INT   int    0 REG NA

                                                 /--*  t41    int    
                                                 +--*  t43    int    
N109 ( 20, 30) [000044] N--XG----U-Z       t44 = *  GT        int    REG eax $208

                                                 /--*  t44    int    
               [004364] ---XG-------     t4364 = *  RELOAD    int    REG edx

N111 (???,???) [003460] ------------     t3460 =    CNS_INT   int    0 REG NA

                                                 /--*  t3458  int    
                                                 +--*  t3460  int    
N113 (???,???) [003475] N--XG----U--     t3475 = *  GT        int    REG eax

                                                 /--*  t3475  int    
                                                 +--*  t4364  int    
N115 (???,???) [003476] ---XG-------     t3476 = *  SELCC     int    REG eax

                                                 /--*  t3476  int    
N117 ( 20, 30) [000046] DA-XG-------             *  STORE_LCL_VAR int    V14 loc6         d:3 REG NA
```

The 2 GT_ANDs in the middle are spilled and at least one of them ends up as reg optional. Then code is generated for the first GT_GT a temporary is not released and then GT_GT itself is spilled. An assert fires here because max spill is 2 and both temporaries are still in use.

> If it is GT_EQ/NE(GT_AND(op1, GT_CNS_INT(c)), GT_CNS_INT(0)), how come TreeNodeInfoInitCmp() is not marking GT_AND as contained?

As mentioned above it's not GT_EQ/GT_NE. Probably an assert in codegen would have been useful here, as it is now it simply assumes that it is eq/ne if it sees a contained GT_AND.

> then how come the following assert on line 6071 in codegenxarch.cpp wasn't fired before emitInsBinary() call is made?

As you can see there's actually a `x and constant` in there.

> genCompareInt() logic needs to be fixed to consider GT_AND is marked as contained by lowerxarch only under the following condition. This roughly corresponds to line 6069 in codegenxarch.cpp

I'll try, we probably need to check if the compare is GT_EQ/GT_NE as well.

**Comment by sivarv** [comment]
Yes, genCompareInt() also need to check that it is GT_EQ/NE
