### ISSUE TITLE
Non-generic Array.Reverse should be rewritten entirely in native code

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#7491]
Currently, `Array.Reverse` performs boxing and is very slow for non-primitive structs. It also suffers the overhead of covariant type checks if the destination array contains reference types.

Since this api is used by [Stack.ICollection.CopyTo](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Stack.cs#L159) and I'm thinking of optimizing `Enumerable.ToArray` for nongeneric ICollections, maybe it would be worth moving Reverse entirely to native code to avoid the boxing, in spite of the generic version that was recently added.

cc @justinvp

**Comment by mikedn** [comment]
Hmm, what real world app have you seen where such an eclectic mix of features (generic stack of value types, use of non-generic `ICollection`, use of `ToArray`/`CopyTo` with a stack) exists and it is a performance bottleneck?

**Comment by jkotas** [comment]
Agree with @mikedn.

Also, rewriting this in native code would be going backwards. Any improvements should be done as managed impl - there are a lot of examples in CoreRT how to do it. (The small core building blocks - like bulk write barrier that you would likely need in this case - are ok.)
