### ISSUE TITLE
Types from assembly referenced by app should be unified in custom load context

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#7493]
From @pranavkm:

Here’s a summary of the issue:
 
•	Application references LibraryA
•	LibraryB references LibraryA
•	We create a ProjectLoadContext and use it to load LibraryB
 
Using Microsoft.NETCore.App 1.0.0, types from LibraryA in the default load context and the created load context are unified. With 1.1.0-preview1-001090-00, this no longer seems to be true.

**Comment by gkhanna79** [comment]
.NET Core 1.0.0 had a bug where for the scenario below we would endup loading LibraryA from DefaultLoadContext directly, without first allowing the custom load context (ProjectLoadContext in the example below) to perform the resolution of the requested load (of LibraryA). Only if the custom load context does not resolve the assembly should we fallback to DefaultLoadContext to look for the assembly.
 
Does your ProjectLoadContext implement the override of Load method that ends up loading LibraryA when LibraryB is loaded?

**Comment by gkhanna79** [comment]
CC @davidfowl @muratg

**Comment by gkhanna79** [comment]
The CoreCLR bug in .NET Core 1.0.0 was https://github.com/dotnet/coreclr/issues/6670.

**Comment by gkhanna79** [comment]
To get the same behaviour as .NET Core 1.0.0, update your AssemblyLoadContext implementation's Load method to first resolve the assembly using DefaultLoadContext (usingAssemblyLoadContext.Default.LoadFromAssemblyName) before explicitly loading the assembly (which I suspect is happening).

**Comment by gkhanna79** [comment]
@pranavkm @muratg Please let me know if there are any further questions. As suggested above, you will need to make a change in your AssemblyLoadContext implementation to get the behaviour as before.

**Comment by pranavkm** [comment]
Thanks. The LoadContext we use is from the CLI - https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel.Loader/ProjectLoadContext.cs#L61-L70 and it doesn't have this behavior. I'll figure out if we can get them to take a fix for this or if we can workaround by wrapping their load context in our tool's callsite.

**Comment by gkhanna79** [comment]
Your code is calling CreateLoadContext that does not appear to be in their repo and is an extension method that returns an AssemblyLoadContext and not ProjectLoadContext type.

You should look for CreateLoadContext implementation and the implementation of ALC type returned by it.



Thanks,
Gaurav


-------- Original message --------

**Comment by gkhanna79** [comment]
Closing since issue is now being tracked in CLI - https://github.com/dotnet/cli/issues/4316
