### ISSUE TITLE
RyuJIT x86: implement profiler enter/leave callback

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#7499]
There are at least 2 NYI:

"RyuJIT: Emit Profiler Enter callback"
"RyuJIT: Emit Profiler Leave callback"

Question: are the profiler APIs, and enter/leave callbacks, supported on .NET Core?

**Comment by cmckinsey** [comment]
@noahfalk ?

**Comment by noahfalk** [comment]
Spoke with Bruce in person, but for anyone following along the quick answer is:

We want them to be supported, but they are not officially supported right now. Current profiler state is described in more detail here: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/profiling-api-status.md

**Comment by pgavlin** [comment]
@RussKeldorph @BruceForstall @noahfalk do we need this for 1.2, or should this be in Future?

**Comment by BruceForstall** [comment]
Without this, we have a regression from JIT32, so probably 1.2, despite the profiler APIs not really being supported.

**Comment by noahfalk** [comment]
Sounds like our dependency doesn't matter too much in the end, but if it does again Lorenzo @lt72 owns deciding that at our end.
