### ISSUE TITLE
WARNING: The target process exited without raising a CoreCLR started event.

### ISSUE THREAD

**Issue by ppatel26** [dotnet/coreclr#7541]
[WARNING: The target process exited without raising a CoreCLR started event. #4657](https://github.com/dotnet/coreclr/issues/4657)

> WARNING: The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use Microsoft.NetCore.App 1.0.0 or newer. This may be expected if the target process did not run .NET code.

I still have the same warning after downloading the latest build (1.0.0-preview2-003131) while executing Hello World! application

**Comment by mikem8361** [comment]
I don't think 1.0.0-preview2-003131 is the latest.  The latest 1.0 "Microsoft.NETCore.App" package is 1.0.4. There is also a 1.1.1 package now too. Could you try one of those versions?

**Comment by lt72** [comment]
@mikem8361: please close this issue if you think this may have been fixed by your latest changes RE: debugger attach.
