### ISSUE TITLE
RyuJIT x86: Assertion failed '!"Unexpected fieldAccessor"'

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7545]
set complus_altjitngen=*

crossgen.exe Microsoft.CodeAnalysis.CSharp.dll

Assert failure(PID 22752 [0x000058e0], Thread: 30604 [0x778c]): Assertion failed '!"Unexpected fieldAccessor"' in 'Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.ContextAwareSyntax:ClassOrStructConstraint(char,ref):ref:this' (IL size 80)
    File: c:\michelm\coreclr\src\jit\importer.cpp Line: 13203

We also hit this assert crossgen'ing System.ComponentModel and System.Runtime

**Comment by mikedn** [comment]
The field accessor in question is `CORINFO_FIELD_INSTANCE_WITH_BASE`. This is a Ready to Run thing.

**Comment by sandreenko** [comment]
Was fixed in #7576.
