### ISSUE TITLE
RyuJIT x86:  Assertion failed '(!value) != (!pValue)'

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7547]
set complus_altjitngen=*

crossgen.exe System.Net.Http.dll

Assert failure(PID 20596 [0x00005074], Thread: 13700 [0x3584]): Assertion failed '(!value) != (!pValue)' in '<>f__AnonymousType0`3[__Canon,__Canon,__Canon][System.__Canon,System.__Canon,System.__Canon]:Equals(ref):bool:this' (IL size 83)
    File: c:\michelm\coreclr\src\jit\gentree.cpp Line: 6634
    Image: C:\michelm\coreclr\bin\Product\Windows_NT.x86.Checked\crossgen.exe

**Comment by sandreenko** [comment]
Was fixed in #7576.
