### ISSUE TITLE
Pull corefx specific APIs out of libcoreclrpal when reasonable.

### ISSUE THREAD

**Issue by ellismg** [dotnet/coreclr#755]
We should adopt the precident that @bartonjs has set with fdc9a0419c55acafa8cd087964e70e0ed87460e1 and take the corefx specific APIs out of the PAL and into standalone native libraries for the cases where we were just using the PAL as a nice place to dump some native code.

/cc @stephentoub @jkotas

**Comment by stephentoub** [comment]
cc: @nguerrera

**Comment by ellismg** [comment]
This is done.
