### ISSUE TITLE
[question] Getting total generated code size from a JitDump

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#7556]
Sorry for my ineptitude at figuring these things out, but how do you get the number of the total bytes of code the JIT produces for a given program (i.e. the sum of the code size of all of the methods it generates)? Is there a configuration knob to control this? `JitDisasm` seems to only print the code size for a particular set of methods.

**Comment by benaadams** [comment]
Might want to ask in https://github.com/dotnet/jitutils ?

**Comment by jamesqo** [comment]
Hm, good idea. I'll keep this issue open though, in case someone knowledgeable enough stumbles across it here.

**Comment by benaadams** [comment]
This is how I generate my outputs:

Build coreclr checked and release (can keep using these till you want an new update of coreclr)

coreclr> `build all x64 x86 Checked Release skiptests`

Build test app as win7-x64 standalone and publish

Copy all files from `coreclr\bin\Product\Windows_NT.x64.Release` and `pdb` to your standalone publish directory e.g. `bin\Release\netcoreapp1.0\win7-x64\publish`

Copy `clrjit.dll` over from checked  `coreclr\bin\Product\Windows_NT.x64.Checked` into the same publish directory.

Set the environment vars
`set COMPlus_JitPrintInlinedMethods=1`
`set COMPlus_JitDisasm=*`

Run your standalone exe from the publish directory probably piping its output to a file ` > dasm.txt`

You can also get the jit to only output a certain disassembly e.g. `set COMPlus_JitDisasm=System.Generic.*`

The jit will work in parallel, so wait for start up to complete before you try doing stuff and try not to parallelise before jitting complete a page or the output will get interleaved.

May want to set
`set COMPlus_JitDiffableDasm=1`

If you want it diffable - not sure if it would be happy with the inlining at same time

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib @BruceForstall @pkukol

**Comment by BruceForstall** [comment]
You can use COMPlus_JitDisasm and parse the line that looks like:
```
; Total bytes of code 161, prolog size 11 for method <some function name>
```
and then add them up.

You could set `COMPlus_NgenOrder=1` and crossgen the app; you'll get one line per function, with the number of bytes hot and cold code as two of the columns.

`COMPlus_JitFunctionTrace=1` also dumps the generated code size per function.

**Comment by briansull** [comment]
It is easier to add up the byte of Hot/Cold code from the information produced by 
 set COMPlus_JitOrder=1

**Comment by pgavlin** [comment]
@benaadams it looks like your question has been answered, so I'm going to close this issue. Please feel free to re-open this issue if I've closed it too soon.
