### ISSUE TITLE
Please make weak reference a language feature instead of class

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#756]
Current weak reference is class, when we use it, we must alloc slots from short or long weak reference table. Thus we can't use too many weak references. But I think this is not necessary. When GC happens, CLR can update strong references of living objects after compaction, why not update weak references of freed objects to be null at the same time? So weak reference can be a language feature instead of class, for example, use keyword "weakref" to specify a variable to store weak reference of an object.
Example:
Class A
{
    weakref int[] a;
    weakref object b;
};

**Comment by kangaroo** [comment]
@ygc369 Language features like this should be made against the roslyn repo.  There may be some runtime support needed here, but that work would coincide with a language spec update.

**Comment by jkotas** [comment]
System.Runtime.InteropServices.GCHandle is unsafe low-level weak reference type that avoids the problem with extra allocation that you are pointing out.

The feature request to create a first class syntax for it should go into Roslyn repo as @kangaroo pointed out. There is actually a very similar one already - focused on event handlers: https://github.com/dotnet/roslyn/issues/101
