### ISSUE TITLE
String::Format Memory Optimization Degrades Performance under RuyJIT 64

### ISSUE THREAD

**Issue by hypersw** [dotnet/coreclr#7569]
The `String::Format` methods have been updated some time ago to eliminate excessive array object allocations and reduce memory traffic.

Was:
```C#
public static String Format(String format, Object arg0) {
    return Format(null, format, new Object[] {arg0}); }
```

Now:
```C#
public static string Format(string format, object arg0) {
    return string.FormatHelper((IFormatProvider) null, format, new ParamsArray(arg0)); }
```

Unfortunately, with RyuJIT x64 this makes simple functions execute up to 10 (ten!) times slower than before in code paths which *do not call* `String::Format`.

Here is a code sample.

```C#
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static int FastFunctionNotCallingStringFormat(int param)
    {
      if(param < 0)
        throw new Exception(string.Format("We do not like the value {0:N0}.", param));
      if(param == int.MaxValue)
        throw new Exception(string.Format("{0:N0} is maxed out.", param));
      if(param > int.MaxValue / 2)
        throw new Exception(string.Format("We do not like the value {0:N0} either.", param));
      return param * 2;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static int FastFunctionNotHavingStringFormat(int param)
    {
      if(param < 0)
        throw new ArgumentOutOfRangeException("param", "We do not like this value.");
      if(param == int.MaxValue)
        throw new ArgumentOutOfRangeException("param", "Maxed out.");
      if(param > int.MaxValue / 2)
        throw new ArgumentOutOfRangeException("param", "We do not like this value either.");
      return param * 2;
    }

    private static int Main()
    {
      int sum = 0;
      for(int a = int.MaxValue / 2; a --> 0;)
      {
        sum = unchecked(sum + FastFunctionNotHavingStringFormat(a));
        sum = unchecked(sum + FastFunctionNotCallingStringFormat(a));
      }
      Console.WriteLine(sum);
      return 0;
    }
```

> A real-life example of this mock-up would be a collection object which has range checks with diagnostics in its `get_Item` indexer. That's how we've hit it: a simple enough indexer suddenly showed up as the hottest function in the profile.

Notice that `String::Format` is *never* called within the course of execution. Supposedly, these two functions should run at the same speed.

Now that's what it looks like in the profiler:

![image](https://cloud.githubusercontent.com/assets/2332070/19285158/12ecc1f8-900a-11e6-86af-3684ecd15d43.png)

None of these functions calls formatting, but the one which merely has it on unused code paths takes tenfold (well, almost) time to execute.

If we go even deeper, the code which takes up the extra time is:
```asm
lea rdi, ptr [rsp+0x28]
mov ecx, 0x20
xor eax, eax
rep stosd dword ptr [rdi]
```
It is located in the function head, before any user code.
That's like doing `ZeroMemory` on the stack frame, and quite an amount of that.

From this I can guess that:
* JIT has inlined the `String::Format` function into the `FastFunctionNotCallingStringFormat` body.
* `System.ParamsArray` now lives on the stack frame of `FastFunctionNotCallingStringFormat`.
* Even though the scopes of the three `System.ParamsArray` copies do not intersect, each seems to be getting its own space in the stack frame. The amount is `0x20 * sizeof(DWORD)`, or `128` bytes, which is enough for entire `4 * sizeof(ParamsArray)`.
* Even though these `System.ParamsArray`s are never used or created in the actually executed code, `ZeroMemory` for them has been pulled up to the head of the function, and it affects any call to this function.

So string-formats which are only sitting there but are never called do suddenly have a cost.

> UPD: Mostly the same happens in 32-bit runtimes, even the relative speeds are the same, even though both lower somewhat.

I hope for the following improvements:
* Costly `ZeroMemory` could be moved closer to the usage; the JITter might even know when it is safe to omit it altogether, but the point is to avoid this until (and unless) the structure is put to use. 
* Memory could be reused for structures whose lifetimes never intersect (and even are of the same type).

**Comment by hypersw** [comment]
UPD2: I've actually tested this with the desktop .NET Framework `4.6.01038` because it is currently our main runtime (up until coreclr gets most of the missing types and members).

**Comment by russellhadley** [comment]
@hypersw this does look like a good instance where the cost of zeroing memory in the function entry is getting us.   (that and not having stack packing) @briansull do have any optimizations for doing this in a flow sensitive way?

**Comment by omariom** [comment]
Looks similar to https://github.com/dotnet/coreclr/issues/1133

AFAIK, it s going to be targeted by First Class Structs https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/first-class-structs.md

**Comment by hypersw** [comment]
#1133 is related, though covers different effects of inlining and does not stress the effect of zeroing.

As for the *First Class Structs*, it looks like the proposal is mostly about removing the penalty of wrapping simple things in a struct and might not be targeting things as large as this `ParamsArray` (four pointers, `32` bytes).

**Comment by russellhadley** [comment]
@omariom it's related to first class structs but not handled by the current set of changes going in.  It boils down to how we represent and report the struct for the GC.  Today we're treating it as untracked and thus zeroing it at entry.  If we could instead track the liveness of the struct - or the underlying GC fields - we could then report a more minimal GC lifetimes and avoid the zeroing.  The other issue of keeping three copies is a separate issue in that we don't implement stack packing.  @swaroop-sridhar can you take a peek at this?

**Comment by russellhadley** [comment]
@AndyAyersMS, there's also the case that we shouldn't be inlining methods 1) on paths to throw, or 2) that grow the zero init cost of the parent function too much.

**Comment by benaadams** [comment]
@russellhadley 
> there's also the case that we shouldn't be inlining methods 1) on paths to throw

Related, if the throws were in method calls so
```csharp
public static int FastFunctionNotCallingStringFormat(int param)
{
  if(param < 0)
	ThrowTooSmallException(param);
  if(param == int.MaxValue)
	ThrowTooBigException(param);
  if(param > int.MaxValue / 2)
	ThrowNotGoodException(param);
  return param * 2;
}
```
Then the jit in Core 1.1.0 will not inline them (https://github.com/dotnet/coreclr/pull/6103)

**Comment by AndyAyersMS** [comment]
Maybe I'm overlooking something, but it seems like in the slow case the jit should be removing the unused struct locals introduced by inlining instead of zeroing them.

There is an inlining case here but it is more subtle. If the callee contains a struct local that is used, and the call site is conditional with low likelihood of execution, and the jit always hoists struct zero inits to the caller's prolog, then the inline should be considered more costly. But if the local is not used then it shouldn't need to be zeroed.

**Comment by AndyAyersMS** [comment]
I guess we have to assume the local is used here. So case 2 applies, since the call site is post dominated by a throw and so is quite likely infrequently executed. There's a penalty for this already but it may not be enough to block the inline if the method is small.

**Comment by briansull** [comment]
There also could be a penalty when considering inlining a method that contains struct with GC pointers.
The penalty could be proportional to the size of the struct (as that is the amount of memory that would get zero-ed)

**Comment by AndyAyersMS** [comment]
The version of `String.Format` called here is only 14 bytes of IL so it falls into the `ALWAYS_INLINE` category. So the fact that the call site is likely rarely executed (which the jit knows) is not considered.

**Comment by controlflow** [comment]
I wonder how BCL changes like this passed performance review: I saw a tons of places where `string.Format` overloads are used on exception throw paths (since exception constructors normally only take strings as a input) + overloads are small enough to be inlined = no one know how various JITs would deal with this `System.ParamsArray` struct :\

**Comment by tom3m** [comment]
@controlflow We all humans, without having automated perf tests based on some baseline IMHO it is not possible ti find such things.

**Comment by benaadams** [comment]
Looking at the some related dasm with everything associated with the exceptions is moved into the ` Beginning of cold code` section so for example [`RegisterForFullGCNotification`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/GC.cs#L405-L431) which has a similar pattern produces the following results:

I believe all the ParamsArrays are being marked as `do-not-enreg[XSB] must-init addr-exposed` and there is one for each call.

C#
<details>
```csharp
public static void RegisterForFullGCNotification(int maxGenerationThreshold, int largeObjectHeapThreshold)
{
	if ((maxGenerationThreshold <= 0) || (maxGenerationThreshold >= 100))
	{
		throw new ArgumentOutOfRangeException("maxGenerationThreshold", 
											  String.Format(
												  CultureInfo.CurrentCulture,
												  Environment.GetResourceString("ArgumentOutOfRange_Bounds_Lower_Upper"), 
												  1, 
												  99));
	}
	
	if ((largeObjectHeapThreshold <= 0) || (largeObjectHeapThreshold >= 100))
	{
		throw new ArgumentOutOfRangeException("largeObjectHeapThreshold", 
											  String.Format(
												  CultureInfo.CurrentCulture,
												  Environment.GetResourceString("ArgumentOutOfRange_Bounds_Lower_Upper"), 
												  1, 
												  99));
}

	if (!_RegisterForFullGCNotification(maxGenerationThreshold, largeObjectHeapThreshold))
	{
		throw new InvalidOperationException(Environment.GetResourceString("InvalidOperation_NotWithConcurrentGC"));
	}
}
```
</details>

Inlines
<details>
```
**************** Inline Tree
Inlines into 06003767 GC:RegisterForFullGCNotification(int,int)
  [1 IL=0042 TR=000042 06001345] [below ALWAYS_INLINE size] String:Format(ref,ref,ref,ref):ref
    [0 IL=0004 TR=000179 060039D0] [FAILED: unprofitable inline] ParamsArray:.ctor(ref,ref):this
  [0 IL=0047 TR=000055 060036B7] [FAILED: unprofitable inline] ArgumentOutOfRangeException:.ctor(ref,ref):this
  [2 IL=0095 TR=000111 06001345] [below ALWAYS_INLINE size] String:Format(ref,ref,ref,ref):ref
    [0 IL=0004 TR=000214 060039D0] [FAILED: unprofitable inline] ParamsArray:.ctor(ref,ref):this
  [0 IL=0100 TR=000124 060036B7] [FAILED: unprofitable inline] ArgumentOutOfRangeException:.ctor(ref,ref):this
  [0 IL=0108 TR=000141 06003763] [FAILED: cannot get method info] GC:_RegisterForFullGCNotification(int,int):bool
  [0 IL=0125 TR=000161 06002EB5] [FAILED: unprofitable inline] InvalidOperationException:.ctor(ref):this
Budget: initialTime=456, finalTime=488, initialBudget=4560, currentBudget=4560
Budget: initialSize=3140, finalSize=3140
```
</details>
Asm
<details>
```asm
; Assembly listing for method GC:RegisterForFullGCNotification(int,int)
; Emitting BLENDED_CODE for X64 CPU with SSE2
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  5,   5  )     int  ->  rcx        
;  V01 arg1         [V01,T01] (  5,   5  )     int  ->  rdx        
;  V02 tmp0         [V02,T03] (  3,   0  )     ref  ->  rsi        
;  V03 tmp1         [V03,T02] (  6,   0  )     ref  ->  rdi        
;  V04 tmp2         [V04,T04] (  3,   0  )     ref  ->  rdi        
;  V05 tmp3         [V05,T05] (  3,   0  )     ref  ->  rsi        
;  V06 tmp4         [V06,T06] (  3,   0  )     ref  ->  rsi        
;  V07 tmp5         [V07,T07] (  3,   0  )     ref  ->  rsi        
;  V08 tmp6         [V08,T08] (  2,   0  )     ref  ->  rbx        
;  V09 tmp7         [V09,T09] (  2,   0  )     ref  ->  rbp        
;  V10 tmp8         [V10,T10] (  2,   0  )     ref  ->  rdx        
;  V11 tmp9         [V11,T11] (  2,   0  )     ref  ->   r8        
;  V12 tmp10        [V12    ] (  3,   0  )  struct (32) [rsp+0x68]   do-not-enreg[XSB] must-init addr-exposed
;  V13 tmp11        [V13,T12] (  2,   0  )     ref  ->  rbx        
;  V14 tmp12        [V14,T13] (  2,   0  )     ref  ->  rbp        
;  V15 tmp13        [V15,T14] (  2,   0  )     ref  ->  rdx        
;  V16 tmp14        [V16,T15] (  2,   0  )     ref  ->   r8        
;  V17 tmp15        [V17    ] (  3,   0  )  struct (32) [rsp+0x48]   do-not-enreg[XSB] must-init addr-exposed
;  V18 tmp16        [V18    ] (  6,   0  )  struct (32) [rsp+0x28]   do-not-enreg[XSB] must-init addr-exposed
;  V19 tmp17        [V19,T16] (  2,   0  )     ref  ->  rcx        
;  V20 tmp18        [V20,T17] (  2,   0  )     ref  ->  rdx        
;  V21 tmp19        [V21,T18] (  2,   0  )     ref  ->  rsi        
;  V22 tmp20        [V22,T19] (  2,   0  )     ref  ->   r8        
;  V23 tmp21        [V23,T20] (  2,   0  )     ref  ->  rcx        
;  V24 tmp22        [V24,T21] (  2,   0  )     ref  ->  rdx        
;  V25 tmp23        [V25,T22] (  2,   0  )     ref  ->  rdi        
;  V26 tmp24        [V26,T23] (  2,   0  )     ref  ->   r8        
;  V27 tmp25        [V27,T24] (  2,   0  )     ref  ->  rdx        
;  V28 OutArgs      [V28    ] (  1,   1  )  lclBlk (32) [rsp+0x00]  
;
; Lcl frame size = 136
G_M48484_IG01:
       push     rdi
       push     rsi
       push     rbp
       push     rbx
       sub      rsp, 136
       mov      rsi, rcx
       lea      rdi, [rsp+28H]
       mov      ecx, 24
       xor      rax, rax
       rep stosd 
       mov      rcx, rsi
G_M48484_IG02:
       test     ecx, ecx
       jle      G_M48484_IG06
       cmp      ecx, 100
       jge      G_M48484_IG06
G_M48484_IG03:
       test     edx, edx
       jle      G_M48484_IG09
       cmp      edx, 100
       jge      G_M48484_IG09
G_M48484_IG04:
       call     GC:_RegisterForFullGCNotification(int,int):bool
       test     eax, eax
       je       G_M48484_IG12
G_M48484_IG05:
       add      rsp, 136
       pop      rbx
       pop      rbp
       pop      rsi
       pop      rdi
       ret      
************** Beginning of cold code **************
G_M48484_IG06:
       lea      rcx, [(reloc)]
       call     CORINFO_HELP_NEWSFAST
       mov      rsi, rax
       lea      rcx, [(reloc)]
       call     CORINFO_HELP_NEWSFAST
       mov      rdi, rax
       call     CultureInfo:get_CurrentCulture():ref
       mov      rbx, rax
       mov      ecx, 0x571D
       call     CORINFO_HELP_STRCNS_CURRENT_MODULE
       mov      rcx, rax
       call     Environment:GetResourceString(ref):ref
       mov      rbp, rax
       mov      dword ptr [rsi+8], 1
       mov      rdx, rsi
       mov      dword ptr [rdi+8], 99
       mov      r8, rdi
       xor      rcx, rcx
       lea      rax, bword ptr [rsp+68H]
       xorpd    xmm0, xmm0
       movdqu   qword ptr [rax], xmm0
       movdqu   qword ptr [rax+16], xmm0
       lea      rcx, bword ptr [rsp+68H]
       call     ParamsArray:.ctor(ref,ref):this
       lea      rcx, [(reloc)]
       call     CORINFO_HELP_NEWSFAST
       mov      rdi, rax
       mov      ecx, 0x14E00
       call     CORINFO_HELP_STRCNS_CURRENT_MODULE
       mov      rsi, rax
       mov      rcx, rbx
       mov      rdx, rbp
G_M48484_IG07:
       movdqu   xmm0, qword ptr [rsp+68H]
       movdqu   qword ptr [rsp+28H], xmm0
       movdqu   xmm0, qword ptr [rsp+78H]
       movdqu   qword ptr [rsp+38H], xmm0
G_M48484_IG08:
       lea      r8, bword ptr [rsp+28H]
       call     String:FormatHelper(ref,ref,struct):ref
       mov      r8, rax
       mov      rdx, rsi
       mov      rcx, rdi
       call     ArgumentOutOfRangeException:.ctor(ref,ref):this
       mov      rcx, rdi
       call     CORINFO_HELP_THROW
G_M48484_IG09:
       lea      rcx, [(reloc)]
       call     CORINFO_HELP_NEWSFAST
       mov      rdi, rax
       lea      rcx, [(reloc)]
       call     CORINFO_HELP_NEWSFAST
       mov      rsi, rax
       call     CultureInfo:get_CurrentCulture():ref
       mov      rbx, rax
       mov      ecx, 0x571D
       call     CORINFO_HELP_STRCNS_CURRENT_MODULE
       mov      rcx, rax
       call     Environment:GetResourceString(ref):ref
       mov      rbp, rax
       mov      dword ptr [rdi+8], 1
       mov      rdx, rdi
       mov      dword ptr [rsi+8], 99
       mov      r8, rsi
       xor      rcx, rcx
       lea      rax, bword ptr [rsp+48H]
       xorpd    xmm0, xmm0
       movdqu   qword ptr [rax], xmm0
       movdqu   qword ptr [rax+16], xmm0
       lea      rcx, bword ptr [rsp+48H]
       call     ParamsArray:.ctor(ref,ref):this
       lea      rcx, [(reloc)]
       call     CORINFO_HELP_NEWSFAST
       mov      rsi, rax
       mov      ecx, 0x14E2E
       call     CORINFO_HELP_STRCNS_CURRENT_MODULE
       mov      rdi, rax
       mov      rcx, rbx
       mov      rdx, rbp
G_M48484_IG10:
       movdqu   xmm0, qword ptr [rsp+48H]
       movdqu   qword ptr [rsp+28H], xmm0
       movdqu   xmm0, qword ptr [rsp+58H]
       movdqu   qword ptr [rsp+38H], xmm0
G_M48484_IG11:
       lea      r8, bword ptr [rsp+28H]
       call     String:FormatHelper(ref,ref,struct):ref
       mov      r8, rax
       mov      rdx, rdi
       mov      rcx, rsi
       call     ArgumentOutOfRangeException:.ctor(ref,ref):this
       mov      rcx, rsi
       call     CORINFO_HELP_THROW
G_M48484_IG12:
       lea      rcx, [(reloc)]
       call     CORINFO_HELP_NEWSFAST
       mov      rsi, rax
       mov      ecx, 0x14E60
       call     CORINFO_HELP_STRCNS_CURRENT_MODULE
       mov      rcx, rax
       call     Environment:GetResourceString(ref):ref
       mov      rdx, rax
       mov      rcx, rsi
       call     InvalidOperationException:.ctor(ref):this
       mov      rcx, rsi
       call     CORINFO_HELP_THROW
       int3     
; Total bytes of code 541, prolog size 31 for method GC:RegisterForFullGCNotification(int,int)
; ============================================================
```
</dasm>

**Comment by mikedn** [comment]
Lolz, `RegisterForFullGCNotification` has more exception related code than actual code.

**Comment by AndyAyersMS** [comment]
Right -- for some reason that's not immediately obvious in the original example there end up being 4 structs instead of 3, so a bit more zeroing happens up in the prolog.

As far as implementing a fix: in general the inliner will likely have to get pretty far into importation so that the temporaries created by newobj of GC ref holding value types become apparent. If the inliner sees that and the call site is in a rare call block we can back out of the inline.

The size of the EH related code is a concern. Hot/cold splitting can help as the EH related code is moved to some remote part of the binary. There is some support for that about but it's not enabled in Core (yet). Also in some cases the volume of code can be cut down with aggressive tail merging, but that is expensive. Merging can also inhibit debuggability if identical code sequences with differing IL offsets are merged.

**Comment by VSadov** [comment]
@russellhadley @briansull  - Out of curiosity. For a language like C# that requires locals be definite assigned before use, zeroing of the locals would rarely be needed.

CIL spec does require us to put to localsinit on methods to make them "verifiable", however it permits the JIT to not zero-out variables that are definitely assigned before use, and that would be the case in nearly 100% cases when IL comes from C#

So I am wondering if it is possible to do at least some trivial/conservative definite analysis in the JIT and skip the zeroing out?

**Comment by briansull** [comment]
What we have here is a a 32-byte struct that contains one or GC pointers.

We must zero out the struct so that we can report the GC pointers.
Technically we only have to zero out the GC pointer fields with in the struct, not the entire struct.

We have to do this because we don't know when the struct is alive, since we don't do lifetime tracking for structs*. 

Since we don't know when the GC pointer inside the struct are alive we treat the struct as an untracked local variable and report its GC pointer as alive everyplace.  In order to do that we have to insure that these GC pointers contain **nulls** rather than uninitialized values.

 

 { * Exception for structs that are fully promoted (i.e. scalar replacement) }

**Comment by VSadov** [comment]
@briansull Thanks!!! I did not know we are not tracking lifetime for structs. That would indeed force zeroing out if they have GC pointers.

So I assume for structs with no refs and nonstructs we actually _can_ bypass zeroing out. Is that right?

**Comment by briansull** [comment]
Yes we can bypass the zero-ing for structs with no GC pointers (unless initlocals was requested for the method)

**Comment by hypersw** [comment]
@benaadams: which tools do you use to see traces like these? I guess those to be JIT-specific. 
> In my samples, for instance, I've used *DotTrace* sampling for the overall managed picture and *VTune* to dig into native code per-instruction sampling.

**Comment by benaadams** [comment]
@hypersw if you want to examine the asm the live jit generates I use this process https://github.com/dotnet/coreclr/issues/7556#issuecomment-252772585

Examining before/after effect and the what crossgen/ngen produces is slightly different and uses [jitutils](https://github.com/dotnet/jitutils); but I don't think you'd need to do that in this case.
