### ISSUE TITLE
System.runtime.MemoryFailPoint not usable on Xplat

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#7577]
Because of the estimates in the following lines, we get a huge upper limit which can not be used to determine the absence of virtual memory on the target machine. This leads us to never throw InsufficientMemoryException making the MemoryFailPoint  not useful on Xplat

https://github.com/dotnet/coreclr/blob/master/src/pal/src/misc/sysinfo.cpp#L175
https://github.com/dotnet/coreclr/blob/master/src/pal/src/misc/sysinfo.cpp#L301

cc @jkotas

**Comment by jkotas** [comment]
@Maoni0 Do you think it would make sense to move MemoryFailPoint logic into the GC as part of fixing this?

**Comment by Maoni0** [comment]
I don't think I wanna move something like this into the GC 'cause it's a fairly dubious implementation and aside from seg size it doesn't need to know anything else from the GC. I am not sure how many people are actually using this but this is clearly not robust (but could be sufficient from some usage scenarios). For platforms that do not offer virtual address info we can just #ifdef the part that checks for VA out in the implementation.... @ramarag, do you think you could do this?

**Comment by ramarag** [comment]
cc @janvorli for thoughts too

**Comment by janvorli** [comment]
@ramarag looking at the MemoryFailPoint.cs, I don't see it using the virtual memory limits that you've pointed out in the issue description. It uses availVirtual and availPageFile. We set the availVirtual in the PAL to the available physical memory and the availPageFile to zero. We can add getting the real page file information, it can be obtained easily using the `sysinfo` function.
As for the GetSystemInfo on Linux it should not set the lpMaximumApplicationAddress to -1 but rather to the 128TB we use as a limit in the other function.
Would that be enough to make it work?
