### ISSUE TITLE
Please provide a way to let the derived class have different static memory from base class

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#758]
Currently all derived classes share the same static memory with base class. But sometimes, we need difference static memory.
For example:
class A
{
static int a;
unique int b; // for example, use keyword "unique" to specify that if a class inherit from class A, then its static field "b" does not share the same memory with class A's field "b".
};
class B:A{};
B.a=0;B.b=10;
A.a=1;A.b=2; //now B.a=A.a=1, but B.b=10 not changed

**Comment by jkotas** [comment]
Again, language feature requests should go to the Roslyn repo.

There is also a lot of ambiguity in your proposal - I do not see how the compiler/runtime can figure out the right copy of the static to use in cases when the field is accessed outside context.
