### ISSUE TITLE
Unbalanced ICorProfilerCallback calls when using profiling api

### ISSUE THREAD

**Issue by tzehetner** [dotnet/coreclr#7599]
While adding .NET Core support to [NProfiler](https://www.nprofiler.com) (a .NET performance profiler) we discovered a bug in the profiling API.

We profiled a simple “Hello World” console app and got the following unbalanced sequence of ICorProfilerCallback calls:
1. AppDomainCreationStarted for AppDomain A
2. AppDomainCreationFinished for AppDomain A
3. AppDomainCreationStarted for AppDomain B
4. AppDomainCreationFinished for AppDomain B
5. AppDomainCreationStarted for AppDomain C
6. AppDomainCreationFinished for AppDomain C
7. Again AppDomainCreationFinished for AppDomain B (this is the unbalanced call, because we already got the finished-notification for AppDomain B before).

We already implemented a workaround, but I wanted to let you know about this issue.

**Comment by cmckinsey** [comment]
@lt72 

Is this x86 or x64?

**Comment by tzehetner** [comment]
x64 on Windows

**Comment by jkotas** [comment]
How are you creating the appdomains? Appdomains do not work well in CoreCLR.

**Comment by tzehetner** [comment]
We didn't create any AppDomains. The AppDomains are created by the clr.

This is the source code of the test app:

```
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
        Console.ReadKey();
    }
}
```

**Comment by sywhang** [comment]
Fixed with: https://github.com/dotnet/coreclr/pull/15691
