### ISSUE TITLE
Move mscorlib facade from CoreCLR to CoreFX

### ISSUE THREAD

**Issue by joperezr** [dotnet/coreclr#7607]
cc: @jkotas @weshaggard 

Today we version mscorlib and System.Private.CoreLib as netstandard1.0 which means that we use the same two dlls across different frameworks (i.e. netcoreapp1.0 and netcoreapp1.1). This started being an issue since PR #7578 caused the mscorlib facade to type forward some types to System.IO. The problem with that, is that in netcoreapp1.0 world, System.IO.dll implementation type-forwards System.IO.Stream to mscorlib.dll facade, which used to type-forward it System.Private.CoreLib.dll where the implementation lives, but that is not the case anymore, and it now type-forwards it back to System.IO causing a type not found.

```
Resolution of System.IO.Stream type
netcoreapp1.1: System.IO(v.4.2.0.0) -> System.Runtime(v.4.2.0.0) -> System.Private.CoreLib (type lives here)
netcoreapp1.0: System.IO(v.4.1.0.0) -> mscorlib -> System.IO(v.4.1.0)....
```

This causes:

```
Unhandled Exception: System.TypeLoadException: Could not load type 'System.IO.Stream' from assembly 'System.IO, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

This would get fixed if we version the mscorlib facade

**Comment by jkotas** [comment]
We should move building of mscorlib façade to corefx repo where it belongs. The current build of it in CoreCLR repo is barely holding together - I do not think it make sense to bug fix it in its current form.

**Comment by joperezr** [comment]
Well, isn't the facade strictly tied down to System.Private.CoreLib?

**Comment by weshaggard** [comment]
It is bound to S.P.CoreLib and other things and I agree it should move to corefx but before we can do that we need to figure out a packaging story for it and how we would ship it.

**Comment by jkotas** [comment]
Right now, it is tightly coupled with System.Private.CoreLib about as much as other ~40 corefx assemblies that build with `<TargetingPackReference Include="System.Private.CoreLib" />`.

The mscorlib façade should not reference System.Private.CoreLib at all. It should be forwarding to the other public surface (System.Runtime, etc.).

**Comment by weshaggard** [comment]
>The mscorlib façade should not reference System.Private.CoreLib at all. It should be forwarding to the other public surface (System.Runtime, etc.).

I don't know that we can do that because currently there are some things in that facade that forward internal things. @AlexGhiondea hit a number of breaks when enabling that for them.

**Comment by jkotas** [comment]
Right, that was before the netstandard20 work. Most of them should be taken care of by the netstandard20 work. And if there are some that are not, and are actually needed - they should be added as proper public APIs to System.Runtime.*

**Comment by jkotas** [comment]
Also, the true internal things are not going through the façade at all because of the tightly coupled corefx assemblies are building directly against System.Private.CoreLib now.

**Comment by weshaggard** [comment]
>Also, the true internal things are not going through the façade at all because of the tightly coupled corefx assemblies are building directly against System.Private.CoreLib now.

Fair. I think this might not be an issue any more because of that.

**Comment by joperezr** [comment]
>The mscorlib façade should not reference System.Private.CoreLib at all. It should be forwarding to the other public surface (System.Runtime, etc.).

If we want to do that then we should definitely have two versions of the facade, one that does the above for netstandard1.7, and then another one for netstandard1.6 where we type forward everything to System.Private.CoreLib, or else, previously built assemblies that type forward to this facade won't work.

**Comment by AlexGhiondea** [comment]
@RussKeldorph do you know if the tests have been updated to not use this facade anymore?

**Comment by RussKeldorph** [comment]
@AlexGhiondea I'm not aware of any such update, but that doesn't mean it didn't happen.

**Comment by weshaggard** [comment]
@AlexGhiondea I think the CI has been updated to consume the new CoreFx layouts which should be getting it the mscorlib facade we generate in corefx. It will become obvious if this doesn't work with the CI runs from @jkotas's PR https://github.com/dotnet/coreclr/pull/9278.
