### ISSUE TITLE
Missing i-ms-win-crt-runtime-l1-1-0.dll

### ISSUE THREAD

**Issue by schotime** [dotnet/coreclr#7614]
I tried to package a standalone self contained coreclr application and deploy it on windows 2012 standard, however I receive and error saying that i-ms-win-crt-runtime-l1-1-0.dll is missing when i try to run it?

Is there are reason why this isn't included in the publish?

**Comment by gkhanna79** [comment]
This is expected to be installed as part of pre-req installation. Please see https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites#net-core-dependencies.
