### ISSUE TITLE
arch linux RID

### ISSUE THREAD

**Issue by markschultz** [dotnet/coreclr#7624]
i'm building coreclr on arch linux via this [PKGBUILD](https://aur.archlinux.org/packages/dotnet-cli). when I run `dotnet --info` i get 

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58
 
Runtime Environment:
 OS Name:     linux
 OS Version:  
 OS Platform: Linux
 RID:         linux.-x64
```

shouldn't the RID be `linux-x64` not `linux.-x64`? with this RID I sometimes run into the following error when running `dotnet build` after `dotnet restore`

```
Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target run
times: 'linux.-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'linux.-x64' in the 'runtimes' section.
3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.
```

the runtimes section contains `linux-x64` and if I change that to `linux.-x64` then `dotnet restore` fails.
If the runtimes section is empty everything seems to run fine.

Is there some way to remove that extra '.' in the RID when i'm compiling coreclr?

**Comment by janvorli** [comment]
Can you check what the arch linux contains in the /etc/os-release? The RID should be the combination of the ID and VERSION_ID with dot in between. So maybe there is no VERSION_ID?

**Comment by markschultz** [comment]
```
NAME="Arch Linux"
ID="linux"
ID_LIKE="arch"
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

it was my understanding that the linux runtime didn't have a specific version.

**Comment by janvorli** [comment]
The RIDs on other linux distros are e.g. ubuntu.16.04-x64, fedora.24-x64, opensuse.13.2-x64, opensuse.42.1-x64, etc.

**Comment by janvorli** [comment]
content of that file on Ubuntu 14.04:
```
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by markschultz** [comment]
since arch linux is a rolling release, as far as i know there is no specific version, just release dates.

usually everything builds and runs just fine with the `linux.-x64` rid. its just when i'm building a project using the `linux-x64` runtime it doesn't match my runtime so no luck. i believe if i could remove that dot it would work.

**Comment by markschultz** [comment]
[here](https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json) you can see the general linux-x64 runtime has no version.
Am I wrong in assuming that if my RID was `linux-x64` instead of `linux.-x64` everything described above would work?

**Comment by mellinoe** [comment]
Unfortunately, Arch Linux is not an officially-supported distro, so we don't have correct handling for this rid. Indeed, the rid itself is not correct at all. It should be something like "arch-x64", not "linux-x64", which is a generic "parent rid" thatall Linux-family distros inherit from in the rid graph. Our rid detection logic currently uses the /etc/os-release file as mentioned above, but that file in Arch Linux has information in it that does not play well with the rest of our system.

On another note, the fact that there is no version number, and there is a "rolling release" paradigm also does not play well with our rid system. We will have to think more deeply about how that sort of thing is going to be supported.

In general, if you're on an unsupported distro, you are going to have a fairly rough time right now. You will be able to restore and build some portable libraries and portable application projects, without too much pain. But if you start getting into anything involving RID-specific references or "standalone" projects, then you will hit bigger issues, which may or may not be solvable without real distro support.

**Comment by markschultz** [comment]
I feared that would be the case. I guess I was just hoping there was a way to change the RID. As it is now, I've modified my os-release file to match the one posted above for ubuntu and that seems to be working fine.

thanks for the info, i'll consider this closed.
