### ISSUE TITLE
Jit: many callers of impNormStructType don't want the GC layout or number of GC fields

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#7625]
`impNormStructType` can be streamlined to avoid calling `getClassGClayout` in many cases. We can instead check the class flag `CORINFO_FLG_CONTAINS_GC_PTR`. This might save a bit of time since (especially for large value types) querying the GC layout can be slow.

**Comment by AndyAyersMS** [comment]
@CarolEidt while working on this I ran across something that puzzles me. Any idea why `impNormStructType` first checks SIMD size via
```
(originalSize >= minSIMDStructBytes()) && (originalSize <= maxSIMDStructBytes())
```
and then later checks size via
```
(originalSize <= getSIMDVectorRegisterByteLength()) && (originalSize >= TARGET_POINTER_SIZE)
```
The upper bounds seem to be equivalent but the lower ones may not be...

**Comment by CarolEidt** [comment]
I have no idea why those are different. Perhaps they were added at different times. As it happens, they are currently equivalent on x64, but won't be on x86 (the lower bound will still be 8 bytes even though the TARGET_POINTER_SIZE will be 4).

**Comment by AndyAyersMS** [comment]
In the reworking there will be just one check, so I'll use the `minSIMD ... maxSIMD` version.

**Comment by CarolEidt** [comment]
Sounds good.
