### ISSUE TITLE
test build once again has a zillion build warnings

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#7626]
My dotnet/coreclr builds of x86 debug & checked (haven't tried others recently) produced well over 6000 warnings like this:

```
D:\gh\coreclr3\Tools\packageresolve.targets(79,5): warning : Your project is not referencing the ".NETCoreApp,Version=v1.0" framework. Add a reference to ".NETCoreApp,Version=v1.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [D:\gh\coreclr3\tests\src\Regressions\common\ThreadCulture.csproj]
```

**Comment by BruceForstall** [comment]
#6022 related?

**Comment by RussKeldorph** [comment]
@dagood Since you fixed #6022, any idea what happened here and what it would take to fix?

**Comment by dagood** [comment]
Looked into it, remembered that things were being upgraded from 1.0 to 1.1 recently. The default in buildtools is 1.0, so there was a mismatch in the restore during build. (Actually, on that note, package restore probably shouldn't be happening during the build. Luckily `IsRestoreRequired` makes it fast anyway.)

**Comment by dagood** [comment]
Looking in the CI for #7937 I actually still see a ton of warnings: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_release_windows_nt_pri1_prtest/1424/consoleText. Reopening.

The problem looks like the right framework (1.1) just needs to be more uniformly applied (e.g. https://github.com/dotnet/coreclr/blob/a4e26c85b3de677df72c1beb94844e0e52243170/tests/src/JIT/config/minimal/project.json#L10), but I don't have time at the moment to look deeper into it and put another PR up.

**Comment by RussKeldorph** [comment]
@dagood Thanks for the help.  Looks like mostly JIT references remaining.
```
src\JIT\config\extra\project.json:21:    "netcoreapp1.0": {}
src\JIT\config\minimal\project.json:10:    "netcoreapp1.0": {}
src\JIT\config\threading\project.json:10:    "netcoreapp1.0": {}
src\JIT\config\threading+thread\project.json:12:    "netcoreapp1.0": {}
src\TestWrappersConfig\project.json:9:    "netcoreapp1.0": {
```
So I can finish it off.

@dotnet/jit-contrib FYI

**Comment by BruceForstall** [comment]
@RussKeldorph This issue can be closed; there are still warnings, but not "zillions".
