### ISSUE TITLE
Proposal to replace the algorithm used in Random Class.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/coreclr#7635]
According to [MSDN documentation](https://msdn.microsoft.com/en-us/library/system.random(v=vs.110).aspx?cs-save-lang=1&cs-lang=vb#Remarks), the `Random` class is using
> a modified version of Donald E. Knuth's subtractive random number generator algorithm.

This algorithm is somewhat obscure. I have found only [this paper](http://www.colostate.edu/~pburns/monte/rngreport.pdf) that can be said that refers to this algorithm.

Therefore, I propose a change of the default RNG in `Random` class to the [Permuted Cogruential Generator(PCG)](http://www.pcg-random.org/). According to its site, PCG is:
* [More difficult to predict](http://www.pcg-random.org/predictability.html#predictability-of-the-pcg-family)
* Smaller both in code size (`InternalSample` will be only five lines of code and `Random`'s constructor will be another five lines) 
and in memory usage (just 16 bytes in comparison with the 232 bytes the existing RNG uses)
* [More statistically random](http://www.pcg-random.org/statistical-tests.html#statistical-performance-of-the-pcg-family)

It can also provide some [other useful features](http://www.pcg-random.org/useful-features.html).
There is a more detailed comparison of PCG and other RNGs [here](http://www.pcg-random.org/other-rngs.html).

I submitted #7477 to apply these changes, but I was told to temporarily close it and to open an issue instead for further discussion.
The implementation is based on [this one](https://github.com/imneme/pcg-c-basic/blob/master/pcg_basic.c).
It has also added some constructors to `Random` class that allow it to be seeded with the longer `ulong` seeds PCG allows. It also implements multiple codebooks. The original constructors are retained, so I guess this isn't a breaking API change.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #12746](https://github.com/dotnet/corefx/issues/12746) via [**ZenHub**](https://www.zenhub.com/)

**Comment by danmosemsft** [comment]
We track issues in the managed code in the corefx repo even if the implementation actually resides in the coreclr repo. (I should have mentioned that)
