### ISSUE TITLE
Consider moving the new Span<T> out of "System" or renaming it

### ISSUE THREAD

**Issue by cwe1ss** [dotnet/coreclr#7636]
I really look forward to the new [Span](https://github.com/dotnet/coreclr/issues/5851) type, however I have concerns regarding naming:

`Span` is a very common word and it will probably already be used by many developers for a type of their own. Searching through github reveals that even Xamarin uses `Span` in their `Xamarin.Forms` namespace.

By adding your Span to mscorlib and the main `System` namespace, you will automatically expose this type to _almost every file in every .NET application_. Everyone who is using Xamarin.Forms or any other library with an existing `Span` type will now get ambiguity problems and will have to resolve them with `using Span=Xamarin.Forms.Span;`.

I think that your new Span will not be a type for the mainstream application developer - it will more likely be used by fewer library developers. Given that, I propose that you either move the type into a different namespace to minimize collisions or that you rename it - maybe to `MemorySpan`?!

**Comment by jamesqo** [comment]
> Everyone who is using Xamarin.Forms or any other library with an existing Span type will now get ambiguity problems and will have to resolve them with using Span=Xamarin.Forms.Span;.

The C# compiler will be able to determine the correct type based on whether/whether or not type arguments are being provided. For example:

```cs
class Span { }
class Span<T> { }

var span = new Span();
var span2 = new Span<int>();
```

[compiles with Roslyn](http://tryroslyn.azurewebsites.net/#b:features-tuples/f:>il/MYGwhgzhAEDKAOYB20De0C+AoUkYOQB4AVAPjUyx3CmgAUAnAewHMGwBbLVLaP6AG5MAlgBNoAWTDCkACgCUvfj36rBYBtAiIUAXmhIApgHc4OhQG4la9Zu3IATNH1HTBJIRkAXUpeuUMIA=). So this will only create ambiguity problems for existing generic `Span<T>`s which I'm guessing are not that common.

**Comment by cwe1ss** [comment]
Ok, this will make it much less of a problem! In that case it's more a question of confusion in the IntelliSense list, because everyone will have the new `Span<T>` in there. People might think that any existing `ISpan`, `Span`, ... might be related to the new `Span<T>`. 

For me, the main question now is whether or not the new `Span` will be such an important concept for enough users that it is understood well enough and worth being put in the global "System" namespace. If it should stay in the "System" namespace but is meant only for arrays/memory, it might help to have it prefixed - e.g. `ArraySpan` or `MemorySpan`, ...
If you keep the same name but put it in any other namespace, people would have to opt-in to it - it would therefore also remove any confusion with other "Span"s from other namespaces IMO.

I'm definitely biased because I'm working on a C# implementation of the [OpenTracing](http://opentracing.io) standard - a vendor-neutral tracing API that's based on [Google Dapper](http://research.google.com/pubs/pub36356.html). It uses the term "span" for one unit in a distributed trace. It's not yet a thing in .NET but it is becoming popular in other languages and it is now part of the cloud native foundation, together with Kubernetes and prometheus.io. 

Since I'm currently more or less the only user of that library, I probably can't claim the word "span" for myself :smile:.  It should just serve as an example that using the broad term "Span" in the global "System" namespace might cause confusion.

thanks for taking the time to think about this! It's definitely not the most important issue. :smile:

PS: I didn't know about https://tryroslyn.azurewebsites.net - thx for sharing this link!

**Comment by KrzysztofCwalina** [comment]
@cwe1ss thanks for pointing out this issue. At some point we should have an API review of the Span<T> and related APIs and we will surely discuss this issue.

**Comment by plioi** [comment]
I'm a little more concerned about the way there are essentially two names for this concept in the code. "Slice" and "Span" seem to be used interchangeably. Is one a subtype of the other, or is one a remnant of history?

**Comment by jkotas** [comment]
Tracked by https://github.com/dotnet/corefx/issues/16997
