### ISSUE TITLE
PCL+System.Type allow usage of operators (`==` & `!=`)

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/coreclr#764]
If the type `System.Type` supported the operators `=` and `<>`. We then could use the `Select Case` to do a matching over types.

For example [Portable\SymbolDisplay\ObjectDisplay\FormatPrimative](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/SymbolDisplay/ObjectDisplay.vb#L37) rewritten to use it.

``` vb
       Public Function FormatPrimitive(obj As Object, options As ObjectDisplayOptions) As String
            If obj Is Nothing Then Return NullLiteral

            Dim type = obj.GetType()
            If type.GetTypeInfo().IsEnum Then type = [Enum].GetUnderlyingType(type)

            Select Case type
                Case GetType(Integer)  : Return FormatLiteral(DirectCast(obj, Integer), options)
                Case GetType(String)   : Return FormatLiteral(DirectCast(obj, String), options)
                Case GetType(Boolean)  : Return FormatLiteral(DirectCast(obj, Boolean))
                Case GetType(Char)     : Return FormatLiteral(DirectCast(obj, Char), options)
                Case GetType(Byte)     : Return FormatLiteral(DirectCast(obj, Byte), options)
                Case GetType(Short)    : Return FormatLiteral(DirectCast(obj, Short), options)
                Case GetType(Long)     : Return FormatLiteral(DirectCast(obj, Long), options)
                Case GetType(Double)   : Return FormatLiteral(DirectCast(obj, Double), options)
                Case GetType(ULong)    : Return FormatLiteral(DirectCast(obj, ULong), options)
                Case GetType(UInteger) : Return FormatLiteral(DirectCast(obj, UInteger), options)
                Case GetType(UShort)   : Return FormatLiteral(DirectCast(obj, UShort), options)
                Case GetType(SByte)    : Return FormatLiteral(DirectCast(obj, SByte), options)
                Case GetType(Single)   : Return FormatLiteral(DirectCast(obj, Single), options)
                Case GetType(Decimal)  : Return FormatLiteral(DirectCast(obj, Decimal), options)
                Case GetType(Date)     : Return FormatLiteral(DirectCast(obj, Date))
            End Select

            Return Nothing
        End Function
```

If I try to use as it as the way I described this is following error.

> BC30452   Operator '=' is not defined for types 'Type' and 'Type'.    

[Roslyn Post](https://github.com/dotnet/roslyn/issues/2149)

_Edit_ 

This is a PCL code.

**Comment by Maxwe11** [comment]
For now `TypeCode` could be used but it limited with predefined set of types

**Comment by AdamSpeight2008** [comment]
@Maxwe11 The pattern I described above does work, just not for PCL.

**Comment by MattWhilden** [comment]
Ugh. Understandably frustrating. Unfortunately, I think think this is more properly titled "Add operator overloads for == and != to Type in PCL" but I may have misunderstood the issue. If that's the case, it may not actually be fixable... but I'm not the expert!

@weshaggard @davkean @dsplaisted What's the right path forward here? Presumably we can't change the surface area for PCL?

**Comment by davkean** [comment]
(Remember, PCL just reflects the underlying platforms, so if something is missing from PCL it's because it's from one of the platforms)

@nguerrera did some investigation around this, and we weren't happy with the semantics of the equality operations. Nick can provide more details.

**Comment by joshfree** [comment]
@nguerrera can you follow up please?

**Comment by jkotas** [comment]
Operators == and != were added back to System.Type in .NET Core as part of .NET Standard 2.0 work.
