### ISSUE TITLE
CordbProcess::DispatchUnmanagedInBandEvent() addrefs a thread twice but only releases it once

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/coreclr#7653]
`CordbProcess::DispatchUnmanagedInBandEvent()` goes like this:

```
    // Get the thread for this event
    pUnmanagedThread = pUnmanagedEvent->m_owner;

    // SOMETHING, then

    // Make sure we keep the thread alive while we're playing with it.
    pUnmanagedThread->InternalAddRef();

   // THEN later just addref it again without any comments

    pUnmanagedThread->InternalAddRef();

    Unlock();

    // SOMETHING

    Lock();

    // SOMETHING, then finally release the thing once

    // Release our reference to the unmanaged thread that we dispatched
    if (pUnmanagedThread)
    {
        // This event should have been continued long ago...
        _ASSERTE(!pUnmanagedThread->IBEvent()->IsEventWaitingForContinue());
        pUnmanagedThread->InternalRelease();
        pUnmanagedThread = NULL;
    }
```

It looks like it is addrefed twice but released twice. Perhaps that's right but this should be explained.

**Comment by gkhanna79** [comment]
CC @lt72 @noahfalk @mikem8361

**Comment by noahfalk** [comment]
The AddRef that you interpreted as being uncommented is part of the operation above it:

>        // Add/Remove a reference which is scoped to the time that m_lastDispatchedIBEvent
>        // is set to pUnmanagedEvent (it is an interior pointer)
>        // see DevDiv issue 818301 for more details
>        if(m_lastDispatchedIBEvent != NULL)
>        {
>            m_lastDispatchedIBEvent->m_owner->InternalRelease();
>            m_lastDispatchedIBEvent = NULL;
>        }
>        pUnmanagedThread->InternalAddRef();
>        m_lastDispatchedIBEvent = pUnmanagedEvent;


The invariant that comment is talking about is that whenever m_lastDispatchedIBEvent != NULL then there should be a +1 ref count on m_lastDispatchedIBEvent->m_owner.

If you look up in the function you will see that pUnmanagedThread == pUnmanagedEvent->m_owner. Thus the last two lines are ensuring that we +1 ref count the owner while transitioning m_lastDispatchedIBEvent from NULL to non-NULL. The lines above it were doing -1 ref count on the old event owner in the non-NULL -> NULL transition.

**Comment by mikem8361** [comment]
So we can close this issue?  Was there a specific app/test/scenario that you hit an CorProcess reference leak?

**Comment by Dmitry-Me** [comment]
Can this code clarity be improved somehow?

**Comment by mikem8361** [comment]
If there is no actual problem, I rather not make any changes.

**Comment by noahfalk** [comment]
@Dmitry-Me we'd be glad to review a PR if you want to submit one

**Comment by Dmitry-Me** [comment]
@noahfalk @mikem8361 How about doing this instead?

    if(m_lastDispatchedIBEvent != NULL)
        {
            m_lastDispatchedIBEvent->m_owner->InternalRelease();
            m_lastDispatchedIBEvent = NULL;
        }
        m_lastDispatchedIBEvent = pUnmanagedEvent;
        m_lastDispatchedIBEvent->m_owner->InternalAddRef();

**Comment by noahfalk** [comment]
Switching the order of the memory writes in the last two lines may introduce a race condition. I don't think we'd want to spend the time, energy, and risk proving that it didn't. Consider what it would look like if two versions of that code ran on seperate threads and interleaved like this:

> Thread 1: if(m_lastDispatchedIBEvent != NULL)
> Thread 1:    {
> Thread 1:        m_lastDispatchedIBEvent->m_owner->InternalRelease();
> Thread 1:       m_lastDispatchedIBEvent = NULL;
> Thread 1:   }
> Thread 1:    m_lastDispatchedIBEvent = pUnmanagedEvent;
> Thread 2: if(m_lastDispatchedIBEvent != NULL)
> Thread 2:    {
> Thread 2:        m_lastDispatchedIBEvent->m_owner->InternalRelease();
> Thread 1:   m_lastDispatchedIBEvent->m_owner->InternalAddRef();

When thread 2 calls InternalRelease the ref count on the thread could drop to 0 causing it be deleted.

How about a comment change or something that doesn't reorder the operations?

**Comment by lt72** [comment]
Please re-open the issue if you would like to submit a PR for it.
