### ISSUE TITLE
Memory leak in mscordbi detected through AppVerifier

### ISSUE THREAD

**Issue by lt72** [dotnet/coreclr#7660]
Steps to reproduce:
1. Install VS with the managed desktop workload.
2. Create a default C# console application.
3. Add something you can break in to -

while (true) {
  int x = 0;
   x += 1;
}
1. Close VS and relaunch it with AppVerifier "Basics" all enabled and a debugger attached.
2. Set a breakpoint in the code added.
3. F5 to start debugging.
4. Click stop debugging.

Expected: nothing from app verifier.
Actual: AppVerifier detects a leak.

**Comment by mikem8361** [comment]
@It72 is there anyway you could have the AppVerifier output about this leak?

**Comment by lt72** [comment]
@mikem8361: You will find the info at the corresponding TFS item https://devdiv.visualstudio.com/DevDiv/_workitems?id=278149&_a=edit

**Comment by mikem8361** [comment]
This is a desktop clr issue.
