### ISSUE TITLE
dotnet restore times out while building CoreCLR on x64 Ubuntu 16.04

### ISSUE THREAD

**Issue by hadibrais** [dotnet/coreclr#7674]
## Steps to reproduce

While building CoreCLR using `./build`, the following step is successfully reached:

`Running: /coreclr/Tools/dotnetcli/dotnet restore "/coreclr/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00809-01/lib/tool-runtime/project.json" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://api.nuget.org/v3/index.json`

However, the packages are not being successfully restored. I'm getting the following output for every package that needs to be restored:

```
log  : Restoring packages for /coreclr/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00809-01/lib/tool-runtime/project.json...
log  : Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/msbuild/index.json'.
log  : The download of 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/msbuild/index.json' timed out because no data was received for 60000ms.
log  :   Exception of type 'System.TimeoutException' was thrown.
```
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

(Even though this shows I've got CLI 1.0.0-preview2-003131, the CLI version that build script is trying to download and install is 1.0.0-preview3-003223. That's strange.)

Not sure if this would be a problem, but I'm behind a web proxy. However, the env variable `http_proxy` is set correctly (`wget` is working perfectly).
## Additional Information

I can successfully restore packages for the hello world project:

```
dotnet new
dotnet restore
```

**Comment by mellinoe** [comment]
Are you able to download from that location manually using curl? Could you try running the restore command manually and adding `--disable-parallel` to the arguments? We have seen problems with concurrent restores in some cases (resulting in download timeouts).

**Comment by hadibrais** [comment]
> Are you able to download from that location manually using curl?

Which location?

> Could you try running the restore command manually and adding --disable-parallel to the arguments?

Yep. It doesn't work. Here is sample output when using this switch:

```
log  : Restoring packages for /coreclr/src/.nuget/init/project.json...
log  : Installing Microsoft.NETCore.Platforms 1.0.2-beta-24224-02.
log  : Writing lock file to disk. Path: /coreclr/src/.nuget/init/project.lock.json
log  : /coreclr/src/.nuget/init/project.json
log  : Restore completed in 3527ms.
log  : Restoring packages for /coreclr/src/ToolBox/SOS/NETCore/project.json...
log  : Installing System.Reflection.Metadata 1.4.1-beta-24417-02.
log  : Writing lock file to disk. Path: /coreclr/src/ToolBox/SOS/NETCore/project.lock.json
log  : /coreclr/src/ToolBox/SOS/NETCore/project.json
log  : Restore completed in 2292ms.
log  : Restoring packages for /coreclr/src/mscorlib/facade/project.json...
log  : Lock file has not changed. Skipping lock file write. Path: /coreclr/src/mscorlib/facade/project.lock.json
log  : /coreclr/src/mscorlib/facade/project.json
log  : Restore completed in 46ms.
log  : Restoring packages for /coreclr/Tools/1.0.26-prerelease-00809-01/project.json...
error: Unable to resolve 'Microsoft.DotNet.BuildTools (>= 1.0.26-prerelease-00809-01)' for 'DNXCore,Version=v5.0'.
log  : Lock file has not changed. Skipping lock file write. Path: /coreclr/Tools/1.0.26-prerelease-00809-01/project.lock.json
log  : /coreclr/Tools/1.0.26-prerelease-00809-01/project.json
log  : Restore failed in 1036ms.
log  : Restoring packages for /coreclr/Tools/tool-runtime/project.json...
log  : Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.build.targets/index.json'.
log  : The HTTP request to 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.build.targets/index.json' has timed out after 100000ms.
```
Notice that there seems to be two different errors: `Unable to resolve 'Microsoft.DotNet.BuildTools...` and `The HTTP request to...has timed out after 100000ms`.

**Comment by janvorli** [comment]
@hadibrais could you also give us the output of the following command?
`curl --version`
We recently had a similar problem on Fedora 24 where the curl library was using nss for https traffic.

**Comment by hadibrais** [comment]
@janvorli 

```
$ curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```

**Comment by janvorli** [comment]
@hadibrais thank you. So this one is not using NSS, but rather GnuTLS. I have just verified that I have exactly the same curl version in my Ubuntu 16.04 docker container and the restore works fine, so it seems the problem is likely not due to the libcurl.
Can you also tell me what it the hardware configuration of your machine? I am interested in how many processor cores and how much memory you have.

**Comment by hadibrais** [comment]
@janvorli I have 16 GB of main memory and 8 logical cores. If you like, I can enable you to remotely access my machine using TeamViewer or whatever.

**Comment by janvorli** [comment]
@hadibrais I was just wondering if you could have something low spec or a VM with a single core or something like that. So this is obviously not the case.
I haven't noticed before that you've mentioned you are behind a web proxy. Let me try to use a proxy on my ubuntu to see if it is related.

**Comment by janvorli** [comment]
@hadibrais I've tried to set a http proxy - using one that I have installed on my other machine - and the restore has succeeded. I wonder then if it can be related to the specific proxy you are using.

**Comment by hadibrais** [comment]
I don't think the proxy is the culprit because this
```
dotnet new
dotnet restore 
```
works.

I have Windows 10 running in a VMware VM on the same physical machine. I'll check if it builds successfully there.

**Comment by janvorli** [comment]
One more thing to try - could you check if curl is able to get the file that was reported as timing out in your list?
`curl -O https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.build.targets/index.json`

**Comment by hadibrais** [comment]
```
$ curl -O https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.build.targets/index.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--    100   215  100   215    0     0    171      0  0:00:01  0:00:01 --:--:--   171
```

**Comment by janvorli** [comment]
Hmm, so it looks ok.
What happens if you delete the Tools and packages folder and try to run the init-tools.sh? Is it always the same or do the failures differ?

**Comment by hadibrais** [comment]
I just built it on Windows, it worked perfectly (except for the warnings emitted while building the tests). Running `init-tools.sh` produces the same errors. I'm not able to figure it out and ran out of ideas on how to pinpoint the cause.

**Comment by janvorli** [comment]
@hadibrais would you be willing to create a docker container with Ubuntu 14.04 and try to do it inside of it? I would like to figure out whether it is just Ubuntu 16.04 issue because of some bad interaction between our HTTP managed code, the libcurl and the GnuTLS or if it behaves the same with OpenSSL based libcurl that's on Ubuntu 14.04.

**Comment by hadibrais** [comment]
How to do that exactly? I never used Docker before. I just installed it on my Ubuntu 16.04. What's next?

**Comment by janvorli** [comment]
Run
`docker run -it --name ubuntu1404 ubuntu:14.04 /bin/bash`
That will download a bunch of stuff and then get you right to ubuntu14.04 shell.
Now you install all the dependencies:
```
apt-get update
apt-get install wget
echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main" | sudo tee /etc/apt/sources.list.d/llvm.list
wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
apt-get update
apt-get install cmake llvm-3.5 clang-3.5 lldb-3.6 lldb-3.6-dev libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev git
```
And now you can fetch the coreclr repo and run the build
```
mkdir /root/git
cd /root/git
git clone https://github.com/dotnet/coreclr.git
cd coreclr
./build.sh
```
You can now exit the shell using `exit`. If you don't want to keep the container with all the stuff, just do `docker rm ubuntu1404`
If you want to keep it for later with all the installed packages and coreclr stuff, do
`docker commit ubuntu1404 ubuntu1404`
Followed by:
`docker rm ubuntu1404`
You can enter the shell again using
`docker run -it --name ubuntu1404 ubuntu1404 /bin/bash`

**Comment by hadibrais** [comment]
Got the same errors. What can we conclude from this?

I appreciate your help so far.

**Comment by janvorli** [comment]
It seems that our HTTP managed code combined with libcurl has problems with your http proxy for some reason. Maybe the proxy does something unexpected to the HTTP headers or something like that. Do you know what proxy are you using?

**Comment by hadibrais** [comment]
The proxy server we are using is called [Squid](http://www.squid-cache.org/). Not sure which we version is currently being used.

I built the repo successfully on Windows. Aren't you using curl there too?

**Comment by janvorli** [comment]
No, the Windows version doesn't use curl. It is based on Windows APIs.
And trying to download something using curl is not the same thing as using the libcurl from our HTTP code. As you could see from your logs, some restoration has worked before the failure, so it partially works, but there is some problem that hits us at some point.

**Comment by hadibrais** [comment]
I see. Is there a temporary workaround for this? Can I avoid using libcurl?

**Comment by janvorli** [comment]
No, on Unix, there is no other way. Let me try installing the Squid to see if I could repro the issue with it.

**Comment by janvorli** [comment]
@hadibrais do you also happen to know the version of Squid you are using? I want to make sure I am trying the same thing.

**Comment by janvorli** [comment]
Oh, I can see you already said you don't know the version.

**Comment by janvorli** [comment]
@hadibrais I have tried to install squid, but the complexity of setting it up for https traffic and the fact that all the different options can theoretically have an effect on our stuff scared me off. 
So I was thinking about possible ways that we have and I have two more ideas, which might not be possible in your environment though.
First, if I could use your instance of the squid proxy from my machine remotely, it would allow me to debug it.
Second, if the first one is not possible, then if you could create an account for me on your linux machine that I can access using ssh, it would also allow me to debug it.

**Comment by hadibrais** [comment]
@janvorli I tried to build the repo on another physical machine that has Ubuntu 14.04 and is also behind the same proxy. I got the same errors. This increases the probability that the theory you've proposed is indeed what's happening -- the interaction between libcurl and our proxy is causing problems.

I can get your access to my machine so that you can access our proxy and debug the issue further. How can I send the instructions to access my machine remotely using ssh?

Also, I learned that version of the Squid we are using is 3.1.19.

**Comment by janvorli** [comment]
@hadibrais thank you for the update. As for the instructions, you can send them to my microsoft email - janvorli at microsoft dot com.

**Comment by hadibrais** [comment]
I was able to get Internet access on the same machine without going through the web proxy. This enabled me to successfully build the code. Yay! I think we can conclude from this that the proxy is indeed the culprit for some reason. Thanks for your help. Should I close the issue?
