### ISSUE TITLE
[Linux] [GDB-JIT] breakpoint set command doesn't work

### ISSUE THREAD

**Issue by lucenticus** [dotnet/coreclr#7687]
Setting breakpoint using GDB JIT interface doesn't work with latest CoreCLR. The main issue that SymbolReader failed with incorrect dll dependencies, but it doesn't tell any error messages about this issue. @mikem8361, do we really need empty `catch` blocks in SymbolReader? Probably, we should print some error message?
I comment out empty `catch` blocks and I found that SOS.NETCore.dll generates exception: 

```
(lldb) pe
Exception object: 00007fff60015068
Exception type:   System.MissingMethodException
Message:          Method not found: 'Void System.Reflection.PortableExecutable.PEReader..ctor(System.IO.Stream, System.Reflection.PortableExecutable.PEStreamOptions)'.
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    00007FFFFFFFB1C0 0000000000000000 SOS.NETCore.dll!SOS.SymbolReader.TryOpenReaderFromAssembly(System.String, Boolean, System.IO.Stream)+0x1
    00007FFFFFFFB1C0 00007FFF7D4C1958 SOS.NETCore.dll!SOS.SymbolReader.GetReader(System.String, Boolean, System.IO.Stream, System.IO.Stream)+0x68
    00007FFFFFFFB220 00007FFF7D4C13D6 SOS.NETCore.dll!SOS.SymbolReader.GetDebugInfoForMethod(System.String, Int32, System.Collections.Generic.List`1<DebugInfo> ByRef)+0x76
    00007FFFFFFFB4B0 00007FFF7D4BDE22 SOS.NETCore.dll!SOS.SymbolReader.GetInfoForMethod(System.String, Int32, MethodDebugInfo ByRef)+0x72

StackTraceString: <none>
HResult: 80131513

```

CC: @Dmitri-Botcharnikov @chunseoklee

**Comment by mikem8361** [comment]
Yes we do need the catch blocks even though they do hide useful diagnostic info.  The reason is to catch version these kind of version mismatches.  If System.Reflection.Metadata doesn't match the one SOS.NETCore requires like this issue demonstrates, the resulting exception terminates your LLDB/SOS session.  Calling a function that references a missing function or type can result in this kind of exception at the call site.

**Comment by Dmitri-Botcharnikov** [comment]
Can we enable exception propagation at least in debug version of SOS.NETCore? Or maybe there is  some log facility to print out exception?
