### ISSUE TITLE
Provide a set of performance tests over the new single-precision math APIs

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#7691]
PR #5492 implemented dotnet/corefx#1151, by providing scalar single-precision floating-point support for many of the trigonometric, logarithmic, and other common mathematical functions.

However, there is still the additional work that needs to be done to provide a full set performance tests over the new single-precision math APIs.

This work is partially blocked on dotnet/corefx#12183 being merged so that a proper NuGet package is available with the appropriate contract assembly.

**Comment by tannergooding** [comment]
I am self-assigning these for the time being and am going to work on getting these completed.

**Comment by tannergooding** [comment]
This will be resolved with https://github.com/dotnet/coreclr/pull/9354, once that is unblocked (the perf tests do not currently support projects that target netcoreapp).

**Comment by gkhanna79** [comment]
CC @brianrob
