### ISSUE TITLE
Use C# 6 auto-implemented readonly properties in Tuple

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#7710]
Seems like since all of the backing fields of Tuple's properties are read-only, they could just be converted to auto-implemented get properties. Seems like it would remove a significant amount of code/enhance readability of the file.

**Comment by jkotas** [comment]
Tools depend on the exact names of these fields (yes, it is not right ... but they do). We have tried to rename these fields in corert (change the prefix from `m_` to just `_`) but rollback the change. It was not worth the pain to push it through the system.

**Comment by jamesqo** [comment]
@jkotas Rather unfortunate... I guess I'll close this then.
