### ISSUE TITLE
Build CoreCLR tests against System.Private.Corelib instead of mscorlib.dll

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#7711]

**Comment by jkotas** [comment]
Note that most of the tests that build against mscorlib should be able to build against regular contracts with netstandard20 work. The number of missing types and methods should be pretty minimal.

**Comment by karelz** [comment]
Do we need it for 2.0?

**Comment by jkotas** [comment]
This is done. I have submitted https://github.com/dotnet/coreclr/pull/10250 to cleanup left overs.

**Comment by karelz** [comment]
Thanks @jkotas, assigned to you to reflect the status.
