### ISSUE TITLE
Please trigger an event after GC every time. 

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#772]
Sometimes we want to do someting after GC, but we don't know when GC finish.

**Comment by Maoni0** [comment]
Various options available - depending on what you are doing. Let us know if none of these work for you.

[ICorProfilerCallback2::GarbageCollectionFinished](https://msdn.microsoft.com/en-us/library/ms230271(v=vs.110).aspx)
[GC End ETW](https://msdn.microsoft.com/en-us/library/ff356162(v=vs.110).aspx#gcend_v1_event)
[GC.RegisterForFullGCNotification](https://msdn.microsoft.com/en-us/library/system.gc.registerforfullgcnotification(v=vs.110).aspx)

**Comment by ericnewton76** [comment]
Could you possibly elaborate why you'd need to know when GC has finished?

**Comment by ygc369** [comment]
@ericnewton76 
For example, I use weak reference to maintain a cache of objects. When GC has finished, I need to check the cache and reorder some of the objects in the cache.

**Comment by ygc369** [comment]
any progress?

**Comment by ayende** [comment]
This is how you can do this:

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/Common/PinnableBufferCache.cs#L481

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
