### ISSUE TITLE
CultureInfo constructor allocates a lot

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#7744]
This test program:

```csharp
using System;
using System.Runtime.CompilerServices;
using System.Globalization;

namespace Program 
{
    public class Thing 
    {
        public static void Main(string[] args) 
        {
            Console.WriteLine("Beginning test");
            for (int i = 0; i < 10000; i++) {
                DoIt();
            }
            Console.WriteLine("Test complete");
        }

        [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization)]
        public static bool DoIt() 
        {
            DateTime result;
            return DateTime.TryParse("4/21 5am", new CultureInfo("en-US"), DateTimeStyles.None, out result);
        }
    }
}
```

allocates on average 71 kilobytes of strings and string arrays every iteration, for a total of 710 megabytes over the course of this program. It also runs for 7.5 seconds. The overwhelming majority of these allocations are coming from [this fcall](https://github.com/dotnet/coreclr/blob/master/src/classlibnative/nls/calendardata.cpp#L470) which populates a managed `CalendarData` object, which occurs every time the constructor to `CalendarData` is invoked (the only place: [here](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/corefx/System/Globalization/CultureData.cs)). 

To experiment, I naively cached instances of `CalendarData` and, with the cache, this same program runs with on average 7.9 kilobytes per iteration for a total of 79 megabytes over the course of the program, while running for only 691 milliseconds. I am not sure if it's safe to cache CalendarDatas, but if so, we would get a nice allocation profile improvement and performance boost.

This was found by using the new `GC.GetAllocatedBytesForCurrentThread` API to measure the allocation profile of `System.Runtime` CoreFX tests.

cc @Maoni0 @sergiy-k @adityamandaleeka

**Comment by Maoni0** [comment]
good find! 

71k 😲

**Comment by stephentoub** [comment]
Is it really TryParse?  Presumably if you move the ```new CultureInfo("en-US")``` call to outside the loop, the costs decrease significantly?

**Comment by swgillespie** [comment]
@stephentoub 

You're right, it does appear to be the culture info. Is it a common scenario to create new culture infos in this manner?

**Comment by stephentoub** [comment]
> Is it a common scenario to create new culture infos in this manner?

I don't think it's particularly common, but @tarekgh or @ellismg would know.  Regardless, if there are easy ways to make it cheaper, it'd be a good thing to do, regardless... just might change the priority level of investigating it :smile:

**Comment by tarekgh** [comment]
the best practice here is to use CultureInfo.GetCultureInfo() which uses the cached cultures and shouldn't allocate any more strings. we have GetCultureInfo specifically for such scenarios. new CultureInfo() creates read/write objects and try to read the underlying system data every time as the settings can change. 

please try GetCultureInfo and let's know if you still see the issue.

**Comment by tarekgh** [comment]
https://msdn.microsoft.com/en-us/library/yck8b540(v=vs.110).aspx

```
The GetCultureInfo method retrieves a cached, read-only CultureInfo object. It offers better performance than a corresponding call to the CultureInfo.CultureInfo(String) constructor.
```

I am going to close this issue but feel free to respond back or re-open if you have any follow up questions. thanks for bringing this issue.
