### ISSUE TITLE
Inliner: support inlining method with pinned locals

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#7774]
Quite a few people have been surprised to see that methods with pinned locals (`fixed` in C#) can't be inlined. We should support inlining such methods where feasible.

In C# a `fixed` statement is used to prevent managed objects from being relocated by GC, so that raw pointer math and/or GC-unaware code can be used to access the objects. The `fixed` statement block is conceptually enclosed in a `try/finally` block to ensure that no matter how control leaves the scope of the `fixed`, the pinned local variables are unpinned. In our implementation the JIT treats pinned locals as untracked GC lifetimes. Hence unpinning requires that the pinned locals be explicitly nulled out. But [in many cases](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_FixedStatement.cs#L49-L54) -- in particular when the call site itself is not in a `try/catch` -- the C# compiler can prove that the unpinning code is unobservable or unreachable and so the `try/finally` and possibly the unpinning code can be omitted.

This "fixed optimization" done by the C# compiler is both good news and bad news.

Good news: it gets us past a deep-seated limitation in the JIT about inlining methods with EH. If the C# compiler always used `try/finally` we'd need to solve a much bigger problem to inline any method with pinning.

Bad news: the JIT must now recreate the unpinning logic after inlining, or risk extending the scope of the pinning. To handle the full set of cases the JIT must be prepared to re-introduce the missing `try/finally` around the body of the inlined code.

The proposal here is to support inlining of methods with pinned locals in the subset of cases where the C# compiler has omitted the `try/finally` and the JIT determines that likewise no `try/finally` need be introduced. The JIT will still need to synthesize and add unpinning code.

**Comment by pentp** [comment]
Is there a reason that pinned locals must be untracked? Deducing liveness info from unpinning code would  remove the `try/finally` blocks, (synthesized) unpinning code and initialization code.

**Comment by AndyAyersMS** [comment]
The immediate reason that pinned locals are untracked is that the GC info reporting requires it to be this way. See for instance [here](https://github.com/dotnet/coreclr/blob/ffeef85a626d7344fd3e2031f749c356db0628d3/src/inc/gcinfo.h#L22-L29) or [here](https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/vm/eetwain.cpp#L4533-L4589) where the flag indicating that a GC reference is pinned is only relevant for untracked locals; that flag bit is repurposed for tracked locals to indicate the reference is to `this`.

One could imagine alternatives, but it's important to keep the GC info compact.

**Comment by pentp** [comment]
After looking through code using `this_OFFSET_FLAG` it looks like `this` and `byref` can't be set at the same time. If the flags were instead treated as a 2-bit enum (`0`, `byref`, `this`, `pinned`) it would be possible to encode pinned & tracked locals? It would also allow encoding `this` for untracked locals.
