### ISSUE TITLE
Add some tests for mscorlib

### ISSUE THREAD

**Issue by Alexx999** [dotnet/coreclr#78]
As for now there is no tests for mscorlib - that pretty much says it.

**Comment by mikedn** [comment]
I think that the tests you're looking for are in the corefx repository, see this for example: https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/Enum.cs

**Comment by AlexGhiondea** [comment]
We are still working on the test infrastructure for mscorlib.

Our plan is to have the majority of tests defined in the CoreFx repo (factored based on contracts).

I am working on setting up the right infrastructure to easily allow changes to mscorlib to be tested.

We are going to have mscorlib tests in the CoreCLR repo as well -- a very simple one is here https://github.com/dotnet/coreclr/blob/master/tests/src/managed/Compilation/Compilation.cs

**Comment by Alexx999** [comment]
Oh, I haven't updated my repo a while - missed that one. Still, I don't see any straightforward way to run that tests right now...

**Comment by AlexGhiondea** [comment]
Yes, there is currently no good way to do that.

We are working on it.

**Comment by AlexGhiondea** [comment]
You can now install the local CoreCLR package into the CoreFx repo and run CoreFx tests on top of them.

More information here: https://github.com/dotnet/coreclr/wiki/Testing-across-repos
