### ISSUE TITLE
Query real swap file size and potential VA space on the target System

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#7807]
This functionality will improve the perf for the MemoryFailPoint feature.
Follow up on https://github.com/dotnet/coreclr/pull/7751

This feature is needed on xplat

**Comment by ramarag** [comment]
enable https://github.com/dotnet/corefx/pull/13399/commits/755ce2f72caee5a29b29cd150cb30b08514482b6#diff-ab7a4b1b3e267c2adfbe272048b78932R30 on Xplat, once this issue is fixed

**Comment by janvorli** [comment]
Fixed by #10700. @ramarag, is seems you can enable the checks that were disabled in #7945 for xplat now.
