### ISSUE TITLE
Linux build error: call to deleted constructor of 'PAL_SEHException'

### ISSUE THREAD

**Issue by MrDetonia** [dotnet/coreclr#7822]
Build output:

```
[  9%] Building CXX object src/vm/wks/CMakeFiles/cee_wks.dir/__/exceptionhandling.cpp.o
[  9%] Building CXX object src/vm/wks/CMakeFiles/cee_wks.dir/__/gcinfodecoder.cpp.o
[  9%] Building CXX object src/vm/wks/CMakeFiles/cee_wks.dir/__/jitinterfacegen.cpp.o
[  9%] Building CXX object src/vm/wks/CMakeFiles/cee_wks.dir/__/amd64/unixstubs.cpp.o
[  9%] Building CXX object src/vm/wks/CMakeFiles/cee_wks.dir/__/amd64/cgenamd64.cpp.o
/home/mrdetonia/git/dotnet/coreclr/src/vm/exceptionhandling.cpp:4733:11: error: call to deleted constructor of 'PAL_SEHException'
    throw ex;
          ^~
/home/mrdetonia/git/dotnet/coreclr/src/pal/inc/pal.h:6530:5: note: 'PAL_SEHException' has been explicitly marked deleted here
    PAL_SEHException(const PAL_SEHException& ex) = delete;
    ^
1 error generated.
make[2]: *** [src/vm/wks/CMakeFiles/cee_wks.dir/build.make:4719: src/vm/wks/CMakeFiles/cee_wks.dir/__/exceptionhandling.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:65021: src/vm/wks/CMakeFiles/cee_wks.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
Failed to build coreclr components.
```

System information (Void GNU/Linux x86_64):

```
iapetus# uname -a
Linux iapetus 4.8.4_1 #1 SMP PREEMPT Sat Oct 22 18:37:10 UTC 2016 x86_64 GNU/Linux

iapetus# g++ --version
g++ (GCC) 4.9.4

iapetus# cmake --version
cmake version 3.6.2
```

Let me know if anything else is useful.

I'm afraid I'm not at all familiar with this codebase, and had to look up what a deleted constructor is, so not too much help beyond this.

---

_EDIT_: As I see it, `PAL_SEHException` objects are non-copyable, and the `throw ex;` tries to make a copy?

**Comment by choikwa** [comment]
http://stackoverflow.com/questions/16432959/exception-and-copy-constructor-c

This seems to suggest that copy ctor must be accessible even if copy/move can be elided.

**Comment by swgillespie** [comment]
Seems like clang should reject this program too for the same reason...

**Comment by ubsan** [comment]
I think clang calls the move constructor?

**Comment by janvorli** [comment]
The build actually uses clang, not g++. I assume it is a clang newer than 3.8, since the build with clang <= 3.8 is well tested.
@MrDetonia can you please try to run `clang --version`?
Anywats, this is a bug, there should be `throw std::move(ex);` instead. I guess the older clang compiler version must have somehow converted it to the move semantics automatically.

**Comment by MrDetonia** [comment]
@janvorli I'm away from that system right now but the version in the repositories is 3.9.0.
I did try `std::move(ex)` and that seemed to get rid of that error, though I have a few more build errors from other places. I guess that fixes this particular issue?
I'll keep trying to get this compiling.

**Comment by MrDetonia** [comment]
Clang version information:
```
iapetus# clang --version
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

After changing that line, the build errors I have left all seem to be `binding dereferenced null pointer to reference has undefined behavior` in various files (`28 errors generated`).
I take it that these errors are a result of the newer clang version.

Would it be worth posting the build errors in this topic, or making a new issue for those?

**Comment by janvorli** [comment]
@MrDetonia I was able to repro the issues locally with Clang 3.9.0 too. I have already merged in a fix for the `std::move(ex)` thing.
Please create a new issue for the other issue.

**Comment by MrDetonia** [comment]
Closing this one now the specific change is merged in, and #8016 seems more on point about clang 3.9 specifically.

**Comment by abrodersen** [comment]
Can someone link me to the pull request that fixed this issue? I

**Comment by janvorli** [comment]
@abrodersen #8311
