### ISSUE TITLE
Automatically archive symbols for CoreCLR release branch builds

### ISSUE THREAD

**Issue by dagood** [dotnet/coreclr#7824]
To ensure releases have symbols archived without complicating the release process, we should archive symbols for each release branch build. This is purely an infra issue tracked in https://mseng.visualstudio.com/Tools/_workitems?id=605797, so this github issue is just for better visibility.

**Comment by mschult2** [comment]
I'm able to download the symbols for clrjit.dll and lots of other Windows libraries from the Windows public symbol server.

Yet I cannot download the symbols for coreclr.dll.

Are the symbols for coreclr.dll indexed somewhere?  If not, do you have an estimate for when this issue will be resolved?

**Comment by dagood** [comment]
You should be able to find coreclr.dll there, although there are occasional hiccups where a specific release isn't archived correctly at first. For example, https://github.com/dotnet/core/issues/1112 discusses symbols for the 2.0.3 release. For the 2.0.4 release, I'm able to get symbols associated with all the files I'd expect. What version are you trying to find on the public symbol server?

This issue is out of date--symbols will eventually be available on the public symbol server, but it won't be specific to release builds and won't be done by archiving them. Here's a related issue, although it isn't perfect either: https://github.com/dotnet/coreclr/issues/10873. Closing, but do let me know if you're having problems with symbols for a specific release.

**Comment by danmosemsft** [comment]
@mikem8361

**Comment by TautvydasZilys** [comment]
@dagood do you happen to have a link to symbols of CoreCLR.dll for runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR version 1.0.2?

**Comment by dagood** [comment]
I don't, that package was from the .NET Core Runtime 1.0.0 release, before I had context on where/if symbol packages were stored. It sounds like you should upgrade to a newer version.
