### ISSUE TITLE
SafeBuffer.Initialize(numElements, sizeOfEachElement) subject to overflow issues.

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/coreclr#7829]
[This check](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/InteropServices/SafeBuffer.cs#L127-L128):

```
if (IntPtr.Size == 4 && numElements * sizeOfEachElement > UInt32.MaxValue)
    throw new ArgumentOutOfRangeException("numBytes", Environment.GetResourceString("ArgumentOutOfRange_AddressSpace"));
```

both `numElements` and `sizeOfEachElement` are also of type `uint` (not that being `int` would prevent the problem).  If the multiplication happens unchecked, overflow would make the value less than the max value.  Probably the check should be written something like:

```
if (IntPtr.Size == 4 && numElements > UInt32.MaxValue / sizeOfEachElement )
    throw new ArgumentOutOfRangeException("numBytes", Environment.GetResourceString("ArgumentOutOfRange_AddressSpace"));
```

...although this presumes elements have non-zero size (which previous checks do not look for).

<hr />

[The following check](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/InteropServices/SafeBuffer.cs#L131-L132):

```
if (numElements * sizeOfEachElement >= (ulong)Uninitialized)
    throw new ArgumentOutOfRangeException("numElements", Environment.GetResourceString("ArgumentOutOfRange_UIntPtrMax-1"));
```

... has the same problem.

<hr />

Note, however, that the method ends by setting `_numBytes` with this line:

```
_numBytes = checked((UIntPtr) (numElements * sizeOfEachElement));
```

... which means that changing this would result in changing the exception thrown.

**Comment by janvorli** [comment]
cc: @gkhanna79, @yizhang82 
Not only this check is wrong, but also the first two checks in the function make no sense. The args are uints, so testing them for < 0 doesn't make sense.

**Comment by jkotas** [comment]
Re-opening to track corefx test update

**Comment by jkoritzinsky** [comment]
Test update is merged in so I believe we can close this.
