### ISSUE TITLE
Enable crossgen to use SSE2 instructions for x86

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#7833]
A PR was started for this https://github.com/dotnet/coreclr/pull/6647 but not finished. Perhaps a volunteer could take it over.

Notes from the PR:

crossgen currently doesn't generate SSE instructions of any kind for x86, which was causing issues in #6638 when I was attempting to use it with 16-and-larger byte types. This change enables it to use SSE2 instructions, dropping support for processors that don't support that.

Here is the gist that results when I dump the disassembly of every method in the System.Private.CoreLib native image, and grep for xmm.

Notes:

According to Wikipedia Pentium 4 (which is targeted for the framework) already supports SSE2, so there's no reason not to enable this for the framework.
The region ifdef'd under FEATURE_CORECLR seems to target Pentium Pro (released in 1995), an older processor than Pentium 4. Since this has no support for SSE, I just deleted this and retargeted it to Pentium 4.
Removed ifndef for CoreCLR that contained a call to GetSpecificCpuInfo, which is presumably querying the actual processor's features at runtime. Is there any reason this wasn't enabled before?

**Comment by mikedn** [comment]
RyuJIT can't generate non-SSE2 code so this is probably useless once x86 CLR moves to RyuJIT.

**Comment by danmosemsft** [comment]
OK. FYI @CarolEidt since she's a JIT person.
