### ISSUE TITLE
Port x-plat SecureString implementation from CoreFX to mscorlib

### ISSUE THREAD

**Issue by shrah** [dotnet/coreclr#7834]
The x-plat SecureString implementation need to be ported from corefx/src/System.Security.SecureString/src/System/Security/SecureString.cs  to mscorlib. This is required in order to port the Marshal.SecureStringTo* APIs as they take SecureString as parameter.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #13062](https://github.com/dotnet/corefx/issues/13062) via [**ZenHub**](https://www.zenhub.com/)
