### ISSUE TITLE
remove custom scripts to donwload coredistools

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#7861]
Remove tests\setup-runtime-dependencies.\* and associated infra 
To restore the coredistools package, just add an entry in 
https://github.com/dotnet/coreclr/blob/master/tests/src/Common/test_runtime/project.json

cc @swaroop-sridhar Please reroute accordingly

**Comment by ramarag** [comment]
cc @gkhanna79 @russellhadley

**Comment by ramarag** [comment]
cc @sbomer

**Comment by gkhanna79** [comment]
@RussKeldorph Is this required for 2.0? If not, can you move it to appropriate milestone?

**Comment by swaroop-sridhar** [comment]
Fixed by https://github.com/dotnet/coreclr/commit/798387ee90d7536d5a620af8482100ba76f6061a
