### ISSUE TITLE
DateTime.ToString(“R”) allocates too much

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/coreclr#7881]
There are alternate lower allocating approaches. I know of a few I'll add to this issue when I find them again.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/HttpAbstractions/pull/716/files

**Comment by Petermarcu** [comment]
I have a change that shows a more than 50% reduction in allocated bytes and 75% reduction in allocations. Will make a PR soon.
