### ISSUE TITLE
System.Numerics.Vectors for pointers not only arrays

### ISSUE THREAD

**Issue by brunom** [dotnet/coreclr#7893]
I want to process data from native components that I have a pointer to, not an arraay.

**Comment by davidfowl** [comment]
You can use https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/4.0.0 to do `Unsafe.Read<Vector<T>>(pointer)`

**Comment by brunom** [comment]
Awesome, I'll try that.
