### ISSUE TITLE
Raspberry PI 3 (ARM) Windows 10 iot target

### ISSUE THREAD

**Issue by JPBlanc** [dotnet/coreclr#7899]
Sorry, not a real issue

I perhaps lose something, but I can't find a way to install .Net Core on Raspberry PI3.

I post the issue #4400 on _dotnet/cli_ , my answer was closed, and I was redirected to this project by piotrpMSFT.
 
Is there a roadmap to target these machines ?

Can I help in testing or developping ?

I used to be a system developper on unix, OS/2 and then Windows from 1995 to 2003 and then applictive over .NET. Now I spend more time batching with PowerShell than writing code, but I still support my code.

regards.

JPB

**Comment by jkotas** [comment]
cc @gkhanna79

**Comment by jkotas** [comment]
CoreCLR can build for Windows ARM as of right now - the build was enabled in the CI just recently https://github.com/dotnet/coreclr/pull/7637. The remaining work is in getting the Windows ARM support pushed throughout the rest of .NET Core stack, testing, etc.

**Comment by gkhanna79** [comment]
@JPBlanc @jkotas is correct. We have been bringing up parts of the .NET Core stack building for Windows Arm32. Over the weekend, I got the builds enabled in https://github.com/dotnet/core-setup CI as well.

With the stack building, you should be able to play with it though keep in mind that no testing has been done of any sort across the board as the infrastructure needs to be brought up. As we come close to enabling that, we will plan for a formal roadmap around the support.

**Comment by JPBlanc** [comment]
@gkhanna79 to be concrete, what have I to do to get a dotnet CLI on my ARM32 ?

Perhaps you can give me some guidelines?

Thanks in advance.

**Comment by gkhanna79** [comment]
@JPBlanc To play with .NET Core for Arm32, you can now try the following:

1) Download it from _Daily Builds_ section at https://github.com/dotnet/core-setup and copy the folder layout to your device.

2) Build a portable app on your x64 machine and publish it locally.
3) Copy the published app to your device.
4) Run `dotnet <path to your publishedapp.dll>` on your device.

Do keep in mind that we just got the E2E stack building and there is no testing done on this yet!

**Comment by gkhanna79** [comment]
@JPBlanc Do you have any further questions on this or can we close this issue?

**Comment by JPBlanc** [comment]
Thanks that' what I was looking for.
Sorry for the delay.
