### ISSUE TITLE
Effective Interlocked.* inlining by JIT

### ISSUE THREAD

**Issue by azhmur** [dotnet/coreclr#79]
x86_64 has 'lock' instruction prefix allowing System.Interlocked methods to be implemented as nearly one CPU instruction. Actually C-compiliers do it for a long time. (just checked MSVC, and it does).
But JIT generated code (.Net framework 4.5.1 from WSUS) seems not so good. Interlocked.Exchange is one instruction, but Add, CompareExchange and others generated as a calls.

PS Haven't checked RyuJIT yet.

**Comment by mikedn** [comment]
All .NET JIT compilers I know generate `lock add` and `lock cmpxchg` rather than calls. The only exception I know are 64 bit interlocked operations on x86. Is that what you're talking about? Or do you have some sample code that shows this issue?

**Comment by cmckinsey** [comment]
One additional comment, I believe a helper call is generated by the JIT for interlocked operations on object references since a write-barrier is required. If this isn't the case let us know.

**Comment by azhmur** [comment]
Sorry guys, its was my misunderstanding. We were doing tests under VS debugger (Release/Any CPU, x64 host, Prefer 32-bit disabled). It seems VS debugger disables inlining in JIT for a purpose of better line positioning (despite assembly attributes). If i run same code without debugger initially and attach it after JIT made his job i can see completely different code from one by simple F5 run.

https://gist.github.com/azhmur/3bbd85330988734c658a

**Comment by mikedn** [comment]
The debugger disables all JIT optimizations, not only inlining.  See Tools\Options\Debugging\General\Suppress JIT optimization on module load.

**Comment by azhmur** [comment]
Thank you for clarification!
