### ISSUE TITLE
Edit and continue not working

### ISSUE THREAD

**Issue by treziac** [dotnet/coreclr#7902]
When creating a Console Application project (.NET Core) in visual studio 2015, edit and continue is not working in debug (classic "this source file has changed. It no longer matches the version of the file used to build the application being debugged")
However, it works when creating a standard console application project.

Couldn't find any info on the edit and continue feature on core project, is there a conf to enable or is it just not implemented in vs2015?

Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
Microsoft .NET Core Tools (Preview 2)   14.1.20907.0

Thanks!

**Comment by hdesouky** [comment]
did you found a solution for this?

**Comment by treziac** [comment]
No, it still doesn't work and isn't fixed with new csproj in 2017 RC, making without it for the moment

**Comment by Ziflin** [comment]
Is there any indication of when this might be fixed?

**Comment by janvorli** [comment]
cc: @noahfalk

**Comment by noahfalk** [comment]
@gregg-miskelly - is something you guys were aware of?

**Comment by gregg-miskelly** [comment]
@treziac Do you know if you are using portable PDBs? I believe it is the default for the VS templates (see https://github.com/OmniSharp/omnisharp-vscode/wiki/Portable-PDBs for more information). 

If so - I believe this is fixed in 2017 RC.3 when that comes out: https://github.com/dotnet/roslyn/pull/16197. 
If not - I am not sure why this isn't working for you. I can give it a try.

**Comment by Sharpiro** [comment]
Using VS 2017 RC4-26206

Creating a simple Console Application from template and trying to modify "Hello World" while debugging, will then not allow the current debug location to be moved.

**Comment by gkhanna79** [comment]
@mikem8361 @noahfalk @lt72 PTAL

**Comment by noahfalk** [comment]
@gkhanna79 - @gregg-miskelly's team usually takes the first crack at issues that repro in VS and then engages our team if they think the bad behavior is coming from our APIs.

**Comment by gkhanna79** [comment]
Thanks @noahfalk - I assigned it to you to triage and route as appropriate as you would know the best :)

**Comment by noahfalk** [comment]
@gkhanna79 - Heh, yeah, I realized your intent a little ways after responding ; ) Certainly thanks for forwarding and please keep doing so.

**Comment by treziac** [comment]
It was working better for me on last RC, but I'm waiting for the official release to check again ;)

**Comment by lt72** [comment]
Assigning to Gregg for proper tracking.

**Comment by gregg-miskelly** [comment]
@treziac did you get a chance to try in RTW yet?

**Comment by treziac** [comment]
Yes, it seems to work properly, thanks!
