### ISSUE TITLE
JIT: Value numbering overly conservative around byrefs

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/coreclr#7903]
Value numbering is (rightly) conservative w.r.t. indirections off byrefs, but should at least be able to remove back-to-back redundant loads.  For example, consider method `Detail` below:

```c#
using System;
using System.Runtime.CompilerServices;

public class Example
{
    public string color;
    public string make;
    public string model;
    public string year;

    public struct Car
    {
        Example ex;
        public Car(Example e) { ex = e; }

        [MethodImpl(MethodImplOptions.NoInlining)]        
        public void Detail()
        {
            Describe(ex.color, ex.year, ex.make, ex.model);
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        public void Describe(string color, string make, string model, string year)
        {
            Console.WriteLine("This is a {0} {1} {2} {3}\n",
                color, make, model, year);
        }
    }

    public static int Main(string[] args)
    {
        Example e = new Example();
        e.year = "1977";
        e.make = "GMC";
        e.model = "K1500";
        e.color = "Rusty";
        
        Car c  = new Car(e);
        c.Detail();
        return 100;
    }
}
```

We generate redundant loads of `this.ex` for each of the arguments:

```asm
; Assembly listing for method Car:Detail():this
; Emitting BLENDED_CODE for X64 CPU with AVX
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 this         [V00,T00] (  7,   7  )   byref  ->  rcx         this
;  V01 OutArgs      [V01    ] (  1,   1  )  lclBlk (40) [rsp+0x00]  
;
; Lcl frame size = 40


G_M19041_IG01:
       4883EC28             sub      rsp, 40

G_M19041_IG02:
       488B11               mov      rdx, gword ptr [rcx]
       488B5218             mov      rdx, gword ptr [rdx+24]
       4889542420           mov      gword ptr [rsp+20H], rdx
       488B11               mov      rdx, gword ptr [rcx]
       488B5208             mov      rdx, gword ptr [rdx+8]
       4C8B01               mov      r8, gword ptr [rcx]
       4D8B4020             mov      r8, gword ptr [r8+32]
       4C8B09               mov      r9, gword ptr [rcx]
       4D8B4910             mov      r9, gword ptr [r9+16]
       E856FBFFFF           call     Car:Describe(ref,ref,ref,ref):this
       90                   nop      

G_M19041_IG03:

       4883C428             add      rsp, 40
       C3                   ret      
```

When value numbering the indirection via `this`, rather than falling down into [this code](https://github.com/dotnet/coreclr/blob/ec5868c2d7b316cc810cc6cec4c845e3a7e9936d/src/jit/valuenum.cpp#L6332-L6336) that uses an entirely opaque value number, you'd think we could use something that is a function of the pointer and heap values.  Possibly there's some subtlety around the cases where the managed pointer doesn't point into the heap; I'd have to check to recall whether we lump address-taken locals and statics into the "heap" value number or not.  If locals are an issue, perhaps limiting the scope to byref parameters would help.

**Comment by JosephTremoulet** [comment]
It looks like we don't in fact lump address-exposed locals/statics into the "heap" value; the code to value-number an assign skips the `mutateHeap` call if it can prove that the thing being written is a local (not specifically a tracked-in-SSA local), hence if we have code like this:

```c#
        static void foo(bool b)
        {
            int x = 5;
            if (b)
            {
                x = 2;
            }
            bar(ref x);
        }
```

then we don't generate a new heap number at the `x = 2`:

```
The SSA definition for heap (#2) at start of BB02 is $100 {InitVal($41)}

***** BB02, stmt 3 (before)
N001 (  1,  1) [000019] ------------             /--*  const     int    2
N003 (  5,  4) [000021] -A--G---R---             *  =         int   
N002 (  3,  2) [000020] D---G--N----             \--*  lclVar    int   (AX) V01 loc0         

N001 [000019]   const     2 => $44 {IntCns 2}
Tree [000021] assigns to local var V01; excluded from SSA, so value not tracked.
N003 [000021]   =         => $44 {IntCns 2}

***** BB02, stmt 3 (after)
N001 (  1,  1) [000019] ------------             /--*  const     int    2 $44
N003 (  5,  4) [000021] -A--G---R---             *  =         int    $44
N002 (  3,  2) [000020] D---G--N----             \--*  lclVar    int   (AX) V01 loc0         

finish(BB02).
   Succ(BB03).
     Not yet completed.
     All preds complete, adding to allDone.
The SSA definition for heap (#2) at start of BB03 is $100 {InitVal($41)}
```

Which in turn means that giving indirect loads via byrefs a value number "that is a function of the pointer and heap values" isn't in itself sufficient; it would also need to be a function of the memory loaded from.  One approach would be to enumerate things that we don't lump into the heap and make such loads functions of them also; another would be to make anything that such a load can dereference part of the "heap" (which, in the case of locals, might be something simple along the lines of updating the places where we check if an address is address-of-local to instead check if it is address-of-tracked-local; haven't yet looked into statics and object fields).

**Comment by JosephTremoulet** [comment]
Looks like statics and object fields do both currently prompt new heap VNs, so I think it really is just not-tracked locals that need to generate new heap values on writes and then byref loads can be modeled as a function of the heap and pointer values.

**Comment by JosephTremoulet** [comment]
We'll still want to be able to disambiguate known "heap" entities (object fields, statics) past stores to untracked locals.  So I think we'll need to add two VNFuncs:
  1. Something like `WriteUntrackedLocal(prevHeap)`, which we'd set as the new "heap" value at stores to untracked locals, which would be parameterized by the previous "heap" value.  Then when value-numbering an object/static field load, we'd walk right through these (maybe in ApplySelectors) since they can't interfere.
  2. Something like `ByrefLoad(ptrVal, heapVal)`, which we'd set as the value at loads from byrefs that we don't have FieldSeqs for.  CSE of loads like in the code above should then just fall out.

**Comment by JosephTremoulet** [comment]
Sounds like #9036 is an instance of this, as well as #7914.

**Comment by benaadams** [comment]
Also https://github.com/dotnet/coreclr/issues/9041 ?

**Comment by JosephTremoulet** [comment]
@benaadams, #9041 sounds more like stack-packing to me

**Comment by briansull** [comment]
I mention to Siva when he was investigating  #9036 that I believed that you were already investigating this issue "addressing the value number assigned for repeated identical loads from memory using a byref pointer"

**Comment by briansull** [comment]
My thinking is that in addition to the "global heap" value number which tracks changes made to the managed heap , we also need another "global everything" state value number which tracks both kinds of changes, to the heap and to other non-heap memory (I.e. byrefs into possible stack locations).

Read indirections through byrefs would be a function of the memory loaded from (i.e "global everything").  All writes and calls would mutate this "global everything" state

I'm not sure that we have to special case writes into untracked locals.  I think that for local variables in your own stack frame can be consider safe, even if they are untracked.  Instead we have to check if the local is  mark address exposed and if so then it mutes the "global everything" state.

This might not get all of the cases that we want (because we aren't doing true alias analysis) but it will allow us to get these cases where there are no writes occurring between to identical reads through byrefs.

**Comment by JosephTremoulet** [comment]
> in addition to the "global heap" value number which tracks changes made to the managed heap , we also need another "global everything" state value number which tracks both kinds of changes, to the heap and to other non-heap memory (I.e. byrefs into possible stack locations)

Great, that's the direction I've been pursuing.


>I'm not sure that we have to special case writes into untracked locals. I think that for local variables in your own stack frame these writes can be consider safe, even if they are into untracked locals. Instead we have to check if the local is marked address exposed and if so then that write would mutate the "global everything" state.

Ah, so any local that can be read/written through a byref, even if untracked, must be "address exposed"?  I've been including all untracked locals in "global everything", but can change it to exclude non-address-exposed (untracked) locals and see how the diffs change.

**Comment by JosephTremoulet** [comment]
Or the check might have to be some combination of tracked-ness and address-exposed-ness... is it possible to have a tracked address-exposed local?  Looks like [they cannot](https://github.com/dotnet/coreclr/blob/6a3c584b80dde7752a595344b3dc727918c94183/src/jit/lclvars.cpp#L2805-L2816), but I'm not sure what state we expect to be set on locals in the `IndirAssignMap`... do those not get marked address-exposed?

**Comment by AndyAyersMS** [comment]
Great to see this get in. Do you have an "after" disasm you can post here for completeness?

**Comment by JosephTremoulet** [comment]
>Do you have an "after" disasm you can post here for completeness?

I do:

```asm
; Assembly listing for method Car:Detail():this
; Emitting BLENDED_CODE for X64 CPU with AVX
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 this         [V00,T00] ( 18,  18  )   byref  ->  rcx         this
;  V01 OutArgs      [V01    ] (  1,   1  )  lclBlk (40) [rsp+0x00]  
;  V02 cse0         [V02,T01] ( 19,  19  )     ref  ->   r9        
;
; Lcl frame size = 40

G_M43145_IG01:
       4883EC28             sub      rsp, 40

G_M43145_IG02:
       4C8B09               mov      r9, gword ptr [rcx]
       498B5118             mov      rdx, gword ptr [r9+24]
       4889542420           mov      gword ptr [rsp+20H], rdx
       498B5108             mov      rdx, gword ptr [r9+8]
       4D8B4120             mov      r8, gword ptr [r9+32]
       4D8B4910             mov      r9, gword ptr [r9+16]
       E85FFBFFFF           call     Car:Describe(ref,ref,ref,ref):this
       90                   nop      

G_M43145_IG03:
       4883C428             add      rsp, 40
       C3                   ret      
```
