### ISSUE TITLE
Investigate mapping one R2R image multiple times into memory

### ISSUE THREAD

**Issue by JohnChen0** [dotnet/coreclr#7955]
Currently, each Ready-to-Run image is only mapped once into the memory, even if it is loaded into multiple load contexts. The consequence is the pre-compiled native code can only be used in one load context, and JIT compiling must be used in all other load contexts.

We should investigate whether it's possible to map the same image multiple times into memory. This should make it possible to use pre-compiled code in multiple load contexts.

**Comment by jkotas** [comment]
We would need to stop using LoadLibrary to map the images ... that would break all sorts of things.

**Comment by gkhanna79** [comment]
@jkotas Should this be closed if it is not actionable (per your earlier comment)?
