### ISSUE TITLE
Optimize number.ToString()

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#7961]
Int64.ToString was too slow for Kestrel and they wrote their own:

https://github.com/aspnet/HttpAbstractions/blob/02363da94eee7311e457e136dc45edf9c5ac3494/src/Microsoft.AspNetCore.Http/Features/HttpRequestIdentifierFeature.cs#L39-L41

We should optimize our implemention such that they could remove their workaround.

This is a CoreCLR issue because the managed code just calls through to https://github.com/dotnet/coreclr/blob/master/src/classlibnative/bcltype/number.cpp#L2814

/c @davidfowl

**Comment by stephentoub** [comment]
I've no doubt that there are things that could be done to make long.ToString go faster than it currently does for particular scenarios, and we can/should certainly look at doing so.  But the linked function is not the equivalent of long.ToString (for example, 42L.ToString() returns "42", whereas GenerateRequestId(42) return "000000000001A").  The purpose as I understand it of that function in ASP.NET is to generate a human-readable representation of a long, but not constrained to be a base-10 representation; this code chooses instead a base-32 representation, is ok padding to always have 13 chars, etc.

**Comment by danmosemsft** [comment]
@stephentoub ack - you're right, and I should have read the code. I"ll close this then (we should do perf work based on data)
