### ISSUE TITLE
Ensure that codegen consumes registers in the proper order

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#7963]
(This was the original description of this issue, when it was opened; see below)
When reversing the GT_FIELD_LIST for pushing the fields onto the stack, we will, as a result, consume them in the wrong order, relative to their execution order. This is generally benign (and doesn't cause an assert, but instead causes "consumed in the wrong order" messages in a jitdump), but could result in problems with GC encoding if we have copy-propagated two GC ref fields to be the same lclVar. I was going to address this with the fix for DevDiv bug 278375, but I would like to create a repro first, and in the meantime I want to get that one fixed. It could potentially be fixed either by reversing the nodes in the execution order (not just in the list) - this should rarely (never?) require new temps because these are fields of promoted structs that shouldn't have side-effects. However, another alternative would be to first consume all the list entries, in original order, and then generate the code.

**Comment by pgavlin** [comment]
@CarolEidt: can you explain this a bit more completely? There should no longer be a dependency between the order in which a node consumes its operands and the order in which a node's operands execute. As long as LSRA and code generation are consistent w.r.t. the order in which a node consumes its operands things should work out fine.

**Comment by CarolEidt** [comment]
@pgavlin I finally took another look at this. As you point out, there should not be a dependency here. However, the code that checks this (that doesn't assert, only prints a warning with JitDump is set) in `genCheckConsumeNode()` is assuming that the correlation still exists between execution (producing) order and consuming order. In the past, this has helped identify bugs in the code generator where it was either not consuming its operands, or consuming them in the wrong order (leading to GC and other issues). So, it would be good to figure out another way to ensure that things are consumed in the proper order. Further, even if LSRA and codegen agree, the last use information on the lclVars will be incorrect if we change the order - which will perpetuate the need for the `setLastUses` phase of LSRA.
I will change the title of this issue and change it to a "suggestion".

**Comment by pgavlin** [comment]
> Further, even if LSRA and codegen agree, the last use information on the lclVars will be incorrect if we change the order

Is last use information calculated based on the order in which the lclVar nodes appear in the function?

**Comment by CarolEidt** [comment]
> Is last use information calculated based on the order in which the lclVar nodes appear in the function?

Yes, that's how liveness computes it. So that will need to change before we eliminate `setLastUses`.

**Comment by CarolEidt** [comment]
Note that the reason `setLastUses` exists is precisely because there have been issues in the past with the sequencing of lclVar uses. So this is just more of same.
