### ISSUE TITLE
JIT asserts fail the Arm64 Pipeline Build

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#7969]
See https://devdiv.visualstudio.com/DevDiv/_build?buildId=411992 as an example.

CC @RussKeldorph @wtgodbe

**Comment by gkhanna79** [comment]
When this is fixed, please work with @wtgodbe to re-enable pipeline builds in master branch.

**Comment by gkhanna79** [comment]
The Arm64 crossgen is broken due to the following assert that I am able to repro on the local CoreCLR master:
 
Missing flags on tree [000235]: ---G--------
               [000243] ----G--------             /--*  <fldList> void   long at offset 8
               [000242] ----G--------             |  \--*  indir     long 
               [000240] -------------             |     |  /--*  const     long   8
               [000241] ----G--------             |     \--*  +         byref
     (  1,  1) [000239] -------------             |        |  /--*  const     long   16 field offset Fseq[guidCustomVersion]
     (  5,  5) [000236] ----G--------             |        \--*  +         byref
     (  3,  3) [000237] L---G--------             |           \--*  addr      byref
     (  3,  2) [000238] ----G--N-----             |              \--*  lclVar    struct(AX) V02 loc1        
               [000235] -------------             *  <fldList> void   long at offset 0
               [000234] -------------             \--*  indir     long 
     (  1,  1) [000224] -------------                |  /--*  const     long   16 field offset Fseq[guidCustomVersion]
     (  5,  5) [000225] -------------                \--*  +         byref
     (  3,  3) [000147] L------------                   \--*  addr      byref
     (  3,  2) [000146] ----G--N-----                      \--*  lclVar    struct(AX) V02 loc1        
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.
 
 
Assert failure(PID 10000 [0x00002710], Thread: 17324 [0x43ac]): Assertion failed '!"Missing flags on tree"' in 'System.Globalization.CompareInfo:get_Version():ref:this' (IL size 131)
 
    File: d:\gh\gkhanna79\coreclr\src\jit\flowgraph.cpp Line: 20590
    Image: D:\GH\gkhanna79\coreclr\bin\Product\Windows_NT.arm64.Debug\x64\crossgen.exe

**Comment by jashook** [comment]
Note this only break the Debug build.

**Comment by jashook** [comment]
Will be fixed by #8003

**Comment by jashook** [comment]
#8003 is closed, based on review the comment is correct and we will change the assert instead to acknowledge this as a valid possibility.

**Comment by gkhanna79** [comment]
@jashook When do you expect the change for the assert coming in? CoreCLR master pipeline build is blocked until that is clean.

**Comment by jashook** [comment]
Fix has been PRed see #8026

**Comment by jashook** [comment]
@gkhanna79 [the debug](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_debug_windows_nt_prtest/lastSuccessfulBuild/console) build is now passing.

**Comment by gkhanna79** [comment]
Excellent - thank you for getting this fixed.
