### ISSUE TITLE
List<T>.Reverse boxes every element in the array if it's instantiated with a struct type.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/coreclr#7986]
At https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/List.cs#L931 ```List<T>``` calls into Array.Reverse to actually implement reversing the elements.  However Array.Reverse implements this here: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Array.cs#L1593

This impl ends up doing the following:

```c#
Object temp = array.GetValue(i);
array.SetValue(array.GetValue(j), i);
array.SetValue(temp, j);
```

which involves a boxing of every object in the array when the array is a struct type.

**Comment by justinvp** [comment]
`List<T>` calls the new generic `Array.Reverse<T>` which doesn't have this issue. See #7132.

**Comment by CyrusNajmabadi** [comment]
Ah, interesting.  Look like us (Roslyn) are being hit because we don't have that fix yet :(

**Comment by stephentoub** [comment]
Even before that, though, this change a year ago would have alleviated such boxing:
https://github.com/dotnet/coreclr/commit/a57dd5a8f6c8374241c570c9307e5dcef9b201d4

**Comment by jkotas** [comment]
> being hit because we don't have that fix yet

You have that fix (and many other perf tweaks) when running on .NET Core ... you just do not have it when running on .NET Framework.

**Comment by CyrusNajmabadi** [comment]
Will these fixes make it to the .Net framework?

**Comment by jkotas** [comment]
Yes, some will ... but it will take quite some time.
