### ISSUE TITLE
Need Build instructions for FreeBSD

### ISSUE THREAD

**Issue by richlander** [dotnet/coreclr#799]
We have instructions for Windows, Linux and OS X. We now need to add FreeBSD now that it is building. #793. Very nice.

Instructions will go here:
https://github.com/dotnet/coreclr/blob/master/README.md#get-coreclr
https://github.com/dotnet/coreclr/blob/master/Documentation/README.md#build-coreclr-from-source

Probably should be called freebsd-instructions.md to match the other instructions.

**Comment by janhenke** [comment]
I am already working on this.

**Comment by josteink** [comment]
@janhenke I'm glad to see someone keeping the momentum, especially now that we're getting "famous". Great effort so far! :)

I'll get back to the project when I have fewer projects at home that needs completion!
