### ISSUE TITLE
GC tests failing to access meminfo

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/coreclr#8030]
Example here: https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/1343/testReport/junit/GC.LargeMemory.API.gc/keepalive/keepalive/

This seems to be happening consistently in these jobs. I just noticed this and haven't investigated it at all, but my first hunch is that this is related to https://github.com/dotnet/corefx/commit/bd667b3e719ff84110d9b3c8c087a678337aa5a5

My guess is that we're now now trying to open /proc/meminfo with write access with the call to `ReadAllLines` (which is occurring in multiple processes at once).

@JeremyKuhne

**Comment by RussKeldorph** [comment]
@jashook FYI

Yet another: https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/1363/testReport/junit/GC.LargeMemory.API.gc/gettotalmemory/gettotalmemory/

**Comment by adityamandaleeka** [comment]
Having looked at this a bit more, it may be related to this PR https://github.com/dotnet/corefx/pull/13415 which changed the StreamReader/Writer ctor that's used in some of the IO functions. I'm not familiar with this code and am currently reading through it, so I still don't know exactly where the problem lies.

FYI @stephentoub

**Comment by stephentoub** [comment]
I believe https://github.com/dotnet/corefx/issues/13459 should fix it.

**Comment by adityamandaleeka** [comment]
@stephentoub Thanks!
