### ISSUE TITLE
Reduce allocations in String.Split

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#8034]
Now that `ArrayPool` is in the coreclr repo, it may be worth trying to use `stackalloc` for the int table required by `Split` if the length of the string is small enough, otherwise using `ArrayPool<int>` to rent the tables.

I have been building [a prototype](https://github.com/dotnet/coreclr/compare/master...jamesqo:better-split?expand=1) to implement this over the last day or so; however, it's turning out much more complex than I expected. I can't even run the corefx tests since the xUnit runner chokes before it gets to them (probably due to something wrong in my changes) ☹️ Once I finish, however, I'll open a PR for this. In the meantime, I'm opening this issue to track this in case I can't finish.

**Comment by Maoni0** [comment]
@swgillespie could you please take a look at the prototype @jamesqo did?

**Comment by swgillespie** [comment]
From an allocation perspective this all looks reasonable and good to me. I'm wondering if we can use a Span instead of char* and length pair for the separator array, though? I see that it's used in MakeSeparatorList but I don't think I see any uses in there that prevent a Span from being used in its place, which would prevent a pin.

**Comment by jamesqo** [comment]
@swgillespie Good point, I didn't think of using `Span` for this. I'll update the code to use it before submitting a PR. Thanks!

**Comment by danmosemsft** [comment]
Per [issues guidance](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/IssuesFeedbackEngagement.md) 
> If in the managed code log it in the CoreFX repo even if the code is in this CoreCLR repo (ie., in mscorlib/System.Private.Corelib). The reason for this is we sometimes move managed types between the two and it makes sense to keep all the issues together.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #14323](https://github.com/dotnet/corefx/issues/14323) via [**ZenHub**](https://www.zenhub.com/)
