### ISSUE TITLE
CoreCLR Ubuntu 14.04 Build fails with Latest liblttng-ust-dev installed

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#8045]
The latest version 2.8.x version which is on the PPA feed ppa:lttng/ppa will cause coreclr builds to fail:

Determining if files lttng/tracepoint.h exist failed with the following output:
Change Dir: /home/brianrob/src/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec1151644146/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec1151644146.dir/build.make CMakeFiles/cmTryCompileExec1151644146.dir/build
make[1]: Entering directory `/home/brianrob/src/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/brianrob/src/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec1151644146.dir/CheckIncludeFiles.c.o
/usr/bin/clang-3.5  -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64 -D_POSIX_C_SOURCE=200809L -Wall -std=c11    -o CMakeFiles/cmTryCompileExec1151644146.dir/CheckIncludeFiles.c.o   -c /home/brianrob/src/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeTmp/CheckIncludeFiles.c
Linking C executable cmTryCompileExec1151644146
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1151644146.dir/link.txt --verbose=1
/usr/bin/clang-3.5   -Wall -std=c11     CMakeFiles/cmTryCompileExec1151644146.dir/CheckIncludeFiles.c.o  -o cmTryCompileExec1151644146 -rdynamic 
CMakeFiles/cmTryCompileExec1151644146.dir/CheckIncludeFiles.c.o: In function `__tracepoints__init':
/home/brianrob/src/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:(.text+0x92): undefined reference to `dlopen'
CMakeFiles/cmTryCompileExec1151644146.dir/CheckIncludeFiles.c.o: In function `__tracepoint__init_urcu_sym':
/home/brianrob/src/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:(.text+0x124): undefined reference to `dlsym'
/home/brianrob/src/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:(.text+0x160): undefined reference to `dlsym'
/home/brianrob/src/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:(.text+0x19c): undefined reference to `dlsym'
CMakeFiles/cmTryCompileExec1151644146.dir/CheckIncludeFiles.c.o: In function `__tracepoints__destroy':
/home/brianrob/src/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:(.text+0x242): undefined reference to `dlclose'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: Leaving directory `/home/brianrob/src/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeTmp'
make[1]: *** [cmTryCompileExec1151644146] Error 1
make: *** [cmTryCompileExec1151644146/fast] Error 2

Source:
/* */
#include <lttng/tracepoint.h>

int main(){return 0;}

**Comment by Librazy** [comment]
Similar problem on Arch Linux AUR package : https://aur.archlinux.org/packages/dotnet-cli/

**Comment by janvorli** [comment]
@Librazy this was already fixed several days ago by #8470.
