### ISSUE TITLE
Finally in-lining or cloning in the corresponding try-block

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#8065]
Kestrel server has following hot methods and the only EH they have is a try-finally block.

1) Microsoft::AspNetCore::Server::Kestrel::Internal::Http::SocketInput::ConsumingComplete()
This method uses lock(obj) for synchronization and results a in try-finally. Whole of the method logic is in try block and finally used for releasing monitor lock.

2) Microsoft::AspNetCore::Server::Kestrel::Internal::Http::Frame::TakeStartLine
This method explicitly uses try-finally block.  Here too whole of the method logic is in try block and finally block has a single method call.

3) Microsoft::AspNetCore::Server::Kestrel::Internal::Http::FrameResponseHeaders::CopyToFast
This method uses C# foreach that results in try-finally.

In-lining finally block within try-block for non-EH execution would be beneficial for these methods.  At least in-lining simple finally funclets that have a single basic block in a non-nested try-finally case, would benefit the above mentioned methods (or similar such methods).

Another related issue: right now if the main method saves/restores 5 callee saved regs, even funclet methods irrespective of whether they use those callee saved regs also save/restore those 5 callee saved regs.  This would become a non-issue (from execution perf perspective) for simple try-finally blocks where we succeed in in-lining finally in the corresponding try.

**Comment by mikedn** [comment]
Related issue: #1505

**Comment by AndyAyersMS** [comment]
I have a [prototype](https://github.com/AndyAyersMS/coreclr/tree/FinallyCloning) underway.
