### ISSUE TITLE
[Port] Add capturing YMM registers to OSX InjectActivationInternal

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#8066]
Currently, we are not capturing the YMM registers on hardware that supports them when we inject activation on OSX and so if any code that's run during the activation modifies these and the code that was interrupted was using them, we would cause it to fail.
It needs to be fixed. There is a x86_avx_state64_t state structure (and x86_AVX_STATE64 flavor) that we can use to capture the state and we should use it when running on a processor that supports YMM registers instead of the x86_float_state64_t.
We will need to modify CONTEXT_GetThreadContextFromPort and CONTEXT_GetThreadContextFromThreadState.
We need to use cpuid to find out whether we are running on processor that has YMM registers or not.
The YMM registers upper halves are to be stored in the CONTEXT::VectorRegister[0..15], the lower halves are in the corresponding XMM registers.

**Comment by janvorli** [comment]
We will also need to set CONTEXT_XSTATE on the context after capturing if we captured the YMM registers. The RtlRestoreContext already has support for handling it.

**Comment by gkhanna79** [comment]
We should use this to track getting the fix in for next LTS and 1.1.x.

**Comment by gkhanna79** [comment]
Once the #2266 is implemented, we want to port it back to 1.0.x.

**Comment by JohnChen0** [comment]
@gkhanna79 @janvorli: Which branches does the fix for #2266 need to be back ported? My guess is release/1.0.0 and release/1.1.0. Is it correct?

Also, now that we know YMM registers are not involved in this issue, do we still want to try implement saving/restoring YMM registers?

**Comment by gkhanna79** [comment]
Yes, it should be ported to release/1.0.0 and release/1.1.0. However, while you can prep the PRs, please hold off on merging them.

**Comment by JohnChen0** [comment]
Create PR #8098 for porting to release/1.0.0, and PR #8099 for porting to release/1.1.0

**Comment by JohnChen0** [comment]
Both PR #8098 and #8099 have been merged.
