### ISSUE TITLE
Fix the execution order for array range check nodes.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#8077]
In an array range check tree, the subtree that computes the array index must execute before the subtree that computes the array length. This currently causes the regression test added for VSO 283795 in #8031 to fail when using the x86 legacy backend; the RyuJIT backend only passes the test because it marks the array length subtree as contained by the range check node during lowering.

**Comment by hqueue** [comment]
@pgavlin As I've already wrote in #8031, ARM legacy backend has same problem. I will follow up this issue for ARM. Thanks!
