### ISSUE TITLE
Create an Ubuntu PPA & DEB packages

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/coreclr#808]
Would love to be able to keep up with what's going on in the official .NET FOSS space.  In order to do that though, it would be helpful to have a channel I can get software installed and updated through.

The DEBs should integrate nicely with the system, and not use `/opt` like some packages do.

**Comment by josteink** [comment]
Lots of projects, FOSS or not, has nightly builds published for testers to consume.

Before establishing a PPA specificly for Ubuntu, I think it would make sense to have a nightly build with all the artifacts for all the builds for all the architecture. Then someone can reuse that to build a PPA.

Opinions?

**Comment by akoeplinger** [comment]
> I think it would make sense to have a nightly build with all the artifacts for all the builds for all the platforms.

The Jenkins CI already does that, e.g. here for Linux: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_linux_release/lastSuccessfulBuild/artifact/

**Comment by atrauzzi** [comment]
So it's important that we not confuse the build with building for debian-based distributions.  I'm not 100% fluent in the process, but one build for all distributions is probably not going to end in something people enjoy using.

**Comment by josteink** [comment]
@akoeplinger isn't that from ongoing CI builds? A nightly build should be nightly, and only from code merged and committed to master. Just double-checking.

**Comment by josteink** [comment]
@atrauzzi agreed. Being Ubuntu-specific is an anti-pattern in the linux-world right now, but it would certainly make things simpler.

**Comment by akoeplinger** [comment]
@josteink it builds each commit on master, PR builds are a separate job.

**Comment by n8ohu** [comment]
At this point, we need to be sure we have viable builds for Linux, both 32 bit and 64 bit, before we get too concerned about distribution specific repository structures. We also need to consider where to draw the line; I don't expect someone to maintain a repository that is readily compatible with CentOS 5.x (which is what I run on my Desktop system) because older distribution versions may not have the most up to date versions of required libraries, if any, and providing those is something a lot of maintainers don't want to bother with.

**Comment by richlander** [comment]
> Being Ubuntu-specific is an anti-pattern in the linux-world right now, but it would certainly make things simpler.

@josteink can you elaborate on that, for a newb? Just want to understand better.

**Comment by n8ohu** [comment]
@richlander In a relatively simple way, there are layers when it comes to distributions of Linux; that is, some distributions are based in part on others that are referred to as the upstream (much like how forks of a github project relate to the original). Ubuntu is based in part on an upstream distribution called Debian, in this case. So what is being said is that supporting Ubuntu before the upstream distribution isn't a common practice.

**Comment by richlander** [comment]
@n8ohu That's what I was looking for. Best to put on your shoes after your pants.

**Comment by josteink** [comment]
@richlander Just referring to how many people who package software say they support "Linux", when all you can download from their website are Ubuntu-targetted debs.

As for creating deb's, RPM's and what not from source, I've heard that trying to solve that problem can give you grey hairs faster than solving multi-threaded race-conditions on live production systems.

In those discussions I've always seen someone refer to this as the only sane solution: https://github.com/jordansissel/fpm

If anyone decides to "attack" this issue (as in  actually trying to solve it), that's probably where they should start looking.

**Comment by atrauzzi** [comment]
It might be worth talking to @directhex on this as well.  He worked on the mono packages.  Very knowledgable.

**Comment by dlech** [comment]
There is a ppa listed now on http://dotnet.github.io/getting-started/

**Comment by josteink** [comment]
Awesome stuff.

Eager to try it out, I tried the instructions on Ubunty Wily Werewolf (16.10) and I'm getting the following bummer:

````
➜  ~  sudo apt-get install dotnet  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet : Depends: libicu52 (>= 52~m1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.
````

Is it only my setup which is weird, or should I raise a separate issue for this?

**Comment by dlech** [comment]
For now (from what I can tell) only Ubuntu 14.04 is supported. You could add trusty to your apt sources so that it can pickup the older version of that library or use trusty in a VM or something like that.

**Comment by forevergenin** [comment]
looks interesting

**Comment by jkotas** [comment]
Packages for many different Linux distros are available now: https://www.microsoft.com/net/learn/get-started/ (official releases), https://github.com/dotnet/core-setup (nightly builds).
