### ISSUE TITLE
ILASM: Add ARM64 command line option

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#8084]
Should probably remove Itanium while we're in there.

**Comment by jkotas** [comment]
This would be really only needed for full .NET Framework on ARM64. And in that case, the similar option has to be added in many places: all managed compilers (C#, VB, ...), msbuild target files, ... .

**Comment by BruceForstall** [comment]
@jkotas Do you still think we shouldn't update ILASM for ARM64 (and remove IA-64)? Is that because we don't have platform-specific .NET Core binaries, so don't need ILASM to be able to create such things?

**Comment by jkotas** [comment]
This should be a simple change (just replace IA64 with ARM64). Somebody can just do it.

This change is nice-to-have. It should not be required to make anything in .NET Core work.
