### ISSUE TITLE
Add JIT intrinsic support to take advantage of Intel SSE4.2 crc32 instruction

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#8089]
Scenario: Bing team needs to copy Giga bytes of data from Cosmos to Bing servers.  Receiving side uses crc32 of the data to verify that the data is correctly received.

On targets where SSE4.2 is not supported, managed implementation should fall-back to a non-accelerated CRC-32C algorithm that intel uses.

This needs to be supported both on Desktop and CoreCLR.

**Comment by redknightlois** [comment]
This is an special case of https://github.com/dotnet/corefx/issues/2209 .. we even discussed CRC32 specifically.

**Comment by fiigii** [comment]
This issue is fixed by https://github.com/dotnet/coreclr/pull/14456 on CoreCLR.
