### ISSUE TITLE
Assert failure(PID 10244 [0x00002804], Thread: 7648 [0x1de0]): Assertion failed '!(block->bbFlags & BBF_FINALLY_TARGET)' in 'GoryNativePastTest:foo():this' (IL size 42)

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#8092]
2 P1 tests fail on this

**Comment by RussKeldorph** [comment]
@gkhanna Mind adding the error output with the failing test names?  A link to a failing CI job might help as well if you have it.

**Comment by BruceForstall** [comment]
I don't see this failure, and because there are no test names listed here, I can't check those specifically.
