### ISSUE TITLE
 Fast append or insert StringBuilder into other StringBuilder

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/coreclr#8112]
Hello,
I think for fast strings processing, StringBuilder should have fast methods to append and insert other StringBuilder.

Now when I gather string from many parts, I gather each part into separated StrindBuilder (for example in different threads for speed) and then when I gather all parts to one StringBuilder, the standard library made many copy operations to convert each StringBuilder to string and then to copy each string to StringBuilder chunks. It is bad because after each part is appended to final StringBuilder, it is no longer used or changed, it is just collected by garbage. So it would be great just append chunks  from  one StringBulder to other without copy them two times.

So to fast append second StringBuilder to first StringBuilder, it can just append chunks from second to first. After that it can set CopyOnChange flag in common chunks of first and second StringBuilders. Later if CopyOnChange chunk should be changed (very rare unusual case) it should be duplicated before changing.

**Comment by mattwarren** [comment]
Admittedly it's a bit hacky, but if you don't mind using `unsafe` and `fixed` you can do something like this:

``` csharp
// https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/StringBuilder.cs#L55
private static BindingFlags flags = BindingFlags.Instance | BindingFlags.NonPublic;
private static FieldInfo rawCharsField = typeof(StringBuilder).GetField("m_ChunkChars", flags);
private static Func<StringBuilder, char[]> GetRawStringData = sb => (char[])rawCharsField.GetValue(sb);

static unsafe void Main(string[] args)
{
    var sbA = new StringBuilder();
    sbA.Append("Testing - ");

    var sbB = new StringBuilder();
    sbB.AppendFormat("{0} {1}", "hi", "there");

    var result = new StringBuilder(sbA.Length + sbB.Length);
    fixed (char *aPtr = GetRawStringData(sbA))
    fixed (char *bPtr = GetRawStringData(sbB))
    {
        //char* resultPtrWritable = resultPtr;
        for (int i = 0; i < result.Capacity; i++)
        {
            if (i < sbA.Length)
                result.Append(aPtr[i]);
            else
                result.Append(bPtr[i - sbA.Length]);
        }
    }

    Console.WriteLine(result.ToString()); // prints: 'Testing - hi there'
}
```

But yeah, it would be nicer if this code was written for you!! (it could also do it in a more efficient way, using `Buffer.BlockCopy` or something like that)

**Comment by AlexRadch** [comment]
Hi, @mattwarren! This code will not work for long StringBuilder because it can have many parts see next fields:
```cs
internal StringBuilder m_ChunkPrevious;      // Link to the block logically before this block
internal int m_ChunkLength;                  // The index in m_ChunkChars that represent the end of the block
internal int m_ChunkOffset;
```

**Comment by mattwarren** [comment]
@AlexRadch, sigh, yes you're right, I didn't look closely enough at the internals of `StringBuilder`. 

My code would need to work in a similar way to the [`StringBuilder` `ToString()`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Text/StringBuilder.cs#L330-L369) method, i.e. loop backwards through the `m_ChunkPrevious` items, adding the data from each one.

**Comment by mattwarren** [comment]
@AlexRadch did you mean to close this? 

I agree that this would be a nice thing to have, so I'd at least like to see what someone from Microsoft thinks before closing it.

My workaround it a bit too much of a hack to be a good solution, plus as you point out it doesn't work in all situations.

**Comment by AlexRadch** [comment]
@mattwarren Append is already tracked by https://github.com/dotnet/corefx/issues/4928, so I close this as duplicate.

**Comment by mattwarren** [comment]
Thanks for the link, I'd missed that issue
