### ISSUE TITLE
Partition morph into separate phases for required expansions and optimizations

### ISSUE THREAD

**Issue by russellhadley** [dotnet/coreclr#8117]
Morph has had a bug tail as well as an issue with unexpected diffs due to the fact that it has expansions required for correctness intermixed with optimizations.   The canonical example of this is the remorphing of expressions after CSE.  It's required for correctness, but the optimizations that are rerun can invalidate VNs and cause diffs requiring extra work.  To reduce this bug tail, as well as give a better handle on throughput the logic that implements the two separate concerns should be separated.
category:correctness
theme:big-bets
skill-level:expert
cost:extra-large

**Comment by mikedn** [comment]
Related/dupe: #4104

**Comment by BruceForstall** [comment]
I'm going to close this as a dup of #4104
