### ISSUE TITLE
Base Interface Method could Not be Found

### ISSUE THREAD

**Issue by efaruk** [dotnet/coreclr#8126]
http://stackoverflow.com/questions/40573675/dotnet-core-could-not-found-base-interface-method

**Comment by MichalStrehovsky** [comment]
`Microsoft.CSharp.RuntimeBinder.RuntimeBinderException` is thrown from System.Dynamic.Runtime and has to do with handling of the C# `dynamic` keyword. If you believe this is a bug in dynamic runtime's method binding, please open an issue in the [dotnet/corefx](https://github.com/dotnet/corefx) repo - that's where the runtime binder lives.
