### ISSUE TITLE
Managed Debugger on Amd64: NativeWalker::Decode() runs into an assert while decoding "inc dword ptr [rax]"

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#8139]
Recently RyuJIT amd64 started generating "inc/dec [mem]" instruction for read-modify-write operations that add or sub 1 (PR https://github.com/dotnet/coreclr/pull/8101)

Here [mem] is any of legal addressing modes permitted.  This lead to an assert while running the following test

```
cd %clr_root%/amd64\devsvcs\tests\RAD\ENC
DDSUITES\SRC\CLR\AMD64\devsvcs\tests\tools\runtest.exe -mdbg active_edit_go_remap_edit_go_remap_step.scr

Assert failure(PID 7808 [0x00001e80], Thread: 22716 [0x58bc]): modrm != NULL

CLR! NativeWalker::Decode + 0x225 (0x00007ffe`75d02cc9)
CLR! DebuggerStepper::TrapStep + 0x247 (0x00007ffe`75cf1913)
CLR! DebuggerStepper::TriggerSingleStep + 0x323 (0x00007ffe`75cf516f)
CLR! DebuggerController::ScanForTriggers + 0xB0D (0x00007ffe`75cee6b1)
CLR! DebuggerController::DispatchPatchOrSingleStep + 0x937 (0x00007ffe`75ce8ebb)
CLR! DebuggerController::DispatchNativeException + 0x99A (0x00007ffe`75ce83ca)
CLR! Debugger::FirstChanceNativeException + 0x4ED (0x00007ffe`75cadb35)
CLR! CLRVectoredExceptionHandlerPhase2 + 0x14E (0x00007ffe`75087a86)
CLR! CLRVectoredExceptionHandler + 0x1E7 (0x00007ffe`7508791b)
CLR! CLRVectoredExceptionHandlerShim + 0xEC (0x00007ffe`75088070)
    File: e:\dd\projectk\src\ndp\clr\src\debug\ee\amd64\amd64walker.cpp Line: 137
    Image: E:\DD\PROJECTK\SRC\DDSUITES\SRC\CLR\AMD64\devsvcs\tests\RAD\ENC\bin\multi1.exe
```

On Debugging it was traced to an assert in amd64walker.cpp!NativeWalker::Decode().  

`_ASSERT(modrm != NULL);
`
It turns out that even jmp and call also have the same opcode byte as inc/dec r32/mm32.  Looks like debugger code (in Amd64Walker.cpp!NativeWalker::Decode) is making the assumption that if the opcode is FF then it is a jmp/call and hence modR/M byte would not be a zero. The repro case has the following instruction whose ModR/M byte is zero and hence the assert.

```
Inc dword ptr [rax]

The instruction bytes are:
Opcodes = FF
ModR/M = 00

```
Ignoring the assert and proceeding further would cause NativeWalker::Decode not to consider the opcode as jmp/call correctly and the test passes.  But it is not clear whether Decode correctly handles inc/dec [mem] correctly for all possible addr modes.

As a workaround, RMW optimization in RyuJIT is disabled while generating debuggable code or when in edit-and-continue mode.  But as per @noahfalk, optimized code debugging is a supported scenario and hence we need to verify whether NativeWalker::Decode works correctly for all possible addr modes in case of inc/dec.

**Comment by sivarv** [comment]
@mikem8361 - For desktop debugger test to pass on amd64, I am making a JIT side fix to not to emit inc/dec [mem] when asked to generate debuggable code. PR https://github.com/dotnet/coreclr/pull/8138/files

Post this PR is merged, if you need to repro, update the if-condition to remove `"!compiler->opts.compDbgCode"` and try running the above mentioned debugger test.

**Comment by mikem8361** [comment]
Fixed.
