### ISSUE TITLE
GetHashCode should not box enums in generic methods.

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#8143]
Relevant comment: https://github.com/dotnet/corefx/pull/8964#r65099479

Currently, whenever `GetHashCode` is called on an enum in a generic context, it is boxed and a virtual call to `object.GetHashCode` is made. For example:

```cs
private int GetHashCode<T>(T obj) => obj?.GetHashCode() ?? 0;
```

generates [this output](https://gist.github.com/anonymous/9175d70ec5e9c02b3877d6e63e591591). It would be nice if the JIT could recognize when it is enums, & avoid making such boxes. Then, we could safely improve [`ValueTuple.GetHashCode` perf](https://github.com/dotnet/corefx/blob/master/src/System.ValueTuple/src/System/ValueTuple/ValueTuple.cs#L1802-L1809) by using `obj?.GetHashCode() ?? 0` instead of `EqualityComparer<T>.Default.GetHashCode`, knowing that the former version will never box.

**Comment by omariom** [comment]
Is it the last reason to use `EqualityComparer<T>.Default.GetHashCode`?

**Comment by jamesqo** [comment]
@omariom, I believe so. If you look at all of the `GetHashCode` implementations for https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/EqualityComparer.cs besides the enum comparers, they all essentially do the equivalent of `obj?.GetHashCode() ?? 0`.

**Comment by MichalStrehovsky** [comment]
@jamesqo What CoreCLR are you running with? I would have expected #7895 to avoid the boxing.

**Comment by jamesqo** [comment]
@MichalStrehovsky, nice! That dump was from a couple of months ago, when I was working on the ValueTuple PR. It looks like your change exactly addresses this issue:

```asm
; Assembly listing for method Program:GetHashCode(int):int
; Emitting BLENDED_CODE for X64 CPU with AVX
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  3,   3  )     int  ->  rcx         ld-addr-op
;* V01 tmp0         [V01    ] (  0,   0  )     ref  ->  zero-ref   
;# V02 OutArgs      [V02    ] (  1,   1  )  lclBlk ( 0) [rsp+0x00]  
;
; Lcl frame size = 0

G_M55903_IG01:

G_M55903_IG02:
       8BC1                 mov      eax, ecx

G_M55903_IG03:
       C3                   ret      

; Total bytes of code 3, prolog size 0 for method Program:GetHashCode(int):int
; ============================================================
```

Happily closing.

**Comment by omariom** [comment]
@jamesqo  Now you can get rid of `EqualityComparer<T>.Default.GetHashCode` in HashSet and Dictionaries :)

**Comment by MichalStrehovsky** [comment]
@omariom @jamesqo But note that other runtimes might not have the optimization (specifically, the desktop CLR, or the .NET Native for UWP apps compiler), so CoreFX code that is expected to run elsewhere should probably still not rely on it.

**Comment by jamesqo** [comment]
@MichalStrehovsky I see, ok. Do you know when this optimization might be implemented on those platforms you mentioned (desktop, .NET Native for UWP)?

**Comment by MichalStrehovsky** [comment]
Desktop has been shipping with this for the past 14 years and the checkin bar is really high. "Never" would be a safe answer since this is just a perf improvement that can be worked around.

I have a PR out to fix it in CoreRT some time soon. There are no specific plans for .NET Native for UWP, but that should pick up the CoreRT fix at some point. Hard to give time estimates.

**Comment by jamesqo** [comment]
> Desktop has been shipping with this for the past 14 years and the checkin bar is really high. "Never" would be a safe answer since this is just a perf improvement that can be worked around.

@MichalStrehovsky Thanks for this info. Do you think I should ever submit the PR then? Technically, it would not "rely" on this optimization; it would just perform worse for a (minority) use case on certain runtimes. Although, I could see a tuple with enums as the key in a dictionary being a plausible scenario.

**Comment by mburbea** [comment]
Can't this be solved with `#ifdef`? If you're on CoreCLR use the simple gethashcode, and if you're not use the comparer?
