### ISSUE TITLE
netcoreapp1.1: An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Security.Cryptography.X509Certificates.dll

### ISSUE THREAD

**Issue by kae** [dotnet/coreclr#8148]
[repro.zip](https://github.com/dotnet/coreclr/files/595994/repro.zip)

Find attached repro for quite strange behavior
You need to import pfx from archive to LocalUser/My container first.

Then if you set `var fail = true;` you will get 'System.ExecutionEngineException' when trying to create certificate from rawData byte array.

When `var fail = false;` everything is working like a charm (difference is loading any certificate from pfx file).

Changing netcore version to 1.0 will result in nonissue with any value for `fail` variable.

**Comment by terrajobst** [comment]
@karelz and @bartonjs, can you guys take a look?

**Comment by bartonjs** [comment]
Worked on Ubuntu 16.04; except for loading the file (due to the path being `@".\demo-svc.pfx"` -- using the wrong directory separator).

So I guess this is on Windows?

**Comment by kae** [comment]
Yeah, sorry.
Targeting windows

**Comment by bartonjs** [comment]
... confirmed on Windows Server 2012 R2.

I broke apart the failing line (`new X509Certificate2(cert.RawData)`) into two lines, and it's the constructor that's failing.

@JohnChen0: This didn't repro under with `COMPlus_ReadyToRunExcludeList=System.Security.Cryptography.X509Certificates`, so it sounds like an R2R problem to me (that being the extent of my diagnosis).

Is there enough information here for you to investigate?

**Comment by JohnChen0** [comment]
I'll take a look.

**Comment by kae** [comment]
Is there a possibility of some workaround that is more subtle than loading some random pfx from disk at start of the program?

**Comment by gkhanna79** [comment]
Workaround is described in https://github.com/dotnet/corefx/issues/13814 and appears to help.

@JohnChen0 is looking into a fix for 1.2.0 and will also look into bringing it in for 1.1.1.

**Comment by JohnChen0** [comment]
Fixed with PR #8230.

**Comment by karelz** [comment]
Documented in known issues: https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1-known-issues.md#systemexecutionengineexception-in-systemsecuritycryptographyx509cerificatesdll-on-windows
