### ISSUE TITLE
Update build + run instructions to use the new package feed and versions

### ISSUE THREAD

**Issue by richlander** [dotnet/coreclr#816]
These instructions are now wrong: https://github.com/dotnet/coreclr/blob/master/Documentation/get-dotnetcore-windows-nuget.md

The new feed: https://www.myget.org/F/dotnet-core

New versions are displayed here: https://www.myget.org/gallery/dotnet-core

**Comment by weshaggard** [comment]
@richlander what is this new feed for? Who do we expect to actually use it?

**Comment by richlander** [comment]
I am putting together binary distribution instructions for the product/repo. The instructions offered on the repo will have a bias to myget, since it is much closer to the latest version of the code. NuGet.org instructions will also be offered.

In terms of "who", I expect everyone who wants to use our product on OS X and Linux to use these instructions, unless they'd prefer to use the ASP.NET team instructions (which is totally fine) since they are more interested in ASP.NET 5.

Put another way, which feed do you expect .NET Core users to use?

**Comment by davidfowl** [comment]
Bleeding edge man! We can play with fixes on myget (pushing every commit would be great!)

**Comment by ghuntley** [comment]
* MyGet.org for bleeding edge/every build to make lives better for the devs.
* Nuget.org for ```-pre``` style CTP releases to general community when and where needed.
* NuGet.org for ```stable``` releases.

**Comment by KevinRansom** [comment]
@richlander @ellismg  Guys, how are we intended to use this feed?  Are there instructions somewhere.  It would seem as if the nuget packages require nuget 3.0.0 but the latest release of nuget is 2.8.60318.667.  I have spent most of the evening trying to find a nuget.exe for v3.0.0 of nuget and failed.
This packages.config fails
````
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="NUnit" version="2.6.4" />
  <package id="NUnit.Runners" version="2.6.4" />
  <package id="System.Collections" version="4.0.10-beta-22827" />
</packages>
````

In our repo we use
````
nuget\NuGet.exe restore packages.config -PackagesDirectory packages
The 'System.Collections 4.0.10-beta-22827' package requires NuGet client version '3.0' or above, but the current NuGet versio
n is '2.8.60318.667'.
````

Could you move back to be compatible with the released version of nuget, or linking to the correct nuget.exe to use.

Thank you

Kevin

**Comment by ellismg** [comment]
I believe it's expected that you need NuGet 3.0 (or perhaps nightly versions of dnu since they are converging) to consume these packages.  @ericstj can likely tell a story about what you should be doing.

**Comment by ericstj** [comment]
Right now the recommended way to consume these packages is using dnu.cmd from dnx and https://github.com/dotnet/buildtools/.  We are working on building support in msbuild/visual studio.

**Comment by jkotas** [comment]
Not relevant anymore. These instructions have been done number of times since this issue was opened.
