### ISSUE TITLE
SemaphoreSlim can throw an ArgumentNullException during a cancel

### ISSUE THREAD

**Issue by rchiodo** [dotnet/coreclr#8177]
I'm using a BlockingCollection<ConcurrentQueue> and a call to TryTake(out value, timeout, cancelToken) will crash with an ArgumentNullException during a cancel. 

It looks to me like SemaphoreSlim is not handling cancel after it's been disposed.

The callstack of the crash is like so:

  at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at System.Threading.SemaphoreSlim.CancellationTokenCanceledEventHandler(Object obj)

**Comment by rchiodo** [comment]
In the debugger the m_lock is null:

 private static void CancellationTokenCanceledEventHandler(object obj)
        {
            SemaphoreSlim semaphore = obj as SemaphoreSlim;
            Contract.Assert(semaphore != null, "Expected a SemaphoreSlim");
            lock (semaphore.m_lockObj)
            {
                Monitor.PulseAll(semaphore.m_lockObj); //wake up all waiters.
            }
        }

**Comment by stephentoub** [comment]
@rchiodo, it sounds like something in your code disposed the BlockingCollection while it was still being used?

**Comment by rchiodo** [comment]
Yes. It looks like the canceltoken has a registered callback that disposes the BlockingCollection. So it depends upon the order that the cancel callbacks are called. 

Shouldn't the semaphoreslim be throwing an ObjectDisposedException in this case?

**Comment by danmosemsft** [comment]
Per [issues guidance](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/IssuesFeedbackEngagement.md) 
> If in the managed code log it in the CoreFX repo even if the code is in this CoreCLR repo (ie., in mscorlib/System.Private.Corelib). The reason for this is we sometimes move managed types between the two and it makes sense to keep all the issues together.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #14320](https://github.com/dotnet/corefx/issues/14320) via [**ZenHub**](https://www.zenhub.com/)
