### ISSUE TITLE
Windows Arm64 infrastructure: Update the lstFile to get GCStress and JitStress job green

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#8192]

**Comment by sdmaclea** [comment]
@jashook I though I saw a patch merge which fixed this

**Comment by danmosemsft** [comment]
@sdmaclea @jashook is this plannedfor the 2.0 release? if not please move to future.

**Comment by sdmaclea** [comment]
@BruceForstall @jashook I thought this was already done

**Comment by BruceForstall** [comment]
I'm going to call this done. If there are jobs that aren't clean (gcstress is really hard to get 100% repeatably clean), we can open new issues.
