### ISSUE TITLE
MSBuild error MSB4025 with .net core 1.1 and 1.0.1

### ISSUE THREAD

**Issue by jphellemons** [dotnet/coreclr#8200]
Hi, I cross posted this from [SO ](http://stackoverflow.com/questions/40676096/msbuild-error-msb4025-in-visual-studio-code) because I think that this has a better reach for .net core related things. Please forgive me if it is in the wrong repo. Just point me to the right one.
I keep getting the message that my project.json is broken but a SO user has verified that it is valid. So I have no idea how to troubleshoot this and have tried to fall back to cli instead of vs code, but failed. 
Here is my current project.json:

````
{
  "version": "1.0.0-*",
  "buildOptions": {
    "preserveCompilationContext": true,
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "publishOptions": {
    "include": ["Views", "web.config"]
  },
  "dependencies": { 
    "Newtonsoft.Json": "9.0.1",
    "System.Security.Cryptography.Hashing.Algorithms" : "4.0.0-beta-23225",
    "System.Xml.XmlSerializer" : "4.3.0-preview1-24530-04",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        },
        "Microsoft.AspNetCore.Server.Kestrel" : "1.1.0",
        "Microsoft.AspNetCore.Mvc" : "1.1.0",
        "Microsoft.AspNetCore.StaticFiles": "1.1.0",
        "Microsoft.Extensions.Logging": "1.1.0",
        "Microsoft.Extensions.Logging.Console": "1.1.0",
        "System.Net.Http": "4.3.0"
      },
      "imports": "dnxcore50"
    }
  }
}
````

and this is the exact message:
**MSBUILD : error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1**

**Comment by gkhanna79** [comment]
Thank for filing this @jphellemons.

@piotrpMSFT Is CLI the right repo to move this issue for the right folks to look at?

**Comment by piotrpMSFT** [comment]
This is a fairly well known issue. Please look at https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md. I hope the doc helps, but if there are still concerns please do reopen this at https://github.com/dotnet/cli

**Comment by Matticusau** [comment]
Just a point as I came across with my repo. In my case I am building my website from a subdirectory of the repo. The **global.json must exist in the root of the repo**, not the site to be built.
