### ISSUE TITLE
Changing AsyncLocal value allocates a new Dictionary object each time

### ISSUE THREAD

**Issue by BertanAygun** [dotnet/coreclr#8204]
When using AsyncLocal in desktop CLR (both 4.6.1 and 4.6.2), each time value is changed from user code a new dictionary object is allocated to clone the current local values in execution context. This causes large number of allocations in scenarios where async local value is changed frequently and may trigger additional GCs. For applications that have few async local instances, is it possible to use a simpler struct and use Dictionary for other cases to reduce memory pressure?

**Comment by BertanAygun** [comment]
@ericstj FYI

**Comment by ericstj** [comment]
Relevant code is here: https://github.com/dotnet/coreclr/blob/2246c1ff94cbd84df83e5308c81a1d1018c3f154/src/mscorlib/src/System/Threading/ExecutionContext.cs#L297

It looks like its already seen [some improvements](https://github.com/dotnet/coreclr/commit/9bc06f7e534a1989911d795528737d767c2b408d) over desktop which we should look at porting back.

I wonder if we could have a pool of dictionaries to further improve this.

/cc @stephentoub

**Comment by stephentoub** [comment]
cc: @kouvel 

A pool would be interesting, but I think it would be challenging here, as to my knowledge we don't have a great way to track the lifetimes of these objects and return them to the pool only when we're sure no one else is using them.

I think the proposal is a reasonable one to explore.  The current design assumes that the primary operations will be flowing values and accessing values, and that comparatively changing values will be infrequent; thus, it optimizes for making flowing and look-ups cheap at the expense of making changes more expensive.  Obviously if you then have a scenario that violates those assumptions and makes very frequent changes, this leads to perf problems.  We could explore using a persistent or immutable collection (e.g. something like ImmutableDictionary), though that will likely make look-ups more expensive.  We could also explore switching between more than one map implementation based on the number of stored elements, starting with something with a low-memory footprint when the number of entries is small, and then graduating to a dictionary when it's larger... that'd add a fixed overhead to lookups (e.g. a type check, branch, etc.), but it would significantly reduce the GC impact when there are only a few items.

**Comment by stephentoub** [comment]
@BertanAygun, can you give me a better sense for the scenario, how many AsyncLocals you typically have flowing around, etc.?

**Comment by BertanAygun** [comment]
@stephentoub, this came up during a perf investigation in Visual Studio. We typically have 1 or 2 instances of AsyncLocal active in the scenario we were looking at.

**Comment by stephentoub** [comment]
Thanks
