### ISSUE TITLE
Remove usage of hash_map/hash_set

### ISSUE THREAD

**Issue by DickvdBrink** [dotnet/coreclr#821]
I changed my buildscripts to generatie VS2015 project files (to fix issue #30) but I found some issues when compiling.
Adding the `_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS` Will probably fix my warming (haven't tried it yet) but I just wanted to let you guys know.

Usage: 
[util.h](https://github.com/dotnet/coreclr/blob/838807429a0828a839958e3b7d392d65886c8f2e/src/ToolBox/SOS/Strike/util.h#L2860)
[decimal.h](https://github.com/dotnet/coreclr/blob/465721555eda899a06bc91fe37bc47c0a1adbdd4/src/debug/daccess/dacimpl.h#L29)

Source: http://blogs.msdn.com/b/vcblog/archive/2014/06/06/c-14-stl-features-fixes-and-breaking-changes-in-visual-studio-14-ctp1.aspx
>In VS14, we're going to deprecate `<hash_map>` and `<hash_set>`.  Including them will emit a static_assert of the form "`<hash_map>` is deprecated and will be REMOVED. Please use `<unordered_map>`. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this warning."

**Comment by DickvdBrink** [comment]
Btw, this is something I'm willing to fix (if that is oke with you guys)

**Comment by jkotas** [comment]
It would be great if you can fix it. Thank you!
