### ISSUE TITLE
Buffer.BlockCopy data corruption on last byte when used with char arrays

### ISSUE THREAD

**Issue by gwicksted** [dotnet/coreclr#8214]
NOTE: I know using `Buffer.BlockCopy` for copying `char`s like this is a bad idea (especially since the stream was UTF-8) -- this was a mistake after changing my file reading function to use a `TextReader` instead of a `Stream`.  However, all chars were within ASCII (7 bit) range with the only non-printables being '\r' and '\n' so I do not believe it conformed to spec which is why I am reporting the issue here.

PROBLEM: When used with `char[]` to `char[]` (copying exactly `496` of `4096` length) resulted in the last `char` copied from `buffer` to `copy` being null (`0x00`) instead of space (`0x32`).

Framework: netcoreapp1.0 Any CPU running with the VS2015u3 debugger on .net core 1.0.0-rc2-002339 and when running via dotnet run in powershell (all on Windows 10 x64).

```C#
char[] buffer = new char[4096];

// reader is StreamReader reading from a FileStream
int read = await reader.ReadAsync(buffer, 0, 4096).ConfigureAwait(false);

// read = 496 (the entire file)

char[] copy = new char[read];

// demonstrates error of copy[495] == 0x00
Buffer.BlockCopy(buffer, 0, copy, 0, read);

// works correctly since copy[495] == ((char)0x32) == buffer[495]
Array.Copy(buffer, copy, read);

// also works correctly and results in an array of bytes which is an identical length:
var bytes = Encoding.UTF8.GetBytes(buffer, 0, read);
```

**Comment by stephentoub** [comment]
StreamReader.ReadAsync returns the number of chars read, not the number of bytes read, yet BlockCopy expects the last argument to be the number of bytes, so you're only copying 496 bytes, not 496 chars (which is 992 bytes).

Looks like part of the problem here may be that the StreamReader.ReadAsync docs are wrong, as they state for the return value that it's in bytes.

**Comment by gwicksted** [comment]
Hi @stephentoub can't believe I missed that... you're absolutely right.  Also, you are correct StreamReader's docs are misleading for newcomers.  Guess it wasn't a total bust!

**Comment by stephentoub** [comment]
@mairaw, how do we go about fixing these docs?

**Comment by mairaw** [comment]
I'll reopen this issue so we can get the API reference docs fixed @stephentoub. The API docs are kind of a hack in the moment until we get the full open source solution in place.

**Comment by mairaw** [comment]
Ah can someone reopen this one and assign this one to me? I thought this was in the docs repo.

**Comment by stephentoub** [comment]
Done. Thanks.

**Comment by AlexGhiondea** [comment]
@mairaw is this something you are still looking into? Is this required for 2.0?

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/docs #1888](https://github.com/dotnet/docs/issues/1888) via [**ZenHub**](https://www.zenhub.com/)
