### ISSUE TITLE
.NetCore on Linux (Mint 18/Ubuntu 16.04) fails to compile just created F# project

### ISSUE THREAD

**Issue by palutz** [dotnet/coreclr#8217]
Hi,
trying to play a bit with F# and .NetCore (1.1). I've read F# is supported so I was trying it but with no luck.
This is my system:

> $ cat /proc/version
> Linux version 4.4.0-36-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016

and 

> $ dotnet --version
> 1.0.0-preview2-1-003177

I create my new app like this:

> $ dotnet new -l F#
> $ dotnet restore
> log  : Restoring packages for /home/palutz/Project/fsharp/core1/project.json...
> log  : Restoring packages for tool 'dotnet-compile-fsc' in /home/palutz/Project/fsharp/core1/project.json...
> log  : Writing lock file to disk. Path: /home/palutz/Project/fsharp/core1/project.lock.json
> log  : /home/palutz/Project/fsharp/core1/project.json
> log  : Restore completed in 2090ms.
> 
but when I try to run it (without any modification, just to see the classic "Hello World") I got this:

> $ dotnet run
> Project core1 (.NETCoreApp,Version=v1.1) will be compiled because expected outputs are missing
> Compiling core1 for .NETCoreApp,Version=v1.1
> The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
>   - Check application dependencies and target a framework version installed at:
>       /usr/share/dotnet/shared/Microsoft.NETCore.App
>   - The following versions are installed:
>       1.1.0
>   - Alternatively, install the framework version '1.0.0'.
> /usr/share/dotnet/dotnet compile-fsc @/home/palutz/Project/fsharp/core1/obj/Debug/netcoreapp1.1/dotnet-compile.rsp returned Exit Code 131
> 
> Compilation failed.
>     0 Warning(s)
>     0 Error(s)
> 
> Time elapsed 00:00:00.3389032
> 

And I attached the project.json (converted to .txt) to help.

[project.json.txt](https://github.com/dotnet/coreclr/files/602408/project.json.txt)

Any suggestion how to solve this?

Thanks.

**Comment by jkotas** [comment]
@palutz Could you please open this issue in https://github.com/microsoft/visualfsharp instead?

cc @KevinRansom

**Comment by palutz** [comment]
@jkotas sure!
