### ISSUE TITLE
Build cannot detect CMake with both x86 and x64 versions installed

### ISSUE THREAD

**Issue by lggomez** [dotnet/coreclr#8221]
The following line in [probe-win](https://github.com/dotnet/coreclr/blob/master/src/pal/tools/probe-win.ps1#L31) will fail to resolve the CMake path when there are multiple versions installed:

```powershell
$inPathPath = (get-command cmake.exe -ErrorAction SilentlyContinue).Path
```

If we have installed both x86 and x64 versions of cmake, there will be 2 command definitions:

```
CommandType     Name                                                Definition
-----------     ----                                                ----------
Application     cmake.exe                                           C:\Program Files\CMake\bin\cmake.exe
Application     cmake.exe                                           C:\Program Files (x86)\CMake\bin\cmake.exe
```

If there is no strict requirement for the cmake version to use, replacing the line by the following code will fix this issue:

```powershell
  $inPathPath = (get-command cmake.exe -ErrorAction SilentlyContinue)
  
  if ($inPathPath.Length -gt 1) {
	$inPathPath = $inPathPath[0].Path
  } else {
	$inPathPath = $inPathPathPath
  }
```

**Comment by gkhanna79** [comment]
CC @wtgodbe

**Comment by lggomez** [comment]
I re-added the fix in a new PR, last time I lagged behind the build checks so I could not read the logs, but I guess it was a formatting issue that prevented the PR from being merged
