### ISSUE TITLE
Question on _TARGET_X86_ for x86/Linux

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#8222]
x86 port for Windows 32 uses `_TARGET_X86_` as compile directive. Some codes have also `_MSC_VER` but not all. I would like to know a good way to enable also for x86 Linux.
To enable also for Linux.
1. Should I use `_TARGET_X86_` and then inner block with `_MSC_VER` or else block ?
2. Or, maybe `_TARGET_X86_ && _MSC_VER` for Windows and `_TARGET_X86_ && LINUX32` for Linux after adding `LINUX32` ? Or maybe `PLATFORM_UNIX` ?
3. Can I add `_TARGET_X86_WIN32_` and `_TAGET_X86_LINUX_` and change all current codes? (maybe too many changes?)

Or is there other way to separate codes between Windows and Linux ?

**Comment by seanshpark** [comment]
cc @janvorli , @jkotas, @gkhanna79, @lemmaa

**Comment by jkotas** [comment]
You should use `_TARGET_X86_`.

`_MSC_VER` is meant for code specific to Microsoft Visual C++ compiler. `PLATFORM_UNIX` is meant for code specific to Unix platform. Another one is `FEATURE_PAL` - it is meant for code specific to the PAL adaption layer that we use on non-Windows platforms. So which one to use depends on the context.

**Comment by seanshpark** [comment]
OK, so then I should use 
- `_TARGET_X86_` and `WIN32` for Windows / `_TARGET_X86_` and `PLATFORM_UNIX` for Linux.
- use also `FEATURE_PAL` for PAL codes

**Comment by janvorli** [comment]
@seanshpark Please note that you will very likely not need to distinguish between Windows and Linux. The PAL is Unix only and the rest of the runtime should be platform agnostic (unless there is something that cannot be handled that way).

**Comment by seanshpark** [comment]
> The PAL is Unix only and the rest of the runtime should be platform agnostic

I sometimes forget this important fact. Thanks for reminding :)

**Comment by seanshpark** [comment]
I think this issue can be closed.

**Comment by seanshpark** [comment]
For the record, it is better to use `!defined(FEATURE_PAL)` for x86/Linux (https://github.com/dotnet/coreclr/pull/8246#discussion_r89155930)

**Comment by janvorli** [comment]
@seanshpark right, I am sorry for not mentioning it in my reply to your question here.
