### ISSUE TITLE
.net core 1.1 upgrade.

### ISSUE THREAD

**Issue by asadsahi** [dotnet/coreclr#8225]
I also installed VS 2017 RC and opend my project, which added csproj file. I deleted that asuming that project.json will still work but getting this error:

AspNetCoreSpa.xproj(8,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.0-preview3-004056\Extensions
\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file ex
ists on disk.

**csproj, xproj, project.json. The whole story is really really confusing.**

Any simple way to upgrade to .net 1.1 from 1.0?

**Comment by karelz** [comment]
@gkhanna79 @weshaggard do you know who could help?

**Comment by gkhanna79** [comment]
@piotrpMSFT or @barrytang should be able to help.

**Comment by zidad** [comment]
I have the same, VS2017 broke the build for my current .NET core projects.

**Comment by asadsahi** [comment]
Another observation is that vs2017 isn't upgrading .net 1.0+ to 1.1 projects properly. Gives an error.

Also, question for some experts, Is .net 1.1 replacing project.json to csproj? The reason I asked if we create a new .net core web application in VS 2017, it doesn't create a project.json, instead puts all the dependencies inside .csproj file. Another dilima for VS code users at thint point in time, that csproj based projects don't work.?

**Comment by natemcmaster** [comment]
If you want to stick with project.json for now, use the .NET Core SDK preview2. Preview3 replaced project.json with MSBuild (.csproj).

> Any simple way to upgrade to .net 1.1 from 1.0?

You can still use project.json. See https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-1-1/. This shows how to upgrade to .NET Core 1.1 with project.json tooling.

> csproj, xproj, project.json. The whole story is really really confusing.

Hopefully this overview will help: https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/.

**Comment by asadsahi** [comment]
Thanks @natemcmaster a little comforting after reading these articles.

Any way to update/add nuget packages in VS code after migrating to csproj or work in progress? Will start migration now.

**Comment by natemcmaster** [comment]
> Any way to update/add nuget packages in VS code after migrating to csproj or work in progress? 

The feature has been requested but is not implemented yet. cref https://github.com/Microsoft/vscode/issues/9211

**Comment by gkhanna79** [comment]
This issue not applicable for CoreCLR repo. Any concerns closing this?

**Comment by tarekgh** [comment]
I am closing this one here. @natemcmaster  could you please move the issue to any other repro as this issue not applicable to this repo?

**Comment by natemcmaster** [comment]
> could you please move the issue to any other repro as this issue not applicable to this repo?

I'm not the issue author. @asadsahi if you are still having issues, try https://github.com/dotnet/sdk.
