### ISSUE TITLE
WSL Ubuntu 16: On resume application throws AccessViolationException and quits.

### ISSUE THREAD

**Issue by rajkumar42** [dotnet/coreclr#8228]
Configuration:
Windows RS2 with “Bash on Ubuntu on Windows”  installed. 
Install "dotnet cli" on WSL. Reproduces in preview2 and preview4. 

Repro steps:
Copy clrdbg to user on WSL.
Run a simple application through VSCode, using pipe transport from windows host.
Set a breakpoint. 
F5 to hit the breakpoint.
Don't remove the breakpoint. F5 to resume execution.

Expected:
Application resumed execution.

Current:
AccessViolationException is thrown and application quits. 
Note: Enable "All Exceptions" in VSCode to catch the AccessViolationException.

**Comment by lt72** [comment]
@rajkumar42: does this still repro?

**Comment by rajkumar42** [comment]
No it does not anymore. Windows folks identified it as a bug in WSL and fixed it in RS2.
