### ISSUE TITLE
Q) x86/Linux, stdcall calling convention ignored on variadic function

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#8248]
While working on x86/Linux, I get this error,
```
coreclr/src/pal/prebuilt/inc/xclrdata.h:1020:25: 
      error: stdcall calling convention ignored on variadic function
      [-Werror,-Wignored-attributes]
        virtual HRESULT STDMETHODCALLTYPE ErrorPrintF(
                        ^
coreclr/src/pal/inc/rt/palrt.h:260:30: note: expanded from macro 'STDMETHODCALLTYPE'
#define STDMETHODCALLTYPE    __stdcall
                             ^
coreclr/src/pal/inc/pal_mstypes.h:43:39: note: expanded from macro '__stdcall'
#define __stdcall      __attribute__((stdcall))
```
This code is wrapped with
```
#ifndef _MSC_VER
#ifdef __i386__
```
so seems only for x86/Linux case.

Can I change like this?
```
- #define __stdcall      __attribute__((stdcall))
+ #define __stdcall
```

**Comment by seanshpark** [comment]
CC @janvorli , @jkotas , @gkhanna79

**Comment by jkotas** [comment]
`__stdcall` needs to stay defined as `__attribute__((stdcall))`.

I would fix this by changing STDMETHODCALLTYPE to STDMETHODVCALLTYPE on the affected method in xclrdata.h.

**Comment by seanshpark** [comment]
Thanks, I'll use `STDMETHODVCALLTYPE` for variadic functions.

**Comment by seanshpark** [comment]
There's a line
```
/* this ALWAYS GENERATED file contains the definitions for the interfaces */
``` 
on top of the file. Is it ok to change manually?

**Comment by jkotas** [comment]
This fix requires exception from this rule - there is no better way.

In case that this file needs to be regenerated in future, the change will need to be reapplied manually. I believe that we have a few other similar places in these auto-generated files.

**Comment by seanshpark** [comment]
OK, got it. Thank you.
