### ISSUE TITLE
coreclr(including corefx) contains GPL3.0 ?

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/coreclr#8261]
I am running black duck protex tool to figure out open source licenses on coreclr/fx.
Protex said that some files have GPL(including LGPL) snippets.
Is there any code of coreclr/fx which has been relicensed to MIT without checking GPL relicense issues ?

**Comment by jkotas** [comment]
cc @richlander @martinwoodward

**Comment by richlander** [comment]
We want to take a look at that. Please start a conversation with me on mail so that we can move forward quickly.

**Comment by lemmaa** [comment]
For reference, in some cases it was determined that someone used source code published by Microsoft in SDK format for their own software and applied the GPL license. This is not a problem in this case. I think most will be false alarms. However, there are too many GPL cases and it is difficult to identify each one with outdated code, so we asked the coreclr team for help.

**Comment by richlander** [comment]
OK. Thanks. Thanks for investigating this case. Going forward, we'll work with you on any other cases you find. Thanks.
