### ISSUE TITLE
Replacing dotnet publish-ed binaries with locally built coreclr ones results in a TypeLoadException.

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#8266]
I have not been able to get a console app working with locally-built binaries since I rebuilt coreclr a week ago... running the app after `dotnet publish` works fine, but after copying over a build of the repo I get a TypeLoadException if the app has a `Console.WriteLine`.

```
$ run_app
125
117
117
118
118
120
128
129
131
128

james@DESKTOP-B1DARHA MINGW64 ~/Code/tests/Dotnet (master)
$ copy_coreclr -t publish

james@DESKTOP-B1DARHA MINGW64 ~/Code/tests/Dotnet (master)
$ run_app

Unhandled Exception: System.TypeLoadException: Could not load type 'System.IO.TextWriter' from assembly 'System.IO, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Console.WriteLine(Int64 value)
   at ConsoleApplication.Benchmarker.Run(Int32 times, Action code)
   at ConsoleApplication.Program.Main()
```

Not sure what's causing this. I tried a bunch of different things, including using the version of the CLI that comes with the repo (in `Tools/dotnetcli/`) instead of the one on my machine, changing my `Microsoft.NETCore.App` reference from 1.0.0 -> 1.1.0, doing a clean build, etc. Unfortunately, it fails with the same error each time.

[Here](https://github.com/jamesqo/Dotnet/blob/eaf0ce41868cafb6ed7a50f62bbe66bfa7560374/project.json) is the project.json, along with all of the other files, of my app.

I'm on Windows 10 64-bit.

**Comment by jkotas** [comment]
Could you please try project.json linked in step 3 in https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md?

There is no good published build of Microsoft.NETCore.App metapackage for netcoreapp1.1 currently, so there needs to be explicit list of assemblies.

**Comment by jamesqo** [comment]
@jkotas Thank you for answering. I followed the instructions in the guide carefully and step-by-step. However, it seems to only yield a different exception when I try `dotnet run`:

```cs
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by jkotas** [comment]
This problem is caused by old System.Runtime. I am not sure how you are getting it - either project.json wrong; or there is something wrong with `dotnet restore`.

Anyway, here is something else that you can try:

1. Run release build, including tests, and start the test run. You can abort it before all tests are finished, but wait for the tests start running and finishing.

```
build.cmd release
cd test
runtest.cmd release
```

2. `\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root` will have the freshly built coreclr.dll together with a matching set of the framework assemblies. You can either copy them over to your published test app; or you can run `corerun <path to your test exe>` from there.

**Comment by jamesqo** [comment]
@jkotas Thanks for your responses. I combined both of your suggestions-- using the CLI from `Tools\dotnetcli\` and using the provided project.json. Seems to work now, thanks!
