### ISSUE TITLE
Local GC: make the rest of diagnostics work

### ISSUE THREAD

**Issue by Maoni0** [dotnet/coreclr#8268]
items left -

DAC - currently the dac vars' RVAs in clr.dll/coreclr.dll are computed and embedded in mscordacwks.dll. this needs to be done for gc.dll as well.

stress log - formatOffset needs to be taken care of for gc.dll.

ETW - need the GC event manifest to be defined on the gc side and need to have the function that actually fires the ETW event exposed on the IGCToCLR interface.

perf counters - there are not many places that do stuff with perf counters on the gc side. it should just be a matter of exposing a method or two on the IGCToCLR interface for the gc side to call

**Comment by Maoni0** [comment]
The 2 big motivations for this project were

1) to allow for easier deployment. On desktop CLR giving folks a build with a new GC feature/fix is quite difficult, even though it should be easy as internal GC changes do not affect interfacing with other components. The easiest way I found was I had to goto the exact branch the customer was using, sync to the version of their clr.dll, do the changes there and give them a clr.dll with the same version, which sounds like a big hassle but it was way less work than trying to get a layout build from the current development branch to work on customer machines.

2) to allow for easier development. Our GC is the same one on all our SKUs (Desktop, coreclr and corert) but different SKUs can move at different paces (and some SKU, by that I really mean Desktop, has many, many different branches that move at different paces). Integrating/porting GC changes amongst them can be quite time consuming. By having the GC source only in one location we avoid all this work. Of course we'll have a version system so if the new gc.dll is incompatible with the rest of the runtime you are using we'll let you know that you need to upgrade the other part too. That would happen very rarely though.

**Comment by swgillespie** [comment]
Pr for the DAC work: https://github.com/dotnet/coreclr/pull/9255

Stress log, ETW, and perf counters remain to be done.

**Comment by swgillespie** [comment]
This issue has been superseded by more specific issues.
