### ISSUE TITLE
Getting error while installing the VSTS Agent on Linux RedHat 

### ISSUE THREAD

**Issue by sahithreddyk** [dotnet/coreclr#8279]
Hello,
1. Copied locally downloaded "vsts-agent-rhel.7.2-x64-2.109.1.tar.gz" to the Linux and extracted the contents
2. Executed, ~/$ mkdir myagent && cd myagent
~/myagent$ tar xzf ~/Downloads/vsts-agent-rhel.7.2-x64-2.109.1.tar.gz
3. while running ./config.sh, getting below error and i dint downloaded "libunwind.x86_64" 

Failed to load $/bin/libcoreclr.so, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at $/bin/libcoreclr.so'

Can someone please advise me please

Thanks in advance

**Comment by janvorli** [comment]
@sahithreddyk it seems you have notinstalled the prerequisities as described below:
https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envredhat.md

**Comment by gkhanna79** [comment]
@sahithreddyk Did the above help?

**Comment by danmosemsft** [comment]
I'm going to close, plesae reopen if you still have an issue.
