### ISSUE TITLE
Add non-throwing methods to Convert class

### ISSUE THREAD

**Issue by Alexx999** [dotnet/coreclr#83]
Convert class is the only method to convert boxed values to needed integer type. However, it throws exceptions, so it is too hard to implement behavior that matches simple explicit cast between integer types.
As a solution - add TryXXX methods to Convert class.

Additionally, it would be nice to have option to make Convert behave like explicit cast.
For example, this is valid:
```C#
int a = -1;
int b = (int)(uint)a;
```
But this is not:
```C#
int a = -1;
int b = Convert.ToInt32(Convert.ToUInt32(a));
```
This can be really useful when you process some data as "just some bytes" and you may get either signed or unsigned boxed value at input.
As a possible solution - add overload that accepts second boolean argument and acts like an explicit integer cast.

Example of this problems and required workaround can be seen here:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Enum.cs#L207

**Comment by jkotas** [comment]
Could you please reopen the issue in the CoreFx repo?

From https://github.com/dotnet/coreclr/wiki/Contribution-guidelines

This means that issues regarding new APIs should move to the CoreFx repo where it would go through the normal API review process.
