### ISSUE TITLE
RyuJIT debug dump displays YMM registers on 128 bit AVX instruction instead of XMM registers 

### ISSUE THREAD

**Issue by litian2025** [dotnet/coreclr#8300]
Currently by setting COMPlus_JITDump or COMPlus_JITDisasm on debug build, the RyuJIT debug dump displays YMM registers instead of XMM registers on 128 bit AVX instruction. To be consistent with Intel Architecture manual and WinDbg/SOS output, the JIT debug dump should print YMM registers on 256 bit AVX instruction and XMM registers on 128 bit AVX instruction.

For example, following C# code:

    static Guid s_dt;
    private static void test()
    {
        var dt = new Guid();
        Method1(dt);
    }

RyuJIT generated following related code via COMPlus_JITDisasm setting:

       33C9                 xor      rcx, rcx
       488D45E8             lea      rax, bword ptr [rbp-18H]
       C4E17957C0           vxorpd   ymm0, ymm0
       C4E17A7F00           vmovdqu  qword ptr [rax], ymm0
       C4E17A6F45E8         vmovdqu  ymm0, qword ptr [rbp-18H]
       C4E17A7F45D8         vmovdqu  qword ptr [rbp-28H], ymm0
       488D4DD8             lea      rcx, bword ptr [rbp-28H]
       E8B49CFFFF           call     Program:Method1(struct)

The vmovdqu instruction has 128bit encode version VMOVDQU xmm2/m128, xmm1 and 256bit encode
version VMOVDQU ymm1, ymm2/m256. Above instruction  "C4E17A7F00         vmovdqu  qword ptr [rax], ymm0" is using 128bit encode version (emitter attr is not EA_32BYTE), the encoding code C4E17A7F00 is correct, however, the dump should display the register to be xmm0 instead of ymm0 to avoid misleading.

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by litian2025** [comment]
I like the alternative solution in #8315 since it covers this issue and some other JIT_Disasm issues, once #8315 is merged we can close this issue too.
