### ISSUE TITLE
Will escape analysis and reference count as alternative GC appear in C# 8.0?

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#8313]
As C# 7.0 will be released soon, there's no time to add more features. But there are still many good ideas that has not come true in C# 7.0, so I wonder which of them would be in the roadmap of C# 8.0, such as escape analysis and reference count as alternative GC.

**Comment by masonwheeler** [comment]
That's not a language-level issue.  Replacing the GC would require massive, fundamental changes to the runtime, and to the runtime specification.

**Comment by jkotas** [comment]
Dup of https://github.com/dotnet/coreclr/issues/430 and https://github.com/dotnet/coreclr/issues/1784. You can follow the discussion about these ideas in the existing issues.
