### ISSUE TITLE
Cannot run dotnetcli (aka SDK) on FreeBSD: System.BadImageFormatException: Could not load file or assembly

### ISSUE THREAD

**Issue by DragonSA** [dotnet/coreclr#8316]
# Background
While trying to create a FreeBSD Port (aka package) of dotnet I followed the recommendations of @mellinoe in [dotnet/corefx#10610](https://github.com/dotnet/corefx/issues/10610#issuecomment-237944753) however the resulting dotnetcli does not work due to an unhandled exception of System.BadImageFormatException.  My understanding is managed code (aka .dll files) should be platform agnostic and thus this exception should not occur.  

The steps I performed were (on FreeBSD 11.0-amd64 unless otherwise specified):
1. Compile native part of coreclr v1.1.0
2. Compile native part of corefx v1.1.0
3. Compile native part of core-setup v1.1.0
4. Built System.Private.CoreLib.dll and mscorlib.dll of coreclr v1.1.0 on Windows
5. Replaced the native and managed components from steps 1-4 in the CentOS SDK
6. Ran crossgen on the managed components

The above steps were sufficient to get "helloworld" to run (with corerun and compiled with mono) however corerun is unable to load any dlls from the sdk.  I have automated the above steps, see "Steps to reproduce".  

# Steps to reproduce
(On FreeBSD 11.0: coreclr 1.1.0)
```
# pkg install mono
# git clone https://github.com/DragonSA/dotnet.git
# cd dotnet/dotnet-sdk
# make install
# cd /usr/local/dotnet/bootstrap/shared/Microsoft.NETCore.App/1.0.1
# echo 'using System; class App { public static void Main() { Console.WriteLine("Hello World"); } }' > /tmp/helloworld.cs
# mcs /r:System.Private.CoreLib.dll /o:/tmp/helloworld.exe /tmp/helloworld.cs
# ./corerun /tmp/helloworld.exe
# cd /usr/local/dotnet/bootstrap
# ./dotnet --version
```

# Expected Output
```
Hello World
1.0.0-preview3-003686
```

# Actual Output
```
Hello World
 

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly '/usr/local/dotnet/bootstrap/sdk/1.0.0-preview3-003686/dotnet.dll'. An attempt was made to load a program with an incorrect format.

Abort
```

**Comment by jkotas** [comment]
> My understanding is managed code (aka .dll files) should be platform agnostic

This is not correct assumption, especially for lower level components of the system.

> Built System.Private.CoreLib.dll and mscorlib.dll of coreclr v1.1.0 on Windows

Are you building it using `build.cmd freebsdmscorlib` ?

**Comment by DragonSA** [comment]
On Sunday, 27 November 2016 07:39:32 Jan Kotas wrote:
> > My understanding is managed code (aka .dll files) should be platform
> > agnostic

> This is not correct assumption, especially for lower level components of the
> system.

For example System.Private.CoreLib.dll, mscorlib.dll, or anything using .NET's 
equivalent of CFFI?  Wouldn't that be the content of the dlls, not the format 
or encoding?

> > Built System.Private.CoreLib.dll and mscorlib.dll of coreclr v1.1.0 on
> > Windows

> Are you building it using `build.cmd freebsdmscorlib` ?

Yes, I used `build.cmd freebsdmscorlib`:
```
# grep FreeBSD System.Private.CoreLib.dll mscorlib.dll
Binary file System.Private.CoreLib.dll matches
Binary file mscorlib.dll matches
```

When the two dlls were not for FreeBSD I got a coreclr initialisation error of 
0x8004005 (or something), or the data size mismatch error.

**Comment by DragonSA** [comment]
> > My understanding is managed code (aka .dll files) should be platform
> > agnostic

> This is not correct assumption, especially for lower level components of the
> system.

For example System.Private.CoreLib.dll, mscorlib.dll, or anything using .NET's 
equivalent of CFFI?  Wouldn't that be the content of the dlls, not the format 
or encoding?

> > Built System.Private.CoreLib.dll and mscorlib.dll of coreclr v1.1.0 on
> > Windows

> Are you building it using `build.cmd freebsdmscorlib` ?

Yes, I used `build.cmd freebsdmscorlib`:
```
# grep FreeBSD System.Private.CoreLib.dll mscorlib.dll
Binary file System.Private.CoreLib.dll matches
Binary file mscorlib.dll matches
```

When the two dlls were not for FreeBSD I got a coreclr initialisation error of 
0x8004005 (or something), or the data size mismatch error.

**Comment by jkotas** [comment]
The managed .dlls in the SDK are AOT-compiled for given platform to get better performance. It makes them not usable on other platforms.

**Comment by DragonSA** [comment]
Ah, I see.  It all makes sense now:
```
# file mscorlib.*
mscorlib.dll:    PE32 executable (DLL) (console) Intel 80386 Mono/.Net assembly, for MS Windows
mscorlib.ni.dll: PE32+ executable (DLL) (console) Mono/.Net assembly, for MS Windows
```
(`file` is a bit strange here, showing the pure managed code having "Intel 80386" and the AOT not having any architecture indicator)

This does make bootstrapping a new architecture more difficult.  Does an SDK without AOT-compilation exist?

Closing issue, this isn't a bug.

**Comment by jkotas** [comment]
@bryanar and @ellismg are working on making bootstrapping new architectures easier: https://github.com/dotnet/core/pull/326 . SDK without AOT should be part of the solution.

**Comment by josteink** [comment]
That would very much be a welcome addition. Currently it feels like all the work we invested in *trying* to land proper FreeBSD-support went under the rug the second donet CLI was introduced.

I really like dotnet CLI and consider it a huge improvement for most parts, but that particular issue has had me bugged ever since. Getting it fixed would be a major milestone IMO.

**Comment by DragonSA** [comment]
Thanks for the link to "rover".  I see that work has been successfully
merged into dotnet/core :-).

We already had the equivalent functionality for FreeBSD (DragonSA/dotnet,
see dotnet-sdk) however the limiter remains the SDK used.  The approach
used by dotnet/core#326 relies on a Linux-x64 based SDK (we used the same
approach) and will only work when bootstrapping for Linux-x64 systems and
excludes everything else (i.e. FreeBSD, or arm) since the dlls are AOT
compiled.

All we need is an SDK that is not AOT compiled.  I see that
dotnet/core-setup produces the `shared/` and `host/` directories of the
SDK.  Do you know how to create the `sdk/` directory from the SDK tarball?
