### ISSUE TITLE
build error in arch linux with 1.0.4

### ISSUE THREAD

**Issue by raininja** [dotnet/coreclr#8317]
[  3%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/sharedmemory/sharedmemory.cpp.o
In file included from /home/raijin/build/aur/dotnet-cli/src/coreclr-1.0.4/src/pal/src/sharedmemory/sharedmemory.cpp:9:
/home/raijin/build/aur/dotnet-cli/src/coreclr-1.0.4/src/pal/src/include/pal/malloc.hpp:139:13: error: destructor called on non-final 'SharedMemoryProcessDataBase' that has virtual functions
      but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]

Hey is there an easy fix for this? Or, possibly, a revision that builds? I am not as excited however now that I am aware that .NET framework programs need ported to use .NET core. My goal is to get BoldChat to run natively in Linux environments. . .

**Comment by janvorli** [comment]
@raininja are you sure you have recent sources? The SharedMemoryProcessDataBase was missing the virtual destructor in the past, but it was fixed on September 21.

**Comment by gkhanna79** [comment]
Closing - please reopen if the issue still repros.
