### ISSUE TITLE
RyuJIT is now the default x86 JIT.  Update relevant documentation.

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#8322]
As of aad84026d7c5dc10b877bec263f4456a31584772, RyuJIT is now the default x86 JIT, replacing the LEGACY_BACKEND JIT (built from these sources) and JIT32, which shows up in the official x86 packages from Microsoft.  For now, setting `COMPlus_UseWindowsX86CoreLegacyJit=1` in the environment will make CoreCLR load the older JIT (LEGACY_BACKEND or JIT32) instead.

Update relevant documentation in this repo to indicate the above.

**Comment by FransBouma** [comment]
Are there any performance metrics available for RyuJIT in x86 mode? As x86's JIT was faster than RyuJIT for a long time (e.g. at startup of apps, x86 builds are much faster than x64 builds).

**Comment by RussKeldorph** [comment]
@FransBouma We have some preliminary measurements but aren't ready to publish anything yet.  As we get the correctness issues under control, our focus will shift to measuring the performance differences between RyuJIT/x86 and JIT32 and mitigating the regressions as much as we can.

If you have specific examples of performance regressions, we've love to hear about them, especially if they are easy for anyone to reproduce and analyze.

@dotnet/jit-contrib

**Comment by FransBouma** [comment]
@RussKeldorph I have an AnyCPU compiled complex winforms app and if I start it on x64 windows 8.1 it takes much longer to get up and running than when I start the same app through an x86 compiled stub to make it run on the 32bit CLR. (.NET 4.x both). Is this the kind of difference that will go away (for the better, so x64 performance will get close to x86 perf as it is now) eventually?

**Comment by mikedn** [comment]
> I have an AnyCPU compiled complex winforms app and if I start it on x64 windows 8.1 it takes much longer to get up and running than when I start the same app through an x86 compiled stub to make it run on the 32bit CLR. (.NET 4.x both). 

I think you are confusing RyuJIT x64 with JIT64, the old x64 JIT. It is JIT64 that sometimes has serious performance problems, not RyuJIT.

**Comment by FransBouma** [comment]
@mikedn afaik, RyuJIT is the JIT in .NET 4.6+? i.o.w: if you have that installed (I do) the JIT used is RyuJIT on x64.

**Comment by mikedn** [comment]
> afaik, RyuJIT is the JIT in .NET 4.6+? i.o.w: if you have that installed (I do) the JIT used is RyuJIT on x64.

Yes, it should be enabled in .NET 4.6. But the scenario you are describing (complex winforms app slow to start) seems similar to one that was causing problems in JIT64. It would be interesting if you could profile the application to see what exactly is going on, if it uses RyuJIT and what exactly is slow about it.

**Comment by FransBouma** [comment]
@mikedn Profiling it doesn't really reveal what's slow other than that things take longer to complete, which suggests a CLR/JIT slowdown (but I'm not a CLR expert). RyuJIT is enabled through the registry (HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework UseRyuJIT is set to 1)

**Comment by kaneboy** [comment]
Will RyuJIT be the default x86 JIT in .NET Framework 4.7? Or there is no such plan on .NET desktop side? Thanks!

**Comment by RussKeldorph** [comment]
@kaneboy No such plan at this point.

**Comment by RussKeldorph** [comment]
Also make sure we support [Runtime Configuration File](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/specs/runtime-configuration-file.md) for this setting and open a new issue if we don't.

**Comment by BruceForstall** [comment]
@RussKeldorph it's already supported, using syntax like (and maybe the syntax has changed):
```
{
  "runtimeOptions": {
    "configProperties": {
      "System.JIT.UseWindowsX86CoreLegacyJit": true
    },
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.0.0"
    }
  }
}
```

**Comment by RussKeldorph** [comment]
We'll use this issue as documentation for now.
