### ISSUE TITLE
Can't open System.Private.CoreLib.csproj in VS2017RC

### ISSUE THREAD

**Issue by svick** [dotnet/coreclr#8323]
When I open System.Private.CoreLib.sln in VS2017RC,  System.Private.CoreLib.csproj fails to load, with the following error:

> error  : The required attribute "Remove" is empty or missing from the element <Internal_ResGenDefines>. GenerateSplitStringResources.targets

Removing the offending elements does let me load and build the project successfully (but I don't know if it breaks something else).

The project also works fine unmodified in VS2015, so I don't know if this is an issue in coreclr or in VS2017.

**Comment by danmosemsft** [comment]
@svick works for me in final release. please reopen if still issues.

**Comment by svick** [comment]
Yeah, it opens fine now. Thanks for verifying.
