### ISSUE TITLE
RyuJIT/x86: encoder uses size_t to accumulate encoding bits, but that's not big enough

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#8331]
While enabling x86/Linux, I get this error
```
coreclr/src/jit/emitxarch.cpp:1182:13: error: shift count >= width of type [-Werror,-Wshift-count-overflow]
    regBits <<= 35;
            ^   ~~
1 error generated.
```
This code is assumed to run in AMD64 and block is surrounded with `#ifdef FEATURE_AVX_SUPPORT`

My question is,
1) Can I get any information about shifting 35 bits is about and how to solve this for x86/Linux?
2) Can I disable `FEATURE_AVX_SUPPORT` for x86/Linux?

Thanks in advance.

**Comment by mikedn** [comment]
It looks like that code assumes that `size_t` is 64 bits, if that's the case then this will likely affect Windows x86 as well. Probably nobody noticed any ill effects until now because enabling SSE/AVX on x86 is work in progress.

**Comment by janvorli** [comment]
cc: @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
@seanshpark There's a pretty pervasive problem in the emitter where it uses `size_t` to accumulate the encoding, but that's too small for AVX (and maybe more?). Temporarily, for bring-up, you can disable `FEATURE_AVX_SUPPORT` (and `FEATURE_SIMD` as well). I'll look into fixing the encoder for x86.

**Comment by seanshpark** [comment]
> Temporarily, for bring-up, you can disable FEATURE_AVX_SUPPORT (and FEATURE_SIMD as well)

Thanks @BruceForstall
