### ISSUE TITLE
Endianness comments in BitConverter.DoubleToInt32Bits and Int32BitsToDouble are irrelevant

### ISSUE THREAD

**Issue by sharwell** [dotnet/coreclr#834]
Similar to the comments highlighted in #833, the `BitConverter.DoubleToInt32Bits` and `Int32BitsToDouble` methods contain endianness comments which are almost certainly irrelevant.

* The .NET Framework doesn't support, and is unlikely to ever support, any architecture which uses a different endianness for its internal representation of integers and floating-point numbers.
* The current implementation of this method *does* already work on both little- and big-endian machines, provided the `Contract.Assert` call is not there.

I recommend these comments as well as the calls to `Contract.Assert` be removed, and the documentation updated to explicitly include the following text (or an equivalent variant) stating a precondition that has always existed but was previously undocumented.

> This method assumes the hardward uses the same endianness for integers and floating-point numbers.

**Comment by jkotas** [comment]
I agree that this comment it bogus and should be removed.

**Comment by mgravell** [comment]
I'm happy to remove those comments and assertions - no skin off my nose either way - but: this is my first coreclr PR: what is the usual process in the case of such a question / decision?

**Comment by sharwell** [comment]
@mgravell I understand why you implemented your pull request the way you did, and believe it makes sense. This issue is meant to formalize the request to alter the original definitions so you can more comfortably remove them from yours as well. :smile:
