### ISSUE TITLE
Local GC: GCToOSInterface platform detection

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#8362]
The Windows implementation of `GCToOSInterface` is complete enough to pass tests, but it is not complete - in particular, it does not attempt to do any kind of platform detection or detection of processor capabilities (e.g. [1](https://github.com/dotnet/coreclr/blob/master/src/gc/gcenv.windows.cpp#L49), [2](https://github.com/dotnet/coreclr/blob/master/src/gc/gcenv.windows.cpp#L274), [3](https://github.com/dotnet/coreclr/blob/master/src/gc/gcenv.windows.cpp#L426)).

All of the code that is used today to calculate this information exists on the VM side.

**Comment by gkhanna79** [comment]
@swgillespie Is this going to be fixed for 2.0?

**Comment by swgillespie** [comment]
Most likely no - it's not needed for correctness of Workstation GC.

**Comment by gkhanna79** [comment]
In that case, please move it out of 2.0

**Comment by swgillespie** [comment]
done!

**Comment by swgillespie** [comment]
closed in favor of newer issues.
