### ISSUE TITLE
Update the build documentation with common pitfalls

### ISSUE THREAD

**Issue by damageboy** [dotnet/coreclr#84]
It would be nice for the documentation/wiki to include to following comments/requirements (which I found to be true... :smile:  )

* When building in windows, the system locale SHOULD be set to English:
<br/>Mine was set to another language and it generated warnings that were treated as errors
![image](https://cloud.githubusercontent.com/assets/125730/6055188/0d9ce336-ad03-11e4-9f32-7eceb6ad9ca2.png)
* The build.cmd should be invoked from a plain command prompt. Invoking it from a VS 2013 command prompt, for example, will cause the mscorlib build to fail: #73

**Comment by gkhanna79** [comment]
The requirement of clean command prompt is described in the Development Guide - https://github.com/dotnet/coreclr/wiki/Developer-Guide.

Can you please share the warnings you got when building in non-English locale?

**Comment by ellismg** [comment]
@damageboy forcing the system locale to be English should no longer be required (I fixed some issues around this the day we opened sourced).  Please make sure you're building from tip.  If you still find issues, please file bugs about the build not working (and note what locale you are in).  We don't want to force folks to change their system locale.
