### ISSUE TITLE
AssemblyLoadContext tries to load assembly System.IO.FileSystem.resources which cannot be found

### ISSUE THREAD

**Issue by christianhuening** [dotnet/coreclr#8416]
I am loading a couple of plugin style assemblies. One of which is using the System.IO namespace.
The load of this particular Assembly crashes into a StackOverflowException while trying to find an assembly with the FullName of: 
`System.IO.FileSystem.resources, Version=4.0.2.0, Culture=de-DE, PublicKeyToken=b03f5f7f11d50a3a `

I searched NuGet, the CoreFX and CoreCLR repos etc. but could not find an assembly that has the .resource suffix. 
What can I do?
![error](https://cloud.githubusercontent.com/assets/738953/20787805/15f9025a-b7ae-11e6-9a9b-5973c2426036.PNG)

/cc @gkhanna79

**Comment by gkhanna79** [comment]
FX assemblies are not localized, so you should skip attempting to resolve them.

CC @weshaggard

**Comment by christianhuening** [comment]
@gkhanna79 Sorry don't get that. Could you explain that a bit more? I am not trying to resolve a FX assembly intentionally, but attempt to load an assembly I have written as a plugin against my APIs. Inside of that (rather simple) plugin, I download a file from an API and load it, which is why it uses the System.IO Namespace. As it seems when loading that assembly, the above mentioned assembly is needed. Or maybe I am getting something completely wrong here?

**Comment by gkhanna79** [comment]
What I am saying is that localized assemblies for FX components do not exist. Thus, if you see a request to load a resources file for a FX assembly, you should just return null.

**Comment by christianhuening** [comment]
well, ok. I just check for ".resources" now and return null if it is requested. 
That seems to work! Thanks
//closed
