### ISSUE TITLE
CI Infrastructure: Random Linux build failures

### ISSUE THREAD

**Issue by janhenke** [dotnet/coreclr#842]
The Linux CI builds started to fail seemingly randomly with an IOExcpetion. For example:
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_linux_release/444/console

Especially dci-ub-fbld-5 seems prone to this:
http://dotnet-ci.cloudapp.net/computer/dci-ub-fbld-5/builds

Would be great if someone can take a look at it. Thanks.

**Comment by stephentoub** [comment]
@mmitche is working on this, I believe...

**Comment by richlander** [comment]
@janhenke Good to CC @mmitche on these (as @stephentoub did). Probably not the last time you'll need to do this.

**Comment by mmitche** [comment]
Yeah, the new image that I cycled the machine to didn't have a writeable /mnt folder. This is fixed.  I have filed an issue dotnet/dotnet-ci/#17 to get a real fix for this to avoid manual intervention in the future.
