### ISSUE TITLE
Collection<T> does not support Ranges

### ISSUE THREAD

**Issue by robertmclaws** [dotnet/coreclr#8439]
Based on the discussion in https://github.com/dotnet/corefx/issues/10752, I'm opening up an issue here to track the PR that will be required to enable the approved changes to ObservableCollection<T>.

**Comment by robertmclaws** [comment]
My initial work is [here](https://github.com/robertmclaws/coreclr/commit/841672090c9245ab961bf25cb682833ef599c358). Feel free to follow along. Would love feedback before the PR, or you can wait till after.

**Comment by gkhanna79** [comment]
@AlexGhiondea @danmosemsft Please guide this through.

**Comment by danmosemsft** [comment]
Thanks for the headsup, looks like this has languished. @ianhays owns collections. @ianhays could you please take a look?

@robertmclaws I haven't looked at your changes, but I suggest you start a PR as it's an easy way to drive it along.

**Comment by robertmclaws** [comment]
No worries, I'll keep working on it. I've been torn about implementation details, mostly because there are a lot of replacements to this functionality out there. Been putting together some real-world tests to verify if this change will be breaking. Will try to get more submitted in the next few days.

**Comment by danmosemsft** [comment]
@robertmclaws just cleaning up old issues. Is this one still active on your side?

**Comment by robertmclaws** [comment]
@danmosemsft Yeah it's still open. Sorry, I plan to get it resolved soon.

**Comment by justinvp** [comment]
This issue was fixed by #23018 and can be closed.

**Comment by danmosemsft** [comment]
Thanks @justinvp
