### ISSUE TITLE
Missing NanoServer MSBuild docker image

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/coreclr#8440]
Hello folks...

Looking for the latest image of dotnet runtime and sdk on Docker hub, I found out that there isn't one for nanoserver. The only one available is for Debian...

I know that we can easily build our own but, is there a plan to ship an "official" one for nanoserver?

Thanks!

**Comment by benaadams** [comment]
https://hub.docker.com/r/microsoft/dotnet/

Not available as `microsoft/dotnet:<version>-nanoserver` ?

**Comment by galvesribeiro** [comment]
https://github.com/dotnet/dotnet-docker/blob/master/1.1/nanoserver/sdk/projectjson/Dockerfile

It is for projectjson, now MSBuild :( The MSBuild is only for Debian https://github.com/dotnet/dotnet-docker/blob/master/1.1/debian/sdk/msbuild/Dockerfile 

(links from docker hub)

**Comment by benaadams** [comment]
Ah, gotcha!

**Comment by dleeapho** [comment]
@galvesribeiro with the fix from msbuild for [](https://github.com/Microsoft/msbuild/issues/1233), msbuild on nanoserver is now available check [](https://hub.docker.com/r/microsoft/dotnet/tags/)

cc @MichaelSimons

**Comment by galvesribeiro** [comment]
Hello Dan, thanks for get back.

Yes, I got the image few days ago. Sorry, I forgot to report it here.

I'm closing the issue.

Thanks!
