### ISSUE TITLE
Q) What are the DBG_TARGET_XXX used for?

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#8458]
When looking around SOS codes, I can see lots of `DBG_TARGET_xxxx` defines. Is there any documents here in github or other places that I could reference while working on Linux/x86 port? 
And also for `SOS_TARGET_XXX`.
Thanks in advance.

**Comment by janvorli** [comment]
I believe DBG_TARGET_XXX represents the target architecture being debugged. So you have have debugger running on AMD64, but debugging remote ARM instance or core dump.
I am not sure about SOS_TARGET_XXX, but my guess it serves the same purpose, but for SOS only.
@mikem8361, please correct me if I am wrong.

**Comment by mikem8361** [comment]
You are correct on both defines.

**Comment by seanshpark** [comment]
Thank you both! :)
One more question, maybe @mikem8361, could you explain more about "same purpose, but for SOS only" means? Is SOS something like a HOST?

**Comment by janvorli** [comment]
SOS is a plugin for debugger (WinDBG / VisualStudio on Windows, lldb on Unix) that extends the debugger with some commands for managed code debugging - dumping managed stack trace, disassembling jitted methods, dumping stack objects and heap etc. It runs on top of the lower level mscordaccore.

**Comment by seanshpark** [comment]
So that means, `SOS_TARGET_XXX` means, this code block is running when SOS target architecture is XXX, I guess :)

**Comment by janvorli** [comment]
@seanshpark yes, that's the case.

**Comment by mikem8361** [comment]
It means this block of SOS code (in src/ToolBox/SOS/Strike) is compiled into the SOS module (i.e. libsos.so) for this target architecture.

**Comment by seanshpark** [comment]
Thank you again :)
I think I can close this issue.
