### ISSUE TITLE
GUI Framework Assistance

### ISSUE THREAD

**Issue by wjk** [dotnet/coreclr#846]
I am very interested in using .NET Core for my programs, especially because it lets me bypass the system-wide installation of the "regular" .NET Framework. (This makes writing "portable" .NET apps -- those that can run off a USB thumb drive without having to be explicitly installed -- extremely easy.) However, I find that I am stymied by the lack of a good GUI framework -- namely, `System.Windows.Forms`. I use Windows Forms mainly because of its excellent designer support in Visual Studio; however, I also find that [alternate GUI frameworks](https://github.com/picoe/Eto) also depend on Windows Forms (or, alternately, WPF). Unfortunately, neither Windows Forms nor WPF is compatible with .NET Core.

In my opinion, the lack of a GUI library for .NET Core seriously hinders uptake of the platform for a large number of applications. What's more, Microsoft has [stated](http://www.infoq.com/news/2014/04/WPF-QA) that they have discontinued the addition of new features to Windows Forms. While I understand their motivation (Windows Forms is extremely old, after all), in my opinion open-sourcing Windows Forms would enable further innovation on the platform without Microsoft needing to commit any more resources to the platform, as the community would take over maintenance. Unfortunately, I know of no plans to do this. Does anyone know of any GUI frameworks that are compatible with .NET Core that I could use, or have any other pointers as to solutions to this problem? Thanks!

**Comment by shahid-pk** [comment]
It is better to discuss this in gitter chatrooms or in dotnet foundation fourms (http://forums.dotnetfoundation.org/) where it has been discussed several times. I do not think it is an issue for this repository.

**Comment by wjk** [comment]
Fair enough.
