### ISSUE TITLE
Setup assembly probe paths before managed code runs

### ISSUE THREAD

**Issue by schellap** [dotnet/coreclr#8469]
The discussion is captured in PR #8333 

The problem is:

1. Host sets `NATIVE_DLL_SEARCH_DIRECTORIES` pointing to `System.Native.so` root directory.
2. Runtime needs to find `System.Native.so` during `AppDomain::DoSetup` to resolve mscorlib `System.Path` PInvoke references.
3. Naturally, it looks up the native DLL search directories in `NDirect::LoadFromNativeDllSearchDirectories`
4. But the https://github.com/dotnet/coreclr/blob/204f6e8859e3676114c85f49b8d2c311458ac715/src/mscorlib/src/System/AppDomain.cs#L3662 is not yet performed yet.
5. So the native DLL search directories are all empty and `System.Native.so` is not resolved.
6. Either we need something like `JIT_PATH` or do the `SetNativeDllSearchDirectories` before `DoSetup`.

We are not able to consume coreclr in `core-setup` from PR dotnet/core-setup#702 and auto PRs from Maestro.

Cc @gkhanna79 @JeremyKuhne

**Comment by gkhanna79** [comment]
@JeremyKuhne Do you have an update on this as this is blocking Core-Setup from picking up new CoreFX and CoreCLR packages?

**Comment by JeremyKuhne** [comment]
@gkhanna79 I'm working on it now. I'll provide more info later today if I don't have a solution finished.

**Comment by JeremyKuhne** [comment]
#8531 should fix this.
