### ISSUE TITLE
CPU goes up after exception and does not come back

### ISSUE THREAD

**Issue by rvfernandes** [dotnet/coreclr#8478]
I made a small router in .Net Core and noticed that some machines from one hour to the other had a cpu jump. When this happens the CPU stays high, although the application responds without problems. I have noticed that this happens when I have a large number of exceptions of type (System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.CurlException: Transferred a partial file).

My system runs on .Net Core with docker.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #14319](https://github.com/dotnet/corefx/issues/14319) via [**ZenHub**](https://www.zenhub.com/)
