### ISSUE TITLE
Make CoreCLR work properly on GRSEC/PAX enabled Linuxes

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#8480]
When GRSEC/PAX has RANDMMAP enabled, it never honors the address passed to mmap unless the MAP_FIXED option is passed in. But there are two parts of CoreCLR that rely on the fact that mmap honors the address unless there is an overlapping mapping. First part is the executable allocator in PAL that tries to  reserve memory range in close vicinity of the libcoreclr.so (within 2GB range) to make sure that jitted managed code that calls into libcoreclr.so doesn't have to use jump stubs.
The second part is the jump stub allocator. If code in one jitted module calls code in another one and the distance of the jump is larger than 2GB, jitter tries to allocate jump stub within 2GB range from the caller address.
Both of these mechanisms fail on GRSEC/PAX enabled Linux since we cannot control the address where we create mappings. The result is either coreclr_initialize failure with HR 0x80004005 or an out of memory exception. Since the mapping address picked by the kernel is random, sometimes, after many attempts, we can actually start and run fine if by a chance the mapping picked by the kernel matches the requested one.
There is a workaround for this - disabling the RANDMMAP for dotnet, corerun or the renamed coreconsole executables using the `paxctl -c -r` command. But it would be great to make it work, possibly with lower performance, even without this workaround.

**Comment by janvorli** [comment]
cc: @gkhanna79, @Petermarcu

**Comment by gkhanna79** [comment]
RANDMMAP sounds like ASLR for Linux (when I read articles like https://copperhead.co/blog/2015/06/11/android-pax). I agree that we should fix the PAL to support it as opposed to disabling it.

**Comment by gkhanna79** [comment]
CC @kouvel

**Comment by janvorli** [comment]
Here are some links on GRSEC / PAX:
https://wiki.debian.org/grsecurity
https://wiki.archlinux.org/index.php/grsecurity
http://man.he.net/man1/paxctl

**Comment by spender-sandbox** [comment]
Also https://pax.grsecurity.net/docs/ ;)

-Brad

**Comment by janvorli** [comment]
@kouvel I think that running `paxctl -c -r` at build time on the corerun, dotnet and coreconsole could be a good solution.

**Comment by jkotas** [comment]
We are fixing the hard dependencies on being able to allocate memory in given region for other reasons (#9883, #9994, more to come). It would be better to get that work finished instead of marking CoreCLR as incompatible with this security measure.

Yes, it means that code may be slower here and there when this security measure is enabled. Security measures tend do cost some perf.

**Comment by janvorli** [comment]
@jkotas actually, maybe that we are already there functionality-wise with the #9883 and #9994. The executable allocator is just a perf optimization, so if we fail to allocate memory for it, everything should still work, just with a large perf hit. See the #2205 description for details on the perf.

**Comment by gkhanna79** [comment]
@janvorli Once #9994 is merged, is there anything actionable here?

**Comment by janvorli** [comment]
We need to test it after that to see if it really fully fixed the issue and also try to measure the perf hit.
