### ISSUE TITLE
Exception on Richtextbox while typing korean fonts with Italic style.

### ISSUE THREAD

**Issue by racuca** [dotnet/coreclr#8493]
I created a simple WPF project like editor has a Richtextbox.

Environment : 
1. Korean font or Korean Windows 
2. Set Richtextbox font to korean font 'Gulim' for example.

When I just type any text, It works fine.
But when I type with Italic style a little fast like stress test, It throws exception.
My project .net version is 3.5 but 4.0, 4.5, and 4.6.1 all versions have also same exceptions. 
this bug is also independent from Windows version.
I am not sure it is core bugs or not.
if not, I will be appreciated if you arrange this bug properly.

I am developing with a public customer and have a big trouble from opening the project.
Already I posted a bug on connect site, but no replied.

So, If you have any idea or workthrough, please let me know.
Thanks.

**Comment by racuca** [comment]
I added Error Message details on Windows 7.

Description:
  Stopped working

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	richtextboxeditortest.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5832ded4
  Problem Signature 04:	WindowsBase
  Problem Signature 05:	3.0.0.0
  Problem Signature 06:	4ca2e281
  Problem Signature 07:	e4
  Problem Signature 08:	1b
  Problem Signature 09:	FatalError
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1042

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by danmosemsft** [comment]
Hello @racuca .. these repos are for .NET Core, which does not contain WPF.

For support on the Desktop framework here are the options:

- Ask the community: https://social.msdn.microsoft.com/Forums/vstudio/en-US/home is an excellent place to engage with an active community of experts. If something you are working on is behaving unexpectedly, this is good place to find answers. http://stackoverflow.com is another great community.
- Feature ideas: User Voice is where we gather your ideas for how to improve Microsoft products. Log suggestions at https://visualstudio.uservoice.com/forums/121579-visual-studio.
- Direct support ticket with https://support.microsoft.com/en-us/getsupport?oaspworkflow=start_1.0.0.0&wf=0&wfName=productselection&gprid=1117&st=1&wfxredirect=1&sd=gn&ccsid=635736129514016010

**Comment by racuca** [comment]
Thank you for your help.
I will try them.
