### ISSUE TITLE
Updated CI badge

### ISSUE THREAD

**Issue by olivierlacan** [dotnet/coreclr#85]
Hey folks,

Along with some good folks at http://shields.io/ I've developed the Shields badge standard that's now used across many open source repositories like this one. We've recently overhauled the design of our badges for consistency. It appears that you've cached the older version of these badges at http://dotnet-i.cloudapp.net/job/dotnet_coreclr_linux_debug/badge/icon

That's actually unnecessary, we provide a really simple API to generate perfect SVG badges on the fly (which you can of course use and cache on a proxy if you like): https://img.shields.io/badge/build-passing-brightgreen.svg

Additionally we've built a slew of integrations with broadly used CI services. I'm guessing yours is private so the proxy route is probably best but you can always open an issue on https://github.com/badges/shields/issues if you'd like to have your CI integrated.

Hope that helps. :smiley:

**Comment by akoeplinger** [comment]
The CI is a standard Jenkins with the [Embeddable Build Status](https://github.com/jenkinsci/embeddable-build-status-plugin) plugin: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr_linux_debug/badge/

I think the badges need to be updated there (which would of course also benefit all the other user's of the plugin :)

**Comment by ellismg** [comment]
@mmitche Do we need to do anything here or should this just be handled once Jenkins takes a fix upstream?

**Comment by mmitche** [comment]
Once the plugin takes a fix upstream (and I install the update), we should get the new version.
