### ISSUE TITLE
RyuJIT x86: Determine why results differ in GitHub_8220 test

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#8506]
In the test added for the fix to #8220, (tests/src/JIT/Regression/JitBlue/GitHub_8220/GitHub_8220.cs) with PR #8482 , the test is checking for margin of error of approximately 1 unit in the last place. The original test was checking for equality, but on RyuJIT x86 (without intrinsics enabled at this point), I was seeing results that were off by 1 ULP. We should determine why that is the case, as the code ought to be identical, modulo the call to `getTestValue`, which is simply returning a `Vector3` (which shouldn't, in theory, change any values).

**Comment by mikedn** [comment]
This isn't x86 specific, there are difference even when running the test on x64 with and without SIMD enabled (via `COMPLUS_FeatureSIMD`):

> Vectors do not match <-0.2773895, -0.3838284, -0.8807558><-0.2773895, -0.3838284, -0.8807557>

**Comment by mikedn** [comment]
Ho-hum, this isn't JIT related, it's an issue in `Vector3.Normalize` implementation:
```C#
public static Vector3 Normalize(Vector3 value)
{
    if (Vector.IsHardwareAccelerated)
    {
        float length = value.Length();
        return value / length;
    }
    else
    {
        float ls = value.X * value.X + value.Y * value.Y + value.Z * value.Z;
        float length = (float)System.Math.Sqrt(ls);
        return new Vector3(value.X / length, value.Y / length, value.Z / length);
    }
}
```
When hardware accelerated it does `value / length` and the division operator is
```C#
public static Vector3 operator /(Vector3 value1, float value2)
{
    float invDiv = 1.0f / value2;

    return new Vector3(
        value1.X * invDiv,
        value1.Y * invDiv,
        value1.Z * invDiv);
}
```
Of course, `x * (1.0f / y)` is not the same as `x / y`.

**Comment by CarolEidt** [comment]
@mikedn - Thanks for tracking that down! I feel rather foolish now, because as I was tracking down the bug in #8220, I noticed that, but realized that couldn't be the issue for that bug, because it was using `Vector3 operator /` in both cases. However, when I found the real bug, I failed to go back and file an issue on that one.

**Comment by CarolEidt** [comment]
@sivarv @mikedn I've filed https://github.com/dotnet/corefx/issues/14286 to track this, and will close this issue. Thanks again @mikedn
