### ISSUE TITLE
Span: Add tests to verify type loader checks for ref-like types

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#8516]
- Span cannot be boxed
- Span cannot be used as argument of generic instantiations
- Span cannot be used as type of static fields or non-value type instance fields

**Comment by ahsonkhan** [comment]
@kouvel, any updates on this issue?

**Comment by kouvel** [comment]
I had tested the C# versions of these tests and all is good, just need to convert them to IL tests

**Comment by ahsonkhan** [comment]
@kouvel, any updates on this issue?

**Comment by kouvel** [comment]
Nope, haven't had the time to look at my issues

**Comment by ahsonkhan** [comment]
@kouvel, can you please triage/prioritize this issue. Ty

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/coreclr/pull/15745.
Closing.
