### ISSUE TITLE
Add more detail to crossgen warning

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/coreclr#8535]
The warning issued here: https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/tools/crossgen/crossgen.cpp#L424
doesn't give enough context to actually figure out what is going wrong.

My scenario: 

I'm attempting to build the optimized package cache for ASP.NET Core docker images, using the crossgen from runtime.debian.8-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.2. When I run the command,

> crossgen /Platform_Assemblies_Path $platformPaths /App_Paths $aspnetAppPaths /ReadyToRun

the tool issues a warning:

>  Warning: Error enumerating files under ($platformPaths)

This includes the list of all folders specified, and does not indicate which folder(s) were actually the source of the error and what that error was.

**Comment by natemcmaster** [comment]
FWIW I finally figured out that the reason for the failure was that crossgen on windows expects `/Platform_Assemblies_Path path1;path2` and on Linux expects `/Platform_Assemblies_Path path1:path2`. Semicolon vs colon. The help text on Linux shows semicolon.

**Comment by gkhanna79** [comment]
@JohnChen0 Can you PTAL?

**Comment by JohnChen0** [comment]
Fixed CrossGen help text with PR #8566.
