### ISSUE TITLE
Ensure reliable fallback to english resources on Linux / BSD

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#854]
I have found that the gettext APIs don't use the locale set for the LC_MESSAGE unless the locale is also one of the locales in the LANGUAGE environment variable. That means that we cannot currently fall back to the default US English messages if the LANGUAGE doesn't contain en_US.
I can see two ways to solve the issue:
1) Modify the LANGUAGE env variable in the PAL_InitializeCoreCLR by adding the en_US in case it is not there
2) Change the way we handle string resources to how gettext is ordinarily used. That means compile the default English string resources into the libcoreclr and use them as a key. That way gettext would return the "key", that means the default English string if it doesn't find the translation.

**Comment by janhenke** [comment]
I favour the second option. Changing environment variables is not a nice thing to do and it is can potentially create new issues.
On the other hand the second approach is indeed commonly used and having an English text in any case certainly has benefits.

**Comment by janvorli** [comment]
I have come to the same conclusion. It would be great if the gettext API allowed me to ask for a string in any language I want and have files, but since it doesn't allow that, the other approach is better.

**Comment by milizhang** [comment]
One more vote for method 2.

If we decide to take that way I think an abstraction layer before calling dgettext, to translate the ID to English string before passing to gettext. In that way we should be able to minimize the changes in source code.

Or another choice is to write a replacement for gettext, so that we also do not need to worry about it on OSX.

**Comment by adityamandaleeka** [comment]
Agreed. I prefer method 2 as well, and just submitted a PR that implements it.
