### ISSUE TITLE
[RyuJIT x64][SIMD][JitStress=2]  newly added SIMD test GitHub_8220.exe fails on Linux with an assertion

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#8550]
Test:
`JIT.Regression.JitBlue.GitHub_8220.GitHub_8220.GitHub_8220`

Assert:
`Thread: 43165 [0xa89d]): Assertion failed 'varDsc->lvSize() == 16' in 'Test.Program:testEquals(struct):int' (IL size 127) File: /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_prtest/src/jit/lower.cpp Line: 240`

This failure I have uncovered while doing stress testing for an LSRA fix.

**Comment by adiaaida** [comment]
It looks like this issue is that the var is a shadowVar, and when we copy the varDsc's info to the shadowVar, we don't copy over lvExactSize, which is needed for SIMD12 vars.
