### ISSUE TITLE
Why Span<T> does not implement interfaces IList<T> and so on like Array<T>

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/coreclr#8553]
Why `Span<T>` does not implement interfaces `IList<T>` and so on like `Array<T>` ?

**Comment by AlexRadch** [comment]
I should ask such question here or in corefx repository?

**Comment by mikedn** [comment]
Probably you should start by reading the design doc: https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md

There are also a bunch of existing discussions about spans, issues 5851, 8054, 5860 are just a few pointers.

**Comment by AlexRadch** [comment]
Cool
