### ISSUE TITLE
[ARM32/Linux] Performance issue when FEATURE_STUBS_AS_IL is enabled

### ISSUE THREAD

**Issue by sjsinju** [dotnet/coreclr#8554]
Currently, when I run an application in an ARM environment, I have created a Native Image of all the DLLs used by Crossgen for performance reasons.
Therefore, most methods do not need JIT Compile at runtime.

The application I have tested uses a lot of Secure Delegate Stub in character.
However, I found that JIT Compile is executed whenever 'Domain NeutralISt ubClass :: IL_STUB_SecureDelegate_Invoke' is executed during execution.(Even though used by Native Images..)

The differences in the number of stub compiles before and after creating NI Image are shown below.
[StubName(WithoutNI),(WithNI)]
```
DomainBoundILStubClass::IL_STUB_InstantiatingStub(14),(14)
DomainBoundILStubClass::IL_STUB_MulticastDelegate_Invoke(3),(3)
DomainBoundILStubClass::IL_STUB_PInvoke(46),(0)
DomainBoundILStubClass::IL_STUB_ReversePInvoke(8),(1)
DomainBoundILStubClass::IL_STUB_SecureDelegate_Invoke(214),(214)
DomainBoundILStubClass::IL_STUB_UnboxingStub(3),(3)
DomainNeutralILStubClass::IL_STUB_InstantiatingStub(7),(7)
DomainNeutralILStubClass::IL_STUB_MulticastDelegate_Invoke(1),(1)
DomainNeutralILStubClass::IL_STUB_PInvoke(12),(0)
DomainNeutralILStubClass::IL_STUB_SecureDelegate_Invoke	(1761),(1761)
DomainNeutralILStubClass::IL_STUB_UnboxingStub(3),(3)
```
As you can see in the above table, you can see that the PInvoke stubs are gone, but the rest are still.
So I checked the code of GetSecureInvoke() which is a method related to creation of SecureDelegate, I figured out that when FEATURE_STUBS_AS_IL is enabled, JIT Compile is executed without fetching stub in Cache.

As far as I know, turning off FEATURE_STUBS_AS_IL does not work Unwind.

When FEATURE_STUBS_AS_IL is turned on, is there any way to fetch a cached stub without JIT compilation every time? Is it different from PInvoke stubs?

**Comment by janvorli** [comment]
@jkotas does it sound like a bug or is there a reason why we need to jit the secure delegate stubs every time?

**Comment by jkotas** [comment]
Yes, it looks like a bug. There should be a hashtable to cache these so that they are not recompiled multiple times.

**Comment by sjsinju** [comment]
@janvorli @jkotas  Thanks for your comments. I will analyze codes.
But I have an question.
In the above table, not only SecureDelegate but also other stubs except PInvoke can be called at least once (although a small number).

Do you think there are bugs in the SecureDelegate Stub as well as others? or is it just a SecureDelegate  Stub bug?

**Comment by sjsinju** [comment]
@janvorli  @jkotas 
I requested for PR related to this issue( #8592 ).
It's just like the implementation of GetMulticastInvoke(), which uses an already created stub.

**Comment by jkotas** [comment]
> Do you think there are bugs in the SecureDelegate Stub as well as others? 

The problem is specific to the SecureDelegate Stub.

**Comment by sjsinju** [comment]
@jkotas 
Thank you for your support.
Using this PR(#8592), I can see the following results for the same application.
```
DomainBoundILStubClass::IL_STUB_ReversePInvoke	1
DomainNeutralILStubClass::IL_STUB_MulticastDelegate_Invoke	1
DomainNeutralILStubClass::IL_STUB_InstantiatingStub	7
DomainBoundILStubClass::IL_STUB_InstantiatingStub	14
DomainBoundILStubClass::IL_STUB_MulticastDelegate_Invoke	3
DomainNeutralILStubClass::IL_STUB_UnboxingStub	9
DomainNeutralILStubClass::IL_STUB_SecureDelegate_Invoke	5
DomainBoundILStubClass::IL_STUB_UnboxingStub	3
DomainBoundILStubClass::IL_STUB_SecureDelegate_Invoke	3
DomainBoundILStubClass::IL_STUB_PInvoke	1
```

**Comment by gkhanna79** [comment]
Can this be closed?
