### ISSUE TITLE
Cleanup dirs.proj, *.nativeproj

### ISSUE THREAD

**Issue by xoofx** [dotnet/coreclr#8558]
Hi here,
This is just a question to understand how the build is organized.
The documentation says that CMake is used for building, but I'm intrigued by `dirs.proj` and `*.nativeproj` files and their usage. It seems that they duplicate a part of what existing CMakeLists.txt contains.
What are they used for?

**Comment by jkotas** [comment]
They are part of the legacy build system that we are not using anymore. They can be deleted (except from under the JIT directory where they are still used).

**Comment by jkotas** [comment]
We can keep this issue open to track cleaning these up.

**Comment by matekm** [comment]
it's up for grabs and it looks like nice task for a guy that want to contribute something on a spare time.  Can I take it?

**Comment by jkotas** [comment]
@matekm It is yours. Thank you!

**Comment by matekm** [comment]
cool, thanks @jkotas !

I noted that there are few directories that are empty, for example 'src\zap\wks' or 'src\utilcode\dac' (it contain only CMakeLists.txt). Should this be removed too?

One more question, what about *.settings.targets files? Leave them or remove them?

**Comment by jkotas** [comment]
> it contain only CMakeLists.txt

CMakeLists files should stay - they are used by the live build. Also, everything under src\jit should stay as I have said above.

> *.settings.targets files

They can be removed. As well as other similar files references by the projects being removed, for example src/vm/vm.settings or src/vm/vm.targets.

**Comment by mikedn** [comment]
> As well as other similar files references by the nativeproj files being removed, for example src/vm/vm.settings or src/vm/vm.targets.

And probably .props files too.
