### ISSUE TITLE
[RyuJIT] TreeNodeInfoInitCmp incorrectly drops a required cast

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#8599]
Example:
```C#
static void escape(ref int x)
{
}

static void Test()
{
    int x = new int[301].Length;
    escape(ref x);
    if ((byte)x > 300)
    {
        Console.WriteLine("boo");
    }
}
```
The cast to byte is dropped by this [code](https://github.com/dotnet/coreclr/blob/master/src/jit/lowerxarch.cpp#L3626) and we get this:
```asm
G_M55887_IG02:
       48B9AA10AA5AF97F0000 mov      rcx, 0x7FF95AAA10AA
       BA2D010000           mov      edx, 301
       E898D8765F           call     CORINFO_HELP_NEWARR_1_VC
       8B4808               mov      ecx, dword ptr [rax+8]
; int sized compare
       81F92C010000         cmp      ecx, 300
       7E12                 jle      SHORT G_M55887_IG03
       48B96830535621020000 mov      rcx, 0x22156533068
       488B09               mov      rcx, gword ptr [rcx]
       E87BA6665E           call     System.Console:WriteLine(ref)
```
Presumably the intention of that code is to generate a byte sized compare but this doesn't happen if the constant doesn't fit in a byte.

**Comment by mikedn** [comment]
This is likely a very rare case, I only found this because I'm trying to somehow refector `TreeNodeInfoInitCmp`, it's quite convoluted. In a week or so I should have a PR that includes a fix for this but maybe having a separate fix would be better since this also affects .NET Framework?

cc @RussKeldorph

**Comment by RussKeldorph** [comment]
Thanks @mikedn!  Do you want me to assign this to you, or are you thinking the separate fix should come from someone else?

@dotnet/jit-contrib

**Comment by mikedn** [comment]
> Do you want me to assign this to you, or are you thinking the separate fix should come from someone else?

IMO since I'm already looking into this there's no point wasting someone else's time on this. I asked just in case the team prefers to fix this because it affects .NET Framework.

**Comment by RussKeldorph** [comment]
@mikedn Sold.  It definitely makes sense to make a separate fix before refactoring in case it helps porting, but its your call.

@russellhadley

**Comment by BruceForstall** [comment]
btw,
> I'm trying to somehow refector TreeNodeInfoInitCmp, it's quite convoluted.
Please! And thank you!
