### ISSUE TITLE
Debugger launch has a race condition making breakpoints in startup code are unreliable

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#8606]
1. Create a new process suspended
2. Use RegisterForRuntimeStartup to find out about the new process
3. When RegisterForRuntimeStartup fires the handler, call DebugActiveProcess and return

Expected:
Debugger should successfully finish the hookup before any managed code runs

Actual:
There is a race where sometimes managed code runs before the hookup finishes. CORDebuggerAttached gets set from coreclr!Debugger::MarkDebuggerAttachedInternal, which is being called from coreclr!Debugger::SuspendComplete.

We have seen this on various Linux distros. I can't tell for sure if this is an xplat-only problem (or maybe Linux only?) or if this applies to Windows also.

**Comment by mikem8361** [comment]
Fixed in master in PR: https://github.com/dotnet/coreclr/pull/8951

**Comment by mikem8361** [comment]
1.1.x PR #9060, 1.0.x PR #9062
