### ISSUE TITLE
RyuJIT/ARM32: Working on "NYI_ARM: ARM IsContainableImmed"

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#8616]
Start implementing Lowering::IsContainableImmed in lowerarm.cpp

I will post a initial PR soon.

This is a part of #8496.

**Comment by BruceForstall** [comment]
@hqueue Is this issue still active? Or can you close it because #8617 fixed it?

**Comment by hqueue** [comment]
@BruceForstall Sure,, I will close this.
