### ISSUE TITLE
[RyuJIT][SIMD][Amd64] Adding OSSCI test leg for testing SIMD intrinsics in SSE2 only mode

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#8626]
RyuJIT supports the following instruction sets for SIMD codegen

SSE2
SSE3_4 and
AVX2.

Most machines are likely to be SSE3_4 or AVX2.  We need to ensure that we continue to test SIMD functionality in SSE2 only mode.  A way to ensure is to run all of CoreCLR SIMD (both JIT and CoreFX) tests with on am64 machine.

COMPlus_EnableAVX=0
COMPlus_EnableSSE3_4=0

Adding a OSSCI test leg will ensure that no regressions creep as we make fixes to SIMD functionality.

Note that for testing SIMD functionality we need to run both JIT and CoreFX SIMD tests.

**Comment by mikedn** [comment]
Has the team considered dropping support for SSE2 and going with SSE3/4 only? SSE2 only processors are ancient.

**Comment by sivarv** [comment]
.Netcore Amd64 minbar is SSE2 and for that reason support for SSE2 is warranted.  Besides, SSE2 is also used on those machines which supports SSE3 but not SSE4.

**Comment by sivarv** [comment]
@BruceForstall  agreed to add this leg as well as part of adding tailcallstres leg.
