### ISSUE TITLE
Introduce a base class for REGDISPLAY

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#8643]
While bring up x86/Linux, I found that the current definition of ``REGDISPLAY`` has several duplicated code  (especially code related with ``WIN64EXCEPTIONS``).

It would be better to introduce a base class to remove such code duplication.

**Comment by parjong** [comment]
It would be better to rename Esp as SP in x86 REGDISPLAY to make it more easy to maintain.

**Comment by gkhanna79** [comment]
CC @rahku
