### ISSUE TITLE
Enable x86 hosted build of cross components for Linux Arm32

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#8647]
We need to build them, similar to what is done for Windows. This will enable us to generate NI images (or perform R2R compilation) on x86/x64 machines.

CC @kouvel @hseok-oh

**Comment by gkhanna79** [comment]
CC @janvorli

**Comment by hseok-oh** [comment]
We need 
1. fix build script to build x86-host/arm-target crossgen (#8646)
2. success x86-host/arm-target crossgen build
3. generate correct NI image

**Comment by gkhanna79** [comment]
Assigned it to @hqueue

**Comment by JensNordenbro** [comment]
Any progress on this one @gkhanna79 ? 
I take it, that compleing this will enable me to generate *.ni variants of dll:s targeting ARM using my x86 computer as build system ?!

**Comment by BruceForstall** [comment]
I believe this has been done, so the issue can be closed.
