### ISSUE TITLE
Estimated time before this leaves pre-alpha?

### ISSUE THREAD

**Issue by TechnikEmpire** [dotnet/coreclr#8658]
I've just flushed a full days wages down the toilet trying to make something as simple as domain name resolution perform consistently on all officially supported platforms. By "consistently" I mean trying to not have the runtime explode, leaving only a 1 liner obituary in syslog. Not to sound too critical, I understand good coding is hard and things take time. 

I'm just wondering if an official timeline can be posted that will indicate when this project and friends will be actually marketable. Certainly can't go giving that impression right now when calling functions is playing Russian roulette that might get you a segfault in System.Native.so (including functions documented in the core docs).

I've wiped this technology stack off the whiteboard for several upcoming projects because it was being marketed to me as something stable when it's not. I think the project is great, open source is great, but the dishonest marketing isn't acceptable. It's not acceptable because people pass that dishonest marketing on to a client to then suffer the aforementioned experience, having to return to their client looking like an ass and also having to explain to their client that the technology is crap.

**Comment by bitcrazed** [comment]
Have you filled a repro and bug on the issue you found? Would be interesting to see what's going on.

**Comment by TechnikEmpire** [comment]
@bitcrazed I found many existing bugs speaking to all the brick walls I was smashing into yesterday. I'll have to dig them up again. That's also part of the problem, it's prohibitively difficult trying to determine which line of code is actually causing the problem when the runtime just calls it quits giving no information. Yes I know I could do proper debugging of the runtime, but again I think the fact that I have to try and debug the technology I'm trying to build atop of is a testament itself to the issue I'm trying to address.

My message was a bit ranty yesterday and I apologize. Microsoft is taking huge strides towards nothing but good things with this entire project and development is not easy. It's just the marketing I have an issue with. It's needs to be honest because like I said, people (hopefully) take you at your word, you make big pitches to clients assuming the technology is stable, then you have to return to those clients and throw your contract and worse, your reputation, at their mercy and understanding.

Anyway I'll try and find the other bug tickets. There was one where many people were asking for the docs to be updated because there were "several" methods documented as supported that would cause the runtime to just shut down. Not even a "not implemented exception", just plain shut down.

**Comment by TechnikEmpire** [comment]
Off the top of my head, this entire namespace is a minefield on Ubuntu Server 16.04 x64:

https://docs.microsoft.com/en-us/dotnet/core/api/system.net.networkinformation

**Comment by ayende** [comment]
@TechnikEmpire Yet your message contains exactly zero information that anyone can use to diagnose and help.

I can tell you that I personally have been able to successfully use the Dns class on Ubuntu 16 and Ubuntu 16 on ARM 32 bits.

There is no way that anyone can help unless you provide actual actionable information. If the issues are already here, point them out and comment on them to indicate their impact.

Just waving your hands in the air and saying "many existing tickets" is pretty useless. For reference, I actually looked and there doesn't seem to be any opened issues with regards to that namespace.

**Comment by janvorli** [comment]
@TechnikEmpire I would love to know about issues where we would segfault. I am not aware of any such problem with the current version, so if there are some, I want to look into them and fix them right away. Also, could you please point me to where this came from?
> There was one where many people were asking for the docs to be updated because there were "several" methods documented as supported that would cause the runtime to just shut down on certain "supported" platforms. Not even a "not implemented exception", just plain shut down.

**Comment by TechnikEmpire** [comment]
@ayende Commenting when you have 0 ability to impact the situation at hand is probably even more useless. I already mentioned in a previous comment that I'll take time out of my day to dig up the tickets and reference them as soon as possible. On that note, talking to people without reading what they say is truly completely useless as it produces an entirely fruitless one-sided dialog.

**Comment by TechnikEmpire** [comment]
@janvorli I will look up them asap. Thanks for inquiring.

**Comment by TechnikEmpire** [comment]
@janvorli @bitcrazed Is there a business contact where I can send these concerns? This way I can be assured I'll get in touch with professionals who won't respond to real world business concerns with emojis and condescending rants just for the sake of showing the world their inner adult baby. Thanks. Closing ticket as I lost interest when the white knights who forget they had open bug tickets 24 days ago with the same core issue come striding in championing that nothing is wrong.

**Comment by janvorli** [comment]
@TechnikEmpire I am sorry, but I really don't understand what you are referring to. Could you please be more specific? Are you saying that I have opened a bug w.r.t. a segfault on a supported platform recently?

**Comment by TechnikEmpire** [comment]
@janvorli No, I was referring to the condescending twit who isn't a Microsoft employee. The MS employees in this thread were helpful, yourself included. I tagged you both asking for a business contact, a place more appropriate for me to bring my concerns.
