### ISSUE TITLE
Failures in TextWriter and StreamWriter to handle null inputs to WriteLineAsync

### ISSUE THREAD

**Issue by JonHanna** [dotnet/coreclr#8661]
If null is passed to `TextWriter.WriteLineAsync(char[])` it will produce no effect. By analogy to the non-async method it should write a newline as if `TextWriter.WriteLineAsync()` had been called.

If null is passed to `StreamWriter.WriteLineAsync(string)` it will throw an `ArgumentNullException`. Likewise it should behave as if `StreamWriter.WriteLine()` had been called.

**Comment by AlexGhiondea** [comment]
@JonHanna I think consistency in the way APIs work is good to have!

What do you think about the breaking change aspect? What scenarios do you think might be broken if we fix this?

**Comment by JonHanna** [comment]
The second case of the two mentioned is probably pretty safe in this regard in that it's relatively unlikely for someone to depend on an ANE being thrown. And if they are they're perhaps going to be broken if they move between using this version to the version in corefx as it throws NRE in that case, dotnet/corefx#14563 being different to this issue in that regard. It's not impossible, but it's pretty unlikely. Also the fact that the class is behaving differently to both its base and other classes derived from that base means there are perhaps components in use today that should be able to work together but which will hit this if they ever do.

The first case is a bit trickier. It's certainly not weird to have had synchronous code that did `if (array != null) writer.WriteLine(array);` and since the async behaviour is analogous not to the synchronous call but to that test-and-call it's possible that someone has written code exactly like that and will have an extra blank line in some output that could be harmful. I think on balance the behaviour is surprising enough to compared to both the synchronous version and the treatment of a null string (in implementing classes other than `StreamWriter` which of course has the exception-throw for that case) and to the documented behaviour ["If the character array is null, only the line terminator is written."](https://msdn.microsoft.com/en-us/library/hh159086(v=vs.110).aspx) that the break risk is relatively low, though not entirely absent.

There's also an argument to be made that if one can expect `XxxAsync()` to behave analogously to `Xxx()` then the current behaviour is in itself if not quite a breaking change, similar in moving away from previous behaviour.

**Comment by JonHanna** [comment]
Obsoleted in coreclr by the removal of these classes.
