### ISSUE TITLE
Optimize SIMDIntrinsicAbs in RyuJIT utilize SSSE3 and AVX2 Abs intrinsics

### ISSUE THREAD

**Issue by litian2025** [dotnet/coreclr#8663]
Currently in CoreCLR RyuJIT, SIMDIntrinsicAbs is implemented as bitwise-And operation with a mask, on system that supports SSSE3 and or AVX2, the SIMD Abs intrinsic implementation can be optimized to utilize those intrinsics directly:
 
![image](https://cloud.githubusercontent.com/assets/14881219/21270173/556de244-c36a-11e6-90da-3107a06552d1.png)

**Comment by litian2025** [comment]
@sivarv PTAL

**Comment by sivarv** [comment]
Note that bitwise-And with a mask is done in case of float/double vectors.
Abs() intrinsic is currently not accelerated for vector<long>, vector<int>, vector<short> and vector<sbyte>

The following Suplemental SSE3 (SSSE3) instructions could be used to accelerate Abs() intrinsic for Vector<int>, Vector<short> and Vector(sbyte) when SSE3_4 or AVX instruction set is available.

pabsd
pabsw
pabssb

CC @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
@sivarv you need to escape the "<" when writing generic type names. I think you were listing the integral Vector types, e.g. `Vector<int>`
