### ISSUE TITLE
[ARM32/Linux] libcoreclrtraceptprovider.so build 

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/coreclr#8684]
If we enable building `libcoreclrtraceptprovider.so` by setting `FEATURE_EVENT_TRACE` to 1 (https://github.com/dotnet/coreclr/pull/8421#discussion_r91406080), the build fail with these error messages

```
/nfs/rbp3/coreclr/cross/rootfs/arm/usr/include/urcu/uatomic/generic.h:75:10: error: address argument to atomic builtin must be a pointer to integer or pointer ('void *' invalid)
                return __sync_val_compare_and_swap_4(addr, old, _new);
                       ^                             ~~~~
/nfs/rbp3/coreclr/cross/rootfs/arm/usr/include/urcu/uatomic/generic.h:112:3: error: address argument to atomic builtin must be a pointer to integer or pointer ('void *' invalid)
                __sync_and_and_fetch_4(addr, val);
                ^                      ~~~~
/nfs/rbp3/coreclr/cross/rootfs/arm/usr/include/urcu/uatomic/generic.h:151:3: error: address argument to atomic builtin must be a pointer to integer or pointer ('void *' invalid)
                __sync_or_and_fetch_4(addr, val);
                ^                     ~~~~
/nfs/rbp3/coreclr/cross/rootfs/arm/usr/include/urcu/uatomic/generic.h:190:10: error: address argument to atomic builtin must be a pointer to integer or pointer ('void *' invalid)
                return __sync_add_and_fetch_4(addr, val);
                       ^                      ~~~~
```

We can reproduce this error message by using clang version >= 3.6 and ubuntu 14.04. In other words, we can avoid this fail by using clang < 3.5 or upper version of ubuntu 14.04. (ex. 16.04). But our default build environment for ARM32/Linux is clang-3.6 and ubuntu 14.04.

**Comment by janvorli** [comment]
@hseok-oh if I remember it correctly, there were some problems with pre-3.5 clang, that's why the 3.5 is the minimal supported version.

**Comment by hseok-oh** [comment]
@gkhanna79 It seems better to using patch file in `build-rootfs.sh` script for ubuntu 14.04 rootfs such that tizen does. The script for Tizen rootfs uses https://github.com/dotnet/coreclr/blob/master/cross/armel/tizen/tizen.patch in https://github.com/dotnet/coreclr/blob/master/cross/armel/tizen-build-rootfs.sh.

**Comment by gkhanna79** [comment]
@hseok-oh I am not sure I follow - are you suggesting to use Tizen rootfs for Ubuntu 14.04 Armhf build?

**Comment by hseok-oh** [comment]
@gkhanna79 No. My suggestion is to use additional patch that fix bug in `cross/rootfs/arm/usr/include/urcu/uatomic/generic.h` after build ubuntu armhf 14.04 rootfs. And this patch is for 14.04 armhf rootfs only.

**Comment by hseok-oh** [comment]
I made patch file and fixed build-rootfs.sh. My changes are in https://github.com/hseok-oh/coreclr/tree/fix_8684. I've cancel PR because we need to update CI setting for ARM first.

**Comment by gkhanna79** [comment]
Sounds good @hseok-oh. Please let me know when you are ready to integrate the change in.
