### ISSUE TITLE
Q) Where is "IL_STUB_ReversePInvoke" from?

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#8689]
I'm in the middle of somewhere fixing Reverse P/Invoke Segment fault problem in x86/Linux.
While tracing in assembly codes, I see 
```
DomainNeutralILStubClass:IL_STUB_ReversePInvoke(int,int)
```
method but could not find where it came from. Other JITted codes could be found.
Anyone know where this method is emiited?

**Comment by jkotas** [comment]
The IL for this method is emitted by CreateNDirectStubWorker

**Comment by seanshpark** [comment]
@jkotas , Thank you!
