### ISSUE TITLE
Can CoreCLR run with JIT compilation disabled entirely?

### ISSUE THREAD

**Issue by EvilSteve** [dotnet/coreclr#869]
Hi, 

Sorry if this is the wrong place to ask - I'm new to both CoreCLR and github.

Is it possible to compile CoreCLR in such a way that it only interprets the CIL bytecode rather than generate assembly which is then executed by the CPU? I noticed FEATURE_INTERPRETER, but that appears to still generate assembly code, just in a different way from JIT? I'm interested in running CoreCLR on different CPU architectures and don't want to have to write a whole new JIT compiler, and the platform on which I'm running can't execute code from memory, so JIT compiled code can't really work.

I'm aware that I could precompile the CIL code and then load the assembly containing native code - but as mentioned, the platform on which I'm running doesn't support executing data, and I'm unable to package the assembly as a DLL / shared object equivalent.

And as a follow-up question, is there any documentation for what the various FEATURE_ defines are?

Sorry if this is a stupid question / has already been asked!

Thanks,
Steve

**Comment by jkotas** [comment]
CoreCLR is not able to run without dynamic code generation today. As you have discovered, there are many places that assume ability to generate code dynamically.

**Comment by EvilSteve** [comment]
Bugger, thanks Jan.

Are there any plans to support this in the near future?

Thanks,
Steve

**Comment by jkotas** [comment]
No dynamic runtime code generation is what .Net Native is about. We plan to open source it, but there is no timeline yet.

**Comment by EvilSteve** [comment]
Fair enough. Thanks again Jan!
