### ISSUE TITLE
[x64/Linux] running dotnet as linux daemon fails

### ISSUE THREAD

**Issue by kars93** [dotnet/coreclr#8691]
Excecuting dotnet run /home/tinder/dashboard/Dashboard.Presentation.dll works perfectly fine. 

When this dll is made into a service and the service is running it returns a http 500 error, but there are no errors in the service log (journalctl -u tinder-dashboard -b)

  ```
 [Unit]
    Description=The api for tinder voor werkplekken project

    [Service]
    ExecStart=/usr/bin/dotnet /home/tinder/dashboard/Dashboard.Presentation.dll
    Restart=always
    RestartSec=10
    SyslogIdentifier=dotnet-tinder-dash
    User=www-data
    Environment=ASPNETCORE_ENVIRONMENT=Production

    [Install]
    WantedBy=multi-user.target
```

( Linux version: Ubuntu Xenial (16.04 LTS) (GNU/Linux 4.5.7-std-3 x86_64 ) )

**Comment by janvorli** [comment]
@davidfowl  do you have some insight into running a dotnet ASP app as a service on Linux and what are the pitfalls here?

**Comment by kars93** [comment]
My humble apologies, there was something wrong with permission rights, required folders in the same directory such as /www and /views were not accessible enough. Closing this now.
