### ISSUE TITLE
System.Exception.StackTrace virtual property is not used in base ToString impl.

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/coreclr#8694]
I'm reporting this issue with the expectation that it cannot be fixed, but I'd like someone to consider it anyway.

The Exception.StackTrace property is virtual, so it appears that a derived Exception can provide a custom stack trace implementation. We would like to do this in our application when we get an exception out of a script engine, which would otherwise provide no stack info for the script code. The problem is that even though the StackTrace property is virtual, it isn't very useful to override because the base Exception.ToString() method doesn't use the StackTrace virtual property, but instead calls the private GetStackTrace method (which is what StackTrace calls internally). We can override ToString which is also virtual. However, the base ToString() method also doesn't call the virtual ToString() on the inner exception, but calls the private ToString(bool,bool) method so that doesn't work either. If the base ToString method would call either the virtual StackTrace, or the virtual ToString on the inner exception it would be a lot more useful to provide overrides.

As I said, I suspect this cannot be improved for fear of breaking existing code, but it seems like a bizarre design to have these virtual methods that the base implementation doesn't consume.

**Comment by gkhanna79** [comment]
CC @rahku

**Comment by danmosemsft** [comment]
Tracking with https://github.com/dotnet/corefx/issues/35647
