### ISSUE TITLE
Remove src/mscorlib/ref/mscorlib.cs?

### ISSUE THREAD

**Issue by matekm** [dotnet/coreclr#8702]
Hi,

during the review of the #8174 pull request I was told that 'src/mscorlib/ref/mscorlib.cs' file is not used. So, this issue is just about asking if it's fine to remove that file? If yes, I can raise a pull request that removes it.

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/coreclr/issues/7607
