### ISSUE TITLE
[x86/Linux] Reverse P/Invoke Segment fault

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#8708]
As described in #8612, with CoreFX `CharMinMax.exe` program, I'm trying to find the reason for the segment fault in `HndGetHandleTableADIndex` function. I've traced all the JITted methods after `UmThunkStub`.

```
#0  0xb74016c7 in HndGetHandleTableADIndex (hTable=0x1c)
    at /home/maxwell/netcore/coreclr/src/gc/handletable.cpp:258
#1  0xb7303cfa in MarshalNative::GCHandleInternalCheckDomain (handle=0xbfffda6c)
    at /home/maxwell/netcore/coreclr/src/vm/marshalnative.cpp:819
```
As one can see in the parameter is that `handle=0xbfffda6c` and `hTable=0x1c`. `hTable` is wrong and  `handle` is also wrong value. For my case, should be `0xb63310d0`, when its created in `EnumCalendarInfo()` in `CalendarData.Unix.cs` file.

**Comment by seanshpark** [comment]
I am not sure about the x86 ABI but x86 sends all arguments to the stack but current `TheUMEntryPrestub` and `UMThunkStub` assumes first and second in `ECX` and `EDX`.
So with the `UMThunkMarshInfo__m_cbActualArgSize` value, we should set `ECX` and `EDX` and then reset of the parameters according to the size.
And I don't we don't need to preserve `ECX` and `EDX` in `TheUMEntryPrestub` also.

**Comment by janvorli** [comment]
@seanshpark you are of course right, I have not realized that only the jitted code uses the fastcall calling convention on Linux, but the native code does not. 
In the future, it might make sense to switch the runtime native code to use fastcall by default, but for now, let's fix the helpers.

**Comment by seanshpark** [comment]
@janvori, thank you :)
