### ISSUE TITLE
Using custom master build fails

### ISSUE THREAD

**Issue by choikwa** [dotnet/coreclr#8717]
I've tried following both https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md and https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingCoreRun.md to no avail. The CI also appears to be inaccessible at https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/OfficalAndDailyBuilds.md.

I am having difficulty making custom build work on ubuntu 14.04/16.04/16.10 and Win8.1/Win10.
Does anyone have similar issues as me and know a workaround to make custom builds work?

Thanks in advance.

**Comment by janvorli** [comment]
Can you please describe what is the problem you are hitting?

**Comment by choikwa** [comment]
`dotnet restore` using the supplied project.json file from first link fails. Issues include missing dependencies on System.Linq for Win81-x64. 

2nd link, corerun (i assume one that is build at bin?), fails due to TypeLoadException when trying to load System.IO.TextWriter.

I used to be able to just robocopy entire bin\Product\<prod> into publish folder as described in https://github.com/dotnet/coreclr/blob/master/Documentation/building/viewing-jit-dumps.md but this method works only for getting JIT dump. It started failing some time ago if it had Console.WriteLine due to  dependency on System.IO.TextWriter.

**Comment by choikwa** [comment]
I will try uninstalling .NetCore and just use CoreRun method with pointing to CoreCLR directory... It seems overwriting system packages method does run into compat issues.

**Comment by choikwa** [comment]
Now getting below error
```
c:\git\work\t1\bin\Debug\netcoreapp1.0\win81-x64\publish>corerun t1.dll

Unhandled Exception: System.TypeLoadException: Access is denied: 'System.MarshalByRefObject'.
   at System.Console.WriteLine(String value)
   at ConsoleApplication.Program.Main(String[] args)

Program.cs:
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            BringUpTest.Test();
        }
    }
}
```

**Comment by choikwa** [comment]
Ok, so after I run runtest.cmd once, and point CORE_ROOT to coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root, it seems to work.

In order to build/update newer CoreCLR binary, I did 
`robocopy /e bin\Product\Windows_NT.x64.Debug %CORE_ROOT%`
and it appears to have updated the binary.
