### ISSUE TITLE
Pinvoke support for versioned symbols

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#8721]
## Rationale

Symbol versioning is a mechanism that allows multiple versions of a symbol to exist in an ELF file.
When you link with such a library, your binary will reference a specific version of the symbol.

It would be great if pinvoke can support calling such libraries.

## Api
This requires an additional argument to be specified in the DllImportAttribute that specifies the version. This could be done in the existing EntryPoint field or a new field (e.g. Version).
```
    [DllImport(Library, EntryPoint="foo@VERS_1.1")]
    public static extern void foo();
// OR
    [DllImport(Library, Version="VERS_1.1")]
    public static extern void foo();
```

## Implementation

When a DllImport attribute has a version specified, the symbol should be found using the dlvsym function instead of the dlsym function. The dlvsym function accepts an additional version argument.

## More information

https://sourceware.org/binutils/docs/ld/VERSION.html
https://linux.die.net/man/3/dlvsym

**Comment by jkotas** [comment]
cc @yizhang82

**Comment by tmds** [comment]
To be able to use a 'symver' library I implemented this on top of 1.1: https://github.com/tmds/coreclr/commit/eb2ac5a51b4ca3e9f4040f176dd4d68cf3d5f074. This is using the 'version in EntryPoint' API since that only required changes to the native parts.

I can start a PR on top of master after the holidays.

**Comment by yizhang82** [comment]
@tmds,thanks for submitting the proposal. Have you considered how your proposal would interact with name mangling (https://en.wikipedia.org/wiki/Name_mangling) - those names might include @, such as _foo@8?

**Comment by tmds** [comment]
> @tmds,thanks for submitting the proposal. Have you considered how your proposal would interact with name mangling (https://en.wikipedia.org/wiki/Name_mangling) - those names might include @, such as _foo@8?

Support for calling such functions can only be done by adding additional fields to the DllImport attribute (e.g. Version field).
```
    [DllImport(Library, Version="VERS_1.1")]
    public static extern void foo();
```

**Comment by janvorli** [comment]
@tmds thank you, that's a very useful suggestion.

**Comment by yizhang82** [comment]
@tmds There are existing code that specify EntryPoint with a mangled name:
```
 [DllImport(Library, EntryPoint="_foo@8")]
    public static extern void foo();
```
OR
```
 [DllImport(Library, EntryPoint="foo@@YAHP6AHH@Z@Z")]
    public static extern void foo();
```
Such code would either stop functioning or have an additional binding failure (and fallback to dlsym).
I'm leading towards not having the complexity / ambiguity of parsing the '@' in the entry point. Using Version seems to be a better approach. 

I'm also wondering whether symbol versioning is a common practice (vs versioning the lib). I searched dlvsym usage in github.com and came back exactly 0 usage.

@jkotas @janvorli What do you guys think?

**Comment by janvorli** [comment]
@yizhang82 for example glibc uses it extensively to ensure that apps linked to old version of glibc will work against the latest glibc version just fine.

**Comment by jkotas** [comment]
How do you deal with versioned symbols in C/C++ - if I want to call a particular symbol version in C/C++, how do I do it?

Overloading of the name string or DllImport attribute for this does not seem to be a good idea.

**Comment by janvorli** [comment]
@jkotas, in C++, if you want to get the symbol address explicitly, e.g. when you load the shared library using dlopen, you call the dlvsym (`void *dlvsym(void *handle, char *symbol, char *version)`) function to get the versioned symbol. 
If you try to use just `dlsym`, you'd get the oldest version of the symbol that's present in the shared library (or maybe the first one that was in the linked script), based on what I've read in some online examples.

The other case is when your C++ app is linked to a shared library with versioned symbols at the build time. The header for the shared library then contains something like `__asm__(".symver foo,foo@@@GLIBC_2.x.x");` for each versioned symbol that tells the linker which version of the symbol to use.

**Comment by yizhang82** [comment]
Searching for dlvsym in github gives me 0 hits. And searching for __asm__ .symver gives me 20000+ hits and a quick cursory look of the C/C++ code seems to be fork of some glibc header or some test code (of foo/bar) over and over. It doesn't seem to be a common enough case that warrants special support in the runtime, but I'll be happy to be proven wrong :) 
@janvorli Is glibc using dlvsym internally to hide the versioning details? I wouldn't expect C/C++ developer usually have to worry about symbol versions in their code using __asm (.symver) (unless there are some very specific problems they are trying to solve)

**Comment by jkotas** [comment]
I agree that with @yizhang82 that building it into the runtime does not sound right. If somebody needs this, I think that the best way to make this work is to do it manually or via auto-generated C#. https://github.com/dotnet/roslyn/issues/11475 should make it pretty straightforward and performant.

**Comment by janvorli** [comment]
@yizhang82 you never load glibc using dlopen, it is always being linked to at the compile time. The `__asm__(.symver)` stuff is in the header files of the glibc functions, so there is no interaction with that from the library user point of view.

**Comment by tmds** [comment]
@jkotas @yizhang82 Let me clarify a bit

How it works in the native world:
Step 1:
The symbol versions allow to mark the version of a library that introduces a function. When the function changes in a non-backwards compatible way, the library author will mark the function with a new version identifier. He can decide to keep supporting the old version. This symbol version information is stored in the library based on the asm symver and linker version-script.
Step 2:
When someone links with a library, the resulting binary will refer to the version of the function present at link time. When multiple versions are present it will take the default (which is typically the latest, but may be set otherwise by the library author).
Step 3:
When the binary is used, the loader will use the library present on the system (which can be a different one than the one used at link time). It will use the versions of the functions that were referred at link time.

Bringing this to the .NET Core picture:
Step 1 has already been done by someone else, e.g. glibc.
Step 2 is when we set our DllImport attributes to point to a specific version
Step 3 is when the runtime uses dlvsym to find the specific version

The number of libraries using symbol versions is more a quantity vs quality concern. Libraries implementing this are typically larger libraries concerned with backwards/forwards compatibility. There are less of those, but they are worth calling.

Symver libraries are currently not usable with pinvoke directly. The dlsym call will give you the first version of a function while you want the 'default' version. The workaround is to make a shim library and let the linker figure out the version (step 2) and then pinvoke the shim.

**Comment by tmds** [comment]
@jkotas @yizhang82 @janvorli can one of you be the api-review 'owner' of this issue?
CC @karelz 

The PR (https://github.com/dotnet/coreclr/pull/8773) has a working implementation of the 'version in EntryPoint' API. Based on the discussion so far, I can change this to a DllImportAttribute.Version field API.

**Comment by yizhang82** [comment]
@tmds Based on the discussion above, at this point I don't see a strong reason for us to consider this proposal. Perhaps we should keep the proposal open and see if there are broader interest. In the future, the more likely scenario is probably to support it as part of a broader proposal that supports both library redirection and symbol redirection, and probably not in the runtime.

**Comment by tmds** [comment]
@yizhang82 based on your and @jkotas comments, it seems that you were not familiar with symver. @janvorli was, his first comment being

> @tmds thank you, that's a very useful suggestion.

I had a look on my system what libraries are using symver: keyutils, libsepol, nss, krb5, fuse, openssl, elfutils, uuid, zlib, glibc, ...
These are all major libraries.

Linux provides two functions for finding the address of a symbol: dlsym and dlvsym. The runtime is currently only supporting one.
This is a request to support the other one too.

I am not familiar with compiler intrinsics and don't see how they can be used to implement the dlvsym lookup. Also, it looks like this feature is a backlog feature request, which makes it rather fuzy in what time frame it will get here.

**Comment by jkotas** [comment]
@migueldeicaza What do you think about overloading DllImport EntryPoint to contain symver version?

**Comment by yizhang82** [comment]
>> I had a look on my system what libraries are using symver: keyutils, libsepol, nss, krb5, fuse, openssl, elfutils, uuid, zlib, glibc, ...
>> These are all major libraries.
@tmds This is a very good data point. Thank you.

**Comment by tmds** [comment]
@yizhang82 how do we continue?

**Comment by tmds** [comment]
To give an idea of the tedious nature of maintaining the shim:
It means writing code like this:
```
int wrap_foo(int arg1, char* arg2)
{
   return foo(arg1, arg2);
}
```
Then the magic of symver ensures things don't break with newer versions the library.
However, when compiling the shim, you will need to link it with the exact version of the lib (step 2). This is a burden as your OS may now come with a newer version of the library.

**Comment by migueldeicaza** [comment]
I am familiar with symbol versioning, but didn't know we  oils specify a specific version to link against.   This is very useful to have.

It seems like the glibc developers did not want to overload the meaning of the symbol, perhaps because it could have broken code in ways that were described above, so they made the version an explicit separate parameter.

It looks to me that supporting this feature deserves a separate "String SymbolVersion" property in Dllimport

**Comment by tmds** [comment]
The current API proposal is:

```C#
    [DllImport(Library, SymbolVersion="VERS_1.1")]
    public static extern void foo();
```

@yizhang82 @jkotas how do we continue?

**Comment by jkotas** [comment]
DllImport is hard to extend. C# syntax makes you believe that it is a custom attribute, but it is not actually encoded as custom attribute in the binary for historic reasons. E.g. if you run ildasm on the binary, you won't see the DllImport metadata as custom attribute. Extending the DllImport attribute would be a IL format breaking change and all tools that produce or read IL would need to updated for it. 

It would need to be a new custom attribute, I think. 

Also, there is a design question whether it is a good idea to make runtime recognize this custom attribute or pre-processing tool would be better as @yizhang82 suggested.

**Comment by yizhang82** [comment]
I'd prefer the pre-processing tool approach since it can be shared across all our runtime/toolchain. It's a good opportunity for us to add more x-plat support as well (such as dllmap-like functionality, etc). I'm currently collecting requirements to see what x-plat support would be good candidates to include in the tool and I've put this in the list of potential candidates as well.

**Comment by tmds** [comment]
> DllImport is hard to extend. C# syntax makes you believe that it is a custom attribute, but it is not actually encoded as custom attribute in the binary for historic reasons. E.g. if you run ildasm on the binary, you won't see the DllImport metadata as custom attribute. Extending the DllImport attribute would be a IL format breaking change and all tools that produce or read IL would need to updated for it.

This is a very good point.

Looking at the fields currently available in the `DllImportAttribute`, `ExactSpelling` is an interesting one. When set, the lookup must exactly match the symbol name. Most compilers set this flag to false. When this is the case, after looking for an exact match is not found, the name is suffixed with A/W depending on the CharSet and then a lookup is performed once more.

Name mangling on Linux does not result in '@' signs. The mangling of gcc and clang is the same and is based on the Itanium C++ abi.

This means that a syntax like this can work:

```C#
    [DllImport(Library, EntryPoint="foo@VERS_1.1")]
    public static extern void foo();
```

When `ExactSpelling` is `false` and the EntryPoint contains an '@', first a `dlvsym` lookup can be performed. This won't break existing code, since symbols don't contain '@' characters.

If the mangling would change at some point so it includes an '@' (which is unlikely scenario), then the symbols can still be referenced by setting `ExactSpelling` to `true`.

```C#
    [DllImport(Library, EntryPoint="_foo@8", ExactSpelling=true)]
    public static extern void foo();
```

@jkotas @yizhang82 This would enable the use-case without the need for extra fields, attributes or pre-processing tools. What do you think?

**Comment by tmds** [comment]
TIL: symbols generated by gcc never contain an '@'. This is described in the [gas manual](https://sourceware.org/binutils/docs/as/Symbol-Intro.html#Symbol-Intro):

> A symbol is one or more characters chosen from the set of all letters (both upper and lower case), digits and the three characters `_.$'

clang's mangling is kept in sync with gcc.

**Comment by jkotas** [comment]
Doesn't this just describe the syntax of asm files? The same link also says:

> Symbol names may also be enclosed in double quote " characters. In such cases any characters are allowed, except for the NUL character.

**Comment by tmds** [comment]
@jkotas haven't found anything more specific, taking the irc route:

Quoting [Jason Merrill](https://github.com/gcc-mirror/gcc/blob/master/MAINTAINERS#L146)

> <jason\> tdeseyn: https://itanium-cxx-abi.github.io/cxx-abi/abi.html#mangling is the GCC/clang mangling specification, which doesn't involve @
> <jason\> @ in mangled names is a Visual C++ thing

**Comment by tmds** [comment]
Based on what was discussed, this is a viable option for versioned symbol (dlvsym) lookup:
```C#
    [DllImport(Library, EntryPoint="foo@VERS_1.1")]
    public static extern void foo();
```
The use of the `@` is okay since it does not conflict with gcc/clang mangling.
It also works within the constraint that the `DllImportAttribute` is difficult to extend.

In the unlikely case this syntax would cause trouble, it could be disabled via the `DllImport.ExactSpelling` flag.

```C#
    [DllImport(Library, EntryPoint="_foo@8", ExactSpelling=true)]
    public static extern void foo();
```

I have updated the PR (https://github.com/dotnet/coreclr/pull/8773) to match the above.

As confirmed by @janvorli and @migueldeicaza this is a useful feature.

@yizhang82 and @jkotas have pointed out that this could be implemented via pre-processing. I don't know how to do this. Adding this to the coreclr also makes sense (in my opinion) since `dlvsym` is an extended version of `dlsym`.

@yizhang82 @jkotas I believe this addresses the pitfalls you have pointed out. How do we continue?

**Comment by yizhang82** [comment]
@tmds I agree this feature is useful, however as folks have already pointed out, it is not clear whether overloading the function name is a good idea. There are many platform specific conventions, and we should be mindful when adding those policies into the runtime. Using additional attribute or putting it in a separate configuration (such as dllmap) to make the intention clear might be more desirable. Pulling the support into a separate tool (we are working on a plan) also makes sharing/servicing those conventions/policies easier across different runtimes.

**Comment by tmds** [comment]
> however as folks have already pointed out, it is not clear whether overloading the function name is a good idea

I find it a good idea, that's clear. Especially since we've mitigated the name mangling issue and the EntryPoint would have exactly the same format as the asm sym directives.

> There are many platform specific conventions, and we should be mindful when adding those policies into the runtime.

Right. The PR shows the impact for the runtime.

> Using additional attribute or putting it in a separate configuration (such as dllmap) to make the intention clear might be more desirable.

Since you are proposing an alternate API and implementation. Can you work this out further?
Can you show a code snippit how this would look for foo@VERS_1.1?
What would it entail to add dlvsym lookup? Expecially, where would the dlvsym call live?

Also somewhat important: when is this tool expected (roughly)?

**Comment by tmds** [comment]
@jkotas @yizhang82 can you provide more information about the preprocessing tool to compare it with the API and implementation proposed here? Did you have a look at the PR to access the impact on the runtime?

**Comment by tmds** [comment]
> @jkotas @yizhang82 can you provide more information about the preprocessing tool to compare it with the API and implementation proposed here? Did you have a look at the PR to access the impact on the runtime?

@jkotas @yizhang82 can you please provide more info?

**Comment by jkotas** [comment]
@yizhang82 is on leave for next few weeks. He should be able to comment on this once he is back.

**Comment by migueldeicaza** [comment]
We could use one of the available bits in ImplMap (do not steal my UTF8 Flag!) to flag that the string pointed to will contain two strings, back to back.   The pointer to the string would be the entrypoint, followed by another string would be the version symbol.

This would preserve the file format without changing the table sizes.

**Comment by tmds** [comment]
> We could use one of the available bits in ImplMap (do not steal my UTF8 Flag!) to flag that the string pointed to will contain two strings, back to back. The pointer to the string would be the entrypoint, followed by another string would be the version symbol.

@migueldeicaza it turns out \<symbol>@\<version> can be used as the EntryPoint. gcc&clang follow the c++ itanium abi name mangling rules, which means symbol will never contain '@'! A bit can be used to opt-out of the versioned lookup. ExactSpelling (aka NoMangle) seems like a good match. This is implemented here: https://github.com/dotnet/coreclr/pull/8773. In the test you can see the [C# declarations](https://github.com/tmds/coreclr/blob/960a99593591aa1a3a5b48a0be4daabd30035b65/tests/src/Interop/SymVer/SymVerManaged.cs#L12-L25) and the matching [C declarations](https://github.com/tmds/coreclr/blob/960a99593591aa1a3a5b48a0be4daabd30035b65/tests/src/Interop/SymVer/SymVerNative.cpp#L20-L22).

**Comment by tmds** [comment]
@jkotas @yizhang82 *ping*

**Comment by yizhang82** [comment]
@tmds I chatted with @jkotas @migueldeicaza yesterday about this. Right now we don't feel there is enough interest / evidence suggest that this is a common enough scenario to address at the moment. Adding a feature into the runtime has a non-trivial amount of cost - we need to make sure every runtime that supports netstandard has this feature (or fail properly if the feature isn't present), and that involves CoreCLR, Mono, Desktop, .NET native, and CoreRT. Also, there are some general concerns about adding parsing logic that depends on name mangling that might change over time as tools evolve/emerge, and adding this parsing dependency into runtime has a higher potential maintenance cost. There are relatively straight-forward ways to workaround this - either by adding additional C++ wrapper layers or pinvoke directly to ldsym. Not very pleasant, I agree, but hopefully rare enough that very few folks would run into this. 

As discussed earlier, we are looking into a potential tool that generates code that is portable across all runtimes, and I think that's probably the right place to add features like this. We don't have a concrete time table for the tool yet, and we are currently looking into some possibilities. 

Can we leave this open and let the community vote on this and voice their opinions/concerns? I'll be happy to revisit this once there are enough interest and/or when the tool is in a good shape to take in such features.  

Thanks again for your suggestion.

**Comment by tmds** [comment]
> Right now we don't feel there is enough interest / evidence suggest that this is a common enough scenario to address at the moment. 

This I can understand. I am only one guy asking for this, right?

Consider the new portable linux-x64 .NET Core linux build. It will work across a range of linux distros thanks to glibc symver. This is exactly what symver enables.

Now have another look at the list of libraries I put earlier in this thread. These are major libraries.
They are:
- exclude for pinvoke (you can only call the base version of the symbols)
- we won't be able to benefit of the cross-distro value they bring (you can't call a common version available in many distros)

> we need to make sure every runtime that supports netstandard has this feature (or fail properly if the feature isn't present)

Sounds like a bogus point as they will fail properly when the feature isn't present.

>  Also, there are some general concerns about adding parsing logic that depends on name mangling that might change over time as tools evolve/emerge,

I think this point was addressed enough.
- the mangling is described in the c++ itanium abi
- it is used as a contract between gcc and clang
- the '@' sign is already used for symver
Yes, it is not carved in stone. But its a pretty good bet it won't change. And when hell freezes over, we can set ExactSpelling to true.

> There are relatively straight-forward ways to workaround this - either by adding additional C++ wrapper layers

As described earlier. This is tedious work and it requires you to link to exactly the library you want to target. Which may not be the one that your OS is providing.

> or pinvoke directly to ldsym. Not very pleasant

I am very found of C# PInvoke.

> but hopefully rare enough that very few folks would run into this.

That is looking at it from not providing the feature. The other way around is seeing what you are enabling.

> As discussed earlier, we are looking into a potential tool that generates code that is portable across all runtimes, and I think that's probably the right place to add features like this. We don't have a concrete time table for the tool yet, and we are currently looking into some possibilities.

Sounds promising.

**Comment by yizhang82** [comment]
>> Consider the new portable linux-x64 .NET Core linux build. It will work across a range of linux distros thanks to glibc symver. This is exactly what symver enables.

That's a very interesting point. @gkhanna79 Do you think support symver would help porting CoreCLR to more linux distros?

**Comment by tmds** [comment]
> That's a very interesting point. @gkhanna79 Do you think support symver would help porting CoreCLR to more linux distros?

.NET Core has native libraries. The linux-x64 build is compiled on RHEL 7 since that links it against the oldest version of glibc to be supported.

**Comment by tmds** [comment]
Being forced to the path of native libraries unfortunately also limits the architectures your package supports since you must build for all of them yourself.

**Comment by jeffschwMSFT** [comment]
https://github.com/dotnet/coreclr/pull/19373

**Comment by tmds** [comment]
Closing due to lack of interest.
