### ISSUE TITLE
[RyuJIT/ARM32] A question about LSRA RegPair

### ISSUE THREAD

**Issue by mskvortsov** [dotnet/coreclr#8726]
[lsra.cpp:3442](https://github.com/dotnet/coreclr/blob/94502643d53d5ded7542d9ed883a45be06fdf6e7/src/jit/lsra.cpp#L3442) has the assertion:
```c++
void LinearScan::buildRefPositionsForNode(GenTree*                  tree,
                                          BasicBlock*               block,
                                          LocationInfoListNodePool& listNodePool,
                                          HashTableBase<GenTree*, LocationInfoList>& operandToLocationInfoMap,
                                          LsraLocation currentLoc)
{
#ifdef _TARGET_ARM_
    assert(!isRegPairType(tree->TypeGet()));
#endif // _TARGET_ARM_

```
Is that a NYI or a by design assertion?

This is a part of #8496.

**Comment by mikedn** [comment]
cc @CarolEidt @sivarv

**Comment by mskvortsov** [comment]
I see these words in `target.h`:
```c++
#if defined(_TARGET_X86_)

  #define CPU_LOAD_STORE_ARCH      0

#ifdef LEGACY_BACKEND
  #define CPU_LONG_USES_REGPAIR    1
#else
  #define CPU_LONG_USES_REGPAIR    0       // RyuJIT x86 doesn't use the regPairNo field to record register pairs for long
                                           // type tree nodes, and instead either decomposes them (for non-atomic operations)
                                           // or stores multiple regNumber values for operations such as calls where the
                                           // register definitions are effectively "atomic".
#endif // LEGACY_BACKEND
```
So the answer to my question is "the assertion is by design". I'll look further how multireg calls are implemented for x86.

(And sorry for closing and reopening the issue, that was accidentally).

**Comment by CarolEidt** [comment]
@mskvortsov - yes, it is by design. If we are encountering register pairs with the RyuJIT backend, it probably means that some operation is not being properly handled (either a call that should be handled as a multireg return, or a node that should have been decomposed).

**Comment by sivarv** [comment]
x86 RyuJIT doesn't use regpair to represent TYP_LONG.  A call node returning a long type value is considered a multi-reg call node and is GT_RETURN of long type value.  Arm32 RyuJIT needs to be implemented on the same lines.  Here are some PRs that you might want to have a look at to get an idea of the code paths that needs to be enabled for Arm32 RyuJIT

Disable RegPair for x86
https://github.com/dotnet/coreclr/pull/4965

Enable FEATURE_MULTIREG_RET for x86 RyuJIT
https://github.com/dotnet/coreclr/pull/5184

Enable GT_CALL with long ret types for x86 RyuJIT
https://github.com/dotnet/coreclr/pull/5890

x86 RyuJIT does decomposition of longs during lowering of IR
See decomposelongs.h/.cpp for details.

**Comment by mskvortsov** [comment]
@CarolEidt Thank you!
@sivarv Now I see there are tons of useful info I can take from the past x86 bring up discussions here. Thanks for the links!
