### ISSUE TITLE
Include windows.h in gc.cpp

### ISSUE THREAD

**Issue by bjjzqd** [dotnet/coreclr#873]
I'm experimenting with a hardware feature and I'm trying to make a function call to LookupPrivilegeValue() from within gc.cpp. The function should be included when I do '#include "Windows.h" ', but I'm still getting the error "LookupPrivilegeValue": Identifier not found.

Does anyone have any recommendations?

**Comment by jkotas** [comment]
Try to remove define for WIN32_LEAN_AND_MEAN

https://github.com/dotnet/coreclr/blob/master/CMakeLists.txt#L386

**Comment by bjjzqd** [comment]
Thanks for the suggestion. Unfortunately though, this didn't change the error.

**Comment by janvorli** [comment]
@bjjzqd are you trying that on Unix or Windows?

**Comment by bjjzqd** [comment]
I'm on Windows.

**Comment by bjjzqd** [comment]
I think I have solved the problem. On a hunch I changed the function over to the Unicode version and I was able to build successfully.

**Comment by MattWhilden** [comment]
Cool. Seems like this is resolved now so I'll close it. Let me know if this is in error.
