### ISSUE TITLE
AVX2 flag unset on Win8.1 x64

### ISSUE THREAD

**Issue by choikwa** [dotnet/coreclr#8736]
...by commit 4f0753d to src/vm/codeman.cpp:1226

**Comment by choikwa** [comment]
Verified by inserting code

`printf("test AVX2 %i\n", opts.jitFlags->IsSet(JitFlags::JIT_FLAG_USE_AVX2));`

at importer.cpp:6611

Before: test AVX2 0
After: test AVX2 1

**Comment by jkotas** [comment]
cc @JohnChen0

**Comment by JohnChen0** [comment]
Resolved with PR #8788.
