### ISSUE TITLE
Marshal.StructureToPtr returning inconsistent results

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/coreclr#8742]
I'm seeing `Marshal.StructureToPtr` returning different values between `net461` and `netcoreapp1.0`. Furthermore, running the same code on `netcoreapp1.0` multiple times results in different outcomes.

The struct is declared as follows:

```
[StructLayout(LayoutKind.Sequential, Pack = 4)]
internal struct ConstTestStruct
{
    [MarshalAs(UnmanagedType.U4)]
    public int Number1;

    [MarshalAs(UnmanagedType.U1)]
    public byte Number2;
}
```

When initializing a new value of `ConstTestStruct` as follows:

```
ConstTestStruct s = new ConstTestStruct()
{
    Number1 = 0x12345678,
    Number2 = 0x9a
};
```

my expectation is that `Marshal.StructuretoPtr` will serialize the struct as `0x78 56 34 12 9A 00 00 00` (i.e. the value of `Number1` as little endian, the value of `Number2` and three zero bytes).
Section "I.8.9.7 Value type definition" in ECMA-335 states that "verification rules require that
verifiable code initialize instances to zero", which appears to back my expectation.

However, I'm observing in at least some of my unit tests running on `netcoreapp1.0` that the value of the seventh byte (after `Number2`) is `0x01`, `0x02` or `0x7F`. This never happens on `net461` - the value is always `0x00` as expected.

I've attached a sample zip file which allows me to consistently reproduce the issue with the `preview4` version of the .NET SDK on multiple machines.

Here are the repro steps:

1. Get the repro project from [ConstTestStruct.zip](https://github.com/dotnet/coreclr/files/676043/ConstTestStruct.zip)
2. `dotnet restore`
3. `dotnet test -c Release` (the issue does not reproduce in Debug mode)

And here is the relevant console output on my PC:

```
dotnet --version
1.0.0-preview4-004233

dotnet test -c Release

Test run for [...]\bin\Release\netcoreapp1.0\XUnitTestProject1.dll(.NETCoreApp,Version=v1.0)
Starting test execution, please wait...
Failed   StructRepro.StructHelperTests.WriteStructWithConstTest
Error Message:
 Assert.Equal() Failure
Expected: ListPartition<Byte> [154, 0, 0, 0]
Actual:   ListPartition<Byte> [154, 1, 0, 0]
Stack Trace:


Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
   at StructRepro.StructHelperTests.WriteStructWithConstTest() in [..]\StructHelperTests.cs:line 40Test Run Failed.
Test execution time: 1.4424 Seconds


Test run for [..]\bin\Release\net461\XUnitTestProject1.exe(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Passed   StructRepro.StructHelperTests.WriteStructWithConstTest

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.9279 Seconds
```

**Comment by jkotas** [comment]
The padding bytes in structs are not guaranteed to be zero initialized. E.g. https://github.com/dotnet/coreclr/issues/1305#issuecomment-125914809 is earlier discussion on the same topic.

**Comment by mikedn** [comment]
For completeness here's the IL generated by the C# compiler and the asm code generated by RyuJIT:
```
   .locals init (
        [0] valuetype ConstTestStruct struct2)
    L_0000: ldloca.s struct2
    L_0002: initobj ConstTestStruct
    L_0008: ldloca.s struct2
    L_000a: ldc.i4 0x12345678
    L_000f: stfld int32 ConstTestStruct::Number1
    L_0014: ldloca.s struct2
    L_0016: ldc.i4 0x9a
    L_001b: stfld uint8 ConstTestStruct::Number2
    L_0020: ldloc.0 
    L_0021: call uint8[] Program::StructureToByteArray<valuetype ConstTestStruct>(!!0)
```
```asm
G_M57965_IG01:
       57                   push     rdi
       56                   push     rsi
       4883EC28             sub      rsp, 40
       418BF0               mov      esi, r8d
G_M57965_IG02:
       B978563412           mov      ecx, 0x12345678
       B89A000000           mov      eax, 154
       488D542420           lea      rdx, bword ptr [rsp+20H]
       890A                 mov      dword ptr [rdx], ecx
       884204               mov      byte  ptr [rdx+4], al
       488B4C2420           mov      rcx, qword ptr [rsp+20H]
       E8B9FAFFFF           call     Program:StructureToByteArray(struct):ref
```
The JIT figured out that both struct fields are assigned values and ignored `initobj` and `.locals init`.

**Comment by qmfrederik** [comment]
@mikedn Thanks, that clarifies a lot. Just for my information, would there be a huge performance penalty if the second 4 bytes were initialized with `0x0000009a` instead of just the first byte with `0x9a`? Or, when running on 64-bit, wouldn't it be faster to initialize all 8 bytes at once?

**Comment by mikedn** [comment]
>  if the second 4 bytes were initialized with 0x0000009a instead of just the first byte with 0x9a?

If you could actually store 0x0000009a instead of 0x9a then it would fine from a performance point of view. However, I'm not sure if it is feasible to do this because this kind of store widening is only valid if the object has just been initialized. This can also be problematic when dealing with float fields or dealing with 8 byte alignment on 32 bit platforms.

> Or, when running on 64-bit, wouldn't it be faster to initialize all 8 bytes at once?

Likely. Or at least the code would be smaller.

The code is far from ideal anyway, in general it should look something like:

```asm
       mov      dword ptr [rsp+20H], 0x12345678
       mov      byte  ptr [rsp+24H], 154 ; in theory this could be widened to dword
       mov      rcx, qword ptr [rsp+20H]
       call     Program:StructureToByteArray(struct):ref
```
or even better in this specific case:
```asm
       mov      rcx, 0x9A12345678 ; this gives you zero initialization for free
       call     Program:StructureToByteArray(struct):ref
```

**Comment by qmfrederik** [comment]
I like where this is going, improving performance _and_ initializing the padding with zeros ;-)

**Comment by yizhang82** [comment]
Note that Marshal.StructureToPtr doesn't zero init the buffer as well - it simply copies the entire structure (if it is blittable) or copy field-by-field (if requires marshaling).
