### ISSUE TITLE
crossgen issue

### ISSUE THREAD

**Issue by cocotr** [dotnet/coreclr#8749]

**Comment by jkotas** [comment]
@cocotr Could you please add description of the issue?

**Comment by cocotr** [comment]
When I am trying to crossgen on Windows or Linux I am always getting similar error:

Error: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
Error compiling ConsoleApp5.dll: Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
Error: compilation failed for "ConsoleApp5.dll" (0x80131621)

**Comment by janvorli** [comment]
Can you also share the full command line you have used to invoke crossgen on your assembly?

**Comment by gkhanna79** [comment]
@cocotr Do you have a repro for this issue?

CC @rahku

**Comment by gkhanna79** [comment]
Closing since there are no repro details. Please feel free to reopen once a repro is available.
