### ISSUE TITLE
ECMA/JIT/Roslyn switch value inconsistency

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#8760]
IL `switch` description from the ECMA spec doesn't clearly state what type the switch value is expected to have:
```
The switch instruction pops value off the stack and compares it, as an unsigned integer, to n. 
```
Note that it says "unsigned integer", not "unsigned int32". Contrast this with the `ldelem` description that states:
```
The ldelem instruction loads the value of the element with index index (of type native int
or int32) in the zero-based one-dimensional array array
```

Now, RyuJIT64 happily accepts any integer type (importer code has `assertImp(genActualTypeIsIntOrI(op1->TypeGet()));`) and if the type is not already `TYP_I_IMPL` (aka `native int`) then it sign extends the switch value to `TYP_I_IMPL`. The fact that it sign extends seems odd considering that after that we have an unsigned compare.

On the other hand Roslyn seems to think that IL `switch` accepts only `unsigned int32` and if you try to switch on a `long` it generates IL code like:
```
    IL_0007:  ldloc.0
    IL_0008:  dup
    IL_0009:  ldc.i4.2
    IL_000a:  conv.i8
    IL_000b:  ble.un.s   IL_0010

    IL_000d:  pop
    IL_000e:  br.s       IL_002d

    IL_0010:  conv.u4
    IL_0011:  switch     (
                          IL_0024,
                          IL_0027,
                          IL_002a)
```
It does a separate check to see if the `long` value is within range and the converts it to `unsigned int32`. This wouldn't be necessary if IL `switch` does in fact accept any integral types.

In the end we get code like:
```asm
G_M57965_IG02:
       488B4228             mov      rax, qword ptr [rdx+40]
       4883F802             cmp      rax, 2
       7732                 ja       SHORT G_M57965_IG10
G_M57965_IG03:
       4863D0               movsxd   rdx, eax
       4883FA02             cmp      rdx, 2
       7729                 ja       SHORT G_M57965_IG10
       488D052E000000       lea      rax, [reloc @RWD00]
       8B0490               mov      eax, dword ptr [rax+4*rdx]
       488D0DDCFFFFFF       lea      rcx, G_M57965_IG02
       4803C1               add      rax, rcx
       FFE0                 jmp      rax
```
I'm not sure what needs to happen here. Maybe the spec needs to be clarified, maybe the JIT simply decided to be more relaxed and IL `switch` indeed accepts only `unsigned int32`.

I'd be happy to hear an explanation for the sign extension that happens in the JIT importer. The code generated for a switch is already pretty large as is and doing sign extend instead of zero extend just wastes a byte. IMO the importer should not do anything here, it's codegen's job to zero extend the switch value before using it for indexing the switch table.

**Comment by mikedn** [comment]
> Now, RyuJIT64 happily accepts any integer type (importer code has assertImp(genActualTypeIsIntOrI(op1->TypeGet()));) 

That's not quite true, the verifier rejects non-INT types:

```C++
if (tiVerificationNeeded)
{
    Verify(impStackTop().seTypeInfo.IsType(TI_INT), "Bad switch val");
}
```
This makes the sign extension of the switch value even more questionable.

**Comment by sivarv** [comment]
CC @dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
@CarolEidt Can you suggest the right way to resolve this inconsistency?

**Comment by CarolEidt** [comment]
>> `The switch instruction pops value off the stack and compares it, as an unsigned integer, to n.`

> Note that it says "unsigned integer", not "unsigned int32".

But the instruction format shows that it is expecting an unsigned int 32:

**III.3.66 switch – table switch based on value**

| Format | Assembly Format | Description
|---|---|---
|45 \<unsigned int32\> \<int32\>… \<int32\> | switch ( t1, t2 … tN ) | Jump to one of n values.

So I think that @mikedn is right and we should be zero-extending.
