### ISSUE TITLE
Optimize statics JIT helpers on x64 and arm64

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#8761]
The statics JIT helpers on x64 and arm64 are missing optimization for the single domain case.

https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=JIT_GetSharedNonGCStaticBase_SingleAppDomain and friends.

**Comment by rahku** [comment]
Fixed by PR https://github.com/dotnet/coreclr/pull/10912
