### ISSUE TITLE
Dependencies on unmaintained implementations of types in corelib

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#8763]
**Problem:** Currently, there are certain types that have files both in coreclr and corefx. The corefx version is usually the actively maintained version, while the coreclr one is poorly formatted and unmaintained. Examples: [`ArrayList`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/ArrayList.cs), [`Directory`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Directory.cs).

We want to remove the old implementations living in coreclr, however sometimes there is other code living in the repo that depends on that class. This is an issue to keep track of all such types, and discuss whether we should

- Move the implementation from corefx to coreclr, or
- Refactor the coreclr version to use lower-level abstractions

**Context:**

- https://github.com/dotnet/coreclr/pull/8753#issuecomment-269809868
- https://github.com/dotnet/coreclr/pull/8753#issuecomment-269819652

**List of types:**

- [ ] `Directory` and `File`
  - Used by: `TimeZoneInfo` ([here][1], [here][2])
  - Transitive dependencies: `StreamReader`, `TextReader`, types in `FileSystemEnumerable.cs`
- [ ] `ArrayList` and `Hashtable`
  - Used by: A fair amount of code ([ArrayList][3], [Hashtable][4])
    - However, these sites can just be refactored to use `List<object>` or `Dictionary<object, object>` respectively
- [ ] Concurrent collections
  - Used by: Search results for [ConcurrentQueue][5], [ConcurrentStack][6], [ConcurrentDictionary][7]

cc @jkotas @JeremyKuhne @justinvp 

[1]: https://github.com/dotnet/coreclr/blob/2e67c8f8a95dddd5716e1b60705ff63c5a09a805/src/mscorlib/src/System/TimeZoneInfo.Unix.cs#L409
[2]: https://github.com/dotnet/coreclr/blob/2e67c8f8a95dddd5716e1b60705ff63c5a09a805/src/mscorlib/src/System/TimeZoneInfo.Unix.cs#L238
[3]: https://github.com/dotnet/coreclr/search?l=C%23&q=ArrayList&type=Code&utf8=%E2%9C%93
[4]: https://github.com/dotnet/coreclr/search?l=C%23&q=Hashtable&type=Code&utf8=%E2%9C%93
[5]: https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=ConcurrentQueue
[6]: https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=ConcurrentStack
[7]: https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=ConcurrentDictionary

**Comment by jamesqo** [comment]
I ran into more cases besides Directory/File, so generalizing this issue to include all such types.

**Comment by danmosemsft** [comment]
@jamesqo this would make it easier for us to sync CoreCLR with CoreRT corelibs in the near future, so it would be great. Do you plan to give it a shot and if so by when do you expect?

**Comment by jamesqo** [comment]
@danmosemsft If I do this it will probably be after fixing #4651 because that yields more gain with the same effort. In the meantime though this can probably be marked up for grabs since it won't conflict with the changes necessary to fix that issue.

**Comment by gkhanna79** [comment]
CC @AlexGhiondea

**Comment by gkhanna79** [comment]
For now, I am parking this in future. It will be good to get this addressed for 2.0, so if someone starts to make progress on this, please adjust the milestone appropriately.

**Comment by danmosemsft** [comment]
@gkhanna79 I'm assuming this is part of our UWP work (at least in large part) since it makes it harder to sync the corelibs.

**Comment by gkhanna79** [comment]
Possibly. Can you please assign it to appropriate individual(s)?

**Comment by danmosemsft** [comment]
@jamesqo I think after the scads of deleting and reformatting we did since you opened this, we're in a pretty good state. There are some types (eg Dictionary) that we still have in both CoreFX and CoreCLR. In that case it's because while we need it in corelib for code there to use, we want a "live" one in CoreFX for folks to contribute to and optimize. (In such a case ideally we're rename eg LowLevelDictionary as we did for LowLevelConsole -- separate issue)

I'm going to close this -- please do open a new issue if there's more that needs attention.
