### ISSUE TITLE
[ARM32/softfp] Using armel instead of arm-softfp for ARM32 with softfp ABI

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#8770]
In CoreCLF and CoreFX, we use `arm-softfp` to indicate ARM32 with softfp ABI.

We are using following commands to build ARM32 softfp now.
```
$ ./cross/build-rootfs.sh arm-softfp
$ ./build.sh arm-softfp cross
```
However arm-softfp is not a common name and it is weired to use `arm-softfp` in rid.
For example,  rid is `ubuntu.14.04-arm`  for ARM32 (hardfp) now and  `debian.8-arm-softfp` might be a candidate rid for arm-softfp, but it's very weired to have another `-` in rid.

Threfore how about using `armel` instead of `arm-softfp` ?
Then rid for arm-softfp might be `<linux id>.<version id>-armel`, e.g. debian.8-armel.

In Ubuntu, armel means ARM with softfp ABI (See https://wiki.ubuntu.com/ToolChain)
> armel: soft-float ABI / hard-float ABI, defaulting to arm-linux-gnueabi.
> armhf: hard-float ABI / soft-float ABI, defaulting to arm-linux-gnueabihf. 

Also similar In Debian. (See https://wiki.debian.org/ArmEabiPort) and we use `armel` port of Debian "jessie" for `arm-softfp` rootfs. (Code at  https://github.com/dotnet/coreclr/blob/master/cross/build-rootfs.sh#L42.)

This is also being discussed at https://github.com/dotnet/core-setup/issues/725.

**Comment by hseok-oh** [comment]
LGTM

**Comment by hqueue** [comment]
Closing, because #8771 was merged.
