### ISSUE TITLE
Perfcollect problem inside docker using configuration from linux-performance-tracing.md

### ISSUE THREAD

**Issue by j33zy** [dotnet/coreclr#8782]
Linux kernel version: 4.4.0-57-generic
Docker version: 1.12.5, build 7392c3b
OS: Ubuntu 16.04.1 LTS

Problem description:
Cannot collect performance data using tutorial located in https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md
Command perfollect is failing in different ways

**Reproduction:**
Using example Dockerfile from: https://raw.githubusercontent.com/dotnet/corefx-tools/master/src/performance/perfcollect/docker-demo/Dockerfile
Building: docker build -t perfcollect .
Starting: docker run -d perfcollect
Then I execute: docker exec -it --privileged <container_id> /bin/bash 
and I'm getting inside container as root user.
Next commands are:
cd /perf
export COMPlus_PerfMapEnabled=1
export COMPlus_EnableEventLog=1

**sudo ./perfcollect collect sampleTrace
Output from this command:**
root@07d9f020d1b7:/perf# sudo ./perfcollect collect sampleTrace
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-57-generic/modules.dep.bin'
Error: Unable to load module lttng-tracer
Error: Unable to remove module lttng-tracer
Warning: No kernel tracer available

**And terminal hangs.
After ctrl+c command output is:**
^CError: Unable to remove module lttng-ring-buffer-metadata-mmap-client
Error: Unable to remove module lttng-ring-buffer-client-mmap-overwrite
Error: Unable to remove module lttng-ring-buffer-client-mmap-discard
Error: Unable to remove module lttng-ring-buffer-metadata-client
Error: Unable to remove module lttng-ring-buffer-client-overwrite
Error: Unable to remove module lttng-ring-buffer-client-discard
Error: Unable to remove module lttng-lib-ring-buffer
Error: Unable to remove module lttng-tracer
tput: unknown terminal "unknown"
Collection started. Press CTRL+C to stop.
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"

tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
...STOPPED.
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"

tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
Starting post-processing. This may take some time.
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"

tput: unknown terminal "unknown"
zero-sized file (perf.data), nothing to do!
tput: unknown terminal "unknown"
Generating native image symbol files
tput: unknown terminal "unknown"
zero-sized file (perf.data), nothing to do!
tput: unknown terminal "unknown"
...SKIPPED
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
Saving native symbols
tput: unknown terminal "unknown"
zero-sized file (perf.data), nothing to do!
tput: unknown terminal "unknown"
...FINISHED
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
Exporting perf.data file
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
...FINISHED
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
Compressing trace files
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
...FINISHED
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
Cleaning up artifacts
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
...FINISHED
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"

tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
Trace saved to sampleTrace.trace.zip
tput: unknown terminal "unknown"

**Trying same things skipping 'sudo' in command 'sudo ./perfcollect collect sampleTrace'**
root@c90d31853aa8:/perf# ./perfcollect collect sampleTrace
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-57-generic/modules.dep.bin'
Error: Unable to load module lttng-tracer
Error: Unable to remove module lttng-tracer
Warning: No kernel tracer available`
**And it hangs again
After ctrl+c:**
^CError: Unable to remove module lttng-ring-buffer-metadata-mmap-client
Error: Unable to remove module lttng-ring-buffer-client-mmap-overwrite
Error: Unable to remove module lttng-ring-buffer-client-mmap-discard
Error: Unable to remove module lttng-ring-buffer-metadata-client
Error: Unable to remove module lttng-ring-buffer-client-overwrite
Error: Unable to remove module lttng-ring-buffer-client-discard
Error: Unable to remove module lttng-lib-ring-buffer
Error: Unable to remove module lttng-tracer
tput: No value for $TERM and no -T specified
Collection started. Press CTRL+C to stop.
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified

tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
...STOPPED.
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified

tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
Starting post-processing. This may take some time.
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified

tput: No value for $TERM and no -T specified
zero-sized file (perf.data), nothing to do!
tput: No value for $TERM and no -T specified
Generating native image symbol files
tput: No value for $TERM and no -T specified
zero-sized file (perf.data), nothing to do!
tput: No value for $TERM and no -T specified
...SKIPPED
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
Saving native symbols
tput: No value for $TERM and no -T specified
zero-sized file (perf.data), nothing to do!
tput: No value for $TERM and no -T specified
...FINISHED
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
Exporting perf.data file
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
...FINISHED
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
Compressing trace files
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
...FINISHED
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
Cleaning up artifacts
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
...FINISHED
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified

tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
Trace saved to sampleTrace.trace.zip
tput: No value for $TERM and no -T specified

**Next try is to set TERM=xterm before running commands
export TERM=xterm
./perfcollect collect sampleTrace
And command hangs again on:**
root@94daf80dd5e9:/perf# ./perfcollect collect sampleTrace
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-57-generic/modules.dep.bin'
Error: Unable to load module lttng-tracer
Error: Unable to remove module lttng-tracer
Warning: No kernel tracer available

**After ctrl+c:**
^CError: Unable to remove module lttng-ring-buffer-metadata-mmap-client
Error: Unable to remove module lttng-ring-buffer-client-mmap-overwrite
Error: Unable to remove module lttng-ring-buffer-client-mmap-discard
Error: Unable to remove module lttng-ring-buffer-metadata-client
Error: Unable to remove module lttng-ring-buffer-client-overwrite
Error: Unable to remove module lttng-ring-buffer-client-discard
Error: Unable to remove module lttng-lib-ring-buffer
Error: Unable to remove module lttng-tracer
Collection started. Press CTRL+C to stop.

...STOPPED.

Starting post-processing. This may take some time.

zero-sized file (perf.data), nothing to do!
Generating native image symbol files
zero-sized file (perf.data), nothing to do!
...SKIPPED
Saving native symbols
zero-sized file (perf.data), nothing to do!
...FINISHED
Exporting perf.data file
...FINISHED
Compressing trace files
...FINISHED
Cleaning up artifacts
...FINISHED

Trace saved to sampleTrace.trace.zip`

**Running command once again, output:**
`root@94daf80dd5e9:/perf# ./perfcollect collect sampleTrace
Collection started. Press CTRL+C to stop.

...STOPPED.

Starting post-processing. This may take some time.

zero-sized file (perf.data), nothing to do!
Generating native image symbol files
zero-sized file (perf.data), nothing to do!
...SKIPPED
Saving native symbols
zero-sized file (perf.data), nothing to do!
...FINISHED
Exporting perf.data file
...FINISHED
Compressing trace files
...FINISHED
Cleaning up artifacts
...FINISHED

Trace saved to sampleTrace.trace.zip

**Command is ending without hitting ctrl+c, soon after start.**

**Comment by DigitalRasta** [comment]
I've installed this lib on host and inside docker: https://launchpad.net/~lttng/+archive/ubuntu/ppa/
And after these errors disappeared:
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-57-generic/modules.dep.bin'
Error: Unable to load module lttng-tracer
Error: Unable to remove module lttng-tracer

But still I'm getting errors with TERM
And still if I set TERM=xterm command is automatically stopping soon after start.

**Comment by xcyroo** [comment]
hello, perfcollect script does not work for me on Debian with linux-tools 4.9 installed. It says "linux-tools-3.16 is not installed".
Do I need to downgrade linux-tools or is there any other way to make this working?
Thanks,

Peter

**Comment by brianrob** [comment]
@DigitalRasta, if you run the whole container privileged, do you get data as well?  From your original post, it looks like perf is not capturing any events:

zero-sized file (perf.data), nothing to do!

Also, FYI, you will need to run these commands as part of your DockerFile prior to starting your app, as they need to be set in the context of the running app:

export COMPlus_PerfMapEnabled=1
export COMPlus_EnableEventLog=1

**Comment by danmosemsft** [comment]
@brianrob is this resolved? If so please close. Otherwise please move to Future if appropriate

**Comment by brianrob** [comment]
Will close this for now.  @j33zy, please let me know if you have additional questions here.
