### ISSUE TITLE
DllImport not finding dylib on Mac

### ISSUE THREAD

**Issue by czifro** [dotnet/coreclr#8790]
I was recommended by @yizhang82 to start here (originated [here](https://github.com/dotnet/core/issues/181)). I am working on a thesis project in F# that is a network protocol for ftp (which is broken up into two projects, a lib and test). I am currently trying to optimize the file write through P/Invoke on the lib project. The P/Invoke adds flags to the `open` call. Most of the code is snippets from corefx with the additions that are specific to my project. I successfully created dylibs for both Mac and Linux. In my F# code I have `extern`functions with the DllImport referencing the names of the dylibs. However, when I run the lib code through the unit tests, I get the following error:

```
Error Message:
 System.DllNotFoundException : Unable to load DLL 'MUDT.Native.Apple': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
Stack Trace:
   at MUDT.IO.FileStreamHelper.OpenApple(String filename, OpenFlags flags, Int32 mode)
   at MUDT.IO.FileStreamHelper.openHandle(String filename, OpenFlags flags, Int32 mode)
   at MUDT.IO.FileStreamHelper.getUnixFileStream(String filename, FileAccess access, Int32 bufferSize)
   at MUDT.IO.MemoryMappedFile.partitionFile@95.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at MUDT.IO.MemoryMappedFile.partitionFile(Boolean isRead, MemoryMappedFileStateConfig config)
```

The project is [located here](https://github.com/czifro-tech/mudt).

I have only tested it on macOS since that is my dev env (Linux lib is for when I get to testing using Linux server). The steps to recreating are:

- from `fsharp` directory, run `sh build-native.sh`, once finished, new directory `.native` will contain dylibs
- `dotnet restore` both src and test
- run `dotnet run -- 3.2` from test directory

I have done various things to try and fix the problem, all of which I outlined here: http://stackoverflow.com/questions/41432671/unable-to-load-dll-dotnet-core

Any help is greatly appreciated!

**Comment by yizhang82** [comment]
Hi czifro,
I couldn't repro your issue. This is what I'm seeing using CLI Preview 4:

Starting test execution, please wait...
Failed   MUDT.Test.MemoryMappedFileUnitTest.Speed Test Non Network File Transfer With No Integrity
Error Message:
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:


Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
   at MUDT.Test.MemoryMappedFileUnitTest.Speed Test Non Network File Transfer With No Integrity()Test Run Failed.
Test execution time: 1.1392 Seconds

Having said that, this does look like another similar packaging issue from your description.  

@piotrpMSFT Do we have any doc on how to package native libraries in project files in CLI?

**Comment by czifro** [comment]
@yizhang82, I did not catch this until now. The unit test is simulating a perfect file transfer by copying a file from one place on disk to another. Since it is a test it assumes the file exists. [This line](https://github.com/czifro-tech/mudt/blob/master/fsharp/test/MemoryMappedFileUnitTest.fs#L47) and the other two strings will need to be set to paths of existing files. The reason that an exception was not thrown about the file not existing is because `MemoryMappedFile.tryGetFileInfo` returns an `Option`. I'm apologize for not catching/stating this sooner. I'm certain that if you point it to an actual file and the other two to a destination, you'll see the error I'm running into.

**Comment by piotrpMSFT** [comment]
@nguerrera should be able to answer the general question of how native binaries should be included by a proj file. @enricosada for any fsharp-specific caveats.

**Comment by czifro** [comment]
I modified the test to allow user input to specify the input file and an output file for easier reproducibility. I noticed though that the prompts do not appear until after the input is entered, test runner may be at fault for that. I do recommend fetching latest commit.

**Comment by czifro** [comment]
I just wanted to add that I tried moving the dylibs to `/usr/include` since the lib used [here](https://github.com/dotnet/corefx/blob/79d44f202e4b6d000ca6c6885a24549a55db38f1/src/System.Console/src/Interop/Interop.manual.Unix.cs) is located there. That did not work though.

@nguerrera @enricosada I changed the way tests are executed. to run the test in question do `dotnet run -- 3.2`.

**Comment by czifro** [comment]
@piotrpMSFT, I am still struggling with this issue. I am certain I'm not doing something right, but I have no idea what it is.

**Comment by yizhang82** [comment]
@czifro I'm closing this issue for now. If you are still seeing this issue, please open another issue with latest information and @livarcocc @piotrpMSFT
