### ISSUE TITLE
System.Buffers' Nuget targets netstandard only; causing issues

### ISSUE THREAD

**Issue by MichaCo** [dotnet/coreclr#8795]
I'm using the System.Buffers package in one of my class libraries.
The library is targeting netstandard AND NET4.5.

For NET4.5, I have to add...

    "net45": {
      "frameworkAssemblies": {
        "System.Runtime": "4.0.0.0"
      }
    }

...to project.json to make it work, otherwise I'm getting compiler errors 

> The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'...

Now, when I do so and consume that ClassLibrary as a Nuget from a Full Framework project, Nuget cannot install it stating it cannot find "System.Runtime" in GAC:

> Failed to add reference. The package '...' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

So far, all packages I consume from System.* usually target multiple frameworks, not only netstandard, and that always works. 
Is that something intentional for System.Buffers? Or how can I fix that on my side?

Thanks,
M

**Comment by janvorli** [comment]
CC: @richlander

**Comment by davidfowl** [comment]
@MichaCo The answer is very complicated, suffice to say that it'll be fixed once we move back to msbuild. Here's the issue https://github.com/dotnet/cli/issues/164

**Comment by gkhanna79** [comment]
@davidfowl @MichaCo Should we close this issue in favor of dotnet/cli#164, since this is not a runtime (CoreCLR) issue?

**Comment by MichaCo** [comment]
sure
