### ISSUE TITLE
Code Review & CLA

### ISSUE THREAD

**Issue by MitchK** [dotnet/coreclr#88]
We are developing two open source GitHub tools that focus on pull request code review and content license agreements for GitHub contributions. 

 * https://github.com/reviewninja/review.ninja (http://review.ninja)
 * https://github.com/cla-assistant/cla-assistant (http://cla-assistant.io)

Keep up your great work with CoreCLR :+1: 

Cheers,
Mitch

**Comment by ellismg** [comment]
Thanks for the heads up.  For what it's worth, we already have our own workflows for both code reviews and CLAs.
