### ISSUE TITLE
dnu restore for coreclr on CentOS does not work

### ISSUE THREAD

**Issue by rohshall** [dotnet/coreclr#882]
% cat /etc/centos-release
CentOS Linux release 7.1.1503 (Core) 

# When I use mono to run my HelloWorld project

 % dnvm use 1.0.0-beta5-11657 -r mono
Adding /home/swadnerkar/.dnx/runtimes/dnx-mono.1.0.0-beta5-11657/bin to process PATH
swadnerkar@localhost ~/Programming/C#/HelloWorld
 % dnu restore                       
Restoring packages for /home/swadnerkar/Programming/C#/HelloWorld/project.json

 % dnx . run
Hello, Linux
Love from CoreCLR.

# When I use coreclr to run my HelloWorld project

swadnerkar@localhost ~/Programming/C#/HelloWorld
 % dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta5-11657    mono         ~/.dnx/runtimes      default
       1.0.0-beta5-11657    coreclr x64  ~/.dnx/runtimes      

swadnerkar@localhost ~/Programming/C#/HelloWorld
 % dnvm use 1.0.0-beta5-11657 -r coreclr
Adding /home/swadnerkar/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta5-11657/bin to process PATH

 % dnu restore                             
System.TypeInitializationException: The type initializer for 'Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole' threw an exception. ---> System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Framework.PackageManager.Program.CreateReports(Boolean verbose, Boolean quiet)
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_1.<<Main>b__2>d.MoveNext()
System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()

**Comment by davidfowl** [comment]
dnu doesn't work on coreclr yet

**Comment by ellismg** [comment]
What @davidfowl said is correct.  We are working on getting dnu to work on CoreCLR.  You can follow along in [aspnet/dnx](https://github.com/aspnet/dnx).
