### ISSUE TITLE
[RyuJIT/x86/Checked] ngen dump assert

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#8824]
On the last build when I try to execute `coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root>crossgen.exe System.Private.CoreLib.dll  with complus_ngendump=* `
I see:
```
RESOLVING BB BOUNDARIES
-----------------------
Resolution Candidates:
Assert failure(PID 14924 [0x00003a4c], Thread: 17084 [0x42bc]): Assertion failed 'varNum < comp->lvaCount' in 'SR:get_ArgumentOutOfRange_Enum():ref' (IL size 11)

    File: c:\git\coreclr\src\jit\compiler.cpp Line: 8106
    Image: C:\git\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\crossgen.exe
```
x64 works fine. Looks like it is a fresh problem.

**Comment by mikedn** [comment]
Likely broken by #8207. `identifyCandidates` is supposed to initialize `resolutionCandidateVars` but it doesn't do so if `lvaCount` is 0. When `dumpConvertedVarSet` tries to enumerate it the set sometimes happen to have set bits (0xFFFFFFFF usually) but there are no lclvars so the assert fires. As far as I can tell there may be other code (`buildIntervals` at least) that uses the set even if `lvaCount` is 0 so there may be other issues in addition to that dump assert.

cc @CarolEidt

**Comment by adiaaida** [comment]
Confirmed that @CarolEidt introduced this.

**Comment by CarolEidt** [comment]
Yes, sorry - I noticed this working on another change, and put a fix in with that change, but as that's not yet ready I will make this change separately.
