### ISSUE TITLE
Remove desktop-only code from corelib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#8857]
We do not need to retain the ability for coreclr's corelib to build for desktop. It has probably rotted anyway.

Diffing the defines I see in \src\mscorlib with the defines I see going to the compiler, code marked with these defines seems eligible for removal (either the code, or the define from code)

- [x] FEATURE_ADVANCED_MANAGED_ETW_CHANNELS
- [x] FEATURE_CASE_SENSITIVE_FILESYSTEM
- [x] FEATURE_CODEPAGES_FILE
- [x] FEATURE_COMINTEROP_MANAGED_ACTIVATION
- [x] FEATURE_COMINTEROP_WINRT_DESKTOP_HOST
- [x] FEATURE_COMPRESSEDSTACK
- [x] FEATURE_CRYPTO
- [x] FEATURE_LEAK_CULTURE_INFO
- [x] FEATURE_LEGACYSURFACE
- [x] FEATURE_LINK_DEMAND
- [x] FEATURE_METHOD_RENTAL
- [x] FEATURE_NORM_IDNA_ONLY
- [x] FEATURE_PLS
- [x] FEATURE_RWLOCK
- [x] FEATURE_SERIALIZATION
- [x] FEATURE_UNSAFE_CONTRACTS
- [x] FEATURE_X509
- [x] FEATURE_X509_SECURESTRINGS

This is just the `FEATURE_` ones, perhaps some others, here are the files:
[alldiffsincode.txt](https://github.com/dotnet/coreclr/files/694509/alldiffsincode.txt)
[alldiffsincompiler.txt](https://github.com/dotnet/coreclr/files/694510/alldiffsincompiler.txt)

Desktop specific build functionality including 

- [ ] https://github.com/dotnet/coreclr/blob/master/clr.desktop.props

 can presumably go also.

Care to not trample on concurrent https://github.com/dotnet/coreclr/issues/4651 work by @jamesqo although many of these will be in code he's not removing, also a delete of some code in a file ought to merge fine with a delete of the file itself.

@jkotas is the above correct?

**Comment by danmosemsft** [comment]
Removed the reference to https://github.com/dotnet/coreclr/blob/master/clr.desktop.props above, that's relevant to the native side as well so let's ignore it for this issue.

**Comment by jkotas** [comment]
> @jkotas is the above correct?

Some of the above ifdefs are set differently for Windows/Unix - they should stay:

```
FEATURE_COREFX_GLOBALIZATION
FEATURE_ACTIVITYSAMPLING
FEATURE_STUBS_AS_IL
```

Otherwise, it should be generally correct.

> that's relevant to the native side as well so let's ignore it for this issue.

This file is not used on the unmanaged side. All unmanaged builds are done via cmake. It is safe to assume that anything msbuild has to do with managed code.

Also, it would be nice to cleanup these from both managed and unmanaged sides at the same time for sanity. Most of these ifdefs are on both sides.

**Comment by danmosemsft** [comment]
I've removed those 3 from the list. 

For sure we should remove from the native side also but it seems reasonable to split into 2 pieces of work. The native can be later if we need to as it's not needed to sync code.

**Comment by jkotas** [comment]
Deleting the code under defines in a few more files should cost next to nothing extra and it is nice to maintain self-consistency ... but if you prefer to do it in two passes, I do not have a problem with it.

**Comment by danmosemsft** [comment]
Flip side of this (removing define, not removing code) is https://github.com/dotnet/coreclr/issues/8883.

**Comment by danmosemsft** [comment]
These are also present in CoreRT code, so would have the same change there

FEATURE_LINK_DEMAND
FEATURE_RELIABILITY_CONTRACTS
FEATURE_SERIALIZATION
FEATURE_UNSAFE_CONTRACTS

**Comment by danmosemsft** [comment]
Discovered a tool that will remove this stuff for us (at least simple cases)

Build https://github.com/dotnet/codeformatter then eg `C:\git\codeformatter\bin\DeadRegions\Debug\DeadRegions.exe System.ComponentModel.TypeConverter.csproj /disable VERIFY_REFLECTION_CHANGE /edit`

will remove all regions active only when VERIFY_REFLECTION_CHANGE  is defined

**Comment by danmosemsft** [comment]
Completed by 6fca5f4
