### ISSUE TITLE
Enlarge MAX_PATH in PAL / coreclr on Unix

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#886]
Currently, PAL defines MAX_PATH to the same value as Windows, that means 260 characters. However, Unix paths can be much longer than that so we should handle them properly.

**Comment by stephentoub** [comment]
Dup of #731?

**Comment by janvorli** [comment]
Ah, I haven't noticed we already have a issue for that. Closing.

**Comment by stephentoub** [comment]
Or, I guess we have this defined in multiple places, both in native in the PAL and in managed in mscorlib, and this issue is about the former. It'd be good to update all of them together, I think.

**Comment by janvorli** [comment]
Ah, you are right, this is about the PAL / coreclr

**Comment by jasonwilliams200OK** [comment]
This is tricky on non-Windows systems as most modern *NIXes support something like loadable kernel filesystem modules. So now entire types of filesystem can come and go at the whim of the sysadmin. Additionally, some FS don't even possess any limitation on path size (virtually unlimited; equal to the available RAM!):

Some references:
* http://stackoverflow.com/q/4267390
* http://stackoverflow.com/q/833291
* http://stackoverflow.com/q/9449241

One approach could be to use standard C's `FILENAME_MAX` constant defined in `stdio.h`. But see [this caution](http://stackoverflow.com/a/6510535):

> FILENAME_MAX is part of the ISO C standard, it works on UNIX and Windows. However, the GNU C library documentation contains the following warnings:
>
"Unlike PATH_MAX, this macro is defined even if there is no actual limit imposed. In such a case, its value is typically a very large number. This is always the case on the GNU system. 
>
Usage Note: Don't use FILENAME_MAX as the size of an array in which to store a file name! You can't possibly make an array that big! Use dynamic allocation."

**Comment by stephentoub** [comment]
cc: @JeremyKuhne

**Comment by poizan42** [comment]
Wouldn't the correct thing be to just get rid of MAX_PATH on unix platforms? Call the api and see whether it succeeds seems to be the only correct way - don't let the clr impose additional contraints.

**Comment by sergiy-k** [comment]
This should be addressed by https://github.com/dotnet/coreclr/pull/3441
