### ISSUE TITLE
ConditionalWeakTable becomes invalid after asynchronous exception

### ISSUE THREAD

**Issue by 47th** [dotnet/coreclr#8873]
Methods Add and Remove in ConditionalWeakTable set _invalid flag, which may remain set after asynchronous exception, like ThreadAbortException. In a web application, where ThreadAbortException is thrown on request timeout, any static ConditionalWeakTable object may accidentally become invalid.

```
var table = new ConditionalWeakTable<object, object>();
var t = new Thread(() =>
{
    while (true)
        try
        {
            table.Add(42, 42);
        }
        catch (ThreadAbortException)
        {
            Thread.ResetAbort();
            Console.WriteLine("Still alive!");
        }
});
t.Start();
Thread.Sleep(1000);
while (true)
{
    t.Abort();
    table.Remove(42); // checks integrity and throws InvalidOperationException
}
```

**Comment by jkotas** [comment]
.NET Core does not support thread abort. The .NET Core libraries are not hardened against thread abort.

**Comment by 47th** [comment]
Is there a possibility that it will be fixed to support .NET 4.6.2 users? ASP.NET framework currently uses Thread.Abort quite heavily and ConditionalWeakTable is not handling ThreadAbortException unlike other concurrent collections.

**Comment by danmosemsft** [comment]
@47th we don't track issues here specific to Desktop. There currently isn't a good place to do that (unless raised through support channels)

**Comment by danmosemsft** [comment]
I will close this feel free to reopen if you believe we need to discuss more or I misunderstood.
