### ISSUE TITLE
Can reflection consume generic and return ref for field?

### ISSUE THREAD

**Issue by Thaina** [dotnet/coreclr#8877]
Since roslyn has a plan for return ref. Is it would possible to return ref from reflection?

Something like
```C#
FieldInfo fi = typeof(obj).GetField("Transform");
ref Matrix4x4 t = fi.GetValueRef<Matrix4x4>(ref obj);
t.M41 = 0;
t.M42 = 0;
t.M43 = 1;
// obj.Transform.M41-43 became 0 0 1
```

ps. This is moved from dotnet/roslyn#16383

**Comment by jkotas** [comment]
It would require reflection APIs that are able to take and return references instead of objects. This proposal is discussed in https://github.com/dotnet/corefx/issues/14021

**Comment by gkhanna79** [comment]
Should this be closed in favor of the proposal issue?

**Comment by jkotas** [comment]
Make sense
