### ISSUE TITLE
Remove unnecessary defines from CoreCLR CoreLib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#8883]
The following are always defined when building the CoreCLR Corelib. Since we are not maintaining multiple builds, we should not need the defines in the code (they are always true).

- [x] FEATURE_APPDOMAIN_RESOURCEMONITORING
- [x] FEATURE_COLLECTIBLE_TYPES
- [x] FEATURE_CORECLR
- [x] FEATURE_CORESYSTEM
- [x] FEATURE_CORRUPTING_EXCEPTIONS
- [x] FEATURE_EXCEPTIONDISPATCHINFO
- [x] FEATURE_EXCEPTION_NOTIFICATIONS
- [x] FEATURE_HOST_ASSEMBLY_RESOLVER
- [x] FEATURE_LOADER_OPTIMIZATION
- [x] FEATURE_MAIN_CLR_MODULE_USES_CORE_NAME
- [x] FEATURE_MANAGED_ETW_CHANNELS
- [x] FEATURE_MULTICOREJIT
- [x] FEATURE_SPAN_OF_T
- [x] FEATURE_STRONGNAME_MIGRATION
- [x] FEATURE_SYNCHRONIZATIONCONTEXT_WAIT
- [x] FEATURE_VERSIONING
- [x] FEATURE_WINDOWSPHONE

Partially keep - break out into another issue:
- [ ] FEATURE_RANDOMIZED_STRING_HASHING

@jkotas why do we define the COMINTEROP symbols, when we don't support COM interop? 

Also, are there any that are valuable to retain for potential future use, eg., private builds or other work?

Their entries can also be removed from 

- [x] https://github.com/dotnet/coreclr/blob/master/clr.coreclr.props

As a subseqnet workitem, they could be then removed from the native side also, both code and their several cmake files.

**Comment by danmosemsft** [comment]
I need to double check this list on a Unix build.

**Comment by danmosemsft** [comment]
These ones are also present in CoreRT so presumably could be cut from there

```
FEATURE_CORECLR
FEATURE_RANDOMIZED_STRING_HASHING
```

**Comment by jkotas** [comment]
> when we don't support COM interop

We do support a good chunk of COM interop on Windows (except COM interop activation and IDispatch).

**Comment by jkotas** [comment]
> Also, are there any that are valuable to retain for potential future use, eg., private builds or other work?

I do not think so. 

`FEATURE_RANDOMIZED_STRING_HASHING`  can use some scrutiny - some of it should be kept and some of it deleted.

> I need to double check this list on a Unix build.

Yes, also different platforms defined these differently. E.g.:

- `FEATURE_USE_LCID` is defined on Windows and not defined on Unix today. Though, it will go away if you switch the CoreCLR globalization implementation to CoreRT version on both Windows and Unix.

- `FEATURE_ARRAYSTUB_AS_IL` is not defined on x86

**Comment by danmosemsft** [comment]
OK, updated the list above.
