### ISSUE TITLE
Audit use of #if FEATURE_SERIALIZATION

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#8884]
We never define this in CoreCLR. There's a bunch of code behind #if FEATURE_SERIALIZATION and I wonder whether some of it should be being compiled now we support binary serialization. (If not we will remove it - https://github.com/dotnet/coreclr/issues/8857)

For example stuff in https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Exception.cs#L496 and a lot in https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Resources/ResourceReader.cs.

**Comment by jkotas** [comment]
Yes, this should be removed. The two examples you have mentioned has been done intentionally the way they were done.

**Comment by danmosemsft** [comment]
OK, then this is redundant as we have #8857

**Comment by danmosemsft** [comment]
@stephentoub since he did most of the binary serialization work.

**Comment by danmosemsft** [comment]
I've gone through the others and I think I've stisfied myself that indeed they're dead code. All the CAS stuff we don't care about serializing in any intersting way. As for FormatterServices.cs that is masked in Corefx.
