### ISSUE TITLE
Remove SetType usage in EnumEqualityComparer's serialization implementation

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#8893]
See https://github.com/dotnet/coreclr/pull/8892#discussion_r95586366 discussion for details.  We need to remove this usage of SetType, add the other deserialization ctors to the model.xml, etc.

**Comment by AlexGhiondea** [comment]
@ianhays could you take a look?

**Comment by stephentoub** [comment]
I can actually take care of it... already on my todo list.
