### ISSUE TITLE
[arm64] Unable to Crossgen System.Private.CoreLib

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#8898]
First failing occurance was [09c95bfa26420b7f29d04b5d47a06cf52f430ffe](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_debug_windows_nt/360/).

**Comment by gkhanna79** [comment]
Assert failure(PID 11804 [0x00002e1c], Thread: 6556 [0x199c]): Assertion failed '(node->gtLsraInfo.dstCount == 0) || node->IsValue()' in 'System.Activator:CreateInstance(ref,ref):ref' (IL size 28)
 
    File: d:\a\_work\100\s\src\jit\lower.cpp Line: 4327
    Image: D:\A\_work\100\s\bin\Product\Windows_NT.arm64.Debug\x64\crossgen.exe
