### ISSUE TITLE
Add the RyuJIT coding conventions document

### ISSUE THREAD

**Issue by cmckinsey** [dotnet/coreclr#890]
Convert to markdown and add to documentation. Link from the wiki would be nice too. @BruceForstall

**Comment by jasonwilliams200OK** [comment]
On a related note, would be nice to rename `Documentation` directory name to `docs`, in conformity to `src` and `tests`.

**Comment by jkotas** [comment]
The directory name is intentionally named Documentation with capital D so that it always comes first in the default sort order. The same name is used by https://github.com/torvalds/linux and other projects that we have looked at.

**Comment by jasonwilliams200OK** [comment]
Makes perfect sense. Thanks! :+1:

**Comment by BruceForstall** [comment]
Fixed with #1004, #1090
