### ISSUE TITLE
System.Private.CoreLib.csproj gives error during opening project and project loading fail.

### ISSUE THREAD

**Issue by tapanrami** [dotnet/coreclr#8919]
I clone the repo and then i try to open System.Private.CoreLib.csproj but i am getting error " The imported project "<local_path>\coreclr-master\coreclr-master\Tools\net45\roslyn\build\Microsoft.Net.Compilers.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. "

**Comment by danmosemsft** [comment]
Have you run "build" at least once from the root?

**Comment by tapanrami** [comment]
Thank you for your kind support. It is now working.
