### ISSUE TITLE
Compiler does not referring to another file

### ISSUE THREAD

**Issue by cstyle** [dotnet/coreclr#8920]
When I create new two classes in different name space and it to two file then it cause compile error.
However When I merge source code both classes to one file and keep different name space then there is not compile error.
Is this compiler bug ?

<img width="1626" alt="different file" src="https://cloud.githubusercontent.com/assets/2171088/21896749/63636126-d922-11e6-843a-d4135b6f2ef3.png">
<img width="1601" alt="same file" src="https://cloud.githubusercontent.com/assets/2171088/21896750/64865f04-d922-11e6-83c2-f6f36cd6591e.png">

DotNet Info
.NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by danmosemsft** [comment]
Check the compiler command line, are both files getting passed to it?

**Comment by mikedn** [comment]
I'm not familiar with MongDB but it seems that there's no Find method in the IMongoCollection interface. That would mean that the Find method you are using is an extension method and as such its availability depends on the existing using directives. Try copying the usings from the file where it works to the file where it doesn't work.

**Comment by cstyle** [comment]
Finally, I could fix it. But I do not know what was problem.
What I did is that I just removed Repositories directly which includes the error file. Then Create it and AcommodationRepository.cs again. Then When I did 'dotnet build' Then nothing error which means build is succeed.

Thank you for all helps.
