### ISSUE TITLE
JIT should eliminate empty try with non empty finally

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#8924]
See https://github.com/dotnet/coreclr/issues/1505#issuecomment-272045324

In CoreFX there are 20+ instances of code like this
```
            try { }
            finally
            {
                // Finally block to protect against corruption due to a thread abort 
                // between setting _next and setting _tail.
                Volatile.Write(ref _tail._next, newSegment); // ensure segment not published until item is fully stored
                _tail = newSegment;
            }
```
In some cases these are [heavily nested](https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionPool.cs#L453) for some reason.

This is a hangover from support for thread abort, which CoreCLR does not support. The CoreCLR JIT therefore should elide the try and finally. (If the JIT is used on runtimes that do support thread abort, I guess it shouldn't do it there, worth checking with @jkotas )

@AndyAyersMS

**Comment by VSadov** [comment]
FWIW. C# compiler can elide some EH regions. 

- empty finally can be dropped
- try with no catches and empty finally can be unwrapped
- if try is empty, catches are pointless and can be removed

We do keep nonempty finallies, because on some runtimes entering/exiting finally is observable due to CER/Thread.Abort

**Comment by danmosemsft** [comment]
@VSadov right, which is why I assumed this has to happen at codegen level, where presumably it knows what runtime it's on - unlike the compiler.

**Comment by danmosemsft** [comment]
> C# compiler can elide some EH regions.

I assume you mean "does" or does this need a Roslyn issue to suggest it?

**Comment by jkotas** [comment]
> The CoreCLR JIT therefore should elide the try and finally

Correct, the try/finally can be elided for non-desktop ABIs.

**Comment by VSadov** [comment]
@danmosemsft  - yes, it _does_ elide when compiling with /o+ 

The definition of "empty" is a bit weak though. 
I.E. if you have a bunch of non-sideeffecting garbage, it may not be smart enough to fgure that out.

```cs
try
{
}
fianlly
{
    // i think this will not be currently optimized until IL emit, so "finally" may stay, albeit empty.
    var dummy = 2+2;
}
```

**Comment by danmosemsft** [comment]
@VSadov maybe you could open a Roslyn issue for that? I think you have more context.

**Comment by AndyAyersMS** [comment]
Have a version of empty try removal working pretty well. Will send a PR out in a bit. There are about 130 impacted methods in the usual set of assemblies we examine (coreclr + some part of corefx).

**Comment by jkotas** [comment]
cc @kouvel Could you please get the Interrupt handling corner case you talked to me about yesterday  removed as part of this change so that this optimization does not affect behavior?

**Comment by AndyAyersMS** [comment]
@jkotas Note #8551 has already stripped protection in CoreCLR for most finallys.

**Comment by danmosemsft** [comment]
thanks @AndyAyersMS !
