### ISSUE TITLE
React to CoreFX layout changes

### ISSUE THREAD

**Issue by ellismg** [dotnet/coreclr#8937]
dotnet/corefx#15135 is introducing changes in how both their build is driven, the layout on disk of their artifacts, and how tests are run.

In CI we have jobs that depend on all of the above which would be broken by this change.  We are fixing the version we depend on in CI to before this change, but we need to go back and then update CI to use the new layouts so we can continue to pick up new versions of CoreFX.

**Comment by gkhanna79** [comment]
@ellismg @wtgodbe merged https://github.com/dotnet/coreclr/pull/9119 and https://github.com/dotnet/coreclr/pull/9113 to use the new CoreFX binary layout for running CoreCLR tests. Is there anything else required to address this issue?

**Comment by wtgodbe** [comment]
@ellismg I believe this has been addressed, the CI has been looking good since the changes Gaurav mentioned above - anything else that needs to be done? Otherwise I'm going to close this at EOD

**Comment by ellismg** [comment]
Nothing else I can think of.  I see @RussKeldorph fixed up the python scripts as well.  Closing.

**Comment by jkotas** [comment]
@wtgodbe @ellismg The CoreFX version is not getting updated in CoreCLR anymore - the CoreCLR tests on my local box are running against January 13 CoreFX. When are we going to get live CoreFX from CoreCLR again? (I need to get more recent CoreFX to fix https://github.com/dotnet/coreclr/pull/9278.)

**Comment by gkhanna79** [comment]
I chatted with @wtgodbe yesterday and he is looking into addressing this.

**Comment by gkhanna79** [comment]
@wtgodbe What is the next step on this?

**Comment by wtgodbe** [comment]
I'm still working on that change, I wasn't able to make much progress yesterday as I spent most of the day working on other things - I'm probably still a few days out from putting a PR up.

**Comment by gkhanna79** [comment]
@wtgodbe Any update on this?

**Comment by wtgodbe** [comment]
I'm going to be focusing on this this week, per our discussion last Tuesday

**Comment by ramarag** [comment]
@wtgodbe i beleive we talked about a solution for this a long time ago to actually not to build corefx for xplat.

I believe the fix is just getting the following in to replace for the build, so that we always get what we want from nuget and do not need to build corefx in CI

```
restore_TestAssets()
{

    if [ $__isMSBuildOnNETCoreSupported == 0 ]; then
        echo "System.Private.CoreLib.dll build unsupported."
        return
    fi

    if [ $__Skiprestoretestassets == 1 ]; then
       echo "Skipping building System.Private.CoreLib."
       return
    fi

    echo "Commencing restore of test components for $__BuildOS.$__BuildArch.$__BuildType"

   __BuildLogRootName=Tests_Overlay
   __msbuildLog="/flp:Verbosity=normal;LogFile=$__LogsDir/$__BuildLogRootName.$__BuildOS.$__BuildArch.$__BuildType.log"
   __msbuildWrn="/flp1:WarningsOnly;LogFile=$__LogsDir/$__BuildLogRootName.$__BuildOS.$__BuildArch.$__BuildType.wrn"
   __msbuildErr="/flp2:ErrorsOnly;LogFile=$__LogsDir/$__BuildLogRootName.$__BuildOS.$__BuildArch.$__BuildType.err"

   "$__ProjectRoot/run.sh" build -Project=$__ProjectDir/tests/runtest.proj -testOverlay -MsBuildLog=$__msbuildLog -MsBuildWrn=$__ms


    popd
}
```
and call it in build.sh
as 
```
restore_TestAssets
```

**Comment by wtgodbe** [comment]
@ramarag that's actually a separate issue to this one, the issue here's is that we're still relying on old CoreFX packages (System.xxx), which haven't been updated since Jan 13 - we should move to relying on Microsoft.Private.CoreFx.NETCoreApp instead. What's making that difficult is that our xunit dependencies have conflicts with that package.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/10074 is the PR for updating to new CoreFX packages

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/10074 is in, so this should be resolved.
