### ISSUE TITLE
Question about pGenGCHeap

### ISSUE THREAD

**Issue by 303248153** [dotnet/coreclr#8959]
Hello, I'm reading source code of GC, and I have a question about pGenGCHeap in GCHeap class
read below part

code taken from gcimpl.h
```
#ifdef MULTIPLE_HEAPS
    gc_heap*    pGenGCHeap;
#else
    #define pGenGCHeap ((gc_heap*)0)
#endif //MULTIPLE_HEAPS
```

code taken from gc.cpp
```
#ifdef MULTIPLE_HEAPS
    for (int i = 0; i < gc_heap::n_heaps; i++)
    {
        gc_heap* h = gc_heap::g_heaps [i];
        hs = h->find_segment_per_heap (o, small_segment_only_p);
        if (hs)
        {
            break;
        }        
    }
#else
    {
        gc_heap* h = pGenGCHeap;
        hs = h->find_segment_per_heap (o, small_segment_only_p);
    }
#endif //MULTIPLE_HEAPS
#endif //SEG_MAPPING_TABLE
```

so if `MULTIPLE_HEAPS` is not defined, pGenGCHeap will always be NULL, why the second part still use pGenGCHeap? Shouldn't that cause null pointer error?

**Comment by mikedn** [comment]
>  Shouldn't that cause null pointer error?

Not necessarily. It depends on what `find_segment_per_heap` is doing, if it doesn't access any data members or virtual member functions then it works fine. Calling a member function on a null object pointer is basically undefined behavior but it works on all current compilers.

**Comment by 303248153** [comment]
Thanks, I found members of gc_heap is prefixed by PER_HEAP which is `static` if `MULTIPLE_HEAPS` not defined.
It looks wired but yeah it work :|
