### ISSUE TITLE
FreeBSD 11.0 x86 build issue

### ISSUE THREAD

**Issue by valeri2** [dotnet/coreclr#8983]
Hello.
I'm trying to build CORECLR for x86 platforms on FreeBSD 11.0 x64.

`./build.sh clang3.7 x86 skiptests`.

But at the end I get **ELF 64-bit LSB executable:**

`~/coreclr/bin/Product/FreeBSD.x86.Debug# file ./corerun`
`./corerun: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), 
dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 11.0 
(1100122), FreeBSD-style, not stripped`

**Comment by janvorli** [comment]
Since you are cross building (building for x86 on x86-64), you need to add `cross` to the build.sh command line.

**Comment by valeri2** [comment]
` ./build.sh clang3.7 x86 skiptests cross`

Right?

Then I get:

/usr/local/bin/clang37 -Wall -std=c11 -m32
  --sysroot=/root/coreclr/cross/rootfs/x86
  -Wno-error=unused-command-line-argument -o
  CMakeFiles/cmTC_664a3.dir/testCCompiler.c.o -c
  /root/coreclr/bin/obj/FreeBSD.x86.Debug/CMakeFiles/CMakeTmp/testCCompiler.c


  Linking C executable cmTC_664a3

  /usr/local/bin/cmake -E cmake_link_script
  CMakeFiles/cmTC_664a3.dir/link.txt --verbose=1

  /usr/local/bin/clang37 -Wall -std=c11
  --sysroot=/root/coreclr/cross/rootfs/x86 -B
  /root/coreclr/cross/rootfs/x86/usr/lib/gcc/i686-linux-gnu
  -L/root/coreclr/cross/rootfs/x86/lib/i386-linux-gnu -m32
  CMakeFiles/cmTC_664a3.dir/testCCompiler.c.o -o cmTC_664a3 -rdynamic

  /usr/bin/ld: crt1.o: No such file: No such file or directory

  clang-3.7: error: linker command failed with exit code 1 (use -v to see
  invocation)

  *** Error code 1

**Comment by janvorli** [comment]
I have forgotten to mention that you need to generate the crossfs first using the cross/build-rootfs.sh. But we support only Ubuntu in that script now.
So to build for x86 FreeBSD, you would either need to build it on native x86 FreeBSD installation or add support for building crossfs for FreeBSD.

**Comment by janvorli** [comment]
Btw, the x86 support for Unix is currently being worked on, it is not complete yet. While executing simple Hello World already works, exception handling is not working yet.
