### ISSUE TITLE
Crossgen failure should terminate the build

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#8988]
This does not happen today as evidenced in https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=526522 where build.cmd passes even when crossgen failed:

```
2017-01-18T16:28:40.9144814Z Command execution succeeded.
2017-01-18T16:28:40.9144814Z BUILD: Generating native image of System.Private.CoreLib for Windows_NT.arm64.Checked
2017-01-18T16:28:40.9144814Z "E:\A\_work\22\s\bin\Product\Windows_NT.arm64.Checked\x64\crossgen.exe" /Platform_Assemblies_Paths "E:\A\_work\22\s\bin\Product\Windows_NT.arm64.Checked" /out "E:\A\_work\22\s\bin\Product\Windows_NT.arm64.Checked\System.Private.CoreLib.ni.dll" "E:\A\_work\22\s\bin\Product\Windows_NT.arm64.Checked\System.Private.CoreLib.dll"
2017-01-18T16:28:48.0710293Z BUILD: Error: CrossGen System.Private.CoreLib build failed. Refer to E:\A\_work\22\s\bin\Logs\CrossgenCoreLib_Windows_NT__arm64__Checked.log
2017-01-18T16:28:48.0710293Z     E:\A\_work\22\s\bin\Logs\CrossgenCoreLib_Windows_NT__arm64__Checked.log
2017-01-18T16:28:48.0710293Z ##[section]Finishing: Run build.cmd
```

**Comment by sdmaclea** [comment]
On Unix there are several failures because many of the files are not managed assemblies.  I do not know if Windows has the same issue.There are also several failures on Arm64 because of real crossgen issues

The most urgent failure detection would be CrossGen System.Private.CoreLib.  Perhaps that could be implemented first.

**Comment by gkhanna79** [comment]
@wtgodbe Can you please get this fixed soon? We have seen this in official builds as well.

**Comment by wtgodbe** [comment]
Sure, will work on this today.

**Comment by wtgodbe** [comment]
Haven't been able to figure out why the return code isn't being picked up by VSO, but I have noticed that the above failure is somewhat persistent in Windows arm builds, and only every repros when BuildType is "Checked" - haven't been able to repro it locally yet, though.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/9703 should address

**Comment by sdmaclea** [comment]
I assume #9703 does not fix Unix builds.

For Unix, if I create a list of current known crossgen failures, I can make runtest.sh fail if crossgen fails unless the known failures are in the list....  Would that patch be useful?  Or do windows/unix crossgen failures correlate well enough that the added coverage is not required?

**Comment by wtgodbe** [comment]
@sdmaclea have you seen build.sh succeed on Linux despite a Crossgen failure? I was under the impression that this specific issue (build succeeding even though crossgen failed) was Windows-specific, while the actual failures were a separate issue.

**Comment by sdmaclea** [comment]
@wtgodbe The errors do not occur in build, but they occur during overlay crossgen creation.  The crossgen errors in test/runtests.sh are ignored. See https://github.com/dotnet/coreclr/blob/master/tests/runtest.sh#L409 .

**Comment by wtgodbe** [comment]
Oh, well that's no good - we should exit with error there. I can put up a PR, unless you see it differently.

**Comment by sdmaclea** [comment]
I think it should exit with an error, but I think there are assemblies which are currently failing. So if this is exercised in CI, then there might need to temporarily be a (per target?) waived list until these are fixed.

**Comment by sdmaclea** [comment]
If it is relevant these managed assemblies are currently failing crossgen on Arm64/Unix

```
Microsoft.CodeAnalysis.VisualBasic.dll
System.Net.NameResolution.dll
System.Net.Primitives.dll
System.Net.Sockets.dll
System.Runtime.WindowsRuntime.UI.Xaml.dll
```

**Comment by wtgodbe** [comment]
I see. If that's the case, could you put together a PR like you mentioned above 

> (I can make runtest.sh fail if crossgen fails unless the known failures are in the list)

?
