### ISSUE TITLE
AppDomain::m_ForceTrivialWaitOperations is not initialized

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#8990]
This sometimes causes waits in STA threads to call `WaitForMultipleObjectsEx` instead of `CoWaitForMultipleHandles`

**Comment by janvorli** [comment]
@kouvel I can see it initialized in the AppDomain constructor to false. Am I missing something?

**Comment by kouvel** [comment]
Ack, don't know how I missed that, thanks :)
