### ISSUE TITLE
ETA for porting mdbg to coreclr

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/coreclr#8999]
realted issue : https://github.com/dotnet/coreclr/issues/1145
Is there any information(ETA or repo) for porting mdbg to dotnet core(coreclr) ?

**Comment by gkhanna79** [comment]
CC @noahfalk @lt72

**Comment by lt72** [comment]
@chunseoklee: we have not committed yet to port MDBG to dotnet core. Decision and execution will be postponed to 2.1.

**Comment by chunseoklee** [comment]
@lt72 Thank you for answer.

**Comment by aaronba** [comment]
Any update on ETA for MDbg being ported to .NET Core 2.x

**Comment by lt72** [comment]
Not yet, still debating what SDK support to implement for diagnostics for .Net Core, but no decision in sight or timeline I can offer for discussion.
