### ISSUE TITLE
Does CLR suspend EE only if MULTIPLE_HEAPS was defined?

### ISSUE THREAD

**Issue by AlekseevAlexander** [dotnet/coreclr#9003]
According to [CLR Threading Overview](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/threading.md) and [Garbage Collection Design](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/garbage-collection.md) the code flow for GC is:
```c
 GarbageCollectGeneration()
 {
     SuspendEE();
     garbage_collect();
     RestartEE();
 }
```

But according to [gc.cpp](https://raw.githubusercontent.com/dotnet/coreclr/master/src/gc/gc.cpp) source code it is correct only if MULTIPLE_HEAPS was defined:
```c
size_t
GCHeap::GarbageCollectGeneration (unsigned int gen, gc_reason reason)
{
    ...
#ifndef MULTIPLE_HEAPS
    ...
    GCToEEInterface::SuspendEE(SUSPEND_FOR_GC);
    ...
#endif //!MULTIPLE_HEAPS
    ...
#ifdef MULTIPLE_HEAPS
    ...
    cooperative_mode = gc_heap::enable_preemptive (current_thread);

    gc_heap::ee_suspend_event.Set();
    gc_heap::wait_for_gc_done();

    gc_heap::disable_preemptive (current_thread, cooperative_mode);
    ...
#else
    ...
    // !!! Here is no 'suspend' operation if MULTIPLE_HEAPS was not defined
    pGenGCHeap->garbage_collect (condemned_generation_number);
    // !!! Here is no 'restart' operation if MULTIPLE_HEAPS was not defined
    ...
#endif //MULTIPLE_HEAPS
    ...
#ifndef MULTIPLE_HEAPS
    ...
    GCToEEInterface::RestartEE(TRUE);
    ...
#endif //!MULTIPLE_HEAPS
    ...
}
```
Is it correct behavoiur or I missed something?
If it is correct then why does CLR suspend EE only if multiple heaps were used?

**Comment by jkotas** [comment]
> If it is correct then why does CLR suspend EE only if multiple heaps were used?

This is not correct. `GCToEEInterface::SuspendEE` is called in multiple places. The path you are looking at calls it for `!MULTIPLE_HEAPS`, other paths call it for `MULTIPLE_HEAPS`.
