### ISSUE TITLE
Allow custom runner for CoreCLR test unix scripts

### ISSUE THREAD

**Issue by nattress** [dotnet/coreclr#9007]
Each CoreCLR test has a Windows `test.cmd` and Unix `test.sh` script that runs the test. The Windows scripts allow a custom test runner so that CoreRun can be switched out (ie, with CoreRT). The Unix scripts need the same feature.

On Windows:
```
IF NOT "%CLRCustomTestLauncher%"=="" (
  set LAUNCHER=call %CLRCustomTestLauncher% %~dp0
) ELSE (
  set LAUNCHER=%_DebuggerFullPath% "%CORE_ROOT%\corerun.exe"
)
      
ECHO %LAUNCHER% class01.exe %CLRTestExecutionArguments%
```

What Unix currently has:
```
$_DebuggerFullPath "$CORE_ROOT/corerun" class01.exe $CLRTestExecutionArguments 
```

**Comment by gkhanna79** [comment]
CC @ramarag

**Comment by ramarag** [comment]
The line that needs to be changed is https://github.com/dotnet/coreclr/blob/37139ef1a7631e618ee587287b48d49dad04be94/tests/src/CLRTest.Execute.Bash.targets#L187

For reference to what is done for windows look at : 
https://github.com/dotnet/coreclr/blob/37139ef1a7631e618ee587287b48d49dad04be94/tests/src/CLRTest.Execute.Batch.targets#L209-L229
