### ISSUE TITLE
"build.cmd clean" removes entire RootBinDir

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#901]
### Issue
Running `build.cmd clean` will remove the entire RootBinDir.

### Proposal
Running `build.cmd clean` should only remove the binary folders for the select configuration. 

Meaning `build.cmd clean` should remove the `x64 debug` configuration and leave the `x64 release` folder, `linuxmscorlib`, and `osxmscorlib` binary output folders alone.

**Comment by tannergooding** [comment]
A fix is available via PR #903.

**Comment by MattWhilden** [comment]
Merged!
