### ISSUE TITLE
Could not load file or assembly 'mscorlib on Linux using Jailkit

### ISSUE THREAD

**Issue by ole1986** [dotnet/coreclr#9014]
When trying to execute `dotnet --version` I get the below error.
Also `dotnet new` does not work (with same error).

I already copied several libraries, like:

/lib/x86_64-linux-gnu/librt.so.*
/usr/lib/x86_64-linux-gnu/libunwind.so.*
/usr/lib/x86_64-linux-gnu/libicu*.so.*

Is there anything else missing? Language files?

**Attached: complete STDOUT**
[error.txt](https://github.com/dotnet/coreclr/files/717981/error.txt)

```
The resolved JIT path is '/opt/dotnet/shared/Microsoft.NETCore.App/1.1.0/libclrjit.so'
CoreCLR path = '/opt/dotnet/shared/Microsoft.NETCore.App/1.1.0/libcoreclr.so', CoreCLR dir = '/opt/dotnet/shared/Microsoft.NETCore.App/1.1.0'
Property TRUSTED_PLATFORM_ASSEMBLIES = /opt/dotnet/sdk/1.0.0-preview2-1-003177/dotnet.dll:/opt/dotnet/sdk/1.0.0-preview2-1-003177/Microsoft.ApplicationInsights.dll:/opt/dotnet/sdk/1.0.0-preview2-1-003177/Mi$
Property NATIVE_DLL_SEARCH_DIRECTORIES = /opt/dotnet/shared/Microsoft.NETCore.App/1.1.0:
Property PLATFORM_RESOURCE_ROOTS =
Property AppDomainCompatSwitch = UseLatestBehaviorWhenTFMNotSpecified
Property APP_CONTEXT_BASE_DIRECTORY = /opt/dotnet/sdk/1.0.0-preview2-1-003177
Property APP_CONTEXT_DEPS_FILES = /opt/dotnet/sdk/1.0.0-preview2-1-003177/dotnet.deps.json;/opt/dotnet/shared/Microsoft.NETCore.App/1.1.0/Microsoft.NETCore.App.deps.json
Property FX_DEPS_FILE = /opt/dotnet/shared/Microsoft.NETCore.App/1.1.0/Microsoft.NETCore.App.deps.json
Property JIT_PATH = /opt/dotnet/shared/Microsoft.NETCore.App/1.1.0/libclrjit.so
Launch host: /opt/dotnet/dotnet, app: /opt/dotnet/sdk/1.0.0-preview2-1-003177/dotnet.dll, argc: 1, args: --version,
Directory core breadcrumbs [] was not specified or found
Fallback directory core breadcrumbs at [/opt/corebreadcrumbs] was not found
--- Begin breadcrumb write
Breadcrumb store was not obtained... skipping write.

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)
Aborted
```

**When using `dotnet` without arguments it shows me  the version and Build properly:**

```
Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```

**Comment by gkhanna79** [comment]
@ole1986 How did you install the SDK? Are you able to repro this with https://www.microsoft.com/net/download/core#/current?

**Comment by ole1986** [comment]
I tried first using "mount --bind" to put the opt folder into the jk_chroot directory from the real root opt path.

Then I fully copied it into the jailbait folder.
Both were actually acting same.

**Comment by ramarag** [comment]
@ole1986  i have a suspicion that this is a PAL issue, is it possible for you to Provide a repro environment/ full steps

**Comment by ole1986** [comment]
I can give it another try.
Do you recommend copying the /opt/dotnet or would a "mount --bind" be an option?!

**Comment by ole1986** [comment]
@ramarag 

I am using my custom jailkit config containing the required libraries (executable = /opt/dotnet/dotnet can be ignored) which includes the extendedshell section

```
[dotnet]
comment = DOTNET Core
executables = /opt/dotnet/dotnet
libraries = /lib/x86_64-linux-gnu/librt.so.*, /usr/lib/x86_64-linux-gnu/libunwind.so.*, /usr/lib/x86_64-linux-gnu/libicu*.so.*, /usr/lib/i386-linux-gnu/libssl.so*, /usr/lib/x86_64-linux-gnu/libcurl.so.*, /lib/x86_64-linux-gnu/libuuid.so.*, /usr/lib/x86_64-linux-gnu/libunwind-x86_64.so.*
includesections = extendedshell
```

Then I am running the command (assuming a user already exist)
`jk_init -j /home/dotnet1 dotnet`

followed by a custom script doing the following:

```
JPATH = /home/dotnet1
echo "Enable DOTNET 1.1.0 for $JPATH"
# remove immunity flag
chattr -i $JPATH
# create an opt folder if not exists
mkdir -p $JPATH/opt
# create a proc folder if not exists 
# otherwise an error: "Failed to resolve full path of the current executable [/proc/self/exe]" will occur
mkdir -p $JPATH/proc
# create a /tmp folder
# otherwise an error: "Failed to initialize CoreCLR, HRESULT: 0x80004005" will occur
mkdir -p $JPATH/tmp

# set the immunity flag back
chattr +i $JPATH
# use mount to bind the opt folder
mount --bind /opt $JPATH/opt
# use mount to bind the proc folder
mount --bind /proc $JPATH/proc
# make a symlink to access "dotnet" easier
jk_chrootlaunch -j $JPATH -x /bin/ln -- -s /opt/dotnet/dotnet /bin/dotnet
```

followed by (from outside the jail)
`jk_chrootlaunch -j /home/dotnet1 -x /bin/bash`

to open the jailed bash and finally run the command (from inside the jail)
`dotnet --version`

which result into:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)
Aborted
```

SIDE NOTE:
The command `find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found' from inside the jail returns the following:

xargs: `/dev/null': No such file or directory
        liblldb-3.6.so => not found
        liblttng-ust.so.0 => not found
        liblldb-3.6.so => not found
        liblttng-ust.so.0 => not found
`
which is same when doing it from outside the jail

**Comment by ole1986** [comment]
Attached file is the output of strace64 when running `strace64 /opt/dotnet/dotnet -v`

[dotnet-strace.txt](https://github.com/dotnet/coreclr/files/885218/dotnet-strace.txt)

**Comment by ole1986** [comment]
Oh, finally I fixed this issue:

While using jailkit I copied all the required files and also `mount --bind /proc <destination>`
But dotnet needs to have `mount --bind /dev <destination>` as well.

I think this issue can now be closed

**Comment by ramarag** [comment]
thanks @ole1986 for figuring this out
