### ISSUE TITLE
webHost.Dispose() does not complete

### ISSUE THREAD

**Issue by izaaz** [dotnet/coreclr#9018]
Hi,

We have a dot net core WebListener service deployed in Service Fabric. When we upgrade the service version, SF tries to stop the application by calling CloseAsync before it upgrades it to the new version. This is our implementation for that.

            Task ICommunicationListener.CloseAsync(CancellationToken cancellationToken)
            {
                etwEventSource.ServiceMessage(serviceContext, "StartClose");
                try
                {
                    webHost?.Dispose();
                }
                catch (Exception ex)
                {
                    etwEventSource.ServiceMessage(serviceContext, "CloseService-Exception", ex);
                    // no op
                }
                etwEventSource.ServiceMessage(serviceContext, "StopClose");

                return Task.FromResult(true);
            }

What we see is, when the service is receiving traffic and when service fabric calls CloseAsync, the dispose function call does not complete (no exception gets thrown) and hence service fabric waits for 15 minutes before killing the application. Where as, when the service is not receiving any traffic, the dispose method completes fine and everything executes as expected. 

Any idea why dispose might not be returning when the service is receiving traffic?

Thanks,
Izaaz

    Project.json:
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNet.WebApi.Client": "5.2.3",
    "Microsoft.AspNet.WebApi.Core": "5.2.3",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Owin": "1.0.0",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.Server.WebListener": "1.1.0",
    "Microsoft.ServiceFabric": "5.3.301",
    "Microsoft.ServiceFabric.Data": "2.3.301",
    "Microsoft.ServiceFabric.Services": "2.3.301"

**Comment by benaadams** [comment]
Might want to open this issue here https://github.com/aspnet/Hosting

**Comment by izaaz** [comment]
Thanks @benaadams. Moved it there!
