### ISSUE TITLE
RyuJIT: Eliminate unnecessary struct copies that materialize after in-lining a method

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#9019]
This issue surfaced while analyzing knucleotide benchmark on Windows.

One of its hot methods `KFrequency() `calls into `Dictionary<Struct, ref>.TryGetValue(struct)` passing it a struct `key` as param.  `TryGetValue()` is a simple wrapper method that passes its struct param to `Dictionary.FindEntry(Struct, ref, bool)`.

`Call Chain: KFrequency() --> TryGetValue() --> FindEntry()`

Before in-lining `TryGetValue()`, in-liner  makes a copy of actual param 'key' and uses the copy within in-linee method body. 

```
v1 = copy of key
use v1 in the place of key while in-lining TryGetValue().
```

Now v1 in turn is getting passed to FindEntry() by value. Hence JIT will make another copy during argument morphing. The resulting IR would be

```
v1 = copy of  key
v2 = copy of v1
FindEntry(addr of v2)

```

In this particular case there are no more uses of v1, other than passing it as an arg to FindEntry().  Though method got in-lined, additional struct copies created in that process remain behind.  In this particular case copy v1 can be eliminated.

The above case occurs twice in Knucleotide hot method KFrequency() i.e. two unnecessary struct copies in a hot loop.  Eliminating such unnecessary copies would benefit real world code as well.

**Comment by sivarv** [comment]
Further investigation reveals that `key` (the source value) gets struct promoted but `v1` (destination) is not.  The reason for not struct-promoting `v1` is that its fields are not accessed.

`v1 = key`

Now we have a block-op whose src is promoted but its destination is not.  As a result, fgMorphCopyBlock() transforms it into field by field assignments by taking addr of V1

```
tmp = GT_ADDR(v1)
indir(tmp, offset) = key.field1
....

```

Further v1 is marked as addr-exposed so that liveness doesn't delete the definition of this LclVar as a dead store later on.

**Comment by sivarv** [comment]
The heuristic that determines it is not profitable to promote v1 is in fgPromoteStructs()

```
               // We *can* promote; *should* we promote?
                // We should only do so if promotion has potential savings.  One source of savings
                // is if a field of the struct is accessed, since this access will be turned into
                // an access of the corresponding promoted field variable.  Even if there are no
                // field accesses, but only block-level operations on the whole struct, if the struct
                // has only one or two fields, then doing those block operations field-wise is probably faster
                // than doing a whole-variable block operation (e.g., a hardware "copy loop" on x86).
                // So if no fields are accessed independently, and there are three or more fields,
                // then do not promote.
                if (structPromotionInfo.fieldCnt > 2 && !varDsc->lvFieldAccessed)
                {
                    JITDUMP("Not promoting promotable struct local V%02u: #fields = %d, fieldAccessed = %d.\n", lclNum,
                            structPromotionInfo.fieldCnt, varDsc->lvFieldAccessed);
                    shouldPromote = false;
                }
```

The struct in question has 3 fields and its fields are not accessed.

**Comment by CarolEidt** [comment]
As all of the structs in this method are now being promoted, it no longer suffers from the lack of struct copy elimination. That issue remains (e.g. #1133), but I'm closing this as #9455 addressed this specific case.
