### ISSUE TITLE
Span: VM side of GC reporting for `Span<T>` - slow tail calls

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#9032]
Fix the following places on the VM side to do proper GC reporting for `Span<T>`:
- `StubLinkerCPU::CreateTailCallCopyArgsThunk`, or slow tailcalls have to be disabled for calls with `Span<T>` arguments

Slow tail calls may not currently be an issue, but apparently, that could change.

Forked from #8517

**Comment by ahsonkhan** [comment]
@kouvel, any updates on this issue?

**Comment by kouvel** [comment]
Last I remember from talking with @jkotas about this is that this was something that is not currently an issue but could be in the future (at the time, the future was earlier in time), I don't remember the details. @jkotas, is there something here that has a potential for failure that needs to be investigated?

**Comment by jkotas** [comment]
Repro:

```
using System;
using System.Reflection;
using System.Reflection.Emit;

public class My {

public static void Target(Span<int> a, Span<int> b, Span<int> c, Span<int> d, Span<int> e)
{
   GC.Collect();
   for (int i = 0; i < 10000; i++) GC.KeepAlive(new Object());
   if (a[0] != 42 || b[0] != 42 || c[0] != 42 || d[0] != 42 || e[0] != 42)
       Internal.Console.WriteLine("FAILED");
}

delegate void MyDelegate(Span<int> x);

static void Main() {
    DynamicMethod dm = new DynamicMethod("TailCall", typeof(void), new Type[] { typeof(Span<int>) });
    ILGenerator il = dm.GetILGenerator();
    il.Emit(OpCodes.Ldarg_0);        
    il.Emit(OpCodes.Ldarg_0);
    il.Emit(OpCodes.Ldarg_0);
    il.Emit(OpCodes.Ldarg_0);
    il.Emit(OpCodes.Ldarg_0);
    il.Emit(OpCodes.Tailcall);
    il.Emit(OpCodes.Call, typeof(My).GetMethod("Target"));
    il.Emit(OpCodes.Ret);
    
    var d = (MyDelegate)dm.CreateDelegate(typeof(MyDelegate));
   
    for (;;) { GC.KeepAlive(new Object()); d(new Span<int>(new int[1] { 42 })); GC.KeepAlive(new Object()); }
}

}
```

Result on Windows x64: prints FAILED occasionally

**Comment by kouvel** [comment]
Thanks, I'll take a look
