### ISSUE TITLE
Please add new syntax keyword "ref?" to represent that  "ref return" result might be null

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#9037]
Now the C#7.0 feature "ref return" doesn't allow null as return value, but null as return value is sometimes useful. For example:
static ref? int findvalue(int[] arr, int value){
    int i;
    for(i=0;i<arr.Length;i++){
        if(value==arr[i])return ref arr[i];
    }
    return null; //not found
}

int[] array=new int[]{1,2,3};
ref? int e=findvalue(array, 4);
if(e!=null)e=5;
ref? int e1=finevalue(array,3);
if(e1!=null)e1=0;
..........

**Comment by jkotas** [comment]
You are asking for a new C# language feature - it belongs to https://github.com/dotnet/roslyn repo

**Comment by ygc369** [comment]
@jkotas 
I know this is a new C# feature, but it maybe need CLR support.

**Comment by jkotas** [comment]
It may or may not depending on the design. If it does, then it would be added to https://github.com/dotnet/roslyn/issues/420.

The null refs are possible in IL today so there is nothing fundamentally needed.

**Comment by danmosemsft** [comment]
I'm closing this as it's not a CLR issue. Good luck in the Roslyn repo.
