### ISSUE TITLE
[RyuJIT] Double CORINFO_HELP_ASSIGN_BYREF?

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#9039]
Outputting the jit dasm for Kestrel `FrameResponseHeaders:SetValueFast(ref,struct):this`

I'm seeing blocks like this:
```asm
G_M28429_IG07:
       48B94096F52B5C020000 mov      rcx, 0x25C2BF59640
       488B09               mov      rcx, gword ptr [rcx]
       488BD5               mov      rdx, rbp
       41B805000000         mov      r8d, 5
       E822ADF95A           call     String:Equals(ref,int):bool:this
       85C0                 test     eax, eax
       0F8427080000         je       G_M28429_IG40
       48814B2800000800     or       qword ptr [rbx+40], 0x80000
       488DBB80010000       lea      rdi, bword ptr [rbx+384]
       E89667AE5F           call     CORINFO_HELP_ASSIGN_BYREF
       E89167AE5F           call     CORINFO_HELP_ASSIGN_BYREF
       E942080000           jmp      G_M28429_IG41
```
I assume one `call CORINFO_HELP_ASSIGN_BYREF` is just as good as two in a row?

Is this a double call to `JIT_ByRefWriteBarrier`?

Block would be in C#
```csharp
if ("Keep-Alive".Equals(key, StringComparison.OrdinalIgnoreCase))
{
    _bits |= 8L;
    _headers._KeepAlive = value;
    return;
}
```

`_bits` is a heap `long`
`_headers` is a heap `struct`
`_KeepAlive` is a `struct` of `_headers`

All private class variables

Don't know if is double assign; or assigning to struct of struct?

**Comment by omariom** [comment]
What is it in C#?

**Comment by benaadams** [comment]
Added more details (including C#)

**Comment by mikedn** [comment]
> Is this a double call to JIT_ByRefWriteBarrier?

Yes, they copy the two reference fields from `StringValues`.

**Comment by benaadams** [comment]
Yeah is a two field struct
```csharp
public struct StringValues
{
    private readonly string _value;
    private readonly string[] _values;
}
```
So by design?

**Comment by mikedn** [comment]
By design in the sense that the generated code is correct. I suppose it might be improved to be a single call with an additional argument to indicate the numbers of fields to copy. Though that trades a call for a loop so it might actually be worse...

**Comment by benaadams** [comment]
Ah, yeah, copying two reference pointers...
