### ISSUE TITLE
Delegate's hash code is poor

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#9040]
Delegate's GetHashCode just returns the hash code of the delegate type.  For a scenario where delegates are used as keys in a dictionary, this leads to obvious performance problems.  We should look at coming up with a better GetHashCode that properly factors in the target object and method, in all of the various forms a delegate can take.

**Comment by mburbea** [comment]
When does it make sense to use delegates as keys to a dictionary? I guess it'd be best to just remove the `GetHashCode` impelementation and rely on the built-in object one. That's probably a breaking change.

**Comment by stephentoub** [comment]
> When does it make sense to use delegates as keys to a dictionary

This came from a reported performance problem from a developer. I don't have details on their exact scenario.

> guess it'd be best to just remove the GetHashCode impelementation and rely on the built-in object one.

That would mean that delegates to the same method could have different hash codes. As you say, it'd be a big breaking change.

**Comment by mburbea** [comment]
Well, it's still an improvement over delegates of the same type have the same key. (Unless your dictionary is literally keyed by `Delegate`. A key like `Func<int,int>` means every key hashes the same.)

I'd have to assume that delegates used for this purpose are cached, as creating new delegates isn't particularly cheap.

**Comment by jkotas** [comment]
A significant breaking change is never an improvement.

**Comment by mburbea** [comment]
@jkotas, I don't follow. Changing anything about it would be a "significant" breaking change. Equality would still work, and the usual case (cached delegates being used as keys) would see a performance improvement.

**Comment by stephentoub** [comment]
> I don't follow

Code like:
```C#
static Dictionary<Action, State> s_data = ...;
static void SomeMethod() { ... }
...
State s;
if (s_data.TryGetValue(SomeMethod, out s))
{
    ...
}
```
would stop working, due to the delegate instances created for SomeMethod not being the same object and thus very likely having different hash codes.

While such a code example may not have great performance, such code exists.  The fact that at least one real-world app was experiencing slow downs as a result of this issue highlights that people do rely on delegates being used as keys in dictionaries, for whatever reason.

**Comment by mburbea** [comment]
Thanks for the example, you're correct such code would fail if we changed to the default method. 

Building a proper hashcode for a delegate would be tricky as you'd have to consider the invocation lists as well.

**Comment by jkotas** [comment]
The current delegate hashcode algorithm does consider the invocation list: https://github.com/dotnet/coreclr/blob/b1f5c6acca00ca471818237d698baca317851b1f/src/mscorlib/src/System/MulticastDelegate.cs#L506 . I do not see a problem there.

**Comment by gkhanna79** [comment]
Is there anything outstanding on this issue based upon @jkotas reply above?

**Comment by jkotas** [comment]
Yes, the performance bug is still there. My comment was clarifying where the bug is and where it is not.

**Comment by mountgellert** [comment]
Hi, I'm the enduser who originally reported the issue.

In case you are having a MulticastDelegate, it was working properly, based on the code @jkotas showed. The problem only surfaces if it's a 'normal', non multicast delegate, than the current implementation only does:

        public override int GetHashCode()
        {
            //
            // this is not right in the face of a method being jitted in one delegate and not in another
            // in that case the delegate is the same and Equals will return true but GetHashCode returns a
            // different hashcode which is not true.
            /*
            if (_methodPtrAux.IsNull())
                return unchecked((int)((long)this._methodPtr));
            else
                return unchecked((int)((long)this._methodPtrAux));
            */
            return GetType().GetHashCode();
        }


instead of doing something along the lines of:


        public override int GetHashCode()
        {
            //
            // this is not right in the face of a method being jitted in one delegate and not in another
            // in that case the delegate is the same and Equals will return true but GetHashCode returns a
            // different hashcode which is not true.
            /*
            if (_methodPtrAux.IsNull())
                return unchecked((int)((long)this._methodPtr));
            else
                return unchecked((int)((long)this._methodPtrAux));
            */
            return ( _target != null ? _target.GetHashCode() : 0) * 33 + GetType.GetHashCode();
        }

**Comment by mountgellert** [comment]
Is there any progress on the item? Would it be fixed in an upcoming full .NET release too?

**Comment by mountgellert** [comment]
@danmosemsft hi, this causes repeatedly performance issues, is there a reason this was removed from 2.0.0 milestone?

**Comment by danmosemsft** [comment]
@mountgellert thanks for asking, just lack of time for 2.0, and it's not a regression. I'd certainly like it fixed though and master is still a 2.0 branch. Do you want to offer a PR?

**Comment by mountgellert** [comment]
I have the from-to above, but will do a PR too.

**Comment by mountgellert** [comment]
#11019 PR added
