### ISSUE TITLE
Assembly.ReflectionOnlyLoad should throw PNSE

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#9047]
Reflection-only loads are not supported in CoreCLR. (`FEATURE_REFLECTION_ONLY_LOAD`)

`Assembly.ReflectionOnlyLoad` are doing full loads instead of reflection-only loads. They should throw PNSE instead.

The matching corefx tests should be updated: https://github.com/dotnet/corefx/blob/f9efc9625f795673c5c17d0791d8c79710a267b9/src/System.Runtime/tests/System/Reflection/AssemblyTests.cs#L161

**Comment by jkotas** [comment]
Note that other ReflectionOnly APIs like `AppDomain.ReflectionOnlyGetAssemblies()` are doing the right thing already.

**Comment by jkotas** [comment]
ReflectionOnlyGetType also - we do not seem to have any tests for it.

**Comment by rahku** [comment]
Fixed
