### ISSUE TITLE
Remove desktop build where not relevant to CoreCLR (native parts)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#9069]
Is there any unnecessary desktop build going on in the native code?

@jkotas - you mentioned GC and JIT still build for desktop, is there any build cleanup still worth doing here.

We already removed desktop build for corelib in https://github.com/dotnet/coreclr/commit/6fca5f4b27deb845ae793cc887b8d631c5a56271.

**Comment by jkotas** [comment]
The desktop build system was removed in #8723. I do not think there is much to cleanup around desktop build system.

The cleanup on the native side is about deleting the ifdefs, unused files and otherwise dead code.

**Comment by danmosemsft** [comment]
OK that's sufficiently covered in https://github.com/dotnet/coreclr/issues/9067 then.
