### ISSUE TITLE
Stop using signals for starting threads in suspended state

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/coreclr#907]
In PAL, we currently use signals for suspending and resuming threads on non-Windows platforms. It would be great to use some other mechanism to accomplish this, since it would free up SIGUSR1 and SIGUSR2 for other uses. As an additional benefit, this would make debugging less painful since LLDB breaks by default on these signals.

A good starting point might be the code that's used when we call `CorUnix::InternalCreateProcess` with the `CREATE_SUSPENDED` flag. It starts a thread suspended by making it wait for a specific byte to be sent through a pipe. A similar concept could be used in the places where we rely on signals.

**Comment by kangaroo** [comment]
On OSX, we can move to just suspending the thread port rather simply, however we have larger lldb integration problems there currently.

On the other hand, pipes will consume fd's, which will contribute towards the ulimit.  Aside from the regular signal processing issues, is there a reason to move away from the current implementation?  Is this issue part of the larger goal to fix the signal problems related to GC susp/resume?

**Comment by adityamandaleeka** [comment]
The eventual goal (beyond the scope of this issue) is to remove Suspend/ResumeThread from PAL entirely. 

With that in mind, given that we'll have only a few places where we still need some kind of suspend/resume ability (such as when creating threads suspended), it seems suboptimal to continue to use the signal-based method. If we find an approach that's more suitable for this than pipes, we can definitely use that. I mentioned pipes as an option only because they're being used today in the process creation logic.

The ulimit issue is a good point to keep in mind. These pipes should be short-lived since they're closed once the thread has resumed. However, I agree that it would be nice not to consume fd's at all.
