### ISSUE TITLE
Clearing up licensing of CoreCLR

### ISSUE THREAD

**Issue by hifi** [dotnet/coreclr#9080]
The root of CoreCLR has the MIT license but https://github.com/dotnet/coreclr/blob/master/src/.nuget/dotnet_library_license.txt seems to be some kind of generic Microsoft EULA for published .NET components which is included in the NuGet packages built from this repo AFAIK.

Could this be cleared up?

**Comment by janvorli** [comment]
CC: @richlander

**Comment by richlander** [comment]
Thanks for reporting. We don't want that.

@ellismg - Matt was looking at this general issue. Can you take care of this one, too, or point to other folks who should?

**Comment by ellismg** [comment]
The current PoR is to adopt the MIT license for nuget packages where the code that makes them up is already MIT licensed.  I should be pushing this change through shortly (there are still some internal issues we need to close on before we can do the change, but we are pushing on it).

**Comment by hifi** [comment]
Thank you @ellismg and others for the answers. The corefx repo is also using the same license text for NuGet packages.

I'm interested in trying packaging CoreCLR and CoreFX with all the required (compile and runtime) components as proper Linux distribution packages with offline reproductive builds in mind when licensing is fixed and all the components for self hosting are available. Goal would be to be able to build and run simple .NET Core applications with no external dependencies without connecting to the internet.

**Comment by richlander** [comment]
That sounds great, @hifi. In fact, we are in the process of developing a plan (docs are coming) on how to make your exact scenario easier.

We're interesting in talking to anyone who wants to become a distro maintainers for .NET Core. We'd like to get feedback from you on what you care about the most and what you need to be successful. Drop me a mail at rlander@ms if you want to chat about this.

**Comment by gkhanna79** [comment]
@richlander @ellismg Is there anything actionable here?

**Comment by ellismg** [comment]
We should change the license file in our packages away from the .NET Library License and to the MIT license.

Do we bundle any external code that's not MIT licensed as part of any of the builds (I could imagine that for windows we end up pulling in some windows PDB stuff that is not open source).

**Comment by gkhanna79** [comment]
@richlander This is being tracked for ZBB for 2.0 on 5/10. Can you PTAL?

**Comment by gkhanna79** [comment]
@richlander @bleroy Any ETA on this?

**Comment by Petermarcu** [comment]
@richlander is this going to happen for 2.0.0?

**Comment by karelz** [comment]
@richlander is there any work left or can we close it?

**Comment by jkotas** [comment]
This is fixed (verified that https://www.nuget.org/packages/Microsoft.NETCore.App/2.1.0-rc1 has MIT license).
