### ISSUE TITLE
Delete old mscorlib facade

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#9087]
Delete
src/mscorlib/ref/mscorlib.csproj
src/mscorlib/facade/mscorlib.csproj

They are replaced by a facade coming out of corefx/src/shims

Issues:
1)	@RussKeldorph is updating CoreClr testing to use flat package
2)	I suspect the old mscorlib façade and the new one might not be 100% compatible. 
a.	Old one might have different identity (version and key)
b.	Old one had some internal APIs which I’m not sure are needed or not. Hopefully they aren’t needed but we will only be able to find out when we test with the new one.

**Comment by jkotas** [comment]
Dups: https://github.com/dotnet/coreclr/issues/7607 https://github.com/dotnet/coreclr/issues/5739

**Comment by AlexGhiondea** [comment]
Let's track this with #7607
