### ISSUE TITLE
It seems build cannot cannot be processed in x86 version of Linux (Ubuntu)?

### ISSUE THREAD

**Issue by huzq** [dotnet/coreclr#909]
Build environment:
1. x86 version of Ubuntu (14.10)
2. Installed all the dependencies which introduce in "building and testing instructions"
3. run ./build.sh
4. Getting following results:
==================================
Commencing CoreCLR Repo build
Setting up directories for build
Checking pre-requisites...
Commencing build of native components for Linux.x64.Debug
Invoking cmake with arguments: "/home/kevin/research/openSource/coreclr" DEBUG
-- LLDB: /usr/lib/i386-linux-gnu/liblldb-3.5.so
-- LLDB_H: /usr/lib/llvm-3.5/include
CMake Error at CMakeLists.txt:339 (message):
  error: Detected non x86_64 target processor.  Not supported!

-- Configuring incomplete, errors occurred!
See also "/home/kevin/research/openSource/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeOutput.log".
See also "/home/kevin/research/openSource/coreclr/bin/obj/Linux.x64.Debug/CMakeFiles/CMakeError.log".
Failed to generate native component build project!
==================================

**Comment by shahid-pk** [comment]
x86 architecture is not supported. not even on windows

**Comment by ellismg** [comment]
As @shahid-pk points out, we don't support targeting x86, but it is on the roadmap.
