### ISSUE TITLE
Struct with Explicit layout not honouring ANSI CharSet

### ISSUE THREAD

**Issue by alexwiese** [dotnet/coreclr#9093]
**Environment/version**

Microsoft.NETCore.App 1.1.0
Microsoft.NETCore.Runtime.CoreCLR 1.1.0
Windows 10 x64 (Build 1607)

**Description of problem**

I have the following structure that works as expected with sequential layout. The characters are populated correctly (using ANSI CharSet), when marshalled from unmanaged memory, with the value of a single byte (rather than 2-byte Unicode values).

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1)]
    public struct MyStructSequential
    {
        public char A;
        public char B;
    }

I can create a copy of that structure from a byte array and I get the expected result.

    var data = new[] { (byte)'J', (byte)'M' };

    var ptr = Marshal.AllocHGlobal(data.Length);
    Marshal.Copy(data, 0, ptr, data.Length);
    var sequential = Marshal.PtrToStructure<MyStructSequential>(ptr);
            
    Console.WriteLine($"sequential.A: {sequential.A} ({(int)sequential.A}) (0x{(int)sequential.A:X})");
    Console.WriteLine($"sequential.B: {sequential.B} ({(int)sequential.B}) (0x{(int)sequential.B:X})");

This produces the following output, which is what I expect to see (characters 'J' and 'M').

    sequential.A: J (74) (0x4A)
    sequential.B: M (77) (0x4D)

If I change the `LayoutKind` to be `Explicit` and provide the field offsets for each field I get a different result. It appears the character values are being populated with 2-byte values instead.

    [StructLayout(LayoutKind.Explicit, CharSet = CharSet.Ansi, Pack = 1)]
    public struct MyStructExplicit
    {
        [FieldOffset(0)]
        public char A;
        [FieldOffset(1)]
        public char B;
    }

This struct produces this output instead, which I did not expect.

    explicitStruct.A: ? (19786) (0x4D4A)
    explicitStruct.B: M (77) (0x4D)

The only difference between the two structures (from my POV) is that one is specifying the layout explicitly, and one is not.
Is this a bug or expected behaviour?

**Comment by alexwiese** [comment]
Minimal repro on GitHub -> https://github.com/alexwiese/StructLayoutRepo

**Comment by danmosemsft** [comment]
Does it repro on desktop?

**Comment by alexwiese** [comment]
@danmosemsft yes.

**Comment by jakobbotsch** [comment]
`sizeof(char) == 2` in .NET, so the explicit layout version should look like this to be equivalent:
```
[StructLayout(LayoutKind.Explicit, CharSet = CharSet.Ansi, Pack = 1)]
public struct MyStructExplicit
{
    [FieldOffset(0)]
    public char A;
    [FieldOffset(2)]
    public char B;
}
```

As it is the write to `B` will overwrite the last byte of `A`.

**Comment by jakobbotsch** [comment]
`FieldOffset` is concerned with the physical layout of the structure, that is it will affect how the actual struct `MyStructExplicit` is laid out in memory. Specifying `CharSet = CharSet.Ansi` will not cause `char` fields to be 1-byte; instead it will just specify that, when marshalling, the `char` fields should use 1-byte ANSI.

So in your explicit structure the offset of `B` will be 1, but the sizes of fields `A` and `B` are still 2; so any write/read from `A` will also affect `B`. It is possible the marshaller is only filling the 1 byte correctly, but when you access the fields, this does not matter since you have specified the fields to be overlapping.

**Comment by alexwiese** [comment]
If that was the case then how does the struct with sequential layout marshal to/from a byte array with only two bytes (and have the fields populated with just a single byte value each). 

It seems to me that there should, in practice, be no difference between a struct with fields set sequentially and one with fields set explicitly (if the explicit offsets match the sequential ones).

**Comment by jakobbotsch** [comment]
Marshalling is a process that happens on top of the structure; it is not an actual 1-to-1 translation of the structure as laid out in memory to bytes.
As an example you can try comparing `sizeof(MyStructExplicit)` to `Marshal.SizeOf<MyStructExplicit>()`.

**Comment by danmosemsft** [comment]
@yizhang82 is this a bug?

**Comment by yizhang82** [comment]
@danmosemsft Not a bug. @jakobbotsch is correct. CharSet only affects how CLR marshals the struct to native - the managed side of the struct is still using UTF-16 char. By having a offset(0) and offset(1) char fields, they effectively overlap with each other by 1 byte and that is not very good.  
@alexwiese Please feel free to let us know if you still have more questions.
