### ISSUE TITLE
Add DumpHeapStat code to SOS.

### ISSUE THREAD

**Issue by mikem8361** [dotnet/coreclr#9098]
The SOS!DumpHeap implementation has two main perf hot spots: there is a check for break in AddStat function for each step in searching a binary tree, there is a linear search in allocation context array every time moving from one object to next one.
 
I'm adding more stat information. The latest addition is adding where certain type in certain generation appears most in a heap segment. HeapDumpW has a /crossRef option to dump every object into .csv files by heap segment and generation. So combining the two, I just go to a .csv file to look for certain type I have concern with.

Feng Yuan

**Comment by danmosemsft** [comment]
UPloaded file and removed internal link
[DumpHeapStat.cs.txt](https://github.com/dotnet/coreclr/files/728336/DumpHeapStat.cs.txt)

**Comment by mikem8361** [comment]
Issue moved to [dotnet/diagnostics #51](https://github.com/dotnet/diagnostics/issues/51) via [**ZenHub**](https://www.zenhub.com/)
