### ISSUE TITLE
JIT/Performance/CodeQuality/SIMD/RayTracer failing under JITStress=2

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#9108]
See e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitstress2/68/

**Comment by pgavlin** [comment]
@CarolEidt @sivarv can one of you take a look?

**Comment by sivarv** [comment]
I will take a look at this.
