### ISSUE TITLE
Infinite loop causing hang in System.Numerics.Vectors.Tests on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#9109]
I've now seen two hangs today in different CoreFx PR CIs in the System.Numerics.Vectors.Tests tests on Windows release:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2495/
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_release_prtest/2487/
I was able to catch one and attach a debugger.  It looks like it's stuck in the JIT in an infinite tail call loop in:
```clrjit.dll!ValueNumStore::VNForRefInAddr(unsigned int vn)```
![image](https://cloud.githubusercontent.com/assets/2642209/22303270/7e4022da-e300-11e6-9727-59055c0ba82c.png)
cc: @CarolEidt, @mellinoe

**Comment by CarolEidt** [comment]
This seems to be the same method that is dying with a seg fault in https://github.com/dotnet/corefx/issues/15309.

**Comment by CarolEidt** [comment]
@stephentoub I believe this is fixed by my PR #9123.

**Comment by stephentoub** [comment]
Thanks, Carol.  I'll close it and re-open it if we see it again.
