### ISSUE TITLE
Use CoreClr.Testwrapper for all CoreCLR test runs

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#9147]
Currently we use Desktop.Coreclr.Testwrapper for Dev runs & in the CI, but Coreclr.Testwrapper in Helix - see https://github.com/dotnet/coreclr/blob/master/tests/runtest.proj#L104 and https://github.com/dotnet/coreclr/blob/master/tests/src/dirs.proj#L20. We should always use Coreclr.Testwrapper

**Comment by sbomer** [comment]
This is being done as part of https://github.com/dotnet/coreclr/pull/18695.
