### ISSUE TITLE
Obsolete documentation on https://github.com/dotnet/coreclr/wiki/Linux-instructions

### ISSUE THREAD

**Issue by ubikuity** [dotnet/coreclr#915]
The wiki page https://github.com/dotnet/coreclr/wiki/Linux-instructions is obsolete compared to the original documentation: https://github.com/dotnet/coreclr/blob/master/Documentation/linux-instructions.md

For example, on the page https://github.com/dotnet/coreclr/wiki/Linux-instructions it's written:
"D:\git\corefx> build.cmd /p:OS=Linux /p:SkipTests=true"
it should be written:
"D:\git\corefx> build.cmd /p:OSGroup=Linux /p:SkipTests=true"

(There is a similar problem on the page https://github.com/dotnet/coreclr/wiki/OS-X-instructions )

**Comment by jkotas** [comment]
@richlander Delete the obsolete wiki pages?

**Comment by ellismg** [comment]
I just deleted them.
