### ISSUE TITLE
Optimize Span Fill, Clear, and CopyTo method implementations

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/coreclr#9161]
Currently the following Span methods contain trivial implementations and they need to be optimized.
- Fill
- Clear
- CopyTo

**Comment by gkhanna79** [comment]
@kouvel Is this something you will be working upon? If so, can you please assign to your self or reassign as appropriate?

**Comment by kouvel** [comment]
@ahsonkhan, is this something you will be working on later?

**Comment by ahsonkhan** [comment]
@kouvel, I wasn't planning on working on this in the near future.

**Comment by jkotas** [comment]
We will want to add some runtime helpers to make these efficient. It would be nice to match the names and signatures of the similar helpers in CoreRT to ease sharing of the implementation:

e.g. RhBulkMoveWithWriteBarrier https://github.com/dotnet/corert/blob/d84f5310c80708584bb908615a331b5520a28d63/src/System.Private.CoreLib/src/System/Runtime/RuntimeImports.cs#L531
