### ISSUE TITLE
Make EnsureSufficientExecutionStack less conservative

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#9167]
> @jcouv 

The compiler is using EnsureSufficientExecutionStack. From what I can tell, that method throws when the stack is only a bit more than half full. In the repro I’m investigating, the stack when the exception is thrown is about 520kB long. When I remove the EnsureSufficientExecutionStack check, the overflow occurs when the stack is full (at 1MB).

Is there any way to do something like EnsureSufficientExecutionStack but not give up on half of the potential stack usage?

> @jkotas

I agree that it may be too conservative and it may be worth it to make it less conservative, e.g. return true if there is 128k (on 64-bit platforms) / 64k (on 32-bit platforms) available.

**Comment by jcouv** [comment]
I didn't follow how https://github.com/dotnet/corefx/pull/15600 fixed this. That PR only has test changes. Was the problem resolved earlier and the new tests just verify it?

**Comment by kouvel** [comment]
Yes these are just tests for the functional fix in PR dotnet/coreclr#9186
