### ISSUE TITLE
Add documentation for SuperPMI

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#9180]
It gets mentioned in PRs, its exe taunts me in the bin/Product directory; yet there is no info about it and what its for, or how to use it in the repo.

(Not suggesting I'd use it; though I can't determine that, just might be good to have it documented)

**Comment by karelz** [comment]
I added a one liner into [glossary](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/glossary.md).
@RussKeldorph @jeffschwMSFT @jkotas who can help provide basic info/usage?

**Comment by mikedn** [comment]
The SuperPMI source [directory](https://github.com/dotnet/coreclr/tree/master/src/ToolBox/superpmi) has a readme.

**Comment by benaadams** [comment]
@mikedn thank you 😄
@karelz maybe link from glossary?

**Comment by karelz** [comment]
Done! :)
