### ISSUE TITLE
AnyCPU 32-bit preferred exe not running by Windows x64 runtime

### ISSUE THREAD

**Issue by linquize** [dotnet/coreclr#92]
AnyCPU 32-bit preferred exe not running by Windows x64 runtime.

This is just 32-bit preferred, not required.
So if 32-bit is not available, run the exe in 64-bit mode.

However, 02084af832c2900cf6eac2a168c41f261409be97 does not run the exe in 64-bit mode, it fails to run.
Failed to load: path_to_XXX.exe
Error code: 193

**Comment by Alexx999** [comment]
I believe that for me AnyCPU fails even when built without "Prefer 32bit" flag - so probably that's problem in general

**Comment by linquize** [comment]
AnyCPU without 32-bit flag seems OK to me. I untick the prefer 32-bit checkbox.

**Comment by Alexx999** [comment]
Indeed, it works fine. Probably I was doing something else wrong too while seeking for combination of options that will work with CoreClr

**Comment by linquize** [comment]
On Linux x64, a 32-bit preferred exe can run successfully.
