### ISSUE TITLE
Complexity of RID graph

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#9210]
Lifted from https://github.com/dotnet/coreclr/issues/5853#issuecomment-276078171

> Can the RID graph be simplified by removing possibly unused RIDs?

e.g. the rid graph for `ubuntu.14.04-x64` looks like this now:
```
                               base
                                 |
                                any
                                 |
                                unix
                               |     |
                          linux     unix-x64
                         |      |       |
                   debian       linux-x64
                  |      |        | 
            ubuntu       debian-x64       
          |        |        |
ubuntu14.04        ubuntu-x64
      |              |
      ubuntu.14.04-x64
```

Are these RIDs used in practice (by .NET Core or any package on NuGet): unix, debian, ubuntu, ubuntu14.04, ubuntu-x64, debian-x64?

Leaving those out, would simplify the graph to:

```
base <- any <- linux                           // pure managed libraries
                 ^- linux-x64                  // library with native bits
                           ^- ubuntu.14.04-x64 // runtime end-point
```

\cc @janvorli @jkotas @gkhanna79

**Comment by janvorli** [comment]
CC @Petermarcu

**Comment by Petermarcu** [comment]
@ericstj  ?

**Comment by ericstj** [comment]
What do you aim to "simplify"?  The RID structure is public and anyone can use those RIDs so even if we aren't using them doesn't mean its safe to remove them: that'd be a breaking change.  The structure is documented here: https://github.com/dotnet/corefx/tree/master/pkg/Microsoft.NETCore.Platforms.

I know that there are folks relying on the debian relationship /cc @moozzyk.  There are folks using the architecture-specific version-less RIDs as well.  In CoreFx we use the structure down to Linux in our managed packages, as well as the ach+version-specific-RIDs in our native packages.

**Comment by moozzyk** [comment]
The libuv package currently uses the `debian-x64` RID for a libuv version for debian and debian derivatives (e.g. ubuntu).

**Comment by tmds** [comment]
> What do you aim to "simplify"? The RID structure is public and anyone can use those RIDs so even if we aren't using them doesn't mean its safe to remove them: that'd be a breaking change.

@ericstj Yes, I understand. I am looking for the rationale for these RIDs. E.g. if your library targets `debian` or `debian-x64`, what does that mean? You can't assume anything more over the parent RIDs, right?
e.g. @moozzyk, why do you target `debian-x64`? and not `linux-x64`?

**Comment by ericstj** [comment]
> what does that mean?

@tmds anything that might be unique behavior for that set of OSes: api, functional behavior, dependencies, etc.  Correct you cannot assume things over the parent RIDs.  Surely since each RID does represent a unique OS or intersection of OSes one can assign unique characteristics to that OS / intersection of OSes.

**Comment by tmds** [comment]
> @tmds anything that might be unique behavior for that set of OSes: api, functional behavior, dependencies, etc. Correct you cannot assume things over the parent RIDs. Surely since each RID does represent a unique OS or intersection of OSes one can assign unique characteristics to that OS / intersection of OSes.

Indeed, the RID represents a unique OS or intersection of OSes. There are no fixed characteristics at this level you can rely on. So, the RID is a way of grouping stuff but it doesn't do anything useful.

@ericstj please also have a look at this related issue: https://github.com/dotnet/coreclr/issues/9208. 

@moozzyk can you elaborate why you target `debian-x64`?

**Comment by moozzyk** [comment]
@tmds: Can you be more specific what you want to know. I thought https://github.com/dotnet/coreclr/issues/9210#issuecomment-276577031 explains it but let me know if you want more details.

**Comment by tmds** [comment]
> @tmds: Can you be more specific what you want to know. I thought #9210 (comment) explains it but let me know if you want more details.

What is debian specific about the libuv package for `debian-x64`?

**Comment by moozzyk** [comment]
Originally the plan was to ship separate libuv for each major supported distro. Since both Debian (AFAIR 8.2) and Ubuntu 14.04 were supposed to be supported and Ubuntu is a derivative of Debian it made sense to have just libuv only for debian-x64 which would be used by all RIDs 'deriving' from debian-x64
Given that libuv depends only on libc we recently started experimenting with having just one libuv version for 64-bit Linux distributions - you can find that the latest libuv package available on myget contains libuv for linux-x64 RID.

**Comment by tmds** [comment]
I believe the `unix` rid is used by .net core for managed assemblies that work across linux and unix oses.
The `unix-x64` isn't meaningful since there is no binaries that can be shared at this level.
The `debian`, `ubuntu`, `debian-x64`, `ubuntu-x64` don't bring anything useful compared to their parents, i.e. one cannot assume certain libraries, apis will be present.
The `ubuntu14.04` allows to make some assumptions. It is debatable whether a managed library should target this RID or a more generic RID and detect the OS at runtime.

@ericstj does this make sense?

**Comment by am11** [comment]
I understand that these RIDs are only for .NET Core packaging; we are considering the same established convention to use in our build. In my opinion, there needs to be 'C' library section in RID construction.

For example, our native lib also just depends on `libc`, so we usually build on old CentOS (gcc 4.4) to maximize the compatibility. However, in the packaging story I am working on, I still need to classify platform by 'C' library.

Use case: Alpine Linux is not the only one using musl-libc; wiki says, other are:

> Dragora 3, OpenWRT, Sabotage, Morpheus Linux and **optionally prebuilt** for Void Linux.

Now, if we build a NuGet package with prebuild binaries for Void Linux with native dependencies, it will have a same OS version, but differs by the OS primary 'C' library based  (ECGLIBC or musl libc in this case).

My existing workaround is to coin custom platform names in 'PlatformName / PlatformFamily' section of RID that CoreFX: `unix-musl`, `unix-bionic`, `unix-libc` (constitutes: libc, glibc, eglibc) etc.

Dare I say "`System.Runtime.InteropServices.RuntimeInformation` should expose an API method for 'C' lib information", as we have an MSBuild inline task which fetches all the salient platform identifiers from that assembly except for the 'which primary libc this system is using'. For that matter, I had to fallback to `<Exec>` in our MSBuild script, which greps on `ldd --version` to get 'C' lib info `{name, version}` (for the platforms, where it is applicable -> all Linux and BSD operating systems).

**Comment by tmds** [comment]
> In my opinion, there needs to be 'C' library section in RID construction.

@am11 see https://github.com/dotnet/coreclr/issues/9208

**Comment by tmds** [comment]
> The unix-x64 isn't meaningful since there is no binaries that can be shared at this level.
The debian, ubuntu, debian-x64, ubuntu-x64 don't bring anything useful compared to their parents, i.e. one cannot assume certain libraries, apis will be present.
The ubuntu14.04 allows to make some assumptions. It is debatable whether a managed library should target this RID or a more generic RID and detect the OS at runtime.

@Petermarcu does this make sense?

Could we 'obsolete' these and similar RIDs? E.g. they can be marked in the runtime.json and no similar RIDs (e.g. alpine-x64 is a new one) should be added.

**Comment by Petermarcu** [comment]
I think the challenge with simplifying is that we really don't know how people are using some of these RID's. I think we should be mindful as we add new ones but I'm not sure we can simplify it now.

**Comment by tmds** [comment]
> I think the challenge with simplifying is that we really don't know how people are using some of these RID's. I think we should be mindful as we add new ones but I'm not sure we can simplify it now.

I think the problem is people are not provided with enough information to choose the proper RID (and the amount of RIDs isn't helping).

The section "How to use native dependencies" at https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries says:

> Specifying a Runtime Identifier (RID) in a runtimes section.

That's it, with a reference to https://docs.microsoft.com/en-us/dotnet/articles/core/rid-catalog.

--

libuv's is a good example.

The `debian-x64` native lib isn't debian specific:
```
~$ ldd ~/.nuget/packages/Libuv/1.9.1/runtimes/debian-x64/native/libuv.so 
	linux-vdso.so.1 (0x00007ffe67dee000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f42610ba000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f4260eb6000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f4260cad000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4260a91000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f42606ce000)
	/lib64/ld-linux-x86-64.so.2 (0x000055ee18961000)
```
The `osx` native lib is missing an architecture:
```
~$ file ~/.nuget/packages/Libuv/1.9.1/runtimes/osx/native/libuv.dylib 
/home/tmds/.nuget/packages/Libuv/1.9.1/runtimes/osx/native/libuv.dylib: Mach-O universal binary with 2 architectures: [i386: Mach-O i386 dynamically linked shared library] [x86_64: Mach-O 64-bit x86_64 dynamically linked shared library]
```

**Comment by tmds** [comment]
@Petermarcu shall I close this issue and open one in docs to improve the documentation on what RID to use?

**Comment by Petermarcu** [comment]
That sounds good.

**Comment by tmds** [comment]
Created https://github.com/dotnet/docs/issues/1693
