### ISSUE TITLE
Delegate.CreateDelegate() - parameter validation hole.

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/coreclr#9215]
Consider the following.

```
    public class C
    {
        public static void Main()
        {
            Type theT = typeof(G<>).GetTypeInfo().GenericTypeParameters[0];
            Type delegateType = typeof(Func<object, object, bool>);
            Delegate d = Delegate.CreateDelegate(delegateType, theT, "ReferenceEquals");
        }
    }

    public class G<T> { }
```

Expected behavior would be an ArgumentException on "target." 

Problem is that the <a href="https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Delegate.cs#L71">validation code</a> that's supposed to catch this is written as:

```
            if (target.IsGenericType && target.ContainsGenericParameters)
                throw new ArgumentException(Environment.GetResourceString("Arg_UnboundGenParam"), nameof(target));

```

The "IsGenericType" part of the conditional makes no sense - it lets types that represent type variables slide through.

The result is not pleasing (as in FatalExecutionEngine errors and unmanaged asserts firing.)

**Comment by danmosemsft** [comment]
@AtsushiKan feel like throwing up a PR?

**Comment by AtsushiKan** [comment]
Added the "easy" tag - this is nice fodder for first time contributors.

**Comment by gkhanna79** [comment]
Is this required for 2.0?

**Comment by mattwarren** [comment]
I'm happy to have a go at this.

@AtsushiKan the code you posted actually ends up hitting the same check, but in a different place, the one inside `CreateDelegate(Type type, Type target, String method, bool ignoreCase, bool throwOnBindFailure)`, not the delegate `.ctor` (`Delegate(Type target, String method)`) you linked to.

Having said that, if I change [this line](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Delegate.cs#L402) in `CreateDelegate(..)` from

``` csharp
if (target.IsGenericType && target.ContainsGenericParameters)
```

to

``` csharp
if (target.ContainsGenericParameters)
```

and then run your code, I get the following output:

```
System.ArgumentException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.
Parameter name: target
   at System.Delegate.CreateDelegate(Type type, Type target, String method, Boolean ignoreCase, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, Type target, String method)
   at Test.C.Main()
```

Is this the fix that you wanted or have I missed something out?

**Questions**

1. Do I also need to make the equivalent change in the code that you originally [linked to](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Delegate.cs#L71), i.e. in `Delegate(Type target, String method)`?
2. If so, what test/sample code do I need to write to have that `.ctor` called, do I need to create my own delegate or something like that? (i.e. `public delegate void TestDelegate()`)?
3. I assume that there needs to be some tests written for this, should they [go here](https://github.com/dotnet/coreclr/blob/master/tests/src/CoreMangLib/system/delegate/generics/) in `common.cs` for instance, or is there somewhere else more appropriate?

**Comment by AtsushiKan** [comment]
Yep, that’s the fix.

**Comment by AtsushiKan** [comment]
>Do I also need to make the equivalent change in the code that you originally linked to, i.e. in Delegate(Type target, String method)?

Yep, looks like another instance of the same mistake.

>2.If so, what test/sample code do I need to write to have that  .ctor  called, do I need to create my own delegate or something like that? (i.e.  public delegate void TestDelegate() )?

Hmm.. I'm not sure how that constructor would be reached. I think this is just an obsolete architectural vestige that's only there to keep apicompat happy.

>3. I assume that there needs to be some tests written for this

Appropriate place would be in the corefx repo (System.Runtime.Tests.) I don't think a test is really pri-1 for this, though.

**Comment by danmosemsft** [comment]
@mattwarren you should get an email offering you contributor rights, when you accept that I can assign you issues like this one!

**Comment by danmosemsft** [comment]
@mattwarren assigned. ..!

**Comment by mattwarren** [comment]
@danmosemsft thanks, I didn't actually have to _accept_ contributor rights, I just got an email saying 'Subscribed to dotnet/coreclr notifications'? (maybe because I'm already part of the DotNetFoundation?). Either way, I soon turned off that fire-hose, wow, I'm not sure how anyone can deal with **all** the notifications that the CoreCLR outputs ;-)

@AtsushiKan 

> Appropriate place would be in the corefx repo (System.Runtime.Tests.) I don't think a test is really pri-1 for this, though.

Are you saying I can send a PR that fixes this, _without_ accompanying tests?

**Comment by AtsushiKan** [comment]
>Are you saying I can send a PR that fixes this, without accompanying tests?

Yes - this is normal practice since the tests and runtimes are in separate repos. 

So the typical process is - 

1. PR the fix for CoreLib in the CoreCLR repo and get it merged.
2. Wait a day or two for the CoreFX repo to update to the fixed CoreCLR bits.
3. Then in the CoreFx repo, PR whatever tests you want to add for the fix.

For this particular bug, I think #3 is pretty optional (but you're welcome to submit a test if you like!)

**Comment by zaytsev-victor** [comment]
Since there is no updates from April, can I take it?

**Comment by jkotas** [comment]
Yes, you are welcomed to!

cc @karelz

**Comment by karelz** [comment]
@zaytsev-victor I added you to collaborator list. Ping me hen you accept. As with CoreFX, we recommend to disable all notifications for the repo (it's quite a lot).

@mattwarren I assume you don't work on the issue anymore. Can you please confirm?

**Comment by zaytsev-victor** [comment]
@karelz I've accept invitation, thanks

**Comment by mattwarren** [comment]
> I assume you don't work on the issue anymore. Can you please confirm?

@karelz yeah that's fine, I've not done anything with this in 7 months!!

**Comment by jkotas** [comment]
@zaytsev-victor Are are also interested in adding a test to https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/DelegateTests.cs ? @AtsushiKan said it is optional ... but I think it would be nice to have one.

**Comment by zaytsev-victor** [comment]
@jkotas Yes, sure, thanks!

**Comment by tdinucci** [comment]
FYI, it looks like @zaytsev-victor did this and the issue can be closed - https://github.com/dotnet/corefx/pull/25528

**Comment by karelz** [comment]
@tdinucci thanks for catching that!
