### ISSUE TITLE
Port latest C# pi-digits benchmark

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#9219]
Source of benchmark:
http://benchmarksgame.alioth.debian.org/u64q/csharp.html

This version of benchmark replaced BigInteger with a native implementation and uses PInvokes.

This benchmark needs to be ported to both Core and Desktop.

**Comment by AndyAyersMS** [comment]
Not sure we really want to do this; would rather have tests that are primarly testing jitted code.

**Comment by AndyAyersMS** [comment]
Closing per comment above.
