### ISSUE TITLE
Port C# Knucleotide benchmark to Core

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#9220]
Source: 
http://benchmarksgame.alioth.debian.org/u64q/csharp.html

This version is same as the cqPerf version ported to desktop.

**Comment by guhuro** [comment]
Hey, I've been working on this. I'll go ahead and take it.

**Comment by DrewScoggins** [comment]
Assigning this to myself while Gustavo and I work out getting him in the .NET Foundation and other permission stuff.

**Comment by guhuro** [comment]
You can see the pull request here https://github.com/dotnet/coreclr/pull/9293

**Comment by DrewScoggins** [comment]
This was merged in the above PR.
