### ISSUE TITLE
Move CoreCLR's pipebuild & build definitions into checked-in JSON blobs

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#9257]
CoreFX already does this - https://github.com/dotnet/corefx/tree/master/buildpipeline. We should do the same. At the same time, we should change our Linux jobs to use the Docker-exec pattern that CoreFX uses, instead of the 'checkout, do something, delete' pattern we use now.

**Comment by wtgodbe** [comment]
CC @gkhanna79

**Comment by gkhanna79** [comment]
This is done, so closing.
