### ISSUE TITLE
Failure to build the coreclr

### ISSUE THREAD

**Issue by IakovK** [dotnet/coreclr#927]
I tried to build the coreclr by following the instructions at https://github.com/dotnet/coreclr/blob/master/Documentation/windows-instructions.md.
My tools versions are: Windows 7 Professional (SP!) and Visual Studio 2013 Professional.
The coreclr seems to build normal, but the tests build fails with the following messages (a lot of them):

```
D:\Projects\clr\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\packageresolve.targets(25,5): warning : Unable to resolve the assets of Microsoft.CodeAnalysis.Workspaces.Common: Couldn't find a matching group [D:\Projects\clr\coreclr\tests\src\managed\Compilation\Compilation.csproj]
D:\Projects\clr\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\packageresolve.targets(25,5): warning : Unable to resolve the assets of System.Collections.Immutable: Couldn't find a matching group [D:\Projects\clr\coreclr\tests\src\managed\Compilation\Compilation.csproj]
D:\Projects\clr\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\packageresolve.targets(25,5): warning : Unable to resolve the assets of System.Reflection.Metadata: Couldn't find a matching group [D:\Projects\clr\coreclr\tests\src\managed\Compilation\Compilation.csproj]
CSC : error CS0518: Заранее определяемый тип "System.Object" не определен или не импортирован [D:\Projects\clr\coreclr\tests\src\managed\Compilation\Compilation.csproj]
Test build failed. Refer D:\Projects\clr\coreclr\tests\..\bin\Logs\Tests_Managed_Windows_NT__x64__Debug.log for details
Test binaries build failed. Refer D:\Projects\clr\coreclr\bin\Logs\MScorlib_Windows_NT__x64__Debug.log for details.
```

(it is a fragment.)

If I try to build corefx right after that, I get similar errors when building corefx itself.

**Comment by jkotas** [comment]
The managed code build requires network access to download nuget packages required by the build. These errors suggest that the nuget packages required by the build were not downloaded successfully.

@weshaggard @AlexGhiondea Is it possible to make these issues easier to diagnose?

**Comment by IakovK** [comment]
Thanks for information.
I had no problems with network access during build.
My own experience showed the following:
somewhere among these issues I found that xamarin caused conflicts; I had xamarin tools for android installed. After I uninstalled them, the build worked.

Maybe it is worth mentioning in [windows-instructions.md](https://github.com/dotnet/coreclr/blob/master/Documentation/windows-instructions.md) file?
Currently it has **Known Issues** section that says only

The DIA SDK gets incorrectly installed when VS 2013 is installed after VS 2012. To workaround this issue), copy  %program files (x86)%\Microsoft Visual Studio 11.0\DIA SDK  to  %program files (x86)%\Microsoft Visual Studio 12.0\DIA SDK . You can then build CoreCLR.

To add something like this:
Xamarin tools for Android cause conflicts. If you fail to build, uninstall them.

**Comment by AlexGhiondea** [comment]
Thanks for reporting this. 

How did you figure out it was Xamarin tools for Android that caused the issues (other than uninstalling it fixed it :) )?

**Comment by IakovK** [comment]
https://github.com/dotnet/corefx/issues/1628 contains the following:

The new Visual Studio 2015 RC will install xamarin if you select all the defaults, go to add/remove programs and remove the xamarin install and it should work.

I didn't have VS2015 but I did have xamarin. I uninstalled it and it worked. :)

**Comment by AndyAyersMS** [comment]
FWIW I hit similar-sounding errors building the tests from CoreCLR, though this was a while back, and they went away when I uninstalled xamarin.

```
17:09:26.569     3>ResolveNuGetPackages: (TargetId:26)
                     resolving assets from C:\llilc\CoreCLRTestAssets\coreclr\tests\src\packages\System.Diagnostics.Process.4.0.0-beta-22412\System.Diagnostics.Process.4.0.0-beta-22412.nupkg (TaskId:40)

17:09:27.100     3>C:\llilc\CoreCLRTestAssets\coreclr\tests\src\packages\Microsoft.DotNet.BuildTools.1.0.21-prerelease\lib\packageresolve.targets(25,5): warning : Unable to resolve the assets of System.Diagnostics.Process: Couldn't find a matching group 
```

**Comment by jasonwilliams200OK** [comment]
@JohnPilczak, @topgenorth, @atsushieno, any ideas what is causing the clash here?
Related: https://github.com/dotnet/coreclr/issues/1033#issuecomment-104717889.

**Comment by atsushieno** [comment]
Let me ask our VS/Windows team.

**Comment by kzu** [comment]
That's weird. Will try it out and report back

**Comment by akoeplinger** [comment]
@kzu note that there's a more detailed discussion of the problem here: https://github.com/dotnet/corefx/issues/449

**Comment by DickvdBrink** [comment]
Any update on this?

**Comment by kzu** [comment]
No one replied on the linked issue :(

**Comment by krk** [comment]
repro +1

**Comment by DickvdBrink** [comment]
Refs https://github.com/dotnet/roslyn/issues/970, so according to that post it should be fixed in a next update :) !

**Comment by sergiy-k** [comment]
Please re-open this issue if you are still having problems building coreclr. Thank you!
