### ISSUE TITLE
Add tests for ICustomMarshaler support

### ISSUE THREAD

**Issue by eerhardt** [dotnet/coreclr#9287]
Download and unzip:
[CustomMarshaler.zip](https://github.com/dotnet/coreclr/files/749101/CustomMarshaler.zip)

1. Install a "2.0" CLI - Here's the one I used https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0.0-alpha-004631/dotnet-dev-win-x64.2.0.0-alpha-004631.zip
2. dotnet restore
3. dotnet run

```
Unhandled Exception: System.Exception: Custom marshaler 'Mono.Unix.Native.FileNameMarshaler' does no
t implement the ICustomMarshaler interface.
   at System.StubHelpers.StubHelpers.CreateCustomMarshalerHelper(IntPtr pMD, Int32 paramToken, IntPt
r hndManagedType)
   at ConsoleApp.Program.rename(String oldpath, String newpath)
   at ConsoleApp.Program.Main(String[] args) in F:\DotNetTest\CustomMarshaler\Program.cs:line 11
```

**Comment by shrah** [comment]
https://github.com/dotnet/corefx/pull/15769 should fix this issue.

**Comment by jkotas** [comment]
We should add a test for this to CoreCLR before closing.

**Comment by yizhang82** [comment]
@shrah Can you look into adding the test?

**Comment by yizhang82** [comment]
Test only. Not blocking 2.0

**Comment by tijoytom** [comment]
@hughbe wrote this test in corefx , but i was decided to move it coreclr, guess it never happened.
https://github.com/dotnet/corefx/pull/17804

**Comment by yizhang82** [comment]
@tijoytom Yep. I remember the reason was that coreclr has better native test support. 
@hughbe Are you planning to give this another try?

**Comment by hughbe** [comment]
Yeah I was, unfortunately my internet at home (I live in cambodia) is too slow to restore nuget packages. Never got round to doing this in a cafe or at work. Will get something out soon!

**Comment by yizhang82** [comment]
@hughbe Awesome. Really appreciate your help making the product better! 
@ericstj Do you have suggestions on how to increase the nuget restore timeout?

**Comment by hughbe** [comment]
The restore timeout for dotnet restore can't be customised unfortunately. I've got decently internet but it varies minute per minute so I can actually download the packages of there was no timeout. No biggie though

**Comment by jkoritzinsky** [comment]
Tests for `ICustomMarshaler` were added in #19195 so we can close this.
