### ISSUE TITLE
.NET Core ILAsm does not correctly sign binaries

### ISSUE THREAD

**Issue by mellinoe** [dotnet/coreclr#9292]
I'm not sure what exactly the root problem is here, but I am seeing some bad / strange behavior when attempting to use the .NET Core version of ilasm from the latest nuget packages. We use the "full framework ILAsm" in our Windows build in corefx in order to build the System.Runtime.CompilerServices.Unsafe library, built from [an IL file](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il). When switching our build targets to use the .NET Core version of ILAsm, we get an error from our signing targets complaining about the assembly produced:

```
"D:\OSS\corefx\src\System.Runtime.CompilerServices.Unsafe\src\System.Runtime.CompilerServices.Unsafe.ilproj" (rebuild target) (1) ->
(OpenSourceSign target) ->
  D:\OSS\corefx\Tools\sign.targets(70,5): error : D:\OSS\corefx\bin/obj/Windows_NT.AnyCPU.Debug/System.Runtime.CompilerServices.Unsafe/netcoreapp/Sys
tem.Runtime.CompilerServices.Unsafe.dll: PE file is not a delay-signed assembly. [D:\OSS\corefx\src\System.Runtime.CompilerServices.Unsafe\src\System
.Runtime.CompilerServices.Unsafe.ilproj]
```

> System.Runtime.CompilerServices.Unsafe.dll: PE file is not a delay-signed assembly

I've used ILDasm (full framework version) to inspect the differences between the Unsafe.dll produced from both ILAsm's (full framework and .NET Core), and there are only two small differences.

[Here is the IL produced from the full framework ILAsm](https://gist.github.com/mellinoe/c3a6c21fd43e143063f86e1069a6347e)

[Here is the IL produced from the .NET Core ILAsm](https://gist.github.com/mellinoe/59ff321e002597b1cc259a86310e8f41)

The obvious difference is the .NET Core version has:
> // Metadata version: v4.0.22220

instead of 
> // Metadata version: v4.0.30319

The .NET Core version also has:
> // Image base: 0x01590000

instead of 
> // Image base: 0x03060000

The MVIDs are different, but that seems normal to me.

Do any of the above differences explain why we would be seeing this error?

**Comment by mellinoe** [comment]
@jkotas @gkhanna79 I'm not sure who is most familiar with this, could you help find the right person?

**Comment by gkhanna79** [comment]
CC @RussKeldorph

**Comment by RussKeldorph** [comment]
@adiaaida Could you find the critical difference?

**Comment by mellinoe** [comment]
@adiaaida Is there anything I can do to help investigate this?

**Comment by adiaaida** [comment]
It looks like we have ifdef'd out the signing functionality in ilasm, which is why you're seeing this error. I'm looking into what we will have to do to get that functionality in ilasm.

**Comment by mellinoe** [comment]
> ifdef'd out the signing functionality

Well, that would do it 😄. Thanks for looking into this.

**Comment by ahsonkhan** [comment]
cc @adiaaida, @mellinoe 
So, do we have a fix?

**Comment by adiaaida** [comment]
We've been talking to various people trying to decide what ilasm will support. We think that we can get it to support delay signing, but we'd like to do this without using legacyactivationshim.h, which is what currently does the signing for full framework. I'm looking into it, but don't currently have more of an update.

**Comment by adiaaida** [comment]
A fix for this has been checked in.

**Comment by mellinoe** [comment]
Thanks for fixing this; much appreciated.
