### ISSUE TITLE
Additional BotR Chapters

### ISSUE THREAD

**Issue by mattwarren** [dotnet/coreclr#9306]
Is it possible for the additional BotR chapters to be made available? 

There are a few additional docs that are [tantalising mentioned in ceemain.cpp](https://github.com/dotnet/coreclr/blob/1d03b8fd8d650bd215623a7b035e68db96697e59/src/vm/ceemain.cpp#L40-L127), only some of which appear to match up with what's already available on GitHub. Although I guess that several don't apply to CoreCLR, 'ClickOnce Activation' for instance?

(issue opened as [suggested by](https://twitter.com/ziki_cz/status/826588632064471040) @karelz)

| Mention in cemain.cpp | Publish BOTR doc | 
|-----------------------|------------------|
| Introduction/BOTR Introduction.docx | [Documentation/botr/botr-faq.md](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/botr-faq.md) |
| JIT/JIT Design.doc | [Documentation/botr/ryujit-overview.md](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/ryujit-overview.md) |
| NGEN/NGENDesign.doc | |
| mscorlib/mscorlibDesign.doc | [Documentation/botr/mscorlib.md](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/mscorlib.md) |
| ManagedEH/Design.doc | |
| CER/CERDesign.doc | |
| AssemblyLoader/AssemblyLoader.doc | |
| AssemblyLoader/FusionDesign.doc | |
| BCL/SystemStringDesign.doc | |
| DiagnosticServices/ProfilingAPIDesign.doc | [Documentation/botr/profiling.md](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/profiling.md) |
| EERemotingSupport/RemotingDesign.doc | |
| MDA/MDADesign.doc | |
| Reflection/ReflectionDesign.doc | |
| RuntimeSecurity/RuntimeSecurityDesign.doc | |
| LoadtimeSecurity/DeclarativeSecurity-Design.doc | |
| LoadtimeSecurity/StrongName.doc | |
| RuntimeSecurity/ClickOnce Activation.doc | |
| RuntimeSecurity/Cryptography.doc | |
| RuntimeSecurity/DemandEvalDesign.doc | |

**Comment by jkotas** [comment]
@richlander and I went over all the Botr documents at the time and get all the good ones published as markdown. The rest is either:
- Not applicable to CoreCLR: ClickOnce, Fusion, Cryptography - it has been 100% refactored and moved to corefx, ...
- Not written very well

**Comment by jkotas** [comment]
Here is an excerpt from the `ManagedEH/Design.doc` that is example of the no written very well one. As you can see, it is better to just look at the code than to read 20 pages like this.

> DefaultCatchHandler starts off by getting the right throwable object either by:
> 1)	Using the one that was passed to it by InternalUnhandledExceptionFilter_Worker, OR
> 2)	Using the LastThrownObject (if asked to get from there), OR
> 3)	Getting one from the managed thread 
>
> If the throwable retrieved is NULL, we exit from the function. Otherwise, we set a flag to indicate if the exception is OOM or not. Next, if the debugger interception is allowed and exception is active, we allow the debugger to initiate unwind and handle the exception. 
> If the debugger is not invoked, we will conditionally invoke the notification to AppDomain’s unhandled exception handlers about the unhandled managed exception. Since this call to DefaultCatchHandler was made from InternalUnhandledExceptionFilter_Worker which had already sent the notifications, they are not sent in this code execution path.

**Comment by jkotas** [comment]
I think the fix for this should be to update the comment in ceemain.cpp to refer to the docs published on github only.

**Comment by mattwarren** [comment]
> @richlander and I went over all the Botr documents at the time and get all the good ones published as markdown. The rest is either:

Ah shame, I was looking forward to reading 'SystemStringDesign.doc', it would've helped me when I wrote [Strings and the CLR - a Special Relationship](http://mattwarren.org/2016/05/31/Strings-and-the-CLR-a-Special-Relationship/). But I completely agree with your reasoning, it's not worth publishing docs that don't help anyone!

> I think the fix for this should be to update the comment in ceemain.cpp to refer to the docs published on github only.

Makes sense, is my table (above) correct or have I missed some links out?
