### ISSUE TITLE
Additional terms for the Glossary?

### ISSUE THREAD

**Issue by mattwarren** [dotnet/coreclr#9309]
Here's 2 more terms I've come across that I don't really understand:

- [Zap](https://github.com/dotnet/coreclr/tree/master/src/zap), I assume it's short for 'zapping' but I still don't get it, is it linked to NGen?
- [BBT](https://github.com/dotnet/coreclr/blob/53e62b4e3ca7792b1c4966823832de56f88db0b6/src/vm/ceemain.cpp#L653-L654)

Are they worth adding? 

Also there are some others listed in [this old issue](https://github.com/dotnet/coreclr/issues/6181) that were never added, maybe some of them are worth including? At 2nd glance, several of them seem to be the names of the folders under [/src/](https://github.com/dotnet/coreclr/tree/master/src) so I don't know if they all warrant explanation?

/cc @karelz

**Comment by jkotas** [comment]
ZAP = original codename for NGen

BBT = Microsoft internal early version of C/C++ PGO. See https://www.microsoft.com/windows/cse/bit_projects.mspx.

**Comment by karelz** [comment]
[Glossary](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/glossary.md) updated with the above info (+PGO, POGO added) see https://github.com/dotnet/coreclr/commit/f0e57dc218055f65e678e78a286fff6976758a55.

**Comment by karelz** [comment]
@mattwarren which of the "old" ones would you like to add?

**Comment by mattwarren** [comment]
Maybe just the following 2:

- MD (Metadata?)
- IPC/IPCMan (Inter-process communication?)

**Comment by mattwarren** [comment]
@jkotas thanks for the info, it's always good to learn new things!

**Comment by hmemcpy** [comment]
What about Dkm? I heard it was the initials of those who worked on the managed debugger API.

**Comment by karelz** [comment]
MD & IPC added: https://github.com/dotnet/coreclr/commit/d00235f94acb7a03d6b8a37604c1f540430fdd03

I didn't add IPCMan nor Dkm - where doers it show?

**Comment by hmemcpy** [comment]
Dkm is the prefix that is used on most types in the managed debugging API (["Concord"](https://github.com/Microsoft/ConcordExtensibilitySamples/wiki/CLR-Expression-Evaluators), is it?). But I just realized it doesn't really fit with the CLR glossary, so nevermind  :)

**Comment by mattwarren** [comment]
ipcman is just the folder name under i,e. [src/ipcman](https://github.com/dotnet/coreclr/tree/master/src/ipcman), so yeah I agree just using ipc is better

**Comment by mattwarren** [comment]
oh, was my educated guess for 'MD' correct, that was lucky!

(I just had a quick look at the code under [/src/md/](https://github.com/dotnet/coreclr/tree/master/src/md))

**Comment by karelz** [comment]
Yep, MD directory is MetaData (I was "happy owner" of that code for quite a few years :))

**Comment by karelz** [comment]
Can we close the issue or do you guys have more terms you would like to add now?

**Comment by mattwarren** [comment]
I don't have any other terms to add at this time

**Comment by karelz** [comment]
Thanks! If you find more things you want us to add, please file new issue(s) and tag me ;-)
