### ISSUE TITLE
Re-enable JIT BenchmarksGame tests in Helix

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#9314]
Once CoreCLR perf testing moves to a Core-based solution (instead of Desktop), and moves from netstandard1.4 to netcoreapp, we can re-enable the regexdna, revcomp, and k-nucleotides tests in Helix.

**Comment by wtgodbe** [comment]
To do so, simply undo the following change: https://github.com/dotnet/coreclr/pull/9315/files#diff-b0896e19988c929c03c28da41dd827beR408

**Comment by danmosemsft** [comment]
@valenis @DrewScoggins @wtgodbe is still still in the 2.0 plans? If not please move to Fture.

**Comment by danmosemsft** [comment]
@valenis @DrewScoggins @wtgodbe is still still in the 2.0 plans? If not please move to Fture.

**Comment by DrewScoggins** [comment]
We can push this out to future.  We still have this test running in the perf lab and we have setup runs that execute all of our performance tests per PR to check for correctness so we do not need this for 2.0
