### ISSUE TITLE
Remove CAS from CoreLib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#9321]
There is lots of CAS-only code -- CodeAccessPermission and related types and code that uses them. Ideally it would all be removed. I'm guessing one thing to take care of is making sure we continue to do the same parameter validation/throw the same exceptions. That has been a gotcha for IO in the past.

Removing remaining FEATURE_CAS_POLICY on the native side is already tracked by https://github.com/dotnet/coreclr/issues/9067

**Comment by danmosemsft** [comment]
I'm already deleting most of the CAS types/members that aren't actually referenced. (There are a few that are rooted by model.xml that I'm not)

**Comment by benaadams** [comment]
Dotnet just keeps getting better and better 😄

**Comment by danmosemsft** [comment]
I want to be clear this concerns removing the implementations in corelib. We brought back (mostly dummy) CAS types in CoreFX to make existing code work, and those are staying.

**Comment by jkotas** [comment]
I am working on round of cleanup for this: https://github.com/jkotas/coreclr/tree/security-cleanup3

**Comment by benaadams** [comment]
@danmosemsft I know; it just means Execution context etc are definitely staying slim 😄

**Comment by jkotas** [comment]
The work remaining here is to cleanup references to types in https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/CleanupToDoList.cs and delete this file.

**Comment by danmosemsft** [comment]
The last ones involve some sigificant changes in AppDomain that I'm reluctant to do without spending the time to properly understand the code to be confident what is really dead.
