### ISSUE TITLE
Provide a way to override the logic of retrieving the preamble bytes in StreamWriter

### ISSUE THREAD

**Issue by kichalla** [dotnet/coreclr#933]
In ASP.NET MVC, we use StreamWriter in some places to write data to the response stream. We want to avoid writing the BOM or preamble bytes irrespective of whether an encoding requires preamble or not.

I was initially looking to subclass StreamWriter and override some method like `GetPreamble` to prevent writing the preamble bytes, but couldn't find any.

(I initially had a wrapper around the supplied encoding to prevent preamble bytes...even though this works, it feels hacky)

For reference:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/StreamWriter.cs#L283

**Comment by bpschoch** [comment]
some say you can do it via the New UTF8Encoding(false) http://stackoverflow.com/questions/5266069/streamwriter-and-utf-8-byte-order-marks/11655096#11655096

I started an issue on corefx: https://github.com/dotnet/corefx/issues/1645

**Comment by kichalla** [comment]
Sure, I am aware of it...the thing is this encoding is provided by an end user and they might provide with a BOM encoding or not...

**Comment by bpschoch** [comment]
I made a general proposal on a possible solution here: https://github.com/dotnet/corefx/issues/1645
I'm trying to understand what you are looking for.  Your issue appears that you get handed an encoding and using that encoding, prevent any BOM from being generated.

Would that proposal solve your issue?

**Comment by kichalla** [comment]
yes, that's right....we want to prevent writing out the BOM in all cases...sure, that proposal would work for me...thanks..

**Comment by svick** [comment]
@kichalla That sounds to me like an edge case that doesn't need to be supported directly by the framework. Any reason why you can't use something like the following code?

```c#
if (encoding is UTF8Encoding)
    encoding = new UTF8Ending(false);
else if (encoding is UnicodeEncoding)
    encoding = new UnicodeEncoding(false, false);
```

**Comment by jbevain** [comment]
Agreed with @svick.

I'd solve it in a generic way using:

```csharp
	class WithoutPreambleEncoding : Encoding
	{
		private readonly Encoding _encoding;

		public WithoutPreambleEncoding(Encoding encoding)
		{
			_encoding = encoding;
		}

		public override byte[] GetPreamble()
		{
			return new byte[0];
		}

		public override int GetByteCount(char[] chars, int index, int count)
		{
			return _encoding.GetByteCount(chars, index, count);
		}

		public override int GetBytes(char[] chars, int charIndex, int charCount, byte[] bytes, int byteIndex)
		{
			return _encoding.GetBytes(chars, charIndex, charCount, bytes, byteIndex);
		}

		// ...
}
```

**Comment by kichalla** [comment]
@svick @jbevain : I actually had the same encoding wrapper like what you mentioned to solve for all encodings...but this felt hacky and so just wanted to check...

**Comment by joshfree** [comment]
@JeremyKuhne can you move this to /dotnet/corefx please

**Comment by karelz** [comment]
@ianhays @JeremyKuhne please move it to corefx repo. API additions should not be tracked in coreclr.

**Comment by ianhays** [comment]
Issue moved to [dotnet/corefx #17242](https://github.com/dotnet/corefx/issues/17242) via [**ZenHub**](https://www.zenhub.com/)
