### ISSUE TITLE
What's the meaning of local GC?

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#9332]
I've found the Local GC project under CoreCLR repo, but what does it mean? I can't find any document to describe it.

**Comment by jkotas** [comment]
The Local GC project description says it all: "Local GC" effort, which is aiming to decouple the GC from the rest of the runtime. Here is a bit longer description from @Maoni0: https://github.com/dotnet/coreclr/projectshttps://github.com/dotnet/coreclr/pull/8199#issuecomment-262669283
