### ISSUE TITLE
HelloMvc does not work on CoreCLR DNX

### ISSUE THREAD

**Issue by richlander** [dotnet/coreclr#934]
- ConsoleApp and HelloWeb work.
- HelloMvc does not.
- Build: 1.0.0-beta5-11706
- Repro: OS X

https://github.com/aspnet/Home/tree/dev/samples/latest

![screen shot 2015-05-05 at 8 04 31 pm](https://cloud.githubusercontent.com/assets/2608468/7486928/856bc198-f362-11e4-98da-cfd9a3544606.png)

Related to #841?

**Comment by richlander** [comment]
@davidfowl determined that was caused by a packaging problem.

@janvorli It would be good to improve on the error messages.

**Comment by ellismg** [comment]
The better error message work is tracked by #678.  Is there anything left to do on this issue?

**Comment by richlander** [comment]
@ellismg Nothing for CoreCLR, AFAIK. I think it's still important to track since it is a scenario issue. That's arguable, however. If you feel strongly, I can 'move' this issue to the aspnet/home repo.

Still repros with dnx-coreclr-darwin-x64.1.0.0-beta5-11722.

**Comment by ellismg** [comment]
I think it should go somewhere under aspnet, if there's nothing actionable from the CoreCLR side of things.

**Comment by richlander** [comment]
Works on dnx-coreclr-darwin-x64.1.0.0-beta5-11735.

/cc @davidfowl
