### ISSUE TITLE
Inlining and implicit tail calls

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#9349]
Recognition of implicit tail calls (calls in tail position w/o the `tail` prefix) is disabled in when importing inlinee IL. So for example in the program below the generated code for `A` contains a normal call to `C`.
```C#
    // Needs to be big enough that we won't inline into caller
    // w/o using the noinline attribute
    static bool C(int x)
    {
        int result = 0;
        for (int i = 0; i < 25; i++)
        {
            result++;
        }
        for (int i = 0; i < 25; i++)
        {
            result++;
        }
        return x == result;
    }

    // Want this to inline
    static bool B(int x)
    {
        return C(x);
    }

    // Needs to be big enough that we won't inline into caller
    // w/o using the noinline attribute
    static bool A()
    {
        int result = 0;
        for (int i = 0; i < 25; i++)
        {
            result++;
        }
        for (int i = 0; i < 25; i++)
        {
            result++;
        }
        return B(result);
    }
```
Such cases arise fairly frequently in real code, for instance in overload delegation chains.

It should be ok to flag calls as implicit tail calls within the inlinee, if the inline call site is itself an implicit tail call. Some care may be required to make sure that the jit correctly models recursion, since recursive tail calls are convert into within-method jumps. If `A` contains implicit tail calls to itself, `B`, and `C`, we should make sure those are properly converted to jumps or left as calls.

Note the jit won't inline at explicit tail call sites, instead favoring the explicit tail call.

**Comment by AndyAyersMS** [comment]
Have a prototype over on my fork: https://github.com/AndyAyersMS/coreclr/tree/InlineImplicitTailCalls

It seems to work well enough, with one exception: if for some reason `A` ends up getting marked as never inline (as might happen say during crossgen if `A` looks like a univerally unprofitable inline) then the call from `A` to `B` is not considered an implicit tail call, and so (once `B` is inlined) the pass through implicit tail to the call to `C` doesn't happen.

Now because of `A`'s no-inline status even if we did pass the implicit tail context down, the jit would not generate a tail call for `C`.

Hence, another motivation for addressing #6095.

**Comment by AndyAyersMS** [comment]
Note there is an R2R blocker for tail calls, see `ZapInfo::canTailCall`. So running diffs via the default jit-diff only shows hits in System.Private.Corelib.dll.

**Comment by benaadams** [comment]
Are `void`s calls considered for tail call inlining? (When called from a void method in tail position)

**Comment by AndyAyersMS** [comment]
They should be, yes. 

I believe the jit will even consider some cases where the caller returns void but the callee doesn't, like
```C#
int Bar() { ... }
void Foo() { Bar(); }
```

If you are looking at specific instances and wondering why they're not converting to tail calls be aware there are various reasons for leaving things as normal calls. Unfortunately the diagnostics for tail calls are not as easy to get at as they are for inlining. You have to dig through the jit dump and sometimes debug through the jit interface to get at root causes.

It might be a worthwhile project someday to consolidate all the decisions made around calls into something like the current inline tree.
