### ISSUE TITLE
AssemblyLoadContext.LoadUnmanagedDll needs to use OS .dll handles on Unix

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#935]
The current implementation of AssemblyLoadContext.LoadUnmanagedDll assumes PAL .dlls handles on Unix. Instead, it needs to use OS .dlls handles instead (e.g. handles returned from dlopen).

**Comment by jkotas** [comment]
Related to discussion #930

**Comment by kouvel** [comment]
I'm taking a look at this
