### ISSUE TITLE
src\mscorlib\mscorlib.shared.sources.props is messed up in git

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#9353]
Repro (on Windows):

```
git clone https://github.com/dotnet/coreclr
cd coreclr\src\mscorlib
touch mscorlib.shared.sources.props (or open in notepad and save it without changing anything)
git checkout -- *
git status
```

Actual result:
`git status` reports mscorlib.shared.sources.props as modified, but there is no actual diff. It is impossible to get to clean state with nothing checked out.

Expected result:
`git status` reports nothing modified

**Comment by jkotas** [comment]
@danmosemsft It has something to do with changing the file to binary that was part of your change. I am not able to tell what you have done exactly to change it ... could you please take a look?

**Comment by danmosemsft** [comment]
I cannot repro this (on a clean clone)

Maybe time to copy and paste the content into a fresh file named "system.private.corelib.sources.props" (or right into the project itself) ..?

**Comment by jkotas** [comment]
Agree ... I will do it.

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/9355
