### ISSUE TITLE
Add AssemblyLoadContext.LoadUnmanagedDllFromPath helper API

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#937]
Simple overrides of LoadUnmanagedDll that just wish to provide alternative paths need to deal with platform differences for no good reason today. Add a helper API to AssemblyLoadContext to fix it:

    protected IntPtr LoadUnmanagedDllFromPath(String unmanagedDllPath)

**Comment by jkotas** [comment]
Note that the advanced uses that wish to pass custom flags to LoadLibrary on Windows, or dlopen on Unix will still need to have platform-specific code.

**Comment by kouvel** [comment]
I'm taking a look at this

**Comment by kouvel** [comment]
API review: https://github.com/dotnet/corefx/issues/3054

**Comment by tzwlai** [comment]
Closing this since it has been addressed.

CC @kouvel
