### ISSUE TITLE
Better alternatives to MSIL and JIT?

### ISSUE THREAD

**Issue by simonegli8** [dotnet/coreclr#938]
I don't know how old MSIL is, but aren't there better alternatives to it, like compressed syntax trees? Has Microsoft done any research on it? And as for JIT, has your team tried trace tree compilation? 
 I'd suggest you connect with Michael Franz from UIC Irvine, he pioneered a compressed syntax tree compiler two years before Java came up, and has done a lot of research also on trace tree compilation. I think the Mozilla Javasript engine is from him.

From one of his (old) abstracts:
 Trace-based compilation is a technique used in managed language runtimes to detect and compile frequently executed program paths. The goal is to reduce compilation time and improve code quality by only considering "hot" parts of methods for compilation. Trace compilation is well suited for interpreter-based execution environments because the control flow of an application program is highly visible and recordable. In this paper, we show that trace compilation is also feasible and beneficial in runtime environments without interpreters where it is more difficult to monitor the control flow of an application.

We present the implementation of Maxpath, a trace-based Java just-in-time compiler for the meta-circular Maxine virtual machine. Maxine uses a tiered compilation strategy where methods are first compiled with a non-optimizing just-in-time compiler in order to collect profiling information, and then recompiled with an optimizing compiler for long-term efficient execution. We record traces by dynamically inserting instrumentation code in non-optimized methods. Execution traces are first collected into trace regions, after which they are compiled, optimized and linked to non-optimized methods for efficient execution. We show that trace-based compilation is an effective way to focus scarce compilation resources on performance critical application regions.

His website is here:
www.michaelfranz.com

PS:
 If you want to be the best programmer you can be, pray for wisdom ;-) I once solved a 3 days debugging session in just 10 minutes finding about 5 errors this way. You'll also have much better ideas. Just give it a try :-)

**Comment by sharwell** [comment]
As a bit of background, MSIL is now called CIL, and is defined in the standard ECMA-335. CIL is very important in its current form because many compilers for many *very* different programming languages use it as a common intermediate language for compiled applications and libraries.

**Comment by xied75** [comment]
This Franz guy recently got a **PATENT** on that piece of magic; in the name of Open Source, shall we consider this issue can be closed now?

**Comment by BruceForstall** [comment]
There are many, many ways to implement a JIT compiler. The RyuJIT compiler that you see in the coreclr repo is an evolution of many years of work, with many constraints and specific design goals. Are there different and potentially better implementation strategies? Yes. (See the LLILC project, for example.) Now that .NET Core is open, researchers / contributors are free to try new strategies and replace RyuJIT entirely, at least in their own forks.

**Comment by richlander** [comment]
I think that we can safely close this issue. The general idea is interesting, but unless there is a concrete proposal on how to move forward with the idea, I'm not seeing this moving forward.

I'll close this in a couple days if I don't hear anything suggesting otherwise.

**Comment by simonegli8** [comment]
As I don't work with Microsoft, and have no influence on Mr. Franz at all, I think, as you're from Microsoft, you could at least contact him, and tell him, you'd be interested if he could start some research for the .NETCore CLR. Thats all we can do for now I think. I myself am not working as a programmer anymore to implement such stuff.

**Comment by simonegli8** [comment]
His Email is franz@uci.edu

**Comment by RussKeldorph** [comment]
Not likely to make progress on this in the foreseeable future.  Better to close for now.
