### ISSUE TITLE
Use a more conventional CMake build

### ISSUE THREAD

**Issue by copumpkin** [dotnet/coreclr#94]
I love that you're using standard tools, but was a little surprised at how you were using cmake in the linux build.

As far as I can tell, the usual practice is to make a build directory, then call cmake on the source directory from that build directory, and then call make to actually build the code. Is there a reason CoreCLR doesn't do that? If I try, I get a "not implemented" error (I can paste it if it helps, but it just seems like unsupported behavior). I'm mostly asking because I'm trying to fit it into a larger project and it's a lot easier if projects follow standard patterns.

Thanks!

**Comment by ellismg** [comment]
I assume you mean doing this instead of running build.sh?

You should be able to do what you want.  Assuming your build directory is in ~/builds/linux-debug-build and the repository is checked out to ~/git/coreclr:

```
$ cd ~/builds/linux-debug-build
$ ~/git/coreclr/src/pal/tools/gen-buildsys-clang.sh ~/git/coreclr
$ make
```

I just tried the above and it works.  Maybe I am misunderstanding what you are asking for, since I'm very much a CMake newbie.

**Comment by mathstuf** [comment]
@copumpkin That error comes from it not detecting that your system is [64-bit](https://github.com/dotnet/coreclr/blob/master/CMakeLists.txt#L319).

**Comment by copumpkin** [comment]
Hi, thanks for the responses. I can't get you more details right now but will do so tomorrow, sorry!

**Comment by kangaroo** [comment]
@copumpkin Is this still an issue for you?

**Comment by copumpkin** [comment]
Hi, sorry, haven't had a chance to look at it again. Can you give me until the end of the week to catch up and post more details (or close it)?

Also, @kangaroo, I think we spoke on IRC quite a few years ago! Hi!

**Comment by kangaroo** [comment]
Hi @copumpkin -- yep, we've discussed a few different things over the years ;)

**Comment by kangaroo** [comment]
@copumpkin ping :+1:

**Comment by copumpkin** [comment]
I think it's okay from preliminary tests, but when I get an environment set up again I'll try again and reopen if I encounter problems. Sorry for the noise/lack of responsiveness!
