### ISSUE TITLE
FreeBSD lldb script build issues on fresh FreeBSD 10.1 box

### ISSUE THREAD

**Issue by tony** [dotnet/coreclr#940]
This is on a fresh 10.1 install, without any other configuration settings (``/etc/make.conf`` / ``/etc/src.conf``).

Currently looking at:
- 10.1 has clang/llvm 3.4 in system out of the box. Even after packages for a newer llvm/clang, using the script may still find 3.4 somehow?
- checking out repos at a release tag 
- Check passing in arguments into the cmake for building to

(in the future, detect version by looking for CC/CXX/CPP? Installed clang's in PATH?) At this point, if we're looking up where / which libraries are on a system, we may want to investigate a cmake solution.

```bash
$ uname -a
FreeBSD z600 10.1-STABLE FreeBSD 10.1-STABLE #0: Wed May  6 05:34:04 CDT 2015     root@z600:/usr/obj/usr/src/sys/GENERIC  amd64
```

```bash

#!/bin/sh
# LLDB installation script for FreeBSD 10.1 STABLE
# LLDB is yet not available in FreeBSD ports/packages, so we have to fetch 
# it from the LLVM source tree and build it ouselves. 
# Prerequisite packages, which must be installed prior to running this script:
# git python cmake ninja swig13
# 
# You can intall the tools by running (as root):
# pkg install git python cmake ninja swig13
# 

GIT=/usr/local/bin/git
CMAKE=/usr/local/bin/cmake
NINJA=/usr/local/bin/ninja
PYTHON_PATH=/usr/local/include/python2.7

$GIT clone http://llvm.org/git/llvm.git
cd llvm/tools
$GIT clone http://llvm.org/git/clang.git
$GIT clone http://llvm.org/git/lldb.git

cd ..
mkdir build
cd build

$CMAKE ../ -G Ninja -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++ -I$PYTHON_PATH -g"
$NINJA lldb
#$NINJA check-lldb # if you want to run tests

su <<EOSU
$NINJA lldb install
EOSU
```

Output: https://gist.github.com/tony/e8bb15cddc7cae43c9d1

Related: https://github.com/dotnet/coreclr/pull/894 (this is ok to merge)

Going to swing back to this. The script is working fine on another box.

**Comment by tony** [comment]
(I tried rebuilding world with ``/etc/make.conf`` with the latest clang, if only that'd work. Frankly you can't rely on doing that even in CURRENT :smile: )

I updated the ``$CMAKE`` line to:

```shell

$CMAKE ../ -G Ninja -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++ -I$PYTHON_PATH -g" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/local/bin/clang36 -DCMAKE_CXX_COMPILER=/usr/local/bin/clang++36
```

As well as checked out llvm, clang and lldb at ``release_36``.

Getting stuck here:

```console

[135/139] Linking CXX executable bin/lldb-gdbserver-3.6.1
FAILED: : && /usr/local/bin/clang++36   -std=c++11 -stdlib=libc++ -I/usr/local/include/python2.7 -g -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -std=c++11 -fcolor-diagnostics -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-deprecated-register  -fno-exceptions -fno-rtti -g  -Wl,-z,origin -Wl,-allow-shlib-undefined    -Wl,-O3 -Wl,--gc-sections tools/lldb/tools/lldb-gdbserver/CMakeFiles/lldb-gdbserver.dir/lldb-gdbserver.cpp.o tools/lldb/tools/lldb-gdbserver/CMakeFiles/lldb-gdbserver.dir/__/__/source/lldb-log.cpp.o tools/lldb/tools/lldb-gdbserver/CMakeFiles/lldb-gdbserver.dir/__/__/source/lldb.cpp.o  -o bin/lldb-gdbserver-3.6.1 -L/usr/local/lib lib/libLLVMAArch64CodeGen.a lib/libLLVMAArch64AsmPrinter.a lib/libLLVMAArch64AsmParser.a lib/libLLVMAArch64Desc.a lib/libLLVMAArch64Info.a lib/libLLVMAArch64Disassembler.a lib/libLLVMARMCodeGen.a lib/libLLVMARMAsmPrinter.a lib/libLLVMARMAsmParser.a lib/libLLVMARMDesc.a lib/libLLVMARMInfo.a lib/libLLVMARMDisassembler.a lib/libLLVMCppBackendCodeGen.a lib/libLLVMCppBackendInfo.a lib/libLLVMHexagonCodeGen.a lib/libLLVMHexagonDesc.a lib/libLLVMHexagonInfo.a lib/libLLVMHexagonDisassembler.a lib/libLLVMMipsCodeGen.a lib/libLLVMMipsAsmPrinter.a lib/libLLVMMipsAsmParser.a lib/libLLVMMipsDesc.a lib/libLLVMMipsInfo.a lib/libLLVMMipsDisassembler.a lib/libLLVMMSP430CodeGen.a lib/libLLVMMSP430AsmPrinter.a lib/libLLVMMSP430Desc.a lib/libLLVMMSP430Info.a lib/libLLVMNVPTXCodeGen.a lib/libLLVMNVPTXAsmPrinter.a lib/libLLVMNVPTXDesc.a lib/libLLVMNVPTXInfo.a lib/libLLVMPowerPCCodeGen.a lib/libLLVMPowerPCAsmPrinter.a lib/libLLVMPowerPCAsmParser.a lib/libLLVMPowerPCDesc.a lib/libLLVMPowerPCInfo.a lib/libLLVMPowerPCDisassembler.a lib/libLLVMR600CodeGen.a lib/libLLVMR600AsmPrinter.a lib/libLLVMR600AsmParser.a lib/libLLVMR600Desc.a lib/libLLVMR600Info.a lib/libLLVMSparcCodeGen.a lib/libLLVMSparcAsmPrinter.a lib/libLLVMSparcAsmParser.a lib/libLLVMSparcDesc.a lib/libLLVMSparcInfo.a lib/libLLVMSparcDisassembler.a lib/libLLVMSystemZCodeGen.a lib/libLLVMSystemZAsmPrinter.a lib/libLLVMSystemZAsmParser.a lib/libLLVMSystemZDesc.a lib/libLLVMSystemZInfo.a lib/libLLVMSystemZDisassembler.a lib/libLLVMX86CodeGen.a lib/libLLVMX86AsmPrinter.a lib/libLLVMX86AsmParser.a lib/libLLVMX86Desc.a lib/libLLVMX86Info.a lib/libLLVMX86Disassembler.a lib/libLLVMXCoreCodeGen.a lib/libLLVMXCoreAsmPrinter.a lib/libLLVMXCoreDesc.a lib/libLLVMXCoreInfo.a lib/libLLVMXCoreDisassembler.a lib/libLLVMInterpreter.a lib/libLLVMAsmParser.a lib/libLLVMBitReader.a lib/libLLVMBitWriter.a lib/libLLVMCodeGen.a lib/libLLVMipo.a lib/libLLVMSelectionDAG.a lib/libLLVMBitReader.a lib/libLLVMMC.a lib/libLLVMMCJIT.a lib/libLLVMCore.a lib/libLLVMMCDisassembler.a lib/libLLVMExecutionEngine.a lib/libLLVMOption.a -Wl,--start-group lib/liblldbBreakpoint.a lib/liblldbCommands.a lib/liblldbDataFormatters.a lib/liblldbHost.a lib/liblldbCore.a lib/liblldbExpression.a lib/liblldbInterpreter.a lib/liblldbSymbol.a lib/liblldbTarget.a lib/liblldbUtility.a lib/liblldbPluginDisassemblerLLVM.a lib/liblldbPluginSymbolFileDWARF.a lib/liblldbPluginSymbolFileSymtab.a lib/liblldbPluginDynamicLoaderStatic.a lib/liblldbPluginDynamicLoaderPosixDYLD.a lib/liblldbPluginDynamicLoaderHexagonDYLD.a lib/liblldbPluginObjectFileMachO.a lib/liblldbPluginObjectFileELF.a lib/liblldbPluginObjectFileJIT.a lib/liblldbPluginSymbolVendorELF.a lib/liblldbPluginObjectContainerBSDArchive.a lib/liblldbPluginObjectContainerMachOArchive.a lib/liblldbPluginProcessGDBRemote.a lib/liblldbPluginProcessMachCore.a lib/liblldbPluginProcessUtility.a lib/liblldbPluginPlatformGDB.a lib/liblldbPluginPlatformFreeBSD.a lib/liblldbPluginPlatformKalimba.a lib/liblldbPluginPlatformLinux.a lib/liblldbPluginPlatformPOSIX.a lib/liblldbPluginPlatformWindows.a lib/liblldbPluginObjectFileMachO.a lib/liblldbPluginObjectContainerMachOArchive.a lib/liblldbPluginObjectContainerBSDArchive.a lib/liblldbPluginPlatformMacOSX.a lib/liblldbPluginDynamicLoaderMacOSXDYLD.a lib/liblldbPluginUnwindAssemblyInstEmulation.a lib/liblldbPluginUnwindAssemblyX86.a lib/liblldbPluginAppleObjCRuntime.a lib/liblldbPluginCXXItaniumABI.a lib/liblldbPluginABIMacOSX_arm.a lib/liblldbPluginABIMacOSX_arm64.a lib/liblldbPluginABIMacOSX_i386.a lib/liblldbPluginABISysV_x86_64.a lib/liblldbPluginABISysV_hexagon.a lib/liblldbPluginABISysV_ppc.a lib/liblldbPluginABISysV_ppc64.a lib/liblldbPluginInstructionARM.a lib/liblldbPluginInstructionARM64.a lib/liblldbPluginObjectFilePECOFF.a lib/liblldbPluginOSPython.a lib/liblldbPluginMemoryHistoryASan.a lib/liblldbPluginInstrumentationRuntimeAddressSanitizer.a lib/liblldbAPI.a lib/liblldbPluginProcessFreeBSD.a lib/liblldbPluginProcessPOSIX.a lib/liblldbPluginProcessElfCore.a lib/liblldbPluginJITLoaderGDB.a -Wl,--end-group lib/libclangAnalysis.a lib/libclangAST.a lib/libclangBasic.a lib/libclangCodeGen.a lib/libclangDriver.a lib/libclangEdit.a lib/libclangFrontend.a lib/libclangLex.a lib/libclangParse.a lib/libclangRewrite.a lib/libclangRewriteFrontend.a lib/libclangSema.a lib/libclangSerialization.a lib/libLLVMAArch64CodeGen.a lib/libLLVMAArch64AsmPrinter.a lib/libLLVMAArch64AsmParser.a lib/libLLVMAArch64Desc.a lib/libLLVMAArch64Info.a lib/libLLVMAArch64Disassembler.a lib/libLLVMARMCodeGen.a lib/libLLVMARMAsmPrinter.a lib/libLLVMARMAsmParser.a lib/libLLVMARMDesc.a lib/libLLVMARMInfo.a lib/libLLVMARMDisassembler.a lib/libLLVMCppBackendCodeGen.a lib/libLLVMCppBackendInfo.a lib/libLLVMHexagonCodeGen.a lib/libLLVMHexagonDesc.a lib/libLLVMHexagonInfo.a lib/libLLVMHexagonDisassembler.a lib/libLLVMMipsCodeGen.a lib/libLLVMMipsAsmPrinter.a lib/libLLVMMipsAsmParser.a lib/libLLVMMipsDesc.a lib/libLLVMMipsInfo.a lib/libLLVMMipsDisassembler.a lib/libLLVMMSP430CodeGen.a lib/libLLVMMSP430AsmPrinter.a lib/libLLVMMSP430Desc.a lib/libLLVMMSP430Info.a lib/libLLVMNVPTXCodeGen.a lib/libLLVMNVPTXAsmPrinter.a lib/libLLVMNVPTXDesc.a lib/libLLVMNVPTXInfo.a lib/libLLVMPowerPCCodeGen.a lib/libLLVMPowerPCAsmPrinter.a lib/libLLVMPowerPCAsmParser.a lib/libLLVMPowerPCDesc.a lib/libLLVMPowerPCInfo.a lib/libLLVMPowerPCDisassembler.a lib/libLLVMR600CodeGen.a lib/libLLVMR600AsmPrinter.a lib/libLLVMR600AsmParser.a lib/libLLVMR600Desc.a lib/libLLVMR600Info.a lib/libLLVMSparcCodeGen.a lib/libLLVMSparcAsmPrinter.a lib/libLLVMSparcAsmParser.a lib/libLLVMSparcDesc.a lib/libLLVMSparcInfo.a lib/libLLVMSparcDisassembler.a lib/libLLVMSystemZCodeGen.a lib/libLLVMSystemZAsmPrinter.a lib/libLLVMSystemZAsmParser.a lib/libLLVMSystemZDesc.a lib/libLLVMSystemZInfo.a lib/libLLVMSystemZDisassembler.a lib/libLLVMX86CodeGen.a lib/libLLVMX86AsmPrinter.a lib/libLLVMX86AsmParser.a lib/libLLVMX86Desc.a lib/libLLVMX86Info.a lib/libLLVMX86Disassembler.a lib/libLLVMXCoreCodeGen.a lib/libLLVMXCoreAsmPrinter.a lib/libLLVMXCoreDesc.a lib/libLLVMXCoreInfo.a lib/libLLVMXCoreDisassembler.a lib/libLLVMInterpreter.a lib/libLLVMAsmParser.a lib/libLLVMBitReader.a lib/libLLVMBitWriter.a lib/libLLVMCodeGen.a lib/libLLVMipo.a lib/libLLVMSelectionDAG.a lib/libLLVMBitReader.a lib/libLLVMMC.a lib/libLLVMMCJIT.a lib/libLLVMCore.a lib/libLLVMMCDisassembler.a lib/libLLVMExecutionEngine.a lib/libLLVMOption.a -ledit -lpanel -lncurses -lexecinfo /usr/local/lib/libpython2.7.so lib/libLLVMAArch64AsmPrinter.a lib/libLLVMAArch64Info.a lib/libLLVMAArch64Utils.a lib/libLLVMARMDesc.a lib/libLLVMARMAsmPrinter.a lib/libLLVMARMInfo.a lib/libLLVMHexagonDesc.a lib/libLLVMHexagonInfo.a lib/libLLVMMipsAsmPrinter.a lib/libLLVMMipsInfo.a lib/libLLVMMSP430AsmPrinter.a lib/libLLVMNVPTXAsmPrinter.a lib/libLLVMPowerPCAsmPrinter.a lib/libLLVMPowerPCInfo.a lib/libLLVMR600AsmPrinter.a lib/libLLVMSparcAsmPrinter.a lib/libLLVMSparcInfo.a lib/libLLVMSystemZDesc.a lib/libLLVMSystemZAsmPrinter.a lib/libLLVMSystemZInfo.a lib/libLLVMX86CodeGen.a lib/libLLVMX86Desc.a lib/libLLVMX86AsmPrinter.a lib/libLLVMX86Utils.a lib/libLLVMX86Info.a lib/libLLVMXCoreAsmPrinter.a lib/libLLVMSelectionDAG.a lib/libLLVMAsmPrinter.a lib/libLLVMXCoreInfo.a lib/libLLVMMCDisassembler.a lib/libLLVMCodeGen.a lib/libLLVMRuntimeDyld.a lib/libLLVMVectorize.a lib/libLLVMScalarOpts.a lib/libLLVMInstCombine.a lib/libLLVMIRReader.a lib/libLLVMAsmParser.a lib/libLLVMInstrumentation.a lib/libLLVMLinker.a lib/libLLVMObjCARCOpts.a lib/libLLVMTransformUtils.a lib/libLLVMipa.a lib/libLLVMAnalysis.a lib/libLLVMTarget.a lib/libLLVMProfileData.a lib/libLLVMObject.a lib/libclangFrontend.a lib/libclangDriver.a lib/libLLVMOption.a lib/libclangParse.a lib/libLLVMMCParser.a lib/libclangSerialization.a lib/libLLVMBitReader.a lib/libclangSema.a lib/libclangAnalysis.a lib/libclangEdit.a lib/libclangAST.a lib/libclangRewrite.a lib/libclangLex.a lib/libclangBasic.a lib/libLLVMMC.a lib/libLLVMCore.a lib/libLLVMSupport.a -lrt -ltinfo -lpthread -lz -lm -Wl,-rpath,"\$ORIGIN/../lib" && :
lib/liblldbPluginProcessGDBRemote.a(GDBRemoteCommunication.cpp.o): In function `GDBRemoteCommunication::StartDebugserverProcess(char const*, unsigned short, lldb_private::ProcessLaunchInfo&, unsigned short&)':
/home/tony/study/dotnet/coreclr/llvm/tools/lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp:790: warning: warning: mktemp() possibly used unsafely; consider using mkstemp()
/usr/bin/ld: warning: libncurses.so.8, needed by /usr/local/lib/libedit.so, may conflict with libncurses.so.5
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)
[135/139] Linking CXX executable bin/clang-3.6
ninja: build stopped: subcommand failed.
```

**Comment by tony** [comment]
lldb builds on freebsd can be on and off: http://lab.llvm.org:8011/builders/lldb-x86_64-freebsd. Especially if we're not checking out at a rev

CURRENT currently is http://lists.cs.uiuc.edu/pipermail/lldb-commits/Week-of-Mon-20150112/014855.html.

Git ref: 2b588ecdbb6fee1f1c22a792a64455677f38575b
URL: https://github.com/llvm-mirror/lldb/commit/2b588ecdbb6fee1f1c22a792a64455677f38575b

**Comment by josteink** [comment]
If your using clang3.4 the build *will* fail as certain code depends on features only found in clang3.5 or newer.

The train went some time ago. Clang 3.4 wont be supported. Instead just install clang3.5 using `pkg install clang35` and try building again.

**Comment by tony** [comment]
@josteink : Correct, to reiterate, this failure is happening using clang36.  Do you have the output of which ref / svn rev's you built against?

In the mean time, I'm going to try this in 3.5 and check over everything once more to assure I'm not overlooking an instruction on my end.

**Comment by tony** [comment]
Edited the above. To clarify my testing so far:

1. I compiled this with the toolchain's 3.4 clang/llvm (included with 10.1) @https://github.com/dotnet/coreclr/issues/940#issue-73733293
2. I tried again with clang 3.6 (``pkg install clang36``) @https://github.com/dotnet/coreclr/issues/940#issuecomment-99925701

Going to give it another go tomorrow.

**Comment by josteink** [comment]
As far as I know, the clang-detection code is currently only written to look for versions installed by `pkg install`. At the time it was updated to support this, [the code only looked for clang3.5](https://github.com/dotnet/coreclr/blob/080b2e0ead54994854b850949e9ebca613ac5197/src/pal/tools/setup-compiler-clang.sh), so I cannot guarantee it will pick up clang3.6 based on changes which has been added later.

During the configure-phase it should output which version of clang it is using. You can use this to easily detect if its using the wrong version or not.

If it gets the version wrong, you could try `pkg install clang35` and see if that resolves your issues.

**Comment by tony** [comment]
@josteink Thank you! Is that referring to building lldb on FreeBSD (a separate phase outside of ``build.sh`` https://github.com/dotnet/coreclr/blob/master/Documentation/freebsd-instructions.md#debugging-coreclr-optional) or just the .NET build.sh process? I did notice for the build.sh (without lldb) I had to type in the clang version as an argument: ``./build.sh clang3.5``. In fact I think it build with my 3.6 successfully at the time.

**Comment by josteink** [comment]
Oh I'm so sorry. I was referring to building CoreClr itself (which does indeed use the system-supplied clang-version).

For matters related to building LLDB3.6 (which is definitely recommended for CoreClr-hacking), we should probably summon @ajensenwaud who wrote those instructions in the first place :)

**Comment by tony** [comment]
yeah, let's establish I'm only here on a QA / docs / maybe porting (package) level. I don't want to distract @ajensenwaud from anything. :)

Still going to throw hammers at this, it'll be a huge win to have this working. If anyone else bumps into the same problem / has any news, please step in.

**Comment by josteink** [comment]
Just to double-check. Did you try build LLDB using the `master` branch instead of the release-branch?

For me it seems like there's a problem in the LLVM-codebase, which I'm guessing has been fixed in a newer revision.

**Comment by tony** [comment]
Yes. I tried against master and release.

Giving it another run through now.

**Comment by tony** [comment]
Yeah, still issues at the end when linking lldb. Just like in my gists. This is when building with the instructions as is.  I think it's just a matter of lldb just not being stable to build on 10.1, mixed with us building against whatever is in trunk at the time.

It says ``use -v to see invocation``, but not sure where I could put that in.

**Comment by josteink** [comment]
It may not be a very elegant approach, but this is the commits used on the system where we built LLDB in the first place:

    LLVM: 728ad0157c573763d1a6f3f5eee20eb8b26b50fc
    LLDB: 61cc715cf2e521fd0b6857ce5e7f2234ee3fef6f
    clang: e1bb9207529ad53c79b37fe87c0f3e7bbed90fc2

Basically from April 24th, and that worked for us.

You can try checking out those revs, and see if that gets you further. If it does, we should probably amend the docs somewhat until LLDB on FreeBSD becomes more stable.

**Comment by tony** [comment]
@josteink Thank you for the above. I tried it, and no luck.

However, I just was able to fully complete the linking process, without the script (trying with installation script again to check if there is anything that can be corrected).

```
$ ./build/bin/lldb-3.7.0 --version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lldb.embedded_interpreter
lldb version 3.7.0 (http://llvm.org/git/lldb.git revision 1de872de438384a404f9d4d7fce00be753d69d4b clang revision f804390611e593da49cbaebfafbed7963d3c5630 llvm revision 78ce816d3fd714411e515ef9d4e2b1e57f315f2b)
```

Will follow up.

**Comment by tony** [comment]
Hi. Don't want to leave anyone hanging here. My time for dotnet fun is limited. It'd be a big deal for us to have dotnet working flawlessly.  I highly recommend FreeBSD to anyone here, providing you pick the right hw before hand.

The compilation error happens during the ``ninja lldb install`` portion of the install. The ``lldb`` is created successfully.

I'm trying to ascertain if we can't get ``ninja lldb install`` to work, maybe we can get away with skipping that short term until it clears up.  If not, I'll go onto the llvm list / freebsd llvm lists and ask around.

@josteink : Does coreclr just need the lldb binary?  Or does it need to build / link against the source / headers of the *same* custom lldb/clang we're downloading?

**Comment by josteink** [comment]
A quick response:

* At this stage LLDB is required for debugging coreclr itself and its executables like corerun when getting things up and running. This is because GDB doesn't support ELF3 binary format and LLDB does. 
* If LLDB (and sources) is found during build-time, coreclr will also biuld a LLDB sos-debugger plugin. If not found, this plugin will not be built. The plugin currently doesn't really do much at all, so it's not the greatest loss.

So if you're able to get a LLDB binary up and running, you should be fine (for now). Don't sweat it.

**Comment by tony** [comment]
The lldb is being created. The ``ninja install`` part fails when linking a python related library.

Also, the script provided isn't ideal, as it builds a custom llvm/clang/lldb against the HEAD's, when the best practice would be to allow the option to detect/install the 1.) toolchain's (``/usr/src/``'s) 2.) installed clang/llvm packages 3.) allow an arbitrary clang/llvm path to be specified.

My time I can devote to this is limited at present, if you want to pick up the ball please mention. Nailing this down is a huge deal for us.  L

**Comment by josteink** [comment]
Agree about the HEAD issue, but the idea behind submitting this script initially was that something (flawed) is better than having nothing at all. To me it sounds like the priority should be investigating the correctness and completeness of the dependencies at this point.

**Comment by jasonwilliams200OK** [comment]
@saper thoughts about @tony's suggestion to make build script detect toolchain in a fallback manner? And BTW thank you for fixing FreeBSD issues in mono! :smile: :+1:

**Comment by saper** [comment]
@tony I understand that the linking process gets killed, correct? Can you check `/var/log/messages` or the console output - the reason of the crash should be there. 95% this problem is because linker is running out of memory - you may hit the limits ( see ulimit(1) man page ) or run out of swap space (or no swap configured). If the crash is due to segmentation fault you should get a cord dump which we can analyze.

**Comment by saper** [comment]
We should avoid the `install` ninja step since it actually builds the ready of llvm  including clang. This should not be necessary.

**Comment by josteink** [comment]
But we need LLDB to be installed in a predictable, system-wide location, otherwise we're left without any reliable cmake-rules for detecting it. 

Do you have any alternate ways to build only LLDB and get that installed without wasting time on the rest of the toolchain?

**Comment by saper** [comment]
Come on, we can just copy what is needed :)

**Comment by josteink** [comment]
If so, someone needs to add it to the script. Build-instructions should be as plug'n'play as possible ;)

**Comment by saper** [comment]
If somebody experiences `clang` dying during linking of lldb or later when compiling CoreCLR it is very often a sign that one runs out of virtual memory. You should have something like this in your `/var/log/messages`:

`Jun 19 09:20:06 m kernel: swap_pager_getswapspace(3): failed`

and also

`Jun 19 09:22:15 m kernel: pid 82435 (ld), uid 169, was killed: out of swap space`

To add more space just create a temporary file on your filesystem and add this as swap:

````
dd if=/dev/zero of=/var/tmp/moreswap bs=512M count=1
mdconfig -f /var/tmp/moreswap -u 0
swapon /dev/md0
````

and then see `swapinfo`:

````
 # swapinfo
Device          1K-blocks     Used    Avail Capacity
/dev/twed0p2      4194304  4167908    26396    99%
/dev/md0           524288   380788   143500    73%
Total             4718592  4548696   169896    96%
````

**Comment by tony** [comment]
I totally missed this.  I am going to look at this.

**Comment by tony** [comment]
To follow up on the gulf in communication, over the weeks I tried again numerous times, but it was a problem I had on this box I overlooked. https://github.com/dotnet/coreclr/issues/797#issuecomment-127187207
