### ISSUE TITLE
Readonly prefix not respected for multidimensional array address method

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/coreclr#9414]
The below code works on desktop CLR, but throws an `ArrayTypeMismatchException` on CoreCLR:

```csharp
using System;

class Program
{
    interface IFrobber
    {
        void Frob();
    }

    class Frobber : IFrobber
    {
        public void Frob()
        {
        }
    }

    class Foo<T> where T : IFrobber
    {
        public static void FrobAll(T[,] arr)
        {
            for (int i = 0; i < arr.Length; i++)
                arr[0, i].Frob();
        }
    }

    private static void Main(string[] args)
    {
        Foo<IFrobber>.FrobAll(new Frobber[,] { { new Frobber() } });
    }
}
```

The `FrobAll` method has the following IL sequence in it:

```
readonly.
call instance !0& !T[0..., 0...]::Address(int32, int32)
constrained. !T
callvirt instance void Program/IFrobber::Frob()
```

As per ECMA-335 III.2.3 the `readonly.` prefix shall suppress the exact type check done by the `Address` method and cause it to return a controlled-mutability managed pointer to the element of the array. The VM is not suppressing the type check in the IL stub.

Note this works when optimizations are enabled.

**Comment by gkhanna79** [comment]
@kouvel PTAL

**Comment by gkhanna79** [comment]
@jkotas @MichalStrehovsky Is this present on Desktop as well? Is there any reason this needs to be fixed for 2.0?

**Comment by jkotas** [comment]
> Is this present on Desktop as well?

It is regression from desktop. @MichalStrehovsky said above: "The below code works on desktop CLR, but throws an ArrayTypeMismatchException on CoreCLR."

> Is there any reason this needs to be fixed for 2.0?

I believe that the compat breaks from desktop are high on the list for 2.0.

**Comment by kouvel** [comment]
I'm able to repro the on desktop as well, when optimizations are turned off (Debug build)

**Comment by jkotas** [comment]
This is regression introduce by #4519. This change incorrectly remove the else statement here: https://github.com/dotnet/coreclr/commit/97b4ff0b438261ba11b357008630076054a6f25d#diff-edc46b80f57431489a82311948a8234dL6424

It is causing us to ignore the read-only prefix essentially.

> I'm able to repro this on desktop as well,

I assume that you have tried it on desktop build that included the above change.

**Comment by gkhanna79** [comment]
@fadimounir Can you help with this?

**Comment by kouvel** [comment]
Thanks @jkotas, adding the 'else' back in seems to solve the problem. I can post a PR but I'm not very familiar with this code, I'll add you folks on it.
