### ISSUE TITLE
Optimize default(T) != null at compile time

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/coreclr#9419]
`default(T) != null` in generic code is a popular* pattern to determine if `T` is a nullable or a reference type.

Example:

```csharp
using System;
using System.Runtime.CompilerServices;

class Program
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static bool IsNotNullableValueType<T>()
    {
        return default(T) != null;
    }

    private static void Main(string[] args)
    {
        Console.WriteLine(IsNotNullableValueType<string>());
        Console.WriteLine(IsNotNullableValueType<int>());
        Console.WriteLine(IsNotNullableValueType<int?>());
    }
}
```

Will print `False True False`.

While the codegen for the "it's a reference type" case is pretty efficient (we can do better though...):

```nasm
xor         eax,eax  
test        rax,rax  
setb        al  
movzx       eax,al  
ret  
```

For the "it's a valuetype" and "it's a nullable" case we get a useless allocation:

```nasm
sub         rsp,28h  
call        __NewHelper_System_Private_CoreLib_System_Int32
xor         edx,edx  
mov         dword ptr [rax+8],edx  
test        rax,rax  
seta        al  
movzx       eax,al  
add         rsp,28h  
ret  
```

The places that use this pattern would likely benefit from being able to statically evaluate this because it could lead to elimination of entire branches and smaller code (aside from removing a useless allocation).

\* There are 17 hits for the `default\(.*\) == null` regular expression in the CoreFX repo and a couple more for the "not equal to null" case.

**Comment by mikedn** [comment]
> default(T) == null in generic code is a popular* pattern to determine if T is a nullable or a reference type.

Hmm, == null works pretty well for me:
```asm
; reference types
       B801000000           mov      eax, 1
       C3                   ret
; value types 
       4883EC28             sub      rsp, 40
       33C0                 xor      eax, eax
       4883C428             add      rsp, 40
       C3                   ret
; nullable types
       50                   push     rax
       33C0                 xor      rax, rax
       48890424             mov      qword ptr [rsp], rax
       33C0                 xor      rax, rax
       488D1424             lea      rdx, bword ptr [rsp]
       488902               mov      qword ptr [rdx], rax
       803C2400             cmp      byte  ptr [rsp], 0
       0F94C0               sete     al
       0FB6C0               movzx    rax, al
       4883C408             add      rsp, 8
       C3                   ret
```
The nullable case isn't great but at least it doesn't allocate/box/whatever.

> call        __NewHelper_System_Private_CoreLib_System_Int32

What's this NewHelper thing? Is this CoreRT specific?

> and a couple more for the "not equal to null" case.

The assembly code you have posted appears to be generated by `!= null` rather than `== null`. 

Heh, the `x != null` mess. There's no `cne` instruction in IL so the C# compiler emits `cgt.un`. The JIT is lame and doesn't recognize that unsigned `x > 0` is the same as `x != 0`, I keep running into this issue and it's quite possible that this is what happens in your examples as well.

**Comment by MichalStrehovsky** [comment]
> What's this NewHelper thing? Is this CoreRT specific?

Yeah, I was doing this on CoreRT because that's what I have set up these days.

> The assembly code you have posted appears to be generated by != null rather than == null.

Yes - was testing that and assumed it's the same for `==`. I'll rename the issue then and update the original posting. Good catch! I assume this will be much lower priority then. `!= null` is less popular.

**Comment by mikedn** [comment]
I verified (hacked the importer) that this is indeed caused by `x cgt.un 0` not being treated as `x cne 0`.

Partially related issue: #7641

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by VSadov** [comment]
For the "popularity"

This pattern may be emitted by C# compiler when `?.` is used on generic targets. So it may be more common than searching through sources would indicate.

Example:
```C#
        static void TryDispose<T>(ref T disposable) where T:IDisposable
        {
            disposable?.Dispose();
        }
```

**Comment by mikedn** [comment]
>static void TryDispose<T>(ref T disposable) where T:IDisposable
{
    disposable?.Dispose();
}

This one doesn't appear to be affected as it uses `brtrue` rather than `cgt.un`.

**Comment by VSadov** [comment]
@mikedn - good to know that `?.` is not affected. 
I wonder if it is possible to have covered by tests? 
Would  not be nice if it starts boxing one day because of a regression.
