### ISSUE TITLE
Move CoreRT fat call transformation after inlining.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#9422]
As was discussed in #9191 there is open question about the best position for this transformation.
There are several possible solutions:
1) Inside importer;
2) Right after importer;
3) During morph;
4) After morph.
cc @BruceForstall, @AndyAyersMS .

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
Feel free to re-open if there is further discussion necessary or changes based on this topic.

**Comment by BruceForstall** [comment]
@RussKeldorph As I stated in #9191 I think the merged code put the phase in the wrong place. Closing this issue will obviously not fix that.

**Comment by RussKeldorph** [comment]
Ok, I was under the impression that this had been resolved offline.  If you and @AndyAyersMS agree that after inlining is still a better place for it, we can leave it open with a new title.

**Comment by sandreenko** [comment]
Decided not to move anywhere #13440.
