### ISSUE TITLE
Native DLL's used through platform invoke arent loaded from AppContext.BaseDirectory

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/coreclr#9447]
Moved from https://github.com/dotnet/cli/issues/5622 on behalf of @PurelySimple. There are more details in the original issue.

 @yizhang82

----

## Steps to reproduce
1. Create a new console project (ie MyApp) that outputs `Console.WriteLine(AppContext.BaseDirectory);`
2. Reference a native DLL call on a method using `[DllImport("MyNative.dll")]`
3. Make a call to that method in the application
4. Run `dotnet build` on the project
5. Copy MyNative.dll to the output directory (ie bin\Debug\netcoreapp1.1)
6. Run `dotnet <MyApp.dll>` from **within the output directory**. Everything should work fine. AppContext.BaseDirectory will be the output folder.
7. Go to another location (such as the project root) and run `dotnet <path\to\MyApp.dll>`
8. Failed to find MyNative.dll but AppContext.BaseDirectory will still be correctly set as the output folder (which contains the native dll).
## Expected  behavior
I would expect any native DLL's referenced from an assembly to reside along side it and behave like other managed DLL's by being loaded from AppContext.BaseDirectory and not wherever the `dotnet path\to\app.dll` was invoked from.

This is especially problematic as VS2017 seems to invoke the compiled app DLL from the project root and not the bin\Debug\netcoreapp1.1\ directory where it resides. I have to keep a separate set of native DLL's in the project root for them to be found.

## Actual behavior
The platform invoke call throws an exception saying the native DLL couldn't be found.

## Environment data
`dotnet --info` output:

$ dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

**Comment by gkhanna79** [comment]
Issue moved to [dotnet/core-setup #1636](https://github.com/dotnet/core-setup/issues/1636) via [**ZenHub**](https://www.zenhub.com/)
