### ISSUE TITLE
GCHandle.ctor mismatched execption

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#9449]
The ctor is using a `ArgumentOutOfRange_Enum` resource exception which seems off?
```
internal GCHandle(Object value, GCHandleType type)
{
    // Make sure the type parameter is within the valid range for the enum.
    if ((uint)type > (uint)MaxHandleType)
        throw new ArgumentOutOfRangeException(nameof(type), Environment.GetResourceString("ArgumentOutOfRange_Enum"));
```

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/InteropServices/GcHandle.cs#L56-L60

**Comment by justinvp** [comment]
Why does it seem off? `GCHandleType` is an enum.

**Comment by benaadams** [comment]
Ahh... yes was thinking of enumerator 😁
