### ISSUE TITLE
[Arm64] tests fail with Assertion failed 'initBlkNode->gtRsvdRegs == RBM_ARG_2' in 'Program:Init(byref,int)'

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#9458]
Failing Tests

<pre>
JIT/Regression/JitBlue/DevDiv_278371/DevDiv_278371/DevDiv_278371.cmd
</pre>

Example Output

<pre>
BEGIN EXECUTION
Core_Root\corerun.exe" DevDiv_278371.exe 10
Assert failure(PID 3552 [0x00000de0], Thread: 3548 [0x0ddc]): Assertion failed 'initBlkNode->gtRsvdRegs == RBM_ARG_2' in 'Program:Init(byref,int)' (IL size 11)
    File: f:\projects\coreclr\src\jit\codegenarm64.cpp Line: 3383
    Image: Tests2\Core_Root\CoreRun.exe
Expected: 100
Actual: 123456789
END EXECUTION - FAILED
FAILED

</pre>

**Comment by sdmaclea** [comment]
@jashook doesnt your recent merge for #9492 fix this?

**Comment by jashook** [comment]
@sdmaclea yes this is fixed with #9492
