### ISSUE TITLE
[Arm64] Tests fail with Assertion failed '(m_Call->gtFlags & GTF_CALL_INLINE_CANDIDATE) == 0' in 'System.ConsolePal:GetUseFileAPIs(int):bool'

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#9459]
Failing Tests

<pre>
Loader/classloader/TypeGeneratorTests/TypeGeneratorTest1481/Generated1481/Generated1481.cmd
</pre>

Example Output

<pre>
TEST_CMD_LINE: Loader\classloader\TypeGeneratorTests\TypeGeneratorTest1481\Generated1481> Loader\classloader\TypeGeneratorTests\TypeGeneratorTest1481\Generated1481\Generated1481.cmd 2161 
BEGIN EXECUTION
 "Core_Root\corerun.exe" Generated1481.exe 2161
Assert failure(PID 4656 [0x00001230], Thread: 7416 [0x1cf8]): Assertion failed '(m_Call->gtFlags & GTF_CALL_INLINE_CANDIDATE) == 0' in 'System.ConsolePal:GetUseFileAPIs(int):bool' (IL size 115)
    File: f:\projects\coreclr\src\jit\inline.cpp Line: 679
    Image: Core_Root\CoreRun.exe
Expected: 100
Actual: 123456789
END EXECUTION - FAILED
FAILED
</pre>

**Comment by AndyAyersMS** [comment]
@jashook any guidance you can offer on how to repro these?

**Comment by jashook** [comment]
Does not repro.
