### ISSUE TITLE
[Arm64] Tests fail with System.InvalidProgramException

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#9462]
Failing Tests

<pre>
JIT/Regression/CLR-x86-JIT/V1-M11-Beta1/b46867/b46867/b46867.cmd
JIT/Regression/CLR-x86-JIT/V1-M13-RTM/b88793/b88793/b88793.cmd
JIT/Regression/CLR-x86-JIT/V1-M11-Beta1/b41391/b41391/b41391.cmd
JIT/jit64/gc/misc/funclet/funclet.cmd
JIT/Regression/CLR-x86-JIT/V1-M11-Beta1/b37598/b37598/b37598.cmd
JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b409748/b409748/b409748.cmd
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b41852/b41852/b41852.cmd
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b37646/b37646/b37646.cmd
JIT/Regression/CLR-x86-JIT/V1-M11-Beta1/b36472/b36472/b36472.cmd
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b32374/b32374/b32374.cmd
JIT/Regression/CLR-x86-JIT/V1-M11-Beta1/b35784/b35784/b35784.cmd
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b31746/b31746/b31746.cmd
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b31745/b31745/b31745.cmd
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b30864/b30864/b30864.cmd
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b28901/b28901/b28901.cmd
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b30838/b30838/b30838.cmd
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b26324/b26324b/b26324b.cmd
JIT/Regression/CLR-x86-EJIT/V1-M12-Beta2/b26323/b26323/b26323.cmd
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b26324/b26324a/b26324a.cmd
JIT/Regression/CLR-x86-JIT/V1-M13-RTM/b91248/b91248/b91248.cmd
JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b16423/b16423/b16423.cmd
JIT/Methodical/eh/deadcode/badcodeafterfinally_d/badcodeafterfinally_d.cmd
JIT/Methodical/eh/deadcode/badcodeafterfinally_r/badcodeafterfinally_r.cmd
JIT/Methodical/Coverage/arglist_pos/arglist_pos.cmd
JIT/Directed/PREFIX/unaligned/4/arglist/arglist.cmd
JIT/Directed/PREFIX/unaligned/1/arglist/arglist.cmd
JIT/Directed/PREFIX/volatile/1/arglist/arglist.cmd
JIT/Directed/PREFIX/unaligned/2/arglist/arglist.cmd
JIT/opt/Tailcall/TailcallVerifyWithPrefix/TailcallVerifyWithPrefix.cmd
JIT/Methodical/refany/_il_relseq/_il_relseq.cmd
JIT/Methodical/xxobj/operand/_il_rellocalloc/_il_rellocalloc.cmd
JIT/Methodical/refany/_il_dbgseq/_il_dbgseq.cmd
JIT/Methodical/xxobj/operand/_il_dbglocalloc/_il_dbglocalloc.cmd
</pre>

Example Output

<pre>
TEST_CMD_LINE: JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b46867\b46867> JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b46867\b46867\b46867.cmd 6667 
BEGIN EXECUTION
 "Tests2\Core_Root\corerun.exe" b46867.exe 6667
Unhandled Exception: System.InvalidProgramException: Vararg calling convention not supported.
   at Test.AA.Main()
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
</pre>

**Comment by sdmaclea** [comment]
@jashook Your example code talks about varargs.  Does not seem to match the title.  For [Uniz] varargs tests are in the UnsupportedOutsideWindows category, so I do not run those tests.  If they are willing to be unsupported on Unix, do they need to be supported on Windows?  Seems like both platforms need to fully support Net Standard 2.0.  Why would Windows need varargs?  Any way I currently only see on e program failing with Invalid Program Exception on my [Arm64/Unix] tip.

**Comment by jashook** [comment]
@sdmaclea Arm64 Windows uses a different set of metadata from Windows x64 around tests. The tests that are varargs and should be removed has not been captured yet.

**Comment by jashook** [comment]
All test have been confirmed to either be VARAG, TLS, or Tail.call Pop ret. All not supported on dotnet core.
