### ISSUE TITLE
[Arm64] [4-Failures] Tests fail with System.NullReferenceException

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#9465]
Failing Tests

<pre>
JIT/Directed/coverage/importer/Desktop/ldelemnullarr1_il_d/ldelemnullarr1_il_d.cmd
JIT/Directed/coverage/importer/Desktop/ldelemnullarr1_il_r/ldelemnullarr1_il_r.cmd
JIT/Directed/coverage/importer/Desktop/nonrefsdarr_il_d/nonrefsdarr_il_d.cmd
JIT/Directed/coverage/importer/Desktop/nonrefsdarr_il_r/nonrefsdarr_il_r.cmd
</pre>

Example Output

<pre>
TEST_CMD_LINE: JIT\Directed\coverage\importer\Desktop\ldelemnullarr1_il_d> JIT\Directed\coverage\importer\Desktop\ldelemnullarr1_il_d\ldelemnullarr1_il_d.cmd 6760 
BEGIN EXECUTION
 "Tests2\Core_Root\corerun.exe" ldelemnullarr1_il_d.exe 6760
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ldelemnullarr1.f()
   at ldelemnullarr1.Main()
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
</pre>

**Comment by sdmaclea** [comment]
@jashook I am not seeing these on my [Arm64/Unix] tip.

**Comment by jashook** [comment]
@sdmaclea I have confirmed these still repro on Arm64 Windows.

**Comment by jashook** [comment]
No longer repro
