### ISSUE TITLE
[Arm64] Test fails with System.FormatException

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#9467]
Failing Tests

<pre>
baseservices/threading/paramthreadstart/ThreadStartBool/ThreadStartBool.cmd
</pre>

Example Output

<pre>
TEST_CMD_LINE: baseservices\threading\paramthreadstart\ThreadStartBool> baseservices\threading\paramthreadstart\ThreadStartBool\ThreadStartBool.cmd 49 
BEGIN EXECUTION
 "Tests2\Core_Root\corerun.exe" ThreadStartBool.exe 49
Unhandled Exception: System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at ThreadStartBool.Main(String[] args)
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED

</pre>

**Comment by sdmaclea** [comment]
@jashook I am not seeing these on my [Arm64/Unix] tip.

**Comment by jashook** [comment]
@sdmaclea Strangely this no longer repros.
