### ISSUE TITLE
Building CoreCLR on OS X requests LLDB

### ISSUE THREAD

**Issue by richlander** [dotnet/coreclr#947]
The build requests LLDB, but doesn't fail. What's that for? It would be good to update the doc to make this clear. https://github.com/dotnet/coreclr/blob/master/Documentation/osx-instructions.md

> Cannot find lldb-3.5 or lldb-3.6. Try installing lldb-3.6-dev (or the appropriate package for your platform)

Reported by @toptensoftware

**Comment by ellismg** [comment]
It's so you can build the sos plugin.  It doesn't fail because this is not needed to produce a functional CLR.  There is already #673 open to document how to do this.
