### ISSUE TITLE
[Arm64] Crossgen System.Private.CoreLib.ni.dll causes test failures

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#9481]
The following tests are failing when crossgen is run to create System.Private.CoreLib.ni.dll.

JIT/Performance/CodeQuality/Linq/Linq/Linq.sh
JIT/Performance/CodeQuality/Math/Functions/Functions/Functions.sh
JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.sh
JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh
JIT/Regression/CLR-x86-JIT/v2.1/DDB/b188478/b188478/b188478.sh
JIT/Regression/CLR-x86-JIT/v2.2/ddb/ddb188478/DDB188478/DDB188478.sh
Loader/classloader/regressions/dev11_95728/dev11_95728/dev11_95728.sh

The problem exists on my fork using 1/11/2017 baseline.  Tests were performed on Ubuntu 16.04

Looks like the problem is related to generics.

I need to verify the problem still exists on the tip.

**Comment by sdmaclea** [comment]
I am unable to verify whether the issue exist on tip due to a new failure when running crossgen on System.Private.CoreLib.dll.

Assert failure(PID 30582 [0x00007776], Thread: 30582 [0x7776]): Assertion failed 'initBlkNode->gtRsvdRegs == RBM_ARG_2' in 'System.Runtime.CompilerServices.Unsafe:InitBlockUnaligned(byref,ubyte,int)' (IL size 9)

    File: /home/sdmaclea/git/coreclr/src/jit/codegenarm64.cpp Line: 3381
    Image: /home/sdmaclea/overlay/crossgen

Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Vararg calling convention not supported. while compiling method System.String.Concat


This is similar to issue #9458

**Comment by sdmaclea** [comment]
Testing on this branch https://github.com/sdmaclea/coreclr/tree/Stability

**Comment by sdmaclea** [comment]
OK, now that #9458 is resolved, I have confirmed the reported issue still exists on tip.

**Comment by sdmaclea** [comment]
@RussKeldorph @CarolEidt There are a few issues which occur only when using the R2R version of System.Private.CoreLib.  Can you please mention the appropriate team(s).  

This is a sample of the assert which I neglected to include in the initial description
```
                Assert failure(PID 18757 [0x00004945], Thread: 18757 [0x4945]): Assertion failed 'genActualType(fptr->gtType) == TYP_I_IMPL' in 'DomainNeutralILStubClass:IL_STUB_InstantiatingStub():int:this' (IL size 21)
                
                    File: /home/sdmaclea/git/coreclr/src/jit/importer.cpp Line: 5640
                    Image: /home/sdmaclea/overlay/corerun
```

**Comment by RussKeldorph** [comment]
@jashook @dotnet/jit-contrib

**Comment by sdmaclea** [comment]
@janvorli @seanshpark Is this the same issue as #9590 was trying to solve?

**Comment by janvorli** [comment]
@sdmaclea no, the issue #9590 has fixed was specific to the x86 calling convention.

**Comment by sdmaclea** [comment]
The current tip has additional fails due to this issue.  The current list of failing tests is

```
JIT/Performance/CodeQuality/BenchmarksGame/k-nucleotide/k-nucleotide/k-nucleotide.sh
JIT/Performance/CodeQuality/BenchmarksGame/regexdna/regexdna/regexdna.sh
JIT/Performance/CodeQuality/Linq/Linq/Linq.sh
JIT/Performance/CodeQuality/Math/Functions/Functions/Functions.sh
JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.sh
JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh
JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh
JIT/Regression/CLR-x86-JIT/v2.1/DDB/b188478/b188478/b188478.sh
JIT/Regression/CLR-x86-JIT/v2.2/ddb/ddb188478/DDB188478/DDB188478.sh
JIT/superpmi/superpmicollect/superpmicollect.sh
Loader/classloader/regressions/dev11_95728/dev11_95728/dev11_95728.sh
```

**Comment by sdmaclea** [comment]
In summary, for a handful of tests, the tests pass if System.Private.CoreLib.ni.dll is removed from the overlay directory (falling back to System.Private.CoreLib.dll).  The set of tests all seem to use generics.

@dotnet/jit-contrib @jkotas @janvorli any guidance would be appreciated.

Does RyuJIT compile differently for R2R vs JIT?
How are generics expected to work for R2R?  
Is something missing which needs to be implemented for arm64?  
Is this a missing generic stub issue which only affect crossgen code?

Recommended debug procedure?
Relevant documentation?

**Comment by jkotas** [comment]
> Does RyuJIT compile differently for R2R vs JIT?

There are some differences - e.g. extra directions.

> Is something missing which needs to be implemented for arm64?

I do not think so. I believe it works fine on Windows.

> Recommended debug procedure?

Find bad code that makes the JIT fail. Once you know which method contains the bad code, you can run `crossgen System.Private.CoreLib.dll` and use the usual debugging techniques (JIT logging, etc.) to trace down the problem.

**Comment by sdmaclea** [comment]
Crossgen is not the root cause of the issue, it is a triggering condition.  Specifically, when the using  System.Private.CoreLib.ni.dll, the memory layout is different.

The issue is triggered when the target address for the indirect function call can fit withing a uint32_t.  The compilation of the ldc.i8 calli ends up getting lowered to ldc.i4 calli.  On 64 bit platforms this will trigger the assert mentioned above.

@dotnet/jit-contrib I will prepare a patch to change the assert to allow this lowering
@jkotas Thanks.  A kick in the pants is sometimes necessary and useful!
