### ISSUE TITLE
Update buildtools to current - required for building with VS2015

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#950]
Building mscorlib using VS2015 RC fails with:

BclRewriter : error BR9999: BclRewriter hit unhandled exception: Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item kind: 7

The problem is that the buildtools nugget package has old version of CCI that does not work with current Roslyn. We need to update it to current to make CoreCLR buildable using VS2015 RC (#30). It should be the last missing piece.

**Comment by jkotas** [comment]
@AlexGhiondea If I remember correctly, you have put together the buildtools nuget package for mscorlib build. Could you please update it to pick up the CCI2 bug fix?

**Comment by AlexGhiondea** [comment]
I will look into updating the BclRewriter tool (from Microsoft.DotNet.BuildTools.CoreCLR) to have the CCI fix you mention.

**Comment by jkotas** [comment]
Fixed by #1007
