### ISSUE TITLE
Review FEATURE_RANDOMIZED_STRING_HASHING define

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#9503]
It's always defined for corelib and for the VM so we could apparently remove it but apparently we may want to remove some cases.
https://github.com/dotnet/coreclr/issues/8883#issuecomment-271756822

**Comment by jkotas** [comment]
The randomized string hashing is enabled unconditionally in CoreCLR. All code for handling fallbacks that switche from non-randomized hashing to randomized hashing can be removed.

**Comment by gkhanna79** [comment]
Should @tarekgh look into this?

**Comment by tarekgh** [comment]
Yes we can clean up this part. @gkhanna79 I moved this to future milestone as I am seeing this is just a clean up.

**Comment by danmosemsft** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/13491
