### ISSUE TITLE
[Arm64] Audit open issues

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#9532]
There are a lot of old Arm64 issues.  I have not observed a lot of these failures in recent history while working with [Arm64/Unix].  

Also my recent pull request may cause status change on many issues.

I will probably go through the issues myself for [Arm64/Unix], but as many of the issues were opened on [Arm64/Windows]  I can only comment that the issue is not observed on [Arm64/Linux]  and suggest closing.

**Comment by RussKeldorph** [comment]
@sdmaclea Feel free to mention @jashook on issues you think may be closeable, and he can follow up.  Thanks for helping clean this up.

**Comment by RussKeldorph** [comment]
@rahku as well for VM issues.

**Comment by sdmaclea** [comment]
The think most of the issues that may fixed by my patches are GC issues.  My GC patches either effect the JIT or the Unix/PAL.  So I commented only to @jashook 

I could not comment on many Feature request issues, but I suspect some of them are also complete.

It may be worth deferring this until #9498 lands (or perhaps as part of approving it).

There seemed also to be additional stress modes mentioned in a few tests which I have not attempted.  Once we get the basic GC tests passing, are there additional configurations to try.

**Comment by sdmaclea** [comment]
@jashook Should I close this?  Looks like you have been auditing fails and have updated RyuJIT arm64 project  status

**Comment by sdmaclea** [comment]
@jashook This appears complete in absence of comment otherwise, closing
