### ISSUE TITLE
[Arm64/Unix]  Ubuntu 16.04 port status

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#9533]
This is issue is to track the status for [Arm64/Unix] on Ubuntu 16.04.  It represents my view of the tree which includes all my published pull requests.

### PAL tests 
100% passing

### CoreCLR tests

There are currently about 42 failing tests.  See #9516 

### Crossgen R2R failures

There currently about 7 tests which fail when using the R2R System.Private.Corelib.ni.dll.  See #9481 

### GC Stress See #9581
- All testing results excludes known failures w/o stress, unsupported on Unix, unexpected failures on Unix 
Amd64
- Also results exclude handful of tests failing due to timeout (Some modes of GCStress seems to increase runtime >10)

#### GCStress=0x1
100% passing

#### GCStress=0x2
There are currently about 2 intermittent failures 

#### GCStress=0x4
There are currently about a dozen tests failing.  

#### GCStress=0x8
100% passing

### CoreFX tests
No attempt to run

**Comment by sdmaclea** [comment]
@dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
@janvorli I am unable to mention arm64-contrib, so my mention above did not work

The above was written describing a tree with #9500, #9498, and the original patch for #9616 applied .

**Comment by janvorli** [comment]
@dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
All relevant changes have merged into tip...  This summary should correlate to master tip reality...  However I'll run regressions on tip to see what else might have changed

**Comment by sdmaclea** [comment]
Testing know is including priority one tests
There are currently 5 default configuration failures on tip 
```
// Optimization failure, No exception thrown
// https://github/com/dotnet/coreclr/issues/8648
// https://github/com/dotnet/coreclr/issues/10111
JIT/Regression/JitBlue/DevDiv_359736/DevDiv_359736_do/DevDiv_359736_do.sh
JIT/Regression/JitBlue/DevDiv_359736/DevDiv_359736_ro/DevDiv_359736_ro.sh

// StringFormat PosTest2
// https://github/com/dotnet/coreclr/issues/10115
CoreMangLib/cti/system/string/StringFormat1/StringFormat1.sh
CoreMangLib/cti/system/string/StringFormat2/StringFormat2.sh

// Error: passing struct with floats via reflection
// https://github/com/dotnet/coreclr/issues/10107
Regressions/coreclr/GitHub_7685/Test7685/Test7685.sh
```

GCStress has regressed.  #9581 failures have been updated to match tip.

Open pull requests assumed to be included ...

- #10243  fixes #9481
- #10211 fixes several libraries which fail to cross gen.  

Open issues

- There are two libraries which fail during crossgen.  See #10359 and #9898

**Comment by sdmaclea** [comment]
The [arm64/unix] current tip is failing 7 tests which are supported on [amd64/unix]

```
// Optimization failure, No exception thrown
// https://github/com/dotnet/coreclr/issues/8648
// https://github/com/dotnet/coreclr/issues/10111
JIT/Regression/JitBlue/DevDiv_359736/DevDiv_359736_do/DevDiv_359736_do.sh
JIT/Regression/JitBlue/DevDiv_359736/DevDiv_359736_ro/DevDiv_359736_ro.sh

// Unhandled Exception: System.OverflowException
// https://github.com/dotnet/coreclr/issues/11525
JIT/Methodical/fp.exgen/10w5d_cs_d/10w5d_cs_d.sh
JIT/Methodical/fp.exgen/10w5d_cs_r/10w5d_cs_r.sh

// Timeout
// https://github.com/dotnet/coreclr/issues/11524
JIT/Methodical/tailcall_v4/hijacking/hijacking.sh
JIT/jit64/opt/cse/hugeexpr1/hugeexpr1.sh
JIT/jit64/opt/cse/HugeField1/HugeField1.sh
```

The five new failures were previously not being tested based on taking to long to run.

GCStress is clean.

**Comment by sdmaclea** [comment]
I am closing this

The port is basically complete.
This has not been updated in a while.  It was superseded by a issue tracking attempt to ready linux-arm64 for release 2.1, which also has closed.
The build is mostly stable
The gcStress is typically clean
CoreFX has been run and it mostly passes
