### ISSUE TITLE
[Arm64] Audit/document Arm64 register usage

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#9534]
The BOTR suggest Coreclr Arm64 will use the Arm64 standard ABI.  

As I look at the code there are a lot of hard coded register values.  Codegen nodes using hardcoded registers.  It also looks like some of the Arm32 ABI also snuck into the Arm64 code.  They also do not conform to my understanding of the Arm64 ABI.

I would like to understand the register allocation design so that I can help drive its correct implementation.  If there is any existing design documentation available that would be nice.

Also given Arm64 larger register set, it would nice to be able to drive a series of register usage optimization studies.

There are CQ comments in the code about architecture for a better model for register allocation and kill mask etc.  Perhaps this is the place to prototype the design.

**Comment by sdmaclea** [comment]
@dotnet/arm64-contrib

**Comment by RussKeldorph** [comment]
@russellhadley @sivarv @briansull @CarolEidt @dotnet/jit-contrib

**Comment by sdmaclea** [comment]
I think the most obvious issue is the use of R12 which was IP for ARM32.  Instead of R16 which is IP0 on arm64.  

Unless there is an objection I would like to replace most to the hard coded usages of R12 with IP0.  I will also look for opportunity to use IP1.  

```
  #define RBM_CALLEE_TRASH_NOGC   (RBM_R12|RBM_R13|RBM_R14|RBM_R15)
  #define REG_DEFAULT_HELPER_CALL_TARGET REG_R12

  #define REG_JUMP_THUNK_PARAM     REG_R12
  #define RBM_JUMP_THUNK_PARAM     RBM_R12

  // IL stub's secret MethodDesc parameter (JitFlags::JIT_FLAG_PUBLISH_SECRET_PARAM)
  #define REG_SECRET_STUB_PARAM     REG_R12
  #define RBM_SECRET_STUB_PARAM     RBM_R12

 #define RBM_PROFILER_TAIL_USED           (RBM_R0 | RBM_R12 | RBM_LR)
```
cc @dotnet/arm64-contrib

**Comment by BruceForstall** [comment]
@sdmaclea Do you believe this issue is still active?

There are quite a few "custom" calling conventions with stubs, etc., which you have discovered. That should all be documented [here](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md) (though I wouldn't be surprised if there are things missing).

**Comment by sdmaclea** [comment]
It seems the register usage is at least internally consistent.  I think the ABI oddities are all related to managed code and do not affect native.  This can probably be safely closed.
