### ISSUE TITLE
[RyuJIT/ARM32] No reload of a trashed register

### ISSUE THREAD

**Issue by mskvortsov** [dotnet/coreclr#9556]
`r12` gets trashed by the helper call target :
<pre>
G_M46028_IG07:
000090  9803           ldr     r0, [sp+0x0c]	// [V00 this]
000092  68C0           ldr     r0, [r0+12]
000094  2800           cmp     r0, 0
000096  D120           bne     SHORT G_M46028_IG08
000098  F247 5000      movw    r0, 0x7500
00009C  F2CB 200E      movt    r0, 0xb20e
0000A0  F646 4371      movw    r3, 0x6c71
0000A4  F2CB 6374      movt    r3, 0xb674
0000A8  4798           blx     r3		// CORINFO_HELP_NEWSFAST
<b>0000AA  4684           mov     r12, r0</b>
0000AC  2100           movs    r1, 0
0000AE  F8CC 102C      str     r1, [r12+44]
0000B2  F241 0144      movw    r1, 0x1044
0000B6  F2CB 3190      movt    r1, 0xb390
0000BA  6809           ldr     r1, [r1]
0000BC  F10C 0014      add     r0, r12, 20
<b>0000C0  F24E 6CC1      movw    r12, 0xe6c1
0000C4  F2CB 6C7B      movt    r12, 0xb67b
0000C8  47E0           blx     r12		// CORINFO_HELP_ASSIGN_REF</b>
0000CA  9803           ldr     r0, [sp+0x0c]	// [V00 this]
<b>0000CC  4661           mov     r1, r12</b>
0000CE  2200           movs    r2, 0
0000D0  F24D 5359      movw    r3, 0xd559
0000D4  F2CB 5342      movt    r3, 0xb542
0000D8  4798           blx     r3		// System.AppDomain:SetupFusionStore(ref,ref):this
</pre>
Full JitDump is [here](https://gist.githubusercontent.com/mskvortsov/339d50ebfddaf9bb4bde05f18799faa1/raw/170a7a42b256540aa0af4f8f3b45239d4d84111e/SetupDomain.txt).
Reproduces with rel or chk builds (i.e. when compiling S.P.CoreLib.dll in the opt mode):
```
$ COMPlus_AltJit=System.AppDomain:SetupDomain corerun Any.exe
```
(This issue is a part of #8496.)

**Comment by mskvortsov** [comment]
The codegen log for that output:
<pre>
							GC regs: 0000 {} => 0001 {r0}
Generating: N143 ( 19, 18) [000031] DAC----------             ▌  st.lclVar ref    V09 tmp0         d:3 r12 REG r12 RV
							GC regs: 0001 {r0} => 0000 {}
IN0031:             mov     r12, r0
							V09 in reg r12 is becoming live  [000031]
							Live regs: 0000 {} => 1000 {r12}
							Live vars: {V00} => {V00 V09}
							GC regs: 0000 {} => 1000 {r12}
Generating: N145 (  1,  1) [000185] -------------             ▌  lclVar    ref    V09 tmp0         u:3 r12 REG r12 RV $38b
Generating: N147 (???,???) [000286] -------------             ▌  lea(b+44) byref  REG NA
Generating: N149 (  1,  1) [000186] -------------             ▌  const     int    0 REG r1 $40
IN0032:             movs    r1, 0
Generating: N151 (???,???) [000267] -A--GO-------             ▌  storeIndir int    REG NA
IN0033:             str     r1, [r12+44]
Added IP mapping: 0x001A STACK_EMPTY (G_M53608_IG07,ins#12,ofs#38)
Generating: N153 ( 11, 12) [000197] -------------             ▌  il_offset void   IL offset: 26 REG NA
Generating: N155 (  3,  7) [000245] -------------             ▌  const(h)  int    0xB3901044 [ICON_STR_HDL] REG r1 $3c6
IN0034:             movw    r1, 0x1044
IN0035:             movt    r1, 0xb390
Generating: N157 (  6,  9) [000246] ----G--------             ▌  indir     ref    REG r1 <l:$402, c:$14f>
IN0036:             ldr     r1, [r1]
							GC regs: 1000 {r12} => 1002 {r1 r12}
Generating: N159 (  1,  1) [000040] -------------             ▌  lclVar    ref    V09 tmp0         u:3 r12 REG r12 RV $38b
Generating: N161 (???,???) [000287] -------------             ▌  lea(b+20) byref  REG r0
IN0037:             add     r0, r12, 20
							Byref regs: 0000 {} => 0001 {r0}
Generating: N163 (???,???) [000268] -A--GO--R----             ▌  storeIndir ref    REG NA
							GC regs: 1002 {r1 r12} => 1000 {r12}
							Byref regs: 0001 {r0} => 0000 {}
IN0038:             movw    r12, 0x5651
IN0039:             movt    r12, 0xb67d
Call: GCvars=00000001 {V00}, gcrefRegs=1000 {r12}, byrefRegs=0000 {}
[58] Rec call GC vars = 00000001
IN003a:             blx     r12		// CORINFO_HELP_ASSIGN_REF
Marking regs modified: [f0] ([r0-r3 r12 lr] => [r0-r3 r12 lr f0])
...
Marking regs modified: [f15] ([r0-r3 r12 lr f0-f14] => [r0-r3 r12 lr f0-f15])
Added IP mapping: 0x0025 STACK_EMPTY (G_M53608_IG07,ins#19,ofs#62)
Generating: N165 ( 19, 17) [000051] -------------             ▌  il_offset void   IL offset: 37 REG NA
Generating: N167 (  1,  1) [000045] -------------             ▌  lclVar    ref    V00 this         u:2 REG r0 $80
IN003b:             ldr     r0, [sp+0x0c]	// [V00 this]
							GC regs: 1000 {r12} => 1001 {r0 r12}
Generating: N169 (???,???) [000288] -------------             ▌  putarg_reg ref    REG r0
							GC regs: 1001 {r0 r12} => 1000 {r12}
							GC regs: 1000 {r12} => 1001 {r0 r12}
<b>Generating: N171 (  1,  1) [000046] -------------             ▌  lclVar    ref    V09 tmp0         u:3 r12 (last use) REG r12 RV $38b</b>
Generating: N173 (???,???) [000289] -------------             ▌  putarg_reg ref    REG r1
							V09 in reg r12 is becoming dead  [000046]
							Live regs: 1000 {r12} => 0000 {}
							Live vars: {V00 V09} => {V00}
							GC regs: 1001 {r0 r12} => 0001 {r0}
IN003c:             mov     r1, r12
							GC regs: 0001 {r0} => 0003 {r0 r1}
</pre>

**Comment by mskvortsov** [comment]
`r12` is used as a lclvar home, but legacy backend used `r4`. `r12` seems somewhat unnatural here in the company of `r0`, ..., `r3`. Can this result of allocation be an issue in itself?

RyuJIT doesn't create an IR node for the call to `CORINFO_HELP_ASSIGN_REF` helper and instructions are emitted during code generation for a `storeIndir` node instead. Though the neighbour call to `CORINFO_HELP_NEWSFAST` does have its own IR node. I guess this discrepancy is caused by the fact that `gcInfo` becomes available only at the codegen phase, so we can't decide which way we go till the very end. From the `codegenarm.cpp`:
```c++
            GCInfo::WriteBarrierForm writeBarrierForm = gcInfo.gcIsWriteBarrierCandidate(treeNode, data);
            if (writeBarrierForm != GCInfo::WBF_NoBarrier)
            {
                ...
                genGCWriteBarrier(storeInd, writeBarrierForm);
            }
            else // A normal store, not a WriteBarrier store
            {
                ...
            }
```
In `genEmitHelperCall` I can see the fragment:
```c++
        if (callTargetReg == REG_NA)
        {
            // If a callTargetReg has not been explicitly provided, we will use REG_DEFAULT_HELPER_CALL_TARGET, but
            // this is only a valid assumption if the helper call is known to kill REG_DEFAULT_HELPER_CALL_TARGET.
            callTargetReg = REG_DEFAULT_HELPER_CALL_TARGET;
        }
```
But how is RA supposed to know about something gets killed if the existence of a helper call is decided only at the CG?

The dump contains this fragment:
```
Generating: N171 (  1,  1) [000046] -------------             ▌  lclVar    ref    V09 tmp0         u:3 r12 (last use) REG r12 RV $38b
Generating: N173 (???,???) [000289] -------------             ▌  putarg_reg ref    REG r1
							V09 in reg r12 is becoming dead  [000046]
							Live regs: 1000 {r12} => 0000 {}
							Live vars: {V00 V09} => {V00}
							GC regs: 1001 {r0 r12} => 0001 {r0}
IN003c:             mov     r1, r12
							GC regs: 0001 {r0} => 0003 {r0 r1}
```
No code is generated for `lclVar`, i.e. the following emit is not executed:
```c++
            // If this is a register candidate that has been spilled, genConsumeReg() will
            // reload it at the point of use.  Otherwise, if it's not in a register, we load it here.

            if (!treeNode->InReg() && !(treeNode->gtFlags & GTF_SPILLED))
            {
                assert(!isRegCandidate);
                emit->emitIns_R_S(ins_Load(treeNode->TypeGet()), emitTypeSize(treeNode), treeNode->gtRegNum,
                                  lcl->gtLclNum, 0);
                genProduceReg(treeNode);
            }
```
and subsequent `genConsumeReg` of `putarg_reg` doesn't reload `r12` too:
```c++
    // Handle the case where we have a lclVar that needs to be copied before use (i.e. because it
    // interferes with one of the other sources (or the target, if it's a "delayed use" register)).
    // TODO-Cleanup: This is a special copyReg case in LSRA - consider eliminating these and
    // always using GT_COPY to make the lclVar location explicit.
    // Note that we have to do this before calling genUpdateLife because otherwise if we spill it
    // the lvRegNum will be set to REG_STK and we will lose track of what register currently holds
    // the lclVar (normally when a lclVar is spilled it is then used from its former register
    // location, which matches the gtRegNum on the node).
    // (Note that it doesn't matter if we call this before or after genUnspillRegIfNeeded
    // because if it's on the stack it will always get reloaded into tree->gtRegNum).
    if (genIsRegCandidateLocal(tree))
    {
        GenTreeLclVarCommon* lcl    = tree->AsLclVarCommon();
        LclVarDsc*           varDsc = &compiler->lvaTable[lcl->GetLclNum()];
        if (varDsc->lvRegNum != REG_STK && varDsc->lvRegNum != tree->gtRegNum)
        {
            inst_RV_RV(ins_Copy(tree->TypeGet()), tree->gtRegNum, varDsc->lvRegNum);
        }
    }
```

**Comment by mskvortsov** [comment]
@BruceForstall Can you take a look?

**Comment by BruceForstall** [comment]
The kill set is decided in lsra.cpp, getKillSetForNode():
```
        case GT_STOREIND:
            if (compiler->codeGen->gcInfo.gcIsWriteBarrierAsgNode(tree))
            {
                killMask = RBM_CALLEE_TRASH_NOGC;
#if !NOGC_WRITE_BARRIERS && (defined(_TARGET_ARM_) || defined(_TARGET_AMD64_))
                killMask |= (RBM_ARG_0 | RBM_ARG_1);
#endif // !NOGC_WRITE_BARRIERS && (defined(_TARGET_ARM_) || defined(_TARGET_AMD64_))
            }
```
and for ARM, we have:
```
#define RBM_CALLEE_TRASH_NOGC   (RBM_R2|RBM_R3|RBM_LR)
```
perhaps you just need to add R12 to that list? Ideally you would only do that if you knew R12 was going to be needed to load the target address.

**Comment by mskvortsov** [comment]
Extending the `RBM_CALLEE_TRASH_NOGC` indeed fixed the issue, thank you for the suggestion! 

The next issue I'm running into is about reload too. The final phase of LSRA can insert additional `GT_RELOAD` nodes. And this happens in the following case:
<pre>
------------ BB12 [???..???), preds={BB11} succs={BB13}
N413 (  1,  1) [000231] ------?------      t231 =    lclVar    int    V11 tmp2         u:3 r0 (last use) REG r0 RV $28b

                                                  ┌──▌  t231   int    
N415 (???,???) [000743] ------------Z      t743 = ▌  putarg_reg int    REG r0

N417 (  3,  7) [000245] ------?------      t245 =    const(h)  int    0xB1FA29C0 token REG r1 $4d

                                                  ┌──▌  t245   int    
N419 (???,???) [000744] -------------      t744 = ▌  putarg_reg int    REG r1

N421 (  3,  7) [000745] ------------Z      t745 =    const(h)  int    0xB67704BD ftn REG r0

<b>                                                  ┌──▌  t745   int    
               [000765] -------------      t765 = ▌  reload    int    REG r10</b>

                                                  ┌──▌  t743   int    arg0 in r0
                                                  ├──▌  t744   int    arg1 in r1
                                                  ├──▌  t765   int    control expr
N423 ( 20, 20) [000248] --CXG-?------      t248 = ▌  call help int    HELPER.CORINFO_HELP_RUNTIMEHANDLE_CLASS $326

                                                  ┌──▌  t248   int    
N425 ( 20, 20) [000561] DACXG--------             ▌  st.lclVar int    V15 tmp6         d:5 r1 REG r1 RV

N001 (  1,  1) [000774] ------------z      t774 =    lclVar    ref    V14 tmp5          REG r12

N001 (  1,  1) [000775] ------------z      t775 =    lclVar    ref    V13 tmp4          REG lr
</pre>
But nothing gets emitted for `t765`, and call target gets uninitialized (and assertion about missing `tmpRlsTemp` is fired). Though the existence of that `reload` node is suspicious or at least unclear for me, I wanted to avoid digging into LSRA internals, and made a fix according to what `codegenarm.cpp` states for these nodes:
```c++
        case GT_RELOAD:
            // do nothing - reload is just a marker.
            // The parent node will call genConsumeReg on this which will trigger the unspill of this node's child
            // into the register specified in this node.
            break;
```
After I added a missing `genConsumeReg` for the call target in `genCallInstruction`
```c++
    if (target != nullptr)
    {
        // For ARM a call target can not be a contained indirection
        assert(!target->isContainedIndir());

        // Reload the call target register if LSRA decided so.
        if (target->gtOper == GT_RELOAD)
        {
            genConsumeReg(target);
        }

        // We have already generated code for gtControlExpr evaluating it into a register.
        // We just need to emit "call reg" in this case.
        //
        assert(genIsValidIntReg(target->gtRegNum));

        genEmitCall(emitter::EC_INDIR_R, methHnd,
                    INDEBUG_LDISASM_COMMA(sigInfo) nullptr, // addr
                    retSize, ilOffset, target->gtRegNum);
    }
```
the issue has gone. The question is whether this fix looks like an acceptable one, or should I instead investigate why the `reload` node gets inserted?

**Comment by mskvortsov** [comment]
Actually, `genConsumeReg` should happen unconditionally in the last fragment, because a target register is indeed consumed by `genEmitCall`. I've updated the PR attached.
