### ISSUE TITLE
[Arm*/Unix] Cross building fails to correctly set HAVE_PROCFS_STATUS

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#9559]
Trying to cross build native components ran into this issue.

Also the #9505 helped reduce the impact of this incorrect cmake setting.

This issue might be resolved by 

1. updating documentation to cross build as sudo. 
2. updating cross build document to instruct user to natively build native components
3. fix cmake definition to correctly set HAVE_PROCFS_STATUS when using ROOTFS as user.
4. fix rootfs.sh to allow cmake to correctly determine HAVE_PROCFS_STATUS when building in user mode

Generally I have worked around it by natively building native components.

I do not intend to fix this

**Comment by sdmaclea** [comment]
When cross building, the pal build.h file does not get affected by tryrun.cmake.

For instance,

SET( HAVE_PROCFS_STAT_EXITCODE 1)
CACHE STRING "Result from TRY_RUN" FORCE)

Should cause HAVE_PROCFS_STAT to be defined as 1 in the generated build.h file.

**Comment by parjong** [comment]
@sdmaclea As I know, you need to set ``HAVE_PROCFS_STAT_EXITCODE`` as 0 to define ``HAVE_PROCFS_STAT``. 

``HAVE_PROCFS_STAT_EXITCODE`` is an exit code of the corresponding test program, and the test program should return 0 (instead of 1) if ``HAVE_PROCFS_STAT`` is supported.

**Comment by sdmaclea** [comment]
Thanks

**Comment by sdmaclea** [comment]
This is still an issue, but I think the user/sudo thing is incorrect.

**Comment by sdmaclea** [comment]
@lemmaa #5406 introduced these variables, but set their value to failure.  Is PROCFS not available required for your Arm64 platform.

The incorrect setting of these variable causes debug mkfifo name collisions

**Comment by lemmaa** [comment]
@sdmaclea The commit https://github.com/dotnet/coreclr/pull/5406 was created in the course of experimental arm64 build enabling to determine the state of coreclr arm64 at that time. So I do not mind changing the cache value. I'm sorry for the inconvenience.

**Comment by sdmaclea** [comment]
@lemmaa Thanks
