### ISSUE TITLE
Crossgen has warning re Vararg calling convention

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#9570]
`Vararg calling convention not supported. while compiling method System.String.Concat`
It doesn't break the build.

Probably introduced when 6ba12d06 exposed members including `Concat(System.Object,System.Object,System.Object,System.Object,__arglist)` in model.xml. Model.xml has been deleted, but the sources were made to match it so the message continues.

@jkotas / @safern  does this refer to `__arglist`? is a fix needed?

**Comment by jkotas** [comment]
This is expected for now.

The eventual fix is tracked by https://github.com/dotnet/coreclr/issues/9204 .
