### ISSUE TITLE
Intermittent Unhandled Exception: System.Exception: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE)) in unit testing (win8.1)

### ISSUE THREAD

**Issue by bpschoch** [dotnet/coreclr#959]
I get very occasional errors in my unit tests for pipes that I'm developing, but they occur after the unit tests are successful:
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.
Discovering: System.IO.Pipes.Tests
Discovered: System.IO.Pipes.Tests
Starting: System.IO.Pipes.Tests
Finished: System.IO.Pipes.Tests
=== TEST EXECUTION SUMMARY ===
System.IO.Pipes.Tests Total: 108, Errors: 0, Failed: 0, Skipped: 0, Time:
0.620s
Unhandled Exception: System.Exception: The handle is invalid. (Exception from
HRESULT: 0x80070006 (E_HANDLE))
at System.Threading.TimerQueue.DeleteAppDomainTimer(IntPtr handle)
at System.Threading.TimerQueue.AppDomainTimerSafeHandle.ReleaseHandle()
at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
at System.Runtime.InteropServices.SafeHandle.Finalize()

**Comment by karelz** [comment]
Do you have a way to repro it? Do you have a crash dump?
Who uses the SafeHandle? Is it System.IO.Pipes or the test itself?

**Comment by tzwlai** [comment]
@bpschoch, closing this issue since there hasn't been any activity in a while.  Please feel free to reopen if necessary.
