### ISSUE TITLE
Add a microbenchmark to track performance of  Slice API on slow and fast Span

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#9595]

**Comment by russellhadley** [comment]
@ahsonkhan Is this complete?  Can we close?

**Comment by ahsonkhan** [comment]
I believe we can. However, the microbenchmarks only run against fast span and won't help with comparison of fast vs slow span.

@sivarv, when you opened the issue, did you have other microbenchmarks in mind other than those that bare-bones exercise the different APIs?

**Comment by sivarv** [comment]
I filed this issue so that we check-in a two benchmarks for slice: one for that runs against fast span and another one that runs against slow span.  Looks like right now all Span benchmarks run against fast span.  We should have the same benchmarks compiled into separate exes that run against Slow span.

You can go ahead and close this issue and open a separate issue for adding benchmarks that run against slow span.

**Comment by ahsonkhan** [comment]
I opened these issues and hence this issue can be closed:
#10098 
#10099
