### ISSUE TITLE
Regressions/common/Marshal/Marshal test fails on Ubuntu16.10 in Helix (transient)

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#9614]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170215.04/workItem/Regressions.XUnitWrapper/analysis/xunit/Regressions._common_Marshal_Marshal_~2F_common_Marshal_Marshal_cmd

**Comment by gkhanna79** [comment]
@wtgodbe Is this still happening?

**Comment by wtgodbe** [comment]
It doesn't appear so, there's no failures for this test in the recent history.
