### ISSUE TITLE
[ARM64] GCStress hole in System.Net.NameResolutionPal.TryGetAddrInfo

### ISSUE THREAD

**Issue by billwert** [dotnet/coreclr#9617]
Credit to @leculver for the investigation here. cc: @RussKeldorph 

There's not a repro test for this in the tree right now; I hit this by spinning up a few tasks (5-10) calling Dns.GetHostEntry. 

```csharp
            Uri uri = new Uri(url);
            while(true)
            {
                Task[] tasks = new Task[count];
                for(int i = 0; i < count; i++)
                {
                    tasks[i] = Task.Run(() => Dns.GetHostEntry(uri.Host));
                }
                Task.WaitAll(tasks);
                Console.WriteLine("looped");
            }

```

    0:008> !vh
    object 0000018e441bf0a8: bad member 0049005700000000 at 0000018E441BF0B0
    Last good object: 0000018E441BD0E0.
     
    0:008> !gcroot 0000018e441bf0a8
    Thread 1340:
        0000003d4fdfe710 00007ffc2486915c System.Net.NameResolutionPal.TryGetAddrInfo(System.String, System.Net.IPHostEntry ByRef, Int32 ByRef)
            X24: 
                ->  0000018e441bf0a8 System.Net.SocketAddress
 
    0:008> !gcinfo   00007ffc2486915c
           [snip]
    000001d0 +X24
    000001ec -X0
    00000210 +X0
    00000228 -X0
    00000254 +X0(interior)
    00000258 -X0(interior) +X0
    0000025c +X1
    00000270 -X24 -X1
    00000298 +X1
    000002b0 -X1 -X0
    000002b4 +X24
    000002c4 +X0(interior)
    000002c8 -X0(interior) +X0
    000002cc +X1
    000002e0 -X24 -X1
     
        00007ffc`248691d8 b940001f ldr         wzr,[x0]
        00007ffc`248691dc d63f0180 blr         x12         This is just a call that will return.
    +270 00007ffc`248691e0 90ffff4b adrp        x11,System_Net_NameResolution+0x1000 (00007ffc`24851000)
        00007ffc`248691e4 910b016b add         x11,x11,#0x2C0
    [snip]
        00007ffc`24869244 f940016c ldr         x12,[x11]
        00007ffc`24869248 b940001f ldr         wzr,[x0]
         00007ffc`2486924c d63f0180 blr         x12
    +2b4 00007ffc`24869250 90ffff4b adrp        x11,System_Net_NameResolution+0x1000 (00007ffc`24851000)
 
From the stress logs, we can see a GC occurred at +270 in the method, triggering the GC hole:

    c94   1.951064200 : `GCROOTS`            Scanning Frameless method 00007FFBB9594380 (System.Net.NameResolutionPal.TryGetAddrInfo(System.String, System.Net.IPHostEntry ByRef, Int32 ByRef)) ControlPC = 00007FFC248691E0

**Comment by RussKeldorph** [comment]
Thanks @leculver for the thorough analysis!

**Comment by jashook** [comment]
Assigning back to @leculver for further information as x24 seems to be marked correctly.
