### ISSUE TITLE
Environment.CurrentExecutionId seems very useful. Why not public?

### ISSUE THREAD

**Issue by VSadov** [dotnet/coreclr#9638]
Environment.CurrentExecutionId seems to be a generally useful API, that can be used to correlate accesses to striped data in order to minimize unwanted cross core sharing.

Currently the best correlation option is the `CurrentManagedThreadId` which helps with continuity of accesses to the same stripe within a thread, but does not help much with preventing unwanted stripe sharing from threads running on separate cores.

**Comment by VSadov** [comment]
Re: https://github.com/dotnet/coreclr/blob/e5f2df239b546ac9ed2417506c90af222eaf1013/src/mscorlib/src/System/Environment.cs#L709

**Comment by jkotas** [comment]
Agree that it looks useful.

@VSadov Process for adding new public APIs
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md

Close the issue here, and open a new one in corefx with the API proposal.

**Comment by gkhanna79** [comment]
@danmosemsft Can you please move this to CoreFX?

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #16767](https://github.com/dotnet/corefx/issues/16767) via [**ZenHub**](https://www.zenhub.com/)
