### ISSUE TITLE
[RyuJIT/ARM32] GT_ARR_INDEX/GT_ARR_OFFSET support in codegen

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#9648]
I've made implementation for `GT_ARR_INDEX` and `GT_ARR_OFFSET` instructions but can'not test it since compiler doesn't put them to the IR on tests. All array access are made buy using `GT_ARR_BOUNDS_CHECK` + `GT_LEA`.
Does them exist on lowering and codegen? Could you help with C# code which cover this test case?

**Comment by mikedn** [comment]
Those are used for multidimensional arrays. As in:
```C#
int[,] a = new int[2, 3];
a[x, y] = 42;
```
There should be tests for that, try tests\src\JIT\Methodical\MDArray\ for example.

**Comment by alpencolt** [comment]
Thank you!
But it works only in optimized build, the call `System.Int[,].Set` is being generated on debug version.

**Comment by alpencolt** [comment]
@Dmitri-Botcharnikov

**Comment by mikedn** [comment]
> But it works only in optimized build, the call System.Int[,].Set is being generated on debug version.

It's quite possible. IL only has instructions for SZArrays (single dimensional arrays with a 0 lower bound - `int[]` in C#) - `ldlen`, `ldelem`, `stelem` etc. For any other type of arrays (single dimensional arrays with a non-0 lower bound and multidimensional arrays) one needs to call array specific methods such as `Set`. It's up to the JIT compiler to treat such methods as intrinsics and turn them into special IR nodes. And the JIT may or may not do so depending on compilation options such as debug/release.

**Comment by BruceForstall** [comment]
Fixed by #9679
