### ISSUE TITLE
Add EnableSSE3_4 as clr configuration knob in the documentation

### ISSUE THREAD

**Issue by litian2025** [dotnet/coreclr#9659]
In the clr configuration knob documentation at https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md, EnableAVX is documented, however, EnableSSE3_4 is not documented, we should add EnableSSE3_4 to the configuration document to help other developers who want to use this configuration knob when prototyping and testing.

The related code is at: https://github.com/dotnet/coreclr/blob/master/src/jit/jitconfigvalues.h#L198-#L209, both EnableSSE3_4 and EanbleAVX are already there.

We can provide a related PR for this, @fiigii PTAL

**Comment by RussKeldorph** [comment]
@sivarv @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Fixed via #15858.
