### ISSUE TITLE
Encoding Match UTF8 implementation with corefxlabs

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#9668]
Tracking issue

Match UTF8 implementation
Simplify fallback as the occasional route (non-hot path) for both ASCII and UTF8

See https://github.com/dotnet/coreclr/pull/9187#discussion_r98521142

**Comment by benaadams** [comment]
This would need to be resolved first https://github.com/dotnet/corefx/issues/16334

**Comment by danmosemsft** [comment]
@tarekgh is this necesasry for 2.0?

**Comment by benaadams** [comment]
Its a bigger change than I tried to do so probably needs the code coverage increased first?

**Comment by tarekgh** [comment]
@danmosemsft I moved it to the future. it is not really required for v2.0

**Comment by danmosemsft** [comment]
Thanks!

**Comment by jkotas** [comment]
If you are not going to fix this for 2.0, you should just resolve it as won't fix. It is pretty non-realistic that we will change it if 2.0 ships with this behavior.

**Comment by jkotas** [comment]
I have just written a comment here that was meant for a different issue. It is deleted now. Sorry for the noise.

**Comment by GrabYourPitchforks** [comment]
Closing because it looks like all the work is completed. Please reopen if I have closed this improperly.
