### ISSUE TITLE
Finalizer not getting called for Disposable type objects 

### ISSUE THREAD

**Issue by rnagpal** [dotnet/coreclr#9674]
**Steps to Reproduce**:
This is my code:
```
            using (TestClass test = new TestClass())
            {

            }

            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();

```

This is how I defined TestClass:

```
    public class TestClass : IDisposable
    {
        public void Dispose()
        {
            Dispose(true);
            //GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                Console.WriteLine("Disposing TestClass.");
            }
        }

        ~TestClass()
        {
            Dispose(false);
            Console.WriteLine("TestClass Finalizer called");
        }
    }

```
**Expected Behavior**:
I do see "Disposing TestClass" being printed after the using statement as expected but I also expect "TestClass Finalizer called" to be printed after the GC commands I run. I ensured that I skip calling GC.SuppressFinalize(this); in the Dispose method. Looks like disposed variables don't get finalized even after they are out-of-scope. They seem to get finalized just before the program exits.

**Actual Behavior**:
I only see "Disposing TestClass" being printed after the using statement as expected only don't see "TestClass Finalizer called" after the GC commands. I only see it just before the program exits.

Isn't this considered a memory leak?

**Comment by rnagpal** [comment]
If I convert this to a non-disposable class and update the code like below, I do see the finalizer being called after the GC commands. 

```
TestClass test = new TestClass();
test = null;

GC.Collect();
GC.WaitForPendingFinalizers();
GC.Collect();
```

This is how TestClass is defined:

```
public class TestClass
    {
        ~TestClass()
        {   
            Console.WriteLine("TestClass Finalizer called");
        }
    }
```

**Comment by mikedn** [comment]
I tried your code but it seems to work fine. Just to be sure I added some more `Console.WriteLine` after `Collect` and `WaitForPendingFinalizers` so the output I'm seeing is:
```
Disposing TestClass.
collect done
TestClass Finalizer called
wait pending done
```
So as far as I can tell the finalizer runs as expected, when `WaitForPendingFinalizers` is called and not when the application exits.

What runtime version are you using to run your program? Perhaps this was a bug that got fixed.

**Comment by rnagpal** [comment]
@mikedn That's strange. I was targeting .NET 4.5.1. Even after changing to .NET 4.6 and .NET 4.6.2, I still see the same results(no finalizer call after GC commands). I'm using running it from a Console App in Visual Studio 2015 Update 3. What Fx were you targeting? I assume that I'm targeting CLR 4.0. Let me know if you need any more info from me.

**Comment by jkotas** [comment]
The behavior you are seeing is by design.

The finalizers are not guaranteed to be called immediately after the object becomes unreachable. The lifetime can be extended by the code generator; conservative scanning of GC roots or other runtime implementation details. Explicit call to collect `GC.Collect()` or `GC.WaitForPendingFinalizers()` does not change it. It just makes it more likely for the finalizers to get called.

https://github.com/dotnet/coreclr/issues/5826#issuecomment-226574611 has more details about this.

**Comment by rnagpal** [comment]
Here is the reason for this behavior:

The following code:
```
using (TestClass test = new TestClass())
{

}
```
Gets compiled to this:
TestClass test;
try
{
test = new TestClass();
}
finally
{
if(test != null)
      test.Dispose();
}

For the same reasons as explained in https://github.com/dotnet/coreclr/issues/9673, when you run this in Debug mode, the "test" variable is alive until the end of the method and hence it's not GC'ed and finalizer not getting called. If you run the same thing in Release mode, it will work as expected which is what @mikedn might be running.

For the non-disposable type(in my second comment), since there is a way in which you can assign this "test" variable to null and hence GC can collect it even when used in Debug mode and hence it works as expected.

**Comment by mikedn** [comment]
>  If you run the same thing in Release mode, it will work as expected which is what @mikedn might be running.

Well, knowing how things work I tend to assume that anyone complaining about GC issues runs Release executables, otherwise it's pointless :)
