### ISSUE TITLE
Enable PipeLine build support for Linux armel (Tizen)

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#9689]
Enable Pipeline build support for Linux for armel (Tizen) and publish packages

@gkhanna79 Please assign this to yourself  as you requested, because I don't have permission :)

**Comment by danmosemsft** [comment]
@gkhanna79 is this on track for ZBB? are you doing the work yourself or should it be assigned to someone else?
@weshaggard @Chrisboh @markwilkie

**Comment by hqueue** [comment]
@jyoungyun Can we close this by now ?

**Comment by gkhanna79** [comment]
@hqueue @jyoungyun Can this be closed?

**Comment by gkhanna79** [comment]
Closing so that work is tracked by https://github.com/dotnet/core-setup/issues/1566
