### ISSUE TITLE
Offline Build Problem

### ISSUE THREAD

**Issue by nick-rudh** [dotnet/coreclr#9696]
I am trying to build dotnet core on RHEL from source; however my development machine does not have internet access. So I found that when running the ./build.sh script I am suppose to use the handle "skipgenerateversion" however when it calls the "init-tools.sh" file it seems to try and grab some packages from the internet from host "dotnetcli.blob.core.dotnet.tar" I downloaded "dotnet-rhel-x64.latest.tar.gz" now i made the init-tools.sh script use the path to this extracted executable, but it seems to try and download some more stuff from "https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json" and some others. Do I need to download these all or is there a flag that is suppose to be set when this script is called so it uses a local repo in the git repository?

thanks

Error: 
Commencing build of managed components for Linux.x64.Debug
Running init-tools.sh
Installing dotnet cli...
curl: (6) Couldn't resolve host 'dotnetcli.blob.core.windows.net'
tar: ~/git/coreclr/Tools/dotnetcli/dotnet.tar: Cannot open: No such file or directory
Restoring BuildTools version 1.0.27-prerelease-01209-01...
~/git/coreclr/init-tools.sh: line 141: ~/git/coreclr/Tools/dotnetcli/dotnet: No such file or directory

**Comment by danmosemsft** [comment]
@weshaggard since he mentioned offline build today.

**Comment by weshaggard** [comment]
For our normal repo builds we do require you to be online to initialize our tools and pull down external dependencies. So you will at least need to do one full build online before you can do a build offline.

We are working on providing a source tar that can build the full .NET Core product offline but it isn't at a state where it works yet. cc @ellismg
