### ISSUE TITLE
Make CoreCLR's Xunit Wrappers more granular

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#9709]
We currently have 13 Xunit Wrappers which comprise ~11,000 tests - when running in Helix, each wrapper  runs all of its tests serially, which means we are only parallelizing across those 13 wrappers, and no further. If we instead had more specific wrappers, each comrpising a smalller set of tests, we could shorten each job & better take advantage of parallelism in Helix.

CC @gkhanna79 @MattGal @Petermarcu

**Comment by gkhanna79** [comment]
CC @ramarag @RussKeldorph @jashook

**Comment by RussKeldorph** [comment]
I think it's a great idea to better partition the tests for distribution among nodes.  I'd still like to see us replace Xunit (#4840) someday, though.  As long as this granularity task doesn't design against a new harness, it sounds good to me.  Would love to understand more about how this is going to be achieved before it's implemented.

**Comment by wtgodbe** [comment]
This should be an intermediary step for now, where all that will change is the wrappers themselves, and not the way that we run them. Currently, we discover all of the top-level directories inside of "tests" (So JIT, CoreMangLib, baseservices, etc....) My plan right now is to change the discovery mechanism, so that instead of treating each top-level directory as the source for a wrapper, we treat each 2nd level directory as the source for a wrapper (So "JIT/Directed", instead of just "JIT").

**Comment by ramarag** [comment]
currently the top level folders are how the granularity is decided. 
The presence of *.cmd indicates a largely self contained tests [ we have run only tests, we should probably get rid of it, if it does not fit the model]. A test has it's own directory which maps to one more directory than where it was authored:

i.e -> JIT\CodeGenBringUpTests\Add1.csproj -->JIT\CodeGenBringUpTests\Add1\Add1.cmd

@wtgodbe  another heuristic   could be to find a [test].cmd  within a top level folder like JIT, go two  levels up  or till the top level folder which ever comes first and generate wrappers from that directory.

**Comment by gkhanna79** [comment]
@wtgodbe Can this be closed?

**Comment by wtgodbe** [comment]
Yes
