### ISSUE TITLE
Defining a value of type HandleRef causes an assert error

### ISSUE THREAD

**Issue by golddranks** [dotnet/coreclr#973]
Happens on Windows 8.1, with this very simple code:
Note: My CoreCLR was built from commit b736a30b25ef8944a1d622437207180c67383a01 (Date:   Thu May 7 00:30:38 2015 -0700)

```
using System;

public class Program
{
    public static void Main(string[] args)
    {
        System.Runtime.InteropServices.HandleRef handle;
        Console.WriteLine("Hello, Windows");
    }
}
```

This will cause the following error:
```
Assert failure(PID 3408 [0x00000d50], Thread: 8620 [0x21ac]): 0

CORECLR! CCompRC::LoadString + 0x521 (0x00007ff9`89e21d21)
CORECLR! CCompRC::LoadString + 0xAA (0x00007ff9`89e217e2)
CORECLR! SString::LoadResourceAndReturnHR + 0x45D (0x00007ff9`89e22981)
CORECLR! SString::LoadResource + 0x1F (0x00007ff9`89e22513)
CORECLR! GetManagedFormatStringForResourceID + 0x116 (0x00007ff9`89f93e9a)
CORECLR! GetTypeLoadExceptionMessage + 0x17D (0x00007ff9`89f95849)
<no module>! <no symbol> + 0x0 (0x00007ff9`2adfb334)
<no module>! <no symbol> + 0x0 (0x00000000`80131522)
<no module>! <no symbol> + 0x0 (0x0000004e`7a9968f0)
<no module>! <no symbol> + 0x0 (0x0000004e`7a996f20)
    File: c:\users\user\documents\repo\coreclr\src\utilcode\ccomprc.cpp, Line: 842 Image:
C:\Users\user\Documents\Repo\coreruntime\CoreRun.exe
**** MessageBox invoked, title 'CoreRun.exe - Assert Failure (PID 3408, Thread 8620/21ac)        ' *
***
  0

CORECLR! CCompRC::LoadString + 0x521 (0x00007ff9`89e21d21)
CORECLR! CCompRC::LoadString + 0xAA (0x00007ff9`89e217e2)
CORECLR! SString::LoadResourceAndReturnHR + 0x45D (0x00007ff9`89e22981)
CORECLR! SString::LoadResource + 0x1F (0x00007ff9`89e22513)
CORECLR! GetManagedFormatStringForResourceID + 0x116 (0x00007ff9`89f93e9a)
CORECLR! GetTypeLoadExceptionMessage + 0x17D (0x00007ff9`89f95849)
<no module>! <no symbol> + 0x0 (0x00007ff9`2adfb334)
<no module>! <no symbol> + 0x0 (0x00000000`80131522)
<no module>! <no symbol> + 0x0 (0x0000004e`7a9968f0)
<no module>! <no symbol> + 0x0 (0x0000004e`7a996f20)

c:\users\user\documents\repo\coreclr\src\utilcode\ccomprc.cpp, Line: 842

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
C:\Users\user\Documents\Repo\coreruntime\CoreRun.exe

********
```

Substituting HandleRef with any other struct defined in InteropServices, e.g. GCHandle, makes the program work as intended.

**Comment by jkotas** [comment]
This assertion failure means that you are missing mscorrc.dll or mscorrc.debug.dll in your CoreCLR copy. The runtime is trying to print an error, but it is not able to find message to print. I have submitted PR to update the assertion failure message - #975.

The error that it is trying to print is that HandleRef is "could not load type System.Runti
me.InteropServices.HandleRef". HandleRef is not included in .NET Core. You need to build against .NET Core reference assemblies to only use what is included in .NET Core:  https://github.com/dotnet/coreclr/blob/master/Documentation/get-dotnetcore-windows.md are the raw instructions, https://github.com/dotnet/coreclr/blob/master/Documentation/get-dotnetcore-dnx-windows.md are the simpler instructions on top of dnx.

**Comment by golddranks** [comment]
Thank you, it was about the missing mscorrc.debug.dll. When #975 gets merged, this kind of confusion shouldn't happen any more :)
