### ISSUE TITLE
Debugging is broken on macOS Sierra (10.12.4 Beta)

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#9730]
1. Install latest beta version of MacOS
2. Install .NET Core SDK, VS Code, and the C# extension, and try to debug

Result:
RegisterForRuntimeStartup will send failures back to the debugger call back with HRESULT E_INVALIDARG. The dbgshim logging isn't very helpful, it just has:

    {0x41e81-0x10b2f85f0} TRACE [PROCESS] at InvokeStartupCallback.1716: CreateProcessModules failed for pid 29295

**Comment by gregg-miskelly** [comment]
It looks like the issue is that the output from vmmap changed, so the sscanf line fails to parse it. Example line that it fails to parse:

    __TEXT                 00000001022aa000-00000001025d1000 [ 3228K  2652K     0K     0K] r-x/rwx SM=COW          /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/libcoreclr.dylib

The vmmap command executed is `/usr/bin/vmmap -interleaved 30184 -wide` (where 30184 is the process id of the target process.

**Comment by gregg-miskelly** [comment]
CC @lt72 @noahfalk @mikem8361

**Comment by mikem8361** [comment]
Fixed PR #10078
