### ISSUE TITLE
JIT.Performance.CodeQuality.Serialization.Serialize.Serialize failing

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#9733]
The JIT.Performance.CodeQuality.Serialization.Deserialize.Deserialize and JIT.Performance.CodeQuality.Serialization.Serialize.Serialize tests are failing with 
`Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'xunit.performance.core, Version=1.0.0.40, Culture=neutral, PublicKeyToken=67066efe964d3b03'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040 (FUSION_E_REF_DEF_MISMATCH))`

**Comment by janvorli** [comment]
They fail on Ubuntu starting with build https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/2806/

**Comment by janvorli** [comment]
CC: @gkhanna79

**Comment by gkhanna79** [comment]
@pgavlin Can you PTAL as it appears to have commenced from your PR?

**Comment by AndyAyersMS** [comment]
This is an issue caused by CoreFX update. See #9733.

**Comment by gkhanna79** [comment]
@AndyAyersMS the link you shared is for this issue itself. Which CoreFX update issue are you referring to?

**Comment by AndyAyersMS** [comment]
Ah, sorry, there are notes on this over in #9729.

**Comment by brianrob** [comment]
CI should be unblocked now that #9741 is merged.  I'll follow-up on re-enabling these tests.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/coreclr/pull/9749 fixes this issue
