### ISSUE TITLE
Project.json file is not equal to the explanations.

### ISSUE THREAD

**Issue by Rvhappen** [dotnet/coreclr#9735]
The explanation of the "UsingYourBuild.md" documentation chapter 3, is inaccurate and misleading. A project.json file is being referenced, but the file misses the crucial parts, like the runtimes. In my case, I got this far, but don't know how to continue. I really want to get it working.

The more important note is that I have to copy the project.json file, while the file has a line: 
>  "Microsoft.NETCore.App": "2.0.0-beta-001494-00",

But if I read the explanation well the line should be:
> "Microsoft.NETCore.Runtime.CoreCLR": "1.2.0-beta-24528-0"

So I tried both scenario's. With of course the editing of the version. I guessed it would be the second line, Microsoft.NETCore.Runtime.CoreCLR. If I add it with the right version, it finds a dependency which works. Except, it only includes: Microsoft.NETCore.Jit (2.0.0-beta-25120-0) <-- this is my version. 
With only the Jit, I'm not able to use any System classes. Can anyone tell me what's wrong and right? And/Or maybe edit the file? Thanks

**Comment by weshaggard** [comment]
The reference project.json was updated by @jkotas with https://github.com/dotnet/coreclr/commit/ec305062fa351ea9b03fc687b985ce007bf81aac at which point it is no longer well suited for the "UsingYourBuild.md" steps. 

I'm looking into updating the instructions based on the latest .NET Core 2.0 tooling that we have dogfooding instructions for at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md. Hopefully I will be able to work these out today and update the steps. Thanks for pointing out that they are outdated.

cc @vancem

**Comment by weshaggard** [comment]
Please have a look at the updated instructions at https://github.com/dotnet/coreclr/pull/9743 and give them a try.

**Comment by Rvhappen** [comment]
Thanks for picking this up so fast. I'm gonna continue tomorrow! I'll let you know.

**Comment by Rvhappen** [comment]
Your tutorial is clear for me indeed now.

One note, in the Dogfooding file you now have this:

> Create a new project
> 
> Create a new folder for your app
> Ensure you have a "2.0.0-*" CLI installed on your path. You can check with dotnet --info.
> Create project file by running dotnet new

The last sentence "Create project file by running dotnet new" is not working with the 2.0, as stated in the UsingYourBuild it should be dotnet new console I guess.

Thank you very much for being so responsive.

**Comment by weshaggard** [comment]
Good to hear and thanks for pointing out the docs are outdated.
