### ISSUE TITLE
Unable to find an entry point named 'EventSetInformation' in DLL 'advapi32.dll'.

### ISSUE THREAD

**Issue by jakesays** [dotnet/coreclr#974]
I receive this error when running an application written against .net 4.6, while running on windows 7.
Apparently EventSetInformation is windows 8+ only.

4.6 was installed along with VS 2015 RC.

Entire stack: 

 	[Managed to Native Transition]	
	mscorlib.dll!System.Diagnostics.Tracing.EventProvider.SetInformation(Microsoft.Win32.UnsafeNativeMethods.ManifestEtw.EVENT_INFO_CLASS eventInfoClass, void* data, int dataSize)	Unknown
 	mscorlib.dll!System.Diagnostics.Tracing.EventSource.Initialize(System.Guid eventSourceGuid, string eventSourceName, string[] traits)	Unknown
 	mscorlib.dll!System.Diagnostics.Tracing.EventSource.EventSource(System.Diagnostics.Tracing.EventSourceSettings settings, string[] traits)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TplEtwProvider.TplEtwProvider()	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskCompletionSource<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskCompletionSource<System.__Canon>.SetResult(System.__Canon result)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperationTaskSource<object>.SetResult(object result)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeCompletions()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame frame)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame frame)	Unknown
 	PresentationFramework.dll!System.Windows.Application.RunDispatcher(object ignore)	Unknown
 	PresentationFramework.dll!System.Windows.Application.RunInternal(System.Windows.Window window)	Unknown
 	PresentationFramework.dll!System.Windows.Application.Run(System.Windows.Window window)	Unknown
 	PresentationFramework.dll!System.Windows.Application.Run()	Unknown
 	CrashTest.exe!CrashTest.App.Main()	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.AppDomain.ExecuteAssembly(string assemblyFile, System.Security.Policy.Evidence assemblySecurity, string[] args)	Unknown
 	Microsoft.VisualStudio.HostingProcess.Utilities.dll!Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	Unknown

**Comment by vancem** [comment]
If you are viewing this in the debugger, There a good chance this is by design.    This exception is caught and swallowed on win7 (just hit go).    If it actually crashes that is a problem.   

Note that the OS group has assured us that Win7 will be patched to include this API soon (within months), so that even the exception will not happen at that point

**Comment by jakesays** [comment]
I have a sample app that doesn't crash outside the debugger but does inside. However I have a larger app that crashes regardless. I'm using roslyn, and I'm pretty sure it's related to the ETW logging roslyn is using.

**Comment by jakesays** [comment]
Ok so it appears you are correct. When I first discovered this my app crashed, so I ran it in the debugger, which gave me this error. Turns out the crash is due to a xaml error.

The missing method exception was foolin' me!

I'm going to close it.

**Comment by JamesZhengRuqing** [comment]
May I know if this is fixed? Which .Net framework update I need for windows 7?

**Comment by karelz** [comment]
@JamesZhengRuqing depends on what you mean by "this" ... the original reporter doesn't have the problem anymore.
If you're seeing similar symptoms, it would be best to file a new bug with repro and additional information.

**Comment by karelz** [comment]
Also note, that CoreCLR/CoreFX GitHub repos are not for .NET Framework bugs - use VS Feedback tool for that.
