### ISSUE TITLE
Make use of new init-docker.sh script from buildtools in order to help stabilize builds 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/coreclr#9740]
This script (added as part of https://github.com/dotnet/core-eng/issues/437) centralizes the common Docker initialization work that all builds should be performing such as cleaning up images/containers, logging the version of docker being used, and pulling the image the build will use.  The most important part, is that the logic to pull the image will retry upon failure.  The builds have been known to fail occasionally because of a network hiccup while pulling images.  This script will help alleviate this problem.

CoreFX already does this - https://github.com/dotnet/corefx/commit/b51505e368f3eaac0f77d6c03965a3026b87fa3a.  

CC @gkhanna79

**Comment by gkhanna79** [comment]
@wtgodbe Is this done with the checked in build definition changes?

**Comment by wtgodbe** [comment]
Yes, closing
