### ISSUE TITLE
[x86/Linux] Build error: "System.Globalization.Native.so has undefined dependencies"

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#9762]
From clean x86/rootfs and CoreCLR source. I get below build failure.
Prepared RootFS with
```
sudo ROOTFS_DIR=$ROOTFS_X86 ./cross/build-rootfs.sh x86 xenial lldb3.8
```
where `$ROOTFS_X86` is pointing to some folder, and then
```
ROOTFS_DIR=$ROOTFS_X86 ./build.sh x86 debug cross clang3.8 skipnuget
```

Error:
```
Verifying System.Globalization.Native dependencies
Undefined symbol(s) found:
 _ZSt7nothrow,
 __gxx_personality_v0,
 _ZSt20__throw_length_errorPKc,
 _ZNSsC1Ev,
 _ZNSaIcED2Ev,
 _ZNKSs5c_strEv,
 _ZdlPv,
...
(and more list of symbols)
Verification failed. System.Globalization.Native.so has undefined dependencies. 
These are likely ICU APIs that need to be added to icushim.h.
src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/build.make:354: 
recipe for target 'src/corefx/System.Globalization.Native/System.Globalization.Native.so' failed
```
am I missing something?

**Comment by seanshpark** [comment]
CC @parjong

**Comment by seanshpark** [comment]
@janvorli , `corefx/System.Globalization.Native/CMakeLists.txt` file runs `verify-os.sh` that I'm not sure it will verify if it's 32bit .so file, as for x86/Linux build, in x64 system. Do you know how to make it work? There was no problem as of today in my office but showed up with fresh cloning with another pc.

**Comment by janvorli** [comment]
@seanshpark I don't understand why the issue has surfaced now. There were no changes in this area recently. The test just runs `ldd -r System.Globalization.Native.so` to get a list of unresolved symbols. Could you please try to copy the System.Globalization.Native.so file to a x86 linux and run the same command over there to see if the problem is that the ldd doesn't work as expected during the cross build or if there is some real problem with the .so?

**Comment by seanshpark** [comment]
> Could you please try to copy the System.Globalization.Native.so file to a x86 linux

@janvorli , thank you. I've skipped the error line in the build script and  with the result binary it runs ok in x86 machine. And, I've prepared another clean x64(Ubuntu 16.04 VM) machine, today, and it works ok. So I think my `ldd` command could be the reason.

**Comment by seanshpark** [comment]
Solved this problem with 
```
sudo apt-get install lib32stdc++6
```
`libstdc++.so.6` was not installed in the first place.
