### ISSUE TITLE
"dotnet new" changed in .netcore 2.0

### ISSUE THREAD

**Issue by Rvhappen** [dotnet/coreclr#9764]
The updated documentation for the .netcore 2.0 is great. But, the 'dotnet new' command is not working as before. Now I'm using 'dotnet new console' which creates a WORKING console application. Which is only executable from the console as well. There is no way to open this in Visual studio. My goal is to add a local reference (dll) to the project, but I have no clue how I should do this now. Is the best way to create a whole new nuget package for this? Any help would be appreciated.

**Comment by benaadams** [comment]
Might want to open this issue in dotnet cli https://github.com/dotnet/cli
