### ISSUE TITLE
Error running crossgen with 1.1.1 - mismatched assembly definitions

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/coreclr#9776]
I'm trying to use the crossgen tool to prepare ASP.NET Core bits for our upcoming release. While trying to crossgen one of our assemblies, `Microsoft.AspNetCore.Diagnostics`, I'm running into the following error:

> Could not load file or assembly 'System.Diagnostics.StackTrace, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Repro**

Here's a minimal project:
[sample.zip](https://github.com/dotnet/coreclr/files/800567/sample.zip).  The same error happens with Microsoft.AspNetCore.Diagnostics, this minimal repro has a smaller dependency graph.

1. Download repo to C:\tmp\crossgen\
1. [Download](https://dotnetcli.blob.core.windows.net/dotnet/release/1.1.0/Binaries/Latest/dotnet-win-x64.latest.zip)  Microsoft.NETCore.App 1.1.1 Extract to  C:\tmp\crossgen\
1. [Download](https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR/1.1.1) runtime.win7-x64.microsoft.netcore.runtime.coreclr v1.1.1. Extract the tools/crossgen.exe file into C:\tmp\crossgen\shared\Microsoft.NETCore.App\1.1.1\
1. Run `shared\Microsoft.NETCore.App\1.1.1\crossgen.exe @crossgen.rsp` with these arguments

    ```
     /Platform_Assemblies_Paths shared\Microsoft.NETCore.App\1.1.1\ 
     /ReadyToRun 
     /in sample\bin\Release\netstandard1.3\sample.dll
    ```

**Details**
As you'll see in sample.zip above, the assembly (`sample\bin\Release\netstandard1.3\sample.dll`) I'm trying to crossgen was compiled with a package reference to System.Diagnostics.StackTrace/4.3.0.

This means sample.dll is compiled with a reference to `System.Diagnostics.StackTrace, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`.

The identity version of `System.Diagnostics.StackTrace.dll` in Microsoft.NETCore.App 1.1.1 is `4.0.1.0`.

cc @javiercn @weshaggard @gkhanna79 @danmosemsft

**Comment by gkhanna79** [comment]
Crossgen is giving the right message - it sees a reference to 4.0.2.0 version but finds version 4.0.1.0 in the specified path list.

If System.Diagnostics.StackTrace/4.3.0 package is not part of 1.1.1, then you cannot simply use NETCore 1.1.1 to compile sample.dll as it seems that package is not part of .NET Core 1.1.1.. You will need to specify the path to the System.Diagnostics.StackTrace/4.3.0 package as well, ahead of .NET Core 1.1.1 so that the correct version is seen for compilation.

**Comment by natemcmaster** [comment]
Aside: I get the same error if I use `/Trusted_Platform_Assemblies` and list each assembly from sharedfx.

So, in a nutshell, crossgen's argument `/App_Path` doesn't take precedence over `/Platform_Assemblies_Paths`? I must be missing the semantics of each argument. IIUC corehost prefers assemblies next to the entry assembly (in the app base path) over those found in shared framework. But it seems crossgen is doing the opposite here.

**Comment by gkhanna79** [comment]
Crossgen has it is own semantics - not to be interchanged/confused with corehost. Platform_Assemblies_Paths takes semi-colon delimited set of paths. Pass the path to the package first and then .NET Core 1.1.1.

**Comment by natemcmaster** [comment]
Ok, thanks for the help @gkhanna79.

**Comment by jnevins-gcm** [comment]
do you think it's reasonable that after 2+ (3+?) years working on dnx/dotnetcore/netstandard/netstandard.library/etc, you still can't make basic assembly referencing work? I can reproduce this by creating a solution in VS 2017 with a 4.6.1 exe and a netstandard 1.3 dll, referencing the 1.3 dll from 4.6.1 in the ide, adding a reference to and using System.Diagnostics.StackTrace package in the 1.3 dll. That's it.
