### ISSUE TITLE
CI error "MSB0001: Internal MSBuild Error: Environment variable name or value is too long."

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#9793]
See https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_windows_nt_prtest/2909/console

> 06:57:53 Starting Build at  6:57:53.56
06:57:53 BUILD: Commencing CoreCLR Repo build
06:57:53 BUILD: Checking prerequisites
06:57:56 BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\VsDevCmd.bat"
06:58:02 Installing .NET Version Manager to C:\Users\dotnet-bot\.dnx\bin
06:58:02 Creating destination folder 'C:\Users\dotnet-bot\.dnx\bin' ... 
06:58:02 Installing 'dnvm.ps1' to 'C:\Users\dotnet-bot\.dnx\bin' ... 
06:58:02 Installing 'dnvm.cmd' to 'C:\Users\dotnet-bot\.dnx\bin' ... 
06:58:02 Adding C:\Users\dotnet-bot\.dnx\bin to Process PATH
06:58:02 Adding C:\Users\dotnet-bot\.dnx\bin to User PATH
06:58:06 Installing dotnet cli...
06:58:13 Restoring BuildTools version 1.0.27-prerelease-01209-01...
06:58:13 Initializing BuildTools ...
06:58:52 Updating CLI NuGet Frameworks map...
06:58:52 Done initializing tools.
06:58:52 Running: D:\j\workspace\x86_checked_w---b3a226f6\Tools\dotnetcli\dotnet.exe D:\j\workspace\x86_checked_w---b3a226f6\Tools\run.exe D:\j\workspace\x86_checked_w---b3a226f6\config.json build -Project=D:\j\workspace\x86_checked_w---b3a226f6\build.proj -generateHeaderWindows -NativeVersionHeaderFile="D:\j\workspace\x86_checked_w---b3a226f6\bin\obj\_version.h" -BuildOS=Windows_NT -BuildType=Checked -BuildArch=x86
06:58:52 Running: D:\j\workspace\x86_checked_w---b3a226f6\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false  /l:BinClashLogger,Tools/net45/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  D:\j\workspace\x86_checked_w---b3a226f6\build.proj /p:__BuildType=Checked /p:__BuildArch=x86 /p:__BuildOS=Windows_NT  /t:GenerateVersionHeader /p:GenerateVersionHeader=true /p:NativeVersionHeaderFile=D:\j\workspace\x86_checked_w---b3a226f6\bin\obj\_version.h       
06:59:00 
06:59:00 Unhandled Exception: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Environment variable name or value is too long.
06:59:00 =============
06:59:00 System.ArgumentException: Environment variable name or value is too long.
06:59:00    at System.Environment.SetEnvironmentVariable(String variable, String value)
06:59:00    at Microsoft.Build.BackEnd.InProcNode.HandleShutdown(Exception& exception)
06:59:00    at Microsoft.Build.BackEnd.InProcNode.Run(Exception& shutdownException)
06:59:00 
06:59:00  ---> System.ArgumentException: Environment variable name or value is too long.
06:59:00    at System.Environment.SetEnvironmentVariable(String variable, String value)
06:59:00    at Microsoft.Build.BackEnd.InProcNode.HandleShutdown(Exception& exception)
06:59:00    at Microsoft.Build.BackEnd.InProcNode.Run(Exception& shutdownException)
06:59:00    --- End of inner exception stack trace ---
06:59:00    at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
06:59:00    at Microsoft.Build.BackEnd.InProcNode.Run(Exception& shutdownException)
06:59:00    at Microsoft.Build.BackEnd.NodeProviderInProc.InProcNodeThreadProc()
06:59:00    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
06:59:00    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
06:59:00    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
06:59:00    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
06:59:00    at System.Threading.ThreadHelper.ThreadStart()
06:59:01 Command execution failed with exit code -532462766.

**Comment by akoeplinger** [comment]
The ghprb Jenkins plugin for triggering pull request builds exports the PR title and description as environment variables. Since your PR description in #9792 is quite long (most is hidden in `<details>`) you might be running into a limit.

FWIW this caused us enough problems in Mono that we now clear those variables at the start of the build (unfortunately there's no option to switch the exporting off in the ghprb plugin).

/cc @mmitche

**Comment by mmitche** [comment]
@akoeplinger Unfortunately people also rely on this to pull data to other systems.  Are we hitting a .NET limit, rather than a system limit?  I'm guessing the title was longer than 4096?

**Comment by benaadams** [comment]
Is it possible to truncate the description? Will make sure I do large summaries in follow up posts in future

**Comment by mmitche** [comment]
@benaadams Probably.  It might be worth looking into why .NET fails while Windows doesn't seem to care.

**Comment by danmosemsft** [comment]
[MSDN does say ](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682653(v=vs.85).aspx) the value can't be more than 32767 chars -- @mmitche you're saying this was successfully set in the environment before MSBuild starts, hence it's odd?

**Comment by mmitche** [comment]
Yeah.  The implication here is that somehow the .NET limit seems to be lower than the OS limit.

**Comment by danmosemsft** [comment]
Could be but I guess the real problem here is a system trying to pass > 32KB of data in an environment variable..

**Comment by gkhanna79** [comment]
@danmosemsft Can you please route this to someone on CoreFX/Msbuild to take a look and assign appropriate mileston?

**Comment by danmosemsft** [comment]
I opened https://github.com/dotnet/corefx/issues/16766 separately for clarity.

IMO a bigger issue is passing unlimited data as env vars. @mmitche up to you whether you open an issue against CI for that.

**Comment by mmitche** [comment]
@danmosemsft I don't think this is a CI bug.  In order for it to be a CI bug, the Java JDK would have to have the same bug as https://github.com/dotnet/corefx/issues/16766.  If it was truly unlimited it should fail there first.  My take is that .NET is incorrectly limiting the size of the environment block.
