### ISSUE TITLE
Missing mscordacwks and mscordbi?

### ISSUE THREAD

**Issue by poizan42** [dotnet/coreclr#98]
The clrdbg solution refers to mscordacwks.vcxproj and mscordbi.vcxproj but they seem to be missing.

**Comment by AlexGhiondea** [comment]
@rahku can you take a look?

**Comment by rahku** [comment]
which clrdbg solution are you referring to? I don't see any by that name

**Comment by poizan42** [comment]
This one: https://github.com/dotnet/coreclr/blob/master/src/debug/clrdbg.sln

**Comment by rahku** [comment]
the solution & proj files that are checked into source tree do not build ...these are old files which were used for source browsing in VS before we moved to cmake based build system. These should get deleted soon maybe in next cleanup.

**Comment by rahku** [comment]
only refer to solution files that are generated by cmake for now...ignore the ones checked into source tree.
