### ISSUE TITLE
Math.Atan2 does not follow IEEE 754 for all inputs

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#9806]
The IEEE 754 spec indicates:
* atan2(±∞, −∞) is ±3π/4
* atan2(±∞, +∞) is ±π/4.

However, the current implementation returns NaN for the specified inputs.

**Comment by danmosemsft** [comment]
cc @dcwuser also

**Comment by dcwuser** [comment]
For reference, here is the spec: https://www.csee.umbc.edu/~tsimo1/CMSC455/IEEE-754-2008.pdf. The required special cases for atan2 are on page 45. I have written a test program for all of them, and the ones listed in this bug are the only ones not satisfied. (Caveat: while I was careful to distinguish +0 from -0 on input, I used a comparator that regards them as equal on output.)

Two points:

A. It wouldn't hurt for us to fulfill the spec.

B. Of all the special cases listed in the spec, these are the least important and most debatable. To derive these cases, you have to regard separate infinities as equal, and we certainly don't do that in other contexts, for example we say -inf/+inf = NaN, not -inf/+inf = -1.

So I would say: if this is easy to fix, and the fix doesn't impact performance, and we have have cycles, let's fix it. But if any of those conditions are violated, let's not.

**Comment by gkhanna79** [comment]
CC @AlexGhiondea

**Comment by tannergooding** [comment]
Self assigning since this is fixed by https://github.com/dotnet/coreclr/pull/10295

**Comment by stephentoub** [comment]
Reopening to track test fixes

**Comment by tannergooding** [comment]
Fixed with https://github.com/dotnet/corefx/pull/17217
