### ISSUE TITLE
Enable FEATURE_SIMD and FEATURE_AVX_SUPPORT for System V

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#983]
@LLITCHEV See PR # 981, which enables it for amd64 windows.

**Comment by pgavlin** [comment]
Is there any particular reason that SIMD isn't enabled on Linux yet? AFAIK it shouldn't affect the CC-related code unless we want to project Vector<T> to `__m128`/`__m256` (for SSE/AVX, respectively). Note that the projection to `__m256` may require some invasive changes, as these values are passed in up to four vector registers and require proper handling of the SSEUP classification.

**Comment by CarolEidt** [comment]
I don't know if Lubo has done any more detailed analysis on this, but even apart from projecting these types, we may run into unexpected issues where we have inadvertently made assumptions about how these are passed. I don't think it would be too hard to try enabling it, and then we would have a better idea about whether there are any issues, and can then estimate the cost of addressing them.

**Comment by stephentoub** [comment]
(For reference, it'd be great to get this fixed by RC2 so that code using the corefx System.Numerics.Vectors.dll library isn't negatively affected.  Thanks!)

**Comment by benaadams** [comment]
This will directly effects the performance of the [AspNet Kestrel](https://github.com/aspnet/KestrelHttpServer) server on Linux when using coreclr which heavily makes use of System.Numerics.Vectors e.g. [MemoryPoolIterator](https://github.com/aspnet/KestrelHttpServer/blob/52f4fa91e3f68c5f8a2e726432d85806024fd834/src/Microsoft.AspNet.Server.Kestrel/Infrastructure/MemoryPoolIterator2.cs#L246) for request parsing.

/cc @davidfowl

**Comment by CarolEidt** [comment]
FEATURE_SIMD is now enabled. I am currently working on enabling AVX2 support, which is the other half of #983

**Comment by benaadams** [comment]
Excellent! Thank you very much :smile:
