### ISSUE TITLE
failed to locate libcoreclr with error libcoreclrpal.so

### ISSUE THREAD

**Issue by AlexZeitler** [dotnet/coreclr#984]
I did  the following on Ubuntu 14.04 x64 Desktop

```
dnvm upgrade -u
dnvm install -r coreclr -arch x64 latest -u
dnvm use 1.0.0-beta5-11749 -r coreclr
```
No errors until now.

running `dnx` or `dnu` results in 
```
failed to locate libcoreclr with error libcoreclrpal.so: cannot open shared object file: No such file or directory
```

**Comment by janvorli** [comment]
It looks like the dnx/dnu uses old managed assemblies that referred to the libcoreclrpal.so that no longer exists.
@ellismg, @ericstj do you have any idea how can that happen?

**Comment by shahid-pk** [comment]
I does not happen for me on the same platform. Of course dnu on coreclr fails but with a different exception which is a known issue. But dnx on coreclr works fine.

**Comment by ellismg** [comment]
The bits we drop to DNX have not been updated to undo the PAL split but everything should be consistent (e.g. They should still have libcoreclrpal in their package).

I have also seen this error in cases where libssl-dev is not installed and the message from dlopen is just confusing.

**Comment by ellismg** [comment]
@AlexZeitler Are you still hitting this?  Do you have the `libunwind8` package installed?

**Comment by AlexZeitler** [comment]
@ellismg Yes, I've still been hitting this. `libunwind8` has not been installed. After installing it, I can execute `dnu` and `dnx` without errors.

Thank your very much! :+1:

**Comment by zhangxin511** [comment]
I think this issue raise again, I have encountered this using both Ubuntu desktop  14.04 and centos7.
When I use 1.0.0-beta7 coreclr x64 for linux, I will get "dnu
failed to locate libcoreclr with error libunwind.so.8: cannot open shared object file: No such file or directory"

But if I switch to 1.0.0-beta7 mono linux/osx, I will not get this output.

I know how to install libunwind8 in Ubuntu, but not sure how to install it on CentOS yet so this issue is currently blocking...

**Comment by ellismg** [comment]
@zhangxin511 You can obtain libunwind8 via [EPEL](https://fedoraproject.org/wiki/EPEL) on CentOS.

**Comment by zhangxin511** [comment]
@ellismg Thank you for your quick reply! I just found you solution as well from http://stackoverflow.com/a/32571051/2388241

**Comment by draper** [comment]
This is biting me now.  I'm getting the "failed to locate libcoreclr with error libunwind-x86_64.so.8: cannot open shared object file: No such file or directory" with 1.0.0-rc1-update1 .  I can't use dnx or dnu on Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-92-generic x86_64.

**Comment by ellismg** [comment]
@draper: The precompiled dnx and dnu libraries that are downloaded when installing DNX are compiled against Ubutu 14.04 packages.  If you want to get this working there, you'll need to build the native components for both CoreCLR and CoreFX from source (check out our RC tags) and then update the versions in the `~/.dnx/runtimes/.../bin` folder.

I was looking at the packages for 12.04 and it looked liked some of the versions are older than anything we've ever built against, so there may be some work to be done to support that distro.  If you do end up having to make changes, we'd appreciate it if you could send a PR or leave a note about what you did.

I may try to try to build myself against 12.04 over the holidays if I have some downtime, but no promises.

Good luck!
