### ISSUE TITLE
Issue with System.Net.WebClient.Proxy.GetProxy

### ISSUE THREAD

**Issue by MysticRyuujin** [dotnet/coreclr#9854]
I noticed this bug while working with a Proxy Auto-Config PAC file. Basically, when using GetProxy, if I pass a relative URI (which generates an exception, which can be caught) and then continue on to pass an absolute URI, it stops processing the PAC file.

More details can be found [HERE](https://github.com/PowerShell/PowerShell/issues/3040) which is where I filed the original bug with the PowerShell team, however, the PowerShell team has since shown that it is a CoreCRL issue and asked that I open the bug report here. From that link @daxian-dbw provided a sample of CoreCRL that reproduces the issue.

Again this is assuming the use of a PAC file such as:
```
function FindProxyForURL(url, host) {
    if ( host == "www.msn.com" ) {
        return "PROXY 10.10.10.10";
    }
    else {
        return  "DIRECT";
    }
}
```

Problem code provided:

```
void Main()
{
	System.Net.WebClient client = new System.Net.WebClient();
	Uri uri_absolute = new Uri("http://www.msn.com", System.UriKind.RelativeOrAbsolute);
	Uri uri_relative = new Uri("www.msn.com", System.UriKind.RelativeOrAbsolute);
	
	Console.WriteLine(client.Proxy.GetProxy(uri_absolute).Host);
	
	try { client.Proxy.GetProxy(uri_relative); }
	catch { Console.WriteLine("Exception"); }
	
	Console.WriteLine(client.Proxy.GetProxy(uri_absolute).Host);
}
```
And the output is:
```
10.10.10.10
Exception
www.msn.com
```

It should be:
```
10.10.10.10
Exception
10.10.10.10
```

**Comment by stephentoub** [comment]
cc: @davidsh

**Comment by davidsh** [comment]
What operating system is this on?  Windows?

On Windows, .NET Core and the HTTP stack does not process PAC files itself.  The proxy detection and evaluation logic of a PAC file is handled by the operating system (WinHTTP AutoProxy Discover Service).  For the default system proxy, we do not know how to map a URI and find it's proxy.  That information is hidden in the OS HTTP stack.  While we can select the system proxy and use it, it will use the proper proxy for a URI.  But we can't retrieve that information.

That means that methods like Proxy.GetProxy(host) don't work when using the system proxy on Windows.  The methods do work if you use a custom proxy.  But for the system proxy, we "fake" the methods and only use a shim.

**Comment by davidsh** [comment]
By the way, this question really belongs in the dotnet/corefx repo.  It is not related to dotnet/coreclr at all.

**Comment by MysticRyuujin** [comment]
So just to verify I need to open this issue with corefx?

**Comment by daxian-dbw** [comment]
@MysticRyuujin both corefx and coreclr are targeting .NET Core, where the API `"WebClient.Proxy.GetProxy"` is not available. This API is only available in Full .NET. You can try opening an issue in corefx, and see how it goes.

**Comment by gkhanna79** [comment]
Closing in favor of https://github.com/dotnet/corefx/issues/16695.
