### ISSUE TITLE
JIT optimization - Perform additional constant propagation for expressions.

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#987]
Thee following two cases should  generate the same code:

public static double Run2A()
{
    return Math.Sqrt(1) + Math.Sqrt(2);
}

public static double Run2B()
{
    double res = Math.Sqrt(1) + Math.Sqrt(2);
    return res;
}

**Comment by briansull** [comment]
Resolving this old issue as I verified that it is fixed.

**Comment by AndreyAkinshin** [comment]
@briansull, great, thanks!
Could you tell me which version of .NET Core and .NET Framework will contain the fix?

**Comment by briansull** [comment]
Any current 4.7 version should contain the fix.

filever c:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
--a-- WAMD64 DLL ENU      4.7.2110.0 shp  1,129,112 08-31-2017 clrjit.dll
