### ISSUE TITLE
[Question] Mentions of 'Rotor' in the source code

### ISSUE THREAD

**Issue by mattwarren** [dotnet/coreclr#9872]
I don't know if it matters or not, but there's a few mentions of ['Rotor' in the source](https://github.com/dotnet/coreclr/search?q=Rotor&utf8=%E2%9C%93), mostly under `\src\pal\`, `\src\inc\` and `\src\vm\`. 

Should they be updated/removed or just left in there for historical reasons?

**Comment by hughbe** [comment]
What actually is Rotor? An old code-name for coreclr? Can't find it in the glossary https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/glossary.md (that should be updated!)

**Comment by mattwarren** [comment]
Rotor is the codename for the [Shared Source Common Language Infrastructure (SSCLI)](https://en.wikipedia.org/wiki/Shared_Source_Common_Language_Infrastructure) which was (sort of) the open source version of the CLR, before CoreCLR was released. There's more info on SSCLI [here](https://msdn.microsoft.com/en-us/library/cc749640.aspx) and there's even a [book available](http://blogs.tedneward.com/post/sscli-20-internals/).

So I think that any mentions of 'Rotor' in the source are just historical, but I just wanted to check

**Comment by danmosemsft** [comment]
I doubt anyone would object to removing them. In the great purging of defines etc done recently we already removed lots of "historical" stuff. Rotor hasn't been developed for ?12 years.

**Comment by danmosemsft** [comment]
If anyone wants to take this, it will likely need care. Any removing of defines or renaming identifiers can cause bugs. Comment changes are hard to get wrong of course. It would make sense to be pragmatic about any changes and make them in small commits testing as going along (unless just comments)
