### ISSUE TITLE
[Question] Cross compile for ARM on non-Debian

### ISSUE THREAD

**Issue by nick-rudh** [dotnet/coreclr#9875]
Is there any talk of creating scripts for giving non-Debian machines the ability to cross compile, like CentOS? I personally would like to be able to cross compile from my machine for an ARM based Linux device. If there is anyone who has done this already would also be interested in their steps.

Thanks

**Comment by justmehlc76** [comment]
Tee hee

**Comment by danmosemsft** [comment]
@janvorli

**Comment by BruceForstall** [comment]
We build for Ubuntu arm/arm64 using Docker on Ubuntu x64. I don't believe there have been cross-OS compilation attempts, although if you can do it in Docker, that might be the answer.

I'm going to close this.
