### ISSUE TITLE
Assembly.LoadFrom should try to fall back to Assembly.Load before failing

### ISSUE THREAD

**Issue by billwert** [dotnet/coreclr#9879]
On CoreCLR, LoadFrom is prohibited from loading things that are in the TPA. This breaks certain patterns developers use for plug-in models, such as this:
```csharp
            var exePath = Assembly.GetExecutingAssembly().Location;
            exePath = exePath.Replace(Path.GetFileName(exePath), "");
            foreach(var plugin in Directory.GetFiles(exePath, "*.dll"))
            {
                var a = Assembly.LoadFrom(plugin);
                // do plugin-y things
            }
```

Instead of failing we could fall back to the Load code path, since it is all the same context anyway.

cc: @rahku

**Comment by jkotas** [comment]
Make sense to me
