### ISSUE TITLE
JIT: figure out how a noway_assert in the importer is firing

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#9891]
There are some as of yet unknown cases where [this](https://github.com/dotnet/coreclr/blob/7b8f9d6c8f5b196b8cf7da6f4c49bf4149f3e15a/src/jit/importer.cpp#L9934) `noway_assert` can fire.

The assert is there to try and ensure that if the jit is inlining a method that uses `starg` on a particular argument the jit has also decided to use a new local to represent that argument in the inlined body (rather than propagating the caller's argument expression directly into the inlinee's body). This should be guaranteed by the analysis of the inlinee done during `fgFindJumpTargets` (which notes `starg` instructions in the inline arg info) and the logic in `impInlineFetchArg`.

So far I have been unable to create a repro case. Some hypotheses below.

- There is an asymmetry in `fgFindJumpTargets` between `starg` and `ldarga` for inlinees. Abstractly both should have the same effect on how the jit propagates the arg value. However the `starg` case calls into `compMapILargNum` for inlinees, which seemingly could cause `starg` impact to be misplaced for methods with hidden arguments. The invariant in the rest of the code is that inlinee arg numbers refer to IL arguments and do not take hidden arguments into account. So far it looks like this asymmetry is harmless because we bail out of `lvaInitTypeRef` early for inlinees so the arg number is not adjusted by the call to `compMapILargNum`.
- We are seeing IL with bad `starg` numbers. We need to tread cautiously with invalid IL when evaluating an inline, because we are not sure the particular method will actually ever be called. So we tend to defer failure and perhaps this `noway_assert` is the first indication of the actual problem. Note the code in `fgFindJumpTargets` will still record properties for nonexistent args since the local table size is at least 16 entries. So for small invalid `starg` values the arg info will still record the right `starg` state (but other aspects of the var will be bogus), while for large invalid `starg` values the `starg` observation is suppressed. IL cases created with bad `starg` numbers trigger a raft of asserts, but so far I have not been able to hit this particular `noway_assert`.

Inlining for `starg` inlinees was enabled in #6572.

**Comment by AndyAyersMS** [comment]
@JosephTremoulet if you have any ideas about how this can happen, I'd love to hear them.

**Comment by JosephTremoulet** [comment]
Do you know how to get [this](https://github.com/dotnet/coreclr/blob/7b8f9d6c8f5b196b8cf7da6f4c49bf4149f3e15a/src/jit/importer.cpp#L10229) inline rejection to happen?  Seems like it should be similar cases...

**Comment by AndyAyersMS** [comment]
Think I figured this out (well at least one way to reach the bug). In the code in `fgFindJumpTargets` that prescans the method, if we see a `starg`, we do the following:
```C++
                if (varNum < lvaTableCnt)
                {
                    if (isInlining)
                    {
                        impInlineInfo->inlArgInfo[varNum].argHasStargOp = true;
                    }
```
here `varNum` is the argument number. Now it turns out that for an inlinee, `lvaTableCnt` is set over in `lvaInitTypeRef` as follows:
```C++
        lvaTableCnt = impInlineInfo->InlinerCompiler->lvaTableCnt;
```
and it is initially set to the larger of 2x the number of locals and args, or 16.

So imagine we have a caller with few/no args or locals that calls an inlineable method with more than 16 parameters. As we scan the inlinee, we may drop the `starg` observation on the floor, since the lvaTableCount is 16. If the corresponding actual argument is a constant, then `impInlineFetchArg` will return a clone of the constant rather than a temp, and we'll hit the assert when we import the inlinee and see that we got a constant back rather than a local.

Verified with the following example:
```C#
using System;

class B
{
    static int X(
        int a01, int a02, int a03, int a04,
        int a05, int a06, int a07, int a08,
        int a09, int a10, int a11, int a12,
        int a13, int a14, int a15, int a16,
        int a17, int a18, int a19, int a20)
    {
        a20 = a19;
        return a20;
    }

    public static int Main(string[] args)
    {
        int v = X(1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
            11, 12, 13, 14, 15, 16, 17, 18, 19, 20);
        return v + 81;
    }
}
```
The fix is to change the "range check" in the inlining case to be against `MAX_INL_ARGS + 1` which is the size of the `inlArgInfo` array. This value is currently fixed at 32 + 1 and we reject inlinees with more argument than this.
