### ISSUE TITLE
Enable Assembly.Load(Byte[]) in UWP/Appx

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#9912]
This is currently blocked. We should enable all NS2.0 API's in UWP that we can possibly enable. This should be able to work. It's also  being requested.

https://github.com/dotnet/coreclr/blob/68f72dd2587c3365a9fe74d1991f93612c3bc62a/src/mscorlib/src/System/AppDomain.cs#L556

@rahku @gkhanna79

**Comment by gkhanna79** [comment]
CC @rahku @kouvel

**Comment by MichalStrehovsky** [comment]
What's the expected use case for this? Load an IL assembly and start running code from it?

We will not be able to support that in a usable way on Project N without a JIT or an interpreter, neither of which are planned for UWP. Making something work in Debug configuration (when CoreCLR is used), but throw `PlatformNotSupportedException` on Retail (when we compile to native with Project N) doesn't seem like a win for anyone.

**Comment by danmosemsft** [comment]
@gkhanna79 I was wondering htis myself actually.

**Comment by gkhanna79** [comment]
Correct - this is the point I raised over email as well.

**Comment by ViktorHofer** [comment]
We have way to many issues for this. Dan closed my dup and I just closed another dup here in coreclr. Let's disucss this here on this one please.

@MichalStrehovsky:
> UWP doesn't allow a JIT. The only thing we could get to work for UWP here is that you could load types and inspect them, and then we would throw whenever you wanted to do anything interesting with them (invoking a method, creating an instance of a type, etc.). I can't come up with a customer scenario where that would be even remotely useful and it's a bunch of code bloat and test cost. It's better to just throw.

As we are also running our tests on UAP (without Project N), would it be possible to support it there? I'm not sure if with 2.1 anything will remain running in UAP instead of UAPAOT.

**Comment by jkotas** [comment]
> Making something work in Debug configuration (when CoreCLR is used), but throw `PlatformNotSupportedException` on Retail (when we compile to native with Project N) doesn't seem like a win for anyone.

It can be win for side-loaded UWP applications that do not need to pass Windows Store restrictions. We have heard asks from developers of enterprise apps who are perfectly happy to ship the "developer experience" to not artificially prohibit things like this.

**Comment by MichalStrehovsky** [comment]
> We have heard asks from developers of enterprise apps who are perfectly happy to ship the "developer experience" to not artificially prohibit things like this

I would be okay with that, but only if it's behind a switch that is off by default. A great deal of .NET Native issues we have dealt with in the past are for customers who turned on .NET Native for the first time the moment they were about to ship. I would rather not see this on the list of issues customer encounter at the last minute that causes them to slip schedules. Behavioral differences between Debug and Release builds are frustrating to deal with.

**Comment by ViktorHofer** [comment]
Exactly for these reasons we have compiler warnings / static analysis tools. When building in Debug it could emit a warning that this API is not available in Release Mode. Or as I said static analysis.

**Comment by ViktorHofer** [comment]
cc @AtsushiKan @danmosemsft

**Comment by jkotas** [comment]
> Exactly for these reasons we do have compiler warnings / static analysis tools

Agree - http://github.com/terrajobst/platform-compat.

> A great deal of .NET Native issues we have dealt with in the past are for customers who turned on .NET Native for the first time

There are number of other differences between .NET Native and CoreCLR. We have tried to conditionally mimic the .NET Native behavior in CoreCLR by adding similar roadblocks like this one in the past. We have given up on it and got rid most of them. I see the LoadFrom/LoadFile checks as last few leftovers from the abandoned effort.

**Comment by danmosemsft** [comment]
There are quite a few other `#if FEATURE_APPX` in corelib but in a quick look they seem legitimate eg related to PRI's, different unhandled error behavior, ... @jkotas are there any others you think we should remove?

**Comment by MichalStrehovsky** [comment]
> Agree - http://github.com/terrajobst/platform-compat.

That's a Roslyn analyzer - it won't give me *anything* if I download a NuGet package targeting NetStandard 2.0 and relying on the API, do my development on Debug, then switch to Release just before uploading to the Store, and find myself having to throw out everything that depends on the missing functionality. It was a really unfortunate choice putting APIs to NetStandard that we can't support everywhere, but we did it and now we need to engineer around it in a way that gives people an experience that is not completely miserable.

If we have been disabling these check, @MattWhilden would definitely want to know.

**Comment by jkotas** [comment]
> @jkotas are there any others you think we should remove?

The few checks around `Assembly.Load` are the only ones left that I am aware of.

**Comment by danmosemsft** [comment]
@safern

**Comment by MattWhilden** [comment]
I share the concerns that @MichalStrehovsky has brought up. We spent a rather large amount of effort in the run up to Win10 RTM gutting CoreCLR capability so that developers wouldn't hit surprises the first time they ship into the store. Some things we know are true about UWP developers (maybe all developers?? :-)):

- They do not expect DEBUG and RELEASE to have behavior differences
- Thus, they often never build+run in RELEASE
- Build Errors are taken care of, Warnings are largely ignored (this relates to comments by @ViktorHofer)

The most compelling argument for removing this block is presented by @jkotas but that presumes that we've accepted CoreCLR as a shipping scenario for UWP. Today, anyone publishing this way is in violation of our licensing as per: https://www.visualstudio.com/en-us/productinfo/2017-redistribution-vs. If side loading CoreCLR is the reason we're changing the behavior here, then we'll also need to do work in other places for this to be a real option.

**Comment by danmosemsft** [comment]
@joshfree thoughts about this one? There does not seem to be consensus emerging here.

**Comment by jkotas** [comment]
Shipped this way. No plans to change it.

**Comment by ViktorHofer** [comment]
Now especially with the `broadFileSystemAccess` UWP capability I believe it would help a lot of if we could make Assembly.Load work for side-loaded scenarios (Debug, non-uap, probably with a switch). That would also help us cleanup a bunch of code in buildtools as we wouldn't need to make a dedicated appx package for each test library anymore. We would build one package for test runner with the broaderFileSystemAccess capability which then can load the test assemblies dynamically.

**Comment by jkotas** [comment]
@ViktorHofer This limitation exists because of the AOT compilation. `Load(byte[])` would be still unsupported in uapaot even if we have done this.

**Comment by ViktorHofer** [comment]
Yes I understood that limitation for uapaot.

**Comment by jkotas** [comment]
So how would the uapaot tests work? You would still need to create a package for each test library, no?
