### ISSUE TITLE
Enable x64 mixed-mode debugging

### ISSUE THREAD

**Issue by tarekgh** [dotnet/coreclr#9919]
@PrashanthIBM commented on [Tue Aug 02 2016](https://github.com/dotnet/corefx/issues/10524)

Hi,

I am using a .Net Core Console App using Visual Studio 2015 update 2 on windows machine. I am using a package "pack1"(managed code) in this console application which in turn calls native / c code dll. I am able to step into pack1 code, but i am not able to step into my native code.

Tried giving symbol path to native code pdb file , enabled native and managed code compatibility option,tried putting breakpoint into the native c source code directly, also tried to step into c code from managed code, but none of them seem to work.

Can some one please help me with this / point to any documentation ?

sample Project.json file :

{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "defines": [ "DEBUG" ]
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    },
    "pack1": "1.0.0.0"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },
  "configurations": {    "debug": { 
    }
  }
}

Thanks and Regards,
Prashanth

---

@joshfree commented on [Tue Aug 02 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-236978598)

@tzwlai can you help route?

---

@tzwlai commented on [Tue Aug 02 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-236988851)

@caslan, could you help with this issue please?

---

@PrashanthIBM commented on [Tue Aug 02 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-237153758)

does any one as any idea about how to solve this issue ?.
I am really struck and appreciate the help ASAP.

---

@clrjunkie commented on [Wed Aug 03 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-237175885)

@PrashanthIBM 

Try this approach: https://github.com/aspnet/Tooling/issues/368

---

@PrashanthIBM commented on [Wed Aug 03 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-237187208)

@gregg-miskelly can you please help 

---

@PrashanthIBM commented on [Thu Aug 04 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-237491562)

Any updates ?

---

@gregg-miskelly commented on [Mon Aug 08 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-238314570)

@PrashanthIBM: The .NET Core project system doesn't currently expose an option to do native-only debugging. So, like @clrjunkie said, you will need to do something similar to the approach I suggested in https://github.com/aspnet/Tooling/issues/368. Here are those steps tweaked for apps using dotnet.exe to host:
1. Right click on the solution, Add Existing Project
2. Open 'dotnet.exe'. This is normally installed to 'C:\Program Files\dotnet\dotnet.exe'.
3. You should now see another node in solution explorer for dotnet.exe. Right click it to bring up project properties:
   - Change the working directory to be what you want
   - Change the arguments to be the path to your built dll
4. Change the exe project to your startup project
5. RECOMENDED: Go to Tools->Options->Projects and Solutions->Build and Run, uncheck 'Only build startup projects and dependcies on Run'

@sayedihashimi it might be useful to add an option to the project system to enable this in the future.

---

@per-samuelsson commented on [Wed Aug 17 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-240399730)

@gregg-miskelly 

Really appreciate the time you spend here, trying to help out! :+1:  But I _think_ what @PrashanthIBM is asking for is a debugging experience where you could step (e.g. F11) from managed code into native code (and back). And what you describe here and in https://github.com/aspnet/Tooling/issues/368 is how to debug native code in a managed process, but in _isolation_.

If my assumptions are correct, I'm also trying just like @PrashanthIBM to find a way to accomplish this kind of mixed mode / interop debugging, but with no success.

I remember back in pre-dotnetcore era, VS would allow mixed mode debugging really early in the life of .NET Framework 1.0 (back in 2000), but that this was only supported for a long period of time (years) for 32-bit processes, not 64-bit ditos. And then this got fixed a few years ago, but now with dotnetcore, it seem not to be possible any longer.

The gain of mixed mode / interop debugging is of course to see a full stack, and be able to debug longer sequences without the hazzle of having to attach/detach separate debuggers for every transition. But maybe this is not at all supported for CoreCLR + native at this point?

---

@gregg-miskelly commented on [Wed Aug 17 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-240465755)

@per-samuelsson you are correct -- coreclr doesn't support x64 mixed mode debugging at the moment.
@tzwlai should we port this issue to CoreCLR and have it track enabling x64 mixed mode?

---

@per-samuelsson commented on [Wed Aug 17 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-240629465)

> @per-samuelsson you are correct -- coreclr doesn't support x64 mixed mode debugging at the moment.

Sad to hear. But thanks for giving a clear answer! :+1:  

---

@danmosemsft commented on [Thu Nov 10 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-259873135)

@karelz perhaps this should be a feature request against the CLR debugging team, their issues are in coreclr right?

---

@karelz commented on [Thu Nov 10 2016](https://github.com/dotnet/corefx/issues/10524#issuecomment-259886042)

@noahfalk @lt72 do you track such request in https://github.com/dotnet/coreclr repo?

**Comment by adityamandaleeka** [comment]
Renamed to more closely match what the request is.

**Comment by gregg-miskelly** [comment]
This issue can be resolved as fixed I believe. See https://github.com/dotnet/coreclr/pull/8603

**Comment by noahfalk** [comment]
Done - closed as fixed : )

If it turns out there is some element that still isn't working just let us know and we can re-open.
