### ISSUE TITLE
Instructions for testing on Linux need work

### ISSUE THREAD

**Issue by pkukol** [dotnet/coreclr#9944]
The "Building and running tests on Linux, OS X, and FreeBSD" page should be updated and fixed; for example, it says to mount "/media/corefx" but never uses it for anything, some of the paths are wrong, etc.

**Comment by gkhanna79** [comment]
@wtgodbe Can you please look into this?

**Comment by RussKeldorph** [comment]
Two other suggestions:
- Remove the requirement of having a CoreFx build on Windows (no longer required); probably related to @pkukol's comment.
- (optional) Provide instructions for pulling coreclr/test and corefx binaries from the CI rather than enlisting and building (esp. on Windows).
