### ISSUE TITLE
GC: Two optimizations worth considering

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#9963]
1. After GC (no matter which generation), all garbage objects with finalizer should be moved to heap zone of generation 0. Thus, these objects may be collected next generation 0 GC after their finalizers are called.
After all, they are more likely to be garbage than to be alive after finalized.
See https://github.com/dotnet/coreclr/issues/1856
Although C# discourage people to use finalizer, but sometimes we have to use it and want to pay less for it.

2. If some objects are found to be only referenced by local variables on the stack during GC period, their generation should not be increased, because they are more likely to become garbage soon.

If these two optimizations above are done, the garbage living time would be less, and memory usage could be reduced.

**Comment by jkotas** [comment]
This looks like a variation on the other suggestions you have opened.

As Vance said in the other issue: Ideas for improvements are considerably more valuable if they have (ideally real world) data that argues that the improvement is very significant. It would be useful if you can support your suggestions with real world data that show the estimated improvement.
