### ISSUE TITLE
None of the build badges are working

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#9968]
https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/OfficalAndDailyBuilds.md

They all point to an old server, hence they all show up as "inaccessible".

**Comment by danmosemsft** [comment]
@stephentoub seems fixed..

**Comment by stephentoub** [comment]
@danmosemsft, the problems I called it here https://github.com/dotnet/coreclr/pull/10021#issuecomment-285029233 are still problems.

**Comment by gkhanna79** [comment]
Assigning to @stephentoub who has a PR out for this.
