### ISSUE TITLE
ToTitleCase does not correctly titlecase Dutch words starting with IJ

### ISSUE THREAD

**Issue by warrantyvoids** [dotnet/coreclr#9981]
The current TextInfo.ToTitleCase() Locale specific function does not correctly titlecase Dutch words starting with IJ as specified by the Unicode Standard, introductory text of paragraph 3.13. 
• Titlecasing of IJ at the start of words in Dutch

An example of this would be ToTitleCase("ijzeren eigenschappen") -> "IJzeren Eigenschappen", although it currently leads to "Ijzeren Eigenschappen".

**Comment by tarekgh** [comment]
Issue moved to [dotnet/corefx #16770](https://github.com/dotnet/corefx/issues/16770) via [**ZenHub**](https://www.zenhub.com/)
